### ISSUE TITLE
Where should I put my dll after building from source?

### ISSUE THREAD

**Issue by Mabinogiysk** [apache/incubator-mxnet#10005]
## Description
I have built mxnet from source and I got error when I import mxnet in python:
```
D:\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
       347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
      349         else:
      350             self._handle = handle

OSError: [WinError 126] 找不到指定的模块。(can not find module)
```
I have used dumpbin.exe to check libmxnet.dll:
```
Dump of file .\libmxnet.dll

File Type: DLL

  Image has the following dependencies:

    libopenblas.dll
    opencv_world341.dll
    cublas64_80.dll
    cufft64_80.dll
    cusolver64_80.dll
    curand64_80.dll
    nvrtc64_80.dll
    nvcuda.dll
    KERNEL32.dll
    VCOMP140.DLL
```
I checked every directories in `$Path`. It seems that `opencv_world341.dll` and `libopenblas.dll` are missing. But I don't know where I should put them. I have tried directories such as `D:\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet`, `C:\Windows\system32` and restarted computer, but still got the same error.
Those are all directories in $Path and dependencies:
```
D:\Anaconda3\Library\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
cublas64_80.dll
cufft64_80.dll
curand64_80.dll
cusolver64_80.dll
nvrtc64_80.dll
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp
C:\Windows\system32
kernel32.dll
libopenblas.dll
nvcuda.dll
opencv_world341.dll
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
D:\UltraEdit
D:\CMake\bin
C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps
```
What should I do?

## Environment info (Required)
```
----------Python Info----------
Version      : 3.6.4
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('default', 'Jan 16 2018 10:22:32')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : D:\Anaconda3\lib\site-packages\pip
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.15063-SP0
system       : Windows
node         : DESKTOP-G2Q55BC
release      : 10
version      : 10.0.15063
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Name
Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz

```

Package used (Python/R/Scala/Julia):
I'm using Python

## Build info (Required if built from source)
Compiler: visual studio 2015

## Error Message:
```
OSError                                   Traceback (most recent call last)
<ipython-input-1-1eadd2d362f9> in <module>()
----> 1 import mxnet

D:\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\__init__.py in <module>()
     23 
     24 from .context import Context, current_context, cpu, gpu
---> 25 from . import engine
     26 from .base import MXNetError
     27 from . import base

D:\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\engine.py in <module>()
     21 
     22 import ctypes
---> 23 from .base import _LIB, check_call
     24 
     25 

D:\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\base.py in <module>()
    111 __version__ = libinfo.__version__
    112 # library instance of mxnet
--> 113 _LIB = _load_lib()
    114 
    115 # type definitions

D:\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\base.py in _load_lib()
    103     """Load library by searching possible path."""
    104     lib_path = libinfo.find_lib_path()
--> 105     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
    106     # DMatrix functions
    107     lib.MXGetLastError.restype = ctypes.c_char_p

D:\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: [WinError 126] 找不到指定的模块。
```
dumpbin.exe -headers .\libmxnet.dll
```
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file .\libmxnet.dll
PE signature found

File Type: DLL

FILE HEADER VALUES
            8664 machine (x64)
                   A number of sections
   5A9E6D0A time date stamp Tue Mar  6 18:27:22 2018
                   0 file pointer to symbol table
                   0 number of symbols
                 F0 size of optional header
            2022 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
                   DLL
```

**Comment by Mabinogiysk** [comment]
I have checked the dependency of `libopenblas.dll` and `opencv_world341.dll`.  Only `libgfortran-3.dll` is missing. I copy it from `caffe` and put it into `C:\Windows\System32`. But nothing changed.

**Comment by Mabinogiysk** [comment]
I used `MS Process Monitor` tool to monitor the python process while I was importing `mxnet`. I searched the whole information and extract the items whose "Path" is a `dll` and "RESULT" is “SUCCESS”.
It seems all dependencies of `libopenblas.dll`, `opencv_world341.dll` and `libmxnet.dll` are loading successfully.

**Comment by xinyu-intel** [comment]
@marcoabreu @cjolivier01 I follow the [doc](https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md) and come across the same problem.

**Comment by cjolivier01** [comment]
run depends:  http://www.dependencywalker.com
it should show you exactly which dependency is missing.

**Comment by xinyu-intel** [comment]
Fortunately, I find the missing deps, thanks! @cjolivier01 

- libgcc_s_seh-1.dll
- libgfortran-3.dll
- libquadmath-0.dll

**Comment by cjolivier01** [comment]
did you compile with gcc on Windows? or some other fall requires that? those seem strange for window

**Comment by xinyu-intel** [comment]
@cjolivier01 Also a bit confused for me. I just followed the instruction [windows_setup](https://mxnet.incubator.apache.org/install/windows_setup.html) on a brand newly installed windows 10 and got this problem. I also reference this issue [#1740](https://github.com/apache/incubator-mxnet/issues/1740) and resolve it.

**Comment by cjolivier01** [comment]
Oh, where did you get that openblas?

**Comment by cjolivier01** [comment]
oh ok. yeah, probably that should be in the instructions somewhere.  does that openblas from the link *come with* those dll's?

**Comment by xinyu-intel** [comment]
No，I find these files somewhere else.

**Comment by cjolivier01** [comment]
ok yeah that's screwed up. Thanks for root-causing this!

**Comment by cjolivier01** [comment]
Ok, I see that's the mingw64_dll.zip downloa on that web site along with the openblas zips.

**Comment by xinyu-intel** [comment]
Ok，I missed it. I think it is necessary to remind users to download and setup this file.

**Comment by cjolivier01** [comment]
yeah, seems like it would be better to compile that with msvc
Closing this issue, please feel free to submit a doc update for that
