### ISSUE TITLE
How to visualise filters of MXNet model?

### ISSUE THREAD

**Issue by lixiangchun** [apache/incubator-mxnet#10006]
How to visualise filters of MXNet model like what has been done in keras - [https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html](https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html)?

**Comment by reminisce** [comment]
Thanks for the reference. We have been working on enabling visualization of MXNet data in the TensorBoard. You can see the design proposal here: https://cwiki.apache.org/confluence/display/MXNET/Logging+MXNet+Data+for+Visualization+in+TensorBoard

After the PR is merged, this might be a good tutorial to write about how to use the visualization tool in MXNet.

**Comment by feevos** [comment]
Hi this solution applies to the gluon framework. I am not sure if you want to visualize the weights or the output of the convolution for some input (the latter is what I usually do). 

Assuming you have a model, in the ```forward``` call you can return more than the last layer and visualize them: 

```Python
%pylab inline

import mxnet as mx
from mxnet import gluon, nd

class tNet(gluon.nn.HybridBlock):
    
    def __init__(self,**kwards):
        gluon.nn.HybridBlock.__init__(self,**kwards)
        
        with self.name_scope():
            
            self.layer1 = gluon.nn.Conv2D(12,kernel_size=3,padding=1)
            self.layer2 = gluon.nn.Conv2D(12,kernel_size=3,padding=1)
            
    def hybrid_forward(self,F,_input):
        
        out1 = self.layer1(_input)
        out2 = self.layer2(out1)
        
        return out1, out2
```

```Python
mynet = tNet()
mynet.initialize(mx.init.Xavier())
xx = nd.random_uniform(shape=[4,12,128,128])
out1, out2 = mynet(xx)
imshow(out1[0,0].asnumpy())
```
this produces the following image: 
![image](https://user-images.githubusercontent.com/14290519/37761966-1781ea28-2df6-11e8-936d-2bd0726b1441.png)


Now say you want to visualize the weights only of a layer, without the convolution. For example you can obtain the weights of self.layer2 or self.layer1 like this: 

```Python
layer2_weight = mynet.layer2.weight.data() # This is an NDArray object
```

```Python
mynet.layer2.weight.data().shape 
# prints (12,12,3,3) for this particular example. 
```
so you can create histograms etc. Hope this helps.

**Comment by reminisce** [comment]
We have open-sourced [MXBoard](https://github.com/awslabs/mxboard) which enables users to visualize MXNet data (including network structures) in [TensorBoard](https://pypi.python.org/pypi/tensorboard). In your case, you can just simply pass the weights/filters to the logging API and view it in TensorBoard.

The current version on PyPI is [0.1.0rc3](https://pypi.python.org/pypi?:action=display&name=mxboard&version=0.1.0rc3). You can either install from source or `pip install`. The GitHub site has rich examples and tutorials on installation and how to use it in MXNet. Could you try it and give us feedbacks? Thanks.

**Comment by thomelane** [comment]
@sandeep-krishnamurthy good answer on this, so good to close. thanks!
