### ISSUE TITLE
C++ API Documentation and Tutorial

### ISSUE THREAD

**Issue by ahkarami** [apache/incubator-mxnet#10003]
Thanks the MXNet team for releasing the framework. However, I think its current documentation for C++ API is not complete (_e.g._, How to install MXNet C++ API, Use MXNet in C++, etc.). Has the team any plan to add documentation or offers any tutorial (_e.g.,_ like the fantastic tutorials for _Gluon_) in the near future?

**Comment by ivshli** [comment]
Hi,
Does this request is in process? I still can't find intuitive example or doc about c++

Thanks

**Comment by leleamol** [comment]
Hello @ahkarami please refer to README Files in [cpp-package] (https://github.com/apache/incubator-mxnet/blob/master/cpp-package/README.md) and [cpp-package/example] (https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/README.md) folders.

Also, the C++ documentation on [mxnet website](https://mxnet.incubator.apache.org/api/c++/index.html)  is up-to-date.  The documentation for classes in mxnet::cpp namespace can be found [here](https://mxnet.incubator.apache.org/versions/master/doxygen/namespacemxnet_1_1cpp.html)

I hope this helps.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by ahkarami** [comment]
Dear @leleamol,
Thank you very much for your nice attempts. I think the MXNet C++ API has improved, but adding more comprehensive examples and tutorials would be helpful.

**Comment by ahkarami** [comment]
Thanks @leleamol,
I agree with you there. I think it is better to close this issue in this state.

**Comment by leleamol** [comment]
@mxnet-label-bot Can we close this issue as per the last comment?
