### ISSUE TITLE
[Bug] There are two broken links on the top level README.md file which point to the old CI

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#10012]
The top level README.md has two links to logos that point to builds.apache.org which is now deprecated. These must point to the new CI
This should be fixed similar to this PR - https://github.com/apache/incubator-mxnet/pull/9908

**Comment by indhub** [comment]
I think these icons were coming from this plugin: https://wiki.jenkins.io/display/JENKINS/Embeddable+Build+Status+Plugin

@marcoabreu Do you know if the new CI has this plugin? If not, what is the effort involved in installing it?

**Comment by marcoabreu** [comment]
@indhub there you go: http://jenkins.mxnet-ci.amazon-ml.com/job/incubator-mxnet/job/master/badge/

**Comment by indhub** [comment]
Thanks, I'll create the PR.

**Comment by marcoabreu** [comment]
Thanks a lot!

**Comment by anirudh2290** [comment]
@indhub can this be closed ?

**Comment by indhub** [comment]
Yes. This is fixed.
