### ISSUE TITLE
MxNet hangs up during bind.

### ISSUE THREAD

**Issue by kandoiNikhil** [apache/incubator-mxnet#10016]
## DataParallelExecutorGroup hangs  

This is a copy of the resolved issue. See [this](https://github.com/apache/incubator-mxnet/issues/6325)
When setting gpu as the context, the above mentioned function takes a very long time to return.
It is currently taking 9 minutes for this function to return and it happens every time.

I am currently using the BucketingModule and the relevant code looks like this
```python
self.ctx = mx.gpu(int(gpu_ordinal)) # gpu_ordinal is the ordinal value of the gpu
self.provide_data = [('data', (self.batch_size, self.default_bucket_key))]
self.provide_label = [('softmax_label', (self.batch_size, self.default_bucket_key))]     
model=mx.mod.BucketingModule(sym_gen=sym_gen,default_bucket_key=max(self.buckets),context=self.ctx)  #sym_gen refers to a function that generates the symbol   
model.bind(self.provide_data, self.provide_label, for_training=False)
```

### Diagnostic info
----------Python Info----------
Version      : 3.6.0
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Mar  5 2018 18:57:22')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/ubuntu/.pyenv/versions/python3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.1.0
Directory    : /home/ubuntu/.pyenv/versions/python3/lib/python3.6/site-packages/mxnet
Commit Hash   : 07a83a0325a3d782513a04f47d711710972cb144
----------System Info----------
Platform     : Linux-4.4.0-1049-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-80-133
release      : 4.4.0-1049-aws
version      : #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2699.714
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.05
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0017 sec, LOAD: 0.6100 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0631 sec, LOAD: 0.0172 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1353 sec, LOAD: 0.3825 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0268 sec, LOAD: 0.1850 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0026 sec, LOAD: 0.0223 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0031 sec, LOAD: 0.0169 sec.

## Build info (Required if built from source)

Did not build it MxNEt from source. Did a 
`pip install mxnet`

## Error Message:
There is no error message.

## Ask
Guidance on how to debug and resolve this

**Comment by sxjscience** [comment]
Hi @kandoiNikhil , what kind of GPU are you using? Sometimes it's due to the JIT compilation. You can cache the result of the JIT compilation following the guide in https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/. For example, you may set `CUDA_CACHE_MAXSIZE` to a large value and set `CUDA_CACHE_PATH` to a position that contains enough storage.

**Comment by Ishitori** [comment]
@kandoiNikhil, did you find the reason? 

if you don't have this problem anymore, can you please close the ticket?

**Comment by kalyc** [comment]
@kandoiNikhil could you update/close this issue?

**Comment by kandoiNikhil** [comment]
I never found out the reason for it, closing as there is no more action needed here.
