### ISSUE TITLE
When doing the distributed training, the bandwidth becomes the bottleneck.

### ISSUE THREAD

**Issue by GoodJoey** [apache/incubator-mxnet#10017]
is there any experience/magic solutions  when using mxnet to do distribute training?
say, is there any method, force the worker communicates with the parameter server on the same node to save the bandwidth? or something like ring-allreduce(horovod)?

**Comment by huyangc** [comment]
You could try the gradient compression first. It is more easier.

**Comment by sandeep-krishnamurthy** [comment]
@rahul003

**Comment by rahul003** [comment]
What kind of a network are you training?

**Comment by GoodJoey** [comment]
such as ResNet-101.
when you got a lot of data to process, you need to do data parallel using distributed training to save time.
