### ISSUE TITLE
How can I build C++ package?

### ISSUE THREAD

**Issue by Mabinogiysk** [apache/incubator-mxnet#10020]
I can not find anything about installing mxnet for C++. 
The tutorials about [C++](https://mxnet.incubator.apache.org/tutorials/c++/basics.html) mentions ["building the C++ package"](https://mxnet.incubator.apache.org/get_started/build_from_source.html#build-the-c++-package), but the page can not open.
I wonder is there anyway to build mxnet C++ package?

**Comment by edmBernard** [comment]
You can use this parameter when you run your make command :
`USE_CPP_PACKAGE=1`

**Comment by marcoabreu** [comment]
@aaronmarkham see comment about website

**Comment by aaronmarkham** [comment]
Hi @Mabinogiysk did #12388 fix this for you? If so, can you close this?
There's this page now: https://mxnet.incubator.apache.org/install/c_plus_plus.html
