### ISSUE TITLE
Who can help me solve this error？（batch_loss.backward()  error）

### ISSUE THREAD

**Issue by kenjewu** [apache/incubator-mxnet#10035]
![1](https://user-images.githubusercontent.com/27672489/37154435-f93cd144-231a-11e8-8177-ee7a57f30f54.jpg)
![2](https://user-images.githubusercontent.com/27672489/37154437-f98051bc-231a-11e8-91d3-9c392b0c57eb.jpg)
![3](https://user-images.githubusercontent.com/27672489/37154438-f9c46014-231a-11e8-9104-81a5d7675031.jpg)
![4](https://user-images.githubusercontent.com/27672489/37154439-fa0959ee-231a-11e8-90bf-ec5389f07c3f.jpg)
![5](https://user-images.githubusercontent.com/27672489/37154440-fa5028c4-231a-11e8-846d-4fc610976608.jpg)

I just started using mxnet, and I'm not sure what the error is.Please help me.

**Comment by sxjscience** [comment]
The for-loop here should be the problem
```python
for step in range(...):
   ...
```
We can revise it to be a single phrase, i.e,
```python
batch_loss = nd.mean(softmax_cross_entropy(logits, one_hot_label))
```
If you still cannot solve it, you can post the codes here (instead of images) and I will help you debug.

**Comment by sxjscience** [comment]
@kenjewu May I know the status of this question?

**Comment by vishaalkapoor** [comment]
@kenjewu Would you mind pasting the code you are using as sxjscience has requested?
