### ISSUE TITLE
How can I use im2rec.py to generate .bin files?

### ISSUE THREAD

**Issue by mongoose54** [apache/incubator-mxnet#10044]
I have modified `im2rec.py` to be more flexible with various image manipulations? However I see that `im2rec.py` is not generating .bin files like `bin/im2rec` does. So how can I modify `im2rec.py` to generate .bin files of images? Or is it just a wish-list feature to have?

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask questions on usage at https://discuss.mxnet.io/
