### ISSUE TITLE
Reduce operators do not support axis=None

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#10041]
The sum/mean OPs do not support `axis=None`. I think it's supported in earlier versions of MXNet. This behavior is inconsistent with Numpy.

```python
import mxnet as mx
b = mx.nd.sum(mx.ones((100, 100)), axis=None)
```

```log
MXNetError: Invalid Parameter format for axis expect Shape(tuple) but value='None'
```

**Comment by anirudh2290** [comment]
This doesn't seem to be specific to sum/mean ops as I was also able to reproduce it with prod. Which version of MXNet supported this ? I wasn't able to reproduce with 0.11.

**Comment by sxjscience** [comment]
Should be some very old version (way before 0.11). We need to consider to revise the code to support this now.

**Comment by eric-haibin-lin** [comment]
`b = mx.nd.sum(mx.nd.ones((100, 100))`  will work.. I guess the problem is that if user provides axis=None, it won't work. @sxjscience

**Comment by sxjscience** [comment]
`None` should represent "empty-axis" and should perform a global reduction. It's very common in numpy.

**Comment by eric-haibin-lin** [comment]
https://github.com/apache/incubator-mxnet/pull/10405

**Comment by eric-haibin-lin** [comment]
fixed
