### ISSUE TITLE
Building MxNet on Win10 with CPP package, CUDA9 and MKL 2018

### ISSUE THREAD

**Issue by EternalSaga** [apache/incubator-mxnet#10049]
## Description
I'm trying to build mxnet on win10 with cpp package. After some hard efforts, I built the libmxnet.dll successfully. But I cannot generate the op.h file through the python script OpWrapperGenerator.py.
Python tells me that some unknown modules cannot be found when generating the op.h header file. Perhaps it is resulted by the MKL path, but I have no idea how to fix it.

## Environment info (Required)
Win10
VS2015
MKL2018
CUDA9
CUDNN7
python3.6

##Diagnose Information
----------Python Info----------
Version      : 3.6.4
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('v3.6.4:d48eceb', 'Dec 19 2017 06:54:40')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : C:\Program Files\Python36\lib\site-packages\pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Windows-10-10.0.16299-SP0
system       : Windows
node         : DESKTOP-TE2BP5I
release      : 10
version      : 10.0.16299
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Name
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0792 sec, LOAD: 1.6584 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3294 sec, LOAD: 1.9067 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, The read operation timed out, DNS finished in 0.544719934463501 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1333 sec, LOAD: 1.2828 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0939 sec, LOAD: 6.4636 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0620 sec, LOAD: 14.4082 sec.

Package used (Python/R/Scala/Julia):
(I'm using ...)
I want to use mxnet through C++.

## Build info (Required if built from source)
![mxnetbuilt](https://user-images.githubusercontent.com/15174504/37193376-838efed8-23a4-11e8-96bd-7bd592041823.PNG)

Compiler (gcc/clang/mingw/visual studio):
visual studio
MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
When this command is running, this message shows.
python OpWrapperGenerator.py D:/Program
mingAndStudy/cpp library/mxnet/build/Release/libmxnet.dll
Traceback (most recent call last):
  File "OpWrapperGenerator.py", line 425, in <module>
    raise(e)
  File "OpWrapperGenerator.py", line 419, in <module>
    f.write(patternStr % ParseAllOps())
  File "OpWrapperGenerator.py", line 314, in ParseAllOps
    cdll.libmxnet = cdll.LoadLibrary(sys.argv[1])
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce

After building the libmxnet.dll with mkl, cd to the folder incubator-mxnet\cpp-package\scripts,
run 
python OpWrapperGenerator.py path_to_the_libmxnet.dll

## What have you tried to solve it?

I tried to add opencv/build/bin/x64 and mkl/lib/intel_64_win to environment varialbes PATH.
Obviously it is useless becasue intel has not provided any shared library for mkl. <--------- This is wrong.

## Additional Efforts
After building the libmxnet.dll, I tried to install it for python. The installation is successful, but when I import the mxnet package, there is a similar error for python install.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yueji\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\__init__.py", line 25, in <module>
    from . import engine
  File "C:\Users\yueji\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "C:\Users\yueji\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\base.py", line 113, in <module>
    _LIB = _load_lib()
  File "C:\Users\yueji\Anaconda3\lib\site-packages\mxnet-1.2.0-py3.6.egg\mxnet\base.py", line 105, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Users\yueji\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by EternalSaga** [comment]
@sandeep-krishnamurthy Could you please tell me what's the unclear error/doc mean? Do I need to add more information?

**Comment by EternalSaga** [comment]
OK, finally I found the solution.
## Solution
First, use your dumpbin tool along with your msvc to check the dll dependence.
    dumpbin /dependents libmxnet.dll
    mkl_rt.dll
    libiomp5md.dll
    opencv_world341.dll
    cudnn64_7.dll
    cublas64_90.dll
    cufft64_90.dll
    cusolver64_90.dll
    curand64_90.dll
    nvrtc64_90.dll
    nvcuda.dll
    KERNEL32.dll
Put the three dlls, mkl_rt.dll, libiomp5md.dll, opencv_world341.dll with python.exe together. And then this problem could be solved. mkl_rt and libiomp should be located in your directory IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win

**Comment by jinhuang415** [comment]
@EternalSaga Besides put all .dll at the same directory, would you also check if this issue could be resolved if we add the actual path of mkl_rt.dll, libiomp5md.dll, opencv_world341.dll to the windows PATH variable? (see https://msdn.microsoft.com/en-us/library/7d83bc18.aspx for windows search dll order)

**Comment by sad-** [comment]
@sandeep-krishnamurthy could we close this issue. user seems to have resolved it.

**Comment by EternalSaga** [comment]
Yes, this issue could be closed.

**Comment by withmch** [comment]
@EternalSaga hello! I have met the same problem，after  building the mxnet from mxnet-source-code with VS2015，the mxnet-cpp file didn't generated the op.h.  when I found out the linked DLL files of libmxnet.dll and put this DLLs into the same file with python.exe,the problem still didnt solved,there wasn't op.h. Please could you tell how to solve the problem?

**Comment by YCAyca** [comment]
Hi! I met with the same error and I did all the things that I read on blogs. Finally I downloaded all the missing dll files (found them typing dumpbin /dependents libmxnet.dll). Then the error message changed and  now I'm getting this error :  OSError: [WinError 193] %1 is not a valid Win32 application 
Is there someone who know how to solve this error? I'm usin VS 2017 on Windows 10 by the way
