### ISSUE TITLE
Nondeterministic order of data in a data batch from NDArrayIter

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#10051]
With the following code:
```
ones = mx.nd.ones((10,10))
zeros = mx.nd.zeros((10,10))
data_iter = mx.io.NDArrayIter({'ones': ones, 'zeros': zeros})
for batch in data_iter:
    first = batch.data[0]
    second = batch.data[1]
    print(first)
    exit()
```
With python3 each time I run the above code, the result is different. A user won't be able to tell whether batch.data[0] is ones or zeros. 

This is caused by non-deterministic order of dict iterator in python3. Maybe we can fix it by update this line: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/io.py#L518

**Comment by pulkitmaloo** [comment]
Can I work on this?

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [Bug]

**Comment by anirudhacharya** [comment]
I was able to run the below code snippet for 100 runs without any errors. Maybe we can close this issue.

```python
import mxnet as mx
import numpy as np

ones = mx.nd.ones((10,10))
zeros = mx.nd.zeros((10,10))
data_iter = mx.io.NDArrayIter({'ones': ones, 'zeros': zeros})
for i in range(100):
    for batch in data_iter:
        first = batch.data[0]
        second = batch.data[1]
        assert first.asnumpy().all() == ones.asnumpy().all()
        assert second.asnumpy().all() == zeros.asnumpy().all()
```

**Comment by anirudhacharya** [comment]
I was able to run the above in python3. @eric-haibin-lin Could you please check if this is still an issue.

**Comment by eric-haibin-lin** [comment]
can you try python <=3.5? python 3.6+ should be fine

**Comment by anirudhacharya** [comment]
able to run with Python 3.5.2.

**Comment by anirudhacharya** [comment]
@eric-haibin-lin can this issue be closed?
