### ISSUE TITLE
Gluon Trainer causes OOM on multi GPU instance for more than 5 GPUs

### ISSUE THREAD

**Issue by orchidmajumder** [apache/incubator-mxnet#10059]
## Description
I am trying to run a CNN based network for text classification (written fully in Gluon) on a single machine multi GPU instance (P2.8XL). Training code works fine as long as number of GPUs don't cross 5. If I use 6 or more GPUs, the training process hangs and my SSH connection to the host gets killed. I don't see any `CudaMalloc failed` error but checking the `nvidia-smi` on a separate terminal shows that the GPU(0) memory goes really high just before this happens and this happens when Gluon Trainer tries to perform the `step`. This happens on both CUDA8 and CUDA9. I have not tested the issue on a P3.16XL or a P2.16XL, my experience is on a P2.8XL. 

## Environment info (Required)

```
----------Python Info----------
Version      : 3.5.2
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Nov 23 2017 16:37:01')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /usr/local/lib/python3.5/dist-packages/pip
----------MXNet Info-----------
Version      : 1.1.0
Directory    : /home/ubuntu/.local/lib/python3.5/site-packages/mxnet
Commit Hash   : 07a83a0325a3d782513a04f47d711710972cb144
----------System Info----------
Platform     : Linux-4.4.0-1052-aws-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : ip-172-31-37-14
release      : 4.4.0-1052-aws
version      : #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               1763.003
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.12
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single retpoline kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0032 sec, LOAD: 0.1134 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0089 sec, LOAD: 0.3352 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0143 sec, LOAD: 0.1261 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0090 sec, LOAD: 0.5626 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.2091 sec, LOAD: 0.0778 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.6427 sec, LOAD: 0.1379 sec.

```

Package used (Python):
 MXNet 1.1 

## Error Message:
No error message, the process gets killed and my SSH connection to EC2 gets terminated as well. 

## Minimum reproducible example

https://gist.github.com/orchidmajumder/f9ee584672f05f653e3c58f9ef30b83a - the line with `trainer.step(mini_batch_size)` is where the code gets stuck when using more than 5 GPUs.

## Steps to reproduce
Described above.

## What have you tried to solve it?

1. Change CUDA version from 9 to 8 - didn't work.
2. Ran with increasing number of GPUs. Worked till 5 and failed at 6. Previously was failing at 8 and running fine at 4.
2. Smaller batch size, lesser number of hidden dimensions, none seem to work.

**Comment by KellenSunderland** [comment]
Reproduced on another machine.

**Comment by sxjscience** [comment]
Seems to be related to https://discuss.gluon.ai/t/topic/5204

**Comment by cjolivier01** [comment]
^ ummm yeah... :)

**Comment by orchidmajumder** [comment]
Well well. I reorganized the code a bit to send it to you and just as a verification I ran it on a new P2.8x and I didn't see this problem. I am running some more training jobs on this instance to verify that.

**Comment by cjolivier01** [comment]
Ok let me know

**Comment by cjolivier01** [comment]
Do you know what changed?

**Comment by orchidmajumder** [comment]
I just changed the EC2 instance to a new instance. Last time, I tried with multiple instances (with both CUDA8 and 9) but all were giving me same problem. @KellenSunderland can you please spawn a new P2.8x instance (with CUDA9) and see if you can reproduce it now? I'd send you my code too.

**Comment by KellenSunderland** [comment]
I'll check when a coworker is back in the office, but please feel free to close without hearing back from me.

**Comment by orchidmajumder** [comment]
I have run multiple tests on the new P2.8x instance and things seem to work fine. I'll close this issue.
