### ISSUE TITLE
Documentation API or file

### ISSUE THREAD

**Issue by lutzroeder** [apache/incubator-mxnet#10063]
Is there an API or machine readable file to get documentation for the various operators (description, attributes, inputs and outputs) similar to `ops.txt` in TensorFlow or `onnx.defs.get_all_schemas_with_history()` in ONNX?

**Comment by nswamy** [comment]
We don't have all in one file, but are generated into md files here: https://github.com/nswamy/incubator-mxnet/tree/master/docs/api/python

**Comment by nswamy** [comment]
@lutzroeder 
We manage and answer user questions/how to's on https://discuss.mxnet.io/, please post this question there. I will close this issue.
