### ISSUE TITLE
Distributed Training (Permission denied)

### ISSUE THREAD

**Issue by Jeffery4000** [apache/incubator-mxnet#10070]
Hi, I am trying to run distributed training the example provided on 2 different node with the following internal IP address: 

```
user1@111.111.111.121
user2@111.111.111.122
```

I created a hosts file with the following ip, and ssh got no issue at all from one to other machine. When i launch the code:

```
python ../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_device_sync
```

And it prompt the following output at the same time:
```
user1@111.111.111.121's password: user1@111.111.111.121's password: user2@111.111.111.122's password: user2@111.111.111.122's password:
```

For both machine I'm using the same admin password, no matter how hard I try it just prom Permission denied, please try again.

It's there any way I can get debug message on what really happening behind the background?

**Comment by marcoabreu** [comment]
Have you tried using private-key based authentication instead of password based?

**Comment by Jeffery4000** [comment]
@marcoabreu Thank you for your prompt reply. 

I did try on this following guide but still doesn't work at all. As mention above, I'm able to ssh to each other without any issue. 
https://help.ubuntu.com/community/SSH/OpenSSH/Keys

**Comment by nswamy** [comment]
We manage and answer user questions/how to's on https://discuss.mxnet.io/, please post this question there. I will close this issue.
