### ISSUE TITLE
NaN in loss when using gluon ELU block

### ISSUE THREAD

**Issue by dmas-at-wiris** [apache/incubator-mxnet#10073]
I have a CNN that uses ELUs as activation function. When I use the gluon implementation (`F.where(x > 0, x, self._alpha * (F.exp(x) - 1.0))` from [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/nn/activations.py#L161)) I obtain NaN values in the loss after few epochs. 

However, if I create a block with this `F.LeakyReLU(x, act_type='elu', alpha)` the loss doesn't diverge.  Any idea?

I'll try to provide a minimal working example asap, if necessary.

**Comment by sxjscience** [comment]
Thanks for reporting this! It would be great if you could get an MWE.

**Comment by charlieyou** [comment]
@dmas-at-wiris 
Is this still an issue for you? If so, could you provide an MWE? Thanks!

**Comment by anirudh2290** [comment]
Since we didnt get a MWE can we close this ? @sxjscience
