### ISSUE TITLE
warpctc issues 

### ISSUE THREAD

**Issue by hsddlz** [apache/incubator-mxnet#10071]
FC = mx.sym.FullyConnected(data=x_3,flatten=False, num_hidden=n_class)
x = mx.sym.softmax(data=FC)

sm_label = mx.sym.Reshape(data=label, shape=(-1,))
sm_label = mx.sym.Cast(data = sm_label, dtype = ‘int32’)
sm = mx.sym.WarpCTC(data=x, label=sm_label, label_length =n_len ,
input_length =rnn_length )

my x layer's shape[(32L, 35L, 27L)] （bacthsize，input_lenth，n_class）
label的shape[(32L,21L)] (batchsize,label_lenth)
warpctc 
simple_bind error. Arguments:
data: (32, 1L, 32L, 286L)
label: (32, 21L)
Error in operator warpctc48: Shape inconsistent, Provided = [672], inferred shape=[0,1]
what can I do`````

**Comment by Ishitori** [comment]
I never worked with CTC, so I don't know for sure. But 672 is the shape of label you receive after the reshape, and WarpCTC expected to receive another shape based on initialization you provided.

I would double check the arguments of WarpCTC block and your actual values.
Also, have you checked this: https://github.com/apache/incubator-mxnet/tree/master/example/ctc ?

**Comment by lanking520** [comment]
@hsddlz are you still facing the same issue?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@hsddlz  Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment]
@mxnet-label-bot add [suggest-closed]
