### ISSUE TITLE
Ordering operators do not support kNullOp

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#10085]
When testing
```python
a = mx.sym.var("data", shape=(6,7,8))
adata= nd.random.uniform(shape=(6,7,8), ctx=mx.gpu(0))
_, inds = mx.sym.topk(a, axis=-1, k=5, ret_typ='both', is_ascend=False)
exe=inds.bind(mx.gpu(0), {'data':adata})
exe.forward()
```
It saids ``` src/operator/tensor/./ordering_op-inl.h:320: Check failed: req[0] == kWriteTo (0 vs. 1) TopK does not support inplace ``` @sxjscience

**Comment by sxjscience** [comment]
It's because the first argument is set as `_`, which gives `req[0]=kNullOp`. If you only needs the indices, a temporary workaround is to use `inds = mx.sym.topk(a, axis=-1, k=5, ret_typ='indices', is_ascend=False)`

**Comment by sxjscience** [comment]
The error also occurs in other ordering operators like Sort, ArgSort. https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/ordering_op-inl.h#L320-L321

**Comment by sxjscience** [comment]
@chinakook I'll fix it tomorrow.

**Comment by chinakook** [comment]
Yes, It's only support indices only. Thanks for your help!

**Comment by sxjscience** [comment]
@chinakook You can get both values using the following code:
```python
values, inds = mx.sym.topk(a, axis=-1, k=5, ret_typ='both', is_ascend=False)
exe=mx.sym.Group([values, inds]).bind(mx.gpu(0), {'data':adata})
exe.forward()
```
The problem is that the following is not supported:
```
_, inds = mx.sym.topk(a, axis=-1, k=5, ret_typ='both', is_ascend=False)
```

**Comment by chinakook** [comment]
@sxjscience thanks.

**Comment by sxjscience** [comment]
Sorry that I'm too busy with other stuffs. Can anyone help solve the bug? If not, I will solve it later.
