### ISSUE TITLE
R can not install, 404 Not Found

### ISSUE THREAD

**Issue by robbig2871** [apache/incubator-mxnet#10088]
> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
Installing package into ‘/usr/local/lib/R/3.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed

**Comment by marcoabreu** [comment]
Hello, MXNet 0.10.1 is a quite old version - the latest released version is 1.1. Would you mind explaining where you found the instructions to install that version and which commands you're running?

**Comment by haimeh** [comment]
These are the instructions from:
https://mxnet.incubator.apache.org/install/index.html
for Windows?, R, CPU installation 

Running those commands inside an R terminal produces the above output.
The binaries are indeed out of date.

@robbig2871 
If all you need is CPU version, you may try running:
install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)
#10038

**Comment by harshitajain1994** [comment]
Proposed labels: "Installation", "R"

**Comment by ankkhedia** [comment]
Hi @robbig2871 
The installation instruction works fine for me now. The binaries have been updated on official repo now. Could you please check if there still exists any issue and close the above issue if the instructions works fine for you.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please close this issue. It has been resolved.
