### ISSUE TITLE
how to install version of 0.9.3

### ISSUE THREAD

**Issue by gydlcc** [apache/incubator-mxnet#10102]

**Comment by mwbyeon** [comment]
https://github.com/apache/incubator-mxnet/releases/tag/v0.9.3

**Comment by gydlcc** [comment]
Thanks pretty much, i get it

**Comment by ankkhedia** [comment]
@gydlcc hope you got your query answered. Closing the issue. Feel free to reopen if closed in error.

@sandeep-krishnamurthy  Could you please close this issue
