### ISSUE TITLE
 error: 'kCPU' was not declared in this scope

### ISSUE THREAD

**Issue by sandipmgiri** [apache/incubator-mxnet#10100]
## Description
I'm trying to build Mxnet from 1.0.0 version , but for make command getting  `error: 'kCPU' was not declared in this scope` and build is failing (building successfully from master branch). However , 10-15 days ago the build was working fine for the same version i.e. 1.0.0.

## Environment info (Required)
Ubuntu 16.04

**Comment by TaoLv** [comment]
Try to update all submodules:
`git submodule update --recursive`

**Comment by sandipmgiri** [comment]
Thanks @TaoLv , After `git submodule update --recursive` the build is working fine.
