### ISSUE TITLE
Error occupied while using multi GPUs in some toy-ctc 

### ISSUE THREAD

**Issue by jj200789** [apache/incubator-mxnet#10107]
```
File "train.py", line 109, in Accuracy
    p.append(np.argmax(pred[k * BATCH_SIZE + i]))
IndexError: index 3840 is out of bounds for axis 0 with size 3840
```

It is fine when I use single GPU to run the toy-ctc. However, it shows the error message above when I try to use 4 GPU.
I used work_load_list to binding different batch size to each GPU but it still shows the same error message.

**Comment by szha** [comment]
were you able to determine the cause? A fix is most welcome!
