### ISSUE TITLE
Flaky test test_operator.test_layer_norm

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#10114]
## Description
Flaky test on Python3 CentOS 7 CPU for the test - test_operator.test_layer_norm.

It is a precision error.

Package used (Python/R/Scala/Julia):
Python

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/55/nodes/539/log/?start=0

## Error Message:

> ======================================================================
> FAIL: test_operator.test_layer_norm
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/work/mxnet/tests/python/unittest/test_operator.py", line 2454, in test_layer_norm
>     check_layer_normalization(in_shape, axis, eps)
>   File "/work/mxnet/tests/python/unittest/test_operator.py", line 2447, in check_layer_normalization
>     numeric_eps=1e-2, rtol=1e-2, atol=1e-3)
>   File "/work/mxnet/python/mxnet/test_utils.py", line 914, in check_numeric_gradient
>     ("NUMERICAL_%s"%name, "BACKWARD_%s"%name))
>   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
>     raise AssertionError(msg)
> AssertionError: 
> Items are not equal:
> Error 2.076643 exceeds tolerance rtol=0.010000, atol=0.001000.  Location of maximum error:(2, 1), a=-0.125115, b=-0.120535
>  NUMERICAL_data: array([[  0.8566879 ,  -0.49894154,  -4.4152503 ,   0.96982235,
>           3.0874987 ],
>        [  0.29245764,  -0.5665615 ,   0.05407035,  -0.4792601 ,...
>  BACKWARD_data: array([[  0.8567169 ,  -0.49888498,  -4.415254  ,   0.96985155,
>           3.087571  ],
>        [  0.29247206,  -0.56657815,   0.05407186,  -0.47925493,...

## Minimum reproducible example
Test is flaky and does not fail consistently.

**Comment by szha** [comment]
@sxjscience

**Comment by marcoabreu** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/483/pipeline

Python3: MKLDNN-CPU


```
======================================================================

FAIL: test_operator.test_layer_norm

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 2454, in test_layer_norm

    check_layer_normalization(in_shape, axis, eps)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 2447, in check_layer_normalization

    numeric_eps=1e-2, rtol=1e-2, atol=1e-3)

  File "/work/mxnet/python/mxnet/test_utils.py", line 914, in check_numeric_gradient

    ("NUMERICAL_%s"%name, "BACKWARD_%s"%name))

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.212738 exceeds tolerance rtol=0.010000, atol=0.001000.  Location of maximum error:(6, 5, 4), a=0.119209, b=0.121900

 NUMERICAL_data: array([[[ 1.2661703 , -0.71018636, -0.28001815,  0.00057742,

         -0.2766095 ],

        [ 2.9813983 , -0.5906479 , -0.8526521 ,  0.59243345,...

 BACKWARD_data: array([[[ 1.2661902 , -0.71017504, -0.28003502,  0.00061297,

         -0.27659297],

        [ 2.9814198 , -0.59063536, -0.8526358 ,  0.59245   ,...



----------------------------------------------------------------------

```
