### ISSUE TITLE
Bug: A typo in src/operator/swapaxis-inl.h

### ISSUE THREAD

**Issue by devymex** [apache/incubator-mxnet#10119]
https://github.com/apache/incubator-mxnet/blob/f7fa49e3068ab30a7379bbce1b288bf285fe5cde/src/operator/swapaxis-inl.h#L113
should be:
`TBlob data_out = out_data[cvmatdataenum::kOut];`

**Comment by szha** [comment]
Why do you think so?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please tag the issue as Pending Requester Information

**Comment by piyushghai** [comment]
@devymex Why do you think the swapaxisenum::kData should be changed to cvmatdataenum::kOut ? 
Can you provide an example as well ? 
Thanks!

**Comment by yzhliu** [comment]
Close due to no response, Please feel free to reopen this issue if you found this issue has not been solved.
