### ISSUE TITLE
Shared library dependent on mxnet

### ISSUE THREAD

**Issue by pokachopotun** [apache/incubator-mxnet#10128]
## Description
Segmentation fault happens when shared library dependent on mxnet_static is loaded with dlopen.

## Environment info (Required)
----------Python Info----------
Version      : 3.6.0
Compiler     : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
Build        : ('default', 'Dec 23 2016 12:22:00')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/denis/anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-4.4.0-53-generic-x86_64-with-debian-stretch-sid
system       : Linux
node         : denis-work
release      : 4.4.0-53-generic
version      : #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Stepping:              9
CPU MHz:               800.000
CPU max MHz:           3601,0000
CPU min MHz:           800,0000                                                                                                                                                                           
BogoMIPS:              7200.65                                                                                                                                                                            
Virtualization:        VT-x                                                                                                                                                                               
L1d cache:             32K                                                                                                                                                                                
L1i cache:             32K                                                                                                                                                                                
L2 cache:              256K                                                                                                                                                                               
L3 cache:              8192K                                                                                                                                                                              
NUMA node0 CPU(s):     0-7                                                                                                                                                                                
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp                                                                                                                             
----------Network Test----------                                                                                                                                                                          
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0939 sec, LOAD: 1.1907 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0642 sec, LOAD: 0.1381 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>, DNS finished in 0.2703831195831299 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0962 sec, LOAD: 0.9239 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0231 sec, LOAD: 0.2188 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0413 sec, LOAD: 0.2917 sec.

Package used: CPP

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
d511d98aeadf4392f8c4c1289d15feecdd98bf81

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
Segmentantion Fault
1 _dl_signal_error dl-error.c 106 0x7ffff7de7396 
2 _dl_open         dl-open.c  714 0x7ffff7dec03c 
3 dlopen_doit      dlopen.c   66  0x7ffff7bd3f09 
4 _dl_catch_error  dl-error.c 187 0x7ffff7de7564 
5 _dlerror_run     dlerror.c  163 0x7ffff7bd4571 
6 __dlopen         dlopen.c   87  0x7ffff7bd3fa1 
7 main             main.cpp   13  0x400d0d       

## Minimum reproducible example

//main.cpp
#include <iostream>
#include <dlfcn.h>
#include <cstdint>
using namespace std;
int main(){
	void (*test)(void);
        void* mylib = dlopen("./liblibexample.so", RTLD_LAZY);
	return 0;
}

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1. 
2.

**Comment by lebeg** [comment]
Can you provide more information on liblibexample.so? How does it depend on mxnet?

**Comment by pokachopotun** [comment]
I hope this would be enough.
//CMakeLists.txt
project(test)
if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)
if(NOT MSVC)
  set(UNITTEST_STATIC_LINK ON)
endif()
set(CPP_EXAMPLE_LIBS
  ${BEGIN_WHOLE_ARCHIVE} mxnet_static ${END_WHOLE_ARCHIVE}
  ${BEGIN_WHOLE_ARCHIVE} dmlc ${END_WHOLE_ARCHIVE}
  ${mxnet_LINKER_LIBS}
 )
add_definitions(-lpthread -std=c++11)
add_library(libexample SHARED lib.h lib.cpp)
target_link_libraries(libexample ${CPP_EXAMPLE_LIBS} pthread)
add_executable(test main.cpp)
target_link_libraries( test libexample dl )

**Comment by pokachopotun** [comment]
The issue was resolved.
Our code executes correctly, if it was compliled as a part of mxnet project tree.
In particular, we added the following lines to incubator-mxnet/cpp-package/example/CMakeLists.txt.

add_library(libexample SHARED test/lib.h test/lib.cpp)
target_link_libraries(libexample ${CPP_EXAMPLE_LIBS})
add_dependencies(libexample ${CPPEX_DEPS})
add_executable(mxnetserver_test test/main.cpp)
target_link_libraries(mxnetserver_test dl)
