### ISSUE TITLE
Change a block

### ISSUE THREAD

**Issue by kazizzad** [apache/incubator-mxnet#10126]
Hi, 
I am trying to implement the following work
https://openreview.net/pdf?id=B1QRgziT-
It has the tensor flow, chainer, and pytorch implementation, but I could not find gluon version of it.
It requires changing the structure of the layers. (sample code for pytorch  https://github.com/godisboy/SN-GAN/blob/master/src/snlayers/snconv2d.py)

Can you help me to design such block in gluon?
This page http://gluon.mxnet.io/chapter03_deep-neural-networks/custom-layer.html
shows how to build a new layer, but not modifying the existing one.

**Comment by kice** [comment]
Here is my implementation for SN-GAN.
```
class SNConv2D(nn.Conv2D):
    def __init__(self, channels, in_channels, Ip=1, **kwargs): 
        super(SNConv2D, self).__init__(channels=channels, in_channels=in_channels, **kwargs)
        with self.name_scope():
            self.u = self.params.get('u', shape=(1, channels),
                                     init=mx.initializer.Normal(sigma=1.0),
                                     allow_deferred_init=False, 
                                     grad_req='null', lr_mult=0.0)
            self.Ip = Ip
            
    def update_u(self):
        w = self.weight.data()
        u = self.u.data()
        
        _, _u = self.w_bar(nd, w, u)
        self.u.set_data(_u)
                
    def max_singular_value(self, F, W, u, Ip=1):
        """
        power iteration for weight parameter
        """
        if not Ip >= 1:
            raise ValueError("Power iteration should be a positive integer")

        _u = u

        for _ in range(Ip):
            _v = F.L2Normalization(F.dot(_u, W), eps=1e-12)
            _u = F.L2Normalization(F.dot(_v, F.transpose(W)), eps=1e-12)
        
        sigma = F.sum(F.dot(_u, W) * _v)
        return sigma, _u
                
    def w_bar(self, F, weight, u):
        """
        Spectrally Normalized Weight
        """
        w_mat = F.reshape(weight, (self._channels, -1))
        sigma, _u = self.max_singular_value(F, w_mat, u)

        return F.broadcast_div(weight, sigma), _u

    def hybrid_forward(self, F, x, u, weight, bias=None):
        weight, _ = self.w_bar(F, weight, u)
        return super(SNConv2D, self).hybrid_forward(F, x, weight, bias)
```
You need to call update_u() after updating the parameters. And it should work after calling hybridize().

```
losses = []
with autograd.record():
    for x, y in zip(data, label):
        z = net(x)
        l = loss(z, y)
        losses.append(l)

    autograd.backward(losses)
trainer.step(batch.data[0].shape[0])
net.update_u()
```

@piiswrong Would you like to give me some advice for my implementation? ( like making it no need to manually call update_u() every update or other better way to implement it)

P.S. @kazizzad  Can you change the title to something like "How to implement SN-GAN in gluon"?

**Comment by sandeep-krishnamurthy** [comment]
This question is very likely to get answered at - https://discuss.mxnet.io/

**Comment by ThomasDelteil** [comment]
@kazizzad does @kice's implementation solves your problem? 
@sandeep-krishnamurthy can you please close the issue.
@kazizzad if you want to follow up, please post your question on https://discuss.mxnet.io
