### ISSUE TITLE
__CUDACC__ seems not defined on non-jetbrains ide?

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#10143]
https://github.com/apache/incubator-mxnet/blob/67af47c889fb5f54cc2b512ab8b453ff5070a1cc/src/common/cuda_utils.h#L35
The "__JETBRAINS_IDE__" macro may cause some common ops dose not use CUDNN acceleration?

**Comment by chinakook** [comment]
Sorry, It may be an intellisense error of VS2017.

**Comment by fgrass** [comment]
Has the problem been solved?

**Comment by chinakook** [comment]
It's an error of VS2017. It's not solved.
