### ISSUE TITLE
Hi, is gloun supporting depthwise conv?

### ISSUE THREAD

**Issue by xmyqsh** [apache/incubator-mxnet#10142]
I dug into [gluon version's mobilenets](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/mobilenet.py), it seems that it doesn't use   [depthwise_convolution-inl.h](https://github.com/apache/incubator-mxnet/tree/master/src/operator/nn/depthwise_convolution-inl.h)

It seems that gloun has no api for [depthwise_convolution-inl.h](https://github.com/apache/incubator-mxnet/tree/master/src/operator/nn/depthwise_convolution-inl.h)

I'm a newbie, just have a check

**Comment by szha** [comment]
depthwise convolution is activated by specifying the number of groups to be equal to number of channels. It is used in mobilenet [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/mobilenet.py#L45)

**Comment by xmyqsh** [comment]
interesting
I will have a check

**Comment by xmyqsh** [comment]
@szha 
Indeed it is [} else if (param.num_filter == param.num_group &&](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/convolution.cu#L70)
