### ISSUE TITLE
Mxnet R Package Installation Doc Bug

### ISSUE THREAD

**Issue by harryprince** [apache/incubator-mxnet#10147]
Wrong:

```
# current repo doc:  https://github.com/apache/incubator-mxnet/tree/master/R-package
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet",dependencies = T)
```

Correct:
```
cran <- getOption("repos")
cran["dmlc"] <- "https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/"
options(repos = cran)
install.packages("mxnet",dependencies = T)
```

## Reference

https://stackoverflow.com/questions/43872455/mxnet-package-installation-in-r

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy  Could you please tag this as Documentation

**Comment by harryprince** [comment]
same issue like:
#10088 
#7985

**Comment by harryprince** [comment]
I summarise an installation example on GPU/linux in detail for Chinese users:
https://segmentfault.com/a/1190000013899075

**Comment by harryprince** [comment]
I recommend someone officially public a stable version mxnet package to CRAN, just like `pip install mxnet-cu80`, which can make installation and development easier.

**Comment by anirudhacharya** [comment]
This issue has been resolved in the latest master. @sandeep-krishnamurthy please close this issue.

@harryprince feel free to reopen if the problem persists.
