### ISSUE TITLE
Please help to provide mxnet 1.1.0 python package for Windows

### ISSUE THREAD

**Issue by PaulaQin** [apache/incubator-mxnet#10166]
Hi,
Would you please help to build latest version mxnet python package for Windows on PyPI? I want to run mxnet on my Windows machine. Thanks.

**Comment by Ishitori** [comment]
Hi, 

What kind of exception do you receive if you follow official installation instruction: https://mxnet.incubator.apache.org/install/index.html?platform=Windows&language=Python&processor=CPU&version=master  Please, notice of --pre flag. It would install you the latest version of mxnet (not a stable release). If you want a stable release, select version 1.2.0 in the dropdown.
