### ISSUE TITLE
CoreML tool, wrong mlmodelc file name for Inception-BN

### ISSUE THREAD

**Issue by Bathilde** [apache/incubator-mxnet#10171]
I am currently using the CoreML tool to transform my models to mlmodel files. The example perfectly work on my mac, I was able to develop a simple application using CoreML and a squeezenet model.

I have downloaded an Inception-BN model (from: http://data.dmlc.ml/mxnet/models/imagenet/inception-bn.tar.gz) and compiled the model with the tools without any error. When the mlmodel file is included in my xcode proj, the compilation works.

At runtime, the application crashes. It seems the model was not correctly build, the mlmodelc is not found.

The generated swift file specify the mlmodelc name "Inception_BN_1" but the real file name contains inside the bundle is "Inception-BN".

Is it your tool that define this name ? Do you know where I can update the mlmodelc file name (outside of the generated swift class file)

The model was build with the following command line:
`/usr/bin/python2.7  mxnet_coreml_converter.py --model-prefix='Inception-BN' --epoch=126 --input-shape='{"data":"3,224,224"}' --mode=classifier --pre-processing-arguments='{"image_input_names":"data"}' --class-labels synset.txt --output-file="Inception-BN.mlmodel"`

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy  Could you please label this issue as converter and bug

**Comment by piyushghai** [comment]
@apeforest Does your recent work on CoreML fixes address this as well ?

**Comment by apeforest** [comment]
@piyushghai I will take a look.

**Comment by apeforest** [comment]
@Bathilde I am not clear about your question. I have just run the command:
`python mxnet_coreml_converter.py --model-prefix='Inception-BN' --epoch=126 --input-shape='{"data":"3,224,224"}' --mode=classifier --pre-processing-arguments='{"image_input_names":"data"}' --class-labels synset.txt --output-file="Inception-BN.mlmodel"` and it seems to have generated the model Inception-BN.mlmodel for me. Could you be more specific on what the error you are encountering? Thanks

**Comment by Bathilde** [comment]
@apeforest , did you try to put your generated model in XCode ?

My issue was at the time it was inserted in an Xcode project and while I was running the application.
The mlmodelc has a filename specified and it was not the right one.

**Comment by lupesko** [comment]
@mxnet-label-bot please add label [CoreML]

**Comment by lupesko** [comment]
@mxnet-label-bot please remove label [Converter]

**Comment by Bathilde** [comment]
It seems with XCode 10 I don't have the issue anymore, I really don't know what happened since the name are generated by XCode.
Thank you for your time, I am closing the ticket
