### ISSUE TITLE
MXNet MKLDNN build dependency/flow discussion

### ISSUE THREAD

**Issue by jinhuang415** [apache/incubator-mxnet#10175]
Hi MXNet owners,

  This is Jin from Intel MXNet Shanghai team, we spent some time analyzing current MXNet make/cmake flow, especially the part related with MKLDNN and BLAS selection and full MKL/MKLML library link usage/dependency. We came out with a small summary slides mainly talk about below items:

(1) MKLDNN, full MKL, MKLML library relationship
(2) BLAS selection
(3) Our preferred MXNet Build Logic regarding full MKL/MKLML library
(4) Current build logic, issues, and potential improvements

  Please help to take at the slides and we can discuss for further comments. Thanks.

**Comment by jinhuang415** [comment]
[MXNet MKLDNN Build Dependency.pptx](https://github.com/apache/incubator-mxnet/files/1830084/MXNet.MKLDNN.Build.Dependency.pptx)

**Comment by marcoabreu** [comment]
Hello Jin, thanks a lot for looking into this! Would you mind creating a thread on dev@ to gain additional attention for this subject?

**Comment by pengzhao-intel** [comment]
@marcoabreu Thanks for the suggestion. I will do

**Comment by lebeg** [comment]
A great suggestion! I would wish that the build selection logic would be put into separate files, ie cmake find module and a Makefile include.

**Comment by rahul003** [comment]
Thanks for clarifying! Once we have finalized the building issues you mentioned, we should add appropriate documentation to mxnet.
