### ISSUE TITLE
Race condition when MKLDNN is enabled

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#10189]
When MKLDNN is enabled, the output of any MKLDNN op will have MKL layout. If such ndarray is passed to any operator registered with `FComputeEx` interface, calling `NDArray::data` will trigger "Reorder2Default" which may cause race condition since it doesn't prevent others from writing to it at the same time. 

The number of non-MKL ops registered with `FComputeEx` is over 50. This should be fixed and explicitly tested.

**Comment by zheng-da** [comment]
This potential race condition is very difficult to produce. It may happen if the output of an MKLDNN operator is used with a sparse array in an operator. The operator has to perform computation on these two arrays (an MKLDNN array and a sparse array) with FComputeEx. However, the current implementation of sparse operators doesn't support this case and fall back using FCompute.

**Comment by zheng-da** [comment]
@eric-haibin-lin i think you can close this issue now.

**Comment by eric-haibin-lin** [comment]
could you reference the PR?
