### ISSUE TITLE
Fail to install MXNet from source on Win10

### ISSUE THREAD

**Issue by jennyzhang0215** [apache/incubator-mxnet#10191]
I tried to install MXNet on my windows 10. 

I can compile it successfully using Visual Studio 2015.
![image](https://user-images.githubusercontent.com/7044477/37747461-54511a6e-2dba-11e8-88ba-4ee84e589098.png)
And mxnet.dll is in the ./build/Release/ 
![image](https://user-images.githubusercontent.com/7044477/37747570-d2a8d3b6-2dba-11e8-8e6b-dddae493c4eb.png)

However, when I try to import mxnet, it comes to an error.
![image](https://user-images.githubusercontent.com/7044477/37747492-719b7448-2dba-11e8-97eb-a9e0ec0803e1.png)

**Comment by jennyzhang0215** [comment]
I've fixed the bug. Maybe the installation page can add more information.

Other than 'Set the environment variable OpenCV_DIR to point to the OpenCV build directory.', we need to 'Add the OpenCV bin directory to the PATH environment variable.', like 
![image](https://user-images.githubusercontent.com/7044477/37750267-0f3e559c-2dc7-11e8-9f62-3d43446535e8.png)

**Comment by sxjscience** [comment]
@aaronmarkham Should I directly update https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md in order to change this?

**Comment by sxjscience** [comment]
@ankkhedia It should be better for us to directly create the PR. The users may be busy working on other projects.
