### ISSUE TITLE
Using MXNet in c++

### ISSUE THREAD

**Issue by aravindhv10** [apache/incubator-mxnet#10198]
Hello,

I wanted to use MXNet conv nets in c++, I tried to find build instructions for c++ and came across the page (http://mxnet.incubator.apache.org/tutorials/c%2B%2B/basics.html) with the link (https://mxnet.incubator.apache.org/get_started/build_from_source.html#build-the-c++-package) but this seems to be pointing to building MXNet with source for python instead (only CPU). But followed this anyway.

I was unable to build the cpp-example programs (I copied libmxnet.so and libmxnet.a) to the appropriate directories. Is there a place where I can find up to date instructions regarding c++ api of mxnet and how to use it ?

Thanks and Regards

**Comment by lebeg** [comment]
Unfortunately this is not that easy at the moment. What is the concrete failure you are facing with the build?

Btw. we have an ongoing design proposal for C++ API improvements: 

**MXNet C++ package improvements**
[JIRA](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75976112) or [GoogleDocs](https://docs.google.com/document/d/1Xi0aU9Nks7-GcsJIfcXoEpgPeYnSiEtBpJlhZvMaIb8/edit?usp=sharing)

Feel free to add your pain points or suggestions.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy  Could you please tag the issue as C++ and enhancement

**Comment by lebeg** [comment]
Yes, this [python script](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/scripts/OpWrapperGenerator.py) needs to be executed as part of [make](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/cpp-package.mk#L38) or [cmake](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/CMakeLists.txt#L13) to run throuh the compiled libmxnet.so binary and generate op.h which will be included in the project sources.

**Comment by aravindhv10** [comment]
ok thanks ! issue solved, with using USE_CPP_PACKAGE=1, the full make line I used is:
make -j "$(nproc)" 'USE_CPP_PACKAGE=1' 'USE_OPENCV=1' 'USE_BLAS=openblas' 'USE_GPERFTOOLS=1'
