### ISSUE TITLE
[Operator] Make sure the result of topk is sorted

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#10204]
Currently, the inner implementation of topk is to first sort and slice the first K elements, which will make the results (value/indices) sorted. However, this is not mentioned in the doc. We need to revise the doc + test accordingly.

**Comment by safrooze** [comment]
@sxjscience Are you going to send a PR for this fix? If not, I can take care of it.

**Comment by sxjscience** [comment]
I’ve submitted this PR https://github.com/apache/incubator-mxnet/issues/11031

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sxjscience** [comment]
I mean https://github.com/apache/incubator-mxnet/issues/11134

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by safrooze** [comment]
@sxjscience I don't see where in PR #11134 you update the doc for topk to mention that the result is sorted. Did I miss it in the diff or are you planning to add it later?

**Comment by thomelane** [comment]
See that it's now been added to https://github.com/apache/incubator-mxnet/pull/12250.
@sxjscience so looks like we're good to close this issue now then?

**Comment by sxjscience** [comment]
@thomelane Yes, it can be closed once #12250 is merged
