### ISSUE TITLE
[Operator] unravel_index and ravel_multi_index

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#10203]
As requested by @fhieber, we should consider to support [unravel_index](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.unravel_index.html) and it's inverse function [ravel_multi_index](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ravel_multi_index.html) in numpy. This feature is recently added to TF (https://github.com/tensorflow/tensorflow/pull/14895).

**Comment by asmushetzel** [comment]
working on it
