### ISSUE TITLE
Pytorch models inference by mxnet

### ISSUE THREAD

**Issue by qingyuanxingsi** [apache/incubator-mxnet#10219]
Is there any possibilities to export pytorch models to some format and make inference in C++ using mxnet??

**Comment by ashokei** [comment]
you could try with recent ONNX integration of mxnet.

**Comment by Ishitori** [comment]
@qingyuanxingsi, did you try the solution above? Did it help?

Here is the tutorial on how to export PyTorch model to ONNX: https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb

Here is the tutorial on how to import ONNX model to MXNet (python, but C++ should be similar): https://github.com/onnx/tutorials/blob/master/tutorials/OnnxMxnetImport.ipynb

**Comment by qingyuanxingsi** [comment]
@Ishitori I will give it a try recently!
