### ISSUE TITLE
Endless Clone when importing on PowerPC

### ISSUE THREAD

**Issue by Lucasyc** [apache/incubator-mxnet#10233]
Note: 
We are using ppc64le so we have to build from source. After all installation we try to import mxnet and then python shell get stuck. We looked into system trace and found that libmxnet.so is endlessly forking at some point and finally freeze CPU. We followed the building process exactly as what the documentation provided. 

## Environment info (Required)
ppc64le  GNU/Linux

## what to do.
```
1. install and build mxnet on a computer with ppc64le architecture and then build from source. (the build command is listed follow). 
2. open a python shell and run "import mxnet as mx", then it will get stuck. 
```

Package used (Python/R/Scala/Julia):
I'm using python

## Build info (Required if built from source)
make -j $(nproc) USE_OPENCV=0 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/mycudapath USE_CUDNN=1

Compiler (gcc/clang/mingw/visual studio):
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

MXNet commit hash:
7d0881036959f383bab7efa22a80a9caa419274c

Build config:
(Paste the content of config.mk, or the build command.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)
After build mxnet and install python dependency. 
Just start a python shell and run
```
import mxnet as mx
```
then the system hang. 

## Error Message:
You can observe the infinite fork in this system trace file. 
[trace.txt](https://github.com/apache/incubator-mxnet/files/1843960/trace.txt)

**Comment by abhinavs95** [comment]
@mxnet-label-bot update [Bug, Build, Python]

**Comment by karan6181** [comment]
@Lucasyc Could you please try to build MXNet from source again with the latest Master and see if the issue still persist? Thanks!

**Comment by karan6181** [comment]
@Lucasyc We are closing this issue for now due to inactivity from 90+ days. Please feel free to re-open it if you are still facing the issue. Thanks!

@nswamy Could you please close this issue? Thanks!
