### ISSUE TITLE
libomp.so is missing in Docker builds for armv6

### ISSUE THREAD

**Issue by msurguy** [apache/incubator-mxnet#10230]
## Description
After compiling and deploying MXNet to Raspberry Pi Zero using the new Docker builds, the `libomp.so` error prevents import of MXNet Python library.

More info about how the docker container output was installed is in https://github.com/apache/incubator-mxnet/commit/85215b6176ef3612d198f590268a6595b86565fb

## Environment info (Required)

```
----------Python Info----------
Version      : 3.4.2
Compiler     : GCC 4.9.1
Build        : ('default', 'Oct 19 2014 13:31:11')
Arch         : ('32bit', 'ELF')
------------Pip Info-----------
No corresponding pip install for current python.
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Linux-4.9.35+-armv6l-with-debian-8.0
system       : Linux
node         : raspberrypi
release      : 4.9.35+
version      : #1014 Fri Jun 30 14:34:49 BST 2017
----------Hardware Info----------
machine      : armv6l
processor    : 
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model name:            ARMv6-compatible processor rev 7 (v6l)
CPU max MHz:           1000.0000
CPU min MHz:           700.0000
----------Network Test----------
Setting timeout: 10
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0275 sec, LOAD: 0.3049 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0254 sec, LOAD: 0.2241 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0589 sec, LOAD: 0.2240 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1296 sec, LOAD: 0.1997 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 1.1327 sec, LOAD: 0.3586 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0214 sec, LOAD: 0.6467 sec
```

Package used (Python/R/Scala/Julia):
Python 3

## Build info (Required if built from source)

Built using Docker containers: https://github.com/apache/incubator-mxnet/tree/master/ci

## Error Message:
```shell
$ python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.4/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/pi/.local/lib/python3.4/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/pi/.local/lib/python3.4/site-packages/mxnet/base.py", line 113, in <module>
    _LIB = _load_lib()
  File "/home/pi/.local/lib/python3.4/site-packages/mxnet/base.py", line 105, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libomp.so: cannot open shared object file: No such file or directory
>>> exit()
```

## Minimum reproducible example
```
python3
import mxnet as mx
```

## What have you tried to solve it?

1. tried installing `libomp` - not successfully (perhaps doesn't exist for ARMv6 
2. tried installing `libcomplearn-gomp-dev` - not successfully

cc @larroy

**Comment by lebeg** [comment]
I've created a JIRA issue for that [MXNET-286](https://issues.apache.org/jira/browse/MXNET-286)

**Comment by lebeg** [comment]
Have you tried `sudo apt install libpomp-dev`?

**Comment by msurguy** [comment]
@lebeg should I do this before I install the `.whl` file or is it ok to run it after?

**Comment by msurguy** [comment]
@lebeg yeah. I tried installing it via the command you provided ( I assume it should be automatically added to the path) but still get the same error from within Python after trying to import mxnet lib.

**Comment by lebeg** [comment]
The problem seems to be with cmake cross builds in general, not with armv6 only. Since it's 1 core hardware anyway I've disabled OpenMP for v6, but will investigate the issue with later architectures. Thanks for reporting this!

**Comment by msurguy** [comment]
I can confirm that everything works on the Pi Zero now! Thanks @lebeg !!!

**Comment by lebeg** [comment]
Actually, if someone faced a similar problem on other platforms, like armv7 RPi try installing: ` sudo apt install llvm-dev`

**Comment by eLvErDe** [comment]
@lebeg 

Hello,

Changes nothing for me here (how is that related to this issue anyway?)

Adam
