### ISSUE TITLE
No setupenv.cmd present in the folder

### ISSUE THREAD

**Issue by dl002** [apache/incubator-mxnet#10237]
The installation docs [here](https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md) say the following at [Installing the Prebuilt Package on Windows](https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md#installing-the-prebuilt-package-on-windows).

> Open the folder, and install the package by double-clicking setupenv.cmd. This sets up all of the environment variables required by MXNet.

However, there is no `setupenv.cmd` inside the folder. The installation guide is not clear on how to locate/ create `setupenv.cmd`.

**Comment by sad-** [comment]
truly there is no setupenv.cmd present in the folder. see https://discuss.mxnet.io/t/installing-mxnet-on-windows/374 if you're still having issues installing or trying installing from source. the installation docs need to be updated to correct the stale info

**Comment by sad-** [comment]
@yzhliu can we close out this issue? @dl002 feel free to reopen if you have follow up questions
