### ISSUE TITLE
Error in Building and Installing packages on Windows using Visual Studio 2017

### ISSUE THREAD

**Issue by dl002** [apache/incubator-mxnet#10239]
When trying to build on Windows following instructions [here](https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md#building-and-installing-packages-on-windows), I could successfully run everything up to `cmake -G "Visual Studio 14 Win64" ..` . But when I open the Visual Studio and try to build the `mxnet `project (on Visual Studio 2017 Enterprise), I get the following error.

![image](https://user-images.githubusercontent.com/37702997/37869903-12763b8c-2fb9-11e8-9935-24ac475b0c5f.png)

I got no error for all previous steps, is there anything else that I should do?

**Comment by lightingghost** [comment]
`iomp5.lib` should be the library file needed when building `mxnet` with mkl support, which should be found under mkl `folder`. You can manually add the path following the instruction [here](https://support.microsoft.com/en-us/help/815645/you-receive-a-fatal-error-lnk1181-error-message-when-you-build-a-manag)

**Comment by sxjscience** [comment]
Also, I strongly suggest using VS2015 as OpenCV does not support VS2017.

**Comment by dl002** [comment]
Thank you @lightingghost, however I checked the `mkl `folder and just noted that `iomp5.lib` is not there. I had got the latest mkl from [here](https://software.intel.com/en-us/mkl) and installed. Should an older version of `mkl `be installed instead?

Thank you @sxjscience, if the `iomp5.lib `issue is solved and VS 2017 still gives errors, I will try with VS 2015.

**Comment by sxjscience** [comment]
@cgraywang

**Comment by lightingghost** [comment]
@dl002 I think iomp5 is the file name under linux, while under window you should be able to find `libiomp5md.lib`. I remember I changed all the occurrence of `iomp5` to `libiomp5md` in the `CMakeLists.txt` when I build mxnet by myself. Can you have a try?

**Comment by dl002** [comment]
@lightingghost In windows also there is no lib called `libiomp5md.lib.` So I just removed `iomp5 `from `Additional Dependencies` in `Linker -> Input` and the Visual Studio project `mxnet` in .sln built without issue (with VS2017). This created a dll libmxnet.dll in my Release folder. Can I now use this dll in my personal project? Do I have to build all projects and get `dll`s?

**Comment by sxjscience** [comment]
@dl002 You can try to python setup.py develop and then import mxnet to see if there is any problem.

**Comment by cgraywang** [comment]
@dl002 after testing, to build with VS2017 successfully is to call the following command to convert it to the right version (14.11):

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.11

please also check whether the above path to the build directory of VS2017 is the same as the one on your machine. Thanks
@yajiedesign

**Comment by dl002** [comment]
@lightingghost thanks a lot, I found `libiomp5md.lib` inside the compiler folder, earlier I checked the mkl folder. With that added, the project `mxnet` got built correctly and produced the following inside the Release folder.
```
libmxnet.dll
libmxnet.exp
libmxnet.lib
```

@sxjscience can you please tell me how to run the tests? I am planning to use `mxnet` with C++. Is it mentioned [here](https://github.com/apache/incubator-mxnet/blob/master/docs/install/windows_setup.md#building-and-installing-packages-on-windows)?

@cgraywang it was VS2017 that I built with, do I have to run the command again?

**Comment by dl002** [comment]
@cgraywang thank you I will do that. 

Thank you everyone for all the inputs!
