### ISSUE TITLE
API Doc not refreshed on website

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#10238]
I compared the API documentation in the source code and on the website. They are different. Is the website refreshed at all? Specifically, the sparse embedding op on website doesn't have the "note" section in the source code:

http://mxnet.incubator.apache.org/versions/master/api/python/ndarray/contrib.html#mxnet.ndarray.contrib.SparseEmbedding

https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/indexing_op.cc#L269-L277

@aaronmarkham @thinksanky

**Comment by sxjscience** [comment]
The newly added `LayerNorm` also does not appear in the website.

**Comment by aaronmarkham** [comment]
The site will need to be refreshed for these to appear.
