### ISSUE TITLE
bug in word language model example

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#10262]
The arguments of RNN don't align
https://github.com/apache/incubator-mxnet/blob/master/example/gluon/word_language_model/model.py#L33
https://mxnet.incubator.apache.org/versions/master/api/python/gluon/rnn.html?highlight=gluon.rnn.rnn#mxnet.gluon.rnn.RNN

**Comment by anirudhacharya** [comment]
please tag this - "Example", "RNN", "gluon"

**Comment by apeforest** [comment]
@szha What is the issue here? I don't see misalignment in the arguments now. Please clarify. Thanks!

**Comment by szha** [comment]
This has already been fixed.
