### ISSUE TITLE
Continue train in R: what is begin_round?

### ISSUE THREAD

**Issue by NiklasDL** [apache/incubator-mxnet#10267]
Suppose I train a model in R with

`begin.round = 1`
`num.round = 10`

and now I would like to continue training for 20 epochs, do I have to set 

`begin.round = 11`
`num.round = 20`

or

`begin.round = 11`
`num.round = 30`

or something else?

I am very confused because mxnet lets me insert any arbitrary number for the **begin.round** argument. For example:

`begin.round = 15`
`num.round = 30`

does also work, but it should not since I only trained for 10 epochs and clearly cannot beginn training at epoch 15.

**Comment by some-guy1** [comment]
I had the same question a while ago, I now use this:

`begin.round =n.rounds, num.round=n.rounds+extra.iter`

**Comment by NiklasDL** [comment]
Wouldn't 

`begin.round =n.rounds + 1`

make more sense?

Anyway, that still does not explain why MXNet allows to use any arbitrary integer for the
`begin.round` argument

**Comment by some-guy1** [comment]
Ya I dont think it matters.  All you are actually doing is selecting a slice in a vector to add new content.  It doesnt matter where you start and end.  It is up to the user to select the correct slice.

**Comment by anirudhacharya** [comment]
@nswamy @sandeep-krishnamurthy Please label this - "R", "Bug".

**Comment by ankkhedia** [comment]
Hi @NiklasDL Thanks for trying out MXNetR.  I understand your confusion regarding begin.round and num.round. As @some-guy1 suggested, the right way to think is 
begin.round =n.rounds+x, num.round=n.rounds+extra.iter+x
where x>0 and n.rounds is the number of epochs for which model was trained previously.

@nswamy @sandeep-krishnamurthy Please close the issue as it has been resolved.

@NiklasDL Feel free to reopen in case closed in error.
