### ISSUE TITLE
[R] mx.nd.BatchNorm Always empty list()

### ISSUE THREAD

**Issue by some-guy1** [apache/incubator-mxnet#10266]
## Description
I have trained a model that used mx.symbol.BatchNorm.  Everything seems to have worked well.

I am then trying to use the weights of the trained model to construct portions of the network.  No matter what I feed into mx.nd.BatchNorm, the result is always an empty list().

Example:  

```
cnn_1 = mx.nd.Convolution(data= cnn_3, weight = autoencoder$arg.params$conv_2_weight,
                            bias = autoencoder$arg.params$conv_2_bias ,
                            kernel = c(2,2), num_filter = 12  )
norm_2 = mx.nd.BatchNorm(data= cnn_1, gamma = autoencoder$arg.params$batchnorm9_gamma)
```
norm_2 is list() regardless of input or options.  Also, including the bias term in the batchnorm seems to through an error "Unused input".  Strange.

Have I misunderstood how to use batchnorm after I have already trained a model?

## Environment info (Required)
Windows 10
MXnet Version 1.2.0
R version 3.4.3

```

**Comment by harryprince** [comment]
@some-guy1 your example is not reproducible, maybe give us a mini-reproducible example.

**Comment by some-guy1** [comment]
:-( I dont think I can provide a better example.  mx.nd.BatchNorm seems to be a dead function for me.  Nothing ever comes out of it.

Maybe I have completely misunderstood.  Should BatchNorm ONLY be used during training with an iterator?

**Comment by harryprince** [comment]
In GAN-Example: https://github.com/apache/incubator-mxnet/tree/master/example/gan/CGAN_mnist_R

```
mx.symbol.concat(data = list(data, gen_rand), num.args = 2, name="gen_concat") %>%
    mx.symbol.Deconvolution( name='g1', kernel=c(4,4), num_filter=gen_features*4, no_bias=T) %>%
    mx.symbol.BatchNorm( name='gbn1', fix_gamma=fix_gamma, eps=eps) %>%
```

This BatchNorm function works well for me. And BatchNorm parameter should be updated in aux-parameters

```
aux_param_ini_D<- mx.init.create(initializer = initializer, shape.array = mx.symbol.infer.shape(D_sym, data=data_shape_D, digit=digit_shape_D)$aux.shapes, ctx = mx.cpu())
```

**Comment by some-guy1** [comment]
But what about "mx.nd.BatchNorm"?

"mx.symbol.BatchNorm"  seems to work fine for me, but "mx.nd.BatchNorm" does not.

I have used the "symbol" during training.  No problems, but when I try to use "nd" during testing, nothing happens, no output, nothing.
