### ISSUE TITLE
some code in example/rcnn/demo.py is wrong.

### ISSUE THREAD

**Issue by wangx404** [apache/incubator-mxnet#10291]
In demo.py, when logging the result after prediction, part of the code is wrong. It is shown below.
_logger.info('[[x1, x2, y1, y2, confidence]]')_

Actually, the number in the result should be [x1, y1, x2, y2, confidence].
Please fix it, as though it has no effect on the visualization.

**Comment by anirudhacharya** [comment]
@wangx404 consider making a PR to fix this.

@nswamy @sandeep-krishnamurthy please tag this - "Example"

**Comment by zhreshold** [comment]
Closing this after #11373 is merged
