### ISSUE TITLE
c++ how to predict for a couple of images

### ISSUE THREAD

**Issue by HaoLiuHust** [apache/incubator-mxnet#10290]
when use c++ to deploy, MXPredSetInput only support a constant size, is there a way that I can forward a few images at once, and the number of images is changing @mli @piiswrong

**Comment by HaoLiuHust** [comment]
Thanks, seems cpp-package is more sense

**Comment by anirudhacharya** [comment]
@nswamy @sandeep-krishnamurthy Please label this - "Question" and close this issue.
