### ISSUE TITLE
[Help] How I can change the in_data in CustomOp

### ISSUE THREAD

**Issue by wangshuailong** [apache/incubator-mxnet#10294]
Hi, I'm writing my own Costom Operator Op following the tutorials here: https://github.com/apache/incubator-mxnet/blob/master/example/numpy-ops/custom_softmax.py

I want to change the "in_data" because my custom loss needs the outputs of anther network. 
for this moment it has only "data" and "label". 

I changed the Data Batch in "forward" of Sequential module. However, when the data_batch was passed into CustomOp, there is only "data" and "label' part. 

I couldn't figure it out how the data batch was passed from the forward of Module to the Custom Op. 

So ideally I can get another part of data besides data and label by 

```
data = in_data[0]
label = in_data[1]
pred = in_data[2]
```

Can anyone give me some advice.  Thank you.

**Comment by chinakook** [comment]
Actually, you can pass more arguments like following:
mx.sym.Custom(*[a, b, c, d, e], ...)
mx.nd.Custom(*[a, b, c, d, e], ...)

in which a = in_data[0], b = in_data[1], c = in_data[2], d = in_data[3], e = in_data[4].

**Comment by wangshuailong** [comment]
@chinakook Thank you, and sorry for my late reply.  Yes It's a way to deal with multiple data sources. 
But still I'm wondering if I can do this by changing batch_data in Module.

**Comment by anirudhacharya** [comment]
@wangshuailong please direct your questions to discuss.mxnet.io

@nswamy @sandeep-krishnamurthy please label this - "Question"

**Comment by wangshuailong** [comment]
@anirudhacharya Didn't try discuss.mxnet.io before, looks awesome! I will try! Thank you!
