### ISSUE TITLE
Disable async forward pass for fastest prediction?

### ISSUE THREAD

**Issue by johnbroughton2017** [apache/incubator-mxnet#10301]
Hi all,

Prediction time is important for my case. I am not sure if this is a good idea (or even possible) to disable async forward pass to make the best of it. 

I am using a single machine and single GPU. Will async forward pass cause any uncertainty or delay in terms of prediction time? 

Any info is appreciated. Thx.
-- J

**Comment by eric-haibin-lin** [comment]
Usually async helps hide some latency. You can turn async execution off with `MXNET_ENGINE_TYPE =NaiveEngine`
 https://github.com/apache/incubator-mxnet/blob/master/docs/faq/env_var.md#engine-type

**Comment by anirudhacharya** [comment]
@nswamy @sandeep-krishnamurthy @eric-haibin-lin Please label this - "Question" and close the issue, as it seems to be resolved.
