### ISSUE TITLE
the document of class mxnet.gluon.rnn.RNN has a error

### ISSUE THREAD

**Issue by xiaotao321** [apache/incubator-mxnet#10314]
## Description
[here](http://mxnet.incubator.apache.org/api/python/gluon/rnn.html#mxnet.gluon.rnn.RNN), the description about 'x_t' has a error.
.. math::
        h_t = \tanh(w_{ih} * x_t + b_{ih}  +  w_{hh} * h_{(t-1)} + b_{hh})

    where :math:`h_t` is the hidden state at time `t`, and :math:`x_t` is the hidden
    state of the previous layer at time `t` or :math:`input_t` for the first layer.
    If nonlinearity='relu', then `ReLU` is used instead of `tanh`.

**Comment by sxjscience** [comment]
@aaronmarkham
