### ISSUE TITLE
Wikitext-2 and Wikitext-103 RNN Model

### ISSUE THREAD

**Issue by ArmageddonKnight** [apache/incubator-mxnet#10327]
Hi, I saw that in the `example` directory, there are three language modeling benchmarks (`bucketing`, `word_lm`, `large_word_lm`). The first two are running on the PTB dataset and the last one is running on the Google-Billion-Word dataset. Could someone please tell me whether we have any model that can run on the Wikitext-2 and Wikitext-103 dataset, which I think are also very popular in language modeling task.

Thanks.

**Comment by szhengac** [comment]
You can find example on Wikitext-2 in the following link:
https://github.com/apache/incubator-mxnet/tree/master/example/gluon/word_language_model

We also have interface for using Wikitext103:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/contrib/data/text.py

**Comment by ArmageddonKnight** [comment]
Great. @szhengac Thanks.
