### ISSUE TITLE
[Post 1.1][WIP] Couple of License Issues from 1.1 Release

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#10330]
## Description
a. [FIXED] LICENSE is missing this BSD licensed file [1]

b. [??] This file [2] seem to be CC-BY-2.5 which is category B [2] and should not be included in text form in the release. I know it's just a readme but probably best to remove it.

a. dmlc-core/include/dmlc/concurrentqueue.h
b. apache-mxnet-src-1.1.0.rc1-incubating/3rdparty/googletest/googlemock/docs/DevGuide.md
b. https://www.apache.org/legal/resolved.html#category-b

**Comment by mbaijal** [comment]
a. Fixed in PR #10373
b. Needs some investigation on best fix since we cant modify 3rdparty submodule

**Comment by anirudhacharya** [comment]
@apache/mxnet-committers Please label this - "Licenses"

**Comment by piyushghai** [comment]
@zachgk I think you handled the issues listed here for the Licenses. 
Can you check and see if this issue can be closed ?

**Comment by zachgk** [comment]
b was fixed by updating googletest and I still need to port that fix back to master. I will close this issue when it is fixed

**Comment by samskalicky** [comment]
@zachgk is this fixed? If so, please resolve this issue
