### ISSUE TITLE
ndarray diagonal operator request

### ISSUE THREAD

**Issue by HawkAaron** [apache/incubator-mxnet#10335]
In numpy, we can fetch the diagonal of an array using `diagonal` api: https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html#numpy.diagonal

It would be convenient to use this api. By the way, if possible, please return a view for that we can change the original array.

**Comment by chinakook** [comment]
I think view can only be a ‘rect’. You can do diagonal by combination of mx.sym.arange and mx.sym.take or mx.sym.gather_nd

**Comment by sxjscience** [comment]
Refer to this one also: https://github.com/apache/incubator-mxnet/issues/9253

**Comment by samskalicky** [comment]
@eric-haibin-lin This issue can be closed now that the PR has been merged for #9253 also
