### ISSUE TITLE
How to subtract mean during prediction with pretrained model (python)

### ISSUE THREAD

**Issue by johnbroughton2017** [apache/incubator-mxnet#10334]
Hi,

I followed the example code (http://mxnet.incubator.apache.org/tutorials/python/predict_image.html) on prediction using pretrained model.
> mod = mx.mod.Module(symbol=sym, context=mx.cpu(), label_names=None)
> mod.bind(for_training=False, data_shapes=[('data', (1,3,224,224))], 
>          label_shapes=mod._label_shapes)
> mod.set_params(arg_params, aux_params, allow_missing=True)

But I don't see where to subtract the mean (e.g. mean.nd). This is inconsistent with the c++ code here which subtracts a default mean (https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc).

From my validation, the c++ code with mean subtraction gives the right output while the python code without mean subtraction gives wrong output on the same image. Something must be wrong.

Any ideas? Thanks in advance.

-- J

**Comment by anirudhacharya** [comment]
@nswamy @sandeep-krishnamurthy Please label this - "Python", "Example"
