### ISSUE TITLE
Correct way to detect JSON file contains MXNet model

### ISSUE THREAD

**Issue by lutzroeder** [apache/incubator-mxnet#10359]
See https://github.com/lutzroeder/Netron/issues/99

`.json` files can contain both Keras models or MXNet models. Would it make sense for one of them to use a different file extension? Should there be a marker in the `.json` to detect it contains MXNet data?

**Comment by szha** [comment]
`.json` can contain not just keras models or mxnet models, but also many other different things, such as datasets, objects, the answer to the ultimate question of life.

For mxnet, it's up to the user to persist the serialized symbolic graph in a form that can be recognized later.

As for the library that deals with visualization of different symbolic graphs, I think it's the responsibility of the user of that library to specify how a serialized file should be interpreted. After all, it's impossible to tell a json is for which library, if the json serialization results of two libraries are identical but are semantically different. Using filename for such decision is an even worse way to go for obvious reasons...

**Comment by anirudhacharya** [comment]
Here is a potential solution to this problem, without having any restrictions on the filename of the json file.

The following is a sample json file that was obtained after serializing an mxnet symbol graph. 

```
{
  "nodes": [
    {
      "op": "null", 
      "name": "a", 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "b", 
      "inputs": []
    }, 
    {
      "op": "elemwise_mul", 
      "name": "_mul5", 
      "inputs": [[0, 0, 0], [1, 0, 0]]
    }, 
    {
      "op": "dot", 
      "name": "dot5", 
      "inputs": [[0, 0, 0], [1, 0, 0]]
    }, 
    {
      "op": "elemwise_add", 
      "name": "_plus11", 
      "inputs": [[2, 0, 0], [3, 0, 0]]
    }, 
    {
      "op": "Reshape", 
      "name": "reshape6", 
      "attrs": {"shape": "(1, 4)"}, 
      "inputs": [[4, 0, 0]]
    }
  ], 
  "arg_nodes": [0, 1], 
  "node_row_ptr": [0, 1, 2, 3, 4, 5, 6], 
  "heads": [[5, 0, 0]], 
  "attrs": {"mxnet_version": ["int", 10200]}
}
```

I have checked with a couple of other serialized graphs and all of them have this particular attribute in their json - 
```
"attrs": {"mxnet_version": ["int", 10200]}
```
We could possibly use the presence of this attribute in the json file to verify if it is an MXNet Symbol graph or not. I doubt Keras models will contain that particular attribute in its json.

**Comment by anirudhacharya** [comment]
@szha please tag this - "HowTo", "Visualization".

**Comment by anirudhacharya** [comment]
@lutzroeder if this is resolved, please close the issue.
