### ISSUE TITLE
MXNet from Source is slower than Pip Package

### ISSUE THREAD

**Issue by ArmageddonKnight** [apache/incubator-mxnet#10356]
Hi there,

I have two copies of `MXNet` - one local copy that I kept for revision and another global copy which has been installed using `sudo -H pip3 install mxnet-cu80==0.12.1`. I built my local copy using the following command:

```
make -j $(nproc) \
	USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 \
	USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_CPP_PACKAGE=1
```

and created a virtual environment for the python binding. The problem is that - when I run the `cudnn_lstm_bucketing.py` example, what I noticed is that the local copy (throughput is around `3600 samples/sec`) is around `1000 samples/sec` slower than the global copy (throughput is around `4600 samples/sec`).

Could someone please tell me whether I am missing some build options in my `make` command? Thank you.

**Comment by rahul003** [comment]
The build flags used for pip package are listed here
https://github.com/apache/incubator-mxnet/issues/8671

**Comment by spidyDev** [comment]
@ArmageddonKnight  Please close this issue, if your is answered. Thanks

**Comment by ArmageddonKnight** [comment]
@rahul003 Thanks a lot for your help and @spidyDev  sorry for forgetting to close this issue.
