### ISSUE TITLE
CI does not check with CuDNN=0

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10353]
At the moment, our CI does not run any tests with CuDNN disabled. I'd propose to change the CentOS 7 GPU environment to run with ```CUDA=1 CuDNN=0```.

**Comment by marcoabreu** [comment]
@zheng-da

**Comment by KellenSunderland** [comment]
Definitely a good idea to get at least one build in without cudnn, theres a lot of code paths it would cover.

**Comment by zheng-da** [comment]
We should definitely test build. The question is whether we should run the code and how? Some test code can't run without CuDNN as we have experienced in https://github.com/apache/incubator-mxnet/pull/10302

**Comment by marcoabreu** [comment]
I'd propose to add specific excludes (for these non-runnable tests) to the nosetest call in runtime_functions.sh.

Other options would have been to set an environment variable and check it in the test or catch the CuDNN-not-present-exception and drop it. But I'd not be in favour of those because this would require CI-specific modifications in tests and (in the latter case) could mask valid errors due to CuDNN missing while expecting it to be present.

**Comment by haojin2** [comment]
Seems like we already have such check in the CI pipeline? @marcoabreu

**Comment by szha** [comment]
@anirudh2290 already added a stage for it
