### ISSUE TITLE
asscalar is very slow

### ISSUE THREAD

**Issue by nju-luke** [apache/incubator-mxnet#10368]
The train part cost 0.01 second, but the asscalar operation cost a few seconds sometimes more than 10. I install the newest version of mxnet by pip, and this was happened with cpu and gpu context both.
Does anyone have any idea for fixing this? Thank you very much.
``` python
    for epoch in range(num_epochs):
        train_loss = nd.array([0.0], ctx=ctx)
        for data, label in tqdm.tqdm(train_data):
            label = label.as_in_context(ctx)
            data = data.as_in_context(ctx)
            with autograd.record():
                output = net(data)
                loss_ = loss(output, label)
            loss_.backward()
            trainer.step(batch_size, ignore_stale_grad=True)
            train_loss += nd.mean(loss_)
        train_loss = train_loss.asscalar()
````

**Comment by reminisce** [comment]
How did you time it? `asscalar` is a blocking function call, while the other lines are async. It would not be accurate to simply time it line by line in Python. You will need to add `mx.nd.waitall()` before the last line to time the training part reasonably.

**Comment by nju-luke** [comment]
This is the  version with time, and the third out put time.
``` python
        print(datetime.datetime.now())
        train_loss = nd.array([0.0], ctx=ctx)
        for data, label in tqdm.tqdm(train_data):
            label = label.as_in_context(ctx)
            data = data.as_in_context(ctx)
            with autograd.record():
                output = net(data)
                loss_ = loss(output, label)
            loss_.backward()
            trainer.step(batch_size, ignore_stale_grad=True)
            train_loss += nd.mean(loss_)
        print(datetime.datetime.now())
        train_loss = train_loss.asscalar()
        print(datetime.datetime.now())
```
``` shell
2018-04-03 01:00:47.525819
100%|██████████| 30/30 [00:01<00:00, 28.00it/s]
2018-04-03 01:00:48.624371
2018-04-03 01:02:18.453842
```

**Comment by reminisce** [comment]
This timing does not reflect the correct time spent on training and `asscalar` respectively. As said before, all the lines before the second `print` are async operations. You need to sync before `asscalar` is called.

**Comment by reminisce** [comment]
For OOM problem, seems it's caused by always pushing operations to engine for every mini-batch in an epoch. You need to sync before another mini-batch starts. Otherwise, new memory are alway allocated when a new mini-batch starts. You can try defining `train_loss` as a scalar, and replace `train_loss += nd.mean(loss_)` with `train_loss += nd.mean(loss_).asscalar()`.

**Comment by nju-luke** [comment]
@reminisce Thanks for the explanation about `asscalar`.
I'm sorry that I didn't make it clear about OOM. When I said iteration, it means the epoch. That is, the OOM error is raised during the second epoch, in half the task is completed.
```
python train_softmax.py
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:05<00:00, 59.88it/s]
Epoch 0. Train loss: 4.608121, Valid loss 4.608134
42%|████████████████████████████████████████████████████▌                                                                       | 1088/2565 [00:21<00:29, 50.49it/s]terminate called after throwing an instance of 'dmlc::Error'
  what():  [19:33:44] src/engine/./threaded_engine.h:359: [19:33:44] src/storage/./pooled_storage_manager.h:107: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
...

```

**Comment by nju-luke** [comment]
The OOM was fixed by changed train_loss with `train_loss += nd.mean(loss_).asscalar()` .
Appreciations @reminisce
