### ISSUE TITLE
When to use SyncCopyFromCPU and SyncCopyToCPU - C++

### ISSUE THREAD

**Issue by mrRo8o7** [apache/incubator-mxnet#10379]
Hi, i want to ask for the difference between SyncCopyFromCPU and SyncCopyToCPU. I don't get it from the mxnet c++ reference.

**Comment by haojin2** [comment]
@mrRo8o7 The documentation is added but may not be rendered on the webpage for some reason. You can find the corresponding docs for SyncCopyFromCPU at: https://github.com/apache/incubator-mxnet/blob/c153a6c789f667abb3bf1ea3d8d352c6f3b120b7/cpp-package/include/mxnet-cpp/ndarray.h#L251. For SyncCopyToCPU at: https://github.com/apache/incubator-mxnet/blob/c153a6c789f667abb3bf1ea3d8d352c6f3b120b7/cpp-package/include/mxnet-cpp/ndarray.h#L272

**Comment by haojin2** [comment]
In general, you would want to use SyncCopyFromCPU/SyncCopyToCPU when you have some contiguous memory region not yet wrapped by NDArray so that you could use NDArray APIs to operate on that region.

**Comment by Roshrini** [comment]
@mrRo8o7 Please close the issue if your query is resolved. 
Also, Please use the user forum for how-to questions. You'll get quicker responses there. https://discuss.mxnet.io/

**Comment by gxkevin** [comment]
I don't know how to set the parameter 'size' in SyncCopyFromCPU?
