### ISSUE TITLE
Report clear errors when opencv::imdecode fails.

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#10389]
Currently when opencv function fails cryptic opencv error is raised. We should catch it and report which file failed.

see https://github.com/apache/incubator-mxnet/blob/121adb6660897d7cef223caba80a43412ab5c9e0/src/io/image_io.cc#L161

**Comment by anirudh2290** [comment]
Currently we don't catch exceptions unless they are dmlc::Error. This would need to change to catch other library exceptions. This TODO list needs to be prioritized: https://github.com/apache/incubator-mxnet/issues/9913

**Comment by vandanavk** [comment]
@mxnet-label-bot add [Exception Handling]

**Comment by anirudh2290** [comment]
Working on a PR for this
