### ISSUE TITLE
[Operator] Support ndim > 3 for batch_dot

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#10386]
In batch_dot, i.e, `C = batch_dot(A, B)`,  both inputs A & B must have ndim=3. However, in some cases our inputs could have have higher dimensionality. We can consider to support the following two cases:

- [ ] Both A, B have ndim >3

    We should compute the output as:
   ```
   C[..., i, j] = sum_k (A[..., i, k] * B[..., k, j]), for all indices i, j.
   ```
   For example, if the shape of A is (batch_size, a1, a2, …, b, c) and the shape of B is (batch_size, a1, a2, …, c, d), the shape of C will be (batch_size, a1, a2, ..., b, d).
   This is similar to the [matmul in Tensorflow](https://www.tensorflow.org/api_docs/python/tf/matmul)
- [ ] One of A, B have ndim > 3

   Assume A.ndim >3, we have
   ```
   C[b, ..., i, j] = sum_k (A[b, ..., i, k] * B[b, k, j]), for all indices i, j.
   ```

Supporting these two cases will solve the problems in https://discuss.gluon.ai/t/topic/2534/8, https://discuss.gluon.ai/t/topic/5618/9

**Comment by tqchen** [comment]
maybe related to optimizations in http://www.tvmlang.org/2018/03/23/nmt-transformer-optimize.html

**Comment by Angzz** [comment]
同问，1.3 pre版本的都已经更新了，但是貌似还是只支持3 dim.

**Comment by yufengwhy** [comment]
数据量较大，reshape有点慢，弄好了通知一声，更新一下代码，@sxjscience
