### ISSUE TITLE
Android build documentation 

### ISSUE THREAD

**Issue by dabraude** [apache/incubator-mxnet#10395]
It would be really useful to have documentation about building android from source.

**Comment by lupesko** [comment]
@nswamy @Roshrini why are we labeling Build as Installation? Doesn't seem like the same thing.

**Comment by thomelane** [comment]
One option for deploying MXNet models is via TVM. See https://docs.tvm.ai/deploy/android.html

**Comment by Ishitori** [comment]
And the second one is here: https://github.com/Leliana/WhatsThis

**Comment by ThomasDelteil** [comment]
There is also this, https://mxnet.incubator.apache.org/versions/master/faq/smart_device.html
You can also try the arm build with the java bindings 
@larroy can maybe shed more light
