### ISSUE TITLE
[MXNET-287] ARMv6 build with 8-10 times bigger file size

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#10398]
The ARMv6 generated wheel grew by 8-10 times in terms of file size according to https://github.com/apache/incubator-mxnet/commit/85215b6176ef3612d198f590268a6595b86565fb.

Investigate and then add more information.

**Comment by marcoabreu** [comment]
Fixed as of https://github.com/apache/incubator-mxnet/commit/582ec4015dff60a6ae6ff25f32cf4b1e3b65925a

@msurguy please validate
