### ISSUE TITLE
Can't press down arrow in search results dropdown on https://mxnet.incubator.apache.org/

### ISSUE THREAD

**Issue by altosaar** [apache/incubator-mxnet#10402]
It would improve UX to be able to press the down arrow in the dropdown that appears when we search https://mxnet.incubator.apache.org/

**Comment by marcoabreu** [comment]
@aaronmarkham

**Comment by ChaiBapchya** [comment]
@ys2843 has this been taken care of?

**Comment by ys2843** [comment]
@aaronmarkham @marcoabreu  Global search now supports keyboard control (up/down arrow select). This issue can be closed.

**Comment by ChaiBapchya** [comment]
Thanks for adding the functionality Yang!
Can you point to which PR added keyboard control? Was it different from the one I mentioned above?

**Comment by ys2843** [comment]
@ChaiBapchya I assume it is the dropdown of the search feature on the top navigation bar that need keyboard control. v1.6+ website has new global search feature #18288 which support navigating through results by pressing up/down arrow key.
