### ISSUE TITLE
https://newdocs.readthedocs.io is outdated

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#10409]
@Awyan can you please remove this site? we found a lot of users are following the instructions there, but some of them are outdated.

**Comment by aaronmarkham** [comment]
Plan B, follow this support request: https://github.com/rtfd/readthedocs.org/issues/3854

**Comment by aaronmarkham** [comment]
Plan B initiated: https://github.com/rtfd/readthedocs.org/issues/4042
