### ISSUE TITLE
There is no API Reference Doc for R bindings.

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#10414]
We need an API reference doc for MXNet R bindings - http://mxnet.incubator.apache.org/api/r/index.html

Currently it is not there. Creating this issue to track it.

@aaronmarkham

**Comment by lanking520** [comment]
I got the document generated, let's discuss where to put it

**Comment by anirudhacharya** [comment]
This is the document @lanking520 shared - https://drive.google.com/file/d/1LUFiKFFiI9ypx-PlaOIw5wO4MoAzu9Jh/view?usp=sharing. 

@aaronmarkham please let us know how it can be included in the mxnet R API documentation.

**Comment by lanking520** [comment]
Update in this PR: https://github.com/apache/incubator-mxnet/pull/10473
@anirudhacharya
