### ISSUE TITLE
How can I build mxnet in ubuntu16.04?

### ISSUE THREAD

**Issue by Tian14267** [apache/incubator-mxnet#10419]
When I build mxnet in ubuntu ,I get this error:

No package 'opencv' found
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/tian/mxnet/3rdparty/mshadow/ -I/home/tian/mxnet/3rdparty/dmlc-core/include -fPIC -I/home/tian/mxnet/3rdparty/nnvm/include -I/home/tian/mxnet/3rdparty/dlpack/include -I/home/tian/mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1  -fopenmp -DMXNET_USE_OPERATOR_TUNING=1  -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/cudnn/cudnn_batch_norm.cc -o build/src/operator/nn/cudnn/cudnn_batch_norm.o
In file included from src/operator/nn/cudnn/./../../../common/cuda_utils.h:31:0,
                 from src/operator/nn/cudnn/./cudnn_algoreg-inl.h:33,
                 from src/operator/nn/cudnn/cudnn_algoreg.cc:26:
/home/tian/mxnet/3rdparty/mshadow/mshadow/base.h:147:23: fatal error: cblas.h: 没有那个文件或目录
...........
..........

when I "import cv2" in python , it's ok.
so, does somebody can help me??

**Comment by kong13661** [comment]
Sorry, I don't know how to fix it, but I think updating your sources such as other ubuntu 16.04 and ubuntu14.04 sources will help you.

**Comment by Sorry** [comment]
Why are you tagging me???

**Comment by NKUCodingCat** [comment]
Well....What you need is Google....

**Comment by sandeep-krishnamurthy** [comment]
Please follow instructions here - http://mxnet.incubator.apache.org/install/index.html
Choose "Linux/Python/BuildFromSource"
