### ISSUE TITLE
Elementwise multiplication of two ndarrays returns wrong results

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#10431]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Elementwise multiplication of two ndarrays returns wrong results

## Environment info (Required)
python, built from source, USE_CUDA=OFF, USE_CUDNN=OFF

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
f60094053e5f2c233bb39b63bdd16503875a4551

## Error Message:
```
AssertionError:
Items are not equal:
Error 100000.000000 exceeds tolerance rtol=0.000010, atol=0.000000.  Location of maximum error:(0, 2), a=0.098160, b=-375054495907840.000000
 a: array([[ 0.88395894,  0.0185979 ,  0.09815959,  0.24501987]], dtype=float32)
 b: array([[  8.83958936e-01,   1.85978990e-02,  -3.75054496e+14,
          2.45019868e-01]], dtype=float32)
```

## Minimum reproducible example

export MXNET_ENGINE_TYPE=NaiveEngine
```
import mxnet as mx
from mxnet.test_utils import *

x = mx.nd.array(np.random.uniform(-1, 1, size=(1, 4)))
x = x.tostype('csr')
#x.attach_grad()
print(x.asnumpy())
z2 = x * x
z1 = mx.nd.sparse.square(x)
assert_almost_equal(z1.asnumpy(), z2.asnumpy())
```

**Comment by rahul003** [comment]
This seems to work on the current nightly pip package which uses the commit 5245ef68191a6d47594bf331ec6e20ba6e93ad4c  from April 2. 

Looks like the bug was introduced after that. 

Btw @szha The latest pip --pre package used the above commit from April 2. Is the package not built nighly?

**Comment by anirudh2290** [comment]
@eric-haibin-lin please tag as bug.

**Comment by eric-haibin-lin** [comment]
@rahul003 can you try `nd.elemwise_mul(x, x)` instead of `x * x`?

**Comment by rahul003** [comment]
`elemwise_mul` has the same behavior crashes on the current master

**Comment by anirudh2290** [comment]
You have to add fix <PR_NO> in the PR for it to automatically close.
