### ISSUE TITLE
[scala-infer]move test files for scala infer API to s3

### ISSUE THREAD

**Issue by CodingCat** [apache/incubator-mxnet#10432]
can we move these files to S3?

https://github.com/apache/incubator-mxnet/blob/aa3f06511e96cbffc7a9a2d9e0a96cf0e446d646/scala-package/examples/src/test/scala/ml/dmlc/mxnetexamples/inferexample/imageclassifier/ImageClassifierExampleSuite.scala#L41-L48

Downloading speed is super slow and usually take minutes to finish

**Comment by marcoabreu** [comment]
@szha

**Comment by Roshrini** [comment]
@lanking520 Can you upload models files for imageclassification and SSD examples in S3 and change the links?

**Comment by lanking520** [comment]
Here you go: https://github.com/apache/incubator-mxnet/pull/10617

**Comment by nswamy** [comment]
#10617
