### ISSUE TITLE
Does gluon support dynamic graph like if clause?

### ISSUE THREAD

**Issue by chengdazhi** [apache/incubator-mxnet#10459]
Hi, 

I have found that if clause in Block.forward() is executed in main thread and causes delay if outputs of former operators are related. 

For example:

```
// pseudo code
class DemoBlock(Block):
    def __init__(self, **kwargs):
        super(DemoBlock, self).__init__(**kwargs)
        self.fc = nn.Dense(10)
    def forward(self, x):
        x = self.fc(x)
        if x.sum() > 0:
            return x
        else:
            return x+1
```

when executing DemoBlock.forward and starting to execute if clause, main thread waits for Dense block(self.fc) to finish computation. So does gluon support if clauses like this?

**Comment by Roshrini** [comment]
@chengdazhi 
For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io you will get a quicker response. Thanks!
@sandeep-krishnamurthy Can you add label -
Question, Gluon
