### ISSUE TITLE
Create base images for CI

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#10498]
@marcoabreu 
It would be nice if the CI base images were stored on dockerhub. So that reproducing locally would be a simple pull and then the code being executed. I assume these intermediate layers are currently kept cached on the build machines, but having them as images would make adding and removing machines to the build farm much more efficient since they wouldn't have to rebuild each image from scratch on a cold start.

**Comment by marcoabreu** [comment]
I'm currently working on auto scaling for our CI and this and putting the images on dockerhub (or a similar service) will be part of that process :)

**Comment by piyushghai** [comment]
@marcoabreu Pinging to check if this feature has been implemented or not :)
Thanks!

**Comment by marcoabreu** [comment]
Yep, they are automatically pulled if people use the build.py script. Thanks for the heads up.
