### ISSUE TITLE
Does RSP storage type NDArray support shared memory?

### ISSUE THREAD

**Issue by moveforever** [apache/incubator-mxnet#10501]
@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
Please post this kind of question on http://discuss.mxnet.io/

Depends on what you mean by shared memory:
- rowsparse Weight sharing is supported if you use bucketing module
- NDArray.__get_item__ with int key returns a view of the original NDArray, which shares the memory of the original NDArray. For row_sparse it's not supported.
