### ISSUE TITLE
Can MXNet operator profiling work well using gluon model?

### ISSUE THREAD

**Issue by jinhuang415** [apache/incubator-mxnet#10504]
I tried 2 models written in Gluon and try to do operator level profiling, but the generated profile.json doesn't contain any operator information (while it contains MXNET_C_API profiling info), by adding debug in OP level code it is confirmed conv/pooling/Eltwise OP is indeed invoked. 

I have set below env variables before start running gluon model but no use (it works well in previous MXNet version):
export MXNET_EXEC_BULK_EXEC_INFERENCE=0
export MXNET_EXEC_BULK_EXEC_TRAIN=0
export MXNET_PROFILER_AUTOSTART=1

Would any MXNet expert help to check if my configurations/steps are correct or if this is an issue for Gluon model profiling? Thanks.

**Comment by jinhuang415** [comment]
Below is a simple gluon model I used (mainly copied from https://mxnet.incubator.apache.org/tutorials/gluon/gluon.html, only added wait_to_wait() call at the end in order to make sure OPs are executed):

```
# import dependencies
from __future__ import print_function
import numpy as np
import mxnet as mx
import mxnet.ndarray as F
import mxnet.gluon as gluon
from mxnet.gluon import nn
from mxnet import autograd

class Net(gluon.Block):
    def __init__(self, **kwargs):
        super(Net, self).__init__(**kwargs)
        with self.name_scope():
            # layers created in name_scope will inherit name space
            # from parent layer.
            self.conv1 = nn.Conv2D(6, kernel_size=5)
            self.pool1 = nn.MaxPool2D(pool_size=(2,2))
            self.conv2 = nn.Conv2D(16, kernel_size=5)
            self.pool2 = nn.MaxPool2D(pool_size=(2,2))
            self.fc1 = nn.Dense(120)
            self.fc2 = nn.Dense(84)
            self.fc3 = nn.Dense(10)

    def forward(self, x):
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        # 0 means copy over size from corresponding dimension.
        # -1 means infer size from the rest of dimensions.
        x = x.reshape((0, -1))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
# Initialize on CPU. Replace with `mx.gpu(0)`, or `[mx.gpu(0), mx.gpu(1)]`,
# etc to use one or more GPUs.
net.collect_params().initialize(mx.init.Xavier(), ctx=mx.cpu())

data = mx.nd.random_normal(shape=(10, 1, 32, 32))  # dummy data
output = net(data)
output.wait_to_read()
```

I also attached the generated profile json zip file FYI:
[profile_gluon.zip](https://github.com/apache/incubator-mxnet/files/1899450/profile_gluon.zip)

**Comment by rahul003** [comment]
Could you use mx.profiler.set_config and set the option profile_all=True, and try again? Note that this is a different way of profiling with more flexibility than MXNET_PROFILER_AUTOSTART, so when you use this don't set that environment variable. 

```
 mx.profiler.set_config(profile_all=True, filename='profile_output.json')
mx.profiler.set_state('run')

    # Code to be profiled goes here...

mx.profiler.set_state('stop')
```

**Comment by jinhuang415** [comment]
@rahul003 Thanks, the way you mentioned works. For the environment variable way,  do we also need to support that when we want to do whole program profiling and don't want to change the code (also keep backward compatible) ?

**Comment by jinhuang415** [comment]
Btw, is there any way to selectively do the profiling? Like only perform operator profiling, I asked this because in many cases the generated profile data are very huge (>100MB) if profile all data, it would save a lot of time if we can do profile selectively.

I tried to use mx.profiler.set_config(profile_symbolic=True, filename='profile_output.json') to filter operators but seems still all types are profiled.

**Comment by jinhuang415** [comment]
For selective profiling, I figured out myself that we need to use "mx.profiler.set_config(profile_all=False, profile_imperative=True, profile_symbolic=False, profile_memory=False, profile_api=False, filename='profile_output.json')" to set related profile types to False since the default type is True.

**Comment by jinhuang415** [comment]
@pengzhao-intel

**Comment by jinhuang415** [comment]
@cjolivier01  We noticed there is profiling enhancement recently, may I know how to get below statistics text output from the profile data? (I see that you pasted this output in another thread but we don't know how to get that)  Thanks.

![35419241-b678695e-01eb-11e8-8907-abd3f6ff57f7](https://user-images.githubusercontent.com/34262351/38658448-d79aa306-3e57-11e8-9ff6-c2594fde7cec.png)

**Comment by rahul003** [comment]
Have you tried this ?
https://github.com/apache/incubator-mxnet/blob/ceb810ccc17a712c375d55418a0ba45ae91714b5/python/mxnet/profiler.py#L127

**Comment by rahul003** [comment]
I'd suggest creating an issue so we can track and fix this. If you identify the issue please feel free to submit a PR. Could you check if the counts are the same or different to those in the json file generated in the above steps?

**Comment by jinhuang415** [comment]
@rahul003  Raise https://github.com/apache/incubator-mxnet/issues/10520

**Comment by Zha0q1** [comment]
@sandeep-krishnamurthy  this issue seems resolved. we can probably close. Also, my PR fixed the other issue linked above
