### ISSUE TITLE
Float16 Support for dot

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#10531]
Is there any work underway to add Float16 support for the dot operator? I know there is a ticket for the general job of adding Float16 support (https://issues.apache.org/jira/browse/MXNET-90), but wanted to know what the timeframe was for support to dot, which is a very core operator that also benefits greatly from the V100 TensorCores.

**Comment by rahul003** [comment]
@haojin2 Looks like we missed this. I went through dot-inl.h. Looks like that's disabled for no reason the GPU through the check. Could you take a look? There's BlasEngine<gpu, half_t> defined. This might be an easy fix.

The concern might be that there's no CPU support for BLASEngine with half_t, but that's fine.

**Comment by rahul003** [comment]
Removing my earlier comment.

Actually float16 dot does seem supported for GPU. What error did you encounter?

**Comment by eric-haibin-lin** [comment]
@rahul003 @haojin2 are you guys working on that?

**Comment by rahul003** [comment]
Dot for fp16 on GPU was supported internally but a (probably older) CHECK was blocking it. Created a PR to fix this.

https://github.com/apache/incubator-mxnet/pull/10538

**Comment by sbodenstein** [comment]
@rahul003: great, thanks for fixing it!

**Comment by rahul003** [comment]
Can we close this now?
