### ISSUE TITLE
Intel MKL-DNN RNN Support

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#10542]
MKL-DNN [recently got support for RNNs](https://github.com/intel/mkl-dnn/commit/f35779d62a0b3a2e0f6be79a647b1e3acf02129b). Are there any plans for adding this as a backend to `mx.sym.RNN`, and what sort of timeframe? Thanks!

@zheng-da

**Comment by TaoLv** [comment]
@sbodenstein Thanks for asking that. It's already on our plan list for Q2. Since it's still an experimental interface, we will keep tracking the development progress from mkldnn team.
FYI, we are working intensively on PR #10104 and #10311 to provide fused RNN operator for mxnet before mkldnn RNN interfaces become mature. Hopefully, after mkldnn RNN is integrated into mxnet, code of #10104 and #10311 would still exsit as a reference implementation for cpu. @pengzhao-intel

**Comment by Roshrini** [comment]
@eric-haibin-lin Can you please add labels-
FeatureRequest, RNN

**Comment by azai91** [comment]
@sbodenstein we plan on implementing MKL-DNN RNN support when MKLDNN 0.15 is released which should be within the next few weeks.

**Comment by sbodenstein** [comment]
@azai91: fantastic, thanks so much!

**Comment by neverjoe** [comment]
Any good news for mkl-dnn rnn support?

**Comment by neverjoe** [comment]
Is there any python test demo for GruForwardInference?

**Comment by pengzhao-intel** [comment]
There's no python interface, but you can test by mkldnn binary very simple.
https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn

https://github.com/intel/mkl-dnn/commit/3ced2c71fdb06fe4546fe95054d1e766a8addfa7 
> ./benchdnn  --rnn --batch=./inputs/rnn/test_rnn_small 

In the test file, it includes several configurations:

> --reset --alg=VANILLA_GRU
> --direction=left2right
> --activation=TANH
> --prop=FWD_D --batch=rnn_gru_small
> --prop=BWD_DW --batch=rnn_gru_small

**Comment by anirudh2290** [comment]
@pengzhao-intel Can you point me to the further discussion for MKLDNN RNN API Integration.

**Comment by pengzhao-intel** [comment]
@anirudh2290 yes, we have the plan but a little complicated mixed the next major release of MXNet 2.0 and MKLDNN 1.0. 

We can talk for more details by email, please ping me patric.zhao@intel.com

**Comment by bgawrych** [comment]
@szha Can we close this issue? MXNet already have support for oneDNN RNN's

**Comment by szha** [comment]
@bgawrych thanks!
