### ISSUE TITLE
Build error for OSX with CUDA support

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#10553]
Building MXNet on OSX with CUDA support using the Makefile appears broken. Using bisection search, the build breakages started with commit `0fd29698a11c0c77180aefdcf8264e063158a2c0`. Building gives an error:
```
nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++    -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/mshadow/ -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/dmlc-core/include -fPIC -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/nnvm/include -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/dlpack/include -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=0 -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/Users/sebastianb/Software/incubator-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0" -M -MT build/src/operator/contrib/adaptive_avg_pooling_gpu.o src/operator/contrib/adaptive_avg_pooling.cu >build/src/operator/contrib/adaptive_avg_pooling_gpu.d
/bin/sh: nvcc: command not found
make: *** [build/src/operator/nn/cudnn/cudnn_batch_norm_gpu.o] Error 127
make: *** Waiting for unfinished jobs....
/bin/sh: nvcc: command not found
/bin/sh: nvcc: command not found
make: *** [build/src/operator/contrib/adaptive_avg_pooling_gpu.o] Error 127
make: *** [build/src/operator/contrib/bilinear_resize_gpu.o] Error 127
make[1]: `libdmlc.a' is up to date.
```
Config file CUDA flags:
```
# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
# USE_CUDA_PATH = NONE

# whether to enable CUDA runtime compilation
ENABLE_CUDA_RTC = 1

# whether use CuDNN R3 library
USE_CUDNN = 1

#whether to use NCCL library
USE_NCCL = 0
#add the path to NCCL library
USE_NCCL_PATH = NONE
```
I'm using NVCC:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Tue_Dec_19_21:36:29_CST_2017
Cuda compilation tools, release 9.1, V9.1.128
```
and Clang:
```
clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by marcoabreu** [comment]
https://github.com/apache/incubator-mxnet/commit/0fd29698a11c0c77180aefdcf8264e063158a2c0
@KellenSunderland

**Comment by KellenSunderland** [comment]
Taking a look ...

**Comment by sbodenstein** [comment]
Attached are my building log and config file. Running `echo $NVCC` after building returns empty. Its not defined.

[build_log.txt](https://github.com/apache/incubator-mxnet/files/1915883/build_log.txt)
[config.txt](https://github.com/apache/incubator-mxnet/files/1915892/config.txt)

**Comment by KellenSunderland** [comment]
Thanks for the report @sbodenstein.  I see what the issue is and will open a PR, it should be reasonably easy to fix.

To give some background: I made this change because previously no matter what you specified as your nvcc path, the makefile would use /usr/local/cuda/bin/nvcc for nvcc.  In your case this was actually a good thing because your config specifies just 'nvcc' which is likely not on your path.  Changing to the absolute path fixes the problem.  However this behaviour causes issues when cross compiling.  You may have an arm and x86 cuda path specified, and you need to select the correct nvcc for your platform.

Thanks again for pointing this out, and for following up with the build log + config.

**Comment by spidyDev** [comment]
@KellenSunderland  Please label this issue : Build

**Comment by KellenSunderland** [comment]
@spidyDev I don't think I have permission to label.  Maybe @marcoabreu  can help us out.

**Comment by KellenSunderland** [comment]
@sbodenstein Can you test this in master, I think the merged PR above should address your concerns.  If it does feel free to close the issue, and if not let us know.

**Comment by kalyc** [comment]
@sbodenstein could you let us know if your issue has been fixed?

**Comment by kalyc** [comment]
@sbodenstein could you close this issue? Looks like it has been fixed.

**Comment by sbodenstein** [comment]
Sorry about that, its definitely fixed. Closing.
