### ISSUE TITLE
Gluon not mentioned in Symbol API tutorial

### ISSUE THREAD

**Issue by thomelane** [apache/incubator-mxnet#10571]
Gluon mention in Symbol API tutorial.

http://mxnet.incubator.apache.org/tutorials/basic/symbol.html

Given Symbol API is being used by Gluon API when Blocks are hybridized, this should be acknowledged by the tutorial. I think it would help users understand the relationship between APIs.

Sometimes Module API is mentioned, but this should also be updated to include Gluon.
e.g. "In this section, we introduce the functions to manipulate a symbol directly. But note that, most of them are wrapped by the module package."

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by spidyDev** [comment]
@eric-haibin-lin  Please label : Doc

**Comment by thomelane** [comment]
Submitted pull request for updates https://github.com/apache/incubator-mxnet/pull/12190
@indhub good to close this issue now, thanks!
