### ISSUE TITLE
How to assign weight for each class in the fine-tuning example?

### ISSUE THREAD

**Issue by lixiangchun** [apache/incubator-mxnet#10598]
Sometimes, we need to assign weight for each class when performing fine-tuning if the class is imbalanced. How to do this with mxnet?

**Comment by spidyDev** [comment]
@lixiangchun : Please do post your question on : discuss.mxnet.io

@reminisce : Please label as : Question, HowTo

**Comment by nswamy** [comment]
Questions are best answered on https://discuss.mxnet.io/. Please take post your question there. I am closing this issue for now.
