### ISSUE TITLE
Gluon Interpolation Layer

### ISSUE THREAD

**Issue by PKurnikov** [apache/incubator-mxnet#10600]
I tried to implement the layer on gluon like this:
```
class BilinearInterp(nn.HybridBlock):
    def __init__(self, target_size, **kwargs):
        super(BilinearInterp, self).__init__(**kwargs)
            self.height = target_size[0]
            self.width = target_size[1]
    def forward(self, x):
        return mx.nd.contrib.BilinearResize2D(x, self.height, self.width)
```

But I've got error msg:

> Argument data must have NDArray type, but got (Symbol icnet0_batchnorm0_fwd)

Is it possible to implement gluon interpolation layer?
I tried a different approach (mx.nd.GridGenerator + mx.nd.BilinearSampler), also unsuccessfully.

**Comment by PKurnikov** [comment]
Unfortunately, I can't to use this approach 

> nn.Block

, because I use BatchNorm, HybridSequential classes which contains HybridBlock realisation.

> Children of HybridBlock must also be HybridBlock
All children layers of HybridBlock must also be HybridBlock.

**Comment by chinakook** [comment]
```
    def hybrid_forward(self, F, x):
        return F.contrib.BilinearResize2D(x, self.height, self.width)
```
or 
```
    def hybrid_forward(self, F, x):
        return F.BilinearResize2D(x, self.height, self.width)
```

**Comment by PKurnikov** [comment]
@chinakook ,
Thanks, this way is work!
But the function BilinearResize2D does not work with 'width' more then 1000.
Are there any alternative approaches to create interpolation layer without this restrictions?

> value 1025 for Parameter width exceed bound [1,1000], in operator _contrib_BilinearResize2D(name="", height="513", width="1025")

**Comment by chinakook** [comment]
I don't know. I think this op is weird.

**Comment by spidyDev** [comment]
@reminisce : Please label as : Gluon, question, operator

**Comment by nswamy** [comment]
Questions are best answered on discuss.mxnet.io. Please take post your question there. I am closing this issue for now.
