### ISSUE TITLE
Reshape network

### ISSUE THREAD

**Issue by smartadpole** [apache/incubator-mxnet#10611]
## Description
In c/c++ code,
How to reshape a network created by ```MXPredCreate```.
The ```MXPredReshape``` is not exported.

e-mail:smartadpole@163.com

**Comment by chinakook** [comment]
https://github.com/apache/incubator-mxnet/pull/10612

**Comment by spidyDev** [comment]
@nswamy  Please tag this as : Question , Feature

**Comment by smartadpole** [comment]
@chinakook 谢谢您的回答。我还有几个问题:
“Add MXPredReshape API MXNET_DLL prefix” 的操作是mxnet的开发者做吗，还是我做？我做的话可能要重编源码，是这样吗？
既然现在要导出MXPredReshape ，为什么一开始没有这样做呢？是编码失误，还是设计需求。
每一次测试时，我用创建和销毁网络替代了reshap，这个问题暂时解决了。但是遇到了另一个问题，我从“MXPredGetOutput”得到了网络的输出，但是不知道数据是怎么组织的，没办法解析。网络是想R-CNN一样的物体检测网络。
————————————————————————————————————————————————
@chinakook Thank you for your help. I also have two question:
-   Should the mxnet author add the ```Add MXPredReshape API MXNET_DLL prefix ```  feature, or should I do it?
-   Why wasn't ```Add MXPredReshape API MXNET_DLL prefix ``` included  in the original version?
-   The output that I recieved from  ```MXPredGetOutput``` should've been similar to other object detection networks, such as R-CNN.  However, I don't understand how the ```MXPredGetOutput`` is organized.
Which language do you want to communicate with？
  




smartadpole@163.com
 
From: chinakook
Date: 2018-04-19 19:57
To: apache/incubator-mxnet
CC: 小白鼠; Author
Subject: Re: [apache/incubator-mxnet] Reshape network (#10611)
#10612

**Comment by chinakook** [comment]
You only need to compile the newest mxnet by yourself. Then the MXPredReshape can be used on windows.
