### ISSUE TITLE
8 gpu no speed up, delay caused by main thread

### ISSUE THREAD

**Issue by chengdazhi** [apache/incubator-mxnet#10627]
Hi all,

I am running resnet backbone on 4 gpus, and when we try to use all 8, it provides no speed-up. We have pinned down the problem to the main thread, specifically, the **training loop**. I understand that all computations and real forward are done on GPUs asynchronously, but still the main thread need to call the python commands like self.conv1(data) to start building computation graphs and perhaps allocate some resources. I have confirmed this as the speed bottleneck. What confuses me is that when I called hybridize, 8 gpus is still only 20% faster than 4 gpus. Why is hybrid_forward so time consuming? How can I bypass this problem and really utilize my nuclear weapons?

**Comment by chengdazhi** [comment]
@piiswrong Hi Junyuan, any suggestions?

**Comment by piiswrong** [comment]
We are working on optimizing gluon performence. One of the things we are trying is using multiple threads for forward. see https://github.com/apache/incubator-mxnet/pull/10536

for now you can train two models on 4 gpus each...

**Comment by piiswrong** [comment]
btw what gpus are you using?

**Comment by chengdazhi** [comment]
Thanks Junyuan, I am using all Titan X.

Multi thread forwarding would be really nice~
