### ISSUE TITLE
[Feature Request] Gluon model zoo allow fine-tuning

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#10638]
Currently it is a little bit of a faff to fine-tune a model from the model-zoo.
The straight dope takes the option of downloading both the pre-trained and non-trained model and assigning the trained features to the non-trained model.
http://gluon.mxnet.io/chapter08_computer-vision/fine-tuning.html
As done in the naming tutorial, you can also re assign the `.output` layer of the model from the model zoo but that again requires knowledge of the code.

I propose that when calling:
```python
vision.resnet18_v1(pretrained=True, classes=10)
```
instead of getting an error with:
```
AssertionError: Failed loading Parameter 'resnetv10_dense0_weight' from saved params: shape incompatible expected (10, 512) vs saved (1000, 512)
```
We get the pre-trained model with the last layer replaced with a 10-unit dense layer, which makes more sense from a user perspective.

**Comment by szha** [comment]
The semantics of such call might be ambiguous. Given that we already consistently name the network parts as "features" and "output", I think an easier approach is to just document this structure and make it a convention.

**Comment by ThomasDelteil** [comment]
I agree that documenting the structure of the network would be very helpful to start with. And also documenting the fact that the `classes` argument is only valid with `pre_trained=False`, in the docs and by throwing an appropriate exception. 

However I don't really see the ambiguity in the semantics? Could you elaborate in which case there would be ambiguity?

**Comment by ThomasDelteil** [comment]
Also @szha , I think another common use case is to use a network as a featurizer. Currently the only way I found without going to the symbolic representation is to replace the output layer with a dense layer without bias and with the identity matrix as weight. It would be nice if we could have an option to set `Featurizer=True` and it would set the output layer to a pass-through `HybridLambda` for example.

**Comment by szha** [comment]
In the proposed design, without the knowledge of actual implementation, the call may either be interpreted as "get me a pre-trained model and replace the output layer with a size of 10", or "get me a pre-trained model that was trained on 10 classes".

For using the network as feature extractor, simply use the net.features block.

**Comment by ThomasDelteil** [comment]
:+1: that's much simpler indeed, thanks. Maybe having a `PreTrained` class that documents the `.features` and `.output`, and various usage could be a good idea.

I see the ambiguity now, one way to circumvent this ambiguity could be that setting specifically the number of classes means getting an untrained last layer. But the issue would be that it is not backward compatible with people having already set pre_trained=True and num_class=1000 :/ Though we could make an exception for these and returning the pre-trained layer.

**Comment by ThomasDelteil** [comment]
I have been thinking about that a bit more and giving a number of class for a pre-trained model does not make sense really. It could 10 class for MNIST, FashionMNIST or CIFAR10. We should have the pre-trained model rather being conditioned on a given dataset: e.g `ImageNet1000`, `CIFAR10`, `mnist`, `Caltech_256`, etc.

**Comment by szha** [comment]
Indeed. The moving parts in the model architectures are:
1. dataset can have different tasks/number of classes
2. input data shape can vary by dataset

Given the architecture, users may further want to get models w/ or w/o pre-trained weights.

This can be one of the APIs that can benefit from some redesign if we indeed start to support pre-trained models on more datasets.

**Comment by spidyDev** [comment]
@ThomasDelteil  Could you please tag: Gluon, FeatureRequest.

**Comment by spidyDev** [comment]
@ThomasDelteil  sorry about that.
@sandeep-krishnamurthy  Please tag this as: Gluon, FeatureRequest.

**Comment by ThomasDelteil** [comment]
Agree with @zhreshold and @piiswrong proposed API. Also note that currently the error for case 2) is quite confusing, this should be improved to explain the incompatibility and point to the proper API call for fine-tuning.

**Comment by ShownX** [comment]
Is it possible to give the pre-trained model link directly on the website as before?
Now I have to write the script and call the function ```get_model_file``` and copy to somewhere.

**Comment by szha** [comment]
This issue has been mostly fulfilled with the various supports in the Gluon toolkits
