### ISSUE TITLE
How to get internal output with C++ API?

### ISSUE THREAD

**Issue by zhaoxy2018** [apache/incubator-mxnet#10634]
I want to get some intermediate results in the network with the C++ API. I found an old issue but the link suggested in the solution (https://github.com/dmlc/mxnet/tree/master/example/cpp/image-classification) is no longer valid now. So what is the proper way to inspect network intermediate results with the new C++ API?

**Comment by chinakook** [comment]
```	int device_type = 1;
	int device_id = 0;
	const char *input_keys[1];
	input_keys[0] = "data";
	const char *out_keys[1];
	out_keys[0] = "your_internal_output";
	const mx_uint input_shape_indptr[] = { 0, 4 };
	const mx_uint input_shape_data[] = { 1,3,static_cast<mx_uint>(data_shape_), static_cast<mx_uint>(data_shape_) };

	predictor_ = NULL;

	int err = MYPredCreatePartialOut(json_buffer.c_str(), param_buffer.data(), static_cast<int>(param_buffer.size()),
device_type, device_id, 1, input_keys, input_shape_indptr, input_shape_data, 1, out_keys, &predictor_);
```

**Comment by spidyDev** [comment]
@zhaoxy2018  Please close this issue if your question is answered.

**Comment by zhaoxy2018** [comment]
@chinakook Can you kindly point me a complete code example?

**Comment by zhaoxy2018** [comment]
@chinakook thanks~~
