### ISSUE TITLE
Mxnet cu90 on Windows

### ISSUE THREAD

**Issue by leedstark** [apache/incubator-mxnet#10640]
## Description
I've installed Mxnet using pip install mxnet-cu90, when I import the package it doesn't get recognized.

## Environment info 
Windows 64 bit
Anaconda virtual env
Python 3.6
GPU Nvidia capability 5.0
CUDA 9.0 installed

## What have you tried to solve it?

1. I've tried mxnet CPU and it worked.

**Comment by r4ghu** [comment]
Did you install CuDNN? I guess you also need to install a right version of compatible cuDNN to make it work.

**Comment by leedstark** [comment]
Yes CuDNN 7 is installed and other Deep learning frameworks (Mxnet, TensorFlow) work very well with the GPU.

**Comment by leedstark** [comment]
It actually works well now. I had two version of CUDA installed. I just disabled the old one.
