### ISSUE TITLE
The tile layer as caffe 

### ISSUE THREAD

**Issue by rainfalj** [apache/incubator-mxnet#10667]
How can I implement a tile layer with axis and tiles param when using symbol API?

**Comment by chinakook** [comment]
mx.symbol.tile

**Comment by rainfalj** [comment]
@chinakook but it has no axis param

**Comment by nswamy** [comment]
You can implement your own operator in MXNet either in C++ or in Python, please refer to the documentation here: https://mxnet.incubator.apache.org/faq/add_op_in_backend.html 
https://mxnet.incubator.apache.org/tutorials/gluon/customop.html. I will close this issue please use https://discuss.mxnet.io for questions and seek help to implement the operator similar to Caffe
