### ISSUE TITLE
mismatch of padding in conv between MXNet and ONNX

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#10663]
MXNet conv currently assumes a tuple of 2 elements (height, width), while ONNX uses a tuple of 4 elements (left, right, top, bottom). Currently, when MXNet loads a ONNX model, it still uses a padding tuple of 4 elements.

The current implementation of MXNet conv doesn't check the number of elements in the tuple and just uses the first two elements in the tuple. For symmetric padding, this issue is currently ignored by MXNet.

The ideal solution should be:

- [ ]  fix the ONNX converter so that it loads the padding correctly, so MXNet always gets a padding tuple with 2 elements.
- [ ] check the parameters of the operators to make sure the inputs are correct.

@ThomasDelteil said there are some potential use cases that might require padding of (left, right, top, bottom).

@eric-haibin-lin @piiswrong @lupesko

**Comment by nswamy** [comment]
@aanirud

**Comment by nswamy** [comment]
@anirudhacharya

**Comment by anirudhacharya** [comment]
fix - https://github.com/apache/incubator-mxnet/pull/10676

**Comment by anirudhacharya** [comment]
@zheng-da can you verify and close this issue?
