### ISSUE TITLE
R installation on MacOS fails (file not found)

### ISSUE THREAD

**Issue by cells2numbers** [apache/incubator-mxnet#10675]
The installation of mxnet fails on MacOS using RStudio because the file mxnet_0.10.1.tar.gz is not found. Probably the file is outdated. Could it be replaced / updated? 

Infos about  the environment info:
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
```

Code and error message for reproduction:
```
> install.packages("mxnet")
Installing package into ‘/usr/local/lib/R/3.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed
> 
```

**Comment by PastequeZ** [comment]
Hello,
I have the same issue when I tried to install version 0.10.1 but have error with:
 URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/macosx/mavericks/contrib/3.3/PACKAGES.gz': status was '404 

I have
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.1

**Comment by anirudhacharya** [comment]
If you are using R version ``R version 3.4.3 (2017-11-30)`` it should work fine now. Try the instructions here - http://mxnet.incubator.apache.org/install/index.html?platform=MacOS&language=R&processor=CPU

@cells2numbers please verify and close the issue accordingly
