### ISSUE TITLE
MXNet conv should check the number of elements in strides, padding, etc.

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#10689]
MXNet conv doesn't check the number of elements in strides, padding, etc.

Below is the code from @anirudh2290 that generates the bug.

```python
import mxnet as mx
arr = mx.nd.random.uniform(shape=(10, 10, 32, 32))
weight1 = mx.nd.random.uniform(shape=(10, 10, 3, 3))
arr1 = mx.nd.Convolution(data=arr, weight=weight1, no_bias=True, kernel=(3, 3), stride=(1), num_filter=10)
arr2 = mx.nd.Convolution(data=arr, weight=weight1, no_bias=True, kernel=(3, 3), stride=(1, 1), num_filter=10)
print((arr1 == arr2).asnumpy().sum())
```
This outputs 2616.0, while we expect 3000 because the output shape is (10L, 10L, 30L, 1L).

**Comment by wkcn** [comment]
It seems that the shape of arr1 is (10,10,30,1), and the shape of arr2 is (10,10,30,30).
The cpu output is 3000 in MXNet 1.2.0 (0ca6dd29).
However, In MXNet 1.1.0 (pip install), the program crashed and return 'Command terminated
'.

**Comment by zheng-da** [comment]
we now check the strides and paddings: https://github.com/apache/incubator-mxnet/pull/10666
