### ISSUE TITLE
How  do I install mxnet on Termux?

### ISSUE THREAD

**Issue by python3-pip** [apache/incubator-mxnet#10684]
I want run mxnet on mobile phone, but when I run:  
`pip install mxnet`
It says:
```
Collecting mxnet
    Could not find a version that satisfies the requirement mxnet (from versions: )
    No matching distribution found for mxnet
```
I tried it to build from source, but it says:
`RuntimeError: Cannot find the MXNet libaray.`

What should I do?

**Comment by wkcn** [comment]
You could compile the source code of MXNet.
I tried it in Termux but it took a long time.

**Comment by python3-pip** [comment]
@wkcn Thanks, but what should I run command?
