### ISSUE TITLE
Is the "gradient compression" only suitable for range_pull?

### ISSUE THREAD

**Issue by hbsun2113** [apache/incubator-mxnet#10699]
Is the "gradient compression" only suitable for range_push,not suitable for hash_push?

**Comment by hbsun2113** [comment]
@rahul003

**Comment by rahul003** [comment]
Could you clarify what you are referring to by hash_push or range_push?

**Comment by hbsun2113** [comment]
@rahul003
![image](https://user-images.githubusercontent.com/27994442/39345992-6d182c42-4a1e-11e8-91bc-2cc3bfb74f40.png)
I think it is the range_push.Can mxnet push or pull by hash kv?

**Comment by nswamy** [comment]
Please ask question https://discuss.mxnet.io, its the best place to get answers/feedback from maintainers and other users.

**Comment by ThomasDelteil** [comment]
@hbsun2113 The code you highlighted gives you the number of servers for the key value store, it isn't related to pushing a range of values of keys to the kvstore. If that was your original question.

@nswamy can you please close this issue?
@hbsun2113 please consider closing as well, if you feel your question has not been answered, please write a post on discuss.mxnet.io as suggested by @nswamy
