### ISSUE TITLE
Problems building and running mxnet on machines with no AVX2 support

### ISSUE THREAD

**Issue by redpine42** [apache/incubator-mxnet#10705]
I'm having problems building and running mxnet from this repo on machines that don't support AVX2.  

I can build and run on machines support AVX2.
I'm following these instructions for a docker build and I've configured for distributed processing ( USE_DIST_KVSTORE=1).  https://mxnet.incubator.apache.org/install/index.html

Below is the dockerfile instructions.

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y wget build-essential git libopenblas-dev liblapack-dev \
    libopencv-dev

RUN cd / && git clone --recursive https://github.com/apache/incubator-mxnet && cd incubator-mxnet && \
    make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_DIST_KVSTORE=1

RUN apt-get install -y python-dev python-setuptools python-pip libgfortran3

RUN python -m pip install --upgrade pip && \
    pip install --upgrade setuptools

RUN cd /incubator-mxnet/python && pip install -e .

RUN mkdir /root/.ssh && chmod 700 /root/.ssh
ENV PYTHONPATH=/incubator-mxnet/python
```
I can build and run on  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz.

This fails a run on an E5-2690.  I also can not build on this machine.

Both machinces are running on Centos 7.

**Comment by redpine42** [comment]
Build error one E5-2690

```
Step 6/8 : RUN bash && cd /incubator-mxnet/python && pip install -e .
 ---> Running in 8b11a421dfef
Obtaining file:///incubator-mxnet/python
Collecting numpy<=1.15.0,>=1.8.2 (from mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/76/4d/418dda252cf92bad00ab82d6b                                                                                                                                                        2a856e7843b47a5c2f084aed34b14b67d64/numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (1                                                                                                                                                        2.1MB)
Collecting requests<2.19.0,>=2.18.4 (from mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d                                                                                                                                                        9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting graphviz<0.9.0,>=0.8.1 (from mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/05/e4/8fcc76823534d47f079c0ff1b                                                                                                                                                        3d8b57784e8fba63ceb1ded32c9f4dd993c/graphviz-0.8.2-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b                                                                                                                                                        65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb                                                                                                                                                        1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<2.7,>=2.5 (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b99                                                                                                                                                        2838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
Collecting urllib3<1.23,>=1.21.1 (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223                                                                                                                                                        e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
Installing collected packages: numpy, certifi, chardet, idna, urllib3, requests, grap                                                                                                                                                        hviz, mxnet
  Running setup.py develop for mxnet
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__fi                                                                                                                                                        le__='/incubator-mxnet/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);c                                                                                                                                                        ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" d                                                                                                                                                        evelop --no-deps:

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/incubator-mxnet/p                                                                                                                                                        ython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r                                                                                                                                                        \n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed                                                                                                                                                         with error code -4 in /incubator-mxnet/python/
The command '/bin/sh -c bash && cd /incubator-mxnet/python && pip install -e .' retur                                                                                                                                                        ned a non-zero code: 1
```

**Comment by marcoabreu** [comment]
Hi @redpine42, the error-log is cut off

**Comment by redpine42** [comment]
@marcoabreu   Log is fixed now.

**Comment by marcoabreu** [comment]
@szha do you have an idea?

**Comment by marcoabreu** [comment]
@anirudh2290 potential blocker?

**Comment by sl1pkn07** [comment]
i'm not sure if is a same problem. but i get segfault if try to build the python module as traditional method:

`python setup.py build`

**Comment by anirudh2290** [comment]
@marcoabreu checking now.

**Comment by anirudh2290** [comment]
hi @redpine42 do you know if i can reproduce this issue on an ec2 instance ?

**Comment by redpine42** [comment]
I tried USE_SSE=0 and same problem.  I did find -msse3 in a grep of files from the source. Not sure if that causes the problem.

**Comment by anirudh2290** [comment]
@redpine42 can you run lscpu and provide the output. I think the issue is related to https://github.com/apache/incubator-mxnet/issues/10541. In general, mxnet currently assumes that if you are not running certain versions of clang or msvc compiler, you have f16c hardware support and tries to compile f16c specific constructs. #10541 also seems to be related. Is there a reason to not have a flag for this in MXNet (USE_F16C) to provide people who don't have the hardware support  with a workaround ? @piiswrong @rahul003

**Comment by redpine42** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz
Stepping:              7
CPU MHz:               1199.634
CPU max MHz:           3800.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.16
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts

**Comment by redpine42** [comment]
@anirudh2290 Thanks that fixed the build.

**Comment by rahul003** [comment]
@redpine42 Could you try running this command and tell me what it shows?

`cat /proc/cpuinfo | grep flags | grep f16c` Your case should be autodetected and f16c should be turned off (if you are compiling on the CPU whose output you listed above). I wonder if Centos 7 doesn't have this file which I was checking.

**Comment by redpine42** [comment]
It returns nothing.

**Comment by sl1pkn07** [comment]
my machive have this flag and fail if use with USE_F16C=1 / DCOMPILER_SUPPORT_MF16C=ON

my solution is remove the `-O3` options from all makefile/cmakelists (include subprojects in 3rdparty) and all Build OK without (aparently) problems

related: https://github.com/apache/incubator-mxnet/issues/10558

anyone can test it?

greetings

**Comment by rahul003** [comment]
@redpine42 This PR should fix your issue. Can you confirm that it does?
https://github.com/dmlc/mshadow/pull/335

**Comment by rahul003** [comment]
@sl1pkn07 It's a good workaround, but -O2 means fewer optimizations done by the compiler. So we need to see what to do.
