### ISSUE TITLE
question: how to speed up the process of feeding data.

### ISSUE THREAD

**Issue by GoodJoey** [apache/incubator-mxnet#10716]
hi, i tried to do the training on the 8 gpus server, but it turns out that it's not faster than when using 4 gpus.
The most likely reason is the GPUs are faster than the processes that load and prepare the data, because i observed the gpu's utility goes down to 0% time by time.
is there any ways to speed up the data feeding process? like use multiple cpus to do the data loading?
Thanks.

**Comment by rahul003** [comment]
Are you using the gluon or symbolic interface?

**Comment by rocketbear** [comment]
Using gluon's Dataset + DataLoader way to load the data, and use num_workers=num_of_cpu_cores for the DataLoader. This is much faster than using the old mx.io.DataIter, as I have tested.
