### ISSUE TITLE
typo in cpp-package/CMakeLists.txt

### ISSUE THREAD

**Issue by sl1pkn07** [apache/incubator-mxnet#10742]
https://github.com/apache/incubator-mxnet/blob/6bef58a920506e6cc2848ffd4ec3b4d5bce6120a/cpp-package/CMakeLists.txt#L19

should be ` if(BUILD_CPP_EXAMPLES)` ? or ` if(WITH_EXAMPLE)`

greetings

**Comment by nswamy** [comment]
seems like its doing the right NOT and DO_NOT ==> build with examples. sure, naming could been better 
https://github.com/apache/incubator-mxnet/pull/9832

**Comment by sl1pkn07** [comment]
this option is not expose in cmake options (gmake-gui)) and is alwaya build by default

**Comment by sl1pkn07** [comment]
hi, ani notice of this?

greetings

**Comment by marcoabreu** [comment]
Sorry, seems like I lost track of this issue. I currently don't have time to work on this issue, would you mind submitting a PR @sl1pkn07 ?

**Comment by sl1pkn07** [comment]
oh, no, you not. I.

seems fixed in https://github.com/apache/incubator-mxnet/pull/14562

closing

greetings and sorry the noise
