### ISSUE TITLE
libmxnet.dll crash on Windows GPU mode, pip install

### ISSUE THREAD

**Issue by XMaster96** [apache/incubator-mxnet#10747]
## Description
Python crash if I try to run MXNet on GPU (libmxnet.dll). I have pip installt MXNet, and not Built my self. The libmxnet.dll is clearly in "Lib\site-packages\mxnet". I have yousd Tensorflow befor, with the same CUDA istallation.

## Environment info (Required)
> X:\PyProjects\XMNET_TEST\venv\Scripts\python.exe X:/PyProjects/XMNET_TEST/Diag.py
> ----------Python Info----------
> Version      : 3.4.0
> Compiler     : MSC v.1600 64 bit (AMD64)
> Build        : ('v3.4.0:04f714765c13', 'Mar 16 2014 19:25:23')
> Arch         : ('64bit', 'WindowsPE')
> ------------Pip Info-----------
> Version      : 10.0.1
> Directory    : X:\PyProjects\XMNET_TEST\venv\lib\site-packages\pip
> ----------MXNet Info-----------
> Version      : 1.2.0
> Directory    : X:\PyProjects\XMNET_TEST\venv\lib\site-packages\mxnet
> Hashtag not found. Not installed from pre-built package.
> ----------System Info----------
> Platform     : Windows-7-6.1.7601-SP1
> system       : Windows
> node         : KAJO
> release      : 7
> version      : 6.1.7601
> ----------Hardware Info----------
> machine      : AMD64
> processor    : AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
> Name                                  
> AMD FX(tm)-8320 Eight-Core Processor  
> 
> ----------Network Test----------
> Setting timeout: 10
> Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3530 sec, LOAD: 5.3323 sec.
> Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0130 sec, LOAD: 1.9941 sec.
> Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0200 sec, LOAD: 0.8671 sec.
> Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0510 sec, LOAD: 0.8450 sec.
> Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.3570 sec, LOAD: 0.8810 sec.
> Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0160 sec, LOAD: 0.2370 sec.

CUDA : 8.0, 9.0, 9.1
Python: 3.4, 3.6
GPU: GTX 1080TI

## Error Message:
I got a Windows Program has crashed popup, and not a error lock. My Popup is in German, so I have to translate it.

> Problemsignatur (problem signature):
>   Problemereignisname(Problem Event Name):	APPCRASH
>   Anwendungsname(application name):	python.exe
>   Anwendungsversion(application version):	0.0.0.0
>   Anwendungszeitstempe(Application Timestamp)l:	5325ec94
>   Fehlermodulname(Fault Module Name):	libmxnet.dll
>   Fehlermodulversion(Fault Module Version):	0.0.0.0
>   Fehlermodulzeitstempel(Error module timestamp):	5ae624eb
>   Ausnahmecode(exception code):	40000015
>   Ausnahmeoffset(except offset):	0000000002b27357
>   Betriebsystemversion(Operating System Version):	6.1.7601.2.1.0.256.48
>   Gebietsschema-ID(Locale ID):	1031
>   Zusatzinformation 1(Additional information 1):	e89d
>   Zusatzinformation 2(Additional information 2):	e89d4075b7616b734d6c6404acf1dcf5
>   Zusatzinformation 3(Additional information 3):	1891
>   Zusatzinformation 4(Additional information 4):	189199de8c66545e2f92a8aef3522bcf

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Installin MXNet using pip
2. Runing Exampel code on GPU.

## What have you tried to solve it?
I Tried different Python and MXNET CUDA versions.

**Comment by aaronmarkham** [comment]
H @XMaster96 - the Windows instructions have recently been updated: https://mxnet.incubator.apache.org/install/windows_setup.html

One thing to note is that you should have CUDA, cuDNN and Visual Studio (2015 or 2017) installed before you use the mxnet-cu92 pip package.
