### ISSUE TITLE
'Take' operator should support non-zero axis values

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#10755]
The current implementation of [Take operator](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.take) is incomplete. As mentioned in the documentation, It supports slicing along only axis=0 and in ‘clip’ mode. 

The operator is intended to support other negative and non-negative values for axis. THe current implementation of the operator needs to be modified to meet multiple axis values.

@piiswrong @szha @zheng-da @haojin2 @eric-haibin-lin

**Comment by haojin2** [comment]
Supported in #11326, can close once that is merged.

**Comment by haojin2** [comment]
@nswamy Could you please change the labels to "Feature Request"? I feel like that's a better description of this issue. Our team is tracking bugs so this kind of issue could be confusing for us.

**Comment by haojin2** [comment]
@anirudhacharya #11326 has been merged, so this issue should be closed?
