### ISSUE TITLE
Start a process for training. The training get stuck

### ISSUE THREAD

**Issue by huyangc** [apache/incubator-mxnet#10788]
I start a process for training procedure, including loading data, prepare a module, and module.fit. However, when I just ran the training procedure, it can be successfully started, but when I start a process of the training procedure, it get stuck with the gpu memory allocated but GPU-Util is also 0%.

some pseudocode here
```
def train_net(args):
    sym = build_net()
    mod = mx.mod.Module(sym, ctx=gpu(0-7))
    initializer=mx.xavier
    dataiter = get_dataiter()
    mod.fit(...)

def train():
    p = mp.Process(target=train_net, args=(args,))
    p.start()
    p.join()

```

**Comment by roywei** [comment]
@huyangc Using the mnist example in a process is working fine, could you provide more detailed information? Like environment, mxnet version, and minimum reproducible code for the problem. The pseudocode has limited information. Thanks!
