### ISSUE TITLE
Unable to install mxnet in R 3.5.0

### ISSUE THREAD

**Issue by apshreyans** [apache/incubator-mxnet#10791]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Installation error on RStudio R 3.5.0
Error:   unable to access index for repository https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU/bin/windows/contrib/3.5:
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU/bin/windows/contrib/3.5/PACKAGES'

**Command Run:**
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")

(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)
R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Package used (Python/R/Scala/Julia):
**(I'm using R 3.5.0)**

For R user, please provide R `sessionInfo()`:
**SessionInfo():**
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0  

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

 no package 'knitr' was found
> install.packages('mxnet')
Installing package into ‘\\homedrive$/Shreyans.Bathiyan/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘mxnet’ is not available (for R version 3.5.0)
Error: invalid version specification ‘NA’
In addition: Warning message:
In utils:::packageDescription(packageName, fields = "Version") :
  no package 'knitr' was found
> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU"
> options(repos = cran)
> install.packages("mxnet")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("mxnet")
Installing package into ‘\\homedrive$/Shreyans.Bathiyan/R/win-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependencies ‘bindr’, ‘brew’, ‘colorspace’, ‘utf8’, ‘gtable’, ‘reshape2’, ‘lazyeval’, ‘assertthat’, ‘bindrcpp’, ‘pkgconfig’, ‘R6’, ‘BH’, ‘plogr’, ‘digest’, ‘yaml’, ‘hms’, ‘XML’, ‘Rook’, ‘dichromat’, ‘plyr’, ‘munsell’, ‘labeling’, ‘viridisLite’, ‘cli’, ‘crayon’, ‘pillar’, ‘tidyselect’, ‘ggplot2’, ‘gridExtra’, ‘dplyr’, ‘downloader’, ‘glue’, ‘htmltools’, ‘htmlwidgets’, ‘igraph’, ‘influenceR’, ‘purrr’, ‘RColorBrewer’, ‘readr’, ‘rlang’, ‘rstudioapi’, ‘rgexf’, ‘scales’, ‘tibble’, ‘tidyr’, ‘viridis’, ‘stringi’, ‘Rcpp’, ‘DiagrammeR’, ‘visNetwork’, ‘data.table’, ‘jsonlite’, ‘magrittr’, ‘stringr’

Warning in install.packages :
  unable to access index for repository https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU/bin/windows/contrib/3.5:
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU/bin/windows/contrib/3.5/PACKAGES'

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.7  1.2.2              TRUE

  Binaries will be installed
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘mxnet’

Kindly help me installing mxnet package.

**Comment by roywei** [comment]
@nswamy  Could you help to add label R and installation? Thanks!

**Comment by mangos47** [comment]
I too am having difficulty installing mxnet r package after updating to R 3.5.0.  
The error is that it cannot download the package - the address is incorrect or sth. please see log below:
------------------------------------------------------------------------------------

R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from C:/R_work/RCA_GSP_failure/APAC_setl_status/.RData]

> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
Installing package into ‘C:/Users/xbbnk69/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/windows/contrib/3.5:
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/windows/contrib/3.5/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mxnet’
installing the source package ‘mxnet’

trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing              
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19

**Comment by marcoabreu** [comment]
@sergeykolychev

**Comment by sergeykolychev** [comment]
@marcoabreu Sorry, I am a perl maintainer not R

**Comment by jeremiedb** [comment]
For CPU, you can install with : 
`install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)`

For GPU: 
`install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/GPU/mxnet.zip", repos = NULL)`

@marcoabreu Is it possible for replace the official repo at `"https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"` with the above compilation for Windows. The current ones are quite dated.

**Comment by some-guy1** [comment]
I just updated to R 3.5 and suddenly all of my MXnet code doesnt work with random errors.  

@jeremiedb is there anything that needed to change in your Windows compilation for the change to R 3.5?

The identical code worked with your compiled mxnet code with the R 3.4.4

**Comment by jakobetzel** [comment]
@jeremiedb 's mxnet (CPU) link above seems to be broken. Installing leads to the error:
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\024\0\0\0\0\0\xea\026\xadL\0\0\0\0\0\0\0\0\0\0\0\0\006\0\0\0mxnet/PK\003\004\024\0\0\0\0\0\xe9\026\xadL\0\0\0\0\0\0\0\0\0\0\0\0\v\0\0\0mxnet/demo/PK\003\004\024\0\0\0\b\0\xf0\x9e\xabL\xd5\\\aY\xa0\0\0\0\xfc'

**Comment by jeremiedb** [comment]
@jakobetzel , could you provide details on your R version and operating system? Those pre-built binaries are for Windows. I just re-tried an installation of the CPU versoin and worked fine on R 3.5 and Win10.

**Comment by jakobetzel** [comment]
@jeremiedb I do apologise, I was trying to install on Ubuntu. Sorry for inconveniences.

**Comment by onlyphantom** [comment]
@jeremiedb any chance you have a pre-built binary package of mxnet for R 3.5.0 for Mac / Linux folks? Been trying everything else so am a little desperate now. Thanks in advance!

**Comment by hetong007** [comment]
@jeremiedb I'd love to have your pre-built package to be on DMLC's CRAN image. Also, I have some questions regarding your compilation. Could you please ping me at my email (hetong007 [at] gmail)? Thanks!

**Comment by anirudhacharya** [comment]
@onlyphantom For R 3.50 on Mac, you can use [this tar](https://github.com/anirudhacharya/MLProjects/blob/master/mxnet_1.3.0.tar.gz)

**Comment by hetong007** [comment]
@anirudhacharya A better way is to update maintain it at https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/

**Comment by jeremiedb** [comment]
@onlyphantom I don't have access to Mac, but for Linux, following the instruciton should work fine (at least on Ubuntu). If you have an issue on Linux, let me know, I might be able to hlep.

**Comment by hetong007** [comment]
@onlyphantom I've updated the official S3 bucket. Please retry the installation on OS X, and feel free to comment if you can't install it by

```r
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
```

**Comment by jeromejh** [comment]
Could you help me installing MXNET in R 3.5.0 on OS? I tried to install MLProjects/mxnet_1.3.0.tar.gz but it says ackage ‘mxnet’ was built under R version 3.5.1

**Comment by hetong007** [comment]
@jeromejh  R 3.5.1 was released a few days ago. Can you please update it from https://cran.r-project.org/bin/macosx/ ?

**Comment by jeromejh** [comment]
I did just right now. But it still doesn't work. Very frustrating. Could you help me?

**Comment by hetong007** [comment]
@jeromejh please paste 

1. the error information
2. your `sessionInfo()` output

**Comment by jeromejh** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/40897593/42479584-983b1976-83a7-11e8-97f2-3c467b4ec094.png">

**Comment by jeromejh** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/40897593/42479616-bf66f4fc-83a7-11e8-8ceb-e45732a7ec80.png">

**Comment by hetong007** [comment]
@jeromejh you need to update your openblas with `brew install openblas`, or other package manager that you are familiar with.

**Comment by jeromejh** [comment]
I just tried to update it like https://gist.github.com/bmmalone/1b5f9ff72754c7d4b313c0b044c42684 but it still doesn't work..

**Comment by jeromejh** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/40897593/42480064-9e7de4e2-83a9-11e8-88d3-900e020a986d.png">

**Comment by hetong007** [comment]
please try brew install openblas, if you have brew installed.

**Comment by jeromejh** [comment]
I'm sorry but where can I run it? In R?

**Comment by jeromejh** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/40897593/42480614-5ae9bfa0-83ac-11e8-9f87-f4fac29d086f.png">

**Comment by hetong007** [comment]
please run **brew install opencv** as well.

**Comment by jeromejh** [comment]
Thank you so much. Not it works! I appreciate it!

**Comment by kmezhoud** [comment]
HI,
In my case is not yet resolved

```r
brew install openblas
brew install opencv
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
library("mxnet", lib.loc="/Library/Frameworks/R.framework/Versions/3.5/Resources/library")
```
```r
Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found
```

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.1.0

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4   Rook_1.1-1         purrr_0.2.5        colorspace_1.3-2   htmltools_0.3.6   
 [6] viridisLite_0.3.0  yaml_2.2.0         XML_3.98-1.16      rlang_0.2.2        pillar_1.3.0      
[11] later_0.7.4        glue_1.3.0         RColorBrewer_1.1-2 bindrcpp_0.2.2     bindr_0.1.1       
[16] plyr_1.8.4         stringr_1.3.1      munsell_0.5.0      gtable_0.2.0       visNetwork_2.0.4  
[21] htmlwidgets_1.2    httpuv_1.4.5       DiagrammeR_1.0.0   Rcpp_0.12.18       xtable_1.8-3      
[26] readr_1.1.1        scales_1.0.0       promises_1.0.1     jsonlite_1.5       rgexf_0.15.3      
[31] mime_0.5           gridExtra_2.3      brew_1.0-6         ggplot2_3.0.0      hms_0.4.2         
[36] digest_0.6.16      stringi_1.2.4      dplyr_0.7.6        grid_3.5.1         influenceR_0.1.0  
[41] tools_3.5.1        magrittr_1.5       lazyeval_0.2.1     tibble_1.4.2       crayon_1.3.4      
[46] tidyr_0.8.1        pkgconfig_2.0.2    downloader_0.4     assertthat_0.2.0   rstudioapi_0.7    
[51] viridis_0.5.1      R6_2.2.2           igraph_1.2.2       compiler_3.5.1 
```

**Comment by hetong007** [comment]
@kmezhoud This two lines are supposed to run in your command line console:

```
brew install openblas
brew install opencv
```

**Comment by kmezhoud** [comment]
@hetong007 Yes

**Comment by hetong007** [comment]
@kmezhoud  Can I have your output from `brew info openblas`? It seems to me that your installation of openblas is not valid, or not 0.3.1, however it is the latest version from brew on my system.

**Comment by kmezhoud** [comment]
@hetong007 
```
 brew install openblas
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask, homebrew/core).
==> Updated Formulae
checkbashisms                                  kakoune                                        sphinx-doc

Warning: openblas 0.3.3 is already installed and up-to-date
To reinstall 0.3.3, run `brew reinstall openblas`
```

**Comment by anirudhacharya** [comment]
@kmezhoud Try to link your openblas installation to v0.3.1 with the following statement and then try `library(mxnet)` on an R console
```
ln -sf /usr/local/opt/openblas/lib/libopenblasp-r0.3.3.dylib /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
```

**Comment by kmezhoud** [comment]
@anirudhacharya it works now 👍 
Many thanks

**Comment by JiaxiangBU** [comment]
I also have a problem to install `openblas` on Mac for R and CPU @ v1.3.0.
The err message is here.

```
$ brew install openblas@0.3.1
Error: No available formula with the name "openblas@0.3.1" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
$ ln -sf /usr/local/opt/openblas/lib/libopenblasp-r0.3.* /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
ln: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib: No such file or directory
```

And when I library the pkg, the err message is here.

``` r
library(mxnet)
#> Error: package or namespace load failed for 'mxnet':
#>  loadNamespace()里算'mxnet'时.onLoad失败了，详细内容：
#>   调用: dyn.load(file, DLLpath = DLLpath, ...)
#>   错误: 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so’：:
#>   dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
#>   Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so
#>   Reason: image not found
```

Created on 2018-10-24 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by anirudhacharya** [comment]
@JiaxiangBU could you try running just `brew install openblas` and then run the softlink command.

**Comment by JiaxiangBU** [comment]
Hi @anirudhacharya, I tried this code, and the command told me to reinstall it.

```
$ brew install openblas
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
shellz
==> Updated Formulae
advancecomp     evince          imagemagick@6   pdfpc           tippecanoe
arangodb        grafana         jbake           planck          vault
ark             httpd           minizinc        skafos
bluepill        imagemagick     node-build      terraform-docs

Warning: openblas 0.3.3 is already installed and up-to-date
To reinstall 0.3.3, run `brew reinstall openblas`
```

Here is the result of re-installation.

```
brew reinstall openblas
==> Reinstalling openblas 
==> Downloading https://homebrew.bintray.com/bottles/openblas-0.3.3.high_sierra.
Already downloaded: /Users/vija/Library/Caches/Homebrew/downloads/eeb066071ee951d9d6d73d9df42678ead1f37f52cb769b884d8a69cf1eecd66f--openblas-0.3.3.high_sierra.bottle.tar.gz
==> Pouring openblas-0.3.3.high_sierra.bottle.tar.gz
==> Caveats
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openblas/0.3.3: 21 files, 115.5MB
```

And I get this error.

```
$ ln -sf /usr/local/opt/openblas/lib/libopenblasp-r0.3.* /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
ln: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib: No such file or directory
```

I think there is a file I miss. Becuase I don't specify the version of `openblas`.
I am still working on it.

**Comment by IrinaMax** [comment]
I have the same error as JiaxiangBU. 
Followed installation on brew and then got error:

```
> $ ln -sf /usr/local/opt/openblas/lib/libopenblasp-r0.3.3.dylib /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
> ln: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib: No such file or directory
```

 Then in R-studio : 
> cran <- getOption("repos")
```
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/macosx/el-capitan/contrib/3.5/mxnet_1.3.0.tgz'
Content type 'application/x-tar' length 10369234 bytes (9.9 MB)
==================================================
downloaded 9.9 MB
The downloaded binary packages are in
	/var/folders/xk/zqkqv02j627g4_jw9hh8hfym0000gn/T//RtmpIuGUr2/downloaded_packages
```
`> library("mxnet", lib.loc="/Library/Frameworks/R.framework/Versions/3.5/Resources/library")
Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found`
