### ISSUE TITLE
CMake ignores USE_MKLDNN flag for 1.2.0.RC[0-2] releases

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#10801]
CMake ignores the `USE_MKLDNN` flag for 1.2.RC2 release. This has been fixed in the master as part of #10731. To workaround the issue on 1.2.RC2 release, please apply the following changes in CMakeLists.txt:

```
 if(USE_MKL_IF_AVAILABLE)
   if(USE_MKLDNN)
+    set(ARCH_OPT_FLAGS "-mtune=generic")
     add_subdirectory(3rdparty/mkldnn)
     include_directories(3rdparty/mkldnn/include)
+    add_definitions(-DMXNET_USE_MKLDNN=1)
     list(APPEND mxnet_LINKER_LIBS mkldnn)
   endif()
   find_package(MKL)
```

**Comment by roywei** [comment]
@anirudh2290  could you add relevant labels (build/MKL) to keep track?  Thanks
