### ISSUE TITLE
How to fix seeds and reproduce results?

### ISSUE THREAD

**Issue by zzd1992** [apache/incubator-mxnet#10831]
My environments:
ubuntu14.04, python2.7, cuda8.0, cudnn, mxnet-cu80.

I can't reproduce results even set all random seeds. Here is the code:
```python
import mxnet as mx
import numpy as np
import random

mx.random.seed(args.seed)
np.random.seed(args.seed)
random.seed(args.seed)
```

Reproduction is really important in my case.
How can I reproduce results within my environments?

**Comment by asitstands** [comment]
Would you please pin down which function shows random behaviour with the same seeds? If you can provide a minimal code reproducing the problem, it would be the best.

**Comment by fhieber** [comment]
Afaik `mx.random.seed` sets the seed also based on the device id. Do you happen to use different device ids across multiple runs?

**Comment by zzd1992** [comment]
@fhieber I just have a single GPU.

**Comment by zzd1992** [comment]
@asitstands Roughly, I build Resnet and load cifar10 dataset in main.py.
The data augment function is defined in utils.py which involves np.random and random.
I just set the random set in main.py.

**Comment by roywei** [comment]
@zzd1992 seem that you are using same seed, but the accuracy is still different, so this may not related to random seed? Could you provide a minimum reproducible example and more details like how many epoch did you test and what's the accuracy different? Thanks

@nswamy  could you help to add label Metric and Pending Requester Info? Thanks

**Comment by piyushghai** [comment]
@zzd1992 Can you update your findings with regards to inconsistent outputs with same seeds ?

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.
