### ISSUE TITLE
Share Numpy Arrays between processes like NDArrays?

### ISSUE THREAD

**Issue by squidszyd** [apache/incubator-mxnet#10834]
(This thread is actually irrelevant to MXNet, but nowhere could I find better than here)
I'm working on a multi-processing system in which I want to transfer Numpy arrays between processes. However, this introduces lags of pickling and unpickling arrays. I've just found [this code](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/dataloader.py) in Gluon in which the pickling and unpickling of NDArray are overrided with the support of cpu shared memory. I'm curious about whether there is an Numpy Array version of this code?

**Comment by roywei** [comment]
@squidszyd Could you also raise your question at https://discuss.mxnet.io/ and stackoverflow?
@sandeep-krishnamurthy could you help to add label Question? Thanks

**Comment by sandeep-krishnamurthy** [comment]
Please ask usage related questions at https://discuss.mxnet.io/ for more people being able to answer, search and refer in future. We want to keep GitHub for issues/bugs.
