### ISSUE TITLE
Feature request - einsum

### ISSUE THREAD

**Issue by altosaar** [apache/incubator-mxnet#10840]
Useful for writing models: https://rockt.github.io/2018/04/30/einsum

**Comment by roywei** [comment]
@sandeep-krishnamurthy  could you help to add label Feature Request? Thanks

**Comment by jasonyu1996** [comment]
I am interested in implementing this. Has anyone already started working on this?

**Comment by sandeep-krishnamurthy** [comment]
@jasonyu1996 - Thanks for looking into this issue, as far as I know, nobody is working on this feature. Contributions are welcome. Let us know, if you need any help.

**Comment by jasonyu1996** [comment]
@sandeep-krishnamurthy It seems that it is somewhat complicated to implement einsum in the backend. But I would like to have a try first. Thanks!

**Comment by jasonyu1996** [comment]
@sandeep-krishnamurthy I am not sure whether this should be implemented in the backend. It needs to be based on several other operators, as it would be complicated and inefficient to directly forward and backward as a whole (especially backward). Could you point to me where I should work if I need to use other operators? Or, alternatively, is there a way of storing temporary data in forward for use in backward? Thanks!

**Comment by sandeep-krishnamurthy** [comment]
Operators are stateless, but, I remember there is a optimization switch, that enables saving data from forward pass to be used in backward pass to make the computation faster.
@azai91 - Can you please help here?

**Comment by jasonyu1996** [comment]
Would it be good then to implement it as a `HybridBlock`?

**Comment by jasonyu1996** [comment]
I have almost finished the implementation, save some polishing and testing. The current solution is not in the backend, but alongside `Block`. To allow one piece of code to support both `ndarray` and `symbol` at the same time, it uses the same idea as `HybridBlock`. The difference is that for `HybridBlock` there might be parameters inside and it is necessary to instantiate and possibly hybridize it before use, whereas an operator has its interfaces exposed in `mxnet.ndarray` and `mxnet.symbol`, and should look the same as other operators 'imported' from the backend.

I think this is probably a decision on the design, as it means a new interface for developing new operators.

**Comment by yifeim** [comment]
May I follow up what is the current state of einsum? It is convenient at times and most useful, perhaps, for its autograd computation.

**Comment by jasonyu1996** [comment]
@yifeim I have actually implemented one based on the high-level interfaces. However, it supports only the Gluon interface. I guess to add support for Symbol I have to move onto a lower abstraction layer, or rely on some missing high-level interfaces (#12484 for example).

@altosaar @roywei @sandeep-krishnamurthy I would be grateful if you can help.

**Comment by yifeim** [comment]
See https://github.com/apache/incubator-mxnet/pull/13244 for an example about how to export gluon models.

**Comment by sxjscience** [comment]
We now have einsum in the numpy interface of MXNet. Thus, close this issue.
