### ISSUE TITLE
"WindowsError: [Error 126]" and "ImportError: cannot import name libinfo"

### ISSUE THREAD

**Issue by whria78** [apache/incubator-mxnet#10854]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

The first error is "WindowsError: [Error 126]"
The second error is "ImportError: cannot import name libinfo"

## Environment info (Required)

Windows 10 64bit with full recent updates
Python 2.7.14
pip install mxnet-cu91 (mxnet-cu90 and mxnet-cu80 make the same problem, whereas mxnet CPU version works well.)

I tested with 2 computers and I had the same error.
I installed Nvidia driver & CUDA 9.1, and BVLC Caffe GPU mode works well on the same windows environment.

## Error Message:
(Paste the complete error message, including stack trace.)

```
C:\Users\whria>pip install mxnet-cu91
Collecting mxnet-cu91
  Using cached https://files.pythonhosted.org/packages/56/20/92638b338feb87f54f9d943a4bf5c2075e65b590915e5c0de1387a96ab76/mxnet_cu91-1.1.0.post0-py2.py3-none-win_amd64.whl
Requirement already satisfied: requests in c:\anaconda2\lib\site-packages (from mxnet-cu91)
Requirement already satisfied: numpy in c:\anaconda2\lib\site-packages (from mxnet-cu91)
Requirement already satisfied: graphviz in c:\anaconda2\lib\site-packages (from mxnet-cu91)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\anaconda2\lib\site-packages (from requests->mxnet-cu91)
Requirement already satisfied: idna<2.7,>=2.5 in c:\anaconda2\lib\site-packages (from requests->mxnet-cu91)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\anaconda2\lib\site-packages (from requests->mxnet-cu91)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda2\lib\site-packages (from requests->mxnet-cu91)
Installing collected packages: mxnet-cu91
Successfully installed mxnet-cu91-1.1.0.post0

C:\Users\whria>python
Python 2.7.14 | packaged by conda-forge | (default, Mar 30 2018, 18:30:38) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\mxnet\__init__.py", line 25, in <module>
    from . import engine
  File "C:\Anaconda2\lib\site-packages\mxnet\engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "C:\Anaconda2\lib\site-packages\mxnet\base.py", line 111, in <module>
    _LIB = _load_lib()
  File "C:\Anaconda2\lib\site-packages\mxnet\base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Anaconda2\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\mxnet\__init__.py", line 25, in <module>
    from . import engine
  File "C:\Anaconda2\lib\site-packages\mxnet\engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "C:\Anaconda2\lib\site-packages\mxnet\base.py", line 30, in <module>
    from . import libinfo
ImportError: cannot import name libinfo

```

The first error is "WindowsError: [Error 126]"
The second error is "ImportError: cannot import name libinfo"

## What have you tried to solve it?

I added windows PATH ; I also tried to add os.environment['path'] in python script.

**Comment by zhreshold** [comment]
WindowsError: [Error 126] indicates that there's `SOME` missing dlls, either not in PATH or missing. Unfortunately, windows won't tell you which one is missing. So it's kind of bad experience to debug what's going wrong.

Can you make sure your PATH include cuda dlls and vc++ runtime dlls?

```
echo $PATH$
```

**Comment by whria78** [comment]
Thank you for the advices.

I found the fact that CUDA 9.1 was not installed correctly in windows 10.

After reinstall the CUDA 9.1, it works well.

Thank you again.
