### ISSUE TITLE
how to set output value but not output possibility

### ISSUE THREAD

**Issue by Rangocold** [apache/incubator-mxnet#10903]
i build cpp-package and run example success.in the example, i find that output is the possibility about every label,but my num of label is too much so i want the network output a value . such as i want to use the network to simulate a function like y = x1 + x2 + x3, the input is an array[x1, x2, x3],and output is a y predicted by network,how should i do ?

**Comment by vdantu** [comment]
@Rangocold : Could you post this on discuss.mxnet.io. You will get a broader audience.

**Comment by sandeep-krishnamurthy** [comment]
Please ask usage related questions at https://discuss.mxnet.io/ for more people being able to answer, search and refer in future. We want to keep GitHub for issues/bugs.
