### ISSUE TITLE
`mxnet.nd.smooth_l1(mxnet.nd.array([1, 2, 3]))' core dumped

### ISSUE THREAD

**Issue by devymex** [apache/incubator-mxnet#10916]
## Description
mxnet.nd.smooth_l1(mxnet.nd.array([1, 2, 3]))
core dumped

## Environment info (Required)
ubuntu 16.04

Package used (Python/R/Scala/Julia):
I'm using Python
Compiler gcc:

MXNet commit hash:
e29b2f5bcac0f1cefaad9232879e7165fa51f67d

Build config:
make -j16 USE_BLAS=atlas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_OPENCV=1 DEBUG=0 USE_OPENMP=1 USE_CPP_PACKAGE=1 CUDA_ARCH="-gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61"

## Error Message:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
Aborted (core dumped)

## Minimum reproducible example
just run python and:
```
import mxnet
mxnet.nd.smooth_l1(mxnet.nd.array([1, 2, 3]))
```

**Comment by chinakook** [comment]
mxnet.nd.smooth_l1(mxnet.nd.array([1, 2, 3]), sigma=2.0)

**Comment by wkcn** [comment]
@chinakook 
Hi, I run the code but it fails.

```python
>>> mxnet.nd.smooth_l1(mxnet.nd.array([1, 2, 3]), sigma=2.0)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
[1]    1591 abort (core dumped)  python
```
Arch Linux + python2/python3 + gcc 8.1.0
MXNet (build from 0fcf1917, make -j 5 USE_OPENCV=1 USE_BLAS=openblas)
