### ISSUE TITLE
problem installing mxnet in R 3.5

### ISSUE THREAD

**Issue by werewere** [apache/incubator-mxnet#10925]
## Description
R is not able to find the repository data to install mxnet in R 3.5. Installation fails.

## Environment info (Required)
PS C:\Users\Administrator\Downloads> python .\diagnose.py
----------Python Info----------
Version      : 3.6.5
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('v3.6.5:f59c0932b4', 'Mar 28 2018 17:00:18')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.3
Directory    : C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Windows-2012ServerR2-6.3.9600-SP0
system       : Windows
node         : WIN-D7J2ETF33B3
release      : 2012ServerR2
version      : 6.3.9600
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
Name
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0000 sec, LOAD: 3.1931 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.8261 sec, LOAD: 3.4812 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 1.3826 sec, LOAD: 3.0218 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-la
bels-idx1-ubyte.gz, DNS: 0.0000 sec, LOAD: 3.2441 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.8144 sec, LOAD: 10.7466 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 1.1913 sec, LOAD: 2.8590 sec.
PS C:\Users\Administrator\Downloads>

---------------
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0   
------------
## Error Message:

> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
Warning: unable to access index for repository https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/windows/contrib/3.5:
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/windows/contrib/3.5/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mxnet’
  These will not be installed

**Comment by harryprince** [comment]
@werewere 
maybe you need to install from source, R 3.5 have changed the kernel and performance improved.

**Comment by jeremiedb** [comment]
@werewere The official repo is keeping a version that is dating a little bit. 
You can try installling this pre-compiled version for Windows, mxnet 1.2.0 compiled with R 3.5.0 in the meantime: 
`install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)`

**Comment by vdantu** [comment]
@sandeep-krishnamurthy : Could you tag this question with "R", "Installation", "Question"

**Comment by werewere** [comment]
thanks @jeremiedb , it seems to install correctly that pre-compiled one.

**Comment by ankkhedia** [comment]
@werewere Also the binaries on the official repo got updated. So, the install instruction from official MXNet page should work fine! Could you please confirm that the issue got fixed and close it?
