### ISSUE TITLE
about the data translating tool im2rec, is there any option to add new images to the existing rec file?

### ISSUE THREAD

**Issue by GoodJoey** [apache/incubator-mxnet#10932]
Hi,
I have about 50G images for training, and it takes me about 2 hours to translate the images to rec file.
And I will receive thousands of new images period by period, then include them in the new training.
So i need to re-generate the rec file. Is there any way i can just add the new images to the existing rec file instead of re-create the rec file from the very beginning? That will save a lot of time.
Thanks a lot.

**Comment by vdantu** [comment]
@GoodJoey : Could you also post this on discuss.mxnet.io? You will get a wider audience there. 

@sandeep-krishnamurthy : Could you tag this "question"

**Comment by sandeep-krishnamurthy** [comment]
Closing the issue. Please ask usability questions at discuss.mxnet.io for faster response
