### ISSUE TITLE
gluon documentation bug

### ISSUE THREAD

**Issue by feevos** [apache/incubator-mxnet#10930]
Dear all, 

in the gluon documentation of the [neural network layers](https://mxnet.incubator.apache.org/api/python/gluon/nn.html) ```(Versions(master))```, the ```mxnet.gluon.nn..HybridLambda(function, prefix=None)``` appears only in the [analytic description](https://mxnet.incubator.apache.org/api/python/gluon/nn.html#mxnet.gluon.nn.HybridLambda) of the page, but is not listed in any of the tables in the beginning. I think this is missing. 

Thank you for all your great work.

**Comment by szha** [comment]
Indeed. Sorry that I missed it. Would you mind adding it to the list at the top?

**Comment by feevos** [comment]
Hi @szha, not at all but I don't know how to do so.

**Comment by szha** [comment]
@feevos thanks! You can add the missing entries in this file https://github.com/apache/incubator-mxnet/blob/master/docs/api/python/gluon/nn.md

**Comment by feevos** [comment]
Thanks @szha I am closing this and I hope I haven't created more trouble than help with my ignorance in contributing (getting there ... :) ).
