### ISSUE TITLE
The negative samples shall be other classes?

### ISSUE THREAD

**Issue by jonbakerfish** [apache/incubator-mxnet#10950]
https://github.com/apache/incubator-mxnet/blob/0fb57ff31ef5caa32edf973213bde8a8faba85e5/example/gluon/embedding_learning/model.py#L128

I think we should uniformly sample indices from other classes:

    n_indices += np.random.choice(n, k-1, p=mask[i]* (1.0/(n-k))).tolist()

**Comment by eric-haibin-lin** [comment]
@chaoyuaw

**Comment by chaoyuaw** [comment]
@jonbakerfish Yes, I think you are right. Would you mind creating a PR for this?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please tag this as Call for Contribution

**Comment by jonbakerfish** [comment]
Hi @chaoyuaw , a PR is created https://github.com/apache/incubator-mxnet/pull/10980. Please have a look. Thanks.
