### ISSUE TITLE
The params can't be saved as expected when using --model-prefix for all the training script belonging to example/image-classification

### ISSUE THREAD

**Issue by juliusshufan** [apache/incubator-mxnet#10952]
## Description
When executing the script at example\image-classification with option --model-prefix, a python run time error will happen and params can't be saved either.

## Environment info (Required)
CentOS 7.2 

```
What to do:
Taking the train_mnist.py as an example, simply run:
python train_mnist.py --model-prefix='mnist'
```

Package used (Python/R/Scala/Julia):
I'm using Python

## Build info (Required if built from source)
gcc 4.8.5

MXNet commit hash:
0fb57ff31ef5caa32edf973213bde8a8faba85e5

Build config:
make -j($nproc) USE_BLAS=openblas USE_OPENCV=1 

## Error Message:
Traceback (most recent call last):
  File "train_mnist.py", line 96, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/ec/fm/disks/nrv_algo_home01/shufanwu/workspace/mxnet/v2/example/image-classification/common/fit.py", line 183, in fit
    checkpoint = _save_model(args, kv.rank)
  File "/ec/fm/disks/nrv_algo_home01/shufanwu/workspace/mxnet/v2/example/image-classification/common/fit.py", line 72, in _save_model
    os.mkdir(dst_dir)
FileNotFoundError: [Errno 2] No such file or directory: ''

## Steps to reproduce
Taking the train_mnist.py as an example, simply run:
python train_mnist.py --model-prefix='mnist'

## What have you tried to solve it?
See PR https://github.com/apache/incubator-mxnet/pull/10922

**Comment by LuckyPigeon** [comment]
This error seems like solved already if your PR #10922 had been merge.

**Comment by juliusshufan** [comment]
@LuckyPigeon Yes, this PR https://github.com/apache/incubator-mxnet/pull/10922 is actually to solve the issue. Thanks for confirmation.

**Comment by juliusshufan** [comment]
@szha Could you please review PR#10922, and merge it if qualified? Thanks~

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please tag this as python and bug

**Comment by juliusshufan** [comment]
fixed
