### ISSUE TITLE
Mxnet dynamic graphs achieve scoure code 

### ISSUE THREAD

**Issue by qichaotang** [apache/incubator-mxnet#10969]
Hi, all hackers
   I want to read Mxnet dynamic graphs source code , I know, gluon is front end, I want to know how to achieve this in C++ Back-end, especially, I want to know the commit by converting static graphs to dynamic graphs. I try to find release 0.11.0 ,but commit is too large to know the essential commits. So I need your help. Point out  the essential commits which achieve static graphs to dynamic graphs.
  Please ignore my bad english!

**Comment by eric-haibin-lin** [comment]
You can read the code in src/imperative folder, in particular related to cached op for Gluon backend execution

**Comment by ankkhedia** [comment]
Hi @qichaotang 
Could you please confirm if they query got answered and close the issue.
@sandeep-krishnamurthy 
Please tag this as question and pending requester info

**Comment by qichaotang** [comment]
Thanks,
