### ISSUE TITLE
How to show the ctc loss?

### ISSUE THREAD

**Issue by maybepossible** [apache/incubator-mxnet#10965]
I want to view the loss of the warp-ctc each epoch to prevent overfit. Is there a way to show the ctc loss just like 'accuracy' or 'F1'?

**Comment by maybepossible** [comment]
I want to view the loss of the warp-ctc each epoch to prevent overfit. Is there a way to show the ctc loss just like 'accuracy' or 'F1'?

**Comment by ankkhedia** [comment]
@maybepossible , Could you please post your question on discuss.mxnet.io ? We handle questions through that forum.

@sandeep-krishnamurthy Could you please tag the issue as question and close the issue.

@maybepossible Please feel free to reopen in case it is closed in error.

**Comment by sandeep-krishnamurthy** [comment]
Please ask usage related questions at https://discuss.mxnet.io/ for more people being able to answer, search and refer in future. We want to keep GitHub for issues/bugs.
