### ISSUE TITLE
linalg_potri() Error: linalg_impl.h:606: Check failed: ret == 0 (3 vs. 0) spotri failed in lapack on cpu.

### ISSUE THREAD

**Issue by sxksxy** [apache/incubator-mxnet#10964]
## Description
I try to use linalg_potri() to get the inverse, the input of linalg_potri is a 2-dimesional ndarray.  Got
linalg_impl.h:606: Check failed: ret == 0 (3 vs. 0) spotri failed in lapack on cpu.

## Environment info (Required)
----------Python Info----------
Version      : 3.6.4
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('default', 'Jan 16 2018 10:22:32')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 10.0.1
Directory    : C:\ProgramData\Anaconda3\lib\site-packages\pip
----------MXNet Info-----------
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\ProgramData\Anaconda3\lib\site-packages\h5py\tests\old\test_attrs_data.py:251: DeprecationWarning: invalid escape sequence \H
  s = b"Hello\x00\Hello"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\func_inspect.py:53: DeprecationWarning: invalid escape sequence \<
  '\<doctest (.*\.rst)\[(.*)\]\>', source_file).groups()
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\_memory_helpers.py:10: DeprecationWarning: invalid escape sequence \s
  cookie_re = re.compile("coding[:=]\s*([-\w.]+)")
Version      : 1.2.0
Directory    : C:\ProgramData\Anaconda3\lib\site-packages\mxnet
Commit Hash   : 007c0c54c3476bd40975f694f05d96a89eaa0397
----------System Info----------
Platform     : Windows-10-10.0.17134-SP0
system       : Windows
node         : XKSUN
release      : 10
version      : 10.0.17134
----------Hardware Info----------
machine      : AMD64
processor    : AMD64 Family 21 Model 16 Stepping 1, AuthenticAMD
Name                                          

AMD A8-4500M APU with Radeon(tm) HD Graphics  

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0000 sec, LOAD: 2.6023 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.2344 sec, LOAD: 0.4844 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1406 sec, LOAD: 2.4745 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1250 sec, LOAD: 2.3438 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.1094 sec, LOAD: 9.1874 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0000 sec, LOAD: 0.6876 sec.

Package used (Python/R/Scala/Julia):
I'm using Python 3.6.4

## Error Message:
Traceback (most recent call last):
  File "C:\Users\xksun\Documents\MxNet\DMVCS\dmvcs_net.py", line 113, in <module>
    train(train_data, valid_data, net, trainer, num_epochs, batch_size)
  File "C:\Users\xksun\Documents\MxNet\DMVCS\dmvcs_net.py", line 93, in train
    tr_ls = loss.asscalar() / batch_size
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\ndarray\ndarray.py", line 1894, in asscalar
    return self.asnumpy()[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\ndarray\ndarray.py", line 1876, in asnumpy
    ctypes.c_size_t(data.size)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:32:11] c:\projects\mxnet-distro-win\mxnet-build\src\operator\linalg_impl.h:606: Check failed: ret == 0 (3 vs. 0) spotri failed in lapack on cpu.

## Minimum reproducible example
Short example is here:  https://github.com/sxksxy/DMVCS
Use `python ./dmvcs_net.py` to run the example.
Data is only 352 image and text.

## Steps to reproduce
`python ./dmvcs_net.py`

## What have you tried to solve it?
In ./mvcs.py line 39, I want to use linalg_potri() to get the inverse, the input of linalg_potri is a 2-dimesional ndarray.
And in ./dmvcs_net.py, I concate the text and image features, then call the mvcs_loss() in ./mvcs.py to get loss, but when I use loss.asscalar() or print(loss), got error!!

I have tried to replace the input of custom loss function ./mvcs.mvcs_loss() with same type and shape random ndarray, it works, but still error in example.

**Comment by piiswrong** [comment]
@asmushetzel

**Comment by asmushetzel** [comment]
potri computes the inverse based on the Cholesky decomposition (see documentation of potri). So the input must be a positive definite matrix say "A".  L = potrf(A) then does the Cholesky decomposition where A = L*L^T.  potri(L) will compute the inverse of A. 
You have to ensure that the initial matrix A is indeed positive definite when feeding it into potrf().

**Comment by ankkhedia** [comment]
@sxksxy Hope your issue got resolved.
@sandeep-krishnamurthy Could you please close the issue and label it as operator

@sxksxy Please feel free to re open the issue in case it is closed in error
