### ISSUE TITLE
Is the doc for launch.py parameters outdated？

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#10967]
https://mxnet.incubator.apache.org/versions/master/faq/distributed_training.html#modeling
##
There are no instractions for option --cluster and option --launcher is deprecated?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please tag this as Question and Documentation

**Comment by rahul003** [comment]
Looks like --launcher is mapped to --cluster to keep it consistent with a dependency (dmlc-core). 
You will need to use --launcher

**Comment by sandeep-krishnamurthy** [comment]
@rahul003 - Do we need to update the doc to reflect that --launcher is mapped to --cluster

**Comment by rahul003** [comment]
@sandeep-krishnamurthy  --launcher is not deprecated.  --cluster is a mapping in dmlc-core, which is not exposed to mxnet users. The doc is up to date. I think you can close this.
