### ISSUE TITLE
CI not early stopping builds anymore

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#10962]
@marcoabreu it seems that the CI is not stopping builds of commits that have subsequent commits in a given PR? Though I think it was doing it before. Is it a change that was done on purpose?

**Comment by marcoabreu** [comment]
Hi, this was never enabled. We always built all commits

**Comment by ThomasDelteil** [comment]
Ah, don't know how I came to be sure of that then. Well I'm thinking that might be a good idea to do it in the future :)
