### ISSUE TITLE
report a bug(?) for CSV iterator

### ISSUE THREAD

**Issue by mazeLinx** [apache/incubator-mxnet#1097]
hi, 

I use csv iterator to train a sample model. I find that some specific batch sizes will cause training crash. 

It crashes when the batch size is 100, 256, 512, 1024, 2048, while it works for 3072.

error logs:
 what():  [12:43:14] src/io/iter_csv.cc:86: Check failed: label_parser_->Next() Data CSV's row is smaller than the number of rows in label_csv

The data format and similar issue is also reported here, https://github.com/dmlc/mxnet/issues/1088 

Here is a screenshot of this issue.![bug](https://cloud.githubusercontent.com/assets/4373620/12029361/fd072ee6-ae23-11e5-8460-6a9d9d70611a.png)

**Comment by piiswrong** [comment]
@antinucleon This looks like a bug in CSV iter.

**Comment by antinucleon** [comment]
will check it tmr. Also loop @tqchen

**Comment by yaguanghu** [comment]
is this bug solved? I seems encountered the same problem.

**Comment by paipai880429** [comment]
Same again~

**Comment by kris-cognitiv** [comment]
same error. doesn't even throw an exception, just aborts.

**Comment by horsepurve** [comment]
Same problem on gpu, but it's fine on cpu, weird.

**Comment by ericyue** [comment]
i have the same problem on gpu

**Comment by Pfeeder** [comment]
same as problem ,but sometimes it may not occur when using some specific batch size or epoch times

**Comment by moveforever** [comment]
i run csviter on cpu, and i come across the same problem. sometime, it can run, sometime it fail to run.

**Comment by sandeep-krishnamurthy** [comment]
I couldn't reproduce this issue. Maybe transient? @antinucleon @piiswrong - Is this issue fixed?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
