### ISSUE TITLE
Question: problem with import model generated by Wolfram Mathematica?

### ISSUE THREAD

**Issue by HyperGroups** [apache/incubator-mxnet#10998]
When I'm using load_checkpoint()
I found the code in model.py is
  ```
symbol = sym.load('%s-symbol.json' % prefix)
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
    arg_params = {}
    aux_params = {}
    for k, v in save_dict.items():
     tp,name = k.split(':', 1)
            if tp == 'arg':
                arg_params[name] = v
            if tp == 'aux':
                aux_params[name] = v
```

the problem is in my arguments, there is no {{{___colon : ____]}}

so the error info is
```
[02:17:25] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v1.0.1. Attempting to upgrade...
[02:17:25] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Traceback (most recent call last):
  File "/home/hypergroups/nutstore/ProjectsOnline/My/Python/MXNet/1.0/script/test_rgb.py", line 25, in <module>
    sym,arg_params, aux_params = mx.model.load_checkpoint(model_prefix,0)
  File "/home/hypergroups/anaconda2/lib/python2.7/site-packages/mxnet/model.py", line 425, in load_checkpoint
    tp, name = k.split(':', 1)
ValueError: need more than 1 value to unpack
```

mxnet.__version__ is 1.1.0

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please tag this as Question

**Comment by HyperGroups** [comment]
@ankkhedia only a contributor can add labels?

**Comment by HyperGroups** [comment]
One solution is add ':' test in the code, but may not be able to solve all questions.
ie,
Modifid code:

  ```
symbol = sym.load('%s-symbol.json' % prefix)
save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
 arg_params = {}
 aux_params = {}
 for k, v in save_dict.items():
     if ':' in k: 
        tp,name = k.split(':', 1)
              if tp == 'arg':
                  arg_params[name] = v
              if tp == 'aux':
                  aux_params[name] = v
        else:
            arg_params[k]=v
```

**Comment by sandeep-krishnamurthy** [comment]
@HyperGroups : Can you please ask the question at https://discuss.mxnet.io/ ? More people will be able to answer and later search for the similar question. We want to keep GitHub issues mainly for bugs and feature requests. Please reopen if you face any issues.

**Comment by ThomasDelteil** [comment]
@HyperGroups can you please show or point me to how you export it from Mathematica?
The reason why you have this error is because only models saved using the module API or the `.export` function of `HybridBlock` in Gluon can be loaded using the `load_checkpoint` function.

As of 1.2.1, you can load your model in Gluon using the `HybridBlock.imports` function:
```python
import mxnet as mx
from mxnet import gluon

net = gluon.nn.SymbolBlock.imports('example-symbol.json',
                                   ['Input'], 
                                   param_file='example-0000.params',
                                   ctx=mx.cpu())
```

**Comment by ThomasDelteil** [comment]
@sandeep-krishnamurthy can you please close the issue?
@HyperGroups let's continue the discussion there: https://discuss.mxnet.io/t/simple-bind-error-when-loading-model/1110/3
