### ISSUE TITLE
How to train the model by c++

### ISSUE THREAD

**Issue by wushilian** [apache/incubator-mxnet#10993]
If I want to use c++ not python to train the model,How should I do?

**Comment by chinakook** [comment]
It's low productive to train model with c++.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy  Could you please tag this as Question and C++

**Comment by sandeep-krishnamurthy** [comment]
Hello @wushilian - You can ask usability questions at https://discuss.mxnet.io/ . It has more users who can answer questions related to using MXNet. GitHub issues are more useful to report bugs.
Please reopen in case of any issues.
