### ISSUE TITLE
The example of train_mnist.py can't exit after completes.

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11029]
Run ../example/image-classification/train_mnist.py --network lenet --kv-store dist_sync, but the process can't exit after task completes.

**Comment by kalyc** [comment]
@liuzx32 thanks for submitting this issue
It looks like @rahul003 opened a PR for this and it has been merged. 
Is your issue resolved? If so, could you close this?

**Comment by vishaalkapoor** [comment]
@eric-haibin-lin can we close this off? Thanks!
