### ISSUE TITLE
mxnet on yarn throw the OSError, how can I solve it.

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11020]
File "/usr/lib64/python2.7/ctypes/__init__.py", line 357, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenblas.so.0: cannot open shared object file: No such file or directory
##
The problem show
s that there is no openblas on ec2，does it means that I need to install openblas for every ec2 on yarn?  Is there any other solutions to solve it.

**Comment by rahul003** [comment]
Did you build from source? I believe you have to install it on each machine.

**Comment by liuzx32** [comment]
@rahul003 Thank you for the answer, Perhaps I can build from source with the static link library openblas.a.
