### ISSUE TITLE
No Windows Support for Scala

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#11023]
## Description
Currently I see the tutorial contains Scala installation page for Scala, please remove that or adding some signs to show we are not currently support Windows.
@aaronmarkham 

## Environment info (Required)
Windows

Package used (Python/R/Scala/Julia):
(I'm using Scala)

**Comment by lanking520** [comment]
Any updates?

**Comment by lupesko** [comment]
@sandeep-krishnamurthy can you please label Scala and Windows? Thanks!
