### ISSUE TITLE
run mxnet on spark throws error: libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11046]
18/05/24 15:16:32 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, ip-172-31-30-210.ec2.internal, executor 2): java.lang.UnsatisfiedLinkError: /mnt/yarn/usercache/mobdev/appcache/application_1498108406715_370596/container_1498108406715_370596_01_000003/tmp/mxnet4326624135048797573/mxnet-scala: libopenblas.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)

**Comment by sandeep-krishnamurthy** [comment]
Hello you need to install Openblas. Please refer installation guide here - http://mxnet.incubator.apache.org/install/index.html

Please provide more details on the system, how did you install mxnet and how did you invoke.

**Comment by liuzx32** [comment]
@sandeep-krishnamurthy Thank you for the answer, I have installed openblas in one machine which runs the script for mxnet on spark. If I run it on yarn, you mean I need to install openblas on every machine, that doesn't seem feasible!  How do you solve the distributed running problems? Perhaps my question is here.

**Comment by liuzx32** [comment]
@sandeep-krishnamurthy Perhaps mxnet can complie with static link library openbblas.a not dynamic link library openblas.so. I hope it will help mxnet on spark or on yarn.
