### ISSUE TITLE
[Feature Request] broadcast_like operator

### ISSUE THREAD

**Issue by zhanghang1989** [apache/incubator-mxnet#11056]
## Description

Request a `broadcast_like` operator, which can output a broadcasted NDArray for the given target. 

For example `y=nd.broadcast_like(x, z)`, which should return the same result with existing operator `y=nd.broadcast_to(x, z.shape)` but avoid reading the shape explicitly, so that it can be used in `HybridBlock`.

**Comment by lanking520** [comment]
I have created a JIRA ticket for this: https://issues.apache.org/jira/browse/MXNET-524.

**Comment by ifeherva** [comment]
Happy to do this next.

**Comment by ifeherva** [comment]
See https://github.com/apache/incubator-mxnet/pull/11820

**Comment by eric-haibin-lin** [comment]
Added in #11820
