### ISSUE TITLE
How to get the shape of input variable for both nd and sym in hybrid_forward dynamically?

### ISSUE THREAD

**Issue by daleydeng** [apache/incubator-mxnet#11050]
When training with different size of images(with batch_size=1), how to get input variable shape using F in HybridBlock.hybrid_forward, that means a single function in both nd and sym api?

For example, using F.contrib.BilinearResize2D for scalling without out_height and out_width.

**Comment by sandeep-krishnamurthy** [comment]
Please ask usage related questions at https://discuss.mxnet.io/ for more people being able to answer, search and refer in future. We want to keep GitHub for issues/bugs. Please reopen if you face any issues.
