### ISSUE TITLE
Failed dist_sync_kvstore test not detected on CI for a long time

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11057]
e.g. http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11001/9/pipeline/1442
The test fails but CI didn't detect that @rahul003 

It seems to fail after https://github.com/apache/incubator-mxnet/pull/10645 @haojin2

**Comment by haojin2** [comment]
@eric-haibin-lin is this good to be closed now? Seems like the test is fixed now.
