### ISSUE TITLE
wget https://s3-us-west-2.amazonaws.com/mxnet.liuyz/data/mnist/train.txt throw 404

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11060]
The script in scala-package/spark for mxnet on spark. wget https://s3-us-west-2.amazonaws.com/mxnet.liuyz/data/mnist/train.txt throw 404, how can I get the train.txt and val.txt data?

**Comment by kalyc** [comment]
@liuzx32 thanks for submitting this issue. It appears that you were able to obtain the training data. Could you please close the issue? 

The S3 bucket you have mentioned does not exist. You can obtain MNIST training data here as well- http://yann.lecun.com/exdb/mnist/

**Comment by lanking520** [comment]
@nswamy @liuzx32 I have updated the link, I think this issue can be closed now.
