### ISSUE TITLE
how to manually occupy all gpu memory like tensorflow?

### ISSUE THREAD

**Issue by kaleidoscopical** [apache/incubator-mxnet#11062]
MxNet is excellent on memory saving. But is there a way to manually occupy all gpu memory like tensorflow?

**Comment by sandeep-krishnamurthy** [comment]
I think MXNet allocates the required memory, there is no option to forcefully occupy full memory.
Can you please let me know, why would this be required?

**Comment by kaleidoscopical** [comment]
Thanks for replying me : )

For example, I have a GPU card with 12GB memory and one of my running programs occupies 11.5GB of it. Besides, there are several dynamic memory allocations in my codes. 

If I accidentally run another program on the same GPU card, both of the programs will report "Out of Memory". So, I wonder whether there is a safer way to solve this problem.

**Comment by ThomasDelteil** [comment]
not that I am aware, you can specify which GPU to use by using `mx.gpu(i)` where `i` is your device index.

**Comment by ThomasDelteil** [comment]
@kaleidoscopical I think there is no way to forcefully occupy full memory.
@indhub can you close the issue or remove the [Question][Pending Requester Info] tags and add a [Feature Request] tag?

**Comment by indhub** [comment]
Agree, there is no way to forcefully occupy memory.
