### ISSUE TITLE
mx.nd.argmax is slow

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#11061]
```
import time
import mxnet as mx
import numpy as np
import os
tmp = mx.nd.random.uniform(-1, 1, shape=(64,300000), ctx=mx.gpu())
#tmp = np.random.RandomState().uniform(-1, 1, (64,300000))
tic = time.time()
for i in range(20):
   if (i == 5):
        begin = time.time();
   elif (i == 15):
        end = time.time();
   tic = time.time()
   max = mx.nd.argmax(tmp, axis=1)
   #max = np.argmax(tmp, axis=1)
   print max[0]
   toc = time.time() - tic
   print ("used time %f:"%toc)
avg = (end - begin) / 10
print ("avg time %f"%avg)

```
We use code before to test the speed of argmax.
NDArray in cpu use 0.112895s.
NDArray in gpu use 0.280577.
numpy.array only use 0.018021.

Why mx.nd.argmax is so slow?

@szha

**Comment by z01nl1o02** [comment]
remove the line  "print max[0]" mx.nd will be faster.

**Comment by solin319** [comment]
@z01nl1o02 
"print max[0]" is used to make sure argmax completed. 
We can change it to 'max.wait_to_read()', the result is same.

**Comment by puppet101** [comment]
In my experiment, the function nd.topk is much faster than nd.argmax, but I just want to know why the nd.argmax is so slow?

**Comment by ThomasDelteil** [comment]
Same issue, nd.argmax() is really slow, close to unusable in real world scenarios

**Comment by szha** [comment]
It's a bit embarrassing...IIRC, our argmax is done through a sequential reduce with no parallelism...
@solin319 how much faster is topk?

**Comment by ThomasDelteil** [comment]
@szha for my use-case topk is approx 100x faster.
the GPU version is also 10 times slower than the CPU one.

```
data = mx.nd.random.uniform(shape=(1,384*384), ctx=mx.gpu())
```
```
%%time
for i in range(10):
    nd.argmax(data,axis=1).wait_to_read()
CPU times: user 192 ms, sys: 112 ms, total: 304 ms
Wall time: 301 ms
```
```
%%time
for i in range(100):
    nd.topk(data, ret_typ='indices', axis=1).wait_to_read()
CPU times: user 28 ms, sys: 8 ms, total: 36 ms
Wall time: 31.9 ms
```

**Comment by fhieber** [comment]
We'd be interested in having this change as well. Sockeye is also has code with `argmin` but intentionally does not use it: https://github.com/awslabs/sockeye/blob/master/sockeye/inference.py#L2213

**Comment by ThomasDelteil** [comment]
@szha I don't think I have the time these coming weeks unfortunately working against some tight deadlines

**Comment by ifeherva** [comment]
Is argmax affected as well?

**Comment by eric-haibin-lin** [comment]
I am interested in this, too. This is taking a noticeable portion of time when training BERT. In my case, each invocation takes ~8ms, while other operators take ~0.1ms.

**Comment by eric-haibin-lin** [comment]
Also both CPU and GPU argmax becomes slow when the number of category is large (e.g. vocab size = 30K).

**Comment by sxjscience** [comment]
Even in the latest MXNet 2.0, this performance issue was not solved:

- Speed of topk(k=1)

```python
import time
import mxnet as mx
import numpy as np
import os
tmp = mx.np.random.normal(-1, 1, (64,300000), ctx=mx.gpu())
tic = time.time()
for i in range(20):
   if (i == 5):
        begin = time.time();
   elif (i == 15):
        end = time.time();
   tic = time.time()
   out = mx.npx.topk(tmp, k=1, ret_typ='indices', axis=1, dtype=np.int32)
   out.wait_to_read()
   toc = time.time() - tic
   print ("used time %f:"%toc)
avg = (end - begin) / 10
print("avg time %f"%avg)
```


Output:
```
used time 0.001522:
used time 0.001141:
used time 0.001141:
used time 0.001094:
used time 0.001081:
used time 0.001080:
used time 0.001086:
used time 0.001089:
used time 0.001075:
used time 0.001085:
used time 0.00108
```

- Speed of argmax:
```python
import time
import mxnet as mx
import numpy as np
import os
tmp = mx.np.random.normal(-1, 1, (64,300000), ctx=mx.gpu())
tic = time.time()
for i in range(20):
   if (i == 5):
        begin = time.time();
   elif (i == 15):
        end = time.time();
   tic = time.time()
   out = mx.np.argmax(tmp, axis=1)
   out.wait_to_read()
   toc = time.time() - tic
   print ("used time %f:"%toc)
avg = (end - begin) / 10
print("avg time %f"%avg)
```

Output
```
used time 0.063610:
used time 0.060543:
used time 0.059911:
used time 0.059865:
used time 0.055048:
used time 0.054780:
used time 0.054773:
used time 0.054817:
used time 0.054653:
used time 0.054758:
used time 0.054723:
used time 0.054765:
used time 0.054680:
used time 0.054769:
```

**Comment by sxjscience** [comment]
Actually, the latest profiling number shows that the argmax in MXNet is 362 times slower than that in PyTorch...

**Comment by sxjscience** [comment]
I think we should try to remove the usage of https://github.com/apache/incubator-mxnet/blob/9de2a48fabf1b8a60eb539640dea4c0637b5522b/src/operator/numpy/np_broadcast_reduce_op.h#L472, and reuse the 
`ReduceAxesComputeImpl` https://github.com/apache/incubator-mxnet/blob/9268f89080d84d37aadb295f918515fd6d43436e/src/operator/tensor/broadcast_reduce_op.h#L621-L650

**Comment by sandeep-krishnamurthy** [comment]
@Zha0q1 - Can you please keep this in your TODO list. looks like interesting and important optimization.
FYI @mseth10 @josephevans

**Comment by sxjscience** [comment]
@Zha0q1 Ping me any time if you are blocked.

**Comment by Zha0q1** [comment]
Yeah looks like an important fix. Will find to do it
