### ISSUE TITLE
The sampling_ratio in roi-align can be specified(not adaptive size)!

### ISSUE THREAD

**Issue by iFighting** [apache/incubator-mxnet#11077]
The sampling_ratio in roi-align can be specified(not adaptive size)!

the sampling_ratio in detectron is 2，if we use adaptive size sampling_ratio, the output feature map diff in mxnet and detectron is large with the same input!

**Comment by ZiyueHuang** [comment]
cc @zhanghang1989

**Comment by anirudhacharya** [comment]
RoiAlign was added in this PR - https://github.com/apache/incubator-mxnet/pull/10852 by @zhanghang1989 . can you take a look.

@sandeep-krishnamurthy please add label - "Operator", "Bug"

**Comment by zhanghang1989** [comment]
I am following up this issue, will fix it soon.
