### ISSUE TITLE
how to pass int as parameter to HybridBlock

### ISSUE THREAD

**Issue by glingyan** [apache/incubator-mxnet#11078]
class hb1(gluon.HybridBlock):
  def hybrid_forward(self, F, x, dims)
      #get dims's value
      out_dim = dims[0] #error raise TypeError('Symbol only support integer index to fetch i-th output')
class hb2(gluon.HybridBlock):
  def __init__():
      self.hb_nn = hb1()
  def hybrid_forward(self, F, x)
      out_dim = 5
      out_dim_ndarray = mx.nd.array([out_dim])
      self.hb_nn(x, out_dim_ndarray)

is there a api to pass int value to HybridBlock as a parameter

**Comment by glingyan** [comment]
@piiswrong

**Comment by szha** [comment]
just keep integer as a member of the class instance.
