### ISSUE TITLE
Is it normal that mxnet takes up much more GPU memory at the start up?

### ISSUE THREAD

**Issue by maybepossible** [apache/incubator-mxnet#11080]
In my program, I found the mxnet will take 900M GPU memory at the beginning when the program starts. And then reduce to 300M. Is that normal?

**Comment by ThomasDelteil** [comment]
answered here, please close the issue and let's continue the discussion on the forum 
https://discuss.mxnet.io/t/is-it-normal-that-mxnet-takes-up-much-more-gpu-memory-at-the-start-up/1134/2
