### ISSUE TITLE
Seems the gperftools-devel and jemalloc-devel wouldn't be detected correctly on rhel(Redhat Enterprise Linux)

### ISSUE THREAD

**Issue by myme5261314** [apache/incubator-mxnet#11108]
https://github.com/apache/incubator-mxnet/blob/2dbd143e4892bb9ad4aa1835c79f0046603e3531/Makefile#L221

Refer to the mxnet Makefile above, the search paths for gperftools-devel and jemalloc-devel are under `/lib`/`/usr/lib`/`/usr/local/lib`.
But gperftools-devel and jemalloc-devel package installed via yum will place the dynamic library files into **`/usr/lib64`**

TL,DR;
As the title said.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please label - "Build",

**Comment by vandanavk** [comment]
@myme5261314 Is this issue still seen on your setup?

**Comment by sandeep-krishnamurthy** [comment]
Closing as the issue is resolved. Please reopen if issue still persists
