### ISSUE TITLE
Feature request: please speed up asnumpy()

### ISSUE THREAD

**Issue by feevos** [apache/incubator-mxnet#11119]
Dear all, 

I am trying to visualize some predictions from an NN run so I need to use ```asnumpy()``` to get ```imshow``` visualizations. For an ```nd.array``` of size 3000x3000  ```(ctx=mx.cpu())``` this takes forever.  In contrast the function ```nd.argmax(some_array_6X3KX3K)``` for some nd.array of shape (6,3000,3000) runs instantly. Surely the ```asnumpy()``` operation can be done much much faster. Could you please consider speeding up this function? It would be a great addition to mxnet usability since the majority of packages in python are using numpy (e.g. I need to save my output as a geotiff file, need to use rasterio which is numpy compatible, cannot use nd.array format). 

The operation that is still running on my laptop is  the simple
```Python
preds = tpreds_use.asnumpy()
```
where I expect preds to be a 3K by 3K numpy array, and tpreds_use is a 3X by 3K nd.array 

Thank you very much for the great work you put on mxnet.

**Comment by reminisce** [comment]
That doesn't sound like a problem of `asnumpy()` itself. More likely, something is wrong in the upstream. Are you saying it's never ending or it just took too much time than expected? I tried on my laptop of calling `asnumpy()` on a 3000x3000 matrix and it's lightning fast. It would be helpful if you could paste the source code here for further analysis.

**Comment by reminisce** [comment]
After looking through the script, I feel it's not the problem of `asnumpy()`. The mxnet operators are async functions in python, which means they may be still running in backend (C++) while python main thread moves to other steps. I suspect that the bottleneck is in the nested loops where ndarray slicing and slicing with assignment are triggered frequently. You can use `tpreds.wait_to_read()` to setup a barrier in the python thread to force the execution on `tpreds` to finish in backend before moving forward in frontend and time the execution.

**Comment by feevos** [comment]
Thank you @reminisce  I will try what you suggested and get back here, but I have a question. How is it possible for the ```tpreds_use = nd.argmax(tpreds,axis=0)``` to be performed and complete while the other operations are still running?

**Comment by reminisce** [comment]
Can you make sure that `nd.argmax` is complete by adding code
```python
tpreds_use.wait_to_read()
print('argmax is complete')
```
after it? It is possible that the memory allocation is done for the output while the content of the output is not ready to read.

**Comment by feevos** [comment]
Hi @reminisce, you are right. ```wait_to_read()``` takes a long time, after the nested for loops are finished. So the problem is in the nested for loops. Thank you very much, am closing the topic.
