### ISSUE TITLE
mxnet 1.2.0 GPU error

### ISSUE THREAD

**Issue by BELZHANG** [apache/incubator-mxnet#11125]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
HI ALL, I'm getting this error when try to run this code  a = mx.nd.ones((2, 3), mx.gpu())

terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:12:18] /home/travis/build/dmlc/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:182: Check failed: e == cudaSuccess CUDA: unknown error

Stack trace returned 10 entries:
[bt] (0) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x30cbe2) [0x7fb294d46be2]
[bt] (1) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x30d1b8) [0x7fb294d471b8]
[bt] (2) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x293b9c8) [0x7fb2973759c8]
[bt] (3) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x293c394) [0x7fb297376394]
[bt] (4) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x294ea9f) [0x7fb297388a9f]
[bt] (5) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x294ec6e) [0x7fb297388c6e]
[bt] (6) /home/chenxi/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x294b46b) [0x7fb29738546b]
[bt] (7) /home/chenxi/anaconda2/envs/mxnet/bin/../lib/libstdc++.so.6(+0xafc5c) [0x7fb2d9701c5c]
[bt] (8) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fb2e00bc6ba]
[bt] (9) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fb2df6e241d]

I have searched this problem online, and it looks like most of the cases were caused by wrong Cuda driver or graphic card driver, I have tried different version of cuda(9.0, 8.0(i install with mxnet-cu80)), different Nvidia driver and all of them give me the same error.
so what is the correct version of Cuda ,cudnn and Nvidia driver should I use for mxnet 1.2.0?
By the way, I have already verified the correctness of Cuda installation before doing this.

Thank you!
## Environment info (Required)
```
What to do:
1.Ubuntu 16.04
2.I'm using conda and use pip to install mxnet in the conda environment
3.cuda version 9.0 with cudnn 7
4.nvidia driver 384.130
```

Package used (Python/R/Scala/Julia):
mxnet-cu90

## What have you tried to solve it?

1.try different verison of cuda driver and graphic card driver

**Comment by szha** [comment]
Could you upgrade the nvidia driver to 396.26?

**Comment by BELZHANG** [comment]
HI, @szha 
my graphics card is a gtx 1080, so the newest driver I can find is 390.59, I tried this and it gives me the same error.
Thank you!

**Comment by BELZHANG** [comment]
OH, I uninstall my manually installed Nvidia driver (.run file) and install the driver using Linux additional drivers(396.24) and it finally works.
