### ISSUE TITLE
ssd inference bug

### ISSUE THREAD

**Issue by ElegantGod** [apache/incubator-mxnet#11121]
In SSD inference, the anchor and step-size (width, height) is changed by the original image size, which is Contrary to full convolution idea. In caffe-ssd, the anchor and step-size are fixed, which is the right disign.

**Comment by vuvko** [comment]
This issue was discussed in https://github.com/zhreshold/mxnet-ssd/issues/156
It's "parent" repository to code in examples.

**Comment by vuvko** [comment]
TL;DR; author wanted to leave as it is for backward compatibility

**Comment by ElegantGod** [comment]
Thank for you reply.

 In python vision, I can fix the input size of inference equal to the input size of training by using "self.mod.bind(data_shapes=[('data', (batch_size, 3, data_shape, data_shape))])", which can generate the result close to truth. 

But in c++ version,  I only use "simple_bind" function to generate the executor, the shape of executor.data is the shape of input image. 

OK, my English is poor, I hope you can understand it, thanks!

**Comment by vuvko** [comment]
In C++ you can provide NDArray with specific shape as part of ``args`` parameter. But you need to create this array beforehand.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy label - "Bug", "Example"

**Comment by kalyc** [comment]
Thanks for opening the issue @ElegantGod 
As discussed offline with @zhreshold the symbol implementation has been likely deprecated and the team has switched to Gluon CV implementation some time back. We have decided to keep the code as it is to retain the backward compatibility. 

@sandeep-krishnamurthy could you close this issue? @ElegantGod please feel free to re-open by commenting for further questions.

**Comment by nswamy** [comment]
@zhreshold, @kalyc can you mark the code deprecated and provide a link to the Gluon CV SSD Implementation to help users.
