### ISSUE TITLE
memory cost problem for different label width when using ssd example

### ISSUE THREAD

**Issue by lynneChan** [apache/incubator-mxnet#11137]
I am working on training face detectors using the code in example/ssd on the [WIDER](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/) dataset, and i found some strange things.
If i use the all the labels and images for training(label width = 4784), the memory cost will be about 10367MB, but if i filter images and labels which number of labels is bigger than 100(label width = 602), the memory cost will be about 6991MB. 

Does anyone knows why mxnet works this way ? Should this be normal or some unknow issues ?

I run my code on Ubuntu 14.04 with GPU Tesla K40c(11439MB), data_shape = 640, network = mobilenet, batch_size = 12.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please label - "Memory", "Example", "Question"

**Comment by thomelane** [comment]
Hi @lynneChan, thanks for the question. Could you clarify which part of this is strange though?

**Comment by thomelane** [comment]
Your `batch_size` is set to 12, so even if the total number of images in your dataset is smaller you're still inputting the same amount of data into the network in both cases.

Saving in memory comes from having a smaller number of classes, but I wouldn't necessarily say this should be linear (i.e. memory footprint falling by the same amount as the labels). Most of the model parameters and activations will be from the feature maps at the start of the convolutional network, which is independent of the number of classes. You would only get a memory saving later on in the network.

**Comment by lynneChan** [comment]
Hi @thomelane, thanks for your replay.

 I was using the SSD example code to training a face detector, the WIDER dataset have about 12880 images, so the `batch_size` is fine. And the number of  classes is 2(face or non-face). The code used `DetRecordIter` in `dataset/iterator.py` to get image batches which called another API `mx.io.ImageDetRecordIter`. This API need a `label_width` parameter. 

I keeped all the settings, and just change the `label_width` from 602 to 4784, and the GPU memory cost changes from  6991MB to 10367MB. That's pretty strange, it should not increase so much.

**Comment by ThomasDelteil** [comment]
label_width should be 2 if you have 2 classes. Try setting it to -1 otherwise.

Why did you pick 4784 ? That would mean that you have 4784 different classes.

**Comment by stu1130** [comment]
@lynneChan I tried the example on the original dataset(voc) and the memory usage like this
| label-width  | GPU memeory  |
| ------------ | -------------    |
| 350               | 5900                 |
| 1000             | 6222                 |
| 2000            | 8180                  |
| 5000            | 14040                |
When you set the label-width to 4784, each label set will be padded to 4784 to make every label set have the same label size(width). So the memory usage is reasonable and inevitable.

**Comment by stu1130** [comment]
@sandeep-krishnamurthy could you please close the issue. @lynneChan if you have any question, please feel free to reopen it
