### ISSUE TITLE
Save/Load Model?

### ISSUE THREAD

**Issue by anchen1011** [apache/incubator-mxnet#11144]
Will there be an API for saving and loading models in the future? 
It was brought up in #6951 but not actually considered carefully. 

Currently we have only: 
1. Save/Load checkpoints, which is epoch-dependent
2. Save/Load params, which is not exactly save/load models, and is very unstable cross versions

Thanks!

**Comment by ThomasDelteil** [comment]
If your model is hybridizable, and you want to shelf it for a while, the recommended way would be to use `.export('prefix', epoch=0)`.
That way you can reload it later in a symbol block, or in a different language binding altogether.

If you are iterating with your model, the recommend way is `save_params/load_params` for the parameters, and save the model definition file in a `.py` file or simply pickle it.

**Comment by lanking520** [comment]
Thank you for submitting the issue! I'm labeling it so MXNet community members can help resolve it. @nswamy can you add 'Question', 'Disscussion' here?

**Comment by ThomasDelteil** [comment]
@szha @piiswrong is it safe to pickle a model to store the network definition? And later reload the params using `net.load_parameters()` ? Could we imagine having a `net.to_pickle()` in the future? What would be the gotchas to consider when doing this ?

**Comment by Ishitori** [comment]
@anchen1011 Did it work for you? If yes, please, close the issue.

**Comment by thomelane** [comment]
@szha @piiswrong any comments to the above? otherwise can we close this issue due to not hearing back from author, thanks!

@anchen1011 can be reopened if `.export` doesn't work for you, cheers.
