### ISSUE TITLE
example error: typestring mismatch

### ISSUE THREAD

**Issue by fayeshine** [apache/incubator-mxnet#1115]
python example/image-classification/train_mnist.py
[01:44:30] ./dmlc-core/include/dmlc/logging.h:208: [01:44:30] include/mxnet/operator.h:456: Check failed: (this->name) == (type) Register Name and TypeString mismatch, name="Embedding", but TypeString="BlockGrad"
terminate called after throwing an instance of 'dmlc::Error'
  what():  [01:44:30] include/mxnet/operator.h:456: Check failed: (this->name) == (type) Register Name and TypeString mismatch, name="Embedding", but TypeString="BlockGrad"

**Comment by vchuravy** [comment]
What compiler did you use? I saw this once with `icc` #413

**Comment by fayeshine** [comment]
@vchuravy ,I used icc 16. However, using gcc 5.2 also generate other bugs.

**Comment by oneengineer** [comment]
I got the same error. Instead, I am using icc15 and mkl 16.

[17:30:15] ../../dmlc-core/include/dmlc/logging.h:215: [17:30:15] include/mxnet/operator.h:494: Check failed: (this->name) == (type) Register Name and TypeString mismatch, name="_PlusScalar", but TypeString="BlockGrad"
terminate called after throwing an instance of 'dmlc::Error'
  what():  [17:30:15] include/mxnet/operator.h:494: Check failed: (this->name) == (type) Register Name and TypeString mismatch, name="_PlusScalar", but TypeString="BlockGrad"
Aborted

**Comment by sandeep-krishnamurthy** [comment]
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_mnist.py works fine. All issues are fixed. This issue can be closed - @piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
