### ISSUE TITLE
Conv1D is slow

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11161]
The Conv1D block uses MXNet's implementation for Convolution, because CUDNN only implements 2-D convolution. In the operator, we can try to optimize the performance by reshaping the inputs to 4D, and kernels to 2D, so that CUDNN kernel can be used.

**Comment by pengzhao-intel** [comment]
In our local case, it can be 10x faster :) We can provide the PR for CPU side @jinhuang415

**Comment by eric-haibin-lin** [comment]
That will be great!

**Comment by vandanavk** [comment]
@pengzhao-intel @jinhuang415 is there a PR for this issue?

**Comment by pengzhao-intel** [comment]
@vandanavk Not yet, the 1D conv is still under the development. 
We will file PR and merge it into MXNet in the next MKL-DNN release (0.17).
https://github.com/intel/mkl-dnn/commit/a1204e41d177c0117f129cfaef92dc81d030ef4e

**Comment by pengzhao-intel** [comment]
@xinyu-intel please check the latest MKL-DNN and conv1d. 
We could start the evaluate and integrate conv1d now.

**Comment by pengzhao-intel** [comment]
https://github.com/apache/incubator-mxnet/pull/13530#issuecomment-449811865

The performance is listed in this PR @eric-haibin-lin
