### ISSUE TITLE
Fix OpenCV 3.4.1 issue for Scala package for OSX

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#11193]
Currently OpenCV@2 package along with Scala package seems to be failing due to an existing opencv version. 
modify scala-package/dev/compile-backend.sh to use OpenCV3.4.1

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by kalyc** [comment]
@nswamy thanks for submitting the issue. The PR - https://github.com/apache/incubator-mxnet/pull/11147/files mentions that the OpenCV version will be updated in the next release

**Comment by nswamy** [comment]
Yes that is because we have already published the package and cannot undo without bumping up the version which will happen only after the next release.

**Comment by mariussoutier** [comment]
Will this fix the `Library not loaded: /usr/local/opt/opencv@2/lib/libopencv_calib3d.2.4.dylib` error?

**Comment by nswamy** [comment]
@mariussoutier. Yes it should fix that issue, however you could also install opencv2 on OSX as `brew install opencv@2`
We are fixing this in 1.2.1, the package is currently in staging 
https://repository.apache.org/#nexus-search;quick~org.apache.mxnet. Feel free to test and provide feedback. see the instructions to use packages in the Staging repo [here](https://cwiki.apache.org/confluence/display/MXNET/MXNet-Scala+Release+Process#MXNet-ScalaReleaseProcess-UsingPackagesinStagingRepository)

**Comment by nswamy** [comment]
#11862 fixes the issue

**Comment by nswamy** [comment]
#11862
