### ISSUE TITLE
onnx do not support conv weight from symbol

### ISSUE THREAD

**Issue by glingyan** [apache/incubator-mxnet#11195]
if weight is from another node
will raise exception
def _fix_channels(op_name, attrs, inputs, proto_obj):
    """A workaround for getting 'channels' or 'units' since onnx don't provide
    these attributes. We check the shape of weights provided to get the number.
    """
    weight_name = inputs[1].name
    if not weight_name in proto_obj._params:
        **raise ValueError("Unable to get channels/units attr from onnx graph.")**

![image](https://user-images.githubusercontent.com/22489989/41134562-98fb2c40-6aff-11e8-9fe0-03b73e97f384.png)

**Comment by lanking520** [comment]
Hi @glingyan , thanks for your issue. We will consider this as a `feature request`. @anirudhacharya @Roshrini can you take a look at this? @nswamy can you add label as `ONNX`?

**Comment by anirudhacharya** [comment]
@glingyan thank you for reporting the issue. Can you please share your complete use case. And the share the ONNX model you are trying to import.

**Comment by glingyan** [comment]
https://github.com/r9y9/wavenet_vocoder/ 
https://www.dropbox.com/s/zdbfprugbagfp2w/20180510_mixture_lj_checkpoint_step000320000_ema.pth?dl=0
https://www.dropbox.com/s/0vsd7973w20eskz/20180510_mixture_lj_checkpoint_step000320000_ema.json?dl=0

**Comment by glingyan** [comment]
I modify both pytorch and mxnet to successfully import the model
1. support Norm
2. to fix the issue, I bypass in torch to pass input size as attr
def mul(g, self, other):
     # See Note [Pointwise by scalar]
-    return g.op("Mul", self, _if_scalar_type_as(other, self), **_broadcast_if_scalar(other))
+    return g.op("Mul", self, _if_scalar_type_as(other, self), **_broadcast_if_scalar(other), self_i = self.type().sizes())

3. change reshape in pytorch
-    return g.op("Reshape", self, shape)
+    #shape = g.op("Constant", value_t=torch.LongTensor(size))
+    #return g.op("Reshape", self, shape)
+    return g.op("Reshape", self, shape_i=size)
4. fix split issue
 def split(g, self, split_size, dim):
@@ -491,7 +492,8 @@ def _convolution(g, input, weight, bias, stride, padding, dilation,
               # symmetric padding
               "pads_i": padding + padding,
               "dilations_i": dilation,
-              "group_i": groups}
+              "group_i": groups,
+              "out_channel_i":  weight_size[0]}

**Comment by glingyan** [comment]
please use pytorch v0.4.0, latest pytorch have big change on onnx,  and shape is also a operator, the graph increase 100% node size,

**Comment by glingyan** [comment]
actually for wavenet it is not a good reason to use onnx
