### ISSUE TITLE
Flaky test Python 3: Win: test_operator.test_gru_bidirectional 

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11202]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11191/2/pipeline

Not much in the error output:

```
test_operator.test_gru_bidirectional ... 

(py3) C:\jenkins_slave\workspace\ut-python-gpu>IF -1073741819 NEQ 0 exit /b 1 

script returned exit code 1
```

**Comment by ThomasDelteil** [comment]
I have had it too just now http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10637/5/pipeline

**Comment by ThomasDelteil** [comment]
And had it here too http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11210/2/pipeline/

**Comment by ThomasDelteil** [comment]
again http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10637/6/pipeline

**Comment by ThomasDelteil** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11225/2/pipeline

**Comment by szha** [comment]
duplicate #11219
