### ISSUE TITLE
Flaky test: test_gru_bidirectional

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11219]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11197/7/pipeline

```
test_operator.test_gru_sym ... ok

test_operator.test_gru_bidirectional ... 

(py2) C:\jenkins_slave\workspace\ut-python-gpu>IF -1073741819 NEQ 0 exit /b 1 

script returned exit code 1

```

**Comment by larroy** [comment]
can be reproduced with MXNET_MODULE_SEED=1447306965
python -mnose -v test_operator.py:test_gru_bidirectional

**Comment by ThomasDelteil** [comment]
duplicate here of this one
https://github.com/apache/incubator-mxnet/issues/11202

**Comment by ThomasDelteil** [comment]
This one is happening way too often, had it 3 times in 6 builds

**Comment by ThomasDelteil** [comment]
@lihaofd can you take a look please? thanks!

**Comment by ThomasDelteil** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11236/1/pipeline

**Comment by ThomasDelteil** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11225/4/pipeline

**Comment by aaronmarkham** [comment]
Still a problem...
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11261/4/pipeline

**Comment by ThomasDelteil** [comment]
@lihaofd could you disable this test while you investigate why it is failing on windows?

**Comment by aaronmarkham** [comment]
Doesn't seem disabled to me:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11287/1/pipeline

**Comment by ThomasDelteil** [comment]
might have been just merged and you got unlucky, got merged 1h ago as well

**Comment by aaronmarkham** [comment]
Ya, you're right. I saw the 16 hours ago and "merged" nearby so I thought that's when it happened. I definitely missed the window.
