### ISSUE TITLE
Bug in gluon.block.Block.LoadParams

### ISSUE THREAD

**Issue by rocketbear** [apache/incubator-mxnet#11222]
The following code is in the LoadParams function:

        for name in loaded:
            if not ignore_extra and name not in params:
                raise ValueError(
                    "Parameter '%s' loaded from file '%s' is not present in ParameterDict, " \
                    "which contains parameters %s. Set ignore_extra=True to ignore. "%(
                        name, filename, _brief_print_list(self._params.keys())))
            params[name]._load_init(loaded[name], ctx)

Apparently this code is buggy if name is in loaded but not in params.
The last line should be changed to:
```
        if name in params:
            params[name]._load_init(loaded[name], ctx)
```

**Comment by kalyc** [comment]
@rocketbear Thanks for opening this issue. I'm labeling it so MXNet community members can help resolve it. @sandeep-krishnamurthy could you add label "bug" to this?

**Comment by sandeep-krishnamurthy** [comment]
Just summarizing the issue for simplifying:
if name is not in params and ignore_extra=True

This line is executed, which it should not-> params[name]._load_init(loaded[name], ctx)

**Comment by apeforest** [comment]
I am looking at this issue now. I will create a JIRA ticket for it.

**Comment by apeforest** [comment]
It seems this issue has been fixed by PR: https://github.com/apache/incubator-mxnet/pull/11235

**Comment by kalyc** [comment]
@rocketbear could you verify the above and close this issue if it has been solved?
