### ISSUE TITLE
How to store a large distributed training model with KVStore？

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11221]
If the training model is large, and one single machine can‘t store the model，how do you solve it at present？The model is the result.

**Comment by kalyc** [comment]
Hi @liuzx32 there is an open discussion forum about mxnet on discuss.mxnet.io - you could post your query there to learn more.

**Comment by liuzx32** [comment]
@kalyc Thank you very much

**Comment by kalyc** [comment]
@liuzx32 could you please close this GitHub issue?

**Comment by liuzx32** [comment]
@marcoabreu Does mxnet support the training model distributed store in every worker or server？
