### ISSUE TITLE
CUDNN implementation of LSTMP layer

### ISSUE THREAD

**Issue by yunzhe-tao** [apache/incubator-mxnet#11253]
Hi, I want to implement the LSTM projection layer on MXNet Gluon. I was trying to implement the LSTMP layer similar to gluon.rnn.lstm based on gluon.contrib.rnn.LSTMPCell but I found that the ndarray.rnn function in LSTM._forward_kernel is implemented based on C++ and the codes are not available. Moreover, the function only works for RNN, LSTM and GRU. Without that function, I found LSTMP layer runs really slow. So I am wondering if someone can implement _forward_kernel for more general recurrent layers. Thanks.

**Comment by kalyc** [comment]
Thanks for submitting this issue @yunzhe-tao 
The MXNet community will pick this up as per the current backlog. In the meanwhile you could use the open discussion forum discuss.mxnet.io to learn more

**Comment by eric-haibin-lin** [comment]
@pengzhao-intel

**Comment by pengzhao-intel** [comment]
Thanks, @eric-haibin-lin , we will provide the CPU implementation in C++ level :)

**Comment by szha** [comment]
cudnn now provides LSTMP implementation in 7.2. https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#features-of-rnn-functions

Since this will require operator API changes, let's discuss in #9543.

**Comment by eric-haibin-lin** [comment]
@pengzhao-intel NVDIA will work on integrate this with the newly released CUDNN. Is there any plan to support this in mkl-dnn/CPU implementation?
