### ISSUE TITLE
Docker cache is not being used

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#11257]
As can be seen for all [latest builds](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11252/1/pipeline/70):  docker cache is not being reused and images are always getting rebuild. This is due to the ccache change https://github.com/apache/incubator-mxnet/pull/11151 

The problem is that due to [multiheaded docker build](https://github.com/apache/incubator-mxnet/blob/master/ci/docker/Dockerfile.build.armv7#L21-L31) the first build does not get a tag and is considered an intermediate layer.

The `--cache-from` parameter in [build.py](https://github.com/apache/incubator-mxnet/blob/master/ci/build.py#L79) restricts the cache only to tagged images and that leads to rebuilds.

**Comment by lebeg** [comment]
I don't have permissions to add labels, but I believe that this should be tagged with the `CI` label.

**Comment by lebeg** [comment]
@ThomasDelteil it is indeed related to ccache, but is a different error

**Comment by kalyc** [comment]
@sandeep-krishnamurthy could you add label "CI", "Docker" to this?

**Comment by lebeg** [comment]
The issue should have been fixed by https://github.com/apache/incubator-mxnet/pull/11302
