### ISSUE TITLE
Flaky test: Python 3: CPU Win

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11265]
```
remote file operation failed: C:/jenkins_slave/workspace/ut-python-cpu at hudson.remoting.Channel@232e68f3:JNLP4-connect connection from ip-172-31-2-173.us-west-2.compute.internal/172.31.2.173:49714: java.nio.file.AccessDeniedException: C:\jenkins_slave\workspace\ut-python-cpu
```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11261/3/pipeline/

**Comment by kalyc** [comment]
@aaronmarkham thanks for submitting the issue. @sandeep-krishnamurthy could you please add label "CI" "Python" to this?

**Comment by kalyc** [comment]
This appears to be a permissions issue `remote file operation failed: C:/jenkins_slave/workspace/ut-python-cpu at hudson.remoting.Channel@232e68f3:JNLP4-connect connection from ip-172-31-2-173.us-west-2.compute.internal/172.31.2.173:49714: java.nio.file.AccessDeniedException: C:\jenkins_slave\workspace\ut-python-cpu`

**Comment by marcoabreu** [comment]
Seems like our slave died..

**Comment by kalyc** [comment]
@marcoabreu is there a way to get the slave back up? Or is this solved?

**Comment by marcoabreu** [comment]
I don't think there is much we can do - especially considering our Windows slaves are effectively a black box. Closing for now
