### ISSUE TITLE
[Nightly Tests] Enable KVStore Single Node Test

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#11289]
This test is currently disabled since the test requires an instance with 4 GPUs which is not available in the MXNet CI at the moment. 
Adding a new instance type is on the roadmap.

**Comment by kalyc** [comment]
Thanks for submitting this issue @mbaijal 
@sandeep-krishnamurthy could you add label "CI", "Feature" to this?

**Comment by piyushghai** [comment]
@mbaijal Looks like the PR for enabling the KVStore Test got merged. 
Can you close this issue as well ?
