### ISSUE TITLE
Support Double precision type in Scala

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#11315]
Currently MXNet-Scala APIs support only float32, this would cause accuracy issues when customers port models between developed on Python to Scala. This needs to be fixed

**Comment by lupesko** [comment]
Thanks for reporting @nswamy - but is this a bug or a feature request?

**Comment by nswamy** [comment]
This is both a bug and feature request, since the accuracy will drop using Float32 on a model vs Float64

**Comment by lanking520** [comment]
Let's combine the conversation in here so we can kill dupes in issues: https://github.com/apache/incubator-mxnet/issues/10338

**Comment by piyushghai** [comment]
@mxnet-label-bot add [Feature request]
