### ISSUE TITLE
Cannot initializing parameters of SymbolBlock.

### ISSUE THREAD

**Issue by kice** [apache/incubator-mxnet#11334]
ref: https://discuss.mxnet.io/t/initializing-parameters-of-symbolblock/1213

It looks like SymbolBlock will initializing all the parameters using the initializer given in the block.initialize() function, including bias, which cannot be initialized by Xavier. 

Alought that [post](https://discuss.mxnet.io/t/initializing-parameters-of-symbolblock/1213) suggests a solution, and in addition, I think we should try to initialize the parameters if it was given in the symbol/json file.

e.g. 
`bias = mx.sym.Variable(name='conv_bias', shape=(num_filter,), init=mx.init.Zero())`
or
```
{
      "op": "null", 
      "name": "conv_bias", 
      "attrs": {
        "__init__": "[\"zero\", {}]", 
        "__shape__": "(64,)"
      }, 
      "inputs": []
}
```

Or if there a better way please let me know.

**Comment by vrakesh** [comment]
Thank you for reporting the issue , @kice , @sandeep-krishnamurthy , requesting to tag this under Gluon

**Comment by ThomasDelteil** [comment]
@kice the question as been answered on the forum, thanks!

@indhub can you please close the issue? Thanks!
