### ISSUE TITLE
Logic operator returns NDArrays of float, not int / boolean

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#11346]
## Description
Logical operators for NDArrays returns a float NDArray, which is counterintuitive and inconsistent of the description of the documentation. For example, [doc here](https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.not_equal).

## Steps to reproduce
It can be produced by running the code in the doc. It seems that the dtype of result NDArray is the same as the dtype of inputs.

For example, when x and y are of dtype int32, (x == y) returns int32.

```python
In [1]: import mxnet as mx
In [2]: x = mx.nd.ones((2,3)).astype("int32")
In [3]: y = mx.nd.arange(2).reshape((2,1)).astype("int32")
In [4]: (x == y).dtype
Out[4]: numpy.int32
```

However, when x and y are of dtype float32, (x == y) returns float32

```python
In [1]: import mxnet as mx
In [2]: x = mx.nd.ones((2,3)).astype("float32")
In [3]: y = mx.nd.arange(2).reshape((2,1)).astype("float32")
In [4]: (x == y).dtype
Out[4]: numpy.float32
```

**Comment by haojin2** [comment]
MXNet does not have bool type support right now.

**Comment by junrushao1994** [comment]
@haojin2 I mean it could be more reasonable if the returned type is `numpy.int`

**Comment by haojin2** [comment]
We may not want to make `numpy.int8` as the default here, if you really need the dtype to be `numpy.int8` you can add a `cast` in your model or script.

**Comment by junrushao1994** [comment]
If it is by design, I guess it will be great to mention in the documentation. Closing this issue for now.

**Comment by haojin2** [comment]
@junrushao1994 I think that's a fair point, we can definitely add that soon.
