### ISSUE TITLE
cudnn_tune and cudnnoff parameters are not passed via gluon

### ISSUE THREAD

**Issue by wenyangchu** [apache/incubator-mxnet#11342]
Hi all,
In the symbol interface, at least cudnn_tune and cudnn_off parameters are included in gluon interface:

mxnet.symbol.Convolution(data=None, weight=None, bias=None, kernel=_Null, stride=_Null, dilate=_Null, pad=_Null, num_filter=_Null, num_group=_Null, workspace=_Null, no_bias=_Null, cudnn_tune=_Null, cudnn_off=_Null, layout=_Null, name=None, attr=None, out=None, **kwargs)¶

Can we have them in gluon as kwargs? They are useful for choosing desired algorithms or only use cuda implementation.

**Comment by vrakesh** [comment]
Thank you for pointing this out, we will look into this, @sandeep-krishnamurthy , requesting to label this issue under Gluon, CUDA

**Comment by sandeep-krishnamurthy** [comment]
@wenyangchu - You could use "MXNET_CUDNN_AUTOTUNE_DEFAULT" environment variable for these options.
MXNET_CUDNN_AUTOTUNE_DEFAULT=0 for off, 1 for limited workspace (default), 2 for fastest.

**Comment by zhreshold** [comment]
Adding additional cudnn specific arguments sounds good to me
