### ISSUE TITLE
Minor typo in ./src/operator/nn/lrn.cc

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#11343]
## Description

Line 188 in [lrn.cc](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/lrn.cc#L188), should be

`.set_attr<nnvm::FListOutputNames>("FListOutputNames",`

## Build info

MXNet commit hash: ccee17672b23fa864f5c2e67d6bcea5ccff2979e (current master)

**Comment by vrakesh** [comment]
Thank you for , pointing out the error, @sandeep-krishnamurthy  requesting to label this under Bug
