### ISSUE TITLE
Question about push and pull of each layer.

### ISSUE THREAD

**Issue by wanderingpj** [apache/incubator-mxnet#11350]
In the backward process, as long as layer n generates the gradient, it can be immediately pushed. Once the update of the layer n is complete, it can be pulled, regardless of whether the push and pull of layer n-1, n-2...have completed.
I wonder if the statement above is correct.

**Comment by vrakesh** [comment]
@wanderingpj thank you for your question, @sandeep-krishnamurthy requesting this to labeled under questions.

**Comment by ThomasDelteil** [comment]
@wanderingpj can you expand a bit on your use-case? Without testing it myself I would say your assumption is correct.
@sandeep-krishnamurthy can you add [Pending Requester Info] tag?

**Comment by thomelane** [comment]
@yzhliu can we please close this issue due to lack of reply from author, thanks.
@wanderingpj is you're still interested in this, please follow up and we can reopen.
