### ISSUE TITLE
Flaky test test_gluon_trainer.test_trainer_reset_kv

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#11353]
Have seen this in a few PRs before. Now it's always failing in my PR.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11251/9/pipeline/749
```
test_gluon_trainer.test_trainer_reset_kv ... 

(py2) C:\jenkins_slave\workspace\ut-python-cpu>IF -1073741676 NEQ 0 exit /b 1 

script returned exit code 1
```

**Comment by zheng-da** [comment]
The same problem shows up in my very old branch (about one month old). So if there is a bug in the code, the bug exists a long time ago. If it's not a bug, it might be something in the Windows testing system (it only fails in Windows as far as I know).
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10893/5/pipeline

**Comment by marcoabreu** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1042/pipeline/752

**Comment by eric-haibin-lin** [comment]
I'm able to reproduce it on windows. Still investigating
