### ISSUE TITLE
Some problems encountered when using deconvolution

### ISSUE THREAD

**Issue by sifengyang** [apache/incubator-mxnet#11376]
the version of mxnet is 0.9, I use the Deconvolution operator base on resnet-50 for instance segmentation, but after dealing with several batch， the program breaks down, the error message is  

> [17:36:55] /home/gnss/mxnet/dmlc-core/include/dmlc/./logging.h:300: [17:36:55] src/operator/./cudnn_deconvolution-inl.h:205: Check failed: req[deconv::kBias] != kWriteInplace (2 vs. 2)

**Comment by vrakesh** [comment]
Thank you for reporting the issue, have you tried newer versions of mxnet? Perhaps that could help. We will look into this, @sandeep-krishnamurthy ,requesting tag this under bug, Also request you to provide a reproducible example, with your system configuration.

**Comment by anirudh2290** [comment]
@sifengyang can you please provide reproduction steps for the issue.

**Comment by sandeep-krishnamurthy** [comment]
Resolving as we don't have more info about reproducing the issue. @sifengyang - Please reopen if issue still persists
