### ISSUE TITLE
How to add out_grad in Regression_output-inl.h?

### ISSUE THREAD

**Issue by nihilityworld** [apache/incubator-mxnet#11386]
I want to train a net using LinearRegressionOutput Layer and a SoftmaxLayer. And I want to ignore some labe in LinearRegressionOutput. So how to add out_grad in Regression_output-inl.h?

**Comment by vrakesh** [comment]
@nihilityworld thank you for your question, requesting this be labeled under questions @sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
Hello @nihilityworld - For usage related question, please you https://discuss.mxnet.io/ forum for a response from wider mxnet community and also helps in the search for future similar questions.

Closing the issue here, please reopen if you face any issues.
