### ISSUE TITLE
how to train models with multiple gpus in C++

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#11400]
The `mx.mod.Module` provides a convenient high level api for model training in python. But due to some reasons, I need to train my models in pure C++ environment. I am wondering if it is also possible to support multiple gpu device with the interfaces in `cpp-package/include/mxnet-cpp`. Currently, I can only find the `Executor` in `cpp-package/include/mxnet-cpp/executor.h` which can get a single context variable each time.

**Comment by frankfliu** [comment]
@nicklhy 
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
Thanks!

**Comment by frankfliu** [comment]
@sandeep-krishnamurthy to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!
