### ISSUE TITLE
Understanding Memory Allocation in MXNet

### ISSUE THREAD

**Issue by ArmageddonKnight** [apache/incubator-mxnet#11402]
Hi there,

I have a question regarding the memory allocation in MXNet. I am trying to obtain the memory **breakdown** of the RNN language modeling example located in `example/rnn/word_lm`. However, after a naive implementation of putting a trace after the `cudaMalloc` call located in `src/storage/pooled_storage_manager.h` and `src/storage/gpu_device_storage.h`, like the following:

```C++
  cudaError_t e = cudaMalloc(&ret, size);

  // Trace the cudaMalloc function.
  static double accumulated_alloc_mem = 0.0;

  std::cout << "cudaMalloc from file " << __FILE__ << " is called." << std::endl;
  std::cout << "\t" "Allocated Memory (MB): " << size * 1.0 / 1e6 << std::endl;
  std::cout << "\t" "Allocated Memory (Accumulated, MB): " <<
    (accumulated_alloc_mem += size * 1.0 / 1e6) << std::endl;
  std::cout << "\t" << dmlc::StackTrace() << std::endl;

  ...
```

I noticed that this is only able to capture around `200` MB out of the total allocated `700` MB memory. 

Therefore, my question is the following:

- What is file `gpu_device_storage.h` used for? I see that it is neither included in any other files nor compiled.
- What are other possible places for GPU memory allocation to happen?

Thanks for the help.

**Comment by rahul003** [comment]
Look at `src/storage/pooled_storage_manager.h`. That's where all the allocation happens. It uses a memory pool. It tries to reuse memory when possible and only requests from CUDA if not enough memory is available in the pool.

**Comment by szha** [comment]
It's likely that the memory used in previous iteration was released back into the gpu memory pool and was held there for next use. This is optimization to reduce number of real allocation.

**Comment by ArmageddonKnight** [comment]
@rahul003 @szha Thank you so much for your comments, but in my opinion this still does not explain the mismatch between the accumulated memory (shown above, reported as `200` MB) and the one given by `nvidia-smi` (`700` MB). Even if there are some optimizations such as memory reuse etc., should the total accumulated memory (i.e. `accumulated_alloc_mem` in the above code snippet) be at least the actual amount of allocated memory (i.e. `accumulated_alloc_mem > actual_alloc_mem`)?

Any help is much appreciated.

**Comment by rahul003** [comment]
The 200M that you mention is from pooled_storage_manager?

**Comment by rahul003** [comment]
The rest can be CUDNN overhead if you're using CUDNN. This overhead can even go as high as 1GB for large models, in my experience.

**Comment by ArmageddonKnight** [comment]
@rahul003 The `200` MB comes from `pooled_storage_manager` and the `700` MB comes from `nvidia-smi`. I inserted the code above to accumulate the memory in `pooled_storage_manager.h` and the final value for `accumulated_alloc_mem` is around `200` MB. That's why I ask.

Yes. You are right, I guess cuDNN overhead is a plausible explanation.

**Comment by SunnyBeike** [comment]
@ArmageddonKnight  
Hi, I use the mlp_gpu example in the cpp-package to do the same experiments, but nothing was printed. Is there other operations I need to do to trace the memory allocation? Thanks.

**Comment by ArmageddonKnight** [comment]
@SunnyBeike Sorry but I am not sure what has happened in your case, but there should definitely be something printed. After all, MXNet needs to allocate certain amount of GPU memory to the inputs, outputs, and weight parameters (whether those sum up to be the total memory consumption reported by `nvidia-smi` is another problem). My suggestion goes as follows:

- Have you recompiled the core libraries (using `make`)?
- Are you sure that you are using the GPU implementation of the operators?

**Comment by SunnyBeike** [comment]
@ArmageddonKnight , Tahks.
- Have you recompiled the core libraries (using make)?
   Yes, I did compile the core libraries using 
`make -j 16 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda-9.0 USE_CUDNN=1 USE_DIST_KVSTORE=1`
- Are you sure that you are using the GPU implementation of the operators?
   Yes, the GPU usage was more than 70% when I run mlp_gpu benchmark.

Here is how did I trace the execution footprint of MxNet cpp example:
I inserted the std::cout<< "TRACE_LOG " in the Executor::Executor() function of  cpp-package/include/mxnet-cpp/executor.hpp, 
`inline Executor::Executor(const Symbol &symbol, Context context,
                          const std::vector<NDArray> &arg_arrays,
                          const std::vector<NDArray> &grad_arrays,
                          const std::vector<OpReqType> &grad_reqs,
                          const std::vector<NDArray> &aux_arrays,
                          const std::map<std::string, Context> &group_to_ctx,
                          Executor *shared_exec) {
  _**std::cout << "TRACE_LOG - " << " File:" << __FILE__ << " Line:"
                << __LINE__ << " Func:" << __FUNCTION__ << std::endl;**_
  this->arg_arrays = arg_arrays;
  this->grad_arrays = grad_arrays;
  this->aux_arrays = aux_arrays;
  this->symbol_ = symbol;

  std::vector<NDArrayHandle> arg_handles;
  std::vector<NDArrayHandle> grad_handles;
  std::vector<NDArrayHandle> aux_handles;

  for (const auto &array : arg_arrays) {
    arg_handles.push_back(array.GetHandle());
  }
  for (const auto &array : grad_arrays) {
    grad_handles.push_back(array.GetHandle());
  }
  for (const auto &array : aux_arrays) {
    aux_handles.push_back(array.GetHandle());
  }

  std::vector<mx_uint> grad_reqs_uint;
  for (auto s : grad_reqs) grad_reqs_uint.push_back(s);

  std::vector<const char *> map_keys;
  std::vector<int> dev_types, dev_ids;
  for (const auto &s : group_to_ctx) {
    map_keys.push_back(s.first.c_str());
    dev_types.push_back(s.second.GetDeviceType());
    dev_ids.push_back(s.second.GetDeviceId());
  }

  ExecutorHandle *shared_exec_handle =
      shared_exec == nullptr ? nullptr : &shared_exec->handle_;
  **_std::cout << "TRACE_LOG - " << " File:" << __FILE__ << " Line:"
                << __LINE__ << " Func:" << __FUNCTION__ << std::endl;_**
  CHECK_EQ(MXExecutorBindEX(symbol.GetHandle(), context.GetDeviceType(),
                            context.GetDeviceId(), group_to_ctx.size(),
                            map_keys.data(), dev_types.data(), dev_ids.data(),
                            arg_handles.size(), arg_handles.data(),
                            grad_handles.data(), grad_reqs_uint.data(),
                            aux_handles.size(), aux_handles.data(),
                            shared_exec_handle, &handle_),
           0);
  **_std::cout << "TRACE_LOG - " << " File:" << __FILE__ << " Line:"
                << __LINE__ << " Func:" << __FUNCTION__ << std::endl;_**
  mx_uint out_size;
  NDArrayHandle *out_array;
  CHECK_EQ(MXExecutorOutputs(handle_, &out_size, &out_array), 0);
  for (mx_uint i = 0; i < out_size; ++i) {
    outputs.push_back(NDArray(out_array[i]));
  }
}`
In this funtion, all the logs were printed normally. However, when I add logs in the MXExecutorBindEX() function (src/c_api/c_api_executor.cc), nothing was printed out.;

`int MXExecutorBindEX(SymbolHandle symbol_handle,
                     int dev_type,
                     int dev_id,
                     mx_uint num_map_keys,
                     const char** map_keys,
                     const int* map_dev_types,
                     const int* map_dev_ids,
                     mx_uint len,
                     NDArrayHandle *in_args,
                     NDArrayHandle *arg_grad_store,
                     mx_uint *grad_req_type,
                     mx_uint aux_states_len,
                     NDArrayHandle *aux_states,
                     ExecutorHandle shared_exec,
                     ExecutorHandle *out) {
  Executor* exec = nullptr;
  

  API_BEGIN();
    **_std::cout << "SUNBEILEI_LOG - " << " File:" << __FILE__ << " Line:"
                << __LINE__ << " Func:" << __FUNCTION__ << std::endl;_**
    return -1;
  nnvm::Symbol *symb = static_cast<nnvm::Symbol*>(symbol_handle);
  Context ctx = Context::Create(static_cast<Context::DeviceType>(dev_type), dev_id);
  std::map<std::string, Context> ctx_map;
  for (mx_uint i = 0; i < num_map_keys; ++i) {
    ctx_map[std::string(map_keys[i])] = Context::Create(
        static_cast<Context::DeviceType>(map_dev_types[i]), map_dev_ids[i]);
  }
  NDArray **in_args_ptr = reinterpret_cast<NDArray**>(in_args);
  NDArray **arg_grad_ptr = reinterpret_cast<NDArray**>(arg_grad_store);
  NDArray **aux_states_ptr = reinterpret_cast<NDArray**>(aux_states);
  std::vector<NDArray> in_args_vec;
  std::vector<NDArray> arg_grad_vec;
  std::vector<OpReqType> grad_req_vec;
  std::vector<NDArray> aux_states_vec;
  ...
}`
