### ISSUE TITLE
nd.softmax() doesn't support grad_req='add'

### ISSUE THREAD

**Issue by safrooze** [apache/incubator-mxnet#11411]
## Description
`nd.softmax()` does not support adding gradients specified by setting `grad_req` to `'add'`. This is obvious in [this line of code](https://github.com/apache/incubator-mxnet/blob/a0a52b38a9046a3ede20c900ff64154642e8e2da/src/operator/nn/softmax-inl.h#L267). 
However, `nd.SoftmaxActivation` which is deprecated does support `grad_req` equal to `'add'`. This issue came up in [this discuss questions](https://discuss.mxnet.io/t/aggregate-gradients-manually-over-n-batches/504/14?u=safrooze).

Package used: Python

## Error Message:
```
mxnet.base.MXNetError: [18:24:22] src/operator/nn/./softmax-inl.h:267: Check failed: req[0] != kAddTo (3 vs. 3)
```

## Minimum reproducible example
```python
import mxnet as mx
from mxnet import gluon, nd, autograd

print(mx.__version__)

grad_req = 'add'

x = (nd.random.uniform(shape=(2, 10)) - 0.5) * 10
x_g = nd.zeros_like(x)

autograd.mark_variables(x, x_g, grad_req)

with autograd.record():
    # Change nd.softmax to nd.SoftmaxActivation and the code doesn't throw an error
    y = nd.softmax(x)
y.backward()
print(x_g.asnumpy())
```

**Comment by frankfliu** [comment]
@safrooze Thank you for submitting the issue! We are labeling it so MXNet community members can help resolve it.

**Comment by haojin2** [comment]
@safrooze Taking a look at this now.

**Comment by haojin2** [comment]
@safrooze #11836 should fix this issue, I've tried your reproduction script and here's the output from it:
```
1.3.0
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [ -3.20495186e-09  -2.34470221e-10  -3.99168448e-10  -9.83819623e-11
   -3.74679523e-08  -8.85198338e-12  -7.68905792e-08  -7.67132469e-11
   -2.32276004e-10  -5.95953564e-10]]
```

**Comment by safrooze** [comment]
That's great, thanks @haojin2!

**Comment by sandeep-krishnamurthy** [comment]
Resolving as  #11836 is merged.
