### ISSUE TITLE
cannot find documentation for some python api

### ISSUE THREAD

**Issue by zchrissirhcz** [apache/incubator-mxnet#11412]
## Description
I read [MXNet's module API tutorial](https://mxnet.incubator.apache.org/tutorials/basic/module.html) and confused to some Python API's usage. On [the official python api url](https://mxnet.incubator.apache.org/api/python/) I can find many documentations but some are not find.

## Environment info (Required)

the environment is not required. I search the python API on your official website.

## Build info (Required if built from source)

The build info is not required.  I search the python API on your official website.

## Error Message:
There is not error message since no code run.

## Steps to reproduce

1. Go to https://mxnet.incubator.apache.org/tutorials/basic/module.html
2. Find some functions that don't know their concrete argument meaning
3. For example, `mx.sym.Convolution` can be found by typing `mxnet.symbol.Convolution`; However, `mx.test_utils` can never be found.

Hoping the documentation can be complete, thanks.

**Comment by frankfliu** [comment]
Hi @zchrissirhcz thanks for the question, @sandeep-krishnamurthy requesting this be labeled under Question

**Comment by frankfliu** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
@sandeep-krishnamurthy to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!

**Comment by sandeep-krishnamurthy** [comment]
@aaronmarkham - Can you please help?

**Comment by ThomasDelteil** [comment]
@zchrissirhcz a few module are indeed not in the API documentation as top-level packages as they should, for example the `mxnet.viz` and `mxnet.test_utils`. This is something we need to be fixed IMO, @aaronmarkham ?
 @indhub can you remove the question tag and add a [Bug] tag?
We should also try to handle better the shorthand versions of the modules: e.g `sym`->`symbol` `viz->vizualisation` `nd`->`ndarray`

**Comment by aaronmarkham** [comment]
I'm not sure why this is the case. My guess is that it is probably doxygen config. I can tackle it first thing next week. Can you assign the issue to me?

**Comment by sad-** [comment]
hi @aaronmarkham, what's the status of this?  any updates?
