### ISSUE TITLE
MXPredReshape

### ISSUE THREAD

**Issue by nihilityworld** [apache/incubator-mxnet#11413]
I have used the MXPredCreate to create a hanlder out use input shape [1,3,12,12]. And I use the MXPredReshape to change the input shape  to [1,3,430,360] and it return 0. But the input shape of the new hander out2 did not changed. Is it a bug?

**Comment by frankfliu** [comment]
Hi @nicklhy thanks for the question, @sandeep-krishnamurthy requesting this be labeled under Question

**Comment by frankfliu** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
@sandeep-krishnamurthy to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!
