### ISSUE TITLE
Can't iterate custom dataset by dataloader with 'num_workers > 1' param on Linux

### ISSUE THREAD

**Issue by ashkanaev** [apache/incubator-mxnet#11421]
Hi!

Let me introduce some problem which I've got runing this code:

First of all I have custom DataSet based on Dataset (mxnet.gluon.data)

```
class CustomDataSet(Dataset):
    def __init__(self, root):
        self.root = os.path.join(root)
        self.img_paths = []
        
        self._img = os.path.join(root, '{}.png')
        
        for fn in os.listdir(os.path.join(root)):
            if len(fn) > 3 and fn[-4:] == '.png':
                self.img_paths.append(fn[:-4])
        
    def __len__(self):
        return len(self.img_paths)
    
    def __getitem__(self, idx):
        img_path = self._img.format(self.img_paths[idx])

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = mx.nd.array(img)
        return img
```
I define dataset and loader like this:

```
    train_dataset = MultiBranchDataSet(args.dataset, 'train', ctx, args.class_weight, args.ignored_class, args.outputs)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=False, last_batch='rollover', num_workers = 4)
```
And trying to complete this code:

```
for data in train_loader:
	print(data.shape)
```

It's working on windows with num_workers > 1, but does't work on Linux on the same parametr.

>   File "/home/user/kpavel/mxnet_27_06/python/mxnet/gluon/data/dataloader.py", line 218, in __next__
>     idx, batch = self._data_queue.get()
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/queues.py", line 335, in get
>     res = self._reader.recv_bytes()
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
>     buf = self._recv_bytes(maxlength)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
>     buf = self._recv(4)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
>     chunk = read(handle, remaining)

Another words, I can't use Custom dataset and iterate my data in multiple threads.

Have you any ideas?

**Comment by frankfliu** [comment]
Hi @ashkanaev thanks for the question, @sandeep-krishnamurthy requesting this be labeled under Question

**Comment by ashkanaev** [comment]
I have achieved some result after I turn off multithreading OpenMP on OpenCV like this:
```
os.environ["OMP_NUM_THREADS"] = '1'
cv2.setNumThreads(0)
```
Unfortunately after 43-th batch I've got:

>   File "/home/user/kpavel/mxnet_27_06/python/mxnet/gluon/data/dataloader.py", line 218, in __next__
>     idx, batch = self._data_queue.get()
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/queues.py", line 337, in get
>     return ForkingPickler.loads(res)
>   File "/home/user/kpavel/mxnet_27_06/python/mxnet/gluon/data/dataloader.py", line 55, in rebuild_ndarray
>     fd = fd.detach()
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
>     with _resource_sharer.get_connection(self._id) as conn:
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
>     c = Client(address, authkey=process.current_process().authkey)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 493, in Client
>     answer_challenge(c, authkey)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 732, in answer_challenge
>     message = connection.recv_bytes(256)         # reject large message
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
>     buf = self._recv_bytes(maxlength)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
>     buf = self._recv(4)
>   File "/home/user/anaconda3/envs/mx/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
>     chunk = read(handle, remaining)
> ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by ThomasDelteil** [comment]
Can you try to use 
```
img = mx.image.imread(img_path)
```
instead of using cv2 and let me know if that still happen?

**Comment by zhreshold** [comment]
As far as I know, opencv seems to be not fork friendly, and therefore will cause all kinds of bug in multiprocessing.

**Comment by thomelane** [comment]
@zhreshold Agreed. Seems that OpenCV works will with multithreading but not with multiprocessing. See a few issues on their Github related to this (e.g. https://github.com/opencv/opencv/issues/5150).

Almost certain that @ThomasDelteil's suggestion will work though, it's used by `ImageFolderDataset` for example. It still uses OpenCV but calls it using an internal process.

**Comment by thomelane** [comment]
@yzhliu should be good to close this issue given the suggestions, thanks!
