### ISSUE TITLE
Shared Embedding layer with different input lengths and same vocabulary size

### ISSUE THREAD

**Issue by MandarGogate** [apache/incubator-mxnet#11420]
I'm building a classification model with name and description as features. I trained the model with a separate embedding layer but since these features share most of the words, I am wondering if there is any way to have a shared embedding layer with different input size. This will reduce significantly reduce the number of parameters in the network.

If I initialize two embedding layers with same weights as below would the weights be same after I train the network?

```python
weight = mx.sym.random.uniform(shape=(10000,50))
embed = mx.symbol.Embedding(data=inp1, name="embed1”, output_dim=50, input_dim=10000, weight=weight)
embed_2 = mx.symbol.Embedding(data=inp2, name="embed1”, output_dim=50, input_dim=10000, weight=weight)
```

I guess a workaround would be to simply force them to the same length, but this is not ideal since name is 5 times shorter than the description.

Any other ideas?

**Comment by sergeykolychev** [comment]
I use https://mxnet.incubator.apache.org/faq/bucketing.html for similar case.

In essence under the Bucketing module you can create multiple modules for with different input size and the same network graph, these modules share parameters of the module with longest input size that is created first.

**Comment by frankfliu** [comment]
Hi @MandarGogate thanks for the question, @sandeep-krishnamurthy requesting this be labeled under Question

**Comment by frankfliu** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
@sandeep-krishnamurthy to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!

**Comment by MandarGogate** [comment]
Thank you @sergeykolychev. It worked!
