### ISSUE TITLE
test_gluon_data:test_multi_worker fails with MKL

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#11455]
A new test has been added by @piiswrong in https://github.com/apache/incubator-mxnet/pull/8677/files#diff-ea07e742b95ae758f6877f7f9f5f2e74R102. It has been committed disabled and should be reenabled entirely.

**Comment by pengzhao-intel** [comment]
Interesting cases @threeleafzerg please help take a look.

**Comment by threeleafzerg** [comment]
I tried many times but it can not be reproduced in local machine . 
Do you know the reproduced step? 
@marcoabreu

**Comment by marcoabreu** [comment]
I'd love to help! Could you please describe how you try to reproduce the issue?

**Comment by threeleafzerg** [comment]
@marcoabreu 
Following is my reproduce step:
Change @unittest.skip("Somehow fails with MKL. Cannot reproduce locally") with @with_seed()
Then run test_gluon_data.py.  Result show all tests passed.

**Comment by marcoabreu** [comment]
How do you compile MXNet? What's the environment configuration?

**Comment by threeleafzerg** [comment]
make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=mkl USE_DIST_KVSTORE=1
My build system is centos 7.0

2018-07-05 11:40 GMT+08:00 Marco de Abreu <notifications@github.com>:

**Comment by marcoabreu** [comment]
@piiswrong please provide guidance how to reproduce the issue

P.s. we usually use openblas as blas library and not full mkl
