### ISSUE TITLE
Tracking issue for tests with fixed random seed

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#11501]
@eric-haibin-lin and @azai91 discovered that some unit tests have been using fixed seed to mask flakiness, opening this issue to keep track of those tests. Ideally every test should not be flaky with whatever seed. 
Tests with fixed seed:
 - test_ndarray/test_operator_gpu.test_ndarray_elementwise
 - test_ndarray/test_operator_gpu.test_ndarray_pickle
 - test_operator/test_operator_gpu.test_elementwise_sum
 - test_operator/test_operator_gpu.test_dot
 - test_operator/test_operator_gpu.test_roipooling
 - test_operator/test_operator_gpu.test_l2_normalization
 - test_operator/test_operator_gpu.test_bilinear_sampler
 - test_operator/test_operator_gpu.test_deformable_psroipooling
 - test_operator/test_operator_gpu.test_laop
 - test_operator/test_operator_gpu.test_laop_2
 - test_operator/test_operator_gpu.test_laop_3
 - test_operator/test_operator_gpu.test_laop_4
 - test_operator/test_operator_gpu.test_dropout
 - test_operator/test_operator_gpu.test_unary_math_operators
 - test_operator/test_operator_gpu.test_binary_math_operators
 - test_loss/test_operator_gpu.test_ce_loss
 - test_loss/test_operator_gpu.test_bce_loss
 - test_loss/test_operator_gpu.test_kl_loss
 - test_loss/test_operator_gpu.test_l2_loss
 - test_loss/test_operator_gpu.test_l1_loss
 - test_loss/test_operator_gpu.test_ctc_loss
 - test_loss/test_operator_gpu.test_ctc_loss_train
 - test_loss/test_operator_gpu.test_sample_weight_loss
 - test_loss/test_operator_gpu.test_saveload
 - test_loss/test_operator_gpu.test_huber_loss
 - test_loss/test_operator_gpu.test_hinge_loss
 - test_loss/test_operator_gpu.test_squared_hinge_loss
 - test_loss/test_operator_gpu.test_triplet_loss
 - test_sparse_ndarray/test_operator_gpu.test_sparse_nd_pickle
 - test_sparse_ndarray/test_operator_gpu.test_sparse_nd_save_load
 - test_executor.test_bind
 - test_executor.test_dot
 - test_module.test_module_set_params
 - test_module.test_monitor
 - test_module.test_factorization_machine_module
 - test_optimizer/test_operator_gpu.test_nag
 - test_optimizer/test_operator_gpu.test_ftml
 - test_optimizer/test_operator_gpu.test_signum
 - test_optimizer/test_operator_gpu.test_nadam
 - test_operator_gpu.test_ifft
 - test_operator_gpu.test_fft
 - test_operator_gpu.test_convolution_with_type
 - test_operator_gpu.test_bilinear_sampler_with_type
 - test_operator_gpu.test_pooling_with_type
 - test_operator_gpu.test_psroipooling_with_type
 - test_operator_gpu.test_deformable_psroipooling_with_type
 - test_operator_gpu.test_deformable_convolution_with_type
 - test_ndarray/test_operator_gpu.test_cached
 - test_operator/test_operator_gpu.test_rnnrelu_bidirectional
 - test_operator/test_operator_gpu.test_sequence_last
 - test_gluon/test_operator_gpu.test_conv
 - test_gluon/test_operator_gpu.test_export
 - test_gluon_data.test_multi_worker
 - test_io.test_ImageRecordIter_seed_augmentation
 - test_nccl.test_nccl_pushpull
 - test_operator_gpu.test_pooling_versions
 - test_quantization.test_get_optimal_thresholds

Please refer this issue if you're providing a fix to any of those tests.

**Comment by frankfliu** [comment]
Thank you for submitting the issue! @sandeep-krishnamurthy requesting this be labeled under feature request.

**Comment by szha** [comment]
Thanks for summarizing the issues @haojin2. Fixed seed indeed has the effect of hiding flaky tests so we should treat these as flaky tests until fixed. On the other hand, I think it's probably better to track them as individual items so that people can contribute to the fix one at a time. I will go ahead and split these into individual issues.
