### ISSUE TITLE
MXNet 1.2.0 - net.save_params() output parameter file contains garbage

### ISSUE THREAD

**Issue by simonmaurer** [apache/incubator-mxnet#11522]
## Description
When using Gluon APIs gluon.nn.SymbolBlock to load a pretrained VGG16 and finetune the model (while replacing the last VGG16 layer with an additional FullyConnected layer) the model file (.json) can be correctly saved, but not the parameters (weights, biases) with net.save_params().
The resulting file is of size 32Byte (no matter what size the additional layer) containing the only binary data:
\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
Model used:
'http://data.dmlc.ml/models/imagenet/vgg/vgg16-symbol.json'
'http://data.dmlc.ml/models/imagenet/vgg/vgg16-0000.params'

## Environment info (Required)
Ubuntu 16.04, MXNet version 1.2.0 (pip3 compiled version)

## Minimum reproducible example
    context = mx.cpu() # same for mx.gpu(0)
    data = mx.sym.var('data')
    sym, arg_params, aux_params = mx.model.load_checkpoint(<model-path>, 0)
    layers = sym.get_internals()
    sym = layers['fc8' + '_output']
    new_sym = mx.symbol.FullyConnected(data=sym, num_hidden=32, name='bit_layer')
    new_params = dict({k: arg_params[k] for k in arg_params if 'bit_layer' not in k})
     
    net = gluon.nn.SymbolBlock(outputs=new_sym, inputs=data)
    net_params = net.collect_params()
    net_params.initialize(mx.init.Uniform(scale=0.1), ctx=context)
    for param in new_params:
        if param in net_params:
            net_params[param]._load_init(new_params[param], ctx=context)
    for param in aux_params:
        if param in net_params:
            net_params[param]._load_init(aux_params[param], ctx=context)
    net.hybridize()
    # Save symbol from Gluon
    sym_json = net(data)
    sym_json.save('test-symbol'+'.json')

    # Save weights after first passing some data to build the graph (not listed here)
    net.save_params('test.params')`

## What have you tried to solve it?

1. Revert to MXNet 1.1.0 -> net.save_params() works accordingly! Size of weights file (.params) will be roughly 500MB
2. Assumption MXNet 1.2.0 model incompatibility with pretrained models created with earlier versions (VGG16 used here was created with MXNet version 0.8)
3. use net.export("test", epoch=0) ??

**Comment by marcoabreu** [comment]
@piiswrong @ThomasDelteil

**Comment by ThomasDelteil** [comment]
@simonmaurer 
please use 
```python
net.hybridize()
net(mx.nd.ones((1,3,224,224))
net.export('test')
```
To export your model.
You will get a `test-symbol.json` and `test-0000.params` file.

For more details refer to this tutorial: https://mxnet.incubator.apache.org/tutorials/gluon/save_load_params.html
