### ISSUE TITLE
mxnet.base.MXNetError  src/storage/storage.cc:127: Unimplemented device 0 when using with sockeye 

### ISSUE THREAD

**Issue by omarkaraksi** [apache/incubator-mxnet#11538]
## Description : 
I faced this problem while trying to use mxnet with sockeye for machine translation after third  translation attempt mxnet raises the following bug . 

## The full error stack : 

mxnet.base.MXNetError: [12:52:28] src/storage/storage.cc:127: Unimplemented device 0
Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x1c05f2) [0x7f13e134e5f2]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x1c0bd8) [0x7f13e134ebd8]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2d7d38f) [0x7f13e3f0b38f]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2d8141d) [0x7f13e3f0f41d]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2d83206) [0x7f13e3f11206]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2d856e1) [0x7f13e3f136e1]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0xb90474) [0x7f13e1d1e474]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x279aff0) [0x7f13e3928ff0]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x279f1b1) [0x7f13e392d1b1]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2782964) [0x7f13e3910964]

## Environment info 
python 3.5
sockeye 1.18
mxnet 1.1

**Comment by andrewfayres** [comment]
Thank you for submitting the issue! @sandeep-krishnamurthy requesting this be labeled as python, bug.

**Comment by sandeep-krishnamurthy** [comment]
@omarkaraksi - Can you please provide code snippet you are using?
At high level looks like context is not being set correctly or you are trying to use GPU on a CPU MXNet build.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@omarkaraksi Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment]
@mxnet-label-bot add [suggest-closed]

**Comment by rkahani** [comment]
If you are using the Flask, it may be because of multithreading.
So, one solution would be:
app.run(threaded=False)

https://github.com/awslabs/sockeye/issues/671#issuecomment-477602579
