### ISSUE TITLE
gpu memory used

### ISSUE THREAD

**Issue by xizi** [apache/incubator-mxnet#11539]
![image](https://user-images.githubusercontent.com/3853150/42222141-d519be74-7f06-11e8-9a68-d4535013702e.png)
When i train a classification network in multi-GPU style, the gpu0 memory is larger than others. Is a test network occupy the gpu0 memory. In that circumstances, how can i remove the test network ?

**Comment by azai91** [comment]
could you provide a bit more details about your code? are you using a network from the model zoo or a custom one?

**Comment by xizi** [comment]
@azai91  i have solved this problem by revise kvstrore = "local"
