### ISSUE TITLE
AttributeError: module 'mxnet.contrib.onnx' has no attribute 'get_model_metadata'

### ISSUE THREAD

**Issue by gr8Adakron** [apache/incubator-mxnet#11536]
I am getting this error while running the tutorial of:
[https://mxnet.incubator.apache.org/tutorials/onnx/inference_on_onnx_model.html](https://mxnet.incubator.apache.org/tutorials/onnx/inference_on_onnx_model.html)

in line:
`model_metadata = onnx_mxnet.get_model_metadata(onnx_path)`

```
python-version = 3.6
=============================
mxnet==1.2.0
onnx==1.2.2
```

Any help?

**Comment by andrewfayres** [comment]
Thank you for submitting the issue! Some more details such as a stack trace would probably be helpful. @sandeep-krishnamurthy requesting this be labeled as example, onnx, gluon.

**Comment by anirudhacharya** [comment]
@gr8Adakron ``get_model_metadata`` API was introduced after the v1.2 release. Could you do a source build and try again.

**Comment by sandeep-krishnamurthy** [comment]
pypi --pre package should get you nightly master builds. @anirudhacharya  - `pip install mxnet --pre` will get `get_model_metadata` API?

**Comment by anirudhacharya** [comment]
yes it should.

**Comment by gr8Adakron** [comment]
Yes! eventually, I figured out its presence in the repo. So, I built it using the master branch and it ran successfully.
