### ISSUE TITLE
Silient CHECK's fails. How to enable logginig for c++ API.  

### ISSUE THREAD

**Issue by ashkanaev** [apache/incubator-mxnet#11541]
Hi, there

I’m trying to find error in my c++ application. There is some error while forward. I found a lot of logging in mxnet, but in console appears only few messages by LOG().

My question is How to enable all levels of logging in mxnet with c++ API. How to redict logger to file or console? Is googleglog required?

Help, please. I’m tried to find failed CHECK’s **manually**. It’s slows down R&D critically.

**Comment by andrewfayres** [comment]
Looks like you're also asking this on the discussion forum. There it will get a wider audience and allow other to learn as well. I'm closing this issue now in favor of the discussion forum issue
Thanks!

@sandeep-krishnamurthy, please label this as question and close in favor of the discussion forum.

**Comment by ctcyang** [comment]
By default, MXNet uses googlelog (see [2]). In googlelog, the default level of logging is to log all levels: INFO, WARNING, ERROR, and FATAL (see [1] for more information). For me, even LOG(INFO)'s get printed by default.

[1] http://rpg.ifi.uzh.ch/docs/glog.html
[2] https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h
