### ISSUE TITLE
Pip package can be much faster (OpenCV version?)

### ISSUE THREAD

**Issue by rahul003** [apache/incubator-mxnet#11549]
## Description
When I build MXNet from source using same build flags as pip package uses, I get much faster speeds. Not sure which versions of dependencies could be different in our case. I used all standard dependencies versions that come with AWS Deep Learning AMI (Cuda 9, CUDNN 7005). This could be because of the OpenCV version used to build. Happy to provide any information needed on this front.

Here is a comparison of running Resnet50v1 on the Imagenet dataset using 8 V100s on a p3.16xl machine with 2048 batch size fp16, all else being equal.

**Built from source: ~5200 samples/sec
Nightly pip package mxnet-cu90: ~3500 samples/sec**

## Environment info

```
----------Python Info----------
Version      : 3.6.4
Compiler     : GCC 7.2.0
Build        : ('default', 'Jan 16 2018 18:10:19')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/ubuntu/anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-4.4.0-1061-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-15-196
release      : 4.4.0-1061-aws
version      : #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               1200.402
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.10
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-15,32-47
NUMA node1 CPU(s):     16-31,48-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt ida
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0057 sec, LOAD: 0.4343 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1129 sec, LOAD: 0.1909 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.2744 sec, LOAD: 0.1096 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0097 sec, LOAD: 0.0958 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0022 sec, LOAD: 0.3638 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0136 sec, LOAD: 0.0810 sec.
```

Package used (Python/R/Scala/Julia): Python

## Build info
Compiler: gcc 5.4
MXNet commit hash: 99ac2f571b3c4431e8a7bd64ad13035e22259cf9 

Build config: 
USE_OPENMP=1 USE_DIST_KVSTORE=1 USE_BLAS=openblas USE_LAPACK=1 USE_NVRTC=1 USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_SIGNAL_HANDLER=1 USE_OPENCV=1

Here's the output of ldd on my binary
```
ldd lib/libmxnet.so
	linux-vdso.so.1 =>  (0x00007ffd9bdb0000)
	/usr/lib/libmpi_cxx.so (0x00007fab7d839000)
	libcudart.so.9.0 => /usr/local/cuda/lib64/libcudart.so.9.0 (0x00007fab7d5cc000)
	libcublas.so.9.0 => /usr/local/cuda/lib64/libcublas.so.9.0 (0x00007fab7a196000)
	libcurand.so.9.0 => /usr/local/cuda/lib64/libcurand.so.9.0 (0x00007fab76232000)
	libcusolver.so.9.0 => /usr/local/cuda/lib64/libcusolver.so.9.0 (0x00007fab71637000)
	libopenblas.so.0 => /usr/local/lib/libopenblas.so.0 (0x00007fab706a2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fab7049a000)
	libopencv_imgcodecs.so.3.4 => /usr/local/lib/libopencv_imgcodecs.so.3.4 (0x00007fab6feb2000)
	libopencv_imgproc.so.3.4 => /usr/local/lib/libopencv_imgproc.so.3.4 (0x00007fab6d5c0000)
	libopencv_core.so.3.4 => /usr/local/lib/libopencv_core.so.3.4 (0x00007fab6c68b000)
	libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7 (0x00007fab5b1f4000)
	libcufft.so.9.0 => /usr/local/cuda/lib64/libcufft.so.9.0 (0x00007fab53153000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007fab522d5000)
	libnvrtc.so.9.0 => /usr/local/cuda/lib64/libnvrtc.so.9.0 (0x00007fab50a8a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fab50708000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fab503ff000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fab501dd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fab4ffc7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fab4fdaa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fab4f9e0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fab8df73000)
	libmpi.so.12 => /usr/lib/libmpi.so.12 (0x00007fab4f70a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fab4f506000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fab4f1db000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fab4ef82000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fab4ed5d000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fab4eae9000)
	libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007fab4e894000)
	libIlmImf-2_2.so.22 => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22 (0x00007fab4e3c6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fab4e1ac000)
	libnvidia-fatbinaryloader.so.384.111 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.111 (0x00007fab4df5a000)
	libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00007fab4dd4b000)
	libopen-rte.so.12 => /usr/lib/libopen-rte.so.12 (0x00007fab4dad1000)
	libopen-pal.so.13 => /usr/lib/libopen-pal.so.13 (0x00007fab4d834000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fab4d5f5000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fab4d3d3000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fab4d1c5000)
	libHalf.so.12 => /usr/lib/x86_64-linux-gnu/libHalf.so.12 (0x00007fab4cf82000)
	libIex-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12 (0x00007fab4cd64000)
	libIlmThread-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12 (0x00007fab4cb5d000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007fab4c923000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fab4c720000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fab4c515000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fab4c30b000)
```

**Comment by szha** [comment]
Does the speed difference come from IO or model?

**Comment by rahul003** [comment]
The IO because for a scenario with less IO load (batch size of 1024 as against the 2048 batch size above), speed of pip package is as expected.

**Comment by szha** [comment]
I see, so you are seeing little to no difference in performance if you use dummy data? I will check what the apt package has for opencv. Note that it may end up not being feasible for pip package, given that we cannot optimize for specific hardware, for portability.

**Comment by chinakook** [comment]
Yes, I found that a years ago. The speed can be different when using different libopencv. The libopencv shipped with Ubuntu will run slower than that built by yourself.
The building system has also affects on speed, for example, MXNet built by config.mk is faster than that built by CMake. The latter will run very slow on some special case.

**Comment by lebeg** [comment]
That is an interesting observation @chinakook, do you have a bit more detail about this so we can identify the root cause?

**Comment by chinakook** [comment]
The first issue can be tested with https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/train_mnist.py
The second issue can be tested with my [repo](https://github.com/chinakook/hr101_mxnet). MXNet built by config.mk will take 1.3s to detection while the CMake built one may take 20s to run on a Nvidia 1080Ti even when the CUDNN_AUTOTUNE is set to 0.

**Comment by rahul003** [comment]
@hetong007 Yes the commit used by the pip package I tried (also again with Jul 3'rd version) is after your commit.

**Comment by rahul003** [comment]
@szha Yes, with dummy data, they match.

**Comment by szha** [comment]
I've made updates in pip it can now achieve similar speed. Let's wait for tomorrow's nightly build to verify

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Could you please label this issue as _pip_, _Performance_ and _installation_

**Comment by szha** [comment]
FYI, the speed-up in opencv comes from its switch to libturbojpeg in 3.4.2, happened in opencv/opencv#11497

**Comment by srochel** [comment]
@szha - what is the performance with you change?

**Comment by szha** [comment]
The speed matches what was reported for building from source.

**Comment by srochel** [comment]
@szha What are the results with the updates?

**Comment by tcye** [comment]
> The first issue can be tested with https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/train_mnist.py
> The second issue can be tested with my [repo](https://github.com/chinakook/hr101_mxnet). MXNet built by config.mk will take 1.3s to detection while the CMake built one may take 20s to run on a Nvidia 1080Ti even when the CUDNN_AUTOTUNE is set to 0.

I recently also found this problem, mxnet build with cmake is much slower with some light network, have you locaed this issue? I found some cflags diff such as -floop-unroll, but unfoutunately, when I add these flags to cmake, no help...

**Comment by lebeg** [comment]
Actually, we think we found the reason for the slowdown in CMake builds. It's due to the fact that even with MKL set to be used, the library is still linked to openblas and the math functions are being linked and used from there instead.
