### ISSUE TITLE
Wrong conversion of `Split` operator of ONNX

### ISSUE THREAD

**Issue by mitmul** [apache/incubator-mxnet#11555]
The `split` attribute of `Split` operator in ONNX is defined as `list of ints`:
https://github.com/onnx/onnx/blob/v1.1.0/docs/Operators.md#Split

However, this attribute is converted into `num_outputs` of `SliceChannel` in MXNet. `num_outputs` should be an integer value, so that this causes error when the ONNX file which has `Split` operator is imported by MXNet using `mxnet.contrib.onnx.import_model`.

https://github.com/apache/incubator-mxnet/blob/7d91602ba771d973360f8a0c66c976c67f700aa3/python/mxnet/contrib/onnx/onnx2mx/_op_translations.py#L411

Is this a bug of MXNet?

**Comment by marcoabreu** [comment]
@Roshrini didn't we have full test coverage for all ONNX supported operators?

**Comment by Roshrini** [comment]
Thanks for reporting the issue. ONNX split operator supports equal and variable splits while MXNet supports only equal splits of a tensor. Have created a PR which should solve this and enabled onnx backed test for equal splits.

**Comment by mitmul** [comment]
Thanks for working on this issue. Please close this issue after the PR is merged.

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy  https://github.com/apache/incubator-mxnet/pull/11593 merged which solves this issue. Can you please close this issue? Thanks!
