### ISSUE TITLE
Deprecate USE_PROFILER from make/cmake.

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#11563]
Let's deprecate USE_PROFILER from cmake and build systems as this flag is now always on at compile time.  Having this option seems to be confusing users.  Doing a full removal from cmake should be safe, and should present users with an intuitive message.  For other build systems we may need to provide a deprecation message.

**Comment by rahul003** [comment]
It's not used for make as well. It can be safely removed. The only usage of USE_PROFILER in the repo are in build scripts and documentation currently.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this issue _Build_, _Deprecate_, _Doc_. Thx

**Comment by ChaiBapchya** [comment]
@KellenSunderland any update on this? Can we close this issue otherwise?

**Comment by KellenSunderland** [comment]
I think we still have to remove this option from our codebase right?  I see a lot of documentation wrongly instructing users to set it to true for an example.
