### ISSUE TITLE
Build timeouts after ccache added

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#11564]
Some rare build failures occur after the addition of ccache. Sample: 

http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-11486/runs/1/nodes/57/log/?start=0

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11486/1/pipeline/

The builds are hitting the Jenkin's timeout as the task fails at exactly the 2h mark.

The machine will probably have a running container until it's down-scaled due to the zombie container bug.

Adding build retries and lowering the Jenkins build timeout should improve the situation.

**Comment by andrewfayres** [comment]
@sandeep-krishnamurthy requesting this be CI

**Comment by szha** [comment]
@marcoabreu you're probably interested.

**Comment by lebeg** [comment]
Zombie container issue has been resolved with https://github.com/apache/incubator-mxnet/pull/12381. Retries had been added with https://github.com/apache/incubator-mxnet/pull/11877. Issue should be resolved.
