### ISSUE TITLE
im2rec number of threads in R

### ISSUE THREAD

**Issue by lichen11** [apache/incubator-mxnet#11569]
In the im2rec function in R, is there an option to specify number of threads? So far I am seeing the following options. I am aware that the Python im2rec.py has num_thread parameter. I am using mxnet 1.3.0.

im2rec(image_lst, root, output_rec, label_width = 1L, pack_label = 0L,
  new_size = -1L, nsplit = 1L, partid = 0L, center_crop = 0L,
  quality = 95L, color_mode = 1L, unchanged = 0L, inter_method = 1L,
  encoding = ".jpg")

**Comment by andrewfayres** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well. I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!

@sandeep-krishnamurthy  please close this issue

**Comment by sandeep-krishnamurthy** [comment]
@anirudhacharya @ankkhedia
