### ISSUE TITLE
MXNet v1.2.0 branch PR build failure

### ISSUE THREAD

**Issue by Roshrini** [apache/incubator-mxnet#11567]
## Description
HI, following PR Builds are failing on dockcross-linux-arm64. 
https://github.com/apache/incubator-mxnet/pull/11478
https://github.com/apache/incubator-mxnet/pull/11548

Probably some issue with this dockerfile:
https://hub.docker.com/r/mxnetci/dockcross-linux-arm64/tags/

@marcoabreu  Can you please take a look?

@anirudh2290 

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by marcoabreu** [comment]
@larroy

**Comment by larroy** [comment]
@lebeg add to our lists please

**Comment by larroy** [comment]
I have a fix for this on a branch.

**Comment by apeforest** [comment]
@Roshrini It seems the two PRs you listed in description have been merged. Could you verify if they are built successfully?

**Comment by Roshrini** [comment]
Thanks for working on the issue. Builds were successful and PRs are merged. Thanks!
