### ISSUE TITLE
MXPredCreate Input Parameters

### ISSUE THREAD

**Issue by RedbackThomson** [apache/incubator-mxnet#11589]
Hello!

While the C API has inline comments, and the documentation describes the input parameters for the methods, it is difficult to understand what they actually mean.

I have seen a number of other people online have asked about 2 parameters in particular:
input_shape_indptr
input_shape_data

The examples tell us that input_shape_indptr should be {0, 4} for a 4-dimensional FeedForward model with 1 input node. However, how would this be modified for 2 or 3 input nodes, each with different dimensions?
This must be fundamentally linked to input_shape_data, which I believe describes the shape of each of the dimensions?

I see in the source that the input_shape_indptr points to indices in the input_shape_data to create a nnvm::TShape. However, since there is no index 4, I don't understand why this value is valid.

Thank you

**Comment by andrewfayres** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!

@sandeep-krishnamurthy please close this issue
