### ISSUE TITLE
Mxnet function

### ISSUE THREAD

**Issue by yyl199655** [apache/incubator-mxnet#11583]
If I want to extract a few lines of a matrix(symbol), how should I do?

**Comment by andrewfayres** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!

@sandeep-krishnamurthy please close this issue
