### ISSUE TITLE
Large Word LM Training

### ISSUE THREAD

**Issue by yunzhe-tao** [apache/incubator-mxnet#11597]
Hi, I noticed that the large_word_lm model in the folder example/rnn/ has been modified recently. However, the perplexity increases at this version. Could anyone explain the differences between two versions?

Moreover, I ran the codes on p3.8xlarge instance and found that the validation process takes much more time than before. Why is it? Previously the whole validation takes only about 10 minutes, but now it's more than 2 hours.

Thanks.

**Comment by andrewfayres** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
Thanks!

@sandeep-krishnamurthy please close this issue
