### ISSUE TITLE
RecordIO DataIter and online triplet generation

### ISSUE THREAD

**Issue by jrabary** [apache/incubator-mxnet#1159]
I'm trying to train a triplet network and I want to create the examples online since pre-computing all possible triplet is not tractable. The idea is to put my raw data (image jpg + label) in a RecordIO DB and run an online triplet sampling by iterating again and again on this RecordIO database. This process should run on a different thread since it's time consuming. There's a PrefetchIter that may help me but I just can't figure out how pieces fit together. Furthermore, is running image decoding and online augmentation run after the triplet generation to avoid decoding every images is interesting ? I mean, should I do : 

RecodIO -> Triplet Generation -> Image Decoder -> Data Augmentation

or 

mx.io.ImageRecordIter -> Triplet Generation

**Comment by piiswrong** [comment]
You can do either, depending on your use case.

**Comment by jrabary** [comment]
@piiswrong is there an example of creating a multi threaded DataIterator ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
