### ISSUE TITLE
Building MXNet Scala produces too many warnings

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#11603]
When Building the Scala package on the master branch, I see too many warnings for unrecognized documentation strings and library mismatch. The doc strings themselves are retrieved from the backend. 

These show up when there are examples with equations. One possible way to fix it is to add **pre** blocks 
<pre>Example </pre> block. 
<pre>
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5163: warning: Could not find any member to link for "3,6,6],[4,5,1".
  /**
  ^
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5239: warning: Could not find any member to link for "".
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5358: warning: Could not find any member to link for "".
  /**
  ^
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5548: warning: Could not find any member to link for "".
  /**
  ^
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5584: warning: Could not find any member to link for "".
  /**
  ^
~/scala-package/core/src/main/scala/org/apache/mxnet/NDArrayAPIBase.scala:5622: warning: Could not find any member to link for "".
</pre>

**Comment by srochel** [comment]
What is the right way to fix the warnings?

**Comment by nswamy** [comment]
The warnings that are mentioned are fixed with the PR referenced. 
There are still some warnings(tech debt) due to the fact that the dependencies use different versions Scala library. We haven't found a way to use Scala 2.11.x in maven. One approach could be update the Scala version to 2.12(needs careful thought to see if it breaks compatibility). I think that can be taken as a separate issue.

**Comment by nswamy** [comment]
closing in favor of https://github.com/apache/incubator-mxnet/issues/11879
