### ISSUE TITLE
[Scala] JavaDocs generated in the core/infer modules are not a part of the assembly Jar

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#11618]
JavaDocs generated in the core/infer modules are not included in the jar produced for the full assembly javadocs. Since we publish the full jars to maven, they should have complete javadocs.

This should also include the SymbolAPIBase and NDArrayAPIBase.

**Comment by lanking520** [comment]
@nswamy Problem addressed, shall we close this?
