### ISSUE TITLE
How to do image down sampling in Mxnet?

### ISSUE THREAD

**Issue by xmuszq** [apache/incubator-mxnet#11614]
Problem: 
I want to resize the image in mxnet, simply like down-sample the image from 200*200 to 100*100. It's easy in Python with other packages like opencv or others. But I search the mxnet, I didn't find any solution to do it in mxnet. Or do down sampling in MXNET's Ndarray. 
Anyone knows the solution?

Best regards!

**Comment by apeforest** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well. I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error. Thanks!

**Comment by apeforest** [comment]
@xmuszq I have posted to the forum for you. You may track the answer here: https://discuss.mxnet.io/t/how-to-do-image-down-sampling-in-mxnet/1384

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please close this issue.

**Comment by xmuszq** [comment]
Thank you for your help!
