### ISSUE TITLE
Find government repositories

### ISSUE THREAD

**Issue by daedaesplayground1911** [apache/incubator-mxnet#11612]
Find government auctions and other valueable resources that they offer online.

**Comment by marcoabreu** [comment]
Hi, I'm sorry, but I'm afraid I don't understand. Could you elaborate a bit more please?

**Comment by apeforest** [comment]
@daedaesplayground1911 Please elaborate this question a bit more or provide more details. Thx

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy This question seems unrelated to MXNet Repository. 
Can you please close this issue ?

**Comment by sandeep-krishnamurthy** [comment]
@daedaesplayground1911  - Please reopen once get more details on this issue. Resolving it for now. Thanks.

**Comment by daedaesplayground1911** [comment]
Yes I'm specifically searching for government liquidation sites and places where I can aquire documents relating to services that are offered to any citizen and people with disabilities.

**Comment by daedaesplayground1911** [comment]
I'm trying to find government liquidation places that specifically specialize in selling vehicles, weapons, used smartphones, and computers.
