### ISSUE TITLE
LBSGD does not have momentum

### ISSUE THREAD

**Issue by al-rigazzi** [apache/incubator-mxnet#11620]
https://github.com/apache/incubator-mxnet/blob/8fde4b7526acbbe242fd5a5f41fac9e477f927f3/example/image-classification/common/fit.py#L219

Hi, I was wondering why LBSGD is not listed as a method with momentum, since it looks like the class offers the possibility of setting it.

**Comment by apeforest** [comment]
For questions, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!

**Comment by apeforest** [comment]
Thanks for posting this question on the forum. @sandeep-krishnamurthy Please close this issue.

**Comment by thomelane** [comment]
@sandeep-krishnamurthy @apeforest can we reopen and tag, looks like this should actually be updated. Signum and LBSGD both have momentum but aren't included here.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this issue _Example_, _Good for first time_

**Comment by vishaalkapoor** [comment]
@thomelane I've submitted a pull request that adds signum and lbsgd to the list of optimizers with momentum. Please take a look: [link](https://github.com/apache/incubator-mxnet/pull/11826)
