### ISSUE TITLE
deconvolution result different with caffe result

### ISSUE THREAD

**Issue by wxcstc** [apache/incubator-mxnet#11629]
## Description
same params, deconvolution result different with caffe 

## Environment info (Required)
windows 10
python3 mxnet version "1.3.0"

Package used (Python/R/Scala/Julia):
I'm using Python

## Steps to reproduce
1.  python code as below:
`import mxnet as mx`
`import mxnet.ndarray as nd`
`a = nd.reshape(nd.arange(9), shape = (1, 1, 3, 3))`
`b = nd.reshape(nd.arange(4), shape=(1, 1, 2, 2))`
`c=mx.nd.Deconvolution(data=a, weight=b, kernel=(2,2), num_filter=1, dilate=(2, 2), stride=(2,2))`
`print(c)`
2. result is 
[[[[ 0.  0.  0.  0.  1.  0.  2.]
   [ 0.  0.  0.  0.  0.  0.  0.]
   [ 0.  0.  0.  2.  3.  4.  6.]
   [ 0.  0.  3.  0.  4.  0.  5.]
   [ 6.  0.  9.  8. 12. 10. 15.]
   [ 0.  0.  6.  0.  7.  0.  8.]
   [12.  0. 18. 14. 21. 16. 24.]]]]
<NDArray 1x1x7x7 @cpu(0)>

3. same params in caffe result is:
[[[[  0.   0.   0.   0.   1.   0.   2.]
   [  0.   0.   0.   0.   0.   0.   0.]
   [  0.   0.   5.   0.  11.   0.  11.]
   [  0.   0.   0.   0.   0.   0.   0.]
   [  6.   0.  23.   0.  29.   0.  23.]
   [  0.   0.   0.   0.   0.   0.   0.]
   [ 12.   0.  32.   0.  37.   0.  24.]]]]

4. and caffe prototxt as below：
input_shape {
 dim: 1
 dim: 1
 dim: 3
 dim: 3
}
layer {
  name: "deconv1"
  type: "Deconvolution"
  bottom: "data"
  top: "deconv1"
  convolution_param {
    num_output: 1
    kernel_size: 2
    stride_h: 2
    stride_w: 2
    dilation: 2
    pad_h: 0
    pad_w: 0
    group: 1
  }
}

## What have you tried to solve it?
1.I calculated deconvoluiton manually，result was same with caffe
2.So，I think implemnet of mxnet maybe have bug.Or I misunderstand the behavior of deconvolution?

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this _Need Triage_. Someone familiar with Deconvolution operator please check if the usage is correct.

**Comment by thomelane** [comment]
See https://github.com/apache/incubator-mxnet/issues/11203.

Seems like a case of the same bug, found with an even simpler example. And difference shown with PyTorch in that case. Could also effect backward pass of convolution.
