### ISSUE TITLE
website install page query string needed for devices

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11634]
Feature request:
With the other install options you get all of the buttons as options for a deep link. Devices doesn't have this.

https://mxnet.incubator.apache.org/install/index.html?platform=Devices&language=Python&processor=CPU

I'd like to have Raspberry Pi and Jetson as options for direct links.

@kpmurali

**Comment by aaronmarkham** [comment]
Also the redirect with the query string gets the URL wrong when using the s3 link from CI builds.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this _Feature Request_

**Comment by kpmurali** [comment]
I will work on this.

**Comment by aaronmarkham** [comment]
This is resolved on the new site.
