### ISSUE TITLE
CI Error: ClosedChannelException

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11644]
```
Remote call on JNLP4-connect connection from ip-172-31-25-206.us-west-2.compute.internal/172.31.25.206:52920 failed. The channel is closing down or has closed down
```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11580/2/pipeline

**Comment by marcoabreu** [comment]
This is a race condition in Jenkins and there's unfortunately not much we can do: https://issues.jenkins-ci.org/browse/JENKINS-49707

We have to wait until they fix it.

**Comment by szha** [comment]
Why close the issue? Shouldn’t we track the problem?

**Comment by marcoabreu** [comment]
Sure,I thought the linked issue is sufficient, but feel free to keep this one here open. Would you mind adding a description and a title?

**Comment by haojin2** [comment]
I encounter another problem with CI with my PR: https://github.com/apache/incubator-mxnet/pull/11631. The build has passed: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11631/8/pipeline, but the status of the PR is not updated.

**Comment by marcoabreu** [comment]
That's a separate issue. Would you mind creating a new issue for this please?

**Comment by haojin2** [comment]
@marcoabreu  #11654

**Comment by szha** [comment]
I haven't seen this issue for a while now. @marcoabreu I'm OK with closing this.
