### ISSUE TITLE
CI Problem: new commits not triggering new builds

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#11655]
## Description
For PR:http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11587/8/pipeline/ after pushing new commit, jenkins is not triggering new build. There are currently build upto 8 for the mentioned PR but there should have been 9 and 10 since pushed two more changes.

## Environment info (Required)
ubuntu 16.04 DLAMI

**Comment by access2rohit** [comment]
Labels: CI

**Comment by haojin2** [comment]
This is a duplicate of #11654.

**Comment by anirudh2290** [comment]
Closing and tracking in #11654.
