### ISSUE TITLE
make docs - lein not found

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11662]
Lein needs to be added to the docs build instructions. 

If you're stuck on this error, do this:

```
wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
chmod 775 lein
sudo cp lein /usr/local/bin
```
Or some directory that is in your `$PATH`. Then re-run, and you should be good to go.

I'll submit a PR to add this to the instructions.

**Comment by aaronmarkham** [comment]
I'm going to wait until this PR is merged: https://github.com/apache/incubator-mxnet/pull/11590
Then I can use the installation script I made for the Ubuntu deps as a base rather than starting from scratch.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this _Build_, _Documentation_
