### ISSUE TITLE
test_loss.test_bce_loss has fixed seed that can mask flakiness

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11691]
The unit test in title have been using fixed seed to mask flakiness. Suggested action:
1. Evaluate whether the test is flaky without fixed seed. If not, remove seed. Else move to 2
2. If test is flaky, determine whether it's an actual uncaught edge case. If so, fix the operator. Else move to 3
3. If numerical instability is inevitable, adjust tolerance level appropriately.

**Comment by apeforest** [comment]
Thanks for filing this issue. We will investigate this Flaky test

**Comment by lanking520** [comment]
Able to reproduce with `MXNET_TEST_SEED=1444380817`

**Comment by lanking520** [comment]
After introducing `atol` and `rtol`, issues are gone, will wrap it up and send a PR

**Comment by lanking520** [comment]
After adding `Xavier` initializer, problem solved:
```
python tools/flakiness_checker.py -n 10000 test_operator_gpu.test_ce_loss
INFO:root:Testing: /home/ubuntu/incubator-mxnet/tests/python/gpu/test_operator_gpu.py:test_ce_loss
INFO:root:No test seed provided, using random seed
/usr/local/lib/python3.5/dist-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=449509033 to reproduce.
test_operator_gpu.test_ce_loss ... ok

----------------------------------------------------------------------
Ran 1 test in 9277.876s

OK
INFO:root:Nosetests terminated with exit code 0
```
