### ISSUE TITLE
test_module.test_factorization_machine_module has fixed seed that can mask flakiness

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11704]
The unit test in title have been using fixed seed to mask flakiness. Suggested action:
1. Evaluate whether the test is flaky without fixed seed. If not, remove seed. Else move to 2
2. If test is flaky, determine whether it's an actual uncaught edge case. If so, fix the operator. Else move to 3
3. If numerical instability is inevitable, adjust tolerance level appropriately.

**Comment by apeforest** [comment]
Thanks for filing this issue. We will investigate this Flaky test

**Comment by apeforest** [comment]
I could reproduce the issue using random seed 1306649843.  The issue is accuracy mismatch

**Comment by apeforest** [comment]
Assigned JIRA ticket: https://issues.apache.org/jira/browse/MXNET-770

**Comment by apeforest** [comment]
Fixed unit test and added training test. PR: https://github.com/apache/incubator-mxnet/pull/12023

**Comment by apeforest** [comment]
@szha PR is merged. Please verify and close this issue. Thanks!

**Comment by haojin2** [comment]
@sandeep-krishnamurthy Related PR is merged, should be good to close.
