### ISSUE TITLE
Problems of bucking iterator in speech example

### ISSUE THREAD

**Issue by AprilSongRits** [apache/incubator-mxnet#11743]
The bucking iterator cannot read all the training data, which will cause the evaluation being significantly different.

**Comment by apeforest** [comment]
@AprilSongRits Can you give more details of this problem. Like a reproducible simple example will be great. Thanks!

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@AprilSongRits Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment]
@mxnet-label-bot add [suggest-closed]

**Comment by cjolivier01** [comment]
closing until requester reopens
