### ISSUE TITLE
Update doc for activation symbol

### ISSUE THREAD

**Issue by azai91** [apache/incubator-mxnet#11752]
## Description
https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.Activation

https://www.dropbox.com/s/w9krenuwsc9z9uo/Screenshot%202018-07-13%2015.53.00.png?dl=0

The simple_forward method says it accepts a kwargs called `act_data`. However, it is passing the parameter to the Activation class which requires a kwargs called `data`.

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1. 
2.

**Comment by azai91** [comment]
@aaronmarkham

**Comment by ThomasDelteil** [comment]
@azai91 can you point to the documentation that says that the `simple_forward` function accepts `act_data` as an argument?

Current docs as I see it is:

```
    A simple forward function for a symbol.

    Primarily used in doctest to test the functionality of a symbol.
    Takes NumPy arrays as inputs and outputs are also converted to NumPy arrays.

    Parameters
    ----------
    ctx : Context
        If ``None``, will take the default context.
    inputs : keyword arguments
        Mapping each input name to a NumPy array.

    Returns
    -------
    The result as a numpy array. Multiple results will
    be returned as a list of NumPy arrays.
```

I think you are confused by the `act_data` argument in the `Activation` example. This is a key/value argument that is used to bind the symbol with the data. Because in the example the Activation symbol is named `act`, the default input symbol should be named `act_data`

For example this would work too:

```
    op = Activation(data=mx.sym.var('data0'), act_type=act_type, name='act')
    y = test_utils.simple_forward(op, data0=x)
```

@sandeep-krishnamurthy can you close please?
