### ISSUE TITLE
[MXNET-677] int8 quantization does not work on toy mnist dataset 

### ISSUE THREAD

**Issue by OneRaynyDay** [apache/incubator-mxnet#11756]
[Link to JIRA ticket issue](https://issues.apache.org/jira/projects/MXNET/issues/MXNET-677?filter=allopenissues)

The reproducible repository is [linked here.](https://github.com/OneRaynyDay/mxnet-quantization-bug)

## Description

Currently, airbnb is using the quantization extensions of mxnet to boost inference time on several convolutional neural network models. However, it has been difficult to achieve. The most complicated bugs lie in the intersection between the python and C++ interface, like the ones that crash jupyter kernels and are hard to run pdb on.

Airbnb currently extensively uses gluon models and are not planning to move to Module models any time soon for training, but it seems that creating a quantized Module model solely for inference is useful. Please refer to the repository for a minimum reproducible example.

## Error & Stacktrace

```
qsym, qarg_params, qaux_params = mx.contrib.quantization.quantize_model(
        sym=model._symbol, 
        arg_params=model._arg_params, 
        aux_params=model._aux_params,
        excluded_sym_names=['hybridsequential0_conv0_fwd',
                           'hybridsequential0_dense0_fwd',
                           'hybridsequential0_dense1_fwd',
                          ],
        ctx=ctx, 
        calib_data=data_iter,
    )
qmodel = mx.mod.Module(symbol = qsym, context = mx.cpu())
qmodel.bind(for_training=False,
           data_shapes = data_iter.provide_data, 
           label_shapes = data_iter.provide_label)
qmodel.set_params(qarg_params, qaux_params)
qmodel.predict(data_iter)
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
~/anaconda3/envs/idp3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/anaconda3/envs/idp3/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/anaconda3/envs/idp3/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/anaconda3/envs/idp3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py in __repr__(self)
    187         """Returns a string representation of the array."""
    188         shape_info = 'x'.join(['%d' % x for x in self.shape])
--> 189         return '\n%s\n<%s %s @%s>' % (str(self.asnumpy()),
    190                                       self.__class__.__name__,
    191                                       shape_info, self.context)

~/anaconda3/envs/idp3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py in asnumpy(self)
   1908             self.handle,
   1909             data.ctypes.data_as(ctypes.c_void_p),
-> 1910             ctypes.c_size_t(data.size)))
   1911         return data
   1912 

~/anaconda3/envs/idp3/lib/python3.6/site-packages/mxnet/base.py in check_call(ret)
    208     """
    209     if ret != 0:
--> 210         raise MXNetError(py_str(_LIB.MXGetLastError()))
    211 
    212 

MXNetError: [19:42:27] src/operator/quantization/mkldnn/mkldnn_quantized_conv.cc:41: Check failed: in_data[0].dtype() == mshadow::kUint8 (5 vs. 3) mkldnn_quantized_conv op only supports uint8 as input type

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x0000000109ffd6d4 libmxnet.so + 26324
[bt] (1) 1   libmxnet.so                         0x0000000109ffd48f libmxnet.so + 25743
[bt] (2) 2   libmxnet.so                         0x000000010a032093 libmxnet.so + 241811
[bt] (3) 3   libmxnet.so                         0x000000010b14f745 MXNDListFree + 289605
[bt] (4) 4   libmxnet.so                         0x000000010b11b3fc MXNDListFree + 75772
[bt] (5) 5   libmxnet.so                         0x000000010b11e931 MXNDListFree + 89393
[bt] (6) 6   libmxnet.so                         0x000000010b11e847 MXNDListFree + 89159
[bt] (7) 7   libmxnet.so                         0x000000010b11c175 MXNDListFree + 79221
[bt] (8) 8   libsystem_pthread.dylib             0x00000001018eb661 _pthread_body + 340
[bt] (9) 9   libsystem_pthread.dylib             0x00000001018eb50d _pthread_body + 0
```

## Environment info (Required)

```
quantization-bug git/master
(idp3) ❯ pip freeze | grep mxnet
keras-mxnet==2.2.0
mxnet-mkl==1.3.0b20180711

quantization-bug git/master
(idp3) ❯ uname -a
Darwin ray-zhangs-mbp.airgc.net 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```

**Comment by reminisce** [comment]
@pengzhao-intel

**Comment by OneRaynyDay** [comment]
Just an update: When I install `mxnet==1.3.0b20180715`, it throws the following error upon `qmodel.bind(...)` in the notebook, as in it segfaults before even the `predict()`.

```
[09:39:42] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_pooling
[09:39:42] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[09:39:42] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_pooling

Segmentation fault: 11

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010a0fbeb4 libmxnet.so + 20148
[bt] (1) 1   libmxnet.so                         0x000000010b751b56 MXTVMBridge + 3956742
[bt] (2) 2   libsystem_platform.dylib            0x00000001018d9f5a _sigtramp + 26
[bt] (3) 3   ???                                 0x0000000000000006 0x0 + 6
[bt] (4) 4   libmxnet.so                         0x000000010b2055dc MXNDListFree + 147580
[bt] (5) 5   libmxnet.so                         0x000000010b2114b3 MXNDListFree + 196435
[bt] (6) 6   libmxnet.so                         0x000000010b21cc04 MXNDListFree + 243364
[bt] (7) 7   libmxnet.so                         0x000000010b221dba MXNDListFree + 264282
[bt] (8) 8   libmxnet.so                         0x000000010b1ac0b0 MXExecutorSimpleBind + 8656
[bt] (9) 9   _ctypes.cpython-36m-darwin.so       0x0000000107e76d17 ffi_call_unix64 + 79
```

**Comment by OneRaynyDay** [comment]
@reminisce Hi, is there a slack channel I can join for discussion about this bug? I can't seem to get quantization working at all. (Even the examples segfault for me)

**Comment by reminisce** [comment]
@OneRaynyDay From the error message, it seems that you quantized the model using a version of MXNet, but ran inference with the quantized model using an older version than that. Were you able to run the example here:
https://github.com/apache/incubator-mxnet/tree/master/example/quantization

It seems that an invitation for you to join the slack channel has been sent out. Let us know if you don't have it. Thanks.

**Comment by OneRaynyDay** [comment]
Hi @reminisce , thanks for the response. I have not received a slack invitation to `ray.zhang@airbnb.com`. Was it to another e-mail address?

**Comment by OneRaynyDay** [comment]
Thank you. I have also found out the reason for the failure, and it is not related to CPU quantization. We should discuss more about this in the slack channel. It is a very strange issue.

**Comment by pengzhao-intel** [comment]
@OneRaynyDay we have successfully run MNIST in our local with the quantization flow.
@xinyu-intel will help to take a look for your scripts.

**Comment by access2rohit** [comment]
@xinyu-intel: do you need help addressing this issue ?

**Comment by bettyeats** [comment]
hi @OneRaynyDay have you resolved your problem? I have the same error:

[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_conv
[17:16:31] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_pooling

Segmentation fault: 11


Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x00000001013236b4 libmxnet.so + 18100
[bt] (1) 1   libmxnet.so                         0x00000001029b4136 MXTVMBridge + 4014070
[bt] (2) 2   libsystem_platform.dylib            0x00007fff5822ff5a _sigtramp + 26
[bt] (3) 3   ???                                 0x00000000a242980c 0x0 + 2722273292
[bt] (4) 4   libmxnet.so                         0x0000000102459bcc MXNDListFree + 147580
[bt] (5) 5   libmxnet.so                         0x0000000102465aa3 MXNDListFree + 196435
[bt] (6) 6   libmxnet.so                         0x00000001024711f4 MXNDListFree + 243364
[bt] (7) 7   libmxnet.so                         0x00000001024763aa MXNDListFree + 264282
[bt] (8) 8   libmxnet.so                         0x00000001024006a0 MXExecutorSimpleBind + 8656
[bt] (9) 9   libffi.6.dylib                      0x00000001007bc884 ffi_call_unix64 + 76

I ran in OSX, and ctx=cpu.

**Comment by OneRaynyDay** [comment]
@bettyeats Hi, it is because you're using `ctx=cpu()`. Please refer to the feature request link for more information. Currently there is no workaround. You need `ctx=gpu()`

**Comment by reminisce** [comment]
For CPU, you can build with MKLDNN. Native CPU quantization is not implemented.

**Comment by ThomasDelteil** [comment]
@xinyu-intel @PatricZhao is there work to support `int8` type in MKLDNN ? Currently it only supports `uint8`

```text
MXNetError: [21:24:54] src/operator/quantization/mkldnn/mkldnn_quantized_conv.cc:41: Check failed: in_data[0].dtype() == mshadow::kUint8 (5 vs. 3) : mkldnn_quantized_conv op only supports uint8 as input type
```

**Comment by pengzhao-intel** [comment]
@ThomasDelteil the fused version of convolution can work with INT8 [in here](https://github.com/apache/incubator-mxnet/blob/d32a3da7a7d8291cf383d5cf7b34533733317cd6/src/operator/subgraph/mkldnn/mkldnn_conv.cc#L671)

Please try to run models with https://github.com/apache/incubator-mxnet/blob/master/example/quantization/imagenet_gen_qsym_mkldnn.py

**Comment by xinyu-intel** [comment]
@ThomasDelteil add this line `sym = sym.get_backend_symbol('MKLDNN_QUANTIZE')` to enable subgraph fusion before using `quantize_net` api.

**Comment by eric-haibin-lin** [comment]
Closing this issue for now. Please feel free to reopen if you come across this again
