### ISSUE TITLE
How to install the latest version of mxnet?

### ISSUE THREAD

**Issue by y12uc231** [apache/incubator-mxnet#11783]
how to install the latest version of mxnet with repo? I think there have been some changes which are not reflected in the latest version of pip.

**Comment by TaoLv** [comment]
You can follow this page and choose 'master' and 'build from source': https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Python&processor=CPU

**Comment by haojin2** [comment]
@y12uc231 You can also install the nightly build version through "pip install --pre mxnet" or "pip install --pre mxnet-cu90" if you have CUDA installed.

**Comment by szha** [comment]
Note that the nightly build is provided to mxnet developers only, as convenience infrastructure. They are not official mxnet releases
