### ISSUE TITLE
Batch_dot does not support FP16 well

### ISSUE THREAD

**Issue by szhengac** [apache/incubator-mxnet#11796]
The `batch_dot` does not support FP16 well and can make training slower compared to using FP32. This is tested using [Transformer](https://github.com/dmlc/gluon-nlp/blob/master/scripts/nmt/train_transformer.py) model in Gluonnlp. This feature has been added in a [NVIDIA mxnet](https://docs.nvidia.com/deeplearning/dgx/mxnet-release-notes/rel_17.11.html#rel_17.11). So I think it is good to enable this in the master.

**Comment by ptrendx** [comment]
@DickJC123

**Comment by eric-haibin-lin** [comment]
I'm adding cublas strided gemm calls in mshadow https://github.com/dmlc/mshadow/pull/353

**Comment by eric-haibin-lin** [comment]
merged

**Comment by eric-haibin-lin** [comment]
Sorry about the revert. I found that it is better to implement fp16 ops in mxnet instead of in mshadow, since there are built in functionality to detect/enable tensorcore. I can make a PR in maybe two or three days. @sbodenstein are you using symbol or gluon to train transformer?

**Comment by sbodenstein** [comment]
@eric-haibin-lin: we are using symbol to train transformer. That would be great to reenable this as soon as possible.

Is there any reason to not expose `linalg_gemm` and `linalg_gemm2` `float16`-support on GPU as well?

**Comment by sbodenstein** [comment]
@eric-haibin-lin: any updates about this?

**Comment by eric-haibin-lin** [comment]
Added in https://github.com/apache/incubator-mxnet/pull/13716
