### ISSUE TITLE
imagenet-11k-place365-ch 

### ISSUE THREAD

**Issue by kli-nlpr** [apache/incubator-mxnet#11812]
Where can I find the label names of imagenet-11k-place365-ch  models?
http://data.mxnet.io/models/imagenet-11k-place365-ch/ 
Thank you very much

**Comment by nswamy** [comment]
Please ask your questions on https://discuss.mxnet.io/, We use GitHub Issues for bugs and Feature Requests.

**Comment by nswamy** [comment]
This might be the one, but I am not sure..please do ask on discuss.mxnet.io
http://data.mxnet.io/models/imagenet-11k/synset.txt

**Comment by back2yes** [comment]
@nswamy No, this is not the corresponding one.

The desired classes num is 11586, while the imagenet-11k/synset.txt has 11221 classes
