### ISSUE TITLE
Duplication of Operators for sampling from random distributions

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#11811]
The operators defined in ``sample_op.cc`` and ``multisample_op.cc`` are seemingly performing the same tasks. Both these files define the following operators respectively
```
sample_op.cc
-----------
random_uniform
random_normal
random_gamma
random_exponential
random_poisson
random_negative_binomial
random_generalized_negative_binomial
```
```
multisample_op.cc
----------
sample_uniform
sample_normal
sample_gamma
sample_exponential
sample_poisson
sample_negative_binomial
sample_generalized_negative_binomial
```

The only difference that I can glean from the documentation is that operators in ``multisample_op.cc`` performs concurrent sampling from multiple distributions, but the behavior of the operators is not different.

Is ``sample_op.cc`` being retained for legacy reasons or backward compatibility? Can it be deprecated or EOLed? Correct me if I am wrong here.

@szha @zheng-da @eric-haibin-lin @hetong007

**Comment by eric-haibin-lin** [comment]
I think the recommended APIs are listed in https://mxnet.incubator.apache.org/versions/master/api/python/ndarray/random.html#random-distribution-generator 
Why are you looking into this? are you trying to add a new one?

**Comment by nswamy** [comment]
@anirudhacharya please bring up this question on the dev list for a wider audience to know about this.

**Comment by anirudhacharya** [comment]
@nswamy Sure I can bring this up on the dev list but I would prefer to keep this issue open. Can you please reopen it?

**Comment by eric-haibin-lin** [comment]
answered in https://lists.apache.org/thread.html/1e80983b9e78b88dc5e5d83edadc0f86b9e368702b954ce05d212e3c@%3Cdev.mxnet.apache.org%3E
