### ISSUE TITLE
Bug: quantization Layers seg fault instead of displaying proper error message

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#11846]
## Description
quantized FC, pooling and convolution layers on native cpu w/o mkl throws segfault, instead of displaying error that it us not supported

## Environment info (Required)
DLAMI (ubuntu16.04) p2.8xlarge

Package used (Python/R/Scala/Julia):
python 3.6

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)
mxnet master branch
make -j USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 DEBUG=0

## Error Message:
Error:
[17:57:00] src/executor/attach_op_execs_pass.cc:336: Neither FCompute nor FComputeEx registered _contrib_quantized_fully_connected
Segmentation fault (core dumped)

## Minimum reproducible example
Use Code in Python Natebook: 
https://github.com/OneRaynyDay/mxnet-quantization-bug/blob/master/Module_Quantization.ipynb

**Comment by CodePlay2016** [comment]
I met a similar situation

**Comment by access2rohit** [comment]
JIRA link: https://issues.apache.org/jira/browse/MXNET-693

**Comment by access2rohit** [comment]
@mxnet-label-bot add [operator]

**Comment by eric-haibin-lin** [comment]
closing this for now since mxnet by default is built with mkldnn
