### ISSUE TITLE
we need to update the doc of scatter_nd and gather_nd

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#11867]
[scatter_nd](http://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.scatter_nd) and [gather_nd](http://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.gather_nd) in MXNet are similar to the ones in TensorFlow. But the current documentation is difficult to understand. We need to update the document.

**Comment by haojin2** [comment]
Working on this.

**Comment by haojin2** [comment]
@zheng-da Fix is in #11918

**Comment by sandeep-krishnamurthy** [comment]
Resolved by @haojin2

**Comment by sandeep-krishnamurthy** [comment]
Reopening as we have few more pending updates - @haojin2

**Comment by piyushghai** [comment]
@haojin2 Were the pending updates merged for resolving the doc issues here ?

**Comment by sad-** [comment]
echoing @piyushghai are there still pending updates for this? @sandeep-krishnamurthy @haojin2 can this be closed now?

**Comment by ThomasDelteil** [comment]
closing for now, please reopen with details of what needs to be updated if necessary, thanks
