### ISSUE TITLE
error when add RandomCropAug into aug_list during initialization of ImageIter

### ISSUE THREAD

**Issue by knwng** [apache/incubator-mxnet#11870]
Hi, I think there's a bug when you want to apply random cropping in ImageIter in python as follows:

> mx.image.ImageIter(batch_size=32, data_shape=(3, 244, 244), aug_list=[mx.image.RandomCropAug(128, 128)], ...)

since the shape of each batch is set in advance(image/image.py, line 1186-1187):
> batch_data = nd.empty((batch_size, c, h, w))
> batch_label = nd.empty(self.provide_label[0][1])

in image/image.py, line 1201, the processed image is directly assigned back to batch_data:
> batch_data[i] = self.postprocess_data(data)

Since the shapes of batch_data and the cropped image are different if you apply random cropping, the cropped image cannot be broadcasted and will raise an error:
> ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (3, 128, 128) and requested shape (3, 244, 244)

I think we can check if RandomCropAug or RandomSizedCropAug are in aug_list first, if so, the shape of batch_data should be set to the size of cropped image and I'm working on it.

**Comment by knwng** [comment]
the ForceResizeAug augmenter also cannot be used directly in ImageIter, since it'll also change the size of image

**Comment by sandeep-krishnamurthy** [comment]
@vandanavk

**Comment by knwng** [comment]
I think it's my misunderstanding of augmenter api. the data_shape indicates the final input data shape which should be satisfied by using various augmenters. close issue.
