### ISSUE TITLE
what is the accuray of imagenet-11k--place365-challenge mean?

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#11881]
I read the doc here:
https://github.com/apache/incubator-mxnet/tree/master/example/image-classification#imagenet-11k--place365-challenge

Is the model accuray is caculated with the imaget11k and place365 365 classes? Or only calculated with imaget11k classes?

**Comment by sandeep-krishnamurthy** [comment]
Hi @universewill For questions, you can use MXNet discuss forum - https://discuss.mxnet.io/ where there are more people who can answer your query. We want to use Github issues mainly for bugs and feature request.

Closing the issue here. Please reopen if you are finding any issues.
