### ISSUE TITLE
How to compile the old version, like 0.7.0, from source file?

### ISSUE THREAD

**Issue by iamweiweishi** [apache/incubator-mxnet#11880]
I downloaded the source file incubator-mxnet-0.7.0.zip from https://github.com/apache/incubator-mxnet/tags?after=v0.10.0. 
But the source file is not complete. Some key files are missing. And some errors come up:
/root/incubator-mxnet/dmlc-core/make/dmlc.mk: No such file or directory

The 'git clone -recursive ' command downloads the latest version mxnet.
So, any suggestions?

**Comment by sandeep-krishnamurthy** [comment]
Hello @iamweiweishi  - I am curious to understand why such an old version of MXNet is required and are there any issues you are facing with latest version?

After clone the latest, you can get the commit hash of v0.7 that you are interested in and do git reset hard to go back to that commit. If you don't find submodules, please do the same for all submodules. Note that currently all submodules are moved into 3rd party directory.

**Comment by rahul003** [comment]
With the old version, I think you will need to do 'git submodule update --recursive --init' to get all the submodules as they are then

**Comment by thomelane** [comment]
@iamweiweishi @rahul003 yes, this works for me too for building MXNet at a specific commit in the past:

```
git clone --recursive https://github.com/apache/incubator-mxnet
cd incubator-mxnet/
git checkout [YOUR_COMMIT_SHA_HERE]
git submodule update --recursive --init
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
```

@sandeep-krishnamurthy should be good to close, thanks!
