### ISSUE TITLE
non-deterministic backward of scatter_nd 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11899]
For [scatter_nd](https://mxnet.incubator.apache.org/versions/master/api/python/ndarray/ndarray.html?highlight=logis#mxnet.ndarray.scatter_nd), it uses atomic add on GPU, thus
```
If the indices have duplicates, the result will be non-deterministic and the gradient of scatter_nd will not be correct!!
```
This should be fixed.

**Comment by haojin2** [comment]
I can probably take a look at this as I've tackled the same problem with `take` operator.

**Comment by piiswrong** [comment]
Why do we need to this to be deterministic? Is there a use case?
Note that we don't promise determinism for most of the operators.

**Comment by eric-haibin-lin** [comment]
If MXNet dosen't promise nondeterminism, then any model using this operator doesn't produce consistent result even if random seed is set. We should try our best to avoid this

**Comment by eric-haibin-lin** [comment]
@sxjscience has such use case and that's why the warning documentation is added.
