### ISSUE TITLE
support 1D and 3D arrays in MKLDNN.

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#11906]
MKLDNN currently only supports 2D and 4D arrays. As @safrooze reported that computation on 1D and 3D arrays is much slower than on 2D and 4D arrays. We can easily accelerate performance by adding a dummy dimension so that the computation can take advantage of MKLDNN. Right now users have to do it manually. We should improve the MKLDNN integration and accelerate 1D and 3D arrays automatically.
@pengzhao-intel @TaoLv

**Comment by TaoLv** [comment]
I think mkldnn already has support for 3D arrays now. You can find the formats definition (ncdhw or nCdhw16c) here: https://github.com/intel/mkl-dnn/blob/master/include/mkldnn_types.h#L134

**Comment by safrooze** [comment]
3D tensors are common in audio signals, e.g. WaveNet. I specifically ran into this issue with WaveNet inference on CPU.

**Comment by TaoLv** [comment]
@safrooze thanks for the information. mkldnn has already support 3D convolution. The input of it may be 5D tensor if we take batch size and channel size into account. I think 1D convolution is still under development for mkldnn. As @zheng-da mentioned, currently we can add a fake dim to turn it into 2D convolution to benefit from mkldnn.
@zheng-da Right, we need spend some effort to integrate mkldnn 3D convolution into mxnet now.

**Comment by safrooze** [comment]
@TaoLv By 3D tensor, I meant something with (batch_size, channels, width), which is a 1D convolution.

**Comment by pengzhao-intel** [comment]
@zheng-da @safrooze  It's on the plan to integrate 1D conv into MXNet soon by @xinyu-intel

**Comment by pengzhao-intel** [comment]
The request features are implemented :)
Closing now. Feel free to reopen if there is another issue.
