### ISSUE TITLE
unfound reference: mx.io.ImageRecordIter

### ISSUE THREAD

**Issue by vivienzou1** [apache/incubator-mxnet#11929]
## Description
after update to the latest version 1.3 mxnet in python 3.6, the IDE catch error as
`' Cannot find reference "ImageRecordIter" in "io.py" `
when I try to 
```bash 
# construct the training image iterator
import mxnet as mx
trainIter = mx.io.ImageRecordIter(
    path_imgrec=config.Train_MX_REC,
    data_shape=(3,224,224)
    batch_size=batchSize,...)
```

## Environment info 
python 3.6
mxnet 1. 3. 0b20 
IDE: latest pycharm community

**Comment by haojin2** [comment]
Was that the exact script you used? Seems like you're missing a comma after
```Python
    data_shape=(3,224,224)
```

**Comment by haojin2** [comment]
BTW the doc for ImageRecordIter is at https://mxnet.incubator.apache.org/api/python/io/io.html?highlight=imagerecorditer#mxnet.io.ImageRecordIter. Docs for all Python APIs can be found at https://mxnet.incubator.apache.org/api/python/index.html.

**Comment by vivienzou1** [comment]
fix it by simply restarting pycharm.... thanks guys
