### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by gulinlin** [apache/incubator-mxnet#11924]
Hey,When I compiled, something went wrong.

Makefile:168: "USE_LAPACK disabled because libraries were not found"
Makefile:276: WARNING: Significant performance increases can be achieved by installing and enabling gperftools or jemalloc development packages
cd /mnt/data/gulinlin/Rpackages/incubator-mxnet/3rdparty/dmlc-core; make libdmlc.a USE_SSE=1 config=/mnt/data/gulinlin/Rpackages/incubator-mxnet/config.mk; cd /mnt/data/gulinlin/Rpackages/incubator-mxnet
make[1]: Entering directory `/mnt/data/gulinlin/Rpackages/incubator-mxnet/3rdparty/dmlc-core'
make[1]: `libdmlc.a' is up to date.
make[1]: Leaving directory `/mnt/data/gulinlin/Rpackages/incubator-mxnet/3rdparty/dmlc-core'

What should I do? Any help would be appreciated.

**Comment by lanking520** [comment]
HI @gulinlin, thanks for your question. what platform are you using currently to build the package? Have you tried to make -j $(nprocs) before you make the R package?

@anirudhacharya Can you also take a look from here? 

@mxnet-email-bot please label : R, build to this issue

**Comment by anirudhacharya** [comment]
@gulinlin can you please provide more information like what environment you are running it on? and provide a steps to reproduce the error.

@mxnet-label-bot please label : [Pending Requester Info]

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please close this due to lack of activity.
