### ISSUE TITLE
Substitute of torch.Tensor.data_ptr() 

### ISSUE THREAD

**Issue by y12uc231** [apache/incubator-mxnet#11927]
Is there any work around to get the address of the first element of the NDarray?

I tried id() but it doesnt give the same address,

**Comment by wkcn** [comment]
Using `MXNDArrayGetData` to get the first element of the NDArray.

Notice: You should call `wait_to_read` before reading a NDArray and call `wait_to_write` before writing a NDArray.

There is no  `wait_to_write` in NDArray, so

`mx.nd.NDArray.wait_to_write = lambda self : _LIB.MXNDArrayWaitToWrite(self.handle)`

Example:

https://github.com/wkcn/MobulaOP/blob/master/mobula_op/glue/mx.py#L28

**Comment by Roshrini** [comment]
@y12uc231 Thanks for trying it out. 
For how-to and usability questions, you can use MXNet discuss forum - https://discuss.mxnet.io/ to involve wider community.
We want to use Github issues mainly for bugs and feature request. Feel free to reopen if closed in error. 

@sandeep-krishnamurthy Can you please label- Question and close this issue?

**Comment by y12uc231** [comment]
Thanks @Roshrini for the suggestion, didnt know about the discussion forum. Apologies for the trouble .
