### ISSUE TITLE
Not Found Links in the doc of MXNet : Training with multiple GPUs

### ISSUE THREAD

**Issue by y12uc231** [apache/incubator-mxnet#11932]
Doc Link : https://mxnet.incubator.apache.org/versions/master/faq/model_parallel_lstm.html

There are some hyperlinks that dont work here :- 
https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm.py
https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm.py#L171
https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm_ptb.py#L97-L102

Will appreciate if you fix these.

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy Could you please add label: Doc, Python

**Comment by aaronmarkham** [comment]
@liyujiel - in #11435 you deleted the file: /example/model-parallel/lstm/lstm.py
Can you point to the new resource and/or update the FAQ?

**Comment by liyujiel** [comment]
@aaronmarkham @y12uc231  I removed old LSTM examples because it not work during logic problem. We should create a new example for parallel LSTM.

**Comment by aaronmarkham** [comment]
So does that mean that whole FAQ should be taken offline? Or just reworded to not include an example?

**Comment by liyujiel** [comment]
I vote for reworded. People can still check and use it.
