### ISSUE TITLE
[Automated Publish] Help needed to run restricted CI

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#11933]
As discussed in [this Thread](https://lists.apache.org/thread.html/464712f0136fb51916ca9f1b702b99847e108dbdbd0b6a2b73fc91f1@%3Cdev.mxnet.apache.org%3E). I am facing the issues to automate publish the Scala issues. This issue address the third point of my problem: How to run/test the restricted CI. 

Thanks to @marcoabreu for the solution provided [here](https://cwiki.apache.org/confluence/display/MXNET/Restricted+jobs+and+nodes).

Let's keep this issue open until we have find a good way to do automated publish on it.

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy Could you please label: CI, Scala

**Comment by piyushghai** [comment]
@lanking520 Have we been able to figure out a good automated way to publish ?

**Comment by lanking520** [comment]
Since @zachgk is working on this, it is good to close now. @piyushghai thanks for your remind!
