### ISSUE TITLE
Distributed and local train have different results when training a wide-deep network. 

### ISSUE THREAD

**Issue by jiajinyu** [apache/incubator-mxnet#11962]
## Description
We see small but noticeable difference of outputs when we trained a wide-deep network. The difference only happened when we have both deep and wide parts of the network. We only used one worker and have the local command as  `OMP_NUM_THREADS=4 MXNET_CPU_WORKER_NTHREADS=24 python train.py some_other_params` and  distributed command as `OMP_NUM_THREADS=4 MXNET_CPU_WORKER_NTHREADS=24  incubator-mxnet/tools/launch.py  -n 1 --launcher=local python 
train.py some_other_params --kvstore dist_async`

To find out where the diff occurs, we have code like this to log the values/states
```
suffix = 'single' if args.kvstore is None else args.kvstore
mod.save_params('module-train-checkpoint-{}-{}.params'.format(suffix, nbatch))
mx.nd.save('batch_{}_{}_inputs.ndarray'.format(nbatch, suffix), batch.data)
mod.forward(batch)
outputs = mod.get_outputs()[0]
mx.nd.save('batch_{}_{}_outputs.ndarray'.format(nbatch, suffix), outputs)
```
**What we see is that both params and inputs are the same**, but the outputs from distributed and local train are different, which is really strange to me.

May I ask how to debug and check from here? Thanks.

P.S. This doesn't occur in the wide deep model in the MXNet example

**Comment by nswamy** [comment]
@jiajinyu Could you please provide a minimum reproducible code?

**Comment by jiajinyu** [comment]
@nswamy thanks for working on it. The whole program is mixed with our custom logic like new data parser etc. so it is very hard to provide a minimum  reproducible code. 

All I am asking is some suggestions from the community on how to further debug the issue. For an example, what states/variables of which class I should check to find out the root cause of the problem.

**Comment by vrakesh** [comment]
@jiajinyu Have you tried kvstore dist_syn?, and when you say difference how much of a difference do you observe? 

If you can share a reproducible example it would be great.

**Comment by piyushghai** [comment]
@jiajinyu Can you try @vrakesh's suggestions and let us know if you still see different/inconsistent outputs ?

**Comment by lanking520** [comment]
@jiajinyu Close this issue due to lack of response. Please feel free to reopen it if problem persist.
