### ISSUE TITLE
Model inference outputs not matching across MXNet versions using save_params and load_params

### ISSUE THREAD

**Issue by piyushghai** [apache/incubator-mxnet#11961]
## Description
Model inference outputs not matching when model is saved on MXNet v1.0.0 and the same model is loaded on MXNet v1.3.0 (built from latest master branch). 
The error was observed in the CI run for Model Backwards Compatibility Check and is available here  : http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-backwards-compatibility-checker/detail/restricted-backwards-compatibility-checker/1/pipeline/ 

## Error Message:
Items are not equal:
```Traceback (most recent call last):
  File "model_backwards_compat_inference.py", line 135, in <module>
    test_lenet_gluon_load_params_api()
  File "model_backwards_compat_inference.py", line 72, in test_lenet_gluon_load_params_api
    assert_almost_equal(old_inference_results.asnumpy(), output.asnumpy())
  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 1.969787 exceeds tolerance rtol=0.000010, atol=0.000000.  Location of maximum error:(5, 0), a=0.003014, b=0.003014
 a: array([[ 0.01743407, -0.30903903],
       [ 0.08352755, -0.365019  ],
       [ 0.06324662, -0.4323489 ],...
 b: array([[ 0.01743408, -0.3090391 ],
       [ 0.08352771, -0.365019  ],
       [ 0.06324662, -0.4323488 ],...
```

## Minimum reproducible example
Perform the training and save the model on MXNet 1.0.0.
Model Definition:
```
class Net(gluon.Block):
    def __init__(self, **kwargs):
        super(Net, self).__init__(**kwargs)
        with self.name_scope():
            # layers created in name_scope will inherit name space
            # from parent layer.
            self.conv1 = nn.Conv2D(20, kernel_size=(5, 5))
            self.pool1 = nn.MaxPool2D(pool_size=(2, 2), strides=(2, 2))
            self.conv2 = nn.Conv2D(50, kernel_size=(5, 5))
            self.pool2 = nn.MaxPool2D(pool_size=(2, 2), strides=(2, 2))
            self.fc1 = nn.Dense(500)
            self.fc2 = nn.Dense(2)

    def forward(self, x):
        x = self.pool1(F.tanh(self.conv1(x)))
        x = self.pool2(F.tanh(self.conv2(x)))
        # 0 means copy over size from corresponding dimension.
        # -1 means infer size from the rest of dimensions.
        x = x.reshape((0, -1))
        x = F.tanh(self.fc1(x))
        x = F.tanh(self.fc2(x))
        return x

```

Training code snippet : 
```
def train_lenet_gluon_save_params_api():
    model_name = 'lenet_gluon_save_params_api'
    create_model_folder(model_name)
    logging.info('Saving files for model %s' % model_name)
    net = Net()
    weights = mx.initializer.Xavier(magnitude=2.57)
    net.initialize(weights, ctx=[mx.cpu(0)])
    # Prepare data

    test_data = mx.nd.array(np.random.uniform(-1, 1, size=(20, 1, 30, 30)))
    output = net(test_data)
    # print (y)

    mx.nd.save(os.path.join(get_model_path(model_name), ''.join([model_name, '-data'])), {'data': test_data})
    save_inference_results(output, model_name)
    net.save_params(os.path.join(get_model_path(model_name), ''.join([model_name, '-params'])))
```

Model Inference to be performed on MXNet built from source from the latest [master](https://github.com/apache/incubator-mxnet)
Inference snippet : 
```
def test_lenet_gluon_load_params_api():
    from mxnet.test_utils import assert_almost_equal
    model_name = 'lenet_gluon_save_params_api'
    logging.info('Performing inference for model/API %s' % model_name)

    data = mx.nd.load(''.join([model_name, '-data']))
    test_data = data['data']
    # Load the model and perform inference
    loaded_model = Net()
    loaded_model.load_params(model_name + '-params')
    output = loaded_model(test_data)
    old_inference_results = mx.nd.load(model_name + '-inference')['inference']
    assert_almost_equal(old_inference_results.asnumpy(), output.asnumpy())
    logging.info('=================================')
    logging.info('Assertion passed for model : %s' % model_name)

```
## Steps to reproduce

1. Run the training on MXNet 1.0.0 ( Installed via pip install mxnet==1.0.0)
2. Run the inference on MXNet 1.3.0 ( Built from source using latest master branch)

This regression is not seen on models trained on v1.1.0 and v1.2.0 with inference performed on v1.3.0

**Comment by lupesko** [comment]
@Roshrini please take a look. This may be another blocker we want to fix for 1.3 release.

**Comment by marcoabreu** [comment]
Reproducible using
```
ci/build.py --platform ubuntu_nightly_cpu /work/runtime_functions.sh nightly_model_backwards_compat_test
```

**Comment by Roshrini** [comment]
@piyushghai Thanks for reporting this issue.
Looking into it.
@sandeep-krishnamurthy Can you please add label: Bug

**Comment by Roshrini** [comment]
I was able to reproduce this issue. Need to debug more to see why its happening.

@szha Have you observed this before or have any idea about why it may be happening?

**Comment by Roshrini** [comment]
Seems like the tolerance level is not set in the mentioned test.. The difference seen in the values is after 7th decimal point which is acceptable.

Output I got:
old_inference_results:
[[-0.22245485 -0.60762584]
 [-0.18619929 -0.4941083 ]
 [-0.2614998  -0.4940931 ]
 [-0.23192915 -0.4607012 ]
 [-0.22917394 -0.4702541 ]
 [-0.03644256 -0.5791895 ]
 [-0.06653443 -0.5936823 ]
 [-0.27859935 -0.55876964]
 [-0.11784768 -0.5614954 ]
 [-0.19131322 -0.65991235]
 [-0.14616844 -0.49545118]
 [-0.19445111 -0.4866081 ]
 [-0.12782529 -0.5715893 ]
 [-0.12283947 -0.59274095]
 [-0.20627439 -0.4948909 ]
 [-0.25454554 -0.5265834 ]
 [-0.16980055 -0.4900279 ]
 [-0.25898194 -0.5047521 ]
 [-0.10910024 -0.60400814]
 [-0.08615021 -0.55358285]]
<NDArray 20x2 @cpu(0)>

new inference result:
[[-0.22245483 -0.6076257 ]
 [-0.18619926 -0.49410838]
 [-0.26149982 -0.49409294]
 [-0.2319293  -0.46070114]
 [-0.2291741  -0.47025427]
 [-0.03644253 -0.5791895 ]
 [-0.06653453 -0.59368235]
 [-0.2785993  -0.5587696 ]
 [-0.11784772 -0.5614954 ]
 [-0.19131319 -0.65991235]
 [-0.14616835 -0.4954512 ]
 [-0.19445102 -0.4866083 ]
 [-0.12782538 -0.5715892 ]
 [-0.12283948 -0.5927409 ]
 [-0.20627451 -0.494891  ]
 [-0.25454548 -0.52658343]
 [-0.1698006  -0.49002784]
 [-0.25898185 -0.50475204]
 [-0.10910021 -0.60400814]
 [-0.08615006 -0.553583  ]]
<NDArray 20x2 @cpu(0)>

@piyushghai will be working on fixing the test with proper tolerance level.

**Comment by piyushghai** [comment]
@Roshrini Created the PR : https://github.com/apache/incubator-mxnet/pull/12006

**Comment by piyushghai** [comment]
Looks like the build has passed now after the PR Merge.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-backwards-compatibility-checker/detail/restricted-backwards-compatibility-checker/5/pipeline

**Comment by piyushghai** [comment]
Closing, since the issue is no longer seen after merging #12006
