### ISSUE TITLE
the speed of C++ predict with libmxnet.so and  libmxment_predcit.so is very different

### ISSUE THREAD

**Issue by sofiawu** [apache/incubator-mxnet#1196]
I build the  mxnet_predict-all.cc in amalgamation and get the libmxnet_predict.so 
I used this lib to predict and find that it is much slower than using libmxnet.so
why?

**Comment by antinucleon** [comment]
mxnet_predict-all.cc is CPU only.

**Comment by sofiawu** [comment]
I run both on cpu

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
