### ISSUE TITLE
scala docs broken links

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12013]
There are some broken links in the scala docs. What's happening is that that links are too long, and the scala linter won't let the files pass lint. So various people, myself included, have attempted a variety of hacks on the URLs to get pass the linter and still be functional. 

Does anyone know the trick for handling these longer URLs - get them to pass lint and not be broken after scaladocs converts the page to html? @lanking520 @andrewfayres ?
  https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/imageclassifier/package.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/object%0A%20%20%20%20detector (HTTP_404)

https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/objectdetector/SSDClassifierExample.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/object%0A%20%20%20%20detector (HTTP_404)

**Comment by Roshrini** [comment]
@nswamy Can you please add label: Doc, Scala

**Comment by lanking520** [comment]
Hi @aaronmarkham do you know why there are `%0A%20%20%20%20` in the middle, I tried to remove then and it directed to the correct folder?

**Comment by aaronmarkham** [comment]
Well, URL shorteners are cool but then there's the matter of control of link and if that resource goes offline. You won't know where it was going.

Those spaces were probably an attempt to make a new line with \ but still have the link work. I tried something different and the link worked in the scaladoc output, but then somehow still shows up broken with the BLC.

**Comment by aaronmarkham** [comment]
This issue has been resolved.
