### ISSUE TITLE
mxnet

### ISSUE THREAD

**Issue by gulinlin** [apache/incubator-mxnet#12032]
> library("mxnet")
Error: package or namespace load failed for 'mxnet':
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/mnt/data/gulinlin/software/NR/lib64/R/library/mxnet/libs/libmxnet.so':
  libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
can you help me?

**Comment by Roshrini** [comment]
@gulinlin Thanks for using MXNet. Can you give more details on the platform you are using? 

@anirudhacharya Seems like R installation issue, Can you take a look?
@sandeep-krishnamurthy Can you please add labels: Installation, R

**Comment by ankkhedia** [comment]
Hi @gulinlin Could you provide more details of the setup/platform you are using like OS, R version, GPU/CPU and we can help you with the issue.

**Comment by lupesko** [comment]
@mxnet-label-bot please add [Pending Requester Info]

**Comment by ankkhedia** [comment]
@nswamy @sandeep-krishnamurthy Could you please close this issue due to inactivity as the issue is not reproducible.

@gulinlin  Please feel free to reopen the issue  case it if closed in error.
