### ISSUE TITLE
Some design proposals from me

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#12033]
hi, guys,
i have performed some design proposals in the confluence space.
see the following links:
KVStore for Distributed Model Parallel FC(nsoftmax)
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89066589

KVStore for Partial FC(nsoftmax) for Large Scale Data Training
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89066594

End2End Fixpoint Finetuning Plug-In
https://cwiki.apache.org/confluence/display/MXNET/End2End+Fixpoint+Finetuning+Plug-In

welcome anybody to join me to finish them into the master branch of mxnet.

thanks.
Ming Zhang

**Comment by Roshrini** [comment]
@starimpact Thanks for sharing these design proposals. Do you mind starting a discussion on apache mxnet @dev list instead?

**Comment by starimpact** [comment]
@Roshrini can you give me the link? i have put them in the `mxnet confluence space` and `dev mail list` and `discuss.mxnet.io`.

**Comment by lupesko** [comment]
@starimpact [https://discuss.mxnet.io/](https://discuss.mxnet.io/) is the right location to post the question. 
You can close this issue, the forum is the best place to get such question answered. Thanks!

@nswamy please label as "Question"
