### ISSUE TITLE
Inception-v3 runs on CPU very slow

### ISSUE THREAD

**Issue by monkeyhen** [apache/incubator-mxnet#1203]
I compiled the newest version of mxnet and use the c++ api to predict image class.
however inception-v3 is unexpected slow.
![image](https://cloud.githubusercontent.com/assets/6859595/12168897/2f08a4c6-b570-11e5-82ed-7d92ac31c162.png)
It costs 6s to process one image.
I am not sure whether it is problem of inception-v3 model or mxnet. The mxnet is compiled only for cpu and use openblas. Could some one give me advices to improve its performance?  thanks a lot

**Comment by winstywang** [comment]
It is common, since Inception V3 is a quite large model.

**Comment by qiaohaijun** [comment]
4 GPU k40m, 70/s. less 20/s each GPU

**Comment by songgc** [comment]
It seems too slow. I can get 6 frames per second on a 6-core cpu with tensorflow.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
