### ISSUE TITLE
reshape_like does not support different input types

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#12048]
There seems no reason for requiring `*_like` functions to have the same input type for both inputs, as only the dimensions of the reference `rhs` are used. For example, this fails:
```
import mxnet as mx
s=mx.sym.reshape_like(lhs=mx.sym.Variable("lhs", dtype="float64"), rhs=mx.sym.Variable("rhs", dtype="float32"))
lhs=mx.nd.ones((1,2,6,6), dtype="float64")
rhs=mx.nd.ones((1,2,6,6), dtype="float32")
s.bind(mx.cpu(), {'lhs': lhs, 'rhs' : rhs})

MXNetError: Error in operator reshape_like0: [15:05:24] src/operator/contrib/../elemwise_op_common.h:133: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node reshape_like0 at 1-th input: expected float64, got float32
```
This means the user needs to cast the `rhs` to the same type as `lhs` just to inherit its shape, which is highly inefficient.

**Comment by sxjscience** [comment]
To revise it, we need to change the FInferType https://github.com/apache/incubator-mxnet/blob/09ae7dfe9cb559dd6fa4996d491ee125e3e0b9e7/src/operator/tensor/elemwise_unary_op_basic.cc#L532-L536

**Comment by szha** [comment]
This is working now.
