### ISSUE TITLE
how does one execute a network with multiple outputs

### ISSUE THREAD

**Issue by timprepscius** [apache/incubator-mxnet#12071]
Using the mxnet-cpp cpp interface to mxnet.

I would like a Conv network with multiple outputs.

```
    Input
      | 
    Conv1
      | 
    Conv2
      |-------------|
      |             |
ApplesConv     OrangesConv
      |             |
    output1      output2
```

I believe I have successfully set this network up.

But I do not understand how to create the executor which will then generate the outputs.
Obviously:

> auto *exe = output.SimpleBind(ctx, args);

will not work, because there is no single output.

Suggestions?  Thanks!!!

**Comment by timprepscius** [comment]
it seems Symbol::Group(std::vector<Symbol>) is the key

**Comment by lanking520** [comment]
Hi @timprepscius looks like the issue you have sent is more likely as a question! Please send this to: https://discuss.mxnet.io/. There will be members pick up this and answer that.

@mxnet-label-bot could you please add [question, c++] to this issue?

**Comment by piyushghai** [comment]
@timprepscius Hope your issue got addressed on the Discussion Forum.
@sandeep-krishnamurthy Can you please close this issue. 
Thanks!
