### ISSUE TITLE
get name from symbol cpp

### ISSUE THREAD

**Issue by timprepscius** [apache/incubator-mxnet#12073]
This is most trivial, and of course a billion ways to work around, however:

Given a symbol:
`auto a = Symbol::Variable("my_super_name") // could be any symbol
`

How do I retrieve the name of the symbol:
`std::cout << a.GetName() << std::endl;
`

Somehow I cannot find the methods to allow this, nor any examples.

**Comment by haojin2** [comment]
There's indeed no such function in Symbol class in cpp-package, a fix in #12076.

**Comment by lanking520** [comment]
@mxnet-label-bot could you please add [feature, c++]

**Comment by haojin2** [comment]
@timprepscius Fix is merged, can you try that out and let me know if you found and problems? Thanks!

**Comment by leleamol** [comment]
@mxnet-lable-bot  [pending-requestor-info]

**Comment by leleamol** [comment]
The fix is merged and there is no update from the requester.
Can this issue be closed?

@mxnet-jenkins @marcoabreu
