### ISSUE TITLE
distribute training on local machines not AWS cloud 

### ISSUE THREAD

**Issue by whu-lyh** [apache/incubator-mxnet#12086]
Hello everyone. recently i meet a problem when i tried to distribute training on different machines each with a 12G 1080ti GPU,  i complied these GPUs with different version of CUDA (some are cuda9.0 , others are cuda8.0).then i meet this error:

Traceback (most recent call last):
  File "train_face.py", line 25, in <module>
    from common import find_mxnet, fit
  File "/tmp/mxnet/common/find_mxnet.py", line 20, in <module>
    import mxnet as mx
  File "/tmp/mxnet/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/tmp/mxnet/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/tmp/mxnet/mxnet/base.py", line 113, in <module>
    _LIB = _load_lib()
  File "/tmp/mxnet/mxnet/base.py", line 105, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory

train scripts are :

export DMLC_INTERFACE=eth0; PS_VERBOSE=1; DMLC_PS_ROOT_PORT=22; ../../tools/launch.py -n 2 -H /home/hosts --sync-dst-dir /tmp/mxnet python2 train_face.py --network resnet-50 --gpus 0 --kv-store dist_sync

so,i'm wander if distribute training must be on the same cuda version.or i miss something before training .thanks a lot. @ry @pluskid

**Comment by rahul003** [comment]
Are you building mxnet from source?

**Comment by whu-lyh** [comment]
both are build from sources command scripts:
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda（-9.0/-8.0） USE_CUDNN=1 USE_DIST_KVSTORE=1

**Comment by rahul003** [comment]
Then you copied libmxnet.so into the current directory, and ran this launch command with sync-dst-dir. I'm guessing that your problem is that you end up trying to use the libmxnet.so which was built on the machine which launched the job because sync-dst-dir synchronizes the current directory to all machines. You could try installing mxnet on each of the machines, using setup.py, then not having libmxnet.so in the current directory and retrying

**Comment by whu-lyh** [comment]
thanks  for your reply. i did copy 'libmxnet.so' to  the current directory,using command:
cp -r ../../python/mxnet .
cp -r ../../lib/libmxnet.so mxnet
i will try to re install mxnet using setup.py. and i 'll update my result timely~~

**Comment by whu-lyh** [comment]
thanks again!

**Comment by lanking520** [comment]
@mxnet-label-bot could you please add [build, installation] to this issue?

**Comment by whu-lyh** [comment]
@rahul003  sry i'v try to using setup.py to install mxnet.but it failed again.and the new training stucked in here:

export PS_VERBOSE=2,DMLC_INTERFACE=eth0,DMLC_PS_ROOT_PORT=22;../../tools/launch.py -n 2 --launcher ssh -H /home/yqs/.ssh/hosts --sync-dst-dir /tmp/mxnet python2 train_face.py --network resnet-50 --gpus 0 --kv-store dist_async
2018-08-10 22:24:01,102 INFO rsync /home/yqs/incubator-mxnet/example/image-classification/ -> 192.168.1.101:/tmp/mxnet
2018-08-10 22:24:01,315 INFO rsync /home/yqs/incubator-mxnet/example/image-classification/ -> 192.168.1.106:/tmp/mxnet
[22:24:01] src/van.cc:289: Bind to role=scheduler, id=1, ip=x.x.x.x, port=9095, is_recovery=0
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[22:24:15] src/van.cc:388: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=x.x.x.x, port=47897, is_recovery=0 } }
[22:24:15] src/van.cc:388: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=x.x.x.x, port=54963, is_recovery=0 } }

and i wait for ten minutes, but there is no response,can u help me solve this new issue? thanks!

**Comment by whu-lyh** [comment]
Anybody here?,The question i asked and described before in five days ago has confused me so many days.  and i still believe it's incompatible to distribute training on different version of CUDA. and i close this issue but hope anybody can tell me if i'm wrong~~

**Comment by whu-lyh** [comment]
@rahul003 @rahul003 @rahul003
