### ISSUE TITLE
crash when using Concat and binding with grad_req = 'add' in backward()

### ISSUE THREAD

**Issue by guoquan** [apache/incubator-mxnet#1208]
Hi,

I try to use a Concat layer in my network and run into some errors.

```
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-3-994bb84ede27> in <module>()
     13 
     14 # it crash here
---> 15 executor.backward()
     16 
     17 outputs = dict(zip(symbol.list_outputs(), executor.outputs))

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor.pyc in backward(self, out_grads)
    117             self.handle,
    118             mx_uint(len(out_grads)),
--> 119             ndarray))
    120 
    121     def set_monitor_callback(self, callback):

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.pyc in check_call(ret)
     74     """
     75     if ret != 0:
---> 76         raise MXNetError(py_str(_LIB.MXGetLastError()))
     77 
     78 def c_str(string):

MXNetError: [11:31:50] src/operator/./concat-inl.h:112: Check failed: (req[i]) == (kWriteTo) 
```

After trying several times, I figure out that it is caused by feeding Variable as (one of) inputs to Concat while binding with grad_req = 'add'.

I use python interface.

The error is raised by src/operator/concat-inl.h#L112 checking the gradient type.

I am not sure why it is checked that way.

When I change to grad_req = 'write' or feeding the output of FC layer as inputs, the error never appears.

I try to repeat the error in a simple way in the following gist: https://gist.github.com/guoquan/959461c8ff2a34fe8ac8

A possible workaround is to split the weight after the concat, but ...

Can anyone help to look into this. Thanks.

**Comment by piiswrong** [comment]
You cannot use add with concat

**Comment by guoquan** [comment]
@piiswrong Is there a "WHY" and will there be a "fix"?

**Comment by tqchen** [comment]
This was a limitation of concat, mainly due to split do not support addto. However, this can be easily changed, by adding support of addto in split function.
https://github.com/dmlc/mxnet/blob/master/src/operator/channel_op_common.h#L65

i.e. Add the requirement parameter, there is a https://github.com/dmlc/mxnet/blob/master/src/operator/operator_common.h#L29 macro to help dispatch the requirement.

change things to like
```
Assign(out[i], req, slice...) 
```
should work.

@guoquan you are more than welcomed to submit a PR to add this support:)

**Comment by guoquan** [comment]
Thanks for the tip @tqchen 

I will look at this. And if I can make it work, I will submit a PR.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
