### ISSUE TITLE
unittest fail on MacOS platform

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#12089]
## Description
The unittest test_gluon_data.py failed on MacOS 10.12

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
Build        : ('default', 'Jun 17 2018 12:26:58')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 18.0
Directory    : /Users/lnyuan/.virtualenvs/mxnet/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.3.0
Directory    : /Users/lnyuan/work/incubator-mxnet/python/mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Darwin-16.7.0-x86_64-i386-64bit
system       : Darwin
node         : 88e9fe759c49.ant.amazon.com
release      : 16.7.0
version      : Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID SMAP RDSEED ADX IPT SGX FPU_CSDS MPX CLFSOPT'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0167 sec, LOAD: 0.5690 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0238 sec, LOAD: 0.3646 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0230 sec, LOAD: 0.1890 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0232 sec, LOAD: 0.2948 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0178 sec, LOAD: 0.3819 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0219 sec, LOAD: 0.0793 sec.
```

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)
gcc

MXNet commit hash:
cb94be94213edc787d69d65eca4d90ba2fcaad6f

Build config:
make -j8

## Error Message:
/Users/lnyuan/.virtualenvs/mxnet/lib/python3.6/site-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=5067578 to reproduce.
test_gluon_data.test_array_dataset ... ok
test_gluon_data.test_recordimage_dataset ... ok
test_gluon_data.test_recordimage_dataset_with_data_loader_multiworker ... thread_monitor No such process in pthread_detach
libc++abi.dylib: terminating
thread_monitor No such process in pthread_detach
libc++abi.dylib: terminating
thread_monitor No such process in pthread_detach
libc++abi.dylib: terminating
thread_monitor No such process in pthread_detach
libc++abi.dylib: terminating
thread_monitor No such process in pthread_detach
libc++abi.dylib: terminating
## Minimum reproducible example
nosetests -v tests/python/unittest/test_gluon_data.py

## Steps to reproduce
nosetests -v tests/python/unittest/test_gluon_data.py

## What have you tried to solve it?
Ran on Linux server and there was no issue.

**Comment by lanking520** [comment]
Hi @apeforest Does this fail in CI?

@mxnet-label-bot could you please add [gluon, test] to this issue?

**Comment by apeforest** [comment]
@marcoabreu Any update on this unit test? This unit test failure on MacOS has caused inconvenience to verify the unittest locally before pushing my change to remote. Any other people who develop on MacOS facing the same issue?

**Comment by KellenSunderland** [comment]
You use gcc on your mac?

**Comment by apeforest** [comment]
@lanking520 We currently don't run MacOS platform in CI, which I think should be installed ASAP.

**Comment by apeforest** [comment]
@lebeg 
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
```

**Comment by KellenSunderland** [comment]
MacOS is now installed on the CI via Travis.
