### ISSUE TITLE
a cheatsheet to document the issues in Gluon hybridize

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12100]
It seems users often ask why hybridize doesn't work. I think it's necessary to have a cheatsheet to document all possible pitfalls that could be encountered during hybridize.

Here are a few examples:
* Symbol doesn't have the shape method.
* [] in NDArray and Symbol has completely different semantics. [] in NDArray is to get a slice from the array. [] in Symbol is to get an output from a grouped symbol.
* Element-wise operators in NDArray and Symbol have different semantics. Element-wise operators in NDArray are broadcast operators, while they in Symbol are actual element-wise operators.
* write-in-place operations.

**Comment by lanking520** [comment]
@mxnet-label-bot could you please add [doc] to this issue?

**Comment by aaronmarkham** [comment]
Hi @zheng-da - here is suggested place for this information:
https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/gluon/hybrid.md

It might also be helpful to clarify these points specifically in the Python documentation.

Let me know if I can help you with those edits. I would put this info in myself, but I fear I'm missing the broader context that you would be able to provide. A couple of examples of the gotchas would really flesh it out. Also, I don't know what the last point was making... one does write-in-place operations and one does not?

**Comment by thomelane** [comment]
https://github.com/apache/incubator-mxnet/pull/13597 (which has been merged) has clarified these points. @ThomasDelteil please close, thanks!
