### ISSUE TITLE
Faulty CUDA detection with cmake

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#12107]
### Problem
The current cmake CUDA support has multiple major problems.

**Multiple not compatible definitions**

CUDA can be part of cmake language detection and is not for older cmake versions.

CUDA architectures can be detected by build-in cmake file. This would be preferred, but is not used by the current MXNet cmake scripts.

CUDA is detected by 3 different files in the current cmake scripts and the choice of those is based on a obscure logic with involves different versions of cmake and platforms which it's building on

- CMakeLists.txt
- cmake/FirstClassLangCuda.cmake
- 3rdparty/mshadow/cmake/Cuda.cmake

**No support for new CUDA architectures or faulty detection**

Only 3rdparty/mshadow/cmake/Cuda.cmake supports Volta architecture, but not in all circumstances.

In a lot of situations the right architecture can not be detected properly and the script falls back to build all architectures bowing up both: build time and artefact size.

cmake/FirstClassLangCuda.cmake is outdated and does not support Volta at all.

CMakeLists.txt sets the CMAKE_GENERATOR_TOOLSET variable which is considered [undefined behaviour](https://cmake.org/cmake/help/v3.1/variable/CMAKE_GENERATOR_TOOLSET.html).

**Confusing and misleading cmake user options**

Currently USE_CUDA / USE_OLDCMAKECUDA. Some of them will do or not do what they supposed to based on cmake generator version and version of cmake.

**Other problems with dependencies**

For example the caffe integration raises the minimum required cmake version to 3.3 due required to c++11 support.

### Solution
As a solution all custom detection of CUDA should be removed and if CUDA is used the minimum cmake version should be raised to 3.10 due to support of latest Volta architectures.

[MXNET-796](https://issues.apache.org/jira/browse/MXNET-796)

**Comment by lanking520** [comment]
Hi @lebeg thanks for your question. Let me try to grab someone who is working on CMake to help you out.

@mxnet-label-bot could you please label this as [CUDA, Installation, Cmake].

**Comment by larroy** [comment]
3.10.0 seems like a super new version of cmake....   but is definitely worth considering if it simplifies the build so much.

**Comment by yajiedesign** [comment]
yes CMAKE_GENERATOR_TOOLSET  is undefined behaviour.In fact, it is already useless.https://github.com/apache/incubator-mxnet/pull/9940 is used to delete it, but it is late asked merger.
