### ISSUE TITLE
Broken test test_io.test_CSVIter

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#12139]
## Description

```
test_io.test_CSVIter ... *** Error in `python3.6': double free or corruption (fasttop): 0x0000000002b74390 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81499)[0x7feff3eec499]
/lib64/libstdc++.so.6(_ZNSs9_M_mutateEmmm+0x1be)[0x7fefdfc56dce]
/lib64/libstdc++.so.6(_ZNSs12_M_leak_hardEv+0x26)[0x7fefdfc56e06]
/work/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc4data9CSVParserIjiE10ParseBlockEPKcS4_PNS0_17RowBlockContainerIjiEE+0x2a8)[0x7fefbcbe7a48]
/work/mxnet/python/mxnet/../../lib/libmxnet.so(+0x3386e6d)[0x7fefbcbb4e6d]
/lib64/libgomp.so.1(+0x163c5)[0x7fefdb11f3c5]
/lib64/libpthread.so.0(+0x7e25)[0x7feff4948e25]
/lib64/libc.so.6(clone+0x6d)[0x7feff3f69bad]
======= Memory map: ========
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/master/runs/1398/nodes/926/steps/1123/log/?start=0

**Comment by lanking520** [comment]
@mxnet-label-bot please label this as [build, CI]

**Comment by marcoabreu** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1397/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1398/pipeline/
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1399/pipeline/
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1400/pipeline/

**Comment by haojin2** [comment]
Fix is merged, and the related test has been re-enabled now. @sandeep-krishnamurthy @nswamy Can you help with closing the issue?
