### ISSUE TITLE
wrong reference to dev list on mxnet.io

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#12150]
Reference to dev list at http://mxnet.incubator.apache.org/community/contribute.html#mxnet-dev-communications 
for dev list correct reference is:
For Contributors to MXNet, join the DEV mailing list:
MXNet Apache DEV mailing list (dev@mxnet.apache.org): To subscribe, send an email to dev-subscribe@mxnet.apache.org 

@aaronmarkham please fix.

**Comment by lupesko** [comment]
@mxnet-label-bot please add [Doc, Bug].

**Comment by vishaalkapoor** [comment]
@eric-haibin-lin The PR has been merged: https://github.com/apache/incubator-mxnet/pull/12271 we can close this off.
