### ISSUE TITLE
Error in Operator implementation guide

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#12168]
## Description
Error in the operator implementation guide:
https://mxnet.incubator.apache.org/faq/add_op_in_backend.html

It's correct in the markdown file: https://github.com/apache/incubator-mxnet/blob/master/docs/faq/add_op_in_backend.md

## Error Message:
"Note that forward and backward functions are registered with attribute key FCompute, rather than FCompute."

**Comment by apeforest** [comment]
@mxnet-label-bot [Documentation]

**Comment by apeforest** [comment]
@nswamy Please label [Doc] for this issue. Thanks

**Comment by anirudhacharya** [comment]
@apeforest there is an ongoing PR to update the operator implementation guide - https://github.com/apache/incubator-mxnet/pull/12230 If you could comment there about what issue you found in the tutorial, it can be fixed in that PR itself.

**Comment by apeforest** [comment]
@nswamy This error is not related to Operator. It is purely a html error. Please remove the [Operator] label and changed it to [Doc]. Thanks!

**Comment by aaronmarkham** [comment]
I think I found the culprit. 
The md-->html build when you do `make html` or `make docs` gives you things like `&lt;gpu&gt;` which renders fine in the browser. 

There's a post-process step for building the versioned website that uses beautiful soup to inject the modified nav bar. It also has a step that swaps out the html tags for < and > with actual < and >.
https://github.com/apache/incubator-mxnet/blame/master/docs/build_version_doc/AddVersion.py#L77

So, introduce this AddVersion.py script and it swaps it back to <gpu>. You can see this in the website static files that have gone through this process:
https://github.com/apache/incubator-mxnet-site/blob/asf-site/faq/add_op_in_backend.html#L751
This does not render properly. This is the same thing happening with the scala tutorial: https://github.com/apache/incubator-mxnet/issues/11438

I can remove that line, but I don't know why it's there in the first place. @piiswrong - you authored it... do you remember what it is for? Can we safely remove it, or provide a more focused implementation so it doesn't break the tags we're trying to put in there?
