### ISSUE TITLE
Control flow operators may fail when names of symbols given duplicate

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#12163]
**TL;DL.** The current implementation of control flow operators heavily relies the assumption that the name of symbols given should be different. This assumption is made in all three control flow operators: `foreach` ([here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L268), [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L272), etc.), `while_loop` ([here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L471), [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L490-L497), etc) and `cond` ([here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L632), [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L651-L656), etc).

**Circumstances that could trigger this.** First, users could pass in a list of arbitrary symbols in which there are symbols sharing the same name. Second, I am not sure if cut graph could produce symbols with the same name. The worst thing is that it seems to me that control flow operators themselves produce symbols of the same name...

**Problems it leads to.** However, this is neither checked in the Python frontend, nor guaranteed in subsequent implementation. This will cause disastrous behavior. For example, in [this line](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L267), when there are two symbols sharing the same name, dict comprehension removes one of them, and then, in [this line](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol/contrib.py#L313), the name of the symbol removed in dict comprehension, will lead to the actual symbol to the unremoved one.

**Sanity check and exceptions.** In `while_loop` and `cond`, this will trigger a `ValueError("The %d-th loop_var doesn't involve into the computation")`, which I happened to add to restrict unnecessary symbols which are unused in all subgraphs. I am not familiar of the behavior of `foreach` when it occurs.

CC: @zheng-da

**Comment by zheng-da** [comment]
Actually, this problem is fixable. A Symbol can have a unique name. The only problem is that Symbol.name() currently only uses the node name as a symbol name. To make a Symbol name unique, we should use NodeEntry names. I'll submit a PR to fix this.

Your other concern is valid. Cutting an edge should generate a var node with a unique name.

**Comment by vdantu** [comment]
@mxnet-label-bot : [Python, Operator, Question]

**Comment by zheng-da** [comment]
@junrushao1994 the corresponding PR has been merged. Can you confirm that your concern has been addressed?

**Comment by junrushao1994** [comment]
@zheng-da Thanks for the reminder! Since #12187 is merged, I believe this issue has been addressed.
