### ISSUE TITLE
Spelling mistake in "mxnet/symbol/image.py" in which "gen_image" is written to be "gen_iamge"

### ISSUE THREAD

**Issue by PlumedSerpent** [apache/incubator-mxnet#12179]
mxnet version:1.2.1
python:3.7
OS:Linux
cuda:8.0

**Comment by haojin2** [comment]
It's a pure typo, see the ndarray counterpart: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/ndarray/image.py#L22

**Comment by Roshrini** [comment]
@nswamy PR with fix was merged. Can you please close this issue? Thanks
