### ISSUE TITLE
LBSGD doc not rendering correctly

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#12171]
<img width="811" alt="screen shot 2018-08-14 at 4 34 51 pm" src="https://user-images.githubusercontent.com/5545640/44124041-07d4bf4a-9fe0-11e8-8463-f963e3e4af83.png">

**Comment by anirudhacharya** [comment]
It is not just documentation, the LBSGD optimizer has bugs as mentioned at the bottom of this PR - https://github.com/apache/incubator-mxnet/pull/8918 and they are still not all addressed. 

@mxnet-label-bot [Optimizer, Bug]

**Comment by aaronmarkham** [comment]
@eric-haibin-lin is this still an issue? I'm not seeing anything particularly unusual with the current output:
https://mxnet.incubator.apache.org/api/python/optimization/optimization.html?highlight=lbsgd#mxnet.optimizer.LBSGD
