### ISSUE TITLE
topk regression

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#12197]
## Description
https://github.com/apache/incubator-mxnet/pull/12085/ introduced a bug into the topk operator. Below code example will output `[ 274232.  179574.  274233.  274231.]` with mxnet-cu90==1.3.0b20180810 but `[ 274232.  179574.  274232.  274232.]` with mxnet-cu90==1.3.0b20180814.

Note that both CPU and GPU versions of the operator are affected.

@szha @ciyongch @eric-haibin-lin 

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. `wget https://s3.amazonaws.com/lllausen-public/topk/array.npy`
2. `python3 -c 'import mxnet as mx;import numpy as np; print(mx.nd.topk(mx.nd.array(np.load("array.npy")), k=4)[80])'`
3. `python3 -c 'import mxnet as mx;import numpy as np; print(mx.nd.topk(mx.nd.array(np.load("array.npy"), ctx=mx.gpu(0)), k=4)[80])'`

**Comment by eric-haibin-lin** [comment]
@ciyongch thanks for looking into this. Your help is much appreciated

**Comment by vdantu** [comment]
@mxnet-label-bot: [Python, Operator, Bug]

**Comment by szha** [comment]
Indeed. Let's address that in 2.0 due to API changes.

**Comment by szha** [comment]
@ciyongch for now please add a follow-up PR to add test for #12202. Thanks a lot for the quick fix.

**Comment by haojin2** [comment]
@szha Fix has been merged, should be good to close

**Comment by szha** [comment]
@haojin2 not really. See comments above. In addition tests need to be added.

**Comment by ciyongch** [comment]
@szha sure, I will add two kinds of test cases to topk op, one is similar to the case used by @leezu , the other one is what I mentioned above (Since it will fail unless API change, so this one will be skipped by default for now). Any comments?

**Comment by ciyongch** [comment]
Hi @szha , I submit a PR https://github.com/apache/incubator-mxnet/pull/12217 to cover this case, and this is only for the first option mentioned above. For the second one, we can add it after the API was changed.
BTW, any plan to support `int` type of ndarray as a input to topk?

**Comment by sxjscience** [comment]
I think https://github.com/apache/incubator-mxnet/pull/12250 has solved this problem. Now we can use `mx.nd.topk(..., dtype=np.int32)` to set the dtype of the output indices. 

```python
import mxnet as mx
import numpy as np
print(mx.nd.topk(mx.nd.array(np.arange(256*300096).reshape(8, -1), dtype=np.int32), k=4, dtype=np.int32))
```

Result:

```
[[9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]
 [9603071 9603070 9603069 9603068]]
<NDArray 8x4 @cpu(0)>
```

**Comment by haojin2** [comment]
@sxjscience I agree that the problem seems to be fixed now, please feel free to close the issue or we can wait for @leezu to close it.

**Comment by leezu** [comment]
Thanks to everyone for fixing this

**Comment by yifeim** [comment]
@leezu Quick question: shall we make `dtype=np.int64` a default? I cannot see any reason we should hold on to the float32 default -- the previous defaults may have been an implicit bug in the first place.

**Comment by leezu** [comment]
@yifeim this may break backwards compatibility of the topk operator. If you feel it is worth to break the compatibility for this change I suggest to discuss with @sxjscience about it.

Nevertheless it seems that #12250 got merged without the documentation on the website being updated about the recommendation to use `dtype=np.int64`.

**Comment by szha** [comment]
@yifeim this is tracked in #9686.
