### ISSUE TITLE
syncBN can't work

### ISSUE THREAD

**Issue by PistonY** [apache/incubator-mxnet#12216]
Note: 

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
I use [syncBn](https://mxnet.incubator.apache.org/api/python/gluon/contrib.html?highlight=sync#mxnet.gluon.contrib.nn.SyncBatchNorm) but the script stucked.It can't run.

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
----------Python Info----------
Version      : 3.6.6
Compiler     : GCC 7.2.0
Build        : ('default', 'Jun 28 2018 17:14:51')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /home/bmi/anaconda3/envs/mxnet-90/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Linux-4.4.0-130-generic-x86_64-with-debian-stretch-sid
system       : Linux
node         : bmi-server
release      : 4.4.0-130-generic
version      : #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2602.687
CPU max MHz:           3200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4801.41
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5
NUMA node1 CPU(s):     6-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0071 sec, LOAD: 1.9778 sec.
```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.I just use syncBN.Before that,I used BN the program run well.
2.the program stucked at 
0%| | 0/39 [00:00<?, ?it/s][15:25:13] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:109: Running performance tests to find the best convolution algorithm, this can take a while… (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)

## What have you tried to solve it?

1.I reduce the batch_size but doesn't work
2.

**Comment by haojin2** [comment]
@zhanghang1989

**Comment by zhanghang1989** [comment]
1). Please set `num_devices` to the number of gpus, if not all of them are used. 
2). Please make sure each gpu has at least one training sample.
3). I only use gluon API, someone also get Symbol working, but I haven't tried. You can refer to GluonCV for examples https://github.com/dmlc/gluon-cv/blob/master/scripts/segmentation/train.py#L112

**Comment by vdantu** [comment]
@mxnet-label-bot : [Python, Operator, Question]

**Comment by PistonY** [comment]
First of two I can ensure them.But I use 
```python
net.hybridize(static_alloc=True)
```
May that cause the problem.

**Comment by zhanghang1989** [comment]
`net.hybridize()` should work. `static_alloc=True` may give troubles due to the tmp workspace? @eric-haibin-lin

**Comment by PistonY** [comment]
I've tried comment
```python
# net.hybridize(static_alloc=True)
```
but it still cat't work.
This is my [code](https://gist.github.com/PistonY/d216e01a64c120a184c87709f3b285b7)
U can have a look.

**Comment by zhanghang1989** [comment]
How about not `hybridize()`

**Comment by PistonY** [comment]
I've tried, but not work.
