### ISSUE TITLE
"make" command producing error. 

### ISSUE THREAD

**Issue by doubleconnect1** [apache/incubator-mxnet#12218]
I am trying to fork a cryptocurrency and successfully compiled the source code  in my local machine and committed those changes to following github repository:   https://github.com/doubleconnect1/realnowcoin.git

Now I am trying to make a seed node using AWS.  I logged into an instance and cloned the repository and ran the following commands

sudo apt install build-essential libqt4-dev qt5-qmake cmake qttools5-dev libqt5webkit5-dev qttools5-dev-tools qt5-default python-sphinx texlive-latex-base inotify-tools openssl libssl-dev libdb++-dev libminiupnpc-dev git sqlite3 libsqlite3-dev g++ libpng-dev gedit python gcc make libbz2-dev libdb-dev libssl-dev libreadline-dev autoconf libtool libleveldb-dev libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev nano qtbase5-dev qt4-dev-tools libqtcore4 libqtgui4 automake -y﻿

sudo apt-get update
sudo apt-get install libboost-all-dev
sudo apt-get update && sudo apt-get install build-essential﻿

and make and got the following error message.

---------------------------------------------------------------------------------------------------
ubuntu@ip-172-31-22-130:~/realnowcoin$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
You have called ADD_LIBRARY for library BlockchainExplorer without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Common without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Crypto without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Http without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library InProcessNode without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Logging without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library NodeRpcProxy without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Rpc without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library P2P without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Serialization without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library System without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Transfers without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library Wallet without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library PaymentGate without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library JsonRpcServer without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:54 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:55 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:56 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:57 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:58 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:65 (target_link_libraries):
  Cannot specify link libraries for target "ConnectivityTool" which is not
  built by this project.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/realnowcoin/build/release/CMakeFiles/CMakeOutput.log".
Makefile:16: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 1

----------------------------------------------------------------------------
In my local machine, the make command worked successfully and I am using the same code 
in aws terminal and make command is producing the above errors.   
What should I do?
Please help me.

**Comment by haojin2** [comment]
Seems like your question is not related to MXNet at all, would you please close your issue? Thanks!

**Comment by doubleconnect1** [comment]
is only MXNet related issue allowed to be posted?
