### ISSUE TITLE
using C++ api and GPU  in windows 10 to extract feature occurs  error when bind weights and parameters

### ISSUE THREAD

**Issue by ghgggg** [apache/incubator-mxnet#12215]
i'm just using mxnet C++ api to extract feature  ,show the codes below

cv::Mat img = _img.getMat();
		img.convertTo(img, CV_32F);
		img = (img - 127.5) / 128;
		static NDArray input(Shape(1, img.channels(), img.rows, img.cols), ctx);	//
		

		NDArray temp(Shape(1, img.channels(), img.rows, img.cols), Context(kCPU, 0),false); 
		NDArray::WaitAll();
		auto ptr = temp.GetData();
		std::vector<cv::Mat> chs(3);
		for (int i = img.channels() - 1; i >= 0; i--)
		{
			chs[img.channels() - i - 1] = cv::Mat(img.size(), CV_32FC1, (float*)ptr + i*img.size().area());
		}
		cv::split(img, chs);
		//input = temp.Copy(ctx);
		input.SyncCopyFromCPU(temp.GetData(), temp.Size());
		NDArray::WaitAll();
		return Extract(input);

when ctx = Context(kGPU, 0);
the code     executor = net.SimpleBind(ctx, args_map, map<string, NDArray>(), map<string, OpReqType>(), aux_map);  occurs  error. but cpu mode all of them are OK.
I don't know how to solve it ,anybody could help me ?thanks a lot

**Comment by vdantu** [comment]
@ghgggg : Could you submit this issue as a issue template? It isn't clear what the exact error is from the issue. For reference https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md

@mxnet-label-bot: [C++, Windows, Question]

**Comment by ghgggg** [comment]
@vdantu  i has recommit the issue as a new one ,could you help me to solve it ?thansk a lot. i will close this one. the new issue is #12267 .thank you
