### ISSUE TITLE
CPU speed problem: MxNet 4 times slow than Caffe 

### ISSUE THREAD

**Issue by wangzhangup** [apache/incubator-mxnet#1222]
I convert same model and parameter from caffe to MxNet. Everything works fine. But time spend more than about 4 times. Only using CPU
They both use atlas, same machine

**Comment by qiaohaijun** [comment]
caffe and mxnet all in the cpu model?

**Comment by wangzhangup** [comment]
@qiaohaijun yes, CPU on same machine

**Comment by starimpact** [comment]
@tqchen @piiswrong

**Comment by winstywang** [comment]
Could you help to do some profile like in http://www.network-theory.co.uk/docs/gccintro/gccintro_80.html ?

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solved the problem?  @wangzhangup

**Comment by uestcbingo** [comment]
I encountered the same issue, CPU version of mxnet is 3 times slower than caffe both using MKL. Did you solve the problem? @wangzhangup

**Comment by javelinjs** [comment]
@wangzhangup @uestcbingo Curious about this issue, mind listing the caffe model configuration?

**Comment by hjk41** [comment]
Guys, is there any performance profiling tools in mxnet? I am also trying
to figure out the issue on CPU. Currently mxnet does not fully utilize my
CPUs on Windows.

On Tue, Feb 2, 2016 at 12:28 AM, Yizhi Liu <notifications@github.com> wrote:

> @wangzhangup <https://github.com/wangzhangup> @uestcbingo
> <https://github.com/uestcbingo> Curious about this issue, mind listing
> the caffe model configuration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1222#issuecomment-178056479>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by piiswrong** [comment]
@hjk41 Not that I'm aware of. I have been thinking about adding profiling to the engine for a while. For example add a string tag to each Push and count time for each tag. But @tqchen Thinks this has negative performance implications.

BTW, there is a pretty easy fix for not fully using CPU: change mshadow/mshadow/tensor_cpu-inl.h:143 to a OpenMP parallel for.

**Comment by hjk41** [comment]
ok. Back in Minerva v2, we had some kind of lightweight profiling which can
be turned on when needed. I think we can do the same for mxnet.

For the mshadow fix, why isn't this enabled by default?

On Tue, Feb 2, 2016 at 10:06 AM, Eric Junyuan Xie <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> Not that I'm aware of. I have been
> thinking about adding profiling to the engine for a while. For example add
> a string tag to each Push and count time for each tag. But @tqchen
> <https://github.com/tqchen> Thinks this has negative performance
> implications.
>
> BTW, there is a pretty easy fix for not fully using CPU: change
> mshadow/mshadow/tensor_cpu-inl.h:143 to a OpenMP parallel for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1222#issuecomment-178311441>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
@wangzhangup I am looking into this issue. Is it possible to give me the program that you are using? Both for mxnet and caffe?

**Comment by piiswrong** [comment]
Because... Its a Pr people have been too lazy to push?

**Comment by hjk41** [comment]
Just tried the mshadow trick. It does boosts the CPU utilization to 100%,
but lowers the overall speed. 😅 I guess enabling OpenMP in that loop
causes a lot of cache coherence overhead.



On Tue, Feb 2, 2016 at 10:15 AM, Eric Junyuan Xie <notifications@github.com>
wrote:

> Because... Its a Pr people have been too lazy to push?
> On Feb 1, 2016 6:10 PM, "Chuntao Hong" <notifications@github.com> wrote:
>
> > ok. Back in Minerva v2, we had some kind of lightweight profiling which
> can
> > be turned on when needed. I think we can do the same for mxnet.
> >
> > For the mshadow fix, why isn't this enabled by default?
> >
> > On Tue, Feb 2, 2016 at 10:06 AM, Eric Junyuan Xie <
> > notifications@github.com>
> > wrote:
> >
> > > @hjk41 <https://github.com/hjk41> Not that I'm aware of. I have been
> > > thinking about adding profiling to the engine for a while. For example
> > add
> > > a string tag to each Push and count time for each tag. But @tqchen
> > > <https://github.com/tqchen> Thinks this has negative performance
> > > implications.
> > >
> > > BTW, there is a pretty easy fix for not fully using CPU: change
> > > mshadow/mshadow/tensor_cpu-inl.h:143 to a OpenMP parallel for.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/dmlc/mxnet/issues/1222#issuecomment-178311441>.
> > >
> >
> >
> >
> > --
> > HONG Chuntao
> > System Research Group
> > Microsoft Research Asia
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dmlc/mxnet/issues/1222#issuecomment-178313054>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1222#issuecomment-178314214>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by piiswrong** [comment]
try reducing the number of omp thread or limit mxnet's number of cpu
workers. They are probably competing.

**Comment by mli** [comment]
did a benchmark on mnist with lenet (batch size = 256) and openblas

|                      |lenet (img/s)   |    cpubenchmark.net|
| ---- | ---- | ---- |
|2 x e5-2630 v3  | 676              |     12877|
|2 x e5-2670        | 604             |      12514|
|e5-1620 v3         | 540            |       9658|
|i7-4790               | 546            |       10019|
|i5-3470               | 476           |        6567|

it looks like mxnet is failed to use all cpu powers, especially for dual socket. i also looked into the performance,

```bash
   9.65%  python   [kernel.kallsyms]            [k] update_curr                                                                                                                                                                                                                    ▒
   8.45%  python   libopenblas.so.0             [.] sgemm_kernel_SANDYBRIDGE                                                                                                                                                                                                       ▒
   7.62%  python   [kernel.kallsyms]            [k] __schedule                                                                                                                                                                                                                     ▒
   6.37%  python   [kernel.kallsyms]            [k] pick_next_entity                                                                                                                                                                                                               ▒
   6.20%  python   [kernel.kallsyms]            [k] pick_next_task_fair                                                                                                                                                                                                            ▒
   6.07%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi2EfEELi2EfNS_4expr13MakeTensorExpINS6_20UnpackPatchToColXExpINS3_IS4_Li4EfEEfLi4EEES9_Li2EfEELi3EEEvPNS_7TRValueIT0_S4_XT1_ET2_EERKNS6_3ExpIT3_SE_XT4_EEE                ▒
   5.66%  python   [kernel.kallsyms]            [k] __calc_delta                                                                                                                                                                                                                   ▒
   3.66%  python   [kernel.kallsyms]            [k] cpuacct_charge                                                                                                                                                                                                                 ▒
   3.56%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi4EfEELi4EfNS_4expr13MakeTensorExpINS6_11CroppingExpINS7_INS6_12UnPoolingExpINS_3red7maximumENS7_INS6_10PaddingExpIS5_fLi4EEES5_Li4EfEEfLi4EEESE_Li4EfEEfLi4EEESG_Li4EfEEL▒
   3.34%  python   libc-2.19.so                 [.] __sched_yield                                                                                                                                                                                                                  ▒
   3.17%  python   [kernel.kallsyms]            [k] update_min_vruntime                                                                                                                                                                                                            ▒
   3.05%  python   [kernel.kallsyms]            [k] system_call                                                                                                                                                                                                                    ▒
   2.64%  python   libm-2.19.so                 [.] __expm1f                                                                                                                                                                                                                       ▒
   2.20%  python   [kernel.kallsyms]            [k] system_call_after_swapgs                                                                                                                                                                                                       ▒
   2.11%  python   [kernel.kallsyms]            [k] _raw_spin_lock_irq                                                                                                                                                                                                             ▒
   2.09%  python   [kernel.kallsyms]            [k] clear_buddies                                                                                                                                                                                                                  ▒
   2.05%  python   [kernel.kallsyms]            [k] _raw_spin_lock                                                                                                                                                                                                                 ▒
   1.93%  python   [kernel.kallsyms]            [k] native_read_tsc                                                                                                                                                                                                                ▒
   1.61%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi3EfEELi3EfNS_4expr13MakeTensorExpINS6_10ReshapeExpINS7_INS6_11SwapAxisExpINS3_IS4_Li4EfEEfLi4ELi3ELi0EEESA_Li4EfEEfLi3ELi4EEESC_Li3EfEELi3EEEvPNS_7TRValueIT0_S4_XT1_ET2_▒
   1.56%  python   libopenblas.so.0             [.] 0x00000000003dc027                                                                                                                                                                                                             ▒
   1.43%  python   [kernel.kallsyms]            [k] sys_sched_yield                                                                                                                                                                                                                ▒
   1.34%  python   [kernel.kallsyms]            [k] check_cfs_rq_runtime                                                                                                                                                                                                           ▒
   1.15%  python   libopenblas.so.0             [.] sgemm_otcopy_SANDYBRIDGE                                                                                                                                                                                                       ▒
   1.07%  python   libopenblas.so.0             [.] sgemm_beta_SANDYBRIDGE                                                                                                                                                                                                         ▒
   1.04%  python   [kernel.kallsyms]            [k] native_sched_clock                                                                                                                                                                                                             ▒
   1.02%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi4EfEELi4EfNS_4expr13MakeTensorExpINS6_10PoolingExpINS_3red7maximumENS7_INS6_10PaddingExpIS5_fLi4EEES5_Li4EfEEfLi4EEESD_Li4EfEELi3EEEvPNS_7TRValueIT0_S4_XT1_ET2_EERKNS6_3▒
   1.02%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi4EfEELi4EfNS_4expr13MakeTensorExpINS6_18PackColToPatchXExpINS3_IS4_Li2EfEEfLi4EEES9_Li4EfEELi3EEEvPNS_7TRValueIT0_S4_XT1_ET2_EERKNS6_3ExpIT3_SE_XT4_EEE                  ▒
   0.99%  python   [kernel.kallsyms]            [k] update_rq_clock.part.81                                                                                                                                                                                                        ▒
   0.91%  python   libm-2.19.so                 [.] __tanhf                                                                                                                                                                                                                        ▒
   0.87%  python   [kernel.kallsyms]            [k] yield_task_fair                                                                                                                                                                                                                ▒
   0.77%  python   [kernel.kallsyms]            [k] sysret_check                                                                                                                                                                                                                   ▒
   0.71%  python   libmxnet.so                  [.] _ZN7mshadow6MapExpINS_2sv6savetoENS_6TensorINS_3cpuELi4EfEELi4EfNS_4expr13MakeTensorExpINS6_11SwapAxisExpINS7_INS6_10ReshapeExpINS3_IS4_Li3EfEEfLi4ELi3EEESA_Li4EfEEfLi4ELi3ELi0EEESC_Li4EfEELi3EEEvPNS_7TRValueIT0_S4_XT1_ET2_▒
   0.65%  python   libopenblas.so.0             [.] sgemm_oncopy_SANDYBRIDGE                                                                                                                                                                                                       ▒
   0.58%  python   [kernel.kallsyms]            [k] rcu_note_context_switch 
```
there is a large system overhead, probably due to most threads are idle. in the most two expensive mshadow functions, there are a large mount of `cmp`, `mov`, and `imul`. hope it helps

**Comment by u1234x1234** [comment]
I have the same problems, it seems due to the python wrapper, because prediction from c++ works 4-5 times faster.

**Comment by piiswrong** [comment]
@u1234x1234 Thanks for reporting this. @hjk41 What do you think?

**Comment by hjk41** [comment]
We are tuning CPU performance these days. We are doing it with MxNet.cpp,
though. Will report back if we have some findings.

On Sun, Mar 20, 2016 at 3:26 AM, Eric Junyuan Xie <notifications@github.com>
wrote:

> @u1234x1234 <https://github.com/u1234x1234> Thanks for reporting this.
> @hjk41 <https://github.com/hjk41> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1222#issuecomment-198774168>
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by starimpact** [comment]
Great!

**Comment by rhythm9229** [comment]
i am trying get predictions for images using imagenet-21k-inception model but the prediction on cpu is very slow.
The prediction takes about 1.06 seconds for a single image and i tried to give images in batch but still there is no speed gain. I thought that giving images in batch will speed things up.
Is there something that i am doing wrong?
Is there a way to make predictions fast on cpu?

**Comment by realzheng** [comment]
I have the same problem, my testing code is in c++ with MXNet.cpp , and do the prediction on cpu, it's about 2 times slower than caffe.

**Comment by careyjiang** [comment]
me too

**Comment by ajtulloch** [comment]
Some points for CPU inference in Caffe:

- For tiny models, there are a few unnecessary allocations in the forward pass in a few layers during reshaping. Only reshaping when shapes change helps a bit.
- Inlining execution (when you can guarantee that all dependencies of a child operator have concluded whe executing a parent, running the child directly instead of throwing back into a job queue) helps a lot for some networks.

- Specifically for convolutional networks on Haswell or above Intel CPUs at reasonable batch sizes (>32 or so), using NNPACK helps a lot (see https://github.com/BVLC/caffe/issues/4264 for an example integration). I'd suggest wrapping that in MXNet as a plugin, it's a really useful library in some scenarios.

**Comment by tqchen** [comment]
Thnks @ajtulloch  the inclining execution is added in #2496 

The NNPack could be an interesting thing to add

**Comment by hjk41** [comment]
Tuning OMP_NUM_THREADS and OPENBLAS_NUM_THREADS can make much difference.
According to our experiments, setting OMP_NUM_THREADS to the number of
cores of a single CPU performs best in a multi-socket machine. The
difference can be more than 2X.

NNPACK seems interesting. Intel has been working on similar things in MKL.
It is said that a DNN-optimized MKL version will be released at Q4 this
year.

On Wed, Jun 22, 2016 at 12:32 PM, Tianqi Chen <notifications@github.com>
wrote:

> Thnks @ajtulloch <https://github.com/ajtulloch> the inclining execution
> is added in #2496 <https://github.com/dmlc/mxnet/pull/2496>
>
> The NNPack could be an interesting thing to add
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1222#issuecomment-227640521>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABFI4RjY5MXBxG70TDVku79VJRyrO0fsks5qOLrygaJpZM4HBqqR>
> .
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by passerbythesun** [comment]
@hjk41 so MxNet is still slower than caffe on CPU for now?

**Comment by Darwin2011** [comment]
@hjk41 @piiswrong 
- community has some plan to integrate NNPACK or MKLDNN library?
- mxnet cpu patch2cols is one element-by-element copy from src images to dst cols. It will slow down performance even though openmp on. Community has plan to improve it?

**Comment by ajtulloch** [comment]
@Darwin2011  NNPACK is there already if you use the CaffeOp and pull https://github.com/ajtulloch/caffe/tree/nnpack-pr into your Caffe branch btw :)

**Comment by hjk41** [comment]
MKLDNN will not be available until late this year. They do have a tech
preview, though. I think we should have someone look into it. I have just
moved to a new company so I won't have much time for this. I will post a
request for contribution in the issue and see if someone is interested.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
