### ISSUE TITLE
Scale to many CPU cores

### ISSUE THREAD

**Issue by qw42** [apache/incubator-mxnet#12239]
What is the best way to achieve best throughput (only forward runs) on a multi-cpu/many-core server?

## Description
I am using CPP package. My problem is "embarrassingly parallel" - each forward pass can be run independently.  It looks to me that mxnet doesn't scale well with number of CPUs.
My goal is to maximize overall throughput, not to minimize each forward passes' computation time.
I can achieve it by running multiple processes (one per core). Maybe I missed something, but I couldn't find a way to do it with multiple threads.

**Comment by pengzhao-intel** [comment]
One practical approach is to launch many instances (mxnet itself) and each one uses several cores, say 4,8,16, for your inference.  So you can get maximize the overall throughput a lot.

BTW, MKLDNN backend will be much faster now. You need to specify the thread number and bind thread to physical cores explicitly.

https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md

**Comment by vdantu** [comment]
@mxnet-label-bot : [C++, Windows, Question]

**Comment by qw42** [comment]
Hi pengzhao.
In that table from MXNET-11 does "28 core, 1 instance" means running 1 process with 28 threads?
Thank you.

**Comment by qw42** [comment]
Hi pengzhao.
Can you elaborate how to do it? Create multiple executors and call them from multiple threads? Which version of mxnet? Thanks you.

**Comment by pengzhao-intel** [comment]
@qw42 , you can use master branch or release version >= 1.2.0.

A simple experiment by following commands. 

```
export OMP_NUM_THREADS=${CORES_NUM}
mem_num=0
COMMAND="numactl -C 0-$[${CORES_NUM}-1] -m ${mem_num} python XXX.py"
for ((i=1;i<${INSTANCES};i++))
        do
              if [ $[${CORES_NUM}*$i] -ge 28 ];then
               mem_num=1
               fi
              CAFFE_COMMAND+=" & numactl -C $[${CORES_NUM}*$i]-$[${CORES_NUM}*$i+${CORES_NUM}-1] -m ${mem_num} python XXX.py"
        done
echo ${CAFFE_COMMAND} > run_instance.sh
bash -x run_instance.sh
```

**Comment by pengzhao-intel** [comment]
@qw42 did you have a chance to try and could this approach help for your case？

**Comment by pengzhao-intel** [comment]
Thanks for the feedback. It needs the FW level supports or you can write your own code for your targets.
