### ISSUE TITLE
Failed compile mxnet master with cuda9.2 and ubuntu 18.04

### ISSUE THREAD

**Issue by guanlinting** [apache/incubator-mxnet#12241]
## Description
Failed compile mxnet master with cuda9.2 and ubuntu 18.04.

Error messages are as follow:
build/src/operator/nn/deconvolution_gpu.o：在函数‘mxnet::op::CuDNNDeconvolutionOp<float>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op20CuDNNDeconvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0xbe)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()’未定义的引用
tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op20CuDNNDeconvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0xd66)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()’未定义的引用
build/src/operator/nn/deconvolution_gpu.o：在函数‘mxnet::op::CuDNNDeconvolutionOp<double>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op20CuDNNDeconvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0xbe)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()’未定义的引用
tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op20CuDNNDeconvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0xd66)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()’未定义的引用
build/src/operator/nn/deconvolution_gpu.o：在函数‘mxnet::op::CuDNNDeconvolutionOp<mshadow::half::half_t>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_[_ZN5mxnet2op20CuDNNDeconvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_]+0xbe)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()’未定义的引用
build/src/operator/nn/deconvolution_gpu.o:tmpxft_00005635_00000000-5_deconvolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op20CuDNNDeconvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_[_ZN5mxnet2op20CuDNNDeconvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_]+0xd66): 跟着更多未定义的参考到 mxnet::op::CuDNNAlgoReg<mxnet::op::DeconvolutionParam>::Get()
build/src/operator/nn/convolution_gpu.o：在函数‘mxnet::op::CuDNNConvolutionOp<float>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op18CuDNNConvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0x219)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()’未定义的引用
tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op18CuDNNConvolutionOpIfE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0x170c)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()’未定义的引用
build/src/operator/nn/convolution_gpu.o：在函数‘mxnet::op::CuDNNConvolutionOp<double>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op18CuDNNConvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0x219)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()’未定义的引用
tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_[_ZN5mxnet2op18CuDNNConvolutionOpIdE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaIS8_EESC_15cudnnDataType_tSD_]+0x170c)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()’未定义的引用
build/src/operator/nn/convolution_gpu.o：在函数‘mxnet::op::CuDNNConvolutionOp<mshadow::half::half_t>::SelectAlgo(mxnet::RunContext const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, cudnnDataType_t, cudnnDataType_t)’中：
tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_[_ZN5mxnet2op18CuDNNConvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_]+0x219)：对‘mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()’未定义的引用
build/src/operator/nn/convolution_gpu.o:tmpxft_00005904_00000000-5_convolution.compute_70.cudafe1.cpp:(.text._ZN5mxnet2op18CuDNNConvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_[_ZN5mxnet2op18CuDNNConvolutionOpIN7mshadow4half6half_tEE10SelectAlgoERKNS_10RunContextERKSt6vectorIN4nnvm6TShapeESaISB_EESF_15cudnnDataType_tSG_]+0x170c): 跟着更多未定义的参考到 mxnet::op::CuDNNAlgoReg<mxnet::op::ConvolutionParam>::Get()
collect2: error: ld returned 1 exit status
Makefile:515: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

**Comment by haojin2** [comment]
Can you also provide more details on your environment?
Detailed instructions provided in the template of issues, copying here for your convenience:
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
```

**Comment by vdantu** [comment]
@guanlinting : Could you please provide further information? 

@mxnet-label-bot : [Ubuntu, Build, CUDA, Question]
