### ISSUE TITLE
RowSparseNDArray.retain() is an infinite loop

### ISSUE THREAD

**Issue by cclauss** [apache/incubator-mxnet#12242]
Spotted by @vandanavk and PyLint at https://github.com/apache/incubator-mxnet/pull/12200#issuecomment-413691405

[RowSparseNDArray.retain()](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/ndarray/sparse.py#L784-L790) would seem to recurse forever. 

At the root of the repo...

$ __python3 -m pylint python --disable=all --enable=undefined-variable__  # with PyLint 2.1.1
```
************* Module mxnet.ndarray.sparse
python/mxnet/ndarray/sparse.py:790:15: E0602: Undefined variable 'retain' (undefined-variable)

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
```

**Comment by vdantu** [comment]
@mxnet-label-bot : [Python, Question] .. 

It looks like this refers to retain() in gen_parse.py ...

**Comment by vandanavk** [comment]
@eric-haibin-lin

**Comment by vandanavk** [comment]
PR https://github.com/apache/incubator-mxnet/pull/12277

**Comment by vandanavk** [comment]
PR merged. Can this be closed?
