### ISSUE TITLE
broken links on mxnet.io

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#12243]
## Description
http://jenkins.mxnet-ci.amazon-ml.com/job/Broken_Link_Checker_Pipeline/225/console reports valid (and invalid broken links).

## Environment info (Required)
see http://jenkins.mxnet-ci.amazon-ml.com/job/Broken_Link_Checker_Pipeline/225/console 

## Error Message:
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/faq/model_parallel_lstm.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/dmlc/mxnet/blob/master/example/model-parallel/lstm/lstm.py (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] ─ https://github.com/dmlc/mxnet/blob/master/example/model-parallel/lstm/lstm.py (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm.py#L171 (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm_ptb.py#L97-L102 (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/blob/master/example/model-parallel/lstm/lstm.py#L225-L235 (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/tutorials/python/linear-regression.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://mxnet.incubator.apache.org/api/python/model.html#evaluation-metric-api-reference (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/tutorials/gluon/logistic_regression_explained.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://mxnet.incubator.apache.org/api/python/model.html#mxnet.metric.Accuracy (HTTP_404)
        broken, but invisible from parent page
[BrokenLinkChecker: CPU] ─ https://mxnet.incubator.apache.org/api/python/model.html#mxnet.metric.F1 (HTTP_404)
        broken, but invisible from parent page
[BrokenLinkChecker: CPU] ─ https://mxnet.incubator.apache.org/api/python/model.html#mxnet.metric.Accuracy (HTTP_404)
        broken, but invisible from parent page
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/imageclassifier/package.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/im%0A%20%20%20%20ageclassifier (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/imageclassifier/ImageClassifierExample$.html
        visible link from parent page, broken
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/im%0A%20%20%20%20ageclassifier (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/objectdetector/package.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/object%0A%20%20%20%20detector (HTTP_404)
        visible link from parent page, broken
[BrokenLinkChecker: CPU] 
[BrokenLinkChecker: CPU] URL -  https://mxnet.incubator.apache.org/api/scala/docs/org/apache/mxnetexamples/infer/objectdetector/SSDClassifierExample.html
[BrokenLinkChecker: CPU] Broken Links
[BrokenLinkChecker: CPU] ─ https://github.com/apache/incubator-mxnet/tree/master/s%0A%20%20%20%20cala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/object%0A%20%20%20%20detector (HTTP_404)
        visible link from parent page, broken

**Comment by vdantu** [comment]
@mxnet-label-bot : [CI, Unclear Error/Doc]

**Comment by srochel** [comment]
Validated links from doc, all issues are addressed.
