### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by TobyRoseman** [apache/incubator-mxnet#12266]
Python 3.7 was officially released almost two months ago. Having MXNet support Python 3.7 would be very helpful.

**Comment by ankkhedia** [comment]
@mxnet-label-bot : [Python, Feature Request]

**Comment by jasonyu1996** [comment]
I agree. Is there any current effort towards this?

**Comment by eric-haibin-lin** [comment]
@TobyRoseman is the turicreate project depending on MXNet?

**Comment by TobyRoseman** [comment]
@eric-haibin-lin - yes, turicreate depends on MXNet: [link to our setup.py](https://github.com/apple/turicreate/blob/master/src/unity/python/setup.py#L181). Before turicreate can support 3.7, we will  need MXNet to support 3.7. We'll also need to update the version of MXNet we depend on.

**Comment by TobyRoseman** [comment]
MXNet appears to support Python 3.7 now: https://pypi.org/project/mxnet/1.3.0.post0/#files

Is this officially supported?

**Comment by marcoabreu** [comment]
Hi, at the moment, our CI runs on python 3.6.

@szha is creating the releases. Could you elaborate whether we do any testing with these binaries related to python 3.7?

**Comment by szha** [comment]
We run part of the unit tests before publishing to pypi. Same applies to 3.7. Note that this represents a partial test, and full coverage requires work on the Jenkins CI side.

**Comment by patricieni** [comment]
Hi, is there an update on this and whether you will add support for 3.7?

**Comment by TobyRoseman** [comment]
MXNet now appears to support Python 3.7. Closing.

**Comment by yuriploc** [comment]
@TobyRoseman This should be reopen, as it looks like MXNet still doesn't support Python 3.7: https://pypi.org/project/mxnet/#files

**Comment by TobyRoseman** [comment]
@yuriploc - The `mxnet-1.5.1.post0-py2.py3-none-manylinux1_x86_64.whl` file from the link you gave is for Linux.

**Comment by yuriploc** [comment]
My apologies, @TobyRoseman. I'm eager for a new version of `turicreate` to support 3.7 and did not read the whole list correctly.

**Comment by TobyRoseman** [comment]
No problem @yuriploc. We're tracking that issues [here](https://github.com/apple/turicreate/issues/788) and getting very close to releasing a fix.
