### ISSUE TITLE
Inconsistent type conversion from numpy.ndarray to mx.ndarray

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#12268]
When we create a mxnet ndarray using a numpy ndarray, the dtype will not be automatically inherited. However, if we create a mxnet ndarray based on an existing mxnet ndarray, the dtype will be inherited.

Example: 
```python
import mxnet as mx
import numpy as np
dat_np_to_mx = mx.nd.array(np.arange(10, dtype=np.int32))
dat_mx_to_mx =mx.nd.array(mx.nd.arange(10, dtype=np.int32)) 
print(dat_np_to_mx.dtype, dat_mx_to_mx.dtype)
```
Result: 
```<class 'numpy.float32'> <class 'numpy.int32'>```

**Comment by ankkhedia** [comment]
@mxnet-label-bot : [Feature Request, Python]

**Comment by ankkhedia** [comment]
I tried reproducing the issue. Seems like whenever we want to try to create a ndarray from bumpy array, the dtype defaults to float32 regardless of dtype of  the input numpy array.

**Comment by sxjscience** [comment]
This issue is solved by the new Numpy NDArray in MXNet:
```python
import mxnet as mx
import numpy as np
mx.npx.set_np()
dat_np_to_mx = mx.np.array(np.arange(10, dtype=np.int32))
dat_mx_to_mx =mx.np.array(mx.np.arange(10, dtype=np.int32)) 
print(dat_np_to_mx.dtype, dat_mx_to_mx.dtype)
```

```log
int32 int32
```
