### ISSUE TITLE
Nightly Tests Binary Failure chapter05_recurrent-neural-networks/rnns-gluon StraightDope: Python2 Single-GPU StraightDope: Python3 Single-GPU

### ISSUE THREAD

**Issue by Chancebair** [apache/incubator-mxnet#12309]
## Description
Nightly tests have failed on test "chapter05_recurrent-neural-networks/rnns-gluon" for two consecutive runs with timeout errors.  We can reasonably say that the CI infrastructure is performing as expected.

08-22: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTests_onBinaries/detail/NightlyTests_onBinaries/125/pipeline
08-23: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTests_onBinaries/detail/NightlyTests_onBinaries/126/pipeline

```
.
INFO:root:Running notebook 'chapter05_recurrent-neural-networks/rnns-gluon'
INFO:traitlets:Executing notebook with kernel: python2
ERROR:traitlets:Timeout waiting for execute reply (600s).
ERROR:root:Cell execution timed out
.
======================================================================
FAIL: test_rnns_gluon (test_notebooks_single_gpu.StraightDopeSingleGpuTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/mxnet/tests/nightly/straight_dope/test_notebooks_single_gpu.py", line 180, in test_rnns_gluon
    assert _test_notebook('chapter05_recurrent-neural-networks/rnns-gluon')
AssertionError
----------------------------------------------------------------------
```

**Comment by marcoabreu** [comment]
@zhreshold

**Comment by sandeep-krishnamurthy** [comment]
@vishaalkapoor - Any comments here? Thanks!

**Comment by vishaalkapoor** [comment]
@sandeep-krishnamurthy 
Hi, this was resolved by reverting notebooks that were added on 08-21 (just prior to the failure) https://github.com/apache/incubator-mxnet/pull/12343
and you created an issue to track adding back those notebooks. 
https://github.com/apache/incubator-mxnet/issues/12345
Coincidentally, I'm looking at the straight dope today :)

Please feel free to close this issue as it's being tracked in issue 12345.
