### ISSUE TITLE
Sphinx is unable to access some MXNet ONNX module functions

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12318]
This causes Sphinx to fail processing the API docs when shorthand references are used. I used a workaround in #12317 to just reference the functions the long way. 

This means the reference is:
`mxnet.contrib.onnx.onnx2mx.import_model.import_model`
When it could be:
`mxnet.contrib.onnx.import_model`

![2018-08-23_15-08-55](https://user-images.githubusercontent.com/5974205/44555096-657b4100-a6e8-11e8-8ea5-49cf3db31063.png)

But the shorthand route doesn't work.

Example:
```
ubuntu@ip-172-31-66-78:~/incubator-mxnet/docs$ python -c "import mxnet.contrib.onnx.onnx2mx"
ubuntu@ip-172-31-66-78:~/incubator-mxnet/docs$ python -c "import mxnet.contrib.onnx.onnx2mx.import_model"
ubuntu@ip-172-31-66-78:~/incubator-mxnet/docs$ python -c "import mxnet.contrib.onnx.import_model"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named import_model
```
@Roshrini

**Comment by ankkhedia** [comment]
@mxnet-label-bot [Doc, Website]

**Comment by aaronmarkham** [comment]
Hi @marcoabreu - this is more of a Python issue on the engineering side than something that can be fixed from within the website or docs systems. I might even label it a bug.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please label above as [Python, Build, Bug] and remove [Doc, Website]

**Comment by vdantu** [comment]
@aaronmarkham : What needs to be done here for the docs?
