### ISSUE TITLE
Clojure's approx= test function has a weakness

### ISSUE THREAD

**Issue by taliesinb** [apache/incubator-mxnet#12320]
## Description
The clojure framework's `approx=` test utility function (defined in `contrib/clojure-package/test/org/apache/clojure_mxnet/util_test.clj`) is unable to detect differences between arrays if they are of different sizes and the difference occurs in the excess.

For example, this returns true, but should return false:

```
(approx= 1e-9 [1 1 1] [1 1 1 9 9 9])
```

This means that tests that use `approx=` in the clojure test suite can incorrectly succeed.

**Comment by taliesinb** [comment]
I have fixed this in https://github.com/apache/incubator-mxnet/pull/12064.

**Comment by ankkhedia** [comment]
@mxnet-label-bot [Clojure]

**Comment by gigasquid** [comment]
Thanks @taliesinb 😸  - Closing this issue
