### ISSUE TITLE
Disabled nightly tests for straightdope example notebooks

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#12345]
This is a tracking issue for re-enabling all the straight dope nightly notebook tests.
1. chapter05_recurrent-neural-networks/rnns-gluon. Ref - https://github.com/apache/incubator-mxnet/pull/12326/
2. chapter08_computer-vision/visual-question-answer Ref - https://github.com/apache/incubator-mxnet/pull/12343

@vishaalkapoor

**Comment by vishaalkapoor** [comment]
Thanks @sandeep-krishnamurthy please add me as an assignee.

**Comment by marcoabreu** [comment]
Sorry, we can't assign to non committers

**Comment by vishaalkapoor** [comment]
@sandeep-krishnamurthy @marcoabreu Please feel free to close as https://github.com/apache/incubator-mxnet/pull/12744 addressing this has been merged. Thanks!

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Can you close this issue ?
