### ISSUE TITLE
Documentation does not match what is in the PyPi package

### ISSUE THREAD

**Issue by ieee8023** [apache/incubator-mxnet#12341]
On this page https://mxnet.apache.org/api/python/contrib/onnx.html it says mxnet has functions relating to onnx but 3 of them are not there. Is the PyPi package out of date? 

```
>>> mxnet.__version__
'1.2.1'
>>> mxnet.contrib.onnx.get_model_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_model_metadata'
```

**Comment by ankkhedia** [comment]
@mxnet-label-bot [Documentation, Question]

**Comment by ankkhedia** [comment]
@ieee8023   Thanks for trying it out.
For how-to and usability questions, please use MXNet discuss forum - https://discuss.mxnet.io/ to involve wider community.
We want to use Github issues mainly for bugs and feature request. Feel free to reopen if closed in error.
@Roshrini Could you please help with it?
@sandeep-krishnamurthy Can you please close this issue?

**Comment by aaronmarkham** [comment]
My just merged PR fixes the docs: https://github.com/apache/incubator-mxnet/pull/12317
@ieee8023 - You may want to keep an eye on #12318 as well.
The website should refresh in a bit.

**Comment by sandeep-krishnamurthy** [comment]
Thanks @aaronmarkham 
@ieee8023 - Closing it here as the PR with fix is merged. Please reopen if closed in error.
