### ISSUE TITLE
No Activation Information for mxnet.gluon.nn._Conv

### ISSUE THREAD

**Issue by wkcn** [apache/incubator-mxnet#12353]
## Description
It's confused that there is no any activation information for mxnet.gluon.nn._Conv
```python
>>> mx.gluon.nn.Conv2D(channels=3,kernel_size=(1,1))
Conv2D(None -> 3, kernel_size=(1, 1), stride=(1, 1))
>>> mx.gluon.nn.Conv2D(channels=3,kernel_size=(1,1),activation='relu')
Conv2D(None -> 3, kernel_size=(1, 1), stride=(1, 1))
```

## Environment info (Required)
Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)
MXNet commit hash:
ad34e05b
ver 1.3.0

## What have you tried to solve it?

1. Add the activation information in `mxnet.gluon.nn._Conv.__repr__`

**Comment by ankkhedia** [comment]
@mxnet-label-bot [Feature Request, Gluon]
