### ISSUE TITLE
Refactor speech recognition example

### ISSUE THREAD

**Issue by vandanavk** [apache/incubator-mxnet#12384]
## Description
- Cleanup/simplify speech recognition example
- Refactor singleton usage
- Fix Python3 failures https://github.com/apache/incubator-mxnet/issues/11042

Package used (Python/R/Scala/Julia):
Python 2 and 3

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
6a7bfe905bafe94a33eccd0cb8bc42f0d667f606

## Related issues
https://github.com/apache/incubator-mxnet/issues/12024
PR https://github.com/apache/incubator-mxnet/pull/12291

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Example, Good First Issue]

**Comment by vishaalkapoor** [comment]
@vandanavk is the checked in PR the only change for this issue? If so, would you be able to close this issue off? Thanks!

**Comment by vandanavk** [comment]
The checked in PR fixes a few bugs but does not address the issues mentioned here. Since fixing the example would be a larger effort, based on comments from reviewers, I opened this issue for tracking.

**Comment by vandanavk** [comment]
PR https://github.com/apache/incubator-mxnet/pull/13068
