### ISSUE TITLE
Clojure test failure in CI

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12383]
PR is unrelated to Clojure. Here's the job console:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12102/18/pipeline

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Flaky, Test, Clojure]

**Comment by piyushghai** [comment]
@gigasquid Can you have a look at the failing test here ?

**Comment by ChaiBapchya** [comment]
Unable to look at the pipeline and hence the error. Can you paste the failure/error?

**Comment by gigasquid** [comment]
This is from last year `2018` - I'm not sure which test it was because the log is not there anymore, but the Clojure package did fix some tests. I think this should be closed and reopened if any failures occur again.

**Comment by gigasquid** [comment]
@aaronmarkham are you ok to close this?
