### ISSUE TITLE
cpp_package instructions need clarification and examples need repair

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12401]
I tried following the [instructions for building c++ examples](https://github.com/apache/incubator-mxnet/tree/master/cpp-package#building-c-examples-in-examples-folder).

The resulting binaries don't work out of the box, and after troubleshooting some terminate abruptly, core dump or do nothing.

```
./alexnet: error while loading shared libraries: libmxnet.so: cannot open shared object file: No such file or directory
```

I worked on the example C++ for image prediction (#12397) that has its own Makefile that points to libmxnet.so specifically, and was able to get it to run without hunting for the mxnet library. The Makefile for the `cpp-package/example` files does not mention the library at all. Maybe that's a problem? 

The steps in the README could use some clarification. Eventually after trying a bunch of things, I found a reference that led me to try this:

```
export LD_LIBRARY_PATH=~/incubator-mxnet/lib
```

And some of the examples started working! At least they're finding the library. I can add this line to the instructions if this is what we should recommend that people do after building from source with the cpp package flag turned on.  Is it?

But, then there's also the fact that several the examples core dump:

```
./mlp_gpu
[21:13:44] src/io/iter_mnist.cc:110: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[21:13:44] src/io/iter_mnist.cc:110: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
terminate called after throwing an instance of 'dmlc::Error'
  what():  [21:13:44] ../include/mxnet-cpp/ndarray.hpp:54: Check failed: MXNDArrayCreate(shape.data(), shape.size(), context.GetDeviceType(), context.GetDeviceId(), delay_alloc, &handle) == 0 (-1 vs. 0) 
```

```
./inception_bn 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [21:15:16] ../include/mxnet-cpp/symbol.hpp:219: Check failed: MXSymbolInferShape(GetHandle(), keys.size(), keys.data(), arg_ind_ptr.data(), arg_shape_data.data(), &in_shape_size, &in_shape_ndim, &in_shape_data, &out_shape_size, &out_shape_ndim, &out_shape_data, &aux_shape_size, &aux_shape_ndim, &aux_shape_data, &complete) == 0 (-1 vs. 0) 
```

```
./test_score 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

Or do nothing:

```
./test_optimizer 
```

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [C++, Build, Example, Breaking]

**Comment by aaronmarkham** [comment]
@kalyc - Yes those instructions are updated, but the examples were failing. 
@leleamol Should this be closed? I think you had a PR that fixed some or all of the issues with the examples.

**Comment by stu1130** [comment]
@aaronmarkham after I dived deeper examples. I've captured the current status.

| Model | cpu | gpu | comment |
| ------|:---|---:| -----:  |
|alexnet.cpp |v|v| acc not update|
|googlenet.cpp |?|v|N/A|
|mlp.cpp|v|v|acc not update on gpu|
|mlp_cpu.cpp|v|N/A|N/A|
|mlp_gpu.cpp|N/A|v|N/A|
|mlp_csv.cpp|?|v|acc not update |
|resnet.cpp|?|v|N/A|
|lenet.cpp|v|v|N/A|
|lenet_with_mxdataiter.cpp|v|v|acc not update|
|inception_bn.cpp|x|x|Lai raise a PR fixing this|

There is actually one more example charRNN but I need to figure the input corpus format for it.

* test_optimizer return nothing(do nothing) if it passes the test (we might need to add some feedback text)
* Regarding test_score you need to input the min_score for it `build/test_score 10` for example.

**Comment by aaronmarkham** [comment]
Is v like ✔️ ?
And x like ❌ ?
Is there an issue with "acc not update"? Does this mean it runs the example, but never reports on accuracy? Is that really a problem for an example?

**Comment by roywei** [comment]
@aaronmarkham Refer to https://github.com/apache/incubator-mxnet/issues/13243, some models are not trained at all in examples. Params are not updated after each epoch.
@stu1130 Thank for the detailed table, suggest creating a PR to remove[ unnecessary prints](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/alexnet.cpp#L278) in alexnet.  Also, update readme on the usage of LD_LIBRARY_PATH. I am also not sure if copy the lib folder is necessary in [example make file](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/Makefile#L21)
