### ISSUE TITLE
[PYTHON] Undefined name: 'logging' in ./ci/util.py

### ISSUE THREAD

**Issue by cclauss** [apache/incubator-mxnet#12406]
## Description

Undefined name: 'logging' in ./ci/util.py  Import statement is missing.  https://github.com/apache/incubator-mxnet/commit/6a7bfe905bafe94a33eccd0cb8bc42f0d667f606#r30308353  Linters can catch this automatically.  @larroy @marcoabreu 

## Environment info (Required)
* https://github.com/apache/incubator-mxnet

Package used (Python/R/Scala/Julia):
(I'm using ...) Python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
```
./ci/util.py:73:21: F821 undefined name 'logging'
                    logging.warning("Exception: %s, Retrying in %d seconds...", str(e), mdelay)
                    ^
```
## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce

[flake8](http://flake8.pycqa.org) testing of https://github.com/apache/incubator-mxnet on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ci/util.py:73:21: F821 undefined name 'logging'
                    logging.warning("Exception: %s, Retrying in %d seconds...", str(e), mdelay)
                    ^
1     F821 undefined name 'logging'
1
```

## What have you tried to solve it?

1.
2.

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Python]
