### ISSUE TITLE
Docker ARMv7 build not working due to dockcross problem

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#12421]
ARMv7 builds using docker is broken due to:

https://github.com/dockcross/dockcross/issues/257

Working on a fix.

**Comment by lupesko** [comment]
Thanks for reporting @larroy !
@mxnet-label-bot [ARM, Build]

**Comment by lupesko** [comment]
@larroy I see in Jenkins ARMv7 build is passing?
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1545/pipeline

**Comment by lebeg** [comment]
The problem I think is in the run and test step on qemu, not in the compile. But for now we don't have a CI testing stage for that platform.

**Comment by larroy** [comment]
it builds but it fails at runtime.

**Comment by larroy** [comment]
This can be closed.
