### ISSUE TITLE
Installation guide does not provide instructions how to build a specific release

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#12432]
## Description
https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Python&processor=CPU does not provide instructions how to build a specific release / git tag

Suggestion:
Add git checkout <tag> like below as comment.
git ls-remote --tags https://github.com/apache/incubator-mxnet can be used to get all release tags.

```
git clone --recursive https://github.com/apache/incubator-mxnet
cd incubator-mxnet
# git checkout <tag>  
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas
```

Then expand the test to use:
```
import mxnet as mx
print(mx.__version__)
```

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Doc, Installation]

**Comment by srochel** [comment]
@mxnet-label-bot [Good First Issue]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Good First Issue]

**Comment by szha** [comment]
this definitely isn't a good first issue without pointers. there are separate issues that track the improvement for source build with version selector.
