### ISSUE TITLE
mxnet install page for linux mentions two different versions of Cuda

### ISSUE THREAD

**Issue by smokytheangel0** [apache/incubator-mxnet#12437]
this may very well not be the right place for this, but I didnt see a webpage specific repo for mxnet

https://mxnet.apache.org/install/index.html?platform=Linux&language=Python&processor=GPU

it says to get CUDA 9.0 at first, and then step 2 says install mxnet using CUDA 9.2.
it also says to be very sure which one it is, and I am about as far from sure as possible,
should I just gather all the latest libraries or is it imperative to use the older 9.0 library.

I dont expect my installation questions to be answered, just pointing out a possible error on the webpage.

Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
the mxnet.apache.org website has a possible error, where it points out multiple
versions of CUDA as neccesity for installation.

## Environment info (Required)
Ubuntu 18.04, Chromium, x86_64, NVIDIA GT 10 series

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. go to https://mxnet.apache.org/install/index.html?platform=Linux&language=Python&processor=GPU
2. search CUDA, and you will find it in 1, 2, and 5 out of ten results

## What have you tried to solve it?

1. Let you lot know
2. Attempting to install with cuDNN for 9.0 and what looks like the latest cuda library (9.2?)

**Comment by anirudhacharya** [comment]
@smokytheangel0 thanks for bringing this to our notice.

@mxnet-label-bot [Doc, Installation]

**Comment by kalyc** [comment]
Hello @smokytheangel0 - looks like this issue has been resolved. Could you please close it accordingly?

**Comment by piyushghai** [comment]
@smokytheangel0 Can you confirm if the issue got resolved ? If yes, please close this issue :)

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Seems like PR #12388 resolved this issue. Can you please close this issue ? 

@smokytheangel0 Feel free to re-open if closed in error.
Thanks!
