### ISSUE TITLE
How to use multiple output nodes in cpp

### ISSUE THREAD

**Issue by GeneZC** [apache/incubator-mxnet#12433]
Using gluon, I've created a net similar to ResNet used in AlphaGo Zero (there are two output nodes processed by policy head and value head). And I just return two results in one line like below:
`return policy, value`
Then I exported the model and there are '.json' for the architecture and '.params' for parameters.
After that, I use API in CPP to do inference, however, I can't get two different results trough setting different indexes in function
` int MXPredGetOutputShape(PredictorHandle handle,
                                   mx_uint index,
                                   mx_uint** shape_data,
                                   mx_uint* shape_ndim); `

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Question, C++]

**Comment by GeneZC** [comment]
The problem come out as I've used the parameters saved with `save_parameters()` instead of `export()` and I just used the model exported by `export()`
