### ISSUE TITLE
cuDNN 7.2 Tensor Core support

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#12463]
cuDNN 7.2 has simplified the usage of Tensor Cores for convolutions and RNNs, and explicit casts to `float16` can be avoided: https://devblogs.nvidia.com/tensor-ops-made-easier-in-cudnn/

Are there plans to expose this in MXNet already? If not, lets discuss a design in this issue.

@szha

**Comment by szha** [comment]
Hi @sbodenstein. Thanks for bringing this up and definitely we are interested in adding its support.

For the RNN part, I hijacked your previous issue #9543 and I brought up the same topic there :)

**Comment by sbodenstein** [comment]
@szha: any updates about this? Now that CUDA 10 and Turing GPUs are on sale (all with TensorCores), it would be very good to add support to make it easier to use TensorCores.
