### ISSUE TITLE
Documentation Inconsistent for Sparse Embedding symbol API

### ISSUE THREAD

**Issue by kalyc** [apache/incubator-mxnet#12465]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Hello, I am using the sparse Embedding symbol API. As per the [documentation here](https://mxnet.apache.org/api/python/symbol/sparse.html#mxnet.symbol.sparse.Embedding)

>>`mx.sym.Embedding(data, weight, input_dim, output_dim, sparse_grad=True)`

I get incorrect argument error for sparse_grad

The [documentation on the contrib API mentions that contrib.SparseEmbedding](https://mxnet.apache.org/api/python/symbol/contrib.html) has been deprecated and Embedding should be used instead - but it results in the above mentioned error 

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.2
Compiler     : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)
Build        : ('default', 'Jul 20 2017 13:14:59')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /anaconda2/envs/test/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.2.1
Directory    : /anaconda2/envs/test/lib/python3.6/site-packages/mxnet
Commit Hash   : 106391a1f0ee012b1ea38764d711e76774ce77e1
----------System Info----------
Platform     : Darwin-16.7.0-x86_64-i386-64bit
system       : Darwin
node         : 186590d284e1.ant.amazon.com
release      : 16.7.0
version      : Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID SMAP RDSEED ADX IPT FPU_CSDS'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0165 sec, LOAD: 0.5148 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0222 sec, LOAD: 0.2490 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0266 sec, LOAD: 0.2472 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0222 sec, LOAD: 0.4398 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0122 sec, LOAD: 0.4293 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0206 sec, LOAD: 0.1459 sec.
```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
`
 k_S = K.embedding(test_sparse_data, test_sparse_weight, 4, 5, sparse_grad=True)

tests/keras/backend/mxnet_sparse_test.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
keras/backend/mxnet_backend.py:89: in func_wrapper
    train_symbol = func(*args, **kwargs)
keras/backend/mxnet_backend.py:1213: in embedding
    sym = mx.sym.contrib.SparseEmbedding(data, weight=weight, input_dim=input_dim, output_dim=output_dim, deterministic=True, sparse_grad=sparse_grad)
<string>:105: in SparseEmbedding
    ???
/anaconda2/lib/python2.7/site-packages/mxnet/_ctypes/symbol.py:125: in _symbol_creator
    ctypes.byref(sym_handle)))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ret = -1

    def check_call(ret):
        """Check the return value of C API call.
    
        This function will raise an exception when an error occurs.
        Wrap every API call with this function.
    
        Parameters
        ----------
        ret : int
            return value from API calls.
        """
        if ret != 0:
>           raise MXNetError(py_str(_LIB.MXGetLastError()))
           MXNetError: Cannot find argument 'sparse_grad', Possible Arguments:
           ----------------
           input_dim : int, required
               Vocabulary size of the input indices.
           output_dim : int, required
               Dimension of the embedding vectors.
           dtype : {'float16', 'float32', 'float64', 'int32', 'uint8'},optional, default='float32'
               Data type of weight.
           deterministic : boolean, optional, default=0
               Force the backward gradient calculation to be executed based on a deterministic order at the cost of slower speed.
          , in operator _contrib_SparseEmbedding(name="", output_dim="5", input_dim="4", deterministic="True", sparse_grad="True")

/anaconda2/lib/python2.7/site-packages/mxnet/base.py:149: MXNetError
`

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)
Error can be reproduced by doing something [similar to this](https://github.com/apache/incubator-mxnet/blob/225f71f744ac5e7bd29868b6d3ba0e4fe2527c43/example/sparse/matrix_factorization/model.py#L30)

## What have you tried to solve it?

1. Using mxnet.contrib.SparseEmbedding() currently

Could you please let us know what is the right API definition and update the documentation accordingly?

**Comment by kalyc** [comment]
I upgraded the mxnet version by running `pip install mxnet --pre --upgrade` and the above error still persists. 

System Config - 
```
----------Python Info----------
Version      : 3.6.2
Compiler     : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)
Build        : ('default', 'Jul 20 2017 13:14:59')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /anaconda2/envs/test/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.3.0
Directory    : /anaconda2/envs/test/lib/python3.6/site-packages/mxnet
Commit Hash   : e290623f621ff0ca631b73b74c82956a83e77aea
----------System Info----------
Platform     : Darwin-16.7.0-x86_64-i386-64bit
system       : Darwin
node         : 186590d284e1.ant.amazon.com
release      : 16.7.0
version      : Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID SMAP RDSEED ADX IPT FPU_CSDS'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0133 sec, LOAD: 0.4970 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0243 sec, LOAD: 0.3365 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0398 sec, LOAD: 0.2375 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0398 sec, LOAD: 0.3687 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0119 sec, LOAD: 0.6777 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0193 sec, LOAD: 0.1858 sec.
```

I noticed that [changes were made to deprecate contrib.SparseEmbedding on May 7](https://github.com/apache/incubator-mxnet/blob/225f71f744ac5e7bd29868b6d3ba0e4fe2527c43/example/sparse/matrix_factorization/model.py) - they are somehow not reflecting in the latest PIP package.

**Comment by eric-haibin-lin** [comment]
Hi I cannot reproduce it with the following code:
```
pip list | grep mxnet
mxnet (1.3.0b20180826)
```
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> data = mx.sym.var('data')
>>> weight = mx.sym.var('weight')
>>> input_dim = 1
>>> output_dim = 1
>>> embed = mx.sym.Embedding(data, weight, input_dim, output_dim, sparse_grad=True)
>>> embed
<Symbol embedding0>
>>> embed = mx.sym.Embedding(data, weight, input_dim, output_dim, sparse_grad=False)
>>> embed
<Symbol embedding1>
```

**Comment by kalyc** [comment]
Hi, as discussed offline this requires upgrading to the latest version of mxnet v1.3 which I installed using `pip install mxnet --pre --upgrade` for both python2 and python3. Closing this issue at the moment - will wait for the new PIP package to be released to use this API with Keras.
