### ISSUE TITLE
nnvm submodule broken in release 1.2.1

### ISSUE THREAD

**Issue by lou-k** [apache/incubator-mxnet#12464]
## Description
It appears the nnvm (or it's tvm) submodule commit is no longer valid.

## Steps to reproduce
```
git clone --recursive --single-branch -b 1.2.1 https://github.com/apache/incubator-mxnet incubator-mxnet
```

Results in:
```
error: no such remote ref fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97
Fetched in submodule path '3rdparty/nnvm/tvm', but it did not contain fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97. Direct fetching of that commit failed.
```

## What have you tried to solve it?
I noticed that https://github.com/apache/incubator-mxnet/commit/8e4aeee6f0021d0c5a90fac0bda4631eac03e1cc looks related to this issue in `master`. 

Can we get a similar fix in the 1.2.1 release? I'd like to build the stable version instead of `master`.

**Comment by marcoabreu** [comment]
@srochel

**Comment by eric-haibin-lin** [comment]
There was a history rewrite in tvm repo which breaks this. 
The commit still exists in my fork https://github.com/eric-haibin-lin/tvm 
Could you add this as the remote and see if you can checkout that commit?

**Comment by lou-k** [comment]
@eric-haibin-lin yes your fork has the commit https://github.com/eric-haibin-lin/tvm/commit/fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97

**Comment by kalyc** [comment]
@lou-k is the issue still persisting? Could you close the issue if it has been fixed?

**Comment by eric-haibin-lin** [comment]
@Roshrini did we fix the v1.2.1 branch, too?

**Comment by Roshrini** [comment]
@eric-haibin-lin 1.2.0 branch was fixed, it tracks new branch of nnvm now. https://github.com/dmlc/nnvm/commit/0ca68e89ced69c0100aed32343cf30b45cafca7a

I think we can do same for 1.2.1 branch too, it can track https://github.com/dmlc/nnvm/tree/mx_1.2.0

**Comment by lou-k** [comment]
@kalyc yes this is still persisting

**Comment by lou-k** [comment]
@Roshrini as far as I can tell this issue exists for 1.2.0 as well:
```
git clone --recursive --single-branch -b 1.2.0 https://github.com/apache/incubator-mxnet incubator-mxnet
...
error: no such remote ref fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97
Fetched in submodule path '3rdparty/nnvm/tvm', but it did not contain fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97. Direct fetching of that commit failed.
```

**Comment by lou-k** [comment]
@kalyc I still see the same error with the same repo case:
```
git clone --recursive --single-branch -b 1.2.1 https://github.com/apache/incubator-mxnet incubator-mxnet
....
error: no such remote ref fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97
Fetched in submodule path '3rdparty/nnvm/tvm', but it did not contain fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97. Direct fetching of that commit failed.
Failed to recurse into submodule path '3rdparty/nnvm'
```
Perhaps you did not receive the error if you already had commit `fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97` in your local remote?

I decent workaround is to just download the release tarball for that version; no problems there.

I've since updated to 1.3.0, so this is no longer an issue for me. I'm closing the issue since (1) there is a workaround and (2) it seems there isn't a lot of need to checkout older versions from git.

**Comment by lou-k** [comment]
Oh and @kalyc thanks a bunch for checking in on it. Certainly nice to have someone working through old issues!

**Comment by zrss** [comment]
... oh, `v1.2.1` is left behind ... and it still turns out

```
git clone --recursive --single-branch -b 1.2.1 https://github.com/apache/incubator-mxnet incubator-mxnet
....
error: no such remote ref fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97
Fetched in submodule path '3rdparty/nnvm/tvm', but it did not contain fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97. Direct fetching of that commit failed.
Failed to recurse into submodule path '3rdparty/nnvm'
```

**Comment by eric-haibin-lin** [comment]
@zrss try this fork:  https://github.com/eric-haibin-lin/tvm

**Comment by zrss** [comment]
@eric-haibin-lin , thx ~ i have tried, it works

post here for ref

```
git clone https://github.com/eric-haibin-lin/tvm
cd tvm
git checkout fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97

cd {MXNET_HOME}
git submodule update --recursive --init
```
