### ISSUE TITLE
[Doc] No content for building from master source

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#12492]
Seems this page is not up-to-date: 
https://mxnet.incubator.apache.org/install/index.html&version=master#

Also, this page is a litte messy for me:
https://github.com/apache/incubator-mxnet/blob/master/docs/install/index.md

**Comment by vrakesh** [comment]
@TaoLv thank you for reporting the issue
@mxnet-label-bot [Doc]

**Comment by kalyc** [comment]
For the first document could you provide more context @TaoLv  - Build from Source on Master on what machine? I do see the [pages opening](https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Python&processor=CPU&version=master#) for building from source

**Comment by TaoLv** [comment]
@kalyc Seems it's already fixed by #12509 . I will close this issue now.
