### ISSUE TITLE
Onnx arange op not supported!

### ISSUE THREAD

**Issue by lizhen2017** [apache/incubator-mxnet#12497]
I'm using mxnet 1.3.0 and onnx 1.3, No conversion function registered for op type _arange yet, so the arange function have not been surported?

**Comment by vrakesh** [comment]
@lizhen2017 thank you for the question

@mxnet-label-bot [ONNX, Question]

**Comment by Roshrini** [comment]
@lizhen2017 thanks for reporting this issue. 
ONNX doesnt have specific "arange" operator. https://github.com/onnx/onnx/blob/master/docs/Operators.md
So, it's not yet supported with import and export with MXNet.

**Comment by kalyc** [comment]
@lizhen2017 could you please close this issue if your question has been addressed?
