### ISSUE TITLE
AddVersion.py breaks the site output in a variety of ways

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12524]
## Description

[AddVersion.py](https://github.com/aaronmarkham/incubator-mxnet/blob/b56da3cc32fee828c352f0bfb1f05e393ca58040/docs/build_version_doc/AddVersion.py#L77-L78) does some pretty aggressive website modifications just before publishing the full website. It was already known to break on the install page, and now it seems it is responsible for #12168 and #11438. I created a PR to fix this issue by commenting out this one line:
```
outstr = str(content).replace('&lt;', '<').replace('&gt;', '>')
```
But this ended up stopping the versions dropdown from appearing in the final website output. Having the versions dropdown is more important right now than fixing a couple of render issues, so I've submitted a patch that reverts this change along with an update for site consistency: #12426 

Browsing the intermediate outputs from this script, you can see things like `<span class="gp">>>> </span>`.  That's with the line enabled. More research is required to fix this script, so it produces valid html and doesn't break the code block's usage of xml or other tags the require > or <.

Tracking here as well:
https://issues.apache.org/jira/browse/MXNET-987

**Comment by kalyc** [comment]
Thanks for submitting the issue @aaronmarkham 
@mxnet-label-bot[Website, Build, Installation]

**Comment by kalyc** [comment]
@aaronmarkham is this issue still persisting?

**Comment by aaronmarkham** [comment]
Yes

**Comment by aaronmarkham** [comment]
New website launch makes this a moot issue.
