### ISSUE TITLE
caffeOp mxnet build failed

### ISSUE THREAD

**Issue by jacky4323** [apache/incubator-mxnet#12532]
Hi,

environment MXNet v1.0.0

I want to use caffe operator to implement some custom layers,such as the solution in mxnet/example/caffe/
I follow the install command described in https://mxnet.incubator.apache.org/faq/caffe.html, how to solve these problems?
1. git clone https://github.com/BVLC/caffe
2. cd caffe && wget https://github.com/BVLC/caffe/pull/4527.patch && git apply 4527.patch

thanks a lot !!

also if it has the cmake method for below configuration.
   CAFFE_PATH = $(HOME)/caffe
   MXNET_PLUGINS += plugin/caffe/caffe.mk

![image](https://user-images.githubusercontent.com/31586393/45429203-63981280-b6d5-11e8-9738-107f94cdc2ef.png)

**Comment by kalyc** [comment]
Thanks for submitting the issue @jacky4323 
Could you also provide your system config for us to be able to assist you better?

@mxnet-label-bot[Caffe Integration, Operator]

**Comment by jacky4323** [comment]
Hi @kalyc ,

system  config of my linux is showed below.
thanks for help!!

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Stepping:              4
CPU MHz:               2675.835
CPU max MHz:           4500.0000
CPU min MHz:           1200.0000
BogoMIPS:              6623.88
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              14080K
NUMA node0 CPU(s):     0-19
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req

**Comment by lanking520** [comment]
@jacky4323 Sorry for the waiting, I am taking over here to help you out. 
[I will update this comment here]

**Comment by jacky4323** [comment]
@lanking520  

OK , thanks for help!!

**Comment by jacky4323** [comment]
Hi @lanking520 

OK, thanks
Are there any plans to update MXNet interface project with Caffe?
some of the custom operators are in caffe for my project. 
Any help would be appreciated! thanks.

**Comment by lanking520** [comment]
@jacky4323 I have reached out to the slack channel of MXNet to see if this is possible. In the meantime, can you try to convert your Caffe model into ONNX and then to MXNet?  I saw you mentioned some custom operators and this may block this approach.

**Comment by lanking520** [comment]
Apart from that, did this help you out? https://discuss.mxnet.io/t/caffeop-mxnet-build-failed/2014

**Comment by safrooze** [comment]
I responded to the relevant question on Discuss: https://discuss.mxnet.io/t/caffeop-mxnet-build-failed/2014/2

Copying response for reference here:

Looks like the patch hasn't been maintained as Caffe has evolved. You should try to reset your branch head to an older node (I tried **rc3** tag) and then apply the patch. Once patch is applied, you can then rebase it on top of the main repo. The following commands will do the job (although I haven't compiled Caffe and even though re-base works without any issues, you may get some compilation errors):
```bash
cd caffe
git reset --hard rc3
wget https://github.com/BVLC/caffe/pull/4527.patch
git apply 4527.patch
git add -u
git commit -m "mxnet patch"
git rebase origin/master
```

**Comment by jacky4323** [comment]
@safrooze ,
I have tried it , the error is solved
unfortunately, When I use cmake to build mxnet, I met the problems below

in CMakeList.txt turn on Use Caffe Plugin
`mxnet_option(USE_PLUGIN_CAFFE     "Use Caffe Plugin" ON) `
`mkdir build/Release  && cd build/Release `
`cmake ../../ `

[CMakeError.log](https://github.com/apache/incubator-mxnet/files/2509111/CMakeError.log)
[console_error_log.txt](https://github.com/apache/incubator-mxnet/files/2509114/console_error_log.txt)

**Comment by safrooze** [comment]
Looks like the patch needs updating. Any chance you'd be interested in fixing the patch and pushing a PR to get your name as an MXNet contributor? :)

**Comment by jacky4323** [comment]
@safrooze Hi,

now I use an old mxnet package build with caffe, it works now!!
However, In my caffe operator which is only implemented custom_layer.cpp (there is no custom_layer.cu),
Can I set not compile Cuda with this custom operator?
When I use the command below, I get the error due to not implementing GPU mode(cuda file)
`mkdir build/Release && cd build/Release` 
`cmake ../../` 
`make -j8` 

![image](https://user-images.githubusercontent.com/31586393/47805275-e3f00100-dd71-11e8-9821-c099f81a7364.png)

**Comment by szha** [comment]
We are deprecating caffe converter
