### ISSUE TITLE
Failing nighty test: test_pixel2pixel (test_notebooks_single_gpu.StraightDopeSingleGpuTests)

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#12539]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTests_onBinaries/detail/NightlyTests_onBinaries/148/pipeline

```
FAIL: test_pixel2pixel (test_notebooks_single_gpu.StraightDopeSingleGpuTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/work/mxnet/tests/nightly/straight_dope/test_notebooks_single_gpu.py", line 255, in test_pixel2pixel

    assert _test_notebook('chapter14_generative-adversarial-networks/pixel2pixel')

AssertionError
```

**Comment by kalyc** [comment]
The test is not Flaky. 
This PR https://github.com/apache/incubator-mxnet/pull/12537 - reverts the change in the NDArrayIter

[WIP] PR - https://github.com/apache/incubator-mxnet/pull/12545 to capture edge case of empty label

**Comment by sandeep-krishnamurthy** [comment]
Resolving this issue as the change is reverted and tests are passing.
