### ISSUE TITLE
[Precision Problem] about the IRHeader when using pack and unpack

### ISSUE THREAD

**Issue by huyangc** [apache/incubator-mxnet#12544]
```
header = mx.recordio.IRHeader(0,[0,1],0,0)
print header.flag # 0
s = mx.recordio.pack(header, '')
header, _ = mx.recordio.unpack(s)
print header.flag # 2
```
The header.flag will be changed when the label is a list(according to the length of the list). is that a feature or bug?

**Comment by huyangc** [comment]
And another "Feature" here:
```
header = mx.recordio.IRHeader(2,[33511722.0, 33511805.0],1,0)
print header.label # [33511722.0, 33511805.0]
s = mx.recordio.pack(header,'')
h, _ = mx.recordio.unpack(s)
print h.label #  array([33511722., 33511804.], dtype=float32)
```

It is so wired that the label in header can change automatically.

Which takes me two days to debug my code. orz

**Comment by huyangc** [comment]
ok, after some digging into the source code, I figure it out. the code here
https://github.com/apache/incubator-mxnet/blob/225f71f744ac5e7bd29868b6d3ba0e4fe2527c43/python/mxnet/recordio.py#L338

using the np.float32, but somehow 33511805.0 this number will be changed when use such kind of dtype. change to np.float64 may solve the problem.

**Comment by huyangc** [comment]
And about the IRHeader. Document [here](https://mxnet.incubator.apache.org/api/python/io/io.html#mxnet.recordio.IRHeader) says that
> flag (int) – Available for convenience, can be set arbitrarily.

but in fact, it is really according to the label length.

**Comment by kalyc** [comment]
Thanks for submitting the issue @huyangc 
You can use discuss.mxnet.io for discussions on MXNet with the community

For your question could you please follow the format posted in the issue template for submitting the issue? Posting details about your dev environment will be helpful for us to debug as well.

**Comment by kalyc** [comment]
@mxnet-label-bot[Question]

**Comment by ThomasDelteil** [comment]
@huyangc indeed the issue is with the conversion from float64 to float32.

If you use instead:

```
header = mx.recordio.IRHeader(2,np.array([33511722.0, 33511805.0], 'float32'),1,0)
print(header.label) # [33511722.0, 33511805.0]
s = mx.recordio.pack(header, bytes("", "utf8"))
h, _ = mx.recordio.unpack(s)
print(h.label)
```
you get
```
[33511722. 33511804.]
[33511722. 33511804.]
```

**Comment by huyangc** [comment]
@ThomasDelteil Thanks, I need to use a nparray when construct an IRHeader.
Help a lot !

**Comment by HaoLiuHust** [comment]
@huyangc I also encounter the same problem, header.flag changed after pack, how to solve this?

**Comment by huyangc** [comment]
@HaoLiuHust you can change the type of irheader to be np.float64 and change the 4 to be 8 with pack and unpack will solve the problem

**Comment by huyangc** [comment]
But this can only solve the problem of too big of the digit but not the flag problem, I think the flag problem is because of the design.

**Comment by HaoLiuHust** [comment]
@huyangc yes, I have read the code too, if we want to use it as we want, we can write a custom pack and unpack

**Comment by SCZwangxiao** [comment]
This bug has not been solved even today !!!
The ``flag`` will change its value when the label is of ``str`` type. Specifically, when we use:
```python
header = mx.recordio.IRHeader(0,'2', idx, 0)
```
, and pack it to ``MXIndexedRecordIO``. After unpacking we will get ``flag=1``!
