### ISSUE TITLE
[Scala] [macOS] GPU / CUDA?

### ISSUE THREAD

**Issue by mariussoutier** [apache/incubator-mxnet#12547]
Hi,

wouldn't it be possible to offer a GPU version on the Mac as well? Nvidia already supports CUDA on the Mac.

**Comment by kalyc** [comment]
Thanks for submitting the issue @mariussoutier 
@mxnet-label-bot[Question, GPU, Mac, Scala]

**Comment by gigasquid** [comment]
Yes! That is on the list for improvements for Clojure/Scala as well. I think it's just a matter of putting in the right maven build profiles, it just needs some time and attention.

**Comment by mariussoutier** [comment]
@gigasquid Is it already possible to build MXNet from source for Mac with CUDA support?

**Comment by gigasquid** [comment]
Yes I believe so http://mxnet.incubator.apache.org/install/osx_setup.html
I would start and try to build from source with cuda. If the base package builds then it is just a matter of getting the pom.xml files for the scala architecture. If you have time to investigate, that would be awesome 😸

**Comment by mariussoutier** [comment]
I will try. Since MXNet doesn't work on Ubuntu and CPU-training is too slow, this would indeed be awesome.

**Comment by thomelane** [comment]
What issue were you having with MXNet on Ubuntu @mariussoutier? Check out AWS EC2 DLAMI for Ubuntu that has MXNet and CUDA pre-installed if you didn't want to configure yourself: see https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html.

**Comment by saudet** [comment]
The JavaCPP Presets for MXNet now bundle the Scala API and binaries for Mac and CUDA are also available on Maven Central too: https://github.com/bytedeco/javacpp-presets/tree/master/mxnet

Please let me know if you encounter any issues with those!

**Comment by lanking520** [comment]
@mariussoutier Currently, we made Scala available to use libmxnet.so directly. As long as you configured CUDA path correctly and build the .so file, you will be able to build scala package by doing `mvn package`

**Comment by lanking520** [comment]
@mariussoutier Close this issue for now. As long as you can configure CUDA path correctly, you will be able to build Scala on that.
