### ISSUE TITLE
installed MXNet problem for win10

### ISSUE THREAD

**Issue by Ian8888** [apache/incubator-mxnet#12562]
## Description
I installed the Mxnet GPU version but it's not working. 

>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())
[14:12:03] c:\jenkins\workspace\mxnet-tag\mxnet\src\imperative\./imperative_utils.h:76: GPU support is disabled. Compile MXNet with USE_CUDA=1 to enable GPU support.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AAA\Anaconda3\lib\site-packages\mxnet\ndarray\ndarray.py", line 2271, in ones
    return _internal._ones(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 34, in _ones
  File "C:\Users\AAA\Anaconda3\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\AAA\Anaconda3\lib\site-packages\mxnet\base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:12:03] C:\Jenkins\workspace\mxnet-tag\mxnet\src\imperative\imperative.cc:78: Operator _ones is not implemented for GPU.

## Environment info (Required)
Anaconda -> Python 3.6 version

Name: mxnet-cu92
Version: 1.2.1
Summary: MXNet is an ultra-scalable deep learning framework. This version uses CUDA-9.2.
Home-page: https://github.com/apache/incubator-mxnet
License: Apache 2.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:08:12_Central_Daylight_Time_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by kalyc** [comment]
Thanks for submitting the issue @Ian8888 
Have you tried MXNet V1.3?
@mxnet-label-bot[Windows, Installation]

**Comment by yajiedesign** [comment]
are you sure installed the mxnet-cu92?i will check build setting.

**Comment by Ian8888** [comment]
> Thanks for submitting the issue @Ian8888
> Have you tried MXNet V1.3?
> @mxnet-label-bot[Windows, Installation]

I using `pip install mxnet --upgrade --pre`  to update my MXNet V 1.3 is work now.
Thanks for your suggestion <3

**Comment by yajiedesign** [comment]
ok

**Comment by kalyc** [comment]
Thanks for the update @Ian8888 
Could you close this GitHub issue if it has been resolved?

**Comment by Ian8888** [comment]
> Thanks for the update @Ian8888
> Could you close this GitHub issue if it has been resolved?

Sorry, I forgot. 
Thanks for your reminded.
