### ISSUE TITLE
Test coverage report gets assigned to wrong commit

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#12564]
Due to the Jenkins merging strategy during our PR validation, CodeCov auto-assumes the wrong commit. In the default implementation, it will pick the commit of our master branch instead of the PRs commit. This means that the coverage report is associated with the wrong branch and thus the results scattered across the place and test coverage differences not properly revealed.

**Comment by kalyc** [comment]
@marcoabreu thanks for submitting the issue
@mxnet-label-bot[Test]
