### ISSUE TITLE
website search showing unavailable APIs

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12566]
## Description

Searching for `allreduce` while in the 1.0.0 version yielded a result:
http://mxnet.incubator.apache.org/versions/1.0.0/search.html?q=allreduce&check_keywords=yes&area=default

But this just dumps you off in the gluon docs at the top. Searching on master yields a correct result.

I recently worked on search, fixing some other bugs and tested that some APIs should not appear in old results. Could be the same issue or something new.

**Comment by kalyc** [comment]
Thanks for submitting the issue @aaronmarkham 
@mxnet-label-bot[Website, Bug]

**Comment by aaronmarkham** [comment]
I have a lead on the problem. Stay tuned.

**Comment by aaronmarkham** [comment]
I'm capturing this issue here for later followup: https://issues.apache.org/jira/browse/MXNET-998
As the issue isn't happening anymore and seems transient, I'm closing this.
