### ISSUE TITLE
mx.contrib.tensorrt.tensorrt_bind got a bad result!

### ISSUE THREAD

**Issue by lizhen2017** [apache/incubator-mxnet#12598]
Environment:mxnet-tensorrt-cu90 tensorrt 4.0, cuda9.0, cudnn 7.1 python3.5
(1)Inference with sym.simple_bind got right  detection result.
executor = sym.simple_bind(ctx=ctx, data=batch_shape, grad_req='null', force_rebind=True)
executor.copy_params_from(arg_params, aux_params)
(2) Inference with mx.contrib.tensorrt.tensorrt_bind got bad result
os.environ['MXNET_USE_TENSORRT'] = '1'
arg_params.update(aux_params)
all_params = dict([(k, v.as_in_context(mx.gpu(1))) for k, v in arg_params.items()])
executor = mx.contrib.tensorrt.tensorrt_bind(sym, ctx=mx.gpu(1), all_params=all_params,
                                                         data=batch_shape, grad_req='null', force_rebind=True)
(3)Inference with gluon got right detection result.
self.__model = gluon.nn.SymbolBlock(outputs=mx.sym.load(self.__symbol), inputs=mx.sym.var('data'))
 self.__model.load_parameters(self.__params, ctx=self.__ctx)
I don't know why.Thanks for your help! Will using tensort makes a lower accuracy?

**Comment by stu1130** [comment]
Thanks for submitting the issue @lizhen2017
@mxnet-label-bot[Bug]

**Comment by lupesko** [comment]
@KellenSunderland - can you take a look please?

**Comment by KellenSunderland** [comment]
@lizhen2017 Thanks for the report.  Would you be able to share the model you're working with?

**Comment by lizhen2017** [comment]
@KellenSunderland I implement a tiny-yolov3 network, the network inference well without trt api, and how can share the model?

**Comment by piyushghai** [comment]
@KellenSunderland @larroy bouncing...

**Comment by lupesko** [comment]
@mxnet-label-bot [TensorRT]

**Comment by KellenSunderland** [comment]
@lizhen2017 Sorry missed your question.  If you're using the symbol API you can save using https://mxnet.apache.org/api/python/symbol/symbol.html#mxnet.symbol.Symbol.save
