### ISSUE TITLE
cannot converge use the dcgan with mnist and cifar10 dataset?

### ISSUE THREAD

**Issue by pengxin99** [apache/incubator-mxnet#12612]
i use the dcgan.py to train dataset with mnist, after 25 epochs the netD`s performance pretty well , train acc is around 0.9, but the netG`s loss is a little high, and it looks like don`t converge 

below is netD loss and netG loss:
![d_and_g_loss](https://user-images.githubusercontent.com/28485566/45806511-d582e400-bcf3-11e8-9972-462bece22ccb.png)

**Comment by stu1130** [comment]
Thanks for submitting the issue @pengxin99 
@mxnet-label-bot [question, example]
You can also post the question here [link](https://discuss.mxnet.io/) to get more help from the community.

**Comment by ThomasDelteil** [comment]
@pengxin99 can you share qualitative example of images generated by your generator? Could you also share your full code?

**Comment by ThomasDelteil** [comment]
@pengxin99  qualitatively the images look pretty good, do you expect them to become better?

**Comment by pengxin99** [comment]
@ThomasDelteil Thanks, and I use the inception score mertic, it looks converge.
