### ISSUE TITLE
Version 1.3.0 doesn't work for me on Windows (cu92); 1.3.0b20180915 works fine

### ISSUE THREAD

**Issue by BrianHanechak** [apache/incubator-mxnet#12628]
## Description
When I install version 1.3.0, the Python process exits whenever I do any GPU operation. 1.3.0b20180915 works fine, however.

## Environment info (Required)

----------Python Info----------
Version      : 3.6.3
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('v3.6.3:2c5fed8', 'Oct  3 2017 18:11:49')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 18.0
Directory    : C:\Users\brianh\AppData\Local\Programs\Python\Python36\lib\site-packages\pip
----------MXNet Info-----------
Version      : 1.3.0
Directory    : C:\Users\brianh\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.17134-SP0
system       : Windows
node         : WLT006174
release      : 10
version      : 10.0.17134
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
Name
Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0160 sec, LOAD: 1.4461 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1440 sec, LOAD: 0.4679 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.2960 sec, LOAD: 0.4274 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0947 sec, LOAD: 0.6719 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0070 sec, LOAD: 0.2740 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0337 sec, LOAD: 0.0710 sec.

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)

I did not build this from the source. I installed it from pip, using the mxnet-cu92 version.

## Error Message:

There isn't an error message; the process just seems to exit

## Minimum reproducible example

import mxnet as mx
ctx = mx.gpu(0)
zeros = mx.nd.zeros((5, 5), ctx)

At this point, there's a pause, and then the Python process ends

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. From the command line, start a python process
2. Type in the lines under "minimum reproducible example"

## What have you tried to solve it?

1. I've tried downgrading my version of MxNet. Versions from 1.3.0b20180915 and back work fine, but 1.3.0 and the newest betas don't work.
2. I tried upgrading to Python 3.7 and that didn't help.
3. Downgrading to 1.3.0b20180915 does work (in both Python 3.6.3 and Python 3.7)

**Comment by stu1130** [comment]
Thanks for submitting the issue @BrianHanechak 
@mxnet-label-bot [Bug, Python]

**Comment by BrianHanechak** [comment]
Some additional information... we are seeing some event log entries. On my computer:

Faulting application name: python.exe, version: 3.6.3150.1013, time stamp: 0x59d3d3a3
Faulting module name: ucrtbase.dll, version: 10.0.17134.191, time stamp: 0x5db729cd
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x1e4c
Faulting application start time: 0x01d4516eaca6e8ca
Faulting application path: C:\Users\brianh\AppData\Local\Programs\Python\Python36\python.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 33c88217-8247-4c7c-a403-b2a44a145697
Faulting package full name: 
Faulting package-relative application ID: 

One of my coworkers is having the same problem with the CUDA 8.0 version, and his event log entries look a little different:

Faulting application name: python.exe, version: 3.7.150.1013, time stamp: 0x5b331a30
Faulting module name: libmxnet.dll, version: 0.0.0.0, time stamp: 0x5b9d1979
Exception code: 0x40000015
Fault offset: 0x000000000312a453
Faulting process id: 0x3778
Faulting application start time: 0x01d451d36b534bd2
Faulting application path: C:\Program Files\Python37\python.exe
Faulting module path: C:\Program Files\Python37\lib\site-packages\mxnet\libmxnet.dll
Report Id: ae543022-bdc6-11e8-ab77-6c3be50b7356

**Comment by yajiedesign** [comment]
ok i am find problem.

**Comment by lupesko** [comment]
Thank you @yajiedesign !
@BrianHanechak can you please confirm the issue was resolved and close it, or otherwise report the error again? Thanks!

**Comment by BrianHanechak** [comment]
I just updated to 1.3.1b20180927 and it seems to be resolved.

**Comment by BrianHanechak** [comment]
Thank you for tracking this down!
