### ISSUE TITLE
Conflicting documentation for RNN dropout

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#12629]
Current documentation on dropout in RNN layers / FusedRNN operator is a bit confusing to me: 
- mx.gluon.rnn.{LSTM,RNN,GRU}'s docstring (for example: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/rnn/rnn_layer.py#L359) state `If non-zero, introduces a dropout layer **on the outputs** of each RNN layer except the last layer.` and this is in line with the `unfuse()` method, which interleaves LSTMCells with DropoutCells, but skips it on the last layer: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/rnn/rnn_layer.py#L144.
- However, fused forward_kernel() uses mx.symbol.RNN, which itself documents dropout as follows: `p (float, optional, default=0) – Dropout probability, **fraction of the input** that gets dropped out at training time.`

I assume equivalence between fused and unfused RNN layers has been tested, so the implementation is probably fine, but one of the docstrings (probably mx.symbol.RNN) should probably be updated for clarity.

**Comment by stu1130** [comment]
Thank for submitting the issue @fhieber 
@mxnet-label-bot [question, example]
You can also post the question here [mxnet discussion](https://discuss.mxnet.io/) to get more help from the community.

**Comment by szha** [comment]
RNN operator doc needs fixing.

**Comment by szha** [comment]
@haojin2 is addressing this in #12541

**Comment by szha** [comment]
I fixed it in #13056
