### ISSUE TITLE
Sequence operators should allow different type for sequence length

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#12649]
Currently, Sequence operators (i.e. Sequence{Last,Mask,Reverse}) require sequence lengths and input data to have the same type, which doesn't seem necessary.

**Comment by stephenrawls** [comment]
FYI I created a PR for this issue: https://github.com/apache/incubator-mxnet/pull/13880

**Comment by szha** [comment]
It's now possible to use different type on index thanks to @stephenrawls's contribution.
