### ISSUE TITLE
Scala doc issue

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#12657]
Currently, the Scala API page is broken. Please check this [link](https://mxnet.incubator.apache.org/api/scala/docs/index.html#org.apache.mxnet.SymbolAPIBase). The format is wrongly represented

**Comment by lanking520** [comment]
@aaronmarkham I have looked into this. It seemed like the `<pre>` things messed up the parser. The reason we added that in the comments is to make it structural and not raising too much warnings. I tried to build doc without `<pre>` and it seemed to work. In this case, I suggest finding an alternative that Scala Parser will understand.

**Comment by aaronmarkham** [comment]
Maybe use [literal blocks](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks) in rst format instead?

**Comment by zachgk** [comment]
@lanking520 This was fixed in #13210 and can be closed

**Comment by lanking520** [comment]
@zachgk Thanks!
