### ISSUE TITLE
MXNet 1.3 on PyPI Cuda 9.1

### ISSUE THREAD

**Issue by tdomhan** [apache/incubator-mxnet#12684]
MXNet 1.3 on PyPI for Cuda 9.1 seems to only be build for windows. 
Looking at: https://pypi.org/project/mxnet-cu91mkl/1.3.0/#files
There are only versions for `mxnet_cu91mkl-1.3.0-1-py2.py3-none-win_amd64.whl` and `mxnet_cu91mkl-1.3.0-py2.py3-none-win_amd64.whl`. A version for `manylinux` is missing. The same is true for `mxnet-cu91`.

Indeed `pip install mxnet-cu91mkl` will install version `1.2.1.post1` and not `1.3` on Linux.

**Comment by vandanavk** [comment]
@mxnet-label-bot [Build, CUDA]

**Comment by zhreshold** [comment]
cuda9.1 is deprecated by Nvidia, so do us. If you have strong reason to stick with cuda9.1, let us know. Otherwise we recommend to upgrade cuda to 9.2 at least.

**Comment by piyushghai** [comment]
@tdomhan If you can try at use Cuda 9.2 for your use case, please let us know if that works for you. If it does, can we close this issue ?

**Comment by tdomhan** [comment]
thanks for confirming that this is about deprecating cuda 9.1. As I saw a version for windows, I assumed there was an issue with releasing the Linux version. In any case I will not use 9.1 with MXNet in this case. Closing the issue.
