### ISSUE TITLE
support fix_beta in sync_batchnorm operator

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#12728]
Add fix_beta parameter in sync_batchnorm. Related PR for adding in BatchNorm - https://github.com/apache/incubator-mxnet/pull/12625

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Looks like the PR for this got merged. 
Can you close this issue ? 

Thanks!

**Comment by kalyc** [comment]
@sandeep-krishnamurthy could you close this issue?
