### ISSUE TITLE
Example of RNN (incl. GRU/LSTM) with APIs defined in c_predict_api.h

### ISSUE THREAD

**Issue by Isa-rentacs** [apache/incubator-mxnet#12734]
## Description
With MXNet 1.3.0, RNN layers can be hybridized. I would like to use those hybridized RNN models from C-api (c_predict_api.h) but couldn't find an example.

## More details
I was looking at [an issue (How to use LSTM or GRU in C++ using c_predict_api.h?)](https://github.com/apache/incubator-mxnet/issues/8487) and in the answer:

>@xiaogehh currently the Gluon LSTM and GRU RNN layers cannot be hybridized but the work towards should be soon completed. You can track the effort here: #10873

I believe it's released as a part of MXNet 1.3.0, and now I would like to know how to use them from C++.
If we can have something like [the one for CNN](https://github.com/apache/incubator-mxnet/blob/d8984e836e1f04142912e366ca73e51a6b1c6353/example/image-classification/predict-cpp/image-classification-predict.cc) it would be very helpful.

**Comment by marcoabreu** [comment]
FYI: All C-APIs are considered internal APIs that don't follow semantic versioning. They are not intended for external use since they might change at any point in time. We got the Cpp-package which is enduser-facing, so this might rather be a feature request for the C++ package.

**Comment by vrakesh** [comment]
@mxnet-label-bot [Feature request]

**Comment by marcoabreu** [comment]
Sorry, I'm not familiar with the c API.

@lebeg @leleamol might be able to answer that question

**Comment by lebeg** [comment]
@Isa-rentacs In my understanding the implemented [RNN layer](https://github.com/apache/incubator-mxnet/pull/11482/files#diff-1aff5f9b61af7ed872118c7369d34d12R30) is implemented in python, so there would be no option to access it from the C API. Maybe this could be a feature request.

**Comment by Isa-rentacs** [comment]
Thanks @lebeg, I understood this is going to be a feature request. Before going forward, I would like to understand a little bit more.

In the [1.3.0 release note](https://github.com/apache/incubator-mxnet/releases/tag/1.3.0), it says:
>Now many dynamic networks that are based on Gluon RNN layers can now be completely hybridized, exported, and used in the inference APIs in other language bindings such as R, Scala, etc.

Do you mean C/C++ is not included in the languages that can import the exported model?

**Comment by leleamol** [comment]
@Isa-rentacs I have submitted the PR #13680 that demonstrates the usage of C++ API in running the inference on RNN models.

The C API are the internal APIs and are not meant for external consumption.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by Isa-rentacs** [comment]
Hi @leleamol, thank you for working on this, I've added several comments to your PR.

**Comment by leleamol** [comment]
The example is merged and available in the master. This issue can be closed.

**Comment by lanking520** [comment]
@Isa-rentacs As explained the PR merged, let's close this issue for now. Please feel free to reopen this thread if you observed more problems with that.
