### ISSUE TITLE
Copying code from the website also copies the prompts

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#12745]
## Description
When copying code using the Copy from Clipboard javascript on the website, it also is copying the prompt
Go to 1) http://mxnet.incubator.apache.org/install/index.htmlplatform=Linux&language=Python&processor=GPU
2) use the copy to Clipboard option to copy text it has copied,
`$ pip install mxnet-cu92` earlier the shell prompt was not copied to clipboard

## Environment info (Required): 
Mac OS/Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

@aaronmarkham could you please take a look

**Comment by nswamy** [comment]
👍 @LuckyPigeon  
Yes, your very welcome to submit a PR.  If you are interested in contributing to the website, I think @aaronmarkham can help you with some starter tasks.

**Comment by aaronmarkham** [comment]
Hi @LuckyPigeon - take a look at these website build instructions, so you can test your changes: https://cwiki.apache.org/confluence/display/MXNET/How+to+Build+the+Website
Please let me know if you need any help.

**Comment by ys2843** [comment]
Current `copycode.js` has several problems
1. mistakenly creates global variables
2. missing prompt mapping
3. the use of jquery tooltip does not work, because we are not loading jquery ui any more

I will rewrite this file and fix this prompt issue.
