### ISSUE TITLE
Nightly for Binaries failing and not caught

### ISSUE THREAD

**Issue by vishaalkapoor** [apache/incubator-mxnet#12743]
## Description
Nightly is failing with a ImportError: No module named 'prompt_toolkit.formatted_text' and is not being caught as a test failure as the test runner isn't executing any tests.

1) Fix import error
2) Make sure a test failure happens if the executor does not execute.

http://jenkins.mxnet-ci.amazon-ml.com/job/NightlyTestsForBinaries/job/master/93/console

**Comment by vishaalkapoor** [comment]
@marcoabreu @ThomasDelteil 
I'll put in a fix today.

**Comment by vrakesh** [comment]
@mxnet-label-bot [Build]

**Comment by vishaalkapoor** [comment]
Code merged. Closing issue.
