### ISSUE TITLE
Absence of randn function in Symbol API

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#12755]
As highlighted by @anirudhacharya in PR #12749 
There is an absence of `randn` function in [Symbol API](https://mxnet.incubator.apache.org/api/python/symbol/random.html) 

Is it a conscious omission?

**Comment by vrakesh** [comment]
@mxnet-label-bot [Question]

**Comment by piyushghai** [comment]
@ChaiBapchya You can also post this question on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
