### ISSUE TITLE
when use python3 to write recodeio, "can't concat str to bytes" will happen

### ISSUE THREAD

**Issue by HaoLiuHust** [apache/incubator-mxnet#12806]
for example there is a writeable rec,   
```
header-mx.recordio.IRHeader(0,[0,1],0,0)
s=mx.recordio.pack(header,'')#error will occur here
```

**Comment by piyushghai** [comment]
@HaoLiuHust You can also post this question on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.

Can you provide a more elaborate example which explains your query more ? 

@mxnet-label-bot [Question]

**Comment by HaoLiuHust** [comment]
how to reproduce: 
```
import mxnet as mx
header-mx.recordio.IRHeader(0,[0,1],0,0)
s=mx.recordio.pack(header,'')#error will occur here
```
the error finally occur in recordio.py, line340:
```
s=label.tostring()+s
```
since label.tostring() is a bytes in python3. when use python2, it will be ok

**Comment by rocinant** [comment]
change to s=mx.recordio.pack(header, b'') to solve the problem
