### ISSUE TITLE
[PYTHON] Unifies the Callback function

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#1280]
Currently `epoch_end_callback` and `batch_end_callback` have two types of interfaces, this make things like logging evaluation metric not compatible. The things presented to the callbacks are also somewhat limited.

I like the way R handles the problem, where an environment variable is passed, which basically is a map containing all the local variables in the scope, this issue is opened to see if anyone likes to move toward this direction, and take stab on proposing specification of function in this issue, and contribute the code

**Comment by tqchen** [comment]
related to #798

**Comment by lofrank** [comment]
And please also expose Accuracy info in epoch_end_callback, so we can save model only when accuracy gains.
