### ISSUE TITLE
No conversion function registered for op type Deconvolution yet

### ISSUE THREAD

**Issue by Mut1nyJD** [apache/incubator-mxnet#12807]
Hi I am using the latest official release of MXNET 1.3.1 I see this message when trying to convert my MXNet network to ONNX. My network consists of an encoder/decoder structure. The decoder using deconvolution layers.

As far as I know ONNX has a convolution transpose node so technically it should be possible.

**Comment by piyushghai** [comment]
@Mut1nyJD Thank you for posting your question. We will look into it.
@mxnet-label-bot [ONNX, Question]

**Comment by piyushghai** [comment]
@Mut1nyJD Seems like your request already has a work in progress PR : https://github.com/apache/incubator-mxnet/pull/12399. The work on this PR should be completed soon! 

@mxnet-label-bot [Feature Request]

**Comment by Mut1nyJD** [comment]
@piyushghai 

Great thank you for the update I'll keep an eye on the PR

**Comment by lupesko** [comment]
@Mut1nyJD feel free to close the issue, unless you have further questions. Thanks!
