### ISSUE TITLE
Installation error by pip in Anaconda environment

### ISSUE THREAD

**Issue by lumist** [apache/incubator-mxnet#12813]
I have already installed NVIDIA's driver and CUDA in Ubuntu 16.04. And when I activate Anaconda environment and use pip to install mxnet or mxnet-cu*, there is an installation error showing like this:
```
(base) inin-aasmc@ININ-Z640:~$ conda --version
conda 4.5.11
(base) x@x:~$ conda activate python35
(python35) x@x:~$ pip install mxnet
Collecting mxnet
  Could not find a version that satisfies the requirement mxnet (from versions: )
No matching distribution found for mxnet
```

I use 'pip install mxnet-cu92 -i https://pypi.tuna.tsinghua.edu.cn/simple/', there is still the same error as below. 
I tried Python 3.6.5, 3.5.6 and 2.7.15 in anaconda environment, and the version of pip is latest.
But if I use pip of original python which is installed before anaconda, it works.
```
(base) x@x:~$ pip2 install mxnet-cu92 -i https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting mxnet-cu92
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/78/f323d6f0de63120b5228bfbee5830dfeda8cd192f6fbb642661a633624fd/mxnet_cu92-1.3.0.post0-py2.py3-none-manylinux1_x86_64.whl (442.1MB)
    9% |███                             | 40.5MB 33.6MB/s eta 0:00:12
```

Are there problems in Anaconda? I'm quite confused.

**Comment by piyushghai** [comment]
@lumist Thanks for submitting your issue. 
You can also post this question on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.

@mxnet-label-bot [Installation, pip, Question]

**Comment by piyushghai** [comment]
@lumist Happy to hear that your issue is now resolved.

@sandeep-krishnamurthy Can this issue be closed as it has been resolved for the user ? 

Thanks!
