### ISSUE TITLE
incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:162:14: fatal error: cblas.h: No such file or directory

### ISSUE THREAD

**Issue by sahbiept** [apache/incubator-mxnet#12815]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(I want to install mxnet R package , I followed the instructions in the following site ( http://mxnet.incubator.apache.org/install/ubuntu_setup.html#install-the-mxnet-package-for-r), .but I get this error , I'm stuck a week ago now . I tried to modify the config.mk file by adding the following two lines: 
# the additional link flags you want to add
ADD_LDFLAGS =/opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/lib

# the additional compile flags you want to add
ADD_CFLAGS =/opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/include
)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```
I installed R 3.5.1 using anaconda using this command: conda create -n mro_env r-essentials mro-base

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:
> sessionInfo()
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/lib/R/lib/libRblas.so
LAPACK: /opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(In file included from /opt/Anaconda/Anaconda3-5.1.0/channel/linux-64/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/mkldnn/../concat-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_concat.cc:25:
/opt/Anaconda/Anaconda3-5.1.0/channel/linux-64/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:162:14: fatal error: cblas.h: No such file or directory
     #include <cblas.h>
              ^~~~~~~~~
compilation terminated.
make: *** [Makefile:463: build/src/operator/nn/mkldnn/mkldnn_act.o] Error 1
make: *** [Makefile:463: build/src/operator/nn/mkldnn/mkldnn_concat.o] Error 1.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.git clone --recursive https://github.com/apache/incubator-mxnet
2.cd incubator-mxnet
3. make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas

## What have you tried to solve it?

1.
2.

**Comment by piyushghai** [comment]
@sahbiept Thanks for reporting this issue.
Can you provide additional information about the environment by following these steps : 
```
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
```

This will help us to debug further.

@mxnet-label-bot [R, Installation, Pending Requester Info]

**Comment by ankkhedia** [comment]
@anirudhacharya Could you please take a look?

**Comment by anirudhacharya** [comment]
This error is not related to the R-package. The error is happening when he is trying to create the base .so file. 

@sahbiept can you please share the commit hash of the commit you are trying to build. Thanks.

@mxnet-label-bot [Build]

**Comment by sahbiept** [comment]
@piyushghai  thank you for your fast response, this the output of diagnose.py

----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 7.2.0
Build        : ('default', 'Mar 29 2018 18:21:58')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-4.15.0-34-generic-x86_64-with-debian-buster-sid
system       : Linux
node         : ben-Aspire-E5-575G
release      : 4.15.0-34-generic
version      : #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture :                          x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :                              Little Endian
Processeur(s) :                         4
Liste de processeur(s) en ligne :       0-3
Thread(s) par cœur :                    2
Cœur(s) par socket :                    2
Socket(s) :                             1
Nœud(s) NUMA :                          1
Identifiant constructeur :              GenuineIntel
Famille de processeur :                 6
Modèle :                                142
Nom de modèle :                         Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Révision :                              9
Vitesse du processeur en MHz :          800.080
Vitesse maximale du processeur en MHz : 3100,0000
Vitesse minimale du processeur en MHz : 400,0000
BogoMIPS :                              5424.00
Virtualisation :                        VT-x
Cache L1d :                             32K
Cache L1i :                             32K
Cache L2 :                              256K
Cache L3 :                              3072K
Nœud NUMA 0 de processeur(s) :          0-3
Drapaux :                               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.1851 sec, LOAD: 1.9129 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0935 sec, LOAD: 0.7190 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.3013 sec, LOAD: 1.6370 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1389 sec, LOAD: 2.2160 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0906 sec, LOAD: 2.5603 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.1360 sec, LOAD: 1.1642 sec.

**Comment by marcoabreu** [comment]
Can you please try installing lib-atlas-dev using apt?

**Comment by sahbiept** [comment]
it works for me when I typed : 
export PKG_CONFIG_PATH=/opt/Anaconda/Anaconda3-5.1.0/envs/mro_env/lib/pkgconfig/:$PKG_CONFIG_PATH

@ankkhedia  ; @piyushghai 
@anirudhacharya I want to know what are the  r package dependencies that I should install before installing mxnet R package ?

I have to do the same thing (installation of mxnet R package )  in this  server : 
[root@slzuyp0apa05 contrib]# cat /proc/version
Linux version 2.6.32-754.3.5.el6.x86_64 (sandman@node3res7) (gcc version 4.4.7 2                                                                                                                                                             0120313 (SuSE 4.4.7-23) (GCC) ) #1 SMP Wed Aug 15 01:10:56 EDT 2018
You have new mail in /var/spool/mail/root
[root@slzuyp0apa05 contrib]# cat /etc/issue
SLES Expanded Support platform release 6.10
Kernel \r on an \m

I have to do the installation in offline mode. what is the procedure that I must follow ?

**Comment by sahbiept** [comment]
@marcoabreu 

 have to do the same thing (installation of mxnet R package ) in this server :
[root@slzuyp0apa05 contrib]# cat /proc/version
Linux version 2.6.32-754.3.5.el6.x86_64 (sandman@node3res7) (gcc version 4.4.7 2 0120313 (SuSE 4.4.7-23) (GCC) ) #1 SMP Wed Aug 15 01:10:56 EDT 2018
You have new mail in /var/spool/mail/root
[root@slzuyp0apa05 contrib]# cat /etc/issue
SLES Expanded Support platform release 6.10
Kernel \r on an \m

I have to do the installation in offline mode. what is the procedure that I must follow ? The package imager is necessary for the installation of Mxnet ?

**Comment by ankkhedia** [comment]
@sahbiept You can follow the instructions here
https://mxnet.apache.org/install/index.html?platform=Linux&language=R&processor=CPU
I don't think that imager is required for mxnet installation.

**Comment by ankkhedia** [comment]
@sahbiept Did the solutions suggested above worked for you?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close this issue due to lack of activity.

@sahbiept Please feel free to re-open in case closed in error
