### ISSUE TITLE
how to prepare data for mxnet.io.NDArrayIter

### ISSUE THREAD

**Issue by qianguih** [apache/incubator-mxnet#1281]
Hi, there,
    I am a little confused about the usage of mxnet.io.NDArrayIter. I have read the documentation here.http://mxnet.readthedocs.org/en/latest/python/io.html#io-api-reference. It suggested to call it in this way:  
mxnet.io.NDArrayIter(data, label=data_label, batch_size=1, shuffle=False, last_batch_handle='pad') 

How should we store the training data in an array data and its label in an array data_label. 

Specifically, I want to train a Lenet for MNIST. So, I get a numpy array of size (60000,28,28) and another one of size (60000,1) for labels. How can I feed them to a mxnet model for training?

**Comment by piiswrong** [comment]
reshape to (60000, 784) and (60000, 1)

**Comment by qianguih** [comment]
thanks for your reply @piiswrong ! However, it shows this error after reshipped to (60000,784) and (60000,1)
Check failed: (dshape.ndim()) == (4) Input data should be 4D in batch-num_filter-y-x

Should we prepare a 4D array for the training data?

**Comment by piiswrong** [comment]
if you are feeding to conv layers, reshape to (60000, 1, 28, 28)

**Comment by qianguih** [comment]
Thanks for your suggestion! @piiswrong  

I tried to reshape the data array to (60000,1,28,28) and label array to (60000,1). And called this command to do the data load:

train=mx.io.NDArrayIter(data,label=data_label,batch_size=100)

And called this command to start the training:

model.fit(X=train)

But it returns this error:

Shape inconsistent, Provided = (100,1), Inferred shape=(100)

Also, I tried to 

Do you have any idea about how to solve this? Thanks!

**Comment by piiswrong** [comment]
reshape label to (60000,)

**Comment by qianguih** [comment]
I tried that too. But it didn't work. It reports:

mxnet.base.MXNetError: [09:43:02] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range

I also tried to reshape the label matrix to (60000,10). It reported a similar error as the previous one:

Shape inconsistent, Provided =(100, 10), inferred shape=(100)

**Comment by piiswrong** [comment]
I'll soon submit a fix for this. For now, try in softmax_output-inl.h:148, replace Shape1(dshape[0]) with Shape2(dshape[0], 1) and use label shape (60000, 1)

**Comment by piiswrong** [comment]
actually, this code works for me without any change:
```Python
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
fc2 = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 64)
act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
fc3 = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=10)
mlp = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
#mysoftmax = NumpySoftmax()
#mlp = mysoftmax(data=fc3, name = 'softmax')

# data

#train, val = mnist_iterator(batch_size=100, input_shape = (784,))
train=mx.io.NDArrayIter(np.zeros((60000, 784)),label=np.zeros((60000,)),batch_size=100)

# train

logging.basicConfig(level=logging.DEBUG)

model = mx.model.FeedForward(
    ctx = mx.cpu(), symbol = mlp, num_epoch = 20,
    learning_rate = 0.1, momentum = 0.9, wd = 0.00001)

model.fit(X=train)
```

**Comment by qianguih** [comment]
I tried a MLP model and it works fine. But problems arise in conv models. After replacing Shape1(dshape[0]) with Shape2(dshape[0], 1) in softmax_output-inl.h:148, do I need to re-compile mxnet to make it work?

**Comment by piiswrong** [comment]
You need to recompile. That's weird though. What's the full message for this error:
mxnet.base.MXNetError: [09:43:02] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range

**Comment by qianguih** [comment]
The full error message is:

[17:20:15] ./dmlc-core/include/dmlc/logging.h:215: [17:20:15] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mnist.py", line 87, in <module>
    batch_end_callback=mx.callback.Speedometer(batch_size))
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/model.py", line 656, in fit
    logger=logger, work_load_list=work_load_list, monitor=monitor)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/model.py", line 276, in _train_multi_device
    executor_manager.load_data_batch(eval_batch)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/executor.py", line 424, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/executor.py", line 305, in _load_data
    _load_general(batch.data, targets)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/executor.py", line 301, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/ndarray.py", line 236, in __getitem__
    return self._slice(in_slice.start, in_slice.stop)
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/ndarray.py", line 276, in _slice
    self.handle, start, stop, ctypes.byref(handle)))
  File "/auto/rcf-proj2/qh/qianguih/mxnet/mxnet_multi/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:20:15] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range

BTW, here is my codes.
[mnist.txt](https://github.com/dmlc/mxnet/files/92737/mnist.txt)

**Comment by qianguih** [comment]
Hi, @piiswrong , is it possible to feed 2d label array for mxnet in training? Basically, I get a data array with size (80000,224,224) and a label array with size (80000,1000). The thing is we can not reshape label array to (80000,1) because there may be multi "1" in each row, such as (0,1,0,0,1,0). Can we just feed the (80000,1000) label array to mxnet model using mxnet.io.NDArrayIter ?

**Comment by SumNeuron** [comment]
I also am confused about prepping data for MXNet.... (although this is more general)

Even the method you [recommend](https://mxnet.incubator.apache.org/architecture/note_data_loading.html)  is only talked about in theory and has no practical demonstration as to how one might convert say a CSV file to your format.

Also while you do have CSVIter it seems way to complex. Here are two lines from the [parameters](https://mxnet.incubator.apache.org/api/python/io.html#mxnet.io.CSVIter ):

```
- data_csv (string, required) – The input CSV file or a directory path.
- label_csv (string, optional, default='NULL') – The input CSV file or a directory path. If NULL, all labels will be returned as 0.
```

What is the difference between `data_csv` and `label_csv` besides one being optional? If I define both does the latter override the former? Why doesn't this have a `delim` parameter so you could just as easily handle TSV files? What if the file has a header? 

=
