### ISSUE TITLE
Navigation for Docs Broken

### ISSUE THREAD

**Issue by thomelane** [apache/incubator-mxnet#12828]
Often end up in state where documentation navigation is unresponsive.
Works when starting from https://mxnet.incubator.apache.org/api/python/index.html, but lots of  documentation links take you away from this page, and then the navigation doesn't work.

* See https://mxnet.incubator.apache.org/api/python/optimization/optimization.html.
* And try clicking on 'Gluon API'.
* Just gives https://mxnet.incubator.apache.org/api/python/optimization/optimization.html#gluon-api in address bar but doesn't change page.

**Comment by thomelane** [comment]
@mxnet-label-bot [Website, Doc]

**Comment by thomelane** [comment]
Already being tracked by @aaronmarkham [here](https://issues.apache.org/jira/browse/MXNET-1019)

**Comment by aaronmarkham** [comment]
@vdantu was working on this file: https://github.com/apache/incubator-mxnet/blob/master/docs/_static/js/auto_module_index.js
And noted a bug in it that can cause the page to go blank if you try to use the `:noindex:` directive in Sphinx. 
This js file also injects some stuff on the left nav bar and it seems awfully close to what we're seeing here with this bug. Maybe this clue will help reach a solution to this issue.

**Comment by thomelane** [comment]
@aaronmarkham reckon we could just add links to the headers in the markdown `docs/api/python/index.md`? Since the headers are getting added to the top level of the navigation tree.

So `## Autograd API` -> `## [Autograd API](autograd/autograd.md)`

Also, for Autograd and Contrib, there's nothing underneath so wonder if we wanted to avoid generating the tree at all, and just use headers?

**Comment by aaronmarkham** [comment]
@thomelane That's a great idea - did you try it or are you speculating? 
Generation of the tree is automatic, but then tampered with by a variety of client side hacks... so I'm reluctant. Each time I try untangling the mess 🍝  in the js, horrible 👹 things happen.

**Comment by IvyBazan** [comment]
@thomelane @aaronmarkham I tried the replacement described above and found that it didn't have any impact unless the tree generation for Autograd was also removed. However, this presented a new issue as removing the tree generation meant that the autograd.md page no longer had a TOC for navigating to the rest of the content. I tried a few other things like using automodule and tinkering with the autosummary options, but didn't have any luck getting closer to desired functionality.

**Comment by IvyBazan** [comment]
@thomelane @aaronmarkham I tried the replacement described above and found that it didn't have any impact unless the tree generation for Autograd was also removed. However, this presented a new issue as removing the tree generation meant that the autograd.md page no longer had a TOC for navigating to the rest of the content.

**Comment by aaronmarkham** [comment]
New website launch makes this a moot issue.
