### ISSUE TITLE
ERROR parameter summary of lstm layer

### ISSUE THREAD

**Issue by soeque1** [apache/incubator-mxnet#12844]
## Description
Error occurs when print_summary() related to lstm layer.

## Environment info (Required)

```
MXNet 1.3.1

Package used (Python/R/Scala/Julia):
Python

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

## Error Message:
(Paste the complete error message, including stack trace.)
```
IndexError                                Traceback (most recent call last)
<ipython-input-5-d356a40b32a2> in <module>
      1 mx.viz.print_summary(
      2     model(mx.sym.var('data')),
----> 3     shape={'data':shape}
      4 )

~/python/venv/ngram_detectors/lib/python3.6/site-packages/mxnet/visualization.py in print_summary(symbol, shape, line_length, positions)
    186                 if key in shape_dict:
    187                     out_shape = shape_dict[key][1:]
--> 188         total_params += print_layer_summary(nodes[i], out_shape)
    189         if i == len(nodes) - 1:
    190             print('=' * line_length)

~/python/venv/ngram_detectors/lib/python3.6/site-packages/mxnet/visualization.py in print_layer_summary(node, out_shape)
    132                         if key in shape_dict:
    133                             shape = shape_dict[key][1:]
--> 134                             pre_filter = pre_filter + int(shape[0])
    135         cur_param = 0
    136         if op == 'Convolution':

IndexError: tuple index out of range
```
## Minimum reproducible example
```
import mxnet as mx
model = mx.gluon.nn.HybridSequential()
with model.name_scope():
    model.add(mx.gluon.nn.Embedding(30, 10))
    model.add(mx.gluon.rnn.LSTM(20))
    model.add(mx.gluon.nn.Dense(5, flatten=False))

model.hybridize()
shape = (2,3)
mx.viz.print_summary(
    model(mx.sym.var('data')), 
    shape={'data':shape}
)
```

## What have you tried to solve it?

1. Add logic for lstm, RNN, and so on layers related to RNN
2. Add Exception for error

**Comment by lanking520** [comment]
@soeque1 Actually I tried to run your code and get some other error:
```
Traceback (most recent call last):
  File "/Users/bla/testEnv/testMX/testCNN/text_cnn.py", line 27, in <module>
    model.add(mx.gluon.rnn.LSTM(20))
  File "/Users/bla/testEnv/testMX/venv/lib/python2.7/site-packages/mxnet/gluon/nn/basic_layers.py", line 106, in add
    self.register_child(block)
  File "/Users/qingla/testEnv/testMX/venv/lib/python2.7/site-packages/mxnet/gluon/block.py", line 544, in register_child
    str(block), str(type(block))))
ValueError: Children of HybridBlock must also be HybridBlock, but LSTM(None -> 20, TNC) has type <class 'mxnet.gluon.rnn.rnn_layer.LSTM'>. If you are using Sequential, please try HybridSequential instead.
```

**Comment by thomelane** [comment]
Hi @soeque1,

You can now use `model.summary()` to get the summary.

```
import mxnet as mx
import numpy as np

model = mx.gluon.nn.HybridSequential()
with model.name_scope():
    model.add(mx.gluon.nn.Embedding(30, 10))
    model.add(mx.gluon.rnn.LSTM(20))
    model.add(mx.gluon.nn.Dense(5, flatten=False))

model.initialize()
data = np.random.randint(low=0, high=30, size=(2,3))
data = mx.nd.array(data)
model.summary(data)
```

@lanking520 what version of MXNet are you using? LSTMs weren't hybridizable before v1.3.

**Comment by ThomasDelteil** [comment]
You can use the `.summary()` method of your gluon block:

```python
import mxnet as mx
model = mx.gluon.nn.HybridSequential()
with model.name_scope():
    model.add(mx.gluon.nn.Embedding(30, 10))
    model.add(mx.gluon.rnn.LSTM(20))
    model.add(mx.gluon.nn.Dense(5, flatten=False))
​
model.initialize()
model.summary(mx.nd.ones((2, 3)))
```
```
--------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #
================================================================================
               Input                                      (2, 3)               0
         Embedding-1                                  (2, 3, 10)             300
              LSTM-2                                  (2, 3, 20)            2560
             Dense-3                                   (2, 3, 5)             105
================================================================================
Parameters in forward computation graph, duplicate included
   Total params: 2965
   Trainable params: 2965
   Non-trainable params: 0
Shared params in forward computation graph: 0
Unique parameters in model: 2965
--------------------------------------------------------------------------------
```

**Comment by lanking520** [comment]
> Hi @soeque1,
> 
> You can now use `model.summary()` to get the summary.
> 
> ```
> import mxnet as mx
> import numpy as np
> 
> model = mx.gluon.nn.HybridSequential()
> with model.name_scope():
>     model.add(mx.gluon.nn.Embedding(30, 10))
>     model.add(mx.gluon.rnn.LSTM(20))
>     model.add(mx.gluon.nn.Dense(5, flatten=False))
> 
> model.initialize()
> data = np.random.randint(low=0, high=30, size=(2,3))
> data = mx.nd.array(data)
> model.summary(data)
> ```
> @lanking520 what version of MXNet are you using? LSTMs weren't hybridizable before v1.3.

I use mxnet 1.2 and I think that could be the reason. @soeque1 Are you still facing the issue now?

**Comment by soeque1** [comment]
Thanks for your help in solving this problem. 

But, There are still some issues. This is not HybridSequential or Sequential.

```
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import HybridBlock, nn, rnn
class MyModel(gluon.HybridBlock):
    def __init__(self, vocab_size, num_embed, **kwargs):
        super(MyModel, self).__init__(**kwargs)
        with self.name_scope():
            self.embed = nn.Embedding(input_dim=vocab_size, output_dim=num_embed)
            self.lstm = rnn.LSTM(20)
            self.out = nn.Dense(2)  
    def hybrid_forward(self, F ,inputs):
        em_out = self.embed(inputs)
        lstm_out = self.lstm(em_out) 
        return(self.out(lstm_out))

model = MyModel(vocab_size =20, num_embed=50)

model.initialize(mx.init.Xavier())
model.hybridize()

mx.viz.print_summary(
    model(mx.sym.var('data')), 
    shape={'data':(1,30)}, #set your shape here
)

```
________________________________________________________________________________________________________________________
Layer (type)                                        Output Shape            Param #     Previous Layer                  
========================================================================================================================
data(null)                                          30                      0                                           
________________________________________________________________________________________________________________________
mymodel3_embedding0_fwd(Embedding)                  30x50                   0           data                            
________________________________________________________________________________________________________________________
mymodel3_lstm0_reshape0(Reshape)                                            0                                           
________________________________________________________________________________________________________________________
mymodel3_lstm0_reshape1(Reshape)                                            0                                           
________________________________________________________________________________________________________________________
mymodel3_lstm0_reshape2(Reshape)                                            0                                           
________________________________________________________________________________________________________________________
mymodel3_lstm0_reshape3(Reshape)                                            0                                           
________________________________________________________________________________________________________________________

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-d83349ac28a7> in <module>
     21 mx.viz.print_summary(
     22     model(mx.sym.var('data')),
---> 23     shape={'data':(1,30)}, #set your shape here
     24 )

~/python/venv/ngram_detectors/lib/python3.6/site-packages/mxnet/visualization.py in print_summary(symbol, shape, line_length, positions)
    186                 if key in shape_dict:
    187                     out_shape = shape_dict[key][1:]
--> 188         total_params += print_layer_summary(nodes[i], out_shape)
    189         if i == len(nodes) - 1:
    190             print('=' * line_length)

~/python/venv/ngram_detectors/lib/python3.6/site-packages/mxnet/visualization.py in print_layer_summary(node, out_shape)
    132                         if key in shape_dict:
    133                             shape = shape_dict[key][1:]
--> 134                             pre_filter = pre_filter + int(shape[0])
    135         cur_param = 0
    136         if op == 'Convolution':

IndexError: tuple index out of range

```

**Comment by thomelane** [comment]
You can use `.summary()` for this example too @soeque1 .

```python
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import HybridBlock, nn, rnn


class MyModel(gluon.HybridBlock):
    def __init__(self, vocab_size, num_embed, **kwargs):
        super(MyModel, self).__init__(**kwargs)
        with self.name_scope():
            self.embed = nn.Embedding(input_dim=vocab_size, output_dim=num_embed)
            self.lstm = rnn.LSTM(20)
            self.out = nn.Dense(2)
            
    def hybrid_forward(self, F ,inputs):
        em_out = self.embed(inputs)
        lstm_out = self.lstm(em_out) 
        return(self.out(lstm_out))

    
model = MyModel(vocab_size=20, num_embed=50)
model.initialize(mx.init.Xavier())
data = mx.nd.array(np.random.randint(low=0, high=20, size=(2,3)))
model.summary(data)
```

```
--------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #
================================================================================
               Input                                      (2, 3)               0
         Embedding-1                                  (2, 3, 50)            1000
              LSTM-2                                  (2, 3, 20)            5760
             Dense-3                                      (2, 2)             122
           MyModel-4                                      (2, 2)               0
================================================================================
Parameters in forward computation graph, duplicate included
   Total params: 6882
   Trainable params: 6882
   Non-trainable params: 0
Shared params in forward computation graph: 0
Unique parameters in model: 6882
--------------------------------------------------------------------------------
```

**Comment by lupesko** [comment]
@mxnet-label-bot [Question, Python]
@soeque1 kindly close the issue, or comment if you have additional questions. Thanks!
