### ISSUE TITLE
MXPredReshape always return -1

### ISSUE THREAD

**Issue by smarsuuuuuuu** [apache/incubator-mxnet#12858]
I tried to reshape the input shape but the function always returns -1.
<br>
Here is the output of MXGetLastError() 
> Check failed: x == default_ctx Input array is in gpu(0) while binding with ctx=cpu(0).
<br>

**I used the latest version of MXNet, and solved this problem.**

**Comment by piyushghai** [comment]
@smarsuuuuuuu Is this issue still persisting ? If not, I'd recommend closing this issue. Please feel free to re-open if closed in error. 

@lanking520 Can you close this issue ? 

Thanks.

**Comment by lanking520** [comment]
@smarsuuuuuuu Close the issue for now. Please feel free to reopen it if you are still facing the same problem
