### ISSUE TITLE
I have a error in python3.7.0 version 

### ISSUE THREAD

**Issue by cunjif** [apache/incubator-mxnet#12864]
I run `pip install mxnet` in anconda environment, and then run `python3 -m mxnet` 
or input `import mxnet as mx`, I receive a error message...QAQ
----system info----
OS: Deepin 15.7 unstable
Kernel: x86_64 Linux 4.15

----hardware info----
CPU: Intel Core i7-4790
GPU: intel
RAM: 1018MiB / 7866MiB

----python version----
Python 3.7.0  with anaconda3
pip 10.0.1 

run follow shell command in dde shell:
> python3 -m mxnet

error meesage:
> Segmentation fault: 11
> Stack trace returned 0 entries

**Comment by lanking520** [comment]
@cunjif this is weird to me. Have you tried building from source? Looks like you are using a distribution we are unsure it would support T.T.  Do you have more information about the error message? I recommend you to use a standard distribution from Ubuntu 14.04 and above.

@mxnet-label-bot please add [python, installation]

**Comment by cunjif** [comment]
> @cunjif this is weird to me. Have you tried building from source? Looks like you are using a distribution we are unsure it would support T.T. Do you have more information about the error message? I recommend you to use a standard distribution from Ubuntu 14.04 and above.
> 
> @mxnet-label-bot please add [python, installation]

It's have no this bug in python version3.6. Addition, I couldn't attain more message about this error QAQ, sorry.

**Comment by lanking520** [comment]
@cunjif I see, so your problem solved when you switch to Python 3.6?

**Comment by cunjif** [comment]
> @cunjif I see, so your problem solved when you switch to Python 3.6?

Right! QAQ

**Comment by lanking520** [comment]
ʕ •ᴥ•ʔ
