### ISSUE TITLE
RuntimeError: Cannot find the MXNet library.

### ISSUE THREAD

**Issue by eyildiz-ugoe** [apache/incubator-mxnet#12861]
## Description
I cannot install Mxnet Python binding due to the error thrown as shown below. 

## Environment info (Required)

----------Python Info----------
Version      : 3.5.2
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Nov 23 2017 16:37:01')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 18.1
Directory    : /usr/local/lib/python3.5/dist-packages/pip
----------MXNet Info-----------
Version      : 1.2.0
Directory    : /usr/local/lib/python3.5/dist-packages/mxnet
Commit Hash   : 297c64fd2ee404612aa3ecc880b940fb2538039c
----------System Info----------
Platform     : Linux-4.15.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : eren
release      : 4.15.0-34-generic
version      : #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Stepping:              7
CPU MHz:               2394.270
CPU max MHz:           3800,0000
CPU min MHz:           1200,0000
BogoMIPS:              6403.81
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0216 sec, LOAD: 0.4055 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1752 sec, LOAD: 0.7410 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0794 sec, LOAD: 0.2528 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0685 sec, LOAD: 0.7554 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0015 sec, LOAD: 0.5077 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0016 sec, LOAD: 0.8124 sec.

Package used (Python/R/Scala/Julia):
(I'm using ...) `Python3`

Compiler (gcc/clang/mingw/visual studio): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

MXNet commit hash:
fc9e70bf2d349ad4c6cb65ff3f0958e23a7410bf

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
```
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 59, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the MXNet library.
List of candidates:
/home/eren/mxnet/python/mxnet/libmxnet.so
/home/eren/mxnet/python/mxnet/../../lib/libmxnet.so
/home/eren/mxnet/python/mxnet/../../build/libmxnet.so
../../../libmxnet.so

```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. `sudo python3 setup.py install`

## What have you tried to solve it?

1. Added `/usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so` to `LD_LIBRARY_PATH` but didn't work.

**Comment by tribbloid** [comment]
I wonder how did you fix it? I encounter the same problem:
https://stackoverflow.com/questions/53384859/how-to-customise-files-being-copied-into-tmp-directory-when-running-a-local-pip

**Comment by Hwang64** [comment]
@tribbloid @eyildiz-ugoe how to solve this problem?

**Comment by Prologueyan** [comment]
@tribbloid @eyildiz-ugoe @Hwang64  have u solve this problem?

**Comment by schliffen** [comment]
I encountered the same problem, Has anyone solved it?

**Comment by szha** [comment]
This happens when the mxnet library build failed

**Comment by adamjstewart** [comment]
This might help others with the same problem: https://github.com/apache/incubator-mxnet/issues/15787#issuecomment-584759416

**Comment by Kashmira-ms** [comment]
I am facing the same issue. How to solve it?
