### ISSUE TITLE
Update mkl-dnn version for building from source

### ISSUE THREAD

**Issue by inglada** [apache/incubator-mxnet#12862]
When building from source with CMake, the compilation of mkl-dnn fails with gcc-8 because the version used in 3rdparty is too old. A bugfix for mkl-dnn was made recently (see https://github.com/intel/mkl-dnn/issues/283) and should solve the issue.
Thanks

**Comment by TaoLv** [comment]
Thanks for reporting this issue. A PR is planned to update MKL-DNN version in the next week. Hopefully that will resolve your problem. Please stay tuned for that.

**Comment by lanking520** [comment]
@mxnet-label-bot [MKLDNN, feature request]

**Comment by pengzhao-intel** [comment]
@inglada The MKLDNN is updated. Please help check if your issue is resolved. 
Feel free to let us know for any issues.

**Comment by inglada** [comment]
It seems to solve the issue. Thanks.
