### ISSUE TITLE
The API doc of mx.nd.arange doesn't explain infer_range

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12874]
As show [here](http://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.arange), the doc doesn't explain infer_range.

**Comment by lanking520** [comment]
@mxnet-label-bot please add [doc, python] here.
@aaronmarkham could you please amend the doc?

**Comment by aaronmarkham** [comment]
Sure, what's it do? :shrug:

**Comment by lanking520** [comment]
> Sure, what's it do? 🤷‍♀️

@aaronmarkham https://github.com/apache/incubator-mxnet/pull/12064 this one! LoL
