### ISSUE TITLE
CUDA 10 Support and Testing

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#12877]
Now that CUDA 10 and Turing GPUs are out, what are the plans for adding testing for CUDA 10 builds?

For example, we've had breakages with building MXNet with CUDA 10 on OSX (eg `MXImperativeInvoke` seems to cause corruption of NDArrays).

**Comment by lanking520** [comment]
@sbodenstein thanks for your issue. 
@szha @marcoabreu @larroy @lebeg to help you out.
@mxnet-label-bot please add [CUDA, CI, test] here

**Comment by szha** [comment]
The code for cuda 10 pip release is ready. We need to request to increase the size limit of mxnet-cu100/mxnet-cu100mkl pip packages to 600mb. @dstufft used to help us with these requests but I haven't heard from him yet. We may need to request this through github issues on pypa repo this time but I don't have enough time to drive this right now.

**Comment by universewill** [comment]
any update about this?

**Comment by universewill** [comment]
any update about this?

**Comment by tribbloid** [comment]
looks like this pypi is slow to respond, is there another release channel we can use?

**Comment by szha** [comment]
Unfortunately, no...

**Comment by lebeg** [comment]
https://github.com/apache/incubator-mxnet/pull/12850

**Comment by gerkulesov** [comment]
Are there any news about mxnet-cu100 pip release?

**Comment by szha** [comment]
@yajiedesign opened an issue and it's currently sitting in https://github.com/pypa/warehouse/issues/4986
Given that, I'm going to start publishing the build artifacts also to s3 bucket, so that at least people can get access while we resolve the size limit.

**Comment by szha** [comment]
I've been working towards an event recently so unfortunately, I haven't got to this yet. I will try to find some cycles on this around 12/3

**Comment by gerkulesov** [comment]
Upload limit for mxnet-cu100 and mxnet-cu100mkl [was increased](https://github.com/pypa/warehouse/issues/4986#issuecomment-442898420) on PyPI!

**Comment by szha** [comment]
CUDA10 are being published now.
