### ISSUE TITLE
Many API documentations are missing. 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#12873]
See https://mxnet.incubator.apache.org/api/python/io/io.html 

The API doc for the following classes are missing: 
```
io.NDArrayIter
io.CSVIter 
io.LibSVMIter
io.ImageRecordIter
io.ImageRecordUInt8Iter
io.MNISTIter
```

**Comment by anirudhacharya** [comment]
Duplicate issue - https://github.com/apache/incubator-mxnet/issues/12854

**Comment by aaronmarkham** [comment]
The APIs appear on the new site.
