### ISSUE TITLE
What is the license for Saving and Loading Gluon Models?

### ISSUE THREAD

**Issue by rozaliyaeverstova** [apache/incubator-mxnet#12870]
## Description
(Brief description of the problem in no more than 2 sentences.)
I found this tutorial: https://mxnet.incubator.apache.org/tutorials/gluon/save_load_params.html 
What is the license for the code?

**Comment by szha** [comment]
All code in mxnet repo, unless otherwise stated, is under apache 2.0.

**Comment by lanking520** [comment]
@mxnet-label-bot [Question]

**Comment by ankkhedia** [comment]
@rozaliyaeverstova It seems that your question got answered
@sandeep-krishnamurthy Could you please close the issue

@rozaliyaeverstova Please feel free to reopen if closed in error.
