### ISSUE TITLE
Take operator doc is broken on the website

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#12888]
<img width="635" alt="screen shot 2018-10-20 at 11 12 58 am" src="https://user-images.githubusercontent.com/5545640/47259061-29026200-d459-11e8-9f83-0190f005c713.png">

**Comment by Roshrini** [comment]
This issue seems to be already fixed. @eric-haibin-lin Can you once check https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.take and close the issue?
