### ISSUE TITLE
[MKLDNN] Performance on Windows - Upgrading MKLDNN submodule?

### ISSUE THREAD

**Issue by masahi** [apache/incubator-mxnet#12891]
Hi, I tried MXNet + MKLDNN on AVX 512 capable Windows machine, but performance was terrible. I noticed that MKLDNN pulled by mxnet is quite old, and older version of MKLDNN does not enable OpenMP on Windows (omp support was added in [this commit](https://github.com/intel/mkl-dnn/pull/260)). 

Do you have a plan to upgrade MKLDNN version?

**Comment by pengzhao-intel** [comment]
Yes, we file PR in the next week.

**Comment by masahi** [comment]
Great! Thanks for the quick reply.

**Comment by pengzhao-intel** [comment]
@masahi updated, please double check if your issue is fixed :)

**Comment by masahi** [comment]
yes, I tried that PR before it was merged. Performance is good now.
