### ISSUE TITLE
The markdown of installation page partly doesn't work

### ISSUE THREAD

**Issue by JiaxiangBU** [apache/incubator-mxnet#12892]
In the [installation](https://mxnet.incubator.apache.org/install/index.html?platform=MacOS&language=R&processor=CPU) page, the markdown fails for the choice (Mac, R, CPU). Here is the screenshot.

![](http://p24kaozv6.bkt.clouddn.com/mxnetinstallation.png)

**Comment by lanking520** [comment]
@JiaxiangBU thank you for letting us know. @aaronmarkham could you please check the reason for this? I got the same output as shown above.
@mxnet-label-bot please add [doc, R]

**Comment by aaronmarkham** [comment]
Looks like the Docker instructions broke the page as these Docker instructions are showing up in the Windows --> Python --> CPU --> Build from Source block. And build from source isn't appearing as expected. Snowball effect... as the R stuff comes after that Docker section.
http://34.201.8.176/versions/install_macos_r_fix/install/index.html?platform=Windows&language=Python&processor=CPU

There looks to be a variety of spots where things are not being encoded properly. Wish we could get rid of this selector.... but I'll see if I can fix it.
