### ISSUE TITLE
Gradient of BatchNorm layer

### ISSUE THREAD

**Issue by x110** [apache/incubator-mxnet#12899]
I have a network consisting only of a batchnorm layer. The gradient that I get for batchnorm0_gamma after running a backward pass is different than the one I computed manually.
Please advise.
```

    import mxnet as mx
    import numpy as np
    X  = mx.nd.array([[ 0.18527887],[-1.23678724]])
    Y = mx.nd.array([[ 2.57767984],[-1.55019435]])
    #define network
    source = mx.sym.Variable("data")
    target = mx.sym.Variable("softmax_label")
    network = mx.sym.BatchNorm(source)
    network=mx.sym.LinearRegressionOutput(network,target)
    input_shapes = {'data': (2, 1), 'softmax_label': (2, 1)}
    exe = network.simple_bind(ctx=mx.cpu(), **input_shapes)
    arg_arrays = dict(zip(network.list_arguments(), exe.arg_arrays))
    x = arg_arrays['data']
    t = arg_arrays['softmax_label']
    #forward pass
    x[:] = X
    t[:] = Y
    y = exe.forward(is_train=True)
    #backwardpass
    exe.backward()
    exe.grad_dict['batchnorm0_beta'],exe.grad_dict['batchnorm0_gamma']

```
The output I get is: 
( [-1.0274856] &lt;NDArray 1 @cpu(0)&gt;, [0.] &lt;NDArray 1 @cpu(0)&gt;)

When calculating the gradient manually, the output i get is:
```

    xi = x.asnumpy()
    a = np.mean(xi)
    b = np.var(xi)
    xn = (xi-a)/np.sqrt(b+1e-5)
    beta, alpha = exe.arg_dict['batchnorm0_beta'].asnumpy(),exe.arg_dict['batchnorm0_gamma'].asnumpy()
    ynorm = alpha * xn+beta
    #backwardpass manually
    2*np.mean((ynorm-t.asnumpy())),2*np.mean((ynorm-t.asnumpy())*xn)

```
(-1.0274856090545654, -2.127872943878174)

The first gradient is same but the second is not.

**Comment by x110** [comment]
In the documentation of batchnorm, I found:
`Both gamma and beta are learnable parameters. But if fix_gamma is true, then set gamma to 1 and its gradient to 0.`

Why is` fix_gamma=True` the default behavior?

**Comment by x110** [comment]
In the documentation of batchnorm, I found:
`Both gamma and beta are learnable parameters. But if fix_gamma is true, then set gamma to 1 and its gradient to 0.`

Why is fix_gamma=True the default behavior?

**Comment by lanking520** [comment]
@x110 Hi your issue is more like a question, please send a post to https://discuss.mxnet.io/ for better support on the usage of MXNet, thank you!

@mxnet-label-bot please add label [Question, python, operator]

**Comment by x110** [comment]
For anyone else wondering `fix_gamma=True` is used when the next layer is linear (also relu) because then the scaling can be done by that layer.

**Comment by lanking520** [comment]
Thank you!
