### ISSUE TITLE
Website build times out

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#12900]
The website build timeout out and failed. This only happened once.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-website-build/detail/restricted-website-build/537/pipeline

```
+ '[' 1.0.0 '!=' 0.11.0 ']'

+ '[' -d VersionedWeb/versions/1.0.0 ']'

+ echo 'The 1.0.0 is going to be updated with new css and install pages.'

+ update_mxnet_css 1.0.0

+ tag=1.0.0

+ echo 'Begin update fixes..'

+ echo 'Copying mxnet.css from artifacts folder...'

The 1.0.0 is going to be updated with new css and install pages.

Begin update fixes..

Copying mxnet.css from artifacts folder...

+ cp artifacts/mxnet.css VersionedWeb/versions/1.0.0/_static

+ echo 'Update fixes complete..'

+ '[' 1.0.0 == master ']'

+ file_loc=VersionedWeb/versions/1.0.0

Update fixes complete..

+ '[' 1.0.0 == master ']'

+ for tag in '$tag_list'

+ python AddVersion.py --root_url http://mxnet.incubator.apache.org/ --file_path VersionedWeb/versions/0.12.1 --current_version 0.12.1 --tag_default master

Sending interrupt signal to process

build.py: 2018-10-19 02:18:30,178 Signal 15 received, cleaning up...

build.py: 2018-10-19 02:18:30,178 Cleaning up containers

Terminated

script returned exit code 143
```

@aaronmarkham

**Comment by lanking520** [comment]
Err. @aaronmarkham have you faced anything like this before? Does this look like an internet connection issue?

@mxnet-label-bot please add label [CI, doc, build]

**Comment by aaronmarkham** [comment]
I can't even use the Jenkins dashboard, let alone this log file. The page times out.
Looking at the error code, it is SIGTERM and Jenkins docs lists this as "The process was explicitly killed by somebody wielding the kill program." In this case, I'm guessing we hit the timeout.

Maybe it is temporary, but the fact that the dashboard is very slow to load and you can't load logs at all means maybe something is going on with the master server.

**Comment by aaronmarkham** [comment]
Transient issue. I recommend closing this and reopening if it becomes a problem. Then we'll need to increase the timeout value.

**Comment by marcoabreu** [comment]
Just to clarify: This was not a valid timeout but rather a total hang. Increasing the timeout wouldn't have helped

**Comment by piyushghai** [comment]
@aaronmarkham Have we seen this issue again ? If not we can close this issue. 
@marcoabreu Please feel free to re-open if closed in error.

@lanking520 Can you close this issue ?

Thanks

**Comment by lanking520** [comment]
Close the issue for now. Please feel free to reopen it if you are still facing the problem
