### ISSUE TITLE
Fixing Weight Decay Regularization in Adam

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#12916]
MXNet should implement this paper: https://arxiv.org/pdf/1711.05101.pdf

**Comment by anirudhacharya** [comment]
@eric-haibin-lin this is already being tracked here - https://github.com/apache/incubator-mxnet/issues/9881#issuecomment-397769492

**Comment by eric-haibin-lin** [comment]
i want to make an explicit feature request since the previous one is a discussion of the inconsistent api
