### ISSUE TITLE
Gluon model zoo docs duplicate ID

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12935]
## Description
Docs build on the [Gluon Python API's model zoo page](https://github.com/apache/incubator-mxnet/blob/master/docs/api/python/gluon/model_zoo.md) throws a severe error.

## Error

```
/home/ubuntu/incubator-mxnet/docs/api/python/gluon/model_zoo.md:403: SEVERE: Duplicate ID: "module-mxnet.gluon.model_zoo.vision".
```
## Comments

There's a workaround:
https://stackoverflow.com/questions/16471032/how-do-i-avoid-severe-duplicate-id-warnings-for-my-autodocd-modules-in-sphin
However, when implementing the `:noindex:` workaround, the page breaks and will not render.

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [gluon,doc]
