### ISSUE TITLE
optimizer doc error

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12938]
## Description
Sphinx throws an error on `optimizer` docs.

## Error
```
/home/ubuntu/incubator-mxnet/python/mxnet/optimizer/__init__.py:docstring of mxnet.optimizer.LBSGD:19: ERROR: Unexpected indentation.
```

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [Optimizer,doc]

**Comment by vdantu** [comment]
@aaronmarkham : Is this a duplicate of https://github.com/apache/incubator-mxnet/issues/13030 ?

**Comment by aaronmarkham** [comment]
Yes, it looks like it.
