### ISSUE TITLE
initializer.InitDesc docs error

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12939]
## Description
Sphinx throws an error on `initializer.InitDesc`.

## Error

```
/home/ubuntu/incubator-mxnet/python/mxnet/initializer.py:docstring of mxnet.initializer.InitDesc:4: SEVERE: Unexpected section title.
```

**Comment by aaronmarkham** [comment]
It also throws this error:

```
/home/ubuntu/incubator-mxnet/python/mxnet/initializer.py:docstring of mxnet.initializer.Initializer.set_verbosity:5: ERROR: Undefined substitution referenced: "x".
```

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [doc]

**Comment by aaronmarkham** [comment]
Notes on `ERROR: Undefined substitution referenced`:

## Undefined substitution reference error

```
ERROR: Undefined substitution referenced: "x".
```

In some math examples, people will use `|var|` to express the absolute value of something. The usage of pipes around a name is special to Sphinx and triggers a substitution of that value for something that is defined in the doc later. Switching to actual code or escaping the math can fix this.

```
            absolute value str((-|--x--|-/size(x)).asscalar()).
            absolute value str((*abs(x**)*/size(x)).asscalar()).
```

An inline literal would work too:
```
            absolute value str((-|--x--|-/size(x)).asscalar())-.-
            ``absolute value str((|*x|*/size(x)).asscalar())``
```
Or a regular block would work:
```
"""
Some description ::

    absolute value str((|*x|*/size(x)).asscalar())

Where you made sure there were line breaks before and after the indented code block 
```

Or a `code-block` should work:
```
    .. code-block:: python

       absolute value str((|*x|*/size(x)).asscalar())

```
