### ISSUE TITLE
docs incorrectly cross-linking gluon.Constant and initializer.Constant

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12944]
## Description

Sphinx is throwing a warning that `gluon.Constant` and `initializer.Constant` are getting mixed up.

## Error
```
/home/ubuntu/incubator-mxnet/python/mxnet/gluon/__init__.py:docstring of mxnet.gluon.ParameterDict.get_constant:None: WARNING: more than one target found for cross-reference u'Constant': mxnet.gluon.Constant, mxnet.initializer.Constant
```

## Comments
Refer to https://github.com/apache/incubator-mxnet/pull/12871 for a guide on how to resolve this kind of issue.

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [Gluon,doc]

**Comment by aaronmarkham** [comment]
@mxnet-label-bot [Good First Issue]
