### ISSUE TITLE
How to use own mxnet cuda operator in gluon?

### ISSUE THREAD

**Issue by jiangzhengkai** [apache/incubator-mxnet#12959]
Hi, can anyone tell how to use mxnet op in gluon code?

**Comment by harshp8l** [comment]
For questions, we would also like for you to please submit on the MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow others to learn as well.

**Comment by harshp8l** [comment]
@mxnet-label-bot add [question, CUDA, Gluon]

**Comment by safrooze** [comment]
Have you added your own operator to MXNet CPP code? If so and your operator is accessible through `nd.my_op`, then you can just call it within Gluon.

**Comment by jiangzhengkai** [comment]
@safrooze Thanks, i will try
