### ISSUE TITLE
load 2 data-sets in a same order

### ISSUE THREAD

**Issue by 729009982** [apache/incubator-mxnet#12973]
Hi.
    I am writing to load 2 data-set by VOCDetection from gluoncv ,But I want to read 2 data-sets (same num,size) in a same order .Due to the shuffle strategy ,I can not ensure that. 
And I want to know if I fix the random seed would works.
If works,and whether or not  this solution would heart the performance.

  What should I do ? Thank you for your time. :slight_smile:

**Comment by andrewfayres** [comment]
Hi @729009982 

We recommend that you submit questions to the MXNet discussion forum (https://discuss.mxnet.io). You'll get a wider audience and it helps other people learn too.

@mxnet-label-bot [gluon, question]

**Comment by ThomasDelteil** [comment]
@nswamy @sandeep-krishnamurthy @indhub can we close the issue? Thanks!
