### ISSUE TITLE
How to reduce memory in Gluon? 

### ISSUE THREAD

**Issue by jiangzhengkai** [apache/incubator-mxnet#12979]
We can use attr={'force_mirroring': 'True'} in mxnet symbol to reduce gpu memory. How can we reduce memory in gluon?

**Comment by safrooze** [comment]
Are you hybridizing? If so, you can always set the same set of attributes on you operators as in hybridized mode F is basically sym.

**Comment by safrooze** [comment]
@mxnet-label-bot [gluon, question]

**Comment by jiangzhengkai** [comment]
@safrooze Thanks
