### ISSUE TITLE
python3.6 pip package for CUDA 9.1 MKL no longer updated?

### ISSUE THREAD

**Issue by jsedoc** [apache/incubator-mxnet#12991]
Hi, it doesn't look like for Linux that there is a MxNet Python 3.6 pip package since right before 1.3.0.post0. Is this intentional?

$ pip install mxnet-cu91mkl==1.3.0.post0
Collecting mxnet-cu91mkl==1.3.0.post0
  Could not find a version that satisfies the requirement mxnet-cu91mkl==1.3.0.post0 (from versions: 1.0.0.post4, 1.0.1b20180123, 1.0.1b20180127, 1.0.1b20180205, 1.1.0b20180212, 1.1.0, 1.2.0b20180318, 1.2.0b20180324, 1.2.0b20180329, 1.2.0b20180407, 1.2.0b20180413, 1.2.0b20180420, 1.2.0b20180426, 1.2.0b20180503, 1.2.0b20180509, 1.2.0b20180516, 1.2.0b20180523, 1.2.0, 1.2.1.post1, 1.3.0b20180529, 1.3.0b20180605, 1.3.0b20180612, 1.3.0b20180619, 1.3.0b20180626, 1.3.0b20180801, 1.3.0b20180802, 1.3.0b20180803, 1.3.0b20180805, 1.3.0b20180807, 1.3.0b20180809, 1.3.0b20180810, 1.3.0b20180811, 1.3.0b20180814, 1.3.0b20180816, 1.3.0b20180818, 1.3.0b20180819, 1.3.0b20180820)
No matching distribution found for mxnet-cu91mkl==1.3.0.post0

**Comment by andrewfayres** [comment]
@mxnet-label-bot [python, pip]

**Comment by szha** [comment]
Yes, we discontinued support for cu91 versions in 1.3. For current support status see #8671
