### ISSUE TITLE
Image API docs error

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13007]
## Description
Sphinx throws an error when generating the Image API docs.

## Error
```
/home/ubuntu/incubator-mxnet/docs/api/python/image/image.md:2: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by frankfliu** [comment]
@mxnet-label-bot [Doc]

**Comment by anirudhacharya** [comment]
In this page - http://mxnet.incubator.apache.org/api/python/io/io.html the links to 
- mxnet.io
- mxnet.recordio
- mxnet.image 

are linking to the wrong destinations. I am not sure if it is related to the error reported in this issue. Just bringing it to your attention.

**Comment by anirudhacharya** [comment]
click on mxnet.image and you will see it goes to the wrong place.
