### ISSUE TITLE
Feature request: numpy.cumsum

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#13001]
MXNet equivalence of numpy.cumsum https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.cumsum.html?highlight=cumsum#numpy.cumsum

**Comment by szha** [comment]
`cumsum` is needed when you have an array of lengths with which to slice another concatenated array, and you want to calculate the start and end index to use. For example, suppose you have three arrays of different lengths, and you concatenated them like:
`[1, 2, 3], [4, 5], [6, 7, 8, 9] => [1, 2, 3, 4, 5, 6, 7, 8, 9]`
Their corresponding lengths are `[3, 2, 4]`.
The `cumsum` would be `[3, 5, 9]`, with which you can slice `[0, 3)` for first array, `[3, 5)` for second array, and `[5, 9)` for third array.

**Comment by tsuberim** [comment]
I'd really like to have this function for computing returns of rewards in the context of reinforcement learning.

**Comment by MyYaYa** [comment]
Yeah, if ndarray supports cumsum operation, some custom metrics(i.e. mAP) will benefit from that.

**Comment by MyYaYa** [comment]
`step = lambda data, state : (data + state[0], state[0] + data)
data = mx.nd.ones((10, 10))
state = mx.nd.zeros(10)
outs, state = mx.nd.contrib.foreach(step, data, state)`

I find a elegant method to implement cumsum. Hope this will be useful.

**Comment by MyYaYa** [comment]
I find a elegant method to implement cumsum. Hope this will be useful.

`
step = lambda data, state : (data + state[0], state[0] + data)
data = mx.nd.ones((10, 10))
state = mx.nd.zeros(10)
outs, state = mx.nd.contrib.foreach(step, data, state)
`

**Comment by MyYaYa** [comment]
I find a elegant method to implement cumsum. Hope this will be useful.
```
step = lambda data, state : (data + state[0], state[0] + data)
data = mx.nd.ones((10, 10))
state = mx.nd.zeros(10)
outs, state = mx.nd.contrib.foreach(step, data, state)
```

**Comment by tsuberim** [comment]
@MyYaYa Cool, is that also differentiable?

**Comment by MyYaYa** [comment]
@tsuberim yeah, as I know, the symbol api in MXNet support auto-differentiation, so you can try the mx.sym.contrib.foreach(), maybe that will work for you.
here is the [link](https://mxnet.incubator.apache.org/api/python/symbol/contrib.html?highlight=foreach#mxnet.symbol.contrib.foreach)

**Comment by soldni** [comment]
Thanks @MyYaYa for the solution! I've repackaged it in a generic cumsum method [here](https://gist.github.com/soldni/b5867b7b4d85084ff4d21fa329b4204c) while waiting for official support.

**Comment by soldni** [comment]
Thank you @MyYaYa for the solution! I've wrapped it up into a generic `consum` function [here](https://gist.github.com/soldni/b5867b7b4d85084ff4d21fa329b4204c) while we wait for official support in future versions.

**Comment by MyYaYa** [comment]
> I find a elegant method to implement cumsum. Hope this will be useful.
> 
> ```
> step = lambda data, state : (data + state[0], state[0] + data)
> data = mx.nd.ones((10, 10))
> state = mx.nd.zeros(10)
> outs, state = mx.nd.contrib.foreach(step, data, state)
> ```

Now, I find this solution is so slow, especially when the size of array is big. So this solution has become a main cost of time in my program. Is there any efficient solution of 'cumsum' using mxnet's ndarray?

**Comment by chinakook** [comment]
I think a better solution is to write a c++ version of this op.

**Comment by crmne** [comment]
It would be great in order to more efficiently implement [Earth Mover's Loss](https://en.wikipedia.org/wiki/Earth_mover%27s_distance)

**Comment by RuRo** [comment]
It would be great to compute the CDF from the histogram.

**Comment by ChaiBapchya** [comment]
Taken note of all the above comments. All these use cases make this feature request very relevant. Tagging myself here as I start working on this.

**Comment by haojin2** [comment]
Added in `mxnet.np` module now, closing.
