### ISSUE TITLE
fix operators to support large arrays.

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#13036]
We're working on a model that requires very large NDArrays. For example, we want to create an NDArray as follows:
```python
arr = mx.nd.random.normal(shape=(50000000, 100))
```
The current implementation doesn't fail with an error, but it doesn't generate a matrix correctly (it only fills the rows at the beginning).

`mx.nd.zeros` also fails.

It's unclear what operators support and which operators don't.

**Comment by frankfliu** [comment]
@mxnet-label-bot [Bug, Operator]

**Comment by wkcn** [comment]
The type of iterator is `int` in MXNet kernel.
So it will fail when the number of iteration is greater than 2^31 - 1, (namely 2147483647).
50000000 * 100 > 2^31 - 1

Please see the code:
CPU:
https://github.com/apache/incubator-mxnet/blob/master/src/operator/mxnet_op.h#L506

GPU:
https://github.com/apache/incubator-mxnet/blob/master/src/operator/mxnet_op.h#L627

**Comment by apeforest** [comment]
Will take a look

**Comment by wkcn** [comment]
@apeforest 
will it drop the performance down If changing the type of iteration to int64_t?
In PyTorch, the type of iteration is a template type.

**Comment by zheng-da** [comment]
i'm fixing some of the operators. but we need a systematic fix. The problem is everywhere. i'll provide a temp fix for some of the operators.

**Comment by zheng-da** [comment]
@wkcn in cpu, it shouldn't be a problem. I heard concerns on GPUs. Potentially, we can use int64_t for CPU and int for GPU.

**Comment by wkcn** [comment]
@zheng-da 
Maybe we can try to use `int32_t` for small for-loop, and `int64_t` for large for-loop.

**Comment by zheng-da** [comment]
@wkcn My concern is that this modification makes the code complex. As for using different int types for CPU and GPU, it's relatively easier. We can use the template argument to easily achieve it.

**Comment by zheng-da** [comment]
@pengzhao-intel what is the performance difference between int32 and int64 in intel CPUs?

**Comment by zheng-da** [comment]
@apeforest I have fixed some of the operators, including all random generators, zeros, ones, full, arange, gather_nd.
https://github.com/zheng-da/incubator-mxnet/commit/2c3d9a3a491d33497c2b37897e73796a0c28e19d
But we need to do more to fix the rest of the operators.

**Comment by apeforest** [comment]
@zheng-da Do you plan to create a PR with your change? I will be glad to review. Also, I have created an epic (https://issues.apache.org/jira/browse/MXNET-1184) to address this support in a systematic way. Please feel free to add additional tasks to it as needed. Thanks.

**Comment by pengzhao-intel** [comment]
@zheng-da in general, int64 is only half of int32 performance.

**Comment by wkcn** [comment]
Hi, I replace the type of all index to a template typename `IndexType`, and add the macro `KERNEL_LAUNCH_TYPE_SWITCH` to choose IndexType. Is it available?

https://github.com/wkcn/incubator-mxnet/blob/support_large_array/src/operator/mxnet_op.h#L62

I use the script [replace_index.py](https://gist.github.com/wkcn/59f6867a217e1a4f68c83ab3d845bba5) to modify all codes.
Using `the_silver_searcher` and the command `ag "MSHADOW_XINLINE static void Map" > map.txt`

**Comment by zheng-da** [comment]
@apeforest I just fixed the operators I use in my model. Could you help add test and fix other operators?

**Comment by wkcn** [comment]
In my test, it seem that the performances of `+/-` between `int32_t` and `int64_t` are the same.

CPU: Intel i7-7500U
Test Code: https://github.com/wkcn/c_performance
```
Test int                                                                                                                                    
2381 ms                                                                                                                                     
2297 ms                                                                                                                                     
2300 ms                                                                                                                                     
3729 ms                                                                                                                                     
Test int32_t                                                                                                                                
2356 ms                                                                                                                                     
2314 ms                                                                                                                                     
2302 ms
3731 ms
Test int64_t
2398 ms
2297 ms
2318 ms
9197 ms
Test float
2687 ms
2690 ms
2690 ms
2686 ms
Test double
2713 ms
2711 ms
2711 ms
2709 ms
```

**Comment by zheng-da** [comment]
integer operations are cheaper. even if int64 is a little more expensive, it's hard to believe that it can affect the overall performance by much.

**Comment by apeforest** [comment]
@wkcn can you share your perf test script. Even though there is not much difference, it would be great to document it with results. Thanks!

**Comment by pengzhao-intel** [comment]
try the gemm with int 32 and int
64 and see how much peak GFLOPS it can achieve

**Comment by lou-k** [comment]
I believe the following is also a repo of this issue:
```python
import mxnet as mx
 mx.nd.eye(10240 * 5) * 2
Out[4]: 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
```

**Comment by apeforest** [comment]
This issue has been fixed. In 1.5.0 release, user need to build MXNet from source with the compilation flag USE_INT64_TENSOR_SIZE=1. We are working to make this flag on by default and available in pip package in next minor release. Closing this issue for now.
