### ISSUE TITLE
Export to ONNX not working as expected for ArcFace model

### ISSUE THREAD

**Issue by ankkhedia** [apache/incubator-mxnet#13044]
I am trying to export Arcface model to ONNX.
The model is located in this public S3 bucket
https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100-0000.params
https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100-symbol.json
When we export to ONNX we get float64 dtype for minscalar layer whereas the ONNX specification doesn't support float64.

## Minimum reproducible example
from mxnet.contrib import onnx as onnx_mxnet
model = onnx_mxnet.export_model('resnet100-symbol.json', 'resnet100-0000.params', [(1,3,112,112)], onnx_file_path='resnet100.onnx')
and then visualise  the model using netron
More details can be found here https://github.com/onnx/models/issues/91

## Steps to reproduce
Please use the above snippet to reproduce.

## What have you tried to solve it?

1. Seems like a bug in the conversion from MXNet to ONNX for particular layer.

**Comment by vandanavk** [comment]
thanks for reporting this @ankkhedia. Looking into it
