### ISSUE TITLE
tutorials C++ index page without meaningful content

### ISSUE THREAD

**Issue by pengzhao-intel** [apache/incubator-mxnet#13055]
https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/c%2B%2B/index.md

@aaronmarkham

**Comment by pengzhao-intel** [comment]
@mxnet-label-bot [Doc]

**Comment by aaronmarkham** [comment]
Many of the tutorial folders were without an index page. Sphinx throws errors when there isn't a table of contents on an index page. The "glob" directive just tells Sphinx to autogenerate a ToC based on the contents of that directory. That is why it seems like it might not be meaningful, but if you browse to the site you can see that it created a basic table of contents:
https://mxnet.incubator.apache.org/tutorials/c++/index.html
If someone wants to expound upon these tutorials and organize an index page differently then that's a wide open opportunity, but at this point, I don't think this is an issue.
@pengzhao-intel - what do you think?

**Comment by pengzhao-intel** [comment]
@aaronmarkham Thanks for the explanation. It makes sense :)
