### ISSUE TITLE
Scala-Package CI Missing

### ISSUE THREAD

**Issue by Wei-1** [apache/incubator-mxnet#13063]
## Description
On the Scala package page:
https://github.com/apache/incubator-mxnet/tree/master/scala-package

The badge for Travis-CI is not working correctly. It is pointing to the DMLC page, which is not there anymore.

## Environment info

The current test for Travis-CI is at https://travis-ci.org/apache/incubator-mxnet/
However, it is only for C++.

in [.travis.yml](https://github.com/apache/incubator-mxnet/blob/master/.travis.yml#L3)

```bash
language: cpp
```

## Build info

If we follow the current link in `README.md` in scala-package and go to https://travis-ci.org/dmlc/mxnet
We will get the following message

## Error Message:

```
We couldn't find the repository 
dmlc/mxnet
```

## Minimum reproducible example

1. Check https://github.com/apache/incubator-mxnet/blob/master/scala-package/README.md

## Steps to reproduce

1. Click https://github.com/apache/incubator-mxnet/tree/master/scala-package
2. Click the Travis-CI Badge

## What have you tried to solve it?

1. I tried building some Scala examples and also [@Ldpe2G 's examples](https://github.com/Ldpe2G/DeepLearningForFun), and the testing works well. So we could add a matrix in the Travis-CI test for Scala at least for those examples.
2. Since there is no GPU for Travis-CI's environment, we can choice OSX and use the CPU Jar in `travis.yml`.

**Comment by frankfliu** [comment]
@mxnet-label-bot [Scala, Doc]

**Comment by lanking520** [comment]
Hi @Wei-1 Thanks for your issue, I will raise a PR regarding your problems. Apart from that, we now have Linux CPU/GPU test on Jenkins and will have one for OSX very soon. 

Check here for some up-to-date examples with README: https://github.com/apache/incubator-mxnet/tree/master/scala-package/examples .

You can also choose our nightly-build package for Scala which is available to download and imported by Maven:
https://repository.apache.org/#nexus-search;gav~org.apache.mxnet~~1.3.1-SNAPSHOT~~

**Comment by lanking520** [comment]
@Wei-1 Got PR merged. Could you please close the issue?
