### ISSUE TITLE
UpSampling Operator Documentation is incomplete

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#13078]
The UpSampling operator documentation is incomplete - https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html?highlight=upsam#mxnet.ndarray.UpSampling 

It does not show `num_args` as a parameter - https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/upsampling-inl.h#L50 . And in bilinear mode the operator expects [two inputs](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/upsampling-inl.h#L79) - data and weight. Even that is not specified in the documentation.

This can cause confusion like in here - https://github.com/apache/incubator-mxnet/issues/13073

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Operator, Doc, Bug]

**Comment by apeforest** [comment]
@mxnet-label-bot [Call for Contribution, Good First Issue]
