### ISSUE TITLE
3D version of mxnet.ndarray.UpSampling

### ISSUE THREAD

**Issue by yash0307** [apache/incubator-mxnet#13073]
mxnert.ndarray.UpSampling checks if the data is in form: (batch_size, channels, x,y) (that is, number of dimensions=4), however, I want to do UpSampling for volumetric data where the data is of the form: (batch_size,channels,x,y,z).

Is there a way to do this ?

**Comment by frankfliu** [comment]
@mxnet-label-bot [Question]

**Comment by frankfliu** [comment]
@mxnet-label-bot [NDArray]
