### ISSUE TITLE
Port Scala Image API to Clojure Package

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#13089]
The Image API would be very useful for Clojure users.

Adding it to Clojure would involve adding a new namespace in the Clojure package and adding the correct interop functions as well as a tests for it.

Here is the Scala PR that was just merged into master https://github.com/apache/incubator-mxnet/pull/12995

**Comment by kedarbellare** [comment]
@gigasquid : I can work on this if no one else has signed up. Note that this is the first time I'm contributing to mxnet so I may need some handholding :smiley:

**Comment by gigasquid** [comment]
@kedarbellare awesome 💯 Happy to help out. Feel free to reach out to me on slack or Github as needed 😸
