### ISSUE TITLE
Search is broken on gluon.mxnet.io (gluon tutorials)

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13091]
## Description
[Reported on that site's repo quite some time ago](https://github.com/zackchase/mxnet-the-straight-dope/issues/462), but I'm bringing it up here where there are more eyes.

The site is a hub of the gluon tutorials. **The site must be searchable**.

**Comment by frankfliu** [comment]
@mxnet-label-bot [Doc, Gluon, Example]

**Comment by kalyc** [comment]
@aaronmarkham I see that Search is working on the Gluon website - 
https://gluon.mxnet.io/search.html?q=autograd&check_keywords=yes&area=default#
https://gluon.mxnet.io/search.html?q=load&check_keywords=yes&area=default#
Could you check at your end and close this issue if its not persisting?

**Comment by aaronmarkham** [comment]
It is working now!
