### ISSUE TITLE
size_array operator returns wrong results on MacOS

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#13098]
## Description
`size_array` operator returns incorrect results on MacOS but works correctly on Linux systems

Package used (Python/R/Scala/Julia):
I'm using **Python**

Compiler (gcc/clang/mingw/visual studio):
clang

MXNet commit hash:
50f43f05ab61fe9e19698bb18dc34858a240b263

Build config:
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas

## Minimum reproducible example
```python
import mxnet as mx
a = mx.nd.array([1,2,3,4,5])
print(mx.nd.size_array(a))
```

## Steps to reproduce
1. Run the above script in MacOS, the function will return a junk memory location.
2. Run it on Linux and it will work fine.

## What have you tried to solve it?
1. Use the operator on a linux system.

**Comment by wkcn** [comment]
In [src/operator/tensor/elemwise_unary_op_basic.cc#L546](https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/elemwise_unary_op_basic.cc#L546),
```c++
  const index_t size_var = in_data.Size();
  memcpy(out_data.dptr_, &size_var, 1U * sizeof(int64_t));
```

In `3rdparty/dmlc-core/include/dmlc/data.h`,
```c++
typedef unsigned index_t;  
```

It's confusing that `index_t` may not the same as `int64_t`

**Comment by apeforest** [comment]
@mxnet-label-bot [Call for Contribution, Good First Issue]

**Comment by apeforest** [comment]
Issue has been fixed:

```
>>> import mxnet as mx
a = mx.nd.array([1,2,3,4,5])
>>> a = mx.nd.array([1,2,3,4,5])
>>> print(mx.nd.size_array(a))

[5]
<NDArray 1 @cpu(0)>
>>> 
```
