### ISSUE TITLE
Python API docs don't mention image.imread

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13090]
## Description
`mx.image.imread` is undocumented. Searches only lead to examples using it, but never any actual API reference.
I'm led to believe this is coming from OpenCV. It would be nice if this feature was explained in detail, so users know what is available to them.

Various preprocessing examples use `mx.image.imread` or `PIL.Image` and their image handling makes a big difference with inference results, throwing off trying to use the examples. Without detailed docs it is hard to understand what is happening.

**Comment by frankfliu** [comment]
@mxnet-label-bot [Doc, Python]

**Comment by anirudhacharya** [comment]
Fix https://github.com/apache/incubator-mxnet/pull/12831

**Comment by aaronmarkham** [comment]
@anirudhacharya - I see that `imresize` is documented in your PR, but not `imread`. Seems like you'd need to add a specific section for it...

**Comment by NRauschmayr** [comment]
As documented here: https://mxnet.incubator.apache.org/_modules/mxnet/image/image.html mx.image.imread uses OpenCV (not the CV2 Python library). MXNet must have been built with USE_OPENCV=1 for `imdecode` to work.

**Comment by aaronmarkham** [comment]
Not sure what happened to Nathalie's comment here, but she points out [this file](https://mxnet.incubator.apache.org/_modules/mxnet/image/image.html). There are a lot of functions coming from OpenCV, and this file has doc strings that could show up in the docs, but they're not at the moment.
