### ISSUE TITLE
Confusing Message when Scala/Clojure package extracts the native library from jar

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#13108]
The message when the Scala package extracts the native library from the jar is not very clear and causing some confusion with users. This issue is to explore how/if we can improve it.

```
INFO  MXNetJVM: Try loading mxnet-scala from native path.
INFO  MXNetJVM: Try loading mxnet-scala-linux-x86_64-gpu from native path.
INFO  MXNetJVM: Try loading mxnet-scala-linux-x86_64-cpu from native path.
WARN  MXNetJVM: MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].
INFO  org.apache.mxnet.util.NativeLibraryLoader: Loading libmxnet-scala.so from /lib/native/ copying to mxnet-scala
```

The message comes from where the native library is being extracted out of the jar, copies it to a temp file, and then loads it into memory from there https://github.com/apache/incubator-mxnet/blob/master/scala-package/core/src/main/scala/org/apache/mxnet/util/NativeLibraryLoader.scala#L92

It was originally brought up by @kohr-h  in https://github.com/apache/incubator-mxnet/pull/12881

**Comment by gigasquid** [comment]
Pinging @nswamy @yzhliu @lanking520

**Comment by lanking520** [comment]
Thanks for raising this issue. I also checked about this before, looks like we need to fix some paths issues.
