### ISSUE TITLE
Dockerhub causing timeouts in CI

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#13104]
I've seen several reports of timeouts in the CI recently and believe it's Dockerhub related.  All of the reports have a docker pull that initially fails and then completes after a lengthy retry:

Example:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/master/runs/1862/nodes/1013/log/?start=0
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1862/pipeline

In this example the job gets terminated after running for over 2 hours, but looking at the actual tests they are only running from 22:49:02 to 2018-11-03 22:58:04 (about 10 minutes).  This means we must be spending nearly 2 hours pull docker images (which is very strange).

**Comment by frankfliu** [comment]
@mxnet-label-bot [CI, build]

**Comment by Chancebair** [comment]
We have seen some Docker Hub issues recently but they have not reported anything for the time this build was triggered: https://status.docker.com/pages/history/533c6539221ae15e3f000031

**Comment by KellenSunderland** [comment]
Yeah I found that strange as well Chance.  I was expecting to see some
outage notices corresponding with these retries to be honest.

**Comment by KellenSunderland** [comment]
Looks like this has been addressed by DockerHub, haven't seen a occurrence in some time.
