### ISSUE TITLE
out_data paramter is wrong

### ISSUE THREAD

**Issue by xueyoo** [apache/incubator-mxnet#13110]
I create one operator and it similar with  incubator-mxnet/src/operator/cudnn_bilinear_sampler-inl.h
and forward function appear one error at out_data.get function.
the error info is: TBlob.get: device type do not match specified type

add some debug information for out_data object, and found both dev_mask and  dev_id in out_data  are zero
this is strange for dev_mask, it should be 1 or 2, but operator code got 0

is there any reason for this problem?

thanks

**Comment by frankfliu** [comment]
@mxnet-label-bot [Question, operator]
