### ISSUE TITLE
Why 'Train-accuracy' is so big when training the fcn-xs model? (Train-accuracy=124157.292647)

### ISSUE THREAD

**Issue by Rafel-Mou** [apache/incubator-mxnet#1312]
Hi all,

I'm working on training the fcn-xs model using PASCAL VOC 2012 dataset. But I noticed that the value of training accuracy is so big (Train-accuracy=123191.432432), that seems like different with the case given in the Readme. Could you tell me what's the reason? Thanks a lot.

**Comment by piiswrong** [comment]
The Accuracy metric doesn't divide by the number of predictions. Should be fixed by https://github.com/dmlc/mxnet/pull/1309

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
