### ISSUE TITLE
example/reinforcement-learning/ddpg is using a deprecated framework RLLAB

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#13127]
The example depends on RLLAB from openAI which is deprecated.
Opening an issue to track and discuss whether we should update or delete the example.

@anirudhacharya

**Comment by anirudhacharya** [comment]
thanks for raising the issue Thomas. This is the example in question - https://github.com/apache/incubator-mxnet/tree/master/example/reinforcement-learning/ddpg

**Comment by leleamol** [comment]
@mxnet-label-bot [RNN, Example]

**Comment by sad-** [comment]
@ThomasDelteil looks like you merged in the pr to address this. can this issue be closed?
