### ISSUE TITLE
Manually compile MXNet1.3.0 release code, which is very inefficient after testing.

### ISSUE THREAD

**Issue by chenyujing1234** [apache/incubator-mxnet#13133]
I compiled the 1.3.0 release code according to the official way.
Code download address: https://github.com/apache/incubator-mxnet/releases/tag/1.3.0
Compile method reference: https://mxnet.incubator.apache.org/install/ubuntu_setup.html
Build MXNet from Source
The compile command is:
Make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
The compilation is successful, but the performance of the resulting libmxnet.so is quite different from that of the published version of libmxnet.so.
Testing method: Face detection using mtcnn algorithm on a single GPU, the speed of publishing version processing is 90 sheets per second, and I compiled only 20 sheets per second (GPU utilization is very low at this time).
I would like to ask you a few questions:
1) I found that the compiled libmxnet. so is only 295M, while the official release is 500M. What's the difference?
2) Later, it was found that the libmxnet.so I compiled is a Debug version. How can I compile the release version?
3) why do I compile my own performance so low?

**Comment by leleamol** [comment]
Hello @chenyujing1234  Thank you very much for submitting the issue. I'm labeling it so MXNet community members can help resolve it. In order to help triage the issue further could you provide some information?
1.  Which MXNet released/published version you have used for comparison with built from source library ? There are pip versions such as mxnet-cu90, mxnet-cu90mkl, etc available.
2. The performance numbers that are mentioned are for the Debug version? Typically debug version binaries tend to show lower performance.

@mxnet-label-bot [Build, Performance, Pending-requestor-info]

**Comment by chenyujing1234** [comment]
> Hello @chenyujing1234 Thank you very much for submitting the issue. I'm labeling it so MXNet community members can help resolve it. In order to help triage the issue further could you provide some information?
> 
> 1. Which MXNet released/published version you have used for comparison with built from source library ? There are pip versions such as mxnet-cu90, mxnet-cu90mkl, etc available.
> 2. The performance numbers that are mentioned are for the Debug version? Typically debug version binaries tend to show lower performance.
> 
> @mxnet-label-bot [Build, Performance, Pending-requestor-info]

1. I  Build In Ubuntu14.04.1 With cuda9.0( No MKL). GPU is GTX 1080
2. I am not sure Is it Debug version,  I Foud the libmxnet.so (readelf -S libmxnet.so), Found there are debug information in the file。 But I am sure  i build it with DEBUG=0

**Comment by chenyujing1234** [comment]
> > Hello @chenyujing1234 Thank you very much for submitting the issue. I'm labeling it so MXNet community members can help resolve it. In order to help triage the issue further could you provide some information?
> > 
> > 1. Which MXNet released/published version you have used for comparison with built from source library ? There are pip versions such as mxnet-cu90, mxnet-cu90mkl, etc available.
> > 2. The performance numbers that are mentioned are for the Debug version? Typically debug version binaries tend to show lower performance.
> > 
> > @mxnet-label-bot [Build, Performance, Pending-requestor-info]
> 
> 1. I  Build In Ubuntu14.04.1 With cuda9.0( No MKL). GPU is GTX 1080
> 2. I am not sure Is it Debug version,  I Foud the libmxnet.so (readelf -S libmxnet.so), Found there are debug information in the file。 But I am sure  i build it with DEBUG=0

Today I found that tensorRT is not used in compile phase.  Does it have any effect?

**Comment by chenyujing1234** [comment]
Please help me , I've been troubled for a long time.

**Comment by KellenSunderland** [comment]
Would you be able to run a simple test (in which you see a performance difference) and run with nvprof for both cases and post the result.  Just run the same python script you'd normally run and prefix your bash command with nvprof.  This should get you some output when the process finishes that will be useful for determining where the perf difference is.

**Comment by chenyujing1234** [comment]
a solution was found. It's normal not to link openblash

**Comment by chenyujing1234** [comment]
It looks like it's openblash that causes me to use only one CPU

**Comment by chenyujing1234** [comment]
This problem can be closed. Thank you.
