### ISSUE TITLE
Perform Fourier Transform on the GPU

### ISSUE THREAD

**Issue by tmquan** [apache/incubator-mxnet#1315]
Dear developers, 

It's great to know that you are doing fantastic job with mxnet. 
I have just one concern that so far GPU does well on fft, fft2, fftn and so on with cufft libraries. 
It is possible that an NDArray variable can be performed fft(n) explicitly across multiple GPUs as lazy evaluation?

Bests,

**Comment by piiswrong** [comment]
You can do it by adding a unary function in src/ndarray/unary_fucntions.cc

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
