### ISSUE TITLE
testissue

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#13163]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by marcoabreu** [comment]
@mxnet-label-bot add label [CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot remove [CI]

**Comment by marcoabreu** [comment]
@mxnet-label-bot remove [CI]

**Comment by marcoabreu** [comment]
@mxnet-label-bot remove [CI]

**Comment by marcoabreu** [comment]
@mxnet-label-bot remove [CI]

**Comment by marcoabreu** [comment]
@mxnet-label-bot add [CI, Good first issue]

**Comment by lanking520** [comment]
@mxnet-label-bot please thanks @marcoabreu for his effort

**Comment by lanking520** [comment]
@mxnet-label-bot update [Question]

**Comment by marcoabreu** [comment]
@mxnet-label-bot update [Question, Good first IsSue, something that doesn't exist]

**Comment by szha** [comment]
Oh poor Marco.

**Comment by marcoabreu** [comment]
Thank god I'm not automatically getting subscribed for all these threads :D

**Comment by marcoabreu** [comment]
@mxnet-label-bot update [something that doesn't exist]

**Comment by marcoabreu** [comment]
@mxnet-label-bot remove [something that doesn't exist]

**Comment by marcoabreu** [comment]
@mxnet-label-bot unsuppored command [something that doesn't exist]

**Comment by szha** [comment]
@mxnet-label-bot dance

**Comment by marcoabreu** [comment]
@mxnet-label-bot elephant [Python]

**Comment by marcoabreu** [comment]
@mxnet-label-bot 123456789

**Comment by marcoabreu** [comment]
@mxnet-label-bot update []

**Comment by szha** [comment]
@mxnet-label-bot add [breaking, dance]

**Comment by harshp8l** [comment]
> @mxnet-label-bot update []

I overlooked this case - this would be useful for the user to delete all labels easily

**Comment by roywei** [comment]
@mxnet-label-bot do you get confused by url like this [Bug](https://github.com/apache/incubator-mxnet/pull/12958#issuecomment-432842299)? add[CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot remove [Good First Issue]

**Comment by lanking520** [comment]
@mxnet-label-bot add [bug, feature, breaking, ci, scala, python, gluon]

**Comment by lanking520** [comment]
@mxnet-label-bot update [fart]

**Comment by piyushghai** [comment]
Hey @mxnet-label-bot Remove [Question], remove [Python], remove Feature

**Comment by lanking520** [comment]
@mxnet-label-bot remove [Question, Python, Feature]

**Comment by aaronmarkham** [comment]
@mxnet-label-bot add [gOOd FiRsT IsSuE]!!!

**Comment by aaronmarkham** [comment]
![good-first-issue](https://user-images.githubusercontent.com/5974205/48276155-2eb9ea80-e3fc-11e8-807c-ecc21373dcfd.jpg)

**Comment by harshp8l** [comment]
Old version was redeployed ;(

**Comment by harshp8l** [comment]
@mxnet-label-bot remove [Bug]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Bug]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [gOOd FiRsT IsSuE]!!!

**Comment by lanking520** [comment]
@mxnet-label-bot remove [good first issue]

**Comment by piyushghai** [comment]
@mxnet-label-bot AdD [QuestiON]

**Comment by lanking520** [comment]
@mxnet-label-bot update [Question]

**Comment by CathyZhang0822** [comment]
@mxnet-label-bot remove [Question]

**Comment by CathyZhang0822** [comment]
@mxnet-label-bot add [a label doesn't exist]

**Comment by CathyZhang0822** [comment]
@mxnet-label-bot update [FEATURE REQUEST, feature request, Feature requests]

**Comment by CathyZhang0822** [comment]
Awesome! @mxnet-label-bot, You are a good bot. Well done.

**Comment by apeforest** [comment]
@mxnet-label-bot update [Question, Bug]

**Comment by apeforest** [comment]
@mxnet-label-bot update [Test]

**Comment by aaronmarkham** [comment]
@mxnet-label-bot add [gOOd FiRsT IsSuE]!!!

**Comment by aaronmarkham** [comment]
@mxnet-label-bot remove [gOOd FiRsT IsSuE]!!!

**Comment by aaronmarkham** [comment]
Sweet. It works!

**Comment by harshp8l** [comment]
@mxnet-label-bot update [pr-awaiting-review]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [bug, Insallation]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [question, Test]

**Comment by kalyc** [comment]
@mxnet-label-bot remove [Bug]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Suggest-Closed]

**Comment by harshp8l** [comment]
@mxnet-label-bot remove [sUgGeSt-cloSEd]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [build]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Build]

**Comment by harshp8l** [comment]
@mxnet-label-bot remove [Build]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Build]

**Comment by harshp8l** [comment]
@mxnet-label-bot add [ci]

**Comment by harshp8l** [comment]
blahblahblah
@mxnet-label-bot add [ci]

**Comment by harshp8l** [comment]
blahblahblah
@mxnet-label-bot add[ci]

**Comment by harshp8l** [comment]
@mxnet-label-bot  add[ci]

**Comment by piyushghai** [comment]
@mxnet-label-bot     remove[CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot       remove[CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot replace[question, ci]

**Comment by harshp8l** [comment]
@mxnet-label-bot replace [Test, CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot replace [Test, CI]

**Comment by harshp8l** [comment]
@mxnet-label-bot replace[CI, Test]

**Comment by harshp8l** [comment]
test test test test test
@mxnet-label-bot add [good first issue]
