### ISSUE TITLE
 mx.sym.sparse.dot generate wrong result?   

### ISSUE THREAD

**Issue by moveforever** [apache/incubator-mxnet#13172]
code is as followed. I found the result of mx.sym.sparse is not equal to the result mx.nd.sparse. I validate the result of mx.nd.sparse is right. So i guess there existed bug in mx.sym.sparse ?
```
data = mx.sym.Variable(DATA_NAME, stype='csr')
label = mx.symbol.Variable(LABEL_NAME)

weight = mx.sym.Variable("weight", shape=(feature_dim, 32),stype='row_sparse')
net = mx.sym.sparse.dot(data, weight)
bias = mx.sym.Variable("bias", shape=(1,))
net = mx.sym.broadcast_plus(net, bias)

net = mx.sym.LogisticRegressionOutput(data=net, label=label)
```

**Comment by moveforever** [comment]
@eric-haibin-lin , help

**Comment by leleamol** [comment]
Hi @moveforever Thanks for submitting the issue. 

@mxnet-label-bot [Python, Symbol, Sparse]

**Comment by moveforever** [comment]
sorry, now i validate that result of mx.sym.sparse.dot is right. There existed some problem in my validation
