### ISSUE TITLE
[Feature request]JPEG Orientation in mxnet.image.imread

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#13216]
When using mxnet.image.imread to deal with some jpeg file, the result image will be wrong, as **mxnet cannot get the right mode of JPEG orientation** from the exif. It's important when people want to train their own images with JPEG orientation information included.
I hope we can add some flags as the OpenCV does.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Feature Request]

**Comment by anirudhacharya** [comment]
this issue is being tracked here - https://github.com/apache/incubator-mxnet/issues/14956 Can we close this issue?

**Comment by chinakook** [comment]
Yes, we can close it.
