### ISSUE TITLE
train_cifar10 example not working with Master Branch

### ISSUE THREAD

**Issue by kalyc** [apache/incubator-mxnet#13211]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
train_cifar10 example not working as described in the readme

Following error message is thrown:
```
Traceback (most recent call last):
  File "train_mnist.py", line 96, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/home/ubuntu/incubator-mxnet/example/image-classification/common/fit.py", line 220, in fit
    lr, lr_scheduler = _get_lr_scheduler(args, kv)
  File "/home/ubuntu/incubator-mxnet/example/image-classification/common/fit.py", line 53, in _get_lr_scheduler
    base_lr=args.lr))
TypeError: __init__() got an unexpected keyword argument 'base_lr'
```

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 7.2.0
Build        : ('default', 'Apr 29 2018 16:14:56')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.3.0
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet
Commit Hash   : b3be92f4a48bce62a5a8424271871c2f81c8f7f1
----------System Info----------
Platform     : Linux-4.4.0-1070-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-13-114
release      : 4.4.0-1070-aws
version      : #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2701.871
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.06
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0018 sec, LOAD: 0.5779 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0474 sec, LOAD: 0.1173 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.3806 sec, LOAD: 0.1539 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0098 sec, LOAD: 0.2449 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0095 sec, LOAD: 0.3935 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0009 sec, LOAD: 0.0534 sec.

```

Package used (Python/R/Scala/Julia):
Python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
89f3091f06b3ab82aab27f6a48d6e2b6223b2a09

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Run `python train_cifar10.py --network resnet --num-layers 110 
 --gpus 0,1`

## What have you tried to solve it?

1. Installed v1.3 from source on Base DLAMI
2. Used DLAMI environment - `mxnet_p36` to test this example

Error thrown in both the cases

@mxnet-label-bot add[Example, Python]

**Comment by Roshrini** [comment]
Thanks for reporting this issue. I tried to reproduce it. Seems like the example script was changed after the release.

If you run script https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/train_cifar10.py from master branch, it will not work with 1.3. release branch.

With MXNet1.3 branch, please run https://github.com/apache/incubator-mxnet/blob/v1.3.x/example/image-classification/train_cifar10.py It works fine.

**Comment by kalyc** [comment]
Thanks for taking a look @Roshrini 
I verified that the example works with `v1.3.x` branch and doesn't work with the `master` branch.
Error log is the same as pasted above for `master` branch

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Example, Python]

**Comment by kalyc** [comment]
Re-installed mxnet using `pip install mxnet --pre` and the example works on master, closing issue
