### ISSUE TITLE
Many operators don't work for integer type 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#13220]
Many operators implicitly cast data to float and return inaccurate results: 
```
>>> mx.nd.array([50000001], dtype='int32')

[50000001]
<NDArray 1 @cpu(0)>

>>> mx.nd.array([50000001], dtype='int32').floor()

[50000000] ------------->  should be [50000001]
<NDArray 1 @cpu(0)> 

>> mx.nd.array([50000001], dtype='int32').round()

[50000000] ------------->  should be [50000001]
<NDArray 1 @cpu(0)>
>>> mx.nd.array([50000001], dtype='int32').ceil()

[50000000] ------------->  should be [50000001]
<NDArray 1 @cpu(0)>
>>> mx.nd.array([50000001], dtype='int32').trunc()

[50000000] ------------->  should be [50000001]
<NDArray 1 @cpu(0)> 
```

**Comment by apeforest** [comment]
@mxnet-label-bot [Good First Issue, Call for Contribution]

**Comment by hanzhaogang** [comment]
Hard to trace. Can't find the  gen_op module in the current package while working on this line:
`from .gen_op import * # pylint: disable=unused-wildcard-import`

**Comment by eric-haibin-lin** [comment]
It's most likely due to the float conversion in https://github.com/apache/incubator-mxnet/blob/f5ba2678f077b58d31d31029f680f93b313e1cea/src/operator/math_functions-inl.h#L43-L61

**Comment by Vikas89** [comment]
@anirudh2290 Please tag PR-work-in-progress
