### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by gjtjx** [apache/incubator-mxnet#13223]
compile error ,stuck at dmc_core or kvstore_utils
ubuntu 16.04
gcc version 5.4.0
cuda9.2 cudnn 7.1.4
any help?

**Comment by leleamol** [comment]
@gjtjx 
Thanks for submitting the issue. Can you please share the flags (such as USE_CUDA_PATH, USE_OPENCV, etc) that you are using while building the MXNet? 

I will add the labels to this issue so that MXNet community members would be able to provide help.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Build]

**Comment by kalyc** [comment]
Could be a related issue https://github.com/apache/incubator-mxnet/issues/12041

**Comment by zachgk** [comment]
@mxnet-label-bot add [Pending Requester Info]

Can you please provide the following info so we can help figure out the problem:

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

**Comment by vrakesh** [comment]
@gjtjx are you still facing this compilation error? Requesting you to provide build info, so that we can reproduce this issue on our end .

**Comment by vdantu** [comment]
@gjtjx : Could you please provide the build command you used? Also, could you provide the output you see. And if you have already fixed it, could you provide what was missing either in the documentation or the steps you followed?

**Comment by vdantu** [comment]
We haven't heard back about the issue. I think we can close it for now. 

@gjtjx  : We will close this issue for now. Please feel free to reopen it if you are still facing this issue. Also, if you are still facing the issue, please do attach the config flags that you are using to run the build.

@lanking520

**Comment by lanking520** [comment]
Close it for now. Please feel free to reopen if you are facing more issues.
