### ISSUE TITLE
visualization docs don't line up with tutorials usage of viz

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13232]
## Description
When visualization is mentioned in tutorials it is always done like `mx.viz.plot` or similar. It is never done as `mx.visualization`. However, our API reference only has `mx.visualization` and the `.viz.` option isn't mentioned.

We have this issue around any kind of shortcut/redirect naming throughout the project.

Sphinx is unable to use the shortcut names for some reason. It has to use the full path. I don't know if this is a configuration issue or by design.

Either way the docs should line up with usage examples. We shouldn't have tutorials that have usage that is never covered in the reference docs. We shouldn't have reference docs that don't have any usage examples.

Similar issue in ONNX: https://github.com/apache/incubator-mxnet/issues/12318

@mxnet-label-bot add [Doc]
@vdantu

**Comment by harshp8l** [comment]
@mxnet-label-bot add [Doc]
