### ISSUE TITLE
broken links on website

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#13250]
This link seems to be broken:
https://mxnet.apache.org/api/python/io/io.html

**Comment by zachgk** [comment]
@mxnet-label-bot add [Doc, Website]

@aaronmarkham, can you take a look at this?

**Comment by aaronmarkham** [comment]
I think that this PR: https://github.com/apache/incubator-mxnet/pull/13246 should fix the problem.

**Comment by aaronmarkham** [comment]
Note that PR's preview links have the content showing up just fine.
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13246/1/api/python/io/io.html
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13246/1/api/python/gluon/model_zoo.html

**Comment by vdantu** [comment]
@roywei and @aaronmarkham : I might have forgotten to Fixes tag .. the PR is merged. Could we close this issue?

**Comment by roywei** [comment]
Thanks for fixing this! Closing
