### ISSUE TITLE
R test failing intermitently

### ISSUE THREAD

**Issue by kalyc** [apache/incubator-mxnet#13274]
## Description
R test failing intermitently

## Environment info (Required)
Test failing on CI and could be flaky

For R user, please provide R `sessionInfo()`:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13266/1/pipeline

Have been observing above behavior on multiple PRs

**Comment by kalyc** [comment]
@mxnet-label-bot add [R, Flaky, CI]

**Comment by kalyc** [comment]
Another PR with similar failure - https://github.com/apache/incubator-mxnet/pull/13256

**Comment by anirudhacharya** [comment]
Duplicate issue https://github.com/apache/incubator-mxnet/issues/13439

Can we close this in favor of the above issue?  @nswamy

**Comment by kalyc** [comment]
Closing issue in favor of https://github.com/apache/incubator-mxnet/issues/13439
