### ISSUE TITLE
Data type error when import onnx model

### ISSUE THREAD

**Issue by wangxinanbook** [apache/incubator-mxnet#13300]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
I report a bug in 
incubator-mxnet/python/mxnet/contrib/onnx/onnx2mx/import_onnx.py

```
def _parse_array(self, tensor_proto):
        """Grab data in TensorProto and convert to numpy array."""
        try:
            from onnx.numpy_helper import to_array
        except ImportError:
            raise ImportError("Onnx and protobuf need to be installed. "
                              + "Instructions to install - https://github.com/onnx/onnx")
        np_array = to_array(tensor_proto).reshape(tuple(tensor_proto.dims))
        return nd.array(np_array)
```

`tensor_proto` can be an numeric variable like Long, etc. Then,  `tensor_proto.dims` will be empty, and `to_array(tensor_proto)` cannot be reshaped to an empty shape. 

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

One way to  fix:

```
def _parse_array(self, tensor_proto):
        """Grab data in TensorProto and convert to numpy array."""
        try:
            from onnx.numpy_helper import to_array
        except ImportError:
            raise ImportError("Onnx and protobuf need to be installed. "
                              + "Instructions to install - https://github.com/onnx/onnx")
        if len(tuple(tensor_proto.dims)) > 0:
            np_array = to_array(tensor_proto).reshape(tuple(tensor_proto.dims))
        else:
            np_array = np.array([to_array(tensor_proto)])
        return nd.array(np_array)
```

**Comment by vandanavk** [comment]
Thanks for reporting the issue and proposing a fix too @wangxinanbook. You could go ahead and raise a PR with this proposed fix. Please verify if all the ONNX import tests pass (tests/python-pytest/onnx/import/mxnet_backend_test.py)

**Comment by vandanavk** [comment]
@mxnet-label-bot add [ONNX, Bug]

**Comment by wangxinanbook** [comment]
Sure @vandanavk

**Comment by wangxinanbook** [comment]
I ran the test. It came out another issue on `test_clip_default_min_cpu`,  even I used the master code.  I think this should be fixed elsewhere.  How do you think ?  @vandanavk 
```
Traceback (most recent call last):
  File "/opt/home/wangxinan/anaconda3/envs/test_mxnet/lib/python3.6/site-packages/onnx/backend/test/runner/__init__.py", line 243, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/opt/home/wangxinan/anaconda3/envs/test_mxnet/lib/python3.6/site-packages/onnx/backend/test/runner/__init__.py", line 273, in run
    prepared_model = self.backend.prepare(model, device)
  File "/opt/home/wangxinan/workspace/incubator-mxnet/tests/python-pytest/onnx/import/mxnet_backend.py", line 57, in prepare
    sym, arg_params, aux_params = graph.from_onnx(model.graph)
  File "/opt/home/wangxinan/workspace/incubator-mxnet/python/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 131, in from_onnx
    raise err
  File "/opt/home/wangxinan/workspace/incubator-mxnet/python/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 128, in from_onnx
    mxnet_sym = self._convert_operator(node_name, op_name, onnx_attr, inputs)
  File "/opt/home/wangxinan/workspace/incubator-mxnet/python/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 69, in _convert_operator
    mxnet_sym = new_op(*inputs, **new_attrs)
  File "<string>", line 73, in clip
  File "/opt/home/wangxinan/workspace/incubator-mxnet/python/mxnet/_ctypes/symbol.py", line 125, in _symbol_creator
    ctypes.byref(sym_handle)))
  File "/opt/home/wangxinan/workspace/incubator-mxnet/python/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for a_max expect float but value='inf', in operator clip(name="", a_max="inf", a_min="0.0")
```

**Comment by vandanavk** [comment]
@wangxinanbook I don't see this error. It seems to pass on my setup
