### ISSUE TITLE
C++ tutorials

### ISSUE THREAD

**Issue by zhaoyao73** [apache/incubator-mxnet#13316]
C++ tutorials is not up to date with current cpp-package.
Current cpp-package doesn't provide get_mnist.sh anymore.
I will provide a patch for it.

**Comment by zachgk** [comment]
@mxnet-label-bot add [C++, Doc]

Thank you for the contributions @zhaoyao73. I am labeling this issue so the MXNet community can help find it.

**Comment by lupesko** [comment]
@zhaoyao73 is the issue fixed now that the PR was merged?
If so - please close the issue, otherwise please elaborate. 
Thanks!
