### ISSUE TITLE
problem about lstm_crf 

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#13329]
![image](https://user-images.githubusercontent.com/24219258/48750595-d1a31c00-ecba-11e8-8e01-4282994a8daa.png)
 
does this step have any problem?  it may not match this logloss 
![image](https://user-images.githubusercontent.com/24219258/48750688-6ad23280-ecbb-11e8-8258-16242599cebd.png)

**Comment by janelu9** [comment]
here is the codes
https://github.com/apache/incubator-mxnet/blob/master/example/gluon/lstm_crf/lstm_crf.py

**Comment by janelu9** [comment]
it's difficult to compute Z(t) ，I think the first "logsumexp" may be replaced with "sumexp"

**Comment by vdantu** [comment]
@mxnet-label-bot add [question, Gluon, Example]

**Comment by janelu9** [comment]
it  may be a divergence on how to comprehend 'exp' in the logloss

**Comment by janelu9** [comment]
I have resolved this theoritically bug. the new result is numerical stability

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        # Do the forward algorithm to compute the partition function
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)

        # Iterate through the sentence
        for feat in feats:
            alphas_t = []  # The forward variables at this timestep
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        # Do the forward algorithm to compute the partition function
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)

        # Iterate through the sentence
        for feat in feats:
            alphas_t = []  # The forward variables at this timestep
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)
        for feat in feats:
            alphas_t = []  # The forward variables at this timestep
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):

        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)


        for feat in feats:
            alphas_t = []  
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)
        for feat in feats:
            alphas_t = []  
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)
        for feat in feats:
            alphas_t = []  
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
`    def _forward_alg(self, feats):
        
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)
        
        for feat in feats:
            alphas_t = []  
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha`

**Comment by janelu9** [comment]
```
    def _forward_alg(self, feats):
        
        alphas = [[0.] * self.tagset_size]
        alphas[0][self.tag2idx[START_TAG]] = 1
        alphas = nd.array(alphas)
        
        for feat in feats:
            alphas_t = []  
            for next_tag in range(self.tagset_size):
                emit_score = feat[next_tag].reshape((1, -1))
                trans_score = self.transitions.data()[next_tag].reshape((1, -1))
                next_tag_var = alphas *nd.exp( trans_score + emit_score)
                alphas_t.append(nsum(next_tag_var))
            alphas = nd.concat(*alphas_t, dim=0).reshape((1, -1))
        terminal_var = alphas *nd.exp( self.transitions.data()[self.tag2idx[STOP_TAG]])
        alpha = log_sum(terminal_var)
        return alpha
```
