### ISSUE TITLE
[Feature Request] Set context for entire file using single command

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#13326]
It would be a good feature to have a single command

`mx.context.set_context('gpu')`

whereby below that line, all the MXNet functions would be run with the context as `gpu`

Current scenario: Use `ctx` parameter for every single function.

Instead of asking the user to mention `ctx` for every function, one command per file would improve the user experience.

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot [add Feature Request]

**Comment by anirudh2290** [comment]
mx.test_utils.set_default_context does this.
