### ISSUE TITLE
MKLDNN LSTM Regression in MKLDNN 0.17

### ISSUE THREAD

**Issue by azai91** [apache/incubator-mxnet#13369]
We noticed that after the MKLDNN 0.17 update on 11/7 that our lstm models have lower throughput than before. https://www.dropbox.com/s/ifglj7lqcv4fw1q/Screenshot%202018-11-21%2017.41.30.png?dl=0

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Clone repo at git@github.com:mseth10/deeplearning-benchmark.git
2. Run the following script `python word_language_model/lstm_bucketing.py --num-hidden 650 --num-embed 650 --gpus 0 --epochs 30 --kv-store local`

**Comment by azai91** [comment]
@pengzhao-intel  created this issue to track progress

**Comment by pengzhao-intel** [comment]
Thanks to create the issue and we will submit PR to fix soon.

**Comment by vdantu** [comment]
@mxnet-label-bot add [MKLDNN, Performance]

**Comment by srochel** [comment]
@pengzhao-intel - added this issue to tracker of open issues for release 1.4.0. Appreciate resolution before code freeze on November 27, 2018.

**Comment by pengzhao-intel** [comment]
@srochel I am working with MKL-DNN team to fix the issue and will back the ETA to you.

**Comment by azai91** [comment]
Performance pre-mkldnn 0.17 (commit: 498e03da7ce420a48050fcd363aacb8dec2516f7)

2018-11-27 19:46:30,234 Epoch[0] Batch [0-50]	Speed: 31.46 samples/sec	perplexity=5543.863167
2018-11-27 19:47:14,732 Epoch[0] Batch [0-100]	Speed: 35.96 samples/sec	perplexity=3904.193633
2018-11-27 19:47:59,995 Epoch[0] Batch [0-150]	Speed: 35.35 samples/sec	perplexity=3247.239610
2018-11-27 19:48:49,773 Epoch[0] Batch [0-200]	Speed: 32.14 samples/sec	perplexity=2776.427683
2018-11-27 19:49:35,590 Epoch[0] Batch [0-250]	Speed: 34.92 samples/sec	perplexity=2494.544111
2018-11-27 19:50:23,366 Epoch[0] Batch [0-300]	Speed: 33.49 samples/sec	perplexity=2257.146195

**Comment by azai91** [comment]
Performance on current master (with regression) - consistent with with chart
Avg: 211.5 
```
2018-11-27 20:56:41,348 Epoch[0] Batch [0-50]	Speed: 196.48 samples/sec	perplexity=7615.827994
2018-11-27 20:56:49,490 Epoch[0] Batch [0-100]	Speed: 196.51 samples/sec	perplexity=4302.516596
2018-11-27 20:56:55,812 Epoch[0] Batch [0-150]	Speed: 253.12 samples/sec	perplexity=3541.693082
2018-11-27 20:57:03,411 Epoch[0] Batch [0-200]	Speed: 210.55 samples/sec	perplexity=3087.250013
```

**Comment by pengzhao-intel** [comment]
@azai91 please try the patch I sent to you by email. The final fix will go into MKL-DNN 0.17.1 and I will update to this release for MXNet.

**Comment by azai91** [comment]
@pengzhao-intel is the patch the latest version of mkldnn (84b2a5ae025c2730bb02e41b2fbf2f7b132f655c)

**Comment by azai91** [comment]
| Pre-0.17 (498e03da7ce420a48050fcd363aacb8dec2516f7) | Master | Patch
-- | -- | -- | --
  | 267.69 | 190.68 | 275.22
  | 279.78 | 176.55 | 267.68
  | 320.43 | 194.2 | 267.94
  | 285.07 | 201.84 | 310.52
  | 295.73 | 232.32 | 289.49
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
Average | 289.74 | 199.118 | 282.17

**Comment by pengzhao-intel** [comment]
Thanks, @azai91 I am working with MKL-DNN team to make the patch release out.

**Comment by pengzhao-intel** [comment]
@azai91 done, ping the v0.17.1

**Comment by kalyc** [comment]
@azai91 looks like this issue has been fixed? Can you verify and close the issue accordingly?

**Comment by azai91** [comment]
closing.
