### ISSUE TITLE
How to get the shape of a network?

### ISSUE THREAD

**Issue by Iamthep** [apache/incubator-mxnet#1337]
I am attempting to duplicate some of the work I have done using SparseConvNet using MXNet. However, I am not able to achieve the same results using MXNet with identical image augmentation and data set.  I think the difference must be in the network.

The standard network using SparseConvNet essentially starts at your last layer and defines it to be 1x1xFeatures wide and then works backwards from there.  For instance here is a partial log of something I get from SparseConvNet:
LeNetLayer 64 5 1 1 1 64C5 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 32 3 1 1 1 32C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 32 3 1 2 2 32C3 FilterStride 1 Dropout 0 VeryLeakyReLU MP2
LeNetLayer 64 3 1 1 1 64C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 64 3 1 2 2 64C3 FilterStride 1 Dropout 0 VeryLeakyReLU MP2
LeNetLayer 96 3 1 1 1 96C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 96 3 1 2 2 96C3 FilterStride 1 Dropout 0 VeryLeakyReLU MP2
LeNetLayer 128 3 1 1 1 128C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 128 3 1 2 2 128C3 FilterStride 1 Dropout 0 VeryLeakyReLU MP2
LeNetLayer 160 3 1 1 1 160C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 160 3 1 2 2 160C3 FilterStride 1 Dropout 0 VeryLeakyReLU MP2
LeNetLayer 192 3 1 1 1 192C3 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 192 1 1 1 1 192C1 FilterStride 1 Dropout 0 VeryLeakyReLU
LeNetLayer 6 1 1 1 1 6C1 FilterStride 1 Dropout 0 Softmax ClassificationSpatially sparse CNN: input size 224x224

Here, the input size is 224x224.  From here I just drop my images somewhere inside of that field.  
As you can see here, the layer sizes progress form 1x1, 3x3, 6x6, 8x8, 10x10, 20x20, 22x22, 24x24, 48x48, 50x50, 52x52, 104x104, 106x106, 108x108, 216x216, 218x218, 220x220, 224x224.

MXNet seems to work differently.  Here it seems you specify the input layer size (data_shape) and then everything feed forwards.  Somewhere towards the end there is usually a flatten layer followed by a fully connected layer.

I would like to see the shapes of each layer given the data_shape, but I am having a hard time figuring it out.

I tried
arg_names = softmax.list_arguments()
arg_shape, out_shape, aux_shape = softmax.infer_shape(data=(100,3,190, 190))
print (aux_shape)  

Please note that my actual data_shape is (3,190,190)

It does give me the shapes of the bias/convs/weights in arg_shape, but out_shape gives 100,6 and then nothing.  And aux_shape just comes out as (none,none, none)

Can anyone tell me what I am doing wrong?

**Comment by shuokay** [comment]
#1090

**Comment by winstywang** [comment]
I will add an option to print out the shapes in the next week.

**Comment by DW9363** [comment]
Is this fixed ?

**Comment by j1mehta** [comment]
You can use print_summary() from visualization.py
Usage:
`mxnet.visualization.print_summary(<NeuralNetSymbol>, shape={'data':(100,3,1152,832)})`
_shape_ is Input shape of data that should be a dictionary with key as _data_ and dimensions as
_noof instances, channels, height, width_.

**Comment by j1mehta** [comment]
Use
