### ISSUE TITLE
Support sparse as return in topK? 

### ISSUE THREAD

**Issue by zerolxf** [apache/incubator-mxnet#13372]
## Description
why not support sparse as return in [topK](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.topk)? 

When k is relatively small, it is very sparse.
It is more efficient than "mask" and simpler than "both".Sparse in distributed transmission saves time.
I want to implement the optimizer described in the paper *Sparsified SGD with Memory*, available at https://arxiv.org/abs/1809.07599

**Comment by vdantu** [comment]
@mxnet-label-bot add [Operator, Question]

**Comment by marcoabreu** [comment]
@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
@zerolxf the topk op returns the top k values in the tensor of certain axis, and the shape of the output depends on k. Are you suggesting a new return type that returns a sparse mask?

**Comment by eric-haibin-lin** [comment]
@zerolxf is it ok to close the issue?
