### ISSUE TITLE
the official image-classification predict-cpp demo crashed if...

### ISSUE THREAD

**Issue by MaeThird** [apache/incubator-mxnet#13370]
In the '**example/image-classification/predict-cpp**' demo, if I comment out the "predict" process,the code would be crashed.I mean **initialize the PredictorHandle but not do the predict the demo would be crashed with or without the MXPredFree(pred_hnd) doesn't matter**.
In my case I must split away the "**initialize of PrdictorHandler**" with "**forward process**" as is really necessary in the product environment .So, to avoid  the crash I used dummy input data after the initialization to do the forward once and feed in the real data in the next process.But to my surprise,no matter what the input data is , the network's output is **always the same as the first forward's**.
I'm new here.Any one can help ?

MXNET : newest fetched  from master.

**Comment by vdantu** [comment]
@mxnet-label-bot add [C++, Example, Question]

**Comment by MaeThird** [comment]
ha ... the "always the same as the first forward's output" is my fault.Sorry about this.But the crash caused by comment out "predict" still happened in the official demo.
