### ISSUE TITLE
How to release GPU memory by CPP interface? 

### ISSUE THREAD

**Issue by DuCheng2018** [apache/incubator-mxnet#13373]
I need to do a forward propagation at first, and then do another one in the same process.
If gpu memory malloced by the first propagation can not be released, the second one will not have enough memory to use.
How to deal with it ?

**Comment by vdantu** [comment]
@mxnet-label-bot add [C++, Question]

**Comment by DuCheng2018** [comment]
I find a interface named MXNDArrayFree( ) and MXSymbolFree( ) in c_api.h of mxnet. But when I use them, they do not work well.

**Comment by DuCheng2018** [comment]
I find that GPUPooledStorageManager::Free() reuse the memory pool instead of releasing it. And GPUPooledStorageManager::ReleaseAll() clear the memory pool. However, in NDArray Class, GPUPooledStorageManager::ReleaseAll() is never used. 
What if I imply release function in Class of StorageImpl and call it in NDArray::Chunk::~Chunk()?

**Comment by DuCheng2018** [comment]
I open a feature request, so I close this issue.
