### ISSUE TITLE
how to carry out unit test on essential classes

### ISSUE THREAD

**Issue by cyh-ustc** [apache/incubator-mxnet#13389]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
I've tried to make a few modification to mxnet including graph executor, op executor, ndarray etc. It seems that there isn't any c++ unittest on those essential classed. Existing c++ unittest(mxnet_unit_test) doesn't test on single class or class's member functions. While, in tensorflow, every essiensial class contains unittest, and those tests covers almost every member functions. So, how to validate those classes? ps. python unittest in mxnet seems to be more complete.  

## Environment info (Required)
x86-64-linux-cuda
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)
python
For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)
gcc  nvcc
Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:388a5f483483b1dc07b2f46f182bd00fa7505732
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)
cmake -DUSE_CUDNN=OFF -DUSE_CUDA=OFF -DUSE_MKLDNN=OFF -DBLAS=Open -DCMAKE_BUILD_TYPE=Release ..
## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by marcoabreu** [comment]
Hello,

that's correct. We mainly use Python tests to validate our backend. We also have some C++ tests, but for most developers it's simply faster to write them in Python than in C++, hence the focus on Python.

Best regards,
Marco

**Comment by KellenSunderland** [comment]
Agree with Marco's points, but just wanted to mention that we're certainly open to adding C++ tests for classes like the engine.  I see a number of advantages for having C++ tests:

* First cost and execution time is substantially less for C++ tests.
* Some of the platforms we'd like to support don't have full python installations, and some customers choose not to install python in their build systems, so having some tests that work without python is nice.
* Some behaviours of the engine are abstracted and non-testable from the Python level.  This leads to a lot of non-deterministic behaviour at the Python level that could be tested deterministically at the C++ level.

So the summary for me is that we have reasonably good critical class coverage from Python tests (which we actually measure), but adding some key C++ tests especially for these classes would be beneficial.

**Comment by vdantu** [comment]
@mxnet-label-bot add [c++, question, test]

**Comment by leleamol** [comment]
The question is not related to C++ frontend API  hence removing the C++ label.

**Comment by leleamol** [comment]
@mxnet-label-bot update [Question, Test, Feature Request]
