### ISSUE TITLE
[Clojure] - Add Clojure to the main website docs install 

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#13388]
Currently Clojure doesn't appear as an option on the main install page of MXNet https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Scala&processor=CPU

![installing_mxnet_ _mxnet_documentation](https://user-images.githubusercontent.com/340299/48959822-0a9af500-ef36-11e8-8c56-ad4e67eb42b9.png)

But the default install option should be almost exactly like Scala since it is a maven package 
https://search.maven.org/search?q=clojure%20mxnet

The documentation to be modified is found here https://raw.githubusercontent.com/apache/incubator-mxnet/master/docs/install/index.md

To test out the results of the change and see what it looks like seehttps://github.com/apache/incubator-mxnet/tree/master/docs/build_version_doc

There is also a Dockerfile to build the website that might be useful
https://github.com/apache/incubator-mxnet/blob/master/docs/build_version_doc/Dockerfile

**Comment by anujsrc** [comment]
@gigasquid - I have submitted https://github.com/apache/incubator-mxnet/pull/13393 and in the description, I have requested readers to review MXNet Scala Setup guide as well before using Clojure dependency.

**Comment by gigasquid** [comment]
Awesome! Thank you 💯
