### ISSUE TITLE
[Clojure] - Port Scala Inference to Clojure Package

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#13384]
The Scala package has a very nice inference package. It would be nice to port it to the Clojure API.

Here is the scala code https://github.com/apache/incubator-mxnet/tree/master/scala-package/infer/src/main/scala/org/apache/mxnet/infer

It would involve creating the corresponding Clojure namespaces and doing the correct interop with the code. It would also need the corresponding unit tests. https://github.com/apache/incubator-mxnet/tree/master/scala-package/infer/src/test/scala/org/apache/mxnet/infer

Finally Porting the examples over to the Clojure examples would be great
https://github.com/apache/incubator-mxnet/tree/master/scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer

This is a bigger chunk of feature work - but it will be very useful to Clojure users. If someone needs assistance with this, I would be happy to help out / mentor.

**Comment by gigasquid** [comment]
@kedarbellare Awesome! No rush. Feel free to ping me here or on slack 😸

**Comment by hellonico** [comment]
IMHO, if the Clojure examples are based on the scala examples, it would be nice to have them in the examples folder. 

Then, just like the other examples, we can just add the  few extra bits necessary to make then run as tests in the integration suite.

**Comment by gigasquid** [comment]
Thanks @kedarbellare for making this happen 💯
