### ISSUE TITLE
Wrong documentation in Optimization API

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#13429]
NDAbs should not show under Optimization API

![screen shot 2018-11-27 at 3 38 05 pm](https://user-images.githubusercontent.com/2778341/49118800-94123600-f25a-11e8-9d98-c8217fafd9de.png)

@aaronmarkham

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Doc, Bug]

**Comment by aaronmarkham** [comment]
Note: `NDAbs` also does not appear on the beta site at all... which is interesting...

The source is here:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer/optimizer.py#L28
Or more likely:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer/optimizer.py#L39

It does not appear in the autosummary and is not listed in the docs for a signature to be provided.
https://mxnet.incubator.apache.org/api/python/optimization/optimization.html?highlight=ndabs#the-mxnet-optimizer-package
In the API Reference section, automodule is generating all members of optimizer, so this must be where it is coming from.
Using this may fix it:
```
:exclude-members: NDAbs
```
But we also need to see why this doesn't appear on beta.

**Comment by anirudhacharya** [comment]
@aaronmarkham are we tracking this on the beta site github repo?

**Comment by aaronmarkham** [comment]
So where should `NDabs` be? I only see it mentioned twice in the code as some way to call `abs`. Is there a good reason for that? Why not just import it as `abs` so Sphinx doesn't try to include it... or set it up so Sphinx can document it?

**Comment by anirudhacharya** [comment]
@aaronmarkham `NDabs` should be under NDArray API.

> I only see it mentioned twice in the code as some way to call `abs`. Is there a good reason for that?

I am not sure of this.
