### ISSUE TITLE
install page selector logic broken

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13430]
## Description
Based on how the selector appears to be designed, you add multiple classes to a div and they will share the same content. It doesn't work when you get to the version level.
The following code should work to share common content:
```
<div class="clojure">
<div class="gpu">
<div class="master v1-3-0">
Install instructions for both master and v1.3.0...
...
</div></div></div>
<div class="1-2-1 1-1-0 1-0-0">
Then older versions see something else
</div>
```
It doesn't work. All of the versions get the top code block.
Then if you break it out and use:
```
<div class="1-2-1">
This older version sees one thing
</div>
<div class="1-1-0">
This older version sees a second thing
</div>
<div class="1-0-0">
This older version sees a third thing
</div>
```
You get the same output for every version all at once:
```
This older version sees one thing
This older version sees a second thing
This older version sees a third thing
```

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Doc]

**Comment by aaronmarkham** [comment]
New website launch makes this a moot issue.
