### ISSUE TITLE
Upgrade CMake to at least 3.10 for NVCC Ccache support 

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#13459]
We need to upgrade to at least 3.10 in order to support CCache for NVCC: https://github.com/pytorch/pytorch/issues/8433

Details available at https://gitlab.kitware.com/cmake/cmake/issues/16953

We currently run CMake 3.5.1

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Build, CMake]
