### ISSUE TITLE
[Feature Request] Release gpu memory by API.

### ISSUE THREAD

**Issue by DuCheng2018** [apache/incubator-mxnet#13482]
## Description
When it is required to do a forward propagation at first, and then do another one in the same process, 
if gpu memory malloced by the first propagation can not be released, the second one will not have enough memory to use.

**Comment by vrakesh** [comment]
@DuCheng2018 Thank you for the feature, request.

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Feature]

**Comment by zhreshold** [comment]
I am getting multiple request similar to this one, I think we need a formal C API as well as python API so user can explicitly release gpu memory pool without waiting for program to exit.

**Comment by haoxintong** [comment]
+1, for some application it is necessary to release gpu memory.

**Comment by relaxli00** [comment]
+1, yes, this is a function needed badly

**Comment by GoGoGoWarriors** [comment]
+1

**Comment by hdjsjyl** [comment]
+1

**Comment by kohillyang** [comment]
+1

**Comment by HermanLiu1** [comment]
+1

**Comment by fallingdust** [comment]
+1

**Comment by fe-codes** [comment]
+1

**Comment by cgraywang** [comment]
+1

**Comment by Shicc** [comment]
+1

**Comment by yuyijie1995** [comment]
+1

**Comment by noodle-overflow** [comment]
+1

**Comment by evi-Genius** [comment]
+1

**Comment by Wondersui** [comment]
+1

**Comment by anonymouslycn** [comment]
+1

**Comment by khui** [comment]
+1

**Comment by hgt312** [comment]
+1

**Comment by smartwell** [comment]
+1

**Comment by Kongsea** [comment]
+1

**Comment by levinguyen** [comment]
+1

**Comment by wkcn** [comment]
Hi, there.
Thank @vladoovtcharov for adding this API for GPU memory release.
The API is `mx.gpu(0).empty_cache()`.
Firstly, we should set the environment variable `MXNET_GPU_MEM_POOL_TYPE` to use GPU memory pool.

Here is an example:
```
# MXNET_GPU_MEM_POOL_TYPE=Round python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> a = mx.nd.zeros((1000, 1000), ctx=mx.gpu(0)) + 1
[14:56:53] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
>>> a = mx.nd.zeros((10000, 30000), ctx=mx.gpu(0)) + 1
>>> del a
>>> mx.gpu(0).empty_cache()
```

In my test, the most GPU memory will be released after calling this API, although there is still around 600Mib memory cache.

**Comment by szha** [comment]
This API only releases the cache in the GPU memory pool. It doesn't release the NDArray cache held by CachedOp

**Comment by ymzx** [comment]
+1

**Comment by zhreshold** [comment]
Closing this issue as #14252 is merged, please feel to ping me if you have other thoughts.
