### ISSUE TITLE
MKLDNN int8 support

### ISSUE THREAD

**Issue by azai91** [apache/incubator-mxnet#13516]
MKLDNN 0.17 release states that it supports int8 quantization (https://github.com/intel/mkl-dnn/releases). However, we run into the following issue when we comment out this line 
```
mxnet.base.MXNetError: [15:57:38] src/operator/nn/mkldnn/mkldnn_convolution.cc:140: Check failed: conv_pd.next_impl() No implementation
```

To reach this, I had to comment out this line of code:
(https://github.com/apache/incubator-mxnet/blob/5111b187e3d8917d45a2482ceaf44b42588eff51/src/operator/subgraph/mkldnn/mkldnn_conv.cc#L346).

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Pending

**Comment by pengzhao-intel** [comment]
@azai91 Thanks for raising the issues. 
We already have the implementations in local and will PR soon (just wait a moment for r1.4 cut before).
@ZhennanQin

**Comment by pengzhao-intel** [comment]
@azai91 we need more validation with the real workload since the int8 network is not too much in the hand.

**Comment by ZhennanQin** [comment]
Corresponding PR is filed at: https://github.com/apache/incubator-mxnet/pull/13697

**Comment by TaoLv** [comment]
#13697 is merged. Closing this issue now.
