### ISSUE TITLE
MXNET can't build from source on MKLDNN enabled

### ISSUE THREAD

**Issue by juliusshufan** [apache/incubator-mxnet#13524]
## Description
On building MXNET from soure with the command:
make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl

The compiling always failed with error as below:

In file included from src/operator/nn/mkldnn/mkldnn_base.cc(23):
src/operator/nn/mkldnn/./mkldnn_base-inl.h(57): catastrophic error: cannot open source file "mkldnn.hpp"
  #include "mkldnn.hpp"
                       ^
In file included from src/operator/quantization/mkldnn/mkldnn_quantized_conv.cc(27):
src/operator/quantization/mkldnn/../../nn/mkldnn/mkldnn_base-inl.h(57): catastrophic error: cannot open source file "mkldnn.hpp"
  #include "mkldnn.hpp"

Seems this is introduced by commit 65edc9500b10a3404945d6d79acbae54a2833890 (@azai91), as the compilation is okay on commit 89499896108ac37f87afbe03ddad658b466deba7 **_with same build command._**

## Environment info (Required)
CentOS 7.5
GCC 4.8.5
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): gcc 4.8.5

MXNet commit hash:
f2dcd7c7b8676b55d912997fc3f9c62c55915307
(Paste the output of `git rev-parse HEAD` here.)

Build config:
make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl

## Error Message:
In file included from src/operator/nn/mkldnn/mkldnn_base.cc(23):
src/operator/nn/mkldnn/./mkldnn_base-inl.h(57): catastrophic error: cannot open source file "mkldnn.hpp"
  #include "mkldnn.hpp"
                       ^
In file included from src/operator/quantization/mkldnn/mkldnn_quantized_conv.cc(27):
src/operator/quantization/mkldnn/../../nn/mkldnn/mkldnn_base-inl.h(57): catastrophic error: cannot open source file "mkldnn.hpp"
  #include "mkldnn.hpp"
## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Clone the code 
2. make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl

@TaoLv @pengzhao-intel

**Comment by azai91** [comment]
looking into

**Comment by azai91** [comment]
I believe the issue is with mkl. system builds fine with openblas. 
```
make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=openblas
```

our CI does not test mkl blas.

**Comment by azai91** [comment]
looking into fixing.

**Comment by Vikas89** [comment]
@azai91  Can we revert this first and then work on the fix ?

**Comment by azai91** [comment]
@juliusshufan can you build this with cmake?
```
cmake -DUSE_MKLDNN=1 -DBLAS=MKL -GNinja -DUSE_CUDA=OFF -DUSE_CUDNN=OFF .. && ninja
```

**Comment by azai91** [comment]
Reverting. https://github.com/apache/incubator-mxnet/pull/13540

**Comment by juliusshufan** [comment]
@azai91 Thanks for prompt fix, the compilation is okay now. I close the issue accordingly.
