### ISSUE TITLE
Scala jar contains the scala standard library

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#13528]
## Description

Created scala package with make && make scalapkg

Following command shows that it contains the scala standard library in addition to mxnet classes.
```
jar tvf ./scala-package/assembly/osx-x86_64-cpu/target/mxnet-full_2.11-osx-x86_64-cpu-1.4.0-SNAPSHOT.jar
```

## Environment info (Required)

f2dcd7c7b8676b55d912997fc3f9c62c55915307

**Comment by larroy** [comment]
@nswamy @lanking520

**Comment by lanking520** [comment]
@larroy Hi Pedro, indeed. It contains all Scala needs. You can run your code by simply starting with 
```
java -cp
```

**Comment by larroy** [comment]
This doesn't sound like a good idea. Libraries shouldn't include the scala standard library. You should use scala -cp to run , and not java -cp.

**Comment by lanking520** [comment]
In fact, all Scala code are generated to `.class` file when we build the jar and I think it is JVM code. In that case, `java -cp` is consider as a super class of `scala -cp`. What do you think?

**Comment by larroy** [comment]
While I think is ok to provide a fat jar for people trying MXNet in the console as you point out, we should provide a standard version with just MXNet and the binary dynamic libraries inside, without standard scala library or other dependencies that can be pulled from maven.

Some of the comments I got from other engineers when I explained this issue were: "Definitely not. Maven artifacts should not be fat jars. The jar should only include classes and resources that are part of the enclosing project.
maven has a concept of "assembly" builds and repo can have those types of artifacts published, but that obvioulsy should be clearly documented or has designated classifier to warn consumers
In any case the build should not replace the default artifact with the output of an assembly build that pulls all dependencies, especially if this jar is then published to a Maven repository and can be imported by other Maven projects. 
"

I don't want to irritate anyone with this issue because you guys have done great work putting the Scala package forward. But my feedback about this topic stands as it is if there's no new information provided.

I asked to other senior engineers in Amazon about this issue and their feedback was the same as mine with regards to this issue, as you can read above. They also having plenty of experience running big java / scala projects. I have maintained Spark myself inside amazon for a few releases (it's a huge project)  and worked in big Scala projects for Amazon which are now in production (SageMaker) and other companies, so I think I know one thing or two about Scala and dependencies.

I suggest you guys do your due diligence about this topic and find out what's the best practice if my arguments are not convincing. If you need people to contact to gather more opinions I can suggest the Scala lists inside Amazon or I can provide some names. 

If you need more help or feedback from my side, let me know. Happy to help.

**Comment by larroy** [comment]
That's why maven / SBT etc. have the concept of transitive dependencies:

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

slf4j and scala language should not be in the package. Only libmxnet.so/jnilib Dependencies from the MXNet backend and libmxnet.so/jnilib Dependencies from the MXNet backend.

What you describe is considered a bad practice.

**Comment by lanking520** [comment]
@larroy This problem are fixed now. We include them into the pom file instead of binding together. Please feel free to close this issue

**Comment by piyushghai** [comment]
@larroy I'm suggesting to close this issue, since we've dealt with it now. 
Please feel free to re-open it if closed in error.

@lanking520 Can you close this issue ?

**Comment by lanking520** [comment]
Close it for now, please feel free to reopen if you are still seeing the same problems in the package
