### ISSUE TITLE
can't restart CI website test

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13552]
## Description
This pipeline test failed because it couldn't reach github.
Not only is this a transient issue that we should probably have at least one or two retries for, I can't seem to restart this job.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwebsite/detail/PR-13544/2/pipeline
It looks like I have to run the whole thing through CI again. Does that mean there's a bug in the pipeline itself? Why won't it restart? I've seen this happen a few times now.

**Comment by lanking520** [comment]
I am also facing this issue last time.

**Comment by piyushghai** [comment]
@aaronmarkham @lanking520 Now you can restart a single job on the CI without going through all the tests again. This issue was resolved sometime back.

@lanking520 Suggest to close the issue. Please feel free to re-open if closed in error.
Thanks!

**Comment by lanking520** [comment]
@aaronmarkham Close it for now. Please feel free to reopen if the issue persist
