### ISSUE TITLE
moveaxis doesn't support negative indices

### ISSUE THREAD

**Issue by asmeurer** [apache/incubator-mxnet#13563]
The moveaxis method doesn't support negative indices. Something like

```
if source < 0: source = axes[source]
if target < 0: target = axes[target]
```

should fix it. It also doesn't support lists of indices like NumPy.

**Comment by lanking520** [comment]
Hi @asmeurer thanks for your issue, 
asked someone to take a look here: @apeforest @samskalicky

**Comment by apeforest** [comment]
@mxnet-label-bot Add [Operator]

**Comment by ifeherva** [comment]
I have an implementation already just need to ask tests and will PR.

**Comment by ifeherva** [comment]
See PR here
https://github.com/apache/incubator-mxnet/pull/14321

**Comment by haojin2** [comment]
Closing the issue since it's been fixed, also in the new `mxnet.np` module:
```Python
>>> from mxnet import np
>>> x = np.zeros((3, 4, 5))
>>> np.moveaxis(x, [0, 1], [-1, -2]).shape
(5, 4, 3)
```
