### ISSUE TITLE
distributed trainig ,  build from soure code ?

### ISSUE THREAD

**Issue by Davdi** [apache/incubator-mxnet#13560]
is it necessary  to build from source code for distributed traing on muti-machine ?
 in default the make/config.mk USE_DIST_KVSTORE = 1
if i install mxnet through pip install mxnet-cu92 ,is this value of USE_DIST_KVSTORE  1?

**Comment by TaoLv** [comment]
Hi @Davdi , please refer the compilation flag table in https://github.com/apache/incubator-mxnet/issues/8671 for detailed configurations.

**Comment by Davdi** [comment]
> Hi @Davdi , please refer the compilation flag table in #8671 for detailed configurations.
