### ISSUE TITLE
What will be theRecommended & tested Edge Device

### ISSUE THREAD

**Issue by MyraBaba** [apache/incubator-mxnet#13561]
We would love to use Mxnet in our edge devices.

What will be the recommended & tested devices for the inference ?  model size around 150MB  and 1 sec around is ok for inference time.

Raspbery pi ? Hikey 970 ? Odroid Xu4 . or intels mini pcs? 

is there any experience ?

thx

**Comment by lanking520** [comment]
Hi @MyraBaba thanks for your question!
@larroy @lebeg Any thoughts for Edge Device?

**Comment by MyraBaba** [comment]
We would love to tranfer our platform to the Mxnet if we found a reasonable edge devices both pysical size and the cost (around 400 - 500 usd).

And inference time should be max 1-2 sec.

What jetson kit did you tested ?  TX1 or TX2 . and what would be the benchmarks (specially face deetction & recognition)

**Comment by lebeg** [comment]
Yes, I suggest [Jetson TX2 Developer Kit](https://developer.nvidia.com/embedded/buy/jetson-tx2) or RaspberryPi. These are supported and tested on. Potentially, you could use an Android as well, but that's tested no so well.

**Comment by larroy** [comment]
You can use any ARMv7 or ARMv8 board with Linux depending on your needs. I tested in other arm boards such as bananapipro and Tx2 is ARMv8. If you want to be fast as @lebeg recommended try jetson with GPU. If you use intel mini PC with GPU it's no difference from any other intel based CPU. Intel mini PC with a low end nvidia  1050 or smaller if your model fits would be the safest / easyest in therms of development headaches, as you won't have to cross compile.

**Comment by MyraBaba** [comment]
Jetson TX2 and the intel mini (really mini :) seems to better fits our edge devices. As far as I googled all mini pc's (intel) not smaller as we expected.  Still looking to find a small intel based (4core min) HW.

Best & Thx

**Comment by larroy** [comment]
@anirudh2290 let's close
