### ISSUE TITLE
[Clojure] - Add Clojure to the main README

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#13580]
Clojure is not mentioned in the main project README as a supported language.

This issue would be to add it in the text:
`Support for Python, R, Scala, C++ and Julia`

Bonus if it can be added to the language binding image too. We do have permission to use the Clojure logo in this scenario.

<img width="957" alt="missing_clojure" src="https://user-images.githubusercontent.com/340299/49664092-d7209600-fa1e-11e8-9d7e-75a1990da20a.png">

**Comment by larroy** [comment]
@kpmurali do we have the original source for that file?

**Comment by lanking520** [comment]
@aaronmarkham If you would like to have a new image to replace the portable section

**Comment by ThomasDelteil** [comment]
See https://github.com/dmlc/web-data/pull/152 and https://github.com/apache/incubator-mxnet/pull/13973

**Comment by gigasquid** [comment]
Thanks @ThomasDelteil !
