### ISSUE TITLE
ImportError: cannot import name CachedOp

### ISSUE THREAD

**Issue by jiangzhengkai** [apache/incubator-mxnet#13587]
Hi, I meet this error after i successfully compile mxnet. The detail output information is as following:

![image](https://user-images.githubusercontent.com/19780166/49685433-2a2d4280-fb1e-11e8-9e12-3d3dd5cb02f8.png)

Anyone help me?

Thanks

**Comment by marcoabreu** [comment]
Could you double check you are running on the latest version of mxnet? It seems like you are trying to use an installed 0.10.0 in combination with some of the latest code.

**Comment by marcoabreu** [comment]
CachedOp has only been introduced recently, so it seems like you did not check it out properly.

Any specific reason you are using 0.10? It's quite old and it's difficult for us to provide support for that. The latest version is 1.3.1 FYI

**Comment by lanking520** [comment]
In this case, as @marcoabreu suggested, please use the latest package from pip or build from source from an official release branch.

**Comment by jiangzhengkai** [comment]
@marcoabreu @lanking520 Thanks, the error disappears on the latest mxnet.

**Comment by marcoabreu** [comment]
Great to hear! Could you elaborate what lead you to using 0.10? That way, we can avoid further users running into the same problem

**Comment by jiangzhengkai** [comment]
@marcoabreu I'm running DFF code from MSRA, they suggest to use this version mxnet.

**Comment by marcoabreu** [comment]
Interesting, do you have a link on hand by any chance?
