### ISSUE TITLE
Inplace Reshape?

### ISSUE THREAD

**Issue by Jerryzcn** [apache/incubator-mxnet#13581]
https://github.com/apache/incubator-mxnet/blob/49e6a7e40691936e533f7cf16848b10c025e4e75/src/operator/tensor/matrix_op.cc#L176

https://github.com/apache/incubator-mxnet/blob/ebe6ea8be97506dba7d00b5a25da58433e38caae/src/operator/tensor/elemwise_unary_op.h#L281

Currently reshape seems to copy the source tensor, which slows down various application. e.g. Gluon-CV.

There is a inplace_reshape here:
https://github.com/apache/incubator-mxnet/blob/6d5e3cb42e088c99be785ca1b43fcc1d08146f53/src/operator/tensor/ordering_op-inl.h#L41

however, it is not exposed and does not support all the feature that reshape currently has

Any plan to add inplace reshape？

Thanks!

**Comment by lanking520** [comment]
@apeforest

**Comment by pengzhao-intel** [comment]
@zhennanqin has looked into this OP and tried inplace optimization previously :)
Maybe he can give some inputs

**Comment by ZhennanQin** [comment]
Hi Jerryzcn, thanks for raising this. `Reshape` has `FInplaceOption` and `FInplaceIdentity` attrs, which means its input and output are force inlined. 
https://github.com/apache/incubator-mxnet/blob/49e6a7e40691936e533f7cf16848b10c025e4e75/src/operator/tensor/matrix_op.cc#L177

For the copy you mentioned, current implementation will do copy even when input and output are in-placed. Probably you can add a check in copy function, to skip the operation at that situation.

**Comment by Jerryzcn** [comment]
@ZhennanQin I think the inplace version does not work actually properly, I have tried 
```F.reshape(x, (shape), out=x)``` and it did not work..

**Comment by Jerryzcn** [comment]
@ZhennanQin It complains that shape mismatch. 
Actually I found something in my previous code that have caused a bug that lead me to think that reshape occupied extra memory. However that is not the case. I will close the issue for now.
