### ISSUE TITLE
SymbolBlock doesn't print anything

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#13616]
When I print a symbolblock loaded from a json file, printing it doesn't help me at all:

```
>>> block = mx.gluon.nn.SymbolBlock.imports('test.json-symbol.json', ['data'], 'test.json-0000.params')
SymbolBlock(

)
```
It does not show anything useful to help me understand what is in the block, even for symbols exported from `nn.Dense(1)`

**Comment by vdantu** [comment]
@mxnet-label-bot add [Gluon, question]

**Comment by Ishitori** [comment]
I confirm this behavior, and here is the minimal reproducible example:

```
import mxnet as mx
from mxnet.gluon.nn import HybridSequential, Dense

model = HybridSequential()
model.add(Dense(units=10))

model.initialize()
model.hybridize()

model(mx.random.uniform(shape=(10, 100)))
model.export("./model")

block = mx.gluon.nn.SymbolBlock.imports('model-symbol.json', ['data'], 'model-0000.params')
print(block)
```

Result that is printed on the screen looks like:

```
SymbolBlock(

)
```

Funny that both pure Gluon and pure Symbol models are still printing something. For Gluon model I would receive expected output:

```
HybridSequential(
  (0): Dense(100 -> 10, linear)
)
```

For same model using Symbolic API I receive only the name of the last layer (not very useful, but still it is something):

```
<Symbol fc1>
```

I would mark this issue as a bug.

**Comment by eric-haibin-lin** [comment]
Maybe we can print the json representation
