### ISSUE TITLE
add weighted softmax loss

### ISSUE THREAD

**Issue by haibo-qiu** [apache/incubator-mxnet#13613]
Hello, My dataset is imbalanced, which means the number of positive class is much less than that of negative class. I want to make the positive loss has weight. I know that I can repeat sample the positive loss, but I want to add weight. How can make it? 
Thanks so much.

**Comment by vdantu** [comment]
@mxnet-label-bot add [question]

**Comment by vuvko** [comment]
You can look at several implementations. For example: https://stackoverflow.com/a/48874517 https://github.com/apache/incubator-mxnet/blob/v1.0.0/example/sparse/weighted_softmax_ce.py

**Comment by vdantu** [comment]
@vuvko : Thanks for the reply.

@haibo-qiu : Would the above examples help you?

**Comment by vdantu** [comment]
@mxnet-label-bot add [pending-requester-info]

**Comment by vrakesh** [comment]
@haibo-qiu Pinging to know if the examples were able to answer your question.  If they did , requesting you to close the issue
