### ISSUE TITLE
Build from source is broken on USE_MKLDNN=1

### ISSUE THREAD

**Issue by juliusshufan** [apache/incubator-mxnet#13636]
## Description
Build from source currently does not work on mxnet repo on github. 
Seems the build is okay with commit afb670353c0355c85dfae5573c8461370b03af2e
@azai91 @anirudh2290 

## Environment info (Required)
GCC 4.8.5 CentOS 7.5.1804
```
What to do:
1. Git clone the code
2. Run make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl

```
Package used (Python/R/Scala/Julia): Python 3.6
(I'm using ...)

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): GCC 4.8.5

MXNet commit hash:
5bcf2bd6e8b48fa27bfcfdafd06401ec2d28978b

Build config:
make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl

## Error Message:
a - build/src/initialize.o
/usr/bin/ld: cannot find -lmklml_intel
/usr/bin/ld: cannot find -lmklml_gnu
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lmklml_intel
/usr/bin/ld: cannot find -lmklml_gnu
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1
~/workspace/validation/mxnet

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by anirudh2290** [comment]
Thanks for reporting @juliusshufan . This test fails only on centos 7.5 and not ubuntu ? MKL build has been added to CI as part of: https://github.com/apache/incubator-mxnet/pull/13607/ .
Do we need to add a centos stage too ? @xinyu-intel @pengzhao-intel

**Comment by vdantu** [comment]
@mxnet-label-bot add [build, breaking]

**Comment by azai91** [comment]
@Vikas89 @mseth10

**Comment by xinyu-intel** [comment]
@anirudh2290 I think this is due to the ci system install mklml in /usr/lib before building mxnet with mkldnn. I'll open a PR to disable it.

**Comment by juliusshufan** [comment]
thanks all, this issue now fixed, issue closed accordingly.

**Comment by mseth10** [comment]
@xinyu-intel @juliusshufan Do we have a PR adding CentOS MKL to the CI? Can you please share the status and let us know if you need any help on that. It's a blocker for us to get the static linking feature pushed.

**Comment by TaoLv** [comment]
@mseth10 Why need have CentOS MKL in CI? I think @juliusshufan just shared his environment information as the issue template required. It doesn't necessarily mean that the issue only happens on CentOS and MKL BLAS.

**Comment by mseth10** [comment]
@TaoLv The build issue on CentOS MKL occurred when we tried to statically link MKL-DNN https://github.com/apache/incubator-mxnet/pull/13503, which passed all the MKL CI tests on Ubuntu. We reverted this static linking PR https://github.com/apache/incubator-mxnet/pull/13540 temporarily, but would like to merge it back. Having MKL on CI for other OS would help us identify such build issues before merging. What are your thoughts on this?
@xinyu-intel Does your PR https://github.com/apache/incubator-mxnet/pull/13643 fix the build issue? Can we go ahead and re-revert the static linking PR after your PR is merged?

**Comment by xinyu-intel** [comment]
@mseth10 It's okay to add MKL env to CentOS if you really want but, as I said before, last time #13503 passed all the MKL CI tests on Ubuntu was caused by a pre-installed `libmklml_intel.so` in `usr/lib`. So, please kindly wait #13643 to fix the CI ENV and then you can go ahead to enable static linking.
