### ISSUE TITLE
error in the train_minst.py image classification example

### ISSUE THREAD

**Issue by giordyb** [apache/incubator-mxnet#13649]
## Description
when running the gpu training validation example listed in https://mxnet.apache.org/install/validate_mxnet.html 

`python example/image-classification/train_mnist.py --network lenet --gpus 0`

the script throws an error about mx.lr_scheduler.MultiFactorScheduler() not having the argument 'base_lr'

this is the complete error

`INFO:root:start with arguments Namespace(add_stn=False, batch_size=64, disp_batches=100, dtype='float32', gc_threshold=0.5, gc_type='none', gpus='0', image_shape='1, 28, 28', ini
tializer='default', kv_store='device', load_epoch=None, loss='', lr=0.05, lr_factor=0.1, lr_step_epochs='10', macrobatch_size=0, model_prefix=None, mom=0.9, monitor=0, network='l
enet', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', profile_server_suffix='', profile_worker_suffix='', save_period=1, test_io=0, top_k=0,
 warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 97, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/root/incubator-mxnet/example/image-classification/common/fit.py", line 220, in fit
    lr, lr_scheduler = _get_lr_scheduler(args, kv)
  File "/root/incubator-mxnet/example/image-classification/common/fit.py", line 53, in _get_lr_scheduler
    base_lr=args.lr))
TypeError: __init__() got an unexpected keyword argument 'base_lr'`
## Environment info (Required)
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Nov 12 2018 14:36:49'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '18.1')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
('Version      :', '1.3.1')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/mxnet')
('Commit Hash   :', '19c501680183237d52a862e6ae1dc4ddc296305b')
----------System Info----------
('Platform     :', 'Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('node         :', '13dfa5d30337')
('release      :', '3.10.0-862.14.4.el7.x86_64')
('version      :', '#1 SMP Wed Sep 26 15:12:11 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
Stepping:              4
CPU MHz:               1650.000
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              5992.37
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts spec_ctrl intel_stibp flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.2172 sec, LOAD: 0.6428 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0006 sec, LOAD: 0.5706 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.2158 sec, LOAD: 1.1902 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0008 sec, LOAD: 0.0529 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0294 sec, LOAD: 0.1301 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.2173 sec, LOAD: 0.0973 sec.

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.docker pull mxnet/python:gpu
2.nvidia-docker run -it mxnet/python:gpu  /bin/bash

inside the container
1.apt-get install git
2.git clone https://github.com/apache/incubator-mxnet.git
2.cd incubator-mxnet
3.python example/image-classification/train_mnist.py --network lenet --gpus 0

## What have you tried to solve it?

1.removing the argument 'base_lr=args.lr' from line 53 in 
        incubator-mxnet/example/image-classification/common/fit.py seems to fix the issue

**Comment by kalyc** [comment]
Thanks for reporting @giordyb 
I had filed a similar issue earlier - https://github.com/apache/incubator-mxnet/issues/13211
Please follow steps mentioned in the above issue and let us know if this still persists.

**Comment by vdantu** [comment]
@mxnet-label-bot add [Question, pending-requester-info]

**Comment by giordyb** [comment]
Hi,

I was able to get it to work by checking out the v1.3.x release

**Comment by vrakesh** [comment]
@giordyb Glad you were able to resolve the issue, requesting to close this issue, if it has been resolved .

**Comment by leleamol** [comment]
@mxnet-label-bot can we close this issue?

**Comment by piyushghai** [comment]
@lanking520 Can you close this issue as the issue has been resolved :)

@giordyb Please feel free to re-open if closed in error.

**Comment by lanking520** [comment]
@giordyb Close it for now. Please feel free to reopen if the issue persist
