### ISSUE TITLE
multivariate time series prediction

### ISSUE THREAD

**Issue by andrewcz** [apache/incubator-mxnet#1365]
Hi,
is there a multivariate time series prediction application in this package.
many continuous sequences to predict another sequence?
example being-

https://github.com/Element-Research/rnn/blob/master/examples/recurrent-time-series.lua

Many thanks,
Best,
Andrew

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
