### ISSUE TITLE
OP request: GPU version of mxnet.ndarray.contrib.boolean_mask

### ISSUE THREAD

**Issue by kalpitdixit** [apache/incubator-mxnet#13675]
I need to use the "**boolean_mask**" operator in my Gluon model. Currently, it is only implemented for CPU which is making training for my model very slow (multiple weeks). Can we please have this op in GPU as well?

https://mxnet.incubator.apache.org/api/python/ndarray/contrib.html#mxnet.ndarray.contrib.boolean_mask

@szha

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [gluon, feature request]

**Comment by szha** [comment]
https://github.com/apache/incubator-mxnet/pull/14090
