### ISSUE TITLE
mpi

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#1368]
Hi all,

I can only use mpirun (openmpi) to launch jobs and not ssh as the load sharing facility doesn;t allow sshs. In this case, can I still use the distributed parameter server framework? I dont have any control on what nodes the job is launched on, except specifying the total number of servers and workers for mpirun.

I have looked at the mpirun launcher.

**Comment by mli** [comment]
are you using qsub? in that case, you don't need to specify the -H configure, mpirun will find it

**Comment by amithr1** [comment]
I am using LSF. Looks like there is a way to get it in. After looking at the scripts, I may have to pass in a job index as an extra env variable. Is this correct?

 Also, I get "OpenCV" unavailable everytime (though the test passes). Is this something to worry about? I am passing the location of the libraries in LD_LIBRARY_PATH. Where is opencv used? So far I am using only cifar and there is no problem

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
