### ISSUE TITLE
MXNet usage on non-AWS cloud providers

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#13713]
Currently there is no information how to use MXNet on non-AWS cloud providers.
Please add the information how to use Nvidia containers with MXNet.

As requested, we distribute our Nvidia MXNet container, updated each month, that runs on our customized virtual images for multiple CSPs in addition to AWS:
 
GCP - VM: https://console.cloud.google.com/marketplace/details/nvidia-ngc-public/nvidia_gpu_cloud_image

Azure - VM: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.ngc_azure_17_11?tab=Overview

Alibaba – VM: https://docs.nvidia.com/ngc/ngc-alibaba-setup-guide/launching-nv-cloud-vm-console.html#launching-nv-cloud-vm-console
Oracle – VM: https://docs.cloud.oracle.com/iaas/Content/Compute/References/ngcimage.htm

All of these use our Nvidia MXNet docker container: https://ngc.nvidia.com/catalog/containers/nvidia%2Fmxnet

**Comment by srochel** [comment]
@mxnet-label-bot add ['documentation', 'website']

**Comment by srochel** [comment]
@mxnet-label-bot add ['doc']

**Comment by harshp8l** [comment]
@mxnet-label-bot add [doc]

**Comment by safrooze** [comment]
@aaronmarkham Have you looked at this issue to see where it would fit on the website?

**Comment by aaronmarkham** [comment]
Assuming we had the content, I think it link from the Ecosystem page... create a new section there.

**Comment by ptrendx** [comment]
The way NVIDIA containers work is as follows:
 - https://ngc.nvidia.com container repository gives access to all containers provided by NVIDIA, including MXNet
 - when working on the particular Cloud Provider, user would go the one of the links that @srochel posted to get the appropriate VM for that cloud (those pages also contain link to documentation how to run those VMs). VM for AWS is available as well (https://aws.amazon.com/marketplace/pp/B076K31M1S)
 - that VM has all the dependencies installed to use containers from NGC, so to start using MXNet user would need to do the steps shown in the description of the MXNet container: https://ngc.nvidia.com/catalog/containers/nvidia:mxnet 
 - User does not need to build MXNet from source (although the source code is available in the container, so user could rebuild if they wanted), it is already installed in the container

Does it answer your questions @aaronmarkham ?
