### ISSUE TITLE
Equivalent of np.ascontiguousarray in mxnet?

### ISSUE THREAD

**Issue by Eniac-Xie** [apache/incubator-mxnet#13712]
Hi,

What is the equivalent of numpy's ascontiguousarray in mxnet?
I use mxnet.ndarray.transpose in my code, will it make the memory discontiguous?

Thank you!

**Comment by TaoLv** [comment]
MXNet NDArray doesn't have stride information and elements of NDArray are compacted. From this point of view, MXNet NDArray is always contiguous.

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [question, ndarray]
