### ISSUE TITLE
Why RegressionOutput-like loss can't support 'ignore_label' ?

### ISSUE THREAD

**Issue by ElegantGod** [apache/incubator-mxnet#13756]
Why RegressionOutput(LogisticRegressionOutput, MAERegressionOutput) loss can't support 'ignore_label' like SoftmaxOutput?

**Comment by leleamol** [comment]
Hello @ElegantGod ,
For questions, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!

**Comment by leleamol** [comment]
@mxnet-label-bot add [Question]
