### ISSUE TITLE
Multi-precision support for Adam optimizer 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#13753]
As title. Currently Adam optimizer doesn't support mixed-precision training.

**Comment by anirudhacharya** [comment]
@eric-haibin-lin will the multi-precision update rules need to support `row_sparse` storage type and `lazy_update` for weight arrays?

**Comment by eric-haibin-lin** [comment]
No. This does not seem to be a common case for the adamw optimizer

closed with #14171
