### ISSUE TITLE
Compiler error with g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#13773]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Gang (Gary) Wang reported a compile error when testing MXNet v1.4.0.rc0. 
See https://lists.apache.org/thread.html/06691d01b8dcbf65a8de3696160ffb3f588a62d363e7b52a8ddf0bb2@%3Cgeneral.incubator.apache.org%3E  

## Environment info (Required)
g++ --version*
*g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0*

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
g++ --version*
*g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0*

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
c84bb78 (v1.4.0.rc0 release hash)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)
*make -j 6 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=0*
It reports
*make[1]: Entering directory
'/home/wg/ws/mxnet/apache-mxnet-src-1.4.0.rc0-incubating/3rdparty/dmlc-core'*
*make[1]: 'libdmlc.a' is up to date.*
*make[1]: Leaving directory
'/home/wg/ws/mxnet/apache-mxnet-src-1.4.0.rc0-incubating/3rdparty/dmlc-core'*
*g++: internal compiler error: Killed (program cc1plus)*
*Please submit a full bug report,*
*with preprocessed source if appropriate.*
*See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.*
*Makefile:461: recipe for target 'build/src/operator/tensor/indexing_op.o'
failed*
*make: *** [build/src/operator/tensor/indexing_op.o] Error 4*

*$ g++ --version*
*g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0*

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by kohillyang** [comment]
One of the possible reasons of "g++: internal compiler error: Killed (program cc1plus)" may the memory is not enough. I think you can try "make j1" instead.

**Comment by zachgk** [comment]
Thank you for submitting the issue! I'm labeling it so the MXNet community members can help resolve it.

@mxnet-label-bot add [Build, Ubuntu]

**Comment by bigdata-memory** [comment]
Compiled it on the machine w/ 8G mem. and w/o the option -j, thanks.

**Comment by flygragon** [comment]
Howerver, today I encountered the same issue, and always with the same file, after a carton of the machine. I was working with Ubuntu 18.04 with 8G mem. Could some one give me a way to solve it?
Building CXX object CMakeFiles/mxnet_static.dir/src/operator/tensor/indexing_op.cc.o
c++: internal compiler error: killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.

**Comment by kohillyang** [comment]
> Howerver, today I encountered the same issue, and always with the same file, after a carton of the machine. I was working with Ubuntu 18.04 with 8G mem. Could some one give me a way to solve it?
> Error msg is following.
> Building CXX object CMakeFiles/mxnet_static.dir/src/operator/tensor/indexing_op.cc.o
> c++: internal compiler error: killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
Please try "make -j1" instead of "make -j".

**Comment by flygragon** [comment]
> > Howerver, today I encountered the same issue, and always with the same file, after a carton of the machine. I was working with Ubuntu 18.04 with 8G mem. Could some one give me a way to solve it?
> > Error msg is following.
> > Building CXX object CMakeFiles/mxnet_static.dir/src/operator/tensor/indexing_op.cc.o
> > c++: internal compiler error: killed (program cc1plus)
> > Please submit a full bug report,
> > with preprocessed source if appropriate.
> 
> Please try "make -j1" instead of "make -j".

I've tried to reboot the OS and make -j1,but it doesn't work. What can I do ?

**Comment by kohillyang** [comment]
is 7.3.8 your default gcc version? Or you can try downgrade your gcc and g++.

**Comment by flygragon** [comment]
> is 7.3.8 your default gcc version? Or you can try downgrade your gcc and g++.
> 
> And check if there is enough swap memory.

My gcc version is 7.5.0, RAM is 8G. I've tried again without graphic desktop, but it didn't work reporting the error of out of memory. I'm goting to try to downgrade the gcc version and enlarge the swap file.

**Comment by leezu** [comment]
You shouldn't downgrade the GCC version. This is a compiler bug. You need to update the version to get a gcc version that has the fix for your bug...

If no version contains a fix, then you need to report a bug report at https://gcc.gnu.org/bugs/

I'll close this issue as it's unrelated to MXNet, but feel free to discuss here further.

**Comment by flygragon** [comment]
> You shouldn't downgrade the GCC version. This is a compiler bug. You need to update the version to get a gcc version that has the fix for your bug...
> 
> If no version contains a fix, then you need to report a bug report at https://gcc.gnu.org/bugs/
> 
> I'll close this issue as it's unrelated to MXNet, but feel free to discuss here further.

Thanks for your help! I've solved this problem by enlarging the swap file from 2G to 10G.

**Comment by flygragon** [comment]
> You shouldn't downgrade the GCC version. This is a compiler bug. You need to update the version to get a gcc version that has the fix for your bug...
> 
> If no version contains a fix, then you need to report a bug report at https://gcc.gnu.org/bugs/
> 
> I'll close this issue as it's unrelated to MXNet, but feel free to discuss here further.

I'm glad that  you're feeling free. I think there is cerntainly a bug with the gcc 7.5.0, because it 
consumes almost 11GB memory when compiling a cc file of 8KB and a h file with 65KB. I hope this bug has been fixed within a higher version of gcc.
