### ISSUE TITLE
is HiKey 970 AI chip supported ? 

### ISSUE THREAD

**Issue by MyraBaba** [apache/incubator-mxnet#13781]
Is therea any experience with the Hikey 970 AI chip which almost 2TPS speed?

**Comment by zachgk** [comment]
For questions, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!
