### ISSUE TITLE
Website build is flaky 

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#13833]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-website-build/detail/restricted-website-build/957/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwebsite/detail/PR-13818/6/pipeline

It's failing intermittently on PRs with oserror bad address from python.

**Comment by larroy** [comment]
@mxnet-label-bot update [Bug, Flaky, Docs]

**Comment by larroy** [comment]
@mxnet-label-bot update [Bug, Flaky, Doc]

**Comment by pengxin99** [comment]
Maybe this is the old version bug. [Sphinx-issue5914](https://github.com/sphinx-doc/sphinx/issues/5914)

**Comment by KellenSunderland** [comment]
Can we disable this until it's fixed?  It's failing the majority of the builds https://github.com/apache/incubator-mxnet/commits/master

**Comment by larroy** [comment]
I have tried, but the status is not being reported:

https://github.com/apache/incubator-mxnet/pull/13841

**Comment by aaronmarkham** [comment]
Hanging of status result on successful builds was something I reported quite a while ago... you just need to restart that job and maybe it'll go through. https://github.com/apache/incubator-mxnet/issues/13714
I don't think anyone has looked at the underlying problem yet as there were no responses to the issue.

**Comment by aaronmarkham** [comment]
And this is a duplicate of https://github.com/apache/incubator-mxnet/issues/13831

**Comment by larroy** [comment]
Closed as dupe
