### ISSUE TITLE
mx.context not found in website docs

### ISSUE THREAD

**Issue by thomelane** [apache/incubator-mxnet#13854]
Can't find `mx.context` module in documentation on the website.

Some useful functions have been added there, such as `gpu_memory_info` and `num_gpus` but they can't be found, and don't show up in website search.

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/context.py

**Comment by thomelane** [comment]
@mxnet-label-bot add [Website, Docs]

**Comment by aaronmarkham** [comment]
Shows up on beta: https://beta.mxnet.io/api/gluon-related/mxnet.context.html?highlight=context#module-mxnet.context

However, I see no mention of `gpu_memory_info`.

**Comment by aaronmarkham** [comment]
It looks like the new API generator has fixed this issue.
https://mxnet.apache.org/api/python/docs/api/mxnet/context/index.html#mxnet.context.gpu_memory_info
