### ISSUE TITLE
Cmake : could not find mkl (missing MKLDNN_LIBRARY)

### ISSUE THREAD

**Issue by likangGit** [apache/incubator-mxnet#13881]
## Description
When compliting mxnet with cmake (BLAS=MKL), cmake tells me that "could not find mkl (missing MKLDNN_LIBRARY)". This is because MKLDNN_LIBRARY=MKLDNN_LIBRARY-NOTFOUND. I know i should specify the library manually, But the mkldnn library has not been complied yet. so what should i do?
## Environment info (Required)
ubuntu16.04
mxnet 1.3.0
## What have you tried to solve it?
To solve this problem, i config BLAS=Atlas first. Then use command "make mkldnn" generates the mkldnn library. Now we can let BLAS=MKL, and specify the MKLDNN_LIBRARY=&lt;path of mkldnn&gt;  manually. But，But，But this is not a right way to solve this problem, right?

**Comment by pengzhao-intel** [comment]
@lebeg related your cmake PR

**Comment by piyushghai** [comment]
@mxnet-label-bot update [MKL, MKLDNN]

**Comment by dbsxdbsx** [comment]
I got the same problem

**Comment by pengzhao-intel** [comment]
@juliusshufan

**Comment by pengzhao-intel** [comment]
could you try the change of this PR #14877?

**Comment by pengzhao-intel** [comment]
@yinghu5 please help take a look :)

**Comment by yinghu5** [comment]
@likangGit  @troore  the cmake build have issues. we try to fix them by #14877. I attach several files. you may try to copy them to corresponding folders and see if it can workaround. 

[Mxnet_417.zip](https://github.com/apache/incubator-mxnet/files/3161092/Mxnet_417.zip)

**Comment by troore** [comment]
@pengzhao-intel @yinghu5 Thanks for your quick response!
And I just tried your solution @yinghu5, the cmake works well. But after that, the ninja has errors related to mkl-dnn. I just post one of them:
`../include/mxnet././ndarray.h:710:51: error: expected ')' before 'mem_pd'`
`explicit NDArray(mkldnn::memory::primitive_desc mem_pd)`
`../include/mxnet/././ndarray.h:739:13: error: ‘primitive_desc’ in ‘struct mkldnn::memory’ does not name a type`
`const mkldnn::memory::primitive_desc &desc) const;`

But still thank you guys. I will just wait for your final solution after merging into master. And now I will just use OpenBLAS instead.

BTW, I just posted on MXNet forum to list the issues during my building:
[[MXNet Build] CMake with MKL/OpenBLAS Issues](https://discuss.mxnet.io/t/mxnet-build-cmake-with-mkl-openblas-issues/3942)

**Comment by pengzhao-intel** [comment]
close this issue and please file new one if you encounter other issues.

**Comment by apeforest** [comment]
I still have this issue recently if I compile using make and USE_BLAS=mkl. If I use cmake with -DUSE_MKL_IF_AVAILABLE=ON it's also not working and complains that "-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_RT_LIBRARY)
-- Found OpenBLAS libraries: /usr/local/lib/libopenblas.so
-- Found OpenBLAS include: /usr/local/include"

I did install mkl following this guide https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo. But it seems by default it's installed at ```/opt/intel/compilers_and_libraries_2020.0.166/linux/mkl``` instead of ```/opt/intel/mkl```. Not sure if this is the rootcause.

Could @PatricZhao help to take a look? Thanks!

**Comment by leezu** [comment]
@apeforest after installing mkl to that location, you likely either need to add the location to the relevant environment variables (such as PATH), or manually specify the mkl root dir as an argument to cmake. It's expected and in fact desirable that cmake doesn't pick up things that are not listed in the relevant environment variables or command line options. 

Or what do you mean?

**Comment by pengzhao-intel** [comment]
closing since when updated to mkldnn 1.0. MKL is not a dependency again.
