### ISSUE TITLE
Java installation instruction is wrong

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#13910]
Currently Java API is only available for master and 1.4.x above. However, we can find the instruction for all previous versions: http://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Java&processor=CPU

Apart from that, the information below should be changed from

```xml
<dependency>
    <groupId>org.apache.mxnet</groupId>
    <artifactId>mxnet-full_2.11-linux-x86_64-cpu</artifactId>
    <scope>system</scope>
    <version>1.4.0</version>
    <systemPath>/system/path/to/jar/mxnet-full_2.11-linux-x86_64-cpu-1.4.0-SNAPSHOT.jar</systemPath>
</dependency>
```
to
```xml
<dependency>
    <groupId>org.apache.mxnet</groupId>
    <artifactId>mxnet-full_2.11-linux-x86_64-cpu</artifactId>
    <version>LATEST</version>
</dependency>
```
on master
@aaronmarkham

**Comment by aaronmarkham** [comment]
It is a known issue that the install page shows things it shouldn't. That selector is broken, broken, broken. Reported here:
https://github.com/apache/incubator-mxnet/issues/13430

So, I won't be able to fix Java showing for previous versions. But we can get the xml updated.

**Comment by piyushghai** [comment]
@lanking520 @aaronmarkham The corresponding PR has been merged. 
Can this issue be closed now ?
