### ISSUE TITLE
Cannot install MXNet R (cannot open URL)

### ISSUE THREAD

**Issue by Kurokokoro** [apache/incubator-mxnet#13923]
Hi, recently i tried installing MXNet with RStudio on Windows 7. After the command:
`install.packages("mxnet")`
I got error:
`Warning in install.packages :
  package ‘mxnet’ is not available (for R version 3.5.1)`

After:
`cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")`
I got:
`trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_1.3.0.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_1.3.0.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_1.3.0.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed`

And finally, after (found somewhere here when seaching for fix):
`install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)`
It installed but when trying to load library:
`Error: pakiet ‘mxnet’ nie jest zainstalowany dla 'arch=i386'`

I know that Windows 7 is not fully supported but I hope it's not that case.
So the file on server is missing or something? 
I would be very grateful if someone could help me
Thanks

Session info:
R version 3.5.1 (2018-07-02)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arules_1.6-2  Matrix_1.2-14

loaded via a namespace (and not attached):
 [1] coin_1.2-2        lattice_0.20-38   codetools_0.2-16  mvtnorm_1.0-8     zoo_1.8-4        
 [6] MASS_7.3-51.1     grid_3.5.1        stats4_3.5.1      multcomp_1.4-8    strucchange_1.5-1
[11] party_1.3-1       sandwich_2.5-0    splines_3.5.1     TH.data_1.0-9     tools_3.5.1      
[16] survival_2.43-3   compiler_3.5.1    modeltools_0.2-22

**Comment by piyushghai** [comment]
@Kurokokoro Thanks for raising the issue. Let me ask the in-house R Gurus to try to resolve this for you.
@anirudhacharya @jeremiedb @ankkhedia Can you guys have a look at this ? 

@mxnet-label-bot Add [R]

**Comment by ankkhedia** [comment]
@Kurokokoro Do you have  OpenBlas already installed in your system?

I am not sure if it is a Windows 7 issue but the installation works fine for Windows10. Alternatively you can try building from source using the instructions mentioned in http://mxnet.incubator.apache.org/install/windows_setup.html#install-mxnet-package-for-r

**Comment by jeremiedb** [comment]
I'm not maintaining the officiel repo on AWS. 

But as a quick hack, I keep up to date CPU/GPU installs here which should be compatible with R >= 3.5.0: 
`install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)`

I'd guess the issue encountered was related to the installation for R <= 3.4 rather than Windows 7. Let me know otherwise.

**Comment by Kurokokoro** [comment]
> @Kurokokoro Do you have OpenBlas already installed in your  system?

I tried but installation had an error, I have precompiled binaries but no idea on how to implement it with RStudio. 
In Windows 10 Mxnet worked in RStudio without installing OpenBlas as I remember

> If still having issue, you may try this version compatible with R >= 3.5.0:
install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)

Still gives error:
`trying URL 'https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip'
Warning in install.packages :
  cannot open URL 'https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip': HTTP status was '403 Forbidden'
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip'`

Thanks for your help so far :D

**Comment by jeremiedb** [comment]
@Kurokokoro Could you give another shot, I think I had failed to change the status to public.

**Comment by Kurokokoro** [comment]
It downloads:
`trying URL 'https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip'
Content type 'application/zip' length 30382408 bytes (29.0 MB)
downloaded 29.0 MB`

But unfortunately gives the same error when trying to load library:
`Error: package ‘mxnet’ is not installed for 'arch = i386'`

**Comment by jeremiedb** [comment]
Oh I missed the 32 bits part. 32 bits isn't supported. Can't you use R 64 bits on Windows 7?

**Comment by Kurokokoro** [comment]
I missed that as well, I switched to 64 bit version and it works now.
Thank you very much :)

**Comment by Kurokokoro** [comment]
Yes please, thanks for help again

**Comment by bunyaminfuatyildiz** [comment]
Error: package or namespace load failed for ‘mxnet’:
 package ‘mxnet’ was installed before R 4.0.0: please re-install it

**Comment by arnoldmashava** [comment]
> If still having issue, you may try this version compatible with R >= 3.5.0:
> `install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)`
> 
> I'd guess the issue encountered was related to the installation for R <= 3.4 rather than Windows 7. Let me know otherwise.

jeremiedb 

> If still having issue, you may try this version compatible with R >= 3.5.0:
> `install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)`
> 
> I'd guess the issue encountered was related to the installation for R <= 3.4 rather than Windows 7. Let me know otherwise.

@jeremiedb - thanks for maintaining the MxNet Repository for R Statistics. This, for me, has been the only function for the MxNet malady on R Stats. Thanks mate!
