### ISSUE TITLE
Let MxNet Support CuDNN v2.

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#1392]
HI, guys, I am going to make MxNet support CuDNNv2.
Do you have any good suggestions?
@tqchen @piiswrong

**Comment by hjk41** [comment]
Why should we support cuDNN v2? Is there any benefit from that?

On Mon, Feb 1, 2016 at 4:25 PM, Zhang Ming <notifications@github.com> wrote:

> HI, guys, I am going to make MxNet support CuDNNv2.
> Do you have any good suggestions?
> @tqchen <https://github.com/tqchen> @piiswrong
> <https://github.com/piiswrong>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1392>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by starimpact** [comment]
TK1 only support CuDNNv2.

**Comment by hjk41** [comment]
I see. 😅

On Mon, Feb 1, 2016 at 4:46 PM, Zhang Ming <notifications@github.com> wrote:

> TK1 only support CuDNNv2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1392#issuecomment-177855174>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by piiswrong** [comment]
Look into cudnn_covlution-inl.h. It shows how to use CUDNN_MAJOR to determine cudnn version and activate different code.

**Comment by starimpact** [comment]
thanks @piiswrong 
do you have any further suggestion?

**Comment by starimpact** [comment]
if do not consider the backward operation, it is easy to make mxnet use cudnn_v2.

**Comment by dangweili** [comment]
Have you make it to support cudadnn v2？

**Comment by starimpact** [comment]
yes, but only for prediction.

**Comment by horsepurve** [comment]
While compiling with cudnn v2, I got the error:
/mxnet/mshadow/mshadow/./base.h:276:45: error: 'CUDNN_DATA_HALF' was not declared in this scope
   static const cudnnDataType_t kCudnnFlag = CUDNN_DATA_HALF;
                                             ^

**Comment by el-oso** [comment]
@starimpact  Have you managed to make mxnet support cudnn v2? I have two TK1 lying around and I would like to use them to train small sets for screening models and it would be great if you already did that :)

**Comment by starimpact** [comment]
@el-oso I am sorry, I just did the prediction on TK1.

**Comment by el-oso** [comment]
@starimpact Well, that is a start :). Could you share your code? Maybe I can manage to also update the training part.

**Comment by marcociccone** [comment]
@starimpact Could you please share your Cudnnv2 version? a fork or a gist file would be really appreciated by the community :)

**Comment by starimpact** [comment]
no problem.i will share it tomorrow.

**Comment by starimpact** [comment]
@marcociccone 
git@github.com:starimpact/mxnet_tk1.git
you need to remove the ```-msse2``` and ```-msse3``` which should be in ```dmlc-core and mshadow``` by yourself.
if there is any problem , you can ask me for help.

**Comment by marcociccone** [comment]
Thank you! I’ll let you know if I have some troubles

**Comment by mcxkarakoc** [comment]
@marcociccone @starimpact Could you succeed in compiling mxnet for cuDNN? I couldn't compile it. In fact, I've noticed GPUs which I may access have compute capability less than 3. So they do not support cuDNN. However, I feel it may require sometime :)

**Comment by dichild** [comment]
Got the same problem as @horsepurve ,
/mxnet/mshadow/mshadow/./base.h:276:45: error: 'CUDNN_DATA_HALF' was not declared in this scope
static const cudnnDataType_t kCudnnFlag = CUDNN_DATA_HALF;

**Comment by crabriver** [comment]
@horsepurve 
Just missing CUDNN_DATA_HALF definition, modify your cudnn.h.
cd /usr/local/cuda/include;
find the cudnn.h file, edit it
find this code block：
/*
* CUDNN data type
*/
typedef enum
{
    CUDNN_DATA_FLOAT  = 0,
    CUDNN_DATA_DOUBLE = 1
} cudnnDataType_t;

Add CUDNN_DATA_HALF = 2

After changes：

typedef enum
{
    CUDNN_DATA_FLOAT  = 0,
    CUDNN_DATA_DOUBLE = 1,
    CUDNN_DATA_HALF = 2
} cudnnDataType_t;

good luck
hhhhhh

**Comment by el-oso** [comment]
No, I still get an error :(. I can build MXNet without CUDA support, but then I don't use the full potential of the board, i.e. no GPU. I just want to build it for prediction with CUDA 6.5/CUDNN v2 (max available in the TK1 afaik), is there a way to do that?

@crabriver did you try your fix yourself? I tried it and compilation goes further but then it gets stuck in  

In file included from src/operator/cudnn_convolution.cc:7:0:
src/operator/./cudnn_convolution-inl.h:36:13: error: ‘cudnnConvolutionBwdDataAlgo_t’ has not been declared
             cudnnConvolutionBwdDataAlgo_t *bwd,

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
