### ISSUE TITLE
Computing aggregations along tensor dimensions

### ISSUE THREAD

**Issue by jsusskin** [apache/incubator-mxnet#1394]
I am fairly new to mxnet so I could be missing something here.
From what I can glean, the facilities for ndarray and symbolic tensor manipulations lack built-in support for aggregations along tensor dimensions. E.g. mean, standard deviation, sum, product...
In theano for example, I can do x.sum(axis=1) in a symbolic graph and all the forward/backward operations are handled properly.
What would be the equivalent thing to do in mxnet at this time?
Suppose for example I want to include a mean and variance normalization step on top of the activities of a given network layer as part of the graph.

**Comment by jsusskin** [comment]
I see now that this is probably related to issue #404, but it may deserve it's own issue since this is really about a family of common aggregation operations on tensors. I'm also wondering whether one way of accomplishing lots of these kinds of operations without spending the time writing the basic ops would be to use the torch modules. This could at least be a temporary way to increase functionality, right?

**Comment by piiswrong** [comment]
We already support these functions with torch modules. See doc/python/tutorial/torch_howto for detail.

**Comment by jsusskin** [comment]
Will definitely try the torch interface.
Regarding the ndarray interface, from what I can see, there is a sum function, but it collapses across all elements of the tensor, returning a scalar. That's definitely useful and can be used to build stats like global means, variances, etc., from a tensor without going back to numpy. Maybe I'm not seeing it, but I can't find any way in the ndarray function interface to do sums across particular tensor dimensions. E.g. how do I compute the row sum of a matrix using ndarray?
I understand the lack of time issue and I'm happy to work towards contributing what I can but I want to make sure I don't duplicate efforts.

**Comment by jsusskin** [comment]
Ok, I see how I can compute row or column sums using dot products of a matrix with a row or column vector of 1s. I think that would allow me to do these basic aggregations in ndarray without using the torch interface or writing a specific op.
One thing I'm still unclear about since I'm new to mxnet is how to mix symbolic and ndarray operations. If I want to include ndarray operations in the symbolic graph, do I need to encapsulate them in a custom op?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
