### ISSUE TITLE
mxnet read jpeg images give different values compared with other libs

### ISSUE THREAD

**Issue by 2void** [apache/incubator-mxnet#13943]
## Description
Hi, guys! I am a student and recently when my colleagues and I use `imread` in mxnet, version 1.3.1, we found a very strange phenomena. For some jpeg images, the RGB values mxnet read may possibly differ from the values read by other libraries, e.g. skimage, scipy, matplotlib. However, on mxnet, version 1.2.1, everything is fine.

## Environment info (Required)
Ubuntu 18.04, Python 3.6.6, Anaconda(conda version 4.5.12), NumPy 1.14.6, skimage 0.14.1
mxnet 1.3.1 was installed by pip

## Reproducible example
1. Here is our result on mxnet=1.3.1. mxnet and skimage give different result! 
![example1](https://user-images.githubusercontent.com/19774964/51463590-8979a600-1d9e-11e9-849d-56de639f34b2.png)
However, skimage, scipy and matplotlib all give the same value!
![example2](https://user-images.githubusercontent.com/19774964/51463820-2fc5ab80-1d9f-11e9-944f-b3a15c0991ad.png)

## Steps to reproduce
(Paste the commands you ran that produced the error.)
1. This is our test image
![test](https://user-images.githubusercontent.com/19774964/51463303-d4df8480-1d9d-11e9-849f-aa6217d7124c.jpeg)
2. here's the code
```python
import mxnet
import skimage.io as io
import numpy as np
filename = "test.jpeg"  # this image lead to value inconsistent!
img_sk = io.imread(filename)
img_mx = mxnet.image.imread(filename).asnumpy()
np.where(img_sk != img_mx)  # should be empty!
# from here you can peek some values using the indices above
```
```python
import matplotlib
import skimage.io as io
filename = "test.jpeg"
img_sk = io.imread(filename)
img_mp = matplotlib.image.imread(filename)
import numpy as np
np.where(img_sk != img_mp)
import scipy
img_sci = scipy.misc.imread(filename)
np.where(img_mp != img_sci)
```

## What have you tried to solve it?
1. The only way to solve this is to use version 1.2.1 instead.

**Comment by piyushghai** [comment]
@2void Thanks for raising this issue.
I'm labelling it so that other community members cab help out here.
@mxnet-label-bot Add [Python, Data-loading]

**Comment by abhinavs95** [comment]
Hi @2void mxnet.image.imread() uses opencv imread under the hood. Using the snippet below we can check that the results from both are identical. (I am using mxnet 1.4.0)
```
import mxnet
import numpy as np
import cv2
filename = "test.jpeg"
img_cv = cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB) #need to convert as default is BGR for opencv
img_mx = mxnet.image.imread(filename).asnumpy()
print(np.where(img_cv != img_mx))
```
The difference in output between opencv and skimage, from what I could gather, is due to different techniques of decoding the jpeg image (source: https://github.com/scikit-image/scikit-image/issues/2293). However, the output from both cannot be differentiated by human eye.

If you want to ensure you have the exact same output as mxnet.image.imread, I would suggest using opencv.

**Comment by 2void** [comment]
@abhinavs95 Thank you very much!👍. Looks like opencv and skimage use different algorithms to deal with compressed JPEG data.

**Comment by piyushghai** [comment]
Thanks. Glad to hear your issue got resolved. 
@Roshrini Can you close this issue ? 
@2void Please feel free to re-open the issue if closed in error.

**Comment by abhinavs95** [comment]
@2void Could you close the issue since your problem has been resolved?

**Comment by 2void** [comment]
@abhinavs95 Sorry, this is my first time open an issue 😅
