### ISSUE TITLE
AttributeError: 'list' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by toufikoss** [apache/incubator-mxnet#13970]
i have a error in this line of my code python:
AttributeError: 'list' object has no attribute 'reshape' 

the code is 
def feedforward(x, W1, W2, b1, b2):
 z1=np.dot(W1, x.reshape(4,1))+b1   
 a1=relu(z1)
 z2=np.dot(W2, a1)+b2
 a2=sigmoid(z2)
 return z1, z2, a1, a2

**Comment by frankfliu** [comment]
@mxnet-label-bot add [question]

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Python]

**Comment by ChaiBapchya** [comment]
As it is a list, it can't be reshaped.
Convert it into a numpy array and then use it's reshape function.
i.e. `np.array().reshape()`
So above feedforward function will look like - 
```
def feedforward(x, W1, W2, b1, b2):
    z1=np.dot(W1, np.array(x).reshape(4,1))+b1
    a1=relu(z1)
    z2=np.dot(W2, a1)+b2
    a2=sigmoid(z2)
    return z1, z2, a1, a2
```
