### ISSUE TITLE
How can I download the precompiled package ?

### ISSUE THREAD

**Issue by yuyijie1995** [apache/incubator-mxnet#13989]
I want to use C++ edition MXNET ,but I do not find the precompiled package

**Comment by frankfliu** [comment]
@mxnet-label-bot add [question, C++]

**Comment by frankfliu** [comment]
@yuyijie1995 
For C++ API, you have to build from source.
See: https://github.com/apache/incubator-mxnet/tree/master/cpp-package

**Comment by leleamol** [comment]
@yuyijie1995,
Can you please let us know if you were able to build cpp-package from source?

@mxnet-label-bot add [Pending Requester Info]

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by lanking520** [comment]
@yuyijie1995 Close this issue for now due to the inactivity. Please feel free to reopen it if you are facing more problems with it.
