### ISSUE TITLE
[Quantization]'Symbol' object has no attribute 'get_backend_symbol'

### ISSUE THREAD

**Issue by hey-yahei** [apache/incubator-mxnet#13986]
## Description
I've  tried to run the [example of quantization](https://github.com/apache/incubator-mxnet/tree/master/example/quantization), but it shows that --     
> AttributeError: 'Symbol' object has no attribute 'get_backend_symbol'     

So why **Symbol** class in ***mxnet-cu92mkl*** has no attribute **get_backend_symbol**?      
And how can I use `imagenet_gen_qsym_mkldnn.py` to quantize my model?      
Thanks.

## Environment info (Required)
----------Python Info----------
Version      : 3.6.7
Compiler     : GCC 7.3.0
Build        : ('default', 'Oct 23 2018 19:16:44')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 18.1
Directory    : /home/yahei/anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.3.1
Directory    : /home/yahei/anaconda3/lib/python3.6/site-packages/mxnet
Commit Hash   : 19c501680183237d52a862e6ae1dc4ddc296305b
----------System Info----------
Platform     : Linux-4.4.0-141-generic-x86_64-with-debian-stretch-sid
system       : Linux
node         : Server2
release      : 4.4.0-141-generic
version      : #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
Stepping:              4
CPU MHz:               3999.980
CPU max MHz:           4000.0000
CPU min MHz:           1200.0000
BogoMIPS:              7008.62
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              8448K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0031 sec, LOAD: 1.4854 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0041 sec, LOAD: 1.5527 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0047 sec, LOAD: 1.0389 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1738 sec, LOAD: 0.8113 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0018 sec, LOAD: 2.2165 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0017 sec, LOAD: 0.4521 sec.

## Error Message:
> yahei@Server2:~/quantization$ python imagenet_gen_qsym_mkldnn.py --model=mobilenet1.0 --num-calib-batches=5 --calib-mode=naive
INFO:logger:shuffle_dataset=True
INFO:logger:calibration mode set to naive
INFO:logger:model mobilenet1.0 is converted from GluonCV
INFO:logger:Converting model from Gluon-CV ModelZoo mobilenet1.0... into path /home/yahei/quantization/model
/home/yahei/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:67: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
Traceback (most recent call last):
  File "imagenet_gen_qsym_mkldnn.py", line 182, in <module>
    sym = sym.get_backend_symbol('MKLDNN')
AttributeError: 'Symbol' object has no attribute 'get_backend_symbol'

**Comment by frankfliu** [comment]
@mxnet-label-bot [Python, Question]

**Comment by eric-haibin-lin** [comment]
Can you try the nightly version by pip install mxnet-cu92mkl --pre -U?

**Comment by hey-yahei** [comment]
I try to install the nightly version. But when I import mxnet in python, some faults occur --    
```bash
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet

Segmentation fault: 11

Stack trace returned 0 entries:
```

**Comment by eric-haibin-lin** [comment]
@ZhennanQin @taolv

**Comment by ZhennanQin** [comment]
I think it's an environment issue that you're mixed using old version of mxnet with recent `imagenet_gen_qsym_mkldnn.py` script. Because we add get_backend_symbol in symbol API and used it in `imagenet_gen_qsym_mkldnn.py`  within same PR.  Please double check your MXNet installation.

**Comment by hey-yahei** [comment]
I reinstall anaconda and mxnet of nightly version. 
Now it works now!
Thanks
