### ISSUE TITLE
Using NaiveEngine with Unix fork() hangs during prediction.

### ISSUE THREAD

**Issue by mlourencoeb** [apache/incubator-mxnet#13988]
Hello everyone,

I need to have single thread process running and performing prediction. After using defaut engine type and setting CPU thread environment variables to 1, I always end up with 2 threads. The only way I could achieve achieve single thread execution is using NaiveEngine.

In this particular context I must use fork() for paralelization but with NaiveEngine it simply just hangs during prediction.

Have anyone experience this behaviour or knows how to make it work?

Cheers,
Miguel

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Question]

**Comment by vdantu** [comment]
@anirudh2290 , would you be able to help?

**Comment by anirudh2290** [comment]
@mlourencoeb please provide a reproducible script.

**Comment by mlourencoeb** [comment]
I ended up converting the modelo to onnx ans performing inference with opencv where we can have granular update of the number of threads.

Thanks anyway :)
