### ISSUE TITLE
Mxnet runtime profile for each layers in details

### ISSUE THREAD

**Issue by jiangzhengkai** [apache/incubator-mxnet#13997]
Hi, Anyone can tell me to use profiler for runtime of each layer for symbol network?

**Comment by TaoLv** [comment]
Have you ever read this tutorial? https://mxnet.incubator.apache.org/versions/master/tutorials/python/profiler.html

**Comment by jiangzhengkai** [comment]
@TaoLv Yes, But from the json file, Only layers time shows, not exactly each layer

**Comment by frankfliu** [comment]
@mxnet-label-bot add [question, profiler]

**Comment by safrooze** [comment]
The profiling results are not separated by layer, but rather by operation. In the [View in browser](https://mxnet.incubator.apache.org/versions/master/tutorials/python/profiler.html#view-in-browser) section of the tutorial mentioned above, you can see every operator execution on a timeline, which allows you to gain a complete understanding of how operators are executed by the engine. Please close this issue if this satisfies your question. Also for future questions like this, please use [discuss.mxnet.io](https://discuss.mxnet.io) forum.

**Comment by sandeep-krishnamurthy** [comment]
Resolving as the question is answered. Please reopen if you still face issue using mxnet profiler.
