### ISSUE TITLE
[feature request] The API for Engine::PushAsync to execute outside asynchronous functions

### ISSUE THREAD

**Issue by wkcn** [apache/incubator-mxnet#14044]
Hi, there.

I would like to implement an outside asynchronous function, without the need of rebuilding the source of MXNet.
For example, I write the following functions with C++, whose code is independent of MXNet.
```c++
void operator_forward(const DLTensor* a, const DLTensor* b, DLTensor* out, void* stream);
void operator_backward(DLTensor* da, DLTensor* db, const DLTensor* dy, void* stream);
```
I want to push them into the computational stream of MXNet, and I tried to use `MXTVMBridge`.
Unfortunately, there is the problem about ABI compatibility. [[issue]](https://github.com/apache/incubator-mxnet/issues/14030), [[discussion]](https://discuss.tvm.ai/t/the-abi-compatibility-of-packedfunc/1601/5)

Will MXNet provide an API to visit `Engine::PushAsync`, to execute an outside asynchronous function?

Thank you!

**Comment by vdantu** [comment]
@mxnet-label-bot add [Question, Feature]

@apeforest @anirudh2290 : Would you be able to answer the question?

**Comment by wkcn** [comment]
The issue is solved.
I use `MXTVMBridge` to execute asynchronous functions.
Since the C++ header file `<funtional>` is different among different compiler, I replace it to the corresponding version to address the ABI compatibility problem.

Example: https://github.com/wkcn/MobulaOP/blob/master/3rdparty/tvm_packed_func/tvm_packed_func.h#L13
