### ISSUE TITLE
Generation of R reference manual fails 

### ISSUE THREAD

**Issue by shadogray** [apache/incubator-mxnet#14075]
## Description
R reference manual generation fails due to bugs in method documentation

## Environment info (Required)
> Rscript -e version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo              

> make -v
GNU Make 4.2.1
Gebaut für x86_64-suse-linux-gnu

a2ps-4.14-lp150.1.37.x86_64
texlive-2017.20170520-lp150.9.6.1.x86_64

```
What to do: 
Try to build mxnet.pdf:
R CMD Rd2pdf R-package/

```

Package used (Python/R/Scala/Julia):
I'm using R

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: openSUSE Leap 15.0

Matrix products: default
BLAS: /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none=/usr/nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/8 --enable-ssp --disable-libssp --disable-libvtv --disable-cet --disable-libcc1 --enable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-8 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 8.2.1 20190103 [gcc-8-branch revision 267549] (SUSE Linux) 

## Error Message:
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Ausführen von 'texi2dvi' für 'Rd2.tex' fehlgeschlagen.
Messages:
sh: /usr/bin/texi2dvi: Datei oder Verzeichnis nicht gefunden
Output:

Fehler bei der Ausführung von tools::texi2pdf()

## Steps to reproduce

R CMD Rd2pdf R-package/

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [bug, doc]
