### ISSUE TITLE
Fp16 support for layernorm

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#14073]
Currently, given fp16 inputs, nd.LayerNorm/sym.LayerNorm perform reduction in fp16, which losses precision. The reduction should be done in fp32 instead. @sxjscience

**Comment by sxjscience** [comment]
Current I propose to solve the issue following these two steps:

- [ ] Add a new 'fp16_mixed_reduce' flag to the LayerNorm operator. When the flag is turned on, the reduction will be performed in fp32 when the input/output have dtype=fp16.
- [ ] Accelerate the implementation of LayerNorm by taking advantage of the techniques in https://github.com/NVIDIA/apex/blob/master/csrc/layer_norm_cuda_kernel.cu, e.g., welford online sum (https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance)

**Comment by haojin2** [comment]
Once #14616 is merged then we can simply switch the LayerNorm's reduction to the safe version to achieve the 1st step @sxjscience proposed. Then we can possibly explore the implementation of the 2nd step later. @eric-haibin-lin What do you think?

**Comment by sxjscience** [comment]
@haojin2 Yes, should first try to directly change the reduce to the safe version.

**Comment by leezu** [comment]
This can probably be closed as https://github.com/apache/incubator-mxnet/pull/15002 is merged
