### ISSUE TITLE
mxnet doesn't have instructions for verifying installation (was: mxnet安装完成后没有验证是否安装成功的过程)

### ISSUE THREAD

**Issue by BigBigWolf-AI** [apache/incubator-mxnet#14109]
操作系统：Windows 10专业版
mxnet版本：1.3.1
问题描述：
mxnet官网给出的安装教程中，只是给出了一条安装命令，并没有给出如何验证安装成功的教程，建议加上。特别是mkl版本和cuda版本的mxnet，没有给出验证是否安装成功的教程，不知道是否安装成功，让新人很难受。

**Comment by BigBigWolf-AI** [comment]
ps：pytorch有这个验证过程，mxnet为什么没有，难受

**Comment by TaoLv** [comment]
@BigBigWolf-AI Please refer to [Validate your MXNet installation](https://mxnet.incubator.apache.org/versions/master/install/validate_mxnet.html) and [the readme of MKL-DNN backend](https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md#verify-mxnet-with-python).

**Comment by szha** [comment]
Translation for @BigBigWolf-AI's request:
Operating system: Windows 10 professional
mxnet version: 1.3.1
Problem statement:
The official mxnet website provides instructions for installation with a single installation command, without providing ways of verifying whether installation is succssful. I suggest adding it.
Especially for mkl and cuda versions of mxnet, without verification steps, it's hard for newcomers to know whether the installation successful.

ps: pytorch has this verification process. why doesn't mxnet have it? it's painful.

**Comment by lanking520** [comment]
MXNet Engine在build结束后并没有任何验证的过程，但是Python和Scala/Java在build结束后可以运行一个test。test本身会花一段时间，所以并没有自动激活。如果你直接使用的是Python的wheel的话，这个是验证过可用的。

MXNet Engine didn't have a verification step after build. However, if you use Python or Scala build, there is an additional test step you can run with. Due to the time cost, we did not enable them by default. If you are using Python wheel, these tests should be covered during our publish procedure.

**Comment by BigBigWolf-AI** [comment]
> @BigBigWolf-AI Please refer to [Validate your MXNet installation](https://mxnet.incubator.apache.org/versions/master/install/validate_mxnet.html) and [the readme of MKL-DNN backend](https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md#verify-mxnet-with-python).

Thank you very much! It's really helpful for me!

**Comment by BigBigWolf-AI** [comment]
> Translation for @BigBigWolf-AI's request:
> Operating system: Windows 10 professional
> mxnet version: 1.3.1
> Problem statement:
> The official mxnet website provides instructions for installation with a single installation command, without providing ways of verifying whether installation is succssful. I suggest adding it.
> Especially for mkl and cuda versions of mxnet, without verification steps, it's hard for newcomers to know whether the installation successful.
> 
> ps: pytorch has this verification process. why doesn't mxnet have it? it's painful.

Thank you for helping me translate my question into English. You are a really nice guy!

**Comment by aaronmarkham** [comment]
Please reopen if you have further issues!
