### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by 975150313** [apache/incubator-mxnet#14112]
line 33   AND (NOT MSVC) ? MKLDNN不支持VC编译器吗

**Comment by pengzhao-intel** [comment]
Thanks @975150313 for the question.

@ZhennanQin @xinyu-intel could you help answer the question?

**Comment by ZhennanQin** [comment]
@975150313 AFAIK, MKLDNN supports windows build with VC. USE_MKLDNN is turned on by default in MXNet recently, and this default enabling is on Linux build only. After some more testing, we may enable MKLDNN by default on other platform like windows. for now you can manually enable MKLDNN with cmake option `-DUSE_MKLDNN`.

**Comment by TaoLv** [comment]
@975150313  Please refer to [the readme of MKL-DNN backend](https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md#3) for the build on Windows.

**Comment by 975150313** [comment]
![qq 20190211125002](https://user-images.githubusercontent.com/24599391/52546601-d4199b80-2dfb-11e9-9317-ed791e5a700a.jpg)
When I compiled mxnet using CMake, there was no MKL-DNN option, and I thought maybe there was a problem with the configuration of CMake. @ @

**Comment by 975150313** [comment]
> @ 975150313 请参阅[MKL-DNN后端自述文件，](https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md#3)了解Windows上的内置版本。

Last version of Make can find MKLDNN, but now this version of Make can not compile MKLDNN to mxnet.

**Comment by 975150313** [comment]
> @975150313 AFAIK, MKLDNN supports windows build with VC. USE_MKLDNN is turned on by default in MXNet recently, and this default enabling is on Linux build only. After some more testing, we may enable MKLDNN by default on other platform like windows. for now you can manually enable MKLDNN with cmake option `-DUSE_MKLDNN`.

![qq 20190211130553](https://user-images.githubusercontent.com/24599391/52546914-12b05580-2dfe-11e9-84aa-66fa88218e58.jpg)

Mkl has been installed on my computer and CMake has recognized it, but there is no MKL-DNN option in CMake, and there is no third-party library of MKL DNN in the compiled bulid folder.

**Comment by 975150313** [comment]
@mxnet-label-bot 
Thank you for your reply. I will pay attention to the relevant labels.

**Comment by pengzhao-intel** [comment]
@juliusshufan 

@mxnet-label-bot add [windows]

**Comment by 975150313** [comment]
Thank you very much. The community problem has been solved.
