### ISSUE TITLE
Website build is failing in CI in Clojure steps.

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#14131]
## Description

See CI validation of master:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwebsite/detail/PR-14122/3/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwebsite/detail/master/304/pipeline

@gigasquid

**Comment by gigasquid** [comment]
I just quickly looked into it, but it seems like the release of leiningen 2.9.0 broke the "codox" generation tool. I think the immediate fix is to disable the clojure doc generation to get ci passing again and unblock builds. The proper fix will be to ping the version of leinengen to a known version so it doesn't get the latest by default and unknowingly break something

**Comment by lanking520** [comment]
Thanks for the quick fix!
