### ISSUE TITLE
alxnet, googlenet do not convergence when using default initializer 

### ISSUE THREAD

**Issue by realbns2008** [apache/incubator-mxnet#1422]
When I use my own data set to play with alexnet and googlenet in the example/image-classifications, it seems that both models will not convergence when using the default initializer in train_model.py:
 (   initializer =  mx.init.Xavier(factor_type="in", magnitude=2.34) )

However when I use mx.init.Normal() as the initializer, then the alexnet do convergence.

Is it possible to let user specific initializer when run example models, or set  mx.init.Normal() as the default initializer when playing with the example model ? Otherwise the user experience is bad when playing with these example models.

**Comment by qiaohaijun** [comment]
this is a old issuse

**Comment by qiaohaijun** [comment]
https://github.com/dmlc/mxnet/issues/826

**Comment by qiaohaijun** [comment]
try inception

**Comment by javelinjs** [comment]
I suggest to modify the example codes to make new users start easily. The code modification should be straightforward, e.g. provide get_initializer() for each example model and pass it as an argument to train_model.fit

**Comment by qiaohaijun** [comment]
@javelinjs  good idea

**Comment by javelinjs** [comment]
@realbns2008 Could you make a PR for this issue?

**Comment by realbns2008** [comment]
ok i will make a PR

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
