### ISSUE TITLE
NameError: name 'mx' is not defined (python)

### ISSUE THREAD

**Issue by jasperDD** [apache/incubator-mxnet#14224]
>>> from skimage import io
>>> import mxnet
>>> test='C:/Users/Admin/Desktop/test.lst' # folder where must be my test.lst
>>> DataSet='C:/Users/Admin/Downloads/mypic/' # folder with my pictures (20 pics

>>> data_iter = mx.image.ImageIter(
... batch_size=4,
... data_shape=(3,816, 1232),
... label_width=4,
... path_imglist='test.lst',
... path_root='DataSet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mx' is not defined
>>>

why mx is not defined, i loaded mxnet?

**Comment by TaoLv** [comment]
import mxnet as mx

**Comment by jasperDD** [comment]
yes, it works, but 
i get error
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\mxnet\image\image.py", line 1071, in __init__
    with open(path_imglist) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'test.lst'
>>>
but this file there is ion my desktop

**Comment by wkcn** [comment]
close since the issue is solved.
