### ISSUE TITLE
Makefile plugins target needs mkldnn dependency

### ISSUE THREAD

**Issue by samskalicky** [apache/incubator-mxnet#14236]
## Description
Building MXNet from source and enabling the WarpCTC plugin following these instructions:
https://github.com/apache/incubator-mxnet/tree/master/example/ctc#ctc-loss-in-mxnet
fails to build on Ubuntu with ```make -j$nproc```  because it depends on mkldnn which wasnt compiled yet. This is due to a missing makefile dependency on the plugin build target. 

Heres the error message:

```
In file included from include/mxnet/./op_attr_types.h:36:0,
                 from include/mxnet/operator.h:40,
                 from plugin/warpctc/./warpctc-inl.h:31,
                 from plugin/warpctc/warpctc.cc:27:
include/mxnet/././ndarray.h:41:22: fatal error: mkldnn.hpp: No such file or directory
 #include <mkldnn.hpp>
                      ^
compilation terminated.
make: *** [build/plugin/warpctc/warpctc.o] Error 1
```

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Build, Bug]

**Comment by pengzhao-intel** [comment]
Thanks to raising the issue. @xinyu-intel could you help take a look?

**Comment by pengzhao-intel** [comment]
@mxnet-label-bot add [MKLDNN]

**Comment by rongzha1** [comment]
@samskalicky  you can workaround by using: make -j1

**Comment by samskalicky** [comment]
Thanks guys!

Ive tried adding " | mkldnn " to the Makefile here:

https://github.com/apache/incubator-mxnet/blob/master/Makefile#L492

that seems to be working. This is similar to another target above:

https://github.com/apache/incubator-mxnet/blob/master/Makefile#L476

Any thoughts about committing this change into the makefile?

**Comment by apeforest** [comment]
Why do we need warpctc if mxnet already has native implementation?
