### ISSUE TITLE
Feature request: share memory between numpy.array and mxnet.ndarray

### ISSUE THREAD

**Issue by SunDoge** [apache/incubator-mxnet#14244]
Last time I did a benchmark and @szha pointed out [that](https://gist.github.com/SunDoge/59a8ff336703b45be30b46dc3ee8b4ab#gistcomment-2841120)

> MXNet made the choice of not doing a zero-copy for numpy arrays, but instead making a copy of the numpy data. 

This is a safe choice but sometimes it can be a performance problem. I check the C API and find no function to share data from outside. Is it possible for MXNet to provide such api?

**Comment by junrushao1994** [comment]
@szha will lead us to implement this feature. I will take a look this weekend.

**Comment by junrushao1994** [comment]
Hey, I did some research this weekend and am convinced it might be possible. So is it acceptable if we assume we are using coupes (instead of cython) @szha

**Comment by szha** [comment]
@junrushao1994 could you elaborate on the consideration?

**Comment by junrushao1994** [comment]
The point is that we need transfer/share ownership of numpy's ndarray to mxnet's C++ backend, because we cannot guarantee the frontend object to exist forever.

Therefore, we need a customized deleter of MXNet's NDArray, aka calling something `Py_DECREF` of the numpy's ndarray object from the C++ backend - It is possible to implement the deleter via ctypes or cython, and then pass it to something roughly like follows this chunk of code.

https://github.com/apache/incubator-mxnet/blob/0f88f61379bd5f59fff6b825be1507d020bf2b7e/include/mxnet/ndarray.h#L131-L148

Per private discussion with @reminisce, his concern is how this could be compatible with the executor and memory planning, in which the executor may take over the ownership. I am not sure about this.

**Comment by wkcn** [comment]
For the sharing from numpy to NDArray, we should use ctypes or weakref module add the inference of numpy object, and decrease the inference through NDArray::deleter.

For the sharing from NDArray to numpy, I think we can add a deleter attribute for numpy object.

**Comment by junrushao1994** [comment]
Agreed with @wkcn

**Comment by junrushao1994** [comment]
I prototyped a version that supports zero copy from numpy to DLManagedTensor in dlpack, but it turns out that MXNet hasn’t support dlpack 0.2 yet...

**Comment by wkcn** [comment]
We can update the submodule dlpack.

**Comment by junrushao1994** [comment]
@wkcn I opened a PR about this to https://github.com/dmlc/dlpack/pull/38.

**Comment by junrushao1994** [comment]
@wkcn Sorry I made a mistake. We already got dlpack 0.2 in MXNet, so everything should be fine

**Comment by wkcn** [comment]
In the submodule DLPack, DLPACK_VERSION is 010 rather than 020.

**Comment by junrushao1994** [comment]
@wkcn this is because dlpack forgots to change its version number to 020 when releasing v0.2 lol. I check the commit hash [here](https://github.com/apache/incubator-mxnet/tree/numpy/3rdparty), and it is identical to tag [v0.2](https://github.com/dmlc/dlpack/releases/tag/v0.2).

**Comment by junrushao1994** [comment]
Being lazy for a while, and now I am thinking of adding an API to mxnet. @wkcn @szha @SunDoge What do you guys think of names for this API? mx.nd.zerocopy_from() or anything else?

**Comment by wkcn** [comment]
I think adding a new argument may be better.

# NDArray to NumPy
a = mx.nd.array([1,2,3])
b = a.asnumpy(shared=True)

# NumPy to NDArray
c = np.array([4,5])
d = mx.nd.array(c, shared=True)

**Comment by reminisce** [comment]
I think adding a parameter to the existing API may introduce certain level of ambiguity which is not desirable. For example, `mx.nd.array` takes not just numpy arrays as arguments, but `shared=True` only works for numpy arrays. We can consider adding this parameter to a new API, for example: `mx.nd.from_numpy(zero_copy=True)`, and it falls back to `mx.nd.array` when `zero_copy` is `False`.

**Comment by junrushao1994** [comment]
@reminisce Sounds good. Will do!

**Comment by SunDoge** [comment]
Thx.
