### ISSUE TITLE
visualize with global_pooling and no kernel crashes.

### ISSUE THREAD

**Issue by danielgilon** [apache/incubator-mxnet#14245]
Using Python. Trying to visualize with global_pooling and no kernel crashes.

The visualization code fails when trying to run:
```
graph = mx.viz.plot_network(symbol)
```
on the layer below:
```
symbol = mx.sym.Pooling(data = data, global_pool = True, pool_type = 'avg') 
```
while it works on when setting a kernel:
```
symbol = mx.sym.Pooling(data = data, global_pool = True, pool_type = 'avg', kernel = (1, 1)) 
```

labels: Bug

**Comment by danielgilon** [comment]
relates to: https://github.com/apache/incubator-mxnet/issues/7814

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Bug]
