### ISSUE TITLE
[DOC] a few documentations for linalg ops are broken

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#14246]
http://mxnet.incubator.apache.org/api/python/ndarray/linalg.html?highlight=lin#mxnet.ndarray.linalg.gemm
and 
http://mxnet.incubator.apache.org/api/python/ndarray/linalg.html?highlight=lin#mxnet.ndarray.linalg.gemm2

<img width="591" alt="screen shot 2019-02-24 at 3 31 38 pm" src="https://user-images.githubusercontent.com/5545640/53307074-7c425200-3849-11e9-9815-5e30c2ca4088.png">

source code in https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/la_op.cc#L54-L61

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Doc]
