### ISSUE TITLE
Flaky cpp test: dropout gpu perf

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#14257]
The dropout cpp test fails intermittently on MXNet master. I can reproduce the failure by running the cpp test locally a couple of times. 

Reference failure log: 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14066/5/pipeline/

**Comment by piyushghai** [comment]
@mxnet-label-bot Add [Test, Flaky]

**Comment by wkcn** [comment]
There is another issue about dropout gpu perf.
http://jenkins.mxnet-ci.amazon-ml.com/job/mxnet-validation/job/unix-gpu/job/PR-14278/1/display/redirect
```bash
C++ exception with description "[07:12:07] /work/mxnet/src/resource.cc:429: Check failed: state_space->ctx.dev_id == stream->dev_id (0 vs. -1) The device id of cudnn dropout state space doesn't match that from stream.
```

Maybe we should modify the code of `tests/cpp/include/test_op.h`.
`opContext_.run_ctx.stream = mshadow::NewStream<gpu>(true, true);` -> `opContext_.run_ctx.stream = mshadow::NewStream<gpu>(true, true, 0);`

**Comment by eric-haibin-lin** [comment]
I see. Maybe that will fix the the failure reported previously

**Comment by eric-haibin-lin** [comment]
#14278 fixes the stream used in the test. feel free to reopen if this issue happens again
