### ISSUE TITLE
Add numpy module under root module mxnet

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#14268]
1. A new module `mxnet.numpy` will be created as a placeholder for future numpy operators.
2. `mxnet.ndarray.numpy` and `mxnet.symbol.numpy` will be created as well for use in Gluon.

**Comment by wkcn** [comment]
I think it is confusing that mx.numpy, mx.nd.numpy and mx.sym.numpy all exist.

In gluon, it is available that Block(nd) and Block(sym) are both supported.

It may be better to support mx.numpy.xxx(nd) and mx.numpy.xxx(sym)

**Comment by reminisce** [comment]
> In gluon, it is available that Block(nd) and Block(sym) are both supported.

Can you elaborate? I don't understand this part.

> It may be better to support mx.numpy.xxx(nd) and mx.numpy.xxx(sym), but using mx.nunpy in the forward of gluon block seems to be not more elegant than F.numpy.

If implemented in this way, how would you differentiate mx.numpy.xxx between symbolic and imperative? The current design considers the minimum change required in Gluon for now and future. With the current design `F.numpy.op`, it would be very easy to just delete `F.` to eliminate `ndarray` and `symbol` namespaces in the future.

**Comment by wkcn** [comment]
@reminisce 
The block in gluon accepts the instance of mx.nd.NDArray or mx.nd.Symbol.
We can distinguish between symbolic and imperative namespaces by the type of inputs.

An Example:
```python
import mxnet as mx


class TestBlock(mx.gluon.nn.HybridBlock):
    def hybrid_forward(self, F, x):
        if isinstance(x, mx.nd.NDArray):
            print('the input is an instance of NDArray')
        elif isinstance(x, mx.sym.Symbol):
            print('the input is an instance of Symbol')
        return x


block = TestBlock()
a_nd = mx.nd.array([1, 2, 3])
print(block(a_nd))
a_sym = mx.sym.Variable('a')
print(block(a_sym))
```

**Comment by reminisce** [comment]
@wkcn Thanks for the example. I see your point. I misunderstood your suggestion before. Agree that it provides clearer UX having a unified operator interface for both `NDArray` and `Symbol` and doing call dispatch under the hood based upon the input argument types. However, we need to consider that there are other operators not belonging to numpy and still needing `F.` prefix in Gluon. I discussed this with @eric-haibin-lin , and we think this kind of mixed use like `np.dot` and `F.Pooling` in Gluon would introduce more confusion to users. One thing we can do is make all the op interfaces ndarray/symbol-agnostic in the future, so that the `F.` can be deleted from Gluon once for all.
