### ISSUE TITLE
Move TShape definition and necessary passes out of NNVM

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#14266]
MXNet needs its own definition of `TShape` to support scalars and zero-size tensors which is compatible with NumPy. To keep NNVM code unchanged, we need to copy `tuple.h` from NNVM to MXNet and make changes in the current MXNet codebase accordingly. Some NNVM passes need to be moved out too.

See https://github.com/apache/incubator-mxnet/issues/14253 for more details.

**Comment by reminisce** [comment]
@junrushao1994

**Comment by junrushao1994** [comment]
Working on this #14217

**Comment by junrushao1994** [comment]
Working on this #14270
