### ISSUE TITLE
[Clojure] Add helper function to convert formed vector to NDArray (infers shape)

### ISSUE THREAD

**Issue by gigasquid** [apache/incubator-mxnet#14271]
We have a ndarray function called `array` that will take a 1d clojure vector and a shape vector and turn it into a ndarray. The Scala function has a new helper function that allows you to pass in a dimensional float/double  array and have the NDArray create it and infer the shape.

It would be nice to create an interop function for this.
Example of interop:

```clojure
user=> (def x [[1.0 2.0 3.0] [4.0 5.0 6.0]])
#'user/x
user=> (NDArray/toNDArray (to-array (mapv #(to-array %) x)) nil)
#object[org.apache.mxnet.NDArray 0x382169db "[\n [1.0,2.0,3.0]\n [4.0,5.0,6.0]\n]\n<NDArray (2,3) cpu(0) float64>"]
user=> 
```

**Comment by Chouffe** [comment]
Should we close the issue now @gigasquid @kedarbellare?
