### ISSUE TITLE
set mxnet single thread

### ISSUE THREAD

**Issue by diandianliu** [apache/incubator-mxnet#14279]
hi
     I run my program on linux, use CPU, call the mxnet.so. I find my program have many threads, and not  call fork an other may have multithread function. it is may be the mxnet.so have mutlithread, and  set MXNET_CPU_WORKER_NTHREADS=1,MXNET_CPU_NNPACK_NTHREADS=1,MXNET_CPU_PRIORITY_NTHREADS=1,but not effect. how to set the mxnet.so run in single thread, thanks!

**Comment by cyrusbehr** [comment]
hi @diandianliu, did you figure out how to do this?

**Comment by cyrusbehr** [comment]
found it https://github.com/apache/incubator-mxnet/issues/15275
