### ISSUE TITLE
[Flaky] test_operator_gpu.test_convolution_multiple_streams

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#14289]
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-gpu/branches/PR-14192/runs/5/nodes/273/log/?start=0

```
======================================================================
FAIL: test_operator_gpu.test_convolution_multiple_streams
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 570, in test_convolution_multiple_streams
    {'MXNET_GPU_WORKER_NSTREAMS' : num_streams, 'MXNET_ENGINE_TYPE' : engine})
  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 540, in _test_in_separate_process
    assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)
AssertionError: Non-zero exit code 255 from _conv_with_num_streams().

-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=997087021 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by junrushao1994** [comment]
@mxnet-label-bot add [Test, Flaky]

**Comment by DickJC123** [comment]
This appears to be an issue with releasing of resources during the NaiveEngine shutdown.  There aren't many tests in our CI that test with the NaiveEngine, so this new test I added is fleshing out the problem.  I saw segfaults (error = 255) on CentOS, and supplied a fix: https://github.com/apache/incubator-mxnet/pull/14006/commits/790a9981440424b6646a7f83f73cce7043ab2398.
It looks like there are more issues here to be worked out though.

**Comment by piyushghai** [comment]
Seen here as well : 

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14269/1/pipeline/273

**Comment by piyushghai** [comment]
There's another duplicate issue : https://github.com/apache/incubator-mxnet/issues/14329. 

Suggest to close this one and carry the conversation on 14239.

**Comment by junrushao1994** [comment]
I am closing this issue and submitting this to #14329
