### ISSUE TITLE
SoftmaxOutput crashes with normalization "valid"

### ISSUE THREAD

**Issue by ashokei** [apache/incubator-mxnet#14301]
## Environment info (Required)
ubuntu 16.04 default build
and, run below script.

```
import numpy as np                                                
import mxnet as mx                                                
xpu = mx.cpu()                                                    
x = mx.sym.Variable('x')                                          
label = mx.sym.Variable('label')                                  
x_nd = mx.nd.array([[1, 6, 4, 2],[1, 6, 4, 2]], ctx=xpu)          
grad_x = mx.nd.zeros((2,4), ctx=xpu)                              
label_nd = mx.nd.array([1,1], ctx=xpu)                            
                                                                  
sym = mx.sym.SoftmaxOutput(data=x, label=label, ignore_label=0,   
                           use_ignore=True, normalization="valid")
ex = sym.bind(ctx=xpu, args={'x': x_nd, 'label': label_nd},       
              args_grad={'x': grad_x})                            
                                                                  
ex.forward(is_train=True)                                         
softmax_out = ex.outputs[0].asnumpy()                             
ex.backward(is_train=True)                                        

```

MXNet commit hash:
fb4f9d55382538fe688638b741830d84ae0d783

Build config:
make

## Error Message:
```
terminated by signal SIGSEGV (Address boundary error)
```

**Comment by wkcn** [comment]
Thanks for your report!

reproduce the bug in MXNet fb4f9d5

**Comment by DickJC123** [comment]
I too recently saw an issue with Softmax that generated a segfault.  This behavior began with the Softmax operator changes introduced by https://github.com/apache/incubator-mxnet/pull/13699 and occurs when the framework is compiled with USE_MKLDNN=0.  The failing test is with sockeye:
```
test/integration/test_constraints_int.py::test_constraints[--encoder rnn --decoder rnn --num-layers 1 --rnn-cell-type lstm --rnn-num-hidden 8 --num-embed 4  --rnn-attention-type mlp --rnn-attention-num-hidden 8 --loss cross-entropy --optimized-metric perplexity --max-updates 2 --checkpoint-frequency 2 --optimizer adam --initial-learning-rate 0.01 --batch-type sentence  --decode-and-evaluate 0-2-10] ./test.sh: line 3:    62 Segmentation fault      python setup.py test
++ RV=139
```
Perhaps you could verify that your fix corrects this behavior?

**Comment by wkcn** [comment]
@DickJC123 Hi! I submitted a PR, which may address the problem.
https://github.com/apache/incubator-mxnet/pull/14302

**Comment by anirudhacharya** [comment]
I can also confirm this issue, it happens only when `normalization-"valid"` and while executing the `Executor.backward` function call. For instance this sample code works fine - 

```
import mxnet as mx                                                                                                                                            
import numpy as np

xpu = mx.cpu()
x_nd = mx.nd.array([[1, 6, 4, 2],[1, 6, 4, 2]], ctx=xpu)    
grad_x = mx.nd.zeros((2,4), ctx=xpu)    
label_nd = mx.nd.array([1,1], ctx=xpu)

x_nd.attach_grad()

with mx.autograd.record():
    y = mx.nd.SoftmaxOutput(data=x_nd, label=label_nd, ignore_label=0, use_ignore=True) #, normalization="valid")

y.backward()
print(x_nd.grad)
```

So the bug is with the gradient calculation of softmax output when `normalization="valid"`

**Comment by fhieber** [comment]
@wkcn Sockeye can use 'valid' normalization in its SoftmaxOutput operator use, see [here](https://github.com/awslabs/sockeye/blob/2f44099cd4f488bd8d348d74e9ae85095f72501e/sockeye/loss.py#L112).
The failure you are observing for `test/unit/test_inference.py::test_topk_func` is related to #13862, which is an open problem.

**Comment by wkcn** [comment]
@fhieber Sorry that I overlooked it.
@anirudhacharya https://github.com/apache/incubator-mxnet/pull/14302 will address the problem.
