### ISSUE TITLE
Predict of mx.mod.Module api problem

### ISSUE THREAD

**Issue by Ian8888** [apache/incubator-mxnet#14333]
I use predcit api in web(https://mxnet.incubator.apache.org/api/python/module/module.html).

I use ImageIter api reading image(It format has [index, label, path]),and mod.predict receive image data, but the predict result can't return label. 

If I need know the label information to calculate the precision. What I can use? 
(My label is 0 or 1 in image data) 
(Example: first Image is label 0, via the predict and math model result is 0. Then I can calculate precision. )

### My code: 
```
test_data = mx.image.ImageIter(
    path_imgrec = Testing_Rec_path,
    path_imglist= Testing_lst_path,
    batch_size = batch_size,
    data_shape = (Training_IMG_channel, Training_IMG_size, Training_IMG_size),
    )

sym,arg_params,aux_params = mx.model.load_checkpoint('models/model', num_batch)  

mod = mx.mod.Module(symbol=sym,context=mx.gpu(),data_names=['data'],label_names=[]) 
mod.bind(for_training=False,data_shapes=[('data', (batch_size, 3, 224, 224))])
mod.set_params(arg_params,aux_params)

predict_stress = mod.predict(test_data, num)
print(predict_stress)

for i in range(batch_size):
	if( np.max(b1[i]) > t[0] ):
		y = b1[i]
	elif( np.max(b2[i]) > t[1]):
		y = b2[i]
	elif( np.max(b3[i]) > t[2]):
		y = b3[i]
 	else:
 		y = mx.ndarray.dot(1/3,mx.ndarray.sum(b1[i],b2[i],b3[i])) 
		print(y)
		print(i)
 	if(y[0] > y[1]):
 		r[i] = 0
 	else:
		r[i] = 1

for i in range(batch_size*num):
	print(i)
	print(r[i])
```

### Program Result:

> [15:38:04] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:109: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
> 
> [[ 0.13922502 -0.11606336]
>  [ 2.5491626  -2.5001898 ]
>  [ 3.2227821  -3.1646605 ]
>  [ 0.5590247  -0.55947936]
>  [ 2.553718   -2.5245237 ]
>  [ 2.3555253  -2.3232493 ]
>  [-0.507339    0.5406278 ]
>  [-3.6946535   3.7650285 ]
>  [ 3.7202609  -3.6908817 ]
>  [-1.4234478   1.4493531 ]
>  [ 1.0976249  -1.0919478 ]
>  [-1.2567718   1.292368  ]
>  [ 2.9257362  -2.8744373 ]
>  [ 1.1325525  -1.0528516 ]
>  [ 1.5805603  -1.5619096 ]
>  [ 2.7989933  -2.7746105 ]
>  [-0.08484261  0.11545819]
>  [ 0.7736175  -0.73774874]
>  [ 6.159645   -6.2119994 ]
>  [ 2.2064366  -2.1589112 ]]
> <NDArray 20x2 @gpu(0)>,
> [[ 1.7868224  -1.7491719 ]
>  [ 3.0314004  -2.9930372 ]
>  [ 2.722186   -2.6855104 ]
>  [ 0.6666924  -0.6146085 ]
>  [ 1.8936342  -1.8417997 ]
>  [-1.1667107   1.1841551 ]
>  [ 0.523639   -0.50577116]
>  [-3.8795347   3.8734357 ]
>  [ 2.3370705  -2.2796764 ]
>  [-2.1853673   2.2118893 ]
>  [ 2.6006656  -2.5628548 ]
>  [ 2.9841046  -2.9405618 ]
>  [ 1.2362471  -1.2052159 ]
>  [ 1.8720301  -1.8446524 ]
>  [ 2.2604988  -2.2260802 ]
>  [ 2.853581   -2.7872398 ]
>  [-0.35405207  0.384872  ]
>  [-1.5976307   1.6023796 ]
>  [ 5.9638176  -5.894341  ]
>  [ 2.8867698  -2.8354802 ]]
> <NDArray 20x2 @gpu(0)>,
> [[-0.71735334  0.7268183 ]
>  [ 1.1493353  -1.135744  ]
>  [ 2.602397   -2.5691428 ]
>  [ 2.0736756  -2.060786  ]
>  [ 3.7577837  -3.7404618 ]
>  [ 1.096659   -1.0867544 ]
>  [ 1.3795273  -1.3542635 ]
>  [-0.965839    0.9946723 ]
>  [ 4.6658382  -4.6550856 ]
>  [ 1.2424159  -1.216668  ]
>  [ 2.348465   -2.3282752 ]
>  [ 0.70985705 -0.6997764 ]
>  [ 3.2956235  -3.2734258 ]
>  [ 1.824274   -1.8073335 ]
>  [ 1.048631   -1.0324684 ]
>  [ 3.4485407  -3.4328256 ]
>  [ 1.279889   -1.2544599 ]
>  [-1.906233    1.9364383 ]
>  [ 8.533272   -8.450782  ]
>  [ 1.3803874  -1.363959  ]]
> <NDArray 20x2 @gpu(0)>]
> 
> 0
> [1.]
> 1
> [0.]
> 2
> [0.]
> 3
> [0.]
> 4
> [0.]
> 5
> [0.]
> 6
> [0.]
> 7
> [1.]
> 8
> [0.]
> 9
> [0.]
> 10
> [0.]
> 11
> [0.]
> 12
> [0.]
> 13
> [0.]
> 14
> [0.]
> 15
> [0.]
> 16
> [0.]
> 17
> [1.]
> 18
> [0.]
> 19
> [0.]
>

**Comment by piyushghai** [comment]
@Ian8888 Can you shed some light on the model you are using ? 
Specifically, what's the last layer of your model ? Is it Sigmoid or Softmax ? 
In case you want to do a binary classification, you could use the softmax layer at the end to convert the output from your model to probability values, and based on that you can predict the class as being x or y ( Or 0 or 1 in your case ).

@mxnet-label-bot Add [Python, Question]

**Comment by Ian8888** [comment]
> @Ian8888 Can you shed some light on the model you are using ?
> Specifically, what's the last layer of your model ? Is it Sigmoid or Softmax ?
> In case you want to do a binary classification, you could use the softmax layer at the end to convert the output from your model to probability values, and based on that you can predict the class as being x or y ( Or 0 or 1 in your case ).
> 
> @mxnet-label-bot Add [Python, Question]



> @Ian8888 Can you shed some light on the model you are using ?
> Specifically, what's the last layer of your model ? Is it Sigmoid or Softmax ?
> In case you want to do a binary classification, you could use the softmax layer at the end to convert the output from your model to probability values, and based on that you can predict the class as being x or y ( Or 0 or 1 in your case ).
> 
> @mxnet-label-bot Add [Python, Question]

The last layer is softmax.
I tried using data.label to get the label information.
Hope, the softmax result has mapping the label information.

**Comment by chinakook** [comment]
Yes, it's normal. You should add a argmax layer on the top of the network to get the label

**Comment by Ian8888** [comment]
> Yes, it's normal. You should add a argmax layer on the top of the network to get the label

Thanks, your suggest. I can get label to calculate.

But, I have the new issue about the "equal operate" in different type.

```
if(r[s_tmp] == label_inf[0][x]):
            sum += 1
```

> type(label_inf[0][x])  <class 'mxnet.ndarray.ndarray.NDArray'>
> label_inf[0][x] is [0.]
> type(r[s_tmp])   <type 'numpy.ndarray'>
> r[s_tmp]  is [1.]
> TypeError: type <type 'numpy.ndarray'> not supported

Have any api can compare this type or convert the same type?
