### ISSUE TITLE
Ensure all usage of `ndim` to be 0-d tensor compatible

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#14342]
EDIT: See also #14323.

After #14315, we should check all the occurrence of `ndim` to ensure they are used correctly in the semantics of 0-d tensor.

@reminisce @szha @eric-haibin-lin @zheng-da @yzhliu

# List of occurrence
## src/c_api
* [x] src/c_api/c_api.cc
* [x] src/c_api/c_api_common.h
* [x] src/c_api/c_api_symbolic.cc
* [x] src/c_api/c_predict_api.cc

## src/common
* [x] src/common/serialization.h
* [x] src/common/static_array.h
* [x] src/common/utils.h

## src/executor
* [x] src/executor/infer_graph_attr_pass.cc

## src/imperative
* [x] src/imperative/cached_op.cc
* [x] src/imperative/imperative_utils.h

## src/io
* [x] src/io/image_aug_default.cc
* [x] src/io/image_det_aug_default.cc
* [x] src/io/image_io.cc
* [x] src/io/image_iter_common.h
* [x] src/io/iter_batchloader.h
* [x] src/io/iter_image_det_recordio.cc
* [x] src/io/iter_image_recordio_2.cc
* [x] src/io/iter_libsvm.cc
* [x] src/io/iter_sparse_batchloader.h

## src/kvstore
* [x] src/kvstore/gradient_compression.cc
* [x] src/kvstore/kvstore_dist.h
* [x] src/kvstore/kvstore_dist_server.h

## src/ndarray
* [x] src/ndarray/ndarray.cc
* [x] src/ndarray/ndarray_function.cc
* [x] src/ndarray/ndarray_function.cu
* [x] src/ndarray/ndarray_function.h

## src/nnvm
Nothing here.

## include
* [x] include/mxnet/ndarray.h
* [x] include/mxnet/operator.h
* [x] include/mxnet/operator_util.h
* [x] include/mxnet/resource.h
* [x] include/mxnet/tensor_blob.h
* [x] include/mxnet/tuple.h

**Comment by reminisce** [comment]
Also include all the infer shape functions of operators.
https://github.com/apache/incubator-mxnet/issues/14323

**Comment by junrushao1994** [comment]
@reminisce Yep. I intentionally ignored `src/operator` in this list because there are too many occurrences in that list, and we should share efforts across these two things - logic and implementation

**Comment by piyushghai** [comment]
@mxnet-label-bot Add [Numpy]

**Comment by piyushghai** [comment]
@mxnet-label-bot Update [Operator]

**Comment by junrushao1994** [comment]
Going to act on this thread this week. I guess most of them have been addressed in recent PRs like #14361, #14315, #14409.

**Comment by junrushao1994** [comment]
#14612
