### ISSUE TITLE
Android port fails with UnsatisfiedLinkError

### ISSUE THREAD

**Issue by bornfree** [apache/incubator-mxnet#1436]
Cross compiling mxnet for Android using instructions at  https://github.com/dmlc/mxnet/blob/master/amalgamation/README.md builds an ARM library sized around 1.8 MB. (OpenBLAS enabled and already crosscompiled)

But when used on the device, it fails with
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Znwj" referenced by "libmxnet_predict.so"`
I'm guessing this is happening because OpenBLAS functions aren't being linked against.

Interestingly, the **mxnet_predict.so** that is available in https://github.com/Leliana/WhatsThis is 5 MB and doesn't throw this error. Any ideas what could be going wrong.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
