### ISSUE TITLE
I  failed to install the mxnet-mkl version on Windows 10

### ISSUE THREAD

**Issue by LittleFatHero** [apache/incubator-mxnet#14376]
OS ：Windows 10 professional
I installed mxnet-mkl version using the following command:

_conda create -n mxnet_mkl_env python=3.6
conda activate mxnet_mkl_env
pip install mxnet-mkl_

When I finished  the installation, I executed the following command in python environment：

>>_import  mxnet as mx_

An error occurred:

**Traceback (most recent call last):
File “”, line 1, in 
File “C:\Users\sheep\Miniconda3\envs\mxnet_mkl\lib\site-packages\mxnet_init_.py”, line 24, in 
from .context import Context, current_context, cpu, gpu, cpu_pinned
File “C:\Users\sheep\Miniconda3\envs\mxnet_mkl\lib\site-packages\mxnet\context.py”, line 24, in 
from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
File “C:\Users\sheep\Miniconda3\envs\mxnet_mkl\lib\site-packages\mxnet\base.py”, line 213, in 
_LIB = _load_lib()
File “C:\Users\sheep\Miniconda3\envs\mxnet_mkl\lib\site-packages\mxnet\base.py”, line 204, in load_lib
lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
File "C:\Users\sheep\Miniconda3\envs\mxnet_mkl\lib\ctypes_init.py", line 348, in init
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found.**

What is the problem and how should I fix it?
Could someone tell me how to fix it in detail ?
Thanks

**Comment by pengzhao-intel** [comment]
@juliusshufan could you help take a look?

@mxnet-label-bot add [Installation, MKLDNN, Windows]

**Comment by wufengqian** [comment]
Hi,
    I also asked the same question in [discuss.gluon.ai](url) ,but it seems that no one know how to solve the problem in detail.

**Comment by pengzhao-intel** [comment]
Sorry, we don't check the forum frequently :(
BTW, please wait a moment because we are building the windows system inside now.

**Comment by wufengqian** [comment]
Building the windows system inside? I'm sorry but I am curious about that. What is the purpose ?

**Comment by pengzhao-intel** [comment]
To reproduce the problem on the Windows

**Comment by stereomatchingkiss** [comment]
> To reproduce the problem on the Windows

Any chances to add a travis build for windows(if you have enough of resources) like #14370 suggest?
One with mkl + cuda
Another one with mkl

This way whenever you commit the codes written on x platform(mac osx, linux etc), you can ensure your new codes do not break anything on windows.
It would be better if you add travis build for every platforms you plan to support, like opencv.

**Comment by juliusshufan** [comment]
As a quick update, this issue can be reproduced with build from source on windows, with mkl+mkldnn,
will keep on the root causing. @pengzhao-intel @stereomatchingkiss

**Comment by wufengqian** [comment]
This problem really make me ,,,,a little upset, at so far I still didn't know how to fix the problem in a simple or understandable way .

**Comment by wufengqian** [comment]
I think the best way is the mxnet should add support to conda instead of  just supporting pip. Just like pytorch, there is no difference in windows and linux.

**Comment by juliusshufan** [comment]
@wufengqian 
Can you please try the below steps to make it works?
1. Download and install the latest full MKL version following instructions on the intel website. https://software.intel.com/en-us/mkl
2. Add the mkl dll path to Windows PATH, the local is similiar to: (X standing for the partition you installing the full MKL)
: X:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.3.203\windows\redist\intel64_win\mkl

Thanks.

**Comment by wufengqian** [comment]
> @wufengqian
> Can you please try the below steps to make it works?
> 
> 1. Download and install the latest full MKL version following instructions on the intel website. https://software.intel.com/en-us/mkl
> 2. Add the mkl dll path to Windows PATH, the local is similiar to: (X standing for the partition you installing the full MKL)
>    : X:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.3.203\windows\redist\intel64_win\mkl
> 
> Thanks.

Thanks, but I'm sorry and I won't try this. Because my SSD's volume is small and the full MKL version is such a big guy,,,,,,,,,. And the most important thing is I think the mxnet should do the thing just like the pytorch does that just need one command that I can install all I need.

**Comment by pengzhao-intel** [comment]
Updated the windows doc in below link which will resolve the issue.
https://mxnet.incubator.apache.org/versions/master/tutorials/mkldnn/MKLDNN_README.html#3
