### ISSUE TITLE
Links and References in Julia tutorials are broken

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#14371]
The links and references in the two Julia tutorials are broken - 
 - [MNIST](https://github.com/apache/incubator-mxnet/blob/master/julia/docs/src/tutorial/mnist.md) 
 - [LSTM Sentence generator](https://github.com/apache/incubator-mxnet/blob/master/julia/docs/src/tutorial/char-lstm.md) 

The links point to the old dmlc url.

**Comment by piyushghai** [comment]
@mxnet-label-bot Add [Doc, Julia]

**Comment by piyushghai** [comment]
@anirudhacharya 
Good catch. Can you perhaps also raise a PR to fix this ? 

@mxnet-label-bot Update [Doc, Julia, Good First Issue]

**Comment by anirudhacharya** [comment]
@piyushghai I do not know the proper links and references. I was just trying to checkout mxnet's julia bindings and found the tutorial links were broken. The author of the tutorials might be able to fix it.

**Comment by TEChopra1000** [comment]
I have gone through and replaced the broken links - the changes will go out with my next PR. I will comment once everything is updated and we can close this ticket.

**Comment by TEChopra1000** [comment]
The links on this page have been fixed. @aaronmarkham you can close this ticket.
