### ISSUE TITLE
beta.mxnet.io does not contain verification step for installation (新版官网没有验证安装过程)

### ISSUE THREAD

**Issue by LittleFatHero** [apache/incubator-mxnet#14375]
新版官网：beta.mxnet.io
该官网只有安装过程，没有说有验证过程，能否把验证cuda版mxnet是否安装成功的，以及mxnet-mkl版本是否安装成功加上？
PS：我知道旧版官网有验证过程，但是不是很明显，也得找的。特别是MKL版本的，得四处找才能找到，何不安装和验证都放在一个页面，改善大家的体验？

**Comment by pengzhao-intel** [comment]
@wufengqian thanks for the great suggestions.
@TaoLv is working on the MKL documentation https://github.com/apache/incubator-mxnet/pull/14202

@mxnet-label-bot add [doc, questions]

**Comment by pengzhao-intel** [comment]
@juliusshufan

**Comment by aaronmarkham** [comment]
Hi  @LittleFatHero I added this: https://beta.mxnet.io/install/validate-mxnet.html
Does this solve the issue?

**Comment by LittleFatHero** [comment]
> Hi @LittleFatHero I added this: https://beta.mxnet.io/install/validate-mxnet.html
> Does this solve the issue?

Yes, it is really nice , it would be better if you can add the validation of mxnet mkl version!

**Comment by aaronmarkham** [comment]
> > Hi @LittleFatHero I added this: https://beta.mxnet.io/install/validate-mxnet.html
> > Does this solve the issue?
> 
> Yes, it is really nice , it would be better if you can add the validation of mxnet mkl version!

I can add a link to this over there:
https://mxnet.incubator.apache.org/versions/master/tutorials/mkldnn/MKLDNN_README.html#verify-whether-mkl-dnn-works

**Comment by aaronmarkham** [comment]
Added a PR for this here: https://github.com/mli/new-docs/pull/107
I'm going to close this issue now as it looks like we have the bases covered. Feel free to reopen if I missed something.
