### ISSUE TITLE
Broken pip package mxnet-cu80 1.5.0b20190310

### ISSUE THREAD

**Issue by redbaron4** [apache/incubator-mxnet#14389]
The nightly build package for windows uploaded to pypi by the build bot on March 10 seems broken. The file https://files.pythonhosted.org/packages/9a/bc/ee216a4dbe1433d881906513768cf61f9d52c1f8dee133f69f99e1ee9ec7/mxnet_cu80-1.5.0b20190310-py2.py3-none-win_amd64.whl shows a size of 0 bytes on download when it should have 259MB size. The MD5 and SHA-256 checksums are also different.

This is causing issues in our pypi mirror sync as mxnet-cu80 can never complete sync due to broken files. Please fix this if possible.

**Comment by piyushghai** [comment]
@marcoabreu Are you aware of any issues with the nightly publishing pipeline ? 

@mxnet-label-bot Add [Windows, Pip]

**Comment by redbaron4** [comment]
It seems to be a PyPI issue because the file is correctly accessible from my home network. Apologies for this.
