### ISSUE TITLE
How to visualize intermediate results / symbols 

### ISSUE THREAD

**Issue by gnujimmik** [apache/incubator-mxnet#1440]
I was wondering it there is any way to visualized symbols from each layer. I'd like to make sure that the training goes on the right track. Thank you in advance!

**Comment by piiswrong** [comment]
You can use mx.monitor

**Comment by gnujimmik** [comment]
you mean use like this?

def norm_stat(d):
    return mx.nd.norm(d)/np.sqrt(d.size)
mon = mx.mon.Monitor(100, norm_stat)
model.fit(X=train, eval_data=val, monitor=mon, 
          batch_end_callback = mx.callback.Speedometer(100, 100))

as in the example?

**Comment by piiswrong** [comment]
yes

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
