### ISSUE TITLE
How to get the output of last layer after every batch as ndarray?

### ISSUE THREAD

**Issue by aplusc98** [apache/incubator-mxnet#14429]
I'm using the Mxnet implementation of Resnet by https://github.com/khetan2/mbem and https://github.com/tornadomeet/ResNet/
I'm using the resnet for a 10 way image classification.
I use a batch size of 500 and I want to perform a matrix operation on the output obtained after the last gully connected layer. I want to access the output as NDArray(batch X no of classes i.e. 500 x 10). Till now I'm getting it as mxnet symbol and am not able to extract the data referenced with the symbol. How do I achieve this?

**Comment by anirudh2290** [comment]
@aplusc98 Calling predict on model should return the outputs as ndarray. If you are using module API call get_outputs() in module API. 

This question is more suited for discuss.mxnet.io and will get higher visibility. Github issues is mainly for tracking mxnet issues. Closing.
