### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by yongfang1995** [apache/incubator-mxnet#14437]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
I did the following:

git clone --recursive https://github.com/apache/incubator-mxnet.git
cd incubator-mxnet
make -j4

## Error Message:
![image](https://user-images.githubusercontent.com/48436808/54449650-98bb1580-4789-11e9-8eda-33ad937ee9ec.png)

Can someone  tell me how to solve this issue.

**Comment by wkcn** [comment]
Could you please provide the error message?

**Comment by wkcn** [comment]
Please install cmake

**Comment by yongfang1995** [comment]
Thank you
I instaledl cmake,and got the following error:
![image](https://user-images.githubusercontent.com/48436808/54470280-f37f5c00-47df-11e9-9560-47b40c7f9ce1.png)

**Comment by TaoLv** [comment]
Seems BLAS is missing. You need install either openblas or mkl and set USE_BLAS=openblas or mkl respectively in the make line.

**Comment by TaoLv** [comment]
BTW, you can follow this document to build MXNet from source: https://mxnet.incubator.apache.org/versions/master/install/ubuntu_setup.html#build-mxnet-from-source

**Comment by TaoLv** [comment]
@yongfang1995  It looks like you have finished the compilation successfully. I will close the issue now. Feel free to reopen if you still have problem on it.
