### ISSUE TITLE
[Torch] Cannot perform shape inference for cuda only operations (such as cudnn)

### ISSUE THREAD

**Issue by lukemetz** [apache/incubator-mxnet#1444]
Doing something as follows crashes.

``` python
    nn = """
    (function()
        mod = cudnn.SpatialConvolution(%d, %d, %d, %d, %d, %d, %d, %d, 1)
        mod = mod:cuda()
        return mod
    end
    )()"""%(nInputPlane, nOutputPlane, kernel[0], kernel[1], stride[0], stride[1], pad[0], pad[1])
    return mx.sym.TorchModule(data_0=data, lua_string=nn, num_data=1, num_params=2, num_outputs=1, name=name)
```

```
torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:33: Only Cuda supported duh!
```

It is an issue with shape inference not knowing what device to run the operation on.

**Comment by piiswrong** [comment]
shape inference is only run on cpu.
An easy solution is to add a flag in TorchModeleParam to specify if you want shape inference to run on gpu, but this own allow selecting which gpu to run on.

**Comment by lukemetz** [comment]
I was thinking something similar. I will look into this when I get a few moments free.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
