### ISSUE TITLE
Cannot release memory sometimes

### ISSUE THREAD

**Issue by ShownX** [apache/incubator-mxnet#14459]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
I realize sometimes when the program is stopped by key interruption, it cannot release the CPU and GPU memory

## Environment info (Required)
Ubuntu 18.04
CUDA 9
MXNET 1.4/1.5
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using Python)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Run the program
2. Stop it by Ctrl-C

## What have you tried to solve it?

1. Manually find the process and kill it

**Comment by zachgk** [comment]
@ShownX Can you provide some more information? Can you give the example or a minimal script that causes the problem?

Can you also provide the above information about the package you are using (Python, R, Scala, etc.) and run the diagnosis script:
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

@mxnet-label-bot add [Memory, Exception Handling, Pending Requester Info]

**Comment by zachgk** [comment]
@mxnet-label-bot add [Memory, Exception Handling, Pending Requester Info]

**Comment by chinakook** [comment]
Please repeat Ctrl-C until you get back to the console.

**Comment by ShownX** [comment]
Hi, Thank you for the response. Right now, I cannot provide the code I am running as an example. Definitely, repeating Ctrl-C does not help.

**Comment by ShownX** [comment]
![Screenshot from 2019-03-19 16-54-23](https://user-images.githubusercontent.com/9678100/54644629-c2b15800-4a67-11e9-8f41-f58ad6f17f45.png)
It can be notice that the gpu memory cannot be released and there is no process shown in nvidia-smi

**Comment by chinakook** [comment]
You are on persistance mode. Ctrl-c cannot release the memory

**Comment by ShownX** [comment]
What is persistance mode? How can I avoid this mode?

**Comment by chinakook** [comment]
```sudo nvidia-smi -pm 0```

**Comment by vdantu** [comment]
@ShownX : Did you try the suggestion given by @chinakook ? Are you still facing this issue?

Some other suggestions going through online forums are 
1. Kill all python processes on the system.
```
killall python
```
2. Do a list of all processes on that GPU
```
lsof /dev/nvidia*
```
and kill all processes running on that GPU. [Refer this](https://github.com/neighthan/gpu-utils/blob/c6329f21fa3780ee89985b7974194cb808643f5c/gpu_utils/utils.py#L114)

**Comment by lanking520** [comment]
@ShownX Close this for now due to the inactivity. Please feel free to reopen if problem persisit
