### ISSUE TITLE
Create a Dataset Using RecordIO

### ISSUE THREAD

**Issue by essalahsouad** [apache/incubator-mxnet#14458]
I am trying to follow the example  [https://mxnet.incubator.apache.org/versions/master/faq/recordio.html](url) and create my own dataset for training using MXnet. My data is organized as specified in the example:

`/data
file1.jpg
file2.jpg
...`
The tutorial says the first step is to run im2rec.py to create a .lst file.
`python im2rec1.py /home/dell/Bureau/data1  /home/dell/Bureau/data/ --recursive --list --num-thread 8`
teh output data1.lst
![Capture du 2019-03-18 13-23-38](https://user-images.githubusercontent.com/34586193/54529735-11d08d80-4981-11e9-90ce-b43b9ea1ed0f.png)
The format is:
`integer_image_index \t label_index \t path_to_image`
But i don't know if my output is it correct??

**Comment by zachgk** [comment]
For questions, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [Question, Example]

**Comment by essalahsouad** [comment]
> For questions, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
> I'm closing this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
> Thanks!

Thank you
