### ISSUE TITLE
broken clojure test

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#14450]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14444/3/pipeline/246

**Comment by andrewfayres** [comment]
Issue was resolved with #14448 which disabled the tests. Those tests have a dependency on an external repository which was experiencing an outage. There is an open issue about how to handle this dependency here  #14394.

@mxnet-label-bot add [Test, Clojure]
