### ISSUE TITLE
[numpy] Fix test failures after using new shape semantics for zero-dim/size tensors

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#14454]
**Branch:** https://github.com/apache/incubator-mxnet/tree/numpy

## CPU withou MKLDNN

**Folder:** [tests/python/unittest](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/unittest)

| Errors/Failures (CPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
|  test_contrib_control_flow.test_contrib_rnn  |     @zheng-da       | Fixed by  https://github.com/apache/incubator-mxnet/pull/14520       |
| test_dynamic_shape.test_dynamic_shape  |    @junrushao1994        |    Fixed by https://github.com/apache/incubator-mxnet/pull/14538     |
| test_gluon_contrib.test_convrnn  |           |     Resolved    |
| test_gluon_contrib.test_convlstm  |           |     Resolved    |
| test_gluon_contrib.test_convgru  |           |    Resolved     |
| test_gluon_contrib.test_conv_fill_shape  |           |  Resolved       |
| test_gluon_contrib.test_lstmp  |           |   Resolved      |
| test_gluon_contrib.test_vardrop  |           |    Resolved     |
| test_gluon_contrib.test_contrib_unroll  |   @junrushao1994          |    Resolved     |
| test_gluon_data.test_recordimage_dataset | @szha  | Resolved |
| test_gluon_model_zoo.test_models  |           |    Resolved     |
| test_gluon.test_deconv | @reminisce   | Resolved |
| test_gluon.test_symbol_block  |           |   Resolved      |
| test_gluon.test_deferred_init  |           |     Resolved    |
| test_gluon.test_hybrid_stale_cache  |           |   Resolved      |
| test_gluon.test_fill_shape_deferred  |           |    Resolved     |
| test_gluon.test_dtype  |           |    Resolved     |
| test_gluon.test_fill_shape_load  |           |    Resolved     |
| test_gluon.test_inline  |           |    Resolved     |
| test_gluon.test_req  |           |  Resolved       |
| test_gluon.test_save_load  |           |   Resolved      |
| test_gluon.test_symbol_block_save_load  |           |   Resolved      |
| test_gluon.test_hybrid_multi_context  |           |   Resolved      |
| test_gluon.test_hook  |           |  Resolved       |
| test_gluon.test_summary  |           |   Resolved      |
| test_gluon.test_legacy_save_params  |           |    Resolved     |
| test_gluon.test_conv2d_16c  |           | Resolved        |
| test_gluon.test_group_conv2d_16c  |           |  Resolved       |
| test_gluon.test_concat  |           |   Resolved      |
| test_gluon.test_reshape_conv  |           |   Resolved      |
| test_gluon.test_slice_conv  |           |     Resolved    |
| test_gluon.test_slice_conv_slice_conv  |           |  Resolved       |
| test_gluon.test_reshape_dense  |           |   Resolved      |
| test_gluon.test_slice_dense  |           |  Resolved       |
| test_gluon.test_slice_dense_slice_dense  |           |   Resolved      |
| test_gluon.test_reshape_dense_reshape_dense  |           |    Resolved     |
| test_gluon.test_slice_dense_reshape_dense  |           | Resolved        |
| test_gluon.test_reshape_dense_slice_dense  |           |    Resolved     |
| test_gluon.test_slice_batchnorm  |           |    Resolved     |
| test_gluon.test_slice_batchnorm_reshape_batchnorm  |           |    Resolved     |
| test_gluon_rnn.test_rnn  |           |     Resolved    |
| test_gluon_rnn.test_lstm  |           |  Resolved       |
| test_gluon_rnn.test_lstm_forget_bias  |           |     Resolved    |
| test_gluon_rnn.test_lstm_cpu_inference  |           |  Resolved       |
| test_gluon_rnn.test_gru  |           |  Resolved       |
| test_gluon_rnn.test_residual  |           |  Resolved       |
| test_gluon_rnn.test_residual_bidirectional  |           |    Resolved     |
| test_gluon_rnn.test_stack  |           |    Resolved     |
| test_gluon_rnn.test_hybridstack  |           |    Resolved     |
| test_gluon_rnn.test_bidirectional  |           |   Resolved      |
| test_gluon_rnn.test_layer_bidirectional  |           |  Resolved       |
| test_gluon_rnn.test_zoneout  |           |    Resolved     |
| test_gluon_rnn.test_unroll_layout  |           |  Resolved      |
| test_gluon_rnn.test_rnn_cells_export_import  |           |   Resolved      |
| test_gluon_rnn.test_rnn_layers_fp32  |           |      Resolved   |
| test_gluon_rnn.test_rnn_unroll_variant_length  |           |   Resolved      |
| test_gluon_rnn.test_cell_fill_shape  |           |  Resolved       |
| test_gluon_rnn.test_layer_fill_shape  |           |     Resolved    |
| test_gluon_rnn.test_bidirectional_unroll_valid_length  |           |    Resolved     |
| test_gluon_trainer.test_trainer_multi_layer_init  |           |  Resolved       |
| test_infer_shape.test_incomplete_infer_elewise  |   @reminisce         |   Resolved      |
| test_infer_shape.test_incomplete_infer_mlp  |  @reminisce          |  Resolved       |
| test_infer_shape.test_incomplete_infer_slicechannel  |   @reminisce         |   Resolved      |
| test_infer_shape.test_incomplete_infer_convolution  |  @reminisce          |    Resolved     |
| test_infer_shape.test_incomplete_infer_concat  |   @reminisce         |  Resolved       |
| test_init.test_default_init  |    @reminisce        |   Resolved      |
| test_init.test_variable_init  |    @reminisce        |     Resolved    |
| test_io.test_NDArrayIter_csr  |  @eric-haibin-lin          |    Resolved     |
| test_io.test_LibSVMIter  |   @eric-haibin-lin   |   Fixed locally      |
| test_ndarray.test_ndarray_setitem | @reminisce  |    Resolved    |
| test_module.test_module_states  |           |   Resolved      |
| test_module.test_module_switch_bucket  |           |    Resolved     |
| test_module.test_executor_group  |           |  Resolved      |
| test_module.test_factorization_machine_module | @eric-haibin-lin | Fixed by sparse slice  |
| test_operator.test_lstm_sym  |  @reminisce          |     Resolved    |
| test_operator.test_lstm_bidirectional  |  @reminisce          | Resolved        |
| test_operator.test_gru_sym  |  @reminisce          |     Resolved    |
| test_operator.test_gru_bidirectional  |  @reminisce         |    Resolved     |
| test_operator.test_rnntanh_sym  |   @reminisce         |  Resolved       |
| test_operator.test_rnntanh_bidirectional  |  @reminisce          |    Resolved     |
| test_operator.test_rnnrelu_sym  |  @reminisce          |    Resolved     |
| test_operator.test_rnnrelu_bidirectional  |   @reminisce         |   Resolved      |
| test_operator.test_boolean_mask  |  @reminisce          |   Resolved      |
| test_operator.test_custom_op  |      @reminisce      |   Resolved      |
| test_operator.test_multi_proposal_op  |  @reminisce          |   Resolved      |
| test_operator.test_diag |  @reminisce          |     Resolved    |
| test_predictor.test_predictor  |           |    Resolved     |
| test_rnn.test_deprecated  |           |   Resolved      |
| test_rnn.test_rnn  |           |    Resolved     |
| test_rnn.test_lstm  |           | Resolved        |
| test_rnn.test_lstm_forget_bias  |           |      Resolved   |
| test_rnn.test_gru  |           |     Resolved    |
| test_rnn.test_residual  |           |  Resolved       |
| test_rnn.test_residual_bidirectional  |           |    Resolved     |
| test_rnn.test_stack  |           |    Resolved     |
| test_rnn.test_bidirectional  |           |     Resolved    |
| test_rnn.test_zoneout  |           |  Resolved       |
| test_rnn.test_unfuse  |           |     Resolved    |
| test_rnn.test_convrnn  |           |     Resolved    |
| test_rnn.test_convlstm  |           | Resolved        |
| test_rnn.test_convgru  |           |   Resolved      |
| test_sparse_ndarray.test_sparse_nd_slice  |     @reminisce       |  Resolved  |
| test_sparse_operator.test_sparse_slice  |  @eric-haibin-lin          |   Resolved      |
| test_subgraph_op.test_subgraph_exe  |    @reminisce        |   Resolved      |
| test_subgraph.test_make_subgraph  |           |     Resolved    |
| test_symbol.test_symbol_infer_shape  |           |   Resolved      |
| test_thread_local.test_createblock |       |    Resolved      |
| test_kvstore.test_single_kv_pair | @eric-haibin-lin | Resolved |

**Folder:** [tests/python/train](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/train)

| Errors/Failures (CPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
|  test_autograd.test_autograd |           |  Resolved      |
| test_bucketing.test_bucket_module |          |  Resolved        |
| test_sparse_fm.test_factorization_machine_module |  @eric-haibin-lin | Fixed by sparse slice |

**Folder:** [tests/python/gpu](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/gpu)

## GPU

| Errors/Failures (GPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
|  test_operator_gpu.test_pooling_versions |   @reminisce         |  Fixed by https://github.com/apache/incubator-mxnet/pull/14577     |
| test_operator_gpu.test_global_pooling |  @reminisce         |    Fixed by https://github.com/apache/incubator-mxnet/pull/14577     |
| test_operator_gpu.test_upsampling_bilinear_with_type | @junrushao1994  | Fixed by https://github.com/apache/incubator-mxnet/pull/14557 |
| test_operator_gpu.test_embedding_with_type | @eric-haibin-lin   | Cannot reproduce with 10K runs |
| test_operator_gpu.test_deconvolution | @szha  | Cannot reproduce |
| test_operator_gpu.test_deformable_convolution_with_type | @zheng-da  | Fixed by https://github.com/apache/incubator-mxnet/pull/14577 |
| test_operator_gpu.test_deformable_convolution_options | @zheng-da  | Fixed by https://github.com/apache/incubator-mxnet/pull/14577 |

## CPU with MKLDNN

**Folder:** [tests/python/unittest](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/unittest)

| Errors/Failures (CPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
| test_gluon_rnn.test_rnn_cells   |   @lihaofd         |  Resolved     |
| test_io.test_LibSVMIter   |           |  May have been fixed on master     |
| Test factorization machine model with sparse operators   |           |   Resolved    |
| test_operator.test_lstm_bidirectional   |    @lihaofd        |  Resolved     |
| test_operator.test_gru_bidirectional   | @lihaofd           |   Resolved    |
| test_operator.test_rnntanh_bidirectional |  @lihaofd          |     Resolved  |
|   test_operator.test_rnnrelu_bidirectional  |  @lihaofd          |    Resolved   |
| test_operator.test_concat | @TaoLv |Resolved |
| test_operator.test_slice | @TaoLv |Resolved |
| test operators which don't implement FComputeEx or FStatefulComputeEx | @ZhennanQin |Resolved |

**Folder:** [tests/python/train](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/train)

| Errors/Failures (CPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
| Test factorization machine model with sparse operators | | Resolved|

**Folder:** [tests/python/mkl](https://github.com/apache/incubator-mxnet/tree/numpy/tests/python/mkl)

| Errors/Failures (CPU) |   Assignee |  Status |
|-------------------------|------------------------------|--------|
| test_subgraph.test_pos_single_concat | |Resolved |

## CPP TEST
```
[----------] 2 tests from ACTIVATION_PERF
[ RUN      ] ACTIVATION_PERF.ExecuteBidirectional
Segmentation fault (core dumped)
tests/cpp/unittest.mk:68: recipe for target 'runtest' failed
make: *** [runtest] Error 139
```

[train.log](https://github.com/apache/incubator-mxnet/files/2993590/train.log)
[unittest.log](https://github.com/apache/incubator-mxnet/files/2993591/unittest.log)
[gpu.log](https://github.com/apache/incubator-mxnet/files/3011452/gpu.log)
[unittest_mkldnn.log](https://github.com/apache/incubator-mxnet/files/3011771/unittest_mkldnn.log)

**Comment by junrushao1994** [comment]
Cannot reproduce `test_gluon_contrib.test_contrib_unroll` now, did I miss anything?

**Comment by reminisce** [comment]
I took a look at unittest.log. `test_gluon_contrib.test_contrib_unroll` should have been fixed by
https://github.com/apache/incubator-mxnet/pull/14520/files#diff-18a3d5a32b024eb7f4d6560001898c4cL755
Thanks for working on it.

**Comment by pengzhao-intel** [comment]
@TaoLv will help taking look the MKLDNN related issues in the list :)

**Comment by pengzhao-intel** [comment]
cc @juliusshufan

**Comment by TaoLv** [comment]
@reminisce Do you have steps for reproducing those failures on local machine?

**Comment by reminisce** [comment]
@TaoLv Let's talk offline today.
