### ISSUE TITLE
undefined symbol: _Z9rleDecodePK3RLEPhm

### ISSUE THREAD

**Issue by roadcode** [apache/incubator-mxnet#14471]
When import mxnet in python, the error occurs:
libmxnet.so: undefined symbol: _Z9rleDecodePK3RLEPhm

## Build info (Required if built from source)
git clone https://github.com/apache/incubator-mxnet mxnet
cd mxnet
git checkout 1.3.1
git submodule init
git submodule update:
cp -r $SIMPLEDET_DIR/operator_cxx/* src/operator/
make -j
cd python
python3 setup.py install

Compiler (gcc/clang/mingw/visual studio):

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

19c501680183237d52a862e6ae1dc4ddc296305b

Build config:
(Paste the content of config.mk, or the build command.)

USE_OPENCV = 0
USE_BLAS = openblas
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
USE_NCCL = 1
USE_DIST_KVSTORE = 1

## What have you tried to solve it?

1. `make clean_all` doesn't help 
2. ldd libmxnet.so
        linux-vdso.so.1 =>  (0x00007ffc34baa000)
        libachk.so => /lib/libachk.so (0x00007f4ce319a000)
        libcudart.so.9.0 => /home/longren/cuda/lib64/libcudart.so.9.0 (0x00007f4ce2f2d000)
        libcublas.so.9.0 => /home/longren/cuda/lib64/libcublas.so.9.0 (0x00007f4cdfaf7000)
        libcurand.so.9.0 => /home/longren/cuda/lib64/libcurand.so.9.0 (0x00007f4cdbb93000)
        libcusolver.so.9.0 => /home/longren/cuda/lib64/libcusolver.so.9.0 (0x00007f4cd6f98000)
        libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007f4cd4f04000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4cd4cfc000)
        libcudnn.so.7 => /home/longren/cuda/lib64/libcudnn.so.7 (0x00007f4cc29c3000)
        libcufft.so.9.0 => /home/longren/cuda/lib64/libcufft.so.9.0 (0x00007f4cba922000)
        libnccl.so.2 => /home/longren/cuda/lib64/libnccl.so.2 (0x00007f4cb5c1f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4cb589d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4cb5594000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f4cb5372000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4cb515c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4cb4f3f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4cb4b75000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4cf5ace000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4cb4971000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f4cb4646000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f4cb4407000)

**Comment by TaoLv** [comment]
@winstywang Can you help? Looks like a SimpleDet issue?

**Comment by roadcode** [comment]
using the [SimpleDet docker images](https://hub.docker.com/r/rogerchen/simpledet) , the problem has been solved

**Comment by Baby47** [comment]
Hi,@roadcode,
I meet the same problem with you, the error occurs like this:
/usr/local/lib/python3.5/dist-packages/mxnet-1.3.1-py3.5.egg/mxnet/libmxnet.so: undefined symbol: _Z9rleDecodePK3RLEPhm
This means i cannot import mxnet in Python3.5, but it can be imported in python2.7, Have you tried it in python 2.7? Maybe some libraries are tangled?

**Comment by dreadlord1984** [comment]
I meet the same error, solved by using the cocoapi code (https://github.com/RogerChern/cocoapi). Must use this version cocoapi when you build mxnet!!!

**Comment by roadcode** [comment]
@Baby47 i just copy the libmxnet.so file from SimpleDet docker images to solve this problem
