### ISSUE TITLE
Predict of mx.mod.Module api problem 2

### ISSUE THREAD

**Issue by Ian8888** [apache/incubator-mxnet#14486]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description

I have the question about the predict result.
When I make the inference program, I must know the model accuracy about image classification.
In my job, I have the two classification(0 or 1 labels).

So, I use the im2rec tool to make the .rec and .lst file.

> 39	1.000000	1/CenterOrg1_000_2_B_b04dfe80-d9f5-4928-9ac0-550fc5d7688a_ScanImgORG.jpg
> 24	1.000000	1/CenterOrg1_000_2_A_16e83b7c-9daf-4393-9a62-41a2a65125ce_ScanImgORG.jpg
> 28	1.000000	1/CenterOrg1_000_2_A_88d71f72-9858-41f3-bd70-8b12a40f009d_ScanImgORG.jpg
> 30	1.000000	1/CenterOrg1_000_2_A_ec1ed52c-c8ea-4cae-967c-25de87720416_ScanImgORG.jpg
> 21	1.000000	1/CenterOrg1_000_1_B_020e5e40-2611-4548-ae57-78da77ddcbca_ScanImgORG.jpg
> 10	0.000000	0/CenterOrg0_0_155_B_ebea1c1c-560f-4512-8ce2-58c9c8fbd7fa_ScanImgORG.jpg
> 34	1.000000	1/CenterOrg1_000_2_B_6cb8cdd4-4345-488b-a195-1c1b3692acb0_ScanImgORG.jpg 

and, use mx.image.ImageIter api to catch the data.
Then, I compare the data.label and predict result label to calculate acc.
And I run the same code in every times, but the acc is not same.

> Infernce Accuracy: 0.45
> Infernce Accuracy: 0.5
> Infernce Accuracy: 0.475

So, I gusset the predict api catch the image data that wasn't the same order with the ImageIter.

How can I solve the problem to calculate the Infernce Accuracy?

**Comment by zachgk** [comment]
@Ian8888, where are you getting the model you are using from? Is it downloaded as symbol and param files or are you training it yourself as part of the code you are running?

If possible, can you share the code that you are running?

@mxnet-label-bot add [Module, Pending Requester Info]
