### ISSUE TITLE
RandomResizedCrop produces wrong aspect ratios.

### ISSUE THREAD

**Issue by mzient** [apache/incubator-mxnet#14505]
RandomResizedCrop randomly swaps with/height which produces out-of-bounds aspect ratios if the ends of the aspect ratio range are not reciprocals. When swapping is removed, then the aspect ratio is skewed. The solution is to use uniform distribution on a logarithmic scale. See https://github.com/pytorch/vision/pull/799

**Comment by zachgk** [comment]
Thank you for submitting the issue! I'm labeling it so the MXNet community members can help resolve it.

@mxnet-label-bot add [Gluon, Data-loading, Bug, Call for Contribution]

**Comment by abhinavs95** [comment]
@mzient fix in #14585. Thank you for your solution.
