### ISSUE TITLE
CUDA 10.1 support

### ISSUE THREAD

**Issue by PistonY** [apache/incubator-mxnet#14514]
I use CUDA 10.1 with mxnet-cu100mkl
But I got this issus
```
Traceback (most recent call last):
  File "/home/piston/PycharmProjects/NASNet-gluon/model/nasnet.py", line 5, in <module>
    from model.basic_block import *
  File "/home/piston/PycharmProjects/NASNet-gluon/model/basic_block.py", line 6, in <module>
    from mxnet.gluon import nn
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```

**Comment by vdantu** [comment]
@mxnet-label-bot add [CUDA, Question]

@PistonY : Is CUDA in your LD_LIBRARY_PATH? 

```
export LD_LIBRARY_PATH=</path/to/cuda/ib64>:$LD_LIBRARY_PATH
```

**Comment by haojin2** [comment]
I think the problem is that MXNet is looking for CUDA 10.0: `OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory` since you installed the cu100mkl version... You either have to build from source or downgrade your CUDA version to 10.0 to use this wheel for now. Please let me know if you have further questions, thanks!

**Comment by PistonY** [comment]
@vdantu Yes.
@haojin2 Do you have plans to release mxnet-cu101mkl?
If you don't I will build from source.

**Comment by haojin2** [comment]
@PistonY Well in short term (like within 2 or 3 days) no, but I'll try to contact related persons on this issue and hopefully we can provide that in the near future. For now please go ahead and build from source, sorry for the inconvenience!

**Comment by haojin2** [comment]
@PistonY Please also let us know if you run into problems when building from source. I actually tried building with CUDA 10.1 + CuDNN 7.5 myself a few days ago and it worked for me.

**Comment by PistonY** [comment]
OK,I will.
Thanks for your help.

**Comment by XiaXuehai** [comment]
I got the same error.I installed mxnet:`pip install mxnet-cu100`.
It runs well in terminal,but got the error in pycharm when` import mxnet as nx`

**Comment by Aaronreb** [comment]
> @PistonY Please also let us know if you run into problems when building from source. I actually tried building with CUDA 10.1 + CuDNN 7.5 myself a few days ago and it worked for me.

Hi,
Can you help me build from source, since iam having cuda 10.1
