### ISSUE TITLE
problem launching on a lsf job submission system

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#1451]
Hi All,

I was able to launch the servers and workers as lsf jobs..However, I am not sure if they are connecting back to the scheduler process. Asking this because I see node ids as 0 for the two workers I launched. I am suspecting that the scheduler will assign the ids for these workers and they ought to be 0, 1.

However, they run to completion.. This is where I am getting confused. Shouldn;t the workers connect to scheduler to get the workloads? Or do they independently choose on their own if they cant connect to scheduler?

It will be great help if you can outline the broad steps that occur to help me debug where the problem may be

amithr

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
