### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [apache/incubator-mxnet#14580]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [KVStoreDist::RunServer](https://github.com/apache/incubator-mxnet/blob/992c3c0dd90c0723de6934e826a49bad6569eeac/src/kvstore/kvstore_dist.h#L130 "KVStoreDist::RunServer function")
- [MNISTIter](https://github.com/apache/incubator-mxnet/blob/992c3c0dd90c0723de6934e826a49bad6569eeac/src/io/iter_mnist.cc#L86 "Destructor for MNISTIter")
- [Predictor](https://github.com/apache/incubator-mxnet/blob/f1c063ebc017d175bd8f6f4d5027f8e178388c58/cpp-package/example/inference/inception_inference.cpp#L333 "Destructor for Predictor")

**Comment by vdantu** [comment]
@mxnet-label-bot add [good first issue, c++]
