### ISSUE TITLE
Install page history broken

### ISSUE THREAD

**Issue by zachgk** [apache/incubator-mxnet#14583]
## Description
On the website install page, there are buttons to select the installation configuration. When you click those buttons, it changes your browser history. But, if you press the browser back button, it won't change the displayed contents or update the page to the previous configuration. For the same reason, it does not react to the forward button as well.

**Comment by zachgk** [comment]
@mxnet-label-bot add [Website, Bug]

**Comment by aaronmarkham** [comment]
@zachgk Is this still an issue on the new site?

**Comment by zachgk** [comment]
@aaronmarkham This issue is still there. To reproduce, 

1. go to the installation docs on the get_started page. 
2. Randomly click on any of the buttons. Note that it changes the url path to index.html which is also wrong.
3. If you press the browser back button, it doesn't do anything. If you press it repeatedly, it only takes effect if you press it more than the number of times you changed the installation options.


You can see the relevant code [here](https://github.com/apache/incubator-mxnet/blob/master/docs/static_site/src/assets/js/options.js). There are two ways to resolve this problem:
1. We simply don't use the [history api](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and delete all occurrences of history.pushState. Then, the back button will simply leave the get_started page.
2. We handle the history `popstate` event so that presses to the back (and I believe forward) button are handled and will switch to the previously selected options. There may be other things to fix to get this working as well (especially due to the new site).

**Comment by aaronmarkham** [comment]
Sheng fixed this on the new site.

**Comment by zachgk** [comment]
I think Sheng fixed a different problem. I just checked and this problem still occurs

**Comment by ys2843** [comment]
@aaronmarkham This bug is still reproducible on new website, can I work on this?

**Comment by ys2843** [comment]
@aaronmarkham This issue was resolved. We can close it.

**Comment by zachgk** [comment]
Thanks @ys2843. Fixed in #18182
