### ISSUE TITLE
Inconsistent naming of pow/power between mx.symbol and mx.nd

### ISSUE THREAD

**Issue by YutingZhang** [apache/incubator-mxnet#14602]
`mx.nd.pow` and `mx.symbol.power` are named inconsistently. As a result, in a HybridBlock, one cannot do `F.pow` or `F.powerl` directly.

**Comment by haojin2** [comment]
It's indeed a problem... To ensure backward compatibility I'll add both `nd.power` and `sym.pow`. How do you like such a fix?

**Comment by YutingZhang** [comment]
@haojin2 That'll be perfect! Thanks!

**Comment by haojin2** [comment]
@YutingZhang WIP, will let you know when the PR is out, should be within today.

**Comment by haojin2** [comment]
@YutingZhang  Fix in #14606

**Comment by abhinavs95** [comment]
@mxnet-label-bot update [Bug, operator]

**Comment by haojin2** [comment]
@YutingZhang Fix merged. Please let me know if the latest master solves your issue.

**Comment by YutingZhang** [comment]
Thanks! @haojin2
