### ISSUE TITLE
Consistent crash on CI test Python3: TensorRT GPU

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#14618]
This test is failed at:
```
===========================================

Model: cifar_resnet20_v1

===========================================

*** Running inference using pure MXNet ***
```

Related CI runs:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/master/496/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14575/3/pipeline

Error message:
```
[2019-04-04 17:21:17   ERROR] Cuda initialization failure with error 35. Please check cuda installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html.

terminate called after throwing an instance of 'std::runtime_error'
```

**Comment by larroy** [comment]
@KellenSunderland

**Comment by KellenSunderland** [comment]
Having a look.  After a first quick glance it seems we're not yet hitting TensorRT code.  Could be a TRT specific environment problem.

**Comment by KellenSunderland** [comment]
Looks like this is an old failure.  Closing as it was addressed in April.
