### ISSUE TITLE
mx.sym.contrib.MultiProposal produces all the same outputs

### ISSUE THREAD

**Issue by pilhoon** [apache/incubator-mxnet#14624]
## Description
[mx.sym.contrib.MultiProposal](https://mxnet.incubator.apache.org/api/python/symbol/contrib.html#mxnet.symbol.contrib.MultiProposal) produces all the same outputs. It’s expected that various rois extracted by this method.

## Environment info (Required)

----------Python Info----------
Version      : 3.7.3
Compiler     : GCC 7.3.0
Build        : ('default', 'Mar 27 2019 22:11:17')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.0.3
Directory    : /home/x/anaconda3/lib/python3.7/site-packages/pip
----------MXNet Info-----------
Version      : 1.4.0
Directory    : /home/x/anaconda3/lib/python3.7/site-packages/mxnet
Commit Hash   : a03d59ed867ba334d78d61246a1090cd1868f5da
----------System Info----------
Platform     : Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
system       : Linux
node         : ***
release      : 3.10.0-693.21.1.el7.x86_64
version      : #1 SMP Wed Mar 7 19:03:37 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               1200.000
CPU max MHz:           2201.0000
CPU min MHz:           1200.0000
BogoMIPS:              4399.74
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
NUMA node1 CPU(s):     10-19
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_pt spec_ctrl ibpb_support tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0009 sec, LOAD: 0.8751 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1852 sec, LOAD: 0.9262 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1460 sec, LOAD: 0.7327 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1050 sec, LOAD: 0.2781 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0372 sec, LOAD: 1.2177 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0046 sec, LOAD: 0.0518 sec.

## Package used (Python/R/Scala/Julia):
python 3.7

## Minimum reproducible example
```python
import mxnet as mx
from mxnet import gluon, nd

prob = mx.sym.var('prob')
pred = mx.sym.var('pred')
im_info = mx.sym.var('im_info')
feature_stride = 100
s = (1,3)
r = (0.5,2)
num_anchors = len(s)*len(r)
rois = mx.sym.contrib.MultiProposal(cls_prob=prob,
                                    bbox_pred=pred,
                                    im_info=im_info,
                                    feature_stride=feature_stride,
                                    scales=s,
                                    ratios=r)
net = gluon.SymbolBlock(inputs=[prob, pred, im_info], outputs=[rois])
net.initialize()

w=5 # feature map widtha
h=4 # feature map height
prob = nd.random.uniform(0,1,(num_anchors,h,w))
prob = nd.expand_dims(nd.concat(prob, 1-prob, dim=0), axis=0)
pred = nd.random.uniform(10,400,(1,4*num_anchors,h,w))
im_info = nd.array([[3,h*feature_stride,w*feature_stride]])

a = net(prob, pred, im_info)
print(a)
```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. run the above code

## What have you tried to solve it?

1. view cpp source
2. run this on multiple machines

**Comment by wkcn** [comment]
Since the input is invalid.

I tried to use MultiPropsosal in Faster RCNN, and it worked.
