### ISSUE TITLE
CI Failure: R CPU

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#14649]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14606/4/pipeline/248
and 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14606/4/pipeline/249
```
The downloaded source packages are in
	'/tmp/Rtmp9NpgwT/downloaded_packages'
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'roxygen2'
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cloud.r-project.org/')); install_deps(pkg='R-package', dependencies = TRUE)"
Error in match.arg(upgrade, c("ask", "always", "never")) : 
  'arg' must be of length 1
Calls: install_deps ... upgradable_packages -> resolve_upgrade -> match.arg
Execution halted
Makefile:621: recipe for target 'rpkg' failed
make: *** [rpkg] Error 1
```

**Comment by zachgk** [comment]
This seems to completely break the CI. Here are some more errors
- https://github.com/apache/incubator-mxnet/pull/14647 with http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14647/1/pipeline and http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14647/1/pipeline
- https://github.com/apache/incubator-mxnet/pull/14627 with http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14627/6/pipeline and http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14627/7/pipeline
- https://github.com/apache/incubator-mxnet/pull/14545 with http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14545/8/pipeline and http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14545/8/pipeline

But, this seems to have affected every PR that has gone through the CI in the last 9 hours

**Comment by lanking520** [comment]
Some stackoverflow stuff:
https://stackoverflow.com/questions/55208794/trouble-installing-r-packages-with-devtools-on-travis

**Comment by lanking520** [comment]
Update: The author of R remote seemed to update their cron package. Please try to clean the cache on CI and build again: https://github.com/r-lib/devtools/issues/2020

**Comment by lanking520** [comment]
The problem should resolve itself, no further action needed. Please restart the CI and  feel free to close this issue if you are not facing this problems.

**Comment by lanking520** [comment]
Close this issue for now since there is no forseen problems in CI. Please feel free to reopen if you are still facing the problems
