### ISSUE TITLE
`mx.gluon.data.DataLoader` is slow when the size of batch is large

### ISSUE THREAD

**Issue by wkcn** [apache/incubator-mxnet#14648]
Hi, there.

I found `mx.gluon.data.DataLoader` is slow when the size of batch is large, since it calls `pickle.load` in `__next__` method of `_MultiWorkerIter` class. [[Code]](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/dataloader.py#L450)

I will upload the re-procedure code.

**Comment by kohillyang** [comment]
Did you try thread_pool=True instead? Sometimes using thread pool is faster than using multi-processing pool, as the pickling process is escaped.

**Comment by wkcn** [comment]
@kohillyang Thank you! I will try it.

**Comment by wkcn** [comment]
Close it since I found the bottleneck of performance is the release of NDArray Object.
