### ISSUE TITLE
Error with NDArray.Reshape

### ISSUE THREAD

**Issue by FAFACHR** [apache/incubator-mxnet#14663]
Thank you for this useful framework, I'm new in this field and I'm trying to work on computer vision stuff so I'm using gluoncv to work on instance segmentation but while I'm doing the training with 
coco pretrained weights on my own dataset and my own classes (I did the training using "mask_rcnn_resnet50_v1b_coco" and I used the reset_classes to reset my classes in gluoncv). I got an exception : "mxnet.base.MXNetError: [12:00:50] src/ndarray/ndarray.cc:253: Check failed: shape_.Size() == shape.Size() (2007040 vs. 50176) NDArray.Reshape: target shape must have the same size as current shape when recording with autograd " this error is raised by MXNetError.
Anyone have a solution ?

**Comment by vrakesh** [comment]
Hi @FAFACHR , thank you for posting the question to the community,requesting to share a reproducible script , so that we can look into what's causing the failure and answer your question.

@mxnet-label-bot add [Question, Pending requester info]

**Comment by FAFACHR** [comment]
Thank you so much, I posted my issue on gluoncv github and we solve it. If anyone wants to see the solution it is Issue #716 on gluoncv github

**Comment by FAFACHR** [comment]
Thank you so much, I posted my issue on gluoncv github and we solve it. If anyone wants to see the solution it is Issue dmlc/gluon-cv#716 on gluoncv github
