### ISSUE TITLE
Why the official website of mxnet has nothing about mxnet-cu100

### ISSUE THREAD

**Issue by LittleFatHero** [apache/incubator-mxnet#14689]
I can use the following command to install the mxnet version which support cuda 10:    
_**pip install mxnet-cu100**_
why the official website of mxnet has nothing about mxnet-cu100?

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Question, installation]

**Comment by aaronmarkham** [comment]
It has been added in the chart here:
https://mxnet.incubator.apache.org/versions/master/install/index.html?platform=MacOS&language=Python&processor=CPU
