### ISSUE TITLE
src/operator/rnn.cc:254:30: error: ‘kCuDNNDropoutDesc’ is not a member of ‘mxnet::ResourceRequest’

### ISSUE THREAD

**Issue by Marcovaldong** [apache/incubator-mxnet#14701]
CentOS 7
CUDA8.0 + CUDNN6.0.21

when I run 'make -j16', then got the current error and I cannot find anything about it. 

g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/disk2/dongsq/asr/mxnet/3rdparty/mshadow/ -I/disk2/dongsq/asr/mxnet/3rdparty/dmlc-core/include -fPIC -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/nnvm/include -I/disk2/dongsq/asr/mxnet/3rdparty/dlpack/include -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_MKLDNN=1 -DUSE_MKL=1 -I/disk2/dongsq/asr/mxnet/src/operator/nn/mkldnn/ -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/disk2/dongsq/environments/OpenCV-3.4.6/include/opencv -I/disk2/dongsq/environments/OpenCV-3.4.6/include   -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/disk2/dongsq/asr/mxnet/3rdparty/nvidia_cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/convolution_v1.cc -o build/src/operator/convolution_v1.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/disk2/dongsq/asr/mxnet/3rdparty/mshadow/ -I/disk2/dongsq/asr/mxnet/3rdparty/dmlc-core/include -fPIC -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/nnvm/include -I/disk2/dongsq/asr/mxnet/3rdparty/dlpack/include -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_MKLDNN=1 -DUSE_MKL=1 -I/disk2/dongsq/asr/mxnet/src/operator/nn/mkldnn/ -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/disk2/dongsq/environments/OpenCV-3.4.6/include/opencv -I/disk2/dongsq/environments/OpenCV-3.4.6/include   -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/disk2/dongsq/asr/mxnet/3rdparty/nvidia_cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/spatial_transformer.cc -o build/src/operator/spatial_transformer.o
src/operator/rnn.cc: In lambda function:
src/operator/rnn.cc:254:30: error: ‘kCuDNNDropoutDesc’ is not a member of ‘mxnet::ResourceRequest’
         request.emplace_back(ResourceRequest::kCuDNNDropoutDesc);
                              ^

**Comment by Marcovaldong** [comment]
After checking the (source code)[https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/resource.h#L47], it seems that the master branch of MxNet only supports CuDNN>=7. Is there such problem? @szha

**Comment by szha** [comment]
@Marcovaldong yes, prior versions of cudnn don't support restoring dropout state from a used dropout state space.

**Comment by szha** [comment]
@Marcovaldong we can fix this at the cost of high overhead as we did before, which is by creating dropout descriptor per forward run. However, for the best performance I'd still recommend that you upgrade to cudnn 7 to benefit from the shared dropout state refactor. Being able to reuse the dropout state would save you non-trivial amount of time.

**Comment by frankfliu** [comment]
@mxnet-label-bot add [question, build, cuda]

**Comment by Marcovaldong** [comment]
@szha It needs time to upgrade cuda and cudnn, I will do it when I am leisure. I git clone wource code frm v1.1.0 branch and I installed it successfully. Thanks for your reply.
