### ISSUE TITLE
3rdparty/sparse-matrix can't work under windows cmake. 

### ISSUE THREAD

**Issue by yinghu5** [apache/incubator-mxnet#14730]
Target
We are working on redesign the build logic of MXNET with MKL/MKLDNN, with @pengzhao-intel @TaoLv @@juliusshufan,

when enable MKL and MKLDNN in build logic,  the build with 3rdparty/sparse-matrix  failed as it haven't windows cmake support. 

Reproduce step: 

C:\mxnet_4\incubator-mxnet\build>cmake -G "Visual Studio 14 Win64" .. -DUSE_CUDA=0 -DUSE_CUDNN=0  -DUSE_OPENCV=1 -DUSE_OPENMP=1 -DUSE_BLAS=mkl -DUSE_LAPACK=1 -DUSE_PROFILER=1 -DUSE_DIST_KVSTORE=0  -DUSE_MKL_IF_AVAILABLE=1 -DUSE_MKLDNN=1  -DCMAKE_BUILD_TYPE=Release -DMKL_ROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.3.203\windows\mkl"

switch on this : 
#if (MSHADOW_USE_MKL == 1)
#include "sparse_matrix.h"
#endif

msbuild mxnet.sln /p:Configuration=Release;Platform=x64 /maxcpucount
 c:\mxnet_4\incubator-mxnet\src\operator\tensor\./dot-inl.h(42): fatal error C1083: Cannot open include file: 'sparse_matrix
       .h': No such file or directory (compiling source file C:\mxnet_4\incubator-mxnet\src\operator\tensor\dot.cc) [C:\mxnet_4\incu
       bator-mxnet\build\mxnet.vcxproj]

Please help to consider to add it  @triplekings  and @eric-haibin-lin.  thanks

**Comment by frankfliu** [comment]
@mxnet-label-bot add [build, windows]

**Comment by triplekings** [comment]
Thanks. I'll check it

**Comment by TaoLv** [comment]
Closed via #14806.
