### ISSUE TITLE
upcasting accumulation type in norm increases loss/Perplexity 

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#14760]
While fixing an issue described [here](https://github.com/apache/incubator-mxnet/issues/14722). 
I applied the changes from master and found that the change from #14616 follows the same pattern as the softmax change in #14098 and increases the loss and hence perpelity from 126.66 to 135, without this change and the fix to softmax #14759, validation perplexity comes back to 126.66

Details on how to test are provided in #14722 

@haojin2 @eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
What about adding env var like MXNET_ENFORCE_SAFE_ACCUMULATION = 1 to trigger safe accumulation with higher precision on existing ops?

**Comment by nswamy** [comment]
If we have to do this for many operators it makes sense to control through a environment variable like you are suggesting. how many operators need this change?

What i am puzzled about is why the loss goes up when the accumulation precision is increased.

**Comment by eric-haibin-lin** [comment]
We need this for softmax, log_softmax, norm and layernorm (coming soon).

@szha @ptrendx what do you guys think is the best way to handle this?

**Comment by anirudh2290** [comment]
Can we avoid adding another env variable ? We can accumulate only when dtype is set otherwise use the default behavior before this change was added. Also I understand FP16 inputs with accumulation in FP32 for softmax but does this also apply to FP32 inputs with accumulation in FP64. Will there be no accuracy loss ?

**Comment by eric-haibin-lin** [comment]
Should be fixed in #14830
