### ISSUE TITLE
how to run distributed mxnet training job by docker container

### ISSUE THREAD

**Issue by jokerwenxiao** [apache/incubator-mxnet#14763]
I tried to run a distributed training job with docker container.

I used the launch.py to run the examples/distributed_training/cifar10_dist.py in container, but i confused with hosts file.

command is as flow:
1. **run container in two hosts:** docker run -ti --net=host image:name bash 
2. **command in shell:** python launch.py -n -2 -s 2 --sync-dst-dir examples/distributed_training/ --launch ssh -H hosts "python examples/distributed_training/cifar10_dist.py"
3.**hosts file content:**
    host_ip1
    host_ip2

**than prompt for a password, The form is as follows:**
root@host_Ip1's password:root@host_Ip1's password:root@host_Ip2's password:root@host_Ip2's password:

I entered the appropriate host password, but the password check failed

**Comment by frankfliu** [comment]
@mxnet-label-bot add [docker, distributed, question]

**Comment by lanking520** [comment]
@eric-haibin-lin Could you please take a look if you have some context about it?

**Comment by Roshrini** [comment]
@jokerwenxiao I think you need to setup passwordless ssh for the communication between the hosts. Can you try to do it? https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/

**Comment by jokerwenxiao** [comment]
> @jokerwenxiao I think you need to setup passwordless ssh for the communication between the hosts. Can you try to do it? https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/

thanks! I solved the problem.

**Comment by jiinhui** [comment]
I   am  trying     to   do    distribute   training   by  mxnet.  But  I meet  the   problem  of   the  ssh   connecting   between  two   mechine.  Is   the  format  of   host_ip1        host_192.168.112.101  ?
