### ISSUE TITLE
ci/build.py time out

### ISSUE THREAD

**Issue by kwanking** [apache/incubator-mxnet#14787]
run ci/build.py, there is a error
build.py: 2019-04-24 15:20:08,193Z WARNING Exception: Command '['docker', 'pull', 'mxnetci/build.android_armv7']' timed out after 900 seconds, Retrying in 50 seconds

how let timeout be long?

**Comment by lanking520** [comment]
@kwanking what are you trying to do? This is the script for CI runs in MXNet.

**Comment by kwanking** [comment]
> @kwanking what are you trying to do? This is the script for CI runs in MXNet.

@lanking520 I want to get android-armv7 library and run python3 ./build.py -p android_armv7. and there is the error because my net speed in not quick.
