### ISSUE TITLE
Documentation of ToTensor shows wrong range

### ISSUE THREAD

**Issue by Flamefire** [apache/incubator-mxnet#14786]
As stated e.g. at https://beta.mxnet.io/api/gluon/_autogen/mxnet.gluon.data.vision.transforms.ToTensor.html#mxnet.gluon.data.vision.transforms.ToTensor the `ToTensor` transform is defined as

> Converts an image NDArray of shape (H x W x C) in the range [0, 255] to a float32 tensor NDArray of shape (C x H x W) in the range [0, 1).

However the implementation does not fulfil this. It converts the image into the range `[0,1]` (*including* 1). This is due to a scaling factor of `255` used which obviously converts a `255` input to an output of  `1`. See https://github.com/apache/incubator-mxnet/blob/0f63659be5070af218095a6a460427d2a1b67aba/src/operator/image/image_random-inl.h#L172

**Comment by stu1130** [comment]
@Flamefire Thanks for finding it out! Would you like to raise a PR to fix this? You only need to change this line  https://github.com/apache/incubator-mxnet/blob/2fd4720342f87be80f280176ffbecb8f37e49b73/python/mxnet/gluon/data/vision/transforms.py#L103

**Comment by Flamefire** [comment]
Sure: https://github.com/apache/incubator-mxnet/pull/14794
