### ISSUE TITLE
c++ and python inference give different result with params trained on python

### ISSUE THREAD

**Issue by hallazie** [apache/incubator-mxnet#14795]
## Description
I trained a shallow yolo-like model on python (dtype=float32), and got different results while running inference with c++ api (GetDType=0).

I visualize come output activation as follows:
[confidence activation with python and c++ api](https://github.com/hallazie/botrouting_cross_recognition/blob/master/dat/confs.png)

## Environment info (Required)
ubuntu 18.04 with mxnet 1.4.0 cpu build

## Build info (Required if built from source)

Compiler:
g++

MXNet commit hash:
b3b952f9d5490ee2707209ab866e6c3f094e2046

## Minimum reproducible example
I modified the code from [the cpp-package inference example](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/inference/inception_inference.cpp) and loaded with my python trained symbol.json and .params file.

**Comment by lanking520** [comment]
@hallazie Could you please provide the code you run with? 
@leleamol here to see if you can help

**Comment by leleamol** [comment]
@hallazie 
Can you please provide some details such as:
1. Modifications to the inference example. 
2. The output you were expecting
3. Details about the model you have trained, etc

It will help us answer the question.
Thanks

**Comment by leleamol** [comment]
@mxnet-label-bot add ["Pending Requester Info"]

**Comment by lanking520** [comment]
@hallazie Close it for now since the question has been answered. Please feel free to reopen if the suggest solution did not fix your problem.
