### ISSUE TITLE
mxnet-cu92mkl can't be installed on Mac

### ISSUE THREAD

**Issue by arun-gupta** [apache/incubator-mxnet#14802]
Trying to install MXNet Model Server on Mac:

```
pip install mxnet-cu92mkl
```

And getting the error:

```
pip install mxnet-cu92mkl --user
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting mxnet-cu92mkl
  ERROR: Could not find a version that satisfies the requirement mxnet-cu92mkl (from versions: none)
ERROR: No matching distribution found for mxnet-cu92mkl
```

A warning needs to be added that CUDA versions of MXNet can't be installed on Mac.

**Comment by lanking520** [comment]
Hi @arun-gupta ,this is only available on Linux machine, currently we do not support Mac with GPU

**Comment by arun-gupta** [comment]
@lanking520 that's not clear from the docs

**Comment by lanking520** [comment]
@aaronmarkham do we have docs direct to that?

**Comment by marcoabreu** [comment]
Our documentation at https://mxnet.incubator.apache.org/versions/master/install/index.html?platform=MacOS&language=Python&processor=GPU states that the package is not available and has to be compiled manually from source

**Comment by aaronmarkham** [comment]
I think we can close this. However, if we don't have one already, we should have an issue/feature tracked for creating macOS pip packages that work with GPUs you can get now.

@arun-gupta What kind of GPU do you have with your Mac?

**Comment by arun-gupta** [comment]
No GPU on the Mac

**Comment by haojin2** [comment]
@arun-gupta If you have no GPU on your mac then none of the GPU wheels will work for you. Please try out `pip install mxnet-mkl`, I just tried on my own mac and it works. If this solves your problem then please close the issue, otherwise feel free to ask! Thanks!

**Comment by aaronmarkham** [comment]
Closing this as we have notifications in the docs about limitations for mac/gpu and how to install MXNet if you have a GPU.
Please feel free to reopen if you have suggestions for more places it should be mentioned.
