### ISSUE TITLE
mxnet.ndarray.contrib.requantize introduces too much error

### ISSUE THREAD

**Issue by shoubhik** [apache/incubator-mxnet#14801]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io  -> https://discuss.mxnet.io/t/mxnet-ndarray-contrib-requantize-introduces-too-much-error/3843

## Description
Consider these two examples

```
from mxnet.ndarray.contrib import quantize, requantize, dequantize
from mxnet import random
```

```
# Dequantizing directly the quantization results
data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high, shape=data_shape).astype('float32')
print(data)
quantized_data, quantized_data_min, quantized_data_max  = quantize(data, data.min(), data.max())
dequantized_data = dequantize(quantized_data, quantized_data_min, quantized_data_max)
print(dequantized_data)
```

```
# output of quantization
[[ 18.81389    99.11418   124.69234   125.0991     60.75303  ]
 [ 95.70334    63.168705    0.5141094  81.21301    34.22389  ]
 [ 46.810246   52.132504   17.386335   54.384426  104.40895  ]
 [ 37.825912   24.110685   50.94381    64.93751    15.323439 ]
 [ 28.488262  124.54886    12.42625    51.5773    109.49832  ]]
<NDArray 5x5 @cpu(0)>
# output of dequantization
[[ 18.64222    99.09811   124.60851   125.0991     60.832504 ]
 [ 95.66402    63.285427    0.4905847  81.43706    34.34093  ]
 [ 46.605545   52.00198    17.170465   54.454903  104.494545 ]
 [ 37.77502    24.03865    51.02081    64.75718    15.208126 ]
 [ 28.453913  124.60851    12.264618   51.511395  109.40039  ]]
<NDArray 5x5 @cpu(0)>
```

Now consider the example of dequantization with requantization introduced after quantization

```
data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high, shape=data_shape).astype('float32')
print(data)

quantized_data, quantized_data_min, quantized_data_max  = quantize(data, data.min(), data.max())
requantized_data, requantized_data_min, requantized_data_max = requantize(
    quantized_data.astype('int32'), quantized_data_min, quantized_data_max)
dequantized_data = dequantize(requantized_data, requantized_data_min, requantized_data_max)
print(dequantized_data)
```

```
# output of quantization
[[ 72.289764  123.560776   43.637897  122.026     100.186844 ]
 [115.132545   52.244297   98.30401    45.62747    42.309433 ]
 [ 50.736362   10.299877   38.332523   51.719627   98.45291  ]
 [ 29.493734  117.629036   16.82593    41.31441     6.7852516]
 [121.01457    92.15048     1.7714465   1.4512868  67.750145 ]]
<NDArray 5x5 @cpu(0)>
# output of dequantization with requantization in between
[[8.5490710e-06 1.4672055e-05 5.1987595e-06 1.4556526e-05 1.1899383e-05]
 [1.3747831e-05 6.2385116e-06 1.1668327e-05 5.4298157e-06 4.9677037e-06]
 [6.0074553e-06 1.1552798e-06 4.5055917e-06 6.1229835e-06 1.1668327e-05]
 [3.4658397e-06 1.3978886e-05 1.9639758e-06 4.8521756e-06 8.0869592e-07]
 [1.4440999e-05 1.0975159e-05 2.3105598e-07 1.1552799e-07 8.0869595e-06]]
<NDArray 5x5 @cpu(0)>
```

As you can see, with the introduction of `mx.ndarray.contrib.requntize` produces wildly more error than should be acceptable. Am i doing something wrong here, or there is some issue with the implementation?

## Environment info (Required)

```
What to do:
1. Run the following code with the latest release to reproduce

data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high, shape=data_shape).astype('float32')
print(data)

quantized_data, quantized_data_min, quantized_data_max  = quantize(data, data.min(), data.max())
requantized_data, requantized_data_min, requantized_data_max = requantize(
    quantized_data.astype('int32'), quantized_data_min, quantized_data_max)

dequantized_data = dequantize(requantized_data, requantized_data_min, requantized_data_max)
print(dequantized_data)
```

Package used (Python/R/Scala/Julia):
(I'm using ...) Python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): gcc

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)
```
data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high, shape=data_shape).astype('float32')
print(data)

quantized_data, quantized_data_min, quantized_data_max  = quantize(data, data.min(), data.max())
requantized_data, requantized_data_min, requantized_data_max = requantize(
    quantized_data.astype('int32'), quantized_data_min, quantized_data_max)

dequantized_data = dequantize(requantized_data, requantized_data_min, requantized_data_max)
print(dequantized_data)
```
## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Run the above code in python terminal with mxnet installed

## What have you tried to solve it?

1. No idea yet.

**Comment by shoubhik** [comment]
To add more data  and another example

```
# original data
[[ 98.73077    86.53261    32.946667   22.652653   47.47427  ]
 [  8.872096   74.62515     1.230398*   34.64838   113.290306 ]
 [ 47.098305   16.950083   25.025894   98.95738    58.4017   ]
 [117.49576**     5.6657615  90.8277    101.57407    62.333965 ]
 [  9.773468   59.626286   65.89206   112.10408    38.964886 ]]
```

```
quantized_data, quantized_data_min, quantized_data_max  = quantize(data, data.min(), data.max())

print(quantized_data)
print(quantized_data_min)
print(quantized_data_max)
```

Produces
```
[[214 188  72  49 103]
 [ 19 162   3  75 246]
 [102  37  54 215 127]
 [255  12 197 220 135]
 [ 21 129 143 243  85]]
<NDArray 5x5 @cpu(0)>

[1.230398]  # The correct min
<NDArray 1 @cpu(0)>

[117.49576] # The correct max
<NDArray 1 @cpu(0)>
```

```
requantized_data, requantized_data_min, requantized_data_max = requantize(
    quantized_data.astype('int32'), quantized_data_min, quantized_data_max)

print(requantized_data)
print(requantized_data_min)
print(requantized_data_max)
```

Produces
```
[[107  94  36  24  51]
 [  9  81   1  37 123]
 [ 51  18  27 107  63]
 [127   6  98 110  67]
 [ 10  64  71 121  42]]
<NDArray 5x5 @cpu(0)>

[-1.39518725e-05] # The min and max are way too small it seems
<NDArray 1 @cpu(0)>

[1.39518725e-05] # The min and max are way too small it seems
<NDArray 1 @cpu(0)>
```

**Comment by pengzhao-intel** [comment]
@xinyu-intel @ZhennanQin

**Comment by ZhennanQin** [comment]
Hi @shoubhik, the problem of your case is,

```
requantized_data, requantized_data_min, requantized_data_max = requantize(
    quantized_data.astype('int32'), quantized_data_min, quantized_data_max)
```

For `requantize` op, its input `data_min` and `data_max` are not the same as the float32 min/max value before quantization.

So for your case, the expected `data_min` and `data_max` of requantize are,

```
data_min = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MIN_VALUE
data_max = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MAX_VALUE
```
Here INT8_MIN_VALUE is the minimum value of int8 type, thus is -128. INT8_MAX_VALUE is the maximum value of int8 type, thus is 127. INT32_MIN_VALUE and INT32_MAX_VALUE are in similar definitions.

**Comment by ZhennanQin** [comment]
Add the reason behind.  `requantize` is to convert int32 to int8. Its int32 input should come from fp32 to int32 `quantize` output , not a casting from `int8` to `int32`.

Consider the case all data are positive value, when converting fp32 to int32, `quantize` will try to map fp32_data_max to INT32_MAX_VALUE. But for casting  from `int8` to `int32`, fp32_data_max will map to  INT8_MAX_VALUE instead of INT32_MAX_VALUE, causing the output is much smaller than expected.

**Comment by pengzhao-intel** [comment]
> Hi @shoubhik, the problem of your case is,
> 
> ```
> requantized_data, requantized_data_min, requantized_data_max = requantize(
>     quantized_data.astype('int32'), quantized_data_min, quantized_data_max)
> ```
> For `requantize` op, its input `data_min` and `data_max` are not the same as the float32 min/max value before quantization.
> 
> So for your case, the expected `data_min` and `data_max` of requantize are,
> 
> ```
> data_min = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MIN_VALUE
> data_max = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MAX_VALUE
> ```
> Here INT8_MIN_VALUE is the minimum value of int8 type, thus is -128. INT8_MAX_VALUE is the maximum value of int8 type, thus is 127. INT32_MIN_VALUE and INT32_MAX_VALUE are in similar definitions.

Could we document this in anywhere?

**Comment by pengzhao-intel** [comment]
A right example as below:
```
import mxnet as mx
from mxnet.ndarray.contrib import quantize, requantize, dequantize
from mxnet import random

# Dequantizing directly the quantization results
data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high,
                            shape=data_shape).astype('float32')
print(data)
quantized_data, quantized_data_min, quantized_data_max  = quantize(data,
                                                                   data.min(),
                                                                   data.max())
dequantized_data = dequantize(quantized_data, quantized_data_min,
                              quantized_data_max)
print(dequantized_data)


data_shape = (5, 5)
data_low = 0.0
data_high = 127.0
data = mx.nd.random.uniform(low=data_low, high=data_high,
                            shape=data_shape).astype('float32')
print(data)

quantized_data, quantized_data_min, quantized_data_max  = quantize(data,
                                                                   data.min(),
                                                                   data.max())
#requantized_data, requantized_data_min, requantized_data_max = requantize(
#        quantized_data.astype('int32'), quantized_data_min,
#        quantized_data_max)
#dequantized_data = dequantize(requantized_data, requantized_data_min,
#                              requantized_data_max)
#print(dequantized_data)

INT8_MIN_VALUE = -128
INT8_MAX_VALUE = 127
INT32_MIN_VALUE = -2147483648
INT32_MAX_VALUE = 2147483647

data_min = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MIN_VALUE
data_max = (quantized_data_max - quantized_data_min) / (INT8_MAX_VALUE - INT8_MIN_VALUE) * INT32_MAX_VALUE

requantized_data, requantized_data_min, requantized_data_max = requantize(
        quantized_data.astype('int32'), data_min, data_max)

dequantized_data = dequantize(requantized_data, requantized_data_min,
                              requantized_data_max)
print(dequantized_data)
```
The output

> (base) [patric@mlt-skx091 quantization]$ python test.py
> 
> [[ 69.69932   75.29127   90.82905  107.22175   76.55095 ]
>  [108.95909   69.200165 107.60097   53.804157  79.19259 ]
>  [ 82.02855   48.81648   55.573574  37.786896 113.25517 ]
>  [  7.202548 122.38517   34.62735   48.69707   60.66347 ]
>  [100.54908  103.145424  67.169655  60.9571    72.141655]]
> <NDArray 5x5 @cpu(0)>
> 
> [[ 69.59157    75.35087    90.70901   107.02703    76.790695 ]
>  [108.9468     69.111626  107.50697    53.753487   79.19041  ]
>  [ 82.07005    48.954067   55.673256   37.915405  113.26627  ]
>  [  7.1991277 122.38517    34.555813   48.474125   60.47267  ]
>  [100.78779   103.1875     67.19186    60.952614   71.99128  ]]
> <NDArray 5x5 @cpu(0)>
> 
> [[ 49.88367   117.55077   106.182       9.021579   42.849316 ]
>  [ 11.06542    82.31783     2.5677366  46.766678  105.74272  ]
>  [121.55871    98.825905   17.824549  110.49155   110.50108  ]
>  [124.28453    60.14822   101.49314   101.71567    58.60788  ]
>  [ 66.10064    99.127205   86.217705   15.020851   91.52035  ]]
> <NDArray 5x5 @cpu(0)>
> 
> [[ 48.8784    115.007996  104.46559     8.6256     42.169598 ]
>  [ 10.542399   80.50559     1.9167999  46.003197  103.507195 ]
>  [118.84159    96.79839    17.2512    108.299194  108.299194 ]
>  [121.7168     58.4624     99.67359    99.67359    57.503998 ]
>  [ 65.171196   96.79839    84.339195   14.375999   90.08959  ]]
> <NDArray 5x5 @cpu(0)>

**Comment by pengzhao-intel** [comment]
cc @ZhuoweiSi to plan to add this info into the document.
