### ISSUE TITLE
Creating multi-label instances in RecordIO by Python interface?

### ISSUE THREAD

**Issue by erogol** [apache/incubator-mxnet#1480]
Is it possible to create multi-label instances by recordIO python interface? I tried these lines to do but it does not work when I give labels as a list. It works when I give a single label value like labels[0]

```
header = mx.recordio.IRHeader(0, labels, int(count_item), 0) # if I give labels[0] it works
s = mx.recordio.pack_img(header, img, quality=80, img_fmt='.jpg')
```

The error is : 

```
    113     """
    114     header = IRHeader(*header)
--> 115     s = struct.pack(_IRFormat, *header) + s
    116     return s
    117 

error: required argument is not a float
```

**Comment by piiswrong** [comment]
the extra labels are only stored in the .lst file, not in .rec

**Comment by kyocen** [comment]
@erogol do you solve this problem, I also meet this problem and have no idea.

**Comment by piiswrong** [comment]
labels can be a list now

**Comment by kyocen** [comment]
@piiswrong I made a .lst file with multi-label like  " integer_image_index \t label_1 \t label_2 \t label_3 \t label_4 \t path_to_image" by myself. when I use "im2rec.py --pack-label=True“” to creat a .rec file, the problem happen. error: required argument is not a float

**Comment by piiswrong** [comment]
You probably need to update mxnet

see if you can run mxnet/tests/python/unittest/test_recordio.py

**Comment by kyocen** [comment]
@piiswrong I solved this problem by update mxnet. Thank you.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
