### ISSUE TITLE
TypeError: object of type ‘NoneType’ has no len()

### ISSUE THREAD

**Issue by jasperDD** [apache/incubator-mxnet#14828]
Hi, please help me
i use im2rec.py
so when i do so
python Downloads/im2rec.py Downloads/test . --center-crop --resize 224 --pack-label

i get the error

opencv@opencv-virtual-machine:~$ python Downloads/im2rec.py Downloads/test . --center-crop --resize 224 --pack-label
Creating .rec file from /home/opencv/Downloads/test/dog.lst in /home/opencv/Downloads/test
multiprocessing not available, fall back to single threaded encoding
imread read blank (None) image for file: /home/opencv/./data/img/h_87.jpg
Traceback (most recent call last):
File “Downloads/im2rec.py”, line 386, in 
record.write_idx(item[0], s)
File “/home/opencv/.local/lib/python2.7/site-packages/mxnet/recordio.py”, line 285, in write_idx
self.write(buf)
File “/home/opencv/.local/lib/python2.7/site-packages/mxnet/recordio.py”, line 135, in write
ctypes.c_size_t(len(buf))))
TypeError: object of type ‘NoneType’ has no len()

What does it mean
here 87.jpg
https://images.guru/i/iPYR

**Comment by jasperDD** [comment]
i found error,  data folder was deleted from root catalog. and it could find my pictures

**Comment by lanking520** [comment]
@jasperDD Thanks for your Q and A. Could you please close this issue if you are no longer facing the same problem?

**Comment by haojin2** [comment]
Closing the issue now since the problem seems to be solved. @jasperDD Please feel free to re-open if you have further questions, thanks!
