### ISSUE TITLE
ci/build.py failed to build MXNet for Android_armv7

### ISSUE THREAD

**Issue by PhanTask** [apache/incubator-mxnet#14844]
## Description
Tried to build Android_armv7 using ci/build.py and failed.
I runned `sudo ./build.py -p android_armv7`
And the error showed as follows:
```
W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Environment info (Required)
OS: Ubuntu 18.04 64bit LTS
MXNet: 1.3.1
Python: 3.6
GPU: NVIDIA GTX1060 6G
CPU: i7-8750H (16G memory)

## What have you tried to solve it?

1. Changed mxnetci dockcross address in `Dockerfile.build.android_armv7`
Previously it is `FROM mxnetci/dockcross-linux-base:08212018`
Now it is `FROM mxnetcipinned/dockcross-base:11262018`
2. Set `--docker-registry` argument in `ci/build.py` to 'mxnetcipinned'
3. Created `/etc/docter/daemon.json` and restarted the docker service
```
{
"registry-mirrors": ["https://registry.docker-cn.com"]
}
```
4. Used proxy(shadowsocks + proxychains4). BUt it seems that it has nothing to do with my network connection?

## Complete building log
```
jinmengrao@jinmengrao-OMEN-by-HP-Laptop-15-dc0xxx:~/gitRepo/apache-mxnet-src-1.3.1-incubating/ci$ sudo ./build.py -p android_armv7
build.py: 2019-04-30 15:43:50,514 Building container tagged 'mxnetcipinned/build.android_armv7' with docker
build.py: 2019-04-30 15:43:50,514 1 out of 1 tries to build the docker image.
build.py: 2019-04-30 15:43:50,514 Running command: 'docker build -f docker/Dockerfile.build.android_armv7 --build-arg USER_ID=0 --build-arg GROUP_ID=0 --cache-from mxnetcipinned/build.android_armv7 -t mxnetcipinned/build.android_armv7 docker'
Sending build context to Docker daemon  156.2kB
Step 1/34 : FROM mxnetcipinned/dockcross-base:11262018
 ---> 94f0363cdb71
Step 2/34 : MAINTAINER Pedro Larroy "pllarroy@amazon.com"
 ---> Running in 6d2c98f8d584
Removing intermediate container 6d2c98f8d584
 ---> cab83d01644a
Step 3/34 : RUN apt-get update && apt-get install -y   unzip
 ---> Running in 234473d03ea3
Ign http://ftp.debian.org jessie-backports InRelease
Ign http://cdn-fastly.deb.debian.org jessie InRelease
Ign http://ftp.debian.org jessie-backports Release.gpg
Ign http://ftp.debian.org jessie-backports Release
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Get:1 http://cdn-fastly.deb.debian.org jessie-updates InRelease [7340 B]
Get:2 http://cdn-fastly.deb.debian.org jessie/updates InRelease [44.9 kB]
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  404  Not Found
Hit http://cdn-fastly.deb.debian.org jessie Release.gpg
Hit http://cdn-fastly.deb.debian.org jessie Release
Get:3 http://cdn-fastly.deb.debian.org jessie/updates/main amd64 Packages [829 kB]



Get:4 http://cdn-fastly.deb.debian.org jessie/main amd64 Packages [9098 kB]
Get:5 http://cdn-fastly.deb.debian.org jessie/contrib amd64 Packages [59.2 kB]
Get:6 http://cdn-fastly.deb.debian.org jessie/non-free amd64 Packages [101 kB]
Fetched 10.1 MB in 9min 38s (17.5 kB/s)
W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y   unzip' returned a non-zero code: 100
build.py: 2019-04-30 15:53:35,677 Failed to build docker image
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./build.py", line 394, in <module>
    sys.exit(main())
  File "./build.py", line 315, in main
    build_docker(platform, docker_binary, registry=args.docker_registry, num_retries=num_docker_build_retires)
  File "./build.py", line 118, in build_docker
    logging.exception('Exception during build of docker image', saved_exception)
Message: 'Exception during build of docker image'
Arguments: (CalledProcessError(100, ['docker', 'build', '-f', 'docker/Dockerfile.build.android_armv7', '--build-arg', 'USER_ID=0', '--build-arg', 'GROUP_ID=0', '--cache-from', 'mxnetcipinned/build.android_armv7', '-t', 'mxnetcipinned/build.android_armv7', 'docker']),)
build.py: 2019-04-30 15:53:35,678 Failed to build the docker image, aborting...

```

I am wondering if there is anyone who can reproduce this error, or there is just something wrong in my network connection (e.g. GFW)?

**Comment by lanking520** [comment]
@larroy Could you please take a look?

**Comment by larroy** [comment]
seems like a network issue?  Works for me:

```
lc.a /usr/arm-linux-androideabi/lib/libopenblas.a && :
build.py: 2019-04-30 19:33:06,432Z INFO Waiting for status of container 38451c89318e for 600 s.
build.py: 2019-04-30 19:33:07,522Z INFO Container exit status: {'Error': None, 'StatusCode': 0}
build.py: 2019-04-30 19:33:07,522Z INFO Container exited with success 👍
build.py: 2019-04-30 19:33:07,522Z INFO Stopping container: 38451c89318e
build.py: 2019-04-30 19:33:07,523Z INFO Removing container: 38451c89318e

real    7m7.247s
user    0m0.506s
sys     0m0.254s
piotr@ip-172-31-63-171:0:~/mxnet_other (master)+$ time ci/build.py -p android_armv7


Im at a386644f2cd2a7b8ef553c518a9558e11923b834  in master
```

**Comment by PhanTask** [comment]
@larroy
Thank you. After adding `RUN sed -i "s/jessie/stretch/g" /etc/apt/sources.list` it works. I think it is indeed a network issue.

**Comment by bykim555** [comment]
1. Tried to build Android_armv7 using ci/build.py and sucess. ndk17, api 24
2.  Use Android Studio. 
Android.mk, 
include $(CLEAR_VARS)
LOCAL_MODULE := mxnet_inference          
LOCAL_SRC_FILES := $(LOCAL_PATH)/libs/libmxnet.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/mxnet        
include $(PREBUILT_SHARED_LIBRARY) 
...
LOCAL_SHARED_LIBRARIES += mxnet_inference
include $(BUILD_SHARED_LIBRARY)           

Application.mk
APP_ABI := armeabi-v7a
APP_PLATFORM := android-24
APP_STL := c++_static
NDK_TOOLCHAIN_VERSION := clang
APP_BUILD_SCRIPT := Android.mk

build.gradle
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.tistory.webnautes.useopencvwithndk_build"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

       // ndk {
       //     abiFilters "armeabi-v7a"
       // }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
   }

    packagingOptions {
       // pickFirst 'lib/arm64-v8a/*'
        pickFirst 'lib/armeabi-v7a/*'
       // pickFirst 'lib/x86/*'
       // pickFirst 'lib/x86_64/*'
    }
}

error showed as follows:
#==================
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tistory.webnautes.useopencvwithndk_build, PID: 12657
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/app/com.tistory.webnautes.useopencvwithndk_build-2/lib/arm/libmxnet.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.tistory.webnautes.useopencvwithndk_build.MainActivity.<clinit>(MainActivity.java:48)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3083)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
I/Process: Sending signal. PID: 12657 SIG: 9
#=======================================
How to fix that? Thank you.

**Comment by leezu** [comment]
@bykim555 which version of MXNet are you building. Please open a new discussion thread. Thanks
