### ISSUE TITLE
Not Found Java Class "org.apache.mxnet.javaapi.Image"

### ISSUE THREAD

**Issue by tomoncle** [apache/incubator-mxnet#14845]
# Not Found Java Class "org.apache.mxnet.javaapi.Image"
I am testing mxnet in Java language, but a problem arises suddenly. I find that the `Image` class file does not exist. I try to reduce the version of mxnet. The problem still exists. So I ask this question here. How can I solve it?

I tested it against the code in the file [SSDClassifierExample.java](https://github.com/apache/incubator-mxnet/blob/master/scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/objectdetector/SSDClassifierExample.java), and the problem code appeared on line 168.

My test project path:  https://github.com/tomoncle/mxnet-spring-samples
bug file is [TestImage.java](https://github.com/tomoncle/mxnet-spring-samples/blob/master/mxnet-spring-samples-image-recognition/src/test/java/com/tomoncle/mxnet/test/TestImage.java)

## Environment info
1. Java version: Oracle 1.8 
2. Maven version: 3.6
3. springboot version: 2.1.2
4. OS: ubuntu-16.04
5. mxnet version: mxnet-full_2.11-linux-x86_64-cpu-1.4.0

![2019-04-30 16-01-59屏幕截图](https://user-images.githubusercontent.com/17229533/56948389-90b10c80-6b62-11e9-811f-3342c3aa0554.png)

**Comment by lanking520** [comment]
@tomoncle Thanks for reporting that. The Image API is introduced after 1.4.0. So you may expect it in 1.5.0. Try to configure your pom file like this: https://github.com/apache/incubator-mxnet/blob/master/scala-package/mxnet-demo/java-demo/pom.xml to use our nightly snapshot.

If you are willing to test it only under 1.4.0, I would suggest follow the code in here:
https://github.com/apache/incubator-mxnet/blob/v1.4.x/scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/objectdetector/SSDClassifierExample.java

**Comment by tomoncle** [comment]
@lanking520 Thank you for your reminder. I'll try `[1.5.0-SNAPSHOT,]` next.
