### ISSUE TITLE
MXNet to ONNX export bug with "out_shape" when using Crop

### ISSUE THREAD

**Issue by AnaRhisT94** [apache/incubator-mxnet#14881]
Hi,
I know Crop is deprecated, and probably this why "out_shape" key isn't available. Is there a future fix for this?
The current available workaround for this is just specifying the height and width manually for the crop, but it's not a long-term fix, if I will be using other width/height, and so on.

**Comment by AnaRhisT94** [comment]
**Solved in ONNX==1.2.2**

**Comment by chezhihong1** [comment]
> Just used Crop with num_args = 1 and sliced the h_w accordingly in the .json file (Directly).
> Also I suggest using ONNX==1.2.2 instead of 1.2.1, which has less op support for mxnet to onnx export functionality.

How to sliced the h_w accordingly in the .json file?  Have you changed _op_translations.py? Thank U~

**Comment by mcourse1993** [comment]
> Just used Crop with num_args = 1 and sliced the h_w accordingly in the .json file (Directly).
> Also I suggest using ONNX==1.2.2 instead of 1.2.1, which has less op support for mxnet to onnx export functionality.

I didn't understand how to fix it, could you elaborate more
