### ISSUE TITLE
[DOC] Build from source link for ubuntu is broken

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#14895]
On this page: https://github.com/apache/incubator-mxnet/blob/master/docs/install/build_from_source.md

If click the ubuntu hyperlink, it is broken:
https://github.com/apache/incubator-mxnet/blob/master/docs/install/ubuntu_setup.html

**Comment by vrakesh** [comment]
Looking into this, this seems to be true for all the links. since we convert our md docs to html for the docs website, looks like html links are hardcoded
