### ISSUE TITLE
How can I handle varying length labels for each instance?

### ISSUE THREAD

**Issue by erogol** [apache/incubator-mxnet#1494]
I like to create a recordio for my dataset where I have different  number of labels per instance. How can I handle such dataset most efficiently in mxnet? I tried to use the normal line of making list and making io file but it requires to have same length labels per instance. Any idea?

**Comment by piiswrong** [comment]
You can use bucketing API. Check out the examples.

**Comment by pluskid** [comment]
The [doc for bucketing API is here](http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html). However, the bucketing API does not help you to build an efficient DataIter.

**Comment by erogol** [comment]
I am sorry but I could not see how to use it for my case. To be more precise here is my example .lst file lines which includes different number on labels for different instances;

```
10	156.0	195.0	184.0	134.0	56af33fd93427e0f448335e60.jpg
11	156.0	195.0	177.0	8.0	56af33cc93427e0f4483353c0.jpg
12	156.0	124.0	343.0	56af33d593427e0f448335470.jpg
13	156.0	124.0	128.0	50.0	56af33cd93427e0f4483353d0.jpg
14	156.0	26.0	185.0	349.0	244.0	56af33fd93427e0f448335e80.jpg
15	156.0	26.0	185.0	349.0	244.0	56af33fd93427e0f448335e81.jpg
```

So for instance I like to use 156.0 195.0 184.0 134.0 as correct labels for the first instance not only one label but all of these. Still bucketing is a way?

I think to use PrefetchingIter which includes different iterators with different label_width values. Is is viable ?

**Comment by kxf8608** [comment]
this is also my question. Hope someone could help. Thanks.

**Comment by tornadomeet** [comment]
@erogol ,you should write your data iter which inherit from DataIter in the python side.

**Comment by erogol** [comment]
@tornadomeet yes it seems so. However one hacky way might be to give variable number of labels to each instance and fill the gaps with padding label values.  Like below one;

```
10  156.0   195.0   184.0   134.0  134.0  56af33fd93427e0f448335e60.jpg
11  156.0   195.0   177.0   8.0      8.0      56af33cc93427e0f4483353c0.jpg
12  156.0   124.0   343.0   343.0  343.0  56af33d593427e0f448335470.jpg
13  156.0   124.0   128.0   50.0    50.0    56af33cd93427e0f4483353d0.jpg
14  156.0   26.0    185.0   349.0   244.0   56af33fd93427e0f448335e80.jpg
15  156.0   26.0    185.0   349.0   244.0   56af33fd93427e0f448335e81.jpg
```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
