### ISSUE TITLE
[Bug] ValueError: There are multiple outputs with name "resnetv1b_layers4_conv0_fwd_output"

### ISSUE THREAD

**Issue by pdx1989** [apache/incubator-mxnet#14957]
Minimum reproducible example:
import gluoncv
import mxnet as mx

data = mx.sym.var(name="data")
net = gluoncv.model_zoo.mask_rcnn_resnet50_v1b_coco(pretrained=False)
net.initialize()
sym = net(data)
sym_block = mx.gluon.nn.SymbolBlock(sym, [data])

Error:
Traceback (most recent call last):
  File "case.py", line 8, in <module>
    sym_block = mx.gluon.nn.SymbolBlock(sym, [data])
  File "/newhome/daoxin/py3-env/lib/python3.5/site-packages/mxnet/gluon/block.py", line 1050, in __init__
    for j in i.get_internals():
  File "/newhome/daoxin/py3-env/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 93, in <genexpr>
    return (self[i] for i in self.list_outputs())
  File "/newhome/daoxin/py3-env/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 517, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "resnetv1b_layers4_conv0_fwd_output"

Version:
gluoncv 0.4.0
mxnet 1.4.0

Could anyone help me? Thank you!

**Comment by vdantu** [comment]
@mxnet-label-bot add [bug, question]

**Comment by mseth10** [comment]
@mxnet-label-bot add [Gluon]

**Comment by mseth10** [comment]
```
import gluoncv
import mxnet as mx

data = mx.sym.var(name="data")
net = gluoncv.model_zoo.mask_rcnn_resnet50_v1b_coco(pretrained=False)
net.initialize()
sym = net(data)
```
After running the above code snippet, if we take a look at `sym`, we see that:
```
>>> print (sym)
(<Symbol maskrcnn0_reshape8>, <Symbol maskrcnn0_reshape9>, <Symbol maskrcnn0_reshape10>, <Symbol maskrcnn0_sigmoid0>)
```
`sym` is a tuple of 4 symbols that share the same internal nodes. Hence, we cannot use these symbols in the same block. We can use them individually though:
```
sym_block0 = mx.gluon.SymbolBlock(sym[0], [data])
sym_block1 = mx.gluon.SymbolBlock(sym[1], [data])
```

@pdx1989 Hope this answers your question.

**Comment by mseth10** [comment]
@anirudh2290 can you please close this issue. It has been answered.
@pdx1989 In case you have any lingering questions feel free to reopen the issue.
