### ISSUE TITLE
performance improvement compare to mxnet1.3.0

### ISSUE THREAD

**Issue by kevinVegBird** [apache/incubator-mxnet#14968]
we know that the mxnet 1.4.0 performance of training is better than mxnet 1.3.0,after my testing the speed of training is faster than mxnet 1.3.0 very much.I want to know which part is critical for the speed improvement?thank you.
Labels:performance

**Comment by pengzhao-intel** [comment]
Could you do profiling for your cases so it will be clear which parts are accelerated?

**Comment by pengzhao-intel** [comment]
Closing because the question is answered. Feel free to reopen :)
