### ISSUE TITLE
Flaky Test: test_tensorrt_lenet5.test_tensorrt_inference

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#14978]
Happening for 2 independent PRs.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14959/9/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14830/19/pipeline

**Comment by asitstands** [comment]
Another failure is here. http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-10951/33/pipeline

**Comment by apeforest** [comment]
one more: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15041/5/pipeline/317

**Comment by perdasilva** [comment]
I've submitted a PR to fix it: #15014

**Comment by apeforest** [comment]
https://github.com/apache/incubator-mxnet/pull/15014 has fixed this issue. Closing it.

**Comment by anirudh2290** [comment]
Reopening, still encountered this here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15118/13/pipeline
