### ISSUE TITLE
mxnet-cu100 vs mxnet-cu100mkl vs mxnet

### ISSUE THREAD

**Issue by Charles-Schleich** [apache/incubator-mxnet#14972]
I'm a bit confused as to which packages i need and the benefits of one vs the others.

Currently i have mxnet 1.4.1 installed and the project i have runs fine on a CPU,
I'm using a machine with a GPU that has NVIDIA 418.40.04 drivers and CUDA 10.1  installed. 
So ideally id like to use that. 

Do i need both mxnet in addition to mxnet-cu100/mkl installed ? 
What are the differences mxnet-cu100 vs mxnet-cu100mkl ?

Hoping this answer clears up questions others might have as well.

**Comment by pengzhao-intel** [comment]
It's a good question. 
`mxnet-cuXX` with cuDNN acceleration, good performance on GPU
`mxnet-cuXXmkl` with both cuDNN and MKL-DNN library acceleration, good performance on both CPU and GPU.

http://mxnet.incubator.apache.org/versions/master/install/index.html?platform=Linux&language=Python&processor=CPU
> mxnet-cu92mkl means the package is built with CUDA/cuDNN and MKL-DNN enabled and the CUDA version is 9.2.

**Comment by pengzhao-intel** [comment]
Suppose the question is answered. Closing now and feel free to re-open.
