### ISSUE TITLE
Flaky test: test_lstm_clip

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#14994]
test_gluon_gpu.test_lstm_clip
```
======================================================================

FAIL: test_gluon_gpu.test_lstm_clip

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 110, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_gluon_gpu.py", line 163, in test_lstm_clip

    assert (cell_states >= clip_min).all() and (cell_states <= clip_max).all()

AssertionError: 

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=551104712 to reproduce.

--------------------- >> end captured logging << ---------------------


````

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14935/6/pipeline

https://github.com/apache/incubator-mxnet/pull/14935/files

**Comment by lanking520** [comment]
@mxnet-label-bot remove [flaky]

**Comment by larroy** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15109/5/pipeline

**Comment by aaronmarkham** [comment]
Failed again....
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15885/14/pipeline

**Comment by TEChopra1000** [comment]
Failed again... 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-16598/1/pipeline/

**Comment by ChaiBapchya** [comment]
For unrelated PR #17487 
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-gpu/branches/PR-17487/runs/21/nodes/431/log/?start=0

**Comment by ChaiBapchya** [comment]
Unrelated PR #18206 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18206/4/pipeline/356

**Comment by ChaiBapchya** [comment]
PR #18597 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18597/9/pipeline

**Comment by leezu** [comment]
https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/centos-gpu/branches/PR-19470/runs/1/nodes/143/steps/215/log/?start=0

**Comment by leezu** [comment]
Flaky test is annotated in source via `@pytest.mark.flaky` now. It may be easier to track the flaky tests via source grep and we can close this issue
