### ISSUE TITLE
The discription of function mxnet.image.imresize is wrong.

### ISSUE THREAD

**Issue by zhouhang95** [apache/incubator-mxnet#14993]
I find it wrong when I also write my psnr code.

'''
        2: Area-based (resampling using pixel area relation). It may be a
        preferred method for image decimation, as it gives moire-free
        results. But when the image is zoomed, it is similar to the Nearest
        Neighbors method. (used by default).
        3: Bicubic interpolation over 4x4 pixel neighborhood.
'''
should be
'''
        2: Bicubic interpolation over 4x4 pixel neighborhood.
        3: Area-based (resampling using pixel area relation). It may be a
        preferred method for image decimation, as it gives moire-free
        results. But when the image is zoomed, it is similar to the Nearest
        Neighbors method. (used by default).
        
'''
you can see this page
https://docs.opencv.org/master/da/d54/group__imgproc__transform.html
'''
import cv2
print(cv2.INTER_CUBIC)
'''
you will see 
2

**Comment by vdantu** [comment]
@mxnet-label-bot add [question, bug]

**Comment by zachgk** [comment]
Thank you for the fix @zhouhang95. If you are interested in contributing to this open source project, feel free to open a pull request fixing those docs at https://github.com/zachgk/incubator-mxnet/blob/master/python/mxnet/image/image.py#L94.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Doc]

**Comment by pinaraws** [comment]
@mxnet-label-bot add[Doc]
