### ISSUE TITLE
[CI][NightlyTestsForBinaries]  nightly test failed on new AMP tutorial

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#15028]
After AMP PR https://github.com/apache/incubator-mxnet/pull/14173 added an AMP tutorial, but the nightly test on it is failing:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/320/pipeline

Seems the tutorial depends on gluoncv, we need to add it in CI environment here:
https://github.com/apache/incubator-mxnet/blob/master/ci/docker/install/ubuntu_tutorials.sh

**Comment by roywei** [comment]
@mxnet-label-bot add[Test, CI]

**Comment by Chancebair** [comment]
Taking a look

**Comment by roywei** [comment]
Now no more warnings, but nightly still fails with CUDA malloc OOM.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/333/pipeline/148

This is not observed in AWS P3 instances.

**Comment by roywei** [comment]
fixed in https://github.com/apache/incubator-mxnet/pull/15141
