### ISSUE TITLE
How to build a siamese network with contrastive loss?

### ISSUE THREAD

**Issue by fangli1992** [apache/incubator-mxnet#1504]
Could you give a example code?

**Comment by erogol** [comment]
Same is here :)

**Comment by qiaohaijun** [comment]
I want know how to set two datainput into the mxnet.

I think the idea of placeholder is nice

**Comment by jonbakerfish** [comment]
Any example?

**Comment by zhengxiawu** [comment]
Any example?@tqchen

**Comment by zihaolucky** [comment]
I've implemented a similar architecture using triple-loss for text classification, joint learning a text representation using CNN and a softmax after this for classification task. 

I think contrastive loss you want is quite similar, siamese should share weights of your representation learning network. For more detail, you can refer the code sample and tutorial from @xlvector here: https://zhuanlan.zhihu.com/p/21725762?refer=xlvector

**Comment by zihaolucky** [comment]
@qiaohaijun Two separated data input might be unnecessary in this case, as you can write a `sample_nagative` & `sample_positive` to generate training samples.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
