### ISSUE TITLE
Profiler Memory output title is misleading, shows as Time(ms) instead of Memory(Bytes)

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#15071]
In MXNet profiler output, for Device Storage output, title is misleading, it should be Memory(Bytes) but shows as Time (ms).

![image](https://user-images.githubusercontent.com/3403674/58363581-87624980-7e5b-11e9-87bd-a650bf164d2b.png)

**Comment by sandeep-krishnamurthy** [comment]
@Zha0q1 - Are you fixing this as part of your planned work at - https://github.com/apache/incubator-mxnet/issues/15069 ?

**Comment by ZhaoqiZhu** [comment]
Yes I am going to fix it

**Comment by ZhaoqiZhu** [comment]
> @Zha0q1 - Are you planning to fix this as part of your proposal at - #15069 ?

Yes I am going to fix it

**Comment by sandeep-krishnamurthy** [comment]
This is now resolved. Thanks @ZhaoqiZhu
