### ISSUE TITLE
tensorrt.tensorrt_bind results NDArray with NaN

### ISSUE THREAD

**Issue by srijiths** [apache/incubator-mxnet#15080]
## Description
Trying to convert ArcFace [https://github.com/deepinsight/insightface](url) using tensorrt.bind , output shape is (512,) coming as NaN but with mx.mod.Module its coming properly.

## Environment info (Required)
Cuda 10.0 , mxnet-cu100, [https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvinfer-runtime-trt-repo-ubuntu1604-5.0.2-ga-cuda10.0_1-1_amd64.deb](url)

What to do:
1. git clone https://github.com/srijiths/arcface_tensorrt_test.git 
2. cd arcface_tensorrt_test
3. Download encoding model 
curl -L -o model.zip https://www.dropbox.com/sh/tj96fsm6t6rq8ye/model-r100-arcface-ms1m-refine-v2.zip?dl=1
4. unzip model.zip
5. pip install opency-python imutils easydict scipy sklearn scikit-image mxnet-cu100

Package used (Python/R/Scala/Julia):
Python

## Error Message:
[[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]]

## Minimum reproducible example
python tensorrt_test.py

## Steps to reproduce
1. git clone https://github.com/srijiths/arcface_tensorrt_test.git 
2. cd arcface_tensorrt_test
3. Download encoding model 
curl -L -o model.zip https://www.dropbox.com/sh/tj96fsm6t6rq8ye/model-r100-arcface-ms1m-refine-v2.zip?dl=1
4. unzip model.zip
5. python tensorrt_test.py

## What have you tried to solve it?
1.
2.

**Comment by frankfliu** [comment]
@mxnet-label-bot add [backend, bug]

**Comment by sandeep-krishnamurthy** [comment]
@KellenSunderland - Can you please help here?

**Comment by KellenSunderland** [comment]
I don't think mxnet-cu100 has tensorrt enabled by default.  I'd recommend building from source on master and retrying.

**Comment by sandeep-krishnamurthy** [comment]
Thanks Kellen.

@srijiths - Please try with installing mxnet with tensorrt support
```
pip install mxnet-tensorrt-cu92
```

Closing the issue. Please reopen if issue still persists.

**Comment by srijiths** [comment]
Thank you @sandeep-krishnamurthy and @KellenSunderland . I have tried with mxnet-tensorrt-cu92 before , but it failed because i have cuda 10. So i have installed mxnet-cu100 . I assume that tensorrt binding is not available for mxnet-cu100. If there is any thing , i will update the ticket.
