### ISSUE TITLE
Mean absolute error regression output layer 

### ISSUE THREAD

**Issue by everglory99** [apache/incubator-mxnet#1508]
Hi, 
I am interested in looking at the detail of how this MAERegressionOutput layer is implemented and specifically how the sub gradient is computed. However, I am not able to find the source code snippet for this part, would you please point me to that? (I am using MXNet python package) Thanks!

**Comment by piiswrong** [comment]
It's in the backend at src/operators/regression_output-inl.h.

@tqchen How about we put some comment in symbol.py to explain where/how things are registered.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
