### ISSUE TITLE
SoftmaxActivation replacement

### ISSUE THREAD

**Issue by zhly0** [apache/incubator-mxnet#15119]
Hi,
        In the mxnet doc,it is said SoftmaxActivation will be deprecated in the future,please use softmax,but it does not give the demo use of softmax,like, I use softmaxactivation like this:
 SoftmaxActivation(data=A,mode="channel"),then what should I set the softmax parameters?
Thanks!

**Comment by chinakook** [comment]
softmax(A, axis=1)

**Comment by zhly0** [comment]
@chinakook ，thanks，I looked into Softmax，and did not found axis parameter.I did not see softmax,which has it.
