### ISSUE TITLE
[Clojure][Scala] Converting an ndarray to a BufferedImage is really slow

### ISSUE THREAD

**Issue by Chouffe** [apache/incubator-mxnet#15123]
When calling the `to-image` function from the clojure package which interops with the Scala `Image/toImage`, it is really slow to create the `BufferedImage`. Waiting for 4-5 seconds on a 1024x576px image ("Pug_cookie.jpg").

**Comment by frankfliu** [comment]
@mxnet-label-bot add [scala, performance, clojure]

**Comment by lanking520** [comment]
Yeah it is kind of slow due to the naïve implementation of  https://github.com/apache/incubator-mxnet/blob/master/scala-package/core/src/main/scala/org/apache/mxnet/Image.scala#L174-L192. In a sense of converting them pixel by pixel. You can try to use some third-party library to accelerate them

**Comment by Chouffe** [comment]
Would there be a way to batch (per row or column) the actual RGB conversion?
