### ISSUE TITLE
doc consistence

### ISSUE THREAD

**Issue by zhly0** [apache/incubator-mxnet#15131]
Hi，
    In the doc，http://mxnet.incubator.apache.org/versions/master/tutorials/onnx/export_mxnet_to_onnx.html，has a page give the supported op：https://cwiki.apache.org/confluence/display/MXNET/ONNX+Operator+Coverage，but in the code，the list is different：
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/contrib/onnx/mx2onnx/_op_translations.py

**Comment by frankfliu** [comment]
@mxnet-label-bot add [ONNX, doc]

**Comment by vandanavk** [comment]
Updated https://cwiki.apache.org/confluence/display/MXNET/ONNX+Operator+Coverage. This doc has a list of operators according to ONNX 1.3 spec. 
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/contrib/onnx/mx2onnx/_op_translations.py may have other operators which are specific to MXNet

**Comment by zhly0** [comment]
Thanks！
