### ISSUE TITLE
mxnet doc error

### ISSUE THREAD

**Issue by William-jia** [apache/incubator-mxnet#15134]
https://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=multiproposal#mxnet.ndarray.contrib.MultiProposal

cls_prob (NDArray) – Score of how likely proposal is object.
bbox_pred (NDArray) – BBox Predicted deltas from anchors for proposals
im_info (NDArray) – Image size and scale.
**rpn_pre_nms_top_n (int, optional, default='6000') – Number of top scoring boxes to keep after applying NMS to RPN proposals
rpn_post_nms_top_n (int, optional, default='300') – Overlap threshold used for non-maximumsuppresion(suppress boxes with IoU >= this threshold
threshold (float, optional, default=0.699999988) – NMS value, below which to suppress.**

i think the right answer is :

rpn_pre_nms_top_n (int, optional, default='6000') – Number of top scoring boxes to keep **before** applying NMS to RPN proposals
rpn_post_nms_top_n (int, optional, default='300') –  Number of top scoring boxes to keep **after** applying NMS to RPN proposals
threshold (float, optional, default=0.699999988) – Overlap threshold used for non-maximumsuppresion(suppress boxes with IoU >= this threshold NMS value, below which to suppress.

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Doc, bug]

**Comment by aaronmarkham** [comment]
@William-jia regarding the last line - I'm seeing this in the code, which is different from what you posted... thinking I should leave this alone. You?
```
    DMLC_DECLARE_FIELD(threshold).set_default(0.7)
    .describe("NMS value, below which to suppress.");
```
https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal-inl.h#L70
