### ISSUE TITLE
Compile failed when disable OPENMP

### ISSUE THREAD

**Issue by moneypi** [apache/incubator-mxnet#15133]
## Description
(Brief description of the problem in no more than 2 sentences.)
Build from source code, when I set
```
OPENMP = 1
```
I can compile success, and run test success, But if I set OPENMP = 0 , I will compile failed

## Environment info (Required)
Ubuntu 19.04 in VMware
g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
No GPU

I'm using Python 3.7.3

MXNet commit hash: 5fc4fc53df74f276aafa51208142e657e9cfe42d

Build config:
I only copy config.mk from make/config.mk, if I don't change anything,I will compile succes.
But if I set
OPENMP =0
I will compile failed.

## Steps to reproduce
make -j4

**Comment by pengzhao-intel** [comment]
@Neozhangjianyu @yinghu5 could you help to take a look?

**Comment by moneypi** [comment]
I'm sorry @mxnet-label-bot , I don't know how to set label......

**Comment by arthw** [comment]
@moneypi
1. Could you post the full build cmd here?
2. Please run following cmd and post the result:
```
env | grep PYTHON
env | grep LD_LIBRARY_PATH
```
3. I guess your build is wrong.
Could you find any error in the build output?
Is it possible to post the full log here?

**Comment by moneypi** [comment]
env | grep PYTHON is empyt

$ env | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=/home/luke/Download/incubator-mxnet/lib

git clone --recursive https://github.com/apache/incubator-mxnet
cd incubator-mxnet
cp make/config.mk config.mk
vim config.mk #set OPENMP=0
make -j4 > OPENMP=0.log 2>&1


[OPENMP=0.zip](https://github.com/apache/incubator-mxnet/files/3246642/OPENMP.0.zip)

**Comment by NeoZhangJianyu** [comment]
@moneypi I'm checking it.

**Comment by NeoZhangJianyu** [comment]
@moneypi I can't repeat your issue.
In your log, there is cause to stop:
```
g++: fatal error: 已杀死 signal terminated program cc1plus
compilation terminated.
```
Do you know the reason? 
or have you stop the compile manually?
I see the compile time is a little long in this part.

**Comment by moneypi** [comment]
I didn't stop the compile manually.
I meet the same problem every time.
I don't know why.
I will try it in another computer later.

**Comment by NeoZhangJianyu** [comment]
@moneypi 
I guess the compiler is crashed in your case:
```
g++: fatal error: 已杀死 signal terminated program cc1plus
```
It's rare case. I think it's the compiler issue.
Maybe to setup another development environment is better solution.

**Comment by moneypi** [comment]
Thanks very much.
I copy the code to another XUbuntu19.04, and it's ok.

I didn't find the reason.Maybe I made mistake.
Thanks.

**Comment by moneypi** [comment]
I change the memory(VMware) from 8G to 16G, and it's ok.
I will try tommory to make sure it's the reason.

**Comment by moneypi** [comment]
I repeat the problem when memory is 8G.
And compile success after change to 16G.
So, that's the reason.
