### ISSUE TITLE
How to print data of NDArray in c++？

### ISSUE THREAD

**Issue by moneypi** [apache/incubator-mxnet#15157]
Maybe I have the similar question with 
https://github.com/apache/incubator-mxnet/issues/3125,

I learn the source code https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/ndarray.h , I want to learn the mxnet source code and add some debug code, but I don't know how to print a NDArray like an array in C++.I know print a NDArray in Python is easy.

Can anyone help me?

**Comment by leleamol** [comment]
@moneypi 
 You can use the overloaded operator "<<" of mxnet::cpp::NDArray object as follows:

`
NDArray image_data = NDArray(input_shape, global_ctx, false);
  image_data.SyncCopyFromCPU(array.data(), input_shape.Size());
std::cout << image_data;
`

You can refer to implementation of "<<" in ndarray.hpp here 
https://github.com/apache/incubator-mxnet/blob/c474f5f88ab39c39a64976adc59ef4cfe7a6be79/cpp-package/include/mxnet-cpp/ndarray.hpp#L433

@mxnet-label-bot add [C++, Question]

**Comment by leleamol** [comment]
@moneypi  please let us know if this answers your question so that we can close this issue.

@mxnet-label-bot add [Pending Requester Info]

**Comment by moneypi** [comment]
I'm sorry, I think that's not easy for me.
I change funcition MXNDArrayGetGrad in c_api.cc
```
int MXNDArrayGetGrad(NDArrayHandle handle, NDArrayHandle *out) {
  API_BEGIN();
  NDArray *arr = static_cast<NDArray*>(handle);
  NDArray ret = arr->grad();
  if (ret.is_none()) {
    *out = NULL;
  } else {
    *out = new NDArray(ret);

    if (!ret.is_none()){
      void *p_void = ret.data().dptr_;
      mx_float *p_float = static_cast<mx_float*>(p_void);
      std::cout << "p = " << p_float[3] << std::endl;
    }
  }
  API_END();
}
```
My python code is simple,
```
from mxnet import autograd, nd
import mxnet
print(mxnet.__version__)

x = nd.arange(2, 7).reshape((5, 1))

x.attach_grad()


with autograd.record():
    y = 2 * nd.dot(x.T, x)

y.backward()


# assert (x.grad - 4 * x).norm().asscalar() == 0
print(x.grad)
```
But I get '0' every time.
Can I get the right value with little change?

**Comment by moneypi** [comment]
Thanks， I can print the grad now.Code as below:
```
int MXNDArrayGetGrad(NDArrayHandle handle, NDArrayHandle *out) {
  API_BEGIN();
  NDArray *arr = static_cast<NDArray*>(handle);
  NDArray ret = arr->grad();
  if (ret.is_none()) {
    *out = NULL;
  } else {
    std::cout << "ret.shape().ndim() = " << ret.shape().ndim() << std::endl;
    std::cout << "ret.shape()[0] = " << ret.shape()[0] << std::endl;
    std::cout << "ret.shape()[1] = " << ret.shape()[1] << std::endl;
    *out = new NDArray(ret);

    NDArray cpu_array(ret.shape(), Context::CPU());
    CopyFromTo(ret, cpu_array);
    cpu_array.WaitToRead();

    float *p_float = (float *)(cpu_array.data().dptr_);
    for (int i = 0; i < ret.shape()[0] * ret.shape()[1]; i++){
     std::cout << "p_float[" << i << "] = " << p_float[i] << std::endl;
    }
  }
  API_END();
}
```
