### ISSUE TITLE
Missing videos in autograd docs page

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#15160]
The beta docs page for autograd - http://beta.mxnet.io/guide/packages/autograd/autograd.html has a couple of embedded videos. But the videos are blank.

cc: @aaronmarkham

**Comment by leleamol** [comment]
@mxnet-label-bot add [Doc, Website]

**Comment by larroy** [comment]
Where is the source for this?

**Comment by anirudhacharya** [comment]
@larroy I think this is the source for the beta website - https://github.com/mli/new-docs

**Comment by aaronmarkham** [comment]
So the trick here is to move the images or videos (these videos are tiny, so they'll count as images) over to the static folder. I did something similar here: https://github.com/apache/incubator-mxnet/pull/15205/files#diff-dd9fe9390d558c60e8a5794696784ec6
I'm back from vacation so I can fix this later today unless one of you were already working on this.
