### ISSUE TITLE
60-Minute Gluon Crash Course External link broken

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#15178]
http://gluon-crash-course.mxnet.io/ (redirecting to https://beta.mxnet.io/guide/crash-course/index.html) is unavailable.

Access rights seem to be misconfigured:

`<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>49557F1F99E46EA4</RequestId><HostId>jznxIFGTB3F/f4XPIeRQIz+2UO0JhmABzAK1yaQY4s58Bx35ZmkxRvAxL4wQCo5uGMwFTnGmHGo=</HostId></Error>`

CC: @astonzhang @szha

**Comment by leleamol** [comment]
@mxnet-label-bot add [Doc, Gluon, Website]

**Comment by leleamol** [comment]
I verified that the links are accessible now.
@lanking520 I would recommend closing this issue.
