### ISSUE TITLE
How to load model parameters in jar packages using java predictor

### ISSUE THREAD

**Issue by rongruosong** [apache/incubator-mxnet#15191]
Linux-1.5.0 

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
I want to put my parameters in jar, but  I don't know how to set the modelPathPrefix of java predictor.

**Comment by zachgk** [comment]
@rongruosong What you could do is copy all of the parameters from the jar to a temporary directory. Then, give the path to the temporary directory. We have to do something similar with the mxnet binary files in https://github.com/apache/incubator-mxnet/blob/master/scala-package/core/src/main/scala/org/apache/mxnet/util/NativeLibraryLoader.scala#L147.

**Comment by zachgk** [comment]
There has not been any response for several months and a solution was proposed for the issue. I will close this for now. Please reopen if the issue remains.
