### ISSUE TITLE
new performance benchmark numbers needed

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#15203]
## Description
https://mxnet.incubator.apache.org/versions/master/faq/perf.html
This refers to a release candidate that is no longer available. (broken link)

From the page:
The following table shows performance of [MXNet-1.2.0.rc1](https://github.com/apache/incubator-mxnet/releases/download/1.2.0.rc1/apache-mxnet-src-1.2.0.rc1-incubating.tar.gz),

I could change that to point to 1.2.0, but then it's not entirely accurate anymore. It may not be reproducible. Can we just get newer benchmark data in there from a recent release?

**Comment by TaoLv** [comment]
Thank you @aaronmarkham. We're collecting new performance numbers on CPU side and will update to the page once 1.5.0 is released. @pengzhao-intel @yinghu5

**Comment by ys2843** [comment]
Looks like the benchmark numbers are up to date. Issue can be closed. @aaronmarkham
