### ISSUE TITLE
Broken Sidebar on website API for master

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#15200]
See https://mxnet.incubator.apache.org/versions/master/api/python/index.html

![Screen Shot 2019-06-10 at 3 56 20 PM](https://user-images.githubusercontent.com/3716307/59232215-60648100-8b98-11e9-877c-7ccb03277b30.png)

vs 

![Screen Shot 2019-06-10 at 3 56 55 PM](https://user-images.githubusercontent.com/3716307/59232225-6f4b3380-8b98-11e9-8341-84cda489ad99.png)

**Comment by ThomasDelteil** [comment]
@aaronmarkham

**Comment by aaronmarkham** [comment]
**Bad news**
I tested a variety of build configurations. 

1. In settings, I turned the artifacts feature on and off.
2. I built all versions plus using 1.5.x to see if a recent cut had a similar problem. It does not. [1.5.x looks fine](http://34.201.8.176/versions/1.5.0/api/python/index.html).
3. I built a variation of master with a [different name and the nav is broken](http://34.201.8.176/versions/master_test/api/python/index.html).

**Good news**
I tested changing the [default version to 1.4.1 and it works](http://34.201.8.176/versions/1.4.1/api/python/index.html) or see the [root working and test the dropdown](http://34.201.8.176/).

**Comment by aaronmarkham** [comment]
I tried rolling back to some older commits and found the site to work.
Then after trying many older commits I decided to look at the s3 previews coming out of CI for anything in `/doc` [history](https://github.com/apache/incubator-mxnet/commits/master/docs). This is very strange - the previews have broken navs then working navs in no obvious order.

1. broken: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-14987/8/api/python/index.html
1. working: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15111/2/api/python/index.html
1. working: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15156/4/api/python/index.html
1. working: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15185/1/api/python/index.html
1. broken: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15205/1/api/python/index.html

Maybe something was going on with CI (and still is?).

**Comment by larroy** [comment]
Have you tried to rebuild one of those commits locally?

**Comment by aaronmarkham** [comment]
I built every commit backwards until I narrowed it down to this one:
https://github.com/apache/incubator-mxnet/pull/14987

Should I revert this commit? I can't see how it would be causing the issues, the commit just prior comes out ok.

**Comment by aaronmarkham** [comment]
I noticed that the content is in the page, but not visible. I don't know why this bug would only affect master, but I imagine the solution is in the javascript that moves the sidebars around. 
https://github.com/apache/incubator-mxnet/blob/master/docs/_static/js/sidebar.js

This area of code is the source of several bugs - from the footer overlapping content when the page toc is too short to not opening the page you expect.

I pointed the website default to 1.4.1 to lessen the disruption for users for now. I don't think I should do a revert on the commit I narrowed down to because the changes wouldn't have this kind of impact. It has to be something else.

I think we need someone to focus on the core issue - the js hacks on the theme and try to fix those directly.

**Comment by larroy** [comment]
Could it be the changes from HTML to md in the links?

**Comment by larroy** [comment]
Can you try to use the browser Dev tools and debug keepExpand to see why the links are not generated? Could be that they don't come from sphynx from a quick look I didn't see anything obvious with the markdown vs HTML.

**Comment by aaronmarkham** [comment]
Yes. It seems like there are quite a few bugs in there - variables that should be tracking what's an API page that are undefined. Seems to be less a doc problem and more a front-end engineering problem to me.

**Comment by ChaiBapchya** [comment]
@aaronmarkham 
> I noticed that the content is in the page, but not visible

Well. I tried to compare the working V1.4.1 vs master
Here's the console output
### Ideal Condition. V1.4.1
![V1.4.1 Console for sidebar](https://user-images.githubusercontent.com/10992635/61981685-2ec04180-afaf-11e9-88ce-95cb2b2c24c6.png)

### Master
Div `<div class="sphinxsidebar leftsidebar">` exists. But the content is missing.
 
![Screen Shot 2019-07-26 at 2 04 48 PM](https://user-images.githubusercontent.com/10992635/61981676-2b2cba80-afaf-11e9-8b99-4724fdd24dfa.png)

Any idea what am I missing?

**Comment by larroy** [comment]
I don't know much about sphinx. 

https://github.com/apache/incubator-mxnet/blob/master/docs/_static/mxnet-theme/layout.html

This seems to reference localtoc: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/localtoc.html

Which seems to be missing. So I guess the toc is not being generated correctly. Let me generate the docs and see if there's some error message with the TOC.

**Comment by larroy** [comment]
I think the problem is in sidebar.js  that component is loaded dynamically in JS, has to be debugged. Also layout.html is somehow missing but not sure is related.

**Comment by larroy** [comment]
I think the problem is in the generated html,is missing the element ul class "current" so the selector gets an empty text. Looks like doxygen problem.

**Comment by larroy** [comment]
It's quite puzzling, I have look at many places, compared with 1.4.1 and don't find the root cause.

**Comment by ChaiBapchya** [comment]
Yup. Went through the steps you mentioned, (breakpoints, comparison with previous version, debug)
But missing the root cause..

**Comment by larroy** [comment]
We need to bisect, to find out when it was broken. I have a script to do that.

**Comment by aaronmarkham** [comment]
@larroy Not sure if it is worth the effort. We're hoping to launch a refactored website soon and we won't be using any of this old js or sphinx theme. But, if it's easy and you want to try... don't let me stop you!

**Comment by larroy** [comment]
OK, I have other things to do, I thought this was important for the release.

**Comment by aaronmarkham** [comment]
New site makes this a moot issue.
