### ISSUE TITLE
java hello world demo is missing

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#15204]
## Description
The instructions for Java have a step where you use a hello world app. This app was deleted, but we still need something for users to try out. I suggest adding it back.

https://mxnet.incubator.apache.org/versions/master/tutorials/java/mxnet_java_on_intellij.html
See step 6. Those links are all broken.

**Comment by aaronmarkham** [comment]
@zachgk

**Comment by zachgk** [comment]
I will add it back
