### ISSUE TITLE
Add tensorrt and quantization in the docs of the website

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#15201]
We are referrencing tensorrt and quantization in a few tutorials / blog posts etc though they do not appear under the contrib section of the docs. It would be great to add them.

@aaronmarkham

**Comment by pengzhao-intel** [comment]
We can contribute to MKLDNN quantization part :)

**Comment by aaronmarkham** [comment]
@IvyBazan can you please take a look at this?

**Comment by ys2843** [comment]
https://mxnet.apache.org/versions/1.6/api/python/docs/api/contrib/index.html, tensorrt and quantization were added to the contrib page. Issue can be closed.
