### ISSUE TITLE
Problems encountered when converting the data

### ISSUE THREAD

**Issue by gclouding** [apache/incubator-mxnet#1522]
I downloaded imagnet-1k dataset (ILSVRC2014_CLS_LOC dataset), and prepared to convert the data into *.rec format that MXNet required, by using the following command:
/mxnet/bin/im2rec   train_for_mxnet.txt     /data/ILSVRC2012_img_train/     train.rec   quality=90 resize=256 center_crop=1

However, an error occurred as shown below "Corrupt JPEG data: 1483 extraneous bytes before marker 0xd9" after 141000 images are processed. 

[00:39:39] tools/im2rec.cc:251: 140000 images processed, 3975.24 sec elapsed
[00:40:11] tools/im2rec.cc:251: 141000 images processed, 4007.3 sec elapsed
Corrupt JPEG data: 1483 extraneous bytes before marker 0xd9
[00:40:41] tools/im2rec.cc:251: 142000 images processed, 4037.94 sec elapsed

Could you please tell me what this means ? And how to avoid this ? Many thanks

**Comment by piiswrong** [comment]
Try the python script for conversion. Also some of your images might be corrupted.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
