### ISSUE TITLE
nd.random is not really random

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#15225]
numpy random module uses a different seed each time program starts: 
```
python
>>> import numpy as np; np.random.randint(10)
4
```
```
[ec2-user@ip-172-31-10-195 bert]$ python
Python 2.7.16 (default, Mar 18 2019, 18:38:44)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
>>> import numpy as np; np.random.randint(10)
>>> 1
```

however, mxnet has a fixed random seed:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx; mx.nd.random.randint(low=0, high=10)

[1]
<NDArray 1 @cpu(0)>
```
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx; mx.nd.random.randint(low=0, high=10)

[1]
<NDArray 1 @cpu(0)>
```
@astonzhang also find this behavior confusing for d2l readers. We should fix it for our numpy compatible feature. 
@haojin2 @reminisce

**Comment by zachgk** [comment]
This problem also came up in #7410

**Comment by larroy** [comment]
suggest closing as duplicate.

**Comment by chinakook** [comment]
Yes, I found this problem too. If we run a script (contain nd.random) 1000 times, we will get 1000 same results. However, If put nd.random to a loop with 1000 iters, we will get 1000 really random numbers.

**Comment by eric-haibin-lin** [comment]
Closing this to discuss on https://github.com/apache/incubator-mxnet/issues/7410 instead
