### ISSUE TITLE
USE NNPACK compile error! FullyConnectedOp does not exists.

### ISSUE THREAD

**Issue by kangkangRabbit** [apache/incubator-mxnet#15232]
Class FullyConnectedOp was deleted since version 1.1.0. Below is compile error message:

    src/operator/nn/../nnpack/nnpack_fully_connected-inl.h:45:39: error: unknown template name 'FullyConnectedOp'

**Comment by kangkangRabbit** [comment]
src/operator/./nnpack/nnpack_convolution-inl.h:37:10: fatal error: '../convolution-inl.h' file not found
    #include "../convolution-inl.h"
             ^~~~~~~~~~~~~~~~~~~~~~

**Comment by leleamol** [comment]
@kangkangRabbit can you please try with the latest code in master branch?

@mxnet-label-bot add [Pending Requester Info]

**Comment by lanking520** [comment]
@kangkangRabbit Close this issue due to the inactivity. Please feel free to reopen if this problem persist.
