### ISSUE TITLE
[RFC] Custom Operator Profiling Enhancement 

### ISSUE THREAD

**Issue by Zha0q1** [apache/incubator-mxnet#15241]
Please find the design doc at:
https://cwiki.apache.org/confluence/display/MXNET/Custom+Operator+Profiling+Enhancement

I have created a PR for this proposal: https://github.com/apache/incubator-mxnet/pull/15210

**Comment by anirudh2290** [comment]
Thanks @Zha0q1 . This is nice work! ccing @wkcn @arcadiaphy to help take a look. @YutingZhang for FYI

**Comment by Zha0q1** [comment]
> Thanks @Zha0q1 . This is nice work! ccing @wkcn @arcadiaphy to help take a look. @YutingZhang for FYI

Thanks!
