### ISSUE TITLE
Symbol Documentation Error

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#1526]
The documentation states that certain symbols (such as `mxnet.symbol.sin`) have as input a named kwarg 'src' (http://mxnet.readthedocs.org/en/latest/python/symbol.html)

Yet running this:

```
in1= mx.symbol.Variable("data")
mx.symbol.sin(src=in1)
```

gives an error:

```
MXNetError: [17:51:47] src/symbol/symbol.cc:121: Symbol.ComposeKeyword argument name src not found.
Candidate arguments:
    [0]data
```

The docs are obviously automatically generated, so the generator should be fixed.

**Comment by Beanocean** [comment]
There is an error in the second example of [Python tutorial of Symbol](http://mxnet.readthedocs.org/en/latest/python/tutorial.html#more-complicated-composition).
Example code:
```
>>> net = mx.symbol.Variable('data')
>>> net = mx.symbol.FullyConnected(data=net, name='fc1', num_hidden=128)
>>> net2 = mx.symbol.Variable('data2')
>>> net2 = mx.symbol.FullyConnected(data=net2, name='net2', num_hidden=128)
>>> composed_net = net(data=net2, name='compose')
>>> composed_net.list_arguments()
```
Expected output:
`['data2', 'net2_weight', 'net2_bias', 'compose_fc1_weight', 'compose_fc1_bias']`
Actual output:
`['data2', 'net2_weight', 'net2_bias', 'fc1_weight', 'fc1_bias'] `

**Comment by eric-haibin-lin** [comment]
The document has been updated. Closing it for now due to inactivity. Please feel free to reopen it for followup discussions.
