### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by frischzenger** [apache/incubator-mxnet#15287]
the pretrained model link is no longer exist,
data.dmlc.ml/mxnet/models
is there a valid link?

**Comment by wkcn** [comment]
Thank you for pointing it out!

It seems that the link `dmlc.ml` is out of date.
We can replace `data.dmlc.ml` with `data.mxnet.io` temporarily.
e.g.

Before:
```
http://data.dmlc.ml/models/imagenet/vgg/vgg16-0000.params
```

After:
```
http://data.mxnet.io/models/imagenet/vgg/vgg16-0000.params
```

`http://data.mxnet.io/models` is an empty website, but the model files can be downloaded.

**Comment by frischzenger** [comment]
i have checked the link you supported, but the pretrained model still cant be downloaded

**Comment by wkcn** [comment]
@frischzenger Could you please provide the link you used?

**Comment by frischzenger** [comment]
http://data.mxnet.io/models/imagenet/resnet/50-layers/resnet-50-0000.params
http://data.mxnet.io/models/imagenet/resnet/50-layers/resnet-50-symbol.json

**Comment by wkcn** [comment]
@frischzenger Thank you! I can download the files from the two links. I think the website may be blocked.

**Comment by aaronmarkham** [comment]
> @frischzenger Thank you! I can download the files from the two links. I think the website may be blocked.

The data.mxnet.io site was switched over to S3 and that doesn't support browsing like a regular website. You have to specifically request an asset for it to respond.

I'm going to close this for now. Please open another issue if you can't find a model.
