### ISSUE TITLE
Symbol Document Error: the arguments' name of symbol

### ISSUE THREAD

**Issue by Beanocean** [apache/incubator-mxnet#1529]
There is an error in the second example of [Python tutorial of Symbol](http://mxnet.readthedocs.org/en/latest/python/tutorial.html#more-complicated-composition).
Example code:

```
>>> net = mx.symbol.Variable('data')
>>> net = mx.symbol.FullyConnected(data=net, name='fc1', num_hidden=128)
>>> net2 = mx.symbol.Variable('data2')
>>> net2 = mx.symbol.FullyConnected(data=net2, name='net2', num_hidden=128)
>>> composed_net = net(data=net2, name='compose')
>>> composed_net.list_arguments()
```

Expected output:
`['data2', 'net2_weight', 'net2_bias', 'compose_fc1_weight', 'compose_fc1_bias']`
Actual output:
`['data2', 'net2_weight', 'net2_bias', 'fc1_weight', 'fc1_bias']`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
