### ISSUE TITLE
Mxnet fails to properly parallelize with a ryzen CPU.

### ISSUE THREAD

**Issue by Bjohnson131** [apache/incubator-mxnet#15304]
## Description
With a Rysen 7 2700 CPU, the libmxnet DLL fails to properly parallelize. At any one time, it's using only one core of CPU and no more, while in an exclusive CPU configuration

## Environment info (Required)
----------Python Info----------
('Version      :', '2.7.15')
('Compiler     :', 'MSC v.1500 32 bit (Intel)')
('Build        :', ('v2.7.15:ca079a3ea3', 'Apr 30 2018 16:22:17'))
('Arch         :', ('32bit', 'WindowsPE'))
------------Pip Info-----------
('Version      :', '18.1')
('Directory    :', 'C:\\Python27\\lib\\site-packages\\pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Windows-10-10.0.17134')
('system       :', 'Windows')
('node         :', 'DESKTOP-33G95HI')
('release      :', '10')
('version      :', '10.0.17134')
----------Hardware Info----------
('machine      :', 'AMD64')
('processor    :', 'AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD')
Name
AMD Ryzen 7 2700 Eight-Core Processor

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0060 sec, LOAD: 1.1130 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0350 sec, LOAD: 0.6090 sec.
Error open FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>, DNS finished in 0.039999961853 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0360 sec, LOAD: 0.2240 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0750 sec, LOAD: 0.6050 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0400 sec, LOAD: 0.4570 sec.

Package used (Python/R/Scala/Julia):
Python

## Error Message:
N/A

## Minimum reproducible example
I'm using Deap Learning Studio, I detail the problem [here](https://superuser.com/questions/1451208/deep-learning-studio-only-handling-5-images-per-second)

## Steps to reproduce
Train on the neural net
Observe Cpu cycles with Process Hacker 2 or similar of the python executable using the most memory.

## What have you tried to solve it?

1. Gosh, I wish I knew what was going on inside the DLL. I've tried finicking with the neural net...

**Comment by leleamol** [comment]
@tuskiomi Can you mention which MXNet version you have installed on your system? 
Also a minimum reproducing example will help diagnose the issue.

@mxnet-label-bot add [Windows, Pending Requester Info, Performance]
