### ISSUE TITLE
can't install mxnet-cu101mkl

### ISSUE THREAD

**Issue by LittleFatHero** [apache/incubator-mxnet#15328]
## Description
I install mxnet-cu101mkl using the command *pip install* but a error occured, the error said that no matching distribution found for mxnet-cu101mkl.

## Environment info (Required)
windows 10 professional 1809
minconda

## Package used (Python/R/Scala/Julia):
I'm using python 3.6.8

## Error Message:
 ERROR: Could not find a version that satisfies the requirement mxnet-cu101mkl (from versions: none)  
ERROR: No matching distribution found for mxnet-cu101mkl

## Attention
even though I can't install mxnet-cu101mkl using command *pip install* , I can install mxnet-cu101 easily by using the command *pip install*.

**Comment by marcoabreu** [comment]
Hi,

we currently don't publish pip packages for Windows that frequently. Could you try building MXNet yourself?

**Comment by marcoabreu** [comment]
@szha on https://pypi.org/project/mxnet-cu101/1.4.1/ we state that this package supports Windows. Wasn't there somebody from China who publishes them?

**Comment by szha** [comment]
@yajiedesign is maintaining it.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pip, WIndows, MKL]

**Comment by LittleFatHero** [comment]
> Hi,
> 
> we currently don't publish pip packages for Windows that frequently. Could you try building MXNet yourself?

Thank for answering my question, I would rather to wait for it to be puplished instead of building mxnet by myself.

**Comment by yajiedesign** [comment]
i will fix it

**Comment by LittleFatHero** [comment]
> i will fix it

Thank you very much! When you finish fixing it, please let us know about that. Thank you~~~~

**Comment by bgawrych** [comment]
` pip install mxnet-cu101mkl` already working on windows. @szha can we close this issue?

**Comment by szha** [comment]
@bgawrych thanks!
