### ISSUE TITLE
[numpy] ndarray.reshape accepts a shape as *args

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#15330]
Based on numpy-0622's build

The following codes work in numpy while not mxnet.np

```python
a = np.zeros((2, 3))
a.reshape(3, 2)
```

**Comment by mli** [comment]
@mxnet-label-bot add [numpy]

**Comment by mli** [comment]
This feature is documented in https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html

**Comment by reminisce** [comment]
Fixed by this PR: https://github.com/apache/incubator-mxnet/pull/15332/files#diff-2867f3bd5e893c32c128044e32d821d6R576

**Comment by reminisce** [comment]
Fixed in https://github.com/apache/incubator-mxnet/pull/15332.
