### ISSUE TITLE
[CI] nightly failure test on amp tutorial

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#15355]
One of these PRs between the following commits broke nightly tutorial test on test_amp

First Failure on commit: f44f6cf
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/355/pipeline/

Last success on commit: 4a9e9f6
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/354/pipeline

Possible PRs:
https://github.com/apache/incubator-mxnet/pull/15023
https://github.com/apache/incubator-mxnet/pull/15321
https://github.com/apache/incubator-mxnet/pull/15311
https://github.com/apache/incubator-mxnet/pull/15313
https://github.com/apache/incubator-mxnet/pull/15170
https://github.com/apache/incubator-mxnet/pull/15240

**Comment by vdantu** [comment]
@mxnet-label-bot add [Test, CI]

**Comment by roywei** [comment]
closing in favor of https://github.com/apache/incubator-mxnet/issues/15374
