### ISSUE TITLE
How to make MXNET run faster?

### ISSUE THREAD

**Issue by cyrusbehr** [apache/incubator-mxnet#15363]
Is there any way to make mxnet (with cpp package) run faster (ex strip symbols?).

**Comment by vdantu** [comment]
@mxnet-label-bot add [question]

**Comment by pengzhao-intel** [comment]
Check if there's useful information for you:)
https://mxnet.incubator.apache.org/versions/master/faq/perf.html

**Comment by cyrusbehr** [comment]
Thank you!
