### ISSUE TITLE
[RFC] Add public functions to get list of registered operators and arguments

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#15367]
A seen in this PR:

https://github.com/apache/incubator-mxnet/pull/15364

It's proposed to add get_all_registered_operators and get_operator_arguments to the Python bindings.

Your feedback is welcome.

**Comment by vdantu** [comment]
@mxnet-label-bot add [Feature Request]

**Comment by larroy** [comment]
https://github.com/apache/incubator-mxnet/pull/15364
