### ISSUE TITLE
Memory leak in Naive engine when profiling

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#15375]
I believe there's a memory leak in Naive engine here:

https://github.com/apache/incubator-mxnet/blob/master/src/engine/naive_engine.cc#L164

I think it would be a great opportunity to refactor how NewOperator is released. As it's also difficult to reason about the release of the operator memory in the threaded engine (looks correct to me, but it takes quite a bit to dig it up and understand).

I would propose returning a unique_ptr directly with a custom deleter using a virtual operator() that is specialized for the engine type which will get the same effect as how operators are being released now. This would make easier to reason about this memory management part.

https://github.com/apache/incubator-mxnet/blob/master/src/engine/threaded_engine.cc#L270

**Comment by vdantu** [comment]
@mxnet-label-bot add [bug]

**Comment by anirudh2290** [comment]
I agree with you about fixing  the memory leak in the NaiveEngine and thanks for raising that. But i disagree about the need to refactor the release of operator memory in the threaded engine. This was a conscious design decision to use Object pool for operator objects which would be manually removed from and added back to the pool. This removal and addition was supposed to be managed by graph executors and other modules that push operators to the engine. If readability is really the issue that is very subjective and  I don't really see the benefit trump the cost here.

**Comment by cjolivier01** [comment]
I agree with Anirudh.

I didn’t write the object pool code, but the reason it was done that way was to
avoid a new/delete operation in-line to the profiling, thus causing profiling to introduce possibly extra locks (and associated heap code), depending on the allocation library used, causing the “Observer Effect”, which is not desired in profiling, of all things. Ideally, the naive engine would use the same mechanism (a better change, imho), but since it’s not used as much for production workloads, I suppose they didn’t think it was worth it to code it.

**Comment by larroy** [comment]
@anirudh2290 I proposed refactoring around a unique_ptr I don't think is going to change the way memory is released, maybe you got a different impression of what I was suggesting to do.

**Comment by larroy** [comment]
@cjolivier01 I didn't understand a word of what you are writing. I'm not proposing to change the object pool, just make NewOp return a smart pointer.

**Comment by anirudh2290** [comment]
@larroy even less encouraging is having you make a PR and then blocking it. I was trying to save you some time. Ownership of the pointer rests with the module that pushes it. So imperative or graph executor should handle it. If you are really keen on doing this do it in the graph executor. There is no need to touch the engine code here.

> Having a pointer released in a call hierarchy 3 levels down leads to bugs and memory leaks, is difficult to reason about it. 

This is the design, Engine relies on object pool for allocation, and the modules depend on engine to handle this, the modules just tell them when it wants a new operator creator or destroyed.
I think the code is very logical and it makes sense to me. Also, the memory leak you found is nowhere related to the ThreadedEngine code.

I considered the benefits of your approach: "readability/understandability" in the first comment.

**Comment by larroy** [comment]
I will make a small fix to the leak in Naive engine, and a separate PR with a refactor, so we can have a more focused and productive conversation then. Thanks for your feedback.

**Comment by larroy** [comment]
@anirudh2290 it makes sense to you because you know the code, I would encourage you to read about the benfits of RAII. This is orthogonal to having an object pool for allocation, which I was not proposing to change.

**Comment by anirudh2290** [comment]
> it makes sense to you because you know the code

So who are you targeting, someone unfamiliar with the code. Everyone needs to spend some time with the code to understand it, but after they spend that time it makes sense.

I know the benefits of RAII, but it doesn't apply to this use case of threaded engine. I am saying there is no need to change threaded engine code here which you are proposing to do. RAII won't benefit here, because engine itself is only responsible for indicating to the object pool that the object has to be deleted. The rest is taken care by the object pool itself. As I said if you really want to add RAII, do it in the graph executor (although I don't think it is really needed there either).

**Comment by larroy** [comment]
Maybe you know the code better and I'm wrong, my proposal was to wrap the operator in a unique_ptr with a custom deleter with a virtual apply operator, so delete doesn't need to be called here:

https://github.com/apache/incubator-mxnet/blob/master/src/engine/threaded_engine.cc#L472

But it will still use the object pool, this wouldn't be changed.

Did I understand correctly that you think this is not possible or that is better to explicitly delete the operator in this case?

The leak would not be in the first place if you would always pass around a smart pointer from the operator, that was my point, maybe I'm missing something which really needs the raw pointer around, but couldn't you pass around a unique_ptr that gets freed from the pool when needed? having the pointer deleted manually is not exactly exception safe.

**Comment by anirudh2290** [comment]
First when you talk about leak, you talk about naive, which does things differently from threaded.

Coming to threaded, What will be the scope and lifetime of the unique_ptr, that you will be creating, how will dependency engine know when it has to be deleted ? It has individual view of operators not the full graph view.

I have spent a lot of time here, having this discussion, on something that hardly adds any value. I have said all I have to say.

**Comment by larroy** [comment]
> I have spent a lot of time here, having this discussion, on something that hardly adds any value. I have said all I have to say.

Hi @anirudh2290 
I don't think this is very constructive to conclude your reply with that, if you are asking questions. I was trying to understand your point and explain my proposal. If you don't have time to followup, no need to start a discussion in the first place. I just made a suggestion on this ticket to prevent similar kinds of leaks in other places using this code. I respect that you have your own opinion, but for me having unmanaged pointers in many places with a complex delete pattern is creating an environment when reasoning about the code is hard and prone to bugs. Saying that something hardly adds any value is not very constructive if you don't try to understand the problem first. Cheers.

**Comment by anirudh2290** [comment]
Okay, I will say it again: the leak is in naive engine and not the threaded engine. Also, let me say again for the threaded engine, there is no problem here. I would request you to spend time fixing some real issues that mxnet has. 

I am going to close this issue, please feel free to open a new one for the naive engine memory leak.

**Comment by larroy** [comment]
Did you read the title of the issue? Why are you closing this? it says the leak is in the NaiveEngine when profiling.

**Comment by anirudh2290** [comment]
This thread has been derailed a lot from the original issue and the whole discussion has been about threaded engine where there is no issue. I will keep this closed, feel free to open a new issue and keep the discussion focused to naive engine.

**Comment by larroy** [comment]
Attaching valgrind run which shows the leaked memory.

![naive_engine_leak](https://user-images.githubusercontent.com/928489/60377426-c12eee80-99cb-11e9-81fc-a15ffb71a799.png)

**Comment by larroy** [comment]
[valgrind.txt](https://github.com/apache/incubator-mxnet/files/3341240/valgrind.txt)
