### ISSUE TITLE
language Model

### ISSUE THREAD

**Issue by SibtainRazaJamali** [apache/incubator-mxnet#15372]
does Mxnet deepspeech model supports language model(kenlm) based decoding?

**Comment by vdantu** [comment]
@mxnet-label-bot add [question]

**Comment by lanking520** [comment]
@Soonhwan-Kwon

**Comment by Soonhwan-Kwon** [comment]
No it does not but we did implemented kenlm based decoding with similar project.

**Comment by SibtainRazaJamali** [comment]
@Soonhwan-Kwon which project?
