### ISSUE TITLE
[R] Fails to build with MKL-DNN on Windows (VS 15 14.16), Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by Crunchy9** [apache/incubator-mxnet#15391]
## Description

I use mxnet with R API , OpenCV works and then error comes:
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

## Build info (Required if built from source)
Compiler (gcc/clang/mingw/visual studio):

Visual Studio 2017 14.16.27023
MKL 2019.4.245
OpenCV 4.1.0
Cmake 3.14.0
R 3.6.0
Rtools 3.5
OpenCV_DIR=C:\build_mxnet\with_mkldnn\opencv\build
MKL_ROOT=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl
PATH=...;C:\Program Files\Git\cmd;C:\build_mxnet\with_mkldnn\opencv\build\x64\vc15\bin;C:\Program Files\CMake\bin

MXNet commit hash: 51acd4d328c6da475c058806565d93bcddee7402

Build config:
cmd x64 Native Tools VS 2017:

c:\build_mxnet\with_mkldnn\incubator-mxnet\build>"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\bin\mklvars.bat" intel64
c:\build_mxnet\with_mkldnn\incubator-mxnet\build>cmake -G "Visual Studio 15 Win64" .. -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_NVRTC=0 -DUSE_OPENCV=1 -DUSE_OPENMP=1 -DUSE_PROFILER=1 -DUSE_BLAS=mkl -DUSE_LAPACK=1 -DUSE_DIST_KVSTORE=0 -DCUDA_ARCH_NAME=All -DUSE_MKLDNN=1 -DCMAKE_BUILD_TYPE=Release -DMKL_ROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl"

(Extracting archive: C:\build_mxnet\with_mkldnn\incubator-mxnet\build\mklml\mklml_win_2019.0.5.20190502.zip)
(Setting MKLROOT path to C:/build_mxnet/with_mkldnn/incubator-mxnet/build/mklml/mklml_win_2019.0.5.20190502) ?

c:\build_mxnet\with_mkldnn\incubator-mxnet\build>msbuild mxnet.sln /p:Configuration=Release;Platform=x64 /maxcpucount

## Error Message:
Start training with 1 devices
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

## Minimum reproducible example
Make R package and  try to start training any network.

## What have you tried to solve it?

1. https://stackoverflow.com/questions/55017740/mxnet-build-with-intel-mkl-always-throw-error-intel-mkl-fatal-error-cannot-loa (doesn't work)
2. https://zhuanlan.zhihu.com/p/58918998 (don't know if I understand properly)

**Comment by pengzhao-intel** [comment]
@yinghu5 @NeoZhangJianyu could you help to take a look for the issue?

@Crunchy9 could you try to read our README and see if the problem can be resolved?
https://mxnet.incubator.apache.org/versions/master/tutorials/mkldnn/MKLDNN_README.html

**Comment by Crunchy9** [comment]
I did. It looks outdated.

**Comment by vdantu** [comment]
@mxnet-label-bot add [question]

**Comment by vdantu** [comment]
@mxnet-label-bot add [R]

**Comment by NeoZhangJianyu** [comment]
@Crunchy9 Several suggestions:
1. remove all of clones of mkl_intel_thread.dll in your PC. You have mentioned that you try to copy them in the folder of EXE in stackoverflow.com.
If you have installed it by Anaconda, try to remove it too.
Only keep a copy of it in your PC.

2. Add folder of mkl_intel_thread.dll in $PATH.

3. Reboot PC and enable the $PATH.

4. If not work, please check the 32/64 issue of EXE and mkl_intel_thread.dll.

**Comment by Crunchy9** [comment]
After `pip uninstall mxnet-mkl`, `conda clean --all` 
`cp "C:\build_mxnet\with_mkldnn\incubator-mxnet\build\Release\libmxnet.dll" D:\R-package\inst\libs\x64
cp "C:\build_mxnet\with_mkldnn\incubator-mxnet\build\mklml\mklml_win_2019.0.5.20190502\lib\mklml.dll" D:\R-package\inst\libs\x64
cp "C:\build_mxnet\with_mkldnn\incubator-mxnet\build\3rdparty\mkldnn\src\Release\mkldnn.dll" D:\R-package\inst\libs\x64`
With `PATH=...;C:\Rtools\bin;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.4.
245\windows\redist\intel64_win\mkl`

I get new error:

> (...) use 4 threads for decoding..
Start training with 1 devices
Error in mx.nd.internal.as.array(nd) : Unknown exception
Calls: mx.model.FeedForward.create ... as.array.MXNDArray -> mx.nd.internal.as.array -> .External
Execution halted
