### ISSUE TITLE
float16 tutorial broken link

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#15409]
URL -  https://mxnet.incubator.apache.org/versions/master/faq/float16.html
Broken Links
─ https://github.com/apache/incubator-mxnet/tree/master/example/image-classificatiIfon/train_imagenet.py (HTTP_404)

TODO: 
Update https://github.com/apache/incubator-mxnet/blob/master/docs/static_site/src/pages/api/faq/float16.md

Find `https://github.com/apache/incubator-mxnet/tree/master/example/image-classificatiIfon/train_imagenet.py` and change to:
`https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/train_imagenet.py`

**Comment by TEChopra1000** [comment]
fixed - will go out with the next link-fixes pull request.

**Comment by TEChopra1000** [comment]
@aaronmarkham this has been fixed. This ticket can be closed.

**Comment by ys2843** [comment]
@aaronmarkham Issue resolved, can we close it? thanks.
