### ISSUE TITLE
[OP] Fix SequenceMask to support different datatypes for data / sequence_length

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#15404]
Currently, the SequenceMask operator does not support different dtypes for data and sequence_length. Usually, we could set data.dtype = np.float32 and sequence_length.dtype = np.int32. However, it's not allowed due to this line: https://github.com/apache/incubator-mxnet/blob/master/src/operator/sequence_mask-inl.h#L220

We should fix it.

**Comment by stephenrawls** [comment]
Hi @sxjscience . I agree this is an annoying issue now, causing you to cast your sequence length tensor to be the same type of your data tensor. I fixed this back in January in this PR: https://github.com/apache/incubator-mxnet/pull/13880

It didn't get merged in time to make it into MXNet 1.4, but it will be in MXNet 1.5 when that release happens. So hang tight :)

Best,
Stephen
