### ISSUE TITLE
data.dmlc.ml redirect (security breach?)

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#15410]
Checking the broken links and found this really weird redirect for anything going to data.dmlc.ml
Goes to iyfnzgb.com... whois on this is hidden but other results indicate mal/adware.

URL -  https://mxnet.incubator.apache.org/model_zoo/index.html
Broken Links
─ http://data.dmlc.ml/mxnet/models/imagenet/caffenet/caffenet-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/nin/nin-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/squeezenet/squeezenet_v1.1-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/vgg/vgg16-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/vgg/vgg19-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/inception-bn/Inception-BN-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/resnet/152-layers/resnet-152-symbol.json (HTTP_400)
─ http://data.dmlc.ml/models/imagenet/resnext/101-layers/resnext-101-64x4d-symbol.json (HTTP_400)

**Comment by aaronmarkham** [comment]
@mli - you might want to check this out...

**Comment by szha** [comment]
@mli told me that he doesn't own the domain name. Also, the domain name probably have expired. All links to data.dmlc.ml should be replaced.

**Comment by aaronmarkham** [comment]
dmlc links have been removed... domain is gone...
