### ISSUE TITLE
documentation link is broken, goes to spam site

### ISSUE THREAD

**Issue by lgoncalves** [apache/incubator-mxnet#15415]
Link to documentation at bottom of README is broken and leads to a spam website

https://dmlc.github.io/MXNet.jl/latest

**Comment by vdantu** [comment]
@lgoncalves : I could'nt find this link on the main README or the docs README. Could you let us know which README has this link? Also, what was this site pointing to previously? 

@mxnet-label-bot add ["Unclear Error/Doc"]

**Comment by vdantu** [comment]
@mxnet-label-bot add [Unclear Error/Doc]

**Comment by lgoncalves** [comment]
The link that is broken is at the bottom of this page :
https://github.com/apache/incubator-mxnet/tree/master/julia

In particular it is the "documentation" link in the last line of the page:

For more details, please refer to the documentation
<https://dmlc.github.io/MXNet.jl/latest> and examples
<https://github.com/apache/incubator-mxnet/blob/master/julia/examples>.


"documentation"  points to https://dmlc.github.io/MXNet.jl/latest ,
but it ends up being forwarded to
http://iyfnzgb.com/?pid=9PO1H9V71&dn=dmlc.ml
perhaps it was hacked?

**Comment by lanking520** [comment]
Find it! 
```
julia/README.md
77:[documentation](https://dmlc.github.io/MXNet.jl/latest) and [examples](examples).
```
@aaronmarkham let's get rid of that

**Comment by aaronmarkham** [comment]
The biggest issue with this domain going away is where do we point to now? Where's the Julia documentation going to live now? And all the model files that were on data.dmlc.io? I find it odd that there's just a sort of shrug that the domain is gone. If it were my domain, I'd make some effort to recover it. Anyway, none of these links can get updated until we have the docs and models hosted somewhere else.

**Comment by aaronmarkham** [comment]
@iblis17 Can you let me know a bit about gathering the docs artifacts from CI? Since the julia docs are now down, I think it would be a good idea to go ahead and host these locally.

**Comment by iblis17** [comment]
@aaronmarkham If you can get access to a CI worker, there is a dir `/work/mxnet/julia/docs/build`.

>  the julia docs are now down, I think it would be a good idea to go ahead and host these locally.

Actually, it's hosted via GitHub page, I guess the problem is the domain CNAME setting has been pointed to somewhere.

**Comment by aaronmarkham** [comment]
> @aaronmarkham If you can get access to a CI worker, there is a dir `/work/mxnet/julia/docs/build`.
> 
> > the julia docs are now down, I think it would be a good idea to go ahead and host these locally.
> 
> Actually, it's hosted via GitHub page, I guess the problem is the domain CNAME setting has been pointed to somewhere.

I think someone sniped the dmlc domain. So we could just get a new one in there. Do you have access to that host?

**Comment by iblis17** [comment]
> Do you have access to that host?

well, you mean the GitHub repo? yes.

**Comment by iblis17** [comment]
Here: https://github.com/dmlc/MXNet.jl/tree/gh-pages
