### ISSUE TITLE
Clojure NDArray broken link

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15446]
URL -  https://mxnet.incubator.apache.org/versions/master/api/clojure/docs/org.apache.clojure-mxnet.ndarray-api.html
Broken Links
─ https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html%3E (HTTP_404)
─ https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html%3E (HTTP_404)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

URL should be:
-https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

**Comment by IvyBazan** [comment]
URL -  https://mxnet.incubator.apache.org/versions/master/api/clojure/docs/org.apache.clojure-mxnet.symbol-api.html
Broken Links
─ https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html%3E (HTTP_404)
─ https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html%3E (HTTP_404)

**Comment by TEChopra1000** [comment]
These links are not in the docs anymore. @aaronmarkham this ticket can be closed.
