### ISSUE TITLE
perf broken links

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15441]
URL -  https://mxnet.incubator.apache.org/versions/master/faq/perf.html
Broken Links
─ https://github.com/apache/incubator-mxnet/releases/download/1.2.0.rc1/apache-mxnet-src-1.2.0.rc1-incubating.tar.gz (HTTP_404)
─ https://github.com/apache/incubator-mxnet/releases/download/1.2.0.rc1/apache-mxnet-src-1.2.0.rc1-incubating.tar.gz (HTTP_404)
─ https://github.com/apache/incubator-mxnet/releases/download/1.2.0.rc1/apache-mxnet-src-1.2.0.rc1-incubating.tar.gz (HTTP_404)

**Comment by TEChopra1000** [comment]
I removed these links because it is not possible to download those mxnet versions from the public download page: https://github.com/apache/incubator-mxnet/tags. @aaronmarkham I think this ticket can be closed.
