### ISSUE TITLE
C API doxygen broken links

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15447]
URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__attributes.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_0.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__convolution.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_1.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_2.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_3.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_4.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_5.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_6.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_7.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__softmax.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_8.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_9.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__pooling.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_10.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_11.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_7.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__lrn.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_12.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_13.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_14.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__batch__normalization.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_15.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_16.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_17.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_18.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__inner__product.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_19.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__rnn.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_0.png (HTTP_404)

URL -  https://mxnet.incubator.apache.org/versions/master/doxygen/group__c__api__types__generic.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_20.png (HTTP_404)
─ https://mxnet.incubator.apache.org/versions/master/doxygen/form_21.png (HTTP_404)

**Comment by aaronmarkham** [comment]
These are old links. Closing for now... we'll get a newer report with current issues later.
