### ISSUE TITLE
Java broken links

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15444]
URL -  https://mxnet.incubator.apache.org/tutorials/java/ssd_inference.html
Broken Links
─ https://mxnet.incubator.apache.org/api/java/index.md (HTTP_404)
─ https://mxnet.incubator.apache.org/tutorials/index.md (HTTP_404)

**Comment by TEChopra1000** [comment]
@aaronmarkham all of the links on the Java SSD Inference tutorial (now found [here](https://mxnet.incubator.apache.org/api/java/docs/tutorials/ssd_inference)) have been fixed. This ticket can be closed.
