### ISSUE TITLE
transforms broken link

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15442]
URL -  https://mxnet.incubator.apache.org/tutorials/gluon/transforms.html
Broken Links
─ https://mxnet.incubator.apache.org/versions/master/tutorials/gluon/[%60CIFAR10%60](https:/mxnet.incubator.apache.org/api/python/gluon/data.html?highlight=cifar#mxnet.gluon.data.vision.datasets.CIFAR10) (HTTP_404)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
URL should be:

https://mxnet.incubator.apache.org/api/python/gluon/data.html?highlight=cifar#mxnet.gluon.data.vision.datasets.CIFAR10

**Comment by TEChopra1000** [comment]
I think that this page is no longer in the current repo. @aaronmarkham if you this is correct we can close this ticket.
