### ISSUE TITLE
CPP broken link

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15443]
URL -  https://mxnet.incubator.apache.org/tutorials/c%2B%2B/mxnet_cpp_inference_tutorial.html
Broken Links
─ https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/inference/inception_inference.cpp (HTTP_404)

**Comment by TEChopra1000** [comment]
All of the links have been fixed in this [tutorial](https://mxnet.incubator.apache.org/api/cpp/docs/tutorials/cpp_inference). @aaronmarkham this ticket can be closed.
