### ISSUE TITLE
MXNet export broken link

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15445]
URL -  https://mxnet.incubator.apache.org/tutorials/onnx/export_mxnet_to_onnx.html
Broken Links
─ http://data.mxnet.io/models/imagenet/ (HTTP_404)

**Comment by IvyBazan** [comment]
@mxnet-label-bot add Website

**Comment by TEChopra1000** [comment]
[Here](https://mxnet.incubator.apache.org/api/python/docs/tutorials/deploy/export/onnx.html) is the page on the current version of the site. 

This is not actually a broken link. If you run the tutorial, this path + the files paths, the command works. @aaronmarkham you can close this ticket.
