### ISSUE TITLE
Failed to compile plugin warpctc

### ISSUE THREAD

**Issue by nopattern** [apache/incubator-mxnet#15472]
## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
----------Python Info----------
Version      : 3.6.8
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'May  7 2019 14:58:50')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 19.1.1
Directory    : /usr/local/lib/python3.6/dist-packages/pip

----------System Info----------
Platform     : Linux-4.4.0-148-generic-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : MS-7817
release      : 4.4.0-148-generic
version      : #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Stepping:              3
CPU MHz:               3598.546
CPU max MHz:           3700.0000
CPU min MHz:           800.0000
BogoMIPS:              6600.45
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3



```

Package used (Python/R/Scala/Julia):
(I'm using Python)

## Build info (Required if built from source)
Compiler (gcc):

MXNet commit hash:
b869ecd65

Build config:
Following the new 'build from source',config.mk has no use now?
(Paste the content of config.mk, or the build command.)

## Error Message:
''' /mxnet/incubator-mxnet/plugin/warpctc/./warpctc-inl.h(257): error: no instance of constructor "mxnet::TShape::TShape" matches the argument list
            argument types are: (int)

1 error detected in the compilation of "/tmp/tmpxft_00002525_00000000-6_warpctc.cpp1.ii".
CMake Error at cuda_compile_generated_warpctc.cu.o.cmake:266 (message):
  Error generating file
  /home/deep/workssd/mxnet/incubator-mxnet/build/CMakeFiles/cuda_compile.dir/plugin/warpctc/./cuda_compile_generated_warpctc.cu.o

CMakeFiles/mxnet_static.dir/build.make:22908: recipe for target 'CMakeFiles/cuda_compile.dir/plugin/warpctc/cuda_compile_generated_warpctc.cu.o' failed
make[2]: *** [CMakeFiles/cuda_compile.dir/plugin/warpctc/cuda_compile_generated_warpctc.cu.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/mxnet_static.dir/all' failed
make[1]: *** [CMakeFiles/mxnet_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
'''

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.cmake -DUSE_PLUGINS_WARPCTC=ON  ..
2.make

## What have you tried to solve it?
old version 1.3.1 is good by using config.mk
0.building Baidu warpctc successfully .
1.config by cmake-gui 
2.set WARPCTC_INCLUDE WARPCTC_LIB_DEBUG WARPCTC_LIB_RELEASE

**Comment by kkurni** [comment]
I also get the same error on v1.5.x branch

/incubator-mxnet/build# cmake -DUSE_PLUGINS_WARPCTC=ON ..

```
CMake Error at CMakeLists.txt:740 (target_link_libraries):
  The "debug" argument must be followed by a library.
```

Here is the error line.
https://github.com/apache/incubator-mxnet/blob/v1.5.x/CMakeLists.txt#L740-L741

Does it requires different parameter?

**Comment by nopattern** [comment]
you can try the old compiling method of 1.3.1.That worked for me.

**Comment by kkurni** [comment]
Do you mean, I can only build the warpctc with make instead?

make -j$(nproc) USE_OPENCV=0 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_MKLDNN=0 WARPCTC_PATH=${WARP_CTC_DIR}/warp-ctc MXNET_PLUGINS+=plugin/warpctc/warpctc.mk

**Comment by nopattern** [comment]
yes ,I think that worked.

**Comment by ThomasDelteil** [comment]
@larroy any idea how to fix it with cmake ?

**Comment by leezu** [comment]
You need to set the path to the warpctc include and lib:

`cmake -GNinja -DUSE_PLUGINS_WARPCTC=1 -DWARPCTC_INCLUDE=/tmp/warp-ctc/include -DWARPCTC_LIB=/tmp/warp-ctc/build/libwarpctc.so ..; ninja`
