### ISSUE TITLE
dmlc.lib is not generated

### ISSUE THREAD

**Issue by smissan** [apache/incubator-mxnet#15514]
when trying to build latest head, dmlc.dll is being generated, but not dmlc.lib (using ms visual studio 2015). Therefore, building mxnet dll fails with

1>------ Build started: Project: mxnet, Configuration: Release x64 ------
1>LINK : fatal error LNK1181: cannot open input file '3rdparty\dmlc-core\Release\dmlc.lib'

**Comment by frankfliu** [comment]
@mxnet-label-bot add [build]
