### ISSUE TITLE
Pybind11 license issue from onnx tensorrt

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#15547]
follow up on 1.5.0 release vote discussion on @general:https://mail-archives.apache.org/mod_mbox/incubator-general/201907.mbox/%3Cpony-fd9da504b63c1736e52a84ae954da2a315f2f28a-abe0ddab200aaebfe96f1266ab8118e4927ddc8b%40general.incubator.apache.org%3E

We need to evaluate whether we can include the following license:
3rdparty/onnx-tensorrt/third_party/onnx/third_party/pybind11/LICENSE

I have created a LEGAL JIRA issue here: https://issues.apache.org/jira/browse/LEGAL-468

**Comment by vrakesh** [comment]
@mxnet-label-bot add [ONNX]

**Comment by vrakesh** [comment]
@mxnet-label-bot  add [Licenses]

**Comment by roywei** [comment]
https://issues.apache.org/jira/browse/LEGAL-468 is closed as the latest Pybind11 license is permissive. But we need to ask onnx-tensorrt and onnx to update them.

@KellenSunderland @Caenorst could you guys help?

Thanks

**Comment by ptrendx** [comment]
The latest ONNX-TensorRT (v7.0) contains the onnx commit that has the right LICENSE in pyBind. However, switching to it would first of all require some changes to the way it is called and second of all require matching TensorRT 7, so I would much prefer to do this in 1.7 release and not as the last thing in 1.6.

**Comment by KellenSunderland** [comment]
I'd also propose we do this in the 1.7 release.

**Comment by leezu** [comment]
I think approval needs to be requested at https://issues.apache.org/jira/browse/LEGAL-468 if the borderline-compliant license should be used in the release? 
Currently it seems that both 1.5 release and 1.6rc are not compliant with ASF policy given this license issue?

**Comment by leezu** [comment]
Apache legal didn't have concerns to continue release as is currently. See above linked thread.

**Comment by ciyongch** [comment]
Hi @ptrendx @KellenSunderland is there any update for this license issue? Do you think we can include the fix in the coming v1.7.0 release? Thanks!

**Comment by ciyongch** [comment]
Hi @leezu @roywei , may I have your suggestions for this issue, since it's not a concern for the previous version, so supposes it's also fine to the upcoming 1.7.0 release. Am I right? 
Thanks!

> Apache legal didn't have concerns to continue release as is currently. See above linked thread.

**Comment by ciyongch** [comment]
Hi @ptrendx , I'm reaching you to check if ONNX-TensorRT (v7.0) is still targeting in 1.7.0 release or not? The license concern would be still there with current code base, right? Thanks!

**Comment by szha** [comment]
This has been resolved in https://github.com/apache/incubator-mxnet/pull/18574
