### ISSUE TITLE
Bug in NAG Optimizer

### ISSUE THREAD

**Issue by zhanghang1989** [apache/incubator-mxnet#15543]
Current implementation of NAG is wrong.

**See this PDF for detail in the equations. [nag.pdf](https://github.com/apache/incubator-mxnet/files/3394333/nag.pdf)**

FYI @eric-haibin-lin

**Comment by vrakesh** [comment]
@zhanghang1989  Thanks for reporting this

@mxnet-label-bot add [Optimizer, Bug]
