### ISSUE TITLE
License issues need to be fixed before 1.6 release

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#15542]
I am creating this issue to be tracked and resolved before next release according to the discussion on @general during 1.5.0 release:
https://mail-archives.apache.org/mod_mbox/incubator-general/201907.mbox/%3CCAMbkE7T6wP6ph6qgDkmKfC6wZ0Cj7ajBbHyE-h-67%3DUKDCka0g%40mail.gmail.com%3E

1.  Mention original license for ONNX export module and FindJeMalloc, as we have modified the code and licensed under ASF, need to mention the original license as well 

Our licenses: [ONNX Export Module](https://github.com/apache/incubator-mxnet/blob/master/LICENSE#L458) and [FindJeMalloc.cmake](https://github.com/apache/incubator-mxnet/blob/master/LICENSE#L659),
ONNX Export original: https://github.com/NVIDIA/mxnet_to_onnx/blob/master/LICENSE
FindJeMalloc original: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/FindJemalloc.cmake

2. Following licenses are missing, need to be added, they are all permissive licenses
- [x]  /3rdparty/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/FindPythonLibsNew.cmake
- [x]  /src/operator/contrib/erfinv-inl.h
- [x]  /3rdparty/nvidia_cub/test/mersenne.h
- [x]  /3rdparty/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/FindEigen3.cmake
- [x]  /3rdparty/onnx-tensorrt/third_party/onnx/tools/protoc-gen-mypy.py
- [x]  /src/operator/special_functions-inl.h
- [x]  /3rdparty/tvm/3rdparty/rang/LICENSE

**Following are nonpermissive license issues  tracked separately:** 

3.  Cub license issue tracked separately here; https://github.com/apache/incubator-mxnet/issues/15569
4. MKLDNN license issue tracked  https://github.com/apache/incubator-mxnet/issues/15544
5. Pybind license issue https://github.com/apache/incubator-mxnet/issues/15547

6.  Lastly, we have images in our source release, we need to identify and add their license or replace them.

- [x] ./contrib/clojure-package/examples/infer/objectdetector/images/marcel.jpg
- [x] ./contrib/clojure-package/test/test-images/Pug-Cookie.jpg
- [x] ./contrib/clojure-package/test/test-images/kitten.jpg
- [x] ./julia/examples/imagenet/ijulia-pretrained-predict/cat.png

more details [on general list](https://lists.apache.org/thread.html/b8768121d9609912c8e8333d12241f996104753dcba71c5062f1113b@%3Cgeneral.incubator.apache.org%3E)

**Comment by roywei** [comment]
@Roshrini any idea why we have a different license than the one on NVIDIA? maybe they changed the license after we used it?

**Comment by vrakesh** [comment]
@mxnet-label-bot add [ONNX]

**Comment by roywei** [comment]
@mxnet-label-bot add [Licenses]

**Comment by pengzhao-intel** [comment]
We will update MKL-DNN 1.0 in the next release and no MKLML is needed again.

**Comment by TaoLv** [comment]
@roywei do you happen to know any updates for these license issues?

**Comment by roywei** [comment]
@gigasquid @adc17 @iblis17 could you help replace the images mentioned in 6 in the issue? We would like to fix them for 1.5.1 release.
Thanks!

**Comment by iblis17** [comment]
well, I'm not sure the source of  `./julia/examples/imagenet/ijulia-pretrained-predict/cat.png`.
@pluskid Can you recall that ?

**Comment by gigasquid** [comment]
License issues have been fixed for the Clojure package and 1.5 branch - see https://github.com/apache/incubator-mxnet/pull/15828 for details

**Comment by roywei** [comment]
Closing as we have open issue tracking the remaining pybind and cub license. everything else is resolved.
