### ISSUE TITLE
Is there whl about mxnet-cu100 on windows ?

### ISSUE THREAD

**Issue by paul777chen** [apache/incubator-mxnet#15628]
There is whl on https://pypi.org/project/mxnet-cu100mkl/. I want to install mxnet on windows through whl. Is there a file about it ?

**Comment by zachgk** [comment]
We have one for MXNet version 1.4.1(https://pypi.org/project/mxnet-cu100mkl/1.4.1/#files). You can install it with:
```
pip install mxnet-cu100mkl==1.4.1
```
