### ISSUE TITLE
asnumpy() took a lot of time when converting NDARRAY into numpy?

### ISSUE THREAD

**Issue by DeepDuke** [apache/incubator-mxnet#15624]
I  found a strange thing that when I convert `NDARRAY`  into `numpy` for a lot of times,  `asnumpy()`  will took much more time for the first time. When I ran on  gpu:

```import mxnet as mx
from mxnet import nd
import time
with mx.Context(mx.gpu(0)):
	for i in range(10):
		t1 = time.time()
		a = nd.array([14, 15])
		a = a.asnumpy()
		t2 = time.time()
		print('Time:{:.6f}'.format(t2-t1))


The result is:
Time:1.156998
Time:0.000000
Time:0.000997
Time:0.000000
Time:0.000998
Time:0.000000
Time:0.000000
Time:0.000000
Time:0.000000
Time:0.000998
when i ran on cpu , i also get similar result, but it took less time than on gpu. I'm quite confusing about this.

**Comment by wkcn** [comment]
Yes, it is correct. When using GPU context, MXNet need to allocate GPU memory in the first time. After that, MXNet can get the memory allocation from the memory pool, so it takes less time.

It takes more time to allocate GPU memory than allocating CPU memory.

**Comment by DeepDuke** [comment]
Thanks!
