### ISSUE TITLE
Benchmark/opperf on CPU

### ISSUE THREAD

**Issue by chaofanl** [apache/incubator-mxnet#15636]
## Description
I manually test with below mxnet version the op test is successful 
**commit c8a1de429b4ba81c14348db0c04f6d3ea3ec4a17
Author: Aaron Markham <markhama@amazon.com>
Date:   Thu Jul 18 00:12:45 2019 -0700**
but with _eec0fb4eda40f4fb8222a8d93d8face454aead09, 9a1a1028529c91c83f275edb74b272f8ad3dcc3d_ the test failed.

## Environment info (Required)

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-111
Thread(s) per core:    2
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               999.908
CPU max MHz:           3800.0000
CPU min MHz:           1000.0000
BogoMIPS:              5000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27,56-83
NUMA node1 CPU(s):     28-55,84-111
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke spec_ctrl intel_stibp
----------Python Info----------
Version      : 3.6.8
Compiler     : GCC 7.3.0
Build        : ('default', 'Dec 30 2018 01:22:34')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.0.3
Directory    : /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.5.0
Directory    : /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet
Commit hash file "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/COMMIT_HASH" not found. Not installed from pre-built package or built from source.
Library      : ['/home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so', '/home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so', '/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/libmxnet.so']
Build features:
✖ CUDA
✖ CUDNN
✖ NCCL
✖ CUDA_RTC
✖ TENSORRT
✔ CPU_SSE
✔ CPU_SSE2
✔ CPU_SSE3
✔ CPU_SSE4_1
✔ CPU_SSE4_2
✖ CPU_SSE4A
✔ CPU_AVX
✖ CPU_AVX2
✖ OPENMP
✖ SSE
✔ F16C
✖ JEMALLOC
✖ BLAS_OPEN
✖ BLAS_ATLAS
✔ BLAS_MKL
✖ BLAS_APPLE
✖ LAPACK
✔ MKLDNN
✔ OPENCV
✖ CAFFE
✖ PROFILER
✖ DIST_KVSTORE
✖ CXX14
✖ INT64_TENSOR_SIZE
✖ SIGNAL_HANDLER
✖ DEBUG
✖ TVM_OP
----------System Info----------
Platform     : Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.5.1804-Core
system       : Linux
node         : mlt-pytorch-skx00
release      : 3.10.0-862.el7.x86_64
version      : #1 SMP Fri Apr 20 16:44:24 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 5.0509 sec, LOAD: 4.2777 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0290 sec, LOAD: 2.6436 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0421 sec, LOAD: 7.2299 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0474 sec, LOAD: 3.5120 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0284 sec, LOAD: 20.1918 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 5.1155 sec, LOAD: 5.1667 sec.

```

Package used (Python/R/Scala/Julia):
(I'm using Python)
1.Python version: python3.68

## Build info (Required if built from source)

Compiler :gcc 5.3.1

MXNet commit hash:
309659d1275f70571201cd1e7a2efa802bb5af96 

Build config:
(Paste the content of config.mk, or the build command.)

make -j USE_MKLDNN=1 USE_BLAS=mkl USE_OPENCV=1 USE_GPERFTOOLS=0

## Error Message:
(Paste the complete error message, including stack trace.)
Error message:
INFO:root:Complete Benchmark - random_negative_binomial
INFO:root:Begin Benchmark - random_normal
INFO:root:Complete Benchmark - random_normal
Traceback (most recent call last):
  File "benchmark/opperf/opperf.py", line 157, in <module>
    sys.exit(main())
  File "benchmark/opperf/opperf.py", line 142, in main
    final_benchmark_results = run_all_mxnet_operator_benchmarks(ctx=ctx, dtype=dtype)
  File "benchmark/opperf/opperf.py", line 73, in run_all_mxnet_operator_benchmarks
    mxnet_operator_benchmark_results.append(run_mx_random_sampling_operators_benchmarks(ctx=ctx, dtype=dtype))
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/nd_operations/random_sampling_operators.py", line 60, in run_mx_random_sampling_operators_benchmarks
    mx_random_sample_op_results = run_op_benchmarks(mx_random_sample_ops, dtype, ctx, warmup, runs)
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/utils/benchmark_utils.py", line 127, in run_op_benchmarks
    warmup=warmup, runs=runs)
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/utils/benchmark_utils.py", line 109, in run_performance_test
    benchmark_result = _run_nd_operator_performance_test(op, inputs, run_backward, warmup, runs, kwargs_list)
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/utils/benchmark_utils.py", line 54, in _run_nd_operator_performance_test
    _, _ = benchmark_helper_func(op, warmup, **kwargs_list[0])
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/utils/profiler_utils.py", line 169, in profile_it
    res = func(*args, **kwargs)
  File "/home/mxnet/workspace/source/intel-mxnet/benchmark/opperf/utils/ndarray_utils.py", line 79, in nd_forward_and_profile
    res = op(*args, **kwargs)
  File "<string>", line 59, in random_pdf_dirichlet
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:07:10] src/c_api/../imperative/imperative_utils.h:369: Check failed: num_inputs == infered_num_inputs (1 vs. 2) : Operator _random_pdf_dirichlet expects 2 inputs, but got 1 instead.
Stack trace:
  [bt] (0) /home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2b) [0x7f40c979003b]
  [bt] (1) /home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so(mxnet::imperative::SetNumOutputs(nnvm::Op const*, nnvm::NodeAttrs const&, int const&, int*, int*)+0x1fd) [0x7f40cc742d5d]
  [bt] (2) /home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so(MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**)+0x403) [0x7f40cc740fe3]
  [bt] (3) /home/mxnet/workspace/source/intel-mxnet/lib/libmxnet.so(MXImperativeInvokeEx+0x6f) [0x7f40cc74169f]
  [bt] (4) /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f40dd8fbec0]
  [bt] (5) /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f40dd8fb87d]
  [bt] (6) /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f40ddb11ede]
  [bt] (7) /home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7f40ddb12915]
  [bt] (8) python(_PyObject_FastCallDict+0x8b) [0x55cf5544d92b]

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.export PYTHONPATH=$PYTHONPATH:/path/to/mxnet/code/
2.  python benchmark/opperf/opperf.py --output-format json --output-file mxnet_operator_benchmark_results.json

## What have you tried to solve it?

no

**Comment by sandeep-krishnamurthy** [comment]
cc: @ChaiBapchya
