### ISSUE TITLE
Packages with Scala classes should end with Scala major release version

### ISSUE THREAD

**Issue by vkorenev** [apache/incubator-mxnet#15633]
Different major Scala releases (e.g. 2.11 and 2.12) are binary incompatible. There is a convention supported by sbt and other build tools that a Scala package with classes should end with underscore and major Scala version used to compile it. In addition to indicating the compatible Scala version, this allows versions of the same package compiled for different Scala versions to be stored at the same repository without interfering with each other.

The current Maven build produces `mxnet-full_2.11` package which follows this convention. However, `mxnet-core` and `mxnet-infer` also contain classes compiled form Scala code, but they do not have `_2.11` at the end.

MXNet commit hash: `77254f2a829d481d61e015e900923f1edb4af39f`.

**Comment by keerthanvasist** [comment]
@mxnet-label-bot add [build, Scala]

**Comment by zachgk** [comment]
The mxnet-core and mxnet-infer are not released. We use the maven-assembly-plugin to combine all of the modules from development into the full jar and then we only release the full jar. Do the other modules not ending in _2.11 cause problems when you install it locally?

**Comment by vkorenev** [comment]
So the problem is different. Both `mxnet-core` and `mxnet-infer` are not supposed to be imported from outside, but they are pulled as dependencies of `mxnet-full`, which is installed to the local repo by `mvn install` (#15634).
