### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by 666xiaohei666** [apache/incubator-mxnet#15647]
(retinaface) root@docker20:/data2/yanmengkai/face/RetinaFace# pip install mxnet                                                                                                                                                       
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: mxnet in /root/anaconda3/lib/python3.7/site-packages (1.5.0)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /root/anaconda3/lib/python3.7/site-packages (from mxnet) (1.16.4)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /root/anaconda3/lib/python3.7/site-packages (from mxnet) (0.8.4)
Requirement already satisfied: requests<3,>=2.20.0 in /root/anaconda3/lib/python3.7/site-packages (from mxnet) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /root/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.20.0->mxnet) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /root/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.20.0->mxnet) (1.23)
Requirement already satisfied: idna<2.9,>=2.5 in /root/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.20.0->mxnet) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.20.0->mxnet) (2018.8.24)
(retinaface) root@docker20:/data2/yanmengkai/face/RetinaFace# python                                                                                                                                                                  
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet

Segmentation fault: 11

Stack trace:
(retinaface) root@docker20:/data2/yanmengkai/face/RetinaFace#

**Comment by zachgk** [comment]
Can you please provide some information about your environment?

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

**Comment by ResearchingDexter** [comment]
I runned ```python python diagnose.py```
then printed 
```shell
----------Python Info----------
Version      : 3.6.8
Compiler     : GCC 8.0.1 20180414 (experimental) [trunk revision 259383
Build        : ('default', 'Jan 14 2019 11:02:34')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.1.1
Directory    : /usr/local/lib/python3.6/dist-packages/pip
----------MXNet Info-----------

Segmentation fault: 11

Segmentation fault (core dumped)
```
@zachgk

**Comment by leezu** [comment]
Please uninstall and reinstall mxnet

**Comment by ResearchingDexter** [comment]
It didn't work that uninstall and reinstall mxnet. I reinstall mxnet many times, please help me. @leezu

**Comment by leezu** [comment]
Ok. Then you should uninstall and build from source. Please follow the guide at https://mxnet.apache.org/get_started/ubuntu_setup
If the error persists, add `-DCMAKE_BUILD_TYPE=Debug` instead of `-DCMAKE_BUILD_TYPE=Release` in the `cmake` line.


Your problem could be related to the conda setup. If you don't want to build from source, I suggest you don't use conda and try again to install mxnet with system python.

**Comment by szha** [comment]
Let's track segmentation fault issues in #17043
