### ISSUE TITLE
Website installation issue

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#15642]
https://mxnet.apache.org/versions/master/install/index.html?platform=Linux&language=Python&processor=CPU&prev=v1.2.1&prev=v1.3.1

1.4.0 installation is showing up on 1.4.1 and master version

version 1.4.1:
$ pip install mxnet
$ pip install mxnet==1.4.0

version master:
https://mxnet.apache.org/versions/master/install/index.html?platform=Linux&language=Python&processor=CPU&prev=v1.2.1&prev=v1.3.1&version=master#

$ pip install mxnet==1.4.0
$ pip install mxnet --pre
MKL-DNN enabled pip packages are optimized for Intel hardware. You can find performance numbers in the MXNet tuning guide.

$ pip install mxnet-mkl --pre

**Comment by roywei** [comment]
cc @aaronmarkham @IvyBazan @eric-haibin-lin

**Comment by keerthanvasist** [comment]
@mxnet-label-bot add [installation, doc]

**Comment by aaronmarkham** [comment]
Looks like 1.4.0 being in there is just a typo and changing to 1.4.1 would be a quick fix.

According to the selector's normal logic `pip install mxnet --pre` should only show up when master is selected. Showing up when selecting a different version means there's probably a bug in options.js. Or the install page is slightly messed up which then causes the js to break. 
Refactoring the install page has been needed for a really long time. It's a front-end js issue more than anything.

**Comment by roywei** [comment]
Two steps are used during website build:
1. build_all_versions.sh
2. update_all_versions.sh 
Reference: https://cwiki.apache.org/confluence/display/MXNET/Production+Website+Build+Pipeline
Current findings, 'pip install mxnet==1.4.0' is wrongly injected into the installation page by update_all_versions. It would appear event if we remove all appearance of such text, so it injected by checking out old release branches (1.4.x, 1.5.x).

**Comment by eric-haibin-lin** [comment]
is this fixed?

**Comment by aaronmarkham** [comment]
Yes, it's fixed.
