### ISSUE TITLE
1.5.0 Scala package missing from Maven Central

### ISSUE THREAD

**Issue by barumrho** [apache/incubator-mxnet#15650]
## Description
Scala packages for 1.5.0 are missing on Maven Central.
https://search.maven.org/search?q=g:org.apache.mxnet

Looking at this PR (https://github.com/apache/incubator-mxnet/pull/13626) it looks like some changes were made on how Scala package is built. Is this related to the packages not being published?

One follow up question: When installing from source, the version is set to `INTERNAL`, is there an easy way to set the version to 1.5.0? (`mvn versions:set -DnewVersion=1.5.0` seems to work, but I'm not sure if this will lead to any issues.)

**Comment by zachgk** [comment]
@barumrho The scala package has not been released yet. @lanking520 and I are currently working on it. We need to have other committers verify the release which takes a bit, but I'll let you know when we get it out.

To change the version, you could update the version in `scala-package/assembly/pom.xml`. You could also run `mvn deploy -Drepo_url=file://$HOME/.m2/repository` and that would give you 1.5.0-SNAPSHOT.  Add `-Drevision=1.5.0` if you want to use a specific version.

**Comment by zachgk** [comment]
@barumrho 1.5.0 is now released on Maven central
