### ISSUE TITLE
Using openblas

### ISSUE THREAD

**Issue by gogazago** [apache/incubator-mxnet#15652]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)
Clearlinux 
incubator-mxnet 1.5.0 
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. compiling with USE_BLAS as openblas,
2. on 1.5.0 version don't we need to change use_blas on Makefile?
open to openblas?

## What have you tried to solve it?

1. change Makefile, open to openblas on line 247
2.

**Comment by zachgk** [comment]
We have it as a switch (see https://github.com/apache/incubator-mxnet/blob/master/Makefile#L255). You should have USE_BLAS=open to use openblas

**Comment by gogazago** [comment]
so can we ignore openblas  on 
https://github.com/apache/incubator-mxnet/blob/master/Makefile#L217 ?

Thanks,
Sean.

**Comment by zachgk** [comment]
I might be wrong. @larroy Can you take a look?

**Comment by larroy** [comment]
What's the question exactly?  The description on the ticket is not clear.

**Comment by zachgk** [comment]
When you build with make and want to set it to openblas, do you use `USE_BLAS=open` or `USE_BLAS=openblas`?  https://github.com/apache/incubator-mxnet/blob/master/Makefile#L255 seems to indicate it should be `open` while https://github.com/apache/incubator-mxnet/blob/master/Makefile#L217 seems to indicate `openblas`

**Comment by larroy** [comment]
Yes, this seems to be wrong.

**Comment by larroy** [comment]
@mxnet-label-bot add [Bug]
