### ISSUE TITLE
Can you give me a UpSampling's doc?  'bilinear'!!

### ISSUE THREAD

**Issue by ngunauj** [apache/incubator-mxnet#15656]
```
F.UpSampling(x[2], scale=4, sample_type='bilinear', num_args=1) error
it needs weight. but i don't know how to set......

```

**Comment by kshitij12345** [comment]
There seems to be a problem with the documentation.
https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.UpSampling

It doesn't mention about weight when using `bilinear`.
Digging into the code,
https://github.com/apache/incubator-mxnet/blob/8158ba4b0f1ebd696ec09a0b1aa6031bacb60740/src/operator/nn/upsampling.cc#L123-L173

It mentions about requiring the weight and also gives an example.
I have verified that the example works,
```
from mxnet import nd
x = nd.ones((1,3,3,3)) # NCHW
w = nd.ones((3,1,4,4))
upsampled = nd.UpSampling(x, w, scale=2, sample_type='bilinear', num_filter=3)
```

**Comment by ngunauj** [comment]
> The documentation seems to be incomplete.
> https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.UpSampling
> 
> It doesn't mention about weight when using `bilinear`.
> Digging into the code,
> https://github.com/apache/incubator-mxnet/blob/8158ba4b0f1ebd696ec09a0b1aa6031bacb60740/src/operator/nn/upsampling.cc#L123-L173
> 
> It mentions about requiring the weight and also gives an example.
> I have verified that the example works,
> 
> ```
> from mxnet import nd
> x = nd.ones((1,3,3,3)) # NCHW
> w = nd.ones((3,1,4,4))
> upsampled = nd.UpSampling(x, w, scale=2, sample_type='bilinear', num_filter=3)
> ```

ok  i will try..try Thanks

**Comment by ngunauj** [comment]
> The documentation seems to be incomplete.
> https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.UpSampling
> 
> It doesn't mention about weight when using `bilinear`.
> Digging into the code,
> https://github.com/apache/incubator-mxnet/blob/8158ba4b0f1ebd696ec09a0b1aa6031bacb60740/src/operator/nn/upsampling.cc#L123-L173
> 
> It mentions about requiring the weight and also gives an example.
> I have verified that the example works,
> 
> ```
> from mxnet import nd
> x = nd.ones((1,3,3,3)) # NCHW
> w = nd.ones((3,1,4,4))
> upsampled = nd.UpSampling(x, w, scale=2, sample_type='bilinear', num_filter=3)
> ```

ok i will try..try Thanks @kshitij12345

**Comment by ngunauj** [comment]
ok i solve it by conv2Dtranspose

**Comment by kshitij12345** [comment]
@zachgk Should this be kept open till the documentation is fixed?

**Comment by zachgk** [comment]
Yeah, we can leave this issue to fix the docs. @kshitij12345, do you want to fix it?

**Comment by kshitij12345** [comment]
@ngunauj Would you like to take it?
Otherwise I will.

**Comment by vuvko** [comment]
seems related https://github.com/apache/incubator-mxnet/issues/13953
