### ISSUE TITLE
Straggler in latest mxnet when training with distributed parameter server

### ISSUE THREAD

**Issue by YouhuiBai** [apache/incubator-mxnet#15674]
## Description
Hi, I found that there is a strange straggler in current newest mxnet when training CNN using distributed parameter server architecture (BSP model) and GPU, it is a special worker whose `rank == 0`. I think it is a bug of mxnet , because I deployed mxnet in hemogeneous environment means that every participated machine has the same hardware and software environment as follows, and the straggler still existed even I changed the number of workers or physical machine like running at AWS. 

## Environment info (Required)

```
system version：CentOS 7.5.1804
kernel version：3.10.0-862.9.1.el7.x86_64
cuda version：cuda_9.2.148
cudnn version：cudnn-9.2-linux-x64-v7.1
nvidia driver version：396.37
GPU: GeForce GTX 1080 Ti
NIC: 10GE

```
Software and parameters:
```
parameter server architecture: m servers n workers, n >= m and each role locates on different physical machine
application: image classification
database: Imagenet 2012
CNN model: inception-v4, lenet, resnet, etc.
GPU usage: one physical GPU per worker
scaling model: strong scaling
consistency model: BSP
```

## what is a straggler?
When I start training with above environment and parameter set up, and did some break down in the critical path, found that a worker's behavior is strange. In BSP consistency model of parameter server, the server would not execute response of one key for push operations unless receiving updates from all workers to the same key, we found that there was a slower worker, always waited by other workers every iteration, it is the straggler. The straggler has other features:

1. rank == 0, the first worker
2. higher CPU usage
3. higher CPU memory throughput
4. higher GPU usage
5. cost more time when calling cudamemcopy
6. higher LLC miss rate
7. lower CPU memory occupancy

It's very very strange. Thanks a lot.

**Comment by YouhuiBai** [comment]
The reason for the straggler is the reutilization of pageable memory.

There is an unorder map int to NDArray comm_buf_ (class KVStoreDist, in kvstore_dist.h), if the compression isn't active, this buffer store the data in pull and push, namely, push pull will share the buffer. When start the distributed kvstore, the first worker whose rank number is zero will push all keys of the model to server(s), and initialize the comm_buf_ with pageable allocated memory (in push_ function of KVStoreDist), then all workers pull keys from server(s) ultil the first worker's push operations have been done, and initialize the comm_buf_ with new allocated pinned (page-locked) memory. As we can see, the comm_buf_ of first worker is different from others', and the memory copy between CPU and GPU is very different with pinned memory or pageable memory at host, the details are in https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/. This discovery will explain all the strange point above, and you can just allocate new pinned memory for comm_buf_ of first worker, the straggler will be eliminated.

**Comment by sandeep-krishnamurthy** [comment]
FYI - @apeforest @yuxihu

**Comment by YouhuiBai** [comment]
@apeforest I think it's probably not related to the Dataloader,  the pinned memory is used at worker to communicate with server through parameter server, all the workers use the pinned memory except the worker whose rank id is zero.

**Comment by apeforest** [comment]
@YouhuiBai Thanks for the explanation.When you say "current newest mxnet" has straggler, are you   implying there was no such behavior before? If so, do you remember the last working version? I can do a trace back to see which PR introduced this.

**Comment by YouhuiBai** [comment]
@apeforest Very sorry, I forgot to check the gmail because it is uncommonly used. I used branch 1.5.0 ("current newest mxnet" as I said), and checked from version 1.0.0 to `master` branch, there is straggler. What can we do is just allocate the pinned memory for `comm_buf` rather than reuse the `merged`, which is pageable memory. Thanks a lot!
