### ISSUE TITLE
mxnet nd array shape modified with benchmark ??

### ISSUE THREAD

**Issue by mycpuorg** [apache/incubator-mxnet#15684]
## Description
mxnet + pytest benchmark introducing errors in nd array shapes?

## Environment info (Required)
EC2 instance for Ubuntu MXNet AMI
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 7.2.0
Build        : ('default', 'Apr 29 2018 16:14:56')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.2.1
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.4.0
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet
Commit Hash   : a03d59ed867ba334d78d61246a1090cd1868f5da
Library      : ['/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so']
Build features:
No runtime build feature info available
----------System Info----------
Platform     : Linux-4.4.0-1085-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-30-250
release      : 4.4.0-1085-aws
version      : #96-Ubuntu SMP Tue Jun 11 09:08:32 UTC 2019
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2699.894
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.17
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0017 sec, LOAD: 0.4541 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1464 sec, LOAD: 0.4580 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.2039 sec, LOAD: 0.4501 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0161 sec, LOAD: 0.2410 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0248 sec, LOAD: 0.2532 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0244 sec, LOAD: 0.0914 sec.

```

Package used (Python/R/Scala/Julia):
I'm using Python

## Error Message:

I'm trying to run pytest benchmark on an application that uses mxnet backend.
I'm running the application: https://github.com/apache/incubator-mxnet/blob/master/example/recommenders/demo1-MF.ipynb
Specifically, I want to benchmark the calls to train() function (in the notebook)
```
def my_train()
    train(net1, train_data, test_data, 15, 1, ctx)

my_train()
```
Without the benchmark things run OK with pytest.

However, the calls to train with benchmark()
```
def my_train()
    train(net1, train_data, test_data, 15, 1, ctx)

benchmark(my_train)
```
throws the following errors:

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)
I'm trying to run pytest benchmark on an application that uses mxnet backend.
I'm running the application: https://github.com/apache/incubator-mxnet/blob/master/example/recommenders/demo1-MF.ipynb

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Download the above example
2. pip install pytest-benchmark
3. Code pasted above

## What have you tried to solve it?

1. I have tried to replace all reshape calls with mxnet.nd.reshape() because it was earlier mentioned in a similar sounding issue: https://github.com/apache/incubator-mxnet/issues/9693#issuecomment-364565215

**Comment by vrakesh** [comment]
@mycpuorg thanks for posting the issue, could you elaborate more on the errors being reported, I do not see a trace in the original post
@mxnet-label-bot add [Pending Requester Info]

**Comment by mycpuorg** [comment]
I figured the problem out. Posting this for posterity.

Do not use pytest-benchmark in cases where your training function is not re-entrant. The issue is that pytest-benchmark, by default, performs many rounds and iterations of testing to generate the benchmark results. This is done by spawning many concurrent threads which does not go well with typical training functions.

So, my solution was to use benchmark.pendatic method where you can specify the number of iterations and rounds needed to be tested. Use this method and limit rounds and iterations to 1 each.
