### ISSUE TITLE
An example of multi target prediction?

### ISSUE THREAD

**Issue by oneengineer** [apache/incubator-mxnet#1569]
This issue is highly related to #910 and #270.

Let's say I have 1234 images, so the train data `X` has the shape of (1234,3,32,32).
Instead of a label, each image is related to two float values. Therefore the output `Y` has shape (1234,1,1), or (1234,2).

I want to predict these two float with linearRegression or logisticRegression, or one is linear the other is logistic.

After reading many examples, I still don't know how to write the code.
Can anyone give a hint or an example?

**Comment by firearasi** [comment]
Are you trying to find feature points?
Does that help if the last fully connected layer has two "hidden" nodes?

**Comment by oneengineer** [comment]
@firearasi  That‘s what I want I think. However can `mx.symbol.FullyConnected` be an output layer?

**Comment by piiswrong** [comment]
linear regression supports multi target.
Or you can simply create 2 output layers.

**Comment by firearasi** [comment]
@oneengineer  I think you follow mx.symbol.FullyConnected with a mx.symbol.LinearRegressionOutput

**Comment by Godricly** [comment]
I'm confused with the shape (1234,1,1), or (1234,2).   In my understanding, you are creating two leaf node for a tree and merge them togather later. So I think maybe you can try something like concate ? @piiswrong can you take a look at my question please?[#1551](https://github.com/dmlc/mxnet/issues/1551)
And is there anyway to fetch symbol name in the c++ or python code ?

**Comment by oneengineer** [comment]
@piiswrong 
I tried to use linear regression to predict Y as a vector (e.g. a coordinate like <123.0,45.0> ) instead of a scalar.
With  symbol.bind() function, I can successfully get some output from the symbol.
However, when I try to build a `mx.model.FeedForward` and feed the train data to it,
it throws the error

`
ValueError: Label must be 1D or 2D (with 2nd dimension being 1)
`

It seems the fit function only support Y which has scalar lable instead of ndarray. How can I fix it?
The code is given below:

`
def get_symbol2():
    X = mx.symbol.Variable('X')
    M = mx.symbol.FullyConnected(data=X,num_hidden = 2,name = "M")
    Y = mx.symbol.LinearRegressionOutput(data=M)
    return Y

def work():
    n = 1000
    shape = (n,32,32)
    x = np.random.randint(0,100,shape)
    y = np.random.randint(0,100,(n,2))
    symbol = get_symbol()
    model = mx.model.FeedForward(
        symbol,
        num_epoch=3,
        learning_rate=0.01)

    model.fit(X=x,y = y)

work()
`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
