### ISSUE TITLE
Transpose does not support inplace

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#15709]
## Description

Crash with below code snippet:
```
import mxnet as mx
import numpy as np

a = mx.sym.Variable('a')
b = mx.sym.transpose(a, axes=(1, 0, 2))
c = mx.sym.zeros_like(b)

mod = c.simple_bind(mx.cpu(), a=(3, 4, 5), grad_req='null')
mod.arg_arrays[0][:] = np.random.normal(size=mod.arg_arrays[0].shape)
out = mod.forward(is_train=False)
print(out[0]) 
```

Error message:
```
mxnet.base.MXNetError: [22:56:12] src/operator/tensor/./matrix_op-inl.h:328: Check failed: req[0] == kWriteTo (0 vs. 1) : Transpose does not support inplace
```

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

Reproduce:
pip install mxnet and run the demo case above.

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Feature request]

**Comment by kshitij12345** [comment]
Hi,

I would like to work on this. However I'll need some pointer as to how to go about it or even a reference of other operator which supports this should do.

**Comment by TaoLv** [comment]
Hi @kshitij12345, thank you for looking into this. Your contribution will be highly appreciated!

Actually this is not an in-place issue and the `transpose` operator in MXNet is not designed to support in-place.

From the error log and the check at https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/matrix_op-inl.h#L334, the `req[0]` here is `kNullOp` which means the operator should do nothing before return.

So the logic should look like:
```cpp
if (req[0] == kNullOp) {
  return;
} else {
  CHECK_EQ(req[0], kWriteTo) << "Transpose does not support kWriteInplace or kAddTo";
  // ....
}
```

**Comment by kshitij12345** [comment]
Oh, I see. Thank You for the nice explanation. Will send a PR soon.
