### ISSUE TITLE
Build MXNET to use NaiveEngine by default

### ISSUE THREAD

**Issue by cyrusbehr** [apache/incubator-mxnet#15712]
How can I build mxnet to use `NaiveEngine` by default?

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Question]

**Comment by ZhennanQin** [comment]
@cyrusbehr Yes if you can build from source. Change below line to the engine you want:
https://github.com/apache/incubator-mxnet/blob/9d7fc7cbee09de2694022995d0601cb4316e4988/src/engine/engine.cc#L35

**Comment by cyrusbehr** [comment]
Excellent thank you
