### ISSUE TITLE
Missing nnvm content from DMLC.ML site

### ISSUE THREAD

**Issue by IvyBazan** [apache/incubator-mxnet#15730]
The blog on fusion and runtime compilation for nnvm and tinyflow was hsoted on the dml.ml site and needs to be recovered. 

http://dmlc.ml/2016/11/21/fusion-and-runtime-compilation-for-nnvm-and-tinyflow.html

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Website]

**Comment by ys2843** [comment]
Issue resolved, @IvyBazan could you close it? Thanks
