### ISSUE TITLE
How can I know where is 10th plus node?

### ISSUE THREAD

**Issue by happynear** [apache/incubator-mxnet#15743]
Report error:
Error in operator _plus10: [19:53:35] src/operator/nn/./../tensor/../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)): Incompatible attr in node _plus10 at 1-th input: expected [100,1,3], got [1,100,3]

Where can I find the _plus10? Is there any debug tools?
If I can find the corresponding symbol, I can correct it simply with mx.sym.reshape. But how can I find it?

**Comment by wkcn** [comment]
‘MXNET_ENGINE_TYPE=NaiveEngine python xxx.py’ enable MXNet to execute operators synchronously in single thread. It can be used to debug.

**Comment by happynear** [comment]
Thanks.
