### ISSUE TITLE
UNIX_CPU build failing

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#15758]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/activity

failing consistently

Train MNIST is failing

**Comment by access2rohit** [comment]
@mxnet-label-bot add [CI]

**Comment by wkcn** [comment]
The CI couldn't download the MNIST dataset in `http://data.mxnet.io/mxnet/data/mnist.zip`

**Comment by access2rohit** [comment]
@wkcn yes data.mxnet.io is down

**Comment by access2rohit** [comment]
its fixed now ... closing!
