### ISSUE TITLE
Cross Compile MXNET for RPI 4 with opencv, openmp and DIST_KVSTORE enabled failed

### ISSUE THREAD

**Issue by chhokrad** [apache/incubator-mxnet#15771]
## Description

Need instructions to cross compile mxnet for raspberry pi using docker with opencv, openmp and DIST_KVSTORE enabled. I tried changing build_armv7() function to reflect my options but got the following error.

## Environment info (Required)

Distributor ID: Ubuntu (Virtual Machine)
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

MXNET REPO:  git clone https://github.com/apache/incubator-mxnet.git --branch v1.4.x --recursive

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

MXNet commit hash:
e368ea24895b92f7e6b43fc0a51b3b0131193f12

## Error Message:
CMake Warning at CMakeLists.txt:376 (find_package):
By not providing “FindOpenCV.cmake” in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by “OpenCV”, but
CMake did not find one.

Could not find a package configuration file provided by “OpenCV” with any
of the following names:

OpenCVConfig.cmake
opencv-config.cmake
Add the installation prefix of “OpenCV” to CMAKE_PREFIX_PATH or set
“OpenCV_DIR” to a directory containing one of the above files. If “OpenCV”
provides a separate development package or SDK, be sure it has been
installed.

CMake Error at CMakeLists.txt:379 (find_package):
By not providing “FindOpenCV.cmake” in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by “OpenCV”, but
CMake did not find one.

Could not find a package configuration file provided by “OpenCV” with any
of the following names:

OpenCVConfig.cmake
opencv-config.cmake
Add the installation prefix of “OpenCV” to CMAKE_PREFIX_PATH or set
“OpenCV_DIR” to a directory containing one of the above files. If “OpenCV”
provides a separate development package or SDK, be sure it has been
installed.

## Minimum reproducible example
Changed build_armv7() function in runtime_function.sh as follows:

```
build_armv7() {
    set -ex
    pushd .
    cd /work/build

    # Lapack functionality will be included and statically linked to openblas.
    # But USE_LAPACK needs to be set to OFF, otherwise the main CMakeLists.txt
    # file tries to add -llapack. Lapack functionality though, requires -lgfortran
    # to be linked additionally.

    cmake \
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} \
        -DCMAKE_CROSSCOMPILING=ON \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DCMAKE_C_COMPILER_LAUNCHER=ccache \
        -DUSE_CUDA=OFF \
        -DUSE_OPENCV=OFF \
        -DUSE_OPENMP=OFF \
        -DUSE_DIST_KVSTOTE=ON \
        -DUSE_SIGNAL_HANDLER=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_MKL_IF_AVAILABLE=OFF \
        -DUSE_LAPACK=OFF \
        -DBUILD_CPP_EXAMPLES=OFF \
        -Dmxnet_LINKER_LIBS=-lgfortran \
        -G Ninja /work/mxnet

    ninja -v
    build_wheel
    popd
}

```

**Comment by chhokrad** [comment]
@aaronmarkham

**Comment by aaronmarkham** [comment]
I believe I had issues with `cmake` when working with Nano an Pi. I avoided it and stuck to `make`. You may want to do the same. That being saId, if you're feeling adventurous, why not try one the cmake files found here: https://github.com/opencv/opencv/tree/master/cmake
It would seem you could drop it here: https://github.com/apache/incubator-mxnet/tree/master/cmake/Modules
You may want to set environment vars for the location... like:
`set(OpenCV_DIR=/home/ubuntu/opencv-3.2.0/share/OpenCV)`
I'll be happy to validate what you come up with and update the directions. I don't happen to have a Pi 4 yet, but I'll order one.

**Comment by aaronmarkham** [comment]
@zheng-da might have some insights on this.

**Comment by chhokrad** [comment]
@aaronmarkham  I ended up compiling on the device using make. But had to do couple of more steps as a result of incompatible version of protobuf (2.5.x) installed during building process. The steps are listed in this [link](https://devtalk.nvidia.com/default/topic/1052663/container-mxnet/mxnet-on-jetson-nano-for-multi-machine-not-working/post/5363570/#5363570). 

Please check if _-gencode arch=compute-63, code=sm_62_ in the instructions contains a type as compute-63 gives unsupported architecture error. I was able to get it to compile with _- gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_62,code=sm_62_

PS: I am using MXNET v1.4.x
