### ISSUE TITLE
RuntimeError: Cannot find the MXNet library.

### ISSUE THREAD

**Issue by yzz-cver** [apache/incubator-mxnet#15787]
after 
cd python  
python setup.py install

I have encountered the following problems, please help me.

**Comment by yzz-cver** [comment]
![image](https://user-images.githubusercontent.com/53545589/62668886-252bd600-b9c0-11e9-94e7-2f8aa01df0cf.png)

**Comment by larroy** [comment]
You have to compile the project first. Are you building from source? 
Please follow docs here:

https://mxnet.incubator.apache.org/versions/master/install/build_from_source.html

**Comment by vdantu** [comment]
@mxnet-label-bot add [question]
As @larroy suggested, you would have to build the project first before you install the python package. Or you could use the published PyPi packages, with "pip install".

**Comment by NamTran838P** [comment]
Hello, I got a similar issue on both of my desktop computers. Their specs are:

Windows 8 & 10
Python 3.8

After installing mxnet using the pip install command, I got the following error message when attempting to call 

`import mxnet as mx`

I have made sure that the CUDA version matches the mxnet package that I installed. Please help. Thanks a lot.

![Capture (1)](https://user-images.githubusercontent.com/26189749/70020554-f4a91280-1541-11ea-9f54-e234ccd9c47d.PNG)

**Comment by leezu** [comment]
There are no Python 3.8 builds for Pip yet.
You most likely have some inconsistency where you tried to install MXNet from source for Py3.8 but forgot to compile (as above). And later you installed from pip for a different Python version.

I'll close the issue for now as it is related to not building MXNet when installing from source. Let's track the Py3.8 release separately.

**Comment by leezu** [comment]
You can follow https://mxnet.apache.org/get_started/windows_setup#build-from-source to build for Python 3.8 on Windows.

**Comment by larroy** [comment]
Try setting
MXNET_LIBRARY_PATH 
to the path of the dll

https://mxnet.apache.org/api/faq/env_var

**Comment by RuRo** [comment]
Just in case anyone stumbles on this issue, notice, that `mxnet` expects the `build` directory to be in the root of the repository. So if you are trying to build in a different directory (i.e. in `/tmp` or in a directory adjacent to your cloned `mxnet` repository), the `setup.py` script will fail with the above error.

**Comment by deltawi** [comment]
> Just in case anyone stumbles on this issue, notice, that `mxnet` expects the `build` directory to be in the root of the repository. So if you are trying to build in a different directory (i.e. in `/tmp` or in a directory adjacent to your cloned `mxnet` repository), the `setup.py` script will fail with the above error.
> 
> Unfortunately, setting `MXNET_LIBRARY_PATH` doesn't work for `setup.py`, so I ended up symlinking my `build` directory to where `mxnet` expected it to be.

Hi @RuRo can you give us the command lines you've done. I can't solve this issue...
