### ISSUE TITLE
How to do online learning on MXnet ?

### ISSUE THREAD

**Issue by mindx0** [apache/incubator-mxnet#1584]
Sorry for the naive question, I was looking into API document and couldn't find answer.

For example,
1. We trained  a matrix factorization model for current 1billion rating data.
2. When a new data item acquired,   we want to train the new item a feature vector
3. We don't want to train exiting 1 billion data set from the beginning,  we only want to make very little modifications to trained weights for the new item

What is the best way to do it on MXnet ?

**Comment by freesouls** [comment]
you mean you want to fine tune your model with new data?
for example you have trained your model for 10 epoch
```
python my_train.py --network my_retwork -lr 0.1 --num-epoch 10 --model-prefix my_model
```
now you have new dataset, you just need to add a new parameter like this
```
python my_train.py --network my_retwork -lr 0.1 --num-epoch 10 --model-prefix my_model --load-epoch 10
```
`--load-epoch 10

**Comment by victor128** [comment]
Thank you,  Is it possible to do fine-tune inside the program ?

**Comment by zihaolucky** [comment]
I think @freesouls means continues training on have-seen user/item with pre-trained model, where we use fresh data to update the model/parameter. 

However, is not that obvious to handle those never seen item/user. It should re-allocate the memory, redefine network size and load pre-trained parameters for those have seen.

**Comment by zihaolucky** [comment]
@mindx0 check https://github.com/dmlc/mxnet/pull/1647

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
