### ISSUE TITLE
Is it possible to train Matrix factorization Model on MXnet?

### ISSUE THREAD

**Issue by mindx0** [apache/incubator-mxnet#1586]
In Matrix factorization, There is no input data, only labels,  how to gradient descent on a model have no input data only have labels, multiple  weights  and multiple biases ?

**Comment by victor128** [comment]
The same question with "Sparse Coding"

**Comment by eric-haibin-lin** [comment]
There's matrix factorization example in https://github.com/apache/incubator-mxnet/tree/master/example/recommenders 
Closing it for now due to inactivity. Please feel free to reopen it for followup discussions.
