### ISSUE TITLE
sym.Variable input init need init.dumps(), but NDarray is not JSON serializable

### ISSUE THREAD

**Issue by david-di** [apache/incubator-mxnet#15927]
## Description
mxnet.symbol.Variable(name, attr=None, shape=None, lr_mult=None, wd_mult=None, dtype=None, init=None, stype=None, **kwargs)
The input parameter init, I used mxnet.initializer.Constant(value).
The introduction of Constant class says "Initializes the weights to a given value. The value passed in can be a scalar or a NDarray that matches the shape of the parameter to be set", so I use a NDarray as "value" parameter. 
Now, accident happened......
In class Variable, if init is not an instance of string, init.dumps() will be called.
"dumps" method is implemented in class mxnet.initializer.Initializer, the superclass of Constant.
```
def dumps(self):
  return json.dumps([self.__class__.__name__.lower(), self._kwargs])
```
NDarray  is not JSON serializable...
Crash...

**Comment by abhinavs95** [comment]
@david-di This has been already fixed by #15150 but was merged after 1.5 release. Its not reproducible in latest pip.

Could you try with `pip install mxnet --pre`?
