### ISSUE TITLE
indexing op does not report out of bound indices 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#15933]
out of bound error is reported in numpy: 
```
>>> import numpy as np
>>> np.ones((1,))[[10]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 10 is out of bounds for axis 0 with size 1
>>>
```

but MXNet does not: 

```
>>> import mxnet as mx
>>> mx.nd.ones((1,))[[10]]
[6.4e-44]
<NDArray 1 @cpu(0)>
```

We can reuse the kernel in ` nd.take(mode='raise') ` to report such an error. 

@reminisce @haojin2 @hhexiy

**Comment by kshitij12345** [comment]
@eric-haibin-lin , 

From a quick view,
`take` as of now doesn't actually support `mode=raise`,
https://github.com/apache/incubator-mxnet/blob/a8b9728d5729b565fdf2f588d1985bb5eca7f68a/src/operator/tensor/indexing_op.h#L671-L675

https://github.com/apache/incubator-mxnet/blob/a8b9728d5729b565fdf2f588d1985bb5eca7f68a/src/operator/tensor/indexing_op.h#L679-L709

So as of now, it doesn't actually raise out-of-bounds error.

**Comment by eric-haibin-lin** [comment]
Raise mode added in #15887
