### ISSUE TITLE
CI compilation times out on unix-gpu and centos-gpu

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#15965]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15167/41/pipeline/50

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-15167/41/pipeline/44

Seems like the compilation is hanging.

CC @ptrendx

**Comment by yuxihu** [comment]
@marcoabreu @ptrendx Are you still seeing the same issue in your PRs? We tried to look into the logs in the provided build and there seems very little useful information there. If we do not have data points showing we consistently hit the same issue, it can be some intermittent infrastructure (ec2, networking, etc) issues.

**Comment by yuxihu** [comment]
I am closing the issue for now. Let's reopen if it surfaces again. Thanks.
