### ISSUE TITLE
How to get sliding window output?

### ISSUE THREAD

**Issue by donhk1011** [apache/incubator-mxnet#16002]
Hi,

Is there any function in mxnet that gives sliding window output like the ‘unfold’ in Pytorch?
e.g., 
(https://pytorch.org/docs/master/nn.html?highlight=unfold#torch.nn.Unfold)
(https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.lib.stride_tricks.as_strided.html)
![image](https://user-images.githubusercontent.com/32080634/63658191-99ef6600-c75d-11e9-9c3f-f7b70563cc96.png)

It should also support back-propagation.

Thanks!!

**Comment by zachgk** [comment]
I don't think so. You could try using gather_nd as a workaround.

**Comment by donhk1011** [comment]
Hi,
Thanks for the reply. Is it possible to use gather_nd with something like for-loop?
Could you please give me an example of how to use it with gather_nd?
E.g., input - [0,1,2,3,4,5], output - [ [0,1], [1,2], [2,3], [3,4], [4,5] ]

**Comment by zachgk** [comment]
You would want to use a for loop to construct the indices input to gather_nd.

```
a = mx.nd.array([0,1,2,3,4,5])
indices = mx.nd.array([[[0,1],[1,2],[2,3],[3,4],[4,5]]])
print(mx.nd.gather_nd(a, indices))
# Outputs:
# [[0. 1.]
# [1. 2.]
# [2. 3.]
# [3. 4.]
# [4. 5.]]
# <NDArray 5x2 @cpu(0)>
```

**Comment by donhk1011** [comment]
Thanks! I
