### ISSUE TITLE
Is there any communication between parameter servers?

### ISSUE THREAD

**Issue by yangwenhuan** [apache/incubator-mxnet#16020]

**Comment by yangwenhuan** [comment]
> No, but there's all-to-all communication between workers and servers

Could you show me the relative source code?

**Comment by eric-haibin-lin** [comment]
The code is at https://github.com/apache/incubator-mxnet/blob/master/src/kvstore/kvstore_dist.h 
and 
https://github.com/apache/incubator-mxnet/blob/master/src/kvstore/kvstore_dist_server.h
Feel free to reopen for further questions
