### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by taoari** [apache/incubator-mxnet#1603]
I am a Caffe user, and is impressed with MXNet's memory management. 

However, for the VGG16 Network, Caffe is able to run with training batch size 25, testing batch size 5 on a 6G GPU, which actually costs 5.67G. But for MXNet, I am not able to run VGG16 on a 6G GPU with batch size 25. This is not reasonable, as Caffe only has in-place calculation, while MXNet additionally employs memory scheduling and sharing! 

When I am switching to a 12G GPU, nvidia-smi shows that its actual memory cost is less than 6G. What's the problem?

Further, I reduce the batch size to 15 to make to fit for  a 6G memory, however, the program can only run for several hours. The next day when I come back, it crashed with out of memory. Is there a memory leak problem?

**Comment by javelinjs** [comment]
single gpu with local-mode kvstore?

**Comment by taoari** [comment]
Yes, will this be a problem?
