### ISSUE TITLE
ndarray error

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [apache/incubator-mxnet#16036]
File "/home/Apps/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:41:07] include/mxnet/././tensor_blob.h:290: Check failed: this->shape_.Size() == static_cast<size_t>(shape.Size()) (3072008192 vs. 18446744072486592512) : TBlob.get_with_shape: new and old shape do not match total elements
Stack trace:
  [bt] (0) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x47597b) [0x2b364d24a97b]
  [bt] (1) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x507ee9) [0x2b364d2dcee9]
  [bt] (2) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x8394ea) [0x2b364d60e4ea]
  [bt] (3) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x83f53b) [0x2b364d61453b]
  [bt] (4) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFCompute(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x307) [0x2b364f27ef17]
  [bt] (5) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x23f6634) [0x2b364f1cb634]
  [bt] (6) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2403fc9) [0x2b364f1d8fc9]
  [bt] (7) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2407264) [0x2b364f1dc264]
  [bt] (8) /home/43694/Apps/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24027d4) [0x2b364f1d77d4]

**Comment by ZHAIXINGZHAIYUE** [comment]
what's the max size of an ndarray ?

**Comment by apeforest** [comment]
By default it's 2^31 (max int32). To support large tensor size, you may need to build MXNet from source with compiler flag USE_INT64_TENSOR_SIZE.

**Comment by leleamol** [comment]
@mxnet-label-bot add [NDarray]

**Comment by ZHAIXINGZHAIYUE** [comment]
@apeforest thank you.
