### ISSUE TITLE
[Numpy] DType information losses when converted from numpy

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#16048]
```python
import mxnet.numpy as np
a = 123123213123
b = np.array(a)
print(b.dtype)
# <class 'numpy.float32'>
```

```python
import numpy as np
a = 123123213123
b = np.array(a)
print(b.dtype)
# int64
```

```python
import cupy as np
a = 123123213123
b = np.array(a)
print(b.dtype)
# int64
```

```python
import jax.numpy as np
a = 123123213123
b = np.array(a)
print(b.dtype)
# int32
```

**Comment by sxjscience** [comment]
@haojin2

**Comment by sxjscience** [comment]
Also, would be more consistent if we could print `float32`, `int64` instead of the raw class name

**Comment by reminisce** [comment]
Acutally, the `fp32` conversion is intended since it's the default dtype in DL. We don't try to match everything exact with numpy, but rather provide a numpy-like experience which is tailored for DL applications.

I will see what we can do for stringizing `dtype`. Thanks.

**Comment by sxjscience** [comment]
Would it be better to convert int types to int32?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VoVAllen** [comment]
Seems related to error at https://github.com/apache/incubator-mxnet/issues/16054

**Comment by sxjscience** [comment]
Close this and move the discussion to https://github.com/apache/incubator-mxnet/issues/16357
