### ISSUE TITLE
[Website] Version selection dropdown on get_started

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16059]
Website's version selection dropdown can be made cleaner

![image](https://user-images.githubusercontent.com/10992635/64068569-ca685180-cbee-11e9-8ae2-7f3e760dfa5c.png)

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [website-beta]

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot update [website]

**Comment by ys2843** [comment]
Can I help with this issue? @aaronmarkham

**Comment by ChaiBapchya** [comment]
Closing the issue since now the version dropdown is clean!!
