### ISSUE TITLE
Problems on distributed training

### ISSUE THREAD

**Issue by gclouding** [apache/incubator-mxnet#1605]
I am now trying to learn distributed training of CNN on imagenet data using mxnet. However, I am not sure how to do this. 
I have two machines, and split the original training image list (1000 samples) into two lists (500 samples each), with which to make two .rec data using im2rec tool, and then put the first .rec in the first machine, and the second one in the second machine. 
In the train_imagenet.py on each machine, the data iterator is pointed to the its local .rec data. So is this way right for distributed training ?

Is there any others convenient ways with detailed procedures to do distributed training ?

**Comment by firearasi** [comment]
Would like to see a detailed hands-on tutorial too:

**Comment by albertyou2** [comment]
HI @gclouding. Have you found out the right way to do distribute training with MXNET? I got the same problem .Could you please show me the right way to do this?

**Comment by gclouding** [comment]
Now we use HDFS to do distributed training. It is a very convenient way. @albertyou2 @firearasi

**Comment by albertyou2** [comment]
@gclouding Thanks for reply. Do you have a step by step instruction?

**Comment by gclouding** [comment]
just install HDFS in your cluster and put the .rec file into the hdfs,and let data_dir point to it.  You can find a lot of instructions on how to install java/hadoop/hdfs in internet. @albertyou2

**Comment by albertyou2** [comment]
@gclouding Thank you very much!

**Comment by eric-haibin-lin** [comment]
Closing it for now due to inactivity. Please feel free to reopen it for followup discussions.
