### ISSUE TITLE
can't run CI scripts on Windows

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16083]
## Description
When running the build script to emulate CI tests while on a Windows host, I ran into an error that's a platform limitation. 
```
ci/build.py --docker-registry mxnetci --platform ubuntu_cpu_python /work/runtime_functions.sh sanity_check
```

Yields:
```
Traceback (most recent call last):
  File "ci/build.py", line 591, in <module>
  File "ci/build.py", line 501, in main
  File "ci/build.py", line 149, in build_docker
AttributeError: module 'os' has no attribute 'getuid'
```

Googling about says that you can't use `getuid` on Windows. If we want to support a Windows community for development, we should probably not have this fail for Windows users. Seems like we could put a placeholder in there if on Windows.

**Comment by marcoabreu** [comment]
Build.py doesn't support Windows and it's also not trivial not planned due to the deep integration of our scripts into the host filesystem. In the end, build.py is a CI utility and not intended to be end-user facing.
