### ISSUE TITLE
trouble on training fcn with new network structure  from scratch

### ISSUE THREAD

**Issue by caffeTao** [apache/incubator-mxnet#1609]
I wanna train a fcn with new network design using the FileIter in origional fcn released in mxnet example, but I have a troule here with the context of data and operator,here is my code,
`import mxnet as mx
import logging
import mxnet.initializer as init
from data import FileIter
from solver import Solver
def ConvFactory(data, num_filter, kernel, stride=(1,1), pad=(0, 0), act_type="relu"):  
    conv = mx.symbol.Convolution(data=data, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad,workspace=2400)
    bn = mx.symbol.BatchNorm(data=conv)
    act = mx.symbol.Activation(data = bn, act_type=act_type)

data = mx.symbol.Variable(name="data")
conv1 = ConvFactory(data=data, kernel=(5,5), pad=(2,2), num_filter=96, act_type="relu")
prep = ConvFactory(data=conv1, kernel=(1,1), pad=(0,0), num_filter=21, act_type="relu")
softmax = mx.symbol.SoftmaxOutput(data=prep, multi_output=True, use_ignore=True, ignore_label=255, name="softmax")

ctx = mx.gpu(0)

initializer=init.Xavier(rnd_type='gaussian',factor_type='in',magnitude=2.0)
data_shape=(1,3,500,500)
arg_shapes, _, aux_shapes = softmax.infer_shape(data=data_shape)
arg_names = softmax.list_arguments()
input_names = ['data','softmax_label']
param_names = list(set(arg_names) - set(input_names))
aux_names = softmax.list_auxiliary_states()
arg_params = dict([(x[0], mx.nd.zeros(x[1], ctx)) for x in zip(arg_names, arg_shapes) if x[0] in param_names])
aux_params = dict([(x[0], mx.nd.zeros(x[1], ctx)) for x in zip(aux_names, aux_shapes)])

for k, v in arg_params.items():
    initializer(k, v)

for k, v in aux_params.items():
    initializer(k, v)

for k, v in arg_params.items():
    print k
    print v.context      

for k, v in aux_params.items():
    print k
    print v.context
train_dataiter = FileIter(
    root_dir             = "./VOC2012",
    flist_name           = "train.lst",
    # cut_off_size         = 400,
    rgb_mean             = (123.68, 116.779, 103.939),
    )
val_dataiter = FileIter(
    root_dir             = "./VOC2012",
    flist_name           = "val.lst",
    rgb_mean             = (123.68, 116.779, 103.939),
    )
log_filename="incep.txt"
logging.basicConfig(level=logging.DEBUG,filename=log_filename,filemode="w")
model_prefix='model/incep'
model = Solver(
    ctx                 = ctx,
    symbol              = softmax,
    begin_epoch         = 0,
    num_epoch           = 10000,
    arg_params          = arg_params,
    aux_params          = aux_params,
    learning_rate       = 0.001,
    momentum            = 0.99,
    wd                  = 0.0005)
model.fit(
    train_data          = train_dataiter,
    eval_data           = val_dataiter,
    batch_end_callback  = mx.callback.Speedometer(1, 10),
    epoch_end_callback  = mx.callback.do_checkpoint(model_prefix))`
and the outputs and error  are as follows:
batchnorm0_gamma
gpu(0)
batchnorm1_gamma
gpu(0)
convolution0_bias
gpu(0)
batchnorm0_beta
gpu(0)
convolution1_bias
gpu(0)
convolution1_weight
gpu(0)
convolution0_weight
gpu(0)
batchnorm1_beta
gpu(0)
batchnorm0_moving_var
gpu(0)
batchnorm1_moving_var
gpu(0)
batchnorm0_moving_mean
gpu(0)
batchnorm1_moving_mean
gpu(0)
[02:06:10] D:\jt\mxnet20160122win\mxnet-master\dmlc-core\include\dmlc/logging.h:241: [02:06:10] ....\src\symbol\graph_executor.cc:562: Check failed: info.data.ctx() == op_nodes_[i].ctx Auxiliary NDArray's context must match the operator's context assignment
Traceback (most recent call last):
  File "D:\jt\mxnet20160129release\example\fcn-xs\fcn_n.py", line 131, in <module>
    epoch_end_callback  = mx.callback.do_checkpoint(model_prefix))
  File "D:\jt\mxnet20160129release\example\fcn-xs\solver.py", line 71, in fit
    aux_states=self.aux_params)
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", line 751, in bind
    ctypes.byref(handle)))
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [02:06:10] ....\src\symbol\graph_executor.cc:562: Check failed: info.data.ctx() == op_nodes_[i].ctx Auxiliary NDArray's context must match the operator's context assignment

**Comment by caffeTao** [comment]
I use the solver and fileIter of  the fcn-xs example, I only try a new network and initiate the parameters mannually

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
