### ISSUE TITLE
[Bug] NDArray asscalar error after set npx.set_np()

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#16099]
## Description
```python
from mxnet import npx
npx.set_np()
from mxnet import ndarray as nd
a = nd.ones((4,))
a[0] # Print 1
a[0].asscalar() # Error
```

![image](https://user-images.githubusercontent.com/8686776/64315490-c10f2880-cfe4-11e9-90eb-86e82d113688.png)

**Comment by reminisce** [comment]
The problem is that scalar sanity check for legacy NDArray is not numpy-compatible. I can send in the fix, but could you explain in what situation you would need to do this with numpy semantics on?

**Comment by VoVAllen** [comment]
It's from `assert a[0] == 1`, which calls `bool(a[0]==1)`, and would trigger the error.

**Comment by samskalicky** [comment]
@zachgk assign [@reminisce ]

**Comment by VoVAllen** [comment]
Any update on this?

**Comment by yzhliu** [comment]
@BenjaminCHEN2016 will be helping.

**Comment by BenjaminCHEN2016** [comment]
@VoVAllen It seems that this problem no longer exists? I tested on the latest master branch, asscalar() works as expected. Would you check if the problem still occurs in your environment?

**Comment by VoVAllen** [comment]
Thanks
