### ISSUE TITLE
Different default values for NDArray and Symbol in random.multinomial

### ISSUE THREAD

**Issue by igolan** [apache/incubator-mxnet#16103]
## Description
```mxnet.symbol.random.multinomial```
 and 
```mxnet.ndarray.random.multinomial```
 have different default values for the argument get_prob.
That confusing, specifically when using hybrid blocks, and calling
```F.random.multinomial```
 without specifying a value for get_prob.

Signatures:
```
mxnet.ndarray.random.multinomial(data, shape=_Null, get_prob=False, out=None, dtype='int32', **kwargs)
```
vs.
```
mxnet.symbol.random.multinomial(data, shape=_Null, get_prob=True, dtype='int32', **kwargs)
```
## Environment info (Required)
N/A

Package used (Python/R/Scala/Julia):
MXNET1.5 python API

## Build info (Required if built from source)
N/A

## Error Message:
N/A

## Minimum reproducible example
N/A

## Steps to reproduce

https://mxnet.incubator.apache.org/versions/master/api/python/ndarray/random.html#mxnet.ndarray.random.multinomial
and
https://mxnet.incubator.apache.org/versions/master/api/python/symbol/symbol.html#mxnet.symbol.random.multinomial

## What have you tried to solve it?
N/A

**Comment by apeforest** [comment]
Since this will impact backward compatibility and there is a plan to consolidate symbol and ndarray modules in 2.0, we will address this issue in MXNet 2.0: https://github.com/apache/incubator-mxnet/issues/9686
