### ISSUE TITLE
Deprecated MXNET website is still online ?

### ISSUE THREAD

**Issue by igolan** [apache/incubator-mxnet#16154]
Hi,
I searched for "install mxnet" in Google, and the first results was this link:
http://mxnet.incubator.apache.org/test/get_started/install.html
(note the /test/ )
which looks like a deprecated version of MXNET website (if you go to the homepage, you'll find news about MXNET0.1 release).

Although it's nice to go back in time, I find it very confusing.
If that website is intentionally online, I think it's worth adding a big notice that this is an old version of MXNET, otherwise, maybe it's worth redirecting this url to the current version.

(I know that Google results are different per user, but it came up first also in my friend's computer, and in any case, that link should redirect to the latest version).

**Comment by marcoabreu** [comment]
@ThomasDelteil

**Comment by aaronmarkham** [comment]
I'll make an infra request. We don't have control of that folder.

**Comment by aaronmarkham** [comment]
This has been resolved. It might take a while for google's index to update.
