### ISSUE TITLE
group norm tests are failing

### ISSUE THREAD

**Issue by Vikas-kum** [apache/incubator-mxnet#16168]
88e9fe53272d:incubator-mxnet vikumar$ nosetests -v tests/python/unittest/test_operator.py:test_groupnorm
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1969046295 to reproduce.
[WARNING] *** test-level seed set: all "@with_seed()" tests run deterministically ***
test_operator.test_groupnorm ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=907522936 to reproduce.
FAIL

======================================================================
FAIL: test_operator.test_groupnorm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vikumar/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/vikumar/incubator-mxnet/tests/python/unittest/common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "/Users/vikumar/incubator-mxnet/tests/python/unittest/test_operator.py", line 1959, in test_groupnorm
    atol=5e-2 if dtype == np.float16 else 1e-5, dtype=dtype)
  File "/Users/vikumar/anaconda3/lib/python3.6/site-packages/mxnet/test_utils.py", line 1228, in check_symbolic_backward
    equal_nan=equal_nan)
  File "/Users/vikumar/anaconda3/lib/python3.6/site-packages/mxnet/test_utils.py", line 533, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 1.247222 exceeds tolerance rtol=0.001000, atol=0.000010.  Location of maximum error:(2, 7, 0, 0), a=-0.008328, b=-0.008351
 EXPECTED_data: array([[[[ 2.758162  ]],

        [[-0.37069988]],...
 BACKWARD_data: array([[[[ 2.758162  ]],

        [[-0.37069988]],...
-------------------- >> begin captured logging << --------------------
common: INFO: Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1969046295 to reproduce.
common: WARNING: *** test-level seed set: all "@with_seed()" tests run deterministically ***
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=907522936 to reproduce.
--------------------- >> end captured logging << ---------------------

**Comment by Vikas-kum** [comment]
https://github.com/apache/incubator-mxnet/pull/14959 

@sxjscience @haojin2 - We saw a failure in PR. This test is failing with that seed consistently. Please check if there is issue with code or test and provide if there is quick fix.

**Comment by sxjscience** [comment]
Lower the atol_eps by https://github.com/apache/incubator-mxnet/pull/16169
