### ISSUE TITLE
How to dump quantized weights from MKLDNN as Ndarray

### ISSUE THREAD

**Issue by shoubhik** [apache/incubator-mxnet#16177]
Hi,
I have a use case where i need to debug the weights of Convolution layer when quantized by MKLDNN in MXNet [here](https://github.com/apache/incubator-mxnet/blob/master/src/operator/subgraph/mkldnn/mkldnn_conv.cc#L189-L190). The problem I am facing is that the model saved has the original fp32 weights and it is converted to int8 during runtime. When I do try to dump the cached_weight_ into a File as NDArray it is computed asynchronously and I get an error saying the weight is unavailable. The code I am using is something like this

```
LOG(INFO) << "Writing cached integer weight file";
      char cwd[200];
      getcwd(cwd, sizeof(cwd));
      std::string current_dir(cwd);
      LOG(INFO) << "The current dir is : " << current_dir;
      LOG(INFO) << "Writing qunatized cached weights to file";
      int num_args = 1;
      std::vector<NDArray> data(num_args);
      std::vector<std::string> names(num_args);
      data[0] = cached_weight_;
      names[0] = op_name;
      std::string cached_weight_file_path = current_dir + "/quantized-conv-weights/" + op_name;
      std::unique_ptr<dmlc::Stream> fo(dmlc::Stream::Create(cached_weight_file_path.c_str(), "w"));
      mxnet::NDArray::Save(fo.get(), data, names);
      LOG(INFO) << "Written weights to " + cached_weight_file_path;
```

**Comment by zachgk** [comment]
ping @pengzhao-intel

**Comment by pengzhao-intel** [comment]
Thanks @zhennanqin to follow up :)

**Comment by ZhennanQin** [comment]
Hi @shoubhik,
Here's a demo code on how to dump mkldnn u8 convolution weights.
https://github.com/ZhennanQin/incubator-mxnet/commit/c775dfc4f444a013302420112cc9c214fc59cd00

For s8 convolution, mkldnn doesn't support to convert its s8 weight back to default format, thus you can't directly save them with aobve code. But you can still access its s8 weight in nhwc format:
```
uint8_t* ptr = static_cast<uint8_t*>(cached_weight_.GetMKLDNNData()->get_data_handle()).
```
You can write a loop to visit each element of it and save into a file.

**Comment by shoubhik** [comment]
@ZhennanQin in your previous comment for s8 it should be?

`int8_t* ptr = static_cast<int8_t*>(cached_weight_.GetMKLDNNData()->get_data_handle())`

and for u8 case in your code snippet you have written

```
MKLDNNStream::Get()->Submit();
....
data[0] = cached_weight_.Reorder2Default();
```

for s8 should it be
```
MKLDNNStream::Get()->Submit();
....
`int8_t* ptr = static_cast<int8_t*>(cached_weight_.GetMKLDNNData()->get_data_handle())
```

**Comment by ZhennanQin** [comment]
https://github.com/ZhennanQin/incubator-mxnet/commit/5276bfac3962fb9511482ac7232a0981f97d9b8e is added to show how to print s8 convolution weights.

**Comment by shoubhik** [comment]
and for bias also we can do the same thing?

**Comment by ZhennanQin** [comment]
for bias, you can try the first solution first(NDArray save), if it doesn't work, then access with pointer will always work.

**Comment by shoubhik** [comment]
thanks this has been very helpful.

**Comment by pengzhao-intel** [comment]
closing sine the question is answered :)
Feel free to reopen or answer more
