### ISSUE TITLE
using gluon/image_classification.py img/sec speed up when metric update and reset when turned off

### ISSUE THREAD

**Issue by vgangal101** [apache/incubator-mxnet#16201]
I am working with the example/gluon/image_classification.py script in the apache incubator mxnet github and was tinkering with the script. I have observed that when I run the following command :  

python image_classification.py --model resnet50_v1 --dataset dummy --epochs 1 --log-interval 1 --batch-size 64 --gpu 0 

I get a img/sec value of 323.0 img/sec on a Tesla V100 gpu 

The same command if I run with the metrics computations turned off ( lines 212,229) I get about 1400 img/sec.

Why am I seeing this speed up ? Why does turning off the metric computations result in such a massive increase in img/sec 

Environment : 
miniconda environment with mxnet-cu101 , cuda/10.1 , cudnn/7.4, python 2.7.15 
mxnet was pip installed 
Tests run on a Tesla V100 gpu

**Comment by TristonC** [comment]
The speedup is not real. And it is due to the asynchronous computation of MXNet.  The nd.asnumpy() function is called in the metrics' update which causes the synchronization for each batch. The performance without metrics update should be close to the one with the metrics update.
