### ISSUE TITLE
Mxnet official website before the search function area ran where? Updated?

### ISSUE THREAD

**Issue by mifan0208** [apache/incubator-mxnet#16237]

**Comment by lanking520** [comment]
Hi @mifan0208 Could you provide more information for your question?

**Comment by wkcn** [comment]
mifan0208’s question may be ‘where is the search box in the main page of MXNet website’.

The search box only exists in the documents pages, like http://mxnet.incubator.apache.org/api/python/docs/api/

Some users report that they could not find the search box in the new website, and the old search box is more convenient than the new one. I also hope that the search box exists on the right-top of the main page of the new website.
