### ISSUE TITLE
[Website] MXNet Version selection Drop-down makes page jump to top of page

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16231]
Upon selecting the version from the drop-down, it moves the screen to the top of the page - not the desired outcome.

![Install page](https://user-images.githubusercontent.com/10992635/65363728-548a5100-dbc2-11e9-80a5-a3f051b3e766.png)

However, upon selecting the rest of the options - OS Platform, Langugage binding, GPU/CPU etc the screen remains in the original position (instead of moving to the top of the page) which is the desired outcome.

I'm guessing it involves playing with the button's on-click and using `$e.preventDefault();` somewhere around showContent() after populating new options

https://stackoverflow.com/questions/43611173/button-onclick-makes-page-jump-to-top-of-page

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [website-beta]

@aaronmarkham What do you think?

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot update [website-beta, website]

**Comment by aaronmarkham** [comment]
> @mxnet-label-bot add [website-beta]
> 
> @aaronmarkham What do you think?

Sounds like we need a jquery label for people that want to hack on the front-end of the site.

**Comment by ys2843** [comment]
I will work on this issue
