### ISSUE TITLE
links broken for https://mxnet.incubator.apache.org/versions/master/gluon/

### ISSUE THREAD

**Issue by srsridharan** [apache/incubator-mxnet#16249]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
The link obtained when searching on google/duckduckgo for mxnet gluon is 
https://mxnet.incubator.apache.org/versions/master/gluon/
The link however appears to lead to a "Not found" error. 

## Steps to reproduce
Paste https://mxnet.incubator.apache.org/versions/master/gluon/ into a web browser

**Comment by roywei** [comment]
lots of google search results went to 404, may due to new mxnet website launch

https://mxnet.incubator.apache.org/api/python/kvstore/kvstore.html
https://mxnet.incubator.apache.org/api/python/index.html

**Comment by roywei** [comment]
@srsridharan you may want to search directly on mxnet new website for now. https://mxnet.incubator.apache.org/

**Comment by igolan** [comment]
The new website has a lot of bugs/missing documentations.
Few examples:
[Searching for broadcast_add does not return Symbol/ndarray broadcast_add methods](https://mxnet.incubator.apache.org/api/python/docs/search.html?q=broadcast_add) ( I also couldn't find it in the menu)
[In Symbol.sqaure , it refers to square methods but the link is to the same page ("Convenience fluent method for square().")](https://mxnet.incubator.apache.org/api/python/docs/api/symbol/_autogen/mxnet.symbol.Symbol.square.html#mxnet.symbol.Symbol.square)

**Comment by apatsekin** [comment]
@roywei the whole Symbol API documentation is missing (try clicking on any links from this page):
https://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/symbol/index.html

**Comment by srsridharan** [comment]
> @srsridharan you may want to search directly on mxnet new website for now. https://mxnet.incubator.apache.org/
@roywei Thanks for the suggestion.  I raised the ticket to flag the website issue and will use the direct serach for now. However please note that the search functionality is pretty slow on the mxnet site. Perhaps requesting a recrawl of the mxnet site from the google crawler would get this resolved a bit sooner?
https://support.google.com/webmasters/answer/6065812?hl=en
just a thought..

**Comment by ThomasDelteil** [comment]
Result | URL |  
-- | -- | --
404 Not found | http://mxnet.io/faq/perf.html<a href>RedirectedLinked from: http://mxnet.incubator.apache.org/get_started and 2 more |  
404 Not found | http://mxnet.incubator.apache.org/validate_mxnet.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/ubuntu_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/scala_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/java_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/ubuntu_setup<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/c_plus_plus<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/centos_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/osx_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/windows_setup.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/versions/master/tutorials/embedded/wine_detector.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started and 2 more |  
404 Not found | http://mxnet.incubator.apache.org/faq/env_var.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.io/tutorials/embedded/wine_detector.html<a href>RedirectedLinked from: http://mxnet.incubator.apache.org/get_started and 2 more |  
404 Not found | http://mxnet.incubator.apache.org/install-jetson.html<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | http://mxnet.incubator.apache.org/download<a href>Linked from: http://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/validate_mxnet.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/ubuntu_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/scala_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/java_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/ubuntu_setup<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/c_plus_plus<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/centos_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/osx_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/windows_setup.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/faq/env_var.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started and 1 more |  
404 Not found | https://mxnet.incubator.apache.org/install-jetson.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/download<a href>Linked from: https://mxnet.incubator.apache.org/get_started |  
404 Not found | https://mxnet.incubator.apache.org/get_started/c_plus_plus<a href>Linked from: https://mxnet.incubator.apache.org/get_started/ |  
404 Not found | https://mxnet.incubator.apache.org/get_started/install-jetson.html<a href>Linked from: https://mxnet.incubator.apache.org/get_started/ |  
404 Not found | https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/mkldnn/MKLDNN_README.md<a href>OutboundLinked from: http://mxnet.incubator.apache.org/get_started/ubuntu_setup |  
404 Not found | http://mxnet.incubator.apache.org/get_started/c_plus_plus<a href>Linked from: http://mxnet.incubator.apache.org/get_started/ubuntu_setup |  
404 Not found | https://github.com/apache/incubator-mxnet/tree/master/docs/build_version_doc<a href>OutboundLinked from: http://mxnet.incubator.apache.org/get_started/scala_setup |  
404 Not found | https://mxnet.incubator.apache.org/install/build_from_source<a href>Linked from: http://mxnet.incubator.apache.org/api/cpp |  
404 Not found | https://github.com/dmlc/MXNet.jl/edit/master/docs/index.md<a href>OutboundLinked from: http://mxnet.incubator.apache.org/api/julia/docs/api/ |  
404 Not found | https://github.com/dmlc/MXNet.jl/tree/master/examples<a href>OutboundLinked from: http://mxnet.incubator.apache.org/api/julia/docs/api/ |  
404 Not found | http://mxnet.io/install/index.html<a href>RedirectedLinked from: http://mxnet.incubator.apache.org/api/architecture/exception_handling |  
404 Not found | https://mxnet.incubator.apache.org/tutorials/basic/data.html<a href>Linked from: http://mxnet.incubator.apache.org/api/architecture/note_data_loading |  
404 Not found | http://mxnet.io/architecture/rnn_interface.html<a href>RedirectedLinked from: http://mxnet.incubator.apache.org/api/architecture/note_engine |  
404 Not found | http://mxnet.incubator.apache.org/api/tutorials/mkldnn/operator_list.md<a href>Linked from: http://mxnet.incubator.apache.org/api/faq/env_var

**Comment by ThomasDelteil** [comment]
<table width="638" cellpadding="0" cellspacing="0" id="brokenLinkTable">
                  <tbody><tr>
                    <td id="brokenLinkTable_td_header" width="30"><div align="center"><strong>#</strong></div></td>
                    <td id="brokenLinkTable_td_header" width="499"><div align="center"><strong>Broken link </strong><span class="style6"> (you can scroll this field left-right)</span></div></td>
                    <td id="brokenLinkTable_td_header" width="51"><div align="center"><strong>Page where found</strong></div></td>
                    <td width="58"><div align="center">
                      <p class="style1">Server response</p>
                    </div></td>
                  </tr>
                <tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/validate_mxnet.html" target="_blank">1</a><a name="1"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/validate_mxnet.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=363" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#1" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/faq/perf.html" target="_blank">2</a><a name="2"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/faq/perf.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=271" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#2" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/ubuntu_setup.html" target="_blank">3</a><a name="3"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/ubuntu_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=576" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#3" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/scala_setup.html" target="_blank">4</a><a name="4"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/scala_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=630" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#4" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/java_setup.html" target="_blank">5</a><a name="5"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/java_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=684" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#5" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/ubuntu_setup" target="_blank">6</a><a name="6"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/ubuntu_setup" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=729" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#6" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/c_plus_plus" target="_blank">7</a><a name="7"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/c_plus_plus" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=747" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#7" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/centos_setup.html" target="_blank">8</a><a name="8"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/centos_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=756" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#8" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/osx_setup.html" target="_blank">9</a><a name="9"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/osx_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=874" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#9" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/windows_setup.html" target="_blank">10</a><a name="10"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/windows_setup.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1161" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#10" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://mxnet.incubator.apache.org/versions/master/tutorials/embedded/wine_detector.html" target="_blank">11</a><a name="11"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://mxnet.incubator.apache.org/versions/master/tutorials/embedded/wine_detector.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1521" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#11" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/faq/env_var.html" target="_blank">12</a><a name="12"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/faq/env_var.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1633" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#12" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/install-jetson.html" target="_blank">13</a><a name="13"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/install-jetson.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1669" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#13" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/download" target="_blank">14</a><a name="14"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.incubator.apache.org/download" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1682" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#14" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/tutorials/embedded/wine_detector.html" target="_blank">15</a><a name="15"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/tutorials/embedded/wine_detector.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started&amp;c&amp;line=1654" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#15" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/mkldnn/MKLDNN_README.md" target="_blank">16</a><a name="16"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/mkldnn/MKLDNN_README.md" readonly="true" id="url_td_field">»</td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started/ubuntu_setup" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started%2Fubuntu_setup&amp;c&amp;line=309" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#16" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://github.com/apache/incubator-mxnet/tree/master/docs/build_version_doc" target="_blank">17</a><a name="17"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://github.com/apache/incubator-mxnet/tree/master/docs/build_version_doc" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/get_started/scala_setup" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fget_started%2Fscala_setup&amp;c&amp;line=249" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#17" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://github.com/dmlc/MXNet.jl/edit/master/docs/index.md" target="_blank">18</a><a name="18"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://github.com/dmlc/MXNet.jl/edit/master/docs/index.md" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/julia/docs/api/" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fjulia%2Fdocs%2Fapi%2F&amp;c&amp;line=609" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#18" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://github.com/dmlc/MXNet.jl/tree/master/examples" target="_blank">19</a><a name="19"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://github.com/dmlc/MXNet.jl/tree/master/examples" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/julia/docs/api/" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fjulia%2Fdocs%2Fapi%2F&amp;c&amp;line=625" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#19" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/install/index.html" target="_blank">20</a><a name="20"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/install/index.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/architecture/exception_handling" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Farchitecture%2Fexception_handling&amp;c&amp;line=343" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#20" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/architecture/rnn_interface.html" target="_blank">21</a><a name="21"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/architecture/rnn_interface.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/architecture/note_engine" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Farchitecture%2Fnote_engine&amp;c&amp;line=697" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#21" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://localhost:8888" target="_blank">22</a><a name="22"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://localhost:8888" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/faq/visualize_graph" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Ffaq%2Fvisualize_graph&amp;c&amp;line=368" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#22" onclick="explain();">timeout </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/faq/multi_devices.html" target="_blank">23</a><a name="23"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/faq/multi_devices.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/faq/perf" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Ffaq%2Fperf&amp;c&amp;line=1333" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#23" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/tutorials/python/mnist.html" target="_blank">24</a><a name="24"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/tutorials/python/mnist.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/image/mnist.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fimage%2Fmnist.html&amp;c&amp;line=2662" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#24" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/api/python/gluon/gluon.html" target="_blank">25</a><a name="25"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/api/python/gluon/gluon.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/image/mnist.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fimage%2Fmnist.html&amp;c&amp;line=2716" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#25" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/api/python/optimization/optimization.html" target="_blank">26</a><a name="26"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/api/python/optimization/optimization.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/image/mnist.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fimage%2Fmnist.html&amp;c&amp;line=2727" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#26" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/api/python/metric/metric.html" target="_blank">27</a><a name="27"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/api/python/metric/metric.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/image/mnist.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fimage%2Fmnist.html&amp;c&amp;line=2743" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#27" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://mxnet.apache.org/_modules/mxnet/gluon/block.html" target="_blank">28</a><a name="28"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://mxnet.apache.org/_modules/mxnet/gluon/block.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/custom-loss/custom-loss.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fcustom-loss%2Fcustom-loss.html&amp;c&amp;line=2676" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#28" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="https://mxnet.apache.org/api/python/gluon/gluon.html" target="_blank">29</a><a name="29"></a></td><td id="brokenLinkTable_td"><input type="text" value="https://mxnet.apache.org/api/python/gluon/gluon.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/gluon/custom-loss/custom-loss.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Ftutorials%2Fpackages%2Fgluon%2Fcustom-loss%2Fcustom-loss.html&amp;c&amp;line=2677" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#29" onclick="explain();">404 </a></td></tr><tr><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.io/faq/new_op.html" target="_blank">30</a><a name="30"></a></td><td id="brokenLinkTable_td"><input type="text" value="http://mxnet.io/faq/new_op.html" readonly="true" id="url_td_field"></td><td id="brokenLinkTable_td" align="center"><a href="http://mxnet.incubator.apache.org/api/python/docs/api/ndarray/_autogen/mxnet.ndarray.Custom.html" target="_blank">url</a> <blink><a href="srcview/view-link.php?url=http%3A%2F%2Fmxnet.incubator.apache.org%2Fapi%2Fpython%2Fdocs%2Fapi%2Fndarray%2F_autogen%2Fmxnet.ndarray.Custom.html&amp;c&amp;line=2662" target="_blank">src</a></blink></td><td id="brokenLinkTable_td_right_end" align="center"><a href="#30" onclick="explain();">404 </a></td></tr></tbody></table>

**Comment by aaronmarkham** [comment]
> > @srsridharan you may want to search directly on mxnet new website for now. https://mxnet.incubator.apache.org/
> 
> @roywei Thanks for the suggestion. I raised the ticket to flag the website issue and will use the direct serach for now. However please note that the search functionality is pretty slow on the mxnet site. Perhaps requesting a recrawl of the mxnet site from the google crawler would get this resolved a bit sooner?
> https://support.google.com/webmasters/answer/6065812?hl=en
> just a thought..

I already have a ticket open with Apach Infra for that.
https://issues.apache.org/jira/browse/INFRA-19144

**Comment by aaronmarkham** [comment]
Since this is really about the google index, let's keep this issue focused on that. 
If we can get a reindex, it'll fix the google search results. 
As for the broken links, I'll try to knock out the ones mentioned in the comments today. I just merged a previous link pass I did on the install page and readme. If y'all find more broken links, please open another issue as I will close this one once the reindex happens. Thanks!

**Comment by aaronmarkham** [comment]
This link is gone from the google index.
