### ISSUE TITLE
[Feature request] mx.ndarray.any and mx.ndarray.all

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#16247]
I think numpy.any/numpy.all are both common used, so mx.ndarray.any and mx.ndarray.all should be implemented.

**Comment by reminisce** [comment]
These ops are included in NumPy Operator Coverage list but haven't been implemented yet.
https://cwiki.apache.org/confluence/display/MXNET/NumPy+Operator+Coverage+Status

**Comment by haojin2** [comment]
@chinakook #17087 is merged, closing this issue.

**Comment by ndeepesh** [comment]
Are there any examples on how to use these operators with MXNet 1.6.0?
