### ISSUE TITLE
Enable anchors on website

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16254]
It would be nice to link to section headings with anchors. I'm pretty sure Jekyll supports this, so it's just a matter of some tinkering on the front-end to get this to work.

**Comment by ys2843** [comment]
On which pages do we need anchors?

**Comment by ChaiBapchya** [comment]
@aaronmarkham gentle ping.
Looks like we do have anchors for section headings. Any specific pages that don't?
