### ISSUE TITLE
website bug: missing documentation

### ISSUE THREAD

**Issue by igolan** [apache/incubator-mxnet#16261]
Hi,
The new website is missing some of the documentations.
[Searching for broadcast_add does not return Symbol/ndarray broadcast_add methods](https://mxnet.incubator.apache.org/api/python/docs/search.html?q=broadcast_add) ( I also couldn't find it in the menu)

It's also true for many other methods (I assume it's the same reason for all of them, so I'm putting only the broadcast_add example).

**Comment by lanking520** [comment]
@aaronmarkham seemed like the search engine is not working properly

**Comment by igolan** [comment]
Still doesn't work (see [https://imgur.com/SAwvEwR](https://imgur.com/SAwvEwR) ).
Just to clarify, it's not about the search, it's about missing documentation (for example, where is Symbol.broadcast_add documentation? can you find it?).

**Comment by Pagey** [comment]
there's also a serious issue with chrome find in the new document pages- it seems that because the docs are not in the main page frame, trying to find (ctrl-F) on the page in chrome doesn't return any hits

**Comment by igolan** [comment]
The missing documentation is now available. Closing.
@Pagey - consider opening a separate issue for the chrome find issue (it is probably due to the usage of multiple frames in the website.)
