### ISSUE TITLE
When using plot_network, I do not see the input data block

### ISSUE THREAD

**Issue by jimxinbo** [apache/incubator-mxnet#1626]
This may sound stupid but am I the only one? 

When repeating the notebook example here: https://github.com/dmlc/mxnet/blob/master/example/notebooks/composite_symbol.ipynb

My visualization does not show the data block at the bottom, but directly starts from the first layer. 

Not a big deal, but it kinda bothers me, any help? Thanks.

**Comment by tqchen** [comment]
@antinucleon can you look into this?

**Comment by horserma** [comment]
I have got the same problem. It seems strange. I am using the latest version of Mxnet.

**Comment by horserma** [comment]
any update on this? I saw this page

**Comment by 5urprise** [comment]
To show input data, replace in python/mxnet/visualization.py in line 65
`heads = set([x[0] for x in conf["heads"]])  # TODO(xxx): check careful`
with
`heads = set(conf["heads"][0])`

**Comment by wshenx** [comment]
@5urprise @jimxinbo @horserma  I have the same problem and I agree that there is something wrong with `heads`. I change `heads` by creating a list containing indices of nodes with `data` or `label` in `nodel['name']`. This might be a quick and dirty way to get things work. I hope the DLMC members can give some hint on this problem. @tqchen @piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
