### ISSUE TITLE
website bug: Symbol.sqaure links to square method link is to the same page (infinite loop)

### ISSUE THREAD

**Issue by igolan** [apache/incubator-mxnet#16260]
Website bug:
[Symbol.sqaure](https://mxnet.incubator.apache.org/api/python/docs/api/symbol/_autogen/mxnet.symbol.Symbol.square.html#mxnet.symbol.Symbol.square)
 refers to square methods but the link is to the same page (infinite loop when clicking "Convenience fluent method for square().")

**Comment by lanking520** [comment]
@aaronmarkham Please take a look

**Comment by aaronmarkham** [comment]
Actually, I'd like someone to explain this to me and how it should work. It seems like the convenience methods in MXNet conflict with how Sphinx works. There might be a way to set this up properly, but so far I'm not aware of one.

`viz` was addressed by adding notes, not by fixing how sphinx does autodoc with it. https://github.com/apache/incubator-mxnet/issues/13232

`onnx` was also addressed with notes.
https://github.com/apache/incubator-mxnet/issues/12318

This `square` method is coming from the `_autogen` folder. I think @ThomasDelteil had to remove a bunch of recursion prior to launch of the new site and that could be a similar thing.

**Comment by igolan** [comment]
It works now, closing.
