### ISSUE TITLE
add custom redirects and 404 page 

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16273]
Since the launch of the new site, there have been a variety of reports of 404s from google search results. 

1. While reindexing should fix this, an interim solution would be a nicer 404 page.
1. Also, some commonly requested URLs could be redirected to their new home.
For example: 
`/install` could go to `/get_started`

A detailed discussion on redirects for the old site can be found here and adapted to the new site:
https://cwiki.apache.org/confluence/display/MXNET/Redirects+on+the+Website

Please note there is already a .htaccess file and a 404 page in the static site. These just need to be linked up.

You can also test deployment on the staging server and this should have redirect enabled.
The code in this pipeline shows how to publish to beta.
http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-website-publish-beta/
One strategy could be to just push your changes to the beta-site branch and preview there.
https://github.com/apache/incubator-mxnet-site/blob/beta-site/.htaccess
This file right now, is in fact, laced with garbage to test.

**Comment by ThomasDelteil** [comment]
This is fixed in https://github.com/apache/incubator-mxnet/pull/16342
