### ISSUE TITLE
New website: where did "Evaluation Metric API" go?

### ISSUE THREAD

**Issue by bricksdont** [apache/incubator-mxnet#16295]
## Description

I was looking at

https://mxnet.incubator.apache.org/versions/master/api/python/metric/metric.html

in the past, which is now a 404.

Where is the page "Evaluation Metric API" now? Where can I find general information about `mxnet.metric`?

**Comment by lanking520** [comment]
Here you go: https://mxnet.apache.org/api/python/docs/api/gluon-related/mxnet.metric.html

**Comment by bricksdont** [comment]
Thanks! In the meantime I learned that there are already several PRs to fix the website issues - closing for now.
