### ISSUE TITLE
in new doc,search "broadcast_div" only find sparse

### ISSUE THREAD

**Issue by yajiedesign** [apache/incubator-mxnet#16293]
![image](https://user-images.githubusercontent.com/771744/65742892-b861cc00-e124-11e9-8ee3-12c494d625a0.png)

**Comment by igolan** [comment]
@yajiedesign it is similar to #16261 and it seems to be solved.

**Comment by ys2843** [comment]
This issue was solved. Search "broadcast_div" now shows multiple results as show below:

<img width="1440" alt="Screen Shot 2020-06-20 at 9 31 32 PM" src="https://user-images.githubusercontent.com/23468760/85216772-a02e7e80-b33d-11ea-9b10-c1795189198e.png">
