### ISSUE TITLE
[website] rendering issue on implementing ops faq

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16322]
## Description
Scroll down till you hit the italicized section.
http://mxnet.incubator.apache.org/api/faq/add_op_in_backend

## How to reproduce & test
You can run into the problem following these steps.

1. Run the Jekyll docs build:
```
ci/build.py --docker-registry mxnetci --platform ubuntu_cpu_jekyll /work/runtime_functions.sh build_python_jekyll
```

2. Find the output in `/docs/static_site/build/html` and deploy that to your dev web server.

**Comment by aaronmarkham** [comment]
#16334 fixed a similar issue with just a line break...

**Comment by Kh4L** [comment]
@aaronmarkham I missed this issue... Shall I also add this page to the PR?

**Comment by aaronmarkham** [comment]
@Kh4L sorry I missed your message. Up to you if you want to tackle this issue too.

**Comment by Kh4L** [comment]
@aaronmarkham  I don't see the italicized section anymore. I guess it has been fixed :+1:
