### ISSUE TITLE
[website] global search feature needed

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16323]
## Description

The website would benefit from a global search feature. 

The current search feature provided by sphinx is only for the Python API, is nested deep in the site, and also happens to come with some legacy issues from its origins:
https://github.com/mli/new-docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search

It might be better to just swap out with a more robust feature that is based on an outside indexing of the site and all of its microsites.

**Comment by ChaiBapchya** [comment]
@ys2843 This is done!!!

**Comment by ys2843** [comment]
Thanks, PR: #18288. We can close this issue now
