### ISSUE TITLE
[Website] Table of contents bug

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16349]
For this page - https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html
From top of the page to Neural network section, the right table of contents works as expected
[responsive]

After scrolling down below Neural network section, starting from Contributed routines
https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html#module-mxnet.ndarray.contrib 
Table of content to right hand side seems to be 
a. unresponsive (can't scroll it down, doesn't highlight based on which part of document we are at)
b. leaks over to the footer
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/10992635/66006251-dc921580-e462-11e9-9fe2-941d3671bc83.png">

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [website]

**Comment by aaronmarkham** [comment]
I'm not seeing the a. issue here:
https://mxnet.apache.org/api/python/docs/tutorials/getting-started/gluon_from_experiment_to_deployment.html

There's a little overlap seen like you point out in b. though.
