### ISSUE TITLE
[CI] Julia Windows CPU timeout

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16352]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/PR-16336/6/pipeline/176

#16336 

Violates the 3-hour timeout.

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [CI, Test, Julia]

**Comment by iblis17** [comment]
(cc me)

**Comment by ChaiBapchya** [comment]
@iblis17 has this been fixed? or was it a one-off I encountered? Coz in last 25 days (ever since issue was created) I didn't see this issue pop up

**Comment by iblis17** [comment]
I cannot reproduce it either. I guess it's one-off.

**Comment by ChaiBapchya** [comment]
Alright. Will close it then.
