### ISSUE TITLE
ImportError: cannot import name 'np'

### ISSUE THREAD

**Issue by pedro-abundio-wang** [apache/incubator-mxnet#16388]
I refer this issue, https://github.com/apache/incubator-mxnet/issues/15681.

running the following command:
pip install https://apache-mxnet.s3-accelerate.amazonaws.com/dist/python/numpy/latest/mxnet_cu100-1.5.0-py2.py3-none-manylinux1_x86_64.whl

But my computer install cuda 9.0.
Does mxnet+numpy+cuda9.0 support? Which url can i get this package?

**Comment by eric-haibin-lin** [comment]
@reminisce

**Comment by szha** [comment]
While cuda 9.0 support is not available, cuda 9.2 support is available at https://apache-mxnet.s3-accelerate.amazonaws.com/dist/python/numpy/latest/mxnet_cu90-1.5.0-py2.py3-none-manylinux1_x86_64.whl

**Comment by pedro-abundio-wang** [comment]
Thank you! And one more question.
Can you also provided cuda8.0+mxnet+numpy package url? 
Maybe i need it on some laptop.

**Comment by szha** [comment]
cuda 8.0 will no longer be supported. mxnet supports only the last two major and minor versions of cuda, which also reflects nvidia's support.
