### ISSUE TITLE
Check failed: (param_.workspace) >= (required_size) 

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#1638]
Hi guys,
When I tried this code:

```
data = mx.symbol.Variable("data")

conv1 = mx.symbol.Convolution(data=data, kernel=(3,3), pad=(1,1), workspace=512, num_filter=64, name="conv1")
relu1 = mx.symbol.Activation(data=conv1, act_type="relu", name="relu1")
conv2 = mx.symbol.Convolution(data=relu1, kernel=(3,3), pad=(1,1), workspace=512, num_filter=64, name="conv2")

executor = conv2.simple_bind(ctx=mx.cpu(),data=(1,3, 1024, 2048),grad_req="null")

executor.forward(is_train=False)
pred = executor.outputs[0].asnumpy()
```

I got an error

```
Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 763363328 Bytes
Given: 536870912 Bytes
```

When I increase the workspace as 

```
data = mx.symbol.Variable("data")

conv1 = mx.symbol.Convolution(data=data, kernel=(3,3), pad=(1,1), workspace=2048, num_filter=64, name="conv1")
relu1 = mx.symbol.Activation(data=conv1, act_type="relu", name="relu1")
conv2 = mx.symbol.Convolution(data=relu1, kernel=(3,3), pad=(1,1), workspace=2048, num_filter=64, name="conv2")

executor = conv2.simple_bind(ctx=mx.cpu(),data=(1,3, 1024, 2048),grad_req="null")

executor.forward(is_train=False)
pred = executor.outputs[0].asnumpy()
```

I got an new one

```
Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 5368709120 Bytes
Given: 2147483648 Bytes
```

I checked out some previous issues, but it did not help. Why it increases the demand after I give it more memory?
BTW, I do use the newest version of MXNet. Anyone can help?

**Comment by piiswrong** [comment]
You have 2 conv layers. The layer one requires more memory

**Comment by ascust** [comment]
Actually, what confused me is that when I do this in gpu mode, I dont even set this workspace (use default 512). But when I do this in cpu mode, even I set this to the limit 4096, still it does not work. I am sure my memory is sufficient, what is the point here. Thanks. @piiswrong

**Comment by ascust** [comment]
I also found if I used cudnn, there would be no problem at all. I used the whole fcn-x16 with 1024x2048 input size, which only took 2500m gpu memory. However, if I used cuda only without cudnn, or cpu only, the error kept showing up. Even though I only used very first two layers to test instead of the whole network like what I posted above. Is it supposed to be like this? @piiswrong

**Comment by rollingstone** [comment]
Hi slightly unrelated issue here, hopefully the issue will be addressed,..

First of all, Thanks  for the fcn implementation.

I tried to download the following files for using with fcn

VOC2012.rar 1.79G
VGG_FC_ILSVRC_16_layers-0074.params 527.8M 
FCN8s_VGG16-0019.params 515.9M 
FCN8s_VGG16-0019-cpu.params

could not succeed. Always timeout issue.....

would it be possible to upload the files to google drive?

Thanks a lot

**Comment by jonbakerfish** [comment]
Same problem here. I use the pre-trained VGG19 model converted from Caffe and increase the input size to 1000x1000. No problem if with cudnn, but not for cpu or cuda. Any idea?

**Comment by antinucleon** [comment]
You need to add workspace=2048 or 1024 in convolution symbol parameter.
Usually, larger input require larger workspace
On Wed, May 4, 2016 at 02:47 Jon <notifications@github.com> wrote:

> Same problem here. I use the pre-trained VGG19 model converted from Caffe
> and increase the input size to 1000x1000. No problem if with cudnn, but not
> for cpu or cuda. Any idea?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1638#issuecomment-216814201>
>
-- 
Sent from mobile phone

**Comment by jonbakerfish** [comment]
@antinucleon increase workspace solve the problem. However, from the mxnet doc [Operator Property](http://mxnet.readthedocs.io/en/latest/system/operator.html#operator-property): 

> Request Resources: Operation like cudnnConvolutionForward need a workspace to help computation.

Why there are no errors when mxnet are compiled with cudnn, but failed for with cpu/cuda?

**Comment by antinucleon** [comment]
Because Cudnn is using different algorithm. Different algorithm requires
different workspace
On Wed, May 4, 2016 at 04:15 Jon <notifications@github.com> wrote:

> @antinucleon <https://github.com/antinucleon> increase workspace solve
> the problem. However, from the mxnet doc Operator Property
> <http://mxnet.readthedocs.io/en/latest/system/operator.html#operator-property>:
>
>
> Request Resources: Operation like cudnnConvolutionForward need a workspace
> to help computation.
>
> Why there are no errors when mxnet are compiled with cudnn, but failed for
> with cpu/cuda?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1638#issuecomment-216831204>
>
-- 
Sent from mobile phone

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
