### ISSUE TITLE
CI flaky test: onnx cpu: TypeError: attrib() got an unexpected keyword argument 'convert'

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#16394]
The failing case is observed on both master branch and mkldnn-v1.0 feature branch.

Master branch: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16369/5/pipeline
mkldnn-v1.0 branch: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16263/5/pipeline
```
+ python tests/python-pytest/onnx/backend_test.py

/work/mxnet/python/mxnet/numpy_op_signature.py:62: UserWarning: Some mxnet.numpy operator signatures may not be displayed consistently with their counterparts in the official NumPy package due to too-low Python version 2.7.12 (default, Aug 22 2019, 16:36:40) 

[GCC 5.4.0 20160609]. Python >= 3.5 is required to make the signatures display correctly.

  .format(str(version)))

Traceback (most recent call last):

  File "tests/python-pytest/onnx/backend_test.py", line 89, in <module>

    unittest.TextTestRunner().run(test_suite(BACKEND_TESTS.enable_report()))

  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/test/runner/__init__.py", line 96, in enable_report

    import pytest  # type: ignore

  File "/usr/local/lib/python2.7/dist-packages/pytest.py", line 13, in <module>

    from _pytest.fixtures import fixture, yield_fixture

  File "/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py", line 832, in <module>

    class FixtureFunctionMarker(object):

  File "/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py", line 834, in FixtureFunctionMarker

    params = attr.ib(convert=attr.converters.optional(tuple))

TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by larroy** [comment]
Checking with a dummy PR: https://github.com/apache/incubator-mxnet/pull/16400

**Comment by lanking520** [comment]
Find the root cause: https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert

The pytest is too old to use the attrs. The right way is to upgrade the pytest version

**Comment by TaoLv** [comment]
Thank you @lanking520 . I'm still wondering why the problem is flaky and wasn't caught by CI at the first place.

**Comment by lanking520** [comment]
@TaoLv The root cause was the Python package `attrs` version control. They made the breaking change since 19.10 -> 19.20 on Oct 1. However, our CI has not set a version for this dependency (always use the latest). Actually, the `pytest` package does not require a fixed version of it. It causing the crash on pytest. Upgrading the version would help to solve the problem.

**Comment by TaoLv** [comment]
Thank you for your explanation, @lanking520 . I'm closing this issue now.
