### ISSUE TITLE
Wrong number of output feature maps in inception-bn

### ISSUE THREAD

**Issue by yuzcccc** [apache/incubator-mxnet#1643]
Is the number of the output feature maps of in4c and in4d correct? the output num should be 576, however, I calculate the number by myself and got the num 608. I looked the number in Google's original BN paper, it seems that they get the wrong number too...
in4c: 160+160+160+128=608
in4d: 96+192+192+128=608

**Comment by piiswrong** [comment]
Why should it be 576?

**Comment by yuzcccc** [comment]
@piiswrong In Figure. 5 of google's BN paper, the number is said to be 576
