### ISSUE TITLE
[website] Mxnet official website menu bar background invalid

### ISSUE THREAD

**Issue by kenjewu** [apache/incubator-mxnet#16453]
When the Mxnet official website slides down, there is an error in the menu bar background. The current website has a high latency when visiting the official website in China.

**Comment by haojin2** [comment]
@ThomasDelteil  Any comments on this issue?

**Comment by ThomasDelteil** [comment]
@kenjewu can you share a screenshot if the issue? Or a clip?

**Comment by kenjewu** [comment]
> @kenjewu can you share a screenshot if the issue? Or a clip?
From these two figures, it can be seen that there is a problem with the background fixing when the navigation bar slides down.
![1571320577(1)](https://user-images.githubusercontent.com/27672489/67015830-be4a3c00-f129-11e9-974f-0897010f1908.png)
![1571320610(1)](https://user-images.githubusercontent.com/27672489/67015834-bf7b6900-f129-11e9-87b7-365a379df8c5.png)

**Comment by samskalicky** [comment]
@zachgk assign [@aaronmarkham ]

**Comment by ys2843** [comment]
@aaronmarkham @sandeep-krishnamurthy  This was a problem about JQuery google CDN. Tested locally, without JQuery the navbar can't change background color (as shown in the screen shot). Since we removed the Google CDN and hosted JQuery locally, this problem is solved. 
Issue can be closed.
