### ISSUE TITLE
MXNet on the Cloud Doc Issues

### ISSUE THREAD

**Issue by TEChopra1000** [apache/incubator-mxnet#16479]
There are a few formatting issues on this page, including:

- Code is not showing up in code-blocks
- Misc. characters showing up around sub-headings. 

https://mxnet.incubator.apache.org/api/python/docs/tutorials/deploy/run-on-aws/cloud.html

**Comment by ys2843** [comment]
@TEChopra1000 The contents on `cloud.html` was moved to aws. This issue is not reproducible any more.
