### ISSUE TITLE
CI failed due to DockerHub outage

### ISSUE THREAD

**Issue by stu1130** [apache/incubator-mxnet#16491]
some example of CI failure
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-cpu/detail/PR-16490/1/pipeline

The latest status of DockerHub
https://status.docker.com/pages/533c6539221ae15e3f000031

**Comment by roywei** [comment]
tracked here on docker: https://github.com/docker/hub-feedback/issues/1897

**Comment by stu1130** [comment]
looks like it's working now, will close it if my PR passed the CI
