### ISSUE TITLE
Returned value incorrectly described in the documentation

### ISSUE THREAD

**Issue by 610v4nn1** [apache/incubator-mxnet#16511]
https://github.com/apache/incubator-mxnet/blob/c2bbde75c36be2fef4a5e6d941cc01f5aabd9fd2/src/operator/tensor/ordering_op.cc#L38

The returned values are the indices of the largest values, as shown in the example below.

**Comment by ddavydenko** [comment]
@mxnet-label-bot add [Doc]

**Comment by roywei** [comment]
cc @ChaiBapchya
