### ISSUE TITLE
how to use model data

### ISSUE THREAD

**Issue by sunbozhang** [apache/incubator-mxnet#1651]
hi,everyone!
   i'm newer, after install mxnet, run "mkdir model; python train_mnist.py --model-prefix model/mnist";
i have some model data, like "mnist-0-0001.params, mnist-0-0002.params, ... mnist-0-0010.parms, mnist-0-symbol.json", so how to use this file data?

**Comment by clcarwin** [comment]
https://github.com/dmlc/mxnet/blob/master/tests/python/train/test_mlp.py
```
# load model from checkpoint
model3 = mx.model.FeedForward.load(prefix, num_epoch)
prob3 = model3.predict(val_dataiter)
print prob3    # the result of the predict
```
