### ISSUE TITLE
mxnet 0.10.0  compile fail

### ISSUE THREAD

**Issue by tianlanli** [apache/incubator-mxnet#16516]
`make -j8 > build.log 2>&1`

then

`src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNDescriptor_t" is incompatible with parameter of type "cudnnHandle_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "uint32_t" is incompatible with parameter of type "cudnnRNNDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDropoutDescriptor_t" is incompatible with parameter of type "int"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNInputMode_t" is incompatible with parameter of type "cudnnDropoutDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDirectionMode_t" is incompatible with parameter of type "cudnnRNNInputMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNMode_t" is incompatible with parameter of type "cudnnDirectionMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDataType_t" is incompatible with parameter of type "cudnnRNNMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: too few arguments in function call
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here`

**Comment by tianlanli** [comment]
> `make -j8 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 > build.log 2>&1`
> 
> then :
> 
> `/incubator-mxnet/mshadow/mshadow/././half.h(19): error: class "__half" has no member "x"`
> `Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_op_extended_gpu.o' failed`
> `make: *** [build/src/operator/tensor/sample_op_gpu.o] Error 1`
> 
> ` errors detected in the compilation of "/tmp/tmpxft_00005ec6_00000000-8_elemwise_binary_scalar_op_extended.compute_50.cpp1.ii". Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o' failed make: *** [build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o] Error 1`
> 
> my cuda 10.1

`make -j8 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=0 USE_CUDNN=0 > build.log 2>&1`

then

`/usr/bin/ld: 找不到 -lopenblas`

but in config.mk
`ADD_LDFLAGS = -I/home/ll/software2/OpenBLAS/lib`
`ADD_CFLAGS = -I/home/ll/software2/OpenBLAS/include`

in my .bashrc
`export PATH="/home/ll/software2/OpenBLAS/:$PATH"
export PKG_CONFIG_PATH="/home/ll/software2/OpenBLAS/lib/pkgconfig:$PKG_CONFIG_PATH"
export LD_LIBRARY_PATH="/home/ll/software2/OpenBLAD/lib:$LD_LIBRARY_PATH"`

**Comment by tianlanli** [comment]
> `make -j8 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 > build.log 2>&1`
> 
> then :
> 
> `/incubator-mxnet/mshadow/mshadow/././half.h(19): error: class "__half" has no member "x"`
> `Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_op_extended_gpu.o' failed`
> `make: *** [build/src/operator/tensor/sample_op_gpu.o] Error 1`
> 
> ` errors detected in the compilation of "/tmp/tmpxft_00005ec6_00000000-8_elemwise_binary_scalar_op_extended.compute_50.cpp1.ii". Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o' failed make: *** [build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o] Error 1`
> 
> my cuda 10.1

I try cuda 8 again , wait

**Comment by tianlanli** [comment]
> > `make -j8 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 > build.log 2>&1`
> > then :
> > `/incubator-mxnet/mshadow/mshadow/././half.h(19): error: class "__half" has no member "x"`
> > `Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_op_extended_gpu.o' failed`
> > `make: *** [build/src/operator/tensor/sample_op_gpu.o] Error 1`
> > ` errors detected in the compilation of "/tmp/tmpxft_00005ec6_00000000-8_elemwise_binary_scalar_op_extended.compute_50.cpp1.ii". Makefile:211: recipe for target 'build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o' failed make: *** [build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o] Error 1`
> > my cuda 10.1
> 
> I try cuda 8 again , wait

I shift to cuda-8.0 ,then make

`src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNDescriptor_t" is incompatible with parameter of type "cudnnHandle_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "uint32_t" is incompatible with parameter of type "cudnnRNNDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDropoutDescriptor_t" is incompatible with parameter of type "int"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNInputMode_t" is incompatible with parameter of type "cudnnDropoutDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDirectionMode_t" is incompatible with parameter of type "cudnnRNNInputMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNMode_t" is incompatible with parameter of type "cudnnDirectionMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDataType_t" is incompatible with parameter of type "cudnnRNNMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: too few arguments in function call
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

8 errors detected in the compilation of "/tmp/tmpxft_0000a3de_00000000-11_rnn.compute_50.cpp1.ii".
Makefile:211: recipe for target 'build/src/operator/rnn_gpu.o' failed
make: *** [build/src/operator/rnn_gpu.o] Error 2
make: *** 正在等待未完成的任务....`

**Comment by tianlanli** [comment]
> `make -j8 > build.log 2>&1`
> 
> then
> 
> `src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNDescriptor_t" is incompatible with parameter of type "cudnnHandle_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "uint32_t" is incompatible with parameter of type "cudnnRNNDescriptor_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDropoutDescriptor_t" is incompatible with parameter of type "int"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNInputMode_t" is incompatible with parameter of type "cudnnDropoutDescriptor_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDirectionMode_t" is incompatible with parameter of type "cudnnRNNInputMode_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNMode_t" is incompatible with parameter of type "cudnnDirectionMode_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDataType_t" is incompatible with parameter of type "cudnnRNNMode_t"
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here
> 
> src/operator/./cudnn_rnn-inl.h(435): error: too few arguments in function call
> detected during:
> instantiation of "void mxnet::op::CuDNNRNNOp::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &, const std::vector<mxnet::TBlob, std::allocatormxnet::TBlob> &) [with DType=float]"
> (54): here
> instantiation of "mxnet::op::CuDNNRNNOp::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]"
> src/operator/rnn.cu(20): here`

`8 errors detected in the compilation of "/tmp/tmpxft_0000a3de_00000000-11_rnn.compute_50.cpp1.ii".
Makefile:211: recipe for target 'build/src/operator/rnn_gpu.o' failed
make: *** [build/src/operator/rnn_gpu.o] Error 2
make: *** 正在等待未完成的任务....`

**Comment by marcoabreu** [comment]
Quick question, but is there a specific reason you're using 0.10.0? We already released 1.5.1.

**Comment by tianlanli** [comment]
> Quick question, but is there a specific reason you're using 0.10.0? We already released 1.5.1.

I want to use FGFA(Flow Guided Feature Aggregation) which base mxnet 0.10.0.

I pip install mxnet 1.5.1 l in another ubuntu server , but I can not use FGFA base on 1.5.1 .

another reason is I don't konw how to do about next line from FGFA github.
` For advanced users, you may put your Python packge into ./external/mxnet/$(YOUR_MXNET_PACKAGE), and modify MXNET_VERSION in ./experiments/fgfa_rfcn/cfgs/*.yaml to $(YOUR_MXNET_PACKAGE). Thus you can switch among different versions of MXNet quickly.`

**Comment by tianlanli** [comment]
> You might want to head over to the discuss forum. 0.10.0 isn't supported anymore but maybe the use case you want can be done in a later version.
> English: https://discuss.mxnet.io/
> Chinese: https://discuss.gluon.ai/

thank you , I will try later version again

**Comment by roywei** [comment]
Please use the latest MXNet, and raise a feature request or file a bug if the latest mxnet does not support the feature you want to use.
