### ISSUE TITLE
CI Travis time out 

### ISSUE THREAD

**Issue by roywei** [apache/incubator-mxnet#16535]
Currently travis test is constantly timed out, Temporarily disable it first to unblock PRs.

Note, this happened before and we already disabled nose tests https://github.com/apache/incubator-mxnet/issues/13136

Now we are disabling builds.

**Comment by roywei** [comment]
Update: I disabled Travis directly as we are not testing anything there now.
We can add it back if we can figure out how to get more resources on Travis. according to #13136

**Comment by szha** [comment]
@leezu built a Github Actions based solution for mac verification. It seems more promising and offers comparable usability. Shall we focus on Github Actions instead?

**Comment by roywei** [comment]
Yes, I think Github Actions can replace Travis.

**Comment by leezu** [comment]
Let's consider which tests to run in Github Actions. I see the following commented out tests in the travis.yml

1) CoreML: `python2 -m nose --verbose tools/coreml/test --exclude-test=test_mxnet_image` @apeforest is this now tested elsewhere? Should an equivalent test for Python 3 be re-enabled?
 2) Python unittests. `python -m nose --verbose tests/python/unittest/` though #12706 disabled a number of tests for speed reasons.

**Comment by leezu** [comment]
I enabled the unittests in the osx github actions build in my fork. Runs mostly fine: 
https://github.com/leezu/mxnet/commit/e32e82a6551da0bd5a8ec2847ae10556039c8bda/checks/484044519/logs

It does expose the problem that in the staticbuild `libcustomop_lib.so not found` and `library libsubgraph_lib.so`, failing the respective tests.

**Comment by samskalicky** [comment]
> It does expose the problem that in the staticbuild `libcustomop_lib.so not found` and `library libsubgraph_lib.so`, failing the respective tests.

It looks like the library was being built:
```
2020-03-04T04:31:36.4082230Z [2/566] Building CXX object CMakeFiles/customop_lib.dir/example/extensions/lib_custom_op/gemm_lib.cc.o
2020-03-04T04:31:36.4154920Z clang: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
2020-03-04T04:31:36.4698910Z [3/566] Linking CXX shared library libcustomop_lib.dylib
```

And then the test is looking for: 
```
mxnet.base.MXNetError: library libcustomop_lib.so not found 
```
This is coming from this code:
https://github.com/apache/incubator-mxnet/blob/5cffa744859658d8192041eafcdcfcf176d27482/tests/python/unittest/test_extensions.py#L37-L51

So maybe all we need to do is something like this
https://github.com/samskalicky/incubator-mxnet/commit/981900ac9eff72bd16d2ab42705037280826353f
