### ISSUE TITLE
Same model  but different time-consuming

### ISSUE THREAD

**Issue by fumingxing2015** [apache/incubator-mxnet#16562]
I trained a model (mobilenet v1.0) with my data. when  test the time-consuming .  I found it's slower than the built-in model in gluon.model_zoo,about twice slower. The model have same structure,the only different is the params values. I check the param , I found there are same values very small . Why the different params can make different time-consuming? Should I set some special option to avoid this situation?

**Comment by ddavydenko** [comment]
@fumingxing2015 , could you please provide your model with params? It is not clear from the question and the context why you might be running into increased latencies.

**Comment by ddavydenko** [comment]
@mxnet-label-bot add [Question]

**Comment by fumingxing2015** [comment]
This is my model and params [https://pan.baidu.com/s/1S7bL2rjYSx0AlDKAgfSADw&shfl=sharepset](url)
The OS I use  is Ubuntu 16.04.4 . 
I use single cpu to test the inference time，cpu info: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz.
the model input is 256*128 rgb image , built-in model consume 20ms，my model consume 80ms.
my test code :
`     
  
    ctx = mx.cpu()
    net0 = gluon.nn.SymbolBlock.imports("test.json", ['data'],
                                       "test.params", ctx=ctx)
    net1=model_zoo.get_model('MobileNet1.0', pretrained=True,ctx=ctx)
  
    file0="test_img/0_0.jpg"
    file1="test_img/0_1.jpg"
    x, img = load_test(file0, short=128)

    t0=time.time()
    net0(x)
    mx.nd.waitall()
    t1=time.time()
    print("my model: ",t1-t0)

    t0=time.time()
    net1(x)
    mx.nd.waitall()
    t1=time.time()
    print("built-in model: ",t1-t0)
`

**Comment by fumingxing2015** [comment]
I try to set the small param values ( below e-37 ) to zero,the inference time get normal. Why the small values can  affect the running speed . Is there any way to avoid this situation?

**Comment by canteen-man** [comment]
Hi，@fumingxing2015，I meet the same problem.I found the geem compute in convlution is very slow.Both MKL and Openblas are slow.
Do you have any suggestion about this problem.

**Comment by fumingxing2015** [comment]
> Hi，@fumingxing2015，I meet the same problem.I found the geem compute in convlution is very slow.Both MKL and Openblas are slow.
> Do you have any suggestion about this problem.

I only set the  small values to zero ,this can avoid the speed slow down and keep the accuracy no change.
