### ISSUE TITLE
Python CPU single thread configuration

### ISSUE THREAD

**Issue by deHsien** [apache/incubator-mxnet#16563]
I'm going to participate in submission limited to use CPU single thread. My implementation is in Python and I found that when import mxnet, a threadpool is created. After trying for a long time, I can only reach a threadpool with 8 threads with MXNET_ENGINE_TYPE=NaiveEngine and OMP_NUM_THREADS=1.  
Is there a configuration to reach a threadpool with 1 thread.  
Thank you.

**Comment by deHsien** [comment]
@pengzhao-intel
May I have your help, thank you

**Comment by pengzhao-intel** [comment]
@ZhennanQin could help you on the topic :)

**Comment by ddavydenko** [comment]
@mxnet-label-bot add [Question]

**Comment by ZhennanQin** [comment]
Please try `export MXNET_USE_OPERATOR_TUNING=0`. Also, default data loader will occupy extra threads for data processing, please consider to use dummy data or activate cpu optimized data loader to avoid data loader using extra threads.

**Comment by deHsien** [comment]
@ZhennanQin Thank you so much!  
With MXNET_USE_OPERATOR_TUNING=0 MXNET_ENGINE_TYPE=NaiveEngine OMP_NUM_THREADS=1 , it works!!

**Comment by pengzhao-intel** [comment]
@apeforest @Vikas-kum I am still thinking to switch off `MXNET_USE_OPERATOR_TUNING` by default.
What's your opinion?
