### ISSUE TITLE
How to initialize a CPU tensor in custom cu file?

### ISSUE THREAD

**Issue by vasusingla619** [apache/incubator-mxnet#16596]
I am trying to initialize a CPU tensor for a new operator in .cu file.

Stream<cpu> *cpu_stream = ctx.get_stream<cpu>();

Tensor<cpu, 1> workspace = ctx.requested[proposal::kTempSpace].get_space<cpu>(Shape1(workspace_size * 5), cpu_stream);

but this fails. I believe this issue may be that I am using reference ctx provided in the operator, which may be GPU, and hence can't init a tensor on CPU.

Is there a workaround to initialize tensors on CPU while working on a .cu file?

**Comment by haojin2** [comment]
@vasusingla619 If you're asking how to create a temporary CPU memory space in a .cu file, you can simply do this:
```c++
void YourFunction(...) {
    vector<char> temp_buffer(workspace_size * 5, 0);
    Tensor<cpu, 1, char> workspace(temp_buffer.data(), Shape1(workspace * 5));
}
```
Lemme know if this solves your question.

**Comment by vasusingla619** [comment]
Thanks, this was solved!
