### ISSUE TITLE
Where is this op.h file ?

### ISSUE THREAD

**Issue by CoinCheung** [apache/incubator-mxnet#16601]
## Description
I did not find the `op.h` file in the directory.  But I find this op.h is included here: 
https://github.com/apache/incubator-mxnet/blob/c3395ca60b20f4388dd76746696497148b82fc80/cpp-package/include/mxnet-cpp/MxNetCpp.h#L37

### Error Message
The make command give the error of: 
/root/build/incubator-mxnet/cpp-package/include/mxnet-cpp/optimizer.hpp:37:26: fatal error: mxnet-cpp/op.h: No such file or directory
compilation terminated.

**Comment by wkcn** [comment]
`op.h` will be generated automatically when building MXNet.

**Comment by CoinCheung** [comment]
Thanks, I tried to compile from source but the `libmxnet.so` does not generated to `incubator-mxnet/lib`. It is just generated to the directory of build/.


My compile command is like this: 
```
mkdir -p build
cmake -DUSE_CUDA=1 -DUSE_CUDA_PATH=/usr/local/cuda -DUSE_CUDNN=1 -DUSE_CPP_PACKAGE=1 -DCMAKE_BUILD_TYPE=Release -GNinja ..
ninja
```
Then the `libmxnet.so` is generated to the current directory of build, and there is still no `op.h` in the `cpp-package/include` folder.

Did I followed the wrong compiling tutorial ?  I did as told in [this](https://mxnet.apache.org/get_started/cpp_setup.html) page.

**Comment by wkcn** [comment]
I use Makefile to compile MXNet. Maybe cmakr approach does not generate op.h.

op.h can be generated manually: 

cd cpp-package/scripts/
python OpWrapperGenerator.py ../../lib/libmxnet.so

The path of libmxnet.so need to be modified.

**Comment by CoinCheung** [comment]
Yes, I generated `op.h` successfully. I noticed that you can generate `libmxnet.so` in `incubator-mxnet/lib`, but I can only generate it to `incubator-mxnet/build` which is my build directory. How did you generate it to `lib/` ?

**Comment by wkcn** [comment]
I use `Makefile` to build MXNet. If using `CMake` to build MXNet, `libmxnet.so` will be created in `incubator-mxnet/build` : )

**Comment by wkcn** [comment]
In `CMakeLists.txt`, `USE_CPP_PACKAGE=OFF` by default, so `op.h` will not be generated.
https://github.com/apache/incubator-mxnet/blob/4e03e6ac20dcf885b39792ebf4fd9e695e8f3eac/CMakeLists.txt#L40

**Comment by CoinCheung** [comment]
Thanks for replying. 

Did I configure the building process correctly if the `libmxnet.so` is generated in the `build/` folder ?

**Comment by wkcn** [comment]
@CoinCheung Yes. You can use `python OpWrapperGenerator.py <the path of libmxnet.so>` to generate the op.h.

**Comment by CoinCheung** [comment]
Thanks, I am closing this.
