### ISSUE TITLE
Python Symbol Package Docs Missing

### ISSUE THREAD

**Issue by TEChopra1000** [apache/incubator-mxnet#16633]
The Symbol docs are no longer in the python packages docs folder. 

The folder was present here: https://github.com/apache/incubator-mxnet/tree/7126438911f0335cdcdf48e76b2aa0f758a131be/docs/python_docs/python/tutorials/packages

And then removed after this PR: https://github.com/apache/incubator-mxnet/tree/8004a027ad6a73f8f6eae102de8d249fbdfb9a2d/docs/python_docs/python/tutorials/packages

A few tutorials link to the Symbol docs. I can remove these links if the docs are not going to be put back into the repo.

**Comment by samskalicky** [comment]
@lanking520 assign @TEChopra1000 
@mxnet-label-bot remove [Bug]

**Comment by TEChopra1000** [comment]
I will take out reference to the Symbol tutorials in the docs.

**Comment by TEChopra1000** [comment]
@aaronmarkham or @lanking520 the Symbol tutorials have been removed, this ticket can be closed.
