### ISSUE TITLE
where to download a old version mxnet R package?

### ISSUE THREAD

**Issue by zhaoliang0302** [apache/incubator-mxnet#16645]
I need mxnet_0.10.1.tar.gz

**Comment by leezu** [comment]
The code is available here on Github. https://github.com/apache/incubator-mxnet/releases/tag/v0.10.0

I'm not sure about the difference to 0.10.1. Maybe you can try with 0.10.0 first.
Possibly 0.10.1 is just the tip of the https://github.com/apache/incubator-mxnet/commits/v0.10.0-support branch

**Comment by zhaoliang0302** [comment]
> The code is available here on Github. https://github.com/apache/incubator-mxnet/releases/tag/v0.10.0
> 
> I'm not sure about the difference to 0.10.1. Maybe you can try with 0.10.0 first.
> Possibly 0.10.1 is just the tip of the https://github.com/apache/incubator-mxnet/commits/v0.10.0-support branch

Thanks, I found a branch of v0.10.0 and I don't know how to download it as an R package (https://github.com/apache/incubator-mxnet/tree/v0.10.0-support/R-package)

**Comment by leezu** [comment]
You need to follow the build from source instructions:
https://github.com/apache/incubator-mxnet/blob/8713d257cde97a660a459aa8a50a780944cf823c/docs/get_started/build_from_source.md#build-mxnet-from-source
and
https://github.com/apache/incubator-mxnet/blob/8713d257cde97a660a459aa8a50a780944cf823c/docs/get_started/build_from_source.md#build-the-r-package

I'll close the issue for now, but please reopen if there is any problem.
Note though that such old releases don't receive any support / fixes anymore.

**Comment by zhaoliang0302** [comment]
I don't have linux system and don't know how to build, is there a mirror website to download  this version R package file (tzr.gz format)?
Much thanks

**Comment by leezu** [comment]
You can use `aws s3 ls --recursive s3://apache-mxnet/R/CRAN/` to list the available pre-built packages. Prebuilt packages for windows and OS X for R 3.4 seem available.

**Comment by zhaoliang0302** [comment]
Can you help me download the v0.10.0 packege file for windows for me? I only have windows system and the terminal code is not allowed.

**Comment by leezu** [comment]
R/CRAN/bin/windows/contrib/3.4/mxnet_0.10.1.zip

**Comment by leezu** [comment]
https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/windows/contrib/3.4/mxnet_0.10.1.zip
