### ISSUE TITLE
[Numpy] Boolean array bug

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#16658]
```python
import mxnet as mx
import numpy as np
from mxnet.gluon import HybridBlock
mx.npx.set_np()

class CastBlock(HybridBlock):
	def hybrid_forward(F, x):
		return x.astype(np.float32)

f_cast = CastBlock()
f_cast.hybridize()
out = f_cast(mx.np.ones((10,)) > 0)
print(out)
```

```
MXNetError: [09:43:24] src/operator/tensor/elemwise_unary_op.h:461: Unknown type enum 7
```

**Comment by sxjscience** [comment]
The problem only occurs after I called hybridize.

**Comment by sxjscience** [comment]
After offline discussion with @haojin2, it could be solved by fixing this line https://github.com/apache/incubator-mxnet/blob/86ed5f5c0a72d1e34b29b0396432d04888274ce2/src/operator/tensor/elemwise_unary_op.h#L454 to add WITH_BOOL

**Comment by reminisce** [comment]
boolean ndarrays are only supported in a few ops right now. We need to enable them gradually in more ops. Thanks for reporting this.

**Comment by sxjscience** [comment]
@reminisce I agree. At least we should fix cast, otherwise we cannot use `>`, `<`.

**Comment by reminisce** [comment]
@sxjscience  `astype` should be working with boolean ndarrays. I think using `cast` is not as pythonic as using `astype`.

**Comment by sxjscience** [comment]
@reminisce In this case, `.astype` will not trigger the error if the block is not hybridized. However, once it's hybridized, it will report the error message.

**Comment by reminisce** [comment]
@sxjscience I will investigate to see why there is a such difference.

**Comment by reminisce** [comment]
In imperative mode, `astype` used `copy` operator which has fully supported boolean ndarrays, while in symbolic mode, `astype` calls `cast`, which has not been fully enabled to support boolean ndarrays.
