### ISSUE TITLE
How does weight tying work in MxNet?

### ISSUE THREAD

**Issue by zeeshansayyed** [apache/incubator-mxnet#16684]
Hi, I have a question regarding weight tying in the encoder and decoder embedding matrix of the NMTModel. Consider [these lines](https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/translation.py#L84-L130) of the NMTModel class.

As has been described in Issue #7785 and [this section](https://d2l.ai/chapter_deep-learning-computation/parameters.html#tied-parameters) in d2l.ai, we usually do it by calling the `params` argument of the layer new layer and pass the params of the layer from which we want to tie.

But in the NMTModel class referenced above, we are simply assigning the references in line 98 and 101 as `self.src_embed = src_embed` and `self.tgt_embed = self.src_embed`.

_Is this also a valid way of tying weights?_

**Comment by leezu** [comment]
I'll respond in https://github.com/dmlc/gluon-nlp/issues/996
