### ISSUE TITLE
ReLU6 and Swish function

### ISSUE THREAD

**Issue by ShoufaChen** [apache/incubator-mxnet#16696]
## Description
(A clear and concise description of what the feature is.)
- If the proposal is about a new model, provide description of what the model is.
- If the proposal is about an API, provide mock examples if possible.

Currently, the `ReLU6()` is implemented by the `clip()`, which is very inefficient. 
Is there any way to implement this function that save gpu memory?

Same request as the `Swish`  funcition.

## References
- list reference and related literature
[Swish ](https://arxiv.org/abs/1905.02244)
[ReLU6  MobileNetv2](https://arxiv.org/abs/1801.04381)
- list known implementations
[memory-efficient Swish activation](https://github.com/lukemelas/EfficientNet-PyTorch/issues/18#issuecomment-511677853)
[TensorFlow ReLU6()](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/nn_ops.py#L2780-L2797)

**Comment by ZhennanQin** [comment]
Also lack for h-sigmoid/h-swish which introduced by mobilenet v3.

**Comment by ptrendx** [comment]
Recently merged pointwise fusion for GPU should handle both of those functions (so you can have implementation that uses multiple operators like in current Relu6 implementation and it will be converted to efficient GPU kernel in the backend).

**Comment by ShoufaChen** [comment]
related issue  [Does HardSwish cost much more memory than ReLU6?](https://github.com/dmlc/gluon-cv/issues/1021)

When I use the gluocv mobilenetv2 script, found that the `ReLU6`  cost 2G more gpu memory than the `nn.Activation('relu')`.   may be the implementation of the ReLU6 of Gluoncv [here]( https://github.com/dmlc/gluon-cv/blob/master/gluoncv/nn/block.py#L45-L57 ) can be improved?

And use the [HardSwish](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/nn/block.py#L73-L85) will cause `out of memory` for MobileNetv2.

**Comment by ptrendx** [comment]
Please try with the newest version of MXNet (that fusion PR is very recent so you will need a nightly version of MXNet for it). It should help with the memory consumption.

**Comment by ShoufaChen** [comment]
Thank you very much! 
I'll try it.
