### ISSUE TITLE
Example link of the image classification show 404

### ISSUE THREAD

**Issue by stereomatchingkiss** [apache/incubator-mxnet#16724]
I keep getting error 404 when I try to read the image classification examples--https://mxnet.apache.org/tutorials/python/predict_image.html

**Comment by stereomatchingkiss** [comment]
True link should be -- https://github.com/dmlc/mxnet-notebooks/blob/master/python/tutorials/predict_imagenet.ipynb

**Comment by samskalicky** [comment]
@zachgk assign @TEChopra1000

**Comment by zachgk** [comment]
@TEChopra1000 Please comment if you want to take this issue.

**Comment by TEChopra1000** [comment]
@zachgk  I will take the issue.

**Comment by TEChopra1000** [comment]
@stereomatchingkiss would you please point me to the page you were on when you found the broken link?

**Comment by ys2843** [comment]
In https://github.com/apache/incubator-mxnet/pull/16764, this image classification link was removed. @stereomatchingkiss @TEChopra1000
