### ISSUE TITLE
GPU is not enabled for mxnet based word embeddings.

### ISSUE THREAD

**Issue by csharma** [apache/incubator-mxnet#16721]
Hi,

bert_embedding = BertEmbedding(mx.gpu(0))

causes the following error.
Exception has occurred: MXNetError
[15:02:22] C:\Jenkins\workspace\mxnet\mxnet\src\ndarray\ndarray.cc:1295: GPU is not enabled

Please help
best regards,
Cartik
 
## Environment
pip install mxnet-cu90
Run in python code 
>import mxnet as mx
bert_embedding = BertEmbedding(mx.gpu(0))
  
causes error

Exception has occurred: MXNetError
[15:02:22] C:\Jenkins\workspace\mxnet\mxnet\src\ndarray\ndarray.cc:1295: GPU is not enabled

**Comment by sxjscience** [comment]
@csharma Did the machine you are using have GPU support? Also, the python code you provided is not runnable.

**Comment by csharma** [comment]
Add this line,

from bert_embedding import BertEmbedding

Yes, the laptop I am using has GPU support with 2 cuda cores.

Best,
Cartik

**Comment by sxjscience** [comment]
@csharma There is no `bert_embedding` here in MXNet.

**Comment by csharma** [comment]
Add the following line to make it run
from bert_embedding import BertEmbedding

Best,
Cartik

**Comment by sxjscience** [comment]
@csharma Would you ask questions here https://discuss.mxnet.io/ ? The issue page is for bug reports.
