### ISSUE TITLE
Run Java example, GPU, Memory leak

### ISSUE THREAD

**Issue by linven0721** [apache/incubator-mxnet#16751]
## Description
When I tried to run the Java predictor example（[https://github.com/apache/incubator-mxnet/blob/master/scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/predictor/PredictorExample.java]） in a circular way, I found that the memory was growing all the time, 30000 times in a circular way, the memory occupied 20GB and could not be released。
##Jar version
mxnet-full_2.11-linux-x86_64-gpu(1.5.1)
##Running environment
linux 3.10.0-693.el7.x86_64 (gcc version 4.8.5) (Red Hat 4.8.5-16)
cuda-9.2
jdk1.8
gpu:GeForce RTX 2080ti
cpu:Intel Xeon(R) Silver 4110 CPU@2.10GHz

**Comment by lanking520** [comment]
@linven0721 Could you please share your code to run it? Currently we use `ResourceScope` to collect the memory effectively.

**Comment by samskalicky** [comment]
@zachgk assign @lanking520

**Comment by linven0721** [comment]
@lanking520 The code is the java example[PredictorExample.java]. I just added a for loop.
`NDArray img=...;
Predictor predictor=...;
for(;;){
     float[] result = predictor.predict(new float[][] {img.toArray});
}`
There is no memory leak in this code on the CPU, and there will be problems only when it runs on the GPU.
Do you still need me to provide specific running code?

**Comment by lanking520** [comment]
Ok, sounds like you didn't have this:
https://github.com/apache/incubator-mxnet/blob/master/scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/imageclassifier/ImageClassifierExample.scala#L52-L68

**Comment by linven0721** [comment]
@lanking520 It seems to work. Thank you very much
