### ISSUE TITLE
AssertionError: HybridBlock inputs must be (nested) list of Symbol or NDArray, but got 0.0 of type <class 'float'>

### ISSUE THREAD

**Issue by ShoufaChen** [apache/incubator-mxnet#16761]
## Description
(A clear and concise description of what the bug is.)
After I update the Mxnet use `pip install mxnet-cu101mkl` yesterday, I can't pass a float value to `hybrid_forward()` .   
### Error Message
(Paste the complete error message, including stack trace.)
AssertionError: HybridBlock inputs must be (nested) list of Symbol or NDArray, but got 0.0 of type <class 'float'>

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by leezu** [comment]
You need to pass a ndarray. Float value is unsupported and does not work correctly. Previous mxnet version was buggy and didn't check the input value correctly.

**Comment by leezu** [comment]
@sxjscience FYI
