### ISSUE TITLE
Windows build from source failure

### ISSUE THREAD

**Issue by vexilligera** [apache/incubator-mxnet#16762]
## Description
(A clear and concise description of what the bug is.)
I followed the official tutorial for building MXNet with CUDA 9.2 from source using Visual Studio 2017 on Windows Server 2016.
The compilation was successful, however I encountered this linking error:

LINK : fatal error LNK1248: image size (894C8000) exceeds maximum allowable size (80000000) [C:\incubator-mxnet\build\mxnet.vcxproj]

Is there any setting I can tweak to fix this? Thanks.

### Error Message
(Paste the complete error message, including stack trace.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
[Follow this tutorial](https://mxnet.apache.org/get_started/windows_setup.html)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by vexilligera** [comment]
#16033

**Comment by vexilligera** [comment]
#16033

**Comment by yajiedesign** [comment]
the all cuda arch make a too big image size.not use all arch,choose it with you gpu.

**Comment by vexilligera** [comment]
> the all cuda arch make a too big image size.not use all arch,choose it with you gpu.

Thank you, that should work.

**Comment by kimtang** [comment]
I encounter the same problem with -DCUDA_ARCH_LIST=Common. But then when I change to -DCUDA_ARCH_LIST=Pascal I can compile and link it on windows. It would be good to let people know how to compile for a specific gpu card
