### ISSUE TITLE
[Numpy] Transpose does not support kAddTo and kNullOp

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#16789]
https://github.com/apache/incubator-mxnet/blob/02f4f0503de60cce41989f1bb779ee8c7b943e4b/src/operator/numpy/np_matrix_op-inl.h#L122

Also, it does not support kNullOp, which has been supported in https://github.com/apache/incubator-mxnet/commit/56999399a44467cbd1d0fbdf9cbba8b46ac53956#diff-d5c9c7d539907caef01a08a74e16592b

**Comment by sxjscience** [comment]
@leezu

**Comment by leezu** [comment]
Let's consider backporting the fix to `mx.nd.Transpose`.

FYI @zburning

**Comment by samskalicky** [comment]
@lanking520 assign @ChaiBapchya
