### ISSUE TITLE
About OpenMP dependencies

### ISSUE THREAD

**Issue by matteosal** [apache/incubator-mxnet#16805]
Cc'ing @dszeto2

On Linux, when mxnet is built using just make, the library shows a dependency from `libiomp5`. When built through cmake, additional dependencies for `libomp` and `libgomp` show up. Can someone please explain this difference? What are the various omp dependencies needed for?

**Comment by TaoLv** [comment]
libiomp5 has been removed from master if you’re not using MKL BLAS. The problem of two omp runtimes in cmake build is discussed at the end of #11417.

**Comment by matteosal** [comment]
Ah ok thanks for the explanation, and sorry for not having checked existing issues
