### ISSUE TITLE
Python API Links broken

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#16802]
## Description
https://mxnet.apache.org/api/python/docs/api/gluon/index.html links to https://mxnet.apache.org/api/python/docs/api/gluon/mxnet.gluon.Trainer.html instead of the correct https://mxnet.apache.org/api/python/docs/api/gluon/trainer.html

Same for many other API pages.

Therefore google still prefers linking to the beta.mxnet.io page.

**Comment by samskalicky** [comment]
@lanking520 assign @TEChopra1000

**Comment by TEChopra1000** [comment]
I will make the correction.

**Comment by ys2843** [comment]
Verified, this Python API links is fixed. Issue can be closed. @leezu
