### ISSUE TITLE
Trouble building Mxnet 1.6.x

### ISSUE THREAD

**Issue by JonTanS** [apache/incubator-mxnet#16822]
## Description
Failure when trying to build mxnet 1.6.x from source code.

### Error Message
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator_util.h:43,
                 from src/operator/numpy/linalg/np_gesvd.cc:25:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -DDMLC_MODERN_THREAD_LOCAL=0 -O3 -DNDEBUG=1 -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/ -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/tvm/nnvm/include -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/dlpack/include -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/deps/usr/local/cuda-10.1/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_NVTX=1 -DMXNET_USE_SIGNAL_HANDLER=1 -DMXNET_USE_MKLDNN=1 -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/src/operator/nn/mkldnn/ -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPENMP=1 -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_INT64_TENSOR_SIZE=0 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1 -DMXNET_USE_BLAS_OPEN=1 -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/deps/include -ffunction-sections -fdata-sections -DMXNET_USE_DIST_KVSTORE -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/ps-lite/include -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/deps/include -I/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/nvidia_cub -DMXNET_ENABLE_CUDA_RTC=1 -I/include -DMXNET_USE_NCCL=1 -I/include -DMXNET_USE_LIBJPEG_TURBO=1 -MMD -c src/operator/nn/mkldnn/mkldnn_reshape.cc -o build/src/operator/nn/mkldnn/mkldnn_reshape.o
Makefile:555: recipe for target 'build/src/operator/numpy/linalg/np_gesvd.o' failed
make: *** [build/src/operator/numpy/linalg/np_gesvd.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/operator/numpy/random/./dist_common.h:30:0,
                 from src/operator/numpy/random/dist_common.cc:27:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/numpy/random/dist_common.o' failed
make: *** [build/src/operator/numpy/random/dist_common.o] Error 1
In file included from src/operator/numpy/random/./np_choice_op.h:29:0,
                 from src/operator/numpy/random/np_choice_op.cc:26:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/numpy/random/np_choice_op.o' failed
make: *** [build/src/operator/numpy/random/np_choice_op.o] Error 1
In file included from src/operator/numpy/random/./np_uniform_op.h:28:0,
                 from src/operator/numpy/random/np_uniform_op.cc:25:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator_util.h:43,
                 from src/operator/numpy/random/./np_multinomial_op.h:28,
                 from src/operator/numpy/random/np_multinomial_op.cc:25:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/numpy/random/np_uniform_op.o' failed
make: *** [build/src/operator/numpy/random/np_uniform_op.o] Error 1
Makefile:555: recipe for target 'build/src/operator/numpy/random/np_multinomial_op.o' failed
make: *** [build/src/operator/numpy/random/np_multinomial_op.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator_util.h:43,
                 from src/operator/numpy/random/./np_normal_op.h:28,
                 from src/operator/numpy/random/np_normal_op.cc:25:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/numpy/random/np_normal_op.o' failed
make: *** [build/src/operator/numpy/random/np_normal_op.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/op_attr_types.h:29,
                 from include/mxnet/graph_attr_types.h:27,
                 from src/operator/nn/mkldnn/./mkldnn_base-inl.h:58,
                 from src/operator/nn/mkldnn/mkldnn_base.cc:23:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_base.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_base.o] Error 1
In file included from src/operator/nn/cudnn/./../../../common/cuda_utils.h:31:0,
                 from src/operator/nn/cudnn/./cudnn_algoreg-inl.h:35,
                 from src/operator/nn/cudnn/cudnn_algoreg.cc:26:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/mkldnn/../concat-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_concat-inl.h:32,
                 from src/operator/nn/mkldnn/mkldnn_concat.cc:27:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/cudnn/cudnn_algoreg.o' failed
make: *** [build/src/operator/nn/cudnn/cudnn_algoreg.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/cudnn/./../batch_norm-inl.h:31,
                 from src/operator/nn/cudnn/./cudnn_batch_norm-inl.h:33,
                 from src/operator/nn/cudnn/cudnn_batch_norm.cc:27:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_concat.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_concat.o] Error 1
Makefile:555: recipe for target 'build/src/operator/nn/cudnn/cudnn_batch_norm.o' failed
make: *** [build/src/operator/nn/cudnn/cudnn_batch_norm.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/io.h:34,
                 from src/operator/nn/mkldnn/./mkldnn_ops-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_slice.cc:28:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_slice.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_slice.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/io.h:34,
                 from src/operator/nn/mkldnn/../convolution-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_convolution.cc:28:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_convolution.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_convolution.o] Error 1
In file included from /home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:33,
                 from include/mxnet/operator_util.h:43,
                 from src/operator/nn/mkldnn/../../tensor/elemwise_unary_op.h:28,
                 from src/operator/nn/mkldnn/mkldnn_reshape.cc:27:
/home/ubuntu/MXnet_perf/MXnet1.6/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:173:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:555: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_reshape.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_reshape.o] Error 1
make: *** wait: No child processes.  Stop.

## To Reproduce
Clone mxnet and checkout v1.6.x
Copy the pip_linux_cu101mkl.mk command and make. 

### Steps to reproduce
(Paste the commands you ran that produced the error.)
1. git clone --recursive https://github.com/apache/incubator-mxnet.git
2. git checkout v1.6.x
3. git submodule update --recursive --init
4. cd incubator-mxnet
5. cp make/pip/pip_linux_cu101mkl.mk config.mk
6. make -j

## What have you tried to solve it?
Deleting 3rd Party Folder and rechecking it out followed by submodule update

## Environment
Deep Learning AMI (Ubuntu 16.04) Version 25.0

@ptrendx 
@access2rohit

**Comment by access2rohit** [comment]
@ptrendx this will fail the pypi wheel build for v1.6.0. This needs to be investigated. Do you know anyone who has knowledge of mshadow and can look into the issue ?

**Comment by access2rohit** [comment]
@mxnet-label-bot add [Build]

**Comment by haojin2** [comment]
Deep Learning AMI 25.0 has CUDA 10.0 installed, and `make/pip/pip_linux_cu101mkl` is trying to use cuda 10.1's path: https://github.com/apache/incubator-mxnet/blob/master/make/pip/pip_linux_cu101mkl.mk#L69. That's why the error message reads: `fatal error: cuda.h: No such file or directory` Please try again with `make/pip/pip_linux_cu100mkl.mk`

**Comment by jonatan1626** [comment]
After doing: 
`cp make/pip/pip_linux_cu100mkl.mk config.mk`
`make -j`

I still encounter the same error, should I try this on another instance or is there some other issue?

**Comment by haojin2** [comment]
Firstly, I don't think you're doing it according to the recommended way: https://mxnet.apache.org/get_started/ubuntu_setup#build-mxnet-from-source.
Secondly, I'm not sure if there's any documentation on how the release builds are done, but seems like your way of doing it is definitely not how the wheels for releases are built.
Lastly, this config may not be designed to be used in this way. My intuition is that `DEPS_PATH` and some other variables should be set properly before using it.

**Comment by access2rohit** [comment]
@haojin2  `DEPS_PATH` is used when we are statically linking most of our dependencies(https://github.com/apache/incubator-mxnet/tree/master/tools/dependencies) in the wheel using https://github.com/apache/incubator-mxnet/blob/master/tools/staticbuild/build.sh and then building wheel using: https://github.com/apache/incubator-mxnet/blob/master/tools/pip/setup.py.

IMO If someone want to building from source on local instance then they can dynamically link the libs and MXNet should work fine. So, make files provided here: https://github.com/apache/incubator-mxnet/tree/master/make/pip should work fine.

Also, this link: https://mxnet.apache.org/get_started/ubuntu_setup#build-mxnet-from-source does not give the exact flags that are used to build the pypi binaries of MXNet. 

Let me know if this makes sense or am I missing something here.

**Comment by haojin2** [comment]
@access2rohit A thing "should" work only where it's designed to be working. Given the facts that we still seeing successful nightly builds including the GPU versions, I would consider those configs work on a properly set up machine. And, even the `build mxnet from source` link have steps on setting up your machine with required libraries, why would you then assume those config files "should" work out-of-the-box on DL AMI 25.0 without you having to do anything extra? I'm not seeing a valid logic here.
But yes, I think at least we're missing the documentation here, we'll need to find the responsible parties to add the doc on how to use those files properly.

**Comment by access2rohit** [comment]
@haojin2 "even the build mxnet from source link have steps on setting up your machine with required libraries, why would you then assume those config files "should" work out-of-the-box on DL AMI 25.0 without you having to do anything extra?"

Fair Point! and +1 for the documentation. I just checked the nightly I has been restored since last 2 days for pip wheel are indeed building correctly.
