### ISSUE TITLE
Configurable log interval for estimator

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#16918]
Currently the gluon Estimator has a LoggingHandler, which supports logging per batch and per epoch. It would be good to have a configurable logging interval (e.g. logging every 50 batches). Logging per epoch does not provide enough information, while logging per batch is tooooo verbose

**Comment by leezu** [comment]
@liuzh91 would you be interested to fix this given you're currently working on the Estimator API?

**Comment by liuzh91** [comment]
> @liuzh91 would you be interested to fix this given you're currently working on the Estimator API?

I can do this.
