### ISSUE TITLE
Why do I install version 1.2.0 using pip install mxnet?

### ISSUE THREAD

**Issue by shrey183** [apache/incubator-mxnet#16924]
## Description
I am using Python 3.7.0 and I want to install mxnet in order to use gluonts. I write `pip install mxnet` and it always install version 1.2.0 but for gluonts I need version >=1.3.0. So I tried `pip install mxnet==1.3.1` but it gives me the following error message. 

### Error Message
ERROR: Could not find a version that satisfies the requirement mxnet==1.3.0 (from versions: 0.11.1b20170915, 0.11.1b20170922, 0.11.1b20170929, 0.11.1b20171006, 0.11.1b20171013, 0.12.0b20171020, 0.12.0b20171027, 0.12.0, 0.12.1b20171103, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.0.1b20180114, 1.0.1b20180121, 1.0.1b20180128, 1.0.1b20180202, 1.1.0b20180209, 1.1.0b20180216, 1.1.0.post0, 1.2.0b20180223, 1.2.0b20180302, 1.2.0b20180309, 1.2.0b20180323, 1.2.0b20180330, 1.2.0b20180406, 1.2.0b20180413, 1.2.0b20180420, 1.2.0b20180427, 1.2.0b20180504, 1.2.0)
ERROR: No matching distribution found for mxnet==1.3.1

I am not sure what I doing wrong here. Any suggestions would be much appreciated.

**Comment by leezu** [comment]
Why do you want to use MXNet 1.2 or 1.3? GluonTS Readme describes they want `pip install mxnet==1.4.1 gluonts`.
If you already have either MXNet or GluonTS installed, you need to run `pip install --upgrade mxnet==1.4.1 gluonts`.

In the near future, GluonTS will also support MXNet 1.5. They are currently waiting for the MXNet 1.5.2 release: https://github.com/awslabs/gluon-ts/pull/245

**Comment by shrey183** [comment]
I tried as you suggested and got the following error message:


ERROR: Could not find a version that satisfies the requirement mxnet==1.4.1 (from versions: 0.11.1b20170915, 0.11.1b20170922, 0.11.1b20170929, 0.11.1b20171006, 0.11.1b20171013, 0.12.0b20171020, 0.12.0b20171027, 0.12.0, 0.12.1b20171103, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.0.1b20180114, 1.0.1b20180121, 1.0.1b20180128, 1.0.1b20180202, 1.1.0b20180209, 1.1.0b20180216, 1.1.0.post0, 1.2.0b20180223, 1.2.0b20180302, 1.2.0b20180309, 1.2.0b20180323, 1.2.0b20180330, 1.2.0b20180406, 1.2.0b20180413, 1.2.0b20180420, 1.2.0b20180427, 1.2.0b20180504, 1.2.0)
ERROR: No matching distribution found for mxnet==1.4.1

**Comment by leezu** [comment]
Strange. Please run the diagnosis script that you were requested to run when creating the issue: `curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python`
