### ISSUE TITLE
autograd.is_training() does not work on hybridized networks.

### ISSUE THREAD

**Issue by Wallart** [apache/incubator-mxnet#16926]
Hello everyone,
I might have found an issue about autograd.is_training().

I've implemented a transformer. At training time my network is returning predictions and attention weights for plotting. During inference it's only returning predictions. After the training phase I'm doing validation on a new dataset. Here is a basic description of the problem

Training loop core : 
``` 
with autograd.record():
  output, attn_w_1, attn_w_2 = transformerNet(someInputs)
  # loss compute, backward, trainer step, etc.
output = transformerNet(someInputs)
# compute validation score
```
Transformer hybrid_forward end :

```
if autograd.is_training():
   return logits, attn_w_1, attn_w_2
return logits
```

Everything is working fine except when I hybridize the network. During validation autograd.is_training() is always true and the method returns 3 variables instead of 1.

I am using MXNet 1.5.1. Is this behavior normal. If so it should be added to hybridize() documentation

**Comment by leezu** [comment]
Hybridization traces the input during the first forward pass to the hybridized network. Afterwards it will re-use the computational graph established during the initial trace.

To solve your issue, simply create two instances of your network. Both should share parameters and both can be hybridized. Just use one of them for training, the other one for validation.

You're very welcome to submit a PR that clarifies the documentation.

**Comment by leezu** [comment]
@Wallart would https://github.com/apache/incubator-mxnet/issues/16932 be helpful? Please comment there if you have any concerns.

**Comment by Wallart** [comment]
@leezu Thank you for your answer.
I will submit a PR to clarify the documentation
