### ISSUE TITLE
Including original Numpy Sort methods 

### ISSUE THREAD

**Issue by GPoloVera** [apache/incubator-mxnet#16939]
## Description
Include in the mxnet.numpy interface functions from the numpy package 

- numpy.sort(a, axis =1, kind=None , order=None ): This is a package function

- numpy.ndarray.sort(axis=-1, kind=None , order=None): This is an instance method

- numpy.argsort(a, axis=-1 , kind=None, order=None): This is a package function

The idea is to use them within a autograd.record() context and being able to compute the gradient of functions that use them.

## References
- numpy.argsort: https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html#numpy.argsort
- numpy.sort:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html#numpy.sort
- numpy.ndarray.sort: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.sort.html#numpy.ndarray.sort

Thank you very much

**Comment by sxjscience** [comment]
I think there is an open PR that tries to add sort: https://github.com/apache/incubator-mxnet/pull/16750

**Comment by haojin2** [comment]
PR for `np.argsort`: #16949

**Comment by eric-haibin-lin** [comment]
looks like the feature is added already
