### ISSUE TITLE
Accuracy drops a lot when AdaGrad restarts training

### ISSUE THREAD

**Issue by futurely** [apache/incubator-mxnet#1695]
If AdaGrad is used as the optimizer, the train accuracy starts from about 35% after loading a model of about 50% accuracy. It takes another epoch for the accuracy to get back to the last epoch's level. The reason is probably because the state of the AdaGrad optimizer is not saved in the model. It would save much training time to save and load the optimizer's state along with the model parameters.

**Comment by piiswrong** [comment]
Yes, this is probably because we are not saving optimizer states. It's not a big issue for SGD.
And option of saving optimizer could be helpful.

**Comment by magic282** [comment]
So how can we save the optimizer states and reload when resuming the training?
