### ISSUE TITLE
Unable to hardcode the OMP_NUM_THREADS into program

### ISSUE THREAD

**Issue by MediosZ** [apache/incubator-mxnet#16961]
Hi, I want to run mxnet in single thread mode, and for some reason I can't set environment variables.
First I recompile the library without MKL-DNN and OpenMP support using the latest code and hardcode "MXNET_ENGINE_TYPE=NaiveEngine"
Then I want to set OMP_NUM_THREADS=1 in a similar way.

Here's what I done, I modify some code in openmp.cc
```c++
OpenMP::OpenMP()
  : omp_num_threads_set_in_environment_(true) {
    enabled_ = true;
    omp_thread_max_ = 1;
}

void OpenMP::on_start_worker_thread(bool use_omp) {
  omp_set_num_threads(1);
}

void OpenMP::set_reserve_cores(int cores) {
  
  CHECK_GE(cores, 0);
  reserve_cores_ = cores;
  omp_set_num_threads(1);
}

int OpenMP::GetRecommendedOMPThreadCount(bool exclude_reserved) const {
  return 1;
}
```

But the program will create 56 workers as usual.
When I set environment variable OMP_NUM_THREADS=1, there would be only one worker.
I don't see how the program would handle this environment variable.
And if I really want to hardcode this, what should I do?
Thanks a lot!

**Comment by ZhennanQin** [comment]
Can you list the mxnet build cmd? If you're using openblas, I doubt the openmp threads are introduced by it. Maybe you can try to rebuild openblas without openmp.

**Comment by MediosZ** [comment]
Yes, the threads are created by openblas, and I rebuild the openblas setting the number of threads to one, then problem solved.
Thanks @ZhennanQin

**Comment by AyushP123** [comment]
@MediosZ how did you rebuild openblas setting the number of threads to one??. And by your responses I understood that OpenMP wasn't the issue, it was OpenBlas. Please correct me if I am wrong.

**Comment by AyushP123** [comment]
Setting `OPENBLAS_NUM_THREADS=1` also limits the number of threads to 1.
