### ISSUE TITLE
Array initialization and indexing is inconsistent with official numpy 

### ISSUE THREAD

**Issue by Alicia1529** [apache/incubator-mxnet#16991]
## Description
Two consistencies with official Numpy
1. when initializing a ndarray, the data type of official Numpy array will be casted to the input data type. DeepNumpy will set the default data type to be float32 unless the dtype parameter is explicitly declared.
```
>>> import numpy as onp
>>> from mxnet import numpy as np
>>> a = np.array([1, 2, 3, 4, 5])
>>> a
array([1., 2., 3., 4., 5.])
>>> a.dtype
dtype('float32')
>>> oa = onp.array([1, 2, 3, 4, 5])
>>> oa
array([1, 2, 3, 4, 5])
>>> oa.dtype
dtype('int64')
```
2. when indexing a 1-d array, the return type of numpy array is a value, while the return type of deenumpy array is still a deenumpy array.
```
a[0] # array([12.])
oa[0] # 12
```

**Comment by samskalicky** [comment]
@apeforest assign @mli

**Comment by sxjscience** [comment]
@Alicia1529 For the second question, I think you will need to use `mx.npx.set_np()` to enable numpy-compatible behavior. 
```python
import mxnet as mx
mx.npx.set_np()
a = np.array([1,2,3,4,5])
print(a[0]) # array(1.)
```

**Comment by yzhliu** [comment]
For the first first issue, I think it is intended as we try to make deep learning the first class. We will provide a global default dtype setting to switch the behavior.

**Comment by yzhliu** [comment]
default dtype landed in https://github.com/apache/incubator-mxnet/pull/18251
