### ISSUE TITLE
Built from source uses old version of opencv

### ISSUE THREAD

**Issue by LukasAdamowicz** [apache/incubator-mxnet#17061]
## Description
Following the directions for building from source [HERE](https://mxnet.incubator.apache.org/get_started/osx_setup.html) for MacOS Catalina, the instructions say to 

```shell script
brew install opencv@3
````
However, once the build finishes, attempting to `import mxnet` results in the an error that it can't find the FFMPEG library `libavcodec.57.dylib`, which is the case because the current version of FFMPEG is up to `libavcodec.58.dylib`. 

Fixing the import error can be achieved by uninstalling, updating OpenCV to the newest version (`4.x`, instead of `3.x`), and re-building from source.  Afterwards, `import mxnet` raises no errors.

### Error Message
Something along the lines of `unable to import mxnet: resource libavcodec.57.dylib not loaded - does not exist.` Don't have the error message anymore after updating OpenCV

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Build from source (with MKL) following instructions  [HERE](https://mxnet.incubator.apache.org/get_started/osx_setup.html)
2. try `import mxnet` in python

## What have you tried to solve it?

1. Update OpenCV to 4.x (instead of 3), rebuild from source - fixed the import error

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
----------Python Info----------
Version      : 3.6.9
Compiler     : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Build        : ('default', 'Jul 30 2019 13:42:17')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.3.1
Directory    : /Users/LukasAdamowicz/opt/anaconda3/envs/face_mxnet/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.6.0
Directory    : /Users/LukasAdamowicz/mxnet/python/mxnet
Num GPUs     : 0
Hashtag not found. Not installed from pre-built package.
----------System Info----------
[14:11:56] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
Platform     : Darwin-19.0.0-x86_64-i386-64bit
system       : Darwin
node         : Lukas-Tower.pfizer.com
release      : 19.0.0
version      : Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: RDWRFSGS SMEP ERMS MDCLEAR IBRS STIBP L1DF SSBD'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF RDTSCP TSCI'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0123 sec, LOAD: 0.3735 sec.
Timing for GluonNLP GitHub: https://github.com/dmlc/gluon-nlp, DNS: 0.0004 sec, LOAD: 0.3750 sec.
Timing for GluonNLP: http://gluon-nlp.mxnet.io, DNS: 0.0960 sec, LOAD: 0.3642 sec.
Timing for D2L: http://d2l.ai, DNS: 0.0550 sec, LOAD: 0.0862 sec.
Timing for D2L (zh-cn): http://zh.d2l.ai, DNS: 0.0418 sec, LOAD: 0.2608 sec.
Timing for FashionMNIST: https://repo.mxnet.io/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0847 sec, LOAD: 0.4442 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0304 sec, LOAD: 0.3734 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0284 sec, LOAD: 0.0769 sec.
```

**Comment by leezu** [comment]
Would you like to open a PR to update the doc (to recommend version 4)?
