### ISSUE TITLE
can't install mxnet through pip install command

### ISSUE THREAD

**Issue by LittleFatHero** [apache/incubator-mxnet#17089]
os: ubuntu 18.04
python: 3.6

problem : When I install mxnet-cu101 using the following command:
```
pip install mxnet-cu101
```
I can't install, it said the Hash values do not match.
I change another computer and network, there is still the same problem. 
I guess it is because the update of the mxnet and cause the software source error.
please fix the problem as soon as possible.

the following is the error information：
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    mxnet-cu101 from https://pypi.tuna.tsinghua.edu.cn/packages/57/aa/474e97edaa2064c4e57dfb5685290ffc188592878c8bc58a1dca770872b5/mxnet_cu101-1.5.1.post0-py2.py3-none-manylinux1_x86_64.whl#sha256=5eb6f1ba3ad76f39cfb980848065b65af509dcd7b48a2cb3c62a622baf961022:
        Expected sha256 5eb6f1ba3ad76f39cfb980848065b65af509dcd7b48a2cb3c62a622baf961022
             Got        c26a55c4d5b85a0f8f69b42887d6006b3bfd9db216a8780086735106dbee5315
```

**Comment by leezu** [comment]
There seem to be frequent problems with the tsinghua mirror. Another user reported similar problems earlier this month.

Please use a different mirror or the original pypi repo.

**Comment by leezu** [comment]
In particular, you can download the file here: https://files.pythonhosted.org/packages/57/aa/474e97edaa2064c4e57dfb5685290ffc188592878c8bc58a1dca770872b5/mxnet_cu101-1.5.1.post0-py2.py3-none-manylinux1_x86_64.whl
