### ISSUE TITLE
How to use system mkldnn?

### ISSUE THREAD

**Issue by jiapei100** [apache/incubator-mxnet#17107]
Can those 3rdparty libraries be replaced by system installed ones?
If so, how?

**Comment by TaoLv** [comment]
No, you cannot do that. MXNet usually depends on certain version (commit id) of MKL-DNN and it's statically linked as a part of libmxnet.so.

**Comment by leezu** [comment]
@TaoLV will newer versions of DNN provide backwards compatibility? Ie can we relax the current "depends on commit id" requirement to minimum version requirement in the future?

**Comment by TaoLv** [comment]
@leezu MKL-DNN follows the semantic versioning 2.0 so it's backwards compatible for minor versions and might be not compatible for major versions.

> Ie can we relax the current "depends on commit id" requirement to minimum version requirement in the future?

We cannot do that without a lot of MKL-DNN version check inside MXNet. My opinion:
1. We don't encourage MXNet users to use older versions of MKL-DNN as they might lack some good features which are already integrated into MXNet.
2. We don't encourage MXNet users to use newer versions of MKL-DNN as they are not fully validated on MXNet side. It will propagate MKL-DNN issues to MXNet. But I think check out a new patch release under the same minor version should be safe.
3. MXNet is keeping a good pace with MKL-DNN releases. AFAIK, MXNet is the first DL framework that upgrades to MKL-DNN v1.0 (ready for 1.6 release) and v1.1 (on master branch).

**Comment by TaoLv** [comment]
I'm closing this issue as it seems not a valid request. Feel free to reopen if any concern. Thanks!
