### ISSUE TITLE
Train and Validation Metric Evaluation

### ISSUE THREAD

**Issue by RishabGargeya** [apache/incubator-mxnet#1712]
Hi,

I was just wondering how metrics are evaluated at the end of a training epoch and during validation afterwards. Is it the mean metric value per batch? 

If so, at least for validation wouldn't it be more robust to evaluate the metric based off of the prediction values off of the entire eval dataset? One example I can think of is for validation with a dataset that has sparse labels. In some batches, certain labels may not appear, breaking specific metric functions.

Thanks!

**Comment by yuzcccc** [comment]
I am also curious about how the training accuracy  of each displayed batch, e.g. 
Batch [50]. speed: 594.15 samples/sec Train-accuracy=0.646563
Does this number indicates the accuracy of batch 50 or the average accuracy of last 50 batches?

**Comment by RishabGargeya** [comment]
Would it be possible to modify the online evaluation process to store batch predictions on the eval data and calculate the evaluation metric at the very end? This would solve the issue of imbalanced evaluation sets and provide a more robust validation measure.
