### ISSUE TITLE
gamma and beta dimensionality error in GroupNorm operator

### ISSUE THREAD

**Issue by wintersurvival** [apache/incubator-mxnet#17139]
## Description
In the implement of mxnet.sym.GroupNorm，the size of gamma and beta is (group_number,)。However, in the paper of group norm the size of gamma and beta is (channel_number,) like the way of batchnorm.

### Steps to reproduce
1.
2.

## What have you tried to solve it?
1.
2.

## Environment
mxnet v1.6.0

# paste outputs here

**Comment by sxjscience** [comment]
Should be a bug @haojin2 .

**Comment by samskalicky** [comment]
@apeforest assign [@haojin2 ]
feel free to re-assign to the appropriate person

**Comment by mikeobr** [comment]
Group Norm is available in the latest 1.6 release, does this issue mean it shouldn't be used?

**Comment by yzhliu** [comment]
fixed by #18199
