### ISSUE TITLE
How to schedule part of dataflow(like large vocabulary embedding lookup)  to CPU  to save GPU memory

### ISSUE THREAD

**Issue by 0rchard** [apache/incubator-mxnet#1716]
My current lstm seq2seq model has a very large vocabulary (~500k Chinese vocabulary).
My context include one K10(4G \* 2) gpu device. When I try to increase embedding lookup hidden size, it exceeded gpu memory very easily.

In my seq2seq model, I set
vocab_size = 500k
emb_size = 128
rnn_hidden = 128
batch_size = 64

parameter_size = batch_size \* (embedding_lookup + rnn_computation + rnn_output)
                          = batch_size \* (vocab_size \* emb_size + emb_size \* 4 \* rnn_hidden + vocab_size \* rnn_hidden)
                          ~= 8G

The main memory consumption is due to my large vocabulary size, and in my case can not reduce.
Is there a way to separate the data flow to different device, such like embedding lookup on CPU, utilizing large computer memory, and lstm computation on GPU, to save GPU memory while accelerate the rnn computation?

I know Tensorflow is utilizing variable scope to assign partial dataflow to different devices. Does Mxnet have similar mechanism?

**Comment by piiswrong** [comment]
you can try the ctx group option in bind

**Comment by 0rchard** [comment]
@piiswrong Is there a way to use sym_gen, mx.model.FeedForward interface to implement ctx group binding?
Or is there a tutorial to illustrate how to bind different operation to different devices?
