### ISSUE TITLE
can't install mxnet-cu100

### ISSUE THREAD

**Issue by tranthanhtung04101995** [apache/incubator-mxnet#17167]
import mxnet 
illegal instruction (core dumped)
Processor: Inter Xeon (R) CPU X5570@ 2.93 GHZ
Graphics: GeForce GTX 960/PCle/SSE2
Cuda 10.0, cudnn 7.4.2, opencv 4.1.2.
Can You help me ?

**Comment by TaoLv** [comment]
@tranthanhtung04101995 
- Could you please install mxnet by `pip install mxnet` and check if the native version works on your machine?
- Could you please share the output of `lscpu` on your machine?

I'm afraid the binary releases need AVX2 supported on your machine. See https://github.com/apache/incubator-mxnet/pull/17047#issuecomment-564863078.

**Comment by tranthanhtung04101995** [comment]
mxnet version: 1.5.1.post0
lscpu:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               26
Model name:          Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz
Stepping:            5
CPU MHz:             1605.121
CPU max MHz:         2927,0000
CPU min MHz:         1596,0000
BogoMIPS:            5852.26
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-3
NUMA node1 CPU(s):   4-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d

**Comment by TaoLv** [comment]
Does the native mxnet (without the suffix -cu100) work well on your machine? It seems that AVX2 is not supported.

**Comment by tranthanhtung04101995** [comment]
also does not work. how to build mxnet on my machine

**Comment by TaoLv** [comment]
See if this works for you: https://mxnet.incubator.apache.org/get_started/ubuntu_setup.html or https://mxnet.incubator.apache.org/get_started/centos_setup.html

**Comment by szha** [comment]
I think this is a problem of not fixing the instruction set when building the binary, and then building on a new environment. cc @ddavydenko

**Comment by TaoLv** [comment]
@szha Previously I thought sse3 is the minimal requirement. I didn't see where -mavx2 is introduced. Is it from the static build of dependencies?

**Comment by tranthanhtung04101995** [comment]
i build mxnet. thank you.
https://github.com/apache/incubator-mxnet/issues/14953#issuecomment-492966154

**Comment by samskalicky** [comment]
@apeforest assign [@apeforest ] please follow up with @TaoLv

**Comment by apeforest** [comment]
> i build mxnet. thank you.
> [#14953 (comment)](https://github.com/apache/incubator-mxnet/issues/14953#issuecomment-492966154)

Can we close this issue now?

**Comment by szha** [comment]
@apeforest no the instruction set problem should still be there.
