### ISSUE TITLE
Need a better build script for CMake

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#17180]
## Description
The current instruction for users to build from source using Cmake is not very user-friendly. Users have to remember each flag whenever they build mxnet.

It will be nice to have a simple setup.py and users only need to run the following as Pytorch:
```
python setup.py install
```

**Comment by leezu** [comment]
We also need to handle other language bindings. But yes, the user experience can be improved.

**Comment by apeforest** [comment]
Closing the issue as the current cmake build step has been greatly simplified using a config.cmake file thanks to @leezu
