### ISSUE TITLE
Cannot access child blocks' parameter in parent block's hybrid_forward

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17220]
I have a very simple model:
```
class MyBlock(HybridBlock):
    def __init__(self):
        self.dense1 = nn.Dense(10)
        self.dense2 = nn.Dense(10)

    def hybrid_forward(self, F, x):
        # I want to concat the weights of `self.dense1` and `self.dense2`.
        # how do I do that? 
```

**Comment by leezu** [comment]
I suggest we deprecate `hybrid_forward`, in which parameters are passed as function arguments.
Instead users should access parameters via the `self.weight.data(ctx)` syntax used in `Block`.

Then you may access child-block parameters as `self.childblock.weight.data(ctx)`.

**Comment by eric-haibin-lin** [comment]
Shall we also consider the case where input is a symbol so the `ctx` is not visible to `forward`?

**Comment by leezu** [comment]
What's the use-case to input symbol into `forward`? It wouldn't work in most cases because `forward` doesn't have `F`.

**Comment by eric-haibin-lin** [comment]
nevermind, in gluon 2.0 the symbol and ndarray will be unified. As long as it still support hybridization, it's fine
