### ISSUE TITLE
How to build conda package on mxnet-cu101 (version 1.5.1)

### ISSUE THREAD

**Issue by tonyng1707** [apache/incubator-mxnet#17232]
I use 'conda skeleton pypi' to build Conda package on mxnet-cu101; however exception 'could not find unpacked source dir' occurs. It seems like PyPI only has the wheel file on the package, not the source. 

How can I get the source (tar file) on mxnet-cu101 (v1.5.1). Thank you.

**Comment by leezu** [comment]
https://github.com/apache/incubator-mxnet/releases/download/1.5.1/apache-mxnet-src-1.5.1-incubating.tar.gz

**Comment by tonyng1707** [comment]
@leezu I can build a MXNet Conda package based on the source you provided; however the package does not support GPU usage.  Please help

**Comment by szha** [comment]
@tonyng1707 you can use `tools/staticbuild/build.sh cu101` for building the mxnet-cu101 variant.
