### ISSUE TITLE
Incorrect installation instruction 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17244]
The instructions for installing mxnet master branch is incorrect. 
https://mxnet.apache.org/get_started?version=master&platform=linux&language=python&environ=pip&processor=cpu

![Screen Shot 2020-01-07 at 3 38 52 PM](https://user-images.githubusercontent.com/5545640/71938317-ddbe9700-3163-11ea-8b4a-12dacc700b1d.png)

It should only show the ones with `--pre` suffix 

@aaronmarkham

**Comment by leezu** [comment]
How did you arrive at the `master` version URL? It's not linked from the https://mxnet.apache.org/get_started page

**Comment by eric-haibin-lin** [comment]
There is a drop-down list for "MXNet version", and i selected "Master"

**Comment by leezu** [comment]
Thanks. I didn't realize that this dropdown list exists. There seems to be no UI element indicating the existence of the dropdown prior to hovering over the version number.

**Comment by aaronmarkham** [comment]
The content looks fine in here: https://github.com/apache/incubator-mxnet/blame/master/docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md

This is probably some javascript bug in here: https://github.com/apache/incubator-mxnet/blob/master/docs/static_site/src/assets/js/options.js
Never been a fan of these conditional selectors... seems like they're always breaking.

**Comment by eric-haibin-lin** [comment]
@aaronmarkham what's the alternative solution you're proposing?

**Comment by aaronmarkham** [comment]
> @aaronmarkham what's the alternative solution you're proposing?
Maybe mxnet-oncall can spend time looking at the js function that runs that feature.
I looked it over and nothing pops out as why it isn't working. Happy to work with someone on it that maybe knows more js and how to use the debugger to experiment with the div states.

**Comment by ys2843** [comment]
@aaronmarkham @eric-haibin-lin Above PR fixed this issue, preview link attached, please feel free to verify.
