### ISSUE TITLE
[website] [doc] tutorial rendering not working  

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17251]
https://mxnet.apache.org/api/python/docs/tutorials/performance/backend/profiler.html#The-incorrect-way-to-profile

Some links are rendered in a strange way. 

![Screen Shot 2020-01-08 at 1 26 54 PM](https://user-images.githubusercontent.com/5545640/72017448-8deed700-321a-11ea-8a78-79d503802026.png)

**Comment by ys2843** [comment]
Not reproducible in newest version website
