### ISSUE TITLE
MXNET Installation for R-Package are wrong

### ISSUE THREAD

**Issue by shawnbrar** [apache/incubator-mxnet#17337]
The official installation instructions of Mxnet for R on Ubuntu are wrong. Under the Install the MXNet Package for R heading it says that "source root directory to build the MXNet Perl package:". Why is that so?
![Screenshot_2020-01-16-08-08-26-830_com brave browser](https://user-images.githubusercontent.com/59639827/72488616-72498900-3837-11ea-9b80-c2a05e89e11c.jpg)

**Comment by leezu** [comment]
It's fixed by https://github.com/apache/incubator-mxnet/pull/17284 2 days ago.
You may need to clear your browser cache.
