### ISSUE TITLE
Tutorial does not render correctly 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17353]
The links are not rendered properly: 
https://mxnet.apache.org/api/python/docs/tutorials/packages/ndarray/sparse/train_gluon.html

![Screen Shot 2020-01-16 at 4 25 05 PM](https://user-images.githubusercontent.com/5545640/72574126-d2aee980-387c-11ea-8ddc-40d45a788f95.png)

**Comment by ys2843** [comment]
Can't reproduce any more. The link is good now.
