### ISSUE TITLE
libmxnet.so: File format not recognized

### ISSUE THREAD

**Issue by a550461053** [apache/incubator-mxnet#17378]
## Description
(A clear and concise description of what the bug is.)
After updating the version of mxnet to mxnet-cu100==1.6.0b20191102, I get error `AttributeError: module 'mxnet.ndarray' has no attribute 'my_gemm'`

### Error Message
When use example/extensions/lib_custom_op/test_gemm.py, got that: `AttributeError: module 'mxnet.ndarray' has no attribute 'my_gemm'`
And I check the libmxnet.so, found that: `objdump: /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so: File format not recognized`

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. cd example/extensions/lib_custom_op/
2. make
3. python test_gemm.py
4. get error: `AttributeError: module 'mxnet.ndarray' has no attribute 'my_gemm'`
5. objdump -T -t /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so
6. get error: `objdump: /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so File format not recognized`

## What have you tried to solve it?

1. I use [MobulaOP](https://github.com/wkcn/MobulaOP), it's ok. Can we explain what different between MobulaOP and MXNET.
2. Why the libmxnet.so is not recognized and when can we release the 1.6.0 (:

**Comment by TaoLv** [comment]
@samskalicky @wkcn Could you please take a look?

**Comment by szha** [comment]
@a550461053 the binary was compressed with upx and thus the format cannot be recognized.

Since then, we moved away from this approach and also stopped publishing nightly builds to pypi directly, and are publishing to our s3 bucket instead.

**Comment by wkcn** [comment]
Hi @a550461053 , the new approach was introduced in Dec. 6, 2019, so MXNet 1.6.0b20191102 is not supported.
It works for MXNet whose version>=1.6.0b20191207

**Comment by a550461053** [comment]
> @a550461053 the binary was compressed with upx and thus the format cannot be recognized.
> 
> Since then, we moved away from this approach and also stopped publishing nightly builds to pypi directly, and are publishing to our s3 bucket instead.

OK, so the release version of mxnet will not use compressing?

**Comment by a550461053** [comment]
> Hi @a550461053 , the new approach was introduced in Dec. 6, 2019, so MXNet 1.6.0b20191102 is not supported.
> It works for MXNet whose version>=1.6.0b20191207

Thank you, the pypi latest version which I can see by `pip install mxnet-cu100==1.6.0 `is 1.6.0b20191102.

**Comment by leezu** [comment]
You can find more recent nightly releases at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html

MXNet 1.6 final release will be pushed to pypi once the release is done in a few days.
Let's close this issue for now, but please reopen in case of further problems.

**Comment by a550461053** [comment]
> You can find more recent nightly releases at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html
> 
> MXNet 1.6 final release will be pushed to pypi once the release is done in a few days.
> Let's close this issue for now, but please reopen in case of further problems.

Ok, Thank you.
