### ISSUE TITLE
document of lib_custom_op support gpu without rebuilding mxnet

### ISSUE THREAD

**Issue by a550461053** [apache/incubator-mxnet#17382]
## Description
I want to create a lib_custom_op in c++ mxnet-backend without rebuilding the whole mxnet. In example/extensions/lib_custom_op/makefile, I didn't see the nvcc compiler and the source code sets the CPU device. Does it support GPU? 
- Can we update the document of custom op.

## References
- https://github.com/apache/incubator-mxnet/tree/master/example/extensions/lib_custom_op
- https://mxnet.apache.org/api/python/docs/api/mxnet/operator/index.html#mxnet.operator.CustomOp

**Comment by wkcn** [comment]
It doesn't support GPU yet. The PR https://github.com/apache/incubator-mxnet/pull/17270 is work in process.

**Comment by a550461053** [comment]
> It doesn't support GPU yet. The PR #17270 is work in process.

OK, thanks, I will pay attention to the PR #17270 . This issue focus on the document.

**Comment by rondogency** [comment]
Hi @a550461053, the lib_custom_op in c++ doesn't support GPU for now, and we are working on both c++ custom op doc #17241 and gpu support #17270 

The doc from python api you mentioned is merely for python custom op, and it is a different thing from lib_custom_op c++ custom op

**Comment by samskalicky** [comment]
@a550461053 The GPU support for customOps is finally ready thanks to all the hard work from @rondogency !!! Yay! You can get a nightly build or build from source with the latest master to try out the functionality. 

@rondogency is also working on the documentation updates for GPU support in #17486 too, so you can review the latest there an leave comments if there is something we can clarify.

**Comment by a550461053** [comment]
> @a550461053 The GPU support for customOps is finally ready thanks to all the hard work from @rondogency !!! Yay! You can get a nightly build or build from source with the latest master to try out the functionality.
> 
> @rondogency is also working on the documentation updates for GPU support in #17486 too, so you can review the latest there an leave comments if there is something we can clarify.

Ok, I will try it and this issue can be closed.
