### ISSUE TITLE
operator missing in AMP operator lists

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17409]
These operators do not appear in any of the AMP list: 
'_contrib_interleaved_matmul_encdec_qk', '_contrib_interleaved_matmul_encdec_valatt',
 '_contrib_interleaved_matmul_selfatt_qk', '_contrib_interleaved_matmul_selfatt_valatt'

It means that AMP may not cast inputs correctly in some cases, when these ops are used.

**Comment by eric-haibin-lin** [comment]
Fixed by https://github.com/apache/incubator-mxnet/pull/17408

**Comment by TaoLv** [comment]
We always need to put the operator into a AMP lsit when implementing a new operator? Do we have any mechanism to guarantee that?
