### ISSUE TITLE
Installed MxNet on Win7 computer, but when I use import mxnet I get an error

### ISSUE THREAD

**Issue by andychao227** [apache/incubator-mxnet#1740]
Here is the traceback:
Traceback (most recent call last):

  File "C:/Users/Andrew/PycharmProjects/NeuralNetwork/example.py", line 1, in <module>
    import mxnet as mx
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\Andrew\Anaconda3\lib\ctypes__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Andrew\Anaconda3\lib\ctypes__init__.py", line 351, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

libmxnet.dll and libmxnet.lib are in /mxnet/python/mxnet. I was also reading some problems others were having and added it to /pycharmprojects/neuralnetworks as well but had the same result.

Another person had said to edit configurations (Run->Edit Configuration... in PyCharm) of the project and add the location of the dll to the working directory, so I tried that but with no results.

Any help would be appreciated. Thanks!

**Comment by hjk41** [comment]
Make sure your dll file and your Python have the same bit-width. If you are
using the binary distribution, then you are using 64-bit dll, you should
use a 64-bit Python, too.

On Tue, Mar 29, 2016 at 2:37 AM, andychao227 <notifications@github.com>
wrote:

> Here is the traceback:
> Traceback (most recent call last):
>
> File "C:/Users/Andrew/PycharmProjects/NeuralNetwork/example.py", line 1,
> in
> import mxnet as mx
> File
> "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet__init__.py",
> line 7, in
> from .base import MXNetError
> File
> "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet\base.py",
> line 43, in
>
>
>
> *LIB = load_lib() File
> "C:\Users\Andrew\Anaconda3\lib\site-packages\mxnet-0.5.0-py3.4.egg\mxnet\base.py",
> line 35, in _load_lib lib = ctypes.cdll.LoadLibrary(lib_path[0]) File
> "C:\Users\Andrew\Anaconda3\lib\ctypes__init*.py", line 429, in LoadLibrary
> return self.
> *dlltype(name) File "C:\Users\Andrew\Anaconda3\lib\ctypes__init_*.py",
> line 351, in *init*
> self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found
>
> libmxnet.dll and libmxnet.lib are in /mxnet/python/mxnet. I was also
> reading some problems others were having and added it to
> /pycharmprojects/neuralnetworks as well but had the same result.
>
> Another person had said to edit configurations (Run->Edit Configuration...
> in PyCharm) of the project and add the location of the dll to the working
> directory, so I tried that but with no results.
>
> Any help would be appreciated. Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1740>
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by andychao227** [comment]
Thanks! I'm using Anaconda 3.x and it is the 64 bit version.

**Comment by andychao227** [comment]
Hi, wondering if anyone has any solutions to this issue. Thanks

**Comment by freddycct** [comment]
I have the same problem too...

**Comment by fengshikun** [comment]
I change my python version 32bit to 64bit and solved this problem

**Comment by pouya-cognitiv** [comment]
I am building my own version of mxnet as x64 Release and building libmxnet.dll to the \python\mxnet directory. But the same error occurs when I use the binaries: 20160419_win10_x64_cpu_only or 20160419_win10_x64_gpu.  I run the cmd file and then install python.

I am using Anaconda 3.5 x64.

Some code:
print("Issue:", lib_path[0])
>> ..\python\mxnet\libmxnet.dll
The error:
lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by freddycct** [comment]
You are probably missing some dlls in your PATH environment.
I solved the problem I had by using 
`C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\dumpbin.exe` 
to check which dependent dll is missing.

**Comment by andychao227** [comment]
Thanks I will look

Respectfully,
Andrew Weir

Please pardon the brevity, this message was sent from my iPhone.

**Comment by bahshetsian** [comment]
Ok guys the problem is that libmxnet.dll  dependent cudnn64_**5**.dll, i.e. you need to download not the last 6 version of the cudnn.

**Comment by kimtang** [comment]
I am able to resolve it by putting these dlls into the system PATH

libgcc_s_seh-1.dll
libgfortran-3.dll
libquadmath-0.dll

OpenBlas depends on it but it is not obvious.

Need to check the dependencies using dumpbin.exe

Kim

**Comment by tdomhan** [comment]
In case someone else finds this issue to use dumpbin:
1. Open the Visual Studio developer command prompt
2. run:
```
cd Miniconda3\Lib\site-packages\mxnet
dumpbin /dependents libmxnet.dll
```

I got the error because I didn't have the right version of cuda instal and because I hadn't installed cudnn yet.

**Comment by kiranvarghesev** [comment]
pip install numpy==1.15.0
Works
