### ISSUE TITLE
[Website][Doc] Gluon Custom Layers doc rendering issue

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#17417]
- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom-layer.html

<img width="1062" alt="Screen Shot 2020-01-23 at 11 12 25 AM" src="https://user-images.githubusercontent.com/6980212/73016050-0389a400-3dd2-11ea-9a40-4f7b50edf059.png">

- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom-layer.html#Layers-with-Parameters

<img width="643" alt="73016547-e4d7dd00-3dd2-11ea-869d-3045de3eeb41" src="https://user-images.githubusercontent.com/6980212/73019050-ac86cd80-3dd7-11ea-9796-1f5d2fde3743.png">

**Comment by ehsanmok** [comment]
@mxnet-label-bot add [Doc, Good First Issue]

**Comment by TEChopra1000** [comment]
These links have been fixed. This issue has been resolved and this ticket can be closed.

**Comment by TEChopra1000** [comment]
PR: https://github.com/apache/incubator-mxnet/pull/17435
