### ISSUE TITLE
[Website][Doc] Incorrect links in Gluon Custom Layer (Beginners)

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#17419]
Always use a released commit to link to a code line. Currently 

- [`forward(self, x)`](https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom_layer_beginners.html#The-simplest-custom-layer) points to [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/block.py#L415).

- [`hybridize`](https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom_layer_beginners.html#The-simplest-custom-layer) points to [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/block.py#L384).

- [`HybridBlock`](https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom_layer_beginners.html#Hybridization-and-the-difference-between-Block-and-HybridBlock) points to [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/block.py#L428).

- [`ParameterDict`](https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/custom_layer_beginners.html#Parameters-of-a-custom-layer) points to [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/parameter.py#L508).

**Comment by ehsanmok** [comment]
@mxnet-label-bot add [Doc, Good First Issue]

**Comment by szha** [comment]
I think those should point to the API doc instead. Also, the parameterdict is deprecated in 2.0. cc @leezu for the issues.
