### ISSUE TITLE
[Website][Doc] Gluon Layers and Blocks links rendering issues

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#17421]
- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/nn.html#Layers-and-Blocks

<img width="797" alt="Screen Shot 2020-01-23 at 11 48 24 AM" src="https://user-images.githubusercontent.com/6980212/73018447-87de2600-3dd6-11ea-8bca-9267344a1851.png">

- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/nn.html#A-Sequential-Block

<img width="778" alt="Screen Shot 2020-01-23 at 11 52 10 AM" src="https://user-images.githubusercontent.com/6980212/73018629-e3a8af00-3dd6-11ea-8f71-3db4402fa563.png">

- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/nn.html#Coding-with-Blocks

<img width="774" alt="Screen Shot 2020-01-23 at 11 55 06 AM" src="https://user-images.githubusercontent.com/6980212/73018861-4b5efa00-3dd7-11ea-9192-7fa077496e9c.png">

- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/nn.html#A-Custom-Block

<img width="758" alt="Screen Shot 2020-01-23 at 11 53 48 AM" src="https://user-images.githubusercontent.com/6980212/73018760-210d3c80-3dd7-11ea-9c56-0aeb2f22bb9d.png">

**Comment by ehsanmok** [comment]
@mxnet-label-bot add [Doc, Good First Issue]

**Comment by TEChopra1000** [comment]
These links have been fixed. This issue has been resolved and this ticket can be closed.

**Comment by TEChopra1000** [comment]
PR: https://github.com/apache/incubator-mxnet/pull/17435
