### ISSUE TITLE
[Website][Doc] Gluon Custom Loss Blocks link rendering issues

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#17422]
- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/loss/custom-loss.html#What-is-Contrastive-Loss

<img width="830" alt="Screen Shot 2020-01-23 at 12 03 15 PM" src="https://user-images.githubusercontent.com/6980212/73019460-7a29a000-3dd8-11ea-9f65-49d26784d284.png">

- https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/loss/custom-loss.html#Prepare-the-training-data

<img width="527" alt="Screen Shot 2020-01-23 at 12 06 41 PM" src="https://user-images.githubusercontent.com/6980212/73019745-0c31a880-3dd9-11ea-99e3-1bef675a2034.png">

**Comment by ehsanmok** [comment]
@mxnet-label-bot add [Doc, Good First Issue]

**Comment by TEChopra1000** [comment]
These issues were resolved and this ticket can be closed.

**Comment by TEChopra1000** [comment]
PR: https://github.com/apache/incubator-mxnet/pull/17435
