### ISSUE TITLE
Website: Separate master and stable versions of website

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#17497]
## Description
We may want a separate built pipeline and website version for each stable branch + master.

## References
For example, https://mxnet.apache.org/get_started/ubuntu_setup will only work for master version of MXNet. This is not a backwards compatibility issue: The previous instructions continue to work for MXNet master. The problem is that users have no way to access the old instructions.

**Comment by eric-haibin-lin** [comment]
We definitely need website versioning for mxnet 2.0

**Comment by aaronmarkham** [comment]
Should probably rename this issue. We don't want to version the website. We want versioned documentation.
