### ISSUE TITLE
[RFC] Partitioning for a given backend

### ISSUE THREAD

**Issue by mseth10** [apache/incubator-mxnet#17532]
## Description
Request for comments for the next PR on partitioning for a given backend
- Printing graph statistics after call to `optimize_for`
- Documentation: adding a markdown file with description and example(s)
- Updating [lib_subgraph](https://github.com/apache/incubator-mxnet/blob/master/example/extensions/lib_subgraph/test_subgraph.py) examples to add ones using gluon

## References
- Recent related PRs: #15969 #15886

**Comment by szha** [comment]
This feature has been merged and will be included as part of the mxnet 2.0. Thank you @mseth10
