### ISSUE TITLE
implement a c++ operator using other outside functions in 'so' file

### ISSUE THREAD

**Issue by a550461053** [apache/incubator-mxnet#17539]
When I write a c++ operator, I want to use functions of my 'so' file. I have add `-L /usr/lib -lmy_so_file -ldl` to g++, nvcc line of 'config.mk'. But when I build mxnet, got error `undefined reference to xxx_function`. The 'xxx_function' is added in xxx-inl.h. And the 'so' file test right independently.

**Comment by a550461053** [comment]
How can we insert a pre-define function to dmlc-core?

**Comment by rondogency** [comment]
@a550461053 are you using the c++ custom operator? if yes, you need to use the mx.library.load(*.so) api to have your .so file dynamically loaded.

**Comment by a550461053** [comment]
> @a550461053 are you using the c++ custom operator? if yes, you need to use the mx.library.load(*.so) api to have your .so file dynamically loaded.

No, I use the c++ operator in mxnet backend according to [](https://mxnet.apache.org/api/faq/add_op_in_backend). Because I have implement a operator and I need  to reuse mshadow op.

**Comment by stu1130** [comment]
[@mxnet-label-bot add custom]

**Comment by rondogency** [comment]
Hi @a550461053 are you able to resolve the problem based on the discussion in https://github.com/apache/incubator-mxnet/pull/17486#issuecomment-586640766

**Comment by a550461053** [comment]
> Hi @a550461053 are you able to resolve the problem based on the discussion in [#17486 (comment)](https://github.com/apache/incubator-mxnet/pull/17486#issuecomment-586640766)

I implement a mxnet backend operator and use 'dlopen' to load 'so' file in 'xxx-inl.h' first forward function. It's ok.
But I have another problem: I inherit the mxnet operator to implement my XXX op, it's ok. But I want to use 'NDArray' as the input of forward function instead of 'TBlob'  for using the dependencies. When I try the `NNVM_REGISTER_OP(_contrib_xxx).set_attr<FComputeEx>("FComputeEx<cpu>", XXX<cpu>);`, test the XXX operator in python, got `_contrib_XXX is not implemented for CPU.` Do you have any ideas?

**Comment by a550461053** [comment]
> > Hi @a550461053 are you able to resolve the problem based on the discussion in [#17486 (comment)](https://github.com/apache/incubator-mxnet/pull/17486#issuecomment-586640766)
> 
> I implement a mxnet backend operator and use 'dlopen' to load 'so' file in 'xxx-inl.h' first forward function. It's ok.
> But I have another problem: I inherit the mxnet operator to implement my XXX op, it's ok. But I want to use 'NDArray' as the input of forward function instead of 'TBlob' for using the dependencies. When I try the `NNVM_REGISTER_OP(_contrib_xxx).set_attr<FComputeEx>("FComputeEx<cpu>", XXX<cpu>);`, test the XXX operator in python, got `_contrib_XXX is not implemented for CPU.` Do you have any ideas?

This new problem has been found: `NNVM_REGISTER_OP` should assign `DispatchMode::kFComputeEx` when using `FComputeEx` .
