### ISSUE TITLE
CUDA: out of memory while runing fcn_xs.py 

### ISSUE THREAD

**Issue by zhubuntu** [apache/incubator-mxnet#1755]
I have changed the `cut_off_size` even to 10,but it always report CUDA: out of memory.
My GPU memory is 4G, so i think there must be something wrong.The dll library I used is the latested prebuild [windows binary ](https://github.com/dmlc/mxnet/releases)
And I cut the train.lst to just one image

```
1   JPEGImages/2010_000503.jpg  SegmentationClass/2010_000503.png
```

It can run but the accuracy is always nan.

```
INFO:root:Saved checkpoint to "model_pascal/FCN32s_VGG16-0001.params"
INFO:root:                     --->Epoch[0] Train-accuracy=nan
INFO:root: in eval process...
INFO:root:batch[0] Validation-accuracy=nan
```

By the way ,I found that even i change the  `cut_off_size`,the memrory  used is always same.

**Comment by zeakey** [comment]
Yes, exactly I have also experienced this problem.

**Comment by LaoAnchor** [comment]
One possible reason is that, the procedure you have runned still  occupied the GPU memory in terminal or python kernal. You can try to restart the terminal  or python kernal to release that.

Besides, you can run " nvidia-smi -l" in terminal to monitor the GPU use in real time to see whether the GPU memory is really working or not.

**Comment by zhubuntu** [comment]
@LaoAnchor I set the `cut_off_size` to 100 and restart the python,the memory GPU used raise from 300M to 3560M, then cuda report out of memory.
