### ISSUE TITLE
typo in CmakeLists.txt about OPENMP_FOUND

### ISSUE THREAD

**Issue by sl1pkn07** [apache/incubator-mxnet#17579]
https://github.com/apache/incubator-mxnet/blob/f0d1d9dd8879920c68290b6f520f97a17444354c/CMakeLists.txt#L420

according cmake documentation, `OPENMP_FOUND` should be `OpenMP_FOUND` 

https://cmake.org/cmake/help/git-master/module/FindOpenMP.html

greetings

**Comment by szha** [comment]
Thanks for bringing this up. Would you be open to contributing a patch to fix it?

**Comment by sl1pkn07** [comment]
@szha done

**Comment by leezu** [comment]
Variables are case sensitive in CMake syntax. This is only an optical issue.

**Comment by sl1pkn07** [comment]
not at all, a example

https://github.com/Nadrin/Quartz/issues/2

**Comment by leezu** [comment]
Ok. I'm not sure why this worked so far then.

**Comment by leezu** [comment]
`OPENMP_FOUND` is also supported variable.

https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindOpenMP.cmake#L584
