### ISSUE TITLE
CUDA: unspecified launch failure on CI Windows

### ISSUE THREAD

**Issue by szhengac** [apache/incubator-mxnet#17616]
## Description
CI on windows keeps giving `CUDA: unspecified launch failure`. It has been retriggered many times.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17400/20/pipeline/

**Comment by ptrendx** [comment]
@haojin2 The first failing test is `test_operator_gpu.test_np_nan_to_num`.

**Comment by haojin2** [comment]
Please first disable then investigate.

**Comment by haojin2** [comment]
#17630 still fails on windows-gpu with `test_np_nan_to_num` disabled, the error starts to occur on the test immediately after `test_np_nan_to_num`, meanwhile there were other PRs passing the windows-gpu build, as a result, I suspect the problem is not with the `test_np_nan_to_num` itself.

**Comment by ChaiBapchya** [comment]
Another one for unrelated PR #17487  - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17487/24/pipeline

**Comment by leezu** [comment]
This issue appears fixed by the toolchain updgrade https://github.com/apache/incubator-mxnet/pull/17962
