### ISSUE TITLE
Missing dnnl_config.h when installing horovod

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#17628]
## Description
I tried to compile MXNet using the cmake command:
```
cmake -GNinja -C ../config.cmake ..
cmake --build .
```
and then install horovod
```
HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL pip3 install -e . --no-cache-dir --user
```
The error message is
```
/home/ubuntu/mxnet/python/mxnet/../../include/mkldnn/dnnl.hpp:23:10: fatal error: dnnl_config.h: No such file or directory
```

I find that we have these lines in `mkldnn.mk`  https://github.com/apache/incubator-mxnet/blob/c2aff58c448bbe5755de0c8d35a1cc7d3fd9aa51/mkldnn.mk#L52-L53

The problem might be that we haven't copied the files to `mxnet/include/mkldnn` so the build system used in horovod is broken.

**Comment by sxjscience** [comment]
@leezu @apeforest Have you met problems when building horovod with the latest version?

**Comment by sxjscience** [comment]
A temporary fix is to manually copy files inside the `build` directory to `include/mkldnn`. I've confirmed that this solves the problem in horovod installation.
```
cp build/3rdparty/mkldnn/include/dnnl_config.h include/mkldnn
cp build/3rdparty/mkldnn/include/dnnl_version.h include/mkldnn
```

**Comment by TaoLv** [comment]
I will take a look at this. I remember previously the recommended build system of mxnet was makefile when cooperating with horovod.
@sxjscience is this the only issue when using cmake to build mxnet and linking it to horovod?

**Comment by sxjscience** [comment]
That’s currently the only one I found for linking to horovod. However I just ran setup.py in horovod and hasn’t run distributed training yet. I’m having some other issues in the cmake-built MXNet which I’m still investigating.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leezu** [comment]
@TaoLv what's your status on this issue?
I think this issue is currently blocking Makefile build removal so we should fix it soon.

**Comment by TaoLv** [comment]
@leezu I‘m working on a fix.
