### ISSUE TITLE
Parallel Unrolling of Stacked Recurrent Neural Networks

### ISSUE THREAD

**Issue by pranv** [apache/incubator-mxnet#1762]
Has anyone tried to construct Deep RNNs which unroll stacked RNNs in parallel?

That is, if there are 3 stacked RNNs (`RNN1`, `RNN2` & `RNN3`), and suppose the input has 5 timesteps (let's ignore batch size for now) most implementations I know of first run 5 recurrent steps fully on `RNN1` and then run 5 steps on `RNN2` and then 5 steps on `RNN3` one by one by one. What I'm proposing here is to run all three RNNs in parallel, but each RNN lags the RNN below it by a timestep. That is, when `RNN1` is in it's 3rd recurrent step, `RNN2` is in its 2nd and `RNN3` is in its 1st step and all 3 RNNs are executed in parallel and they go to the next time step together.

Obvious benefit is speed and device utilization (which is done mostly by increasing batch size elsewhere). Normal Deep RNNs should take `N * T` steps if there are `N` stacked RNNs and `T` timesteps. This proposed method should reduce it to `N + T` steps. This obviously can be extended to all forms of RNNs - LSTMs and GRUs.

I'll be trying to implement this soon. I'll be using **MXNET's ND ARRAY** backend mainly because this should be easy to do on top of your _lazy evaluation_ scheme. I'm not sure if the MXNET engine deduces that this optimization is possible from the dependency graph and implicitly use this method even for normally programmed Deep RNNs. Does it do this automatically? Has this idea been done/considered before? Any inputs regarding any aspect of this is welcome.

**Comment by tqchen** [comment]
Yes, both symbolic execution and ndarray benefit from the dep engine

**Comment by tqchen** [comment]
Spefically, both the unrolled RNN graph(symbolic executor) and imperative NDArray are lazily scheduled and will try to maximize the device utilization by scheduling things as soon as dependency is fulfilled, like what you talked about.

We have not yet have experiment on small batch setting yet. But your idea is indeed interesting and we would love to hear what are the results

**Comment by tqchen** [comment]
You might want to also change environment variable, on the parallelism level on each GPU on such setting, see http://mxnet.readthedocs.org/en/latest/env_var.html

MXNET_EXEC_NUM_TEMP  and MXNET_GPU_WORKER_NTHREADS  are relevant env vars

**Comment by pranv** [comment]
Thanks a lot for the tips. I'll try it out and share the results here
