### ISSUE TITLE
mxnet=1.6.0 for OSX on pypi does not work

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#17671]
## Description
It seems that mxnet 1.6.0 was published on pypi: https://pypi.org/project/mxnet/1.6.0/
However, when installing it through pip on a mac, I receive this error message:
```
> import mxnet as mx
 no suitable image found.  Did find:
	/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/libmxnet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/libmxnet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by leezu** [comment]
CC @szha

**Comment by leezu** [comment]
Seems the linux wheels are labeled wrongly and claim support for all platforms: https://pypi.org/project/mxnet/1.6.0/#files

@szha

**Comment by szha** [comment]
wheels for osx for py36 through py38 have been uploaded. the linux wheel is a long-standing problem as py2.py3 tag is only supported for universal wheels with any

**Comment by leezu** [comment]
How about py35?

**Comment by szha** [comment]
I made py35 available too

**Comment by fhieber** [comment]
Thanks, installing `mxnet` now works, but `mxnet-mkl` still shows the same problem.

**Comment by cosmincatalin** [comment]
Doesn't `mxnet` 1.6.0 make `mxnet-mkl` redundant?

**Comment by fhieber** [comment]
> Doesn't `mxnet` 1.6.0 make `mxnet-mkl` redundant?

Good question, it would be good to know if that is the case.

**Comment by leezu** [comment]
> Doesn't `mxnet` 1.6.0 make `mxnet-mkl` redundant?

`mxnet-mkl` for 1.6 refers to MKLDNN enabled build.
https://github.com/apache/incubator-mxnet/pull/16899 was recently merged to master branch and in the future `mxnet` build will come with MKLDNN enabled by default.

**Comment by ChaiBapchya** [comment]
@fhieber has the issue been resolved? 
@leezu since the pypi has been made available can we close it?

**Comment by fhieber** [comment]
Yes, this issue is resolved for me, thank you.

**Comment by ChaiBapchya** [comment]
@leezu plz close. Thanks!

**Comment by qcq** [comment]
so, you mean, currently we not support the python3.9 version?

**Comment by saravanan-natarajan** [comment]
> Thanks, installing `mxnet` now works, but `mxnet-mkl` still shows the same problem.
> 
> It might also be useful to update the package description to include a mention of the recently added Cuda 10.2 version and remove older versions.
> Current text:
> 
> ```
> This package supports Linux and Windows platforms. You may also want to check: - mxnet-cu101 with CUDA-10.1 support. - mxnet-cu100 with CUDA-10.0 support. - mxnet-cu100mkl with CUDA-10.0 support and MKLDNN support. - mxnet-cu92 with CUDA-9.2 support. - mxnet-cu92mkl with CUDA-9.2 support and MKLDNN support. - mxnet-cu91 with CUDA-9.1 support. - mxnet-cu91mkl with CUDA-9.1 support and MKLDNN support. - mxnet-cu90 with CUDA-9.0 support. - mxnet-cu90mkl with CUDA-9.0 support and MKLDNN support. - mxnet-cu80 with CUDA-8.0 support. - mxnet-cu80mkl with CUDA-8.0 support and MKLDNN support. - mxnet-cu75 with CUDA-7.5 support. - mxnet-cu75mkl with CUDA-7.5 support and MKLDNN support. - mxnet-mkl with MKLDNN support. - mxnet.
> ```

I am using MacOs but still I too get the same error. Can you please let me know how did you solved this issues. Will be great help indeed.

**Comment by joelteply** [comment]
If you have an m1 mac and still have a problem (not a mach-o library), I have some basic instructions on how I got this working using some of the 2.0 cmake work.
https://github.com/apache/incubator-mxnet/issues/20992
