### ISSUE TITLE
Cuda 10.2 Ubuntu 18  mxnet installation error 

### ISSUE THREAD

**Issue by i55code** [apache/incubator-mxnet#17678]
Hi, I have followed this post (https://github.com/apache/incubator-mxnet/issues/17058) to install the nightly convenience builds using: 
pip install --pre mxnet -f https://dist.mxnet.io/python/cu102mkl

However, when I test the following code: 
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())

The error message is : 
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())
[20:56:28] src/imperative/./imperative_utils.h:92: GPU support is disabled. Compile MXNet with USE_CUDA=1 to enable GPU support.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [20:56:28] src/imperative/imperative.cc:81: Operator _ones is not implemented for GPU.
Stack trace:
  [bt] (0) /home/.local/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x307d3b) [0x7f1a6fb0fd3b]
  [bt] (1) /home/.local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x6bb) [0x7f1a72cb1c5b]

Aborted (core dumped)

Please let me know how to install mxnet properly for Cuda 10.2 in ubuntu 18.04. Thanks!

**Comment by leezu** [comment]
The instruction is wrong. You need to ` pip install --pre mxnet_cu102 -f https://dist.mxnet.io/python/cu102mkl`

**Comment by i55code** [comment]
Thank you so much! It works!

**Comment by Qualiazero** [comment]
Hello are you using linux install this package?
