### ISSUE TITLE
mxnet inference wrong

### ISSUE THREAD

**Issue by northeastsquare** [apache/incubator-mxnet#17695]
## Description
I train mask classification, validation acc:98%, but inference with train and val image, many case is wrong, maybe 50% is wrong
the codes in:https://github.com/northeastsquare/mxnet_mask_classification
## Occurrences
in training:
![Screenshot from 2020-02-26 22-56-56](https://user-images.githubusercontent.com/3086078/75356965-98108600-58eb-11ea-94e5-95334ed85caf.png)
but inference:
![image](https://user-images.githubusercontent.com/3086078/75357058-bb3b3580-58eb-11ea-9523-58bf3f79ab9d.png)
because all the image's class is 1, so the result is not right
## What have you tried to solve it?

1. Use this to save checkpoint: export_block('mobilenetv2-0.5-new', net,preprocess=True, ctx=mx.gpu(0)), and inference no need  to subtract mean, divide std.
2. Use inference.py to inference the result, but are wrong
3. Inference same image multiple time, result is the same

**Comment by apeforest** [comment]
@Jerryzcn have you seen this issue before?

**Comment by northeastsquare** [comment]
OK, get it, my fault. Because I resize image 256x256.But when train,resize 128x128
