### ISSUE TITLE
[RFC] New Branches for MXNet 1.x, 1.7.x, and 2.x

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#17701]
Hi,

I created the following branches in the MXNet repo: 1.x, 1.7.x. I propose that these branches will function as the following:
- 1.7.x: release branch for 1.7.x versions. 1.7.0 roadmap is specified at https://github.com/apache/incubator-mxnet/issues/16864
- 1.x: development branch for MXNet's future 1.x versions (e.g. 1.8.x, 1.9.x, ...)
- master: development branch for 2.x. 2.0 roadmap is specified at https://github.com/apache/incubator-mxnet/issues/16167

**Comment by szha** [comment]
cc @apache/mxnet-committers

**Comment by TaoLv** [comment]
Nice. It's an essential step towards MXNet 2.0. Curious to know that do we still encourage contributors to create PR against the master branch? And in what strategy we need pick a commit to branch 1.x? Or they need create two PRs against two branches simultaneously?

**Comment by szha** [comment]
Contributors are encouraged to create PR against master branch. Since master branch is the development branch for 2.0, backward incompatible changes will be allowed, while 1.x branch only allows backward compatible changes.

**Comment by szha** [comment]
Pinging @apache/mxnet-committers again in case there's any more concern. Otherwise I will assume lazy consensus by the end of Wednesday of this week.

**Comment by aaronmarkham** [comment]
Docs are currently generated from master. What's the proposal for what should be the default version of the docs on the website?
Do we need to escalate the production of docs variations for different versions - like at a minimum, master(2.0) and 1.x?

**Comment by szha** [comment]
Let's switch the doc generation for the website to 1.x for now. 2.0 doc should be generated when version selection of the website is available.

**Comment by leezu** [comment]
Even for 1.x, the current instructions are not compatible with stable 1.6 release. We should build the website based on 1.6 release branch until a version selection is available.

**Comment by szha** [comment]
Website versioning is tracked in https://github.com/apache/incubator-mxnet/issues/17497

**Comment by aaronmarkham** [comment]
@leezu @szha - We need a clear direction on what to do for the current site's docs generation. It isn't really website versioning. It's generating documentation from different branches. The core website jekyll should stay the same and be generated from master. However, the default docs for each API can be generated from a specific version/branch.

**Comment by leezu** [comment]
It's not only about the API documentation. Installation instructions or tutorials will change over time. Building the website independently for different versions may be the simplest approach. I'm also fine with any other approach that enables users to look up documentation and instructions for their respective version.

**Comment by szha** [comment]
Let's continue the discussion on website in #17497
