### ISSUE TITLE
mkldnn quantized FC is slow

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17705]
quantized BERT model with int8 is 2x slower than float32. 

Download trained SST params from: https://dist-bert.s3.amazonaws.com/demo/finetune/sst.params 

Clone is install gluon-nlp v0.9
```
# calibration
KMP_AFFINITY=granularity=fine,noduplicates,compact,1,0 OMP_NUM_THREADS=1 numactl --physcpubind=0 --membind=0 python3 finetune_classifier.py --task_name SST --only_calibration --model_parameters  sst.params
# fp32 inference
python3 finetune_classifier.py --task_name SST --epoch 1 --only_inference --model_parameters sst.params --round_to 128 --dev_batch_size 1
# int8 inference
python3 finetune_classifier.py --task_name SST --epoch 1 --only_inference --model_prefix ./output_dir/model_bert_SST_quantized_customize --deploy --round_to 128 --dev_batch_size 1
```

I'm using c5.12xlarge. I tried to set OMP_NUM_THREAD=8, but int8 is still slower than float32.

**Comment by pengzhao-intel** [comment]
@wuxun-zhang @ciyongch

**Comment by ciyongch** [comment]
Thanks for reporting this, I will take a look.

**Comment by ciyongch** [comment]
@eric-haibin-lin I just created a PR https://github.com/apache/incubator-mxnet/pull/17707 to address this issue, please take a review.

**Comment by pengzhao-intel** [comment]
Feel free to reopen if the issue is not resolved.
