### ISSUE TITLE
1.6.0 Windows pip installation fails

### ISSUE THREAD

**Issue by smpawlowski** [apache/incubator-mxnet#17719]
Pip install of mxnet 1.6.0 fails on windows due to libmxnet.dll missing. Windows whl doesn't seem to be available. Installation tries to use mxnet-1.6.0-py2.py3-none-any.whl, which seems to contain libmxnet.so, but not dll.
Same issue when using
pip install mxnet-cu101==1.6.0 -f https://dist.mxnet.io/python/all

Any chance you could publish windows build?

steps to reproduce:
pip install mxnet-cu101==1.6.0 -> success
in Python: import mxnet -> libmxnet.dll not found

**Comment by relaxli00** [comment]
+1

**Comment by ehosler** [comment]
Issue here as well.

**Comment by leezu** [comment]
CC @szha

**Comment by szha** [comment]
The wheel should have been a manylinux1 wheel. I will look into correcting the problem.
@yajiedesign to update on the windows wheels

**Comment by dorijanf** [comment]
Same issue, dll file missing. If I may ask, when can we expect a fix?

**Comment by szha** [comment]
The windows version of mxnet has been released and it should not occur anymore. Going forward we will release automatically from CD (potentially with manylinux2010 tag for linux)

**Comment by smpawlowski** [comment]
Thanks for looking into it. pip install mxnet==1.6.0 works great. But I have trouble installing any version with cuda support like mxnet-cu101 / mxnet-cu101mkl. In [pypi mxnet-cu101mkl](https://pypi.org/project/mxnet-cu101mkl/#files) I can only find manylinux wheel. 

Is it possible to also release 1.6.0 with cuda / Windows?

**Comment by relaxli00** [comment]
Yes, please release the 1.6.0 cuda support versions also, e.g. mxnet-1.6.0cu101mkl. Thanks. 

@szha

**Comment by szha** [comment]
Hi @smpawlowski @relaxli00. @yajiedesign is still working on the windows wheels for GPU. It takes particularly long for the windows compilation and hence the delay.

In the meantime, we will look into how to improve the development experience and smoothness for releases in the next few weeks.

**Comment by relaxli00** [comment]
Thanks @szha . I found the DLL released in the wheels can be used for C++ programming also after opwrapper. Not sure if it will work all the time. Compiling the whole system from source code on Windows is painful for individual users.

**Comment by leezu** [comment]
@relaxli00 there are no ABI guarantees for C++. Please do not rely on it.

**Comment by relaxli00** [comment]
@leezu, thanks for the information. Will keep eyes open on it.

I adopted MXNet mainly because of its C++ support at the beginning. In many cases, Python is not a good solution for production deployment.

But, everything is changing quickly. From time to time, I met inconsistent results between Python and C++ implementations. I'm struggling to balance the usage of both.

**Comment by szha** [comment]
@relaxli00 thanks for sharing your experiences. For continued support of c++ in mxnet 2.0, it would be great to continue the discussion on c++ support in https://github.com/apache/incubator-mxnet/issues/16167.

**Comment by smpawlowski** [comment]
Now
pip install mxnet-cu101==1.6.0 -f https://dist.mxnet.io/python/all
works. Thanks a lot for sorting it out!

**Comment by yjh2533130373** [comment]
Cannot find the MXNet library.
List of candidates:
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\libmxnet.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\../../lib/libmxnet.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\../../build/libmxnet.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\../../build\libmxnet.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\../../build\Release\libmxnet.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\mxnet\../../windows\Release\libmxnet.dll
怎么我的还是有这个问题

**Comment by relaxli00** [comment]
Not sure if it's because of your python version of 3.8. Python 3.8 need implicitly claim the path for the dll dependents search. For example, if you're using cuda, you'll need claim the path of its dlls in your program using os.add_dll_directory(). It's a popular topic of Python 3.8 dll loading.
