### ISSUE TITLE
MXNet nightly cpu build (w/o MKLDNN) does not work with Horovod

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#17715]
## Description
Installing Horovod with MXNet nightly CPU (w/o MKLDNN) failed. GPU build and CPU mkldnn build are both okay.

## Error Message:

OSError: /usr/local/lib/python3.6/dist-packages/horovod/mxnet/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5mxnet10CopyFromToERKNS_7NDArrayEPS1_i

@TaoLv Is it also related to the change you made recently that fixed MKLDNN build?

@szha @leezu FYI

**Comment by TaoLv** [comment]
Hmm if you're using the latest nightly build, I'm afraid MKL-DNN is already enabled in it. Could please share the output of mx.runtime.Features()?

**Comment by apeforest** [comment]
Tested with the latest nightly build and the issue was gone.
