### ISSUE TITLE
MXNet website often down with "Error 503 Backend unavailable, connection timeout"

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#17724]
```
Error 503 Backend unavailable, connection timeout

Backend unavailable, connection timeout
Guru Mediation:

Details: cache-pao17420-PAO 1582943298 879971478

Varnish cache server
```

Happened for the second time (at least) this week. Who operates the webserver?

**Comment by ys2843** [comment]
Apache Infra team operates the server. If it still happens frequently, this is where we can report the problem. On our side, there is very little we can do about it.
> https://issues.apache.org/jira/projects/INFRA/issues/INFRA-20453?filter=allopenissues.
