### ISSUE TITLE
 "Segmentation fault: 11" after "Running: OpWrapperGenerator.py"

### ISSUE THREAD

**Issue by HolyTerra** [apache/incubator-mxnet#17733]
## Description
I tried to build MXNet(tag 1.6.0) from source,but failed each time after Running: OpWrapperGenerator.py.

### Error Message
[ 93%] Built target mxnet
Running: OpWrapperGenerator.py

Segmentation fault: 11

make[2]: *** [cpp-package/CMakeFiles/cpp_package_op_h.dir/build.make:59: cpp-package/CMakeFiles/cpp_package_op_h] Error 255
make[1]: *** [CMakeFiles/Makefile2:2229: cpp-package/CMakeFiles/cpp_package_op_h.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Built target image-classification-predict
[ 93%] Built target im2rec
make: *** [Makefile:141: all] Error 2

## Environment
Ubuntu 19.10, CUDA 10.2, OpenCV 4.2
gcc/g++ version is 7.4.0,build with c++14.
I chose USE_CPP_PACKAGE, set BLAS to MKL and CPU runtime to TBB.

## What have you tried to solve it?

1.I switched BLAS from openblas to MKL because of issue #11543, but it doesn't work.

**Comment by leezu** [comment]
After switching to MKL, you may run into https://github.com/apache/incubator-mxnet/issues/17641

Can you try deleting `3rdparty/openmp` to see if the segfault is due to conflict between llvm openmp and intel openmp?

**Comment by HolyTerra** [comment]
> After switching to MKL, you may run into #17641
> 
> Can you try deleting `3rdparty/openmp` to see if the segfault is due to conflict between llvm openmp and intel openmp?

You're right.Build finished after `3rdparty/openmp` removed,.Thank you for your support!
