### ISSUE TITLE
1.6.0 installation error using pip on windows platform

### ISSUE THREAD

**Issue by fierceX** [apache/incubator-mxnet#17730]
## Description
After installing using pip on the windows platform, the import reports an error. I found that the installation did not look like a package for the windwos platform.
```bash
RuntimeError: Cannot find the MXNet library.
List of candidates:
c:\users\fierc\miniconda3\lib\site-packages\mxnet\libmxnet.dll
c:\users\fierc\miniconda3\lib\site-packages\mxnet\../../lib/libmxnet.dll
c:\users\fierc\miniconda3\lib\site-packages\mxnet\../../build/libmxnet.dll
c:\users\fierc\miniconda3\lib\site-packages\mxnet\../../build\libmxnet.dll
c:\users\fierc\miniconda3\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
c:\users\fierc\miniconda3\lib\site-packages\mxnet\../../windows/x64\Release\libmxnet.dll
```
![image](https://user-images.githubusercontent.com/13912058/75611387-06a44c80-5b55-11ea-9503-2a75c3713fd8.png)

![image](https://user-images.githubusercontent.com/13912058/75611346-b4fbc200-5b54-11ea-9dd1-e983a6df032f.png)

**Comment by dorijanf** [comment]
If I'm not mistaken this is the same issue https://github.com/apache/incubator-mxnet/issues/17719
Apparently it's being fixed.

**Comment by szha** [comment]
The windows version of mxnet has been released and it should not occur anymore. Going forward we will release automatically from CD (potentially with manylinux2010 tag for linux)
