### ISSUE TITLE
[CI] How to restart a single stage on MXNet CI?

### ISSUE THREAD

**Issue by wkcn** [apache/incubator-mxnet#17750]
Hi, there.

Sometimes, due to strage reason, the CI test fails, but it may be not relevant to the PR.

There are many PRs failing only a check because of strage reason. As we know, it will cost a lot of money and take a long time to restart all stages : (

It will be economic and convenient if it is available to restart a single stage on MXNet CI.

**Comment by leezu** [comment]
@ChaiBapchya is working to provide this feature for the github bot

**Comment by wkcn** [comment]
The problem has been solved : )
