### ISSUE TITLE
mxnet illegal instruction

### ISSUE THREAD

**Issue by shahriyar888** [apache/incubator-mxnet#17790]
Hey guys I am working on a project which uses mxnet. I don't know enough about mxnet.
The problem is I cant even import mxnet because I have this error :Illegal instruction (core dumped)
I have tryed different operation systems such as ubuntu , manjaro and now I am using archlinux.
I have tryed different version of cuda and mxnet such as cuda 10.2, 10.1, 9.0 and mxnet-cu102 ,mxnet-cu101,mxnet-cu90.
this is my bashrc exports:

    export  PATH=/opt/cuda-9.0/bin:$PATH
    export  LD_LIBRARY_PATH=:/opt/cuda-9.0/lib64:$LD_LIBRARY_PATH
this is my python3.6 exits:

    Python 3.6.10 (default, Mar  1 2020, 10:16:25) 
    [GCC 9.2.1 20200130] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import mxnet
    Illegal instruction (core dumped)

and this is my system information :

    H/W path           Device  Class       Description
    ==================================================
                               system      System Product Name (To Be Filled By O.E.M.)
    /0                         bus         M4A89GTD-PRO/USB3
    /0/0                       memory      64KiB BIOS
    /0/4                       processor   AMD Phenom(tm) II X6 1090T Processor
    /0/4/5                     memory      640KiB L1 cache
    /0/4/6                     memory      2560KiB L2 cache
    /0/4/7                     memory      6MiB L3 cache
    /0/36                      memory      12GiB System Memory
    /0/36/0                    memory      [empty]
    /0/36/1                    memory      4GiB DIMM Synchronous 667 MHz (1.5 ns)
    /0/36/2                    memory      4GiB DIMM Synchronous 667 MHz (1.5 ns)
    /0/36/3                    memory      4GiB DIMM Synchronous 667 MHz (1.5 ns)
    /0/100                     bridge      RS880 Host Bridge
    /0/100/3                   bridge      RS780 PCI to PCI bridge (ext gfx port 1)
    /0/100/3/0                 display     GP106 [GeForce GTX 1060 6GB]
    /0/100/3/0.1               multimedia  GP106 High Definition Audio Controller
    /0/100/9                   bridge      RS780/RS880 PCI to PCI bridge (PCIE port 4)
    /0/100/9/0                 bus         uPD720200 USB 3.0 Host Controller
    /0/100/9/0/0       usb1    bus         xHCI Host Controller
    /0/100/9/0/1       usb2    bus         xHCI Host Controller
    /0/100/9/0/1/2             bus         USB3.1 Hub
    /0/100/a                   bridge      RS780/RS880 PCI to PCI bridge (PCIE port 5)
    /0/100/a/0                 storage     JMB361 AHCI/IDE
    /0/100/a/0.1               storage     JMB361 AHCI/IDE
    /0/100/11                  storage     SB7x0/SB8x0/SB9x0 SATA Controller [IDE mode]
    /0/100/12                  bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
    /0/100/12/1        usb6    bus         OHCI PCI host controller
    /0/100/12/1/1              generic     Xbox 360 Wireless Receiver for Windows
    /0/100/12/1/5              input       USB Receiver
    /0/100/12.2                bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
    /0/100/12.2/1      usb3    bus         EHCI Host Controller
    /0/100/12.2/1/2            bus         USB2.0 Hub
    /0/100/12.2/1/2/2          input       Twin USB Joystick
    /0/100/13                  bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
    /0/100/13/1        usb7    bus         OHCI PCI host controller
    /0/100/13/1/1              input       G9 Laser Mouse
    /0/100/13.2                bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
    /0/100/13.2/1      usb4    bus         EHCI Host Controller
    /0/100/13.2/1/4            storage     Mass Storage Device
    /0/100/14                  bus         SBx00 SMBus Controller
    /0/100/14.1                storage     SB7x0/SB8x0/SB9x0 IDE Controller
    /0/100/14.2                multimedia  SBx00 Azalia (Intel HDA)
    /0/100/14.3                bridge      SB7x0/SB8x0/SB9x0 LPC host controller
    /0/100/14.4                bridge      SBx00 PCI to PCI Bridge
    /0/100/14.4/7              bus         VT6306/7/8 [Fire II(M)] IEEE 1394 OHCI Controller
    /0/100/14.5                bus         SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
    /0/100/14.5/1      usb8    bus         OHCI PCI host controller
    /0/100/15                  bridge      SB700/SB800/SB900 PCI to PCI bridge (PCIE port 0)
    /0/100/15/0        enp5s0  network     RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
    /0/100/16                  bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
    /0/100/16/1        usb9    bus         OHCI PCI host controller
    /0/100/16.2                bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
    /0/100/16.2/1      usb5    bus         EHCI Host Controller
    /0/100/16.2/1/3            storage     Mass Storage Device
    /0/101                     bridge      Family 10h Processor HyperTransport Configuration
    /0/102                     bridge      Family 10h Processor Address Map
    /0/103                     bridge      Family 10h Processor DRAM Controller
    /0/104                     bridge      Family 10h Processor Miscellaneous Control
    /0/105                     bridge      Family 10h Processor Link Control
    /1                 scsi10  storage     
    /2                 scsi11  storage  
cuda info :

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2017 NVIDIA Corporation
    Built on Fri_Sep__1_21:08:03_CDT_2017
    Cuda compilation tools, release 9.0, V9.0.176

I really need help:(
Thanks guys 

Update :

I have tryed install mxnet even without gpu support and the error is same.

**Comment by TaoLv** [comment]
Are you using mxnet pip package or building mxnet from source code? May be similar issue: https://github.com/apache/incubator-mxnet/issues/17613.

**Comment by leezu** [comment]
Switching the CD setup to make use `-mno-avx` flag during compilation should fix this issue (if it's about the pip packages).

It's done by default for the cmake staticbuild (https://github.com/apache/incubator-mxnet/pull/17448), but the change hasn't been backported to the Makefile build used for the 1.6 release pip packages.

@shahriyar888 we will fix this for the nightly builds via https://github.com/apache/incubator-mxnet/pull/17646

For the 1.6 release build: you can build it yourself from source. https://mxnet.apache.org/get_started/ubuntu_setup

**Comment by leezu** [comment]
Should be fixed in latest nightly builds, as https://github.com/apache/incubator-mxnet/pull/18205 enabled the cmake setup for nightly builds
