### ISSUE TITLE
Change instance type in CI to use G4 instance

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#17804]
This still require experimentation on time v/s cost v/s completeness. One of the proposal is to use AWS G4 instances instead of current P2/P3 instances for GPU tests.

**Comment by sandeep-krishnamurthy** [comment]
@ChaiBapchya @josephevans

**Comment by ChaiBapchya** [comment]
This has been completed. Unix-gpu builds use G4 since May 11
https://github.com/apache/incubator-mxnet/pull/18186
