### ISSUE TITLE
Add a bot to manually trigger CI builds for PR

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#17801]
This helps in giving more control to PR authors and reviewers when to run the builds. Avoids un-necessary CI runs for work in progress commits / when PR is still not ready for review / merge.

**Comment by sandeep-krishnamurthy** [comment]
@ChaiBapchya

**Comment by ChaiBapchya** [comment]
@mxnet-bot is deployed!!

**Comment by ChaiBapchya** [comment]
Ofcourse!

**Comment by marcoabreu** [comment]
@mxnet-blt run ci all

**Comment by marcoabreu** [comment]
@mxnet-bot run ci [all]

**Comment by ChaiBapchya** [comment]
Lol doesn't work with issues! Will filter for those :p

**Comment by ChaiBapchya** [comment]
Let's try this now 
@mxnet-bot run ci [all]

**Comment by ChaiBapchya** [comment]
@sandeep-krishnamurthy @szha Can we close this issue since this has been completed? Thanks!
