### ISSUE TITLE
Staggered Jenkins CI pipeline

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#17802]
We need to stagger the CI build pipeline to run sanity tests, unix-cpu tests sequentially. Only when these tests pass, trigger all other target builds in parallel. This will avoid un-necessary runs on PR where even sanity and basic cpu tests are failing.

**Comment by sandeep-krishnamurthy** [comment]
@ChaiBapchya @josephevans

**Comment by josephevans** [comment]
Activated the staggered build pipelines on 4/27.

**Comment by sandeep-krishnamurthy** [comment]
Thanks @josephevans :-)
