### ISSUE TITLE
Why is nvcc not installed along with cuda in mxnet docker builds?

### ISSUE THREAD

**Issue by rbavery** [apache/incubator-mxnet#17819]
I'm trying to reproduce this repository: https://github.com/msracver/FCIS, which depends on an older version of mxnet, 1.4.1. I've using https://hub.docker.com/layers/mxnet/python/1.4.1_gpu_cu80_py2/images/sha256-d069471816ee1184bfffb644b173c17cf0d9a80f54448a669ee8defa6beeea38?context=explore

But when I try to compile FCIS's custom operators I get an error that nvcc is not found in my PATH, because it is not installed in the usual location at /usr/local/cuda/bin (there is no bin folder in the cuda directory). 

Here is my Dockerfile. The build completes but the step `sh init.sh` fails because there is no nvcc to compile the custom operators

```
FROM mxnet/python:1.4.1_gpu_cu80_py2 as mxnet

RUN apt-get update

RUN apt-get install -y --fix-missing git build-essential

RUN pip install Cython \
    && pip install opencv-python==3.2.0.6 \
    && pip install easydict==1.6 \
    && pip install hickle \
    && cd /home \
    && git clone https://github.com/msracver/FCIS.git \
    && apt-get install -y libopenblas-dev

RUN cd /home/FCIS \
    && sh ./init.sh

RUN pip install pillow matplotlib pyaml jupyterlab scipy scikit-image \
    && mkdir /home/code \
    && mkdir /home/data
```

**Comment by leezu** [comment]
Did you verify the problem exists for the latest (1.6 or master) docker images?

**Comment by rbavery** [comment]
I need to use older docker versions to reproduce the FCIS repo, but I fixed the issue by going back to version .12 where nvcc is included in the builds.

**Comment by leezu** [comment]
I understand it's needed for FCIS. If you believe nvcc should be distributed in mxnet containers, it would be good to verify if this is still a problem so that it can be fixed for new versions of mxnet.
