### ISSUE TITLE
[Question] Distributed training performance for one worker and one server on the same node

### ISSUE THREAD

**Issue by hkvision** [apache/incubator-mxnet#17822]
Hi,

I’m referring to this page https://mxnet.apache.org/api/faq/distributed_training.html for distributed training (using mxnet-mkl and running on multiple cpu nodes).
Want to ask is there any performance benchmarks to run distributed training with one worker and one server on a node? Or is there any best practices to run distributed training to well utilize the resources while get good performance?
As I run, the performance is affected if I put one worker and one server on a single node, each occupying half of the cores.
Thanks a lot in advance!

**Comment by eric-haibin-lin** [comment]
You probably want to check out https://medium.com/apache-mxnet/intel-mlsl-makes-distributed-training-with-mxnet-faster-7186ad245e81

**Comment by hkvision** [comment]
> You probably want to check out https://medium.com/apache-mxnet/intel-mlsl-makes-distributed-training-with-mxnet-faster-7186ad245e81

Hi Eric @eric-haibin-lin 

Thanks for your reply. This post is about using mlsl with horovod for distributed training. It will be a good approach to try later. But currently I'm just using the traditional ps-lite approach with dist kvstore. Want to ask is there any related performance stats or practice for this?

**Comment by hkvision** [comment]
Seems the performance issue is related to my wrong setting of OMP environment variables. Thanks so much. Close this issue now.
