### ISSUE TITLE
An incorrect result generated by exec.backward

### ISSUE THREAD

**Issue by zleyk22** [apache/incubator-mxnet#17864]
## Description
I run the python program below and I get a wrong result (`nan`)

## To Reproduce
This is a python program I run:
```
import mxnet as mx
sym = mx.symbol.prod(data=mx.symbol.Variable("in"), axis=(1))
exec = sym.bind(mx.cpu(0), {"in":mx.nd.array([[4, 0]])}, {"in":mx.nd.array([[9, 9]])})

out = exec.forward()[0]
print('-- Output:')
print(exec.outputs)
exec.backward(mx.nd.ones(out.shape))
print('-- Gradient:')
print(exec.grad_dict['in'])
```
I get this output:
```
-- Output:
[
[0.]
<NDArray 1 @cpu(0)>]
-- Gradient:

[[ 0. nan]]
<NDArray 1x2 @cpu(0)>
```
But I expected to get this result instead of `[[0. nan]]`:
```
[[0. 4.]]
```
I cannot explain why I get `nan`. It would be helpful if somebody can help me with this.

## Environment

I use MXNet 1.6.0
and run python 3.7.7 (with ipython 7.13.0)

**Comment by leezu** [comment]
cc @eric-haibin-lin

**Comment by zleyk22** [comment]
I investigated the MXNet C++ code and noticed that the gradient of the input array [[x, y]] is computed as [[(x*y)/x, (x*y)/y]]. Therefore, if y is zero, then we always get nan as the second element of the array. Is it a bug, or is it done on purpose? If the latter is true, how can I avoid it?

**Comment by zleyk22** [comment]
Moved to #18078 ([Numpy] Gradient of np.prod is wrong when there are zeros in the array)
