### ISSUE TITLE
installing mxnet on centos 6.6

### ISSUE THREAD

**Issue by narayaba** [apache/incubator-mxnet#1788]
I am getting lot of errors while installing mxnet in centos 6.6. Are there any pre-built versions for centos 6.6. Thanks

**Comment by piiswrong** [comment]
Possibly relevant posts: https://github.com/dmlc/mxnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+centos+
we should consider fix this once for all @tqchen @antinucleon

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
