### ISSUE TITLE
[Bug][Numpy] Wrong gradient of np.where

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#17893]
## Description
Example 1: Using np.where(array, array, scalar)

```python
import mxnet as mx
mx.npx.set_np()

a = mx.np.array([1, 0, 1])
b = mx.np.array([2, 3, 4])

b.attach_grad()

with mx.autograd.record():
    c = mx.np.where(a, b, -1)
    c.backward()
print(b.grad)
```
Output: [0. 1. 0.]

Example 2: Using np.where(array, array, array)
```python

import mxnet as mx
mx.npx.set_np()

a = mx.np.array([1, 0, 1])
b = mx.np.array([2, 3, 4])

b.attach_grad()

with mx.autograd.record():
    c = mx.np.where(a, b, mx.np.array([-1, -1, -1]))
    c.backward()
print(b.grad)
```
Output: [1. 0. 1.]

The second one is correct.

**Comment by sxjscience** [comment]
@hgt312 I think that there might be some issue in the backward + scalar case of where: https://github.com/apache/incubator-mxnet/blob/9a355ebc1dfc5c087d41bb24c946e7f773e01af9/src/operator/numpy/np_where_op.cc#L236-L254

**Comment by hgt312** [comment]
Fixed in https://github.com/apache/incubator-mxnet/pull/17899
