### ISSUE TITLE
AWS: ami-12fd8178 is missing?

### ISSUE THREAD

**Issue by satoshi-harashima** [apache/incubator-mxnet#1790]
To launch an instance in N. Virginia region, I searched "ami-12fd8178" in Community AMIs,
but I couldn't find the ami. When I searched "mxnet", I found following three AMIs.

MXNet.jl_GPU_IJulia_No_S3 - ami-29e6b043
GPU enabled MXNet.jl (Julia 0.4.2) +IJulia
Root device type: ebs Virtualization type: hvm

DeepestLearning - ami-b0162fda
Cuda 7.5 with cuDNN r4 (4.0.7) w/ TensorFlow, MXNet, Theano
Root device type: ebs Virtualization type: hvm

MXNet.jl_GPU - ami-eda8fc87
GPU enabled MXNet.jl 0.0.4 on Julia 4.2
Root device type: ebs Virtualization type: hvm

Am I missing something to find the ami-12fd8178?
(I might just use one of the above AMIs. The second one probably suits my purpose, which is to use python.)

**Comment by xiandong79** [comment]
Yes. The ami-12fd8178 is lost.

Now, the AMI Ids for the Deep Learning Amazon Linux AMI are the following:
us-east-1 : ami-e7c96af1
us-west-2: ami-dfb13ebf
eu-west-1: ami-6e5d6808 

Product highlights:
New in Version 2.0 - CPU Instance Type Support, MXNet built with MKL support.
6 Deep Learning Frameworks - contains the most popular Deep Learning Frameworks (MXNet, Caffe, Tensorflow, Theano, Torch and CNTK) all prebuilt and pre-installed.
Pre-installed components to speed productivity include Nvidia drivers, CUDA, cuDNN, Anaconda, Python2 and Python3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
