### ISSUE TITLE
Jenkins build failures on v1.6

### ISSUE THREAD

**Issue by connorgoggins** [apache/incubator-mxnet#17910]
## Description
Currently, Jenkins builds are failing for v1.6 - both the branch `v1.6.x` and the tagged release `1.6.0.rc0`. The errors can be traced to dependency-related issues with the build processes for Julia, Python, and R docs.

### Error Message
For shell script output and errors for each docs build, see [here](http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/docs%2Fconnor-website-build-master/detail/connor-website-build-master/18/pipeline). For general Jenkins build failure, see [here](http://jenkins.mxnet-ci-dev.amazon-ml.com/job/docs/job/connor-website-build-master/18/).

## To Reproduce
Copy [my pipeline](http://jenkins.mxnet-ci-dev.amazon-ml.com/job/docs/job/connor-website-build-master/) on the [dev Jenkins instance](http://jenkins.mxnet-ci-dev.amazon-ml.com/) and run it on either the branch `v1.6.x` or on the tag `1.6.0.rc0`.

**Comment by connorgoggins** [comment]
Update: fixes for Julia and Python have been identified, still running into the R docs build issue: https://github.com/apache/incubator-mxnet/issues/17920

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [Doc]

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [Website]

**Comment by connorgoggins** [comment]
Update: the issue with Julia & R has been root caused and identified as a Python version problem with the Jenkins pipeline (using 2.7 instead of 3). Since this will take a significant amount of time and we want to make the v1.6 website available to our users as soon as possible, we will move forward with generating the v1.6 artifact without Julia & R docs as a stopgap solution and make a note of this issue for future work.

**Comment by leezu** [comment]
Could you provide more details on the Python version problem? The pipeline used to work well and there has been no change to the Python version support in the 1.6 release.

**Comment by aaronmarkham** [comment]
> Could you provide more details on the Python version problem? The pipeline used to work well and there has been no change to the Python version support in the 1.6 release.

Sort of a time travel issue. 1.6 used to be fine when it was master and when the Python dependencies had not yet sunsetting Python 2. But they have now, so we must use Python 3. And bring that back from the future and apply it to v1.6.x if we want to build those docs.

**Comment by szha** [comment]
> > Could you provide more details on the Python version problem? The pipeline used to work well and there has been no change to the Python version support in the 1.6 release.
> 
> Sort of a time travel issue. 1.6 used to be fine when it was master and when the Python dependencies had not yet sunsetting Python 2. But they have now, so we must use Python 3. And bring that back from the future and apply it to v1.6.x if we want to build those docs.

This sounds more like a problem of dependencies not being frozen. We should be able to deduce what versions were working from a past successful run.

**Comment by aaronmarkham** [comment]
> > > Could you provide more details on the Python version problem? The pipeline used to work well and there has been no change to the Python version support in the 1.6 release.
> > 
> > 
> > Sort of a time travel issue. 1.6 used to be fine when it was master and when the Python dependencies had not yet sunsetting Python 2. But they have now, so we must use Python 3. And bring that back from the future and apply it to v1.6.x if we want to build those docs.
> 
> This sounds more like a problem of dependencies not being frozen. We should be able to deduce what versions were working from a past successful run.

It's Markdown 2.1 - this is the dep that is now Python 3 only. In some previous fixes I went through and pinned dependencies. And this is what I tried to apply. Thus the error on Python 2.
This is captured [here in my PR that I closed](https://github.com/apache/incubator-mxnet/pull/17919#issuecomment-605301300) because it won't work without a [significant amount of back-porting](https://github.com/apache/incubator-mxnet/pull/17919#issuecomment-606044838).
