### ISSUE TITLE
Ways of Freezing part of parameter and not the whole layer.

### ISSUE THREAD

**Issue by djaym7** [apache/incubator-mxnet#17939]
Using grad_req == null freezes whole layer, i want to freeze certain weights in the current parameter, how to do this ? 
Eg: Freezing 1 of 5 kernels in conv parameter during training..

Thanks
 
@zhreshold help ?

#question and not #featureRequest

**Comment by leezu** [comment]
You can't freeze part of a parameter. However, you can overwrite the gradient arrays, once computed, accordingly and set those parts to 0 that you like "freezed".

**Comment by zhreshold** [comment]
Unless you separate the e.g. conv layer to multiple one and concat you can't freeze partial weights.

**Comment by djaym7** [comment]
Okay, thanks

**Comment by djaym7** [comment]
![image](https://user-images.githubusercontent.com/12378820/78163995-f4d8f200-73fd-11ea-9e74-f7049539c591.png)
Instead of freezing, i can use a custom layer and slice them back in the weights in forward and backward passes, wouldn't it serve the same purpose ?

**Comment by leezu** [comment]
It may not have the same performance
