### ISSUE TITLE
I meet a problem when I used mnist dataset to predict a single number image, greatful.

### ISSUE THREAD

**Issue by ruobo** [apache/incubator-mxnet#1796]
I am a new student of mxnet and deeplearning, when I save the train_mnist.py training result, I take one 28*28 handwrite image to make a predict. I transfer the JPG image to REC, named number.rec, and I write the code like this, but there are some errors. Who can help me? With my best wishes.

[16:25:47] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: myTest/number.rec, use 3 threads for decoding..
[16:25:47] src/io/./iter_normalize.h:103: Load mean image from myTest/vali.bin
[16:25:47] /home/kang/mxnet/dmlc-core/include/dmlc/logging.h:245: [16:25:47] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "myPredict.py", line 25, in <module>
    pred = model.predict(test_dataiter)
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/model.py", line 594, in predict
    self._init_predictor(data_shapes)
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/model.py", line 526, in _init_predictor
    pred_exec.copy_params_from(self.arg_params, self.aux_params)
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/executor.py", line 228, in copy_params_from
    array.astype(dst.dtype).copyto(dst)
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 424, in copyto
    return NDArray._copyto(self, out=other)
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 765, in unary_ndarray_function
    c_array(ctypes.c_char_p, [])))
  File "/home/kang/mxnet/example/image-classification/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:25:47] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

**# MY code here.**

import find_mxnet
import mxnet as mx
import logging
import argparse
import os, sys
import train_model
import numpy as np

prefix = 'model/mnist-0'
iteration = 9

model = mx.model.FeedForward.load(prefix, iteration)

test_dataiter = mx.io.ImageRecordIter(
    path_imgrec = 'myTest/' + "number.rec",
    mean_img    = 'myTest/' + "vali.bin",
    rand_crop   = False,
    rand_mirror = False,
    data_shape  = (1,28,28),
    batch_size  = 1,
    )

pred = model.predict(test_dataiter)
print pred

**Comment by piiswrong** [comment]
It depends on the network you loaded. Most likely it takes 1 dim input while you are feeding 2 dim.
You can try NDArrayIter. It's easier to work with.

**Comment by clcarwin** [comment]
Example for NDArrayIter.
You may need to modify the parameter of np.reshape to fit your network.

```
data = cv2.imread(imagepath)    # check if the size of image is 28x28
data = data.transpose((2,0,1))
data = data[0:1,:,:]
print data.shape    # (1, 28, 28)

data = np.reshape(data,(1,1,28,28))    # for lenet (batchsize, ch, height, width)
#data = np.reshape(data,(1,784))    # for mlp

dataiter = mx.io.NDArrayIter(data)
r = model.predict(dataiter)
print r
```

**Comment by ruobo** [comment]
Thanks for your help @piiswrong @clcarwin ,I will try to understand. @clcarwin where is cv2 defined? Thank you.

**Comment by ruobo** [comment]
@clcarwin I found cv2 model and import, but it's said that data didn't have transpose() method. What can I do? thanks.

**Comment by ruobo** [comment]
Nobody here today? I m very interesting about the mxnet. I think here maybe a mistake when I use make_list.py, it has labled my number image, however I want see the image prediced result. So anybody who can tell me how to get the result like: " this image is 5" or "this image is 6 95%". And I m still not understand about the data_shape, what means of Dimensions? I have read some documents but not found. Who can give me some help, I m very grateful.

**Comment by ruobo** [comment]
yes it worked, but the predict result is ridiculous， I write some numbers image but the result like:
python oneNumberTestPredict.py 
(1, 28, 28)
[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]

I think label  '1' means number '2', but it's may be number '5' or '1' or '7', I have tried 10 numbers but no one is correct, why?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
