### ISSUE TITLE
Cuda 10.2 mxnet installation error mxnet-cu102mkl

### ISSUE THREAD

**Issue by Qualiazero** [apache/incubator-mxnet#17963]
Hi, I have followed this post #17678 , I want to install the mxnet-cu102mkl package by `pip install mxnet-cu102mkl==1.6.0` on the windows,
but it didn't work with `ERROR: Could not find a version that satisfies the requirement 
mxnet-cu102mkl==1.6.0 (from versions: none)
ERROR: No matching distribution found for mxnet-cu102mkl==1.6.0`
I changed other package resourse but it always can't work, does this package only have nightly build version now? How should I do?

**Comment by szha** [comment]
We do have that for linux. https://pypi.org/project/mxnet-cu102mkl/#files

What operating system are you using?

**Comment by Qualiazero** [comment]
> 
> 
> We do have that for linux. https://pypi.org/project/mxnet-cu102mkl/#files
> 
> What operating system are you using?

I am using python compiler of anaconda on the windows10, will you have a windows version soon?

**Comment by szha** [comment]
The windows version was too large in size so we only have it available in our own repo https://dist.mxnet.io/python. You can install with
`pip install mxnet-cu102mkl==1.6.0 -f https://dist.mxnet.io/python`

**Comment by szha** [comment]
Let's keep this issue open until the installation doc is updated.

**Comment by Qualiazero** [comment]
> The windows version was too large in size so we only have it available in our own repo https://dist.mxnet.io/python. You can install with
> `pip install mxnet-cu102mkl==1.6.0 -f https://dist.mxnet.io/python`

Did the option -f equal to --find ？ I can't find this option in the user guide documentation of pip..

**Comment by ianhellstrom** [comment]
> We do have that for linux. https://pypi.org/project/mxnet-cu102mkl/#files
> 
> What operating system are you using?

@szha What does the `post0` suffix signify?

**Comment by szha** [comment]
> > We do have that for linux. https://pypi.org/project/mxnet-cu102mkl/#files
> 
> > 
> 
> > What operating system are you using?
> 
> 
> 
> @szha What does the `post0` suffix signify?

It's just that after the release the pip package document needs to be patched and hence a new version. Since pypi versions are immutable, such patch happens on a post-release version, hence the suffix.

**Comment by ianhellstrom** [comment]
> It's just that after the release the pip package document needs to be patched and hence a new version. Since pypi versions are immutable, such patch happens on a post-release version, hence the suffix.

Is there a reason a patch does not get its own patch version?

**Comment by szha** [comment]
@ianhellstrom there's no code change other than a readme update. I think this is a proper use of the post-release version numbers according to [PEP440](https://www.python.org/dev/peps/pep-0440/#post-releases)

**Comment by xiaosiyu0603** [comment]
Thanks a lot, it works well. Could you please update the command on "https://mxnet.apache.org/versions/1.6/get_started?platform=windows&language=python&processor=gpu&environ=pip&" either? People may get frustrated when they run the command from offical website.
