### ISSUE TITLE
No recent nightly builds for ubuntu-latest

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#17976]
## Description
It seems that no recent nightly builds for mxnet-1.7 are published for linux.

The latest nightly build found by the install command `pip install --pre "mxnet<2" -f https://dist.mxnet.io/python` is `1.7.0b20200315` (March 15th).

For macos recent nightly builds seem to exist.

For reference this is the Github action file and a corresponding log:
https://github.com/awslabs/sockeye/blob/master/.github/workflows/mxnet_nightly.yml#L41
https://github.com/awslabs/sockeye/runs/561191699?check_suite_focus=true#step:5:6

**Comment by leezu** [comment]
May be due to https://github.com/apache/incubator-mxnet/issues/17903

**Comment by leezu** [comment]
Works again

```
% pip install --pre --upgrade --user "mxnet<2" -f https://dist.mxnet.io/python                                                ~/src/mxnet-master fixcd +
Looking in links: https://dist.mxnet.io/python
Collecting mxnet<2
  Downloading https://repo.mxnet.io/dist/python/cpu/mxnet-1.7.0b20200415-py2.py3-none-manylinux1_x86_64.whl (48.4 MB)
     |████████▌                       | 12.8 MB 3.5 MB/s eta 0:00:11^C
```
