### ISSUE TITLE
[nvidia-docker][1.6] apt-get update failing with gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#18005]
## Description
Ubuntu 14.04
1.6 branch
Static build Python

### Error Message
```
W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed
```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-17993/5/pipeline

## To Reproduce
```
git checkout v1.6.x
ci/build.py --docker-registry mxnetci --nvidiadocker --platform publish.ubuntu1404_gpu --docker-build-retries 3 --shm-size 500m /work/runtime_functions.sh build_static_python_cu101mkl
```

## What have you tried to solve it?

1. Tried it locally. Able to reproduce. Hence ruling out possibility of Jenkins error.
This is a security / certificate issue [likely]. Since apt-get is unable to fetch the package.

While : https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages is a 404.

https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 is a valid URL. It has several files [Packages.gz being one of them.

## Comments
Surprisingly, this doesn't happen on master branch or on the previous commits to v1.6 branch

**Comment by ChaiBapchya** [comment]
Discovered in all 5 builds of PR https://github.com/apache/incubator-mxnet/pull/17993

**Comment by leezu** [comment]
Ubuntu 14.04 is no longer supported. Nvidia may now require a newer ssl toolchain than provided by ubuntu 14.04.

The issue doesn't occur on master because it's hidden by the Docker cache
