### ISSUE TITLE
Amalgamation Android arm64

### ISSUE THREAD

**Issue by cenggokhan** [apache/incubator-mxnet#18006]
I compiled amalgamation for android arm64 in my macbook pro and get jni_libmxnet_predict.so for Android arm64, however when I use this file in my app, an exception like;
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN5mxnet18CachedOpThreadSafeC1ERKN4nnvm6SymbolERKNSt6__ndk16vectorINS5_4pairINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESD_EENSB_ISE_EEEE" referenced by "/data/app/com.example.tr-ip3Uhkl5FWXePuSYo9ENVA==/lib/arm64/libmxnet_predict.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at org.dmlc.mxnet.Predictor.<clinit>(Predictor.java:8)

arises. Can you help me, what am I doing wrong?

**Comment by cenggokhan** [comment]
ndk 21 and gcc compile problem.

**Comment by cenggokhan** [comment]
ndk 21 and gcc compile problem.

**Comment by cenggokhan** [comment]
ndk 21 and gcc compile problem.

**Comment by leezu** [comment]
@cenggokhan I'm fixing the compile issues for NDK 19+ as part of https://github.com/apache/incubator-mxnet/pull/17984 

We'll likely merge it soon, but may need to wait for a resolution of https://gitlab.kitware.com/cmake/cmake/-/issues/20572 to properly test on Jetson devices.

**Comment by leezu** [comment]
In general, I suggest you don't use amalgamation if not needed. For Android, you don't need amalgamation.
