### ISSUE TITLE
[Flaky Test] test_operator_gpu.test_ftrl

### ISSUE THREAD

**Issue by zixuanweeei** [apache/incubator-mxnet#18003]
## Description
`test_ftrl()` is located in https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_optimizer.py#L671

## Occurrences
+ http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18001/2/pipeline/429
+ http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18001/2/pipeline/418
+ http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-17779/17/pipeline
+ http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-17531/28/pipeline

**Comment by zixuanweeei** [comment]
@mxnet-label-bot add [gpu, optimizer]

**Comment by ptrendx** [comment]
Also seen in #17995.

**Comment by ptrendx** [comment]
Hmm, something is wrong with the random seed generation of tests - all those failing `test_ftrl` got the same seed: 
```
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=386103813 to reproduce.
```

FYI @roywei Since you are already looking at random-related stuff and @DickJC123 since you wrote the `@with_seed` facility.

**Comment by leezu** [comment]
@szha plans to switch the testing suite to pytest
This involves refactoring the randomness logic and may fix the issue. The new code would likely be inspired by the code in GluonNLP, where we transitioned to pytest already in the initial release and thus refactored the random-related stuff for pytest.

https://github.com/dmlc/gluon-nlp/blob/v0.9.x/conftest.py#L41

**Comment by szha** [comment]
Occurred again in http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-18146/runs/2/nodes/365/steps/784/log/?start=0

**Comment by leezu** [comment]
With the new random infrastructure, the test failure can be reproduced deterministically:

`MXNET_TEST_SEED=1632189249 pytest tests/python/unittest/test_optimizer.py  -k test_ftrl`
