### ISSUE TITLE
Model load problem in 64 bit devices

### ISSUE THREAD

**Issue by cenggokhan** [apache/incubator-mxnet#18030]
I compiled amalgamation for armeabi-v7a and arm64-v8a, I am trying to test model https://github.com/flyingzhao/mxnet_VanillaCNN/blob/master/vanilla-0001.params and https://github.com/flyingzhao/mxnet_VanillaCNN/blob/master/vanilla-symbol.json
devices with arch armeabi-v7a loads model without any problem. But arm64-v8a devices can not load model. Exception:
org.dmlc.mxnet.MxnetException: [21:53:21] jni/../mxnet_predict-all.cc:18084: Check failed: from.shape() == to->shape() operands shape mismatch
When I try same model with python this exception occurs as arm64 device. Exception:
Shape inconsistent, Provided = [100,576], inferred shape=(100,256)
My python code:

import mxnet as mx
from mxnet import model
import numpy as np
import cv2

img=cv2.imread("test.jpg")
img=cv2.resize(img,(40,40))
m=model.FeedForward.load('vanilla',1,num_batch_size=1)
b=np.zeros((1,3,40,40),dtype=np.float32)      #change chanels into shape[1,3,40,40]
b[0,0,:,:]=img[:,:,2]
b[0,1,:,:]=img[:,:,1]
b[0,2,:,:]=img[:,:,0]

points=m.predict(b)
print(points)

Please help.

**Comment by leezu** [comment]
Can you try to come up with a minimal reproducible example? That will make it easier to help you
