### ISSUE TITLE
QuantizedElemwiseMulOpShape accesses out of bound elements

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18034]
## Description
MKLDNN `QuantizedElemwiseMulOpShape` accesses out of bound elements in line 64 during `quantized_elemwise_mul` test.

https://github.com/apache/incubator-mxnet/blob/ab4f7f6a7335e88034edcf61402aec170cdca5fd/src/operator/quantization/quantized_elemwise_mul.cc#L63-L65

Preventing that invalid access by adding `out_attrs->size() > quantized_elemwise_mul::kOutMin` to the if condition, leads to errors in `infer_shape_pass`.

CI with updated toolchain (ie #17984) catches the bug. See https://github.com/apache/incubator-mxnet/issues/17987 for instructions to reproduce: use recent gcc and build in debug build

CC: @xinyu-intel

**Comment by pengzhao-intel** [comment]
Thanks to reporting the issue. We will fix soon.

**Comment by pengzhao-intel** [comment]
cc @bgawrych

**Comment by leezu** [comment]
Ping @bgawrych @pengzhao-intel 

Let's try to fix this and reenable the tests. Thanks for your help

**Comment by leezu** [comment]
Thanks @bgawrych
