### ISSUE TITLE
Improve log_softmax performance by OneDNN library

### ISSUE THREAD

**Issue by pengzhao-intel** [apache/incubator-mxnet#18065]
The original request:
https://github.com/apache/incubator-mxnet/pull/18001#issuecomment-613666611

The related code:
https://oneapi-src.github.io/oneDNN/dev_guide_logsoftmax.html
https://github.com/apache/incubator-mxnet/blob/681cfc4205a568d3bfc35da1a601489abdd44074/src/operator/nn/log_softmax.cc

**Comment by bgawrych** [comment]
@pengzhao-intel Can we close this issue? Link to PR https://github.com/apache/incubator-mxnet/pull/18320

**Comment by pengzhao-intel** [comment]
closing since PR is merged.
