### ISSUE TITLE
FFT layer in MXNet

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#1813]
Dear MXNet Developers:

I'm planning to add an FFT transform operator in MXNet similar to that described in https://papers.nips.cc/paper/5649-spectral-representations-for-convolutional-neural-networks for some related experiments. After reading the code, I think I may need to first extend the complex engine of MShadow (like https://github.com/dmlc/mshadow/blob/master/mshadow/expr_engine-inl.h#L409-L421) to support cuFFT and FFTW and define an additional operator in MXNet. Could you provide me some guidance or related codes on this extension? 

Thanks vey much!

**Comment by tqchen** [comment]
It is not necessary to implement this as a template. For example, softmax implement this as a function. The expression is only needed when you want to do something like pipeline up expressions. Alternatively, you can simply implement the functions just in mxnet by calling cuFFT and FFTW separately by reference the implementation of CuDNN operators


https://github.com/dmlc/mshadow/blob/master/mshadow/tensor.h#L649

**Comment by sxjscience** [comment]
@tqchen Thanks for your suggestion! I have one more question. Since 2D FFT of real matrix will return complex numbers stored with cuComplex, it will be more natural for the output of the FFT layer to have complex data-types (Also the input of IFFT layer). I'm not sure if it's simple to add complex types in MXNet.

**Comment by tqchen** [comment]
How do CUDA solve complex type normally, is it a specific type? or two arrays of floats?

@piiswrong helped to add type support to mxnet, it should not be hard to add a user defined type to mshadow

**Comment by sxjscience** [comment]
I find it's a structure of two floats `typedef float2 cuFloatComplex;`. Currently I'm trying to directly implement this layer in the MXNet side similar to CuDNN.

**Comment by morningpig917** [comment]
Hi @sxjscience , have you implemented fft in MXNet? Found your complex number extension in mshadow, but it seems that MXNet does not support fft yet...

**Comment by sxjscience** [comment]
@morningpig917 Yes, I'may PR it later after I finish the current work...

**Comment by morningpig917** [comment]
That's great! I'm trying to implement Compact Bilinear Pooling with MXNet. I think without your code, I will have to add cuFFT into mshadow, but I am not so familiar with mshadow.. Could you please give me some brief instructions, for example, which files should I modify or create?

**Comment by sxjscience** [comment]
@morningpig917 I've written the RFFT2D and IRFFT2D operators, which could be directly used as mx.sym.RFFT2D and mx.sym.IRFFT2D

**Comment by morningpig917** [comment]
@sxjscience Thanks! but I cannot access them at the moment, right? Really hope you can give a few instructions on how to add the FFT operator...

**Comment by morningpig917** [comment]
@sxjscience How did you convert the real number tensors of MXNet into cufftComplex in the opeaters?

**Comment by sxjscience** [comment]
@morningpig917 These days I'm too busy with a deadline. `cufftComplex` is stored as a structure of two floats so we can store the Tensor as [real_1, imag_1, real_2, imag_2,...] and directly cast it to cufftComplex.

**Comment by morningpig917** [comment]
@sxjscience Many thanks. I'll try it.

**Comment by morningpig917** [comment]
@sxjscience and... How did you solve complex number multiplication?

**Comment by sxjscience** [comment]
@morningpig917 Here I've added several complex operators https://github.com/sxjscience/mxnet/blob/master/src/operator/elementwise_binary_op-inl.h#L389-L435 .(I feel that it's not a very good solution and is not suitable for a PR)

**Comment by morningpig917** [comment]
@sxjscience Just implemented FFT and IFFT operator based on your code with cufft. Anyone who's in a hurry could check out my fork https://github.com/morningpig917/mxnet.

**Comment by sxjscience** [comment]
@morningpig917 Looks good!

**Comment by morningpig917** [comment]
@sxjscience How to do it?

**Comment by sxjscience** [comment]
You can first check the gradient using functions in `test_utils.py` and write some test cases. Later you can submit a pull request containing the implementation of this OP. (Also it would be better if you can provide an example showing how to use this OP, e.g, the example of Compact Bilinear Pooling). You can do it if you have time.

**Comment by morningpig917** [comment]
@sxjscience Fine, I'll PR it later. The compact bilinear pooling also requires another algorithm, count sketch, which could be implemented as sparse matrix multiplication. However, sparse matrix seems not supported by MXNet. So I am also writing the CUDA version of count sketch (without sparse matrices). I will test the code together with FFT/IFFT.

**Comment by sun9700** [comment]
@morningpig917 Dose Compact Bilinear Pooling progress well? Any release?

**Comment by morningpig917** [comment]
@sun9700 You can check my fork. I have implemented FFT, IFFT and count-sketch operators. But the count sketch seems not efficient enough, so I have not PR it.

**Comment by shiyangdaisy** [comment]
@morningpig917 Do you have any tests codes for the count sketch and fft operators?

**Comment by yajiedesign** [comment]
look like is added.closed. If has some problem, reopen it.

**Comment by KeyKy** [comment]
@zhuchen03 Could you give me an example to show how to use your compact bilinear pool in image classification?

**Comment by hubenjm** [comment]
Hi,

I am trying to compute the 2D FFT of gray-scale images (shape = (nx, ny)) inside of an iterator that applies data augmentation transformations on the fly. I've seen in the documentation that the 1D FFT works on the GPU and I've verified it myself. But it's not clear how to get the 2D FFT out of this in a nice way, without either converting the mx.ndarray back to numpy or having to write a custom mshadow operator in C++, which I'm not at all experienced at. So just wondering if anyone has implemented the 2D FFT already for use with mx.ndarray objects?
