### ISSUE TITLE
[Numpy] different behaviours between numpy and mxnet.numpy

### ISSUE THREAD

**Issue by acphile** [apache/incubator-mxnet#18137]
### different dtype when calculating division
For example:
in mxnet.numpy
&nbsp;&nbsp; for two ndarray a,b with dtype='int64', the dtype of result c = a  / b is 'float32'
in numpy
&nbsp;&nbsp; the dtype is 'float64'
Generally, when calculating division, mxnet.numpy often uses float32 while numpy uses float64.
Using float32 will often lead to the loss of floating point precision.
```
b=mx.np.array(1, dtype='int32')
e=b/3
e.item()
>>> 0.3333333432674408
```

### operator between different types
for example
```
import mxnet as mx
mx.npx.set_np()
mx.np.arange(5)
array([0., 1., 2., 3., 4.])
b=mx.np.arange(5)
a=b.astype('int32')
a==b
```
it will raise Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/incubator-mxnet/python/mxnet/numpy/multiarray.py", line 991, in __eq__
    return equal(self, other)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/numpy/multiarray.py", line 8451, in equal
    return _mx_nd_np.equal(x1, x2, out)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/numpy/_op.py", line 6622, in equal
    return _api_internal.equal(x1, x2, out)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/_ffi/_ctypes/function.py", line 115, in __call__
    raise get_last_ffi_error()
mxnet.base.MXNetError: MXNetError: Type inconsistent, Provided = float32, inferred type = int32
```
But numpy supports equal operation between different types

### fail to use mxnet.numpy.prod(a.shape)
```
>>> mx.np.prod(a.shape)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 31, in prod
AssertionError: Argument a must have NDArray type, but got (5,)
```
while numpy supports that.

**Comment by leezu** [comment]
I think divergence between numpy and mxnet.numpy should be treated as bug as long as it's not explicitly called out in the documentation?

**Comment by leezu** [comment]
@acphile can you help to create a separate issue for each problem, to simplify tracking the individual issues?

**Comment by acphile** [comment]
> @acphile can you help to create a separate issue for each problem, to simplify tracking the individual issues?

Now they are added:
https://github.com/apache/incubator-mxnet/issues/18297
https://github.com/apache/incubator-mxnet/issues/18299
https://github.com/apache/incubator-mxnet/issues/18300
https://github.com/apache/incubator-mxnet/issues/18301

**Comment by yzhliu** [comment]
As they been well tracked by separate issues, I will close this issue.
