### ISSUE TITLE
/usr/bin/ld fail when build

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#18170]
## Description
build mxnet master in ubuntu with build.sh

### Error Message
/usr/bin/ld: build/src/operator/tensor/elemwise_binary_broadcast_op_basic_gpu.o: in function `void mxnet::op::BinaryBroadcastComputeSparseEx<mshadow::gpu, mxnet::op::mshadow_op::div>(nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)':
tmpxft_000410b3_00000000-5_elemwise_binary_broadcast_op_basic.cudafe1.cpp:(.text._ZN5mxnet2op30BinaryBroadcastComputeSparseExIN7mshadow3gpuENS0_10mshadow_op3divEEEvRKN4nnvm9NodeAttrsERKNS_9OpContextERKSt6vectorINS_7NDArrayESaISE_EERKSD_INS_9OpReqTypeESaISJ_EESI_[_ZN5mxnet2op30BinaryBroadcastComputeSparseExIN7mshadow3gpuENS0_10mshadow_op3divEEEvRKN4nnvm9NodeAttrsERKNS_9OpContextERKSt6vectorINS_7NDArrayESaISE_EERKSD_INS_9OpReqTypeESaISJ_EESI_]+0x48a): undefined reference to `void mxnet::op::ElemwiseBinaryOp::DnsCsrCsrOp<mshadow::gpu, mxnet::op::mshadow_op::mul>(nnvm::NodeAttrs const&, mxnet::OpContext const&, mxnet::NDArray const&, mxnet::NDArray const&, mxnet::OpReqType, mxnet::NDArray const&, bool)'
/usr/bin/ld: build/src/operator/tensor/elemwise_binary_broadcast_op_basic_gpu.o: in function `void mxnet::op::BinaryBroadcastComputeSparseEx<mshadow::gpu, mxnet::op::mshadow_op::mul>(nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)':
tmpxft_000410b3_00000000-5_elemwise_binary_broadcast_op_basic.cudafe1.cpp:(.text._ZN5mxnet2op30BinaryBroadcastComputeSparseExIN7mshadow3gpuENS0_10mshadow_op3mulEEEvRKN4nnvm9NodeAttrsERKNS_9OpContextERKSt6vectorINS_7NDArrayESaISE_EERKSD_INS_9OpReqTypeESaISJ_EESI_[_ZN5mxnet2op30BinaryBroadcastComputeSparseExIN7mshadow3gpuENS0_10mshadow_op3mulEEEvRKN4nnvm9NodeAttrsERKNS_9OpContextERKSt6vectorINS_7NDArrayESaISE_EERKSD_INS_9OpReqTypeESaISJ_EESI_]+0x3c2): undefined reference to `void mxnet::op::ElemwiseBinaryOp::DnsCsrCsrOp<mshadow::gpu, mxnet::op::mshadow_op::mul>(nnvm::NodeAttrs const&, mxnet::OpContext const&, mxnet::NDArray const&, mxnet::NDArray const&, mxnet::OpReqType, mxnet::NDArray const&, bool)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:645: bin/im2rec] Error 1

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by chinakook** [comment]
https://github.com/apache/incubator-mxnet/pull/17767

**Comment by ptrendx** [comment]
Are you sure you have a clean build environment? When developing that PR I did see that there are some problems with dependency tracking for some of the files touched by it (not caused by the PR) and I had to do a clean build to see all the changes made. Maybe it is a manifestation of the same problem?

**Comment by chinakook** [comment]
I'll try again.

**Comment by chinakook** [comment]
@ptrendx Thank for your reply. It's solved by using right version of gfortran in Ubuntu 20.04.
