### ISSUE TITLE
Compiling with USE_TVMOP flaky due to downloading

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18229]
```
[2020-05-04T03:39:44.167Z] -- Prepare external packages for TVM...

[2020-05-04T03:39:44.167Z]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

[2020-05-04T03:39:44.167Z]                                  Dload  Upload   Total   Spent    Left  Speed

[2020-05-04T03:39:44.167Z] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

[2020-05-04T03:50:03.354Z] 
 32  325M   32  105M    0     0   112M      0  0:00:02 --:--:--  0:00:02  112M
 44  325M   44  143M    0     0  67.2M      0  0:00:04  0:00:02  0:00:02 31.8M
[...]
 44  325M   44  143M    0     0   238k      0  0:23:15  0:10:14  0:13:01     0

[2020-05-04T03:50:03.354Z] curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110
```

Suggest to rely on system LLVM instead of downloading LLVM as part of configuration.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18226/1/pipeline

**Comment by ChaiBapchya** [comment]
Yet another issue : unrelated PR #18206 
```
curl: (7) Failed to connect to releases.llvm.org port 443: Connection timed out
```
unix-cpu
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-18206/runs/7/nodes/47/log/?start=0

unix-gpu
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18206/6/pipeline

**Comment by ChaiBapchya** [comment]
Another one #18261 

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18261/1/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18261/1/pipeline

@leezu 
clang failed but not sure if its related to this issue
Is this 500 internal server error in google protobuf related to tvm?
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fclang/detail/PR-18261/1/pipeline

**Comment by leezu** [comment]
No, that's due to using Makefile build

**Comment by szha** [comment]
I think this issue requires developers to navigate through the set-up of CI pipeline and eventually come to the responsible script, so it's not a good first issue without pointers on the code base.

**Comment by samskalicky** [comment]
This is being invoked here:
https://github.com/apache/incubator-mxnet/blob/3840786a25b16d0cfe6411e26f25aba8d3b574ff/cmake/BuildTVM.cmake#L19

that tries to download the llvm archive here:
https://github.com/apache/incubator-mxnet/blob/3840786a25b16d0cfe6411e26f25aba8d3b574ff/contrib/tvmop/prepare_tvm.sh#L48
