### ISSUE TITLE
[Website] Global Search Feature

### ISSUE THREAD

**Issue by ys2843** [apache/incubator-mxnet#18234]
##  Description
MXNet website hosts not only rich and comprehensive documentations, but also many useful resources including tutorials, installation guide, APIs and blogs etc. The majority of our target users are those who are curious about MXNet and want to explore, their primary target will mostly be tutorials, FAQs, blog posts and other solution contents. But the current version of MXNet website does not provide anything for them to find the materials they need. This could prevent users from further exploring and staying interested in MXNet. And for power users who will come to API docs directly, it will greatly improve their experience if a global search feature is available everywhere not only within API document.

## Proposed Solution
Global search feature on MXNet website can improve user experience, website usability and better convey our product values to end users.  A search bar should be implemented on the top Nav bar accessible to users across all main information pages, with the capability of searching information across all site and always provide the valid and fresh results.
Integrate a stable and trust worthy 3rd party search service to MXNet websiteIt is a lot more cost and time efficient than start from scratch. [DocSearch by Algolia](https://docsearch.algolia.com/) is one of the site search solutions that is technical documentation oriented and widely adopted by many professional documentation websites including [PyTorch](https://pytorch.org/), [TypeScript](https://www.typescriptlang.org/index.html ), [React](https://reactjs.org/), [Bootstrap](https://getbootstrap.com/), [Scala](https://www.scala-lang.org/) and [GitLab](https://about.gitlab.com/) etc. 

## Deliverable
A search bar powered by DocSearch on MXNet website, capable of searching across all site in any version, located on the right side of main Nav bar with a drop down menu attached that contains all available version options.

## Acceptance Criteria
* Search bar accessible across all information web pages
* Providing real time searching, search as you type, always return fresh and valid result
* The scope of search should be the whole website and all versions
* Simple and consistent front end user interface for searching and result displaying

## Stakeholders
@sandeep-krishnamurthy 
@aaronmarkham 
@leezu 
@sojiadeshina 
@szha 

## Reference
1. [Detailed quip project proposal - internal](https://quip-amazon.com/3bsRAMn6uvx0/MXNet-Website-20-Global-Search)
2. [DocSearch website](https://docsearch.algolia.com/)
3. [Please share your feedback here](https://quip-amazon.com/awmoAhi6FQuK/Website-20-Global-Search-Feedback)

## Dev link
Demo link of this project:  http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/

**Comment by ys2843** [comment]
@mxnet-label-bot add [website]

**Comment by ChaiBapchya** [comment]
Thanks a lot for this feature.

Few suggestions
1. Let's get rid of the symbol at the end of each line
<img width="608" alt="Screen Shot 2020-05-09 at 2 13 40 AM" src="https://user-images.githubusercontent.com/10992635/81469620-c1c31480-919a-11ea-9668-c0d0bcb70027.png">

2. Also it only gives 5 suggestions. Is there any way of giving more suggestions & preferably a longer list [scrollable?]

**Comment by ys2843** [comment]
@ChaiBapchya Thank you for the feedback. Very good suggestion. I will add it to the quip doc.
