### ISSUE TITLE
[VOTE] Where to host the ipynotebook and examples

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#1825]
It is great that we are getting more examples than we started, and the repo is now dominated as a jupyter notebook project.  The fact that notebook have more bulk size than traditional script makes it a bit cumbersome to keep everything in the main repo and make things explode in size. 

I am opening this issue to vote a solution to host notebook, or example.
- option 1: Create a repo mxnet-notebook to host all notebooks, put this as submodule under mxnet/example
- option 2: Create a  repo mxnet-notebook to host all notebooks, do not put this as submodule,  but include links to the notebooks from READMEs in example
- option 3: Create a repo mxnet-example, and move the entire example folder into the repo, optionally put it as submodule of mxnet.

Option 3 requires a bit of work in fixing the links, and we will do that in several days span, move things over before delete the main one

**Comment by mli** [comment]
vote 2. cloning notebook could be a problem especially the network is not so great (such as at china). but recommend to have script in notebook to install mxnet and start the notebook service, so that anyone can view and run the notebook in browser, just as what we did for gtc.

don't think it's necessary to have a separate example repo. but i do recommend to clean the example folder.

**Comment by antinucleon** [comment]
vote 2

**Comment by terrytangyuan** [comment]
Vote 2. It will take a very long time to recursively clone the repo if include them as submodule. Providing a link to users should be enough.

**Comment by pluskid** [comment]
Vote 2. The notebooks already exist in history, so moving does not help speeding up cloning unless the user explicitly do shallow clone. But it is still good to separate notebooks as the history diff usually is not very interpretable.

I would prefer to keep the other examples in the main repo. While notebooks can be directly viewed online, the examples needs to be downloaded to run. Having them in the main repo makes it convenient for user to try them out.
