### ISSUE TITLE
same calculation for CrossEntropy and NegativeLogLikelihood in mxnet.metric

### ISSUE THREAD

**Issue by acphile** [apache/incubator-mxnet#18266]
CrossEntropy: http://mxnet.incubator.apache.org/api/python/docs/api/metric/index.html#mxnet.metric.CrossEntropy
NegativeLogLikelihood: http://mxnet.incubator.apache.org/api/python/docs/api/metric/index.html#mxnet.metric.NegativeLogLikelihood
Currently, in mxnet.metric, the definition of CrossEntropy is actually same as the definition of NegativeLogLikelihood, which leads to a duplicate in mxnet.metric.

**Comment by eric-haibin-lin** [comment]
i think we can remove one of them
