### ISSUE TITLE
[v1.x] CI pipeline for NVIDIA Jetson fails with "unsupported GNU version"

### ISSUE THREAD

**Issue by nickguletskii** [apache/incubator-mxnet#18298]
## Description

The CI pipeline for NVIDIA Jetson uses the following container:  https://hub.docker.com/r/dockcross/linux-arm64/
It was recently updated to use GCC 8:
https://github.com/dockcross/dockcross/commit/37c54a369441edbe98ef65a026d8704574cf086d

However, CUDA 9 doesn't support GCC versions above 6, so the CI pipelines are currently failing with the following message:

### Error Message

```
error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-18268/3/pipeline/43

## To Reproduce

Run a CI pipeline on the v1.x branch.

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by leezu** [comment]
It should be fine to backport the docker image used on master branch
