### ISSUE TITLE
How to shuffle recordIO file in place?

### ISSUE THREAD

**Issue by erogol** [apache/incubator-mxnet#1832]
I created a huge recordIO file but it is in natural order. Is it possible to shuffle in place or create another file from that file in shuffled order?

**Comment by LaoAnchor** [comment]
code like below in example code may help (https://github.com/dmlc/mxnet/blob/master/example/adversary/adversary_generation.ipynb)
`train_iter.reset()`

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
