### ISSUE TITLE
how to hybridize this code

### ISSUE THREAD

**Issue by yezqNLP** [apache/incubator-mxnet#18345]
When I use the following code, which cannot be hybridized as code `height, width = x.shape[2:]` which reported error that `AttributeError: 'Symbol' object has no attribute 'shape'`. 
How can I change this code to hybridize?

```
def calc_tf_padding(x,
                    kernel_size,
                    strides=1,
                    dilation=1):
    """
    Calculate TF-same like padding size.

    Returns
    -------
    tuple of 4 int
        The size of the padding.
    """
    height, width = x.shape[2:]
    oh = math.ceil(height / strides)
    ow = math.ceil(width / strides)
    pad_h = max((oh - 1) * strides + (kernel_size - 1) * dilation + 1 - height, 0)
    pad_w = max((ow - 1) * strides + (kernel_size - 1) * dilation + 1 - width, 0)
    return 0, 0, 0, 0, pad_h // 2, pad_h - pad_h // 2, pad_w // 2, pad_w - pad_w // 2

```
The method that call `calc_tf_padding`
```        
x = F.pad(x, mode="constant", pad_width=calc_tf_padding(x, kernel_size=3), constant_value=0)
```

**Comment by wms2537** [comment]
This might help you: https://mxnet.apache.org/api/python/docs/api/symbol/symbol.html?highlight=shape_array#mxnet.symbol.shape_array

**Comment by yezqNLP** [comment]
> This might help you: https://mxnet.apache.org/api/python/docs/api/symbol/symbol.html?highlight=shape_array#mxnet.symbol.shape_array

Thanks, I change `x.shape` to `F.shape_array`, `math.ceil` to `F.ceil`, `max` to `F.max`, and it still reports error that `pad_h//2`, `symbol and int can not calculated by //`.

**Comment by yezqNLP** [comment]
well, I solve this problem by record the padding_size in non_hybrid mode manually and discard `calc_tf_padding`.
