### ISSUE TITLE
the metric.py is missed in the latest master branch

### ISSUE THREAD

**Issue by TriLoo** [apache/incubator-mxnet#18386]
mxnet installed using latest source code from master branch complains: `AttributeError: module 'mxnet' has no attribute 'metric'`

looks like the `metric.py` is missed or moved to another package ?

**Comment by TriLoo** [comment]
It was indeed moved to `mx.gluon.metrix` ...

**Comment by cristobal140** [comment]
Hi, I have the same problem, I'm new to this and I don't know how to solve the problem.

could someone help me please?
