### ISSUE TITLE
Various issues on Python 3.8

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18380]
CI doesn't test Python 3.8 and in fact some things are broken. What I noticed:

- [Use of `time.clock()`](https://github.com/apache/incubator-mxnet/search?l=Python&q=time.clock) which is deprecated since Python 3.3 and not available in 3.8 in some files breaks those functionalities on 3.8

To prevent such issues, suggest to test Python 3.8 on the unix pipelines (and test the minimum supported Python version on centos).

**Comment by ma-hei** [comment]
@leezu can this be reproduced locally by running python tests via nosetest?

**Comment by leezu** [comment]
Yes. You'll see an exception due to accessing an undefined function. Though note that you should use pytest instead of nosetest.

**Comment by ma-hei** [comment]
I see, so as part of this fix we would update the base image of ubuntu_cpu to 20.04. I will create a first PR in which the base image of ubuntu_cpu is updated to 20.04, to see which tests are failing.

**Comment by ekdnam** [comment]
@szha I would love to work on this issue. Can you assign me to this?

**Comment by szha** [comment]
@ekdnam thanks for offering to help! let me know if you have any question or need any pointer.

**Comment by ekdnam** [comment]
Yes surely!

**Comment by ekdnam** [comment]
@szha is this a unix specific issue?

**Comment by szha** [comment]
@ekdnam apologies, I didn't realize that the issue has already been fixed in https://github.com/apache/incubator-mxnet/pull/18619/files#diff-9b62bcdde840f4769a6f1e1cf1e664a7L55 by @leezu. I think we still need to add the python3.8 pipeline, for which @ma-hei opened #18445.

**Comment by szha** [comment]
@ma-hei would you be able to complete #18445?

**Comment by ekdnam** [comment]
Oh okay, its no big deal. Till then, I shall try to solve some other issue

**Comment by ma-hei** [comment]
Hi, sorry I haven't looked at #18445 in a while. Will take a look again this week.

**Comment by leezu** [comment]
Python 3.8 is now tested on CI as part of https://github.com/apache/incubator-mxnet/pull/19588
