### ISSUE TITLE
[Development] License and Trademark issues in Distributions

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#18397]
Per https://lists.apache.org/thread.html/r738c102492649c754f49e2195985bc765df07df3c8a1e06942e8872f%40%3Cdev.mxnet.apache.org%3E, there are several licensing issues that we need to address and below are the issues as well as action items in each area.

## Developer pre-releases

This section tracks the problems that are related to nightly builds and developer-only pre-releases. The related issues are:
- Developer releases available to users and public searchable https://repo.mxnet.io / https://dist.mxnet.io
- The repo.mxnet.io and dist.mxnet.io weren't clear that the binaries there are for developer testing only and not for public consumption.
 
**Actions**
- [x] Add disclaimer to repo.mxnet.io and dist.mxnet.io to clarify that the nightly releases there are not intended for public consumption. (**done**)
- [x] Remove non-Apache releases in github release page. (**done**)(https://github.com/apache/incubator-mxnet/releases)
- [x] Remove repo.mxnet.io and dist.mxnet.io from search engine index (**done**)(https://github.com/apache/incubator-mxnet/issues/18397#issuecomment-647075093)

## First-party release

This section tracks the problems that are related to official releases that are intended to be Apache License v2 compliant. The related issues are:
- convenance binary releases containing Category X licensed code
- Maven releases containing Category X licensed code.
- PiPy releases containing Category X licensed code.
- Docker releases containing Category X licensed code.
- Trademark and branding issues with PiPy and Docker releases.

**Actions**
- [x] Delete problematic Maven releases. (**Waiting for [LEGAL-516](https://issues.apache.org/jira/browse/LEGAL-516)**) ([thread](https://lists.apache.org/thread.html/ra4e9572ac74857a80c64a31e8bf292d353e74cfa87bf457f47450303%40%3Cdev.mxnet.apache.org%3E), [INFRA-20442](https://issues.apache.org/jira/browse/INFRA-20442))
- [x] Delete problematic pypi releases. (**Waiting for [LEGAL-516](https://issues.apache.org/jira/browse/LEGAL-516)**)
- [x] Delete problematic docker releases.

## Third-party release

This section tracks the problems that are related to convenience binary releases that cannot be Apache License v2 compliant. The related issues are:
- Lack of clarity on all platforms for what is an ASF release and what is not.
- Developer releases available to users and public searchable https://repo.mxnet.io / https://dist.mxnet.io
- Trademark and branding issues with PiPy and Docker releases.
- NVIDIA's build of MXNet contains unreleased code: https://docs.nvidia.com/deeplearning/frameworks/mxnet-release-notes/rel_20-03.html
- AWS Deep Learning Container build of MXNet contains unreleased code: https://github.com/aws/deep-learning-containers/blob/master/mxnet/training/docker/1.6.0/py3/Dockerfile.gpu#L10

**Actions**
- [x] Review with Apache Trademark on the current third-party binary distributions of mxnet and make necessary correction. (**In progress**)
- [x] Review with Apache Legal on the appropriate license for convenience binary distribution and display it prominently. (**in progress**)([LEGAL-515](https://issues.apache.org/jira/browse/LEGAL-515))
- [x] Resolve NVIDIA trademark usage issue for MXNet (**in progress**, engaged NVIDIA in [LEGAL-516](https://issues.apache.org/jira/browse/LEGAL-516))
- [x] Resolve Amazon trademark usage issue for MXNet (**in progress**)
- [x] Add disclaimer in PyPI page on the license
- [x] Remove nightly builds in PyPI

## Documentation

This section tracks the problems that are related to documentation for releases and pre-releases. The related issues are:
- Website giving access to downloads of non released/unapproved code.
- Website giving access to releases containing Category X licensed code.
- Web site doesn't given enough warning to users of the issues with non (P)PMC releases or making it clear that these are not ASF releases.
- Lack of clarity on all platforms for what is an ASF release and what is not.

**Actions**
- [x] add disclaimer for non-Apache releases in installation selector (**done**)
- [x] remove mentions of nightly builds in pypi page in wheel build pipeline (**done**, update will happen with next release)

## Longer-term

This section tracks items that are for the purpose of mitigating usability impact as a result of addressing the issues above.

**Actions**
- [ ] Add source distribution to PyPI package `apache-mxnet` and build automatically on user machines.

Related:
#18463 
https://issues.apache.org/jira/browse/INCUBATOR-253

**Comment by leezu** [comment]
Another issue https://github.com/apache/incubator-mxnet/issues/18463

**Comment by justinmclean** [comment]
I would not consider the issues with repo.mxnet.io and dist.mxnet.io resolved. Please see and track progress in [1].

There is a further question that need to be ask is why do these domains exist at all? Projects (with some exceptions) are generally not allowed to use domains like this see [2]. There may have been discussions about this in this as that I'm not aware of but I cannot remember it being dices on the incubator list. What is the long term intention with these domain names? Who currently has control of this domain?

1. https://issues.apache.org/jira/browse/INCUBATOR-253
2. https://www.apache.org/foundation/marks/pmcs#websites
3. https://www.apache.org/foundation/marks/domains#secondlevel

**Comment by szha** [comment]
@justinmclean I'm not used to using JIRA so please excuse the choice of our tools and me insisting on tracking the progress here.

**Comment by szha** [comment]
Discouraged search engine with dist.mxnet.io/robots.txt and repo.mxnet.io/robots.txt and requested removal from google
![image](https://user-images.githubusercontent.com/2626883/85216292-8b4eec80-b337-11ea-95b1-d913a0895c31.png)

**Comment by justinmclean** [comment]
Re the domain repo.mxnet.io and dist.mxnet.io, other than their use you mean? link are provided to these pages from the getting started section of the website. I can also see the links exposed for example here [1] and here [2].

I can also see release and branding issue with 3rd parties e.g [3] which also link to those pages. You note NVIDIA is creating releases that include unreleased code. This is another issue the PPMC will need to deal with.

1. https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html
2. https://pypi.org/project/mxnet-cu101/
3. https://docs.nvidia.com/deeplearning/frameworks/mxnet-release-notes/rel_20-03.html

**Comment by szha** [comment]
The items in this issue are outdated and already tracked in INCUBATOR-253. For the remaining source distribution item, I created #20241 for tracking.
