### ISSUE TITLE
can't import mxnet

### ISSUE THREAD

**Issue by paylak2002** [apache/incubator-mxnet#18395]
After installing mxnet via pip I've tried to import the mxnet package, but unfortunately I've got this error message:
Illegal instruction (core dumped)
I think there are some problems with my cpu. My cpu: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller

**Comment by ChaiBapchya** [comment]
@pengzhao-intel @TaoLv for Intel CPU support, any idea?

**Comment by pengzhao-intel** [comment]
Which one are you installed? Could you share the CMD line?

**Comment by leezu** [comment]
You're using a too old cpu to be supported by the existing pip package. Please compile from source.

The pip packages will be fixed in the next release.

**Comment by leezu** [comment]
Reference https://github.com/apache/incubator-mxnet/pull/18408

**Comment by leezu** [comment]
@ciyongch please recommend if we like to backport the build improvements to 1.7 release and fix this issue for 1.7. Otherwise the pip wheels will remain broken on older cpu until 2.x release

**Comment by ciyongch** [comment]
Hi @leezu, do you mean https://github.com/apache/incubator-mxnet/pull/18408 will address this issue for the pip wheels? If so, i suggest to include this fix in v1.7.x and v1.x to make the upcoming release more stable :) Thanks.

**Comment by ciyongch** [comment]
Hi @leezu , would you mind to help backport the fix to v1.x and v1.7.x as well? Thanks!
