### ISSUE TITLE
Add Optuna to MXNet Ecosystem

### ISSUE THREAD

**Issue by Crissman** [apache/incubator-mxnet#18401]
Hi!

Optuna works well for optimizing hyperparameters for MXNet, and we've written an [integration module for MXNet](https://optuna.readthedocs.io/en/latest/reference/integration.html#optuna.integration.MXNetPruningCallback), and I've recently published a [blog about using MXNet with Optuna](https://medium.com/optuna/using-optuna-to-optimize-mxnet-hyperparameters-4c06518c1ec9).

Can Optuna be added to the MXNet Ecosystem?

Thanks!

**Comment by leezu** [comment]
Would you like to open a PR?

**Comment by Crissman** [comment]
PR opened. Thanks!

**Comment by wkcn** [comment]
The PR has been merged : )
Thank you for the contribution of MXNet Ecosystem!
