### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [apache/incubator-mxnet#18421]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by leezu** [comment]
cc @marcoabreu

**Comment by thomasrockhu** [comment]
Hi @marcoabreu and @leezu, let me know if there's anything I can do to help here.

**Comment by leezu** [comment]
@thomasrockhu if you can provide more details on the existing setup, that will be helpful. Changing this may require opening a ticket with the Apache Software Foundation Infrastructure Team at https://issues.apache.org/jira/secure/Dashboard.jspa

**Comment by thomasrockhu** [comment]
Hi @leezu, thanks for getting back to me. Regarding Apache Software Foundation Infrastructure Team, we asked a [similar repository] (https://github.com/apache/skywalking/issues/4835#issuecomment-635714799) to move to the integration as well. Since access has been granted, it should only require an admin to add this repository by configuring the [integration](https://github.com/apps/codecov)

**Comment by marcoabreu** [comment]
Thanks Thomas, I will check with Apache Infra in parallel.

In the meantime, could you elaborate what steps are necessary here to use the ingration? Which part of our setup is exactly being replaced - speak, which changes in our code-base have to be done? What has to be done before we make the switch and what afterwards?

Thanks for assisting us on this matter!

**Comment by marcoabreu** [comment]
From what I can see, the access for the app has already been granted. What steps are necessary for us to take here now?

**Comment by thomasrockhu** [comment]
Hi @marcoabreu, I just checked and everything looks good on our side. Thanks for the quick turnaround here!

**Comment by thomasrockhu** [comment]
As far as necessary steps, that's the only one. There is no need for code changes here. If you have been using the [team bot](https://docs.codecov.io/docs/team-bot), it can now be removed.

**Comment by leezu** [comment]
@marcoabreu thank you for checking with INFRA. I requested the access for the app as per the suggestions in above linked Apache repo. They stated we don't need an INFRA ticket but simply request the access with github. 

@thomasrockhu thank you. So let's close this ticket.

**Comment by leezu** [comment]
@thomasrockhu previously we only tracked codecov data without exposing it in Github PRs. Our codecov is not stable, and until then we'd like to not expose the data. Enabling the marketplace app lead to the codecov status being shown on every PR and commit. How do we disable this again?

**Comment by thomasrockhu** [comment]
Hi @leezu, if you want to disable status checks, you can update the `codecov.yml` to include

```
coverage:
  status:
    project: off
    patch: off
```

Let me know if that works for you!

**Comment by leezu** [comment]
Thank you @thomasrockhu. We'll work towards making the codecov stable and then re-enable the badges.

**Comment by thomasrockhu** [comment]
@leezu great, let me know what I can do to help!

**Comment by leezu** [comment]
@thomasrockhu the `codecov.yml` stopped working https://github.com/apache/incubator-mxnet/blob/master/.codecov.yml

New PRs show the `codecov/project` badge again despite we haven't made enough progress on stabilizing the CI to have a stable codecov https://github.com/apache/incubator-mxnet/pull/18757

**Comment by thomasrockhu** [comment]
Hi @leezu, it looks like there are duplicate entries under `coverage -> status -> project`
```
coverage:
  status:
    project: off
    patch: off
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
```
I would recommend removing one of them.

**Comment by leezu** [comment]
Thank you @thomasrockhu
