### ISSUE TITLE
The number of samples is batch size. How to convert the convolution to GEMM in the CPU? What is the effect of Batch size on GEMM?

### ISSUE THREAD

**Issue by lingweiyang** [apache/incubator-mxnet#18425]
## Description
(The location and name of the flaky test.)

## Occurrences
(Links to the known occurrences.)

## What have you tried to solve it?

1.
2.

**Comment by pengzhao-intel** [comment]
Could you elaborate on why do you want to covert Conv to GEMM in CPU?

**Comment by pengzhao-intel** [comment]
NAB,Closing since no enough information.
