### ISSUE TITLE
Third-party releases from Jenkins CI / CD on Dockerhub

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18479]
As of early 2019 https://hub.docker.com/u/mxnet provides automated third-party releases of the MXNet project (see [LEGAL-427](https://issues.apache.org/jira/browse/LEGAL-427)). The major change since then is that the pipeline moved to https://github.com/apache/incubator-mxnet/ via #16547 and is executed by the Jenkins Server. This may jeopardize it's status as a third-party. Note that due to inclusion of [Category-X](https://www.apache.org/legal/resolved.html#category-x) components, https://hub.docker.com/u/mxnet can't be a first-party / PPMC distribution channel.

This is pending clarification of ASF Legal in https://issues.apache.org/jira/browse/LEGAL-515

**Comment by leezu** [comment]
According to Roy Fielding from the ASF Legal team, "A third party acts on its own behalf, outside our scope or direction. AWS is not a third party unless it isn't acting at our direction – with our direction, it's just a data processor, which is our responsibility as the first party."

As of #16547, the Dockerhub releases are under control of the ASF as the CD pipeline code is under PPMC control. This means that the PPMC distributes Category-X builds on Dockerhub, which should not happen.

**Comment by szha** [comment]
Status of the issue has been tracked in LEGAL-515/516 and INCUBATOR-253
