### ISSUE TITLE
Import mxnet error

### ISSUE THREAD

**Issue by reking** [apache/incubator-mxnet#1850]
OSError: libluajit.so: cannot open shared object file: No such file or directory

It seems like in torch.py
try:
15      _LUAJIT = ctypes.CDLL("libluajit.so", mode=ctypes.RTLD_GLOBAL)

has problem.

But I changed the path to liblujit.so as absolute path, not working.

There must be something wrong with find lib in this file

**Comment by piiswrong** [comment]
```
try:
    _LUAJIT = ctypes.CDLL("libluajit.so", mode=ctypes.RTLD_GLOBAL)
except OSError:
    pass
```

**Comment by piiswrong** [comment]
This error should have been ignored. Are you sure you are using the most recent code?

**Comment by reking** [comment]
@piiswrong  Thank you for reply, I have checked the code, it's the newest one, with the 
try:
    _LUAJIT = ctypes.CDLL("libluajit.so", mode=ctypes.RTLD_GLOBAL)
except OSError:
    pass

in torch.py

OSError: libluajit.so: cannot open shared object file: No such file or directory

I am not sure which file causes this error, maybe base.py?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
