### ISSUE TITLE
Reduce the size of libmxnet_predict.so file genrated using amalgamation for android

### ISSUE THREAD

**Issue by saustar** [apache/incubator-mxnet#1851]
Hi,

I have followed the instructions given [here](https://github.com/dmlc/mxnet/tree/master/amalgamation#android). And I have my own libmxnet_predict.so file but size of this file is 6.2 MB whereas size of .so file used in[ WhatsThis](https://github.com/Leliana/WhatsThis) app is 4.8MB. How can I reduce the size of .so file?

Is it possible to reduce it to 1MB?

**Comment by tqchen** [comment]
You can reduce it by removing the un-used ops and only link to the necessary ones. By default the amalgamation linked to a lot of things. Some function may not be needed for prediction, but nevertheless registered as ndarray function or operators

**Comment by saustar** [comment]
@tqchen mxnet_predict-all.cc file has more than 1,00,000 lines. Is there any way to see which functions are not being used by my model.

**Comment by xylcbd** [comment]
mark

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
