### ISSUE TITLE
website redirects needed

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#18547]
## Description
I'm sure there are more, but let's put them here for now (until this gets resolved and we have to open another issue)

* https://mxnet.incubator.apache.org/versions/master/faq/model_parallel_lstm.html --> https://mxnet.apache.org/api/faq/model_parallel_lstm
* https://mxnet.incubator.apache.org/versions/master/faq/multi_devices.html --> https://mxnet.apache.org/api/faq/distributed_training

For these maybe just a redirect of /master/faq/* --> /api/faq/* would be sufficient.

**Comment by ys2843** [comment]
I will add the redirect

**Comment by ys2843** [comment]
Question about the second link `multi_devices.html` => `distributed_training`. If we add this link, there will be 2 different cards link to the same content. https://mxnet.apache.org/api/python/docs/tutorials/performance/index.html

**Comment by ys2843** [comment]
@aaronmarkham The above PR redirects the `version/master/` to a valid link. For update links in the documents, could you ask someone who is familiar with the contents to do it? Or just confirm this change and I will go ahead updating it. Thanks
