### ISSUE TITLE
CPU memory leak when running inference on model with GPU

### ISSUE THREAD

**Issue by zhongqingyang** [apache/incubator-mxnet#18591]
## Description
I used cpp to inference on model with GPU in childthread.
cpu Memory increase 0.1G after 72000 execution.
cpu Memory increase 0.14G after 100000 execution.
cpu Memory increase 0.236G after 163500 execution.
cpu Memory increase 0.437G after 163500 execution.
cpu Memory increase 2G after 643100 execution.

### Here is my test code
`
#include <iostream>
#include <opencv2/opencv.hpp>
#include <mxnet-cpp/MxNetCpp.h>
#include <zconf.h>
#include <thread>
#include <future>
#include <unistd.h>
#include <malloc.h>

#define FILE_NAME_SIZE 255

#include "mxnet/c_predict_api.h"
using namespace mxnet::cpp;
using namespace std;

std::vector<mx_uint> batch_size = {1, 3, 512, 896};//设置模式
Context global_ctx = Context::gpu();//模型选择的运行设备cpu或gpu
map<string, NDArray> args_map;//框架内部保留的代码,初始化模型有用到
map<string, NDArray> aux_map;//框架内部保留的代码,初始化模型有用到
Symbol net;//网络对象
Executor *executor = nullptr;//执行器 用于网络前向传播
string model_type = "YOLO";
mutex mut;

void LoadParameters(string params) {
    map<string, NDArray> parameters;
    NDArray::Load(params, 0, &parameters);

    for (const auto& pair : parameters) {
        string type = pair.first.substr(0, 4);
        string name = pair.first.substr(4);
        if (type == "arg:") {
            (args_map)[name] = pair.second.Copy(global_ctx);
        } else if (type == "aux:") {
            (aux_map)[name] = pair.second.Copy(global_ctx);
        }
    }

    NDArray::WaitAll();
}

NDArray YOLOSSDTransform(vector<cv::Mat> ori_image_vec, int &new_height, int &new_width)
{
    int pre_H = 0, pre_W = 0;
    int maxLongSide = 1024;
    int short_side = 512;

    //判断是否有输入图片
    if (ori_image_vec.empty())
    {
        LG << "输入图片为空";
        throw runtime_error("输入图片为空");
    }
    //判断输入尺寸是否一致
    for (auto & i : ori_image_vec)
    {
        if (pre_H == 0)
        {
            pre_H = i.rows;
            pre_W = i.cols;
        }
        else
        {
            if (pre_H != i.rows || pre_W != i.cols)
            {
                LG << "输入图片尺寸不一致";
                throw runtime_error("输入图片尺寸不一致!");
            }
            pre_H = i.rows;
            pre_W = i.cols;
        }
    }

    int H = ori_image_vec[0].rows;
    int W = ori_image_vec[0].cols;
    float times;
    vector<float> array;
    //std::vector<uchar> array;
    if (H > W)
    { //当高大于宽时
        if ((H * short_side) > (maxLongSide * W))
        { //当图片过于狭长时,选用长边为固定边
            times = maxLongSide * 1.0 / H;
        }
        else
        { //当图片不狭长时,选用短边为固定边
            times = short_side * 1.0 / W;
        }
    }
    else
    { //当宽大于高时
        if ((W * short_side) > (maxLongSide * H))
        { //当图片过于狭长时,选用长边为固定边
            times = maxLongSide * 1.0 / W;
        }
        else
        { //当图片不狭长时,选用短边为固定边
            times = short_side * 1.0 / H;
        }
    }

    if (model_type == "YOLO")
    {
        new_height = int(times * H) / 32 * 32;
        new_width = int(times * W) / 32 * 32;
    }
    else if (model_type == "SSD")
    {
        new_height = int(times * H);
        new_width = int(times * W);
    }
    else
    {
        LG << "no model type  match with " << model_type << " !" << endl;
        throw runtime_error("wrong value with model type !");
    }
    //图片标准化
    cv::Mat im;
    int channels = 3;
    int bach_size = ori_image_vec.size();
    cv::resize(ori_image_vec[0], im, cv::Size(new_width, new_height));
    int size = im.rows * im.cols * channels;
    std::vector<std::vector<float>> files(bach_size);
    files[0].resize(size);

    float *image_data = files[0].data();
    float *ptr_image_b = image_data;
    float mean_b = 0.485;
    float mean_g = 0.456;
    float mean_r = 0.406;
    float std_b = 0.229;
    float std_g = 0.224;
    float std_r = 0.225;

    for (int i = 0; i < im.rows; ++i)
    {
        auto data = im.ptr<uchar>(i);
        for (int j = 0; j < im.cols; j++)
        {
            *ptr_image_b++ = (static_cast<float>(*data++) / 255.0 - mean_b) / std_b;
            *ptr_image_b++ = (static_cast<float>(*data++) / 255.0 - mean_g) / std_g;
            *ptr_image_b++ = (static_cast<float>(*data++) / 255.0 - mean_r) / std_r;
        }
    }

    //transpose shape from (h,w,c) to (c,h,w)
    for (int k = 0; k < 1; k++)
    {
        for (int c = 0; c < 3; ++c)
        {
            for (int i = 0; i < new_height; ++i)
            {
                for (int j = 0; j < new_width; ++j)
                {
                    array.push_back(static_cast<float>(image_data[(i * new_width + j) * 3 + c]));
                }
            }
        }
    }

    //expend shape from (c,h,w) to (1,c,h,w)
    Shape image_shape = Shape(1, 3, new_height, new_width);
    NDArray transformed_image = NDArray(image_shape, global_ctx, false);

    transformed_image.SyncCopyFromCPU(array.data(), image_shape.Size());
    NDArray::WaitAll();
    return transformed_image;
}

//
void PredictFromMat(const NDArray& normalized_images,const float &height_plus, const float &width_plus)
{
    std::lock_guard<std::mutex> _guard(mut);

    normalized_images.CopyTo(&(executor->arg_dict()["data"]));
    NDArray::WaitAll();

    // Run the forward pass.
    executor->Forward(false);

    // The output is available in executor->outputs.
    auto ids = executor->outputs[0].Copy(Context(kCPU, 0));
    auto scores = executor->outputs[1].Copy(Context(kCPU, 0));
    auto bboxes = executor->outputs[2].Copy(Context(kCPU, 0));
    NDArray::WaitAll();
    malloc_trim(0);
}

int main() {

    net = Symbol::Load("/home/enhance/workspace/json/walker-ssd-symbol.json");
    LoadParameters("/home/enhance/workspace/params/walker-ssd.params");

    //获取执行器
    args_map["data"] = NDArray(Shape(batch_size), global_ctx);
    executor = net.SimpleBind(global_ctx, args_map, map<string, NDArray>(),map<string, OpReqType>(),aux_map);

    cv::Mat frame;
    vector<cv::Mat>vframe;
    frame = cv::imread("/home/enhance/png/0.jpg");
    vframe.push_back(frame);
    int w,h;
    NDArray normalized_images = YOLOSSDTransform(vframe,h,w);
    frame.release();
    vframe.clear();

    for (auto i = 0;i<1000000;i++){
        cout<<i<<endl;
        auto fun = [&normalized_images, h, w] { return PredictFromMat(normalized_images, h, w); };
        std::thread go(fun);
        go.join();
    }
}

`

**Comment by chinakook** [comment]
This api may not support multi thread safety.
