### ISSUE TITLE
DataParallelExecutorGroup Issue? 

### ISSUE THREAD

**Issue by FranciscoReveriano** [apache/incubator-mxnet#18623]
Hello. I was wondering if this file was moved to a different location. I built MxNet from source and the following command no longer works: 
from mxnet.executor_manager import DataParallelExecutorGroup

**Comment by FranciscoReveriano** [comment]
I am also not able to make the following imports anymore: 
from mxnet.module.base_module import BaseModule, _check_input_names, _parse_data_desc

**Comment by leezu** [comment]
You can refer to https://github.com/apache/incubator-mxnet/issues/17676 regarding these API deprecations
Does the 1.x branch or the last stable release work for you? There the APIs are available
