### ISSUE TITLE
LINK : fatal error LNK1181: 无法打开输入文件“ws2_32.lib”

### ISSUE THREAD

**Issue by ZjjConan** [apache/incubator-mxnet#1864]
CMake之后，利用VS编译的时候出现这样一个问题，查看了一下VS，在mxnet项目的依赖项里面是包含有ws2_32.lib库。不知道为什么会出现这样的问题。

我的环境是 WIN 8.1 + VS2013 + OpenCV 3.0

Thanks

**Comment by piiswrong** [comment]
@hjk41

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
