### ISSUE TITLE
Unit test 'test_npx_batch_norm' failed under UNIX GPU environment

### ISSUE THREAD

**Issue by AntiZpvoh** [apache/incubator-mxnet#18687]
## Description
Unit test 'test_npx_batch_norm' failed under UNIX GPU environment. And this test is in file tests/python/unittest/test_numpy_op.py.

## Occurrences
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/master/2099/pipeline/376
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18319/30/pipeline

## What have you tried to solve it?

retrigger CI [unix-gpu] multiple times.

**Comment by wkcn** [comment]
The issue may be related to the PR #18504
