### ISSUE TITLE
missing commands in the instructions for building from source

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#18698]
## Description
As part of #18487 the build from source instruction no longer includes the commands for building from source. Also, it doesn't document the usage of the cmake configs in https://github.com/apache/incubator-mxnet/tree/master/config

**Comment by leezu** [comment]
The documentation is contained in the files. https://github.com/apache/incubator-mxnet/blob/19e373daac76b466cf11b5d31fa5d5e2eb518a21/config/linux.cmake#L18-L36
