### ISSUE TITLE
Transpose only supports up to 6 dimensions

### ISSUE THREAD

**Issue by JeanKossaifi** [apache/incubator-mxnet#18695]
## Description
Transpose does not currently support tensors with more than 6 dimensions.

### Error Message
```
E           mxnet.base.MXNetError: Traceback (most recent call last):
E             File "src/operator/tensor/./matrix_op-inl.h", line 459
E           MXNetError: Check failed: shp.ndim() <= 6 (7 vs. 6) : Transpose support at most 6 dimensions
```

## To Reproduce
Apply transpose to a higher-order tensor.

## Environment
Python 3.7.3
MXNet 2.0.0

**Comment by szha** [comment]
Thanks for reporting, Jean. I confirm that this affects numpy operators too.

**Comment by szha** [comment]
Two changes will help immediately:
- Collapse consecutive axes of the input array into a single axis here https://github.com/apache/incubator-mxnet/blob/master/src/operator/numpy/np_matrix_op-inl.h#L142-L149
- Extend the implementation to support more https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/matrix_op-inl.h#L362-L419

The root cause is really the limitation of template based programming in mshadow. Because of that choice, the axis is in template variable and thus needs to be expanded at compile time. We should move away from this approach and have a transpose implementation without mshadow instead.

Let's focus on only the immediate changes, and I will open a separate issue for the larger change.

**Comment by wkcn** [comment]
Hi @szha , I am trying to fix it and select 'Collapse consecutive axes of the input array into a single axis here when axes.ndim() > 2'.

**Comment by wkcn** [comment]
Hi @szha , I create a [`TransposeKernel`](https://github.com/wkcn/incubator-mxnet/blob/support_transpose_dim_gt_6/src/operator/tensor/matrix_op-inl.h#L324) and need to copy the argument (namely `axes`) into the target context. Is there any good way to copy it?

I try to call [`get_space_typed`](https://github.com/wkcn/incubator-mxnet/blob/support_transpose_dim_gt_6/src/operator/tensor/matrix_op-inl.h#L429), but it need to declare a temporary space in each operator which calls `TransposeImpl`.

**Comment by JeanKossaifi** [comment]
I still get the issue with `mxnet-1.8.0.post`: 

```python
import mxnet.numpy as mnp

a = mnp.arange(2**7).reshape((2,)*7)
a = mnp.transpose(a)
```

raises the following issue:
```python
MXNetError: Traceback (most recent call last):
  File "../src/operator/numpy/np_matrix_op.cc", line 53
MXNetError: Check failed: shp.ndim() <= 6 (7 vs. 6) : Transpose support at most 6 dimensions
```

**Comment by szha** [comment]
@JeanKossaifi I think the change was not included in the 1.x but only in 2.0. The np support in 1.x is experimental, and if you plan on integrating with the np interface, it's probably a good idea to do so with 2.0 which includes all the latest fixes.

**Comment by JeanKossaifi** [comment]
Thanks @szha -- what's the recommended way to install mxnet 2.0? 
I'm looking mostly for a pypi version for the CI. I tried `pip install mxnet==2.0.0a0` but I get an error: 
```
ERROR: Could not find a version that satisfies the requirement mxnet==2.0.0a0 (from versions: 1.6.0, 1.7.0.post1, 1.7.0.post2, 1.8.0.post0)
ERROR: No matching distribution found for mxnet==2.0.0a0
```

**Comment by szha** [comment]
@JeanKossaifi you can use the nightly version for development and testing purpose from https://dist.mxnet.io/python

**Comment by szha** [comment]
It would be
```
pip install mxnet<3 --pre -f https://dist.mxnet.io/python
```

**Comment by JeanKossaifi** [comment]
@szha when I run 
```pip install mxnet<3 --pre -f https://dist.mxnet.io/python;```, 
I get the error: `/home/runner/work/_temp/41bba640-2fbf-4c14-beef-a62339f5a353.sh: line 16: 3: No such file or directory` 

I did install `gfortran`. Am I missing something? 
Thanks! :)

**Comment by merajhashemi** [comment]
@JeanKossaifi Try this:
```bash
pip install mxnet --pre -f https://dist.mxnet.io/python
```
This will install the latest nightly build. As of today version `2.0.0b20220718`.
