### ISSUE TITLE
[website] beta.mxnet.io redirects affecting discoverability

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#18719]
#### Search 
- Searching mxnet grid generator, mxnet grid sampler, mxnet bilinear sampler, mxnet batchnorm on google
- all 3 searches give beta.mxnet.io links in first 2 results
- Clicking on all of them routes to mxnet.apche.org landing page and not the actual page of the API.

![Screen Shot 2020-07-15 at 1 53 23 PM](https://user-images.githubusercontent.com/10992635/87595004-b7ddf600-c6a2-11ea-932e-ce6c31a31519.png)
![Screen Shot 2020-07-15 at 1 53 34 PM](https://user-images.githubusercontent.com/10992635/87595012-b9a7b980-c6a2-11ea-86fe-8d5a7dea6ece.png)
![Screen Shot 2020-07-15 at 1 53 49 PM](https://user-images.githubusercontent.com/10992635/87595015-bad8e680-c6a2-11ea-9581-8221f299ba86.png)
![Screen Shot 2020-07-15 at 1 54 16 PM](https://user-images.githubusercontent.com/10992635/87595016-bb717d00-c6a2-11ea-9d18-e20ac50295a6.png)

## Suggestions
1. Prevent indexing of beta.mxnet.io & instead have official website APIs getting indexed
2. Redirect beta.mxnet.io links to actual working links [instead of landing page]

**Comment by ChaiBapchya** [comment]
@ys2843

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot update [bug, website]

**Comment by marcoabreu** [comment]
We should add a robots.txt to beta.mxnet.io to avoid crawling

@szha

**Comment by szha** [comment]
I've taken down beta.mxnet.io already.
