### ISSUE TITLE
module doc missing

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#18727]
## Description
This is blank: https://mxnet.apache.org/api/python/docs/api/module/index.html

I believe this was deprecated. Should this node be removed or should it point to older versions?

**Comment by szha** [comment]
let's have it removed.

**Comment by suyz526** [comment]
Hi, 

In [https://mxnet.apache.org/api/python/docs/api](https://mxnet.apache.org/api/python/docs/api), almost every page is empty. 

This 'beta' page works: [https://mxnet-beta.staged.apache.org/api/python/docs/api](https://mxnet-beta.staged.apache.org/api/python/docs/api)

Why there exist two different websites for the document? And google always lead me to the first one, which is the blank one.

**Comment by ys2843** [comment]
This problem is fixed, user is currently redirected to corresponding page in v1.6 website.
