### ISSUE TITLE
search issues

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#18728]
## Description
* Doesn't return results on v1.6
  - to reproduce, change version to 1.6, then search for metric.
<img width="839" alt="2020-07-15_18-28-17" src="https://user-images.githubusercontent.com/5974205/87616027-f7b7d400-c6c8-11ea-8159-bb4b116f88c7.png">

* Doesn't have metadata about which API is being returned... Having a list of results that all look the same, but are not the same, isn't user-friendly.
<img width="904" alt="2020-07-15_18-19-05" src="https://user-images.githubusercontent.com/5974205/87615922-ab6c9400-c6c8-11ea-951b-b0357b79e91b.png">

**Comment by ys2843** [comment]
<img width="845" alt="Screen Shot 2021-02-13 at 3 35 04 PM" src="https://user-images.githubusercontent.com/23468760/107864462-2a69ac80-6e11-11eb-8a46-7a9ad2af173a.png">

Search is working for v.16 website, and metadata is returned for similar search result.
