### ISSUE TITLE
test_operator_gpu.py::test_batchnorm_with_type inadvertently retests cases, misses others

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#18737]
## Description
Notice the test case duplication in the code:
https://github.com/apache/incubator-mxnet/blob/2abf0b8c2b3361c73c9dfdeabdb8a88278b693d0/tests/python/gpu/test_operator_gpu.py#L406-L424

This is one of the issues fixed by PR https://github.com/apache/incubator-mxnet/pull/18694 in commit https://github.com/apache/incubator-mxnet/pull/18694/commits/4e81d14fb05d48e1eb53e861fb0065b68347f4c0

**Comment by szha** [comment]
fixed by #18694
