### ISSUE TITLE
executor_manager doc shows up blank in master

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#18730]
## Description
This is blank: https://mxnet.apache.org/api/python/docs/api/mxnet/executor_manager/index.html
Looks like it was (re)moved in master. Does this doc node need to be removed?

**Comment by szha** [comment]
@eric-haibin-lin do we need this?

**Comment by eric-haibin-lin** [comment]
https://github.com/apache/incubator-mxnet/issues/18730
