### ISSUE TITLE
test_gluon_probability_v2.py::test_gluon_kl and test_gluon_probability_v1.py::test_gluon_kl_v1 are flaky

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#18755]
## Description
I encountered a failure in one of my CI runs, and have supplied a fix in PR https://github.com/apache/incubator-mxnet/pull/18694 in commit https://github.com/apache/incubator-mxnet/pull/18694/commits/3e05edb3ff4e166831779d438c4537550986b2a0.

The fix was developed by printing out the distribution params and noting that the failures occurred when the parameters of the Geometric distribution (being selected from a [0,1] uniform distribution) were in the range 1e-4 -> 1e-3.  The fix was to select the parameters from np.random.uniform(size=shape, low=1e-3).  This is consistent with approaches taken elsewhere in the tests, where the parameters of the binomial distribution are taken from np.random.uniform(low=0.1, size=shape).

After the fix, both tests passed 3000 trials without error.  Tagging test creator @xidulu.

## Repro with
MXNET_TEST_SEED=1633210984 pytest --verbose -s tests/python/unittest/test_gluon_probability_v2.py::test_gluon_kl
MXNET_TEST_SEED=702820740 pytest --verbose -s tests/python/unittest/test_gluon_probability_v1.py::test_gluon_kl_v1

**Comment by xidulu** [comment]
@DickJC123
Thanks for discovering this issue, I will take a look at your fix.

**Comment by szha** [comment]
fixed by #18694
