### ISSUE TITLE
Horovod support in MXNet 2

### ISSUE THREAD

**Issue by ZheyuYe** [apache/incubator-mxnet#18766]
## Description
Horovod is currently one of the most effective ways of gpu communication acceleration but lacks of support for current mxnet 2.0. I tried to run Horovod on the latest Mxnet master branch (2020.07.21) and it failed as below. 

### Steps to reproduce
Horovod was installed by `HOROVOD_GPU_OPERATIONS=NCCL pip3 install  --no-cache-dir horovod ` and the openmpi version I used is 4.0.2.

[A gist exmaple](https://gist.github.com/ZheyuYe/f59b33c20a0b6fdcbf471af3e2d5ac64) revised by [offical mnist example](https://github.com/apache/incubator-mxnet/blob/master/example/distributed_training-horovod/gluon_mnist.py) was executed with `mpirun -np 4 -H localhost:4 -bind-to none -map-by slot python3 mxnet_mnist.py`

Please point out the steps I missed if I did't run this example properly.
## Outputs
```bash
File "/home/ubuntu/.local/lib/python3.6/site-packages/horovod/mxnet/__init__.py", line 154, in broadcast_parameters
    broadcast_(tensor, root_rank, name=str(name))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/horovod/mxnet/mpi_ops.py", line 232, in broadcast_
    c_in = tensor.handle
AttributeError: 'Parameter' object has no attribute 'handle'
Traceback (most recent call last):
  File "gluon_mnist.py", line 144, in <module>
    hvd.broadcast_parameters(params, root_rank=0)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/horovod/mxnet/__init__.py", line 154, in broadcast_parameters
    broadcast_(tensor, root_rank, name=str(name))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/horovod/mxnet/mpi_ops.py", line 232, in broadcast_
    c_in = tensor.handle
AttributeError: 'Parameter' object has no attribute 'handle'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[28180,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

## Comments
@leezu  @sxjscience

**Comment by leezu** [comment]
Horovod only supports MXNet 1 at this point. I suggest you open an issue in the Horovod repository and request (or directly contribute) MXNet 2 support. That's because Horovod relies on some implementation details of the MXNet 1 APIs that have been changed.

**Comment by szha** [comment]
cc @eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
I have a version that seems to work with mxnet built from source here: https://github.com/eric-haibin-lin/horovod/tree/mx2 
feel free to try it out if you need it before the PR is merged

**Comment by ZheyuYe** [comment]
@eric-haibin-lin  Thanks a lot. I'll try this version.

**Comment by sxjscience** [comment]
I'll close this since it has been supported in horovod. Thanks @eric-haibin-lin and @leezu .
