### ISSUE TITLE
Failures seen in unittest test_gluon_probability{_v1,_v2}.py::test_gluon_cauchy_{v1,}

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#18775]
## Description
This was observed during the development of https://github.com/apache/incubator-mxnet/pull/18424.  I've developed a fix which I've added via commit https://github.com/apache/incubator-mxnet/pull/18424/commits/29286c3f7e3b3e7f0836877c2644b95820182322.  I observed that the failures occurred when the sample was near one or both ends of the unit normal distribution for the samples data input.  Repro commands provided below.

## Occurrences
MXNET_TEST_SEED=783333771  pytest --verbose -s tests/python/unittest/test_gluon_probability_v2.py::test_gluon_cauchy
MXNET_TEST_SEED=1447693795 pytest --verbose -s tests/python/unittest/test_gluon_probability_v2.py::test_gluon_cauchy
MXNET_TEST_SEED=952434416 pytest --verbose -s tests/python/unittest/test_gluon_probability_v1.py::test_gluon_cauchy_v1

**Comment by xidulu** [comment]
@DickJC123 
It looks like your commits have solved this issue. Thanks for that.

This reason behind, is the heavy-tailed property of Cauchy, when the input for the quantile/icdf function is close to 1 or 0, the output will blow up, causing flaky tests.
![image](https://user-images.githubusercontent.com/26022201/88356358-1a697d00-cd9a-11ea-8b5a-aa7f95c335b1.png)
