### ISSUE TITLE
bfloat16 rendered as uint16

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18788]
```
[ins] In [1]: import mxnet as mx

[ins] In [3]: a = mx.nd.arange(10)

[ins] In [6]: import numpy as np

[ins] In [7]: a.astype(np.dtype([('bfloat16', np.uint16)]))
Out[7]:

[(    0,) (16256,) (16384,) (16448,) (16512,) (16544,) (16576,) (16608,)
 (16640,) (16656,)]
<NDArray 10 @cpu(0)>
```

**Comment by szha** [comment]
cc @rongzha1 @pengzhao-intel

**Comment by rongzha1** [comment]
@piotr

**Comment by pengzhao-intel** [comment]
@leezu could you give more description of what's the problem is and where it is used?

**Comment by leezu** [comment]
MXNet bfloat16 type is registered as having numpy equivalent `np.dtype([('bfloat16', np.uint16)])`:

 https://github.com/apache/incubator-mxnet/blob/c1098aa33d6795f84a19601d0319d5bb8e19f317/python/mxnet/ndarray/ndarray.py#L86

As printing a NDArray works via converting to numpy, this causes `bfloat16` arrays to be printed as `uint16`.

The fundamental issue here is that numpy does not support `bfloat16`. We can consider if there is a better solution

**Comment by pengzhao-intel** [comment]
@ElaineBao could you explain the background?

**Comment by ElaineBao** [comment]
As @leezu said, numpy doesn't support the data type of `bfloat16`, when printing a NDArray as type `bfloat16`, it will be printed as pre-defined `uint16`. 

I think it's not a bug actually, if printing a NDArray has to work via converting to numpy, and numpy has no support of `bfloat16`, the only way to print is converting to another numpy supported data type.

**Comment by leezu** [comment]
@ElaineBao I agree it's expected for people who understand how the internal mxnet printing logic works. But I'm not sure if this is the optimal user experience.

**Comment by ElaineBao** [comment]
Yes, I think so, it's not that friendly for users to print out `bfloat16` values. We can consider if there is a better solution for this.

**Comment by samskalicky** [comment]
> MXNet bfloat16 type is registered as having numpy equivalent `np.dtype([('bfloat16', np.uint16)])`:
> 
> https://github.com/apache/incubator-mxnet/blob/c1098aa33d6795f84a19601d0319d5bb8e19f317/python/mxnet/ndarray/ndarray.py#L86
> 
> As printing a NDArray works via converting to numpy, this causes `bfloat16` arrays to be printed as `uint16`.
> 
> The fundamental issue here is that numpy does not support `bfloat16`. We can consider if there is a better solution

Should we just convert to float32 in Numpy?

**Comment by sxjscience** [comment]
Is it possible to customized a dtype in numpy just for printing?

**Comment by pengzhao-intel** [comment]
@anko-intel
