### ISSUE TITLE
Bug in new docs

### ISSUE THREAD

**Issue by pluskid** [apache/incubator-mxnet#1881]
See for example [here](http://mxnet.readthedocs.org/en/latest/packages/python/ndarray.html#mxnet.ndarray.empty). I'm not very sure what is `dtype=<Mock name='mock.float32' id='140046414661200'>` here.

**Comment by tqchen** [comment]
Was due to numpy is blacklisted by using mock module, because numpy is not available in build machine. c.f. https://github.com/dmlc/mxnet/blob/master/docs/conf.py#L30

We should change default parameter to string type perhaps

**Comment by eric-haibin-lin** [comment]
Documents are updated. Closing it for now due to inactivity. Please feel free to reopen it for followup discussions.
