### ISSUE TITLE
Does mxnet support shared model with multi input?

### ISSUE THREAD

**Issue by jiumem** [apache/incubator-mxnet#1882]
like this:
 margin loss
      |      |
     h1   h2
       \    /
      model
       /     \
    x1     x2
Maybe I should use a bucket mechanism and `bucket_key` will be `x1`, `x2` .
But how can I write a margin loss both with the `h1` and  `h2` ?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
