### ISSUE TITLE
ONNX model zoo missing json and params files 

### ISSUE THREAD

**Issue by quantum-fusion** [apache/incubator-mxnet#18862]
## Description
(A clear and concise description of what the bug is.)

I want to download an ONNX model from the model Zoo. (https://github.com/onnx/models). Since the model zoo only provides the ONNX files

I do not know where to get these files from, and how to generate them. (see exporter function) (https://mxnet.apache.org/versions/1.6/api/python/docs/tutorials/deploy/export/onnx.html#How-to-use-MXNet-to-ONNX-exporter-API)

Where do these files come from, and can they be generated from the ONNX model?
# Downloaded input symbol and params files
sym = './resnet-18-symbol.json'
params = './resnet-18-0000.params'

# paste outputs here
```

**Comment by leezu** [comment]
json and params file is the mxnet format. ONNX is a separate format. You can import onnx models to mxnet, or you can download mxnet model from mxnet model zoo.

**Comment by quantum-fusion** [comment]
The problem is the .ONNX model is custom, and did not come from the MxNet model zoo.  Do you know how to generate the sym and params files themselves?

**Comment by TristonC** [comment]
@szha  Has this issue solved in 1.x?

**Comment by Zha0q1** [comment]
the .json and .params file are exported from MXNet. We can convert mxnet models to the onnx format and recently GluonCV has also converted many pretrained cv models and hosted them here https://github.com/dmlc/gluon-cv/tree/master/scripts/onnx

**Comment by Zha0q1** [comment]
[This](https://mxnet.apache.org/versions/1.8.0/api/python/docs/tutorials/deploy/export/onnx.html) is the doc for converting mxnet models to the onnx format in mxnet 1.8. 

mxnet 1.9 release will also include a big update package to the mxnet2onnx conversion module, which will have more and better operator support, dynamic input shapes, multiple input dtypes and more
