### ISSUE TITLE
Build from source issue

### ISSUE THREAD

**Issue by yx1215** [apache/incubator-mxnet#18891]
## Description
In the build from source guide [here](https://mxnet.apache.org/versions/1.6/get_started/osx_setup), I need to copy the file make/osx.mk as ./config.mk. However, there seems to be no directory called make?

### Error Message
```
f8ffc22b2d38:mxnet yixiaxia$     cp make/osx.mk ./config.mk
cp: make/osx.mk: No such file or directory
```

**Comment by szha** [comment]
@yx1215 we deprecated Makefile on master branch in favor of the new CMake build that @leezu helped revamping. The instruction can be found in https://mxnet.apache.org/get_started/build_from_source

@ys2843 @leezu what do you recommend about the build from source guide problem?

**Comment by leezu** [comment]
@yx1215 you're reading the instructions for MXNet 1.6 (look the upper right corner of the website). The instructions will work for 1.6. If you want to build master version, then select master version of website.

As this is a version mismatch issue, I'm closing the issue. But feel free to re-open or comment if there are more issues

**Comment by ys2843** [comment]
I am working on enabling build_from_source per version in master website in #18835, WIP
