### ISSUE TITLE
Benchmarking on 8 GPU System

### ISSUE THREAD

**Issue by gosha1128** [apache/incubator-mxnet#1889]
Alright, I'm running the out-of-box CIFAR10 image training script on an 8 GPU system.

It seems like I'm getting the best performance using just 4 GPUs (graph attached.)  Is this expected to be expected or possibly i need to do some additional configuration ?  

Thanks !

![mxnet_cifar10_gpus](https://cloud.githubusercontent.com/assets/442121/14619220/4a43764e-056b-11e6-9fc1-f8259789ca7f.png)

**Comment by mli** [comment]
the workload of cifar10 with inception is quite tiny. i suggest you to try the imagenet dataset

**Comment by gosha1128** [comment]
great, thats what i needed to know.  i figured i'd try a smaller dataset first and work my way to imagenet...

**Comment by gosha1128** [comment]
Hey, Mu - maybe you can point me in the right direction.  

As you recommended - I have downloaded imagenet and i'm ready to reproduce the experiment here- http://mxnet-bing.readthedocs.org/en/latest/tutorial/imagenet_full.html

There seems to be some missing documentation links in the **step-by-step tutorial** here - https://mxnet.readthedocs.org/en/latest/python/io.html#create-dataset-using-recordio

Should I just use the train_imagenet.py script and point it to the imagenet directory ?  Do I need to use "recordio" files ?

Thanks...

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
