### ISSUE TITLE
Website API doc is empty

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#18909]
<img width="1286" alt="Screen Shot 2020-08-11 at 2 26 19 PM" src="https://user-images.githubusercontent.com/5545640/89950553-b12d9a80-dbde-11ea-9293-28bb2f62f760.png">

https://mxnet.apache.org/api/python/docs/api/gluon/loss/index.html

**Comment by szha** [comment]
looking into this in #18839
