### ISSUE TITLE
Can't link master version docs

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18913]
https://mxnet.apache.org/get_started/build_from_source will always forward external visitors to https://mxnet.apache.org/versions/1.6/get_started/build_from_source.html

Sometimes we may wish to link the master docs. Currently there is no link, such as https://mxnet.apache.org/versions/master/get_started/build_from_source.html available and it is impossible to link to websites in the master version documentation

**Comment by szha** [comment]
@ys2843 would it make sense to use a url schema like `https://mxnet.apache.org/versions/master/` for master docs too, so that it won't break the links?
