### ISSUE TITLE
Floating point exception in mxnet.ndarray.LeakyReLU

### ISSUE THREAD

**Issue by leeyeetonn** [apache/incubator-mxnet#18934]
## Description
(A clear and concise description of what the bug is.)
`mxnet.ndarray.LeakyReLU` has floating point exception when given data's shape contain 0. Please see provided code snippet for example.

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=10` before running your script.)
>Floating point exception (core dumped)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
```python
import mxnet
import numpy as np

input = mxnet.nd.array(np.random.rand(0,1,1))
mxnet.ndarray.LeakyReLU(input)
```

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. run the provided code in python interpreter or as a script
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```
Got 404 when trying to get the script.

Some environment information:

* OS: ubuntu 18.04
* Python: 3.7.6
* pip: 20.0.2
* numpy: 1.18.5
* mxnet: 1.6.0

**Comment by szha** [comment]
I can reproduce the problem. The error also occurs in 2.0 with the numpy interface
```
import mxnet as mx
from mxnet import np

mx.npx.set_np()

input = mx.np.random.rand(0,1,1)
mx.npx.leaky_relu(input)
```

**Comment by TaoLv** [comment]
We will take a look. cc @pengzhao-intel
