### ISSUE TITLE
input argument(--exts) in tools/make_list.py

### ISSUE THREAD

**Issue by xycoco** [apache/incubator-mxnet#1893]
Hi!

I want to create my own dataset, so I use`tools/make_list.py` to make a image list. However, when I input argument `--exts=.png`, I can't get any output in output file. 

Then I debug program and find that the input argument has changed as `['.', 'p', 'n', 'g']` instead of `['.png']`, and I modify the code `parser.add_argument('--exts', type=list, default=['.jpeg','.jpg'], help='list of acceptable image extensions.')` as `parser.add_argument('--exts', nargs='+', default=['.jpeg','.jpg'], help='list of acceptable image extensions.')`. The program can run smoothly.

I want to ask whether I use `tools/make_list.py` incorrectly or it is just a minor bug.

Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
