### ISSUE TITLE
Floating point exception in mxnet.ndarray.Correlation

### ISSUE THREAD

**Issue by leeyeetonn** [apache/incubator-mxnet#18942]
## Description
(A clear and concise description of what the bug is.)
`mxnet.ndarray.Correlation` has floating point exception when given `stride2=0`. Please see the provided code for example.
### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=10` before running your script.)
>Floating point exception (core dumped)
## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
```python
import mxnet
import numpy as np
data1 = mxnet.nd.array(np.random.rand(1,1,1,1))
data2 = mxnet.nd.array(np.random.rand(1,1,1,1))
mxnet.ndarray.Correlation(data1=data1, data2=data2, stride2=0)
```
### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. run the provided code in python interpreter or as a script
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```
Got 404 when trying to get the script.

Some environment information:

* OS: ubuntu 18.04
* Python: 3.7.6
* pip: 20.0.2
* numpy: 1.18.5
* mxnet: 1.6.0

**Comment by szha** [comment]
So here's the problem:
```
% DMLC_LOG_STACK_TRACE_DEPTH=150 MXNET_ENGINE_TYPE=NaiveEngine lldb python3.7 -- test_18942.py
(lldb) target create "python3.7"
Current executable set to 'python3.7' (x86_64).
(lldb) settings set -- target.run-args  "test_18942.py"
(lldb) run
Process 82919 launched: '/usr/local/bin/python3.7' (x86_64)
Process 82919 stopped
* thread #2, stop reason = exec
    frame #0: 0x0000000100006000 dyld`_dyld_start
dyld`_dyld_start:
->  0x100006000 <+0>: popq   %rdi
    0x100006001 <+1>: pushq  $0x0
    0x100006003 <+3>: movq   %rsp, %rbp
    0x100006006 <+6>: andq   $-0x10, %rsp
(lldb) cont
Process 82919 resuming
[23:55:46] ../src/engine/engine.cc:55: MXNet start using engine: NaiveEngine
[23:55:46] ../src/storage/storage.cc:198: Using Pooled (Naive) StorageManager for CPU
Process 82919 stopped
* thread #2, queue = 'com.apple.main-thread', stop reason = EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)
    frame #0: 0x0000000112b06279 libmxnet.dylib`mxnet::op::CorrelationProp::InferShape(this=0x000000010056ffa0, in_shape=0x00007ffeefbfc1d0, out_shape=0x00000001005baeb0, aux_shape=0x00007ffeefbfc1b0) const at correlation-inl.h:219
   216 	     / static_cast<float>(stride1));
   217 	    top_height_ = std::ceil(static_cast<float>(paddedbottomheight - border_size_ * 2)\
   218 	     / static_cast<float>(stride1));
-> 219 	    neighborhood_grid_radius_ = param_.max_displacement / stride2;
   220 	    neighborhood_grid_width_ = neighborhood_grid_radius_ * 2 + 1;
   221 	    top_channels_ = neighborhood_grid_width_ * neighborhood_grid_width_;
   222 	    CHECK_GE(top_width_, 1U) <<
```

https://github.com/apache/incubator-mxnet/blob/9bdd4d6347c284770ee5bfe5ae98f1dabc283829/src/operator/correlation-inl.h#L219

The code needs to guard against zero-size array for right operand of `/`, and we should add a smoke test to guard against such problem in this op, similar to https://github.com/apache/incubator-mxnet/pull/18972/files

**Comment by ekdnam** [comment]
@szha can I work on this issue? Would need some advice on how to solve it

**Comment by szha** [comment]
@ekdnam yes. I think in this case the problem is that both stride1 and stride2 should not be zero. The existing mechanism for declaring operator parameter ranges is in the declaration of the parameter object. Currently, it only has default values:
https://github.com/apache/incubator-mxnet/blob/0de7484884292eb028342b1e5669233792429af0/src/operator/correlation-inl.h#L57-L60
To fix it, we will need to do something similar to https://github.com/apache/incubator-mxnet/pull/18857/files

**Comment by ekdnam** [comment]
Noted @szha 

Are these changes okay?

`DMLC_DECLARE_FIELD(stride1).set_default(1).set_lower_bound(1)`
`.describe("stride1 quantize data1 globally");`
 `DMLC_DECLARE_FIELD(stride2).set_default(1).set_lower_bound(1)`
`.describe("stride2 quantize data2 within the neighborhood centered around data1");`
