### ISSUE TITLE
mxnet in mac os

### ISSUE THREAD

**Issue by balla2011** [apache/incubator-mxnet#1895]
I installed the mxnet following the instructions.However,at the end of the process,just before make -j4,it occurred an error that 
<img width="644" alt="a9e73068-84d3-4880-adab-17302e52983b" src="https://cloud.githubusercontent.com/assets/18537874/14628879/8341f096-0634-11e6-92e3-66ee16943296.png">
I searched everywhere in the github,but could not find "cblas.h"!!!!!!!!!!!!Who can help me !SOS!!!!!!!

**Comment by balla2011** [comment]
A billion thanks to the helper~

**Comment by piiswrong** [comment]
you need to install openblas

**Comment by balla2011** [comment]
<img width="499" alt="aafdbc83-ee09-49b9-be0a-9d8e50c512dc" src="https://cloud.githubusercontent.com/assets/18537874/14632380/f2f75c9e-064a-11e6-8427-74a33b4fd230.png">
love your reply~but has already installed at first

**Comment by balla2011** [comment]
LOVE YOUR REPLY~MUA~BUT,openblas is included in install homebrew/science~It is said that openblas HAS ALREADY INSTALLED!OH~still cannot find cblas.h....is there anything with the path?I am installing it for the whole day.....OH MY GOd!Can I speak Chinese?
----- 原始邮件 -----
发件人：Eric Junyuan Xie <notifications@github.com>
收件人：dmlc/mxnet <mxnet@noreply.github.com>
抄送人：balla2011 <mhweijianding@sina.com>
主题：Re: [dmlc/mxnet] mxnet in mac os (#1895)
日期：2016年04月19日 15点46分

you need to install openblas

&mdash;

**Comment by tjuzhao111** [comment]
It seems that you have not add your blas include path into the config.mk.

**Comment by tmatas** [comment]
`ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib'`
and
`ADD_CFLAGS = '-I/usr/local/opt/openblas/include'`
in the `config.mk` file should work for you.

**Comment by AlecWong** [comment]
#2835

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
