### ISSUE TITLE
test_bbox_augmenters randomly crashes

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#18986]
## Description
tests/python/unittest/test_contrib_gluon_data_vision.py::TestImage::test_bbox_augmenters

## Occurrences
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-18969/7/pipeline

**Comment by ChaiBapchya** [comment]
+1 for unrelated PR : #19061
https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/windows-gpu/branches/PR-19061/runs/1/nodes/109/steps/155/log/?start=0

**Comment by leezu** [comment]
https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/windows-gpu/branches/PR-19478/runs/1/nodes/108/steps/133/log/?start=0

**Comment by leezu** [comment]
Also crashes on Linux. Repro via:

`MXNET_TEST_SEED=1492532915 python3.8 -m pytest tests/python/unittest/test_numpy_contrib_gluon_data_vision.py::TestImage::test_bbox_augmenters`

**Comment by leezu** [comment]
@zhreshold please see the deterministic reproducer in the comment above.

**Comment by leezu** [comment]
https://github.com/apache/incubator-mxnet/blob/a2b400c72e4069a2ee531a969fa874bef109a763/src/operator/image/image_random-inl.h#L836-L880

```
(lldb) p sector
(int) $8 = 6
(lldb) p c_HlsSectorData[6]
(const int [3]) $9 = ([0] = 2020422990, [1] = 846488942, [2] = 1765109871)
```

```
* thread #1, name = 'python3.8', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007fff3adc8c54 libmxnet.so`mxnet::op::image::HLS2RGBConvert(src_h=0x00007fffffff29f0, src_l=0x00007fffffff29ec, src_s=0x00007fffffff29e
8, dst_r=0x00007fffffff29e4, dst_g=0x00007fffffff29e0, dst_b=0x00007fffffff29dc) at image_random-inl.h:877:9
    frame #1: 0x00007fff3adc8042 libmxnet.so`mxnet::op::image::AdjustHueImpl(alpha=-0.0850340575, ctx=0x00007fffffff3030, inputs=size=1, req=size=1, outp
uts=size=1) at image_random-inl.h:895:3
    frame #2: 0x00007fff3adc0783 libmxnet.so`mxnet::op::image::RandomColorJitter(attrs=0x0000555556c5e7f0, ctx=0x00007fffffff3030, inputs=size=1, req=siz
e=1, outputs=size=1) at image_random-inl.h:991:11
```
