### ISSUE TITLE
Documentation bug: format issue in the document of `mxnet.contrib.quantization.quantize_model_mkldnn` 

### ISSUE THREAD

**Issue by DNXie** [apache/incubator-mxnet#18993]
## Description
There is a format issue in the document of `mxnet.contrib.quantization.quantize_model_mkldnn`  in the **Parameter** and **Returns** section. 

Link to the document: https://mxnet.apache.org/versions/1.6/api/python/docs/api/contrib/quantization/index.html#mxnet.contrib.quantization.quantize_model_mkldnn

![image](https://user-images.githubusercontent.com/24580222/90995086-d16b3b00-e588-11ea-82c4-fe5547adb1a1.png)

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=10` before running your script.)
None
## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
None

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```
OS: ubuntu 18.04
Python: 3.7.6
pip: 20.0.2
numpy: 1.18.5
mxnet: 1.6.0

**Comment by bgawrych** [comment]
@mxnet-label-bot remove [Bug, needs triage]
@mxnet-label-bot add [Doc, MKLDNN, v1.x]

**Comment by bgawrych** [comment]
@mxnet-label-bot add [Doc, MKLDNN, v1.x]

**Comment by bgawrych** [comment]
@szha - issue is fixed, please close
