### ISSUE TITLE
unix-cpu flaky. Timeouts and fails on different test suits

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#19031]
## Description
For PR https://github.com/apache/incubator-mxnet/pull/18930 it has failed on different test suits at different times 

## Occurrences
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18930/4/pipeline

https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18930/3/pipeline

https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18992/11/pipeline/

https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-18690/57/pipeline/

**Comment by szha** [comment]
@access2rohit which test? please fill out the template.

**Comment by access2rohit** [comment]
Last reported failure showed 
test_io.py::test_Cifar10Rec
test_io.py::test_inter_methods_in_augmenter 
timed out

**Comment by szha** [comment]
as discussed offline, Rohit will report the multiple test issues as individual issues. Thanks Rohit.
