### ISSUE TITLE
Numpy GCD

### ISSUE THREAD

**Issue by Zha0q1** [apache/incubator-mxnet#19077]
we have np.lcm but not gcd, should we add it?

**Comment by Zha0q1** [comment]
If no one is actively working on this I will give it a try.

**Comment by szha** [comment]
thanks for bringing this up! yes I think it would be very useful. make sure the semantics is consistent with np.gcd.

**Comment by wkcn** [comment]
There is a PR about np.gcd (https://github.com/apache/incubator-mxnet/pull/16744/files).
I do not know why it is closed.

**Comment by Zha0q1** [comment]
I had something very similar to that PR that I was going to publish. @haojin2 would you share shed some lights on why the pr was closed?
