### ISSUE TITLE
cannot find cpp-package

### ISSUE THREAD

**Issue by fireant** [apache/incubator-mxnet#19086]
## Description
The master branch doesn't have the cpp-package directory. It seems in June this was removed?

### Error Message
The C++ package is not built. `USE_CPP_PACKAGE` is not used in the cmake script.

## To Reproduce
Try to build with the c++ package from master.

**Comment by pribadihcr** [comment]
@fireant, did you resolve it?

**Comment by leezu** [comment]
@pribadihcr you will need to use the `v1.x` branch. If you are interested in helping to update the CPP package for the master branch that would be very welcome. (It needs update due to deprecation of some underlying APIs in master)
