### ISSUE TITLE
multiple input/output of a layer

### ISSUE THREAD

**Issue by freesouls** [apache/incubator-mxnet#1909]
Hi, for example, My network has two branches `a` and `b`, and in some middle layer(which I will implement later, let's call it `newLayer`), how can I pass two branches `a` and `b` to `newLayer`?
(Note: **`a` and `b` have different data shapes!**)

for a common layer, I can write the following code with one input and one output

```
fc = mx.symbol.FullyConnected(data=a, name='fc', num_hidden=10)
```

what if input data has two streams?
and what if my `newLayer` also has two output streams, how can I use them? like below?

```
outs = mx.symbol.newLayer(data=(a,b), name='newLayer')
c = outs[0]
d = outs[1]
```

is the above codes right? I can not find any docs!!!

thanks in advance!

**Comment by tqchen** [comment]
You are in general correct, except that if you define an input of two inputs, you can declare two inputs, and it is likely you will do

```
outs = mx.symbol.newLayer(a, b, name='newLayer')
```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
