### ISSUE TITLE
Bullet points on website are not separated by new lines

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#19091]
## Description
On https://mxnet.apache.org/versions/1.6/api/faq/security.html the bullet point list does not get separated into newlines

### Error Message
![image](https://user-images.githubusercontent.com/18629099/92314122-fd98aa00-efd3-11ea-9567-bf49f825d59f.png)

**Comment by ys2843** [comment]
Fixed in latest 1.7.0 and master website
https://mxnet.apache.org/versions/1.7.0/api/faq/security.html
https://mxnet.apache.org/versions/master/api/faq/security.html
