### ISSUE TITLE
Fatal Python error: Aborted in test_operator.py::test_correlation

### ISSUE THREAD

**Issue by r3stl355** [apache/incubator-mxnet#19105]
## Description
`python -m pytest tests/python/unittest/test_operator.py -k "test_correlation"` throws `Fatal Python error: Floating point exception` here: https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L3237-L3238

## Occurrences
Happens on MacOS, not tested/seen elsewhere

**Comment by szha** [comment]
Thanks for reporting. I tried just now on a mac and didn't trigger the same problem. Could you also add information on your mxnet build, and the environment?

**Comment by r3stl355** [comment]
Perhaps my mxnet build is outdated, I'll follow with an update after rebuild

**Comment by r3stl355** [comment]
Issue disappeared after full rebuild, learning from my own mistakes here, sorry for wasted time

**Comment by szha** [comment]
no worries
