### ISSUE TITLE
Error in test_operator.py::test_deformable_convolution

### ISSUE THREAD

**Issue by r3stl355** [apache/incubator-mxnet#19104]
## Description
AttributeError: module 'mxnet.symbol.numpy_extension' has no attribute 'deformable_convolution'. 

Looks like `src/operator/contrib/deformable_convolution.cc` has been removed or renamed from codebase, closest attribute I found is `deconvolution` but I'm not sure if it's about the same thing

## Occurrences
To replicate, `python -m pytest tests/python/unittest/test_operator.py -k "test_deformable_convolution"`

**Comment by szha** [comment]
@r3stl355 this has been moved to the npx namespace #19046 and you need to re-build mxnet or update your source code.

**Comment by r3stl355** [comment]
Issue disappeared after full rebuild, learning from my own mistakes here
