### ISSUE TITLE
CUDA:OUT of Memory

### ISSUE THREAD

**Issue by CXMA479** [apache/incubator-mxnet#1910]
I have seen some similar issues,but they do not match. I use MXNet under julia to build a NN.
code like this
 `gpu_dw1=gpu_w.*(1-mx.sign(gpu_w))`  (where `gpu_dw1` is define as NDArray,so as `gpu_w`) in iteration will suffer from error like the title.
But what most drives me crazy is that by simply placing a line of `copy(gpu_dw1);`  behind the previous ,things goes fine! And this means I have to cost most of the time in data transfer. IS there any way to make the engine work right away? not just idle!

**Comment by vchuravy** [comment]
cc @pluskid 

@CXMA479 can you post a minimal code example? It helps tremendously in debugging that kind of problem. Also what hardware are you running on and what is the version of the MXNet.jl package?

**Comment by CXMA479** [comment]
@vchuravy 
Thanks for your advance.

**Platform**: Ubuntu 14.04 64-bits 
 **MXNet Version** : 0.0.8(comes from julia's Pkg.installed(),but I compiled `libmxnet.so` manually from `github` which I guess being latest,is that?)
**Graphic Card**: GTX 760 (4GB)

**Code Example**:
`using MXNet
ctx=mx.gpu();
gpu_w=mx.rand(0,1,( 7000,9600),ctx);
const iter=6;
const sub_iter=30;

for i=1:iter
println("$i loop");
   for sub_i=1:sub_iter
       gpu_dw1=gpu_w.*(1-mx.sign(gpu_w));
        copy(gpu_dw1);   #  **if you comment this line**,you would like to get sth. like **Error**
end
end`



**Error**:

`[07:53:11] /home/chen/bin/mxnet/dmlc-core/include/dmlc/./logging.h:235: [07:53:11] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
[07:53:11] /home/chen/bin/mxnet/dmlc-core/include/dmlc/logging.h:235: [07:53:11] src/engine/./threaded_engine.h:295: [07:53:11] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [07:53:11] src/engine/./threaded_engine.h:295: [07:53:11] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN9__gnu_cxx27__verbose_terminate_handlerEv at /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (unknown line)
unknown function (ip: 0x7f6b44c9a6d6)
unknown function (ip: 0x7f6b44c9a703)
unknown function (ip: 0x7f6b44cedaf5)
unknown function (ip: 0x7f6b45a1f182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
Aborted (core dumped)`
**NOTE**:
 `/home/chen/bin/mxnet ` is downloaded from `github`,NOT from julia' `Pkg`.

I'll appreciate any suggestion from you.

**Comment by vchuravy** [comment]
Sometimes the interaction between GC and GPU memory can be troublesome. We only release memory when the Julia values are gc'd and your code is creating a large amount of copies and you are running out of memory because of that.

Additionally the code you are using creates a few temporaries arrays that then need to be garbage collected, amplifying the problem. `gpu_w` and `gpu_dw1` together use about 600MBs and one iteration of your code allocates atleast 800MB for temporaries.

From my understanding of MXNet.jl we currently don't have to many inplace operators defined for NDArrays to do such computations and mainly rely on MXNet graph based execution to do those optimizations. So you might have more luck expressing this in terms of the symbolic API.

See the latter part of http://mxnetjl.readthedocs.org/en/latest/user-guide/overview.html for a discussion of inplace operations (low-level API) and the symbolic API.

@pluskid Please correct me if I got anything wrong :)

**Comment by CXMA479** [comment]
@vchuravy 
ok,it seems impossible by using NDArrays.
I have also being trying Symbolic API,but it is not easy for me,for example,there is no transpose operation ,but most important ,how can I use `backward()`  of `executor`?  The document seems to fail to give more details ;I saw there is a object of `grad_arrays` in the `executor`,but after implementing `backward()` I got nothing from it.

> using MXNet
> ctx=mx.gpu();
> const n_h=5000;
> const n_i=9066;
> gpu_w=mx.rand(0,1,(n_h,n_i),ctx);
> gpu_x_noise=mx.rand(-1,1,(n_i,1),ctx);
> 
> X_noise=mx.Variable(:X_noise);
> W_t=mx.Variable(:W_t);
> WX_noise=mx.FullyConnected(data=X_noise,weight=W_t,name=:WX_noise,no_bias=1,num_hidden=n_h);
> 
> exec_wx=mx.bind(WX_noise,context=ctx,args=Dict(:W_t=>gpu_w',:X_noise=>gpu_x_noise),);
> mx.forward(exec_wx);
> mx.backward(exec_wx);
>

**Comment by pluskid** [comment]
A `transpose` symbolic operator has been added in the upstream (libmxnet) recently. I guess we should be able to use it automatically (need to update the doc).

For the backward, if your graph contains a loss node at the top, then it should be fine. Otherwise, you need to have some kinds of `output_error` or `out_grad` to allow it to do a chain-rule to back-propagate. The computed gradients are stored in `executor.grad_arrays`.

**Comment by CXMA479** [comment]
Good,I mean updating the doc.But  `loss node` and 
> Otherwise, you need to have some kinds of output_error or out_grad
sound abstract.Maybe more tutorials should be included in the document(also,I need more time to learn).
Now,let me share some tricks obtained yesterday to reduce time cost  :
replacing 

> copy(gpu_dw1);
with  

> copy(gpu_dw1[1:70]);

:)

Thanks

**Comment by CXMA479** [comment]
Well, following your suggestion(with the help of `transpose` operator)
I made some code using symbolic API, but there seems no difference : 


> const n_h=6000;
> const n_i=9600;
> const rho=0.03;
> const iter=100;
> const learn_rate=0.004;
> gpu_x_noise=mx.rand(0,1,(n_i,1),ctx);
> gpu_w=mx.rand(-0.01,0.01,(n_h,n_i),ctx);
> mxones_n_i=mx.ones((1,n_i),ctx);
> exec_dw1=mx.bind(DW1,context=ctx,args=Dict(:X_noise=>gpu_x_noise,:W=>gpu_w,:MXONES_n_i=>mxones_n_i));
> jlogg1=zeros(iter);
> dyn_learn_rate=0.0;
> cpu_j1=zeros(1,1);
> for i=1:iter
>    dyn_learn_rate=learn_rate*i/iter;
>    mx.forward(exec_dw1);
>    @mx.inplace gpu_w -=dyn_learn_rate*exec_dw1.outputs[1];
> end

Or did you mean construct `gpu_w` with symbolic Variable ?I'm confused.

**Comment by r3tex** [comment]
I'm also getting an out of memory error in MXNet.jl on Windows (GeForce 670 2GB) using precisely pluskid's LeNet tutorial with mnist-data.jl:
```
julia> mx.fit(model, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)
INFO: Start training on [GPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
[12:34:51] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:241: 
[12:34:51] d:\chhong\mxnet\src\storage\./gpu_device_storage.h:39: 
Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory

```

**Comment by CXMA479** [comment]
⊙﹏⊙ .Ｉ always thought built-in commands would function well.
MXNet is useful for me,anyway,there are some other tricks to achieve.Just more time to develop.

**Comment by vchuravy** [comment]
@r3tex 2GB might be to little memory for that particular network. What batchsize are you using? 

@CXMA479 You seem to be trying to do something specific. Best to get familiar with the general usecase MXNet is designed for.

**Comment by r3tex** [comment]
@vchuravy the Julia version crashes with a batch size of 1. I just tried through R and it runs fine with a batch size of 100. Running on a GeForce 670 is about 2x faster than running on a 6-core i7-3930K.

**Comment by vchuravy** [comment]
@r3tex You are running this: https://github.com/dmlc/MXNet.jl/blob/bbe31513ade7cdf1db04ead6c7195d679e56d99e/examples/mnist/lenet.jl and you are running out of memory? Could you try the master version of MXNet.jl

Memory consumption (observed with nvidia-smi -l 1) is constant at `1866MiB`

**Comment by r3tex** [comment]
Yes, precisely that example. I wonder if the windows build I've put together is causing issues. It's not make-or-break now since the card is admittedly old. If the issue persists after upgrading to a newer card I'll follow up.

**Comment by sandeep-krishnamurthy** [comment]
I think this issue does not persist anymore. Please reopen this issue if you are still seeing OOM issue.

@piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
