### ISSUE TITLE
Installation missing at https://github.com/deepinsight/mxnet

### ISSUE THREAD

**Issue by keithbriggs** [apache/incubator-mxnet#19114]
. Installation

*click*

404 page not found :(

**Comment by szha** [comment]
Hi @keithbriggs. Thanks for reporting this. Could you provide the link to the webpage that has the broken link?

**Comment by keithbriggs** [comment]
In the issue title.

Another one: at https://mxnet.incubator.apache.org/versions/1.6/get_started/build_from_source, it says "Starting with MXNet 1.7, MXNet recommends using the cmake cross platform build tool", but at https://mxnet.incubator.apache.org/versions/1.6/get_started/download, the latest release is 1.6.0.


________________________________

**Comment by szha** [comment]
@keithbriggs thanks. The one in the title is a fork of mxnet by deepinsight (so @nttstar may be able to help you).
The 1.7 website update is ongoing in #19102 and will be made available soon.
