### ISSUE TITLE
PyPi 1.7.0 install fails

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#19132]
On Linux, PyPI installation of 1.7.0 not available.
Despite https://pypi.org/project/mxnet/1.7.0/ exists.
```
pip --version
pip 20.2.3 from /home/ubuntu/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
```

```
pip install mxnet==1.7.0
ERROR: Could not find a version that satisfies the requirement mxnet==1.7.0 (from versions: 0.9.5.post2, 0.10.0, 0.10.0.post2, 0.11.0, 0.12.0, 0.12.1, 1.0.0, 1.0.0.post0, 1.0.0.post1, 1.0.0.post2, 1.0.0.post3, 1.0.0.post4, 1.1.0, 1.1.0.post0, 1.2.0, 1.2.1, 1.2.1.post0, 1.2.1.post1, 1.3.0, 1.3.0.post0, 1.3.1, 1.4.0, 1.4.0.post0, 1.4.1, 1.5.0, 1.5.1, 1.5.1.post0, 1.6.0, 1.7.0.post1)
ERROR: No matching distribution found for mxnet==1.7.0
```

**Comment by ChaiBapchya** [comment]
Workaround was to install 1.7.0.post1
```
pip install mxnet==1.7.0.post1
```
It works. However, if PyPI website for mxnet shows a particular version, it should be installable.

**Comment by pengzhao-intel** [comment]
> Workaround was to install 1.7.0.post1
> 
> ```
> pip install mxnet==1.7.0.post1
> ```
> 
> It works. However, if PyPI website for mxnet shows a particular version, it should be installable.

Another workaround is `pip install mxnet`

**Comment by szha** [comment]
current doc says `pip install mxnet` for the CPU version which should work.
