### ISSUE TITLE
FindMKL.cmake small bugs

### ISSUE THREAD

**Issue by sfraczek** [apache/incubator-mxnet#19151]
## Description
1. `cmake/Modules/FindMKL.cmake` doesn't search `$HOME/intel` path, but only `/opt/intel`. I believe it could search both because if mkl is installed without sudo, it is installed in `$HOME/intel`.
2. `mklvars.sh` exports env variable `MKLROOT` therefore FindMKL should search in `ENV{MKLROOT}` instead of `ENV{MKL_ROOT}` because `MKL_ROOT` is cmake variable.
3. Unused cmake variables `INTEL_ROOT` `INTEL_RTL_ROOT` should be replaced with `MKL_ROOT`.

## To Reproduce
Run cmake after running source ../path/to/mklvars.sh or set environment variable MKLROOT manually and see that it doesn't find MKL properly.

**Comment by pengzhao-intel** [comment]
@anko-intel
