### ISSUE TITLE
[1.x] Test failure seen in recently introduced intgemm test

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#19197]
## Description
A test_contrib_intgemm.py:test_contrib_intgemm_prepare_data failure was seen in pipeline:
https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-19186/runs/3/nodes/293/steps/515/log/?start=0

Not sure if this repros the error, or if the error is also present on master:
```
MXNET_TEST_SEED=704110622 nosetests --verbose -s tests/python/unittest/test_contrib_intgemm.py:test_contrib_intgemm_prepare_data
```
Test was recently introduced into 1.x by backport PR https://github.com/apache/incubator-mxnet/pull/19099

@kpuatamazon ? 
FYI @samskalicky

**Comment by kpuatamazon** [comment]
I am able to reproduce.  Investigating.

**Comment by kpuatamazon** [comment]
Ugh sorry, at least it's a test issue rather than a code issue.  I've submitted PRs to fix in both branches.
