### ISSUE TITLE
Amalgamation

### ISSUE THREAD

**Issue by believeitmyway** [apache/incubator-mxnet#19193]
The amalgamation folder seems to disappear from the repo, is it no longer supported?  I want to minimize the dependency and convert it to a single file. Is there another way?

**Comment by szha** [comment]
Amalgamation is still available in [v1.x](https://github.com/apache/incubator-mxnet/tree/v1.x/amalgamation).

In terms of generating a single binary to link to that minimizes dependency, you could use `-DMXNET_BUILD_SHARED_LIBS=OFF` to build static library of mxnet with `.a` extension, link to it, and strip all symbols that weren't used. On linux, you can use `strip --strip-unneeded` on your final library so file for this purpose.

**Comment by believeitmyway** [comment]
Thank you so much.  I have another question.  The URL below states that we can also remove the dependency on BLAS.  Is there any procedure for that?

https://mxnet.apache.org/versions/1.7/api/faq/smart_device

**Comment by szha** [comment]
I think that comment may be outdated. BLAS functions include accelerated gemm which is quite essential to deep learning. I would recommend to always choose a BLAS library in any case.

**Comment by believeitmyway** [comment]
I understand that.  Thank you!
