### ISSUE TITLE
Dual license header issue

### ISSUE THREAD

**Issue by ciyongch** [apache/incubator-mxnet#19198]
## Description
This is to track the dual license header issue of file [cmake/Modules/FindJeMalloc.cmake](https://github.com/apache/incubator-mxnet/blob/master/cmake/Modules/FindJeMalloc.cmake) which mentioned in https://github.com/apache/incubator-mxnet/pull/18478.

**Comment by ciyongch** [comment]
@samskalicky not sure if you're aware of this issue, it's better to address this in 1.8.0, what do you think?

**Comment by samskalicky** [comment]
Hi @ciyongch thanks for pointing this out. It would be great to pull in this fix into 1.8 if it already exists. Is there a PR already or is someone working on it?

**Comment by ciyongch** [comment]
Hi @samskalicky , I don't think there's anyone working on this, as well as another one regarding pybind11 https://github.com/apache/incubator-mxnet/issues/15547, ping @szha to confirm and see if there's any other potential license issues for the release.

**Comment by szha** [comment]
After reviewing the cmake file, it seems ok to have the file under both licenses. The BSL license is under [category A](https://www.apache.org/legal/resolved.html#category-a) and is compatible with Apache License.
