### ISSUE TITLE
Unable to compile mxnet R package.

### ISSUE THREAD

**Issue by kstawiski** [apache/incubator-mxnet#19238]
## Description
Since few last commits, I'm having a problem with compiling and installing mxnet for R in Docker image.
Nothing changed in the command that previously worked.

### Error Message
```
make: R-package/Makefile: No such file or directory
make: *** No rule to make target 'R-package/Makefile'.  Stop.
```

It happens on both CPU and GPU-based version.

### Steps to reproduce
(Paste the commands you ran that produced the error.)

For CPU-based version:

```
/bin/sh -c pip install --upgrade cmake && cd / && git clone --recursive https://github.com/apache/incubator-mxnet.git && cd /incubator-mxnet && mkdir build && cd build && cmake -DUSE_CUDA=OFF -DUSE_MKL_IF_AVAILABLE=ON -DUSE_MKLDNN=OFF -DUSE_OPENMP=ON -DUSE_OPENCV=ON .. && make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas && make install && cp -a . .. && cp -a . ../lib && cd /incubator-mxnet/ && make -f R-package/Makefile rpkg
```

For GPU-based version:

```
RUN pip install --upgrade cmake && cd / && git clone --recursive https://github.com/apache/incubator-mxnet.git && cd /incubator-mxnet && mkdir build && cd build && cmake -DUSE_CUDA=ON -DUSE_MKL_IF_AVAILABLE=ON -DUSE_MKLDNN=OFF -DUSE_OPENMP=ON -DUSE_OPENCV=ON .. && make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas && make install && cp -a . .. && cp -a . ../lib && cd /incubator-mxnet/ && make -f R-package/Makefile rpkg
```

## What have you tried to solve it?

1. Check documentation on any updates about compiling R package - none found.

## Environment

Ubuntu-based docker images, Dockerfiles: https://github.com/kstawiski/miRNAselector/blob/master/Dockerfile.gpu and https://github.com/kstawiski/miRNAselector/blob/master/Dockerfile

**Comment by szha** [comment]
Hi @kstawiski, we have temporarily removed the R package from the master branch due to C-API changes. For now, please make sure that you use `git clone --recursive https://github.com/apache/incubator-mxnet.git -b v1.x` when checking out the code base.

**Comment by kstawiski** [comment]
Thank you @szha for the quick response. Closing the issue.
