### ISSUE TITLE
Java Binding API is broken

### ISSUE THREAD

**Issue by wangtieqiao** [apache/incubator-mxnet#19230]
## Description
the link provided below is broken, I can not find any instruction on how to install java binding ..

https://mxnet.apache.org/get_started/build_from_source#install-the-mxnet-package-for-java

**Comment by szha** [comment]
cc @lanking520

**Comment by lanking520** [comment]
@wangtieqiao here is the steps to follow:

1. Build from source for MXNet 1.x or grab released native file from pip wheel and place it to the `lib` folder.
2. cd scala-package and run `mvn install`, this should build the whole Scala/Java package. You can grab the package from there to use the Java bindings.

Another option is to use AWS maintained DeepJavaLibrary for MXNet Java support. You can follow the instruction: [load your mxnet model with DJL](http://docs.djl.ai/jupyter/load_mxnet_model.html).

**Comment by wangtieqiao** [comment]
hi @lanking520 Thanks for looking into this

**But I can not find** `scala-package` as you mentioned .... Below is the  directory after I pull from source, and follow instruction to run cmake for linux.cmake
`
.
├── 3rdparty
│   ├── ctc_include
│   ├── dlpack
│   ├── dmlc-core
│   ├── googletest
│   ├── mkldnn
│   ├── mshadow
│   ├── nvidia_cub
│   ├── onnx-tensorrt
│   ├── openmp
│   ├── ps-lite
│   └── tvm
├── benchmark
│   ├── __init__.py
│   ├── opperf
│   └── python
├── build
│   ├── 3rdparty
│   ├── bin
│   ├── cmake
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   ├── cmake_install.cmake
│   ├── CTestTestfile.cmake
│   ├── DartConfiguration.tcl
│   ├── _deps
│   ├── dummy.c
│   ├── im2rec
│   ├── lib
│   ├── libcustomop_lib.so
│   ├── libmxnet.so
│   ├── libpass_lib.so
│   ├── libsubgraph_lib.so
│   ├── libtransposecsr_lib.so
│   ├── libtransposerowsp_lib.so
│   ├── Makefile
│   ├── Testing
│   └── tests
├── cd
│   ├── img
│   ├── Jenkinsfile_cd_pipeline
│   ├── Jenkinsfile_release_job
│   ├── Jenkinsfile_utils.groovy
│   ├── mxnet_lib
│   ├── python
│   ├── README.md
│   └── utils
├── ci
│   ├── build.py
│   ├── build_windows.py
│   ├── dev_menu.py
│   ├── docker
│   ├── docker_login.py
│   ├── __init__.py
│   ├── jenkins
│   ├── Jenkinsfile_docker_cache
│   ├── Jenkinsfile_utils.groovy
│   ├── logging.conf
│   ├── other
│   ├── publish
│   ├── README.md
│   ├── requirements.txt
│   ├── safe_docker_run.py
│   ├── test_docker_login.py
│   ├── test_safe_docker_run.py
│   ├── util.py
│   └── windows
├── cmake
│   ├── BuildCythonModules.cmake
│   ├── BuildTVM.cmake
│   ├── ChooseBlas.cmake
│   ├── libmxnet.sym
│   ├── libmxnet.ver
│   ├── Modules
│   ├── upstream
│   └── Utils.cmake
├── CMakeLists.txt
├── CODE_OF_CONDUCT.md
├── CODEOWNERS
├── config
│   ├── darwin.cmake
│   ├── distribution
│   ├── linux.cmake
│   └── linux_gpu.cmake
├── config.cmake
├── conftest.py
├── contrib
│   └── tvmop
├── CONTRIBUTORS.md
├── DISCLAIMER-WIP
├── doap.rdf
├── docker
│   ├── Dockerfiles
│   ├── docker-python
│   ├── install
│   ├── README.md
│   ├── run.sh
│   └── tool.sh
├── docs
│   ├── cpp_docs
│   ├── python_docs
│   ├── README.md
│   ├── static_site
│   └── tutorial_utils
├── example
│   ├── adversary
│   ├── autoencoder
│   ├── automatic-mixed-precision
│   ├── bi-lstm-sort
│   ├── distributed_training
│   ├── distributed_training-horovod
│   ├── extensions
│   ├── gluon
│   ├── multi-task
│   ├── multi_threaded_inference
│   ├── MXNetTutorialTemplate.ipynb
│   ├── probability
│   ├── profiler
│   ├── README.md
│   ├── recommenders
│   ├── restricted-boltzmann-machine
│   └── rnn
├── include
│   ├── dlpack -> ../3rdparty/dlpack/include/dlpack
│   ├── dmlc -> ../3rdparty/dmlc-core/include/dmlc
│   ├── mkldnn
│   ├── mshadow -> ../3rdparty/mshadow/mshadow
│   ├── mxnet
│   └── nnvm -> ../3rdparty/tvm/nnvm/include/nnvm
├── KEYS
├── LICENSE
├── MKLDNN_README.md
├── NEWS.md
├── NOTICE
├── plugin
│   ├── opencv
│   ├── sframe
│   ├── torch
│   └── warpctc
├── pytest.ini
├── python
│   ├── mxnet
│   ├── mxnet.egg-info
│   ├── README.md
│   └── setup.py
├── README.md
├── readthedocs.yml
├── SECURITY.md
├── snap.python
├── src
│   ├── api
│   ├── base.cc
│   ├── c_api
│   ├── common
│   ├── engine
│   ├── imperative
│   ├── initialize.cc
│   ├── initialize.h
│   ├── io
│   ├── ir
│   ├── kvstore
│   ├── lang
│   ├── lib_api.cc
│   ├── libinfo.cc
│   ├── ndarray
│   ├── nnvm
│   ├── operator
│   ├── optimizer
│   ├── profiler
│   ├── resource.cc
│   ├── runtime
│   └── storage
├── tests
│   ├── CMakeLists.txt
│   ├── cpp
│   ├── nightly
│   ├── python
│   ├── README.md
│   ├── tutorials
│   └── utils
└── tools
    ├── bandwidth
    ├── cfn
    ├── dependencies
    ├── diagnose.py
    ├── flakiness_checker.py
    ├── im2rec.cc
    ├── im2rec.py
    ├── ipynb2md.py
    ├── kill-mxnet.py
    ├── launch.py
    ├── license_header.py
    ├── parse_log.py
    ├── pip
    ├── profile
    ├── rec2idx.py
    ├── staticbuild
    └── windowsbuild

113 directories, 85 files
`

And the steps I followed to build from source was:
after git clone the repository, then run following command so got the directory above
<pre>
 1975  cp config/linux.cmake config.cmake
 1976  mkdir build; cd build
 1977  cmake .. 
 1978  cmake --build . --parallel 12
</pre>

**Comment by szha** [comment]
@wangtieqiao it's available on v1.x in https://github.com/apache/incubator-mxnet/tree/v1.x/scala-package

**Comment by wangtieqiao** [comment]
ok, got it -- it is on v1.x branch. Thanks @szha
