### ISSUE TITLE
 Could not find a version

### ISSUE THREAD

**Issue by PrShi113** [apache/incubator-mxnet#19240]
After typing 
pip install mxnet-cu101==1.6.0

ERROR: Could not find a version that satisfies the requirement mxnet-cu101==1.6.0 (from versions: 1.5.0)
ERROR: No matching distribution found for mxnet-cu101==1.6.0

How can I install a 1.6.0 version???

**Comment by PrShi113** [comment]
Then I uninstalled mxnet 1.5.0, however I still cannot install 1.6.0 version by using 
pip install mxnet-cu101==1.6.0. Errors occurred...

**Comment by leezu** [comment]
Hi @PrShi113, you can see the available versions at https://pypi.org/project/mxnet-cu101/#history In particular, you may be interested in 1.6.0.post0
