### ISSUE TITLE
Gluon export changing params

### ISSUE THREAD

**Issue by samskalicky** [apache/incubator-mxnet#19354]
## Description
When exporting a model from Gluon, some param values can be modified:
https://github.com/apache/incubator-mxnet/blob/ce1e68260eb3cf9219ae4d59df8bdde7361802ec/python/mxnet/gluon/block.py#L1354
The `_reduce` function here actually performs a sum/division:
https://github.com/apache/incubator-mxnet/blob/ce1e68260eb3cf9219ae4d59df8bdde7361802ec/python/mxnet/gluon/parameter.py#L406

If the data type is floating point, then the resulting [IEEE FP standard calls for a rounding operation](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Representable_numbers,_conversion_and_rounding). Even though summing by 1 and dividing by 1 should result in the same value, it may be slightly altered. 

If specific binary data is encoded within a param, then this operation will modify that data and cause corruption. 

### Possible solution
I propose checking the length of the block, and if it is 1 then skipping the sum/divide operation.

**Comment by samskalicky** [comment]
This problem is compounded by the bug in:
https://github.com/apache/incubator-mxnet/blob/6729cf3bf4edd6837b0feb6417691ce2e00dbcee/src/c_api/c_api.cc#L1419
where its calling the `NDArray` constructor:
https://github.com/apache/incubator-mxnet/blob/v1.x/include/mxnet/ndarray.h#L95-L96
and its passing in the dtype to the 3rd argument which is `delay_alloc`.

**Comment by samskalicky** [comment]
It further compounds in Gluon where creating the new Parameter doesnt set the dtype explicitly:
https://github.com/apache/incubator-mxnet/blob/6729cf3bf4edd6837b0feb6417691ce2e00dbcee/python/mxnet/gluon/block.py#L1002-L1003
This leads to the default dtype `mx_real_t` which is float32:
https://github.com/apache/incubator-mxnet/blob/ce1e68260eb3cf9219ae4d59df8bdde7361802ec/python/mxnet/gluon/parameter.py#L106

**Comment by samskalicky** [comment]
FYI @leezu @Kh4L @mseth10 @rondogency

**Comment by szha** [comment]
@samskalicky thanks for the fix!
