### ISSUE TITLE
lars_multi_mp_sgd_update kernel used in MLPERF v0.7 not found in  v1.6 or v1.7

### ISSUE THREAD

**Issue by Eric-seu** [apache/incubator-mxnet#19367]
## Description
In the submission of mxnet in mlperf training v0.7 benchmark, mxnet used a optimizer kernel call "[lars_multi_mp_sgd_update](https://github.com/mlperf/training_results_v0.7/blob/3dbb53064a6b79354c68a6832414b6536fee1a75/NVIDIA/benchmarks/resnet/implementations/mxnet/common/fit.py#L47)" or "lars_multi_mp_sgd_mom_update".   

Mxnet used this optimizer and got great results in mlperf v0.7,  and I  would like to try it in my project.  
BUT i could not find this kernel in mxnet v1.6 or v1.7. 

### Error Message
![image](https://user-images.githubusercontent.com/73010366/96328544-cefffb80-1076-11eb-863e-f463b4ed936f.png)

## What have you tried to solve it?
i had tried with the master branches of v1.6 and v1.7

**Comment by ptrendx** [comment]
You can use `LARS` optimizer - it uses the same kernels as the MLPerf submission (they are named slightly differently - `                        preloaded_multi_mp_sgd_update`). The NVIDIA NGC MXNet container, which was used for that submission, had the LARS optimizer before the upstream and the names were changed as part of the upstreaming process.
