### ISSUE TITLE
Is there any tools or instructions of converting regular feature vector into recordio

### ISSUE THREAD

**Issue by tjuzhao111** [apache/incubator-mxnet#1937]
I have some numberical feature vectors ( about 130 miliion ) for a regression task. I construct a simple 3 layers MLP with a logiticOuput layer (FC with 128 units, FC 128 units, FC 64 units, FC 1 units, LogisticOutput). 
1. Is it a right layer combination?
2. I used the NDArrayIter with the original numpy array. However it looks like it wiil be more efficent and can save more memery if use a recordIO format. I just notice the tool of im2rec converting raw image into recordio. Is there any example or instructions for converting the common numberical feature vector into recordio?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
