### ISSUE TITLE
memory leak in Executor when inference in cpu !help!

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [apache/incubator-mxnet#19424]
![image](https://user-images.githubusercontent.com/46700201/97136982-94414600-178f-11eb-8da0-fa89c13b2135.png)

i have try only run
```
mxnet::cpp::NDArray data = GetDataBatch(src, faces)
```
it haven`t momery leak,,so i think the problem is not in here.
is my code wrong in use Executor?
thank you!

**Comment by bgawrych** [comment]
@ZHEQIUSHUI Can you provide more details like MXNet version, how you've built this package - also it would be helpful if you will post your net definition and input shapes

**Comment by ZHEQIUSHUI** [comment]
@bgawrych the mxnet version is v1.7.x lastest.build with mkl(no cuda),input shape is bitchsize*3*107*108

and you view the other issue that i have report?

issue https://github.com/apache/incubator-mxnet/issues/19430

**Comment by bgawrych** [comment]
@ZHEQIUSHUI Can you check with debugger stack trace when memory leak happen? I can't reproduce this issue without network definition. Are you sure that this loop with memcpy is right?

**Comment by ZHEQIUSHUI** [comment]
@bgawrych can I get your email address?I can send your the net Json file and my inference code(if your have free time).thank your so much.I can make sure there is not memory leak except this function.thank you so much!

**Comment by ZHEQIUSHUI** [comment]
@bgawrych i got the reason...because i use std::cout to log something....i am so sorry....thank you a lot!!!

**Comment by ZHEQIUSHUI** [comment]
@bgawrych the reason isn`t cout, i use the same code with v1.5.x,there is not memory leak,but v1.7.x.....

**Comment by ZHEQIUSHUI** [comment]
but the v1.5.x doesn`t compile with mkl....

**Comment by bgawrych** [comment]
@ZHEQIUSHUI You can create private repository on github with the code and give me an access to it. I will look at this

**Comment by ZHEQIUSHUI** [comment]
i have try the same code in cpu with the same version mxnet(v1.7.x),but i have compile two libmxnet([just only cpu] and [with mkl]),i make sure the problem is the mxnet with mkl!!my code have not memory leak!

this is only cpu version mxnet
![QQ录屏20201029084031 00_00_00-00_00_30](https://user-images.githubusercontent.com/46700201/97511638-8293b480-19c2-11eb-9ff7-f4cefe93a120.gif)



this is with 
![QQ录屏20201029083614 00_00_00-00_00_30](https://user-images.githubusercontent.com/46700201/97511468-203ab400-19c2-11eb-9e98-4e2a0f8ed92c.gif)
mkl

**Comment by pengzhao-intel** [comment]
@ZHEQIUSHUI thanks to reporting this issue and it's really important for us.  
Could you help provide a reproducer? Maybe a proxy model is fine which will accelerate our debugging progress?

**Comment by ZHEQIUSHUI** [comment]
@pengzhao-intel of course.what do you need?

**Comment by bgawrych** [comment]
@ZHEQIUSHUI we need minimal part of your model that causes this memory leak, currently we don't even know which operators you're using

And as I said before, if you're still ok with that:

> @ZHEQIUSHUI You can create private repository on github with the code and give me an access to it. I will look at this

**Comment by ZHEQIUSHUI** [comment]
hey @bgawrych @pengzhao-intel i just create a new  repository and invited you to it,you can come if you need the model json file.

**Comment by ZHEQIUSHUI** [comment]
i closed this issue

**Comment by bgawrych** [comment]
@ZHEQIUSHUI Would you mind to share also inference code in github repository?
