### ISSUE TITLE
New [Python/NDArray(MXRtc)] error: identifier "FLT_MAX" is undefined

### ISSUE THREAD

**Issue by jonbakerfish** [apache/incubator-mxnet#1943]
I follow the [tutorial on Python/NDArray(MXRtc)](http://mxnet.readthedocs.org/en/latest/how_to/new_op.html#python-ndarray-mxrtc) and create a new layer. During training, it has the following errors:

```
mxrtc.cc:128: Check failed: (compile_res) == (NVRTC_SUCCESS) xx.cu error: identifier "FLT_MAX" is undefined
```

I noticed that somewhere in my rtc code use `FLT_MAX` which are defined in `<float.h>`. How can I include it via the python interface?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
