### ISSUE TITLE
[BUG] [TUTORIAL]Mxnet2.0 crashcourse was not reflecting on website

### ISSUE THREAD

**Issue by vidyaravipati** [apache/incubator-mxnet#19467]
## Description
(A clear and concise description of what the bug is.)
The new crash course material which is merged as part of [PR](https://github.com/apache/incubator-mxnet/pull/19345)  is not being reflected on the [website](https://mxnet.apache.org/versions/1.6/api/python/docs/tutorials/getting-started/crash-course/index.html)

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=100` before running your script.)
Crash course website(https://mxnet.apache.org/versions/1.6/api/python/docs/tutorials/getting-started/crash-course/index.html) still not showing the latest crash course material

</details>

**Comment by Zha0q1** [comment]
There was a minor git identity issue in our publish pipeline. It should be resolved now.
https://mxnet.apache.org/versions/master/api/python/docs/tutorials/getting-started/crash-course/index.html

**Comment by leezu** [comment]
Thank you @Zha0q1!
