### ISSUE TITLE
cudaMalloc retry failed

### ISSUE THREAD

**Issue by seekFire** [apache/incubator-mxnet#19499]
## Description
Error occurs in logging stage:
```
logger.info("Training: [epoch: %d, steps: %d, learning_rate: %.2e, batch_loss: %.4f, batch_time: %.2fs]"
                        % (i, step_num, trainer.learning_rate, batch_loss.mean().asscalar(), cost_batch))
```

### Error Message
```
mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/storage/./pooled_storage_manager.h", line 161
MXNetError: cudaMalloc retry failed: out of memory
```

## Environment
Python3.7
mxnet-cu102==1.7.0

So could you please help me with these questions?

**Comment by szha** [comment]
Hi @seekFire. Because MXNet execution is asynchronous, the OOM error likely happened earlier. I'd suggest reducing model size or batch size to make it fit in your current GPU. If you have reason to believe that the current setting should fit in your GPU memory, it would be helpful if you elaborate on that so that I can take a closer look.

**Comment by seekFire** [comment]
@szha Thank you for your suggestion! When I turn down the batch size to 2 on one GPU it works ok, I'm just surprised that the batch size is so low when training with HRNet-W18 for segmentation... 
BTW, when I trained the model with one GPU, the batch size can not even be set to 4, but when I trained with 4 GPUs, it will works fine with batch_size = 4, I just wonder what's the difference between these two situations?

**Comment by seekFire** [comment]
@szha Another question is, the loss value not only doesn't decrease, but also changes back and forth between several fixed values during training, what do you think is the possible reason for this?

**Comment by szha** [comment]
> when I trained with 4 GPUs, it will works fine with batch_size = 4

Is this a per-GPU batch size? I imagine it has to do with the input image sizes.

**Comment by seekFire** [comment]
@szha Yes, you're right, and the input image size is 512*512

**Comment by seekFire** [comment]
@szha 
Well, I think this question is not important for me, as long as the model can be trained with at least one image per batch...BTW, when I run some script like below under the shell environment, it works OK:
```
>>> import mxnet as mx
>>> x = mx.nd.ones((2, 3, 4, 5))
>>> y = x.transpose((0, 3, 1, 2)).reshape(0, -3, -1)
>>> y.shape    # (2, 15, 4)
```
But the reshape operation in my custom metric function will generate error during training:
`labels = labels.transpose((0, 2, 3, 1)).reshape(0, -3, -1).argmax(-1)`

The error message shown as below:
`ValueError: can only specify one unknown dimension`

So what do you think about the cause?

**Comment by leezu** [comment]
Have you enabled the numpy compatible mode? `use_np` or `set_np`?

**Comment by seekFire** [comment]
@leezu 
No, I don't. but the type of the tensor manipulated is **mxnet.ndarray.ndarray.NDArray** rather than **numpy.ndarray**, the special values like 0, -1, -3 are defined in the function **reshape** of **mxnet.ndarray.ndarray.NDArray**, and when I used the older version of mxnet(1.5.0), there has no such error... So I guess whether or not it is a bug

**Comment by seekFire** [comment]
@leezu 
I tried your suggestion by adding the script:
`mx.npx.set_np()`
But it didn't work and new error occurs...

**Comment by seekFire** [comment]
@leezu 
I'm doing the semantic segmentation task, and because of using sparse label, the shape of label needs to be converted, from (n, c, h, w) to (n, h*w), and the shape of prediction also needs to be converted from (n, c, h, w) to (n, h*w, c)
I just wonder if it is because I set the **last_batch** of dataloader to '**keep**', so the batch size is not fixed, and the error occured...

**Comment by seekFire** [comment]
@leezu 
I think I may find out the error reason: when I use the class **mx.metric.CustomMetric** to wrap my custom metric function, the type of tensor in this function will convert from **mxnet.ndarray.ndarray.NDArray** to **numpy.ndarray**, so it will generate this error. The validation process is as follows, same script as above except using **numpy** to replace **mxnet.ndarray**:

```
>>> import numpy as np
>>> x = np.ones((2, 3, 4, 5))
>>> y = x.transpose((0, 3, 1, 2)).reshape(0, -3, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: can only specify one unknown dimension
```
The error is same as the mentioned above.
