### ISSUE TITLE
[Bug] Graph optimization bug

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#19524]
## Description

The recent merged https://github.com/apache/incubator-mxnet/pull/18690 has broken the CI of GluonNLP. The tests that are related to relative positional embedding which contains the unique operator. See https://github.com/dmlc/gluon-nlp/pull/1432/checks?check_run_id=1391543133 for the error message.

Need some help in investigating the issue.

@mseth10 @sandeep-krishnamurthy @szha @leezu

**Comment by mseth10** [comment]
Thanks for reporting the issue @sxjscience . This issue happens during training when the model is hybridized. It is a known bug #18823 with MXNet that we are currently working on. Meanwhile, what we can do is disable the graph partitioning by default. Will create a PR shortly.

**Comment by szha** [comment]
keeping this open for now to make sure the case is tested when actual fix is added.

**Comment by sxjscience** [comment]
@szha Would it be a 2.0-release issue?

**Comment by mseth10** [comment]
Fixed by #19614
