### ISSUE TITLE
pip install mxnet-cu102==1.6.0 error 官网

### ISSUE THREAD

**Issue by gengyanlei** [apache/incubator-mxnet#19548]
![image](https://user-images.githubusercontent.com/22360785/99338987-40bea580-28c0-11eb-8efc-1a0438531f14.png)

**Comment by Zha0q1** [comment]
would you paste the error message too?

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/99339430-21744800-28c1-11eb-8bb9-df1f2d0bb161.png)
我是觉得官网尽量不要犯这种低级错误！
