### ISSUE TITLE
Can't use mxnet with GPU in Windows Server 2016

### ISSUE THREAD

**Issue by normalclone** [apache/incubator-mxnet#19546]
## Description
I'm trying to run mxnet-cu101 in my windows server 2016 but it return some weird error

## What I had installed
`Cuda Toolkit 10.1`
`Windows Server 2016 x64`
`Python 3.7 x64`
newest `mxnet-cu101`

### Error Message
My env vars:
`CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1`
`CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1`
`CUDA_VISIBLE_DEVICES=0`
`USE_CUDA=1`

My error message
`  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\insightface\__init__.py", line 9, in <module>`
    `import mxnet as mx`
 ` File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\__init__.py", line 24, in <module>`
    `from .context import Context, current_context, cpu, gpu, cpu_pinned`
 ` File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\context.py", line 24, in <module>`
   ` from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\base.py", line 213, in <module>`
    `_LIB = _load_lib()`
  `File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\base.py", line 204, in _load_lib`
   ` lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)`
  `File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)`
`OSError: [WinError 126] The specified module could not be found`

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.Just `import mxnet`

## What I have tried
1. Search the problem in google: Some forum such as StackOverflow said this happen because of incompatibility between x86 and x64 bit mode, I tried to re-install all soft in x64 bitmode but it still return this above error message
2. Run mxnet in CPU: It run okay, but it's not what I want :(

**Comment by leezu** [comment]
It can also mean that the `libmxnet.dll` has a dependency on another dll which can't be found at the time of opening `libmxnet.dll`.

**Comment by normalclone** [comment]
> It can also mean that the `libmxnet.dll` has a dependency on another dll which can't be found at the time of opening `libmxnet.dll`.

Can u suggest me how to fix it! Thanks

**Comment by leezu** [comment]
cc @yajiedesign
