### ISSUE TITLE
No matching distribution found for mxnet==1.7.0.post1

### ISSUE THREAD

**Issue by StevenJokess** [apache/incubator-mxnet#19594]
## Description
(A clear and concise description of what the bug is.)

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=100` before running your script.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
![image](https://user-images.githubusercontent.com/71307974/100420472-7eda7700-30c1-11eb-87e6-a3bf359e09ce.png)

2. ![image](https://user-images.githubusercontent.com/71307974/100420202-fb208a80-30c0-11eb-9427-6cce57be7c15.png)

## What have you tried to solve it?

1. went to https://pypi.org/project/mxnet/#history , but there isn't any clue to download it correctly.
2. https://mxnet.apache.org/versions/1.7.0/get_started?platform=windows&language=python&processor=cpu&environ=pip&

## Environment

***We recommend using our script for collecting the diagnostic information with the following command***
`curl --retry 10 -s https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py | python3`

<details>
<summary>Environment Information</summary>

```
# Paste the diagnose.py command output here
```

</details>
How to download mxnet==1.7.0.post1?

**Comment by bartekkuncer** [comment]
Reproduced the issue.

**Comment by szha** [comment]
I think the problem was that the windows pip package for mxnet has become too large to publish on PyPI.

**Comment by bartekkuncer** [comment]
@szha I understand. I tried looking for this package but only found mxnet==1.7.0 (not 1.7.0.post1) for windows. Is this package (1.7.0.post1 for win10) available anywhere?

**Comment by bartekkuncer** [comment]
@StevenJokess Try this package: https://repo.mxnet.io/dist/python/cpu/mxnet-1.7.0-py2.py3-none-win_amd64.whl. Please let me know if it works for you.

**Comment by StevenJokess** [comment]
@bartekkuncer Where did you find this package?

**Comment by bartekkuncer** [comment]
@StevenJokess On internal CI page. Does it work? :)

**Comment by StevenJokess** [comment]
![image](https://user-images.githubusercontent.com/71307974/100626636-0abdfe80-3361-11eb-9e23-f2a8e7bed010.png)
Thanks.
How to find it next time? Or another wheel?

**Comment by bartekkuncer** [comment]
> How to find it next time? Or another wheel?
If the package will not decrease in size for future releases I believe it will be hard to publish them on PyPl.
@szha Is there any other public channel to get the win10 version of 1.7.0 and other mxnet release packages?

**Comment by szha** [comment]
Not that I'm aware of. @yajiedesign was looking into custom compression that may help this, though I think a more reliable way forward is for NVIDIA to publish these dependencies as a separate package that we can depend on.

Let's track this in #18793 which was intended for tracking CD automation for windows.

**Comment by bartekkuncer** [comment]
@StevenJokess I believe as of now there is no way to find those packages for windows on your own. You can always try building mxnet from source to have recent versions: https://mxnet.apache.org/versions/1.7.0/get_started/build_from_source.

**Comment by rogerdettloff** [comment]
I would also like to pip install mxnet==1.7.0 on windows.
@szha How sure are you about the size issue mentioned above?  I noticed that two other mxnet whl files (for macos and linux) are already on PyPi and they are much larger than the one that @bartekkuncer helpfully referenced on Monday https://github.com/apache/incubator-mxnet/issues/19594#issuecomment-735826843 .  That whl file was only about 17MB.  The macos and linux whl files are 30MB and 55MB.
![image](https://user-images.githubusercontent.com/6138503/101098299-88f3ee00-3577-11eb-9c45-1ff83b13a8b3.png)


I wonder if someone could again try to send the Windows whl file to PyPi?  It would be a big help to me. Thanks!

**Comment by szha** [comment]
the windows version should be available on pypi now

**Comment by dmteams** [comment]
hi, same problem here
![Capture](https://user-images.githubusercontent.com/75791502/101986456-3361c480-3c8e-11eb-95f2-50289e170d04.JPG)

I tried to activate the package of @bartekkuncer but not working either... 
![Capture2](https://user-images.githubusercontent.com/75791502/101986580-e9c5a980-3c8e-11eb-81f6-eea84ddab3cd.JPG)

can anyone help me?

**Comment by szha** [comment]
@dmteams what you have seems to be a different problem where compilation for numpy failed. you can try to first install numpy directly (to hopefully pick up pre-built binary instead of building from source) and then install mxnet.

**Comment by bartekkuncer** [comment]
@dmteams I see that the numpy package was taken from cache. It is possible that there were some problems during download and therefore it does not work now. You might want to try `pip install --no-cache-dir mxnet` which will ignore cached libs. Please let me know if it helps.

If it goes to missing environment, you have to create one first to be able to activate it. I believe you do not need it to install mxnet with pip.

**Comment by dmteams** [comment]
I tried to uninstall/reinstall numpy successfully, then try both `pip install mxnet` and `pip install --no-cache-dir mxnet` but I still have the same problem. I really do not understand... I finally installed TensorFlow that seems working just fine... Thank you anyway guys!
