### ISSUE TITLE
lower GPU speed on Windows

### ISSUE THREAD

**Issue by jennyzhang0215** [apache/incubator-mxnet#1961]
My training speed of cifar10 is about 500 samples/sec

![image](https://cloud.githubusercontent.com/assets/7044477/14806305/5d82ff4c-0ba4-11e6-9c4d-a1873dd4e0de.png)

However, my friend's speed is about twice faster than mine, around 1000 samples/sec

My GPU is TitanX, CUDA7.5 Cudnn v4.  I'm quite curious about this issue.

**Comment by CharlesMei** [comment]
Maybe the reason is that only cudnn v3 is supported

**Comment by CharlesMei** [comment]
@jennyzhang0215 Maybe the reason is that only cudnn v3 is supported
