### ISSUE TITLE
Edge pipeline segmentation fault

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#19630]
## Description
tests/python/unittest/test_engine.py

## Occurrences
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-19624/2/pipeline#step-276-log-165

**Comment by szha** [comment]
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-19624/4/pipeline/

**Comment by leezu** [comment]
You may skip the test to improve CI stability

**Comment by leezu** [comment]
The segmentation fault should be unrelated to test_engine. I'm updating the title.

**Comment by Zha0q1** [comment]
I will look into this today. Seems to be affecting many prs

**Comment by Zha0q1** [comment]
@josephevans helped launched a bunch of new worker machines and edge should be able to pass now. I restarted the edge pipeline on a few of the recent prs that were previously blocked

**Comment by leezu** [comment]
Thank you @Zha0q1 @josephevans
