### ISSUE TITLE
infer_shape error  using Function Inception7B  of symbol_inception-v3.py for special input size

### ISSUE THREAD

**Issue by xzqjack** [apache/incubator-mxnet#1967]
I tried to reimplement "deepDream" in mxnet-python and succeed in model vgg16  and model vgg19 .
But infer_shape error happened when i reused the code to _symbol_inception-v3.py_.  By testing, i found that concate op failed inFunction Inception7B when the input_size is (1,288,70,126). The reason is the shape difference between  pooling outputs(stride=2) and convolution (stride=2) to the same input shape.
The following code would reproduce the error

```
import mxnet as mx
def Conv(data, num_filter, kernel=(1, 1), stride=(1, 1), pad=(0, 0), name=None, suffix=''):
    conv = mx.sym.Convolution(data=data, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, no_bias=True, name='%s%s_conv2d' %(name, suffix))
    bn = mx.sym.BatchNorm(data=conv, name='%s%s_batchnorm' %(name, suffix), fix_gamma=True)
    act = mx.sym.Activation(data=bn, act_type='relu', name='%s%s_relu' %(name, suffix))
    return act
input_size = (1,288,70,126)
num_3x3=384
num_d3x3_red=64
num_d3x3_1=96
num_d3x3_2=96
pool="max",
name="mixed_3"
data = mx.symbol.Variable(name="data")
tower_3x3 = Conv(data, num_3x3, kernel=(3, 3), pad=(0, 0), stride=(2, 2), name=('%s_conv' % name))
tower_d3x3 = Conv(data, num_d3x3_red, name=('%s_tower' % name), suffix='_conv')
tower_d3x3 = Conv(tower_d3x3, num_d3x3_1, kernel=(3, 3), pad=(1, 1), stride=(1, 1), name=('%s_tower' % name), suffix='_conv_1')
tower_d3x3 = Conv(tower_d3x3, num_d3x3_2, kernel=(3, 3), pad=(0, 0), stride=(2, 2), name=('%s_tower' % name), suffix='_conv_2')
pooling = mx.symbol.Pooling(data=data, kernel=(3, 3), stride=(2, 2), pad=(0,0), pool_type="max", name=('max_pool_%s_pool' % name))
concate = mx.sym.Concat(*[tower_3x3, tower_d3x3, pooling], name='ch_concat_%s_chconcat' % name)

out =mx.symbol.Group([tower_3x3, tower_d3x3, pooling,concate])
out_name = out.list_outputs()
arg_shapes, output_shapes, aux_shapes = out.infer_shape(data=input_size)
for i in xrange(len(out_name)):
    print 'out_name-',out_name[i],'  output_shape-',output_shapes[i]
```

If you remove 'concate' out of group list, you will find the shape of tower_3x3, tower_d3x3, pooling is different, which is why 'Concat' op failed.
Of cource, i can set the pad=(1,1) to ensure the shape same this time. But i'm afraid that  the code might fail with another special input_size. 
So how to set the parameters of convolution layer to ensure the output shape always same as of  pooling for arbitrary input size.
Any hints will be appreciated!

**Comment by mavenlin** [comment]
@tqchen could be the pooling op, rounding of the infershape makes it fail. 
The same thing happens to strided convolution when it can't be divided by 2. As long as the behavior is consistent in pooling and convolution, it should work. (Unfortunately we fail to do this).

**Comment by winstywang** [comment]
Yes, our infer shape in pooling is somewhat tricky.

**Comment by winstywang** [comment]
Yes, our infer shape in pooling is somewhat tricky.

**Comment by winstywang** [comment]
Yes, our infer shape in pooling is somewhat tricky.

**Comment by piiswrong** [comment]
We should fix this soon. Shouldn't cause too much compatibility problem since most people use even input size. Variable size networks are mostly fully convolutional.

**Comment by winstywang** [comment]
@piiswrong At least, it will break the pre-trained Inception model.

**Comment by piiswrong** [comment]
The pretrained model is converted from google's model right? How did they do rounding?

**Comment by xzqjack** [comment]
Hi, @tqchen @winstywang @piiswrong @mavenlin, is this problem sovled about round operation in convolution and pool?
