### ISSUE TITLE
Segmentation Fault in mxnet.ndarray.split_v2

### ISSUE THREAD

**Issue by DNXie** [apache/incubator-mxnet#19684]
## Description
Segmentation fault in `mxnet.ndarray.split_v2`

### Error Message
~~~python
Segmentation fault: 11
~~~

## To Reproduce
~~~python
import mxnet
import numpy as np
ary=mxnet.nd.array(np.random.rand(0,1))
mxnet.ndarray.split_v2(ary=ary, indices_or_sections=-1)
~~~

## Environment

OS: ubuntu 18.04
Python: 3.7.6
pip: 20.0.2
numpy: 1.18.5
mxnet: 1.6.0

**Comment by leezu** [comment]
`0` shapes are unsupported in the `mxnet.nd` interface. Please update to MXNet 2 and use `mxnet.np` (or use the experimental `mxnet.np` in mxnet 1.x versions).

I'm closing the issue as it's unsupported.

**Comment by leezu** [comment]
You can refer to https://github.com/apache/incubator-mxnet/issues/14253 for more information
