### ISSUE TITLE
Probability distirbutions

### ISSUE THREAD

**Issue by dibgerge** [apache/incubator-mxnet#19700]
## Description

For probabilistic modeling, pytorch has the `distributions` module, and tensorflow has the `tensorflow_probability` package. I haven't seen something similar for MXNet. The closest I've seen is `GluonTS`, but this more domain specific for forecasting. 

Is this to be considered the official MxNet probability package?

**Comment by szha** [comment]
GluonTS certainly has plenty of distributions offerings. @xidulu and @szhengac also made the gluon.probability module for Gluon 2.0 (#18403, discussion in #17240), though this is not yet available in mxnet 1.x releases.

**Comment by dibgerge** [comment]
Great news! Thank you!
