### ISSUE TITLE
How to do distributed training ?

### ISSUE THREAD

**Issue by kandycs** [apache/incubator-mxnet#1971]
Hi, I am trying to setup mxnet with 2 nodes. 
I have successfully compiled the code with KV_STORE, and USE_HDFS. 
But I met some problem  when running the example code using 2 nodes.
1. When I try to run the train_mnist.py following the instruction in tutorial, it seems the code hangs there with no progress: 
   `>>../local/mxnet/tools/launch.py -n2 -H hosts --sync-dst-dir /tmp/mxnet python train_mnist.py --kv-store dist_sync`
   `Output:
   2016-04-26 17:23:51,776 INFO rsync /home/cchen/train/ -> 143.215.131.65:/tmp/mxnet
   2016-04-26 17:23:51,921 INFO rsync /home/cchen/train/ -> 143.215.131.185:/tmp/mxnet
   `
2. How to use HDFS ? 
   I put the training data under the HDFS file system with the path as /user/cchen/mnist
   and tried to access it with `python train_mnist.py --data-dir hfs://mnist`.
   mxnet reports `mxnet.base.MXNetError: [16:34:52] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration`. So what is the correct way to use HDFS ?

**Comment by mli** [comment]
can you change `-n2` to `-n 2` and try again?

is `hfs://mnist` the right dhfs right path?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
