### ISSUE TITLE
can't install mxnet package

### ISSUE THREAD

**Issue by izzitrin9** [apache/incubator-mxnet#19716]
## Description
trying to install mxnet on Windows 10 using pip install mxnet==1.7.0.post1
, keep getting error message 

### Error Message

 ERROR: Command errored out with exit status 1:
   command: 'C:\Users\zhang\miniconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zhang\\AppData\\Local\\Temp\\pip-install-gbe7d_2e\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\zhang\\AppData\\Local\\Temp\\pip-install-gbe7d_2e\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\zhang\AppData\Local\Temp\pip-wheel-v5qdsit8'
       cwd: C:\Users\zhang\AppData\Local\Temp\pip-install-gbe7d_2e\numpy\
  Complete output (264 lines):
  Running from numpy source directory.
  C:\Users\zhang\AppData\Local\Temp\pip-install-gbe7d_2e\numpy\numpy\distutils\misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\zhang\\miniconda\\lib', 'C:\\', 'C:\\Users\\zhang\\miniconda\\libs']
    NOT AVAILABLE

  blis_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blis not found in ['C:\\Users\\zhang\\miniconda\\lib', 'C:\\', 'C:\\Users\\zhang\\miniconda\\libs']

**Comment by dai-ichiro** [comment]
You need C compiler.
For example, install Visual Studio 2019 community, and then install mxnet.
