### ISSUE TITLE
Unable to disable MXNET_CUDNN_AUTOTUNE_DEFAULT 

### ISSUE THREAD

**Issue by cyrusbehr** [apache/incubator-mxnet#19729]
When I run GPU inference, I get the following message:
```
[21:47:34] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
```

This significantly slows things down as tuning can take some time, and is an issue when I have variable input sizes (as tuning can occur for every image). I therefore want to disable tuning. 

If I run `export MXNET_CUDNN_AUTOTUNE_DEFAULT=0` then re-run my script, it makes no difference. The message is still printed, and auto tuning is still performed. Why is the environment variable not being used?

I am building mxnet release 1.6.0 from source, using the following cmake flags:

```
  cmake\
 -DBLAS=open\
 -DUSE_CUDA=ON\
 -DUSE_CUDNN=ON\
 -DMXNET_CUDA_ARCH="6.0;6.1;7.0;7.5"\
 -DENABLE_CUDA_RTC=OFF\
 -DCMAKE_BUILD_TYPE=Release\
 -DUSE_F16C=OFF\
 -GNinja\
 -DUSE_LAPACK=OFF\
 -DUSE_LAPACK=OFF\
 -DUSE_JEMALLOC=OFF\
 -DUSE_CPP_PACKAGE=ON\
 -DUSE_SIGNAL_HANDLER=OFF\
 -DUSE_OPENCV=OFF\
 -DUSE_MKL_IF_AVAILABLE=OFF\
 -DUSE_MKLDNN=OFF\
 -DBUILD_CPP_EXAMPLES=OFF\
 -DCMAKE_INSTALL_PREFIX=./packaged\
 ..
```

Using 18.04 and Cuda 10.1.

**Comment by wkcn** [comment]
Could you please try to add the following code in the head of your script?
```python
import os
os.environ['MXNET_CUDNN_AUTOTUNE_DEFAULT'] = '0'
```

**Comment by cyrusbehr** [comment]
Adding that doesn't change anything for me.

**Comment by DickJC123** [comment]
Is it possible that in your model the Convolutions have set the cudnn_tune parameter, e.g. mx.sym.Convolution(...,cudnn_tune=1)?  This would take precedence over the environment variable, which supplies the default setting.

**Comment by cyrusbehr** [comment]
I inspected the model json file, and saw the following in the json file:
`"cudnn_tune": "limited_workspace", ` 

So it looks like `cudnn_tune` needs to be set to off or None.
