### ISSUE TITLE
Trying to build MXNET with MSVC 2019 under windows 10 under CMAKE GUI

### ISSUE THREAD

**Issue by jbensabat** [apache/incubator-mxnet#19783]
Hello 
I am trying to build a MSVC 2019 X64  using CMAKE GUI
the configuration goes fine (Although does not recognize GoogleTest)
I get 

Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMAKE_CROSSCOMPILING FALSE
**_CMAKE_HOST_SYSTEM_PROCESSOR AMD64
CMAKE_SYSTEM_PROCESSOR AMD64_**
CMAKE_SYSTEM_NAME Windows
CMake version '3.19.3' using generator 'Visual Studio 16 2019'
Found OpenBLAS libraries: C:/software/openblas/library/debug/lib/openblas.lib
Found OpenBLAS include: C:/software/openblas/library/debug/include
After choosing blas, linking to C:/software/openblas/library/debug/lib/openblas.lib
OpenCV Disabled
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
USE_LAPACK is ON
CMake Warning (dev) at 3rdparty/googletest/googletest/CMakeLists.txt:13 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'gtest_force_shared_crt'.
This warning is for project developers.  Use -Wno-dev to suppress it.

Found Python: C:/miniconda3/python.exe (found version "3.8.5") found components: Interpreter 
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found GTest: gtest  
Using 64-bit integer for tensor size
Found Python3: C:/miniconda3/python.exe (found version "3.8.5") found components: Interpreter 
CMake Warning at CMakeLists.txt:933 (message):
  OpenCV_VERSION_MAJOR: , version 3 with imgcodecs is required for im2rec,
  im2rec will not be available

Google Test not found
Configuring done
CMake Error at CMakeLists.txt:547 (add_library):
  No SOURCES given to target: nnvm

When I try to create the solution I get an error but no indication
it seems to me that it defines my computer as AMD64 while it is not 
any help would really be welcome
best
jac

**Comment by leezu** [comment]
You forgot to initialize 3rdparty subdirector. Run `git submodule update --init --recursive`

**Comment by jbensabat** [comment]
could you be more explicit please
thanks 
jac

**Comment by leezu** [comment]
If you have a terminal, run `git submodule update --init --recursive` inside mxnet dir. If you don't know how to do that, I suggest you search on the internet how to do it with MSVC

**Comment by leezu** [comment]
I suspect that you forgot to initialize the git 3rdparty submodules. That's why cmake doesn't find all components.

**Comment by jbensabat** [comment]
thanks 
i downloaded the code from the site (zip file)
I then cloned using git and updated and now I can build the lib
thanks
