### ISSUE TITLE
[TEST] [MAC] test_gluon_rnn.test_rnn_layers_fp16 is not skipped when using `nose`

### ISSUE THREAD

**Issue by r3stl355** [apache/incubator-mxnet#19790]
## Description
Test `test_gluon_rnn.test_rnn_layers_fp16` is currently attributed with `@pytest.mark.skipif(mx.context.num_gpus() == 0, reason="RNN FP16 only implemented for GPU for now")` but this is ignored if `nose` is used to run tests resulting in failed test. Documentation shows most of the test being executed using `nose`.

## Occurrences
Occurs on Mac but could equally happen in other environments without GPU. Currently only spotted in `test_gluon_rnn.test_rnn_layers_fp16` but could exist in other tests

## Solution

Replace with `@unittest.skipIf(mx.context.num_gpus() == 0, reason="RNN FP16 only implemented for GPU for now")` which works both for `nose` and `pytest`

**Comment by r3stl355** [comment]
I think I'm a bit lost here. Different places show running tests either using `nose` or `pytest`. I now vaguely recall seeing something that says you'll be standardising on `pytest`, is that right?

**Comment by szha** [comment]
@r3stl355 thanks for pointing out the issue. We switched to pytest for better support, extension, and maintenance, so the nose-related instructions are outdated. The most up-to-date development guide can be found in https://mxnet.apache.org/versions/master/community/code_guide#testing

I fixed these three wiki pages with references to nosetests:
https://cwiki.apache.org/confluence/display/MXNET/Fixing+Flaky+Tests
https://cwiki.apache.org/confluence/display/MXNET/Development+Process
https://cwiki.apache.org/confluence/display/MXNET/MXNet+Developer+Setup+on+Mac

**Comment by r3stl355** [comment]
@szha  thank you for clarifying this. Part of that https://mxnet.apache.org/versions/master/community/code_guide#testing is actually my own contribution :). 

If I may ask, (or I can move this to a different issue), what's the procedure for making changes to those wiki page (https://cwiki.apache.org/confluence/display/MXNET/MXNet+Developer+Setup+on+Mac would benefit from a small change regarding the alternative parameters to pass to `cmake`. e.g. on my Catalina Mac I need to use `CC=clang CXX=clang++ ...`, using exact version of `clang` doesn't work). 

Also, related, there is this page which is currently mostly empty and does not have `latest` in the dropdown, is it possible to edit it? I could add instructions for Mac and EC2 there. Not sure if adding `latest` to that drop-down would be appropriate.

**Comment by leezu** [comment]
@r3stl355 you are welcome to edit the pages. Have you tried if you can edit it?
