### ISSUE TITLE
Shape of Pred array in FCN-XS

### ISSUE THREAD

**Issue by Viswa14** [apache/incubator-mxnet#1979]
@tornadomeet @piiswrong  : Hello, I have a doubt in https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/solver.py#L87-L90 . From My Understanding, if PRED array is output from softmax for an image of size(512,512) and 2 classes in segmentation task, the PRED array should be of shape (1,262144) with each pixel having the value of Class 0 or Class 1 Exactly as the Label Image? but here the shape if PRED array in (1,2,512,512) then how does it sync with Segmentation or the use of Softmax(multi_output=True). Can you correct me if my understanding is wrong ?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
