### ISSUE TITLE
MXNET_USE_SAFE_ACCUMULATION env var operation

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#19805]
## Description
Maybe I'm missing something, but is the handling of the MXNET_USE_SAFE_ACCUMULATION variable in LayerNorm backwards (i.e. setting the variable true turns off safe accumulation)?

https://github.com/apache/incubator-mxnet/blob/3122423f3118f5ad2e278eeae97fc5a19c1feef1/src/operator/nn/layer_norm-inl.h#L124-L137

https://github.com/apache/incubator-mxnet/blob/3122423f3118f5ad2e278eeae97fc5a19c1feef1/src/operator/tensor/broadcast_reduce-inl.h#L391-L413

Tagging some that have worked or referred to this code: @sxjscience @leezu

**Comment by sxjscience** [comment]
@DickJC123 Thanks for pointing this out. It's a bug in the general case of LayerNorm. I just checked the accelerated case and it seems to be correct there https://github.com/apache/incubator-mxnet/blob/3122423f3118f5ad2e278eeae97fc5a19c1feef1/src/operator/nn/layer_norm.cu#L348-L352 . But this is incorrect for the general case.

**Comment by szha** [comment]
Thanks to @sxjscience for fixing the issue.
