### ISSUE TITLE
Loading parameters and architecture from file (gluon I3D model)

### ISSUE THREAD

**Issue by Gregorino** [apache/incubator-mxnet#20057]
## Description
I have trained and exported gluon's (I3D model) to:
 - model-0000.params
 - model-symbol.json

Loading the model by calling:

    mx.gluon.nn.SymbolBlock.imports("model-symbol.json", ['data'], "model-0000.params", ctx=context)

fails. And the output is incomplete model:

    SymbolBlock(
    <Symbol dense0_fwd> : 1 -> 1

### Error Message
This warning appears when trying to load the model:

    UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
    data: None
    input_sym_arg_type = in_param.infer_type()[0]

## Environment

custom build mxnet 1.8, with cuda 11
python 3.8

**Comment by bgawrych** [comment]
Hi @Gregorino, this is only warning that input data type can't be inferred during loading model, but it's assumed to be fp32. Your model probably have loaded correctly. To visualize graph you can follow this tutorial: https://mxnet.apache.org/versions/1.7.0/api/faq/visualize_graph
```
sym = mx.symbol.load("model-symbol.json")
mx.viz.plot_network(net)
```
