### ISSUE TITLE
MKLDNN header missing in mxnet head 

### ISSUE THREAD

**Issue by EnricoMi** [apache/incubator-mxnet#20054]
## Description
Horovod does not compile with `mxnet-2.0.0b20210317` due to missing mkldnn header files. It did with earlier head snapshots.

### Error Message
Compiling Horovod with it, I get the usual

      MXNet was found with mkl-dnn support but mkldnn header files are missing.
      Please, install MXNet with mkldnn header files.

## To Reproduce

Horovod integration tests compile against mxnet head:

https://buildkite.com/organizations/horovod/pipelines/horovod/builds/5118/jobs/aa1d13eb-069c-4fb9-95a3-b96bf821ca16/raw_log

Is there a fundamental reason why mkldnn headers are dropped from releases and head snapshots from time to time? Can / do CI pipeline check for their existence?

**Comment by leezu** [comment]
mkldnn was renamed to onednn by Intel and MXNet nomenclature was updated in https://github.com/apache/incubator-mxnet/commit/aa92db02201799841bf52db5a0b8507719f04e61 including renaming include/mkldnn folder name to include/onednn

**Comment by EnricoMi** [comment]
So you are saying Horovod should update the way it detects mkldnn headers, as well as including it?

**Comment by leezu** [comment]
Updating the include dirs in horovod's cmake detection code should be sufficient.

**Comment by EnricoMi** [comment]
Fixing this then in Horovod. Thanks for the quick support.
