### ISSUE TITLE
Issue in amalgamation

### ISSUE THREAD

**Issue by saustar** [apache/incubator-mxnet#2017]
When I run make I get following error:

```
g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/home/saurabh/Downloads/OpenBLAS -fPIC -o mxnet_predict-all.o -c mxnet_predict-all.cc
mxnet_predict-all.cc:21:19: fatal error: c_ash.h: No such file or directory
 #include <c_ash.h>
                   ^
compilation terminated.
```

any idea?

**Comment by tqchen** [comment]
have no idea where this comes from, as it is not part of the code base

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
