### ISSUE TITLE
[RFC] Evaluation of performance on Eigen as BLAS engine in MXNet on ARM(Aarch86)

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#20185]
## Problem statement

_Motivation_: Eigen has improved Convolution Op performance in Tensorflow: https://www.linaro.org/blog/optimizing-tensorflow-convolution-performance-on-aarch64/

_GOAL_: Evaluate if MXNet performance with eigen BLAS on Graviton instances compared to OpenBLAS and ArmPL. Make recommendation regarding 

_Tasks:_

1. Install Eigen(either from source or apt install to ensure native installation, https://gitlab.com/libeigen/eigen/-/blob/master/INSTALL).
2. Build MXNet on graviton natively. i.e. All dependencies of MXNet should be either installed via apt-get install or build using architecture = Aarch64 from source on graviton instance. Also,
    1. Set Eigen as blas engine for MXNet. https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html
        if there are no signature changes required for eigen blas integration with MXNet then only changes required are for  linking MXNet to Eigen BLAS.
3. Check correctness of build but running unittests in file test_operator.py after build succeeds
4. Run Benchmarks for following models (latency and throughput, p50,p90,avg) on ARM instance
    1. Mobilenet (MobileNets are small, low-latency, low-power models parameterized to meet the resource constraints of a variety of use cases)
    2. MaskRCNN
    3. resernet50_v2
    4. bert
5. Update build scripts to incorporate Eigen as BLAS engine and compare perf no.‘s with ArmPL and OpenBLAS.
6. Compare performance of certain MXNet operators that utilize BLAS ops. 

_Testing_ 
Test for correctness: Run operator tests for correctness, verify model inference outputs with CPU outputs

_Tracking Branch and Commit_
https://github.com/access2rohit/incubator-mxnet/commit/04a1a82d0f59a642bde4fab83536a276edeb5ada

**Comment by marcoabreu** [comment]
I think it would be good if we can use cross compilation as we do right now as opposed to having to compile on the target machine directly.

**Comment by szha** [comment]
> either from source or apt install to ensure native installation

Eigen is a header-only library so either installation should work.

**Comment by access2rohit** [comment]
@marcoabreu @szha Thank you for inputs! 
We are able to build natively as the ARM team suggested that its more performant this way instead of cross-compilation. 

Eigen does install headers only but it also has `libeigen_blas.so` and `libeigen_lapack.so`. Unfortunately it doesn't provide all thr LAPACK APIs so Its not usedul for LAPACK: https://gitlab.com/libeigen/eigen/-/issues/2221#note_554042309

The file `libeigen_blas.so` does have APIs for `gemm`, `syrk`, `trsm` and `trmm`. But these are not CBLAS APIs but BLAS APIs so currently modifying these inside the code to evaluate the performance of its BLAS support only at Ops level and model level.

**Comment by access2rohit** [comment]
Performance of Eigen is not good
