### ISSUE TITLE
Why there are obvious differences between using cpu and cuDNN to predict?

### ISSUE THREAD

**Issue by Zondabb** [apache/incubator-mxnet#2035]
I want to move my prediction from PC to IPhone, like the project (https://github.com/pppoe/WhatsThis-iOS) do. But the result on IPhone is quite different from PC. I check that it is because PC use cuDNN to accelerate and IPhone has not. How can I solve this problem？

**Comment by piiswrong** [comment]
Could you verify by building with USE_CUDNN=0 on PC and see if the results are the same with on iphone?

**Comment by Zondabb** [comment]
I have test USE_CUDNN=0 and USE_CUDNN=1 on PC, the results are no same.

**Comment by piiswrong** [comment]
Thanks for reporting this. Could you post a minimal reproducing code snippet?

**Comment by zeakey** [comment]
I have the same problem on another projects, in which I use caffe.

I found that results  significantly differs with cuDNN on/off (better precision with cuDNN off).

I suggest you to train model without cuDNN, and verify the consistence on gpu and cpu.

**Comment by Zondabb** [comment]
Here is the code snippet: git@github.com:Zondabb/mxnet_cudnn_test.git. @piiswrong @tqchen

**Comment by superzrx** [comment]
do you use raw data or data in format ( e.g. JPEG) ? different device maybe lead to different decoding result

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
