### ISSUE TITLE
nvcc fatal unsupported gpu architecture 'compute_86' 

### ISSUE THREAD

**Issue by Adnios** [apache/incubator-mxnet#20368]
## Description
When I install mxnet from source, it gives me nvcc fatal unsupported gpu architecture 'compute_86'. My cuda version is 11.0. I can alleviate the issue by change `Auto` to `;8.0`.
https://github.com/apache/incubator-mxnet/blob/b54b7f36c944b933f2aa94f224821548da5fcaf6/CMakeLists.txt#L43

I think the current mxnet installation may not handle cuda 11.0 well.

## To Reproduce
```
rm -rf build
mkdir -p build && cd build
cmake -GNinja \
    -DUSE_CUDA=ON \
    -DUSE_MKL_IF_AVAILABLE=ON \
    -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_BUILD_TYPE=Release \
..
ninja
```

**Comment by leezu** [comment]
This is caused by outdated copy of https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindCUDA/select_compute_arch.cmake Should be fixed by https://github.com/apache/incubator-mxnet/pull/20369

**Comment by Adnios** [comment]
Thanks @leezu . I think this issus is fixed by the https://github.com/apache/incubator-mxnet/pull/20369. Closed.
![image](https://user-images.githubusercontent.com/41060790/122848644-8fdc2580-d33c-11eb-8860-2f0492f70078.png)
