### ISSUE TITLE
[BUG!]build error: 'operator!=' function uses 'auto' type specifier without trailing return type

### ISSUE THREAD

**Issue by jikechao** [apache/incubator-mxnet#20366]
## Description
When I build Mxnet from source with the statement `make`, the build crash.

### Error Message

![image](https://user-images.githubusercontent.com/29506758/122634101-e532ef80-d10e-11eb-859c-5c31bad17cea.png)

## To Reproduce
* Ubuntu 16
* gcc-8
* GNU Make 4.1

**Comment by jikechao** [comment]
I build MXnet(version 1.8.0) following the install shell file 'install-mxnet-ubuntu-python.sh'

**Comment by leezu** [comment]
`install-mxnet-ubuntu-python.sh` is not maintained and has been removed in later releases AFAIK. You can follow the official instructions instead: https://mxnet.apache.org/get_started/build_from_source
