### ISSUE TITLE
请问同等设备，同等代码的情况下，C++与python的速度差别有多大。

### ISSUE THREAD

**Issue by yangkunpeng-coder** [apache/incubator-mxnet#20396]
## Description
(A clear and concise description of what the bug is.)

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=100` before running your script.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.同等设备，同等代码的情况下，C++与python的速度差别有多大。
2.

## What have you tried to solve it?

1.同等设备，同等代码的情况下，C++与python的速度差别有多大。
2.

## Environment

***We recommend using our script for collecting the diagnostic information with the following command***
`curl --retry 10 -s https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py | python3`

<details>
<summary>Environment Information</summary>

```
# Paste the diagnose.py command output here
```

</details>

**Comment by TristonC** [comment]
Do you have a case? It is a vague question  without any context.
