### ISSUE TITLE
Nvidia GPU Rest Engine

### ISSUE THREAD

**Issue by loweew** [apache/incubator-mxnet#2043]
are there any efforts to make an example using GRE (https://developer.nvidia.com/gre) announced at GTC? I don't want to duplicate work. 

Also, I enjoyed the mxnet talks at GTC. Great work.

**Comment by piiswrong** [comment]
None that I know of. You are welcome to lead this. What do you want to use it for?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
