### ISSUE TITLE
Issue with OpenBLAS when building on Windows

### ISSUE THREAD

**Issue by jfsantos** [apache/incubator-mxnet#2044]
I followed the instructions to build mxnet on Windows but I am getting errors related to OpenBLAS during the build stage. Here is a sample message:

`unresolved external symbol __imp__cprintf referenced in function blas_memory_alloc C:\Users\jfsantos\src\mxnet\build\libopenblas.a(memory.obj) mxnet`.

Apparently these symbols are only defined on Visual Studio 2015 and even changing the compiler to the updated Nov 2013 CTP did not solve it. Maybe the new OpenBLAS builds are compiled with VS2015?

**Comment by CharlesMei** [comment]
@jfsantos you maytry libopenblas.dll.a, this works for me

**Comment by atlury** [comment]
Thanks libopenblas.dll.a works for me

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
