### ISSUE TITLE
[Windows] Access GPU only using libmxnet.dll 20160223 version

### ISSUE THREAD

**Issue by pagpires** [apache/incubator-mxnet#2045]
First, many thanks to MXNET contributors, for this great package.
I had a similar issue in accessing GPU. When type:
a = mx.nd.ones((2,3), mx.gpu())
it returns a matrix with zeros (while it works fine without mx.gpu() argument)

My system:
Windows 8.1, GeForce 820M (2.1 capability), I installed the MXNET-20160429 by directly using the binray files.

Then I found if and only if I change the libmxnet.dll to the 20160223 version, I fixed this issue. None of the later version of libmxnet.dll works.

Hope this helps you pinpoint the problem.

**Comment by hjk41** [comment]
Looks like another binary compatibility problem...
We have long been struggling with binary compatibility issues in MxNet.
Windows 10/8/7 and Windows servers need to have different binaries, and
some Windows 8 machines cannot run the binary built with Windows 10. We
haven't figured out why. Is it possible for you to build a binary from
source? It may help us pinpoint the problem.

On Thu, May 5, 2016 at 11:47 PM, pagpires <notifications@github.com> wrote:

> First, many thanks to MXNET contributors, for this great package.
> I had a similar issue in accessing GPU. When type:
> a = mx.nd.ones((2,3), mx.gpu())
> it returns a matrix with zeros (while it works fine without mx.gpu()
> argument)
>
> My system:
> Windows 8.1, GeForce 820M (2.1 capability), I installed the MXNET-20160429
> by directly using the binray files.
>
> Then I found if and only if I change the libmxnet.dll to the 20160223
> version, I fixed this issue. None of the later version of libmxnet.dll
> works.
>
> Hope this helps you pinpoint the problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2045>
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by juliandewit** [comment]
Hello I have some developments on this issue too.
I have 2 computers. One with windows 8, one with windows 10. Different GPU's.

For both computers only release 20160223 and release 20151228 worked. I tried many others but they didn't.

So for me the problem is consistent on win 8 and win 10. Only the above 2 releases work.

Does this help you ?

I can build a binary from source as I did this before once but I'm a bit busy at the moment and it took me a few hours then. I'll try to do it asap.

**Comment by pagpires** [comment]
@hjk41 Hi Chuntao, I actually tried to compile by myself once but failed. My VS2013 spat some errors during building the binary file and I am still figuring out what happened.. I will post any updates I get. Sorry for not being helpful..

**Comment by juliandewit** [comment]
The win10 64 gpu also worked on my win 8 machine. So perhaps you already fixed it.

If you are still interested I built mxnet on my win8 machine of the current source code.
Can you see anything from my compiled binary ?

**Comment by CharlesMei** [comment]
windows 7 SP1, GeForce GT 705m((2.1 capability), cuda7.5
my machine can use gpu with prebuild version 20160223 , but not 20160419
