### ISSUE TITLE
RTX 3080TI support

### ISSUE THREAD

**Issue by seventheli** [apache/incubator-mxnet#20451]
## Description
Both docker Release 21.06 and mxnet_cu112-2.0.0b20210714-py3-none-manylinux2014_x86_64.whl not work for RTX 3080TI, is any version work on 3080TI?

docker run --gpus all -it --rm --env NVIDIA_DISABLE_REQUIRE=1 nvcr.io/nvidia/mxnet:21.06-py3
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

## References
https://docs.nvidia.com/deeplearning/frameworks/mxnet-release-notes/rel_21-06.html#rel_21-06

**Comment by TristonC** [comment]
@seventheli Which driver did you install on your machine? It should work with RTX 3080Ti.

**Comment by seventheli** [comment]
the problem is from the windows 10 dev version is too old,
