### ISSUE TITLE
1.9.RC6 Licensing Issues

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#20475]
Based on feedback from the general@incubator 1.9 rc6 release vote, we have some issues with licensing to address. 

Vote thread and feedback: https://lists.apache.org/thread.html/rb60ab16d34f7c019fdc63fd99a34bc61c099eb480cb407c1f1905e30%40%3Cgeneral.incubator.apache.org%3E

I've compiled the feedback into a list of action items. If you can assist in tackling one of these items, please coordinate in the comments on this issue.

Action Items

- [x] 1. The following files have an ASF header but is listed as MIT in LICENSE file. We need to determine what the files are actually licensed as and ensure the header and LICENSE files reflect this.

 - src/operator/nn/layer_norm.cc
 - src/operator/numpy/np_einsum_op.cc
 - src/operator/numpy/np_einsum_op-inl.h
 - src/operator/numpy/np_einsum_path_op-inl.h

- [x] #20511

 - This file has a comment that states "Code is a direct translation of the erfinv m file in matlab version 2.0.” and the GitHub reference doesn't have a BSD file header. As far as I’m aware Matlab is not open source software. Is this Category X software?
 - This files seem to have incorrect licensing information [13] At the URL referenced it has a different header. I can’t see why the ASF copyright would be in this header.

- [x] #20515

 - example/image-classification/predict-cpp/image-classification-predict.cc

- [x] 4. These files seem to incorrectly have an ASF header

 - python/mxnet/onnx/mx2onnx/_export_onnx.py
 - cmake/Modules/FindJeMalloc.cmake
 - src/operator/nn/mkldnn/mkldnn_base-inl.h

- [x] 5. A large number of file have ASF headers but also state "Copyright (c) 201X by Contributors”. e.g [1][2][3][4] There looks to be more than 500 files like this.  Are these 3rd party file or ASF files? If they are ASF files there there should be no copyright line. Examples:

 - include/mxnet/op_attr_types.h
 - cpp-package/include/mxnet-cpp/op_suppl.h
 - src/initialize.cc
 - src/operator/cudnn_bilinear_sampler-inl.h

- [X] 6. A number of files have "Copyright (c) 201X Microsoft” and also have ASF headers. Are these files 3rd party files or ASF files? e.g. [11] They look like 3rd party files to me. Some are Apache licensed but some are not. e.g [12] I cannot see this mentioned in LICENSE.

 - 11: src/operator/contrib/deformable_psroi_pooling.cu
 - 12: src/operator/contrib/modulated_deformable_convolution.cu

- [x] 7. I also noticed that the docker file refreshes to https://github.com/dmlc/mxnet Why is this? In fact there seems to be a large number of references to "https://github.com/dmlc” (https://github.com/dmlc) and "https://github.com/dmlc/mxnet". (https://github.com/dmlc/mxnet.)

**Comment by TristonC** [comment]
Thanks @josephevans . @szha will you help to address the license issues?

**Comment by Kh4L** [comment]
@josephevans thanks for driving this forward

**Comment by sandeep-krishnamurthy** [comment]
PR for item 6 - https://github.com/apache/incubator-mxnet/pull/20520

**Comment by josephevans** [comment]
Thanks everyone for helping with these license issues. All items have been fixed and merged.

**Comment by szha** [comment]
@josephevans thanks for driving the fix for these license issues!
