### ISSUE TITLE
License issue with example/image-classification/predict-cpp/image-classification-predict.cc

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#20515]
Based on feedback from our 1.9.0.RC6 vote (see thread [here](https://lists.apache.org/thread.html/rb60ab16d34f7c019fdc63fd99a34bc61c099eb480cb407c1f1905e30%40%3Cgeneral.incubator.apache.org%3E)), the code in `image-classification-predict.cc` is not compatible with the ASF 2.0 license.

It looks like we have a few options:

1. Ask the original authors to release any copyright claims and license the file under ASF 2.0 license. 
2. Remove the example from the repository entirely.

The code was added in https://github.com/apache/incubator-mxnet/pull/891. It looks like the original authors are @skylook, 
@caprice-j, and @pertusa.

**Comment by josephevans** [comment]
Since we are not getting any responses from the original authors and can't resolve this licensing issue at this time, I am going to remove the example from the repository. 

@szha @sandeep-krishnamurthy @leezu Any objections to this?

**Comment by sandeep-krishnamurthy** [comment]
I agree to make MXNet license compliance. We can rewrite the example if users request for one for this use case.

**Comment by szha** [comment]
#20530 and #20536 added the logic in preparing the source archive for release to remove the image classification file. Thanks @josephevans for fixing this issue!

**Comment by skylook** [comment]
I agree to release all copyright claims on the code in image-classification.cpp
Thx
