### ISSUE TITLE
License issue with src/operator/contrib/erfinv-inl.h

### ISSUE THREAD

**Issue by mseth10** [apache/incubator-mxnet#20511]
This file has a comment that states "Code is a direct translation of the erfinv m file in matlab version 2.0.”
https://github.com/apache/incubator-mxnet/blob/dba682a57812b49a222c04297224921393ea90bb/src/operator/contrib/erfinv-inl.h#L61-L62
Since Matlab is not open source software, it's basically a Category X software.

#### Proposed Solution
There are two commonly used methods for implementing the inverse error function:
- Initial approximation followed by two steps of Newton's method
  - Used by MATLAB (current implementation) - Category X license
  - Also used by Scilab (GPL license - also Category X): https://github.com/scilab/scilab/blob/master/scilab/modules/special_functions/macros/erfinv.sci 
- Rational approximation of percentage points of normal distribution
Used by SciPy (new BSD license): https://github.com/scipy/scipy/blob/master/scipy/special/cephes/erfinv.c 

We can modify MXNet's `erfinv` function to use SciPy's implementation as SciPy's license is Apache compliant.

**Comment by szha** [comment]
Is the performance comparable between the translated solution and the scipy's implementation?

**Comment by mseth10** [comment]
> Is the performance comparable between the translated solution and the scipy's implementation?

I can check for performance after getting SciPy's implementation to work and then post the results here.

**Comment by mseth10** [comment]
Do we have inverse normal distribution function in MXNet? Something similar to https://github.com/scipy/scipy/blob/master/scipy/special/cephes/ndtri.c @szha @leezu

**Comment by szha** [comment]
I don't recall if we have one

**Comment by mseth10** [comment]
Fixed by #20517
