### ISSUE TITLE
Does the argument of input_shape is required for MNISTIterator?

### ISSUE THREAD

**Issue by tjuzhao111** [apache/incubator-mxnet#2055]
I am reading the code of example/image-classification/train_mnist.py. There is a argument of input_shape. 
`input_shape = data_shape,`
But when I refer to the source code in src/io/iter_mnist.cc, I didn't find the parameter of input_shape. The doc don't list this argument too. When I delete these two lines, everything looks OK.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
