### ISSUE TITLE
[RFC] [Licensing] Address ASF Feedback for 1.9.0.rc7 release

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#20616]
## Problem statement
Based on the feedback from ASF on our vote to release MXNet v1.9.0.rc7, we still have a few licensing issues that caused a -1 vote, which prevents us from moving forward with the release.

Based on the RC7 voting thread, the following licensing issues are still outstanding:

- [x] Files incorrectly have ASF headers. These files are all copyrighted by NumPy developers and released under the 3-clause BSD license. We should not have added the ASF header and kept the original license headers intact, and mention this by including it in the "3-clause BSD license" section in LICENSE.
  - src/operator/numpy/np_einsum_op.cc
  - src/operator/numpy/np_einsum_op-inl.h
  - src/operator/numpy/np_einsum_path_op-inl.h

- [x] Some files are not correctly listed in LICENSE. For example, these files contain a "Copyright Microsoft" line but are released under ASF-2 or MIT license. These need to be properly mentioned in LICENSE:
  - src/operator/contrib/deformable_psroi_pooling.cu
  - src/operator/contrib/deformable_psroi_pooling-inl.h
  - src/operator/contrib/deformable_psroi_pooling.cc
  - src/operator/contrib/multi_proposal-inl.h
  - src/operator/contrib/multi_proposal.cc
  - src/operator/contrib/multi_proposal.cu
  - src/operator/contrib/psroi_pooling.cc
  - src/operator/contrib/psroi_pooling.cu
  - _**Additional files in the same situation as above (identified by running skywalking-eyes):**_
  - src/operator/contrib/psroi_pooling-inl.h
  - src/operator/contrib/deformable_convolution-inl.h
  - src/operator/contrib/deformable_convolution.cc
  - src/operator/contrib/deformable_convolution.cu

As ASF noted, not all files were checked and there could be others that are missed. In order to better identify licensing issues in the future, we should extend the use of automated tools (such as [skywalking-eyes](https://github.com/apache/skywalking-eyes)). 

- [x] Update our CI pipelines to utilize the latest Apache tool for license checks (skywalking-eyes)
- [x] Update our automated tools to detect files that have multiple license headers
- [ ] #20723
- [x] Properly document 3rd-party files/symlinks in include directory in LICENSE

## References
- RC7 Voting Thread: https://lists.apache.org/thread.html/r5789f5d93716d9d710b855775e71e4892fd37e41338c70c0855958ad%40%3Cgeneral.incubator.apache.org%3E

**Comment by josephevans** [comment]
I manually checked all source files in `src/operator/contrib` and `src/operator/numpy` to ensure they are either:

1. Licensed under ASF-2.0 license with standard recognizable header. If they do not contain the standard header, they should be listed under the ASF-2.0 section in `LICENSE`
2. Licensed under some other compatible license, but clearly mentioned in `LICENSE` under the compatible license section (ie BSD 2/3-clause, MIT, etc.)

Any help manually auditing the rest of the source tree would be greatly appreciated.

**Comment by barry-jin** [comment]
I have manually checked all the header files in include/onednn(mkldnn), include/dlpack, include/dmlc, include/mshadow and found one more issue: 

- [ ] include/dmlc/concurrentqueue.h and include/dmlc/blockingconcurrentqueue.h are under the Simplified BSD license (2-clause BSD license), which are not correctly listed in LICENSE.

**Comment by josephevans** [comment]
I'm currently having issues getting #20626 to pass CI because of MKLDNN-related tests - opened an issue (#20643) to track.

**Comment by josephevans** [comment]
I looked into the `license_header.py` script, and it actually will detect when a file has multiple licenses and throw an error. We may need to expand the list of strings it recognizes licenses with here:

https://github.com/apache/incubator-mxnet/blob/v1.9.x/tools/license_header.py#L62-L63

**Comment by josephevans** [comment]
Based on @szha's comments above, I have created a [PR](https://github.com/apache/incubator-mxnet/pull/20709) to address these issues as well as make the licensing more clear for binary releases.

**Comment by josephevans** [comment]
Created a PR for the v1.9.x branch: https://github.com/apache/incubator-mxnet/pull/20722

**Comment by josephevans** [comment]
Once #20722 is merged, I would like to close this issue and move forward with 1.9.0.rc8. I've converted the single outstanding task of updating the license tool to a new item for tracking (#20723).

**Comment by szha** [comment]
Thanks Joe & community for continuing to push this along. 

Given that this release process has drawn on quite a while, would it be possible to pull in PR #20137 [1]? This goes along with #20107 [2] that was part of 1.9.0.rc7 [3] for deconvolution support. I would be happy to do the backporting.

Thanks!
Sam

[1] https://github.com/apache/incubator-mxnet/pull/20137
[2] https://github.com/apache/incubator-mxnet/pull/20107 
[3] https://github.com/apache/incubator-mxnet/releases/tag/1.9.0.rc7


﻿On 11/2/21, 7:12 PM, "Joe Evans" ***@***.***> wrote:

    CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you can confirm the sender and know the content is safe.



    Once #20722 is merged, I would like to close this issue and move forward with 1.9.0.rc8. I've converted the single outstanding task of updating the license tool to a new item for tracking (#20723).

**Comment by josephevans** [comment]
Merged #20726 into v1.9.x, we should be ready for another release candidate. Closing this issue.
