### ISSUE TITLE
MxNet input dataset

### ISSUE THREAD

**Issue by linnanwang** [apache/incubator-mxnet#2063]
Hello,

Does mxnet take the same data file as Caffe (lmdb)? Thank you. If yes, please elaborate.

**Comment by zeakey** [comment]
As I know, Mxnet doesn't take lmdb(or leveldb) as data backend which is used by caffe.

But it uses a unique data IO module to tackle the bottle-neck of training big models, the database files usually end with '.rec', which can be easily generated by mxnet_root/bin/im2rec.

**Comment by linnanwang** [comment]
Thanks for the quick reply. But wouldn't be nice if they are using the same dataset format. ImageNet are pretty large dataset.

**Comment by linnanwang** [comment]
Hello,

After I have successfully compiled it with CMake, there is no such a file named mxnet_root/bin/im2rec. 
Could you please provide more info? Thanks.

**Comment by piiswrong** [comment]
Use the python version tools/im2rec.py

**Comment by linnanwang** [comment]
Thank you for the assist. Is there an example to build a dataset with im2rec.py? Thank you.

**Comment by qiaohaijun** [comment]
@linnanwang you can generate the image list use awk
