### ISSUE TITLE
Mxnet model visualisation

### ISSUE THREAD

**Issue by rhythm9229** [apache/incubator-mxnet#2066]
Is there a tool for visualising what the mxnet model has learnt after training like https://github.com/yosinski/deep-visualization-toolbox for caffe models?
Or is there some way for visualizing what each layer is learning, this is specially needed for finetuning models.

**Comment by tmatas** [comment]
I have the same issue!

Is this topic considered relevant for the future development of MxNet?

**Comment by larabear** [comment]
Need this!

**Comment by szha** [comment]
@zihaolucky

**Comment by zihaolucky** [comment]
@rhythm9229 We have https://github.com/dmlc/tensorboard to visualize image.
