### ISSUE TITLE
conventions for symbol attributes

### ISSUE THREAD

**Issue by pluskid** [apache/incubator-mxnet#2070]
Since attributes are used more and more frequently by different components, do you guys think it would be better to have some naming conventions? @piiswrong @tqchen @mli @antinucleon , here are some conventions that have never been documented anywhere:
- Internal variables with double underscopes (e.g. `__shape__` is internally used to store optional shape information for a variable).
- Namespace: currently `list_attrs` use `_` as a separator between the symbol name and actually attribute name. I think since `_` might be very commonly be used in the attribute names themselves, we might want to choose a more distinct name, such as `:` or `.` or `/`.

Are there any other cases we need to consider?

Also when composing symbols. Currently the attributes are set **before** calling `_compose`. As a results, some attributes are implicitly created for children nodes. For example:

``` python
    data = mx.sym.Variable('data', attr={'mood': 'angry'})
    op = mx.sym.Convolution(data=data, name='conv', kernel=(1, 1),
                            num_filter=1, attr={'mood': 'so so'})
    assert op.list_attr() == {'data_mood': 'angry', 'conv_mood': 'so so',
                              'conv_weight_mood': 'so so', 'conv_bias_mood': 'so so'}
```

Note those `conv_weight_mood`, etc. I could imaging this might be useful in the case of `ctx2grp`. But @tqchen can you confirm this is expected behavior? Because we recently got a PR from the Julia side that changed the order of `_compose` and `setattr`, and I am wondering if I should switch it back.

**Comment by tqchen** [comment]
The implicit copy of the attributes to implicitly created children was expected behavior. 
This was used to support, say set learning rate in the convolution operators, without creating the weight explicitly.  I do not have a good idea on better alternatives. 

I agree that list_attrs may need a better separator than underscore. We can fix a convention. ```/```(used by tf). ```:``` or ```.``` all works for me

**Comment by piiswrong** [comment]
You can directly set 'weight_lr_mult': 0.01 to change attributes for implicit created variables.
I guess the only use case for copying is group ctx

**Comment by vchuravy** [comment]
We are also using it to freeze parameters during training with the Julia bindings. https://github.com/dmlc/MXNet.jl/pull/87, increasing efficiency for iterative model building.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
