### ISSUE TITLE
Tutorial page is not displayed properly.

### ISSUE THREAD

**Issue by dai-ichiro** [apache/incubator-mxnet#20731]
This website is not displayed properly.

https://mxnet.apache.org/versions/master/api/python/docs/tutorials/getting-started/gluon_migration_guide.html#NumPy-Arrays

**Comment by barry-jin** [comment]
Will be fixed in #20716

**Comment by barry-jin** [comment]
Documentation is fixed: https://mxnet.apache.org/versions/master/api/python/docs/tutorials/getting-started/gluon_migration_guide.html

**Comment by dai-ichiro** [comment]
Thank you so much.

But some parts are still strange.
