### ISSUE TITLE
Port #18028 to v1.x, master

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#20737]
## Description
[This PR](https://github.com/apache/incubator-mxnet/pull/18028) was created for the v1.6 branch and merged. However, this change never made it into the v1.x branch, and it's [associated port for master](https://github.com/apache/incubator-mxnet/pull/18001) was never merged as well.

We have users with models that use these ops, and they are unable to upgrade from v1.6 since these ops are not present. Could we get some help from the Intel folks to get this ported into v1.x and master branches?

**Comment by ssriram1978** [comment]
As v1.9 official release is getting closer, can we expedite this  pull request to v1.x branch ASAP? Thanks!

**Comment by bgawrych** [comment]
quantized RNN is already merged to v1.9.x, v1.x and master branch - please open new issue if something is wrong
v1.9.x: https://github.com/apache/incubator-mxnet/pull/20815
v1.x: https://github.com/apache/incubator-mxnet/pull/20759
master: https://github.com/apache/incubator-mxnet/pull/20952
