### ISSUE TITLE
Where to find the benchmark of mxnet on mobile devices?

### ISSUE THREAD

**Issue by qinjian623** [apache/incubator-mxnet#2074]
Hi,
I'm a Caffe user, but considering moving to mxnet because Caffe is lack of Recurrent Layer.

My team is doing CV task on mobile devices (Android platform now, but iOS will be included in the future). And we want to build the connections between frames of video with RNN. So we want to know the performance of mxnet on mobile phone to help us to make this tech decision. Caffe has a none-official version on mobile phone based on Eigen lib. 
1. We only care about one thing: "Is mxnet at least as fast as Caffe on mobile devices?", and if faster, it'll be better.
2. I've seen the APK app for Android, so does mxnet need any extra works to adapt to iOS?

Thanks.

**Comment by piiswrong** [comment]
I don't know of any benchmark but here are a few tips for performance: set MXNET_ENGINE_TYPE=NaiveEngine and compile with openmp

**Comment by antinucleon** [comment]
There is an iOS example: https://github.com/pppoe/WhatsThis-iOS

Note it is running Inception-Batch Norm model, and I don't think this example are using muti-cores.

**Comment by ysh329** [comment]
@piiswrong My dear brother, do you mean: `export MXNET_ENGINE_TYPE=NaiveEngine` in command line?

**Comment by ysh329** [comment]
@qinjian623 @piiswrong I think this issue can close

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
