### ISSUE TITLE
Loading weights and bias for all layers:

### ISSUE THREAD

**Issue by gaush123** [apache/incubator-mxnet#2080]
Is there a way to load parameters (weights and bias) from a mxnet params model, and subsequently replace those arrays with desired arrays?

**Comment by antinucleon** [comment]
The ```params``` is a dictionary of NDarray, you can set value and bind to new model.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
