### ISSUE TITLE
Confusing documentation regarding Large Tensor Support

### ISSUE THREAD

**Issue by DominikaJedynak** [apache/incubator-mxnet#20807]
## Description
In https://mxnet.incubator.apache.org/versions/master/api/faq/large_tensor_support it is stated that "...tensors are indexed in MXNet using INT32 indices by default. Now MXNet build with Large Tensor supports INT64 indices." 
If I understand correctly, this means that the size of every dimension can be INT64. 

Meanwhile in a config file, it is said that every dimension in bounded by INT32: https://github.com/apache/incubator-mxnet/blob/4fc58fa1862a00c1af0788c6ce0ab19015f512d7/config/linux.cmake#L120 
https://github.com/apache/incubator-mxnet/blob/4fc58fa1862a00c1af0788c6ce0ab19015f512d7/config/linux.cmake#L121

Could you clarify it and correct the documentation if it is incorrect?

**Comment by anko-intel** [comment]
@access2rohit, any comments? 
I originally thought that USE_INT64_TENSOR_SIZE allowed the use of tensor indices in any dimension in the int64_t range.

**Comment by access2rohit** [comment]
Code supports and testing was done with vectors and tensors with individual dims that are > INT_MAX. The line in came can be deleted since it causes confusion. @DominikaJedynak This feature is only supported for CPU.
