### ISSUE TITLE
mxnet1.9.0 ndarray初始化时报错

### ISSUE THREAD

**Issue by yoyy123** [apache/incubator-mxnet#20818]
执行以下代码初始化
NDArray nd_input
执行到下面这行
CHECK_EQ(MXNDArrayCreateNone(&handle), 0);
报错 
0xC0000005: Access violation executing location 0x0000000000000000.

**Comment by TristonC** [comment]
@yoyy123  Could you add more details about how this issue can be reproduced?

**Comment by yoyy123** [comment]
> @yoyy123您能否添加有关如何重现此问题的更多详细信息？

描述
Vs2019 在执行以下代码
NDArray nd_input时生成错误

错误信息
0xC0000005：执行位置0x0000000000000000时出现访问冲突。

这个问题我找了一下，发现是dll没有在path添加路径，导致一些dll没有读取到引起的，我配置了路径就可以了，但是另外的地方又在报错了
