### ISSUE TITLE
What does each dimension the input array stands for? nrow by ncol, or ncol by nrow.

### ISSUE THREAD

**Issue by snowdustdj** [apache/incubator-mxnet#2084]
I searched a lot try to find some words about the dimensions of the input data array.
I'm using mxnet in R, for example, the train.array is of shape c(23,28,1, ncol(X_train)):

X_train is my training data, with each column being an sample, for example, X_train[,1] is the first sample with 644 elements. The input image has a true size of 23*28 (23 rows, 28 columns), and I vectorize the image columnwise which gives me a vector of length 644.

So am I specifying the right input array dimension? I saw all the documents about mx.symbol.Convolution is talking about shape (y,x), I'm assuming it's (nrow, ncol) fashion, and the training array is (nrow, ncol,n_ chanel, n_sample). Am I right?

Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
