### ISSUE TITLE
KeyError: 'rescale_grad' when using ccsgd

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#2088]
When I tried to create a ccsgd optimizer like this:

```
optimizer = mx.optimizer.ccSGD()
```

I got this error:

```
KeyError: 'rescale_grad'
```

From the source code:

```
self.handle = Optimizer._init_cc_optimizer(
            'ccsgd',
            ['momentum', 'rescale_grad', 'clip_gradient'],
            [momentum, kwargs['rescale_grad'], kwargs['clip_gradient']])
```

It seems if I dont pass rescale_grad and clip_gradient explicitly, it will pop up this error. Since they all have default values, can I just use the default ones?

**Comment by piiswrong** [comment]
rescale_grad doesn't have a default value. It needs to be 1/batch_size

**Comment by ascust** [comment]
What about clip_gradient? I think the previous versions did have a default value. I found this because I updated Mxnet and my previous code did not work because of this error. @piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
