### ISSUE TITLE
ImportError: cannot import name lib info  On Mac OS X captain  Python2.7.10

### ISSUE THREAD

**Issue by szad670401** [apache/incubator-mxnet#2092]
I follow the official Installation Guide compile the mxnet and setup for python2.7.10.
It appear this  problem.
But this problem doesn't appear in python3 .

> > > import mxnet
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/mxnet/**init**.py", line 7, in <module>
> > >     from .base import MXNetError
> > >   File "/Library/Python/2.7/site-packages/mxnet/base.py", line 10, in <module>
> > >     from . import libinfo
> > > ImportError: cannot import name lib info

**Comment by erickingxu** [comment]
@szad670401 ,I had same problem
do you had some resolution for it?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
