### ISSUE TITLE
Inconsistent behavior of mx.sym.LeakyReLU between CPU and GPU

### ISSUE THREAD

**Issue by mazeltovlee** [apache/incubator-mxnet#20947]
## Description
When sending `mx.sym.LeakyReLU` with `slop=0.0` a `-Inf` array, it will output `0` in CPU but `NaN` in GPU. In contrast, LeakyRelu behaves the same on the `Inf` array (output `Inf` in both CPU and GPU)

## To Reproduce
```
import os
import mxnet as mx
net = mx.symbol.Variable('data', shape=(0, 10,10,3))
net = mx.sym.LeakyReLU(data=net, slope=0.0, act_type="leaky")
mx.viz.plot_network(symbol=net)
import numpy as np
input_shape = (10, 10,10,3)
x = np.random.rand(*input_shape)
x *= -np.Inf
e = net.bind(mx.gpu(), {'data': mx.nd.array(x,mx.gpu())})
output_gpu = e.forward()
print("The GPU output is: ", output_gpu)

e_cpu = net.bind(mx.cpu(), {'data': mx.nd.array(x,mx.cpu())})
output_cpu = e_cpu.forward()
print("The CPU output is: ", output_cpu)
```

### Steps to reproduce
Run above code with GPU or access the CoLab link: https://colab.research.google.com/drive/1jIyOFR0n8j15Yy10b1EwUKWj6v7EmJAF?usp=sharing

**Comment by mazeltovlee** [comment]
I also find giving the LeakyReLU `NaN` will also trigger inconsistency: given NaN, LeakyReLU in GPU mode will output NaN while it outputs 0 in CPU mode. I seems that, given a NaN input, the expected behavior should be NaN instead of 0. But for the -inf input, the expected behavior should be 0 instead of NaN?

**Comment by DickJC123** [comment]
For negative input `x`, isn't the leaky relu output `slope*x`?  So the proper output = `-inf * 0` = `Nan`.

**Comment by mazeltovlee** [comment]
Yes, I have tried `-Inf` to `mx.sym.relu` on both GPU and CPU, it will output 0.

**Comment by hankaj** [comment]
Hi! I investigated the issue and the case is that MxNet implementation of Leaky ReLU is different than OneDNN approach. Building the project without OneDNN (flag USE_ONEDNN set to 0) results in the same results for CPU and GPU (nan for -inf and for nans). In OneDNN, for slope=0.0 multiplication by 0 does not occur. They use plain ReLU in this case (max(0, z)) and they would prefer it to stay that way to keep the consistency with older oneDNN versions.

Is it okay to close the issue considering the fact that it is clarified where the difference comes from?

**Comment by mazeltovlee** [comment]
Hi @hankaj 
Thanks for your investigation. Where the difference comes from is very clear to me now. Since oneDNN may not change its behavior for this corner case, may I know if you plan to fix this inconsistency on the MXNet side?

**Comment by hankaj** [comment]
For now, we do not plan to change this. Workaround for this inconsistency may result in worse performance. In addition, MXNet approach is currently aligned with PyTorch approach.

**Comment by mazeltovlee** [comment]
Thanks! I have closed this issue.
