### ISSUE TITLE
[RFC] Graduate MXNet from Apache Incubator

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#20984]
Hello MXNet Community,

I'd like to start the discussion of graduating MXNet from an Apache Incubating project to a top-level ASF project. 

MXNet has been an incubating project since January 23rd, 2017 [1]. Since then, the project has had 24 releases under the ASF Incubator (0.11.0, 0.12.0, 0.12.1, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.8.0, 1.9.0, and 7 alpha/beta releases of 2.0.) There is a thriving community of developers and users from all over the world that regularly contribute to the project.

I’m asking the community and mentors for feedback or suggestions on how to move this forward. Based on the graduation guidelines [2], the next step for graduation is having a community vote. Should we have a community (dev@) vote in a few weeks?

One thing I also noticed is the project status page [1] may be a little out-of-date (the committers and incubation status reports are not up-to-date), would one of our PPMCs like to take on updating this?

References:

[1] https://incubator.apache.org/projects/mxnet.html
[2] https://incubator.apache.org/guides/graduation.html

**Comment by TristonC** [comment]
Complete (and sign off) tasks documented in the [status file](https://incubator.apache.org/guides/graduation.html#notes-status)

[x] Ensure [suitable names](https://incubator.apache.org/guides/graduation.html#notes-names) for project name and product names

[x] Demonstrate ability to [create Apache releases](https://incubator.apache.org/guides/graduation.html#releases). MXNet has  1.9 and 2.0Beta1 releases

[] Demonstrate [community readiness](https://incubator.apache.org/guides/graduation.html#community) @josephevans  will send invitations

[x]Ensure [Mentors](https://incubator.apache.org/incubation/Roles_and_Responsibilities.html#Mentor) and [IPMC](https://incubator.apache.org/incubation/Roles_and_Responsibilities.html#Incubator_Project_Management_Committee_IPMC) have no [remaining issues](https://incubator.apache.org/guides/graduation.html#notes-issues)

[x]Decide upon [destination](https://incubator.apache.org/guides/graduation.html#subproject-or-top-level). Top-level project is the decided destination

[] Prepare a [resolution](https://incubator.apache.org/guides/graduation.html#tlp-resolution) (top level candidates only). @josephevans 

[Incubator PMC (IPMC)](https://incubator.apache.org/incubation/Roles_and_Responsibilities.html#Incubator_Project_Management_Committee_IPMC):

For top level candidates, this is a [recommendation VOTE](https://incubator.apache.org/guides/graduation.html#ipmc-top-level-recommendation)

Final [hand-over](https://incubator.apache.org/guides/graduation.html#notes-on-hand-over)

Consider post graduation [tasks](https://incubator.apache.org/guides/graduation.html#project-first-steps)

[] https://incubator.apache.org/projects/mxnet.html needs to be updated @szha 
Additional information

**Comment by josephevans** [comment]
Just to update everyone on the progress:

- Updated mentors, PPMC members and committers on our [status page](https://incubator.apache.org/projects/mxnet.html)
- Identified some issues with formatting of status page source file that prevented the dev and commits mailing list from being recognized by [apache clutch tool](https://incubator.apache.org/clutch/) (status is now green for these columns.)
- Created a [PR](https://github.com/apache/incubator-mxnet/pull/20993) to address errata listed on [clutch project status page](https://incubator.apache.org/clutch/mxnet.html)
- Updated the [Apache Maturity Model Assessment for MXNet](https://cwiki.apache.org/confluence/display/MXNET/Apache+Maturity+Model+Assessment+for+MXNet) to reflect resolution of the last remaining open item (having a clear [security](https://mxnet.incubator.apache.org/api/faq/security) reporting page and process.)

**Comment by TristonC** [comment]
Thanks @josephevans.  I think we are ready to send invitations.

**Comment by bartekkuncer** [comment]
Yeah, lets graduate! 😄

**Comment by waytrue17** [comment]
Graduation is important. Thank you @josephevans for leading this!

**Comment by josephevans** [comment]
Here is the proposed resolution to graduate the project:

```
Establish the Apache MXNet Project

WHEREAS, the Board of Directors deems it to be in the best interests of
the Foundation and consistent with the Foundation's purpose to establish
a Project Management Committee charged with the creation and maintenance
of open-source software, for distribution at no charge to the public,
related to a flexible and efficient library for Deep Learning.

NOW, THEREFORE, BE IT RESOLVED, that a Project Management Committee
(PMC), to be known as the "Apache MXNet Project", be and hereby is
established pursuant to Bylaws of the Foundation; and be it further

RESOLVED, that the Apache MXNet Project be and hereby is responsible for
the creation and maintenance of software related to a flexible and
efficient library for Deep Learning; and be it further

RESOLVED, that the office of "Vice President, Apache MXNet" be and
hereby is created, the person holding such office to serve at the
direction of the Board of Directors as the chair of the Apache MXNet
Project, and to have primary responsibility for management of the
projects within the scope of responsibility of the Apache MXNet Project;
and be it further

RESOLVED, that the persons listed immediately below be and hereby are
appointed to serve as the initial members of the Apache MXNet Project:

* Anirudh Subramanian <anirudh2290@apache.org>
* Bing Xu <bingxu@apache.org>
* Bob Paulin <bob@apache.org>
* Carin Meier <cmeier@apache.org>
* Chiyuan Zhang <pluskid@apache.org>
* Chris Olivier <cjolivier01@apache.org>
* Dick Carter <dickjc123@apache.org>
* Eric Xie <jxie@apache.org>
* Furkan Kamaci <kamaci@apache.org>
* Haibin Lin <haibin@apache.org>
* Henri Yandell <bayard@apache.org>
* Hongliang Liu <hliu@apache.org>
* Indhu Bharathi <indhub@apache.org>
* Jackie Wu <wkcn@apache.org>
* Jason Dai <jasondai@apache.org>
* Jian Zhang <jianzhangzju@apache.org>
* Joe Spisak <jspisak@apache.org>
* Jun Wu <reminisce@apache.org>
* Leonard Lausen <lausen@apache.org>
* Liang Depeng <ldpe2g@apache.org>
* Ly Nguyen <lxn2@apache.org>
* Madan Jampani <madjam@apache.org>
* Marco de Abreu <marcoabreu@apache.org>
* Markus Weimer <weimer@apache.org>
* Mu Li <muli@apache.org>
* Nan Zhu <codingcat@apache.org>
* Naveen Swamy <nswamy@apache.org>
* Przemysław Trędak <ptrendx@apache.org>
* Qiang Kou <qkou@apache.org>
* Qing Lan <lanking@apache.org>
* Sandeep Krishnamurthy <skm@apache.org>
* Sergey Kolychev <sergeykolychev@apache.org>
* Sheng Zha <zhasheng@apache.org>
* Shiwen Hu <yajiedesign@apache.org>
* Tao Lv <taolv@apache.org>
* Terry Chen <terrychen@apache.org>
* Thomas Delteil <thomasdelteil@apache.org>
* Tianqi Chen <tqchen@apache.org>
* Tong He <the@apache.org>
* Tsuyoshi Ozawa <ozawa@apache.org>
* Xingjian Shi <sxjscience@apache.org>
* YiZhi Liu <liuyizhi@apache.org>
* Yifeng Geng <gengyifeng@apache.org>
* Yu Zhang <yzhang87@apache.org>
* Yuan Tang <terrytangyuan@apache.org>
* Yutian Li <hotpxl@apache.org>
* Zhi Zhang <zhreshold@apache.org>
* Zihao Zheng <zihaolucky@apache.org>
* Ziheng Jiang <ziheng@apache.org>
* Ziyue Huang <ziyue@apache.org>

NOW, THEREFORE, BE IT FURTHER RESOLVED, that Sheng Zha be appointed to
the office of Vice President, Apache MXNet, to serve in accordance with
and subject to the direction of the Board of Directors and the Bylaws of
the Foundation until death, resignation, retirement, removal or
disqualification, or until a successor is appointed; and be it further

RESOLVED, that the Apache MXNet Project be and hereby is tasked with the
migration and rationalization of the Apache Incubator MXNet podling; and
be it further

RESOLVED, that all responsibilities pertaining to the Apache Incubator
MXNet podling encumbered upon the Apache Incubator PMC are hereafter
discharged.
```

**Comment by nswamy** [comment]
```
NOW, THEREFORE, BE IT FURTHER RESOLVED, that Sheng Zha be appointed to
the office of Vice President, Apache MXNet, to serve in accordance with
and subject to the direction of the Board of Directors and the Bylaws of
the Foundation until death, resignation, retirement, removal or
disqualification, or until a successor is appointed; and be it further
```
Until death really ?

**Comment by marcoabreu** [comment]
Apache memberships are for life ☠️😅

**Comment by lanking520** [comment]
Since we are moving towards the graduation. I would also want to check with everyone if we would like to prmote all of our committers to PMC as we graduate. 

Most of the Apache MXNet contriubutors has significant code contribution as well as support on the community. They fixed our issues and maintain the docs to ensure the day2day running of our framework.

**Comment by marcoabreu** [comment]
I definitely think it's a good opportunity to see if have missed recognizing committers that should have been promoted to PPMC. But my understanding is that a graduation is usually not combined with converting committers to PMCs. 

Rather, it seems like TLD projects aim to having a healthy mix of PMCs and committers.

**Comment by josephevans** [comment]
Hi everyone. It's been awhile since the graduation [discussion thread](https://lists.apache.org/thread/3rxzjcmo2y457y6r8ohz1j4qv49joyo6) on general@incubator has been started and there has been very little traffic supporting the effort. Could the MXNet community please help promote graduation by replying to the thread?

**Comment by josephevans** [comment]
The final IPMC vote has been started in the general@incubator list. This is the final step in graduating the project to an Apache top level project. Thanks to everyone for your hard work getting to this point.

https://lists.apache.org/thread/hmd5gyq3xhqn48yqszwjcqx0q5wl7qv6

Please participate in the vote to show your support.

**Comment by josephevans** [comment]
The final IPMC vote has passed. Thanks to the everyone in the Apache MXNet community for all the work to get to this point. We will now submit the resolution to the Apache Board for consideration in the September board meeting.

Voting thread: https://lists.apache.org/thread/hmd5gyq3xhqn48yqszwjcqx0q5wl7qv6

**Comment by TristonC** [comment]
Thank you, @josephevans for leading the effort of the graduation!

**Comment by josephevans** [comment]
Now that the vote has passed, I will create another issue for post-graduation activities to track.
