### ISSUE TITLE
Out of memory issue when training on a small dataset

### ISSUE THREAD

**Issue by dafukua** [apache/incubator-mxnet#2099]
I've got a 16GB RAM machine (i.e., `g2.2xlarge`) with NVIDIA K520 and CUDA 7.5 installed (driver version is 352.93). I was trying to train Inception-BN on a dataset of 15000 images each with size 224x224. After generating the `.rec` file using `im2rec.py`, I mainly used the `train_model.py` with GPU mode, which comes with the `MXNet` package under `examples/image-classification`, to train the Inception-BN model.

However, I kept getting the `what() std::bad_alloc` error, which basically means out of memory. And indeed, while I was monitoring the system memory, the model training ate up all of it. If I decreased the number of training samples down to 10000, the system memory would be ~15GB during model training.

I couldn't figure out what the problem is. Can I know anybody else ever faced such an issue?

By the way, I'm using the latest code (Commit: [b9947a0d6aa96f4d2bad8cd0eedc86e3901285b0](https://github.com/dmlc/mxnet/commit/b9947a0d6aa96f4d2bad8cd0eedc86e3901285b0)).

Thanks in advance.
# 

**Update 1:**

I also tested with CUDA 7.0 (i.e., `cuda_7.0.28_linux.run`) and NVIDIA driver version 346.72 (i.e., `NVIDIA-Linux-x86_64-346.72.run`). As a result, the aforementioned memory issue still exists.

**Comment by martinbel** [comment]
@EasonD3  getting the same in EC2 g2.2.

**Comment by GMarzinotto** [comment]
I'm getting the exact same error, the training eats all my memory.
I'm using CUDA-8.0
NVIDIA GTX950M
Running Ubuntu 16.04
it starts normally and then the OS kills the process after it consumes my 16Gb Memory.

3 threads for decoding..
2016-11-05 18:45:22,940 Node[0] Start training with [cpu(0)]
Killed

Have you found any solution for this issue?

**Comment by martinbel** [comment]
@GMarzinotto I've used another library

**Comment by EasonD3** [comment]
@GMarzinotto I changed to use another lib. But I suspect the issue could be due to the setting of the parameter server. You may try another parameter for that.

**Comment by zhanghan328** [comment]
#4299 Maybe i have the same problem.

**Comment by ysh329** [comment]
I met same problem!

**Comment by KeyKy** [comment]
I have the same problem!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
