### ISSUE TITLE
[RFC] v1.9.1 release

### ISSUE THREAD

**Issue by waytrue17** [apache/incubator-mxnet#21000]
## Problem statement
Dear MXNet community,

After the v1.9.0 release, there are many important bug fixes merged into v1.9.x branch. For example:
- Fix CPP package build when large tensor support enabled #20841,
- Fix security vulnerability in RTC code #20840,
- Fix identity fuse for oneDNN in large graph #20884,
- Fix accuracy issue due to reuse of primitives for MKLDNN-AArch64 #20921,
- Fix sporadic crash issue when closing MXNet #20944,
- Fix security vulnerabilities affecting numpy<1.19.1 #20940,
- Upgrade oneDNN to fix slim convolutions weight issue #20994

Based on these bugfixes, we would like to release a 1.9.1 patch release. If there are any outstanding bugfixes or improvements that you would like to see included, please respond to this thread immediately.

We would like to tag the release on Friday, April 15th, 2022, so any changes should be merged by then.

**Comment by josephevans** [comment]
Thanks, Wei for driving this release. Looking forward to having it
available!

Joe

**Comment by szha** [comment]
Hi there,
I am a security researcher and I have found a DMARC vulnerability which I
reported from this attack. An attacker can spam your users by sending them
email using your website's official email address, kindly forward this to
the development team.
hoping for a bounty for my ethical disclosure of this vulnerability to you.
Waiting for your response.
Always Best Regards
Arslan
