### ISSUE TITLE
[RFC] MXNet Website - ASF Issues

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#21054]
In our incubator discussion to graduate the MXNet project, some website issues were identified by ASF:

https://lists.apache.org/thread/j29jcv0zdkvx7vyy701qnfhnj09fzv8o

Current status of the issues are here: https://whimsy.apache.org/pods/project/mxnet

1. The website is missing a link to the Apache privacy policy
2. The website links to external sites (google-analytics.com and api.rss2json.com.) The second is utilized for our medium blog integration.

**Comment by josephevans** [comment]
In order to solve the external site reference noted by ASF, I am proposing that we remove the "live" Medium blog integration that we currently have on our website to just linking to it. From the [main page](https://mxnet.apache.org/versions/1.9.1/) we will remove the "Latest News" section. We will also remove the "Blog" page (and top-nav link) from the site. We will link to our Medium site at the bottom of the page footer, just like we link to our Github, Youtube and Twitter pages.

Are there any objections to this approach?

**Comment by szha** [comment]
+1 sounds like an acceptible work-around to me.

Thanks Joe!

Sam

﻿On 6/3/22, 11:20 AM, "Joe Evans" ***@***.***> wrote:

    CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you can confirm the sender and know the content is safe.



    In order to solve the external site reference noted by ASF, I am proposing that we remove the "live" Medium blog integration that we currently have on our website to just linking to it. From the [main page](https://mxnet.apache.org/versions/1.9.1/) we will remove the "Latest News" section. We will also remove the "Blog" page (and top-nav link) from the site. We will link to our Medium site at the bottom of the page footer, just like we link to our Github, Youtube and Twitter pages.

    Are there any objections to this approach?

**Comment by josephevans** [comment]
Updated the forum to properly cite Apache MXNet (vs MXNet.) https://discuss.mxnet.apache.org/

Will work on a new logo that includes Apache over the weekend.

**Comment by josephevans** [comment]
Updated the website to clearly show it's an Apache project. Moved Apache links to topnav, as per ASF guidelines.

**Comment by josephevans** [comment]
Also updated the website to no longer use Google Analytics and instead use Apache's installation of Matomo tracker.
