### ISSUE TITLE
Build for Cuda 11.3

### ISSUE THREAD

**Issue by david-waterworth** [apache/incubator-mxnet#21074]
I'm struggling to install `mxnet` side by side with `torch` because neither library appears to provide wheels built against the same version of cuda. The torch LTS and many recent releases support 11.3 and I cannot find any torch release built against 11.2 - on the other `mxnet` only seems to have wheels for 11.2 but not 11.3 or 11.1 (I have issues on my system with 11.0)

The reason is I want to use gluon-ts which depends on both torch and mxnet but I so far I've only managed to install torch with gpu and mxnet as cpu.

It would be nice if there was a 11.3 wheel for the latest mxnext

**Comment by josephevans** [comment]
Hi David, we've recently published MXNet 1.9.1 packages for Cuda 11.0 through 11.7. You can get the 11.3 wheel using the command `pip install mxnet-cu113==1.9.1`.

https://pypi.org/project/mxnet-cu113/

**Comment by Rijulsin** [comment]
Hi @josephevans , I'm unable to import mxnet after using "pip install mxnet-cu113==1.9.1" for installation. The error : 

OSError: libnccl.so.2: cannot open shared object file: No such file or directory
