### ISSUE TITLE
LeNet for matrices of different sizes

### ISSUE THREAD

**Issue by bdlacree** [apache/incubator-mxnet#2107]
Hello! First, I love mxnet, and thanks to all the folks who work and contribute to it.

I have a question about the CNN with LeNet in R. The examples I'm seeing require a 4-d array, where the first two dimensions are the pixel-by-pixel matrix for the images. I'm trying to fit a CNN for text classification, but the documents all have different lengths. I.e., there is no standard dimension for the document matrix. R won't allow for an array of different sizes. 

Is there any way to fit the CNN when the document dataframes are of different row rank? I can try to dream up some kludgey fixes---cropping documents to the size of the doc with the fewest sentences, populating extra rows with zeros, whatever---but these seem problematic. Any suggestions?

Thanks!

**Comment by piiswrong** [comment]
please checkout the lstm_bucketing example
