### ISSUE TITLE
RandomOut Implementation

### ISSUE THREAD

**Issue by ieee8023** [apache/incubator-mxnet#2115]
I've implemented RandomOut as an MXNet monitor. I made a demo notebook for it. Is there a better place to put this? Should I put it in the examples folder and submit a pull request?

https://github.com/ieee8023/NeuralNetwork-Examples/blob/master/mxnet/randomout/randomout-cifar-inception.ipynb

**Comment by tqchen** [comment]
@ieee8023 Glad to see it. We have decided to not add future notebook to the repo to prevent it from exploding. I think you can create a repo on your side, with links to your paper and add a link to https://github.com/dmlc/mxnet/tree/master/example#deep-learning-examples

**Comment by piiswrong** [comment]
This is a creative use of monitor but since you are operating on weight and gradients instead of internals, you actually don't need to use monitor as it can hurt performance.

If you can directly access grad_arrays and param_arrays at each batch_end_callback from batchparam.locals
