### ISSUE TITLE
Building from source with MKL-DNN fails on Fedora37

### ISSUE THREAD

**Issue by comrade62** [apache/incubator-mxnet#21188]
## Description
Building from source with MKL-DNN fails on Fedora37 using (at least) these branches: master and v2.0.0.beta0.rc1 when using the following steps in the offical mxnet doc pages:
- https://mxnet.incubator.apache.org/versions/1.9.1/api/python/docs/tutorials/performance/backend/mkldnn/mkldnn_readme.html#6

### Error Message
In file included from /usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:49,
                 from /repos/mxnet/3rdparty/intgemm/intgemm/types.h:3,
                 from /repos/mxnet/3rdparty/intgemm/intgemm/intgemm.h:45,
                 from /repos/mxnet/3rdparty/intgemm/intgemm/intgemm.cc:1:
In function ‘__m256d _mm512_extractf64x4_pd(__m512d, int)’,
    inlined from ‘float intgemm::AddFloat32(__m512)’ at /home/owner/repos/mxnet/3rdparty/intgemm/intgemm/stats.h:51:34,
    inlined from ‘intgemm::MeanStd intgemm::avx512bw::VectorMeanStd(const float*, const float*, bool)’ at /home/owner/repos/mxnet/3rdparty/intgemm/intgemm/stats.inl:86:33:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:5946:10: error: ‘__Y’ is used uninitialized [-Werror=uninitialized]
 5946 |   return (__m256d) __builtin_ia32_extractf64x4_mask ((__v8df) __A,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5947 |                                                      __imm,
      |                                                      ~~~~~~
 5948 |                                                      (__v4df)
      |                                                      ~~~~~~~~
 5949 |                                                      _mm256_undefined_pd (),
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~~
 5950 |                                                      (__mmask8) -1);
      |                                                      ~~~~~~~~~~~~~~

../mxnet/3rdparty/onednn/src/cpu/x64/shuffle/jit_uni_shuffle_kernel.cpp: In member function ‘void dnnl::impl::cpu::x64::jit_uni_shuffle_kernel_t<isa>::shuffle_blocked_format() [with dnnl::impl::cpu::x64::cpu_isa_t isa = dnnl::impl::cpu::x64::sse41]’:
/repos/mxnet/3rdparty/onednn/src/cpu/x64/shuffle/jit_uni_shuffle_kernel.cpp:297:15: note: object ‘vmm_tmp’ of size 32
  297 |     const Vmm vmm_tmp[4] = {Vmm(5), Vmm(6), Vmm(7), Vmm(8)};
      |               ^~~~~~~
[ 46%] Built target dnnl_cpu_x64
make: *** [Makefile:146: all] Error 2

## To Reproduce
Build from source.

### Steps to reproduce
1. Download the source (git clone --recursive https://github.com/apache/mxnet.git) and switch to dir mxnet
2. Use dev branch (master) or v2.0.0.beta0.rc1
3. mkdir build && cd build
4. cmake -DUSE_CUDA=OFF -DUSE_MKL_IF_AVAILABLE=ON -DUSE_MKLDNN=ON -DUSE_OPENMP=ON -DUSE_OPENCV=ON
5. make -j $(nproc)

## What have you tried to solve it?
Nothing, I have no idea where to start.

## Environment
Fedora 37
Kernel: Linux fedoravm 6.1.15-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  3 17:29:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

<details>
<summary>Environment Information</summary>

```
# Paste the diagnose.py command output here
----------Python Info----------
Version      : 3.11.2
Compiler     : GCC 12.2.1 20221121 (Red Hat 12.2.1-4)
Build        : ('main', 'Feb  8 2023 00:00:00')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 23.0.1
Directory    : /home/owner/.local/lib/python3.11/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-6.1.15-200.fc37.x86_64-x86_64-with-glibc2.36
system       : Linux
node         : fedoravm
release      : 6.1.15-200.fc37.x86_64
version      : #1 SMP PREEMPT_DYNAMIC Fri Mar  3 17:29:44 UTC 2023
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  15
  On-line CPU(s) list:   0-14
Vendor ID:               GenuineIntel
  Model name:            Genuine Intel(R) CPU 0000%@
    CPU family:          6
    Model:               85
    Thread(s) per core:  1
    Core(s) per socket:  15
    Socket(s):           1
    Stepping:            5
    BogoMIPS:            4199.95
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm c
                         onstant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic mov
                         be popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_s
                         hadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushop
                         t clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku ospke md_clear arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   256 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    8 MiB (8 instances)
  L3:                    22 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-14
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Mitigation; Clear CPU buffers; SMT disabled
  Meltdown:              Not affected
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
  Retbleed:              Mitigation; IBRS
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Mitigation; Clear CPU buffers; SMT disabled

</details>

**Comment by comrade62** [comment]
If this can be fixed by downgrading gcc, please advise to which version I should downgrade to as this page (https://mxnet.apache.org/get_started/build_from_source) suggests that all versions above gcc7 should work when building the dev or 2.x versions.

**Comment by vpirogov** [comment]
@comrade62, looks like GCC is barking at it's own `avx512fintrin.h` header included from `3rdparty/intgemm`. This module [is built with](https://github.com/kpu/intgemm/blob/8f28282c3bd854922da638024d2659be52e892e9/CMakeLists.txt#L16) `-Werror` unlike the rest of MXNet. Try disabling it or adding `-Wno-error=unused-variable` like it's done for MXNet iteslf.

A note issued from oneDNN code is benign and should not affect build.

**Comment by comrade62** [comment]
@vpirogov thank you for your response, I mistakenly included just the one error where there was in fact two but once I added to the  compile options "-Wno-error=maybe-uninitialized" it fixed the above error and then also added "-Wno-error=uninitialized" (both) to the file "3rdparty/intgemm/CMakeLists.txt" the build completed successfully, thank you again for your assistance it is very much appreciated.
