### ISSUE TITLE
GoogleNet only has one loss output?

### ISSUE THREAD

**Issue by dafukua** [apache/incubator-mxnet#2148]
The standard GoogleNet tries to minimize three softmax losses, while the GoogleNet in MXNet (as defined in [the symble file](https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_googlenet.py)) only has one softmax loss at the end. Is there any reason for that? Is it simply because one softmax loss leads to almost the same performance compared to the standard?

**Comment by sun9700** [comment]
I have the same question
The googlenet V1 implementation misses two **auxiliary loss**
What's more, the **Local Response Normalization** is missing too。
@mli

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
