### ISSUE TITLE
NDArray Slicing Question

### ISSUE THREAD

**Issue by eaplatanios** [apache/incubator-mxnet#2170]
Hi,

I have not figured out something very simple regarding NDArrays. Let's say I have a 2D NDArray. How do I go about setting the (i,j) element to some value? I am using the Scala package.

Also, I have added support for the reshape operator in my version of the Scala package, but I notice that many operators that exist in the Python package are not yet supported in the Scala package. Do you plan to keep that package up to date or do you focus just on the Python package?

Thanks

**Comment by piiswrong** [comment]
you can't. If you want to operate on single elements convert it to numpy array and back.

Scala package is under development by @javelinjs. It's a work in progress. You are welcome to contribute to it.

**Comment by javelinjs** [comment]
@eaplatanios Could you make a PR for the reshape operator? We are willing to keep scala package up to date, we are just short of hands.

**Comment by eaplatanios** [comment]
@piiswrong Thanks for response! Could you tell me what the main reason is for not supporting accessing single elements or slicing along different axes than 0? Is there some limitation, or is it because of prioritizing other features?

@javelinjs I'm pretty busy with NIPS and the camera-ready deadline for ICML (25th). I've been working on adding more features (e.g., bucketing support) to the Scala package, as well as more documentation. I'll make a PR once I'm done with deadlines. :)
