### ISSUE TITLE
make -j4 error

### ISSUE THREAD

**Issue by n080509** [apache/incubator-mxnet#2174]
make -j4 error
as flow:
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o local_filesys.o src/io/local_filesys.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc
ar crv build/libps.a build/customer.o build/postoffice.o build/van.o build/meta.pb.o
a - build/customer.o
a - build/postoffice.o
a - build/van.o
a - build/meta.pb.o
rm src/meta.pb.h
make[1]: Leaving directory `/home/slave/mxnet/ps-lite'
ln -fs /home/slave/mxnet/ps-lite/tracker .
ln: â€˜./trackerâ€™: cannot overwrite directory
make: *** [/home/slave/mxnet/ps-lite/build/libps.a] Error 1
make: *** Waiting for unfinished jobs....
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
ar cr libdmlc.a line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o
make[1]: Leaving directory`/home/slave/mxnet/dmlc-core'

**Comment by qiaohaijun** [comment]
I think the core of errer is "cannot overwrite directory"

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
