### ISSUE TITLE
Bug in CustomOp

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#2180]
The example `numpy-ops\custom_softmax.py` seems to be broken, it does not training. 

The issue seems to be that `executor.forward` is broken: it never returns. I've tested this on CPU with Python 2.

**Comment by piiswrong** [comment]
Is this before or after you added your changes?

**Comment by sbodenstein** [comment]
I tested this directly on MXNet master without any of my changes.

**Comment by piiswrong** [comment]
For custom to work on cpu, environment variable MXNET_CPU_WORKER_NTHREADS needs to be at least 2
