### ISSUE TITLE
src/operator/operator.cc:19: Cannot find Operator Convolution in registry

### ISSUE THREAD

**Issue by saeedizadi** [apache/incubator-mxnet#2200]
When I try to feedforward an image into a pre-trained model, using MATLAB wrapper, I get the following error. 

`src/operator/operator.cc:19: Cannot find Operator Convolution in registry
`
Any help would be welcome!

**Comment by Piyush3dB** [comment]
Are you able to run the existing Matlab example to begin with?

**Comment by lygstate** [comment]
I also face this problem, running amalgamation Under Win32.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
