### ISSUE TITLE
load symbol error

### ISSUE THREAD

**Issue by lightingghost** [apache/incubator-mxnet#2201]
I want to load symbol from pretrained model, 

`sym = mx.sym.load('auto_sum-symbol.json')`

but I got the error below:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/symbol.py", line 958, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op reshape0 of type Reshape: Invalid Parameter format for shape expect  but value='()'
`

Any hint on what's wrong?

Thanks

**Comment by lightingghost** [comment]
I checked the json file, if deleting the item of `"shape":"()"`, it will be fine. 

Seems to be deprecating issue. I will leave this open for you to see whether it's bug or not.

**Comment by piiswrong** [comment]
@antinucleon Seems to be a default value problem?

**Comment by antinucleon** [comment]
Seems so. Will fix it tonight.

**Comment by melody-rain** [comment]
I got the same problem. 
The network has something like 
`label = mx.symbol.Reshape(data = label, target_shape = (0, ))`

and in the trained model I got
`    {
      "op": "Reshape", 
      "param": {
        "keep_highest": "False", 
        "shape": "()", 
        "target_shape": "(0,)"
      }, 
      "name": "reshape0", 
      "inputs": [[34, 0]], 
      "backward_source_id": -1
    },`

and if I predict with the trained model, I got 
`Failed loading Op reshape0 of type Reshape`

**Comment by freddycct** [comment]
`MXNetError: Failed loading Op reshape0 of type Reshape: Invalid Parameter format for shape expect  but value='()'
`

same problem in examples/rnn/char-rnn.ipynb

**Comment by antinucleon** [comment]
Sorry for delay, will fix it tomorrow.

**Comment by antinucleon** [comment]
In https://github.com/dmlc/mxnet/pull/2342

**Comment by wplct** [comment]
? is  close

 `Traceback (most recent call last):
  File "D:/code/python/jira/mxnet_learn/infer_cnn_ocr.py", line 95, in <module>
    _, arg_params, __ = mx.model.load_checkpoint("cnn-ocr", 1)
  File "C:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.py", line 363, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "C:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 958, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "C:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op reshape0 of type Reshape: Invalid Parameter format for shape expect  but value='()'`

**Comment by wplct** [comment]
20160531_win10_x64_gpu.7z

**Comment by ibyte2011** [comment]
The same problem .Use  20160531_win10_x64_cpu.7z.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
