### ISSUE TITLE
NDArray Data Types

### ISSUE THREAD

**Issue by eaplatanios** [apache/incubator-mxnet#2207]
Hi,

I'm currently working on making several improvements to the Scala package. One issue is that it currently does not handle NDArray dtypes very well. I do not have a clear understanding of these types though. Most API functions deal with floats, but an NDArray can use other types too (?). So, what kind of array pointer does "MXNDArraySyncCopyFromCPU", for example, need in that case. Also, do all interactions happen always in float, independently of the underlying storage type. Could someone please provide some more information so that I can proceed with my improvements to the package?

Thanks!

**Comment by piiswrong** [comment]
most api (including ndarray apis) are agnostic to type. Type is stored in ndarray data structure. Interactions happen with appropriate type (kinda like what happens when you multiple float by int in c++)

**Comment by eaplatanios** [comment]
Thanks a lot for that response! What types are currently supported? I'm
making NDArray a generic class in Scala and I want it to only allow the
supported underlying types.

**Comment by piiswrong** [comment]
float16 32 64 int32 uint8

**Comment by eaplatanios** [comment]
Great thanks! I guess I'll leave float16 support out of the Scala package.

**Comment by eaplatanios** [comment]
Just to clarify something so there are no issues. Let's say we have a float32 array and we call MXNDArraySyncCopyToCPU with an integer array as argument. Will MXNet convert the float32 numbers to integers before copying them into the provided array or will it assume that the provided array complies with the underlying type?
