### ISSUE TITLE
fault tolerance of trained on a GPU cluster

### ISSUE THREAD

**Issue by buptqitian** [apache/incubator-mxnet#2218]
I am wondering when trained on a cluster, if a node was killed with some reason, can the training going on?
I know that, in Mu Li's OSDI'14 paper, parameter server is fault tolerance, which trains on a very large CPU cluster(1000+CPU cores).
But, in deep learning work, GPU is much more important. Maybe there are only  10-20 GPU node, much less than 1000 CPU node.
In mxnet, ps-lite supports training distributed model, is the fault tolerance reserved? 
Or, fault tolerance could be ignored in a small cluster(only 10-20 nodes)?

Thank you!

**Comment by mli** [comment]
the probability for a node failure during training with 10-20 gpu nodes is much slower comparing to 1k cpu node. simple model checkpoint, (already provided), should be good enough

**Comment by eric-haibin-lin** [comment]
Closing it for now due to inactivity. Please feel free to reopen for any follow-up discussions.
