### ISSUE TITLE
A question about shared weights in RNN

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#2222]
Hi, 
I have a question about how weights are shared in RNN unrolled. I notice that since the weights in every timestamp are the same, so these weights are represented by the same variable in the rnn example. My question is when we do back propagation, how the gradients are computed? Since the gradient variables correspond to the arguments, I only get one gradient variable for each weight. So does it mean this gradient is calculated by taking weights in every time stamp in consideration and I only need to update the weight once using this gradient?

**Comment by mavenlin** [comment]
Yes you're right. It follows the mathematical derivation of the gradient.
