### ISSUE TITLE
How to implement this idea by mxnet?

### ISSUE THREAD

**Issue by YuetianLiu** [apache/incubator-mxnet#2224]
The idea that only the k highest activities in the hidden layers are kept and the others are setted to zero. Should I create a new operator in the mxnet? I don't know how to implement it.  Thank you very much.

**Comment by sxjscience** [comment]
Seems like the dynamic k-max pooling (http://arxiv.org/pdf/1404.2188v1.pdf). I think you need to create a new k-max-pooling Op. Refer to the examples in http://mxnet.readthedocs.io/en/latest/how_to/new_op.html, http://mxnet.readthedocs.io/en/latest/system/operator_util.html and also source code https://github.com/dmlc/mxnet/tree/master/src/operator.

**Comment by ilkarman** [comment]
Was curious if you ended up writing one?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
