### ISSUE TITLE
Can python take argument of type ShapeInfo?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [apache/incubator-mxnet#2236]
In this PR, 

https://github.com/dmlc/mxnet/commit/b5a369384e566490211cfb458bc9936d6c2a5678

@antinucleon added a new type `ShapeInfo` 

https://github.com/dmlc/mxnet/commit/b5a369384e566490211cfb458bc9936d6c2a5678#diff-da1f96786394d599a92835e3560928efR29

But it's not registered anywhere, like the following
`DMLC_DECLARE_TYPE_NAME(mxnet::TShape, "Shape(tuple)");`

I wondered how can python recognize/take this data type as an argument?

**Comment by piiswrong** [comment]
python side doesn't care. everything is converted to string. then c++ side parses it as declared in parameter structure

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong 
Even so, I think it's better to register ShapeInfo somewhere, because it gives wrong information when ```MXSymbolGetAtomicSymbolInfo``` is called,  which gives ```optional, default=()```.
No type names, wrong default value.
(if the type is ```Shape```, it will give ```Shape(tuple), optional, default=(1,1)```)

**Comment by piiswrong** [comment]
Ok. Could you propose a PR?

**Comment by zhangchen-qinyinghua** [comment]
I wil try.
