### ISSUE TITLE
Installing with OpenCV support on CentOS 7

### ISSUE THREAD

**Issue by phunterlau** [apache/incubator-mxnet#2244]
eventually got a working solution for CentOS OpenCV support without compiling the source code. I put here for future reference.
1. CentOS with OpenCV
   on Cent OS 7, one needs to install opencv like this

```
yum install opencv opencv-python opencv-devel.i686
```

and the `pkg-config` in CentOS has problem with OpenCV for finding libs, so we need to manually change this line in `Makefile`

```
LDFLAGS += `pkg-config --libs opencv` 
```

to 

```
LDFLAGS += -lopencv_calib3d -lopencv_imgproc -lopencv_contrib -lopencv_legacy -lopencv_core -lopencv_highgui
```

where `pkg-config` may miss the last two.

After changing this, it is safe to use `USE_OPENCV=1` and get `im2rec` compiled.
1. import cv2

For importing `cv2` from python, the current best solution is using `Anaconda`'s `conda install opencv`
if one doesn't want `Anaconda`, one can `pip install opencv` firstly, compile the .so from OpenCV source code, and put to the site-package path.

**Comment by piiswrong** [comment]
does it work if you set `LDFLAGS += -lopencv_calib3d -lopencv_imgproc -lopencv_contrib -lopencv_legacy -lopencv_core -lopencv_highgui` in config.mk's add_ldflags?

Could you send a PR that add this to documentation?

**Comment by phunterlau** [comment]
`pkg-config --libs opencv` gives `-lopencv_calib3d -lopencv_imgproc -lopencv_contrib -lopencv_legacy -l` (note the weird ending `-l` in the parameter), so `LDFLAGS += -lopencv_calib3d -lopencv_imgproc -lopencv_contrib -lopencv_legacy -lopencv_core -lopencv_highgui` may mess up the parameter format. If you have a better solution for removing the weird ending `-l` for `pkg-config`, it would be great.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
