### ISSUE TITLE
A problem about "update" function in Class "CustomMetric"

### ISSUE THREAD

**Issue by Darwin-Lu** [apache/incubator-mxnet#2250]
Hi,
When I customize my metric for the binary classification problem, the shape of "pred" variable fed into my metric function is **(batch_size,)** instead of the expected **(batch_size, 2)**. In my understanding, the pred.shape = **(batch_size, num_class)**
After examining the caller function in Class CustomMetric in the python library, I find there are two incomprehensible code lines in "update" function shown in the red box.
<img width="469" alt="ad56e604-cded-4c1a-abb2-52fa0ed93c6a" src="https://cloud.githubusercontent.com/assets/7271023/15567485/3922839e-2359-11e6-8cb9-9a33595a271a.png">

These codes change the shape of "pred" from (batch_size, 2) to (batch_size,). I are really confused about this behavior. If I have any wrong understanding, please point it out. Much thanks XD.

**Comment by piiswrong** [comment]
I think this is to convert (1-p, p) to (p) for binary classification. But this indeed looks weird and not very general. We should remove it. Could you propose a PR?

**Comment by Darwin-Lu** [comment]
OK, I see. To make the function behavior more consistent, it is indeed better to remove those If no other functions rely on this transformation.
