### ISSUE TITLE
A puzzling question about image-classification example using resnet

### ISSUE THREAD

**Issue by joyivan** [apache/incubator-mxnet#2251]
When I use the symbol_resnet-28-small.py and put my data into the model  that my data is 256x256x3 (256 is the width,3 is the channel).I find in the residual_factory method the second 2n layers when dim_match=False， the code show me that ' conv1 = conv_factory(data=data, num_filter=num_filter, kernel=(3,3), stride=(2,2), pad=(1,1), act_type='relu', conv_type=0)'  I calculated that '(W-F+2P)/S+1' using W=256 F=3 P=1 S=2 the result is (255/2+1=128.5 ) it is not a integer, I think the code will through a error but it works and the model chart show me the mothod transform the data to 128*128 
  why ？？？ Could anyone tell me ?   thanks .
![2016-05-26 16 45 05](https://cloud.githubusercontent.com/assets/11532837/15568968/39add720-2361-11e6-8139-c52640e24f5a.png)

**Comment by piiswrong** [comment]
it's rounded down
