### ISSUE TITLE
Pad should be properly computed in NDArrayIter when handling the last batch using `roll_over`

### ISSUE THREAD

**Issue by dafukua** [apache/incubator-mxnet#2258]
In `NDArrayIter`, I feel when setting `last_batch_handle = roll_over`, the `pad` should be properly computed instead of just returning `0` (see the [`getpad`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L426) function in [`python/mxnet/io.py`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py). This can be done by simply adding one condition to check if `self.last_batch_handle == 'roll_over'` in `getpad`, e.g.:

``` python
def getpad(self):
    if (self.last_batch_handle == 'pad' or self.last_batch_handle == 'roll_over') and \
       self.cursor + self.batch_size > self.num_data:
        return self.cursor + self.batch_size - self.num_data
    else:
        return 0
```

I think this is particularly important when one tries to combine different iters, since the consistency of each iter's `pad` needs to be checked at the end of every epoch.

Please help confirm if checking `self.last_batch_handle == 'roll_over'` is indeed necessary. If so, I'll submit a PR for that.

Thanks.

**Comment by tornadomeet** [comment]
when using 'roll_over' and the last data size is less than the batch size, it will use the front data to pad it, so if it return 0 in getpad(), then it behave the same as 'pad'; so i think it is no need; Or could you give a clear description about your  scene of combine different iters? i do not get the point, myabe i missed something.

**Comment by EasonD3** [comment]
@tornadomeet , please consider the following example, where `iter1` and `iter2` are expected to be combined:
```python
import os
import sys
sys.path.insert(0, '~/mxnet/python')

import mxnet as mx
import numpy as np


def print_iter(iter_):
    #iter_.reset()
    bi = 1
    for b in iter_:
        print '* batch {}: len(data[0]) = {}, b.pad = {}'.format(bi, len(b.data[0].asnumpy()), b.pad)
        print 'data[0]:'
        print b.data[0].asnumpy()
        print ''
        bi += 1


if __name__ == '__main__':
    N = 5
    batch_size = 3

    with open('data.csv', 'w') as f_out:
        f_out.write('\n'.join([str(x+1) for x in range(N)]))
    iter1 = mx.io.CSVIter(data_csv='./data.csv', data_shape=(1,), batch_size=batch_size)
    print '\n- iter1 -\n'
    print_iter(iter1)

    data = np.arange(N) + 1
    data = data[:, np.newaxis]
    iter2 = mx.io.NDArrayIter(data, batch_size=batch_size, last_batch_handle='roll_over')
    print '\n- iter2 -\n'
    print_iter(iter2)
```
The output of the above script is as follows:
```
- iter1 -

* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 1.]
 [ 2.]
 [ 3.]]

* batch 2: len(data[0]) = 3, b.pad = 1
data[0]:
[[ 4.]
 [ 5.]
 [ 1.]]


- iter2 -

* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 1.]
 [ 2.]
 [ 3.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 4.]
 [ 5.]
 [ 1.]]
```

If `iter1` and `iter2` are to be combined by using `PrefetchingIter`, their `pad`s will be checked in [`iter_next()`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L260) in `PrefetchingIter` at the end of every epoch, i.e., as in the current source code:
```python
for batch in self.next_batch:
    assert batch.pad == self.next_batch[0].pad, \
        "Number of entry mismatches between iterators"
```

As in the above example, where we set `last_batch_handle='roll_over'` for `iter2`, `iter2`'s `pad` will always be `0` in the last batch (e.g., batch 2 as shown in the above output), while `iter1`'s `pad` equals to `1`. So the `assert` will raise exception accordingly.

**Comment by tornadomeet** [comment]
@EasonD3  sorry, just to see it now. Yes, in your example, the pad assert in PrefetchingIter will fail. but i think this broken is cased by the two iters do not share the same property which should  follow in the currently PrefetcingIter class. it's better update PrefetcingIter if needed, but not add pad number when using roll_over.

**Comment by EasonD3** [comment]
@tornadomeet , thanks for the reply. If that change should be done in the `PrefetchingIter` class, can you please advise how to make the change? I'd like to keep the customized `PrefetchingIter` somewhat generic (e.g., able to take any iterator), rather than specifically designed for `NDArrayIter` only.

**Comment by tornadomeet** [comment]
if not want to a specific PrefetchingIter, the input two iters should have the same pad number. so you should be careful design the two iters. such as in your example, the data length in iter2 be designed to N, not N+1;

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
