### ISSUE TITLE
Compiling MxNet: Problems with CMake

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#2284]
Hello,
I want to add a new operator to MxNet and for that I need to able to compile the MxNet library. I am running into some problems in the CMake stage and could not build the Visual Studio solution.

I installed the prebuilt MxNet library for Windows and the python package. In addition, I downloaded and extracted the source code for the MxNet. I configured the CMake so that it points to the source code coming from the extracted code.

Firstly, I have installed the OpenCV library: I set the environment variable OpenCV_DIR to the build folder as "C:\Users\ufuk.bicici\Desktop\OpenCV\opencv\build" and I add %OpenCV_DIR% to the Path variable. This stopped CMake to complain about finding OpenCV. 

Then I downloaded the mshadow tensor source code. I extracted the contents under the mshadow folder, which is empty by default in the MxNet source code. CMake seemed happy to see related mshadow .cmake files and errors about mshadow library ceased.

In the next step, I added CUDNN_ROOT environment variable, pointing to "C:\Users\ufuk.bicici\Desktop\cuDNN\cuda\" where the cuDNN,s bin, include and lib folders reside. 

Lastly, I downloaded the OpenBlas library. I placed it in a separate folder at "C:\Users\ufuk.bicici\Desktop\OpenBLAS" and set its environment variable "OpenBLAS_HOME" to this path. But CMake finds an another OpenBlas under the MxNet  installation and it detects where the include files are, under the folder: "C:/Users/ufuk.bicici/Desktop/MxNet/20160419_win10_x64_gpu/3rdparty/openblas/include". This is the folder where the prebuilt package is installed. Then it throws the following error: 

> Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
> CMake Error at cmake/Modules/FindOpenBLAS.cmake:59 (MESSAGE):
>   Could not find OpenBLAS
> Call Stack (most recent call first):
>   mshadow/cmake/mshadow.cmake:13 (find_package)
>   CMakeLists.txt:17 (include)
>   Configuring incomplete, errors occurred!
>   See also "C:/Users/ufuk.bicici/Desktop/MxNet/mxnet-20160419/build/CMakeFiles/CMakeOutput.log".

Looking to FindOpenBLAS.cmake, it seems that the following line fails:
`FIND_LIBRARY(OpenBLAS_LIB NAMES openblas PATHS ${Open_BLAS_LIB_SEARCH_PATHS})`

Despite I set the related OpenBlas environment variable and the needed lib files are in place, CMake refuses to detect lib folder for OpenBLAS and it fails. I am simply stuck at that point. What can be the problem here?  Is there any special steps for OpenBLAS installation that I am missing? Thanks in advance.

**Comment by hjk41** [comment]
The file name for OpenBLAS library is libopenblas.dll.a, which can not be recognized by CMake correctly. I am creating a pull request to handle this correctly. Before the PR is merged, you can manually point OPENBLAS_LIB to the libopenblas.dll.a file.

**Comment by ufukcbicici** [comment]
Changed the related line to:

`FIND_LIBRARY(OpenBLAS_LIB NAMES libopenblas PATHS ${Open_BLAS_LIB_SEARCH_PATHS})`

Unfortunately, this didn't help, the error continues.

**Comment by hjk41** [comment]
Cmake cannot recognize the .a suffix on Windows. So you will need to use
FIND_FILE and specify the full file name.

You can take a look at the PR here:
https://github.com/dmlc/mxnet/pull/1548/files#diff-a16f56795f78049b03a273dcc09b7bc9R38

On Tue, May 31, 2016 at 11:30 PM, ufukcbicici <notifications@github.com>
wrote:

> Changed the related line to:
>
> FIND_LIBRARY(OpenBLAS_LIB NAMES libopenblas PATHS
> ${Open_BLAS_LIB_SEARCH_PATHS})
>
> Unfortunately, this didn't help, the error continues.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2284#issuecomment-222725840>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABFI4XzXJD4cDaXQe1nyonDEms7pIucaks5qHFQcgaJpZM4IpmpP>
> .
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
@ufukcbicici The PR is already merged. You can checkout the latest code and it should be able to find libopenblas.dll.a correctly.
