### ISSUE TITLE
install compile  "cannot find -lnvrtc"

### ISSUE THREAD

**Issue by zhaolei** [apache/incubator-mxnet#2285]
make -j4

`stone@gpu mxnet $ make`
`[  7%] Built target dmlccore`
`Linking CXX shared library libmxnet.so`
`/usr/bin/ld: cannot find -lnvrtc`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [libmxnet.so] Error 1`
`make[1]: *** [CMakeFiles/mxnet.dir/all] Error 2`
`make: *** [all] Error 2`

**Comment by qiaohaijun** [comment]
can you give more info about you os, complier set....?

**Comment by piiswrong** [comment]
1. Pull the most recent code.
2. set USE_NVRTC=0 in config.mk

**Comment by zhaolei** [comment]
I check config.mk "USE_NVRTC = 0  "
I edit "CMakeFiles/mxnet.dir/link.txt"  del "-lnvrtc"

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
