### ISSUE TITLE
Variable batch size (number of samples, the dim1) during forward-backward computation

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#2294]
Hello,

I am working on an architecture which has such a mechanism: Imagine a data batch with N samples. Each sample can have an arbitrary shape. For example, the shape can be 4D (N,a,b,c), the result of a convolution operation or 2D (N,m), the result of a Fully Connected layer. I have an operation, call it F, when applied to an input batch, it determines that n of the N samples in the batch won't be processed by the network further. So, only N-n samples should be propagated through F. The next operation should operate only on N-n samples.  

For example: We place F after a convolution operation. It takes a (N,a,b,c) shaped batch as the input. F determines that n of the samples will be dropped. It selects the N-n relevant samples, packs them into a (N-n,a,b,c) shaped batch and propagates them into the next layer. It should be noted that this is different than Dropout, F deterministically decides which samples to drop.

I am currently able to do that by supressing the dropped samples by using workarounds like multiplying them by zero, blocking their gradients etc. But this leads to a lot of redundant processing time for samples which we won't use and slows down the training immensely.

I wonder if it is possible to build a custom operator which drops such samples online and transfers only the relevant samples to the next layers? I see that each operator needs to implement an infer_shape function, and declares what their input and output shapes will be in advance. In my case, the output shape will be determined as the result of the operator's computation, so I have doubts that this could be implemented straightforwardly. What would you suggest in this case? Does this need a heavy modification of the underlying MxNet library for example? Or could it be implemented by simple CustomOperators somehow?

Thanks.

**Comment by antinucleon** [comment]
The RCNN example is using variable batch size https://github.com/dmlc/mxnet/tree/master/example/rcnn

**Comment by ufukcbicici** [comment]
To be precise, my question is not about variable input size. The input can be, for example, a batch of shape (100,3,200,200), 100 images, 3 channels with 200x200 size each. I am just asking about the possibility of a custom layer, which selects, say 75 of these 100 images according to an inner operation and propagate a (75,3,200,200) shaped batch into the next layer. I do not know "75" in advance, it will determined by the layer itself.

**Comment by antinucleon** [comment]
Sorry for previous short reply, I mean you can do re-binding similar to variable input shape.

**Comment by ufukcbicici** [comment]
How do I do that? Following my previous example, in every iteration, I give a minibatch of size (100,3,200,200), I copy that into the input array, bind it, get the executor, but in the symbolic network, I have my custom operation, which gets (100,3,200,200) as an input and gives (N,3,200,200) as output, where 1 <= N <= 100. N depends on the current minibatch and not known until the forward pass is called. Is this possible to do?

**Comment by antinucleon** [comment]
You may refer the example in RCNN, it is very similar: Input shape is different https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/solver.py#L78

**Comment by ufukcbicici** [comment]
I cannot run the example currently, but I wonder how the input shape is different? What type of data does it process? Does the batch shape change from iteration to iteration?

**Comment by antinucleon** [comment]
Yes. Each batch's input shape is difference. You can either eshape exectuor, or re-bind

**Comment by ufukcbicici** [comment]
But the number of samples (the first dimension) does change DURING the forward-backward passes, right? So, if the minibatch contains 100 samples, all 100 samples are fully processed in that iteration?

**Comment by antinucleon** [comment]
Sorry I missed it at beginning. You can cut your execution graph into two executor: before F and after F. After F, you can use re-bind or reshape. Sample code:
```
sym1 = xxx
sym1 = F(sym1)
sym2 = yyy

exe1 = sym1.bind(...)
exe2 = sym2.bind(...) # need grad for data

for batch in diter:
   exe1.forward(...)
   outputs = exe.outputs()
   exe2 = exe2.reshape() # determined by output shape
   exe2.forward()
   exe2.backward()
   exe1.backward([exe1.grad_dict["data"])
   #sgd
```

**Comment by ufukcbicici** [comment]
Thanks for the answer. In my case, if the network is deep, I can have 2,3, sometimes 4 Fs. I believe this approach would result in a big performance hit then, due to the partial executions and memory copy overheads in between the executions, right?

**Comment by antinucleon** [comment]
No, there won't be big performance hit. All op are async, it will be scheduled automatically instead of running in a queue

**Comment by ufukcbicici** [comment]
Ok, but in order to exe2,exe3, etc to start, exe1 should first execute and prepare its results, so all other executors will be blocked. What will be the benefit of async execution here? All function calls to the MxNet library and initializations will be done in parallel, so the overheads will be hidden, I suppose?

**Comment by antinucleon** [comment]
While running exe2, if it is not blocked manually, exe1 is running on next batch. This is a difference between MXNet and other toolkit. A potential problem for reshape exe in middle is potentially out of memory. So some manual wait_to_read call is necessary. See https://github.com/dmlc/mxnet/issues/2264

**Comment by ufukcbicici** [comment]
I read the issue 2264, it seems the general problem of async execution, since the memory gets being copied continually into the buffers as the forward execution is blocked. I assume this problem appears when the network is too deep and the execution takes too long, so a lot of memory gets allocated while waiting.

**Comment by ufukcbicici** [comment]
A question came into my mind, when I was going through this post again. In the case of aysnc execution, we say that: 

> While running exe2, if it is not blocked manually, exe1 is able to run on next batch

But in order to correctly run on the next batch, the parameters need to be updated with the SGD calculations. So, if exe1 runs on the next batch while exe2 is processing the previous one, exe1 will calculate outdated forward pass results. exe1 should wait for the SGD calculation anyhow. So, everything will be placed in a queue, more or less. How exactly does help async scheduling in that case?

**Comment by antinucleon** [comment]
In this case, while running backprop in exe1 (bottom), it is able to run SGD update in exe2(top). So once full backprop is done, full update is almost done, then we are ready to run next batch.

**Comment by ufukcbicici** [comment]
Thanks for all the answers. I have yet another (hopefully final) question: Let's say we have an input shape of again (100,3,200,200). And let's assume that I have divided the network into two layers: The first layer, containing network F1 is bound to exe1. After exe1 runs on the batch, its output is analyzed and we decide 60 of the output samples will be processed by network F2, represented by exe2 and the remanining 40 will be processed by another network F3, represented by exe3. 

With pseudocode:
`exe1.forward()`
`#Determine which samples go into exe2 and exe3`
`exe2Input = getExe2Input(exe1.outputs)`
`exe3Input = getExe3Input(exe1.outputs)`
`# copy exe2Input and exe3Input into input buffers for exe2 and exe3`
`exe2.forward()`
`exe3.forward()`
`exe2.backward()`
`exe3.backward()`
`#Reshape and pad exe2.grad_dict["data"] into grad2`
`#Reshape and pad exe3.grad_dict["data"] into grad3`
`exe1.backward([grad2])`
`exe1.backward([grad3])`

If 60 samples go into exe2 and 40 into exe3, the last two lines will execute 100 reduntant operations in total since, grad2 will have 40 and grad3 will have 60 zero entries as the result of padding.

My question is, how can we avoid these redundant backward calculations? A naive solution would be rebind two executors, exe1_2 and exe1_3 (encapsulating F1) according to 60 and 40 sample sizes, but in order to calculate gradients with them, we need to execute forward passes as `exe1_2.forward()` and `exe1_3.forward()`. So, for the first layer we execute two forward calculations (the other one is the first `exe1.forward()`). This again introduces redundancy. When we call the first forward() on exe1, actually we calculate all the needed intermediate results for the backward calculations for all 100 samples. To take it short: Is there any way to copy the results of the first `exe1.forward()` into both exe1_2 and exe1_3, such that we can directly call backward() on them, without redundantly executing forward passes?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by guruvishnuvardan** [comment]
@phunterlau - how to define batch size for a video? in mxnet
