### ISSUE TITLE
(info.type) != (kNotInitialized)

### ISSUE THREAD

**Issue by SkidanovAlex** [apache/incubator-mxnet#2317]
Hi,
I'm hitting a bug, for which I can't create a small repro. I have a rather complex model with several LSTMs and attentions mixed up together, and as part of the model I have a `Concat` operation. When I run the model, I hit an error on line 650 in graph_executor.cc: `(info.type) != (kNotInitialized)`. The op that fails is a `Concat` of four inputs, all of shape (1, 200), along the 2-st axis (one-based), with inputs coming from `Embedding` or `FullyConnected` ops, or element wise multiplication.

I added some tracing info:

```
CHECK_NE(info.type, kNotInitialized) << graph_.nodes[nid].name << " i=" << i << " nid=" << nid << " ord=" << ord << " total=" << graph_.nodes[nid].inputs.size() << " shape=" << info.shape << " prev node=" << graph_.nodes[topo_order_[i - 1]].name;
```

(ord is an extra counter that counts iterations of the `for (StaticGraph::DataEntry e : graph_.nodes[nid].inputs) {`)

And this is what I observe:

```
(info.type) != (kNotInitialized) attn_single_concat_backward i=912 nid=910 ord=2 total=4 shape=(1,200) prev node=fullyconnected106_backward
```

Here's where it gets interesting:
1. Note that the `ord=2`, which means that the third input to the Concat op is not initialized. If I swap the first and the third inputs to the `Concat` and rerun it, it still fails on `ord=2`. So it seems like there's nothing wrong with the second input per se, since replacing it with previously working first input still makes it fail on the same ordinal.
2. If I rearrange inputs to the Concat further, sometimes `total` becomes equal to three (in other words, a Concat op that has `num_args=4` somehow only has three inputs?)

I understand that this is not enough information to debug it. So I have some questions that would help me get more info:
1. Inputs to the `*_backward` operations are the inputs to the corresponding symbol, right? If yes, what can explain the fact that I see 3 reported inputs to a Concat op that has `num_args=4`?
2. What is the meaning of `kNotInitialized`? The input to the op is an output of another op. Does it suggest that the corresponding output is somehow unreachable?

**Comment by SkidanovAlex** [comment]
To add an extra data point, that I think is very relevant:

I have a smaller version of the same model that works. Here's a line from the model:

    flow = mx.sym.Concat(in1, in2, in3, in4, num_args=4)

If I change this code to:

    outputs.append(mx.sym.BlockGrad(in3))
    flow = mx.sym.Concat(in1, in2, in3, in4, num_args=4)

It starts hitting the same issue on the `Concat` op. So seems like blocking grads on that particular argument starts breaking stuff. Note that I change it to:

    outputs.append(mx.sym.BlockGrad(in3))
    flow = mx.sym.Concat(in1, in3, in2, in4, num_args=4)

it still fails, and still with `ord=2`, even though the `in3` is not the second argument (with ordinal=1), so it makes me suspect that ordinal has nothing to do with the order of inputs to the `Concat`.

Finally, if I change it to:

    outputs.append(mx.sym.BlockGrad(in2))
    flow = mx.sym.Concat(in1, in3, in2, in4, num_args=4)

Then it does not fail. So it is specific to `in3`. If I block any of `in1`, `in2` and `in4`, it works, but if I block `in3` it breaks. The difference in them that `in1`, `in2` and `in4` come from Embedding and FullyConnected layers, while `in3` comes from a pointwise multiplication of some activations over `SliceChannel` output.

**Comment by piiswrong** [comment]
@tqchen Any ideas?

**Comment by tqchen** [comment]
The last time this happens. I recall it was due to some output of slice
channel not binded for gradient and in gradient construction, the supposed
to be initialized slice channel output gradient was not initialized(
because it did not get binded)

**Comment by piiswrong** [comment]
Can we set gradient input to any unused output to 0?

**Comment by SkidanovAlex** [comment]
@tqchen, it seems relevant, I will try to dig there. I try to `BlockGrad` on all dangling outputs, but might have missed some.
I though, however, that dangling outputs result in errors before the binding starts.

**Comment by SkidanovAlex** [comment]
I confirmed that I have no dangling outputs.

Most interesting thing is that if I replace

    flow = mx.sym.Concat(in1, in2, in3, in4, num_args=4)

with

    flow = mx.sym.Concat(in1, in2, num_args=2)
    flow = mx.sym.Concat(flow, in3, num_args=2)
    flow = mx.sym.Concat(flow, in4, num_args=2)

Then the issue doesn't repro anymore.

I have another issue that might be relevant or not. When I switch to multiple Concats  to get around the `kNotInitialized` error, I hit another issue:

      what():  [15:03:37] src/engine/./threaded_engine.h:306: [15:03:37] src/operator/./embedding-inl.h:85: Check failed: (req[embedding::kData]) == (kNullOp) Embedding layer doesn't support calculate data gradient 1

An extra `1` at the end is my debug output -- it's the actual `type` (and stands for `kWriteTo`). All my `Embedding` layers only accept `mx.sym.Variable` as inputs, so none of their inputs should be `kWriteTo`. However, some of my `Embedding` layers share their inputs. If I duplicate shared inputs (so that each `Variable` is fed to at most one `Embedding`), the issue goes away.

With both hacks in place my models runs, but the fact that the hacks work suggests that both issues are real bugs, and not just a result of me forgetting some dangling outputs.

**Comment by piiswrong** [comment]
@tqchen Looks like implicit copy for branching is not handled correctly for all cases?

**Comment by sxjscience** [comment]
For the second bug, it seems the embedding layer is trying to compute gradient w.r.t the data.

**Comment by tqchen** [comment]
I think @sxjscience could be correct about the second one. Could due to the fact that the gradient aggregations is computed

**Comment by SkidanovAlex** [comment]
@tqchen, so you suggesting that if a certain variable is fed into multiple nodes, the code that handles aggregations automatically marks it as `kWriteTo`, because it will compute an aggregation?

So the fix would be to change that code to recognize that all the nodes that the variable is fed into do not propagate gradient back? Do you know where the code that handles aggregations is located?

**Comment by cemkeskin** [comment]
We also have a very large and complicated model, and we see the same error (info.type) != (kNotInitialized). I checked and it happens for a concat node. 
I'm using the latest master branch, but we have been seeing this error since early March. The same code base was working fine for earlier builds. I believe the last Windows release that didn't have this issue was either 0229 or 0321 (I can check if necessary). 
 I checked the commits since then but nothing strikes me as suspicious. But given Alex's findings above, maybe this information can help?

**Comment by cemkeskin** [comment]
I found a workaround for our case which definitely points to concat being the issue. We were using concat to duplicate a symbol N times on axis 1 (which worked fine for earlier builds but now fails). Now I did the same thing with mx.symbol.broadcast_axis(symbol, axis = 1, size = N) and it worked without any issues. 

So, this fails:
list = []
for _ in range(0, N):
        list.append(symbol)
net = mx.symbol.Concat(*list, num_args = N, dim = 1)

while this works:
net = mx.symbol.broadcast_axis(symbol, axis = 1, size = N)

**Comment by sxjscience** [comment]
My guess is that the concat op cannot handle correctly the case when the inputs contain duplicates? E.g concat(a, b) will be OK but concat(a, a) will be problematic ?

**Comment by cemkeskin** [comment]
Very likely - although it used to work fine. We use concat extensively (without duplicates) but only this one seems to have an issue

**Comment by SkidanovAlex** [comment]
@sxjscience, in my case no input was the same, but some of them depended in the same nodes.  I think toposort somehow screws up such cases.

**Comment by sxjscience** [comment]
@cemkeskin @SkidanovAlex Any update on this issue? I've tested `b = mx.sym.Concat(a, a, num_args=2)` and the backward seems to be correct.

**Comment by SkidanovAlex** [comment]
I hit this issue again. I just started debugging it, and here's some early info: I am using a very simple graph: (array of 33 inputs) => concat of 33 => concat with another input => convolution => fc => softmax

Now, when I get the abovementioned CHECK_NE failure, the offending node is `concat52_backward`, which is the backward node corresponding to the concatenation of 33 inputs. Obviously, the **backward** node is expected to have precisely one input, and that input is expected to point to `concat53_backward`, node corresponding to the second concat in my graph. However instead it has 33 inputs, the first one indeed going into `concat53_backward`, and the remaining 32 going into `concat52_backward`, in other words it has 32 unexpected inputs pointing to itself (effectively creating a loop).

I am trying to figure out where they come from, but may be someone here who knows the code better can give me some pointers or guess possible reasons?

The second concat backward node (`concat53_backward`) has one input, and that input is connected to the convolution, as expected.

**Comment by sxjscience** [comment]
@SkidanovAlex Thanks for your work! It'll be really helpful if you can find a repeatable example.

**Comment by SkidanovAlex** [comment]
The bug I'm hitting right now is in `CreateGradSumNode`. It only reproes if `Concat` concatenates at least 8 nodes (in my original repro I had a concat of 4 nodes, so it is unclear if this is the same issue).

`CreateGradSumNode` introduces edges between its inputs. In my case all those nodes are the same, and thus the connections that are introduced are loops. That code is wrong in a more general case: the inputs to that node might have more complex dependencies, and introducing new edges blindly can in general create loops.

Locally I just set `MXNET_EXEC_INPLACE_GRAD_SUM_CAP` to a larger value, I guess @tqchen is way more qualified than I to fix the fundamental issue.

**Comment by sxjscience** [comment]
@SkidanovAlex Here's the example code I get from your description. Concatenating 8 nodes will trigger the addto optimization. No such problem when `AddTo` is not triggered .
```python
import mxnet as mx
a = mx.sym.Variable('a')
b = mx.sym.Concat(a, a, a, a, a, a, a, a, num_args=8, dim=0)
exe = b.simple_bind(ctx=mx.cpu(), a=(10, 10, 10))
```

Output
```
Check failed: (info.type) != (kNotInitialized)
```

**Comment by sxjscience** [comment]
@piiswrong I find that we still seem to have this bug in the latest master.

**Comment by eric-haibin-lin** [comment]
@sxjscience Does this PR help? #8055

**Comment by eric-haibin-lin** [comment]
#8055 fixes the example test case @sxjscience provides. I'm gonna close it for now. Feel free to reopen it
