### ISSUE TITLE
MxNet (pre-built packages) in Windows 10 cannot import mxnet following README

### ISSUE THREAD

**Issue by gd-zhang** [apache/incubator-mxnet#2372]
import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program\Python\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet__init__.py", line 7, in <module>
    from .base import MXNetError
  File "D:\Program\Python\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "D:\Program\Python\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "D:\Program\Python\lib\ctypes__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "D:\Program\Python\lib\ctypes__init__.py", line 351, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by phunterlau** [comment]
Do you use 64bit or 32 bit Windows?

**Comment by jellyzhang** [comment]
64bit

Guodong Zhang
College of Information Science and Electronic Engineering
Zhejiang University, Hangzhou, China
Mobile: 86 15868865328
Email: jelly_zhang@zju.edu.cn

**Comment by Answeror** [comment]
Please ensure your Python and MxNet are both 64bit.
Personally, I recommend to use 64bit Anaconda2 on Windows platform.

**Comment by jellyzhang** [comment]
@Answeror Have you successfully used pre-built packages? Both my mxnet and python are 64bit. But I don't have cudnn64_70.dll, does it cause the failure?

**Comment by juliandewit** [comment]
What usually works is to :
Use this tool : http://www.dependencywalker.com/
With the tool, select libmxnet.dll in the directory where mxnet is installed. (site-packages\mxnet-0.7.0-py3.4.egg\mxnet)

It almost always shows you dll's that it cannot find.
You need cudnn.

**Comment by Answeror** [comment]
I haven't tried MxNet on Windows. It seems cuDNN is the cause. I recommend @juliandewit's solution.

**Comment by freddycct** [comment]
You are probably missing some dlls in your PATH environment.
I solved the problem I had by using 
`C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\dumpbin.exe `
to check which dependent dll is missing.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
