### ISSUE TITLE
Predicting with random crop and average

### ISSUE THREAD

**Issue by phunterlau** [apache/incubator-mxnet#2373]
Do we have some examples of predicting with `rand_crop=True` and averaging the prediction using .rec format and ImageIO? 

For example, I have a trained network on 480x360 images from StateFarm competition using inception-bn (random crop to 224x224), and I want to predict my dataset on 480x360 images. Currently I am looping for each image, random cropping 100x times on the fly, predicting on each crop and averaging the result. It is too slow since I have about 80k test images. I am wondering if MXnet support batch prediction with random crop + average on .rec files. I see a similar issue #1402 which suggests "Subclass DataIter", can you provide some examples for it? Thanks.

**Comment by mli** [comment]
i guess you can predict the 80k test images by 100 times to set rand_crop=True for each test. then do average.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
