### ISSUE TITLE
using ‘../notebooks/predict-with-pretrained-model.ipynb ’ failed

### ISSUE THREAD

**Issue by zhenzhen1022** [apache/incubator-mxnet#2382]
I just start build MXnet and I have one problem need your help. I predicted using the trained model, that was provided in examples, the model trained done,however the file 'predict-with-pretrained-model.ipynb' has one mistake:../notebooks/predict-with-pretrained-model.ipynb: line 237: syntax error: unexpected end of file.while I used gedit command to check the mistake and I found that there were no line 237. so I don't what wrong here. Did anyone occur the same problem? pls share me ur solution, thx so much.

**Comment by zhenzhen1022** [comment]
the coding style is ASCII, but when I use "cat -A ../notebooks/predict-with-pretrained-model.ipynb", at end of each line, there is a '$'. So this not the encoding fault,but what's wrong?

**Comment by sxjscience** [comment]
You need to use `ipython notebook` or `jupyter notebook` to open these notebook files.

**Comment by zhenzhen1022** [comment]
Thx for your advice. yes, I can open the file with jupyter notebook, but I am confused, I can't solve my problem, can you explain more details.

**Comment by sxjscience** [comment]
@zhenzhen1022 To run the notebook, you need to click the `running` button on the notebook page.

**Comment by zhenzhen1022** [comment]
no, I have tried your advice,but result out 'model' is not exist, however, I have trained. So any advice? and I have an another question, if I have trained one model, would I have to train it next time? and if not ,where the trained model saved? THX　so much! @sxjscience

**Comment by zhenzhen1022** [comment]
how to use ipython notebook or jupyter notebook efficiently?THx !

**Comment by sxjscience** [comment]
@zhenzhen1022 You can try to run the code blocks one by one and analyze the outputs.

**Comment by zhenzhen1022** [comment]
yes, I see. and I have trained cifar10-py like this' python train_cifar10.py --batch-size 128 --lr 0.1 --lr-factor .94 --num-epoch 50'  so ipython notebook is just to tell us how to use mxnet or we can directly run our model and predict?

**Comment by sxjscience** [comment]
You can use ipython notebook to do that.

**Comment by zhenzhen1022** [comment]
yeah, I did so, I have run the code step by step, at the end is 
'# Predict as normal
global_pooling_feature = feature_extractor.predict(test_dataiter)
print(global_pooling_feature.shape)'
but I didn't see any print info, so what's the problem?

**Comment by CNevd** [comment]
run   python train_cifar10.py --batch-size 128 --lr 0.1 --lr-factor .94 --num-epoch 50 --save-model-prefix "cifar10_model"   to save your model first

**Comment by zhenzhen1022** [comment]
oh,yeah,thx so much! I think I have trained by run python train_cifar10.py --batch-size 128 --lr 0.1 --lr-factor .94 --num-epoch 50 without saving the model. and thx for your help, now i can use 'cifar10.ipynb' step by step and predict successfully. and the next is I need to find out the predict result, as i know in mxnet the format of images is '.rec', so what's the output format, and what I need to do to convert to one format such as '.jpg' or '.bmp', that represent the result we can see directly? waiting for your help, THx.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
