### ISSUE TITLE
Windows binary release incompatibilties new observation

### ISSUE THREAD

**Issue by juliandewit** [apache/incubator-mxnet#2386]
Hello,
I got a system with 2 GPU cards. A titan X and a 970.
When I select gpu(0) everything works but when I select gpu(1) (the 970) I get the same behaviour as In [issue 2045](https://github.com/dmlc/mxnet/issues/2045) which is no learning.

Might this help in finding this problem ?

**Comment by wdx04** [comment]
I observed the similar situation today, I have a GTX970(gpu0) and a GTX750Ti(gpu1) on a same machine. With libmxnet.dll in 20160531_win2012_x64_gpu.7z, both GPUs do not work, but with libmxnet.dll in 20160531_win10_x64_gpu.7z, GTX970(gpu0) works but GTX750Ti(gpu1) still does not work.

**Comment by sxjscience** [comment]
@wdx04 Could you help build from source and check if the problem persists? I have only one GPU on my windows computer so I cannot check this. To build from source, you can follow http://mxnet.readthedocs.io/en/latest/how_to/build.html#building-on-windows . Also, the following CMake command may help:

```
cmake -G "Visual Studio 12 2013 Win64" ^
-DCMAKE_BUILD_TYPE=Release ^
-DCMAKE_CONFIGURATION_TYPES="Release" ^
-DMKL_INCLUDE_DIR="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016\\windows\\mkl\\include" ^
-DMKL_RT_LIBRARY="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016\\windows\\mkl\\lib\\intel64\\mkl_rt.lib" ^
-DOpenCV_DIR="E:\ThirdParty\opencv-3.1\opencv\build\x64\vc12\lib" ^
-DCUDNN_INCLUDE="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\include" ^
-DCUDNN_ROOT="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\lib\\x64" ^
-DBLAS=MKL ..
```

**Comment by wdx04** [comment]
@sxjscience I have compiled libmxnet.dll from the latest source, it works for both gpu0 and gpu1 on my macine:
http://pan.baidu.com/s/1dFrzQet

**Comment by yajiedesign** [comment]
you can downlaod in https://github.com/yajiedesign/mxnet/releases. i build windows binary release every day

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
