### ISSUE TITLE
src/io/iter_image_recordio.cc:56: Check failed: p != end Bad ImageList format.

### ISSUE THREAD

**Issue by onthehilluu** [apache/incubator-mxnet#2393]
I experienced the same issue mentioned by   ContinuedStory:
https://github.com/dmlc/mxnet/issues/1411#issuecomment-181156093
Any hints?

Thanks!

**Comment by tornadomeet** [comment]
maybe it's your `label_width` in rec is not consist with your io code.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
