### ISSUE TITLE
A runtime error when training my own FCN model

### ISSUE THREAD

**Issue by fangyizhang** [apache/incubator-mxnet#2395]
I am training my own FCN model, below is my model. I also change some codes in other files to accommodate my model. The error below will occur after a few batches, and it was random, so I don't know how to find this bug. Please help! 

def get_fcn_fuse(workspace_default=1024, shape=(1,1,500,375)):
    input = mx.symbol.Variable('data')
    # group 1
    conv1_1 = mx.symbol.Convolution(data=input, kernel=(3, 3), pad=(1, 1), num_filter=64,
                workspace=workspace_default, name="conv1_1")
    relu1_1 = mx.symbol.Activation(data=conv1_1, act_type="relu", name="relu1_1")
    conv1_2 = mx.symbol.Convolution(data=relu1_1, kernel=(3, 3), pad=(1, 1), num_filter=64,
                workspace=workspace_default, name="conv1_2")
    relu1_2 = mx.symbol.Activation(data=conv1_2, act_type="relu", name="relu1_2")
    pool1 = mx.symbol.Pooling(data=relu1_2, pool_type="max", kernel=(2, 2), stride=(2,2), name="pool1")
    deconv1 = mx.symbol.Deconvolution(data=pool1, kernel=(4, 4), stride=(2, 2), num_filter=2, pad=(0, 0),
                workspace=workspace_default, name="deconv1")
    deconv1 = mx.symbol.Crop(*[deconv1, input], name="crop1", center_crop=True)

```
# group 2
conv2_1 = mx.symbol.Convolution(data=pool1, kernel=(3, 3), pad=(1, 1), num_filter=128,
            workspace=workspace_default, name="conv2_1")
relu2_1 = mx.symbol.Activation(data=conv2_1, act_type="relu", name="relu2_1")
conv2_2 = mx.symbol.Convolution(data=relu2_1, kernel=(3, 3), pad=(1, 1), num_filter=128,
            workspace=workspace_default, name="conv2_2")
relu2_2 = mx.symbol.Activation(data=conv2_2, act_type="relu", name="relu2_2")
pool2 = mx.symbol.Pooling(data=relu2_2, pool_type="max", kernel=(2, 2), stride=(2,2), name="pool2")
deconv2 = mx.symbol.Deconvolution(data=pool2, kernel=(8, 8), stride=(4, 4), num_filter=2, pad=(0, 0),
            workspace=workspace_default, name="deconv2")
deconv2 = mx.symbol.Crop(*[deconv2, input], name="crop2", center_crop=True)

# group 3
conv3_1 = mx.symbol.Convolution(data=pool2, kernel=(3, 3), pad=(1, 1), num_filter=256,
            workspace=workspace_default, name="conv3_1")
relu3_1 = mx.symbol.Activation(data=conv3_1, act_type="relu", name="relu3_1")
conv3_2 = mx.symbol.Convolution(data=relu3_1, kernel=(3, 3), pad=(1, 1), num_filter=256,
            workspace=workspace_default, name="conv3_2")
relu3_2 = mx.symbol.Activation(data=conv3_2, act_type="relu", name="relu3_2")
conv3_3 = mx.symbol.Convolution(data=relu3_2, kernel=(3, 3), pad=(1, 1), num_filter=256,
            workspace=workspace_default, name="conv3_3")
relu3_3 = mx.symbol.Activation(data=conv3_3, act_type="relu", name="relu3_3")
pool3 = mx.symbol.Pooling(data=relu3_3, pool_type="max", kernel=(2, 2), stride=(2,2), name="pool3")
deconv3 = mx.symbol.Deconvolution(data=pool3, kernel=(16, 16), stride=(8, 8), num_filter=2, pad=(0, 0),
            workspace=workspace_default, name="deconv3")
deconv3 = mx.symbol.Crop(*[deconv3, input], name="crop3", center_crop=True)

result = deconv1 + deconv2 + deconv3
softmax = mx.symbol.SoftmaxOutput(data=result, multi_output=True, name="softmax")

return softmax
```

[22:11:20] /home/jf/mxnet/dmlc-core/include/dmlc/logging.h:235: [22:11:20] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
[22:11:20] /home/jf/mxnet/dmlc-core/include/dmlc/logging.h:235: [22:11:20] src/engine/./threaded_engine.h:306: [22:11:20] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [22:11:20] src/engine/./threaded_engine.h:306: [22:11:20] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)

**Comment by tornadomeet** [comment]
@fangyizhang  you can use cpu model to debug it first.

**Comment by feiyulv** [comment]
@fangyizhang Have you solved this problem? I met this random error too, when I trained fully cnn with mutable data shape.

**Comment by fangyizhang** [comment]
@feiyulv Nope, hard to solve

**Comment by xinghedyc** [comment]
Hi 
I got an error when training fcn32s, cpu and gpu mode got the same error.
log:
INFO:root:Namespace(epoch=74, init_type='vgg16', model='fcn32s', prefix='VGG_FC_ILSVRC_16_layers', retrain=False)
INFO:root:Start training with gpu(0)
[17:19:00] /home/dyc/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:19:00] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
[17:19:00] /home/dyc/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:19:00] src/engine/./threaded_engine.h:306: [17:19:00] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [17:19:00] src/engine/./threaded_engine.h:306: [17:19:00] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)

**Comment by xinghedyc** [comment]
@tornadomeet I've checked the code, line 91 in solver.py :
pred = mx.nd.array(output_buff["softmax_output"].asnumpy().reshape(pred_shape[0], \
                    pred_shape[1], pred_shape[2]*pred_shape[3]))
may be the problem.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
