### ISSUE TITLE
Does mxnet support float-matrix inputs?

### ISSUE THREAD

**Issue by alecwangcq** [apache/incubator-mxnet#2399]
Hi all, each sample is a M*N matrix, and all the elements in the matrix are float numbers.
Also, the label of each sample is a real vector (i.e.  [1.0, 1.2, 2.2, 0.5, -1.2,...]). 
So how to convert such data into the data that mxnet supports?
Note: My training data is roughly 200G.

**Comment by sxjscience** [comment]
@AlecWong Seems like a simple regression problem? MXNet supports this kind of data/label combination. To get full customization, you can
1: define your own data iterator to handle such kinds of data. 
2: use lower level forward/backward APIs provided in `mx.mod.Module`

**Comment by AlecWong** [comment]
@sxjscience Yes, it can be regarded as a simple regression problem.   Can you be a bit more specific about  

>  "MXNet supports this kind of data/label combination"

?

**Comment by sxjscience** [comment]
@AlecWong I mean MXNet supports arbitrary NDArray shape for data/label. Documents of the module APIs may be helpful. Refer to http://mxnet.readthedocs.io/en/latest/packages/python/module.html
