### ISSUE TITLE
Pastalog integration

### ISSUE THREAD

**Issue by tmatas** [apache/incubator-mxnet#2419]
Would it be useful to integrate [Pastalog](https://github.com/rewonc/pastalog) as a real-time logging tool?
Seems like the integration should be extremely fast

**Comment by thirdwing** [comment]
I think this can be done by adding a callback function.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
