### ISSUE TITLE
How can I load my own data (not images) into MXNet?

### ISSUE THREAD

**Issue by tokyolearninng** [apache/incubator-mxnet#2421]
Hi all, I am confronting with a problem on how to load my own data into MXNet? My data is the features extracted from audio files. Mx(N+1) (M is the instances for training, N is the numbers of features, (N+1)th stores the labels of each instance for training). Since the most documents are designed for images, not for normal data. Anyone knows how to simply load the external data into MXNet? Thanks a lot!

**Comment by Godricly** [comment]
check [bucketing](http://mxnet.readthedocs.io/en/latest/how_to/bucketing.html) example for variant length under example/rnn. I didn't see any difference between yours case and image as u didn't mention the time length of each instance.

**Comment by tokyolearninng** [comment]
Hi, thanks! However, I am not using sequence learning method like RNN. My case is, 1. I have already extracted features from audio files, the features are the data ready for training; 2. Each instance has 384 features; 3. For each instance, the feature numbers (length) are the same: 384. Thus, I just want to import such a data into MXNet for training. Thanks!

**Comment by Godricly** [comment]
well.Thats easier for you now. U can still follow the bucketing example without caring about the bucket_key.

**Comment by tokyolearninng** [comment]
Hi, I have tried bucketing, but my case seems not same as words training. Let me put it simply:
here we want to train a very Simple 3-layer MLP like the example below:
''using MXNet
fc1  = mx.FullyConnected(data = data, name=:fc1, num_hidden=128)
act1 = mx.Activation(data = fc1, name=:relu1, act_type=:relu)
fc2  = mx.FullyConnected(data = act1, name=:fc2, num_hidden=64)
act2 = mx.Activation(data = fc2, name=:relu2, act_type=:relu)
fc3  = mx.FullyConnected(data = act2, name=:fc3, num_hidden=10)
mlp  = mx.SoftmaxOutput(data = fc3, name=:softmax)...''
our matrix data is already there, so how to feed it into the neural network? We are beginners of MXNet, so we want to need a simple script to tell us how to feed our own data simply to the network. Thanks a million!

**Comment by Godricly** [comment]
check if these 2 help you.
[io_util.py](https://github.com/dmlc/mxnet/blob/master/example/speech-demo/io_util.py)
[data_iter.py](https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/data_iter.py)
@sxjscience Do you know where the standard data_iter tutorial is? Bucketing is a little hard for beginners but I can't find any better tutorial.

**Comment by sxjscience** [comment]
@tokyolearninng You can try to directly bind the symbol and use low-level APIs (`forward` + `backward`). https://github.com/dmlc/mxnet/blob/master/example/notebooks/simple_bind.ipynb and https://github.com/dmlc/mxnet/blob/master/example/adversary/adversary_generation.ipynb are good examples. Also, the first notebook contains example about how to use `NDArrayIter`. You can also load your data into an `NDArrayIter` and call high-level APIs like `fit` for training.

**Comment by Godricly** [comment]
I think [example/python-howto/data_iter.py](https://github.com/dmlc/mxnet/blob/master/example/python-howto/data_iter.py) should be renamed. It is so misleading.

**Comment by tokyolearninng** [comment]
Thanks a lot! However, we tried the tutorial method, but it didn't work. It seems like API issues in MXNet. We put our data, and the python script shared here (the data is downloaded from website, and without copyright issues):
https://www.dropbox.com/s/wf9124aruymat0z/mxnet_study.zip?dl=0
Could you kindly help us check it, and give a simple example code to start MXNet with our data?
Thanks a million!

**Comment by Godricly** [comment]
Can you post the log here? 
Can you try sth like this to see if your iter works.
```python
for batch in Nditer:
    print batch
```

the dropbox is blocked within GFW. :trollface:

**Comment by tokyolearninng** [comment]
Hi, Thanks! We checked the MXNet tutorial books, and thinking that it might be iter problem. The log is as:
*******************************************************************************************************************
Traceback (most recent call last):
  File "mxnet_start.py", line 73, in <module>
    batch_end_callback = mx.callback.Speedometer(batch_size, 200))  # Logging module to print out progress
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(100,1), inferred shape=(100,)
***********************************************************************************************
BTW, the data is not big, if convenient, we could send our data to you by an E-mail?

**Comment by Godricly** [comment]
Is your label a 2d numpy array with label width 1? try reshape it as 1d array.

**Comment by tokyolearninng** [comment]
Hi, here is our data structures shown in Python:
![temp](https://cloud.githubusercontent.com/assets/19944091/16141129/0995e67a-3493-11e6-81dc-00b9becbe758.PNG)

**Comment by Godricly** [comment]
You network has problem when infering its input output shapes, so please double check to make sure their dimensions and sizes are same.

**Comment by tokyolearninng** [comment]
@Godricly Thanks a lot! We have solved the problem, when training a multi-layer neural network, we need to reshape the labels from (8000,1) to (8000,)...But when we further steps in CNN, the problem comes like:
******************************************************************************************************************
Traceback (most recent call last):
  File "cnn_start.py", line 88, in <module>
    batch_end_callback = mx.callback.Speedometer(batch_size, 200))  # Logging module to print out progress
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:18:15] src/symbol/symbol.cc:126: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]conv1_weight
	[2]conv1_bias
	[3]bn1_gamma
	[4]bn1_beta
	[5]conv2_weight
	[6]conv2_bias
	[7]bn2_gamma
	[8]bn2_beta
	[9]fc2_weight
	[10]fc2_bias
	[11]sm_label
********************************************************************************************************************
We re-check some notes in community, but it seems like other users also have such problem when using CNN. Could you find the problem? Maybe still caused by format of labels? We defined labels as in Multi-layer NN.

**Comment by Godricly** [comment]
Is your softmax_out layer name sm? try changing it as softmax and see if works. I'm not quite sure about the reason. The softmax might be the default setup for sth. @sxjscience

**Comment by tokyolearninng** [comment]
Hi, thanks again! But now backing to MLP, we set up a 3-layer MLP for our task. However, the results are very low, accuracy is around 10.0%, compared with SVM's, 90.0%. We'r not sure if we made some mistakes (overfitting?), because when training in MATLAB with a sam 3-layer MLP, it can achieve around 70.0%. How do you suggest to do with MXNet settings if we wanna a better results?

**Comment by Godricly** [comment]
First thing is to check if your data iter giving correct data format as you implemented by urself. Second is to check the MLP setup. Then plot the training and validation curve given the same setup u had in Matlab, I hope u can get sth in this step by comparing them. The worst situation is to debug each layer one by one, I hope you don't have to do this. If you come to this last situation, pycharm is a good choice according to my experience.

**Comment by tokyolearninng** [comment]
Thanks! It's the problem caused by unsuitable network structure. Now we r trying auto-encoders. However, we r wondering if we can use multiple GPUs within MXNet on training auto-encoders.
But when we read the examples, we found that, what is the rule to use multiple GPUs here?
*******************************************************************************************************
ae_model = AutoEncoderModel(mx.gpu(0), [784,500,500,2000,10], pt_dropout=0.2,
        internal_act='relu', output_act='relu')

**Comment by Godricly** [comment]
theres a parameter named context which specifies the devices you are using. U can find a [train_model.py](https://github.com/Godricly/mxnet/blob/master/example/image-classification/train_model.py) file in example/img-classification. Read it and you can get some idea.

**Comment by tokyolearninng** [comment]
Thanks! We have tried using context, however it doesn't work, and the error information is:
*************************************************************************************
Traceback (most recent call last):
  File "big_birds_auto_encoder_temp.py", line 43, in <module>
    internal_act='relu', output_act='relu')
  File "/home/Kun/tokyo_tech_project/model.py", line 45, in __init__
    self.setup(*args, **kwargs)
  File "/home/Kun/tokyo_tech_project/autoencoder.py", line 39, in setup
    sparseness_penalty, idropout, odropout, encoder_act, decoder_act)
  File "/home/Kun/tokyo_tech_project/autoencoder.py", line 75, in make_stack
    args = {'encoder_%d_weight'%istack: mx.nd.empty((num_hidden, num_input), self.xpu),
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/ndarray.py", line 502, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/blackbird/opt/lib/python3.5/site-packages/mxnet-0.5.0-py3.5.egg/mxnet/ndarray.py", line 61, in _new_alloc_handle
    ctypes.c_int(ctx.device_typeid),
AttributeError: 'list' object has no attribute 'device_typeid'
**********************************************************************************************************************
do you know how to fix this problem? Thanks!

**Comment by Godricly** [comment]
Sry ..I don't know...The lstm example under rnn might be helpful.

**Comment by lavenderGit** [comment]
@tokyolearninng Can you share your code to load non-image data for a MLP case in MXNET? Thank you!

**Comment by sxjscience** [comment]
Close it now. Feel free to reopen it.
