### ISSUE TITLE
Is there something wrong when full-connected layer calculate its gradient of weight?

### ISSUE THREAD

**Issue by quanzongfeng** [apache/incubator-mxnet#2427]
In full_connected-int.h, Backward function, we see:

```
Tensor<xpu, 2, DType> gwmat = in_grad[fullc::kWeight].get<xpu, 2, DType>(s);
Assign(gwmat, req[fullc::kWeight], dot(grad.T(), data));
```

When we train models with batch size(m),  gwmat is the gradient of sum of m's gradient. 
Why not gwmat = dot(grad.T(), data)/m ?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
