### ISSUE TITLE
Support optional target_shape in Deconv/Conv

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#2428]
Recently I have been playing around the deconv operators for generative models. I find that it was quite hard to manually construct the deconv operator with desired shapes through pad and stride parameter.

Due to the constraint in current shape inference formula, there are some configurations that are not yet possible, e.g. start from 4x4 feature map, use 3x3 convolution and stride=2 cannot get to 8x8 feature map(need pad from one side but not the other).

I am proposing adding a target_shape parameter to specify the desired output feature maps that can be used exclusively with the pad parameter. When presented, the target_shape will be used to calculate the desired shapes. This of course cannot be abused, and an error can be raised when target_shape was not reasonable during shape inference.

target_shape will default to empty, so things will be backward compatible

I need to confirm the several questions
- Can we directly generalize the implementation of deconv to this setting? e.g. . start from 4x4 feature map, use 3x3 convolution and stride=2  get to 8x8 
- Anyone who want to add this extension.

@piiswrong @tornadomeet

**Comment by tornadomeet** [comment]
@tqchen yes, it is not convenient  to desire the output shape currently.

for above  two questions:   
1. yes, we can do it after add the output pad parameters, like in torch(namely adjW and adjH): https://github.com/torch/nn/blob/master/doc/convolution.md#spatialfullconvolution;  
2.  i'm glad to add this this weekend. i'll try to add target_shape and adj to deconv, then user can use its own pad, adj to desire the output shape, or just passed into data_shape, and the program will do it automatically.

**Comment by tqchen** [comment]
This would be great! @tornadomeet
