### ISSUE TITLE
Is this a bug? im2rec using opecv  resize () function to reduce image 

### ISSUE THREAD

**Issue by zxfzqf** [apache/incubator-mxnet#2429]
# im2rec.py about reduce image :

```
def image_encode(item, q_out):
        try:
            img = cv2.imread(os.path.join(args.root, item[1]), color_modes[args.color])
        except:
            print 'imread error:', item[1]
            return
        if img == None:
            print 'read none error:', item[1]
            return
        if args.center_crop:
            if img.shape[0] > img.shape[1]:
                margin = (img.shape[0] - img.shape[1])/2;
                img = img[margin:margin+img.shape[1], :]
            else:
                margin = (img.shape[1] - img.shape[0])/2;
                img = img[:, margin:margin+img.shape[0]]
        if args.resize:
            if img.shape[0] > img.shape[1]:
                newsize = (img.shape[0]*args.resize/img.shape[1], args.resize)
            else:
                newsize = (args.resize, img.shape[1]*args.resize/img.shape[0])
            img = cv2.resize(img, newsize)
        header = mx.recordio.IRHeader(0, item[2], item[0], 0)

        try:
            s = mx.recordio.pack_img(header, img, quality=args.quality, img_fmt=args.encoding)
            q_out.put(('data', s, item))
        except:
            print 'pack_img error:',item[1]
            return  

```

> Python: cv.Resize(src, dst, interpolation=CV_INTER_LINEAR) → None
> Parameters:  
> dsize –
> output image size; if it equals zero, it is computed as:
> 
> \texttt{dsize = Size(round(fx*src.**_cols**_), round(fy*src.**rows**))}
> 
> Either dsize or both fx and fy must be non-zero.

cv2.imread function return about image shape  first  is cols (height ),so……
For example ，Im2rec will be the resolution of the 900x1200 image, in the input parameters of resize 90, the picture is reduced to 120X90, but the actual should be 90x120

This is a bug? Or did I use the wrong method?

**Comment by freddycct** [comment]
I talked about it here
#1963

**Comment by zxfzqf** [comment]
Sorry to bother you.I don't have to search for it .
Thank you.

**Comment by zxfzqf** [comment]
Sorry to bother you. I don't have to search for it .
Thank you

**Comment by sxjscience** [comment]
@piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
