### ISSUE TITLE
Intel DAAL Layers

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#2435]
Intel is releasing highly optimized CPU network layers via its open-sourced DAAL library. The [beta has been released](https://01.org/daal/blogs/kmoffat/2016/intel%C2%AE-daal-2017-beta-update-1-now-available-1), and the layer types available can be seen [here](https://github.com/01org/daal/tree/b01433b921b2a0a99f11bf83922109ee1f05d7f9/include/algorithms/neural_networks/layers).

Supporting this seems like a very useful improvement.

Edit: [here](https://software.intel.com/en-us/articles/single-node-caffe-scoring-and-training-on-intel-xeon-e5-series-processors) are some performance numbers given by Intel, and a [discussion](https://github.com/soumith/convnet-benchmarks/issues/59).

**Comment by antinucleon** [comment]
I think there are several issues:

It is specialized for PC. If we use these, we can't make it run on ARM. So if we are going to support it under current code template, the device types will be like: ```cpu, gpu, intel_cpu```, which seems a little bit strange, and redundant. Together with OpenCL issue, I think we may do a refactor on operator together with symbol.

@tqchen

**Comment by sbodenstein** [comment]
Can't it work exactly like cuDNN layers, where you can disable/enable DAAL at compile-time?

**Comment by tqchen** [comment]
I think @sbodenstein is right that it will work exactly like cuDNN layers. We can first add it as a optional plugin

**Comment by antinucleon** [comment]
Yes. But it will make the operator folder size explosion.

**Comment by tqchen** [comment]
that is why it can be added as an optional plugin first, so it does not need to be coupled with the current project

**Comment by antinucleon** [comment]
So I think we may do a refactor on organization of operators in summer:
We need support these operator as plugin:
- Pure C++/CUDA Kernel/CuDNN/DAAL
- MShadow/Eigen
- OpenCL/Whatever 

The third may involve storage change and need more discussion, and the first & second seems need to make ```.cc```, ```.cu``` and ```.h``` file lie in different place. 

Besides I think another target is: if one cuda op is missing but there is cpu op, we can insert a copy op in graph and call cpu op then copy back, rather than implement everything.

**Comment by piiswrong** [comment]
I can't find the real code that does computation. Is it like MKL where only headers are given while actual library is only released in binary?

**Comment by sbodenstein** [comment]
@piiswrong: It seems exactly the same as cuDNN or MKL in this regard, yes.

**Comment by mli** [comment]
100K LOC in include/*.h, quite impressive..

**Comment by rhythm9229** [comment]
@antinucleon has anybody tried to build mxnet with mshadow/eigen?
I would like to compare the performance of mxnet on android with multithreaded openblas and eigen.
Some pointers are highly appreciated.

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/search?o=desc&q=mkl&s=updated&type=Issues&utf8=%E2%9C%93

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
