### ISSUE TITLE
How to update the aux parameters?

### ISSUE THREAD

**Issue by gclouding** [apache/incubator-mxnet#2438]
In model.py in the python package, 
_update_params(executor_manager.param_arrays, executor_manager.grad_arrays, updater=updater, num_device=len(ctx), kvstore=kvstore) is used for updating of the parameters. However, seen from the code, the parameters (gamma and beta) of Batch Normalization operator is included in executor_manager.aux_arrays, but not included in executor_manager.param_arrays. So the parameters of Batch Normalization are not updated after each iteration ?

**Comment by piiswrong** [comment]
aux states are not updated by optimizer. Operators are responsible for maintaining it

**Comment by zjubxl123** [comment]
thanks

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
