### ISSUE TITLE
An fatal error occurred in asynchronous engine operation.

### ISSUE THREAD

**Issue by ShawnWongMILab** [apache/incubator-mxnet#2439]
I use GPU and copy some parameters from Cpu to Gpu, When I excuted the program , It got the following error:
/home/shawn/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:15:35] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
[11:15:35] /home/shawn/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:15:35] src/engine/./threaded_engine.h:306: [11:15:35] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:15:35] src/engine/./threaded_engine.h:306: [11:15:35] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

When I  only use Cpu, I got this error:
terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at

I don't know why this error happend? Can anybody help me?

**Comment by sxjscience** [comment]
Could you help provide an example that reproduces the error? I've met this error message before. But in my case, it is corrected after starting the program again.

**Comment by ShawnWongMILab** [comment]
oo,,my example codes scale is a bit large, besides, I don't know  where the error is happend, if you are convenient, I can email the code to you.

**Comment by sxjscience** [comment]
It would be better for us to debug if you could simplify the code and get a minimal example.

**Comment by ShawnWongMILab** [comment]
After I simplified the code, it works! I am  tangled now.... @sxjscience

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
