### ISSUE TITLE
How to copy a model without save and load from file?

### ISSUE THREAD

**Issue by cjfan** [apache/incubator-mxnet#2442]
I want to copy all the trained model param to another,
I see there is some way by using checkpoint, save ,load thought a file.
but Is there any API can do this just in memory?

**Comment by cjfan** [comment]
I don't know what's the common way to do it, but I try the following method, it works. 
model2 use the param of model.
```
params = pickle.loads(pickle.dumps(model.get_params(),2))
model2 = mx.mod.Module(symbol=net,context = mx.gpu(0),data_names=('data',), label_names=('label',),)
...
model2.bind(val_iter.provide_data)
model2.init_params(None,params[0],params[1])
```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
