### ISSUE TITLE
why c++98?

### ISSUE THREAD

**Issue by qiaohaijun** [apache/incubator-mxnet#2444]
```
cc1: warning: command line option '-std=c++98' is valid for C++/ObjC++ but not for C
```

I am working with c++11. Do not get why add this to makefile?

**Comment by tornadomeet** [comment]
i just met the build warning too.

**Comment by Godricly** [comment]
same here

**Comment by tmatas** [comment]
same here

**Comment by piiswrong** [comment]
@jermainewang

**Comment by vchuravy** [comment]
Introduced in #2405

**Comment by sbodenstein** [comment]
On MacOSX, it gives an error, not a warning:
```
error: invalid argument '-std=c++98' not allowed with 'C/ObjC'
```

**Comment by conan7456** [comment]
same here

**Comment by rajafan** [comment]
same here. I am using MacOSX, and it outputs an error as 'error: invalid argument '-std=c++98' not allowed with 'C/ObjC''

**Comment by sxjscience** [comment]
Probably related to https://github.com/dmlc/mxnet/issues/2510

**Comment by rajafan** [comment]
Anything that can be done to work around this error? Thanks.

**Comment by sxjscience** [comment]
@rajafan For OS X, I've been using CMake + XCode (Similar to https://github.com/dmlc/mxnet/blob/master/docs/how_to/build.md#building-on-osx). You may need to manually configure the XCode project. I haven't met this C++98 problem.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
