### ISSUE TITLE
multiple gpu layers from dsstne

### ISSUE THREAD

**Issue by ElleryBaines** [apache/incubator-mxnet#2452]
It would be great to merge in the model parallel multiple gpu capabilities from dsstne. This would make mxnet faster and more efficient on machines with multiple gpu's (many many machines, like a lot).

**Comment by piiswrong** [comment]
mxnet already supports multi gpu and multi machien

**Comment by mli** [comment]
here is a model parallelism example: https://github.com/dmlc/mxnet/tree/master/example/model-parallel-lstm

**Comment by ElleryBaines** [comment]
But dsstne has support for single layers spread across multiple gpus, which is much faster for simple networks, and enables learning more parameters than can fit in a single gpu.

**Comment by eric-haibin-lin** [comment]
The [sparse feature](https://mxnet.incubator.apache.org/versions/master/api/python/ndarray/sparse.html) could be useful to avoid spreading single layer across multiple gpus. Closing it for now due to inactivity. Please feel free to reopen for any follow-up discussions.
