### ISSUE TITLE
input image size smaller than input shape when I train inception-bn-28-small using my own data set

### ISSUE THREAD

**Issue by zhudelong** [apache/incubator-mxnet#2454]
1. I prepare my data set using make_list.py tool and im2rec tool. All the samples are gray images  in 28*28. There are two classes.
2. python train_tagbn.py --network inception-bn-28-small --gpus 0 --data-dir /home/name/DJI/dataset/build/ --num-examples 4544 --model-prefix /home/name/DJI/dataset/model/bn/

3 .
I modify the data_shape into **data_shape = (1, 28, 28)**

```
def get_iterator(args, kv):
    **data_shape = (1, 28, 28)**

    train = mx.io.ImageRecordIter(
        path_imgrec = args.data_dir + "train.rec",
        mean_img    = args.data_dir + "mean.bin",
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        rand_crop   = False,
        rand_mirror = False,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)

    val = mx.io.ImageRecordIter(
        path_imgrec = args.data_dir + "test.rec",
        mean_img    = args.data_dir + "mean.bin",
        rand_crop   = False,
        rand_mirror = False,
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)

    return (train, val)
```
1. I also modify the model into "def get_symbol(**num_classes = 2,** force_mirroring=False):"

but it always tells me that:
[23:28:52] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: /home/name/DJI/dataset/build/train.rec, use 4 threads for decoding..
[23:28:52] src/io/./iter_normalize.h:103: Load mean image from /home/name/DJI/dataset/build/mean.bin
[23:28:52] /home/name/DevTool/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:28:52] src/io/image_aug_default.cc:254: Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape
terminate called after throwing an instance of 'dmlc::Error'
  what():  [23:28:52] src/io/image_aug_default.cc:254: Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape
Aborted (core dumped)

Do you have any suggestions ? Thank you very much!

**Comment by zhudelong** [comment]
I read the source code and fix it. Images to be classified should have larger size than "shape" parameter

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by yian2271368** [comment]
@zhudelong hey, i faced the same problem, how did you fix it ?
