### ISSUE TITLE
mxnet much slower than caffe on Tegra X1 when batch size is small

### ISSUE THREAD

**Issue by LeagueOfCodes** [apache/incubator-mxnet#2460]
1. network: alexnet
2. image shape: 3 \* 227 \* 227
3. cuda 7.0, cudnn v4
4. only **forward** pass time counted

Here's profiling information from nvprof (only significant ones):
## function time:

27.59%  maxwell_scudnn_128x128_stridedB_splitK_small_nn
10.74%  sgemm_largek_lds64<bool=1, bool=0, int=5, int=5, int=4, int=4, int=4, int=34>
7.28%   maxwell_sgemm_128x128_nt
### API time:

42.03%  cudaStreamSynchronize
20.49%  cudaEventSynchronize
10.54%  cudaStreamCreateWithFlags
9.38%   cudaFree
### function time:

32.16%  maxwell_scudnn_128x128_small_nn
16.69%  sgemm_largek_lds64<bool=1, bool=0, int=5, int=5, int=4, int=4, int=4, int=34>
11.85%  fft2d_r2c_32x32<float, bool=1>
### API time:

44.19%  cudaStreamSynchronize
19.31%  cudaFree
13.24%  cudaStreamCreateWithFlags
12.85%  cudaMalloc
### function time:

40.20%  gemmk1_kernel<float, int=256, int=5, bool=0, bool=0, bool=1, bool=0>
23.60%  maxwell_scudnn_128x128_stridedB_splitK_small_nn
17.15%  gemv2T_kernel_val<float, float, float, int=128, int=16, int=2, int=4, bool=0>
### API time:

21.52%  cudaStreamCreateWithFlags
20.68%  cudaMemcpy
19.74%  cudaFree
12.28%  cudaStreamSynchronize
11.96%  cudaEventSynchronize
### function time:

87.87%  sgemm_largek_lds64<bool=1, bool=0, int=6, int=3, int=4, int=5, int=2, int=66>
8.80%    maxwell_scudnn_128x128_small_nn
1.02%   maxwell_scudnn_128x32_interior_nn
### API time:

80.88%  cudaStreamSynchronize
7.12%    cudaLaunch
3.07%    cudaFree
2.55%    cudaMemcpy2DAsync
2.40%    cudaStreamCreateWithFlags
### average time per image: 87.4ms

The average time per image increase dramatically as batch size goes small. Do you have any suggestions regarding this problem? Thank you!

**Comment by tqchen** [comment]
Could due to multi-threading and stream overhead. have you tried use NaiveEngine instead and see how it goes?

**Comment by LeagueOfCodes** [comment]
@tqchen 
I've tried NaiveEngine, also pulled the latest mxnet, but seems no much difference.

**Comment by sxjscience** [comment]
It's superising that in the first experiment fft2d appears (optimized convolution?) Also CudaStream synchronize takes a huge amount of time.

**Comment by tqchen** [comment]
Thanks, this was due to the current execution mode which executes each function step by step. We will need a optimized graph executor for GPU inference.

**Comment by tqchen** [comment]
opened issue here https://github.com/dmlc/mxnet/issues/2462

**Comment by tqchen** [comment]
@LeagueOfCodes  I looked at this again. There are two possible cause of the difference

- MXNet has more synchronization overhead between each ops. This should be fixed by #2496 
- The different choice of CUDNN algorithms. Since from the prof, the algorithm choice was quite different between the two, it could because somehow the selection algorithm choose a bad algorithm in this case.

It is likely that you can confirm which is the case by see how #2496 works, and we can proceed to fix the remaining problem

**Comment by mxs30443** [comment]
@LeagueOfCodes   Hi, I have a problem when install mxnet on Tegra X1 : gcc can't  recognize option '-mess3', i try  commented 'mess3' out. but it have other mistake like miss '*.h' file. Could you help me

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
