### ISSUE TITLE
Improve website style

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#2464]
the website is generated from /docs, but there are a few things need to be fixed
- [ ] navigation bar in narrow screen, namely when the width is less than a threshold, the navbar becomes a symbole "[=]", then the dropdown menu should be aligned vertically rather than horizontally
- [ ] search doesn't work. it works well when build on local machine, so it's probably due to readthedocs.org using different version software or failed to load the index.js
- [ ] the [doc body](http://mxnet.dmlc.ml/en/latest//packages/python/index.html) has no padding when the screen width is less than a threshold

we definitely need to change more things to make the website looks better

**Comment by mli** [comment]
ping @yuweiw823

**Comment by yuweiw823** [comment]
will work on this :)

**Comment by yuweiw823** [comment]
![screen shot 2016-06-20 at 00 58 49](https://cloud.githubusercontent.com/assets/8573604/16186927/3a1ffe20-3682-11e6-8db3-a33b5ca31b5c.png)

Seems that we missed a .js file...Never see it before in the docs folder.

@tqchen

**Comment by tqchen** [comment]
could this be something from sphinx instead of docs natively

**Comment by mli** [comment]
it's the search index generated from all docs, should be located at the
root directory.

http://mxnet.readthedocs.io/en/latest/searchindex.js

**Comment by eric-haibin-lin** [comment]
Closing it for now since we have new website design
