### ISSUE TITLE
have problem when simply use pip install 

### ISSUE THREAD

**Issue by Maofei** [apache/incubator-mxnet#2474]
when I use pip install mxnet
there is no problem
but when i import mxnet, is reports like:

> > > import mxnet
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/mxnet/**init**.py", line 7, in <module>
> > >     from .base import MXNetError
> > >   File "/usr/lib/python2.7/site-packages/mxnet/base.py", line 43, in <module>
> > >     _LIB = _load_lib()
> > >   File "/usr/lib/python2.7/site-packages/mxnet/base.py", line 35, in _load_lib
> > >     lib = ctypes.cdll.LoadLibrary(lib_path[0])
> > >   File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
> > >     return self._dlltype(name)
> > >   File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: /usr/lib/python2.7/site-packages/mxnet/./lib/libmxnet.so: undefined symbol: _ZN2cv3Mat10deallocateEv

hope for help

**Comment by sxjscience** [comment]
Seems to be some linking problems. You'll probably need to add `BLAS` and `OpenCV` related libraries to the environment variable like `LIBRARY_PATH`, `LD_LIBRARY_PATH`, etc.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
