### ISSUE TITLE
Why the max of image_index in train.lst is 9999 on cifar 10?

### ISSUE THREAD

**Issue by wangxingxing** [apache/incubator-mxnet#2476]
Hi All
I run the train_cifar10.py and the script will download cifar10 dataset, i find the the max image_index in train.lst is 9999, but there 50000 lines in train.lst. why the max image_index is 9999? i think it should be 49999. @antinucleon

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
