### ISSUE TITLE
what's the difference between model and module

### ISSUE THREAD

**Issue by rongrongxiangxin** [apache/incubator-mxnet#2489]
I am confused. And how to thransfer the mx.model to mx.mod.Module or mx.mod.Module to mx.model?

**Comment by piiswrong** [comment]
module is a newer interface. we recommend module for new projects.

**Comment by dengdan** [comment]
Why is module interface added, for the convenience of multiple devices?

**Comment by klory** [comment]
Why module is better, could you please explain this? Thank you

**Comment by hegderavin** [comment]
Using the model API, we could load the trained model and predict, without re-creating the network.
But in the module API, I think it expects you to create the network and bind it before you can predict.
Is my understanding correct?
Can I safely use the checkpoint saved by the Module API and load it using the FeedForward/model API and predict? will there be any side effects?
Also, will you be adding this support (predicting without requiring explicit bind) in the module API as well?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
