### ISSUE TITLE
Fully embrace CXX11 in CUDA

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#2510]
For legacy reasons the GPU related code in mxnet so far has been using c++98 standard, to alleviate the previous problem of nvcc not handling c++11 standard code well. Seems this is no longer the case and c++11 is clearly the future to go. I am opening this issue to propose we move the entire project, including CUDA component to be c++11.

There is nothing we need to do about it, except to turn on the c++11 option for nvcc, as the old code will compile without problem. But this simply eliminates the restriction on not using c++11 features on CUDA code, and hopefully make the project more concise moving forward.

**Comment by vchuravy** [comment]
Yes please!
