### ISSUE TITLE
warp-ctc plugin compilation error

### ISSUE THREAD

**Issue by wanghaisheng** [apache/incubator-mxnet#2514]
```

[wanghs@db2 docker-mxnet]$ cat Dockerfile
From dmlc/mxnet:cpu
RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y cmake
RUN  cd ~/ && \
     git clone https://github.com/baidu-research/warp-ctc && \
     cd warp-ctc && \
     mkdir build && \
     cd build && \
     cmake .. && \
     make &&  make install

RUN cd /mxnet && \
    echo "WARPCTC_PATH = $(HOME)/warpctc" >>config.mk && \
    echo "MXNET_PLUGINS += plugin/warpctc/warpctc.mk" >>config.mk && \
    make -j$(nproc)

VOLUME /work
WORKDIR /work
```

error is like this 

```

Step 1 : FROM dmlc/mxnet:cpu
 ---> 26b869b5bb67
Step 2 : RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
 ---> Using cache
 ---> f31b2e93c0a9
Step 3 : RUN apt-get update && apt-get install -y cmake
 ---> Using cache
 ---> 5aece4b3e894
Step 4 : RUN cd ~/ &&      git clone https://github.com/baidu-research/warp-ctc &&      cd warp-ctc &&      mkdir build &&      cd build &&      cmake .. &&      make &&  make install
 ---> Using cache
 ---> 05084853843f
Step 5 : RUN cd /mxnet &&     echo "WARPCTC_PATH = $(HOME)/warpctc" >>config.mk &&     echo "MXNET_PLUGINS += plugin/warpctc/warpctc.mk" >>config.mk &&     make -j$(nproc)
 ---> Running in ab85027b08fa
/bin/sh: 1: HOME: not found
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I/mxnet/mshadow/ -I/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -I/warpctc/include -DMXNET_USE_NVRTC=0 -MM -MT build/plugin/warpctc/warpctc.o plugin/warpctc/warpctc.cc >build/plugin/warpctc/warpctc.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/mxnet/mshadow/ -I/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -I/warpctc/include -DMXNET_USE_NVRTC=0 -c plugin/warpctc/warpctc.cc -o build/plugin/warpctc/warpctc.o
In file included from plugin/warpctc/warpctc.cc:8:0:
plugin/warpctc/./warpctc-inl.h:14:17: fatal error: ctc.h: No such file or directory
 #include <ctc.h>
                 ^
compilation terminated.
make: *** [build/plugin/warpctc/warpctc.o] Error 1
The command '/bin/sh -c cd /mxnet &&     echo "WARPCTC_PATH = $(HOME)/warpctc" >>config.mk &&     echo "MXNET_PLUGINS += plugin/warpctc/warpctc.mk" >>config.mk &&     make -j$(nproc)' returned a non-zero code: 2

```

**Comment by qiaohaijun** [comment]
config.mk 
1. ADD_LDFLAGS
2. ADD_CFLAGS

**Comment by wanghaisheng** [comment]
how to set these two variable ?

**Comment by wanghaisheng** [comment]
make a little change about Dockerfile
```
➜  warp-docker git:(master) ✗ cat Dockerfile 
From dmlc/mxnet:cpu
RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y cmake
RUN  cd /home && \
     git clone https://github.com/baidu-research/warp-ctc && \
     cd warp-ctc && \
     mkdir build && \
     cd build && \
     cmake .. && \
     make &&  make install


RUN cd /mxnet && \
    echo "WARPCTC_PATH = /home/warp-ctc" >>config.mk && \
    echo "MXNET_PLUGINS += plugin/warpctc/warpctc.mk" >>config.mk && \
    make -j$(nproc)

VOLUME /work
WORKDIR /work
```
the problem goes like this 
```
root@f9df040f3302:/mxnet/example/warpctc# python toy_ctc.py 
Traceback (most recent call last):
  File "toy_ctc.py", line 6, in <module>
    import mxnet as mx
  File "../../python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "../../python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "../../python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libwarpctc.so: cannot open shared object file: No such file or directory

```
i try the following ones  just replace  /where/you/install =/home/warp-ctc/build here
1.ln -s /where/you/install/lib/*.so /usr/lib 
2.export LD_LIBRARY_PATH=/where/you/install/lib:$LD_LIBRARY_PATH
sudo ldconfig
neither one is working

**Comment by qiaohaijun** [comment]
I did not use docker

**Comment by shuokay** [comment]
`git clone https://github.com/baidu-research/warp-ctc`
You cloned the code into `warp-ctc`, however in the `config.mk`, you config the  `WARPCTC_PATH` to `WARPCTC_PATH = $(HOME)/warpctc" >>config.mk`. So I think you can either change the `WARPCTC_PATH` to ` $(HOME)/warp-ctc` or rename `warp-ctc` to `warpctc`

**Comment by wanghaisheng** [comment]
@shuokay
no you are not true
in config.mk  WARPCTC_PATH is already the clone target directory
```
    echo "WARPCTC_PATH = /home/warp-ctc" >>config.mk && \
```

**Comment by everal** [comment]
@shuokay 
 I compiled warp-ctc and mxnet successful.
I add warp-ctc in config.mk, also generate libwarpctc.so in mxnet/lib
but when I run lstm_ocr.py, the problem disapper
/*
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'
*/
Did you have idea about this?

**Comment by sinmaystar** [comment]
@wanghaisheng I have meet the same problem with you, when I run toy_ctc.py it occurs mxnet.base.MXNetError: [18:01:57] src/storage/storage.cc:44: Please compile with CUDA enabled
problem, Did you solve this problem? I want to use CPU to run this code.

**Comment by wanghaisheng** [comment]
@sinmaystar  still not fix that

**Comment by sinmaystar** [comment]
@wanghaisheng issue #2470 describe he use both cpu and gpu run successfully, so it must have some way to solve this problem

**Comment by shuokay** [comment]
@everal If you have installed mxnet by `sudo python setup.py install` before, you should reinstall again.

**Comment by sinmaystar** [comment]
@everal I have met the same problem with you, did u solve this problem ? and how to solve this problem? thanks many!

**Comment by sinmaystar** [comment]
@shuokay when I run lstm_ocr.py it occurs the same problem with @everal , I have installed baidu warp-ctc and rebuild mxnet then I have uninstalled mxnet by pip uninstall, after that I have reinstall python package but it still the same problem, did u know how to solve this problem?

**Comment by livedimg** [comment]
I also met AttributeError: 'module' object has no attribute 'WarpCTC'， and  solve it：
uncomment the following lines：
WARPCTC_PATH = $(HOME)/warp-ctc
MXNET_PLUGINS += plugin/warpctc/warpctc.mk
and reinstall the mxnet
copy the file:libwarpctc.so(warp-ctc/build) to usr/lib
then it will be ok

**Comment by sinmaystar** [comment]
thanks a lot,I have solved this problem,btw what's the accuracy do u run this code lstm_ocrI also met AttributeError: 'module' object has no attribute 'WarpCTC'， and  solve it：
uncomment the following lines：
WARPCTC_PATH = $(HOME)/warp-ctc
MXNET_PLUGINS += plugin/warpctc/warpctc.mk
and reinstall the mxnet
copy the file:libwarpctc.so(warp-ctc/build) to usr/lib
then it will be ok

**Comment by livedimg** [comment]
@sinmaystar after epoch[9],validation-accuracy = 0.96500

**Comment by fq19851220** [comment]
@livedimg  兄弟你怎么解决module' object has no attribute 'WarpCTC'  能用中文详细说说吗？我也碰到这问题

**Comment by BobLiu20** [comment]
@fq19851220 Please open config.mk file and uncomment the following lines:
```
WARPCTC_PATH = $(HOME)/warp-ctc
MXNET_PLUGINS += plugin/warpctc/warpctc.mk
```
take care the WARPCTC_PATH is our warp-ctc path so please instead of it by your correct path.
and then rebuild mxnet by make clean && make -j 

Chinese again:
在mxnet目录下有一个config.mk，打开找到前面说的那两行，取消注释，然后修改WARPCTC_PATH为你的warp-ctc目录，然后重新编译mxnet，就可以了。（warp-ctc目录请到baidu warp-ctc仓库单独下载）

**Comment by fq19851220** [comment]
@BobLiu20   谢谢

**Comment by qieaaa** [comment]
@BobLiu20 hello, I tried this way as you said as it in official page, but it still doesn't work .
I found that if I don't comment out these two lines, it works very well.
BUT when I comment out these lines, I can't REBUILD the mxnet successfully, it's crazzy.
Chinese : 
我按照官方文档安装完毕ctc后，改mxnet的config.mk的配置再重新编译mxnet就报错。warpctc测试了下没问题，mxnet不取消注释情况下编译也没问题。一取消这两行注释就报错，简直抓狂。。求教怎么办

**Comment by BobLiu20** [comment]
@qieaaa  Can you share your error output in here? BTW, You have to specify the path of your warpctc lib for mxnet. Maybe you can export a env (eg: export LD_LIBRARY_PATH=$LIB_LIBRARY_PATH:/your/path/warp-ctc/).

**Comment by qieaaa** [comment]
@BobLiu20 Thank you for your reply, I'm sorry that I don't make myself clear.Here is what I did : 
1. I installed mxnet , warp-ctc respectively, totally follow the official guide. Then I run tests. each of them  works well.

2. I enabled warpctc in mxnet ,commented out following lines in mxnet/config.mk
    _WARPCTC_PATH = $(HOME)/warp-ctc
    MXNET_PLUGINS += plugin/warpctc/warpctc.mk_
rebuilt mxnet after that.

3. then I get the following results,last line shows:
    **_make[1]: Leaving directory `/home/lab/mxnet/dmlc-core'_**
then the make process stopped. I found mxnet still works,but there are no bin and lib files in mxnet. when I run the lstm_ocr demo,it shows:
_**Traceback (most recent call last):
  File "lstm_ocr.py", line 157, in <module>
    symbol = sym_gen(SEQ_LENGTH)
  File "lstm_ocr.py", line 148, in sym_gen
    num_label = num_label)
  File "/home/lab/mxnet/example/warpctc/lstm.py", line 77, in lstm_unroll
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'**_

It really drives me crazy. BTW, when I export a env ,it shows RuntimeError: Cannot find the files.
List of candidates:
_**/home/lab/mxnet/python/mxnet/libmxnet.so
/home/lab/mxnet/python/mxnet/../../lib/libmxnet.so
/home/lab/mxnet/python/mxnet/../../build/Release/libmxnet.so
libmxnet.so
/home/lab/warp-ctc/libmxnet.so**_

so I don't do that

**Comment by BobLiu20** [comment]
@qieaaa  Hi, It seems you don't had build complete because it is not lib folder with bin and lib files in mxnet. 

So, Please check carefully if an error appear like ```plugin/warpctc/./warpctc-inl.h:14:17: fatal error: ctc.h: No such file or directory```.  Maybe you can search keyword "warpctc" in build output terminal to confirm if build done.

BTW:   
* Please make sure the path of warp-ctc is really in $(HOME)/warp-ctc. Because you have config it in config.mk with ```WARPCTC_PATH = $(HOME)/warp-ctc```
* There are two way to build mxnet:
one is:
```
make clean
cp make/config.mk .
make -j
```
   another one is:
```
make clean
mkdir build && cd build
cmake ..
make -j
```
I think do a make clean is nice for us.
Anyway, if you still not solve, you can [Email](liubofang@cvte.com) me if possible (chat in time).

**Comment by qieaaa** [comment]
@ld909 you mean you have the same error with me ? Please follow  [this](https://github.com/baidu-research/warp-ctc/issues/46) with Mr BobLiu's solution.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
