### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by zy-huang** [apache/incubator-mxnet#2521]
I tried to install mxnet on Windows 10,and got a CMake error.I don't know how to fix it.

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "mxnet" in directory F:/Program Files/mxnet
    linked by target "mxnet" in directory F:/Program Files/mxnet
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "mxnet" in directory F:/Program Files/mxnet
    linked by target "mxnet" in directory F:/Program Files/mxnet
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "mxnet" in directory F:/Program Files/mxnet
    linked by target "mxnet" in directory F:/Program Files/mxnet

-- Configuring incomplete, errors occurred!`

I have installed CUDA,Cudnn,openCV and openBLAS.

**Comment by mmacd33** [comment]
I just experienced the same problem.  The solution is selecting the right compiler for your OS architecture ("Win32 or x64") as discussed here: http://stackoverflow.com/questions/33097558/cmake-cuda-libraries-not-found-when-compiling-opencv 

Try selecting "Visual Studio 12 2013 Win64" as your generator, and your problem should be solved.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by KrisLee512** [comment]
Hi,I also encountered the same problem with my Ubuntu 18.04 computer,how did you solve the issue,Thank you
