### ISSUE TITLE
NDArrayIter expects "softmax_label"

### ISSUE THREAD

**Issue by jonasrla** [apache/incubator-mxnet#2532]
This is not a problem yet, but if pull request #2531 gets approved people may have problems whenever they try build a model using a mxnet.symbol.SupportVectorMachine object as their top layer on Python.

Whenever we try to build a using NDArrayIter to save data and labels, the model fit will complain because it didn't found a "softmax_label". I worked around this on the example that is also on the pull request setting the attribute label again with

`train_iter.label = io._init_data(label, allow_empty=True, default_name='svm_label')`

But as I mentioned on #1810 that's a underlined function. That should be private, right?

Given that context what could be done to prevent people running on this problem?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
