### ISSUE TITLE
"ValueError:NDArray only support continous slicing on axis 0" what it happened

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2539]
Hello,everyone.I am a mxnet and python beginer.So when I use MXnet ,I encounter some errors that confuse me so much.

I wanna use MXnet to do the image's  super resolution.So when I set up the DataIter object,I refer to the data.py in fcn-xs example. Because I use gray images,so I modify some codes. and  set the batch_size=1

Some changed codes as follows:
"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
 def _read_img(self, img_name, label_name):
        img = Image.open(os.path.join(self.root_dir, img_name))
        label = Image.open(os.path.join(self.root_dir, label_name))
        img = np.array(img, dtype=np.float32)  # (h, w, c)
        label = np.array(label)  # (h, w)
        img = img - self.mean
        img = np.expand_dims(img, axis=0)  # (1, c, h, w)
        img = np.expand_dims(img, axis=0)
        label = np.array(label)  # (h, w)
        label = np.expand_dims(label, axis=0)  # (1, h, w)
"''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
 def next(self):
        """return one dict which contains "data" and "label" """
        if self.iter_next():
            self.data, self.label = self._read()
           # return {self.data_name  :  self.data[0][1],
           #         self.label_name :  self.label[0][1]}
           #change the numpy to nd
            mydata=mx.nd.array(self.data[0][1],self.ctx)
            mylabel=mx.nd.array(self.label[0][1],self.ctx)
            return mx.io.DataBatch(data=mydata,label=mylabel)
        else:
            raise StopIteration
"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

When I create the Dataiter object ,it it right.But when I  execute the following command ,I get errors below:
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

> > > model=mx.model.FeedForward.create(mynet,X=train_data,num_epoch=10,learning_rate=0.01)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/opt/mxnet/python/mxnet/model.py", line 901, in create
> > >     eval_batch_end_callback=eval_batch_end_callback)
> > >   File "/opt/mxnet/python/mxnet/model.py", line 784, in fit
> > >     sym_gen=self.sym_gen)
> > >   File "/opt/mxnet/python/mxnet/model.py", line 222, in _train_multi_device
> > >     executor_manager.load_data_batch(data_batch)
> > >   File "/opt/mxnet/python/mxnet/executor_manager.py", line 394, in load_data_batch
> > >     self.curr_execgrp.load_data_batch(data_batch)
> > >   File "/opt/mxnet/python/mxnet/executor_manager.py", line 245, in load_data_batch
> > >     _load_data(data_batch, self.data_arrays)
> > >   File "/opt/mxnet/python/mxnet/executor_manager.py", line 87, in _load_data
> > >     _load_general(batch.data, targets)
> > >   File "/opt/mxnet/python/mxnet/executor_manager.py", line 78, in _load_general
> > >     for d_src, d_targets in zip(data, targets):
> > >   File "/opt/mxnet/python/mxnet/ndarray.py", line 212, in __getitem__
> > >     raise ValueError('NDArray only support continuous slicing on axis 0')
> > > ValueError: NDArray only support continuous slicing on axis 0
> > > ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

I have no idea about the error.I hope that some expert can give me some advice.Thank you so much

**Comment by tornadomeet** [comment]
hello, @lugui2009 could you provide the full code then we can help you? from the error message, it means you are using the NDArray slice on axis like 1,2,3 which do not support, just convert it to numpy array using .asnumpy().

**Comment by lugui2009** [comment]
@tornadomeet   Thank you for your reply.Yesterday,I read the code again.And I am sure I have  mistaken  this code .I have no idea of the concept of slice,and don't know what it is used for.Could you give me an template that how to write an DataIter of MXnet? Thank you again.

**Comment by tornadomeet** [comment]
just read the code of python/mxnet/io.py, then you can know how to write, because we only need the next() function to get the data and label.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
