### ISSUE TITLE
Training Autoencoders using Multiple GPUs?

### ISSUE THREAD

**Issue by tokyolearninng** [apache/incubator-mxnet#2542]
We r using MXNet to train autoencoders. Anyone knows how to use multiple GPUs when training autoencoders? We found the example code as:

---

ae_model = AutoEncoderModel(mx.gpu(0), [784,500,500,2000,10], pt_dropout=0.2,
internal_act='relu', output_act='relu')

---

it seems like we can use gpus = [mx.context.gpu(0), mx.context.gpu(1), mx.context.gpu(2)]? However, it doesn't work.

**Comment by leotam** [comment]
Just to get a little more thought on this, the path forward should probably be a data parallel approach similar to https://github.com/timsainb/Tensorflow-MultiGPU-VAE-GAN/blob/master/VAE-GAN-multi-gpu-celebA.ipynb.  The model is duplicated across GPUs and gradients are averaged periodically.

In terms of minimally reproducible example, we could target mnist_sae.py under /root/mxnet/example/autoencoder/.  As @tokyolearninng noticed, piping in for example ctx=[mx.gpu(2), mx.gpu(3)] on ln 13, throws:

```
Traceback (most recent call last):
  File "mnist_sae.py", line 14, in <module>
    internal_act='relu', output_act='relu')    
  File "/root/mxnet/example/autoencoder/model.py", line 45, in __init__
    self.setup(*args, **kwargs)
  File "/root/mxnet/example/autoencoder/autoencoder.py", line 39, in setup
    sparseness_penalty, idropout, odropout, encoder_act, decoder_act)
  File "/root/mxnet/example/autoencoder/autoencoder.py", line 75, in make_stack
    args = {'encoder_%d_weight'%istack: mx.nd.empty((num_hidden, num_input), self.xpu),
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.2-py2.7.egg/mxnet/ndarray.py", line 638, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.2-py2.7.egg/mxnet/ndarray.py", line 82, in _new_alloc_handle
    ctypes.c_int(ctx.device_typeid),
AttributeError: 'list' object has no attribute 'device_typeid'
```

Diving into the implementation, it seems parallelism would occur in https://github.com/dmlc/mxnet/blob/master/example/autoencoder/solver.py.  Will try to parse the implementation a bit better, but better documentation and comments are appreciated.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
