### ISSUE TITLE
where can I find the source code of ImageRecordIter or MNISTIter of python

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2546]
hello everybody.I have to write my own DataIter.However in the file  I can't find the source code of ImageRecordIter or MNISTIter of python.

**Comment by zhangchen-qinyinghua** [comment]
Those two DataIter are written in Cpp.
You can always write your own DataIter in python.

**Comment by lugui2009** [comment]
@zhangchen-qinyinghua thank you.But I found it was difficult to write my own DateIter.Do you have some templates ?I am working on image-processing.Thank you again

**Comment by kikoqiu** [comment]
@lugui2009 You may have a look at NDArrayIter in python/mxnet/io.py .  Basically, you should overwrite the __next__ function to return a DataBatch with data=[mx.ndarray(4d)]. Also don't forget to set provide_data and provide_label property of the iter.

**Comment by lugui2009** [comment]
@kikoqiu   Thank you so much.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
