### ISSUE TITLE
launch job errors on SGE grid

### ISSUE THREAD

**Issue by galactica147** [apache/incubator-mxnet#2549]
Hi, I've having a trouble trying to launch several SGE jobs for a tutorial example from https://github.com/dmlc/mxnet/blob/master/docs/how_to/multi_devices.md

After compiling with `USE_DIST_KVSTORE=1`, I was able to run `python train_mnist.py`under `mxnet/example/image-classification/`, however when i tried 

`../../tools/launch.py -n 2 --launcher sge python train_mnist.py --network lenet --kv-store dist_sync`

I got the following errors:

```
Traceback (most recent call last):
  File "train_mnist.py", line 132, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "/<path>/mxnet/example/image-classification/train_model.py", line 8, in fit
    kv = mx.kvstore.create(args.kv_store)
  File "/<path>/mxnet/python/mxnet/kvstore.py", line 378, in create
    ctypes.byref(handle)))
  File "/<path>/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:00:27] src/kvstore/kvstore.cc:41: compile with USE_DIST_KVSTORE=1 to use dist_sync
```

I have to say the package build seemed successful but I haven't verified it with any examples using ssh or sge. 

Also, please advise if there is way to kill the attempts of launching jobs -- currently it simply keeps trying (and failing), and the only way to kill it is to kill the terminal (e.g., bash) session. 
Anyone has an idea how to fix this? 
Thanks!

**Comment by mli** [comment]
run `make clean` first.

**Comment by galactica147** [comment]
`make clean` seems to remove the generated .so lib file, is that lib file supposed to be copied to any targeted location before 'make clean'?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
