### ISSUE TITLE
I have a question about fcnxs in the example file

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2557]
Hello everyone.Recently I have read the code of fcnxs in the example file. In this example,It mentions that
    """FileIter object in fcn-xs example. Taking a file list file to get dataiter.
    in this example, we use the whole image training for fcn-xs, that is to say
    we do not need resize/crop the image to the same size, so the batch_size is
    set to 1 here'''''

So the example has his own data.py to create a DateIter.Moreover,the example has his own solver file which confuses me very much.Why does this example has to write its own solver rather than using the default solver like model.fit()

I mimic this  example ,and write a DataIter like that.However,It doesn't work when I use the default solver model.fit().

So are there some special rules when using the model.fit()? Thank you .

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
