### ISSUE TITLE
memory increasing during training

### ISSUE THREAD

**Issue by li-haoran** [apache/incubator-mxnet#2558]
when i train a model on GPU, the Memory is increasing. the dataiter i write following the fcn-xs

**Comment by sxjscience** [comment]
@li-haoran Could you help provide a small example?

**Comment by li-haoran** [comment]
https://github.com/li-haoran/mxnet/blob/master/example/pose/cpmdata.py  here is my data iter
https://github.com/li-haoran/mxnet/blob/master/example/pose/solver.py  this is solver

**Comment by piiswrong** [comment]
https://github.com/li-haoran/mxnet/blob/master/example/pose/solver.py#L80
you need to pass the initial executor as shared_mem here

**Comment by piiswrong** [comment]
There is usually no need to write a solver now. Try mx.module.bucketing_module

**Comment by piiswrong** [comment]
have a look at the bucketing example

**Comment by mcxkarakoc** [comment]
.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
