### ISSUE TITLE
how to use '.mat' of matlab data in the MXnet 

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2567]
Hello，everyone.Because I am familiar with matlab.So I want MXnet to load matlab datas.I have read the  code of autoencoder in the example file.In it ,there is a function called "fetch_mldata()"function ,but I encounter some problem when I use this fuction.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

> > > from sklearn.datasets.mldata import fetch_mldata
> > > mnist=fetch_mldata('mnist-original',data_home='./')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/opt/anaconda2/lib/python2.7/site-packages/sklearn/datasets/mldata.py", line 158, in fetch_mldata
> > >     matlab_dict = io.loadmat(matlab_file, struct_as_record=True)
> > >   File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 135, in loadmat
> > >     matfile_dict = MR.get_variables(variable_names)
> > >   File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
> > >     res = self.read_var_array(hdr, process)
> > >   File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
> > >     return self._matrix_reader.array_from_header(header, process)
> > >   File "scipy/io/matlab/mio5_utils.pyx", line 668, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.                                       c:7079)
> > >   File "scipy/io/matlab/mio5_utils.pyx", line 698, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.                                       c:6196)
> > >   File "scipy/io/matlab/mio5_utils.pyx", line 771, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (scipy/io/matlab/mio5_utils.                                       c:7541)
> > >   File "scipy/io/matlab/mio5_utils.pyx", line 444, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (scipy/io/matlab/mio5_utils.c:424                                       2)
> > >   File "scipy/io/matlab/mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element (scipy/io/matlab/mio5_utils.c:389                                       2)
> > >   File "scipy/io/matlab/streams.pyx", line 331, in scipy.io.matlab.streams.FileStream.read_string (scipy/io/matlab/streams.c:5074)
> > > IOError: could not read bytes
> > > """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

I read some documents about this fuction.It seems to download the data from mldata.org.And it isn't  what I want. But I don't know how to use my own Data from matlab. And is there anybody who can give me some advice? Thank you so much.

**Comment by piiswrong** [comment]
http://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html

**Comment by lugui2009** [comment]
@piiswrong  thank you so much .

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
