### ISSUE TITLE
how can I convert my binary file to .rec file, thanks

### ISSUE THREAD

**Issue by kelcyzhang** [apache/incubator-mxnet#2568]
I wrote a binary file (containing label &image data(0~1)),but I don't know how to use it to train CNN. Besides, I only know how to covert .jpg to .rec,  can anyone know how to convert binary file to .rec file ?

**Comment by piiswrong** [comment]
read it into python, and write out with mx.recordio

**Comment by kelcyzhang** [comment]
Thanks a lot! And my data format is not int, but float, is it ok?

**Comment by tmatas** [comment]
the `im2rec` tool might be useful

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
