### ISSUE TITLE
caffe_convert prelu ?

### ISSUE THREAD

**Issue by zhangqianhui** [apache/incubator-mxnet#2569]
Does caffe_convert.py support prelu layer ?
I don't find it, just have the relu and the num = 18.

**Comment by zhangqianhui** [comment]
thanks , I need help.

**Comment by piiswrong** [comment]
not yet. should be easy to add the support, similar to relu

**Comment by zhangqianhui** [comment]
@piiswrong  and do you can add the prelu support?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
