### ISSUE TITLE
How to create a KvstoreServer?

### ISSUE THREAD

**Issue by cjfan** [apache/incubator-mxnet#2571]
I want to run mxnet in two different processes and share some data through kvstore,
so I can push some trained parameters from one process and pull them in another to do some prediction.
When directly use:

```
kvs = mx.kv.create('dist')
```

I meet some problem about environment variable, and after set: DMLC_NUM_WORKER=1,DMLC_NUM_SERVER=1,DMLC_ROLE=server,
it result in an exception: access violation reading.

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\__init__.
py", line 35, in <module>
    from . import kvstore_server
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_s
erver.py", line 68, in <module>
    _init_kvstore_server_module()
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_s
erver.py", line 65, in _init_kvstore_server_module
    server.run()
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_s
erver.py", line 56, in run
    check_call(_LIB.MXKVStoreRunServer(self.handle, _ctrl_proto(self._controller
()), None))
WindowsError: exception: access violation reading 0x0000000000000000
```

Who can give me some advise?

**Comment by piiswrong** [comment]
@mli

**Comment by cjfan** [comment]
Thank you. I trace the code, and find it crash here, in \mxnet\ps-lite\src\van.cc
```
void Van::Start() {
  // get scheduler info
  scheduler_.hostname = std::string(CHECK_NOTNULL(Environment::Get()->find("DMLC_PS_ROOT_URI")));
  scheduler_.port     = atoi(CHECK_NOTNULL(Environment::Get()->find("DMLC_PS_ROOT_PORT")));
  scheduler_.role     = Node::SCHEDULER;
  scheduler_.id       = kScheduler;
  is_scheduler_       = Postoffice::Get()->is_scheduler();

```
After add the environment variable 'DMLC_PS_ROOT_URI','DMLC_PS_ROOT_PORT', 
the beginning test code seems passed, But I'm not sure the following situation.
I will try it later. And is there some example about it?

**Comment by mli** [comment]
doc https://github.com/dmlc/ps-lite/blob/master/docs/env.md
example https://github.com/dmlc/ps-lite/blob/master/tests/local.sh

**Comment by cjfan** [comment]
Thanks! The doc in `dmlc/ps-lite/docs/` is helpful for me.
But I still have some problem.
When I use `mx.kv.create('dist')`, the worker procces will always hang up. Is this all right?
How can I do the pull/push operation then?
I looked at the example of `image-classification\train_model.py`,
```
def fit(args, network, data_loader, batch_end_callback=None):
    # kvstore
    kv = mx.kvstore.create(args.kv_store)
...
if args.kv_store == 'dist_sync':
        epoch_size /= kv.num_workers
        model_args['epoch_size'] = epoch_size
```
I'm not very clear, does it suppose this will not hang up the running?
or what is the correct usage?

I have startup a 'scheduler' and 'server' , by set PS_VERBOSE=2
I get the console output below:
scheduler
```
[14:57:16] D:\Work\mxnet\ps-lite\src\van.cc:206: the scheduler is connected to 1 workers and 1 servers
[14:57:16] D:\Work\mxnet\ps-lite\src\van.cc:142: 9 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[14:57:16] D:\Work\mxnet\ps-lite\src\van.cc:142: 1 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=7 }
[14:57:16] D:\Work\mxnet\ps-lite\src\van.cc:119: ? => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=7 }
[14:59:13] D:\Work\mxnet\ps-lite\src\van.cc:142: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.240.160.23, port=2939 } }
[19:02:56] D:\Work\mxnet\ps-lite\src\van.cc:142: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.240.160.23, port=27867 } }
[19:11:53] D:\Work\mxnet\ps-lite\src\van.cc:142: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.240.160.23, port=29392 } }
```
server
```
[14:56:48] D:\Work\mxnet\ps-lite\src\van.cc:65: Bind to role=server, ip=10.240.160.23, port=2563
[14:56:48] D:\Work\mxnet\ps-lite\src\van.cc:119: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=10.240.160.23, port=2563 } }
```
worker
```
>>> execfile('paramworker.py')
[19:11:53] D:\Work\mxnet\ps-lite\src\van.cc:65: Bind to role=worker, ip=10.240.160.23, port=29392
[19:11:53] D:\Work\mxnet\ps-lite\src\van.cc:119: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.240.160.23, port=29392 } }
```
the test code in paramworker.py:
```
import os
import sys
env = os.environ
env['DMLC_NUM_WORKER'] = '1'
env['DMLC_NUM_SERVER'] = '1'
env['DMLC_ROLE'] = 'worker'
env['DMLC_PS_ROOT_URI'] = 'localhost'
env['DMLC_PS_ROOT_PORT'] = '9091'
#env['DMLC_LOCAL'] = '1'
env['PS_VERBOSE'] = '2'
import mxnet as mx
#kvs = mx.kv.create('dist')
kvs = mx.kv.create('dist_sync')
#pull/push
print(kvs)
#sys.exit()
```
and now the libmxnet.dll is block here, in zmq_van.h
```
  int RecvMsg(Message* msg) override {
    msg->data.clear();
    size_t recv_bytes = 0;
    for (int i = 0; ; ++i) {
      zmq_msg_t* zmsg = new zmq_msg_t;
      CHECK(zmq_msg_init(zmsg) == 0) << zmq_strerror(errno);
      while (true) {
        if (zmq_msg_recv(zmsg, receiver_, 0) != -1) break; <<<<<<<-----------
        if (errno == EINTR) continue;
        LOG(WARNING) << "failed to receive message. errno: "
                     << errno << " " << zmq_strerror(errno);
        return -1;
      }
```

**Comment by cjfan** [comment]
the scheduler,server,worker can start up.
but when I use such code in the worker procces,
```
kvs = mx.kv.create('dist_sync')
#kvs._set_updater(update)
...
kvs.push(3,mx.nd.ones(2))
```
the server will crash with:
```
    import mxnet as mx
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\__init__.py", line 35, in <module>
    from . import kvstore_server
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_server.py", line 68, in <module>
    _init_kvstore_server_module()
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_server.py", line 65, in _init_kvstore_server_module
    server.run()
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\kvstore_server.py", line 56, in run
    check_call(_LIB.MXKVStoreRunServer(self.handle, _ctrl_proto(self._controller()), None))
  File "D:\Work\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:00:50] d:\work\mxnet\src\kvstore\./kvstore_dist_server.h:197: Check failed: updater_
```
I think there is something wrong with my usage, I want to run two worker and share some value by kvstore.
but the pull value step not work, how can I do it?

**Comment by cjfan** [comment]
from example and the code implementation in kvstore_dist_server.h,
I find when use kvstore_server, the updater mush be set by call set_optimizer in the worker node, before call kvstore push.
when just use local version kvstore, the updater can be default as the "Assign" operation, which is consistent with the doc.
I have a question why there can't be default assignment behavior in kvstore server?
for example, the code in 
```
void DataHandle(const ps::KVMeta& req_meta,
                  const ps::KVPairs<real_t>& req_data,
                  ps::KVServer<real_t>* server) {
```
can such code
```
 // async push
        exec_.Exec([this, key, &recved, &stored](){
          CHECK(updater_);
          updater_(key, recved, &stored);
        });
        server->Response(req_meta);
        stored.WaitToRead();
```
be modified to
```
 // async push
        if(updater_ != nullptr){
          exec_.Exec([this, key, &recved, &stored](){
            CHECK(updater_);
            updater_(key, recved, &stored);
          });
        } else {
          CopyFromTo(recved, &stored, 0);
        }
        server->Response(req_meta);
        stored.WaitToRead();
```
?
and sorry, another question, after try them all, I guess kvstore is not design as I read from its name, a key-value storage and support distribution.
directly use it to share value in different process is not easy (finaly, i only achieved in the 'dist-async' mode, the 'dist-sync' mode will blocking when call push).
maybe It try to do some automatic work for parameter-server.
and, If I want use serveral workers for training and one worker just pull param only for prediction. is there any convenient way by using kvstore? or I should do the communication by myself like use multiprocessing?

**Comment by SmartAir** [comment]
@cjfan 
Hi, I am also trying to modify `kvstore_dist_server.h` to implement another mode of synchronizing data in distributed training. I am also confused with the question:

> why there can't be default assignment behavior in kvstore server
 

And do you have an answer to your work:

> If I want use serveral workers for training and one worker just pull param only for prediction. is there any convenient way by using kvstore? or I should do the communication by myself like use multiprocessing?

I am doing similar work, but met some problems during my current modification of  `kvstore_dist_server.h` #6158  #6078 , maybe we can have a more detailed discuss?
Thank you in advance~

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
