### ISSUE TITLE
Amalgamation compile error on iOS

### ISSUE THREAD

**Issue by voidrank** [apache/incubator-mxnet#2573]
I followed this [guide](https://github.com/dmlc/mxnet/tree/master/amalgamation), but failed.
Fortunately, I found that when compiling predict_mxnet-all.cc, the macro `MSHADOW_USE_SSE` is set to 1. But all iOS devices use ARM cpu, and SSE is an extension instruction set of x86. So we need to add this code at the beginning of the file: 
`#define MSHADOW_USE_SSE 0`
So is it the right solution to that problem? Or I did something wrong....?

**Comment by SlipknotTN** [comment]
You're right, you have to manually change mxnet_predict-all.cc setting MSHADOW_USE_SSE to 0.

In the guide I put this:

Change
```
#if defined(__ANDROID__) || defined(__MXNET_JS__)
#define MSHADOW_USE_SSE         0
#endif
```

To
```
#define MSHADOW_USE_SSE         0
```

**Comment by voidrank** [comment]
@SlipknotTN I'm sorry, I didn't see that. In fact, I followed the Chinese version guide and that guide was out of date...=  =

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
