### ISSUE TITLE
caffe_convert vgg error

### ISSUE THREAD

**Issue by zhangqianhui** [apache/incubator-mxnet#2576]
I change the vgg model and train again.
But i got the error

Swapping BGR of caffe into RGB in mxnet
converting layer conv1_anc_7x7_s2, wmat shape = (64, 3, 7, 7), bias shape = (64,)
**conv1_anc_7x7_s2_weight not found in arg_shape_dic**

Traceback (most recent call last):
  File "./convert_model.py", line 106, in <module>
    main()
  File "./convert_model.py", line 75, in main
    wmat[:, [0, 2], :, :] = wmat[:, [2, 0], :, :]
**IndexError: too many indices**

why ?
Thanks I need help.

**Comment by zhangqianhui** [comment]
@pluskid

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
