### ISSUE TITLE
windows build error  c1002 

### ISSUE THREAD

**Issue by li-haoran** [apache/incubator-mxnet#2579]
the previous version MXnet, i built successfully,
but now i update to the latest version, there is a build error:
 **fatal error C1002: 在第 2 遍中编译器的堆空间不足.**

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by HeshanMountteen** [comment]
Do u have any solution and know why?
