### ISSUE TITLE
is there any symbol like "cut" ? x into x1[0:10]  and x2[10:20] ?

### ISSUE THREAD

**Issue by cquwxx** [apache/incubator-mxnet#2580]

**Comment by kxf8608** [comment]
slice = mx.symbol.SliceChannel(data = input_data, num_outputs = 2, name = 'slice', axis = 0)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
