### ISSUE TITLE
Link only necessary opencv libraries

### ISSUE THREAD

**Issue by Neiko2002** [apache/incubator-mxnet#2591]
Right now the build process of mxnet is linking all installed OpenCV libraries on the system. Or to be exact all libraries delivered by "pkg-config --cflags opencv". Wouldn't it be better to only add the necessary ones, otherwise mxnet will stop working if one of the opencv modules gets deleted later on.

```
# setup opencv
ifeq ($(USE_OPENCV), 1)
    CFLAGS += -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`
    LDFLAGS += `pkg-config --libs opencv`
    BIN += bin/im2rec
else
    CFLAGS+= -DMXNET_USE_OPENCV=0
endif
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
