### ISSUE TITLE
Compile amalgamation error ?

### ISSUE THREAD

**Issue by zhangqianhui** [apache/incubator-mxnet#2602]
the error info is :

arm-linux-androideabi-g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/opt/OpenBLAS/include -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -O3 -MD -MF mxnet_predict0.d \
    -I `pwd`/../ -I `pwd`/../mshadow/ -I `pwd`/../dmlc-core/include \
    -I `pwd`/../include \
    -D__MIN__=0 -c mxnet_predict0.cc
rm mxnet_predict0.o
Generating amalgamation to  mxnet_predict-all.cc
python ./amalgamation.py mxnet_predict0.d mxnet_predict0.cc mxnet_predict-all.cc 0 1
-  This is a Standard C++ Library file.  You should @c #include this file

`
# include <bits/c++config.h>

 not found

`

**Comment by zhangqianhui** [comment]
Can you give me a tip ?

**Comment by zhangqianhui** [comment]
@SlipknotTN

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
