### ISSUE TITLE
How do I correctly use SliceChannel?

### ISSUE THREAD

**Issue by horserma** [apache/incubator-mxnet#2620]
Hi,
I am trying to split a symbol to several symbols and deal with them respectively, but i found that the return value of SliceChannel is a single symbol rather than an array. For example,

```
layer------> /part1------->fc layer1-------->loss1
             \part2------->fc layer2-------->loss2
```

Any clue? thanks.

**Comment by piiswrong** [comment]
It's a symbol that can be indexed just like an array.

**Comment by horserma** [comment]
@piiswrong Thanks for your reply.
I am trying to iterate the elements based on what you said. But I received an error when I tried to visualize the network. The code is as follows:
```
import mxnet as mx
net = mx.symbol.Variable("data")
net = mx.symbol.SliceChannel(net, num_outputs=3, name="sliced")
groups = []
for i in range(2):
    temp = mx.symbol.FullyConnected(net[i], num_hidden=2)
    groups.append(temp)
final_output = mx.symbol.Group(groups)

a = mx.viz.plot_network(final_output, shape={"data":(1, 3)}, node_attrs={"shape":'rect',"fixedsize":'false'})
a.render(view=True)
```
The error says " 
```
shape = shape_dict[key][1:]
KeyError: u'sliced_output
```
Is there anything wrong here?

**Comment by horserma** [comment]
Also when I used list_outputs() to see the names of output blocks, I found the name system was strange. If the number of channel is less than 10, the name is normal like "sliced_output0, sliced_output1 etc.". When it is bigger than 10, it becomes like "sliced_output:, sliced_output;" or even "sliced_outputA". It seems based on ASCII. Is the error due to this issue?

**Comment by liuzhi136** [comment]
@horserma Have you solve your problem with SliceChannel? I also meet the same problem just like you.

**Comment by horserma** [comment]
@liuzhi136 which one do you mean, to be more precise?

**Comment by luoruisichuan** [comment]
I follow the script on 
'https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar10-recipe.ipynb'
and input command 'mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsize':'false'}) '
and then get the error as following
'In [3]: mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsize
':'false'})
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-ed0839cfcbb0> in <module>()
----> 1 mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsize
':'false'})

d:\mxnet\python\mxnet\visualization.pyc in plot_network(symbol, title, shape, no
de_attrs)
     52         from graphviz import Digraph
     53     except:
---> 54         raise ImportError("Draw network requires graphviz library")
     55     if not isinstance(symbol, Symbol):
     56         raise TypeError("symbol must be Symbol")

ImportError: Draw network requires graphviz library   '

what is the problem?
thanks.

**Comment by heubme** [comment]
@luoruisichuan , maybe you should install PyGraphViz.
[Here](http://stackoverflow.com/questions/22722730/installing-pygraphviz-on-windows-python-2-7-graphviz-2-36) is the ref solved my problem like yours

**Comment by luoruisichuan** [comment]
@heubme  thanks very much!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
