### ISSUE TITLE
value ranges for 'max_random_illumination', 'max_aspect_ratio', etc

### ISSUE THREAD

**Issue by jonbakerfish** [apache/incubator-mxnet#2635]
[ImageRecordIter](http://mxnet.readthedocs.io/en/latest/packages/python/io.html#mxnet.io.ImageRecordIter) has a lot of parameters for augmentation. I'm not quite sure what is the reasonable value ranges for some parameters. E.g. `max_random_illumination` should range from [0,255] or [0,1]? How about `max_random_scale`, `max_aspect_ratio` and `max_shear_ratio`?

**Comment by leehonglak** [comment]
Bumping this ;-)
Any color on this would be very useful. Thanks!
