### ISSUE TITLE
When running amalgamtion in android studio suffering error?

### ISSUE THREAD

**Issue by zhangqianhui** [apache/incubator-mxnet#2636]
**jni/../mxnet_predict-all.cc:107736: Check failed: (dshape.Size()) == (size) Memory size do not match**

the model is mnist that is converted from caffe using the caffe_converter.

the shape is (1 , 1 28 ,28)

the json is 

{
  "nodes": [
    {
      "op": "null", 
      "param": {}, 
      "name": "data", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(5,5)", 
        "no_bias": "False", 
        "num_filter": "20", 
        "num_group": "1", 
        "pad": "(0,0)", 
        "stride": "(1,1)", 
        "workspace": "512"
      }, 
      "name": "conv1", 
      "inputs": [[0, 0], [1, 0], [2, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool1", 
      "inputs": [[3, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(5,5)", 
        "no_bias": "False", 
        "num_filter": "50", 
        "num_group": "1", 
        "pad": "(0,0)", 
        "stride": "(1,1)", 
        "workspace": "512"
      }, 
      "name": "conv2", 
      "inputs": [[4, 0], [5, 0], [6, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool2", 
      "inputs": [[7, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Flatten", 
      "param": {}, 
      "name": "flatten_0", 
      "inputs": [[8, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "ip1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "ip1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "FullyConnected", 
      "param": {
        "no_bias": "False", 
        "num_hidden": "500"
      }, 
      "name": "ip1", 
      "inputs": [[9, 0], [10, 0], [11, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu1", 
      "inputs": [[12, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "ip2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "ip2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "FullyConnected", 
      "param": {
        "no_bias": "False", 
        "num_hidden": "10"
      }, 
      "name": "ip2", 
      "inputs": [[13, 0], [14, 0], [15, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "prob_label", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "SoftmaxOutput", 
      "param": {
        "grad_scale": "1", 
        "ignore_label": "-1", 
        "multi_output": "False",
        "use_ignore": "False"
      }, 
      "name": "prob", 
      "inputs": [[16, 0], [17, 0]], 
      "backward_source_id": -1
    }
  ], 
  "arg_nodes": [0, 1, 2, 5, 6, 10, 11, 14, 15, 17], 
  "heads": [[18, 0]]
}

I need help .

**Comment by lsy17096535** [comment]
@zhangqianhui similar error , i got this error on ios.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
