### ISSUE TITLE
slicing along non-first axis of an ndarray and element updating 

### ISSUE THREAD

**Issue by kxf8608** [apache/incubator-mxnet#2654]
Hi, I wish to compute the batch_dot between one particular position (as rnn node) of one feature map A( batch , channel , i-1, j) (where i and j range at [1, 63] ) and weights W( batch , channel , i, j) (where i and j range at [0, 63]). However, ndarray does not support indexing except first axis slicing. 

I found out that there is a function "slice_axis" and successfully located elements that I want (in the previous case, it was batch_dot between a number of 64 by 64 ndarraies dot a number of 64 by 1 ndarraies). However, the output of "slice_axis" does not share the same memory of the input ndarray and thus prevents me updating the rnn node. How should I solve this problem please?

**Comment by tqchen** [comment]
The slice axis indeed copies the content, currently, what we can do was to write the update by concating the data back into the full content and write

**Comment by kxf8608** [comment]
@tqchen Hi, Tianqi, Thanks a lot for your answer! 

Suppose I want to change [[1,2,3],[4,5,6]] to [[1,2,3],[10,5,6]], am I supposed to do like this:
a = mx.nd.array([[1,2,3],[4,5,6]])
a_line = mx.ndarray.slice_axis(a,axis=0,begin=1,end=2)   //get the second line of a
a_line = a_line.T     //transpose
a_line[0:1] = 10     // change the element value
a_line = a_line.T   //transpose back
a_other_line = mx.ndarray.slice_axis(a,axis=0,begin=0,end=1)   //get other lines
b = mx.ndarray.concatenate([a_other_line,a_line],False)   //concatenate

Are there more succinct solutions please? Thanks!

**Comment by kxf8608** [comment]
This is okay when only one matrix is computed. However, when I do it batch-wise, or batch-and-channel wise, the concatenate function does not fit as it requires the dimension of the arrays to be the same only except the first.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
