### ISSUE TITLE
DataIter for lstm

### ISSUE THREAD

**Issue by KCHWang** [apache/incubator-mxnet#2670]
I am not really sure about the role of DataIter class in training a network. So my question is do I have to build my own iterator like "BucketSentenceIter" in https://github.com/dmlc/mxnet/blob/master/example/rnn/bucket_io.py.

I am implementing a many-to-many lstm, which is quite similar to the example in https://github.com/dmlc/mxnet/blob/master/example/rnn/char-rnn.ipynb. The only difference is that my output and input are not relevant. My input numpy.ndarray's shape is (200,15,18) and output numpy.ndarray's is (200,15,5). I have 200 examples. The seq_len is 15. Input feature is in 18d and output  results are  softmax possibilities of 5 varieties. Can I use iterator similar to BucketSentenceIter or mx.io.NDArrayIter? Thanks so much!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
