### ISSUE TITLE
Does mxnet support multiple threads well?

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2673]
when I create 100 threads, there will be one thread locked after several rounds. the whole program will be stopped.
how to solve it?

**Comment by javelinjs** [comment]
Do you mean that you are trying to run dist training in one process?

**Comment by tqchen** [comment]
The general idea of execution engine is to eliminate the need of multi threaded programming.. So it is in general not adviced to issue commands from multiple threads. It would be great if you can be more specific on your usecase

**Comment by starimpact** [comment]
It works fine when I use the version in May.

**Comment by tqchen** [comment]
The best way to proceed is to solve the problems :) The compilation error has already been fixed. It would be great if you can describe in more detail  what the problem is, or provide a script to reproduce the problem, so we can understand what is going on. Thanks

**Comment by starimpact** [comment]
Yes, you are right. :)

**Comment by starimpact** [comment]
The another problem:
The gpu utility is always 40% whether using one thread to run one network, or multiple threads to run multiple networks in parallel.
Is it normal ❓

**Comment by tqchen** [comment]
This really depend on your usecase..would be nice if you have a description on what exactly your usecase is. GPU was not very great at resource sharing and running small workloads concurrently, because CuDNN and most CUDA libs are optimized to fully utilize the GPU

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
