### ISSUE TITLE
Compilation faild in the newest 449e88e8a6

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2683]
src/operator/./cudnn_convolution-inl.h:404:56: error: too many arguments to function ‘cudnnStatus_t cudnnSetConvolutionNdDescriptor(cudnnConvolutionDescriptor_t, int, const int_, const int_, const int*, cudnnConvolutionMode_t)’
                                                  dtype_), CUDNN_STATUS_SUCCESS);

**Comment by piiswrong** [comment]
This is likely due to your cudnn version being too old. Any reason you can't update to a newer one?

**Comment by starimpact** [comment]
OK, I should use old version mxnet.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
