### ISSUE TITLE
compile issue using cmake (need std=c++11，not std=c++0x)

### ISSUE THREAD

**Issue by chenghuige** [apache/incubator-mxnet#2685]
Using cmake . then make
will fail, facing errors like below
mxnet/src/operator/./cudnn_convolution-inl.h(349): error: initialization with "{...}" is not allowed for object of type "std::vector<int, std::allocator<int>>"
          detected during:
            instantiation of "void mxnet::op::CuDNNConvolutionOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(48): here

The problem can be solved by modifying CMakeList.txt adding below

include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
else()
        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()

**Comment by piiswrong** [comment]
Thanks for reporting this.
Would you like to submit a PR with your fix?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
