### ISSUE TITLE
I suggest mxnet should give a milestone version periodically.

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2686]
we need a stable version. 
so I suggest mxnet gives a milestone version periodically.

**Comment by piiswrong** [comment]
there was a 7.0 release

**Comment by starimpact** [comment]
:+1:

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
