### ISSUE TITLE
How to understand the bucket_io.py's mission in lstm example ?

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#2687]
@pluskid Hi, I'm the new guy that learning to use mxnet. For now, I have read the lstm example for few days. Unfortunately, I can not understand the entile processing procedure. I have read the files about bucket_io.py, lstm.py  and lstm_bucketing.py. I can not understand the real meaning for "bucket" and struggle about it. I really need your help. Could you explain about it? I will be extremely appreciate if you could explain bucket_io.py's function for me.

**Comment by piiswrong** [comment]
sequence data samples have different lengths, thus require different network for each sample.
Bucketing is the process of sending samples to networks with corresponding lengths.

**Comment by liuzhi136** [comment]
@piiswrong Thank you first. I get this idea about it. Can I directly apply the bucket_io.py to my Question-Anwser system? Or I need implement my own DataIter? Because I can just understand the code in it partially. And Do you have some detailed tutials about how to build our own bucket? Thanks a lot.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
