### ISSUE TITLE
Versioning on MXNet

### ISSUE THREAD

**Issue by hotpxl** [apache/incubator-mxnet#2690]
I think I saw a previous issue on versioning so I'm just checking the status here. Can we have a version number on MXNet releases? This makes packages that depend on MXNet (like MinPy) much easier to specify the constraints. Also it would then be possible to release MXNet to PyPI or other package managers.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
