### ISSUE TITLE
mxnet NDArray slice op inconsistent with numpy

### ISSUE THREAD

**Issue by kikoqiu** [apache/incubator-mxnet#2693]
> import numpy as np
> import mxnet as mx
> a=np.arange(5)
> print(a[0:0])
> b=mx.nd.array(a)
> print(b[0:0].asnumpy())

np will output [], while ndarray will output [0,1,2,3,4]

**Comment by piiswrong** [comment]
```
>>> import numpy as np
>>> a = np.zeros((5,))
>>> a
array([ 0.,  0.,  0.,  0.,  0.])
>>> a[0:0]
array([], dtype=float64)
>>> 
```

**Comment by kikoqiu** [comment]
\>>> a[0:0]
array([], dtype=float64)
\>>> b=mx.nd.array(a)
\>>> b[0:0].asnumpy()
array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
