### ISSUE TITLE
MxNet/example/rcnn/demo.py  error

### ISSUE THREAD

**Issue by hollyholly5** [apache/incubator-mxnet#2694]
demo.py error shows:
Traceback (most recent call last):
  File "E:\2016prog\rcnnpython\demo.py", line 33, in <module>
    demo_net(detector, os.path.join(os.getcwd(), 'data', 'demo', '000004'))
  File "E:\2016prog\rcnnpython\tools\demo_net.py", line 33, in demo_net
    scores, boxes = detector.im_detect(im_array, roi_array)
  File "E:\2016prog\rcnnpython\rcnn\detector.py", line 46, in im_detect
    aux_states=None)#self.aux_params
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 783, in bind
    args_handle, args = self._get_ndarray_inputs('args', args, listed_arguments, False)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 625, in _get_ndarray_inputs
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args

How can I deal with it ?

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
Bind will issue this error when arguments are missing. Try listing `arg_params.keys()` and see if anything is missing. We uploaded a new demo for faster rcnn with a pretrained model. You are welcome to check that out.

**Comment by hollyholly5** [comment]
@precedenceguo Thank you very much for your response. 
I tried the pretrained model
 python demo.py --prefix final --epoch 0 --image 000004.jpg --gpu 0
I got errors:
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:33:23] d:\chhong\mxnet\src\operator\./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size)
Minimum workspace size: 1135104000 Bytes
Given: 536870912 Bytes
[15:33:23] D:\chhong\mxnet\src\engine\naive_engine.cc:28: Engine shutdown

so I wonder  this pretrained model requires what size of workspace. Sorry for the low level of my GPU: GTX 965

**Comment by precedenceguo** [comment]
Please consider use cudnn to avoid this problem.

**Comment by marcociccone** [comment]
Hi have the same issue, I cannot use cudnn on my board. Could you elaborate on this problem? What is related to?

**Comment by precedenceguo** [comment]
Please follow http://mxnet.io/api/python/symbol.html#mxnet.symbol.Convolution to set proper workspace for convolution.

**Comment by marcociccone** [comment]
Thank you for you help, now it’s working.

**Comment by wengyc** [comment]
I got the same error  ValueError: Must specify all the arguments in args,but i don't know how to deal with it.I use it in windows 10.I ran the command python demo.py --prefix final --epoch 0 --image myimage.jpg --gpu 0

**Comment by precedenceguo** [comment]
It means some parameters are missing. Please check everything is there in `arg_params` and `aux_params`.

**Comment by yasenvlsim** [comment]
How and where can I set proper workspace for convolution?

**Comment by precedenceguo** [comment]
Like this https://github.com/precedenceguo/mx-rcnn/blob/master/rcnn/symbol/symbol_vgg.py

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
