### ISSUE TITLE
avoiding jitter in loading data set

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#2706]
Hi All,

Are the data sets stored in the GPU after the first epoch or do they have to copied for every run?
I am running cifar10 and notice lot of fluctuations for every batch. 

If the data sets are copied for every new batch, is there a way to keep them on the GPU for all the epochs?

**Comment by piiswrong** [comment]
You can write a data iter that hold data on the gpu and feed a slice each time

**Comment by amithr1** [comment]
can you please point me to the relevant files/functions? I will give it a shot

**Comment by Yang507** [comment]
@piiswrong  hello,I have some captcha data and build lst and rec form, but I don't know how to write a iterator for my data while use example/warpctc/lstm_ocr.py, I also don't know if you run your data with mxnet and hope to be abel to get your answer, thank you!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
