### ISSUE TITLE
How to write out the file '.params' and '.json' if I customize my own training loop

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2716]
Hello,everyone.I wrote a script of a custom training loop according to the file" tutorial.ipynb" in the file of example/notebooks .But I don't know how to write out the file'.params' and '.jsom' for every epoch.I have written the "epoch-end_callback = mx.callback.do_checkpoint(prefix)" for every epoch.However it doesn't work.

Could  someone  give me some advise?Thank you so much

**Comment by huangzehao** [comment]
`    
checkpoint = mx.callback.do_checkpoint(prefix,1)
model.fit(
        X                  = train_iter,
        eval_data          = val_iter,
        eval_metric        = eval_metrics,
        kvstore            = kv,
        batch_end_callback = batch_end_callback,
        epoch_end_callback = checkpoint
        )
`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
