### ISSUE TITLE
implemente log_validation_metric callback function?

### ISSUE THREAD

**Issue by yitang** [apache/incubator-mxnet#2717]
Hello, I am new to mxnet and deep learning. I wonder if we shuold include `log_validation_metric` function in callback.py? 

By default, mxnet logs validation score after each epoch, and if we have `log_validation_metric` function, users would able to save validation score after each mini-batch by giving the function to `eval_batch_end_callback` argument.

**Comment by piiswrong** [comment]
validation metric is only computed at the end of epoch

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
