### ISSUE TITLE
how to get the value of 'mean_r'

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#2724]
in the script of 'mxnet/example/image-classification/train_imagenet.py' , there is 
# data

def get_iterator(args, kv):
    data_shape = (3, args.data_shape, args.data_shape)
    train = mx.io.ImageRecordIter(
        path_imgrec = os.path.join(args.data_dir, args.train_dataset),
        mean_r      = 123.68,
        mean_g      = 116.779,
        mean_b      = 103.939,
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        rand_crop   = True,
        rand_mirror = True,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)

but how to get the value of ' mean_r,  mean_g, mean_b' ?
and another question, the ' data_shape' is the size of the picture ?  for instance,  I have a picture with size of  1920_1080, then the   ' data_shape' should set be 3_1920_1080?
and if I crop the picture to the size 1080_1080, then the   ' data_shape' should set be 3_1080_1080? 
@mli 
thank your help.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
