### ISSUE TITLE
Pretrained model is unavailable

### ISSUE THREAD

**Issue by Bihaqo** [apache/incubator-mxnet#2729]
The link to the pretrained model for the full imagenet is broken.
The link is here: https://github.com/dmlc/mxnet/blob/master/docs/tutorials/imagenet_full.md
And it leads here: https://github.com/dmlc/mxnet-model-gallery/tree/master/imagenet-21k-inception

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
