### ISSUE TITLE
How to modify executor_manager.grad_arrays in model.py?

### ISSUE THREAD

**Issue by blazerygy** [apache/incubator-mxnet#2738]
I want to modify executor_manager.grad_arrays in model.py to do some experiments as the following code.

```
if nbatch % 2 == 0:           
   grad_array1 = copy.deepcopy(executor_manager.grad_arrays)                     
else:
   for i in range(len(grad_array1)):
      for j in range(len(grad_array1[i])):
          executor_manager.grad_arrays[i][j] = executor_manager.grad_arrays[i][j] + grad_array1[i][j]

   _update_params_on_kvstore(executor_manager.param_arrays, 
                             executor_manager.grad_arrays,
                             kvstore)

```

but it failed, I found MXNet using only the space which allocated initially to store the gradient, If I modify executor_manager.grad_arrays as shown above, the ndarray will point to the new space, so it failed, and the model can't converge.
So, how  to modify executor_manager.grad_arrays? Thx

**Comment by piiswrong** [comment]
executor_manager.grad_arrays[i][j][:] = executor_manager.grad_arrays[i][j] + grad_array1[i][j]
note the [:]

**Comment by blazerygy** [comment]
@piiswrong thanks a lot!

**Comment by blazerygy** [comment]
@piiswrong hi, I found "grad_array1 = copy.deepcopy(executor_manager.grad_arrays)" cost time much, is there any other ways to replace this?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
