### ISSUE TITLE
how to transfer data from one ndarray to another

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2740]
How to copy data of a ndarray to another ndarray directly ❓

**Comment by sxjscience** [comment]
@starimpact You can use `a[:] = b` to copy the data from `b` to `a`.

**Comment by starimpact** [comment]
but how to use it in C code.

**Comment by sxjscience** [comment]
@starimpact You can do it via `b = F<mshadow::op::identity>(a)`

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
