### ISSUE TITLE
Any special reason for the default initializer mx.init.Xavier(factor_type="in", magnitude=2.34) to take the magnitude 2.34?

### ISSUE THREAD

**Issue by taoari** [apache/incubator-mxnet#2749]
The Xavier initializer is mx.init.Xavier(factor_type="in", magnitude=3), and
The MSRA initializer  is mx.init.Xavier(factor_type="in", rnd_type="gaussian", magnitude=2).

Why the default initializer adopts a strange magnitude of 2.34, any special reason for this?

**Comment by srand99** [comment]
I don't think it is a good initializer, you should change it according to your model to avoid divergence.

**Comment by taoari** [comment]
@srand99 Thank you, but I think there should be some reasons to use 2.34, otherwise why not simply use the Xavier initializer that is mx.init.Xavier(factor_type="in", magnitude=3).

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
