### ISSUE TITLE
How to output variant size out_data in operator?

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2752]
Hi, guys,
I need to handle the bounding box calculation in the gpu side after operator RPN in the mxnet framework.
but the number of bounding box is variant.
the only way I can do is to fix the maximum number of bounding box.but I don't like it.
so, how to do it?

**Comment by piiswrong** [comment]
You can use bucketing

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
