### ISSUE TITLE
mxnet get stuck when training with 2-gtx1070

### ISSUE THREAD

**Issue by FighterLYL** [apache/incubator-mxnet#2760]
Hi, I use mxnet to train a model with 2 gtx1070, but it get stuck. It is normal when training with single gpu. I find it get stuck in `EvalMetric.update` function, to be precise, this line: `pred = pred.asnumpy()`. 
My computer environment: Ubuntu 14.04, cuda 8.0rc , cudnn 4.0. 
Is this problem caused by cuda? Thanks!

**Comment by sxjscience** [comment]
@FighterLYL Could you get a small verifiable example?

**Comment by albertyou2** [comment]
concern  to this issue

**Comment by FighterLYL** [comment]
@sxjscience you can use [train_mnist.py](https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_mnist.py) with option `--gpus 0,1`, the program will be stuck at [this line](https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L137) the third time get here.

**Comment by realwill** [comment]
@FighterLYL is the problem solved？

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
