### ISSUE TITLE
how to write the file of .params ever 10 epoch when using model.fit()

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2764]
I use the default solver "model.fit()" ,and  in it I set up the save parameter "epoch_end_callback=mx.callback.do_checkpoint(prefix)" .By default ,it writes out the file of .params for every epoch. However ,I want  it to write out the file of .params every 10 epoch or evey 20 epoch.And how to modify the parameters?

Thank you so much.

**Comment by magic282** [comment]
The following code is from mxnet/callback.py
You can see that there is a ```period``` argument.
```python
def do_checkpoint(prefix, period=1):
    """Callback to checkpoint the model to prefix every epoch.

    Parameters
    ----------
    prefix : str
        The file prefix to checkpoint to
    period : int
    	How many epochs to wait before checkpointing. Default is 1.

    Returns
    -------
    callback : function
        The callback function that can be passed as iter_end_callback to fit.
    """
    period = int(max(1, period))
    def _callback(iter_no, sym, arg, aux):
        """The checkpoint function."""
        if (iter_no + 1) % period == 0:
            save_checkpoint(prefix, iter_no + 1, sym, arg, aux)
    return _callback
```

**Comment by lugui2009** [comment]
@magic282  thank you .But when I wrote the the second argument,I got an error:

=========================================
 >>> prefix='aa'
>>> p=10
>>> cp=mx.callback.do_checkpoint(prefix,p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: do_checkpoint() takes exactly 1 argument (2 given)
========================================

**Comment by lugui2009** [comment]
@magic282 thank you .But when I wrote the the second argument,I got an error:

 ```
prefix='aa'
 p=10
 cp=mx.callback.do_checkpoint(prefix,p)
 Traceback (most recent call last):
 File "", line 1, in <module>
TypeError: do_checkpoint() takes exactly 1 argument (2 given)
```

**Comment by magic282** [comment]
@lugui2009 https://github.com/dmlc/mxnet/blob/master/python/mxnet/callback.py
Are you using the latest version?

**Comment by lugui2009** [comment]
@magic282 Oh,I see.I will update my version of mxnet .Thank you so much

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
