### ISSUE TITLE
CRF as RNN with permutohedral lattice

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#2771]
I have implemented high dimensional filtering for dense crf with permutohedral lattice approximation.
However, I don't have time to work on reproducing crf as rnn.

The code is here: https://github.com/piiswrong/permutohedral. the GPU implementation is 20x faster than cpu version (which is taken from the caffe implementation by the original author of crf as rnn paper).

If anyone want's to try reproducing crf as rnn please let me know.

@winstywang @tornadomeet

**Comment by tornadomeet** [comment]
@pluskid  refer to #337

**Comment by winstywang** [comment]
Will do that later, bot possibly not now.

**Comment by buptweixin** [comment]
Dose anybody has  already implemented it?

**Comment by buptweixin** [comment]
@piiswrong @tornadomeet @winstywang
