### ISSUE TITLE
run warpctc/lstm_ocr.py in CPU

### ISSUE THREAD

**Issue by anxingle** [apache/incubator-mxnet#2777]
I run lstm_ocr.py(cpu),
a@a:~/mxnet/example/warpctc$ python lstm_ocr.py 
But it shows the below message:

begin fit
2016-07-20 18:09:30,431 Start training with [cpu(0)]
iter
[18:09:30] /home/a/Downloads/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:09:30] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
[18:09:30] /home/a/Downloads/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:09:30] src/engine/./threaded_engine.h:306: [18:09:30] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:09:30] src/engine/./threaded_engine.h:306: [18:09:30] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. **Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)**

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
