### ISSUE TITLE
compile mxnet with Cuda7.5

### ISSUE THREAD

**Issue by anxingle** [apache/incubator-mxnet#2782]
I install cuda in /usr/local/cuda-7.5, and run ./deviceQuery pass;edit ~/.bashrc   like this:
export LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:/home/a/warp-ctc/build:/usr/local/cuda-7.5/lib64"
export PATH=/usr/local/cuda-7.5/bin:/home/a/anaconda2/bin:$PATH
and edit config.mk:
USE_CUDA=1
USE_CUDA_PATH=/usr/local/cuda-7.5
USE_BLAS=openblas
### But Terminal show the message:

g++ -std=c++11 -DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/a/GPU_mxnet/mxnet/mshadow/ -I/home/a/GPU_mxnet/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda /include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d

g++: error: /include: No such file or directory
make: **\* [build/src/resource.o] Error 1

**Comment by anxingle** [comment]
mxnet could install through  binary package like tensorflow: pip install --upgrade $TF_BINARY_URL or pip install mxnet.whl.  Install will be much more easy.

**Comment by sxjscience** [comment]
@anxingle The make should be fine. Maybe you are not running make under the MXNet directory?

**Comment by anxingle** [comment]
@sxjscience    Thank you. I run make in mxnet.  and I can run (compile ) mxnet in cpu model.

**Comment by chqsark** [comment]
@anxingle @sxjscience I'm having the same issue compiling mxnet using cuda-8.0. I can compile it in cpu mode. I'm running make in the mxnet root directory, and I've set cuda related path in config.mk

**Comment by chqsark** [comment]
I figured that when I chance USE_CUDA_PATH, there was an extra space. Everything works now.

**Comment by wukongHH** [comment]
how to fix it?

**Comment by No41Name** [comment]
Where can I found a guide to how enable CUDA compiling in R (for Windows)?
I've already installed CUDA 8.0, but then?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
