### ISSUE TITLE
missing script in example bi-lstm-sort

### ISSUE THREAD

**Issue by Bomme** [apache/incubator-mxnet#2783]
The [example on bidirectional LSTM](https://github.com/dmlc/mxnet/tree/master/example/bi-lstm-sort) misses the gen_data.py script that is referenced in the ReadMe
Maybe it did not get committed due to gitignore rules? 
@xlvector do you still have the script lying around?

**Comment by dianyancao** [comment]
I have the same problem,waiting for solution.

**Comment by dianyancao** [comment]
I am learning create grid-lstm layer by mxnet,this example helps lot with lstm bucketing.
I use following python code in './data/gen_data.py' to generate random numbers in [100,999],is it a right way to prepare the data and auto create labels by BucketSentenceIter.__iter__?
```
# coding:utf-8
import random

with open('./sort.train.txt','w') as f:
    for k in range(60000):
        f.write(' '.join([str(random.randint(100,999)) for i in range(5)]) + '\n')
with open('./sort.valid.txt','w') as f:
    for k in range(10000):
        f.write(' '.join([str(random.randint(100,999)) for i in range(5)]) + '\n')
```

**Comment by Ldpe2G** [comment]
I have asked xlvector before, here is the code:

import random

vocab = [str(x) for x in range(100, 1000)]

sw_train = open("sort.train.txt", "w")
sw_test = open("sort.test.txt", "w")
sw_valid = open("sort.valid.txt", "w")

for i in range(1000000):
    seq = " ".join([vocab[random.randint(0, len(vocab) - 1)] for j in range(5)])
    k = i % 50
    if k == 0:
        sw_test.write(seq + "\n")
    elif k == 1:
        sw_valid.write(seq + "\n")
    else:
        sw_train.write(seq + "\n")

sw_train.close()
sw_test.close()
sw_valid.close()

**Comment by xlvector** [comment]
Thanks!

**Comment by diggerdu** [comment]
@Ldpe2G 
THX

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
