### ISSUE TITLE
arguments in im2rec.py 

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#2787]
in the script of im2rec.py, there is sentence 
 'cgroup.add_argument('--chunks', type=int, default=1, help='number of chunks.')  '
 what is the function of 'chunks' ?

@piiswrong 

thanks for your help very much.

**Comment by piiswrong** [comment]
It means split the data into n parts

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by luoruisichuan** [comment]
what is the intention of spliting the data into n parts? can you give a example of spliting the data?
thank you.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
