### ISSUE TITLE
Cannot run C++ example on Win7.

### ISSUE THREAD

**Issue by anthony-han** [apache/incubator-mxnet#2792]
Hi everyone,

I cannot run the C++ example on Win7. There is no error during compilation. When running the program, it cannot enter the main function. However, the same program can run pretty well on Win10. Can anyone help?

Tony

**Comment by thirdwing** [comment]
@hjk41

**Comment by hjk41** [comment]
Are you using pre-compiled libmxnet.dll or did you compile it on your own?

**Comment by xxradon** [comment]
I have the same problem with @anthony-han  , @hjk41 and i use both  pre-compiled libmxnet.dll and  compiled it on my own,the problem is still there.

**Comment by basejn** [comment]
I have the same problem . If this line is in the code 
#include "mxnet-cpp/MxNetCpp.h"
The CMD windows starts but just freezes , without even entering the main function.
if a comment the include and all the code that uses it , the program runs ok (Just printf("Started\n"))

**Comment by hjk41** [comment]
This is usually caused by a mis-match in the DLL.
If you are using pre-compiled libmxnet.dll, you should download the
win10_x64_xxx releases instead of win2012_xxx. If you are building your own
dll, make sure you use the same machine/compiler/compiler options to
compile the DLL and the CPP code.

**Comment by GabbaGandalf** [comment]
I have the same problem when compiling mxnet on windows 7 (32 bit). The build works without any errors, but simple examples using the c api just freeze:
```cpp
#include <iostream>

extern "C" __declspec(dllimport) const char* MXGetLastError();
int main(){
	std::cout << "LAST ERROR: " << MXGetLastError() << std::endl;
	return 0;
}
```
The strange thing is the same executable (with same opencv, openblas, mxnet dlls) works without any problems on windows10 (32 and 64 bit).  
Additionally I tried not linking mxnet but loading the library manually like this: 
```cpp
#include <iostream>
#include <windows.h>
#include <tchar.h>

typedef const char*(* f_LAST)();

int main(){
    HINSTANCE proc = LoadLibrary(_T("libmxnet.dll"));
	if(proc) std::cout << "lib loaded" << std::endl;
	f_LAST last = (f_LAST)GetProcAddress(proc, "MXGetLastError");
	if (last) std::cout << "FUNC last error loaded : " << last() << std::endl;
	return 0;
}
```
This works on windows 7 and 10.

**Comment by zhyj3038** [comment]
@GabbaGandalf  but it seems the MXGetLastError function does not work  wither!  i saw womeone load  the dll dynamicly, but i donot know how to do it !

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by Tyill** [comment]
On Win7 statically does not work, the application hangs.
Dynamically normal.
Check yourself what's the matter there.
