### ISSUE TITLE
change Reshape'parameter target_shape to shape raise an error

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#2803]
When I try to change Reshape'parameter target_shape which not be supposed to shape, I get an error like below:
C:\Users\zliu\Desktop\rnn\lstm\test>python char_rnn.py
Summary of dataset ==================
bucket of len 129 : 8290 samples
C:\Users\zliu\Desktop\rnn\lstm\test\bucket_io.py:206: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  bucket_plan = np.hstack([np.zeros(n, int)+i for i, n in enumerate(bucket_n_batches)])
-------bucket_plan---------:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
init_states: [('l0_init_c', (32, 512)), ('l1_init_c', (32, 512)), ('l2_init_c', (32, 512)), ('l0_init_h', (32, 512)), ('l1_init_h', (32, 512)), ('l2_init_h', (32, 512))]
[13:48:52] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [13:48:52] d:\chhong\mxnet\src\operator./reshape-inl.h:220: Check failed: (oshape.Size()) == (dshape.Size()) Target shape size is different to s
ource. Target: 1
Source: 4128
Traceback (most recent call last):
  File "char_rnn.py", line 98, in <module>
    epoch_end_callback=mx.callback.do_checkpoint("obama"))
  File "C:\Python34\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "C:\Python34\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(*_input_shapes)
  File "C:\Python34\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, *_kwargs)
  File "C:\Python34\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "C:\Python34\lib\site-packages\mxnet-0.7.0-py3.4.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in reshape0: [13:48:52] d:\chhong\mxnet\src\operator./reshape-inl.h:220: Check failed: (oshape.Size()) == (dshape.Size()) Target shape size is different to source. Targe
t: 1
Source: 4128

Just beacuse I change the parameter's name, I receive this error. Does any one can help me? Any expalination will be appreciated.

**Comment by liuzhi136** [comment]
@pluskid @thinxer I just replace the code (1) with (2)
(1)
 label = mx.symbol.transpose(data=label)
 label = mx.symbol.Reshape(data=label, target_shape=(0,))
(2)
    label_slice = mx.symbol.SliceChannel(data=label, num_outputs=seq_len)
    label = [label_slice[t] for t in range(seq_len)]
    label = mx.symbol.Concat(*label, dim=0)
    label = mx.symbol.Reshape(data=label, shape=(0,))
This error just disappeard. Could anyone explain it? Thank alot for any explaination.

**Comment by sxjscience** [comment]
@liuzhi136 You need to use shape=(-1,)

**Comment by liuzhi136** [comment]
@sxjscience Code (1) used to make the similar form to the pred. Is that right? If it's right and I have read the doc page's explaination for default value 0. It seems like that:
"shape (, optional, default=()) – Target new shape. If the dim is same, set it to 0. If the dim is set to be -1, it will be inferred from the rest of dims. One and only one dim can be -1".
I think the result of code (1) will retain the same dimension. So, Why not 0?

**Comment by liuzhi136** [comment]
@sxjscience Unfortunately, I use shape=(-1,) and it's still not working. Do you have other solution for me? Thanks a lot for any reply.

**Comment by sxjscience** [comment]
@liuzhi136 I've changed https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L103 to `shape=(-1,)` and it runs well.

**Comment by pluskid** [comment]
There seem to be a recent change on the reshaping API if I recall correctly, is that so? @piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
