### ISSUE TITLE
I get extremely large training perplexity

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#2805]
I clone the lastest version from the github and follow the char-rnn.ipynb'step. But I get a very large training perplexity as same as below and it seems that each batch mini-batch's Train-Perplexity is the same value. Why?!

Summary of dataset ==================
bucket of len 129 : 8290 samples
mxnet-20160531-lastet\example\rnn\bucket_io.py:184: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  bucket_plan = np.hstack([np.zeros(n, int)+i for i, n in enumerate(bucket_n_batches)])
[16:37:56] d:\chhong\mxnet\src\operator./reshape-inl.h:227: Using target_shape will be deprecated.
04:37:56 INFO:Start training with [gpu(0)]
[16:37:56] d:\chhong\mxnet\src\operator./reshape-inl.h:227: Using target_shape will be deprecated.
[16:38:02] d:\chhong\mxnet\src\operator./reshape-inl.h:227: Using target_shape will be deprecated.
[16:38:02] d:\chhong\mxnet\src\operator./reshape-inl.h:227: Using target_shape will be deprecated.
04:38:54 INFO:Epoch[0] Batch [50]       Speed: 31.41 samples/sec        Train-Perplexity=10000000000.010738
04:39:46 INFO:Epoch[0] Batch [100]      Speed: 30.42 samples/sec        Train-Perplexity=10000000000.010738
04:40:39 INFO:Epoch[0] Batch [150]      Speed: 30.15 samples/sec        Train-Perplexity=10000000000.010738
04:41:33 INFO:Epoch[0] Batch [200]      Speed: 29.70 samples/sec        Train-Perplexity=10000000000.010738
04:42:28 INFO:Epoch[0] Batch [250]      Speed: 29.39 samples/sec        Train-Perplexity=10000000000.010738
04:42:37 INFO:Epoch[0] Resetting Data Iterator
04:42:37 INFO:Epoch[0] Time cost=275.005
04:43:33 INFO:Epoch[1] Batch [50]       Speed: 28.98 samples/sec        Train-Perplexity=10000000000.010738
04:44:31 INFO:Epoch[1] Batch [100]      Speed: 27.67 samples/sec        Train-Perplexity=10000000000.010738
04:45:24 INFO:Epoch[1] Batch [150]      Speed: 30.51 samples/sec        Train-Perplexity=10000000000.010738
04:46:16 INFO:Epoch[1] Batch [200]      Speed: 30.70 samples/sec        Train-Perplexity=10000000000.010738
04:47:08 INFO:Epoch[1] Batch [250]      Speed: 30.63 samples/sec        Train-Perplexity=10000000000.010738
04:47:17 INFO:Epoch[1] Resetting Data Iterator
04:47:17 INFO:Epoch[1] Time cost=280.155

I really don't know what's wrong with it. Could any one help me?
Any explanation will be greteful!

**Comment by sxjscience** [comment]
@liuzhi136 You can try to run the lstm_bucketing exmple

**Comment by liuzhi136** [comment]
@sxjscience It still very large.
2016-07-22 17:20:10,289 Epoch[0] Batch [50]     Speed: 266.81 samples/sec       Train-Perplexity=9999999999.999542
2016-07-22 17:20:14,221 Epoch[0] Batch [100]    Speed: 407.02 samples/sec       Train-Perplexity=9999999999.998825
2016-07-22 17:20:19,001 Epoch[0] Batch [150]    Speed: 334.79 samples/sec       Train-Perplexity=9999999999.999622
2016-07-22 17:20:23,412 Epoch[0] Batch [200]    Speed: 362.72 samples/sec       Train-Perplexity=9999999999.999296
Do you know the reason? I really upset about it.

**Comment by sxjscience** [comment]
@liuzhi136 I've just tried and the result is reasonable. Are you using the latest MXNet version?

**Comment by liuzhi136** [comment]
@sxjscience Yes, at first I didn't use the lastest version. Then, I get this problem, I download the lastest version and perform the code. It still happen. Could I have your weChat ID or other communication number? I want to talk to you directly.

**Comment by sxjscience** [comment]
@liuzhi136 You can first try the image classification examples and see whether they work or not.

**Comment by liuzhi136** [comment]
@sxjscience I have tried the MNIST example and other image CNN examples. They worked very well. This problem just occur when I run the lstm'code.

**Comment by sxjscience** [comment]
@liuzhi136 We can communicate via email first.

**Comment by liuzhi136** [comment]
@sxjscience liuzhi7936@sina.cn this is my email. Thank you so much for help me a lot. You are so kind. I'm thinking a problem. I download the version is pre-built version in win7. How's your version? Do you build it by yourself and set envrionment manually?

**Comment by sxjscience** [comment]
@liuzhi136 I'm usinh win10 and I've built from source. You can try building from the latest Github source first.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
