### ISSUE TITLE
where can i find rbm example by mxnet?

### ISSUE THREAD

**Issue by TimLindgren** [apache/incubator-mxnet#2811]
hi guys,
where can i find rbm example by mxnet.
thanks

**Comment by TimLindgren** [comment]
is there the implementation of DBN or RBM?

**Comment by sxjscience** [comment]
@TimLindgren Currently there is no such example. You can contribute one. (The Theano implementation may be helpful http://deeplearning.net/tutorial/rbm.html#sampling-in-an-rbm)

**Comment by godpgf** [comment]
@sxjscience This job will cost us a great deal of time, I want to use it by handle.

**Comment by godpgf** [comment]
@sxjscience If this job won't be done, I will do it.....

**Comment by sxjscience** [comment]
@godpgf Seems that there is no one on it currently. You are more than welcome to contribute an example.

**Comment by sxjscience** [comment]
@chzhour may have time to do it.

**Comment by machuck** [comment]
Any updates would be really appreciated!

**Comment by vishaalkapoor** [comment]
I realize this post is over a year old, I'm adding to it in case it helps anyone who's found this issue or in case it helps the original posters.

Here is an RBM library in Python, 

[pydbm-mxnet is Python library based on MXNet for building restricted boltzmann machine, deep boltzmann machine, and multi-layer neural networks.
](https://libraries.io/pypi/pydbm-mxnet 
)

and a series on Medium (so far just the first, keep tabs on the series for the second) that talks about RBMs with MXNet. 

[Python/MXNet Tutorial #1: Restricted Boltzmann Machines using NDArray.](https://medium.com/@MeTroFuN/python-mxnet-tutorial-1-restricted-boltzmann-machines-using-ndarray-f77578648ecf)

Vishaal

**Comment by vishaalkapoor** [comment]
@yzhliu Would you be able to close? Thank you!

**Comment by metrofun** [comment]
Second post on RBM in MXNet was low on my priority, but here is the code I wrote for the second post

https://gist.github.com/metrofun/5c76dc280b8ce19e56d673e19dc262c4

**Comment by yzhliu** [comment]
Close for now as @vishaalkapoor  and @metrofun provided several links. Feel free to reopen or create a new one if there's task we can track.

**Comment by asitstands** [comment]
Now an RBM example is included in MXNet. https://github.com/apache/incubator-mxnet/tree/master/example/restricted-boltzmann-machine
