### ISSUE TITLE
windows pre build update everyday

### ISSUE THREAD

**Issue by yajiedesign** [apache/incubator-mxnet#2813]
I am build some update in https://github.com/yajiedesign/mxnet/releases everyday
Running 2 months to work well, and now open to everyone.

**Comment by piiswrong** [comment]
Thanks a lot! This should be very helpful for windows users. @hjk41 Any idea how to merge this to main repo?

@yajiedesign Is the build based on your fork or dmlc:master everyday?

**Comment by yajiedesign** [comment]
yes

**Comment by albertyou2** [comment]
Very nice!

**Comment by wangg12** [comment]
@yajiedesign Can you share how you build the windows version with GPU support? I think it may be useful to others.

**Comment by yajiedesign** [comment]
@wangg12  install cuda, use cmake. check USE_CUDA

**Comment by wangg12** [comment]
@yajiedesign Which version of cmake and  build tool(mingw or vs) do you use?

**Comment by yajiedesign** [comment]
@wangg12 cmake 3.5.1 vs2013 cuda7.5 and 8.0 (i am use 8.0 and prebuild is 7.5)

**Comment by ufukcbicici** [comment]
Hello,

I am trying to use the prebuilt library by doing the following:
1) I download the latest build. Todays is 20160919_mxnet_x64_gpu
2) I copy the contents (include,lib,python folders) into the current installation of the mxnet, the 20160531_win10_x64_gpu one. I overwrite all the files.
3)I delete the mxnet installation from python site-packages folder.
4) I go into the python folder of the overwritten mxnet installation, open the console and install the library with python setup.py install command.

Whenever I try to import the mxnet library in python then, I get the following error:
`Connected to pydev debugger (build 145.1504)
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/ufuk.bicici/Desktop/Projects/Mnist Experiments/train_mnist.py", line 2, in <module>
    import mxnet as mx
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pydev\_pydev_bundle\pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "C:\Users\ufuk.bicici\AppData\Local\Continuum\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pydev\_pydev_bundle\pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "C:\Users\ufuk.bicici\AppData\Local\Continuum\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Users\ufuk.bicici\AppData\Local\Continuum\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\ufuk.bicici\AppData\Local\Continuum\Anaconda2\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\ufuk.bicici\AppData\Local\Continuum\Anaconda2\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Belirtilen mod�l bulunamad

It seems like a dll is missing, which causes ctypes to crash. Any ideas how to fix it?

Many thanks.`

**Comment by MaticsL** [comment]
@yajiedesign I got the Error 126 too.
```
In [1]: import mxnet
C:\mxnet\python\mxnet\../../lib/libmxnet.dll
C:\mxnet\python\mxnet\../../lib/libmxnet.dll
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-1-30eb4f951ea5> in <module>()
----> 1 import mxnet

C:\mxnet\python\mxnet\__init__.py in <module>()
      5
      6 from .context import Context, current_context, cpu, gpu
----> 7 from .base import MXNetError
      8 from . import base
      9 from . import ndarray

C:\mxnet\python\mxnet\base.py in <module>()
     41 __version__ = libinfo.__version__
     42 # library instance of mxnet
---> 43 _LIB = _load_lib()
     44
     45 # type definitions

C:\mxnet\python\mxnet\base.py in _load_lib()
     33     """Load libary by searching possible path."""
     34     lib_path = libinfo.find_lib_path()
---> 35     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     36     # DMatrix functions
     37     lib.MXGetLastError.restype = ctypes.c_char_p

C:\Anaconda\lib\ctypes\__init__.pyc in LoadLibrary(self, name)
    443     def LoadLibrary(self, name):
    444         print name
--> 445         return self._dlltype(name)
    446
    447 cdll = LibraryLoader(CDLL)

C:\Anaconda\lib\ctypes\__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    364         if handle is None:
    365             print name
--> 366             self._handle = _dlopen(self._name, mode)
    367         else:
    368             self._handle = handle

WindowsError: [Error 126]
```
It seems that the dll file `libmxnet` is not found.

**Comment by yajiedesign** [comment]
@MaticsL check dependency dll,opencv,cuda.cudnn,openblas.etc
you must put dll in PATH or python dir.

**Comment by MaticsL** [comment]
@yajiedesign  Thanks a lot. I use `depends walker` to check dependency of `libmxnet` and find that the dll file `cudnn64_4.dll` is missing. So the reason is that I am using cudnn v3, not v4. Now it works. Maybe this can help with many other people.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
