### ISSUE TITLE
About Distribute training data path (without distribute file system)(chinese,english)

### ISSUE THREAD

**Issue by albertyou2** [apache/incubator-mxnet#2815]
@mli @piiswrong 

我有两台电脑，一台是MACPRO一台是PC 使用WINDOWS10系统
两台机器都在同一个局域网并且SSH可连通
I have to computers the one is mac book pro the other is PC(windows10)
They are both in one local network.And they can communicate with each other by ssh. 

我MAC上做了测试如下命令可以运行单机版的分布式训练
I can run distribute training on each computer separately by using this command:

python /Users/zuekiWork/Documents/mxnet/tools/launch.py -n 1 --launcher ssh -H hosts.txt python train_albertnet.py  --kv-store dist_sync --data-dir="/Users/zuekiWork/Documents/mxnet_code”

但是到两台机器，我就迷茫了 ：
1.如果不使用分布式文件系统，我是否需要在两台电脑各自持有一份本地的训练数据？还是说有一个机器持有训练数据就可以了？
2.我应该怎样写我的mx.io.ImageRecordIter呢？考虑到launch.py只有一个地方传入训练数据路径，我该如何在上述命令中指定每个机器的--DATA--DIR 呢（这里还有一个问题，两个操作系统的路径格式都不一样）
3.最终的模型和参数保存在那个机器上呢？

可能还有很多和我一样的人有这样的问题，如果能做成一个完整的LOCAL分布式训练的例子，真的不胜感激!

I am now confusing about dristibute training on two machines in local network:
1. Should I maintain 1 copy of training data for each computer?how to write the mx.io.ImageRecordIter?
2.How to path the --data-dir argument for each computer?
3.Which machine will save the model ?

**Comment by albertyou2** [comment]
does any one knows how to do this job?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
