### ISSUE TITLE
import mxnet error

### ISSUE THREAD

**Issue by stevenhanjun** [apache/incubator-mxnet#2818]
When I use mxnet to write code with python, it gives me this error.
![3a46b304-89c2-45ac-88f4-816aa1f8b0cf](https://cloud.githubusercontent.com/assets/4454187/17082913/e07eb82a-51c0-11e6-88cb-3ef38b8498e4.png)

and I have write 'export PYTHONPATH=~/mxnet/python' in .bash_profile. I don't know how to solve this problem?
![c89aad79-45df-4335-8019-4177acda3df4](https://cloud.githubusercontent.com/assets/4454187/17082930/1e1b4446-51c1-11e6-8c40-bf5b76afe926.png)

**Comment by piiswrong** [comment]
your mxnet is not built correctly

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
