### ISSUE TITLE
about the using of mx.symbol.Concat

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#2819]
in the script of 'mxnet/cifar10-recipe.ipynb at master · dmlc/mxnet  https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar10-recipe.ipynb',
there is the function as following,
# A Simple Downsampling Factory

def DownsampleFactory(data, ch_3x3):
    # conv 3x3
    conv = ConvFactory(data=data, kernel=(3, 3), stride=(2, 2), num_filter=ch_3x3, pad=(1, 1))
    # pool
    pool = mx.symbol.Pooling(data=data, kernel=(3, 3), stride=(2, 2), pool_type='max')
    # concat
    concat = mx.symbol.Concat(*[conv, pool])
    return concat

if I write another 'A Simple Downsampling Factory', get rid of 'mx.symbol.Concat' , as following

def DownsampleFactory1(data, ch_3x3):
    # conv 3x3
    conv = ConvFactory(data=data, kernel=(3, 3), stride=(2, 2), num_filter=ch_3x3, pad=(1, 1))
    # pool
    pool = mx.symbol.Pooling(data=conv, kernel=(3, 3), stride=(2, 2), pool_type='max')
     return pool

what is the difference between DownsampleFactory and DownsampleFactory1?
another primitive question, what is the function of 'pad=(1, 1)' in conv?
thanks for your help very much.
@wangg12

**Comment by wangg12** [comment]
@luoruisichuan This function is not written by me, so I can only share some ideas of mine. Convolution with stride > 1 can do downsample and max pooling can also do downsample. If you just put the max pooling after the conv, the size of feature maps will decrease more faster. 

If you take a look into the [paper](http://www.cs.unc.edu/~wliu/papers/GoogLeNet.pdf) where GoogLeNet was proposed and look at the inception modules of it, you will understand that the DownsampleFactory is somewhat like the inception module where a multi-branch and concat strategy is used. 

By the way, in my understanding, the `pad=(1,1)` in conv means to zero-pad the feature maps with size 1 in height and width fed into conv.

Correct me if I am wrong.
Thanks.

**Comment by luoruisichuan** [comment]
sorry,  I didnot expressed my problem correctly.
My question is what is the difference between the two function--DownsampleFactory and DownsampleFactory1?  one uses  'mx.symbol.Concat' , and the other not.
thanks .

**Comment by wangg12** [comment]
I think I've explained this above.

**Comment by luoruisichuan** [comment]
thanks for your help very much.

**Comment by tornadomeet** [comment]
@luoruisichuan in your DownsampleFactory, the down sampling scale is 2, but in your DownsampleFactory1, the down sampling scale is 4

**Comment by luoruisichuan** [comment]
@wangg12
I run the above script ( 'mxnet/cifar10-recipe.ipynb at master · dmlc/mxnet), and use the visualization command 
'''mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsize':'false'}) '''
but the result just  
''':mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsize':'fals
e'})
:--
Out[1]: <graphviz.dot.Digraph at 0x8895860>
'''
if I want get the graph , I need another command?
thanks.

**Comment by wangg12** [comment]
@luoruisichuan Did you run the codes before the viz line? Because the number in your "Out[1]" is only 1.

**Comment by luoruisichuan** [comment]
I have run the codes before the viz line and the viz line in ipython with %cpaste. I expect the result is the network arichitecture graph, but the rusult is a setence.

thanks.

**Comment by luoruisichuan** [comment]
I have run the codes before the viz line and the viz line in ipython with %cpaste. I expect the result is the network arichitecture graph, but the rusult is a setence.

thanks.

**Comment by wangg12** [comment]
@luoruisichuan If you run it in ipython, you may need to use this:
```
 g=mx.viz.plot_network(xxxxxxxxxx)
 g.view()
```
And you will see the result in the corresponding directory.
If you run it in jupyter notebook, the graph will show bellow your code block.

**Comment by luoruisichuan** [comment]
in ipython, I use the following command,
'''   
  55   g=mx.viz.plot_network(symbol=softmax,node_attrs={'shape':'oval','fixedsi
ze':'false'})
---> 56   g.view()
'''
and then get the error informtion,
'''
C:\Users\Administrator\Anaconda2\lib\site-packages\graphviz\files.pyc in view(se
lf)
    246             The (possibly relative) path of the rendered file.
    247         """
--> 248         rendered = self.render()
    249         self._view(rendered, self._format)
    250         return rendered

C:\Users\Administrator\Anaconda2\lib\site-packages\graphviz\files.pyc in render(
self, filename, directory, view, cleanup)
    224                 raise RuntimeError('failed to execute %r, '
    225                     'make sure the Graphviz executables '
--> 226                     'are on your systems\' path' % cmd)
    227             else:  # pragma: no cover
    228                 raise

RuntimeError: failed to execute ['dot', '-Tpdf', '-O', 'plot.gv'], make sure the
 Graphviz executables are on your systems' path
'''
I can  'import grapyviz' correctly.
and even when I add '  C:\Users\Administrator\Anaconda2\Lib\site-packages\graphviz;' into the system path,
it still get the error information.
what is wrong?

thanks.

**Comment by wangg12** [comment]
@luoruisichuan I just tested it on my windows machine and it works fine.

**Comment by luoruisichuan** [comment]
'''
By the way, in my understanding, the pad=(1,1) in conv means to zero-pad the feature maps with size 1 in height and width fed into conv.
'''
if pad=(3,3), then it  means to zero-pad the feature maps with size 3 in height and width fed into conv?
@wangg12
thanks.

**Comment by wangg12** [comment]
@luoruisichuan Yes, if pad = (3,3), it will add zeros outside each feature map by 3 circles.
