### ISSUE TITLE
Error on Python  Document 

### ISSUE THREAD

**Issue by anxingle** [apache/incubator-mxnet#2820]
In this page [Python tutorial](http://mxnet.readthedocs.io/en/latest/packages/python/tutorial.html), we can see:
'''
We can also construct a symbol in a more flexible way than the single forward composition exemplified above.

> > > net = mx.symbol.Variable('data')
> > > net = mx.symbol.FullyConnected(data=net, name='fc1', num_hidden=128)
> > > net2 = mx.symbol.Variable('data2')
> > > net2 = mx.symbol.FullyConnected(data=net2, name='net2', num_hidden=128)
> > > composed_net = net(data=net2, name='compose')
> > > composed_net.list_arguments()
> > > ['data2', 'net2_weight', 'net2_bias', 'compose_fc1_weight', 'compose_fc1_bias']
> > > '''   

But in my ipython notebook ,it shows: ['data2', 'net2_weight', 'net2_bias', 'fc1_weight', 'fc1_bias'].   Hope you can revise it ( and other small tiny errors ).

**Comment by tornadomeet** [comment]
@anxingle yes, you are right, the same here. you can give a PR for this, file is https://github.com/dmlc/mxnet/blob/master/docs/packages/python/tutorial.md

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
