### ISSUE TITLE
mac os install Mxnet error:symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by pjpan** [apache/incubator-mxnet#2821]
while command : make -j8，report error;
Undefined symbols for architecture x86_64:
  "cv::imencode(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)", referenced from:
      _main in ccvZTcls.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by magicyb2016** [comment]
I also met the same problem. is there any solution?

**Comment by pjpan** [comment]
my system version is  Os X El Capitan 10.11.6 (15G31). no one help to solve this problem.

**Comment by burness** [comment]
I have met this problem too and i can't solve this problem

**Comment by pjpan** [comment]
mxnet doesn't support Os X El Capitan 10.11.6  yet，see when will they update their code.Be patient.

**Comment by pangeran-bottor** [comment]
same error in OS X El Capitan 10.11.5, any update @pjpan ?

**Comment by burness** [comment]
@Walid-Ahmed  CUDA seems only support the nvidia cards

**Comment by tornadomeet** [comment]
same error in OSX EI 10.12.3, build from source with `USE_OPENCV = 1`, cannot solve it! @piiswrong   

if try ```make -stdlib=libstdc++````after this error, then it will build the lib success, but actually `bin/im2rec` cant run.

**Comment by formath** [comment]
Also the same problem in OSX EI 10.12.5. Reinstall opencv can't solve this problem.

**Comment by szha** [comment]
We now provide OSX pre-built pip packages, which has opencv support. See instructions here: https://mxnet.incubator.apache.org/get_started/install.html
