### ISSUE TITLE
Why MXNet update parameters according to the key in dist_async？

### ISSUE THREAD

**Issue by blazerygy** [apache/incubator-mxnet#2825]
Traditional asynchronous, parameter server update the model parameter as a whole, but MXNet update parameter according to the key, in the case of multimachine, this way will lead to the case a worker pull down the model parameters but its keys are not the same version, why MXNet implement dist_async in this way? The model convergence can be better?

**Comment by blazerygy** [comment]
@piiswrong @mli

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
