### ISSUE TITLE
char-rnn

### ISSUE THREAD

**Issue by GeorgeXia1828** [apache/incubator-mxnet#2828]
I am reading the code of https://github.com/dmlc/mxnet/blob/master/example/rnn/char-rnn.ipynb
I am wondering the sym_gen
`# generate symbol for a length
def sym_gen(seq_len):
    return lstm_unroll(num_lstm_layer, seq_len, len(vocab) + 1,
                       num_hidden=num_hidden, num_embed=num_embed,
                       num_label=len(vocab) + 1, dropout=0.2)`
why the input_size of one-hot is len(vocab)+1 not len(vocal) ? and so the num_label?

**Comment by eric-haibin-lin** [comment]
Hmm, the most recent code doesn't have the `+ 1`. 
https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm_bucketing.py#L39

@pluskid @antinucleon  notebook outdated?

**Comment by pluskid** [comment]
+1 is probably reserving a special symbol for zero-padding. If you break your data into equal length chunks, there is no need for padding. But if you use variable-length sentence, and use Bucketing, probably you will need an extra symbol for padding.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
