### ISSUE TITLE
Has the high level API for autoencoder in R implemented?

### ISSUE THREAD

**Issue by MikeHuYimin** [apache/incubator-mxnet#2841]
I saw somebody asked about the API for auto-encoder and wondered whether there were already some for it. And if I want to built the auto-encoder using the symbols layer by layer, how can I add the sparse penalty into the cost function?  BTW, can I use RBM to set the weights for auto-encoder in mxnet?

Thanks a lot!

**Comment by rajafan** [comment]
Looking forward to it too.

**Comment by terrytangyuan** [comment]
@thirdwing seems to have some progress on this. Could you share some updates?

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please close this, it is being tracked here - https://github.com/apache/incubator-mxnet/issues/1518
