### ISSUE TITLE
Runtime varies with different versions of CUDA

### ISSUE THREAD

**Issue by ghost** [apache/incubator-mxnet#2848]
When I run my code which is built with mxnet and cuda-8.0, the speed is quite slow. However, when it runs with cuda-7.5, the speed is much faster.

Does it mean that mxnet for now is not capable with cuda-8.0?

**Comment by sxjscience** [comment]
@Cdyzhao Could you provide the script for benchmarking?

**Comment by Cdyzhao** [comment]
@sxjscience The examples like MNIST with mlp can have this problem. The GPU is GeForce GTX TITAN X.

**Comment by sxjscience** [comment]
@Cdyzhao What's the training speed for Cuda 7.5 and 8.0 on your computer?

**Comment by Cdyzhao** [comment]
@sxjscience The training speed is about 1 min for Cuda 7.5, while 10 min for 8.0. (Using mlp to train MNIST dataset.)

**Comment by sxjscience** [comment]
@Cdyzhao I'm using CUDA 8.0 + GTX 980 TI + Windows 10 and the training speed for CIFAR10 (`python train_cifar10.py`) is about 1120.45 samples/sec. Could you compare the speed of CUDA 7.5 and CUDA 8.0 on CIFAR10? MNIST is rather small and may not be suitable for benchmarking.
