### ISSUE TITLE
Get a zero matrix from output layer when using GPU.

### ISSUE THREAD

**Issue by NKUCodingCat** [apache/incubator-mxnet#2855]
I run a script to train an CNN network, Everything looks good. However, when [@wplct](https://github.com/wplct) use GTX 765M to run this file, the array passed to Accuracy function are all 0, I don't konw if it's a bug but he got correct result when run the script with CPU.

System: Windows 10 Pro
MXnet Pkg: 20160531_win10_x64_gpu.7z in release page
Python: anaconda2 4.1.1 (64-bit)

How to repeat this issue : run `python cnn_ocr.py` in the zip , change Line146 of cnn_ocr.py to select devices

The output of using CPU/GPU included.

Thanks for the GFW. I save the zip to Onedrive https://1drv.ms/u/s!AiEbtKTwM8EbhQ1oKHtQ3zsMoVR6
eventually, since I can  not drag and drop to upload files github

**Comment by taoari** [comment]
I encounter similar issues before. Just compile your own version from source code, and the problem is solved.

**Comment by CheungXu** [comment]
@NKUCodingCat I met the same problem. It seems that it is caused by different version of libmxnet.dll. This issue [issue #2045](https://github.com/dmlc/mxnet/issues/2045) may be helpful to you.

**Comment by lofrank** [comment]
I get zero matrics when select gpu 1, while it's OK when select gpu 0.
So in my case, it's not caused by different version of libmxnet.dll.
I can't find solution until now.
Any advice is appreciate, thanks.

> >>> a = mx.nd.ones((2,3),mx.gpu(0))
>>> print a.asnumpy()
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
>>> a = mx.nd.ones((2,3),mx.gpu(1))
>>> print a.asnumpy()
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
>>> a = mx.nd.ones((2,3),mx.cpu(0))
>>> print a.asnumpy()
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
>>>

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
