### ISSUE TITLE
NDArray header in SAVE and LOAD function:

### ISSUE THREAD

**Issue by gaush123** [apache/incubator-mxnet#2860]
Hi,

In the code below, in Save function while storing the value of NDArray, default value of header is set to `kMXAPINDArrayListMagic = 0x112`; Whereas in LOAD function if header value is set to be kMXAPINDArrayListMagic, it will provide `CHECK(header == kMXAPINDArrayListMagic)
      << "Invalid NDArray file format";` related issue. Do I need to pass on some custom value as head to successfully load the NDArray value.

`const uint64_t kMXAPINDArrayListMagic = 0x112;

void NDArray::Save(dmlc::Stream\* fo,
                   const std::vector<NDArray>& data,
                   const std::vectorstd::string& names) {
  uint64_t header = kMXAPINDArrayListMagic, reserved = 0;
  fo->Write(&header, sizeof(header));
  fo->Write(&reserved, sizeof(reserved));
  fo->Write(data);
  fo->Write(names);
}

void NDArray::Load(dmlc::Stream\* fi,
                   std::vector<NDArray>\* data,
                   std::vectorstd::string\* keys) {
  uint64_t header, reserved;
  CHECK(fi->Read(&header))
      << "Invalid NDArray file format";
  CHECK(fi->Read(&reserved))
      << "Invalid NDArray file format";
  CHECK(header == kMXAPINDArrayListMagic)
      << "Invalid NDArray file format";
  CHECK(fi->Read(data))`

**Comment by starimpact** [comment]
```header``` must be ```kMXAPINDArrayListMagic```.
It has no problem.

**Comment by sds6** [comment]
@gaush123 Is this resolved ? I get a mismatch error when loading a downloaded Vgg19.params file -https://github.com/dmlc/mxnet/tree/master/example/neural-style

I was confused because of the same reason. If header is saved as kMXAPINDArrayListMagic why is there an error thrown for reading kMXAPINDArrayListMagic when loading?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by 91Eric** [comment]
Is this resolved ? I get a mismatch error when loading a downloaded resnet50.params files @gaush123 @sds6
