### ISSUE TITLE
Why is num_epoch the parameter of FeedForward initializer instead of parameter of fit method in python model api

### ISSUE THREAD

**Issue by Azure-Vani** [apache/incubator-mxnet#2871]
I think it's will be more straightforward if pass num_epoch to `fit` method instead of pass it to `FeedForward` class initializer, because num_epoch shouldn't be regarded as an attribution of model. It's a training argument. 

The current implementation is inconvenient if I want to train a model on a training data  for several epochs and then train the model on another train data for epochs. 

There is same issue on `initializer` and `optimizer` parameter

**Comment by pluskid** [comment]
@Azure-Vani Agreed. You could look at our new [module API](http://mxnet.readthedocs.io/en/latest/packages/python/module.html), parameters like `num_epoch` are now in the `fit` function instead of the constructor of the model.

**Comment by Azure-Vani** [comment]
@pluskid Thanks for updating. Will look into it :)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
