### ISSUE TITLE
why it cost much more time why it cost much more time between finish epoch and save checkpoint when run multimachine when loading much more data?

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#2874]
Running on sync mode.
About loading 1days, it will only cost 10s betwwen finish epoch and save checkpoints.
About loading 10days,it cost 87s ,and loading 15days data to memory,it will cost 152s

It seem there has relevant with larger data.Is it reasonably?

**Comment by starimpact** [comment]
can you specify your question specifically?

**Comment by liumilan** [comment]
i add some code on python about nd.save.
toc3 = time.time()
nd.save(param_name, save_dict)
toc4 = time.time()
logging.info('nd[%d] nd save param cost=%.3f', epoch, (toc4 - toc3))

@starimpact

**Comment by starimpact** [comment]
the size>

**Comment by liumilan** [comment]
what u mean?
As I said, the much more data loaded,it cost much more time to save
@starimpact

**Comment by starimpact** [comment]
it is normal.
the data transfer from gpu and cpu is slower as your data is bigger.

**Comment by liumilan** [comment]
but in fact is it only up to batchsize?
the batchsize is equal.
What i means is that loading more data before start trainning.
@starimpact

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
