### ISSUE TITLE
bin/im2rec does not support bmp format file

### ISSUE THREAD

**Issue by cleardusk** [apache/incubator-mxnet#2878]
I read the `bin/im2rec` code, it only support jpeg/png format. I want to add bmp and other format support, but I'm not familiar with the the details of mxnet's image-record-io.
Can anyone add bmp and other format support or give some instructions to implement it?

**Comment by starimpact** [comment]
bmp is very memory consuming, why not to convert it to jpg or png.

**Comment by cleardusk** [comment]
Because `bmp` format is not compressed. If i want to keep all the pixel info, I can not use `jpeg`.
`png` seems to support loss-compression and lossness-compression, but I'm not sure whether `bin/im2rec` supports png lossness-compression.

**Comment by starimpact** [comment]
int im2rec.cc, it use ```cv::Mat img = cv::imdecode(decode_buf, color_mode);``` to get image data. this function supports bmp file also.
I think you just have a try to change some code to let im2rec support bmp.

**Comment by cleardusk** [comment]
OK, I'll give it a try : )

**Comment by piiswrong** [comment]
png is loss less. You only need to add an option to make it use png. I suggest using the python version since it's easier to work with

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
