### ISSUE TITLE
how to creat a arbitrary rnn layer

### ISSUE THREAD

**Issue by chenboheng** [apache/incubator-mxnet#2886]
If I want to creat a rnn layer like this, and set the recurrence=5, does is easy to create this rnn operation by mxnet interface? 
![image](https://cloud.githubusercontent.com/assets/20148944/17276899/646c1aa4-5768-11e6-8612-31f1ae4cad7b.png)
Where can I get the tutorial to construct the rnn layer?

**Comment by piiswrong** [comment]
mx.sym.RNN

**Comment by sxjscience** [comment]
@chenboheng It can be implemented by sharing the weight/bias symbols. The LSTM example may be helpful https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L17-L113 .

**Comment by starimpact** [comment]
@piiswrong mx.sym.RNN hasn't been implemented.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
