### ISSUE TITLE
How to calculate the computation and communication time of one iteration?

### ISSUE THREAD

**Issue by blazerygy** [apache/incubator-mxnet#2889]
I want to calculate the computation and communication time of one iteration, code as follows(in model.py):

```
computation_begin = time.time()

executor_manager.forward(is_train=True)
executor_manager.backward()

computation_end = time.time()
print "computation_time = %.6f" % (computation_end - computation_begin)

communication_begin = time.time()

if update_on_kvstore:
    _update_params_on_kvstore(executor_manager.param_arrays,
                              executor_manager.grad_arrays,
                              kvstore)
else:
    _update_params(executor_manager.param_arrays,
                   executor_manager.grad_arrays,
                   updater=updater,
                   num_device=len(ctx),
                   kvstore=kvstore)

communication_end = time.time()
print "communication_time = %.6f" % (communication_end - communication_begin)
```

and then I train cifar10:
`../../tools/launch.py -n 2 -s 1 python train_cifar10.py --batch-size 128 --lr 0.1 --lr-factor .94 --num-epoch 1 --kv-store dist_sync`

the result is:

```
computation_time = 0.000288
communication_time = 0.004348
```

the time is too short, not conform to the actual, so how to calculate can be accurate? Thx

**Comment by piiswrong** [comment]
Everything is async in mxnet, so these timer won't give you actual time cost
You can try nvprof to see how much idle time there is

**Comment by ysh329** [comment]
mark

**Comment by eric-haibin-lin** [comment]
You could give the profiler a try. Set USE_PROFILER=1

On 2017年4月5日, at 01:14, Shuai Yuan <notifications@github.com> wrote:

mark

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
