### ISSUE TITLE
there are same result in each  epoch  training

### ISSUE THREAD

**Issue by windelu** [apache/incubator-mxnet#2891]
i use the mxnet/example/notebooks/tutorial.ipynb code
load the [titanic ](https://www.kaggle.com/c/titanic/) train data (892,delete the string data like name ,and change the male to 1 ,the famale to 0) and use LogisticRegressionOutput, and get the result link this: 
why each accuracy is the same, and what can i do to gave a good result . whether i should use another classifier like SVM or another, thank you !!

epoch 0 iter 20 metric ('accuracy', 0.65625)
epoch 0 iter 40 metric ('accuracy', 0.621875)
epoch 0 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 0 iter 80 metric ('accuracy', 0.609375)
epoch 0 iter 100 metric ('accuracy', 0.615)
epoch 1 iter 20 metric ('accuracy', 0.65625)
epoch 1 iter 40 metric ('accuracy', 0.621875)
epoch 1 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 1 iter 80 metric ('accuracy', 0.609375)
epoch 1 iter 100 metric ('accuracy', 0.615)
epoch 2 iter 20 metric ('accuracy', 0.65625)
epoch 2 iter 40 metric ('accuracy', 0.621875)
epoch 2 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 2 iter 80 metric ('accuracy', 0.609375)
epoch 2 iter 100 metric ('accuracy', 0.615)
epoch 3 iter 20 metric ('accuracy', 0.65625)
epoch 3 iter 40 metric ('accuracy', 0.621875)
epoch 3 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 3 iter 80 metric ('accuracy', 0.609375)
epoch 3 iter 100 metric ('accuracy', 0.615)
epoch 4 iter 20 metric ('accuracy', 0.65625)
epoch 4 iter 40 metric ('accuracy', 0.621875)
epoch 4 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 4 iter 80 metric ('accuracy', 0.609375)
epoch 4 iter 100 metric ('accuracy', 0.615)
epoch 5 iter 20 metric ('accuracy', 0.65625)
epoch 5 iter 40 metric ('accuracy', 0.621875)
epoch 5 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 5 iter 80 metric ('accuracy', 0.609375)
epoch 5 iter 100 metric ('accuracy', 0.615)
epoch 6 iter 20 metric ('accuracy', 0.65625)
epoch 6 iter 40 metric ('accuracy', 0.621875)
epoch 6 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 6 iter 80 metric ('accuracy', 0.609375)
epoch 6 iter 100 metric ('accuracy', 0.615)
epoch 7 iter 20 metric ('accuracy', 0.65625)
epoch 7 iter 40 metric ('accuracy', 0.621875)
epoch 7 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 7 iter 80 metric ('accuracy', 0.609375)
epoch 7 iter 100 metric ('accuracy', 0.615)
epoch 8 iter 20 metric ('accuracy', 0.65625)
epoch 8 iter 40 metric ('accuracy', 0.621875)
epoch 8 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 8 iter 80 metric ('accuracy', 0.609375)
epoch 8 iter 100 metric ('accuracy', 0.615)
epoch 9 iter 20 metric ('accuracy', 0.65625)
epoch 9 iter 40 metric ('accuracy', 0.621875)
epoch 9 iter 60 metric ('accuracy', 0.6083333333333333)
epoch 9 iter 80 metric ('accuracy', 0.609375)
epoch 9 iter 100 metric ('accuracy', 0.615)
 and the main function is:

 batch_size = 8
    hidden = 5
    h1 = 10
    h2 = 15
    h3 = 1
    epoch = 10
    learningrate = 0.1
    net1 = createNetWorkL1(hidden=hidden)
    net3 = createNetWorkL3(h1=h1,
                          h2=h2,
                          h3=h3
                          )
    myNN(
        train_path=train_path,
        test_path=test_path,
        net=net3,
        batch_size=batch_size,
        epochs=epoch,
        learningrate=learningrate
    )

**Comment by starimpact** [comment]
find the problem by yourself. :smile:

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
