### ISSUE TITLE
path_imgrec accepts multiple .rec files?

### ISSUE THREAD

**Issue by wshenx** [apache/incubator-mxnet#2893]
It seems that mxnet supports multiple .rec files in `path_imgrec` as suggested in https://github.com/dmlc/dmlc-core/blob/d0afb8e946dda3310e6ed062a59f97726bf4c565/src/io/input_split_base.cc#L97
The separator is ';'. Am I correct? @piiswrong @tqchen 
BTW, I remember @tqchen onced pointed out that `path_imgrec` also accepts directory as input. So both ways are correct?

**Comment by N01Z3** [comment]
I checked: `path_imgrec` accepts directory with multiple .rec files

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
