### ISSUE TITLE
CPU RNN Symbol

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#2895]
@piiswrong, @sxjscience, @antinucleon, @pluskid : I am ready to start implementing a CPU version of mx.sym.RNN symbol introduced in #2401. My thoughts on this now:

1) We should build this up from existing ops, even if its slower. First, optimized CPU versions are likely to come from Intel in the future (via DAAL package). Second, it will allow us to more easily add new algorithms to the RNN symbol (like memory networks, etc) that are not supported by cuDNN.

2) Given the performance benefits of being able to call cuDNN (and most RNN problems are compute-limited), many people will want to start using the RNN symbol for applications. Its rather annoying at the moment in that it has no CPU mode in any language binding. 

3) As mentioned previously: this project will add first-class RNN support to MXNet, which means that this has to implemented once and all language bindings will benefit. It is also conceptually simpler to use than current RNN examples. So its worthwhile putting some effort into this. 

Some questions:

Q1: does anyone have time to work on this with me?
Q2: do others agree with the philosophy outlined above (ie that we should implement this from existing OPs)?
Q3: If we decide to build this symbol out of existing symbols (and thus avoid defining a derivative), how exactly would I implement this? @piiswrong [mentioned](https://github.com/dmlc/mxnet/issues/2401#issuecomment-225470060) that we can handle this on the C++ side: 

> ... chain up other operators in the c++ side. You just need to dispatch the Tblobs correctly.

I would really appreciate some help getting started with this: I can't find another example of a symbol implementation that is built up from other symbols.

**Comment by piiswrong** [comment]
If you want to chain up c++ operators, I think you can create a bunch of them from the RNN operator and pass TBlobs around them. This hasn't been done before but I don't see any reason why it shouldn't work

**Comment by sbodenstein** [comment]
@piiswrong: are you referring to using this interface (https://github.com/dmlc/mxnet/blob/master/include/mxnet/operator.h) explicitly? So you would need two separate functions: one for the forward chain of ops, and one for the backward chain?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
