### ISSUE TITLE
A problem when I build 

### ISSUE THREAD

**Issue by ftxj** [apache/incubator-mxnet#2896]
![image](https://cloud.githubusercontent.com/assets/17945397/17297867/1a836af0-583a-11e6-9770-7d4632398590.png)

使用cmake生成项目后，vs2013中编译出现该问题，我应该如何处理？

After using cmake to build the project, and compile by vs2013 appear this problem occurs, what should I do?

**Comment by piiswrong** [comment]
try reinstall openblas

**Comment by Dianxj** [comment]
thanks and I found this problem is because I used openblas_win64_int_32 but should use openblas_win64_int_64

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
