### ISSUE TITLE
How to pass a none-ndarray to the backward function in a operator?

### ISSUE THREAD

**Issue by dianyancao** [apache/incubator-mxnet#2901]
I am doing instance-aware text image segmentation.One pixel may belong to multiple instances or multiple classes.For each pixel in a text image,I assign a label set and a instance id set to it,this is a set but not an array.So I write convert function to convert them from both ndarray and set.
Is there a good way to pass a none-ndarray to backward function in a operator effectively?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
