### ISSUE TITLE
Facing issue with dmlc::Stream::Create

### ISSUE THREAD

**Issue by amanaman118** [apache/incubator-mxnet#2912]
Below is what i am getting upon running  below code in predictor.cc class

```
const char* fPath = env->GetStringUTFChars(filePath, 0);
const char* fFlag = env->GetStringUTFChars(fileFlag, 0);
dmlc::Stream *fStream = dmlc::Stream::Create(fPath, fFlag);
```

Issue generated is as below

```
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN4dmlc6Stream6CreateEPKcS2_b" referenced by "/data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so"...
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at org.dmlc.mxnet.Predictor.<clinit>(Predictor.java:5)
```

**Comment by amanaman118** [comment]
@SlipknotTN can you help me with this issue.

**Comment by phunterlau** [comment]
@amanaman118 which `gcc` version do you use? is it `gcc-5` or 4.8 something?

**Comment by phunterlau** [comment]
@amanaman118 seems like you have updated some package but the old link libs are not yet removed, so the code is trying to link to an old lib but failed. It usually happens on `dmlc-core` since it is one of the most dependent. Please check out a very fresh repo and try again.

**Comment by amanaman118** [comment]
Hello @phunterlau ,

Below is my gcc version

```
Amans-MacBook-Pro:platform-tools aman$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Well i have been building amalgamation part of mxnet, i haven't changed anything in dmlc-core. Even though i would give it a try again with fresh repo.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
