### ISSUE TITLE
Which iterator(s) support loading a label file by batch for parallel training?

### ISSUE THREAD

**Issue by dafukua** [apache/incubator-mxnet#2916]
I'm working on some image classification project. I have a giant label file (multi-label, >100 GB) to load during training. It looks to me that `ImageRecordIter` loads all the labels from the label file once directly into RAM, which does not fit into the best machines (64GB RAM) I've got.

Can I know how I can modify the code to make the label file to be loaded by batch in `ImageRecordIter`? Or is there any other iterator I can use for such a purpose?

Thanks.

**Comment by piiswrong** [comment]
There are two ways you can do it.
1. modify ImageLabelMap in src/io/iter_image_recordio.cc to use a database
2. write your own data iter in python following /plugin/opencv/opencv.py:ImageListIter. You can use a database to store the data and labels or use recordio and pack data and label into the same record using self defined datastructure.

**Comment by EasonD3** [comment]
Thanks, @piiswrong. Can you please give more details about the first way using a database? For the second way, I just quickly checked `ImageListIter`, but it seems it does not has data partition stuffs that are to be used by parallel training?

**Comment by piiswrong** [comment]
@EasonD3 ImageLabelMap in src/io/iter_image_recordio.cc read the whole label file on init and Find() return label given index. You can change it to open a database on init and return label from database.
You can use leveldb, lmdb, or rocksdb for this

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
