### ISSUE TITLE
Customized loss function in R

### ISSUE THREAD

**Issue by kosta501** [apache/incubator-mxnet#2922]
How can I make customized loss function in R? For example i want to use weighted mean squared loss

**Comment by thirdwing** [comment]
Have you tried to write a new `metric`?

See https://github.com/dmlc/mxnet/blob/master/R-package/R/metric.R for examples.

**Comment by khalida** [comment]
When I follow [this example](http://mxnet.io/tutorials/r/fiveMinutesNeuralNetwork.html#next-steps) for using a custom evaluation metric; i.e. passing an argument to `eval.metric` in a call to `mx.model.FeedForward.create()`, I can see the custom evaluation metric reported during the training, but it does not change the training of the model.

Is it possible to define a custom layer in `R` so that we can train a network to minimize some other loss function?

**Comment by thirdwing** [comment]
Sorry that I misunderstood you. You should use `mx.symbol.MakeLoss`.

**Comment by thirdwing** [comment]
I provide a simple example in https://github.com/dmlc/mxnet/blob/master/docs/tutorials/r/CustomLossFunction.md

Please check that.

**Comment by khalida** [comment]
Many thanks for the simple example. This will definitely help me and others to make use of `mx.symbol.MakeLoss`

**Comment by ChrisBotella** [comment]
@thirdwing , Sorry if I missed something, but in your tutorial, which besides that is really clear, you didn't indicate what is the nature of the variable `label` that appears in :  
`lro <- mx.symbol.MakeLoss(mx.symbol.square(mx.symbol.Reshape(fc1, shape = 0) - label))`

Of course when I execute your code  i get the error : 
`mx.varg.symbol.MakeLoss(list(...)) : object 'label' not found`

I guess `label` is a kind of MXNET symbolic variable associated with the `y` parameter that we give to `mx.model.FeedForward.create` for optimization.  So how did you defined `label`?  

Plus, to go further, how you define and manipulate this variable in the multilabel case, ie when `y` is a matrix.

**Comment by ChrisBotella** [comment]
Ok I found issue #6596, and some other which create the symbol `label = mx.symbol.Variable('label')` and it works. 

However, i still don't understand how `mx.model.FeedForward.create` function understands it must replace of the variable `label`  with the values of parameter `y`...
