### ISSUE TITLE
FCN32s: crop offset is different from the berkeley released network.

### ISSUE THREAD

**Issue by zeakey** [apache/incubator-mxnet#2925]
I test FCN32s with my own data,  I guarantee that the image/label are of the same size, and caffe works well with the data.

But When I fit the Mxnet version of fcn32s demo to my data, an error occurs:

>  Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height

It's obviously that the crop offset is some too big.

So I continuously check the crop offset parameter,  in https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/symbol_fcnxs.py#L65 I find the offset of 'FCN32s' is 34.

BUT here https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/pascalcontext-fcn32s/train.prototxt#L517 the official released FCN32s the crop offset is 19.

I think that once the network architecture is determined, the crop offset is fixed, so why the offset of Mxnet version of FCN32s and official released are different ?

Is there some distinction between official FCN32s and Mxnet version of FCN32s ?

**Comment by zeakey** [comment]
@tornadomeet  I think you can help solve this problem.

**Comment by tornadomeet** [comment]
@zeakey hello, thanks for your test,  
i write fcn-xs last year, at that time i implement it learn from caffe to  calc  the offset of crop layer automatic,  so i just learn the code from caffe : https://github.com/shelhamer/caffe/blob/918ac729c5f513e6bb477db74e64d0eb6ecc7f12/include/caffe/util/coords.hpp#L52, the caffe code there actually has bug, so my code has a bug too, i suspect with it at that thime , and  i gave a  commit in https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/symbol_fcnxs.py#L5, but i forget to solve it.  

so you can use the commit line of https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/symbol_fcnxs.py#L5 instead, which is :  
```python
def filter_map(kernel=1, stride=1, pad=0):
    return (stride, (kernel-stride)/2-pad)
```

**Comment by tornadomeet** [comment]
i 'll give a pr for this, but it's maybe influence the pre-trained model.

**Comment by tornadomeet** [comment]
@zeakey  should be fixed by : https://github.com/dmlc/mxnet/pull/2926

**Comment by zeakey** [comment]
@tornadomeet  OK, I'll update the code and test again. Thanks for quick response!

**Comment by zhenzhen1022** [comment]
recently, I came to MXNet. I trained fcn-xs today, but I got an error, here is the log:
[16:40:25] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
[16:40:25] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:40:25] src/engine/./threaded_engine.h:306: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:40:25] src/engine/./threaded_engine.h:306: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

I looked  the offset is 19, so how to solve the problem? looking forward your help

**Comment by tornadomeet** [comment]
@zhenzhen1022  https://github.com/dmlc/mxnet/pull/3654

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by baijin93** [comment]
@tornadomeet Is it correct to use `center_crop=True` here instead of manually computing the `offset`s?
