### ISSUE TITLE
How to use the multi-label version of SoftmaxOutput?

### ISSUE THREAD

**Issue by dafukua** [apache/incubator-mxnet#2928]
I'd like to train Inception-BN by using a multi-label dataset. I've learned that in SoftmaxOuput in the Inception-BN symbol file [[link](https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_inception-bn.py#L81)], I need to set `multi_output=True`, i.e.,

``` python
softmax = mx.symbol.SoftmaxOutput(data=fc1, multi_output=True, name='softmax')
```

After adding that change, when I ran my code, I got the following error:

```
mxnet.base.MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(128,500), inferred shape=(128,1)
```

where `128` is the batch size and `500` is the number of labels I have.

Can anyone please advise how I can make the multi-label version of SoftmaxOutput work?

Thanks.

**Comment by novog** [comment]
You might find some of the following discussion useful:

#647
#910 (includes a link to code for a multilabel softmax layer; I haven't tried it yet)

I just posted a related question (#2929) about using an NDArrayIter with grouped outputs.

**Comment by EasonD3** [comment]
#647 and #2929 are multi-task learning and not quite related to my question. Well, I could consider each class in my problem as a binary task, but I've got hundreds of classes at hand...

I think [multilabel-layer-mxnet](https://github.com/jimxinbo/multilabel-layer-mxnet) can be used for my problem. But according to #1658, it seems MXNet can directly deal with that.

**Comment by novog** [comment]
Okay, yes, the method described in #1658 does look useful. If I understand properly, it does have the limitation that the number of possible classes in the network will be the same for each label. If the actual number of classes for each label varies, I think it should still work; it will simply never learn to predict any of the unused class indexes for each label. However, it seems like it could be inefficient if, for example, the data had a large number of binary labels and then a few labels with up to 1000 possible classes.

**Comment by EasonD3** [comment]
@novog, agreed. Thanks for the comment.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
