### ISSUE TITLE
A problem during training

### ISSUE THREAD

**Issue by zhqshen** [apache/incubator-mxnet#2930]
While I tried to use the train_imagenet.py training alexnet with my own data, the application was crashed. The computer used GTX 970 under windows 10. Anyone know why?
![image](https://cloud.githubusercontent.com/assets/20835063/17423787/495e75be-5af0-11e6-8859-f3c490967824.png)
![image](https://cloud.githubusercontent.com/assets/20835063/17423791/57441b70-5af0-11e6-9b69-e49b59dc89ba.png)

And I can run the example train_cifar10.py and train_mnist.py properly.

**Comment by hoaphumanoid** [comment]
Have you checked the memory consumption?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
