### ISSUE TITLE
How I can set different 'lr_mult' for weight and bias in one layer?

### ISSUE THREAD

**Issue by lugui2009** [apache/incubator-mxnet#2932]
I set up one layer ,for example ,fc1=mx.symbol.Fullyconnected(data=data,name='fc1',num_hidden=64)
There are two parameters of this layer : weight and bias。I want to set different 'lr_mult'  for these two 
parameters . for example,'lr_mult'='0.1' for weight ,and 'lr_mult'='1' for bias. 

What should I write the code for this purpose ? Thank you .

**Comment by piiswrong** [comment]
```
fc1=mx.symbol.Fullyconnected(data=data,name='fc1',num_hidden=64, attr={'weight_lr_mult':'0.1', 'bias_lr_mult':'1.0'})
```

**Comment by lugui2009** [comment]
@piiswrong thank you so much

**Comment by lugui2009** [comment]
@piiswrong I used this code .How,maybe I got the wrong attributions as follows.
![mymistake](https://cloud.githubusercontent.com/assets/20158014/17467932/85417470-5d55-11e6-9d61-36447665cf45.jpg)
Why I got the 'fc1_bias_bias_lr_mult' ,'fc1_weight_weight_lr_mult' and so on.

**Comment by piiswrong** [comment]
those are harmless

**Comment by lugui2009** [comment]
@piiswrong Thank you very much .I see

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by pilhoon** [comment]
It looks some changes are. You can use a simple `var`

```python
w=mx.sym.var(lr_mult=0.1)
b=mx.sym.var(lr_mult=0.1)
fc1=mx.symbol.Fullyconnected(data=data,name='fc1',num_hidden=64, weight=w, bias=b)
```
