### ISSUE TITLE
UVA and Access data from another device

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#2942]
CUDA allows access another device's GPU memory without doing copy and allocate a copy buffer, can be helpful sometimes

see 
- http://on-demand.gputechconf.com/gtc-express/2011/presentations/cuda_webinars_GPUDirect_uva.pdf
- https://github.com/dmlc/mxnet/issues/2919

Should be simple and just turn on some options and remove a few checks on operations have to be on same device to function

**Comment by jermainewang** [comment]
I remember to enable GPUDirect on the same machine, just simply call [`cudaDeviceEnablePeerAccess` ](http://horacio9573.no-ip.org/cuda/group__CUDART__PEER_g9e5ea65a18938c2b8715a5602105c306.html) and then all the memory copies will automatically use GPUDirect. 
The example code is in `cuda_sdk/samples/1_Utilities/p2pBandwidthLatencyTest`. 
Do we have some kind of initialization part of all the mxnet contexts? If so, we could add the code there.

**Comment by mli** [comment]
just use `cudaDeviceEnablePeerAccess` can accelerate things one some hardwares.  using cpu direct, e.g. performing + on two ndarrays on different gpus, seems doesn't affect the performance comparing to first copy and then execute, but potentially reduce gpu memory usage.

for the latter, we need to disable the context check at https://github.com/dmlc/mxnet/blob/master/src/operator/operator_util.cc#L886

in this case, we need to set a flag on some place p2p is enabled, so do not check here. any suggestion?

**Comment by tqchen** [comment]
Change it to something like context compatible checker function.
