### ISSUE TITLE
how can I use C++example with per-build and mxnet.cpp

### ISSUE THREAD

**Issue by ftxj** [apache/incubator-mxnet#2949]
when I use MxnetTestApp.sln I can run mlp.cpp success,but when I replace mlp.cpp with other example such as googlenet.cpp ,there is a problem.
![image](https://cloud.githubusercontent.com/assets/17945397/17460328/93063360-5c93-11e6-908f-21fb145e8a9a.png)
![image](https://cloud.githubusercontent.com/assets/17945397/17460332/a6d3e64e-5c93-11e6-85cf-24e1ad83a69b.png)

**Comment by hjk41** [comment]
It seems you are using the CPU-only version of pre-built library and you
used GPU device in the code. You can either use the GPU version library or
use only CPU device in the code.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
