### ISSUE TITLE
problem about  'mx.callback.do_checkpoint'

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#2950]
to get the imformation about training procedure , I use the following script,
''' model_prefix = "d:/test/cifar_100"
   model.fit(X=train_dataiter,
           eval_metric="accuracy",
          epoch_end_callback=mx.callback.do_checkpoint(model_prefix))  '''
 but get the following error imformation,
'''  MXNetError: [09:42:11] d:\chhong\mxnet\src\storage./cpu_device_storage.h:44: Ch
eck  notnull: ptr   '''
and more information about error is like this,
''' 
C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\b
ase.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78
     79 def c_str(string):
'''
but if I get rid of ''' epoch_end_callback=mx.callback.do_checkpoint(model_prefix) ''', then the training procedure is OK.
what is wrong?
thanks.

**Comment by luoruisichuan** [comment]
and the whole imformation of error is following,
'''
[09:42:11] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [09:42:11] d:\c
hhong\mxnet\src\storage\./cpu_device_storage.h:44: Check  notnull: ptr
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-3-8bb7ab063571> in <module>()
      1 model.fit(X=train_dataiter,
      2            eval_metric="accuracy",
----> 3            epoch_end_callback=mx.callback.do_checkpoint(model_prefix))

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\m
odel.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_en
d_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    743
    744         arg_names, param_names, aux_names = \
--> 745                 self._init_params(dict(data.provide_data+data.provide_la
bel))
    746         param_idx2name = {}
    747         for i, n in enumerate(param_names):

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\m
odel.pyc in _init_params(self, input_shapes, overwrite)
    492
    493         param_name_shapes = [x for x in zip(arg_names, arg_shapes) if x[
0] in param_names]
--> 494         arg_params = {k : nd.zeros(s) for k, s in param_name_shapes}
    495         aux_params = {k : nd.zeros(s) for k, s in zip(aux_names, aux_sha
pes)}
    496

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\m
odel.pyc in <dictcomp>((k, s))
    492
    493         param_name_shapes = [x for x in zip(arg_names, arg_shapes) if x[
0] in param_names]
--> 494         arg_params = {k : nd.zeros(s) for k, s in param_name_shapes}
    495         aux_params = {k : nd.zeros(s) for k, s in zip(aux_names, aux_sha
pes)}
    496

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\n
darray.pyc in zeros(shape, ctx, dtype)
    686         The created NDArray.
    687     """
--> 688     arr = empty(shape, ctx, dtype)
    689     arr[:] = 0.0
    690     return arr

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\n
darray.pyc in empty(shape, ctx, dtype)
    511     if ctx is None:
    512         ctx = Context.default_ctx
--> 513     return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
    514
    515 def add(lhs, rhs):

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\n
darray.pyc in _new_alloc_handle(shape, ctx, delay_alloc, dtype)
     63         ctypes.c_int(int(delay_alloc)),
     64         ctypes.c_int(int(_DTYPE_NP_TO_MX[np.dtype(dtype).type])),
---> 65         ctypes.byref(hdl)))
     66     return hdl
     67

C:\Users\Administrator\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\b
ase.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78
     79 def c_str(string):

MXNetError: [09:42:11] d:\chhong\mxnet\src\storage\./cpu_device_storage.h:44: Ch
eck  notnull: ptr
'''
@pqn   @piiswrong 

thanks.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
