### ISSUE TITLE
Why mxnet need so much memory?

### ISSUE THREAD

**Issue by zhqshen** [apache/incubator-mxnet#2969]
Hi, all
    I used alexnet to train my own data, gpu is GTX 970, sample number (train + validation) is 10648, data shape is (3,244,244), the GPU memory is 1600-1700MB, but the system memory is over 13GB while training, what's the problem? How to reduce memory consuming?
![image](https://cloud.githubusercontent.com/assets/20835063/17503104/c6ad4d1a-5e1f-11e6-884e-65a0f0d1e77a.png)

**Comment by mli** [comment]
it's virtual memory

**Comment by zhqshen** [comment]
I checked, it was not the virtual memory, if I increase the sample number, the python.exe will crash due to not enough memory, and the total memory is 16GB.

**Comment by mli** [comment]
got it. did you read the whole dataset into memory? or using .rec format. what's your batch size?

**Comment by piiswrong** [comment]
@tqchen ImageRecordIter seems to be doing too much prefetching which is over engineering now that networks are usually big enough.

**Comment by zhqshen** [comment]
The batch size is 32, .rec format is used as the data input.

**Comment by zhqshen** [comment]
How to cut the memory requirement? For example, change the parameter?

**Comment by Godricly** [comment]
#2111 as a reference.

**Comment by zhqshen** [comment]
@Godricly thanks a lot.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
