### ISSUE TITLE
Beyond virtual memory limits On Yarn(GPU)

### ISSUE THREAD

**Issue by coder-james** [apache/incubator-mxnet#2970]
when i run train_mnist.py on yarn using gpu, it will need much virtual memory (e.g. 160GB). Through process-tree for container i see that run python script need  so much memory. So i think python script may want more GPU resources and yarn try to stop this dangerous behavior. 
To solve this problem , I must set yarn.nodemanager.vmem-check-enabled to false which i think it may be not a good way. Any Advices?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
