### ISSUE TITLE
GPU-util not stable

### ISSUE THREAD

**Issue by magic282** [apache/incubator-mxnet#2976]
Hi,

I am training a seq2seq model. I observed that the GPU util(output of nvidia-smi Volatile GPU-Util) is not as stable as other tools, i.e. Theano.
The util changes between [70%, 95%]. When I used Theano, the GPU-util roughly stays at 98% or 99%.
Is this related to IO? I tried to increase the batch size from 32 to 256, but it did not help. Or poorly implemented model?
Any hints? 

Thanks.

**Comment by antinucleon** [comment]
I think it may due to call ```asnumpy``` and sync write, eg ```a[:] = b``` too often, this will block async execution. We will provide a high level API for seq2seq.

**Comment by antinucleon** [comment]
Another issue I notice is we are not using batch-dot now. Switch to batch dot will reduce cuda call and improve performance.

**Comment by antinucleon** [comment]
Another potential issue is kernel fusion. I think it can be solved by using CuDNN RNN op and a C++ implementation of RNN. I am doing a refactor on general RNN API.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
