### ISSUE TITLE
enabling different optimizers for train_cifar10.py

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#2980]
Hi All,

How can I enable different optimizers for train_cifar10 ? For example, AdaGrad ?

**Comment by Godricly** [comment]
U need to change train_model.py a little bit to enable this. There is a [parameter](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L415) to do this.

**Comment by VoVAllen** [comment]
You can use your own optimizer in this way.

```
opt = mx.optimizer.SGD(
    learning_rate=0.01,
    momentum=0.9,
    wd=0.00001)

model.fit(data,opt, ...)
```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
