### ISSUE TITLE
GPU memory cannot be released 

### ISSUE THREAD

**Issue by anthony-han** [apache/incubator-mxnet#2981]
Hi,

I use the C++ APIs of MXNet to do some classification tasks. But I find that MXNet does not release GPU memory when calling MXPredFree(). When my program exits, all occupied GPU memory is released. So when I run my program, I can do classification just once, otherwise GPU memory is not enough. I think this is a very serious problem. I hope MXNet developers @tqchen @mli @piiswrong can look into this issue and resolve it ASAP. Thanks!

BTW, I used the latest source code to build MXNet library.

Tony

**Comment by piiswrong** [comment]
memory release is async. could you post your code?

**Comment by piiswrong** [comment]
A minimal reproducing example would be helpful

**Comment by anthony-han** [comment]
@piiswrong You can try the C++ example "image-classification-predict.cc". GPU memory will not be released after MXPredFree().

**Comment by anthony-han** [comment]
void Predict()
{
    MXPredCreate();
    MXPredSetInput();
    MXPredForward();
    MXPredGetOutput();
    MXPredFree();
}

@piiswrong Suppose you have a function "Predict", and its maximum GPU memory consumption is 1GB. After you call Predict(), the occupied GPU memory will not be released. If you call Predict() again, then memory occupied will be 2GB. After you program terminates, all the memory will be released finally.

**Comment by feiyulv** [comment]
@anthony-han  Has your problem be solved? It seems #3055 just solved the problem of cpu memory leak, but for gpu predict, the problem still exists@piiswrong

**Comment by feiyulv** [comment]
@anthony-han  Has your problem be solved? It seems #3055 just solved the problem of cpu memory leak, but for gpu predict, the problem still exists @piiswrong

**Comment by neodooth** [comment]
@feiyulv I think you can change src/storage/storage.cc line 76
from
`ptr = new storage::GPUPooledStorageManager();`
to
`ptr = new storage::NaiveStorageManager<storage::GPUDeviceStorage>();`

It seems that GPUPooledStorageManager will use up nearly all gpu memory, for speedup

**Comment by neodooth** [comment]
In my opinion, naivestorgemanager is more intuitive and convenient; sometimes i just need to launch multiple jobs on a single gpu, and by using gpupooledstoragemanager, the processes often end up with memory allocation error (size of input images change and the memory rarely can be reused). I think a better strategy should be introduced @piiswrong

**Comment by eldercrow** [comment]
Thanks a lot @neodooth for this comment. I've been suffering for the same out of memory issue and it is now solved. I wonder if I can add an option to choose between pooled and naive memory allocations.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
