### ISSUE TITLE
Question on data consistency model

### ISSUE THREAD

**Issue by yingfeng** [apache/incubator-mxnet#2996]
It seems that SSP(Stale Synchronous Parallel) or Bounded Delay which had been mentioned in the `Communication Efficient Distributed Machine Learning with the Parameter Server` of the parameter server publication, has not been used in MXNet, only BSP or ASP(totally asynchronous) is available? 

What's the reason of not choosing SSP as the consistency model, and does there exist such a plan in the roadmap ?

**Comment by piiswrong** [comment]
Async is generally not needed for gpu clusters. sync sgd is good enough

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
