### ISSUE TITLE
waitall() operation on benchmark testing

### ISSUE THREAD

**Issue by dx80232** [apache/incubator-mxnet#2998]
I just tried to do some benchmarks about different convnets on single and multi-GPUs.
Thus, I followed _soumith's_ benchmark framework on mxnet and modified it to support multi-GPUs.
However, I got the result of the 4 gpus is slower than that of a single gpu.
For example, the average mini-batches time of vgg on my machine is like below:
- 1 GPU: 911 ms
- 4 GPUs: 1110 ms

I also set the kv_store to 'local_allreduce_device'
Now I am not sure if this result is the effect of waitall()? 
Or does anyone know how I can do benchmark on mxnet much better? Thanks!

**Comment by antinucleon** [comment]
What is your mini-batch? For example, if single gpu mini-batch is 32, for 4 gpus, you need set batch size to 128

**Comment by dx80232** [comment]
Yes, my mini-batch size is 32.  And I also feed each GPU with 32 min-batch size.  So I think the setting is same as you said.

**Comment by piiswrong** [comment]
It's expected to be a little slower since you have communication cost

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
