### ISSUE TITLE
Problem with WarpCTC design

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#3043]
@xlvector @antinucleon: currently, there is no clean way to feed tensors of shape `[sequence, batch, feature size]` into WarpCTC: it only takes `[sequence x batch, feature size]`, and there is no nice syntax with Reshape to produce this form from `[sequence, batch, feature size]` (Reshape layer doesn't have a nice way of doing this. You need to explicitly state the sequence + batch size, which makes executor reshaping ugly). 

`[sequence x batch, feature size]` is also very confusing to people, as they don't know what order batch and sequence appear in for the underlying data. In addition, they need to specify the sequence length ("input_length") and label length explicitly, which would just be inferred from the input tensor if you used  `[sequence, batch, feature size]`.

So: should we change `[sequence x batch, feature size]` to  `[sequence, batch, feature size]` and break backward compatibility, or just add support for Rank-3 inputs that will be interpreted as  `[sequence, batch, feature size]`?

**Comment by xlvector** [comment]
I think current lstm example in examples/rnn also use shape [sequence x batch, feature size]. When I implement ctc, I just follow it.

However, I think you suggestion is good, I was also confused about this (sequence and batch which should be first?) before.

@antinucleon

**Comment by sbodenstein** [comment]
@xlvector: ok, so then the question is whether to break backward compatibility or just support the [sequence, batch, feature size] as well.

One other thing: its super annoying to not be able to get out the actual CTC loss values. Its a non-trivial calculation to get CTC loss, and its just being thrown away. Perhaps have an optional 2nd output to store this in? Any other ideas?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
