### ISSUE TITLE
 Factorized Convolutional Neural Networks: at least 3 times off from old convolutional layer!!

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#3047]
http://arxiv.org/abs/1608.04337.
Can you implemented it with mxnet?
I heard it has been done with tensorflow.
@tqchen @piiswrong

**Comment by winstywang** [comment]
Your contribution is welcomed :)

**Comment by austingg** [comment]
It's tf.nn.separable_conv2d()  in TensorFLow

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
