### ISSUE TITLE
How to do the prediction with the output layer is LinerRegressionOutput

### ISSUE THREAD

**Issue by yechaochen** [apache/incubator-mxnet#3053]
I have train a params model with the last layer in network like:

```
s2_fc2a = mx.symbol.FullyConnected(data=s2_relu5, num_hidden=1)
linearRegression1 = mx.symbol.LinearRegressionOutput(data=s2_fc2a, name="softmax1")
s2_fc2b = mx.symbol.FullyConnected(data=s2_relu5, num_hidden=1)
linearRegression2 = mx.symbol.LinearRegressionOutput(data=s2_fc2b, name="softmax2")
linearRegression = mx.symbol.Group([linearRegression1,linearRegression2]) 
return linearRegression
```

And I follow the the prediction of mnist write the predict programe like:

```
def predict(params, symbol, image):
    predictor = Predictor(open(symbol).read(), open(params).read(), {'data':(1 , 3, 256, 256)},'gpu',0) #use cpu if you don't have a gpu card
    img = io.imread(image)

    predictor.forward(data=img)
    # for first task
    prob = predictor.get_output(0)
    pred = np.argsort(prob[0])[::-1]
    # label_id (same as label if MNIST), score
    print pred, prob[0][pred[0]]
    # for second task
    prob2 = predictor.get_output(1)
    pred2 = np.argsort(prob2[0])[::-1]
    # label_id (same as label if MNIST), score
    print pred2[0],  prob2[0][pred2[0]]

symbol_file = "./net/1207-symbol.json"
params_file = "./net/1207-0020.params"
image_file = "./1.jpg"
predict(params_file, symbol_file, image_file)
```

But the output of this programe is like following type and the number is fixed when I change the input image.

```
0 11432.5
0 9855
```

My label is in the former like:

```
215541 10212
```

Is the code in prediction programe I have write  wrong or I have make mistake when I prepare to training?

**Comment by winstywang** [comment]
Is your training accuracy correct? Does it work with only one output?

**Comment by yechaochen** [comment]
@winstywang I'm a new comer of mxnet.
It's is a multi-label regression task,Althought I don't know how to write the code about multi-label regression. So I follow the instruction in [https://github.com/haria/mxnet-multi-task-example/blob/master/multi-task.ipynb](url) I have change my data and path.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
