### ISSUE TITLE
link in the example/kaggle-ndsb2/readme.md that describing how  to build MXNet on AWS   is invalid 

### ISSUE THREAD

**Issue by lzx1413** [apache/incubator-mxnet#3061]
link in the example/kaggle-ndsb2/readme.md describing how to build MXNet on AWS is invalid
https://mxnet.readthedocs.io/en/latest/aws.html

**Comment by winstywang** [comment]
@antinucleon @piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
