### ISSUE TITLE
The online doc is dead

### ISSUE THREAD

**Issue by LiamZhuuu** [apache/incubator-mxnet#3080]
The online doc is very wired that I cannot find most content that was there. For example, the symbol api.

**Comment by tornadomeet** [comment]
@LiamZhuuu http://mxnet.io/packages/python/symbol.html  
yes, the doc website is not very friendly~

**Comment by LiamZhuuu** [comment]
I get the link of doc from google, which seems like a bad version
https://mxnet.readthedocs.io/en/latest/packages/python/symbol.html

**Comment by pluskid** [comment]
@mli It seems something is missing for the RTD build. We should either fix it or just make it to redirect to mxnet.io.

**Comment by mli** [comment]
we got timeout error on rtd for the last month. the doc build is now switched into ec2, the up to date version is hosted at mxnet.io. @tqchen can you let the rtd document redirect to mxnet.io?

**Comment by jonbakerfish** [comment]
Which site has the up-to-date and correct version of doc/api?
http://mxnet.io/
http://mxnet.readthedocs.io/
https://github.com/dmlc/mxnet/tree/master/docs/
http://newdocs.readthedocs.io/

**Comment by mli** [comment]
both http://mxnet.io/ and https://github.com/dmlc/mxnet/tree/master/docs/

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
