### ISSUE TITLE
Is there any way to fix the bias in fc?

### ISSUE THREAD

**Issue by LiamZhuuu** [apache/incubator-mxnet#3081]
Is there any way to fix the bias in fc?
Do I have to modify the optimizer?
Thx!

**Comment by sxjscience** [comment]
@LiamZhuuu You can use the no-bias mode and add a constant bias by yourself.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
