### ISSUE TITLE
“dmlc-core\Release\dmlccore.lib”

### ISSUE THREAD

**Issue by buaaswf** [apache/incubator-mxnet#3083]
严重性   代码  说明  项目  文件  行 禁止显示状态
错误  LNK1181 无法打开输入文件“dmlc-core\Release\dmlccore.lib”    mxnet   E:\swfface\mxnet-face\build\LINK    1

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
