### ISSUE TITLE
How does the python api "mxnet.symbol.L2Normalization" work?

### ISSUE THREAD

**Issue by jonbakerfish** [apache/incubator-mxnet#3099]
Can someone provide more details about the "mxnet.symbol.L2Normalization"?

Suppose there is a input tensor with shape (b, c, h, w), can I separately L2 normalize each c-dimensional vector at each (h, w) location by using "mxnet.symbol.L2Normalization"?

**Comment by winstywang** [comment]
Yes, there is an option to control whether to normalize within channel or cross channel. It is committed in one recent PR.

**Comment by jonbakerfish** [comment]
@winstywang Could you send me a link to this PR or related docs/code please? I can't found these options from [l2_normalization-inl.h](https://github.com/dmlc/mxnet/blob/master/src/operator/l2_normalization-inl.h)

**Comment by jonbakerfish** [comment]
in numpy, we can use something like:

    shape = (10,100,9,9)
    eps = 1e-10

    a = np.ones(shape)
    b = a / (np.sqrt(np.sum(a ** 2, axis=1))[:,np.newaxis,:,:] + eps)

in mxnet, the following code does not work since the corresponding part of `[:,np.newaxis,:,:]` is missing

    a = mx.symbol.Variable(name='a',shape=shape)
    b = a / (mx.sym.sqrt(mx.sym.sum(mx.sym.pow(a,2),axis=1)) + eps)

Is there any function support creating `newaxis` for a symbol?

**Comment by jonbakerfish** [comment]
After searching from various documents (#3080), I find [mxnet.symbol.expand_dims](http://mxnet.io/packages/python/symbol.html#mxnet.symbol.expand_dims) and [mxnet.symbol.broadcast_div](http://mxnet.io/packages/python/symbol.html#mxnet.symbol.broadcast_div) can do the trick:

    a = mx.symbol.Variable(name='a',shape=shape)
    b = mx.sym.broadcast_div(a, mx.sym.expand_dims(mx.sym.sqrt(mx.sym.sum(mx.sym.pow(a,2),axis=1)) + eps, axis=1))

However, the docs for `mxnet.symbol.broadcast_*` are still not very clear. And I still can't find any option for `mxnet.symbol.L2Normalization` to control whether to normalize within channel or cross channel.

**Comment by coolbrain** [comment]
Could this way work well in backpropagation? @jonbakerfish

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
