### ISSUE TITLE
How to explain this phenomenon in FullyConnectedLayer ? 

### ISSUE THREAD

**Issue by aaronwater** [apache/incubator-mxnet#3100]
I printed the first two data input of each data batch in the first FullyConnectedLayer in MNIST example like below
![2t0a tt c 3xc w3 fw x](https://cloud.githubusercontent.com/assets/21171292/17851340/ffb177d4-6893-11e6-9390-9fd62c96a636.png)

It showed that head lines of two data batches were the same  and one data batch was not printed. 
![0o69 _p95k860a1 9xql8y](https://cloud.githubusercontent.com/assets/21171292/17851509/ec70e03c-6894-11e6-8408-de775be1d2c1.png)

So what happened here ? Did it has something to do with the task engine which made the data I printed was not the actual data loaded?

**Comment by piiswrong** [comment]
use monitor to print stuff instead of inserting printf. example/python-howto/monitor_weight.py shows how to do it

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
