### ISSUE TITLE
A problem for prediction with trained model

### ISSUE THREAD

**Issue by zhqshen** [apache/incubator-mxnet#3122]
Hi, all
    After I run the train_cifar10.py in the mxnet example, I predict the train and test datasets with trained model, and the accuracy of prediction for train and test are all **100%**, is there anyone help me to find the problem?
my code like this,

import find_mxnet  
import mxnet as mx  
import logging  
import argparse  
import os, sys  
import train_model  
import numpy as np  

prefix = 'cifar_test'  
iteration = 20  
model_load = mx.model.FeedForward.load(prefix, iteration,ctx=mx.gpu())  
data_shape = (3, 28, 28)  

val = mx.io.ImageRecordIter(  
        path_imgrec = 'test.rec",  
        mean_img    = 'test.bin",  
        rand_crop   = False,  
        rand_mirror = False,  
        data_shape  = data_shape,  
        batch_size  = 1)  

[prob, data, pred_label] = model_load.predict(val, return_data=True)

**Comment by zihaolucky** [comment]
You've successfully train a model and use it, so what's your question? 

BTW, you can use md to improve formatting.

**Comment by zhqshen** [comment]
My problem is that the prediction is not correct with trained model while using mx.io.ImageRecordIter and   .rec data, the mxnet just extract the class of samples and the predicted accuracy will be 100%, is it normal?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
