### ISSUE TITLE
why not the item 'quality' of 'encode_params = [cv2.IMWRITE_PNG_COMPRESSION, quality]' is  from 0 to 9?

### ISSUE THREAD

**Issue by JulyUp** [apache/incubator-mxnet#3124]
When I read the module python/mxnet/recordio.py and notice that the item 'quality' of 'encode_params = [cv2.IMWRITE_PNG_COMPRESSION, quality]' is  from 0 to 9 in function pack_img. I am wondering. Would you like to explain to me?  Thank you .

**Comment by piiswrong** [comment]
please refer to opencv's document

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
