### ISSUE TITLE
mxnet predict code running on gpu

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#3127]
I'd like to predict test_data using predict function as below:   

 devs = mx.cpu() if args.gpus is None else [
               mx.gpu(int(i)) for i in args.gpus.split(',')]

```
model = mx.model.FeedForward(ctx = devs)

model_load = model.load(prefix, args.iteration)  
```

and it will report 
 Traceback (most recent call last):
 File "predict.py", line 40, in <module>
   model = mx.model.FeedForward(ctx = devs)
 TypeError: **init**() takes at least 2 arguments (2 given)
  Exception in thread Thread-4:

how can i fix it?

**Comment by VoVAllen** [comment]
```
model = mx.model.FeedForward(
    symbol = mlp,
    num_epoch = 20,
    learning_rate = .1)
model.fit(X = train, eval_data = val)
```

You should transfer the computation graph(symbol) to model.feedforward

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
