### ISSUE TITLE
bug: import mxnet error:OSError: dlopen(./mxnet/python/mxnet/../../lib/libmxnet.so, 6): Symbol not found: __ZN4half5_eLutE

### ISSUE THREAD

**Issue by pjpan** [apache/incubator-mxnet#3129]
while import mxnet ,report error:

> > > import mxnet
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/ppj/Documents/mxnet/python/mxnet/**init**.py", line 7, in <module>
> > >     from .base import MXNetError
> > >   File "/Users/ppj/Documents/mxnet/python/mxnet/base.py", line 43, in <module>
> > >     _LIB = _load_lib()
> > >   File "/Users/ppj/Documents/mxnet/python/mxnet/base.py", line 35, in _load_lib
> > >     lib = ctypes.cdll.LoadLibrary(lib_path[0])
> > >   File "//anaconda/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
> > >     return self._dlltype(name)
> > >   File "//anaconda/lib/python3.5/ctypes/__init__.py", line 347, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: dlopen(/Users/ppj/Documents/mxnet/python/mxnet/../../lib/libmxnet.so, 6): Symbol not found: __ZN4half5_eLutE
> > >   Referenced from: /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
> > >   Expected in: /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
> > >  in /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib

**Comment by piiswrong** [comment]
git pull && git submodule update && make clean && make

**Comment by pjpan** [comment]
still the same error.

**Comment by thesby** [comment]
I meet the same problem on win10. I am using python3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
