### ISSUE TITLE
Problem about binary image classification with 'LogisticRegressionOutput' 

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#3133]
I use 'LogisticRegressionOutput' in image binary classification, and get the error information "MXNetError: [09:50:29] D:\chhong\mxnet\src\symbol\symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.",   what is wrong?
part of my code as following,
'''
def inception(nhidden, grad_scale):
    # data
    data = mx.symbol.Variable(name="data")
    # stage 2
    in3a = InceptionFactoryA(data, 64, 64, 64, 64, 96, "avg", 32, '3a')
    in3b = InceptionFactoryA(in3a, 64, 64, 96, 64, 96, "avg", 64, '3b')
    in3c = InceptionFactoryB(in3b, 128, 160, 64, 96, '3c')
    # stage 3
    in4a = InceptionFactoryA(in3c, 224, 64, 96, 96, 128, "avg", 128, '4a')
    in4b = InceptionFactoryA(in4a, 192, 96, 128, 96, 128, "avg", 128, '4b')
    in4c = InceptionFactoryA(in4b, 160, 128, 160, 128, 160, "avg", 128, '4c')
    in4d = InceptionFactoryA(in4c, 96, 128, 192, 160, 192, "avg", 128, '4d')
    in4e = InceptionFactoryB(in4d, 128, 192, 192, 256, '4e')
    # stage 4
    in5a = InceptionFactoryA(in4e, 352, 192, 320, 160, 224, "avg", 128, '5a')
    in5b = InceptionFactoryA(in5a, 352, 192, 320, 192, 224, "max", 128, '5b')
    # global avg pooling
    avg = mx.symbol.Pooling(data=in5b, kernel=(7, 7), stride=(1, 1), name="global_pool", pool_type='avg')
    # linear classifier
    flatten = mx.symbol.Flatten(data=avg, name='flatten')
    fc1 = mx.symbol.FullyConnected(data=flatten, num_hidden=nhidden, name='fc')

```
label = mx.sym.Variable("label")
logicr= mx.symbol.LogisticRegressionOutput(data=fc1, label=label, name='logicr')     
return logicr
```

logicr= inception(100, 1.0)
    #above is to get the network

batch_size =1
train_dataiter = mx.io.ImageRecordIter(
    shuffle=True,
    path_imgrec="d:/test/train1.rec",
    rand_crop=True,
    rand_mirror=True,
    data_shape=(3, 200, 200),
    batch_size=batch_size,
    prefetch_buffer=4,
    preprocess_threads=2)

test_dataiter = mx.io.ImageRecordIter(
    shuffle=True,
    path_imgrec="d:/test/valid1.rec",
    rand_crop=True,
    rand_mirror=True,
    data_shape=(3, 200, 200),
    batch_size=batch_size,
    prefetch_buffer=4,
    preprocess_threads=2)
# above is to get the input dataiter from REC files

num_epoch = 5
model_prefix = "d:/test/cifar_100"

model = mx.mod.Module(symbol=logicr, data_names=('data',), label_names=('label',))
model.bind(data_shapes=train_dataiter.provide_data, label_shapes=train_dataiter.provide_label)

model.fit(train_dataiter,
          eval_data=test_dataiter,
           eval_metric="accuracy",
           num_epoch=num_epoch,
           optimizer_params={'learning_rate':0.01, 'momentum': 0.9},
          batch_end_callback=mx.callback.Speedometer(batch_size, 200),
          epoch_end_callback=mx.callback.do_checkpoint(model_prefix))
'''
the file name is temp.py in Spider , and when run it ,then get the following error information:
'''
runfile('C:/Users/ipmlogin/.spyder2/temp.py', wdir='C:/Users/ipmlogin/.spyder2')
Traceback (most recent call last):

  File "<ipython-input-15-d4396a36fbc3>", line 1, in <module>
    runfile('C:/Users/ipmlogin/.spyder2/temp.py', wdir='C:/Users/ipmlogin/.spyder2')

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/ipmlogin/.spyder2/temp.py", line 97, in <module>
    model.bind(data_shapes=train_dataiter.provide_data, label_shapes=train_dataiter.provide_label)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\module\module.py", line 252, in bind
    shared_group, logger=self.logger)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\module\executor_group.py", line 95, in **init**
    self.bind_exec(data_shapes, label_shapes, shared_group)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\module\executor_group.py", line 123, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\module\executor_group.py", line 321, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", line 412, in infer_shape
    return self._infer_shape_impl(False, _args, *_kwargs)

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", line 472, in _infer_shape_impl
    ctypes.byref(complete)))

  File "C:\Users\ipmlogin\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [09:50:29] D:\chhong\mxnet\src\symbol\symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
    [0]data
    [1]conv_3a_1x1_weight
    [2]conv_3a_1x1_bias
.....
[265]fc_weight
    [266]fc_bias
    [267]label
'''
obey the advice in "Weird LogisticRegressionOutput Bug · Issue #1975 · dmlc/mxnet  https://github.com/dmlc/mxnet/issues/1975",   I change the value of num_hidden with "logicr= inception(1, 1.0)", and the error information is the same.
what is wrong?
thanks for your help very much!

**Comment by xzqjack** [comment]
The problem of your code i think is that the name of your data is different from the variable name of your network.  The default name of label data is `softmax`. So you should set the name of LogisticOutput layer 'softmax' instead of 'label'.

**Comment by luoruisichuan** [comment]
'''
label = mx.sym.Variable("label")
logicr= mx.symbol.LogisticRegressionOutput(data=fc1, label=label, name='logicr')     
return logicr
model = mx.mod.Module(symbol=logicr, data_names=('data',), label_names=('label',))
model.bind(data_shapes=train_dataiter.provide_data, label_shapes=train_dataiter.provide_label)
'''
in above code, which should be replaced by 'softmax' ?
thanks.

**Comment by xzqjack** [comment]
To make your  name of data label in `train_dataiter.provide_label` same as the name of network label  **label** in  `label = mx.sym.Variable("label")`.  
You can print `train_dataiter.provide_label` to see the name of data label. It should be `'softmax_label'`
```
label = mx.sym.Variable("softmax")
logicr= mx.symbol.LogisticRegressionOutput(data=fc1, label=label)
```

**Comment by luoruisichuan** [comment]
i change some code as following,
'''
label = mx.sym.Variable("softmax")
    softmax= mx.symbol.LogisticRegressionOutput(data=fc1, label=label, name='softmax')     
    return softmax

model = mx.mod.Module(symbol=logicr, data_names=('data',), label_names=('softmax_label',))
model.bind(data_shapes=train_dataiter.provide_data, label_shapes=train_dataiter.provide_label)
'''
but still have the error imformation 
'Symbol.InferShapeKeyword argument name softmax_label not found.'  

and the error locate in the code 
'''model.bind(data_shapes=train_dataiter.provide_data, label_shapes=train_dataiter.provide_label)
'''
what is wrong?
thanks for your help very much!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
