### ISSUE TITLE
multiple gpus runs slower than one gpu

### ISSUE THREAD

**Issue by zhangjiulong** [apache/incubator-mxnet#3136]
I have tried toy-ctc and rnn demo when I use multiple 2 gpus the two demos all runs slower than use one gpu.
could any give some explantion??

**Comment by ilkarman** [comment]
I have the same issue; it seems that you need to increase the batch-size to make use of this. However, then I wonder if you are trying to replicate someone's model where they used minibatch=128 and you use minibatch=128*16*4 (i.e. 16 to fill the ram on one GPU, across 4 GPUs) whether you get the same model or whether your results are less accurate

**Comment by zhangjiulong** [comment]
Thanks @ilkarman  I will try. Thx

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
