### ISSUE TITLE
batch padding bug in ml.dmlc.mxnet.spark.io.LabeledPointIter

### ISSUE THREAD

**Issue by wrongtest** [apache/incubator-mxnet#3137]
if sample_size % batch_size != 0, the last batch generated by next() is still initialized with NDArray.empty() using original batch_size and set pad = (batch_size - real_size).

However, the mxnet training process seems to ignore the pad field of DataBatch. The whole batch is taken into calculation, which may produce NaN result in my linear regression model. I find that the uninitialized part of the last batch contains randomly huge numbers like xxxxxE10. 

Using NDArray.zeros() to initialize the batch or just discarding the last batch can fix in my case. And is it possible to use different batch_size for different batch in the DataIter object?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
