### ISSUE TITLE
How to use symbol and constant to construct a network

### ISSUE THREAD

**Issue by chenboheng** [apache/incubator-mxnet#3141]
I want to construct a network by symbol.
But if my network has a constant, how to construct my network?
Like this:

A=mx.symbol.Variable('A')
B=5
C=A+B // C=A/B

Those above codes are wrong.
How to construct a network which has symbol and constant like C=A+B or C=A/B

**Comment by VoVAllen** [comment]
This code runs well at my version. Please update your mxnet to the newest version.

**Comment by chenboheng** [comment]
Thank you, you are right. But I want to get the more general operation like this: 
A=mx.symbol.Variable('A')
B=[1,2,3,4]
C=A+B

B is a matrix or a vector. Does mxnet has the element-wise operation of symbol and constant matrix?

**Comment by VoVAllen** [comment]
Please use B=mx.nd.array([1,2,3,4])

**Comment by jiumem** [comment]
NDarray can not interact with a symbol directly.  why there is not a Constant op? Each time feed a constant value to the symbol graph is inconvenient.

**Comment by csherstan** [comment]
A constant op would be great.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
