### ISSUE TITLE
How to use mxnet RNN symbol?

### ISSUE THREAD

**Issue by bombomtsao** [apache/incubator-mxnet#3142]
Hi all,
I've found RNN symbol is added in mxnet v0.7.
Now, I'm trying to use it to impl lstm in example/rnn with python.
But I have no idea because there's no document or any information of the input and output.
Can anyone give me any advice?
thanks

**Comment by pluskid** [comment]
Currently only cuDNN wrapped version is added. We plan to refine the interface and add examples using RNN symbol recently.

**Comment by philipskokoh** [comment]
Just try to understand, any design reason to make RNN symbol to be time-major shape layout instead of batch-major? from my understanding, the low level symbol lstm.py process batch-major

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
