### ISSUE TITLE
DMLC_REGISTER_PARAMETER

### ISSUE THREAD

**Issue by peerchen** [apache/incubator-mxnet#3147]
我在windows下运行mxnet的alexnet案例的时候，运行到DMLC_REGISTER_PARAMETER，还未进入main函数，程序就死掉了，debug到的调用过程如下
![image](https://cloud.githubusercontent.com/assets/6119960/17997579/d4c9afc6-6ba1-11e6-9c9f-dcd24335084c.png)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
