### ISSUE TITLE
how to accelerate training process of lstm model?

### ISSUE THREAD

**Issue by littleDing** [apache/incubator-mxnet#3155]
I am playing with the example/rnn/lstm.py char-rnn  codes.
When I use 4 gpus to run, it only use 10-30% on each of them and cpu is around 200%.
I've tried kvstore =  local, all_reduce_cpu, all_reduce_device etc, nothing better, some may be even worse then the default option local_update_cpu.

Any tricks to accelerate this ?

More details:
data set : 132w Chinese sentences, with Jieba to cut words, 4.5w words.
params : batch_size = 128,  buckets = [40], num_hidden = 64, num_embed = 16, num_lstm_layer = 3
devices :  Tesla K40c \* 4, mxnet building with USE_CUDA=1 and USE_CUDNN=0 

some  speed logs : 
02:48:47 INFO:Auto-select kvstore type = local_update_cpu
02:48:47 INFO:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
02:57:50 INFO:Epoch[0] Batch [1000] Speed: 235.90 samples/sec   Train-Perplexity=129.630862
03:06:47 INFO:Epoch[0] Batch [2000] Speed: 238.64 samples/sec   Train-Perplexity=15.946662
03:15:47 INFO:Epoch[0] Batch [3000] Speed: 237.14 samples/sec   Train-Perplexity=14.958449

**Comment by magic282** [comment]
having the same issue.

**Comment by pluskid** [comment]
Increasing the batch size?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
