### ISSUE TITLE
can mxnet use hdf5 data except rec data? 

### ISSUE THREAD

**Issue by IvyGongoogle** [apache/incubator-mxnet#3156]
Now I have a hdf5 data, and I want to use mxnet to train. So can mxnet use hdf5 data except rec data?

**Comment by piiswrong** [comment]
No. But you can inherit mx.io.DataIter and parse hdf5 data yourself

**Comment by JulyUp** [comment]
@piiswrong Thank you very much. For lmdb and hdf5, which of inheriting mx.io.DataIter and parsing hdf5 or lmdb data is simpler?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
