### ISSUE TITLE
Python docs reference `compile`

### ISSUE THREAD

**Issue by vchuravy** [apache/incubator-mxnet#3157]
The python docs reference a function called `compile` http://mxnet.readthedocs.io/en/latest/system/program_model.html

As far as I can tell that function doesn't exist anymore. Is this `bind` nowadays?

**Comment by piiswrong** [comment]
I think that's pseudo code...

**Comment by vchuravy** [comment]
Haha, how would you write this in real code? Somebody recently tried to do this, http://stackoverflow.com/questions/35840176/how-to-get-a-gradient-node-with-mxnet-jl-and-julia# so it might be better if we provide a proper example.

**Comment by pluskid** [comment]
@vchuravy I believe that the compile should be a call to create a `Group` symbol, and then one need to do bind/simple_bind in order to run it with executors.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
