### ISSUE TITLE
Temporal k-max pooling

### ISSUE THREAD

**Issue by ilkarman** [apache/incubator-mxnet#3160]
I need to construct a temporal k-max pooling layer, which outputs k features. I had a quick search and I think my problem is similar to [this](https://github.com/fchollet/keras/issues/373).

Basically the layer gets an input of 1(=height) x 125(=width) x 512(=number of filters) and outputs 1(=height) x k(=width) x 512(=number of filters). 

In my mind this is different to a standard max pooling layer - and I dont know if that can be reduced to this?

**Comment by CNevd** [comment]
@ilkarman i've wrote one use CustomOp, you can check [k max pool](https://github.com/CNevd/DeepLearning-Mxnet/blob/master/DCNN/dcnn_train.py#L15)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
