### ISSUE TITLE
How to use amalgamation w/pre trained model

### ISSUE THREAD

**Issue by tanayz** [apache/incubator-mxnet#3164]
You might find this question easy,however mxnet amalgamation link https://github.com/dmlc/mxnet/tree/master/amalgamation
doesn't tell how to include a pre-trained model(.json & .param file) into this mechanism.
For example Lelina's app whatsthis uses imagenet,but I'm not sure how that has been 
compiled to libmxnet_predict.so.

**Comment by perp** [comment]
You can have a loot at the image classification example in mxnet/example/cpp/image-classifcation/image-classification-predict.cc

**Comment by SlipknotTN** [comment]
The net model is separated from the mxnet lib (libmxnet_predict.so), so you can change model without touching the lib (for standard image classification tasks). In the Android app the model (4 files) is included in the [raw directory](https://github.com/Leliana/WhatsThis/tree/master/app/src/main/res/raw), in the iOS app is quite similar.
P.S.: probably some models need an update of the core mxnet lib to work respect to the Leliana old version lib.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
