### ISSUE TITLE
How does decay_factor work in Adam?

### ISSUE THREAD

**Issue by Vogen** [apache/incubator-mxnet#3166]
In optimizer.py, 
The initialization for Optimizer class is
`def __init__(self, rescale_grad=1., param_idx2name=None, wd=0., clip_gradient=None, learning_rate=0.01, lr_scheduler=None, sym=None, begin_num_update=0): ...`

The initialization for Adamclass is
`def __init__(self, learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8, decay_factor=(1 - 1e-8), **kwargs):
        super(Adam, self).__init__(learning_rate=learning_rate, **kwargs)
        self.beta1 = beta1
        self.beta2 = beta2
        self.epsilon = epsilon
        self.decay_factor = decay_factor`

I find nowhere using decay_factor. And instead of using decay_factor, Adam:update use wd to decay updating weight. I get confused here. Do I misunderstand or the decay_factor should renamed as wd?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
