### ISSUE TITLE
Compilation Error with the latest version

### ISSUE THREAD

**Issue by yuzcccc** [apache/incubator-mxnet#3169]
update to the latest version of mxnet, I face a compilation error as follows: 
include/mxnet/././tensor_blob.h(39): error: cannot determine the exception specification of the default constructor due to a circular dependency

My gcc is 4.8.5 and cuda 6.5. Everything works well under the previous version.

**Comment by tornadomeet** [comment]
do you update the submodule?

**Comment by marcociccone** [comment]
anyone who knows how to solve this problem? I have the same configuration with Cuda 6.5 and I also tried both gcc 4.8 and 5. 
I have cloned recursively , so I updated all the submodules but I faced the same issue. 
Could it be related with the introduction of the c++11 flag here ? #2585

**Comment by cloudygoose** [comment]
+1 met this problem too.

**Comment by cloudygoose** [comment]
@yuzcccc @marcociccone  My colleagues advise me to use cuda7.5, I did and problem solved. You can try too.

**Comment by lazyparser** [comment]
I've reproduced this issue on tk1, with cuda-6.5 and cuDNNv2. Currently cuda-6.5 is the highest version for tk1.
(mxnet commit id: 4ac67307dfe97c6d2490f8f050f941ef96fc44c3)

**Comment by luca-nardelli** [comment]
Hi all, an update on this issue:

I've tried to change the definition in tensor_blob.h from 

`Tuple()=default;`

to

`inline Tuple(){}`

and that seemed to do the trick (for me at least). However, I have no idea if this might impact something else in the long run.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
