### ISSUE TITLE
is there any example of LSTM image classification?(not a issue)

### ISSUE THREAD

**Issue by albertyou2** [apache/incubator-mxnet#3171]
Is there any example of LSTM image classification?
Or is  any other method for image classification except CNN?

**Comment by tornadomeet** [comment]
http://arxiv.org/abs/1505.00393

**Comment by albertyou2** [comment]
@tornadomeet thank you !!!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
