### ISSUE TITLE
A question about async engine

### ISSUE THREAD

**Issue by horserma** [apache/incubator-mxnet#3174]
This is related to #1452, which is already closed.
Since I am still confused about this async engine, may I ask you one more question? Like you said before, executor.outputs[0].copyto(mx.cpu()).asnumpy() will force the engine to sync. So if I have two parts in my network, which means two executors, e1 and e2. The whole training process can be described as:

```
e1.forward(is_train=True)
output1 = e1.outputs[0].copyto(mx.cpu()).asnumpy()
...process output1 and get input2 for e2...
e2.arg_dict["data"][:] = input2
e2.forward(is_train=True)
output2 = e2.outputs[0].copyto(mx.cpu()).asnumpy()
...calculate gradients for output2 say grad2...
e2.backward(mx.ndarray.array(grad2))
data_grad = e2.grad_dict["data"].copyto(mx.cpu()).asnumpy() //get gradients for data
...process data_grad and get grad_output1 for e1...
e1.backward(mx.ndarray.array(grad_outpu1))
for arg in update_list:
    updater(...)
```

So is this the correct way of doing this? Since I used too many copyto(mx.cpu()) to force the sync, would this cause any slow-down? If this is non-optimal, what is the best way to implement this? Thank you very much. @tqchen @piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
