### ISSUE TITLE
about unpack_patch2col and swapaxis

### ISSUE THREAD

**Issue by perp** [apache/incubator-mxnet#3188]
When I read the Forward function in convolution-inl.h 
I want to find out where unpack_patch2col and swapaxis exectutor is.
The time cost of these two functions are very huge. Or I did not get the right part because of Async 
Thanks in advance!

**Comment by piiswrong** [comment]
mshadow/src/extensions

**Comment by perp** [comment]
@piiswrong Whether convert the result of unpack_patch2col to MakeTensor cost a lot of time?
I add some timestamp to the start and the end of unpack_patch2col function in unpack_patch2col.h and convolution-inl.h.
this is what I add in the convolution-inl.h

  if (param_.pad[0] == 0 && param_.pad[1] == 0) {
128     ┊   ┊   ┊   double start = gettime("conv7 start");
129     ┊   ┊   ┊   temp_col = unpack_patch2col(data.Slice(i, i + step),
130     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.kernel[0],
131     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.kernel[1],
132     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.stride[0],
133     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.stride[1],
134     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.dilate[0],
135     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.dilate[1]);
136     ┊   ┊   ┊   printf("conv forward 7 time cost:%.3f ms\n",gettime("conv7 end")-start);
137     ┊   ┊   } else {          
138     ┊   ┊   ┊   double start = gettime("conv7 start");
139     ┊   ┊   ┊   temp_col = unpack_patch2col(pad(data.Slice(i, i + step),
140     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊       param_.pad[0], param_.pad[1]),
141     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.kernel[0],
142     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.kernel[1],
143     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.stride[0],
144     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.stride[1],
145     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.dilate[0],
146     ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   param_.dilate[1]);
147     ┊   ┊   ┊   printf("conv forward 7 time cost:%.3f ms\n",gettime("conv7 end")-start);
148     ┊   ┊   }

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
