### ISSUE TITLE
MapReduceKeepHighDim::reduction dimension do not match

### ISSUE THREAD

**Issue by neodooth** [apache/incubator-mxnet#3189]
Hi,
I'm adding some modifications to the structure of a pretrained network; I added a skip connection and a 1x1 conv after the concat to make the final feature dimension unchanged. Here are the visualization of the modified part of the network:
original net
![qq20160831-1](https://cloud.githubusercontent.com/assets/1276769/18134310/7f10bc54-6fd0-11e6-8a22-fcc0a379c5db.png)

modified:
![qq20160831-2](https://cloud.githubusercontent.com/assets/1276769/18134528/43870912-6fd1-11e6-9504-7688f77af0af.png)

(I changed visualization.py a bit so it displays batch size, which is the first dimension)

since "shared_conv_reduce" is a new symbol and does not exist in the pretrained model, I initialized its weight using normal distribution with shape (1024, 1536, 1, 1); but during forwarding (I suppose), mxnet reports this error:

dmlc-core/include/dmlc/logging.h:235: [23:16:07] src/engine/./threaded_engine.h:306: [23:16:07] mshadow/mshadow/./tensor_gpu-inl.h:146: Check failed: (eshape[dimkeep]) == (dshape[0]) MapReduceKeepHighDim::reduction dimension do not match

and I don't know why?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
