### ISSUE TITLE
mxnet MATLAB interface error , R Works Win 10 64 Binary install

### ISSUE THREAD

**Issue by Qunal** [apache/incubator-mxnet#3190]
Too intimidating posting on github for newbie issues. Just starting and need help and posted in Google group first. Repeating

Installed mxnet on win 10 64 bit using binary option.

R demo worked fine with MNIST data. Can get predictions and data is read in.

MATLAB demo ( which is where I want to do most work) is having issues

The demo fails in calls to libmxnet.

Failure in callmxnet .m at line 26

24 assert(ischar(func))
25 ret = calllib('libmxnet', func, varargin{:});
26 assert(ret == 0)

func is MXPredCreatePartialOut
varargin is cell of 12 elements

The folder mxnet/lib has the libmxnet.dll and lib files
The path includes these folders

Demo.m

21 pred = model.forward(img);

**Comment by mli** [comment]
is there any error message? i didn't test window version before.

**Comment by Qunal** [comment]
MATLAB issues a statement in console

`Failure in callmxnet .m at line 26`
that line is calllib to libmxnet See below
`
24 assert(ischar(func))
25 ret = calllib('libmxnet', func, varargin{:});
26 assert(ret == 0)
27 end

`

I set a breakpoint and saw that the function was being called with the following parameters
func is MXPredCreatePartialOut
varargin is cell of 12 elements

I suspect this is about locating or loading libmxnet which is in folder \mxnet\lib while the code is in \mxnet\matlab\+mxnet\private

**Comment by Qunal** [comment]
I used binary option( Did not compile anything). I am on Win10 64 bit version. the environment variable MXNET_HOME is set up .

Since I was able to run the examples with prediction using R Studio I suspect this is a MATLAB issue. 

![image](https://cloud.githubusercontent.com/assets/7659303/18232680/a6575118-72f2-11e6-9e5f-c0eddb7bd92d.png)

**Comment by Qunal** [comment]
Hoping to get some insight. Now I have used MXNET extenisvly with R and Python. The R DRAT and binary install method seems to work. I wanted to check is there is a conflict as mxnet is added as a library in R with code in folder under R_USERLIB ( not in R_HOME) and in Python under Anaconda . Do the DLL get placed in various follers with chance of conflict. If I am running a example in R and in Python using MXNET at same time will it be Ok

**Comment by gisoo2017** [comment]
I get the same error on CPU version:
Is this because of CPU version? Do I need to change something in the model to be able to run it on CPU?


Error using callmxnet (line 26)
Assertion failed.

Error in mxnet.model/forward (line 136)
    callmxnet('MXPredCreatePartialOut', obj.symbol, ...

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
