### ISSUE TITLE
get each layer output

### ISSUE THREAD

**Issue by windelu** [apache/incubator-mxnet#3192]
whether i can get each neural output when i finish my training

**Comment by tornadomeet** [comment]
yes, you can. when you get your sym, just use sym.get_internals(a_out), a is your layer name.

**Comment by starimpact** [comment]
@tornadomeet sym.get_internals() has no parameters.
@windelu you can use sym.Group to gather the internal layers as outputs.

**Comment by tornadomeet** [comment]
@starimpact  i just make a mistake, it should be used like this ```sym.get_internals()['***_output']```.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by pilhoon** [comment]
`sym.list_outputs()` will work too.
