### ISSUE TITLE
mxnet csharp Interface

### ISSUE THREAD

**Issue by yajiedesign** [apache/incubator-mxnet#3196]
I make a  csharp Interface with mxnet 
https://github.com/yajiedesign/mxnet.csharp

**Comment by tqchen** [comment]
this looks great, you are more than welcomed to PR to https://github.com/dmlc/mxnet/blob/master/example/README.md If you have examples or blogposts to make it a more formal package, we can also have an invitation blogpost to dmlc

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
