### ISSUE TITLE
Check list for more operators

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#3198]
Lacking of operators is the major disadvantage of MXNet comparing to other frameworks. The current multidimensional array interface follows the `numpy.ndarray` convention. See this [tutorial](http://nbviewer.jupyter.org/github/dmlc/mxnet-notebooks/blob/master/python/basic/ndarray.ipynb) for a quick overview. 

Now we are going to add the rest numpy operators into MXNet, and also fix the existing operators if their are different to the according ones in numpy.

I grabbed numpy's routines from [this page](https://docs.scipy.org/doc/numpy/reference/routines.html). The comparison to MXNet's operators will be listed in a few following issues. 

For an operator, there are 4 states 
- **v** : already done, and it is consistent to numpy
- **p** : partially done. the part should be fixed is on the comments
- **x** : not exists, need to add into mxnet
- **=** : not exists, but will not support in a short time
- **?** : not sure whether x or =, leave for discussion
  We will use separate issues to track each operator category. The schedule is
- [ ] survey the current status, and which operators should be added or fixed.
- [ ] examples codes to implement new operators
- [ ] assign jobs to contributors 

Also some related tasks:
- better operator documents
- better unittest 
- improve neural network related operators

**Comment by tqchen** [comment]
close on stale issue
