### ISSUE TITLE
[OP] Mathematical functions

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#3201]
See context #3198

Please feel free to edit this thread or leave comment.
### Trigonometric functions

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [sin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html) | v |  |  |
| [cos](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html) | v |  |  |
| [tan](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tan.html) | v | @yajiedesign | #3317 |
| [arcsin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arcsin.html) | v | " | " |
| [arccos](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arccos.html) | v | " | " |
| [arctan](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan.html) | v | " | " |
| [hypot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hypot.html) | v | " | #3335 |
| [arctan](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan.html) | v | " | " |
| [degrees](https://docs.scipy.org/doc/numpy/reference/generated/numpy.degrees.html) | v | " | " |
| [radians](https://docs.scipy.org/doc/numpy/reference/generated/numpy.radians.html) | v | " | " |
| [unwrap](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unwrap.html) | x |  |  |
| [deg](https://docs.scipy.org/doc/numpy/reference/generated/numpy.deg.html) | x |  |  |
| [rad](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rad.html) | x |  |  |
### Hyperbolic functions

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [sinh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sinh.html) | v | @yajiedesign | #3335 |
| [cosh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cosh.html) | v | " | " |
| [tanh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tanh.html) | v | " | " |
| [arcsinh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arcsinh.html) | v | " | " |
| [arccosh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arccosh.html) | v | " | " |
| [arctanh](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctanh.html) | v | " | " |
### Rounding

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [around](https://docs.scipy.org/doc/numpy/reference/generated/numpy.around.html) | p |  | has `nd.round` |
| [round](https://docs.scipy.org/doc/numpy/reference/generated/numpy.round.html) | v |  |  |
| [rint](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rint.html) | x | santosh |  |
| [fix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fix.html) | x | santosh |  |
| [floor](https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor.html) | v |  |  |
| [ceil](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ceil.html) | v |  |  |
| [trunc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trunc.html) | x |  |  |
### Sums

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [prod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.prod.html) | x |  |  |
| [sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) | ~~p~~ v |  | ~~no `axis` option, which is supported by `sum_axis`~~ |
| [nanprod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanprod.html) | x |  |  |
| [nansum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nansum.html) | x |  |  |
| [cumprod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumprod.html) | x |  |  |
| [cumsum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html) | x |  |  |
| [nancumprod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nancumprod.html) | x |  |  |
| [nancumsum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nancumsum.html) | x |  |  |
| [diff](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html) | x |  |  |
| [ediff1d](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ediff1d.html) | x |  |  |
| [gradient](https://docs.scipy.org/doc/numpy/reference/generated/numpy.gradient.html) | = |  |  |
| [cross](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cross.html) | x |  |  |
| [trapz](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trapz.html) | x |  |  |
### Exponents and logarithms

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [exp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp.html) | v |  |  |
| [expm1](https://docs.scipy.org/doc/numpy/reference/generated/numpy.expm1.html) | v | @vafl | #3337 |
| [exp2](https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp2.html) | x | santosh |  |
| [log](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html) | v |  |  |
| [log10](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log10.html) | x | " |  |
| [log2](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log2.html) | x | " |  |
| [log1p](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log1p.html) | v | @vafl | #3337 |
| [logaddexp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp.html) | x | santosh |  |
| [logaddexp2](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp2.html) | x | " |  |
### Other special functions

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [i0](https://docs.scipy.org/doc/numpy/reference/generated/numpy.i0.html) | x |  |  |
| [sinc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sinc.html) | x |  |  |
### Floating point routines

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [signbit](https://docs.scipy.org/doc/numpy/reference/generated/numpy.signbit.html) | x |  |  |
| [copysign](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copysign.html) | x |  |  |
| [frexp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.frexp.html) | x |  |  |
| [ldexp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ldexp.html) | x |  |  |
### Arithmetic operations

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [add](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html) | v |  |  |
| [reciprocal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reciprocal.html) | x |  |  |
| [negative](https://docs.scipy.org/doc/numpy/reference/generated/numpy.negative.html) | v |  |  |
| [multiply](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html) | v |  |  |
| [divide](https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html) | v |  |  |
| [power](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html) | v |  |  |
| [subtract](https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html) | v |  |  |
| [true_divide](https://docs.scipy.org/doc/numpy/reference/generated/numpy.true_divide.html) | v |  |  |
| [floor_divide](https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor_divide.html) | x |  |  |
| [fmod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fmod.html) | x |  |  |
| [mod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mod.html) | x |  |  |
| [modf](https://docs.scipy.org/doc/numpy/reference/generated/numpy.modf.html) | x |  |  |
| [remainder](https://docs.scipy.org/doc/numpy/reference/generated/numpy.remainder.html) | x |  |  |
### Handling complex numbers

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [angle](https://docs.scipy.org/doc/numpy/reference/generated/numpy.angle.html) | = |  |  |
| [real](https://docs.scipy.org/doc/numpy/reference/generated/numpy.real.html) | = |  |  |
| [imag](https://docs.scipy.org/doc/numpy/reference/generated/numpy.imag.html) | = |  |  |
| [conj](https://docs.scipy.org/doc/numpy/reference/generated/numpy.conj.html) | = |  |  |
### Miscellaneous

| Numpy | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [convolve](https://docs.scipy.org/doc/numpy/reference/generated/numpy.convolve.html) | = |  |  |
| [clip](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html) | v |  |  |
| [sqrt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html) | v |  |  |
| [cbrt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cbrt.html) | x |  |  |
| [square](https://docs.scipy.org/doc/numpy/reference/generated/numpy.square.html) | v |  |  |
| [absolute](https://docs.scipy.org/doc/numpy/reference/generated/numpy.absolute.html) | p |  | see `nd.abs` |
| [fabs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fabs.html) | p |  | see `nd.abs` |
| [sign](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sign.html) | v |  |  |
| [maximum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html) | v |  |  |
| [minimum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html) | v |  |  |
| [fmax](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fmax.html) | x |  |  |
| [fmin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fmin.html) | x |  |  |
| [nan_to_num](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nan_to_num.html) | x |  |  |
| [real_if_close](https://docs.scipy.org/doc/numpy/reference/generated/numpy.real_if_close.html) | x |  |  |
| [interp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html) | = |  |  |
| [entropy](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html) | x |  |  |
| [fft2](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fft2.html) | = |  |  |
| [ifft2](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.ifft2.html) | = |  |  |
| [rfft2](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.rfft2.html) | = |  |  |
| [irfft2](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.irfft2.html) | = |  |  |

**Comment by piiswrong** [comment]
We should also consider supporting torch style axpby functions like a:add(0.5, b). These functions can save one to many ndarray alloc/free compared to a += 0.5*b

**Comment by sxjscience** [comment]
@piiswrong I agree. We can also add something like addmm and addbmm(https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchaddmmres-v1-m-v2-mat1-mat2). Moreover, we can directly include some BLAS operations like GEMM.

**Comment by mli** [comment]
but shouldn't it nnvm's job to do the optimization? @tqchen

**Comment by tqchen** [comment]
Let us avoid add these operators for now, and focus on the scope we have so far. For symbolic layers, we will try to do RTC to resolve some of the issues.

**Comment by taliesinb** [comment]
For what its worth I implemented (on the Wolfram fork of MXNet) a ScaledPlus NDArray op that takes two inputs, two scales, and an output and does `out = a*x + b*y` without any allocations. That was needed to make our ADAM optimizer more memory-efficient. I was surprised it wasn't in there already. I would actually like to upstream this at some point.

**Comment by piiswrong** [comment]
@taliesinb I made a single step adam op here https://github.com/dmlc/mxnet/pull/3225
it will be released with 1.0

**Comment by thatindiandude** [comment]
@mli Have these requirements changed since the NNVM branch merge?
