### ISSUE TITLE
Global memory allocation policy

### ISSUE THREAD

**Issue by feiyulv** [apache/incubator-mxnet#3213]
Is that possible to support global memory pool in mxnet.  Current memory share policy between different executors is based on each NDArray. If new executor has more NDArray numbers, even the total memory consumption is lower than the shared executor, it will still alloc new memory space. For example, to improve the efficiency of full sequence lstm, we can use a large batch size for short sequence and small batch size for long sequence, however due to the memory allocation policy of mxnet, this will cacuse OOM.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
