### ISSUE TITLE
where to find hostd3.pl and ami_local_bptt.cfg in the file  mxnet/example/speech-demo/run_ami.sh

### ISSUE THREAD

**Issue by felixchen0113** [apache/incubator-mxnet#3216]
Hi,
     when i  tried to run  "mxnet/example/speech-demo/run_ami.sh"  , the files hostd3.pl in line 16 and  ami_local_bptt.cfg  in line 35 were not found. can you tell me where to find them? thank you!

**Comment by venkateshappea** [comment]
^did you ever figure this out? I am trying run the run_ami.sh and running into the same issues as well.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
