### ISSUE TITLE
I want to run warp-ctc with flexible length data, Is there any suggestion?

### ISSUE THREAD

**Issue by zhangjiulong** [apache/incubator-mxnet#3219]
I want to run warp-ctc with flexible length data, Is there any suggestion?

**Comment by starimpact** [comment]
I suggest you make batch be one. and using reshape to handle variable size input data.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
