### ISSUE TITLE
Does warp-ctc support multiple input feature length?

### ISSUE THREAD

**Issue by zhangjiulong** [apache/incubator-mxnet#3220]
Does warp-ctc support multiple input feature length?
I tried rnn's bucket iterator, but it does not work

**Comment by starimpact** [comment]
warp-ctc only support unified length input feature in a batch.

**Comment by zhangjiulong** [comment]
but the toy ctc runs ok on gpu.

**Comment by starimpact** [comment]
no, it can not run on GT1080.

**Comment by zhangjiulong** [comment]
I know thanks @starimpact .
I know the fact  when running ctc in a batch feature length should be the same, 
but between batches the length could be different is this right?

**Comment by starimpact** [comment]
you can use '0' to fit the extra positions to make the label length be same.
yes, you could use different length between batches. but you need to do reshape firstly.

**Comment by zhangjiulong** [comment]
Hi @starimpact thank you very much.
Now I have changed all the length to the same in the data iterator.
Several days ago I haved tried the method of using different length between batches, but failed.
Could please give me some example?

**Comment by starimpact** [comment]
my samples are all same.
you can look up how to use ```reshape``` function.

**Comment by zhangjiulong** [comment]
Ok  thx

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
