### ISSUE TITLE
Some error  occured when installing mxnet on centos6.5

### ISSUE THREAD

**Issue by iMaThML** [apache/incubator-mxnet#3229]
/usr/local/cuda-7.5/bin/nvcc -c -o build/src/operator/broadcast_reduce_op_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/root/Desktop/mxnet/mshadow/ -I/root/Desktop/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda-7.5/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I/root/Desktop/mxnet/ps-lite/include -I/root/Desktop/mxnet/deps/include -DMXNET_USE_NVRTC=1" src/operator/broadcast_reduce_op.cu
ERROR: certificate common name \u201cwww.github.com\u201d doesn\u2019t match requested host name \u201craw.githubusercontent.com\u201d.
To connect to raw.githubusercontent.com insecurely, use \u2018--no-check-certificate\u2019.
make[1]: **\* [/root/Desktop/mxnet/deps/include/zmq.h] Error 5
make[1]: Leaving directory `/root/Desktop/mxnet/ps-lite'
make: **\* [PSLITE] Error 2
make: **\* Waiting for unfinished jobs....

**Comment by jingpengwu** [comment]
did you tried to update all the submodules? I used to have error of building, it is fine after updating submodules.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
