### ISSUE TITLE
when release a new stable version ? 

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#3230]
the last stable version is 0.7.0.
when will be the new stable version released?

**Comment by zihaolucky** [comment]
I failed to make the latest. The old one has been deleted >< 

Any way to clone the code of a stable version?

**Comment by Ldpe2G** [comment]
@zihaolucky you can clone the lastest version and then use 'git set xxxx' to the old version

**Comment by starimpact** [comment]
@zihaolucky don't use latest versions, they are not stable.
just use 0.7.0, it is good enough to use.

**Comment by zihaolucky** [comment]
Thank you~ @Ldpe2G @starimpact

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
