### ISSUE TITLE
I found my mxnet starts very slow, takes about 5 minutes before the gpus begin to run

### ISSUE THREAD

**Issue by zhangjiulong** [apache/incubator-mxnet#3239]
when starting it stops here for about 5 minutes 

```
2016-09-07 09:46:52,681 Auto-select kvstore type = local_update_cpu
2016-09-07 09:46:52,683 Start training with [gpu(0), gpu(1)]
```

**Comment by zhangjiulong** [comment]
I have closed opencv like this:
```
# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 0
```
and rebuild mxnet
```
make clean
make -j8
cd python && sudo python setup.py install
```
but still very slow

**Comment by piiswrong** [comment]
Does other gpu based programs have this problem?
Try running cuda samples and see if any of them also have slow start problem

**Comment by zhangjiulong** [comment]
I runned a test program using tensorflow.
It runs normal, starting very fast.

**Comment by zhangjiulong** [comment]
mxnet's gpu memory used incread very slow
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      8255    C   python                                        1061MiB |
|    1      8255    C   python                                         137MiB |
```

**Comment by i-MaTh** [comment]
I have same problem with you!

**Comment by sxjscience** [comment]
May try to change the cache path and turn on the cache support https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-understand-fat-binaries-jit-caching/ .
Like the following
```bash
export CUDA_CACHE_MAXSIZE=2147483647
export CUDA_CACHE_DISABLE=0
export CUDA_CACHE_PATH="/home/data/xingjian/.nv/ComputeCache"
```

**Comment by aktiger** [comment]
same problem!

**Comment by aktiger** [comment]
@sxjscience  thanks, this solved my problem.

**Comment by ion-elgreco** [comment]
> May try to change the cache path and turn on the cache support https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-understand-fat-binaries-jit-caching/ .
> Like the following
> 
> ```shell
> export CUDA_CACHE_MAXSIZE=2147483647
> export CUDA_CACHE_DISABLE=0
> export CUDA_CACHE_PATH="/home/data/xingjian/.nv/ComputeCache"
> ```

How do you run this export, with what program?

**Comment by ilyak93** [comment]
@aktiger , @sxjscience, can you guys give more details on how you changed the CACHE_PATH and to where and how you exactly exported those variable (on which stage of the docker build/run or from inside the python script using os.system) and etc.

This will be very helpful due to the fact that I have the same problem as the author of the post.

@ion, where you able to figure this out ?

I know thats an old one, but more details on the solution would be great.
