### ISSUE TITLE
question about the pad design

### ISSUE THREAD

**Issue by GeorgeXia1828** [apache/incubator-mxnet#3240]
The pad in convolution seems to add the pad by two side, means that every time I add the pad number +1, then the output size will plus +2 given the stride is (1, 1). So it seems not so flexible to get what output size I want like there is a 'same' setting in keras border_mode. Why it is designed to like this?

**Comment by winstywang** [comment]
This is normal setting as in Caffe and also in CuDNN

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
