### ISSUE TITLE
New Operator Guide

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-mxnet#3248]
After #3245 get merged in, we can start editing a new operator registration guide. Let us start by pasting and collaboratively edit markdown format to this issue, before we move it to the docs

@piiswrong

**Comment by tqchen** [comment]
# Operator Registration

The new version of MXNet support operator registration via NNVM, the following code is a snippet on how an operator can be registered.

```c++
NNVM_REGISTER_OP(abs)
.MXNET_DESCRIBE("Take absolute value of the src")
.set_num_inputs(1)
.set_num_outputs(1)
.attr<nnvm::FInferShape>("FInferShape", ElemwiseShape<1,1>);
```
The syntax is quite simple, we register the operator via name, set number of inputs and outputs. Furthermore, we can register additional attributes of the operator.

## Operator Attribute System
One of the biggest improvements brought by the recent refactor is the operator attribute system. This is like traits for types in common languages like c++. We can register arbitrary attribute to any operator, with the syntax
```c++
NNVM_REGISTER_OP(op-name)
.attr<AttributeType>("AttributeKey", CorrespondingAttributeObject);
```

Then these registered operator attribute can be retrieved by the system later for various purposes. For example ```FInferShape``` attribute is used for shape inference, ```FCompute<cpu>``` attribute is used for carry out the actual computation on CPU.

We do restrict that all the attributes with same attribute key need to be in the same type. Other than that, we can register any attributes of operators. The more attribute each operator provide, the more information the system can leverage to perform various optimizations.

## List of Operator Attribute that Must be Registered
As long as the following two attributes are registered, the operator can run on computation and take gradients
- ```nnvm::FInferShape```
- ```nnvm::FGradient```
- ```mxnet::FCompute```

## A Complete List of Attributed that is used by MXNet
All the operator attributes are listed under two files
- [nnvm/op_attr_types.h](https://github.com/dmlc/nnvm/blob/master/include/nnvm/op_attr_types.h)
- [mxnet/op_attr_types.h](https://github.com/dmlc/mxnet/blob/nnvm/include/mxnet/op_attr_types.h)

## Examples
TODO @piiswrong

**Comment by tqchen** [comment]
@pluskid  @vchuravy @tornadomeet @sxjscience @antinucleon @winstywang 

We have done a pass on the new operator guide, please review this content, some of you have write access to the post and can direct edit this, otherwise, please post your reply to this issue in markdown on how this guide can be enhanced, and provide your version of enhancement.

Possible content can be a case study on how to implement a specific operator, and some detailed explanation on how some of operator works.

**Comment by tornadomeet** [comment]
Does all operators in `src/operator/tensor` need to be refactored to the new operator? we'd better have a case on how to convert a 'big operator' to the new operator, like 'convolution'.

**Comment by flyers** [comment]
The above guide does not provide an example on how to write FListInputNames when there are multiple inputs.
For operators which have multiple inputs, you may refer to https://github.com/tqchen/tinyflow/blob/master/src/op_nn.cc#L262-L277

**Comment by tqchen** [comment]
@flyers  do you mind provide an updated version that reflect this, by posting a version in this issue? Thanks!

**Comment by flyers** [comment]
@tqchen OK. I will try to update the above guide by adding some uncovered materials, and perhaps provide the bigger embedding op as an example.
