### ISSUE TITLE
Multiple `ResourceRequest::kTempSpace` in a single operator

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#3257]
It seems that we cannot use multiple `ResourceRequest::kTempSpace` in a single operator. However, in some cases, we have to create temporary spaces with different data types, like `int` and `real_t`. Is it possible to revise the current implementation to achieve that? @tqchen @piiswrong

**Comment by piiswrong** [comment]
request for bytes and cast should work

**Comment by tqchen** [comment]
I feel that the tempspace should serve as a unified temp mempry cache. And you can cast raw pointers from the TBlob, as long as pointers are aligned, we might want to have some kinda of stack like allocator function to make such casting easy.

**Comment by tqchen** [comment]
@sxjscience Do you might do a bit weight lifting here?

**Comment by sxjscience** [comment]
@tqchen  Yes, I can do that. 'm busy with deadlines these days so I may be slow for that....

**Comment by sxjscience** [comment]
We can achieve the feature by initialising a workspace with `char` type and cast it to get the other types.
For example:
```c++
// The following example allocates space for both a array with int type and an array with real_t type
workspace_size =  sizeof(int) * int_array_size + sizeof(real_t) * float_array_size;
workspace = resource.get_space_typed<xpu, 1, char>(Shape1(workspace_size), s);
char* ptr = workspace.dptr_;
int_array = Tensor<xpu, 1, int>(reinterpret_cast<int*>(ptr), Shape1(int_array_size), s);
ptr += sizeof(int) * int_array_size;
float_array = Tensor<xpu, 1, real_t>(reinterpret_cast<real_t*>(ptr), Shape1(float_array_size), s);
```
