### ISSUE TITLE
raw in MXNet Android Example

### ISSUE THREAD

**Issue by nextowang** [apache/incubator-mxnet#3262]
Dear mxnet contributors,
    I have trouble in generating the "params" files. Could you tell me how to generate this file?  I just try to change it into an acoustic model using your interface and made some experiment with that !
![qq 20160909145759](https://cloud.githubusercontent.com/assets/16679801/18378146/bcda8050-769d-11e6-9bb2-bd3bc985efd4.jpg)
    Please help me with that.  Thank you very much!

Xin Wang 
nextowang@gmail.com

Xidian University 
September 9th, 2016

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
