### ISSUE TITLE
using im2rec.cc in VS2013  with the error of ">im2rec.obj : error LNK2019: 无法解析的外部符号 "public: static class dmlc::Stream * __cdecl dmlc::Stream::Create(char const *,char const * const,bool)" (?Create@Stream@dmlc@@SAPEAV12@PEBDQEBD_N@Z)，该符号在函数 main 中被引用"

### ISSUE THREAD

**Issue by NuoerSwift** [apache/incubator-mxnet#3263]
Hello everyone:
   I want to transform the data form to rec.It is only the tool of im2rec.cc that can transform data with multilabels in one picture.However I don't know how to use it.
   I open the MxnetTestApp.sln in VS,and add the im2rec.cpp in it. It goes with the errors following.

ERROR---------------------------------------------------------------------------------------------------

1>im2rec.obj : error LNK2019: 无法解析的外部符号 "public: static class dmlc::Stream \* __cdecl dmlc::Stream::Create(char const *,char const \* const,bool)" (?Create@Stream@dmlc@@SAPEAV12@PEBDQEBD_N@Z)，该符号在函数 main 中被引用
1>im2rec.obj : error LNK2019: 无法解析的外部符号 "public: static class dmlc::InputSplit \* __cdecl dmlc::InputSplit::Create(char const *,unsigned int,unsigned int,char const *)" (?Create@InputSplit@dmlc@@SAPEAV12@PEBDII0@Z)，该符号在函数 main 中被引用
1>im2rec.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl dmlc::RecordIOWriter::WriteRecord(void const *,unsigned __int64)" (?WriteRecord@RecordIOWriter@dmlc@@QEAAXPEBX_K@Z)，该符号在函数 main 中被引用
1>D:\MXNet\windows\vs\MxnetTestApp\x64\Debug\MxnetTestApp.exe : fatal error LNK1120: 52 个无法解析的外部命令
========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by piiswrong** [comment]
try im2rec.py

**Comment by NuoerSwift** [comment]
@piiswrong 
There's no parameter of "label_width" in im2rec.py which can transform data with multilabels in one picture.    im2rec.py  and  im2rec.cc  are not the same.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
