### ISSUE TITLE
How can I implement the RCNN model by mxnet?

### ISSUE THREAD

**Issue by YuetianLiu** [apache/incubator-mxnet#3275]
I want to impelement the RCNN model by mxnet. My code is as follows:
`def rcnn_factory(data, num_filter, kernel, stride=(1,1), pad=(0,0), name=None, suffix=''):
    #conv = conv_factory(data=data, num_filter=num_filter, kernel=(3,3), name=('conv_%s' % name))
    conv = mx.symbol.Convolution(data=data, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, name = 'conv_%s%s'%(name, suffix))
    bn = mx.symbol.BatchNorm(data=conv, name='bn_%s%s'%(name,suffix))
    act = mx.symbol.LeakyReLU(data=bn, act_type='rrelu', name='rrelu%s%s'%(name,suffix))
    conv_a = mx.symbol.Convolution(data=act, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, name='conv_a_%s%s'%(name,suffix), weight='conv_%s%s_weight'%(name, suffix),no_bias=True)
    sum_a = mx.symbol.ElementWiseSum(conv, conv_a)
    bn_a = mx.symbol.BatchNorm(data=sum_a, name='bn_a_%s%s'%(name,suffix))
    act_a = mx.symbol.LeakyReLU(data=bn_a, act_type='rrelu', name='rrelua%s%s'%(name,suffix))
    conv_b = mx.symbol.Convolution( data=act_a, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, name='conv_b_%s%s'%(name, suffix), weight='conv_%s%s_weight'%(name, suffix),no_bias=True)
    sum_b = mx.symbol.ElementWiseSum(conv, conv_b)
    act_b = mx.symbol.LeakyReLU(data=sum_b, act_type='rrelu', name='rrelub%s%s'%(name,suffix))
    conv_c = mx.symbol.Convolution(data=act_b, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, name='conv_c_%s%s'%(name, suffix), weight='conv_%s%s_weight'%(name, suffix),no_bias=True)
    sum_c = mx.symbol.ElementWiseSum(conv, conv_c)
    act_c = mx.symbol.LeakyReLU(data=sum_c, act_type='rrelu', name='rreluc%s%s'%(name,suffix))
    return act_c`
The conv, conv_a, conv_b, conv_c are shared weights.

But there are some bugs.
![bug](https://cloud.githubusercontent.com/assets/8369046/18409540/209077f6-777c-11e6-8ce1-a942b115bd92.png)

The RCNN is proposed by [https://papers.nips.cc/paper/5634-convolutional-neural-networks-with-intra-layer-recurrent-connections-for-scene-labeling.pdf](url).
and the caffe model is as follows:
[model_RCNN128.txt](https://github.com/dmlc/mxnet/files/465336/model_RCNN128.txt)

**Comment by austingg** [comment]
@YuetianLiu  There are examples rcnn in example directory

**Comment by YuetianLiu** [comment]
@austingg Thank you for your reply. The RCNN is recurrent convolutional layer which is different to the rcnn examples in example directory.

**Comment by xzqjack** [comment]
@YuetianLiu Model parameters in Mxnet are stored in dictionary type. The index is parameter name.  
By now, Mxnet couldn't automatically make parameters share same weights even two layer have same name defined with `name`. You have to firstly define your parameters `Variable` with unique `name`. Then you can bind them to your desired layer just as #3113

**Comment by sxjscience** [comment]
@YuetianLiu You can refer to the LSTM example. See https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L17-L113
