### ISSUE TITLE
low accuracy of example kaggle-ndsb1

### ISSUE THREAD

**Issue by yech1990** [apache/incubator-mxnet#3279]
I follow all the instructions if the `README.md` file of example `kaggle-ndsb1`. Everything goes fine, but the accuracy of the training models is weird. 

``` bash
$ python training_curves.py
```

![image](https://cloud.githubusercontent.com/assets/5415510/18416837/e83f51d8-7852-11e6-8eb0-61b2229a064b.png)

**Comment by yech1990** [comment]
```bash
mkdir data48
../../bin/im2rec data/tr.lst ./ data48/tr.rec resize=48
../../bin/im2rec data/va.lst ./ data48/va.rec resize=48
../../bin/im2rec data/test.lst ./ data48/test.rec resize=48
ln -s ../image-classification/find_mxnet.py .
ln -s ../image-classification/train_model.py .
mkdir model
python train_dsb.py --log-file "log_tr_va" --log-dir "." --model-prefix models
python train_dsb.py --log-file "log_tr_va" --log-dir "."
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
