### ISSUE TITLE
Crash on predict - Check failed: (out_data.size()) == (2) 

### ISSUE THREAD

**Issue by JonBoyleCoding** [apache/incubator-mxnet#3287]
I first trained a network using the symbol_alexnet that can be found in the examples. The size of each exemplar is (3, 256, 256).

```
import mxnet
import symbol_alexnet

train_iter = mxnet.io.NDArrayIter(exemplars_train, labels_train, 100)
test_iter = mxnet.io.NDArrayIter(exemplars_test, labels_test, 100)

alexnet = symbol_alexnet.get_symbol(len(class_list))
epochs = 80

model = mxnet.model.FeedForward(
    ctx = mxnet.gpu(0),
    symbol=alexnet,
    num_epoch=epochs,
    learning_rate = 0.1,
    momentum = 0.9)

model.fit(
    X=train_iter,
    eval_data=test_iter,
    epoch_end_callback = mxnet.callback.do_checkpoint("chks/train", 10),
    batch_end_callback = mxnet.callback.Speedometer(100,10))

model.save("alx-%d"%(epochs))
```

This all seems to run fine, however when I try to predict from a model after loading in using this code:

```
img = cf.LoadAndConvertImage(sys.argv[1])
img = numpy.reshape(img, (1,3,256,256))
model = mxnet.model.FeedForward.load("alx-80", 80)

a = model.predict(img)
```

I end up with the following error:

> [17:19:14] /data/Programming/Libraries/mxnet/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:19:14] src/operator/./lrn-inl.h:59: Check failed: (out_data.size()) == (2) 
> [17:19:14] /data/Programming/Libraries/mxnet/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:19:14] src/engine/./threaded_engine.h:306: [17:19:14] src/operator/./lrn-inl.h:59: Check failed: (out_data.size()) == (2) 
> An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [17:19:14] src/engine/./threaded_engine.h:306: [17:19:14] src/operator/./lrn-inl.h:59: Check failed: (out_data.size()) == (2) 
> An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
> Aborted (core dumped)

Any ideas on what could cause this problem? Thanks.

**Comment by JonBoyle87** [comment]
In additional tests, I set the training epochs low so I could try a test prediction before saving, and got some different behaviour.

```
a = model.predict(exemplars_train[0:1])
print a
```
> [[ nan  nan  nan  nan  nan  nan  nan  nan  nan]]

I presume then that something has gone wrong with the training, if everything is coming out as NaNs.

**Comment by JonBoyle87** [comment]
After running the test over and over, occasionally I get values such as:

> [[ 0.02064759  0.06183811  0.00453668  0.16070589  0.04567864  0.55165589 0.03681038  0.0664523   0.05167448 ]]

but mostly I just get the NaNs. The only times this happens is when I print the arg_params from the FeedForward model before predicting (but not always).

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
