### ISSUE TITLE
suggest to add 'roi_warp_layer' operator

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#3299]
Instance-aware Semantic Segmentation via Multi-task Network Cascades.
https://arxiv.org/abs/1512.04412

**Comment by sxjscience** [comment]
I'll ask @Oh233 if he has time to implement it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
