### ISSUE TITLE
VOTE for MXNet's new logo!

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#3305]
We need a new logo to replace the current one since I received several negative comments about the latter. 

William Wang from Amazon kindly provides us several candidates. Please thumb up the post below if you like it. Any comment and suggestion is also welcome.

Please vote with github's thumb up feature:
![image](https://cloud.githubusercontent.com/assets/568948/18532589/de8ab68c-7a91-11e6-9f85-41699135c3a6.png)

**Comment by piiswrong** [comment]
1. Ribbon 1

   <img width="232" alt="screen shot 2016-09-02 at 11 21 48 am" src="https://cloud.githubusercontent.com/assets/421857/18213943/75fa655e-70ff-11e6-9ae8-629507f3aee8.png">

    The idea of a continuous shape to form the logo I think communicates the concept of flexilbity well, and is conceptually similar to related competitors in the space. This gives us a logo mark that can be used alone for the “MX” or with the logotype below combined.

**Comment by piiswrong** [comment]
2. Ribbon 2

    <img width="241" alt="screen shot 2016-09-02 at 11 22 46 am" src="https://cloud.githubusercontent.com/assets/421857/18213971/97fcdcc2-70ff-11e6-874d-d35e1bf84031.png">

   Same idea as above, but slightly different design.

**Comment by piiswrong** [comment]
3. MX polygon

    <img width="314" alt="screen shot 2016-09-02 at 11 23 33 am" src="https://cloud.githubusercontent.com/assets/421857/18214013/c33f893e-70ff-11e6-84aa-ab56f76100c6.png">

    Abstracted shape of “M” and “X” that is intended to look like a butterfly/crystal shape. It has some three dimensionality depending on the colors we use.

**Comment by piiswrong** [comment]
4. Continuous line

    <img width="285" alt="screen shot 2016-09-02 at 11 23 42 am" src="https://cloud.githubusercontent.com/assets/421857/18214032/d910acc0-70ff-11e6-9740-bf668889898a.png">

    A single line forming MX, with a partial infinity loop at the end

**Comment by piiswrong** [comment]
Let't use github's new thumb up feature.

BTW, I like green better :)

**Comment by mli** [comment]
Everything is available in green. Vote this post if you like blue.

<img width="241" alt="screen shot 2016-09-02 at 11 22 46 am" src="https://cloud.githubusercontent.com/assets/421857/18213971/97fcdcc2-70ff-11e6-874d-d35e1bf84031.png">

**Comment by mli** [comment]
Vote this post if you like green

<img width="304" alt="screen shot 2016-09-14 at 3 30 00 pm" src="https://cloud.githubusercontent.com/assets/421857/18532409/c3924062-7a90-11e6-8c9f-9ca9a25756e5.png">

**Comment by mli** [comment]
Please feel free to submit any other logo candidates.

**Comment by piiswrong** [comment]
The blue one is actually a little different from the green one. I like the blue one's shape better. M should be a little smaller and X should be bigger.

**Comment by starimpact** [comment]
```MX polygon``` is definitely the best one.

**Comment by Beronx86** [comment]
The first one is concise and easy to recognize.

**Comment by xianyi** [comment]
I prefer blue than green for software icon.

**Comment by weihwang** [comment]
Hi everyone, William here. I wanted to share a few other color options since I feel strongly about avoiding the green design so that the MXNet logo can be more unique. I added some sample colors and reference to other brands out there to help the group reach a final color choice. To me, in order to stand out, the MXNet logo should use blue or purple as the main color.

![mxnet-logo-color-test-08](https://cloud.githubusercontent.com/assets/551333/19164038/3bbb0302-8bb3-11e6-9bd7-3119a56cd7eb.png)

![mxnet-logo-color-test-07](https://cloud.githubusercontent.com/assets/551333/19164044/4040c5ba-8bb3-11e6-9e52-943c52ba7472.png)

**Comment by csyking** [comment]
Design for MXNet's new logo to embrace open source. Please thumb up the post below if you like it. Any comment and suggestion is also welcome.
[http://photo.weibo.com/h5/comment/compic_id/1022:230597eecbfea942c091c899153f4667c126ff](url)

**Comment by csyking** [comment]
Design for MXNet's new logo to embrace open source. Please thumb up the post below if you like it. Any comment and suggestion is also welcome.
http://t.cn/RfB1fqH

**Comment by csyking** [comment]
Design for MXNet's new logo to embrace open source. Please thumb up the post below if you like it. Any comment and suggestion is also welcome.
the logo site is: http://t.cn/RfB1fqH

**Comment by ozgurakan** [comment]
I like the blue best but "MXNet" text could be better.
