### ISSUE TITLE
Proposal on building tensorboard-like tool

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#3306]
By using Kibana+Logstash tech stack. It's a very common and matured tool(also open-sourced) in industry. It provides the interface to show&collect logs from various machines. Therefore what we only need to do is design the format of mxnet's output log about what to export to the tool.

And it can be deployed easily&independently by docker.

Just a very naive idea. But I believe this tool will makes mxnet easier to use. It's also useful in real industry community.

**Comment by piiswrong** [comment]
logging and visualization is something we should have. I don't know about Kibana+Logstash though. Seems like pretty heavy machinery with a log of dependencies. Is it really necessary?

**Comment by VoVAllen** [comment]
Yes, you are right……They are much bigger than I thought. I'll keep on finding appropriate tools to do so.

**Comment by VoVAllen** [comment]
However I would say logging and visualization are kind of independent. Maybe we could start from logging first.

**Comment by piiswrong** [comment]
yes. We can even consider using tensorflow's logging format and try to strip tensorboard out of tensorflow

**Comment by austingg** [comment]
@piiswrong  for visualization log, you may reference nvidia-digits, there is a light-weight web-based module based on python flask.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
