### ISSUE TITLE
the bug of the adversary example

### ISSUE THREAD

**Issue by YuetianLiu** [apache/incubator-mxnet#3315]
Hi,
    I run the adversary code in the example/adversary/adversaty_generation.ipynb, but it has some bugs as follows:
![bug1](https://cloud.githubusercontent.com/assets/8369046/18612466/0633d562-7d8d-11e6-85f0-7afb30ff50bd.png)
![bug2](https://cloud.githubusercontent.com/assets/8369046/18612467/0c40ad54-7d8d-11e6-90c1-27a4e1f3466e.png)
![bug3](https://cloud.githubusercontent.com/assets/8369046/18612468/0fdaf94c-7d8d-11e6-8aa3-2852393c1882.png)

Thanks!

**Comment by piiswrong** [comment]
change it to 
```
for batch in train_iter:
    data = batch.data
    label = batch.label
```
Could you submit a pr if you can get it working?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
