### ISSUE TITLE
How do I know if mxnet was compiled with USE_CUDA=1 ?

### ISSUE THREAD

**Issue by guy4261** [apache/incubator-mxnet#3319]
I'm working on a remote cluster environment where mxnet is installed but not by me.
This page says it will only work with CUDA if it was compiled accordingly:
https://github.com/dmlc/mxnet/blob/master/docs/how_to/multi_devices.md
Is there a way I can check if my version of mxnet was compiled with USE_CUDA=1?

**Comment by tornadomeet** [comment]
```ldd libmxnet.so``` to see if there is a link to *cuda*.so like
```
inux-vdso.so.1 =>  (0x00007ffc420c3000)
	/lib64/libharfbuzz.so (0x00007fe736167000)
	libcudart.so.7.5 => /usr/local/cuda/lib64/libcudart.so.7.5 (0x00007fe735f09000)
	libcublas.so.7.5 => /usr/local/cuda/lib64/libcublas.so.7.5 (0x00007fe73462a000)
	libcurand.so.7.5 => /usr/local/cuda/lib64/libcurand.so.7.5 (0x00007fe730dc1000)
	libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007fe72e9ab000)
...
```

**Comment by wushouchuan** [comment]
mxnet/make/config.mk

**Comment by guy4261** [comment]
Thank you both.
It could make a nice feature to have this available programatically, i.e.
```python
>>> mxnet.using_cuda
True # or False
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
