### ISSUE TITLE
Cannot run rcnn training

### ISSUE THREAD

**Issue by Trangle** [apache/incubator-mxnet#3321]
the log is like this:
INFO:root:########## TRAIN RPN WITH IMAGENET INIT
INFO:root:########## GENERATE RPN DETECTION
voc_2007_trainval gt roidb loaded from D:\Data\faster_rcnn\cache\voc_2007_trainval_gt_roidb.pkl
prepare roidb
generating detections 0/5011
generating detections 10/5011
generating detections 20/5011
generating detections 30/5011
generating detections 40/5011
generating detections 50/5011
generating detections 60/5011
generating detections 70/5011
generating detections 80/5011
generating detections 90/5011
generating detections 100/5011
generating detections 110/5011
generating detections 120/5011
generating detections 130/5011
generating detections 140/5011
generating detections 150/5011
generating detections 160/5011
[21:57:37] D:\MyCoding\DeepLearning\OpenSource\dmlc\mxnet\dmlc-core\include\dmlc/logging.h:235: [21:57:37] D:\MyCoding\DeepLearning\OpenSource\dmlc\mxnet\src\operator\cudnn_convolution.cc:225: Check failed: (cudnnFindConvolutionF
orwardAlgorithm(s->dnn_handle_, in_desc, filter_desc, conv_desc, out_desc, kMaxAlgos, &nalgo, fwd_algo)) == (CUDNN_STATUS_SUCCESS)
[21:57:37] D:\MyCoding\DeepLearning\OpenSource\dmlc\mxnet\dmlc-core\include\dmlc/logging.h:235: [21:57:37] d:\mycoding\deeplearning\opensource\dmlc\mxnet\src\engine./threaded_engine.h:306: [21:57:37] D:\MyCoding\DeepLearning\Ope
nSource\dmlc\mxnet\src\operator\cudnn_convolution.cc:225: Check failed: (cudnnFindConvolutionForwardAlgorithm(s->dnn_handle_, in_desc, filter_desc, conv_desc, out_desc, kMaxAlgos, &nalgo, fwd_algo)) == (CUDNN_STATUS_SUCCESS)
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all oper
ations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

i use gtx980m with 8g graph memory, and use model vgg16 as default, it seems that the memory was not free during the forward waiting period cause the batchsize is only 1.

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
Set environment variable
MXNET_ENGINE_TYPE=NaiveEngine
MXNET_CUDNN_AUTOTUNE_DEFAULT=0.
If this is not working, change StorageManager to NaiveStorageManager.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
