### ISSUE TITLE
Is there any typo in "Dependency Engine for Deep Learning"?

### ISSUE THREAD

**Issue by maxint** [apache/incubator-mxnet#3347]
https://github.com/dmlc/mxnet/blob/master/docs/system/note_engine.md#case-study-on-multi-gpu-neural-net

The original sample code is:

``` python
# aggregate gradient and update
fc1_wgrad[cpu]  = fc1_wgrad[gpu0] + fc1_wgrad[gpu1]
fc2_wgrad[cpu]  = fc2_wgrad[gpu0] + fc2_wgrad[gpu1]
fc1_weight[cpu] -= lr *  fc1_wgrad[gpu0] # typo here?
fc2_weight[cpu] -= lr *  fc2_wgrad[gpu0] # typo here?
fc1_weight[cpu].copyto(fc1_weight[gpu0] , fc1_weight[gpu1])
fc2_weight[cpu].copyto(fc2_weight[gpu0] , fc2_weight[gpu1])
```

Should it be revised as following?

``` python
fc1_weight[cpu] -= lr *  fc1_wgrad[cpu] # corrected here
fc2_weight[cpu] -= lr *  fc2_wgrad[cpu] # corrected here
```

There is same problem in the graph show:

![](https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/engine/dep_net.png)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
