### ISSUE TITLE
alexnet parameter amount inconsistent

### ISSUE THREAD

**Issue by dx80232** [apache/incubator-mxnet#3348]
I tried to utilize the example code in _./example/image-classification/symbol_alexnet.py_.
However, when I checked the shape to compute the parameter amount of the network, I found that it was not consist to the number presented in the original paper (~60M).

```
shape checking:
(96, 3, 11, 11)     param: 34848
(96, )              param: 96
(256, 96, 5, 5)     param: 614400
(256, )             param: 256
(384, 256, 3, 3)    param: 884736
(384, )             param: 384
(384, 384, 3, 3)    param: 1327104
(384, )             param: 384
(256, 384, 3, 3)    param: 884736
(256, )             param: 256
(4096, 6400)        param: 26214400
(4096, )            param: 4096
(4096, 4096)        param: 16777216
(4096, )            param: 4096
(1000, 4096)        param: 4096000
(1000, )            param: 1000

Total parameter: 50844008 (~50M)
```

I guessed the problem occurs between the pooling layer and the fully-connected layer, but I had no idea how to solve it.
Does anyone know how to fix it to make it correspond to what the original paper mentions?
Thanks.

**Comment by guolinke** [comment]
Same issue. 
The shape between poll_3 and fc_1 should be (4096, 9216).  
I try to use flatten = mx.symbol.Reshape(data=pool3, target=[0, 256 * 6 * 6]), but it don't work.

**Comment by guolinke** [comment]
fixed. add pad=(2,2) at first conv layer. 
 https://github.com/guolinke/deep-learning-benchmarks/blob/master/mxnet/models/alexnet.py#L15

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
