### ISSUE TITLE
Win10 DLL for R and MATLAB conflict?

### ISSUE THREAD

**Issue by Qunal** [apache/incubator-mxnet#3352]
Hoping to get some insight. Now I have used MXNET  with R and Python on Win 10 64 bit for 2 weeks.. The R DRAT and binary install method seems to work. I wanted to check is there is a conflict as mxnet is added as a library in R with code in folder under R_USERLIB ( not in R_HOME) and in Python under Anaconda . Do the DLL get placed in various folders with chance of conflict. If I am running a example in R and in Python using MXNET at same time will it be Ok.

In R there is a weekly update possibility. What anout python. Do I need to do it manually?

And I keep getting issues with MATLAB as reported earlier.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
