### ISSUE TITLE
Why is LOG(INFO)  not working as supposed in mxnet C++ code ?

### ISSUE THREAD

**Issue by aaronwater** [apache/incubator-mxnet#3353]
I ran example/image-classification/train_mnist.py with batch_size = 10000, so there would be 6 batches for the forword training ( val is set to None)，the Forword function of the first Fully-connect layer should be called 6 times. I added some debug codes as follows:
![p hayw f d 0 t 11 i u3j](https://cloud.githubusercontent.com/assets/21171292/18749082/de8e6ada-8107-11e6-9df1-3f52a0650dcc.png)
![o466yu t _ tq_ yrezt3oy](https://cloud.githubusercontent.com/assets/21171292/18749092/e5510e18-8107-11e6-9b6c-40553ccf2522.png)

But the log printed  is not what I supposed:
![_o smuqtw sdk ou 6 ji](https://cloud.githubusercontent.com/assets/21171292/18749230/6e527bfc-8108-11e6-9e58-a54226372fd3.png)

why is "logger.info(load123)" in python executed 6 times as supposed, while  "LOG(INFO) << "forward123" in fully_connected-inl.h just once ? 
@piiswrong

**Comment by piiswrong** [comment]
add execmanager.update_metric at the end

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
