### ISSUE TITLE
Features in mysql database

### ISSUE THREAD

**Issue by rpalenik** [apache/incubator-mxnet#3354]
Hello, I am new in mxnet and trying to figure out the way how to train my model with features in a large mysql table. Is there any iterator/code  for mysql?

**Comment by piiswrong** [comment]
inherit mx.io.DataIter and connect to mysql from python
http://stackoverflow.com/questions/372885/how-do-i-connect-to-a-mysql-database-in-python

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
