### ISSUE TITLE
amalgamation for full convolution network, memory leak

### ISSUE THREAD

**Issue by luweishuang** [apache/incubator-mxnet#3364]
I use [https://github.com/Leliana/WhatsThis](url) framework and recompiled jni_libmxnet_predict.so to support my own network.  There're convolution, batchnorm, relu, deconvolution, residual block in my network and it's a fully convolution network which has a random input data shape(not fixed to 1_3_224*224). So I change a little the [https://github.com/Leliana/WhatsThis](url) java code and some core code like this:
`
- Predictor predictor = WhatsApplication.mInstance.getPredictor(inWidth, inHeight);
- predictor.forward("data", colors);
- float [] outputData=predictor.getOutput(0);
- ....
- predictor.free();

`
for the input image may has a size of "512*512" and a forward calculation would need about 200M memory size in android phone. Usually I did forward calculation three times or more the apk will break because of out of memory. I have do "predictor.free();"  as you see and I doubt  there is a memory leak in mxnet_predict-all.cc. I also found this situalation in [https://github.com/pppoe/WhatsThis-iOS](url) as using my fcn. looking for helps about how to solve this memory leak or the right way to do fcn in android using mxnet

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
