### ISSUE TITLE
Can I pass non-tensor data as a c++ object through layers?

### ISSUE THREAD

**Issue by x10000year** [apache/incubator-mxnet#3370]
I want to implement a layer which can output non tensor data as a c++ object that is stored in cpu memory. In caffe, I can store the object as a data member of a layer, and pass the address of the object in a Blob to subsequent layers. Storing the memory address in a Blob is a hack but it works, because in caffe every thread has separate layer instances, and the computation of a minibatch doesn't cross over different threads/machines. Can I do the same thing in mxnet?

**Comment by piiswrong** [comment]
it should work for cpu layers

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
