### ISSUE TITLE
redefine #CHECK in sframe plugin

### ISSUE THREAD

**Issue by uzhao** [apache/incubator-mxnet#3372]
I got this error in log when I make with sframe plugin

In file included from /home/papillon/SFrame/oss_src/serialization/iarchive.hpp:42:0,
                 from /home/papillon/SFrame/oss_src/serialization/serialize.hpp:34,
                 from /home/papillon/SFrame/oss_src/serialization/serialization_includes.hpp:33,
                 from /home/papillon/SFrame/oss_src/parallel/atomic.hpp:38,
                 from /home/papillon/SFrame/oss_src/flexible_type/flexible_type.hpp:17,
                 from /home/papillon/SFrame/oss_src/unity/lib/image_util.hpp:12,
                 from plugin/sframe/iter_sframe.cc:16:
/home/papillon/SFrame/oss_src/logger/assertions.hpp:119:0: warning: "CHECK" redefined
 #define CHECK(condition)                                                \

**Comment by winstywang** [comment]
@antinucleon

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
