### ISSUE TITLE
problem about setup.py on nnvm branch

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#3399]
when using https://github.com/dmlc/mxnet/blob/nnvm/python/setup.py#L7 to install mxnet by:

``` shell
 python setup.py install --user
```

then the libmxnet.so is not installed , because when using`import mxnet` is will export error.
if we change from `from distutils.core import setup` to `from setuptools import setup`, then it will be ok.   

@piiswrong @tqchen how to fix this?

**Comment by tqchen** [comment]
There is two conflicting things, if the install command is inplace, distutils.core works better because things are copied to the right inplace folder.

If install by user seems setuptools works better. Maybe we should find a better way to solve this problem

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
