### ISSUE TITLE
speech demo baselines

### ISSUE THREAD

**Issue by danpovey** [apache/incubator-mxnet#3402]
Guys,
someone pointed out this repo to me...
I'm a little confused where you are getting your kaldi baselines for AMI from... they seem quite a bit worse than what we have checked in right now.  BTW the AMI s5b recipe is probably a better starting point than AMI s5.  But in either case your results are quite a lot worse than what we have checked in.

**Comment by antinucleon** [comment]
The current speech demo breaks by a bug in clip gradient setting. We are going to fix it very soon.

**Comment by danpovey** [comment]
I wasn't actually running it, I was just looking at the reported numbers.
I suspect you guys may have looked at, and copied, the Kaldi AMI scripts about a year ago, and maybe the results were a lot worse at that time.

**Comment by antinucleon** [comment]
Thanks for pointing out it. Let's sync with @pluskid @yzhang87

**Comment by yzhang87** [comment]
@danpovey, yeah, the AMI scripts was a year ago. I noticed it is much better now but haven't sync with it.

**Comment by danpovey** [comment]
There are many changes that will improve your numbers, but also changes to
our nnet training that will improve our numbers.. it will make the
comparison much more meaningful if you switch over to using the newer
recipes.

**Comment by yzhang87** [comment]
Thanks for point out! We were waiting for the NNVM support for RNN. Will update the whole things soon.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
