### ISSUE TITLE
How can I make a facial landmark prediction using the .params and .json files on windows

### ISSUE THREAD

**Issue by Rainy000** [apache/incubator-mxnet#3409]
I have trained a usable facial landmark model on linux using python, but now I want to use the model to make prediction by  C++ on windows. I am not familiar with C++ very much ,is anyone can give me some instructions ?

**Comment by thirdwing** [comment]
I think you can use https://github.com/dmlc/mxnet/tree/master/example/cpp/image-classification as an example

**Comment by Rainy000** [comment]
@thirdwing Thank you very much,  I will try it!

**Comment by Rainy000** [comment]
@thirdwing  I add the libmxnet.dll to system root, and copy the libmxnet.lib to my project. I write one statement  #pragma comment(lib,"libmxnet.lib")  in image-classification-predict.cc file , but some errors also occur when I building this project,such as 1>predict.obj : error LNK2019: 无法解析的外部符号 __imp__MXPredCreate，该符号在函数 _main 中被引用.

**Comment by Rainy000** [comment]
@thirdwing  usually, those errors occur when the *.lib is missing .  Is MXPredCreate API is not included in libmxnet.lib？

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by Rainy000** [comment]
@yajiedesign OK, I have solved this problem early. Thank you!
