### ISSUE TITLE
what are the values in kernel, dshape, pad? 

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#3415]
Hi All MXNET users,

When I run googlenet and other networks, many times I have the following errors:

mxnet/dmlc-core/include/dmlc/logging.h:235: [11:27:37] src/operator/./pooling-inl.h:200: Check failed: param_.kernel[0] <= dshape[2] + 2 \* param_.pad[0] && param_.kernel[1] <= dshape[3] + 2 \* param_.pad[1] kernel size exceed input

For ILSVRC2012 ImageNet data, I resized the images to 256 when creating .rec database. When I run train_imagenet.py with 4 GPUs, I tried several settings:
(1) batch_size=144  and data_shape=256
(2) batch_size=128 and data_shape=224
(3) batch_size=256 and data_shape=224

only (1) was working, and the other two had the above errors. The gdb for python cannot be used on my server now and I cannot install it. So I cannot debug the program to check the values in these parameters. Could anyone explain what are the values in kernel, dshape and pad? So that I can know which values should be chosen. Thanks.

Regards,
Rengan

**Comment by piiswrong** [comment]
googlenet uses at least 300x300 input images.

**Comment by hfutxrg** [comment]
But why it was working for 256x256 images? Could you explain a bit more about kernel, dshape and pad? Thanks.

**Comment by winstywang** [comment]
It may related to the pretrained model issue. We will update the pretrained model soon.

**Comment by hfutxrg** [comment]
Why it was related to pretrained model? I trained the model from scratch.

**Comment by winstywang** [comment]
@hfutxrg Could you try the lastest symbol? It works for me.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
