### ISSUE TITLE
 use fit with a network with two inputs with different sized images?

### ISSUE THREAD

**Issue by ironblue** [apache/incubator-mxnet#3417]
Hi,

I can build a model with two input but i can't train it. I would build one model with two different input and in next levels the network  merge the Feature map.

Thank you

**Comment by marugari** [comment]
Is this what you want?
https://github.com/marugari/Notebooks/blob/master/mxnet_multi-input_multi-output.ipynb

**Comment by ironblue** [comment]
Thank you

my problem is similar at your code but it not the same. In my case i have a
single output and different image input. I wrote a stupid network only for
example. In this network data1 and data2 have two image with different
resolution ( course in level "Concat" shapes should be equal, but this just
an example). If i wanted to change code in train_imagenet.py and the
relative code for read image dataset (ImageRecordIter), how can i do?
I have made many tests but without result!

But thank you very much for your response!


get_symbol <- function(num_classes = 1000) {

data1 <- mx.symbol.Variable('data1')
data2 <- mx.symbol.Variable('data2')


conv1 <- mx.symbol.Convolution(data = data1, kernel = c(5, 5), num_filter =
20)


conv2 <- mx.symbol.Convolution(data = data2, kernel = c(10, 10), num_filter
= 50)

tanh1 <- mx.symbol.Activation(data = conv1, act_type = "tanh")

tanh2 <- mx.symbol.Activation(data = conv2, act_type = "tanh")

actf = mx.symbol.concat[tanh1,tanh2];

flatten <- mx.symbol.Flatten(data = actf)

fc1 <- mx.symbol.FullyConnected(data = flatten, num_hidden = 500)

tanh3 <- mx.symbol.Activation(data = fc1, act_type = "tanh")

# second fullc

fc2 <- mx.symbol.FullyConnected(data = tanh3, num_hidden = num_classes)

# loss

lenet <- mx.symbol.SoftmaxOutput(data = fc2, name = 'softmax')

return(lenet)

}

2016-10-02 13:02 GMT+02:00 Yoshinori Nakano <notifications@github.com>:

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
