### ISSUE TITLE
希望加强Neural art

### ISSUE THREAD

**Issue by qggjonny** [apache/incubator-mxnet#3425]
身边很多程序员是想玩Neural art才下载mxnet的，Neural art目前看来有两个缺陷，一是可选参数比https://github.com/jcjohnson/neural-style 少很多，另一个是做不了 deepart.io 那样的样式，例如： https://deepart-io.s3.amazonaws.com/cache/d0/70/d0706a734b53118ef47cf975a444f5c2.jpg 或者 https://deepart-io.s3.amazonaws.com/cache/a8/fd/a8fdba4b86ee61b1658075682edd5679.jpg ，希望加强Neural art成明星样例，这样对mxnet的普及应该会很有帮助。

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
