### ISSUE TITLE
Training/testing only layers?

### ISSUE THREAD

**Issue by eldercrow** [apache/incubator-mxnet#3439]
I am now trying to implement the paper:
https://arxiv.org/abs/1604.02878
which detects faces and regresses their bounding boxes at the same time. 
For BB regression, I use L_2 distance metric based loss, but in testing I want to use different evaluation metric rather than simply using L_2 distance. For that I want to use some intermediate layers within the network but I found that I can only use the outputs from get_outputs() function in evaluation. Caffe, for instance, has the "phase" keyword so that the network structure can vary between training and testing phases. Dose mxnet have a similar functionality?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
