### ISSUE TITLE
Install mxnet into anaconda's python

### ISSUE THREAD

**Issue by jacklxc** [apache/incubator-mxnet#3441]
I'm trying to use minpy which requires mxnet in anaconda's jupyter notebook. minpy can be installed using anaconda's pip successfully.

However there is an issue on installing mxnet. I noticed using anaconda's "pip install mxnet" does not work (opencv not found, although opencv.pc clearly exists and the path is correctly set). So I wonder how can I install mxnet into anaconda's python, instead of system's default python by changing some settings? I figured out I can disable using opencv by changing config.mk file. I used a similar way to get both minpy and mxnet work on system's default python.

Thank you.

**Comment by zihaolucky** [comment]
You should use `python setup install` under python directory when you are in your anaconda's virtual env. 

Follow the instruction here: http://mxnet.readthedocs.org/en/latest/how_to/build.html

**Comment by starimpact** [comment]
do not use 'sudo' when you type 'python setup install', and your anaconda path should be in environment variable PATH.

**Comment by RogerBorras** [comment]
Can you provide an easy conda installation for mxnet? It will be very usefull!

**Comment by zihaolucky** [comment]
@RogerBorras do you mean `conda install mxnet`?

**Comment by RogerBorras** [comment]
@zihaolucky Yes :)

**Comment by zihaolucky** [comment]
Okay, I understand. Since I'm not familiar with conda itself, and tensorflow does support `conda install tensorflow`, so let's do some research and see if that's possible.

Reference:

https://github.com/conda-forge/tensorflow-feedstock

**Comment by RogerBorras** [comment]
As far as I know, is not difficult to create a conda installer if you have installed the normal Python version. But I have problems to install it in conda distribution. It would be great for a lot of users if you can provide it. Is avaliable an mxnet conda installer for OSX-64 (but not for windows and linux):

[https://anaconda.org/derickl/mxnet](url)


Thanks for your amazing mxnet library!

**Comment by zihaolucky** [comment]
@RogerBorras Yes, the link in my previous comment might provide a promising source to provide this feature for MXNet easy installation :)

**Comment by RogerBorras** [comment]
@zihaolucky Great!

**Comment by RogerBorras** [comment]
@zihaolucky Any progress?? :)

**Comment by zihaolucky** [comment]
@RogerBorras sorry for no any progress on this direction and let you down. 

I've check the material above but fail to get any useful information, besides I'm now working on a project to bring TensorBoard to MXNet so I'm afraid I have no enough energy to work on this for a while. But I would keep it and work again when I have time.

**Comment by RogerBorras** [comment]
@zihaolucky No problem, I use MXNet in R too and Tensorboard in MXNet will be a great feature!!

**Comment by zihaolucky** [comment]
Hi @RogerBorras @jacklxc 

As I'm working on the TensorBoard project, https://github.com/dmlc/tensorboard/pull/2 I learned how to provide a `.whl` for easy installation just like TensorFlow does. In TensorFlow, they provide different `.whl` and TF could be easily installed via `pip install $TF_BINARY_URL`. 

Just pack all external dependencies, like `libmxnet.so` and setup properly in `setup.py`, then ` python setup.py bdist_wheel >/dev/null` and you can get the distributable `.whl`.

I would let you know after I finished the experiment in TensorBoard and provide a proper solution for MXNet.

**Comment by RogerBorras** [comment]
Great news @zihaolucky! Many thanks for your effort :)

**Comment by littlelid** [comment]
Hi, I have DONE this by this way:
before you execute `bash install-mxnet-XXX.sh` , you need do some changes in this `.sh` file. Don't be afraid,it's very sample.

1. find code in `.sh`file like this:    
`runme python setup.py install`    
2. change this line to this:
`runme /the/absolute/path/to/anaconda/bin/python setup.py install`
3. save the file,and use the bash to run

**DONE**

**Comment by NaiveScript** [comment]
Fllowing official installation guid,.At last,you shouldn't use 
`sudo python setup.py install`
 Because the sudo option will install mxnet in built in python version.cause anaconda will have a environmental path,you just need to use
`python setup.py install`
However before that, you should make all the files in ~/mxnet/python with common accecess right,the most easy way is use
`sudo chmod  -R 777 ~/mxnet/python`
before install. 
Note, ~/mxnet/python is the path to your python folder in mxnet,you can use absolute path if any problem happens.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by RajeshRaja27** [comment]
Its not installing on Windows on condaprompt when giving conda install mxnet???
Then How i should install it

**Comment by jakirkham** [comment]
We at [conda-forge]( https://conda-forge.org/ ) would be happy to help you with the review of an `mxnet` recipe for `conda` if someone would be interested in submitting one. Issue ( https://github.com/conda-forge/staged-recipes/issues/4447 ) would be a great place to discuss this if someone would like to step forward.

**Comment by wenboown** [comment]
I figured out a way to install mxnet in conda. I recorded the steps here:

**Comment by wenboown** [comment]
I figured out how to build `mxnet` from source for `conda` for macOS 10.12 and 10.13. Here's the step-by-step guide:
[https://boknowsit.wordpress.com/2018/05/30/setting-up-mxnet-on-macos-with-conda/](url)
