### ISSUE TITLE
What does "Please pass all the input Symbols via positional arguments instead of keyword arguments." mean?

### ISSUE THREAD

**Issue by yxchng** [apache/incubator-mxnet#3442]
I am having this problem when using the UpSampling layer

**Comment by piiswrong** [comment]
data=x -> x

**Comment by yxchng** [comment]
why some layer allows me to specify data=x but some doesn't?

**Comment by winstywang** [comment]
Some layers need the order. For example, concat.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
