### ISSUE TITLE
How to make a prediction of heatmap (matrix) when y can only be dimension 1?

### ISSUE THREAD

**Issue by yxchng** [apache/incubator-mxnet#3444]
How to make a prediction of heatmap (matrix) when y can only be dimension 1?

I intend to predict the pixel location of the body pose, where each pixel is a probability of the pose. Hence, I should have a matrix of the same size as the input image. However, I am encountering the following error when y is a matrix: ValueError: Label must be 1D or 2D (with 2nd dimension being 1)

**Comment by piiswrong** [comment]
use softmax with multi_output=True

**Comment by yxchng** [comment]
i am not passing the output of the last layer through softmax. In fact, the last layer is just a convolution layer and the size of the output is 64x64

**Comment by yxchng** [comment]
in fact i need my label to be of dimension (batch_size, number_of_heat_maps=16, dimension_y=64, dimension_x=64). For each image, it has to predict 16 heatmaps of size 64x64.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
