### ISSUE TITLE
request: move/add L1 L2 regularization to layers/symbols

### ISSUE THREAD

**Issue by ivokwee** [apache/incubator-mxnet#3445]
I think it would be great to move the L2 (and adding L1) regularization from the solver to the layers/symbols. I believe Keras does this. In this way L1/L2 can be specified per layer and not global. Also all solvers will just work. Gradient will just be modified by each layer. What do you think? Is that easy to do?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by Hui-Li** [comment]
Any updates about this? I am transferring some algorithms from keras to mxnet and need to specify regularization for each layer.
