### ISSUE TITLE
How to use im2rec when both input and label are images?

### ISSUE THREAD

**Issue by yxchng** [apache/incubator-mxnet#3449]
How to use im2rec when both input and label are images?

I have seen how to make multilabel rec using im2rec but there does not seem to be any instruction on how to make rec where the labels are images as well.

Does mxnet also support this function?

**Comment by rayjs** [comment]
There are two ways to do this:

First one uses file iterator. See the example here (both input and label are images):
https://github.com/dmlc/mxnet/tree/master/example/fcn-xs

The second way to do this would be first create two image recorders (using im2rec tool) one for the input and the other for the labels.   Now implement a file iterator that takes in these two recorders files as argument and produces a data batch object somethign similar to this: https://github.com/dmlc/mxnet/blob/master/example/multi-task/example_multi_task.py

**Comment by zhangfanqie** [comment]
@yxchng  Could you please tell me how to make label images? I tried labelme but got some error.I'm new with mxnet. Thanks a lot!

**Comment by zhangfanqie** [comment]
@yxchng Hi,me again.Did you solve the problem? I also dont know how to make .rec where the labels are images as well.

**Comment by zrxzrx** [comment]
@zhangfanqie nope sorry

**Comment by yxchng** [comment]
@zhangfanqie nope sorry

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
