### ISSUE TITLE
NCE Loss has dead argument

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#3450]
@xlvector: the argument `num_label` is not used anywhere in the function definition `nce_loss(data, label, label_weight, embed_weight, vocab_size, num_hidden, num_label)` in [nce.py](https://github.com/dmlc/mxnet/blob/master/example/nce-loss/nce.py). Should be removed.

**Comment by tornadomeet** [comment]
@sbodenstein give a pr please~

**Comment by xlvector** [comment]
Yes, previous implement need this. However, after I use broadcast_mul, its not needed. Feel free to remove it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
