### ISSUE TITLE
Library built with VS2015 causes python a hang

### ISSUE THREAD

**Issue by aaronzs** [apache/incubator-mxnet#3452]
Hi,

I built mxnet from master branch on a Windows 7 machine with Visual Studio 2015 Update 3, CUDA 8, CuDNN 5.1 and MKL. There was no error and only a few warnings when I built it. When I tested it with the examples, for instance, image classification, the task could finish (I mean I can get the results) but python could not quit properly. There is no error message and I had to kill the python process manually. I tried GPU and CPU modes, both have this issue.

**Comment by tornadomeet** [comment]
@aaronzs  could you debug the code and figure out which line cause the quit problem.

**Comment by NoNamesLeft4Me** [comment]
@aaronzs Have you solved this problem yet? I tried to built mxnet with VS 2015, but it failed when I installed Python interface. I am starting to wonder if VS 2015 is the reason.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
