### ISSUE TITLE
Pooling formula seems wrong to cause Googlenetv1 not working

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#3457]
If trying https://github.com/soumith/convnet-benchmarks/blob/master/mxnet/gnetv1.py using mxnet, the error report 
mxnet.base.MXNetError: InferShape Error in pooling4: [13:02:47] src/operator/./pooling-inl.h:200: Check failed: param_.kernel[0] <= dshape[2] + 2 \* param_.pad[0] && param_.kernel[1] <= dshape[3] + 2 \* param_.pad[1] kernel size exceed input 

I think the reason is that the pooling formula in Mxnet may be wrong? If change the formula to 
oshape[2] = 1 + (dshape[2] + 2 \* param_.pad[0] - param_.kernel[0] + param_.stride[0] - 1) / param_.stride[0];
Then it run well. 

Are you aware of this issue?

**Comment by sxjscience** [comment]
Yes, we are trying to make the pooling compatible to Caffe by adding a new option. It should be fixed after https://github.com/dmlc/mxnet/pull/3438 gets merged.

**Comment by zhenlinluo** [comment]
I don't think these two things are the same thing. Since #3458 is not changing the formula. Maybe I should submit a separate PR for this?

**Comment by sxjscience** [comment]
@zhenlinluo We have this PR (https://github.com/dmlc/mxnet/pull/3392), which is included in https://github.com/dmlc/mxnet/pull/3438.

**Comment by piiswrong** [comment]
@zhenlinluo btw we have dmlc/mxnet-deepmark for benchmarking

**Comment by zhenlinluo** [comment]
I try #3458 using convnet gnetv1 but it is stil failed. In deepmark, there have no googlenetv1 symbol yet. @sxjscience @piiswrong Did you test it in your side? Can you share your gnetv1 symbol? 

https://raw.githubusercontent.com/soumith/convnet-benchmarks/master/mxnet/gnetv1.py

**Comment by sxjscience** [comment]
@zhenlinluo Could you help verify if it works after applying the changes described in https://github.com/dmlc/mxnet/pull/3392 and use `pooling_convention='full'` for all the pooling layers?

**Comment by zhenlinluo** [comment]
No, it still does not work. The same error

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
