### ISSUE TITLE
can it possible run loop in mxnet?

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#3459]
I'd like to write loop code to tuning dnn parameters ,in case that to avoid loading large data everytime.The code as below

![qq 20161006104232](https://cloud.githubusercontent.com/assets/5533901/19138782/c7ff45d2-8bb1-11e6-9b7a-232a9a6c883c.png)

And I found when the first loop finished,it will be hunt after starting to the second loop.
![qq 20161006104541](https://cloud.githubusercontent.com/assets/5533901/19138838/27b8e10e-8bb2-11e6-83ba-343b3a9a87ba.png)
Can't it possbile to run loop in python code?

the command as below
launch.py -H hosts2 -n2 -s1 python train.py --kv-store dist_sync --train-dir=$train_path --val-dir=$val_path --save-model -prefix=model/dnn --batch-size=800 --num-epochs=100 --gpu=0,1,2,3 --momentum=0.8 --num-examples=$train_examples --lr-factor=0.4
@piiswrong

**Comment by tornadomeet** [comment]
@liumilan what's you want is to try different `lr`? this code should be run ok, but the second loop result model will override previous i think.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
