### ISSUE TITLE
Why "x+y" in python will call SimpleBinaryOperator but not ElementWiseSum

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#3461]
Hi, if write "x + y" for resnet, I found that it will call to SimpleBinaryOperator but not ElementWiseSum. Anyone know where is this being defined and how to change?

**Comment by piiswrong** [comment]
Elementwisesum must be called explicitly

**Comment by zhenlinluo** [comment]
For resnet, can I change sum_sym= sym+conv3 in ResModule in deepmark/resnet.py  into sum_sym=mx.sym.ElementWiseSum(conv3, sym, num_args=2)? Once I changed, it seems work fine. But I don't know if there have any problem or limitation? What I need to test to make sure it works correctly? If working, should I submit patch to change it in example/imageclassification/symbol_resnet*.py?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
