### ISSUE TITLE
R CMD INSTALL mxnet_0.7.tar.gz cannot run successfully

### ISSUE THREAD

**Issue by joebling** [apache/incubator-mxnet#3462]
R CMD INSTALL mxnet_0.7.tar.gz 

it returns in the tail: 

*\* R
*\* demo
*\* inst
*\* preparing package for lazy loading
*\* help
**\* installing help indices
*\* building package indices
*\* installing vignettes
*\* testing if installed package can be loaded

then it stops for a long time.

Is it downloading something when testing?

But when I require(mxnet) in another R terminal,  it returns back:

> library(mxnet)

 **\* caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: .Call(Module__functions_names, xp)
 2: Module(module, mustStart = TRUE, where = env)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 7: loadModule("mxnet", TRUE)
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(package, lib.loc)
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
19: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
20: library(mxnet)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

clearly, mxnet has not been installed successfully
How can I fix this problem?

BTW, i have installed python-version .

**Comment by thirdwing** [comment]
Please show your system information.

**Comment by joebling** [comment]
Ubuntu 16.04.1 
NVIDIA Corporation GM107M [GeForce GTX 960M]


And i reinstall mxnet, but still it came out the similar problem, even worse.

* installing to library ‘/home/joebling/R/x86_64-pc-linux-gnu-library/3.2’
* installing *source* package ‘mxnet’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c executor.cc -o executor.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c export.cc -o export.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c io.cc -o io.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c kvstore.cc -o kvstore.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c mxnet.cc -o mxnet.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ndarray.cc -o ndarray.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include  -I"/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c symbol.cc -o symbol.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o mxnet.so executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o -llapack -lblas -L/usr/lib/R/lib -lR
installing to /home/joebling/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** stack smashing detected ***: /usr/lib/R/bin/exec/R terminated
Aborted (core dumped)
ERROR: loading failed
* removing ‘/home/joebling/R/x86_64-pc-linux-gnu-library/3.2/mxnet’

**Comment by thirdwing** [comment]
Please show your R `sessioninfo()` and gcc version.

**Comment by joebling** [comment]
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C   

gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hoaphumanoid** [comment]
Have you changed the gcc version? Ubuntu 16.04 should come with gcc5. One possible path (not easy) is to upgrade to the last ubuntu 16.04.2, it will come with gcc5, then try again. If you are using CUDA 8 you need a patch for the new gcc. Chech this [tutorial](https://blogs.technet.microsoft.com/machinelearning/2016/09/15/building-deep-neural-networks-in-the-cloud-with-azure-gpu-vms-mxnet-and-microsoft-r-server/) for more info.

**Comment by thirdwing** [comment]
@joebling I have to say I have no idea why you met `stack smashing`.

My best guess is the mismatch between lib and compiler.

**Comment by thirdwing** [comment]
I am closing this since it has been inactive for a while. Feel free to reopen if necessary.
