### ISSUE TITLE
The predict function in 'base_module.py' of the new interface module some wrong?

### ISSUE THREAD

**Issue by ZiJianZhao** [apache/incubator-mxnet#3465]
I train a model using the new interface 'module':

``` Python
batch_size = 100
train_iter = mx.io.NDArrayIter(X_train, Y_train, batch_size = batch_size)
test_iter = mx.io.NDArrayIter(X_test, Y_test, batch_size = batch_size)
model = mx.module.Module(
    context = mx.gpu(0),
    symbol = mlp)
model.fit(
    train_data = train_iter,
    eval_data = test_iter,
    optimizer_params={'learning_rate':0.1, 'momentum': 0.9, 'wd': 0.00001},
    num_epoch=10,
    batch_end_callback = mx.callback.Speedometer(batch_size, 200))
```

When I want to predict some data using this model:

``` Python
tIter = mx.io.NDArrayIter(X_test, batch_size = 100)
print 'Result:', model.predict(tIter)
```

Here, if the batch_size is smaller than 100, then it will output the following error:

> MXNetError: [20:14:41] include/mxnet/ndarray.h:244: Check failed: (shape_[0]) >= (end) Slice end index out of range 

But it will be all right if the batch_size is not smaller than 100. Why?

**Comment by piiswrong** [comment]
Is this the same model you used for training? Did you reload it did you use the training model directly for testing?
If it's the same model you can only use the trianing data's batch_size

**Comment by ZiJianZhao** [comment]
Then, if I want to predict a single example, what should I do?

**Comment by piiswrong** [comment]
create  a new module or re-bind

**Comment by ZiJianZhao** [comment]
Thanks for your reply. I try the following code:
```Python
t_iter = mx.io.NDArrayIter(X_test[0:1], batch_size = 1)
model.bind(data_shapes = t_iter.provide_data, force_rebind=True)
print model.predict(t_iter).asnumpy()[0].argmax()
```
But the predicted result seems to go wrong every time. I've tried some examples and they are all wrong. 
So what do you think  the problem is?

**Comment by shuokay** [comment]
If you bind manually, make sure your net input match the data_shapes. In your case, make sure `t_iter.provide_data` is all the shape you should provide manually.

**Comment by shuokay** [comment]
Also you can reload your model,  convert your data to `numpy.array` format and feed it you `predict()`, the mxnet will take care of the shapes problems.
Refer to https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L599

**Comment by ZiJianZhao** [comment]
OK. Thanks for your reply. I will have a try.
