### ISSUE TITLE
How to set constraints for the arguments

### ISSUE THREAD

**Issue by taoari** [apache/incubator-mxnet#3466]
How can I set constraints for the parameter updating, for example, restricting the gamma parameters of PReLU within range [0,1]? Is it possible to do this within existing MXNet framework?

**Comment by piiswrong** [comment]
you can try modifying the operator or optimizer

**Comment by taoari** [comment]
@piiswrong Thank you. On the operator side, I add the clipping code in the Forward() function, but it seems that the clipped gamma is not synced on the kvstore. I will try to do this on the optimizer side.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
