### ISSUE TITLE
[PERF] Call for NN Layer Kernel Improvement

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#3487]
The current NN Layers are implemented with mshadow and have performance issues.
They should be replaced with optimized cpu and gpu kernels. These should be easy to adapt from caffe or torch's kernels.
Ideally we also want support for different layout (NCHW and NHWC, optionally CHWN).

Here is the inital list of layers:
- [ ] convolution-inl.h
- [ ] deconvolution-inl.h
- [ ] batch_norm-inl.h
- [ ] pooling-inl.h
- [ ] lrn-inl.h

**Comment by xmchen1987** [comment]
@piiswrong currently in mshadow, it use unified high level API to support CPU & GPU. so on the new design, shall we keep this style, or non-unified design is also OK?

**Comment by piiswrong** [comment]
No. mshadow was used to make it easier to write simple kernels for both gpu and cpu.
For these heavy ops we need hand tune cpu and gpu code separately anyway so there is no point using it.
These should be done in roi_pooling-inl.h's style

**Comment by xmchen1987** [comment]
so these implements will take as a default implements, but not fastest ones like MKL or cuDNN, right?

I think i can have a look at the cpu side.

**Comment by piiswrong** [comment]
Yes. Thanks a lot!
