### ISSUE TITLE
Something wrong with CUDA driver version and CUDA runtime

### ISSUE THREAD

**Issue by Leaflowave** [apache/incubator-mxnet#3499]
There's an exception which someone reported several days ago.
I try to train a model with gpu, it crashes and throws an exception saying  
 **raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:34:49] src/storage/storage.cc:48: Check failed: e == cudaSuccess || e ==    cudaErrorCudartUnloading CUDA: CUDA driver version is insufficient for CUDA runtime version**
with centos 7.0,cuda-8.0,Driver Version: 361.77.   

  2 days ago ,I fixed this problem.But it's appear again when  changing the cuda toolkit to cuda-7.5. 
Making matters even worse,attempt to recovering the toolkit to cuda-8.0 is useless.I  have no idea what happend.

**Comment by TigerBass** [comment]
Caffe works just fine and cuda/samples ./deviceQuery ./bandwidthTest return pass.

**Comment by hoaphumanoid** [comment]
Have you installed the patch of version 8: `cuda_8.0.27.1_linux.run`?

**Comment by shuokay** [comment]
If you are using a tesla P100 GPU, you should upgrade the driver to R361.93, refer to https://developer.nvidia.com/cuda-downloads
>Install the R361.93 driver to complete installation of CUDA 8

**Comment by TigerBass** [comment]
Sorry,but we have given up this problem.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
