### ISSUE TITLE
Can I train the faster_RCNN with multi-GPU with multi-machine 

### ISSUE THREAD

**Issue by samuel1208** [apache/incubator-mxnet#3517]
I found faster RCNN is supported in mxnet.  Can I train it on multi-GPU with multi-machine ?

**Comment by tornadomeet** [comment]
yes, you can. i used it training with multi-gpus, but not test on multi-machine.

**Comment by niluanwudidadi** [comment]
I just use python train_end2end.py --gpu 0,1,2,3 ,but the cost time more than use 2 gpu,I don't know the reason,should I change some paramrter? @tornadomeet

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
