### ISSUE TITLE
Support for single-machine multi-process KVStore based on Shared-Memory

### ISSUE THREAD

**Issue by peterzcc** [apache/incubator-mxnet#3518]
I have been trying to implement the [A3C algorithm](https://arxiv.org/abs/1602.01783). However, I have found that it is impossible to create an ndarray that is shared among different processes.

Howevery, sharing a ndarray object between different processes could be very useful since the multi-threading module on Python is so limited due to GIL. 

As far as I know, the Chainer framework supports this feature and here is an [example](https://github.com/muupan/async-rl) 

May I ask if MXNet support similar features or anyone has been working on it?

Thanks!

**Comment by piiswrong** [comment]
There is generally no need to use multi processing with mxnet if you are smart about where to sync. Everything is automatically parallelized by the engine.
If you have to use multi processing, use distributed kvstore. I think you can have multiple workers on the same machine. @mli

**Comment by peterzcc** [comment]
@piiswrong 

Thanks a lot for your reply! I understand your idea,  MXNet is truly good at asynchronous computation.

However, my case is to develop the ["Asynchronous Method for Deep Reinforcement Learning"(A3C) algorithm](https://arxiv.org/abs/1602.01783). 

It is **multi-processor computing on a single machine with centralized neural network parameters**, which usually involves more than 16 parallel actor-learners. 

Multi-threading is not feasible, partly because the RL environements are not thread-safe. 

Distributed KVStore is also not optimal because it will introduce too much overhead caused by network communication.

Numpy has an API that allows as to create an array from a existing memory buffer, which enables multiprocessing.

I would be willing to develop such functionality for KVStore that supports efficient single-machine, multi-process communication based on shared memory, given that it's not supported yet.

Thanks!

Peter

**Comment by piiswrong** [comment]
Try dist kv and see. I think connecting to 127.0.0.1 should be fast enough

**Comment by mli** [comment]
you can set `export DMLC_LOCAL=1` to use the `ipc` protocol for communication.

**Comment by Vogen** [comment]
How your A3C implementation goes?   @peterzcc

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
