### ISSUE TITLE
i want to know how to speed up when i use gpu mode to predict

### ISSUE THREAD

**Issue by AihahaFox** [apache/incubator-mxnet#3525]
i want to know how to speed up when i use gpu mode to predict, we cost a lot when we use gpu to wait for gpu preparition

**Comment by shuokay** [comment]
Bind the symbol and shape yourself and run forward manually may help. 
The `mxnet.model.FeedForward.predict()` init the executor by calling `simple_bind()` every time you call it. If you make online predictions, you only need to call simple_bind one time and feed the inputs to the executor in sequence.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
