### ISSUE TITLE
Improvement in set up and installation guide

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#3528]
We can improve set up and installation guide to make it more easier, smoother and faster for users to install mxnet. https://mxnet.readthedocs.io/en/latest/how_to/build.html

**TODOs**
- Have a separate install chapter under getting started.
- Have quick installation script for common installation requirement. 
  - Example: MXNet for Python on Ubuntu/RHEL/Amazon Linux/Mac OS for CPU only.
    This would cover 80% of our user base and get them started and running initial examples of mxnet in minutes.
- We need more re-structuring of contents. OS wise, set up wise like pre-built binary or build from source etc.
- Language proof read and improve content quality.
- Move set up issues to "Common Problems" section in this guide.

**Comment by sandeep-krishnamurthy** [comment]
I have started working on this.

**Comment by sandeep-krishnamurthy** [comment]
Complete
1. Separate install chapter
2. Re-structuring of content
3. Language proof read and improving content quality
4. Move set up issues to "Common Problems" section.

In Progress
1. Quick installation script

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
