### ISSUE TITLE
Bash scripts for easy installation of MXNet

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#3537]
It would be very help full if we can provide a bash script that users can run and get all dependencies and mxnet installed and ready to use.

With this, we will have high conversion rate from people seeing getting_started page and actually getting_started.

To start with, we can cover common OS and simple installation mechanism. But this would cover maximum customer base.

At minimum following flavors should be covered.
1. Ubuntu + MXNet for Python (CPU Only)
2. Amazon Linux (RHEL) + MXNet for Python (CPU Only)
3. Mac OS + MXNet for Python (CPU Only)

Following this, we can cover script based installation for R, Scala, Julia. Then, GPU based MXNet installation.

@pluskid @piiswrong @mli : Where do you think these scripts reside? Another separate repo (dmlc/mxnet/ezinstall)? or a folder within this repo, say "utilities"?

**Comment by sandeep-krishnamurthy** [comment]
Started working on installation bash script for Amazon Linux (RHEL) and Ubuntu.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
