### ISSUE TITLE
Can it affect the accurary if skip the code in model.py

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#3544]
I'd like to skip the train metric in model.py because it cost too much time during trainning.
And can it possible to affect the program result ?
 # evaluate at end, so we can lazy copy
 #executor_manager.update_metric(eval_metric, data_batch.label)

**Comment by piiswrong** [comment]
it apears to be costing time because it's a sync point. Metric shouldn't take much time to compute unless you have 10k+ classes

**Comment by liumilan** [comment]
i have 3 metric ,and it take as 3 times as skip the code.
And i have one question,if i skipped executor_manager.update_metric(eval_metric, data_batch.label) this code,will it affect the whole trainning,final result?
@piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
