### ISSUE TITLE
ubuntu mxnet install issue

### ISSUE THREAD

**Issue by smbatchou** [apache/incubator-mxnet#3549]
Hi I have been trying to install mxnet_0.0.7.targ.gz For and R-client on ubuntu 16.04; but the following error message is returned
installing to /home/stef/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs
*\* R
*\* demo
*\* inst
*\* preparing package for lazy loading
*\* help
**\* installing help indices
*\* building package indices
*\* installing vignettes
*\* testing if installed package can be loaded
**\* Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x0000000003e0f488 ***

Thanks

**Comment by RogerBorras** [comment]
I have problems in ubuntu 16.04 too. It is possible to provide an easy installation like in windows?

**Comment by thirdwing** [comment]
Can you provide more info, including your os, compiler version, R version, Rcpp version, cuda version?

**Comment by smbatchou** [comment]
Hi,
R version: 3.3.1 (Bug in your hair)
Rcpp: 0.12.7
gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
cuda : version (8.0.44-1)

**Comment by thirdwing** [comment]
Have you compiled and built mxnet lib successfully? You just failed in building R package?

I met some issues with gcc 5.4 in this summer.

**Comment by skrish13** [comment]
@RogerBorras you just have to run the bash file, "install-mxnet-ubuntu-r.sh". What exactly did you try?

**Comment by thirdwing** [comment]
I am closing this since it has been inactive. Feel free to reopen if necessary.
