### ISSUE TITLE
mxnet conv only support zero padding?

### ISSUE THREAD

**Issue by xlvector** [apache/incubator-mxnet#3556]
I find in torch, there are different types of padding like 

SpatialReflectionPadding
SpatialReplicationPadding

In mxnet, are there similar padding methods?

**Comment by piiswrong** [comment]
No. Does cudnn support these?

**Comment by sbodenstein** [comment]
@xlvector @piiswrong: Torch and TensorFlow have standalone padding layers that support reflective padding etc and padding that isn't applied to all sides. This has many uses, particularly for the likes of style transfer where zero padding is more likely to introduce edge artifacts. It obviously comes at a greater memory cost (as its not merged as part of pooling/convolution), but sometimes you would rather have more control.

I'm thinking of adding a mx.pad layer based on [tf.pad](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#pad). Let me know if you have thoughts on this layer, otherwise will just make a PR in the next few days.

**Comment by piiswrong** [comment]
@sbodenstein Sounds good! Thanks.
Lets try to be consistent with the other packages

**Comment by xlvector** [comment]
@sbodenstein Thanks very much!

**Comment by sbodenstein** [comment]
@piiswrong, @xlvector: its actually a larger project than I thought at first to write an efficient pad layer for n-dimensional tensors (and won't have time to do it).

The cases of interest are almost always for images (in which case only two of the four dimensions are padded), so I propose a layer `mx.image_pad`. This takes a tensor `(n, c, h, w)`, and parameters:

* `mode`: padding mode, can be "constant" (pad with 0), "reflect", "replicate" (same as Torch)
* `padding`: a matrix {{pad_h_up, pad_h_down}, {pad_w_left, pad_w_right}}

In the future, a layer `mx.pad` could be written that deals with the general case (and will require a more verbose syntax for the common image case).

What are your thoughts?

**Comment by piiswrong** [comment]
Let's stick with mx.pad and make the interface support general padding. Then you can check if you actually only need to pad the last 2 dims and fail if otherwise

**Comment by sbodenstein** [comment]
@piiswrong: ok. One more thing: can arguments to mxnet symbols be tuples of tuples? If not, will just use a single tuple to represent padding.

**Comment by piiswrong** [comment]
No. Only support tuple of unsigned. You can add support to your own type by writing parsers though

**Comment by sbodenstein** [comment]
Would you recommend that I just use a tuple of unsigned for the padding? Or add a parser? (if so, in which file are parsers defined?)

**Comment by piiswrong** [comment]
Please use tuple if it's enough. just to be consistent

**Comment by sbodenstein** [comment]
@piiswrong: I'm having some difficulties. I need to use atomicAdd, but it doesn't work for double + half. I can easily overload the double case, but having difficulties with the half case. 

Is it better just to avoid using DType, and use floats instead?

**Comment by piiswrong** [comment]
You can use DType but only instantiate for float and double when creating
layers

**Comment by erikbeall** [comment]
@sbodenstein: did you make any further progress on adding reflect and replicate to padding? I'd like to help if that would be useful.

**Comment by sbodenstein** [comment]
I haven't added reflection padding. Replicate is working working on the dims supported. If you would like to help, there are two projects:
* Currently, only padding for 2d + 3d images is supported (when images are represented as [c,h,w] format). It is good having a fast code path for these, but it would be nice to support padding for arbitrary tensor shapes (like tensorflow supports)
* add reflection padding support

**Comment by erikbeall** [comment]
@sbodenstein: so replicate is working, that is wonderful wonderful :) I'd like to help with adding reflection padding support first. Please let me know where your replicate code is, and I can work on implementing reflection in a consistent way, test/compare with tensorflow. Are you working from https://github.com/sbodenstein/mxnet/tree/master/src/operator?

**Comment by sbodenstein** [comment]
@erikbeall: apologies for not getting back to you earlier, lost track! 

Have you made any more progress implementing reflection padding? I need support for this as well now, so I can add it if you haven't done too much work on this yet.

**Comment by matteosal** [comment]
@erikbeall 
I am currently implementing reflection padding. I should be making a PR soon (no more than a few days).

**Comment by matteosal** [comment]
https://github.com/dmlc/mxnet/pull/6123

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
