### ISSUE TITLE
Code freezing with joblib

### ISSUE THREAD

**Issue by jmschrei** [apache/incubator-mxnet#3570]
I'm trying to parallelize predictions using joblib and noticing that the code will freeze when I try to use the `predict` method in parallel. This was reported in joblib a while ago (https://github.com/joblib/joblib/issues/125) and they said that the issue was with MKL and that making the number of threads equal to 1 would solve the problem. I'm using atlas-sse3 and tried setting atlas threads to 1 (ATL_NTHREADS) but it isn't working for me. I was wondering if there could be an issue in mxnet explaining this? I tried setting MXNET_GPU_WORKER_NTHREADS to 1, MXNET_CPU_PRIORITY_NTHREADS to 1, and MXNET_ENGINE_TYPE to 'NaiveEngine'.

**Comment by piiswrong** [comment]
why do you need joblib? mxnet engine already does multi threading for you

**Comment by jmschrei** [comment]
Does mxnet parallelize prediction using a fitted model across multiple GPUs?

**Comment by piiswrong** [comment]
mx.mod.Module does. mx.model is deprecated and doesn't. It should be easy to switch

**Comment by jmschrei** [comment]
Oh, great. Can you point me to an example or some documentation on how to do this with Module? I'm not seeing anything in the module examples folder.

**Comment by piiswrong** [comment]
examples/module/train_cifar10.py

**Comment by zihaolucky** [comment]
@jmschrei Did you successfully solve this problem and could you provide more details? Do you use python or some other languages in deployment?

**Comment by zihaolucky** [comment]
Hi @piiswrong 

I got similar problem and changed my old `mx.model.FeedForward` to `mx.mod.Module` in training, should I change to Module api in Scala in serving as I train in Python? Cause Scala-pkg doesn't support Module api yet.

**Comment by jmschrei** [comment]
I did not find a solution to this other than using `NaiveEngine` to make predictions. I'm imagining that this is because too many threads are being called and cause the entire thing to get flummoxed. Using `Module` was in fact much slower than parallelizing it using `NaiveEngine` and joblib.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
