### ISSUE TITLE
convert caffe model failed

### ISSUE THREAD

**Issue by damNull** [apache/incubator-mxnet#3586]
the newest caffe has changed their data format
in tools/caffe_converter/convert_symbol.py
the code
`if len(proto.input_dim) > 0:
        input_dim = proto.input_dim
    elif len(proto.input_shape) > 0: 
        input_dim = proto.input_shape[0].dim`
is not suitable yet

for example, in older version of caffe alexnet model
`name: "AlexNet"
input: "data"
input_shape {
  dim: 10
  dim: 3
  dim: 227
  dim: 227
}`
now changed to
`name: "AlexNet"
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 10 dim: 3 dim: 227 dim: 227 } }
}`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
