### ISSUE TITLE
How to set the mxnet environment variable？

### ISSUE THREAD

**Issue by meanmee** [apache/incubator-mxnet#3600]
Since the official Docs just show the types of the Environment Variable, It dosen't tell us how to set!

**Comment by shuokay** [comment]
This is a Linux question. Set it from command line.
for example:
```bash
export MXNET_ENGINE_TYPE=NaiveEngine
```

**Comment by meanmee** [comment]
It doesn't work for me, Maybe there are too many user count in my machine, I do forget which one I used to install Mxnet...

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
