### ISSUE TITLE
Could not open readthedocs documents.

### ISSUE THREAD

**Issue by DCYN** [apache/incubator-mxnet#3609]
Could not open below linkage provided by cifar10-recipe.ipynb for Image RecordIO Iterator. 

https://mxnet.readthedocs.io/en/latest/python/io.html

Seems that I also could not open all the MXNET document on the readthedocs.io, such as the documents about using symbol. Would you please help? Thanks.

**Comment by tornadomeet** [comment]
all documents is now in http://mxnet.io/, so the doc your want is in http://mxnet.io/api/python/io.html

**Comment by DCYN** [comment]
Many thanks!

**Comment by tornadomeet** [comment]
http://mxnet.io/api/python/io.html#how-to-get-data

**Comment by DCYN** [comment]
Many thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
