### ISSUE TITLE
How can I use Xavier to initial parameters while not using model.FeedForward

### ISSUE THREAD

**Issue by dx80232** [apache/incubator-mxnet#3610]
Now I want to train CIFAR-10, and I use simple_bind to do it because I want to add some operations more flexibly.
However, currently I can only get about 48% validation error, which is not good at all.
I guess the problem might be using random initialization without carefully chosen.
The below is my initialization.

`for r in exec.arg_arrays:`
`r[:] = np.random.randn(*r.shape)`

So how can I apply Xavier to better initialize in this situation?
Thanks

**Comment by shuokay** [comment]
Now that you can get the `shape`, you can define Xavier initialization easily. What Xavier matters is the number of input and output neurons.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
