### ISSUE TITLE
How to use the parameters in im2rec.py?

### ISSUE THREAD

**Issue by sunshineInmoon** [apache/incubator-mxnet#3622]
I have some problems when I use the "--exts" in parametes of im2rec.py.
It's right if I use the default value,but It's error if I use it like --exts=['.jpg','.jpeg'].
Why?

**Comment by sunshineInmoon** [comment]
I have find reason from im2rec.py.
cgroup.add_argument('--exts', type=list,default=['.jpeg', '.jpg'],
                        help='list of acceptable image extensions.')
change to
cgroup.add_argument('--exts', type=list, action='append',default=['.jpeg', '.jpg'],
                        help='list of acceptable image extensions.')
OK!

modified im2rec.py
https://github.com/sunshineInmoon/mxnet/blob/master/tools/im2rec.py

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
