### ISSUE TITLE
Could not set FactorSchedule

### ISSUE THREAD

**Issue by DCYN** [apache/incubator-mxnet#3624]
When I tried to set a factor schedule in cifar10-recipe ipynb, I got below error message. Would you please help? Thanks.

AttributeError                            Traceback (most recent call last)
<ipython-input-10-01000f16f948> in <module>()
      9 model = mx.model.FeedForward(ctx=mx.gpu(), symbol=softmax, num_epoch=num_epoch,
     10                               learning_rate=0.00003, momentum=0.9, wd=0.00001,
---> 11                               lr_scheduler=mx.misc.FactorScheduler(2))
     12 # In this example. learning rate will be reduced to 0.1 \* previous learning rate for every 2 epochs

AttributeError: 'module' object has no attribute 'misc'

**Comment by piiswrong** [comment]
change misc to lr_scheduler

**Comment by DCYN** [comment]
Many thanks! It works when I use lr_scheduler=mx.lr_scheduler.FactorScheduler(a,b)

**Comment by piiswrong** [comment]
@DCYN We have a lot of examples over time and some of them are outdated. You are more than welcome to contribute fixes for outdated examples.

**Comment by DCYN** [comment]
Many thanks. Let me try to contribute something after mastering it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
