### ISSUE TITLE
I have a question about the startup speed of the mxnet

### ISSUE THREAD

**Issue by AihahaFox** [apache/incubator-mxnet#3628]
I test 4 desktops with the same project as follow:
1. gtx 1080, cuda 8.0, cudnn v5 A
2. gtx 960, cuda 7.5, cudnn v5 B
3. gtx 750ti, cuda 7.5, cudnn v4 C
4. gtx 750ti, cuda 7.5, cudnn v4 D
time cost by the prepared stage is different.
for A, 37s
for B, 2s
for C, 3s
for D, 80s

is there any dependency can influence this?

**Comment by piiswrong** [comment]
Does it still cost more time when you run it for the second time?

**Comment by antinucleon** [comment]
One potential reason is PTX assemble runtime compile. You may try to change NVCCFLAGS, add -gencode option to generate special code for special hardware arch.

**Comment by AihahaFox** [comment]
@piiswrong, yeah, everytime

**Comment by piiswrong** [comment]
are you linking with opencv?
sometimes it's caused by gpu enabled opencv.
also try reboot

**Comment by AihahaFox** [comment]
OK, I will try it, thank you

**Comment by AihahaFox** [comment]
@piiswrong not link with opencv may not help

**Comment by AihahaFox** [comment]
@piiswrong , you are right, I have solve the problem, it is because I compile opencv with cuda. Thanks a lot!!

**Comment by eldercrow** [comment]
Seems like the issue's already solved, but in my case using naive GPU memory allocation as mentioned in  #2981 solved the problem.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
