### ISSUE TITLE
one problem occurred when trainning  fcn-xs,the log as follows.I have no idea what happend,and I just did it according to readme. how to fix it, would someone like to help me out,thanks so much.

### ISSUE THREAD

**Issue by zhenzhen1022** [apache/incubator-mxnet#3634]
dl@dl:~/mxnet/example/fcn-xs$ ./run_fcnxs.sh
INFO:root:Namespace(epoch=74, init_type='vgg16', model='fcn32s', prefix='VGG_FC_ILSVRC_16_layers', retrain=False)
/home/dl/mxnet/example/fcn-xs/data.py:79: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = img[:, rand_start : rand_start + min_hw]
/home/dl/mxnet/example/fcn-xs/data.py:80: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  label = label[:, rand_start : rand_start + min_hw]
INFO:root:Start training with gpu(0)
[13:04:12] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [13:04:12] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
[13:04:12] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [13:04:12] src/engine/./threaded_engine.h:306: [13:04:12] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [13:04:12] src/engine/./threaded_engine.h:306: [13:04:12] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
./run_fcnxs.sh: line 3:  5298 Aborted                 (core dumped) python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16

**Comment by zhenzhen1022** [comment]
now I can locate the problem,"" pred = mx.nd.array(output_buff["softmax_output"].asnumpy().reshape(pred_shape[0], \
                    pred_shape[1], pred_shape[2]*pred_shape[3]))"" in solver.py. Is there anyone have the same problem, I need help!

**Comment by tornadomeet** [comment]
@zhenzhen1022 i'll check it this week.

**Comment by tornadomeet** [comment]
@zhenzhen1022 https://github.com/dmlc/mxnet/pull/3654

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
