### ISSUE TITLE
mxnet-scala2.11

### ISSUE THREAD

**Issue by shell4j** [apache/incubator-mxnet#3637]
hi! I'm using scala 2.11 in my project, and , i want to know is your mxnet suitable for my project ?

**Comment by javelinjs** [comment]
Yes, the scala-package is now using scala 2.11.

**Comment by ctongfei** [comment]
If it is possible, please push a scala_2.11 jar to the maven central repository. Thanks!

**Comment by javelinjs** [comment]
I'll do it this weekend.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
