### ISSUE TITLE
is there anyone trianed fcn-xs successed? why I failed with an error.

### ISSUE THREAD

**Issue by zhenzhen1022** [apache/incubator-mxnet#3638]
INFO:root:Namespace(epoch=74, init_type='vgg16', model='fcn32s', prefix='VGG_FC_ILSVRC_16_layers', retrain=False)
INFO:root:Start training with gpu(0)
[16:40:25] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
[16:40:25] /home/dl/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:40:25] src/engine/./threaded_engine.h:306: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:40:25] src/engine/./threaded_engine.h:306: [16:40:25] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
./run_fcnxs.sh: line 3: 13455 Aborted                 (core dumped) python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16

**Comment by tornadomeet** [comment]
@zhenzhen1022  i'll check it this week.

**Comment by bertjiazheng** [comment]
Same error.

**Comment by tornadomeet** [comment]
@zhenzhen1022 @bertjiazheng https://github.com/dmlc/mxnet/pull/3654

**Comment by zhenzhen1022** [comment]
@tornadomeet thx for your help. I update the files and there are two problem: 1. when I set cutoff_cut_off_size = 400, the log is "/home/dl/mxnet/example/fcn-xs/data.py:80: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future img = img[rand_start_min : rand_start_min + self.cut_off_size, rand_start_max : rand_start_max + self.cut_off_size]
/home/dl/mxnet/example/fcn-xs/data.py:72: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  label = label[rand_start_min : rand_start_min + self.cut_off_size, rand_start_max : rand_start_max + self.cut_off_size] ";
2. cudaMalloc failed: out of memory, the specific log is: "[19:14:22] /home/dl/mxnet/dmlc-core/include/dmlc/./logging.h:235: [19:14:22] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
Traceback (most recent call last):
  File "fcn_xs.py", line 73, in <module>
    main()
  File "fcn_xs.py", line 57, in main
    epoch_end_callback  = mx.callback.do_checkpoint(fcnxs_model_prefix))
  File "/home/dl/mxnet/example/fcn-xs/solver.py", line 75, in fit
    aux_states=self.aux_params)
  File "/home/dl/mxnet/example/fcn-xs/mxnet/symbol.py", line 844, in bind
    ctypes.byref(handle)))
  File "/home/dl/mxnet/example/fcn-xs/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:14:22] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory"
For the second problem, I wonder if my GPU memory(GTX1070 with 8G memory) is not enough for this training or not. Looking forward your reply. Thx!

**Comment by tornadomeet** [comment]
fcn-xs need large gpu memory. try cut-off smaller.

**Comment by zhenzhen1022** [comment]
yes, when set cut-off, here is the first problem.
/home/dl/mxnet/example/fcn-xs/data.py:71: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = img[rand_start_min : rand_start_min + self.cut_off_size, rand_start_max : rand_start_max + self.cut_off_size]
/home/dl/mxnet/example/fcn-xs/data.py:72: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  label = label[rand_start_min : rand_start_min + self.cut_off_size, rand_start_max : rand_start_max + self.cut_off_size]
the log is above,by the way, it didn't break off the training.

**Comment by zhenzhen1022** [comment]
@tornadomeet now I set cutoff=200, and when save the params of the first epoch, the cuda also out of memory. does it means I cannot train fcn-xs with 8G GPU memory? the log is following.
INFO:root:Saved checkpoint to "model_pascal/FCN32s_VGG16-0001.params"
INFO:root:                     --->Epoch[0] Train-accuracy=0.750734
INFO:root: in eval process...
[20:40:42] /home/dl/mxnet/dmlc-core/include/dmlc/./logging.h:235: [20:40:42] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
Traceback (most recent call last):
  File "fcn_xs.py", line 73, in <module>
    main()
  File "fcn_xs.py", line 57, in main
    epoch_end_callback  = mx.callback.do_checkpoint(fcnxs_model_prefix))
  File "/home/dl/mxnet/example/fcn-xs/solver.py", line 120, in fit
    aux_states=self.aux_params)
  File "/home/dl/mxnet/example/fcn-xs/mxnet/symbol.py", line 844, in bind
    ctypes.byref(handle)))
  File "/home/dl/mxnet/example/fcn-xs/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:40:42] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory

**Comment by zhenzhen1022** [comment]
@tornadomeet which kind of GPU did you use?

**Comment by tornadomeet** [comment]
i think 8g is ok when using smaller cutoff. this maybe some other bug,i will look it next week when i have time.

**Comment by zhenzhen1022** [comment]
@tornadomeet That is so great if you can take a look of this problem. maybe you can check the log firstly:
/home/dl/mxnet/example/fcn-xs/data.py:68: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = img[rand_start_max : rand_start_max + self.cut_off_size, rand_start_min : rand_start_min + self.cut_off_size]
By the way, is there any requirement for the version of python.Is python 2.7.6 ok? thx so much!

**Comment by zhenzhen1022** [comment]
@tornadomeet hi，it's very embarrass to brother you, but I am very interest on fcn method and mxnet, so I wonder when you will take a look at this problem?

**Comment by tornadomeet** [comment]
@zhenzhen1022 you can use `pdb` to debug it and use `nvidia-smi` to see the memory(at saving moment) usage first.

**Comment by zhenzhen1022** [comment]
@tornadomeet hi,yes, I have seen  the memory of GPU at saving moment, the usage is 7543 MiB(about 7.4G). So what should I do now? maybe I need to create a simple symbol. but I wonder how to solve the data when data and labels are images? if I use your data.py what I can do to solve the arg_params and aux_params that you loaded from VGG and initialize the model?

**Comment by tornadomeet** [comment]
you can use https://github.com/dmlc/mxnet-memonger to save memory, an example is https://github.com/tornadomeet/ResNet#training-resnet-200-by-only-one-gpu-with-dark-knowledge-of-mxnet  you can read the code about ```--memonger```

**Comment by zhenzhen1022** [comment]
@tornadomeet  today I tried this approach, I downloaded memonger.py file and set fcnxs._set_attr(force_mirroring='True') in fcn_xs.py according to the reference. but It didn't make any  improvement of the usage of GPU memory at saving moment. Due to the limits of hardware for DL, I thought may I should create a simple network, and my problem is how to solve the two parameters ：arg_params and aux_params that you load from VGG to initialize the model? can u give me some advices, pls more specific. THX!

**Comment by tornadomeet** [comment]
@zhenzhen1022   ```fcnxs._set_attr(force_mirroring='True') ``` is not correctly, you should set it in the middle of the symbol, like in resnet, set it in every 'add'. so in fcn-xs, you may just try set mirror after every pool and score, that is pool1/pool2/pool3/pool4/pool5/score.  
another, after set_attr, you also need use ```memonger.search_plan()``` like https://github.com/tornadomeet/ResNet/blob/master/train_resnet.py#L71 Please try it(if used the right way, 8G is enough for big cut_off in fcn-xs, i think), thanks~

**Comment by zhenzhen1022** [comment]
@tornadomeet I see. can you explain more details about setting mirror in the symbol? According to  https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py#L40-47, when do I need to setting mirror? I setted mirror after every pool and score, but I got a message:
  File "fcn_xs.py", line 29, in main
    fcnxs = memonger.search_plan(fcnxs)#######1108
  File "/home/dl/mxnet/example/fcn-xs/memonger.py", line 140, in search_plan
    sym = make_mirror_plan(sym, threshold=threshold, plan_info=info, **kwargs)
  File "/home/dl/mxnet/example/fcn-xs/memonger.py", line 63, in make_mirror_plan
    shape_dict = list(zip(internals.list_outputs(), out_shapes))
TypeError: zip argument #2 must support iteration

**Comment by zhenzhen1022** [comment]
@tornadomeet use pbd to debug, I found that "internals.infer_shape(**kwargs)" returned (None None None) that means out_shapes=None. so is there anywhere I did wrong?

**Comment by tornadomeet** [comment]
because the input size of fcn-xs is also changing, you should feed data shape in ```memonger.search_plan``` at every image, so i think it should be putted it fit fun in solver.py.

**Comment by tornadomeet** [comment]
if still have problem, then this weekend i'll try add it(a little busy these days, sorry)

**Comment by zhenzhen1022** [comment]
@tornadomeet it's so sorry to brother you. I so glad that you could help. thx!

**Comment by zhenzhen1022** [comment]
@tornadomeet hi, did you add mxnet-memonger to save the memory?It‘s too hard to do that for the green hand,looking for your help!

**Comment by II-Matto** [comment]
@zhenzhen1022 @tornadomeet I have tried memonger and it seems to be the solution. The training runs 8 epoches now without reporting OOM.

I do not use memonger to `search_plan` for each image. I just do it at the very beginning with a large enough input size. Specifically, I added `fcnxs = memonger.search_plan(fcnxs, data=(1, 3, 1000, 1000))` right before constructing `train_dataiter`. I will update the comment when the training is successfully done.

**Comment by II-Matto** [comment]
@tornadomeet Hi, the reported speed during my training is approximately 2.7 samples/sec. Is it normal or too slow? What is the reported speed during your training?

**Comment by II-Matto** [comment]
@zhenzhen1022 There is another possible solution at [https://github.com/dmlc/mxnet/issues/2981#issuecomment-256233058](https://github.com/dmlc/mxnet/issues/2981#issuecomment-256233058), which I haven't tried. If memonger does not resolve your problem, you can consider using `NaiveStorageManager` as described.

**Comment by II-Matto** [comment]
@tornadomeet The indent of the code seems to be incorrect. https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/image_segmentaion.py#L6-L22

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
