### ISSUE TITLE
multi-gpu support of joint training of rcnn example is broken

### ISSUE THREAD

**Issue by neodooth** [apache/incubator-mxnet#3639]
not sure if this is due to the modifications to executor_group.py in 23bf60cab87ff0e4cf02deccdbc2ca9791d9d821

the error message is
AssertionError: all data must have the same batch size: batch_size = 2, but label has shape (1, 72900)
raised from decide_slices in executor_group.py

the maximum shape is [('data', (2, 3, 1440, 1440))] [('label', (1, 72900)), ('bbox_target', (1, 36, 90, 90)), ('bbox_inside_weight', (1, 36, 90, 90)), ('bbox_outside_weight', (1, 36, 90, 90)), ('gt_boxes', (2, 500))]

**Comment by winstywang** [comment]
@precedenceguo

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
