### ISSUE TITLE
How can I shuffle the iterator and split it to several sets?

### ISSUE THREAD

**Issue by DCYN** [apache/incubator-mxnet#3642]
Is there any function to shuffle an iterator and split it into several sets? 

I want to split the Cifar training data into 3 sets, but only find a shuffle parameter in mxnet.io.ImageRecordIter. How can I split it?

Many thanks.

**Comment by shuokay** [comment]
Define a `mx.io.DataIter` class, shuffle and split data in `__init__` function

**Comment by DCYN** [comment]
Many thanks! Would you please give me further instruction? I really know a little about DataIter.

**Comment by VoVAllen** [comment]
Check mxnet/python/mxnet/io.py

You need to extend DataIter to create your own dataiter

**Comment by DCYN** [comment]
Many thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
