### ISSUE TITLE
there are no setupenv.cmd in Windows Pre-built Packages.

### ISSUE THREAD

**Issue by EGQM** [apache/incubator-mxnet#3644]
I follow the steps to install Pre-built Packages on window in http://mxnet.io/get_started/setup.html#installing-pre-built-packages-on-windows ,and find there are no setupenv.cmd in Windows Pre-built Packages in https://github.com/yajiedesign/mxnet/releases .How to install it?

**Comment by VoVAllen** [comment]
Just try python setup.py install. I believe it will work.

**Comment by EGQM** [comment]
@VoVAllen I have tried,and It did not work.failed to import mxnet:
```
Traceback (most recent call last):

  File "<ipython-input-1-30eb4f951ea5>", line 1, in <module>
    import mxnet

  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError

  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()

  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])

  File "C:\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)

  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] 找不到指定的模块。
```

**Comment by EGQM** [comment]
@yajiedesign can you give me some suggestion?

**Comment by yajiedesign** [comment]
the https://github.com/yajiedesign/mxnet/releases is upgrade package
you need to download  20160531 in https://github.com/dmlc/mxnet/releases first.

**Comment by EGQM** [comment]
@yajiedesign thank you very much!
I install 20160531_win10_x64_gpu,and test it.It works.
After I overwrite the files with Nightly Windows Release (20161029_mxnet_x64_gpu.7z) and install it again,it does not work.

**Comment by alvinjamur** [comment]
i'm struggling with thos gpu install and will try this today. i am presuming u unzipped the file and only did setupenv.cmd

u did not have to install all the other stuff right? ot is a fully comtained solution?

**Comment by EGQM** [comment]
@alvinjamur 
the solution is as follows:
(1)install 20160531_win10_x64_gpu. execute setupenv.cmd and python setup.py install.
(2)overwrite the files with new release vesion in https://github.com/yajiedesign/mxnet/releases
(3)overwrite the cudnn files with cudnn V4 

It is ok with GPU,but not CPU.

**Comment by alvinjamur** [comment]
and what about the r package?

**Comment by yuan1202** [comment]
I am also facing this issue...... now

here's the process i tool:
1. download 20160531_win10_x64_gpu
2. download vc14 base package and use it to overwrite 20160531_win10_x64_gpu
3. follow the installation process, i.e. get cuda files, run setupenv.cmd, then python install.
4. test by import mxnet and it runs fine.
5. then tried to install the lastest build which is 20170802_mxnet_x64_vc14_gpu by simply python setup.py install, didn't work
6. tried to use 20170802_mxnet_x64_vc14_gpu to overwrite the vc14 base package then install, still didn't work.
always getting the WinError 126.

@yajiedesign could you please include some clearer installation guide? "if you are first download.please download base package first" really doesn't help...

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by ali2210** [comment]
[check this for mxnet on windows ]https://www.youtube.com/watch?v=qvw-Gtv2uz8
