### ISSUE TITLE
Question on SequenceMask OP

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#3647]
http://mxnet.io/api/python/symbol.html#mxnet.symbol.SequenceMask

It said 

>  If sequence_length is false, then each example in the batch is assumed to have the max sequence length, and this operator becomes the identity operator.

First I think the sequence_length parameter here mentioned should be use_sequence_length.

Then this document means this op works only if I set use_sequence_length is true, otherwise it's just an identity OP. 
Therefore why do we need this parameter? Why it shouldn't be true by default?

**Comment by sbodenstein** [comment]
Good question: you are correct, by default, its the identity op. The reason for this strange looking design: it brings consistency with the other sequence ops (`SequenceLast` and `SequenceReverse`) which often just want to be used without specifying sequence lengths. 

Whether this is the best design is debatable. I'm honestly not sure if this was correct.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
