### ISSUE TITLE
fcn-xs on multi-gpu

### ISSUE THREAD

**Issue by animebing** [apache/incubator-mxnet#3657]
when i run the example/fcn-xs, i replace the ctx=mx.gpu(0) with ctx=[mx.gpu(0), mx.gpu(1)], there is the error message below

> Traceback (most recent call last):
>   File "fcn_xs.py", line 73, in <module>
>     main()
>   File "fcn_xs.py", line 29, in main
>     fcnxs_args, fcnxs_auxs = init_fcnxs.init_from_vgg16(ctx, fcnxs, fcnxs_args, fcnxs_auxs)
>   File "/home/bingbing/example/fcn-xs/init_fcnxs.py", line 26, in init_from_vgg16
>     fcnxs_args[k] = mx.nd.zeros(v.shape, ctx)
>   File "/usr/local/mllib/mxnet/python/mxnet/ndarray.py", line 842, in zeros
>     arr = empty(shape, ctx, dtype)
>   File "/usr/local/mllib/mxnet/python/mxnet/ndarray.py", line 578, in empty
>     return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
>   File "/usr/local/mllib/mxnet/python/mxnet/ndarray.py", line 65, in _new_alloc_handle
>     ctypes.c_int(ctx.device_typeid),
> AttributeError: 'list' object has no attribute 'device_typeid'

when i just use ctx=mx.gpu(0), it works well, i want to know whether this example just can use single-gpu

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
