### ISSUE TITLE
Some questions about Embedding Layer

### ISSUE THREAD

**Issue by allenlverson** [apache/incubator-mxnet#3659]
Questions about Embedding layer
(1) What is the function of Embedding layer ?
 In Keras ,it says Turn positive
 integers (indexes) into dense vectors of fixed size. eg. [[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]

But what is the meaning ? When will it be used ?

(2)I try some simple codes to see how the Embedding layer works:
I use the code in the xlvector blog:
http://blog.xlvector.net/2016-05/mxnet-regression-classification-for-concret-continuous-features/
# 我们虚构了201个不同的品牌，并给每个品牌设置一个出场价格

seriesdata = [1 + i for i in range(100)] + [101 - i for i in range(100)]

for i in range(10000):
    k = random.randint(0, 199)
    #越贵的品牌，我们认为在数据集里出现的次数越少，因为它卖的少
    count = 1000 / seriesdata[k]
    for j in range(count):
        dis = random.random() \* 10
        #实际的价格是品牌的出场价除以里程数的开方
        price = seriesdata[k] / math.sqrt(1.0 + dis)
        print str(price) + '\t' + str(dis) + '\t' + str(k)
# dis 是输入的里程

dis = mx.symbol.Variable('dis')
# price 是要预测的目标价格

price = mx.symbol.Variable('price')
# price_interval 是要预测的价格区间

price_interval = mx.symbol.Variable('price_interval')
# series 是输入的车的品牌

series = mx.symbol.Variable('series')

series_out = mx.symbol.Embedding(data = series, input_dim = 200,
                             output_dim = 100, name = "series_embed")
ne = mx.symbol.Flatten(series_out, name = "series_flatten")

arg , out,aux = ne.infer_shape(series=(6,1))
print arg
print ne.list_arguments()
print out

execute = ne.bind(ctx=mx.cpu(),args={'dis_flatten':seriesdata})
execute.forward()
d_out = execute.outputs[0]
print d_out.asnumpy()

IN console:
[(6L, 1L), (200L, 100L)]
['series', 'series_embed_weight']
[(6L, 100L)]
Then throw an error:
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args

I know it means that I did not give values to  the series_embed_weight . But in this example, which values to give it?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
