### ISSUE TITLE
[OP] Convention for the `axis` argument

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#3660]
See context #3198 for the OP checklist

We will strictly follow Numpy's convention for the `axis` argument in the future.
- The default behavior of negative axis is to wrap around the dimensions.
  For example, for a 4-dimensional tensor, `axis=-1` is the same as `axis=3`. 
- For OPs that perform reduction, like [sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html), [max](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html#numpy.ndarray.max), [min](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html#numpy.ndarray.min), [prod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.prod.html#numpy.prod), [norm](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html), [argmax](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html) and [argmin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html):
  The `axis` could be either empty or an integer or a tuple. We can set `axis=(0, 1, 2)` or `axis=(-1, 2)` or `axis=-1`. Empty `axis` means global reduce, which is the default behavior.
- For [split](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html), [concatenate](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html), [take](https://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html), [swapaxes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html#numpy.swapaxes):
  The `axis` should be an integer and is 0 by default.
- For [transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)
  The `axes` should be a tuple and is the reverse order of the dimensions by default.
- For [sort](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html) and [argsort](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html)
  The `axis` should be an integer and is -1 by default

### List of OPs that involves the "axis" argument:

| Name | Status | Assignee | Comments |
| --- | --- | --- | --- |
| [sum](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.cc) | p |  | does not support negative axis |
| [min](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.cc) | p |  | does not support negative axis |
| [max](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.cc) | p |  | does not support negative axis |
| [argmin](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.cc) | p |  | does not support negative axis |
| [argmax](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.cc) | p |  | does not support negative axis |
| [sort](https://github.com/dmlc/mxnet/pull/3952) | v |  |  |
| [argsort](https://github.com/dmlc/mxnet/pull/3952) | v |  |  |
| [SliceChannel](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/slice_channel.cc) | p |  | support negative axis, but should be moved to "operator/tensor" |
| [slice_axis](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/matrix_op.cc) | p |  | does not support negative axis, also the `end` argument does not support negative value. |
| split | x |  | Should be an alias of _SliceChannel_ |
| [Concat](https://github.com/dmlc/mxnet/blob/nnvm/src/operator/concat.cc) | p |  | does not support negative axis, need to move to "operator/tensor", also the keyword is **dim** instead of **axis** |
| concatenate | x |  | Should be an alias of _Concat_. We need to use **axis** for this OP|

Possible TODOs
-----------------
- [x] Support `axis=None` when parsing the arguments. ~~Need to revise the parser (https://github.com/dmlc/mxnet/blob/nnvm/python/mxnet/_ctypes/ndarray.py), (https://github.com/dmlc/mxnet/tree/nnvm/python/mxnet/cython)~~ We support optional now, so we can support axis=None by `optional<int>`
- [ ] Check the default behaviors of the OPs that are the same as Numpy
- [ ] Support negative axis

**Comment by piiswrong** [comment]
The problem is existing models use -1 for global reduction and it's written into the json files.

@tqchen We need a versioning and conversion system for json files

**Comment by tqchen** [comment]
I think we will change the convention of sum to allow tuple axis first and none. The negative index support could come later after 0.9 get widely adopted

**Comment by piiswrong** [comment]
Either way we need versioning and conversion to change axis=-1 to axis=None for previously saved jsons
