### ISSUE TITLE
Matlab c_api gives  wrong predict result for binary classification

### ISSUE THREAD

**Issue by chengjuzhou** [apache/incubator-mxnet#3665]
Thanks for providing Matlab binding for mxnet. The Matlab binding works well when I use to predict multi-class classification, but gives wrong result when I try to do binary classification.  The predicted probability is always like [0.9998  0.0002], the index-0 is near 1 while index-1 is near zero. Can someone help me solve the problem?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
