### ISSUE TITLE
Mxnet amalgamation project rely on intel MKL?

### ISSUE THREAD

**Issue by fengshikun** [apache/incubator-mxnet#3667]
I didn't install the intel mkl lib and have installed the mxnet without mkl. After i build the openblas for android, make the amalgamation project for android will generate such error:

```
arm-linux-androideabi-g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/home/kun/Documents/Android/mxnet/OpenBLAS -I/home/kun/Documents/Android/mxnet/OpenBLAS/include -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -O3 -fPIC -o jni_libmxnet_predict.o -c jni/predictor.cc
In file included from jni/predictor.cc:4:0:
jni/../mxnet_predict-all.cc:41:36: fatal error: mkl/mkl_batch_norm-inl.h: No such file or directory
 #include <mkl/mkl_batch_norm-inl.h>
                                    ^
compilation terminated.
make: *** [jni_libmxnet_predict.o] Error 1
```

**Comment by piiswrong** [comment]
@zhenlinluo

**Comment by zhenlinluo** [comment]
@fengshikun  can you let me know how to reproduce this issue? It seems very weird that you predict-all.cc try to find mkl header file. Can you check if you enable "MXNET_USE_MKL2017=1?

**Comment by glingyan** [comment]
reproduced , will have a look
looks like amalgamation's problem

**Comment by piiswrong** [comment]
@glingyan While you are at it, could you also fix the warnings caused by mkl?

**Comment by fengshikun** [comment]
Updated, it looks like the amalgamation.py problem: it doesn't filter the mkl2017 .h file
change amalgamation.py  line 89-90 to:
```
if not source:
    if h not in blacklist and h not in sysheaders and 'mkl' not in h: sysheaders.append(h)
```
fixed the error!

**Comment by arank** [comment]
Hi I'm getting the same error when trying to compile via amalgamation for mxnet.js 

$ make MIN=1 libmxnet_predict.js
emcc -std=c++11 -O2 -D__MXNET_JS__  -o libmxnet_predict.js mxnet_predict-all.cc \
	-s EXPORTED_FUNCTIONS="['_MXPredCreate', '_MXPredGetOutputShape', '_MXPredSetInput', '_MXPredForward', '_MXPredPartialForward', '_MXPredGetOutput', '_MXPredFree', '_MXNDListCreate', '_MXNDListGet', '_MXNDListFree']" \
	-s ALLOW_MEMORY_GROWTH=1
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
mxnet_predict-all.cc:43:10: fatal error: 'mkl/mkl_batch_norm-inl.h' file not found
#include <mkl/mkl_batch_norm-inl.h>
         ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [libmxnet_predict.js] Error 1


I made the change to amalgamation.py described above but the same error persists. How do I get this building?

**Comment by glingyan** [comment]
I tested
But get below error first
/mxnet/amalgamation$ make MIN=1 libmxnet_predict.js
emcc -std=c++11 -O2 -D__MXNET_JS__  -o libmxnet_predict.js mxnet_predict-all.cc \
-s EXPORTED_FUNCTIONS="['_MXPredCreate', '_MXPredGetOutputShape', '_MXPredSetInput', '_MXPredForward', '_MXPredPartialForward', '_MXPredGetOutput', '_MXPredFree', '_MXNDListCreate', '_MXNDListGet', '_MXNDListFree']" \
-s ALLOW_MEMORY_GROWTH=1
WARNING  root: Disabling asm.js validation for memory growth (memory can grow, but you lose some amount of speed)
mxnet_predict-all.cc:21:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
Makefile:60: recipe for target 'libmxnet_predict.js' failed
make: *** [libmxnet_predict.js] Error 1

**Comment by leezu** [comment]
@fengshikun
Thanks. In addition to blacklisting `mkl` I had to exclude `nnpack` and `omp.h`:

Should this be incorporated in the master branch? (And is this even correct? At least the build process for mxnet.js would run through without problems, but I haven't tested it further). If so I can prepare a pull request..

Is my understanding correct, that one has to assure that in the config.mk CUDA, CUDNN, OPENMP, MKL2017, etc. are disabled? If so I would suggest to state this in the readme.

```
diff --git a/amalgamation/amalgamation.py b/amalgamation/amalgamation.py
index be85418..9967ed7 100644
--- a/amalgamation/amalgamation.py
+++ b/amalgamation/amalgamation.py
@@ -7,7 +7,8 @@ blacklist = [
     'glog/logging.h', 'io/azure_filesys.h', 'io/hdfs_filesys.h', 'io/s3_filesys.h',
     'kvstore_dist.h', 'mach/clock.h', 'mach/mach.h',
     'malloc.h', 'mkl.h', 'mkl_cblas.h', 'mkl_vsl.h', 'mkl_vsl_functions.h',
-    'nvml.h', 'opencv2/opencv.hpp', 'sys/stat.h', 'sys/types.h', 'cuda.h', 'cuda_fp16.h'
+    'nvml.h', 'opencv2/opencv.hpp', 'sys/stat.h', 'sys/types.h', 'cuda.h', 'cuda_fp16.h',
+    'omp.h'
     ]
 
 if len(sys.argv) < 4:
@@ -87,7 +88,7 @@ def expand(x, pending):
         h = m.groups()[0].strip('./')
         source = find_source(h, x)
         if not source:
-            if h not in blacklist and h not in sysheaders: sysheaders.append(h)
+            if h not in blacklist and h not in sysheaders and 'mkl' not in h and 'nnpack' not in h: sysheaders.append(h)
         else:
             expand(source, pending + [x])
     print >>out, "//===== EXPANDED: %s =====\n" %x

```

**Comment by glingyan** [comment]
Hi Leonard:
   Although I am not a maintainer, I think you are right, just pull a request and waiting for board to review

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
