### ISSUE TITLE
Difficult to get/save symbols in new API mxnet.module

### ISSUE THREAD

**Issue by bearsroom** [apache/incubator-mxnet#3668]
I've been using MXNET for a while and get used to the interface mxnet.model.FeedForward, which has a method save_checkpoint(). This method returns a JSON file of symbol definition and .params for saving args and aux params. But with the new API mxnet.module I can't figure out how to get/save the symbol easily in this module, and it makes more complex to use or finetune on models based on this interface, since loading a model requires a JSON file for symbol definition.

In `mxnet.module.BaseModule` there's a property `symbol` which allows us to get the symbol in module. But in other inherit classes like `mxnet.module.Module` and `mxnet.module.SequentialModule`, we can comprise/stack modules to build more complex networks. This makes harder to access the whole symbol in these modules, even though we can get symbols of each submodules in recursive way and concat them, but this is still not straightforward for me.

**Comment by piiswrong** [comment]
@pluskid How about a save_symbol() or save_checkpoint method for module?

**Comment by pluskid** [comment]
@piiswrong checkpoint saving and loading is already supported for plain `Module`. For example, the built-in `checkpoint` callback works fine in the same way. I think @bearsroom is talking about more complicated modules like `SequentialModule` and `BucketingModule`. In some cases, there are multiple symbols (like bucketing). I was thinking about saving all the instantiated instances as a key-value dictionary. But that might not be enough during testing. In some other cases, such a `PythonModule`, there might not even be any symbol associated with it.

Currently a better solution might be to isolate the network definition functions of your experiment in a separate file, and load that file to define networks in both training and testing, and then it will work even if no symbols are loaded. But I agree this is not ideal for deploying.

**Comment by bearsroom** [comment]
@pluskid  Saving and loading params using `load_params` and `save_params` in `Module` works fine for me, but I was thinking about another advantage of having a complete definition of network: We can easily check every component and visualize the network using `mxnet.visualization` (it requires symbol definitions too!). Also it's more straightforward for caffe people, as the whole network is well defined in a single prototxt file.

**Comment by DiaG48** [comment]
Also, predict API require "symbol_json_str" and "param_bytes". Am I forced to use mxnet.model interface (for amalgamation)?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
