### ISSUE TITLE
How to choose batch size when using multi-GPU

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#3675]
Hi All,

I used MXNet to run the GoogleNet and Inception-BN networks in examples/image_classification. I got good speedup in both networks, but the batch size choice is different in these two models. 

In GoogleNet, the batch size is constant 144 for 1 GPU, 2 GPUs and 4 GPUs.
But in Inception-BN, the batch size is 64 for 1 GPU, 128 for 2 GPUs and 256 for 4 GPUs.

Based on the description in https://github.com/dmlc/mxnet/blob/master/docs/how_to/multi_devices.md, the batch size should be constant for 1 GPU and multiple GPUs. This is because when multiple GPUs are used, the samples in one batch is distributed to all GPUs. But why for Inception-BN, we need to change the batch size? Another post https://github.com/dmlc/mxnet/issues/2283 also changed the batch size. 

Regards,
Rengan

**Comment by piiswrong** [comment]
Its a hyperparameter that you can set to whatever you want.

**Comment by hfutxrg** [comment]
I did not mean the absolute value of batch size. I mean what the batch size should be when using multiple GPUs compared to the batch size when using only 1 GPU. For example, when using 1 GPU, we set the batch size as M. If the goal is just to see the performance speedup when using multiple GPUs, then for the same model using 2 GPUs, the batch size should also be M instead of 2M, right? Because if we use 2M, then the learning will be different from M. 

In GoogleNet, I did use M (M=64) for 1 GPU and multiple GPUs and got good speedup. But for Inception-BN, I had to use M for 1 GPU and 2M for 2 GPUs. That's the part I do not understand.

**Comment by zihaolucky** [comment]
I use the -1 trick, which MXNet would auto-figureout batchsize. Take a look at the document for details.

**Comment by mli** [comment]
suggest to use n*M for n GPUs. the gradients are divided by the batch size, so it should not be too sensitive to the value you use.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
