### ISSUE TITLE
Can we use MXNET to do unsupervised learning?

### ISSUE THREAD

**Issue by DCYN** [apache/incubator-mxnet#3688]
Can we use MXNET to do unsupervised learning, such as clustering? Where shall I find the examples and API? Thanks

**Comment by VoVAllen** [comment]
There are examples for GAN as semi-supervised learning example. I don't think mxnet is the right tool for clustering.

**Comment by DCYN** [comment]
@VoVAllen Many thanks. Is there any good tool to calculate clustering on GPU?

**Comment by piiswrong** [comment]
try examples/dec

**Comment by DCYN** [comment]
@piiswrong Many thanks!

**Comment by hukangrong** [comment]
@piiswrong the acc of the dec clustering is 0.11?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
