### ISSUE TITLE
cudnn result not consistent with cpu's

### ISSUE THREAD

**Issue by shesung** [apache/incubator-mxnet#3690]
I compiled mxnet with cudnn and used the example in example/notebooks/predict-with-pretrained-model.ipynb. I printed global_pooling_feature.sum() to check the consistency betwwen cudnn and cpu. The result differs significantly. After removing the cudnn pooling operator, two results became the same.

I wonder whether there are bugs in cudnn's pooling function. I tested cudnn v3 and v5, and both had the same behavior. 

Please check this!

**Comment by piiswrong** [comment]
@winstywang

**Comment by winstywang** [comment]
How much is the difference? Does it affect the final result?

**Comment by shesung** [comment]
@winstywang 

Yes. The probs can differ as much as 10 percents when the number of classes is small. In some case, it will result in a different top-1 label. 

Without cudnn, the difference between cuda and cpu can be ignorable. the probs differ less than 10^-6

**Comment by neodooth** [comment]
+1

**Comment by reminisce** [comment]
We re-implemented pooling operator to support 1/2/3-D operations and fixed some bugs. Could you try it one more time? Besides, you can use **cudnn_off=True** to turn off cudnn pooling and force using MXNet pooling operator (gpu) instead.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
