### ISSUE TITLE
Numerical Gradient Improvement

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#3693]
@sxjscience: I noticed that the [numerical gradient checker](https://github.com/dmlc/mxnet/blob/2c8d209baac9ca262240dd3af59a14a5f49f8832/python/mxnet/test_utils.py#L260) uses `(f(x + h) - f(x)) / h` instead of the centered difference method `(f(x + h) - f(x -h)) / 2h`. The numerical error in the latter is of order `O(h^2)` and works much better in practice, whilst the former is `O(h)`. I've noticed that one needs to give a very large tolerance when doing grad checks in the test suite, perhaps because of this method.

Is there a reason for using the less precise method? Or can I change it?

**Comment by sxjscience** [comment]
@sbodenstein I think the reason is that we need to evaluate the function two times if using the latter version. However, since central difference is more accurate, we can change it to this version.

**Comment by sbodenstein** [comment]
@sxjscience: you pay twice the computational cost for much more than twice the precision. I really think its worthwhile, particularly because the gradient checker doesn't work very well at the moment (from a few tests I've run).

**Comment by sxjscience** [comment]
@sbodenstein Yes, I think it's worthwhile to make the change. Let's do it.

**Comment by sxjscience** [comment]
@sbodenstein Have you already worked on this? I can ask @jennyzhang0215 to finish this part if you do not have time.

**Comment by sbodenstein** [comment]
Sorry, didn't get around to it. That would be great if @jennyzhang0215 could do it.

**Comment by jennyzhang0215** [comment]
Fine. I'll pull it soon.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
