### ISSUE TITLE
How to slice a tensor along its first axis (axis=0)?

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#3705]
For some reason, I have to slice the feature tensor from (N, C) to N separate feature tensor (1, C). I know that I can do it like `f_out = mx.sym.SliceChannel(data=f_in, num_outputs=N, axis=0)` if the batch size N is known.

But that requires me to add a parameter in my symbol building function like `get_symbol(num_classes, batch_size)`. Can I get that value dynamically when calling this symbol building function? Or just set num_outputs=-1 to let mx.sym.SliceChannel slice each row as a default way?

**Comment by piiswrong** [comment]
It doesn't work that way because the graph would be different.

**Comment by nicklhy** [comment]
@piiswrong , then I guess I do have to explicitly pass the batch size as a parameter when calling that symbol building function.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
