### ISSUE TITLE
Where the req type is defined when do backward?

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#3707]
Hi, 

In Backward definition, if OpReqType &req is not what I want, how I can change it and where? @mli @piiswrong 

Thanks

**Comment by piiswrong** [comment]
it's specified by grad_req in symbol.bind

**Comment by zhenlinluo** [comment]
rnn_cell_demo.py does not have mx.sym.bind to be called. Is there any example python to verify the grad_req of param and statecell can support kWriteTo?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
