### ISSUE TITLE
`reldiff` in NNVM branch

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#3711]
I find that the `reldiff` in NNVM has been changed and the 1e07 here seems to be a typo (https://github.com/dmlc/mxnet/blob/nnvm/python/mxnet/test_utils.py#L100). Should we make it the same as the master? @piiswrong

**Comment by piiswrong** [comment]
It should be 1e-07...
I changed it because I think we should use max instead of avg

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
