### ISSUE TITLE
3D Support for Pooling and Convolution

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#3712]
We would really like to have full 3D support for convolutions and pooling (for both GPU + CPU ), and will start contributing the missing pieces. This issue is to track the various tasks and progress, get comment and feedback, and coordinate efforts (if others would also like to contribute). The following needs to be implemented:

- [ ] CPU 3D convolution (already have cuDNN GPU)
- [ ] CPU + GPU 3D dilated convolution
- [ ] CPU 3D Max, Mean + Total Pooling (already have cuDNN for GPU)
- [ ] CPU + GPU 3d Pad layer

The strategy: adapt corresponding Torch layers. Everything will be `NCDHW` format (`D` = depth, of course the order of the spatial dims doesn't matter).

@piiswrong @sxjscience

**Comment by piiswrong** [comment]
maybe caffe layer would be easier to adapt

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
