### ISSUE TITLE
can pooling_convention be set as full by default?

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#3717]
Currently most symbol still does not have pooling_convention parameter, the default value is valid. Why can it be set as full by default? It can help all future training to base on the new formula and avoid potential shape issue(like googlenet in deepmark can not be run by default until it add pooling_convention=full). But this require all pre-trained model to be retrained again. 

@mli  @piiswrong  What do you think about this?

**Comment by piiswrong** [comment]
Changing default behavior breaks backward compatibility

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
