### ISSUE TITLE
Does mxnet provide Model Average for distributed training?

### ISSUE THREAD

**Issue by dx80232** [apache/incubator-mxnet#3723]
Now I would like to train the example code _train_cifar10_resnet.py_ with two local workers, is there any existed model average implementation I can directly use? (For example, CNTK has this kind of feature)
Or should I write the corresponding update rules for the kv-store?

Thanks a lot!

**Comment by piiswrong** [comment]
what model averaging?
try kv-store=dist_sync?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
