### ISSUE TITLE
Problem with SoftmaxOutput() in multi-output prediction

### ISSUE THREAD

**Issue by linxiamen** [apache/incubator-mxnet#3726]
Hi,all!
   I want to use a network to predict a 19,19 matrix.After using the fully connected layer I use a SoftmaxOutput layer with multi-output is True.Each label is a 19*19 matrix which has only one position equal to 1.Then I tried to flatten the labels and the predictions changed to 1/361.
def getnet():
    data    =   mx.symbol.Variable('data')
    conv1   =   ConvFactory(data=data,num_filter=128,kernel=(5,5),pad=(2,2))
    conv2   =   ConvFactory(data=conv1,num_filter=128,kernel=(3,3),pad=(1,1))
    conv3   =   ConvFactory(data=conv2,num_filter=128,kernel=(3,3),pad=(1,1))
    conv4   =   ConvFactory(data=conv3,num_filter=128,kernel=(3,3),pad=(1,1))
    conv5   =   ConvFactory(data=conv4,num_filter=128,kernel=(3,3),pad=(1,1))
    conv6   =   ConvFactory(data=conv5,num_filter=128,kernel=(3,3),pad=(1,1))
    conv7   =   ConvFactory(data=conv6,num_filter=128,kernel=(3,3),pad=(1,1))
    conv8   =   ConvFactory(data=conv7,num_filter=128,kernel=(3,3),pad=(1,1))
    conv9   =   ConvFactory(data=conv8,num_filter=128,kernel=(3,3),pad=(1,1))
    conv10  =   ConvFactory(data=conv9,num_filter=128,kernel=(3,3),pad=(1,1))
    conv11  =   ConvFactory(data=conv10,num_filter=128,kernel=(3,3),pad=(1,1))
    conv12  =   ConvFactory(data=conv11,num_filter=128,kernel=(3,3),pad=(1,1))
    conv13  =   ConvFactory(data=conv12,num_filter=1,kernel=(1,1))
    #flatten =   mx.symbol.Flatten(data=conv13,name='flatten')
    mlp     =   mx.symbol.SoftmaxOutput(data=conv13,name='softmax',multi_output=True)
    return mlp
The input data shape is (48,19,19) and the output label shape is (19,19).
I've seen the #1404,and tried the accuracy function:
def array_acc(label,pred):
    return float(np.sum(np.square(label-pred)))
Can anyone please advise how I can make it work correctly?
Thanks.

**Comment by piiswrong** [comment]
multi_output=False

**Comment by linxiamen** [comment]
@piiswrong I've tried that,and I add a flatten layer before the last layer.After that I set multi-output=False,then I get 1/361 at every position in the predicted array.Thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
