### ISSUE TITLE
Cudnn of two different GPU cards

### ISSUE THREAD

**Issue by DCYN** [apache/incubator-mxnet#3728]
My computer has two different GPU cards. The GFX-1060 supports Cudnn and NVS 290 does not. I will only use the 1060 to run MXNET. Is there any problem, if I keep both cards and make the installation with Cudnn supported?

**Comment by piiswrong** [comment]
If nvidia supports that mxnet will

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
