### ISSUE TITLE
mean() operator

### ISSUE THREAD

**Issue by fedorzh** [apache/incubator-mxnet#3729]
Why is there no mxnet.symbol.mean operator? May be I'm missing something, but I don't see how to easily replicate it with sum() as I would need to infer shapes, and thus connect the symbols to data already

**Comment by piiswrong** [comment]
It should be fairly easy to add. copy the sum op and make some small changes

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
