### ISSUE TITLE
Second order derivative

### ISSUE THREAD

**Issue by fedorzh** [apache/incubator-mxnet#3730]
Any ideas how to calculate second order derivative? 
a = mx.sym.Variable('a');
b = mx.sym.FullyConnected(data=a, name='fc1', num_hidden=64)
gr = b.grad(wrt='a')
gr2 = gr.grad(wrt='a')
fails with "Do not support Backward of Backward"

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
