### ISSUE TITLE
Anaconda mxnet package

### ISSUE THREAD

**Issue by RogerBorras** [apache/incubator-mxnet#3734]
I have some problems to install mxnet in ubuntu 16.04 with anaconda. Can you provide an easily build packages for conda, and upload them to anaconda.org? It will be very usefull for python conda users I think, and more easy to install... Thanks for your amazing mxnet library and for you effort!!

**Comment by pjmtdw** [comment]
I wrote a build script for creating Anaconda package for linux:
https://github.com/pjmtdw/mxnet-conda-builder
It can build Python 2.7 and 3.5 package, also with cuDNN.

And here's the repository:
https://anaconda.org/pjmtdw/mxnet

cuDNN one is here:
https://anaconda.org/pjmtdw/mxnet-cudnn

You can install mxnet using `conda install -c pjmtdw mxnet=0.9.3`

I hope someday there would be official repository for Anaconda.

**Comment by RogerBorras** [comment]
Many thanks @pjmtdw !!

The installation i correct in my anaconda installation. But when I import the library, I have this error:

`>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/roger/anaconda3/lib/python3.5/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/roger/anaconda3/lib/python3.5/site-packages/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/roger/anaconda3/lib/python3.5/site-packages/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/roger/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/roger/anaconda3/lib/python3.5/site-packages/mxnet/../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/roger/anaconda3/lib/python3.5/site-packages/mxnet/libmxnet.so)
`
Do you now what happes?

**Comment by pjmtdw** [comment]
Yes, your libgcc is old. try `conda install libgcc=5.2.0`

https://github.com/pjmtdw/mxnet-conda-builder#troubleshooting

I'm searching for a method to force this from dependency.

**Comment by pjmtdw** [comment]
added libgcc >=5.2.0 for dependency. so this should not happen anymore.

**Comment by zihaolucky** [comment]
@piiswrong @szha

**Comment by RogerBorras** [comment]
@pjmtdw Great job, thanks a lot!

**Comment by RogerBorras** [comment]
@pjmtdw is possible to provide the same conda installer for windows users?

**Comment by pjmtdw** [comment]
@RogerBorras  I will give a try: https://github.com/pjmtdw/mxnet-conda-builder/issues/3

**Comment by szha** [comment]
@pjmtdw thanks for making the anaconda package. Are you still maintaining them?

**Comment by pjmtdw** [comment]
@szha sorry for being late, I updated the mxnet package for anaconda to version 0.10.0.
https://anaconda.org/pjmtdw/mxnet
https://anaconda.org/pjmtdw/mxnet-cudnn

If you are speaking about anaconda package for Windows,
since I'm not so familiar with Windows, it is hard for me to create it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by jiagengliu** [comment]
@pjmtdw Could you add the support for 1.0.0? Thank you!

**Comment by pjmtdw** [comment]
@jiagengliu 
Yes, I'was struggling to support it. but got stuck a little bit according to compile error. Maybe takes time.
