### ISSUE TITLE
element - wise logical operator ?

### ISSUE THREAD

**Issue by raAen** [apache/incubator-mxnet#3738]
is there any element - wise logical operator in mxnet, for example "greater" or "less than"

or how to implement by current function

===================
example code : 

a = mx.nd.array([0, 1, 1, 0])

b = mx.nd.array([1, 0, 1, 0])

print type(a > b)

======================

current output is a normal python bool type  <type 'bool'> and only one value

but i want output to be an element-wise array, like : [False, True, False, False]

**Comment by VoVAllen** [comment]
No such operator currently in mxnet I think. Maybe http://mxnet.io/api/python/symbol.html#mxnet.symbol.sign can somehow solve your proble.

**Comment by raAen** [comment]
@VoVAllen  thank you for your reply, but i edited my post , i think previous version is some kind of misleading , i want the output to be an element wise array, not python type

**Comment by VoVAllen** [comment]
I think http://mxnet.io/api/python/symbol.html#mxnet.symbol.sign can solve your problem. Just mx.sym.sign(a-b) I think it's what's you want.

Also if you are using executor to do your model, you can use http://mxnet.io/api/python/ndarray.html#mxnet.ndarray.sign

**Comment by raAen** [comment]
@VoVAllen but my value is not only binary value 
for example [ -1 , 19 , 4 ] > [0 , 5, 22 ] = [ False, True , False ]

**Comment by raAen** [comment]
@VoVAllen thank you it works !

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
