### ISSUE TITLE
NDArray slice_axis bug? "unary_ndarray_function() got an unexpected keyword argument 'axis'"

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#3749]
Hello,

I just downloaded the latest source code for the mxnet library and compiled it. Using the new libmxnet.dll, my code breaks where I use slice_axis method of mx.ndarray module. I tried it for the following simple example as well:

    array = mx.ndarray.zeros(shape=(10,20,30))
    sliced = mx.ndarray.slice_axis(src=array, axis=0, begin=2, end=3)

I get following error:

    sliced = mx.ndarray.slice_axis(src=array, axis=0, begin=2, end=3)
TypeError: unary_ndarray_function() got an unexpected keyword argument 'axis'

This was not present until I recently started to use the new mxnet code. Could there be a bug introduced somewhere?

**Comment by piiswrong** [comment]
are you using nnvm branch?

**Comment by sxjscience** [comment]
The NNVM branch also works for me.
You need to use
```python
array = mx.ndarray.zeros(shape=(10,20,30))
sliced = mx.ndarray.slice_axis(array, axis=0, begin=2, end=3)
```

**Comment by shuokay** [comment]
master branch works for me.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
