### ISSUE TITLE
Backward OpReqType is not respected by a few layers

### ISSUE THREAD

**Issue by taliesinb** [apache/incubator-mxnet#3751]
The following layers seem not to use the Assign macro or any custom code to actually implement the OpReqType that they are passed during Backward:

* Spatial Transfomer
* Correlation 
* Crop
* SoftmaxOutput
* SwapAxis

I may be missing some, I didn't check exhaustively. 

This is a bit troubling, though it shouldn't be hard to fix. We ( @sbodenstein ) haven't actually verified with tests that these layers will do the wrong thing (or crash in the case of no ingrad being allocated), but that seems probable. @piiswrong what do you make of this?

**Comment by piiswrong** [comment]
Operators would either respect OpReq or CHECK_EQ(req, kXXX). Otherwise it's a bug we need to fix

**Comment by tqchen** [comment]
related to https://github.com/dmlc/mxnet/pull/3470

Maybe consider AddTo as Opt in and re-sweep the operators is a better strategy in NNVM

**Comment by taliesinb** [comment]
Thanks for weighing in guys.

One argument in favor of AddTo being Opt in is that the Assign macro can contribute to code bloat if used naively. I would guess that if the backward op is complex and the ingrad can't be calculated without a temporary, then it's better left up to the framework to implement AddTo, because there's no memory benefit to using Assign, it just contributes to code bloat.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by taliesinb** [comment]
How can I re-open this. I think its important not to forget about the underlying issue.
