### ISSUE TITLE
Add new optimizer - Eve (Adam improvement)

### ISSUE THREAD

**Issue by gugatr0n1c** [apache/incubator-mxnet#3753]
Hi,

there is new improvement of Adam algorithm, called Eve.
I would be nice to add this as a new optimizer, results are interesting:

https://arxiv.org/pdf/1611.01505v1.pdf

**Comment by piiswrong** [comment]
Looks interesting. Would you like to submit a PR?

**Comment by gugatr0n1c** [comment]
I am sorry, but unfortunately that is out of my skill. I just create this issue as proposal.
Thx to anyone who is interested to code this.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
