### ISSUE TITLE
Change threading module to multiprocessing module in PrefetchingIter(python)

### ISSUE THREAD

**Issue by dccho** [apache/incubator-mxnet#3755]
I use a lot of small images and process some random crop and resize which are very cpu oriented works.
I find that PrefetchingIter in python module are implemented using threading module which does not work like real thread as we expect.
Can you change threading module to multiprocessing module in PrefetchingIter to get full performance of multicore CPU? I try to change it but somehow it hang and can't debug.

**Comment by piiswrong** [comment]
You can try the new io interface in mx.image

**Comment by shuokay** [comment]
@dccho May be you can refer to [this post](http://shuokay.com/2016/08/16/mxnet-io/)(in zh_cn) about multiprocessing prefetching

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
