### ISSUE TITLE
mx.apply crash

### ISSUE THREAD

**Issue by Orbifold** [apache/incubator-mxnet#3766]
Something as simple as this crashes both on Mac and Windows:
    
    require(mxnet)
    a = mx.symbol.Variable(name = "a")
    b = mx.symbol.Variable(name = "b")
    c = a + b
    res = mx.apply(x=c, a=1, b=4, name="sum", ctx=mx.ctx.default())

Anything forbidden here? Shouldn't crash the whole thing in any case.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
