### ISSUE TITLE
Problems using csviter

### ISSUE THREAD

**Issue by wsstriving** [apache/incubator-mxnet#3767]
In the example/module/mnist_mlp.py, validation  accuracy is computed as follows:
```python
# a dummy call just to test if the API works for merge_batches=True
# preds = mod.predict(val_dataiter)

# perform prediction and calculate accuracy manually
preds = mod.predict(val_dataiter, merge_batches=False)
val_dataiter.reset()
acc_sum = 0.0; acc_cnt = 0
for i, batch in enumerate(val_dataiter):
    print i
    pred_label = preds[i][0].asnumpy().argmax(axis=1)
    label = batch.label[0].asnumpy().astype('int32')
    acc_sum += (label == pred_label).sum()
    acc_cnt += len(pred_label)
print('validation Accuracy: %.3f' % (acc_sum / acc_cnt))
```

I borrowed this part in my own training scripts, which read in csv data using csviter.
```python
    data_val = mx.io.CSVIter(data_csv = valdatacsv,
                                    data_shape = (400, ),
                                    label_csv = vallabelcsv,
                                    label_shape = (1,),
                                    batch_size = batchsize,
                                    shuffle = True,
                                    seed = 10)
    #preds =  mod.predict(data_val, merge_batches=False)
    preds =  mod.predict(data_val, merge_batches=False)
    data_val.reset()
    acc_sum = 0.0
    acc_cnt = 0
    for i, batch in enumerate(data_val):
        print i
        pred_label = preds[i][0].asnumpy().argmax(axis=1)
        label = batch.label[0].asnumpy().astype('int32')
        acc_sum += (label==pred_label).sum()
        acc_cnt += len(pred_label)
    print('Validation accuracy = %.3f' % (acc_sum/acc_cnt))
```
However, this will throw an error as 
```
Traceback (most recent call last):
  File "train_model.py", line 93, in <module>
    pred_label = preds[i][0].asnumpy().argmax(axis=1)
IndexError: list index out of range
```
The validation sample number is 9534 and the batchsize is 128; 9534/128=74.48, which means there should be 74 full batch and the last batch is not full. This error happens because the the preds abandons the last batch? I don't know how to fix this (MnistIter doesn't have this problem). Then a strange thing happens, if we uncomment the commented line, which means we compute the preds twice(which seems to me overwriting, which makes no difference); no error will be reported, but the computed validation accuracy is very low (wrong);  I think it should because of the last batch causes the label shift, but can not understand why it happens and how to fix it. Could anyone give some explanation?

**Comment by shuokay** [comment]
Try to change `pred_label = preds[i][0].asnumpy().argmax(axis=1)` to 
`pred_label = preds[i].asnumpy().argmax(axis=1)`

**Comment by wsstriving** [comment]
@shuokay Nope, this doesn't since preds[i] is a list

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
