### ISSUE TITLE
distributed issues

### ISSUE THREAD

**Issue by huanhuanxuxu** [apache/incubator-mxnet#3772]
hi, I'm working on distributed training following instructions in the tutorial "../..tools/launch.py -n 2 python train_minist.py --kv-store dist_sync", here's the error:

Traceback (most recent call last):
  File "../../tools/launch.py", line 88, in <module>
    main()
  File "../../tools/launch.py", line 69, in main
    raise RuntimeError('Unknown submission cluster type %s' % args.cluster)
RuntimeError: Unknown submission cluster type ssh

any thoughts?

**Comment by feiyulv** [comment]
You should specify the hosts file
```
../..tools/launch.py -n 2 -H hosts 2 python train_minist.py --kv-store dist_sync
```

**Comment by huanhuanxuxu** [comment]
> @feiyulv Thanks. I follow the instructions it says "have a quick test on local machine by using two workers" so I don't think thats a problem.

**Comment by guotong1988** [comment]
Same question. What is the format of `host-file`?
Thank you @huanhuanxuxu @feiyulv

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
