### ISSUE TITLE
cudnn v5  problem on win7

### ISSUE THREAD

**Issue by nopattern** [apache/incubator-mxnet#3773]
I am running mxnet on python+win7+cuda8.0.  It's good . Then I added cudnn v5.15 . The program output an error:
        

> mxnet\src\operator\./cudnn_c
> onvolution-inl.h:296: Check failed: (cudnnSetFilter4dDescriptor(filter_desc_, dt
> ype_, format_, param_.num_filter / param_.num_group, data.shape_[1] / param_.num
> _group, param_.kernel[0], param_.kernel[1])) == (CUDNN_STATUS_SUCCESS)

      
     Does the current version support cudnn v5.15?

**Comment by piiswrong** [comment]
mxnet does.
Cuda8 probably doesn't

**Comment by nopattern** [comment]
I installed spyder(python) + keras  on my pc  too which supports  cuda8+cudnnv5. Cuda8 is provided with cudnn v5 by nvidia, I think  cuda8 supports cudnn5.

**Comment by nopattern** [comment]
The cudnnSetFilter4dDescriptor  function returns CUDNN_STATUS_BAD_PARAM==3. 
Function parameters are as following :
dtype_:0 ,format_:0, param_.num_filter,param_.num_group :64 1,data.shape_[1] :3,  param.kernel: 3 3.

It seems nothing wrong .

**Comment by nopattern** [comment]
I have tesetd the linux  version which is correct. @piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
