### ISSUE TITLE
LSTM Regression model 

### ISSUE THREAD

**Issue by kreshnaaraamsb** [apache/incubator-mxnet#3779]
Will it be possible to fit a regression model using current implementation of LSTM in mxnet. I tried it, but not able to run it. I am able to run MLP implementation using rmse as activation engine. Training works fine, but when predicted gives only one value as output. In case of feed forward model I am not getting any value when fitting the train data. All the eval metrics ie train rmse values are NA's. Same with predictions.
I use the same variable(R array) for all three models. I am not able to understand why mlp can fit a model (Though it gives only single prediction value) whereas Feedforwards fits NA values, and LSTM throws error.

P.S: I am new to learning neural nets. may be the question is too basic or amaetuer. Excuse if it is so.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
