### ISSUE TITLE
Wrong hierarchy in the mxnet doc

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#3786]
http://mxnet.io/how_to/perf.html

345 should be the sub point of 2

**Comment by piiswrong** [comment]
@sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
Submitted PR - https://github.com/dmlc/mxnet/pull/3834

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
