### ISSUE TITLE
Multiple-node training never ends...

### ISSUE THREAD

**Issue by FreemanX** [apache/incubator-mxnet#3787]
![image](https://cloud.githubusercontent.com/assets/9710644/20166611/f394c888-a750-11e6-9925-3602ff23f83d.png)
As shown above, the process of training ends but the program doesn't. I set PS_VERBOSE=2 and these are the outputs after training. The lower Terminal shows the current network traffic status.  I have no idea what's going on here...
I notice that there are '? => id' in it, does it lose track of certain processes? 
My running script:
DMLC_INTERFACE=em3 PS_VERBOSE=2 python ~/mxnet/tools/launch.py --launcher ssh -n 2 -s 1 -H hosts2 python train_mnist.py --lr 0.05 --kv-store dist_sync --batch-size 4096 --num-epochs 4 --gpus 0,1,2,3

**Comment by mli** [comment]
that's because python catches the terminate signals even `exit(0)` is called. before it is fixed, please kill the job by hands

```
cat hosts | xargs -I {} ssh {} killall -9 python
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
