### ISSUE TITLE
lstm inference simple_bind error?

### ISSUE THREAD

**Issue by xlvector** [apache/incubator-mxnet#3793]
I write an symbol for lstm like：

```

def cls_hidden_sym(vocab_size, num_lstm_layer, \
                  num_hidden, seq_index):
    param_cells, last_states = param_and_states(num_lstm_layer)
    data = mx.sym.Variable('data')
    embed_weight = mx.sym.Variable('embed'+str(seq_index) + '_weight')
    hidden = mx.sym.Embedding(data = data, input_dim = vocab_size,
                                  weight = embed_weight,
                                  output_dim = num_hidden,
                                  name = 'data' + str(seq_index) + '_embed')
    for i in range(num_lstm_layer):
        next_state = lstm(num_hidden, indata = hidden,
                          prev_state = last_states[i],
                          param = param_cells[i],
                          seqidx = 0, layeridx = i)
        hidden = next_state.h
        last_states[i] = next_state
    output = [hidden]
    for state in last_states:
        output.append(state.c)
        output.append(state.h)
    return mx.sym.Group(output)

```

When I do simple_bind, I will get following error:

mxnet.base.MXNetError: [12:03:50] src/symbol/graph_executor.cc:578: Check failed: graph_.InferNodeShapes(topo_order_, &out_shapes, &aux_shapes, false) Shape inference cannot be complete in bind

But if I let output = [mx.FullyConnected(hidden, num_hidden = xxxx)], everything is ok.

When node name casue above error is _mul5_0_out_grad_agg, I find it has two input shapes, but both of them is empty.

**Comment by piiswrong** [comment]
@tqchen

**Comment by xlvector** [comment]
seems I use output = [mx.sym.MakeLoss(hidden)] will also not cause error. However, I does not check if it will give right result. It just will not cause error.

**Comment by xlvector** [comment]
@piiswrong on master

**Comment by xlvector** [comment]
output = [hidden * 1] also works.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
