### ISSUE TITLE
How can i get the shape with the net?

### ISSUE THREAD

**Issue by burness** [apache/incubator-mxnet#3796]
Hi, I want to design a net like this:
```

def net_01(net, **):
    net_1  = conv(net, ...)
    net_2 = conv(net_1, num, (1,1),...)
    return net_2
```

the num must be the same as the input params `net`'s channel, how can i get from the net ?
In tensorflow, I can get the shape of the tensor like `net.get_shape()[3]`.

I'm sorry I can't get it from the mxnet  example code ? Could any one help me with this

**Comment by phunterlau** [comment]
Should be related with issue #1090

**Comment by zhreshold** [comment]
```
_, output_shape, _= net.infer_shape(data=(1, 3, 256, 256))
num_channel = output_shape[1]
```
However, I do have concerns that in some situations, the input data shape may not always be consistent. For example, faster-rcnn, though the number of channels are not changing. But anyway, it depends on the demands.

**Comment by feiyulv** [comment]
An operator which gets shape as a symbol will be very usefull

**Comment by wangg12** [comment]
+1 for the feature request!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
