### ISSUE TITLE
im2rec.py problem with image_index all 0  

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#3797]
Hi, I used the im2rec.py tool to make a train.lst and val.lst for my data, but in the lists image_index are all zero, command I type in terminal:
~/mxnet/tools$ python im2rec.py --list=True /home/dyc/data/ /home/dyc/data/train/ --recursive=True
And I got these lines in my train.lst:
0	57.000000	KJDZ0007_FYZCBXPZ_67/X00100000K0S.jpg
0	59.000000	KJDZ0009_SWDJZ_59/X11000000V63.jpg
0	203.000000	neg/X110000041XM.jpg
0	186.000000	KJDZ0203_KHHD_85zxyh/X11000003Q0J.jpg
0	75.000000	KJDZ0101_JSSWXSGJSWJTYJDFP_62/X112000001PH.jpg
0	37.000000	KJDZ0003_SZYXHQCKMXZ_58/X11000004OX9.jpg
0	8.000000	05.KJDZ0003.jsyhckmxz/X102000001FH.jpg
0	70.000000	KJDZ0101_HBZZSZYFP_7287/X11000002WWL.jpg
0	120.000000	KJDZ0103_SHZZSPTFP/X110000056Z8.jpg
0	104.000000	KJDZ0103_BJSGJSWJTYJDFP_21/X11000002L6J.jpg
0	203.000000	neg/X110000030XK.jpg
0	88.000000	KJDZ0101_SXSDFSWJTYJDFP/A8800011HO6E.jpg
0	24.000000	18.KJDZ0202.ywhdskpz/X11000002EYA.jpg
0	172.000000	KJDZ0202_XJJKD_59nyyh/X104000001E2.jpg
0	203.000000	neg/X11000003ZQ8.jpg
0	198.000000	KJDZ0203_YXFKHD_94jnnsh/X104000005B5.jpg
0	146.000000	KJDZ0202_CKLXD_88xyyh/X110000058M7.jpg
0	38.000000	KJDZ0003_ZDMX_29/A880001lHZKR.jpg
0	203.000000	neg/X110000015VG.jpg
0	144.000000	KJDZ0201_ZGYXDZJSFKPZ_58/X11000004KTV.jpg
0	57.000000	KJDZ0007_FYZCBXPZ_67/X11000000998.jpg
0	168.000000	KJDZ0202_WSYXSKHD_88/X11000000HB4.jpg
0	30.000000	28.KJDZ0101.jzytyfpzk/X00100000L0F.jpg
0	18.000000	12.KJDZ0203.gnzfywfkhd/X11000003PG8.jpg
0	141.000000	KJDZ0201_ZGJSYXDWKHZYHD_86/X10200000E8J.jpg
0	182.000000	KJDZ0202_ZGYXDGKHSKTZD/X00300000A2C.jpg
0	78.000000	KJDZ0101_NBZZSZYFP/X11000004C5N.jpg
0	123.000000	KJDZ0103_XMSGJSWJTYJDFP/X11000004NNH.jpg
0	24.000000	18.KJDZ0202.ywhdskpz/X004000001A5.jpg
0	78.000000	KJDZ0101_NBZZSZYFP/X11000003ZW2.jpg
0	192.000000	KJDZ0203_SFRZTZS_87nyyh/X10200000A90.jpg
0	119.000000	KJDZ0103_SDZZSZYFP/X104000006T2.jpg
0	100.000000	KJDZ0101_ZJSDFSWJTYJDFP_6263/X11000004FCU.jpg
0	108.000000	KJDZ0103_FJZZSPTFP/X10200000C5Z.jpg
0	186.000000	KJDZ0203_KHHD_85zxyh/X1100000190B.jpg
0	101.000000	KJDZ0101_ZJSGJSWJTYJDFP_7778/X1100000514Q.jpg
0	175.000000	KJDZ0202_ZFYWHDSK_83/X1100000395L.jpg
0	185.000000	KJDZ0203_KHFFHD_57zgyh/X11000005GLW.jpg
Do I use it incorrectly?

**Comment by piiswrong** [comment]
It's fixed in the nnvm branch

**Comment by xinghedyc** [comment]
@piiswrong thanks for your reply!
I found another problem when training image classification on my dataset using Alexnet,
when I set the scale option to 1.0/255 in ImageRecordIter,it seems train acc does not go up and val acc is always the same, but if I set scale to 1, acc will go up as I expect.
I used the im2rec to make the .rec file and send it to ImageRecordIter.
This looks strange.

**Comment by shuokay** [comment]
I think it because you have a `mean.bin` file generated before you set `scale=1.0/255`, try to remove mean.bin and run again

**Comment by ysh329** [comment]
same error.

First use, I generated rec format data correctly. However, when second use, I met same error (index file is 0KB).

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
