### ISSUE TITLE
how does mxnet process multi-branches network?

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#3799]
take inception network for example:
a. calculates them parallelly as much as possible.
b. calculates them one after one.
 which one?

**Comment by shuokay** [comment]
a, I think you should read the engine document. As to nnvm, I am not sure.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
