### ISSUE TITLE
installation error for scala package

### ISSUE THREAD

**Issue by benlyyan** [apache/incubator-mxnet#3814]
I try to install mxnet for scala-package following the installation guide. After building the shared library, then execute the command: make scalapkg.
But I got an error: 
Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (default) on project mxnet-init_2.11: Execution default of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed
Anybody knows how to solove it?  Thank you so much.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
