### ISSUE TITLE
Documentation error in image_aug_default.cc

### ISSUE THREAD

**Issue by eldercrow** [apache/incubator-mxnet#3820]
In /src/io/image_aug_default.cc, documentations between parameter declaration part and default value setting (DMLC_DECLARE_PARAMETER) do not match. For instance, fill_value should be "filled color while padding", but it is described as "Maximum value of illumination variation" and so on.

**Comment by piiswrong** [comment]
Thanks for reporting. would you like to propose a fix?

**Comment by eldercrow** [comment]
I created a pull request. 
BTW, it seems that crop_y_start and crop_x_start are declared but not used. Are they used in ImageRecordIter?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
