### ISSUE TITLE
[OP] index_fill and index_add operators

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#3822]
As pointed out by @winstywang , the current NDArray and Symbol API do not support operations like a[a>0]=1 and a[a<0] += 2.

I think one solution is to support OPs that set/accumulate part of the input matrix based on the given flags and values. I thus suggest supporting these two operators in the future: `index_add` and `index_fill`.
- **index_add(src, indices, value, index_typ='indices', axis=None)**
  Like [Torch's indexAdd](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor-indexadddim-index-tensor). Accumulate the elements in value to the given indices in the source tensor.
If the axis argument is empty, it performs `src.ravel()[indices] += value`.
If the axis argument is not empty, it performs `src[:, :, indices, :, :] += value`.
  - src: Source tensor. 
  - indices: Tensor that contains either indices or 0-1 mask.
  - value: Tensor that contains the values to accumulate to *src*. If the `axis` is empty, the shape of *value* must be the same as *indices*. If the `axis is not empty, e.g, axis=2, the shape of *value* should be (src.shape[0], src.shape[1], len(indices), src.shape[3]).
  - index_typ: Type of the indices. Can be `indices` or `mask`. If selected as `mask`, *indices* must be a 0-1 tensors and the shape must be the same as the src tensor along the given *axis*
  - axis: The axis to perform the operation. The whole *src* tensor will be taken into consideration if set to empty.
- **index_fill(src, indices, value, index_typ='indices', axis=None)**
  Like [Torch's indexFill](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor-indexfilldim-index-val). Fill the given indices in the source tensor with the elements in value along. If there are duplicate indices with different values, the last value will be filled to the original tensor and the result may be non-deterministic.
If the axis argument is empty, it performs `src.ravel()[indices] = value`.
If the axis argument is not empty, it performs `src[:, :, indices, :, :] = value`.
  - src: Source tensor. 
  - indices: Tensor that contains either indices or 0-1 mask.
  - value: Tensor that contains the values to accumulate to *src*. If the `axis` is empty, the shape of *value* must be the same as *indices*. If the `axis is not empty, e.g, axis=2, the shape of *value* should be (src.shape[0], src.shape[1], len(indices), src.shape[3]).
  - index_typ: Type of the indices. Can be `indices` or `mask`. If selected as `mask`, *indices* must be a 0-1 tensors and the shape must be the same as the src tensor along the given *axis*
  - axis: The axis to perform the operation. The whole *src* tensor will be taken into consideration if set to empty.

In fact, index_add is similar to [the backward operation of Embedding](https://github.com/dmlc/mxnet/blob/master/src/operator/embedding-inl.h#L74-L123) and we can use similar kernels to do the job.

TODOs
-------
- [ ] index_add and index_fill without axis support (only support axis=0)
- [ ] full axis support

**Comment by piiswrong** [comment]
We need binary operator. like b = a > 0

**Comment by sxjscience** [comment]
The new numpy ndarray supports this feature.
