### ISSUE TITLE
ResNet for ILSVRC12 dataset

### ISSUE THREAD

**Issue by cuihenggang** [apache/incubator-mxnet#3837]
I was looking for the ResNet config file for the ILSVRC12 dataset, but I only find the one for the Cifar10 dataset:

https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_resnet.py

Do we have a ResNet config file for the ILSVRC12 dataset?

Thank you very much!

**Comment by piiswrong** [comment]
https://github.com/tornadomeet/ResNet

@tornadomeet Let's merge this into master

**Comment by tornadomeet** [comment]
ok, after @mli refactored the example/classification.

**Comment by mli** [comment]
hope to get the refactor done this week.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
