### ISSUE TITLE
Anyone can help me with the build check after an PR?

### ISSUE THREAD

**Issue by burness** [apache/incubator-mxnet#3846]
I have make an PR #3811  but fails in checks. It's very  stange to me , Could anyone help me with this?  I check the all log of the build check, it seem to be noting with my commits.
the build logs:

[http://54.84.234.35:8080/job/mxnet/412/consoleText](http://54.84.234.35:8080/job/mxnet/412/consoleText)
[https://travis-ci.org/dmlc/mxnet/builds/176068718](https://travis-ci.org/dmlc/mxnet/builds/176068718)

**Comment by zhreshold** [comment]
Fetch upstream again and rebase should fix it. Some links have been fixed which caused the 
 check to fail.

**Comment by burness** [comment]
@zhreshold  Thanks, I will try

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
