### ISSUE TITLE
Heteroscedastic dropout uncertainty

### ISSUE THREAD

**Issue by CharlieKirkwood** [apache/incubator-mxnet#3856]
Can heteroscedastic dropout uncertainty be enabled in MXNet?

This follows from #3821 - I now have networks predicting with dropout uncertainty, but I believe this is homoscedastic uncertainty - see [Yarin Gal's blog post](https://github.com/yaringal/HeteroscedasticDropoutUncertainty).

Yarin provides an [example ConvnetJS code for heteroscedastic uncertainty](https://github.com/yaringal/HeteroscedasticDropoutUncertainty/blob/master/convnetjs/convnet_heteroscedastic.js#L971) but I don't know enough to apply this to MXNet myself.

Can anyone advise on how to implement heteroscedastic regression layers in MXNet? It seems this would be a very useful feature for all regression purposes.

Many thanks.

**Comment by tornadomeet** [comment]
do you mean using drop only in test with random drop the activation value?  if that, you should change the  forward fun in dropout op file, that is :  
* delete this line https://github.com/dmlc/mxnet/blob/master/src/operator/dropout-inl.h#L90  
* delete the else part code, https://github.com/dmlc/mxnet/blob/master/src/operator/dropout-inl.h#L108-L111  

BTW, why during test using the random drop method?

**Comment by tqchen** [comment]
If you mean non-uniform probability It is likely we could do it via composition, now that we have mx.sym.uniform to generate uniform random numbers. One way would be

0.5* (mx.sym.sign(prob - mx.sym.uniform(low=0, high=1)) + 1)

**Comment by CharlieKirkwood** [comment]
Thanks for your answer tornadomeet, I think your suggestion might be equivalent to setting forward(is_train=True) in the predict call? This does provide dropout uncertainty but I believe it is only homoscedastic - i.e. it assumes that the uncertainty of the target variable in relation to predictor variables is consistent throughout the predictor variable feature space, which is not the case in my application. 

The reason to use random drop during test is to get a probabilistic output - i.e. with dropout on you can re-run predict x times to build up a probability distribution, the spread of which provides an indication of the uncertainty of the prediction. Yarin Gal has written a [very good article](http://mlg.eng.cam.ac.uk/yarin/blog_3d801aa532c1ce.html) about this.

Thanks for your answer tqchen. Would that allow the spread of prediction uncertainty for the target variable to become data dependent?

The aim is to achieve the lower of these two images, standard dropout uncertainty provides the upper:
![Homoscedastic dropout uncertainty](https://github.com/yaringal/HeteroscedasticDropoutUncertainty/raw/master/images/homoscedastic_dropout_reg_large_observation_noise.png)

![Heteroscedastic dropout uncertainty](https://github.com/yaringal/HeteroscedasticDropoutUncertainty/raw/master/images/heteroscedastic_dropout_reg.png)

The theory is explained [here](https://github.com/yaringal/HeteroscedasticDropoutUncertainty/blob/master/readme.md) but I'm struggling to understand how it can be implemented.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
