### ISSUE TITLE
how to predict input in variable length using mxnet_predict-all api

### ISSUE THREAD

**Issue by vsooda** [apache/incubator-mxnet#3864]
Use **mxnet_predict-all.cc** is very convenient to make the model run in smart device. 

In my project (speech synthesis), I had used dnn to predict the output. But the input is with **variable length**.

 I had not found api for this type input, so I predict the output one by one... In fact, it is very slow.  The code is like this: 

```cpp
std::vector <std::vector<float>> DnnttsPredictor::process(std::vector <std::vector<float>> labData) {
        std::vector <std::vector<float>> outputs;
        for (int i = 0; i < labData.size(); i++) {
            std::vector<float> dnnOneInput = labData[i];
            MXPredSetInput(predictor_, "data", dnnOneInput.data(), dnnOneInput.size());
            MXPredForward(predictor_);
            mx_uint outputIndex = 0;
            std::vector<float> dnnOneOutput(outputDim_);
            MXPredGetOutput(predictor_, outputIndex, &(dnnOneOutput[0]), outputDim_);
            outputs.push_back(dnnOneOutput);
        }
        return outputs;
    }
```

I want to know if mxnet have something like `placeholder` in tensorflow in mxnet c api. If no, how to make it more efficient. Use bucket?

Thank you!

**Comment by VoVAllen** [comment]
There is a bucket io to deal with variable length
http://mxnet.io/how_to/bucketing.html

placeholder I think it's just mx.sym.Variable and you can feed in data by NDArrayIter if you want

**Comment by vsooda** [comment]
@VoVAllen  many thanks. 

maybe what you said is about **trainning**. but I need to process the data using raw c api in **tesing** time. there is not mx.sym.Variable  and NDArrayIter in it.

here is an predictor creating example:

```cpp
const mx_uint inputShapeData[4] = {1, 1, inputDim, 1};
//Create Predictor: predict an sample every time
MXPredCreate(jsonDataString.c_str(),
             paramDataString.c_str(),
             static_cast<size_t>(paramDataString.length()),
             devType,
             devId,
             numInputNodes,
             inputKeys,
             inputShapeIndptr,
             inputShapeData,
             &predictor_);
```

the problem is that, I have **not a determine number** when I construct the predictor. so I set the number to 1

thank you

**Comment by feiyulv** [comment]
Do you use the rnn/lstm, and the network changes with the variable length input? Or just the like the fully-cnn, only input varies, network(json) keeps the same? The first situation is not easy to deal in C++. Only way  I can figure out is to construct the network in C++ code, like this [https://github.com/dmlc/MXNet.cpp](url)

**Comment by feiyulv** [comment]
@vsooda Sorry to reply this so late. Have you fix this problem? For variable input inference, creating a predictor handle for each input is time consuming. You can create a max shape executor as the shared executor at first, then bind with the shared executor for each input, this maybe a little faster, but will have to write a lot of code in c++. Hope this will give you a little help

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
