### ISSUE TITLE
Auto generated Scala Package API docs

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#3869]
We are using "Doxygen" to auto-generate API docs for CPP package. http://mxnet.io/doxygen/
This is very helpful for developers and power users of mxnet.

We need something similar for Scala and R packages.
For Scala package, there is not out of box support from Doxygen. May be we should use "scaladoc"?

Feedback and suggestions from the community is welcome.

**Comment by piiswrong** [comment]
@Ldpe2G @javelinjs Any ideas?

**Comment by Ldpe2G** [comment]
@javelinjs Any ideas?

**Comment by javelinjs** [comment]
The scaladoc is not working because of the maven settings. I'm considering to fix it, or if we use sbt it might be easier to make it work.

**Comment by andremoeller** [comment]
Merged in: https://github.com/dmlc/mxnet/pull/3879

http://mxnet.io/api/scala/
http://mxnet.io/api/scala/docs/index.html#package

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
