### ISSUE TITLE
Android amalgamation mxnet_predict-all.cc: cblas error when execute forward function

### ISSUE THREAD

**Issue by fengshikun** [apache/incubator-mxnet#3870]
When execute the line "p->exec->Forward(false);":
```
int MXPredForward(PredictorHandle handle) {
  MXAPIPredictor* p = static_cast<MXAPIPredictor*>(handle);
  API_BEGIN();
  p->exec->Forward(false);
  API_END();
}
```

There will generate cblas error:

```
 ** On entry to SGEMM  parameter number 13 had an illegal value
 ** On entry to SGEMM  parameter number 13 had an illegal value
 ** On entry to SGEMM  parameter number 13 had an illegal value
 ** On entry to SGEMM  parameter number 13 had an illegal value
 ** On entry to SGEMM  parameter number 13 had an illegal value

```
Because i use five convolution layer in network, so i guess perhaps this error relate to the cblas function `cblas_sgemm` which do the matrix multiplication. Anyone can help me? Thanks!

**Comment by nihilityworld** [comment]
I have the same problem.

**Comment by martin-frbg** [comment]
@nihilityworld are you using OpenBLAS or some other implementation ? On the OpenBLAS side https://github.com/xianyi/OpenBLAS/issues/1014 was created but we did not receive further details.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
