### ISSUE TITLE
What rpc framework is used in Mxnet

### ISSUE THREAD

**Issue by nilbody** [apache/incubator-mxnet#3876]
What RPC framework is used in Mxnet ? Does Mxnet implement RPC by self ? 
Where is the RPC code of Mxnet ?

Thanks

**Comment by piiswrong** [comment]
zeromp

**Comment by tqchen** [comment]
Strictly no rpc is used yet . Data passing in pslite uses zeromq.but can be switched to other backends

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
