### ISSUE TITLE
Expandable sidebars are collapsed by default

### ISSUE THREAD

**Issue by andremoeller** [apache/incubator-mxnet#3888]
Now it requires multiple clicks to expand the sidebars to see the page layout.

**Comment by piiswrong** [comment]
@kevinthesun

**Comment by leopd** [comment]
We can certainly start with 1 level open by default on all pages.  Sometimes it will make sense to have more than that -- ideally this should be configurable on a page-by-page basis, maybe with a line of script, but I'm not sure how to express this in markdown.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
