### ISSUE TITLE
Mxnet.io doc problem

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#3912]
1. On this page, the API dropdown in headline doesn't work 
http://mxnet.io/tutorials/python/mnist.html#

2. Unfinished content in http://mxnet.io/api/python/io.html#extension-multiple-labels-for-a-single-image

**Comment by skrish13** [comment]
Is the (source of) doc also available on the git repo to edit? If yes, would love to get the link :D

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
