### ISSUE TITLE
cudaMalloc failed: out of memory while training fcn32s

### ISSUE THREAD

**Issue by GoalQ** [apache/incubator-mxnet#3913]
My device is TitanX(Maxwell) and dataset is VOC2012.When I run run_fcns.sh,it will raise Error: cudaMalloc failed: out of memory.So,I set cut_off_size = 400 and I get the same error.At last , I changes cut_off_size = 300 and it woks.I want to know why mxnet's fcnxs costs much more GPU memory than caffe.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
