### ISSUE TITLE
im2rec 各个文件里存放了每一类的图片

### ISSUE THREAD

**Issue by nsy3694** [apache/incubator-mxnet#3914]
建立自己的数据的时候，如果我的图片不是每个类别一个文件夹，而是所有图片都在一个文件夹中，类别标签由单独的文本文件保存，那么如何使用im2rec.py生成自己的数据，还有image.lst中integer_image_index是做什么用的，感觉有类别有路径不就够了么

**Comment by xzqjack** [comment]
1. 按照mxnet的格式制作自己的图像标签文本就可以了；
2.  integer_image_index应该就是单纯的索引，可以用来用于检测错误等吧。

**Comment by jinfagang** [comment]
@nsy3694 大神球分像个代码啊，im2rec把makelist合并到一起去了，我每一类也是单独放在一个文件夹里面，然后所有类放在了train/ 下面，用im2rec怎么生成啊，我把root设置成了***/train 貌似报错啊
```
Traceback (most recent call last):
  File "im2rec.py", line 207, in <module>
    make_list(args)
  File "im2rec.py", line 57, in make_list
    chunk = image_list[i * chunk_size:(i + 1) * chunk_size]
TypeError: slice indices must be integers or None or have an __index__ method

```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
