### ISSUE TITLE
auto_module_index.js doesn't work properly

### ISSUE THREAD

**Issue by kevinthesun** [apache/incubator-mxnet#3915]
Some changes made in API pages, for example, changing the link content of left sidebar, makes auto_module_index.js failed. Now some entries such as "Symbol Creation API Reference" has no child level any more.

**Comment by piiswrong** [comment]
try bisecting?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
