### ISSUE TITLE
There are two predictions when a picture  run twice. Why?

### ISSUE THREAD

**Issue by kyocen** [apache/incubator-mxnet#3920]
### There are two predictions when a picture run twice
I train a OCR model use CNN net,when I predict a pic one time, the result is correct，but run twice,the first is correct and the second is wrong.
***

code:

    batch_size = 1
    sym, arg_params, aug_params= mx.model.load_checkpoint("ocr", 0)
    data_shape = [("data", (batch_size, 3, 50, 200))]
    input_shapes = dict(data_shape)
    sym = getnet()
    executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        if key in arg_params:
            arg_params[key].copyto(executor.arg_dict[key])

    executor.forward(is_train = False, data = mx.nd.array([img]))
    probs = executor.outputs[0].asnumpy()
    
    a=np.argmax(probs[0])
    b=np.argmax(probs[2])
    print a,b

***
when run

 testRecognizeOne("0.jpg")
 testRecognizeOne("0.jpg")

***
the output:
2,3
0,0

why?

**Comment by kyocen** [comment]
@piiswrong @xlvector

**Comment by xlvector** [comment]
Strange, can you print probs?

**Comment by kyocen** [comment]
@xlvector the second probs is wrong
*** 
(3L, 35L)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
None
(3L, 35L)
[ 0.02857143  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143
  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143
  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143
  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143
  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143
  0.02857143  0.02857143  0.02857143  0.02857143  0.02857143]

**Comment by akturtle** [comment]
Hi @kyocen, you give a new network to sym by getnet(). Is this network the same as which u load from model before?

**Comment by kyocen** [comment]
@akturtle I remove some symbol about “label“. The problem makes me  puzzled .

**Comment by akturtle** [comment]
what if put all the samples in the same batch?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
