### ISSUE TITLE
What unit test have for rnn?

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#3924]
@mli  @piiswrong , do you have unit test operator for rnn so far?

**Comment by piiswrong** [comment]
I don't think so

**Comment by sxjscience** [comment]
@zhenlinluo We've created a higher-level API for RNN. See https://github.com/dmlc/mxnet/issues/3930

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
