### ISSUE TITLE
About SequenceLast symbol and asnumpy() Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ZiJianZhao** [apache/incubator-mxnet#3937]
```Python
def MLP():
    data=mx.sym.Variable("data")
    length=mx.sym.Variable("length")
    fc1=mx.sym.FullyConnected(data=data,num_hidden=3)
    fc2=mx.sym.FullyConnected(data=fc1,num_hidden=3)
    hidden=mx.sym.Concat(fc1,fc2,dim=0)
    last=mx.sym.SequenceLast(
        data=hidden,
        use_sequence_length=True,
        sequence_length=length
    )
    returnmx.sym.Group([fc1,fc2,hidden,last])

mlp=MLP()
input_shapes={"data":(1,1),"length":(3,)}
executor=mlp.simple_bind(ctx=mx.cpu(),grad_req='null',**input_shapes)
#Initial
arg_arrays=dict(zip(mlp.list_arguments(),executor.arg_arrays))
init=mx.init.Uniform(scale=1)
for name, arr in arg_arrays.items():
    if name not in input_shapes:
        init(name,arr)

executor.arg_dict["data"][:]=np.array([[1]])
executor.arg_dict["length"][:]=np.array([0,0,1])
executor.forward()printmx.nd.zeros((1,2)).asnumpy()
for i in executor.outputs:
    print i.asnumpy()
```
I write this simple code to test the new symbol SequenceLast, but something strange happens. 
If I just call the SequenceLast with only the data argument, all is well.
But if I call the SequenceLast like above, when 
```
print i.asnumpy()
```
 it reports following mistake:
> Segmentation fault (core dumped) 

Look forward to your reply! Thanks.

**Comment by pluskid** [comment]
Please note that according to [the doc](http://mxnet.io/api/python/symbol.html#mxnet.symbol.SequenceLast), `SequenceLast` takes input of the shape `(max_seq_len, batch_size, fea_dim)`, however, `FullyConnected` produces output of shape `(batch_size, fea_dim)`. I guess this is the source of the seg fault.

**Comment by piiswrong** [comment]
Still it should fail gracefully.
@sbodenstein

**Comment by sbodenstein** [comment]
@piiswrong: agreed. Fix in #3940

**Comment by ZiJianZhao** [comment]
OK! Thanks.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
