### ISSUE TITLE
OpenCV3 in installing MXNet on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by tianqig** [apache/incubator-mxnet#3944]
I am going to install MXNet/Python on a Mac based on the installation steps from http://mxnet.io/get_started/setup.html#standard-installation. 

But  I already have  OpenCV3 installed with Homebrew. 

**Q1.** Can I use my installed OpenCV3 for MXNet  installation?

If I can, then do I need to make some change from the standard installation procedures?

**Q2.** If I have to use OpenCV2.4 for MXNet, can I  install OpenCV 2.4 with Homebrew? 
Wonder  if this may cause some problems because of two OpenCV of different versions are installed by Homebrew.

Not sure if this is the right place to ask the question, please help

Thanks

**Comment by piiswrong** [comment]
you can use opencv3

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
