### ISSUE TITLE
(Question) Slow calculation and mulit thread issues (pyhton)

### ISSUE THREAD

**Issue by ZahlGraf** [apache/incubator-mxnet#3947]
Hi,

for learning reasons, I implement the stochastic gradient descent by myself with mxnet.
Basically I do in my learning loop the following steps:

1. Select a sample from the learning data by random
2. Copy it to the executor memory
3. do forward calculation
4. calculate head gradient
5. do backward calculation
6. adapt weights of executor

I iterate this code around 50000 times and it takes around 15 seconds on my computer.
15 seconds does not sound much, however if I need to search 50 different arguments for the best fit with 10-fold-crossvalidation, then we talk about around 2 hours of training time. And this is bad.

I guess the internal learning algorithms from the library are much faster, but by using them there is only little I can learn. 
I also notices, that it really does not matter how many samples are calculated per iteration. If I calculate for validation 200 samples in the same loop, does not increase the learning time much, as long as I copy the data just once to the test-executor-memory. So setting up the memory for the train executor seems to be costly here, not the calculation of the executor. 

Does anyone has an idea how to speed up my learning? 

I also tried to learn different arguments (learning-rate, regularization rate) on different threads at the same time. Here every thread has its own training and test executors and writes only local data. So they should not share any resources. However I got race condition errors and the threads slows down it calculation enormously when running in parallel. So I guess even by using different executors, they have some kind of shared resource by mxnet?

I would be happy if someone can give me some hints about multi-threading with mxnet.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
