### ISSUE TITLE
When I compiled mxnet with the ssd example, I got erro :

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#3948]
3>     正在创建库 E:/opensource/mxnet-master/build/Debug/libmxnet.lib 和对象 E:/opensource/mxnet-master/build/Debug/libmxnet.exp
3>multibox_detection.obj : error LNK2019: 无法解析的外部符号 "class mxnet::Operator * __cdecl mxnet::op::CreateOp<struct mshadow::gpu>(struct mxnet::op::MultiBoxDetectionParam,int)" (??$CreateOp@Ugpu@mshadow@@@op@mxnet@@YAPEAVOperator@1@UMultiBoxDetectionParam@01@H@Z)，该符号在函数 "public: virtual class mxnet::Operator * __cdecl mxnet::op::MultiBoxDetectionProp::CreateOperatorEx(struct mxnet::Context,class std::vector<class mxnet::TShape,class std::allocator<class mxnet::TShape> > *,class std::vector<int,class std::allocator<int> > *)const " (?CreateOperatorEx@MultiBoxDetectionProp@op@mxnet@@UEBAPEAVOperator@3@UContext@3@PEAV?$vector@VTShape@mxnet@@V?$allocator@VTShape@mxnet@@@std@@@std@@PEAV?$vector@HV?$allocator@H@std@@@7@@Z) 中被引用
3>multibox_prior.obj : error LNK2019: 无法解析的外部符号 "class mxnet::Operator * __cdecl mxnet::op::CreateOp<struct mshadow::gpu>(struct mxnet::op::MultiBoxPriorParam,int)" (??$CreateOp@Ugpu@mshadow@@@op@mxnet@@YAPEAVOperator@1@UMultiBoxPriorParam@01@H@Z)，该符号在函数 "public: virtual class mxnet::Operator * __cdecl mxnet::op::MultiBoxPriorProp::CreateOperatorEx(struct mxnet::Context,class std::vector<class mxnet::TShape,class std::allocator<class mxnet::TShape> > *,class std::vector<int,class std::allocator<int> > *)const " (?CreateOperatorEx@MultiBoxPriorProp@op@mxnet@@UEBAPEAVOperator@3@UContext@3@PEAV?$vector@VTShape@mxnet@@V?$allocator@VTShape@mxnet@@@std@@@std@@PEAV?$vector@HV?$allocator@H@std@@@7@@Z) 中被引用
3>multibox_target.obj : error LNK2019: 无法解析的外部符号 "class mxnet::Operator * __cdecl mxnet::op::CreateOp<struct mshadow::gpu>(struct mxnet::op::MultiBoxTargetParam,int)" (??$CreateOp@Ugpu@mshadow@@@op@mxnet@@YAPEAVOperator@1@UMultiBoxTargetParam@01@H@Z)，该符号在函数 "public: virtual class mxnet::Operator * __cdecl mxnet::op::MultiBoxTargetProp::CreateOperatorEx(struct mxnet::Context,class std::vector<class mxnet::TShape,class std::allocator<class mxnet::TShape> > *,class std::vector<int,class std::allocator<int> > *)const " (?CreateOperatorEx@MultiBoxTargetProp@op@mxnet@@UEBAPEAVOperator@3@UContext@3@PEAV?$vector@VTShape@mxnet@@V?$allocator@VTShape@mxnet@@@std@@@std@@PEAV?$vector@HV?$allocator@H@std@@@7@@Z) 中被引用
3>cuda_compile_1_generated_convolution.cu.obj : error LNK2019: 无法解析的外部符号 cudnnConvolutionBackwardFilter_v3，该符号在函数 "public: virtual void __cdecl mxnet::op::CuDNNConvolutionOp<float>::Backward(struct mxnet::OpContext const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<enum mxnet::OpReqType,class std::allocator<enum mxnet::OpReqType> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &)" (?Backward@?$CuDNNConvolutionOp@M@op@mxnet@@UEAAXAEBUOpContext@3@AEBV?$vector@VTBlob@mxnet@@V?$allocator@VTBlob@mxnet@@@std@@@std@@11AEBV?$vector@W4OpReqType@mxnet@@V?$allocator@W4OpReqType@mxnet@@@std@@@6@11@Z) 中被引用
3>cuda_compile_1_generated_deconvolution.cu.obj : error LNK2001: 无法解析的外部符号 cudnnConvolutionBackwardFilter_v3
3>cuda_compile_1_generated_convolution.cu.obj : error LNK2019: 无法解析的外部符号 cudnnConvolutionBackwardData_v3，该符号在函数 "public: virtual void __cdecl mxnet::op::CuDNNConvolutionOp<float>::Backward(struct mxnet::OpContext const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<enum mxnet::OpReqType,class std::allocator<enum mxnet::OpReqType> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &,class std::vector<class mxnet::TBlob,class std::allocator<class mxnet::TBlob> > const &)" (?Backward@?$CuDNNConvolutionOp@M@op@mxnet@@UEAAXAEBUOpContext@3@AEBV?$vector@VTBlob@mxnet@@V?$allocator@VTBlob@mxnet@@@std@@@std@@11AEBV?$vector@W4OpReqType@mxnet@@V?$allocator@W4OpReqType@mxnet@@@std@@@6@11@Z) 中被引用
3>cuda_compile_1_generated_deconvolution.cu.obj : error LNK2001: 无法解析的外部符号 cudnnConvolutionBackwardData_v3
3>E:\opensource\mxnet-master\build\Debug\libmxnet.dll : fatal error LNK1120: 5 个无法解析的外部命令

**Comment by poorfriend** [comment]
I use cudnn V5, should I use v3?

**Comment by piiswrong** [comment]
v5 is fine. You are not linking agains cudnn library. Where did you install it? See if you can find it in path

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
