### ISSUE TITLE
problem with CNN for text classification with multiple convolutional layers

### ISSUE THREAD

**Issue by morphos30** [apache/incubator-mxnet#3954]
Dear all,

I would like to create a CNN for text classification with multiple convolutional layers.

Here is my code, but I am lost when I want to do the second convolutional layer.

    input_x = mx.sym.Variable('data') # this is a set of sentences, each sentence is composed of DNA letters (A,T,G,C or N)
    input_y = mx.sym.Variable('softmax_label') # label for each sentence

   num_embed=5 #(A,T,G,C or N)
   batch_size=50
   sentence_size=100
   filter_size=8

    embed_layer = mx.sym.Embedding(data=input_x, input_dim=num_embed, output_dim=num_embed, name='vocab_embed')
    conv_input = mx.sym.Reshape(data=embed_layer, shape=(batch_size, 1, sentence_size, num_embed)) # output shape=(50,1,100,5)
    
   # 1st convolutional layer
   conv1 = mx.sym.Convolution(data=conv_input, kernel=(filter_size, num_embed), num_filter=num_filter) # output shape should be (50,100,93,1), no? I don't know how to check the output shape.
   relu1 = mx.sym.Activation(data=conv1, act_type='relu')
   pooled1 = mx.sym.Pooling(data=relu1, pool_type='max', kernel=(3, 1), stride=(3,1)) # output shape should be (50,100,31,1), no?

   # 2nd convolutional layer: i would like to convert shape (50,100,31,1) in shape (50,1,31,100), so that I could rerun convolution on it, but i don't know how to do at all!!! ???

Thanks in advance
Raphael

**Comment by pluskid** [comment]
Maybe this help? http://mxnet.io/api/python/symbol.html#mxnet.symbol.SwapAxis

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
