### ISSUE TITLE
error when running "predict-with-pretrained-model.ipynb"

### ISSUE THREAD

**Issue by huanyu-liao** [apache/incubator-mxnet#3961]
I have not GPU envrionment, so use CPU for this example.

I change this line : ctx = mx,cpu();
model = mx.model.FeedForward.load(prefix, num_round, ctx=mx.cpu(), numpy_batch_size=1)

then get the error infomation.

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-4-ee7dbb5b02b9> in <module>()
      2 prefix = "inception-bn/Inception-BN"
      3 num_round = 126
----> 4 model = mx.model.FeedForward.load(prefix, num_round, ctx=mx.cpu(), numpy_batch_size=1)

C:\Users\leo\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.pyc in load(prefix, epoch, ctx, **kwargs)
    832         - ``prefix-epoch.params`` will be saved for parameters.
    833         """
--> 834         symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
    835         return FeedForward(symbol, ctx=ctx,
    836                            arg_params=arg_params, aux_params=aux_params,

C:\Users\leo\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.pyc in load_checkpoint(prefix, epoch)
    361     - parameters will be loaded from ``prefix-epoch.params``.
    362     """
--> 363     symbol = sym.load('%s-symbol.json' % prefix)
    364     save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
    365     arg_params = {}

C:\Users\leo\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.pyc in load(fname)
    956         raise TypeError('fname need to be string')
    957     handle = SymbolHandle()
--> 958     check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
    959     return Symbol(handle)
    960 

C:\Users\leo\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: Failed loading Op conv_1 of type Convolution: Cannot find argument 'cudnn_off', Possible Arguments:
----------------
kernel : Shape(tuple), required
    convolution kernel size: (y, x)
stride : Shape(tuple), optional, default=(1,1)
    convolution stride: (y, x)
dilate : Shape(tuple), optional, default=(1,1)
    convolution dilate: (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for convolution: (y, x)
num_filter : int (non-negative), required
    convolution filter(channel) number
num_group : int (non-negative), optional, default=1
    Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace : long (non-negative), optional, default=512
    Tmp workspace for convolution (MB).
no_bias : boolean, optional, default=False
    Whether to disable bias parameter.

**Comment by piiswrong** [comment]
please update to latest master

**Comment by pfornia** [comment]
@huanyu-liao did that fix your problem? I'm working off the newest version and getting the same error. Tried both 0.9.3 and 0.9.3a

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
