### ISSUE TITLE
problem with bi-lstm-sort example 

### ISSUE THREAD

**Issue by Jiakui** [apache/incubator-mxnet#3965]
According to bi-lstm-sort example readme, it's said that we need to generate the data first: 

_Firstly, generate data by:
    cd data
	python gen_data.py_

But I can not find the corresponding file for generating training data. Can anybody fix this problem ?

**Comment by Jiakui** [comment]
@xlvector

**Comment by xlvector** [comment]
gen_data.py only need to generate a file , with every line is space spearated numbers like :

34 56 78 9 1 23
45 23 98 11 73 24 90
1 5 2 7 8
.......

If you solve this problem, you can submit a PR.

**Comment by gurumurthys** [comment]
Refer to https://github.com/dmlc/mxnet/issues/2783

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
