### ISSUE TITLE
the value of executor.arg_dict["bn_conv1_gamma"] is different in different position of one iteration

### ISSUE THREAD

**Issue by animebing** [apache/incubator-mxnet#3967]
I use the symbol.simple_bind to train the network batch by batch, below is the code snippet

 exe = self.symbol.simple_bind(ctx=self.ctx, **input_shapes)
 for batch in train_data:
      exe.forward(is_train=True)
      exe.backward()
      print "before"
      print exe.arg_dict['bn_conv1_gamma'].asnumpy()
      
      for i, pair in enumerate(zip(exe.arg_arrays, exe.grad_arrays)):
            weight, grad = pair
            if i==3:
                  print "arr_arrays"
                  print weight.asnumpy()
                  print "arg_dict"
                  print exe.arg_dict['bn_conv1_gamma'].asnumpy()
                  
      self.updater(i, grad, weight)

where 'bn_conv1_gamma' is the 3rd(from 0) of self.symbol.list_arguments(), i found that the value of exe.arg_dict['bn_conv1_gamma'].asnumpy() is different in different position, which really confused me.

**Comment by piiswrong** [comment]
why do you mean different position

**Comment by animebing** [comment]
@piiswrong I "print exe.arg_dict['bn_conv1_gamma'].asnumpy()" in two positions. As I write in the code, one is below "print before", the other is below "print arg_dict", but the value is different.

**Comment by piiswrong** [comment]
if you are using fix_gamma=True for bn then it's normal. the BN layer is just forcing it to be 1

**Comment by animebing** [comment]
@piiswrong thanks a lot, i find "fix_gamma=True" is default for mx.symbol.BatchNorm, but i can't understand what you mean by "it is normal", can you explain more about why the value is different?

I am also curious about when the value of exe.arg_arrays and exe.arg_dict will be updated, it seems that they are not updated after exe.forward or exe.backward, which really confuses me. thank you again

**Comment by chimengxian** [comment]
Maybe this page can help you for using executor. :)
https://github.com/dmlc/mxnet/blob/bcc28dfb547eb8c6f7b414fa9c94269933f778a4/example/notebooks/simple_bind.ipynb

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
