### ISSUE TITLE
 example/cpp/image classfication can not work in Windows

### ISSUE THREAD

**Issue by SureD** [apache/incubator-mxnet#4000]
##compile sucessfully but found same runtime error for processing images"

D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\dmlc-core\includ
e\dmlc/logging.h:235: [12:42:16] d:\program files (x86)\jenkins\workspace\mxnet\
mxnet\src\operator\./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Inc
orrect shape[2]: (1,320,15,24). (first input shape: (1,576,16,25))

**Comment by piiswrong** [comment]
Looks like you are using inception?
Please use latest mxnet code and updated symbols from data.mxnet.io/models

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
