### ISSUE TITLE
Differences/simliarity  between mxnet's runtime dependency engine and neon's transformer?

### ISSUE THREAD

**Issue by fengyuleidian0615** [apache/incubator-mxnet#4008]
Quite new to mxnet and neon, so the question might sound naive, but it puzzles me recently.

In mexnet, runtime dependency engine do the tricky things of scheduling parallel computing tasks, which is the key difference from other ML/DL libs. While a quick glance of transformer from [ngraph](https://github.com/NervanaSystems/ngraph) , it seems this component based on [llvm](http://www.aosabook.org/en/llvm.html)  do the optimization with the same effect. 

Didn't jump into the code yet, but in essence, what's the differences and similarity of those two components from mxnet and neon?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
