### ISSUE TITLE
numpy indexing and symbolic shapes

### ISSUE THREAD

**Issue by mujjingun** [apache/incubator-mxnet#4009]
I want to slice a (50 x N x 1) symbolic tensor to (50 x N - 1 x 1), and as far as I see, there's no way to do that without knowing the exact value of N at definition time. You must know N at symbol definition time, or otherwise you can't to the "discard 1 row" operation. This is very easy to do in Theano, you just have to do `tensor[:, :-1]`. 

Also I found that there are no symbolic shapes in MXNet, which is surprising because it's very useful to do operations with them a lot of the time. What I mean by "symbolic shapes" is that when you do `tensor.shape` where tensor is a symbol, it returns a symbolic tuple containing symbolic integers lazily evaluated at runtime.

So I request:
1. numpy indexing for symbolic tensors
2. symbolic shapes to do symbolic operations with.

**Comment by zhreshold** [comment]
+1 for runtime shape inference symbol.
Creating such kind of symbol is easy, however, current Ops must change behaviors according to "shape" or "axis", etc. More specifically, Ops that take "shape-like" parameters must take into consideration more inputs including symbolic shape.

I was thinking about something like:
```
shape = mx.symbol.SymbolicShape(data=data)
a = mx.symbol.Variable(name="xxx", symbolic_shape=shape)
b = mx.symbol.SliceChannel(symbolic_num_outputs=shape[1])
```

Variable, Crop, ROIPooling, Reshape, SliceChannel, SpatialTransformer, broadcast_axis, broadcast_to, expand_dims, normal, slice_axis, sum, sum_axis, uniform.
Roughly there are 10+ Ops to be affected. So it's not a simple task.

**Comment by tqchen** [comment]
This is not yet possible because the shape inference is done during graph initialization time, instead of runtime to give better memory planning. We might include alternative executor later, to support dynamic runtime shaping. But there is always a tradeoff between what is provided vs what can be optimized

**Comment by mujjingun** [comment]
Then is this possible at least?

`mx.symbol.slice_axis(x, axis=1, begin=0, end=-1)`

The `end` is -1, which indicates the last element like in python.

**Comment by tqchen** [comment]
yes, this should be possible by using our shape inference function

**Comment by sxjscience** [comment]
@mujjingun See the discussion of the convention of axis here https://github.com/dmlc/mxnet/issues/3660

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by zanbri** [comment]
I'd like to reopen this issue as I still don't see a general solution for how to slice a symbol to the shape of another symbol. Previously, there was the `Crop()` function which allowed for this to be done, but it has been depreciated for some reason.

How should `slice()` be used to perform the action of `Crop()`?
