### ISSUE TITLE
Loss increase when running another program on same GPU

### ISSUE THREAD

**Issue by zmonoid** [apache/incubator-mxnet#4018]
I tried to run the following program on my GTX980
https://github.com/zmonoid/mxdqn

When running one instance, everything works perfectly. 
However, when running anther instance, the first one's loss will increase to NAN very fast, so does the second one.

What may be the cause of this problem, is this a known problem?

**Comment by sxjscience** [comment]
@zmonoid Seems to be related to https://github.com/dmlc/mxnet/issues/1720. May be related to `choose_element_0index`?

**Comment by zmonoid** [comment]
@sxjscience 
Exactly! I tried to do it in numpy and there is no such problem anymore!
But what may be the cause of such probem?

**Comment by zmonoid** [comment]
I tried to run `choose_element_0index` with context `mx.cpu()`, still the same problem.
I guess there should be some problem with this file?
https://github.com/dmlc/mshadow/blob/master/mshadow/extension/choose.h

**Comment by zmonoid** [comment]
@sxjscience 
Add `mx.nd.waitall()` after `choose_element_0index` will solve this problem.
But will also decrease the speed.

**Comment by zmonoid** [comment]
Not really... Still diverge at last

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
