### ISSUE TITLE
output is wrong when set state_outputs=True for RNN layer

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#4019]
@piiswrong  and others, 

I change example/rnn/rnn_cell_demo.py to get 3 ouputs. The changes as below. 
        rnn = mx.sym.RNN(data=embed_tm, state_size=num_hidden,
                         num_layers=num_lstm_layer, mode='lstm',
                         name='LSTM', 
                         # The following params can be omitted
                         # provided we do not need to apply the
                         # workarounds mentioned above
                         state=rnn_h_init,
                         state_cell=rnn_c_init, 
                         parameters=rnn_params,
                         state_outputs=**True**)
        hidden = mx.sym.Reshape(data=rnn**[0]**, shape=(-1, num_hidden))

However, it report the error as below:
mxnet/mxnet_cuda/dmlc-core/include/dmlc/logging.h:235: [19:58:58] src/symbol/static_graph.cc:488: Check failed: it != grad_map.end() bad graph: Cannot find node LSTM's 1-th output

Can someone help to check what's wrong in graph?

**Comment by piiswrong** [comment]
what's rnn.list_outputs()?

**Comment by sxjscience** [comment]
You need to also include `rnn[1]` when constructing the executor, like `BlockGrad(rnn[1])`.

**Comment by zhenlinluo** [comment]
rnn.list_output() shows ['LSTM_output', 'LSTM_state', 'LSTM_state_cell']

@sxjscience  can you provide more details how to include rnn[1] to replace below? My intention is to get point of rnn[0/1/2] separately then do operation. 

hidden = mx.sym.Reshape(data=rnn[0], shape=(-1, num_hidden))

**Comment by sxjscience** [comment]
I find that the RNN layer requires all the output nodes for calculating the gradient. Our final symbol should be something like
```python
rnn = mx.sym.RNN(..., mode='lstm', ..., state_outputs=True)
your_loss = f(rnn)
net = mx.sym.Group([your_loss, mx.sym.BlockGrad[rnn[1]], mx.sym.BlockGrad[rnn[2]]])
```
However, I think it's not so convenient.
Similar thing holds for the `SliceChannel` operator, i.e, we need to include all the outputs when building the executor.
I think we should find a way to solve this. @piiswrong Do you know whether NNVM provides a way to solve the problem?

**Comment by piiswrong** [comment]
I think this is fixed in nnvm. @tqchen COuld you confirm?

**Comment by sxjscience** [comment]
I've tried using the SliceChannel. Should be fixed in nnvm.

**Comment by zhenlinluo** [comment]
But how about in current version w/o nnvm? 

@sxjscience  could you help to write a runnable example code?

**Comment by sxjscience** [comment]
@zhenlinluo Yes. I'll continue working on the example after meeting with my supervisor tomorrow.

**Comment by zhenlinluo** [comment]
@sxjscience  how is going on?

**Comment by WellyZhang** [comment]
Guys, I've got a similar problem using ```SliceChannel``` in the latest version of NNVM.

The problem arises in partial grouping. Example code shown below:

```python
import mxnet as mx

data0 = mx.sym.Variable("data0")

group = mx.sym.SliceChannel(data0, num_outputs=4, axis=1)

output0 = group[0]
output1 = group[1]
output2 = group[2]
output3 = group[3]

group_again = mx.sym.Group([output0, output1, output2])#, output1, output2, output3, output4, 
                            #output5, output6])


exe = group_again.simple_bind(ctx=mx.gpu(), data0=(10, 4))
```
Error trackback:
```python
[21:06:59] /home/data/czhangbr/mxnet/dmlc-core/include/dmlc/./logging.h:235: [21:06:59] src/pass/infer_shape_type.cc:118: Check failed: finfer != nullptr Attribute FInferShape is not registed by op _NoGradient
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-1-c718a24b7bc9> in <module>()
     15 
     16 
---> 17 exe = group_again.simple_bind(ctx=mx.gpu(), data0=(10, 4))

/home/data/czhangbr/anaconda2/lib/python2.7/site-packages/mxnet/symbol.pyc in simple_bind(self, ctx, grad_req, type_dict, group2ctx, **kwargs)
    717         executor = self.bind(ctx, arg_ndarrays,
    718                              grad_ndarrays, grad_req, aux_ndarrays,
--> 719                              group2ctx=group2ctx)
    720         return executor
    721 

/home/data/czhangbr/anaconda2/lib/python2.7/site-packages/mxnet/symbol.pyc in bind(self, ctx, args, args_grad, grad_req, aux_states, group2ctx, shared_exec)
    848                                          aux_args_handle,
    849                                          shared_handle,
--> 850                                          ctypes.byref(handle)))
    851         executor = Executor(handle, self, ctx, grad_req, group2ctx)
    852         executor.arg_arrays = args

/home/data/czhangbr/anaconda2/lib/python2.7/site-packages/mxnet/base.pyc in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise MXNetError(py_str(_LIB.MXGetLastError()))
     76 
     77 if sys.version_info[0] < 3:

MXNetError: [21:06:59] src/pass/infer_shape_type.cc:118: Check failed: finfer != nullptr Attribute FInferShape is not registed by op _NoGradient
```

**Comment by zhenlinluo** [comment]
@sxjscience  @piiswrong Do you have chance to take a look at this and provide a example ASAP?  I need this to implement RNN layer based seq2seq model.

**Comment by dsqx71** [comment]
In nnvm,  mx.sym.RNN has an error:  

src/operator/./cudnn_rnn-inl.h:191: Check failed: req[rnn_enum::kState] != kAddTo (3 vs. 3) AddTo is not supported for state

However, I didn't set grad_req  as 'add'.

**Comment by sxjscience** [comment]
@zhenlinluo I'm too busy with my phd qualifying exam these days... May look into this after I complete it.

**Comment by sxjscience** [comment]
We've switched to gluon (http://gluon.mxnet.io/). Also, this problem has been solved in the lastest MXNet.
