### ISSUE TITLE
How to save model if using a low level training loop?

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#4022]
I follow this https://github.com/dmlc/mxnet/blob/master/example/notebooks/tutorial.ipynb to train my own model. But I get confused about how to save my model. I know one way is set up a model when I want to save. But is there a better way to do this?

**Comment by piiswrong** [comment]
mx.model.save_checkpoint('save', 1, exec.sym, exec.arg_arrays, exec.aux_arrays)

**Comment by akturtle** [comment]
@piiswrong  Thanks a lot. I think this should be added to the example.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
