### ISSUE TITLE
C++ image classification of GPU data

### ISSUE THREAD

**Issue by dtmoodie** [apache/incubator-mxnet#4026]
Hi,
From looking at the C++ image classification example, it looks like there is no way of signifying that the data already resides on the GPU.  
I would like to access the very low level elements of mxnet through a C++ api such that I can load directly into the input gpu tensor and read from the output gpu tensor.  I would also like access to the streams so I can correctly utilize streams in my application.
Currently this looks possible, but on windows a fair bit of the mxnet api is not decorated for dll export.
Has anyone else run into this issue?

**Comment by piiswrong** [comment]
What exactly do you want to do? You shouldn't need to worry about streams since mxnet does parallelization automatically

**Comment by dtmoodie** [comment]
For the purposes of inference, I have a GPU based acquisition and pre-processing pipeline.  I'd like that pipeline to dump data directly into the inputs to an mxnet network and either synchronizing my pre-processing stream or share a stream with the mxnet inference stream.  I also would like to control the GPU parallelism because I currently parallelize pre-processing pipelines across GPUs.  Thus each GPU would have its own network.

**Comment by piiswrong** [comment]
That's very hacky.
I recommend do a copy. Have you verified that a single copy is the bottleneck?
Also you can use mxnet for your acquisition. Check out mx.image in the nnvm branch. You can do fast image io with mxnet

**Comment by dtmoodie** [comment]
I'll test it out, I've put a lot of work into making sure everything works asynchronously and it pains me a little to have to stop a stream, copy everything to the cpu, then copy everything back to the gpu for asynchronous operation within mxnet.

**Comment by piiswrong** [comment]
You don't need to copy back to cpu.
It should be relatively easy to add a c_api for creating an NDArray given pointer to gpu data.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
