### ISSUE TITLE
Feeding video frames data into LSTM 

### ISSUE THREAD

**Issue by ngmanhei** [apache/incubator-mxnet#4036]
I am new to MXNET. I have a video dataset, in which each video has different length of frames. I want to use LSTM to train a feature descriptor of the video. For each moment of LSTM, the input is one frame of the video. Is there anyone who can show me an easy way to feed video frame data to LSTM ?
Any suggest will be appreciated.

**Comment by sxjscience** [comment]
@ngmanhei You can flatten the input to a 1D tensor. Another choice is to use ConvLSTM.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
