### ISSUE TITLE
Link address typo on python data loading api

### ISSUE THREAD

**Issue by kevinthesun** [apache/incubator-mxnet#4040]
On http://mxnet.io/api/python/io.html#parameters-for-data-iterator page, some links such as:
https://github.com/dmlc/mxnet/tree/master/doc/tools/im2rec.cc, are incorrect.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
