### ISSUE TITLE
Build error with CUDA build

### ISSUE THREAD

**Issue by sanjeevm0** [apache/incubator-mxnet#4041]
I am seeing following error when trying to build with CUDA support.  Same error shows up when trying to build CUDA docker container.

g++ -std=c++11 -DMSHADOW_FORCE_STREAM -Wall -O3 -I/root/mxnet/mshadow/ -I/root/mxnet/dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/root/mxnet/mshadow/ -I/root/mxnet/dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
In file included from /root/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:9:
/root/mxnet/mshadow/mshadow/./base.h:242:13: error: conflicting declaration 'typedef int cudnnTensorFormat_t'
 typedef int cudnnTensorFormat_t;
             ^
In file included from /root/mxnet/mshadow/mshadow/./base.h:152:0,
                 from /root/mxnet/mshadow/mshadow/tensor.h:16,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:9:
/usr/include/cudnn.h:146:3: error: 'cudnnTensorFormat_t' has a previous declaration as 'typedef enum cudnnTensorFormat_t cudnnTensorFormat_t'
 } cudnnTensorFormat_t;
   ^
In file included from /root/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:9:
/root/mxnet/mshadow/mshadow/./base.h:325:50: error: invalid conversion from 'int' to 'cudnnTensorFormat_t' [-fpermissive]
   static const cudnnTensorFormat_t kCudnnFlag = -1;
                                                  ^
/root/mxnet/mshadow/mshadow/./base.h:335:50: error: invalid conversion from 'int' to 'cudnnTensorFormat_t' [-fpermissive]
   static const cudnnTensorFormat_t kCudnnFlag = -1;
                                                  ^
/root/mxnet/mshadow/mshadow/./base.h:347:50: error: invalid conversion from 'int' to 'cudnnTensorFormat_t' [-fpermissive]
   static const cudnnTensorFormat_t kCudnnFlag = -1;
                                                  ^
/root/mxnet/mshadow/mshadow/./base.h:357:50: error: invalid conversion from 'int' to 'cudnnTensorFormat_t' [-fpermissive]
   static const cudnnTensorFormat_t kCudnnFlag = -1;
                                                  ^
make: *** [build/src/resource.o] Error 1

**Comment by SpecialM2580** [comment]
I encountered the problem too...Have you solved it @sanjeevm0 ?

**Comment by SpecialM2580** [comment]
@sanjeevm0 I update my cuDNN version to v5 , and it shows no more error. You may try it.

**Comment by ouceduxzk** [comment]
updating to v5 does not work for me on centos. Compiles fine without cudnn.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
