### ISSUE TITLE
Master frozen until v0.9 release. Please redirect pull requests to nnvm branch

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#4044]
We are freezing the master branch until v0.9 release. With the exception of changes limited to docs/ folder, all pull requests should be redirected to the nnvm branch. 

v0.9 is currently under development in the nnvm branch. It contains many new features and a major refactor to move the backend to nnvm. Development is almost completed, we now need to add more tests to ensure nothing breaks.

Specifically, we would like to add around 50% of the examples to "maintained" examples, which means we will add automatic tests for them. An example is here: https://github.com/dmlc/mxnet/blob/master/example/image-classification/test_score.py

Training takes too long to test so I think we can just train for a few iterations to make sure the code works but doesn't need to verify convergence. We can probably train to convergence once every month or so.

Tests should pass on both master and nnvm without modification so that we can be confident there is no break.

Here is a tentative list of tasks to be completed before 0.9 release:
- [ ] verify that distributed training works. Maybe add it to test. Simulation on a single machine is probably good enough @tqchen @mli
- [ ] add test for rcnn @winstywang @precedenceguo 
- [ ] add test for ssd @zhreshold 
- [ ] add some rnn models to test @pluskid @antinucleon 
- [ ] add dcgan to test @tqchen 
- [ ] add neural style to test @antinucleon @leopd 
- [ ] add speech-demo to test @pluskid @antinucleon @yzhang87 
- [ ] add caffe module to test @cjolivier01 @HrWangChengdu 
- [ ] add torch module to test @piiswrong
- [ ] test optimizer @piiswrong

Please feel free to add more

We should also manually go through the rest of the examples to make sure they run on nnvm branch.

**Comment by pluskid** [comment]
1. For examples that takes too long to train, I think we can store a subset of the training data (for a few batches only) and run the training, record the training behavior. And then in the test we check the training behavior are approximately the same as the expected one for a few batches. However, I guess this might not be very helpful for some of the larger models which is more difficult to train, and takes a lot of epochs to start converging.

2. "list of tasks to be completed before 0.9 release": just want to clarify, those developments are on the nnvm branch and those are long term goals target the NEXT release, right?

**Comment by tqchen** [comment]
Please formalize the test folder structure, for the examples.

**Comment by piiswrong** [comment]
@pluskid No, these are short term goals we need to finish ASAP in order to rollout the 0.9 release soon.

**Comment by pluskid** [comment]
OK. "Rollout" means 0.9 becoming the master or 0.9 being released? I'm a bit confused.

**Comment by piiswrong** [comment]
merge in master.

**Comment by zhreshold** [comment]
What will be the test environment? The test build script need to be modified to allow extra operators before example ssd can be tested.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
