### ISSUE TITLE
Check failed: from.shape() == to->shape() operands shape mismatch

### ISSUE THREAD

**Issue by liuxialong** [apache/incubator-mxnet#4049]
```
class DataIter(mx.io.DataIter):
    def __init__(self, batch_size, item2idx, user2idx, cnt_day):
        super(DataIter, self).__init__()
        self.batch_size = batch_size
        self.item2idx = item2idx
        self.user2idx = user2idx
        self.day_list = get_file_list(cnt_day)
        self.provide_data = [('user', (batch_size, 1)),
                             ('item', (batch_size, 1))]
        self.provide_label = [('score', (self.batch_size, 1))]

    def __iter__(self):
        batch_user = []
        batch_item = []
        batch_label = []
        for file_name in self.day_list:
            for line in open(file_name,'r'):
                if len(line.strip().split(' ')) != 3: continue
                user, item, rating = line.strip().split(' ')
                if user not in self.user2idx or item not in self.item2idx: continue
                user = self.user2idx[user]
                item = self.item2idx[item]
                batch_user.append(user)
                batch_item.append(item)
                batch_label.append(float(rating))

                if len(batch_user) == self.batch_size:
                    data_all = [mx.nd.array(batch_user), mx.nd.array(batch_item)]
                    label_all = [mx.nd.array(batch_label)]
                    data_names = ['user', 'item']
                    label_names = ['score']
                    # clean up
                    batch_user = []
                    batch_item = []
                    batch_label = []
                    yield SimpleBatch(data_names, data_all, label_names, label_all)

    def reset(self):
        pass


class SimpleBatch(object):
    def __init__(self, data_names, data, label_names, label):
        self.data = data
        self.label = label
        self.data_names = data_names
        self.label_names = label_names

    @property
    def provide_data(self):
        return [(n, x.shape) for n, x in zip(self.data_names, self.data)]

    @property
    def provide_label(self):
        return [(n, x.shape) for n, x in zip(self.label_names, self.label)]

def get_one_layer_mlp(hidden, k, max_user, max_item):
    # input
    user = mx.symbol.Variable('user')
    item = mx.symbol.Variable('item')
    score = mx.symbol.Variable('score')
    # user latent features
    #user = mx.symbol.Embedding(data = user, input_dim = max_user, output_dim = k)
    user = mx.symbol.Embedding(data = user, input_dim = max_user, output_dim = k)
    user = mx.symbol.Activation(data = user, act_type='relu')
    user = mx.symbol.FullyConnected(data = user, num_hidden = hidden)
    # item latent features
    #item = mx.symbol.Embedding(data = item, input_dim = max_item, output_dim = k)
    item = mx.symbol.Embedding(data = item, input_dim = max_item, output_dim = k)
    item = mx.symbol.Activation(data = item, act_type='relu')
    item = mx.symbol.FullyConnected(data = item, num_hidden = hidden)
    # predict by the inner product
    pred = user * item
    pred = mx.symbol.sum_axis(data = pred, axis = 1)
    pred = mx.symbol.Flatten(data = pred)
    # loss layer
    pred = mx.symbol.LinearRegressionOutput(data = pred, label = score)
    return pred

def main():
    data_train = DataIter(batch_size, context.item2idx, context.user2idx, cnt_day)

    net2 = get_one_layer_mlp(hidden_cnt, embedding_len, len(context.user2idx), len(context.item2idx))

    model = mx.model.FeedForward(
        ctx = [mx.cpu(0)], 
        symbol = net2,
        num_epoch = num_epoch,
        optimizer = 'adam',
        learning_rate = learning_rate,
    )

    model.fit(X = data_train,
              eval_metric = 'rmse'
              )

```
I still can't find where is the problem. Can anyone help me?

  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 811, in fit
    sym_gen=self.sym_gen)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 236, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 410, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 257, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 93, in _load_data
    _load_general(batch.data, targets)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 89, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 533, in copyto
    return _internal._copyto(self, out=other)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 1225, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [07:56:44] src/ndarray/ndarray.cc:231: Check failed: from.shape() == to->shape() operands shape mismatch

**Comment by Ldpe2G** [comment]
try 
self.provide_data = [('user', (batch_size)),
                             ('item', (batch_size))]
        self.provide_label = [('score', (self.batch_size))]

**Comment by liuxialong** [comment]
@Ldpe2G 
I solve the problem by change from 
```
                batch_user.append(user)
                batch_item.append(item)
                batch_label.append(float(rating))
```
to 
```

                batch_user.append([user])
                batch_item.append([item])
                batch_label.append([float(rating)])
```

It works now. But I don't know why it works.

**Comment by nitingupta2** [comment]
I get the same error in the mxnet R package

Error in eval(expr, envir, enclos) : 
  [20:18:29] D:\chhong\mxnet\src\ndarray\ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

Here's my sessionInfo()

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mxnet_0.7         Matrix_1.2-7.1    dplyr_0.5.0       visdat_0.0.4.9800 ggplot2_2.2.0

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
