### ISSUE TITLE
About running image_segmentation.py, for image with size 500*281 the program crashed

### ISSUE THREAD

**Issue by liyin2015** [apache/incubator-mxnet#4056]
Here is the error output: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
The error happened in exector.forward(is_train=False).

I tried some other images, some succeed. It seems that it has a problem with feeding in different image size

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
