### ISSUE TITLE
error when compiling using clang-omp on mac

### ISSUE THREAD

**Issue by artzers** [apache/incubator-mxnet#4070]
My mac system is osx 10.11 and  I brew install clang-omp 
I change mxnet configure that cc = clang-omp and CXX = clang-omp++. when compiling mxnet there are many errors. Part of them are shown below:
clang-omp++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -msse2 -o line_split.o src/io/line_split.cc
In file included from src/io/line_split.cc:2:
In file included from include/dmlc/io.h:8:
/usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/../include/c++/v1/cstdio:125:9: error: no member
      named 'FILE' in the global namespace
using ::FILE;
      ~~^
/usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/../include/c++/v1/cstdio:126:9: error: no member
      named 'fpos_t' in the global namespace
using ::fpos_t;

**Comment by piiswrong** [comment]
clang omp is not supported

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
