### ISSUE TITLE
Making mxnet/examples compatible for python2/3

### ISSUE THREAD

**Issue by jostep** [apache/incubator-mxnet#4071]
This is inspired by the issue #3995  as most examples in mxnet/examples still only support python2. 

currently, common incompatible issues in the mxnet/examples are:
1. print 
2. raise errors.
3. urllib
4. StringIO
5. iterator
6. dict keys to list.

@leopd  I realized you planned to work on this. Let me know your opinions on this.
I will try to create a pr for each compatibility update for each example.
Please let me know if there are any questions or concerns.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
