### ISSUE TITLE
weird out of memory error on GPU/slowdown on CPU

### ISSUE THREAD

**Issue by szilard** [apache/incubator-mxnet#4074]
I got back to benchmarking various DL tools on the airline dataset https://github.com/szilard/benchm-ml

For this use case I use fully connected networks, though I cannot reach the accuracy of GBMs, even after extensive tuning https://github.com/szilard/benchm-ml#deep-neural-networks

I've experimented with this before and that's when I suggested mxnet to implement sparse features https://github.com/dmlc/mxnet/issues/773

I know this is still in the works https://github.com/dmlc/mxnet/issues/1524

However, now with the larger EC2 GPU instances I can try to run the larger dataset (10M rows) with the dense representation (now it will fit in RAM with 1-hot encoding, which was not the case before).

For comparison, the 1M dataset is fast: 35 sec on p2.xlarge (1 GPU) and 70 sec on r3.8xlarge (CPU 32 cores).

On the 10M dataset, however:

on p2.8xlarge (using 1 GPU only):
```
[06:17:48] /home/ubuntu/mxnet/dmlc-core/include/dmlc/./logging.h:235: [06:17:48] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
[06:17:48] /home/ubuntu/mxnet/dmlc-core/include/dmlc/logging.h:235: [06:17:48] src/engine/./threaded_engine.h:306: [06:17:48] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:17:48] src/engine/./threaded_engine.h:306: [06:17:48] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)
```

while on r3.8xlarge (CPU 32 cores) it runs for about 1 hour, i.e. 100x more time then on 1M dataset.

How can this be?

For GPU I would expect same memory usage since I'm doing mini-batches (of 128).

For CPU I would expect 10x runtime, not 100x.

Any ideas?

Code here: https://github.com/szilard/benchm-ml/blob/master/4-DL/2-mxnet.R

**Comment by piiswrong** [comment]
try USE_MKL2017 and USE_MKL_EXPERIMENTAL in config.mk for cpu performance

**Comment by szilard** [comment]
@piiswrong That would require MKL. But I doubt the problem is with MKL. There are 2 problems above:

1. GPU out-of-memory (while mini-batches are of same size, so why?)

2. CPU 100x slower on 10x data. Since last post I tried out keras with Tensorflow backend it's 10x train time on 10x data (not 100x). 

Any ideas why 1 and 2 above?

**Comment by piiswrong** [comment]
```
USE_MKL2017 = 1
USE_MKL2017_EXPERIMENTAL = 1
```
try this

**Comment by szilard** [comment]
OK, would that help w the GPUs or just CPU?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
