### ISSUE TITLE
are there some tutorials for distributed training with kubernetes

### ISSUE THREAD

**Issue by pineking** [apache/incubator-mxnet#4103]
are there some tutorials for distributed training with kubernetes?

**Comment by zihaolucky** [comment]
Same question.

**Comment by piiswrong** [comment]
@mli

**Comment by mli** [comment]
not yet, you can try to implement a kubernetes tracker in https://github.com/dmlc/dmlc-core/tree/master/tracker/dmlc_tracker it's fairly straightfoward

**Comment by pineking** [comment]
@mli Thanks for the link , I will have a try

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
