### ISSUE TITLE
error in im2rec.py Line 51

### ISSUE THREAD

**Issue by maxiaoyuelun** [apache/incubator-mxnet#4104]
Line 51:
if args.shuffle is True:
when use --shuffle=True, this line is false, just delete is True

**Comment by shuokay** [comment]
This bug is caused by `argparse`, I think a better way is
```python
if args.shuffle.upper() == "true":
```
and change the `parse_args()` accordingly:
```python
cgroup.add_argument('--shuffle', default="true", choices=["true", "false"], help='If this is set as True, \                              │                                                                                                                    
        im2rec will randomize the image order in <prefix>.lst')
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
