### ISSUE TITLE
why do not use etcd for distribute communication?

### ISSUE THREAD

**Issue by shendl1978** [apache/incubator-mxnet#4110]
Why do not use etcd for distribute communication?
Why create a special parameters server?
I think that etcd is very suitable for distribute communication.
Etcd has very good read performance and good write performance. 
We can use etcd to store meta-data.We can use etcd as a mq  server for async communication.
Peer to peer and topic all both supported by etcd.

**Comment by mli** [comment]
you can create a kvstore type with etcd as the backend. i'm not familar with etcd, i thought etcd's main feature is robustness, not performance

**Comment by shendl1978** [comment]
Etcd was designed for performance.The read performance is almost same as redis.The write performance is also pretty good,althogh it is poorer than redis.But redis was designed for cache,so redis does not guarantee persistence,but etcd guarantees.
The follow link is the etcd performance doc:
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/performance.md
So I think that etcd is suitable for mxnet.I will try to use etcd to replace kvstore for mxnet.

**Comment by criloz** [comment]
@samster25  any update?, is it possible to use etcd?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
