### ISSUE TITLE
do bucketing support variable length input for  bidirectional lstm?

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#4113]
It seems to use 0 padding to get fixed length in every bucket.
But bi-lstm needs 2 direction to input, could mxnet know the difference ?

**Comment by piiswrong** [comment]
@sbodenstein 
I think the masking and reverse layers does it

**Comment by xinghedyc** [comment]
@piiswrong Thanks a lot for your fast reply. I'll check it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
