### ISSUE TITLE
mxnet is much slower than caffe on android

### ISSUE THREAD

**Issue by perp** [apache/incubator-mxnet#4145]
I predict a face image  using Lightened CNN model on my android phone.
Mxnet on i5 machine is about 80ms
Caffe on i5 machine is about 75ms
Mxnet on android is about 700ms (OpenBLAS arm)
caffe on android is adbout 200ms (OpenBLAS arm)
So what is the root cause?

**Comment by dprylipko** [comment]
I have a similar issue, but MXnet is far behind both on powerful PC and on Raspberry PI. 
Namely, on PC I have 17.38ms per image for MXNet and around 4ms for Caffe. On Raspberry PI - 369.55ms per image for MXNet and 76.53ms for Caffe. The network is identical for both setups, I converted it from the Caffe model.

I am using MXNet.cpp API. The benchmark code looks like this:

```
        vector<float> img_data(img_size * batch_size, 0.5);
        img.SyncCopyFromCPU(img_data);
        NDArray::WaitAll();
        m_argsMap["data"] = img;

        Executor *executor =
            m_net.SimpleBind(global_ctx, m_argsMap, map<string, NDArray>(),
                             map<string, OpReqType>(), m_auxMap);

        CHECK_NOTNULL(executor);

        std::vector<long> timings;
        for (int i = 0; i < NUM_EVAL; ++i) {
            auto start = std::chrono::system_clock::now();

            executor->Forward(false);
            NDArray::WaitAll();
            auto end = std::chrono::system_clock::now();
            timings.push_back(
                std::chrono::duration_cast<std::chrono::milliseconds>(
                    end - start).count());
        }

        report_metrics(timings, batch_size);
```

Is it the correct way to measure the MXNet forward pass time?

**Comment by tornadomeet** [comment]
try to set your env like `export MXNET_ENGINE_TYPE=NaiveEngine` or try to rebuild mxnet with `MXNET_PREDICT_ONLY=1`, this will make predict faster about 2times.

**Comment by dprylipko** [comment]
When I compile MXNet with `ADD_CFLAGS = -DMXNET_PREDICT_ONLY=1` in config.mk, I am getting a segfault when running benchmark:
```
[10:44:24] src/engine/engine.cc:36: MXNet start using engine: NaiveEngine
Segmentation fault (core dumped)
```

If I use MXNet lib compiled without this flag, but use the env variable `export MXNET_ENGINE_TYPE=NaiveEngine`, the benchmark executes just fine, but I do not see any difference in the inference time.

Some more info: I am using OpenBLAS and CPU-only setup:
```
echo "USE_CUDA=0" >>config.mk
echo "USE_CUDNN=0" >>config.mk
echo "USE_BLAS=openblas" >>config.mk
echo "ADD_LDFLAGS += -lopencv_core -lopencv_imgproc -lopencv_imgcodecs" >>config.mk
```

**Comment by tornadomeet** [comment]
i'm not familiar with ARM, in may pc cpu, this indeed speed up. but it maybe due to your model, such as  model-size.

**Comment by perp** [comment]
@tornadomeet 
I have tested what you said above.in mxnet_predict-all.cc MXNET_PREDICT_ONLY macro is already set as true.
I used openblas in android and it is truly utilizing four cores of CPU fully.

the below is the time cost of convolution and dot cost on my android phone of lightened CNN model.

unpack_patch2col 2 cost:21.904 ms
unpack_patch2col 2 cost:146.750 ms
unpack_patch2col 2 cost:76.812 ms
unpack_patch2col 2 cost:37.764 ms
 
304ms in total
 
dot cost:10.211 ms
dot cost:63.549 ms
dot cost:61.920 ms
dot cost:21.202 ms
 
168ms in total
 
swapaxis cost:27.053 ms
swapaxis cost:6.774 ms
swapaxis cost:14.554 ms
swapaxis cost:7.757 ms
61ms in total             
 
                                                                                                                                                                                                            
533 ms

**Comment by ysh329** [comment]
Mark

**Comment by pby5** [comment]
mark

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
