### ISSUE TITLE
when I compile mxnet with cmake, an error occured

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#4146]
CMake Warning at D:/opencv3/build/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)

CMake Error at CMakeLists.txt:59 (find_package):
  Found package configuration file:

    D:/opencv3/build/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

**Comment by hjk41** [comment]
You are probably using a 32bit OpenCV and trying to compile a 64bit mxnet,
or vice versa. Make sure your OpenCV binary fits your chosen platform.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
