### ISSUE TITLE
How to extract features of an image  from a pretrained CNN model? and I try,  but get an error,mxnet.base.MXNetError: InferType Error in transpose0: [15:48:18] src/operator/operator_util.cc:402: At least one input type needs to be specified.

### ISSUE THREAD

**Issue by lji72** [apache/incubator-mxnet#4151]
I trained a CNN model and want to use the model to extract features of an specify image from a full connected layer. Here is the code:
     img = cv2.imread( "/******/code-release1.1_random_part/val/157wpot_68_0.jpg" ,     cv2.IMREAD_GRAYSCALE)
     img = img.reshape((1, 1, 64, 64)).astype("float32")
    img = np.multiply(img, 1/255.0)
    train_lbl =np.array([1], dtype="float32")
    print train_lbl.shape, train_lbl.dtype, img.dtype
    print type(train_lbl), type(train_lbl[0])
    testiter = mx.io.NDArrayIter(img, train_lbl, 1, shuffle=False)
    testiter.label =  mx.io._init_data(train_lbl, allow_empty=True, default_name='label')
    prefix = "cnn-ocr"
    iterator = 30
    model = mx.model.FeedForward.load(prefix, iterator)
    [prob, data1, label1] = model.predict(testiter, return_data=True)   
    
then, I meet the strange error.like this:

 File "lstm_ocr_part.py", line 392, in <module>
    [prob, data1, label1] = model.predict(testiter, return_data=True)   
  File "../../python/mxnet/model.py", line 616, in predict
    self._init_predictor(data_shapes, type_dict)
  File "../../python/mxnet/model.py", line 536, in _init_predictor
    self.ctx[0], grad_req='null', type_dict=type_dict, **dict(input_shapes))
  File "../../python/mxnet/symbol.py", line 685, in simple_bind
    arg_types, _, aux_types = self.infer_type(**type_dict)
  File "../../python/mxnet/symbol.py", line 417, in infer_type
    ctypes.byref(complete)))
  File "../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferType Error in transpose0: [15:48:18] src/operator/operator_util.cc:402: At least one input type needs to be specified.

 If you can give some advice, I will be very glad.

**Comment by longwoo** [comment]
refer to
 'https://github.com/dmlc/mxnet-notebooks/blob/master/python/how_to/predict.ipynb'

**Comment by lji72** [comment]
@longwoo  Thanks very much!

**Comment by lji72** [comment]
@longwoo  Hello,  guys, I try with the example, but it does not work and raise the error as below:
Traceback (most recent call last):
  File "lstm_ocr_part.py", line 433, in <module>
    mod.bind(for_training=False, data_shapes=[('data', (1,1,64,64))])
  File "../../python/mxnet/module/module.py", line 284, in bind
    grad_req=grad_req, input_types=input_types)
  File "../../python/mxnet/module/executor_group.py", line 191, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "../../python/mxnet/module/executor_group.py", line 231, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "../../python/mxnet/module/executor_group.py", line 454, in _bind_ith_exec
    assert arg_shapes is not None, "shape inference failed"
AssertionError: shape inference failed

Here is the code:
 sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, iterator)
    print sym, arg_params
    print aux_params
    mod = mx.mod.Module(symbol=sym, context=mx.gpu())
    mod.bind(for_training=False, data_shapes=[('data', (1,1,64,64))])
    mod.set_params(arg_params, aux_params)
    from collections import namedtuple
    Batch = namedtuple('Batch', ['data'])
    img = cv2.imread( "code-release1.1_random_part/val-300/157wpot_68_0.jpg" ,    cv2.IMREAD_GRAYSCALE)
    img = img.reshape((1, 64, 64)).astype("float32")
    img = img[np.newaxis, :]
    print img.shape
    img = np.multiply(img, 1/255.0)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
