### ISSUE TITLE
 An error occured when I complie mxnet in VS2013, could you tell me how to fix it 

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#4155]
2>  symbol.cc
2>     正在创建库 G:/OpenSource/mxnet/build/Release/libmxnet.lib 和对象 G:/OpenSource/mxnet/build/Release/libmxnet.exp
2>  正在生成代码
2>g:\opensource\mxnet\src\engine\threaded_engine.cc(298): fatal error C1001: 编译器中发生内部错误。
2>  (编译器文件“f:\dd\vctools\compiler\utc\src\p2\ehexcept.c”，第 956 行)
2>   要解决此问题，请尝试简化或更改上面所列位置附近的程序。
2>  请选择 Visual C++
2>  “帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
2>LINK : fatal error LNK1257: 代码生成失败

**Comment by kevinthesun** [comment]
Have you tried to install mxnet with prebuilt package?http://mxnet.io/get_started/setup.html#installing-the-prebuilt-package-on-windows

**Comment by poorfriend** [comment]
@kevinthesun thank you , it works

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
