### ISSUE TITLE
How to bind 3 inputs using mxnet.io.NDArrayIter?

### ISSUE THREAD

**Issue by fungtion** [apache/incubator-mxnet#4159]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler:python 2.7

Package used (Python/R/Scala/Julia):python

I want to feed the convolution net with triple input: image, annotation, label. According to #2929, I define the input using mxnet.io.NDArrayIter as:
```
import mxnet as mx
import numpy as np

train = mx.io.NDArrayIter(data=np.zeros((120000, 3, 224, 224), dtype='float32'), 
    label={'label1': np.zeros((120000, 81), dtype='int8'),
    'label2': np.zeros((120000, ), dtype='int8')}, 
    batch_size=10)
``` 

However, I got an error: **include/mxnet/./tensor_blob.h:742:check failed: (this->shape_.Size())==(shape.size()) TBlob.get_with_shape: new and old shape do not match total elements**   and
**TypeError: Invalid type'<type 'numpy.ndarray'> for data, should be NDArray or numpy.ndarray'**

Does it means data and label should match in shape? And how can I feed triple input (one data and two kinds of label) to network?

**Comment by kevinthesun** [comment]
I didn't get this error when running your code. Is this error arise from the latter codes? Basically you can use a list or a dict of ndarray for both data and label. http://mxnet.io/api/python/io.html#mxnet.io.NDArrayIter

**Comment by fungtion** [comment]
@kevinthesun I make a script only these codes above, it still reports this error

**Comment by kevinthesun** [comment]
@fungtion Can you paste the full traceback message for your error?

**Comment by fungtion** [comment]
@kevinthesun This is the traceback message:
```
/home/wfx/mxnet/dmlc-core/include/dmlc/logging.h:235: [07:54:27] include/mxnet/./tensor_blob.h:742: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
Traceback (most recent call last):
  File "/home/wfx/PycharmProjects/kb/mxnet_triple_input/tmp.py", line 7, in <module>
    train = mx.io.NDArrayIter(data=np.zeros((120000, 3, 224, 224), dtype='float32'),label={'label1': np.zeros((120000, 81), dtype='int8'), 'label2': np.zeros((120000, ), dtype='int8')},batch_size=10)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/io.py", line 420, in __init__
    self.data = _init_data(data, allow_empty=False, default_name='data')
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/io.py", line 391, in _init_data
    "should be NDArray or numpy.ndarray")
TypeError: Invalid type '<type 'numpy.ndarray'>' for data, should be NDArray or numpy.ndarray

Process finished with exit code 1
```

**Comment by shuokay** [comment]
I have implement triple input when doing image retrieval using triplet loss. I used DataIter instead of NDArrayIter, the followed code maybe give you a hint: 
```python
class DataBatch(object):
    def __init__(self, data, label):
        self.data = data
        self.label = label

class DataIter(mx.io.DataIter):
    def __init__(self, names, batch_size):
        super(DataIter, self).__init__()
        self.provide_data = [('same', (batch_size, 3, HEIGHT, WIDTH)),('diff', (batch_size, 3, HEIGHT, WIDTH)),('one', (batch_size, ))]
        self.provide_label = [('anchor', (batch_size, 3, HEIGHT, WIDTH))]
        self.started = True
        self.q = multiprocessing.Queue(4)
        self.pws = [multiprocessing.Process(target=self.write,) for i in range(2)]
        for pw in self.pws:
            pw.start()

    def write(self):
        while True:
            if not self.started:
                break
            batch = self.generate_batch(self.batch_size)
            batch_anchor = [x[0] for x in batch]
            batch_same = [x[1] for x in batch]
            batch_diff = [x[2] for x in batch]
            batch_one = np.ones(self.batch_size)
            data_all = [mx.nd.array(batch_same, ctx=dev), mx.nd.array(batch_diff, ctx=dev),mx.nd.array(batch_one, ctx=dev)]
            label_all = [mx.nd.array(batch_anchor, ctx=dev)]
            data_batch = DataBatch(data_all, label_all)
            self.q.put(data_batch)
    def next(self):
        if self.q.empty():
            logging.debug("waiting for data")
        if self.iter_next():
            return self.q.get(True)
        else:
            raise StopIteration
```

**Comment by kevinthesun** [comment]
@fungtion Is your mxnet package updated version? Since I have no problem to run your code. Also the traceback shows the exception position is in line 391 of io.py, which should be in line 397 in current version.

**Comment by fungtion** [comment]
@shuokay Thank you, I will try it later

**Comment by fungtion** [comment]
@kevinthesun I am sure that the path is the correct, and other operations I used in mxnet works well except this one. Can it be the problem of gcc, because I used gcc-4.8.2.

**Comment by kevinthesun** [comment]
@fungtion I'm wondering why traceback reported error at line 391 at io.py. This exception should be at line 397.

**Comment by fungtion** [comment]
@kevinthesun I tried this script in another machine with latest mxnet version, it worked without any problem. So I think there may be some problems about my compilation.

**Comment by fungtion** [comment]
@kevinthesun I reduce the numpy array size to 12000, it runs without error, but if I increase to 120000, it still report that error

**Comment by fungtion** [comment]
@shuokay where is the function generate_batch?

**Comment by dnaase** [comment]
I met the same error with newest mxnet version.

Here is my code to generate the error:

t1=mx.nd.array(np.zeros((12000, 3, 224, 224), dtype='float32'))
t2=mx.nd.array(np.zeros((120000, 3, 224, 224), dtype='float32'))

t1 is fine, but t2 will produce error msg like this:

MXNetError                                Traceback (most recent call last)
<ipython-input-144-d8e2679a845c> in <module>()
----> 1 t2=mx.nd.array(np.zeros((120000, 3, 224, 224), dtype='float32'))

/home/yaping/mxnet/python/mxnet/ndarray.pyc in array(source_array, ctx, dtype)
   1121             raise TypeError('source_array must be array like object')
   1122     arr = empty(source_array.shape, ctx, dtype)
-> 1123     arr[:] = source_array
   1124     return arr
   1125 

/home/yaping/mxnet/python/mxnet/ndarray.pyc in __setitem__(self, in_slice, value)
    269                 _internal._set_value(float(value), out=self)
    270             elif isinstance(value, (np.ndarray, np.generic)):
--> 271                 self._sync_copyfrom(value)
    272             else:
    273                 raise TypeError('type %s not supported' % str(type(value)))

/home/yaping/mxnet/python/mxnet/ndarray.pyc in _sync_copyfrom(self, source_array)
    342             self.handle,
    343             source_array.ctypes.data_as(ctypes.c_void_p),
--> 344             ctypes.c_size_t(source_array.size)))
    345 
    346     def _slice(self, start, stop):

/home/yaping/mxnet/python/mxnet/base.pyc in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise MXNetError(py_str(_LIB.MXGetLastError()))
     76 
     77 if sys.version_info[0] < 3:

MXNetError: [10:06:08] include/mxnet/././tensor_blob.h:243: Check failed: this->shape_.Size() == shape.Size() (18063360000 vs. 883490816) TBlob.get_with_shape: new and old shape do not match total elements

Another weird thing:
when I change the dtype from "float32" to "int32", t1 is still fine. but t2 never finished or throw error msg.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by anjishnu** [comment]
I just got this issue -

> TypeError: Invalid type '<type 'numpy.ndarray'>' for x_2, should be NDArray, numpy.ndarray or h5py.Dataset

I only seem get it when my array is > certain number of elements. I reduce my array size and the code seems to run fine. Is the suggested solution to write my own DataIter?

**Comment by anjishnu** [comment]
I am also using a network architecture like OP which takes in 2 streams as input.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by kalyc** [comment]
Hey @anjishnu thanks for submitting the issue. Were you able to resolve it?

**Comment by lanking520** [comment]
Close this issue due to the inactivity. Please feel free to reopen this if you are still facing the same problems.
