### ISSUE TITLE
what's correct way to stop the subprocess created by launcher.py

### ISSUE THREAD

**Issue by pineking** [apache/incubator-mxnet#4186]
In distributed experiments, for example:
```bash
../../tools/launch.py -n 2 -H hosts python train_mnist.py --kv-store dist_sync
```

when I press the `Ctrl+C`， the subprocess created by launcher.py still running
and must be killed manually by pid on each node (`kill -9 PID`).
what's the best way to stop the launcher.py, any ideas?

**Comment by piiswrong** [comment]
@mli

**Comment by infwinston** [comment]
I temporarily used the following command found in this [page](https://github.com/dmlc/mxnet/blob/master/docs/how_to/cloud.md) to kill all processes.
`cat hosts | xargs -I{} ssh -o StrictHostKeyChecking=no {} 'uname -a; pgrep python | xargs kill -9'
`
but I think it's not a good enough solution as all your python processes will be killed.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
