### ISSUE TITLE
I get this error"Check failed: p[0] == RecordIOWriter::kMagic  terminate called after throwing an instance of 'dmlc::Error'"

### ISSUE THREAD

**Issue by DeanDon** [apache/incubator-mxnet#4188]
I am tring transform caffe modul to mxnet,and transform the network construct,when I run the program,get this error:
"[11:14:29] include/dmlc/././logging.h:235: [11:14:29] src/recordio.cc:117: Check failed: p[0] == RecordIOWriter::kMagic 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:14:29] src/recordio.cc:117: Check failed: p[0] == RecordIOWriter::kMagic 
Aborted (core dumped)
"

**Comment by AIROBOTAI** [comment]
Has the problem been solved?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
