### ISSUE TITLE
错误	9	error MSB6006: “cmd.exe”已退出，代码为 1。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	mxnet

### ISSUE THREAD

**Issue by Lvhhhh** [apache/incubator-mxnet#4196]
i follow the instruction from http://mxnet.io/get_started/setup.html
using the thirdparty containing the opencv,openblas and cudnn v3
there is no problem using cmake
but the problem came when i compile the mxnet.cpp.
i dont know why it happens, anyone can help me?

**Comment by kevinthesun** [comment]
Are you using the prebuilt package?

**Comment by Lvhhhh** [comment]
yep. i replace the include,lib and python folk from the 20161125_mxnet_x64_gpu. but i try another time without replacing the folk. it comes to the same problem.

**Comment by Lvhhhh** [comment]
i try again. with an without replacing the include,lib and python folk from the 20161125_mxnet_x64_gpu. it has the same error:
错误	9	error MSB6006: “cmd.exe”已退出，代码为 1。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	mxnet

**Comment by Lvhhhh** [comment]
i know the problem!! because cuda is 7.5 and win10~i change the cuda to 8.0. this problem has been solved! thank you for your advice.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
