### ISSUE TITLE
Something wrong with dilate Conv

### ISSUE THREAD

**Issue by yetionyo** [apache/incubator-mxnet#4199]
I think there should be something wrong with the dilate Conv. I try to run this demo below, but an error raised:
src/engine/./threaded_engine.h:306: [16:51:50] /mxnet/mshadow/mshadow/././extension/pack_col2patch.h:51: Check failed: (sshape[1]) == (o_height * o_width * imshape.ProdShape(0, dstdim - 3)) PackColToPatchExp: src.size(1) mismatch

It should mean that I feed the net with wrong shape of data. But I can run this demo without part 1 or part 2, which means I should feed the net with proper data, because as you can see that the two parts would not change the shapes of input and output. So it's strange that why shape mismatch error will occur when combine the two parts.

Besides, the error occurs in the process of backward. If the data shape is improper, it should be more reasonable that the error occurs in the process of forward.

Traceback (most recent call last):
  File "train.py", line 189, in <module>
    epoch_end_callback=mx.callback.do_checkpoint("models/"))
  File "/home/mxnet/python/mxnet/model.py", line 806, in fit
    sym_gen=self.sym_gen)
  File "/home/mxnet/python/mxnet/model.py", line 227, in _train_multi_device
    executor_manager.backward()
  File "/home/mxnet/python/mxnet/executor_manager.py", line 418, in backward
    self.curr_execgrp.backward()
  File "/home/mxnet/python/mxnet/executor_manager.py", line 268, in backward
    texec.backward()
  File "/home/mxnet/python/mxnet/executor.py", line 147, in backward
    ndarray))
  File "/home/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

Code: 

    batch_size = 1
    length = 41000    
    shape = {
        "input": (batch_size, 1, 2, length),
        "label": (batch_size,  length)
    }
    net = mx.symbol.Variable(name="input")
    label = mx.symbol.Varible(name="label")

    #---------------------part 1--------------------------#
    zero_0 = mx.sym.Variable(name='zero_0')
    shape['zero_0'] = (batch_size, 1, 2, 1)
    concat_0 = mx.sym.Concat(*[zero_0, net], dim=3, name='concat_0')
    net = mx.sym.Convolution(data=concat_0, kernel=(1, 2), stride=(1, 1), num_filter=1)
    #-----------------------------------------------------#
    
    #---------------------part 2--------------------------#
    zero_1 = mx.sym.Variable(name='zero_1')
    shape['zero_1'] = (batch_size, 1, 2, 2)
    concat_1 = mx.sym.Concat(*[zero_1, net], dim=3, name='concat_1')
    net = mx.sym.Convolution(data=concat_1, kernel=(1, 2), dilate=(1, 2), stride=(1, 1), num_filter=1)
    #-----------------------------------------------------#
    
    net = mx.symbol.Convolution(data=net, kernel=(2, 1), num_filter=5, name="post-conv")
    net = mx.symbol.SoftmaxOutput(data=net, label=label, name="softmax", multi_output=True)

**Comment by piiswrong** [comment]
kernel and dilate size need to be the same for w, h
(1, 2 ) is invalid

**Comment by yetionyo** [comment]
@piiswrong  Thank you for reply. Do you mean when I use dilate conv, I should set the parameter like "kernel=(2,2), dilate=(2,2)" ? But I can run this demo by deleting part 1 without any errors, that means the conv(kernel=(1,2), dilate=(1,2)) in part 2 can actually work. And it should make sense that only do dilate conv in one direction (kernel=(1,2), dilate=(1,2)), for example the wavenet.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
