### ISSUE TITLE
Detailed traceback information on exception

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#4206]
We need to have more detailed traceback on errors and exceptions. For example in this questions on stackoverflow - http://stackoverflow.com/questions/41096590/mxnet-build-model-error-on-r

Error message is very abstract - Error in mx.io.internal.arrayiter(as.array(data), as.array(label), unif.rnds, : basic_string::_M_replace_aux

It is difficult for users to understand that the issues is related to mismatch in index value when creating a matrix or any shape of a data structure.

Example of similar issue and fix in Tensorflow package - https://github.com/rstudio/tensorflow/pull/42

**Comment by piiswrong** [comment]
Yeah. If you look for issues with "Unclear Error/Doc" you can find some examples.
Let's do this after (or while) we add examples to API docs.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
