### ISSUE TITLE
Is there are any one to share ImageNet(Current, 1K，ILSVRC 2012 etc) rec and lst file?

### ISSUE THREAD

**Issue by lincolneejdk** [apache/incubator-mxnet#4211]
Dear all:

As the original dataset is too large and downloading process is not reliable, is there anyone willing to share the Imagenet rec and lst file? Data files for ILSVRC 2012 dataset, Imagenet 1K is also ok. Thank you very much.

**Comment by chaseadams509** [comment]
I am also trying to get Imagenet 1K rec and lst files, but am having not much luck other than seeing this: https://mxnet.incubator.apache.org/tutorials/vision/large_scale_classification.html

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by marcoabreu** [comment]
Please use the forum for this question.
