### ISSUE TITLE
How to convert SSD caffemodel to mxnet

### ISSUE THREAD

**Issue by oyxhust** [apache/incubator-mxnet#4217]
I want convert a SSD caffemodel to mxnet. I have tried the caffe_converter to deal with deplopy.prototxt and SSD caffemodel, but I get errors:

Traceback (most recent call last):
  File "convert_model.py", line 110, in <module>
    main()
  File "convert_model.py", line 37, in main
    prob, input_dim = proto2symbol(args.caffe_prototxt)
  File "/home/ubuntu/mxnet/tools/caffe_converter/convert_symbol.py", line 194, in proto2symbol
    sym, output_name, input_dim = proto2script(proto_file)
  File "/home/ubuntu/mxnet/tools/caffe_converter/convert_symbol.py", line 169, in proto2script
    raise Exception('Unknown Layer %s!' % layer[i].type)
Exception: Unknown Layer Normalize!

**Comment by zhreshold** [comment]
This is not yet supported by mxnet converter, see https://github.com/zhreshold/mxnet-ssd/issues/29
Several issues made it not that easy to convert directly from protobufs.
Be patient before I can come up with a better way to handle it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by sampathchanda** [comment]
@zhreshold Is there an update on this one yet ?
