### ISSUE TITLE
bind fail for the GPU RNN operator

### ISSUE THREAD

**Issue by ykim362** [apache/incubator-mxnet#4226]
Hi,

I have some trouble to run simple RNN operator test code in GPU.
Below code fails when it binds.

The error message is as below.

Could you please help to make it running?

Thanks,

# Error message

[ec2-user@ip-10-0-0-12 unittest]$ python test_operator_rnn.py
['data', 'LSTM_bias', 'LSTM_init_h', 'LSTM_init_c']
[(2L, 4L, 3L), (304L,), (2L, 4L, 4L), (2L, 4L, 4L)]
[(2L, 4L, 4L)]
[18:44:59] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:44:59] src/symbol/graph_executor.cc:578: Check failed: graph_.InferNodeShapes(topo_order_, &out_shapes, &aux_shapes, false) Shape inference cannot be complete in bind
Traceback (most recent call last):
  File "test_operator_rnn.py", line 185, in <module>
    test_lstm()
  File "test_operator_rnn.py", line 174, in test_lstm
    args_grad=grad_dict)#, LSTM_init_h=init_hc_shape, LSTM_init_c=init_hc_shape)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 844, in bind
    ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:44:59] src/symbol/graph_executor.cc:578: Check failed: graph_.InferNodeShapes(topo_order_, &out_shapes, &aux_shapes, false) Shape inference cannot be complete in bind
[18:44:59] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:44:59] /home/ec2-user/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
[18:44:59] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:44:59] /home/ec2-user/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:44:59] /home/ec2-user/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed

# Code

def test_lstm():
    seq_length = 2
    batch_size = 4
    num_hidden = 4
    num_lstm_layer = 2
    input_size = 3

    init_hc_shape = (num_lstm_layer, batch_size, num_hidden)
    data_shape = (seq_length, batch_size, input_size)
    bias_shape = (4*num_hidden*(input_size+num_hidden+2)+(num_lstm_layer - 1)*(4*num_hidden*(2*num_hidden+2)),)

    inp_shapes = {'data':data_shape}
    inp_shapes['LSTM_init_h'] = init_hc_shape
    inp_shapes['LSTM_init_c'] = init_hc_shape
    inp_shapes['LSTM_bias'] = bias_shape

    # param_shape = ()
    # data = np.random.random(data_shape)
    # data = [('data', data_shape)]
    init_h = [('LSTM_init_h', init_hc_shape)]
    init_c = [('LSTM_init_c', init_hc_shape)]

    data = mx.sym.Variable("data")
    rnn_h_init = mx.sym.Variable('LSTM_init_h')
    rnn_c_init = mx.sym.Variable('LSTM_init_c')
    rnn_params = mx.sym.Variable('LSTM_bias')
    # rnn_params = mx.sym.Variable(mx.symbol.norm(scale=0.1, shape=(4*num_hidden*(num_hidden+num_hidden+2)*num_layers),), name="LSTM_bias")

    grad_dict = {}
    ddata = mx.nd.empty(data_shape)
    grad_dict['data'] = ddata;
    dLSTM_init_h = mx.nd.empty(init_hc_shape)
    grad_dict['LSTM_init_h'] = dLSTM_init_h;
    dLSTM_init_c = mx.nd.empty(init_hc_shape)
    grad_dict['LSTM_init_c'] = dLSTM_init_c;
    dLSTM_bias = mx.nd.empty(bias_shape)
    grad_dict['LSTM_bias'] = dLSTM_bias;

    rnn_native = mx.sym.RNN(data=data, state_size=num_hidden,
                         num_layers=num_lstm_layer, mode='lstm',
                         name='LSTM', 
                         # The following params can be omitted
                         # provided we do not need to apply the
                         # workarounds mentioned above
                         state=rnn_h_init,
                         state_cell=rnn_c_init, 
                         parameters=rnn_params)

    arg_names = rnn_native.list_arguments()
    print arg_names

    arg_shape, out_shape, aux_shape = rnn_native.infer_shape(**inp_shapes)
    arg_dict = dict(zip(arg_names, [mx.nd.ones(shape, ctx=mx.gpu()) for shape in arg_shape]))

    print arg_shape
    print out_shape

    # embed = mx.sym.Embedding(data=data, input_dim=in_dim, output_dim=out_dim, name="embed")
    rnn_test = rnn_native.bind(ctx=mx.gpu(), args=arg_dict,
                                args_grad=grad_dict)#, LSTM_init_h=init_hc_shape, LSTM_init_c=init_hc_shape)
    # forward
    rnn_test.forward()
    print(rnn_test.outputs[0].asnumpy())

**Comment by tangyuq** [comment]
Any update on this issue? I am  also looking for a working example of mx.sym.RNN along with a correct way of corporating RNN with mxnet.io.DataBatch(data, label, pad=None, index=None, bucket_key=None, provide_data=None, provide_label=None) and/or the right BucketDataIter/PrefetchingIter.

The new mx.sym.RNN looks great but there is little document on how to use it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
