### ISSUE TITLE
does Warp-CTC support bucketing?

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#4234]
I try to use bucketing lstm and Warp-CTC to do OCR task, 
and I find the output never update when training,
However if I only use one bucket the output works fine. 
So I doubt  whether Warp-CTC could use in a bucketing way?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
