### ISSUE TITLE
training process becomes zombie process and keeps occupying GPU memory

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#4242]
My training program creates a child process for data IO while the model(mx.model.FeedForward) is running in the parent process. But for some unknown reason, I just find the parent process becomes a zombie process which keeps occupying the GPU memory.  The child process(for io) is still running background and can be killed.

When I run `nvidia-smi` in cmd-line, part of the displayed message is 
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=====================================================================|
|    0     31794    C   Unknown Error                                 5371MiB |
|    1      7653    C   python                                        5369MiB |
|    1     13386    C   /xx/xxx/caffe             1205MiB |
|    1     27707    C   Unknown Error                                 1011MiB |
|    2     18049    C   python                                        5809MiB |
|    3     11827    C   python                                        6169MiB |
+-----------------------------------------------------------------------------+

It seems that two different processes (31794 and 27707) became zombies at the same time (`top -p 31794/27707` shows the process's state is "Z").

BTW, the parent of these two zombie processes is init(pid=1) now.
Anyone seen this before? Is it possible to clear them and release the GPU memory without rebooting?

------------
## Environment info
Operating System: Ubuntu 16.04 LTS

Compiler: GCC 5.3

Package used (Python/R/Scala/Julia): Python

Or if installed from source: Yes

MXNet commit hash (`git rev-parse HEAD`): 2fefed4692007a34197df655f4e54db8942eb4ab

Python version and distribution: Python 2.7

**Comment by inflation** [comment]
The system should take care of the process, as well as nvidia-smi. You can try to soft-reset the GPU. But it will also affect other processes.

**Comment by nicklhy** [comment]
@inflation , can you explain the details about the "soft-reset"?
I thought a process should be cleared by init even if its parent does not do that.
My problem seems to be something crashed in CUDA and result an "Unknown Error" which prevents the process exiting normally.

**Comment by inflation** [comment]
@nicklhy Well, I never encountered those problems. You can try rmmod + insmod nvidia.ko. But this will also stop everything running on the GPU at that time.

**Comment by nicklhy** [comment]
@inflation , already tried your soft-reset method. But I failed to rmmod nvidia(nvidia_uvm).
```
sudo rmmod nvidia_uvm
(rmmod: ERROR: Module nvidia_uvm is in use)
sudo rmmod nvidia_uvm
(rmmod: ERROR: Module nvidia_uvm is in use)
sudo rmmod -f nvidia_uvm
(rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'nvidia_uvm': Resource temporarily unavailable
rmmod: ERROR: could not remove module nvidia_uvm: Resource temporarily unavailable)
```

**Comment by inflation** [comment]
@nicklhy How about a `nvidia-smi -r`?

**Comment by nicklhy** [comment]
@inflation , doesn't work either(since the zombie processes still occupying the GPU card).
Some tensorflow users also encountered similar issues [here](https://github.com/tensorflow/tensorflow/issues/1947). But no fix found yet.

**Comment by tornadomeet** [comment]
```kill -9 31794  27707```

**Comment by nicklhy** [comment]
I have tried that, but since a zombie process is not an alive process. You can not kill it like that.
I also tried to send SIGCHLD to its current parent `sudo kill -s SIGCHLD 1`. But it does not help too.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
