### ISSUE TITLE
mx.symbol.RNN in bidirectional mode: what is the layout of its output?

### ISSUE THREAD

**Issue by WarBean** [apache/incubator-mxnet#4246]
If the hidden size is set to `H` and the mode is set to "bidirectional", the output size of `mx.sym.RNN` will be `(batch_size, sequence_length, H * 2)`. Then what is the layout of this output tensor? Which parts correspond to the forward output and backward output?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
