### ISSUE TITLE
How to initialize parameter of mx.sym.RNN in Orthogonal mode?

### ISSUE THREAD

**Issue by WarBean** [apache/incubator-mxnet#4247]
`mx.sym.RNN` accepts one single parameter vector then passes it to CuDNN's RNN interface. It's unclear that which parts of this vector correspond to those weights and biases in RNN. Neither MXNet nor CuDNN's documents provide a hint to the layout of this vector. So how could I apply orthogonal initialization to the RNN's weights?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
