### ISSUE TITLE
build mxnet in RHEL

### ISSUE THREAD

**Issue by jchen24** [apache/incubator-mxnet#4250]
# Environment info
Operating System: RHEL6

Compiler: GCC

I have a question here.  Can current mxnet source code be built and installed on RHEL6 ? OR has anyone built it on RHEL6 ? I tried to build on RHEL6 but could not find any installation documentation for RHEL in <http://mxnet.io/get_started/setup.html#installing-mxnet> or other websites I googled. 

Thank you very much for your help

**Comment by inflation** [comment]
Amazon Linux is based on RHEL. So the guide maybe also works though.

**Comment by philipskokoh** [comment]
Mxnet requires gcc 4.8 or later. The default compiler for RHEL 6 is gcc 4.4. You need to upgrade your gcc, or even better upgrade the OS.
http://mxnet.io/get_started/setup.html#minimum-requirements

**Comment by mli** [comment]
building gcc 4.8 is straightforward: http://mxnet.io/get_started/setup.html#building-gcc-from-source-code

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
