### ISSUE TITLE
mx.nd.save function can't be used to save into S3 bucket with periods in bucket name

### ISSUE THREAD

**Issue by DamonDeng** [apache/incubator-mxnet#4255]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04

Compiler:
gcc

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.7

Or if installed from source:
Yes

MXNet commit hash (`git rev-parse HEAD`):
487c22a50541686cc3fd207ad4656dbd2f9fa969

If you are using python package, please provide

Python version and distribution:
2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-23-133db28d92b2> in <module>()
----> 1 mx.nd.save("s3://imagetraining.xxxx.com/testing/a",[a,b])

/home/ubuntu/.local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.pyc in save(fname, data)
   1082                                   mx_uint(len(handles)),
   1083                                   c_array(NDArrayHandle, handles),
-> 1084                                   keys))
   1085 
   1086 def imdecode(str_img, clip_rect=(0, 0, 0, 0), out=None, index=0, channels=3, mean=None):

/home/ubuntu/.local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: [03:32:57] src/io/s3_filesys.cc:682: Check failed: num_retry < max_error_retry_  maximum retry time reached

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

Create a new Jyputer notebook, run the following Python , make sure that the bucket name of S3 has period in it: 

a = mx.nd.zeros((100, 200))
b = a+1
mx.nd.save("s3://imagetraining.xxx.com/testing/a",[a,b])

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Start Jupyter.
2. Create a notebook with the sample code above 
3. Run it and then will fail

## What have you tried to solve it?

1. Tried another S3 bucket without period in the bucket name. It worked.
2. In the document of S3: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html, found the following description:

When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic.

3. Looked into the source code dmlc-core/src/io/s3_filesys.cc:682, found that the source code is using virtual host style url to access S3, as the following code shows:

surl << "https://" << path_.host << ".s3.amazonaws.com" << '/'
       << RemoveBeginSlash(path_.name) << args;

This virtual host style method will fail because of SSL issue when the target bucket has period in the bucket name.

**Comment by piiswrong** [comment]
@mli

**Comment by DamonDeng** [comment]
One PR was created to resolve this issue:
<https://github.com/dmlc/dmlc-core/pull/203>

Please help to review it and check whether it is a proper fix.
