### ISSUE TITLE
block in Batch[2150]

### ISSUE THREAD

**Issue by achao2013** [apache/incubator-mxnet#4297]
## Environment info
Operating System: ubuntu14.04
Package used (Python/R/Scala/Julia): Python2.7
MXNet version:0.7.0

## Error Message:
i  run the train_imagenet.py in the example, and i modified some code.
it seems blocked as follows:
![image](https://cloud.githubusercontent.com/assets/5026576/21337172/edb94032-c6a5-11e6-925d-d84aeb59688a.png)

i attached the preocess in gdb ,and excute bt , the result is as follows:
![image](https://cloud.githubusercontent.com/assets/5026576/21337128/7eaff1ae-c6a5-11e6-8bc2-8574b38e8a3d.png)

## Minimum reproducible example
my code of line 619 in optimizer.py is as follows:
![image](https://cloud.githubusercontent.com/assets/5026576/21337249/b10836d8-c6a6-11e6-83c0-9d47b09b55cc.png)

I edit adam class ,and it seems some problems in SyncCopyToCpu, as #3724 
This not happens always,but i think it's a bug.
I don't know if it's fixed in nnvm branch, so if it's need to be fixed yet, i can try by best to provide more infomation.

**Comment by li-haoran** [comment]
i meet the same problem, when the nd array asnumpy() in rcnn detector. i run the code in cpu.
![image](https://cloud.githubusercontent.com/assets/3754431/21382313/028318d0-c79b-11e6-8789-be3dbeef8168.png)

some time,i run  the code in the different device like run in gpu, the code maybe fine.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
