### ISSUE TITLE
python example/gan/dcgan.py error

### ISSUE THREAD

**Issue by zhanghan328** [apache/incubator-mxnet#4299]
Operating System:
ubuntu 16.04
I just operated the example. And i turn down the batch size, the error remains.

-> train_iter = mx.io.NDArrayIter(X_train, batch_size=batch_size)
(Pdb) continue
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

the error comes out after loading data.
My gpu is GTX1060,6G.
Who can help me ?

**Comment by zhanghan328** [comment]
@piiswrong

**Comment by inflation** [comment]
Which version did you try? And could you confirm that you have enough memory?

**Comment by ysh329** [comment]
I met same question.
#5525

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
