### ISSUE TITLE
When I use the 'mx.symbol.Convolution' with 3d kernel,  I get the problem"Volume convolution is not implmented in mshadow" .

### ISSUE THREAD

**Issue by JaggerYoung** [apache/incubator-mxnet#4301]
Does mxnet still not support 3D convolution？？

**Comment by tornadomeet** [comment]
3d convolution only support in MXNet when use cudnn, not support onnormal  cpu and cuda.

**Comment by JaggerYoung** [comment]
I see, thx

**Comment by artzers** [comment]
@tornadomeet Is there detail documentary for 3d convolution? I have great interesting on 3D CNN. THX

**Comment by rongrongxiangxin** [comment]
@tornadomeet @JaggerYoung I got the same error. Is there some example for using 3d convolution with cudnn? Thanks.

**Comment by JaggerYoung** [comment]
@rongrongxiangxin You can read the document of mxnet about mx.symbol.Convolution.

**Comment by tornadomeet** [comment]
@JaggerYoung please using cudnn because 3d conv only support with cudnn in MXNet.  
  i am not sure whether there is 3d convolution examples.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
