### ISSUE TITLE
any advice of hyper parameters to train resnet and inception-bn with IMAGENET

### ISSUE THREAD

**Issue by kernel8liang** [apache/incubator-mxnet#4302]
thses days I am training "resnet and inception-bn" with IMAGENET, both of them converge very slowly after train accuracy around 0.6.  

is any advice of hyper parameters? I used the default hyper parameters with ```train_imagenet```.

**Comment by tornadomeet** [comment]
Please post more detail information about your experiment.  such as your rec prepare progress. ..

btw, resnet training detail can be found in https://github.com/tornadomeet/ResNet

**Comment by kernel8liang** [comment]
I use data "ILSVRC2012_img_train.tar", i applied to downed the full version image data, but haven't be approved. So, I only can download the "ILSVRC2012_img_train.tar", I use ```im2rec.py``` to split it to 3 pieces with shuffle, [0.7, 0.2, 0.1], respect to [train, val, test]. 

I used train and val.

**Comment by tornadomeet** [comment]
how do you use im2rec.py?and  what's the paramters?,Please read the readme https://github.com/tornadomeet/ResNet

**Comment by kernel8liang** [comment]
#4197 

first step

```
python im2rec.py /data1/ILSVRC2012/train/  /data1/ILSVRC2012/train_raw --train-ratio=0.7 --test-ratio=0.2 --list=True --recursive=True --resize=227  
```

second step 

```
python im2rec.py /data1/ILSVRC2012/train/ILSVRC2012  /data1/ILSVRC2012/train_raw --num-thread=28  --recursive=True --resize=227
```


i have read through the README.  may it need update, tools mentioned in it is no longer exist.

```im2rec_path```,   ```train_resnet.py```, i can not find them in today's code. 

in the new code, there is a parameter i don't understand ``` lr_step_epochs   = '30,60' ```, what it's for?

**Comment by tornadomeet** [comment]
because that's readme is one file of mxnet ....
your ```--resize=227``` should not work well, use 480 if your really read the readme.

**Comment by tornadomeet** [comment]
```lr_step_epochs = '30,60'``` means when the training come to epoch 30, the learning rete will be changed slower, the same is thing will happen at epoch 60.

**Comment by kernel8liang** [comment]
if use bigger size will get more robust result?
if use 480, should also use ```min_random_scale = 0.53``` in ```train_imagenet.py```

**Comment by kernel8liang** [comment]
if alexnet use a bigger size will get more robust result?

**Comment by tornadomeet** [comment]
yes, you're right.

**Comment by kernel8liang** [comment]
ok, i will try it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
