### ISSUE TITLE
why not use const reference in "ElementwiseSum" template function

### ISSUE THREAD

**Issue by yuewu001** [apache/incubator-mxnet#4304]
why not use const reference for the first argument of the following function?
```
ndarray_function.h: L134

template <typename Device>
void ElementwiseSum(const std::vector<TBlob> source,  TBlob* out,  RunContext ctx);
```

**Comment by howard0su** [comment]
this should be a code defect.
src/ndarray/ndarray.cc:void ElementwiseSum(const std::vector<NDArray> &source, NDArray *out, int priority)
src/ndarray/ndarray_function-inl.h:void ElementwiseSum<DEVICE>(const std::vector<TBlob> source,
src/ndarray/ndarray_function.h:void ElementwiseSum(const std::vector<TBlob> source,

clearly, they are no in sync

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
