### ISSUE TITLE
The implement of LRN layer that similar to caffe 

### ISSUE THREAD

**Issue by liangfu** [apache/incubator-mxnet#4317]
There are two version of LRN implement in caffe: within_channel and cross_channel version. When porting pretrained caffemodel to mxnet params, they perform quite different with exactly same input. Here is a sample of code from Caffe from https://github.com/BVLC/caffe/blob/master/src/caffe/layers/lrn_layer.cpp
```
template <typename Dtype>
void LRNLayer<Dtype>::WithinChannelForward(
    const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top) {
  split_layer_->Forward(bottom, split_top_vec_);
  square_layer_->Forward(square_bottom_vec_, square_top_vec_);
  pool_layer_->Forward(square_top_vec_, pool_top_vec_);
  power_layer_->Forward(pool_top_vec_, power_top_vec_);
  product_layer_->Forward(product_bottom_vec_, top);
}
```
and in mxnet, LRN layer is defined as:
```
const real_t salpha = param_.alpha / param_.nsize;
Stream<xpu> *s = ctx.get_stream<xpu>();
Tensor<xpu, 4> data = in_data[lrn_enum::kData].get<xpu, 4, real_t>(s);
Tensor<xpu, 4> out = out_data[lrn_enum::kOut].get<xpu, 4, real_t>(s);
Tensor<xpu, 4> tmp_norm = out_data[lrn_enum::kTmpNorm].get<xpu, 4, real_t>(s);
tmp_norm = chpool<red::sum>(F<mshadow_op::square>(data) , param_.nsize) * salpha + param_.knorm;
Assign(out, req[lrn_enum::kOut], data *  F<mshadow_op::power>(tmp_norm, -param_.beta));
```
I'm wondering the explanation of LRN layer in mxnet compared to caffe implmentation, especially why the additional `knorm` variable.is defined to 2.0 by default. Or is there any reference article that tightly related to the implementation.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
