### ISSUE TITLE
How to train ssd model for one class against background?

### ISSUE THREAD

**Issue by erogol** [apache/incubator-mxnet#4319]
I've only one class to detect. When I train the model only with this class, it predicts thousands of detection boxes so that I guess it tries to capture all ground truth boxes with random guesses of predicted boxes. How can I force the model to consider background as well?

**Comment by howard0su** [comment]
ssd support class_num=1, just change it from 21 to 1 in example/ssd

**Comment by mzmssg** [comment]
I notice that the vggnet of ssd is 20 classes，but caffe‘s ssd net is 21 classes. So if I want to solve single class detection problem, should I set num_classes 1 or 2 ?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
