### ISSUE TITLE
[Keras] Support binding a value in Symbol Constructor.

### ISSUE THREAD

**Issue by shivarajugowda** [apache/incubator-mxnet#4322]
NDArray supports binding a value in a constructor.
`  v = mx.ndarray.array(value)`
For Symbol the only time you can bind a value is during a "bind" call. Providing a interface to bind it in a constructor will make it easy in some scenarios(like in integration with Keras)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
