### ISSUE TITLE
[Discussion] Should Github Issues still be used for bug/installation issues?

### ISSUE THREAD

**Issue by skrish13** [apache/incubator-mxnet#4323]
Wouldn't it be better to discuss or ask questions related to installation issues and bugs in the users code on a different platform like [Google groups](https://groups.google.com/forum/#!forum/mxnet) or [SO](https://stackoverflow.com/questions/tagged/mxnet). 

I just realized this has been discussed a year before in #1020 (and #976), and a Google group has been created in fact. **Please** go ahead and **close** this if there isn't a need for a discussion again. 
The reason I thought of starting a discussion is because the github issue still encourages people to share usage/installation/newbie questions here. Probably promoting/mentioning the usage of Google groups for those, will help github issues be more focused towards the development of mxnet only?

I've seen scikit-learn do something like this,

![image](https://cloud.githubusercontent.com/assets/10350518/21402414/488682de-c7de-11e6-8316-6fc0e74eb0f4.png)

**Comment by mli** [comment]
prefer to have "how to" moving to SO, but the current problem is that we need to have our contributors to monitor SO.

i think installation issues and bugs are better fit github issues. they should be tracked and solved by fixing codes and documents

**Comment by leopd** [comment]
I agree with Mu.  SO has better semantics for any questions about issues that others will have later.  The purely linear discussion of github issues makes it difficult to even figure out if a question has been answered, much less what the correct answer is.  SO solves this nicely with voting and editing.  So for issues around usage which are likely to effect many users, SO is a better choice.  But for issues that are about bugs in MXNet that will get fixed and go away, or suggested improvements -- these should stay here in github.

**Comment by howard0su** [comment]
put the discussions on what topics should be discussed in "Issues" aside. I do see we need some sort of mail list thing to help community grows.

We need -announce mail list. we will have release soon. How can you proactive to reach the users? an announce mail list is very typical for such purpose. low volume and encourage people to subscribe.

We need -users mail list. How can I share my best practice? How can I seek for help? How can I get advise on implementing one paper? we need a mail list to have our active users exchange the voices.

We need -dev mail list. How developer coordinate the effort to make next release like code frozen, api frozen, release schedule? I see next release is not transparent enough. Like we still accept examples change but no core src change. I didn't see we announce that to the developers. Also, we need a better place to share the design and longer term roadmap discussion.

Just my two cents. please consider.

**Comment by skrish13** [comment]
What @leopd said is mostly what even I tried to express. And +1 for @howard0su's views about the need for a mailing lists! SO would be really helpful infact as people like @thirdwing manually tag the issues to different labels (R-Package in his case) and the issues aren't just limited to core mxnet but also different parts of it like the r-package etc. So it makes more sense especially in our case, to automatically tag/allow users to tag/label (hence SO)

**Comment by thirdwing** [comment]
I think we still need to keep bug reports on github.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
