### ISSUE TITLE
A strange thing while training with googlenet

### ISSUE THREAD

**Issue by zhqshen** [apache/incubator-mxnet#4333]
Hi, all:
      while training with googlenet, the training curve is very strange, 
![image](https://cloud.githubusercontent.com/assets/20835063/21415353/d90590a6-c843-11e6-93e1-02b7ad79f800.png)
Is there anyone good suggestions? Net is googlenet, --lr is set to 0.05, --lr-factor is set to 0.95, --lr-factor-epoch is set to 5, --num-epochs is set to 30, using mx.io.NDArrayIter to load npy files standardized by myself.

**Comment by piiswrong** [comment]
looks normal to me

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
