### ISSUE TITLE
Is there a python ordinary classification example? 

### ISSUE THREAD

**Issue by anddelu** [apache/incubator-mxnet#4342]
I am a new user to mxnet. Recently, I want to do mulitclasses using mxnet so I look the examples by mxnet. However it has many examples about image, I can't find an example about ordinary classification, such as binary, multiclass labels in traditional machine learning scenario. can you provide such an example for the new user to understand more about mxnet?

**Comment by piiswrong** [comment]
exmaple/multi-task

**Comment by anddelu** [comment]
thank you very much! I need time to think it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
