### ISSUE TITLE
Installation problem related to OpenCV3

### ISSUE THREAD

**Issue by Walid-Ahmed** [apache/incubator-mxnet#4350]
Hi

I am having trouble installing MXNet, it seems unable to find my opencv3 folder

Walids-MacBook-Pro:mxnet walidahmed$   make -j$(sysctl -n hw.ncpu)
make: *** No rule to make target `/usr/local/Cellar/opencv/2.4.13.2/include/opencv2/opencv.hpp', needed by `build/src/io/image_aug_default.o'.  Stop

OpenCV is already installed at  /usr/local/Cellar/opencv3

opencv.hpp is at /usr/local/Cellar/opencv3/HEAD-dc9602e_4/include/opencv2/opencv.hpp

if I uninstall OpenCV3 nad install OpenCV2.4, MXNet installation works fine. the issue that I need OpenCV3.

## Environment info
Operating System:
MacOs Sierra

Package used (Python/R/Scala/Julia):
Python

Python version and distribution:
2.7

## Error Message:

Please paste the full error message, including stack trace.
Walids-MacBook-Pro:mxnet walidahmed$   make -j$(sysctl -n hw.ncpu)
make: *** No rule to make target `/usr/local/Cellar/opencv/2.4.13.2/include/opencv2/opencv.hpp', needed by `build/src/io/image_aug_default.o'.  Stop

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

**Comment by piiswrong** [comment]
make clean first

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
