### ISSUE TITLE
How to set net use different input shape?

### ISSUE THREAD

**Issue by zhengxiawu** [apache/incubator-mxnet#4355]
the network use different image size as input, how to write the dataiter?

**Comment by andremoeller** [comment]
Not sure if I understand exactly what you're asking, but have you tried using [mx.symbol.Reshape](http://mxnet.io/api/python/symbol.html#mxnet.symbol.Reshape)?

**Comment by zhengxiawu** [comment]
thanks:)

**Comment by formath** [comment]
The input and output shape is checked when constructing symbol and don't be changed afterward. The reshape is mostly used in inner implementation for cuda matrix calculation. But I'm not sure about that.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
