### ISSUE TITLE
mxnet.io: search bar can't be selected after zooming page

### ISSUE THREAD

**Issue by andremoeller** [apache/incubator-mxnet#4370]
To reproduce:

1. Go to http://mxnet.io/api/python/index.html
2. Zoom in. (CTRL +).
3. Try to click on search bar.

Tried with Chrome and Firefox on Ubuntu.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
