### ISSUE TITLE
docker for cpu: version too old

### ISSUE THREAD

**Issue by Stonesjtu** [apache/incubator-mxnet#4371]
the mxnet version on docker hub seems way too old, hope that you can update the docker image together with the code base.

## Environment
Operating System: Ubuntu 16.04 LTS with docker
MXNet version: Python

## Steps to reproduce

1.docker pull dmlc/mxnet
2.docker run dmlc/mxnet python /mxnet/example/image-classification/train_mnist.py
3.404 not found

**Comment by piiswrong** [comment]
@mli

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
