### ISSUE TITLE
Could NOT find CUDA: Found unsuitable version "8.0", but required is exact   version "7.5" (found /usr/local/cuda)

### ISSUE THREAD

**Issue by thesby** [apache/incubator-mxnet#4380]
`Could NOT find CUDA: Found unsuitable version "8.0", but required is exact version "7.5" (found /usr/local/cuda)`
I clone the repository, and run cmake. The error occurs.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
