### ISSUE TITLE
The try: except code in python/mxnet/notebook/callback.py caused a lots of error

### ISSUE THREAD

**Issue by DamonDeng** [apache/incubator-mxnet#4384]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Mac/Ubuntu

Compiler:
gcc

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.7

Or if installed from source:
Yes

MXNet commit hash (`git rev-parse HEAD`):
5434387d60ee121d7bd2221ff710de2a5db67a54

If you are using python package, please provide

Python version and distribution:
2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/notebook/callback.pyc in __init__(self, metric_name, display_freq, frequent)
    292             'eval': {'elapsed': [],},
    293         }
--> 294         super(LiveLearningCurve, self).__init__(None, metric_name, display_freq, frequent)
    295 
    296     def setup_chart(self):

/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/notebook/callback.pyc in __init__(self, pandas_logger, metric_name, display_freq, batch_size, frequent)
    199         #NOTE: would be nice to auto-detect the metric_name if there's only one.
    200         self.metric_name = metric_name
--> 201         bokeh.io.output_notebook()
    202         self.handle = self.setup_chart()
    203 

NameError: global name 'bokeh' is not defined

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

Just run the example/recommenders/demo1-MF.ipynb

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Start Jupyter
2. Run example/recommenders/demo1-MF.ipynb
3.

## What have you tried to solve it?

1. Track the error log, found that module `bokeh` was not installed. 
2. Check the source code, found the follow code:

`try:`
`    import bokeh.plotting`
`except ImportError:`
 `   pass`
 

 

3. Don't understand why we just pass it when we can't import bokeh.plotting, isn't it a better way to let the system report that we can't import this module which is not installed, and let the users to install it with `pip install bokeh`?

**Comment by kevinthesun** [comment]
http://stackoverflow.com/questions/3131217/error-handling-when-importing-modules
We can consider providing "pip install bokeh" in error message.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
