### ISSUE TITLE
    from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \ AttributeError: 'module' object has no attribute 'Scale'

### ISSUE THREAD

**Issue by thx-fan** [apache/incubator-mxnet#4387]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by Walid-Ahmed** [comment]
I also have the same bug
 from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \
AttributeError: 'module' object has no attribute 'Scale'

**Comment by xinghedyc** [comment]
please take a look at ssd example readme and recompile your mxnet and try again
key information maybe : 
```
# for Ubuntu/Debian
cp make/config.mk ./config.mk
# modify it if with vim or whatever editor
EXTRA_OPERATORS = example/ssd/operator
# or add a line if you have other EXTRA_OPERATORS directory
EXTRA_OPERATORS += example/ssd/operator
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
