### ISSUE TITLE
New MXNet logo proposals

### ISSUE THREAD

**Issue by weihwang** [apache/incubator-mxnet#4392]
Hi everyone, I wanted follow up on the previous open issue: https://github.com/dmlc/mxnet/issues/3305
and share a few new options for the MXnet logo update.

Please vote for the proposal(s) if you would like to use it as an update to the MXnet logo. If there is enough interest for a specific design I can share assets needed for next steps.

![github-like](https://cloud.githubusercontent.com/assets/551333/21507801/4690f792-cc30-11e6-9347-fe84eaeae738.jpg)

Cheers,
William

**Comment by weihwang** [comment]
1. small circle

![mxnet-logo-sm-circle](https://cloud.githubusercontent.com/assets/551333/21507897/4bc1006c-cc31-11e6-8b45-e6a519b46941.png)

**Comment by weihwang** [comment]
2. medium circle
![mxnet-logo-md-circle](https://cloud.githubusercontent.com/assets/551333/21507914/5c19a87e-cc31-11e6-9b73-13a84099c4d9.png)

**Comment by weihwang** [comment]
3. large circle
![mxnet-logo-lg-circle](https://cloud.githubusercontent.com/assets/551333/21507920/6e310174-cc31-11e6-999d-9345cb0453ba.png)

**Comment by weihwang** [comment]
4. fold
![mxnet-logo-fold](https://cloud.githubusercontent.com/assets/551333/21507923/759a2cf6-cc31-11e6-98a0-d2de57f28f35.png)

**Comment by weihwang** [comment]
5. loop
![mxnet-logo-loop](https://cloud.githubusercontent.com/assets/551333/21507936/7cd327f2-cc31-11e6-91a8-cfd60d6fe745.png)

**Comment by smolix** [comment]
IMHO 1 (small circle) and 5 (loop) look best. 1 is elegant. 5 is cute (the loop around 'net' looks like a fish, so it's a fish catching a net ...). it's also probably the most recognizable and unique.

**Comment by Primus-zhao** [comment]
vote 4.
Shows mix, and that's the key feature of mxnet, isn't it?

**Comment by jspisak** [comment]
I am inclined to say that #1 is the winner here but let's give it a few more days and then we can lock it if there is agreement. I have some hoodies to order.. :)

**Comment by jonsafari** [comment]
Any developments with this?

**Comment by asmushetzel** [comment]
IMHO, #1 is by far best. It's the most elegant version mainly because it's so simple. It also focuses nicely on "mx"  and keeps the "net" a bit at a side (which is good as "net" is a term that is used all over)
#4 is nice too but IMO a bit too complex. It tries to bring a certain message but at the end, most people may not get it anyway.

**Comment by pineking** [comment]
vote 5 (loop)

**Comment by jonsafari** [comment]
Why was this closed?
