### ISSUE TITLE
odd behavior of ndarray

### ISSUE THREAD

**Issue by howard0su** [apache/incubator-mxnet#4397]
Is this expected or by design?
>>> import numpy as np
>>> import mxnet as mx
>>> x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> y = mx.nd.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> x[0:0].shape
(0,)
>>> y[0:0].shape
(10,)

**Comment by piiswrong** [comment]
@sxjscience

**Comment by sxjscience** [comment]
Fixed now.
