### ISSUE TITLE
MXNetError: [16:38:44] src/operator/cudnn_batch_norm.cc:20: CuDNNBatchNorm is merged into BatchNorm for cudnn version above v5.Use the later instead.

### ISSUE THREAD

**Issue by motypas** [apache/incubator-mxnet#4406]
OS: Linux / Ubuntu /16.04LTS
MXNET version  - from GIT (today)
CUDA version 8
DNN version 5.1
compile for GPU 100% -ok no error
GPU 1070 nvidia
deep3d version - from git (today)

when I run the deep3d.ipynb with jupyter notebook I get this error...

**MXNetError: [16:38:44] src/operator/cudnn_batch_norm.cc:20: CuDNNBatchNorm is merged into BatchNorm for cudnn version above v5.Use the later instead.**

Any working solution for this error message? Any fix or patch? working idea?

**Comment by yajiedesign** [comment]
use BatchNorm replace CuDNNBatchNorm.

**Comment by motypas** [comment]
OK I change in the json file the CuDNNBatchNorm to BatchNorm
BUT I get another error:
ValueError: Find name bn_pool3_moving_inv_var that is not in the auxiliary states

How can I fix this error?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
