### ISSUE TITLE
NDArrayIter building one more iter even if last_batch_handle set to discard ?

### ISSUE THREAD

**Issue by alinagithub** [apache/incubator-mxnet#4411]
Hi,

I use the following call:
`train_iter = mx.io.NDArrayIter(mydata ,mylbl, 1 shuffle=True, last_batch_handle='discard')`
with
mydata.shape = (33, 1, 28, 28)
mylbl.shape = (33,)

then the following prints:

```
batch_data  = train_iter.getdata()
print(batch_data)
train_iter.iter_next()
batch_data  = train_iter.getdata()
print(batch_data)
train_iter.iter_next()
batch_data  = train_iter.getdata()
print(batch_data)
```

return:

[<NDArray 34x1x28x28 @cpu(0)>]
[<NDArray 1x1x28x28 @cpu(0)>]
[<NDArray 1x1x28x28 @cpu(0)>]

shouldn't the first print be:
[<NDArray 3**3**x1x28x28 @cpu(0)>] as the last_batch_handle set to discard and the batch size is 1 ?

many thanks,
AL

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
