### ISSUE TITLE
Does mxnet has the matrix_inverse symbol?

### ISSUE THREAD

**Issue by chenboheng** [apache/incubator-mxnet#4422]
I want to implement some new operations by mxnet.
And I need to use the matrix_inverse operation. Dose mxnet has the symbol (mx.symbol.matrix_inverse) to implement the inverse of matrix?

**Comment by xlvector** [comment]
Sparse Matrix or Dense?

**Comment by chenboheng** [comment]
dense matrix

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by 610v4nn1** [comment]
Is there an answer to the question?

**Comment by 610v4nn1** [comment]
Looks like it is possible to do it: https://mxnet.incubator.apache.org/api/python/ndarray/linalg.html#mxnet.ndarray.linalg.potri
