### ISSUE TITLE
Undefined symbols for architecture x86_64  when compiling using Cuda

### ISSUE THREAD

**Issue by Walid-Ahmed** [apache/incubator-mxnet#4426]
## Environment info
Operating System:

MacOS

Package used (Python/R/Scala/Julia):

MXNet version:

0.7

Python version and distribution:

2.7

my graphics card is Intel Iris Pro 1536 MB

## Error Message:
ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
Undefined symbols for architecture x86_64:
  "mxnet::op::TuneCudnnConvolution(mxnet::op::ConvolutionParam, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, mxnet::Context, cudnnDataType_t, cudnnConvolutionFwdAlgo_t*, cudnnConvolutionBwdDataAlgo_t*, cudnnConvolutionBwdFilterAlgo_t*)", referenced from:
      mxnet::op::CuDNNConvolutionOp<float>::CuDNNConvolutionOp(mxnet::op::ConvolutionParam, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, mxnet::Context) in convolution_gpu.o
      mxnet::op::CuDNNConvolutionOp<double>::CuDNNConvolutionOp(mxnet::op::ConvolutionParam, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, mxnet::Context) in convolution_gpu.o
      mxnet::op::CuDNNConvolutionOp<mshadow::half::half_t>::CuDNNConvolutionOp(mxnet::op::ConvolutionParam, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, std::__1::vector<mxnet::TShape, std::__1::allocator<mxnet::TShape> >*, mxnet::Context) in convolution_gpu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libmxnet.so] Error 1

**Comment by kevinthesun** [comment]
Try to use following settings in config.mk:

USE_BLAS = openblas
ADD_CFLAGS += -I/usr/local/opt/openblas/include
ADD_LDFLAGS += -L/usr/local/opt/openblas/lib
ADD_LDFLAGS += -L/usr/local/lib/graphviz/
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
USE_NVRTC = 1

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
