### ISSUE TITLE
Error occured when compiling with vs2013 and mxnet(2016-12-30)

### ISSUE THREAD

**Issue by artzers** [apache/incubator-mxnet#4444]
## Environment info
Operating System: Win7 64

Compiler: VS 2013 12.0.21005.1 REl

Package used : python

MXNet version: master in 2016-12-30

Python version and distribution: Anaconda python 2.7.11

## Error Message:
(1) in dmlc-core/include/dmlc/optional.h: 
namespace dmlc {
/*! \brief dummy type for assign null to optional */
struct nullopt_t {
  /*! \brief dummy constructor */
  constexpr nullopt_t(int) {} // error : expected an identifier,error : expected a ";"
};

(2) in mshadow/base.h:
/base.h(243): error : invalid redeclaration of type name "cudnnTensorFormat_t"

(3)dmlc-core\include\dmlc/logging.h(95): error C2040: “!=”:“void *const ”与“const int”的间接寻址级别不同

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Download mxnet master, dmlc-core and mshadow. 
2. CMAKE configure and generate success. OpenCV, cudnn 4 and openblas is OK
3. all_build and error occured:

**Comment by yajiedesign** [comment]
fix with https://github.com/dmlc/dmlc-core/pull/204.wait merge

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
