### ISSUE TITLE
Error occured when runing rnn_cell_demo.py with yajiedesign mxnet release

### ISSUE THREAD

**Issue by artzers** [apache/incubator-mxnet#4449]
Environment info

Operating System: Win7 64

Compiler: VS 2013 12.0.3 Update 4

3rd Library : cudnn 4, openblas, opencv2, cuda 7.5

MXNet version: yajiedesign GPU release: 2016-12-29,2016-11-25,2016-09-09

Python version and distribution: Anaconda python 2.7.11

Error info:
mxnet.base.MXNetError: [15:45:06] D:/Program Files (x86)/Jenkins/workspace/mxnet
/mxnet/src/operator/rnn.cu:24: RNN is only available for cuDNN at the moment.

Description:

1. CNN module can be run quickly and produce good results with GPU. cudnn has been put into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5. I think cudnn is OK

2. run rnn_cell_demo.py, error shows : 
mxnet.base.MXNetError: [15:45:06] D:/Program Files (x86)/Jenkins/workspace/mxnet
/mxnet/src/operator/rnn.cu:24: RNN is only available for cuDNN at the moment.

3. I  change many many prebuilt yajiedesign  version, error occurs still.

In addition, I would appreciate that RNN corresponding models and symbols, such like codes in bucket_io.py, can be programmed into standard mxnet library and more easily to use. It means,  just compose several existed symbol, then  I  can wrap input samples, labels and  get complete char-RNN model  or speech rnn model.

An ideal assumption:
data = mx.sym.SequenceVariable(name='data',bucket=[5,10,15])
...
rnn = mx.sym.RNN(name='rnn',data=...,num_filter=...)

**Comment by yajiedesign** [comment]
i will check

**Comment by yajiedesign** [comment]
rnn.cu only work with cudnn5 .but prebuild vc12 is cudnn4.
you can use vc14 prebuild. it cudnn5.
and i am update vc12 pebulid cudnn4 to cudnn5 some hour ago.now it building, you can wait it build and upload finish.

**Comment by yajiedesign** [comment]
e..i have some problem.please wait.

**Comment by yajiedesign** [comment]
sorry for later,you can download and test now
@artzers

**Comment by artzers** [comment]
@yajiedesign Why it is so big? At last it was several MBs ...

**Comment by artzers** [comment]
@yajiedesign the CNN speed seems much slower than before version like 2016-11-25 release with cudnn4... Is it a debug version?

**Comment by artzers** [comment]
@yajiedesign  the CNN speed seems much slower than before version like 2016-11-25 release with cudnn4... Is it a debug version? My current envirionment is cudnn v5.1 for cuda 7.5, python2.7.11

**Comment by artzers** [comment]
@yajiedesign the CNN speed seems much slower than before version like 2016-11-25 release with cudnn4. Luckily mxnet can still produce good result.  Is it a debug version? My current envirionment is cudnn v5.1 for cuda 7.5, python2.7.11

**Comment by artzers** [comment]
I see that the mxnet version is 0.9.1. In past when training CNN, the GPU load is about 25%~40%, now the GPU load is 70%, but the training speed seems a little lower. Later I will try RNN

**Comment by artzers** [comment]
hello @yajiedesign , error occured when run rnn_cell_demo.py:
Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

However, I run cuda deviceQueryDrv.exe, get normal information, why?

CUDA Device Query (Driver API) statically linked version
Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX TITAN X"
  CUDA Driver Version:                           7.5
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12288 MBytes (12884901888 bytes
)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Max Texture Dimension Sizes                    1D=(65536) 2D=(65536, 65536) 3D
=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size (x,y,z):    (2147483647, 65535, 65535)
  Texture alignment:                             512 bytes
  Maximum memory pitch:                          2147483647 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Concurrent kernel execution:                   Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Mo
del)
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simu
ltaneously) >
Result = PASS

**Comment by zihaolucky** [comment]
@yajiedesign I meet similar issue `RNN is only available for cuDNN at the moment.`, but I've set the config cuDNN = 1 in `config.mk` and I can complete the installation.

**Comment by yajiedesign** [comment]
@zihaolucky do you set USE_CUDA=1?

**Comment by zihaolucky** [comment]
@yajiedesign yes. I've try to print the cuda and cudnn version, seems I have to upgrade them. I use cuda7.5

**Comment by yajiedesign** [comment]
@zihaolucky cudnn must >=5

**Comment by zihaolucky** [comment]
@yajiedesign yep, thank you.

**Comment by zihaolucky** [comment]
@yajiedesign can I use cuda7.5 but cudnn>5?

**Comment by zihaolucky** [comment]
After I upgrade the cudnn, I met 

```
Check failed: err == CUDNN_STATUS_SUCCESS (1 vs. 0) CUDNN_STATUS_NOT_INITIALIZED
```

**Comment by yajiedesign** [comment]
@zihaolucky update you gpu driver.
