### ISSUE TITLE
 fcn_xs.py data.py Crashes Semantic Segmentation Setup

### ISSUE THREAD

**Issue by hskapasi** [apache/incubator-mxnet#4460]
Hi

I was trying to reproduce results on semantic segmentation given in example folder fcn_xs. But unfortunately, I am having multiple issues trying to understand the code and the code keeps crashing.

## Environment info
Operating System: Windows/Linux
Package used (Python):
MXNet version:Master 

I am totally confused about the structure of  train.lst and val.lst used for simulating fcn_xs example on VOC 2012 dataset. 

I am using VOC2012 dataset as mentioned in the code with my
root_dir             VOCdevkit\VOC2012\SegmentationClass
flist_name          VOCdevkit\VOC2012\SegmentationClass\train.lst

I created the train.lst and val.lst as follows

2008_000033	0
2008_000197	0
2008_000716	0
2008_001719	0
2008_002221	0
2008_002551	0
2008_002719	0
2008_003196	0
2008_003703	0
2008_003729	0
2008_006140	0

First column is Segmented ImageID and Second Column is the Class. Here 0 mean aeroplane. 

When I feed this file to the project provided in fcn_xs I get following error. 
I modified the data.py file little to read the .lst files 

    # _, data_img_name, label_img_name = self.f.readline().strip('\n').split("\t")
    data_img_name, label_img_name = self.f.readline().strip('\n').split("\t")

## Error Message:
runfile('H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs/fcn_xs.py', args=' --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16', wdir='H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs')
(32, 32) 2008_000033 0
Traceback (most recent call last):

  File "<ipython-input-4-034dc04e8c56>", line 1, in <module>
    runfile('H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs/fcn_xs.py', args=' --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16', wdir='H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs')

  File "C:\Users\asdlfj\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Users\asdlfj\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs/fcn_xs.py", line 73, in <module>
    main()

  File "H:/MXNet/mxnet-master/mxnet-master/example/fcn-xs/fcn_xs.py", line 36, in main
    rgb_mean             = (123.68, 116.779, 103.939),

  File "data.py", line 44, in __init__
    self.data, self.label = self._read()

  File "data.py", line 54, in _read
    data[self.data_name], label[self.label_name] = self._read_img(data_img_name, label_img_name)

  File "data.py", line 59, in _read_img
    label = Image.open(os.path.join(self.root_dir, label_name))

  File "C:\Users\asdlfj\Anaconda2\lib\site-packages\PIL\Image.py", line 2272, in open
    fp = builtins.open(filename, "rb")

IOError: [Errno 2] No such file or directory: 'H:\\AWS\\VOCdevkit\\VOC2012\\SegmentationClass\\0'

## Steps to reproduce

Problem is here in data.py file where it tries to read the images and labels.

        img = Image.open(os.path.join(self.root_dir, img_name))
        label = Image.open(os.path.join(self.root_dir, label_name))

Here it tries to read images for both image and labels. But  I only have Image and Labels ( as numeric class value). I am really unable to understand what img_name and label_name mean here.
Does JPEGImages map to img_name and
SegmentationClass map to label_name in VOC2012 folder? 
Obviously, some link in  understanding is missing between JPEGImages ,SegmentationClass images, Label Values in my setup.

Clarification will be really helpful

Thanks

**Comment by hskapasi** [comment]
AeroPlane is Labelled as '1' NOT '0'. Please ignore. Although, it is irrelevant to question

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
