### ISSUE TITLE
Error in make scalapkg 

### ISSUE THREAD

**Issue by Bill-Q** [apache/incubator-mxnet#4469]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Mac OS X 10.12.2

Compiler:

Package used (Python/R/Scala/Julia):
Scala

MXNet version:
0.9.1

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
d0728ca552d919fd40616149016ba4dd664c4e20

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
make scalapkg
(cd /myhome/Tools/mxnet/scala-package; \
		mvn clean package -Posx-x86_64-gpu -Dcxx="g++" \
			-Dcflags="-DMSHADOW_FORCE_STREAM -Wall -O3 -I/myhome/Tools/mxnet/mshadow/ -I/myhome/Tools/mxnet/dmlc-core/include -fPIC -I/myhome/Tools/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include -DMSHADOW_USE_CUDNN=1  -I/usr/local/opt/openblas/include -DMXNET_USE_DIST_KVSTORE -I/myhome/Tools/mxnet/ps-lite/include -I/myhome/Tools/mxnet/deps/include -DMXNET_USE_NVRTC=0" -Dldflags="-pthread -lm -lcudart -lcublas -lcurand -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lopenblas  -L/usr/local/Cellar/opencv/2.4.13.2/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lcudnn  -L/usr/local/opt/openblas/lib -L/usr/local/lib/graphviz/ /myhome/Tools/mxnet/deps/lib/libprotobuf-lite.a /myhome/Tools/mxnet/deps/lib/libzmq.a -lcuda" \
			-Dlddeps="/myhome/Tools/mxnet/ps-lite/build/libps.a /myhome/Tools/mxnet/dmlc-core/libdmlc.a /myhome/Tools/mxnet/nnvm/lib/libnnvm.a")
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.artifactId' for ml.dmlc.mxnet:libmxnet-init-scala-${platform}:${libtype} with value 'libmxnet-init-scala-${platform}' does not match a valid id pattern. @ line 77, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project ml.dmlc.mxnet:mxnet-macros_2.11:0.1.2-SNAPSHOT (/myhome/Tools/mxnet/scala-package/macros/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.artifactId' for ml.dmlc.mxnet:libmxnet-init-scala-${platform}:${libtype} with value 'libmxnet-init-scala-${platform}' does not match a valid id pattern. @ line 77, column 19
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http:/cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
make: *** [scalapkg] Error 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
make scalapkg

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
After building mxnet
1. make scalapkg
2.
3.

## What have you tried to solve it?

1. Modify pom.xml
2.
3.

**Comment by Ldpe2G** [comment]
@javelinjs

**Comment by Ldpe2G** [comment]
@Bill-Q seems scalapkg hasn't support osx-x86_64-gpu yet,
see https://github.com/dmlc/mxnet/blob/master/scala-package/core/pom.xml 
start at line 18

**Comment by Bill-Q** [comment]
I see. Thanks for pointing it out. Do we have an ETA for supporting it?

**Comment by javelinjs** [comment]
By adding profile `osx-x86_64-gpu` in `core/pom.xml`, with a new sub module under `native`, I think it should not be hard to support gpu on osx. Are you interested in contributing this support?

**Comment by alexy** [comment]
@javelinjs what does adding the support for osx-x86_64-gpu entail -- is it just `pom.xml` massage or more heavy lifting?

**Comment by javelinjs** [comment]
It could be done by modifying `pom.xml`, while I'm not sure whether special compile options are needed.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by alexy** [comment]
Does it build on Mac OSX?  People try and abandon the project when it does not build on Mac.  I'd think the way to close it is to make it build, and the issue should not be closed until it does.

**Comment by szha** [comment]
@javelinjs

**Comment by javelinjs** [comment]
As we've discussed, it builds on osx for cpu, but not gpu. I'm working on maven deploy currently. The gpu support for osx is under relatively low priority. I'll make a roadmap soon.

**Comment by seveniruby** [comment]
yes, when i change to cpu, that's work. it's mean scala+gpu+mac not work

**Comment by ali2210** [comment]
does windows support mxnet along with scala , if so then how  ?
