### ISSUE TITLE
LSTM in predictor (c++ API)?

### ISSUE THREAD

**Issue by dneprDroid** [apache/incubator-mxnet#4482]
Is it possible to implement LSTM networks in this predictor?
( https://github.com/dmlc/mxnet/tree/master/amalgamation )

**Comment by piiswrong** [comment]
save your network to json, then it works the same way as CNN

**Comment by kongjiellx** [comment]
@dneprDroid have you solved the problem? I try to implement lstm predictor in c_predict_api, but have some  problem. should I provide not only 'data' but also lstm's init state to MXPredCreate?
@piiswrong

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
