### ISSUE TITLE
About MXNDArrayCreateEx:The Performence with std::make_shared

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#4486]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
x86-64-Red Hat Linux
Compiler:
gcc4.8.5
Package used (Python/R/Scala/Julia):
Python
MXNet version:
v0.7
Or if installed from source:
Yes
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

when I call this Function as followed:

arg_params["data"] = mx.nd.array(img, ctx)

it will take a long time for a return from this function, and I has debug with gdb --args and python -m pdb between python and c++ , then I found that It is mainly because the std::make_shared when allocated

Thank you very much for giving me some suggestion, thank you , sir!

**Comment by piiswrong** [comment]
The first allocation on GPU will take a long time due to cuda initialization

**Comment by idealboy** [comment]
Thank you, and I have found that, the cudaStreamCreate will take a long time in mxnet, while it take a short time when I call this function in a standlone c++ demo?why?  Thank you

very long time to consume

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
