### ISSUE TITLE
a question about the new Image APIs

### ISSUE THREAD

**Issue by horserma** [apache/incubator-mxnet#4487]
In the release note, it says:
```imgs = [mx.image.imdecode(open(f).read()) for f in img_paths]```
this will be automatically processed in parallel. So I am wondering if the other preprocessing functions can be used in the same way. Like "crop", "random scale", can I make them parallel as well?

**Comment by piiswrong** [comment]
yes. as long as you don't call asnumpy()

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
