### ISSUE TITLE
Different performance of Deconvolution layer with or without num_group

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#4492]
Hi,
I tried to use deconvolution layer to do upsampling. I guess a good way is to use deconvolution layer with bilinear kernels. There could be two ways of doing it: one is to set num_group equal to the channel number, and the other one is to use num_group=1 and use a multi-channel kernel. However, I observed there was a big difference using these two. The test code is as follows:
```
def check_speed(sym, ctx, scale=1.0, N=100):
    exe = sym.simple_bind(grad_req='write', **ctx)
    init = [np.random.normal(size=arr.shape, scale=scale) for arr in exe.arg_arrays]
    for arr, iarr in zip(exe.arg_arrays, init):
        arr[:] = iarr.astype(arr.dtype)

    # warm up
    exe.forward(is_train=True)
    exe.backward(exe.outputs[0])
    exe.outputs[0].wait_to_read()

    tic = time.time()
    for i in range(N):
        exe.forward(is_train=True)
        exe.backward(exe.outputs[0])
        exe.outputs[0].wait_to_read()
    return (time.time() - tic)*1.0/N

channel=10

ctx_list = [{'ctx': mx.gpu(0), 'deconv_data': (1, channel, 224, 224)}]
sym = mx.symbol.Deconvolution(name = "deconv", kernel=(4,4), stride=(2, 2), num_filter=channel, pad=(1, 1), no_bias=True)
for ctx in ctx_list:
    print ctx, check_speed(sym, ctx, N=10)
sym = mx.symbol.Deconvolution(name = "deconv", kernel=(4,4), stride=(2, 2), num_filter=channel, num_group=channel, pad=(1, 1), no_bias=True)
for ctx in ctx_list:
    print ctx, check_speed(sym, ctx, N=10)
```

Using num_group=1 seems quicker, but if the channel number is very larger, the kernel will be very big. Since most of the values are 0, setting num_group=channel seems a good solution, but is this suppposed to be slow?

**Comment by ascust** [comment]
@tqchen @piiswrong Any suggestions?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
