### ISSUE TITLE
running bug:  typeerror:_init_() got an unexpected keyword argument 'factor1'

### ISSUE THREAD

**Issue by wanderingpj** [apache/incubator-mxnet#4494]
I want to change the factor in lr_scheduler.py to 3 different factors , so I changed lr_scheduler.py like this
![image](https://cloud.githubusercontent.com/assets/24189081/21590999/518bcb26-d13b-11e6-8403-29d18e22cc07.png)
and changed train_model.py like this 
![image](https://cloud.githubusercontent.com/assets/24189081/21591018/6f583784-d13b-11e6-896d-b701c698a4a4.png)
and changed some other files which use factor.
But there is a bug like this
![image](https://cloud.githubusercontent.com/assets/24189081/21591071/d85d9ad0-d13b-11e6-8f20-ff890108d1c7.png)
I don't know what's the reason.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
