### ISSUE TITLE
Evaluation metric: train or test score ?

### ISSUE THREAD

**Issue by alinagithub** [apache/incubator-mxnet#4497]
Hi Mxnet,

I am a bit confused.
Looking at the examples and at the callback.py file, I can see that the same function param.eval_metric.get() is used for both the Test-metric and the Train_metric.
Can you clarify ? What makes the result test versus train, the used callback entry-point (batch_end_callback versus eval_batch_end_callback versus eval_end_callback)?
In other words, how to retrieve the Test score, the train score, and the train loss in a single custom callback, for example from the eval_batch_end_callback?

Many thanks,
AL

**Comment by alinagithub** [comment]
I tried using model.score inside my custom callback to calculate the train and the test accuracy scores... unfortunately this lead to an infinite fit process... If you have any suggestion :)

**Comment by piiswrong** [comment]
model is deprecated. Try moduel

**Comment by alinagithub** [comment]
Thank you Eric. I will definitely try Module.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
