### ISSUE TITLE
[win] Validation-accuracy一直不变

### ISSUE THREAD

**Issue by xzc9180** [apache/incubator-mxnet#4508]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: win10

Compiler:

Package used (Python/R/Scala/Julia):python

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: .

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
![image](https://cloud.githubusercontent.com/assets/24893937/21608146/b6598df8-d1f5-11e6-8576-59071e31ad49.png)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by mli** [comment]
try a new win version at https://github.com/yajiedesign/mxnet/releases?

**Comment by xzc9180** [comment]
I have tried the new win version, but I failed to install it, could you tell me how to install the new version correctly?

**Comment by xzc9180** [comment]
I have tried the new win version, but I failed to install it, could you tell me how to install the new version correctly?

**Comment by mli** [comment]
@yajiedesign

**Comment by yajiedesign** [comment]
@xzc9180 first download base package .then download  update package. copy update to base package.
run setupenv.cmd

**Comment by xzc9180** [comment]
I use visual studio 2015 and windows 10, so  I download  'prebuildbase_win10_x64_vc14' and '20170105_mxnet_x64_vc14_gpu', then copy the update to base package, run setupenv.cmd, and install mxnet for python ,but met some error as follows
![image](https://cloud.githubusercontent.com/assets/24893937/21670780/068c8818-d352-11e6-9711-ea4642dbb8b4.png)

**Comment by yajiedesign** [comment]
@xzc9180 do you install Cython and it work fine?the 0.9.1 python interface must use Cython .

**Comment by xzc9180** [comment]
@yajiedesign 
I have installed Cython, and  it can work as follows
![image](https://cloud.githubusercontent.com/assets/24893937/21672812/c773ba76-d35f-11e6-985b-4a14090df228.png)

**Comment by yajiedesign** [comment]
@xzc9180 give me a full  traceback info.

**Comment by xzc9180** [comment]
@yajiedesign I am sorry to tell you that I still failed, I have tried Microsoft Visual C++ Compiler for Python (only for Python 2.7.x), but still occur errors. I want to know the software version you use, could you please tell me your another contact information,such as QQ.

**Comment by yajiedesign** [comment]
@xzc9180 qun 489170253

**Comment by xzc9180** [comment]
@yajiedesign  I have joined in it, so who can I ask or could tell me your ID

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
