### ISSUE TITLE
[c++][win] wrong predict results for image-classification

### ISSUE THREAD

**Issue by dxp5823625** [apache/incubator-mxnet#4515]
MXNet :20160531_win10_x64_cpu

VS2013

As image-classification-predict.cc

ALL the image , MXPredGetOutput return the same result:

![image](https://cloud.githubusercontent.com/assets/9913161/21632409/0b32c82c-d281-11e6-98e5-25cb9793740e.png)

**Comment by mli** [comment]
which pre-trained model are you using. `20160531_win10_x64_cpu` is probably too old.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
