### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by motypas** [apache/incubator-mxnet#4520]
Im run the deep3d under mxnet (latest) and before the final I get this error:

TypeError: only integer scalar arrays can be converted to a scalar index

What is this? How can fix it?

**Comment by vasusharma** [comment]
Did you manage to fix this?

**Comment by BJ00D** [comment]
I have the same problem, what cudnn version are you using?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
