### ISSUE TITLE
mxnet 0.9.1 seems to be slower and use much more memory

### ISSUE THREAD

**Issue by marcociccone** [apache/incubator-mxnet#4525]
Hi, I just updated my system to the newest version of mxnet from the sources.
It seems to be using more memory and it is even slower compared to the previous version that I was using.

`cf00ca064d5f6e46b062c2027ae2905c6147a04c`

I'm not using CUDNN (because I need to deploy on a system that has cudnn2.. ), I'm using just the classic cuda backend and testing on inception v3 network.

```
python inceptionv3.py 
('Temp Space: ', 'Total 96 MB allocated')
('Avg forward per batch: ', 0.01688439130783081)

python inceptionv3.py 
('Temp Space: ', 'Total 169 MB allocated')
('Avg forward per batch: ', 0.020625998973846437)

```
Same thing on `example/memcost` passing from 41 to 74 MB...

Why is that? Are you still optimizing nnvm?
Do you have any suggestion?

**Comment by piiswrong** [comment]
@tqchen

**Comment by tqchen** [comment]
There is a change in pooling shape, which could affect the behaviour of inception model https://github.com/dmlc/mxnet/pull/2585 , and cause inception model description need to be updated.

I would be helpful if you can verify
- If the problem occurs in v0.8 tag
- Provide a script to reproduce the difference.

Thanks!

**Comment by marcociccone** [comment]
yes I've fix the shape in inception model adding a pad of 1 on the last pooling of factoryB. Thanks for sharing. Maybe it's better to fix it also in the master.

I verified in the v0.8 tag and it behaves in the same way of my previous version: less memory and less inference time... It seems that the new backend has some problems..

You can try the example memcost with the inception_memcost.py script or you can refer to this gist:

https://gist.github.com/marcociccone/0028b91e8b9267132195f9bf0ad43463

**Comment by tqchen** [comment]
I did not observe significant difference in the cudnn. For predict only task, this could due to the missing bulk execution mode, this is the only known missing piece that is not yet added back.

We can verify by setting environment variable  ```MXNET_EXEC_PREFER_BULK_EXEC=false``` in v0.8 to see if that is the case.

**Comment by marcociccone** [comment]
yes @tqchen ! your PR actually solved the issue! Thank you! 
I didn't try `MXNET_EXEC_PREFER_BULK_EXEC=false` yet, I'll let you know

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
