### ISSUE TITLE
Can't use multi-core CPU correctly!

### ISSUE THREAD

**Issue by dytmas** [apache/incubator-mxnet#4543]
Run on CPU with openblas and openmp.

Run the following code:
```
import time, os

def do(x, n):
    return [mx.nd.dot(x,x) for i in range(n)]

def wait(x):
    for y in x:
        y.wait_to_read()
        
tic = time.time()
a = mx.nd.ones((1000, 1000))
b = do(a, 1000)
print('time for pushed into backend engine:\n %f sec' % (time.time()-tic))
wait(b)
print('time for all finished:\n %f sec' % (time.time()-tic))
```

when OMP_NUM_THREADS = 4, it will take about 8-9s.
but when OMP_NUM_THREADS = 32, it will take about 28-32s.

I have checked and I am sure that when OMP_NUM_THREADS = 4,  4 cores are filled, when OMP_NUM_THREADS = 32, 32 cores are filled .

when I set a = mx.nd.ones((10000, 10000))
32 cores will be faster than 4 cores, but only about 2 times faster.

why mxnet or openblas can't use the power of multi-core cpu, in such a simple situation?

**Comment by howard0su** [comment]
Try to increase worker thread # as well:
export MXNET_CPU_WORKER_NTHREADS=16

**Comment by dytmas** [comment]
I found that changing $MXNET_CPU_WORKER_NTHREADS has no effect on the results. No matter it's 16, 32, or 1, the results are almost the same.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by daranday** [comment]
I'm still experiencing the same issue

**Comment by daranday** [comment]
This problem was addressed. Adding the export line increased the detection speed dramatically!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
@daranday's comment above says setting 'MXNET_CPU_WORKER_NTHREADS' fixes the problem. I'm closing this issue. Please reopen if that suggestion doesn't fix the problem. Thanks!

**Comment by duothink** [comment]
same issue
run the code as follow in multi-thread get a crash
```
        mxnet::cpp::Symbol data = mxnet::cpp::Symbol::Variable("data");
	mxnet::cpp::Symbol w = mxnet::cpp::Symbol::Variable("w");
	mxnet::cpp::Symbol b = mxnet::cpp::Symbol::Variable("b");
	mxnet::cpp::Symbol conv = mxnet::cpp::Convolution("convolution", data, w, b, kernal, filterNum);
	mxnet::cpp::Symbol activ = mxnet::cpp::Activation("activation", conv, mxnet::cpp::ActivationActType::tanh);
	mxnet::cpp::Symbol pool = Pooling("pooling", activ, poolKernal, mxnet::cpp::PoolingPoolType::max);
	{
		//boost::lock_guard<boost::mutex> lock(mutex_);
		std::map<std::string, mxnet::cpp::NDArray> args_map;
		args_map["data"] = ndData;
		args_map["w"] = ndWeight;
		args_map["b"] = ndBias;
		pool.InferArgsMap(mxnet::cpp::Context::cpu(), &args_map, args_map);
		mxnet::cpp::Executor *exec = pool.SimpleBind(mxnet::cpp::Context::cpu(), args_map);
		exec->Forward(false);

		exec->outputs[0].SyncCopyToCPU(pFeatures, exec->outputs[0].Size());
		exec->outputs[0].WaitToRead();
		delete exec;
	}
```
