### ISSUE TITLE
use Inception-bn to train ilsvrc12 dataset, the val accuracy will fluctuate strongly

### ISSUE THREAD

**Issue by blazerygy** [apache/incubator-mxnet#4557]
Why do I use Inception-bn to train ilsvrc12 dataset, the val accuracy will fluctuate strongly? 
 (ps: dist_async, 5 parameter servers, 5 wokers)
thx

**Comment by mli** [comment]
try `dist_sync`?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
