### ISSUE TITLE
GT750M is a bit slower than i5-3230M, is that normal ?

### ISSUE THREAD

**Issue by metorm** [apache/incubator-mxnet#4559]
I just installed the newest pre-compiled windows version[20170105_mxnet_x64_vc14_gpu]. I have cuda 8 and cudnn5 installed.

Then I run the following python code:

```
import mxnet as mx
import numpy as np
import time


def f():
    a = mx.nd.ones((1000, 1000))
    b = mx.nd.ones((1000, 1000))
    for i in range(5000000):
        a = mx.nd.dot(a, b)
    print('Done')
# in default mx.cpu() is used
start = time.time()
f()
end = time.time()
print(end - start)
# change the default context to the first GPU
with mx.Context(mx.gpu()):
    start = time.time()
    f()
    end = time.time()
    print(end - start)
```

Surprisingly, the output is:

```
Done
136.67168521881104
Done
148.3044981956482
```

GPU is a bit slower than CPU. I know GT750M is not a high-end GPU, but shall it be that slow? Or something else is wrong? I am sure GPU did work because GPU-z tell me that GPU load is about 90%

**Comment by mli** [comment]
try a larger matrix size

**Comment by metorm** [comment]
```
    a = mx.nd.ones((5000, 5000), dtype=np.float32)
    b = mx.nd.ones((5000, 5000), dtype=np.float32)
    for i in range(500000):
```

gives

```
Done
13.822206258773804
Done
15.38121771812439
```

Larger matrix size results in "out of memory error" on GPU

I'll try on other computers later. May be its time to get a new laptop ...

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
