### ISSUE TITLE
Python 3.5.2 Compabilitiy with mxnet ?

### ISSUE THREAD

**Issue by jiapei100** [apache/incubator-mxnet#4560]
Hi :
I just wonder if current mxnet-git compatible with Python 3.5.2???

## Environment info
Operating System:
Ubuntu 16.04.1

Compiler:
GCC/G++ 5.4.0

Package used (Python/R/Scala/Julia):
Python 3.5.2 

MXNet version:
0.9.1 (Current-git)

Or if installed from source:
Yes, install from source

MXNet commit hash (`git rev-parse HEAD`):
1ae2905cc3c2e35541d45edab18ddffb9cf455da

If you are using python package, please provide
Python 3.5.2 

Python version and distribution:
3.5.2

## Error Message:
Please paste the full error message, including stack trace.
```
RefactoringTool: Warnings/messages while refactoring:
RefactoringTool: ### In file ./example/image-classification/symbol/inception-resnet-v2.py ###
RefactoringTool: Line 111: You should use 'operator.mul(tower_5b_out, 10, block35, scale=0.17, input_num_channels=320)' here.
RefactoringTool: Line 119: You should use 'operator.mul(net, 20, block17, scale=0.1, input_num_channels=1088)' here.
RefactoringTool: Line 132: You should use 'operator.mul(net, 9, block8, scale=0.2, input_num_channels=2080)' here.
RefactoringTool: There was 1 error:
RefactoringTool: Can't parse ./example/fcn-xs/image_segmentaion.py: IndentationError: unindent does not match any outer indentation level (<tokenize>, line 22)

```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Trying to convert all .py files from version 2 to version 3 by using command "2to3" .

Cheers
Pei

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
