### ISSUE TITLE
Installation problem while make -j$(nproc)

### ISSUE THREAD

**Issue by cliveysk** [apache/incubator-mxnet#4566]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Compiler: gcc 5.4

Package used (Python/R/Scala/Julia): R

MXNet version: 0.9.1

Or if installed from source: check out from github

MXNet commit hash (`git rev-parse HEAD`):b67a4457ffd162ce8e7b7eca96285111362e74b9

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. follow standard installation step to build mxnet
2. make -j$(nproc)

the following compilation error appear:
build/src/operator/convolution_gpu.o: In function `mxnet::op::CuDNNConvolutionOp<float>::SelectAlgo(mxnet::Context const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const':
/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:568: undefined reference to `mxnet::op::CuDNNAlgoReg::Get()'
build/src/operator/convolution_gpu.o: In function `mxnet::op::CuDNNConvolutionOp<double>::SelectAlgo(mxnet::Context const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const':
/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:568: undefined reference to `mxnet::op::CuDNNAlgoReg::Get()'
build/src/operator/convolution_gpu.o: In function `mxnet::op::CuDNNConvolutionOp<mshadow::half::half_t>::SelectAlgo(mxnet::Context const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const':
/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:568: undefined reference to `mxnet::op::CuDNNAlgoReg::Get()'
build/src/operator/convolution_gpu.o: In function `mxnet::op::CuDNNConvolutionOp<float>::SelectAlgo(mxnet::Context const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&)':
/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:471: undefined reference to `mxnet::op::CuDNNAlgoReg::Get()'
/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:472: undefined reference to `mxnet::op::CuDNNAlgoReg::Get()'
build/src/operator/convolution_gpu.o:/home/clive/mxnet/src/operator/./cudnn_convolution-inl.h:471: more undefined references to `mxnet::op::CuDNNAlgoReg::Get()' follow
collect2: error: ld returned 1 exit status
Makefile:259: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
git pull && git submodule init && git submodule update && make clean && make -j$(nproc)

**Comment by jingpengwu** [comment]
I got the same error with release version v0.9.3. 

This error got fixed after following @piiswrong 's suggestion. It is due to outdated submodule packages, if you manually checkout the submodules, it probably will work too.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
