### ISSUE TITLE
The batch size of training data should no greater than the batch size of test data

### ISSUE THREAD

**Issue by greatwall1995** [apache/incubator-mxnet#4576]
## Environment info
Operating System: Linux Mint 18.1

Compiler: python 2.7

MXNet version: Maybe 0.8.0. It was downloaded several days ago.

MXNet commit hash (`git rev-parse HEAD`): a3a928c21ab91b246a5fab7c9ec135f6e616f899

If you are using python package, please provide: numpy, sklearn

Python version and distribution: 2.7

## Error Message:
Please paste the full error message, including stack trace.

> MXNetError: [15:57:49] include/mxnet/ndarray.h:259: Check failed: (shape_[0]) >= (end) Slice end index out of range

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Open svm_mnist.py
2. Change the batch_size in line 55 and 56. For example, we can change them to 100, 99 respectively.
3. If the batch_size of training data is larger than it in the test, the code would fail to run.

## What have you tried to solve it?

1.
2.
3.

**Comment by janelu9** [comment]
I find that the simples will be lost if their bucket size smaller than the batch size
so when your batch_size is lager than the test_num , all will be lost, none is test

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
