### ISSUE TITLE
how to use mx.sym.dot

### ISSUE THREAD

**Issue by Eshter** [apache/incubator-mxnet#4577]
In mxnet, I HAVE no idea about how to use the mx.sym.dot, hope u can help me

**Comment by Eshter** [comment]
For example, i want a row vector in a matrix TO dot-multiply with a row vector in another matrix ，but I do not want to do for operation, is there any easy ways to solve this,,,

**Comment by sxjscience** [comment]
@Eshter Use batch_dot for the case http://mxnet.io/api/python/symbol.html#mxnet.symbol.batch_dot

**Comment by Eshter** [comment]
why are u closing this？

**Comment by sxjscience** [comment]
@Eshter

For example, assume `MatA` has shape (B, 1, C) and `MatB` also has shape (B, 1, C). Our goal is to get the `ret` of size (B, 1, 1) by dot-multiply the corresponding row-vectors in two matrices.

There are two ways to achieve this:

1) Elementwise multiplication and use `mx.nd.sum`
```python
ret = mx.nd.sum(MatA * MatB, axis=-1, keepdims=True)
```
2) Use `mx.nd.batch_dot`
```python
ret = mx.nd.batch_dot(MatA, MatB, transpose_b=True)
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
