### ISSUE TITLE
Source operators prevent fast symbol resizing

### ISSUE THREAD

**Issue by taliesinb** [apache/incubator-mxnet#4581]
Stochastic source ops / sample ops are useful, obviously. While it is possible to sample from random distributions *outside* of your network and provide the randomness as input, this is slower, more complicated, and makes the graph less self-contained.

However, there is a problem with using the source ops like 'normal' and 'uniform' as it stands, which is that they break an important property of an symbol/graph: resizability. It is highly desirable to be able to resize an existing symbol by simply doing shape inference using a different batch size of the relevant input tensors, rather than the alternative of generating a completely new symbol/graph each time you want to use a different batch size. 

A very important application of fast resizing is when evaluating a net on a large set of user inputs. One obviously should break the input into batches that match the batch size one chose for the evaluation network, but there will be in general a 'leftover' part at the end, and to generate a whole new graph to evaluate that leftover part (or using junk data) will often be slower than the ideal thing, which is to fast resize to the length of the final piece, then evaluate. 

There are others examples of the value of fast resizability, probably the most important one is for me is dealing with variable-length sequence networks when unrolling can be avoided (e.g. using the RNN op), where creating buckets quickly is again very desirable.

For a concrete example of how resizability can be broken by sample ops, let's take variational dropout (https://arxiv.org/abs/1512.05287). That's straightforward to implement by sampling from a bernoulli distribution and then doing a broadcast multiply onto the sequence tensor. The problem here is that the batch size needs to be hardcoded into the sample op's 'shape' parameter, because backward shape inference doesn't pass through broadcast layers (as broadcast is 'polymorphic': it has multiple input shapes that would work with the output shape). 

And even if we make a variational dropout op or modify the existing dropout op to be able to do broadcasting internally, we can't depend on backward shape inference to solve this problem for user-defined networks that come from a high level framework like that of Mathematica. The user might want to do a reshape or broadcast of a random source, and then again MXNet will not be able to figure out the batch size to use for the sample op. 

I have prototyped a solution for this already was pretty straightforward to implement and simple to reason about, but it does require making a small modification to the nnvm backprop engine, so first I'd first like to ask what the preference of the core MXNet developers is to solve this problem. I can go into detail about my proposed solution if that is desired.

**Comment by taliesinb** [comment]
@sbodenstein

**Comment by piiswrong** [comment]
see https://github.com/dmlc/mxnet/pull/4586

After this PR you can specify partial shape like (0, 100) for arbitrary batchsize

**Comment by piiswrong** [comment]
any updates on this?

**Comment by taliesinb** [comment]
@piiswrong I'm very sorry, we were hard at work getting ready for a freeze and I lost track of this thread. I see that #4586 is now closed, but aside from that, was the idea that the random source could be given partial size information using '0' for "don't know", and then that 0 would be resolved with backward inference later? I don't see how that would overcome the problem I described in which backward shape inference cannot in principle go through certain operators (e.g. Resize) that are on the DAG between the place where batch information is available (the layer output the sequences on which you want to apply variational dropout for example) to where the batch information is needed (the random source).

**Comment by taliesinb** [comment]
For the record the way that we ended up solving this is to have a 'useless' arg node, of dimensions (batch, n1, n2, ...) that we control and initialize to all zeros to which we add the random source. The resizer code knows about this arg node and can change its initial dimension size and have the rest of the graph infer in forward-mode correctly, with just one step of backward inference that reaches the random source. Slightly wasteful but completely reliable.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
