### ISSUE TITLE
how to save and load a DataIter or mx.io.NDArrayIter for the python program?

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#4591]
the following code is the DataIter of lstm.py, I want to save the local filesytem.

After saving, when the training, I  load the DataIter. I don't want to build the DataIter again when train the model. Thank you very much for a help!

```python
data_train = bucket_io.BucketSentenceIter(
    "./obama.txt", 
    vocab, 
    [seq_len], 
    batch_size,             
    init_states, 
    seperate_char='\n',
    text2id=text2id, 
    read_content=read_content)
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
