### ISSUE TITLE
Grad Error

### ISSUE THREAD

**Issue by TommeyChang** [apache/incubator-mxnet#4596]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: OSX 10.12.2

Compiler: gcc 4.2.1

Package used (Python/R/Scala/Julia): Python

If you are using python package, please provide

Python version and distribution:2.7.12

## Error Message:
Please paste the full error message, including stack trace.

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-15-7c0c69847072> in <module>()
----> 1 x = c.grad(wrt=('a'))
      2 print x.list_arguments()
      3 print x.list_outputs()
      4 
      5 ex2 = x.bind(ctx=mx.cpu(), args={c.name+'_0_grad': mx.nd.ones([3,4])*5, 

/usr/local/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/symbol.pyc in grad(self, wrt)
    951                                      mx_uint(len(wrt)),
    952                                      c_wrt,
--> 953                                      ctypes.byref(handle)))
    954         return Symbol(handle)
    955     # pylint: enable= no-member

/usr/local/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/base.pyc in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise MXNetError(py_str(_LIB.MXGetLastError()))
     76 
     77 if sys.version_info[0] < 3:

MXNetError: [20:02:11] src/c_api/c_api_symbolic.cc:534: not implemented

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010e345b18 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010e8ee938 MXSymbolGrad + 88
[bt] (2) 2   _ctypes.so                          0x000000010bd097f7 ffi_call_unix64 + 79
[bt] (3) 3   ???                                 0x00007fff549ab0f0 0x0 + 140734612812016

**Comment by piiswrong** [comment]
@tqchen

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
