### ISSUE TITLE
NDArray saved in file with GPU context can't be loaded by NDArray in CPU only environment.

### ISSUE THREAD

**Issue by DamonDeng** [apache/incubator-mxnet#4597]
NDArray saved in file with GPU context can't be loaded by NDArray in CPU only environment.

If GPU context was saved together with the data in NDArray saved file, it can't be loaded back as NDArray in CPU only environment.

In the source code of src/ndarray/ndarray.cc, we can find the following code in `NDArray::load(dmlc::Stream *strm)` method:

	  if (strm->Read(load_data.dptr_, nread) != nread) return false;
	  if (ctx.dev_mask() == cpu::kDevMask) {
	    *this = std::move(temp); return true;
	  } else {
	    *this = temp.Copy(ctx); return true;
	  }

The loading code will check the Context of reading file, if the Context in that file is GPU, it will call `NDArray::Copy()` method, which will finally call CUDA lib to copy data from GPU to CPU.

While, in CPU only environment, CUDA is not enabled, so the operation will cause "GPU not enabled" fatal error.

The issue can be fixed by simply adding `#if MXNET_USE_CUDA` as the following code.

But I am not sure whether it is a good coding style matching MXNet, please comment.

If it is OK, one Pull Request will be created for this.

	  if (strm->Read(load_data.dptr_, nread) != nread) return false;
	  if (ctx.dev_mask() == cpu::kDevMask) {
	    *this = std::move(temp); return true;
	  } else {
	#if MXNET_USE_CUDA
	    *this = temp.Copy(ctx); return true;
	#else
	    *this = std::move(temp); return true;
	#endif
	  }

**Comment by piiswrong** [comment]
Yes I think this is a good solution
