### ISSUE TITLE
Why I get different training performance with same NVIDIA cards?

### ISSUE THREAD

**Issue by PhanTask** [apache/incubator-mxnet#4610]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 14.04 desktop 64bit

Compiler:gcc

Package used (Python/R/Scala/Julia):python

MXNet version:0.7

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:python2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message

EARLY VERSION:
I have two PC(both Ubuntu 14.04 64bit), one with GTX750Ti(2GB) / Intel I5x4 and the other with GTX1060 (6GB)  / Intel I7x8. I trained a customized SSD example with GTX750Ti and I got the speed at around 90 samples/sec, but when I tried GTX1060 I got only around 40 samples/sec. Why? GTX1060 should get better performance right?

UPDATE:
Just now I get another GTX750Ti(2GB) and I build a CUDA8/CUDNN5.1/MXNET environment on another computer(all the same, except the CPU Intel I7x8).
The same thing happened. On this card I get the poor performance too(max to about 45 samples/sec when training my own SSD example, while I get about 80 samples/sec on my first GTX750Ti).
I checked nvidia-smi of both GTX750Ti per second when training, and I found that the GTX750Ti with good performance showed stable volatile GPU-Util around 95%, but the one with bad performance showed quite a unstable volatile GPU-Util (ranged from 20% to 95%). Later I checked GTX1060 too, and its volatile GPU-Util ranged from 0% to 49%.
So it seems like there is something wrong in my latest cuda/mxnet environment built, not GTX1060's problem.

Environment:
CUDA:8.0   
CUDNN:5.1
NVIDIA DRIVER:375.20
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.python train.py
2.
3.

## What have you tried to solve it?

1.I  tried the nvidia 367 driver but it showed no difference.
2.I reinstalled CUDA8.0 CUDNN5.1 and recompiled mxnet, but still no difference.

**Comment by PhanTask** [comment]
Oh, just now I trained two networks (extremely light one and extremely heavy one) and I got the similiar speed around 36 ~ 40 with GTX1060. It seems my GTX1060 is "leashed"... How can I slove this?

**Comment by piiswrong** [comment]
try dmlc/deepmark-mxnet and see if 1060 is faster than 750

**Comment by PhanTask** [comment]
@piiswrong Hi, I tried dmlc/deepmark-mxnet and it turned out that GTX1060 is definitely faster than GTX750Ti.
(vgg/resnet/alexnet:         GTX1060:46/31/12         GTX750Ti:120/75/26)
But in my SSD example it is just like there is a upper limit to my GTX1060(max to about 45 samples/sec), which didn't happen on my GTX750Ti...Could you give me some suggestions?

**Comment by PhanTask** [comment]
@piiswrong Em...Just now I get another GTX750Ti(2GB) and I build a CUDA8/CUDNN5.1/MXNET environment on another computer(all the same, except the CPU Intel I7x8).
The same thing happened. On this card I get the poor performance too(max to about 45 samples/sec when training my own SSD example, while I get about 80 samples/sec on my first GTX750Ti).
I checked nvidia-smi of both GTX750Ti per second when training, and I found that the GTX750Ti with good performance showed stable volatile GPU-Util around 95%, but the one with bad performance showed quite a unstable volatile GPU-Util (ranged from 20% to 95%). Later I checked GTX1060 too, and its volatile GPU-Util ranged from 0% to 49%.
So it seems like there is something wrong in my latest cuda/mxnet environment built, not GTX1060's problem. 
But I can't remember the difference because the first GTX750Ti environment was built long time ago. Do you know what kind of wrong setting would lead to this huge difference?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
