### ISSUE TITLE
==MXNet Project Ideas==

### ISSUE THREAD

**Issue by howard0su** [apache/incubator-mxnet#4613]
This issue is intent to maintain a list of some ongoing projects, or some project ideas. This is a prefect places for anyone who want to contribute to the projects. No matter you are beginner to Deep learning, or you are expert in this area, you can always find some projects to work with.

## Fix Issues
There are many user reported small issues in the GitHub. Grab one, fix it and submit PR

### Skill Needed: DL basic
Several APIs, functions or function argument is deprecated in 0.8. We need clean up example so that we don't carry those deprecated API forward. Some common used: 
[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
src/operator/tensor/./matrix_op-inl.h:155: Using target_shape will be deprecated.

### Skill Needed: Python, some c++
In order to release binary package to support various hardware and software configurations, like GPU, CUDNN presents, we need some code to handle this gracefully. some issues reported on the problem that fails run binary compiled with CUDA on non-CUDA machine are fixed. Need some volunteer to look at this issue and build package. If publish to some common repo, it will be even greater.

### Skill Needed: Python, some c++ skill
This project is aiming to bring Tensorboard as the virtualization tool for MXNet. It is already working but need help to support more features.

### Skill Needed: English Writing
MXNet documentation can be improved in many aspects. For example, it is great that this article can have a similar one for mxnet: http://stackoverflow.com/questions/33962226/common-causes-of-nans-during-training?noredirect=1

### Skill Needed: English Read, Chinese writing
There are already several documents are translated into Chinese. But we need more and a lot more. This will help us growing our community in Chinese community.

### Skill needed: C++, Performance profiling
In order to scale better on multi GPU when training the model with complex data pipeline, the performance of CPU executing operation becomes very critical. MXNet need more tuning in this area.

### Skill needed: Python, DL basic
Although you can use mxnet in ipython today fine, however there are several low hang fruit can improve the experience a lot. 
- Improve to_string for various important objects, like NDArray, symbol, model, iter, etc.
- Improve the default values for common used functions. like model.fit, and provides more sensible default values.

**Comment by zihaolucky** [comment]
Yes, the Tensorboard project only supports `scalar` and `histogram`, we need to support `image`, `video`, even `graph` and `embedding`. All the above are logging components.

There're other works to do beyond the logging, we're going to merge Tensorboard into MXNet, but currently users have to build it from scratch and make the whole installation too heavy(I'm not sure if it's acceptable). I was going to write a script to auto-build the wheel file using Travis-CI and user could install TensorBoard simply using `pip install tensorboard`, just like TF does. It needs some effects.

**Comment by zihaolucky** [comment]
Besides, the logging part could be extended to other languages, as long as we have same logging format.

**Comment by zihaolucky** [comment]
Update. `image` is now supported. I'm going to make TensorBoard easy to install by `pip install tensorboard` in the next few weeks. Then try to finish the rest `audio`, `graph` and `embedding`, might need some time. 

As we've finished the `image`, the **visualization toolbox for MXNet** could be started, my plan is to support the common visualization techniques to understand the neural network, like CS231n does.  @piiswrong @mufeili

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
