### ISSUE TITLE
Distributed training problem

### ISSUE THREAD

**Issue by zmonoid** [apache/incubator-mxnet#4614]
For distributed training, I am facing the following issue:

the default dmlc_tracker ssh does not source '.bashrc'.

Therefore, it cannot use ananconda's package, and cannot find cuda's so package position, and report error like this:
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Is there anyway to solve this problem, like add 'source .bashrc' into the beginning ssh commands?

Solution:
**Need to modify dmlc-core/...../ssh.py
Add 'source .zshrc' to prog.**

New problem:
After launch distributed learning,
**In htop, we can clearly see the process is running.
However, in nvidia-smi we cannot see the activity.**
And the root machine's printout does not have anything.

What may be the cause?

Best,
Zhou

**Comment by zmonoid** [comment]
@mli 
Here is how it looks like:

```
➜  bandwidth git:(master) ✗ python ../launch.py -H hosts -n 1 python measure.py --kv-store dist_device_sync --gpus 0 --network resnet --num-layers 200
INFO:root:Namespace(disp_batches=1, gpus='0', image_shape='3,224,224', kv_store='dist_device_sync', network='resnet', num_batches=5, num_classes=1000, num_layers=200, optimizer='None', test_results=1)
```

However, the program will halt here and does not print anything. In the slave machine(ip in hosts file), we can find the process using htop, but not in nvidia-smi

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
