### ISSUE TITLE
The  key words of mx.symbol.Variable()

### ISSUE THREAD

**Issue by BingzheWu** [apache/incubator-mxnet#4622]
In the document [http://mxnet.io/api/python/symbol.html#mxnet.symbol.Variable](url), It says that Variable() has a key word dtype. But in the Python implement code, there isn't.

**Comment by WellyZhang** [comment]
Maybe you have the wrong MXNet version, but in the latest version, it is just [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/symbol.py#L958-L999).

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
