### ISSUE TITLE
dtype of Convolution weights.

### ISSUE THREAD

**Issue by BingzheWu** [apache/incubator-mxnet#4623]
Can I use weight of Convolution with uint8 dtype? Or there is any solution to make mxnet  surport this?

**Comment by Godricly** [comment]
only half, float and double are supported in convolution now. You need to write your own implementation.

**Comment by piiswrong** [comment]
should be pretty easy
change https://github.com/dmlc/mxnet/blob/master/src/operator/convolution.cc#L57 to MSHADOW_TYPE_SWITCH and add uint8 to dtype in ConvolutionParam

**Comment by feiyulv** [comment]
It seems cudnn doesn't support unit8 convolution yet

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
