### ISSUE TITLE
memcost/Makefile

### ISSUE THREAD

**Issue by my777777** [apache/incubator-mxnet#4632]
I noticed that the file "Makefile" has been modified, the prefix mxnet_ replaced by nnvm_.
Then I type the command to see the allocation cost. However, the result of command "make with_inplace", "make with_sharing" and "make with_both" is same, is this a normal phenomenon?

**Comment by piiswrong** [comment]
@tqchen

**Comment by tqchen** [comment]
please make sure the mxnet is reinstalled in the latest version. The script is meant to work with the correspondent version in the master branch

**Comment by my777777** [comment]
I believe the version of mxnet is latest... this is some output on the terminal

mayang@gpu-cluster-2:~/mxnet$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
mayang@gpu-cluster-2:~/mxnet$ cd example/memcost
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make no_optimization
Estimating the cost with no optimization...
Total 2781 MB allocated
mayang@gpu-cluster-2:~/mxnet/example/memcost$ **make with_inplace**
Estimating the cost with inplace optimization...
**Total 1340 MB allocated**
mayang@gpu-cluster-2:~/mxnet/example/memcost$ **make with_sharing**
Estimating the cost with memory sharing ...
**Total 1340 MB allocated**
mayang@gpu-cluster-2:~/mxnet/example/memcost$ **make with_both**
Estimating the cost with all optimizations ...
**Total 1340 MB allocated**
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make forward_only
Estimating the cost of forward only ...
Total 242 MB allocated

**Comment by my777777** [comment]
I believe the version of mxnet is latest... this is some output on the terminal

mayang@gpu-cluster-2:~/mxnet$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
mayang@gpu-cluster-2:~/mxnet$ cd example/memcost
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make no_optimization
Estimating the cost with no optimization...
Total 2781 MB allocated
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make with_inplace
Estimating the cost with inplace optimization...
Total 1340 MB allocated
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make with_sharing
Estimating the cost with memory sharing ...
Total 1340 MB allocated
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make with_both
Estimating the cost with all optimizations ...
Total 1340 MB allocated
mayang@gpu-cluster-2:~/mxnet/example/memcost$ make forward_only
Estimating the cost of forward only ...
Total 242 MB allocated

**Comment by piiswrong** [comment]
I can reproduce:
```
c4b301d74d83:memcost junyuanx$ make with_inplace
Estimating the cost with inplace optimization...
Total 1340 MB allocated
c4b301d74d83:memcost junyuanx$ vim Makefile 
c4b301d74d83:memcost junyuanx$ make with_sharing
Estimating the cost with memory sharing ...
Total 1340 MB allocated
c4b301d74d83:memcost junyuanx$ vim Makefile 
c4b301d74d83:memcost junyuanx$ make with_both
Estimating the cost with all optimizations ...
Total 1340 MB allocated
```
Maybe the flags are not working

**Comment by blueardour** [comment]
@tqchen
Hi, could it be possible to automatically load network from the json file and report the memory usage? If then, could you please give an example?

**Comment by blueardour** [comment]
OK, I have finish load the VGG16.json file.

Just replace the softmax = mx.symbol.load('vgg16.json')

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
