### ISSUE TITLE
.base import MXNetError?

### ISSUE THREAD

**Issue by wguo68** [apache/incubator-mxnet#4634]
ImportError                               Traceback (most recent call last)
<ipython-input-2-36f7894d9f39> in <module>()
----> 1 import mxnet as mx
      2 
      3 def to4d(img):
      4     return img.reshape(img.shape[0], 1, 28, 28).astype(np.float32)/255
      5 

/home/d/mxnet/python/mxnet/__init__.py in <module>()
      5 
      6 from .context import Context, current_context, cpu, gpu
----> 7 from .base import MXNetError
      8 from . import base
      9 from . import ndarray

/home/d/mxnet/python/mxnet/base.py in <module>()
      8 import atexit
      9 import numpy as np
---> 10 from . import libinfo
     11 
     12 __all__ = ['MXNetError']

ImportError: cannot import name libinfo

**Comment by tornadomeet** [comment]
information is not enough.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
