### ISSUE TITLE
I use multilayer bidirectional LSTM and CTC to train, but Train-Accuracy is 0

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#4635]
Here is my code

`
def bi_lstm_unroll_concat_first(seq_len, num_hidden, num_label, num_lstm_layer):
    forward_param_cell = []
    backward_param_cell = []
    forward_last_states = []
    backward_last_states = []

    for i in range(num_lstm_layer):

        forward_param_cell.append(LSTMParam(i2h_weight=mx.sym.Variable("forward_l%d_i2h_weight" % i),
                                     i2h_bias=mx.sym.Variable("forward_l%d_i2h_bias" % i),
                                     h2h_weight=mx.sym.Variable("forward_l%d_h2h_weight" % i),
                                     h2h_bias=mx.sym.Variable("forward_%d_h2h_bias" % i)))
        forward_state = LSTMState(c=mx.sym.Variable("forward_l%d_init_c" % i),
                          h=mx.sym.Variable("forward_l%d_init_h" % i))
        forward_last_states.append(forward_state)

        backward_param_cell.append(LSTMParam(i2h_weight=mx.sym.Variable("backward_l%d_i2h_weight" % i),
                                            i2h_bias=mx.sym.Variable("backward_l%d_i2h_bias" % i),
                                            h2h_weight=mx.sym.Variable("backward_l%d_h2h_weight" % i),
                                            h2h_bias=mx.sym.Variable("backward_%d_h2h_bias" % i)))
        backward_state = LSTMState(c=mx.sym.Variable("backward_l%d_init_c" % i),
                                  h=mx.sym.Variable("backward_l%d_init_h" % i))
        backward_last_states.append(backward_state)

    data = mx.sym.Variable('data')
    label = mx.sym.Variable('label')
    wordvec = mx.sym.SliceChannel(data=data, num_outputs=seq_len, squeeze_axis=1)

    hidden = [wordvec[i] for i in range(seq_len)]
    forward_hidden = range(seq_len)
    backward_hidden = range(seq_len)

    for layeridx in range(num_lstm_layer):

        for seqidx in range(seq_len):

            forward_next_state = lstm(num_hidden, indata=hidden[seqidx],
                              prev_state=forward_last_states[layeridx],
                              param=forward_param_cell[layeridx],
                              seqidx=seqidx, layeridx=layeridx)

            forward_hidden[seqidx] = forward_next_state.h
            forward_last_states[layeridx] = forward_next_state

            k = seq_len - seqidx - 1
            backward_next_state = lstm(num_hidden, indata=hidden[k],
                              prev_state=backward_last_states[layeridx],
                              param=backward_param_cell[layeridx],
                              seqidx=k, layeridx=layeridx)

            backward_hidden[k] = backward_next_state.h
            backward_last_states[layeridx] = backward_next_state

        for seqidx in range(seq_len):

            hidden[seqidx] = mx.sym.Concat(*[forward_hidden[i], backward_hidden[i]], dim=1)

    hidden_concat = mx.sym.Concat(*hidden, dim=0)

    pred = mx.sym.FullyConnected(data=hidden_concat, num_hidden=70)

    label = mx.sym.Reshape(data=label, shape=(-1,))
    label = mx.sym.Cast(data = label, dtype = 'int32')
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)

    return sm
`

**Comment by poorfriend** [comment]
Is any mistake in bi_lstm_unroll_concat_first

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
