### ISSUE TITLE
the validation curve of imagenet has oscillation , anyone else met this problem?

### ISSUE THREAD

**Issue by StarrySky1213** [apache/incubator-mxnet#4637]
## Environment info
Operating System:
ubuntu
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.7
Or if installed from source:
yes
Python version and distribution:
2.7

## Error Message:

when I train the imagenet using inception-bn(using sync and async), I met a problem that the validation accuracy of imagenet has oscillation (but the train accuracy is normal) . For example ,from epoch 0 to epoch 10 ,the validation accuracy is increased from 0 to 0.5, however at epoch 11, the validation is suddently decreased to 0.2. it can happen many times during the train ,making me feel confused.

I want to ask if there was anyone else who met the same problem?
or who can show me the right curve of validation accuracy of imagenet(include sync and async)?
I want to know the right curve of validation accuracy of iamgenet.

Thanks a lot.^_^

**Comment by tornadomeet** [comment]
you can found the resnet-50 val acc curve in the exmaple, https://github.com/dmlc/mxnet/tree/master/example/image-classification#convergence

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
