### ISSUE TITLE
issue using sgd with momentum

### ISSUE THREAD

**Issue by animebing** [apache/incubator-mxnet#4638]
When I use sgd with momentum, I train for 10 epoches first and save the parameters, but the state created by mx.optimizer.Updater for gradient updates with momentum is not saved, so if I want to train the same model from 10th epoch, the state will be initialized with all zeros, which is not what i want, so i want to know whether there is the solution to this problem? Thanks

**Comment by piiswrong** [comment]
use mx.callback.module_checkpoint with mx.mod.Module

**Comment by animebing** [comment]
@piiswrong thanks for your help

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
