### ISSUE TITLE
Shared gamma for BatchNorm

### ISSUE THREAD

**Issue by assafmus** [apache/incubator-mxnet#4639]
I was wondering if it is possible to have multiple BatchNorm layers that use the same gamma variable?

I couldn't find how to define the variable name similar to what is done for convolution layer  here https://github.com/dmlc/mxnet/issues/557

**Comment by piiswrong** [comment]
you can do the same thing for batchnorm

**Comment by assafmus** [comment]
How? 
I don't see any arguments except for the data. 
Can you give me a code example?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
