### ISSUE TITLE
my mxnet was automatically installed under python 2.7 while I use anaconda for python 3.5

### ISSUE THREAD

**Issue by ffflycnffflycnffflycn** [apache/incubator-mxnet#4651]
Hi,

I installed mxnet in linux mint. I use anaconda for python 3.5. I followed the instruction and it was successfully installed. Both mxnet and the anaconda are latest version. However, when I tried the code:

import mxnet as mx
res = mx.nd.array([1,2,3])

I got the error: AttributeError: module 'mxnet' has no attribute 'nd'

if I  typed "mx", I got: <module 'mxnet' (namespace)>

after repeating the installation and checking the scripts, I saw mxnet was installed under python 2.7. How can change it to python 3.5? Thanks.

Regards,

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
