### ISSUE TITLE
Are the training samples in each batch randomly picked from the whole bag of training data? 

### ISSUE THREAD

**Issue by darrylbobo** [apache/incubator-mxnet#4652]
I am just curious about if the samples in each batch are randomly sampled from the bag of whole training data? 

If so, is there a way to ensure the ratio of positive and negative samples in each batch? 

Thanks.

**Comment by janelu9** [comment]
randomly sorted not sampled, only few samples are lost. others are all trained

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
