### ISSUE TITLE
cudnn-convolution performance tests on cnn-lstm-ctc

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#4660]
## Environment info
Operating System: ubuntu 14.04

Compiler: gcc 4.8

Package used (Python/R/Scala/Julia): python

MXNet version: 0.9.1 (0.7.1 nightly 32cb6bc)

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 32cb6bc

If you are using python package, please provide

Python version and distribution: anaconda 2.7.11

## Error Message:
I used cnn-lstm-ctc to do ocr tasks, and it can work well with mxnet 0.7 version, but when I use the latest mxnet version 0.9.1 it will block here forever :
```
src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while...
```
## Steps to reproduce
1.
2.
3.

**Comment by poorfriend** [comment]
@xinghedyc ,can you release your predict code, i don't know how to predict
here is my issue ,can you help me[4650](https://github.com/dmlc/mxnet/issues/4650)

**Comment by piiswrong** [comment]
`export MXNET_CUDNN_AUTOTUNE_DEFAULT=0` to disable this

**Comment by xinghedyc** [comment]
@poorfriend I haven't write predict code yet, I will try the following days, if I make it , I'll inform you for sure.
@piiswrong Thanks a lot ,I'll try it and send you feedback later.

**Comment by xinghedyc** [comment]
@piiswrong when I try to run example in warp-ctc/toy-ctc.py, it also block here :
```
~/mxnet/example/warpctc$ python toy_ctc.py
WARNING:root:[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
begin fit
```
when I crtl + c to stop the job here is the log :
```
File "toy_ctc.py", line 162, in <module>
    batch_end_callback=mx.callback.Speedometer(BATCH_SIZE, 50),)
  File "../../python/mxnet/model.py", line 814, in fit
    sym_gen=self.sym_gen)
  File "../../python/mxnet/model.py", line 259, in _train_multi_device
    executor_manager.update_metric(eval_metric, data_batch.label)
  File "../../python/mxnet/executor_manager.py", line 425, in update_metric
    self.curr_execgrp.update_metric(metric, labels)
  File "../../python/mxnet/executor_manager.py", line 277, in update_metric
    metric.update(labels_slice, texec.outputs)
  File "../../python/mxnet/metric.py", line 348, in update
    pred = pred.asnumpy()
  File "../../python/mxnet/ndarray.py", line 500, in asnumpy
    ctypes.c_size_t(data.size)))
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
