### ISSUE TITLE
Installation error of Installation MXNet for Python(Installing Python package for MXNet)

### ISSUE THREAD

**Issue by guo253** [apache/incubator-mxnet#4665]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
【ubuntu 14.04】
Compiler:
 【gcc version 4.8.4】
【 g++ version 4.8.4】
Package used (Python/R/Scala/Julia):
【Python 2.7.6】
MXNet version:
 【20170113 download】
If you are using python package, please provide

Python version and distribution:
【Python 2.7.6】
【Cython version 0.20.1post0】

## Error Message:
Quick Installation
Install MXNet for Python
bash install-mxnet-ubuntu-python.sh
－－－－－－－－－－－－－－－－－－－－
... ...
Installing Numpy...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python-numpy 已经是最新的版本了。
下列软件包是自动安装的并且现在不需要了：
  fonts-font-awesome ipython-notebook-common kde-l10n-engb kde-l10n-zhcn
  libjs-highlight libjs-jquery-ui libjs-marked libpgm-5.1-0 libzmq3
  python-simplegeneric python-zmq
Use 'apt-get autoremove' to remove them.
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 698 个软件包未被升级。
Installing Python setuptools...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python-setuptools 已经是最新的版本了。
python-pip 已经是最新的版本了。
下列软件包是自动安装的并且现在不需要了：
  fonts-font-awesome ipython-notebook-common kde-l10n-engb kde-l10n-zhcn
  libjs-highlight libjs-jquery-ui libjs-marked libpgm-5.1-0 libzmq3
  python-simplegeneric python-zmq
Use 'apt-get autoremove' to remove them.
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 698 个软件包未被升级。

Installing Python package for MXNet...
Compiling mxnet/cython/symbol.pyx because it changed.
Compiling mxnet/cython/ndarray.pyx because it changed.
Cythonizing mxnet/cython/ndarray.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        svec[i] = vec[i].c_str()
    return svec

cdef extern from "nnvm/c_api.h":
    const char* NNGetLastError();
                               ^
------------------------------------------------------------

mxnet/cython/./base.pyi:54:32: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    ext_modules=config_cython())
  File "setup.py", line 53, in config_cython
    return cythonize(ret)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: mxnet/cython/ndarray.pyx

Thank you very much!

**Comment by piiswrong** [comment]
@tqchen 
you can turn off cython support by removing make cython from the script.

**Comment by guo253** [comment]
@piiswrong 
Thanks for your help.
I have completed the installation following your advise by modifying the setup.py and Makefile.

But the questions are:
     Do I need cython in the future?
     Is the wrong my method of installation or the version of mxnet?

Thank you again.

**Comment by acaridor** [comment]
I met the same problem when attempting to setup python interface.  An incompatible Cython version, perhaps?

**Comment by maxenceliu** [comment]
Same question? Is there any potential problem if we fix this problem like this?

**Comment by cheneyfan** [comment]
@guo253 , can you share the specific step?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
