### ISSUE TITLE
How to upsample a feature map?

### ISSUE THREAD

**Issue by PhanTask** [apache/incubator-mxnet#4666]
I want to unsample a feature map by a factor of 4 (e.g 9x9 -> 36x36 , nearest method). I find the mxnet.symbol.upsamping but I don't know exactly how to use it. Could somebody give me an example?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
