### ISSUE TITLE
problem when running warp-ctc example on latest mxnet version

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#4668]
## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc 4.8

Package used (Python/R/Scala/Julia): Python

MXNet version: latest 0.9.1

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: Anaconda 2.7.11

## Error Message:
Please paste the full error message, including stack trace.
```
~/mxnet/example/warpctc$ python toy_ctc.py
WARNING:root:[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
begin fit
```
when I crtl + c to stop the job here is the log :
```
File "toy_ctc.py", line 162, in <module>
    batch_end_callback=mx.callback.Speedometer(BATCH_SIZE, 50),)
  File "../../python/mxnet/model.py", line 814, in fit
    sym_gen=self.sym_gen)
  File "../../python/mxnet/model.py", line 259, in _train_multi_device
    executor_manager.update_metric(eval_metric, data_batch.label)
  File "../../python/mxnet/executor_manager.py", line 425, in update_metric
    self.curr_execgrp.update_metric(metric, labels)
  File "../../python/mxnet/executor_manager.py", line 277, in update_metric
    metric.update(labels_slice, texec.outputs)
  File "../../python/mxnet/metric.py", line 348, in update
    pred = pred.asnumpy()
  File "../../python/mxnet/ndarray.py", line 500, in asnumpy
    ctypes.c_size_t(data.size)))
```
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
run example/warp-ctc/toy-ctc.py

## What have you tried to solve it?

1. toy-ctc.py work fine on mxnet 0.7

**Comment by piiswrong** [comment]
please pull lastest master

**Comment by xinghedyc** [comment]
Thanks a lot, it works.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
