### ISSUE TITLE
Performace regression issue on current mxnet with latest nnvm

### ISSUE THREAD

**Issue by mz24cn** [apache/incubator-mxnet#4673]
Compared with the version before NNVM refactored, a epoch requires 216s, while the previous value is 155s, performance downgrade up to 40%.
GPU-Z shows PCI bus load and GPU load is lower, while CPU occupy is higher. Previously one CPU core is fullly running, now more than one cores are actively running.
I copied dmlc/nnvm to overwirte dmlc/mxnet/nnvm otherwise the program cannot run (https://github.com/dmlc/MXNet.cpp/pull/61).

Anyone encounters similar performance issue?

**Comment by piiswrong** [comment]
what network are you using?
@tqchen

**Comment by mz24cn** [comment]
C++ version charRNN via MXNet.cpp API: https://github.com/dmlc/MXNet.cpp/tree/master/windows/vs/charRNN

**Comment by mz24cn** [comment]
Current version (2017/1/21) worsens from 216s to 238s, 10%.

**Comment by mz24cn** [comment]
link to #4795 for later observation

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
