### ISSUE TITLE
Bug in src/resource.cc [function: GetHostSpace]

### ISSUE THREAD

**Issue by devymex** [apache/incubator-mxnet#4684]
https://github.com/dmlc/mxnet/blob/master/src/resource.cc#L56
This line should be:
```cpp
if (host_handle.size != 0) {
```

**Comment by starimpact** [comment]
@piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
