### ISSUE TITLE
Compiler error C2664 in mxnet-cpp io.h struct MXDataIterBlob constructor.

### ISSUE THREAD

**Issue by Sooriyajeevan** [apache/incubator-mxnet#4689]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Microsoft Windows 10

Compiler: Visual Studio 2015 C++15 x64

## Error Message:
1>C:\MxNet\MXNet.cpp\include\mxnet-cpp/io.hpp(21): error C2664: 'std::shared_ptr<mxnet::cpp::MXDataIterBlob> std::make_shared<mxnet::cpp::MXDataIterBlob,nullptr>(nullptr &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&'

## Minimum reproducible example
I was building mlp example as a DLL with Microsoft CLR support.

## What have you tried to solve it?
I resolved the bug by providing static_cast to nullptr as shown below in io.hpp line 21:
MXDataIter::MXDataIter(const std::string &mxdataiter_type) {
creator_ = mxdataiter_map_->GetMXDataIterCreator(mxdataiter_type);
// blob_ptr_ = std::make_shared<MXDataIterBlob>(nullptr); // this original code gives compiler error C2664.
blob_ptr_ = std::make_shared<MXDataIterBlob>(static_cast<DataIterHandle>(nullptr));

**Comment by piiswrong** [comment]
@yajiedesign @howard0su

**Comment by howard0su** [comment]
I can compile it with VC2015 Update 3. can u try to upgrade your VS to latest Update?

**Comment by Sooriyajeevan** [comment]
can compile it with VC2015 as a stand alone C++ project. But I created a Common Language Runtime (CLR) DLL with /clr complier flag. That found a bug in implicit type casting of nullptr in statement 
blob_ptr_ = std::make_shared<MXDataIterBlob>(nullptr). It needed a static cast, and with that the bug was resolved. 
blob_ptr_ = std::make_shared<MXDataIterBlob>(static_cast<DataIterHandle>(nullptr))

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
