### ISSUE TITLE
CSV Iterator errors - number of input must be bigger than batch size

### ISSUE THREAD

**Issue by vlad-cognitiv** [apache/incubator-mxnet#4700]
High level issue description: There appeared to be a bug in the most recent version of MxNet, which affects CSV Iterator and makes it virtually unusable. In fact, this issue is very critical because NDArrayIter cannot be used for very large data sets that are not fitting in memory entirely. It invalidates one of the most attractive features of MxNet, so unless this issue is resolved we cannot use MxNet for many of our clients. Please review.

## Environment info

Operating System: Both - Ubuntu 14.04.3 & MS Windows 8.1

Compiler: GCC  (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 on Ubuntu & VS 2015 Update 2 on Windows

Package used:  Python

MXNet version: Installed from source (the moist recent version taken from  https://github.com/dmlc/mxnet on January 10 , 2017

MXNet commit hash (`git rev-parse HEAD`): 837fe9b972c8e92cd5d8a8bafd9f788fd3693dbf

If you are using python package, please provide: No 

Python version and distribution: Anaconda3, Python 3.5.1

If you are using R package, please provide: No

## Error Message:
\src\io\iter_batchloader.h:100: Check failed: base_->Next() number of input must be bigger than batch size
	libmxnet.dll!mxnet::io::BatchLoader::Next() Line 100	C++ >	
        libmxnet.dll!mxnet::io::PrefetcherIter::Init::__l2::<lambda>(mxnet::DataBatch * * dptr) Line 78
        libmxnet.dll!dmlc::ThreadedIter<mxnet::DataBatch>::Init::__l2::<lambda>() Line 338	C++	C++

## Minimum reproducible example

I’m using the minimalistic code from original kaggle-ndsb2 example provided with MxNet. This is the only example in the latest package, which is using CSVIter. I simplified this code and provided a small CSV data sets to reproduce the error (please see attachments) – both Train_min.py.txt (please remove txt extension before running *.py code), test_data.txt, and test_label.txt are attached.

## Steps to reproduce
1.	Just run Train_min.py as is without any parameters to reproduce the error.

The most critical line here is line # 45, which sets the batch size:
	batch_size = 181 
 
Please keep in mind that the data set contains 681 lines in CSV files. I assume that the batch size up to 681 (inclusive) should be supported. This is the behavior we have seen in the previous version of MxNet built from source on September 14, 2016.

Behavior is slightly different on Windows and Linux. On Linux the highest batch size I can specify is 180. Everything higher than 181 (inclusive) failed with the above error.

On Windows the highest batch size I can specify is 91. Everything higher than 92 (inclusive) failed with the above error.

Using smaller batch size (180 on Linux and 91 on Windows) helps us to have the run completed without the errors. However, in this case most of the data is ignored and only first 180/91 records are used in training. 

## What have you tried to solve it?

1. I was able to debug the source code in C++ and can see that MxNet calculates the number of labels as 86 (instead of 681, which it really is). It looks like the system assumes that 681 is not the number of records in the file but the number of bytes (681 / 8 = 85.125) or something like that.

2. I tried to switch from ThreadedEngine to NaiveEngine but it did not help.

3. I’ve also tried turning round_batch option of CSVIter on and off but it did not help either.

4. I stopped my research at this point because it looks like the affected code goes beyond MxNet itself into DMLC’s ThreadedIter and fixing the bug might affect other MxNet functionality, which should be thoroughly tested and verified.

[Train_min.py.txt](https://github.com/dmlc/mxnet/files/712003/Train_min.py.txt)
[test_data.txt](https://github.com/dmlc/mxnet/files/712004/test_data.txt)
[test_label.txt](https://github.com/dmlc/mxnet/files/712005/test_label.txt)

Regards,
Vladimir Drozdetski

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
