### ISSUE TITLE
compile error fatal error c1001:

### ISSUE THREAD

**Issue by newzhx** [apache/incubator-mxnet#4705]
when compile the source file, I meet an error:
3>E:\zhx2\mxnet-master\mxnet-master\nnvm\src\pass\order_mutation.cc(114): fatal error C1001: 编译器中发生内部错误。
3>  (编译器文件“f:\dd\vctools\compiler\cxxfe\sl\p1\c\trees.h”，第 884 行)
3>   要解决此问题，请尝试简化或更改上面所列位置附近的程序。
3>  请选择 Visual C++
3>  “帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。

My environment is:
windows 7 64bit
vs2013(i have installed the visual c++ compiler nov 2013 ctp, and replace the original vs2013 files)
cuda7.5
cudnn v3 v4 v5(i tried all the version)
opencv3.0
openblas

how can i solve this problem?

**Comment by piiswrong** [comment]
try upgrading to vs2015

**Comment by due2me** [comment]
change codes in order_mutation.cc(114) to:
`NodeEntry value = NodeEntry{ nullptr, 1, e.version };
auto it = std::lower_bound(vec.begin(), vec.end(), value, comparator);`

**Comment by louiskoo520** [comment]
I have encountered the same question in VS2015.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
