### ISSUE TITLE
About std::thread In ThreadPool is Very slow to Start the Thread Entry Function

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#4707]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Linux version 3.10.0-327.el7.x86_64
Compiler:
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) 
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.7
Or if installed from source:
Yes, I Install from Source
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python-2.7.5
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. mxnet-face-master
2.
3.

## What have you tried to solve it?

1.Debug
2.
3.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
