### ISSUE TITLE
small amount memory cost in GPU device 0 even if context is set to mx.gpu(1)

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#4708]
I just noticed that running mx.mod.Module.fit can produce a small amount GPU memory cost in device 0 even if I set context to mx.gpus(1) when creating the mx.mod.Module variable(`mod = mx.mod.Module(context=mx.gpu(1), symbol=net)`).

The problem seems to be caused at line 410 in python/mxnet/module/module.py when it tries to copy initialized local parameters to kvstore(). I loaded my pre-trained weights using `mx.nd.load` which means these parameters are stored in cpu originally. Thus, when copying them to kv-store, they are copied to mx.gpu(0) by default.

I am not sure if it is a bug or so. But maybe we should check and transfer arg_params/aux_params to the target device in mx.mod.Module.init_params?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
