### ISSUE TITLE
Why cudaStreamCreate will consume a long time in mxnet, while with a short time in a simple c++ demo?

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#4712]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by idealboy** [comment]
why I need a long time when call cudaStreamCreate in mxnet library, while I need a short time with a simple call in my demo?

Is it relative with compilation or local context(cuda version or run time?)

Thank you very much

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by masahi** [comment]
@idealboy Have you solved this issue? We are seeing the same problem.

cudaStreamCreate takes about 1 second, when linked with libmxnet.dll.
