### ISSUE TITLE
Sometimes, in some environment, load params is very slow, it seem as blocking in somewhere

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#4717]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by idealboy** [comment]
it is mainly at cudaStreamCreate and cudaMalloc, it will block there and consume a very long time, about several minutes, why? thank you

**Comment by piiswrong** [comment]
the first cuda call is compiling cuda kernels.
Updating to cuda8.0 should improve this.

you can also add 6.1 to config.mk un cuda_arch if you are using pascal gpus

**Comment by idealboy** [comment]
Thank you very much. When I call cudaStreamCreate in c_api.cc, in the function mxNDArrayLoad, it will take about two minutes, but when I call cudaStreamCreate in the Constructor function in a global class object in c_api.cc, it wiil pass quickly, so I'm disturbed, thank you

**Comment by idealboy** [comment]
I call MXNDArrayLoad function by python interface， is it relative with this reason?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
