### ISSUE TITLE
Core installation success, but Python interface fail (Win7+VS2015+CUDA 8 + Cudnn 5.1)

### ISSUE THREAD

**Issue by NoNamesLeft4Me** [apache/incubator-mxnet#4722]
I am trying to install with win7 + vs 2015. The core libraries build (libmxnet.lib + libmxnet.dll) is successful, but when I tried to install Python interface, it failed:
![python01](https://cloud.githubusercontent.com/assets/24922424/22077657/f2e9cf10-dd69-11e6-9d84-5f5e88b13aba.png)

My sys info:
win 7, VS 2015, cuda 8, cudnn 5.1, Cmake 3.7.2, Python 2.7 (Anaconda 4.2), OpenCV 3.2

Discussion:
I tried to solve it by installing Visual C++ 9.0 and re-running setup.py script, but it certainly doesn't work neither. 

I am wondering if building VS2015 is possible, since on the website it specifically says uisng VS 2013. The reason is that VS2015 wasn't compatible with CUDA back then. Since now VS 2015 is working with CUDA 8, I am trying to build it with VS 2015.

Another possible reason is about OpenBlas. I read that to use OpenBlas, using mingw64_dll is a must (details are in the link).
http://www.voidcn.com/blog/u010414386/article/p-6319697.html
However, I didn't use it and the building of the library seems fine. SoI don't know if this causes the failure of the Python interface.

Also I use the latest OpenCV 3.2 (available 2016/12), so I am curious if that is an issue?

Anyway, would someone know how to solve this issue? Thanks!

**Comment by piiswrong** [comment]
cython support is not necessary.
@tqchen can we make install not use cython by default?

**Comment by piiswrong** [comment]
@NoNamesLeft4Me For the moment I think you can remove cython with `pip uninstall cython` and install will work

**Comment by NoNamesLeft4Me** [comment]
@piiswrong Thanks. The updated setup.py works!
 
And to run mxnet, I also have to add the Opencv sub dir ${Opencv_dir}\build\x64\vc14\bin in PATH environment, otherwise it cannot find some opencv DLLs. 

Also, there is a problem that after I ran mxnet in python using cmd, it cannot exit from Python. Might not be a big problem, but it seems abnormal.

**Comment by tqchen** [comment]
Current logic means if cython is not installed, then it will switched to default build. Maybe we did not catch all exceptions

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
