### ISSUE TITLE
Tree LSTM implementation

### ISSUE THREAD

**Issue by speedcell4** [apache/incubator-mxnet#4725]
Is that possible and easy to implement [Tree-LSTM](https://arxiv.org/abs/1503.00075) in MXNet?

I have noticed that [DyNet](https://github.com/clab/dynet/blob/master/dynet/treelstm.cc) can do this dynamically . Is that also easy for MXNet with imperative programming?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
