### ISSUE TITLE
I found it so slow on train compared with paddle or tensorflow

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#4726]

**Comment by janelu9** [comment]
otherwise, the cpu usage is so high

**Comment by feiyulv** [comment]
which model do you train? cnn, lstm, nmt?

**Comment by janelu9** [comment]
@feiyulv  lstm

**Comment by feiyulv** [comment]
the bucket lstm training will be a little slower at first, speed will be faster when all buckets are built

**Comment by janelu9** [comment]
it stopped without any errors threw when validating at the first epoch
