### ISSUE TITLE
successful install and import mxnet in cmd, but Pycharm cannot find  "FullyConnect " and other nn functions. And the code works both with Pycharm and cmd

### ISSUE THREAD

**Issue by jiachengzju** [apache/incubator-mxnet#4727]
## Environment info
Operating System:
windows
Compiler:
PyCharm
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.9.2
Python version and distribution:
2.7.12

I try to run demo in both terminal and pycharm
```
import mxnet as mx
net = mx.sym.Variable("data")
net1 = mx.sym.FullyConnected(data=net,name='cf1',num_hidden=128)
```
following happens 
1. these code work fine in cmd
2. these code work fine in Pycharm
3. but Pycharm cannot find declaration for "FullyConnected" or "ActivationFunction"

I try to reinstall pycharm and invalidate cash with in pycharm, but it didn't work.
It seem that pycharm cannot find classes and function not write in .py files

**Comment by jdchoi77** [comment]
I have the same issue; any explanation?  I'm wondering if this has to do with C-binding in mxnet.

**Comment by KeithYin** [comment]
I have the same issue too, is there some method to solve it?

**Comment by jiachengzju** [comment]
gave mxnet up，turn to tf




________________________________
苗加成
M：+86-13656719129
E：miaojiacheng@huawei.com<mailto:miaojiacheng@huawei.com>
产品与解决方案-OSS与存量技术开发部

发件人： KeithYin
收件人： dmlc/mxnet<mxnet@noreply.github.com<mailto:mxnet@noreply.github.com>>
抄送： miaojiacheng<miaojiacheng@huawei.com<mailto:miaojiacheng@huawei.com>>;Author<author@noreply.github.com<mailto:author@noreply.github.com>>
主题： Re: [dmlc/mxnet] successful install and import mxnet in cmd, but Pycharm cannot find "FullyConnect " and other nn functions. And the code works both with Pycharm and cmd (#4727)
时间： 2017-06-30 22:12:46


I have the same issue too, is there some method to solve it?

―

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by y12uc231** [comment]
Please look into the version available to install on pycharm . got the following error while installing mxnet in pycharm .
"
Could not find a version that satisfies the requirement mxnet (from versions: )
No matching distribution found for mxnet
"
