### ISSUE TITLE
could not use gpu

### ISSUE THREAD

**Issue by newzhx** [apache/incubator-mxnet#4733]
I have compiled the source file and installed the python interface.
But when i tried to use gpu, it failed：
![847231828126022107](https://cloud.githubusercontent.com/assets/17644192/22111835/cb837a38-de9b-11e6-933e-d87f198b3d0d.jpg)
My environment is:
windows 7 64bit
vs2015 with update3
cmake 3.7.1
cuda7.5
cudnn v3
opencv 3.0
openblas
python3.4(winpython)

when I install the python interface, I encounter an error: c:\program files(x86)\microsoft visual studio 10.0\vc\bin\x86_amd64\cl.exe fatal error with statue 2
I modified the regedit, change the  root of microsoft visual studio 10.0 to microsoft visual studio 12.0 and successfully installed the python interface. Are there something wrong?

**Comment by howard0su** [comment]
maybe your GPU is too old to be supported by CUDNN.

please try to disable CUDNN in config.mk and try build again.

**Comment by newzhx** [comment]
Thank you, that is right the problem.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
