### ISSUE TITLE
slow IO

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#4734]
Hi All,

I was running imagenet with --test-io 1 and found that I get only 22 samples/sec which is very slow.
On profiling with -cProfile, it shows that the majority of time is spent in 
21   70.439    3.354   70.441    3.354 io.py:565(next)

Not sure what occurs behind the covers..am I missing anything basic? The raw IO performance seems fine.

    def next(self):
        if self._debug_skip_load and not self._debug_at_begin:
            return  DataBatch(data=[self.getdata()], label=[self.getlabel()], pad=self.getpad(),
                              index=self.getindex())
        if self.first_batch is not None:
            batch = self.first_batch
            self.first_batch = None
            return batch
        self._debug_at_begin = False
        next_res = ctypes.c_int(0)
        check_call(_LIB.MXDataIterNext(self.handle, ctypes.byref(next_res)))
        if next_res.value:
            return DataBatch(data=[self.getdata()], label=[self.getlabel()], pad=self.getpad(),
                             index=self.getindex())
        else:
            raise StopIteration

**Comment by janelu9** [comment]
give it a larger batch_size

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
