### ISSUE TITLE
Using NDArrayIter causes Huge Memory Usage

### ISSUE THREAD

**Issue by JonBoyleCoding** [apache/incubator-mxnet#4738]
I've got a network that I'm trying to train, but I'm running into weird memory issues. When using the following code...
```
t = softmax.simple_bind(ctx=mxnet.cpu(),
                            data=(10, 3, 227, 227))

print(t.debug_str())
```

It suggests I'll need about 250MB of memory for this. When training the network using NDArrayIter, it uses over 40GB of ram (64GB machine)!

Ideally I'm wanting to use my GPU, but I'm sure it's pretty obvious that my GPU does not have that sort of RAM.

My iterators are defined as follows, where exemplars_train is (7878, 3, 227, 227), and exemplars_test is (2623, 3, 227, 227):

```
train_iter = mxnet.io.NDArrayIter(exemplars_train, labels_train, 10)
test_iter = mxnet.io.NDArrayIter(exemplars_test, labels_test, 10)
```

And the fitting of the model for training is as follows:

```
model = mxnet.model.FeedForward(
	ctx = mxnet.cpu(0),
	symbol=softmax,
	num_epoch=epochs,
	learning_rate = 0.9)

eval_metrics = ['accuracy']

model.fit(
	X=train_iter,
	eval_data=test_iter,
	eval_metric = eval_metrics,
	epoch_end_callback = mxnet.callback.do_checkpoint("chks2/train", 10),
	batch_end_callback = mxnet.callback.Speedometer(100,10))
```

Is it normal to have this amount of memory usage? It seems extraordinarily high to me. As I mentioned above, I want to get this training on my GPU, but with things currently, this doesn't seem like it will be a possibility. Even if I set the batch size to 1, it is still too much for my GPU.

So my questions regarding this are as follows:

- Is this amount of memory usage normal?
- Am I using NDArrayIter wrong?
- Is there another type of iterator I can use with less memory footprint if this is normal?

Thanks in advance.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
