### ISSUE TITLE
batch_size, cpu_num , memory,train_time,

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#4739]
I found that the larger the batch_size is the less the memory will be, why?
otherwise the train time become less obviously

**Comment by janelu9** [comment]
when i set more cpu_num it will be stop unpredictable dure trainning

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
