### ISSUE TITLE
unable to run train_end2end.py

### ISSUE THREAD

**Issue by yasserabbass** [apache/incubator-mxnet#4749]
I had created the data/ and model/ directories in examples/rcnn downloaded the datasets and pre-trained models when I run train_end2end it give me the following error
line 99, in load_pascal_annotation
    size = cv2.imread(roi_rec['image']).shape
AttributeError: 'NoneType' object has no attribute 'shape'

opencv cannot read the file have no clue why, I started debugging the script and although the path is there opencv does not read the file.

one more question why should I open each image to get it's width and height, these data is recorded in the annotation file

**Comment by yasserabbass** [comment]
resolved when I installed opencv v3 

but now I have another problem cudaMalloc failed: out of memory
how can I overcome this

thanks

**Comment by yasserabbass** [comment]
I had resolved the issue I had opencv v2 when I installed opencv 3 it worked

**Comment by precedenceguo** [comment]
Image size is very useful right? To prevent opening image multiple times, we store sizes of all images when generating imdb.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
