### ISSUE TITLE
Weird Mxnet Model Zoo Domain Problem 

### ISSUE THREAD

**Issue by VoVAllen** [apache/incubator-mxnet#4750]
![1](https://cloud.githubusercontent.com/assets/8686776/22169934/47971738-df46-11e6-8a1a-c53e0e5a0a2b.png)
![2](https://cloud.githubusercontent.com/assets/8686776/22169936/4cfea916-df46-11e6-9d27-40b6dd0b7df3.png)
![3](https://cloud.githubusercontent.com/assets/8686776/22170161/b288efba-df48-11e6-9828-f452144aad07.png)

I tried to download the VGG16 model from model zoo. However the link doesn't work **sometimes**. Sometimes there is VGG folder but sometimes not.

It seems there're two version of data.dmlc.ml and the DNS server will randomly resolved into one. However they have different content. I'm not sure what's the real reason of this.

**Comment by piiswrong** [comment]
@mli

**Comment by msollami** [comment]
@VoVAllen Yes that's what I was seeing. I guess they are back (for now).

**Comment by VoVAllen** [comment]
Try to bind 54.208.175.7 with data.dmlc.ml in hosts

I'm not sure whether this could work or not

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
