### ISSUE TITLE
opencv error of SSD

### ISSUE THREAD

**Issue by guo253** [apache/incubator-mxnet#4756]
@zhreshold 
## Environment info
Operating System:
ubuntu14.04
Compiler:
gcc 4.8.4
g++ 4.8.4
Package used (Python/R/Scala/Julia):
Python
IDE:Spyder
MXNet version:
0.9.2
Python version and distribution:
2.7

Opencv version:
3.0

## Error Message:
In Spyder:
>>> runfile('/home/guorui/soft/code/mxnet/mxnet/example/ssd/demo.py', args=r'--cpu', wdir=r'/home/guorui/soft/code/mxnet/mxnet/example/ssd')
UMD has deleted: common, tools, tools.find_mxnet, detect, dataset.testdb, dataset.imdb, symbol_vgg16_reduced, tools.rand_sampler, dataset.iterator, detect.detector, dataset
[23:01:59] src/nnvm/legacy_json_util.cc:153: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
Detection time for 1 images: 4.4787 sec
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/guorui/soft/opencv/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp, line 1837
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/guorui/soft/code/mxnet/mxnet/example/ssd/demo.py", line 100, in <module>
    CLASSES, args.thresh, args.show_timer)
  File "detect/detector.py", line 170, in detect_and_visualize
    img = cv2.imread(im_list[k])
cv2.error: /home/guorui/soft/opencv/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp:1837: error: (-213) Unknown/unsupported array type in function type

or

>>> runfile('/home/guorui/soft/code/mxnet/mxnet/example/ssd/demo.py', args=r'--cpu', wdir=r'/home/guorui/soft/code/mxnet/mxnet/example/ssd')
[23:10:05] src/nnvm/legacy_json_util.cc:153: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
Detection time for 1 images: 5.2720 sec
OpenCV Error: Assertion failed (d == 2 && (sizes[0] == 1 || sizes[1] == 1 || sizes[0]*sizes[1] == 0)) in create, file /home/guorui/soft/opencv/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp, line 2294
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/guorui/soft/code/mxnet/mxnet/example/ssd/demo.py", line 100, in <module>
    CLASSES, args.thresh, args.show_timer)
  File "detect/detector.py", line 170, in detect_and_visualize
    img = cv2.imread(im_list[k])
cv2.error: /home/guorui/soft/opencv/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp:2294: error: (-215) d == 2 && (sizes[0] == 1 || sizes[1] == 1 || sizes[0]*sizes[1] == 0) in function create

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.demo.py  --cpu

## What have you tried to solve it?
import cv2 is ok,and the installation of opencv is correct.
sometimes,when close and restart spyder,it can work,and if it works once,it can work forever without closing the spyder.

Thank you.

**Comment by zhreshold** [comment]
What do you mean by sometimes it can work? It looks like a cv2.imread error.
Did you download the images in data/demo?

**Comment by guo253** [comment]
@zhreshold 
Yes,I have download the images.

I found a phenomenon as below.

I creat a new file named test.py
###
import cv2
img_path = './data/demo/dog.jpg'
img = cv2.imread(img_path,0)
###
(1)
I run test.py,it is ok.and then I run demo.py,it is ok too.
(2)
when I closed spyder and open it.
I run demo.py,it show the error msg as above.and then I run test.py,it show the error too.
(3)
I insert the content of test.py to the beginning of demo.py in main,and run demo.py,it show the error.

I'm very confused with this.
Do you have any suggestion?
Thank you.

**Comment by zhreshold** [comment]
Very likely your python packages are messed up in sys path, and I don't know exactly where the problem is.
Could you use a virtualenv?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
