### ISSUE TITLE
rcnn custom dataset tutorial

### ISSUE THREAD

**Issue by yasserabbass** [apache/incubator-mxnet#4757]
Is there any tutorial on how to train rcnn on custom dataset 

thanks

**Comment by precedenceguo** [comment]
There is not. The coco dataset has the following changes: a new imdb class as is in rcnn.dataset.coco; new config as in rcnn.config.coco. You can follow coco dataset to train on new datasets.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
