### ISSUE TITLE
How to use native Infiniband instead of IPoIB

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#4766]
Hi All,

I could use distributed training with IPoIB. But since using IPoIB is still slower than using native Infiniband, is there any way to use native Infiniband? Thanks.

Regards,
Rengan

**Comment by howard0su** [comment]
mxnet didn't support it. be more accurate, ps-lite doesn't support native IB.

If you want to contribute, please take a look project dmlc/ps-lite. a good start point will be class Van (reference include/ps/internal/van.h) You can leverage RDMA to do message send/receive.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by byronyi** [comment]
Hi all, please see https://github.com/dmlc/ps-lite/pull/124 for our PR. Many thanks to my colleagues @crazyboycjr and @snowzjx for their design and implementation.
