### ISSUE TITLE
DistilledSGLD regression algorithm shows the MSE is nan

### ISSUE THREAD

**Issue by changlinwan** [apache/incubator-mxnet#4768]
I use my own data insteed of the sample toy data, and the MSE is nan.
I debug in the python source code, and find that the student network output is nan.

## Environment info
Operating System:
WIN7
Compiler:
Prebuild 20160531
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.93
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python 2.7

**Comment by changlinwan** [comment]
when use one layer architecture the output is fine.
when use multiple layers architecture the output is nan.

data is ok, it works fine for one layer network

**Comment by changlinwan** [comment]
net = mx.symbol.Variable('data')
        net = mx.symbol.FullyConnected(data=net, name='teacher_fc1', num_hidden=400)
        net = mx.symbol.Activation(data=net, name='teacher_relu1', act_type="relu")
        net = mx.symbol.FullyConnected(data=net, name='teacher_fc2', num_hidden=400)
        net = mx.symbol.Activation(data=net, name='teacher_relu2', act_type="relu")
        net = mx.symbol.FullyConnected(data=net, name='teacher_fc3', num_hidden=1)
        net = mx.symbol.LinearRegressionOutput(data=net, name='teacher_output',
                                               grad_scale=teacher_noise_precision)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
