### ISSUE TITLE
im2rec resize=100 original image have various width and height, how to get ImageRecordIter datashape?

### ISSUE THREAD

**Issue by jinfagang** [apache/incubator-mxnet#4772]
I using `~/Mxnet/bin/im2rec ` set `resize` to 100, my original image width and height are different for each single image, so how do I set `datashape` in ImageRecordIter?
Here is what I do:
```
train_iter = mx.io.ImageRecordIter(
    path_imgrec="tiny5_train.rec",
    data_shape=(3, 150, 100),
    batch_size=batch_size,
    rand_crop=True,
    rand_mirror=True
)
```
but when I run I got this error:
```
 input image size smaller than input shape
terminate called after throwing an instance of 'dmlc::Error'
  what():  [13:13:40] src/io/image_aug_default.cc:254: Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape
```
Anybody know why?

**Comment by Godricly** [comment]
May I ask how do you handle image of (50,100). I think im2rec will resize this case to (100,200). There is a resize parameter for ImageRecordIter class too. But the data.py file in tutorial did not included it.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
