### ISSUE TITLE
About creat new operator:Is it true that I don't need write .cu at all time using c++?

### ISSUE THREAD

**Issue by guo253** [apache/incubator-mxnet#4773]
Hi,
I think I just need write x-inl.h and x.cc when creating a new operator using mshadow in mxnet using c++.
It can be tanslated to .cu when I set the CUDA=1 and make automatically.
When is it translated? after make?

So,Are xx.cu(s) in src/operator created as above?
Or,when should I write xx.cu manually?

Some code in xx.cu(s) is look like writing manually? 

Thank you.

**Comment by Godricly** [comment]
you dont have to write forward and backward if you can implement the operator using mshadow.
The ```CreateOp``` is needed for creating GPU operator.
You can refer to these 2 links:
[new_op](http://mxnet.io/how_to/new_op.html#c)
[mshadow tutorial](https://github.com/dmlc/mshadow/tree/master/guide)

**Comment by guo253** [comment]
Thank you very much.
I have already read these two links,but it is a little hard to a new mxnet'er.
It is better giving a completely toy example for new operator using c++,not just description in words,although there is examples in src/operator,but I don't know which part should be written,which can be generated automatically.
And how to use auto-diff in backward using c++?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
