### ISSUE TITLE
ImageNet expected speed on Pascal GPUs with resnet-50?

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#4779]
Hi All,

Wondering if any body knows the expected rate with resnet-50 for imagenet on Pascal GPUs. I am debugging a problem (most likely an I/O issue) but knowing in what range will it be can help me,
(bs=128). Even a single node or single GPU rate would also help,

thanks

**Comment by mli** [comment]
http://mxnet.io/how_to/perf.html#nvidia-gpu

**Comment by amithr1** [comment]
Thanks..I think I am getting very close to the 32 batch for P100 number now. I am planning to launch a large scale run. May be I will open another issue for that.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
