### ISSUE TITLE
How to run MXNet with less than 1 epoch

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#4780]
Hi All,

Is there any way to run MXNet with fewer than 1 epoch? Because Nvidia profiler nvprof crashed even with 1 epoch. And the possible reason is that it generated too much profiling data. So can I run MXNet with only a specific number of iterations which is less than 1 epoch?

Regards,
Rengan

**Comment by piiswrong** [comment]
mx.io.Resize

**Comment by hfutxrg** [comment]
Could you be more specific which file I should change? I am still not familiar with MXNet code structure. Thanks.

**Comment by mz24cn** [comment]
use step by step debug.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
