### ISSUE TITLE
Are there any other distributed training examples?

### ISSUE THREAD

**Issue by guotong1988** [apache/incubator-mxnet#4789]
I only find one MNIST lenet example from here:
https://aws.amazon.com/cn/blogs/compute/distributed-deep-learning-made-easy/
I prefer to run it in the AWS.

**Comment by mli** [comment]
http://mxnet.io/how_to/multi_devices.html

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
