### ISSUE TITLE
Proposed improvements for the mxnet Scala package

### ISSUE THREAD

**Issue by ctongfei** [apache/incubator-mxnet#4800]
I propose the following improvements for the mxnet Scala package, mostly making it more idiomatic and user-friendly for Scala users (could be in the form of a higher-level API while retaining the current API as the lower-level API):

 - Current API is full of `kwargs: Map[String, Any]`, which is not at all idiomatic Scala. Manually rewrite them to normal Scala functions with default parameters. Without the reference of the mxnet Python API I'm really lost at how to use these layers/functions.
 - RNNs: Utilize the Scala `foldLeft`/`scanLeft`/etc operations on `Seq`s to automatically unroll the RNN computation graph. E.g. make an LSTM unit as a function of type `(LSTMState, Symbol) => LSTMState)`, so that you can just say `xs.foldLeft(lstm)` to unroll an LSTM network.
 - Revamping the BucketIO/DataBatch/etc. stuff to be more Scala-idiomatic.
 - Support for GPU on Mac OS X (I've attempted this but failed)
 - Better documentations
 - Better API for executors/gradients maps/etc.
 - [tentative] Typesafe `NDArray`s. Encode the rank/order of the tensor into the type system (What Scala is good at! ), so that an NDArray like `NDArray[Float, _3]` means that it is of rank-3 and each cell contains a `Float` (can be done with the typeclass / phantom type pattern in Scala and with shapeless (https://github.com/milessabin/shapeless)). Concatenation/slicing/etc. will all encode the ranks of the resulting NDArray/Symbol. This enhances compile-time type safety, e.g. `Embedding` layer is a function whose type is `Symbol[Int, N] => Symbol[Float, N+1]`. You cannot pass a symbol with `Float` into an embedding layer.
 - [tentative] Migrate the build system from `maven` to `sbt`.

I can first come up with a prototype of this (also for my own use in NLP research) and we can discuss.

@javelinjs @Ldpe2G @piiswrong @jermainewang

**Comment by javelinjs** [comment]
I agree with most of your suggestions, especially for the RNN and IO things.
To modify the `kwargs` argument, we have to detect the arguments (with their types) of registered C++ functions, which may encounter some difficulties. Currently the c api doc may not be well defined for programs, e.g., the types. We need to check all the operators to make sure `scala macros` can get enough information.

**Comment by ctongfei** [comment]
`kwargs` is difficult to deal with. How about relinquishing macros and do it manually? Or retain those APIs with `kwargs` as low-level API and wrap them up in an idiomatic way as the high-level API (prototypical example: https://github.com/ctongfei/nexus-mxnet/blob/master/src/main/scala/nexus/mxnet/Expr.scala#L51)

**Comment by piiswrong** [comment]
I'm working on a run interface for python. You can use it as a reference.
It's currently sitting in pull request


Tongfei Chen <notifications@github.com>于2017年1月24日 周二下午7:18写道：

**Comment by Ldpe2G** [comment]
@ctongfei Thanks for your suggestions. In my opinion, I think the high-level api you designed is good but a little hard to understand. Because I am not very famililar with the High-level syntax of Scala. Those users come from java side may encounter the same problem when they try to read the source code.
Also this is just my personal opinion.

**Comment by ctongfei** [comment]
@Ldpe2G what about this? (https://github.com/ctongfei/nexus-mxnet/blob/master/src/test/scala/nexus/mxnet/MNIST.scala#L17)

Or we could first publish a simple, clean Java API instead of a Scala one (java has a much larger audience), and then delegate all those fancy stuffs to Scala.

**Comment by Ldpe2G** [comment]
@ctongfei ok I see. Users could construct a net with less code and a more elegant way.

**Comment by javelinjs** [comment]
@ctongfei The arguments for `FullyConnected`, and the name `FullyConnected` itself should be automatically generated (https://github.com/dmlc/mxnet/blob/master/scala-package/macros/src/main/scala/ml/dmlc/mxnet/SymbolMacro.scala#L104). Otherwise it'll be too hard to sync with the cpp core.

**Comment by ctongfei** [comment]
@javelinjs It'd be desirable if it could be automatically generated. Is the c++ core constantly changing?

**Comment by javelinjs** [comment]
I don't think doing it manually is a good idea. That really suffered so we turned to code generation. The operators can be added, deprecated, so as their arguments. And from the view of design, those changes should not be done twice, in core and its front-end binding. 

I think what we need to do is to ensure that scala macros can correctly parse the c++ api doc, especially for the argument types.

BTW, your api design in `nexus-mxnet` is quite cool.

**Comment by ctongfei** [comment]
Got it. I'll read the scala macro code to see if there something I can do.

**Comment by benqua** [comment]
@ctongfei I fully agree that a more idiomatic scala API would be great (an API that take more advantage of the type system).

I would add one point:
- use Option[T] instead of null default value for optional parameters

I am willing to help if an effort in this direction is started.

**Comment by ctongfei** [comment]
@benqua `Option[T]` would be weird because whenever you feed in such an argument, you are going to feed a `Some[T]` there, which is not quite desirable afaik.

**Comment by ctongfei** [comment]
@javelinjs @Ldpe2G I'll be working on my prototype `nexus-mxnet` in my freetime (next step: RNN/executor/etc.)

**Comment by Ldpe2G** [comment]
@ctongfei Great ! look forward to it.

**Comment by benqua** [comment]
I agree it would be better to avoid Option in the public API whenever possible. However, better hsve Option than null.
We should get rid of the null.

**Comment by benqua** [comment]
Is there any progress / activity on this?

**Comment by lanking520** [comment]
I have updated with a CWiki page here: https://cwiki.apache.org/confluence/display/MXNET/Scala+Project+Status
Let's keep all TODOs into one place and also pick up from there. @yzhliu @nswamy let's close this for now.
