### ISSUE TITLE
Running of ImageNet with multiple nodes

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#4811]
I am planning to do some large scale runs up to 64 GPUs. Is there a good recommendation to get a good accuracy for the Imagenet. I saw a pointer recommending 0.5 as initial rate but 0.1 towards 30, 60 epochs..Will this improve accuracy or just training speed? And how do I set this in my run script?

Also, the batch size..Can the batch size go beyond 2048 ? (for eg. 32 Batch size/GPU * 64 == 2048 or 4096 if I use 64 Batch size./GPU).  Are there any pointers on how large can this batch size be? Accordingly, the batch size/GPU can be adjusted.

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/tree/master/example/image-classification#distributed-training

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
