### ISSUE TITLE
OSError: /home/sojoyoo/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN2cv12_OutputArrayC1ERNS_3MatE

### ISSUE THREAD

**Issue by albertyou2** [apache/incubator-mxnet#4815]
## Environment info
Operating System:Ubuntu 16.04
Compiler: gcc/g++5.4
Package used (Python/R/Scala/Julia): python 
Or if installed from source:0.9.3
MXNet commit hash (`git rev-parse HEAD`):64bdd25665019cec2ca38009b1e1a1cdf96d3cb2
If you are using python package, please provide
Python version and distribution:Python 2.7.12 , miniconda2

## Error Message:
Traceback (most recent call last):
  File "train_mnist.py", line 8, in <module>
    from common import find_mxnet, fit
  File "/home/sojoyoo/mxnet/example/image-classification/common/find_mxnet.py", line 4, in <module>
    import mxnet as mx
  File "/home/sojoyoo/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/sojoyoo/mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/sojoyoo/mxnet/python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/sojoyoo/miniconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sojoyoo/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN2cv12_OutputArrayC1ERNS_3MatE

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
1.I installed opencv 2.4.13 as the docmunts mentioned.
2.I installed mxnet by runing  install-mxnet-ubuntu-python.sh
3.The installation was finished successfully.
4.I want to make sure the setup is ok so i tried to run train_mnist.py as below
    1).cd  /home/sojoyoo/mxnet/examples/image-classification/
    2).python train_mnist.py

## What have you tried to solve it?
1.I have no idea of this error

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
