### ISSUE TITLE
Mxnet has no mx.img.ImageIter

### ISSUE THREAD

**Issue by jinfagang** [apache/incubator-mxnet#4822]
On mxnet official documents site : `http://mxnet.io` I searched something about put single image into iter, but
http://mxnet.io/tutorials/python/image_io.html?highlight=imageiter this link gives me this:
> [NEW] mx.img.ImageIter: implemented in python, easily customizable, can load from both .rec files and raw image files.
[OLD] mx.io.ImageRecordIter: implemented in backend (C++), less customizable but can be used in all language bindings, load from .rec files
Custom iterator by inheriting mx.io.DataIter

However, when I run something like this:
```
data_iter = mx.img.ImageIter(
    image='horse.jpg',
    data_shape=(3, 100, 150),
    batch_size=1,
)
```
I got an error:
```
AttributeError: module 'mxnet' has no attribute 'img'
```
I wonder is this method was deprecated or merged into other methods? Anyone could give me a help?

**Comment by howard0su** [comment]
Please try latest version.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
