### ISSUE TITLE
Alexnet and googlenet symbol in example/image-classification is wrong

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#4826]
@piiswrong  Symbol for alexnet and googlenet should be switched. Pls check.  
https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbols/alexnet.py
https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbols/googlenet.py

**Comment by piiswrong** [comment]
Yes could you make a pr?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
