### ISSUE TITLE
Missing model files

### ISSUE THREAD

**Issue by msollami** [apache/incubator-mxnet#4832]
Most of the symbol and params files for the models in the model gallery are missing (http://data.dmlc.ml).

**Comment by VoVAllen** [comment]
https://github.com/dmlc/mxnet/issues/4750

I don't know what's the problem...... So good luck!

**Comment by arlose** [comment]
http://data.dmlc.ml/models/imagenet/vgg/ there is
http://data.dmlc.ml/mxnet/models/imagenet/vgg/ there is not

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
