### ISSUE TITLE
Build failed on EC2 g2 instances

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#4833]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler: default

Package used (Python/R/Scala/Julia): default

MXNet version: latest master branch

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
/usr/local/cuda/bin/nvcc -c -o build/src/operator/tensor/matrix_op_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++   -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_PROFILER=1 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv   -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I/home/ubuntu/mxnet/ps-lite/include -I/home/ubuntu/mxnet/deps/include -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0" src/operator/tensor/matrix_op.cu
src/operator/tensor/././indexing_op-inl.cuh(84): **error: identifier "__shfl_xor" is undefined**

Was working okay. Stopped compiling when updated to the latest master branch

**Comment by piiswrong** [comment]
@ap-hynninen

**Comment by piiswrong** [comment]
try `cp make/config.mk config.mk` then edit the flags again.

**Comment by ap-hynninen** [comment]
Looks like the "-gencode arch..." arguments given in CUDA_ARCH are missing.

**Comment by haimeh** [comment]
I think I may be experiencing a related problem? Part way through compiling, I get several variations of the the error:
...\mxnet\src\operator\tensor\./indexing_op-inl.cuh(84): error : identifier "__shfl_xor" is undefined
and the build fails to generate the libmxnet.dll
However the gencode arch arguments are not missing (as shown below) and trying a few variations did not help, which was the only possibly related solution that I found on stack exchange.
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50

Done Using:
latest master branch
VS 2013
Windows 10
CUDA 8
CuDNN 8
OpenBLAS
OpenCV

**Comment by piiswrong** [comment]
windows build uses cmake, not config.mk. You need to change cmake options

**Comment by cjolivier01** [comment]
Yes, please pull latest for MShadow, which has a revised Cuda.cmake which omits flavors below 30.

**Comment by cjolivier01** [comment]
Around the middle of the mshadow/cmake/Cuda.cmake, there's some code (shown below). You can also explicitly set the architectures to build by defining CUDA_ARCH_ALL for cmake.  On my machine, reducing the number of architectures dramatically shortens nvcc compile times.

if(CUDA_ARCH_ALL)
  set(mshadow_known_gpu_archs "${CUDA_ARCH_ALL}")
else()
  if(${CUDA_VERSION} GREATER 7.5)
    set(mshadow_known_gpu_archs "30 35 50 52 60 61")
  else()
    set(mshadow_known_gpu_archs "30 35 50 52")
  endif()
endif()

**Comment by haimeh** [comment]
Ooooh, I think I understand! Just to clarify, the requirement for using GPU is now different from http://mxnet.io/get_started/setup.html#requirements-for-using-gpus and Compute Capability now must be greater than 3 instead?

**Comment by ap-hynninen** [comment]
@piiswrong  I thought the requirement was >= 3.0 all along. Are we supposed to support 2.0? 2.0 support is possible with some code changes.

**Comment by cjolivier01** [comment]
Just curious, what sort of hardware still requires 2.0?

**Comment by ap-hynninen** [comment]
Fermi boards, see this thread:
https://github.com/dmlc/mxnet/issues/4886#issuecomment-277516062

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
