### ISSUE TITLE
Multiple softmax outputs / targets (or, using multi_output in SoftmaxOutput layer)

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#4837]
Let's say we will predict two types of labels X and Y for a dataset, and set the loss function to be the sum of the individual softmax loss.

I have read all the issues on "multi target prediction" here, yet unfortunately I still can't make it work. Please let me know if I made any silly mistakes. Here's the example code:

```
import mxnet as mx
import logging
import math
import random
import numpy as np

# generate dummy data

n_img = 10
img_size = 1
img = [[[[ random.uniform(0, 1) for x in range(img_size) ] for y in range(img_size)] for c in range(1)] for n in range(n_img)]
label1 = [0 for n in range(n_img)]
label2 = [0 for n in range(n_img)]

for i in range(n_img):
    label1[i] = 3
    label2[i] = 2

batch_size = 1
logging.getLogger().setLevel(logging.DEBUG)

data = mx.sym.Variable('data')
data = mx.sym.Flatten(data=data)

## SINGLE OUTPUT TEST, which works
#train_iter = mx.io.NDArrayIter(data=np.array(img), label=np.array(label1)
#                               , batch_size=batch_size, shuffle=True)
#
#fc1  = mx.sym.FullyConnected(data=data, num_hidden = 10)
#softmax1  = mx.sym.SoftmaxOutput(data=fc1, name='softmax')
#    
#module = mx.mod.Module(symbol=softmax1)
    
# MULTIPLE OUTPUT TEST 1, which does not work
train_iter = mx.io.NDArrayIter(data=np.array(img), label={'softmax1_label':np.array(label1),'softmax2_label':np.array(label2)}
                               , batch_size=batch_size, shuffle=True)

fc1  = mx.sym.FullyConnected(data=data, num_hidden = 10)
fc2  = mx.sym.FullyConnected(data=data, num_hidden = 10)
softmax1  = mx.sym.SoftmaxOutput(data=fc1, name='softmax1')
softmax2  = mx.sym.SoftmaxOutput(data=fc2, name='softmax2')
    
module = mx.mod.Module(symbol=mx.sym.Group([softmax1, softmax2]))

## MULTIPLE OUTPUT TEST 2, which does not work
#train_iter = mx.io.NDArrayIter(data=np.array(img), label=[np.array(label1), np.array(label2)]
#                               , batch_size=batch_size, shuffle=True)
#
#data = mx.sym.Flatten(data=data)
#fc1  = mx.sym.FullyConnected(data=data, num_hidden = 10)
#fc2  = mx.sym.FullyConnected(data=data, num_hidden = 10)
#out = mx.sym.Concat(fc1, fc2)
#softmax  = mx.sym.SoftmaxOutput(data=out, multi_output = True, name='softmax')
#    
#module = mx.mod.Module(symbol=softmax)

module.fit(
    train_iter,
    eval_data = None,    
    optimizer = 'sgd',
    optimizer_params = {'learning_rate': 0.1, 'momentum': 0.0},
    num_epoch = 10,
    batch_end_callback = mx.callback.Speedometer(batch_size, 1)
)
```

**Comment by cheshirecats** [comment]
The error for TEST1 is:
`ValueError: Unknown initialization pattern for softmax2_label. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern`
So basically mxnet thought labels are not provided but to be solved.

The error for TEST2 is:
`mxnet.base.MXNetError: [13:48:44] src/c_api/c_api_symbolic.cc:385: InferShapeKeyword argument name _1_softmax_label not found.`
and it does not work even if I provide the label names as _1_softmax_label and _2_softmax_label as in TEST1.

**Comment by wsstriving** [comment]
Try to define your module as 
```
module=mx.mod.Module(symbol=mx.sym.Group([softmax1, softmax2]), label_names=(['softmax1_label', 'softmax2_label']))
```
You need to explicitly  give the label_names, or mxnet will try to initialize it.

**Comment by cheshirecats** [comment]
@wsstriving  works now. Thanks.

p.s. so the loss is now the sum of the individual loss (such that the gradients are BPed correctly)?

**Comment by wsstriving** [comment]
I think the loss is the sum of the individual loss

**Comment by Strateus** [comment]
Since it is most likely a sum of losses, you wont be able to backpropagate different gradients associated with every single label, to make them distinct and learn at least last FC weights independently, ie network usually learns whatever is easier to learn between the labels, and ignores hard labels. Its not trully a multi-output learning, its more likely learn-whatever-is-easier-between-multiple-outputs, and developers keep silence about **how you can pass different gradients for every label** for few months now, not sure why.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
