### ISSUE TITLE
Define a mx.sym.Variable which is constant in each mini-batch, but still trainable

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#4839]
Consider the following code. The **mx.sym.Variable('extra_bias')** is expected to be **[small small large small]** after training, which is indeed the case.

However, currently the inferred shape has an extra dimension (=mini-batch-size), and hence there will be mini-batch-number-of-copies of it. For example (run the code and you will see this output):
[[-0.37707356 -0.37662297  1.12921023 -0.37551349]
 [-0.37635165 -0.37655994  1.12926149 -0.37634984]
 [-0.37645847 -0.37651965  1.12986588 -0.37688756]
 [-0.37663144 -0.37624913  1.12919986 -0.37631923]
 [-0.3760089  -0.3764413   1.12953496 -0.37708497]]

How can we tell mxnet that this variable should be constant in each mini-batch (so there is no need to train such a large array), while making sure it's still trainable? Thanks.
 
```
import mxnet as mx
import logging
import math
import random
import numpy as np

# generate dummy data

n_img = 100
img_size = 2
img = [[[[ random.uniform(0, 1) for x in range(img_size) ] for y in range(img_size)] for c in range(1)] for n in range(n_img)]
label = [0 for n in range(n_img)]

for i in range(n_img):
    label[i] = 2

batch_size = 5
logging.getLogger().setLevel(logging.DEBUG)

train_iter = mx.io.NDArrayIter(data=np.array(img), label=np.array(label), batch_size=batch_size, shuffle=True)

# simple model

data = mx.sym.Variable('data')
conv = mx.sym.Convolution(data=data, kernel=(1, 1), pad=(0, 0), num_filter = 1)

# optimal value expected to be [small small large small]
extra = mx.sym.Variable('extra_bias') 

flatten = mx.sym.Flatten(data=conv)
flatten = flatten + extra
out  = mx.sym.SoftmaxOutput(data=flatten, name='softmax')

module = mx.mod.Module(symbol=out)

# training

def epoch_callback(epoch, symbol, arg_params, aux_params):
    for k in arg_params:
        print(k)
        print(arg_params[k].asnumpy())

module.fit(
    train_iter,
    eval_data = None,    
    optimizer = 'sgd',
    optimizer_params = {'learning_rate': 0.1, 'momentum': 0.0},
    num_epoch = 5,
    batch_end_callback = mx.callback.Speedometer(batch_size, 1),
    epoch_end_callback = epoch_callback
)
```

**Comment by piiswrong** [comment]
```
extra = mx.sym.Variable('extra_bias', shape=(4,1,1)) 

flatten = mx.sym.Flatten(data=conv)
flatten = mx.sym.broadcast_add(flatten, extra)
```

**Comment by cheshirecats** [comment]
Thanks. It works now (the shape should be (1,4) for it to work).

p.s. Could you take a look at my other question: https://github.com/dmlc/mxnet/issues/4837 ?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
