### ISSUE TITLE
NDArray invocations with scalar arguments.

### ISSUE THREAD

**Issue by jermainewang** [apache/incubator-mxnet#4844]
There are many complaints about passing scalar arguments to MXNet's ndarray calls (https://github.com/dmlc/minpy/issues/139, https://github.com/dmlc/minpy/issues/134). What I am thinking about is to have a wrapper for every registered NDArray function in MXNet such that if the given argument is scalar but supposed to be array, do an automatic conversion. My question is should we do it on python side? or on C++ side?
- If done on python side, each ndarray call will have an extra wrapper (another function redirect), which may introduce overhead.
- I don't know whether this is supported on C++ side, since I guess C++ cannot have arguments of either NDArray or scalar type?

@piiswrong @hotpxl @lryta

**Comment by piiswrong** [comment]
calls like sqrt(2) isn't worth a call to backend. It should be handle in frontend

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
