### ISSUE TITLE
mx.sym.Convolution(weight=xxxxx) no longer works

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#4846]
It seems mx.sym.Convolution(weight=xxxxx) no longer works, probably because the parameter is removed?

The error **(as we can see, weight is no longer in the parameter list):**

mxnet.base.MXNetError: Cannot find argument 'weight', Possible Arguments:

kernel : Shape(tuple), required
    convolution kernel size: (h, w) or (d, h, w)
stride : Shape(tuple), optional, default=()
    convolution stride: (h, w) or (d, h, w)
dilate : Shape(tuple), optional, default=()
    convolution dilate: (h, w) or (d, h, w)
......

**Comment by piiswrong** [comment]
argument to weight must be a symbol

**Comment by cheshirecats** [comment]
Thanks. Now it works.

Can we initialize mx.sym.Variable while defining it? (instead of having to pass its value in arg_params when binding the model)

**Comment by sxjscience** [comment]
@cheshirecats The constant op by tianqi should be a good workaround for that. https://github.com/tqchen/mxnet-gan/blob/master/mxgan/custom_ops.py#L65-L104

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
