### ISSUE TITLE
Python CustomOp limited to default type float32

### ISSUE THREAD

**Issue by mseeger** [apache/incubator-mxnet#4850]
This issue is related to #2300, which fixes it for SimpleOp.

I need to implement an operator via CustomOp, whose arguments (input, output) all have the same type, but this is not np.float32. In fact, I need np.float64 for numerical reasons.

The default implementation of InferType in include/mxnet/operator.h requires all types to be float32.
This is fixed in src/operator/operator_util.cc, where InferType now does the sensible thing, namely requires that all types are the same, or unspecified.

But this does not extend to CustomOp (Python API).

I tried to insert this code into src/operator/custom-inl.h. With this, simple_bind works without exception, but the kernel crashes when any computation is done. So there seems to be a "deeper" reason for the type to be float32.

What I find funny is that casting things from float32 to float64 works totally fine when I build my operator using mxnet.symbol only. It is just once I use CustomOp somewhere that things break. This means that float64 is supported in principle, but not everywhere.

Thanks for some help.

**Comment by Godricly** [comment]
Is there any bias or weight term in your operator using float64? Can you check their type after initialization? I think they are initialized as float32.

**Comment by mseeger** [comment]
Hello, this happens even for the most simple operator (see the example below).

When I look at the code, I think one would simply have to move the InferType implementation in src/operator/operator_util.cc to the default case in include/mxnet/operator.h. The default case checks that all dtypes are float32, and the (more sensible) code in src/operator/operator_util.cc checks whether all dtypes are the same.
I could submit a fix, but I am simply not sure whether this would break other things elsewhere.

Example:
-----
import os
# MXNET_CPU_WORKER_NTHREADS must be greater than 1 for custom op to work on CPU
os.environ["MXNET_CPU_WORKER_NTHREADS"] = "2"
import mxnet as mx
import numpy as np

class IdentOp(mx.operator.CustomOp):
    def forward(self, is_train, req, in_data, out_data, aux):
        self.assign(out_data[0], req[0], in_data[0])

    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        self.assign(in_grad[0], req[0], out_grad[0])

@mx.operator.register("ident_op")
class IdentOpProp(mx.operator.CustomOpProp):
    def __init__(self):
        # this is not a loss, need gradient input from preceding layers
        super(IdentOpProp, self).__init__(need_top_grad=True)
    
    def list_arguments(self):
        return ['x']

    def list_outputs(self):
        return ['y']

    # All shapes must be the same
    def infer_shape(self, in_shape):
        csp = in_shape[0]
        return [csp], [csp], []
    
    def create_operator(self, ctx, shapes, dtypes):
        return IdentOp()

x = mx.sym.Variable('x')
y = mx.symbol.Custom(x=x, name='identity', op_type='ident_op')

executor = y.bind(
    ctx=mx.cpu(),
    args={'x': mx.nd.zeros([2, 3], dtype=np.float64)})
----

At this point, I get:
----
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-2-38de5c96ee62> in <module>()
      5 executor = y.bind(
      6     ctx=mx.cpu(),
----> 7     args={'x': mx.nd.zeros([2, 3], dtype=np.float64)})

/Users/matthis/git/mxnet/python/mxnet/symbol.pyc in bind(self, ctx, args, args_grad, grad_req, aux_states, group2ctx, shared_exec)
    929                                          aux_args_handle,
    930                                          shared_handle,
--> 931                                          ctypes.byref(handle)))
    932         executor = Executor(handle, self, ctx, grad_req, group2ctx)
    933         executor.arg_arrays = args

/Users/matthis/git/mxnet/python/mxnet/base.pyc in check_call(ret)
     73     """
     74     if ret != 0:
---> 75         raise MXNetError(py_str(_LIB.MXGetLastError()))
     76 
     77 if sys.version_info[0] < 3:

MXNetError: Error in operator identity: [09:30:13] include/mxnet/operator.h:267: Check failed: in_type->at(i) == mshadow::default_type_flag || in_type->at(i) == -1 Unsupported data type 1

Stack trace returned 14 entries:
[bt] (0) 0   libmxnet.so                         0x000000010c00aa7c _ZN4dmlc15LogMessageFatalD2Ev + 44
[bt] (1) 1   libmxnet.so                         0x000000010c00a3c9 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010c6d23cf _ZNK5mxnet16OperatorProperty9InferTypeEPNSt3__16vectorIiNS1_9allocatorIiEEEES6_S6_ + 1327
[bt] (3) 3   libmxnet.so                         0x000000010c6afbf1 _ZN5mxnet2op15OpPropInferTypeERKN4nnvm9NodeAttrsEPNSt3__16vectorIiNS5_9allocatorIiEEEESA_ + 881
[bt] (4) 4   libmxnet.so                         0x000000010c914079 _ZZN4nnvm4pass12_GLOBAL__N_19InferAttrIiZNKS1_3$_1clENS_5GraphEEUliE_PFbRKNS_9NodeAttrsEPNSt3__16vectorIiNS9_9allocatorIiEEEESE_EEES4_OS4_T_PKcSK_SK_SK_SK_T0_T1_ENKUljbE_clEjb + 1753
[bt] (5) 5   libmxnet.so                         0x000000010c912f4a _ZNSt3__110__function6__funcIN4nnvm4pass12_GLOBAL__N_13$_1ENS_9allocatorIS5_EEFNS2_5GraphES8_EEclEOS8_ + 3146
[bt] (6) 6   libmxnet.so                         0x000000010c8fce5f _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 991
[bt] (7) 7   libmxnet.so                         0x000000010c5dd6ee _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 206
[bt] (8) 8   libmxnet.so                         0x000000010c5e0724 _ZN4nnvm4pass9InferTypeENS_5GraphENSt3__16vectorIiNS2_9allocatorIiEEEENS2_12basic_stringIcNS2_11char_traitsIcEENS4_IcEEEE + 1108
[bt] (9) 9   libmxnet.so                         0x000000010c60d4a6 _ZN5mxnet4exec13GraphExecutor9InitGraphEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEES4_NS7_4lessISE_EENSC_INS7_4pairIKSE_S4_EEEEEERKNS7_6vectorINS_7NDArrayENSC_ISP_EEEEST_RKNSO_INS_9OpReqTypeENSC_ISU_EEEEST_ + 5622
[bt] (10) 10  libmxnet.so                         0x000000010c60af7f _ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEES4_NS7_4lessISE_EENSC_INS7_4pairIKSE_S4_EEEEEERKNS7_6vectorINS_7NDArrayENSC_ISP_EEEEST_RKNSO_INS_9OpReqTypeENSC_ISU_EEEEST_PNS_8ExecutorE + 111
[bt] (11) 11  libmxnet.so                         0x000000010c6126ed _ZN5mxnet8Executor4BindEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEES3_NS6_4lessISD_EENSB_INS6_4pairIKSD_S3_EEEEEERKNS6_6vectorINS_7NDArrayENSB_ISO_EEEESS_RKNSN_INS_9OpReqTypeENSB_IST_EEEESS_PS0_ + 285
[bt] (12) 12  libmxnet.so                         0x000000010c5c7eda MXExecutorBindEX + 1834
[bt] (13) 13  libffi.dylib                        0x00007fff82d1df44 ffi_call_unix64 + 76
----

**Comment by piiswrong** [comment]
It doesn't have type support yet. It's a simple fix. I'll do it when I can find time

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
