### ISSUE TITLE
error: ISO C++ forbids comparison between pointer and integer

### ISSUE THREAD

**Issue by n1kt0** [apache/incubator-mxnet#4851]
Can't build mxnet after solving many other problems I still have the following error...

## Environment info
Operating System: Ubuntu 16.10

Compiler: gnu compilers 4.8, 4.9, 5, 6

Package used (Python/R/Scala/Julia):

MXNet commit hash (`git rev-parse HEAD`): 0f6d583417b7233ede66642b0319a7c39ff1b672

Python version and distribution: 2.7, 3.5

## Error Message:
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/nikita/mxnet/mshadow/ -I/home/nikita/mxnet/dmlc-core/include -fPIC -I/home/nikita/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -I/opt/intel/mkl/include/mkl/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include -fopenmp -DMXNET_USE_NNPACK=1 -DMXNET_USE_MKL2017=1 -DUSE_MKL=1 -I/home/nikita/mxnet/src/operator/mkl/ -DMKL_EXPERIMENTAL=1 -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I/home/nikita/mxnet/ps-lite/include -I/home/nikita/mxnet/deps/include -I/home/nikita/Git/public/caffe/include -I/home/nikita/Git/public/caffe/build/src -DUSE_CUDNN=1 -I/home/nikita/Git/public/torch/install/include -I/home/nikita/Git/public/torch/install/include/TH -I/home/nikita/Git/public/torch/install/include/THC/ -DMXNET_USE_TORCH=1 -I/home/nikita/Git/public/warp-ctc/include -I/home/nikita/Git/public/SFrame/oss_src/unity/lib/ -I/home/nikita/Git/public/SFrame/oss_src/ -I/home/nikita/mxnet/cub -DMXNET_USE_NVRTC=1 -MMD -c plugin/torch/torch_base.cc -o build/plugin/torch/torch_base.o
plugin/torch/torch_base.cc: In member function ‘void mxnet::TorchState::SetStream(mshadow::Stream<Device>*) [with xpu = mshadow::gpu]’:
plugin/torch/torch_base.cc:46:16: warning: variable ‘cs’ set but not used [-Wunused-but-set-variable]
   cudaStream_t cs = THCState_getCurrentStream(CudaState());
                ^~
In file included from /home/nikita/mxnet/dmlc-core/include/dmlc/io.h:14:0,
                 from include/mxnet/base.h:10,
                 from plugin/torch/./torch_base.h:9,
                 from plugin/torch/torch_base.cc:7:
/home/nikita/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_NE(const X&, const Y&) [with X = THCharStorage*; Y = long int]’:
plugin/torch/./torch_base.h:77:5:   required from here
/home/nikita/mxnet/dmlc-core/include/dmlc/./logging.h:95:24: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
/home/nikita/mxnet/dmlc-core/include/dmlc/./logging.h:76:9:
     if (x op y) return LogCheckError();                           \
         ~~~~~~          
/home/nikita/mxnet/dmlc-core/include/dmlc/./logging.h:95:24:
 DEFINE_CHECK_FUNC(_NE, !=)
                         
/home/nikita/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^~
Makefile:218: recipe for target 'build/plugin/torch/torch_base.o' failed
make: *** [build/plugin/torch/torch_base.o] Error 1

**Comment by piiswrong** [comment]
The torch plugin isn't working for now. Compile without it.

**Comment by n1kt0** [comment]
Perhaps I could help somehow? Is resolving this error enough or are the issues more complex with torch? Is someone working on it?

**Comment by piiswrong** [comment]
You can fix this by changing CHECK_EQ(a, b) to CHECK(a == b) and simiar with CHECK_NE.

There is another issue with change in Torch. We have a pull request on this but the author disapeared https://github.com/dmlc/mxnet/pull/4329

**Comment by n1kt0** [comment]
I think I've managed the most stuff but there are still some problems with the logging facility:
Method 'stream' could not be resolved	iter_normalize.h	/mxnet/src/io	line 103	Semantic Error

somehow the macro doesn't expand to LOG_"XXX". I think here lies the Problem, but can't figure out what is wrong with that, conceptually it seems legit:

#define LOG(severity) LOG_ ## severity.stream()

is this macro trickery realy needed?

**Comment by n1kt0** [comment]
essentially it breaks when these two macros are used together:

note the semicolon which is missing in the macro so that you can append output with "<<" operator. When you delete it you get other types of errors on those two lines. so they affect each other 

`CHECK_EQ(unit_size_[i], d.data[i].Size());`

` MSHADOW_TYPE_SWITCH(data_[i].type_flag_, DType, {
            mshadow::Copy(
              data_[i].get<cpu, 1, DType>().Slice(top * unit_size_[i],
                                                  (top + 1) * unit_size_[i]),
              d.data[i].get_with_shape<cpu, 1, DType>(mshadow::Shape1(unit_size_[i])));
          }); `

the affected file is src/io/iter_batchloader.h on line 83 and 105

**Comment by piiswrong** [comment]
Did you change logging.h?
Currently everything out side of torch plugin should compile

**Comment by piiswrong** [comment]
It should be simple matter of changing `CHECK_NE(chunk, NULL);` to `CHECK(chunk != NULL);`

**Comment by n1kt0** [comment]
No i didn't touch it before the errors appeared, after that i played a little bit around. yes, i did the stuff you said but then the mentioned errors appeared.

**Comment by piiswrong** [comment]
try reset all changes beside CHECK_NE(chunk, NULL); to CHECK(chunk != NULL);

**Comment by githubfragments** [comment]
So ,we can not use torch in mxnet up to now?

**Comment by githubfragments** [comment]
Is there any versions of Torch we can use? @piiswrong

**Comment by n1kt0** [comment]
I've switched in the mean time to tensorflow and keras because i had to do my thesis and didn't have any more time to play around but i'm still interested after my thesis in a month or so to look at mxnet

**Comment by ChidanandKumarKS** [comment]
Any updates on using Torch functions in mxnet? is it possible?
