### ISSUE TITLE
SSD example crashes on CPUs

### ISSUE THREAD

**Issue by rsaffores** [apache/incubator-mxnet#4853]
Running the example given here crashes on CPUs both with and without MKL flags being set, but runs fine on GPUs:

https://github.com/dmlc/mxnet/tree/master/example/ssd

Steps to reproduce are described in the above link.  Just follow the steps as-is and when you run this it will crash:

python demo.py

The crash is show here:
[demo_crash.txt](https://github.com/dmlc/mxnet/files/746348/demo_crash.txt)

Eric can you take a look?

@piiswrong @zhenlinluo @glingyan

**Comment by glingyan** [comment]
seems that lack some operator for cpu

**Comment by howard0su** [comment]
please apply #4890 and run 
python demo.py --cpu

**Comment by rsaffores** [comment]
This fixed things for no MKL, but crashed if I enable MKL.  It crashes in the concat layer.  If I enable MKL, but disable MKL_EXPERIMENTAL for the concat layer it still crashes.  Both crashes are attached.  
[ssd_with_concat.txt](https://github.com/dmlc/mxnet/files/756019/ssd_with_concat.txt)
[ssd_without_concat.txt](https://github.com/dmlc/mxnet/files/756020/ssd_without_concat.txt)

@glingyan can you take a look as to why it may be crashing with MKL enabled?

**Comment by glingyan** [comment]
will do it today !

**Comment by glingyan** [comment]
mxnet master linked failed when DEBUG=1, I still could not solve this problem , takes me half day to finish debug in windows
I find the second callee to MultiBoxPriorOp , out data is unvalid
![image](https://cloud.githubusercontent.com/assets/22489989/22726310/d1651020-ee0d-11e6-8c80-1397bb8ed090.png)

**Comment by glingyan** [comment]
just share some finding by boundchecker

**Comment by glingyan** [comment]
![image](https://cloud.githubusercontent.com/assets/22489989/22932573/5cf90cb4-f303-11e6-9853-4a8e15cbf440.png)

**Comment by glingyan** [comment]
![image](https://cloud.githubusercontent.com/assets/22489989/22932604/747ef9a2-f303-11e6-906e-60c31cdbefe9.png)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
