### ISSUE TITLE
cannot declare pointer to ‘void*&’

### ISSUE THREAD

**Issue by ckapfer** [apache/incubator-mxnet#4860]
## Environment info
Operating System: CentOS 7.3.1611

Compiler: gcc 4.8.5

Package used (Python/R/Scala/Julia): Anaconda 2.3.0

MXNet version: Latest git pull ... v0.9.2-67-gdec952a

Or if installed from source:
MXNet commit hash (`git rev-parse HEAD`): 

dec952a9b65af10a4d5014c0930fac0b91aa7e4e

If you are using python package, please provide

Python version and distribution: Anaconda 2.7.13

If you are using R package, please provide

R `sessionInfo()`:  n/a

## Error Message:
Please paste the full error message, including stack trace.
Bug when installing the python interface:

python setup.py install 
<snip>
building 'mxnet/_cy2/.ndarray' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/mxnet
creating build/temp.linux-x86_64-2.7/mxnet/cython
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../include/ -I../nnvm/include -I/opt/anaconda/v2.3.0-caffe.app/include/python2.7 -c mxnet/cython/ndarray.cpp -o build/temp.linux-x86_64-2.7/mxnet/cython/ndarray.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
mxnet/cython/ndarray.cpp: In function ‘PyObject* __pyx_pf_7ndarray_22_make_ndarray_function_generic_ndarray_function(PyObject*, PyObject*, PyObject*)’:
mxnet/cython/ndarray.cpp:2512:36: error: cannot declare pointer to ‘void*&’
   __pyx_t_7ndarray_NDArrayHandle &*__pyx_t_15;
                                    ^
error: command 'gcc' failed with exit status 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

python setup.py install

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.  n/a, Compilation problem, python interface
2.
3.

## What have you tried to solve it?

1. n/a
2.
3.

**Comment by piiswrong** [comment]
You can turnoff cython. Easiest way is pip uninstall cython

**Comment by ckapfer** [comment]
Thanks ... while this would allow me to install, this doesn't actually solve the bug of course.  Also, an even easier workaround is to put a return statement in setup.py as the first line of config_cython(), but that also doesn't solve the underlying problem.

**Comment by abidmalik1967** [comment]
I am getting the same problem. Is there a solution? Is uninstalling cython the real solution. I am trying to install it on a cluster and uninstalling will need admin. privileges.

**Comment by piiswrong** [comment]
Should have been fixed now.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
