### ISSUE TITLE
Distributed Training. How does mxnet worker and ps find each other?

### ISSUE THREAD

**Issue by guotong1988** [apache/incubator-mxnet#4867]
http://mxnet.io/how_to/multi_devices.html

For example, if I run the instruction below from the link above. Which code or API could explain the mechanism about how the machines find each other? It seems that they just run in SSH way.

`../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync`

Thanks!

**Comment by formath** [comment]
When launching worker and server nodes, they send a control message of ADD_NODE to the scheduler. The scheduler will know the whole information about worker and server nodes. It then send a response message of this information to each node.

**Comment by guotong1988** [comment]
@formath Thank you. Can you tell me the exact code position?

**Comment by formath** [comment]
@guotong1988 most code in `van.cc` of ps-lite project.
`void void Van::Start() `
`void Van::Receiving()`

**Comment by guotong1988** [comment]
@formath Thank you. If we use ssh as the launcher. The releted code is:
https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_tracker/ssh.py
I have read the code from the link and my question is: How does the ssh launcher associate with the scheduler?

**Comment by formath** [comment]
The scheduler is launched in ssh.py:
```
def submit():
   ...
   tracker.submit()
```

Specially, it's in `class PSTracker` of tracker.py

**Comment by guotong1988** [comment]
May I ask that how does `van.cc` associate with `tracker.py`? 
@formath Thank you very much.

**Comment by formath** [comment]
KVScheduler, KVWorker and KVServer are system processes in which a `van` instance runs as a rpc tool. `tracker.py` is just to launch those processes.

**Comment by guotong1988** [comment]
@formath Could you please point the position where `PSTracker` launch the three system processes.
I can not find it from the link below. Thank you. 
https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_tracker/tracker.py#L333

**Comment by formath** [comment]
PSTracker just launch scheduler https://github.com/dmlc/dmlc-core/blob/48720bf08dff116fa4216015a69dde32586da770/tracker/dmlc_tracker/tracker.py#L363
server and worker launched by specific platform function https://github.com/dmlc/dmlc-core/blob/48720bf08dff116fa4216015a69dde32586da770/tracker/dmlc_tracker/tracker.py#L416

**Comment by guotong1988** [comment]
@formath Could you please have a look at this question. Thank you. #5157

**Comment by qiyuangong** [comment]
@guotong1988 

**First of all, all subprocesses or working nodes are launched with nearly the same command and parameters. So, how do they make sure they act just like we want?** 
The answer is the MXNet using `envs` to specify roles and other parameters, e.g., `env['DMLC_ROLE'] = 'scheduler'` means launch a `scheduler` process.

**Let's go back and see the whole workflow.** 

1. When you are submitting tasks with `tools/launch.py`, MXNet will redirect it to a specific script such as `ssh.py` according to your `--launch parameter`. 
2. Then, **all** these scripts will call `submit` defined in  `tracker.py`. In most cases, this submit function will try to init and launch a `PSTracker` (actually, it just write a few envs, e.g, `env['DMLC_ROLE'] = 'scheduler'`, and run the command you give). 
3. Then, it stores scheduler's **IP and port to `envs` ( `DMLC_PS_ROOT_URI ` and `DMLC_PS_ROOT_PORT `)**, such that `worker` and `server` can communicate or register with `scheduler`.
4. submit function in `ssh.py` etc is called by `tracker.py` (remember you have passed a function to tracker.submit). Note that envs are passed to this submit function.  This function will try to launch `worker` and `server` with given command and `envs`.  For worker nodes, their roles are  `env['DMLC_ROLE'] = 'woker'`.

**Comment by bigdata2** [comment]
@qiyuangong : Do you happen to know or can you point me to documentation/code explaining what export DMLC_NUM_SERVER=1 environment variable is for? I know that you can set more than one num_server, but it is not clear to me why it is needed, how it is used and how it is implemented. My understanding is that the scheduler resides on the server and that there is only one scheduler thus one server in the architecture. Does this num_server correspond to distributed KV_STORE?

**Comment by qiyuangong** [comment]
@bigdata2

I think you means `export DMLC_NUM_SERVER=$1`, which is located in `local.sh`.

`DMLC_NUM_SERVER ` is used to set number of `servers` (parameter server) launched during distributed training (when kvstore is set to be `dist_sync` or `dist_async`). 

For more details, you can search for `parameter server`. But, currently, we don't need to worry about this parameter. MXNet documents recommend us to use `tool/launch.py`  with `-n num` parameter, which launches `num` servers and `num` workers (with 1 `scheduler` launched in client side).

Well, these details are hidden in messes of docs (http://mxnet.io/how_to/multi_devices.html) and codes (https://github.com/dmlc/mxnet/blob/master/tools/launch.py#L53). I found these details by reading docs, codes and papers (http://www.cs.cmu.edu/~muli/file/parameter_server_osdi14.pdf).

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by thvasilo** [comment]
I'll leave this blog post here for future reference (not the author): https://blog.kovalevskyi.com/mxnet-distributed-training-explained-in-depth-part-1-b90c84bda725
