### ISSUE TITLE
PReLU gamma initialization with gamma = 0.0 should be better

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#4885]
Currently the PReLU gamma is initialized to be 1.0 because of the following code in Initializer.scala :

```
if (name.endsWith("gamma")) {
      initGamma(name, arr)
    } 
```

and 

```
  protected def initGamma(name: String, arr: NDArray): Unit = {
    arr.set(1f)
  }
```

I think it will be better to initialize PReLU gamma to 0.0 (or, 0.25 as in the original paper), as this will be closer to ReLU (which is a good starting point).

When gamma = 1.0 the unit is simply linear and hence not a very good starting point. So I suggest adding a parameter for PReLU's initialize value.

**Comment by piiswrong** [comment]
Should be fixed by this pr https://github.com/dmlc/mxnet/pull/4644

**Comment by cheshirecats** [comment]
@piiswrong Thanks. Could you take a look at my other question: https://github.com/dmlc/mxnet/issues/4837

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
