### ISSUE TITLE
scala source package is published but empty on Maven

### ISSUE THREAD

**Issue by fkirill** [apache/incubator-mxnet#4893]
Hey guys,

Publishing empty source package for Scala makes it difficult to browse the sources in the IDE.
Shouldn't be a difficult fix.

For example, see the contents of http://central.maven.org/maven2/ml/dmlc/mxnet/mxnet-core_2.10/0.1.1/mxnet-core_2.10-0.1.1-sources.jar

**Comment by piiswrong** [comment]
@javelinjs

**Comment by javelinjs** [comment]
I haven't figured out how to make maven correctly generate sources for Scala. Anyone can help? @CodingCat

**Comment by CodingCat** [comment]
I will check it...

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
