### ISSUE TITLE
Does Mxnet for windows support multi-device training?

### ISSUE THREAD

**Issue by Vogen** [apache/incubator-mxnet#4897]
I read Mxnet\dmlc-core\tracker\dmlc_tracker\mpi.py, and don't know how to install mpirun for windows.
I tried MS-MPI, it has mpiexec but not mpirun.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
