### ISSUE TITLE
Is it possible to do "broadcast_concat"?

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#4901]
Suppose I have a variable A, which has the shape of (1, 3, 4, 4), and a variable B with (1, 3, 1, 1). I have to concatenate them along axis=1, and get C = (1, 6, 4, 4). Since the current Concat symbol requires that B should be something like (1, *, 4, 4), I am wondering if there is a way I could do "broadcast concat"?

**Comment by sxjscience** [comment]
@ascust You can do the following
```python
B = mx.sym.broadcast_to(B, shape=(1, 3, 4, 4))
C = mx.sym.Concat(A, B, num_args=2, dim=1)
```

**Comment by ascust** [comment]
@sxjscience The problem is if I don't know the shape of A in advance, so it is actually a variable size.

**Comment by piiswrong** [comment]
you can use broadcast_to(B, shape=(0, 3, 0, 0))

**Comment by ascust** [comment]
Seems not working, I replaced "B = mx.sym.broadcast_to(B, shape=(1, 3, 4, 4))" with "B = mx.sym.broadcast_to(B, shape=(0, 3, 0, 0))". Is this what you meant? I got "infer shape" error. @piiswrong

**Comment by umutisik** [comment]
The following works for me:
```python
class TestModel(gluon.HybridBlock):
    def __init__(self, **kwargs):
        super(TestModel, self).__init__(**kwargs)
        # self.c2 = self.params.get_constant('c2', [[1,2,3]])
        self.c2 = self.params.get_constant('c2', np.arange(12).reshape([1,3,2,2]).tolist()) # 1,3,2,2
        self.compa = 1.
        
    def hybrid_forward(self, F, x, **kwargs):
        c = F.broadcast_to(kwargs['c2'], shape=(-1, 0, 0, 0)) 
        return F.concat(c, x, dim=1) 

model = TestModel()
model.hybridize()
model.initialize()
# x = np.arange(100).reshape([5,5,2,2])*100.
x = np.ones([5,5,2,2])*100.
x = nd.array(x)
out = model(x)
print(out.shape)
print(out[0, 0])
print(out[0, 3])
```

Shape -1 is not supported in ndarray though.
But I only needed the non-fixed size in symbol.
