### ISSUE TITLE
I find that the version 0.9.3 really has a big promotion

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#4912]
the more CPUs I set the faster it performed，little while ago the more CPUs i set the slower it was，though the cpu utilization percentage was so high. and the distributed training is faster obviously than other deep learning frame like paddle

**Comment by janelu9** [comment]
But there is a fatal problem why it often interrupts unpredictable

**Comment by piiswrong** [comment]
Please provide more info.
hardware?
config.mk setting?
full error message with stacktrace?

**Comment by janelu9** [comment]
hardware are Inspur server NF5280M4×2  with ：intel Xeon cpu e5-2670 v3（12cores 24threads/cpu）×2，256g memory，2T Hard disk，Gigabit Lan，Suse 12
docker version is 1.2
the docker image is Ubuntu 14.04 LTS with mxnet 0.9.3
config.mk 's setting is almost the default and I only echo "USE_DIST_KVSTORE = 1" to it at the end
I built the docker container on the servers with command：
docker run --name mxnet_8cpu -d -v ... -m 64g --cpuset=8...15 -it .....
and I add the cpu number by setting：ctx=[mx.context.cpu(i) for i in range(cpu_num)]
when I let cpu_num=4 or 8 it interrupted unpredictable sometimes without any messages

**Comment by janelu9** [comment]
maybe the way I set the cpu number was unreasonable , It's used to set the gpu number

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
