### ISSUE TITLE
Bug if do backward on symbol mean

### ISSUE THREAD

**Issue by lisabug** [apache/incubator-mxnet#4917]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc4.8.4

Package used (Python/R/Scala/Julia): Python

MXNet version: Master Latest

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

> Traceback (most recent call last):
>   File "test.py", line 20, in <module>
>     mod.backward([mx.nd.array([1.0], dtype=np.float32)])
>   File "/home/lisabug/.virtualenvs/nnvm/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7-linux-x86_64.egg/mxnet/module/module.py", line 487, in backward
>     self._exec_group.backward(out_grads=out_grads)
>   File "/home/lisabug/.virtualenvs/nnvm/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7-linux-x86_64.egg/mxnet/module/executor_group.py", line 437, in backward
>     end=islice.stop)
>   File "mxnet/cython/ndarray.pyx", line 167, in ndarray._make_ndarray_function.generic_ndarray_function (mxnet/cython/ndarray.cpp:3602)
>   File "mxnet/cython/base.pyi", line 36, in ndarray.CALL (mxnet/cython/ndarray.cpp:1731)
> mxnet.base.MXNetError: [16:15:17] src/operator/tensor/./matrix_op-inl.h:1028: Check failed: (*end <= axis_size) && (*end >= 0) Invalid begin, end, get begin=0, end=3

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```Python
import mxnet as mx
import numpy as np

data = mx.sym.Variable('data')
data = mx.sym.mean(data)

mod = mx.mod.Module(symbol=data, data_names=('data',), label_names=None)
mod.bind(data_shapes=[('data', (3, 1))])
mod.init_params()
mod.init_optimizer()

x = mx.nd.array([[1.0], [2.0], [3.0]], dtype=np.float32)

batch = mx.io.DataBatch([x], label=None)
mod.forward(batch, is_train=True)
mod.backward([mx.nd.array([1.0], dtype=np.float32)])
mod.update()
```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by sxjscience** [comment]
@lisabug Due to the automatic slicing in the backward.
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py#L431-L443
The slice is determined by the batch_size, which is assumed to be 3 in this example.
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py#L210-L211

**Comment by lisabug** [comment]
@sxjscience Yes. The automatic slicing itself caused the problem of backward on mean symbol since the output of mean symbol is a scalar instead of a tensor of size (b,).

**Comment by sxjscience** [comment]
Close it now and we suggest using gluon in the future.
