### ISSUE TITLE
No module named bbox when running rcnn demo.py

### ISSUE THREAD

**Issue by realbns2008** [apache/incubator-mxnet#4919]
I have met probelm when running the demo.py in rcnn.
The exception says :

"File "/mnt/gelu/mxnet/example/rcnn/rcnn/processing/bbox_transform.py", line 2, in 
from ..cython.bbox import bbox_overlaps_cython
ImportError: No module named bbox"

I'm pretty sure that i have compiled and installed all operators.

I have solve the problem by doing the following steps:

I make the following changes to the project and fix the problem:
1.add following lines of code before import '..cython.bbox import bbox_overlaps_cython' in rcnn/processing/bbox_transform.py:
	import pyximport
	pyximport.install()

2.edit the setup.py in rcnn/cython/:
  change the code from ['nms_kernel.cu', 'gpu_nms.pyx'], to ['nms_kernel.cu', 'gpu_nms.cpp'],

3. run the command: python setup.py install under the above directory

4. copy 3 .so files from rcnn/cython/build/lib.linux-x86_64-2.7/ to ~/.pyxbld/lib.linux-x86_64-2.7/rcnn/cython

I just want to ask is there any more nice way to solve this problem ?

**Comment by sxjscience** [comment]
@precedenceguo

**Comment by xinyifcc** [comment]
## There is a easy way to solve this problem 
And here's the code! 

under your rcnn file     ~/rcnn/

```javascript
# install cython
sudo pip install cython scikit-image easydict
# build cython extension
make
```

### problem solved!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
