### ISSUE TITLE
Detecting for MACRO DMLC_USE_CXX11 is not properly for MSVC

### ISSUE THREAD

**Issue by lygstate** [apache/incubator-mxnet#4921]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Windows
Compiler:
vs 2015
Package used (Python/R/Scala/Julia):
C++
MXNet commit hash (`git rev-parse HEAD`):
85636ff1a015d04d3a8f960bc644b85ee5157135

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
