### ISSUE TITLE
cpu number is not the more the better

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#4931]
As a convex function ,4 is the best ,isn't  it?

**Comment by VoVAllen** [comment]
Hard to understand your problem. Could you elaborate more?

**Comment by janelu9** [comment]
From 1 to 4, the more the CPUs are used the faster the train will be. when the CPUs' number is more than 4. the speed will slow down

**Comment by sbodenstein** [comment]
If you want an intelligent answer, you should specify relevant details:
* How many physical cores does your CPU have?
* What do you mean by "CPU Number"? The max OpenMP thread number that you are setting via `OMP_THREAD_NUM`? or one of these: http://mxnet.io/how_to/env_var.html
One hypothesis: your machine has four physical cores, and when setting a higher thread number than 4, launching more threads means using hyperthreading, which can cause performance problems.

**Comment by janelu9** [comment]
@sbodenstein  thank you. I know what's wrong with it , pardon me for my major is math. and I am unfamiliar with the the underlying development

**Comment by janelu9** [comment]
@sbodenstein hello I didn’t find any change when I set OMP_THREAD_NUM if I did not use MKL, but when I use MKL the model is not convergence at the same epoch though it really becomed faster  as the OMP_THREAD_NUM set

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
