### ISSUE TITLE
[bugs] label grad for loss operator

### ISSUE THREAD

**Issue by feiyulv** [apache/incubator-mxnet#4933]
currently, mxnet did't handle label grad in loss operator, this will cause random problems when label is generated by a subnet. Maybe set the label grad to zero is a good idea to avoid this problem

**Comment by sxjscience** [comment]
@feiyulv How about adding BlockGrad to the generated labels?

**Comment by feiyulv** [comment]
@sxjscience Yes, it will solve this problem, but for the newers of mxnet, it will be easy to make a mistake and hard to debug

**Comment by sxjscience** [comment]
@feiyulv I think setting the label grad to zero is a good solution.

**Comment by sxjscience** [comment]
Close it now.
