### ISSUE TITLE
Is RNN operator of CPU  version in developing？

### ISSUE THREAD

**Issue by artzers** [apache/incubator-mxnet#4942]
Though the speed of RNN and 3D CNN of cpu version may be very slow, I think high level operator of CPU version is in need for algorithm tests and little projects.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by gautamkmr** [comment]
@artzers Please add more details on algorithm tests

**Comment by szha** [comment]
We have CPU RNN API in frontend such as in mx.rnn and mx.gluon.rnn.
