### ISSUE TITLE
The accuracy of imagenet1k-inception-bn

### ISSUE THREAD

**Issue by blazerygy** [apache/incubator-mxnet#4946]
I use inception-bn to train imagenet 2012, after 100 epochs, the train accuracy: 0.90(top1)、 0.98(top5),
and the val accuracy:**0.67**(top1)、**0.87**(top5), are lower than **0.7245**(top1)、**0.9079**(top5) given by
[Single Center Crop Accuracy](https://github.com/dmlc/mxnet/tree/master/example/image-classification) so I doubt it.
can you give the values of the following parameters for training to get the given result?
(1)--batch-size
(2)--lr
(3)--lr-factor
(4)--data-shape
(5)--num-epoch
and  the following parameters for train data and val data?
(1)--resize
(2)--quality
(3)rand_crop
(4)rand_mirror

Thx

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
