### ISSUE TITLE
Typo for "output_names" in module's document

### ISSUE THREAD

**Issue by dnaase** [apache/incubator-mxnet#4948]
Hi,
I am a beginner for mxnet. Just found a typo in your mxnet online document. 

http://mxnet.io/api/python/module.html#

When initialize module, it requires you to provide both of "data_names" and "output_names". However, it should be "label_names" here. Otherwise, it will give error msg

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
