### ISSUE TITLE
mxnet example error

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#4956]
Dear all:

I have found an error when running fine-tuning  pre-trained example (http://mxnet.io/how_to/finetune.html) with the latest mxnet version. Is there any way to fix it?

Traceback (most recent call last):
  File "FineTune.py", line 76, in <module>
    mod_score = fit(new_sym, new_args, aux_params, train, val, batch_size, num_gpus)
  File "FineTune.py", line 66, in fit
    return mod.score(val)
TypeError: score() takes at least 3 arguments (2 given)

**Comment by devaib** [comment]
Hello, @lincolnBush.
First,

`from mxnet import metric`

then,

`metric = mx.metric.Accuracy()`
`return mod.score(val, metric)`

There are also [other metrics](https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L128) for you to choose from.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
