### ISSUE TITLE
What's the meaning of "index" in batch_norm.cc?

### ISSUE THREAD

**Issue by eldercrow** [apache/incubator-mxnet#4961]
In src/operator/batch_norm.cc, line 50, there is a script for initializing some internal variables.
Here, variables are indexed by the argument "const int index", but I have no idea how to compute the correct index to access each variable to be initialized. 

Can anyone explain me about this? 

```c++
NNVM_REGISTER_OP(BatchNorm)
.set_attr<nnvm::FSetInputVarAttrOnCompose>("FSetInputVarAttrOnCompose",
    [](const nnvm::NodeAttrs& attrs, nnvm::NodePtr var, const int index) {
      if (var->attrs.dict.find("__init__") != var->attrs.dict.end()) return;
      if (index == 3) {
        var->attrs.dict["__init__"] = "[\"zero\", {}]";
      } else if (index == 4) {
        var->attrs.dict["__init__"] = "[\"one\", {}]";
      }
    });
```

**Comment by piiswrong** [comment]
It's just the order in list_arguments() + list_auxiliary_states

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
