### ISSUE TITLE
Error while building Python wrapper for speech demo 

### ISSUE THREAD

**Issue by baileyqbb** [apache/incubator-mxnet#4962]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04 LTS

Compiler: g++

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.9.3

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 2413a8ed421b5a917eed544b08d434839b8c812d 

If you are using python package, please provide

Python version and distribution: Python 2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

I was trying the example/speech-demo. While building Python wrapper for kaldi toolkits after installing the kaldi in the system successfully, I got the following error：

g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/beibei.qian/kaldi/tools/ATLAS/include -I/home/beibei.qian/kaldi/tools/openfst/include  -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include   -c -o ctypes.o ctypes.cc
ctypes.cc: In function ‘kaldi::nnet1::Nnet_t* Nnet_new(char*, float, int)’:
ctypes.cc:206:25: error: ‘class kaldi::nnet1::Nnet’ has no member named ‘SetDropoutRetention’
       nnet->nnet_transf.SetDropoutRetention(dropout_retention);
                         ^
ctypes.cc:209:25: error: ‘class kaldi::nnet1::Nnet’ has no member named ‘SetDropoutRetention’
       nnet->nnet_transf.SetDropoutRetention(1.0);
                         ^
In file included from ../base/kaldi-common.h:38:0,
                 from ../util/table-types.h:23,
                 from ctypes.cc:3:
../base/kaldi-math.h: At global scope:
../base/kaldi-math.h:130:17: warning: ‘kaldi::kLogZeroBaseFloat’ defined but not used [-Wunused-variable]
 const BaseFloat kLogZeroBaseFloat = -std::numeric_limits<BaseFloat>::infinity();
                 ^
make: *** [ctypes.o] Error 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Download and install Kaldi
2. Copy example/speech-demo/python_wrap/ to kaldi/src/
3. cd kaldi/src/python_wrap
4. make

## What have you tried to solve it?

1. Pull the latest Kaldi and reinstall
2. Pull the latest mxnet
3.

**Comment by tinyloop** [comment]
I met the same problem. I guess it may be caused by the update of Kaldi.
So, I try to use the older Kaldi around seven month ago, the problem disappeared.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
