### ISSUE TITLE
OP request: softmax with mask

### ISSUE THREAD

**Issue by magic282** [apache/incubator-mxnet#4963]
Hi,

I think that attention mechanism can be acccelerated if we have a softmax OP with mask.
Currently the input sentences are of different length and I fix this ugly as follows:
```python
if use_masking:
    energy = energy * attend_masks[idx] + (1.0 - attend_masks[idx]) * (-10000.0)  # (batch, 1)
```
But if there is softmax with mask, we can change to a faster implementation without computing energe for each source sentence word.

**Comment by magic282** [comment]
Also, this is useful for decoder vocabulary constraint.

**Comment by sbodenstein** [comment]
@magic282: One solution: `SequenceMask("value" -> "-INF", "use_sequence_length" -> true)`, followed by Softmax. On GPU, this will be your fastest option, as you can use cuDNN Softmax, which will be faster than a custom softmax you could write.

Having a built-in attention layer written in MShadow would be very nice, and could be made faster/memory efficient than building it out of layers.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
