### ISSUE TITLE
Mxnet symbol implementation details?

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#4971]
Dear all:

I am trying to implement a structure as follows:

Image1--->Res Net(except for last layer)
//////////////////////////////////////////////diff -> predict result
Image2--->Res Net(except for last layer)

or:

Image_Combined -> slice channel-> Image1--->Res Net(except for last layer)
///////////////////////////////////////////////////////////////////////////////////////diff -> predict result
//////////////////////////////////////////Image2--->Res Net(except for last layer)

Which way is easier. I am now trying the second way. The problem is that how to use the previous resnet  symbols to do this, as the original resnet symbol get a variable named 'data' as the input, how to make the output of slice channel transmit data to the variable 'data' and how to initialize the network with pretrained parameters? Or is there are any examples or smarter ways of doing this.

**Comment by lincolnBush** [comment]
The problem may be regarded as how to link a symbol to head instead of tails

**Comment by nicklhy** [comment]
I guess you can implement it like this,
1. use a (N, 2, C, H, W) tensor as the network's input.
2. reshape it to (2*N, C, H, W) and extract features for both images with any CNN you want. The output should be (2*N, M).
3. use slice channel operation to split each image's feature. (2*N, M) -> (N, M) x 2;
4. compute the difference like mx.sym.sum(mx.sym.square(f1-f2)) where f1 and f2 are the two feature vectors in step 3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
