### ISSUE TITLE
MXNet Symbol Implementation details(2)

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#4972]
Dear all
Do you have any idea of what's the meaning of arg_nodes and node_row_ptr, heads.

Example code:
import mxnet as mx
a = mx.sym.Variable('a')
b = mx.sym.Variable('b')
c = a + b
print(c.tojson())

output:
{
 "nodes": [
   {
     "op": "null", 
     "name": "a", 
     "inputs": []
   }, 
   {
     "op": "null", 
     "name": "b", 
     "inputs": []
   }, 
   {
     "op": "elemwise_add", 
     "name": "_plus1", 
     "inputs": [[0, 0, 0], [1, 0, 0]]
   }
 ], 
 "arg_nodes": [0, 1], 
 "node_row_ptr": [0, 1, 2, 3], 
 "heads": [[2, 0, 0]], 
 "attrs": {"mxnet_version": ["int", 904]}
}

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by KeyKy** [comment]
I also want to know the meaning of node_row_ptr
