### ISSUE TITLE
GPU build notes for Ubuntu 16.10

### ISSUE THREAD

**Issue by ck37** [apache/incubator-mxnet#4978]
Hello,

It took some tweaks to get mxnet built with gpu support on Ubuntu 16.10, so I wanted to document things I had to do for possible incorporation into the build instructions (http://mxnet.io/get_started/ubuntu_setup.html#build-the-shared-library) and for others' reference.

This is based on the source code as of 2017-02-10, commit 70df5ad736f1cd462b6b583917032e8f2dd127be

## 1. Ubuntu 16.10 uses gcc-6, but CUDA 8.0 currently requires gcc 5.4 or earlier to compile.

We need to tell the make system to use gcc-5 (https://codeyarns.com/2015/02/26/how-to-switch-gcc-version-using-update-alternatives/):

```bash
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```

## 2. Instructions install the Atlas BLAS but we append OpenBLAS to the config.mk file.

We need to either make sure we have OpenBLAS (`sudo apt-get install openblas`) or remove/edit the config.mk line that specifies openblas: `USE_BLAS=openblas` so that we use atlas.

## 3. Ubuntu 16.10 uses OpenCV 2.4, but the installation instructors add a config part that requires OpenCV 3.

Remove `-lopencv_imgcodecs` from ADD_LDFLAGS in config.mk or manually install OpenCV 3 (https://www.hiroom2.com/2016/05/20/ubuntu-16-04-install-opencv-3-1/)

With those tweaks I was able to build the shared library, and everything worked out from there.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
