### ISSUE TITLE
How to use mxnet?

### ISSUE THREAD

**Issue by dinasaif** [apache/incubator-mxnet#4989]
I want to use mxnet in deep learning ,I have CSV file with binary features and 2 class labels (0,1) ,How can I train and test my data with mxnet and deep belief network?
Thanks

**Comment by VoVAllen** [comment]
http://mxnet.io/api/python/io.html#mxnet.io.CSVIter

Please go through the tutorial on http://mxnet.io and the example folder.

**Comment by EsraaRagaa** [comment]
The tutorials are unclear, I guess after preparing the iterator their should be an example of how to pass this iterator to mxnet as training and testing with lables

**Comment by edmBernard** [comment]
http://mxnet.io/api/python/module.html#overview
or you can check the new gluon tutorial : http://thestraightdope.mxnet.io/
