### ISSUE TITLE
combining demo3-dssm.ipynb with rating based solutions

### ISSUE THREAD

**Issue by pianoman4873** [apache/incubator-mxnet#4991]
How would you combine the additional user data ( for example search queries ) in the demo2 solution - i.e. rating based solution ?
Would the item ( movie ) embedding be simply augemented with its title and image ( like the augmentation done for the user ) ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
