### ISSUE TITLE
can't convert from numpy array to mx.nd.array

### ISSUE THREAD

**Issue by dnaase** [apache/incubator-mxnet#4992]
I met the error with newest mxnet version 
(mxnet: 0.9.3 with python 2.7 in Ubuntu 16.04.1 LTS, gcc version 5.4.0).

Here is my code to generate the error:

import mxnet as mx
import numpy as np
t1=mx.nd.array(np.zeros((12000, 3, 224, 224), dtype='float32'))
t2=mx.nd.array(np.zeros((120000, 3, 224, 224), dtype='float32'))

t1 is fine, but t2 will produce error msg like this:

MXNetError Traceback (most recent call last)
in ()
----> 1 t2=mx.nd.array(np.zeros((120000, 3, 224, 224), dtype='float32'))

/home/yaping/mxnet/python/mxnet/ndarray.pyc in array(source_array, ctx, dtype)
1121 raise TypeError('source_array must be array like object')
1122 arr = empty(source_array.shape, ctx, dtype)
-> 1123 arr[:] = source_array
1124 return arr
1125

/home/yaping/mxnet/python/mxnet/ndarray.pyc in setitem(self, in_slice, value)
269 _internal._set_value(float(value), out=self)
270 elif isinstance(value, (np.ndarray, np.generic)):
--> 271 self._sync_copyfrom(value)
272 else:
273 raise TypeError('type %s not supported' % str(type(value)))

/home/yaping/mxnet/python/mxnet/ndarray.pyc in _sync_copyfrom(self, source_array)
342 self.handle,
343 source_array.ctypes.data_as(ctypes.c_void_p),
--> 344 ctypes.c_size_t(source_array.size)))
345
346 def _slice(self, start, stop):

/home/yaping/mxnet/python/mxnet/base.pyc in check_call(ret)
73 """
74 if ret != 0:
---> 75 raise MXNetError(py_str(_LIB.MXGetLastError()))
76
77 if sys.version_info[0] < 3:

MXNetError: [10:06:08] include/mxnet/././tensor_blob.h:243: Check failed: this->shape_.Size() == shape.Size() (18063360000 vs. 883490816) TBlob.get_with_shape: new and old shape do not match total elements

**Comment by sxjscience** [comment]
Cannot reproduce the error. (120000, 3, 224, 224) is too large and will raise the MemoryError.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
