### ISSUE TITLE
What about adding mxnet to pip ?

### ISSUE THREAD

**Issue by thesby** [apache/incubator-mxnet#4998]
What about adding mxnet to pip so that we can easily install mxnet?

**Comment by piiswrong** [comment]
Try pip install mxnet and pip install mxnet_gpu.
We have a experimental version that support linux (ubuntu and maybe some other newer distros) and mac os.

**Comment by szha** [comment]
For GPU support, I've published mxnet-cu80 and mxnet-cu75 which supports CUDA8.0 and 7.5 respectively to replace mxnet-gpu. Both versions use cuDNN5.1.
