### ISSUE TITLE
Question about the scalable training

### ISSUE THREAD

**Issue by pineking** [apache/incubator-mxnet#5001]
Suppose we start a distributed mxnet training job with 3 ps and 10 workers. In the training, I need to scale the job to 1 ps and 5 workers, Does MXNet support this scalable training ? If it is supported , How we can do it ?

**Comment by piiswrong** [comment]
shutdown and restart from checkpoint

**Comment by pineking** [comment]
@piiswrong what's the checkpoint meaning? could we have some methods or APIs which can communicate with the scheduler to increase/decrease the number of ps/workers dynamically instead of shutdown and restart directly.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
