### ISSUE TITLE
Error with VGG model loading.

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#5005]
Dear all:

The vgg models in the data center cannot be loaded correctly by current mxnet. The error messages are as below:

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-8-e2cb7ab98622> in <module>()
      1 import mxnet as mx
----> 2 sym, arg_params, aux_params = mx.model.load_checkpoint('vgg16',0)
/.virtualenvs/HDR/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/model.pyc in load_checkpoint(prefix, epoch)
    371     - parameters will be loaded from ``prefix-epoch.params``.
    372     """
--> 373     symbol = sym.load('%s-symbol.json' % prefix)
    374     save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/symbol.pyc in load(fname)
   1067         raise TypeError('fname need to be string')
   1068     handle = SymbolHandle()
-> 1069     check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
   1070     return Symbol(handle)
   1071 
/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: [20:05:12] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "vgg16-symbol.json"

**Comment by VoVAllen** [comment]
Try to bind 54.208.175.7 with data.dmlc.ml in hosts

I'm not sure whether this could work or not

**Comment by lincolnBush** [comment]
@VoVAllen  Sorry, I think that cannot work. Maybe we need to modify the current models to enable it to be compatitable with current mxnet version

**Comment by darrylbobo** [comment]
@lincolnBush 

did you solve the issue? I also have the same problem with loading vgg16 or caffenet.

**Comment by lincolnBush** [comment]
Not yet, get stuck.

2017-03-07 21:43 GMT+00:00 darrylbobo <notifications@github.com>:

**Comment by darrylbobo** [comment]
@lincolnBush  

I solved mine. This is because the json file for VGG16 downloading from the model zoo is broken, if directly using their provided url. 

So, I would suggest you literally download the model, and check the completeness of them before using.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
