### ISSUE TITLE
[Question] Setting the updater of PS in backend (c++)

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#5006]
I'm wondering if it is possible to set the updater in parameter server using KVStoreDistServer.set_updater directly in the backend (c++), and currently this seems to be called from the C API from Python calls that I do not quite understand.

I'm wondering whether I can achieve the same thing by calling into that method directly? If so, what updater should be used and how?

Many thanks!

**Comment by piiswrong** [comment]
You can call it from C++. If you do that you need to set it to a functor with necessary states for the update. The prototype is here https://github.com/dmlc/mxnet/blob/master/python/mxnet/kvstore.py#L39

**Comment by Luo-Liang** [comment]
Thanks! I was looking at the same code, but I don't understand where is the implementation of updater itself. It seems the wrapper wraps the call. What is the actual implementation of updater? Thanks for the patience 😊

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py#L800

**Comment by Luo-Liang** [comment]
Thanks! Do I need to reimplement those in c++, or do I need to call that from c++? Sorry I still don't get it 😔

**Comment by piiswrong** [comment]
You need to implement the update and optimizer in c++. Shouldn't be too hard, you can see MXNet.cpp for example. ccoptimizer is removed though, you need to use the new operators instead.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
