### ISSUE TITLE
mxnet on centos 7

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-mxnet#5007]
http://mxnet.io/get_started/centos_setup.html

I have tried it on centos 7. I dont see python27 but

$ sudo yum install python-devel
$ sudo pip install numpy

Does anyone try following the rest of the tutorial on centos 7?
Or the document is out of date?

## Environment info
Operating System:

centos 7 with kernel 3.10

**Comment by qiyuangong** [comment]
Type `python --version` then`pip --version` in command line to check if both of them are properly installed. Then you can try the rest of the tutorial (just updated in Jan-2017).

**Comment by chakpongchung** [comment]
Anything wrong?

[cpchung@cam-linx-100 Downloads]$ pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
[cpchung@cam-linx-100 Downloads]$ python --version
Python 2.7.5

[cpchung@cam-linx-100 Downloads]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[cpchung@cam-linx-100 Downloads]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by qiyuangong** [comment]
Seems all right. :)

**Comment by luoyetx** [comment]
@chakpongchung python27 is the default python on CentOS7. python is an alias to python27.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
