### ISSUE TITLE
Amalgamation for android failed on Dropout layer

### ISSUE THREAD

**Issue by pallashadow** [apache/incubator-mxnet#5009]
## Environment Info

Operating System: Ubuntu 14.04 64bit Desktop
Compiler: arm-linux-androideabi-clang++
MXNet version: v0.9.3
NDK vesion: android-ndk-r13b

## Error Discription

error message: 

> org.dmlc.mxnet.MxnetException: value 4.14277e-314 for Parameter p exceed bound [4.14277e-314,4.14277e-314], in operator Dropout(name="dropout0", p="0.5")

it is thrown out by these lines in file **amalgamation/mxnet_predict-all.cc** perhaps passed from file **dmlc-core/include/dmlc/parameter.h**
```
if (v < begin_ || v > end_) {
        os << "value " << v << " for Parameter " << this->key_
           << " exceed bound [" << begin_ << ',' << end_ <<']';
        throw dmlc::ParamError(os.str());
```

It will happen for any network carrying dropout layer, including NIN and inception network from Mxnet Zoo. 

Where does the number 4.14277e-314 comes from? It doesn't make sense for v=4.14277e-314 in this case is not exceed the bound of [4.14277e-314,4.14277e-314]. 

## Compiling Steps
My compiling process is listed in https://github.com/dmlc/mxnet/issues/4969

**Comment by piiswrong** [comment]
@sbodenstein Related to the stof issue?

**Comment by kensaem** [comment]
@pallashadow 
I met the exactly same issue.
When I removed "src/operator/dropout-inl.h:63", it does not fail to load on dropout, anymore.

@piiswrong 
Would you check out the mechanism of "set_range" on parameter?
In my thought, it does not operate correctly when it get parameters as float.

**Comment by sbodenstein** [comment]
@piiswrong: wasn't the stof issue resolved?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
