### ISSUE TITLE
MxNet can't fully utilize CPU in multithread programs

### ISSUE THREAD

**Issue by liurenjie1024** [apache/incubator-mxnet#5015]
Hi, all:
I'm using mxnet scala package and runs prediction in a multithread program and each thread has a thread local FeedForward instance. It seems that mxnet is not able to utilize multi cores since only one core is busy while I have 20 threads in this program.  The java stacktrace show that all  threads are in   this mxNDArraySyncCopyToCPU method. Is this method waiting some lock for all threads in the same process? One quick solution may be to  use multi process instead of multi thread but jvm has much heavy overhead and this is may be my last resort. Is there any way to solve this issue?

**Comment by javelinjs** [comment]
@piiswrong @tqchen Any idea why this happens? It seems that all the threads bind the same cpu.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
