### ISSUE TITLE
A little bug in mxnet python code

### ISSUE THREAD

**Issue by Vandermode** [apache/incubator-mxnet#5016]
Hi, I'm new to mxnet, and I am walking through a kaggle project to familiar with its python interface.
But something confused me when I try to call mx.mod.Module.predict function to complete my final work.
Since there was no headache when I called mx.mod.Module.score function, predict function should also work fine unless bug around. Then I read through python source code to find the bug.
following info displayed when I run the code `best_model.predict(eval_data=test)`

`---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-14-6eee4a79ad10> in <module>()
----> 1 best_model.predict(eval_data=test)

/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/base_module.pyc in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    291             self.forward(eval_batch, is_train=False)
    292             pad = eval_batch.pad
--> 293             outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
    294 
    295             output_list.append(outputs)

/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/ndarray.pyc in __getitem__(self, in_slice)
    317             raise ValueError('NDArray only support continuous slicing on axis 0')
    318         if in_slice.start is not None or in_slice.stop is not None:
--> 319             return self._slice(in_slice.start, in_slice.stop)
    320         else:
    321             return self

/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/ndarray.pyc in _slice(self, start, stop)
    358         stop = mx_uint(stop) if stop else mx_uint(self.shape[0])
    359         check_call(_LIB.MXNDArraySlice(
--> 360             self.handle, start, stop, ctypes.byref(handle)))
    361         return NDArray(handle=handle, writable=self.writable)
    362 

/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: [23:38:09] include/mxnet/ndarray.h:262: Check failed: shape_[0] >= end (200 vs. 201) Slice end index out of range`

Notice it's an index out of range problems, and the fault is directed by ` outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]`, I check the variable `pad` and find it equals to -1.

That's the key problem. Next I find where `pad` defined. Since I initialize `test` variable by following code
`test = mx.img.ImageIter(
    batch_size=batch_size,
    data_shape=data_shape,
    path_imgrec='test/test.rec',
    resize=resize,
    mean=mean_img,
    std=std_img)`

I check `image.py` and find `pad` is assigned by `batch_size-1-i` from `return io.DataBatch([batch_data], [batch_label], batch_size-1-i)` of 455 line.
By just change the `batch_size-1-i` to `max(batch_size-1-i, 0)` , I successfully fixed the bug.
But I still not sure whether the right code is `max(batch_size-1-i, 0)` or `batch_size-i`
the second way also fix the problem.

Any idea about this little bug? and if I certainly fix the bug, could you give me a chance to help me pull request to merge my little work into mxnet? Thank you,

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
