### ISSUE TITLE
why DMLC server process utilize all CPU but not limit by nthread_reduction? 

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#5020]
@mli @piiswrong 

When I run below command on BDW server which have 44 cores.  
export PS_VERBOSE=1;export OMP_NUM_THREADS=40;export KMP_AFFINITY=granularity=fine,compact,1,0; ../../tools/launch.py -n 1 --launcher ssh -H hosts python train_imagenet.py --batch-size 144 --lr 0.05 --lr-factor .94 --num-epoch 1 --kv-store dist_sync --network inception-bn --data-train data/train.rec --data-val data/val.rec 

I found there have two major process running. One is DMLC worker and another one is DMLC server. However, I found DMLC server process will init subthread on all of the CPU cores. This is not happen when I set kv-store=local. When running local, I only see 4 subthreads which equal to nthread_reduction. 

Could you pls let me know how to limit the threads when kvstore=dist_sync?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
