### ISSUE TITLE
 error: more than one instance of overloaded function "max" matches the argument list

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-mxnet#5021]
[cpchung@cam-linx-100 mxnet]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[cpchung@cam-linx-100 mxnet]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[cpchung@cam-linx-100 mxnet]$ uname -a
Linux cam-linx-100 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

src/operator/tensor/././indexing_op-inl.cuh(170): error: more than one instance of overloaded function "max" matches the argument list:
            function "max(int, int)"
            function "max(unsigned int, unsigned int)"
            function "max(int, unsigned int)"
            function "max(unsigned int, int)"
            function "max(long long, long long)"
            function "max(unsigned long long, unsigned long long)"
            function "max(long long, unsigned long long)"
            function "max(unsigned long long, long long)"
            function "max(float, float)"
            function "max(double, double)"
            function "max(float, double)"
            function "max(double, float)"
            argument types are: (size_t, size_t)
          detected during:
            instantiation of "void mxnet::op::AddTakeGradLargeBatchCaller(const mxnet::OpContext &, mshadow::Tensor<xpu, 2, DType>, const mshadow::Tensor<xpu, 1, IndexType> &, const mshadow::Tensor<xpu, 2, DType> &) [with xpu=mxnet::gpu, IndexType=float, DType=float]" 
src/operator/tensor/./indexing_op.h(234): here
            instantiation of "void mxnet::op::EmbeddingOpBackward<xpu>(const nnvm::NodeAttrs &, const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]" 
src/operator/tensor/indexing_op.cu(15): here

sudo yum check-update 

 #Install gcc-4.8/make and other development tools
sudo yum install -y gcc
sudo yum install -y gcc-c++
sudo yum install -y clang

# Install Python, Numpy, pip and set up tools.

sudo yum install python-devel
sudo pip install numpy

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
pip -V

# install graphviz, jupyter
sudo -E pip install graphviz
sudo -E pip install jupyter

# Install OpenBLAS at /usr/local/openblas
git clone https://github.com/xianyi/OpenBLAS
cd OpenBLAS
sudo make -j $(($(nproc) + 1))
sudo make PREFIX=/usr/local install
cd ..

 # Install cmake for building opencv
sudo yum install -y cmake

# Install OpenCV at /usr/local/opencv
git clone https://github.com/opencv/opencv
cd opencv
mkdir -p build
cd build
cmake -D BUILD_opencv_gpu=OFF -D WITH_EIGEN=ON -D WITH_TBB=ON -D WITH_CUDA=OFF -D WITH_1394=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
sudo make PREFIX=/usr/local install	

# Download MXNet source code to ~/mxnet directory
git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive
# Move to source code parent directory
cd ~/mxnet
cp make/config.mk .
# Replace this line if you use other BLAS libs
echo "USE_BLAS=openblas" >>config.mk
echo "ADD_CFLAGS += -I/usr/include/openblas" >>config.mk
echo "ADD_LDFLAGS += -lopencv_core -lopencv_imgproc -lopencv_imgcodecs" >>config.mk

echo "USE_CUDA=1" >>config.mk
echo "USE_CUDA_PATH=/usr/local/cuda" >>config.mk
echo "USE_CUDNN=1" >>config.m

make -j$(nproc)

# Assuming you are in ~/mxnet directory, run below commands.
    # # Install MXNet Python package
cd python
sudo python setup.py install

**Comment by piiswrong** [comment]
you need cuda 7.5+

**Comment by chakpongchung** [comment]
Hi Eric,

I am using a toy GPU to verify the installation script so I can deploy on cluster later:

[cpchung@cam-linx-100 mxnet]$ nvidia-smi 
Tue Feb 14 15:47:29 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 361.42     Driver Version: 361.42         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 600          Off  | 0000:05:00.0      On |                  N/A |
| 30%   68C    P0    N/A /  N/A |    483MiB /  1021MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


There is a new problem:

r - build/src/operator/tensor/ordering_op_gpu.o
/bin/ld: warning: libopencv_core.so.3.2, needed by /usr/local/lib/libopencv_imgcodecs.so, may conflict with libopencv_core.so.2.4
/bin/ld: warning: libopencv_core.so.3.2, needed by /usr/local/lib/libopencv_imgcodecs.so, may conflict with libopencv_core.so.2.4
/bin/ld: warning: libopencv_core.so.3.2, needed by /usr/local/lib/libopencv_imgcodecs.so, may conflict with libopencv_core.so.2.4
/bin/ld: /tmp/ccTg1SWR.o: undefined reference to symbol '_ZN2cv6String10deallocateEv'
/bin/ld: note: '_ZN2cv6String10deallocateEv' is defined in DSO /usr/local/lib/libopencv_core.so.3.2 so try adding it to the linker command line
/usr/local/lib/libopencv_core.so.3.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status


Should I upgrade to CUDA 8.0 or 7.5

**Comment by piiswrong** [comment]
both should work.
This is a problem with opencv. Looks like you have opencv 2.4 and 3.2 installed and they conflict with each other

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
