### ISSUE TITLE
Segmentation fault (core dumped) after "import mxnet as mx "

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-mxnet#5023]
in mxnet folder,

`make -j$(nproc)`
I have the following problem:
```
cpchung:python$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Segmentation fault (core dumped)
cpchung:python$ 
```

My running environment:

Linux cam-linx-100 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/usr/local/cuda/bin/nvcc

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

3.2.0

MXNet version:\n
750af1c191a8f42640c21ef0fa5739c137d83104

Python 2.7.5

Wed Feb 15 10:46:36 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 600          Off  | 0000:05:00.0      On |                  N/A |
| 30%   67C    P0    N/A /  N/A |    384MiB /   962MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
Stepping:              7
CPU MHz:               1316.390
BogoMIPS:              7182.16
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              10240K
NUMA node0 CPU(s):     0-7

**Comment by wallinm1** [comment]
I had the same problem with segfaults during import. For me, it seems to have been caused by an incompatible version of the opencv-python library. I use anaconda and had installed opencv using `conda install opencv`, which installs the following version: `opencv: 3.1.0-np111py27_1`. I uninstalled that with `conda uninstall opencv` and installed an older version with `conda install -c menpo opencv=2.4.11` and that seems to have resolved the problem for now.

**Comment by chakpongchung** [comment]
Hi Michael,

Good catch! I built the opencv from source(3.2 as shown above). I remember first I was using 2.4 but did not work so I changed to 3.2 later. Anyway, will try again.

I will try your suggestion. I see it in mxnet installtion on centos:
    wget https://codeload.github.com/opencv/opencv/zip/2.4.13
http://mxnet.io/get_started/setup.html#prerequisites

BTW, I am not using anaconda for python. Can I just install anaconda and then export the anaconda python in ~/.bashrc? Any standard tutorial I can follow?

**Comment by wallinm1** [comment]
Hm, I can't really help with the `pdb/gdb` stuff but I can give a brief tutorial on Anaconda. 

Anaconda does not seem to be the "recommended" way of installing mxnet, but I prefer it anyway as it does not require altering the system python environment. I'm not at my development machine now, but these should roughly be the steps for installing mxnet with anaconda and GPU support:
1. Install cuda 8 and cudnn 5.1
2. Clone mxnet, set the gpu compilation flags in config.mk
3. Install dependencies with `sudo apt-get update; sudo apt-get install -y build-essential libatlas-base-dev libopencv-dev graphviz`
4. Build mxnet with `make -j$(nproc)`
5. Install Anaconda. The installer with instructions can be found [here](https://www.continuum.io/downloads). The installer adds the anaconda location to your path. After running the installer and starting a new terminal (or sourcing `.bashrc`), `which python` should point to the anaconda executable. (At any point, you can uninstall anaconda by removing the anaconda directory and removing the line that adds anaconda to your path from your `~/.bash_profile` or `~/.bash_rc`-file.)
6. Now you can choose to install mxnet in a fresh anaconda environment or your root anaconda environment.
7. If you want a fresh environment, run something like `conda create --name mxnet numpy` to create a new mxnet-environment with numpy and activate the environment with `source activate mxnet`
8. Now, if mxnet was successfully built, you should be able to run `python setup.py install` (without sudo) in mxnet's python directory. This should install mxnet for either the root anaconda environment  or the fresh mxnet environment, depending on whether you completed step 7. 
9. Finally, install opencv with `conda install -c menpo opencv=2.4.11`, and any other packages you may want. The anaconda root environment comes with quite a few scientific python packages. For a more compact option, there is also [miniconda](https://conda.io/miniconda.html).

**Comment by buaacszj** [comment]
Hi, have you solved this problem now? I also encountered this problem.

I build mxnet with warp-ctc plugin. And I get segmentation fault when run 'import mxnet'

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
