### ISSUE TITLE
I want to implement CNN_LSTM_CTC with C++ instead of Python, but an error arises out

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#5028]
I have implemented model with Python sucessfully but an error arises out in C++:

param-symbol.json ... 278523 bytes
param-0020.params ... 38367630 bytes
[15:32:30] E:\OpenSource\mxnet0.9.3\mxnet\src\nnvm\legacy_json_util.cc:153: Load
ing symbol saved by previous version v0.9.1. Attempting to upgrade...
[15:32:39] E:\OpenSource\mxnet0.9.3\mxnet\nnvm\include\dmlc/logging.h:300: [15:3
2:39] e:\opensource\mxnet0.9.3\mxnet\src\operator\./softmax_output-inl.h:307: Ch
eck failed: (*in_type)[i] == dtype (4 vs. 0) This layer requires uniform type. E
xpected 0 v.s. given 4 at label
Assertion failed: pred_hnd, file E:\OpenSource\mxnet0.9.3\mxnet\example\image-cl
assification\predict-cpp\image-classification-predict.cc, line 227
--------------------------------------------------------------------------------------------
here is my code:

`std::string json_file = "param-symbol.json";
    std::string param_file = "param-0020.params";

    BufferFile json_data(json_file);
    BufferFile param_data(param_file);

    // Parameters
    int dev_type = 1;  // 1: cpu, 2: gpu
    int dev_id = 0;  // arbitrary.
    mx_uint num_input_nodes = 10;  // 1 for feedforward
    const char* input_key[10] = {"data", "label", "forward_l0_init_c", "forward_l1_init_c" , "forward_l0_init_h", "forward_l1_init_h" ,
								"backward_l0_init_c", "backward_l1_init_c" , "backward_l0_init_h", "backward_l1_init_h" };
    const char** input_keys = input_key;

    // Image size and channels
    int width = 64;
    int height = 256;
    int channels = 1;
	int num_hidden = 256;

    const mx_uint input_shape_indptr[11] = { 0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22 };
    const mx_uint input_shape_data[22] = { 1, static_cast<mx_uint>(channels), static_cast<mx_uint>(width),static_cast<mx_uint>(height)
										 ,1, static_cast<mx_uint>(32) #32 is the sequence length
										 ,1, static_cast<mx_uint>(num_hidden)
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										 ,1, static_cast<mx_uint>(num_hidden) 
										};
    PredictorHandle pred_hnd = 0;

    if (json_data.GetLength() == 0 ||
        param_data.GetLength() == 0) {
        return -1;
    }

    // Create Predictor
    MXPredCreate((const char*)json_data.GetBuffer(),
                 (const char*)param_data.GetBuffer(),
                 static_cast<size_t>(param_data.GetLength()),
                 dev_type,
                 dev_id,
                 num_input_nodes,
                 input_keys,
                 input_shape_indptr,
                 input_shape_data,
                 &pred_hnd);
    assert(pred_hnd);`
----------------------------------------------------------------------
How can I fix it?

**Comment by Godricly** [comment]
The input data type for your softmax is wrong. What is your input type for label? it asked for float type.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
