### ISSUE TITLE
Add defaultt value for parser in train_mnist example to use inception-bn

### ISSUE THREAD

**Issue by Vogen** [apache/incubator-mxnet#5033]
I want use inception-bn in train_mnist example to test multi-node performance.  And inception-bn symbol need three parameters as follow.
`def get_symbol(num_classes, image_shape, **kwargs):`
So I add these three values passing through `parser.set_defaults` in `train_mnist.py`
```
        # data
        num_classes     = 10,
        num_examples    = 60000,
        image_shape     = '1,28,28',
```
I hope it helps

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
