### ISSUE TITLE
how to use "mxnet.symbol.sgd_update" ?

### ISSUE THREAD

**Issue by x39826** [apache/incubator-mxnet#5045]
**mx.symbol.adam_update**

<cyfunction _make_atomic_symbol_function.<locals>.creator at 0x7f1c6cd1fa10>

 **mx.symbol.adam_update(lr=1,name='as')**

[17:19:10] /home/user/jwhu2/mxnet/dmlc-core/include/dmlc/./logging.h:300: [17:19:10] src/core/symbolic.cc:295: Not enough argument to call operator adam_update

Stack trace returned 10 entries:
[bt] (0) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f1c7b710cac]
[bt] (1) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapISsS4_St4hashISsESt8equal_toISsESaISt4pairIKSsS4_EEERSE_+0x690) [0x7f1c7ce89fa0]
[bt] (2) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(NNSymbolCompose+0x1bd) [0x7f1c7ce7538d]
[bt] (3) /home/user/jwhu2/mxnet/python/mxnet/_cy2/symbol.so(+0xe2e9) [0x7f1c6cd5a2e9]
[bt] (4) /home/user/jwhu2/mxnet/python/mxnet/_cy2/symbol.so(+0x11fc1) [0x7f1c6cd5dfc1]
[bt] (5) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (6) python() [0x567d14]
[bt] (7) python(PyRun_InteractiveOneFlags+0x18c) [0x465a2d]
[bt] (8) python(PyRun_InteractiveLoopFlags+0xaa) [0x465b49]
[bt] (9) python(PyRun_AnyFileExFlags+0x37) [0x4661fe]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/cython/symbol.pyx", line 167, in symbol._make_atomic_symbol_function.creator (mxnet/cython/symbol.cpp:3751)
  File "mxnet/cython/base.pyi", line 36, in symbol.CALL (mxnet/cython/symbol.cpp:1624)
mxnet.base.MXNetError: [17:19:10] src/core/symbolic.cc:295: Not enough argument to call operator adam_update

Stack trace returned 10 entries:
[bt] (0) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f1c7b710cac]
[bt] (1) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapISsS4_St4hashISsESt8equal_toISsESaISt4pairIKSsS4_EEERSE_+0x690) [0x7f1c7ce89fa0]
[bt] (2) /home/user/jwhu2/mxnet/python/mxnet/../../lib/libmxnet.so(NNSymbolCompose+0x1bd) [0x7f1c7ce7538d]
[bt] (3) /home/user/jwhu2/mxnet/python/mxnet/_cy2/symbol.so(+0xe2e9) [0x7f1c6cd5a2e9]
[bt] (4) /home/user/jwhu2/mxnet/python/mxnet/_cy2/symbol.so(+0x11fc1) [0x7f1c6cd5dfc1]
[bt] (5) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (6) python() [0x567d14]
[bt] (7) python(PyRun_InteractiveOneFlags+0x18c) [0x465a2d]
[bt] (8) python(PyRun_InteractiveLoopFlags+0xaa) [0x465b49]
[bt] (9) python(PyRun_AnyFileExFlags+0x37) [0x4661fe]

**Comment by piiswrong** [comment]
Use optimizer, you shouldn't call those directly

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
