### ISSUE TITLE
Documentation of generated functions need to be clarified.

### ISSUE THREAD

**Issue by sighingnow** [apache/incubator-mxnet#5058]
In mxnet, we use cython (or via ctypes on windows) to generate functions for NDArray and Symbol. However, the generated documentation is misleading.

Take `mxnet.symbol.mean` as an example, [the documentation](http://mxnet.io/api/python/symbol.html#mxnet.symbol.mean) says:

~~~
mxnet.symbol.mean(*args, **kwargs):

    Parameters:	
        data (NDArray) – Source input
        axis (Shape(tuple), optional, default=()) – Empty or unsigned or tuple. The axes
            to perform the reduction.If left empty, a global reduction will be performed.
        keepdims (boolean, optional, default=False) – If true, the axis which is reduced
            is left in the result as dimension with size one.
        name (string, optional.) – Name of the resulting symbol.
    Returns:	
        symbol – The result symbol.
    Return type:	
        Symbol
~~~

Notice that the parameter `data`'s type is `NDArray`. However, when we pass a ndarray as argument to this function, **an error will be raised**:

~~~python
In [1]: a = ndarray.array([[1,2], [3,4]])

In [2]: type(a)
Out[2]: mxnet.ndarray.NDArray

In [3]: symbol.mean(a)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-37f4ed75ee14> in <module>()
----> 1 symbol.mean(a)

Anaconda\lib\site-packages\mxnet-0.9.3-py3.5.egg\mxnet\_ctypes\symbol.py in creator(*args, **kwargs)
    189         hint = func_name.lower()
    190         name = NameManager.current.get(name, hint)
--> 191         s._compose(*args, name=name, **symbol_kwargs)
    192         return s
    193

Anaconda\lib\site-packages\mxnet-0.9.3-py3.5.egg\mxnet\symbol.py in _compose(self, *args, **kwargs)
    235         for arg in args:
    236             if not isinstance(arg, Symbol):
--> 237                 raise TypeError('Compose expect `Symbol` as arguments')
    238         for val in kwargs.values():
    239             if not isinstance(val, Symbol):

TypeError: Compose expect `Symbol` as arguments
~~~

Notice that when apply `mxnet.symbol.mean` to a ndarray, a `TypeError` is raised. According to the documentation, however, the program is valid.

The root of this issue is that we have registered all functions from `MXListAllOpNames` both into `mxnet.ndarray` and `mxnet.symbol` modules when these two modules are imported, regardless what there argument types actual are!

A possible solution for this trouble is do some analysis in function `_make_ndarray_function` and `_make_atomic_symbol_function`, rather than register all operators and provide misleading documentation.

**Comment by piiswrong** [comment]
@mli

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
