### ISSUE TITLE
run image_segmentation.py error

### ISSUE THREAD

**Issue by Hjy20255** [apache/incubator-mxnet#5061]
i built the fcn-8s model successfully.But i run image_segmentation.py ,i meet an error!

check failed: x.ctx() == default_ctx Input array is in cpu(0) while binding with ctx=gpu(0). All arguments must be in global context (gpu(0)) unless group2ctx is specified for cross-device graph.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
