### ISSUE TITLE
cross-correlation (convolution) of two NDArray ?

### ISSUE THREAD

**Issue by GarrickLin** [apache/incubator-mxnet#5066]
I used the trained model get two different size of feature map from two different sized image input. And now I want to do the cross-correlation operation (or convolution) of those two feature map. But I didn't find such an API in document. How can I do that ?

**Comment by sxjscience** [comment]
You can use Convolution by setting the weight to be the other matrix.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
