### ISSUE TITLE
Execution not exiting while using distributed training

### ISSUE THREAD

**Issue by sampathchanda** [apache/incubator-mxnet#5077]
When using the launch.py script for training, the execution is not exiting after the training is done (even for the simple MNIST example). I have tried on multiple clusters, lot many times, including AWS linux machine cluster.

Can anyone please help me understand, why could this be happening.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
