### ISSUE TITLE
how can i mask a array

### ISSUE THREAD

**Issue by morusu** [apache/incubator-mxnet#5078]
## Environment info
Operating System: centos

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version: 0.9.3

the newest version gives:
element_mask is removed. Please use src*mask.reshape((mask.size, 1, 1, ..., 1)) directly as binary ops now support broadcasting.

how can i realize the function?

for example, I have a matrix A, shape(32,256) and a mask maxtrix, shape(32,)
how can i do the broadcast_mul function?

I try:
A = mx.sym.broadcast_mul(A, mx.sym.Reshape(data=mask, shape=(1, 256)))
but error

**Comment by morusu** [comment]
why remove element_mask but not giving a new example !!!

**Comment by piiswrong** [comment]
src*mask.reshape((mask.size, 1, 1, ..., 1))
This saids you should reshape((32,1))

**Comment by morusu** [comment]
thanks, i got it.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
