### ISSUE TITLE
Does mxnet amalgamated library have memory effective forward operations?

### ISSUE THREAD

**Issue by KentoNakada** [apache/incubator-mxnet#5082]
I'm trying to export mxnet according to Amalgamation manual (http://mxnet.io/how_to/smart_device.html?highlight=amalgamation) and run prediction on iOS and Android with neural net models.
The neural nets I create might have large size and memory consuming, so I want to ask following:

1. Does the amalgamated library have memory optimization mechanism in forward calculation, like re-allocating memory regions of already calculated layers' parameter variables for next layer variables ? 

2. Does it supports GPU calculation on mobile devices? (If not, is there any plans for GPU support in the future ?)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
