### ISSUE TITLE
How to set the req for a custom operator's invisible outputs?

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#5083]
I was testing a custom operator from [here](https://github.com/luoyetx/mx-lsoftmax) and the example code runs perfectly. But when I embedded it in my own network, the program just crashed and displayed a message like
`Check failed: req[lsoftmax_enum::kWeightNorm] == kWriteTo (0 vs. 1)`

I am wondering how can I set the req for this specific output to kWriteTo. Notice that lsoftmax_enum::kWeightNorm is actually an invisible output since there are three OpOutputs here and NumVisibleOutputs is set to 1.

**Comment by nicklhy** [comment]
I just changed the code from
`CHECK_EQ(req[lsoftmax_enum::kDataNorm], kWriteTo);`
to
`CHECK(req[lsoftmax_enum::kDataNorm] == kNullOp || req[lsoftmax_enum::kDataNorm] == kWriteTo);`
and the error disappeared. But I still don't know much about the difference between kNullOp and kWriteTo.

**Comment by luoyetx** [comment]
@nicklhy Could you paste your symbol definition?

**Comment by nicklhy** [comment]
The input data is a tensor containing several video frames with the shape (batch_size, frame_per_video, 3, 224, 224). Then, I use ResNet152 to extract each frame's feature and utilize a temporal fusion method to get a single feature representation for each video. Now, the tensor with the shape (batch_size, feat_dim) will be feed into your LSoftmax operator. The code is like this:

```
data = mx.sym.Variable('data') # shape = (batch_size, frame_per_video, 3, 224, 224)
label = mx.sym.Variable('label') # shape = (batch_size,)
# ...
# ResNet152 and temporal fusion
# ...
video_feat = ... # shape=(batch_size, feat_dim)
video_clf = mx.symbol.LSoftmax(data=video_feat, label=label, num_hidden=num_classes, margin=2, scale=0.99, beta=200, beta_min=0, verbose=True)
video_prob = mx.sym.SoftmaxOutput(data=frame_clf, label=label, name='video_prob')
```

I am not sure if it is all right to allow `req[lsoftmax_enum::kDataNorm]== kNullOp` in your implementation. But you can find similar code in mxnet's bn operator(line 98, 99).

**Comment by luoyetx** [comment]
It seems OK to let `req[lsoftmax_enum::kDataNorm]== kNullOp` as the graph already allocate memory for the output. But it is confusing me that `kNullOp` means don't write to that output and it seems [this line](https://github.com/dmlc/mxnet/blob/master/src/executor/graph_executor.cc#L561) in graph_executor.cc set req to be `kNullOp`. As norms data should be referenced in Backward part, don't know why it sets to `kNullOp`.

**Comment by luoyetx** [comment]
@nicklhy I'll fix the operator in my repo.

**Comment by nicklhy** [comment]
@luoyetx , I wanted to submit a pr in your repo but not sure if this change will result some new bugs. Thus I opened this issue here.
BTW, I think it will be better if you define and use the "label" inside the if(ctx.is_train){} block in order to support network inference(when "label" is not available)

**Comment by luoyetx** [comment]
@nicklhy You can pass a fake label (which is not used in inference). Or the operator needs a parameter to indicate the phase whether train or test, then `ListArguments()` function in `OperatorProperty`  can remove `label` as an input. It's a little complex.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
