### ISSUE TITLE
How to calculate the gradient of symbol? 

### ISSUE THREAD

**Issue by MasKong** [apache/incubator-mxnet#5084]
## Environment info
Operating System: Ubuntu 14.04

Package used (Python/R/Scala/Julia): Python

MXNet version: 

If you are using python package, please provide

Python version and distribution: Python 2.7

I want to calculate the gradient of symbol, what I am supposed to do?

**Comment by Godricly** [comment]
[mxnet.symbol.sum](http://mxnet.io/api/python/symbol.html#mxnet.symbol.sum)

**Comment by MasKong** [comment]
@Godricly Thank you

**Comment by MasKong** [comment]
@Godricly Could you please tell me how to calculate the gradient of a symbol?

**Comment by Godricly** [comment]
its depends on the formula of your backward calculation.

**Comment by MasKong** [comment]
@Godricly  But I need to calculate it in the process of forward. 
This is part of the code.
 cost = mx.symbol.mean(data = self.free_energy(self.var_data)) - \
               mx.symbol.mean(data=self.free_energy(h_gi)) 
#here I calculate the cost ,and in the next step,I am supposed to calculate the gradient of cost so that I can use it later, how can I achieve this?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
