### ISSUE TITLE
How can i get maximum of a matrix and use as a scalar

### ISSUE THREAD

**Issue by morusu** [apache/incubator-mxnet#5087]
I want to get a maximum of a input maxtrix , and us it as a scalar 

First, I try:

da = mx.sym.Variable('data')
max = mx.sym.max(da)
arg_shape,out_shape,aux_shape = max.infer_shape(data=(256,12))
print out_shape

I got
 [(1L,)]

when i use it in my network：

da= mx.sym.Variable('data')   
max = mx.sym.max(mx.sym.Variable('da'))

I use max[0] as the maximum i got
max cannot be use as a scalar,==>Symbol.ComposeKeyword argument name label_length not found.

I try
max = mx.nd.array(mx.sym.max(mx.sym.Variable('da')))
error too, ====> source_array must be array like object

what should i do?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
