### ISSUE TITLE
Locally connected layer (convolution layer without weights shared)

### ISSUE THREAD

**Issue by haibarasiao** [apache/incubator-mxnet#5091]
I want to build a locally connected layer(just like a convolution layer without weights shared) with mxnet, any ideas?

**Comment by haibarasiao** [comment]
this is locally connected layer with SliceChannel:
`flatten = mx.symbol.Flatten(data=data, name="flatten")
slice = mx.symbol.SliceChannel(flatten,num_outputs = 100, name="slicechannel")
groups = []
for i in range(100):
        fc = mx.symbol.FullyConnected(data=slice[i],num_hidden=1, name = "fc%d" % i)
        groups.append(fc)
concat = mx.symbol.Concat(*groups)
relu = mx.symbol.Activation(data=concat, act_type='relu' ,name = 'relu')
softmax = mx.symbol.SoftmaxOutput(data=relu,label = "softmax_label",name='softmax')
`
and when I trained with this code , it was really very very slow , slower than FullyConnected.why...

**Comment by haibarasiao** [comment]
this is locally connected layer with SliceChannel:
`
flatten = mx.symbol.Flatten(data=data, name="flatten") 
slice = mx.symbol.SliceChannel(flatten,num_outputs = 100, name="slicechannel") 
groups = [] 
for i in range(100): 
     fc = mx.symbol.FullyConnected(data=slice[i],num_hidden=1, name = "fc%d" % i) 
    groups.append(fc) 
concat = mx.symbol.Concat(*groups) 
relu = mx.symbol.Activation(data=concat, act_type='relu' ,name = 'relu') 
softmax = mx.symbol.SoftmaxOutput(data=relu,label = "softmax_label",name='softmax')
`
and when I trained with this code , it was really very very slow , slower than FullyConnected.why...

**Comment by haibarasiao** [comment]
this is locally connected layer with SliceChannel:
`flatten = mx.symbol.Flatten(data=data, name="flatten")`
`slice = mx.symbol.SliceChannel(flatten,num_outputs = 100, name="slicechannel")`
`groups = []`
`for i in range(100):`
`     fc = mx.symbol.FullyConnected(data=slice[i],num_hidden=1, name = "fc%d" % i)`
`     groups.append(fc)`
`concat = mx.symbol.Concat(*groups)`
`relu = mx.symbol.Activation(data=concat, act_type='relu' ,name = 'relu')`
`softmax = mx.symbol.SoftmaxOutput(data=relu,label = "softmax_label",name='softmax')`        
and when I trained with this code , it was really very very slow , slower than FullyConnected.why...

**Comment by eldercrow** [comment]
I am not sure, but I think you can try something like this.
```python
flatten = mx.symbol.Flatten(data=data, name="flatten")
multiplier = mx.sym.Variable(name='multiplier', shape=(100,))
relu = mx.sym.Activation(flatten*multiplier, act_type='relu', name='relu')
softmax = mx.sym.SoftmaxOutput(data=relu, label='softmax_label', name='softmax')
```

**Comment by haibarasiao** [comment]
@eldercrow I'm sorry,but It didn't work. And what I wish is a locally connected layer. something like below:
a---\
      e---\
b---/       \
               output
c---\       /
      f---/
d---/

**Comment by haibarasiao** [comment]
@eldercrow I'm sorry,but It didn't work. And what I wish is a locally connected layer,something like below:
<img width="257" alt="wx20170224-135327 2x" src="https://cloud.githubusercontent.com/assets/21122045/23292167/ab396968-fa98-11e6-8b87-c55ba9aa2213.png">

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
