### ISSUE TITLE
mxnet do not work

### ISSUE THREAD

**Issue by 91Eric** [apache/incubator-mxnet#5092]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntun16.04 lts
Compiler:

Package used (Python/R/Scala/Julia):
Python
MXNet version:
newest version 
Or if installed from source:
NO
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
2.7.13
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.when I use mxnet at beginning  ,it works well,but suddenly it does not  work at all,what confused me is that I can import it .But all modules are not be used.I have reinstall it ,but it occurs again
2.
3.

## What have you tried to solve it?

  @darxriggs 1.reinstal

2.
3.

**Comment by matt32106** [comment]
provide the commands you have run that lead to the error

paste the full error message or log files or ..., at least describe the error

**Comment by 91Eric** [comment]
I run a demo using mlp for mnist in spyder,The following is my code`
import mxnet as mx  

print('import finish!')  
#这是训练模型的主函数  
  
#定义数据迭代器  
def get_iterator():  
    train = mx.io.MNISTIter(  
        image      = "/home/eric/mxnet/example/image-classification/data/train-images-idx3-ubyte",  
        label      = "/home/eric/mxnet/example/image-classification/data/train-labels-idx1-ubyte",  
        batch_size = 128,  
        data_shape = (784, ))  
    val = mx.io.MNISTIter(    
        image       = "/home/eric/mxnet/example/image-classification/data/t10k-images-idx3-ubyte",    
        label       = "/home/eric/mxnet/example/image-classification/data/t10k-labels-idx1-ubyte",    
        batch_size = 128,  
        data_shape = (784, ))    
    return train,val  
  
#定义一个两层网络  
def get_mlp():  
    """ 
    multi-layer perceptron 
    """  
    data = mx.sym.Variable('data')  
    fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=128)  
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")  
    fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 64)  
    act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")  
    fc3  = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=10)  
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')  
    return mlp  

mlp  =get_mlp()
train,val = get_iterator()  
model = mx.model.FeedForward(  
    symbol = mlp,  
    num_epoch = 10,  
    learning_rate = .1)  
model.fit(X = train, eval_data = val)  `

when I run the code, I get the error:
Traceback (most recent call last):

  File "<ipython-input-1-c3f93f396fe0>", line 1, in <module>
    runfile('/home/eric/program/py/arg.py', wdir='/home/eric/program/py')

  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/eric/program/py/arg.py", line 70, in <module>
    mlp  =get_mlp()

  File "/home/eric/program/py/arg.py", line 61, in get_mlp
    data = mx.sym.Variable('data')

AttributeError: 'module' object has no attribute 'sym'

And then mxnet doesn't work at all.But I can import mxnet .If  I restart spyder or python several times,It woks again.I don't know the reason for that.
Thanks @matt32106

**Comment by matt32106** [comment]
I don't have a test environment with me so i cannot verify it but i think some objects may have been renamed during the life of the project and maybe mx.sym should read mx.symbol?!
Can you try to replace `data = mx.sym.Variable('data')` by `data = mx.symbol.Variable('data')`?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
