### ISSUE TITLE
The optimizer object may not properly initialized

### ISSUE THREAD

**Issue by li-weihua** [apache/incubator-mxnet#5098]
Recently I run the tutorial  [Handwritten Digit Recognition](http://mxnet.io/tutorials/python/mnist.html), 
if I change the optimizer option to a optimizer object as following
```
optimizer = mx.optimizer.SGD(learning_rate=0.1)
model = mx.model.FeedForward(
    symbol = mlp,       # network structure
    num_epoch = 10,     # number of data passes for training 
   optimizer = optimizer
)
```
I got poor result. I find that the optimizer class did not set the  mini-batch optimization parameter _rescale_grad_  to (1.0/batch_size).  The correct code is
```
optimizer = mx.optimizer.SGD(learning_rate=0.1, rescale_grad=(1.0/batch_size))
model = mx.model.FeedForward(
    symbol = mlp,       # network structure
    num_epoch = 10,     # number of data passes for training 
   optimizer = optimizer
)
```
Is this an intended design?

**Comment by piiswrong** [comment]
model is deprecated. Use module instead.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
