### ISSUE TITLE
Unknown error from using module.predict()

### ISSUE THREAD

**Issue by wangsen992** [apache/incubator-mxnet#5100]
I am working on using a simple lenet-style conv net to predict some values, similar to the kaggle-ndsb2 example. However, after I fit the model and tried to using predict(), a "key error 0" pops out and I am not sure what it means, as no information is provided. As I have successfully fitted the model, I attempted to run predict with the train data iterator and the same error appears, so I am pretty sure it is not due to the construction of the data iterator. 

Below is the error information. 

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-122-06a34d3cf6f8> in <module>()
----> 1 con_model.predict(eval_data = data_val)

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    289             if num_batch is not None and nbatch == num_batch:
    290                 break
--> 291             self.forward(eval_batch, is_train=False)
    292             pad = eval_batch.pad
    293             outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/module/module.py in forward(self, data_batch, is_train)
    450         """
    451         assert self.binded and self.params_initialized
--> 452         self._exec_group.forward(data_batch, is_train)
    453 
    454     def backward(self, out_grads=None):

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/module/executor_group.py in forward(self, data_batch, is_train)
    311 
    312         """
--> 313         _load_data(data_batch, self.data_arrays, self.data_layouts)
    314         if is_train is None:
    315             is_train = self.for_training

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/module/executor_group.py in _load_data(batch, targets, major_axis)
     41 def _load_data(batch, targets, major_axis):
     42     """Load data into sliced arrays"""
---> 43     _load_general(batch.data, targets, major_axis)
     44 
     45 

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/module/executor_group.py in _load_general(data, targets, major_axis)
     28                     end[axis] = slice_idx.stop
     29                     # pylint: disable=no-member,protected-access
---> 30                     if d_src.context == d_dst.context:
     31                         nd.crop(d_src, begin=tuple(begin), end=tuple(end), out=d_dst)
     32                     else:

/Users/Sen/anaconda/lib/python3.5/site-packages/mxnet-0.9.1-py3.5-macosx-10.6-x86_64.egg/mxnet/ndarray.py in context(self)
    462         check_call(_LIB.MXNDArrayGetContext(
    463             self.handle, ctypes.byref(dev_typeid), ctypes.byref(dev_id)))
--> 464         return Context(Context.devtype2str[dev_typeid.value], dev_id.value)
    465 
    466     @property

KeyError: 0`

## Environment info
Operating System:
MacOS, version 10.12.2

**Comment by piiswrong** [comment]
Please post a reproducible example

**Comment by chaonan99** [comment]
I encountered this problem too and this seems to happen only when I execute predict in IPython shell.

https://github.com/chaonan99/mxnet-play/blob/master/deeplearningbook/xor/config/xor.py

After training, copy and run L124 in IPython will cause the error above.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
