### ISSUE TITLE
Negative indexing as input to mx.sym.Embedding crashes Python.

### ISSUE THREAD

**Issue by rishita** [apache/incubator-mxnet#5105]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu

Package used (Python/R/Scala/Julia): Python

Or if installed from source: (Installed from source for the new RNN interface, __version__ = 0.9.4)

MXNet commit hash (`git rev-parse HEAD`): 6a0db691f156748b6091b54c0f5c3128764d1a80

If you are using python package, please provide

Python version and distribution: (2.7 and 3.4 both)

## Error Message:
Please paste the full error message, including stack trace.
No error message, the python kernel just crashes.

## Minimum reproducible example

import mxnet as mx
import numpy as np

vocab_size = 1000
embedding_size = 50

word_vecs = np.random.uniform(-1.0, 1.0, (vocab_size+1, embedding_size))
x = np.array([-1, 1, 2, 3, 4])
nd_sample_data = mx.nd.array(x)
nd_word_vecs = mx.nd.array(word_vecs)

embedding_data = mx.sym.Variable('embedding_data')
embeddings = mx.sym.Embedding(data=embedding_data, 
                              input_dim=vocab_size+1, # Add 1 for padding
                              output_dim=embedding_size,
                              name="embedding")
print(embeddings.list_arguments(), embeddings.list_outputs())
print(embeddings.infer_shape(embedding_data=nd_sample_data.shape, 
                       embedding_weight=word_vecs.shape))

"""
Output:
(['embedding_data', 'embedding_weight'], ['embedding_output'])
([(5L,), (1001L, 50L)], [(5L, 50L)], [])
"""

inputs = {"embedding_data": nd_sample_data, 
          "embedding_weight": nd_word_vecs}
executor = embeddings.bind(ctx=mx.cpu(),
                           args=inputs)
executor.forward()
============ Kernel crashes at this point ============ 

## Steps to reproduce

The same code pasted above is also available in a short jupyter notebook:
[Mxnet+Negative+Index+Embedding.ipynb.zip](https://github.com/dmlc/mxnet/files/794628/Mxnet.Negative.Index.Embedding.ipynb.zip)

## What have you tried to solve it?
There is a simple workaround I am using for now. Fix padding to not be negative indexing and instead be (word_vec.shape[0]-1). 
The fix for now can just be a more graceful failure if not support for negative indexing.

**Comment by piiswrong** [comment]
@ap-hynninen Is it easy to support negative indexing? We can also clip them to range, like the clip option here https://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html

**Comment by ap-hynninen** [comment]
I don't think there's much stopping us from using negative indexing. It may be that the only thing we need to do is shift the dst buffer in dst[index[y]]. We should be able to do this at the higher level with no changes to kernels.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
