### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'monitor'

### ISSUE THREAD

**Issue by zhenxingjian** [apache/incubator-mxnet#5110]
## Environment info
Operating System: Win7

Compiler: Python

Package used (Python):

MXNet version: example is in mxnet-0.9.3, and my mxnet version is windows binary build 20160531

Python version and distribution: Python 2.7.12

## Error Message:

example\image-classification>python train_mnist.py
INFO:root:start with arguments Namespace(batch_size=64, disp_batches=100, gpus=N
one, kv_store='device', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs=
'10', model_prefix=None, mom=0.9, monitor=0, network='mlp', num_classes=10, num_
epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_
k=0, wd=0.0001)
Traceback (most recent call last):
  File "train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "D:\Zhenxingjian\MxNet\mxnet-0.9.3\mxnet-0.9.3\example\image-classificati
on\common\fit.py", line 183, in fit
    monitor            = monitor)
TypeError: fit() got an unexpected keyword argument 'monitor'

## Steps to reproduce

1. I have changed nothing in that file. 
2. I just coded 'python train_mnist.py'
3. 

## What have you tried to solve it?

1. Before this error, I found out that some *.dll are missing. So I download them and copy them into path.
2. I can run the normal test. 
    >>> import mxnet as mx;
    >>> a = mx.nd.ones((2, 3));
    >>> print ((a*2).asnumpy());
        [[ 2.  2.  2.]
        [ 2.  2.  2.]]
3.

**Comment by BlueWinters** [comment]
new version mxnet had modified this method 
see details for [https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py](url)
`def fit(self, train_data, eval_data=None, eval_metric='acc',
            epoch_end_callback=None, batch_end_callback=None, kvstore='local',
            optimizer='sgd', optimizer_params=(('learning_rate', 0.01),),
            eval_end_callback=None,
            eval_batch_end_callback=None, initializer=Uniform(0.01),
            arg_params=None, aux_params=None, allow_missing=False,
            force_rebind=False, force_init=False, begin_epoch=0, num_epoch=None,
            validation_metric=None, monitor=None):`

**Comment by AnTruong** [comment]
@zhenxingjian: Hello zhenxingjian, did you solved this issue, I have the same problem :(

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
