### ISSUE TITLE
Any plan to implement bi-lstm-unroll in BaseRNNCell? 

### ISSUE THREAD

**Issue by deepim** [apache/incubator-mxnet#5112]
Hi,
I found bi-lstm-sort example don't make full use of LSTMCell and SequentialRNNCell. I guess it's related to the lack of bi-lstm-unroll implementation in BaseRNNCell.  Is anyone working on this? 

K.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
