### ISSUE TITLE
when i run the train_alternate.py  cv2.error  , but i test opencv indenpendenly  it runs well

### ISSUE THREAD

**Issue by zht3344** [apache/incubator-mxnet#5115]
/home/tukrin/mxnet/example/rcnn/data/VOCdevkit/VOC2007/JPEGImages/000005.jpg
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/tukrin/Downloads/opencv-3.1.0/modules/core/src/matrix.cpp, line 1879
Traceback (most recent call last):
  File "train_alternate.py", line 110, in <module>
    main()
  File "train_alternate.py", line 107, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "train_alternate.py", line 29, in alternate_train
    train_shared=False, lr=rpn_lr, lr_step=rpn_lr_step)
  File "/home/tukrin/mxnet/example/rcnn/rcnn/tools/train_rpn.py", line 42, in train_rpn
    for image_set in image_sets]
  File "/home/tukrin/mxnet/example/rcnn/rcnn/utils/load_data.py", line 10, in load_gt_roidb
    roidb = imdb.gt_roidb()
  File "/home/tukrin/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 83, in gt_roidb
    gt_roidb = [self.load_pascal_annotation(index) for index in self.image_set_index]
  File "/home/tukrin/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 101, in load_pascal_annotation
    size = cv2.imread(roi_rec['image'])
cv2.error: /home/tukrin/Downloads/opencv-3.1.0/modules/core/src/matrix.cpp:1879: error: (-213) Unknown/unsupported array type in function type

## Environment info
Operating System:Ubuntu 14.04   python 2.7

MXNet version: 0.9

**Comment by edmBernard** [comment]
I got the same error today in `example/ssd/dataset/pascal_voc.py`
my config previous : `Mxnet 0.9.3 / ubuntu 16.04 / python 2.7.9 / opencv 2.4.9.1`

I switch to : 
`Mxnet 0.9.3 / ubuntu 16.04 / python 3.5.2 / opencv 3.2`
and the error disappear.

maybe a encoding problem ? I can't test right now if adding `# encoding : utf-8` can solve the problem

**Comment by JasonBrody** [comment]
Try using python3.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by ThomasDelteil** [comment]
I tested the ssd example with latest master, I confirm it was working. Can you try again after upgrading mxnet?

**Comment by ThomasDelteil** [comment]
@indhub can you please close this issue? Thanks!
