### ISSUE TITLE
training a model in python and running in in c++ 

### ISSUE THREAD

**Issue by everwind** [apache/incubator-mxnet#5118]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by Piyush3dB** [comment]
You can train your model in python as usual and save the symbol json and weights.  This example https://github.com/dmlc/mxnet/tree/master/example/image-classification/predict-cpp shows how you can load your saved model in C++ and run inference.  This uses the amalgamation shared object to run.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
