### ISSUE TITLE
it takes several minutes to launch gpu

### ISSUE THREAD

**Issue by Cv9527** [apache/incubator-mxnet#5120]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:ubuntu 16

Compiler:i7

Package used (Python/R/Scala/Julia):Python

MXNet version:lastest

Or if installed from source: yes

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 2.7.12

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
 I test the example,
python example/image-classification/train_mnist.py --network lenet --gpus 0

it takes several minutes to launch gpu

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
when I run mtcnn demo.py(https://github.com/Seanlinx/mtcnn)
it negerates issus:

src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
time:  0.560523033142
init done 
opengl support available
 
how should I solve the problem?
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
