### ISSUE TITLE
How can I apply scalar multiplication on a specific dimension of a symbol?

### ISSUE THREAD

**Issue by applesleam** [apache/incubator-mxnet#5122]
How can I apply scalar multiplication on a specific dimension of a symbol, but without slice the tensor?

For example, I got the symbol **Conv1** with size `[128, 64, 32, 32]` and variable **c** with size `[64]`

How can I apply **c[i]** scalar multiplication with **Conv1** `[128, i, 32, 32]`?
That is, apply the variable **c** scalar multiplication on `axis=1` with **Conv1**.

I know 'full group' 1x1 group convolution is result equivalent, however it is too slow.
Thanks for reading this.

**Comment by piiswrong** [comment]
c = Reshape(c, (64, 1, 1))
out = broadcast_mul(conv1, c)

**Comment by applesleam** [comment]
Thanks for your kindness.
Sorry, I'm new to MXNET. I don't know how to apply ndarray operation to a symbol. The variable **c** here is with type (mx.sym.Variable), is trainable weights.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
