### ISSUE TITLE
image segmentation  Error

### ISSUE THREAD

**Issue by Hjy20255** [apache/incubator-mxnet#5124]
my output symbol file like this, and this file can not load by mx.model.load_checkpoint()
@tornadomeet 
@qiyuangong 
@bittnt 
{
  "nodes": [
    {
      "op": "null", 
      "name": "data", 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "conv1_1_weight", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "conv1_1_bias", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": []
    }, 
    {
      "op": "Convolution", 
      "name": "conv1_1", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": [[0, 0, 0], [1, 0, 0], [2, 0, 0]]
    }, 
...

and it is not like the offical file(FCN8s_VGG16-symbol.json):

{
  "nodes": [
    {
      "op": "null", 
      "param": {}, 
      "name": "data", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
...

there is no param and backward_source_id in my file .
could any one tell me what's going on ?

when I run the image_segmentation.py, got this error:

Traceback (most recent call last):
  File "image_segmentaion.py", line 61, in <module>
    main()
  File "image_segmentaion.py", line 52, in main
    exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
  File "/home/manager/mxnet/python/mxnet/symbol.py", line 926, in bind
    ctypes.byref(handle)))
  File "/home/manager/mxnet/python/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:44:32] src/executor/graph_executor.cc:240: Check failed: x.ctx() ==default_ctx All arguments must be in global context unless group2ctx is specified

**Comment by qiyuangong** [comment]
For your second question (i.e. #5061 ), it seems that you are trying to pass NDarray on CPU to GPU(0), which is not allowed. Use `FCN8s_VGG16-0019.params` rather than `FCN8s_VGG16-0019-cpu.params`, if you want to load it to GPU. 

If you want to load on CPU, use `FCN8s_VGG16-0019-cpu.params`, and change line 29 in `image_segmentaion.py` to `ctx = mx.cpu(0)`.

**Comment by Hjy20255** [comment]
thanks for your reply
@qiyuangong 
1.my GPU：TITAN X
2.MXNET 0.9.2
3.i use  VGG_FC_ILSVRC_16_layers-symbol.json、VGG_FC_ILSVRC_16_layers-0074.params to train with gpu
python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16
python -u fcn_xs.py --model=fcn16s --prefix=FCN32s_VGG16 --epoch=31 --init-type=fcnxs
python -u fcn_xs.py --model=fcn8s --prefix=FCN16s_VGG16 --epoch=27 --init-type=fcnxs
4.it successfully  generates  FCN8s_VGG16-0019.params and  FCN8s_VGG16-symbol.json
5. i find  "ctx=mx.gpu(0)"  in  image_segmentaion.py and fcn_xs.py.
6.when i run image_segmentaion.py.,i have  above  errors.

**Comment by qiyuangong** [comment]
According to your workflow, I have check the code, and found these lines (342-343 in model.py for saving models)
```python
    save_dict = {('arg:%s' % k) : v.as_in_context(cpu()) for k, v in arg_params.items()}
    save_dict.update({('aux:%s' % k) : v.as_in_context(cpu()) for k, v in aux_params.items()})
```
It seems that MXNet try to save (trained) model into CPU format. Then, when you tried to load it to GPU, it raised an error.

**Comment by Hjy20255** [comment]
@qiyuangong 
i change “cpu” to"gpu“in model.py .Then i run the scripts,i also have the same error.Is this a bug？

**Comment by qiyuangong** [comment]
@Hjy20255 
Do not change anything in `model.py`. Meanwhile, use model.save and model.load rather than save_checkpoint or load_checkpoint.

I think this may be an unfixed bug or a configure problem. Please provide more information about your env. (Use the issue template, if you can).

**Comment by Hjy20255** [comment]
@qiaohaijun   thankyou!
gpu_TITAX S
UBuntu16.04
MXNET 0.9.3

**Comment by Hjy20255** [comment]
@qiyuangong 
Hi, I have worked with FCN models for image segmentation in mxnet v0.7.0 .
i have a question ,how to train own dataset?
my dataset is about UAV remote sensing images, and I labeled them, Thedataset have 4 class (contains background). all images are spilted into 500*500.I gernerate own train.lst and val.lst.
i change "21" to "4" in "fcn_xs.py".
But when i run scripts" python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16" , i meet error.
File "/home/hjy/trian-0.7.0_fcn_xs/solver.py", line 66, in fit
label_shape[1]*label_shape[2]), self.ctx)
ValueError: cannot reshape array of size 750000 into shape (1,250000)
How to solve it?

**Comment by T800GHB** [comment]
@qiyuangong 
I meet same error about 
mxnet.base.MXNetError: [21:44:32] src/executor/graph_executor.cc:240: Check failed: x.ctx() ==default_ctx All arguments must be in global context unless group2ctx is specified

I have tried, if change line 29 ctx = mx.cpu(0), this could work well with FCN8s_VGG16-0019.params.
But the result is so worse.

I find out some cue.
If the model download from your website(baidu yun), there is  no problem
If the model is trained by myself, above problem occurred.

When i train this model, some other problem happened, you could see the issue #5613

**Comment by zht3344** [comment]
@Hjy20255 @T800GHB  i meet the same error ,do you solve this problem?

**Comment by T800GHB** [comment]
@zht3344 Not yet. I have read souuce code of fcn-xs, training context is gpu, but the model can't load as gpu context.

**Comment by Hjy20255** [comment]
@T800GHB  i try using MXNET 0.7.0 , it can run  successfully!

**Comment by zhengxiawu** [comment]
add this code:
`arg_params = {('arg:%s' % k) : v.as_in_context(cpu()) for k, v in arg_params.items()}`

**Comment by zhengxiawu** [comment]
add this code:
`arg_params = {('arg:%s' % k) : v.as_in_context(ctx) for k, v in arg_params.items()}`
to automatically change your context

**Comment by zhengxiawu** [comment]
for any one use fcn-xs code 
add 
`fcnxs_args = {('arg:%s' % k) : v.as_in_context(ctx) for k, v in fcnxs_args.items()}`
in line 45 for image_segmentation.py
in line 28 for fcn_xs.py

**Comment by Kaiturkey** [comment]
@zhengxiawu I meet the same bind problem,and i tried to type 
`fcnxs_args = {('arg:%s' % k) : v.as_in_context(ctx) for k, v in fcnxs_args.items()}`
after 
`load_checkpoint`
then i meet an error
`Traceback (most recent call last):
  File "image_segmentaion.py", line 68, in <module>
    main()
  File "image_segmentaion.py", line 59, in main
    exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
  File "/mxnet/python/mxnet/symbol.py", line 990, in bind
    args_handle, args = self._get_ndarray_inputs('args', args, listed_arguments, False)
  File "/mxnet/python/mxnet/symbol.py", line 832, in _get_ndarray_inputs
    raise ValueError('key `%s` is missing in `%s`' % (name, arg_key))
ValueError: key `conv1_1_weight` is missing in `args`
`
i used FCN8s-VGG16 and gpu format params , when i run fcn_xs.py added 
`fcnxs_args = {('arg:%s' % k) : v.as_in_context(ctx) for k, v in fcnxs_args.items()}`
 met the similar error, is there something i did in wrong way? thank you.

**Comment by OliverColeman** [comment]
For the pretrained FCN-8s model I could only find the parameters exported with the CPU context (FCN8s_VGG16-0019-cpu.params downloaded from the dropbox link as the baidu link seems to have disappeared). In `example/fcn-xs/image_segmentation.py`, using mxnet 0.11.0, I used this line
```
fcnxs_args = {k : v.as_in_context(ctx) for k, v in fcnxs_args.items()}
```
after the line
```
fcnxs, fcnxs_args, fcnxs_auxs = mx.model.load_checkpoint(model_previx, epoch)
```
(instead of `fcnxs_args = {('arg:%s' % k) : v.as_in_context(ctx) for k, v in fcnxs_args.items()}` suggested in a previous comment which doesn't work because it changes the parameter layer keys; perhaps there's been a change in newer versions of mxnet?).

The above line changes the context of the loaded mxnet.ndarrays representing the parameters to a GPU context.

On a side note, saving the execution context along with the parameter values and/or not allowing specifying the context to use when loading parameter values seems fairly mad..! Neither the model.load_checkpoint() or ndarray.load() functions allow specifying a new context for the loaded arrays.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
