### ISSUE TITLE
Installing MXNET in the user space

### ISSUE THREAD

**Issue by abidmalik1967** [apache/incubator-mxnet#5128]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Linux (REDHAT)
Compiler:
gcc 4.9.3
Package used (Python/R/Scala/Julia):
Python
MXNet version:
latest
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide
anaconda2/4.1.1
Python version and distribution:
2.7.11
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

[amalik@hpc1 python]$ python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to mxnet.egg-info/requires.txt
writing mxnet.egg-info/PKG-INFO
writing top-level names to mxnet.egg-info/top_level.txt
writing dependency_links to mxnet.egg-info/dependency_links.txt
reading manifest file 'mxnet.egg-info/SOURCES.txt'
writing manifest file 'mxnet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'mxnet/_cy2/.ndarray' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../include/ -I../nnvm/include -I/software/anaconda2/include/python2.7 -c mxnet/cython/ndarray.cpp -o build/temp.linux-x86_64-2.7/mxnet/cython/ndarray.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
mxnet/cython/ndarray.cpp: In function ‘PyObject* __pyx_pf_7ndarray_22_make_ndarray_function_generic_ndarray_function(PyObject*, PyObject*, PyObject*)’:
mxnet/cython/ndarray.cpp:2512:36: error: cannot declare pointer to ‘void*&’
   __pyx_t_7ndarray_NDArrayHandle &*__pyx_t_15;
                                    ^
error: command 'gcc' failed with exit status 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. I am trying to install the final building
2.
3.

**Comment by piiswrong** [comment]
should be fixed now

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
