### ISSUE TITLE
Is there any rules when use MXNET_CUDNN_AUTOTUNE_DEFAULT ?

### ISSUE THREAD

**Issue by morusu** [apache/incubator-mxnet#5132]
some times when I don't set MXNET_CUDNN_AUTOTUNE_DEFAULT=0 
It will train , but when compute the Training set's Accuracy ,it may give error like this

[10:25:56] mxnet/dmlc-core/include/dmlc/./logging.h:300:
[10:25:56] src/operator/./cudnn_convolution-inl.h:517: Check failed: cudnnFindConvolutionForwardAlgorithm(s->dnn_handle_, in_desc_, filter_desc_, conv_desc_, out_desc_, kMaxAlgos, &nalgo, fwd_algo) == CUDNN_STATUS_SUCCESS (2 vs. 0)

when I set the iteration times smaller ( from 3k to 500) , error was gone 

It's there any unstable factor in   MXNET_CUDNN_AUTOTUNE_DEFAULT ? 
just like buckets length is too long?

**Comment by piiswrong** [comment]
@ap-hynninen

**Comment by morusu** [comment]
thanks ,  if the traingset is too large,  computing the Training set's Accuracy will malloc new gpu memory , decrease the buckets length will solve this problem

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
