### ISSUE TITLE
Weird align issue when training on datasets other than mnist

### ISSUE THREAD

**Issue by stoneyang** [apache/incubator-mxnet#5146]
## Environment info
Operating System: Ubuntu 16.04
Compiler: GCC 4.9.4
Package used (Python/R/Scala/Julia): Python
MXNet commit hash (`git rev-parse HEAD`): 5e5f19a
Python version and distribution: 2.7.12 GCC 5.4.0 20160609

## Error Message:
Segmentation fault (core dumped)

## Steps to reproduce

1. compile mxnet according to the official tutorial
2. go to python directory and input `sudo python setup.py install`
3. run `python train_cifar10.py` (as stated in the title, we can sucessfully train model on mnist by running `train_mnist.py`), then the error message:

INFO:root:start with arguments Namespace(batch_size=128, benchmark=0, data_nthreads=4, data_train='data/cifar10_train.rec', data_val='data/cifar10_val.rec', disp_batches=20, dtype='float32', gpus=None, image_shape='3,28,28', kv_store='device', load_epoch=None,)
[18:05:28] src/io/iter_image_recordio.cc:221: ImageRecordIOParser: data/cifar10_train.rec, use 4 threads for decoding..
[18:05:28] /opt/share1/xxx/Engine/mxnet/dmlc-core/include/dmlc/./logging.h:300: [18:05:28] src/io/input_split_base.cc:23: Check failed: files_[i].size % align_bytes == 0 file do not align by 4 bytes

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f2a7a136f0c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc2io14InputSplitBase4InitEPNS0_10FileSystemEPKcm+0x1ad) [0x7f2a7adbec5d]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc10InputSplit6CreateEPKcjjS2_+0xe2e) [0x7f2a7ad8eefe]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io19ImageRecordIOParserIfE4InitERKSt6vectorISt4pairISsSsESaIS5_EE+0x76a) [0x7f2a7a9fceda]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io15ImageRecordIterIfE4InitERKSt6vectorISt4pairISsSsESaIS5_EE+0x8a) [0x7f2a7a9fd3ba]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io18ImageNormalizeIter4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x88) [0x7f2a7a9f9508]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io11BatchLoader4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x48f) [0x7f2a7a9cdc9f]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io14PrefetcherIter4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x1fc) [0x7f2a7a9ce5fc]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(MXDataIterCreateIter+0x2c8) [0x7f2a7ad477d8]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f2ad4936e40]

Traceback (most recent call last):
  File "train_cifar10.py", line 53, in <module>
    fit.fit(args, sym, data.get_rec_iter)
  File "/opt/share1/xxx/Engine/mxnet/example/image-classification/common/fit.py", line 105, in fit
    (train, val) = data_loader(args, kv)
  File "/opt/share1/xxx/Engine/mxnet/example/image-classification/common/data.py", line 134, in get_rec_iter
    part_index          = rank)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/io.py", line 667, in creator
    ctypes.byref(iter_handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:05:28] src/io/input_split_base.cc:23: Check failed: files_[i].size % align_bytes == 0 file do not align by 4 bytes

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f2a7a136f0c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc2io14InputSplitBase4InitEPNS0_10FileSystemEPKcm+0x1ad) [0x7f2a7adbec5d]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc10InputSplit6CreateEPKcjjS2_+0xe2e) [0x7f2a7ad8eefe]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io19ImageRecordIOParserIfE4InitERKSt6vectorISt4pairISsSsESaIS5_EE+0x76a) [0x7f2a7a9fceda]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io15ImageRecordIterIfE4InitERKSt6vectorISt4pairISsSsESaIS5_EE+0x8a) [0x7f2a7a9fd3ba]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io18ImageNormalizeIter4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x88) [0x7f2a7a9f9508]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io11BatchLoader4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x48f) [0x7f2a7a9cdc9f]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2io14PrefetcherIter4InitERKSt6vectorISt4pairISsSsESaIS4_EE+0x1fc) [0x7f2a7a9ce5fc]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(MXDataIterCreateIter+0x2c8) [0x7f2a7ad477d8]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f2ad4936e40]

**Comment by stoneyang** [comment]
Closed due to inactivity.

**Comment by kirk86** [comment]
This should not be close, it is related to the same error message that I get  #13885
