### ISSUE TITLE
Display feature maps?

### ISSUE THREAD

**Issue by No41Name** [apache/incubator-mxnet#5150]
How Can I display features maps from a loaded model and a given image?

**Comment by piiswrong** [comment]
feat = y.get_internals()['conv_output']
model = mx.mod.Module(feat, data_names=..., label_names=None, context=...)
model.bind(...)
model.set_params(...)
model.forward(mx.io.DataBatch(data=[image], label=[]), is_train=False)
print model.get_ouputs()[0].asnumpy()

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
