### ISSUE TITLE
import mxnet as mx error - cannot import name 'rmsprop_update'

### ISSUE THREAD

**Issue by kishoreabhishek** [apache/incubator-mxnet#5154]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version:0.9.4

Python version and distribution: Pyhton version - 3.6.0, Anaconda - 4.3.0

## Error Message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\mxnet-master\python\mxnet\__init__.py", line 23, in <module>
    from . import optimizer
  File "D:\mxnet-master\python\mxnet\optimizer.py", line 6, in <module>
    from .ndarray import sgd_update, sgd_mom_update, adam_update, rmsprop_update
ImportError: cannot import name 'rmsprop_update'

**Comment by edmBernard** [comment]
Have you correctly import cub submodule ?

**Comment by kishoreabhishek** [comment]
Where can I find this module and how do I import it correctly. I am following the steps mentioned in the document here - http://mxnet.io/get_started/windows_setup.html

**Comment by edmBernard** [comment]
oups, I don't use windows for long time. 
I remember that I got this error when I update my repos from mxnet 0.9.3 to mxnet 0.9.4 because I don't update the whole repos and Cub was not import. 

You use the prebuild version of mxnet or did you build from source ? 
[this](https://github.com/yajiedesign/mxnet/releases/tag/20170227) mxnet release version ?

**Comment by kishoreabhishek** [comment]
That solved my problem.
Thanks a lot for pointing me to the correct prebuild version of mxnet.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
