### ISSUE TITLE
Distributed deep learning problem on yarn.

### ISSUE THREAD

**Issue by guotong1988** [apache/incubator-mxnet#5157]
```
[ec2-user@ip-10-0-0-27 image-classification]$ ../../tools/launch.py --launcher=yarn -n $DEEPLEARNING_WORKERS_COUNT -H $DEEPLEARNING_WORKERS_PATH python train_mnist.py --gpus $(seq -s , 0 1 $(($DEEPLEARNING_WORKER_GPU_COUNT - 1))) --network lenet --kv-store dist_sync $DEEPLEARNING_WORKERS_PATH
```
It still says
```
Traceback (most recent call last):
  File "../../tools/launch.py", line 88, in <module>
    main()
  File "../../tools/launch.py", line 78, in main
    raise RuntimeError('Unknown submission cluster type %s' % args.cluster)
RuntimeError: Unknown submission cluster type yarn
```

**Comment by qiyuangong** [comment]
There are  a number of errors in your command:

(1) Please change `--launcher=yarn` to `--launcher yarn`.
(2) Remove `-H $DEEPLEARNING_WORKERS_PATH`. Note that `-H` is for ssh or mpi not yarn.
(3) If you have built jar through `build.bat`, put it in your working dir, or configure it using ` --yarn-app-dir $your working dir`.

You can find more information in `launch.py` and `yarn.py`.

**Comment by guotong1988** [comment]
Thank you @qiyuangong 
If I remove `-H` , how does mxnet find each machine?

**Comment by qiyuangong** [comment]
@guotong 
Honestly, I am not familiar with that part. To the best of my knowledge, this job is done by client or AppMaster. You can find more information in `tracker.py` and `ApplicationMaster.java`.

By the way, you should set more memory for containers (2-4GB), otherwise they will run out of memory.

**Comment by guotong1988** [comment]
![_20170307095325](https://cloud.githubusercontent.com/assets/4702353/23638334/09d7b93a-031c-11e7-8439-e24d6c5f06f7.png)

**Comment by formath** [comment]
export HADOOP_HOME='your_hadoop_home_path'

**Comment by guotong1988** [comment]
@formath Thank you. Do I need to install hadoop by myself on ec2 ?

**Comment by formath** [comment]
https://github.com/dmlc/xgboost/blob/master/doc/tutorials/aws_yarn.md  You can setup a yarn cluster on ec2.  But I have no actual operation about this.

**Comment by qiyuangong** [comment]
Personally, I suggest running distributed training with `--launch local`, which launch all nodes with subprocess, so you can debug locally. Use `export PS_VERBOSE=1` or `export PS_VERBOSE=2` to print more detail.  The only drawback is that you have to kill all processes manually when something goes wrong.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
