### ISSUE TITLE
How to generate synset.txt files?

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#5163]
We can use im2rec according to the lst file to generate rec files. But how could we generate synset.txt files? And if we use NDArrayIter, how to find the relation between the sequence of the prediction and label file?
Many thanks.

**Comment by lincolnBush** [comment]
For example, for a 2 class classification problem. The label is 0 or 1. And we get the prediction results from the network which is [0.5, 0.4], what's the possibility of getting result of 1 and what's the possibility of getting result 0.

**Comment by Piyush3dB** [comment]
@lincolnBush is this what you are after? http://data.dmlc.ml/mxnet/models/imagenet/synset.txt

The mapping from index to label in the `synset.txt` file is done outside the training/evaluation process, and the actual labels are not encoded in the mxnet symbol or data iterators as it is not required.  Does this clarify your question?

**Comment by lincolnBush** [comment]
Thank you very much for your reply. I mean how to generate this file by programme. How does this file related to the label by programme.

**Comment by Piyush3dB** [comment]
This file is supplied together with the training dataset, and is not created by any script in the MXNet repo.  You can find out about the origin of the `synset.txt` here: http://image-net.org/challenges/LSVRC/2015/browse-synsets

**Comment by statist-bhfz** [comment]
@lincolnBush 
After creating .lst and .rec files you can make your own `synset` (example in R for cifar10 dataset):

    labels <- read.table("cifar_train.lst")
    labels <- labels[!duplicated(labels$V2), ]
    class_labels <- data.frame(response = labels$V2,
                                              label = sapply(tmp, function(x) x[1]))
    class_labels <- class_labels[order(class_labels$response), ]
    write.table(class_labels, "synset.txt", row.names = FALSE, col.names = TRUE)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by rocknamx8** [comment]
I have the same problem with that. What's the mean of the id(e.g. n01440764) in front of the class name? And, how can I do to make my own synset.txt?

**Comment by YCAyca** [comment]
Hi! I was stucking with the same problem and solved with this way : creating a .lst file from my dataset. Convering the .lst file to the synset file with this python code : 

f= open("C:/Users/SAHINA/Desktop/mxnet_sample/mxnet_sample/OKNOK.lst","r")

f2 = open("C:/Users/SAHINA/Desktop/mxnet_sample/mxnet_sample/OKNOKsynset.txt", "w")

for line in f:
    line = line[line.find("\t")+1:len(line)]
    line = line[line.find("c"):len(line)-5] + " " + line[line.find("\t")+1:line.find("\\")]
    f2.write(line)
    f2.write("\n")
    
f.close()
f2.close()  

So you just need to change the file path and the characters to find and move for having the synset order. An example line from my .lst file to synset file is :
 315	0.000000	NOK\crop53_3906_2.jpg   ---> crop53_3906_2 NOK

**Comment by monkeyking** [comment]
> @lincolnBush is this what you are after? http://data.dmlc.ml/mxnet/models/imagenet/synset.txt
> 
> The mapping from index to label in the `synset.txt` file is done outside the training/evaluation process, and the actual labels are not encoded in the mxnet symbol or data iterators as it is not required. Does this clarify your question?

Hi,
The domain may changed, 
May i have the latest domain of 
     http://data.dmlc.ml/mxnet/models/imagenet/synset.txt
TY
