### ISSUE TITLE
how to  create a BucketingModule in c++

### ISSUE THREAD

**Issue by morusu** [apache/incubator-mxnet#5180]
we can create a predictor to forward in c++ like this:

 // Create Predictor
 MXPredCreate((const char*)json_data.GetBuffer(),
                          (const char*)param_data.GetBuffer(),
                          static_cast<size_t>(param_data.GetLength()),
                          dev_type,
                          dev_id,
                          num_input_nodes,
                          input_keys,
                          input_shape_indptr,
                          input_shape_data,
                          &pred_hnd);

How can I create a BucketingModule in c++ just like realizing the model in python 
model = mx.mod.BucketingModule(sym_gen             = sym_gen,
                                                     default_bucket_key  = data_val.default_bucket_key,
                                                             context             = contexts)

any one knows about it ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
