### ISSUE TITLE
error: 'class nnvm::Symbol' has no member named 'GetChildren'

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-mxnet#5182]
src/c_api/c_api_symbolic.cc:156:44: error: 'class nnvm::Symbol' has no member named 'GetChildren'

I did "get pull" in my mxnet folder and then "bash install-mxnet-ubuntu-python.sh"

environment:

Linux ubuntu1604 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/usr/local/cuda-8.0/bin/nvcc

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

cudnn:
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

pkg-config --modversion opencv:
2.4.9.1

MXNet version:

"eeeab1c4c617defe2ba5b7ba4aa8588d9a7f98db"

python -V
Python 2.7.12

Tue Feb 28 08:27:50 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |

**Comment by eric-haibin-lin** [comment]
Did you check if you have the most recent version of nnvm? Try git pull in the nnvm folder. 

On 2017年2月28日, at 05:26, cpchung <notifications@github.com> wrote:

src/c_api/c_api_symbolic.cc:156:44: error: 'class nnvm::Symbol' has no member named 'GetChildren'

I did "get pull" in my mxnet folder and then "bash install-mxnet-ubuntu-python.sh"

Linux ubuntu1604 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/usr/local/cuda-8.0/bin/nvcc

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

cudnn:
#define CUDNN_MAJOR 5
#define CUDNN_MINOR 1
#define CUDNN_PATCHLEVEL 5

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

pkg-config --modversion opencv:
2.4.9.1

MXNet version:\n
eeeab1c

python -V
Python 2.7.12

Tue Feb 28 08:26:04 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39 Driver Version: 375.39 |

**Comment by chakpongchung** [comment]
Hi Eric,

I git pull in the root folder of mxnet, anything else I should try?

**Comment by eric-haibin-lin** [comment]
try 
cd MXNet/nnvm
Git pull origin master 

On 2017年2月28日, at 17:11, cpchung <notifications@github.com> wrote:

Hi Eric,

I git pull in the root folder of mxnet, anything else I should try?

**Comment by eric-haibin-lin** [comment]
Is it resolved?

**Comment by chakpongchung** [comment]
Hi Eric,

I just git pull the whole caffe folder and compile again. The problem is now resolved. thanks!

**Comment by ikvision** [comment]
pull the nnvm folder and run install-mxnet-osx-python.sh
Problem solved
Thanks

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
