### ISSUE TITLE
Segmentation fault - abrupt crash when training

### ISSUE THREAD

**Issue by DominicKhooWM** [apache/incubator-mxnet#5188]
Hello guys,

I ran the 'train_end2end.py' module (without modification) found within the rcnn example that was provided with the mxnet package. Each time, I ran the training, the training would abruptly stop before the completion of even the first node, stating 'segmentation fault (core dumped)' and with the exact same error. I used gdb to traceback the error (provided below), but I am not familiar with c++. Could anyone kindly assist me on this error?

## Environment info
Operating System: Ubuntu 16.04 LTS

Compiler: cmake

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.93

If you are using python package, please provide

Python version and distribution: 2.7.13

## Error Message:
Thread 20 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8affd700 (LWP 15392)]
0x00007fffe5a97028 in std::_Function_handler<void (mxnet::RunContext, mxnet::engine::CallbackOnComplete), mxnet::Engine::PushSync(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, mxnet::FnProperty, int, char const*)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext&&, mxnet::engine::CallbackOnComplete&&) (__functor=..., 
    __args#0=..., __args#1=...) at /usr/include/c++/5/functional:1869
1869	      _M_invoke(const _Any_data& __functor, _ArgTypes&&... __args)

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
