### ISSUE TITLE
Where is the definition of the mx.symbol.Convolution?

### ISSUE THREAD

**Issue by ly-atdawn** [apache/incubator-mxnet#5191]
Like mx.symbol.Convolution， mx.symbol.Pooling etc, Where is the definition of those operators?  I can't find it, please help. Thanks.

**Comment by luoyetx** [comment]
I think they are register by [this function](https://github.com/dmlc/mxnet/blob/master/python/mxnet/cython/symbol.pyx#L181) or [this function](https://github.com/dmlc/mxnet/blob/master/python/mxnet/_ctypes/symbol.py#L200). Then call nnvm code [here](https://github.com/dmlc/nnvm/blob/master/src/c_api/c_api_symbolic.cc#L13-L32).

**Comment by ly-atdawn** [comment]
I don't understand clearly, Could you detial more? Thanks， Thanks.

**Comment by Godricly** [comment]
they are under src/operator/ folder.

**Comment by ly-atdawn** [comment]
Thanks.

**Comment by ysh329** [comment]
I advice you to read source code.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
