### ISSUE TITLE
the module which save BucketingModule from different buckets can load, but cann't use

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5192]
```
buckets = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150,160,170,180,190]
data_val = bucket_io.PredictBucketSentenceIter(data_vocab, label_vocab,buckets, init_states,devs)
mod = mx.mod.BucketingModule(sym_gen, default_bucket_key=data_val.default_bucket_key, context=devs)
haozl, arg_params, aux_params = mx.model.load_checkpoint(model_prefix, model_epochs)
print(mod.tojson() == haozl.tojson())
haozl.bind(data_shapes=data_val.provide_data, label_shapes=data_val.provide_label)
mod.set_params(arg_params, aux_params) 
```
**AttributeError: 'BucketingModule' object has no attribute 'tojson'**
**TypeError: bind() got an unexpected keyword argument 'data_shapes'**

**I don't want to redefine the module, I would like to use the saved model to predict. I want to separate model training and model prediction.**

**Because the model is trained with Python, I would like to model predictions using C++ or other languages. It is not easy to redefine the model with C++ or C# to call the loaded parameters.**

**Comment by Godricly** [comment]
Y do you bind haozl? I think the mod is what you should bind.

**Comment by whaozl** [comment]
but haozl is the saved module，I want to use the saved module to bind param.  I also try set haozl.set_params, but have errors as above.

**Comment by Godricly** [comment]
The parameters are the same for all buckets. The symbol you loaded is actually the one with max bucket_key. So try with the mod.

**Comment by whaozl** [comment]
@Godricly ,Thank you very much! you solve my problem.
```

**Comment by whaozl** [comment]
But, I use the module the max bucket_key to predict the DataIter() with the max bucket_key, it also has the same error:
```
data_val = bucket_io.PredictBucketSentenceIter(data_vocab, label_vocab,[190], init_states,devs)
haozl, arg_params, aux_params = mx.model.load_checkpoint(model_prefix, model_epochs)
haozl.bind(data_shapes=data_val.provide_data, label_shapes=data_val.provide_label)
haozl.set_params(arg_params, aux_params) 
```
the error is 

 haozl.bind(data_shapes=data_val.provide_data, label_shapes=data_val.provide_label)
TypeError: bind() got an unexpected keyword argument 'data_shapes'

I test the data_val.provide_data is the (1,190)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
