### ISSUE TITLE
Define a new operator

### ISSUE THREAD

**Issue by ly-atdawn** [apache/incubator-mxnet#5193]
Now, I want define a new operator. Simplicity, I use the your convolution's operator, after doingthis:

DMLC_REGISTER_PARAMETER(myconvolutionParam);
MXNET_REGISTER_OP_PROPERTY(myconvolution, myconvolutionProp)
.add_argument(......)

I executive program again, but there is a fault:
AttributeError: 'module' object has no attribute 'myconvolution'
How can I solve this problem?  Thanks.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
