### ISSUE TITLE
Speed Question for single machine and distribute training

### ISSUE THREAD

**Issue by zhongkeli** [apache/incubator-mxnet#5194]
Below is the speed output:

For one gpu, single machine:
Node[0] 06:49:12 INFO:root:Epoch[5] Batch [47]	Speed: 161.80 samples/sec	Train-Perplexity=892.936346

For distribute training, three workers
Node[0] 06:49:12 INFO:root:Epoch[5] Batch [47]	Speed: 161.80 samples/sec	Train-Perplexity=892.936346
Node[1] 06:49:12 INFO:root:Epoch[5] Batch [47]	Speed: 161.80 samples/sec	Train-Perplexity=892.936346
Node[2] 06:49:12 INFO:root:Epoch[5] Batch [47]	Speed: 161.80 samples/sec	Train-Perplexity=892.936346

Could I say that, the speed for single machine is 161.80 samples/sec, the speed for distribute training is 161.80*3 samples/sec

**Comment by zhongkeli** [comment]
Anyone can help me?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
