### ISSUE TITLE
mxnet-notebook example failed.

### ISSUE THREAD

**Issue by lincolnBush** [apache/incubator-mxnet#5196]
The example for linear regression failed with the error below, Is there anyone has idea about that? Many thanks.

https://github.com/dmlc/mxnet-notebooks/blob/master/python/tutorials/linear-regression.ipynb

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-14-60be205bd7b1> in <module>()
     32             optimizer_params={'learning_rate':0.00001, 'momentum': 0.9},
     33             num_epoch=1000,
---> 34             batch_end_callback = mx.callback.Speedometer(batch_size, 5))
     35 

mxnet/callback.pyc in __call__(self, param)
    114         if self.init:
    115             if count % self.frequent == 0:
--> 116                 speed = self.frequent * self.batch_size / (time.time() - self.tic)
    117                 if param.eval_metric is not None:
    118                     name_value = param.eval_metric.get_name_value()

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
