### ISSUE TITLE
Can not get right result using mx.io.ImageRecordIter following official tutorial

### ISSUE THREAD

**Issue by zwx8981** [apache/incubator-mxnet#5197]
I installed MXNET in Z:\mxnet, so, according to official tutorial of image io, I set MXNET_HOME as:

MXNET_HOME = 'Z:\mxnet'

After that, I download the caltech101 and unpack it under Z:\mxnet\data\caltech data\101_ObjectCategories

Then I run two commands following tutorial as :
os.system('python %s/tools/im2rec.py --list=1 --recursive=1 --shuffle=1 --test-ratio=0.2 data/caltech data/101_ObjectCategories'%MXNET_HOME)

os.system("python %s/tools/im2rec.py --num-thread=4 --pass-through=1 data/caltech data/101_ObjectCategories"%MXNET_HOME)

However, the generated caltech.lst and caltech.rec are two empty files. Ignoring this strange thing, I continue to run the last command as:

data_iter = mx.io.ImageRecordIter(
    path_imgrec="./data/caltech.rec", # the target record file
    data_shape=(3, 227, 227), # output data shape. An 227x227 region will be cropped from the original image.
    batch_size=4, # number of samples per batch
    resize=256 # resize the shorter edge to 256 before cropping
    # ... you can add more augumentation options here. use help(mx.io.ImageRecordIter) to see all possible choices
    )
data_iter.reset()
batch = data_iter.next()
data = batch.data[0]
for i in range(4):
    plt.subplot(1,4,i+1)
    plt.imshow(data[i].asnumpy().astype(np.uint8).transpose((1,2,0)))
plt.show()

Finally, I got an error which shows that:
.
Cannot find any files that matches the URI patternz ./data/caltech.rec. 

What's the problem?

## Environment info
Operating System:
Windows 10 64-bit

Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.3

Python version and distribution:
2.7

**Comment by saicoco** [comment]
### generate lst  

To generate list ,you can try following command:
```
python --recursive=True --list=True prefix root
```  
the args need `prefix` and `root`, `prefix` is where you wanna generate .lst file, `root` is your path of your dataset  

### generate rec  

After you generate lst file successfully, you can run the command to generate rec:  

```
usage: im2rec.py [-h] [--list LIST] [--exts EXTS] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive RECURSIVE] [--shuffle SHUFFLE]
                 [--pass-through PASS_THROUGH] [--resize RESIZE]
                 [--center-crop CENTER_CROP] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label PACK_LABEL]
                 prefix root
```  

there are also `prefix` and `root`, they are same as above I talk

**Comment by zwx8981** [comment]
@saicoco Thank you for your explanation! Now I get correct .lst and .rec files, but when I run the mx.io.ImageRecordIter function, an unknown error happens and python.exe stop working....

**Comment by saicoco** [comment]
Are you compile mxnet with `USE_OPENCV=1` in file config.mk? If `USE_OPENCV=0` , `mx.io.ImageRecordIter` will raise error about opencv

**Comment by zwx8981** [comment]
@saicoco  I use pre-built version from yajiedesign.

**Comment by saicoco** [comment]
@zwx8981 Can you paste the error here?

**Comment by zwx8981** [comment]
@saicoco I can't see the detailed error because when I run this command the Ipython stop working and closed...

**Comment by saicoco** [comment]
It's alright, you can read it detail when you run it next time in cmd, the error when you run program in ipython will be output in cmd, I guss the error related to opencv

**Comment by zwx8981** [comment]
@saicoco  I think it's better to compile a package from scratch myself. Thank you anyway.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
