### ISSUE TITLE
in mxnet.io/api/python/module.hml, how to use the loaded module?

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5200]
in [mxnet.io/api/python/module](http://mxnet.io/api/python/module.html), I want to use sym.set_params(arg_params, aux_params), because i do not want to use the previously defined model to directly predict, want to use the loaded sym to predict. But it has error in #5192 

**sym** is the  the loaded module.
**mod** is the defined model by code 

To load the saved module parameters, call the load_checkpoint function:
```
    sym, arg_params, aux_params=mx.model.load_checkpoint(model_prefix, n_epoch_load)

    # assign parameters
    mod.set_params(arg_params, aux_params)
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
