### ISSUE TITLE
CMake Warning that OpenBLAS_HOME not used & Cannot open include file: 'cblas.h': No such file or directory

### ISSUE THREAD

**Issue by lxn2** [apache/incubator-mxnet#5202]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

I have not easily been able to install MXNet on Windows.

## Environment info
Operating System:
Windows Server 2016

Compiler:
Visual Studio 2014

Package used (Python/R/Scala/Julia):

Or if installed from source:
MXNet commit hash (`git rev-parse HEAD`):
1fd940e944b88249f0b3ae926df4d1061a89ec9b

## Error Message:
Please paste the full error message, including stack trace.

(mxnet-vc14) C:\Users\Administrator\mxnet>cmake -Wno-dev -DUSE_CUDA=0 -DUSE_CUDNN=0 -DBLAS="Open" -DOpenBLAS_HOME="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\" -DOpenBLAS_INCLUDE_DIR="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\\\include\\" -DOpenBLAS_LIB="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\\\lib\\" -DUSE_PROFILER=1 -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Checking if C linker supports --verbose - yes
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Checking if CXX linker supports --verbose
-- Checking if CXX linker supports --verbose - yes
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_MODULE_PATH C:/Users/Administrator/mxnet/cmake/Modules
-- OpenBLAS_INCLUDE_DIR SYSTEM
-- OpenCV Disabled
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: /openmp
-- Found PythonInterp: C:/ProgramData/Miniconda2/envs/mxnet-vc14/python.exe (found version "2.7.10")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OpenBLAS_HOME

msbuild build\mxnet.sln /t:Build /m
.
.
 6>c:\users\administrator\mxnet\mshadow\mshadow\./base.h(136): fatal error C
       1083: Cannot open include file: 'cblas.h': No such file or directory (com
       piling source file C:\Users\Administrator\mxnet\src\c_api\c_api_ndarray.c
       c) [C:\Users\Administrator\mxnet\mxnet.vcxproj]
     6>c:\users\administrator\mxnet\mshadow\mshadow\./base.h(136): fatal error C
       1083: Cannot open include file: 'cblas.h': No such file or directory (com
       piling source file C:\Users\Administrator\mxnet\src\c_api\c_api_executor.
       cc) [C:\Users\Administrator\mxnet\mxnet.vcxproj]
.
.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Followed https://github.com/lxn2/mxnet/blob/jenkins/setup-utils/install-mxnet-windows-python.bat for the most part
2. Set use_opencv off in CMakeList.txt: mxnet_option(USE_OPENCV  "Build with OpenCV support" OFF)
3. Run CMake: cmake -Wno-dev -DUSE_CUDA=0 -DUSE_CUDNN=0 -DBLAS="Open" -DOpenBLAS_HOME="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\" -DOpenBLAS_INCLUDE_DIR="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\\\include\\" -DOpenBLAS_LIB="C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\\\lib\\" -DUSE_PROFILER=1 -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
4. Run build: msbuild build\mxnet.sln /t:Build /m

## What have you tried to solve it?

1. Explicitly add include directory in CMakeLists.txt: 
include_directories("C:/ProgramData/Miniconda/envs/mxnet-vc14/Library/include")

**Comment by lxn2** [comment]
@howard0su and @yajiedesign

**Comment by yajiedesign** [comment]
is cblas.h in "C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\\include\"?
and try "C:/ProgramData/Miniconda2/envs/mxnet-vc14/Library/include/"

**Comment by lxn2** [comment]
Yes it is
```
(mxnet-vc14) C:\Users\Administrator\mxnet>dir C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\include
 Volume in drive C is Windows
 Volume Serial Number is BCBD-819C

 Directory of C:\ProgramData\Miniconda2\envs\mxnet-vc14\Library\include

02/24/2017  12:13 AM    <DIR>          .
02/24/2017  12:13 AM    <DIR>          ..
02/24/2017  12:13 AM    <DIR>          %
10/28/2015  08:06 PM            45,648 cblas.h
10/28/2015  08:06 PM            47,356 f77blas.h
04/15/2016  08:23 PM             1,553 jconfig.h
04/15/2016  08:23 PM            14,580 jerror.h
04/15/2016  08:23 PM            14,925 jmorecfg.h
04/15/2016  08:23 PM            17,284 jpegint.h
04/15/2016  08:23 PM            49,287 jpeglib.h
10/28/2015  08:06 PM         1,068,261 lapacke.h
10/28/2015  08:06 PM             4,470 lapacke_config.h
10/28/2015  08:06 PM               474 lapacke_mangling.h
10/28/2015  08:06 PM            33,047 lapacke_utils.h
02/24/2017  12:11 AM    <DIR>          libpng16
02/24/2017  12:00 AM             4,849 openblas_config.h
10/28/2015  08:06 PM             4,706 openblas_config.h.orig
02/24/2017  12:11 AM    <DIR>          opencv
02/24/2017  12:11 AM    <DIR>          opencv2
01/05/2017  01:52 PM           143,251 png.h
01/05/2017  01:52 PM            22,842 pngconf.h
01/13/2017  01:49 PM             7,385 pnglibconf.h
08/28/2015  10:16 PM            11,379 t4.h
08/28/2015  10:16 PM            35,987 tiff.h
08/28/2015  10:16 PM             3,902 tiffconf.h
08/28/2015  10:16 PM             3,902 tiffconf.vc.h
08/28/2015  10:16 PM             3,346 tiffconf.wince.h
08/28/2015  10:16 PM            23,003 tiffio.h
08/28/2015  10:16 PM            18,110 tiffiop.h
09/12/2015  07:36 PM               410 tiffvers.h
11/02/2016  10:01 AM             3,282 tif_config.h
11/02/2016  10:01 AM             3,282 tif_config.vc.h
08/28/2015  10:16 PM             1,852 tif_config.wince.h
08/28/2015  10:16 PM            10,918 tif_dir.h
08/28/2015  10:16 PM            16,183 tif_fax3.h
08/28/2015  10:16 PM             2,870 tif_predict.h
08/28/2015  10:16 PM             5,635 uvcode.h
01/23/2017  02:09 PM            16,885 zconf.h
01/15/2017  05:29 PM            96,239 zlib.h
              33 File(s)      1,737,103 bytes
               6 Dir(s)  12,114,448,384 bytes free
```

**With Forward Slashes**
```
(mxnet-vc14) C:\Users\Administrator\mxnet>cmake -Wno-dev -DUSE_CUDA=0 -DUSE_CUDNN=0 -DBLAS="Open" -DOpenBLAS_HOME="C:/ProgramData/Miniconda2/envs/mxnet-vc14/Library/" -DOpenBLAS_INCLUDE_DIR="C:/ProgramData/Miniconda2/envs/mxnet-vc14/Library/include/" -DOpenBLAS_LIB="C:/ProgramData/Miniconda2/envs/mxnet-vc14/Library/lib/libopenblas.lib" -DUSE_PROFILER=1 -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Checking if C linker supports --verbose - yes
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Checking if CXX linker supports --verbose
-- Checking if CXX linker supports --verbose - yes
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_MODULE_PATH C:/Users/Administrator/mxnet/cmake/Modules
-- OpenBLAS_INCLUDE_DIR SYSTEM C:/ProgramData/Miniconda2/envs/mxnet-vc14/Library/include/
-- OpenCV Disabled
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: /openmp
-- Found PythonInterp: C:/ProgramData/Miniconda2/envs/mxnet-vc14/python.exe (found version "2.7.10")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
    OpenBLAS_HOME
```
And msbuild still has "cblas.h: no such file or directory" error.

**Comment by lxn2** [comment]
@yajiedesign @howard0su and suggestions to move forward? Are you able to repro this?

**Comment by yajiedesign** [comment]
I am confused...
There seems to be no problem...
can you try use cmake_gui?
and try move include file to another driver.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
