### ISSUE TITLE
Backward shape inference

### ISSUE THREAD

**Issue by Piyush3dB** [apache/incubator-mxnet#5206]
@piiswrong, @tqchen,  currently the C API supports forward shape inference using the function `MXSymbolInferShape`.  

Does the C API provide a similar function for backward shape inference to deduce the shapes of the gradient tensors when given the gradient at the output of the computation graph?  

If not, does the NNVM support this and how much work do you think it would take to expose a C API for this?

**Comment by formath** [comment]
In backward phase, shape will be the same as that of the forward pass.  So, what is the benefit of adding backward shape inference?

**Comment by Piyush3dB** [comment]
@formath say for example I don't know my input argument shapes for an arbitrary graph (doesn't have to be DNN graph), then one way for me to figure them out is to use backward shape inference.  I'm still looking at the NNVM code, but do you know if such  functionality is already there?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
