### ISSUE TITLE
Distributed training, worker server or scheduler lose control cmd

### ISSUE THREAD

**Issue by qzfnihao** [apache/incubator-mxnet#5219]
I use  dist_sync training on 2 machines.  ./launch -n 2 -H host my_cmd. 
I found control message lost when training, and the worker blocked on cond_wait. 
I tried ps-lite tests, and run ./local n n test_connection or test_simple_app or test_kv_app, and they all run well; but when build libmxnet.so use USE_DIST_KVSTORE = 1, and build my program use libmxnet.so,  my program may lost control signal. 
my program is like this:
if dist,  kv = new kvstr('dist_sync')
if !worker, kv->RunServer();                  -------------1

in training stage:
if batch_num % 50 == 0,  print output of net, here, i use NDArray::WaitAll() ----------2

the signal lost may occured in 1 or 2 ablove;  if at 1,  just like scheduler could not receive all AddNode cmd from workers and servers. when gdb, all process stop at sleeping; and recv_byte_ is 0 or 100 or 150, never full, just because it not receive workers and servers AddNode cmds.  

when worker stopped at 2,  it always stop at cond_wait function in gdb.  It seems that it have not receive Barrier cmd from scheduler. 

I tried PS_RESEND = 1 and PS_RESEND_TIMEOUT=100000, and the scheduler process coredump because it send Barrier cmd with request=false to worker more than 10 times. 

I tried modify Makefile not use -O3, just use -O2 or -O1, but the question still exist. 

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by formath** [comment]
I have also encountered message lost many times when training on yarn. Have you solved this problem?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
