### ISSUE TITLE
Issue in running mxnet on windows

### ISSUE THREAD

**Issue by MohammadAvrahem** [apache/incubator-mxnet#5222]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10 

Compiler: 64 bit

Package used (Python/R/Scala/Julia): Python 

MXNet version: 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): latest verion

If you are using python package, please provide

Python version and distribution: python 2.7.13

## Error Message:
Please paste the full error message, including stack trace.

C:\Python27\python.exe C:/Users/Avrahim/PycharmProjects/CDL/cdl.py
Traceback (most recent call last):
  File "C:/Users/Avrahim/PycharmProjects/CDL/cdl.py", line 2, in <module>
    import mxnet as mx
  File "C:\Python27\lib\site-packages\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Python27\lib\site-packages\mxnet\base.py", line 45, in <module>
    _LIB = _load_lib()
  File "C:\Python27\lib\site-packages\mxnet\base.py", line 36, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "C:\Python27\lib\site-packages\mxnet\libinfo.py", line 37, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
C:\Python27\lib\site-packages\mxnet\libmxnet.dll
C:\Python27\lib\site-packages\mxnet\../../lib/libmxnet.dll
C:\Python27\lib\site-packages\mxnet\../../build/Release/libmxnet.dll
C:\Python27\lib\site-packages\mxnet\../../build\libmxnet.dll
C:\Python27\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
C:\Python27\lib\site-packages\mxnet\../../windows/x64\Release\libmxnet.dll

Process finished with exit code 1

**Comment by sxjscience** [comment]
Have you successfully compiled the package?

**Comment by MohammadAvrahem** [comment]
Yeah, of course, but i did not get mxnet.dll, instead i get libmxnet.dll (about 1.5 gb) with successful building.

**Comment by sxjscience** [comment]
I think one solution is to put the compiled dll to the listed candidate directories. Also, you may try install the package via `python setup.py develop --user`.

**Comment by MohammadAvrahem** [comment]
sxjscience,

 I need the detailed instructions of how to install mxnet on Windows need to rewritten. Because the building of mxnet did not give mxnet.dll as it is mentioned, but it gives libmxnet.dll (about 1.5 gb).

http://mxnet.io/get_started/windows_setup.html#install-the-mxnet-package-for-python

**Comment by tornadomeet** [comment]
@MohammadAvrahem  a pr for that is welcome~

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
