### ISSUE TITLE
include/dmlc/logging.h:235: [00:59:21] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "model/det1-symbol.json"

### ISSUE THREAD

**Issue by IvyGongoogle** [apache/incubator-mxnet#5224]
hello, Now I use mxnet and face detection model 'mtcnn' to inference an image, but it shows error: `include/dmlc/logging.h:235: [00:38:08] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "model/det1-symbol.json"`
I doubt that whether it is caused by mxnet or not.
Can you give me some advices how to solve this problem?

**Comment by ysh329** [comment]
same problem. @piiswrong

**Comment by novioleo** [comment]
same problem.@piiswrong

**Comment by ysh329** [comment]
@novioleo Okay, thanks my dear friend and stupid me. :rofl:

**Comment by novioleo** [comment]
@ysh329 i know it's too late~lol

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
