### ISSUE TITLE
A wrong comment In /python/mxnet/io.py ?

### ISSUE THREAD

**Issue by maxpy** [apache/incubator-mxnet#5225]
In /python/mxnet/io.py ,  DataIter class
the comment is:
`

    def getdata(self):
        """Get data of current batch.
        Returns
        -------
        data : NDArray
            The data of current batch.
        """
        pass

    def getlabel(self):
        """Get label of current batch.
        Returns
        -------
        label : NDArray
            The label of current batch.
        """
        pass 
`

When I try to write a custom DataIter, I return a NDArray object in these function 
then a ` Shape inconsistent` error will occur., like:  
`MXNetError: Shape inconsistent, Provided=(100,600), inferred shape=(100,)`
it spend my whole afternoon to found the solution:
`return [NDArray]  # a list of NDArray ;   poor me `

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
