### ISSUE TITLE
How to set a constant array in a symbol ?  ndarray seems not to work. mxnet version is 0.9.4.

### ISSUE THREAD

**Issue by DW9363** [apache/incubator-mxnet#5239]
a simple sym code like this:
import mxnet as mx

data = mx.sym.Variable(name='data', shape=(4,3,20,20))
b_sub = mx.sym.broadcast_sub(lhs=data, rhs=mx.nd.array([1,2,3]).reshape((1,3,1,1)))
arg_shapes,out_shapes,aux_shapes = b_sub.infer_shape()
print (type(out_shapes),type(arg_shapes),type(aux_shapes))

it can run, but all shapes are NoneType

but when i change b_sub to 
b_sub = mx.sym.broadcast_sub(lhs=data, rhs=mx.sym.ones((1,3,1,1)))
everything works fine.

Is this normal ?  @tqchen

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
