### ISSUE TITLE
in mxnet0.9.4,I also find a problem, the model load is so so so so so slow, the train is also so so so slow. the mxnet0.9.3 is faster. I test my lstm python.

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5249]
window 10
python27
mxnet0.9.3
mxnet0.9.4

**Comment by tornadomeet** [comment]
can you give a reproduceable example?

**Comment by whaozl** [comment]
This speed is so slow in mxnet0.9.4, and it has not any errors. but finally it successfully load the module.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
