### ISSUE TITLE
I think USE_INTEL_PATH should be removed (config.mk) or explained more.

### ISSUE THREAD

**Issue by mcxkarakoc** [apache/incubator-mxnet#5260]
If `USE_INTEL_PATH` is set to the correct path of full MKL version, it prevents MxNet from compiling when `USE_MKL2017 = 1` and `USE_BLAS = mkl` (since the full MKL hides MKLML). Unless the full MKL have some advantages (for MxNet) over (or plus) MKLML, I think all of the referrals to the full MKL should be removed. Otherwise, they confuse both mind and compiler :)    

In addition, I think the expression of "`# For USE_BLAS!=mkl only`" was forgotten since `MKLML_ROOT` and `USE_BLAS = mkl` works well anymore.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
