### ISSUE TITLE
its convergency is so poor though the same optimizer when i use MKL2017

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#5264]

**Comment by janelu9** [comment]
at the same num_pass ,though it's faster but it is not convergent when i use MKL2017

**Comment by sxjscience** [comment]
@janelu9 Have you turned on the MKL2017 experimental flag? I cannot get my network converge after turning this flag on.

**Comment by janelu9** [comment]
@sxjscience I just turned on the MKL2017. it couldn't be convergence ,either

**Comment by sxjscience** [comment]
Close it now. Feel free to reopen it if the problem still occurs in the latest version.
