### ISSUE TITLE
mod.predict gives more columns than expected

### ISSUE THREAD

**Issue by kishoreabhishek** [apache/incubator-mxnet#5266]
I am using MXNet on IRIS dataset which has 4 features and it classifies the flowers as -'setosa', 'versicolor', 'virginica'. My training data has 89 rows. My label data is a row vector of 89 columns. I encoded the flower names into number -0,1,2 as it seems - mx.io.NDArrayIter does not accept numpy ndarray with string values.  Then I tried to predict using - **re = mod.predict(test_iter)**.  
I get a result which has the shape 14 * 10. 
Why am I getting 10 columns when I have only 3 labels and how do I map these results to my labels. The result of predict is shown below:

[[ 0.11760861  0.12082944  0.1207106   0.09154381  0.09155304  0.09155869
   0.09154817  0.09155204  0.09154914  0.09154641]
 [ 0.1176083   0.12082954  0.12071151  0.09154379  0.09155323  0.09155825
   0.0915481   0.09155164  0.09154923  0.09154641]
 [ 0.11760829  0.1208293   0.12071083  0.09154385  0.09155313  0.09155875
   0.09154838  0.09155186  0.09154932  0.09154625]
 [ 0.11760861  0.12082901  0.12071037  0.09154388  0.09155303  0.09155875
   0.09154829  0.09155209  0.09154959  0.09154641]
 [ 0.11760896  0.12082863  0.12070955  0.09154405  0.09155299  0.09155875
   0.09154839  0.09155225  0.09154996  0.09154646]
 [ 0.1176089   0.1208287   0.1207095   0.09154407  0.09155297  0.09155882
   0.09154844  0.09155232  0.09154989  0.0915464 ]
 [ 0.11760896  0.12082864  0.12070941  0.09154408  0.09155297  0.09155882
   0.09154844  0.09155234  0.09154993  0.09154642]
 [ 0.1176088   0.12082874  0.12070983  0.09154399  0.09155302  0.09155872
   0.09154837  0.09155215  0.09154984  0.09154641]
 [ 0.11760852  0.12082904  0.12071032  0.09154394  0.09155304  0.09155876
   0.09154835  0.09155209  0.09154959  0.09154631]
 [ 0.11760963  0.12082832  0.12070873  0.09154428  0.09155257  0.09155893
   0.09154856  0.09155177  0.09155051  0.09154671]
 [ 0.11760966  0.12082829  0.12070868  0.09154429  0.09155258  0.09155892
   0.09154858  0.0915518   0.09155052  0.09154672]
 [ 0.11760949  0.1208282   0.12070852  0.09154446  0.09155259  0.09155893
   0.09154854  0.09155205  0.0915506   0.09154666]
 [ 0.11760952  0.12082817  0.12070853  0.0915444   0.09155261  0.09155891
   0.09154853  0.09155206  0.09155057  0.09154668]
 [ 0.1176096   0.1208283   0.12070892  0.09154423  0.09155267  0.09155882
   0.09154859  0.09155172  0.09155044  0.09154676]]

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
