### ISSUE TITLE
Unknown initialization pattern when seting the initializer for a specific variable.

### ISSUE THREAD

**Issue by KangHsi** [apache/incubator-mxnet#5271]
I tried to create a forgetting gate in my network, thus I created a symbol:

```
fgt = mx.sym.Variable(name=name + '_fgt', shape=[128, num_filter, w, h], wd_mult=0.0002,
                                init=mx.initializer.Xavier(rnd_type='gaussian', factor_type="avg", magnitude=2))
```

However I got the error as below:

ValueError: Unknown initialization pattern for unit13_fgt. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern

------------------------------------------------
I don't really understand the error information, and try to solve this by changing the initializer, but it doesn't work.

**Comment by lilhope** [comment]
mxnet is not as,same as tensorflow,The`Variable` is different from tensorflow's Variable(which often used as the weight or bias in a layer),mxnet's`Variable` often used for network's input. After you create your symbol,you can list all parameters' name use `symbol.list_arguments()`,create a dict,for example,`arg_params`,initialize your by this way:`arg_params['conv1_weights']=mx.random.normal(0,1,shape=shape)`,then create your module use those parameters.

**Comment by KangHsi** [comment]
@lilhope 
Thanks. It helps me understanding this, but 
If the `Variable` in MXNet doesn't mean learnable weights, how can I just create learnable weights as symbol(not a basic NN symbol) with customized attr.

**Comment by sxjscience** [comment]
`mx.sym.Variable` can be used to construct the model parameter.  @KangHsi Could you give us a reproducible example?

**Comment by KangHsi** [comment]
@sxjscience 
Problem actually  has been solved(I'm not sure, but no exception arised) after I follow @lilhope suggestion and try this in my net symbol:
```
fgt = mx.sym.Variable(name=name + '_fgt', shape=[128, num_filter, w, h], wd_mult=0.0002)
arg_params=fgt.list_arguments()
arg_params[0]=mx.initializer.Xavier(rnd_type='gaussian', factor_type="avg", magnitude=2)
```
I'll close this issue soon. By the way, I wonder if this is a common way to create customized learnable weights in MXNet?

**Comment by sxjscience** [comment]
@KangHsi The `fgt = mx.sym.Variable(name=name + '_fgt', shape=[128, num_filter, w, h], wd_mult=0.0002,
                                init=mx.initializer.Xavier(rnd_type='gaussian', factor_type="avg", magnitude=2))` way should be supported by the latest version of MXNet. I feel that there may be some bugs if it raises an error.

**Comment by lilhope** [comment]
@KangHsi ,I often use this code:
```
>>> import mxnet as mx
>>> 
>>> a = mx.sym.Variable('data')
>>> b = mx.sym.FullyConnected(data=a,name='fc1',num_hidden=100)
>>> data_shape = {'data':(256,64)}
>>> arg_shape,_,_ = b.infer_shape(**data_shape)
>>> arg_shape
[(256L, 64L), (100L, 64L), (100L,)]
>>> b.list_arguments()
['data', 'fc1_weight', 'fc1_bias']
```
you can get a map of all variables.Then create the dict,initialize all parameters as you want.
You don't need to create all learnable parameters by yourself,It will be create automatically.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by tiger-JK** [comment]
The variable name should be end up with '_weight'
