### ISSUE TITLE
In mxnet or offical mxnet imagenet pretrained model, When processing images,the data layout is batchSize x channel x width x height or batchSize x channel x height xwidth ？ 

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5274]
```
#cv2.imread returns [height, width, channel] in BGR
cv2img = cv2.cvtColor(cv2.imread(finename), cv2.COLOR_BGR2RGB)
#http://mxnet.io/tutorials/python/predict_imagenet.html
cv2img.shape
cv2img = np.swapaxes(cv2img, 0, 2)
cv2img = np.swapaxes(cv2img, 1, 2)#this return (channel,height,width)
```
in [tutorials-predict_imagenet](http://mxnet.io/tutorials/python/predict_imagenet.html) I see the predict imagenet the pre-trained model forward image_shap is as above(channel,height,width).

but I know, in the mxnet pre-trained model for example [vgg-imagenet-pretrained-model](http://data.mxnet.io/models/imagenet/vgg/) and [](), the image-shape is (batch_size,channel,width,height). but this is 

and, in the [offical mxnet readme](https://github.com/dmlc/mxnet/blob/33930c6b89314739f4f39c3fd642db5e024b8dc2/matlab/README.md), When processing images, MXNet assumes the data layout is
batchSize x channel x width x height.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
