### ISSUE TITLE
Why no mxnet.symbol.relu (or sigmoid)?

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#5275]
I've noticed that in mxnet.symbol we have defined:
* mxnet.symbol.tanh
* mnet.symbol.LeakyReLU
However, we don't have mxnet.symbol.ReLU or mxnet.symbol.sigmoid defined. These functions are defined but only within the 

I think this is bad for a couple reasons:
* This appears disorganized. Like functions should be grouped in like folders.
* This makes our library overly married to neural network notation. We could imagine other times when someone might want to access the sigmoid or hinge functions but wouldn't think of them as activation functions.

I think both ReLU (better to spell "relu") and sigmoid should both be available in mxnet.symbol

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
Activation(act_type='relu')

**Comment by mli** [comment]
per discussion with zack, we should add make these activation functions individual operators, such as `sym.relu` and `sym.sigmod`.

besides, we should also add lower case alias to these neural network functions, this is consistent with google python style.

**Comment by ZihengJiang** [comment]
I'm in favor with the idea to add lower case alias. It will unite the style of operators

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
