### ISSUE TITLE
How to use sequential module for a frozen part and trainable part.

### ISSUE THREAD

**Issue by lovedl** [apache/incubator-mxnet#5279]
Hi, I am new to Mxnet, and I want to use sequential module for this specific task. Suppose I have a feature extraction network, which is fixed and takes no gradient. In other words, I use this as "grad_req='null' and is_train=False". The second network is trainable with several layers. I saw there is a argument "fixed_param_names". Does it mean the parameters only get lr=0? If yes, it will be not very sufficient, because there is no need for the frozen part to calculate gradients and so on. Any suggestions? really appreciate it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
