### ISSUE TITLE
[API Discuss] Support for partial execution

### ISSUE THREAD

**Issue by ZihengJiang** [apache/incubator-mxnet#5282]
```
import mxnet as mx

a = mx.sym.var('a')
b = mx.sym.var('b')
c = 2*a+b
d = mx.sym.var('d')
e = c+d
executor = e.bind(mx.cpu(), {
                   'c': mx.nd.array([1,2]),
                   'd':mx.nd.array([4,5])
                   })

res = executor.forward()
print(res[0].asnumpy())
```

As you can see in the code snippet above, `c` and `d` is enough to calculate the result of e, which means we only need to execute a part of graph. But this usage is not supported in MXNet yet, IMHO, an API for partial execution (maybe not like above) would be necessary, also helpful (Image that you want to debug a part of model).

**Comment by piiswrong** [comment]
This is not possible because e could be optimized out unless you group it as an additional output

debug can be done with monitor

**Comment by ZihengJiang** [comment]
Could you explain why e could be optimized out? Since it is the only output.

BTW, I just want to look up the usage of monitor, but it looks like it is missing now on the official API document.

**Comment by piiswrong** [comment]
Oh I meant c could be optimized out

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
