### ISSUE TITLE
[API Discuss] The `p` argument in `symbol.RNN` is quite confusing

### ISSUE THREAD

**Issue by ZihengJiang** [apache/incubator-mxnet#5283]
It is ok to put p in `dropout` like `sym.dropout(p=0.5)`, but it is quite confusing to put an alone argument `p` in the context of RNN: `sym.RNN(p=0.5)`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
