### ISSUE TITLE
train_cifar10.py not running

### ISSUE THREAD

**Issue by sampathchanda** [apache/incubator-mxnet#5285]
I am able to run train_mnist.py, both using single CPU node (with no GPUs) and using multi node CPU cluster (distributed training). However, I am seeing that training is very slow with the MNIST example. 

After looking into the suggestion of using bigger workload, from following thread:
https://github.com/dmlc/mxnet/issues/5158
I am now trying to run train_cifar10.py instead. However, I am unable to run the example, even with a single node.

Following is the issue I am facing. Whenever I am trying to run the example, the process is getting killed, as below:

**0 $ python train_cifar10.py --kv-store local**
INFO:root:start with arguments Namespace(batch_size=128, benchmark=0, data_nthreads=4, data_train='data/cifar10_train.rec', data_val='data/cifar10_val.rec', disp_batches=20, gpus=None, image_shape='3,28,28', kv_store='local', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs='200,250', max_random_aspect_ratio=0, max_random_h=36, max_random_l=50, max_random_rotate_angle=0, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='resnet', num_classes=10, num_epochs=300, num_examples=50000, num_layers=110, optimizer='sgd', pad_size=4, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, wd=0.0001)
[05:30:23] src/io/iter_image_recordio.cc:221: ImageRecordIOParser: data/cifar10_train.rec, use 1 threads for decoding..
[05:30:23] src/io/iter_image_recordio.cc:221: ImageRecordIOParser: data/cifar10_val.rec, use 1 threads for decoding..
Killed

Steps:
1. mkdir train_cifar10 ; cd train_cifar10
2. Have following files/directories in the current directory, from mxnet repository:
    a) common/
    b) data/
         -- cifar10_train.rec
         -- cifar10_val.rec
    c) hosts
    d) __init__.py
    e) mxnet/
    f) symbols/
    g) train_cifar10.py
3. python train_cifar10.py --kv-store local

Can anyone please help me out, with fixing this issue.

**Comment by salemmohammed** [comment]
@sampathchanda 
Hi,

Are you able to run the dataset on distributed node ? if yes, what is the speed. I am having the following speed.
#5422 

sincerely

**Comment by sampathchanda** [comment]
Are you able to run on CIFAR10 dataset ?
If yes, what steps did you follow apart from the ones I mentioned above. I am unable to run the cifar10 example.

I ran distributed training only on mnist dataset, and I am seeing significant slow down. Its around like 2x slowdown with 2 nodes.

**Comment by chuckbasstan123** [comment]
I met the same issue, not able to run cifar10 case :( No idea how to debug it. Does anyone else meet this problem?

**Comment by LakeCarrot** [comment]
I believe it is the batch size is too large and out of memory. Try to set the batch size to one at first, and see whether it can work or not.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
