### ISSUE TITLE
Dependence of training accuracy on number of CPU nodes

### ISSUE THREAD

**Issue by sampathchanda** [apache/incubator-mxnet#5287]
I am training MNIST classifier using the mnist example provided in MXNET repository.
I came to know that convergence is not guaranteed when using asynchronous update of weights from the documentation at following link: [Sync vs. Async](http://newdocs.readthedocs.io/en/latest/distributed_training.html#synchronous-vs-asynchronous)

With the multi CPU node cluster that I am training MNIST classifier on, I tried once with async update and the other time with sync update of weights, with 5 nodes of t2.micro instances of AWS.

The training starts with a good accuracy of 80+ while using 'dist_sync' and converges. However, it starts and even arrives at only around 10-12% accuracy at the end of 20 epochs, while using 'dist_async' updation of weights.

On the other side, with lower number of cluster nodes, like 4 CPU nodes, both of them are leading to convergence. I am unable to understand clearly, what could be the reason of dependence of number of CPU nodes in cluster for distributed training convergence.

Can anyone please help me understand about this.

MXNET version: 0.9.3

**Comment by sampathchanda** [comment]
@qiyuangong 

Can you please share your insights on this issue.

**Comment by qiyuangong** [comment]
Actually, I am not an expert in deep learning (I am still trying to be :) ).  Here are some suggestions:

First, your result seems not good enough, even in `sync` model. Normally, it should be more than 96% with default parameters. Use `export PS_VERBOSE=1; your current command` to print more details. (`PS_VERBOSE=2` will print more)

Second, you can debug locally on your machine, with 'local' model (But you have to kill process manually when they go wrong). The basic workflow is the same as `yarn`, but run locally in different processes. Aforementioned `export PS_VERBOSE=1` also works in `local` model.

Also, as mentioned by MXNet members in #5422, distributed training is meaningless in small datasets. It seems that they have not added warnings in docs yet.

**Comment by sampathchanda** [comment]
Thanks for your insights. Will try your suggestions and get back.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
