### ISSUE TITLE
Backward() raise gpu error

### ISSUE THREAD

**Issue by saicoco** [apache/incubator-mxnet#5292]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu15.10
Compiler:
gcc-4.9.x
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.4
Or if installed from source:
yes
MXNet commit hash (`git rev-parse HEAD`):
be38c5b84030a63d0ab51f19737f99a75a7feb23
If you are using python package, please provide

Python version and distribution:
python2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
...
--Return--                                                                                                                                                    
> mxnet-0.9.4-py2.7.egg/mxnet/module/base_module.py (193)forward_backward()->None                                                                                                                                 
-> self.backward()                                                                                                                                            
(Pdb) [21:41:13] /home/1511314015/LIB/mxnet-0.9.4.x/mshadow/mshadow/././././cuda/tensor_gpuinl.cuh:56: too large launch parameter: MapReduceKeepDim1[256,1,1] 
```
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```python
def get_mcb(debug=False, batch_size=128):
    # pylint: disable=line-too-long
    audio_data = mx.sym.Variable(name='audio_data')
    face_data = mx.sym.Variable(name='face_data')
    softmax_label = mx.sym.Variable(name='softmax_label')
    
    # LSTM1, LSTM2
    rnn1 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm1_')
    rnn1_outputs, rnn1_states = rnn1.unroll(length=49, inputs=audio_data, merge_outputs=False)
    rnn2 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm2_')
    rnn1_out_expand = [mx.sym.expand_dims(item, axis=1) for item in rnn1_outputs]
    rnn1_out_concat = mx.sym.Concat(*rnn1_out_expand, dim=1, num_args=49)
    rnn2_outputs, rnn2_states = rnn2.unroll(length=49, inputs=rnn1_out_concat, merge_outputs=False)

```
Error happens in `LSTMCell` when modal does `backward`, the method `forward`works well, by the way, it works well in CPU, except GPU.
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.Debug, trace to exector.backward()->None.
2.
3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
