### ISSUE TITLE
Unable to install mxnet with matlab on win10

### ISSUE THREAD

**Issue by kaare-mikkelsen** [apache/incubator-mxnet#5294]
This should probably be read more as an issue with the documentation, rather than a technical obstacle. While clearly not being sufficiently computer savvy to make my way through this installation, I do consider myself quite technically minded, and I am probably representative of a pretty large potential user group (Matlab on Windows is a pretty common setup, after all). 

The pre-built packages do not contain the matlab component. If it is possible to combine the matlab component from a new version with a pre-built (old) version, then that is not mentioned anywhere (and it seems pretty unlikely anyway).

That leaves building mxnet on windows "by hand". 

Going to the guide (http://newdocs.readthedocs.io/en/latest/build.html#building-on-windows), an immediate problem seems to be that it was written a while ago. I have been unable to find a version of VS community 2013 older than the "Visual C++ Compiler Nov 2013 CTP". When the installed version is newer than the patch, the patch won't install. Presumably, this means that the patch isn't needed? For the record, I have used VS 2013 downloaded from https://go.microsoft.com/fwlink/?LinkId=517284. That link, in turn, was taken from https://www.visualstudio.com/en-us/news/releasenotes/vs2013-community-vs.

Finally, I am instructed to "use CMake to create a Visual Studio solution in ./build/". There is no "build" directory in my mxnet-0.9.3 folder. What am I missing? 

-------------------------------------------

Operating System: Windows 10

Compiler: Visual Studio 2013 Community Edition Patch 4

Package used (Python/R/Scala/Julia): Matlab

MXNet version: 0.9.3

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
