### ISSUE TITLE
How to run autoencoder

### ISSUE THREAD

**Issue by Bin13** [apache/incubator-mxnet#5295]
## Environment info
mac os X EI CapItan

Hi, 
     I am a fresher on mxnet, and I'm sorry that my english is not good. I installed the mxnet on my mac ,and I can run example image-classification. Now I want to run autoencoder, but I got a error message:"ImportError: No module named sklearn.datasets".
When I use pip install sklearn , the system told me to installed it, like this: "Requirement already satisfied: scikit-learn in /usr/local/lib/python2.7/site-packages (from sklearn)" . I have set the path to environment , but it still can't work.
     who can tell me how to resolve this problem. thank you very much.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
