### ISSUE TITLE
where is optimizer.h?

### ISSUE THREAD

**Issue by wlike** [apache/incubator-mxnet#5304]
In src/optimizer/sgd-inl.h, the file is included as `<mxnet/optimizer.h>`. But it doesn't exist.
Can it be deleted? sgd-inl.h is not used by other files.

**Comment by wlike** [comment]
@piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
