### ISSUE TITLE
mxnet : how to make prediction using a trained RNN model

### ISSUE THREAD

**Issue by FCInter** [apache/incubator-mxnet#5306]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Centos 6.6
Compiler:
gcc-4.8.5
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.4
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
Traceback (most recent call last):
  File "lstm_bucketing.py", line 138, in <module>
    x = model.predict(eval_data = data_val, num_batch=10)
  File "/home/mypath/software/try_mxnet/mxnet/python/mxnet/module/base_module.py", line 342, in predict
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
TypeError: unsupported operand type(s) for -: 'long' and 'NoneType'

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
    

    import numpy as np
    import mxnet as mx
    import argparse

    parser = argparse.ArgumentParser(description="Train RNN on Penn Tree Bank",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--num-layers', type=int, default=2,
    help='number of stacked RNN layers')
    parser.add_argument('--num-hidden', type=int, default=200,
    help='hidden layer size')
    parser.add_argument('--num-embed', type=int, default=200,
    help='embedding layer size')
    parser.add_argument('--gpus', type=str,
    help='list of gpus to run, e.g. 0 or 0,2,5. empty means using cpu. ' 
    'Increase batch size when using multiple gpus for best performance.')
    parser.add_argument('--kv-store', type=str, default='device',
    help='key-value store type')
    parser.add_argument('--num-epochs', type=int, default=25,
    help='max num of epochs')
    parser.add_argument('--lr', type=float, default=0.01,
    help='initial learning rate')
    parser.add_argument('--optimizer', type=str, default='sgd',
    help='the optimizer type')
    parser.add_argument('--mom', type=float, default=0.0,
    help='momentum for sgd')
    parser.add_argument('--wd', type=float, default=0.00001,
    help='weight decay for sgd')
    parser.add_argument('--batch-size', type=int, default=32,
    help='the batch size.')
    parser.add_argument('--disp-batches', type=int, default=50,
    help='show progress for every n batches')

    def tokenize_text(fname, vocab=None, invalid_label=-1, start_label=0):
    lines = open(fname).readlines()
    lines = [filter(None, i.split(' ')) for i in lines]
    sentences, vocab = mx.rnn.encode_sentences(lines, vocab=vocab, invalid_label=invalid_label,
    start_label=start_label)
    num_sent = len(sentences)
    num_vocab = len(vocab)
    return sentences, vocab
    
    if name == 'main':
    import logging
    head = '%(asctime)-15s %(message)s'
    logging.basicConfig(level=logging.DEBUG, format=head)`

    args = parser.parse_args()

    #buckets = []
    buckets = [10, 20, 30, 40, 50, 60]

    start_label = 1
    invalid_label = 0

    train_sent, vocab = tokenize_text("./data/ptb.train.txt", start_label=start_label,
                                      invalid_label=invalid_label)
    val_sent, _ = tokenize_text("./data/ptb.test.txt", vocab=vocab, start_label=start_label,
                                invalid_label=invalid_label)

    data_train  = mx.rnn.BucketSentenceIter(train_sent, args.batch_size, buckets=buckets,
                                            invalid_label=invalid_label)
    data_val    = mx.rnn.BucketSentenceIter(val_sent, args.batch_size, buckets=buckets,
                                            invalid_label=invalid_label)

    stack = mx.rnn.SequentialRNNCell()
    for i in range(args.num_layers):
        stack.add(mx.rnn.LSTMCell(num_hidden=args.num_hidden, prefix='lstm_l%d_'%i))
    def sym_gen(seq_len):
        data = mx.sym.Variable('data')
        label = mx.sym.Variable('softmax_label')
        embed = mx.sym.Embedding(data=data, input_dim=len(vocab),
                                 output_dim=args.num_embed, name='embed')

        stack.reset()
        outputs, states = stack.unroll(seq_len, inputs=embed, merge_outputs=True)

        pred = mx.sym.Reshape(outputs, shape=(-1, args.num_hidden))
        pred = mx.sym.FullyConnected(data=pred, num_hidden=len(vocab), name='pred')

        label = mx.sym.Reshape(label, shape=(-1,))
        pred = mx.sym.SoftmaxOutput(data=pred, label=label, name='softmax')

        return pred, ('data',), ('softmax_label',)

    if args.gpus:
        contexts = [mx.gpu(int(i)) for i in args.gpus.split(',')]
    else:
        contexts = mx.cpu(0)

    model = mx.mod.BucketingModule(
        sym_gen             = sym_gen,
        default_bucket_key  = data_train.default_bucket_key,
        context             = contexts)
    model.fit(
        train_data          = data_train,
        eval_data           = data_val,
        eval_metric         = mx.metric.Perplexity(invalid_label),
        kvstore             = args.kv_store,
        optimizer           = args.optimizer,
        optimizer_params    = { 'learning_rate': args.lr,
                                'momentum': args.mom,
                                'wd': args.wd },
        initializer         = mx.init.Xavier(factor_type="in", magnitude=2.34),
        num_epoch           = args.num_epochs,
        batch_end_callback  = mx.callback.Speedometer(args.batch_size, args.disp_batches),
        epoch_end_callback = mx.callback.do_checkpoint("obama"))
    
    x = model.predict(eval_data = data_val, num_batch=10)
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. python lstm_bucketing.py --num-epochs 1
2.
3.

## What have you tried to solve it?

1. I tried the example of RNN located [here](https://github.com/dmlc/mxnet/tree/master/example/rnn). The training finishes successfully and I hope to use it to do next word prediction.
2. I just read the source code for `base_module.py` and find that it has a function `predict` which can be used to make prediction. Therefore I tried to call the `predict` function after the training. So I run 
`x = model.predict(eval_data = data_val, num_batch=10)`
But error happens and it says 
`outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
TypeError: unsupported operand type(s) for -: 'long' and 'NoneType'`
What's wrong? 
How to use a trained RNN to make predictions?
BTW, the [tutorial for character prediction](http://mxnet.io/tutorials/python/char_lstm.html) does not work. When I run it, I received error saying "XXX function has been deprecated" and then the process terminated.
Thank you all for helping me!

**Comment by Cloudyrie** [comment]
This is caused by pad value is not provided when BucketSentenceIter.next() returns DataBatch. Just add pad=0 to BucketSentenceIter.next() like:
`return DataBatch([data], [label], pad=0,
                         bucket_key=self.buckets[i],
                         provide_data=[(self.data_name, data.shape)],
                         provide_label=[(self.label_name, label.shape)])`
in mxnet/python/rnn/io.py and model.predict() seems to work

**Comment by Cloudyrie** [comment]
#5518 fixed.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
