### ISSUE TITLE
MXNET metric function

### ISSUE THREAD

**Issue by ChristianEschen** [apache/incubator-mxnet#5316]
I use MXNET for semantic image segmentation with binary classes.
Since my images primary represents background I am trying to change the sum metric function.
For this purpose I use mxnet.metric.F1
However, I problems running mxnet.metric.F1.

    mod.fit(
        dataiter,
        eval_metric=mx.metric.F1(), # here I apply binary classification metric
        batch_end_callback=mx.callback.Speedometer(dataiter.batch_size, 1),
        epoch_end_callback=mx.callback.do_checkpoint(to_model),
        kvstore=args.kvstore,
        optimizer='sgd',
        optimizer_params=optimizer_params,
        initializer=initializer,
        arg_params=net_args,
        aux_params=net_auxs,
        allow_missing=args.from_epoch == 0,
        begin_epoch=args.from_epoch,
        num_epoch=args.stop_epoch,

Unfortunately, the response is:

Traceback (most recent call last):
  File "issegm/voc.py", line 932, in <module>
    2017-03-09 07:21:11,655 Host Labels: 169
_train_impl(args, model_specs, logger)
  File "issegm/voc.py", line 675, in _train_impl
    num_epoch=args.stop_epoch,
  File "/mxnet/python/mxnet/module/base_module.py", line 412, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/mxnet/python/mxnet/module/module.py", line 556, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "//mxnet/python/mxnet/module/executor_group.py", line 470, in update_metric
    eval_metric.update(labels_slice, texec.outputs)
  File "//mxnet/python/mxnet/metric.py", line 200, in update
    if y_pred == 1 and y_true == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I do not understand why this is not working. The pred and label values which are as I can see quite fixed and not modifiable.

**Comment by ChristianEschen** [comment]
If I run with the costum metric function I experience no issues. 
Here I can define my own feval as:
def _get_metric():
    def _eval_func(label, pred):
        gt_label = label.ravel()
        valid_flag = gt_label != 255
        gt_label = gt_label[valid_flag]
        pred_label = pred.argmax(1).ravel()[valid_flag]
        
        sum_metric = (gt_label == pred_label).sum()
        num_inst = valid_flag.sum()
        return (sum_metric, num_inst + (num_inst == 0))
return mx.metric.CustomMetric(_eval_func, 'fcn_valid')

And compile it with no errors:

 mod.fit(
        dataiter,
        eval_metric=_get_metric(),
        batch_end_callback=mx.callback.Speedometer(dataiter.batch_size, 1),
        epoch_end_callback=mx.callback.do_checkpoint(to_model),
        kvstore=args.kvstore,
        optimizer='sgd',
        optimizer_params=optimizer_params,
        initializer=initializer,
        arg_params=net_args,
        aux_params=net_auxs,
        allow_missing=args.from_epoch == 0,
        begin_epoch=args.from_epoch,
        num_epoch=args.stop_epoch,
)

However, it is the binary sum metric function which is of interest.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
