### ISSUE TITLE
DataIter does not have provide_data and provide_label

### ISSUE THREAD

**Issue by jdchoi77** [apache/incubator-mxnet#5331]
I see many comments mentioning that `DataIter` gives `provide_data` and `provide_label`, which do not exist in the current version: https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L89

These comments should be modified to avoid confusion.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
