### ISSUE TITLE
how to train own dataset  with fcn_xs

### ISSUE THREAD

**Issue by Hjy20255** [apache/incubator-mxnet#5343]
Hi, I have worked with FCN models for image segmentation using FCN_XS, my dataset is about UAV remote sensing images, and I labeled them, Thedataset have 4 class (contains background). all images are spilted into 500*500.I gernerate own train.lst and val.lst.
i change "21" to "4" in "fcn_xs.py".
But when i run scripts" python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers        --epoch=74 --init-type=vgg16" , i meet  error.
 File "/home/hjy/trian-0.7.0_fcn_xs/solver.py", line 66, in fit
    label_shape[1]*label_shape[2]), self.ctx)
ValueError: cannot reshape array of size 750000 into shape (1,250000)
How to solve it?

**Comment by Godricly** [comment]
Is your label of shape (3,500,500). The reshaping of label is not correct.

**Comment by Hjy20255** [comment]
@Godricly  my label  shape (1, 500, 500, 3)

**Comment by xinghedyc** [comment]
@Hjy20255 I guess the label should be like (500,500).

**Comment by zhangfanqie** [comment]
Hi,could you please tell me how you label your own images,I used the labelme but got some error.
Thank you!

**Comment by lzx1413** [comment]
@zhangfanqie you can have a try with this one https://github.com/lzx1413/labelImgPlus

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
