### ISSUE TITLE
mx.io.NDArrayIter：batch size for evaluation data

### ISSUE THREAD

**Issue by wanglovesyang** [apache/incubator-mxnet#5344]
I tried a dozen of time before I get the conclusion that the training data and evaluation data shall use the same batch size. What if the evaluation data size is smaller than the batch size for training. I read some of the document and figured out that batch size is related to pre-allocation of memory, thus the prediction is conducted on one batch at a time. I am not sure if I am on the right channel.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
