### ISSUE TITLE
Amalgamation using weBLAS (JS + WebGL) ?

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#5346]
I've got mxnet amalgamation working in a browser JS webapp, however the speed is really slow comparing with native code.

Is there a method for the amalgamation to use weBLAS? (which uses WebGL and is much, much faster)
https://github.com/waylonflinn/weblas

weBLAS is a simple library with the most commonly used operations. It provides 32-bit versions of each of these:
sscal - Matrix (and Vector) Scale (with addition)
sgemm - Matrix Multiply
sdwns - Matrix (and Image) Downsample (for Max Pooling)
sclmp - Matrix clamp (for ReLU)

**Comment by gusdoe** [comment]
There is similar blas library called flame/blis and lapack. These are more complete than weblas. If any one try to migrate mxnet, these are worth to try.
