### ISSUE TITLE
Which mxnet version am i using?

### ISSUE THREAD

**Issue by avspavan** [apache/incubator-mxnet#5348]
I am a newbie with MXNET. How do i check the version? My git branch says its master.

**Comment by wangg12** [comment]
@avspavan You could check the version in python by `mx.__version__`.

**Comment by matt32106** [comment]
in R:
`packageVersion("mxnet")`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
