### ISSUE TITLE
NDArray: Adding to discontinuous indices

### ISSUE THREAD

**Issue by ghost** [apache/incubator-mxnet#5349]
I have the following case. Assume that I have have an NDArray object, A, with the shape (D, dim) where dim is any arbitrary shape and D is the minibatch size. I have another NDArray object, B, with the shape (d, dim) where d < D. Now, I have a mapping between the axis-0 indices of B and A, such that entry B[i] is mapped to A[j] where j >= i. My aim is to add each B[i] to A[j]. The naivest thing I could to is to iterate on B's axis0 and do for each B[i] the operation A[j] += B[i]. But each such addition operation is costly. To reduce the it, I keep the track of each consequent j entries in the A object and do addition as A[j1:j2] += B[i1:i2]. While this lowers the number of additions, still I have to do multiple ones.

I wonder if such an operation is possible currently: Let's say I know all the j indices, [j1,j2, ..., jd]. In numpy, it is possible to do operations by using the index array as A[[j1,j2,...,jd]] += B. Trying the similar operation results in "ValueError: NDArray only support continuous slicing on axis 0" with MxNet NDArray. My purpose is to execute this addition in a single command. Is this possible with the current MxNet API?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
