### ISSUE TITLE
Docker build on raspbian fails

### ISSUE THREAD

**Issue by asifamz** [apache/incubator-mxnet#5353]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Raspbian

Compiler: g++-4.8

Package used (Python/R/Scala/Julia): Pythno

MXNet version: latest

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/mxnet/mshadow/ -I/mxnet/dmlc-core/include -fPIC -I/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv  -fopenmp  -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_basic.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o
/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_EQ(const X&, const Y&) [with X = int; Y = unsigned int]’:
/mxnet/nnvm/include/nnvm/tuple.h:446:5:   required from ‘mshadow::Shape<ndim> nnvm::TShape::get() const [with int dim = 5]’
src/operator/tensor/./broadcast_reduce-inl.h:172:71:   required from ‘void mxnet::op::broadcast::BinaryBroadcastComputeImpl(mshadow::Stream<mshadow::cpu>*, mxnet::OpReqType, const mxnet::TBlob&, const mxnet::TBlob&, const mxnet::TBlob&) [with DType = float; OP = mxnet::op::mshadow_op::power]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:116:5:   required from ‘void mxnet::op::BinaryBroadcastCompute(const nnvm::NodeAttrs&, const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&) [with xpu = mshadow::cpu; OP = mxnet::op::mshadow_op::power]’
src/operator/tensor/elemwise_binary_broadcast_op_extended.cc:17:84:   required from here
/mxnet/dmlc-core/include/dmlc/./logging.h:94:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_FUNC(_EQ, ==)
                        ^
/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^
In file included from /mxnet/dmlc-core/include/dmlc/registry.h:13:0,
                 from include/mxnet/operator_util.h:18,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_broadcast_op_basic.cc:6:
/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_EQ(const X&, const Y&) [with X = unsigned int; Y = int]’:
src/operator/tensor/./elemwise_unary_op.h:79:3:   required from here
/mxnet/dmlc-core/include/dmlc/./logging.h:94:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_FUNC(_EQ, ==)
                        ^
/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^
/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_EQ(const X&, const Y&) [with X = int; Y = unsigned int]’:
/mxnet/nnvm/include/nnvm/tuple.h:446:5:   required from ‘mshadow::Shape<ndim> nnvm::TShape::get() const [with int dim = 5]’
src/operator/tensor/./broadcast_reduce-inl.h:172:71:   required from ‘void mxnet::op::broadcast::BinaryBroadcastComputeImpl(mshadow::Stream<mshadow::cpu>*, mxnet::OpReqType, const mxnet::TBlob&, const mxnet::TBlob&, const mxnet::TBlob&) [with DType = float; OP = mshadow::op::plus]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:116:5:   required from ‘void mxnet::op::BinaryBroadcastCompute(const nnvm::NodeAttrs&, const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&) [with xpu = mshadow::cpu; OP = mshadow::op::plus]’
src/operator/tensor/elemwise_binary_broadcast_op_basic.cc:17:84:   required from here
/mxnet/dmlc-core/include/dmlc/./logging.h:94:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_FUNC(_EQ, ==)
                        ^
/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^
/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_NE(const X&, const Y&) [with X = unsigned int; Y = int]’:
/mxnet/mshadow/mshadow/./tensor_cpu-inl.h:213:3:   required from ‘void mshadow::MapReduceKeepLowest(mshadow::TRValue<R, mshadow::cpu, 1, DType>*, const mshadow::expr::Exp<E, DType, etype>&, DType) [with Saver = mshadow::sv::plusto; Reducer = mshadow::red::sum; R = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float; E = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::right, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; int etype = 3]’
/mxnet/mshadow/mshadow/././extension/reduceto1d.h:99:63:   required from ‘static void mshadow::expr::ExpComplexEngine<SV, mshadow::Tensor<xpu, 1, DType>, mshadow::expr::ReduceTo1DExp<SrcExp, DType, Reducer, 1>, DType>::Eval(mshadow::Tensor<xpu, 1, DType>*, const mshadow::expr::ReduceTo1DExp<SrcExp, DType, Reducer, 1>&) [with SV = mshadow::sv::plusto; Device = mshadow::cpu; DType = float; SrcExp = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::right, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; Reducer = mshadow::red::sum]’
/mxnet/mshadow/mshadow/././expr_engine-inl.h:461:72:   required from ‘static void mshadow::expr::ExpEngine<Saver, RValue, DType>::Eval(RV*, const mshadow::expr::Exp<E, DType, 7>&) [with E = mshadow::expr::ReduceTo1DExp<mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::right, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>, float, mshadow::red::sum, 1>; SV = mshadow::sv::plusto; RV = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float]’
/mxnet/mshadow/mshadow/./expression.h:175:78:   required from ‘Container& mshadow::expr::RValueExp<Container, DType>::operator+=(const mshadow::expr::Exp<E, DType, etype>&) [with E = mshadow::expr::ReduceTo1DExp<mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::right, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>, float, mshadow::red::sum, 1>; int etype = 7; Container = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:163:5:   required from ‘void mxnet::op::ReduceToAssign(mshadow::Tensor<xpu, 2, DType>, mxnet::OpReqType, const SrcExp&) [with Reducer = mshadow::red::sum; xpu = mshadow::cpu; SrcExp = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::right, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; DType = float]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:224:79:   required from ‘void mxnet::op::BinaryBroadcastBackwardUseInImpl(const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&, const TShape&, const TShape&, const TShape&) [with xpu = mshadow::cpu; int ndim = 2; DType = float; LOP = mxnet::op::mshadow_op::right; ROP = mxnet::op::mshadow_op::left; mxnet::TShape = nnvm::TShape]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:241:5:   required from ‘void mxnet::op::BinaryBroadcastBackwardUseIn(const nnvm::NodeAttrs&, const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&) [with xpu = mshadow::cpu; LOP = mxnet::op::mshadow_op::right; ROP = mxnet::op::mshadow_op::left]’
src/operator/tensor/elemwise_binary_broadcast_op_basic.cc:74:80:   required from here
/mxnet/dmlc-core/include/dmlc/./logging.h:95:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_FUNC(_NE, !=)
                        ^
/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^
/mxnet/dmlc-core/include/dmlc/./logging.h: In instantiation of ‘dmlc::LogCheckError dmlc::LogCheck_NE(const X&, const Y&) [with X = unsigned int; Y = int]’:
/mxnet/mshadow/mshadow/./tensor_cpu-inl.h:213:3:   required from ‘void mshadow::MapReduceKeepLowest(mshadow::TRValue<R, mshadow::cpu, 1, DType>*, const mshadow::expr::Exp<E, DType, etype>&, DType) [with Saver = mshadow::sv::plusto; Reducer = mshadow::red::sum; R = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float; E = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power_grad, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; int etype = 3]’
/mxnet/mshadow/mshadow/././extension/reduceto1d.h:99:63:   required from ‘static void mshadow::expr::ExpComplexEngine<SV, mshadow::Tensor<xpu, 1, DType>, mshadow::expr::ReduceTo1DExp<SrcExp, DType, Reducer, 1>, DType>::Eval(mshadow::Tensor<xpu, 1, DType>*, const mshadow::expr::ReduceTo1DExp<SrcExp, DType, Reducer, 1>&) [with SV = mshadow::sv::plusto; Device = mshadow::cpu; DType = float; SrcExp = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power_grad, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; Reducer = mshadow::red::sum]’
/mxnet/mshadow/mshadow/././expr_engine-inl.h:461:72:   required from ‘static void mshadow::expr::ExpEngine<Saver, RValue, DType>::Eval(RV*, const mshadow::expr::Exp<E, DType, 7>&) [with E = mshadow::expr::ReduceTo1DExp<mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power_grad, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>, float, mshadow::red::sum, 1>; SV = mshadow::sv::plusto; RV = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float]’
/mxnet/mshadow/mshadow/./expression.h:175:78:   required from ‘Container& mshadow::expr::RValueExp<Container, DType>::operator+=(const mshadow::expr::Exp<E, DType, etype>&) [with E = mshadow::expr::ReduceTo1DExp<mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power_grad, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>, float, mshadow::red::sum, 1>; int etype = 7; Container = mshadow::Tensor<mshadow::cpu, 1, float>; DType = float]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:163:5:   required from ‘void mxnet::op::ReduceToAssign(mshadow::Tensor<xpu, 2, DType>, mxnet::OpReqType, const SrcExp&) [with Reducer = mshadow::red::sum; xpu = mshadow::cpu; SrcExp = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::cpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power_grad, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, mshadow::expr::MakeTensorExp<mshadow::expr::BroadcastWithMultiAxesExp<mshadow::Tensor<mshadow::cpu, 2, float>, float, 2>, mshadow::Tensor<mshadow::cpu, 2, float>, 2, float>, float, 3>, float, 3>; DType = float]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:224:79:   required from ‘void mxnet::op::BinaryBroadcastBackwardUseInImpl(const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&, const TShape&, const TShape&, const TShape&) [with xpu = mshadow::cpu; int ndim = 2; DType = float; LOP = mxnet::op::mshadow_op::power_grad; ROP = mxnet::op::mshadow_op::power_rgrad; mxnet::TShape = nnvm::TShape]’
src/operator/tensor/./elemwise_binary_broadcast_op.h:241:5:   required from ‘void mxnet::op::BinaryBroadcastBackwardUseIn(const nnvm::NodeAttrs&, const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&) [with xpu = mshadow::cpu; LOP = mxnet::op::mshadow_op::power_grad; ROP = mxnet::op::mshadow_op::power_rgrad]’
src/operator/tensor/elemwise_binary_broadcast_op_extended.cc:29:87:   required from here
/mxnet/dmlc-core/include/dmlc/./logging.h:95:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_FUNC(_NE, !=)
                        ^
/mxnet/dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro ‘DEFINE_CHECK_FUNC’
     if (x op y) return LogCheckError();                           \
           ^

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

I am compiling a Dockerfile on raspbian. 

Dockerfile content:

FROM resin/rpi-raspbian:latest

# Install build-essential, git, wget and other dependencies
RUN apt-get update && apt-get install -y \
 git \
 cmake \
 build-essential \
 g++-4.8 \
 c++-4.8 \
 liblapack* \
 libblas* \
 libopencv* \
 libopenblas* \
 python-dev \
 python-numpy \
 python-setuptools \
 wget \
 python3-pip \
 nginx supervisor \
 python-pip \
 python-opencv

# Clone MXNet repo and move into it
RUN cd / && git clone --recursive https://github.com/dmlc/mxnet && cd mxnet && \
# Copy config.mk
  cp make/config.mk config.mk && \
# Set OpenBLAS
  sed -i 's/USE_BLAS = atlas/USE_BLAS = openblas/g' config.mk && \
# Make
  make -j"$(nproc)"

# Install Python package
RUN cd /mxnet/python && python setup.py install

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.  install docker on pi3
2. docker build -t mxnet . 
3.

## What have you tried to solve it?

1. changed g++ 
2. tried debian and it works
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
