### ISSUE TITLE
magic python functions in ndarray.py

### ISSUE THREAD

**Issue by wanglovesyang** [apache/incubator-mxnet#5354]
I have been reading the code of mxnet for some further understanding of the platform. In optimizer.py, I saw following code:
"from .ndarray import sgd_update, sgd_mom_update, adam_update, rmsprop_update, rmspropalex_update"

However, the python implementations of these functions are absent in ndarray.py. I am sure these functions are written in c but these should at least some cython-wraps for them, but I only get "NNVM_REGISTER_OP(sgd_mom_update)" when scanning the code using ack.

**Comment by ZihengJiang** [comment]
Try to read some codes here: https://github.com/dmlc/mxnet/blob/master/python/mxnet/_ctypes/ndarray.py#L155

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
