### ISSUE TITLE
How to write a new custom layer with learned parameters?

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#5355]
Anyone know how to write a new custom layer with learned param? Is there any tutorial or example that create new layers with learned parameters?

**Comment by shuokay** [comment]
I think this work can be divided into 2 steps:
1. create a new layer, this can refer to [How to Create New Operators (Layers)](http://mxnet.io/how_to/new_op.html)
2. bind leaned params. this can refer to the [python source code](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L509-L522)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
