### ISSUE TITLE
Combining items within batch during forward pass

### ISSUE THREAD

**Issue by Strateus** [apache/incubator-mxnet#5356]
Is there any way in Mxnet to concat for example 3 consecutive images from same batch on forward pass right after one of layers and then pass them thru several more layers as combined input to get one output? I.e. for initial batch size of 300 on the inputs there will be 100 final outputs for same batch.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
