### ISSUE TITLE
What factor impact the speed (xxx samples/sec) in training process ?

### ISSUE THREAD

**Issue by bruinxiong** [apache/incubator-mxnet#5365]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04.5

Compiler: gcc 4.8.4

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:  installed by git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: python 2.7.13 anaconda 4.3.0

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

Build environment
nvidia 375.26, cuda 8.0, gcc 4.8.4, ubundu 14.04.5, cudnn 5.1
@tqchen @piiswrong @tornadomeet
First, we implement DenseNet-BC introduced by Gao Huang, Zhuang Liu, Kilian Q. Weinberger, Laurens van der Maaten in the paper "Densely Connected Convolutional Networks" with MXNet.  More detailed information can be found in https://github.com/bruinxiong/densenet.mxnet 

However, we don't know what factor impact the speed (xxx samples/sec) in training process.
In this figure, we deploy neural network (DenseNet-BC ) on VGG-Face data (num_classes=2613, num_examples=1483368) with batch size 128.
![image](https://cloud.githubusercontent.com/assets/3366247/23845962/111423a2-0806-11e7-9836-2f8f6f896be1.png)

However, in the following figure, we deploy the same neural network and same training procedure on MS-Celeb data (num_classes=79051, num_examples=4513005) with batch size 96.
![image](https://cloud.githubusercontent.com/assets/3366247/23846014/53e8342a-0806-11e7-8516-a19d75b2af6e.png)

Is this the reason of data cause this large difference on speed ?

If is not, what factor impact the speed (xxx samples/sec) in training process ?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
