### ISSUE TITLE
Why don't use TBlob directly in Operator

### ISSUE THREAD

**Issue by shuokay** [apache/incubator-mxnet#5366]
I am wondering why don't use `TBlob` directly in Operator's `Forward` and `Backward`. What is the advantage of using `Tensor` compared to `TBlob`.

If `Tensor` is better than `TBlob`, then why don't pass `Tensor` to `Forward` and `Backward` directly.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
