### ISSUE TITLE
"key "stride" not found" when using to_graphviz with Convolutional layers in Julia API

### ISSUE THREAD

**Issue by facundoq** [apache/incubator-mxnet#5369]
From the Julia API, we can't access the attr "stride" for Convolution layers. 

I reported this issue in the Julia API repo  @pluskid suggested this is may be a bug in the core mxnet API (https://github.com/dmlc/MXNet.jl/issues/213#issuecomment-285790634).

## Environment info
Operating System: ubuntu 14.04

Compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Package used (Python/R/Scala/Julia): Julia: Version 0.5.0 (2016-09-19 18:14 UTC), Official http://julialang.org/ release, x86_64-pc-linux-gnu

MXNet version:  julia> Pkg.status("MXNet")       0.2.1              e599d51d

## Error Message:
```
ERROR: LoadError: KeyError: key "stride" not found
 in getindex(::Dict{String,Any}, ::String) at ./dict.jl:688
 in #to_graphviz#6566(::String, ::Void, ::Function, ::MXNet.mx.SymbolicNode) at ~/.julia/v0.5/MXNet/src/visualize.jl:71
```

## Minimum reproducible example
```
using MXNet
mlp = @mx.chain mx.Variable(:data)             =>
  mx.Convolution(kernel=(5,5), num_filter=64)
mx.to_graphviz(mlp)
```

The error appears when accessing `node["attr"]["stride"]` when `node["op"]=="Convolution"`.
Accessing `kernel` or `num_filter` works fine.

Printing the node from julia you get:
```
Dict{String,Any}(Pair{String,Any}("name","convolution1"),Pair{String,Any}("attr",Dict{String,Any}(Pair{String,Any}("num_filter","64"),Pair{String,Any}("kernel","(5,5)"))),Pair{String,Any}("op","Convolution"),Pair{String,Any}("inputs",Any[Any[10,0,0],Any[11,0,0],Any[12,0,0]]))
```

## What have you tried to solve it?
Obviously removing the access to the attr in https://github.com/dmlc/MXNet.jl/blob/master/src/visualize.jl#L72-L74, makes the error go away but then there's no stride info in the graph.

Apparently the python api does the same thing as Julia's:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/visualization.py#L252

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
