### ISSUE TITLE
unable to compile mxnet after latest pull

### ISSUE THREAD

**Issue by ForoughA** [apache/incubator-mxnet#5375]
I am unable to compile mxnet after the latest pull on Monday March 13, 2017. I am trying to do:
make clean && make

## Environment info
Operating System:
Mac OS X El Capitan (version 10.11.5)

Compiler:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Package used (Python/R/Scala/Julia):
Python 2.7

MXNet commit hash (`git rev-parse HEAD`):
b446aef95d738ce0ce1bbe621fa9fc41b549ef6c

If you are using python package, please provide

Python version and distribution:
Python 2.7.12 :: Anaconda 4.2.0 (x86_64)

## Error Message:
rm -rf python/mxnet/*/*.so python/mxnet/*/*.cpp
rm -f -r build lib bin *~ */*~ */*/*~ */*/*/*~ R-package/NAMESPACE R-package/man R-package/R/mxnet_generated.R \
		R-package/inst R-package/src/*.o R-package/src/*.so mxnet_*.tar.gz
cd /Users/Forough/mxnet/dmlc-core; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -f line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o  libdmlc.a test/filesys_test test/dataiter_test test/iostream_test test/recordio_test test/split_read_test test/stream_read_test test/split_test test/libsvm_parser_test test/split_repeat_read_test test/strtonum_test test/logging_test test/parameter_test test/registry_test test/csv_parser_test test/unittest/dmlc_unittest test/unittest/unittest_any.o test/unittest/unittest_array_view.o test/unittest/unittest_config.o test/unittest/unittest_json.o test/unittest/unittest_logging.o test/unittest/unittest_main.o test/unittest/unittest_optional.o test/unittest/unittest_serializer.o test/unittest/unittest_threaditer.o *~ src/*~ src/*/*~ include/dmlc/*~ test/*~
/Users/Forough/mxnet
cd /Users/Forough/mxnet/ps-lite; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -rf build  tests/test_connection  tests/test_kv_app  tests/test_simple_app tests/*.d
find src -name "*.pb.[ch]*" -delete
/Users/Forough/mxnet
cd /Users/Forough/mxnet/nnvm; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -f -rf build lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o cli_test
/Users/Forough/mxnet
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/mkl/mkl_cppwrapper.cc -o build/src/operator/mkl/mkl_cppwrapper.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/mkl/mkl_memory.cc -o build/src/operator/mkl/mkl_memory.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/nnpack/nnpack_util.cc -o build/src/operator/nnpack/nnpack_util.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/broadcast_reduce_op_index.cc -o build/src/operator/tensor/broadcast_reduce_op_index.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/broadcast_reduce_op_value.cc -o build/src/operator/tensor/broadcast_reduce_op_value.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/control_flow_op.cc -o build/src/operator/tensor/control_flow_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_basic.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_extended.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_logic.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_basic.cc -o build/src/operator/tensor/elemwise_binary_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_extended.cc -o build/src/operator/tensor/elemwise_binary_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_logic.cc -o build/src/operator/tensor/elemwise_binary_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_basic.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_extended.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_logic.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_sum.cc -o build/src/operator/tensor/elemwise_sum.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_unary_op.cc -o build/src/operator/tensor/elemwise_unary_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/indexing_op.cc -o build/src/operator/tensor/indexing_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/init_op.cc -o build/src/operator/tensor/init_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/matrix_op.cc -o build/src/operator/tensor/matrix_op.o
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:9:
In file included from include/mxnet/operator_util.h:24:
In file included from include/mxnet/base.h:16:
/Users/Forough/mxnet/nnvm/include/nnvm/./tuple.h:35:3: error: static_assert failed "Tuple only support simple data
      type like int"
  static_assert(std::is_pod<ValueType>::value,
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/operator/tensor/./matrix_op-inl.h:673:37: note: in instantiation of template class
      'nnvm::Tuple<dmlc::optional<int> >' requested here
  nnvm::Tuple<dmlc::optional<int> > begin, end;
                                    ^
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:14:
In file included from src/operator/tensor/../elemwise_op_common.h:18:
src/operator/tensor/../operator_common.h:229:11: error: no matching member function for call to 'Init'
    param.Init(attrs->dict);
    ~~~~~~^~~~
src/operator/tensor/matrix_op.cc:209:18: note: in instantiation of function template specialization
      'mxnet::op::ParamParser<mxnet::op::SliceParam>' requested here
.set_attr_parser(ParamParser<SliceParam>)
                 ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/parameter.h:127:15: note: candidate function [with Container =
      std::__1::unordered_map<std::__1::basic_string<char>, std::__1::basic_string<char>,
      std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >]
      not viable: no known conversion from 'mxnet::op::SliceParam' to 'dmlc::Parameter<mxnet::op::SliceParam>' for
      object argument
  inline void Init(const Container &kwargs,
              ^
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:9:
In file included from include/mxnet/operator_util.h:18:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/registry.h:14:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/parameter.h:22:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/json.h:29:
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:179:21: error: no viable conversion from 'mxnet::op::SliceParam'
      to 'dmlc::any'
    this->construct(std::forward<T>(other));
                    ^~~~~~~~~~~~~~~~~~~~~~
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:229:3: note: in instantiation of function template
      specialization 'dmlc::any::any<mxnet::op::SliceParam>' requested here
  any(std::forward<T>(other)).swap(*this);
  ^
src/operator/tensor/../operator_common.h:241:17: note: in instantiation of function template specialization
      'dmlc::any::operator=<mxnet::op::SliceParam>' requested here
  attrs->parsed = std::move(param);
                ^
src/operator/tensor/matrix_op.cc:209:18: note: in instantiation of function template specialization
      'mxnet::op::ParamParser<mxnet::op::SliceParam>' requested here
.set_attr_parser(ParamParser<SliceParam>)
                 ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:176:13: note: candidate constructor
      [with T = mxnet::op::SliceParam]
inline any::any(T&& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:192:13: note: candidate constructor not viable: no known
      conversion from 'mxnet::op::SliceParam' to 'dmlc::any &&' for 1st argument
inline any::any(any&& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:196:13: note: candidate constructor not viable: no known
      conversion from 'mxnet::op::SliceParam' to 'const dmlc::any &' for 1st argument
inline any::any(const any& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:163:31: note: passing argument to parameter 'other' here
  inline void construct(any&& other);
                              ^
3 errors generated.
make: *** [build/src/operator/tensor/matrix_op.o] Error 1

## Minimum reproducible example
make clean && make

**Comment by shuokay** [comment]
Have you tried `git submodule update` ?

**Comment by ForoughA** [comment]
Great, this resolved it, thank you!

I opened [another issue](https://github.com/dmlc/mxnet/issues/5368#issuecomment-286184838), and "make clean && make" was supposed to correct it. But I still have the same issue. Can you please help me resolve it?

Thanks!
Forough.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
