### ISSUE TITLE
when i use mx version is 0.9.4 train faster-rcnn, i found it is very slowly.

### ISSUE THREAD

**Issue by abner2015** [apache/incubator-mxnet#5387]
when i use mx version is 0.9.4 train faster-rcnn, i found it is running slow.
what is the reason?

ENVIRONMENT
ubuntu14.04,
GTX1080
CUDA 8.0

**Comment by lilhope** [comment]
I have test it,about 4~5 samples/sec.

**Comment by sergeykolychev** [comment]
playing with batch size usually helps, did you try to increase it ?

**Comment by lilhope** [comment]
@sergeykolychev It seem only 1 batch_size supported if only have one GPU

**Comment by abner2015** [comment]
@sergeykolychev  start-up consumes a lot time , then  running demo.py consumes a lot of time. 
Running demo.py ,the whole process takes 2 minutes and 14seconds. (python demo.py --prefix final --epoch 0 --image 946.jpg --gpu 0
)
But, when  used caffe predict the picture it is quickly start-up

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
