### ISSUE TITLE
mxnet.base.MXNetError: [20:49:24] src/c_api/c_api_ndarray.cc:274: Operator _ones cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

### ISSUE THREAD

**Issue by danieleewww** [apache/incubator-mxnet#5389]
MXNet OSX install OK, running CPU ok, but GPU with the following errors

 
>>> import mxnet as mx
    >>> a = mx.nd.ones((2, 3), mx.gpu())  with the followings traces:
  

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x0000000107abc005 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010805c9cb MXImperativeInvoke + 13723
[bt] (2) 2   _ctypes.cpython-35m-darwin.so       0x00000001007de077 ffi_call_unix64 + 79
[bt] (3) 3   python                              0x00007fff5bffe990 __progname + 140730441914608

**Comment by matt32106** [comment]
Check #5378, i had the same error, it may be the same problem & solution?

**Comment by piiswrong** [comment]
you need to pull and recompile

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
