### ISSUE TITLE
About faster-rcnn C++ version

### ISSUE THREAD

**Issue by abner2015** [apache/incubator-mxnet#5405]
I want to use c++ code detection the object. I think is faster python code.
my question is :
Is there a c++ version  of faster-rcnn? 
if not, how can i do?
thanks for u help!

**Comment by dtmoodie** [comment]
Hello,

I too have run into this issue.  I've discovered that the proposal_target operator is only implemented in python https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/symbol/proposal_target.py#L14 and thus is holding me back from running my network in C++.
I will probably be looking into implementing this in C++ soon.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
