### ISSUE TITLE
how to save checkpoint at the end of some minibatch during training 

### ISSUE THREAD

**Issue by zhongkeli** [apache/incubator-mxnet#5408]
It is easy to save checkpoint at each epoch callback by define parameter epoch_end_callback.

But how to save checkpoint at the end of some minibatch during training instead of saving ckpt at the end of each epoch.

**Comment by lilhope** [comment]
try save checkpoints in`batch_end_callback`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
