### ISSUE TITLE
C++ API for mxnet current status

### ISSUE THREAD

**Issue by MaratZakirov** [apache/incubator-mxnet#5409]
[This issue is some kind of duplicate of https://github.com/dmlc/mxnet/issues/868]
For the production purposes now I thinking about migrating from keras to mxnet (I also excited about mxnet stuff like usage of multi GPU, its performance and so on, but the main reason is production purposes).
**As I currently think (or hope) previously trained on Python+mxnet+GPU model could be executed directly on C++ CPU code simply by model load in C++ code. Am I right?** If it so, could somebody please give some example of that?

**Comment by wguo68** [comment]
I have same question?C++ examples seems not work on wibdows and  msvc?

**Comment by chicn** [comment]
I also have a kind of same question though more simple one like if I can load model files trained with python + mxnet. #6419

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
