### ISSUE TITLE
How to load model in the tutorial Text Classification Using a Convolutional Neural Network

### ISSUE THREAD

**Issue by yanxu1per** [apache/incubator-mxnet#5411]
There is no model loading and test code in the tutorial, and the way it saves the model seems different with others.
Now I think the API used in the tutorial is kind of outdated.
The nametuple mechanism can be replaced by mod.Module maybe.
Need help thanks:)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
