### ISSUE TITLE
How to share params in a network?

### ISSUE THREAD

**Issue by 501177639** [apache/incubator-mxnet#5412]
Hi,
      If I have a network, I hope some layers in this network can share params, how can I do? Can I just get them the same name?

**Comment by piiswrong** [comment]
pass the same parameter variable to all layers

**Comment by 501177639** [comment]
get it , thank you~

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
