### ISSUE TITLE
Caffe importer fails to resnet-50

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#5416]
Running `convert_model.py` on the ResNet-50 model from [here](http://data.mxnet.io/models/imagenet/test/caffe/) produces an error importing the BatchNorm layers. I do not have Caffe installed, so am using the pure protobuf version of the importer. @nirbenz, @mli 

## Environment info
OSX

MXNet version:
0.9.4
dea87660c9d3b55ccd28a812116c93ca9e5032c2

Protobuf version:
```
>>> google.protobuf.__version__
'3.0.0'
```

Python version:
3.5

## Error Message:
```
converting layer conv1, wmat shape = (64, 3, 7, 7), bias shape = (64,)
Traceback (most recent call last):
  File "convert_model.py", line 162, in <module>
    main()
  File "convert_model.py", line 158, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "convert_model.py", line 127, in convert_model
    mean = mean.reshape(aux_shape_dic[mean_name])
AttributeError: 'RepeatedScalarFieldContainer' object has no attribute 'reshape'

**Comment by nirbenz** [comment]
Okay I noticed you linked to the source prototxt. That's the same one I was testing against so it should work with Caffe installed. It seems that there are fields missing in the included protobuf.

**Comment by mli** [comment]
this is a known bug. the current version only works with caffe installed for resnet.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
