### ISSUE TITLE
Training faster-rcnn use resnet

### ISSUE THREAD

**Issue by abner2015** [apache/incubator-mxnet#5421]
when i used resnet trained faster-rcnn it had a good trained result but the test is poor.
cmd : bash example/rcnn/script/resnet_voc07.sh 0
After trained, i test the dataset that used trained  i found that the result is error, all of the result is wrong.
who can help me ?
Or, tell me your idea!
thanks !

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
