### ISSUE TITLE
Cannot resume training while using adam optimizer

### ISSUE THREAD

**Issue by chenxu31** [apache/incubator-mxnet#5428]
I trained a neural network using adam optimizer. When I tryed to resume training the neural network from checkpoint using mxnet.module.Module.load with load_optimizer_states=True, an error occurred:
```
[15:33:55] E:\mxnet\dmlc-core\include\dmlc/logging.h:300: [15:33:55] e:\mxnet\include\mxnet\./tensor_blob.h:160: Check failed: Device::kDevMask == dev_mask_ TBlob.get: device type do not match specified type
[15:33:56] E:\mxnet\dmlc-core\include\dmlc/logging.h:300: [15:33:56] e:\mxnet\src\engine\./threaded_engine.h:336: [15:33:55] e:\mxnet\include\mxnet\./tensor_blob.h:160: Check failed: Device::kDevMask == dev_mask_ TBlob.get: device type do not match specified type
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
```

This is because when we load optimizer states, the states of adam optimizer recovered by pickle.loads sit on the device CPU, which is different from the weight of module (commonly sitting on device GPU). Thus when adam_update is called, the error occured.

**Comment by piiswrong** [comment]
Would you like to try fixing it?
You can probably fix it by copying state to the same context as weight in updater

**Comment by chenxu31** [comment]
I tryed to fix it by modifying optimizer.py.Updater.__call__(...) as following:
```python
def __call__(self, index, grad, weight):
    """Update weight given gradient and index"""
    if index not in self.states:
        self.states[index] = self.optimizer.create_state(index, weight)
    ####---- what I added
    else:
        if weight.context != self.states[index][0].context:
            self.states[index] = tuple([x.copyto(weight.context) for x in self.states[index]])
    ####----
    self.optimizer.update(index, weight, grad, self.states[index])
```

But I'm not sure whether it is a suitable solution.

**Comment by piiswrong** [comment]
Generally good. But states can be empty or contain things that are not ndarray. So you should check for that.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
