### ISSUE TITLE
Predicting with mx.io.ImageRecordIter object returns different size vector each time is run

### ISSUE THREAD

**Issue by CarlosUziel** [apache/incubator-mxnet#5432]
Hi,

I'm training a CNN using mx.io.ImageRecordIter objects as input during training and also for predicting purposes. However, I've come across a weird behavior when calling the predict() function. Each time is run, this function returns a vector of predicted values always less than or equal to the original number of images in the test image iterator.

After a while trying to solve this problem, I've realized that every time predict() is called, the size of the returned vector is always increased by the same amount, until it reaches or exceeds the original size and then starts again. For example, if the test image iterator contains 194 images, predict() calls initially return 132, then 138, 144... all the way to 192, and then starts again from 132.

Another discovery was that during execution time, running predict() more than once didn't change the vector size in the same way. Although it's still the wrong size (different from the original one), consecutive calls to predict() return the same size for a while, then for a short period of time it increases in the same amount it did in the first place, and then returns the initial wrong size. For example, it prints 132 for a while, then 138, 144, 150, 156 and then 132 again for a while. It does not always reach 156 or more, sometimes it pops a small size, like 144, and then starts returning 132 again.

However, if I do Sys.sleep(0.01) after each predict() run during execution time, apparently it allows enough time for the program (or whatever being is responsible for this) to advance in the returned size, which means that it doesn't get stuck in 132, but goes all the way from 132 to 192 (the limit for steps of size 6 each). I came up with this solution after realizing that when the execution was paused in debug mode using browser() with Rstudio, the vector sizes changed in a constant way after each call of the predict() function.

The following is my code for creating the image iterator, pretty standard. I'm also including the workaround I'm currently using to face this problem.

```R
  data.iterator <- mx.io.ImageRecordIter(
      path.imgrec             = sprintf("%s_%s.rec", name, dataset.type),
      path.imglist            = sprintf("%s_%s.lst", name, dataset.type),
      batch.size              = iterator.batch.size,
      data.shape              = c(image.size, image.size, 1),
      mean.img                = "mean.bin"
  )
```

```R
GetPrediction <- function(model, test.iterator){
  # Predict labels
  return(predict(model, test.iterator, mx.gpu(0)))
}

# get predicted values
# bug workaround (predicted size is not coherent)
repeat{
  predicted <- GetPrediction(model, model.sets$test.iterator)
  Sys.sleep(0.01)
  if(length(predicted) > length(model.sets$test.label) * 0.98){
    break
  }
}
```

As a side note, I'm using Ubuntu 16.04 with CUDA support. MXNET version is 0.9.3, but this has also happened to me in version 0.7.

If you need any other information, please do not hesitate to ask.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by uran209** [comment]
I have the same problem of "Predicting with mx.io.ImageRecordIter object returns different size vector".
Could you give me some helps if you had solved this? Thanks in advance.
