### ISSUE TITLE
mxnet.rnn.BucketSentenceIter has bug

### ISSUE THREAD

**Issue by hyxie6** [apache/incubator-mxnet#5433]
suppose we have sentences with length [11, 12, 13, 14, 19], all <= 20, 
and we provide two bucket keys [30, 40], 
after we call mxnet.rnn.BucketSentenceIter will raise an

> IndexError: too many indices for array

this happens with the following program statement,
`label[:, :-1] = buck[:, 1:]`

because bucket with key 40 is empty
one possible solution is to add the following program statement after line 104
`self.data = [i for i in self.data if i]`

**Comment by piiswrong** [comment]
Yes. Would you like to submit a PR?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by wcollins-ebsco** [comment]
I'm trying to follow the code example in https://github.com/apache/incubator-mxnet/blob/master/example/rnn/lstm_bucketing.py and I get this error also.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
