### ISSUE TITLE
Make it easier to save test and validation error

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#5436]
I think it would be nice to make easier to get the test and validation error when using the Module API.

Right now you have to go through a convoluted process of using eval_end_callback and batch_end_callback and collapsing the batches so they match epochs. (Please correct me if there's an easier way to do this).

The goal would be to have a boolean toogle for the Module API which will record the train and validation error  or have an specific callback that does this.

**Comment by larroy** [comment]
I will send a patch with a new callback in the Module API to pass the eval metric for train and validation per epoch, any inconvenients with this approach?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
