### ISSUE TITLE
[Distributed Training]Tuning frequency of parameter synchronization?

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#5446]
Hi!

In distributed training, is there a knob to tune the frequency of parameter synchronization? Can I synchronize every 10 batches instead of one?

(Need this for experimental purposes)

Thanks! :)

**Comment by piiswrong** [comment]
Isn't it equivalent to make batchsize 10x larger?

**Comment by Luo-Liang** [comment]
That's right, but performance wise they are not equal :(

**Comment by piiswrong** [comment]
you can bind executor for grad_req='add' and do forward_backward() 10 times before update

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
