### ISSUE TITLE
Can I speak chinese here?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#5447]
\>_<

**Comment by tornadomeet** [comment]
you'd better speak english here:)

**Comment by ysh329** [comment]
hahaha, you'd better speak english. In that way, your questions may help other guys all over the world.

**Comment by leezu** [comment]
As a Chinese learner I would encourage you to add a Chinese translation to your English questions^^ I guess that would be helpful to learn some computer related jargon ;)

**Comment by lilhope** [comment]
因吹斯汀～

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
