### ISSUE TITLE
how to limit threads number in windows

### ISSUE THREAD

**Issue by cjfan** [apache/incubator-mxnet#5449]
When training with cpu mode, openmp will create multi threads.
but toward some very small net model, the performance of using multi threads is not better or even worse.
In linux, by set the enviorment  variable OMP_NUM_THREADS = 1,
the threads number can be limited. but in windows, it doesn't work.
I have tried some other enviorment varable:
OPENBLAS_NUM_THREADS
MXNET_CPU_WORKER_NTHREADS
MXNET_CPU_PRIORITY_NTHREADS
but the result is same.
dose any one have some suggestion?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
