### ISSUE TITLE
When executing "train_mnist.py" with two machines, no response returns

### ISSUE THREAD

**Issue by Y-Ymb** [apache/incubator-mxnet#5452]
I want to run the "train_mnist.py" on multi-machines.
I run the command as follow, however, no responses return.

[user@machineA image-classification]$  ../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet python train_mnist.py --network mlp --kv-store dist_sync

-----
2017-03-18 03:16:32,929 INFO rsync /home/user/mxnet/example/image-classification/ -> user@machineB:/tmp/mxnet
[03:16:33] src/van.cc:75: Bind to role=scheduler, id=1, ip=machineA's IP address, port=9094, is_recovery=0
-----

When input machineA's IP address  into "hosts" instead of machineB's IP address  and execute it, it executed correctly.
And I already set up ssh environment, so I can't guess the cause of this situation.

Please help me how I can run it on multi-machines 
thanks.

  
## Environment info
Operating System: CentOS7.3.1611

Package used (Python/R/Scala/Julia):Python

MXNet version: 0.9.4

Python version and distribution: Python 2.7.5

**Comment by idealboy** [comment]
it is probably because of the firewall in the machine, try to close it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
