### ISSUE TITLE
rename  mx.metric.Torch to mx.metric.Custom

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#5453]
Minor refactor of mx.metric.Torch to rename it to custom metric. When you provide a custom loss function, often you will want a custom evaluation metric. Torch is not a very good name. (For example when using MakeLoss to minimize log likelihood.)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
