### ISSUE TITLE
Refactor 'softmax_label' to 'label'

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#5455]
softmax_label is not really a good default name, many times you are not doing softmax. I think 'label' would be a better default name. This proposed refactor would change the default values of 'softmax_label' to 'label'.

**Comment by piiswrong** [comment]
We are refactoring to remove label_names entirely: https://github.com/dmlc/mxnet/tree/loss

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
