### ISSUE TITLE
follow mnist tutorial but cannot get result

### ISSUE THREAD

**Issue by jamestang0219** [apache/incubator-mxnet#5456]
Hi, I'm a beginner of mxnet. I follow the mnist tutorial but get some Error, here are errors:
```
Traceback (most recent call last):
  File "mnist_mx.py", line 64, in <module>
    main(os.sys.argv)
  File "mnist_mx.py", line 60, in main
    res = mod.predict(valid_image[0:1].astype(np.float32)/255)[0]
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/base_module.py", line 338, in predict
    eval_data.reset()
AttributeError: 'numpy.ndarray' object has no attribute 'reset'
```
I wanna know is the tutorial out-of-date? I just followed the tutorial.
I'm also confused about the input of mxnet. Whatever I wanna train or predict, I have to use data_iterator? I cannot directly use np.ndarray or mx.ndarray as the input just like the feeder of tensorflow?
Last question, in python api, how the model can connect the input data with the symbol placeholder? just using data_names and label_names?
Thank you all.

**Comment by matt32106** [comment]
Maybe this page help?
http://mxnet.io/tutorials/python/symbol.html

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by Jing-Luo** [comment]
I met with the same problem today. You can try to make a copy of the prediction result.
`plt.imshow((X_show[0].reshape((28,28))*255).astype(np.uint8), cmap='Greys_r')
plt.show()
prediction = mod.predict(test_iter, num_batch=1)[0]
print('Result:', type(prediction), prediction)
z = prediction.asnumpy()
print(z.argmax())`
