### ISSUE TITLE
recommend to use 0 as default value for mxnet.rnn.BucketSentenceIter's variable invalid_label instead of -1

### ISSUE THREAD

**Issue by hyxie6** [apache/incubator-mxnet#5457]
In file [mxnet/python/mxnet/rnn/io.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/rnn/io.py#L86)
line 86, the default value of invalid label is defined -1
however, if we use this default value, [cudnn_lstm_bucketing.py](https://github.com/dmlc/mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py) cannot run.

refers to the document of [mxnet.symbol.Embedding](http://mxnet.io/api/python/symbol.html#mxnet.symbol.Embedding) which requires all the input values should be integers in the range [0, input_dim).

setting the default value of invalid_label to be -1 is very dangerous since many nlp applications apply RNN and mxnet.symbol.Embedding layer together
I recommend to use 0 as default value

**Comment by piiswrong** [comment]
@ap-hynninen Can we modify embedding to ignore out of range labels or clip them to range?

**Comment by ap-hynninen** [comment]
It should be doable. I'll look into this.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
