### ISSUE TITLE
How to see C++ function invocations behind the SWIG interface, mxnet

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-mxnet#5465]
https://github.com/rmekdma/python_misc/blob/master/caffe/caffe_ftr.py

I need to do some system integration in C++(has to be). Given the above caffe code,

What is the python wrapper used by mxnet? swig?

Similarly, it will be interesting to know whether I can do the same from python to c++ in **mxnet** or other python binding code, if it is easier to do it than caffe.

Here is a sister problem in tensorflow:

http://stackoverflow.com/questions/41210347/how-to-see-c-function-invocations-behind-the-swig-interface-tensorflow?s=1|4.7945

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
