### ISSUE TITLE
[DOC] Stale documentations and doc versions

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#5468]
Many sections in the documentation are either 
1. stale (e.g. http://mxnet.io/architecture/overview.html#operators-in-mxnet), or
2. provide deprecated/broken examples

For (1), I suggest that we maintain versioned documentations with release tags. (Even a simple "last updated" timestamp would help)

For (2), we need broader testing coverage. #5321

**Comment by matt32106** [comment]
Same for examples scripts, i have seen several examples  that do not work out of the box (wrong args called, changed names, missing files) or need to follow some documentation that is not mentioned in the file.
