### ISSUE TITLE
Can tensorflow model convert to MXNet model?

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#5469]

**Comment by lilhope** [comment]
I‘m not sure,but if tensorflow model can convert to numpy. I think you can convert numpy to mxnet model.

**Comment by ysh329** [comment]
ysh329/deep-learning-model-convertor: The convertor/conversion of deep learning models for different deep learning frameworks/softwares.
https://github.com/ysh329/deep-learning-model-convertor
