### ISSUE TITLE
Difference between ImageIter  and ImageRecordIter

### ISSUE THREAD

**Issue by littlelid** [apache/incubator-mxnet#5475]
I feed same train.lst and train.rec to ImageIter ImageRecordIter,

val = mx.io.ImageRecordIter(
      ......
      batch_size          = batch_size,
      data_shape          = (3, 224, 224),
      label_width          = 2,
      rand_crop           = True,
      rand_mirror         = True)

val = mx.img.ImageIter(
    ......
    batch_size          = batch_size,
    data_shape          = (3, 224, 224),
    label_width          = 2,
    rand_crop           = True ,
    rand_mirror         = True)

But Evalutation genetated from ImageRecordIter is extremly better.
I curious about what preprocess ImageRecordIter is doing on  a raw image

**Comment by melody-rain** [comment]
I got the similar issue. Have you found any clues?

**Comment by anxiaoxi45** [comment]
@mli @piiswrong @tqchen This seems like a bug.............

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@nswamy Please add 'Bug', 'Python' to this topic

**Comment by vandanavk** [comment]
@littlelid @melody-rain have you had a chance to try this out on a recent version?
its been a long time, but do you have the dataset/script that you used when you saw the issue?

**Comment by Roshrini** [comment]
@littlelid Its difficult to reproduce this issue with little information provided. I tried to reproduce this issue on Caltech dataset. Was not able to do it. Referred: 
https://mxnet.incubator.apache.org/tutorials/basic/data.html#using-imagerecorditer

Didn't see any difference between images generated by ImageRecordIter and ImageIter
Used resnet 50 model for inference. Didn't see any major accuracy difference.

I will be closing this issue for now. Please reopen if closed in error or if issue still persists. Please provide script with which you saw this difference.

@sandeep-krishnamurthy Can you please close this issue? Thanks!
