### ISSUE TITLE
Linux Install MXNet

### ISSUE THREAD

**Issue by ly-atdawn** [apache/incubator-mxnet#5484]
In Non root user，after I configured the config.mk，then make -j12. But  I get the following class of error:

In file included from /home/jlu_guan/gcc-4.9.4/gcc_compile/include/c++/4.9.4/random:42:0,
                 from /home/jlu_guan/gcc-4.9.4/gcc_compile/include/c++/4.9.4/bits/stl_algo.h:66,
                 from /home/jlu_guan/gcc-4.9.4/gcc_compile/include/c++/4.9.4/algorithm:62,
                 from /home/jlu_guan/MXNet/dmlc-core/include/dmlc/json.h:15,
                 from src/operator/mkl/../operator_common.h:11,
                 from src/operator/mkl/mkl_memory.cc:22:
/home/jlu_guan/gcc-4.9.4/gcc_compile/include/c++/4.9.4/limits:1558:7: **internal compiler error: Illegal instruction**
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
       ^
In file included from /home/jlu_guan/MXNet/dmlc-core/include/dmlc/./parameter.h:12:0,
                 from /home/jlu_guan/MXNet/dmlc-core/include/dmlc/registry.h:14,
                 from include/mxnet/operator_util.h:18,
                 from src/operator/tensor/./broadcast_reduce_op.h:9,
                 from src/operator/tensor/broadcast_reduce_op_value.cc:6:
/home/jlu_guan/gcc-4.9.4/gcc_compile/include/c++/4.9.4/limits:1558:7: **internal compiler error: Illegal instruction**
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
...............................................................

**Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.**

I have no idea what it means. What is to be done about this?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
