### ISSUE TITLE
[WIP] RNN with bucketing and mask - R package

### ISSUE THREAD

**Issue by jeremiedb** [apache/incubator-mxnet#5488]
Since there wasn't an API yet for bucketing and masking in the R-package, I started building some functionnalities to address this. Inference from iterator is also provided. Further work remains to render the interface more flexible to different structures (seq-to-seq vs. seq-to-single used to demo). I've tried to stay as close as possible to the current `model.R` for standard feedforward training. 

I've detailed the approach and put the code here: 
https://github.com/jeremiedb/mxnet_R_bucketing

I was wondering if there were already plans to develop bucketing utilities in the R package. If not, would you see this approach as a decent one it and worth buildind further on it?

There are some specificities with how I dealt with the iterarators, it assumes that a pre-processing is performed to put the data and label arrays in lists for each bucket. Also noticed that shared module options seems not supported in the `symbol_bind` operator, not sure if this may result in memory management issues. 

In any case I can turn it into an example to add to the docs. CNN examples reaches 89% accuracy on IMDB sentiment in few minutes on laptop CPU.

**Comment by piiswrong** [comment]
@thirdwing

**Comment by thirdwing** [comment]
@jeremiedb Really thank you for this.

Sorry that I am occupied by thesis right now.

**Comment by thirdwing** [comment]
@jeremiedb The first version of refactor can be found in https://github.com/thirdwing/mxnet/tree/r_rnn_refactor1

**Comment by thirdwing** [comment]
The RNN bucketing example has been added into https://github.com/apache/incubator-mxnet/tree/master/example/rnn/bucket_R
