### ISSUE TITLE
Installation problem on Mac 10.11.6 El Capitan 

### ISSUE THREAD

**Issue by pchankh** [apache/incubator-mxnet#5491]
Have anyone been successful compiling and installing mxnet on Mac 10.11.6 El Capitan OSX,
using CUDA 8.0 libraries?
Been facing a lot of issues 
1) openmp not supported (tried installing latest clang and it results in nvcc error saying 40000 not supported.
2) changed clang to gcc4.8 and 6.2 and nvcc complains 
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.
Appreciate any advice
Patrick

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
