### ISSUE TITLE
Take up too much GPU memory

### ISSUE THREAD

**Issue by dovanchan** [apache/incubator-mxnet#5494]
Neural-style python2.7 ubuntu ,with GPU0 . when training ,is about 1.8G GPU memory took up;
(with the default parameters)
So,what things can I do to reduce the GPU memory . ?

**Comment by sxjscience** [comment]
Try to set `MXNET_BACKWARD_DO_MIRROR` to 1. https://github.com/dmlc/mxnet/blob/2413a8ed421b5a917eed544b08d434839b8c812d/docs/how_to/env_var.md

**Comment by dovanchan** [comment]
Can I change the optimizer to Adam?  How can I do that in mxnet.when i use MXNET_BACKWARD_DO_MIRROR,It still need 1.7G GPUmemory. (but in tensorflow just 1.0G)~thanks

**Comment by mcxkarakoc** [comment]
.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
