### ISSUE TITLE
CUDA: unknown error

### ISSUE THREAD

**Issue by mlWill** [apache/incubator-mxnet#5495]
Hey guys, 

I am trying to use the mxnet lib in R and python using my old laptop.
**OS**: Ubuntu 14.04LTE
**Graphics:**
$lspci | grep VGA;
```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09);
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GTX 660M] (rev a1)
```
**MXNet version**: 5450
**CUDA**: MXNet version: 

I tried to run the sample provided in [here](http://firsttimeprogrammer.blogspot.co.at/2016/08/image-recognition-tutorial-in-r-using.html). To do so, I followed the installation guide [here](http://mxnet.io/get_started/ubuntu_setup.html#prepare-environment-for-gpu-installation). After that, the sample runs. But if I change the device in my R Code to
`n.gpu <- 1;
devicesGPU <- lapply(0:(n.gpu-1), function(i) { mx.gpu(i)})`
I get an error in my training line:
```
model2 <- mx.model.FeedForward.create(NN_model, 
                                      X=train_array, 
                                      y=train_y,
                                      ctx=devicesGPU, 
                                      num.round=5, 
                                      array.batch.size=100,
                                     learning.rate=0.05, 
                                     momentum=0.9, 
                                     wd=0.00001,
                                     eval.metric=mx.metric.accuracy,
                                     epoch.end.callback=mx.callback.log.train.metric(100))
```
The error is
`Start training with 1 devices
[14:38:03] /home/wilfried/mxnet/dmlc-core/include/dmlc/./logging.h:300: [14:38:03] src/storage/storage.cc:37: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error

Stack trace returned 10 entries:
[bt] (0) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f0c8419d5dc]
[bt] (1) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN5mxnet11StorageImpl14ActivateDeviceENS_7ContextE+0x2f3) [0x7f0c84d8f9c3]
[bt] (2) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN5mxnet11StorageImpl5AllocEmNS_7ContextE+0x4a) [0x7f0c84d8beba]
[bt] (3) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(MXNDArrayCreate+0x58d) [0x7f0c849ef63d]
[bt] (4) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/mxnet.so(_ZN5mxnet1R7NDArray5EmptyERKN4Rcpp9DimensionERKNS2_6VectorILi19ENS2_15PreserveStorageEEE+0xdd) [0x7f0c67e78d4d]
[bt] (5) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/mxnet.so(_ZN4Rcpp12CppFunction2INS_4XPtrIN5mxnet1R6NDBlobENS_15PreserveStorageEXadL_ZNS_25standard_delete_finalizerIS4_EEvPT_EELb0EEERKNS_9DimensionERKNS_6VectorILi19ES5_EEEclEPP7SEXPREC+0xd2) [0x7f0c67e856e2]
[bt] (6) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/libs/Rcpp.so(_Z23InternalFunction_invokeP7SEXPREC+0xd1) [0x7f0c91703d51]
[bt] (7) /usr/lib/R/lib/libR.so(+0xce3c1) [0x7f0cb3ae03c1]
[bt] (8) /usr/lib/R/lib/libR.so(Rf_eval+0x6fb) [0x7f0cb3b255ab]
[bt] (9) /usr/lib/R/lib/libR.so(+0x1158b0) [0x7f0cb3b278b0]

Fehler in mx.nd.internal.empty.array(shape, ctx) : 
  [14:38:03] src/storage/storage.cc:37: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error

Stack trace returned 10 entries:
[bt] (0) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f0c8419d5dc]
[bt] (1) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN5mxnet11StorageImpl14ActivateDeviceENS_7ContextE+0x2f3) [0x7f0c84d8f9c3]
[bt] (2) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(_ZN5mxnet11StorageImpl5AllocEmNS_7ContextE+0x4a) [0x7f0c84d8beba]
[bt] (3) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/libmxnet.so(MXNDArrayCreate+0x58d) [0x7f0c849ef63d]
[bt] (4) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/mxnet.so(_ZN5mxnet1R7NDArray5EmptyERKN4Rcpp9DimensionERKNS2_6VectorILi19ENS2_15PreserveStorageEEE+0xdd) [0x7f0c67e78d4d]
[bt] (5) /home/wilfried/R/x86_64-pc-linux-gnu-library/3.3/mxnet/libs/mxnet.so(_ZN4Rc`

Unfortunately, I am right now out of ideas... I already checked all paths and permissions. I installed cuda to /usr/local/cuda/bin.
Any ideas?

All the best from Austria!
Will

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
