### ISSUE TITLE
_set_attr() needs to be public (or list_attr needs to be private)

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#5500]
Right now _set_attr() is a private function. But list_attr() is public. So basically if the user can't set the attributes, then list_attr() will always return `{}`. 

They should either both be public or both be private.

(in symbol.py)

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
yes it should be public

**Comment by tqchen** [comment]
The original intention was only set attributes at symbol creation time, so the graph is immutable object

**Comment by piiswrong** [comment]
it's sometimes useful to set __xxx__ attributes. but I guess those are considered hidden.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
