### ISSUE TITLE
Segfault when changing the name of a variable (& other madness)

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#5501]
There are some serious issues with how the names of variables are implemented.
1) Names are attributes
2) Names can be manually set, e.g. a._set_attr(name="a")
3) Names do not show up in the attributes returned by list_attr().

I understand that having the name appear as an attribute makes the recursive call attr_dict() a little bit less pretty, but otherwise anyone trying to understand what these functions do will be confused.

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
