### ISSUE TITLE
Build from source with GPU supported ended with "cannot find -lopencv_imgcodecs"

### ISSUE THREAD

**Issue by chenzhuo8804** [apache/incubator-mxnet#5502]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Compiler: g++

MXNet commit hash 2e4be17a014bb5315c18a8fc974fd0c7754081be

## Error Message:
Hi, I tried to build from source with GPU support on Ubuntu but got following error message
/usr/bin/ld: cannot find -lopencv_imgcodecs

## What have you tried to solve it?
I googled and found that -lopencv_imgcodecs is available from opencv 3.0 but "apt-get install libopencv-dev" will only install open 2.4.9, could this be the issue?

**Comment by piiswrong** [comment]
try pip install mxnet-cu75 or pip install mxnet-cu80 depending on your cuda sdk version

**Comment by chenzhuo8804** [comment]
The issue happens when I build mxnet from source

**Comment by chenzhuo8804** [comment]
Hi
pip install mxnet-cu75/80 will install mxnet on my machine, this bugs actually happens when I build mxnet from source

**Comment by reminisce** [comment]
In my case, removing this linking flag works. I think this flag should only be used with opencv of version 3.0.

**Comment by chenzhuo8804** [comment]
yeah my solution was to remove this flag, but we should also remove it from the setup instruction here? http://mxnet.io/get_started/ubuntu_setup.html

**Comment by praveen7728** [comment]
I am facing the same problem. Can you let me know how to remove the linking flag?

**Comment by eric-haibin-lin** [comment]
If you don't need open cv, set USE_OPENCV=0 in your configure.mk

**Comment by szha** [comment]
If you use OpenCV2.4, change `-lopencv_imgcodecs` to `-lopencv_highgui` instead (and you will probably need to suffer through installing all the dependencies required by opencv UIs...)
