### ISSUE TITLE
SliceChannel only supports 'float32' data type

### ISSUE THREAD

**Issue by bikestra** [apache/incubator-mxnet#5504]
It seems like SliceChannel only supports 'float32' data type. Is it really the case? Since this is such a generic operator, I would expect it to support every data type. I can work around this problem by casting before and after SliceChannel(), but I hope there is a better way.

On a side note: When throwing the data type error in include/mxnet/operator.h:267 , it should be better to (also) print type names ('int32', 'float64', ...) instead of type indices (0, 1, 2, 3, ...).

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04.5 LTS

Compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Package used (Python/R/Scala/Julia): Python

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): dc47e06f6f05adf08050fb62b8e9d855f94422bf

If you are using python package, please provide

Python version and distribution: Python 2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

```bash
/efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/dmlc-core/include/dmlc/./logging.h:300: [04:57:38] include/mxnet/operator.h:267: Check failed: in_type->at(i) == mshadow::default_
type_flag || in_type->at(i) == -1 Unsupported data type 4

Stack trace returned 10 entries:
[bt] (0) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd8f4f0536c]
[bt] (1) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet16OperatorProperty9InferTypeEPSt6vectorIiSaIiEES4_S4_+0x327) [0x7fd8f58b3d57]
[bt] (2) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(+0xfd63a6) [0x7fd8f58973a6]
[bt] (3) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(+0x1d3d24c) [0x7fd8f65fe24c]
[bt] (4) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(+0x1d3e48a) [0x7fd8f65ff48a]
[bt] (5) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(+0x1d3ed96) [0x7fd8f65ffd96]
[bt] (6) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7fd8f65ed158]
[bt] (7) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7fd8f5790dee]
[bt] (8) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass9InferTypeENS_5GraphESt6vectorIiSaIiEESs+0x240) [0x7fd8f57947a0]
[bt] (9) /efs/datasets/users/yunhyoku/code/workplace/yunhyoku/mxnet-withoutmkl/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor9InitGraphEN4nnvm6SymbolERKNS_7ContextERKSt3mapISsS4_St4lessISsESaISt4pairIKSsS4_EEER
KSt6vectorINS_7NDArrayESaISI_EESM_RKSH_INS_9OpReqTypeESaISN_EESM_+0xc2c) [0x7fd8f57d1b6c]
```

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

```python
import mxnet as mx

def test_slicechannel():
    data = mx.sym.Variable('data')
    target = mx.sym.SliceChannel(data, num_outputs=3)
    executor = target[0].bind(mx.cpu(),
                              {
                                  'data': mx.nd.array([[0, 1, 0], [1, 1, 0]], dtype='int32')
                              })
    executor.forward()
```

**Comment by piiswrong** [comment]
yes this should be fixed. @reminisce Could you do it?

**Comment by reminisce** [comment]
@piiswrong Yes, I can fix it. Will submit a PR later.

**Comment by reminisce** [comment]
PR submitted. https://github.com/dmlc/mxnet/pull/5558

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
