### ISSUE TITLE
How can I scale/resize the rec format data (cifar-10) before train?

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#5506]

**Comment by louiskoo520** [comment]
what error?

**Comment by ysh329** [comment]
@louiskoo520 
I want to train a network with 80*80 input shape based on cifar-10 data set. However, the size of single cifar-10 image is 32*32, not 80*80. besides, cifar-10 data set is rec format. 

How can I resize rec format data? Thanks!

**Comment by ysh329** [comment]
It seems can't resize rec format image data before training.
