### ISSUE TITLE
Getting Nan and inf in the output of MLP.

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#5516]
Hi all,

I am using EC2 Ubuntu and python. When I ran the train_mnist.py on distributed environment ( 3 workers and 1 server ) I got the nan and inf as output from activation layer and fully connected layer. I show a sample of my output below. I hope someone has an answer.
`
INFO:root:Batch:    1131 relu1_backward_data            nan	
INFO:root:Batch:    1131 fc1_backward_data              nan	
INFO:root:Batch:    1131 fc3_backward_weight            nan	
INFO:root:Batch:    1131 fc1_backward_bias              nan	
INFO:root:Batch:    1131 fc3_backward_bias              nan	
INFO:root:Batch:    1131 data                           0.32695	
INFO:root:Batch:    1131 fc1_backward_weight            nan	
INFO:root:Batch:    1131 relu2_backward_data            nan	
INFO:root:Batch:    1131 fc1_backward_bias              nan	
INFO:root:Batch:    1131 fc1_weight                     nan	
INFO:root:Batch:    1131 fc2_backward_data              nan	
INFO:root:Batch:    1131 data                           0.334415	
INFO:root:Batch:    1131 fc1_bias                       nan	
INFO:root:Batch:    1131 fc2_backward_weight            nan	
INFO:root:Batch:    1131 fc2_weight                     nan	
INFO:root:Batch:    1131 fc1_weight                     nan	
INFO:root:Batch:    1131 fc2_backward_bias              nan	
INFO:root:Batch:    1131 fc1_bias                       nan	
INFO:root:Batch:    1131 fc2_bias                       nan	
INFO:root:Batch:    1131 relu1_backward_data            nan	
INFO:root:Batch:    1131 fc3_weight                     nan	
INFO:root:Batch:    1131 fc2_weight                     nan	
INFO:root:Batch:    1131 fc1_backward_data              nan	
INFO:root:Batch:    1131 fc3_bias                       nan	
INFO:root:Batch:    1131 fc2_bias                       nan	
INFO:root:Batch:    1131 fc1_backward_weight            nan	
INFO:root:Batch:    1131 softmax_label                  5.30585	
INFO:root:Batch:    1131 fc1_backward_bias              nan	
INFO:root:Batch:    1131 fc3_weight                     nan	
INFO:root:Batch:    1131 data                           0.337408	
INFO:root:Batch:    1131 fc3_bias                       nan	
INFO:root:Batch:    1131 fc1_weight                     nan	
INFO:root:Batch:    1131 softmax_label                  5.24767	
INFO:root:Batch:    1131 fc1_bias                       nan	
INFO:root:Batch:    1131 fc2_weight                     nan	
INFO:root:Batch:    1131 fc2_bias                       nan	
INFO:root:Batch:    1131 fc3_weight                     nan	
INFO:root:Batch:    1131 fc3_bias                       nan	
INFO:root:Batch:    1131 softmax_label                  5.40555`

**Comment by salemmohammed** [comment]
@winstywang

**Comment by ysh329** [comment]
Can you show complete code, detail enviroment info?

**Comment by mcxkarakoc** [comment]
.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
