### ISSUE TITLE
RMSProp not converging

### ISSUE THREAD

**Issue by rcapobianco** [apache/incubator-mxnet#5517]
Hi,
I updated mxnet last friday (March 17th) and I saw there have been major changes in the RMSProp implementation. I have set the parameters (centered=True, gamma1=0.95) to the values they had before the update, but I'm not able to get the same network I was using to converge as it did before the update.

Any ideas on what might be the reason?

**Comment by piiswrong** [comment]
@sxjscience I think the original implementation had bugs.

**Comment by sxjscience** [comment]
@rcapobianco I think you can try to train the network with (centered=False, gamma1=0.95). The original implementation of RMSProp has some bugs and we've fixed it.
