### ISSUE TITLE
question about random crop in ImageRecordIter

### ISSUE THREAD

**Issue by qz28** [apache/incubator-mxnet#5520]
If I set this rand_crop augmentation parameter in ImageRecordIter to be true, does that mean the ImageRecordIter will always crop a random part from each of my images and feed it to my model? I also notice there are two parameters called max_crop_size and min_crop_size, I believe that these two parameters will ensure the sizes of the random cropped parts are in [min_crop_size, max_crop_size]. But what does the default setting mean? Does it mean it will crop any size that is smaller than the original if I don't set max_crop_size and min_crop_size?  

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
