### ISSUE TITLE
amalgamation android compile error

### ISSUE THREAD

**Issue by sun9700** [apache/incubator-mxnet#5524]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04
Compiler: NDK r14, linux-androideabi-clang
MXNet version:0.9.3, latest source
MXNet commit hash (`git rev-parse HEAD`): 5e9e3d0949cb8051da61ef49339541b5e6f69c03

## Steps to reproduce
export CC=arm-linux-androideabi-clang  
export CXX=arm-linux-androideabi-clang++  
export NDK_ROOT=/home/sun/Android/ndk
export SYS_ROOT=${NDK_ROOT}/sysroot
export INCLUDE=${NDK_ROOT}/include/c++/4.9.x
ifndef OPENBLAS_ROOT
    export OPENBLAS_ROOT=/home/sun/Android/openblas_armv7
endif

make clean 
make ANDROID=1
## Error Message:
1.
/home/sun/Android/mxnet/amalgamation/../dmlc-core/include/dmlc/./logging.h:18:10: fatal error: 
      'execinfo.h' file not found
#include <execinfo.h>
sloved by comment include <execinfo.h> out
2.
jni/../mxnet_predict-all.cc:7649:13: error: use of undeclared identifier 'fopen64'; did you mean 'fopen'?
      fp_ = fopen64(fname, "rb");
sloved by replace fopen64 with fopen in line 2805 and 7649 of mxnet_predict-all.cc

The amalgamation seems stop updating for a year. Is there any other solution for mxnet in android?

**Comment by piiswrong** [comment]
@arank

**Comment by arank** [comment]
I have solved this issue in a similar manner but but android is still not compiling due to an issue in the NDK toolchain. I am working on a fix

**Comment by sun9700** [comment]
@piiswrong many examples are out of date, like kaggle ndsb1 is still using image-classification files in mxnet v0.7, is the example updating in plan? or we submit our patch？

**Comment by ZaccurLi** [comment]
I have achieved to compile mxnet amalgamation for android successfully, and put the steps at #7146 
[How to compile Amalgamation for android?](https://github.com/dmlc/mxnet/issues/7146)
Maybe it can help you,
thanks a lot!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
