### ISSUE TITLE
A issue about Distributed Training with train_mnist

### ISSUE THREAD

**Issue by dushoufu** [apache/incubator-mxnet#5536]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: ubuntu 14.04

Compiler: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

Package used (Python/R/Scala/Julia):
python

MXNet version: V0.7

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python 2.7.6 

## Error Message:
Please paste the full error message, including stack trace.
train_mnist can be laucned in distributed cpus,but it seemed it can not work normally, because the programm do not use the cpu and memory and the logging message can't be seen

## Minimum reproducible example
I use train_mnist to test Distributed Training according to the guide provided at http://mxnet.io/how_to/multi_devices.html.

the steps include:
1.There are two machines in total, each of which has gpus and use ssh service. However, the ssh users are diffrent with these two machines.

2. I installed NFS on the two machines and ensure each of them can access each other. However the mxnet folder on these two machines are different. I used soft link to ensure that one machine can access the mxnet folder of another machine with the same folder path of itself.

3. I run the command python ../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync.
I run this command on machine A with a hosts file,in which I wrote another machine's IP addr like user@10.46.169.115.
On machine A, I was required to input the ssh password of another machine, Although almost every time I must input the password serveral times, the programm fortunately can run finally. 

4. I used "ps -ef" on these two machines and saw "python train_mnist.py" running on the two machines.
But it seemed that python train_mnist.py was blocked and can't run normally with the cpu and memory usage equalling zero. In addition, I also can't see the logging messages when training as local version.

who can tell me what's wrong?

**Comment by mzmssg** [comment]
if you have stop the firewalld and SELinux？

**Comment by dushoufu** [comment]
Thank you! I checked these two ubuntu machines and the ufw are disabled in default.  BTW, Can the fact that I can see the program running on the another machine illustrate the firewall is disabled?  Is there any other data transferred that requires the firewall disabled? 
 Are there any other things I can check?

**Comment by mzmssg** [comment]
MXNET have to synchronize between two machine(default seem to be 9092 port)， so if the firewall is on, the program will run on the workers but can't communicate with each other, it looks like blocked. I am not sure this is your problem.

**Comment by dushoufu** [comment]
But i have verified that the ufw in my ubuntu is disabled. Most importantly, I cannot see some error or any prompt messages, which perplexed me a lot and I don't know where I can start from.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
