### ISSUE TITLE
BatchNorm is not support for 3D? only support 2D?

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5540]
![1](https://cloud.githubusercontent.com/assets/6327360/24242835/06d2481a-0ff4-11e7-9888-07bb20aeb59b.png)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by KnightOfTheMoonlight** [comment]
Hi,3d bn is suported at least in mxnet version 0.12.0
Here is the example code:
```
import mxnet as mx
print(mx.__version__)
data = mx.nd.arange(1029).reshape((3,1,7,7,7)) # NCDHW
data_shape=(3,1,7,7,7)
x = mx.sym.Variable('data')
conv3D = mx.sym.Convolution(data=x, kernel=(3, 3, 3), pad=(2, 2, 2), num_filter=2)
conv3D_bn = mx.sym.BatchNorm(data=conv3D)
conv3D_exe = conv3D.simple_bind(mx.gpu(),data=data.shape)
```
