### ISSUE TITLE
A3C dont have acceleration effect？

### ISSUE THREAD

**Issue by apeng5399** [apache/incubator-mxnet#5541]
I run the A3C(as it in the mxnet sample after fix bug https://github.com/dmlc/mxnet/pull/5473 ) with same parameters. However in aws with 1cpu 32 cores,,I run it with 1cores-1worker,  4cores-4worker, 16cores-16worker, I didn't see any improment, anyone has campare the results under different situation? any advice

**Comment by apeng5399** [comment]
@piiswrong

**Comment by piiswrong** [comment]
operators are already multi threaded and using all 32 cores

**Comment by achao2013** [comment]
the improvement can be revealed  in gpu mode, because the multi-env is build in gpu, i think. you can have a try

**Comment by apeng5399** [comment]
thank you all guys!
1.as limited to the resource, there are only my pc gpu avaliable, besides in the paper，author use cpu with 16cores，see
![image](https://cloud.githubusercontent.com/assets/26270443/24278643/f6ee35c6-107f-11e7-9f71-c62317646b74.png)
2.I try again in the situation first set OMP_NUM_THREADS = 1,witch constrain the process will only have 1 thread, second in rl_data.py I set nthreads = 1, besides i check the cpu  occupation ratio,each python process(worker) enjoy almost same part, still don't any improvement
plus I use the same parameters without any change when the number of workers changes

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
