### ISSUE TITLE
Consideration on applying mask on RNN

### ISSUE THREAD

**Issue by hyxie6** [apache/incubator-mxnet#5546]
at time step t，the lstm network receive previous cell c_t_1 and hidden state h_t_1 and other inputs, then it computes c_t and h_t
suppose mask=0 (out of sequence, keep previous cell and hidden state)
we can perform
 c_t_1 * (1-mask) + c_t * mask 
h_t_1 * (1-mask) +h_t * mask
then we can get what we want
the same formulation can be applied when mask=1

does this operation slow?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
