### ISSUE TITLE
gradient computation support for take() and batch_take()

### ISSUE THREAD

**Issue by bikestra** [apache/incubator-mxnet#5548]
mx.sym.take() and batch_take() do not seem to support gradient computation:

```bash
MXNetError: [17:33:14] include/nnvm/./././op.h:514: Check failed: idx < data_.size() && data_[idx].second Attribute FGradient has not been registered for Operator batch_take
```

In terms of the first argument, however, gradients of these operators should be well defined. Can the support for gradient computation of these operators be added?

@reminisce : I talked with @piiswrong and he said you are the most familiar with these operators. Would you please take a look?

**Comment by reminisce** [comment]
@bikestra I just checked source code.
1. Operator **take** has already supported gradient computation.
2. Operator **batch_take** does not support gradient computation.

We can add the gradient computation for **batch_take**.

Could you please paste your minimum reproducible python script here? Thanks.

**Comment by bikestra** [comment]
Thanks @reminisce ! Sorry for just assuming take() doesn't have gradient support.
Below is the example for computing gradients with batch_take:

```python
def test_batchtake():
    ma = mx.nd.array([[0.3, 2.0],
                      [1.0, 4.0],
                      [5.2, 6.1]])
    mb = mx.nd.array([0, 1, 1], dtype='int32')

    va = mx.sym.Variable('A')
    vb = mx.sym.Variable('B')
    vtake = mx.sym.batch_take(va, vb)
    args_grad = {'A': mx.nd.zeros((3,2))}
    executor = vtake.bind(mx.cpu(),
                          {'A': ma, 'B': mb},
                          args_grad=args_grad)
    print(executor.forward()[0].asnumpy())
    executor.backward(out_grads=mx.nd.ones(3))
    print(args_grad)
```

**Comment by reminisce** [comment]
@bikestra Thanks for the script. I will implement it and let you know once finished.

**Comment by UfukCanBicici** [comment]
Hello, I think this issue is also related with this. Can you look into that as well?

https://github.com/dmlc/mxnet/issues/5668

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
