### ISSUE TITLE
example/ssd error Check failed: op != nullptr Operator MultiBoxPrior is not registered

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#5550]
I use commit e4f73f1f4e76397992c4b0a33c139d52b4b7af0e @zhreshold

**Comment by poorfriend** [comment]
[09:50:38] /home/mxnet/dmlc-core/include/dmlc/./logging.h:300: [09:50:38] src/core/op.cc:55: Check failed: op != nullptr Operator MultiBoxPrior is not registered

Stack trace returned 10 entries:
[bt] (0) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm2Op3GetERKSs+0x369) [0x7f4b63971af9]
[bt] (1) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x1ed8874) [0x7f4b6399d874]
[bt] (2) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x110) [0x7f4b639a24f0]
[bt] (3) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x1ed7682) [0x7f4b6399c682]
[bt] (4) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f4b62b2393f]
[bt] (5) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f4b63975348]
[bt] (6) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x18b) [0x7f4b62b1e5cb]
[bt] (7) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f4b62b2393f]
[bt] (8) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f4b63975348]
[bt] (9) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f4b62a328fe]

Traceback (most recent call last):
  File "demo.py", line 95, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 41, in get_detector
    data_shape, mean_pixels, ctx=ctx)
  File "/home/mxnet/example/ssd/detect/detector.py", line 34, in __init__
    _, args, auxs = mx.model.load_checkpoint(model_prefix, epoch)
  File "/home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/model.py", line 373, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/symbol.py", line 1215, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op relu4_3_anchors of type MultiBoxPrior: [09:50:38] src/core/op.cc:55: Check failed: op != nullptr Operator MultiBoxPrior is not registered

Stack trace returned 10 entries:
[bt] (0) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm2Op3GetERKSs+0x369) [0x7f4b63971af9]
[bt] (1) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x1ed8874) [0x7f4b6399d874]
[bt] (2) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x110) [0x7f4b639a24f0]
[bt] (3) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x1ed7682) [0x7f4b6399c682]
[bt] (4) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f4b62b2393f]
[bt] (5) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f4b63975348]
[bt] (6) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x18b) [0x7f4b62b1e5cb]
[bt] (7) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f4b62b2393f]
[bt] (8) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f4b63975348]
[bt] (9) /home/anaconda2/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f4b62a328fe]

**Comment by zhreshold** [comment]
Plz re-download the model again, due to the previous change to contrib package

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
