### ISSUE TITLE
symbol.bind error

### ISSUE THREAD

**Issue by Kdecem** [apache/incubator-mxnet#5552]
when i use test.py
(https://github.com/tornadomeet/mxnetface/blob/a4ba156c3f65fd1cba67a50b2affd43d7dcb7e7f/verification/lfw.py) 
to test my model, i got the error.  now i have to use cpu, it is too slow.
i train my model with"train_model.fit". Is it save model correctly in version 0.9.3? i mean is it save model with GPU_format？ and when i use  train_model.fit, cmd shows that"
                   mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
"

    now i have to use cpu, it is too slow.
## Environment info
Operating System:unbuntu 14

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.3

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
1.Check failed: x.ctx() == default_ctx Input array is in cpu(0) while binding with ctx=gpu(0). All arguments must be in global context (gpu(0)) unless group2ctx is specified for cross-device graph.
2. warning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.

## Minimum reproducible example

       i use lfw.py to test.    (https://github.com/tornadomeet/mxnetface/blob/a4ba156c3f65fd1cba67a50b2affd43d7dcb7e7f/verification/lfw.py) 
   i changged  105 to "
    feed= mx.model.FeedForward.load(args.model_prefix, args.epoch,ctx)
        model_args=feed.arg_params
        model_auxs=feed.aux_params
        symbol = googlenet.get()
"
## What have you tried to solve it?

1.read#5061
2.
3.

**Comment by Kdecem** [comment]
I do not kow is it right or wrong,but i use  
exector=symbol.bind(mx.gpu(),model_args,args_grad=None,grad_req="null",aux_states=model_auxs,group2ctx=group2ctx)
solved my problem.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
