### ISSUE TITLE
some questions about random

### ISSUE THREAD

**Issue by 501177639** [apache/incubator-mxnet#5554]
Hi,
     if I have a network, I hope I can get the same result every training, how can I do?
     I find just use  mx.random.seed(seed) can't help, it just help get the same init params for the network every training, but still get different grads every training.  I have checked my input data iter, it can get the same input data every training.

**Comment by 501177639** [comment]
`                    data_batch = train_data.next()

                    self.forward_backward(data_batch)
                    # save grad
                    self.temp_grad = [
                        [grad.copyto(grad.context) for grad in grads]
                        for grads in self._exec_group.grad_arrays]

                    self.forward_backward(data_batch)
                    # compare grad
                    for index, pair in enumerate(zip(self.temp_grad, self._exec_group.grad_arrays)):
                        temp_grad_list, grad_arrays_list = pair
                        for k, p in enumerate(zip(temp_grad_list, grad_arrays_list)):
                            a_temp_grad, a_grad_arrays = p
                            flag = (a_temp_grad == a_grad_arrays).asnumpy()
                            flag = bool(flag.all())
                            print flag`
                   # always get the value of flag is False, why?

I forward and backward twice using the same data_batch, why did get different grads?

**Comment by 501177639** [comment]
`                   data_batch = train_data.next()
                    self.forward(data_batch, is_train=True)
                    output1 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output2 = self.get_outputs()[0].asnumpy()
                    flag1 = bool((output1 == output2).all()) # false
                    self.forward(data_batch, is_train=False)
                    output3 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=False)
                    output4 = self.get_outputs()[0].asnumpy()
                    flag2 = bool((output3 == output4).all()) # true`

I further found if the value of is_train is True, forward would get different outputs, why?

**Comment by 501177639** [comment]
`                    data_batch = train_data.next()
                    self.forward(data_batch, is_train=True)
                    output1 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output2 = self.get_outputs()[0].asnumpy()
                    flag1 = bool((output1 == output2).all()) # false
                    self.forward(data_batch, is_train=False)
                    output3 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=False)
                    output4 = self.get_outputs()[0].asnumpy()
                    flag2 = bool((output3 == output4).all()) # true`

I further find that if the value of is_train is true, forward would get different outputs, why?

**Comment by 501177639** [comment]
`
                    data_batch = train_data.next()
                    self.forward(data_batch, is_train=False)
                    output1 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output2 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output3 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=False)
                    output4 = self.get_outputs()[0].asnumpy()
                    flag1 = bool((output2 == output3).all())  # false
                    flag2 = bool((output1 == output4).all())  # true
`

**Comment by 501177639** [comment]
data_batch = train_data.next()
                    self.forward(data_batch, is_train=False)
                    output1 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output2 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=True)
                    output3 = self.get_outputs()[0].asnumpy()
                    self.forward(data_batch, is_train=False)
                    output4 = self.get_outputs()[0].asnumpy()
                    flag1 = bool((output2 == output3).all())  # false
                    flag2 = bool((output1 == output4).all())  # true

**Comment by 501177639** [comment]
If the value of is_train, forward would get different output, why?

**Comment by 501177639** [comment]
If the value of is_train is true, forward would get different output, why?

**Comment by 501177639** [comment]
@piiswrong  Could you help me?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
