### ISSUE TITLE
Amalgamation compile error for Android

### ISSUE THREAD

**Issue by PKUEcho** [apache/incubator-mxnet#5555]
Cannot build Amalgamation on my Mac 10.10.

This is how I build the standalone toolchain
`python build/tools/make_standalone_toolchain.py --stl=libc++ --arch arm --api 21 --install-dir /tmp/my-android-toolchain`

And I change the OPENBLAS_ROOT, SYS_ROOT, CXX, CC following the instructions. But when I type `make ANDROID=1` to compiled I got errors like this
`/Users/echo/Library/Android/my-android-toolchain/include/c++/4.9.x/cstddef:43:25: fatal error: stddef.h: No such file or directory`

Then I read [this thread](https://github.com/android-ndk/ndk/issues/215), and add this to makefile
`# DEFS+=-isystem /Users/echo/Library/Android/my-android-toolchain/include/c++/4.9.x`

Then the error becomes following
`jni/../mxnet_predict-all.cc:53:36: fatal error: src/c_api/c_api_error.cc: No such file or directory`

I also tried Clang, as I change the makefile like this
`export SYS_ROOT=/Users/echo/Library/Android/my-android-toolchain/sysroot`
`export CXX=/Users/echo/Library/Android/my-android-toolchain/bin/arm-linux-androideabi-clang++`
`export CC=/Users/echo/Library/Android/my-android-toolchain/bin/arm-linux-androideabi-clang`

But the error remains
`jni/../mxnet_predict-all.cc:53:10: fatal error: 'src/c_api/c_api_error.cc' file not found`

Anyone can help me to compile this?

**Comment by arank** [comment]
The issue is that you (i.e. the makefile which is broken for this build) has not told the compiler about the paths to the files. You will have to add -I{MXNET_ROOT} to the CFlags in the makefile for this, and other included files whose paths may be missing

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
