### ISSUE TITLE
How do I use the python training model in the background to get the predict results to the web front end, in C# and RNN?

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5581]

**Comment by kevinthesun** [comment]
Would you like to get input from web frontend and predict it in the backend, then pass the result back to frontend? If so, this is a restful service and you may consider following client-server process.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
