### ISSUE TITLE
Do we need to decay the learning rate when using RMSProp or Nesterov?

### ISSUE THREAD

**Issue by cuihenggang** [apache/incubator-mxnet#5585]
I'm trying to train the Inception-BN model on the ILSVRC12 dataset, and I have some questions on the training configurations.

I have heard that decaying the learning rate is necessary to get a good model accuracy. So how about using adaptive learning rate tuning algorithms, such as RMSProp, Nesterov, AdaDelta, or AdaGrad. Do they work well in this case? Also, when we use those adaptive learning rate tuning algorithms, do we still need to decay the learning rate?

Thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
