### ISSUE TITLE
[Discussion] CreateBackwardOp interface for `Operator`

### ISSUE THREAD

**Issue by jermainewang** [apache/incubator-mxnet#5592]
Based on discussion in https://github.com/dmlc/nnvm/pull/108 , we propose two new interfaces for `OperatorProperty` class:
```c++
// Return whether the operator is stateless, which means the backward operator can be created
// without forward operator.
virtual bool IsStateless() const {
  return false;
}
// [Optional] Create an operator that is used to do backward.
// It defaults to return null, which means the backward operator cannot be created
// standalone and should be created together with forward operator.
virtual Operator* CreateBackwardOperatorEx(
    const Context& ctx,
    const std::vector<TShape>& in_shape,
    const std::vector<int>& in_type,
    const std::vector<TShape>& out_shape,
    const std::vector<int>& out_type) const {
  return nullptr;
}
```

By default, these interfaces return stateful for all current operators. Upon creating `OpExecutor` for a node, following logic will be used:
* If it is a forward node, go straight create its `OpExecutor`. (same as original logic)
* If it is a backward node and its forward node exists, reuse its forward `OpExecutor`. (same as original logic)
* If it is a backward node but no forward node exists, create the `OpExecutor` using the new interface. (the new logic)

Therefore, **nothing will be changed for all current MXNet codes**. The only part that uses this currently is `AutogradRuntime`. It will first check whether the given symbol is stateless (if not, raise error). Then it will use the third logic above to create its backward `OpExecutor`.

The implementation overhead is to override above interfaces for stateless operators. This should be easy since most of the current operator is stateless so the `CreateBackwardOperatorEx` usually follows the *same* logic as `CreateOperatorEx`.

Please leave your comments.

@piiswrong @tqchen @ZihengJiang

**Comment by piiswrong** [comment]
Creating an operator from an operator seems weird. If you have access to the forward operator why not just use it for the backward operation

**Comment by jermainewang** [comment]
>If you have access to the forward operator why not just use it for the backward operation.

This part is what the second logic does.

> You can cache the operator used in imperativeinvoke (instead of deleting it) and reuse in backward. I don't see why you need another interface.

If the operator is invoked through imperative calls, you can do this. But this does not solve the inherent problem that forward and backward are coupled. This blocks many passes from developed. For example, if its forward operator is optimized away (fused or whatever), its backward operator must be changed as well, but this may not be possible. The stateful operator is hard to deal with and marking some of them to be stateless can solve most of the problem.

**Comment by jermainewang** [comment]
Oops, mistake. It is not in the `Operator` class. The interface should be in the `OperatorProperty` class.

**Comment by piiswrong** [comment]
fusing forward while keeping backward is impossible due to many things. Only changing this won't help. You also have control_dep/backward infershape problems.

In general I don't think you can modify the forward graph after gradientpass (it is possible to modify the backward part of the graph after gradient pass, however). Also I don't see any reason to modify forward graph after gradient. You can do it before gradientpass is applied.
