### ISSUE TITLE
example/rcnn mistake--KeyError: 'width'

### ISSUE THREAD

**Issue by Fansiee** [apache/incubator-mxnet#5596]
## Environment info
Operating System:
Ubuntu16.04.2

Compiler:
gcc5.4.0

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.3 

Or if installed from source:
yes

## Error Message:
```
num_images 5011
voc_2007_trainval gt roidb loaded from data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
Traceback (most recent call last):
  File "train_end2end.py", line 184, in <module>
    main()
  File "train_end2end.py", line 181, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 44, in train_net
    for image_set in image_sets]
  File "/home/cv/mx-rcnn/rcnn/utils/load_data.py", line 12, in load_gt_roidb
    roidb = imdb.append_flipped_images(roidb)
  File "/home/cv/mx-rcnn/rcnn/dataset/imdb.py", line 165, in append_flipped_images
    boxes[:, 0] = roi_rec['width'] - oldx2 - 1
KeyError: 'width'
```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. changed to 0.9.1
2.
3.

## What have you tried to solve it?

1.NO
2.
3.

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
Could be closed due to duplication in https://github.com/precedenceguo/mx-rcnn/issues/58

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
