### ISSUE TITLE
Any route to make auto complete of my PyCharm (or any other IDE) work again?

### ISSUE THREAD

**Issue by metorm** [apache/incubator-mxnet#5597]
Newbie to mxnet. It is important to have auto complete when learning / writing my own code.

However, some of the symbols in mxnet just cannot be recoganised by PyCharm. I don't know if this is an issue with PyCharm or other editors also have this problem.

![image](https://cloud.githubusercontent.com/assets/12082680/24393069/3a58841e-13c9-11e7-9bfd-186ee0fd0925.png)

**Comment by metorm** [comment]
OK, it seems that this situation happens because mxnet contains C extension, and PyCharm only handles ordinary python code.

One possible work round is using the terminal panel in PyCharm. Run ipython in that panel, import mxnet as mx, then

    mx.sym.FullyConnected?

shows the full comment string, and 

    mx.sym.FullyConnected?

shows source code the the function

**Comment by lvaleriu** [comment]
Isnt there a way to add a Python class wrapper for every symbol and then construct the NN from them?

**Comment by metorm** [comment]
Appearently that's what tensorflow did.

I guess doing like this costs developers lots of time, so mxnet may not write these wrappers recently.

**Comment by lvaleriu** [comment]
Or we should wait for the keras mxnet backend. All mxnet symbols will be hided by keras layers.

**Comment by metorm** [comment]
Yeah, the more choices, the better.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
