### ISSUE TITLE
running lazy evaluation code example outputs "Illegal instruction"

### ISSUE THREAD

**Issue by Maslino** [apache/incubator-mxnet#5601]
## Environment info
Operating System:
CentOS Linux release 7.2.1511

Compiler:
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

Package used (Python/R/Scala/Julia):
Python

MXNet version:
mxnet-cu80 (0.9.3a3)

CUDA version:
cuda 8.0.61
Nvidia driver 367.57
GPU Grid K1

Python version and distribution:
CPython 2.7.5

## Error Message:
time for all computations are pushed into the backend engine:
 0.001749 sec
Illegal instruction
## Minimum reproducible example
the following code is copied from [mxnet tutorial](http://mxnet.io/tutorials/python/ndarray.html):
```
# @@@ AUTOTEST_OUTPUT_IGNORED_CELL
import time

def do(x, n):
    """push computation into the backend engine"""
    return [mx.nd.dot(x,x) for i in range(n)]
def wait(x):
    """wait until all results are available"""
    for y in x:
        y.wait_to_read()
        
tic = time.time()
a = mx.nd.ones((1000,1000))
b = do(a, 50)
print('time for all computations are pushed into the backend engine:\n %f sec' % (time.time() - tic))
wait(b)
print('time for all computations are finished:\n %f sec' % (time.time() - tic))
```
## Steps to reproduce
just run the code above

## What have you tried to solve it?
I'm not sure what's going on. What maybe the problem?

**Comment by Maslino** [comment]
I tried in ipython:
```
In [1]: import mxnet as mx

In [2]: a = mx.nd.ones((1000, 1000))

In [3]: mx.nd.dot(a, a)
Out[3]: <NDArray 1000x1000 @cpu(0)>

Illegal instruction
```
The problem seems related with matrix multiplication.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by eric-haibin-lin** [comment]
What version of openblas did you use? I've seen similar error when a buggy version of openblas was used.
