### ISSUE TITLE
How can i adjust the sync frequency when use distributed learning?

### ISSUE THREAD

**Issue by apeng5399** [apache/incubator-mxnet#5602]
while using launcher under local mode, how can i adjust the parameter sync frequency, it seems each worker have one parameter sever, and every sever can communicate with each other, can i adjust it to 1master n worker mode?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
