### ISSUE TITLE
the  train- accuracy is upon 0.98  while the validation-accuracy is around 0.02 sometimes with version 0.9.4

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#5603]
it is so instable of  V0.9.4.

**Comment by janelu9** [comment]
it seems that it‘s a validation-error rate

**Comment by bravomikekilo** [comment]
please give us more details, such as **some example code** for reproduce** or **logs**

**Comment by janelu9** [comment]
@bravomikekilo  It went well when I switched mxnet to 0.9.3 without changing any codes.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
