### ISSUE TITLE
fcn-xs can't finish training task with 8s model

### ISSUE THREAD

**Issue by T800GHB** [apache/incubator-mxnet#5613]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu14.04

Compiler:
g++ 5.4.1

Package used (Python/R/Scala/Julia):
python

MXNet version:
0.9.3

Or if installed from source:
yes

MXNet commit hash (`git rev-parse HEAD`):
3a48185324a47d988ba6cef3bfbdcaecd30793a0

If you are using python package, please provide

Python version and distribution:
Python2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
INFO:root:Epoch[32] Batch [1640]	Speed: 5.64 samples/sec	Train-accuracy=0.761236
*** Error in `python': double free or corruption (out): 0x00007f64c4000020 ***
./run_fcnxs.sh: line 13: 27997 Aborted                 (core dumped) python -u fcn_xs.py --model=fcn8s --prefix=/home/andrew/ExtraSpace/fcn-xs/model_pascal/FCN16s_VGG16 --epoch=27 --init-type=fcnxs

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
I just use run_fcnxs.sh step by step following the tutorial

if you are using your own code, please provide a short script that reproduces the error.
I have finish the training task with fcn-32s and fcn-16s model after 50 epoch iteration.
When I train fcn-8s model after 32 epoch, problem occured.

## What have you tried to solve it?
I don't know what could do.

@tqchen @tornadomeet @piiswrong

**Comment by bravomikekilo** [comment]
could you tell me your python version?
And is this always happens around epoch[32] ? or exactly at epoch[32]?

**Comment by T800GHB** [comment]
@bravomikekilo python version is 2.7.6.
I use NV 1080 to train this model
First try, i train this 8s model, task stop at batch 1670 of epoch 32,.
Second try, train task stop at batch 1320 of epoch 47. 
Maybe the number of batch is not very precisely.
Those tasks dumped with same reason.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
