### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by shivajid** [apache/incubator-mxnet#5617]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
Broken Link
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Broken links - Click the below link
2. https://github.com/dmlc/mxnet/tree/master/doc/tutorials/python/record_io.ipynb
3. It shows 404

## What have you tried to solve it?

1.
2.
3.

**Comment by bravomikekilo** [comment]
that file seems has been removed, maybe you use git to get the older version of it.

**Comment by matt32106** [comment]
there is already an issue for broken links: #5588

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
