### ISSUE TITLE
Faster R-CNN decrease memory usage

### ISSUE THREAD

**Issue by creiser** [apache/incubator-mxnet#5620]
I tried the Faster R-CNN example with the Pascal VOC data and ran out of  memory, just as I expected with my GTX 770 with 2GB since the README says 4GB are needed (although for Fast R-CNN, which is more memory intensive)

Will decreasing the number of training images or adjusting any other parameters help to reduce the memory usage? I am only interested on training with a relatively small dataset.

With CNTK's Fast (not: faster) R-CNN implementation I was able to train on a 350 image dataset by decreasing the number of ROIs. Is there something similiar in this implementation?

**Comment by piiswrong** [comment]
you can try `export MXNET_BACKWARD_DO_MIRROR=1` before running

**Comment by creiser** [comment]
Thank you. It still does not work. What I also tried so far:
Decreased number of training samples to 100 by calling (just for testing)
`roidb = roidb[:100]`
and I reduced the RPN batch size as well to:
`config.TRAIN.RPN_BATCH_SIZE = 1`

Do you have any other idea what make decrease memory usage?

**Comment by piiswrong** [comment]
you can try mxnet memmonger: https://github.com/dmlc/mxnet-memonger
It's more involved and require code changes

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
