### ISSUE TITLE
support spark 2.1.0

### ISSUE THREAD

**Issue by mykidong** [apache/incubator-mxnet#5624]
In scala-package/spark module, I have changed spark version to 2.1.0.

And I tried building with make scalapkg, but compilation errors ocurred like this:

[ERROR] /home/alm/mxnet/scala-package/spark/src/main/scala/ml/dmlc/mxnet/spark/transformer/MXNet.scala:34: error: class MXNet needs to be abstract, since method train in class Predictor of type (dataset: org.apache.spark.sql.Dataset[_])ml.dmlc.mxnet.spark.transformer.MXNetModelWrap is not defined
[INFO] (Note that org.apache.spark.sql.Dataset[_] does not match org.apache.spark.sql.DataFrame: their type parameters differ)
[INFO] class MXNet extends Predictor[Vector, MXNet, MXNetModelWrap] {
[INFO]       ^
[ERROR] /home/alm/mxnet/scala-package/spark/src/main/scala/ml/dmlc/mxnet/spark/transformer/MXNet.scala:43: error: method train overrides nothing.
[INFO] Note: the super classes of class MXNet contain the following, non final members named train:
[INFO] protected def train(dataset: org.apache.spark.sql.Dataset[_]): ml.dmlc.mxnet.spark.transformer.MXNetModelWrap
[INFO]   override def train(dataset: DataFrame) : MXNetModelWrap = {
[INFO]                ^
[ERROR] two errors found

Is there any plan to support spark 2.1.0?

- Kidong Lee.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by bejjani** [comment]
just change occurrences of ```Dataframe``` to ```Dataset[_]``` in MXNet.scala to match the new signature of ```Predictor``` in Spark 2.x
You will have to change the version of spark in the pom before building.
