### ISSUE TITLE
the usage for cpu multi cores with local kv store

### ISSUE THREAD

**Issue by apeng5399** [apache/incubator-mxnet#5626]
when use local kv-store，should I adjust batch to batch_size/worker_num，it seems mnist use the same batch_size with lenet has no speed up at all, I want to figure out how i can achieve speed up using local kv-store as limited to resource(1cpu with 32 cores )

**Comment by apeng5399** [comment]
I have try the inception-bn，the sample/sec has become num_worker times，the validation accuracy has not change at all

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
