### ISSUE TITLE
NNPACK compiling error since #5519

### ISSUE THREAD

**Issue by pallashadow** [apache/incubator-mxnet#5627]
since line 64 in file src/operator/pooling-inl.h
has been modified to 
template<typename xpu, typename DType>

To enable NNPACK
3 lines in src/oprator/nnpack/nnpack_pooling-inl.h should be updated

//(old)template <typename xpu, typename Reducer, typename DType>
template <typename xpu, typename DType>
//(old)class NNPACKPoolingOp : public PoolingOp<xpu, Reducer, DType> {
class NNPACKPoolingOp : public PoolingOp<xpu, DType> {
 private:
  PoolingParam param_;

 public:
  explicit NNPACKPoolingOp(PoolingParam p)
//(old)      : PoolingOp<xpu, Reducer, DType>(p) {
      : PoolingOp<xpu, DType>(p) {
    this->param_ = p;
  }

1 line in src/oprator/pooling.cc should be updated
//(line 53)return new NNPACKPoolingOp<cpu, mshadow::red::maximum, float>(param);
return new NNPACKPoolingOp<cpu, float>(param);

@reminisce

**Comment by reminisce** [comment]
Thanks for pointing it out. I will submit a PR to fix it.

**Comment by pallashadow** [comment]
But I have got an error after compiling
-------------------------------------------------------------
mxnet.base.MXNetError: [12:15:47] src/c_api/c_api_ndarray.cc:381: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

**Comment by reminisce** [comment]
Could you post your script here for diagnosis?

**Comment by pallashadow** [comment]
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py", line 623, in predict
    self._init_predictor(data_shapes, type_dict)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py", line 546, in _init_predictor
    self.ctx[0], grad_req='null', type_dict=type_dict, **dict(input_shapes))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/symbol.py", line 901, in simple_bind
    for dtype, dev, shape in zip(arg_types, arg_ctx, arg_shapes)]
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/ndarray.py", line 926, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/_ctypes/ndarray.py", line 133, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:15:47] src/c_api/c_api_ndarray.cc:381: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

**Comment by reminisce** [comment]
Can you post your minimum reproducible python script here? It's hard to tell simply from the error backtrace.

**Comment by piiswrong** [comment]
try make clean and make again

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
