### ISSUE TITLE
problem about kv-store

### ISSUE THREAD

**Issue by apeng5399** [apache/incubator-mxnet#5631]
1st situation:
1cpu 32cores kv=mx.kvstore.create(local)
use launcher in example python launcher.py --cpus=0  -n 4 ...
2rd situation:
2cpu kv=mx.kvstore.create(local)
use launcher in example python launcher.py --cpus=0,1  -n 4 ...
r 
will the 2 situation use kv? I use the 1st for fast train, but didn't have effect

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
