### ISSUE TITLE
BatchNorm -Error Gamma parameter 

### ISSUE THREAD

**Issue by yuantangliang** [apache/incubator-mxnet#5632]
## Environment info
Operating System:
Ubuntu14.04  
Compiler:
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.3 release 

python2.7.3 
If you are using R package, please provide

## Error Message:
Please paste the full error message, including stack trace.

When I get gamma parameter from model I train,the gamma parameter in all layer  are the same value.  and The features I calculate manual can only match the first feature Mxnet calculate. is there exists a bugs? can anyone tell me ? 

![sdkk1n 6](https://cloud.githubusercontent.com/assets/7912276/24496366/a0f31016-156a-11e7-913b-5c2511ac739c.PNG)

more evidence: I can refer different gamma value from the the batch node output.

**It seems that when I load parameter and model from disks,the Mxnets knows the right gamma value,but when i convert the gamma to numpy, something goes wrong.**

how can i  check parameter in disks ? I want know what's really save in disk.  can anyone tell me how   ?

**Comment by yuantangliang** [comment]
some evidence:  I can refer different gamma value from the the batchnode output.

**Comment by yuantangliang** [comment]
It seems that when I load network and model form disks,the Mxnets knows the right gamma value,but when i convert it to numpy, something goes wrong.

**Comment by yuantangliang** [comment]
how can i check parameter in disks ? and see what's really save in disk? can anyone tell me ?

**Comment by piiswrong** [comment]
if you used fix_gamma, gamma will be ignored and value set to 1

**Comment by yuantangliang** [comment]
I do not set fix_gamma to 1,and only the first  value show above is used by Mxnet. the Mxnet use different value  (not the value show above) when forward.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
