### ISSUE TITLE
about Frequently Asked Questions

### ISSUE THREAD

**Issue by Vogen** [apache/incubator-mxnet#5645]
In [faq](https://github.com/dmlc/mxnet/blob/master/docs/how_to/faq.md)
"
No increase in speed when using more than one GPU or computer
Check the following:
Does your neural network already run fast, such as >1000 example/sec or >10 batches/sec? If yes, it's unlikely to speed up any further by adding more resources because of the communication overhead.
"
If neural network alreading run fast, will training become slower or get larger train/validation error?

**Comment by tornadomeet** [comment]
cannot get your point..

**Comment by Vogen** [comment]
@tornadomeet 
I use few worker to speed up training. But, when using more workers, it cost much more time reaching same train accuracy. 
How do parameter server work when communication overhead.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
