### ISSUE TITLE
[discuss]predict class with c++

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#5647]
currently using pre-trained model with c++ deploy is too complexity. such as an example is in [image-classification-predict.cc](https://github.com/dmlc/mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc), in which you can found that it's not friendly for users to use predict function in `src/c_api/c_predict_api.cc`.    

one inconvenient  lies in then initialization,  after initialized the  predict handle,  we can use it do forward, but if we only changed the input shape(such as batch-size), we need init again like this:
```c++
MXPredCreate(const char* symbol_json_str,
                 const void* param_bytes,
                 int param_size,
                 int dev_type, int dev_id,
                 mx_uint num_input_nodes,
                 const char** input_keys,
                 const mx_uint* input_shape_indptr,
                 const mx_uint* input_shape_data,
                PredictorHandle* out) 
```
it means that we not only need to input `json` and `param` file again, but also need the device id, input-key etc, but actually we only changed the shape, so better solve is using reshape like in caffe:
```c++
input_layer->Reshape(1, shape[0], shape[1], shape_[2], shape[3]);
net->Reshape();
``` 

another is when getting the output data, we need to set the output-shape first, such as:
```c++
MXPredGetOutputShape(PredictorHandle handle,
                         mx_uint out_index,
                         mx_uint** shape_data,
                         mx_uint* shape_ndim)
```
but the shape should be deduced automatically during using `MXPredGetOutput`, such as in caffe:
```c++
net->output_blobs()[0];
``` 

so here is the question:
do we need a c++ predict class interface? 
if needed, which directory should it be put, ```src/c_api``` or ```cpp-package``` or other places?  
and please give some advices to design interface. i'm glad to add this.

thanks.

**Comment by piiswrong** [comment]
@lx75249 @hotpxl 
I guess if it's going to be c++ we should put it in cpp-package. We should clean up the cpp-package and suggest users use that for production.

**Comment by feiyuvl** [comment]
I'm planning to do the same work.  I create a `model` dir in `src` which contains implementations of different predcit classes. And providing c interface in `src/c_api`.  Since some package is not needed in inference process, will it be better to provide a branch for production with less depdency?

**Comment by feiyulv** [comment]
I'm planning to do the same work and has a simple design like follows
```
include
|---mxnet
|---|---model.h
src
|---model
|---|---base_model.h/.cc
|---|---bucket_model.h/.cc
|---|---model.cc
|---c_api
|---|---c_model_api.h
```
BaseModel provides a Reshape interface
BucketModel handles bucket models like lstm, using a single subgraph/executor.
By the way, since some packages(ps-lite/python/...) are not needed in inference phase, will it be better to provide a branch for production with less dependency?

**Comment by piiswrong** [comment]
Can we call it module to be consistent?

feiyulv <notifications@github.com>于2017年3月31日 周五下午8:22写道：

**Comment by feiyulv** [comment]
@piiswrong OK

**Comment by lx75249** [comment]
@feiyulv It's better to put them to cpp-package. I suppose they are not backend apis?

**Comment by feiyulv** [comment]
@lx75249 It's elegant to put them to cpp-package. But concerning the effciency, we may need to handle GraphExecutor manually. The cpp-package is based on c_api backend, will it be convient to access the executor interface?

**Comment by lx75249** [comment]
@feiyulv Why do we need to handle GraphExecutor? Could you explain the details? If we do need it, we can make it a backend api so that all front end bindings can benefit.

**Comment by feiyulv** [comment]
@lx75249 No much detailed  thought on that yet. Using cpp-package is a more elegant way to handle this.

**Comment by mixcoder** [comment]
is there any progress about this?  @feiyulv  @tornadomeet

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by idealboy** [comment]
why the image-classification-predict.cc is slow for predict than python and feature_extract.cc?

in image-classification-predict.cc, the most time is located in MXPredGetOutput(with SyncCopyTOcpu)?

Thank you

**Comment by szha** [comment]
@idealboy would you create a separate issue for this and include relevant details such as your system and the code?
