### ISSUE TITLE
Why CPU utilization is so high with only Softmax Layer and reasonable with MLP ?

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#5653]
Hi all,

Nowadays, I am using MXNet and I noticed very strange behavior in MXNet. I am using provided example on the GitHub called Train_mnist.py 

I am working on AWS environment, local and distributed. 
Machine Specification: 
Ubuntu, instance: m4.xlarge.

Model  m4.xlarge
vCPU	4
Mem (GiB)  16
SSD Storage (GB)	EBS-only
Dedicated EBS Bandwidth (Mbps) 750

I modified the MLP.py for the following.

def get_symbol(num_classes=10, **kwargs):
    data = mx.symbol.Variable('data')
    flatten = mx.sym.Flatten(data=data)
    fc3  = mx.symbol.FullyConnected(data = flatten, name='fc3', num_hidden=num_classes)
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
    return mlp

My CPU utilization for single or distributed systems is almost 80% --> so high comparing to other framework

Then: I run the same code with out modification

"""
a simple multilayer perceptron
"""
import mxnet as mx

def get_symbol(num_classes=10, **kwargs):
    data = mx.symbol.Variable('data')
    flatten = mx.sym.Flatten(data=data)
    fc1  = mx.symbol.FullyConnected(data = flatten, name='fc1', num_hidden=512)
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
    fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 256)
    act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
    fc3  = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=num_classes)
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
    return mlp

Here the CPU utilization is about 40% for single machine or distributed version.

My question is why its so high for Softmax layer alone and low with network layers + softmax layer.

I am wondering if this is a common phenomenon in MXNet or I am having something not right.

Sincerely

**Comment by salemmohammed** [comment]
@piiswrong
Can you please share something in the above problem ?
I believe that this is an issue.

**Comment by piiswrong** [comment]
if you are training on cpu isn't high cpu utilization a good thing?

**Comment by salemmohammed** [comment]
@piiswrong 

Thanks for your reply.

My question is why softMax layer took too much CPU utilization than MLP+softMax layer ? 

SoftMax: I mean here is using SoftMax layer without any network layer ( hidden layer )
Code:
`
data = mx.symbol.Variable('data')
flatten = mx.sym.Flatten(data=data)
fc3 = mx.symbol.FullyConnected(data = flatten, name='fc3', num_hidden=num_classes)
mlp = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
`

MLP: I mean here is using SoftMax layer with network layer ( hidden layer )
`
data = mx.symbol.Variable('data')
flatten = mx.sym.Flatten(data=data)
fc1 = mx.symbol.FullyConnected(data = flatten, name='fc1', num_hidden=512)
act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
fc2 = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 256)
act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
fc3 = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=num_classes)
mlp = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
`


Based on my understanding from different framework, CPU is increasing while I am increasing layers.
it does not make sense for me to use 80 % of CPU for doing SoftMax layer while 40% for SoftMax and MLP layers. 

Sincerely

**Comment by piiswrong** [comment]
I wouldn't stress over performance numbers on these small networks. Try resnet to get realistic performance measure

**Comment by salemmohammed** [comment]
@piiswrong 
@mli 

My explanation for that is the backward propagation is stolen. 
In the SoftMax layer alone, there is no backward propagation and it is so fast and CPU intensive. However, for SoftMax and MLP, back propagation is slow, thus CPU utilization is low.


Sincerely

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
