### ISSUE TITLE
Installation error - local installation

### ISSUE THREAD

**Issue by itorres2607** [apache/incubator-mxnet#5655]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Error Message:
Please paste the full error message, including stack trace.

/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1

I am trying to do a local installation

## What have you tried to solve it?

1. Installed openblas locally, set the LD_LIBRARY_PATH in the .profile, so everytime i login it is executed
2. Set the argument ADD_LDFLAGS = -I/path to library
3. execute "make PREFIX=path to local installation"

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
