### ISSUE TITLE
Parameter Passing problem of custom operator in python

### ISSUE THREAD

**Issue by MultiLi** [apache/incubator-mxnet#5658]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu
Compiler:

Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.4
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
2.7.12

When I try to pass a parameter to my operator based on CustomProp, it automatically casts the value to a string type. And that's one output_shape that I got.

(10L, 1, '888888888888888888888888888888888888888888888888', '8888888888888888888888888888888888888888888888888888888888888888')

Hope you can update soon

**Comment by piiswrong** [comment]
you need to cast back in constructor.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
