### ISSUE TITLE
Error compiling docs

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#5664]
Running the new command to compile docs (`make html`) I get the following error:

## Error Message:
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.8

Configuration error:
There is a syntax error in your configuration file: invalid syntax (sphinx_util.py, line 100)
Did you change the syntax from 2.x to 3.x?
make: *** [html] Error 1
```

**Comment by mli** [comment]
change the line in docs/sphinx_util.py from python2 to python3?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
