### ISSUE TITLE
Python testing: nosetests and `if __name__ == "__main__"`

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#5667]
As far as I understand the only "supported" way to run all python test cases is with `nosetests`. Nevertheless most (if not all) python test cases run some tests when started as `python test_X.py`.

Unfortunately the two ways to start the tests are inconsistent, as the `if __name__ == "__main__"` part of the `test_X.py` file is not guaranteed to run all tests run by `nosetests`.

For example when running `python` [test_operator_gpu.py](https://github.com/dmlc/mxnet/blob/master/tests/python/gpu/test_operator_gpu.py#L645) the method [test_upsampling_bilinear_with_type](https://github.com/dmlc/mxnet/blob/master/tests/python/gpu/test_operator_gpu.py#L377) is not run, though it is run by `nosetests`.

This is confusing and I therefore propose to change the current behaviour. I think there are two possible approaches:

- Make sure that `if __name__ == "__main__"` runs all relevant test cases.
- Don't run any test cases in `if __name__ == "__main__"` but print an error message requesting the user to run `nosetests`.

The first option seems inferior, as it requires constant care when adding new test cases, while option two is a one time change.

What do you think?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
