### ISSUE TITLE
Request about ndarray take() function

### ISSUE THREAD

**Issue by ghost** [apache/incubator-mxnet#5668]
In my code, a function which I commonly call does the following operation. Assume that we have a tensor A of shape (d1,d2,...,dn) and tensor B of shape (D1,d2,...,dn) where D1 > d1. So, the axis0 indices of the tensor A is mapped to a subset of axis0 indices of B. Assume that this mapping is stored into a dict, f. What I want to do this is to pick A[i] and add to B[f[i]], for each axis0 index of A, basically:

`for i in (0, A.shape[0]):
     B[f[i]] += A[i] 
`
This operation is inefficient and constitutes a bottleneck. Theoretically, I can solve this with the take operation, where I can get the subset of B, as determined by the mapping f and add A, as in the example:

`B = mx.ndarray.zeros(shape=(10, 4), ctx=mx.gpu(0))`
`A = mx.ndarray.ones(shape=(3, 4), ctx=mx.gpu(0))`
`# f = { 0:3, 1:4, 2:6}`
`indices = mx.ndarray.array(source_array=[3, 4, 6], ctx=mx.gpu(0))`
`b_subset = mx.ndarray.take(B, indices)`
`b_subset[:] += A[:]`

The problem here is, `b_subset` is a new buffer, it does not refer to the original B and when I add A on it, this new buffer is modified, not the original one.

Is it possible to add at least a flag to ndarray's take, so that it enables the modification of the original array to handle the cases like above?

**Comment by reminisce** [comment]
The difficulty is creating a view of the **take** result from an ndarray in which case the memory is not contiguous. I don't think mxnet currently supports that since most of the operators relies on contiguous memory allocation for tensors. Have you timed your first solution in your application? Is it really a bottleneck?
@piiswrong

**Comment by UfukCanBicici** [comment]
Actually, yes. Basically I use a heuristic in which I group the samples to be added from A into contiguous locations at B, and for addition then I use slicing for example like 
`            self.sourceArgument.gradientArray[source_tuple[0]:source_tuple[1] + 1] += \
                self.destinationArgument.gradientArray[destination_tuple[0]:destination_tuple[1] + 1]`
 and this clearly improves the performace compared to one by one adding.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
