### ISSUE TITLE
definition conflict of `slice`

### ISSUE THREAD

**Issue by GarrickLin** [apache/incubator-mxnet#5669]
After I updating mxnet to version 0.9.5, it came an error:
```
File "C:\Program Files\Anaconda2\Lib\site-packages\mxnet\ndarray.py", line 258, in __setitem__
  if isinstance(in_slice, slice):

TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```
and I debug into that
```
>>> slice
<function slice at 0x0000000005F52B38>
>>> type(slice)
<type 'function'>
```
it seems that there is a function named `slice` in mxnet conficting with python built-in class `slice`. Does anyone have the same problem as me ?

**Comment by piiswrong** [comment]
Your mxnet isn't properly updated. try cloning again

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
