### ISSUE TITLE
python train_mnist.py --gpus 0 report error

### ISSUE THREAD

**Issue by chenhaifeng2016** [apache/incubator-mxnet#5672]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 16.04 

Compiler:

Package used (Python/R/Scala/Julia):
python

MXNet version:
0,95

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python 2.7.2

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
![2017-04-03 22-25-47](https://cloud.githubusercontent.com/assets/18096245/24614137/ecfba8f6-18bc-11e7-8fd7-a06b7a791df3.png)

2.
3.

**Comment by piiswrong** [comment]
git submodule update && make clean && make

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
