### ISSUE TITLE
How to define a new operator to support Factorization Machine?

### ISSUE THREAD

**Issue by yxzf** [apache/incubator-mxnet#5681]
I find it is very easy to write FM using TensorFlow, but I am not   familiar with mxnet, how to define a new  operator in mxnet to support Factorization Machine?

**Comment by moveforever** [comment]
@yxzf it's not necessary to define a new operator.
you can refer to [https://github.com/moveforever/mxnet-project/blob/master/src/model.py](fm)

**Comment by formath** [comment]
It's not the appropriate time to add fm op until sparse tensor support has been done.  https://github.com/dmlc/mxnet/issues/5498#issuecomment-291352163

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
