### ISSUE TITLE
mx.mod.Module does not print .*output statistics anymore. Bug?

### ISSUE THREAD

**Issue by mcxkarakoc** [apache/incubator-mxnet#5691]
## Environment info
Package used (Python/R/Scala/Julia): Python
MXNet commit hash (`git rev-parse HEAD`): 138344683e65c87af20250e3f4cdcc5a72ac3cc5
#### 

I've created such a monitor: `mx.mon.Monitor(1, stat_func=self.mean_abs, pattern='.*', sort=False);` I'm passing it to a mx.mod.Module object as a parameter. After each batch, only the stats of data, .*weight, *.bias and softmax_label are printed. I've updated MxNet recently. 0.9.4 was working without any problems. Source code was the same.

**Comment by piiswrong** [comment]
@eric-haibin-lin Possibly due to bulking?

**Comment by eric-haibin-lin** [comment]
@piiswrong no bulk execution when monitor_callback is present. https://github.com/dmlc/mxnet/blob/master/src/executor/graph_executor.cc#L694

@mcxkarakoc do you mind providing some example code for us to reproduce the issue?

**Comment by mcxkarakoc** [comment]
**Here is an example code.**

```python
import mxnet as mx
import logging
import sys

def mean_abs(x):
    return mx.ndarray.divide(mx.ndarray.sum(mx.ndarray.abs(x)), reduce(lambda x, y: x * y, x.shape));

logger = logging.getLogger();
logger.setLevel(logging.DEBUG);
formatter = logging.Formatter('%(message)s');
h2 = logging.StreamHandler(sys.stdout)
h2.setFormatter(formatter);
logger.addHandler(h2)

mx.random.seed(11)
data = mx.nd.array([[0.05, .10]]);
label = mx.nd.array([[.01, 0.99]]);

dataIter = mx.io.NDArrayIter(data=data, label=label, batch_size=1, last_batch_handle='roll_over');

x = mx.symbol.Variable('data')
x = mx.symbol.FullyConnected(name='encoder_0', data=x, num_hidden=2)
x = mx.symbol.Activation(data=x, act_type='sigmoid')
x = mx.symbol.FullyConnected(name='encoder_1', data=x, num_hidden=2)
x = mx.symbol.Activation(data=x, act_type='sigmoid')
x = mx.symbol.LinearRegressionOutput(data=x, name='softmax', grad_scale=2)

mon = mx.mon.Monitor(1, stat_func=mean_abs, pattern='.*', sort=True);

modSolver = mx.mod.Module(x, context=[mx.cpu()]);
modSolver.fit(dataIter,
              kvstore=mx.kvstore.create('local'),
              optimizer='sgd', optimizer_params=(('learning_rate', 0.5),),
              eval_metric=mx.metric.create('rmse'),
              monitor=mon,
              initializer=None,
              arg_params={'encoder_0_weight': mx.nd.array([[.15, .20], [.25, .30]]), 'encoder_0_bias': mx.nd.array([.35, .35]),
                          'encoder_1_weight': mx.nd.array([[.40, .45], [.50, .55]]), 'encoder_1_bias': mx.nd.array([.60, .60])},
              num_epoch=2);
```

**Output:**

```
Batch:       1 data                           0.075	
Batch:       1 encoder_0_backward_bias        0.0093628	
Batch:       1 encoder_0_backward_data        0.762147	
Batch:       1 encoder_0_backward_weight      0.00070221	
Batch:       1 encoder_0_bias                 0.345319	
Batch:       1 encoder_0_weight               0.224649	
Batch:       1 encoder_1_backward_bias        0.0882984	
Batch:       1 encoder_1_backward_data        0.0388603	
Batch:       1 encoder_1_backward_weight      0.0525444	
Batch:       1 encoder_1_bias                 0.5749	
Batch:       1 encoder_1_weight               0.460064	
Batch:       1 softmax_label                  0.5	
Epoch[0] Train-rmse=0.546234
Epoch[0] Time cost=0.002
Batch:       2 data                           0.075	
Batch:       2 encoder_0_backward_bias        0.00843154	
Batch:       2 encoder_0_backward_data        0.753409	
Batch:       2 encoder_0_backward_weight      0.000632365	
Batch:       2 encoder_0_bias                 0.341103	
Batch:       2 encoder_0_weight               0.224333	
Batch:       2 encoder_1_backward_bias        0.0893122	
Batch:       2 encoder_1_backward_data        0.034964	
Batch:       2 encoder_1_backward_weight      0.0530456	
Batch:       2 encoder_1_bias                 0.548497	
Batch:       2 encoder_1_weight               0.444382	
Batch:       2 softmax_label                  0.5	
Epoch[1] Train-rmse=0.529596
Epoch[1] Time cost=0.002
```

By the way, other than output data, please notice that backward_data of activation layers is not printed, too.

**Comment by zhreshold** [comment]
Same here. But in my case, one and only one *_output was printed out of 60+ layers, pretty weird.

**Comment by piiswrong** [comment]
@eric-haibin-lin Could you have a look?

**Comment by moveforever** [comment]
i came across similar problem #5644 that when using BucketingModule, it didn't print backward.*

**Comment by eric-haibin-lin** [comment]
@moveforever @mcxkarakoc Could you pull in the patch and try again?

**Comment by moveforever** [comment]
@eric-haibin-lin , i update mxnet into newest, and  when i run my code again using BucketingModule, there no output* or backward* in log

**Comment by mcxkarakoc** [comment]
@eric-haibin-lin Thanks for your efforts. It seems handled for my case.

**Comment by eric-haibin-lin** [comment]
@mcxkarakoc What about without printing? I/O may slow things down. Is both code running on cpu? 
@moveforever do you mind providing a piece of code for me to reproduce? 
@zhreshold do you still have the problem after pulling in the patch?

**Comment by zhreshold** [comment]
@eric-haibin-lin  Looks good now!

**Comment by mcxkarakoc** [comment]
@eric-haibin-lin Without printing, each batch takes about 700ms. Just printing in cpu, others in gpu.

**Comment by moveforever** [comment]
@eric-haibin-lin, my code and data is https://github.com/moveforever/gated_cnn

**Comment by fhieber** [comment]
@piiswrong This problem apparently still exists in latest version of MXNet: pattern=".*" only prints weights/biases when using a BucketingModule, but everything if using a regular Module.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
