### ISSUE TITLE
What is bucket_key in mxnet.io.DataBatch(data, label, pad=None, index=None, bucket_key=None, provide_data=None, provide_label=None)

### ISSUE THREAD

**Issue by MarleneHathaway** [apache/incubator-mxnet#5696]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by kevinthesun** [comment]
Bucket key is used to switch bucketing module. In bucketing module, you can specify bucket key for each data batch to use different module for training/testing/predicting.

**Comment by kevinthesun** [comment]
```
  def forward(self, data_batch, is_train=None):
        """Forward computation.

        Parameters
        ----------
        data_batch : DataBatch
        is_train : bool
            Default is `None`, in which case `is_train` is take as `self.for_training`.
        """
        assert self.binded and self.params_initialized
        self.switch_bucket(data_batch.bucket_key, data_batch.provide_data,
                           data_batch.provide_label)
        self._curr_module.forward(data_batch, is_train=is_train)
```

This is the forward of bucketing_module. Bucket key of each data batch is used to switch module before forward operation.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
