### ISSUE TITLE
[PROPOSAL] SparseNDArray Python API

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#5707]
# Overview

End-to-end design overview available at https://github.com/dmlc/mxnet/issues/5498
**This issue is opened to gather comments regarding priority of sparse operators to support.**

#### Data Types

We focus on two sparse formats: csr and row-sparse. Both symbolic and imperative execution will be supported. Implementation on CPU has higher priority than GPU.

#### Implicit Sparse/Dense Format Conversion

Since not all operators are re-implemented with sparse input, sometimes a sparse tensor is converted to other format if needed. Specifically,  
* If an operator doesn't handle sparse input, then sparse inputs are converted to dense ones automatically on runtime. 
* By default an operator refuses to handle inputs with multiple sparsity formats. In the future we might consider convert them to a same format, chosen by the operator.

Warnings will be thrown so that users are aware of such conversion.

# Python API

#### mx.sparse_nd.csr_mat(dense_mat, ctx=None, dtype=None)
Creates a `CSR` matrix from a dense matrix.
#### mx.sparse_nd.csr_mat(data, indices, indptr, shape, ctx=None, dtype=None)
Creates a `CSR` matrix with standard input.
```
>> data = np.array([1, 2, 3, 4, 5, 6])
>> indices = np.array([0, 2, 2, 0, 1, 2])
>> indptr = np.array([0, 2, 3, 6])
>> shape = (3, 3)
>> result = mx.sparse_nd.csr_mat(data, indices, indptr, shape)
   <SparseNDArray 3x3@cpu(0)>
>> result.asnumpy()
   array([[1, 0, 2],
         [0, 0, 3],
         [4, 5, 6]], dtype=float32)
```
#### mx.sparse_nd.row_sparse_array(data, indices, shape, ctx=None, dtype=None)
Creates a `row sparse` array, which is sparse in the first dimension, the dense in the rest(similar to IndexedSlice in tf). Row sparse array is not limited to 2D.
```
>> indices = np.array([0, 2])
>> data = np.array([[1, 0, 2], [3, 4, 5]])
>> shape = (3, 3)
>> result = mx.sparse_nd.row_sparse_array(data, indices, shape)
   <SparseNDArray 3x3@cpu(0)>
>> result.asnumpy()
   array([[1, 0, 2],
         [0, 0, 0],
         [3, 4, 5]], dtype=float32)
```

#### SparseNDArray.to_csr()
Makes a copy of data and returns SparseNDArray in CSR format.

#### SparseNDArray.to_row_sparse()
Makes a copy of data and returns a SparseNDArray in row sparse format.

#### SparseNDArray.to_dense()
Returns a dense NDArray

#### SparseNDArray.asnumpy()
Returns a dense numpy.ndarray object with value copied from this array.

## Mathematical Functions
*For common functions, their descriptions are omitted.*
#### mx.sparse_nd.dot(lhs, rhs, transpose_a=False, transpose_b=False, out=None)
Ordinary dot product of two arrays. 
```
>> # create a sparse array
>> a = mx.sparse_nd.csr_mat(..., shape=(10,10)) 
>> 
>> # create a dense array 
>> b = mx.nd.array(..., shape=(10, 1)) 
>> 
>> # sparse - dense matrix multiplication, returns a dense ndarray
>> mx.sparse_nd.dot(a, b) 
>> 
>> # sparse - sparse matrix multiplication, returns a dense ndarray
>> mx.sparse_nd.dot(a, a)
```
#### mx.symbol.Variable
Variable with attr['sparse_type'] will be considered as sparse input. 
#### mx.symbol.Embedding
Embedding layer with sparse input.

#### SparseNDArray.transpose()
Permute the dimensions of an array.

#### SparseNDArray.check_format()
Check whether the matrix format is valid

## KVStore and Distributed Training
User is not expected to change kv-store code to have sparse gradient updates. Once the engine detects sparse gradients, their parameters are updated using sparse gradient accordingly.

@tqchen @jermainewang Any comment on introducing a new SparseNDArray front-end class?
@mli

**Comment by janelu9** [comment]
can it support the sparse format such as libsvm

**Comment by eric-haibin-lin** [comment]
@janelu9 Could you find the spec of libsvm sparse file? We can make some evaluation

**Comment by tqchen** [comment]
LIBSVM can basically converted to CSR format easily. We had a parser in dmlc-core for that

**Comment by janelu9** [comment]
@tqchen now I use the dataiter after restoring the libsvm to the real sparse matrix. that's inefficient I think. it's helpful if there is a sparser iteration I believe

**Comment by janelu9** [comment]
now I find symbol.one-hot  it's so helpful for handling sparse data

**Comment by janelu9** [comment]
CSVIter+one_hot greatful
