### ISSUE TITLE
Running error in the example code of googlenet

### ISSUE THREAD

**Issue by shyhuai** [apache/incubator-mxnet#5714]
I run the example code of googlenet: [image-classification](https://github.com/dmlc/mxnet/tree/master/example/image-classification) on a K80 server with the newest version of MXNet(0.9.5). It seems that the error is caused by the size configuration of pooling. Could you help to fix it?  Thanks.
The command I used:

```
python train_imagenet.py --network=googlenet --gpus=0
```
The error information:
```
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator pooling4: [23:46:47] src/operator/./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (7) exceeds input (6 padded to 6)
```

**Comment by 123chengbo** [comment]
Image resolution is too small。
train_imagenet.py set default data_shape = '3, 224, 224'， which is too small for googlenet，try 300.....

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
