### ISSUE TITLE
Resnet pre-trained models

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#5715]
The resnet pretrained models hosted on mxnet doesn't come with epoch number. http://data.dmlc.ml/mxnet/models/imagenet/resnet/18-layers/
e.g. `resnet-18-0000.params 2016-10-21 02:15	45M`
It may confuse user how many epochs it was trained.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
