### ISSUE TITLE
Question about sparsity regularization and IdentityAttachKLSparseReg

### ISSUE THREAD

**Issue by GaiYu0** [apache/incubator-mxnet#5724]
Hi! I would like to apply sparsity regularization to outputs of ReLU layers. I notice there is a layer called IdentityAttachKLSparseReg. However, its documentation states that it "applies a sparse regularization to the output of a sigmoid activation function". Then is it correct to apply IdentityAttachKLSparseReg to outputs of ReLU functions? Could anyone provide the mathematical formula of this layer? If this layer does not work for outputs of ReLU functions, how can I apply sparsity regularization correctly? 

Thank you very much!

**Comment by antonysamuelb** [comment]
Was your issue solved? I am trying to implement L2 regularization, and I have no idea how to do it!

**Comment by GaiYu0** [comment]
Nope...

**Comment by szha** [comment]
@GaiYu0 @antonysamuelb you can use the `MakeLoss` operator described here http://mxnet.io/api/python/symbol.html#mxnet.symbol.MakeLoss

**Comment by eric-haibin-lin** [comment]
@GaiYu0  doesn't ReLU already encourages sparsity (as in, negatives are replaced by zeros)? 
The identity_kl_sparse_reg is for sigmoid activation. 
https://github.com/apache/incubator-mxnet/blob/master/src/operator/identity_attach_KL_sparse_reg-inl.h#L62
