### ISSUE TITLE
Replace element_mask

### ISSUE THREAD

**Issue by data-compute-geek** [apache/incubator-mxnet#5739]
I am trying to re-code the following code,

next_c = mx.sym.element_mask(next_c, mask, name="t%d_l%d_c" % (seqidx, layeridx))

with 

next_c = next_c*mask.reshape([mask.size]+[1]*next_c.shape[1]);
next_c._set_attr(name="t%d_l%d_c" % (seqidx, layeridx));

I got an error:
AttributeError: 'Symbol' object has no attribute 'reshape'

What would be the proper way to code it? 
Thanks.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
