### ISSUE TITLE
Creating and reading dmlc::InputSplit from Python? 

### ISSUE THREAD

**Issue by jmerkow** [apache/incubator-mxnet#5749]
Is it possible to use dmlc::InputSplit from Python. I have code Python code which packs my custome data into record files and iterators which read the packed data and convert to NDArray for training. I am trying to split up the record files as described [here](http://mxnet.io/architecture/note_data_loading.html), but cannot find any uses of dmlc::InputSplit for reading or writing anywhere but c++.  Is this feature only available for code written in c++?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
