### ISSUE TITLE
How can I get the value of the output of the last backword node?

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#5758]
When mxnet process a fc-network, the noeds in the graph executor are just like belows.
 0:data
1:flatten
2:fullyconnected1_weight
3:fullyconnected1_bias
4:fullyconnected1
5:relu6
6:drop6
7:fullyconnected2_weight
8:fullyconnected2_bias
9:fullyconnected2
10:relu7
11:drop7
12:fullyconnected3_weight
13:fullyconnected3_bias
14:fullyconnected3
15:softmax_label
16:softmax
17:softmax_backward
18:fullyconnected3_backward
19:drop7_backward
20:relu7_backward
21:fullyconnected2_backward
22:drop6_backward
23:relu6_backward
24:fullyconnected1_backward

After run the backward operations by 'RunOps(true, num_forward_nodes_, idx.num_nodes());'
I can get the value of the output of the node 23 by 'op_nodes_[23].exec->out_array[0]'.
But the value in 'op_nodes_[24].exec->out_array[0]' has many 'nan'.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
