### ISSUE TITLE
[Bug Report]mxnet.io.DataBatch.index return all values as 0

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#5759]
I use im2rec to convert images to rec file. But when i get databatch, it gives index as 0.  Does anyone meet the same issue?

**Comment by kevinthesun** [comment]
Can you provide more details about your issue? Some codes?

**Comment by akturtle** [comment]
hi,@kevinthesun .  here is a simple code to present this issue. The batch.index give results as 0 value.

import mxnet as mx
import numpy as np
batchSize = 64
dataPrefix = '/home/dataSet/'
train_dataiter = mx.io.ImageRecordIter(
        shuffle=True,
        path_imgrec= dataPrefix +'flowers/flowers_train.rec',
        rand_crop=True,
        rand_mirror=True,
        data_shape=(3,224,224),
        label_width =1,   
        batch_size=batchSize,
        preprocess_threads=4)
batch =train_dataiter.next()
print batch.index

**Comment by kevinthesun** [comment]
Do all databatch have 0 index? If so:

`
    def getindex(self):
        index_size = ctypes.c_uint64(0)
        index_data = ctypes.POINTER(ctypes.c_uint64)()
        check_call(_LIB.MXDataIterGetIndex(self.handle,
                                           ctypes.byref(index_data),
                                           ctypes.byref(index_size)))
        address = ctypes.addressof(index_data.contents)
        dbuffer = (ctypes.c_uint64* index_size.value).from_address(address)
        np_index = np.frombuffer(dbuffer, dtype=np.uint64)
        return np_index.copy()
`

You can try to print index information in MXDataIterGetIndex to see whether something is wrong.

**Comment by akturtle** [comment]
@kevinthesun I set the batchSize = 1 and  print the address and index value:
140725274544400
[0]
140725274574896
[0]
140725274576464
[0]
140725274576912
[0]
140725274573776
[0]

**Comment by mcxkarakoc** [comment]
@kevinthesun @akturtle This is so true. I'm facing with the issue for two weeks. Was it resolved?

MxNet commit hash: f89f96540ec477de6f2e0fee5001df0b78810316

**Comment by mcxkarakoc** [comment]
I've found the bug. `ImageRecordIter` does not copy indices to batch (see `ParseNext()` in `src/io/iter_image_recordio_2.cc`). However, `ImageRecordIter_v1` works correctly. @kevinthesun @akturtle

**Comment by akturtle** [comment]
@mcxkarakoc Thanks, I'll test ImageRecordIter_v1.

**Comment by akturtle** [comment]
@mcxkarakoc WOW, ImageRecordIter works well. I found it has a lot of data augmentation methods. Could you give me some hints how to use them?

**Comment by mcxkarakoc** [comment]
Sorry, I don't have any practice about augmentation methods. @akturtle

**Comment by mcxkarakoc** [comment]
I think this issue should be reopened and marked as bug since` ImageRecordIter `works incorrectly. @kevinthesun

**Comment by akturtle** [comment]
@mcxkarakoc Hi, I reopened this issue. But i don't how to report bug

**Comment by JACKHAHA363** [comment]
So how to fix this bug? Do we have to use ImageRecordIter_V1 then?

**Comment by JDwangmo** [comment]
Now, the problem still exists.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by tuoyuxiang** [comment]
都2021年了，这个bug还没人修复？？

**Comment by tuoyuxiang** [comment]
> 都2021年了，这个bug还没人修复？？

It's 2021 now, the bug still alive here?
