### ISSUE TITLE
Split an existing symbol graph into 2 symbols

### ISSUE THREAD

**Issue by bearsroom** [apache/incubator-mxnet#5762]
Say we have a symbol like AlexNet model, which outputs are 
```
['data',
 'conv1_weight',
 'conv1_bias',
 'conv1_output',
 'activation0_output',
 'lrn0_output',
 'pooling0_output',
 'conv2_weight',
 'conv2_bias',
 'conv2_output',
 'activation1_output',
 'lrn1_output',
 'pooling1_output',
 'conv3_weight',
 'conv3_bias',
 'conv3_output',
 'activation2_output',
 'conv4_weight',
 'conv4_bias',
 'conv4_output',
 'activation3_output',
 'conv5_weight',
 'conv5_bias',
 'conv5_output',
 'activation4_output',
 'pooling2_output',
 'flatten0_output',
 'fc1_weight',
 'fc1_bias',
 'fc1_output',
 'activation5_output',
 'dropout0_output',
 'fc2_weight',
 'fc2_bias',
 'fc2_output',
 'activation6_output',
 'dropout1_output',
 'fc3_weight',
 'fc3_bias',
 'fc3_output',
 'softmax_label',
 'softmax_output']
```
Now I just want to split this symbol into 2 symbols, for example, the first symbol "bottom" includes nodes from `data` to `flatten0_output`, and the second symbol "top" ONLY includes nodes from `flatten0_output` to `softmax_output`. The former can be achieved by `flatten = alexnet.get_internals()['flatten0_output']`, but after getting node `flatten0_output` , I cannot cut the connection between `flatten0_output` and previous nodes, i.e the second symbol "top" is exactly the original symbol.

Splitting a symbol into 2 symbols is for model-parallelism usage, in this way we can put the first symbol "bottom" into a `mxnet.mod.Module` using GPU 1 and the second symbol "top"  into another `mxnet.mod.Module` using GPU2. This could be a method to implement model-parallelism for an existing symbol, but if you have another option, please let me know.
Thanks!

**Comment by piiswrong** [comment]
to_json and load_json

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
