### ISSUE TITLE
Would it be a good idea to output initialisation details?

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#5776]
I found that the initialisation has no rich information, so it is hard to make sure if the initialisation is correct. Would it be better to output the everything done in initialisation step like what weights are initialised with what values? Like caffe, it has different level of log, so we can see the info we need.

**Comment by zhreshold** [comment]
+1. Probably with verbose level in initializer.

**Comment by ascust** [comment]
Is it good to make initialisers verbose?

**Comment by piiswrong** [comment]
yes. we can print something similar to keras. But need to set the logging levels right.

**Comment by ascust** [comment]
@piiswrong as far as I can see in "initializer.py". Only class "Load" has this verbose option, but the other initialisers don't have such a thing.

**Comment by ascust** [comment]
@piiswrong Any progress on this? I tried to modify it but it seems a little bit complicated because there are two parts, a legacy part and a newer part. Things got a little bit messed up.

**Comment by JohanCao** [comment]
@piiswrong I find this to be a problem as well, it is good to  output initialisation details

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
