### ISSUE TITLE
Float64 support for symbolic dot operator

### ISSUE THREAD

**Issue by zhenwendai** [apache/incubator-mxnet#5783]
The symbolic "dot" operator cannot handle float64 with the error message: 

[15:52:00] src/operator/tensor/./matrix_op-inl.h:349: Check failed: outputs[0].type_flag_ == kFloat32 (1 vs. 0) dot only support 32 bit float so far

Matrix multiplication is such a common functionality. Is there any plans to add the support soon?

A simple example to recreate the situation:
```python
import mxnet as mx
import numpy as np
L = np.random.rand(4,4)
L_mx = mx.sym.Variable('L',dtype=np.float64)
o_mx = mx.sym.dot(L_mx,mx.sym.transpose(L_mx))
f = o_mx.simple_bind(mx.cpu(),L=(4,4),grad_req='write')
f.forward(L=L,is_train=True)[0].asnumpy()
```

**Comment by piiswrong** [comment]
You can use FullyConnected(no_bias=True) for now. Will fix later

**Comment by zhenwendai** [comment]
Cool, thanks for the information!

It would be great to have this info in the error message, so that other users could know this work-around.

**Comment by eric-haibin-lin** [comment]
Should be fixed by https://github.com/apache/incubator-mxnet/pull/6756
