### ISSUE TITLE
loading image with mx.image.imdecode(, flag=0)

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#5793]
An error arised:
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::ipp_cvtColor, file C:\buildslave64\win64_amdocl\master_PackSlave-win64-vc14-shared\opencv\modules\imgproc\src\color.cpp, line 7341

How can I fix it
## Environment info
Operating System: Ubuntu and Windows

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version:0.9.5

Or if installed from source: yes

MXNet commit hash (`git rev-parse HEAD`): 

If you are using python package, please provide

Python version and distribution: 2.7.12

**Comment by piiswrong** [comment]
your image is broken. opencv cannot recognize it

**Comment by poorfriend** [comment]
@piiswrong , Thank you. My image is fine, when I use flag=1, everything is ok.

**Comment by Mochimazui** [comment]
@piiswrong. I'm afraid this is a bug.
https://github.com/dmlc/mxnet/blob/986b736b816018b96e9d1e2c358bb7665b80944d/src/io/image_io.cc#L94
In this function, setting param.flag = 0 makes cv::imdecode loading a grayscale image. 
However following color conversion code 
` if (param.to_rgb) {
      cv::cvtColor(dst, dst, CV_BGR2RGB);
}`
didn't check this flag and may call cv::cvtColor on a CV_8UC1 image which triggers assertion 
> OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::ipp_cvtColor

@poorfriend You may pass to_rgb=0 to imdecode when loading grayscale image to avoid this conversion.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
