### ISSUE TITLE
Model Parallelism

### ISSUE THREAD

**Issue by hondaathma** [apache/incubator-mxnet#5807]
Does MXNET support model parallelism?

What I mean is I have 2 GPUs (12GB each).A single Caffe model (Resnet152 with some changes and additions) exceeds 12GB memory and does not fit in a single GPU for training. How can I solve that problem with 2 GPUs?
Can I split this huge model to both the GPUs and make sure they communicate gradients with each other?
If so what all should I change in the solver/train files in MXNET?

**Comment by eric-haibin-lin** [comment]
Yes it does
http://mxnet.io/how_to/model_parallel_lstm.html

**Comment by KeyKy** [comment]
Is there any other easier examples about model parallel? I want to put resnet in gpu2 and lenet in gpu0

**Comment by kaonashi-tyc** [comment]
The example in the tutorial is no longer available
