### ISSUE TITLE
The sequential module example in mxnet/example/module/sequential_module.py does not work for python3

### ISSUE THREAD

**Issue by sumethy** [apache/incubator-mxnet#5809]
When I run the example code at mxnet/example/module/sequential_module.py with Python 3, I get the following error. I didn't modify the code in any way except change `demo_data_model_parallelism` in line 10 to `False` as I don't have 4 gpus.

Traceback (most recent call last):
  File "sequential_module.py", line 41, in <module>
    mod_seq.add(mod1).add(mod2, take_labels=True, auto_wiring=True)
  File "/home/sumeth/miniconda3/envs/mx/lib/python3.5/site-packages/mxnet/module/sequential_module.py", line 64, in add
    for key in kwargs.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

However, when I switched to Python 2, it runs fine.

## Environment info
Operating System: Ubuntu 16.04

Package used (Python/R/Scala/Julia): Python 2 and 3

MXNet version: 0.9.3a3

If you are using python package, please provide

Python version and distribution: Anaconda3, python 2.7 and 3.5

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
