### ISSUE TITLE
link in mxnet.io mismatch

### ISSUE THREAD

**Issue by Godricly** [apache/incubator-mxnet#5813]
The content in this [page](http://mxnet.io/tutorials/python/symbol.html) is not matching with [this](https://github.com/dmlc/mxnet/blob/master/docs/tutorials/python/symbol.md). 
Could it be possible to add document of 'mx.name.prefix' into python API page? It is not included yet while hiding in [this](https://github.com/dmlc/mxnet/blob/master/docs/tutorials/python/symbol.md).
 @mli

**Comment by mli** [comment]
sure, will add it later

**Comment by Godricly** [comment]
@mli can we have a headline for Prefix? It's a little difficult to find it.
[Prefix](http://mxnet.io/tutorials/basic/symbol.html)
