### ISSUE TITLE
How to correct run rcnn in windows with cython compiled

### ISSUE THREAD

**Issue by Trangle** [apache/incubator-mxnet#5820]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
windows 10 x64

Compiler:
vs2013 update5
nvcc
gcc

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.5

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
anaconda2 python2.7
anaconda3 python3.5

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
C:\Users\Trangle\Anaconda2\python.exe D:/MyCoding/PublicCode/example2/rcnn/test.py
Traceback (most recent call last):
  File "D:/MyCoding/PublicCode/example2/rcnn/test.py", line 5, in <module>
    from rcnn.tools.test_rcnn import test_rcnn
  File "D:\MyCoding\PublicCode\example2\rcnn\rcnn\tools\test_rcnn.py", line 7, in <module>
    from ..symbol import *
  File "D:\MyCoding\PublicCode\example2\rcnn\rcnn\symbol\__init__.py", line 1, in <module>
    from symbol_vgg import *
  File "D:\MyCoding\PublicCode\example2\rcnn\rcnn\symbol\symbol_vgg.py", line 2, in <module>
    import proposal
  File "D:\MyCoding\PublicCode\example2\rcnn\rcnn\symbol\proposal.py", line 14, in <module>
    from rcnn.processing.nms import py_nms_wrapper, cpu_nms_wrapper, gpu_nms_wrapper
  File "D:\MyCoding\PublicCode\example2\rcnn\rcnn\processing\nms.py", line 3, in <module>
    from ..cython.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. just test rcnn
2.
3.

## What have you tried to solve it?

1. how to compile the needed .pyd for rcnn in windows
2.
3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
