### ISSUE TITLE
Autoencoder: Why is the shape of args set to be (num_hidden,num_input)

### ISSUE THREAD

**Issue by FCInter** [apache/incubator-mxnet#5829]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
CentOS 6.6
Compiler:
gcc 4.8

Package used (Python/R/Scala/Julia):
python

I'm testing the example of autoencoder [here](https://github.com/dmlc/mxnet/tree/master/example/autoencoder).
I don't understand the settings of shapes of args, like follows:

```
args = {'encoder_%d_weight'%istack: mx.nd.empty((num_hidden, num_input), self.xpu),
         'encoder_%d_bias'%istack: mx.nd.empty((num_hidden,), self.xpu),
         'decoder_%d_weight'%istack: mx.nd.empty((num_input, num_hidden), self.xpu),
         'decoder_%d_bias'%istack: mx.nd.empty((num_input,), self.xpu),}
```
Why is the shape of encoder args set to be `(num_hidden, num_input)` instead of `(num_input, num_hidden)`. Suppose `X` is the input data item with dimension `num_input`, then to encode `X`, we should multiply `X` with the transition matrix, which is the `encoder_weight` here. Since `X` is in shape (1,num_input), shouldn't the `encoder_weight` be of shape `(num_input,num_hidden)`? Why it is set to be the transpose?

**Comment by bhokaal2k** [comment]
I guess this is just a convention coming from the statistical pattern recognition domain where the rows of the weight matrix are treated as the basis vectors of the subspace spanned by W and the multiplication from the left is considered as projecting in that subspace. Anyways, it should not matter this is just a convention being followed by MxNet see here https://github.com/dmlc/mxnet/blob/master/src/operator/fully_connected-inl.h#L81

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
