### ISSUE TITLE
Support 3D Convolution

### ISSUE THREAD

**Issue by korneil** [apache/incubator-mxnet#583]

**Comment by pluskid** [comment]
Do you mean 3D convolution (and pooling)?

**Comment by korneil** [comment]
Yes!

**Comment by pluskid** [comment]
cuDNN always support 3D convolution and pooling. We will just need to change the API to adapt that. But for the mshadow backend, I guess need some work to support 3D case.

**Comment by tqchen** [comment]
going to mark it as help wanted, would be great if someone could to open a PR to contribute this:)

**Comment by korneil** [comment]
I implemented a volumetric convolution layer that uses only cudnn for the sake of brevity. Bc the input is now 5D instead 4, I will have to adopt activation layer as well for 5D. Do you recomment to create a new layer like "VolumetricActivation", or would you rather prefer to change the code of the current activation operator?

**Comment by korneil** [comment]
Also I have a problem with `cudnnAddTensor()` in regard of bias, maybe you can help.

I am creating the tensor with this command:

        if (!param_.no_bias) {
            Tensor <gpu, 1> bias = in_data[conv::kBias].get<gpu, 1, real_t>(s);
            int biasDimA[] = {1, (int) bias.shape_[0], 1, 1, 1};
            int biasStrideA[] = {
                    (int) bias.shape_[0],
                    1,
                    1,
                    1,
                    1
            };
            CHECK_EQ(cudnnSetTensorNdDescriptor(bias_desc_, dtype_, 5, biasDimA, biasStrideA), CUDNN_STATUS_SUCCESS);
        }

but this part at `Forward()` term gives cudnn error CUDNN_STATUS_NOT_SUPPORTED:

                if (!param_.no_bias) {
                    beta = 1.0f;
                    Tensor <gpu, 1> bias = in_data[conv::kBias].get<gpu, 1, real_t>(s);
                    int ret = cudnnAddTensor(s->dnn_handle_,
                                             CUDNN_ADD_SAME_C,
                                             &alpha,
                                             bias_desc_,
                                             bias.dptr_,
                                             &beta,
                                             out_desc_,
                                             out.dptr_);
                    LOG(INFO) << "ret: " << ret;
                    CHECK_EQ(ret, CUDNN_STATUS_SUCCESS);
                }

Do you have idea?

**Comment by piiswrong** [comment]
@korneil I think activation should work for any input dimension, like the non-cudnn version already does.

**Comment by kayhan-batmanghelich** [comment]
Hi @korneil, thanks for the post. I was wondering if you manage to get it running?

**Comment by Godricly** [comment]
Here is some nice work by @Liquidburner and his coworkers. Including pooling,BN,conv. 

There are several issues to be solved:
1. The code is a llittle outdated. 
2. it is only available using cudnn on gpu.
3. cudnnv5 Issue
        cudnnSetFilterNdDescriptor function requires a format input only considered 4D case. It still works for me when I use NCHW format, but I'm still worried about it. I wrote an email to nvidia but no answer yet.

link: [mxnet supporting 3d](https://github.com/Liquidburner/mxnet/tree/master/src/operator)

**Comment by tqchen** [comment]
depending on how complicated it is to share code between 3D and 2D, we can consider start with a 3D conv first, then see if things can be shared. @Godricly you are more than welcomed to lead a charge on this

**Comment by sandeep-krishnamurthy** [comment]
Conv3D is fully supported now - https://github.com/dmlc/mxnet/issues/747

@piiswrong  - Can we close this issue?

**Comment by Pagey** [comment]
are BatchNorm and LRN supported on 3D now? There used to be dimension errors when using them on 3D- as mentioned in [https://github.com/dmlc/mxnet/issues/747](url)

**Comment by Pagey** [comment]
nope still getting this on when trying 3d on layer LRN (mxnet 0.10.1) @sandeep-krishnamurthy 

[12:21:07] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:304: [12:21:07] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\nnvm\include\nnvm/tuple.h:439: Check failed: dim == static_cast<int>(ndim()) (4 vs. 5) dimension do not match target dimension 4 vs 5
[12:21:07] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:304: [12:21:07] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\engine\./threaded_engine.h:329: [12:21:07] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\nnvm\include\nnvm/tuple.h:439: Check failed: dim == static_cast<int>(ndim()) (4 vs. 5) dimension do not match target dimension 4 vs 5
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

**Comment by Pagey** [comment]
but BatchNorm on 3d is working 👍

**Comment by yajiedesign** [comment]
https://github.com/apache/incubator-mxnet/pull/5615
