### ISSUE TITLE
pip installation  does not check libcudnn version

### ISSUE THREAD

**Issue by divfor** [apache/incubator-mxnet#5835]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu desktop 16.04.2
Compiler:
Not used
Package used (Python/R/Scala/Julia):
Python
MXNet version:
version pip install mxnet-cu80,  0.9.3a3
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python 2.7.112
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.5: cannot open shared object file: No such file or directory

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. I want to try libcudnn 6 but found both pip installations of tensorflow and mxnet requires libcudnn.so.5 to import. I download and install libcudnn 6 from https://developer.nvidia.com/cudnn.
2. pip install mxnet-cu80, and it is silently installed successfully.
3. import mxnet as mx, and it prints error: **OSError: libcudnn.so.5: cannot open shared object file**

## What have you tried to solve it?

1. force pip install to check the depended libcudnn version,
2.  let pip install to select correct pre-compiled mxnet binaries to install
3.

**Comment by ysh329** [comment]
Same problem on a server which has been installed MXNet by some user.

**Comment by ysh329** [comment]
After set `USE_CUDNN=0` :crying_cat_face: , it's ok :rofl:

**Comment by szha** [comment]
In 0.9.3, installing cudnn was part of the instruction since there's no run-time detection for loading the .so. Starting from 0.9.5, cudnnv6 is statically linked and shipped as part of mxnet, so you don't need to install cudnn any more. 0.9.5 pip packages have been released for a while and should have resolved this problem.

**Comment by ysh329** [comment]
@szha Thanks, I'm trying......

**Comment by szha** [comment]
@ysh329 Let me know how it goes.

**Comment by ysh329** [comment]
@szha it's okay to install `mxnet-cu80`. Thanks a lot !

**Comment by szha** [comment]
Great to hear that. Feel free to close this issue when you're ready.

**Comment by SherlockLiao** [comment]
@szha hello, I pip install mxnet-cu80, I met this problem, do u know how can I solve this? Thank u!

**Comment by szha** [comment]
@SherlockLiao hi, just to be sure could you run `pip install -U mxnet-cu80` to make sure it's the latest, and then test?

**Comment by SherlockLiao** [comment]
@szha Thank u so much, it works! so happy!

**Comment by szha** [comment]
@divfor is this still an issue for you?

**Comment by divfor** [comment]
@szha it is solved, thanks!

**Comment by szha** [comment]
@divfor no problem. Feel free to close this issue.
