### ISSUE TITLE
 How to train my own data with fcn-xs

### ISSUE THREAD

**Issue by zht3344** [apache/incubator-mxnet#5836]
I want to train my own data with fcn-xs,  the data have 2 class (include the  background),I know is that it should change the numclass in the fcn_xs.py, are there any other places to change ? And what's the requirements for the size of images?

Can anybody help me ? I am not quite sure what should I do for training with my own data. It is a little complicated for me. 

MXNet version:0.9

**Comment by Hjy20255** [comment]
i have  the same question

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
