### ISSUE TITLE
Error caused by two different dependencies in protobuf version when using both distributed mode and tensorboard

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [apache/incubator-mxnet#5837]
When trying to use distributed mode in MXNet and tensorboard for MXNet
(https://github.com/dmlc/tensorboard),
because distributed MXNet(especially from ps-lite) needs protobuf-2.5.0 version(see https://github.com/dmlc/ps-lite/blob/acdb698fa3bb80929ef83bb37c705f025e119b82/make/deps.mk)
but tensorboard requires protobuf-3.2.0 version,
and it causes below error(see ## Error Message).

To use both distributed machine and tensorboard for MXNet, I think the
1. protobuf version should be the same(2.5.0 to 3.2.0 upgrade protobuf version for ps-lite)  
or 
2. another work around code should be introduced.

Tensorboard features are very helpful for developers, so I look forward to be able to use it under distributed mode.
Thanks in advance.

## Environment info
Operating System:
Ubuntu 16.04
Compiler:

Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.5
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires ver                                                                             sion 3.2.0 of the Protocol Buffer runtime library, but the installed version is                                                                              2.5.0.  Please update your library.  If you compiled the program yourself, make                                                                              sure that your headers are from the same version of Protocol Buffers as your lin                                                                             k-time library.  (Version verification failed in "google/protobuf/descriptor.pb.                                                                             cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException                                                                             '
  what():  This program requires version 3.2.0 of the Protocol Buffer runtime li                                                                             brary, but the installed version is 2.5.0.  Please update your library.  If you                                                                              compiled the program yourself, make sure that your headers are from the same ver                                                                             sion of Protocol Buffers as your link-time library.  (Version verification faile                                                                             d in "google/protobuf/descriptor.pb.cc".)
Aborted (core dumped)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Set USE_DIST_KVSTORE = 1 in config.mk to use distributed machine
2. Install tensorboard for mxnet from https://github.com/dmlc/tensorboard
3. test some tensorboard related code with mxnet

## What have you tried to solve it?

1. 
2.
3.

**Comment by zihaolucky** [comment]
@Soonhwan-Kwon Do you solve your problem? Try `pip install tensorboard` to walk around the protobuf issue on tensorboard.

**Comment by LakeCarrot** [comment]
I met the same problem, with MXNet v0.10.0support and Ubuntu 14.04 with GPU, S3 and distributed training support.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
