### ISSUE TITLE
Padding for page titles is wacky. Needs to be less wacky.

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#5840]
On MXNet.io the padding is currently strange. The page titles, e.g. "Tutorials" appears to close to the top of the page. This should have padding-top: 40px; Also they are not aligned with the TOC. Please make the TOC line up with the section titles (currently padding-top is 20px, should also be 40px).  Can you please fix this @kevinthesun? Thanks!

<img width="753" alt="screenshot 2017-04-14 11 29 14" src="https://cloud.githubusercontent.com/assets/2390222/25052260/bffe9e3e-2105-11e7-97d8-e047d1013888.png">

**Comment by kevinthesun** [comment]
Can we close this?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by SuperLinguini** [comment]
Proposed labels: Doc, Feature Request

Potentially close this issue.
