### ISSUE TITLE
Broadcast_to with inferred size

### ISSUE THREAD

**Issue by jmacglashan** [apache/incubator-mxnet#5842]
There are a number of scenarios in which I'd like to broadcast/repeat/tile a tensor to a size that matches a batch size determined at binding time. This would mean that I'd like to be able to have the size of the broadcast based on one of those shape elements. However, it seems those methods require an upfront constant when defining the graph, which takes some of the wind out of shape inference. It would be nice to have auxiliary functionality that let you specify the size by looking at an axis of the shape of some input symbol that gets ground at shape-inference time.

**Comment by piiswrong** [comment]
if you leave some axis as 0 in broadcast it will be infered from upward layers

**Comment by jmacglashan** [comment]
Thanks, that will indeed help with most scenarios. Unfortunately for the scenario I'm currently in, it won't help because the result after my broadcast is an output symbol (or at least is a symbol that is only further processed in ways that won't reveal the final shape I need) and I'd really like to pin it to some other symbol that I know it must mirror in batch size.

This is a rather special case, but I do feel like being able to access and define shapes symbolically may ultimately be useful in other contexts.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
