### ISSUE TITLE
Jupyter notebook  DeprecationWarning: encoder.py:207 Interpreting naive datetime as local

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#5849]
When I execute below codes in Jupyter Notebook, screen printed below warning message:
```ipython
import mxnet as mx
/usr/local/lib/anaconda2/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2017-04-15 21:14:24.451223. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)
```
However, when I execute in ipython or python command, everything is okay!

**Comment by SherlockLiao** [comment]
I have the same question, but I don't know how to fix that.

**Comment by aaron235** [comment]
Hey!

Check this out, it (mostly) solves the issue:

https://github.com/jupyter/notebook/issues/2239

**Comment by merl-dev** [comment]
Explored all the solutions and links, but none seems to help.  Constantly getting this warning message making mxnet unusable from jupyter notebook. And this is localised only to mxnet under jupyter, and no other package.  Is there an mxnet solution?

**Comment by slye0612** [comment]
@merl-dev so do I, have you  solved the problem now?

**Comment by merl-dev** [comment]
Since this is only a problem in python jupyter (which is unfortunate), I decided that until resolved I'll work with mxnet through Julia/Flux where it runs well as a backend and enables lower level direct access to mxnet functionality.

**Comment by ysh329** [comment]
unresolved.
