### ISSUE TITLE
Cannot find custom operator type proposal

### ISSUE THREAD

**Issue by sugartest007** [apache/incubator-mxnet#5865]
`....
{
      "op": "Custom", 
      "name": "rpn_rois", 
      "attr": {
        "feat_stride": "16", 
        "is_train": "False", 
        "op_type": "proposal", 
        "ratios": "(0.5, 1, 2)", 
        "scales": "(4, 8, 16, 32)"
      }, 
      "inputs": [[355, 0, 0], [358, 0, 0], [359, 0, 0]]
    }
....`
work in python2.7. (resave json from https://github.com/tornadomeet/mxnet-face/blob/master/detection)
but error in c++ using "MXPredCreate" api .
src/operator/custom/./custom-inl.h:128: Check failed: registry_.find(param_.op_type) != registry_.end() Cannot find custom operator type proposal

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
