### ISSUE TITLE
How to make some convolution weights same in a network

### ISSUE THREAD

**Issue by poorfriend** [apache/incubator-mxnet#5866]

**Comment by zhreshold** [comment]
shared_weight = mx.sym.Variable("shared_weight", shape=(3, 64, 3, 3))
conv1 = mx.sym.Convolution(data=data, weight=shared_weight, name="conv1", ...)
conv2 = mx.sym.Convolution(data=conv1, weight=shared_weight, name="conv2",...)

**Comment by poorfriend** [comment]
@zhreshold Thank you

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
