### ISSUE TITLE
AttributeError: module 'mxnet' has no attribute 'symbol'

### ISSUE THREAD

**Issue by Tianyang-Yang** [apache/incubator-mxnet#5868]
## Environment info
Operating System: Ubuntu 16.04LTS
Compiler: g++
MXNet version: 0.93
Using quick installation for python.
Python version and distribution: Python 3.6 in anaconda.

## Error Message:
Just a simple input:
`import mxnet as mx`
`a = mx.symbol.Variable('a')`
Then I got the message:
`AttributeError: module 'mxnet' has no attribute 'symbol'`

And I find that all the attributes in my `mxnet` module are only `__doc__`, `__loader__`, `__name__`, `__path__`, `__spec__` and `__package__`.
I have tried to reinstall `mxnet` but still receive this message.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by TangDL** [comment]
https://github.com/szha Hi，when  I run  example/image-classificati/train_mnist.py --network lenet --gpus 0, I meet this issue now,can you tell me how to slove it?

**Comment by szha** [comment]
@TangDL would you mind creating a new issue for the problem? We will need some additional information from you to best help. You will be able to provide the information by filling out the issue template.
