### ISSUE TITLE
if it's easy to distribute a model to the online system 

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#5874]
deep learning will be widely used on industry I think

**Comment by janelu9** [comment]
can I get the parameters visually after training ？so I can rebuild a only predicted model online

**Comment by janelu9** [comment]
paddle gives the user  different layer's parameters visible by different files

**Comment by moveforever** [comment]
you can see any layer's parameter
you can use 
`all_layers = sym.get_internals()['sym_name']`

**Comment by moveforever** [comment]
yes, it can. you can see any layer's parameter.
you can refer use function `load_checkpoint`  to load all parameters
`sym, arg_para, aux_para = load_checkpoint(prefix, epoch)`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
