### ISSUE TITLE
Is there a way could debug through python and c++ smoothly 

### ISSUE THREAD

**Issue by kernel8liang** [apache/incubator-mxnet#5880]
as the title.

**Comment by eric-haibin-lin** [comment]
You can use gdb for c++ and pdb for python. 

On 2017年4月18日, at 02:53, liang <notifications@github.com> wrote:

as the title.

**Comment by kernel8liang** [comment]
currently， I use both at same time, I need switch tab time to time, so I hope there is one combined them.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
