### ISSUE TITLE
request on updating docs and examples about rnns

### ISSUE THREAD

**Issue by skywalkerytx** [apache/incubator-mxnet#5896]
I noticed from python API that `symbol.RNN` and `symbol.rnn._` has been added to mxnet.

`net = mx.sym.RNN(data=net,state_size = 1234,num_layers=56,mode = 'lstm', p =0.1)` 

exists in python api doc but no example and further explaination - i pretty much like this one because it looks very simple and easy to usee btw

`mx.rnn.LSTMCell(100, prefix='rnn_', forget_bias=1.0)`

 exists in example but API docs contains no info about the whole `mx.rnn` module

and tutorials about rnn are still using `lstm.py` that write by their own - outdated for mxnet now.

**Comment by piiswrong** [comment]
@mli

**Comment by mli** [comment]
@piiswrong shall we recommend to use `mx.rnn` instead of `mx.sym.RNN`?

**Comment by piiswrong** [comment]
yes.
the rnn package needs a intro page.
RNNParam will be refactored to be the same with nn.Parameter soon.

**Comment by skywalkerytx** [comment]
so the `mx.rnn` is the promising future?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
