### ISSUE TITLE
Intel MKL version

### ISSUE THREAD

**Issue by kice** [apache/incubator-mxnet#5917]
This commit (https://github.com/dmlc/mxnet/pull/5000) requires Intel MKL 2018 beta, which some features are not available in Intel MKL 2017.

For example: 
File: src\operator\mkl\mkl_pooling-inl.h
```
line 183:
    case pool_enum::kAvgPooling:
      algorithm = (param_.pooling_convention == pool_enum::kValid) ?
          dnnAlgorithmPoolingAvgIncludePadding : dnnAlgorithmPoolingAvg;
```
dnnAlgorithmPoolingAvgIncludePadding is only defined in Intel MKL 2018 beta: https://software.intel.com/en-us/mkl-developer-reference-c-2018-beta-enumerated-types

And currently it was not defined: https://software.intel.com/en-us/node/684760 (Intel MKL 2017 update 2)

**Comment by wguo68** [comment]
But I have no intel mkl2018 just 2017. how to do with it?

**Comment by kice** [comment]
@wguo68 https://software.intel.com/en-us/articles/intel-mkl-2018-beta-is-now-available

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
