### ISSUE TITLE
Dynamic Graphs

### ISSUE THREAD

**Issue by davidbuniat** [apache/incubator-mxnet#5918]
### Feature Request

Would be great to have dynamic unrolling of recurrent nets (LSTMs, GRUs, etc.) for training long sequences. Also to be able to implement Recursive Nets. Multidimensional Recurrent Nets (e.g. PixelRNN or PyramidLSTM) used for images require very pretty long timesteps to parse pixel by pixel. Theano scan is limited to 1D sequences and it is quite tricky to implement MDRNNs in Tensorflow. Also Memory Networks/Differential Neural Computer would benefit from dynamic graphs.

**Comment by piiswrong** [comment]
see here for a dynamic graph package similar to pytorch: https://github.com/dmlc/mxnet/pull/5705

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
