### ISSUE TITLE
Exponential symbol error

### ISSUE THREAD

**Issue by ywi4ebyrawi** [apache/incubator-mxnet#5926]
MXNet version installed from source0.9.5 62ecb60fb327e615db1b8b22ccaf7b0230598a29
Python version and distribution: 2.7

## Error Message:
O.K. in documents (http://mxnet.io/api/python/symbol.html#mxnet.symbol.MakeLoss) it's told that exp([0, 1, 2]) = [inf, 1, 0.707]. So the question is what the hell exponent you use?

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
exp([0, 1, 2]) = [inf, 1, 0.707]

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
