### ISSUE TITLE
updating mxnet pip package

### ISSUE THREAD

**Issue by ogail** [apache/incubator-mxnet#5932]
The current mxnet version in pip isn't in sync with github master branch and some of the examples are not working because mxnet pip package does not have `contrib` package yet. Please update the pip package with what's latest in master branch. Here are repro steps:
```
$ pip install mxnet # installed mxnet-0.9.3a3
$ git clone https://github.com/dmlc/mxnet.git
$ cd mxnet/example/rcnn
$ python demo.py --prefix model/final --epoch 0 --image output/too-cute-doggone-it-video-playlist.jpg --gpu 0
Traceback (most recent call last):
  File "demo.py", line 142, in <module>
    main()
  File "demo.py", line 136, in main
    symbol = get_vgg_test(num_classes=config.NUM_CLASSES, num_anchors=config.NUM_ANCHORS)
  File "/home/ubuntu/rcnn/rcnn/symbol/symbol_vgg.py", line 276, in get_vgg_test
    rois = mx.contrib.symbol.Proposal(
AttributeError: 'module' object has no attribute 'contrib'
```

**Comment by szha** [comment]
0.9.5 has been released a while back, which should have solved this problem.

**Comment by great-thoughts** [comment]
The latest i could install after updating pip was mxnet-0.9.3a1. I need the 3D deconvolution from 0.9.5. Is there a way to install 0.9.5 through pip?

**Comment by szha** [comment]
Yes, I meant that the pip wheels for 0.9.5 has been released. Could you try `pip install -U mxnet`?
