### ISSUE TITLE
mkl/mkl_pooling-inl.h(185): error C2065: 'dnnAlgorithmPoolingAvgIncludePadding': undeclared identifier

### ISSUE THREAD

**Issue by wguo68** [apache/incubator-mxnet#5940]
When I compile mxnet on windows 10 using VS2015

**Comment by piiswrong** [comment]
mkl doesn't work for windows. please compile without mkl2017

**Comment by wdx04** [comment]
Just replace dnnAlgorithmPoolingAvgIncludePadding with dnnAlgorithmPoolingAvg and do not use average pooling with padding in your model design.
I was able to compile libmxnet with Visual Studio 2015 and MKL2017 Update 2 on Windows and run train_mnist.py on both CPU and GPU without problem. But training my own FCN-like model for semantic segmentation on GPU strangely crashed inside a MKL dll(even if I turn of USE_MKL_EXPERIMENTAL option), though training the same model on CPU did not crash. By the way, the MKLDNN-enabled version is around 3.5X as fast as the libopenblas version when training my model on CPU.

**Comment by wdx04** [comment]
Update: MKL 2017 Update 3 is out, dnnAlgorithmPoolingAvgIncludePadding is added in this release.
Also I found the cause of the crash when training my model resides in dropout-inl.h, where the MKL+OpenMP optimized path does not work in GPU context. Modifying the code to use the default path  fixes the crash.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
