### ISSUE TITLE
Problems about training speed

### ISSUE THREAD

**Issue by z-xiuxiu** [apache/incubator-mxnet#5942]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 14.04

Compiler:

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.4

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:python 2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
I have a problem about the speed. when I train a model, the speed is lower and lower during the training process. I use 4 gpus (TITAN X) and here is the training speed. Could anyone give me some help? thanks!

![screenshot from 2017-04-22 15 43 00](https://cloud.githubusercontent.com/assets/27837384/25302536/af711f2e-2772-11e7-8f9b-2897b2dd2aee.png)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by eric-haibin-lin** [comment]
What's the model you are training? Can you provide a minimal reproducible example?

**Comment by z-xiuxiu** [comment]
Here is my model.  This model is trained to generate image quality score for LIVE In the Wild Challenge Database. I use the VGG16 structure, using a deconvolution layer replace  all connection layers, the last layer is mae regression to predict the image quality scores.
![Uploading Screenshot from 2017-04-23 09;41;46.png…]()
![Uploading Screenshot from 2017-04-23 09;44;09.png…]()

**Comment by z-xiuxiu** [comment]
Here is my model.  This model is trained to generate image quality score for LIVE In the Wild Challenge Database. I use the VGG16 structure, using a deconvolution layer replace  all connection layers, the last layer is mae regression to predict the image quality scores.

**Comment by z-xiuxiu** [comment]
![screenshot from 2017-04-23 09 41 46](https://cloud.githubusercontent.com/assets/27837384/25310023/7c4539dc-280d-11e7-8e47-06653525bc9a.png)

**Comment by z-xiuxiu** [comment]
@eric-haibin-lin
![screenshot from 2017-04-23 09 44 09](https://cloud.githubusercontent.com/assets/27837384/25310059/2a38a330-280e-11e7-8a37-8e342b78b243.png)

**Comment by piiswrong** [comment]
may be related to io. see if image reading is the bottle neck

**Comment by starimpact** [comment]
I have the same problem before, but it is changed when I replace the python preprocessing image code into cpp multithreads preprocessing code.

**Comment by z-xiuxiu** [comment]
@piiswrong @starimpact 
Thank you for your answers, I'll try your method, thanks!

**Comment by z-xiuxiu** [comment]
![screenshot from 2017-04-23 09 44 09](https://cloud.githubusercontent.com/assets/27837384/25319988/7df7ae36-28d5-11e7-9f06-0db081a2f188.png)

**Comment by Cv9527** [comment]
@starimpact could you share code of cpp multithreads preprocessing code ?

**Comment by dongxiao92** [comment]
I met the same problem.At then end training process will stop.Do you find any solutions yet?

**Comment by z-xiuxiu** [comment]
After converting data to rec format, the problem is solved @dongxiao92

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
