### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by tmm88** [apache/incubator-mxnet#5944]
**it would be cool if mxnet would feature:**

- _a deep convolutional recursive swarm of hybrid bdi and artificial neural networks;_
- _it would be cool if it would be possible to feed such a thing with elastic fusion for gesture recognition using advanced computer vision algorithms_

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
