### ISSUE TITLE
imread read blank (None) image for file:  *.jpg

### ISSUE THREAD

**Issue by gypsysunny** [apache/incubator-mxnet#5947]
why do i get such error while i use im2rec.py to create .rec file? the file is available and the path is correct. i can run cv2.read to read the same file correctly in a new .py file.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by prateekagarwal3** [comment]
imread read blank (None) image for file: *.jpg

**Comment by sunny1072** [comment]
i am facing the same issue.please share the resolution.

**Comment by hananawi** [comment]
I also encount this problem, and I find that my path contain Chinese then I change it to English, then it works
