### ISSUE TITLE
mxnet.symbol.Symbol.grad not implemented

### ISSUE THREAD

**Issue by GrindstoneLZX** [apache/incubator-mxnet#5951]
I'm going to use mxnet.symbol.Symbol.grad to define my own loss function, however this function is not implemented. 
I found that tensorflow has [this function](https://www.tensorflow.org/api_docs/python/tf/gradients). If there is a way to implement this function in mxnet?
Thank you!

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04
Compiler:
g++
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.5
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
[11:29:30] /home/zxlee/Downloads/mxnet12/dmlc-core/include/dmlc/./logging.h:300: [11:29:30] src/c_api/c_api_symbolic.cc:547: not implemented

Stack trace returned 10 entries:
[bt] (0) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f11b5175b0c]
[bt] (1) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXSymbolGrad+0x4a) [0x7f11b5ddcb4a]
[bt] (2) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7f11c679257c]
[bt] (3) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7f11c6791cd5]
[bt] (4) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7f11c6789376]
[bt] (5) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7f11c6780db3]
[bt] (6) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53) [0x7f11c7d6ae93]
[bt] (7) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x715d) [0x7f11c7e1d80d]
[bt] (8) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e) [0x7f11c7e1fc3e]
[bt] (9) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47) [0x7f11c7e1f1f7]

Traceback (most recent call last):
  File "test_mxnet2.py", line 10, in <module>
    grad = loss.grad(wrt='data')
  File "/home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/symbol.py", line 1076, in grad
    ctypes.byref(handle)))
  File "/home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 83, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:29:30] src/c_api/c_api_symbolic.cc:547: not implemented

Stack trace returned 10 entries:
[bt] (0) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f11b5175b0c]
[bt] (1) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXSymbolGrad+0x4a) [0x7f11b5ddcb4a]
[bt] (2) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7f11c679257c]
[bt] (3) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7f11c6791cd5]
[bt] (4) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7f11c6789376]
[bt] (5) /home/zxlee/miniconda2/envs/mxnet12/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7f11c6780db3]
[bt] (6) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53) [0x7f11c7d6ae93]
[bt] (7) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x715d) [0x7f11c7e1d80d]
[bt] (8) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e) [0x7f11c7e1fc3e]
[bt] (9) /home/zxlee/miniconda2/envs/mxnet12/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47) [0x7f11c7e1f1f7]

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
import mxnet as mx

data = mx.sym.Variable('data')
weight = mx.sym.Variable('weight')
out = data * weight
label = mx.sym.Variable('weight')
loss = (out - label)**2.0
loss = mx.sym.MakeLoss(loss, name='loss')

grad = loss.grad(wrt='data')
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by nicklhy** [comment]
I noticed there is a mx.sym.grad function in the doc. But unfortunately, it has not been fully implemented yet. I guess someone is still working on it and will submit a PR soon.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
