### ISSUE TITLE
Missing information in the module tutorial

### ISSUE THREAD

**Issue by abyoussef** [apache/incubator-mxnet#5960]
In the module tutorial http://mxnet.io/tutorials/python/module.html, there is some missing information that should be added in order to help the reader: 
* In the first script: `from data_iter import SyntheticData`, it should be pointed out that the module data_iter could be found in https://github.com/dmlc/mxnet-notebooks/tree/master/python/basic  in order to run the first script. 
*  There is a missing pointer to `data.ipynb`, as it should point to the following notebook in GitHub: https://github.com/dmlc/mxnet-notebooks/blob/master/python/basic/data.ipynb

**Comment by eric-haibin-lin** [comment]
Thanks for pointing that out. We are still working on improving the documentation and tutorials. Do you mind contributing with a PR to fix it, when you have spare time? 

On 2017年4月24日, at 20:48, Youssef <notifications@github.com> ...

**Comment by abyoussef** [comment]
Yes sure, I can help fix this issue and more.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
