### ISSUE TITLE
Automatic type conversion not supported ?

### ISSUE THREAD

**Issue by EvanzzzZ** [apache/incubator-mxnet#5963]
Writing a program with NDArray using default type 'float32', and turns out the value overflow in the end. 

And it seems like I need to manually change all the variables into 'float64', otherwise the compiler will throw exception. 

While in Numpy, data types will be automatically converted into the advanced one. e.g. a float32 will be converted to float64 if it adds up with a float64.

Do I miss anything here or this is what mxnet support right now.

**Comment by piiswrong** [comment]
there is not automatic type promotion

**Comment by EvanzzzZ** [comment]
After I changed all the NDArray into 'float64', python throw exception and terminate.
Here is the error report, 
`terminating with uncaught exception of type dmlc::Error: [09:50:15] src/engine/./threaded_engine.h:336: [09:50:15] src/operator/tensor/./matrix_op-inl.h:360: Check failed: outputs[0].type_flag_ == mshadow::kFloat32 (1 vs. 0) dot only support 32 bit float so far`

What I missed here?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
