### ISSUE TITLE
Use "aux_args" in OP failed  

### ISSUE THREAD

**Issue by kernel8liang** [apache/incubator-mxnet#5965]
I am writing an OP, which will use the extra args parameter. 

add the extra parameter shape information in OPProp's InferShape
```
 354       Shape<4> _aux_shape = Shape4(param_.num_filter * 16 / param_.num_group, dshape[1] / param_.num_group,                                                          ||-   function
 355                                   param_.kernel[0], param_.kernel[1]);                                                                                               |||     DMLC_DECLARE_PARAMETER 
 356       _aux_shape[0] *= param_.num_group;                                                                                                                             |||     c3x3_16Op [mxnet::op::c
 357       SHAPE_ASSIGN_CHECK(*aux_shape, 0, _aux_shape); 
```
when test it, get 'segment fault'
debug around found when translate mxnet's   ```Registry<::mxnet::OperatorPropertyReg> ```  to nnvm  ```Registry<nnvm::op >```  use closure like below to setup mxnet op's ```InferShape```, which dosen't give the ```aux``` point,  so the function in mxnet op never get the ```aux``` parameter. 

```
  95 bool OpPropInferShape(const NodeAttrs& attrs,
  96                       std::vector<TShape> *iattr,
  97                       std::vector<TShape> *oattr) {
  98   auto finfer = [](const OperatorProperty* op,
  99                    std::vector<TShape> *in,
 100                    std::vector<TShape> *out,
 101                    std::vector<TShape> *aux) {
 102     return op->InferShape(in, out, aux);
 103   };
 104   return OpPropInferAttr(attrs, iattr, oattr, finfer);
 105 }

```

So, if i want to use the extra parameter I still put it in ```in_data```, by ```add_argument``` ?
Is it bug ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
