### ISSUE TITLE
Distributed MXNet Import Error

### ISSUE THREAD

**Issue by caoyue10** [apache/incubator-mxnet#5967]
## Environment info
Operating System: Ubuntu 16.04.1 LTS

Python version and distribution: python 2.7

MXNet version: 0.9.3 Official Release Version
Downloaded from https://github.com/dmlc/mxnet/releases/tag/v0.9.3

But nnvm, dmlc-core, ps-lite and mshadow are not in the release version. So I clone the newest version of these four packages to their directories.

## Error Message:

The compilation procedure of distributed MXNet (USE_DIST_KVSTORE = 1) is passed, but after the compilation and `sudo python setup.py install`, the error occurred when `import mxnet`.

>>> import mxnet
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 2.6.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-pkdHET/mir-0.21.0+16.04.20160330/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 2.6.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-pkdHET/mir-0.21.0+16.04.20160330/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
Aborted (core dumped)

The MXNet version on Single machine (USE_DIST_KVSTORE = 0)  works well.

I've found that the ps-lite package has used the v2.5.0 of protobuf, but the program needs v2.6.0. I don't know how to solve this. 

Thanks.

**Comment by caoyue10** [comment]
@pluskid @mli

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
