### ISSUE TITLE
DeprecationWarning:mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead

### ISSUE THREAD

**Issue by 123chengbo** [apache/incubator-mxnet#5969]
there is something wrong :
.......model.py：870：DeprecationWarning:mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead .

（my mxnet is the latest version）
i am new to python，and confused about this problem， could you give me some advice about how to modify this？

Thank you so much

**Comment by Soonhwan-Kwon** [comment]
It is just warning and there is no valid predict function for multi device for model. Try look at function do_training in the example https://github.com/dmlc/mxnet/blob/master/example/speech_recognition/train.py, it has module implementation.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
