### ISSUE TITLE
Low Precision Support for Inference and Training

### ISSUE THREAD

**Issue by arank** [apache/incubator-mxnet#5978]
Opening issue to track low precision (int8, fp16) training and inference progress as well as support for CUDA8 int8,fp16 acceleration support.

**Comment by arank** [comment]
@piiswrong Can we move this to the "feature request" project in the "in progress" column given @ZihengJiang is working on this and there have been may user requests to track progress on this feature?

Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
