### ISSUE TITLE
Normalization is not done in SoftmaxOutput if N-D label probability array is given

### ISSUE THREAD

**Issue by zhipeng-jia** [apache/incubator-mxnet#5981]
From https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L124, I found normalization property is ignored if shapes of output and label are equal.

Also from https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L171, I found the gradient is divided by s3[2] even if normalization is null. But in the documentation, it says null means "do nothing". I believe the exact behaviors of SoftmaxOutput in each condition (combination of parameters) should be explained in the documentation.

**Comment by jiajiechen** [comment]
Hi Zhipeng, 

You are right the normalization mode is only applied when the softmax output has different shape than the label. 

This API's doc is still under modifying. Here is a preview. Let me know if you have more comments.

<img width="1070" alt="screen shot 2017-04-26 at 5 32 07 pm" src="https://cloud.githubusercontent.com/assets/9403337/25462918/1eb1a340-2aa7-11e7-9f78-393f8cc9e68a.png">


As for your second question, I am not very sure. If there is someone else answers me I will let you know.

**Comment by zhipeng-jia** [comment]
@jiajiechen Thanks for your quick reply.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
