### ISSUE TITLE
Memory leak in Module. Bug?

### ISSUE THREAD

**Issue by mcxkarakoc** [apache/incubator-mxnet#5983]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Compiler: gcc

Package used (Python/R/Scala/Julia): Python

MxNet commit hash: f89f96540ec477de6f2e0fee5001df0b78810316

If you are using python package, please provide

Python version and distribution: 2.7
---------------------------------------------------
I'll explain the issue as a little bit story :) Sorry about this. Let's have a 8GB GPU.

When I've executed the code below, no problem.
```python
A = mx.nd.uniform(...) #Create a 7GB array in GPU
A= None

sleep(1)
A = mx.nd.uniform(...) #Create a 7GB array in GPU
```
However, when I've executed such a code, `CUDA: Out of memory` error occurs when a new 7GB array is being created after `fit()`.

```python
A = mx.nd.uniform(...) #Create a 7GB array in GPU
A= None

sleep(1)

B = mx.mod.Module(...) # Will create and use 1,5GB array in total in GPU
B.fit(...)
B = None # or del B or something else to run garbage collector

sleep(1) # 1, 2 sec or whatever. Does not matter.
A = mx.nd.uniform(...) #Create a 7GB array in GPU, Out of memory
```

How can I force the module to release its GPU memory?

**Comment by mcxkarakoc** [comment]
FYI
I think these are similar issues: 

#2981 
#1176
#3055
#2827
#1946
#1677
#1432
#1526
#2827
#1301

As I see, no basic solution yet.

**Comment by mcxkarakoc** [comment]
@wshenx Since you seem into the this problem, I'd like to ask to you.  Did #2927 really solve the problem? I couldn't find any solution to my problem above. I've tried almost everything. Now, I'm at the point where I will use a subprocess for each module so that CUDA memory will be release after the termination of each subprocess However, this will make my application really complex. If I cannot find a solution within 1-2 days, I have to give up MxNet. I hope other deep learning frameworks do not suffer from the similar problems.

**Comment by mcxkarakoc** [comment]
I've noticed just now that there is Module.reshape. I will try it. I hope it solves my problem.

**Comment by ap-hynninen** [comment]
@piiswrong We might be seeing the effect of this bug in bucketed training where the memory usage creeps up as we introduce more buckets.

**Comment by boyurmit** [comment]
I got the same issue. When creating new executor with different symbol, the old one will never release the gpu memory even if I use "del executor" to delete it.

**Comment by bowenbaker** [comment]
Is there a solution to this yet? I am trying to release the Module so that I can begin training a new network, but it won't release the GPU memory no matter what I do.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by kli-nlpr** [comment]
Is there any solutions for this problem now?

**Comment by samskalicky** [comment]
@sandeep-krishnamurthy the related issues mentioned above have been closed/fixed. Please close this issue as well. Thanks!
