### ISSUE TITLE
Prefetching data using "parallel" threads 

### ISSUE THREAD

**Issue by saurabh3949** [apache/incubator-mxnet#5998]
Does mxnet provide a method to prefetch data into a queue using multiple threads that **actually run in parallel?**

I have textual data and not images. I am using python and multithreading in python is not parallel so I need to use a C++ based method for reading data in a parallel fashion. 

In short, does mxnet have a similar method like that of tensorflow's coordinator and queue runner?
https://www.tensorflow.org/programmers_guide/threading_and_queues

**Comment by piiswrong** [comment]
text is small and easy to load. Are you sure IO is the bottleneck and you really need multithreading?
Most text data fit in memory so you can preload everything

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
