### ISSUE TITLE
Training MNIST example with VGG broken

### ISSUE THREAD

**Issue by thatindiandude** [apache/incubator-mxnet#6018]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 14.04 

Compiler:
gcc 4.8.4

Package used (Python/R/Scala/Julia):
Python

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
06f1c4dee7636f7db3ae22d192ec0ee1a095e100

If you are using python package, please provide

Python version and distribution:
Python2.7 

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

INFO:root:start with arguments Namespace(batch_size=64, disp_batches=100, gpus=None, kv_store='device', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs='10', model_prefix=None, mom=0.9, monitor=0, network='vgg', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_k=0, wd=0.0001)
[23:48:43] /home/ubuntu/src/mxnet/dmlc-core/include/dmlc/logging.h:304: [23:48:43] src/operator/./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (2) exceeds input (1 padded to 1)

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f3a84c4612c]
[bt] (1) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x883) [0x7f3a858e9073]
[bt] (2) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0xd13088) [0x7f3a85724088]
[bt] (3) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x103babd) [0x7f3a85a4cabd]
[bt] (4) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x103d3b2) [0x7f3a85a4e3b2]
[bt] (5) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f3a85a38b18]
[bt] (6) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f3a855d12ae]
[bt] (7) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EESs+0x240) [0x7f3a855d40e0]
[bt] (8) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0x329) [0x7f3a855cbf79]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f3a88b99adc]

infer_shape error. Arguments:
  data: (64, 1L, 28L, 28L)
  softmax_label: (64,)
Traceback (most recent call last):
  File "train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/home/ubuntu/src/mxnet/example/image-classification/common/fit.py", line 187, in fit
    monitor            = monitor)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/base_module.py", line 445, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 205, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 301, in bind_exec
    shared_group))
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 548, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/ubuntu/src/mxnet/python/mxnet/symbol.py", line 747, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/home/ubuntu/src/mxnet/python/mxnet/symbol.py", line 871, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/ubuntu/src/mxnet/python/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator pool5: [23:48:43] src/operator/./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (2) exceeds input (1 padded to 1)

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f3a84c4612c]
[bt] (1) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x883) [0x7f3a858e9073]
[bt] (2) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0xd13088) [0x7f3a85724088]
[bt] (3) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x103babd) [0x7f3a85a4cabd]
[bt] (4) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x103d3b2) [0x7f3a85a4e3b2]
[bt] (5) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x518) [0x7f3a85a38b18]
[bt] (6) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f3a855d12ae]
[bt] (7) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EESs+0x240) [0x7f3a855d40e0]
[bt] (8) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0x329) [0x7f3a855cbf79]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f3a88b99adc]

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. cd ~/src/mxnet/examples/image-classification
2. python2.7 train_mnist.py --network vgg
3.

## What have you tried to solve it?

1. Re-compile MXNet without MKL
2.
3.

**Comment by 123chengbo** [comment]
your image resolution is too small （mnist ：28*28、and you use the original size），so it is too small for vgg（）。
try other dataset and make sure the size is large enough

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
