### ISSUE TITLE
How to convert the C++ syntax to python

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#6024]
I find it helpful to read the source code to find it useful functions for my application. The problem is I am not sure how to write the corresponding file function in python. Is there a general template that I can use to convert from c++ to python. For example I am trying to convert a model from caffe and I see there is a function convert_model.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
