### ISSUE TITLE
[Doc] Check Dead links

### ISSUE THREAD

**Issue by antinucleon** [apache/incubator-mxnet#6027]
There are still many dead links in doc, eg, 
In http://mxnet.io/tutorials/python/module.html, there is a dead link

https://github.com/dmlc/mxnet/tree/master/doc/tutorials/python/data.ipynb

I suggest add a dead link checker in CI.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
