### ISSUE TITLE
[Discussion] Revise Module API (get_outputs, get_input_grads, ...)

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#6034]
Currently Module.get_outputs(), Module.get_input_grads(), etc. return a list and the user is responsible to use the correct index to get the correct output, input gradient, etc.

This is error prone and requires a tight coupling between different parts of the code (i.e. a user can't change the order of inputs without changing all the parts of the code where he is calling the get_input_grads() method).

One workaround is to use dict(zip()) with the output_names / data_names:
`m_outputs = dict(zip(m.output_names, m.get_outputs()))`

This is less error prone and induces less coupling (i.e. even if the order changes, the user can still access the outputs by their name). It might be advisable to change the API to directly return such a dict like object.

However, this naive workaround would break current code. So instead one could base the return type on an adaptation of collections.OrderedDict, making values accessible both by their name and their index, bringing together the advantage of access by name and staying compatible with current code.

What do you think?

**Comment by piiswrong** [comment]
we can add get_output_dict

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
