### ISSUE TITLE
Are there any examples or instruction of using data augmentation in ImageRecordIter_v1?

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#6043]
New ImageRecordIter_v1 provides rich data augmentation options.  But i don't know how to use them. 
Are there any examples or instruction of using data augmentation in ImageRecordIter_v1?

**Comment by ysh329** [comment]
same issue

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
