### ISSUE TITLE
How can I crop a feature map through given coordinates like croping an image？

### ISSUE THREAD

**Issue by xinghedyc** [apache/incubator-mxnet#6044]
Hi, everyone. I'm trying to crop a feature map from given coordinates, like ROIAlign operation in resent paper Mask RCNN. Is there any way to do such thing?

**Comment by piiswrong** [comment]
ROIPooling?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
