### ISSUE TITLE
skip_exec_node doesn't work for forward_backward nodes in computational graph

### ISSUE THREAD

**Issue by hwang595** [apache/incubator-mxnet#6047]
Hello,
I’m doing a synchronous distributed machine learning project, where I am trying to terminate some of the slower instances(workers) per distributed iteration. This means that out of the n workers, I want to only wait for k workers (say 90%) to complete their gradient computations. At the same time, I would like to terminate the n-k workers that haven’t reported their gradients back to the master. When the next iteration starts, all n workers (including the n-k terminated ones)  will  again compute gradients, as if it is a “normal” distributed iteration.

I’m trying to force the slow workers to go directly into the next iteration by using “skip_exec_node “(https://github.com/dmlc/mxnet/blob/master/src/executor/graph_executor.h#L76). (e.g. skip the back prop nodes in the computational graph).

## Environment info
Operating System:
ubuntu 14.04
Compiler:
gcc 4.8.4
Package used:
Python
MXNet version:
Build from source
MXNet commit hash (`git rev-parse HEAD`):
974d7dad55c6a07ccae8333af1c6f064920fe9c9
Python Version:
python 2.7.6

## Error Message:
 Without skipping any nodes, the time cost is like:
 'Time cost for forward_backward: 0.0002989768981933594' 
'Time cost for update_metric: 0.25156497955322266'

Then, in my very simple example(in which I just skip all the nodes in computational graph), the time costs after the skip are:
'Time cost for forward_backward: 0.0003230571746826172'
 'Time cost for update_metric: 0.11911201477050781'

 My question is, why "skip_exec_node" will skip some execution for "update metric" operation rather than "forward_backward" execution? How can I skip the "forward and backward prop" operation in MXNet?

## Minimum reproducible example
I only added a few lines of code in https://github.com/dmlc/mxnet/blob/master/src/executor/graph_executor.cc#L780, everything else is the same as the original version.
```
bool SHORT_CIRCUIT_TEST = true;
void GraphExecutor::RunOps(bool is_train, size_t topo_start, size_t topo_end) {
  // Update context
  const auto& idx = graph_.indexed_graph();
 //Start to skip the nodes
  if (SHORT_CIRCUIT_TEST==true){
  for (size_t nid = topo_start; nid < topo_end; ++nid) {
      op_nodes_[nid].skip_exec_node = true;
    }
  }
  for (size_t nid = topo_start; nid < topo_end; ++nid) {
    OpNode& opnode = op_nodes_[nid];
    if (opnode.skip_exec_node) continue;
    const auto& inode = idx[nid];
    if (inode.source->is_variable()) continue;
    opnode.exec->op_ctx.is_train = is_train;
  }
... ...
```
## Steps to reproduce
The example I use is the image-classification examples https://github.com/dmlc/mxnet/tree/master/example/image-classification.
1. cd ~/mxnet/example/image-classification
2. python train_mnist.py --network lenet --batch-size 128

**Comment by piiswrong** [comment]
computation is async. This is just pushing it to the engine.
you need a different stragegy

**Comment by mli** [comment]
one simple solution is that letting all workers compute the gradients, but on the server side only merge a part of workers, namely dropping the gradients arrived at the end, by changing

https://github.com/dmlc/mxnet/blob/master/src/kvstore/kvstore_dist_server.h#L179

also, you can let a worker sleep a random time to simulate the stragglers before each data push

**Comment by agnusmaximus** [comment]
Thanks for the response! Does this method save computational resources during the gradient computation? It seems like even with this change, every machine will still be doing the same amount of gradient computation; in other words, gradient computation is not skipped via the skip_exec_node flag. Is this true or am I missing something?

**Comment by mli** [comment]
You can create two modules, A for layer 1-3, B for layer 4-10. then a node can randomly to skip to call A.backward to reduce the cost. But you cannot skip B.backward because it is required for A.backward. 

http://mxnet.io/tutorials/python/module.html

But it's hard to skip a random layer until @piiswrong 's imperative training is done.

**Comment by agnusmaximus** [comment]
Awesome thanks! We'll try this out.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
