### ISSUE TITLE
converting caffe model 

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6052]
I converted a caffe model to mxnet model on one machine and load the model to a mxnet docker container, when trying to load the model from the docker container, I see the following message, 

"loading symbol saved by MXNet version 905 with lower version of MXNet v904. May cause undefined behavior. Please update MXNet if you encounter any issue"

I think the docker image is with mxnet version 0.9.3. How to find the above maxnet version numbers, like v904, v905?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
