### ISSUE TITLE
MXNet threads and processes ?

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#6053]
Hi all,

my question is not an issue but a request for help. I am interesting to reading MXNet core in depth. However, I kind of missing many points and it's currently difficult for me. My goal is to know everything related to create/kill threads and processes. Can anybody here point me out for documentation and part of source code should I read ?

Sincerely
Salem

**Comment by salemmohammed** [comment]
@mli

**Comment by yuruofeifei** [comment]
Hi @salemmohammed 

I'm also starting to read mxnet now, so my understanding will have lots of mistakes but we can learn together.

I think http://mxnet.io/architecture/note_engine.html is a very good documentation.

From what I'm understanding is after executor optimized the graph, we will push ops to engine in topo order.
There are 3 engines: 
1.naive 
2.threaded pool 
3.threaded per device

threaded pool engine is create a common thread pool for all devices and all workers are consuming tasks from the blocking queue.

threaded per device engine is creating thread pool per device. 
I'm not sure the purpose of creating this engine, my guess is the execution time is not similar across different devices, so it's better to dispatch similar job in the same queue to increase throughput.
Hope someone better understand can explain...

Thanks

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
