### ISSUE TITLE
"input type to dropout is not specified" Error

### ISSUE THREAD

**Issue by KayneWest** [apache/incubator-mxnet#6054]
When building a model in 0.9.4 and using symbol.Variable to create a learnable weight, one will get an Error if that same learnable weight is used in mx.symbol.Dropout.

    def model():
    
        ...
        ...
        learnable_weight = mx.sym.Variable('learnable_weight', init=mx.init.Xavier(factor_type="in", magnitude=2.34))
        dp_lw = mx.sym.Dropout(data=learnable_weight,p=0.2)
        ....
        return out`
    out = model()
    mod = mx.mod.Module(out)
    mod.fit(train_data = data_train,
              eval_metric = metric,
              num_epoch = 20,
              optimizer_params={'learning_rate':0.3, 'momentum': 0.9},
              initializer=mx.init.Orthogonal(0.25),
              batch_end_callback = mx.callback.Speedometer(batch_size, 50))

    MXNetError: Error in operator dp_lw: [10:37:06] src/operator/./dropout-inl.h:183: input type to dropout is not specified.

THE FIX (add dtype='float32' as param to your sym.Variable() call):

    def model():
    
        ...
        ...
        learnable_weight = mx.sym.Variable('learnable_weight', init=mx.init.Xavier(factor_type="in", magnitude=2.34), dtype='float32')
        dp_lw = mx.sym.Dropout(data=learnable_weight,p=0.2)
        ....
        return out`
    out = model()
    mod = mx.mod.Module(out)
    mod.fit(train_data = data_train,
              eval_metric = metric,
              num_epoch = 20,
              optimizer_params={'learning_rate':0.3, 'momentum': 0.9},
              initializer=mx.init.Orthogonal(0.25),
              batch_end_callback = mx.callback.Speedometer(batch_size, 50))

**Comment by mli** [comment]
@piiswrong how about we set the default dtype for variable as float32?

**Comment by piiswrong** [comment]
It should default to float32. Not sure why its not working here

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
