### ISSUE TITLE
[Question] Where does the code for Server and Scheduler diverge from that of Worker?

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#6063]
This is not a bug. I have a question.

I've been using https://github.com/tornadomeet/ResNet/blob/master/train_resnet.py this script to launch mxnet, but when it seems every role calls into the `FeedForward.Fit` method in Model.py which calls `_train_multi_device` and presumably starts training. But server role and scheduler should not be doing actual training besides launching their ps-lite instances.

Where does the the code for server and scheduler role diverge from that of worker's?

Many thanks! :)

**Comment by piiswrong** [comment]
on import mxnet, if it's a server instance import kvstore_server will block

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
