### ISSUE TITLE
[Question] What would be the suggested way to initialize keys on server?

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#6064]
This is not a bug. I have a question.

I'm porting ZMQVan to InfiniBand, which requires explicit buffer to be setup before data can be transmitted. This means I need to know beforehand the number of keys and the size of each key.

Currently the key on server is initialized by worker 0 calling into `KVStore::Init`, after `PostOffice.Start` is called where connections are set up. I'm wondering what would be the suggested way to tell the server what is the number of keys and the size of each key without communicating with any worker.

Please advice. Many thanks! :)

**Comment by piiswrong** [comment]
maybe you can setup a default small buffer for bootstraping

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
