### ISSUE TITLE
Set OpenMP Threads at Runtime

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#6069]
We would like to be able to set the number of OpenMP threads used by MXNet at runtime via `omp_set_num_threads`. One approach is to expose an api function `MXNET_DLL int  MXSetNumOMPThreads(int thread_num)` in `c_api.h`, which calls into `omp_set_num_threads`. Something like this is also done by libraries like WarpCTC.

@piiswrong: what do you think of this?

Also: @taliesinb, @matteosal

**Comment by piiswrong** [comment]
I would automatically set it to num physical cpu.

**Comment by sbodenstein** [comment]
Are you suggesting that we have an API function like `MXSetNumOMPThreads`, but also default `omp_set_num_threads` to the number of physical cores when MXNet starts?

One thing we have noticed: for things like unrolled RNN's, the CPU usage increases hugely when going from 1 OMP thread to 4, but the speed doesn't increase much (sometimes it decreases). So we would like control at runtime of the thread number.

**Comment by piiswrong** [comment]
This sounds like a bug we should fix...

but yeah a MXSetNumOMPThreads API is fine.

**Comment by sbodenstein** [comment]
Ok, great. Will make a PR.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
