### ISSUE TITLE
Profiler outputs are titled with symbol type instead of name

### ISSUE THREAD

**Issue by padentomasello** [apache/incubator-mxnet#6072]
I am trying to use the profiler on a net with many layer, but it is hard to distinguish between them because they are all titled 'FullyConnected'. Is there a way for the profiler to use the symbol name? (fc1 vs FullyConnected?). The screen shot at http://mxnet.io/how_to/perf.html looks like it is using the symbol name. 

## Environment info
Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS

Compiler:
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Package used (Python/R/Scala/Julia):Python 3.6

MXNet Version: 3d4d845

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. I am able to reproduce using https://github.com/dmlc/mxnet/blob/master/example/profiler/profiler_executor.py

## What have you tried to solve it?

1. Using both `symbolic` and `all` modes for profiling

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by huangh12** [comment]
Before profiling, set the env as follows.
export MXNET_EXEC_BULK_EXEC_TRAIN=0
export MXNET_EXEC_BULK_EXEC_INFERENCE=false
