### ISSUE TITLE
Check failed: type_ != nullptr The any container is empty requested=struct nnvm::VariableParam

### ISSUE THREAD

**Issue by tengfly** [apache/incubator-mxnet#6077]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Windows Server 2012

Compiler:
Visual Studio 2013

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.5

Or if installed from source:
Build from source

MXNet commit hash (`git rev-parse HEAD`):
1dec793e1dc2eaa5d82780ededb2986bf1f45d6a

If you are using python package, please provide

Python version and distribution:
Python 2.7.11 (Miniconda2-x64)

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
[15:39:31] D:\code\mxnet.git\dmlc-core\include\dmlc/logging.h:300: [15:39:31] D:\code\mxnet.git\dmlc-core\include\dmlc/any.h:261: Check failed: type_ != nullptr The any container is empty requested=struct nnvm::VariableParam
Traceback (most recent call last):
  File "D:/code/mxnet.git/example/image-classification/fine-tune.py", line 53, in <module>
    sym, arg_params, args.num_classes, args.layer_before_fullc)
  File "D:/code/mxnet.git/example/image-classification/fine-tune.py", line 18, in get_fine_tune_model
    net = mx.symbol.FullyConnected(data=net, num_hidden=num_classes, name='fc')
  File "C:\Miniconda2-x64\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\_ctypes\symbol.py", line 191, in creator
    s._compose(*args, name=name, **symbol_kwargs)
  File "C:\Miniconda2-x64\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\symbol.py", line 311, in _compose
    self.handle, name, num_args, keys, args))
  File "C:\Miniconda2-x64\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:39:31] D:\code\mxnet.git\dmlc-core\include\dmlc/any.h:261: Check failed: type_ != nullptr The any container is empty requested=struct nnvm::VariableParam

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
example/image-classification/fine-tune.py

Pyhon fine-tune.py --pretrained-model "\mxnet.git\model\inception-bn-xb" --load-epoch 25 --num-classes 63 --layer-before-fullc "global_pool" --data-train "/Images/20170416-shuffle.rec" --data-val "0170413-pnEqual-shuffle.rec" --num-examples 67000 --lr-step-epochs 50,100,150 --gpus 0,1 --model-prefix "\model\inception-bn-new" --num-epoch 300 --top-k 5

## What have you tried to solve it?
I tried to build two versions: 0.9.5 and 0.9.3, the same issue happened.

**Comment by tengfly** [comment]
This issue is related to #6177 where I located the issue.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
