### ISSUE TITLE
Problems when implementing Stale Synchronous Parallel(SSP) in MXNet

### ISSUE THREAD

**Issue by SmartAir** [apache/incubator-mxnet#6078]
Hello, I am now implementing Stale Synchronous Parallel(SSP) in MXNet. However, I have met a problem for a long time.  

I mainly code in _**kvstore_dist_server.h**_ to implement SSP. To briefly describe my code, when the difference of the number of training iterations finished between  the fastest worker and the slowest worker reaches the maximum number I set, the fastest worker will be blocked to wait for the slowest worker, and the push data of the fastest worker will be stored in a waitlist in the server node temporarily to be updated later. However, when I complete my codes and train Cifar-10 with 1 server node and 2 worker nodes (only use GPU), I always meet a sudden stop and find errors listed as below (also the full version error message is pasted at the end of this post)

> /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val)

> ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (10L,) and requested shape (96L,)

I printed the `vals->size()` and `total_val` in a log file, found that the value of the two variants kept equal to each other for a long time from the beginning of the training, but suddenly they had different values and the training stopped. The last few lines of the log file that recorded the two values are listed as below:

> vals->size()=15360, total_val=15360
> vals->size()=96, total_val=96
> vals->size()=48, total_val=48
> vals->size()=48, total_val=48
> vals->size()=48, total_val=48
> vals->size()=69120, total_val=69120
> vals->size()=112, total_val=112
> vals->size()=112, total_val=112
> vals->size()=17920, total_val=17920
> vals->size()=112, total_val=112
> vals->size()=80, total_val=80
> vals->size()=80, total_val=80
> vals->size()=57600, total_val=57600
> vals->size()=80, total_val=80
> vals->size()=48, total_val=48
> vals->size()=27648, total_val=27648
> vals->size()=48, total_val=48
> vals->size()=48, total_val=48
> vals->size()=32, total_val=32
> vals->size()=2048, total_val=2048
> vals->size()=32, total_val=32
> vals->size()=32, total_val=32
> vals->size()=27648, total_val=27648
> vals->size()=32, total_val=32
> vals->size()=32, total_val=32
> vals->size()=32, total_val=32
> vals->size()=32, total_val=32
> vals->size()=3072, total_val=3072
> vals->size()=32, total_val=32
> vals->size()=32, total_val=32
> vals->size()=2592, total_val=2592
> vals->size()=96, total_val=96
> vals->size()=96, total_val=96
> vals->size()=96, total_val=10

So, could someone please help me review my code and the error message, and tell me what caused the errors? Thanks a lot~ 

## Environment info
Operating System: Ubuntu 14.04.1 LTS

Compiler: gcc version 4.8.2

Package used (Python/R/Scala/Julia): Python

Python version and distribution: Python 2. 7. 6

## Error Message:

> [15:20:10] /home/xiongzi/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:20:10] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [15:20:10] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 
> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 314, in 'calling callback function'
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/kvstore.py", line 45, in updater_handle
>     updater(key, lhs, rhs)
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/optimizer.py", line 820, in updater
>     optimizer.update(index, weight, grad, states[index])
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/optimizer.py", line 305, in update
>     mom[:] += -lr * (grad + wd * weight)
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 101, in \_\_add\_\_
>     return add(self, other)
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 658, in add
>     None)
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 629, in _ufunc_helper
>     rhs = rhs.broadcast_to(lhs.shape)
>   File "/home/xiongzi/mxnet/example/image-classification/../../python/mxnet/ndarray.py", line 354, in broadcast_to
>     raise ValueError(err_str)
> ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (10L,) and requested shape (96L,)
> [15:20:13] /home/xiongzi/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:20:13] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [15:20:13] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 
> bash: line 1:  5319 Aborted                 (core dumped) python train_cifar10.py --data-dir /home/xiongzi/mxnet_data/cifar10/ --batch-size 128 --lr 0.1 --lr-factor .94 --num-examples 5000 --num-epoch 1 --gpus 0,1 --cluster1-begin 0 --cluster1-end 0.2 --cluster2-begin 0.2 --cluster2-end 0.4 --cluster3-begin 0.4 --cluster3-end 0.6 --cluster4-begin 0.6 --cluster4-end 0.8 --cluster5-begin 0.8 --cluster5-end 1 --kv-store dist_ssp
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/xiongzi/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
>     subprocess.check_call(prog, shell = True)
>   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 192.168.0.3 -p 22 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:; export DMLC_INTERFACE=eth1; export DMLC_PS_ROOT_URI=192.168.0.2; export DMLC_ROLE=worker; export DMLC_NUM_SERVER=1; export DMLC_NUM_WORKER=2; export DMLC_PS_ROOT_PORT=9102; cd /home/xiongzi/mxnet/example/image-classification/; python train_cifar10.py --data-dir /home/xiongzi/mxnet_data/cifar10/ --batch-size 128 --lr 0.1 --lr-factor .94 --num-examples 5000 --num-epoch 1 --gpus 0,1 --cluster1-begin 0 --cluster1-end 0.2 --cluster2-begin 0.2 --cluster2-end 0.4 --cluster3-begin 0.4 --cluster3-end 0.6 --cluster4-begin 0.6 --cluster4-end 0.8 --cluster5-begin 0.8 --cluster5-end 1 --kv-store dist_ssp'' returned non-zero exit status 134
> 
> bash: line 1: 27037 Aborted                 (core dumped) python train_cifar10.py --data-dir /home/xiongzi/mxnet_data/cifar10/ --batch-size 128 --lr 0.1 --lr-factor .94 --num-examples 5000 --num-epoch 1 --gpus 0,1 --cluster1-begin 0 --cluster1-end 0.2 --cluster2-begin 0.2 --cluster2-end 0.4 --cluster3-begin 0.4 --cluster3-end 0.6 --cluster4-begin 0.6 --cluster4-end 0.8 --cluster5-begin 0.8 --cluster5-end 1 --kv-store dist_ssp
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/xiongzi/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
>     subprocess.check_call(prog, shell = True)
>   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 192.168.0.2 -p 22 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:; export DMLC_INTERFACE=eth1; export DMLC_PS_ROOT_URI=192.168.0.2; export DMLC_ROLE=worker; export DMLC_NUM_SERVER=1; export DMLC_NUM_WORKER=2; export DMLC_PS_ROOT_PORT=9102; cd /home/xiongzi/mxnet/example/image-classification/; python train_cifar10.py --data-dir /home/xiongzi/mxnet_data/cifar10/ --batch-size 128 --lr 0.1 --lr-factor .94 --num-examples 5000 --num-epoch 1 --gpus 0,1 --cluster1-begin 0 --cluster1-end 0.2 --cluster2-begin 0.2 --cluster2-end 0.4 --cluster3-begin 0.4 --cluster3-end 0.6 --cluster4-begin 0.6 --cluster4-end 0.8 --cluster5-begin 0.8 --cluster5-end 1 --kv-store dist_ssp'' returned non-zero exit status 134

**Comment by SmartAir** [comment]
Here is my code in _**kvstore_dist_server.h**_:
 main part of  SSP  is marked with `/*SSP push begin*/` and `/*SSP push end*/`

```
/*!
 * Copyright (c) 2015 by Contributors
 * \file mxnet_node.h
 * \brief implement mxnet nodes
 */
#ifndef MXNET_KVSTORE_KVSTORE_DIST_SERVER_H_
#define MXNET_KVSTORE_KVSTORE_DIST_SERVER_H_
#include <queue>
#include <string>
#include <mutex>
#include <condition_variable>
#include <memory>
#include <functional>
#include <future>
#include <vector>
#include "ps/ps.h"
#include "mxnet/kvstore.h"

namespace mxnet {
namespace kvstore {

static const int kStopServer = -1;
static const int kSyncMode = -2;
static const int kSyncByGroupMode = -3;
static const int kSyncBySSPMode = -4; 
const int MaxStale = 1; // xiong

/**
 * \brief executor runs a function using the thread called \ref Start
 */
class Executor {
 public:
  /**
   * \brief start the executor
   */
  void Start() {
    std::unique_lock<std::mutex> lk(mu_);
    while (true) {
      cond_.wait(lk, [this]{return !queue_.empty();});
      Block blk = std::move(queue_.front());
      queue_.pop();
      lk.unlock();

      if (blk.f) {
        blk.f(); blk.p->set_value();
      } else {
        blk.p->set_value(); break;
      }
      lk.lock();
    }
  }

  /**
   * \brief function
   */
  typedef std::function<void()> Func;

  /**
   * \brief let the thread called \ref Start to exec a function. threadsafe
   */
  void Exec(const Func& func) {
    Block blk(func);
    auto fut = blk.p->get_future();
    {
      std::lock_guard<std::mutex> lk(mu_);
      queue_.push(std::move(blk));
      cond_.notify_one();
    }
    fut.wait();
  }

  /**
   * \brief stop the thread, threadsafe
   */
  void Stop() {
    Exec(Func());
  }

 private:
  struct Block {
  explicit Block(const Func& func) : f(func), p(std::make_shared<std::promise<void>>()) { }
    Func f;
    std::shared_ptr<std::promise<void>> p;
  };
  std::queue<Block> queue_;
  std::mutex mu_;
  std::condition_variable cond_;
};

class KVStoreDistServer {
 public:
  KVStoreDistServer() {
    using namespace std::placeholders;
    ps_server_ = new ps::KVServer<float>(0);
    static_cast<ps::SimpleApp*>(ps_server_)->set_request_handle(
        std::bind(&KVStoreDistServer::CommandHandle, this, _1, _2));
    ps_server_->set_request_handle(
        std::bind(&KVStoreDistServer::DataHandle, this, _1, _2, _3));
    sync_mode_ = 0; 
  }

  ~KVStoreDistServer() {
    delete ps_server_;
  }

  void set_controller(const KVStore::Controller& controller) {
    CHECK(controller);
    controller_ = controller;
  }

  void set_updater(const KVStore::Updater& updater)  {
    CHECK(updater);
    updater_ = updater;
  }

  /**
   * \brief blocked until received the command \a kSyncMode
   */
  void Run() {
    exec_.Start();
  }

 private:
  void CommandHandle(const ps::SimpleData& recved, ps::SimpleApp* app) {
    if (recved.head == kStopServer) {
      exec_.Stop();
    } else if (recved.head == kSyncMode) {
		sync_mode_ = kSyncMode;
		std::cout << "--sync--" << std::endl;
	} else if (recved.head == kSyncByGroupMode) {
            sync_mode_ = kSyncMode;
            std::cout << "not used" << std::endl;

  } else if (recved.head == kSyncBySSPMode) {
    if (MaxStale == 0) // BSP
    {
        sync_mode_ = kSyncMode;
        std::cout << "--sync--" << std::endl;
    }
    else // SSP
    {
        sync_mode_ = kSyncBySSPMode;
        std::cout << "--sync_mode: SSP--" << std::endl;
    }
	} else {
      // let the main thread to execute ctrl, which is necessary for python
      exec_.Exec([this, recved]() {
          CHECK(controller_);
          controller_(recved.head, recved.body);
        });
    }
    app->Response(recved);
  }

  void DataHandle(const ps::KVMeta& req_meta,
                  const ps::KVPairs<real_t>& req_data,
                  ps::KVServer<real_t>* server) {
    // do some check
    CHECK_EQ(req_data.keys.size(), (size_t)1);
    if (req_meta.push) {
      CHECK_EQ(req_data.lens.size(), (size_t)1);
      CHECK_EQ(req_data.vals.size(), (size_t)req_data.lens[0]);
    }

    int key = DecodeKey(req_data.keys[0]);
    auto& stored = store_[key];

    static int min_iter = 10000; // record the minimum number of iterations among the workers
    static int min_key = 10000; // record the minimum number of keys that has been updated among the wokers
    int NumKeys = 78; // the total number of keys in a model

    // there used several WaitToRead, this is because \a recved's memory
    // could be deallocated when this function returns. so we need to make sure
    // the operators with \a NDArray are actually finished
    if (req_meta.push) {
      size_t ds[] = {(size_t)req_data.lens[0]};
      TShape dshape(ds, ds + 1);
      TBlob recv_blob((real_t*)req_data.vals.data(), // NOLINT(*)
                      dshape, cpu::kDevMask);
      NDArray recved = NDArray(recv_blob, 0);
      if (stored.is_none()) {
        // initialization
        stored = NDArray(dshape, Context());
        CopyFromTo(recved, &stored, 0);
        server->Response(req_meta);
        stored.WaitToRead();

      } else if (sync_mode_ == kSyncMode) { 
        // synced push
        auto& merged = merge_buf_[key];
        if (merged.array.is_none()) {
          merged.array = NDArray(dshape, Context());
        }

        if (merged.request.size() == 0) {
          CopyFromTo(recved, &merged.array, 0);
        } else {
          merged.array += recved;
        }

        merged.request.push_back(req_meta);

        if (merged.request.size() == (size_t)ps::NumWorkers()) {
          // let the main thread to execute updater_, which is necessary for
          // python
          if (updater_) { // ???? useful for gsp?
            exec_.Exec([this, key, &merged, &stored](){
                CHECK(updater_);
                updater_(key, merged.array, &stored);
              });
          } else {
            // if no updater, just copy
            CopyFromTo(merged.array, &stored);
          }
          for (const auto& req : merged.request) {
            server->Response(req);
          }
          merged.request.clear();
          stored.WaitToRead();
        } else {
          merged.array.WaitToRead();
        }
      }
        /*SSP push begin*/
        else if (sync_mode_ == kSyncBySSPMode){
 
               int WorkerID = req_meta.sender; // Node ID of current worker

               // waitlist of current worker, which stores the keys and
               // values of previous push request due to too large stales
               auto& sender_buf = ssp_buf_[WorkerID];  
                
               std::unordered_map<int, int>::iterator it;
               int min;

               // first push request of current worker
               std::unordered_map<int, int>::iterator iter = iter_record.find(WorkerID);
               if (iter == iter_record.end())
               { 
                  key_record[WorkerID] = 0;
               }
               
               // determine the slowest worker and its key update times and iteration update times
               if (key_record[WorkerID] < min_key)
               {
                  min_key = key_record[WorkerID]; // key update times of the slowest worker 
                  min_iter = min_key / NumKeys; // iteration update times of the slowest worker
               }             
           
               // deal with current push request
               if (iter_record[WorkerID] - min_iter < MaxStale) // MaxStale not reached, update immediately
               {
                  exec_.Exec([this, key, &recved, &stored](){
                  CHECK(updater_);
                  updater_(key, recved, &stored);
                  });

                  server->Response(req_meta); // response to the worker
                  stored.WaitToRead();

                  key_record[WorkerID] += 1; // the number of key update times increase
                  iter_record[WorkerID] = key_record[WorkerID] / NumKeys; // the number of iteration update times
            
                  // find the slowest worker
                  min = (key_record.begin())->second;
                  
                  for (it = ++(key_record.begin()); it != key_record.end(); ++it)
                  {                     
                      if (it->second < min)
                      {
                          min = it->second;
                      }
                  }
                  min_key = min;
                  min_iter = min_key / NumKeys;               
                }
                else // MaxStale reached, put the current push request and data into the waillist for later update
                {
                    (sender_buf.request).push_back(req_meta);
                    (sender_buf.array).push_back(recved);
                    (sender_buf.keys).push_back(key);
                }

               // deal with previous push request in the waitlist
               for (it = iter_record.begin(); it != iter_record.end(); ++it)
               {
                    auto& to_update = ssp_buf_[it->first];

                    if (it->second - min_iter >= MaxStale) // MaxStale reached, no need to deal with the waitlist
                    {
                        continue;
                    }
                    else if ((to_update.request).size() == 0) // empty waitlist
                    {
                        continue;
                    }
                    else // deal with the data in the waitlist
                    {
                       unsigned int i = 0;
                       for (; i < to_update.request.size(); ++i)
                       {
                            auto& update_key = (to_update.keys)[i]; // key waited to be updated
                            auto& update_value = (to_update.array)[i]; // value waited to be updated
                            auto& update_req = (to_update.request)[i]; // request waited to be responsed to the sender

                            stored = store_[update_key];
                            // CopyFromTo(update_value, &stored);
                            exec_.Exec([this, update_key, &update_value, &stored](){
                            CHECK(updater_);
                            updater_(update_key, update_value, &stored);
                            });
                            server->Response(update_req);
                            stored.WaitToRead();

                            key_record[it->first] += 1;                   
                       }
                       to_update.request.clear();
                       to_update.array.clear();
                       to_update.keys.clear();
                       

                       iter_record[it->first] = key_record[it->first] / NumKeys;
                       if (min_key > key_record[it->first])
                       {
                          min_key = key_record[it->first];
                          min_iter = iter_record[it->first];
                       }
                    }
               }

      } /*SSP push end*/
        else {
        // async push
        exec_.Exec([this, key, &recved, &stored](){
            CHECK(updater_);
            updater_(key, recved, &stored);
          });
        server->Response(req_meta);
        stored.WaitToRead();
      }
    } else {

			ps::KVPairs<real_t> response;
			CHECK(!stored.is_none()) << "init " << key << " first";
			int len = stored.shape()[0];
			response.keys = req_data.keys;
			response.lens = {len};
			// TODO(mli) try to remove this CopyFrom
			response.vals.CopyFrom(static_cast<const float*>(stored.data().dptr_), len);
			server->Response(req_meta, response);
    }
  }

  int DecodeKey(ps::Key key) {
    auto kr = ps::Postoffice::Get()->GetServerKeyRanges()[ps::MyRank()];
    return key - kr.begin();
  }

  /**
   * \brief user defined
   */
  int sync_mode_;
  KVStore::Controller controller_;
  KVStore::Updater updater_;

  std::unordered_map<int, NDArray> store_;

  struct MergeBuf {
    std::vector<ps::KVMeta> request;
    NDArray array;
  };
  std::unordered_map<int, MergeBuf> merge_buf_; 

  // xiong
  struct SSPBuf{
    std::vector<ps::KVMeta> request;
    std::vector<NDArray> array;
    std::vector<int> keys;
  };
  std::unordered_map<int, SSPBuf> ssp_buf_; // xiong
  std::unordered_map<int, int> iter_record; // xiong
  std::unordered_map<int, int> key_record; // xiong

  Executor exec_;

  ps::KVServer<float>* ps_server_;
};

}  // namespace kvstore
}  // namespace mxnet

#endif  // MXNET_KVSTORE_KVSTORE_DIST_SERVER_H_
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
