### ISSUE TITLE
faster rcnn train error！

### ISSUE THREAD

**Issue by 123chengbo** [apache/incubator-mxnet#6080]
when i run：bash script/vgg_voc07.sh 0
i found there is something wrong in: pascal_voc.py: size = cv2.imread()，the info is: Segmentation fault, core, without any other information.

i add some print info above this、and under this , then make sure that the problem is here.

but i've tried cv2.imread() in python, it work well。

can anybody help me with it？

thank you

**Comment by wyzero** [comment]
Is there anything new about this problem?

**Comment by 123chengbo** [comment]
no，still can't solve this.

**Comment by eldercrow** [comment]
Are you using anaconda python? I got the same error when I use anaconda's cv2. It worked ok when I installed python cv2 from ubuntu repo. Still don't know why such thing's happening though.

**Comment by KevinWangTHU** [comment]
Having the same issue here with opencv 3.1. Go back to opencv 2.4 then everything is fine. But I am not sure if this is the problem. I will try to figure it out.

**Comment by AlphaZiggy** [comment]
I'm using Ubuntu 14.04 and OpenCV 3.2, run into the same issue with you. I found MxNet is trying to load libopencv_core.so.2.4.8, which is installed follow the official mxnet tutorials. The wrong version of opencv caused the seg fault.
So i remove opencv 2.4.8 from system and recompile mxnet, everything goes well now.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
