### ISSUE TITLE
Runtime Error Handling

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#6083]
In general, when there are data-dependent conditions that can cause a layer to fail, we want to avoid making this failure something that aborts the process.

With a usual error handling (`DMLC_THROW_EXCEPTION`) during asynchronous engine execution, the process is terminated. A language like Mathematica wants to share the process with MXNet, and it cannot have this shared process terminate. We would like to have a principled solution built into MXNet

@piiswrong: Is there a way for MXNet to handle this? (or is there some approach we can implement?)

@taliesinb, @matteosal

**Comment by sbodenstein** [comment]
A ping on this.

**Comment by taliesinb** [comment]
@piiswrong For the record, we have an internal solution to this, but of course we want our fork of MXNet to be as close to upstream as possible, so it would be good to figure something out. Can we describe our solution, or do you have a strong opinion about how to do this?

**Comment by piiswrong** [comment]
Yeah you are welcome to send a pr


Tali Beynon <notifications@github.com>于2017年5月25日 周四下午6:03写道：

**Comment by piiswrong** [comment]
@taliesinb @sbodenstein Any updates?

**Comment by taliesinb** [comment]
Will get to this this week I think...

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
