### ISSUE TITLE
How python API translated to lower level ?

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#6085]
Hi all,

I am here struggling with reading MXNet source code. I am a end user for a few months and I decided to go deep in the code. I read some parts of it but I still struggle. So, I wanna trace the code from end user to the low level. However, I have not seen any clear explanation how to read it. Also, How API python transfer the code to the lower layer ?

Sincerely

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
