### ISSUE TITLE
[Feature Request]: Persistent RNN's

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#6086]
The new persistent RNN functionality in cuDNN v6 should be supported (https://developer.nvidia.com/cudnn).

@piiswrong:  can you add that to "Projects" -> 'feature requests"?

**Comment by piiswrong** [comment]
Isn't it controled by a flag in cudnn RNN api? Should be pretty easy to do.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
