### ISSUE TITLE
Multiple calls to train cause cudaMalloc to fail

### ISSUE THREAD

**Issue by smissan** [apache/incubator-mxnet#6095]
If calling train several times, I ran out of GPU memory:

pooled_storage_manager.h:80: cudaMalloc failed: out of memory

looks like GPU buffers are never cleared and memory runs out. 
It needs to be solved to be able to use MXNet in the larger application, where multiple train attempts are made in sequence, without restarting the app.

**Comment by smissan** [comment]
it looks like the problem can be solved by setting 

ptr = new storage::NaiveStorageManager<storage::GPUDeviceStorage>();

instead of GPUPooledStorageManager in storage.cc

Can this be made as an option to be configured at runtime? It really is a bad practice to allocate all availabe GRAM and never release it. Another option is to add a public method that would allow all allocated memory to be released.

**Comment by zhangfanqie** [comment]
Hi, is this problem solved? I met the same question.

**Comment by smissan** [comment]
no it is not solved, we have ended up modifying storage.cc and making native storage manager a default. The threaded pooled one is garbage, never frees the memory making it impossible to use in any application where we need to be able to use DNN and cuda at the same time.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
