### ISSUE TITLE
How to get fixed size output feature map from a variable size input feature map (kind of like spatial pyramid pooling)

### ISSUE THREAD

**Issue by jdhao** [apache/incubator-mxnet#6097]
## Background
I am doing a project on learning discriminative features for images of various size.  In my case, I do not want to resize the images into fixed width and height in order for them to be feed into the predefined network.

##  Problem
For convolutional layers, it is ok that the input images have different size. But if we go from conv layer to fully-connected layer, we must make sure the output of last conv layer is fixed size.

For example, output feature map for 2 conv layers may be 512*16*18 and 512*24*32. I want to get a fixed size output, say 3*3 or 3*4 by dividing the input feature maps into 3*3 or 3*3 regions of the same size and then doing pooling operations (max pooling or sum pooling). Ideally, after this transformation, the output feature maps of the two images  will become 512*3*3, regardless of the original image size.

## Question
Can anyone shed some light on how to implement this in MXNet, preferably using a composition of existing symbols.

**Comment by abieler** [comment]
I second that question.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by pavanteja295** [comment]
ROI Pooling may be one option ?

**Comment by abieler** [comment]
Yes, ROI-Pooling was exactly what I was looking for back then. Thanks for posting it here, I did find it but forgot to actually mention it here!
