### ISSUE TITLE
why sym.SoftmaxOutput can't support other name

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#6099]
if i define mx.symbol.SoftmaxOutput(data=ip5, name="softmax1111") ,it will report Symbol.InferShapeKeyword argument name softmax_label not found

Can't it support arbitrarily name in SoftmaxOutput?

**Comment by jdhao** [comment]
what is your complete code, you should post a minimum working example

**Comment by liumilan** [comment]
def gen_caffe_net():
    input=mx.symbol.Variable('data')
    ip1=mx.symbol.FullyConnected(data=input, name="ip1", num_hidden=3)
    relu1=mx.symbol.Activation(data=ip1, act_type="relu", name="relu1")
    ip5=mx.symbol.FullyConnected(data=relu1, name="ip5", num_hidden=2)
    net=mx.symbol.SoftmaxOutput(data=ip5, name="softmax1111")
    print net.debug_str()
    return net
here is my code
@jdhao

**Comment by jdhao** [comment]
I think your code is corret. refer to [here](http://mxnet.io/tutorials/python/module.html) for an example.

**Comment by liumilan** [comment]
my question is why SoftmaxOutput name can't be arbitrarily ...If I specified softmax,it will be ok

**Comment by jdhao** [comment]
maybe it is a convention. if it is not critical, just follow the convention.

**Comment by liumilan** [comment]
if it can't support arbitrarily  name ,how can it support group features?
like that
 data = mx.symbol.Variable('data')
    fc1 = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=128)
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
    fc2 = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 64)
    act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
    fc3 = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=10)
    sm1 = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax1')
    sm2 = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax2')

**Comment by jdhao** [comment]
@liumilan , In my system, you can give any name to the SoftmaxOutput.  The following code runs without error:
```
input=mx.symbol.Variable('data')
ip1=mx.symbol.FullyConnected(data=input, name="ip1", num_hidden=3)
relu1=mx.symbol.Activation(data=ip1, act_type="relu", name="relu1")
ip5=mx.symbol.FullyConnected(data=relu1, name="ip5", num_hidden=2)
net=mx.symbol.SoftmaxOutput(data=ip5, name="softmax1111")
```

**Comment by marugari** [comment]
I think `DataIter` doesn't support arbitrarily name.
https://github.com/marugari/Notebooks/blob/master/mxnet_multi-input_multi-output.ipynb

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
