### ISSUE TITLE
"Cannot find custom operator type *" when running distributed training with multiple machines

### ISSUE THREAD

**Issue by Mochimazui** [apache/incubator-mxnet#6102]
[code mxnet-issue-6102](https://github.com/Mochimazui/mxnet-issue-6102)

MXNet version: v0.9.5  (downloaded using `git clone -b v0.9.5 URL`)

Built with:

    Ubuntu 16.04
    CUDA 8.0
    CUDNN 5.1
    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
    Python 2.7.12
    make -j USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_DIST_KVSTORE=1 ADD_LDFLAGS = -L/opt/OpenBLAS -L/opt/OpenBLAS/lib

I'm running a simple network with a customized operator:

    class FrobeniusNorm(mx.operator.CustomOp):
        ...
    @mx.operator.register("frobenius")
    class FrobeniusNormProp(mx.operator.CustomOpProp):
        ...

It works fine on single machine, however crashed when launched with command `python ../../tools/launch.py ...` and kvstore set to 'dist_sync' for multi-machine learning.

    [00:02:57] HOME/src/mxnet/dmlc-core/include/dmlc/./logging.h:304: [00:02:57] src/operator/custom/./custom-inl.h:128: Check failed: registry_.find(param_.op_type) != registry_.end() Cannot find custom operator type frobenius
    
    Stack trace returned 10 entries:
    [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f54b9fa434c]
    [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2op12CustomOpProp4InitERKSt6vectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_ESaISA_EE+0x916) [0x7f54ba7ecc36]
    [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2op12ParsedOpProp4InitERKN4nnvm9NodeAttrsE+0x124) [0x7f54ba88a3a4]
    [bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(+0xe8eef7) [0x7f54ba880ef7]
    [bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet17UpgradeJSON_ParseEN4nnvm5GraphE+0x4fe) [0x7f54ba89c21e]
    [bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f54ba8a1781]
    [bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x1a44) [0x7f54ba8923e4]
    [bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f54ba8a1781]
    [bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f54bb8f69dc]
    [bt] (9) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f54babf5189]
    
    Traceback (most recent call last):
      File "_ctypes/callbacks.c", line 315, in 'calling callback function'
      File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/kvstore_server.py", line 38, in server_controller
        optimizer = pickle.loads(cmd_body)
      File "/usr/lib/python2.7/pickle.py", line 1388, in loads
        return Unpickler(file).load()
      File "/usr/lib/python2.7/pickle.py", line 864, in load
        dispatch[key](self)
      File "/usr/lib/python2.7/pickle.py", line 1223, in load_build
        setstate(state)
      File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/symbol.py", line 247, in __setstate__
        check_call(_LIB.MXSymbolCreateFromJSON(c_str(json_str), ctypes.byref(handle)))
      File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 84, in check_call
        raise MXNetError(py_str(_LIB.MXGetLastError()))
    mxnet.base.MXNetError: [00:02:57] src/operator/custom/./custom-inl.h:128: Check failed: registry_.find(param_.op_type) != registry_.end() Cannot find custom operator type frobenius
    
    Stack trace returned 10 entries:
    [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f54b9fa434c]
    [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2op12CustomOpProp4InitERKSt6vectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_ESaISA_EE+0x916) [0x7f54ba7ecc36]
    [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet2op12ParsedOpProp4InitERKN4nnvm9NodeAttrsE+0x124) [0x7f54ba88a3a4]
    [bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(+0xe8eef7) [0x7f54ba880ef7]
    [bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet17UpgradeJSON_ParseEN4nnvm5GraphE+0x4fe) [0x7f54ba89c21e]
    [bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f54ba8a1781]
    [bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x1a44) [0x7f54ba8923e4]
    [bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f54ba8a1781]
    [bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f54bb8f69dc]
    [bt] (9) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f54babf5189]

**Comment by Mochimazui** [comment]
[code mxnet-issue-6102](https://github.com/Mochimazui/mxnet-issue-6102)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
