### ISSUE TITLE
Negative padding specification in Padding Layer (negative values in TShapes)

### ISSUE THREAD

**Issue by matteosal** [apache/incubator-mxnet#6124]
Negative padding specification in Padding Layer are officially not supported but are not catched and result in undefined behavior (at least when using the python interface). 
Negative values are overflown to large positive values in the padding spec TShape before hitting the operator. 
Magically enough, some other overflow happens during evaluation and the output is actually a cropped tensor, even if this is unintended (for 'constant' and 'edge' methods only).

Also, this is maybe affecting more than just the padding layer.

**Comment by piiswrong** [comment]
yeah we need better ways of handling this

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
