### ISSUE TITLE
Outdated Tutorials

### ISSUE THREAD

**Issue by adrianloy** [apache/incubator-mxnet#6126]
Running Tutorials like [http://mxnet.io/tutorials/python/mnist.html] produce Deprecated Errors like the following:
```

DeprecationWarning: Calling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.
  self.initializer(k, v)
```

Apparently they are outdated.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by jrosebr1** [comment]
I am seeing this issue too. What is the correct way to initialize the model?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudh2290** [comment]
@adrianloy I wasn't able to reproduce the issue with the latest master. Can you please provide the MXNet version that you are using and Minimum Reproducible example.

**Comment by anirudh2290** [comment]
@jrosebr1 By default the model.fit call uses the default initializer. You can also call fit with a different initializer: https://mxnet.incubator.apache.org/api/python/module/module.html?highlight=modu#mxnet.module.BaseModule.fit

**Comment by anirudh2290** [comment]
@szha can you please remove "Need Triage" and add the label "Pending Requester Info" "Module"
