### ISSUE TITLE
ps-lite clarification in distributed systems and ps-lite version in MXNet

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#6127]
Hi all,
In regards to parameter server, I have two questions.
MXNet uses parameter server but I am guessing that ps-lite is that exactly the same parameter server version/generation that is using in dmlc/MXNet. Can anybody shed some light on this ?

In ps-lite, the distributed systems have two costs in addition to single machine. One is the data communication cost, namely sending data over the network; the other one is synchronization cost due to the imperfect load balance and performance variance cross machines. 

Can anybody explain the second cost in the distributed version ?

**Comment by salemmohammed** [comment]
@pluskid

**Comment by pluskid** [comment]
Yes, ps-lite is used as a submodule, as the parameter server for mxnet. @mli should know better for this part.

I'm not sure what exactly your question is. It seems you are answering your own question? There will be cost from synchronization when the load balance is not perfect across machines.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
