### ISSUE TITLE
Does anyone have pretrained inception-resnet-v2 model?

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#6142]
I didn't find it on mxnet model zoo :sob: 

Thanks a lot! :laughing:

**Comment by iFighting** [comment]
the same problem as you

**Comment by ysh329** [comment]
@iFighting Do u play Kaggle?

**Comment by iFighting** [comment]
@ysh329 yep,i play

**Comment by ysh329** [comment]
@iFighting I emailed u.

**Comment by TerryLovesLife** [comment]
@ysh329 @iFighting.  I am also looking for pretrained inception-resnet-v2 model. Where can I download one? Or could you please email me one copy? Thank you.

**Comment by ysh329** [comment]
@TerryLovesLife Excuse, we don not have pre-trained inception-resnet-v2 models, either. :disappointed:

**Comment by universewill** [comment]
I am also looking for inception-v4 and inception-resnet-v2, does anyone have them?
