### ISSUE TITLE
WarpCTC Plugin fails to compile on OSX with CUDA support

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#6146]
## Environment info
Operating System: OSX

Compiler: Clang (Apple LLVM version 8.0.0 (clang-800.0.42.1))

## Error Message:
```
ers/sebastianb/git/warp-ctc/include -I/Users/sebastianb/Software/mxnet2/cub -DMXNET_USE_NVRTC=0 -MM -MT build/plugin/warpctc/warpctc_gpu.o plugin/warpctc/warpctc.cu >build/plugin/warpctc/warpctc_gpu.d
In file included from plugin/warpctc/warpctc.cu:7:
In file included from plugin/warpctc/./warpctc-inl.h:10:
/Users/sebastianb/Software/mxnet2/dmlc-core/include/dmlc/logging.h:11:10: fatal error: 'cstdio' file not found
#include <cstdio>
         ^
1 error generated.
make: *** [build/plugin/warpctc/warpctc_gpu.o] Error 1
```

## Steps to reproduce
Change `config.mk`:

```
WARPCTC_PATH = /Users/sebastianb/git/warp-ctc
MXNET_PLUGINS += plugin/warpctc/warpctc.mk
```
and set `USE_CUDNN = 1`, `USE_CUDA_PATH = /usr/local/cuda`, `USE_CUDA = 1`.

**Comment by sbodenstein** [comment]
@piiswrong: MXNet with GPU builds correctly on OSX now (after #6131). However, the WarpCTC plugin breaks the build. 

I'm using the latest master of WarpCTC (https://github.com/baidu-research/warp-ctc).

**Comment by piiswrong** [comment]
Could you compile on ubuntu and do a fix?

**Comment by piiswrong** [comment]
Also please move ctc_loss to contrib asap

**Comment by sbodenstein** [comment]
I've moved this op to contrib (#6154).

Yes, I'll use a ubuntu machine to do the fix.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
