### ISSUE TITLE
More efficient implementation of strided convolution

### ISSUE THREAD

**Issue by anthony-han** [apache/incubator-mxnet#6155]
I need to use strided convolution to do some classification tasks. But I find that strided convolution is not as efficient as expected. For example, convolution with stride=2 costs more time than convolution with stride=1. I don't know why. Is there an efficient way to implement strided convolution?

**Comment by piiswrong** [comment]
how much more time?
Due to non contiguous reads some performance degradation is expected

**Comment by anthony-han** [comment]
@piiswrong About 30% more.
I read an article. It mentions that using conv2d to perform strided convolution in Theano is not efficient either. It sugguests using FilterActs instead, which is much more efficient. I wonder if we have some efficient way to implement strided convolution.
http://benanne.github.io/2014/04/03/faster-convolutions-in-theano.html

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
