### ISSUE TITLE
weighted cross entropy for imbalanced data

### ISSUE THREAD

**Issue by benwu232** [apache/incubator-mxnet#6157]
Hi,

I'm new on MxNet and I'm dealing some imbalanced multi-class data.
As far as I know, Keras allows users to set class weights or per-sample weight in its fit function. In tensorflow, there is similar functions tf.nn.weighted_cross_entropy_with_logits or tf.losses.softmax_cross_entropy. I did some search. Similar question has been issued. Somebody said it is possible in MxNet but I just can't find any example. Is there any similar function in MxNet? or can anybody kindly tell me how to implement it?

Thanks a lot!

#1535 
#1783

**Comment by gurumurthys** [comment]
Does this work?

https://github.com/dmlc/mxnet/blob/84f1f2e4346ea90b0d9f77405631b688b76ad98f/example/numpy-ops/weighted_logistic_regression.py

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
