### ISSUE TITLE
Check failed: (vals->size()) == (total_val) in KVWorker<Val>::Pull_

### ISSUE THREAD

**Issue by SmartAir** [apache/incubator-mxnet#6158]
Hello, I store some push requests from a worker node  in a list and do not let the server node handle these push requests until a certain requirement is satisfied (i.e. not handle the present pull request immediately, block it until a time the user sets). 
For example, if a worker node is too fast and has run 10 more iterations than the slowest worker node in the cluster, I try to block the handle of the present push request from this fastest worker node in the server node, only handle the push requests in the waitlist and send responses to the fastest worker node if the slowest worker has catched up with it. However, I met an error as below:

> [03:19:47] /home/xiongzi/mxnet/dmlc-core/include/dmlc/logging.h:235: [03:19:47] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [03:19:47] /home/xiongzi/mxnet/ps-lite/include/ps/kv_app.h:579: Check failed: (vals->size()) == (total_val) 

The code is in `mxnet/ps-lite/include/ps/kv_app.h`, I feel puzzled about the code that raises the error in the function **KVWorker<Val>::Pull_:**
`CHECK_EQ(vals->size(), total_val);`

Could someone please explain this sentence of code for me?
 `vals->size()`  refers to the the size of values in the present pull request, and the `total_val` refers to the total size of all values of the pull request's timestamp? (Plz point out my mistake if I says something wrong)
So what is the purpose of checking whether `vals->size()` and `total_val ` are equal to each other? And what may cause the error I mention above?
Thanks a lot!

**Comment by SmartAir** [comment]
In addtion, I am implementing Stale Synchronous Parallel(SSP) in MXNet now, if you are also interested in this or have done some similar work, welcome to contact and discuss with me, always here!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
