### ISSUE TITLE
Duplicate classes in the Python API

### ISSUE THREAD

**Issue by JeanKossaifi** [apache/incubator-mxnet#6168]
MXNet currently has duplicates such as `mxnet.io.ImageRecordIter ` and `mxnet.io.ImageRecordIter_v1` which is detrimental to both the users and developers.

An easy way around these problems would be to have better separation between dev and stable branches, along with two versions (at least) of the doc (/stable and /dev with an auto redirect to the stable version by default).

**Comment by piiswrong** [comment]
let's mark them as deprecated and remove in some later release

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
