### ISSUE TITLE
Discussion and troubleshooting on PyPI (pip) installation with Windows (the newest 0.9.5 release)

### ISSUE THREAD

**Issue by yajiedesign** [apache/incubator-mxnet#6174]
The PyPI mxnet installation is now available with windows:

- [mxnet-cu80-win](https://pypi.python.org/pypi/mxnet-cu80-win/0.9.5) on Windows, supports CUDA-8.0 and cuDNN-6.0
- the cpu only is to be later

Install:

1. install  [NVIDIA Display Driver](http://www.nvidia.com/Download/index.aspx) Newest
2. install  [CUDA](https://developer.nvidia.com/cuda-downloads)
3. install  [Anaconda3 ](https://www.continuum.io/downloads) (Highly Recommended)  or standard [Python](https://www.python.org/)
4. pip install mxnet-cu80-win

Is currently in test. welcome feedback

**Comment by bityangke** [comment]
Do I need to install VS 2015？

**Comment by bityangke** [comment]
@yajiedesign  Thank you！ Gob Job! I will have a try.

**Comment by jerrywind** [comment]
Need python2.7 or python3 or python3.5 or python3.6?

**Comment by yajiedesign** [comment]
@jerrywind 2.7 3.5 3.6

**Comment by jerrywind** [comment]
tks, Good job!!!!

**Comment by RogerBorras** [comment]
Many thanks @yajiedesign !

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
