### ISSUE TITLE
Error accnn.py

### ISSUE THREAD

**Issue by Shiro-LK** [apache/incubator-mxnet#6178]
Hello,

I try to use accnn.py so as to accelerate the inception model, but I get an error. The model comes from https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-inception-v3.md

> python /home/rd/Documents/RD2/lib/mxnet/tools/accnn/accnn.py -m Inception-7  --load-epoch 1 --save-model new_inception --ratio 2

> [15:30:12] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
> [15:30:12] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
> /home/rd/Documents/RD2/lib/mxnet/python/mxnet/model.py:870: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
>   **kwargs)
> [15:30:35] /home/rd/Documents/RD2/lib/mxnet/dmlc-core/include/dmlc/./logging.h:300: [15:30:33] src/operator/./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (8) exceeds input (5 padded to 5)
> 
> Stack trace returned 10 entries:
> [bt] (0) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f172cf9965c]
> [bt] (1) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x92f) [0x7f172dabe30f]
> [bt] (2) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0xe19a52) [0x7f172d83ea52]
> [bt] (3) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6a3fc) [0x7f172e68f3fc]
> [bt] (4) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6b99a) [0x7f172e69099a]
> [bt] (5) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6ccad) [0x7f172e691cad]
> [bt] (6) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f172e6b6fac]
> [bt] (7) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f172dbc5b79]
> [bt] (8) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f172dbc9145]
> [bt] (9) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f172dbbf48b]
> 
> infer_shape error. Arguments:
>   data: (1, 3, 224, 224)
> Traceback (most recent call last):
>   File "/home/rd/Documents/RD2/lib/mxnet/tools/accnn/accnn.py", line 25, in <module>
>     config['conv_params'] = rank_selection.get_ranksel(model, args.ratio)
>   File "/home/rd/Documents/RD2/lib/mxnet/tools/accnn/rank_selection.py", line 23, in get_ranksel
>     _, output_shapes, _ = model.symbol.get_internals().infer_shape(data=(1,3,224,224))
>   File "/home/rd/Documents/RD2/lib/mxnet/python/mxnet/symbol.py", line 636, in infer_shape
>     res = self._infer_shape_impl(False, *args, **kwargs)
>   File "/home/rd/Documents/RD2/lib/mxnet/python/mxnet/symbol.py", line 719, in _infer_shape_impl
>     ctypes.byref(complete)))
>   File "/home/rd/Documents/RD2/lib/mxnet/python/mxnet/base.py", line 78, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: Error in operator global_pool: [15:30:33] src/operator/./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (8) exceeds input (5 padded to 5)
> 
> Stack trace returned 10 entries:
> [bt] (0) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f172cf9965c]
> [bt] (1) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x92f) [0x7f172dabe30f]
> [bt] (2) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0xe19a52) [0x7f172d83ea52]
> [bt] (3) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6a3fc) [0x7f172e68f3fc]
> [bt] (4) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6b99a) [0x7f172e69099a]
> [bt] (5) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c6ccad) [0x7f172e691cad]
> [bt] (6) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f172e6b6fac]
> [bt] (7) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f172dbc5b79]
> [bt] (8) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f172dbc9145]
> [bt] (9) /home/rd/Documents/RD2/lib/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f172dbbf48b]

how can I solve this problem ?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
