### ISSUE TITLE
cudnn_deconvolution-inl.h

### ISSUE THREAD

**Issue by picctree** [apache/incubator-mxnet#6186]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 12.04
Compiler:
g++-4.8 nvcc
Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:
from source
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:
src/operator/./cudnn_deconvolution-inl.h(124): error: identifier "out" is undefined
 detected during instantiation of "mxnet::op::CuDNNDeconvolutionOp<DType>::CuDNNDeconvolutionOp(mxnet::op::DeconvolutionParam, int, int, const std::vector<mxnet::TShape, std::allocator<mxnet::TShape>> &, const std::vector<mxnet::TShape, std::allocator<mxnet::TShape>> &, const mxnet::Context &) [with DType=float]" 
src/operator/deconvolution.cu(47): here

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. make 

## What have you tried to solve it?

1. line 136 out.dptr_  change to out_ptr,  line  258 gwmat.dptr_ also 
then can compile, but I don't know whether it is correct.

**Comment by zihaolucky** [comment]
Similar issue:

```

src/operator/./cudnn_deconvolution-inl.h(191): warning: variable "gwmat_ptr" was set but never used
          detected during:
            instantiation of "void mxnet::op::CuDNNDeconvolutionOp<DType>::Backward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=mshadow::half::half_t]"
(68): here
            instantiation of "mxnet::op::CuDNNDeconvolutionOp<DType>::CuDNNDeconvolutionOp(mxnet::op::DeconvolutionParam, int, int, const std::vector<nnvm::TShape, std::allocator<nnvm::TShape>> &, const std::vector<nnvm::TShape, std::allocator<nnvm::TShape>> &, const mxnet::Context &) [with DType=mshadow::half::half_t]"
src/operator/deconvolution.cu(47): here

2 errors detected in the compilation of "/tmp/tmpxft_00004167_00000000-16_deconvolution.compute_52.cpp1.ii".
make: *** [build/src/operator/deconvolution_gpu.o] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by wgting96** [comment]
I met the same problem. Then I updated the CuDNN version from v4.0 to v5.0 and complied successfully.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
