### ISSUE TITLE
Any plan to enable multiprocessing feature of NDArray?

### ISSUE THREAD

**Issue by happywu** [apache/incubator-mxnet#6188]
Hi, 

Is there any plan to implement a method that could share NDArray (or model) using multiprocessing? Many tasks in deep reinforcement learning needs shared model to run in parallel, and due to training and evaluation often happen on-line (like train a batch size of 20, then inference), using parameter sever method (multi machine) is rather slow (small batch size, frequent parameter communication). 

A reference could be http://pytorch.org/docs/multiprocessing.html . 

Many Thanks.

**Comment by piiswrong** [comment]
mxnet engine is already async, so there is no need of multiprocessing.

**Comment by happywu** [comment]
I know that mxnet engine is already async. However, what is needed there is in fact explicit async, which is just like distributed training. Instead of using multiple nodes and parameter server, shared model parameters used in a single node is preferred due to large communication overhead.  

The way you mentioned could work, just like your version of a3c, however, is it not exactly the same as the paper's mechanism. In that way, fair comparsion and solid replica would be impossible. 

In fact, I also have my version of a3c using distributed training. Unfortunately I could only use dist_sync to make it work fast enough. If dist_async used in my case, training speed is extremely slow and would take roughly 4 or larger x time than dist_sync. And althought dist_sync could achieve comparable result with the paper, dist_async is really the same way as the paper. 

Thus a way to share model paremeter in multiprocessing or a way to speed up dist async training in this specical case is both acceptable.  

Many Thanks.

**Comment by piiswrong** [comment]
that's not what I meant

You can have N workers that are only running the simulator and a single master that runs training.

**Comment by piiswrong** [comment]
@mli 
Is there room for improving dist_async? Use memory mapping when running multiple processes on a single node?

**Comment by happywu** [comment]
How can I collect the data from different simulators using multiprocessing? Use Queue?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
