### ISSUE TITLE
how can i print any weight arrays using monitor

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#6190]
there is one example code using monitor
return mx.nd.norm(d)/np.sqrt(d.size)
but it print the L2 of weight.
if i'd like to the weight array
how can i change the code?
i tried  return d.asnumpy()
it report  assert isinstance(v_list, list)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
