### ISSUE TITLE
New padding value in max Pooling

### ISSUE THREAD

**Issue by matteosal** [apache/incubator-mxnet#6191]
The padding behaviour of max Pooling layer has changed at some point, padding with a value of -3.4e+38 (probably the most negative float) instead of zero.

While the reason for this is understandable (i.e. never pick the padding value as output), it leads to very undesirable side effects for the cases in which the kernel size is less or equal the padding size. Namely, the huge negative padding value makes it to the output.

```
inp = mx.symbol.Variable('input')
sym = mx.symbol.Pooling(data=inp, kernel=(2,2), pool_type='max', pad=(2,2))

data = mx.ndarray.random_uniform(shape=(1,1,2,2))

executor = sym.bind(mx.cpu(), {'input': data})
out = executor.forward()
print data.asnumpy()
print( out[0].asnumpy() )
```

output:

```
[[[[ 0.54881352  0.59284461]
   [ 0.71518934  0.84426576]]]]
[[[[ -3.40282347e+38  -3.40282347e+38  -3.40282347e+38  -3.40282347e+38
     -3.40282347e+38]
   [ -3.40282347e+38   5.48813522e-01   5.92844605e-01   5.92844605e-01
     -3.40282347e+38]
   [ -3.40282347e+38   7.15189338e-01   8.44265759e-01   8.44265759e-01
     -3.40282347e+38]
   [ -3.40282347e+38   7.15189338e-01   8.44265759e-01   8.44265759e-01
     -3.40282347e+38]
   [ -3.40282347e+38  -3.40282347e+38  -3.40282347e+38  -3.40282347e+38
     -3.40282347e+38]]]]

```

As a possible fix, we were thinking about actually forbidding padding sizes greater or equal to the kernel sizes. After all, it's a meaningless operation, as it is creating values not dependent on the input. This could be applied to convolutions also.

And if someone really wants to do it anyway for some reason, the padding layer is already there for this special cases.

@sbodenstein @taliesinb

**Comment by piiswrong** [comment]
sounds good.

**Comment by taliesinb** [comment]
@matteosal any news about this?

**Comment by matteosal** [comment]
No news, but I didn't forget about it.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
