### ISSUE TITLE
ToolkitError: Error applying callback. Error code -1

### ISSUE THREAD

**Issue by songshuang00** [apache/incubator-mxnet#6194]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: OSX 10.11

Compiler: Unknown

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.7.0

If you are using python package, please provide

Python version and distribution: 2.7.13

## Error Message:
Please paste the full error message, including stack trace.
---------------------------------------------------------------------------
ToolkitError                              Traceback (most recent call last)
<ipython-input-39-e494156d0f91> in <module>()
----> 1 mx_model = mx.model.FeedForward.create(symbol=softmax, X=dataiter, num_epoch=num_epoch, learning_rate=0.1, wd=0.0001, momentum=0.9, eval_metric=mx.metric.Accuracy(), )

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/model.pyc in create(symbol, X, y, ctx, num_epoch, epoch_size, optimizer, initializer, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, eval_batch_end_callback, **kwargs)
    912                   logger=logger,
    913                   work_load_list=work_load_list,
--> 914                   eval_batch_end_callback=eval_batch_end_callback)
    915         return model
    916 

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    793                             logger=logger, work_load_list=work_load_list, monitor=monitor,
    794                             eval_batch_end_callback=eval_batch_end_callback,
--> 795                             sym_gen=self.sym_gen)
    796 
    797 

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/model.pyc in _train_multi_device(symbol, ctx, arg_names, param_names, aux_names, arg_params, aux_params, begin_epoch, end_epoch, epoch_size, optimizer, kvstore, update_on_kvstore, train_data, eval_data, eval_metric, epoch_end_callback, batch_end_callback, logger, work_load_list, monitor, eval_batch_end_callback, sym_gen)
    220         while True:
    221             do_reset = True
--> 222             for data_batch in train_data:
    223                 executor_manager.load_data_batch(data_batch)
    224 

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/io.pyc in next(self)
     71             The data of next batch.
     72         """
---> 73         if self.iter_next():
     74             return DataBatch(data=self.getdata(), label=self.getlabel(), \
     75                     pad=self.getpad(), index=self.getindex())

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/io.pyc in iter_next(self)
    733 
    734     def iter_next(self):
--> 735         ret = super(self.__class__, self).iter_next()
    736         # Postprocess: normalize by mean, scale, ...
    737         self.data_ndarray = (self.data_ndarray - self._rgb_mask) * self._scale

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/io.pyc in iter_next(self)
    606                 self.pad = end - self.data_size
    607                 end = self.data_size
--> 608             self._copy(start, end)
    609             if self.pad > 0:
    610                 bias = self.batch_size - self.pad

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/io.pyc in _copy(self, start, end, bias)
    594 
    595     def _copy(self, start, end, bias=0):
--> 596         _copy_from_sframe(self.data_sframe, self.data_ndarray, start, end, self.field_length, bias)
    597         if self.label_field is not None:
    598             _copy_from_sarray(self.label_sframe, self.label_ndarray, start, end, 1, bias)

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/mxnet/ndarray.pyc in _copy_from_sframe(sf, arr, start, end, field_length, bias)
     96     callback_handle = SFrameCallBackHandle(arr.handle.value, bias, (end - start),
     97                                            ctypes.cast(c_field_length_arr, ctypes.POINTER(ctypes.c_ulonglong)))
---> 98     gl.extensions.sframe_callback(sf, addr, ctypes.addressof(callback_handle), start, end)
     99 
    100 

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/extensions.pyc in <lambda>(*args, **kwargs)
    166 
    167 def _make_injected_function(fn, arguments):
--> 168     return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
    169 
    170 def _class_instance_from_name(class_name, *arg, **kwarg):

/Users/songshuang/anaconda2/envs/gl-env/lib/python2.7/site-packages/graphlab/extensions.pyc in _run_toolkit_function(fnname, arguments, args, kwargs)
    155     if ret[0] != True:
    156         if len(ret[1]) > 0:
--> 157             raise _ToolkitError(ret[1])
    158         else:
    159             raise _ToolkitError("Toolkit failed with unknown error")

ToolkitError: Error applying callback. Error code -1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

mx_model = mx.model.FeedForward.create(symbol=softmax, X=dataiter, num_epoch=num_epoch, learning_rate=0.1, wd=0.0001, momentum=0.9, eval_metric=mx.metric.Accuracy())

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
