### ISSUE TITLE
Using ignore_labels in SoftmaxOutput with multi_output = true

### ISSUE THREAD

**Issue by jk314** [apache/incubator-mxnet#6202]
I have a confusion regarding using SoftmaxOutput for multi-label classification with ignore_labels.
It seems that if the labels are provided as a 1-hot array, the ignore_labels are not honoured, and gradients are still compute for those (x,y) locations.

For example:
Lets say we have a image segmentation problem with two labels : S == Sky == 0 and G == Ground == 1 and C == Car == 2 and ignore_label == 255

You can construct the labels using either 1ofK encoding or using a single array to hold all labels

Method1:
Label[0,:] = [ 1 1 1 1  ; 255 255 0 0 ; 0 0 0 0]  
Label[1,:] = [ 0 0 0 0  ; 255 255 0 0 ; 1 1 1 1]  
Label[2,:] = [ 0 0 0 0  ; 255 255 1 1 ; 0 0 0 0]  

Method2:
Label[:] = [ 0 0 0 0  ; 255 255 2 2 ; 1 1 1 1]  1

And say your prediction will look something like this
Pred[0,:] = [ 0.9 0.9 0.9 0.9  ; 0.9 0.9 0 0 ; 0 0 0 0]  
Pred[1,:] = [ 0 0 0 0  ; 0 0 0 0 ; 0.9 0.9 0.9 0.9]  
Pred[2,:] = [ 0 0 0 0  ; 0 0 0.9 0.9 ; 0 0 0 0]
​
When we use Method1 with SoftmaxLabel with multi_output = true, the ignore_labels are NOT honoured in the gradients computed by backward(). However they work as expected with Method2.

Why does ignore label work differently for method1 and method2 ?

Sample code to reproduce this is attached
`
    import mxnet as mx
    import numpy as np

    def test_softmax():
        workspace=256

        import logging
        head = '%(asctime)-15s %(message)s'
        logging.basicConfig(level=logging.DEBUG, format=head)

        ignore_label = 255

        data = mx.sym.Variable(name='data') # input data to softmax
        joint_labels = mx.sym.Variable(name='labs')
        sym = mx.sym.SoftmaxOutput(data=data, label = joint_labels, multi_output=True, use_ignore=True, ignore_label=ignore_label,
                                            name='softmax')

        l1 = np.array( [[[1, 1, 1, 1], [255, 255, 0, 0], [0, 0, 0, 0]],
                        [[0, 0, 0, 0], [255, 255, 0, 0], [1, 1, 1, 1]],
                        [[0, 0, 0, 0], [255, 255, 1, 1], [0, 0, 0, 0]]]
            )

        l2 = np.array([[0,0,0,0],[255,255,2,2],[1,1,1,1]])

        d1 = np.array( [[[0.9, 0.9, 0.9, 0.9], [0.9, 0.9, 0, 0], [0, 0, 0, 0]],
                        [[0, 0, 0, 0], [0.9, 0.9, 0, 0], [0.9, 0.9, 0.9, 0.9]],
                        [[0, 0, 0, 0], [0.9, 0.9, 0.9, 0.9], [0, 0, 0, 0]]]
            )

        d1 = np.expand_dims(d1, axis=0)
        l1 = np.expand_dims(l1, axis=0)
        l2 = np.expand_dims(l2, axis=0)

        print('d1 = {}'.format(d1.shape))
        print('l1 = {}'.format(l1.shape))
        print('l2 = {}'.format(l2.shape))

        print('d1 = {}'.format(d1))
        print('l1 = {}'.format(l1))
        print('l2 = {}'.format(l2))

        d = mx.nd.array(d1)
        lmx1 = mx.nd.array(l1)
        lmx2 = mx.nd.array(l2)

        dx = mx.nd.empty(d1.shape)
        e1 = sym.bind(ctx=mx.cpu(), args={'data':d, 'labs':lmx1}, args_grad={'data': dx})
        e1.forward(is_train=True)
        e1.backward(out_grads=[mx.nd.ones(dx.shape)])
        print ('\n e1 grad_arrays[0] = {}'.format(e1.grad_arrays[0].asnumpy()))

        e2 = sym.bind(ctx=mx.cpu(), args={'data':d, 'labs':lmx2}, args_grad={'data': dx})
        e2.forward(is_train=True)
        e2.backward(out_grads=[mx.nd.ones(dx.shape)])
        print ('\n e2 grad_arrays[0] = {}'.format(e1.grad_arrays[0].asnumpy()))

    if __name__ == '__main__':
        test_softmax()

`
The returned output is:
`
    d1 = (1, 3, 3, 4)
    l1 = (1, 3, 3, 4)
    l2 = (1, 3, 4)
    d1 = [[[[ 0.9  0.9  0.9  0.9]
       [ 0.9  0.9  0.   0. ]
       [ 0.   0.   0.   0. ]]

      [[ 0.   0.   0.   0. ]
       [ 0.9  0.9  0.   0. ]
       [ 0.9  0.9  0.9  0.9]]

      [[ 0.   0.   0.   0. ]
       [ 0.9  0.9  0.9  0.9]
       [ 0.   0.   0.   0. ]]]]
    l1 = [[[[  1   1   1   1]
       [255 255   0   0]
       [  0   0   0   0]]

      [[  0   0   0   0]
       [255 255   0   0]
       [  1   1   1   1]]

      [[  0   0   0   0]
       [255 255   1   1]
       [  0   0   0   0]]]]
    l2 = [[[  0   0   0   0]
      [255 255   2   2]
      [  1   1   1   1]]]

     e1 grad_arrays[0] = [[[[ -4.48470414e-01  -4.48470414e-01  -4.48470414e-01  -4.48470414e-01]
       [ -2.54666672e+02  -2.54666672e+02   2.24235207e-01   2.24235207e-01]
       [  2.24235192e-01   2.24235192e-01   2.24235192e-01   2.24235192e-01]]

      [[  2.24235192e-01   2.24235192e-01   2.24235192e-01   2.24235192e-01]
       [ -2.54666672e+02  -2.54666672e+02   2.24235207e-01   2.24235207e-01]
       [ -4.48470414e-01  -4.48470414e-01  -4.48470414e-01  -4.48470414e-01]]

      [[  2.24235192e-01   2.24235192e-01   2.24235192e-01   2.24235192e-01]
       [ -2.54666672e+02  -2.54666672e+02  -4.48470414e-01  -4.48470414e-01]
       [  2.24235192e-01   2.24235192e-01   2.24235192e-01   2.24235192e-01]]]]

     e2 grad_arrays[0] = [[[[-0.03737254 -0.03737254 -0.03737254 -0.03737254]
       [ 0.          0.          0.01868627  0.01868627]
       [ 0.01868627  0.01868627  0.01868627  0.01868627]]

      [[ 0.01868627  0.01868627  0.01868627  0.01868627]
       [ 0.          0.          0.01868627  0.01868627]
       [-0.03737254 -0.03737254 -0.03737254 -0.03737254]]

      [[ 0.01868627  0.01868627  0.01868627  0.01868627]
       [ 0.          0.         -0.03737254 -0.03737254]
       [ 0.01868627  0.01868627  0.01868627  0.01868627]]]]
`

Note that the e2 grad has 0's where the ignore_label is set, where as e1 does not honour the ignore_label. Can someone explain what I am doing wrong here?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
