### ISSUE TITLE
Install the scripts in the tools package.

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#6206]
MXNet has provides many utility scripts in the tools folder. These scripts are commonly used(e.g: tools/im2rec.py). 
These should packaged and installed when MXNet installed using either PIP or built from source and available in the default PYTHONPATH.

**Comment by szha** [comment]
This is partly resolved thanks to @jiajiechen and the tools scripts will be shipped along with the package starting from the next version. More work needs to be done to move these scripts into bin/ to make it easier to use.
