### ISSUE TITLE
404 error for the installation guide

### ISSUE THREAD

**Issue by AmedeoSapio** [apache/incubator-mxnet#6207]
Hello, 
the link to the [installation guide](http://mxnet.io/get_started/setup.html) seems to be broken.
This page is linked both in github and the website.

**Comment by chetkhatri** [comment]
@AmedeoSapio We are working on this.

CC\ @madjam

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
