### ISSUE TITLE
How to use MakeLoss and self defined metric together

### ISSUE THREAD

**Issue by yangshao** [apache/incubator-mxnet#6210]
I want to use a loss layer only calculating the cross entropy loss without logistic/softmax activation. so I use makeloss as following:

net = mx.sym.Variable('data')
y = mx.sym.Variable('softmax_label')
net = mx.sym.L2Normalization(net,name='l2', mode='instance')

gate_activations = mx.sym.FullyConnected(net, name='fc1_gate', num_hidden=num_class*(num_mixtures + 1))
expert_activations = mx.sym.FullyConnected(net, name='fc1_expert', num_hidden=num_class* num_mixtures)
gating_distribution = mx.sym.softmax(mx.sym.reshape(gate_activations,shape=(-1, (num_mixtures + 1))),axis=1)
expert_distribution = mx.sym.Activation(mx.sym.reshape(expert_activations,shape=(-1, num_mixtures)),name='sigmoid',act_type='sigmoid')
final_probabilities_by_class_and_batch = mx.sym.sum(mx.sym.slice_axis(gating_distribution,axis=1, begin=0, end = num_mixtures) * expert_distribution, axis=1)
out = mx.sym.reshape(final_probabilities_by_class_and_batch,
                                     shape=(-1, num_class),name='softmax')
ce = y * mx.sym.log(out) + (1 - y) * mx.sym.log(1 - out)
loss = mx.sym.MakeLoss(ce, normalization='batch')
pred_loss = mx.sym.Group([loss,mx.sym.BlockGrad(out)])

I use a self defined metric as following:
def ml_acc(label, pred, label_width=4716):
  return float((label == np.round(pred)).sum()) / label_width / pred.shape[0]

but during the training, I get following error:
ValueError                                Traceback (most recent call last)
<ipython-input-9-978e7ebaa7cf> in <module>()
      4         optimizer_params={'learning_rate':0.01},
      5         eval_metric=eval_metrics,
----> 6         num_epoch=3
      7        )

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/base_module.py in fit(self, train_data, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, optimizer, optimizer_params, eval_end_callback, eval_batch_end_callback, initializer, arg_params, aux_params, allow_missing, force_rebind, force_init, begin_epoch, num_epoch, validation_metric, monitor)
    479                     end_of_batch = True
    480 
--> 481                 self.update_metric(eval_metric, data_batch.label)
    482 
    483                 if monitor is not None:

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/module.py in update_metric(self, eval_metric, labels)
    662             Typically ``data_batch.label``.
    663         """
--> 664         self._exec_group.update_metric(eval_metric, labels)
    665 
    666     def _sync_params_from_devices(self):

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/executor_group.py in update_metric(self, eval_metric, labels)
    533                     labels_slice.append(label)
    534 
--> 535             eval_metric.update(labels_slice, texec.outputs)
    536 
    537     def _bind_ith_exec(self, i, data_shapes, label_shapes, shared_group):

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/metric.py in update(self, labels, preds)
    108     def update(self, labels, preds):
    109         for metric in self.metrics:
--> 110             metric.update(labels, preds)
    111 
    112     def reset(self):

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/metric.py in update(self, labels, preds)
    387     def update(self, labels, preds):
    388         if not self._allow_extra_outputs:
--> 389             check_label_shapes(labels, preds)
    390 
    391         for pred, label in zip(preds, labels):

/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/metric.py in check_label_shapes(labels, preds, shape)
     18     if label_shape != pred_shape:
     19         raise ValueError("Shape of labels {} does not match shape of "
---> 20                          "predictions {}".format(label_shape, pred_shape))
     21 
     22 class EvalMetric(object):

ValueError: Shape of labels 1 does not match shape of predictions 2

I think the possible reason is that mxnet module doesn't know which value is the prediction value can be use for eval_metric, currently it's using pred_loss as the prediction right?  how can I specify variable with name 'softmax' is the true prediction should be used? 

Thanks.

## Environment info
Operating System: Centos

Compiler:

Package used (Python/R/Scala/Julia): python 3.6

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by maxenceliu** [comment]
Same question? Have you resolved?

**Comment by maxenceliu** [comment]
@piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
