### ISSUE TITLE
Is optimization a blocking operation on parameter server?

### ISSUE THREAD

**Issue by saurabh3949** [apache/incubator-mxnet#6214]
Assuming that I have 1 parameter server node in dist_async mode and multiple worker nodes, I am trying to do most of the computation on the server using a custom updater function.
Essentially I am trying to implement Word2Vec using async SGD using the parameter server. My updater method receives some indices from the workers and then it performs several matrix operations on the server itself to update the weights.
Will these operations be blocking? If yes, then is it true that I am not achieving any parallelism out of it?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
