### ISSUE TITLE
tools/im2rec.cc does not handle error cases

### ISSUE THREAD

**Issue by mengjiaow** [apache/incubator-mxnet#6216]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

im2rec.cc throws exception in the cases where a file from .lst is not an image or does not exist. It would be better if it handled the exception instead like in im2rec.py

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

./bin/im2rec image.lst image_root_dir output.bin resize=256

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
