### ISSUE TITLE
mxnet.base.MXNetError  on gpus

### ISSUE THREAD

**Issue by yangshao** [apache/incubator-mxnet#6218]
I'm trying to run mxnet on an multi-label problem using self defined MakeLoss, the code runs fine on cpu, but fails on gpus, I cannot find any related information online.

## Environment info
Operating System: Centos

Compiler: gcc 5.3.0

Package used (Python/R/Scala/Julia): python 3.6

MXNet version: 0.9.5

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
[21:55:20] /home/ubuntu/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [21:55:20] /home/ubuntu/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:118: Check failed: err == cudaSuccess (11 vs. 0) Name: MapPlanLargeKernel ErrStr:invalid argument

Stack trace returned 10 entries:
[bt] (0) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x184dfc) [0x2b4cd8067dfc]
[bt] (1) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x17e3b2e) [0x2b4cd96c6b2e]
[bt] (2) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x17f4a7a) [0x2b4cd96d7a7a]
[bt] (3) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb45646) [0x2b4cd8a28646]
[bt] (4) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb201f7) [0x2b4cd8a031f7]
[bt] (5) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb2431c) [0x2b4cd8a0731c]
[bt] (6) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb24c4d) [0x2b4cd8a07c4d]
[bt] (7) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb47472) [0x2b4cd8a2a472]
[bt] (8) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(MXExecutorForward+0x15) [0x2b4cd89ca475]
[bt] (9) /mnt/home/yangshao/.linuxbrew/lib/libffi.so.6(ffi_call_unix64+0x4c) [0x2b4c97755ff6]

Traceback (most recent call last):
  File "mlp.py", line 178, in <module>
    num_epoch=3
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/base_module.py", line 472, in fit
    self.forward_backward(data_batch)
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/base_module.py", line 193, in forward_backward
    self.forward(data_batch, is_train=True)
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/module.py", line 538, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 379, in forward
    exec_.forward(is_train=is_train)
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/executor.py", line 124, in forward
    ctypes.c_int(int(is_train))))
  File "/mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:55:20] /home/ubuntu/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:118: Check failed: err == cudaSuccess (11 vs. 0) Name: MapPlanLargeKernel ErrStr:invalid argument

Stack trace returned 10 entries:
[bt] (0) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x184dfc) [0x2b4cd8067dfc]
[bt] (1) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x17e3b2e) [0x2b4cd96c6b2e]
[bt] (2) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x17f4a7a) [0x2b4cd96d7a7a]
[bt] (3) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb45646) [0x2b4cd8a28646]
[bt] (4) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb201f7) [0x2b4cd8a031f7]
[bt] (5) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb2431c) [0x2b4cd8a0731c]
[bt] (6) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb24c4d) [0x2b4cd8a07c4d]
[bt] (7) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xb47472) [0x2b4cd8a2a472]
[bt] (8) /mnt/home/yangshao/mxnet/lib/python3.6/site-packages/mxnet/libmxnet.so(MXExecutorForward+0x15) [0x2b4cd89ca475]
[bt] (9) /mnt/home/yangshao/.linuxbrew/lib/libffi.so.6(ffi_call_unix64+0x4c) [0x2b4c97755ff6]

[21:55:21] src/engine/naive_engine.cc:35: Engine shutdown

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
