### ISSUE TITLE
suggest add a condition statement to allow label to be None

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#6234]
before https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py#L522,
should add:
```
  if labels is not None:
    ....
  else:
    eval_metric.update....
```
because, sometime we do not need labels for training.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
