### ISSUE TITLE
How to get the total number of keys in kvstore?

### ISSUE THREAD

**Issue by SmartAir** [apache/incubator-mxnet#6248]
Hi, I want to get the total number of keys in kvstore. In addition to directly counting the different keys in `mxnet/src/kvstore/kvstore_dist_srever.h`, is there any existing function that I can use？

 And could someone please tell me how the keys are organized and distributed on multiple server nodes or which file I should read?

Thank you!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
