### ISSUE TITLE
Query Compile Flags

### ISSUE THREAD

**Issue by liangfu** [apache/incubator-mxnet#6250]
Is there anyway to check compile flags of `mxnet` with python interface?
The way i'm trying to use is to locate libmxnet.so, and check linkage with `ldd`:
```
ldd libmxnet.so | grep cud
```
so that I can know whether `cudnn` is enabled, along with which version of cudnn i'm using.

Things become more complicated when there are multiple instance installed in the system, such as locations at `~/.local/lib/python2.7/dist-packages/`, `/usr/local/lib/python2.7/dist-packages/` and multiple version of the library might available in these directories.

I'm wondering is there any more friendly way to do this?
Or what additional work should be done to enable this feature?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
