### ISSUE TITLE
[New OP] slice a row from a matrix with input variable, not a fixed integer.

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#6252]
formally, it is like the following:
```
row_idx = mx.sym.Variable('ridx')
matrix = mx.sym.Variable('matrix')
one_row = mx.sym.slice_row_var(data=matrix, ridx=row_idx)
```
how about to implement a operator be like ```slice_row_var``` ?
it will be very useful!

**Comment by zhreshold** [comment]
sym.take?

**Comment by starimpact** [comment]
seems like it! I will have a try.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
