### ISSUE TITLE
how to use RNN parameters in rnn example

### ISSUE THREAD

**Issue by superclocks** [apache/incubator-mxnet#6254]
@piiswrong, I found that FusedRNNCell used in cudnn_lstm_bucketing.py finally call mxnet.symbol.RNN. These is a parameters mode ({'gru', 'lstm', 'rnn_relu', 'rnn_tanh'} in RNN, i want to know how mode control the rnn net struction, but i can't debug into mxnet.symbol.RNN. Could you show me some infos about mxnet.symbol.RNN, i think the infos in http://mxnet.io/api/python/symbol.html?highlight=rnn#mxnet.symbol.RNN is not  enough

**Comment by szha** [comment]
The mode is just passed to sym.RNN. https://github.com/dmlc/mxnet/blob/master/python/mxnet/rnn/rnn_cell.py#L630-L635
I don't get the question? What are you asking? What is the missing info that could solve your problem?

**Comment by superclocks** [comment]
actually, i want to know the network topology in sym.RNN. and i have a another question, how can i add Hierarchical Softmax activation function in mxnet, follow this instruction http://mxnet.io/how_to/new_op.html?highlight=customopprop ?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
