### ISSUE TITLE
no get_mnist() in test_utils

### ISSUE THREAD

**Issue by ShownX** [apache/incubator-mxnet#6260]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler: GCC 4.9

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.9.5

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`): 

If you are using python package, please provide

Python version and distribution: 2.7 Conda

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

AttributeError: 'module' object has no attribute 'get_mnist'

## Minimum reproducible example
```
import mxnet as mx
mnist = mx.test_utils.get_mnist()
```

I followed the instruction: http://mxnet.io/tutorials/python/mnist.html

I checked the test_utils.py. It does not provide these function. Maybe the document is out-of-date.

**Comment by patriciaaa82** [comment]
I have the same issue

**Comment by alexshepard** [comment]
fwiw, there are other methods to download the same dataset, such as from `sklearn`, which worked fine for me.
you'll need to do some wrangling to fit them into the data iterator for this tutorial, including paying close attention to how you reshape the input data, but you already did the data iterator tutorial, right? ;)

```
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
```
