### ISSUE TITLE
sym, arg_params, aux_params = mx.model.load_checkpoint('vgg16',0) failed in mxnet 0.9.5

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6265]
keep getting the following error when trying to load a model in python:
src/ndarray/ndarray.cc:700: Check failed: header == kMXAPINDArrayListMagic Invalid NDArray file format

**Comment by yuconglin** [comment]
def get_model(prefix, epoch):
    download(prefix+'-symbol.json')
    download(prefix+'-%04d.params' % (epoch,))

 get_model('http://data.mxnet.io/models/imagenet/vgg/vgg16',0)
 sym, arg_params, aux_params = mx.model.load_checkpoint('vgg16', 0)

the above works fine for me

**Comment by patricianing** [comment]
@yuconglin Did you run it on 0.9.5? It works for me on previous versions.

**Comment by yuconglin** [comment]
yes, I ran it on 0.9.5

**Comment by SCP-173-cool** [comment]
Maybe your params files were broken when downloading.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
