### ISSUE TITLE
RNN data iterator for the general inputs

### ISSUE THREAD

**Issue by ykim362** [apache/incubator-mxnet#6266]
The current design of bucketing iterator could only handle the case of input vector size 1. Of course, this is a general use case for the seq-2-seq or language modeling. But, it could not be used for more general input shape. 

In summary, it would be good if we could have a new iterator that can handle input vector of size n.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
