### ISSUE TITLE
NNVM memory optimization example does not work

### ISSUE THREAD

**Issue by MarvinTeichmann** [apache/incubator-mxnet#6272]
# Steps to reproduce

Run the memcost example provided [here](https://github.com/dmlc/mxnet/tree/master/example/memcost).

* `make with_inplace`, `make with_sharing` and `make with_both` all three use the same amount of Memory `Total 1784 MB allocated`.

*  `make no_optimization` runs indefinitely

## Environment info
MXNet versions tested:

* 0.9.5-1
* build from source / master

Operating System: Linux

**Comment by MarvinTeichmann** [comment]
@tqchen

**Comment by eric-haibin-lin** [comment]
I think this example is out of date, currently MXNet always enable inplace_update, and the macro for shared_memory is updated as `NNVM_EXEC_MATCH_RANGE`

https://github.com/dmlc/mxnet/blob/986b736b816018b96e9d1e2c358bb7665b80944d/src/executor/graph_executor.cc#L403

https://github.com/dmlc/nnvm/blob/b279286304ac954098d94a2695bca599e832effb/src/pass/plan_memory.cc#L277

@mli  we should either remove outdated examples, or keep it up to date by testing it regularly

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by MarvinTeichmann** [comment]
The issue still persists. Closing the issue on github does not fix the bug.

**Comment by yajiedesign** [comment]
@MarvinTeichmann ok it reopen,

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by samskalicky** [comment]
@MarvinTeichmann is this still an issue? If so, can you update your reproducibility instructions to 1.3 and we'll try and debug if the issue still persists. Thanks!

**Comment by szha** [comment]
@samskalicky the example hasn't been updated so the instruction remains the same.

**Comment by kalyc** [comment]
@MarvinTeichmann your issue has been fixed by this https://github.com/apache/incubator-mxnet/pull/13235#event-1970036707 can you close it?

**Comment by MarvinTeichmann** [comment]
Thanks.
