### ISSUE TITLE
How to test a c++ operator extension?

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#6294]
Hi,I'm not quite familiar with mxnet c++ API,and after implement a c++ operator extension,and successfully compiled,how to test the operator? For example,how to write a `.cpp` file and use gdb to test the function?

**Comment by piiswrong** [comment]
see https://github.com/dmlc/mxnet/blob/master/tests/python/unittest/test_operator.py for operator tests

**Comment by ysh329** [comment]
mark

**Comment by ysh329** [comment]
@piiswrong Have a MXNet dev Wechat group? :rofl:

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
