### ISSUE TITLE
problem with data iterator for multiple inputs and labels

### ISSUE THREAD

**Issue by jasiozaucha** [apache/incubator-mxnet#6301]
I am trying to use a dataset (input as well as labels) of shape  1000 x 45
Using this in a straightforward way doesn't work, in order to have a multidimensional label you need a dictionary of many labels. 
So I create the dictionaries with keys 'data1' to 'data45' and a single value each
as well as  'label1' to 'label45' and a single value each

```
    data = np.load('dataset.npy')
    X=np.array(data[0]) 
    Y=np.array(data[1]) 
    data = {}
    label = {}
    for i in xrange(1, len(X[0])+1):
	data['data'+str(i)] = np.transpose(X)[i].reshape(1000,1)
	label['label'+str(i)] = np.transpose(Y)[i].reshape(1000,1)
    data_iter = mx.io.NDArrayIter(data, label, 1, True, last_batch_handle='discard')
```
When I try to 'bind':  
 
` mod.bind(data_shapes=data_iter.provide_data,label_shapes=data_iter.provide_label) `

I get an error: 
`ValueError: Data provided by data_shapes don't match names specified by data_names ([DataDesc[data42,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data43,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data40,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data41,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data44,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data28,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data29,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data20,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data21,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data22,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data23,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data24,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data25,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data26,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data27,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data9,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data8,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data5,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data4,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data7,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data6,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data1,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data0,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data3,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data2,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data37,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data36,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data35,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data34,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data33,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data32,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data31,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data30,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data39,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data38,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data19,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data18,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data15,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data14,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data17,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data16,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data11,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data10,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data13,(1, 1L),<type 'numpy.float32'>,NCHW], DataDesc[data12,(1, 1L),<type 'numpy.float32'>,NCHW]] vs. ['data'])`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
