### ISSUE TITLE
color channel order of .rec files

### ISSUE THREAD

**Issue by yuconglin** [apache/incubator-mxnet#6307]
If I use bin/im2rec or im2rec.py to generate .rec files from images according to http://mxnet-tqchen.readthedocs.io/en/latest/packages/python/io.html or https://github.com/dmlc/mxnet/tree/master/example/image-classification,
is the channel order of the rec file always RGB? or it is dependent on the "color" parameter for im2rec as user input?

**Comment by piiswrong** [comment]
rec file stores JPEG images. The color channel order depends on how you decode it. By default ImageRecordIter gives RGB

**Comment by yuconglin** [comment]
Same for png?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
