### ISSUE TITLE
Better enum generator in cpp-package

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#6309]
Currently the enum generated for cpp-package in cpp-package/include/mxnet-cpp/op.h directly copies the enum name declared in NNVM registry. 

e.g. the enum generated for PadMode is
```
enum class PadMode {
  constant = 0,
  edge = 1,
  reflect = 2
};
```
Ideally we should generate enums following cpp style convention, such as 
```
enum class PadMode {
  kConstant = 0,
  kEdge = 1,
  kReflect = 2
};
```
so that enum will not conflict with existing cpp keywords (e.g. static, default, etc).

To do so OpWrapperGenerator.py needs to be updated by appending 
```
self.enumValues[i] = 'k' + self.enumValues[i][0].upper() + self.enumValues[i][1:]
```
to https://github.com/dmlc/mxnet/blob/master/cpp-package/scripts/OpWrapperGenerator.py#L29
and change the enums used in cpp-package/example/*.cc accordingly. 

We should change it sooner rather than later before the cpp-package grows huge. 
@piiswrong  @lx75249 @hjk41  Any comment?

**Comment by lx75249** [comment]
Agree. It's better to solve it before we need to consider backward compatibility.

**Comment by eric-haibin-lin** [comment]
@lx75249 one more edge case to check: 
```
enum class Convolution_v1CudnnTune {
  kNone = 0,
  kFastest = 1,
  kLimited_workspace = 2,
  kOff = 3
};
```
 `kLimited_workspace` should be `kLimitedWorkspace`

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
