### ISSUE TITLE
Running image-classification example failed with opencv issue

### ISSUE THREAD

**Issue by EvanzzzZ** [apache/incubator-mxnet#6312]
Trying to run the example on the `example/image-classification` folder by
`python train_cifar10.py --network alexnet --batch-size 128`.

The program failed with error message `src/io/iter_image_recordio_2.cc:200: ImageRec need opencv to process`, which said the `MXNET_USE_OPENCV` is not turned on.

What I missed here?

**Comment by eric-haibin-lin** [comment]
check your config.mk (if you built MXNet from source) and set MXNET_USE_OPENCV=1


On 2017年5月17日, at 13:51, EvanChong <notifications@github.com> wrote:

MXNET_USE_OPENCV

**Comment by EvanzzzZ** [comment]
If you mean the USE_OPENCV, it's already set to 1. 
Double check and rebuild the package and same error happened.

**Comment by formath** [comment]
I met the same problem. Using `opencv` to compile have been successful but running example will cause that error.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
Hi @EvanzzzZ and @formath , are you still facing the same issue?

**Comment by anirudhacharya** [comment]
this issue is not reproducible. please close this issue.

@EvanzzzZ please reopen if the issue persists.
