### ISSUE TITLE
Issue converting caffe model with multiple outputs to mxnet

### ISSUE THREAD

**Issue by andrewbleonard** [apache/incubator-mxnet#6319]
I am trying to use the caffe to mxnet converter tool at [convert_model.py](https://github.com/dmlc/mxnet/blob/master/tools/caffe_converter/convert_model.py) on a caffe model with more than one final output and running into issues.  It looks like the converter tool is setup to handle a single final output layer in [convert_symbol.py](https://github.com/dmlc/mxnet/blob/master/tools/caffe_converter/convert_symbol.py), so some of my layers that are only in the DAGs of the other output layers are culled out (at least I think that is what is happening).  Because of this, I get an assertion error (pasted below) in convert_model.py.  Does the converter tool currently not support caffe models with multiple outputs?
Sorry if my nomenclature is wrong; I am new to deep learning, caffe, and mxnet.

## Environment info
Operating System: **Ubuntu 14.04.5 LTS**

Compiler: **4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)**

Package used (Python/R/Scala/Julia): **Python**

MXNet version: **0.9.5**

Python version and distribution: **2.7.6 from Ubuntu repos**

## Error Message:
Please paste the full error message, including stack trace.
```
converting layer res5c_up_pose, wmat shape = (2048, 16, 3, 3)Traceback (most recent call last):
  File "convert_model.py", line 165, in <module>
    main()
  File "convert_model.py", line 161, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "convert_model.py", line 83, in convert_model
    bias = bias.reshape(arg_shape_dic[bias_name])
KeyError: 'res5c_up_pose_bias'
```
convert_model.py is reading in the prototxt file and iterating over each layer, assuming that the layer exists in the arg_shape_dic, but since it is getting culled out, it doesn't and causes the crash.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. **Run convert_model.py against a prototxt file with multiple outputs**

**Comment by arikpoz** [comment]
Please check again with the latest merge of (#6489)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
