### ISSUE TITLE
DataParallelExecutorGroup hangs

### ISSUE THREAD

**Issue by zhaolili** [apache/incubator-mxnet#6325]
the **_bind_** function costs a long time, taking around 80 seconds to complete binding operation. Below shows part of my code. 

```
mod = mx.mod.Module(symbol=new_sym, context=devs)
mod.bind(data_shapes=train.provide_data, label_shapes=train.provide_label,for_training=True)
mod.init_params(initializer=mx.init.Xavier(rnd_type='gaussian', factor_type="in", magnitude=2))
```

And after debugged into the bind function, i found the code hangs in function '_**DataParallelExecutorGroup**_' which is the bottleneck.   Anyone ever met this issue? Thanks a lot.

Here is my system info:
ubuntu 16.04
cuda 8.0.44

**Comment by piiswrong** [comment]
It could happen the first time you are using gpus.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by kandoiNikhil** [comment]
i am currently facing the same issue, but the halt period is like 9 minutes which seems way too long.
Also, this is happening on every occurrence rather than just being on the first time.

Is there something I can try to debug this time

**Comment by kandoiNikhil** [comment]
@yajiedesign, would you mind re-opening this issue.
Thanks.
