### ISSUE TITLE
Error running bash script/get_coco.sh

### ISSUE THREAD

**Issue by maxrichter-scdm** [apache/incubator-mxnet#6342]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04

Compiler:
GCC 5.4.0 20160609

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.5.post1

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
 extracting: val2014/COCO_val2014_000000441814.jpg  
mv: missing file operand
Try 'mv --help' for more information.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
from my HOME directory, I run:
The directory is:
example/rcnn/
Then run: bash script/get_coco.sh
The three ZIP files were downloaded, the error occurs in the unzip from the test2014 as well as the train2014 image folder.
The instances_train-val2014.zip extracts fine.
The folder: data/coco/images is empty.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. mxnet/example/rcnn/
2. I executed all commands until:
3. bash script/get_coco.sh

## What have you tried to solve it?

1. I tried to redownload the data
2. I restarted the EC2 machine
3.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
