### ISSUE TITLE
Split layers of network to multiple modules using SequentialModule

### ISSUE THREAD

**Issue by zazzydistsgd** [apache/incubator-mxnet#6344]
Hi, 

I'm trying to split layers of network (e.g. LeNet) to different modules, and train the network using SequentialModule, like the example did
https://github.com/dmlc/mxnet/blob/master/example/module/sequential_module.py

However, the example tries to do model and data parallelization at the same time. Basically, I just want to do the regular networking training like:
data->layer0->layer1->...->ouput_layer and then backprop (but layers are split into multiple modules).

I tried to change the input of the fully connected layer in second module by modifying this line in the foregoing example to make activation function 1 as input to next layer(fc2 in the example) (I changed the "data=data" to "data=act1"):
https://github.com/dmlc/mxnet/blob/master/example/module/sequential_module.py#L30

But I got this error:
```
Traceback (most recent call last):
  File "sequential_module.py", line 65, in <module>
    optimizer_params={'learning_rate':0.01, 'momentum': 0.9}, num_epoch=n_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/base_module.py", line 449, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/sequential_module.py", line 196, in init_params
    _check_name(arg_names, arg_params.keys(), self._modules, i_layer)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/sequential_module.py", line 189, in _check_name
    type(modules[known_names[name]])))
AssertionError: Duplicated parameter names: name "fc1_weight" in layer 1 (<class 'mxnet.module.module.Module'>) is already used in layer 0 (<class 'mxnet.module.module.Module'>).
```
Can someone tell me how can I split layers of network into multiple module, connect them together as a chain, and train the whole chain with data input at layer0 and label at last layer?

## Environment info
Operating System:
ubuntu 14.04
Compiler:
gcc 4.8.4
Package used:
Python
build from source

Python version and distribution:
python 2.7.10

**Comment by EvanzzzZ** [comment]
My guess is you don't need to explicitly change the input of the second module to the output of the last module. `Seq_module.add()` simply chain that for you.

**Comment by zazzydistsgd** [comment]
Thanks for the response! I think your guess is probably right, I use the following code to split LeNet into different modules:
```
def get_lenet_symbol(num_classes=10, add_stn=False):
    '''
    get lenet symbol, and split it into multiple modules wrt layers
    '''
    data = mx.symbol.Variable('data')
    if(add_stn):
        data = mx.sym.SpatialTransformer(data=data, loc=get_loc(data), target_shape = (28,28),
                                         transform_type="affine", sampler_type="bilinear")
    #module 1:------------------------------------------------------------------------------
    # first conv
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=20)
    tanh1 = mx.symbol.Activation(data=conv1, act_type="tanh")
    pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",
                              kernel=(2,2), stride=(2,2))
    mod1 = mx.mod.Module(pool1, label_names=[], context=mx.context.cpu())
    #module 2:------------------------------------------------------------------------------
    # second conv
    data = mx.symbol.Variable('data')
    conv2 = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=50)
    tanh2 = mx.symbol.Activation(data=conv2, act_type="tanh")
    pool2 = mx.symbol.Pooling(data=tanh2, pool_type="max",
                              kernel=(2,2), stride=(2,2))
    flatten = mx.symbol.Flatten(data=pool2)
    mod2 = mx.mod.Module(tanh2, label_names=[], context=mx.context.cpu())

    #module 3:------------------------------------------------------------------------------
    # first fullc
    data = mx.symbol.Variable('data')
    fc1 = mx.symbol.FullyConnected(data=data, num_hidden=500)
    tanh3 = mx.symbol.Activation(data=fc1, act_type="tanh")
    mod3 = mx.mod.Module(tanh3, label_names=[], context=mx.context.cpu())

    #module 4:------------------------------------------------------------------------------
    # second fullc
    data = mx.symbol.Variable('data')
    fc2 = mx.symbol.FullyConnected(data=data, num_hidden=num_classes)
    # loss
    lenet = mx.symbol.SoftmaxOutput(data=fc2, name='softmax')
    mod4 = mx.mod.Module(lenet, context=mx.context.cpu())

    #--------------------------------------------------------------------------------
    # Container module
    #--------------------------------------------------------------------------------
    lenet_mod_seq = mx.mod.SequentialModule()
    lenet_mod_seq.add(mod1, take_labels=False).add(mod2, auto_wiring=True, take_labels=False).add(mod3, auto_wiring=True, take_labels=False).add(mod4, take_labels=True, auto_wiring=True)
    return lenet_mod_seq
```
Based on my tests of time costs for each iteration and each epoch, after splitting the network, the time costs are slightly higher than just train using the original code (https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_mnist.py). (e.g. 424.044 sec for each epoch after splitting, and 405 sec for each epoch on the original code, trained with MNIST data set using batch size of 128).
But, how can I totally make sure that this is the case (I don't need to explicitly change the input of the each module following the first module in the chain)?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
