### ISSUE TITLE
is there a way to get the number of images in a rec file

### ISSUE THREAD

**Issue by yuconglin** [apache/incubator-mxnet#6360]
Suppose that we have a ".rec" file, is there any function I can use to get the number of images in it?

**Comment by mli** [comment]
do you have the `lst` file? if yes then you can count the images. otherwise you need to pass the `rec` once.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
