### ISSUE TITLE
upgrdae to pre-release version of mxnet

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#6367]
i want to upgrade to the pre-release package of mxnet. Can i do this through pip`? i tried `pip` with `--pre` but no luck? is there another way to upgrade a library to the pre-release version. i am using mac

**Comment by SCP-173-cool** [comment]
The newest version is `0.9.5`. Maybe you could try `pip uninstall mxnet; pip install mxnet -U --pre`.

**Comment by szha** [comment]
we have not released any pre-release pip packages. the new version has been upgraded to 0.10.0.

**Comment by szha** [comment]
We now provide nightly builds as pre-releases. Give it a try if you'd like to stay up to speed of the latest mxnet development. Feel free to reopen if you have more questions.
