### ISSUE TITLE
remove "update_metric" in module faces weird performance

### ISSUE THREAD

**Issue by zazzydistsgd** [apache/incubator-mxnet#6371]
Hi,

I faced an issue involves "update_metric" in module(https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L875). 
Based on the document, this function is to 
"Evaluate and accumulate evaluation metric on outputs of the last forward computation" e.g. train accuracy.

However, for some reasons I'm not sure, time costs of this function is quite high in each training iteration/epoch.
based on my test (train with cifar10 dataset, --network resnet --num-layers 110 --batch-size 128)
time cost for the whole iteration: 15.2210628986
time cost for forward: 0.000531911849976
time cost for backward: 0.000345945358276.

Also, this issue reported similar performances: https://github.com/dmlc/mxnet/issues/1614

Please correct me if I'm wrong, my thinking is the "update_metric" function is not necessary in training iterations if one doesn't care about the metrics for training accuracy.
Then, I tried to remove this funtion in module.fit()(https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L497)

After removing it, I observed some weird performance:
```
INFO:root:Epoch[0] Batch [1]	Speed: 3320.10 samples/sec	accuracy=nan
time cost for iteration: 0.0386838912964
for ward duration: 0.000452995300293
back ward duration: 0.000340223312378
INFO:root:Epoch[0] Batch [2]	Speed: 5261.22 samples/sec	accuracy=nan
time cost for iteration: 0.0244591236115
for ward duration: 0.000442981719971
back ward duration: 0.000354051589966
INFO:root:Epoch[0] Batch [3]	Speed: 1540.11 samples/sec	accuracy=nan
time cost for iteration: 0.0833520889282
for ward duration: 0.000473976135254
back ward duration: 0.000328063964844
INFO:root:Epoch[0] Batch [4]	Speed: 8.49 samples/sec	accuracy=nan
time cost for iteration: 15.0820829868
for ward duration: 0.000502109527588
back ward duration: 0.000353097915649
INFO:root:Epoch[0] Batch [5]	Speed: 8.42 samples/sec	accuracy=nan
time cost for iteration: 15.2083821297
for ward duration: 0.00049901008606
back ward duration: 0.000357866287231
INFO:root:Epoch[0] Batch [6]	Speed: 8.46 samples/sec	accuracy=nan
time cost for iteration: 15.1280579567
for ward duration: 0.000498056411743
back ward duration: 0.000345945358276
INFO:root:Epoch[0] Batch [7]	Speed: 8.94 samples/sec	accuracy=nan
time cost for iteration: 14.3195838928
for ward duration: 0.000482082366943
back ward duration: 0.000361919403076
INFO:root:Epoch[0] Batch [8]	Speed: 7.67 samples/sec	accuracy=nan
time cost for iteration: 16.6979029179
for ward duration: 0.000547885894775
back ward duration: 0.000380992889404
INFO:root:Epoch[0] Batch [9]	Speed: 7.79 samples/sec	accuracy=nan
time cost for iteration: 16.4334449768
for ward duration: 0.000562906265259
back ward duration: 0.000375032424927
INFO:root:Epoch[0] Batch [10]	Speed: 8.39 samples/sec	accuracy=nan
time cost for iteration: 15.2526218891
for ward duration: 0.000514984130859
back ward duration: 0.000386953353882
INFO:root:Epoch[0] Batch [11]	Speed: 8.21 samples/sec	accuracy=nan
time cost for iteration: 15.5851790905
for ward duration: 0.000509977340698
back ward duration: 0.00036096572876
INFO:root:Epoch[0] Batch [12]	Speed: 8.22 samples/sec	accuracy=nan
time cost for iteration: 15.5702950954
for ward duration: 0.000547170639038
back ward duration: 0.000411987304688
INFO:root:Epoch[0] Batch [13]	Speed: 7.93 samples/sec	accuracy=nan
time cost for iteration: 16.1498420238
for ward duration: 0.000536918640137
back ward duration: 0.000396013259888
INFO:root:Epoch[0] Batch [14]	Speed: 8.13 samples/sec	accuracy=nan
time cost for iteration: 15.7489438057
for ward duration: 0.000575065612793
back ward duration: 0.000539064407349
```
As one can see from this sample output, in the first three iterations, it seems I avoided time costs of "update_metric" successfully, however in the next iterations, time cost for the whole iteration increased largely and the value became similar to the one when I did nothing on the "update_metric". 

My questions are:
1. can someone tell me why the "update_metric" function costs so much time in a certain iteration?
2. how can I skip the "update_metric" in an iteration and only do forward(), back_ward(), and update() by modifying the "fit" function in module
(https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L377)?

**Comment by luoyetx** [comment]
How do you test the performance? Would you paste your code?

I think there's some trick to evaluate the time of forward and backward. Since `forward` and `backward` call only push the ops to engine and return immediately, and in `update_metric` function, it needs to get the output result from engine (mainly call `asnumpy()`), which means `update_metric` will wait `forward` and `backward` finishes.

**Comment by zazzydistsgd** [comment]
@luoyetx many thanks for your response. Based on the information you offered, I probably used a wrong way to measure time costs for `forward` and `backward`. I just measured the time cost for `forward_backward` here, 
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L190
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L191
The time costs I got should just be the time cost that pushing the ops to the engine. (Also I measured the time cost of `update_metric` through this line https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L495, whose time cost is quite high).
Can you show me the tricks to get the real time cost for `forward_backward` and `update_metric`?
Also, do you have effective way to remove the `update_metric` for train-accuracy and only implement it on validation data like from this line( https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L524)?
Thank you very much.

**Comment by juilin** [comment]
Can you show me the tricks to get the real time cost for forward_backward and update_metric?
=> Use profiler to see time cost of forward_backward http://mxnet.io/how_to/perf.html#profiler; update_metric should not take too much time. However, it needs to wait for the result ready

do you have effective way(s) to remove the update_metric for train-accuracy and only implement it on validation data?
=> set validation_metric, eval_metric in fit()

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by liav-teichner** [comment]
Reading this thread it is still not clear to me whether calling lowering the frequency of calls to update_metric affects the trained final trained model - e.g. calling update metric once for for every two forward_backward calls result.
