### ISSUE TITLE
"im2rec" doesn't support the "tif" format

### ISSUE THREAD

**Issue by Daliben** [apache/incubator-mxnet#6375]
Hi,
I would like to create a .rec file for "tif" format images by using im2rec.py.
First, i have run im2rec for creating .list file, but the file obtained was empty. 
I think that "im2rec" doesn't support the "tif" format. 
Please, can you help me to create .rec file from"tif" images?
Thanks in advance. 
## Environment info
Operating System:Windows 8.1

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.9.5

Python version and distribution:2.7

**Comment by piiswrong** [comment]
look at the usage message. There is a option for setting file extensions to include

**Comment by Daliben** [comment]
Hi,
I don't understand what do you mean by usage message. can you explain me please.

**Comment by SCP-173-cool** [comment]
@Daliben remember to read `im2rec.py`, and find：
```python
cgroup.add_argument('--exts', nargs='+', default=['.jpeg', '.jpg'],
                        help='list of acceptable image extensions.')

```

**Comment by Daliben** [comment]
Hi,
That's OK!...Thanks for your reply  :+1:

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
