### ISSUE TITLE
How did the GraphExecutor::RunOps make sure the computation is not deadlocked?

### ISSUE THREAD

**Issue by shuokay** [apache/incubator-mxnet#6376]
When digging the source code of mxnet, I am curious about mxnet's methods to solve the compute deadlock problem, or maybe this is no deallock at all.
If there is no risk of deadlock, please kindly give a brief explanation

Thanks.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
