### ISSUE TITLE
Enhancement: Segmentation of namespace mx.sym

### ISSUE THREAD

**Issue by asmushetzel** [apache/incubator-mxnet#6381]
With ongoing development, having a flat list of operators in mx.sym becomes cumbersome. There will be more and more closely related groups of operators for support of certain special types of computations and I think we should reflect that in terms of different namespaces for operators for 
- easier navigation and usage
- keeping development of operators more consistent (by forcing them to belong to a certain namespace and therfore  to comply in interfaces/functionality with the other operators in that namespace).  

Some examples of such namespaces:

mx.sym.random (for all random sampling methods)
mx.sym.la  (for all advanced single/double precision linear algebra as matrix decompositions etc)

I think that can improve the outside perception of MXNet by the user community.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
