### ISSUE TITLE
build with mkl, cannot find -lmkl_intel_lp64, -lmkl_intel_thread, -lmkl_core

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6384]
I am trying to build MXNet from source, and using MKL.

1. Enable USE_MKL2017=1 in make/config.mk
2. wget https://github.com/dmlc/web-data/raw/master/mxnet/mklml-release/mklml_lnx_<MKL VERSION>.tgz
3.tar zxvf mklml_lnx_<MKL VERSION>.tgz
4. cp -rf mklml_lnx_<MKL VERSION>/* <MKLML_ROOT>/
5. Set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MKLML_ROOT/lib
6. make -j USE_BLAS=mkl

Then I am getting:
/bin/ld: cannot find -lmkl_intel_lp64
/bin/ld: cannot find -lmkl_intel_thread
/bin/ld: cannot find -lmkl_core

Where can I get those three libraries? They are not included in the downloaded MKL files based on 
https://github.com/dmlc/mxnet/blob/master/MKL_README.md

**Comment by piiswrong** [comment]
Do exactly as the readme saids https://github.com/dmlc/mxnet/blob/master/MKL_README.md
don't change use_blas

**Comment by patricianing** [comment]
@piiswrong So I should add " USE_BLAS=mkl"in config.mk, but not specify when make? Thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
