### ISSUE TITLE
Compile install MXNet using MKL

### ISSUE THREAD

**Issue by yancz1989** [apache/incubator-mxnet#6386]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

MXNet commit hash (`git rev-parse HEAD`):
d35fc765f9526bd836ba4a431729d130a862db3f

If you are using python package, please provide

Python version and distribution:
python3.5

#Error message
src/operator/./mkl/mkl_pooling-inl.h: In member function ‘virtual void mxnet::op::MKLPoolingOp<xpu, DType>::Forward(const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::TBlob>&)’:
src/operator/./mkl/mkl_pooling-inl.h:185:11: error: ‘dnnAlgorithmPoolingAvgIncludePadding’ was not declared in this scope
           dnnAlgorithmPoolingAvgIncludePadding : dnnAlgorithmPoolingAvg;

## What have you tried to solve it?

1. modify root of MKL directory

**Comment by piiswrong** [comment]
@glingyan @zhenlinluo

**Comment by glingyan** [comment]
Young jin will support for me
Customer is use an old mkl version, please download latest

**Comment by glingyan** [comment]
latest in https://software.intel.com/en-us/performance-libraries 
you could check mkl_version.h #define __INTEL_MKL_BUILD_DATE 20170127

**Comment by yancz1989** [comment]
I have checked my MKL installation. with MKL_BUILD_DATE. But I haven’t found any libmklml_intel.so or other related library. Any advices?

**Comment by yancz1989** [comment]
Or can you give me the location of dnnAlgorithmPoolingAvgIncludePadding definition?

**Comment by glingyan** [comment]
Current mxnet is enable for mklml small package, please check mkl_readme.md for details

**Comment by yancz1989** [comment]
I know it, and follow your advice download mklml from https://github.com/dmlc/web-data/blob/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20170209.tgz <https://github.com/dmlc/web-data/blob/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20170209.tgz>. The error still exists. I wonder if there is any update version of this software?

**Comment by glingyan** [comment]
Please provide the whole crash stack
Yonng jin may help you on that

**Comment by yancz1989** [comment]
I upload my config.mk file
[Uploading config.mk.txt…](config.mk file)
during compilation, the output and the error showed are uploaded
[out.log.txt](https://github.com/dmlc/mxnet/files/1031179/out.log.txt)

[Uploading out.log.txt…](out.log.txt)

MKL info
#define __INTEL_MKL_BUILD_DATE 20170127

#define __INTEL_MKL__ 2017
#define __INTEL_MKL_MINOR__ 0
#define __INTEL_MKL_UPDATE__ 2

#define INTEL_MKL_VERSION 20170002

**Comment by yancz1989** [comment]
[config.mk.txt](https://github.com/dmlc/mxnet/files/1031180/config.mk.txt)

**Comment by yancz1989** [comment]
@glingyan

**Comment by ykim362** [comment]
Hi @yancz1989 
Could you do this?

1. Download mklml into any of your directory. (wget https://github.com/dmlc/web-data/raw/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20170209.tgz)
2. Extract the file, then you will have a directory named ./mklml_lnx_2017.0.2.20170209
3. export USE_MKLML=1;export MKLROOT={the directory you extracted the mklml)
4. Copy 'libmklml_gnu.so' and 'libmklml_intel.so' into /usr/local/ from the mklml_lnx_2017.0.2.20170209/lib directory
5. Please use the default ./make/config.mk file. and just change USE_MKL2017 and USE_MKL2017_EXPERIMENTAL to 1. 
6. compile again.

Please let me know if this doesn't work.

Thanks.

**Comment by yancz1989** [comment]
Hi @ykim362 
I finished the compilation. One more variable should be set in config.mk is the USE_BLAS = mkl.

But, when I run fcn_xs example, I get the following error from gdb.

Thread 76 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff1a3fb300 (LWP 30958)]
0x00007fff7a953c29 in mkl_vsl_sub_kernel_l9_sBRngMCG31M1 ()
   from /usr/local/lib/python2.7/dist-packages/mxnet/libmklml_intel.so

Have you ever seen this problem?

**Comment by ykim362** [comment]
How could you run it? 
When I downloaded experiment data, its directory steucture was different from one the script expected. So, I got an error that there is no train.lst file.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
