### ISSUE TITLE
FCN_XS example can't run.

### ISSUE THREAD

**Issue by yancz1989** [apache/incubator-mxnet#6387]
About FCN_XS example.

Environment info

Operating System:
Ubuntu 16.04

Compiler:
g++ 5.4

Package used (Python/R/Scala/Julia):
Python

MXNet version: mxnet-mkl-cu80_0.9.5
Segmentation fault. Error message from gdb:

Thread 90 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe9ebf4a00 (LWP 5866)]
0x00007fff7a953c29 in mkl_vsl_sub_kernel_l9_sBRngMCG31M1 ()
from /usr/local/lib/python2.7/dist-packages/mxnet/libmklml_intel.so

To reproduce, simply run fcn_xs example with mxnet package downloaded.

**Comment by SCP-173-cool** [comment]
No errors happen when I use the `openblas` mxnet, which is compiled by myself.

**Comment by yancz1989** [comment]
@SCP-173-cool Thanks, but how about with MKL? I need a new operator with SVD, which mkl is a must.

**Comment by SCP-173-cool** [comment]
@yancz1989 Maybe you should compile the MKL MXNet with your PC, because the error you claimed is about `libmklml_intel.so`.

**Comment by yancz1989** [comment]
@SCP-173-cool I compiled but failed... Errors are in #6386 ...

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
