### ISSUE TITLE
[im2rec] attributeErroe:'module' object has no attribute 'MXIndexedRecordIO'

### ISSUE THREAD

**Issue by Daliben** [apache/incubator-mxnet#6399]
Hi all,
I have used  im2rec.py to convert "caltech101 images" into record io format:
1) I have created "caltech.lst" succesfully using
os.system('python %s/tools/im2rec.py --list=1 --recursive=1 --shuffle=1  data/caltech data/101_ObjectCategories'%MXNET_HOME)
2) Then, when I run this : 
os.system("python %s/tools/im2rec.py --train-ratio=0.8 --test-ratio=0.2 --num-thread=4 --pass-through=1 data/caltech data/101_ObjectCategories"%MXNET_HOME)

I have this error : attributeErroe:'module' object has no attribute 'MXIndexedRecordIO'
Please, someone has an idea to fix this error ?
Thanks in advance.

## Environment info
Operating System:Windows 8.1
Package used (Python/R/Scala/Julia): Python
MXNet version:0.9.5
Python version and distribution:2.7

**Comment by Daliben** [comment]
any suggestions for solving this error please..

**Comment by Daliben** [comment]
@piiswrong  any suggestions for solving this error please

**Comment by eric-haibin-lin** [comment]
@Daliben did you try the im2rec binary? Does it work for your case? 
You can follow the tutorial here: http://mxnet.io/how_to/recordio.html?highlight=im2rec

**Comment by Daliben** [comment]
Hi,
No, it doesn't work for me :(

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
