### ISSUE TITLE
[New Function] Add Reset into kvstore, enable set_params() to reset weights in kvstore 

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#6421]
I think this is a good enhancement to set_params() when using kvstore.
for details, please see #6005.

@piiswrong @tqchen

**Comment by starimpact** [comment]
I have a new more general idea to solve the part of big weight update problem, that's using compress algorithm to compress the transfer data in the ```slicer_``` of worker's ```Send```.

**Comment by starimpact** [comment]
compression is not a good idea, but I just got a better idea to do partial weight update. It will change a lot code of kvstore related codes. 😄

**Comment by starimpact** [comment]
oh ...I have been finished the code in the ps-lite and kvstore. But there is some bugs. How can I debug easily a distributed system....
@mli @piiswrong

**Comment by starimpact** [comment]
haha, I fixed the bugs. Now my distribution training system (based on mxnet0.8.0) can support partial weight update now!
@mli @piiswrong

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
