### ISSUE TITLE
Does mxnet provide operator to 'rearange' data?

### ISSUE THREAD

**Issue by xhpohanka** [apache/incubator-mxnet#6423]
Hi,
I'm new to mxnet and I'm looking for operator/layer doing folloving manipulation with data:
* I have two tensors with shapes eg. `[1, 1, 8, 8]` and `[1, 1, 4, 4]`
* I want to concat these two along second axis (channels) so the first one has to be rearanged to get same width and height as second one
* I can take each four neigbouring *pixels* (with stride 2) and put them to four channels so I'll get new tensor with `[1, 4, 4, 4]`
Does mxnet provide similar function or I need to implement it by myself?

thanks
Jan

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
