### ISSUE TITLE
concat argument dim->axis

### ISSUE THREAD

**Issue by jmacglashan** [apache/incubator-mxnet#6425]
The concat operator takes the argument `dim` to specify along which axis to concat. How do you all feel about changing the argument name to `axis`? Almost every operator in mxnet uses the key-word name `axis` to specify this information and it's a little hard to remember that it's `dim` for concat.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
