### ISSUE TITLE
0.9.5 nnpack

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6426]
Does the 0.9.5 release has NNPACK installed by default? I tried to build MXNET without/with NNPCAK, but get similar performance as NNPACK installed (the faster one) reported http://mxnet.io/how_to/nnpack.html

**Comment by piiswrong** [comment]
we updated our default convolution and pooling ops recently. They are probably on par with nnpack now.

nnpack may still be faster on embedded devices

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
