### ISSUE TITLE
Can I use autograd for custom op written with python?

### ISSUE THREAD

**Issue by eldercrow** [apache/incubator-mxnet#6437]
I've just found that mxnet supports autograd functionality with ndarrays, but I cannot find any example related to it. Specifically, I want to use autograd for backward function of my custom op layer. Is there any how-to's for that?

**Comment by piiswrong** [comment]
Its intended for mxnet's imperative interface (like pytorch), which will be released soonish.
see https://github.com/dmlc/mxnet/pull/5705

**Comment by eldercrow** [comment]
Thank, I thought it'd be great if I could simply call autograd in backward function when I implement a python op.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
