### ISSUE TITLE
 fit() got an unexpected keyword argument 'monitor'

### ISSUE THREAD

**Issue by AnTruong** [apache/incubator-mxnet#6439]
Hello, please take a look and help me with this problem

## Environment info
Operating System: windows 10

Compiler: I use built package for VC12

Package used Python

MXNet version: tried with 0.9.3, 0.9.5, 0.10.0

Or if installed from source: https://github.com/yajiedesign/mxnet/releases

Python version and distribution: python version 2.7

## Error Message:
python train_mnist.py --network mlp

INFO:root:start with arguments Namespace(batch_size=64, disp_batches=100, gpus=None, kv_store='device', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs='10', model_prefix=None, mom=0.9, monitor=0, network='mlp', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_k=0, wd=0.0001)
Traceback (most recent call last):
  File "train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "D:\mxnet\example\image-classification\common\fit.py", line 187, in fit
    monitor            = monitor)
TypeError: fit() got an unexpected keyword argument 'monitor'

## Steps to reproduce
I run the example "image-classification" and I meet the error when run:
python train_mnist.py --network mlp

1. I have download 2 newest package from https://github.com/yajiedesign/mxnet/releases : *vc12 base package* and *20170525_mxnet_x64_vc14_cpu.7z*
2. Extract, setup pre-built package 
3. run the example from newest github  source code project: python train_mnist.py --network mlp

## What have you tried to solve it?

1. I have tried with 3 version: 0.9.3, 0.9.5, 0.10.0. Not yet for previous

Regards
Thanks

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
