### ISSUE TITLE
 mx.sym.SVMOutput breaks LR toy example

### ISSUE THREAD

**Issue by MartinTorres** [apache/incubator-mxnet#6448]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04.2 LTS

Installed with pip according to [http://mxnet.io/get_started/install.html](http://mxnet.io/get_started/install.html)

## Error Message:
Please paste the full error message, including stack trace.
`(64700, 300) (64700, 1)
([(1024, 300), (1, 300), (1,), (1024,)], [(1024, 1)], [])
infer_shape error. Arguments:
  target: (1024, 1)
  data: (1024, 300)
Traceback (most recent call last):
  File "svmexample.py", line 33, in <module>
    label_shapes= [mx.io.DataDesc(name='target', shape=(batch_size, 1), layout='NC')])
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/module/executor_group.py", line 205, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/module/executor_group.py", line 301, in bind_exec
    shared_group))
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/module/executor_group.py", line 548, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/symbol.py", line 747, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/symbol.py", line 871, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/martin/.local/lib/python3.5/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator svmoutput0: Shape inconsistent, Provided=(1024,1), inferred shape=(1024,)`

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
import mxnet as mx
import mxnet.ndarray as nd
import numpy as np
import logging
import sys
import os

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)  # Config the logging
np.random.seed(777)

xy = np.loadtxt(os.path.join('w8a.csv'), delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape, y_data.shape)

sample_num = x_data.shape[0]
dimension = x_data.shape[1]
batch_size = 1024

data = mx.sym.Variable("data")
target = mx.sym.Variable("target")
fc = mx.sym.FullyConnected(data=data, num_hidden=1, name='fc')
pred = mx.sym.SVMOutput(data=fc, label=target)
print(pred.infer_shape(data=(batch_size, dimension)))

net = mx.mod.Module(symbol=pred, data_names=['data'], label_names=['target'], context=mx.cpu(0))
net.bind(data_shapes = [mx.io.DataDesc(name='data', shape=(batch_size, dimension), layout='NC')],
         label_shapes= [mx.io.DataDesc(name='target', shape=(batch_size, 1), layout='NC')])
net.init_params(initializer=mx.init.Normal(sigma=0.01))
net.init_optimizer(optimizer='sgd', optimizer_params={'learning_rate': 1E-2, 'momentum': 0.9})

train_iter = mx.io.NDArrayIter(x_data, y_data, batch_size, shuffle=False, label_name='target')
feval=lambda labels, pred : ((pred > 0.5) == labels).mean()
metric = mx.metric.CustomMetric(feval=feval, name="acc")
net.fit(train_data=train_iter, eval_metric=metric, num_epoch=1000)

Hello, 

I was able to successfully run the code above using LogisticRegressionOutput, however when I change the output to SVMOutput using the same configuration I get the Inconsistent shape error shown above. Printing the inferred shape is the same in both cases of SVM and LR, however SVM complains and throws an error. I believe the error is thrown by Symbol.py after calling svm_output-inl.h. I compared the implementations between SVM and LR, and it looks like the SVM implementation has an extra check that throws the error. Here is the code for LR: (starts at line 48 in regression_output-inl.g) 
`CHECK_EQ(in_data.size(), 2U) << "RegressionOutputOp Input: [data, label]";
    CHECK_EQ(out_data.size(), 1U) << "RegressionOutputOp Output: [output]";
    Stream<xpu> *s = ctx.get_stream<xpu>();
    Tensor<xpu, 2> data = in_data[reg_enum::kData].FlatTo2D<xpu, real_t>(s);
    Tensor<xpu, 2> out = out_data[reg_enum::kOut].FlatTo2D<xpu, real_t>(s);
    Assign(out, req[reg_enum::kOut], F<ForwardOp>(data));`

While the SVM implementation looks like this: 
`CHECK_EQ(in_data.size(), 2U) << "Expecting [data, label]";
    CHECK_EQ(out_data.size(), 1U) << "Expecting [output]";
    CHECK_EQ(req.size(), 1U) << "Expecting output.size() == req.size()";
    Stream<xpu> *s = ctx.get_stream<xpu>();
    Tensor<xpu, 2, DType> data = in_data[svm_enum::kData].FlatTo2D<xpu, DType>(s);
    Tensor<xpu, 2, DType> out = out_data[svm_enum::kOut].FlatTo2D<xpu, DType>(s);
    Assign(out, req[svm_enum::kOut], F<mshadow_op::identity>(data));`

My question is, why does the SVMOutput and LogisticRegressionOutput differ in the inferred shape and is there a solution to run this example using SVMOutput?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
