### ISSUE TITLE
distributed training on multiple machines speed is slowing down instead of an expected increase

### ISSUE THREAD

**Issue by encodingwaddles** [apache/incubator-mxnet#6450]
Hi all,

I am trying to run distributed training on multiple machines (data parallelism) with mxnet using the VOC dataset. I have been successful in doing this on AWS machines (g2.2x large) whether it has been 1, 2 or 5 machines (given all the hyperparameters are kept the same e.g. batch size on each gpu) . 

| Instance Type / GPU Card | Num of GPU| Speed (samples/sec) |
| ------------- | ------------- | ------------- |
| g2.2x large / k520 | 1  | ~9-10   |
| g2.2x large / k520  |2  | ~9-10  |
| g2.2x large / k520  |5  | ~9-10  |

The speed (samples/sec) stays relatively the same regardless of the number of machines I have, which means that the training time will subsequently be reduced as I increase the number of GPU (b/c the batch will decrease). This is ideal because that is in accordance with mxnet documentation. 

However, when I do this on my own local network, I unfortunately am getting a decrease in speed when I add on more machines (given all the hyperparameters are kept the same - e.g. batch-size on each gpu, kv-store = dist-sync ). The decrease in speed is pretty significant - almost 5x slower on 2 machines than if I just used 1 machine!

| Instance Type / GPU Card | Num of GPU| Speed (samples/sec) |
| ------------- | ------------- | ------------- |
| local / gtx 1080 | 1  | ~40-50   |
| local / gtx 1080  |2  | ~8-10  |

From this speed decrease, it means the training time will take longer as compared to when I was training with only 1 machine which is less than ideal. **Do you know why this might be the case?** 

## What have you tried to solve it?

I thought it might be a bandwidth issue and used [iperf](https://www.linode.com/docs/networking/diagnostics/diagnosing-network-speed-with-iperf) to test the connection speed but that seems to be comparable between my local machines and aws instances.

| | Interval | Transfer | Bandwidth |
| ------------- | ------------- | ------------- | ------------ |
| local gtx 1080 & local gtx 1080 | 0.0-10s  | 1012 MBytes  | 848 MBits/sec  |
| g2.2x large k520 &  g2.2x large k520 | 0.0-10s  | 867 MBytes  | 727 MBits/sec  |

If anyone could advise me on this , I would greatly appreciate it! Thank you so much ! 

----------------------------------------------------------
## Environment info
Operating System: Ubuntu 14.04 + Ubuntu 16.04 

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.9.5 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 703e8eeb117109ea345639610780e30775056412

If you are using python package, please provide

Python version and distribution: Python 2.7.8

**Comment by piiswrong** [comment]
which model are you training?

**Comment by encodingwaddles** [comment]
@piiswrong I am training with ssd model -  [commit](https://github.com/zhreshold/mxnet-ssd/commit/67ba1c9a8cb0508b018e958fd540f1e99423d0e3)

**Comment by piiswrong** [comment]
multi gpu/machine ssd training doesn't scale very well

**Comment by cainiao2hao** [comment]
I've met the same problem when training ssd. Training speed on two machines is much slower than on one machine. Is this caused by the Custom operator or something else?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
