### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by JACKHAHA363** [apache/incubator-mxnet#6458]
I am building MxNet from source. And it shows me this error

/usr/bin/ld: cannot find -ljvm
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -ljvm
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

**Comment by stone-huang** [comment]
me too

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
