### ISSUE TITLE
a bug in 'tools/im2rec.py' while argument 'pass-through' is turned on

### ISSUE THREAD

**Issue by wenxuanxie** [apache/incubator-mxnet#6460]
I have found a bug in 'tools/im2rec.py' while argument 'pass-through' is turned on.

See Line 105 of 'tools/im2rec.py':

`with open(fullpath) as fin:`

'fullpath' represents the path of an image, which is a binary file. Reading it with the default mode might result in a truncated string.

The workaround is to open the image file with binary mode:

`with open(fullpath, 'rb') as fin:`

And then reinstall mxnet:

> cd python
> python setup.py install

Thank you for reading, and wish you not to be stuck by this issue.

**Comment by piiswrong** [comment]
would you like to submit a fix?

**Comment by wenxuanxie** [comment]
@piiswrong Pull request submitted. Thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
