### ISSUE TITLE
[mxnet] . no get_mnist() in test_utils

### ISSUE THREAD

**Issue by huangguanMayday** [apache/incubator-mxnet#6461]
import mxnet as mx
mnist = mx.test_utils.get_mnist()

AttributeError: 'module' object has no attribute 'get_mnist'

**Comment by pracheer** [comment]
Hi @huangguanMayday 
This has been fixed by this [this](https://github.com/dmlc/mxnet/pull/6389) and [this](https://github.com/dmlc/mxnet/pull/6436). Let us know if this still doesn't work.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
