### ISSUE TITLE
where to find the synset of the published model

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6464]
@jychoi84 
Could  you please point where to find the synsets of the published model LocationNet on
http://mxnet.io/model_zoo/

Thanks!

**Comment by jychoi84** [comment]
@patricianing By 'synsets', do you mean the mapping from geo-coordinate (latitude, longitude) to geographical cell?  
For instance, the mapping such as (lat:37.12, lon:122.23) --> (cell#12)?

**Comment by patricianing** [comment]
@jychoi84 I mean the labels of the model. The model predicts a location of an image, I would like t find all labels of the locations. Thanks!

**Comment by jychoi84** [comment]
@patricianing 
Oh right. We should've linked this tutorial that includes how to use the labels of the model (grids.txt). 
https://github.com/multimedia-berkeley/tutorials/blob/master/predict_geolocation.ipynb

**Comment by luoyetx** [comment]
@patricianing  http://data.dmlc.ml/models/imagenet/synset.txt

**Comment by jychoi84** [comment]
@luoyetx LocationNet model is not trained with ImageNet :) 
I added the link to the label file in my response above.

**Comment by patricianing** [comment]
@jychoi84 Thanks a lot! So it is a different model from PlaNet? Do you know how to map the result vector (the probability of falling into each S2 cell) to the text info like city/country name of the corresponding location?

**Comment by jychoi84** [comment]
@patricianing 
LocationNet is inspired by PlaNet but it's trained on different dataset, architecture, hyperparams. 
The comparison of these two can be found [here](https://github.com/multimedia-berkeley/tutorials).

Examples in this [tutorial](https://github.com/multimedia-berkeley/tutorials/blob/master/predict_geolocation.ipynb) will give you coordinate geo-tag (latitude, longitude). If you want to get a plaintext place name from this coordinate geo-tag, you can use one of the reverse geocoding services online such as [Google's MAP API](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse) or [this one on github](https://github.com/thampiman/reverse-geocoder).

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
