### ISSUE TITLE
Unsynchronized access to comm_buf_?

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#6467]
https://github.com/dmlc/mxnet/blob/02671ebee036c62eefd09ce0dea0c46213f0bf67/src/kvstore/kvstore_dist.h#L99
https://github.com/dmlc/mxnet/blob/02671ebee036c62eefd09ce0dea0c46213f0bf67/src/kvstore/kvstore_dist.h#L206

Looks like in these two places the access to comm_buf_ is unsynchronized? This can happen if push or pull is called twice with different keys if they are not present?

Is this a problem or it never happens?

**Comment by Luo-Liang** [comment]
or maybe calling push and pull is run by a single thread

**Comment by tqchen** [comment]
comm_buf is NDArray, which means all the operations on top of them are scheduled, as opposed to executed immediately, if pull or pull called twice with different keys, they will be serialized properly

**Comment by Luo-Liang** [comment]
but comm_buf is unordered_map, before accessing the ndarray, accessing unordered_map (potentially adding a key) without synchronization is a race. The engine only kicks in after the comm_buf_ is accessed.

This is only safe is the pull() and push() methods themselves are called serially. Is that true?


comm_buf_ = {}
T1:                            T2:
push(0)                 push(1)
//race

comm_buf_ = {0:ndarray1,1:ndarray2}
T1:                            T2:
push(0)                 push(1)
//race

comm_buf_ = {0:ndarray1,1, 1:ndarray2}
T1:                            T2:
push(0)                 push(0)
//standard says race, but most likely safe

So unless MXNET guarantees push and pull themselves are serialized, it seems to me it's unsafe.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
