### ISSUE TITLE
Error in .infer_shape for deconvolution when the input is 5D batch-num_filter-z-y-x

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#6475]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Mac

Compiler:

Package used (Python/R/Scala/Julia): python

MXNet version:0.10

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: Python 2.7.10

## Error Message:
[(1L, 1L, 64L, 64L, 64L)]
infer_shape error. Arguments:
  data: (1, 1, 64, 64, 64)

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-16-bb4f7eff4e4d> in <module>()
      7 net = mx.sym.Deconvolution(source, kernel=(3, 3,3), pad=(0, 0,0), stride=(2,2, 2), num_filter=32,ctx=mx.gpu(0))
      8 
----> 9 net.infer_shape(data=(1, 1,64,64,64))

/Users/mas/PycharmProjects/NCF/mxnet/python/mxnet/symbol.pyc in infer_shape(self, *args, **kwargs)
    457         """
    458         try:
--> 459             return self._infer_shape_impl(False, *args, **kwargs)
    460         except MXNetError:
    461             print("infer_shape error. Arguments:")

/Users/mas/PycharmProjects/NCF/mxnet/python/mxnet/symbol.pyc in _infer_shape_impl(self, partial, *args, **kwargs)
    524             ctypes.byref(aux_shape_ndim),
    525             ctypes.byref(aux_shape_data),
--> 526             ctypes.byref(complete)))
    527         if complete.value != 0:
    528             arg_shapes = [

/Users/mas/PycharmProjects/NCF/mxnet/python/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: InferShape Error in deconvolution2: [11:11:00] src/operator/./deconvolution-inl.h:357: Check failed: (dshape.ndim()) == (4) Input data should be 4D in batch-num_filter-y-x

## Minimum reproducible example
import mxnet as mx

source = mx.sym.Variable("data")
a,b,c=source.infer_shape(data=(1, 1,64, 64, 64))
print(b)

net = mx.sym.Deconvolution(source, kernel=(3, 3,3), pad=(0, 0,0), stride=(2,2, 2), num_filter=32,ctx=mx.gpu(0))

net.infer_shape(data=(1, 1,64,64,64))

## What have you tried to solve it?

1. Upgraded mxnet to latest release
2.
3.

**Comment by great-thoughts** [comment]
3D conv is supported for cudnn. If I set context to gpu will the cudnn version of the function be used?

**Comment by great-thoughts** [comment]
Now I am running the code on Deep Learning AMI Ubuntu Version. How can I enable cudann?

**Comment by rongrongxiangxin** [comment]
@great-thoughts have you solved the problem? I got the same one.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
