### ISSUE TITLE
Why APIs are different between mxnet.module.BaseModule.fit and mxnet.model.FeedForward.fit?

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#6484]
Why APIs are different between `mxnet.module.BaseModule.fit` and `mxnet.model.FeedForward.fit`?

I'm confused about these similar `fit`. Besides, I found many a different input parameters, such as 
`mxnet.model.FeedForward.fit` supports `work_load_list` but `mxnet.module.BaseModule.fit` doesn't.

I'm recently finetuning a pretrained model according to official guide. However, guide uses `mxnet.module.BaseModule.fit` to make fit, but it doesn't support different power GPUs. Because I want to use `work_load_list` parameter according to officail [Run MXNet on Multiple CPU/GPUs with Data Parallelism — mxnet documentation](http://mxnet.io/how_to/multi_devices.html#advanced-usage) guide, can anyone help me? Thanks a lot!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
