### ISSUE TITLE
some doubt of simple_bind

### ISSUE THREAD

**Issue by alues** [apache/incubator-mxnet#6485]
**

    Model_Net_Load, arg_params, aux_params = mx.model.load_checkpoint(prefix="Model_Saved", epoch=1)
    Model_Net = Config.Get_OCR_Net()
    data_shape = [("data", (Model_Batch_Size, 3, 50, 130))]
    input_shapes = dict(data_shape)
    executor_Load = Model_Net_Load.simple_bind(ctx=mx.gpu(), **input_shapes)
    executor = Model_Net.simple_bind(ctx=mx.gpu(), **input_shapes)
**

what's the diff between  'Model_Net_Load'  and 'Model_Net ' on method simple_bind
@piiswrong

**Comment by alues** [comment]
@piiswrong  plz

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
