### ISSUE TITLE
amalgamation fails to build

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6492]
In mxnet-0.10.0, under amalgamation, when type make, I see the following error:

mxnet_predict-all.cc:35701:19: error: cannot convert ‘const dim_t* {aka const long int*}’ to ‘__gnu_cxx::__alloc_traits<std::allocator<const unsigned int*> >::value_type {aka const unsigned int*}’ in assignment
       data->at(i) = shapes[i].data();
                   ^

mxnet_predict-all.cc:51537:15: error: cannot convert ‘nnvm::dim_t* {aka long int*}’ to ‘mx_uint* {aka unsigned int*}’ in assignment
   *shape_data = p->out_shapes[out_index].data();

mxnet_predict-all.cc:51631:14: error: cannot convert ‘nnvm::dim_t* {aka long int*}’ to ‘const mx_uint* {aka const unsigned int*}’ in assignment
   *out_shape = p->shapes[index].data();

**Comment by piiswrong** [comment]
@ZihengJiang

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
