### ISSUE TITLE
prediction size not matching

### ISSUE THREAD

**Issue by data-compute-geek** [apache/incubator-mxnet#6495]
## Environment info
Operating System: Deep Learning AMI for Amazon Linux
Package used (Python):
MXNet version: 0.9.5

I running the rnn example, mxnet/example/rnn/lstm_bucketing.py. After the model training, I use the following command to make predictions on the validation data.

>>> predicts=model.predict(data_val)
>>> predicts
<NDArray 95040x10000 @cpu(0)>

The size of the prediction, 95040, does not seem to match the data_val which is 98940

>>> sum([data_val.data[c].size for c in range(6)])
98940

What did I do wrong or did I miss something?

Thanks.

**Comment by piiswrong** [comment]
It got rounded to evenly divide batch_size.
predicts[:98940] would give you the real predictions

**Comment by data-compute-geek** [comment]
The dimension of predicts is 95040 which is smaller than 98940. Statement predicts[:98940] would give an index out of range error.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
