### ISSUE TITLE
how to use huffman tree softmax in mxnet

### ISSUE THREAD

**Issue by superclocks** [apache/incubator-mxnet#6497]
hi @phunterlau i want to use huffman softmax in mxnet to speed up lstm training, just like huffman softmax used in word2vec(ref:http://www.trevorsimonton.com/blog/2016/12/15/huffman-tree-in-word2vec.html#effword, http://www.cnblogs.com/peghoty/p/3857839.html). But i don not know how to  build network graphs,  because i think huffman softmax network graph should have ability to  train sparse data. could you give me some suggestion?

**Comment by superclocks** [comment]
hi @xlvector i have read your nce-loss in mxnet(https://github.com/xlvector/learning-dl/tree/master/mxnet/nce-loss), do you konw how to add huffman softmax into mxnet, pls give me some suggestion.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
