### ISSUE TITLE
L2Normalization errors when use channel Mode

### ISSUE THREAD

**Issue by maxenceliu** [apache/incubator-mxnet#6505]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
OSX 10.12
Compiler:
gcc
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.5
Or if installed from source:
yes
MXNet commit hash (`git rev-parse HEAD`):
f8840029ea10fae37f5cdf6c8cc8802d0faa02cc
If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.in the api document,  **## l2Normalization**
2.the following calculation is not correct, please check it out. I also tried it in a 4D matrix, it is also not correct
x = [[[1,2],
      [3,4]],
     [[2,2],
      [5,6]]]

L2Normalization(x, mode='channel')
=[[[ 0.31622776  0.44721359]
   [ 0.94868326  0.89442718]]
  [[ 0.37139067  0.31622776]
   [ 0.92847669  0.94868326]]]
3.

## What have you tried to solve it?

1. None, I think these is some errors when calculate
2.
3.

**Comment by maxenceliu** [comment]
you can simply compare the result from following two expression:
a=np.arange(48).reshape(1,3,4,4)
ret1 = mx.nd.L2Normalization(mx.nd.array(a),mode="channel").asnumpy()
ret2 = a[:,0,:,:]/np.sqrt(np.sum(a[:,0,:,:]**2))

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
