### ISSUE TITLE
Help, how to convert params files

### ISSUE THREAD

**Issue by vosey** [apache/incubator-mxnet#6507]
I trained a model with mxnet v0.7, now I want to upgrade mxnet to v0.10. How can I use the old *.params and sysbol.json files in the new version?  Is there a way to convert them ? Or I must train it again using the new version of mxnet?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
