### ISSUE TITLE
Benchmarking module in MXNet

### ISSUE THREAD

**Issue by EvanzzzZ** [apache/incubator-mxnet#6512]
Thinking if it make sense to have a benchmarking module in mxnet.

Even though there are many examples in the repo that can be used for benchmarking, it will be more convenient to have a module in mxnet that packaging all the common applications together. Most of the popular applications have dominant datasets for benchmarking. All the user need to do is giving his designed model or symbol and setup the configurations, the interface handle the dataset retrieving, data iterators and potentially generate meaningful benchmarking metrics when comparing to the baseline.

The convenience of quickly prototyping and benchmarking their models might attract more users to the community.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
