### ISSUE TITLE
Support 'kAddTo' for SwapAxis Op

### ISSUE THREAD

**Issue by feiyulv** [apache/incubator-mxnet#6526]
I'm currently working on implmenting  facebook fairseq on mxnet, and find SwapAxis doesn't support kAddTo which is needed when accumlating encoder gradient for each attention layer.  Is that easy to add kAddTo for  SwapAxis?  And  is there any other op that doesn't support kAddTo?  By the way, it is very easy to fall in this trap and diffcult to debug.
@eric-haibin-lin @piiswrong

**Comment by piiswrong** [comment]
Should be easy to do. Are you talking about forward or backward?

**Comment by feiyulv** [comment]
Backward

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by khaotik** [comment]
Hi, I'm looking for simple issues for my first PR. Upon reviewing C++ code, it seems this issue is already resolved, or am I missing anything?

I also made a small test case:

```python
#!/usr/bin/env python
from itertools import product
import numpy as np
import mxnet as mx

CTX_LIST = [mx.gpu(), mx.cpu()]
DTYPE_LIST = ['float16', 'float32', 'float64']
for CTX, DTYPE in product(CTX_LIST, DTYPE_LIST):
    with mx.autograd.record():
        v_x = mx.nd.random.uniform(
           -1., 1., shape=(4,5,6), 
           dtype=DTYPE, ctx=CTX)
        v_x.attach_grad(grad_req='add')
        v_x.grad[:] = 0.
        v_y = mx.nd.swapaxes(v_x, 1, 2)
        v_err = mx.nd.square(v_y)
        v_err.backward(retain_graph=True)
        v_y = mx.nd.swapaxes(v_x, 0, 1)
        v_err = mx.nd.square(v_y)
        v_err.backward(retain_graph=True)
        v_y = mx.nd.swapaxes(v_x, 0, 2)
        v_err = mx.nd.square(v_y)
        v_err.backward(retain_graph=True)
    assert(np.allclose(v_x.asnumpy()*6, v_x.grad.asnumpy()))
```

**Comment by szha** [comment]
@khaotik indeed. Thanks for updating the issue.
