### ISSUE TITLE
Why Overrided Function backward of CustomOp Not be Called

### ISSUE THREAD

**Issue by DarkerDreamer** [apache/incubator-mxnet#6527]
I subclassed **mxnet.operator.CustomOp** and **mxnet.operator.CustomOpProp** following the way described in http://mxnet.io/how_to/new_op.html. All overloaded function worked well except the **backward** function had never been called in the execution of **Module.fit**. And there was no warning or error logged. Why and how to fix it? Have I missed something else to be set or configured?

Compared to other networks with subclass of **CustomOp** that **backward** function works well, I used symbols **slice_axis** and **concat** in this network, dose it matter?

I worked on windows 7,  the mxnet 0.9.5 is compiled with vs2013 and installed in python 2.7.

**Comment by piiswrong** [comment]
This depends on your network definition. If no gradient is needed along a path backward will not be called for that path

**Comment by eldercrow** [comment]
I wonder if you set need_top_grad=True in your custom op prop.

**Comment by DarkerDreamer** [comment]
@eldercrow need_top_grad has been set to False.

I checked the backward **Node**s generated, it seems that the problem arises because of an out-of-date understand about how loss layers work. In the code I tried to run, the **SoftmaxOutput** accepts gradient from its top layer, but the **LinearRegressionOutput** dose not. I guess the reason maybe that the argument **out_grad** has been removed from **LinearRegressionOutput**(**grad_scale** seems not be dynamically and example-wise changed?) and still works in **SoftmaxOutput**(when **out_grad**=True) in mxnet 0.9.5.

**Comment by DarkerDreamer** [comment]
@piiswrong @eldercrow  
Is there any tutorials or specifications explaining how to declare forward & backward dependency with Python API?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
