### ISSUE TITLE
[question] language binding interface

### ISSUE THREAD

**Issue by dzhwinter** [apache/incubator-mxnet#6528]
theres are some questions about the mxnet, if it is not right way to ask by a issue, please let me know.
I have three question about the language binding interface in mxnet. 
-  is there any go interface in current state?  after i googled, i only find the gomxnet repo, which seems has been deprecated for a long time.
- what is the relationship between NNVM interface and framework language binding interface? 
- python language binding, support in ctypes and cython? is there any compartion between these two method? 

Thanks.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
