### ISSUE TITLE
VGG structure is wrong? 

### ISSUE THREAD

**Issue by darrylbobo** [apache/incubator-mxnet#6535]
I think the provided VGG structure as in (mxnet/example/image-classification/symbols/VGG.py) is not the original VGG16? 

It is not corresponding the provided pre-trained VGG16 model as in http://data.dmlc.ml/mxnet/models/imagenet/vgg/.

For example, in the first conv group, there are two conv layers, but in VGG.py, there is only one. 

So, in this case, if we load the pre-trained VGG16, we are just loading part of the whole structures.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
