### ISSUE TITLE
R Documentation hyperlinks at http://mxnet.io/api/r/index.html all lead to something other than R 

### ISSUE THREAD

**Issue by paulsendavidjay** [apache/incubator-mxnet#6536]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by thirdwing** [comment]
@paulsendavidjay Really sorry for this. We are rewriting all the documents and will fix this soon.

**Comment by TroyHernandez** [comment]
Now they lead to Julia.  Progress!

**Comment by paulsendavidjay** [comment]
Thumbs up!

**Comment by thirdwing** [comment]
You can the R tutorials from https://github.com/apache/incubator-mxnet/tree/master/R-package/vignettes

**Comment by topepo** [comment]
Can you make a priority to update the installation documents? Many still reference `https://github.com/dmlc/mxnet` and give incorrect directions (i.e. the `make` targets don't exist, the amazon CRAN mirror doesn't work, etc.).

**Comment by thirdwing** [comment]
@topepo Can you give more details about the error? Especially the `make` error.
