### ISSUE TITLE
How to make step-by-step predictions using RNN with bucketing 

### ISSUE THREAD

**Issue by Cloudyrie** [apache/incubator-mxnet#6556]
By ‘step-by-step predictions’ I mean using values sampled from current time step's output as input in the next time step. For example, to generate a sentence using the lstm model in example/rnn/lstm_bucketing.py, I need to start from a particular word, feed it to the network and get outputs, then sample a word from the outputs and fix it as the input in the next time step.    

Now in every time step I need to construct a data batch and pad the sequence to a legal length(one of the buckets' length) because forward() can only accept DataBatch.  Are there any existing interfaces (I found a LSTMInferenceModel in tutorial but it seems to be deprecated.) or methods to make it a more elegant process?

Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
