### ISSUE TITLE
MXIndexedRecordIO

### ISSUE THREAD

**Issue by Daliben** [apache/incubator-mxnet#6562]
#Hi,
The class called "MXIndexedRecordIO" is not recognized in the  recordio module !!
When i run the code below:

record = mx.recordio.MXIndexedRecordIO('tmp.idx', 'tmp.rec', 'w')
for i in range(5):
    record.write_idx(i, 'record_%d'%i)
record.close()

i had this error: AttributeError: 'module' object has no attribute 'MXIndexedRecordIO'

OS:Windows
Python 2.7
Mxnet 0.9.5

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
