### ISSUE TITLE
Q: Checkpointing and how much to train?

### ISSUE THREAD

**Issue by offerm** [apache/incubator-mxnet#6566]
Thanks for your help and the great work you are doing here.

Im training my first LSTM model from R environment using the shakespeare file. 
Very easy to see that with time the model improves and generates better sequences.   Still I'm not sure:
1. How much time should I give it for training? 
2. If I stop it after N hours/days/weeks is there a way to check the model and continue the training from the point it stopped? 
3. Any kind of checkpointing? 

Im using the mx.lstm() function.

Thanks for assisting,

Offer

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
