### ISSUE TITLE
GPU stream error when running with gpu context

### ISSUE THREAD

**Issue by EvanzzzZ** [apache/incubator-mxnet#6572]
Trying to add a new operator in C++.
The code compiled and run as expected with cpu context, 
but when I ran it with gpu context, it throw the following error,
`Default GPU stream was used when MSHADOW_FORCE_STREAM was on`.

My guess is I used `NewTensor` in the forward/backward operation in a way not as expected.
Any clue here ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
