### ISSUE TITLE
251MB memory in gpu 0 even when context is not mx.gpu(0)

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#6575]
I just found that passing kvstore = mx.kvstore.create('local') into mx.mod.Module.fit would produce 251MB memory in gpu 0 even when context is not mx.gpu(0). Is it a bug?
```
ctx = [mx.gpu(1), mx.gpu(2)]
mod = mx.mod.Module(symbol=xxx, context=ctx)
...
mod.fit(kvstore=mx.kvstore.create('local'), ...)
```
Changing kvstore to None solves the problem but I am not sure if it is a proper solution.

-------
BTW, the code below also produce 251M memory in gpu 0
```
import mxnet as mx
kv = mx.kvstore.create('local')
kv.init(3, mx.nd.ones((5, 5)))
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
