### ISSUE TITLE
weight norm  implemention

### ISSUE THREAD

**Issue by feiyulv** [apache/incubator-mxnet#6576]
Does anyone implement weight normalizaiton using mxnet. I use  python symbol to implement it like follows:
```
def weight_norm(num_filter, num_channel, kernel, name):
       shape = (num_filter, num_channel, kernel[0], kernel[1])
       g = mx.sym.Variable(shape=shape, name='%sg_weight'%name)
       v = mx.sym.Variable(shape=(num_filter, ), name='%sv_bias'%name)
       s = v / mx.sym.L2Normalization(data=g)
       w = mx.sym.broadcast_mul(g, mx.sym.Reshape(data=s, shape=(num_filter, 1, 1, 1)))
       return w
```
But I'm not sure whether it can work. Any suggestion will be appreciated

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
