### ISSUE TITLE
Visualization Error due to usage of split method

### ISSUE THREAD

**Issue by angelsrates** [apache/incubator-mxnet#6594]
## Environment info
Operating System: MacOs

Compiler:

Package used (Python/R/Scala/Julia): Python (Jupyter Notebook)

MXNet version: 0.9.5
[vsLSTM_visBug.ipynb.zip](https://github.com/dmlc/mxnet/files/1056080/vsLSTM_visBug.ipynb.zip)

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: Python 2.7.13

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
KeyError: u'split9_output-1'

##
Hi there,

I have been lately playing with bi-directional LSTMs and came across with an issue when visualizing the model in mxnet.
The visualization of the forward hidden states works, whereas that when both the backward and forward hidden states are returned as a group, mx.viz.plot_network returns an error. It looks like the error is given by the usage of the split method.
It seems that there is no problem with the model implementation, since the outputs are returned correctly, and so it might be due to the visualization method itself.
Could you please help me on that? I am attaching a demo of the code showing where the problem is (vsLSTM_vizBug.ipynb.zip).
Thank you very much!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
