### ISSUE TITLE
MKL Breaking Existing Functionality

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#6615]
Building against MKL-DNN breaks certain existing functionality. For example: the Activation symbol with "relu" crashes during a forward pass whenever the rank of the input is not 4. 

Are there any other areas where linking against MKL-DNN breaks existing functionality? And is this expected behaviour, or is this a bug?

@piiswrong, @glingyan, @taliesinb

**Comment by glingyan** [comment]
Hi  Sebastian:
   Young Jin will support.
   What MKL-DNN, which library and what kind of case?

**Comment by ykim362** [comment]
Hi @sbodenstein ,

Are you trying to use this?
https://github.com/01org/mkl-dnn
If so, it is under active development and will be available some time later.

If not, could you please let me know the problem more details?

Thanks.

**Comment by sergeykolychev** [comment]
@sbodenstein when I try to use padding for convolution if mxnet is linked against mkl it crashes. just one more example of some buggy mkl related area.

**Comment by ykim362** [comment]
@sbodenstein Could you provide some more details? Are you referring to the dimension of the tensor? If so, in what dimension does that crash?

**Comment by sbodenstein** [comment]
@ykim362: 

```
a = mx.sym.Activation(act_type="relu", data = mx.sym.Variable('a'))
e = a.bind(mx.cpu(), {'a': mx.nd.array([1,2])})
y = e.forward()
```
produces:
```
[18:26:50] /mxnet/dmlc-core/include/dmlc/logging.h:304: [18:26:50] /mxnet/nnvm/include/nnvm/tuple.h:446: Check failed: dim == static_cast<int>(ndim()) (4 vs. 1) dimension do not match target dimension 4 vs 1

**Comment by sbodenstein** [comment]
@sergeykolychev: could you give an explicit example that fails for you?

**Comment by ykim362** [comment]
Thanks, @sbodenstein !

I will investigate the case.

**Comment by ykim362** [comment]
@sbodenstein ,
Currently, MKL relu is only enabled for 2D, 3D and 4D tensors.
Even though 1D tensor can be supported by MKL, it hasn't been enabled, yet. Above example is 1D tensor case.

I will fix two and make a pull request.
(1) Correctly support 1D tensor.
(2) In the case of non-supported dimensions (higher than 4D), make use of the default 3rd party library.

I will also look into the way how to support higher than 4-d tensors.

I am sorry for the inconvenience.
Thanks.

**Comment by ykim362** [comment]
(1) is merged. (2) will be integrated when we are switching to MKL-DNN.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
