### ISSUE TITLE
How do you load a params file for mxnet?

### ISSUE THREAD

**Issue by shyamalschandra** [apache/incubator-mxnet#6624]
## Environment info
Operating System: MacOS Sierra

Compiler: n/a

Package used (Python/R/Scala/Julia): python

MXNet version: latest stable version

How do you load a params file in MXnet?

**Comment by ysh329** [comment]
It's an easy question, which docs clarifies clearly.
```Python
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-50', 0)
```

ref:Fine-tune with Pretrained Models — mxnet documentation
http://mxnet.io/how_to/finetune.html

**Comment by shyamalschandra** [comment]
@ysh329  I just tried that and it doesn't work with .param files.  Instead, it is looking for a json file.  Any ideas?

**Comment by papercatnku** [comment]
@shyamalschandra 
try mx.nd.load() you'll get a dictionary, which key is param name, value is corresponding param array.

**Comment by ysh329** [comment]
@shyamalschandra Can u give the code you wrote?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
