### ISSUE TITLE
incompatibility between backward mirror and batch normalization

### ISSUE THREAD

**Issue by winstywang** [apache/incubator-mxnet#6644]
Currently the MXNET_BACKWARD_DO_MIRROR=1 cannot work with batch norm layer followed by ReLU activation. Error message:  src/operator/./cudnn_batch_norm-inl.h:62: Check failed: req[cudnnbatchnorm::kOut] == kWriteTo (0 vs. 1)

It is closely related to this issue: https://github.com/dmlc/mxnet/issues/4187 It should be fixed after NNVM is merged in, however it still does not work so far...

@piiswrong @tqchen

**Comment by cjolivier01** [comment]
https://issues.apache.org/jira/browse/MXNET-207

**Comment by cjolivier01** [comment]
no longer an issue

**Comment by HaoLiuHust** [comment]
the issue still exists

**Comment by kaleidoscopical** [comment]
the issue still exists

**Comment by leiyu1980** [comment]
这个问题依然存在。请问可以安排修复吗？

**Comment by cqlyiyeshu** [comment]
the issue still exists

@cjolivier01
