### ISSUE TITLE
How to concat mxnet::cpp::NDArray?

### ISSUE THREAD

**Issue by rococopeach** [apache/incubator-mxnet#6645]
What is the best way to concat mxnet::cpp::NDArray?
I have a std::vector<mxnet::cpp::NDArray> and context is gpu. 
How can I merge them and get new NDArray?

**Comment by lx75249** [comment]
Concat() in op.h

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
