### ISSUE TITLE
[New Function]Let kvstore and kvstore_dist support partial weight update.

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#6646]
I have finished the code which is based on mxnet_0.8.0. My new distribution training system can do partial weight update now!
see #6421 
see the repository: https://github.com/starimpact/mxnet_v0.8.0/tree/bProxy_Weight

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
