### ISSUE TITLE
How dose mxnet.symbol.Custom add arguments?

### ISSUE THREAD

**Issue by DarkerDreamer** [apache/incubator-mxnet#6653]
How dose mxnet.symbol.Custom add arguments that can be manipulated and saved/loaded to param file in the same way as  weight/bias for mxnet.symbol.Convolution and gamma for mxnet.symbol.LeakyReLu?

**Comment by piiswrong** [comment]
in list arguments()

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by kaleidoscopical** [comment]
@piiswrong I would like to know how to set attributes of the arguments. For example, in LeakyReLU I would like to set 'wd_mult = 0'
