### ISSUE TITLE
Is it possible that use python to write a custom convolutional layer?

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#6656]
I want to write a custom convolutional layer. I've checked the example of softmax. But softmax doesn't contain any parameters. Anyone know how to do it?

**Comment by Ldpe2G** [comment]
@akturtle you can refer to https://github.com/pangyupo/mxnet_center_loss/blob/master/center_loss.py

**Comment by akturtle** [comment]
@Ldpe2G Thanks,  but this example uses its own updating rule.  I want to know how to assign the gradient of parameters.  Then we can use the optimizer of mxnet to update it.

**Comment by Ldpe2G** [comment]
@akturtle for example if yor list_augment gives [data, weight, label], 
then you can access the gradient of weight with in_grad[1], then you can use the optimizer to update it

**Comment by akturtle** [comment]
@Ldpe2G Thanks

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
