### ISSUE TITLE
Get error "TBlob.get_with_shape: new and old shape do not match total elements". Can anyone help me with this?

### ISSUE THREAD

**Issue by yancz1989** [apache/incubator-mxnet#6657]
I'm implementing a simple segmentation using mxnet. I tried this code.
```
network = {}
network['data'] = mx.symbol.Variable('data')
network['conv1_1'] = mx.symbol.Activation(mx.symbol.Convolution(data = network['data'],
    kernel = (5, 5), num_filter = 32, pad = (2, 2), workspace = workspace), act_type = 'relu', name = 'conv1_1')
network['conv1_2'] = mx.symbol.Activation(mx.symbol.Convolution(data = network['conv1_1'],
    kernel = (3, 3), num_filter = 32, pad = (1, 1), workspace = workspace), act_type = 'relu', name = 'conv1_2')
network['pool1'] = mx.symbol.Pooling(data = network['conv1_2'],
pool_type = 'max', kernel = (2, 2), stride = (2, 2), name = 'pool1')
network['upspl1'] = mx.symbol.Activation(mx.symbol.UpSampling(
      data = network['pool1'],
      scale = 2,
      num_filter = 128,
      sample_type = 'bilinear',
      num_args = 2,
      workspace = workspace),
    act_type = 'relu', name = 'upspl1')
network['deconv1_2'] = mx.symbol.Activation(mx.symbol.Convolution(data = network['upspl1'], 
    kernel = (3, 3), num_filter = 32, pad = (1, 1), workspace = workspace), act_type = 'relu', name = 'deconv1_2')
network['deconv1_1'] = mx.symbol.Activation(mx.symbol.Convolution(data = network['deconv1_2'], 
    kernel = (3, 3), num_filter = 1, pad = (1, 1), workspace = workspace), act_type = 'relu', name = 'deconv1_1')
network['softmax'] = mx.symbol.SoftmaxOutput(data = network['deconv1_1'],
    multi_output = True, name = 'softmax')
decoder = network['softmax']
model.bind(data_shapes=train.provide_data, label_shapes=train.provide_label,
                  for_training=False, force_rebind=False)
model.init_params(initializer = initializer)
model.forward(dat)
print(self.get_outputs())
```

I get error

> TBlob.get_with_shape: new and old shape do not match total elements

I have checked the infer_shape which is the same with input dimension. I wonder what the problem is. Thanks for any advice.

**Comment by tornadomeet** [comment]
what's the output shape of `decoder`?  
what's the shape of your `train.provide_data` and `train.provide_label`?

**Comment by yancz1989** [comment]
@tornadomeet under current setting, output shape of decoder, train.provide_data and train.provide_label are all (batchsize, 1, 450, 794).

**Comment by tornadomeet** [comment]
ok. i suggest make sure which line cause this error, maybe it's not in your post code. or you can use minimum the symbol code to debug that.

**Comment by yancz1989** [comment]
@tornadomeet Fact is that if I remove the the last convolution layer, named "deconv1_1", making the output shape smaller than the input, the algorithm could run perfectly. Otherwise, it output an error. I use only one batch data for testing this.

**Comment by tornadomeet** [comment]
but `deconv1_1` do not change the shape when ```kernel=(3,3)``` and ```pad=(1,1)```

**Comment by yancz1989** [comment]
@tornadomeet Yes, and that's exactly what I want, to make the input and output shape the same.

**Comment by tornadomeet** [comment]
so your segmentation clss number is ```32```?   
try change `deconv1_1` to 
```python
network['deconv1_1'] = mx.symbol.Activation(mx.symbol.Convolution(data = network['deconv1_2'], 
    kernel = (3, 3), num_filter =32, pad = (1, 1), workspace = workspace), act_type = 'relu', name = 'deconv1_1')
```

**Comment by tornadomeet** [comment]
your label should be ```(batchsize, cls_num, 450, 794)```, and the num_filer of `deconv1_1` should be `cls_num`.

**Comment by yancz1989** [comment]
I use synthetic data just for a test. Class number is 31, and I leave one as ignore label.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by zhanghang1989** [comment]
I still get this error `TBlob.get_with_shape: new and old shape do not match total elements`
Any thoughts on this?

**Comment by XWalways** [comment]
I also get the error`TBlob.get_with_shape: new and old shape do not match total elements` when using gpu,but if i set the ctx=cpu, it works
