### ISSUE TITLE
Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_RT_LIBRARY)

### ISSUE THREAD

**Issue by codentropy** [apache/incubator-mxnet#6658]
hello, i want to install mxnet with python interface in win10 by vs2017.
as i run cmake -G  "Visual Studio 15 2017" in gitbash console, the MKL NOT FOUND error comes out:
$ cmake -G "Visual Studio 15 2017"
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_RT_LIBRARY)
--  MKL not found
CMake Error at CMakeLists.txt:129 (include):
  include could not find load file:

    mshadowUtils
...
i think i have installed Inter MKL correctly:
$ echo $MKL_INCLUDE_DIR
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\mkl\include

$ echo $MKL_RT_LIBRARY
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\mkl\lib\ia32

i tried: export MKL_FOUND=1, but the error remains. Can anyone help me? Thanks a lot!

**Comment by viper7882** [comment]
Hi @codentropy,

I've encountered the same error with yours. Here's one of the ways I've got it to work:
1. Open .\mxnet\build\CMakeCache.txt file.
2. Replace 
`MKL_RT_LIBRARY:FILEPATH=MKL_RT_LIBRARY-NOTFOUND`
with the following line:
`MKL_RT_LIBRARY:FILEPATH=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\mkl\lib\ia32_win`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
