### ISSUE TITLE
can mxnet support  incremental training？

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#6663]
go on trainning a pre-trained modle

**Comment by formath** [comment]
http://mxnet.io/how_to/finetune.html

**Comment by zihaolucky** [comment]
Load the checkpoint and fit again as @formath has pointed out.

```python
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-152', 0)
```

**Comment by janelu9** [comment]
@zihaolucky but I should reconnect the last layer ?

**Comment by zihaolucky** [comment]
@janelu9 Depends on you. You can get the useful info from the tutorial.

```python
# get checkpoint data, contains symbol and trained params.
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-152', 0)

# incremental
mod = mx.mod.Module(symbol=symbol, context=devs, arg_params=xxx, aux_params=xxx)  # you might want to push the params also
# fit/train again
mod.fit()
```

**Comment by janelu9** [comment]
@zihaolucky 
the tutorial says "We first define a function which replaces the last fully-connected layer for a given network."
 is this a latest tutorial?

**Comment by zihaolucky** [comment]
@janelu9 The idea of incremental learning and fine-tuning has a slight difference. If you just want to continue a training from a checkpoint, just load the model and fit again(in this time you choose a new data).

The tutorial tells you how to train your custom image classifier based on a pre-trained model from some other domain(ImageNet).

**Comment by janelu9** [comment]
sovled
