### ISSUE TITLE
cudnn_rnn-inl.h:233：对‘cudnnRNNBackwardData’未定义的引用

### ISSUE THREAD

**Issue by yja1** [apache/incubator-mxnet#6664]
when i make ,cause error:
cudnn_rnn-inl.h:233：对‘cudnnRNNBackwardData’未定义的引用
./cudnn_rnn-inl.h:260：对‘cudnnRNNBackwardWeights’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:205: recipe for target 'bin/im2rec' failed

gcc (Ubuntu 4.8.4-1ubuntu15) 4.8.4
libcudnn.so.5.1.10
cuda8.0

i have add in config.mk
ADD_LDFLAGS = -L/home/user/cudnn8.0/lib64
ADD_CFLAGS = -I/home/user/cudnn8.0/include

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
