### ISSUE TITLE
Compile for Android(arm64) failed, amalgamation

### ISSUE THREAD

**Issue by hereislife** [apache/incubator-mxnet#6678]
## Environment info
Operating System: ubuntu 16.04

Compiler: aarch64-linux-android-g++

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.10.0

MXNet commit hash (`git rev-parse HEAD`): ba2d9f61aa7b744c4ec3243097fb7170ad06012c

Python version: Python3.5

## Error Message:

/home/android-toolchain/bin/aarch64-linux-android-g++ -std=c++11 -Wno-unknown-pragmas -Wall -DMSHADOW_USE_CBLAS=0 -DMSHADOW_USE_SSE=0 -DDISABLE_OPENMP=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DDMLC_LOG_STACK_TRACE=0 -DMSHADOW_FORCE_STREAM -DMXNET_USE_OPENCV=0 -DMXNET_PREDICT_ONLY=1 -isystem /home/android-toolchain/include/c++/4.9.x -I/opt/OpenBLAS -I/opt/OpenBLAS/include -D_NDK_MATH_NO_SOFTFP=1 -O3 -fPIC -o jni_libmxnet_predict.o -c jni/predictor.cc \
-I `pwd`/../ \
-I `pwd`/../mshadow \
-I `pwd`/../include \
-I `pwd`/../nnvm/include -I `pwd`/../nnvm \
-I `pwd`/../dmlc-core/include -I `pwd`/../dmlc-core/src \
-I `pwd`/../dlpack/include \
-I /home/android-toolchain/include/c++/4.9.x
In file included from jni/predictor.cc:4:0:
jni/../mxnet_predict-all.cc:8542:0: warning: "MSHADOW_FORCE_STREAM" redefined
 #define MSHADOW_FORCE_STREAM
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from jni/predictor.cc:4:0:
jni/../mxnet_predict-all.cc:14207:0: warning: "API_END" redefined
 #define API_END() } catch(dmlc::Error &_except_) { return NNAPIHandleException(_except_); } return 0;  // NOLINT(*)
 ^
In file included from /home/cx/mxnet-arm/amalgamation/../src/c_api/c_api.cc:26:0,
                 from jni/../mxnet_predict-all.cc:61,
                 from jni/predictor.cc:4:
/home/cx/mxnet-arm/amalgamation/../src/c_api/./c_api_common.h:22:0: note: this is the location of the previous definition
 #define API_END() } catch(dmlc::Error &_except_) { return MXAPIHandleException(_except_); } return 0;  // NOLINT(*)
 ^
In file included from jni/predictor.cc:4:0:
jni/../mxnet_predict-all.cc:14213:0: warning: "API_END_HANDLE_ERROR" redefined
 #define API_END_HANDLE_ERROR(Finalize) } catch(dmlc::Error &_except_) { Finalize; return NNAPIHandleException(_except_); } return 0; // NOLINT(*)
 ^
In file included from /home/cx/mxnet-arm/amalgamation/../src/c_api/c_api.cc:26:0,
                 from jni/../mxnet_predict-all.cc:61,
                 from jni/predictor.cc:4:
/home/cx/mxnet-arm/amalgamation/../src/c_api/./c_api_common.h:28:0: note: this is the location of the previous definition
 #define API_END_HANDLE_ERROR(Finalize) } catch(dmlc::Error &_except_) { Finalize; return MXAPIHandleException(_except_); } return 0; // NOLINT(*)
 ^
In file included from jni/../mxnet_predict-all.cc:64:0,
                 from jni/predictor.cc:4:
/home/cx/mxnet-arm/amalgamation/../src/c_api/c_api_ndarray.cc: In function 'int MXAutogradBackward(mx_uint, void**, void**, int)':
/home/cx/mxnet-arm/amalgamation/../src/c_api/c_api_ndarray.cc:493:26: warning: unused variable 'ret' [-Wunused-variable]
   MXAPIThreadLocalEntry *ret = MXAPIThreadLocalStore::Get();
                          ^
In file included from jni/../mxnet_predict-all.cc:74:0,
                 from jni/predictor.cc:4:
/home/cx/mxnet-arm/amalgamation/../src/initialize.cc: In function 'void mxnet::segfault_logger(int)':
/home/cx/mxnet-arm/amalgamation/../src/initialize.cc:16:9: warning: unused variable 'stack' [-Wunused-variable]
   void *stack[MAX_STACK_SIZE];
         ^
In file included from /home/cx/mxnet-arm/amalgamation/../nnvm/include/nnvm/./base.h:9:0,
                 from /home/cx/mxnet-arm/amalgamation/../nnvm/include/nnvm/op.h:9,
                 from /home/cx/mxnet-arm/amalgamation/../include/mxnet/base.h:9,
                 from jni/../mxnet_predict-all.cc:27,
                 from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc: At global scope:
/home/cx/mxnet-arm/amalgamation/../dmlc-core/include/dmlc/registry.h:232:51: error: specialization of 'static dmlc::Registry<EntryType>* dmlc::Registry<EntryType>::Get() [with EntryType = nnvm::Op]' after instantiation
   Registry<EntryType > *Registry<EntryType >::Get() {                   \
                                                   ^
jni/../mxnet_predict-all.cc:11255:1: note: in expansion of macro 'DMLC_REGISTRY_ENABLE'
 DMLC_REGISTRY_ENABLE(nnvm::Op);
 ^
In file included from jni/predictor.cc:4:0:
jni/../mxnet_predict-all.cc: In member function 'nnvm::Symbol nnvm::Symbol::GetChildren() const':
jni/../mxnet_predict-all.cc:11688:16: warning: unused variable 'fnum_vis_output' [-Wunused-variable]
   static auto& fnum_vis_output = Op::GetAttr<FNumVisibleOutputs>("FNumVisibleOutputs");
                ^
In file included from /home/cx/mxnet-arm/amalgamation/../nnvm/include/nnvm/./base.h:9:0,
                 from /home/cx/mxnet-arm/amalgamation/../nnvm/include/nnvm/op.h:9,
                 from /home/cx/mxnet-arm/amalgamation/../include/mxnet/base.h:9,
                 from jni/../mxnet_predict-all.cc:27,
                 from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc: At global scope:
/home/cx/mxnet-arm/amalgamation/../dmlc-core/include/dmlc/registry.h:232:51: error: specialization of 'static dmlc::Registry<EntryType>* dmlc::Registry<EntryType>::Get() [with EntryType = nnvm::PassFunctionReg]' after instantiation
   Registry<EntryType > *Registry<EntryType >::Get() {                   \
                                                   ^
jni/../mxnet_predict-all.cc:11950:1: note: in expansion of macro 'DMLC_REGISTRY_ENABLE'
 DMLC_REGISTRY_ENABLE(nnvm::PassFunctionReg);
 ^

I have no idea about the error that says "specialization of xxx after instantiation".
Help!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
