### ISSUE TITLE
!!!GPU performance of Cmake built mxnet is worse than Make built one

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#6685]
I have tested the three cases many times as below:
1. When running train_mnist.py(GPU) on the Cmake built mxnet on Ubuntu, the average epoch time cost is 
0.7s. But the Make built mxnet on Ubuntu takes only 0.42s.

2. When running train_mnist.py(GPU) on the Cmake built mxnet on Windows, the average epoch time cost is 0.822s, even longer than running the script on MKL. The CPU(MKL) mode is about 0.6s.

3. The Windows MKL built mxnet version is better than the Ubuntu MKL built one. Each epoch of the former takes about 0.62s and each epoch of the later takes above 0.8s.
It's very weird. I hope the performance differences can be eliminated. I suggest that mxnet should bring a standard benchmark tool and reference performance index to measure running time such as the 'make runtest' of Caffe.

**Comment by chinakook** [comment]
I have also tested the detection on another computer with TITAN X(Maxwell). The CPU mode gets 61s but the GPU mode gets 89s. It's so strange!

**Comment by chinakook** [comment]
I use the Makefile instead of the CMake and the problem is solved.

**Comment by dtmoodie** [comment]
Which GPU do you have?  Is it a pascal?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by lebeg** [comment]
The reason for this is described in: https://github.com/apache/incubator-mxnet/issues/14085  Default cmake build uses openblas instead of MKL

**Comment by chinakook** [comment]
Does openblas or MKL have impacts on GPU performance?

**Comment by lebeg** [comment]
> Does openblas or MKL have impacts on GPU performance?

You are right, probably not. Didn't read the description carefully.
