### ISSUE TITLE
Segmentation Fault mx.sym.Convolution ops in CPU but working in GPU

### ISSUE THREAD

**Issue by chuckbasstan123** [apache/incubator-mxnet#6686]
I met a wired issue about `mx.sym.Convolution` operation with the error message of `segmentation fault` in ubuntu machine and `Segmentation fault: 11` in MAC machine under `mx.cpu()` context. 
However, the same code is working under `mx.gpu(0)`. 

## Environment info
Operating System: Ubuntu16.06 and MAC OS
Package used (Python/R/Scala/Julia): Python
MXNet version:'0.10.0' (with default `pip install mxnet`)
If you are using python package, please provide
    Python version and distribution: Python 2.7.10

## Error Message:
gdb -ex r --args python conv_debug.py
```
Starting program: /usr/bin/python conv_debug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3b88700 (LWP 2203)]
[New Thread 0x7ffff1387700 (LWP 2204)]
[New Thread 0x7ffff0b86700 (LWP 2205)]
[Thread 0x7ffff0b86700 (LWP 2205) exited]
[Thread 0x7ffff1387700 (LWP 2204) exited]
[Thread 0x7ffff3b88700 (LWP 2203) exited]
[New Thread 0x7ffff0b86700 (LWP 2208)]
[New Thread 0x7ffff1387700 (LWP 2209)]
[New Thread 0x7ffff3b88700 (LWP 2210)]
[New Thread 0x7fffbb846700 (LWP 2211)]
[New Thread 0x7fffbb045700 (LWP 2212)]
[New Thread 0x7fffba844700 (LWP 2213)]
[New Thread 0x7fffba043700 (LWP 2214)]
[New Thread 0x7fffb9842700 (LWP 2215)]

Thread 12 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb9842700 (LWP 2215)]
__memset_avx2 () at ../sysdeps/x86_64/multiarch/memset-avx2.S:152
152	../sysdeps/x86_64/multiarch/memset-avx2.S: No such file or directory.
```

## Minimum reproducible example
Here is the code to reproduce the error
```
import mxnet as mx
CTX = mx.cpu() #working by setting CTX to mx.gpu(0)
x = mx.sym.Variable('x')
kernel_size = (3,3)
dilate_size = (1,2)
stride = (1,1)
num_filter = (20)

conv = mx.sym.Convolution(data=x,
                          kernel=kernel_size,
                          pad=dilate_size,
                          dilate=dilate_size,
                          stride=stride,
                          num_filter=num_filter,
                          no_bias=True)
exe = conv.simple_bind(ctx=CTX,x=(1,128,1,128)) # NCHW, back to normal if H is set to a large number
out = exe.forward()[0].asnumpy()
print (out)
```
## What have you tried to solve it?
One possible problem is the code in **_CPU_** tried to access invalid memory when `H` is small than filter's `H`. 
However, this issue should be covered by setting padding as (1, *) (pad input's `H` to 3, same as filter's `H`). This issue is taken care by GPU implementation but not the CPU implementation. 
1. It is working by declaring the context to `mx.gpu(0)`
2.  OR, It is working by setting `x` with higher height (>kernel_size, 3 in this case)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
