### ISSUE TITLE
grouped convolutions seemingly not very efficiently

### ISSUE THREAD

**Issue by onealwj** [apache/incubator-mxnet#6689]
I implemented mobilenet but forward time looks slow in GPU. I use grouped conv to implement depthwise conv, set group equal to number of feature maps. The computation reduced by depthwise conv dosn't make inference time decrease. The mobilenet impemented by TF seem to be much faster[https://github.com/Zehaos/MobileNet](url),

**Comment by aktiger** [comment]
I encounter the same problem, will MxNet  add a more efficient group convolutions implementation ?

**Comment by KeyKy** [comment]
I encounter the same problem, will MxNet add a more efficient group convolutions implementation ? I found tf can run mobilenet 0.059s/image in cpu !!!

**Comment by ysh329** [comment]
mark

**Comment by coolbrain** [comment]
I encountered the same problem. The implementation of grouped convolutions is slow.

**Comment by ysh329** [comment]
Generally speaking, group implementation is based one or more GEMM ( matrix multiply, one implementation ways of convolution ). For example, if `group_num = 1` (default situation), then the total execution times of GEMM equals one. However, when `group_num = 2`, then the execution times equals two.

I don't read MXNet code of low API, so Is MXNet as I said above, which shoud read low-level codes.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by piiswrong** [comment]
For the record, we now have an efficient depthwise conv implementation when you set num_filters to num_groups
