### ISSUE TITLE
how to debug network layer by layer

### ISSUE THREAD

**Issue by vikingMei** [apache/incubator-mxnet#6692]
first of all, thank very much for afford such powerful tool

I'm try to combine [NCE loss](https://github.com/dmlc/mxnet/tree/master/example/nce-loss) and [bucketing LSTM](https://github.com/dmlc/mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py) in Python for few days. For now, the network is build successful and run without complain, the loss decreasing as batch feeding(very slow), and the PPL test on result model is very huge, so, I wanna to debug the model step by step, print weights and each layer's forward/backward tensor, to find where is the problem.

what's I have done yet:
1. install a monitor (find and fix a tiny bug while using monitor with bucketing module)
2. feed sample one per batch again and again
3. save weights, forward/backward tensor into file

after that, I do have all weights and each layers's forward/backward tensor saved in files. 

but while analysis those file, I found that some tensor are work as defined in net symbol, but some are not, what I have found are:
1. some layer are merge, such as a  element-wise multiply layer follow by a softmax layer, those two layers' forward output tensor are exactly same
1. in a mx.sym.Reshape layer, the input tensor and output tensor look like have no relation with each other, which is confuse me
1. the sample problem appear in backward flow

**so, is the underlay graph executor have optimize the symbol graph, and change the behavior of some layer?**

1. if so, is possible to disable this behavior?
2. if impossible, are there any document about this
3. or which source code should I read?
4. or, how do you debug model?

**thanks for and advices**

blows are my environment:
1. **OS**: centos 7.0, X86_64
1. **Python**:  Python 2.7.5
1. **Mxnet**:   da08c9203ecd1d8e3cd6a29ecf1a9238521f2351
`
Author: ziheng <ziheng@apache.org>
Date:   Sun Jun 4 17:43:47 2017 -0700
`
   - USE_PROFILE=1    (not open profile while running)
   - USE_CUDA = 1
   - USE_CUDNN = 1
   - USE_BLAS=mkl
   - USE_MKLML2017 = 1
   - USE_MKL2017_EXPERIMENTAL = 0
   -  USE_OPENMP = 1
   -  USE_NNPACK = 0
1. **gcc**:  gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by winstywang** [comment]
A trick used by me is to create a "debug" custom op. It simply duplicate the input to output. With it, you can simply access to all the internal outputs of a network.

**Comment by saicoco** [comment]
You can try `mx.monitor.Monitor`(https://github.com/dmlc/mxnet/blob/master/python/mxnet/monitor.py#L16), which can monitor outputs, weights, and gradients for debugging.

**Comment by vikingMei** [comment]
@winstywang, thanks, could you tell more detail about your method?

**Comment by vikingMei** [comment]
I think I have found where's the problem. 

as the monitor start before forward() call ( [see here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L484) ), and collection result after `backward()`, `update()`, `update_metric()` ([see here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L497)), while the tensor compute in `forward` may overwrite by latter call, as describe in [MXNet architecture::In place Option](http://mxnet.io/architecture/overview.html#operator-property) (I guess). After change to call monitor callback after each call, the saved tensor seems flow as define

I'll verify that latter

**Comment by Godricly** [comment]
Sth I used before. FYI.
```python
class Debug(mx.operator.CustomOp):
    def forward(self, is_train, req, in_data, out_data, aux):
        f = open('s.txt','w')
        value = in_data[0].asnumpy()
        for i in range(value.size):
            f.write('%1.6f\n'%(value.flat[i]))
        f.close()
        #x = in_data[0].asnumpy()
        #for i in range(144):
        #    print(x[i])
        self.assign(out_data[0],req[0], in_data[0])

    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        self.assign(in_grad[0],req[0], out_grad[0])
```

**Comment by vikingMei** [comment]
I think I have found the problem, as the monitor.tic() is call before `forward` call, but collect result after `backward`, `update` and `update_metric` call, which may change the tensor compute while forward.  I have change to collect result after each call, the tensor flow as defined  now. 

but backward gradients still confuse me, I'm trying to understand them....

**Comment by BiranLi** [comment]
@Godricly Can you print the name of Debug Symbol?
I have tried to code debug in C++, but it crash in KNL machine.

**Comment by Godricly** [comment]
@BiranLi Just follow the custom op introduction in python.

**Comment by BiranLi** [comment]
Just drop the label_shape?



lerin123@163.com
 
From: Yan Li
Date: 2017-06-22 19:45
To: dmlc/mxnet
CC: BiranLi; Mention
Subject: Re: [dmlc/mxnet] how to debug network layer by layer (#6692)
@BiranLi Just follow the custom op introduction in python.

**Comment by BiranLi** [comment]
@Godricly Just drop the label_shape is OK?

**Comment by Godricly** [comment]
@BiranLi Y do you need label shape?  This op acts like a shortcut in resnet. You can write a simple testing code.

**Comment by BiranLi** [comment]
@Godricly I thought of it as a all-pass layer. This layer does not need the label param. I will try it. Thx.

**Comment by Godricly** [comment]
its the same thing. forget that dimension match case.

2017-06-23 8:54 GMT+08:00 BiranLi <notifications@github.com>:

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by hdjsjyl** [comment]
@Godricly  thanks for your advice. But when I use the code, It has error: Check failed: reinterpret_cast<CustomOpFBFunc>(params.info->callbacks[kCustomOpBackward])( ptrs.size(), ptrs.data(), tags.data(), reinterpret_cast<const int*>(req.data()), static_cast<int>(ctx.is_train), params.info->contexts[kCustomOpBackward]). Any advice will be appreciated. Thanks
