### ISSUE TITLE
Is there InfogainLoss output symbol in mxnet?

### ISSUE THREAD

**Issue by xyddj** [apache/incubator-mxnet#6694]
I'm trying a regression work using mxnet, since the label is discrete, maybe "InfogainLoss" is better than LinearRegressionOutput. So is there a solution? Or I can only "make loss"?

**Comment by chunyang-wen** [comment]
[Loss Layers](https://github.com/chunyang-wen/mxnet/tree/master/example/recommenders)

Maybe you can refer to the code to define your own loss layers.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
