### ISSUE TITLE
Selecting argmax indices of a matrix column - Is it possible?

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#6705]
Hello,

I want to achieve the following in the symbolic graph: Assume that I have a Nxk sized matrix in the symbolic network, which is produced as the result of a FullyConnected layer. What I want to achieve is, for each k columns, indices of the rows, which has the maximum activations in the current column. For example, let's say we have
 `x = [[ 2.,  1.],
     [ 3.,  4.],
     [ 5.,  6.]]` . Assume that we a hypothetic function `argmaxColumn` which produces `[0]` as the result of `argmaxColumn(x,0)` and `[1,2]` as the result of `argmaxColumn(x,1)`. Then I aim to take the corresponding samples separately from x by using `mx.symbol.take` function. Is there a way to achieve this using Symbol API?

**Comment by piiswrong** [comment]
max(x, axis=0) and argmax(x, axis=0)?

**Comment by ufukcbicici** [comment]
No, since argmax(x, axis=1) will return the maximum column indices along each row. This is not what I want. I want that given a column i, the indices of the rows, which have their maximum values at column i. These are quite different things.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
