### ISSUE TITLE
data communication between nodes

### ISSUE THREAD

**Issue by Madalin-Florin** [apache/incubator-mxnet#6713]
Hello,

I am interesting in analyzing the traffic done during multi node training of imagenet and I am looking for the block of code that handles the shuffling of data between nodes. 

Can anyone help me to identify that?

**Comment by piiswrong** [comment]
python/mxnet/module/executor_group.py: load_general

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
