### ISSUE TITLE
Hacking codes fail when moving from CPU to GPU

### ISSUE THREAD

**Issue by chao1224** [apache/incubator-mxnet#6720]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 14

Package used (Python/R/Scala/Julia):
Python 2.7.6

MXNet version:
0.9.5

## Error Message:
I have some intermediate hacking output from some files under `~/src/operators/*`, and build local mxnet on it. You can think it's simply just some `cout` lines.

When I run my testing code for CPU, the intermediate information will show up. But when move to GPU, it never reaches the output lines. I'm doing exactly same thing, only provide `--gpus=0` when running.

## What have you tried to solve it?

I followed the instruction [here](http://mxnet.io/get_started/build_from_source.html), modify the config.mk, still not working.

Any thoughts would be helpful.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
