### ISSUE TITLE
How to save a learned network in C++ API

### ISSUE THREAD

**Issue by Bumblebee1964** [apache/incubator-mxnet#6726]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Win10

Compiler:VS2015

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
I learn my network with c++ API. I wan to use the "Predict" C++ API, but it requires I save the network in json format. How can I do that in c++ API? Has anyone an example?

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by lx75249** [comment]
Use NDArray::Save(https://github.com/dmlc/mxnet/blob/master/cpp-package/include/mxnet-cpp/ndarray.h#L386) to save your arg map and load it using NDArray::Load

**Comment by Bumblebee1964** [comment]
Thanks for your reply, very helpful. I will try it soon. Is there also a simple function to write the structure of the network to a json file?

**Comment by lx75249** [comment]
@Bumblebee1964 Symbol::Save(https://github.com/dmlc/mxnet/blob/master/cpp-package/include/mxnet-cpp/symbol.h#L109)

**Comment by Bumblebee1964** [comment]
Great, seams to solve my required functionality:)
