### ISSUE TITLE
Unable to release the GPU memory of the executor

### ISSUE THREAD

**Issue by boyurmit** [apache/incubator-mxnet#6737]
Hi, I need to build and train multiple model with different symbol in my program. When a new model is created, I need to delete the old one. However, the GPU memory of the old one seems never release. Is there some way to manual delete the executor or release the GPU memory?

## Environment info
Operating System: Ubuntu 16.04

Compiler: 

Package used (Python/R/Scala/Julia):

MXNet version: 0.10.0

Python version and distribution: Anaconda python 3.5

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. build first executor with 
mod = mx.mod.Module(symbol=sym1, context=devs)
mod.bind(data_shapes=train.provide_data, label_shapes=train.provide_label)
mod.set_params(arg_params, aux_params, allow_missing=True)

2. the GPU memory won't release when the function where build the mod ends or manual delete it by 'del mod'

## What have you tried to solve it?

1. command 'del mod' won't help
2. 'mx.model.FeedForward'  will also suffer this problem
3. put the building command in a function, but the GPU memory taken still exists when the function terminates.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
