### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by miraclewkf** [apache/incubator-mxnet#6760]
**I want to fine-tune a image classification model and the pre-trained model is a object detection model.
I just want to use the convNets part of the object detection model to initialize the parameters of my classification model. For example the object detection model is faster R-CNN and the classification model is VGG16. I use the fine-tune.py to fine-tuning my classification model, but there is an error.**

## the command is:
`python mxnet/example/image-classification/fine-tune.py --pretrained-model mx-detection/faster-rcnn --load-epoch 0004 --gpus 0 --data-train mx-detection/data/train_lst.rec --data-val mx-detection/data/test_lst.rec --batch-size 16 --num-classes 2 --num-examples 500000 --layer-before-fullc conv4`

## Error Message:
Traceback (most recent call last):
  File "mxnet/example/image-classification/fine-tune.py", line 49, in <module>
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/model.py", line 373, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/symbol.py", line 1771, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/base.py", line 85, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:23:35] src/operator/custom/./custom-inl.h:128: Check failed: registry_.find(param_.op_type) != registry_.end() Cannot find custom operator type proposal

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
