### ISSUE TITLE
Prepare data MXNET

### ISSUE THREAD

**Issue by Daliben** [apache/incubator-mxnet#6761]
Hi, 
I am new in python and mxnet, I want to make the example in the link:http://mxnet.io/how_to/finetune.html In the "Prepare data" part, when i run this script:

mkdir -p caltech_256_train_60
for i in 256_ObjectCategories/*; do
    c=`basename $i`
    mkdir -p caltech_256_train_60/$c
    for j in `ls $i/*.jpg | shuf | head -n 60`; do
        mv $j caltech_256_train_60/$c/
    done
done
I have the error:

"invalid syntax"
I did

os.system ('mkdir -p caltech_256_train_60')

and it worked and the directory was created.

For the rest, it does not work.

I think that this script is made for Linux and I need to ru it on windows 8 and python 2.7, someone can help me to translate this code so i can run it.

**Comment by nbrandaleone** [comment]
Those commands are meant to be run in a BASH script.

**Comment by Daliben** [comment]
Thanks.
How to run a bash script on python please?

**Comment by nbrandaleone** [comment]
You can't. It must be run separately.

**Comment by Daliben** [comment]
Please, give me an example for caltech256.sh knowing that i am using windows.

**Comment by nbrandaleone** [comment]
Sorry, I am not sure how to do it on Windows.  It MAY work if you you use Windows 10, and have installed the BASH shell.
You probably want to run it on an Ubuntu linux box for easiest compatibility.

https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10 <https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10> 

	Nick

**Comment by Daliben** [comment]
Thanks Nick.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
