### ISSUE TITLE
A question about ColorJitterAug

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#6771]
I am trying to do do some colour jitter using "**ColorJitterAug**" in "**image.py**". I saw in the code that the function returns a **RandomOrderAug** object. I am wondering how we put augmentation on real images. Does it work like: 
`cj = ColorJitterAug(x, x, x)`
`cj(image)` ?
If yes, does it simply calculate each pixel in a for loop? or use some efficient way internally. Thanks

**Comment by szha** [comment]
Yes. The returned `RandomOrderAug` just applies the three transformations from ColorJitterAug in random order. See https://github.com/dmlc/mxnet/blob/master/python/mxnet/image.py#L351. And yes, the returned object is a function that you can call. The way the transformation is applied depends on the implementation of those augmentation, see https://github.com/dmlc/mxnet/blob/master/python/mxnet/image.py#L369-L399.
