### ISSUE TITLE
undefined symbol: dnnBatchNormalizationCreateBackward_v2_F32

### ISSUE THREAD

**Issue by YANG-H** [apache/incubator-mxnet#6778]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: `Ubuntu 16.04`

Compiler: `g++5.4.0`

Package used (Python/R/Scala/Julia): `Python`

MXNet version: 

Or if installed from source: `YES`

MXNet commit hash (`git rev-parse HEAD`): `3ceb6d2f91121d5ffa5b81f435e8bcfcc1a75792`

If you are using python package, please provide

Python version and distribution: `Python 2.7.13 :: Anaconda custom (64-bit)`

## Error Message:
Please paste the full error message, including stack trace.
```
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yanghao/tools/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/yanghao/tools/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/yanghao/tools/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/yanghao/tools/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yanghao/tools/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so: undefined symbol: dnnBatchNormalizationCreateBackward_v2_F32
```

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Build MXNet with [this config.mk](https://gist.github.com/YANG-H/0e11a710c09bb87ed7430d121a017cda), where I set `USE_MKL2017=1` and `USE_MKL2017_EXPERIMENTAL = 1`,  no error occurred;
2. Install python binding with the following commands, no error;
```
cd python
python setup.py install
```
3. launch python and type `import mxnet as mx`, error occur.

## What have you tried to solve it?

1.  the generated `libmxnet.so` does not contain the `dnnBatchNormalizationCreateBackward_v2_F32` function as shown by `nm -gC libmxnet.so`

**Comment by szha** [comment]
What's the output of the following command?:
```readelf -d /home/yanghao/tools/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so```

**Comment by morusu** [comment]
same problem ， how to fix？

**Comment by szha** [comment]
@morusu which version, and which OS are you using?

**Comment by szha** [comment]
Feel free to reopen if issue persists.
