### ISSUE TITLE
Error importing mxnet in python, installed using pip 

### ISSUE THREAD

**Issue by varun-bankiti** [apache/incubator-mxnet#6785]
Hello All,

I just installed mxnet using `pip install mxnet-cu80` and the installation was successful. 

When I ran `import mxnet` in python it throws the fallowing error. 

**`undefined symbol: cublas gemm 3mStridedBatched`**

Below are the environment details. 
`Ubuntu 16.04.2 LTS, Python: 2.7.12, CUDA: 8.0, cuDNN: 5.0.5, GPU: Nvidia - Titan X(Pascal)
`
```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXXX/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/XXXX/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/XXXX/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/XXXX/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet/libmxnet.so: undefined symbol: cublasCgemm3mStridedBatched
```

Let me know if any other details will be useful to help me out. TIA.

**Comment by htcr** [comment]
Hi, I suppose you have cuda 8.0 and used the latest version of mxnet.
I ran into the same problem, and it turns out that cublasCgemm3mStridedBatched is a function of cuda v8.0.61. Check your cuda version. To solve the problem, you can either update cuda to latest version, or try with an older mxnet(before jun 2, when cuda v8.0.61 was released).

**Comment by yl-1993** [comment]
@htcr  Your solution works for me. Thanks!

**Comment by jm-huang** [comment]
Thanks you @htcr

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by cjolivier01** [comment]
This issue looks to be resolved. Please reopen if necessary.

**Comment by MXLHELLO** [comment]
> 嗨，我想你有cuda 8.0并使用了最新版本的mxnet。
> 我遇到了同样的问题，结果发现cublasCgemm3mStridedBatched是cuda v8.0.61的一个功能。检查你的cuda版本。要解决此问题，您可以将cuda更新到最新版本，或者尝试使用较旧的mxnet（在jun 2之前，当cuda v8.0.61发布时）。

hello~but I still can not solve this problem.because I can't use pip to install the mxnet-cu80 if the version is less than 0.10.0 .and the mxnet-cu80 remain the same problem

**Comment by MXLHELLO** [comment]
> Hi, I suppose you have cuda 8.0 and used the latest version of mxnet.
> I ran into the same problem, and it turns out that cublasCgemm3mStridedBatched is a function of cuda v8.0.61. Check your cuda version. To solve the problem, you can either update cuda to latest version, or try with an older mxnet(before jun 2, when cuda v8.0.61 was released).

hello~but I still can not solve this problem. Because I can't use pip to install the mxnet-cu80 if the version is less than 0.10.0 .and the mxnet-cu80 remain the same problem
