### ISSUE TITLE
OSError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ChongWu-Biostat** [apache/incubator-mxnet#6787]
I exactly followed the http://mxnet.io/get_started/install.html instruction to install the GPU version in the server, however, I am unable to install it successfully.

## Environment info
Operating System: CentOS release 6.9 (Final)

Compiler: gcc version 4.8.1 (GCC)

Package used (Python/R/Scala/Julia): Python

MXNet version:  mxnet-cu80

Or if installed from source: No. 

MXNet commit hash (`git rev-parse HEAD`): NA

If you are using python package, please provide

Python version and distribution: Python 3.5.2 |Anaconda 4.1.1

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panwei/wuxx0845/.local/lib/python3.5/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/panwei/wuxx0845/.local/lib/python3.5/site-packages/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/panwei/wuxx0845/.local/lib/python3.5/site-packages/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/panfs/roc/msisoft/anaconda/anaconda3-4.1.1/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so.1: cannot open shared object file: No such file or directory

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. I followed the steps as described on the website.

## What have you tried to solve it?

1. I tried to fix the path, including PATH, USE_CUDA_PATH, LD_LIBRARY_PATH.
Here is the information:
echo $PATH
/panfs/roc/msisoft/anaconda/anaconda3-4.1.1/bin:/panfs/roc/msisoft/openmpi/el6/1.7.2/gnu-4.8.1/bin:/panfs/roc/msisoft/gcc/4.8.1/bin:/panfs/roc/msisoft/opencv/3.1.0/bin:/panfs/roc/msisoft/ffmpeg/2.6.2/bin:/panfs/roc/msisoft/java/jdk1.8.0_45/bin:/panfs/roc/msisoft/vtk/7.0.0/bin:/panfs/roc/msisoft/gcc/6.1.0/bin:/panfs/roc/msisoft/cuda/8.0/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/adm/suacct/bin:/opt/suacct/bin:/opt/moab/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/panfs/roc/msisoft/cuda-sdk/8.0/NVIDIA_CUDA-8.0_Samples/bin/x86_64/linux/release

 echo $USE_CUDA_PATH
/panfs/roc/msisoft/cuda/8.0/

 echo $LD_LIBRARY_PATH
/panfs/roc/msisoft/cuda/8.0/:/panfs/roc/msisoft/cuda/8.0/lib64/stubs/:/panfs/roc/msisoft/openmpi/el6/1.7.2/gnu-4.8.1/lib:/panfs/roc/msisoft/gcc/4.8.1/lib64:/panfs/roc/msisoft/opencv/3.1.0/lib:/panfs/roc/msisoft/ffmpeg/2.6.2/lib:/panfs/roc/msisoft/java/jdk1.8.0_45/jre/lib/amd64/server:/panfs/roc/msisoft/vtk/7.0.0/lib:/panfs/roc/msisoft/vtk/7.0.0/lib/vtk-7.0:/panfs/roc/msisoft/isl/0.16.1_gcc6.1.0/lib:/panfs/roc/msisoft/mpc/1.0.3_gcc6.1.0/lib:/panfs/roc/msisoft/mpfr/3.1.4-p1_gcc6.1.0/lib:/panfs/roc/msisoft/gmp/6.1.0_gcc6.1.0/lib:/soft/intel/x86_64/2013/composer_xe_2013/composer_xe_2013.5.192/compiler/lib/intel64:/soft/intel/x86_64/2013/composer_xe_2013/composer_xe_2013.5.192/mkl/lib/intel64:/panfs/roc/msisoft/cudnn/5.1/lib64:/panfs/roc/msisoft/cuda/8.0/lib64:/panfs/roc/msisoft/cuda/8.0/lib:/panfs/roc/msisoft/gcc/6.1.0/lib64

Since I am using the server, I just load cuda and related packages. 
module load cuda/8.0
module load cuda-sdk/8.0 
module load cudnn/5.1
module load mkl
module load opencv/3.1.0_gcc6.1.0
module load ompi/gnu
module load python3/3.5.2_anaconda4.1.1

I am not sure what's wrong with my procedures. I really want to install mxnet and use it. Thanks for your help in advance.

**Comment by szha** [comment]
So the problem here is just that `ctypes.CDLL` can't find the libcuda. Could you try the following?
```
find / -type f -name libcuda.so.* -exec dirname {} \; 2>/dev/null
```
The above command prints the paths to libcuda.so.*, and you can append those to your LD_LIBRARY_PATH variable to fix the issue. Otherwise, you may want to look into installing cuda again since the libcuda isn't available on your system.

**Comment by zhangxgu** [comment]
I have the same problem as you. I was trying to install mxnet-cu80 on supercomputer, when I met this problem. I also did
module load cuda/8.0
module load cudnn/5.1
But I still can't make it.

**Comment by ChongWu-Biostat** [comment]
@zhangxgu 
Do you solve the problems? At that time, I used Theano to do my project. I think it might be a good time to learn mxnet.

**Comment by szha** [comment]
@ChongWu-Biostat did you try the proposed fix above?

**Comment by ChongWu-Biostat** [comment]
@szha I don't think that works. I am unable to find libcuda.so anyway.

Thanks,
Chong

**Comment by szha** [comment]
@ChongWu-Biostat you need your cuda driver and the cuda library to use the GPU version. Are you able to find and install the libcuda through other methods?

**Comment by ChongWu-Biostat** [comment]
@szha  I use the university super computing source. I load all the required packages and software and with the right version, I think. How do you solve this problem? Thanks for your help in advance...

Thanks,
C

**Comment by szha** [comment]
@ChongWu-Biostat you should try to get help from your university on locating the cuda driver and the cuda library, and once you find the location, adding it to LD_LIBRARY_PATH variable fixes the problem.

**Comment by mli** [comment]
accroding to the LD_LIBRARY_PATH, cuda seems installed at /panfs/roc/msisoft/cuda/8.0/

you can try if you have libcuda.so on the directory, often it is located at

 /panfs/roc/msisoft/cuda/8.0/lib64/stubs/libcuda.so

**Comment by ChongWu-Biostat** [comment]
Yes, I find libcuda.so under the folder /panfs/roc/msisoft/cuda/8.0/lib64/stubs/libcuda.so. However, I am unable to find libcuda.so.1 under this folder.

**Comment by szha** [comment]
Does creating a symlink in that path work?
```
ln -s libcuda.so /panfs/roc/msisoft/cuda/8.0/lib64/stubs/libcuda.so.1
```

**Comment by ChongWu-Biostat** [comment]
@szha @mli 
Thanks for your help. I solve the problems. It simply because I do not login into the right server, which contains GPUs.
