### ISSUE TITLE
how can I export the embedding layer's parameter from a trained word2vec model?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#6791]
I plan to share this parameter to other model

**Comment by szha** [comment]
Yes. It requires having the same indexer  for words across different models. Specifically, suppose you want to share a pretrained word-embedding of vocabulary size `K`, each of dimension `d`:
1. use the indexer to index the `K` words (i.e "word" -> index such as 0, 1 ...K-1)
```
# suppose word2vec = {w: v_ddim}
idx2w = list(word2vec.keys())
w2idx = {w: i for i, w in enumerate(idx2w)}
```
2. create the weight for embedding and use it perform look up.
```
weight = nd.array(word2vec.values())
sentence = 'hello world'.split()
sent_idx = nd.array([w2idx[w] for w in sentence])
sent_weights = nd.Embedding(data = sent_idx, weight = weight)
```
3. and in your new model, just remember to index the sentence using the same indexers (`idx2w and w2idx`.

**Comment by zihaolucky** [comment]
```python
sym, arg_params, aux_params = mx.model.load_checkpoint('your-model-prefix', best_epoch)
arg_params['the-param'].asnumpy()   # arg_params is a dict from params to NDArray 
```

**Comment by janelu9** [comment]
@szha but is there a mx.nd.Embedding? need i import it by the dataiter firstly and use it as a mx.symbol?

**Comment by szha** [comment]
yes
