### ISSUE TITLE
can't find op.h when I try to use example in cpp-package

### ISSUE THREAD

**Issue by bsli** [apache/incubator-mxnet#6794]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 14.04

Compiler:g++ 4.8

Package used (Python/R/Scala/Julia):C++

MXNet version:trunk

Or if installed from source:yes

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.compile test sample in cpp-package.
2.op.h file can not found 
3.In file included from ../include/mxnet-cpp/MxNetCpp.h:16:0,
                 from mlp.cpp:8:
../include/mxnet-cpp/optimizer.hpp:19:26: fatal error: mxnet-cpp/op.h: No such file or directory

## What have you tried to solve it?

1.vim a new file named op.h just edit it include op*.h

**Comment by szha** [comment]
op.h was removed in pr #5573. @cjolivier01 @piiswrong

**Comment by szha** [comment]
This shouldn't cause problems any more if you check out the latest version.

Feel free to reopen if issue persists.
