### ISSUE TITLE
Fix cmake build

### ISSUE THREAD

**Issue by dtmoodie** [apache/incubator-mxnet#6799]
There are several runtime issues that exist in a cmake build but not a make build:
https://github.com/dmlc/mxnet/issues/6592
https://github.com/dmlc/mxnet/issues/6204
https://github.com/dmlc/mxnet/issues/6775

All the above are resolved using the makefile build on ubuntu 16.04.

**Comment by piiswrong** [comment]
@cjolivier01

**Comment by chinakook** [comment]
#6685

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
