### ISSUE TITLE
Order matters for data_names in Module

### ISSUE THREAD

**Issue by yash1** [apache/incubator-mxnet#6801]
Hey, 

I was creating a Module, and it looks like the order of the list of the `data_names` matters. 
For example, 
```
mod = mx.mod.Module(symbol=net,
                    context=mx.cpu(),
                    data_names=['user','item'],
                    label_names=['score'])
```

Gave the error: `ValueError: Data provided by data_shapes don't match names specified by data_names`

However, this works:
```
mod = mx.mod.Module(symbol=net,
                    context=mx.cpu(),
                    data_names=['item','user'],
                    label_names=['score'])
```

I don't think it should matter what order you specify the `data_names`. Is this the expected behavior? If so, there is no documentation on what order the `data_names` need to be.

**Comment by formath** [comment]
this should be the same order with that of `net.list_inputs()`

**Comment by formath** [comment]
Error should show more message. Please paste all.

**Comment by vikingMei** [comment]
the order of data_names your pass to Module should same with provider_data and provider_label in data iterator, I guess

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
