### ISSUE TITLE
Can multiple gpu will reduce the accuracy compared to single gpu?

### ISSUE THREAD

**Issue by niluanwudidadi** [apache/incubator-mxnet#6804]
Can multiple gpu will reduce the accuracy compared to single gpu?

**Comment by kevinthesun** [comment]
Data parallelism should get the same result on single device if batch size remains the same.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
