### ISSUE TITLE
Batchsize error on multi cpus

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#6806]
I configured batch size = 64, and dev = [mx.cpu(i) for i in range(4)] to use four cpus.  
And got error like bellow。I modified the dev = [mx.cpu(0)] to use only one cpu, the error disappears.   
  
I know each cpu takes 1/4 slice of the batch.  
What should i do if i want to use 4 cpus on my macbook?  

---
Here is the error when dev = [mx.cpu(i) for i in range(4)]:

DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  optimizer=optimizer)
[14:58:06] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [14:58:06] src/operator/tensor/./matrix_op-inl.h:1041: Check failed: (*end <= axis_size) && (*end >= 0) Invalid begin, end, get begin=0, end=64

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010c42e2b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010c42c099 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010c977ed7 _ZN5mxnet2op18GetSliceAxisParamsERKNS0_14SliceAxisParamERKN4nnvm6TShapeEPiS8_S8_ + 535
[bt] (3) 3   libmxnet.so                         0x000000010c963a59 _ZN5mxnet2op14SliceAxisShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 233
[bt] (4) 4   libmxnet.so                         0x000000010db62343 _ZZN4nnvm4pass12_GLOBAL__N_19InferAttrINS_6TShapeEZNKS1_3$_0clENS_5GraphEEUlRKS3_E_DnEES5_OS5_T_PKcSC_SC_SC_SC_T0_T1_ENKUljbE_clEjb + 2707
[bt] (5) 5   libmxnet.so                         0x000000010db60c1a _ZNSt3__110__function6__funcIN4nnvm4pass12_GLOBAL__N_13$_0ENS_9allocatorIS5_EEFNS2_5GraphES8_EEclEOS8_ + 3738
[bt] (6) 6   libmxnet.so                         0x000000010db4aefb _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 1419
[bt] (7) 7   libmxnet.so                         0x000000010ca57080 _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 208
[bt] (8) 8   libmxnet.so                         0x000000010ca5a781 _ZN4nnvm4pass10InferShapeENS_5GraphENSt3__16vectorINS_6TShapeENS2_9allocatorIS4_EEEENS2_12basic_stringIcNS2_11char_traitsIcEENS5_IcEEEE + 929
[bt] (9) 9   libmxnet.so                         0x000000010ca585a6 MXSymbolInferShape + 1974

infer_shape error. Arguments:
  positive: (16, 3, 224, 224)
  one: (16,)
  anchor: (16, 3, 224, 224)
  negative: (16, 3, 224, 224)
Traceback (most recent call last):
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 113, in <module>
    test_train()
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 109, in test_train
    epoch_end_callback=mx.callback.do_checkpoint("models/ir-blur"))
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 826, in fit
    sym_gen=self.sym_gen)
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 207, in _train_multi_device
    logger=logger)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 326, in __init__
    self.slices, train_data)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 238, in __init__
    input_types=data_types)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 105, in _bind_exec
    arg_shape, _, aux_shape = sym.infer_shape(**input_shapes)
  File "/Library/Python/2.7/site-packages/mxnet/symbol.py", line 872, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/mxnet/symbol.py", line 998, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Library/Python/2.7/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator slice_axis0: [14:58:06] src/operator/tensor/./matrix_op-inl.h:1041: Check failed: (*end <= axis_size) && (*end >= 0) Invalid begin, end, get begin=0, end=64

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010c42e2b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010c42c099 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010c977ed7 _ZN5mxnet2op18GetSliceAxisParamsERKNS0_14SliceAxisParamERKN4nnvm6TShapeEPiS8_S8_ + 535
[bt] (3) 3   libmxnet.so                         0x000000010c963a59 _ZN5mxnet2op14SliceAxisShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 233
[bt] (4) 4   libmxnet.so                         0x000000010db62343 _ZZN4nnvm4pass12_GLOBAL__N_19InferAttrINS_6TShapeEZNKS1_3$_0clENS_5GraphEEUlRKS3_E_DnEES5_OS5_T_PKcSC_SC_SC_SC_T0_T1_ENKUljbE_clEjb + 2707
[bt] (5) 5   libmxnet.so                         0x000000010db60c1a _ZNSt3__110__function6__funcIN4nnvm4pass12_GLOBAL__N_13$_0ENS_9allocatorIS5_EEFNS2_5GraphES8_EEclEOS8_ + 3738
[bt] (6) 6   libmxnet.so                         0x000000010db4aefb _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 1419
[bt] (7) 7   libmxnet.so                         0x000000010ca57080 _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 208
[bt] (8) 8   libmxnet.so                         0x000000010ca5a781 _ZN4nnvm4pass10InferShapeENS_5GraphENSt3__16vectorINS_6TShapeENS2_9allocatorIS4_EEEENS2_12basic_stringIcNS2_11char_traitsIcEENS5_IcEEEE + 929
[bt] (9) 9   libmxnet.so                         0x000000010ca585a6 MXSymbolInferShape + 1974

**Comment by kevinthesun** [comment]
Try to use module instead of model?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
