### ISSUE TITLE
The process has forked on macbook when running with python dataiter code

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#6807]
I am using my own data iter to train resnet, and encountered  error:
   
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

  ---

My data iter code is like this:  
  

class DataIter(mx.io.DataIter):
        
   def __init__(self, images, image_pairs, image_similar_neg, batch_size, height, width, process_num):
          assert process_num <= 40
          super(DataIter, self).__init__()
          self.batch_size = batch_size
          self.conut = len(images)
          self.height = height
          self.width = width
          self.images = images
          self.image_pairs = image_pairs
          self.image_similar_neg = image_similar_neg
          self.cursor = -self.batch_size
          self.provide_data = [("positive", (self.batch_size, 3, height, width)),
                               ("negative", (self.batch_size, 3, height, width)),
                               ("one", (self.batch_size, ))]
         self.provide_label = [("anchor", (self.batch_size, 3, height, width))]
         self.queue = multiprocessing.Queue(maxsize=4)
         self.started = True
         self.processes = [multiprocessing.Process(target=self.write) for i in range(process_num)]
         for process in self.processes:
              process.daemon = True
              process.start()

**Comment by universewill** [comment]
It seems that macos doesn't support fork reliablely. I am wandering how to implement a dataIter on macbook.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
