### ISSUE TITLE
I need some tips for creating a new Iterator in C++

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#6812]
Hi,
I want to create a new iterator in C++ for segmentation tasks. So the data labels are different from the ones used in Classification or Detection. Could anyone give me some tips on general procedures, like what classes should I extend from and what classes should I include, etc. thanks a lot.
@tqchen @piiswrong @mli

**Comment by ascust** [comment]
I have figured out something to implement a new iterator, but there is one thing I am confused. I want to make each batch have two types of labels, like DATABATCH((image), (label1, label2)), but I have gone through the code and have thought a solution. 
In each of the already done iterators in C++, I found this is one variable called _out to hold the current batch of data. The type of this variable is "DataInst". From the definition of this type.
```
struct DataInst {
  /*! \brief unique id for instance */
  unsigned index;
  /*! \brief content of data */
  std::vector<TBlob> data;
  /*! \brief extra data to be fed to the network */
  std::string extra_data;
};  // struct DataInst
```
It seems it only has a vector of TBlob. So how do we distinguish between data and labels if we want multiple types of labels of even data? Thanks. @piiswrong @tqchen @mli

**Comment by ascust** [comment]
@piiswrong I have modified the code a bit to support more than just one label ndarray. Please modify it further if there is anything inappropriate.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
