### ISSUE TITLE
How can I train with multiple CPUs with model parallelism?

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#6815]
I read the doc 'How can I train with multiple GPUs with model parallelism?'
However, my macbook only has cpus available. 
I set the ctx as  [mx.cpu(i) for i in range(4)], and set the dataiter, network batch size as 64, and encounters error. i do not know how to fix it.
I set model_parallel = True in the data iter, the same error still exists.

-----
  
I got error like this:  
  
src/operator/tensor/./matrix_op-inl.h:1041: Check failed: (*end <= axis_size) && (*end >= 0) Invalid begin, end, get begin=0, end=64
... ...
infer_shape error. Arguments:
  positive: (16, 3, 224, 224)
  one: (16,)
  anchor: (16, 3, 224, 224)
  negative: (16, 3, 224, 224)  
... ...
mxnet.base.MXNetError: Error in operator slice_axis0: [16:14:17] src/operator/tensor/./matrix_op-inl.h:1041: Check failed: (*end <= axis_size) && (*end >= 0) Invalid begin, end, get begin=0, end=64

**Comment by kevinthesun** [comment]
Can you share your code or provide a minimal reproducible example?

**Comment by eric-haibin-lin** [comment]
Why do you want to train model parallel on CPU? If you use mx.cpu(), it uses all CPU cores.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
