### ISSUE TITLE
Infer_shape in custom operator

### ISSUE THREAD

**Issue by abuzn** [apache/incubator-mxnet#6816]
I try to implement a customOp using python, if anyone knows how to implement the infer_shape(self,in_shape) function if the out_shape is independent of in_shape but depended on in_data?
For example, if you want to implement a customOp like mx.symbol.arange, and the out_shape is only related with input data.

Thanks.

**Comment by Ldpe2G** [comment]
@abuzn did you means your customOp's shape may be change every batch since it relates to the input data. Or you means the customOp's shape is relates to the attribute parameter like arange?

**Comment by abuzn** [comment]
@Ldpe2G I mean  customOp's shape changed every batch since it relates to the input data. Is it possible in mxnet?

**Comment by Ldpe2G** [comment]
@abuzn shape change every is possible in mxnet, but your case is special because the out shape of the customOp is related to the inData which is not known in the inferShape but only known in the forward pass.
I am not sure whether this is possible in mxnet.
@piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by KeyKy** [comment]
Is there a solution of this issue??

**Comment by Ldpe2G** [comment]
try using the gluon api
