### ISSUE TITLE
im2rec.py can not work

### ISSUE THREAD

**Issue by skywayoo** [apache/incubator-mxnet#6821]
Hello,

I use im2rec.py create .lst and .rec looks work well, until my number of images grow to 1 million, when i create .rec it stop without any error, any suggestion? I check memory and disk are enough.

![image](https://user-images.githubusercontent.com/13115561/27553734-c2b3a09e-5ade-11e7-9cdc-f15410fda807.png)

*update error
![image](https://user-images.githubusercontent.com/13115561/27579771-3053302a-5b5b-11e7-81ba-07f9ab063a89.png)

 Thanks for your time

## Environment info
Operating System: win7 64bit
Package used (Python/R/Scala/Julia): python 2.7
MXNet version: mxnet-0.9.5-py2.7

**Comment by kevinthesun** [comment]
Looks like buff s is None and passed into record.write_idx. Can you check that?
