### ISSUE TITLE
Is there a way to limit the allocation of GPU memory that mxnet uses?

### ISSUE THREAD

**Issue by im9uri** [apache/incubator-mxnet#6833]
Hello.

I'm curious if there is a way to limit the allocation of GPU memory that mxnet uses.

For example in theano, setting cnmem in .theanorc limits the maximum amount of memory used by the system.

Thank you!

**Comment by dtmoodie** [comment]
I too would be interested in this.  I have a system using caffe, mxnet, and my own memory allocator and 12GB isn't enough!

It would be really nice to able to install my own memory allocator so everyone can share nicely.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
