### ISSUE TITLE
Mxnet  does not contain any example codes of attention model!

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#6835]
As you can see above in the title. I don't find any attention example codes. I'm a newer for attention model. I wish Mxnet developers or any contributors can provide a notebook for attention model.

**Comment by Ldpe2G** [comment]
@liuzhi136 you can refer to this project:
https://github.com/magic282/MXNMT/tree/next/mxwrap/attention

**Comment by fhieber** [comment]
@liuzhi136 the sockeye seq2seq project (https://github.com/awslabs/sockeye) also contains a couple of attention models.

**Comment by liuzhi136** [comment]
@fhieber @Ldpe2G thank you for both of you. @fhieber Do you have any attention model paper collections or paper road-map? I want to read them systematically.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
