### ISSUE TITLE
Saving ndarray to disk using .rec format?

### ISSUE THREAD

**Issue by im9uri** [apache/incubator-mxnet#6836]
Hello.

I'm attempting to save a ndarray to disk using RecordIO.

Because it is larger than memory, NDArrayIter can't be used.

Because it is not an image (specifically because it is float32, not uint8), ImageRecordIter can't be used.

MXRecordIO can't be used because ndarray is not an integer or string.

What I'm specifically trying to achieve is saving the result of a convolution layer of resnet, so that I can just load a precomputed value when fine tuning.

Any help would be appreciated.

Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
