### ISSUE TITLE
What is  python interface to underlying c/c++?

### ISSUE THREAD

**Issue by wguo68** [apache/incubator-mxnet#6853]
How MxNet use one or both of " cython "  and "ctypes" to bind to underlying c/c++?  
I don't know the process of how the python interact with the underlying  C/C++ code. There is little document to explain the process. It prevent me from reading the code.

Thanks

**Comment by reminisce** [comment]
It is all under the directory src/c_api, where c++ provides interfaces to be called from python. You can take a look at existing implementations such as symbol.py/executor.py to get a feeling of it. The convention of naming the interface has "MX" as prefix. So when you see something like _LIB.MXSymbolCopy, you can search for "MXSymbolCopy" under src/c_api to look at its c++ implementation.

**Comment by wguo68** [comment]
Thank you. I am not familiar with python.  Did Mxnet use both ctypes and cpython to bind the underlying C++ API?

**Comment by reminisce** [comment]
It's not only for python. Other language can use those c apis too. By default it uses ctypes, but you can switch to cython as well.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
