### ISSUE TITLE
build mxnet with MKL installed on system

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6855]
If I want to build mxnet with an existing MKL, I need to set 
USE_INTEL_PATH=.....
and run make -j USE_BLAS=mkl
Do I still need to set USE_MKL2017 = 1? 

Setting USE_MKL2017 seems always downloading MKL and use the downloaded MKLML to build mxnet, correct? Will it turn on different code in mxnet by setting USE_MKL2017=1?

**Comment by BiranLi** [comment]
YES. you should set USE_MKL2017 to 1 to use MKL set in INTEL_PATH.

**Comment by patricianing** [comment]
@BiranLi But setting MKL2017=1 always downloads mklml libraries and used those to build mxnet instead of using the mkl installed. 
Also is mklml a subset of MKL or a subset of MKL_DNN?

**Comment by BiranLi** [comment]
@patricianing Have you run the mklvars.sh script in current session?

**Comment by patricianing** [comment]
@BiranLi where is mklvars.sh located? I only see prepare_mkl.sh in the master directory.

**Comment by BiranLi** [comment]
@patricianing Check the path where you installed mkl2017 such as "/opt/intel/mkl/bin/". Then exercute "source mklvars.sh intel64".

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
