### ISSUE TITLE
Links on the page with the RNN tutorials are broken

### ISSUE THREAD

**Issue by b0noI** [apache/incubator-mxnet#6857]
All links here: http://mxnet.io/tutorials/nlp/rnn.html returns 404

**Comment by kevinthesun** [comment]
Hi @b0noI ,

We are removing these old tutorials from website. You can find them here: https://github.com/dmlc/mxnet/tree/master/example/rnn/old

**Comment by b0noI** [comment]
@kevinthesun ack, though, main bug is just about the fact that customer facing page with the tutorial have broken links, we need either remove the page or update the links.

**Comment by kevinthesun** [comment]
This issue has been fixed.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Still gives 404

**Comment by szha** [comment]
that specific tutorial is no longer offered.
