### ISSUE TITLE
Distributed KeyValue Store broken?

### ISSUE THREAD

**Issue by amithr1** [apache/incubator-mxnet#6858]
Hi All,

Are the new KVStore API changes applied to distributed KVStore? Looks like the new API (using strings instead of ints for keys) is added only to the KVStore local.

**Comment by szha** [comment]
Did you observe problem with the distributed kvstore?

**Comment by piiswrong** [comment]
@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
@amithr1 did you observe any problem? kvstore_dist inherits the str method from kvstore_local. 
https://github.com/dmlc/mxnet/blob/master/src/kvstore/kvstore_local.h#L105
