### ISSUE TITLE
HDF5 DataIter Python

### ISSUE THREAD

**Issue by abieler** [apache/incubator-mxnet#6872]
Edit: NDArrayIter now supports h5py datasets, which is the recommended way for interacting with hdf5 data sets. See example a few comments below.

I basically put together a DataIter for HDF5 data in python. It is pretty much a clone of NDArrayDataIter  (without shuffeling as it is out of core).
See code and example below. The idea is to load data into memory batch by batch, hence it performs slower than NDArrayIter which has everything in memory.

(getlabel() update 15.08.2017)
```python
class HDF5ArrayIter(DataIter):

    def __init__(self, data, label, batch_size=1,
                 data_name="data", label_name="softmax_label",
                 last_batch_handle="pad"):
        super(HDF5ArrayIter, self).__init__(batch_size)

        self.data = data 
        self.label = label 
        self.batch_size = batch_size
        self.cursor = -batch_size
        self.num_data = data.shape[0]
        self.last_batch_handle = last_batch_handle
        self.data_name = data_name
        self.label_name = label_name


    @property
    def provide_data(self):
        return [DataDesc(self.data_name,
                         tuple([self.batch_size] + list(self.data.shape[1:])),
                         self.data.dtype)]

    @property
    def provide_label(self):
        return [DataDesc(self.label_name,
                         tuple([self.batch_size] + list(self.label.shape[1:])),
                         self.label.dtype)]

    def hard_reset(self):
        self.cursor = -self.batch_size

    def reset(self):
        if self.last_batch_handle == "roll_over" and self.cursor > self.num_data:
            self.cursor = -self.batch_size + (self.cursor % self.num_data) % self.batch_size
        else:
            self.cursor = -self.batch_size 


    def iter_next(self):
        self.cursor += self.batch_size
        return self.cursor < self.num_data


    def next(self):
        if self.iter_next():
            return DataBatch(data=self.getdata(),
                             label=self.getlabel(),
                             pad=self.getpad(),
                             index=None)
        else:
            raise StopIteration


    def getdata(self):
        assert(self.cursor < self.num_data), "DataIter needs reset."
        if self.cursor + self.batch_size <= self.num_data:
            return [array(self.data[self.cursor:self.cursor+self.batch_size])]
        else:
            pad = self.batch_size - self.num_data + self.cursor
            return [concatenate(array(self.data[self.cursor:]), array(self.data[:pad]))]


    def getlabel(self):
        assert(self.cursor < self.num_data), "DataIter needs reset."
        if self.cursor + self.batch_size <= self.num_data:
            return [array(self.label[self.cursor:self.cursor+self.batch_size])]
        else:
            pad = self.batch_size - self.num_data + self.cursor
            return [concatenate(array(self.label[self.cursor:]), array(self.label[:pad]))]


    def getpad(self):
        if self.last_batch_handle == "pad" and self.cursor + self.batch_size > self.num_data:
            return self.cursor + self.batch_size - self.num_data
        else:
            return 0
```
And finally to be used as follows:
```python
with h5py.File("myDataFile.hdf5", "r") as h5:
    X = h5["myData"]
    y = h5["myLabels"]
    train_iter = HDF5ArrayIter(X, y, BATCH_SIZE, last_batch_handle="pad")
```

I can submit a PR and add docs if people find it a good enough idea.
Comments?

Cheers
Andre

**Comment by xiaogehh** [comment]
I use this code but have error.What library should be import?

**Comment by xiaogehh** [comment]
![image](https://user-images.githubusercontent.com/7589403/31527584-f4760ef6-b000-11e7-9533-54c09b730628.png)

But no example anout how to use oout-of-training for hdf5

**Comment by abieler** [comment]
Here a toy example where I first write the data to disk, then load it back (assuming this would be a different session...) and iterate over it with `NDArrayIter`

```python
import numpy as np
import h5py
import mxnet as mx

N = 1000

X = np.random.normal(0,1,(N,12))
y = np.random.randint(0,2,N)

# write data to file
with h5py.File('myfile.hdf5', "w") as ofile:
    ofile.create_dataset("X", data=X)
    ofile.create_dataset("y", data=y)

# load data from file
ifile = h5py.File('myfile.hdf5', 'r')

X_h5 = ifile["X"]
y_h5 = ifile["y"]

batch_size = 200
dataiter = mx.io.NDArrayIter(X_h5, y_h5, batch_size=batch_size)

for iBatch, batch in enumerate(dataiter):
    print(iBatch, batch.data[0].asnumpy().shape)

ifile.close()
```

**Comment by xiaogehh** [comment]
wow,Thank you so much.But sometime I want to train a RNN,and it has varing time-steps,can it be load as hdf5 format then uising `NDArrayIter`?

**Comment by abieler** [comment]
Sorry I have never done anything with RNNs, so I dont know the answer to this.

**Comment by xiaogehh** [comment]
I find the function `provide_data` is be defined but not using.

**Comment by jingpengw** [comment]
@xiaogehh I think the provide_data function was required and used by mxnet dataprovider. Whenever you create a new data iter, you need to define provide_data and provide_label function.

**Comment by xiaogehh** [comment]
@jingpengw  Actually,it's not be very important weather it exists. I make a custom iter and find we only provide the next() function,then mxnet will return a Databatch object. Then we can feed this data to net

**Comment by jingpengw** [comment]
@xiaogehh It sounds like not consistent with the documentation. Maybe I am just out-dated. Anyway, good to know. Thanks.

**Comment by xiaogehh** [comment]
@jingpengw  You are welcome~

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by yzhliu** [comment]
Since we now have NDArrayIter support HDF5, looks like the original issue has been resolved. Feel free to reopen if you still have problem loading HDF5 format data.
