### ISSUE TITLE
There are 2 "install" pages of the Mac OS and this is confusing

### ISSUE THREAD

**Issue by b0noI** [apache/incubator-mxnet#6877]
Search request "install MxNet on Mac OS" shows, at least for me, following 2 pages as the top results:

- mxnet.io/get_started/osx_setup.html -  Installing MXNet on OS X (Mac)
- mxnet.io/get_started/install.html - Installing MXNet 

Even though both of them states "Installing MXNet" one of the page is actually about compiling MxNet from sources and only second one is about actual installation. IMHO first page need to be renamed to something like:
"installing MXNet from source" or "compiling MxNet from source"

**Comment by piiswrong** [comment]
@sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
We need to remove the first page. This is redundant. mxnet.io/get_started/install.html  is the latest and greatest.
Will create a PR for this.

**Comment by b0noI** [comment]
grep -r "osx_setup" ./docs/*
./docs/get_started/install.md:Follow the installation instructions [in this guide](./osx_setup.md) to set up MXNet.
./docs/tutorials/scala/mxnet_scala_on_intellij.md:- The MXNet package for Scala. For installation instructions, see [this procedure](http://mxnet.io/get_started/osx_setup.html#install-the-mxnet-package-for-scala).

it is actually been used, here: http://mxnet.io/get_started/install.html , if you select MacOS and Scala it will show the link to the compiling from source (mxnet.io/get_started/osx_setup.html ). Probably renaming, for now is the best option and when Scala page is ready we can remove it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
