### ISSUE TITLE
kvstore_dist_server.h remove memcopy when Pull

### ISSUE THREAD

**Issue by Jianghi** [apache/incubator-mxnet#6887]
the diff is below
diff --git a/src/kvstore/kvstore_dist_server.h b/src/kvstore/kvstore_dist_server.h
index 02d4a38..441522d 100644
--- a/src/kvstore/kvstore_dist_server.h
+++ b/src/kvstore/kvstore_dist_server.h
@@ -212,8 +212,7 @@ class KVStoreDistServer {
       int len = stored.shape()[0];
       response.keys = req_data.keys;
       response.lens = {len};
-      // TODO(mli) try to remove this CopyFrom
-      response.vals.CopyFrom(static_cast<const float*>(stored.data().dptr_), len);
+      response.vals = ps::SArray<real_t>(static_cast<const float*>(stored.data().dptr_), len, false);
       server->Response(req_meta, response);
     }
   }

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
