### ISSUE TITLE
distributed mxnet is too slow when parameter size are increased

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#6888]
As input are sparse feature, the total parameters are 1.3G , the speed of distributed trainning are too slow.So mxnet can't support large parameters?

**Comment by formath** [comment]
https://github.com/dmlc/mxnet/issues/5498 sparse tensor is in development

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
