### ISSUE TITLE
Does the speech_recognition example OK with warp-ctc now?

### ISSUE THREAD

**Issue by xinq2016** [apache/incubator-mxnet#6890]
@piiswrong, @sbodenstein，
Does the speech_recognition example OK with warp-ctc now?

Many thanks

**Comment by piiswrong** [comment]
see if this fix works: https://github.com/dmlc/mxnet/pull/6905

**Comment by Soonhwan-Kwon** [comment]
@piiswrong @sbodenstein  @piiswrong I tested speech_recognition from lastest build, it works well.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
