### ISSUE TITLE
OpWrapperGenerator.py fails

### ISSUE THREAD

**Issue by smissan** [apache/incubator-mxnet#6895]
OpWrapperGenerator.py in c++ backend fails:

mxnet/cpp-package/scripts$ python OpWrapperGenerator.py
Traceback (most recent call last):
 File "OpWrapperGenerator.py", line 405, in <module>
   raise(e)
IndexError: list index out of range

**Comment by CNevd** [comment]
```OpWrapperGenerator.py``` needs one argument libmxnet.so, you can run  ```python OpWrapperGenerator.py ../../lib/libmxnet.so```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
