### ISSUE TITLE
a strange ndarray.asscalar time cost problem 

### ISSUE THREAD

**Issue by vikingMei** [apache/incubator-mxnet#6914]
hi, I'm using RNN to train language model on PTB[(code here)](https://github.com/dmlc/mxnet/tree/master/example/rnn) with K20, the time cost of a batch is about **26s**, after profiling, I found that metric.update take about **25s**, about 96% of total. 

with some print and compare, I found the key problem is:   ` loss.asscalar()`, which copy data from GPU to CPU memory, and the under engine function is `NDArray::SyncCopyToCPU`, and the most time consuming function is `Wait_To_Read`

so, is this a normal performance?

if this is normal, then another strange problem is time cost of save parameters to file, which is only **0.2s**, obviously, save parameter need copy data to CPU also, then, what's the difference of those two scenes???

tks for any help

to reproduce this problem, just add a break [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L632)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
