### ISSUE TITLE
ImportError: You used to compile with protoc --python_out=./ ./caffe.proto

### ISSUE THREAD

**Issue by meanmee** [apache/incubator-mxnet#6917]
I am trying to convert a caffe model to mxnet model using conver_model.py provided by mxnet/tools/caffe_converter.But the following error raised, I googled it but seems no one has the problem same to me. Can anyone solve it? thanks vvery much!

Traceback (most recent call last):
  File "convert_model.py", line 6, in <module>
    import caffe_parser
  File "/home/wuxiaomin/anaconda2/lib/python2.7/site-packages/mxnet/tools/caffe_converter/caffe_parser.py", line 12, in <module>
    raise ImportError('You used to compile with protoc --python_out=./ ./caffe.proto')
ImportError: You used to compile with protoc --python_out=./ ./caffe.proto

MXNet version: pip install mxnet-cu80

**Comment by joey2014** [comment]
to solve it:
cd /home/wuxiaomin/anaconda2/lib/python2.7/site-packages/mxnet/tools/caffe_converter
make

**Comment by miraclewkf** [comment]
@joey2014 It still has the error information: ImportError: You used to compile with protoc --python_out=./ ./caffe.proto

**Comment by YoWhatever** [comment]
@miraclewkf Have U solved that? And how?

**Comment by lanking520** [comment]
Close this issue due to the inactivity. Currently we have full support on ONNX where you can translate your model to this type and used in MXNet. Please feel free to reopen it if you are still facing the problems or would like to improve the script.
