### ISSUE TITLE
mxnet R 3.4 installation for CentOS release 6.9 (Final)

### ISSUE THREAD

**Issue by kgnsflint96** [apache/incubator-mxnet#6918]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: CentOS release 6.9 (Final)

Compiler: gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)

Package used (Python/R/Scala/Julia): R

MXNet version: 0.10

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide 3.4

R `sessionInfo()`:
> sessionInfo(package=NULL)
R version 3.4.0 (2017-04-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] drat_0.1.2     compiler_3.4.0 tools_3.4.0

## Error Message:
Please paste the full error message, including stack trace.
Warning message:
package ‘mxnet’ is not available (for R version 3.4.0)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. From R console I entered the following commands:
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")
2.
3.

## What have you tried to solve it?

1. Attempted to install from source and received the following error message when running the make rpkg command:

mkdir -p R-package/inst
mkdir -p R-package/inst/libs
cp -rf lib/libmxnet.so R-package/inst/libs
mkdir -p R-package/inst/include
cp -rf include/* R-package/inst/include
cp -rf dmlc-core/include/* R-package/inst/include/
cp -rf nnvm/include/* R-package/inst/include
echo "import(Rcpp)" > R-package/NAMESPACE
echo "import(methods)" >> R-package/NAMESPACE
R CMD INSTALL R-package
make[1]: Entering directory `/root/mxnet/R-package/src'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/mxnet/R-package/src'
No man pages found in package  ‘mxnet’
Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/lib64/R/library/mxnet/libs/libmxnet.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted

2.
3.

**Comment by thirdwing** [comment]
As we said, the `drat` repo is for Windows and OSX users. On Linux, you need to compile from source.

From your error log:
> libopenblas.so.0: cannot open shared object file: No such file or directory
I think you need to check your openblas installaton.
