### ISSUE TITLE
Is SyncCopyToCPU really thread-safe？

### ISSUE THREAD

**Issue by zhangxiao-ustc** [apache/incubator-mxnet#6920]
In `mxnet::NDArray::SyncCopyToCPU`, it calls `WaitToRead` at first and then do the copy. However, I was just wondering whether the src data would be changed during the copy. Because there is no mechanism to prevent src from being changed by other operation which may be pushed into
engine and executed after the call of `WaitToRead`.

**Comment by tqchen** [comment]
if the code is only issued from a single python script, it is fine, because all the write ops before wait to read is issued, and the followups write won't issue until synccopy  finish

**Comment by zhangxiao-ustc** [comment]
thx, if the assumption is true, this explanation sounds reasonable. : )

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
