### ISSUE TITLE
predict(model, val) produces fewer number of samples compared to original sample size

### ISSUE THREAD

**Issue by lichen11** [apache/incubator-mxnet#6945]
I have noticed a puzzling phenomenon. Every time I predict on a rec file, the number of samples becomes fewer and fewer. 
Let's say train and val are the rec files generated by im2rec.py. Suppose the model is trained as follows.
model <- mx.model.FeedForward.create(
  symbol             = new_soft,
  X                  = train,
  #eval.data          = val, I removed this part as it's optional and will use val for validation outside. 
  ctx                = mx.gpu(0),
  eval.metric        = mx.metric.accuracy,
  num.round          = 1,
  learning.rate      = 0.05,
  momentum           = 0.9,
  wd                 = 0.00001,
  kvstore            = "local",
  array.batch.size   = 128,
  epoch.end.callback = mx.callback.save.checkpoint("my_model"),
  batch.end.callback = mx.callback.log.train.metric(150),
  initializer        = mx.init.Xavier(factor_type = "in", magnitude = 2.34),
  optimizer          = "sgd",
  arg.params         = arg_params_new,
  aux.params         = inception_bn$aux.params
)
probs = predict(model, val)
The first time I executed this command, ncol(probs) is the correct number of validation size. 
The second time I execute the command, ncol(probs) has 98 less number of samples compared to the correct validation size.
The third time I execute the command, ncol(probs) has 189 less number of samples compared to the correct validation size. 
I believe ncol(probs)'s size should be the same as the validation size no mater how many times I run the predict command. Can you help explain what went wrong here or what I can do to ensure I get the correct number of samples back. Thanks!

**Comment by thirdwing** [comment]
Please show a reproducible example. We don't know what `train` is.

**Comment by thirdwing** [comment]
Can you show your system information?

I can't reproduce your error on my Linux machine:

```r
> pred <- predict(model, val_iter)
> dim(pred)
[1]   2 400
> pred <- predict(model, val_iter)
> dim(pred)
[1]   2 400
> pred <- predict(model, val_iter)
> dim(pred)
[1]   2 400
```
