### ISSUE TITLE
question about LinearRegressionOutput operator

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#6948]
I use the LinearRegressionOutput operator as the final layer of the net but it seems not work. A simple code like this:
```
import mxnet as mx

a = mx.nd.array([[1,0,0],[0,1,0]])

b = mx.nd.array([[1,0,0],[0,1,0]])

c = mx.nd.LinearRegressionOutput(data=a,label=b)

c
Out[5]: <NDArray 2x3 @cpu(0)>

c.asnumpy
Out[6]: <bound method NDArray.asnumpy of <NDArray 2x3 @cpu(0)>>

c.asnumpy()
Out[7]: 
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]], dtype=float32)
```  
It's strange and I'm confused.

**Comment by CNevd** [comment]
c is the output of forward propagation, it's itself for LinearRegression
see [RegressionOutputOp](https://github.com/dmlc/mxnet/blob/master/src/operator/regression_output.cc#L17)

**Comment by Godricly** [comment]
[`LinearRegressionOutput`](http://mxnet.io/api/python/symbol.html#mxnet.symbol.LinearRegressionOutput) 
The forward pass is an identical mapping. Go checking the gradient value.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
