### ISSUE TITLE
support converting caffe mtcnn and mobilenet model

### ISSUE THREAD

**Issue by joey2014** [apache/incubator-mxnet#6950]
current convert tool has issues to support converting caffe mtcnn and mobilenet model, I made patch for [group symbols](https://github.com/mview/mxnet-samples/commit/f7d89cdb150bb1ee628bff49fb76ae0b25931d40)  and  [BatchNorm] (https://github.com/mview/mxnet-samples/commit/a8ec4bbde5a0bcdd6ded6d3c0eb7eae753e767a0)

detail document see [write mtcnn c++ version code for mxnet](https://zhuanlan.zhihu.com/p/27725063)  and  [test MobileNet model under mxnet](https://zhuanlan.zhihu.com/p/27734639).

Can you help check if it's possible to  add support the two models by converting caffe models?

**Comment by piiswrong** [comment]
Would you like to submit a PR

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
