### ISSUE TITLE
A possible bug due to lacking synchronization after Copy

### ISSUE THREAD

**Issue by AIROBOTAI** [apache/incubator-mxnet#6953]
In the code of `src/operator/softmax_output-inl.h`, I think there might be a bug [in this line](https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L160). This line aims to copy the contents in `label` to `workspace`. However, since in the case that `label` resides in gpu, the copy is asynchronous w.r.t the host, shouldn't there be a synchronize sentence after this line, e.g. `cudaStreamSynchronize(label.stream_)` to do synchronization? Otherwise, I think unexpected error may occur [here](https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L163) where the content of `workspace` is used.

Any comments? Thanks a lot!

**Comment by piiswrong** [comment]
@tornadomeet

**Comment by AIROBOTAI** [comment]
Any update? @tornadomeet @piiswrong

**Comment by AIROBOTAI** [comment]
Could anyone look into this problem?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
