### ISSUE TITLE
improve speed of training 

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#6963]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Compiler:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Package used (Python/R/Scala/Julia):
python2.7.6

MXNet version:
Or if installed from source:
'0.10.1'

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

No error message but mxnet is slow

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
```
python /src/mxnet/example/image-classification/train_imagenet.py --benchmark 1  --num-epochs 1 --gpus 0 --network inception-v3 --batch-size 16   --image-shape 3,299,299 --num-epochs 1 --kv-store device

INFO:root:start with arguments Namespace(batch_size=16, benchmark=1, data_nthreads=4, data_train=None, data_val=None, disp_batches=20, dtype='float32', gpus='0', image_shape='3,299,299', kv_store='device', load_epoch=None, lr=0.1, lr_factor=0.1, lr_step_epochs='30,60', max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='inception-v3', num_classes=1000, num_epochs=1, num_examples=1281167, num_layers=50, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, wd=0.0001)
[06:29:08] src/operator/././cudnn_algoreg-inl.h:65: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [20]	Speed: 14.66 samples/sec	accuracy=0.726190
INFO:root:Epoch[0] Batch [40]	Speed: 14.66 samples/sec	accuracy=1.000000
INFO:root:Epoch[0] Train-accuracy=1.000000
INFO:root:Epoch[0] Time cost=54.575
```
I am running the code on an amazon ec2 instance: EC2 g2.2xlarge

the reported speed using K80 (single GPU,  EC2 p2.2xlarge) is ~28 images/sec (http://mxnet.io/how_to/perf.html)
 which is double the speed. Is there any configuration I should do to speed up my code?

## What have you tried to solve it?

1. installed opencv with_cuda=off
2.
3.

**Comment by great-thoughts** [comment]
I will appreciate if someone can tell me if the speed I am getting is as expected.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
