### ISSUE TITLE
How to do Xavier initialization on specific convolutional layer

### ISSUE THREAD

**Issue by coolbrain** [apache/incubator-mxnet#6964]
I define a convolution in caffe prototxt file
layer {
  name: "rpn_conv/3x3"
  type: "Convolution"
  bottom: "conv5_3"
  top: "rpn_conv/3x3"
  param { lr_mult: 1.0 }
  param { lr_mult: 2.0 }
  convolution_param {
    num_output: 384
    kernel_size: 3 pad: 1 stride: 1
    weight_filler { type: "gaussian" std: 0.01 }
    bias_filler { type: "constant" value: 0 }
  }
}
So I initilize this layer in Mxnet:
arg_params['rpn_conv_3x3_weight'] = mx.random.normal(0, 0.01, shape=arg_shape_dict['rpn_conv_3x3_weight'])
        arg_params['rpn_conv_3x3_bias'] = mx.nd.zeros(shape=arg_shape_dict['rpn_conv_3x3_bias'])

But when the weight filler is like { type: "xavier"}， I read the Mxnet initilize document, but I can't figure it out how to initilize this layer by xavier as the above way.

**Comment by CNevd** [comment]
```
initializer=mx.init.Xavier(factor_type="in", magnitude=2.34)
initializer(mx.init.InitDesc('rpn_conv_3x3_weight'),arg_params['rpn_conv_3x3_weight'])
```

**Comment by coolbrain** [comment]
Thanks, @CNevd  it works.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
