### ISSUE TITLE
install previously released version

### ISSUE THREAD

**Issue by mtbui2010** [apache/incubator-mxnet#6969]
Hi,
I want to manually install mxnet 0.9.5  on an ubuntu system.
But, the git in https://github.com/dmlc/mxnet/releases/tag/v0.9.5 may lack of several required package such as, cud, dmlc-core, mshadow, nnvm, ps-lite.
Therefore, I have tried download these packages from the most current version in https://github.com/dmlc/mxnet/tree/master/.
But, when I typed 'make'. The error showed up.
Would you please guide me how to install mxnet 0.9.5 manually?

**Comment by thirdwing** [comment]
```
git clone https://github.com/dmlc/mxnet.git
cd mxnet
git checkout v0.9.5
git submodule init
git submodule update
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
