### ISSUE TITLE
L2Normalization document is wrong

### ISSUE THREAD

**Issue by coolbrain** [apache/incubator-mxnet#6973]
L2Normalization document：http://mxnet.io/api/python/symbol.html#mxnet.symbol.L2Normalization

mxnet.symbol.L2Normalization(data=None, eps=_Null, mode=_Null, name=None, attr=None）

with mode = channel, it normalizes each channel in the array by its L2 norm
for i in 0...N
  out[:,i,:,...,:] = data[:,i,:,...,:] / sqrt(sum(data[:,i,:,...,:] ** 2) + eps)

with mode = spatial, it normalizes the cross channel norm for each position in the array by its L2 norm.:
for dim in 2...N
  for i in 0...N
    out[.....,i,...] = take(out, indices=i, axis=dim) / sqrt(sum(take(out, indices=i, axis=dim) ** 2) + eps)
        -dim-

I think argument mode=channel and mode=spatial should be reversed.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
