### ISSUE TITLE
Reuse feature extractor for multiple inputs

### ISSUE THREAD

**Issue by conansc** [apache/incubator-mxnet#6979]
Hey,
I would like to use AlexNet to extract features from my images. Then I want to pass those features  into a RNN. My problem is that I first want to extract the features from 5 images and then pass all extracted features to the RNN. The important thing here is that I want to reuse the feature extractor for every image, so I don't need to have AlexNet five times in my network.

Is it possible to do that? How can I define the network so that I pass 5 different images through the same feature extractor and then pass everything to the RNN?

Thanks in advance,
Best,
Sebastian

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
