### ISSUE TITLE
Help implementing multiple instance (bag) learning with MXNet

### ISSUE THREAD

**Issue by jmerkow** [apache/incubator-mxnet#6984]
I am attempting to implement bag learning with MXNet but I am running into an issue with executor_group.

Code:
```
num_classes = 2
batch_net = mx.sym.Variable('data')
batch_net = mx.sym.FullyConnected(data=batch_net, name='fc1', num_hidden=64)
batch_net = mx.sym.Activation(data=batch_net, name='relu1', act_type="relu")
batch_net = mx.sym.FullyConnected(data=batch_net, name='fc2', num_hidden=num_classes)
batch_net = mx.sym.softmax(data=batch_net, name='img_scores')

MIL = mx.symbol.reshape(batch_net, shape=[1, num_classes, -1], name='MI_reshape')
MIL = mx.symbol.Pooling(MIL, global_pool=True, name='MI_score', kernel=(2), pool_type='max')
MIL = mx.sym.Flatten(MIL, name='MI_flat')
net = mx.symbol.SoftmaxOutput(MIL, name='softmax')
```

I have a DataIter that provides:
```
[('data', (32, 1, 224, 224))], [('softmax_label', (1,))]
```

```
data_names = ['data']
label_names = ['softmax_label']
devices = mx.gpu()
mod = mx.module.Module(net, data_names=data_names, label_names=label_names,
                    context=devices)
mod.fit(data, num_epoch=10)
```

I get this error:
```
AssertionError: all data must have the same batch size: batch_size = 32, but softmax_label has shape (1,)
```

This error a raises from [decide_slices](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py#L216) called [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py#L296)

Im looking for suggestions on a solution/workaround for this.  My first idea is to create a new module that takes 2 symbols.  One for the regular single instance network and the second for the multiple instance network then pass gradients/data between.  I was hoping there was a solution that was less involved though.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
