### ISSUE TITLE
sharedctypes for ndarray

### ISSUE THREAD

**Issue by jonasteuwen** [apache/incubator-mxnet#6987]
In my data iterator, I want to fill an array with multiple threads.

Right now, the code fill
```
def next(self):
        <snip>
        i = 0
        try:
            while i < batch_size:
                image, bbox = self.next_image()
                label = 1 if bbox else 0
                data = self.get_patch(image, bbox)
                batch_data[i][:] = self.postprocess_data(data)
                batch_label[i][:] = mx.nd.array([label])
                i += 1

        except StopIteration:
            raise StopIteration
```
If I would do this in parallel with numpy I would write the data to a `sharedctypes.RawArray` and when done apply the function `np.ctypeslib.as_array()` to this. What is the right way to do this in mxnet? 

I could write it to a numpy array, but, if I understand correctly, this would mean the data is copied once I apply `mx.nd.array` and I just want to use the reference.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
