### ISSUE TITLE
Axis selection for Sequence* operators

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#6994]
Currently, all Sequence* operators (Sequence{Reverse,Mask,Last}) require time-major input data, that is (time, batch, depth). In some networks, this enforces users to do a lot of transpositions/reshapes to apply these operators, which are crucial for some use cases (variable-length seq2seq models).

It would be great if these operators would support an axis argument, that defaults to 0:
```
# input: (batch, time, depth)
# length: (batch,)
output = mx.sym.SequenceReverse(data=input, axis=1, sequence_length=length, 
 use_sequence_length=True)
# output: (batch, time, depth)
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
