### ISSUE TITLE
Generalized batch_dot / matrix multiplication

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#6997]
Currently, mx.{nd,sym}.batch_dot is constrained to 3d input where the first dimension is considered the batch size.
It would be great to be able to have n-dimensional inputs to a matrix multiplication and do the matrix multiplication on the last two dimensions only. This avoids having to combine/split dimensions before and after.
Desired behavior:
```
# i1: (d1, ... dn, m, x)
# i2: (d1, ... dn, x, n)
out = mx.sym.batch_dot(lhs=i1, rhs=i2)
# out: (d1, ... dn, m, n)
```
The `transpose_*` flags would always only transpose the last two dimensions.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by nicklhy** [comment]
@fhieber , have you figured out a solution about this feature now?

**Comment by fhieber** [comment]
@nicklhy mxnet-0.12.0 added a `flatten` argument to FullyConnected. If set to `False`, you can pass in n-dimensional input and the matrix multiplication with the weight matrix is applied to the last two dimensions of your input.

I am not aware of any changes in batch_dot, so it probably is still constrained to 3d input (first dim being batch_size).
