### ISSUE TITLE
bgr or rgb input to vgg16?

### ISSUE THREAD

**Issue by yuconglin** [apache/incubator-mxnet#6999]
Hi Everyone:
    Should the input image to vgg16 model in mxnet (http://mxnet.io/model_zoo/) be bgr or rgb? The original caffe model supports bgr. I am not sure what is the case for mxnet.
    Thanks a lot!

**Comment by coolbrain** [comment]
I want to know this, too. Is the vgg16 model trained by mxnex or just converted from caffe model?

**Comment by edmBernard** [comment]
I think it's bgr as opencv convention.
when i use my model I keep opencv color order

**Comment by coolbrain** [comment]
But mxnet change as RGB in implementation.  Are you sure? @edmBernard

**Comment by edmBernard** [comment]
ho shit ... 
you are write in the exemple : http://mxnet.io/tutorials/python/predict_image.html
images are converted in RGB.

**Comment by coolbrain** [comment]
I had confirmed that VGG16 pre-trained model is directly converted from caffe model. In mxnet, the input channel of image is RGB, but BGR in caffe, so when converting the model, it adjusts the first convolution kernel sequence, so the result may be right.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
