### ISSUE TITLE
fatal: reference is not a tree: 89de7a...

### ISSUE THREAD

**Issue by seongkyun** [apache/incubator-mxnet#7004]
i just installed ubuntu 16.04 and try to install [MXNet@(commit 62ecb60)](https://github.com/dmlc/mxnet/tree/62ecb60) 

so

`git clone --recursive https://github.com/dmlc/mxnet.git`
`git checkout 62ecb60`
`git submodule update`

then it prints out

fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'

if i ignore that fatal error, then another error occurs during make operation

`make -j8`

it prints out

/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:242: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:264: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

please help me guyz   :)

**Comment by Soonhwan-Kwon** [comment]
```
git submodule update --recursive --remote
```
after check out may help

**Comment by oliverdain** [comment]
I think the issue is that, "with branch 1.7.0. We squashed all commits to avoid the huge .git folder." (from https://github.com/dmlc/cub) so the git hash recorded for the submodule no longer exists.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
