### ISSUE TITLE
Some unwise code in symbol.__getitem__ of symbol.py

### ISSUE THREAD

**Issue by BiranLi** [apache/incubator-mxnet#7005]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info

Package used (Python/R/Scala/Julia): python

MXNet version: 0.10

I found that the implementation of this code is not elegant enough.Code locate on function __getitem__
```python
if index >= (len(self.list_outputs())):
    # Important, python determines the end by this exception
    raise IndexError
```
It cost much time if output list is large.
In my opinion, use a directly member variable should be much better.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
