### ISSUE TITLE
Clarification about MKLML and MKL DNN

### ISSUE THREAD

**Issue by al-rigazzi** [apache/incubator-mxnet#7008]
Hello guys,

I've been using MXNet with MKLML and I was positively surprised by the outcome. I stumbled upon [the MKL-DNN github repo](https://github.com/01org/mkl-dnn) and I was  wondering what the connection is between MKLML and MKL DNN. On a related note, I looked for new distributions of MKLML and could not find anything, so I was wondering if the project has moved to DNN or what happened.

Thanks,
Al

**Comment by edmBernard** [comment]
It seem mxnet MKL installation use MKL DNN and not MKL 2017. https://github.com/apache/incubator-mxnet/blob/master/prepare_mkl.sh#L87

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@al-rigazzi Hi, are your still facing the issue?

**Comment by lanking520** [comment]
@nswamy  Please add 'Question' to this topic

**Comment by al-rigazzi** [comment]
@lanking520 no, now that MKLDNN is used as submodule, everything is simpler.
