### ISSUE TITLE
How to find the people who are not wearing helmet in the picture

### ISSUE THREAD

**Issue by laughsmile** [apache/incubator-mxnet#7018]
Hello everyone.

I know how to using image detection to find whether there is helmet or not in the picture,
but I don't know how to find whether there is someone without wearing helmet,  especially when there is another  wearing helmet in the picture.

Would you please tell me how to solve the problem?
Thanks in advance.
Ryu

Update
ーーーーーーーーーーーーーーーーーーーーーー
I have tried to train a model with my picture with and without helmet(about 100 images each), but the recognition rate is not good when using the trained model actually, sometimes the model can recognize well and sometimes it can NOT recognize correctly when my head moves. Are my images for training too few? Can the model be use to recognize the people without wearing helmet but another wearing helmet?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
