### ISSUE TITLE
R Character RNN program question

### ISSUE THREAD

**Issue by netmr** [apache/incubator-mxnet#7019]
Package used (Python/R/Scala/Julia): R
MXNet version: 0.10.0

This is not an issue of mxnet but my problem of trying to understand the basic Character RNN program.
The program in [http://mxnet.io/tutorials/r/charRnnModel.html] sets the following parameter values:

`batch.size = 32
seq.len = 32
num.hidden = 16
num.embed = 16
num.lstm.layer = 1`

My question is what are the dimensions of the variables "embed" and "wordvec" in lines 53 and 55 of the following program [https://github.com/dmlc/mxnet/blob/master/R-package/R/lstm.R]

As a general question, in R, how to check the internal variable values/dimensions in functions such as lstm.unroll()?

**Comment by thirdwing** [comment]
I think the best method to get the dimension is to write a small helper function. Just like we I did in the unit test https://github.com/apache/incubator-mxnet/blob/master/R-package/tests/testthat/test_img_seg.R#L5-L8

**Comment by netmr** [comment]
Thanks a lot!
