### ISSUE TITLE
training data resides in AWS s3

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#7021]
How can I modify the iterator in this example (https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/data.py) to read images from AWS s3. I have .png images in a folder in AWS s3. I tried passing the rootdir as s3://bucketname/folder. I have also tried to change the function that reads images from Image (by PIL) to imdecode (by mx.image). I had no luck in both cases. 
I have an image segmentation problem. my input is an image and my output is an image too.

**Comment by piiswrong** [comment]
You need to pack your images in recordio format to let mxnet read from s3 automatically.

Otherwise please follow s3 user guide.

**Comment by great-thoughts** [comment]
I used the functions described [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/recordio.py) to pack my images and labels in recordio format. The .rec file that I am getting is much bigger than the original dataset. My dataset is ~ 8GB and when I encode 1% of the data my .rec file would have a size of 2.3G

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
