### ISSUE TITLE
Ask : Tensorboard without fit function ?

### ISSUE THREAD

**Issue by Shiro-LK** [apache/incubator-mxnet#7024]
Hello,

I was wondering if it is possible to use tensor board if we use forward/backward/update function instead of fit function? I did not find an example about it.

**Comment by zihaolucky** [comment]
@Shiro-mx check this https://github.com/dmlc/tensorboard/tree/master/tests/python

**Comment by Shiro-mx** [comment]
@zihaolucky  thank for the help that's what I needed. I will try it.

**Comment by zihaolucky** [comment]
@Shiro-mx :)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
