### ISSUE TITLE
How to fix the random seed?

### ISSUE THREAD

**Issue by AIROBOTAI** [apache/incubator-mxnet#7025]
Is there a method to fix the random seed in mxnet, in order to produce same results in each run?

**Comment by vikingMei** [comment]
find the random method is come from `import random` or `np.random`, and call correspond seed function, or you can use below for both(at the begin of code)
```python
import random
import numpy as np

if '__main__'==__name:
    random.seed(0)
    np.random.seed(0)

    # other codes
```

if the result is not what you want, find call code that call random.*, comment what's commentable

if you are using *unix, this command may be useful
```shell
grep -R . -e 'random' --exclude-dir data $(find . -name '*.py')
```

some other tips:
1. change DataIter's next function, make it alway generate same samples every time
1. change the batch_size to 1 if neccessary

**Comment by eric-haibin-lin** [comment]
Also `mx.random.seed(12)`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
