### ISSUE TITLE
How to switch a layer to cpu mode while the other layers are in gpu mode.

### ISSUE THREAD

**Issue by horserma** [apache/incubator-mxnet#7034]
Hi,
I found the layer I implemented in cpu mode is working fine, but got "segmentation fault" in gpu mode. I guess it is just because there is some difference between gpu memory and cpu memory in terms of operations. Is there any way that I only use cpu mode for this single layer and keep the other layers in gpu mode. Thank you very much

**Comment by eric-haibin-lin** [comment]
You can try the `ctx2group` option during simple_bind(). For example, if you want to specify a layer on cpu among the gpu layers,
```
a = mx.sym.var("a")
b = mx.sym.var("b")
with mx.AttrScope(ctx_group="cpu"):
    c = mx.sym.sample_negative_binomial(a,b) # runs on cpu
d = mx.sym.dot(a, c) # runs on gpu

executor = d.simple_bind(ctx=mx.gpu(), a=(10,), b=(10,), group2ctx={"cpu": mx.cpu()})
```
allows `sample_negative_binomial` to be on cpu while the rest on gpu. 

Caveat: there's a known bug for elemwise_add with group2ctx https://github.com/apache/incubator-mxnet/issues/7080

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
