### ISSUE TITLE
The output layer name 'flatten0' automatically changed to 'flatten1' when get network twice?

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#7039]
I use get_net func to get inception network twice. However, the flatten layer name is 'flatten0_output', and the second time the flatten layer name is 'flatten1_output'.

I don't know why it is changed. How can i keep the name of these output layers stable when i get the network twice?

---

first time output:
['global_pool_output', 'flatten0_output', 'fullyconnected0_weight', 'fullyconnected0_bias', 'fullyconnected0_output', 'softmax_label', 'softmax_output']

second time output:
['global_pool_output', 'flatten1_output', 'fullyconnected1_weight', 'fullyconnected1_bias', 'fullyconnected1_output', 'softmax_label', 'softmax_output']

**Comment by piiswrong** [comment]
You can use name='xxx' to give a name to it

**Comment by universewill** [comment]
OK.  But why let the name of layers change automatically if it is not given a name? @piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
