### ISSUE TITLE
C/C++ API: Get updated weights/args/params from Symbol?

### ISSUE THREAD

**Issue by NiklasTreutner** [apache/incubator-mxnet#7052]
Hi,

i'd like to access the updated weights during training. Following the LeNet-example, if i just access the args_map i used to initialize the Net (e.g. args_map["conv1_w"] ), the weights don't get updated from iteration to iteration (although training works and the output changes). that's probably because the actual symbol-bound weights on the gpu-context aren't synced to the weights that were used to initialize.

How can I "download" or update the current weights (along the lines of "get_params" for a model), if i only have the currently trained symbol?

I'm not entirely sure if i completely understand all connections between NDArrays, Symbols and Models (e.g. how can i "turn" a trained stack/group of symbols into a model?), so i'd be thankful for all advice.

Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
