### ISSUE TITLE
Any plan to have NTM?

### ISSUE THREAD

**Issue by machuck** [apache/incubator-mxnet#7058]
Is there a plan to develop a NTM (neural turing machine)? I am looking forward to seeing it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
