### ISSUE TITLE
Project Ideas: Provide additional prebuilt Windows binaries

### ISSUE THREAD

**Issue by viper7882** [apache/incubator-mxnet#7061]
Hi @piiswrong 

I'm using both Windows (32-bit and 64-bit) and Linux Operating Systems (UBuntu and Debian) to run MXNet. I've found out that the installation steps for Linux Operating Systems are generally straight forward and easy to automate. Whereas for Windows, it is quite a challenge to build MXNet and the decision I've made was to install prebuilt 64-bit binaries. Currently I'll need to switch to 32-bit Windows and the prebuilt binaries aren't available for 32-bit.

Looking at the number of build issues reported in the Issues like, I don't see how this trend would be reduced.

The existing working model for new MXNet release is:
1. Besides using prebuilt binaries, whenever there is a new version, both MXNet developers and users are expected to build from scratch.
2. MXNet user will have to invest time and efforts into debugging any compilation failure due to the new version.
3. It is time consuming for MXNet users to go through this hassle, debug, report and wait for the official support from this forum.

One improvement opportunity I would like to propose is for MXNet to provide more prebuilt binaries where:
1. Only core MXNet developers will require to build from the source code.
2. MXNet released official prebuilt binaries once for all supported major platforms once.
3. User will only have to pick up the necessary prebuilt binary targeting their platform.
4. Issue found is consistent across MXNet users and chances are the fix will be introduced in the coming prebuilt binaries.

To clarify, I am suggesting MXNet to release official prebuilt binaries including Windows 32-bit as well? It would be great if there are other prebuilt binaries for major Linux platforms as well (RPM, DEB etc.).

Compiler:
Package used, with version and distribution: Python 2.7
MXNet version: 0.10.0
MXNet commit hash (`git rev-parse HEAD`): I'm not using git for Windows.

**Comment by viper7882** [comment]
Another thing, are instructions listed in http://mxnet.io/get_started/windows_setup.html still valid? I found out that many steps are no longer valid. E.g.
1. Visual Studio 2013 is no longer available in the Microsoft Visual Studio website.
2. There is no troubleshooting guide for failure encountered as well. Mostly related to cmake error as well as OS-specific issue, such as Windows 10.

**Comment by viper7882** [comment]
By cloning the latest MXNet git, as anticipated, building MXNet from source produces the following error messages:
`1>c_api.obj : error LNK2019: unresolved external symbol "public: static class dmlc::Stream * __cdecl dmlc::Stream::Create(char const *,char const * const,bool)" (?Create@Stream@dmlc@@SAPAV12@PBDQBD_N@Z) referenced in function _MXNDArrayLoad
1>iter_image_det_recordio.obj : error LNK2001: unresolved external symbol "public: static class dmlc::Stream * __cdecl dmlc::Stream::Create(char const *,char const * const,bool)" (?Create@Stream@dmlc@@SAPAV12@PBDQBD_N@Z)
1>iter_image_recordio.obj : error LNK2001: unresolved external symbol "public: static class dmlc::Stream * __cdecl dmlc::Stream::Create(char const *,char const * const,bool)" (?Create@Stream@dmlc@@SAPAV12@PBDQBD_N@Z)
1>c_api_symbolic.cc.obj : error LNK2001: unresolved external symbol "public: static class dmlc::Stream * __cdecl dmlc::Stream::Create(char const *,char const * const,bool)" (?Create@Stream@dmlc@@SAPAV12@PBDQBD_N@Z)
1>c_api.obj : error LNK2019: unresolved external symbol "public: void __thiscall dmlc::RecordIOWriter::WriteRecord(void const *,unsigned int)" (?WriteRecord@RecordIOWriter@dmlc@@QAEXPBXI@Z) referenced in function _MXRecordIOWriterWriteRecord
1>c_api.obj : error LNK2019: unresolved external symbol "public: bool __thiscall dmlc::RecordIOReader::NextRecord(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?NextRecord@RecordIOReader@dmlc@@QAE_NPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function _MXRecordIOReaderReadRecord
1>pooling.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>convolution.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>convolution_v1.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>lrn.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>mkl_memory.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>attach_op_execs_pass.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>activation.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>batch_norm.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>concat.obj : error LNK2001: unresolved external symbol _dnnLayoutGetMemorySize_F32
1>pooling.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>convolution.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>convolution_v1.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>lrn.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>mkl_memory.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>attach_op_execs_pass.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>activation.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>batch_norm.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>concat.obj : error LNK2001: unresolved external symbol _dnnAllocateBuffer_F32
1>pooling.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
1>convolution.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
1>convolution_v1.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
1>lrn.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
1>mkl_memory.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
1>attach_op_execs_pass.obj : error LNK2001: unresolved external symbol _dnnReleaseBuffer_F32
`

I do not expect someone to help fixing these errors for me. The issue I would like to highlight is that how awesome is it if MXNet could release a prebuilt Windows 32 binaries so that no one else will have to troubleshoot MXNet build issue.

**Comment by szha** [comment]
@sandeep-krishnamurthy

**Comment by szha** [comment]
We now have windows pip packages thanks to the joint work by @yajiedesign and @zhreshold. Thanks guys!
