### ISSUE TITLE
Is there any tutorial on how to write data loader in C++ which uses RecordIO API?

### ISSUE THREAD

**Issue by squidszyd** [apache/incubator-mxnet#7066]
As title. I only found various implementation in `src/io`, but feel confused with the APIs

**Comment by madjam** [comment]
AFAIK, there isn't a C++ tutorial.
Are you trying to read records from a file in recordio format from C++?
Have you looked at how the python binding is implemented? https://github.com/dmlc/mxnet/blob/master/python/mxnet/recordio.py

It simply delegates to the appropriate C++ API calls.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
