### ISSUE TITLE
How can I generate my own float data?

### ISSUE THREAD

**Issue by acone2003** [apache/incubator-mxnet#7068]
I wanna train a CNN using my float data, which has 1.2million samples and 57600*6 per sample. How can I generate the data file for MxNet? I wanna generate it using my another C++ program, without any MxNet functions. What's the simplest file format?

**Comment by piiswrong** [comment]
try csv and mxnet.io.CSVIter

**Comment by acone2003** [comment]
I think csv isn't a good method. it is about 1.5TB in bin mode.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
