### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CaffeOp'

### ISSUE THREAD

**Issue by El-H** [apache/incubator-mxnet#7070]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc 4.8.5

Package used (Python/R/Scala/Julia): Python

MXNet version: latest

Or if installed from source: installed from GitHub 

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Traceback (most recent call last):
  File "caffe_net.py", line 104, in <module>
    net = get_lenet()
  File "caffe_net.py", line 32, in get_lenet
    conv1 = mx.symbol.CaffeOp(data_0=data, num_weight=2, prototxt="layer{type:\"Convolution\" convolution_param { num_output: 20 kernel_size: 5 stride: 1} }")
AttributeError: 'module' object has no attribute 'CaffeOp'

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. cd mxnet/example/caffe/
2. python caffe_net.py 
3.

## What have you tried to solve it?

1. carefully recompile caffe and mxnet by following the instruction, but still shows this error.
2.
3.

**Comment by ChidanandKumarKS** [comment]
Iam also getting the same error... Any solution to this problem...?

**Comment by piiswrong** [comment]
You need to compile with caffe plugin to enable Caffeop

**Comment by El-H** [comment]
@piiswrong Thanks for replying! Do you mean uncomment the two line in config.mk? Cause I have already done this.

**Comment by ChidanandKumarKS** [comment]
Already enabled
CAFFE_PATH = /home/chidanand/Softwares/MXNET_CAFFE_Integration/caffe-enet/
MXNET_PLUGINS += plugin/caffe/caffe.mk

getting the same error. Any suggestions would be helpful.

**Comment by piiswrong** [comment]
Did you make clean and make again after enabling it?

**Comment by ChidanandKumarKS** [comment]
Yeah I did multiple times make clean && make . Still the same attribute error caffeop not found. Kindly suggest how to proceed since Ian not able to move further

**Comment by ChidanandKumarKS** [comment]
@piiswrong , any updates on this issue since i got stuck at this problem.

**Comment by piiswrong** [comment]
@cjolivier01 @sandeep-krishnamurthy

**Comment by ChidanandKumarKS** [comment]
@piiswrong , @cjolivier01 @sandeep-krishnamurthy, any updates on this issue?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by wangshuailong** [comment]
I had the same problem minutes ago, it turned out that I set the wrong environment path which was still the old mxnet version .... 
Now it's working after I corrected it ... Just for others as reference.
