### ISSUE TITLE
Does anyone know PVAnet? How to configure its CRelu structure using mxnet

### ISSUE THREAD

**Issue by lcwyylcwyy** [apache/incubator-mxnet#7074]
The pvanet is proposed in https://github.com/sanghoon/pva-faster-rcnn
It use caffe to train and infer.
Like title, I want to know how to implement the CRelu structure.
The structure is that
Conv->bn->concat(bn, -bn)->scale->Relu
How to configure it?
Should I use fix_gamma parameter?

**Comment by lcwyylcwyy** [comment]
how to transfer caffe scale layer to mxnet symbol?

**Comment by qingzhouzhen** [comment]
Hi, have you finished PVAnet on mxnet? I am interested on it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
