### ISSUE TITLE
 integer divide by zero

### ISSUE THREAD

**Issue by soraphis** [apache/incubator-mxnet#7077]
edit: 

    net = ConvFactory(data=net, kernel=(1, 1), num_filter=1, stride=1)

results in 

    OSError: exception: integer divide by zero

and can be fixed with:

    net = ConvFactory(data=net, kernel=(1, 1), num_filter=1, stride=(1,1))

took me a while

**Comment by soraphis** [comment]
found the error, updated the issue

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
