### ISSUE TITLE
How to implement  logistical regression with unknown feature count?

### ISSUE THREAD

**Issue by zhangjing** [apache/incubator-mxnet#7087]
Hi

After reading through the tutorials & howto& architechture , I still cann't find solution of my problem.
My problem can be simplified as follow:
  1. I want to implement a logistical regresion for online learning  (it seems https://github.com/dmlc/mxnet/issues/1840  give the answer)
  2. I can not get the feature count , because the feature unseen before will be produced

Thx
Jing

**Comment by formath** [comment]
Problem 2: use feature hash

**Comment by zhangjing** [comment]
thx @formath 
we have applied feature hash ~
The question is  how to intergrate hashed feature into mxnet?

**Comment by zhangjing** [comment]
But the hash space will be very large , then use sparse tensor??

**Comment by eric-haibin-lin** [comment]
@zhangjing you can use sparse tensor https://mxnet.incubator.apache.org/versions/master/tutorials/sparse/train.html 
Closing it for now. For further questions/comments please post it on https://discuss.mxnet.io/
