### ISSUE TITLE
Feed data into intermediate layer in forward pass

### ISSUE THREAD

**Issue by msbauer** [apache/incubator-mxnet#7090]
Is there a way to feed data into an intermediate symbol in the forward pass without constructing a new graph, similar to how you can use a feed_dict in tensorflow to feed data into every node of the computation graph?

I.e., conceptually, I would like to do something like this:
```
A=mx.sym.Variable('A')
B=mx.sym.Variable('B')
C=mx.sym.add_n(A, B, name='C')
D=mx.sym.Variable('D')
E=C*D
executor=E.bind(mx.cpu(), {'C':mx.nd.array([2]), 'D':mx.nd.array([3])})
```

My use case is a pretrained network, for which I would like to compute a forward pass for either a new input X or some feature representation at an intermediate layer (which might come from another network or some processed representation.

I presume there should be some way to do this; however, I have not been able to find it. Sorry if this question has already been answered elsewhere

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
