### ISSUE TITLE
[DISCUSS] API for improved image decoding/augmentation to keep up with future GPU architectures

### ISSUE THREAD

**Issue by ptrendx** [apache/incubator-mxnet#7092]
Hi, this is Przemek from NVIDIA. While working on Volta support and optimizations for MXNet (and other frameworks) we stumbled upon a problem that I think requires discussion with the community. 

The benchmark that we use to assess CNN performance is ResNet 50 (v1). It turns out that with Volta, the GPU performance is high enough that we cannot feed the GPU with decoded and augmented images (even though the augmentations we use are actually pretty minimal - random resize, crop and mirror) fast enough (even though the testing system we use is very high end - 8 GPUs are paired with 40 CPU cores).

One could argue of course, that we should just move to a bigger model and circumvent this problem that way. One needs to also think about the inference time though - if the model becomes too big, then it becomes difficult to do inference e.g. on mobile device.

That is why we would like to tackle this problem somehow, and the most promising solutions require offloading at least some of the IO pipeline to the GPUs. However, this would be a pretty big change to MXNet's `fit` function, since right now the placement of IO pipeline is pretty rigid - the batch needs to be processed to be then split into parts for each GPU and sent to feed the actual training. The proposed approach would require iterator to split and send batches itself, which would require at least wrapping existing iterators.

What do you think about this issue and proposed solution? Any advice on how this could be implemented?

@tqchen @piiswrong @mli

**Comment by piiswrong** [comment]
It's better to do this in python with mx.image.
Although this approach will put more pressure on the engine.

**Comment by ptrendx** [comment]
I was under impression that mx.image is still in the pre-split and send portion of the fit method, right? So it would need to be changed the same way to be able to do hybrid approach.

**Comment by piiswrong** [comment]
Allowing iterator to return either a single ndarray or a list of ndarray isn't very hard.

On the other hand, this is easier to do with the new gluon interface. Although gluon is currently 10% slower than module

**Comment by ptrendx** [comment]
Still, this is a change to API of iterators (also, you need to provide GPU context to iterators then, that's another change). Would also need a change to other frontends, besides Python. This issue is to gather feedback from the community on how to do it properly (and I agree if iterators will include the splitting code then it may be not very hard to do it).

**Comment by tqchen** [comment]
Let us clarify here, what is the proposal here, is it:

- Data parallel augs(split ahead and have different thread process each split)
- GPU native augs( have gpu to do the job)

In general, I think we could take benefit of the scheduler/engine on tracking some of the dependencies as we did for the GPU trainining, to make the event handling easier whenw e need asynchrous data parallel augs

**Comment by ptrendx** [comment]
GPU native augs and actually even more - as I said the augmentations I'm doing are actually pretty minimal and most of the time is spent on JPEG decode. We think about different ways to speed up decoding - hybrid pipeline (Huffman decode on CPU, DCT on GPU), moving to video i-frames and use hardware decoder for them etc.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
