### ISSUE TITLE
Save a mxnet model to keras and vice versa

### ISSUE THREAD

**Issue by lichen11** [apache/incubator-mxnet#7094]
Is there a function or some sample code to save a mxnet model as a keras model (such as .h5) or load a keras model into mxnet?

**Comment by imranshaikmuma** [comment]
i am looking for the same thing!! please let me know if you find any!!!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
