### ISSUE TITLE
Proposal: random seed should better to be different in each run by default

### ISSUE THREAD

**Issue by maxenceliu** [apache/incubator-mxnet#7104]
Otherwise, the result is exactly the same each time. Besides, we could set the seed if we wish.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
