### ISSUE TITLE
Add build instructions for Fedora to the Installation page

### ISSUE THREAD

**Issue by kottmann** [apache/incubator-mxnet#7107]
It would be great if the Installation page contains a step-by-step list of things that need to be done to compile MXNet on Fedora.

**Comment by kottmann** [comment]
See this PR for further discussion:
https://github.com/apache/incubator-mxnet/pull/7123

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
