### ISSUE TITLE
Low GPU usage on training

### ISSUE THREAD

**Issue by soraphis** [apache/incubator-mxnet#7108]
| Environment info |  |
| - | - |
| Operating System | Windows |
| Package used | Python |
| Python Version | 3.4.1 |
| MXNet version | 0.10.1 |
| CUDA | 8.0.61 |
| cudNN | 5.1 |
| MXNet version | 0.10.1 |
| - | - |
| GPU | GTX 970 |

Running a few of the [image classification](https://github.com/dmlc/mxnet/tree/master/example/image-classification) examples (on an own datasets - *.rec file).

This is my GPU usage while training lenet with a batch size of 60 on 3x32x32 image data
![lenet_32](https://user-images.githubusercontent.com/3066582/28376678-0652eeb2-6cab-11e7-965b-390786514d7a.png)

dataset has 1000 images, one epoche takes ~200 seconds.

training resnet with 50 layers and a batch size of 30 on the same data:

![resnet_32](https://user-images.githubusercontent.com/3066582/28377316-aa47c8de-6cac-11e7-931b-c7b4c2259910.png)

___

i try to stay below ~3GB of Memory usage, because of the bottle neck in the GTX 970, but that seems to make no difference. The graphs show clearly that the GPU is used (my cpu usage is around 30%-40%), but it seems that it spends most of the time idle

**Comment by Arielnabai** [comment]
Hello,
I meet the same question and  have you got the solution?

**Comment by soraphis** [comment]
Not yet, but i'd got other stuff to do the last week. I'll see if i can test more this week, i'll check with another graphics card, but this seems odd.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
