### ISSUE TITLE
[gluon] feature request -- parameter save arguments

### ISSUE THREAD

**Issue by jsamson008** [apache/incubator-mxnet#7111]
Could the gluon save function also include an option for 
1) epoch -- like the default mxnet one
2) global_step
2) max_to_keep
3) keep_checkpoint_every_n_hours

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
