### ISSUE TITLE
Weight sharing in SequentialRNNCell throws AssertionError

### ISSUE THREAD

**Issue by cherryc** [apache/incubator-mxnet#7112]
Using SequentialRNNCell's params= constructor option always results in an AssertionError with GRUCell. This seems to stem from the fact that the RNNCell getter sets self._own_params=False, and most cells (LSTMCell, GRUCell) call the getter even if they were not given a params= argument in their respective constructors.

## Environment info
Operating System: OS X
MXNet version: 0.10.0
Python version and distribution: Python 3.6.0 :: Anaconda 4.3.1 (x86_64)

## Error Message:
Traceback (most recent call last):
  File "myParamsTest.py", line 8, in <module>
    seq2.add(cell2)
  File "/anaconda/lib/python3.6/site-packages/mxnet/rnn/rnn_cell.py", line 733, in add
    "Either specify params for SequentialRNNCell " \
AssertionError: Either specify params for SequentialRNNCell or child cells, not both.

## Minimum reproducible example
import mxnet as mx

cell1 = mx.rnn.GRUCell(10)
seq1 = mx.rnn.SequentialRNNCell()
seq1.add(cell1)
cell2 = mx.rnn.GRUCell(10)
seq2 = mx.rnn.SequentialRNNCell(params=seq1.params)
seq2.add(cell2)

## Steps to reproduce
python myParamsTest.py

**Comment by piiswrong** [comment]
specify weight sharing for the children cells, not sequentialcell

**Comment by cherryc** [comment]
PS: For anyone facing this issue, the workaround I am using is to reset _own_params after construction of the child.
import mxnet as mx

cell1 = mx.rnn.GRUCell(10)
seq1 = mx.rnn.SequentialRNNCell()
seq1.add(cell1)
cell2 = mx.rnn.GRUCell(10)
cell2._own_params = True  # Workaround
seq2 = mx.rnn.SequentialRNNCell(params=seq1.params)
seq2.add(cell2)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
