### ISSUE TITLE
There is a bug in  mxnet/example/recommenders/crossentropy.py 

### ISSUE THREAD

**Issue by miraclewkf** [apache/incubator-mxnet#7116]
There is a bug in  mxnet/example/recommenders/crossentropy.py, line 57: grad = -1. / (p - self.eps_1 + y). The (p - self.eps_1 + y) part will be 0 in some cases, so I suggest use d_new = p - self.eps_1 + y, d_new[d_new==0] = self.eps_1,   grad = -1. / d_new instead.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
