### ISSUE TITLE
Feature request : mobilenet

### ISSUE THREAD

**Issue by qingzhouzhen** [apache/incubator-mxnet#7122]
I am intending to implement mobilenet : [MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications
](https://arxiv.org/abs/1704.04861)
Any suggestions?

**Comment by xyddj** [comment]
You can use this one. https://github.com/KeyKy/mobilenet-mxnet

It worked for me.

**Comment by qingzhouzhen** [comment]
I have tested on this, the training speed on GPUS is about 50 samples/second, which is about half of normal convolution.
