### ISSUE TITLE
mxnet.ndarray.random_normal uses same seed on every run.

### ISSUE THREAD

**Issue by sebastian-lapuschkin** [apache/incubator-mxnet#7124]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Package used (Python/R/Scala/Julia): Python

If you are using python package, please provide

Python version and distribution: Python 2.7.12

MXNet version: mxnet-cu80 via pip: mxnet version 0.10.1, today's nightly build

## Error Message:
No error message, but the following, when working through the tutorial
mxnet.ndarray.random_normal() will produce the same results every time on a fresh run. E.g. running this code

import mxnet.ndarray as nd
a = nd.random_normal(shape=3)
print a

N times in a row (by calling python <script>), produces:

apuschkin@smorrebrod:~/Desktop/mxnet-tutorial$ python /home/lapuschkin/Desktop/mxnet-tutorial/2.py
[ 2.21220636  1.16307867  0.7740038 ]
<NDArray 3 @cpu(0)>
lapuschkin@smorrebrod:~/Desktop/mxnet-tutorial$ python /home/lapuschkin/Desktop/mxnet-tutorial/2.py
[ 2.21220636  1.16307867  0.7740038 ]
<NDArray 3 @cpu(0)>
lapuschkin@smorrebrod:~/Desktop/mxnet-tutorial$ python /home/lapuschkin/Desktop/mxnet-tutorial/2.py
[ 2.21220636  1.16307867  0.7740038 ]
<NDArray 3 @cpu(0)>
lapuschkin@smorrebrod:~/Desktop/mxnet-tutorial$ python /home/lapuschkin/Desktop/mxnet-tutorial/2.py
[ 2.21220636  1.16307867  0.7740038 ]
<NDArray 3 @cpu(0)>
lapuschkin@smorrebrod:~/Desktop/mxnet-tutorial$ python /home/lapuschkin/Desktop/mxnet-tutorial/2.py
[ 2.21220636  1.16307867  0.7740038 ]
<NDArray 3 @cpu(0)>

[...]

and so on. Is this intended behaviour to always re-use / initiate the random number generator with the same seed?

The random number can change when changing context, but sticking to one context will produce the same output for that context over and over again.

## Minimum reproducible example
import mxnet.ndarray as nd
a = nd.random_normal(shape=3)
print a

## Steps to reproduce
1. paste above code sample into a python script.
2. run script N times.
3. observe N identical random arrays

## What have you tried to solve it?
1. manually setting a seed, eg. mx.random.seed(int(time.time()*1e6)) , which solves it. 
2. Gut feeling says: 1. should not be necessary. Am I wrong?

**Comment by piiswrong** [comment]
This is the same behavior as rand(). If you don't set a random seed, it's deterministic

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
