### ISSUE TITLE
Compile fail on the Jetson TX1

### ISSUE THREAD

**Issue by liketheflower** [apache/incubator-mxnet#7129]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 14.04

Compiler:
gcc 4.8
Package used (Python/R/Scala/Julia):

MXNet version:
latest version following the git clone --recursive...
Or if installed from source:
installed from source
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -I/home/ubuntu/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMXNET_USE_LAPACK  -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0 -MMD -c src/resource.cc -o build/src/resource.o
cd /home/ubuntu/mxnet/dmlc-core; make libdmlc.a USE_SSE=0 config=/home/ubuntu/mxnet/make/config.mk; cd /home/ubuntu/mxnet
make[1]: Entering directory `/home/ubuntu/mxnet/dmlc-core'
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o line_split.o src/io/line_split.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio_split.o src/io/recordio_split.cc
cd /home/ubuntu/mxnet/nnvm; make lib/libnnvm.a DMLC_CORE_PATH=/home/ubuntu/mxnet/dmlc-core; cd /home/ubuntu/mxnet
make[1]: Entering directory `/home/ubuntu/mxnet/nnvm'
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/c_api/c_api_error.o src/c_api/c_api_error.cc >build/src/c_api/c_api_error.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/c_api/c_api_error.cc -o build/src/c_api/c_api_error.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/c_api/c_api_graph.o src/c_api/c_api_graph.cc >build/src/c_api/c_api_graph.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/c_api/c_api_graph.cc -o build/src/c_api/c_api_graph.o
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o input_split_base.o src/io/input_split_base.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/c_api/c_api_symbolic.o src/c_api/c_api_symbolic.cc >build/src/c_api/c_api_symbolic.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/c_api/c_api_symbolic.cc -o build/src/c_api/c_api_symbolic.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/core/graph.o src/core/graph.cc >build/src/core/graph.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/core/graph.cc -o build/src/core/graph.o
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o local_filesys.o src/io/local_filesys.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
/usr/local/cuda/bin/nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=[sm_52,compute_52] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -I/home/ubuntu/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMXNET_USE_LAPACK  -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0" -M -MT build/src/operator/contrib/count_sketch_gpu.o src/operator/contrib/count_sketch.cu >build/src/operator/contrib/count_sketch_gpu.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/core/node.o src/core/node.cc >build/src/core/node.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/core/node.cc -o build/src/core/node.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/core/op.o src/core/op.cc >build/src/core/op.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/core/op.cc -o build/src/core/op.o
/usr/local/cuda/bin/nvcc -c -o build/src/operator/contrib/count_sketch_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=[sm_52,compute_52] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -I/home/ubuntu/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMXNET_USE_LAPACK  -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0" src/operator/contrib/count_sketch.cu
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/core/pass.o src/core/pass.cc >build/src/core/pass.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/core/pass.cc -o build/src/core/pass.o
/usr/local/cuda/bin/nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=[sm_52,compute_52] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -I/home/ubuntu/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMXNET_USE_LAPACK  -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0" -M -MT build/src/operator/contrib/ctc_loss_gpu.o src/operator/contrib/ctc_loss.cu >build/src/operator/contrib/ctc_loss_gpu.d
/home/ubuntu/mxnet/nnvm/include/nnvm/./op.h(468): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r346/r346_00/drivers/compiler/edg/EDG_4.9/src/decl_inits.c", line 3274

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00002c0a_00000000-16_count_sketch.compute_52.cpp1.ii".
Compilation aborted.
Aborted
make: *** [build/src/operator/contrib/count_sketch_gpu.o] Error 134
make: *** Waiting for unfinished jobs....g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc

g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/core/symbolic.o src/core/symbolic.cc >build/src/core/symbolic.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/core/symbolic.cc -o build/src/core/symbolic.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/gradient.o src/pass/gradient.cc >build/src/pass/gradient.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/gradient.cc -o build/src/pass/gradient.o
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
src/core/symbolic.cc: In member function ‘nnvm::Symbol nnvm::Symbol::GetChildren() const’:
src/core/symbolic.cc:439:16: warning: unused variable ‘fnum_vis_output’ [-Wunused-variable]
   static auto& fnum_vis_output = Op::GetAttr<FNumVisibleOutputs>("FNumVisibleOutputs");
                ^
/usr/local/cuda/bin/nvcc -c -o build/src/operator/contrib/ctc_loss_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=[sm_52,compute_52] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ubuntu/mxnet/mshadow/ -I/home/ubuntu/mxnet/dmlc-core/include -fPIC -I/home/ubuntu/mxnet/nnvm/include -I/home/ubuntu/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMXNET_USE_LAPACK  -I/home/ubuntu/mxnet/cub -DMXNET_USE_NVRTC=0" src/operator/contrib/ctc_loss.cu
ar cr libdmlc.a line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o
make[1]: Leaving directory `/home/ubuntu/mxnet/dmlc-core'
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/infer_shape_type.o src/pass/infer_shape_type.cc >build/src/pass/infer_shape_type.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/infer_shape_type.cc -o build/src/pass/infer_shape_type.o
/home/ubuntu/mxnet/nnvm/include/nnvm/./op.h(468): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r346/r346_00/drivers/compiler/edg/EDG_4.9/src/decl_inits.c", line 3274

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00002c92_00000000-16_ctc_loss.compute_52.cpp1.ii".
Compilation aborted.
Aborted
make: *** [build/src/operator/contrib/ctc_loss_gpu.o] Error 134
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/order_mutation.o src/pass/order_mutation.cc >build/src/pass/order_mutation.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/order_mutation.cc -o build/src/pass/order_mutation.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/place_device.o src/pass/place_device.cc >build/src/pass/place_device.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/place_device.cc -o build/src/pass/place_device.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/plan_memory.o src/pass/plan_memory.cc >build/src/pass/plan_memory.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/plan_memory.cc -o build/src/pass/plan_memory.o
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -MM -MT build/src/pass/saveload_json.o src/pass/saveload_json.cc >build/src/pass/saveload_json.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I/home/ubuntu/mxnet/dmlc-core/include -I/home/ubuntu/mxnet/dmlc-core/include  -c src/pass/saveload_json.cc -o build/src/pass/saveload_json.o
ar crv lib/libnnvm.a build/src/c_api/c_api_error.o build/src/c_api/c_api_graph.o build/src/c_api/c_api_symbolic.o build/src/core/graph.o build/src/core/node.o build/src/core/op.o build/src/core/pass.o build/src/core/symbolic.o build/src/pass/gradient.o build/src/pass/infer_shape_type.o build/src/pass/order_mutation.o build/src/pass/place_device.o build/src/pass/plan_memory.o build/src/pass/saveload_json.o
a - build/src/c_api/c_api_error.o
a - build/src/c_api/c_api_graph.o
a - build/src/c_api/c_api_symbolic.o
a - build/src/core/graph.o
a - build/src/core/node.o
a - build/src/core/op.o
a - build/src/core/pass.o
a - build/src/core/symbolic.o
a - build/src/pass/gradient.o
a - build/src/pass/infer_shape_type.o
a - build/src/pass/order_mutation.o
a - build/src/pass/place_device.o
a - build/src/pass/plan_memory.o
a - build/src/pass/saveload_json.o
make[1]: Leaving directory `/home/ubuntu/mxnet/nnvm'

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.git clone --recursive https://github.com/dmlc/mxnet
2.cd mxnet
3. make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=0

## What have you tried to solve it?

1.try to install the CPU only version by following the standard installation from source instruction and It works good.
2.try to install the GPU version on a ubuntu laptop with cuda 8.0. It works good too.
3.

**Comment by liketheflower** [comment]
the CUDA version is 7.0

**Comment by andyhx** [comment]
hi,how do u solve it ,i buiding the newest mxnet version on cuda 6.5 on jeston tk1 ,came across the  same problem ,errors were like the following 
`/home/ubuntu/mxnet/git/mxnet/nnvm/include/nnvm/./op.h(468): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r343/r343_00/drivers/compiler/edg/EDG_4.8/src/decl_inits.c", line 3158


1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000ca5_00000000-15_count_sketch.compute_52.cpp1.ii".
Compilation aborted.
Aborted
make: *** [build/src/operator/contrib/count_sketch_gpu.o] Error 134`

**Comment by liketheflower** [comment]
I just gave up. I don't know which version will work well on the jetson. On my aws, the working version for the FCIS of CUDA is 8.0.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
