### ISSUE TITLE
Publish scala artifacts for CentOS 7

### ISSUE THREAD

**Issue by milandesai** [apache/incubator-mxnet#7134]
We have a security requirement that any third-party artifacts used in production must be published by the developer to a repository, i.e. we cannot build the artifacts ourselves. However, the currently published scala artifacts do not work on CentOS 7, which is what our production machines run on. 

The published native library located at https://oss.sonatype.org/content/repositories/snapshots/ml/dmlc/mxnet/libmxnet-scala-linux-x86_64-cpu/0.10.0-SNAPSHOT/libmxnet-scala-linux-x86_64-cpu-0.10.0-20170611.163119-3.so fails to load due to an incorrect GLIBC version and a missing libcblas.so. The latter error is due to the fact that in CentOS 7, the Atlas blas library name is satlas instead of cblas.

Would it be possible to publish mxnet-scala artifacts for CentOS 7? We have created a PR at https://github.com/dmlc/mshadow/pull/272 that should help to this end - it removes the need for any manual build configuration changes by fixing the atlas blas library issue mentioned earlier. We have tested that that with that fix, running `make` and `make scalapkg` on a CentOS 7.3 machine after installing opencv-devel and atlas-devel produces a working library.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
