### ISSUE TITLE
Multidimensional label input?

### ISSUE THREAD

**Issue by nash007** [apache/incubator-mxnet#7139]
My inputs to the network are images along with a fixed number of 2D image coordinates. How does one represent coordinates as labels in a .lst file? 

Also, I couldn't really find examples of such implementations in mxnet apart from SSD. Are there more?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
