### ISSUE TITLE
installing mxnet for python  in windows.

### ISSUE THREAD

**Issue by akshay2495** [apache/incubator-mxnet#7145]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
windows 10
Compiler:

The package used (Python/R/Scala/Julia):
python
MXNet version:
is it not possible to install mxnet using python in windows 10 OS for CPU?
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by edmBernard** [comment]
have you try to use this https://github.com/yajiedesign/mxnet/releases ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
