### ISSUE TITLE
Questions about the distributed training recovery using mxnet python

### ISSUE THREAD

**Issue by LakeCarrot** [apache/incubator-mxnet#7153]
I found someone has mentioned before about the failure recovery behavior of distributed MXNet #2268. But that is limited in a way that it only applied to the scala version of MXNet. I wonder is there any failure recovery support for the python version of MXNet or is there any for developer to define that behavior?

Thanks in advance!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
