### ISSUE TITLE
image prediction example is not valid 

### ISSUE THREAD

**Issue by r-y-zadeh** [apache/incubator-mxnet#7157]
The link in image classification example is not valid (the link is redirected to: http://mxnet.io/tutorials/python/predict_imagenet.html ) - >i think  the correct link is: "http://mxnet.io/tutorials/python/predict_image.html"

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
