### ISSUE TITLE
var duplication happens for ones_like operation

### ISSUE THREAD

**Issue by CarlyleCao** [apache/incubator-mxnet#7159]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04

Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.5
Or if installed from source:
[MXNet@(commit 62ecb60)](https://github.com/dmlc/mxnet/tree/62ecb60)
MXNet commit hash (`git rev-parse HEAD`):
commit 62ecb60
If you are using python package, please provide

Python version and distribution:
2.7.12

## Error Message:
Please paste the full error message, including stack trace.

MXNetError: [22:05:50] src/executor/graph_executor.cc:653: var duplication happens for op cumsum

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f601ea7384c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet4exec13GraphExecutor13InitCachedOpsEv+0x2080) [0x7f601f66cac0]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_St4lessISD_ESaISt4pairIKSD_S4_EEERKSt6vectorINS_7NDArrayESaISO_EESS_RKSN_INS_9OpReqTypeESaIST_EESS_PNS_8ExecutorE+0xacf) [0x7f601f66fe4f]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet8Executor4BindEN4nnvm6SymbolERKNS_7ContextERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_St4lessISC_ESaISt4pairIKSC_S3_EEERKSt6vectorINS_7NDArrayESaISN_EESR_RKSM_INS_9OpReqTypeESaISS_EESR_PS0_+0x107) [0x7f601f6700c7]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXExecutorBindEX+0x23c1) [0x7f601f612ac1]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f6052a4fe40]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f6052a4f8ab]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f6052c5f3df]
[bt] (8) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f6052c63d82]
[bt] (9) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```python
inputs = mx.sym.var(name='inputs')
mask = mx.sym.ones_like(data=inputs, name='mask')
cumsum = mx.sym.zeros_like(mask, name='cumsum')
cumsum.eval(mx.cpu(), inputs=mx.nd.ones([1,1,1,5]))[0].asnumpy()
```

By the way, I found out that this bug seems to be fixed in the latest released version. However, it is hard for me to transfer the code to the latest version, so is there a light solution that I can fix this bug based on mxnet 0.9.5?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
