### ISSUE TITLE
SSD running " python demo.py" problems

### ISSUE THREAD

**Issue by InesBeltaief** [apache/incubator-mxnet#7160]
## Environment info
Operating System: ubuntu 16.04

Compiler: 

Package used (Python/R/Scala/Julia): Python

MXNet version: 10

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:2.7

## Error Message:

`/home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [09:00:53] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc72fc) [0x7f1b5c9ee2fc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXImperativeInvoke+0xaca) [0x7f1b5d423b5a]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f1b60ea6e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f1b60ea68ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f1b610b63df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f1b610bad82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]

Traceback (most recent call last):
  File "demo.py", line 99, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 42, in get_detector
    data_shape, mean_pixels, ctx=ctx)
  File "/home/ines/SSD/ssd-text_detection-master/mxnet-master/example/ssd/detect/detector.py", line 39, in __init__
    self.mod.bind(data_shapes=[('data', (batch_size, 3, data_shape, data_shape))])
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 216, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 312, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 620, in _bind_ith_exec
    arg_arr = nd.zeros(arg_shapes[j], context, dtype=arg_types[j])
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray.py", line 1003, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "<string>", line 15, in _zeros
  File "/usr/local/lib/python2.7/dist-packages/mxnet/_ctypes/ndarray.py", line 72, in _imperative_invoke
    c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:00:53] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc72fc) [0x7f1b5c9ee2fc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXImperativeInvoke+0xaca) [0x7f1b5d423b5a]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f1b60ea6e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f1b60ea68ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f1b610b63df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f1b610bad82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
