### ISSUE TITLE
About sync frequency in distributed training

### ISSUE THREAD

**Issue by Some-random** [apache/incubator-mxnet#7163]
I have two questions about distributed training in mxnet.

First, after reading the code in train_mnist.py, as to my understanding, the only changes you need to make is:
1 pass "dist_sync"/ "dist_async" kvstore to optimizer or module.fit() method
2 make a hosts file and make sure all IPs on that list is ssh-able or mpirun-able
3 call launch.py in tools
Is my understanding correct or am I missing something?

Second, I just want to verify the sync frequency in distributed setting. Are the weights being synced every time you call module.update()? And if I want to sync on each machine for every n batches, is there any way I can do something like module.local_update() on every batch and module.global_update() every n_batch?

Thanks in advance!

**Comment by rahul003** [comment]
First part looks right. 
Secondly, ya they are synced each time. Currently it seems like it is not possible to sync every n batches.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
