### ISSUE TITLE
 Get error: 'Gradient function not returning enough gradient'

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#7168]
I update mxnet to the latest version, then run my code which works fine for old versions. It gives me error as Gradient function not returning enough gradient. What is this? I can not find any information about this.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
