### ISSUE TITLE
I meet Segmentation fault (core dumped) when I load checkpoint

### ISSUE THREAD

**Issue by searchXiaoLai** [apache/incubator-mxnet#7169]
## Environment info
Operating System:
ubuntu14.04
Compiler:
gcc4.9
Package used (Python/R/Scala/Julia):
python
MXNet version:
v.0.10.0
Or if installed from source:
yes
Python version and distribution:
2.7.6

## Error Message:
Segmentation fault (core dumped)
## Minimum reproducible example
I create a new operate. Which could get data and label, for example, 128 images of fully connected layer features and their labels are the input. And then compute the difference of two images, the label become 0 or 1 which means whether these two images are from one class or not. So the input size may be 128, and the output size will be 64. I train this model successfully. But when I want to load the save model, I meet the Segmentation fault. Maybe I should rewrite my operate, or what should I do. thank you.
## Steps to reproduce
sym, arg_params, aux_params = mx.model.load_checkpoint('dpn107-one', 10)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
