### ISSUE TITLE
RAM consumption MobileNets?

### ISSUE THREAD

**Issue by Shiro-LK** [apache/incubator-mxnet#7174]
I'm trying to re train mobilenet network. (this one [https://github.com/KeyKy/mobilenet-mxnet](https://github.com/KeyKy/mobilenet-mxnet))
I have a strange and huge RAM consumption that increase over time and when there is no ram available the process is killed. 
I trained this model with about 300k images (299 x 299) and don't got issues on a standard inception_bn.
It seem the deepwise convolution layer made with argument num_group in the convolution layer have memory leak.

**Comment by qingzhouzhen** [comment]
What "--batch-size" you used? I use --batch-size=512 then mache went out of memory, but when I turn it to 128, everything is OK.

**Comment by Shiro-mx** [comment]
I used a batch size of 4. The computer has 16 GB of RAM and 32 gb of swap. The graphical card is a nvidia 1070 with 8 gb of memory.

**Comment by qingzhouzhen** [comment]
My machine has 360G RAM, with 2 GPUs K80

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
