### ISSUE TITLE
kernel dies when trainning begins

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#7176]
why did iPython's kernel die when i used cpu but it worked normally when i used gpu?
mxnet 10.0 & windows 10 platform

**Comment by janelu9** [comment]
Summary of dataset ==================
bucket of len   5 : 2320 samples
bucket of len   6 : 2544 samples
bucket of len   7 : 3748 samples
bucket of len   8 : 4728 samples
bucket of len   9 : 5283 samples
bucket of len  10 : 6200 samples
bucket of len  11 : 6659 samples
bucket of len  12 : 6421 samples
bucket of len  13 : 5428 samples
bucket of len  14 : 4365 samples
bucket of len  15 : 3097 samples
bucket of len  16 : 2138 samples
bucket of len  17 : 1386 samples
bucket of len  19 : 1326 samples
bucket of len  29 : 541 samples
news_train.py:54: DeprecationWarning: [91mmxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.[0m
  optimizer='Adam',
D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.10.1-py2.7.egg\mxnet\model.py:530: DeprecationWarning: [91mCalling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.[0m
  self.initializer(k, v)
Start training with [cpu(0)]

died

**Comment by edmBernard** [comment]
Are you sure you have enough ram memory to train a network on cpu only ? Some network consume lot's of ram (vgg16).

**Comment by janelu9** [comment]
@edmBernard  My device has 16g of ram , gpu's ram is only 6G

**Comment by edmBernard** [comment]
when you say ipython kernel, you use jupyter notebook ?

**Comment by janelu9** [comment]
as attached above, it is anaconda's ipython

**Comment by janelu9** [comment]
nothing wrong happened when it was running on mxnet0.9.5

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
