### ISSUE TITLE
Shape inconsistent

### ISSUE THREAD

**Issue by zhang-jian** [apache/incubator-mxnet#7178]
Hi,

<pre>
import mxnet as mx
import numpy as np
import logging

def create_net():
    
    stack = mx.rnn.SequentialRNNCell()    
    for i in range(3):
        cell = mx.rnn.LSTMCell(num_hidden=num_hidden, prefix='lstm_%dl0_'%i)
        cell = mx.rnn.BidirectionalCell(
                cell,
                mx.rnn.LSTMCell(num_hidden=num_hidden, prefix='lstm_%dr0_'%i),
                output_prefix='bi_lstm_%d'%i)
        stack.add(cell)
    
    
    X = mx.sym.Variable('data')
    Y = mx.sym.Variable('lin_reg_label')
    stack.reset()
    outputs, states = stack.unroll(seq_len, inputs=X, merge_outputs=True)
    fc1  = mx.sym.FullyConnected(data=outputs, name='fc1', num_hidden = num_hidden)
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
    fc2  = mx.symbol.FullyConnected(data = act1, name='fc2', num_hidden=out_feature_size)
    net = mx.sym.LinearRegressionOutput(data=fc2, label=Y, name="lro")
    #print net.debug_str()
    return net

logging.getLogger().setLevel(logging.DEBUG)

seq_len=10
num_hidden = 20
in_feature_size = 30
out_feature_size = 10
batch_size = 16

#Training data
train_data = np.random.uniform(0, 1, [100, seq_len, in_feature_size])
train_label = np.random.uniform(0, 1, [100, seq_len, out_feature_size])

#Evaluation Data
eval_data = train_data
eval_label = train_label

train_iter = mx.io.NDArrayIter(train_data,train_label, batch_size, shuffle=True, label_name='lin_reg_label')
eval_iter = mx.io.NDArrayIter(eval_data, eval_label, batch_size, shuffle=False)

net = create_net()

# a = mx.viz.plot_network(net)
# a.render("example")
context = mx.cpu(0)

model = mx.mod.Module(
    context = context,
    symbol = net,
    data_names=['data'],
    label_names = ['lin_reg_label']# network structure
)

frequent = 50
#wd: weight decay for sgd
model.fit(train_iter, eval_iter,
            optimizer='sgd',
            optimizer_params={'learning_rate':0.005, 'momentum': 0.9, 'wd': 0.00001},
            num_epoch=50,
            eval_metric='mse',
            initializer = mx.init.Xavier(factor_type="in", magnitude=2.34),
            batch_end_callback = mx.callback.Speedometer(batch_size=batch_size, frequent=frequent), #Logs training speed and evaluation metrics periodically.
            epoch_end_callback = mx.callback.do_checkpoint("test_model", 2) #test_model-0032.params
            )

metric = mx.metric.MSE()
score = model.score(eval_iter, metric)
print score
</pre>

gave me 

<pre>
mxnet.base.MXNetError: Error in operator lro: Shape inconsistent, Provided=(16,10,10), inferred shape=(16,10)
</pre>

I thought the <pre>outputs</pre> from <pre>stack</pre> has size (batch_size, sequence_length, 2*hidden_dim), then after 2 feedforward networks, fc2 would be the size  (batch_size, sequence_length, out_feature_size).

Thanks,

J

**Comment by jingpengw** [comment]
I just get the same error, still checking what's wrong.

**Comment by zhang-jian** [comment]
I think the issue is related with mxnet.symbol.FullyConnected only takes  (batch_size, input_dim) as input. So, we need to reshape the outputs from RNN and labels:

<pre>
 outputs = mx.sym.Reshape(outputs, shape=(-1, 2*num_hidden))
 Y = mx.sym.Reshape(Y, shape=(-1, out_feature_size))
</pre>

However, another error occurs
<pre>
ValueError: operands could not be broadcast together with shapes (16,10,10) (160,10) 
</pre>

**Comment by zhang-jian** [comment]
<pre>
ValueError: operands could not be broadcast together with shapes (16,10,10) (160,10)
</pre>

is related with evaluation metric. The evaluation data also need to be reshaped. I couldn't find a better solution other than writing my own 'mse'. The working code is

<pre>
import mxnet as mx
import numpy as np
import logging

def custom_metric(label, pred):
    label = label.reshape(batch_size*seq_len, -1)
    return np.mean((label-pred)**2)


def create_net():
    
    stack = mx.rnn.SequentialRNNCell()    
    for i in range(3):
        cell = mx.rnn.BidirectionalCell(
                mx.rnn.LSTMCell(num_hidden=num_hidden, prefix='lstm_%dl0_'%i),
                mx.rnn.LSTMCell(num_hidden=num_hidden, prefix='lstm_%dr0_'%i),
                output_prefix='bi_lstm_%d'%i)
        stack.add(cell)
    
    
    X = mx.sym.Variable('data')
    Y = mx.sym.Variable('lin_reg_label')
    
    stack.reset()
    outputs, states = stack.unroll(seq_len, inputs=X, merge_outputs=True)
    
    
    #FullyConnected: data: (batch_size, input_dim)
    outputs = mx.sym.Reshape(outputs, shape=(batch_size*seq_len, -1))
    
    Y = mx.sym.Reshape(Y, shape=(batch_size*seq_len, -1))
    #input_label_shapes = {'lin_reg_label':(batch_size,seq_len,out_feature_size)}
    #input_data_shapes = {'data':(batch_size,seq_len,in_feature_size)}

    fc1  = mx.sym.FullyConnected(data=outputs, name='fc1', num_hidden = num_hidden)
    act1 = mx.sym.Activation(data = fc1, name='relu1', act_type="relu")
    fc2  = mx.sym.FullyConnected(data = act1, name='fc2', num_hidden=out_feature_size)
    act2 = mx.sym.Activation(data = fc2, name='relu2', act_type="relu")
    act2 = mx.sym.Reshape(act2, shape=(-1, out_feature_size))
    #print act2.infer_shape(**input_data_shapes)
    #print Y.infer_shape(**input_label_shapes)
    
    net = mx.sym.LinearRegressionOutput(data=act2, label=Y, name="lro")
    return net


logging.getLogger().setLevel(logging.DEBUG)

seq_len=10
num_hidden = 5
in_feature_size = 30
out_feature_size = 10
batch_size = 16


#Training data
train_data = np.random.uniform(0, 1, [160, seq_len, in_feature_size])
train_label = np.random.uniform(0, 1, [160, seq_len, out_feature_size])

#Evaluation Data
eval_data = train_data
eval_label = train_label

train_iter = mx.io.NDArrayIter(train_data,train_label, batch_size, shuffle=True, label_name='lin_reg_label')
eval_iter = mx.io.NDArrayIter(eval_data, eval_label, batch_size, shuffle=False)


net = create_net()

# a = mx.viz.plot_network(net)
# a.render("example")
context = mx.cpu(0)

model = mx.mod.Module(
    context = context,
    symbol = net,
    data_names=['data'],
    label_names = ['lin_reg_label']# network structure
)

frequent = 50
my_eval_metric = mx.metric.create(custom_metric)

#wd: weight decay for sgd
model.fit(train_iter, eval_iter,
            optimizer='sgd',
            optimizer_params={'learning_rate':0.005, 'momentum': 0.9, 'wd': 0.00001},
            num_epoch=50,
            eval_metric=my_eval_metric,
            initializer = mx.init.Xavier(factor_type="in", magnitude=2.34),
            batch_end_callback = mx.callback.Speedometer(batch_size=batch_size, frequent=frequent), #Logs training speed and evaluation metrics periodically.
            epoch_end_callback = mx.callback.do_checkpoint("test_model", 2) #test_model-0032.params
            )

score = model.score(eval_iter, my_eval_metric)
print score
</pre> 

This is my first time using mxnet, so, not sure if the code is correct. Could anyone verify this, thanks!!

J

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
