### ISSUE TITLE
Amalgamation is broken again!

### ISSUE THREAD

**Issue by divamgupta** [apache/incubator-mxnet#7180]
I built the libmxnet_predict.so by running the make command in 

When I run `mxnet_predict_example.py`  at `mxnet/tests/python/predict` . The following error comes.

```

Traceback (most recent call last):
  File "mxnet_predict_example.py", line 5, in <module>
    from mxnet_predict import Predictor, load_ndarray_file
  File "../../../amalgamation/python/mxnet_predict.py", line 57, in <module>
    _LIB = _load_lib()
  File "../../../amalgamation/python/mxnet_predict.py", line 46, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/mxnet5/mxnet/amalgamation/python/../../lib/libmxnet_predict.so: undefined symbol: _ZN5mxnet8autograd15AutogradRuntime9is_train_E

```

To reproduce this pls make sure that  the amalgamated .so file is used. Hence only `libmxnet_predict.so` should be in `mxnet/lib`.

This error does not come before version 0.9

**Comment by divamgupta** [comment]
To reproduce this:  

In a new folder:

```
git clone https://github.com/dmlc/mxnet/
cd mxnet
git submodule update --init --recursive
cd amalgamation
make MIN=1
cd python
python mxnet_predict.py
```

This will throw an error.  This error does not come before mxnet version 0.9. 



--

**Comment by edmBernard** [comment]
I try to find where this error come from : 
`AutogradRuntime::is_train_` is define [here](https://github.com/dmlc/mxnet/blob/1bb9e45f5df2b4a283bb930a25c985b1a9b5cd82/src/ndarray/autograd.cc#L25) and [here](https://github.com/dmlc/mxnet/blob/ed190957bb57abd29aca1d22d201a87fd871a272/src/ndarray/autograd.h#L110)
and it seem it's correctly include in mxnet_predict-all.cc

**Comment by edmBernard** [comment]
I only get the same error for Android compilation. 
with standard gcc and g++, I don't get any issus.

**Comment by edmBernard** [comment]
with nm tools to check library it find symbol `AutogradRuntime::is_train_`
on gcc : 
```
root@55b5b95994dd:~/lib/mxnet/amalgamation# nm -g ../lib/libmxnet_predict.so | grep is_train_
                 U _ZN5mxnet8autograd15AutogradRuntime9is_train_E
                 w _ZTHN5mxnet8autograd15AutogradRuntime9is_train_E
```
on arm-linux-androideabi-clang
```
root@77d4bf712ae4:~/lib/mxnet/amalgamation# nm -g ../lib/libmxnet_predict.so | grep is_train_
         w _ZTHN5mxnet8autograd15AutogradRuntime9is_train_E
         U __emutls_v._ZN5mxnet8autograd15AutogradRuntime9is_train_E
```

**Comment by edmBernard** [comment]
if it's for android it can come from android version :
https://stackoverflow.com/a/40471506/7786237

**Comment by divamgupta** [comment]
@edmBernard 
In standard g++ and gcc the .so file will be compiled but you wont be able to use the .so file. Even if you make a hello world mxnet cpp application with including mxnet_predict-all.cc you wont be able to compile it.  But these errors wont come in older version of mxnet!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
