### ISSUE TITLE
What's the .rec file format?

### ISSUE THREAD

**Issue by acone2003** [apache/incubator-mxnet#7182]
It perhaps is: | kMagic(4bytes, 0x0A23D7CE) | LRecord(4byts,3bits cflag and 29bits length) | unknown(8byts) | ImageID(8bytes) | Reserved(8bytes, all be 0) | Image data and pad |.
Am I right? what is the unknown 8  bytes? and how can I make a float .rec file?

**Comment by edmBernard** [comment]
The .rec format is explain here http://mxnet.io/architecture/note_data_loading.html. I don't see your unknown 8bytes. 
What did you mean by "float" .rec ?
To make a .rec file you can use this script : https://github.com/dmlc/mxnet/blob/master/tools/im2rec.py or the [RecordIO](http://mxnet.io/api/python/io.html#mxnet.recordio.MXRecordIO) function

**Comment by acone2003** [comment]
I get it. the first 8 bytes is RecordIO header,which is defined in mxnet/dmlc-core/include/dmlc/recordio.h.
The next 24 bytes is image header defined in mxnet/drc/io/image_recordio.h. Is it right?
If I want to train a CNN using my non-image data. should I write a new class inherited form class DataIter and override the virtual functions? I'd like using C++.

**Comment by edmBernard** [comment]
I don't use C++ API for training.
In python [MXRecordIO](http://mxnet.io/api/python/io.html#mxnet.recordio.MXRecordIO) is used for regular data (raw data, not image). 
I find in the c_api these two functions to manage RecordIO : 
* [MXRecordIOWriterWriteRecord](http://mxnet.io/doxygen/c__api_8h.html#a0c380b6aa00446e7cb6021c8e2df75f3)
* [MXRecordIOReaderReadRecord](http://mxnet.io/doxygen/c__api_8h.html#a38e350f748967e0caa2c781a507667e4)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by douglas125** [comment]
I could not find useful resources about how to write a REC file from my own data.
I can create an array dataset using:

`dataset_train = mx.gluon.data.dataset.ArrayDataset(X_train, y_train)`

and then use it in the DataLoader. But if X_train, y_train are too large, I would like to generate them 1 by 1 and save them to disk as I read them, to then be able to use RecordFileDataset function. My question is: how to write X_train[i], y_train[i] one at a time to the REC file?

The link to [MXRecordIO](http://mxnet.incubator.apache.org/api/python/io.html#mxnet.recordio.MXRecordIO) is broken, by the way.
