### ISSUE TITLE
benchmark_score.py is broken

### ISSUE THREAD

**Issue by ykim362** [apache/incubator-mxnet#7185]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 14.04.5 LTS

Compiler:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Package used (Python/R/Scala/Julia): Python

MXNet version: 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
84ce29bcbbe0b17240d1976f49871eab0560238c

If you are using python package, please provide

Python version and distribution:
Python 2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
:~/mxnet/example/image-classification$ python benchmark_score.py 
/usr/lib/python2.7/dist-packages/numpy/oldnumeric/__init__.py:11: ModuleDeprecationWarning: The oldnumeric module will be dropped in Numpy 1.9
  warnings.warn(_msg, ModuleDeprecationWarning)
INFO:root:network: alexnet
INFO:root:device: cpu(0)
Traceback (most recent call last):
  File "benchmark_score.py", line 63, in <module>
    speed = score(network=net, dev=d, batch_size=b, num_batches=10)
  File "benchmark_score.py", line 27, in score
    sym, data_shape = get_symbol(network, batch_size)
  File "benchmark_score.py", line 22, in get_symbol
    num_layers  = num_layers)
TypeError: get_symbol() takes exactly 2 arguments (1 given)

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Install the latest MXNet
2. Run the benchmark_score.py
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by al-rigazzi** [comment]
Same problem for me, using Python 2.7.13, MKL, no GPU.

**Comment by ptrendx** [comment]
That's because there is additional parameter (dtype) now in the get_symbol for some networks and I forgot to give default value for it in alexnet. Posted a PR to fix it #7193

**Comment by ptrendx** [comment]
@ykim362 @al-rigazzi Please check with the current master.

**Comment by ykim362** [comment]
@ptrendx It works good for me now. Thanks!

**Comment by ptrendx** [comment]
@szha please close
