### ISSUE TITLE
Writing when slicing. Weird bug, needs urgent fixing

### ISSUE THREAD

**Issue by zackchase** [apache/incubator-mxnet#7194]
If you assign array of shape (10,) to shape of (10,) using the slice operator, i.e.:
``w[:,0] = w[:,0]``,
you get a horrible bug. 

In [9]: import mxnet as mx

In [10]: import ndarray as nd
---------------------------------------------------------
ImportError             Traceback (most recent call last)
<ipython-input-10-abe6825c56ca> in <module>()
----> 1 import ndarray as nd

ImportError: No module named 'ndarray'

In [11]: import mxnet as mx

In [12]: import mxnet.ndarray as nd

In [13]: w = nd.zeros(shape=(10,2))

In [14]: w[:,0] = w[:,0]
---------------------------------------------------------
MXNetError              Traceback (most recent call last)
<ipython-input-14-1e895c2e651f> in <module>()
----> 1 w[:,0] = w[:,0]

~/mxnet/python/mxnet/ndarray.py in __setitem__(self, key, value)
    389                 value = value.as_in_context(self.context)
    390                 _internal._crop_assign(self, value, out=self,
--> 391                                        begin=begin, end=end)
    392             elif isinstance(value, numeric_types):
    393                 _internal._crop_assign_scalar(self, out=self,

~/mxnet/python/mxnet/ndarray.py in _crop_assign(lhs, rhs, begin, end, out, name, **kwargs)

~/mxnet/python/mxnet/_ctypes/ndarray.py in _imperative_invoke(handle, ndargs, keys, vals, out)
     70         ctypes.c_int(len(keys)),
     71         c_array(ctypes.c_char_p, [c_str(key) for key in keys]),
---> 72         c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
     73 
     74     if original_output is not None:

~/mxnet/python/mxnet/base.py in check_call(ret)
    100     """
    101     if ret != 0:
--> 102         raise MXNetError(py_str(_LIB.MXGetLastError()))
    103 
    104 if sys.version_info[0] < 3:

MXNetError: Shape inconsistent, Provided=(10,), inferred shape=(10,1)

In [15]: 

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

NOTE THAT THIS DOES WORK IN NUMPY 

In [15]: import numpy as np

In [16]: z = np.zeros((10,2))

In [17]: z
Out[17]: 
array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [18]: z[:,0] = z[:,0]

In [19]:

**Comment by rahul003** [comment]
```
import mxnet as mx
import mxnet.ndarray as nd
w = nd.zeros(shape=(10,2))
w[:,0] = w[:,0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/ndarray.py", line 405, in __getitem__
    raise ValueError('Multi-dimension indexing is not supported')
ValueError: Multi-dimension indexing is not supported

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
