### ISSUE TITLE
batch processing with image-classification demo

### ISSUE THREAD

**Issue by Asinta** [apache/incubator-mxnet#7201]
I noticed that under https://github.com/dmlc/mxnet/tree/master/example/image-classification demo. We use one picture to do classification one time. It worked well.
Now I'm trying to do image classification with batch_size = 256 or other batch size, but I'm not sure how to change the existing code, I assume this line:
`    const mx_uint input_shape_data[4] = { 1,
                                        static_cast<mx_uint>(channels),
                                        static_cast<mx_uint>(height), 
                                        static_cast<mx_uint>(width)};`
the first argument "1" is batch_size = 1?
So what I have to do is to read continue batch_size images and store the data into vector:
`std::vector<mx_float> image_data = std::vector<mx_float>(image_size * batch_size);` 
then set input:
`MXPredSetInput(pred_hnd, "data", image_data.data(), image_size * batch_size);`
and do forward:
`MXPredForward(pred_hnd);`

am I right?

**Comment by Asinta** [comment]
@ry @pluskid @darxriggs @jamesliu @thinxer 
Thank you!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
