### ISSUE TITLE
Missing File according to doc (tests/python/gpu/test_conv.py)

### ISSUE THREAD

**Issue by jqueguiner** [apache/incubator-mxnet#7204]
## Error Message:
python: can't open file 'tests/python/gpu/test_conv.py': [Errno 2] No such file or directory
not consistent with doc:
https://github.com/dmlc/mxnet/blame/master/docs/how_to/cloud.md#L105

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.go to doc : https://github.com/dmlc/mxnet/blame/master/docs/how_to/cloud.md#L105
2.go to https://github.com/dmlc/mxnet/tree/master/tests/python/gpu
3.see test_conv.py missing

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
