### ISSUE TITLE
Model parameter update

### ISSUE THREAD

**Issue by duyvuleo** [apache/incubator-mxnet#7209]
Hi,

I would like to **manually** update the model parameter(s) from module (either Module or BucketingModule). 

Assume that I have created a module for my network. 

I tried the following code:

```
updater = self.module._curr_module._updater
for ind, pair in enumerate(zip(self.module._curr_module._exec_group.param_arrays, new_grads)):
            # here, I don't want to use self.module._curr_module._exec_group.grad_arrays
            updater(index=ind, grad=pair[1][0], weight=pair[0][0])

arg_params, _ = self.module.get_params()  # sync aux params across devices
self.params.update(arg_params)
```

The above code does not work correctly. After this update, the model parameter seems to be much worse and worse. 

I am looking for your advice. Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
