### ISSUE TITLE
ConfusionMatrix in C++

### ISSUE THREAD

**Issue by smissan** [apache/incubator-mxnet#7210]
Is there an easy way to output a confusion matrix with C++ API?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
