### ISSUE TITLE
poor gpu performance with mx.io.ndarrayIter

### ISSUE THREAD

**Issue by Arielnabai** [apache/incubator-mxnet#7218]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Window
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.7.0
Python version and distribution:
2.7.12

The gpu works normal with a 60%+ gpu load in the  example/image_classfication/train_cifar10.py.
But when I try my own code with mx.io.ndarrayIter for the numpy array data,the gpu load keeps zero with cpu load increase。
The same question happens in the example /"End2End Captcha Recognition (OCR)" by xlvector github link Blog in Chinese.
Will it be solved once I change my data to .rec?And if there a guide on how to trans numpy array data to .rec format?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
