### ISSUE TITLE
[R] How to include a minimum function in MakeLoss

### ISSUE THREAD

**Issue by solalm** [apache/incubator-mxnet#7219]
Hi, I am trying under R to use a constant as minimum for instance in a custom MAE loss function to cap it at 1. How do I do that?

Tried:
lro2<-mx.symbol.MakeLoss(mx.symbol.min(mx.symbol.abs(mx.symbol.Reshape(fc3, shape = 0) - label),1.0),name="lro2")

Which returns:
Error in mx.varg.symbol.min(list(...)) : 
  symbol.cc:302: RCheck failed: keys[i].length() != 0 Non Symbol parameters is only accepted via key=value style.

Thanks!

**Comment by thirdwing** [comment]
Can you show the full example?

**Comment by solalm** [comment]
Hi, the idea is to create a custom MAE loss function (with cap) cf. #3368 [https://github.com/dmlc/mxnet/issues/3368](url).

  label <- mx.symbol.Variable("label")
  
  data <- mx.symbol.Variable("data")
  fc1 <- mx.symbol.FullyConnected(data, name="fc1", num_hidden=8)
  relu1 <- mx.symbol.Activation(fc1, name="relu1", act_type="relu")
  fc2 <- mx.symbol.FullyConnected(relu1, name="fc2", num_hidden=4)
  relu2<-mx.symbol.Activation(fc2, name="relu2", act_type="relu")
  fc3<- mx.symbol.FullyConnected(relu2, name="fc3", num_hidden=1)

  lro2<-mx.symbol.MakeLoss(mx.symbol.min(mx.symbol.abs(mx.symbol.Reshape(fc3, shape = 0) - 
  label),1.0),name="lro2")

Error in mx.varg.symbol.min(list(...)) :
symbol.cc:302: RCheck failed: keys[i].length() != 0 Non Symbol parameters is only accepted via key=value style.

Or I was trying to create a constant variable on which to run the min in MakeLoss, but can we in R define a constant value behind a symbol yet?...

  lossfloor <- mx.symbol.Variable("lossfloor")  # To be set to 1.0, but how?...
  lro2<-mx.symbol.MakeLoss(mx.symbol.min({mx.symbol.abs(mx.symbol.Reshape(fc3, shape = 0) - label);lossfloor}),name="lro2")

Thanks.

**Comment by thirdwing** [comment]
@solalm Can you try the code below. I am sorry that the function isn't exported correctly.

```r
library(mxnet)

label <- mx.symbol.Variable("label")

data <- mx.symbol.Variable("data")
fc1 <- mx.symbol.FullyConnected(data, name = "fc1", num_hidden = 8)
relu1 <- mx.symbol.Activation(fc1, name = "relu1", act_type = "relu")
fc2 <- mx.symbol.FullyConnected(relu1, name = "fc2", num_hidden = 4)
relu2 <- mx.symbol.Activation(fc2, name = "relu2", act_type = "relu")
fc3 <- mx.symbol.FullyConnected(relu2, name = "fc3", num_hidden = 1)
fc_abs <- mx.symbol.abs(mx.symbol.Reshape(fc3, shape = 0) - label)

lro2 <- mxnet:::mx.varg.symbol.internal.MinimumScalar(list(fc_abs, scalar = 1))
```

**Comment by solalm** [comment]
Thank you!

**Comment by thirdwing** [comment]
@solalm You will be able to use `mx.symbol.min(fc_abs, 1)` if you use the latest code.

The prebuilt pkg will contain the fix in next release.
