### ISSUE TITLE
I think mxnet is lack of a execution order iterator of a symbol

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#7228]
I think mxnet is lack of a execution order iterator of a symbol.
Usually, If a symbol is binded, the execution graph is determined. I want to iterate(traverse) the execution graph to get all node attributes by myself to calculate something useful such as receptive field(RF) size and RF offset of each layer but I can't do it now.
In addtional, given a symbol, how can I get the 'op' type of that symbol?

**Comment by chinakook** [comment]
I have write a graph iterator by myself. The way to do that is same to the mx.viz.plot_network function. Nervertheless, I want the official can provide a handy way.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
