### ISSUE TITLE
Custom Operator compute forward twice terminate with error

### ISSUE THREAD

**Issue by tonyyangToBeNo1** [apache/incubator-mxnet#7234]
Hi, I am new to Mxnet and recently when I implement some customOps and I get the following errors in the forward().
![image](https://user-images.githubusercontent.com/10970617/28708829-3da498e6-73b0-11e7-8395-e48e7e4b60ad.png)
However I print the params in forward_entry I find that the forward() in my customOp seems to be computed twice and combine the params together randomly. 
![image](https://user-images.githubusercontent.com/10970617/28708930-9fc74fb4-73b0-11e7-95a7-74a94206032c.png)
I just create the operator once and i have no idea why it can be computed twice. My mxnet version is 0.10.0 and my environment is ubantu14.04. 
my customOp is the following:
![image](https://user-images.githubusercontent.com/10970617/28709041-21835e58-73b1-11e7-8127-e761e7de037f.png)
Please give me a hint if someone has met the same error. Thanks for the helping!

**Comment by piiswrong** [comment]
your forward signiture is wrong. you need an is_train argument
