### ISSUE TITLE
How to use a classification pretrain model to train a triple-loss?

### ISSUE THREAD

**Issue by jerrywind** [apache/incubator-mxnet#7235]
Recently , I've tried to use mxnet to do some experiments about metric learning. 
Now I trained a multi-classification model by mxnet , and then use it as a `pretrain` model to train a triple-loss model, the problem is always that  :

    raise MXNetError(py_str(_LIB.MXGetLastError()))
    mxnet.base.MXNetError: [18:00:07] src/c_api/c_api_symbolic.cc:398: InferShapeKeyword argumentname label not found.
    Candidate arguments:
        [0]data
        [1]conv1_weight
        [2]conv1_bias
        [3]conv2_weight
        [4]conv2_bias
        [5]conv3_weight
        [6]conv3_bias
        [7]conv4_weight
        [8]conv4_bias
        [9]conv5_weight
        [10]conv5_bias
        [11]fc1_weight
        [12]fc1_bias
        [13]fc2_weight
        [14]fc2_bias
        [15]fc3_weight
        [16]fc3_bias
        [17]fc4_weight
        [18]fc4_bias
        [19]fc5_weight
        [20]fc5_bias
        [21]fc6_weight
        [22]fc6_bias
---- 

## Here is the multi-classification model : 

    def get_ocrnet():
        data = mx.symbol.Variable('data')
        label = mx.symbol.Variable('label')
        # stage 1
        conv1 = mx.symbol.Convolution(name='conv1',
                                      data=data, kernel=(5, 5), stride=(1, 1), num_filter=64)
        relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
        lrn1 = mx.symbol.LRN(data=relu1, alpha=0.0001, beta=0.75, knorm=2, nsize=5)
        pool1 = mx.symbol.Pooling(
            data=lrn1, pool_type="max", kernel=(3, 3), pad=(1, 1), stride=(2, 2))
        # stage 2
        conv2 = mx.symbol.Convolution(name='conv2',
                                      data=pool1, kernel=(5, 5), num_filter=128)
        relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
        lrn2 = mx.symbol.LRN(data=relu2, alpha=0.0001, beta=0.75, knorm=2, nsize=5)
        pool2 = mx.symbol.Pooling(data=lrn2, kernel=(3, 3), stride=(2, 2), pool_type="max")
        # stage 3
        conv3 = mx.symbol.Convolution(name='conv3',
                                      data=pool2, kernel=(3, 3), num_filter=256)
        relu3 = mx.symbol.Activation(data=conv3, act_type="relu")
        conv4 = mx.symbol.Convolution(name='conv4',
                                      data=relu3, kernel=(3, 3), num_filter=384)
        relu4 = mx.symbol.Activation(data=conv4, act_type="relu")
        conv5 = mx.symbol.Convolution(name='conv5',
                                      data=relu4, kernel=(3, 3), num_filter=512)
        relu5 = mx.symbol.Activation(data=conv5, act_type="relu")
        pool3 = mx.symbol.Pooling(data=relu5, kernel=(3, 3), pad=(1, 1), stride=(2, 2), pool_type="max")
        # stage 4
        flatten = mx.symbol.Flatten(data=pool3)
        fc1 = mx.symbol.FullyConnected(name='fc1', data=flatten, num_hidden=4096)
        relu6 = mx.symbol.Activation(data=fc1, act_type="relu")
        dropout1 = mx.symbol.Dropout(data=relu6, p=0.4)
        # stage 5
        fc2 = mx.symbol.FullyConnected(name='fc2', data=dropout1, num_hidden=4096)
        relu7 = mx.symbol.Activation(data=fc2, act_type="relu")
        dropout2 = mx.symbol.Dropout(data=relu7, p=0.4)
        # stage 6
        fc3 = mx.symbol.FullyConnected(name='fc3', data=dropout2, num_hidden=3002)
        label = mx.symbol.transpose(data=label)
        label = mx.symbol.Reshape(data=label, target_shape=(0,))
        return mx.symbol.SoftmaxOutput(data=fc3, label=label, name="softmax")

## here is the triple net:

    def get_triplet(symbol, arg_params, layer_name,len_size):
        all_layers = symbol.get_internals()
        label = all_layers['label']
        one = mx.sym.Reshape(data=label, shape=(-1,))
        one = np.ones_like(one)
        fc3 = all_layers[layer_name + '_output']
        fc4 = mx.symbol.FullyConnected(name='fc4', data=fc3, num_hidden=1048)
        fc5 = mx.symbol.FullyConnected(name='fc5', data=fc4, num_hidden=512)
        fc6 = mx.symbol.FullyConnected(name='fc6', data=fc5, num_hidden=128)
        l2 = mx.sym.L2Normalization(data=fc6)
        fa = mx.symbol.slice_axis(l2, axis=0, begin=0, end=len_size)
        fp = mx.symbol.slice_axis(l2, axis=0, begin=len_size, end=2 * len_size)
        fn = mx.symbol.slice_axis(l2, axis=0, begin=2 * len_size, end=3 * len_size)
        fs = fa - fp
        fd = fa - fn
        fs = fs * fs
        fd = fd * fd
        fs = mx.symbol.sum(fs, axis=1, keepdims=1)
        fd = mx.symbol.sum(fd, axis=1, keepdims=1)
        loss = fd - fs
        loss = one - loss
        loss = mx.symbol.Activation(data=loss, act_type='relu')
        #loss = triplet_loss(l2,one, len_size)
        net = mx.symbol.MakeLoss(loss)
        new_args = dict({k: arg_params[k] for k in arg_params if 'fc' not in k})
        return (net, new_args)

## the data are put in the model in the same ways, and the model train func here is :

    def train(path,train_txt,test_txt,train_model, pre_model,pre_epoch=20):
        devs = [mx.gpu(0)]
        batch_size = 120
    
        sym, arg_params, aux_params = mx.model.load_checkpoint(pre_model, pre_epoch)
        network,new_args = get_triplet(sym, arg_params,'fc3',batch_size//3)
        # network = get_triple_net(batch_size // 3)
    
        model =mx.model.FeedForward(
                symbol=network,
                num_epoch=30,
                ctx=devs,
                learning_rate=0.01,
    
                wd=0.00001,
                initializer=mx.init.Xavier(factor_type="in", magnitude=2.34),
                arg_params=new_args,
                aux_params=aux_params,
                momentum=0.9)
    
        data_train = OCRIter(batch_size, 1, path, train_txt)
        import logging
        head = u'%(asctime)-15s %(message)s'
        logging.basicConfig(level=logging.DEBUG, format=head)
        model.fit(X=data_train,
                  epoch_end_callback=mx.callback.do_checkpoint(train_model, 5),
                  batch_end_callback=mx.callback.Speedometer(batch_size, 50))
        model.save(train_model)

---

## Environment info
Operating System:
Ubuntu 14.04 LTS
Compiler:
GCC 4.8 
Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.10 release

Or if installed from source:

installed by pypi resource

## Error Message:
Please paste the full error message, including stack trace.

**Comment by jerrywind** [comment]
@thinxer @pluskid @darxriggs @ry @jamesliu

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by maybepossible** [comment]
请问现在代码正常了么？我也尝试用的类似代码，但是loss一直不降。
