### ISSUE TITLE
load multi models from different params & json files

### ISSUE THREAD

**Issue by dennisgu** [apache/incubator-mxnet#7257]
## Environment info
Operating System: Ubuntu 14.04 & 16.04

Compiler: gcc 4.8.4,  g++ 4.8.4

Package used (Python/R/Scala/Julia): Python

MXNet version:

Or if installed from source: master on 2017.05.25

Python version and distribution: Python 2.7

## Question:
I'm a beginner user of mxnet, and i've tried to use some neural networks and trained 3 different models(different .params and json files), the question is , how can i load the all 3 models from local .params & .json files in a single python process? Or is there any api that i can refer to ? 
Thanks in advance.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
