### ISSUE TITLE
when train fcn-xs for VOC,the train and val accuracy is always the same?

### ISSUE THREAD

**Issue by iFighting** [apache/incubator-mxnet#7259]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
centos
Compiler:
gcc 4.8.2
Package used (Python/R/Scala/Julia):
python
MXNet version:

Or if installed from source:
from source
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

![image](https://user-images.githubusercontent.com/6366788/28760147-fb1ad692-75d6-11e7-8884-7e54dfc676a5.png)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
