### ISSUE TITLE
Batch processing for rcnn prediction

### ISSUE THREAD

**Issue by YvesHarrison** [apache/incubator-mxnet#7279]
I want to send pictures to rcnn network for prediction by batch. Does the current rcnn function like im_detect() and Predictor() support this. If they do not support this function, what change should I do to achieve the goal?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
