### ISSUE TITLE
How to visualize the mxnet network written in json format?? 

### ISSUE THREAD

**Issue by ChidanandKumarKS** [apache/incubator-mxnet#7288]
How to visualize the mxnet network written in json format?? 

## Environment info
Operating System: Ubuntu 16.0.4.1

Compiler:

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.x

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 2.7.13

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by chinakook** [comment]
mx.viz.plot_network

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
