### ISSUE TITLE
Kernel crash with negative indices

### ISSUE THREAD

**Issue by nikrao** [apache/incubator-mxnet#7292]
It seems like if we use negative indices to access an mx.ndarray location, and convert to numpy, the python kernel crashes. 

EDIT: still the same with version 0.11

## Environment info
Operating System: Ubuntu

Package used (Python/R/Scala/Julia): Python

MXNet version: v.0.10.x

## Minimum reproducible example
`mx.__version__`
`0.11.0`

` a = mx.nd.array([1,2,3])`
`a[-1].asnumpy()`
`Segmentation fault (core dumped)`

Note that when I do a[-1], there is no error. It's only when converted to numpy. 

## STACK TRACE
[16:22:16] /home/ubuntu/src/mxnet/dmlc-core/include/dmlc/./logging.h:308: [16:22:15] src/ndarray/ndarray.cc:90: Check failed: begin < end (4294967295 vs. 0) Invalid slicing range [4294967295, 0)

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f46c0419f0c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet7NDArray5SliceEjj+0xd99) [0x7f46c1106b39]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet7NDArray2AtEj+0x3a) [0x7f46c1106f2a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(MXNDArrayAt+0x4e) [0x7f46c14af1ae]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f46d2b88e40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f46d2b888ab]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f46d2d983df]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f46d2d9cd82]
[bt] (8) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (9) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/ndarray.py", line 485, in __getitem__
    return self._at(key)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/ndarray.py", line 618, in _at
    self.handle, idx, ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:22:15] src/ndarray/ndarray.cc:90: Check failed: begin < end (4294967295 vs. 0) Invalid slicing range [4294967295, 0)

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f46c0419f0c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet7NDArray5SliceEjj+0xd99) [0x7f46c1106b39]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet7NDArray2AtEj+0x3a) [0x7f46c1106f2a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/libmxnet.so(MXNDArrayAt+0x4e) [0x7f46c14af1ae]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f46d2b88e40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f46d2b888ab]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f46d2d983df]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f46d2d9cd82]
[bt] (8) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (9) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by eric-haibin-lin** [comment]
Negative index should be supported since 1.0. Feel free to reopen it.
