### ISSUE TITLE
test_gluon_rnn.test_rnn_cells hang

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#7293]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: DL AMI

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):  861e929cec8fa8fbab06884d9605debb74cd7217

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
.... 
test_executor.test_dot ... ok
test_executor.test_reshape ... ok
test_gluon_data.test_array_dataset ... ok
test_gluon_data.test_recordimage_dataset ... --2017-08-01 18:07:26--  http://data.mxnet.io/data/test_images.tar.gz
Resolving data.mxnet.io (data.mxnet.io)... 54.208.175.7
Connecting to data.mxnet.io (data.mxnet.io)|54.208.175.7|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2211939 (2.1M) [application/x-gzip]
Saving to: ‘data/test_images.tar.gz’

100%[=================================================>] 2,211,939   2.57MB/s   in 0.8s

2017-08-01 18:07:27 (2.57 MB/s) - ‘data/test_images.tar.gz’ saved [2211939/2211939]

ok
test_gluon_data.test_sampler ... ok
test_gluon_model_zoo.test_concurrent ... ok
test_gluon_model_zoo.test_identity ... ok
test_gluon_model_zoo.test_models ... ok
test_gluon_rnn.test_rnn ... ok
test_gluon_rnn.test_lstm ... ok
test_gluon_rnn.test_lstm_forget_bias ... ok
test_gluon_rnn.test_gru ... ok
test_gluon_rnn.test_residual ... ok
test_gluon_rnn.test_residual_bidirectional ... ok
test_gluon_rnn.test_stack ... ok
test_gluon_rnn.test_bidirectional ... ok
test_gluon_rnn.test_zoneout ... ok
test_gluon_rnn.test_rnn_cells ... 
```
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. run `nosetests-2.7 -v ./tests/python/unittest/`, it hangs when it comes to `test_gluon_rnn.test_rnn_cells`. 
2.
3.

## What have you tried to solve it?

1. run `nosetests-2.7 -v ./tests/python/unittest/test_gluon_rnn.py`, but it successfully passes the test
2.
3.

**Comment by szha** [comment]
It indeed takes a lot longer for `nosetests -v unittest` to run through `test_gluon_rnn.test_rnn_cells` than for `nosetests -v unittest/test_gluon_rnn.py`. I have the same experience running it on my laptop.

The codes that this test is stuck at is the first invocation of the following function:
```
def check_rnn_forward(layer, inputs):
    layer.collect_params().initialize()
    with mx.autograd.record():
        layer.unroll(3, inputs, merge_outputs=True)[0].backward()
        mx.autograd.backward(layer.unroll(3, inputs, merge_outputs=False)[0])
    mx.nd.waitall()
```
By printing my way through the codes, it seems to be stuck at `mx.nd.waitall()` after it successfully exits the autograd.record(). I'm at a loss. @piiswrong what's your guess?

**Comment by szha** [comment]
It didn't help changing `mx.nd.waitall()` to
```
for param in layer.collect_params().values():
    param.grad().wait_to_read()
```

**Comment by piiswrong** [comment]
You can fix this by deleting test_gluon_model_zoo.py
so I think it's because test_gluon_model_zoo is slow and didn't wait for it's computation to finish

**Comment by szha** [comment]
You're right. I will add wait in model zoo tests.
