### ISSUE TITLE
Discussion and troubleshooting on PyPI (pip) Nightly Releases

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#7302]
As some of you might already know, the PyPI [mxnet](http://mxnet.io) installation has been available for a while. Recently, we enabled nightly build of the master branch as pip pre-releases. I'm opening this issue to collect feedbacks, suggestions and issue reports for the nightly pre-releases.

Supported variants:
- [mxnet](https://pypi.python.org/pypi/mxnet/) on both `OSX` and `Linux`, with CPU-only without MKL support.
- [mxnet-mkl](https://pypi.python.org/pypi/mxnet-mkl/) on both `OSX` and `Linux`, with CPU-only and with `MKL` support.
- [mxnet-cu75](https://pypi.python.org/pypi/mxnet-cu75/) on `Linux`, supports `CUDA-7.5`.
- [mxnet-cu80](https://pypi.python.org/pypi/mxnet-cu80/) on `Linux`, supports `CUDA-8.0`.
- [mxnet-cu75mkl](https://pypi.python.org/pypi/mxnet-cu75mkl/) on `Linux`, supports `CUDA-7.5` and `MKL`.
- [mxnet-cu80mkl](https://pypi.python.org/pypi/mxnet-cu80mkl/) on `Linux`, supports `CUDA-8.0` and `MKL`.

Users can install it via `pip install --pre --upgrade`. Be sure to update `pip` (`setuptools`) to the most recent version, by `pip install --upgrade pip`. 

For bug submissions on issues found in the pre-releases, one can find the corresponding commit hash from the package itself with the following command:
```
$ python -c 'import os, mxnet; print open(os.path.join(os.path.dirname(mxnet.__file__), "COMMIT_HASH")).readline().strip()'
```

**Comment by jmacglashan** [comment]
Only thing that comes to mind is that I ran into issue on my mac with the pip install of the latest version. I'm not sure if it's worthwhile to add some unit tests to this or if that just slows down the intent of a pre-release. Either way, on the latest 802 build, when I imported mxnet, I got the following error (I'm removing the path to the virtual env)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pyenv/lib/python3.5/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File ".../pyenv/lib/python3.5/site-packages/mxnet/base.py", line 69, in <module>
    _LIB = _load_lib()
  File ".../pyenv/lib/python3.5/site-packages/mxnet/base.py", line 61, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(.../mxpip/pyenv/lib/python3.5/site-packages/mxnet/libmxnet.so, 6): Symbol not found: _clock_gettime
  Referenced from: .../pyenv/lib/python3.5/site-packages/mxnet/libmxnet.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in .../pyenv/lib/python3.5/site-packages/mxnet/libmxnet.so
```

An earlier pre-release worked fine though.

**Comment by szha** [comment]
@jmacglashan thanks for reporting. I got other reports on the same issue too. It seems to be a compatibility problem with OSX framework that [affected many people](https://www.google.com/search?q=_clock_gettime). I currently have a fix and am verifying it now.

**Comment by szha** [comment]
@jmacglashan the fix should be on pypi now. Let me know if the issue still persists.

**Comment by jmacglashan** [comment]
Yep, works fine now. Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
