### ISSUE TITLE
resnet

### ISSUE THREAD

**Issue by niluanwudidadi** [apache/incubator-mxnet#7307]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 16.04
Compiler:
gcc 5.4
Package used (Python/R/Scala/Julia):

MXNet version:
0.10.1
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

Is there are resnet base pretrained model, such as vgg_reduced?

**Comment by edmBernard** [comment]
you can check this python script to download pre-trained model : 
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/common/modelzoo.py

**Comment by thirdwing** [comment]
@niluanwudidadi You can find pretrained models from http://data.dmlc.ml/models/

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
