### ISSUE TITLE
Validation Accuracy does not grow and stays in constant, running alexnet on ImageNet1k 

### ISSUE THREAD

**Issue by xingzhaoo** [apache/incubator-mxnet#7313]
I set exact same initial settings as alexnet paper suggested and ran alexnet on 1 machine in CPU only mode (kvstore='none'). The dataset is ImageNet1k (size=24G). But the val accuracy stays constant during initial 20 Epochs.   
Does anyone have any suggestion why the val accuracy does not grow for Alexnet?

![image](https://user-images.githubusercontent.com/15624862/28884313-5df8a146-777f-11e7-8f8b-6720970a073c.png)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by choudharykrish** [comment]
Pls reopen this issue..
