### ISSUE TITLE
Is there any plan to refactor the legacy Ops into nnvm?

### ISSUE THREAD

**Issue by mbrookhart** [apache/incubator-mxnet#7316]
Right now, primitive Tensor operations are directly registered with nnvm, but the legacy layer operations go through a more convoluted forward/backward wrapper to interact with nnvm and thus the graph executor.  After #6928 Is there any thought to refactor the legacy ops into the nnvm tensor primitive ops for easier graph optimization?

**Comment by piiswrong** [comment]
It's in the backlog. Currently we don't have people assigned on this

**Comment by mbrookhart** [comment]
Thanks.
