### ISSUE TITLE
where PS-lite implementation of server manager & hash ring ??

### ISSUE THREAD

**Issue by beyondli** [apache/incubator-mxnet#7320]
while reading the ps-lite model  , I can just find how server /work / scheduler created .but cannot find

1:**server manager** which handles the  hash ring management,  I just found the likely code in void Van::Receiving() fun
              int id = node.role == Node::SERVER ?
                       Postoffice::ServerRankToID(num_servers_) :
                       Postoffice::WorkerRankToID(num_workers_);
   are these the so called "direct-mapped DHT design" in the Mu Li paper OSDI 2014? 
   so where is hash ring and server  manager ,so not implemented yet or in some models I just not found??

2: since no hash ring found ,  **"virtual" servers** which can improve LB and recovery are also not found.

so where **consistent Hashing** in paper delcared in mxnet, since it is so important in distributed Machine Learning

anyone help is appreciated in andance!!

**Comment by formath** [comment]
The new version of ps-lite has no hash ring.

**Comment by beyondli** [comment]
1:if no hash ring , what kind of policy to implement **consistent Hashing**?since this is such important factor to scale server node ??

2:all the node (server/worker) managment is coded in van.cc, rigint??

3:seems code below is hash coded or not , it just linear transformation from rank to ID, even not the simplest linear hash.
int id = node.role == Node::SERVER ?
Postoffice::ServerRankToID(num_servers_) : 
Postoffice::WorkerRankToID(num_workers_);

4:why remove hash ring in new version? Is there better method instead of hash ring?? if not , how to improve load balance  that server node added or removed dynamiclly hash ring can solve better??

thanks!!

**Comment by formath** [comment]
It makes the system too complicated and actually has rare use in training. I don't see anyone who needs to dynamically add or remove nodes during training.

**Comment by beyondli** [comment]
@formath , I see, thank you! hope mxnet can becom better and better!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
