### ISSUE TITLE
Imperative Programs Tend to be More Flexible (but do not make much sense ;)

### ISSUE THREAD

**Issue by tomisilander** [apache/incubator-mxnet#7333]
In  http://mxnet.io/architecture/program_model.html , there is a python code:

```
a = 2
b = a + 1
d = np.zeros(10)
for i in range(d):
    d += np.zeros(10)
```
that does not run (range(d) ??) and adding zeros to zeros does not make much sense either.
I do not really get what is the intended message.

ts.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
