### ISSUE TITLE
cannot use ImageIter in Perl package

### ISSUE THREAD

**Issue by dokechin** [apache/incubator-mxnet#7334]
## Environment info
Operating System:
Mac OS

Package used (Python/R/Scala/Julia):
Perl

MXNet version:
0.10.0

## Error Message:
loading image list...
Use of uninitialized value $fname in concatenation (.) or string at /Users/user/perl5/lib/perl5/AI/MXNet/Image.pm line 866.

## Minimum reproducible example
 use AI::MXNet qw('mx');                                                     
  my $ite = mx->img->ImageIter(
     { batch_size => 1, data_shape=> [3,224,224],label_width =    >1, path_imglist => "data/custom.lst"});
   for $data (@{$ite}){
     print $data->[0];
   }

custom.lst is separated by tab
1 1 data/test.jpg

**Comment by sergeykolychev** [comment]
@dokechin thanks for testing, I'll check what's going on.

**Comment by sergeykolychev** [comment]
@dokechin 
Looks like custom.lst 
supposed to be in a format of 
id label filename
you currently have 
id filename
however I do see a bug in the imageIter
Try applying this patch and fixing your custom.lst as well
```
diff --git a/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm b/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
index 50e4a41..93829c5 100644
--- a/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
+++ b/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
@@ -747,7 +747,7 @@ sub BUILD
         {
             chomp($line);
             my @line = split(/\t/, $line);
-            my $label = AI::MXNet::NDArray->array([@line[1..@line-1]]);
+            my $label = AI::MXNet::NDArray->array([@line[1..@line-2]]);
             my $key   = $line[0];
             $imglist{$key} = [$label, $line[-1]];
             push @imgkeys, $key;
```

**Comment by dokechin** [comment]
I changed source code and custom.lst file.
And tried again.
But same error has occurred. at line 866.

**Comment by sergeykolychev** [comment]
@dokechin Ok, let's do some debugging. Can you please send me your script and custom.lst (no images needed) and I'll try to get to the bottom of this. The Image.pm is battle untested yet and hopefully with your help we can get get it working.

**Comment by dokechin** [comment]
@sergeykolychev Thank you very much. I upload files.
[image.pl.zip](https://github.com/apache/incubator-mxnet/files/1202781/image.pl.zip)
[custom.lst.zip](https://github.com/apache/incubator-mxnet/files/1202782/custom.lst.zip)

**Comment by sergeykolychev** [comment]
@dokechin 
Thank you. Let's move to next level of our debugging. I've fixed your immediate problem and the data is being loaded. Try to plug in this iter into  mxnet and train something, we'll see if you hit any snugs.
Here's the patch to the Image.pm that fixes the bugs:
```developer@devbox:~/mxnet/perl-package/AI-MXNet$ git diff
diff --git a/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm b/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
index 50e4a41..e61d1a4 100644
--- a/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
+++ b/perl-package/AI-MXNet/lib/AI/MXNet/Image.pm
@@ -747,7 +747,7 @@ sub BUILD
         {
             chomp($line);
             my @line = split(/\t/, $line);
-            my $label = AI::MXNet::NDArray->array([@line[1..@line-1]]);
+            my $label = AI::MXNet::NDArray->array([@line[1..@line-2]]);
             my $key   = $line[0];
             $imglist{$key} = [$label, $line[-1]];
             push @imgkeys, $key;
@@ -821,6 +821,10 @@ sub BUILD
     {
         $self->aug_list(AI::MXNet::Image->CreateAugmenter(data_shape => $self->data_shape, %{ $self->kwargs//{} }));
     }
+    else
+    {
+        $self->aug_list([]);
+    }
     $self->cur(0);
     $self->reset();
 }
@@ -860,7 +864,7 @@ method next_sample()
         }
         else
         {
-            my ($label, $fname) = $self->imglist->{$idx};
+            my ($label, $fname) = @{ $self->imglist->{$idx} };
             if(not defined $self->imgrec)
             {
                 open(F, $self->path_root . "/$fname") or confess("can't open $fname $!");

```
And here is patched image.pl script with correct usage:
```
#!/usr/bin/perl

## a bit modified
## added path_root
## $data is not an array but an object of class AI::MXNet::DataBatch
use AI::MXNet qw('mx');
use Data::Dumper;
my $ite = mx->img()->ImageIter(
{  batch_size => 1, data_shape=> [3,224,224],label_width =>1, path_imglist => "custom.lst", path_root => '.' });
for $data (@{$ite}){
  print Dumper($data);
  print $data->data->[0]->aspdl;
  print $data->label->[0]->aspdl;
}
```

**Comment by dokechin** [comment]
I tried and succeeded!
I appreciate prompt response.

**Comment by sergeykolychev** [comment]
@dokechin Thank you, please report if you'll have any problems, I greatly appreciate your testing.
I've just released fixed Image.pm to CPAN along with some other stuff.
You can see the changes here https://github.com/apache/incubator-mxnet/pull/7357
hopefully it'll soon be merged into master.
Thanks!

**Comment by sergeykolychev** [comment]
@dokechin the changes to Image.pm were merged to master branch.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
