### ISSUE TITLE
time series delay output mxnet

### ISSUE THREAD

**Issue by kurt-o-sys** [apache/incubator-mxnet#7349]
## Question

Having a rnn to predict a point in time, based in indirect inputs. This is not the 'normal' time series prediction in which the future is predicted on previous values, but for which a certain curve property is predicted on a bunch of indirectly related features. When training, the first S (let's say 50) outputs will not be accurate at all. 

During training, I will have to provide at least 51 inputs (and hence, there will be 51 outputs as well - 1 output per input). Let's call this number T. I'd only like to use only the last outputs (T-50) for the parameter/weights estimation during training, omitting the first S. How can I do/achieve that in mxnet?

## Environment info
This is not really relevant, but well, I don't mind providing it :)

Operating System:
```
$ uname -ar
Linux flipflap 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Compiler: ?

Package used (Python/R/Scala/Julia): R

MXNet version:
```
> packageVersion("mxnet")
[1] ‘0.10.1’
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_BE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_BE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mxnet_0.10.1 httr_1.2.1   jsonlite_1.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12       compiler_3.4.1     RColorBrewer_1.1-2 influenceR_0.1.0   plyr_1.8.4         bindr_0.1          viridis_0.4.0     
 [8] tools_3.4.1        digest_0.6.12      tibble_1.3.3       gtable_0.2.0       viridisLite_0.2.0  rgexf_0.15.3       pkgconfig_2.0.1   
[15] rlang_0.1.1        igraph_1.1.2       rstudioapi_0.6     curl_2.4           bindrcpp_0.2       gridExtra_2.2.1    stringr_1.2.0     
[22] DiagrammeR_0.9.0   dplyr_0.7.2        htmlwidgets_0.9    grid_3.4.1         glue_1.1.1         R6_2.2.2           Rook_1.1-1        
[29] XML_3.98-1.9       ggplot2_2.2.1      magrittr_1.5       codetools_0.2-15   scales_0.4.1       htmltools_0.3.6    assertthat_0.1    
[36] colorspace_1.3-2   brew_1.0-6         stringi_1.1.5      visNetwork_2.0.1   lazyeval_0.2.0     munsell_0.4.3    
```

**Comment by jeremiedb** [comment]
If I understand well, your need is similar to a one-to-one RNN structure in which the first 50 outputs are ignored. 

If you're not already using it, I think it would be worth looking at the `mx.symbol.RNN` which provides a convenient abstraction for working with of recurrent structure. In short, it takes as input a data of dims batch_size x sequence_length and its output is of dims hidden_features x batch_size x sequence_length. For your need, you could slice that output to remove the first 50 elements of the sequence_length dimension and then proceed to the decoding and application of the output layer as usual. 

Not sure if the model might crash because some elements of the RNN outputs end nowhere because of the slicing. If it's the case, it could do a dummy trick such as multiplying by 0 these first 50 outputs and merge back to the rest for decoding. 

I don't have code that do exactly that, but I'm currently looking to bring that RNN structure into the general R API, you can take a look at the WIP here so see how to deal with `mx.symbol.RNN`: https://github.com/jeremiedb/mxnet_R_bucketing/blob/master/blog/Blog_LSTM_NLP_Classification.Rmd

**Comment by kurt-o-sys** [comment]
Thx for you answer... It is a one-to-one RNN indeed, unfolded, I'd like to have a 'many-to-one'. Every time frame, a 'summary' of the events are added to the AI system. Here's how the network (more or less) looks like. 

![image](https://user-images.githubusercontent.com/2430465/29090285-50aea288-7c7f-11e7-8efa-126e545ac861.png)

If I would unfold it, in the scenario described above, I'd have 51 times the same structure next to each. I would like to have only 1 output (the last one) during training. Setting to 0 is not really an option, since this would intervene with the training: a value of 0 is not the same as something that has more a meaning as 'not available yet'. 
(During usage of the trained network, the errors made during the first outcomes are less important. It's just that at the start of the 'game', one just knows that the game state is still unsure. Only after a number of iterations, this improves towards how the game actually evolves).

I still wonder how to achieve it, or stated another way, how I can 'remove the first x elements of the sequence_length' in a one-to-one RNN.

**Comment by kurt-o-sys** [comment]
Oh yeah, this may be important: I'm defining the model separately from the training data:

```
input <- mx.symbol.Variable("data")

guess.add <- mx.symbol.slice(input, name=guesses added/removed",
                             begin=0, end=7)
...
game.trend <- mx.symbol.RNN(..., name="game trend", 
                        mode="gru", num.layers=1, state.size=1)
regression <- mx.symbol.LinearRegressionOutput(lpeaks, name="final regression")
```

I asked the question above before getting into the mxnet api itself. The question would be: do I need to unroll it first, so I can use mx.model.FeedForward.create to train it? Or is there a way to use the model as it is and feed it with a time-series dataset for training?

**Comment by jeremiedb** [comment]
symbol.RNN performs the unrolling. 
Taking a minimal example: 

```
data <- mx.symbol.Variable("data")
rnn.weight <- mx.symbol.Variable("rnn.weight")
rnn <- mx.symbol.RNN(data = data, num.layers=1, state.size=10)
regression <- mx.symbol.LinearRegressionOutput(data=rnn, name="final regression")
```
Here a sequence of length 51 with batch of 64 and 20 features and sent into a RNN which outputs 1 output for each of the 51 elements of fed into the model.

![graph0](https://user-images.githubusercontent.com/18605903/29151649-bc5f7260-7d50-11e7-8e55-441c416aaf4f.png)

If taking the last element of the sequence, you then feed only the latest (51th element) into the regression output. 

![graph1](https://user-images.githubusercontent.com/18605903/29151650-bf8b7506-7d50-11e7-8a19-71e5c933b704.png)

You might need to hack a little the FeedForward function to account for extra parameters required by the RNN cell. The [symbol documentation](http://mxnet.io/api/python/symbol.html) should provide the required tool to adapt the network according to your needs.

**Comment by kurt-o-sys** [comment]
OK... I'm not sure if I get it. I'll have to play a little more, I guess. Training the above network:

    mx.model.FeedForward.create(regression, X=...,  ...)

Right? Since the network is unrolled, it can be considered as a normal FeedForward model? (It looks a bit odd to me to put `FeedForward` to train the rnn, and I actually want to have a rnn as a result, so I continuously add new data).
