### ISSUE TITLE
Multi-Training-Task on the same GPU card

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#7350]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
centos-7.2
Compiler:
gcc-4.8.5
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.3
Or if installed from source:
installed from source
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide
python-2.7
Python version and distribution:
python-2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
When I run a single process on a single gpu card, I got about 56 samples/sec; 
When I run two single process on a single gpu card, I got about 27 samples/sec
I think it is mainly the band-width in IO for GPU which cause the low trainning speed
How can I run multi-trainning-task on the sample single GPU card with a high training performence?
And My GPU's version is k40(12G)

Thank you very much!

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by idealboy** [comment]
when trainning, the following problem occurs:
（1）One trainning task on one gpu card(k40c, 12G)，batchsize=64的，59 samples/ s ec;
 (2) Two sample trainning task on one gpu card(k40c, 12G)，batchsize=32， 27samples / sec

why? Thank you very much!

**Comment by edmBernard** [comment]
You have two training at 27 samples/sec each one ?
GPU have power processing so if one training use 100% the second need to wait even if they share the memory. 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0     Off |                  N/A |
| 29%   44C    P8    14W / 151W |      0MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                              ^
                                                              |
                                                              |
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
