### ISSUE TITLE
The intellisence support for mxnet with Python

### ISSUE THREAD

**Issue by dbsxdbsx** [apache/incubator-mxnet#7351]
Operating System: Linux,
Compiler:  Vscode,Pycharm
Package used (Python/R/Scala/Julia): Python 2.7.13
MXNet version:  0.10.1
---------------------------------------------------------
After installing mxnet,  I found I  could get intellisense when typing  "mx.io." , but no intellisense when typing "mx.sym.",say looking for "flatten".

I wonder whether there is some setting I missed?

**Comment by jmacglashan** [comment]
I think this is because sym points to symbol and in general, many references, like operators, currently don't show up in autocomplete. The 1.0 roadmap issue (#7319) raises this point and possible solutions to have full auto completion support.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
