### ISSUE TITLE
AI-MXNet 'make test' failed.

### ISSUE THREAD

**Issue by mtakanobu** [apache/incubator-mxnet#7353]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-30-generic x86_64)

Compiler:gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

Package used (Python/R/Scala/Julia):perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
with AI-MXNet-1.0101,AI-MXNetCAPI-1.0101,AI-NNVMCAPI-1.01

MXNet version:0.10.0

Or if installed from source:

MXNet commit hash:b2360f4ff5cccbcf09a780d8065ecc4a64ce470f
If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

AI-MXNet 'make test' failed.
In next test.
1.test_autograd.t
2.test_model_parallel.t

I attach detail log files.
[test_autograd_log.txt](https://github.com/apache/incubator-mxnet/files/1203087/test_autograd_log.txt)
[test_model_parallel_log.txt](https://github.com/apache/incubator-mxnet/files/1203088/test_model_parallel_log.txt)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.Uninstall AI-MXNet,AI-MXNetCAPI,AI-NNVMCAPI and 'make clean' for MXNet.
2.Rebuild MXNet with GoogleTest.
3.Reinstall AI-NNVMCAPI and AI-MXNetCAPI.
4.Rebuild AI-MXNet.(Now I'm here.)

**Comment by sergeykolychev** [comment]
@mtakanobu you're right, these test became invalid because of the changes made in upstream C++ and C code.
This pull https://github.com/apache/incubator-mxnet/pull/7343 removes these tests (I'll read fixed tests later) for now and puts Perl API under CI unit tests.

**Comment by mtakanobu** [comment]
@sergeykolychev thanks.
