### ISSUE TITLE
[API missing] mx.nd.stack & mx.sym.stack

### ISSUE THREAD

**Issue by Lyken17** [apache/incubator-mxnet#7355]
Hi there

I found `mx.nd.stack` description on [web documents](http://mxnet.io/api/python/ndarray.html?highlight=stack#mxnet.ndarray.stack), however, in latest `mxnet` this API no longer exists, is it removed?

```python
In [1]: import mxnet as mx

In [2]: mx.__version__
Out[2]: '0.10.0'

In [3]: a = mx.nd.array([0,1,2])

In [4]: mx.nd.stack(a, a)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-09d48e52dd59> in <module>()
----> 1 mx.nd.stack(a, a)

AttributeError: 'module' object has no attribute 'stack'
```

**Comment by piiswrong** [comment]
you need to install the nightly build with pip install --pre

**Comment by Lyken17** [comment]
@piiswrong Thanks. Perhaps it is better to indicate `nightly build` on web documents? Find APIs on documents but not in code is kinda frustrating.

**Comment by Lyken17** [comment]
Solved.
