### ISSUE TITLE
Compile MXNet error: no matching function for call to ‘std::vector<unsigned int*>::push_back

### ISSUE THREAD

**Issue by lnuchiyo** [apache/incubator-mxnet#7359]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:  ubuntu 16.04
Package used (Python/R/Scala/Julia): python
MXNet version: mxnet (0.10.1)
i am  using python package ,
 
 when i do this:
cd ${MXNET_ROOT}
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1

there are some error:
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -I/home/cs/mxnet/mshadow/ -I/home/cs/mxnet/dmlc-core/include -fPIC -I/home/cs/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMSHADOW_USE_CUDNN=1  -I/home/cs/mxnet/cub -DMXNET_USE_NVRTC=0 -MMD -c src/operator/custom/ndarray_op.cc -o build/src/operator/custom/ndarray_op.o
In file included from src/operator/custom/native_op.cc:7:0:
src/operator/custom/./native_op-inl.h: In member function ‘virtual bool mxnet::op::NativeOpProp::InferShape(std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*) const’:
src/operator/custom/./native_op-inl.h:204:36: ****error: no matching function for call to ‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’
       shapes.push_back(iter->data());
                                    ^
In file included from /usr/include/c++/5/vector:64:0,
                 from /home/cs/mxnet/dmlc-core/include/dmlc/logging.h:13,
                 from src/operator/custom/./native_op-inl.h:10,
                 from src/operator/custom/native_op.cc:7:
/usr/include/c++/5/bits/stl_vector.h:913:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(const value_type& __x)
       ^
/usr/include/c++/5/bits/stl_vector.h:913:7: note:   no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/usr/include/c++/5/bits/stl_vector.h:931:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(value_type&& __x)
       ^
/usr/include/c++/5/bits/stl_vector.h:931:7: note:   no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
In file included from src/operator/custom/ndarray_op.cc:7:0:
src/operator/custom/./ndarray_op-inl.h: In member function ‘virtual bool mxnet::op::NDArrayOpProp::InferShape(std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*) const’:

is anyone here,can help me to deal with it?

**Comment by ElPatou** [comment]
I am having the same issue when trying to compile MX-Net 0.1.0 for FGFA https://github.com/msracver/Flow-Guided-Feature-Aggregation

I simply followed the procedure from the FGFA github but it still does not work smoothly.
Note: I manually updated the cub module to its former location (https://github.com/NVlabs/cub), so I should get the version 0.1.0 with all the correct submodules right?

Which version of gcc and cuda, cudnn libraries do you recommend for that particular version?
Thanks

**Comment by selinachenxi** [comment]
@ElPatou I installed FGFA without problem follow the instruction except when build mxnet with GPU
`make -j 4 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`
I am using cuda 8 + cudnn 6

**Comment by ElPatou** [comment]
@selinachenxi  Thanks, I also installed that way using instructions from MXNet website. My issue was with OpenCV: make -j4 USE_OPENCV=0 USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudh2290** [comment]
@sxjscience  can you please remove "Need Triage" label and add "Build" "Question" labels.
