### ISSUE TITLE
I checkout to MXNet@(commit 62ecb60),then compile mxnet error,but when i dont checkout to MXNet@(commit 62ecb60),compile successfully!!

### ISSUE THREAD

**Issue by tianhaijie** [apache/incubator-mxnet#7360]
First,I clone mxnet ,if I compile,it's ok
But when i try to checkout to MXNet@(commit 62ecb60) by git checkout 62ecb60
And I compile again,it fails!!!
## Environment info
Operating System:CentOS release 6.5

Package used (Python/R/Scala/Julia):python

Python version and distribution:python2.7

## Error Message:
In file included from src/operator/custom/ndarray_op.cc:7:0:
src/operator/custom/./ndarray_op-inl.h: 在成员函数‘virtual bool mxnet::op::NDArrayOpProp::InferShape(std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*) const’中:
src/operator/custom/./ndarray_op-inl.h:116:36: 错误：对‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’的调用没有匹配的函数
       shapes.push_back(iter->data());
                                    ^
src/operator/custom/./ndarray_op-inl.h:116:36: 附注：备选是：
In file included from /data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/vector:64:0,
                 from /data1/NLPRMNT/fujun/tianhj/test_mxnet/mxnet/dmlc-core/include/dmlc/logging.h:13,
                 from src/operator/custom/./ndarray_op-inl.h:10,
                 from src/operator/custom/ndarray_op.cc:7:
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(const value_type& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(value_type&& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
In file included from src/operator/custom/custom.cc:7:0:
src/operator/custom/./custom-inl.h: 在成员函数‘virtual bool mxnet::op::CustomOpProp::InferShape(std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*) const’中:
src/operator/custom/./custom-inl.h:190:36: 错误：对‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’的调用没有匹配的函数
       shapes.push_back(iter->data());
                                    ^
src/operator/custom/./custom-inl.h:190:36: 附注：备选是：
In file included from /data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/vector:64:0,
                 from /data1/NLPRMNT/fujun/tianhj/test_mxnet/mxnet/dmlc-core/include/dmlc/logging.h:13,
                 from src/operator/custom/./custom-inl.h:10,
                 from src/operator/custom/custom.cc:7:
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(const value_type& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(value_type&& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
In file included from src/operator/custom/native_op.cc:7:0:
src/operator/custom/./native_op-inl.h: 在成员函数‘virtual bool mxnet::op::NativeOpProp::InferShape(std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*, std::vector<nnvm::TShape>*) const’中:
src/operator/custom/./native_op-inl.h:204:36: 错误：对‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’的调用没有匹配的函数
       shapes.push_back(iter->data());
                                    ^
src/operator/custom/./native_op-inl.h:204:36: 附注：备选是：
In file included from /data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/vector:64:0,
                 from /data1/NLPRMNT/fujun/tianhj/test_mxnet/mxnet/dmlc-core/include/dmlc/logging.h:13,
                 from src/operator/custom/./native_op-inl.h:10,
                 from src/operator/custom/native_op.cc:7:
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(const value_type& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(value_type&& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
src/operator/custom/custom.cc: 在成员函数‘virtual mxnet::Operator* mxnet::op::CustomOpProp::CreateOperatorEx(mxnet::Context, std::vector<nnvm::TShape>*, std::vector<int>*) const’中:
src/operator/custom/custom.cc:166:34: 错误：对‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’的调用没有匹配的函数
     shapes.push_back(iter->data());
                                  ^
src/operator/custom/custom.cc:166:34: 附注：备选是：
In file included from /data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/vector:64:0,
                 from /data1/NLPRMNT/fujun/tianhj/test_mxnet/mxnet/dmlc-core/include/dmlc/logging.h:13,
                 from src/operator/custom/./custom-inl.h:10,
                 from src/operator/custom/custom.cc:7:
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(const value_type& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:901:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
       push_back(value_type&& __x)
       ^
/data1/NLPRMNT/fujun/local/gcc-4.8.4/include/c++/4.8.4/bits/stl_vector.h:919:7: 附注：  no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
In file included from src/operator/custom/native_op.cc:7:0:
src/operator/custom/./native_op-inl.h: In instantiation of ‘void mxnet::op::NativeOp<xpu>::SyncVec(const std::vector<mxnet::TBlob>&, const string&, mshadow::Stream<Device>*, int) [with xpu = mshadow::cpu; std::string = std::basic_string<char>]’:
src/operator/custom/native_op.cc:27:1:   required from here
src/operator/custom/./native_op-inl.h:146:66: 错误：从类型‘const dim_t* {aka const long int*}’到类型‘mxnet::index_t* {aka unsigned int*}’中的 const_cast 无效
       shapes.push_back(const_cast<index_t*>(vec[i].shape_.data()));
                                                                  ^
make: *** [build/src/operator/custom/native_op.o] 错误 1
make: *** 正在等待未完成的任务....
make: *** [build/src/operator/custom/custom.o] 错误 1
make: *** [build/src/operator/custom/ndarray_op.o] 错误 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by edmBernard** [comment]
There is a issue to checkout an old version of MXNet du to a change in the Cub Module.
You can try this : https://github.com/apache/incubator-mxnet/issues/6891

**Comment by tianhaijie** [comment]
Hi, @edmBernard  Actually,when i use git checkout 62ecb60,i got
M	cub
M	dmlc-core
M	mshadow
M	nnvm
HEAD is now at 62ecb60... Add 'argnum' for autograd (#5787)
it seems that mxnet is at 62ecb60 
Then i use git submodule update,i got
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'
it seems git submodule update doesn't work!And I think the problem might be here

**Comment by edmBernard** [comment]
yeah try the method in this issue : https://github.com/apache/incubator-mxnet/issues/6891.
that allow to correctly ckeckout before the cub change

**Comment by tianhaijie** [comment]
@edmBernard Thank you for your attention!!I find a solution at stackoverflow,now,it seems everything is ok now.... The main reason for this problem is that i cannot fully understand what git submodule do...Anyway,thanks again!!

**Comment by edmBernard** [comment]
Mxnet change Cub repository from NVLab to dmlc because there is a size issue on official history. 
now cub -> dmlc/cub
before cub -> NVLAB/cub
when you clone you are on  dmlc/cub repository. if you try to checkout to 89de7ab this hash don't exist on the dmlc/cub repository. It's a hash from NVLAB/cub so it fail.

**Comment by tianhaijie** [comment]
@edmBernard Yeah,it's help for me!
cool!!Thanks!
