### ISSUE TITLE
training speed of batch-norm is less than batch-norm-v1

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#7361]
if set `use_global_stats=True` then the training speed of batch-norm is less than batch-norm-v1, so what's the change the newer batch-norm?

**Comment by chinakook** [comment]
Is the cudnn_off = False ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
