### ISSUE TITLE
import mxnet errors

### ISSUE THREAD

**Issue by stmatengss** [apache/incubator-mxnet#7362]
## Description
If I use pip(which is provided by OS, is not the version through get-pip.py script) to install mxnet, there are some errors occur when I run "import mxnet as mx".

## Environment info
Operating System:
Ubuntu 14.04 

Compiler:
gcc 4.8.4

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.10.0.post2

MXNet commit hash (`git rev-parse HEAD`):

Python version and distribution:
python 2.7

## Error Message:

---------------------------------------------------------------------------                             
OSError                                   Traceback (most recent call last)                             
<ipython-input-1-cb88d04c42ec> in <module>()                                                            
----> 1 import mxnet as mx                                                                              
                                                                                                        
/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py in <module>()                                  
      5                                                                                                 
      6 from .context import Context, current_context, cpu, gpu                                         
----> 7 from .base import MXNetError                                                                    
      8 from . import base                                                                              
      9 from . import contrib                                                                           
                                                                                                        
/usr/local/lib/python2.7/dist-packages/mxnet/base.py in <module>()                                      
     50 __version__ = libinfo.__version__                                                               
     51 # library instance of mxnet                                                                     
---> 52 _LIB = _load_lib()                                                                              
     53                                                                                                 
     54 # type definitions                                                                              
                                                                                                        
/usr/local/lib/python2.7/dist-packages/mxnet/base.py in _load_lib()                                     
     42     """Load libary by searching possible path."""                                               
     43     lib_path = libinfo.find_lib_path()                                                          
---> 44     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)                                          
     45     # DMatrix functions                                                                         
     46     lib.MXGetLastError.restype = ctypes.c_char_p                                                
                                                                                                        
/usr/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error) 
    363                                                                                                 
    364         if handle is None:                                                                      
--> 365             self._handle = _dlopen(self._name, mode)                                            
    366         else:                                                                                   
    367             self._handle = handle                                                               
                                                                                                        
OSError: /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so: invalid ELF header                   

## Minimum reproducible example
I don't use `wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py`, and I directly use the pip which provided by OS. The pip version is `pip-1.5.4`.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. I try to uninstall my pip and use the pip which gained through `get-pip.py`. After that, mxnet is running normally.
2.
3.

**Comment by szha** [comment]
pip 1.5.4 is too old, so you might have got a wrong version of mxnet.

**Comment by BenLag2906** [comment]
Hi,

I have the same problem when i try to import package under python : 

********************************
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet\__init__.py", line 25, in <module>
    from .base import MXNetError
  File "mxnet\base.py", line 86, in <module>
    _LIB = _load_lib()
  File "mxnet\base.py", line 78, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Le module spÚcifiÚ est introuvable
**********************************************

I recompiling this morning with the HEAD.

And I launch the command after compilation: 'python setup.py install'

I work on windows 10.

Could you please give an advise ?

regards

**Comment by szha** [comment]
Windows pip wheels are provided now for `mxnet` and `mxnet-cu80` (CUDA8.0 support) packages. You can try it by invoking `pip install -U --pre mxnet`.

Feel free to reopen if it's still an issue.
