### ISSUE TITLE
MxnetR chunk-wise neural nets

### ISSUE THREAD

**Issue by train-test-laura** [apache/incubator-mxnet#7364]
Dear all,

I just now started using the mxnet R package in Windows. 

I have a pretty big dataset which I need to process in chunks due to memory limits. Therefore, I split my dataset and wanted to run a feed-forward  neural net on chunk 1, and use the parameters (weights and bias) for chunk 2 , which in turn can be used for chunk 3, and so on. However, despite some examples (https://statist-bhfz.github.io/cats_dogs_finetune) I cannot figure out how to get that to work.

My model looks like that:
```
## set up neural network
data <- mx.symbol.Variable("data")
fc1 <- mx.symbol.FullyConnected(data, name="fc1", num_hidden=150)
act1 <- mx.symbol.Activation(fc1, name="relu1", act_type="relu")
fc2 <- mx.symbol.FullyConnected(act1, name="fc2", num_hidden=100)
softmax <- mx.symbol.SoftmaxOutput(fc2, name="sm")

prefix='Checkpoints/chkpt'
## train
system.time(model <- mx.model.FeedForward.create(softmax, X=train.x, y=train.y,
                                                 ctx=devices, num.round=20, array.batch.size=200,
                                                 learning.rate=0.09, momentum=0.9,  eval.metric=mx.metric.accuracy,
                                                 optimizer='sgd', 
                                                 epoch.end.callback=mx.callback.save.checkpoint(prefix),
                                                 batch.end.callback=mx.callback.log.speedometer(200, frequency = 200)))

```
and now I tried to follow other posts and used 
```
net001<- mx.model.load(prefix, iteration=20)

symbol<- net001$symbol
internals<- symbol$get.internals()
outputs<- internals$outputs

arg_params_batch1<- net001$arg.params
fc1_weights_batch1<- arg_params_batch1[["fc1_weight"]]
fc2_weights_batch1<- arg_params_batch1i[["fc2_weight"]]
```

But now I am unsure how to use the weights and bias for the next batch of mx.model.FeedForward.create. 
Any hint would be greatly appreciated.
Thank you,
Best, Laura

**Comment by thirdwing** [comment]
I think we have a document on similar situations: https://github.com/apache/incubator-mxnet/blob/master/R-package/vignettes/CatsDogsFinetune.Rmd#load-pretrained-model

Let me know if this helps.

**Comment by train-test-laura** [comment]
Thanks for your reply.

I have found that page already pretty helpful, but there are a few questions I have - maybe you or someone else could help me.

First of, I am not sure what the output named "flatten_output" is - I thought for me it could be softmax_output as well, not sure. 

For mx.model.init.params: I get the error:  could not find function "mx.model.init.params"
There, I am also not sure what to put in "Input Shape". - the dimensions of the original data set? the dimensions of the neural net? I am lost...

Any help would be great!
Thanks
Laura

**Comment by thirdwing** [comment]
@train-test-laura If you are using the same model over different chunks of data, you can do something similar to below:

```r
data(BostonHousing, package = "mlbench")

train.ind <- seq(1, 506, 3)
train.x <- data.matrix(BostonHousing[train.ind,-14])
train.y <- BostonHousing[train.ind, 14]
test.x <- data.matrix(BostonHousing[-train.ind,-14])
test.y <- BostonHousing[-train.ind, 14]

train.x2 <- train.x
train.y2 <- train.y

library(mxnet)

data <- mx.symbol.Variable("data")
fc1 <- mx.symbol.FullyConnected(data, num_hidden = 1)
lro <- mx.symbol.LinearRegressionOutput(fc1)

mx.set.seed(0)
model <- mx.model.FeedForward.create(lro,
                                     X = train.x,
                                     y = train.y,
                                     ctx = mx.cpu(),
                                     num.round = 50,
                                     array.batch.size = 20,
                                     learning.rate = 2e-6,
                                     momentum = 0.9,
                                     eval.metric = mx.metric.rmse)

model2 <- mx.model.FeedForward.create(lro,
                                      X = train.x2,
                                      y = train.y2,
                                      ctx = mx.cpu(),
                                      num.round = 50,
                                      array.batch.size = 20,
                                      learning.rate = 2e-6,
                                      momentum = 0.9,
                                      eval.metric = mx.metric.rmse,
                                      arg.params = model$arg.params,
                                      aux.params = model$aux.params)
```

**Comment by train-test-laura** [comment]
Hi Thirdwind,
thank you very much - this seems to be exactly what I was looking for. 
That is easier than I expected it to be - just taking arg.params and aux.params from model 1 (chunk 1) and take it to model 2 (chunk 2) and so on - great!
