### ISSUE TITLE
Code freeze - halt code merges

### ISSUE THREAD

**Issue by lxn2** [apache/incubator-mxnet#7367]
A pending item for our release is adding license headers to all source files. We first need to stabilize the CI before we can merge the license headers since it is a very big change. To avoid introducing any breaking changes, **until the CI is stable please do not merge a PR unless it's a bug fix.**

@piiswrong @mli @javelinjs @thirdwing @nswamy @madjam

**Comment by mli** [comment]
#7379

**Comment by lxn2** [comment]
Unless it's a very small change or bug fix, please stop merging PRs today.
