### ISSUE TITLE
gluon.nn.Conv2D initialization int stride not handled correctly

### ISSUE THREAD

**Issue by zhanghang1989** [apache/incubator-mxnet#7377]
When creating 'gluon.nn.Conv2D', passing the stride with integer value, it does not automatically convert to tuple and cause 'Floating Point Exception'.

 for example 
```
nn.Conv2D(in_channels=inplanes, 
                   channels=planes * self.expansion,
                   kernel_size=1, stride=1)
```
will cause error when forwarding.

**Comment by szha** [comment]
@zhanghang1989 @Jerryzcn Could you send a minimum example?

**Comment by zhanghang1989** [comment]
```python
import mxnet as mx   
from mxnet import gluon
from mxnet.gluon import nn
layer=nn.Conv2D(in_channels=3,                               
                   channels=3,                      
                   kernel_size=1, stride=1)
layer.initialize() 
x=mx.nd.random_normal(loc=0, scale=1, shape=(2, 3, 224, 224))
layer(x) 
```
will produce the Error ``Floating point exception``

**Comment by zhanghang1989** [comment]
Never mind, it is a typo.  Should be ``strides=1`` instead of ``stride=1``

**Comment by Jerryzcn** [comment]
We should probably change it to either strides or stride, not both, or give some warning...
