### ISSUE TITLE
Parameter 'dtype' in the function 'ImageRecordIter' doesn't work

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#7384]
In mxnet-0.10 version, I add 'dtype = float16', 'dtype = float64', 'dtype = uint8' in the function 'ImageRecordIter' in example/image-classifacation/common/data.py.  But the data read from this function is always  'float32' .

I find this parameter only used in the 266 line of the file iter_image_recordio_2.cc. It pass a new type to a variable 'dtype'. But this variable was no longer be used.

Is it a bug? 
How can I read data in float16 format?

**Comment by ptrendx** [comment]
Did it work in the previous version of the ImageRecordIter (you can test that by changing ImageRecordIter to ImageRecordIter_v1)? Judging by the code it should not work (it should either give you an error or result in a silent corruption), so the dtype option is just wrong and should not be there. For example to get UInt8 data type you need to use ImageRecordUInt8Iter.
The best way of getting fp16 data is to cast it to fp16 after it is produced in fp32 (I assume you are using GPU - this gives additional bonus of double buffering of data copies to GPU, so should generally be faster than just using ImageRecordIter and outputting fp16 format). Example of doing that is in example/image-classification/symbols/alexnet.py (resnet, resnet-v1, inception-v3 and v4 also have that, but alexnet is the simplest).

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
