### ISSUE TITLE
OSError: /home_dir/mxnet/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: cblas_ddot

### ISSUE THREAD

**Issue by pras1406** [apache/incubator-mxnet#7397]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
RHEL 6.9 (2.6.32-696.el6.x86_64)
Compiler:
gcc (GCC) 5.3.0

Package used (Python/R/Scala/Julia):
Python

MXNet version:

Or if installed from source:
 git clone --recursive https://github.com/dmlc/mxnet (Installed from source)

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python 2.7.10

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
I have installed mxnet at this dir: ~/mxnet/mxnet
PYTHONPATH is set to ~/mxnet/mxnet/python

A. OpenBLAS used:
1. git clone "git://github.com/xianyi/OpenBLAS.git"
2. cd OpenBLAS
3. make TARGET=SANDYBRIDGE ( our processor is Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz which is haswell but it was giving this error with `make` command ./kernel/x86_64/dtrmm_kernel_4x8_haswell.c:77: Error: no such instruction: vpe rmpd $0x1b,%ymm3,%ymm3' ../kernel/x86_64/dtrmm_kernel_4x8_haswell.c:78: Error: no such instruction:vpe rmpd $0xb1,%ymm2,%ymm2') So I changed TARGET=SANDYBRIDE

4. Installed OpenBLAS with make PREFIX=dir install

B.
1.  Installed mxnet with USE_BLAS=openblas and USE_OPENCV=0 and specifying path of OpenBLAS in mxnet/make/config.mk file.
2. make -j4 (Successful as it generated lib/libmxnet.a and libmxnet.so)
3. export PYTHONPATH=~/mxnet/mxnet/python/
4.  Ran python in interactive mode as
[c244728_lx@host1]$ module load gcc/5.3.0
[c244728_lx@host1]$ python
Python 2.7.10 (default, Jun  6 2015, 14:08:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/base.py", line 69, in <module>
    _LIB = _load_lib()
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/base.py", line 61, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/lrlhps/apps/python/python-2.7.10/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/c244728_lx/mxnet/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: cblas_ddot
>>>

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
Also ran mxnet/example/ as
[c244728_lx@host1 mxnet]$ python example/image-classification/train_mnist.py
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 8, in <module>
    from common import find_mxnet, fit
  File "/home/c244728_lx/mxnet/mxnet/example/image-classification/common/find_mxnet.py", line 3, in <module>
    import mxnet as mx
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/base.py", line 69, in <module>
    _LIB = _load_lib()
  File "/home/c244728_lx/mxnet/mxnet/python/mxnet/base.py", line 61, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/lrlhps/apps/python/python-2.7.10/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/c244728_lx/mxnet/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: cblas_ddot

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by pras1406** [comment]
Tried to buld OpenBLAS with DYNAMIC_ARCH=1 NO_AVX2=1 and then again rebuilded mxnet still giving the same error.

**Comment by szha** [comment]
Since it complains about missing cblas symbols, consider adding openblas to linker flags.

**Comment by pras1406** [comment]
@szha yes specifying 
make -j8 ADD_CFLAGS="-I/home_dir/OpenBLAS_build/include" ADD_LDFLAGS="-L/home_dir/OpenBLAS_build/lib -lopenblas" and then exporting LD_LIBRARY_PATH=/OpenBLAS_build/lib:$LD_LIBRARY_PATH
solved the issue.

Thanks.
