### ISSUE TITLE
When does kWriteInplace happen?

### ISSUE THREAD

**Issue by kmichaelkills** [apache/incubator-mxnet#7400]
I am trying to make an OP that do inplace in imperative mode. 

For instance:

```python
a = mx.nd.zeros([1])
b = mx.nd.Add1(a)
assert a.asnumpy()[0] == 1
```
I've activated the ForwardInplace option in my operator, but the req type is still `kWrite`. When I do `mx.nd.Add1(a, out=a)`  it does inplace calculation, but the req type is still `kWrite` instead of `kWriteInplace`.
 
Checking out the documentation, the explanation is missing:

```cpp
// file /include/mxnet/op_attr_types.h
  /*!
   * \brief perform an inplace write,
   * Target shares memory with one of input arguments.
   * This option only happen when
   */
  kWriteInplace,
```

**Comment by eric-haibin-lin** [comment]
For imperative execution the (dense) operator always use `kWriteTo` for now. kWriteInplace is usually added for symbolic execution, where MXNet performs extensive memory planning. 

Also there's a good note regarding mem optimization in MXNet for background. https://mxnet.incubator.apache.org/architecture/note_memory.html

I'm closing this issue for now. For further questions/discussion, we're moving to discuss.mxnet.io
