### ISSUE TITLE
inconsistent accuracy: ImageRecordIter vs ImageIter

### ISSUE THREAD

**Issue by melody-rain** [apache/incubator-mxnet#7406]
ImageRecordIter gets much better accuracy. Any reasons for that?
```
data = mx.io.ImageRecordIter(
        data_name          = 'data',
        label_name         = 'softmax_label',
        path_imgrec        = data_val,
        label_width        = 1,
        data_shape         = data_shape,
        batch_size         = batch_size,
        mean_r             = rgb_mean[0],
        mean_g             = rgb_mean[1],
        mean_b             = rgb_mean[2],
        )

data = mx.image.ImageIter(
        data_name='data',
        label_name='softmax_label',
        path_imgrec=data_val,
        label_width=1,
        data_shape=data_shape,
        batch_size=batch_size,
        mean = np.ndarray(shape=(3, 1, 1), buffer=np.array(rgb_mean)),
    )
```

**Comment by ZhaoxiaZhang** [comment]
HI, I met something maybe similar with you. I trained  ImageRecordIter and get a very good accuracy. However when I tested with the same data, the accuracy is much lower. I don't kown why. 
BTW, how did you get the mean r, g b.?

**Comment by melody-rain** [comment]
@ZhaoxiaZhang  Hi, I suggest that you use ImageIter instead of ImageRecordIter all the time, such that you get good accuray when testing. 
As for mean_X, just use imagenet‘s mean, which is (123.68,116.779,103.939). You can also calculate the mean of all the training data by yourself.

**Comment by ZhaoxiaZhang** [comment]
@melody-rain Thanks for your comments. I will try the imageiter.
BTW, any insights why ImageRecordIter does,'t work? I'm reallly confused abot this.

**Comment by melody-rain** [comment]
@ZhaoxiaZhang  ImageRecordIter works for training and the test during training. But for production environment, we read an image with opencv or other libraries and resize the image, during which we cannot reproduce the accuracy from the trained model. 

According to the debug, I found the image from ImageRecordIter is a bit different from the one I got from cv2.imread()(plus cv2.imresize() if necessary), which I do not know why. But with ImageIter, I found there is almost no difference. 

BTW, check how im2rec.py converts JPEGs to .rec if you need resize the image. You'd better follow the same way to resize(maybe you also crop) the images in the production environment.

**Comment by ZhaoxiaZhang** [comment]
Thanks for that! let me try and will update the results later.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
