### ISSUE TITLE
concat operator optimization

### ISSUE THREAD

**Issue by pgplus1628** [apache/incubator-mxnet#7407]
It seems the current implementation of `concat` operator is based on mshadow. And if the input of concat has multiple NDArray, on gpu, it will launch kernel for many times. Tensorflow has customized kernel for concat operator, it will do kernel launch only once. 
Any plan to optimize this?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
