### ISSUE TITLE
How to do a sobel operation in symbol layer

### ISSUE THREAD

**Issue by pdmengmeng** [apache/incubator-mxnet#7408]
there is a symbol layer , its size is ( 1 ,1 ,300 ,300 ) .How to use it to do a sobel operation.
I kown that  we need to use symbol.broadcast_add/broadcast_sub......
But how to select the specif area, Symbol can be used as numpy ?  

Symbol[ : ,: , 1:W, 1: H] - Symbol [:,:,0:W-1,  0: H-1]  this is right?

**Comment by edmBernard** [comment]
Sobel filter is just a filter with a specific 3x3 kernel, so you can mimic it with a convolutionnal layer ?

**Comment by szha** [comment]
Something like this? The example is in ndarray but you can pass the kernel values in through `sym.var`.
```
from mxnet import ndarray as nd

data = nd.random_uniform(shape=(1, 1, 300, 300))

kx = nd.array([[1, 2, 1]]).T * nd.array([[1, 0, -1]])
ky = kx.T.reshape((1, 1, 3, 3))
kx = kx.reshape((1, 1, 3, 3))

gx = nd.Convolution(data, kx, kernel=(3, 3), num_filter=1, no_bias=True, layout='NCHW')
gy = nd.Convolution(data, ky, kernel=(3, 3), num_filter=1, no_bias=True, layout='NCHW')

out = nd.sqrt(gx*gx + gy*gy)
```
