### ISSUE TITLE
How to implement NG(nonlinearity generator) activate function in mxnet?

### ISSUE THREAD

**Issue by kobenaxie** [apache/incubator-mxnet#7409]
According to this paper: https://arxiv.org/ftp/arxiv/papers/1708/1708.01666.pdf

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
