### ISSUE TITLE
why rnn train speed is not stable,sometims very slow?

### ISSUE THREAD

**Issue by zhaoningning** [apache/incubator-mxnet#7414]
hi, everyone,
recently,  I train a  cnn+rnn  model for ocr,  but during the training process, i found that the training speed  is not stable, sometimes 30 samples/sec,after a while, it may become 1000 samples/sec...
so i wonder why this happen?  I have tried updating mxnet  from 0.9.5 to  0.10, not solved.

**Comment by eric-haibin-lin** [comment]
Is 30 samples/sec the speed for a batch? Do you have variable sequence length?

**Comment by zhaoningning** [comment]
I used mxnet.callback.Speedometer, so yes, I think 30 samples/sec is the mean speed  for a batch,and I fixed the input image size, so it's not variable sequence length;  

ps: I tried training two models at the same time(using the same cnn+rnn ) with different gpus on a server,the training  speeds of two process almost the same,and when one training speed become 600 samples/sec, the other training speed also grow to nearly 600 samples/sec, when one training speed slow down,the other training slow down  as well;  And  during the low training speed time, most of cpus is  free, and gpus are  almost free.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
