### ISSUE TITLE
Caffe-converter convert_model.py fail

### ISSUE THREAD

**Issue by yonadavs** [apache/incubator-mxnet#7415]
Hi, tried converting a caffe model.
The convert_symbol ran successfully, but the convert_model crashed.
I know the model works fine on caffe. I don't know any details about the model.

## Environment info
Operating System:
Ubuntu 16.04

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash (`git rev-parse HEAD`):
89e3ee3ea7c223db8c65ddd8c94c6e787d7c52df
If you are using python package, please provide

Python version and distribution:
python 2.7

## Error Message:
Please paste the full error message, including stack trace.

converting layer fc6, wmat shape = (22440, 512)fc6_bias not found in arg_shape_dic.
        skipping layer softmaxloss1 of type SoftmaxWithLoss
        skipping layer center_loss_1 of type CenterLoss
Traceback (most recent call last):
  File "convert_model.py", line 220, in <module>
    main()
  File "convert_model.py", line 216, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "convert_model.py", line 198, in convert_model
    assert len(layer_blobs) == 0
AssertionError

## Steps to reproduce

1. run tools/caffe_converter$ python convert_model.py proto caffemodel filename

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
