### ISSUE TITLE
Update mxnet in maven timely?

### ISSUE THREAD

**Issue by maxenceliu** [apache/incubator-mxnet#7417]
in the maven repository, the mxnet version is much delayed. Furmore, it depends on opencv, in which the case our server doesn't need opencv.

**Comment by piiswrong** [comment]
@javelinjs Let's release static build on maven?

**Comment by javelinjs** [comment]
Sure. I'll work on this.
BTW, are we going to change package name from `ml.dmlc` to `org.apache`? cc @mli

**Comment by szha** [comment]
@javelinjs let me know if need any help on this.

**Comment by javelinjs** [comment]
@szha Thanks for invitation to the deployment project.

**Comment by maxenceliu** [comment]
@javelinjs @szha @piiswrong Thanks for your paying attention to this issue. Another question about scala version is: NDarray.toArray method could be block on cpu version mxnet? 

This method will block me for about 10 seconds each time I run it on the Centos server, which could be neglected when I run it on my Mac cpu only.

**Comment by maxenceliu** [comment]
I Read the code
`if (this->ctx().dev_mask() == cpu::kDevMask) {
    **this->WaitToRead();**
    RunContext rctx{this->ctx(), nullptr};
    ndarray::Copy<cpu, cpu>(this->data(), &dst,
                            Context::CPU(), Context::CPU(), rctx);
  } `
I guess it is blocked here. I don't no why we have to wait to read, if there is something we don't have to wait to do this copy?

**Comment by javelinjs** [comment]
@maxenceliu the same problem as you mentioned in https://github.com/apache/incubator-mxnet/issues/3724 ?

**Comment by maxenceliu** [comment]
@javelinjs Yes. I haven't located the problem. Do you have some suggestions?

**Comment by maxenceliu** [comment]
@javelinjs @piiswrong @szha I think I have partly solved this problem. But I still don't know the reason.
After I replace FeedForward with Module, there is no halt anymore. Is there anything different between Module and FeedForward? Since predict methords are both implemented in these two class.

**Comment by zihaolucky** [comment]
@maxenceliu I also use FeedForward in v0.7 and failed to upgrade because of the same problem. I would try Module later.

**Comment by gautamkmr** [comment]
Given that this thread has digressed a little, 
@javelinjs  Do you need any help on the original issue ?  " Update mxnet in maven timely? #7417 "

**Comment by madjam** [comment]
@javelinjs what are the next steps here and do you need any help?

Now that mxnet is a apache incubator project I do think we need to change the package names prefix from ml.dmlc to org.apache.mxnet. That is what all other apache projects have done.
Also, going forward I think we should automate the "publish artifacts to maven central" step that executes whenever a new release is cut. Lets talk about how to get there.

**Comment by javelinjs** [comment]
I'm working on the deploy repo. Following the py package, I shall make it work this weekend. Once it is stable, we will go on to change the package name.

One thing I'd like to raise is the PGP key, now I'm using my private key for maven deploying. Do we have a key for `org.apache`?

**Comment by madjam** [comment]
@javelinjs Thanks.

This page has some info regarding releasing maven artifacts for a apache project: http://www.apache.org/dev/publishing-maven-artifacts.html

In particular, the project needs to be configured in Nexus. For this we need to open a JIRA: http://www.apache.org/dev/publishing-maven-artifacts.html#signing-up

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
@yzhliu Any update on this?

**Comment by nswamy** [comment]
Its in Maven now, we'll be releasing regularly with every release. https://mvnrepository.com/search?q=org.apache.mxnet
