### ISSUE TITLE
mx random seed doesn't work for random_uniform/random_normal on gpu

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#7426]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: DL AMI

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`): 251ae71a20d8318ab20f4c19520f74b881fdf3ff

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```
import mxnet as mx
import numpy as np
shape = (2, 2)
out1 = mx.nd.zeros(shape=shape, ctx=mx.gpu(0))
out2 = mx.nd.zeros(shape=shape, ctx=mx.gpu(0))
mx.random.seed(0)
np.random.seed(0)
mx.nd.random_uniform(out=out1)
print(out1.asnumpy())
mx.random.seed(0)
np.random.seed(0)
mx.nd.random_uniform(out=out2)
print(out2.asnumpy())
```

```
[[ 0.74021935  0.9209938 ]
 [ 0.03902049  0.96896291]]

[[ 0.92514056  0.4463501 ]
 [ 0.66731918  0.10993068]]
```

**Comment by xzqjack** [comment]
The same error happened in my service (ubuntu16.04, gpu, mxnet-version:0.10.1)

**Comment by eric-haibin-lin** [comment]
related issue: #6783

**Comment by haojin2** [comment]
Seems like this issue has already been solved, I cannot reproduce it on the latest master(b1b0521366344b516a618ce73f7bc9a1c0708092):
>>> import mxnet as mx
>>> import numpy as np
>>> shape = (2, 2)
>>> out1 = mx.nd.zeros(shape=shape, ctx=mx.gpu(0))
>>> out2 = mx.nd.zeros(shape=shape, ctx=mx.gpu(0))
>>> mx.random.seed(0)
>>> np.random.seed(0)
>>> mx.nd.random_uniform(out=out1)
[[ 0.66865093  0.17409194]
 [ 0.38500249  0.24678314]]
<NDArray 2x2 @gpu(0)>
>>> mx.random.seed(0)
>>> np.random.seed(0)
>>> mx.nd.random_uniform(out=out2)
[[ 0.66865093  0.17409194]
 [ 0.38500249  0.24678314]]
<NDArray 2x2 @gpu(0)>
