### ISSUE TITLE
how to set dataiter with multi data?

### ISSUE THREAD

**Issue by AihahaFox** [apache/incubator-mxnet#7427]
hey guys, I tried to rewrite Dataiter to provide multi data, for func provide_data(), I set it be [('data1', shape1), ('data2', shape2)]. and bind this iter with module. But there is problem in _parse_data_desc function. The data_name must be ['data'], cannot change to any other name. so how can I solve this problem

**Comment by xzqjack** [comment]
You can look up the definition of class module (python/mxnet/module/module.py), and init module by
`mod = mx.mod.Module(..., data_names=('data1', 'data2'), ...)`

**Comment by squidszyd** [comment]
Use collections.namedtuple:
Batch = namedtuple('Batch',['data', 'label'])
def __iter__(self):
    ...
    yield Batch(data=[data1, data2, data3,...], label=[...])
@property
def provide_data(self):
     return [('data1', shape1), ('data2', shape2), ('data3', shape3), ...]

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
