### ISSUE TITLE
AttributeError: 'module' object has no attribute 'stack'

### ISSUE THREAD

**Issue by Tao-Sun** [apache/incubator-mxnet#7431]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: OSX and Ubuntu

Compiler: Not sure. Installed according to http://mxnet.io/get_started/install.html.

Package used (Python/R/Scala/Julia): Python

MXNet version: Not sure. Installed according to http://mxnet.io/get_started/install.html.

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. import mxnet as mx
2.mx.nd.stack

Comment:
I installed both on my Apple Mbp (pip) and Ubuntu (14.04, docker) following the steps in Not sure http://mxnet.io/get_started/install.html.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
