### ISSUE TITLE
Not appending to end of linked list correctly?

### ISSUE THREAD

**Issue by chenzhuo8804** [apache/incubator-mxnet#7451]
Hi I am reading money's source code and am confused in following block
line 64 - 67 in threaded_engine.cc
head_->next = new_var_block;
head_->trigger = opr_block;
head_ = new_var_block;

Is this trying to append a new_var_block to head? why the last line is not head_ = head_ -> next?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
