### ISSUE TITLE
Pb in import of mxnet

### ISSUE THREAD

**Issue by BenLag2906** [apache/incubator-mxnet#7453]
I have a Pb in import of mxnet in python

## Environment info
Operating System: windows 10

Compiler:
visual 2015 64

Package used (Python/R/Scala/Julia): Python

MXNet version:
0.10 or 0.11
installed from source:

If you are using python package, please provide

Python version and distribution:
2.7.13

## Error Message:
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import mxnet
Traceback (most recent call last):
File "", line 1, in 
File "mxnet_init_.py", line 25, in 
from .base import MXNetError
File "mxnet\base.py", line 86, in 
_LIB = _load_lib()
File "mxnet\base.py", line 78, in load_lib
lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
File "C:\Python27\lib\ctypes_init.py", line 362, in init
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Le module spÚcifiÚ est introuvable

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. AFTER COMPILATION : Import mxnet
2.
3.

## What have you tried to solve it?

1. different version
2.
3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
