### ISSUE TITLE
Question about networks for cifar100.

### ISSUE THREAD

**Issue by wanderingpj** [apache/incubator-mxnet#7454]
What networks are suitable for cifar100 with relatively high testing accuracy?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
