### ISSUE TITLE
[gluon] nomenclature for hybrid computation

### ISSUE THREAD

**Issue by bikestra** [apache/incubator-mxnet#7462]
I find that names like HybridBlock, HybridSequential, and hybridize() in gluon are not effectively conveying what their utilities and usages are. To me, 'HybridBlock' sounds like a mixture of 'Block' and something else, although it is actually an extension of a Block. Also, calling hybridize() sounds like imperative and symbolic program will be mixed in executions, although in reality, calling it makes an one-way transition of the block from an imperative program to a symbolic program. Lastly, 'hybrid' is an ambiguous word which meaning is unclear until a user takes a careful look at the hybrid computation tutorial.

Proposal: Why don't we call these CompilableBlock, CompilableSequential, and compile()? Then, it should be clear CompilableBlocks are extensions of Blocks, and executions of CompilableBlocks will be faster after calling compile() than they were before, because 'compile' is a concept most programmers are familiar with.

Furthermore, from the API design point of view, it might be clearer if compile() creates a new Block rather than changing the state of an exiting HybridBlock. Then it should be clear that CompilableBlock is still an imperative program, whereas CompilableBlock.compile() is a declarative program.

I am curious what others' thoughts on this are. Tagging @szha since I talked with him on this separately.

**Comment by szha** [comment]
@piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
