### ISSUE TITLE
[Gluon] Resnet152_v1 batch_size 32 doesn't work quite well 

### ISSUE THREAD

**Issue by Roshrini** [apache/incubator-mxnet#7463]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Amazon Linux

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version: Master

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 1a617fadc3cf612f964722e09571e1b80ad16f68

If you are using python package, please provide

Python version and distribution: Python 2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Using resnet152_v1 model  https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/resnet.py
2. python image_classification.py --dataset dummy --gpus 8—epochs 10 --benchmark --mode imperative --model resnet152_v1 --log-interval 1

This command uses default batch_size of 32 and the results are not comparable as compared to symbolic approach. 

Here are the results with symbolic, imperative and hybrid approach after running for 10 epochs:

<img width="981" alt="screen shot 2017-08-14 at 2 32 53 pm" src="https://user-images.githubusercontent.com/8004078/29292823-83010172-80fd-11e7-965a-a3834c27257b.png">

**Comment by szha** [comment]
My understanding is that this is due to memory consumption being too large. #7433 may help with the memory consumption. Please give a it a try once that's merged, and send a patch if this isn't fixed by then.

**Comment by Roshrini** [comment]
Thanks! Much better than before after the C++ optimizations done.

![screen shot 2017-08-16 at 12 30 32 pm](https://user-images.githubusercontent.com/8004078/29381641-cdc81718-827e-11e7-8ed2-22b58a204095.png)

**Comment by szha** [comment]
Nice. @piiswrong
