### ISSUE TITLE
Why are resnet's RELU and BN set before CONV?

### ISSUE THREAD

**Issue by cuteding** [apache/incubator-mxnet#7471]
Why are resnet's RELU and BN set before CONV?
In https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/symbols/resnet.py

        bn1 = mx.sym.BatchNorm(data=data, fix_gamma=False, eps=2e-5, momentum=bn_mom, name=name + '_bn1')
        act1 = mx.sym.Activation(data=bn1, act_type='relu', name=name + '_relu1')
        conv1 = mx.sym.Convolution(data=act1, num_filter=int(num_filter*0.25), kernel=(1,1), stride=(1,1), pad=(0,0),
                                   no_bias=True, workspace=workspace, name=name + '_conv1')

bn1 and act1 are set before conv1

But resnext and resnet-v1 are normal()        
In https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/symbols/resnext.py
       
        conv1 = mx.sym.Convolution(data=data, num_filter=int(num_filter*0.5), kernel=(1,1), stride=(1,1), pad=(0,0),
                                      no_bias=True, workspace=workspace, name=name + '_conv1')
        bn1 = mx.sym.BatchNorm(data=conv1, fix_gamma=False, eps=2e-5, momentum=bn_mom, name=name + '_bn1')
        act1 = mx.sym.Activation(data=bn1, act_type='relu', name=name + '_relu1')

https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/symbols/resnet-v1.py
        
        conv1 = mx.sym.Convolution(data=data, num_filter=int(num_filter*0.25), kernel=(1,1), stride=stride, pad=(0,0),
                                   no_bias=True, workspace=workspace, name=name + '_conv1')
        bn1 = mx.sym.BatchNorm(data=conv1, fix_gamma=False, eps=2e-5, momentum=bn_mom, name=name + '_bn1')
        act1 = mx.sym.Activation(data=bn1, act_type='relu', name=name + '_relu1')

**Comment by cuteding** [comment]
Identity Mappings in Deep Residual Networks explains why.

**Comment by edmBernard** [comment]
https://arxiv.org/abs/1603.05027
