### ISSUE TITLE
Training error when using cifar100.

### ISSUE THREAD

**Issue by wanderingpj** [apache/incubator-mxnet#7474]
I train the network given in
https://github.com/dmlc/mxnet-notebooks/blob/master/python/moved-from-mxnet/cifar-100.ipynb
with cifar100. But here comes a training error like this.
![qq 20170815175608](https://user-images.githubusercontent.com/24189081/29311528-df0311c6-81e4-11e7-9613-ff7c055b7a12.png)
What's the problem?@aileli

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
