### ISSUE TITLE
[v0.11.0] Amalgamation for Javascript JS has unresolved symbol: __cxa_thread_atexit

### ISSUE THREAD

**Issue by cheshirecats** [apache/incubator-mxnet#7481]
The amalgamation for Javascript in mxnet v0.9.2 worked fine, however for the latest 0.11.0 version, 
I got this error while running "make clean libmxnet_predict.js MIN=1":
`warning: unresolved symbol: __cxa_thread_atexit`
and the compiled js code crashed upon loading (with the same unresolved symbol error).

It seems this may have something to do with C++11 features support in emcc.

**Comment by cheshirecats** [comment]
For now I am using #define DMLC_CXX11_THREAD_LOCAL 0 in amalgamation.py to solve it.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
