### ISSUE TITLE
Quick question about LSTM parameters

### ISSUE THREAD

**Issue by aspzest** [apache/incubator-mxnet#7486]
I am using LSTM from mxnet and was able to get the parameters of the LSTM block. I have a question about the biases. According to the equation below taken from [here](http://colah.github.io/posts/2015-08-Understanding-LSTMs/), there is a single bias_f defined to get f_t. But, mxnet's LSTM parameters contain two biases for this equation: 1. i2h_f_bias and 2. h2h_f_bias. Is b_f here simply i2h_f_bias + h2h_f_bias? Or there is some other relation?

![screen shot 2017-08-15 at 3 13 07 pm](https://user-images.githubusercontent.com/29802784/29338879-4f8cadbc-81cc-11e7-992c-8dd4ce63896d.png)

I am also seeing that i2h_f_bias and h2h_f_bias are same sometimes.

Thank You

**Comment by szha** [comment]
This is to keep consistent with cudnn RNN implementation

**Comment by aspzest** [comment]
@szha So, b_f = i2h_f_bias + h2h_f_bias?

**Comment by szha** [comment]
yes

**Comment by aspzest** [comment]
Okay. Thanks a lot!

**Comment by szha** [comment]
No problem. And the reason that you see i2h_f_bias and h2h_f_bias being the same could be that they were initialized the same way. Since they are added together with the same weight 1, what ends up happening is that the gradients they received will always be the same.

**Comment by aspzest** [comment]
Yes, that's correct. Same initialization should lead to same values because gradients will always be same. Thank you!
