### ISSUE TITLE
cpp-package does not build with makefile build.

### ISSUE THREAD

**Issue by dtmoodie** [apache/incubator-mxnet#7493]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04

Compiler:
GCC 5.4

MXNet commit hash (`git rev-parse HEAD`):
75ee5976bc1a7ec24746d764b529d0ae8e6e9583

## Error Message:
Please paste the full error message, including stack trace.

cpp-package/example/mlp_cpu.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/mlp_cpu.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/mlp_cpu.cpp:45:61: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1 ? fc : Activation(fc, ActivationActType::kRelu);
                                                             ^
cpp-package/example/mlp_cpu.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);
                                             ^
cpp-package/example/test_score.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/test_score.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/test_score.cpp:45:60: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1? fc : Activation(fc, ActivationActType::kRelu);
                                                            ^
cpp-package/example/test_score.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);
                                             ^
cpp-package/example/mlp_gpu.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/mlp_gpu.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/mlp_gpu.cpp:45:61: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1 ? fc : Activation(fc, ActivationActType::kRelu);
                                                             ^
cpp-package/example/mlp_gpu.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);

What I've tried:
Have not been building the cpp-package.

**Comment by lx75249** [comment]
Do you have python installed? Can you build mxnet without USE_CPP_PACKAGE?

**Comment by dtmoodie** [comment]
I have python installed but I am not using it on this computer with mxnet.
The build works correctly with USE_CPP_PACKAGE=0.

**Comment by dtmoodie** [comment]
Nevermind, I found the source of the problem.

**Comment by schliffen** [comment]
Dear @dtmoodie Im facing with the same problem, can you share your solution? thank you.

**Comment by leezu** [comment]
We will remove the Makefile build. Please use cmake instead.
