### ISSUE TITLE
Why the data size can not be bigger than batch size?

### ISSUE THREAD

**Issue by FreeAlex** [apache/incubator-mxnet#7497]
https://github.com/apache/incubator-mxnet/blob/c79d4e50cb9561bcfd69dd866b8ededa47c64d76/python/mxnet/io.py#L626

Why can't it have consistent behavior as treating the whole data as the last batch and padding zeros?
This can reduce the work to pad zeros to the data when it's smaller than batch size.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
