### ISSUE TITLE
how to correctly have multiple inputs with Perl API?

### ISSUE THREAD

**Issue by adamcrussell** [apache/incubator-mxnet#7499]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: OS X 10.11.6

Compiler: gcc

Package used (Python/R/Scala/Julia): Perl

MXNet version: 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 897cc55a0ffd53317628bbccadea34b072228937

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

this code:

my $data_age = mx->symbol->Variable("data_age");
my $fc0 = mx->symbol->FullyConnected({data => $data_age, name=> "fc0", num_hidden => 1});
my $data_hours = mx->symbol->Variable("data_hours");
my $fc1 = mx->symbol->FullyConnected({data => $data_hours, name=> "fc1", num_hidden => 1});
my $data_years = mx->symbol->Variable("data_years");
my $fc2 = mx->symbol->FullyConnected({data => $data_years, name=> "fc2", num_hidden => 1});
my $composed_input=mx->symbol->Concat($data_age, $data_hours, $data_years);
my $fc3 = mx->symbol->FullyConnected(data => $composed_input, name=> "fc3", num_hidden => 1);
my $softmax=mx->symbol->MAERegressionOutput(data => $fc3, name => "softmax");
my $module = mx->mod->Module(symbol => $softmax);

gives the following error:
You created Module with Module(..., data_names=data) but input with name 'data' is not found in symbol.list_arguments(). Did you mean one of:
	data_age
	data_hours
        data_years
	softmax_label at /Users/arussell/perl5/lib/perl5/AI/MXNet/Module/Base.pm line 46.
	AI::MXNet::Module::Base::_check_input_names(AI::MXNet::Module=HASH(0x7fec8583efd8), AI::MXNet::Symbol=HASH(0x7fec83a943d8), ARRAY(0x7fec842f7458), "data", 1) called at /Users/arussell/perl5/lib/perl5/AI/MXNet/Module.pm line 223
	AI::MXNet::Module::BUILD(AI::MXNet::Module=HASH(0x7fec8583efd8), HASH(0x7fec85812830)) called at /Users/arussell/perl5/lib/perl5/AI/MXNet/Module.pm line 229
	AI::MXNet::Module::Module("AI::MXNet::Module", "symbol", AI::MXNet::Symbol=HASH(0x7fec83a943d8)) called at

I have multiple data inputs, each with their own iterator and I assumed, based on the documentation, that something along these lines was the way in which to handle this situation but this does no seem to work. How does one combine multiple inputs with the Perl API? Did I have the right idea and just get the API calls wrong?

**Comment by sergeykolychev** [comment]
@adamcrussell the 'data' is a default name for the variable where we expect the data to come from into the net.
If you use different name then you should create a module with additional parameters.
In this case use:
```
my $module = mx->mod->Module(symbol => $softmax, data_names => ['data_age']);
```
If you have more than one input variable then specify them all in the data_names array.
Also do not forget to have your iterator also return AI::MXNet::DataDesc with the correct names and shapes (the 'provide_data') call.

**Comment by adamcrussell** [comment]
@sergeykolychev great, that works as far as getting the module to accept the inputs. I'll hadn't written my own iterator. I had thought that model->fit() would somehow be ale to take multiple iterators, say, one for each corresponding input. I guess that is not the case...model->fit() expect a single iterator for all inputs, correct?

**Comment by sergeykolychev** [comment]
yes

**Comment by sergeykolychev** [comment]
you can create one hot encoding in multiple ways.
easiest one to have your iterator return an ndarray for that variable with that many rows as batch size and columns being your one hot encoding. for 9 cities you need a row with 9 columns with one of these set to 1 and others as 0.
default type is float32 so it should suffice for all your vars.
If you need something custom , have your iterator return ndarray of a particular dtype and make sure that iterator provide_data call also has a correct dtype for corresponding datadesc.

**Comment by adamcrussell** [comment]
@sergeykolychev ok, sounds good. I'll give it a shot. thanks for your help!

**Comment by adamcrussell** [comment]
@sergeykolychev a very minor thing I noted was that on line 136 of https://github.com/apache/incubator-mxnet/blob/master/perl-package/AI-MXNet/examples/char_lstm.pl should have $self->seq_size and not $seq_size. It is pretty irrelevant and works presently because $seq_size is global. anyone else borrowing the code might get the same error as I did once they separate out the package ASCIIIterator code though.

**Comment by sergeykolychev** [comment]
@adamcrussell Thank you! Feel free to create a pull :-) We need more perl devs for mxnet!

**Comment by adamcrussell** [comment]
@sergeykolychev ok, one earth shattering pull request sent! I'm more than happy to contribute a bit more significant code in the future.
