### ISSUE TITLE
[Feature Request] save symbol as well in gluon

### ISSUE THREAD

**Issue by ShownX** [apache/incubator-mxnet#7501]
I start to use gluon but I found it cannot save the model into the symbol file. Is it possible to implement this function?

**Comment by piiswrong** [comment]
Only hybridblock can be serialized to symbol. Normal blocks can only be pickled

**Comment by ShownX** [comment]
how to serialize hybridblock?

**Comment by szha** [comment]
you can call the `.save_params()` function on it.

**Comment by ShownX** [comment]
Yes. I tried ```.save_params()``` function, it only saves the params. I cannot find the symbol file :(.

**Comment by szha** [comment]
@ShownX ah sorry for missing that. To get the symbol out of a block, just feed the block with a symbol of the intended put variable. Something like `block(sym.Variable('data'))` and then you can use symbol.save.

**Comment by ShownX** [comment]
Suppose I wrote the following code:
```
net = gluon.nn.HybridSwquential()
net.add(gluon.nn.Dense(512))
```
Is it possible to save ```net``` definition to a symbol file? I cannot find the API like you said above. What I only find is ```net.save_params()``` to save weights.

**Comment by szha** [comment]
You can call `net(mx.sym.Variable('data'))` and the returned value is a symbol, with which you can save with the symbol API.

**Comment by ShownX** [comment]
I see. Thanks.
