### ISSUE TITLE
can't find sf1_train.lst for the cpp example

### ISSUE THREAD

**Issue by hpsoar** [apache/incubator-mxnet#7504]
I'm trying to run resnet.cpp example, can't find sf1_train.lst/sf1_train.rec data from `http://data.dmlc.ml/mxnet/data/`

I'm new to machine learning, I want to know is sf1_train a standard data set, or any data processed by im2rec.py is fine for the example.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
