### ISSUE TITLE
SSD example error

### ISSUE THREAD

**Issue by jinfagang** [apache/incubator-mxnet#7509]
Simply run SSD example got this error:

```
[01:09:24] src/nnvm/legacy_json_util.cc:185: Warning: loading symbol saved by MXNet version 1001 with lower version of MXNet v1000. May cause undefined behavior. Please update MXNet if you encounter any issue
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

**Comment by edmBernard** [comment]
MXNet can upgrade old network on newer version but not in the other way. 
Can you try with a newer MXNet version or download an older pretrained model.

**Comment by jinfagang** [comment]
Well, I know it's version issue, but I just installed from pip which gives me 0.10.0, the newest version is 0.11, but why not update pip? I really cannot build from source, the official doc is so out-of-date and messy.

**Comment by edmBernard** [comment]
MXNet 0.11 is not release yet. It's in rc2.
The official doc seem up to date for installation from source : http://mxnet.io/get_started/install.html
if you know how docker work you can see that : [docker mxnet gpu](https://github.com/edmBernard/DockerFiles/blob/master/mxnet/Dockerfile.gpu)

**Comment by edmBernard** [comment]
Where did your model come from ?

**Comment by jinfagang** [comment]
Just follow the SSD example, download right from link given by that example, exception for some path issue, this model seems not compatiable with mxnet 0.10.0. But strongly recommended update pip source version.

**Comment by sandeep-krishnamurthy** [comment]
You can install 0.11-rc1 with below pip command:
# for cpu
pip install mxnet==0.11.0.rc1

#for gpu with cuda8
pip install mxnet-cu80==0.11.0.rc1

As mentioned by @edmBernard MXNet 0.11 is not yet released. Pip package will be updated post release.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
