### ISSUE TITLE
How to view results from recommender examples?

### ISSUE THREAD

**Issue by dhaners** [apache/incubator-mxnet#7513]
I am new to MXNet and recommender engines and wanted to test out the matrix factorization demos provided with MXNet. I can run the python notebooks such as demo1-MF.ipynb just fine, but I am confused as to how to view the final output of recommendations. After training the model it plots a graph of RMSE over time, but how do I view the actual recommendations that the model should predict?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
