### ISSUE TITLE
cmake -DUSE_DIST_KVSTORE=1 . ERROR

### ISSUE THREAD

**Issue by buryang** [apache/incubator-mxnet#7519]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 14.04lts

Compiler:
gcc 4.8.4
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.11
Or if installed from source:
yes
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python 2.7.6
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

mxnet$ cmake . -DUSE_DIST_KVSTORE=1
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Could NOT find MKL (missing:  MKL_INCLUDE_DIR MKLML_GNU_LIBRARY)
--  MKL not found
-- Could NOT find MKL (missing:  MKL_INCLUDE_DIR MKLML_GNU_LIBRARY)
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- CUDA detected: 8.0
-- Found cuDNN (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
--  OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc
-- OpenCV found (/usr/share/OpenCV)
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Found cuDNN (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
You have called ADD_LIBRARY for library mxnet without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Found ZMQ: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found PROTOBUF Compiler: /usr/bin/protoc
CMake Error at CMakeLists.txt:438 (target_link_libraries):
  The "debug" argument must be followed by a library.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. cmake . -DUSE_DIST_KVSTORE=1
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by zhangxiao-ustc** [comment]
Has this problem been solved? I got the same error log. 
with standard v0.11.0 branch

**Comment by ehsanmok** [comment]
@buryang I have the same issue. Dow did you resolve it? it'd be great to write it down so that others can benefit from it.

**Comment by rahul003** [comment]
Upgrading CMake solved the issue for me.
