### ISSUE TITLE
how to calculate an evaluation metric using intermediate layer output?

### ISSUE THREAD

**Issue by yuconglin** [apache/incubator-mxnet#7522]
Hi Dear mxnet users and developers:
    I understand that there is example of how to use intermediate layer output in prediction.
   However, in training and validation, is it possible to use intermediate layer output to calculate an evaluation metric?
   Thanks a lot

**Comment by edmBernard** [comment]
you can define this layer in output : 
```python
def get_symbol():
    data = mx.symbol.Variable(name="data")
    inter = mx.symbol.FullyConnected(data=data, num_hidden=4096, name="inter")
    fc1 = mx.symbol.FullyConnected(data=inter, num_hidden=4096, name="fc1")
    softmax = mx.symbol.SoftmaxOutput(data=fc1, name='softmax')
return mx.symbol.Group([softmax, inter])
```
look at [this](https://github.com/apache/incubator-mxnet/blob/master/example/python-howto/multiple_outputs.py)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
