### ISSUE TITLE
using python interface,some doubts for c++ api

### ISSUE THREAD

**Issue by Tveek** [apache/incubator-mxnet#7532]
like following python api
`mxnet.symbol.Activation(data=None, act_type=_Null, name=None, attr=None, out=None, **kwargs)`
in activation.cc file ,i can only find those two parameters(data,act_type) by following code
`.add_argument("data", "NDArray-or-Symbol", "Input array to activation function.")
.add_arguments(ActivationParam::__FIELDS__());`
but other parameters can not be found ,how python knows those parameters? where those parameter are defined?

**Comment by szha** [comment]
Are you looking for this? https://github.com/apache/incubator-mxnet/blob/master/src/operator/activation-inl.h#L51-L58

**Comment by Tveek** [comment]
No,i am looking for the defination of parameters(name,attr,out) in `mxnet.symbol.Activation(......)` api .

**Comment by KeyKy** [comment]
Are you looking for this? https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol.py#L2257

**Comment by ZiyueHuang** [comment]
Other parameters are related to symbol. You can refer to `MXSymbolCompose` and  https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/symbol.py#L434.`data` and `act_type` are in the activation-inl.h as @szha stated. And they are initialized by `param_.Init(kwargs)`

**Comment by szha** [comment]
Feel free to reopen if this is still an issue.
