### ISSUE TITLE
Call symbol/nd.smooth_l1 without scalar causing uncaught exception

### ISSUE THREAD

**Issue by zhreshold** [apache/incubator-mxnet#7533]
Call mx.nd.smooth_l1 without scalar parameter will cause mxnet to crash
```
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: stod: no conversion
```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

```
import mxnet.ndarray as nd
nd.smooth_l1(nd.array([1, 2]))
```

## What have you tried to solve it?

Specify scalar will solve it
```
nd.smooth_l1(nd.array([1, 2]), scalar=1.0)
```
However, in the example, the argument is specified as `sigma`, which is very confusing.
http://mxnet.io/api/python/symbol.html#mxnet.symbol.smooth_l1

We should add a default value for scalar (1.0), fix the document, and fix the uncaught exception anyway

**Comment by zhreshold** [comment]
Mark and will fix later.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by zhreshold** [comment]
I though it was resolved, but apprarently not, it exception is still uncaugh in python.

**Comment by anirudh2290** [comment]
@sxjscience Please also tag as "Bug" because of the crash.

**Comment by samskalicky** [comment]
@sandeep-krishnamurthy please close this issue as the fix PR is now merged. Thanks!
