### ISSUE TITLE
conflict mxnet version hint

### ISSUE THREAD

**Issue by Amocy-Wang** [apache/incubator-mxnet#7537]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu-16.04

Package used (Python/R/Scala/Julia): Python

MXNet version:0.11.0

Or if installed from source: yep

If you are using python package, please provide

Python version and distribution: anaconda2-4.4.0

## Error Message:
Please paste the full error message, including stack trace.
After finishing compiling mxnet-0.11.0 from source, I use the command "cd python; pip install -e ." to install mxnet egg for python. The output is "Installing collected packages: mxnet
  Running setup.py develop for mxnet
Successfully installed mxnet-0.10.1", while the return sting of the command "mxnet.__version__" is '0.11.0'

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. git clone --recursive https://github.com/apache/incubator-mxnet.git
2. make
3. cd python; pip install -e .

**Comment by szha** [comment]
Is it possible that a stale egg folder happens to be in the current working directory?

**Comment by Amocy-Wang** [comment]
@szha Thank you. I have created a pure docker environment and repeat operations above. I was wrong. Everything is ok now.
