### ISSUE TITLE
Change font from comic sans in diagrams

### ISSUE THREAD

**Issue by altosaar** [apache/incubator-mxnet#7539]
Would it be possible to change the font away from comic sans in the architecture diagrams?

e.g. https://github.com/apache/incubator-mxnet/blob/master/docs/architecture/note_engine.md

The docs are otherwise excellent and very helpful.

Thank you!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by altosaar** [comment]
Reopening - this is still an issue:

https://mxnet.incubator.apache.org/api/python/symbol_in_pictures.html

**Comment by thomelane** [comment]
@altosaar this was most likely a design choice to avoid discrimination against dyslexics.
As a British Dyslexic myself I fully support the recommendation from the The British Dyslexia Association to use this typeface for ease of reading: see https://bdatech.org/what-technology/typefaces-for-dyslexia.

As a matter of fact, my code editor's font is set to comic sans. :)

**Comment by altosaar** [comment]
Wow, I had no idea about that - fascinating. Thanks for sharing @thomelane :) I'll keep that in mind for inclusive design moving forward.
