### ISSUE TITLE
images2neibs

### ISSUE THREAD

**Issue by zhang-jian** [apache/incubator-mxnet#7540]
is there a function like theano.tensor.nnet.neighbours.images2neibs in mxnet? 

Thanks,

J

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
