### ISSUE TITLE
How to build custom operators into separate library/package with C++?

### ISSUE THREAD

**Issue by chihkao-cognitiv** [apache/incubator-mxnet#7544]
I want to try out some new activation functions and I have successfully created custom operators in C++ on top of the latest mxnet source code. But what I really like to have is to build a separate library (.so file in ubuntu) just for my custom operators so I can leave mxnet source code and its library as it is and I do not have to worry about merging my code to mxnet source code every time I need to use newer mxnet releases. I understand that if this is working, I need both libmxnet.so and mycustom.so in order to use my new activation functions. Any help is appreciated.
Thanks in advance.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
