### ISSUE TITLE
 Check failed: infer_complete The shape information of is not enough to get the shapes

### ISSUE THREAD

**Issue by wuchuanying** [apache/incubator-mxnet#7550]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:win10

Compiler:vs2013
Package used (Python/R/Scala/Julia):C++

MXNet version:apache-mxnet-src-0.11.rc1-incubating

Or if installed from source:yes

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
[09:28:50] D:\YISA\PR\mxnet_cpu\apache-mxnet-src-0.11.rc1-incubating\dmlc-core\include\dmlc/logging.h:308: [09:28:50] D:\YISA\PR\mxnet_cpu\apache-mxnet-src-0.11.rc1-incubating\src\c_api\c_predict_api.cc:199: Check failed: infer_complete The shape information of is not enough to get the shapes

## Minimum reproducible example

	string prefix = "Inception1/cnn-ocr";
	string symbol_file = prefix + "-symbol.json";
	string params_file = prefix + "-0001.params";
	int dev_type = 1; // 1:CPU, 2:GPU
	int dev_id = 0;
	mx_uint num_input = 1;
	const char* input_keys[] = { "data" };
	const mx_uint input_shape_indptr[] = { 0, 4 };
	//const mx_uint input_shape_data[] = { 1, 3, kIMSIZE, kIMSIZE };
	const mx_uint input_shape_data[] = { 1, 3, static_cast<mx_uint>(30), static_cast<mx_uint>(120) };//ocr
	//const mx_uint input_shape_data[2] = { 1, static_cast<mx_uint>(30*120) };//ocr

	// Read symbols file
	string symbols = readAllBytes(symbol_file.c_str());

	// Read params file
	string strparams = readAllBytes(params_file.c_str());

	// Create predictor
	int status = MXPredCreate(symbols.c_str(),
		strparams.c_str(),
		strparams.size(),
		dev_type,
		dev_id,
		num_input,
		input_keys,
		input_shape_indptr,
		input_shape_data,
		&predictor);
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
