### ISSUE TITLE
How to get the symbol of gluon's RNN model by hybridizing

### ISSUE THREAD

**Issue by everwind** [apache/incubator-mxnet#7551]
I follow the instruction of http://gluon.mxnet.io/P14-C05-hybridize.html#, but fail.  the error message is:
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.0-py2.7.egg/mxnet/gluon/block.py", line 312, in __setattr__
    super(HybridBlock, self).__setattr__(name, value)
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.0-py2.7.egg/mxnet/gluon/block.py", line 177, in __setattr__
    self.register_child(value)
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.0-py2.7.egg/mxnet/gluon/block.py", line 327, in register_child
    str(block), str(type(block))))
ValueError: Children of HybridBlock must also be HybridBlock, but RNN(100 -> 100, TNC, num_layers=2, dropout=0.2) has type <class 'mxnet.gluon.rnn.rnn_layer.RNN'>. If you are using Sequential, please try HybridSequential instead.
I can not find the HybridSequential  RNN  in source code of gluon

**Comment by piiswrong** [comment]
RNN is not a HybridBlock so you cannot use it as a children of a HybridBlock.

RNN will be changed to a hybridblock in the future.

**Comment by dmas-at-wiris** [comment]
@piiswrong Any ETA for this feature?

**Comment by aidan-plenert-macdonald** [comment]
@piiswrong Is this feature available now?

**Comment by Matafight** [comment]
looking forward to this new feature

**Comment by sontran** [comment]
same here. thanks!

**Comment by xylcbd** [comment]
same here.

**Comment by QiXuanWang** [comment]
is it still a limitation yet? Can someone post a workaround?

**Comment by Aashit-Sharma** [comment]
@piiswrong How to use the HybridRecurrentCell , as it seems has to have no documentation and do you have an intention of making an Hybrid recurrent layer ? 
Thanks.

**Comment by szha** [comment]
This request is tracked in #10873. The overall project is tracked in https://github.com/apache/incubator-mxnet/projects/11

**Comment by sandeep-krishnamurthy** [comment]
Resolving it since it is now supported - https://github.com/apache/incubator-mxnet/pull/11482
