### ISSUE TITLE
Networks for CIFAR-10.

### ISSUE THREAD

**Issue by wanderingpj** [apache/incubator-mxnet#7552]
What networks are suitable for CIFAR-10 besides inception and resnet?

**Comment by ShownX** [comment]
I think it is CV problem. Maybe you can check here: https://github.com/apache/incubator-mxnet/tree/master/example/image-classification

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
