### ISSUE TITLE
There is a problem in distribute training with dtype=fp16

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#7554]
1. There is a problem in distribute training with dtype=fp16. The command is as below.

python ../../tools/launch.py -n 2 --launcher ssh -H hosts `which python` train_imagenet.py \
--data-train=/data/ILSVRC2012_img_train.rec \
--data-val=/data/ILSVRC2012_img_val.rec \
--network=resnet \
--num-layers=50 \
--kv-store=dist_sync \
--gpus=0,1,2,3 \
--disp-batch=10 \
--top-k=5 \
--batch-size=128 \
--dtype='float16'

Then the program break, and "Bad address (src/tcp.cpp:199)" was printed on the screen.

2. I think the 'kvstore_dist.h' doesn't support fp16 yet. In the function 'Push_', the type of 'send_buf' is fp16. But the type of the data pointer passed to ps-lite is real_t(fp32).  There is the same problem was also in the function 'Pull'.
Does these problem cause the break in distribute training with fp16?

**Comment by Godricly** [comment]
Try bypassing it with float32. I'm not sure if there any update since #5818.

**Comment by solin319** [comment]
The dtype problem in local training on single machine was solved in  #5818.
But there is still a problem in distribute training when using 'ps-lite'.

**Comment by ZiyueHuang** [comment]
https://github.com/apache/incubator-mxnet/blob/master/src/kvstore/kvstore_dist.h#L243. `real_t* data = static_cast<real_t*>(send_buf.data().dptr_)` is an invalid cast if the underlying datatype is fp16. Although this line could compile because `dptr_` is `void*` = =

**Comment by Godricly** [comment]
So the old issue never dies. :laughing:  Try converting them into fp32 before kvstore operations. The time cost here is limited.

**Comment by ptrendx** [comment]
@mli  @piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
