### ISSUE TITLE
error LNK2019: 无法解析的外部符号 "class nnvm::Graph __cdecl nnvm::ApplyPasses

### ISSUE THREAD

**Issue by wuchuanying** [apache/incubator-mxnet#7558]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:win10

Compiler:vs2013 x64 debug

Package used (Python/R/Scala/Julia):cpp-package

MXNet version:mxnet_cpu\apache-mxnet-src-0.11.rc1-incubating

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
错误	1	error LNK2019: 无法解析的外部符号 "class nnvm::Graph __cdecl nnvm::ApplyPasses(class nnvm::Graph,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?ApplyPasses@nnvm@@YA?AVGraph@1@V21@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z)，该符号在函数 "class nnvm::Graph __cdecl nnvm::ApplyPass(class nnvm::Graph,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?ApplyPass@nnvm@@YA?AVGraph@1@V21@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用	D:\YISA\PR\MXNet.cpp-master\windows\vs\MxnetTestApp\lenet_with_mxdataiter.obj	MxnetTestApp
## Minimum reproducible example
nnvm::Symbol sym;

	{
		nnvm::Graph g;
		g.attrs["json"] = std::make_shared<nnvm::any>(symbol_json_str);
		sym.outputs = nnvm::ApplyPass(g, "LoadLegacyJSON").outputs;
	}
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.add all lib:openblas dmlc mxnet opencvlib ，but still error
2.
3.

**Comment by wuchuanying** [comment]
cpu版本

**Comment by chinakook** [comment]
On Windows, VS2015 update 3 is OK.
I have only tried Release mode.

**Comment by wuchuanying** [comment]
is ok，thanks
