### ISSUE TITLE
How to measure the time consumed by every batch in training?

### ISSUE THREAD

**Issue by clavichord93** [apache/incubator-mxnet#7575]
I want to measure the time consumed by every batch in training, but the asynchronous mechanism in mxnet make this difficult and I didn't find a way to do synchronization in documentations. Is there a way to force synchronization in mxnet? And what is the best way to do this evaluation in mxnet? And should I use NaiveEngine or other engine types? Thanks a lot.

**Comment by ShownX** [comment]
how about
```
import timeit
timeit.default_timer()
```
or you can use callback function ```mxnet.callback.Speedometer(batch_size, frequent=1)```

**Comment by clavichord93** [comment]
@ShownX Can timeit be used to measure asynchronous procedure? And how can I use callback function? Can you explain it more explicitly?

**Comment by ShownX** [comment]
Not sure, I am only using this to measure the time for one batch.

**Comment by clavichord93** [comment]
@ShownX Thank you, I will take a try.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
