### ISSUE TITLE
warp_size

### ISSUE THREAD

**Issue by stefanhenneking** [apache/incubator-mxnet#7578]
For the GPU kernels, it'd be good to have a defined constant for the warp size so that it doesn't have to be hard coded in each file (see for example `static const unsigned WARP_SIZE = 32` in `batch_norm.cu`). 
Reading the `warpSize` from the `cudaDeviceProp` wouldn't be a good solution in my opinion in terms of performance.
If NVIDIA decides to change the warp size on a future architecture, it could then easily be switched depending on `__CUDA_ARCH__`.

@eric-haibin-lin @reminisce @cjolivier01 @bhavinthaker @piiswrong

**Comment by szha** [comment]
common/cuda_utils.h might be a good place for that.

**Comment by szha** [comment]
Is anyone taking this?

**Comment by cjolivier01** [comment]
Be sure not to call to retrieve the value until a CUDA operation is imminent (i.e. Not on stating startup), or else it will cause the CUDA library to initialize (when there is one) or error (when there isn't).

**Comment by cjolivier01** [comment]
I can probably add it to my optimization work since I make note of when GPU has first use. One drawback is that since mshadow has no static data, it's not straightforward how to set it in such a way that mshadow scope would be able to "see" it, without being kludgy.  Any suggestions?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
