### ISSUE TITLE
Why a same code's GPU version cost more memory than CPU version?

### ISSUE THREAD

**Issue by cuteding** [apache/incubator-mxnet#7588]
I made a very simple network using mxnet(two fc layers with dim of 512).

By changing the ctx = mx.cpu() or ctx = mx.gpu(0), I run the same code on both CPU and GPU.

The memory cost of GPU is much bigger than CPU version.(I checked that using 'top' instead of 'nvidia-smi').

![mem](https://user-images.githubusercontent.com/28648091/29701664-9452417a-899f-11e7-920e-8813ab807280.jpg)

It seems strange, as the GPU version also has memory on GPU already, why GPU still need more space on memory?

**Comment by chinakook** [comment]
+1, I have this problem too. When I test a SSD detection model in CPU, the host memory consumption is about 400MB. However, in the GPU context the host memory consumption is about 1200MB and GPU memory consumption is about 500MB.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
