### ISSUE TITLE
MXNetR: How to corrupt input layer? (

### ISSUE THREAD

**Issue by thomasmooon** [apache/incubator-mxnet#7595]
I've asked a similar, but not the same question in issue #7490.
The difference is: The intention is not to dropout input units, rather corrupt the input by setting values to zero. I don't know how to implement it in a net using symbolic language.

How can one implement the "corrupting procedure" into the "net"?

# corrupting procedure
p <- 0.25
set.seed(1)
x <- mx.nd.array(matrix(runif(25,1,20),nrow=5))
mask <- mx.nd.uniform(0,1,dim(x)) 
mask <- mx.nd.broadcast.lesser(mask ,mx.nd.array(1-p))

### original input
x
```
          [,1]      [,2]      [,3]      [,4]
[1,]  6.044664  4.831957 12.953167 14.053434
[2,]  8.070354 18.069405  2.173939  8.297971
[3,] 11.884213 18.948830  4.913517 15.626987
[4,] 18.255947 13.555158  4.354578 10.456285
```
### corruption mask
mask
   ```
  [,1] [,2] [,3] [,4]
[1,]    0    1    0    1
[2,]    0    0    0    0
[3,]    1    0    1    1
[4,]    0    1    1    0
```

### apply corruption
x*mask
```
         [,1]      [,2]     [,3]     [,4]
[1,]  0.00000  4.831957 0.000000 14.05343
[2,]  0.00000  0.000000 0.000000  0.00000
[3,] 11.88421  0.000000 4.913517 15.62699
[4,]  0.00000 13.555158 4.354578  0.0000
```

# net

```
create_drop_net <- function(num_hidden=10, p = 0.2) {
  data <- mx.symbol.Variable("data")
```
Corrupt input, but how?? This  insertion won't work:
```
mask <-  mx.symbol.random_uniform(low = 0, high = 1, shape = dim(data))
mask <- mx.symbol.broadcast_lesser(lhs = mask, rhs = 1-p)
data <- data*mask
```
--> error
_Error in mx.varg.symbol.random_uniform(list(...)) :
  symbol.cc:308: RCheck failed: keys[i].length() != 0 Non Symbol parameters is only accepted via key=value style.
Calls: mx.model.FeedForward.create ... mx.symbol.random_uniform -> mx.varg.symbol.random_uniform -> .External
Execution halted_

```
  label <- mx.symbol.Variable('label')
  fc1 <- mx.symbol.FullyConnected(data, name = "fc1", num_hidden = num_hidden)
  act1 <- mx.symbol.Activation(fc1, name = "relu1", act_type = "relu")
  fc2 <- mx.symbol.FullyConnected(act1, name = "fc2", num_hidden = num_hidden)
  act2 <- mx.symbol.Activation(fc2, name = "relu2", act_type = "relu")
  fc3 <- mx.symbol.FullyConnected(act2, name = "fc3", num_hidden = num_hidden)
  act3 <- mx.symbol.Activation(fc3, name = "relu3", act_type = "relu")
  recon <- mx.symbol.FullyConnected(act3, name = "reconstruction", num_hidden = nrow(train))
  net <- mx.symbol.LinearRegressionOutput(data = recon, label = label)
  return(net)
}
```

the rest of the code (data iterator and training)
```
# data iterator
batchIter <- 128
trainIter <- mx.io.arrayiter(data = train, label = train, batch.size = batchIter)
valIter <- mx.io.arrayiter(data = test, label = test, batch.size = batchIter)

# train
mx.set.seed(0)
model <- mx.model.FeedForward.create(
  create_drop_net(num_hidden = 10),
  X = trainIter, 
  eval.data = valIter,
  ctx = device,
  num.round = 10,
  array.batch.size = length(device)*128,
  learning.rate = 0.1,
  momentum = 0.9,
  eval.metric = mx.metric.rmse, 
  array.layout = "colmajor",
  initializer = mx.init.uniform(0.1),
  epoch.end.callback = mx.callback.log.train.metric(10)
)
```

**Comment by thomasmooon** [comment]
# graph.viz

### and why does  this work? (mx.symbol.random_uniform..., shape = c(128, 99)))
![image](https://user-images.githubusercontent.com/29228225/29668485-acb88d10-88e0-11e7-9831-0237243e7d87.png)


![image](https://user-images.githubusercontent.com/29228225/29668365-33e5481a-88e0-11e7-9090-e4518956580b.png)



### ... but this not?  (mx.symbol.random_uniform..., shape = dim(data))
![image](https://user-images.githubusercontent.com/29228225/29668511-c1d3002c-88e0-11e7-8cba-b346fb67f97f.png)

![image](https://user-images.githubusercontent.com/29228225/29668449-804b33ea-88e0-11e7-80c6-c89bb2ee2209.png)

**Comment by xzqjack** [comment]
As there is no nd.randint,symbol in mxnet, you can define a sym.Variable('mask') to store mask. Then, you can generate mask tensor with numpy.randint as mask input during training. When testing, you can set all values of mask 1.

Absolutely you can define a 0-1-mask layer with reference to [https://github.com/apache/incubator-mxnet/blob/master/example/numpy-ops/custom_softmax.py](https://github.com/apache/incubator-mxnet/blob/master/example/numpy-ops/custom_softmax.py).

**Comment by thomasmooon** [comment]
If I would do this, then I'd have the same mask for every iteration / batch. 
This would be equal to corrupt my data directly (outside the net by corruption a fraction of p) and then plug it into the net.
This has the huge disadvantage, that if any observation is drawn more than once, the corruption pattern is guaranteed the same (thus not random) and the net doesn't learn a generalization to fill in the gaps. 

But if the intention is to generate a new corruption mask _every time a new batch is drawn_ this won't work either. 

To clarify: The final result will be a stacked denoising autoencoder (SDAE), whereas no example for MXNetR exists so far.

**Comment by thomasmooon** [comment]
Solved
![image](https://user-images.githubusercontent.com/29228225/29713204-d36d9460-899d-11e7-8758-8b131948bc68.png)
