### ISSUE TITLE
"is_1x1_" in convolution operator is not really used

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#7596]
I found that "is_1x1_" in convolution-inl.h is not really used.  MXNet just create the "is_1x1_" but not use it to skip the im2col function call. In contrast, the "is_1x1_" in Caffe is really used to skip im2col function call to accelerate the 1x1 convolution. It is very important in some cases such as the Google's Mobilenet.

**Comment by piiswrong** [comment]
@reminisce

**Comment by reminisce** [comment]
This variable is borrowed from caffe: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/base_conv_layer.cpp#L110, where it is used to skip col_buff memory allocation in the 1x1 kernel case. If it's really a common use case, we should also do the optimization as in caffe as well.

**Comment by chinakook** [comment]
[The 3.2 section](https://arxiv.org/abs/1704.04861) of Mobilenet paper have mentioned that. I found the 1x1 convolution(with stride 1 and pad 0) is commonly used in almost all modern networks such as Googlenet/Inception/Resnet/ResNeXt too. When these networks are used in detection or segmetation, the intermediate feature maps will become very large, so the im2col skipped 1x1 convolution operation might save a lot of memory and computing resource.

**Comment by reminisce** [comment]
@chinakook Are your interested in submitting a PR to fix this? Otherwise, I will do it later.

**Comment by chinakook** [comment]
@reminisce I will try it. I've optimized the Forward funtion, then I‘ve got about 10ms reduced when inferencing a mobilenet on CPU.

**Comment by chinakook** [comment]
@reminisce PR is pulled. #7613
