### ISSUE TITLE
error C2768 "linalg_gemm":Illegal use of explicit template arguments

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#7610]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Windows
Compiler:
Visual studio 2015 update 3, MKL, WITHOUT_CUDA
Package used (Python/R/Scala/Julia):
non
MXNet version:
0.11.1
Or if installed from source:
master
MXNet commit hash (`git rev-parse HEAD`):
bc468b0
If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

Codes in line 357 to 376 of "linalg_impl.h" is wrong and cause VS show "error C2768".

## What have you tried to solve it?

1.
2.
3.

**Comment by chinakook** [comment]
error LNK2019
"void __cdecl linalg_batch_trsm"
"void __cdecl linalg_batch_gemm"

**Comment by piiswrong** [comment]
Is this solved by the most recent fix?

**Comment by chinakook** [comment]
It's partly solved. New issues:
d:\proj\dev\mx\src\operator\linalg_impl.h(442): error C2872: 'cpu': ambiguous symbol (compiling source file D:\proj\dev\mx\src\operator\upsampling.cc)
d:\proj\dev\mx\src\operator\linalg_impl.h(443): error C2872: 'cpu': ambiguous symbol (compiling source file D:\proj\dev\mx\src\operator\upsampling.cc)
