### ISSUE TITLE
train_cifar10.py issue

### ISSUE THREAD

**Issue by rohith14** [apache/incubator-mxnet#7619]
I get this error while running train_cifar10.py,

[17:56:49] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/./logging.h:304: [17:56:49] src/io/image_aug_default.cc:282: Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape

modified the code in train_cifar10.py to,
fit.add_fit_args(parser)
    data.add_data_args(parser)
    data.add_data_aug_args(parser)
    data.set_data_aug_level(parser, 2)
    parser.set_defaults(
        # network
        network        = 'alexnet',
        # data
        data_train     = 'points to .rec file in s3 bucket',
        #data_train = train_fname,
        data_val       = val_fname,
        num_classes    = 10,
        num_examples  = 50000,
        image_shape    = '3,227,227',
        pad_size       = 4,
        # train
        batch_size     = 128,
        num_epochs     = 300,
        lr             = .05,
        lr_step_epochs = '200,250',
    )
    args = parser.parse_args()

Also, while generating the rec file using im2rec.py, i re-sized my images to 227x227x3

Any help is appreciated.  Thanks

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
