### ISSUE TITLE
Passing arguments to Custom operators

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#7639]
I am trying to implement a custom operator, using the  directives in https://mxnet.incubator.apache.org/how_to/new_op.html . To keep things simple, I am following the Python approach and subclass `mx.operator.CustomOp`. From the example I see that we need to call `mx.symbol.Custom(data=fc3, name='softmax', op_type='softmax')` in order to instantiate the new custom operator (using the registered name for the new operator instead of softmax, of course). In my case, I need some input custom input arguments for my operator while creating it, affecting its operational behavior. What would be the best way to pass them to the custom op; since `mx.symbol.Custom` init method takes limited number of arguments.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by mlipkovich** [comment]
For those who will be facing the same issue:
`mx.symbol.Custom`  has `**kwargs` parameter. All these parameters will be passed to your custom operator `__init__` method. 
So if your custom operator `custom_operator` requires argument `additional_argument` you can pass it using 
`mx.symbol.Custom(data=fc3, name='operator', op_type='custom_operator', additional_argument=4) `
