### ISSUE TITLE
Max norm regularization

### ISSUE THREAD

**Issue by patwa67** [apache/incubator-mxnet#7642]
Is there some way to perform max norm regularization in mxnet?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by viebboy** [comment]
Have you figured out how to implement max norm regularization yet?
