### ISSUE TITLE
About resnet50 implemented using CaffeOp

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#7651]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
centos7.2
Compiler:
gcc
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.9.5
Or if installed from source:
yes
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide
python-2.7
Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

When I implement the resnet-50 network by CaffeOp operator fully, I found that, the "batch normlization layer" and the "scale layer" with some problems:

First, in init_params, the dimension is not adapted;

Second, I think the network with CaffeOp can not convergence when trainning, which is normal in train_resnet.py in mxnet's original operator; and also, It is normal in caffe;

Third, When I alternate the resnet-50 symbol with a simple lenet-5 symbol, it looks like normall

Thank you for your answer!
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by idealboy** [comment]
The weight is not updated normally , when I check the value with monitor, and all the value is same from begin to end in training in each batch

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
