### ISSUE TITLE
ipython, The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by HuangZhanPeng** [apache/incubator-mxnet#7653]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: CentOS

Compiler:

Package used (Python/R/Scala/Julia):Python

MXNet version:0.11.rc

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
I follow the tutorial:Manipulate data the MXNet way with ndarray, the code is ok, but when I excute nd.dot(x, y.T), ipython raise the error "The kernel appears to have died. It will restart automatically." 

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by DamonDeng** [comment]
Dear, 
Would you please share more information of the code you run?

I have tested the following code in Jupyter notebook environment, and it works well:

`import mxnet as mx
x = mx.nd.ones((2,3))
y = mx.nd.ones((2,3))*2

z = mx.nd.dot(x, y.T)

z.asnumpy()`

the output is:

`array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)`

**Comment by hdjsjyl** [comment]
Do you have solved this problem? I meet the same problem.

**Comment by HuangZhanPeng** [comment]
@hdjsjyl No！I have already change to UBUNTU now

**Comment by eric-haibin-lin** [comment]
What version of openblas did you use? I've seen similar issues like this when a buggy version of openblas is installed.

**Comment by WeiLai5432** [comment]
Do you have solved this problem? I meet the same problem on my RaspberryPi 3B (armv7l GNU/Linux), and I have tried all solutions I found but no one works, neither are rpi branch and arm-stable branch in [arank/mxnet](https://github.com/arank/mxnet/tree/rpi).

**Comment by phizaz** [comment]
Using `np.float16` causes it to die.

```
import mxnet as mx
import numpy as np

x = mx.nd.ones((2,3), dtype=np.float16)
z = mx.nd.dot(x, x.T)
z.asnumpy()
```

**Comment by lebeg** [comment]
Is this still a problem with latest / 1.2 MXNet?

**Comment by lanking520** [comment]
Close this issue due to the inactivity. Please try with the up-to-date package and use blas version 0.33+ in your build. Please feel free to comment or reopen it if you are still facing the same problems.
