### ISSUE TITLE
Create cublas handle failed

### ISSUE THREAD

**Issue by Godricly** [apache/incubator-mxnet#7666]
## Environment info
Operating System:
Ubuntu， cuda8.0

MXNet commit hash (`git rev-parse HEAD`):
e05129774e76206fe890b511c346953107b05fce

python2.7

## Error Message:
Please paste the full error message, including stack trace.
incubator-mxnet/mshadow/mshadow/./stream_gpu-inl.h:115: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```python
ctx=mx.gpu(0)
doc_net = models.Inception3(classes=2)
doc_net.collect_params().initialize(mx.init.Xavier(magnitude=2.24), ctx=ctx,verbose=True)
```

**Comment by xuzhenqi** [comment]
I have also encountered this problem, when upgrading driver for 375.26 to 378.13.
