### ISSUE TITLE
Issue with Loss function

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#7677]
@szha @astonzhang @madjam 
test_ce_loss is failing too frequently leading to failures in master CI builds. Based on the conversation, it looks like Aston is working on the fix. In the meantime, as part of stabilizing CI builds and avoid other issues getting in unnoticed, I am skipping this test.
This issue should help to track in the fix and re-enabling the test_ce_loss.

**Comment by szha** [comment]
@astonzhang is already looking at this and will pr shortly.

**Comment by astonzhang** [comment]
@sandeep-krishnamurthy @madjam 
#7659 proposed a fix in its latest commit

**Comment by sandeep-krishnamurthy** [comment]
Thanks @astonzhang Can we get this fix to the test go ahead in separate PR ASAP so that we recover from failing builds?
Thanks for working on this.

**Comment by astonzhang** [comment]
Thank you @sandeep-krishnamurthy 
The separate PR is now available in #7693
