### ISSUE TITLE
ValueError: Data provided by data_shapes don't match names specified by data_names ([] vs. ['data'])

### ISSUE THREAD

**Issue by jaewoosong** [apache/incubator-mxnet#7681]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Compiler: Python 3.6.1 (Anaconda 4.4.0, 64bit), installed by pip

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.11.0

Python version and distribution: Python 3.6.1 (Anaconda 4.4.0, 64bit), installed by pip

## Error Message:
```
Traceback (most recent call last):
  File "/home/jaewoo/temp2.py", line 63, in <module>
    mod.fit(data_iter, num_epoch=5)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py", line 487, in fit
    self.forward_backward(data_batch)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py", line 191, in forward_backward
    self.forward(data_batch, is_train=True)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 594, in forward
    self.reshape(new_dshape, new_lshape)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 457, in reshape
    self.data_names, self.label_names, data_shapes, label_shapes)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py", line 71, in _parse_data_desc
    _check_names_match(data_names, data_shapes, 'data', True)
  File "/home/jaewoo/Programs/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py", line 63, in _check_names_match
    raise ValueError(msg)
ValueError: Data provided by data_shapes don't match names specified by data_names ([] vs. ['data'])
```

## Minimum reproducible example
```
import mxnet as mx
import os
import subprocess
import numpy as np
import matplotlib.pyplot as plt
import tarfile

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

class SimpleIter(mx.io.DataIter):
    def __init__(self, data_names, data_shapes, data_gen,
                 label_names, label_shapes, label_gen, num_batches=10):
        self._provide_data = zip(data_names, data_shapes)
        self._provide_label = zip(label_names, label_shapes)
        self.num_batches = num_batches
        self.data_gen = data_gen
        self.label_gen = label_gen
        self.cur_batch = 0

    def __iter__(self):
        return self

    def reset(self):
        self.cur_batch = 0

    def __next__(self):
        return self.next()

    @property
    def provide_data(self):
        return self._provide_data

    @property
    def provide_label(self):
        return self._provide_label

    def next(self):
        if self.cur_batch < self.num_batches:
            self.cur_batch += 1
            data = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_data, self.data_gen)]
            label = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_label, self.label_gen)]
            return mx.io.DataBatch(data, label)
        else:
            raise StopIteration

num_classes = 10
net = mx.sym.Variable('data')
net = mx.sym.FullyConnected(data=net, name='fc1', num_hidden=64)
net = mx.sym.Activation(data=net, name='relu1', act_type="relu")
net = mx.sym.FullyConnected(data=net, name='fc2', num_hidden=num_classes)
net = mx.sym.SoftmaxOutput(data=net, name='softmax')
print(net.list_arguments())
print(net.list_outputs())

n = 32
data_iter = SimpleIter(['data'], [(n, 100)],
                  [lambda s: np.random.uniform(-1, 1, s)],
                  ['softmax_label'], [(n,)],
                  [lambda s: np.random.randint(0, num_classes, s)])

mod = mx.mod.Module(symbol=net)
mod.fit(data_iter, num_epoch=5)
```
Actually this code is same as the official mxnet tutorial. ( https://mxnet.incubator.apache.org/tutorials/basic/data.html )

## What have you tried to solve it?
It seems `def _parse_data_desc(data_names, label_names, data_shapes, label_shapes)` and `def _check_names_match(data_names, data_shapes, name, throw)` have bugs.

**Comment by jesterhazy** [comment]
This example code doesn't work with Python 3 yet. If you create a new conda environment with python 2.7, the example will run fine. I was able to run the full data.ipynb notebook in this conda environment:

```
conda create --name mxnet-py27 python=2.7
pip install opencv-python requests matplotlib jupyter mxnet future
```

**Comment by jaewoosong** [comment]
@jesterhazy I see. Thank you for your help!

**Comment by shipeng-uestc** [comment]
Hi,I have the same problem.How solve it in the python3?

**Comment by blakeliu** [comment]
**win10 
python                      3.5.2
mxnet-cu80                0.12.0b20171024
run data.ipynb**

```
import logging
logging.basicConfig(level=logging.INFO)
n = 32
data_iter = SimpleIter(['data'], [(n, 100)],
                  [lambda s: np.random.uniform(-1, 1, s)],
                  ['softmax_label'], [(n,)],
                  [lambda s: np.random.randint(0, num_classes, s)])

mod = mx.mod.Module(symbol=net)
mod.fit(data_iter, num_epoch=5)
```


:------>
ValueError                                Traceback (most recent call last)
<ipython-input-7-6ceb7dd11508> in <module>()
      9 
     10 mod = mx.mod.Module(symbol=net)
---> 11 mod.fit(data_iter, num_epoch=5)

C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py in fit(self, train_data, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, optimizer, optimizer_params, eval_end_callback, eval_batch_end_callback, initializer, arg_params, aux_params, allow_missing, force_rebind, force_init, begin_epoch, num_epoch, validation_metric, monitor)
    485                 if monitor is not None:
    486                     monitor.tic()
--> 487                 self.forward_backward(data_batch)
    488                 self.update()
    489                 try:

C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py in forward_backward(self, data_batch)
    189     def forward_backward(self, data_batch):
    190         """A convenient function that calls both ``forward`` and ``backward``."""
--> 191         self.forward(data_batch, is_train=True)
    192         self.backward()
    193 

C:\Anaconda3\lib\site-packages\mxnet\module\module.py in forward(self, data_batch, is_train)
    592                 new_lshape = None
    593 
--> 594             self.reshape(new_dshape, new_lshape)
    595 
    596         self._exec_group.forward(data_batch, is_train)

C:\Anaconda3\lib\site-packages\mxnet\module\module.py in reshape(self, data_shapes, label_shapes)
    454         assert self.binded
    455         self._data_shapes, self._label_shapes = _parse_data_desc(
--> 456             self.data_names, self.label_names, data_shapes, label_shapes)
    457 
    458         self._exec_group.reshape(self._data_shapes, self._label_shapes)

C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py in _parse_data_desc(data_names, label_names, data_shapes, label_shapes)
     69     """parse data_attrs into DataDesc format and check that names match"""
     70     data_shapes = [x if isinstance(x, DataDesc) else DataDesc(*x) for x in data_shapes]
---> 71     _check_names_match(data_names, data_shapes, 'data', True)
     72     if label_shapes is not None:
     73         label_shapes = [x if isinstance(x, DataDesc) else DataDesc(*x) for x in label_shapes]

C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py in _check_names_match(data_names, data_shapes, name, throw)
     61             name, name, str(data_shapes), str(data_names))
     62         if throw:
---> 63             raise ValueError(msg)
     64         else:
     65             warnings.warn(msg)

ValueError: Data provided by data_shapes don't match names specified by data_names ([] vs. ['data'])

**Comment by QiXuanWang** [comment]
Found the same issue with Python3.6. I was about to report an issue and then found this. Please fix.

**Comment by SrivastavaKshitij** [comment]
I am having the issue while running latest version of mxnet. Can somebody help here !!

Contributors ?

**Comment by aaronmarkham** [comment]
#9460 should have fixed this. Please confirm & close.
