### ISSUE TITLE
How can I debug mxnet?

### ISSUE THREAD

**Issue by mxmxlwlw** [apache/incubator-mxnet#7683]
Hi, I want to debug mxnet, and I use mxnet in python. How can I smoothly debug mxnet and its submodule nnvm?

**Comment by szha** [comment]
DEBUG flag in make config, and gdb

**Comment by mxmxlwlw** [comment]
Yes, that's how I do this now. So there's no elegant way to do this? Because I want to debug every function in the mxnet.

**Comment by szha** [comment]
@mxmxlwlw what would you describe as elegant? IDE integration?

**Comment by mxmxlwlw** [comment]
for example, I want to run python and when the code goes into the library, it stopped, and so I can debug it.

**Comment by szha** [comment]
@mxmxlwlw I see. I found the following two posts that are relevant, though I haven't tried gdb this way myself.
http://johntfoster.github.io/posts/debugging-cc%2B%2B-libraries-called-by-python.html
https://stackoverflow.com/questions/13653467/gdb-break-in-shared-library-loaded-by-python

**Comment by mxmxlwlw** [comment]
@szha I know these method. However, it still can't be stopped when the code goes into the library unless you already know what function it will goes in.

**Comment by chinakook** [comment]
Building mxnet with visual studio DEBUG mode may be a good choice.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
