### ISSUE TITLE
Python3.5 MXNet doesn't execute for loop！！

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#7684]
I try to follow The Custom Iterator section's code in the tutorial page at  https://mxnet.incubator.apache.org/tutorials/basic/data.html.  But I found these two line are never executed!
data = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_data, self.data_gen)]
label = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_label, self.label_gen)]
My python's version is python3.5 and mxnet is 0.95.
Does any could help to fix this problem?

**Comment by szha** [comment]
The example works fine.
