### ISSUE TITLE
dec (in examples) fails for 2 cluster

### ISSUE THREAD

**Issue by zqkhan** [apache/incubator-mxnet#7687]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: GNU/linux

Compiler:

Package used : python

MXNet version: 0.7.0

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 2.7.5

## Error Message:

Please paste the full error message, including stack trace.

121.5 [220 463]
102.5 [444 239]
0.948755490483
463 0.683
Traceback (most recent call last):
  File "dec.py", line 190, in <module>
    mnist_exp(mx.cpu(0))
  File "dec.py", line 175, in mnist_exp
    a,b,y[i] = dec_model.cluster(X,Y,i)
  File "dec.py", line 155, in cluster
    train_iter, 0, 1000000000, {}, False)
  File "/home/khan.zu/mxnet-master/example/dec/../autoencoder/solver.py", line 117, in solve
    [output_buff[output_names[0]]])
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/metric.py", line 350, in update
    reval = self._feval(label, pred)
  File "dec.py", line 125, in ce
    return np.sum(label*np.log(label/(pred+0.000001)))/label.shape[0]
ValueError: operands could not be broadcast together with shapes (256,2) (256,)

## Minimum reproducible example
using the same code as in the example/dec with my own dataset which has 2 clusters, works fine when i set clusters more than 2
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
