### ISSUE TITLE
Fixed Embedding Layer on Gluon

### ISSUE THREAD

**Issue by rravu3** [apache/incubator-mxnet#7692]
Is there a way to declare a Layer(Block) to be constant and not be updated during training?
The only way I see it as of now is to create my own layer and not add embedding matrix to the ParameterDict.

**Comment by szha** [comment]
```python
layer = Dense(10)
layer.weight.lr_mult=0
```

**Comment by szha** [comment]
Or you can do the dot and addition yourself with the fixed weight matrix.

**Comment by piiswrong** [comment]
Set grad_req to 'null' for the parameter that you don't want to update
