### ISSUE TITLE
can not find pretrained model of inception-v4 and inception-resnet-v2 in model zoo.

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#7697]
i need pretrained model of inception-v4 and inception-resnet-v2 , but i can not find them in model zoo. I think it is proper to add them in the model zoo.
Does anyone have one?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
