### ISSUE TITLE
Webpage rendering error on IE 11, showing blank page.

### ISSUE THREAD

**Issue by zhreshold** [apache/incubator-mxnet#7704]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows server 2016 Base (ami-27a58d5c)
IE version 11.1593.14393

## Error Message:
Internet Explorer can't render mxnet.io webpage. Showing blank page with scroll bar.
Debug tool shows: 
```
Could not locate https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/less/grid.less specified in source map https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css.map.
```

## Minimum reproducible example
https://mxnet.io or https://mxnet.incubator.apache.org/

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
@kevinthesun

**Comment by kevinthesun** [comment]
Did this issue pop up recently? Bootstrap version hasn't been changed since last year. 
IE can be problematic since many html5/css3 features are not supported. Use chrome/firefox/safari if possible.
