### ISSUE TITLE
About the preprocessing.py in inception-v3 pretraned model tar file

### ISSUE THREAD

**Issue by universewill** [apache/incubator-mxnet#7705]
Shoud i normalize the image before put it as data input? Or the normalize process will automatically down by mxnet? 
I see the code in preprocessing.py in inception-v3 pretraned model tar file (The pretrainded model is in mxnet model zoo). Should i do the same before using the inception-v3 pretraned model?

```
# sub mean
normed_img = sample - 128.
normed_img /= 128.
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
