### ISSUE TITLE
How symbol composition works?

### ISSUE THREAD

**Issue by x10000year** [apache/incubator-mxnet#7714]
The following code:

x = mx.symbol.Variable('x')
y = mx.symbol.Variable('y')
a = x * 2
b = y + a
c = b(y=a)

If we run print(c.tojson()), we can find that there are two duplicate input variables named "x" in symbol c, and the expression a is computed twice. Is this the expected result?

The output of c.tojson() is:

{
  "nodes": [
    {
      "op": "null", 
      "name": "x", 
      "inputs": []
    }, 
    {
      "op": "_mul_scalar", 
      "name": "_mulscalar0", 
      "attr": {"scalar": "2"}, 
      "inputs": [[0, 0, 0]]
    }, 
    {
      "op": "null", 
      "name": "x", 
      "inputs": []
    }, 
    {
      "op": "_mul_scalar", 
      "name": "_mulscalar0", 
      "attr": {"scalar": "2"}, 
      "inputs": [[2, 0, 0]]
    }, 
    {
      "op": "elemwise_add", 
      "name": "_plus0", 
      "inputs": [[1, 0, 0], [3, 0, 0]]
    }
  ], 
  "arg_nodes": [0, 2], 
  "node_row_ptr": [0, 1, 2, 3, 4, 5], 
  "heads": [[4, 0, 0]], 
  "attrs": {"mxnet_version": ["int", 1101]}
}

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
