### ISSUE TITLE
Volumetric convolution in mxnet

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#7718]
I had a feature map of dim(H*W*C).
H->Height, W->Width,C->No of channels.

I would like to apply on 3-dim feature map to have output like...(h*w*r2*l)
h->height of modified feature map
w->width of modified feature map
r2->no of channels of modified feature map.
l-> no of label map and each label map is of resolution h*w*r2.

How to implement this in mxnet?
Kindly provide solution....

**Comment by chowkamlee81** [comment]
I had a feature map of dim(HWC).
H->Height, W->Width,C->No of channels.

I would like to apply convolution operation on 3-dim feature map to have output like...(hwr2l)
h->height of modified feature map
w->width of modified feature map
r2->no of channels of modified feature map.
l-> no of label map and each label map is of resolution hw*r2.

How to implement this in mxnet?
Kindly provide solution....

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
