### ISSUE TITLE
Can a header file that uses DMLC_DECLARE_PARAMETER be included more than once?

### ISSUE THREAD

**Issue by x10000year** [apache/incubator-mxnet#7723]
In the file "dmlc-core/include/dmlc/parameter.h" line 234, the macro DMLC_DECLARE_PARAMETER  is documented that 

> This macro need to be put in a source file so that registeration only happens once. 

Is this true? So if I put DMLC_DECLARE_PARAMETER in a header file, the header file cannot be included by multiple .cc files? But DMLC_DECLARE_PARAMETER can only be written inside the definition of a struct, so the struct can only be used by one .cc file?

Another problem is, whether DMLC_DECLARE_FIELD support std::vector?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
