### ISSUE TITLE
MXNetError: This layer requires uniform type. Expected 3 v.s. given 0 at weight

### ISSUE THREAD

**Issue by freshmanfresh** [apache/incubator-mxnet#7729]
**when i used gluon package, i met the error following:**

MXNetError                                Traceback (most recent call last)
/home/wangy/test/multi/cnn_mxnet.py in <module>()
    113 
    114 
--> 115 train(400)
    116 
    117 t1 = time.time()

/home/wangy/test/multi/cnn_mxnet.py in train(batch_size)
     93             data = data.as_in_context(ctx)
     94             label = label.as_in_context(ctx)
---> 95             output = net(data)
     96             loss = bce(output,label)
     97 

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.pyc in __call__(self, *args)
    266     def __call__(self, *args):
    267         """Calls forward. Only accepts positional arguments."""
--> 268         return self.forward(*args)
    269 
    270     def forward(self, *args):

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/gluon/nn/basic_layers.pyc in forward(self, x)
     44     def forward(self, x):
     45         for block in self._children:
---> 46             x = block(x)
     47         return x
     48 

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.pyc in __call__(self, *args)
    266     def __call__(self, *args):
    267         """Calls forward. Only accepts positional arguments."""
--> 268         return self.forward(*args)
    269 
    270     def forward(self, *args):

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.pyc in forward(self, x, *args)
    408                         i._finish_deferred_init()
    409                     params = {i: j.data(ctx) for i, j in self._reg_params.items()}
--> 410                 return self.hybrid_forward(ndarray, x, *args, **params)
    411 
    412         assert isinstance(x, Symbol), \

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/gluon/nn/conv_layers.pyc in hybrid_forward(self, F, x, weight, bias)
    125             act = getattr(F, self._op_name)(x, weight, name='fwd', **self._kwargs)
    126         else:
--> 127             act = getattr(F, self._op_name)(x, weight, bias, name='fwd', **self._kwargs)
    128         if self.act is not None:
    129             act = self.act(act)

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/ndarray.pyc in Convolution(data, weight, bias, kernel, stride, dilate, pad, num_filter, num_group, workspace, no_bias, cudnn_tune, cudnn_off, layout, out, name, **kwargs)

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/_ctypes/ndarray.pyc in _imperative_invoke(handle, ndargs, keys, vals, out)
     87         ctypes.c_int(len(keys)),
     88         c_array(ctypes.c_char_p, [c_str(key) for key in keys]),
---> 89         c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
     90 
     91     if original_output is not None:

/home/wangy/tools/anaconda2/lib/python2.7/site-packages/mxnet/base.pyc in check_call(ret)
    127     """
    128     if ret != 0:
--> 129         raise MXNetError(py_str(_LIB.MXGetLastError()))
    130 
    131 if sys.version_info[0] < 3:

MXNetError: [11:28:32] src/operator/./convolution-inl.h:550: Check failed: (*in_type)[i] == dtype (0 vs. 3) This layer requires uniform type. Expected 3 v.s. given 0 at weight

**Following is part of my code**

    def cnn_model():
        net = gluon.nn.Sequential()
        net.add(gluon.nn.Conv1D(channels=700,kernel_size=8,strides=1,activation='relu'))
        net.add(gluon.nn.MaxPool1D(pool_size=20))
        net.add(gluon.nn.Dropout(0.2))
        net.add(gluon.nn.Flatten())
        net.add(gluon.nn.Dense(5000,activation='relu'))
        net.add(gluon.nn.Dropout(0.2))
        net.add(gluon.nn.Dense(919,activation='sigmoid'))
        return net

        
    #Loading data
    print("Loading training data...")
    f1 = h5py.File('../../data/train_100.hdf5')
    data1=f1['sequence_code'][:,:,:]
    data1=data1.swapaxes(1,2)
    label1=f1['label'][:,:]
    t_dataset=gluon.data.ArrayDataset(data1,label1)

    train_data = mx.gluon.data.DataLoader(t_dataset,batch_size,shuffle=False)
       
    #traning and validing
    net=cnn_model()
    ctx=mx.gpu()
    net.collect_params().initialize(mx.init.Xavier(magnitude=2.24),ctx=ctx)
    bce=mx.gluon.loss.SigmoidBinaryCrossEntropyLoss()
    trainer = mx.gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': 1,'wd':1e-6})
    print("Start training...")
    
    epochs = 15
    smoothing_constant = .01

    for e in range(epochs):
        for i, (data, label) in enumerate(train_data):
            data = data.as_in_context(ctx)
            label = label.as_in_context(ctx)
            output = net(data)`

**Comment by szha** [comment]
It seems that your network is somehow expecting `uint8` for the weight while receiving `float32` type instead. Could you try to cast the data using `data = data.astype('float32')`?

**Comment by freshmanfresh** [comment]
Emm.. i didn't notice it, It works. Thanks for your help! @szha

**Comment by szha** [comment]
@freshmanfresh no problem. It seems to be a recurring problem, so I made a PR to update the error message to display the type string instead of type codes in #7730
