### ISSUE TITLE
Predict function in gluon package?

### ISSUE THREAD

**Issue by freshmanfresh** [apache/incubator-mxnet#7731]
Is there a good way to achieve predict function when using gluon package?
I used something like output=net(data),then use np.vstack to combine all the output together.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
