### ISSUE TITLE
How to convert the data of the result of mx.symbol.Convolution to nd.array data format?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [apache/incubator-mxnet#7733]
How to convert the data of the result of mx.symbol.Convolution to nd.array data format?
Kindly suggest

**Comment by reminisce** [comment]
`mx.symbol.Convolution` indeed generates `nd.NDArray` data format. You just need to create an executor first through symbol binding and run executor's forward function.

**Comment by ChidanandKumarKS** [comment]
Can u provide small snippet code sine iam a beginner to this field

**Comment by reminisce** [comment]
@ChidanandKumarKS I encourage you to read this tutorial to understand symbolic programming in MXNet. It's helpful to understand how complicated symbolic operators such as Convolution work in MXNet. You can find many examples in tests/python/unittest/test_operator.py.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Please check http://mxnet.incubator.apache.org/tutorials/basic/symbol.html.
