### ISSUE TITLE
My jupyter notebook uses old mxnet version 0.9.5 whereas pycharm debugger uses 0.11.1...

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#7735]
Recently i deleted mxnet version 0.9.5 and upgraded to 0.11.1 version
Still my jupyter notebook points to old version0.9.5 rather than new one 0.11.1.
Kindly help

Chowkamlee

**Comment by szha** [comment]
You might have more than one copy of python and your ipython/Jupyer has old mxnet in its site packages and it wasn't upgraded. You can open a notebook, import mxnet, and then print mxnet to find where the old package is. Note down the location, find the pip command in the bin folder at the same level as the site-packages you found from last step, and explicitly use the absolute path of the pip you found for installation and upgrade.

**Comment by chowkamlee81** [comment]
Thanks got the solution as you said.. Closing the issue
