### ISSUE TITLE
Formula to calculate dimensions of output of Deconvolution filter given kernel filter size and stride.

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#7736]
Formula to calculate dimensions of output of Deconvolution filter given kernel filter size and stride 
How the stride factor is related to the upsampling factor?
Kindly suggest

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
