### ISSUE TITLE
NDArray::WaitToWrite() hangs in custom c++ operator. Bug?

### ISSUE THREAD

**Issue by x10000year** [apache/incubator-mxnet#7742]
I'm writing a custom operator in c++. And I try to construct a NDArray object from a blob. I use NDArray because it is more dynamic and easier to use than mshadow::Tensor (which makes dim and device a template argument, etc.). However, I found that a NDAarray object constructed from an output blob hangs on call to WaitToWrite(). Is this a bug?

The code is as following:

  void Forward(const OpContext &ctx,
      const std::vector<TBlob> &in_data,
      const std::vector<OpReqType> &req,
      const std::vector<TBlob> &out_data,
      const std::vector<TBlob> &aux_args) override {
    CHECK(req[0] == kWriteTo);
    NDArray x(out_data[0], out_data[0].dev_id());
    x.WaitToWrite();  // hangs here
    ...
    x.SyncCopyFromCPU(...);  // which calls WaitToWrite() inside
}

**Comment by piiswrong** [comment]
You can't use NDArray inside operators

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
