### ISSUE TITLE
MXNet 0.11.0 Release Feedback: README File

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#7750]
Copied and assembled as is from this [email thread](https://lists.apache.org/thread.html/171c0ff73e5f7539611a8024fef42968f5ffea800c354b2cdfa04ab2@%3Cgeneral.incubator.apache.org%3E) 

1. Install Instructions needed - "Agreed with Justin that there needs to be a Getting Started text file of some kind. This could be a link from the README.md to the docs/get_started directory perhaps; though .md format isn't the easiest to read (ie: link to website and over time we should consider whether a local version is needed)."
2. Also the README has a large number of links to http://mxnet.io. These should be changed.
3. R-package/ directory is empty (needs removing as confusing, or a README could be added explaining the code is not present and can be found outside of Apache).
4. The README.md also refers to rc3. It shouldn't refer to rc3 as a release, and ideally it would refer to 0.11.0 as a release (though tricky to be forward looking given that GitHub treats that as a homepage). Randomly noting that the What's New should be dated.
5. The README.md refers to the copyright being owned by Contributors. Needs updating to a license statement (with NOTICE handling the copyright side of things).

**Comment by mbaijal** [comment]
In Review

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by mbaijal** [comment]
All the points mentioned were fixed as a part of: 
1. https://github.com/apache/incubator-mxnet/pull/8051
2. https://github.com/apache/incubator-mxnet/pull/8061
