### ISSUE TITLE
MXNet 0.11.0 Release Feedback: NEWS.md and CONTRIBUTORS.md

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#7751]
As pointed out in this [email thread](https://lists.apache.org/thread.html/171c0ff73e5f7539611a8024fef42968f5ffea800c354b2cdfa04ab2@%3Cgeneral.incubator.apache.org%3E)
1. CONTRIBUTORS.md calls the project DMLC/MXNet.
2. The NEWS.md refers to 0.11.0-rc3 as the latest version. This should refer to the version being released rather than the rc3.

**Comment by yajiedesign** [comment]
look like is fixed.If there is a problem. at me.
