### ISSUE TITLE
Element wise maximum operations using mx.symbol

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#7761]
I had a feature map of dim `12*800*1280`
dimension/No of channels =12
height = 800
width =1280

I want to perform element-wise maximum operation on all the channels.
Kindly suggest the mxnet.symbol.operator and its sample example.

**Comment by szha** [comment]
Do you mean you want to find the maximum value for each channel? Suppose your feature is packed as an NDArray, with shape of `(12, 800, 1280)` (i.e. `CHW` layout), you can do
```python
mx.nd.max(data, axis=0, exclude=True)
```
This performs maximum search on all axes except 0th axis. Information on this API can be found at https://mxnet.apache.org/api/python/ndarray.html#mxnet.ndarray.max

**Comment by chowkamlee81** [comment]
I want to perform element-wise maximum among all the channels
I/P : N*H*W
O/P : H*W.
Kindly suggest using mxnet.symbol operation.pls....

**Comment by szha** [comment]
then set the exclude to be false. For symbol, just replace .nd. with .sym. and it should work

**Comment by chowkamlee81** [comment]
Thanks szha.it worked.. Closing the issue
