### ISSUE TITLE
How to implement fixed size pooling like spatial pyramid pooling?

### ISSUE THREAD

**Issue by ArsenLuca** [apache/incubator-mxnet#7766]
Fixed size pooling such as SPP is commonly used in CNN, however I found SPP doesn't exist in mxnet symbols.

**Comment by jdhao** [comment]
@ArsenLuca , To implement spp, you actually need adaptive pooling, but mxnet does not support it now. Fortunately, there is [PyTorch that support it](http://pytorch.org/docs/master/nn.html#adaptivemaxpool2d). If you can not implement it by yourself in MXNET, consider PyTorch. aha :)

**Comment by edmBernard** [comment]
Does the ROIPooling function used in Faster RCNN can't work ?
`mx.symbol.ROIPooling`

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
