### ISSUE TITLE
MKL ML results depending on number of threads

### ISSUE THREAD

**Issue by al-rigazzi** [apache/incubator-mxnet#7770]
Hello, don't know if this is documented anywhere, but I've been scratching my head for 4 days, so I'm opening a quick issue.

If you use MKL blas + MKLML it seems that the number of threads influences the results you get. As a MWE, I suggest to run alexnet and check the norm of the computed gradients for different number of threads (limiting them setting OMP_NUM_THREADS, for example). You will see that at the very first step, you already have different values. Obviously remove all sorts of randomness to get the same samples and random values for each run.

Is this known? I tested this with Resnext-50, and it seems that the more threads, the faster the convergence (in terms of accuracy vs epochs), which I find absolutely misleading.

**Comment by szha** [comment]
Would you be able to isolate where the training diverges depending on the number of threads? @ykim362 what's MKLML's plan and timeline?

**Comment by piiswrong** [comment]
What's your version?

**Comment by ykim362** [comment]
Could you also provide the versions of MKL and MKLML?

**Comment by chinakook** [comment]
MKL ML or MKL DNN is full of bug in my testing, you can just ban it and use MKL blas only.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
