### ISSUE TITLE
Error when loading JSON network definition with c++ api

### ISSUE THREAD

**Issue by Bumblebee1964** [apache/incubator-mxnet#7771]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10

Compiler:VS2015

Package used (Python/R/Scala/Julia):

MXNet version: 9.0.5

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Console output:
[12:39:43] C:\Projects\MXNet\Base\dmlc-core\include\dmlc/logging.h:300: [12:39:43] C:\Projects\MXNet\Base\nnvm\src\core\op.cc:55: Check failed: op != nullptr Operator Convolution is not registered
[12:39:43] c:\projects\mxnet\base\dmlc-core\include\dmlc\logging.h:300: [12:39:43] c:\projects\mxnet\base\cpp-package\include\mxnet-cpp\symbol.hpp:79: Check failed: MXSymbolCreateFromFile(file_name.c_str(), &(handle)) == 0 (-1 vs. 0)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
		Symbol m_symNetwork = Symbol::Load("C:\\DataSets\\alex.json");

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.  Tried to save a network created in code. Then saved to JSON. The JSON output file seems OK. ->But errors is the same.
2.  Tried to load one of the sample files from internet (Inception-BN-symbol.json. ->Same error
3.

**Comment by goodtogood** [comment]
same problem.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@nswamy please add Bug, C++ to this topic

**Comment by leleamol** [comment]
@Bumblebee1964 Can you please try with the latest MXNet version and if the issue persists, can you. please provide a minimum reproducible example? 

I have recently submitted a PR #12930 demonstrating how to load model in JSON format.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by kalyc** [comment]
Hi @Bumblebee1964 there appears to be no update on your end on this issue
I am requesting to close it at the moment, please feel free to open it if the problem persists.

@mxnet-label-bot add [suggest-closed]

**Comment by kalyc** [comment]
@mxnet-label-bot add [suggest-closed]

**Comment by Bumblebee1964** [comment]
Dear Kalyanee,

Thanks for addressing.

Currently we use the Python interface.

We will revert to the C++ api in December using the latest MxNet version. If we still encounter the same problem, we will open the issue.

Regards,

Fred

**Comment by kalyc** [comment]
Thanks for the update @Bumblebee1964 
Could you please close this issue at the moment then?
