### ISSUE TITLE
float16 has no performance improvement

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#7778]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: RHEL 7.3

Compiler: GCC 4.8.5

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.11.1

Or if installed from source: Yes

MXNet commit hash (`git rev-parse HEAD`): ef16cc28635d0c1ad8889232f7461c2d41fa61c7

If you are using python package, please provide

Python version and distribution: 2.7.5

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
no error message

## Steps to reproduce
I was training resnet50 using train_imagenet.py in mxnet/example/image-classification folder. I compiled mxnet with CUDA 9, CUDNN 7.0 and run it on four V100 GPUs. 

The command I used to run with the default Float32 is:
``python train_imagenet.py \``
    ``--network resnet \``
    ``--num-layers 50 \``
    ``--gpus 0,1,2,3 \``
    ``--num-examples 1281167 \``
   `` --num-epochs 1 \``
    ``--data-train /cm/shared/scratch/database/mxnet/ilsvrc12_train.rec \``
    ``--data-val /cm/shared/scratch/database/mxnet/ilsvrc12_val.rec \``
    ``--kv-store device``

To use Float16, I just added the option:
``"--dtype float16"``

The training speed is 1036.15 samples/sec with float32 and 1034.27 samples/sec for float16. So why there is no performance improvement at all? 

## What have you tried to solve it?
I tried nvidia branch of Caffe and got close to 2x speedup with FP16 compared to FP32. 

Regards,
Rengan

**Comment by piiswrong** [comment]
@ptrendx

**Comment by ptrendx** [comment]
V100 as in Volta? Then the speed you see is quite low even on fp32, so I would say you are limited by IO here. Default number of threads for  IO is 4 which is way to low to saturate 4 V100 - could you test with --data-nthreads N option (N should be 10+ for fp16 version at least). Also, if that does not solve the issue, could you test single GPU numbers?

**Comment by ptrendx** [comment]
Oh, you also use the default batch size which is 128 - consider increasing it. 1 V100 can train with batch sizes even over 128 with fp16.

**Comment by hfutxrg** [comment]
Hi @ptrendx, yes I am using Volta GPUs. I just tried 1 V100 and found FP16 is 47% faster than FP32. So it is effective for 1 GPU. I will try larger batch size as you suggested because this improvement is still much lower than the improvement I got in Nvidia caffe. Also I will try to use larger --data-nthreads N value for multiple GPUs. Thanks for the help!

**Comment by ptrendx** [comment]
Oh, one additional thing - set environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 2 - the default version of 1 may not choose the fastest algorithm for fp16 training.

**Comment by hfutxrg** [comment]
Thanks @ptrendx . I will try that environment variable setting. So does --data-nthreads N value also have impact for FP32 with multiple GPUs?

**Comment by ptrendx** [comment]
And lastly:
Network resnet from image classification examples is actually resnet V2 which is a little more computationally expensive than v1 that caffe uses. You may want to switch to resnet-v1 in the script you use.

**Comment by ptrendx** [comment]
It should have an impact, yes.

**Comment by ptrendx** [comment]
@hfutxrg Did it solve your problem?

**Comment by hfutxrg** [comment]
@ptrendx Yes I am able to run resnet-v1 and it does have impressive performance improvement if large --data-nthreads N is used. I also saw great speedup of FP16 compared to FP32. Thanks for the help!

**Comment by ptrendx** [comment]
@hfutxrg That's great!
@piiswrong Please close the issue.

**Comment by ptrendx** [comment]
@szha please close

**Comment by 315386775** [comment]
@hfutxrg how to use fp16 with the pre-train model.  python /image-classification/fine-tune.py

**Comment by 315386775** [comment]
@hfutxrg I run resnet-v1 but it does have impressive performance improvement if large --data-nthreads N is used. Actually. The speed is not speedup.
Environment info :  one V100. Mxnet 0.11.0
