### ISSUE TITLE
cuDNN performance

### ISSUE THREAD

**Issue by beeva-juangomez** [apache/incubator-mxnet#7790]
Hi,

I have run LeNet model with CUDA 8.0 and cuDNN enabled and later disabled. The results shows a 5-10% better performance (time) with cuDNN enabled. Is this result typical or the performance should be higher?

Thank you.

**Comment by ptrendx** [comment]
LeNet model is very small and so dominated by latencies, not by kernel performance. Try testing with a bigger network, you should generally see better performance with cuDNN.

**Comment by beeva-juangomez** [comment]
Thank you, I'm going to test with a bigger network
