### ISSUE TITLE
Enhance For DataLoad Directly from folder

### ISSUE THREAD

**Issue by jinfagang** [apache/incubator-mxnet#7804]
Hi, mxnet so far so good, especially gluon provide an elegant ever interface for building networks. But have gluon provide a DataIter class or something allows user load image directly from folder? Something like in keras which can send folder and load class and images automatically. (If such method already exist please aware me.)

**Comment by chinakook** [comment]
It's a simple functionality but sometimes complicated because of charset differences in different OS. If your filename is all English, It's all OK. However, If your filename is other Language such as Chinese, It's hard to handle. Python is also bad at that.

**Comment by jinfagang** [comment]
I don't like the rec way cause lack of flexibility. Maybe I should write myself.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
