### ISSUE TITLE
newest mxnet build failed with linalg_impl uninitialized error

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#7807]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 14.04
Compiler: 4.8.4

Package used (Python/R/Scala/Julia):

MXNet version: 0.11.1

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`): 3f742d254846fbc14dbaa459191403330425ef83

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
cclplus: all warnings begin treated as errors
make: *** [build/src/operator/tensor/la_op.o] Error
```

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
```make -j4```

only build with gpu will make this error.
![build-failed](https://user-images.githubusercontent.com/5860892/30213589-102f7c4e-94dc-11e7-8ef5-242a10ad4c60.jpeg)

**Comment by piiswrong** [comment]
What's the error? The last line is a note. Not the error

**Comment by tornadomeet** [comment]
@piiswrong  error is:  

g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -g -Werror -O3 -DNDEBUG=1 -I/home/wuwei/project/dmlc/mxnet/mshadow/ -I/home/wuwei/project/dmlc/mxnet/dmlc-core/include -fPIC -I/home/wuwei/project/dmlc/mxnet/nnvm/include -I/home/wuwei/project/dmlc/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_PROFILER=1 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMSHADOW_USE_CUDNN=1  -I/home/wuwei/project/dmlc/mxnet/cub -DMXNET_USE_NVRTC=0 -MMD -c src/executor/attach_op_execs_pass.cc -o build/src/executor/attach_op_execs_pass.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -g -Werror -O3 -DNDEBUG=1 -I/home/wuwei/project/dmlc/mxnet/mshadow/ -I/home/wuwei/project/dmlc/mxnet/dmlc-core/include -fPIC -I/home/wuwei/project/dmlc/mxnet/nnvm/include -I/home/wuwei/project/dmlc/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_PROFILER=1 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include   -fopenmp -DMSHADOW_USE_CUDNN=1  -I/home/wuwei/project/dmlc/mxnet/cub -DMXNET_USE_NVRTC=0 -MMD -c src/executor/attach_op_resource_pass.cc -o build/src/executor/attach_op_resource_pass.o
In file included from src/operator/tensor/./../linalg.h:167:0,
                 from src/operator/tensor/./la_op_inline.h:27,
                 from src/operator/tensor/la_op.cc:25:
src/operator/tensor/./../linalg_impl.h: In function ‘int linalg_gelqf_workspace_query(const mshadow::Tensor<Device, 2, DType>&, mshadow::Stream<Device>*) [with xpu = mshadow::cpu; DType = float]’:
src/operator/tensor/./../linalg_impl.h:843:37: error: ‘work’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   int ws_size(static_cast<int>(work)); \
                                     ^
src/operator/tensor/./../linalg_impl.h:838:9: note: ‘work’ was declared here
   DType work; \
         ^
src/operator/tensor/./../linalg_impl.h:852:1: note: in expansion of macro ‘LINALG_CPU_GELQF_WORKSPACE_QUERY’
 LINALG_CPU_GELQF_WORKSPACE_QUERY(s, float)
 ^
src/operator/tensor/./../linalg_impl.h: In function ‘int linalg_gelqf_workspace_query(const mshadow::Tensor<Device, 2, DType>&, mshadow::Stream<Device>*) [with xpu = mshadow::cpu; DType = double]’:
**src/operator/tensor/./../linalg_impl.h:843:37: error: ‘work’ may be used uninitialized in this function [-Werror=maybe-uninitialized]**
   int ws_size(static_cast<int>(work)); \
                                     ^
src/operator/tensor/./../linalg_impl.h:838:9: note: ‘work’ was declared here
   DType work; \
         ^
src/operator/tensor/./../linalg_impl.h:853:1: note: in expansion of macro ‘LINALG_CPU_GELQF_WORKSPACE_QUERY’
 LINALG_CPU_GELQF_WORKSPACE_QUERY(d, double)

**Comment by tornadomeet** [comment]
@piiswrong  try to fix this as pull request: https://github.com/apache/incubator-mxnet/pull/7819
