### ISSUE TITLE
NHWC not supported for convolution, but the docs say that it is.

### ISSUE THREAD

**Issue by danielwaterworth** [apache/incubator-mxnet#7811]
The docs say that NHWC is supported for convolution, but it's not.

This is the error I get:
```
mxnet.base.MXNetError: [11:54:54] src/operator/./convolution-inl.h:116: Check failed: param_.layout.value() == mshadow::kNCW || param_.layout.value() == mshadow::kNCHW || param_.layout.value() == mshadow::kNCDHW Only support NCW, NCHW and NCDHW layout
```

[Here](https://mxnet.incubator.apache.org/api/python/ndarray.html#mxnet.ndarray.Convolution) are the docs. I'm using mxnet 0.11.0.

**Comment by piiswrong** [comment]
It's only supported on GPU

**Comment by danielwaterworth** [comment]
Could you update the docs then

**Comment by chinakook** [comment]
NHWC is not efficient for image data, use NCHW instead.

**Comment by danielwaterworth** [comment]
@chinakook, it would be useful to state that in the docs too.

**Comment by eric-haibin-lin** [comment]
[This document](https://s3.amazonaws.com/mxnetdoc/API+Doc+Contributions%281%29.pdf) shows you how to contribute to API docs in MXNet. Anyone is welcome to post a patch for this

**Comment by ThomasDelteil** [comment]
@yzhliu  the docs have been updated, can you close please? thanks
