### ISSUE TITLE
can anyone give clue how to install latest prebuilt package , where is setupenv.cmd? thanks

### ISSUE THREAD

**Issue by DomLi** [apache/incubator-mxnet#7823]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by DomLi** [comment]
can anyone give clue how to install latest prebuilt package , where is setupenv.cmd? thanks

**Comment by szha** [comment]
http://mxnet.apache.org/get_started/install.html

**Comment by yajiedesign** [comment]
https://github.com/yajiedesign/mxnet/releases/download/weekly_binary_build/prebuildbase_win10_x64_vc14.7z

**Comment by DomLi** [comment]
thx to all response, will try it.

**Comment by DomLi** [comment]
Hi, HU,

thanks, by the way, I am using win7x64 , is this the right one to use?

Best regards,

**Comment by yajiedesign** [comment]
win7 64 is ok.

**Comment by DomLi** [comment]
thx lot!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by bhavinthaker** [comment]
Please label: Installation, Windows. 

This issue seems to be resolved and so I would suggest closing it.
