### ISSUE TITLE
How to partition a computing graph among multiple machines？

### ISSUE THREAD

**Issue by LukcyqXD** [apache/incubator-mxnet#7824]
Mxnet is a great DL framework! When i read the source code ,I am confused about that whether the system partition the computational graph ? As for multiple machines environment,  does a single machine  get the complete model ?

**Comment by eric-haibin-lin** [comment]
MXNet supports partitionning the graph between multiple devices but probably not multiple machines... @mli @tqchen

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
