### ISSUE TITLE
This code may cause some error

### ISSUE THREAD

**Issue by TimonLiu** [apache/incubator-mxnet#7841]
https://github.com/apache/incubator-mxnet/blob/e25074a469b45f2cbde68e2a0c8963daea93b66b/python/mxnet/image/detection.py#L246
I think line#246 should be something like this:
`coverages = self._calculate_areas(intersects) / object_areas[valid_objects]`

Because if `valid_objects<len(object_areas)` , an error will occur:
`File "/usr/local/lib/python2.7/dist-packages/mxnet/image/detection.py", line 246, in _check_satisfy_constraints
    coverages = self._calculate_areas(intersects) / object_areas
ValueError: operands could not be broadcast together with shapes`

**Comment by zhreshold** [comment]
should be
```
coverages = self._calculate_areas(intersects) / object_areas[valid_objects]
```
This seems to be only reproducible when min_scale=0 when the area of a crop region can be smaller than 2 pixels?
