### ISSUE TITLE
Where can I find detailed documents about Executor class!

### ISSUE THREAD

**Issue by v2up** [apache/incubator-mxnet#7842]

**Comment by szha** [comment]
The api docs are currently available alongside the implementation. https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/executor.py

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudh2290** [comment]
@szha this issue has been idle for a while. Can this be closed ?
