### ISSUE TITLE
rcnn fix_param_list prefix checking

### ISSUE THREAD

**Issue by Godricly** [apache/incubator-mxnet#7845]
The code logic here is confusing. It is checking whether the prefix is a part of name other than the prefix of it. @precedenceguo 

```python
        fixed_param_names = list()
        if fixed_param_prefix is not None:
            for name in self._symbol.list_arguments():
                for prefix in self._fixed_param_prefix:
                    if prefix in name:
fixed_param_names.append(name)
```

[link](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/core/module.py#L60-L65)

**Comment by precedenceguo** [comment]
Yes, indeed. It is probably better to require fixed_param_names as a parameter for MutableModule instead, while moving this logic outside and log the fixed params.

**Comment by Godricly** [comment]
It's already a parameter for MutableModule. But the matching logic is wield here. 
If I add 'gamma' or 'beta' in the fixed_param_names. it will fix all gamma and beta, even the one I defined. Maybe this is not expected before.
