### ISSUE TITLE
__shfl_down is undefined. Is the end of CUDA 2.1 support?

### ISSUE THREAD

**Issue by juselec** [apache/incubator-mxnet#7848]
Compiling mxnet either on Windows or linux throws the error **identifier __shfl_down is undefined** when compiling the stable 0.11.0 branch. If I compile the master branch (until commit e25074a4), **identifier __shfl_xor is undefined_ error** is also thrown. 

I have read in issue #4886 that this error is thrown because the lack of support of fermi GPU's, with CUDA capability 2.1. Is this the end of the support? Or just a temporary issue?

Thanks a lot.

## Environment info
**Operating System:**

Windows 10 x64.
Archlinux (Kernel 4.12.12).

Intel HD graphics 4000 + Nvidia GeForce 710m (Nvidia Optimus configuration).

**Compiler:**

CUDA 8.0.61
Visual Studio 2015 (on Windows).
G++ version 5 (on linux, as CUDA 8 is not compatible with gcc 6+).

## Error Message:

Compiling master branch.
> Error		identifier "__shfl_down" is undefined	mxnet	c:\software\mxnet\src\operator\depthwise_convolution_tf.cuh	44	
Error		identifier "__shfl_xor" is undefined	mxnet	c:\software\mxnet\src\operator\depthwise_convolution_tf.cuh	39

Compiling 0.11.0 stable branch:
>Error		identifier "__shfl_down" is undefined	mxnet	c:\software\mxnet\src\operator\depthwise_convolution_tf.cuh	479	
Error		identifier "__shfl_down" is undefined	mxnet	c:\software\mxnet\src\operator\depthwise_convolution_tf.cuh	507

Similar error on Linux.

## Steps to reproduce
1. Clone stable 0.11 branch or master branch.
2. Compile with a fermi gpu, CUDA 2.1.

## What have you tried to solve it?
1. Revert to previous commits, problem persists.

## config.mk file.
These are the lines I modified in the config.mk file. They are right at the end of the file. Similar configuration in Windows with cmake.

USE_CUDA=1
USE_CUDA_PATH=/opt/cuda
USE_CUDNN=0
USE_BLAS=blas
USE_OPENCV=0
USE_OPENCV=0

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by cjolivier01** [comment]
Redirect to: https://github.com/apache/incubator-mxnet/issues/9632
