### ISSUE TITLE
Initial parameter in HybridBlock.

### ISSUE THREAD

**Issue by danache** [apache/incubator-mxnet#7858]
Hi,I am trying build a net using HybridBlock, but I got trouble in initial parameters.
My codes are as follows:
```
class AttentionPartsCRF(gluon.HybridBlock):
    def __init__(self,num, lrnSize, iterSize, usepart, **kwargs):
        super(AttentionPartsCRF, self).__init__(**kwargs)
        with self.name_scope():
            self.att = AttentionIter(lrnSize=self.lrnSize,iterSize=self.iterSize)
            self.att2 = []
            self.conv = []
            for i in range(num):
                self.att2.append(AttentionIter(lrnSize=self.lrnSize,iterSize=self.iterSize))
                self.conv.append(gluon.nn.Conv2D(1,kernel_size=1,strides=1,padding=0))
```
where AttentionIter is an another sub module I build.
I use a list to save the net I build, but When I initial the  AttentionPartsCRF net.I found that I didn't initial the net in the list.
So how can I solve the problem ?Because I don't know the value num is.So I can't build the net one by one like this:
```
self.AttentionIter1 = AttentionIter(lrnSize=self.lrnSize,iterSize=self.iterSize)
self.conv1 = gluon.nn.Conv2D(1,kernel_size=1,strides=1,padding=0)
```

**Comment by szha** [comment]
How do you intend to use those two lists?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by cjolivier01** [comment]
Pending response from asker for some time.  Assuming this issue can be closed.
Questions are answered faster on: https://discuss.mxnet.io/
Please reopen if necessary.
