### ISSUE TITLE
mx.nd.Custom bug

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#7860]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. use custom sigmoid op in "incubator-mxnet\docs\tutorials\gluon\customop.md"
2. running "a = mx.nd.array([1,2,3,4])
    mx.nd.Custom(data=a, op_type='sigmoid')" would be dead.
3. 

## What have you tried to solve it?

"mx.nd.Custom(a, op_type='sigmoid')" is OK.

**Comment by Soonhwan-Kwon** [comment]
There is no usage or example that using data as argument in mx.nd.Custom or mx.nd.array. Maybe you may confused with usage of mx.sym.*.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by mbaijal** [comment]
@chinakook Were you able to solve the issue?

**Comment by mbaijal** [comment]
Please add the label 'Pending Requester Info' and 'Operator' and remove the label 'Needs Triage'

**Comment by chinakook** [comment]
@mbaijal Yes, It's solved but not smart.

**Comment by sandeep-krishnamurthy** [comment]
Resolving. Please reopen if issue still persists.
