### ISSUE TITLE
confused about update on kvstrore in /gluon/trainer.step()

### ISSUE THREAD

**Issue by meanmee** [apache/incubator-mxnet#7861]
if self._kvstore:
                self._kvstore.push(i, param.list_grad(), priority=-i)
                if self._update_on_kvstore:
                    self._kvstore.pull(i, param.list_data(), priority=-i)
                    continue
                else:
                    self._kvstore.pull(i, param.list_grad(), priority=-i)

---------------------------------------------------------------------------
if the kvstore is in 'device' mode
is it just use the all reduced gradients to replaece the weights?

**Comment by eric-haibin-lin** [comment]
`kv.push` will apply an updater/optimizer with aggregated grads (e.g. SGD)
https://mxnet.incubator.apache.org/api/python/kvstore.html?highlight=kvstore#push-aggregation-and-updater

**Comment by meanmee** [comment]
I see， Thank U very much! I'll close the issue.
