### ISSUE TITLE
Website redesign proposal

### ISSUE THREAD

**Issue by sebouh** [apache/incubator-mxnet#7862]
A redesign proposal is live on [the /master page](https://mxnet.incubator.apache.org/versions/master/ ). Please share any bugs or feature suggestion. We will add a [Discourse](https://github.com/discourse/discourse) forum in the next couple weeks.

**Comment by madjam** [comment]
On home page:
- *is a flexible and efficient library for deep learning* - don't think we need "is" at the start of this phrase.
- Consider removing or shortening the text: *Building a high-performance deep learning library requires many system-level design decisions. In this design note, we share the rationale for the specific choices made when designing MXNet. We imagine that these insights may be useful to both deep learning practioners and builders of other deep learning systems.*
- Typo in the Examples box (exmaples)
- White boxes (news) does not mix well with the rest of the color scheme.

**Comment by lupesko** [comment]
- 0.11RC3 should be removed from the versions list (we already released 0.11

**Comment by hen** [comment]
Noting that a lot of the media content is being pulled from raw.githubusercontent.com/dmlc

Let's stop using dmlc's GitHub please.

**Comment by hen** [comment]
Github should be renamed imo. "Source" would be better, and possibly should go to a page that describes the availability of source code and then links to GitHub.

The examples link goes to dmlc (which is then redirected).  Generally doing a grep for 'dmlc' and removing most if not all of them is probably a good thing.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy I think we can close this issue now. 
Redesigning the website was done.
