### ISSUE TITLE
Why library size so large

### ISSUE THREAD

**Issue by feiyuvl** [apache/incubator-mxnet#7871]
I found the libmxnet.so is still very large (about 80MB) after I modified the Makefile options. Then I checked the object files in build dir and got this.
![default](https://user-images.githubusercontent.com/13388702/30355775-fc7d090c-9867-11e7-94c5-539d90b2e54f.JPG)

The operator dir occupies the most part of the total build size.  And some *_gpu.o generated by nvcc is much larger
![Uploading gpu.JPG…]()

**Comment by chinakook** [comment]
Because you build all nvidia sm types such as sm_52

**Comment by feiyuvl** [comment]
@chinakook No, I modify the make.config, only keep sm_61. Original libmxnet.so is about 500M. What's your library size?

**Comment by chinakook** [comment]
151MB

**Comment by feiyuvl** [comment]
@piiswrong Any advices on reducing the gpu obj size?

**Comment by szha** [comment]
Dynamic links for dependencies such as cudnn tend to reduce the size. What's the problem with the library size? Is there a specific use case that requires small library size for you?

**Comment by feiyuvl** [comment]
We are deploying mxnet for inference, and need library size as small as possible.

**Comment by szha** [comment]
Is it on special hardware where disk is very limited?

**Comment by feiyuvl** [comment]
No, just feel it is too large. A single obj file generated by some op is above 10M which is unreasonable. Maybe the using of template in mshadow causes this.

**Comment by szha** [comment]
Unrolled loops with instantiation of many types tend to do that... Closing for now since there doesn't seem to be actionable item here. Feel free to reopen if this causes issue.

**Comment by tada123** [comment]
I get 240MiB libmxnet.so size (built with CUDA disabled), which is really big. Is there any CMake definition/option to reduce it at least under 100MiB (got 217MiB after stripping debugging symbols, which is still very large)?

Could you please reopen the issue?
