### ISSUE TITLE
Where is the mxnet.ndarray.RNN function's implementation code?

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#7872]
I want to see below function's python code. Does anyone know where is it?
mxnet.ndarray.RNN(data=None, parameters=None, state=None, state_cell=None, state_size=_Null, num_layers=_Null, bidirectional=_Null, mode=_Null, p=_Null, state_outputs=_Null, out=None, name=None, **kwargs)

The output of this function is NDArray or list of NDArrays, which notes on mxnet's official web set. I want to know which form the list of NDArrays constructed when the mode is 'lstm'. Is it in the form of 'h, [h,c]'?

**Comment by danache** [comment]
I think this [link ](https://github.com/apache/incubator-mxnet/blob/master/example/gluon/word_language_model/model.py#L48-L52)may help you .
You may also want to  check the c++ implementation:
[https://github.com/apache/incubator-mxnet/blob/e61fa7c86db06ac960e76bbe577480d446084502/src/operator/rnn-inl.h](https://github.com/apache/incubator-mxnet/blob/e61fa7c86db06ac960e76bbe577480d446084502/src/operator/rnn-inl.h )

**Comment by szha** [comment]
@liuzhi136 that API is built for directly invoking cudnn implementation. There are other higher-level APIs that help you deal with data layout, etc.. You can find the example [here](https://github.com/apache/incubator-mxnet/blob/master/example/gluon/word_language_model/model.py) for the gluon RNN API.

**Comment by szha** [comment]
And the API doc can be found here: https://mxnet.incubator.apache.org/versions/master/api/python/gluon/gluon.html#mxnet.gluon.rnn.LSTM

**Comment by liuzhi136** [comment]
@szha @danache Thanks both of you. @szha this page of https://mxnet.incubator.apache.org/versions/master/api/python/gluon/gluon.html#mxnet.gluon.rnn.LSTM just give some explanations for this function. How could I get each hidden states of the final lstm layer across time steps from gluon? Cause all of these model just return the last hidden state of the final layer and outputs of each time step.

**Comment by szha** [comment]
@liuzhi136 do you mean cell state c or hidden state h?

**Comment by liuzhi136** [comment]
@szha the hidden state h!

**Comment by szha** [comment]
@liuzhi136 the layer in the doc outputs all the hidden states in the layout of (T, N, C)

**Comment by liuzhi136** [comment]
@szha Yes, it is.
 emb = self.drop(self.encoder(inputs))
 output, hidden = self.rnn(emb, hidden)
 output = self.drop(output)
 decoded = self.decoder(output.reshape((-1, self.num_hidden)))
the output stands for the rnn's out than hidden states h. I only want to retrieve each h of the time step. Do you have any idea?

**Comment by liuzhi136** [comment]
@szha the output contains seq_length items, while the hidden h just a (bath_size, num_hidden) matrix. I want to get seq_length hs.

**Comment by szha** [comment]
@liuzhi136 you can slice it. refer to the doc

**Comment by liuzhi136** [comment]
uh, I do not understand that. Do you mean slicing the output?

**Comment by szha** [comment]
yes

**Comment by szha** [comment]
Feel free to reopen if you have more questions on this topic.

**Comment by douglas125** [comment]
Hi

I find the same difficulty.

For the GRU cell, for example, the documentation says that:

data: input tensor with shape (sequence_length, batch_size, input_size)
out: output tensor with shape (sequence_length, batch_size, num_hidden)
out_states: output recurrent state tensor with shape (num_layers, batch_size, num_hidden)

Is there any way to get access to ALL (sequence_length) hidden states? These are the states which need to be weighted on using the AttentionCell before feeding as a hidden state to the decoder RNN, correct?

I am trying to use the Attention cell described here: https://gluon-nlp.mxnet.io/api/model.html#gluonnlp.model.MLPAttentionCell
using the source code in mxnet 1.2

It seems feasible to just implement all the sequence using GRUCells but I feel that could be quite inefficient.

Thanks!
