### ISSUE TITLE
The Meaning of parameters of mxnet.gluon.Embedding function

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#7894]
The doc of mxnet.gloun.Embedding function have the following states:
Input shape:
    2D tensor with shape: (N, M).
Output shape:
    3D tensor with shape: (N, M, output_dim). 
So, What's the meaning of N, M? Does it means the shape of inputs? say (batch_size, vocab_size).
And another one is what's the implementation strategy of this function? Does it just a one or two layer neural network?

**Comment by liuzhi136** [comment]
@szha Do you know these parameters' meaning?

**Comment by szha** [comment]
sorry for the delay. @liuzhi136 
they don't have meaning and can be arbitrary numbers

**Comment by liuzhi136** [comment]
But these two parameter below the Input shape: I'm thinking if it stands for the (num_word, vocab_size), that is it stands for the number of words and vocabulary size.

**Comment by szha** [comment]
The doc is trying to tell you that the input and output sizes are consistent in those two dimensions. What meanings should they have is up to you.

**Comment by liuzhi136** [comment]
Ok, Thanks.
