### ISSUE TITLE
What will happen when executing  Model.update() and Model.forward() at same time in two threads?

### ISSUE THREAD

**Issue by ChenYingfeng** [apache/incubator-mxnet#7897]
I try to implement a distributed RL algorithm, so I use two threads in my learner program: 
**Thread one** is response to receive a sample from remote machine and then use Model.forward() to return a action immediately.
**Thread two** is response to do batch training using the received samples.

Now I found under this  case, the Thread one is often blocked at certain time, so I wonder what happens inside the mxnet? and how could I solve this problem?

**Comment by reminisce** [comment]
You cannot multi-thread python code in MXNet. Those functions have to be called in sequence so that the backend engine can schedule operations in the right order. The purpose of execution engine in backend is to eliminate the overhead of writing multi-threaded code in frontend.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
