### ISSUE TITLE
Need help: numpy array to mxnet ndarray is too slow.

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#7899]
numpy array to mxnet ndarray is too slow.

```
start = time.time()
data_ = [mx.nd.array(img_data)]
label_ = [mx.nd.array(label_data)]
end = time.time()
print 't3: {}'.format(end-start)
```
t3: 0.293313980103. sometimes i get 1.5s. Need help, thanks! It slows down my training!

**Comment by madjam** [comment]
How big is `img_data` and `label_data`?
FYI: this involves allocating memory and copying contents of numpy array into the allocated memory.
How is this step slowing down your training? how often are you doing this copy?

**Comment by KeyKy** [comment]
image_data is (128, 3, 224, 224) label_data is (128,)
Because it needs to load batch of data before doing net forward.

**Comment by Joke09** [comment]
For inference, I have the same problem. The client send jpg to server, then the server use cv2 to do resize. When put the image data into the mx.nd.array, it's very slow. And the Utilization of GPU is low too. How to solve it? Thank you!

**Comment by summer-via** [comment]
I have the same problem, why is the nd.array() function  so slow?

**Comment by leezu** [comment]
You can use the `mx.nd.from_numpy(ndarray, zero_copy=True)` if you don't mind that the numpy array is invalid afterwards.
