### ISSUE TITLE
Segmentation fault for gluon.ndarray.random_*

### ISSUE THREAD

**Issue by hashbangCoder** [apache/incubator-mxnet#7901]
## Environment info
Operating System:
Ubuntu 16.04

Compiler:
[GCC 5.4.0 20160609] on linux

Package used (Python/R/Scala/Julia):
Python

MXNet version:
v0.11

Python version and distribution:
3.5.2

## Error Message:
Please paste the full error message, including stack trace.
Segmentation fault (core dumped)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```
import mxnet as mx
mx.gluon.ndarray.random_uniform(2,10)
```
This also likely works for any `random_*` without mandatory args (tested with uniform and exponential). Don't think this is intended behavior.

**Comment by szha** [comment]
mx.gluon.ndarray.random_uniform((2,10))

**Comment by hashbangCoder** [comment]
`mxnet.gluon.ndarray.random_uniform((2,10))` gives :

```mxnet.base.MXNetError: Invalid Parameter format for low expect float but value='(2, 10)', in operator random_uniform(name="", low="(2, 10)")```

But, my issue was whether the intended output for not providing shape info was a seg fault?

**Comment by szha** [comment]
I share the same reaction to this... This is to be fixed soon by @reminisce

**Comment by reminisce** [comment]
This https://github.com/apache/incubator-mxnet/pull/7874 is supposed to fix the seg fault problem.

**Comment by szha** [comment]
Random refactor has been merged thanks to @reminisce . This issue should be fixed now on the master branch. Let us know if it still persists.
