### ISSUE TITLE
Do I need to change grad_req when sharing weights?

### ISSUE THREAD

**Issue by liyi14** [apache/incubator-mxnet#7912]
Hi, I was building a conv layer sharing weights with another one, using the  #557. Since the default grad_req is 'write' and I need to update the weights using the gradient from both of the two conv layer, do I need to change it to 'add'? Will it have some affect on other layers or say can I limit the 'add' req only only the shared weights?
Thanks.

**Comment by piiswrong** [comment]
no need to use add. it's automatic within one executor

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Answered above.
