### ISSUE TITLE
what are the dependencies between each modules

### ISSUE THREAD

**Issue by mxmxlwlw** [apache/incubator-mxnet#7913]
Hi,
    I like your design of mxnet very much, but I still can't get the idea of dependencies between each modules. I'd be really appreciated if you give me some hints.
    Like what is the dependency between executor, engine, kvstore, ndarray, operator, storage, nnvm.
    I've read your code for three weeks, but still can't grape the whole ideas of your architecture. I just know how they may do some specific tasks.

**Comment by szha** [comment]
The best starting point that gives larger picture can be found in this doc: https://mxnet.incubator.apache.org/versions/master/architecture/overview.html

**Comment by mxmxlwlw** [comment]
yeah, I've seen it several times... However, it doesn't give me more details. For example, I still don't know how to use engine to run operators and something like that.

**Comment by formath** [comment]
Functionality is clear between modules but api is not. Some modules may use inner variables or implicit functions in the other modules.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
Hi @mxmxlwlw , we apologize for the late reply. As the issue is more related to a Question, please submit on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
