### ISSUE TITLE
SequenceLast of LSTM throws error

### ISSUE THREAD

**Issue by SumNeuron** [apache/incubator-mxnet#7917]
After using a LSTM, one may just want the last layer.

```
lstm = mx.gluon.rnn.LSTM(100,3)
mx.sym.SequenceLast(lstm)
```

throws an error.
How to get around this?

**Comment by szha** [comment]
LSTM layer already only returns the output of the last layer for all time steps. Did you mean you want the last time step?

**Comment by SumNeuron** [comment]
Yes

**Comment by szha** [comment]
`lstm` is declared as a gluon RNN layer while mx.sym and mx.nd operates on symbol and ndarray. You can define the network as a block and use sym/ndarray functions in the `forward()`. See details at http://gluon.mxnet.io/chapter03_deep-neural-networks/plumbing.html

**Comment by SumNeuron** [comment]
I don't see how that answers my question...

Also are you saying I can't combine the two (gluon and sym)

**Comment by szha** [comment]
The above post shows how to combine the two

**Comment by SumNeuron** [comment]
Perhaps you are seeing something that I am not.
This shows how to define blocks utilizing gluon which is the newer version of symbol. 
It doesnt explain how to grab the last time step of LSTM.
Nor does it provide an example of merging sym and gluon

**Comment by ZiyueHuang** [comment]
More specifically, how to combine the two is in section `Composing-networks-with-gluon.Block` as @szha said. http://gluon.mxnet.io/chapter07_distributed-learning/hybridize.html should be helpful for you too.

**Comment by szha** [comment]
@SumNeuron feel free to reopen if the question is still not resolved.
