### ISSUE TITLE
Support a parameter for maximum memory usage

### ISSUE THREAD

**Issue by maximsch2** [apache/incubator-mxnet#792]
I'm running into issues with creating layers that are too big and running out of memory, causing my entire PC to slow to a halt for several minutes before the process is killed. Would it make sense to support an optional parameter that will specify the maximum amount of memory all NDArrays are allowed to take? That way the program will fail earlier without involving OOM killer.

**Comment by piiswrong** [comment]
This feature should be easy to add as an environment variable. Just build a huge network, make it fail for oom. and look that part of code where it failed. add something there should fix it.

**Comment by mli** [comment]
we are considering to allow to set a gpu memory usage limit, then the system will automatically optimize the memory usage (e.g. transfer data to memory if out-of-memory)

**Comment by dtmoodie** [comment]
Any progress on this?
