### ISSUE TITLE
[BUG] elewise_binary_op.cc:: add_alias(" ?") ? in ["_sub", "_mul", "_div"]

### ISSUE THREAD

**Issue by saicoco** [apache/incubator-mxnet#7922]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 15.10
Compiler:
gcc 4.9.x
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.11.1
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
e81a3a88abaa2c4847602dfb2864e05adc5a5f56

If you are using python package, please provide

Python version and distribution:
python2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
It raises error when ops such as `_sub`, `_mul`, `_div` call  `.add_alias()`. 
```
dmlc-core/include/dmlc/registry.h:66: Check failed: e == fmap_.at(alias) (0x24622b0 vs. 0x232b020) Trying to register alias _mul for key elemwise_mul but _mul is already taken

Trying to register alias _div for key elemwise_div but _div is already taken
```
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Compile from source
2. `python setup.py install`
3. `import mxnet`

## What have you tried to solve it?
After I delete them in `elemwise_binary_op_basic.cc`, it works well.
1. delete `.add_alias("_sub")`
2. delete `.add_alias("_mul")`
3. delete `.add_alias("_div")`

**Comment by piiswrong** [comment]
This will be fixed soon.
