### ISSUE TITLE
Cannot reproduce the results of faster-rcnn

### ISSUE THREAD

**Issue by jonbakerfish** [apache/incubator-mxnet#7928]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Debian GNU/Linux 8 (jessie)

Compiler: gcc & g++ (4.9.2) 

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.11.1

Or if installed from source: 

MXNet commit hash (`git rev-parse HEAD`): 2372518e22ad329b4a6a61486144760350171a80

If you are using python package, please provide

Python version and distribution: 2.7 / anaconda

## Error Message:
Cannot reproduce the mAPs of faster-rcnn with resnet101+voc2017+voc2012. 
The mAP I got is ~0.69 which is far less than the claimed 0.79.

If I use the pre-trained model from `https://github.com/precedenceguo/mx-rcnn`, the mAPs is correct. Please also see [this issue](https://github.com/precedenceguo/mx-rcnn/issues/72).

## Minimum reproducible example
in the rcnn folder, `script/resnet_voc0712.sh 0`

**Comment by solin319** [comment]
I got mAP 0.69 ,too.
Why all the gamma and beta were fixed in config? 
Why  "use_global_stats" in "symbol_resnet.py" was always true in train and test?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by rahul003** [comment]
@cjolivier01  Could you please label this with question, performance

**Comment by stu1130** [comment]
@jonbakerfish @solin319 confirmed that the example still works. got mean AP= 0.70, 0.74 and 0.78 on vgg voc2007, vgg voc2007+2012, resnet voc2007+2012
