### ISSUE TITLE
Has anyone a guide for installing MxNet with Python on Windows 10 / VS2017 toolset (including Anaconda2)?

### ISSUE THREAD

**Issue by Bumblebee1964** [apache/incubator-mxnet#7945]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10

Compiler: VS2017

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.11

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: Python 2.7 / VS2017-Anaconda2-x64 environment

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

1. In Install manual, the link to pre-built binary is wrong (found the prebuilt binary on the branch of yajiedesign   https://github.com/yajiedesign/mxnet/releases/tag/20170902 )

2. No idea how to install the package interface from VS2017 python toolset:
         sudo python setup.py install
And I guess sudo is not available on Windows (should use elevation?).

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by chinakook** [comment]
Use the yajiedesign's version is the simplest.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
