### ISSUE TITLE
Dropout layer crashes jupyter kernel

### ISSUE THREAD

**Issue by zjost** [apache/incubator-mxnet#7960]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Deep Learning AMI for Amazon Linux

Compiler:

Package used (Python/R/Scala/Julia):  Python
MXNet version: 0.10.0

Python version and distribution:  3.4.3

## Error Message:
Please paste the full error message, including stack trace.
Jupyter Notebook Kernel crash
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

You can see code in [this](https://gist.github.com/zjost/4e10b2c7e4e31c23d93ad76f3c23c401) gist

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.  Different architectures (CNN, fully connected)
2. Moving to different places within the architecture
3.

**Comment by szha** [comment]
Please paste the full error message, including stack trace.

**Comment by zjost** [comment]
I don't get a stack trace, the Jupyter notebook kernel crashes.  It says "The kernel appears to have died. It will restart automatically."

**Comment by szha** [comment]
I noticed that the version you're using is 0.10. Do you mind getting onto 0.11 and give it a try?

**Comment by szha** [comment]
Hi @zjost. Sorry for the late reply. The best way to move forward is to find and patch up the problem. There's a chance that this is a known bug and has been patched, thus the suggestion on upgrading.

Could you run the following script on your machine to collect information for the environment you're using? https://gist.github.com/zhreshold/f4defab409cc0e6f6a0e75237f73ca99

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by nswamy** [comment]
I am closing this issue for now. @zjost please open a new issue if you still have a problem on the latest version of MXNet
