### ISSUE TITLE
fixed_param in module

### ISSUE THREAD

**Issue by Godricly** [apache/incubator-mxnet#7961]
Hi,

The current fixed_param is only compatible with params fixed at early stage. For example. fixing A here.
```
input -> A -> B
```
But if I have another network like following one. The fixed_param is not working as I want.
Here I want to train C and D while fixing A and B. So I will need the gradient from , which is blocked if I use fix param.
```
input -> A ----------------> B
           |---->C|      |-> D
```

**Comment by kevinthesun** [comment]
You can do forward and backward on A and B but don't update their parameters. In this way you will still get head gradient of A and B but keep their parameters unchanged.

**Comment by ZiyueHuang** [comment]
Seems you can set lr_mult = 0 and wd = 0 for freezing the params and getting the gradients.

**Comment by Godricly** [comment]
Exactly What I did now. I hijacked kvstore and set those gradient to zero when updating.
