### ISSUE TITLE
Perl AI::MXNet

### ISSUE THREAD

**Issue by xurc** [apache/incubator-mxnet#7965]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
CentOS 7
3.10.0-693.2.2.el7.x86_64 #1 SMP

Compiler:
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
perl 5.16.3

Package used (Python/R/Scala/Julia):
mxnet/perl-package/AI-MXNetCAPI

MXNet version:

Or if installed from source:
git --branch 0.11.0

MXNet commit hash (`git rev-parse HEAD`):
a5edbf94094581ee27157eae4f2113115a3994e7

## Error Message:
Please paste the full error message, including stack trace.

"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MXNetCAPI.bs blib/arch/auto/AI/MXNetCAPI/MXNetCAPI.bs 644
gcc -c  -I../../include/mxnet -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.0102\" -DXS_VERSION=\"1.0102\" -fPIC "-I/usr/lib64/perl5/CORE"   mxnet_wrap.cxx
mxnet_wrap.cxx: In function ‘void _wrap_NDArrayCreate(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:4194:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_NDArrayCreateEx(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:4299:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_NDArraySave(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:4502:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:4530:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx: In function ‘void _wrap_NDArrayLoad(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:4612:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx:4629:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg4 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_NDArrayReshape(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:4994:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_NDArrayGetShape(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5070:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_ListFunctions(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5422:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg1 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_FuncGetInfo(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5533:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (i = 0; i < *arg4 ; i++) {
                            ^
mxnet_wrap.cxx: In function ‘void _wrap_FuncInvoke(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5676:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:5702:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:5727:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_FuncInvokeEx(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5809:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:5835:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:5860:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_ImperativeInvoke(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:5998:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6026:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6085:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) == -1)
                                       ^
mxnet_wrap.cxx:6083:12: warning: unused variable ‘svs’ [-Wunused-variable]
       SV **svs;
            ^
mxnet_wrap.cxx:6105:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) > -1)
                                       ^
mxnet_wrap.cxx:6123:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) > -1)
                                       ^
mxnet_wrap.cxx: In function ‘void _wrap_AutogradMarkVariables(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6213:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6240:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6265:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_AutogradComputeGradient(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6340:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_AutogradBackward(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6407:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6435:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_CreateCachedOp(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6489:20: warning: unused variable ‘temp20’ [-Wunused-variable]
     CachedOpHandle temp20 ;
                    ^
mxnet_wrap.cxx: In function ‘void _wrap_InvokeCachedOp(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6594:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6622:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:6645:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) == -1)
                                       ^
mxnet_wrap.cxx:6643:12: warning: unused variable ‘svs’ [-Wunused-variable]
       SV **svs;
            ^
mxnet_wrap.cxx:6665:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) > -1)
                                       ^
mxnet_wrap.cxx:6678:39: error: ‘av_top_index’ was not declared in this scope
       if(av_top_index((AV*)SvRV(ST(3))) > -1)
                                       ^
mxnet_wrap.cxx: In function ‘void _wrap_ListAllOpNames(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6714:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg1 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListAtomicSymbolCreators(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6758:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg1 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolGetAtomicSymbolInfo(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:6872:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (i = 0; i < *arg4 ; i++) {
                            ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolCreateGroup(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7063:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListAttr(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7588:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2*2 ; i++) {
                               ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListAttrShallow(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7642:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2*2 ; i++) {
                               ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListArguments(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7696:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListOutputs(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7750:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolListAuxiliaryStates(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:7937:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolCompose(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8004:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:8029:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolGrad(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8115:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolInferShape(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8237:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:8261:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:8285:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:8308:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg6 ; i++)
                          ^
mxnet_wrap.cxx:8330:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg9 ; i++)
                          ^
mxnet_wrap.cxx:8352:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg12 ; i++)
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolInferShapePartial(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8487:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:8511:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:8535:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:8558:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg6 ; i++)
                          ^
mxnet_wrap.cxx:8580:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg9 ; i++)
                          ^
mxnet_wrap.cxx:8602:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg12 ; i++)
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_SymbolInferType(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8727:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:8751:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:8774:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg5 ; i++)
                          ^
mxnet_wrap.cxx:8789:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg7 ; i++)
                          ^
mxnet_wrap.cxx:8804:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg9 ; i++)
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorBackward(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:8993:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorOutputs(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:9063:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg2 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorBind(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:9146:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9174:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9201:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9231:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorBindX(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:9369:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:9393:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9418:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9449:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9477:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9504:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9534:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorBindEX(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:9695:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:9719:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9744:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9775:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9803:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9830:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:9860:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_ExecutorSimpleBind(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:10070:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10094:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:10119:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:10150:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10175:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10205:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10229:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:10253:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:10283:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10307:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:10338:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:10359:11: warning: unused variable ‘hash_len’ [-Wunused-variable]
       int hash_len;
           ^
mxnet_wrap.cxx:10424:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < *arg25 ; i++)
                              ^
mxnet_wrap.cxx:10441:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < *arg28 ; i++)
                              ^
mxnet_wrap.cxx: In function ‘void _wrap_ListDataIters(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:10623:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg1 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_DataIterGetIterInfo(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:10784:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (i = 0; i < *arg4 ; i++) {
                            ^
mxnet_wrap.cxx: In function ‘void _wrap_DataIterGetIndex(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:10982:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < *arg3 ; i++) {
                          ^
mxnet_wrap.cxx: In function ‘void _wrap_KVStoreInitEx(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:11264:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:11289:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_KVStorePushEx(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:11372:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:11397:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_KVStorePullEx(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:11487:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:11512:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx: In function ‘void _wrap_RtcCreate(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:12573:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:12598:32: error: ‘av_top_index’ was not declared in this scope
       len = av_top_index(tempav) + 1;
                                ^
mxnet_wrap.cxx:12623:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:12651:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:12536:15: warning: unused variable ‘temp90’ [-Wunused-variable]
     RtcHandle temp90 ;
               ^
mxnet_wrap.cxx: In function ‘void _wrap_RtcPush(PerlInterpreter*, CV*)’:
mxnet_wrap.cxx:12786:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
mxnet_wrap.cxx:12814:35: error: ‘av_top_index’ was not declared in this scope
       av_len = av_top_index(tempav) + 1;
                                   ^
In file included from mxnet_wrap.cxx:745:0:
mxnet_wrap.cxx: In function ‘void boot_AI__MXNetCAPI(PerlInterpreter*, CV*)’:
/usr/lib64/perl5/CORE/XSUB.h:164:20: warning: unused variable ‘items’ [-Wunused-variable]
 #define dITEMS I32 items = (I32)(SP - MARK)
                    ^
/usr/lib64/perl5/CORE/XSUB.h:172:16: note: in expansion of macro ‘dITEMS’
  dSP; dAXMARK; dITEMS
                ^
mxnet_wrap.cxx:13641:3: note: in expansion of macro ‘dXSARGS’
   dXSARGS;
   ^
make: *** [mxnet_wrap.o] Error 1

## Steps to reproduce
Just make AI-MXNetCAPI as here: https://mxnet.incubator.apache.org/get_started/ubuntu_setup.html

## What have you tried to solve it?
Rechecked installed dependencies.

**Comment by sergeykolychev** [comment]
@xurc 
old perl has not av_top_index defined, for now please change all av_top_index to av_len
 I'll patch the master code later when I'll be adding bigger feature.
For now please just use this as local workaround.

**Comment by xurc** [comment]
Yes, patch fixed the issue. Thank you.
