### ISSUE TITLE
feature request : shufflenet 

### ISSUE THREAD

**Issue by qingzhouzhen** [apache/incubator-mxnet#7972]
I am trying to implement shufflenet, when it is OK, I will contribute it to mxnet.

**Comment by szha** [comment]
Thanks for offering to help. It will be useful to many.

@ZiyueHuang you seem to have a shuffle net implementation in symbol. Do you have plan to port that into mxnet symbol model_zoo?

@qingzhouzhen there's currently no Gluon implementation for shufflenet in the model zoo. Would you like to give it a try there? Since Gluon has similar syntax to chainer just like pytorch, you can probably refer to a pytorch implementation (e.g. https://github.com/jaxony/ShuffleNet) as a starting point.

**Comment by ZiyueHuang** [comment]
@szha  Sure, I'm willing to contribute it to mxnet. I'll start training it on imagenet.

**Comment by szha** [comment]
Thanks to you both :). @qingzhouzhen  In the current Gluon model zoo, we follow the convention of having `features` and `classifier` sub-structures. This is to make it easier for feature extraction. You can take a look at an example for [alexnet](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/alexnet.py). Let me know if any clarification is needed.

**Comment by qingzhouzhen** [comment]
Could you give some suggestions on how to implement 'concate', 'reshape','add' operator on gluon, for I can not find these API on current gluon API `https://mxnet.incubator.apache.org/api/python/gluon.html`, did I found the wrong place? @szha

**Comment by szha** [comment]
Those can be implemented in the network's forward/hybrid_forward methods. Just refer to either symbol or ndarray API doc for them.
For example:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/custom_layers.py#L45-L50

Here the F is a placeholder for either symbol package or ndarray package. If you are familiar with pytorch, this basically means that you can use symbol/ndarray as the functional package. Thus, `F.concat` invokes either `symbol.concat` or `ndarray.concat`, depending on the input type.

**Comment by szha** [comment]
How's the progress?

**Comment by sandeep-krishnamurthy** [comment]
OONX version is available that can be imported in MXNet - https://github.com/onnx/models/tree/master/shufflenet

**Comment by sandeep-krishnamurthy** [comment]
Resolving it here - @qingzhouzhen - Please reopen if closed in error.
