### ISSUE TITLE
Concatenation r2D array to form 3D array type

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#7978]
I had an array of dimension 768*1024. I want to replicate this 2D array 19 times to make an 3D array of dimension 19x768x1024.
I got  confused reading docs...Kindly suggest what is the usage

**Comment by kevinthesun** [comment]
https://mxnet.incubator.apache.org/api/python/ndarray.html?highlight=repe#mxnet.ndarray.tile
a = mx.nd.zeros((768, 1024))
b = mx.nd.tile(a, reps=(19, 1, 1))

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by ThomasDelteil** [comment]
@chowkamlee81 does the example provided by @kevinthesun answer your query?

@szha can you please close this issue? Thanks!
