### ISSUE TITLE
Python: When pass None to mx.sym.var's shape and infer, python stop working

### ISSUE THREAD

**Issue by traveller59** [apache/incubator-mxnet#7981]
## Environment info
Operating System: Windows 10 64bit
Package used (Python/R/Scala/Julia):Python 
MXNet version: 0.11
## Error Message:
mxnet should raise a exception instead of stop working when user pass a None(tensorflow style) shape to mx.sym.var
Code:
```python
x = mx.sym.var('x', shape=(None, 100))
y = mx.sym.var('y', shape=(None, 100))
z = x + y
t = x** 2 + z / y
t.infer_shape()
```
Error:
```
[19:40:57] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\src\executor\infer_graph_attr_pass.cc:139: Check failed: is >> rshape[out_ent_id] Invalid attribute
```

**Comment by piiswrong** [comment]
None is not supported. Use 0

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Please use 0 for placeholder dimension like suggested above.
