### ISSUE TITLE
Is there any economy efficient large scale inferencing example?

### ISSUE THREAD

**Issue by yupbank** [apache/incubator-mxnet#7982]
it's expensive to train a model and we really want to apply deep learning for our production.

and it's expensive to download data to a big SSD disk

is there any example for easily apply mxnet model with s3 images and write back to s3 buckets the inference results in a large scale ?

would be supper helpful !!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudh2290** [comment]
Here is a document which should help you with using S3 https://mxnet.incubator.apache.org/faq/s3_integration.html. In general you should be able to use any of the existing examples with S3 by just changing the data source to point to the S3 url. Please let us know if you have any additional questions.

**Comment by anirudh2290** [comment]
@szha can you please remove "Need Triage" and add "Pending Requester Info" "Example"

**Comment by szha** [comment]
We have the option to use s3 as one of the supported file systems. The build option can be found in https://github.com/apache/incubator-mxnet/blob/master/make/config.mk#L156-L159

All pip packages of mxnet should already support s3 file systems.

**Comment by yupbank** [comment]
ah.. too bad, i have made a tensorflow model run within amazon lambda, it would still be tempting, if we have mxnet in lambda to use right away...

**Comment by szha** [comment]
mxnet is on pip. You can bring up an amazon linux instance and do `mkdir lambda_pack && pip install mxnet-mkl -t lambda_pack` and then use it on lambda.

**Comment by sandeep-krishnamurthy** [comment]
Please see here for an example of using MXNet on Lambda - https://aws.amazon.com/blogs/compute/seamlessly-scale-predictions-with-aws-lambda-and-mxnet/

Resolving. Please reopen if you still encounter any issue
