### ISSUE TITLE
404 not found when install mxnet in R in mac

### ISSUE THREAD

**Issue by Bee-zest** [apache/incubator-mxnet#7985]
> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
Installing package into ‘/mnt/home/fl/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed

**Comment by szha** [comment]
The file is in https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/macosx/el-capitan/contrib/3.4/mxnet_0.10.1.tgz

**Comment by szha** [comment]
@thirdwing

**Comment by szha** [comment]
@Bee-zest were you able to resolve the issue?

**Comment by Bee-zest** [comment]
I resolve it by installing in another way.(Installing via GPU version, I
just have CPU though)

**Comment by szha** [comment]
Thanks for the update. Good to know that it works for you now. I'm closing this issue for now, and feel free to let me know if there's any issue by reopening.
