### ISSUE TITLE
def _list_iamges(self, root) in ImageFolderDataset

### ISSUE THREAD

**Issue by KayneWest** [apache/incubator-mxnet#7986]
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/vision.py#L271

'images' not 'iamges'?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
