### ISSUE TITLE
I don't see any seq_len  was defined in the example of lstm

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#7990]
Was it inputed though the bucket_key in the BucketSentenceIter?

**Comment by szha** [comment]
There are several LSTM examples. Which one are you referring to?

**Comment by janelu9** [comment]
@szha  i mean the old one with bucket_io.py, lstm.py and lstm_bucketing.py

**Comment by janelu9** [comment]
# embeding layer
    data = mx.sym.Variable('data')
    label = mx.sym.Variable('softmax_label')
    embed = mx.sym.Embedding(data=data, input_dim=input_size,
                             weight=embed_weight, output_dim=num_embed, name='embed')
    wordvec = mx.sym.SliceChannel(data=embed, num_outputs=seq_len, squeeze_axis=1)

I don't understand how this argument was passed in

**Comment by szha** [comment]
https://github.com/apache/incubator-mxnet/blob/251ae71a20d8318ab20f4c19520f74b881fdf3ff/example/rnn/old/bucket_io.py#L269-L270
https://github.com/apache/incubator-mxnet/blob/251ae71a20d8318ab20f4c19520f74b881fdf3ff/python/mxnet/module/bucketing_module.py#L347
https://github.com/apache/incubator-mxnet/blob/251ae71a20d8318ab20f4c19520f74b881fdf3ff/example/rnn/old/lstm_bucketing.py#L56-L59
https://github.com/apache/incubator-mxnet/blob/251ae71a20d8318ab20f4c19520f74b881fdf3ff/example/rnn/old/lstm.py#L65-L88

**Comment by janelu9** [comment]
@szha 
    def sym_gen(seq_len):
        return lstm_unroll(num_lstm_layer, seq_len, len(vocab),
                           num_hidden=num_hidden, num_embed=num_embed,
                           num_label=len(vocab))
.....

    if len(buckets) == 1:
        # only 1 bucket, disable bucketing
        symbol = sym_gen(buckets[0])
    else:
        symbol = sym_gen
