### ISSUE TITLE
The Mulit-task learning example can not run

### ISSUE THREAD

**Issue by kli-nlpr** [apache/incubator-mxnet#7993]
AttributeError: 'Multi_Accuracy' object has no attribute 'num'

Then I change  https://github.com/apache/incubator-mxnet/blob/master/example/multi-task/example_multi_task.py#L79
to
```
    def __init__(self, num=None):
        super(Multi_Accuracy, self).__init__('multi-accuracy')
        self.num=num
```
There are still errors
```
    self.sum_metric[i] += (pred_label.flat == label.flat).sum()
TypeError: 'float' object has no attribute '__getitem__'
```

**Comment by szha** [comment]
Working on a fix

**Comment by szha** [comment]
#8006

**Comment by szha** [comment]
Fixed. You can checkout the latest master branch and give the example another try. Let me know if there's still issue.
