### ISSUE TITLE
Question about Float16

### ISSUE THREAD

**Issue by hfutxrg** [apache/incubator-mxnet#7996]
There is no errors on my side. I just want to ask a question about float16/FP16. Based on the info in this presentation http://on-demand.gputechconf.com/gtc/2017/presentation/s7218-training-with-mixed-precision-boris-ginsburg.pdf, there are three variables related to FP16: training values storage, matrix-multiply accumulator and master weight storage. At least nvidia caffe have these variables. In FP16 mode, there are multiple combinations:

training values storage | matrix-multiply accumulator |    training name
FP16       |                        FP32                                    |       mixed precision training
FP16        |                       FP16                                     |      FP16 training

In both mixed precision training and FP16 training, master weight storage could be either FP32 or FP16. 

So there are 4 combinations in total when using FP16 data types.

The question is that does MXNet have similar variables? When mxnet use float16 dtype, which one in these 4 combinations are you using? Do you also support these 4 combinations?

Thanks,
Rengan

**Comment by ptrendx** [comment]
If you choose fp16 dtype then training values storage is fp16, compute accuracy is fp32/TensorCore on Volta. By default, there is no fp32 master weight, but for SGD optimizer you can set multi_precision=True which will result in fp32 master weight. I have a PR #7654 that will make mixed precision work with all optimizer (although slower than a dedicated path like in sgd). If you use train_imagenet.py script with fp16 then it sets multi_precision option to True.

Before there was MSHADOW_USE_PASCAL compile flag that would enable fp16 compute (what caffe calls true fp16 training) but we decided that (especially with Volta) it is not worth the confusion it makes.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by cjolivier01** [comment]
Is this question resolved?
Questions are answered more quickly on https://discuss.mxnet.io/
Closing now, please reopen if necessary.
