### ISSUE TITLE
Question about benchmarking imagenet

### ISSUE THREAD

**Issue by Ujjalbuet** [apache/incubator-mxnet#7997]
Hi,

If I run the train_imagenet with benchmark option, I can see that for each epoch it executes 50 batches irrespective of batch size.

Is there a way to change the number of batches?

Thanks,
Saiful

**Comment by kevinthesun** [comment]
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/common/data.py#L113

The maximum iteration for each epoch is 500. 

You can also try gluon image benchmark which is easier to use: https://github.com/apache/incubator-mxnet/blob/master/example/gluon/image_classification.py

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by leleamol** [comment]
Recommnded Labels: "Question", "Need Requestor Info"

**Comment by sandeep-krishnamurthy** [comment]
Please reopen if you cannot find the required answer.
