### ISSUE TITLE
Is ndarray api designed for users  construct networks to predict, and symbol for training?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#7999]

**Comment by szha** [comment]
both symbol and ndarray can do both training and prediction.

**Comment by szha** [comment]
Feel free to reopen for follow up questions.

**Comment by janelu9** [comment]
@szha which one is faster , how to train a ndarray? can you give me a example please?

**Comment by szha** [comment]
Symbolic way is usually faster. Most of the examples were written in symbolic way.
For NDArray, you can use autograd to train in imperative way. https://mxnet.incubator.apache.org/versions/master/api/python/autograd.html?highlight=autograd#record-vs-pause
Yet another alternative is to use the new interface Gluon, to use imperative way for development and debugging and to use symbolic way for large-scale training. There are many step-by-step tutorials on this in http://gluon.mxnet.io/ and https://zh.gluon.ai/.

**Comment by janelu9** [comment]
@szha I want to train a word2vec model such as n-gamma , but i don't find any example ，I am familiar to use the symbol Api，but the first n-1 words of the sentence should be initiated as zeros I think，need I define it as a ndarray firstly in the BucketIter and use it as a symbol when training
