### ISSUE TITLE
Make a prediction using mxnet CNN model for text sentence classification

### ISSUE THREAD

**Issue by zannxD** [apache/incubator-mxnet#8004]
Hi I'm a newbie to data science, I followed this tutorial https://mxnet.incubator.apache.org/tutorials/nlp/cnn.html but I am confused over how to make a single prediction using the trained model generated by the above mentioned tutorial. Please guide me the right direction to fix this. Thanks.

**Comment by Rabia-Noureen** [comment]
Same question.... I am also a newbie Kindly provide some guidance.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by gautamkmr** [comment]
Please remove label: Need Triage
Please add label:  Exploration, Model, CNN,

**Comment by Ishitori** [comment]
To make a prediction using this model, you need to do a forward pass with the new data, as it is written in the bottom of the tutorial. It is very similar to how it is done to calculate test accuracy:

1. You set your data to the model
2. Then execute format pass with `is_train=False` flag
3. The output result is probabilities of being negative or positive labels (index 0 - negative, index 1 - positive)
4. You get the maximum value via argmax to get the final prediction.

Here is the code snippet:
```
    cnn_model.data[:] = x_data
    cnn_model.cnn_exec.forward(is_train=False)
    final_result = np.argmax(cnn_model.cnn_exec.outputs[0].asnumpy(), axis=1)
```
If you are doing prediction outside of the training script, then you also need to load parameters first, using `load_checkpoint` method.
