### ISSUE TITLE
cross compile mxnet for android, without using Amalgamation?

### ISSUE THREAD

**Issue by fye881** [apache/incubator-mxnet#8014]
Wondering anyone has tried to cross compile the whole mxnet to ARM platform, so that we can run python scripts. With Amalgamation, there's only .so generated and the python directory is not compiled I think.

**Comment by KellenSunderland** [comment]
@fye881: @larroy and I have worked on this a bit, and had pretty good success cross-compiling with docker.  We hope to merge in work once we get it a little more polished.  In the mean time was there a specific platform you were interested in?  I could probably create a gist with a Dockerfile for you.

**Comment by KellenSunderland** [comment]
Here's an example for ARMV6 and Linux https://gist.github.com/KellenSunderland/2ed6b52a16b403fdbc467259ff5cc355

**Comment by larroy** [comment]
https://github.com/apache/incubator-mxnet/pull/7792 Here's a dockerfile that builds for android.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by kalyc** [comment]
Hello @fye881, Thank You for submitting the issue. Were you able to resolve it? I am requesting the MXNet community to add label "Pending Requester Info"

**Comment by lupesko** [comment]
@sandeep-krishnamurthy can you please add "Android" and "Build" labels, and remove the "Need Triage" label?

**Comment by fye881** [comment]
Yes I think I get it compiled afterwards.

    On Monday, June 11, 2018, 4:08:19 PM PDT, Kalyanee Chendke <notifications@github.com> wrote:  
 
 
Hello @fye881, Thank You for submitting the issue. Were you able to resolve it? I am requesting the MXNet community to add label "Pending Requester Info"

**Comment by kalyc** [comment]
@fye881 could you please resolve this issue in that case?
