### ISSUE TITLE
mxnet installation GPU validation issue/error

### ISSUE THREAD

**Issue by kaisark** [apache/incubator-mxnet#8016]
Hi. I ran into an mxnet installation GPU validation issue on the Nvidia TX1 (Ubuntu 16.04). I built mxnet from source according to the Device Jetson TX2 GPU directions at:
[https://mxnet.incubator.apache.org/get_started/install.html#validate-mxnet-installation](url)

The CPU validation code works just fine, but the GPU errors (see attached log file):

>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())
>>> b = a * 2 + 1
>>> b.asnumpy()
array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]], dtype=float32)

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04

Compiler:
g++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Package used (Python/R/Scala/Julia):

MXNet version:
mxnet===0.11.1

Or if installed from source:
git clone https://github.com/dmlc/mxnet.git --recursive

MXNet commit hash (`git rev-parse HEAD`):
ebf1bf9d3a6cef335a5b2c2a37175e9e91f5b546

If you are using python package, please provide
pip (9.0.1)

Python version and distribution:
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
>>> [19:27:21] /home/nvidia/mxnet/dmlc-core/include/dmlc/./logging.h:308: [19:27:21] /home/nvidia/mxnet/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:110: Check failed: err == cudaSuccess (8 vs. 0) Name: MapPlanKernel ErrStr:invalid device function
(see attached log file)

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())
>>> b = a * 2 + 1
>>> b.asnumpy()
array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]], dtype=float32

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. reinstalled
2.
3.

[mxnet-out.log](https://github.com/apache/incubator-mxnet/files/1327872/mxnet-out.log)

**Comment by eric-haibin-lin** [comment]
@arank Do you know if anything on Jetson could cause this?

**Comment by arank** [comment]
this is giving a CUDA error so it is probably isn't finding your CUDA install or the version of CUDA you installed and mxnet expects is off. Did you go through the Jetpac setup to get the CUDA/CUDNN drivers onto the machine? What version of CUDA/CUDNN do you have?

**Comment by KellenSunderland** [comment]
I've tested that this works as expected with recent builds.  As mentioned previously it was likely an environment issue.  @kaisark Please let us know if this is still causing you problems.

**Comment by bhavinthaker** [comment]
@sandeep-krishnamurthy @eric-haibin-lin  Could one of you please close this issue?
