### ISSUE TITLE
How to put 2 networks in different gpus (resnet152 in gpu0 and resnet50 in gpu1) ?

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#8018]
Because of my large batch size, I can not put both resnet152 and resnet50 in the same gpu. How to put 2 network in different gpus? I found the lstm example of model parallelism but it is hard for me to understand. Who can show me an easier example? Thanks!

**Comment by solin319** [comment]
Is there any relationship between the two network, such as they will share some parameter?
If not ,you can run them in two process.
If yes, you must bind two different model in two different device. And design the order of execution and how the data pass between the two network.

**Comment by KeyKy** [comment]
@solin319 thanks. They share the same loss layer. The whole network is similar to a two stream network and one is resnet152(in gpu0) the other is resnet50(in gpu1).

**Comment by KeyKy** [comment]
I found the way!
