### ISSUE TITLE
Bug: arg_name "feat" lead to wrong result

### ISSUE THREAD

**Issue by devymex** [apache/incubator-mxnet#8021]
https://github.com/apache/incubator-mxnet/blob/e33da520641489363a710752e4fa7245a84aaa68/cpp-package/include/mxnet-cpp/symbol.hpp#L277

if `arg_name == "feat"`, both `arg_name.rfind("label")` and `arg_name.length() - 5` are -1.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@nswamy please add 'Bug', 'C++' to this topic

**Comment by leleamol** [comment]
@devymex I have recommended a workaround [here](https://github.com/apache/incubator-mxnet/issues/12966#issuecomment-435542458)
The "std::map<std::string, OpReqType>"  can be passed to SimpleBind() function that would model to upgrade gradients for the variable that have custom names. 

Please let us know if this helps.

**Comment by leleamol** [comment]
@mxnet-label-bot add ["Pending Requestor Info"]

**Comment by leleamol** [comment]
@mxnet-label-bot Can we close this issue since the fix has been merged with PR #13284
