### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by Vedaevolution** [apache/incubator-mxnet#8033]
Dear community,
I'm using mx-net 0.11.1 under windows x64 with cuda 8. Executing the ssd example i encountered serveral problems. As i have seen in other related issues some will get fixed. I fixed a few myself but now i have a problem. 

    File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\mxnet\lib\site-packages\mxnet\io.py", line 395,       in prefetch_func
    self.next_batch[i] = self.iters[i].next()
    
    File "D:/MachineLearning/MxNet/incubator-mxnet/example/ssd\dataset\iterator.py", line 215, in next
    pad=self.getpad(), index=self.getindex())

    File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\mxnet\lib\site-packages\mxnet\io.py", line 156, in __init__
    assert isinstance(data, (list, tuple)), "Data must be list of NDArrays"
    AssertionError: Data must be list of NDArrays

I get those error's and i must admit i don't see the cause of this. The test images and models get loaded correctly. At least i'm thinking that after debugging. Does anyone know how to solve this issue?

I can reproduce this easily by typing:

    demo.py --epoch 0 --images ./data/demo/dog.jpg --thresh 0.5

Best Regards

**Comment by zhreshold** [comment]
#8064 
Will fix this once merged.

**Comment by Vedaevolution** [comment]
Thank you very much! I'm knew to mxnet and didn't see the cause right away.
