### ISSUE TITLE
Bug: Shape of one dimension lead to crash in LogLoss::Update

### ISSUE THREAD

**Issue by devymex** [apache/incubator-mxnet#8040]
https://github.com/apache/incubator-mxnet/blob/50564bd7261fafe6aee809a23e8a1173fe060ea1/cpp-package/include/mxnet-cpp/metric.h#L92

how about a shape of one dim?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
@devymex Could you please add a small example that reproduces the crash?

**Comment by sandeep-krishnamurthy** [comment]
Resolving due to pending inactivity. Please reopen if the issue still persists.
