### ISSUE TITLE
Convert network written in json format to mxnet symbol code?

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8042]
Hai,

Is there is any utility which converts network written in mxnet  *.json format to mxnet symbols level code? Any options are available kindly let us know.

**Comment by solin319** [comment]
In python, "mxnet.symbol.load_json()" can load a json str to a mxnet symbol
![image](https://user-images.githubusercontent.com/13029886/30890701-068c90d0-a361-11e7-813f-eab5c094a30f.png)

**Comment by chinakook** [comment]
The 'convert_symbol.py' tool in 'tools\caffe_converter' can convert the protobuf of caffe to python code of mxnet and then execute the created code to establish symbol graph and save to json. You can draw inspiration from that.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by Imshepherd** [comment]
https://github.com/Imshepherd/MxNetR-Convert-json-to-symbol
Example code which I wrote for R.

**Comment by ThomasDelteil** [comment]
@chowkamlee81 there is no such utility I am afraid. It would be great to be able to do that, getting the code generated from a symbol definition or also for an ONNX model for example.

@sandeep-krishnamurthy can you please close this issue or convert it to Feature Request? Thanks!
