### ISSUE TITLE
Help！ when I go on training a language model, errors occured

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#8065]
my model:
```
import mxnet as mx
import numpy as np
from word2vec_io import BucketSentenceIter
import pickle as pk

sym, arg_params, aux_params = mx.model.load_checkpoint('output/5_gram', 10)

def Perplexity(label, pred):
    label = label.T.reshape((-1,))
    loss = 0.
    for i in range(pred.shape[0]):
        loss += -np.log(max(1e-10, pred[i][int(label[i])]))
    return np.exp(loss / label.size)

N=5
batch_size=64
data=pk.load(open('.//data//train.pkl','r'))
data=[i[0] for i in data]
data_val=pk.load(open('.//data//test.pkl','r'))
data_val=[i[0] for i in data_val]
train=BucketSentenceIter(data,batch_size,N)
val=BucketSentenceIter(data_val,batch_size,N)

devs = [mx.gpu(i) for i in range(1)]
mod = mx.mod.Module(symbol=sym, context=devs)
mod.fit(train, val,
        num_epoch=8,
        arg_params=arg_params,
        aux_params=aux_params,
        epoch_end_callback=mx.callback.do_checkpoint("./output/5_2gram"),
         eval_metric = mx.metric.np(Perplexity))

```

**Comment by janelu9** [comment]
``Traceback (most recent call last):

  File "<ipython-input-20-b8878605d082>", line 8, in <module>
    eval_metric = mx.metric.np(Perplexity))

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\base_module.py", line 472, in fit
    self.forward_backward(data_batch)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\base_module.py", line 193, in forward_backward
    self.forward(data_batch, is_train=True)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\module.py", line 538, in forward
    self._exec_group.forward(data_batch, is_train)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\executor_group.py", line 369, in forward
    _load_data(data_batch, self.data_arrays, self.data_layouts)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\executor_group.py", line 45, in _load_data
    _load_general(batch.data, targets, major_axis)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\module\executor_group.py", line 37, in _load_general
    d_dst_copy.copyto(d_dst)

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\ndarray.py", line 819, in copyto
    return _internal._copyto(self, out=other)

  File "<string>", line 31, in _copyto

  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\base.py", line 83, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [11:02:43] E:\Mxnet\mxnet-0.9.5\src\ndarray\ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (64,9) to.shape=(64,33)``

**Comment by janelu9** [comment]
I use a BucketSentenceIter , I infer that the data_batch's bucket_length is not equal to the one which the loaded model remembered

**Comment by szha** [comment]
The error is on shape mismatch, but it is impossible for others to diagnose if the symbol itself is not shared.

**Comment by szha** [comment]
Please reopen after attaching the symbol construction logic. Just to give an idea on what's likely happening, the symbol you have has a static shape for (64, 9), but you're feeding it with (64, 33). It's probably because you didn't use BucketingModule along with BucketingSentenceIter.

**Comment by szha** [comment]
When using bucketing module, you need a function that defines the symbol based on bucket key (usually length for language modeling). An example can be found here:
https://github.com/apache/incubator-mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py#L108-L122

@janelu9 the issues you opened tends to have incomplete information. Given incomplete information, it's unlikely that others can help you immediately. Next time please stick to the issue template and at least you should fill in the fields that could be relevant to your problem. Otherwise I will have to immediately close your issues.

**Comment by janelu9** [comment]
it never means that others don't know what I am asking . I load the model after it had been trained 10 epoches ,nothing wrong happened when I training it . but errors occured when I go on training from a save point .

**Comment by janelu9** [comment]
`import mxnet as mx
#mx.symbol_doc.SymbolDoc.get_output_shape()
def N_gamma(seq_len,batch_size,vocab_size,embed_dim,hidden_num,N):    
    data = mx.sym.Variable('data')
    embed_weight=mx.sym.Variable('embed_weight')
    H_weight=mx.sym.Variable('H_weight')
    d_bias=mx.sym.Variable('d_bias')
    U_weight=mx.sym.Variable('U_weight')
    W_weight=mx.sym.Variable('W_weight')
    b_bias=mx.sym.Variable('b_bias')
    b0_bias=mx.sym.Variable('b0_bias')
    label = mx.sym.Variable('softmax_label')
    embed = mx.sym.Embedding(data=data, input_dim=vocab_size, weight=embed_weight,output_dim=embed_dim, name='embed')
    wordvec = mx.sym.SliceChannel(data=embed,num_outputs=seq_len+N-1,squeeze_axis=1)
    y_all=[]
    for seq_idx in range(N-1,seq_len+N-1):
        word=[wordvec[i] for i in xrange(seq_idx-N+1,seq_idx+1)]
        hidden_concat = mx.sym.Concat(*word, dim=1)
        tanh_hidden=mx.sym.FullyConnected(data=hidden_concat,num_hidden=hidden_num,weight=H_weight,bias=d_bias,name='tanh_hidden')
        tanh_act=mx.sym.Activation(data=tanh_hidden, act_type="tanh")
        tanh_part=mx.sym.FullyConnected(data=tanh_act,num_hidden=vocab_size,weight=U_weight,bias=b_bias,name='tanh_part')
        fc_part=mx.sym.FullyConnected(data=hidden_concat,num_hidden=vocab_size,weight=W_weight,bias=b0_bias,name='fc_part')
        y=tanh_part+fc_part
        y_all.append(y)
    y_concat=mx.sym.Concat(*y_all,dim=0)
    label = mx.sym.transpose(data=label)
    label = mx.sym.Reshape(data=label, target_shape=(0,))
    sm = mx.sym.SoftmaxOutput(data=y_concat, label=label, name='softmax')
    return sm`

**Comment by janelu9** [comment]
my iter :
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 15:11:46 2017

@author: T800
"""

import mxnet as mx
import numpy as np
  
def gen_buckets_data(data,batch_size=32):
    bucket_data={}
    for d in data:
        len_d=len(d) 
        if len_d !=0:
            if  len_d in bucket_data:
                bucket_data[len_d].append(d)
            else:
                bucket_data[len_d]=[d]
    bk=bucket_data.keys()
    len_max=max(bk)
    for h,ij in enumerate(bucket_data.iteritems()):
        i,j=ij
        lj=len(j)
        rm_num=lj%batch_size
        if rm_num and i<len_max:
            bucket_data[bk[h+1]].extend(bucket_data[i][:rm_num])
            del bucket_data[i][:rm_num]
    for k in bucket_data.keys():
        if bucket_data[k]==[]: 
            bucket_data.pop(k)
    bucket_data=bucket_data.values()
    if rm_num>0:bucket_data[-1].extend(bucket_data[-2][:batch_size-rm_num])
    return bucket_data

class SimpleBatch(object):
    def __init__(self, data_names, data, label_names, label,bucket_key):
        self.data = data
        self.label = label
        self.data_names = data_names
        self.label_names = label_names     
        self.bucket_key=bucket_key

    @property
    def provide_data(self):
        return [(n, x.shape) for n, x in zip(self.data_names, self.data)]
    @property
    def provide_label(self):
        return [(n, x.shape) for n, x in zip(self.label_names, self.label)]
    
class BucketSentenceIter(mx.io.DataIter):
    def __init__(self,data,batch_size,N):
        super(BucketSentenceIter, self).__init__()
        data=gen_buckets_data(data,batch_size)
        self.data,self.bucket_plan,self.bucket_idx=[],[],[]
        for idx,i in enumerate(data):
            temp=np.zeros((len(i),len(i[0])),int)            
            for jdx,j in enumerate(i):
                temp[jdx,:len(j)]=j
            self.data.append(temp)
            li=len(i)
            self.bucket_plan.extend([idx]*(li/batch_size))
            rg=range(0,li,batch_size)
            np.random.shuffle(rg)
            self.bucket_idx.append(rg)
        np.random.shuffle(self.bucket_plan)
        self.batch_size=batch_size
        self.bucket_idx_ct=[0]*len(data)
        self.buckets=[len(i[0]) for i in data]
        self.default_bucket_key = self.buckets[-1]
        self.N=N
        self.provide_data = [('data', (batch_size, self.default_bucket_key+self.N-1))]
        self.provide_label = [('softmax_label', (self.batch_size, self.default_bucket_key))]
    def __iter__(self):
        for i in self.bucket_plan:
            begin=self.bucket_idx[i][self.bucket_idx_ct[i]]
            data=self.data[i][begin:begin+self.batch_size]
            self.bucket_idx_ct[i]+=1
            label=np.zeros(data.shape,int)
            label[:,:-1]=data[:,1:]
            data = [mx.nd.array(np.hstack([np.zeros([self.batch_size,self.N-1],int),data]))]
            label = [mx.nd.array(label)]
            data_names = ['data']
            label_names = ['softmax_label']
            yield SimpleBatch(data_names, data, label_names, label,self.buckets[i])
    def reset(self):
        self.bucket_idx_ct = [0]*len(self.data)

**Comment by janelu9** [comment]
the error's info"  failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (64,9) to.shape=(64,33)" 
33 is just the largest bucket_len of my data

**Comment by janelu9** [comment]
@szha now can this issue be reopened?

**Comment by szha** [comment]
It seems that you only have the data iterator logics and you don't have the logic for constructing the RNN model. The later is required if you want to use bucketing module, because bucketing module requires sym_gen function for generating the function. The example is here

https://github.com/apache/incubator-mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py#L108-L122

**Comment by janelu9** [comment]
this is a  n-gram model
import mxnet as mx
import numpy as np
from n_gamma import N_gamma
from word2vec_io import BucketSentenceIter
import pickle as pk

def Perplexity(label, pred):
    label = label.T.reshape((-1,))
    loss = 0.
    for i in range(pred.shape[0]):
        loss += -np.log(max(1e-10, pred[i][int(label[i])]))
    return np.exp(loss / label.size)

if __name__ == '__main__':
    batch_size=64
    hidden_num = 128
    embed_dim = 128
    N=5
    vocab=pk.load(open('.//data//dict_news_lstm20160804.pkl','r'))
    vocab_size=len(vocab)
    data=pk.load(open('.//data//train.pkl','r'))
    data=[i[0] for i in data]
    data_val=pk.load(open('.//data//test.pkl','r'))
    data_val=[i[0] for i in data_val]
    def sym_gen(seq_len):
        return N_gamma(seq_len,batch_size,vocab_size,embed_dim,hidden_num,N)
    train=BucketSentenceIter(data,batch_size,N)
    test=BucketSentenceIter(data_val,batch_size,N)
    symbol=sym_gen
    model = mx.model.FeedForward(ctx=[mx.context.gpu(i) for i in range(1)],
                                 symbol=symbol,
                                 num_epoch=10,
                                 learning_rate=0.01,
                                 momentum=0.0,
                                 wd=0.00001,
                                 initializer=mx.init.Xavier(factor_type="in", magnitude=2.34))

    import logging
    #head = '%(asctime)-15s %(message)s'
    #logging.basicConfig(level=logging.DEBUG, format=head)
    logging.basicConfig(level=logging.DEBUG,
                    filename='./train.log',
                    filemode='w')
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    logging.getLogger().addHandler(console)

    model.fit(X=train, eval_data=test,
              eval_metric = mx.metric.np(Perplexity),
			  epoch_end_callback=mx.callback.do_checkpoint("./output/5_gram"),
              batch_end_callback=mx.callback.Speedometer(batch_size, 100),)``

**Comment by szha** [comment]
You need BucketingModule to train the model, instead of regular Module or Model.

Example can be found here:
https://github.com/apache/incubator-mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py#L129-L132

Hope it helps.

**Comment by janelu9** [comment]
@szha  it seems this iter 'mx.rnn.BucketSentenceIter' doesn't match my model

**Comment by szha** [comment]
I'd suggest reading the API doc to decide whether that's the case. Read the documentation to decide is always faster than guess work from examples.

**Comment by janelu9** [comment]
Anyone else who can tell me how can I modify my iter to make the training goes well

**Comment by szha** [comment]
Please be considerate of other people's time. If you have specific questions, let us know.

**Comment by janelu9** [comment]
boy you have closed a unsolved problem

**Comment by szha** [comment]
@janelu9 [a quick search](https://github.com/apache/incubator-mxnet/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Ajanelu9%20) turns up that all your issues are similar to this one, and all of them don't follow the issue templates and always lacks the necessary details. Not only does this cost other people a lot of time to go back and forth with you, you're unlikely to receive the help you need either. Next time when you open issues, please be considerate and provide all the necessary information following the issue template.
