### ISSUE TITLE
How to freeze mean and variance parameters of batchnorm layers of resnet-50? When using mx.mod.Module(fixed_param_names), those parameters belongs to auxiliary parameters and not in symbol.list_arguments()

### ISSUE THREAD

**Issue by jay1204** [apache/incubator-mxnet#8066]
How to freeze mean and variance parameters of batchnorm layers of resnet-50? When using mx.mod.Module(fixed_param_names), those parameters belongs to auxiliary parameters and not in symbol.list_arguments()

**Comment by solin319** [comment]
When training, moving_mean,moving_var just compute a result. They were not used in param normalization .
When testing, if you don't want to use moving_mean and moving_var, you can set " use_global_stats = False" in batchnorm layers or set is_training=True in forward() function
