### ISSUE TITLE
Test 'good' trained model but any detection

### ISSUE THREAD

**Issue by pitLog** [apache/incubator-mxnet#8076]
## Environment info
Operating System: Linux and Windows
Compiler: gcc 5.4.0
Package used (Python/R/Scala/Julia): Python 2.7
MXNet commit hash (`git rev-parse HEAD`):
Python version and distribution: Python 2.7, Linuxmint 18.1

I make a train with ssd (example/ssd) and model vgg16_reduced . The train seems to be good :
Epoch[498] Validation-VL=0.846089
Epoch[498] Validation-PL=0.770777
Epoch[498] Validation-BUS=0.631579
Epoch[498] Validation-UTILITAIRE=0.933206
Epoch[498] Validation-MOTO=0.678569
Epoch[498] Validation-PT=0.788829
Epoch[498] Validation-mAP=0.774841

but when I run the trained model to an example, nothing is detected, even with images I used to make the train.

I used the code : https://github.com/zhreshold/mxnet-ssd.cpp to test model.

I try to change threshold but nothing is better.

Anybody has a solution ?

**Comment by zhreshold** [comment]
That cpp codebase is deprecated. It's not entirely compatible now.

**Comment by pitLog** [comment]
Is there a framework for object detection like SSD available with C++ and Mxnet ?

**Comment by zhreshold** [comment]
Seems like mxnet is the simplest option, if you want continue use the cpp version, simply update the mxnet backend in that repo and modify according to API changes. Basically that one is still usable if upgraded.

**Comment by pitLog** [comment]
I actually find the problem, I had invert xmax and ymin in annotation xml files. It's strange because condition statement in generic.py (if xmin < xmax ....) didn't work. And also, train worked well and had good mAp although there was any blob for the train ??
 
Thanks for your feedbacks.
