### ISSUE TITLE
Bulk Closing Issues

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#8081]
Hello,

As you may have noticed, we contributors of mxnet are bulk closing old inactive issues. To avoid confusion, here are several things to know:

**Why**
We are closing issues that haven't been updated for at least 90 days and don't have labels, so that contributors can better focus our efforts on active issues.

Many issues haven't been active because the issues have already been patched and the involved parties forgot to follow up. Others might be due to incomplete information, making the issues not actionable. Some may be issues on APIs that are deprecated, and better solution/API has been developed. By closing these old inactive issues, we can get a better signal-to-noise ratio from users to guide our efforts.

**What do I need to do?**
If the issue is a problem that hasn't been solved and is still impacting you, you have the choice of commenting on the closed issue and asking for reopen. Alternatively, you could comment on this issue, quoting the issue number that you believe should be reopened, and we will happily reopen it and help.

If the issue is already resolved, remember to give the contributor a thumbs-up!

**Comment by zhreshold** [comment]
And please remember to close the issue once it's solved.
