### ISSUE TITLE
Example of mxnet based superresolution.py fails...

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8098]
Hai,

I was executing superresolution.py example . But i got an error below at line 33:
ImportError: No module named data

Kindly suggest how to proceed

**Comment by szha** [comment]
Checking

**Comment by szha** [comment]
#8106 should fix it.

**Comment by szha** [comment]
@chowkamlee81 thanks for reporting the problem. The example is fixed. Please check out the latest version and give it a try.

Also, note that you need to run the example with `example/gluon/` as the current working directory, so that `data` module can be correctly imported.

**Comment by szha** [comment]
And feel free to close the issue if it's resolved.

**Comment by ChidanandKumarKS** [comment]
Thanks ur solution got worked for me. Thanks and closing the issue.
