### ISSUE TITLE
rec generated by im2rec.py has same value for different key in idx

### ISSUE THREAD

**Issue by caiqi** [apache/incubator-mxnet#8103]
I generate a large rec file (over 1M files) using im2rec with MXIndexedRecordIO and observe that in data.idx file, after specific lines, the first number in each line keeps increasing while the second one keeps unchanged, like this:

> 32989	18446744073709551615
> 32990	18446744073709551615
> 32991	18446744073709551615
> 32992	18446744073709551615
> 32993	18446744073709551615
> 32994	18446744073709551615
> 32995	18446744073709551615
> 32997	18446744073709551615
> 32998	18446744073709551615

From this line https://github.com/apache/incubator-mxnet/blob/22b2897d23de44c696c7776a7a2ba1879be5eb2e/python/mxnet/recordio.py#L226, it seems that the second number determines the position for a specific key. So different key should have a different position. I have tried read through the full rec file and found that the last few items are not the same and their position should be different. So what does the second column in idx file mean and is it normal to have same values in second columns? Is there any documentation? Thanks.

**Comment by zhreshold** [comment]
I suspect it's overflown.  @piiswrong

**Comment by ptrendx** [comment]
It would mean that the rec file has exabytes of data in it. For some reason tell errored out with -1. I will look into reproing it just in case there is some bug in mxnet, but I would suspect problems with filesystem. What was the filesystem where you were saving your .rec file?

**Comment by caiqi** [comment]
The file system is NTFS. I will try on another machine to check whether it's due to hardware reasons.

**Comment by caiqi** [comment]
I have tried on another machine, it still has the problem.  When I use read_idx() to read the rec, it will throw an error, however, when I use read() I checked that the unpacked label is correct with the *.lst file.

**Comment by ptrendx** [comment]
Thanks for checking. I did not yet have time to try reproducing it, will do that next week. Could you tell me how big is the file by the way? Also, what is the version of MxNet you use (commit if compiled from source)?

**Comment by caiqi** [comment]
The file size is about 55GB. I create the rec for Imagenet VID dataset following this https://github.com/apache/incubator-mxnet/tree/master/example/ssd. The mxnet version is 0.11.0, installed with **pip install mxnet-cu80** on windows. Thanks.

**Comment by caiqi** [comment]
I found that the problem occurs when the file size reaches 2GB.  The pos in this line https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/recordio.py#L248 becomes 18446744073709551615(-1). I have checked the system is x64 based and tested with python2/python3 and the latest build of mxnet. The problem still exists. However, the *.rec looks fine.

**Comment by ptrendx** [comment]
Ok, I looked it up and it turns out that on Windows long is 32 bit vs 64
bit on linux, and ftell returns long. I will make a PR to dmlc-core today
with the fix.

Thanks for reporting the bug!

**Comment by caiqi** [comment]
Thank you very much!

**Comment by ptrendx** [comment]
Hi @caiqi - could you check that applying this PR dmlc/dmlc-core#318 fixes your issue?

**Comment by caiqi** [comment]
It fixes the problem. But there is a typo here: https://github.com/dmlc/dmlc-core/pull/318/files#diff-1f6c080379cd78f60fe204c6c9a1eb44R46. It misses a ')'. Thank you very much!
