### ISSUE TITLE
Proposal: PR Template

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#8105]
# What
I’d like to propose that we use PR template in MXNet. The template should consist of a checklist for the required items for merging a PR (e.g. lint and testing), as well as the items of the change (e.g. features)

# Why
It should serve two purposes:
- It reminds both the contributor and reviewer/committers of checking the prerequisites before merging.
- It serves as a progress tracking tool on which PRs are ready for review and merging, so that reviewer/committers 

# How
- Contributor should maintain the status of PR by checking/unchecking items in the checklist.
- Committer should uncheck items that hasn’t been passed yet (e.g. contributor checked lint but lint failed on CI), and make comments on what more should be done. By default committers review PRs that are shown to be complete in the PR list.

# FAQ
- What if I as a contributor want to request for review of things working in progress?
Everyone can still do what everyone is doing now: requesting reviewer to take a look by @ them.
- What if some items in the checklist don’t apply to my PR?
They can be deleted.

# Template
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] For user-facing API changes, API doc string has been updated.

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Intersting edge cases to note here

**Comment by bhavinthaker** [comment]
Looks good to me. Thanks for this suggestion.

**Comment by szha** [comment]
Thanks. @apache/mxnet-committers just to make sure everyone is aware.
