### ISSUE TITLE
how can I get the ndarray'grad for multi gnu simply?

### ISSUE THREAD

**Issue by junranhe** [apache/incubator-mxnet#8142]
My code like this:
def test_mult_gpu(a, b):
  with mx.autograd.record():
    return a+b.as_in_context(a.context)
a = mx.nd.array([1.,2.], ctx=mx.context.gpu(0))
b = mx.nd.array([3.,4.], ctx=mx.context.gpu(1))
a.attach_grad()
b.attach_grad()
mult_test = test_mult_gpu(a, b)
print 'test mult:', mult_test.asnumpy()
mult_test.backward()
print 'test backward',a.grad.asnumpy(), b.grad.asnumpy()

I want to get b's grad, 
but in this code, b.grad == [0.,0.], b.as_in_context(a.context) can not backward b'grad, how can I get it simply?

**Comment by ZiyueHuang** [comment]
Please try `copyto`. https://github.com/apache/incubator-mxnet/blob/master/tests/python/gpu/test_operator_gpu.py#L1422 `test_cross_device_autograd ` should be helpful for you.

**Comment by junranhe** [comment]
@ZiyueHuang  thank you very much, it is helpful!!!
