### ISSUE TITLE
`mx.callback.Speedometer` cannot be used in `epoch_end_callback`

### ISSUE THREAD

**Issue by VikingMew** [apache/incubator-mxnet#8143]
mxnet 0.11

  model.fit(
        train_data=data_train,
        eval_data=data_test, eval_metric=mx.metric.Perplexity(-1),
        kvstore=args.kv_store,
        optimizer=args.optimizer,
        optimizer_params={'learning_rate': args.lr,
                          'momentum': args.mom,
                          },
        initializer=mx.init.Uniform(0.05),
        num_epoch=args.num_epochs,
        epoch_end_callback=mx.callback.Speedometer(args.batch_size, args.disp_batches, auto_reset=False),
    )

Traceback (most recent call last):
  File "main.py", line 121, in <module>
    epoch_end_callback=mx.callback.Speedometer(args.batch_size, args.disp_batches, auto_reset=False),
  File "/scratch/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/mxnet-0.11.0-elgezfabbrsjq72fmhjzb77fbqt7fpeg/lib/python2.7/site-packages/mxnet/module/base_module.py", line 521, in fit
    callback(epoch, self.symbol, arg_params, aux_params)
TypeError: __call__() takes exactly 2 arguments (5 given)

**Comment by ZiyueHuang** [comment]
`Speedometer ` should be used as batch_end_callback.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by mbaijal** [comment]
@VikingMew were you able to fix this as suggested?

**Comment by mbaijal** [comment]
Please add the label 'Pending Requester Info' and remove the label 'Need Triage'

**Comment by sandeep-krishnamurthy** [comment]
@vikingMei - Please reopen if your issue is still not resolved.
