### ISSUE TITLE
footer overlay covering search results

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#8146]
## Steps to reproduce

1. Switch to master using the dropdown at the top of the mxnet.io home page
2. Search for something in the search field at the top right
3. Or follow this [link](https://mxnet.incubator.apache.org/versions/master/search.html?q=ndarray&check_keywords=yes&area=default)

**Comment by aaronmarkham** [comment]
Bump. This is still a problem in the 0.12 release...

**Comment by nswamy** [comment]
can we move this issue to https://github.com/apache/incubator-mxnet-site

**Comment by szha** [comment]
#8841

**Comment by aaronmarkham** [comment]
Fixed with #8841
