### ISSUE TITLE
Error when compiling MXNet from source with VS2013 / Windows 10

### ISSUE THREAD

**Issue by Bumblebee1964** [apache/incubator-mxnet#8155]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10

Compiler: VS2013 Professional

Package used (Python/R/Scala/Julia):

MXNet version: 0.11

Or if installed from source: Cloned on October 4th 2017

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Error	277	error C2668: 'mshadow::cuda::AddTakeGrad' : ambiguous call to overloaded function	c:\projects\mxnet-0.11\base\src\operator\tensor\indexing_op.h	304	1	mxnet

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

Generated CMake script:
# Install script for directory: C:/Projects/MxNet-0.11/Base

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/mxnet")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Projects/MxNet-0.11/Base/build/Debug/libmxnet.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Projects/MxNet-0.11/Base/build/Release/libmxnet.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Projects/MxNet-0.11/Base/build/MinSizeRel/libmxnet.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Projects/MxNet-0.11/Base/build/RelWithDebInfo/libmxnet.lib")
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Projects/MxNet-0.11/Base/build/Debug/libmxnet.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Projects/MxNet-0.11/Base/build/Release/libmxnet.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Projects/MxNet-0.11/Base/build/MinSizeRel/libmxnet.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Projects/MxNet-0.11/Base/build/RelWithDebInfo/libmxnet.dll")
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "C:/Projects/MxNet-0.11/Base/include/")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/mxnet" TYPE DIRECTORY FILES "C:/Projects/MxNet-0.11/Base/example")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Projects/MxNet-0.11/Base/build/dmlc-core/cmake_install.cmake")
  include("C:/Projects/MxNet-0.11/Base/build/mshadow/cmake_install.cmake")
  include("C:/Projects/MxNet-0.11/Base/build/tests/cmake_install.cmake")
  include("C:/Projects/MxNet-0.11/Base/build/cpp-package/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/Projects/MxNet-0.11/Base/build/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. Tried to compile with VS2017 Professional. Got same error message
2.
3.

**Comment by santanpereira** [comment]
I got some similar error earlier, then i tried the setup with VS 2015, Miniconda3 and python 3.5 which worked for me. After the python and VS 2015 install i run [install-mxnet-windows-python.bat](https://github.com/apache/incubator-mxnet/blob/master/setup-utils/install-mxnet-windows-python.bat) and keep on resolving the few errors which i got. That is what worked for me.

**Comment by Bumblebee1964** [comment]
I my case it doesn't matter whether I use VS2013/VS2015/VS2017. Maybe I have something wrong with the CMake file (text of it in the original post).

Has anybody a guide for compiling the sources on WIndows with VS20xx??? I managed to do it with mxnet 0.95 but with vs 0.11 that doesn't work anymore, so frustrating.

**Comment by Bumblebee1964** [comment]
@santanpereira : is there a guide for using install-mxnet-windows-python.bat?

Do you mean install VS 2015 install, the installation of Windows VS 2015 or installing mxnet for VS 2015?

**Comment by santanp** [comment]
Sadly, There are no document which i came across for using install-mxnet-windows-python.bat, I went through the file to understand it. Also by VS 2015 install i mean we need to install VS 2015 on windows which have necessary built tools for building mxnet.

**Comment by Bumblebee1964** [comment]
@santanpereira did you use MKL or OpenBLAS?

**Comment by santanpereira** [comment]
I used OpenBLAS

**Comment by Bumblebee1964** [comment]
Is the MXNet team going to resolve this issue, or at least document how to build MXNet with cpp package on Windows?

I am considering to move to an other Deep Learning platform despite all efforts until now. As I am stuck for over a month and only able to work with Python interface instead of C++

**Comment by Bumblebee1964** [comment]
@santanpereira: Do you know the version of OpenBLAS? Did you build it yourselve?

**Comment by santanpereira** [comment]
Earlier I tried to build openblas which didn’t work out, So I booted a new windows 2016 server machine and relyed on install-mxnet-windows-python.bat to setup openblas.

**Comment by Bumblebee1964** [comment]
@santanpereira thanx:)

**Comment by bhavinthaker** [comment]
@sandeep-krishnamurthy @eric-haibin-lin  Could one of you please close this issue?
