### ISSUE TITLE
mx.symbol.Upsampling issue confusing

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8157]
i had an input [1,2048,4,4]. And i need output of dim [1,2048,48,64] i.e a row_factor=12 and col_factor=16.
Using Deconvolution i have tried, but it takes a lot of time since its shape of the product is too large i.e 2048x2048x12x16..
I would like to use simple mx.symbol.upsampling, but very confusing. Kindly suggest for the above problem and pls help

**Comment by chowkamlee81** [comment]
@szha @pluskid any solution kindly suggest

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudhacharya** [comment]
@chowkamlee81 can you please elaborate on what you want to accomplish. I doubt UpSampling is the operator you need.

@eric-haibin-lin please add the label - "Question", "Pending Requester Info".

**Comment by sandeep-krishnamurthy** [comment]
Resolving due to lack of inactivity. Please use discuss forum for how-to questions. Please reopen the issue, if you still encounter the issue.
