### ISSUE TITLE
Fine tune tutorial urllib bug on Python 3

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#8159]
Tutorial:
https://github.com/apache/incubator-mxnet/blob/master/docs/faq/finetune.md

Python version and distribution:
3.6

## Steps to reproduce

1. Executing the section of code to download the dataset will fail with a urllib error unless you're using Python 2.7.x

```
urllib.urlretrieve(url, filename)
```
Yields:
```
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

This replacement for the offending code block seems to work when tested locally:

```
import os, sys

if sys.version_info[0] >= 3:
    from urllib.request import urlretrieve
else:
    from urllib import urlretrieve
    
def download(url):
    filename = url.split("/")[-1]
    if not os.path.exists(filename):
        urlretrieve(url, filename)
download('http://data.mxnet.io/data/caltech-256/caltech-256-60-train.rec')
download('http://data.mxnet.io/data/caltech-256/caltech-256-60-val.rec')
```

**Comment by szha** [comment]
Would you propose a change in the form a pull request?
