### ISSUE TITLE
missing arguments in SSD example train.py

### ISSUE THREAD

**Issue by caiqi** [apache/incubator-mxnet#8165]
It seems that this line  https://github.com/apache/incubator-mxnet/blob/master/example/ssd/train.py#L132 misses train_list and val_list parameters. 

Here the  https://github.com/apache/incubator-mxnet/blob/master/src/io/iter_image_det_recordio.cc#L100 label_ seems including image_path and cause error here https://github.com/apache/incubator-mxnet/blob/master/src/io/image_det_aug_default.cc#L265 (1).

**Comment by zhreshold** [comment]
I don't get the point. What's the error you got?

**Comment by caiqi** [comment]
If I pass path_imglist parameter to ImageDetRecordIter, it will throw an error: 

\src\io\image_det_aug_default.cc:274: Check failed: (label_width - header_width) % object_width_ == 0 (1 vs. 0).

**Comment by zhreshold** [comment]
Detection label used is different from classification. https://mxnet.incubator.apache.org/versions/master/api/python/image/image.html
The label can be included in record file, so in the example I didn't include it. However, passing in correct list file should still be ok.

**Comment by 7oud** [comment]
Some basic questions about ImageDetRecordIter, expecting answers
1. When training, it loaded .rec file without .idx file, then why generated .idx file ?
2. When loading .rec file as input, how to do the image augmentation ?
3. The main function of DetRecordIter is reshape the batch with batch size, is it?
4. If processing 16-bit png image, I suppose to read it using cv.imread('', flag=2), then covert it to float32 type and normalized to [0,1]. This lossless procession can be implemented in ssd data processed framework ?

**Comment by thomelane** [comment]
@caiqi I realise this is from a long time ago, but were you able to provide a few more details so we can check whether this is still an issue for users. Much appreciated!

**Comment by caiqi** [comment]
@thomelane This is not a problem if using the SSD code directly. The original confusing thing is the format of imglist is not the same with the list which is used to create the rec file if I would like to provide imglist additionally. I think it's not a problem anymore. Thanks.

**Comment by thomelane** [comment]
Ah, okay, so the image lists (for getting data into RecordIO format, and specifically for this SSD example) serve a similar purpose but are different formats. Many thanks for clarifying that.

@indhub good to close when you get a chance, thanks!
