### ISSUE TITLE
CODEOWNERS

### ISSUE THREAD

**Issue by hen** [apache/incubator-mxnet#8177]
Please add commentary to https://github.com/apache/incubator-mxnet/blob/master/CODEOWNERS to explain what the file is for. "Owners" is a very broad phrase, and I'm guessing this is a GitHub functionality rather than saying that that individual has any kind of special veto over code going into that codebase.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by srochel** [comment]
@hen - please see updated file content. Is this sufficient or what additional information is needed?
Suggest to close this issue.

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Please close this issue as the CodeOwners file has been updated. 

@hen Please feel free to re-open the issue if closed in error.
Thanks!
