### ISSUE TITLE
All Keras 1.2.2 examples Illegal instruction/core dump

### ISSUE THREAD

**Issue by peterfig** [apache/incubator-mxnet#8183]
Any time I call Keras model.train method, there is an illegal instruction error.  I can reproduce this behavior with any/all the Keras examples.

## Environment info
Operating System:
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

MXNet version: 0.11.0
Keras 1.2.2

## Error Message:
```
Train on 60000 samples, validate on 10000 samples
Epoch 1/50
/home/peter/virtualenvs/mxnet2/local/lib/python2.7/site-packages/mxnet/module/bucketing_module.py:385: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.01). Is this intended?
  force_init=force_init)
Illegal instruction (core dumped)
```

## Minimum reproducible example/steps to reproduce
From your clone of the Keras repo, examples directory, run any of the example from the command line.  (`python addition_rnn.py` for example).

**Comment by peterfig** [comment]
I am also getting `Illegal instruction (core dumped)` when running the mxnet examples.  So it is not a Keras issue.

I am getting the error with Python 3.5.2 as well.  

I will try to compile from source.  I have these new Intel v4 Xeons and they've been a headache at times.

**Comment by szha** [comment]
@peterfig which mxnet example did you run?

**Comment by peterfig** [comment]
`cnn_text_classification` and others.

I just installed the mxnet-mkl package and `cnn_text_classification` is working.  I bet the Keras stuff will work now too.  So, I think it is fair to say the Python mxnet package will not work out of the box for all Intel processors.

**Comment by szha** [comment]
@peterfig this might be the case. AVX support was turned on by default before 0.11.1 so it could cause problems. Starting from 0.11.1, it supports run-time detection so similar problem shouldn't happen any more. If you'd like to test it, you can get 0.11.1 nightly build using `pip install --pre mxnet` (with other appropriate flags). Let me know how it goes if you decide to give it a try.

**Comment by peterfig** [comment]
Absolutely, I'll give it a whirl.  If you let me know what the "other appropriate flags are" because I have no idea.

**Comment by szha** [comment]
Sorry for the confusion. For example, you may want to turn on `--user` for installing in user directory. Or if you already have a pip-installed mxnet, you may want to turn on `--upgrade`.

**Comment by peterfig** [comment]
I tried `pip install mxnet==0.11.1b20171007` and it works!  However, `mxnet-mkl`was using all my cores whereas this one appears to be using only two.  This one is much more efficient, getting 153 samples/sec with 2 cores while `mxnet-mkl` was getting 450 samples/sec with 32 cores.

Anyhow, it works, thanks much!

**Comment by szha** [comment]
Good to know. BTW the `mxnet-mkl` also has the nightly version and can be installed with the same method.

**Comment by peterfig** [comment]
`mxnet-mkl-0.11.1b20171007` is also only using two cores, and is a little (10%) faster than the regular version.

**Comment by szha** [comment]
What's the number of physical cores on your machine? Try `export OMP_NUM_THREADS=$NUM_PHYSICAL_CORES`.

**Comment by peterfig** [comment]
I've got two CPUS for a total of 20 physical cores; setting that environment variable doesn't seem to change anything.  But the 0.11.0 mxnet-mkl used them all automatically.

**Comment by szha** [comment]
That's weird. @cjolivier01 do you have an idea?

**Comment by cjolivier01** [comment]
This issue says closed, right?

Is the MKL build built with GPU support (even though only CPU is being used)?  GPU and CPU builds have different OpenMP characteristics, regardless of whether GPU is being used. This difference will be relaxed somewhat in the 1.0 release.

**Comment by szha** [comment]
`mxnet-mkl` is not built with GPU support.

**Comment by cjolivier01** [comment]
I am not aware of anything being added into master since 0.11 that would affect that. It would have to be investigated.

**Comment by kalyanghosh** [comment]
I am getting started with Keras! When I run the code python examples/mnist_cnn.py, I am getting the same error.
I would be very thankful, if someone can list down the steps to solve this issue.

**Comment by cjolivier01** [comment]
pull the latest from master (as of 90 seconds ago) and build or set USE_PROFILER=1 in config.mk
