### ISSUE TITLE
Could you put GPU version python package for windows to PyPi

### ISSUE THREAD

**Issue by PaulaQin** [apache/incubator-mxnet#8186]
I want to use mxnet python package on windows OS. I have found a GPU version on PyPi (https://pypi.python.org/pypi/mxnet-cu80/0.11.0), but not CPU version. Could you put one on the website https://pypi.python.org/pypi/mxnet/0.11.0?

**Comment by szha** [comment]
It's now available thanks to @yajiedesign. Closing for now. Let me know if you have any trouble using it.

**Comment by PaulaQin** [comment]
I have seen it. Thank @szha @yajiedesign very much!
