### ISSUE TITLE
How to define custom callback function?

### ISSUE THREAD

**Issue by liuzhi136** [apache/incubator-mxnet#8197]
I want to define my own callback function that will be used at every training epoch, not just saving the model's parameters. Does anyone has any idea about this?
Any help will be appreciated.

**Comment by ZiyueHuang** [comment]
You can refer to https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/callback.py. Here is an application example https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/core/callback.py.

**Comment by liuzhi136** [comment]
@ZiyueHuang Thanks, it's very useful.

**Comment by eric-haibin-lin** [comment]
The issue seems to be resolved. Closing it for now. For further questions / comments, you're welcome to post them on the discussion forum https://discuss.mxnet.io/
