### ISSUE TITLE
L2Normalization can not support matrix which rows number is larger than 65536

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#8202]
this limitation is in the gpu reduce code. it should be solved.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by leleamol** [comment]
Requested Labels: "Bug"

**Comment by haojin2** [comment]
@starimpact Seems like this issue has been fixed, here's an example that I ran on the current master:
```
>>> a = mx.nd.zeros((65540, 2, 2), ctx=mx.gpu(1))
>>> mx.nd.L2Normalization(a, mode='channel')

[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 ..., 
 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]
<NDArray 65540x2x2 @gpu(1)>
>>> mx.nd.L2Normalization(a)

[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 ..., 
 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]
<NDArray 65540x2x2 @gpu(1)>
```
If you have further questions or concerns regarding this operator please feel free to raise that, thanks!

**Comment by starimpact** [comment]
after more than half year, eventually.....

**Comment by haojin2** [comment]
@starimpact My apologies about that on behalf of the team! Hope that you're still using MXNet as your DL framework. Your issue should be fixed by some earlier PRs, but we somehow failed to link the improvement to your issue.

**Comment by starimpact** [comment]
emmmm.....
swapaxis operator is written by me in 2015.
hahahah....

**Comment by haojin2** [comment]
@starimpact lol, would you mind closing the issue as the bug seems to be solved already? Thanks!
