### ISSUE TITLE
How to release the GPU?!

### ISSUE THREAD

**Issue by Tommymhz** [apache/incubator-mxnet#8203]
Hi, I find that the mxnet use the model to training ,but afer training ,I want to know how to release the memory so I can do the task other?  I find there is no api to release the gpu memory !!

**Comment by janelu9** [comment]
command nvidia-smi, you will see the pid 
kill it

**Comment by janelu9** [comment]
Just run "
`kill `nvidia-smi|sed -n '18p'|awk -F ' ' '{print $3}'``
" in the terminal

**Comment by Tommymhz** [comment]
Oh! Thank you first!  I mean that I want to release a module and take another module in python, but the Mxnet don't release the gpu memory which use in the first module,  In the tensorflow,  the sess.close() is to release the gpu. So I want to know if any api like "sess.close()" to release the gpu!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudhacharya** [comment]
please label this - "Question", "Memory" and close it for lack of activity.
