### ISSUE TITLE
Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8204]
I got the same bug as in issue 6958. Iam doing semantic segmentation as a module bit stuck with up this issue.
The above  issue 6958 has not been solved yet. Kindly suggest

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
