### ISSUE TITLE
Ask : MKL2017 and MKL-DNN

### ISSUE THREAD

**Issue by edmBernard** [apache/incubator-mxnet#8205]
It seem Mxnet with MKL2017 config use MKL-DNN api for ML and not MKL2017 api. [prepare_mkl.sh#L87](https://github.com/apache/incubator-mxnet/blob/master/prepare_mkl.sh#L87)
on the intel doc both are similar but different. 
> Intel MKL-DNN includes functionality similar to [Intel(R) Math Kernel
Library (Intel(R) MKL) 2017](https://software.intel.com/en-us/intel-mkl), but is not
API compatible. We are investigating how to unify the APIs in future Intel MKL releases.

It's a bit confusing

**Comment by eric-haibin-lin** [comment]
@ykim362

**Comment by ykim362** [comment]
@edmBernard  Just the binary of MKL2017 is residing in mkl-dnn's git repo. The current master doesn't uses any mkl-dnn functions, yet.

**Comment by edmBernard** [comment]
oh thank's
