### ISSUE TITLE
module.fit() doesn't work for image segmentation

### ISSUE THREAD

**Issue by m-ky** [apache/incubator-mxnet#8206]
Hello, I'm having troubles using mxnet to do image segmentation. Here is a small sample source where method module.fit() does nothing and prints nothing - it seems as learning never happened without any error message.
When I run this code it immediately prints "end.". Function module.fit() does nothing.
In the example I have data as 32 randomly generated 2x2 images with values 0-9 and the result of segmentation is a 2x2 image with values 0-1.

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Win7, 64 bit

Compiler: VS 2015

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.11

Or if installed from source: yes, from 0.11 branch and master branch - same result

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: Anaconda 5.0.0, python 3.5

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace: no error message, no warning

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

`
import mxnet as mx
import numpy as np

def main():

   input_x = mx.sym.Variable("data")
   c = input_x
   c = mx.sym.Convolution(data=c, num_filter=4, kernel=(3, 3), pad=(1, 1))
   c = mx.sym.Activation(data=c, act_type="relu")
   c = mx.sym.Convolution(data=c, num_filter=1, kernel=(1, 1))
   #c = mx.sym.LogisticRegressionOutput(data=c, name="softmax")
   c = mx.sym.SoftmaxOutput(data=c, name="softmax")
   symbol = c

   train_x = np.random.randint(10, size=(32, 1, 2, 2))
   train_y = train_x > 0

   val_x = np.random.randint(10, size=(8, 1, 2, 2))
   val_y = val_x > 0

   batch_size = 2
   num_epoch = 10

   it_train = mx.io.NDArrayIter(train_x, train_y, batch_size=batch_size, shuffle=True)
   it_val = mx.io.NDArrayIter(val_x, val_y, batch_size=batch_size)

   module = mx.mod.Module(symbol=symbol, context=mx.cpu())
   module.fit(it_train, it_val, num_epoch=num_epoch)

   print("end.")

if __name__ == '__main__':
   main()
`

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by Soonhwan-Kwon** [comment]
It seems you missed eval_metric argument in module.fit. You need it to print out your result. Take a look at the link https://mxnet.incubator.apache.org/tutorials/python/mnist.html

**Comment by m-ky** [comment]
Thank you, but the eval_metric defaults to "acc". I tried other metrics, but it still doesn't print anything.

**Comment by Soonhwan-Kwon** [comment]
I recommend you to test with your own custom metric, like below
```
class ClassifyMetric(mx.metric.EvalMetric):

    def __init__(self, batch_size, num_gpu):
        super(ClassifyMetric, self).__init__('ClassifyMetric')

        self.batch_size = batch_size
        self.num_gpu = num_gpu

    def update(self, labels, preds):
        print(preds)
        print(labels)
```
then switch your script
```
eval_metric = ClassifyMetric(batch_size=batch_size, num_gpu=1)
module.fit(it_train, it_val, num_epoch=num_epoch,eval_metric='acc')
```
then it prints out preds and labels you generates through.
It seems default acc metric doesn't met your output shape.

**Comment by m-ky** [comment]
Thank you, it works now and prints the preds and labels. I will play around with it more.
