### ISSUE TITLE
test_loss.t fails sporadically and causes builds to fail

### ISSUE THREAD

**Issue by indhub** [apache/incubator-mxnet#8213]
[test_loss](https://github.com/sergeykolychev/mxnet/blob/163dfe8a428e2c0322929ed36b857ba80cec1ef3/perl-package/AI-MXNet/t/test_loss.t) fails sporadically and causes builds to fail.

test_loss.t was added in PR #8015.

Links to build failures:
https://builds.apache.org/view/Incubator%20Projects/job/incubator-mxnet/job/master/481/
https://builds.apache.org/view/Incubator%20Projects/job/incubator-mxnet/job/master/483/
https://builds.apache.org/view/Incubator%20Projects/job/incubator-mxnet/job/master/490/

## Environment info
Operating System: Ubuntu

MXNet version:
Commit hashes:
Build 481: 759f5091eb5feae68ffc5914d6cf8798dd2af6d7
Build 483: 92e5198d659ab8f69e22bbbb9c54a36e5a25a2fa
Build 490: ee9771580765393b194172bab169dd67ac575209

## Error Message:
```
[Perl: GPU] #   Failed test at t/test_loss.t line 233.
```
```
[Perl: GPU] #   Failed test at t/test_loss.t line 183
```

## Steps to reproduce
Run build and unit test.

**Comment by sergeykolychev** [comment]
I'll look at it tomorrow and fix.

**Comment by sergeykolychev** [comment]
https://github.com/apache/incubator-mxnet/pull/8214

**Comment by indhub** [comment]
Thanks. I think that fixed the issue. I'll close this. Will reopen if I see the issue again.
