### ISSUE TITLE
how to import a trained embedding_weight into a nlp model ?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#8237]

**Comment by szha** [comment]
You can load it into an NDArray and use the [Embedding operator](https://mxnet.incubator.apache.org/versions/master/api/python/ndarray.html?highlight=embedding#mxnet.ndarray.Embedding). For general "how-to" questions, we recommend using the user forums such as https://discuss.mxnet.io and https://discuss.gluon.ai/

**Comment by janelu9** [comment]
yes that's what i did
