### ISSUE TITLE
different behaviour of customop in latest MXNet

### ISSUE THREAD

**Issue by VikingMew** [apache/incubator-mxnet#8238]
https://discuss.gluon.ai/t/topic/1540/2

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by anirudh2290** [comment]
@VikingMew can you please help provide a brief description and current status of the issue in English. I looked at the discuss post using google translate and the translated statements are not very clear.

**Comment by samskalicky** [comment]
@VikingMew Is this still a problematic issue? If so, can you please provide more info about which versions were consistent and which version it is no longer consistent with? 

Also, that customop example is incomplete. Can you provide a complete working/failing script?

**Comment by samskalicky** [comment]
@VikingMew need your help, could you please provide more info about which versions and a complete example of a failing customop?

**Comment by apeforest** [comment]
@nswamy @sandeep-krishnamurthy Could you please close this issue. It's been over 90 days without response. Thanks
