### ISSUE TITLE
Failing to create R package on Linux.

### ISSUE THREAD

**Issue by hadjipantelis** [apache/incubator-mxnet#8240]
Hello, I try to create the R-package to install from source on CentOS 7 but loading the package during package building fails. I follow the instructions [here](https://mxnet.incubator.apache.org/get_started/install.html).
In the past (around Feb-March 2017) I have installed and ran `mxnet` fine on this particular system but now the `make rpkg` fails so I am slightly puzzled what is going on. I have the same error as https://github.com/apache/incubator-mxnet/issues/1104 but the proposed solutions (`make clean`/ `make clean_all` prior to built) do not work. Building the MXNet core shared library works fine on face value, but building the MXNet R binding/package fails.

The exact commands I use are:
```
rm mxnet/ -rf
git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet --branch 0.11.0
cd mxnet/
make clean_all #(I tried simple make clean too)
cp make/config.mk .
echo "ADD_CFLAGS += -I/usr/include/openblas" >>config.mk
make -j $(nproc) USE_OPENCV=0 USE_BLAS=openblas USE_LAPACK=1
make rpkg
```
The error that I get is:
```
Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/userh/R/x86_64-redhat-linux-gnu-library/3.4/mxnet/libs/mxnet.so':
  /home/userh/R/x86_64-redhat-linux-gnu-library/3.4/mxnet/libs/mxnet.so: undefined symbol: _ZN2cv8fastFreeEPv
```

R environment:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1
```
 
I have also tried (as in https://github.com/apache/incubator-mxnet/issues/1011): 1. after `make clean_all` to go into `cd ps-lite` and `make -j` prior to the general building of the shared MXnet libraries as well as 2. after `make clean_all` to `git submodule update` but neither has resolved the error. 
A final thing I tried is to install the clone current ( so use `git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet` directly instead of `0.11.0` and then `make clean` etc. etc.) but this gave the same error as above.

(I am able to build the MXNet Python binding fine.)
(*Update (16-Oct-2017)*: I am able to build the R bindings on Debian 8 but not on CentOS 7. -- *Update  (20-Oct-2017): OpenCV was installed in that system so unintentionally the dependency was met.*
(*Update (20-Oct-2017)*: I am able to build the R bindings on this CentOS system when using branch [v0.10.0](https://github.com/apache/incubator-mxnet/tree/v0.10.0). Something has changed (probably in the `R-package` or `MAKEFILE rpkg`? I suspect that all the `cp src/io/image_recordio.h R-package/src` line; see also https://github.com/apache/incubator-mxnet/issues/7273 ) between the two versions causing CentOS to fail creating the R bindings.

Thank you!

**Comment by thirdwing** [comment]
I guess `_ZN2cv8fastFreeEPv` should come from `opencv`.

Please try to remove the installed `mxnet` package first.

**Comment by hadjipantelis** [comment]
@thirdwing: Hello, thank you for the reply. Y
es, of course I have removed my prior `mxnet` installation. The issue is that OpenCV is unavailable on the systems I work on and this prohibits running newer `mxnet` versions. (I don't work on CV/ImRec.)

**Comment by anirudhacharya** [comment]
This issue has been resolved in the latest master. @sandeep-krishnamurthy please close this issue.

@hadjipantelis feel free to reopen if the problem persists.
