### ISSUE TITLE
A3C code does not learn

### ISSUE THREAD

**Issue by moakra** [apache/incubator-mxnet#8248]
Hi @piiswrong ,

I tried to run your code on my GPU but the variable final_score.mean() is always around -20.
Did you succeed to make it work? If yes, did you use the default hyper-parameters ? How much time does the learning take for you?

Mohamed

**Comment by piiswrong** [comment]
Which A3C?
This one is working for me https://github.com/apache/incubator-mxnet/blob/master/example/gluon/actor_critic.py

**Comment by moakra** [comment]
I was talking about this code: https://github.com/apache/incubator-mxnet/tree/master/example/reinforcement-learning/a3c  

Now it works.

Thank you!
