### ISSUE TITLE
can row sparse array support other sparse store? 

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#8250]
I just refer to RowSparseNDArray,which is just only fit for all 0 in one row.
array([[ 1.,  2., 3.],
       [ 0.,  0., 0.],
       [ 4.,  0., 5.],
       [ 0.,  0., 0.],                            -->                                 array([[ 1.,  2., 3.],
       [ 4.,  0., 5.]], dtype=float32)
                                                                                  [ 0.,  0., 0.]], dtype=float32)

And can mxnet support the matrix like that
[1,2],
[1,2,3],
[1,3,4,5] every row has different colums
If not ,i still need to increase storage in order to keep fixed length.

**Comment by reminisce** [comment]
Current RowSparseNDArray has equal amount of memory for each row. This looks like a different format to support. Could you describe the use case where this matrix is used?

**Comment by liumilan** [comment]
advertisement,Click-Through-Rate using in lr.
every sample has different features
@reminisce

**Comment by reminisce** [comment]
It looks like that CSR format makes better sense here.
https://mxnet.incubator.apache.org/versions/master/tutorials/sparse/csr.html

**Comment by eric-haibin-lin** [comment]
CSR will work for you. There's an sparse LR example in MXNet here using avazu CTR data: https://github.com/apache/incubator-mxnet/tree/master/example/sparse

Closing it for now. For further questions/discussions, we're moving to https://discussion.mxnet.io
