### ISSUE TITLE
Better GPU producing worse results for cifar10

### ISSUE THREAD

**Issue by Ujjalbuet** [apache/incubator-mxnet#8251]
Hi,
I have a K20c GPU and a Titan Z GPU. The Titan Z GPU is faster in running all other networks except for training cifar10 with mlp or lenet network. I can see from profiler that two systems use different sgemm kernels for the same application.

Why is this happening?

**Comment by solin319** [comment]
The version of cuda and cudnn are same between two systems?

**Comment by szha** [comment]
@Ujjalbuet consider using the diagnose script to report the system environments of your machines to avoid dealing with the back-and-forth questions. It's really simple to use.

What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

**Comment by Ujjalbuet** [comment]
No. I have to use docker image for one system and have standard installation with cuda 8.0 and cudnn 6 for the other. I think the docker image uses cudnn 5.  Is there any docker image for R available with cudnn 6?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by kalyc** [comment]
@Ujjalbuet could you please update the issue/ resolve it if its not persisting anymore?
