### ISSUE TITLE
Does mxnet have a dataiter for prediction of buckets models  ?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#8255]

**Comment by janelu9** [comment]
need I write it myself? if I use the same one as train ,it will output a  disordered result

**Comment by janelu9** [comment]
need I write it myself? if I use the same one as train ,it will output a disordered result

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by gautamkmr** [comment]
Please remove label: Need Triage
Please add label: Data-loading,  Exploration, Modelling

**Comment by janelu9** [comment]
i  have resolved it
