### ISSUE TITLE
update examples of mxnet

### ISSUE THREAD

**Issue by mxmxlwlw** [apache/incubator-mxnet#8256]
Hello, some examples use deprecated api. Can you update them? Thanks. ( for example: multi-task)

**Comment by aidan-plenert-macdonald** [comment]
https://github.com/zackchase/mxnet-the-straight-dope has more up to date examples if you want examples.

I'm sure they would appreciate a pull request :)

**Comment by mxmxlwlw** [comment]
Yeah, thank you very much!
