### ISSUE TITLE
How can I view the network in rnn example?

### ISSUE THREAD

**Issue by mxmxlwlw** [apache/incubator-mxnet#8257]
How can I view the network in rnn example? Thank you

**Comment by aidan-plenert-macdonald** [comment]
Did you see https://mxnet.incubator.apache.org/how_to/visualize_graph.html?

**Comment by mxmxlwlw** [comment]
Yeah, but in rnn, it use mx.mod.BucketingModule. and I tried to pass the return value to the mx.viz.plot_network, it didn't seem to work out.

**Comment by eric-haibin-lin** [comment]
Does this issue help?
https://github.com/apache/incubator-mxnet/issues/5051

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by rahul003** [comment]
Hi, did eric-haibin-lin's suggestion solve your problem?
If not, could you use https://discuss.mxnet.io/ to ask this again. We request you to use that forum for questions.

**Comment by rahul003** [comment]
@eric-haibin-lin Please label this with doc, question, visualization

**Comment by mxmxlwlw** [comment]
Yes, thank you
