### ISSUE TITLE
test_kvstore_gpu.test_row_sparse_pull takes forever to run and causes build failures

### ISSUE THREAD

**Issue by indhub** [apache/incubator-mxnet#8262]
## Description
test_kvstore_gpu.test_row_sparse_pull takes forever to run and causes build failures

Links to build failures:
https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/516/pipeline
https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/PR-8244/2/pipeline/
https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/PR-8246/2/pipeline/288

PR that introduced the change:
https://github.com/apache/incubator-mxnet/pull/7082

MXNet commit hash:
a05ac492379f479769b948b2268a175233e96784
420f2229f4bedf4b01e7cf010e673affd28f8916

## Error Message:
```
[Python3: MKLML-GPU] test_kvstore_gpu.test_row_sparse_pull ... [Pipeline] [Python3: MKLML-GPU] }
[Pipeline] [Python3: MKLML-GPU] // timeout
[Pipeline] [Python3: MKLML-GPU] }
[Pipeline] [Python3: MKLML-GPU] // ws
[Pipeline] [Python3: MKLML-GPU] }
[Pipeline] [Python3: MKLML-GPU] // node
[Pipeline] [Python3: MKLML-GPU] }
[Python3: MKLML-GPU] Failed in branch Python3: MKLML-GPU
```

## Steps to reproduce
Build and run the unit test. Failure seems to happen in Python3: MKLML-GPU.

**Comment by eric-haibin-lin** [comment]
@indhub could you disable this test for now?

**Comment by indhub** [comment]
@eric-haibin-lin Done.
