### ISSUE TITLE
/mxnet/example/rcnn/rcnn/symbol/symbol_vgg.py Error: mx.symbol.contrib

### ISSUE THREAD

**Issue by truongbuu** [apache/incubator-mxnet#8266]
I just overcome an issue in this file.

Trying to run the script with bash command return error :

line 293, in get_vgg_test
    rois = mx.symbol.contrib.Proposal(
AttributeError: 'module' object has no attribute 'contrib'

I think it should be fixed into: mx.contrib.symbol (Fixed this and works fine)
Best

**Comment by aidan-plenert-macdonald** [comment]
Can you submit a pull request?

**Comment by solin319** [comment]
try to use 'mx.contrib.symbol.Proposal'

**Comment by aidan-plenert-macdonald** [comment]
@truongbuu Could you include steps to reproduce it?

I am getting,
```python
>>> import mxnet.contrib.symbol.Proposal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mxnet.contrib.symbol.Proposal'; 'mxnet.contrib.symbol' is not a package
>>> import mxnet.symbol.contrib.Proposal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mxnet.symbol.contrib.Proposal'; 'mxnet.symbol.contrib' is not a package
>>> mxnet.__version__
'0.11.1'
```

**Comment by truongbuu** [comment]
@aidan-plenert-macdonald : It should be 

`from mxnet.contrib import symbol as sym
sym.Proposal`

**Comment by zhreshold** [comment]
sym.contrib or contrib.sym are now equivalent methods in the latest mxnet.
