### ISSUE TITLE
[Feature Request][Gluon] Add text processing utilities for Gluon like PyTorch/Text

### ISSUE THREAD

**Issue by orchidmajumder** [apache/incubator-mxnet#8278]
Similar to vision module, MXNet Gluon should have utilities to ease NLP experiments by providing modules like BucketingIterator, Popular dataset loaders etc.

Similar module for PyTorch: https://github.com/pytorch/text

**Comment by szha** [comment]
Thanks for the request. It's on my radar.

**Comment by orchidmajumder** [comment]
Thanks Sheng.

**Comment by szha** [comment]
#8763

**Comment by szha** [comment]
Check out https://github.com/dmlc/gluon-nlp
