### ISSUE TITLE
Error: dot‑gemm: matrix shape mismatch

### ISSUE THREAD

**Issue by DIYer22** [apache/incubator-mxnet#8282]
## Description
raise `dot‑gemm: matrix shape mismatch` when fit a net which employ `mx.sym.UpSampling`

## Others
modification `mx.sym.UpSampling(sample_type='bilinear')` to `mx.sym.UpSampling(sample_type='nearest')` solved my problem

**Comment by eric-haibin-lin** [comment]
Do you mind posting some code snippet here so that others can reproduce the issue?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by mbaijal** [comment]
Can you please add the label 'Pending Requester Info' and remove the label 'Need Triage'
