### ISSUE TITLE
Caffe integration test fails because it is not able to download files from caffe server

### ISSUE THREAD

**Issue by indhub** [apache/incubator-mxnet#8283]
## Description
Caffe integration test fails because it is not able to download files from caffe server.

Failed build:
https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/v0.12.0/4/pipeline

- If license permits, we should be hosting these files in S3 and downloading from there for the purposes of tests instead of depending on external servers. 
- The test can also check if the file already exists in the file system to avoid downloading again and again every time.

## Environment info (Required)
CI builds.

## Steps to reproduce
Build and run integration test.

**Comment by szha** [comment]
This is more likely a slave setup problem. The link indicated in the error works fine here. http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel

**Comment by szha** [comment]
Reviewed the license, and it doesn't pose any restriction on use. I will move its hosting to s3 and re-enable.
