### ISSUE TITLE
dist_sync kvstore can not load balance ?

### ISSUE THREAD

**Issue by junranhe** [apache/incubator-mxnet#8290]
hi, I do distributed training with 80000 classes ,the base network is inception-resent_v2 the last predict layer are concat by 8 fc layer(weight shape  is (10000,512)  ), train with 4 machine( 8 gpu, 4 worker , 4 server), I find the networkflow are not balance, 3 machine with 4 Gb/s,  and 1 machine with 7Gbs, how can I may load balance with dist kvstore?  
我英文不好，还是用中文写下我的问题吧， 我用分布式训练一个8万分类的任务，网络结构是inception_restnet_v2, 4台机器，每台8gpu，分布式的命令是4worker 4 server，  我把最后一层的全连接拆成了8个等分的全连接层（基于项目中显存均衡分配到每个gpu的目的）， 我训练时候查看了4台机器中的网络流量负载， 发现3台服务器 4Gb／s，一台 7Gb／s， 感觉负载均衡的不够好？mxnet dist kvstore的负载均衡策略具体是怎样的？我可以怎样做让网络的负载均衡更好？（同时，我留意到用softmax的交叉熵loss的话，最后一层全连接大部分权重的剃度都是零，我能怎么用kvstore优化这种只有少部分权重的更新呢？）

**Comment by solin319** [comment]
The default value of environment parameter MXNET_KVSTORE_BIGARRAY_BOUND is 10^6.
In key-value pairs, if the number of values larger than MXNET_KVSTORE_BIGARRAY_BOUND, this key-value pair will be split into num_servers parts and stored partly.

**Comment by junranhe** [comment]
@solin319 thanks for reply! but  how the params  stored？randow？ How can I get the stored data information details？：）
