### ISSUE TITLE
Import error in SSD example

### ISSUE THREAD

**Issue by agataradys** [apache/incubator-mxnet#8291]
## Description
After this commit https://github.com/apache/incubator-mxnet/commit/b2ce81218b13c3140dc3d2fd9fa27a1dd0264b75 SSD example stopped working. In this line https://github.com/apache/incubator-mxnet/blob/b2ce81218b13c3140dc3d2fd9fa27a1dd0264b75/example/ssd/config/config.py#L19 there was a change from `utils` to `config.utils`. Bringing back previous version solves the problem.

## Environment info (Required)
I'm using Python 2.7

## Error Message:
```
Traceback (most recent call last):
  File "perf.py", line 27, in <module>
    from train.train_net import train_net
  File "/root/Models/SSD_VGG/Mxnet/train/train_net.py", line 28, in <module>
    from config.config import cfg
  File "/root/Models/SSD_VGG/Mxnet/config/config.py", line 19, in <module>
    from config.utils import DotDict, namedtuple_with_defaults, zip_namedtuple, config_as_dict
ImportError: No module named utils
```

**Comment by edmBernard** [comment]
did you use python2 or python3 ?

**Comment by agataradys** [comment]
@edmBernard I use python2

**Comment by edmBernard** [comment]
@agataradys it seem ssd example have been port to python3 
your error come from the different behaviour in import between python2 and python3
either you can switch to python3 or you can try to import this at the beginning of the file : `from __future__ import absolute_import`

**Comment by agataradys** [comment]
@edmBernard Thank you, this solution worked. Are you going to fix this example to work on both Python versions? Do you still support Python2?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by b0noI** [comment]
Suggested tags: "Bug", "Doc"

**Comment by zhreshold** [comment]
I suppose it is solved now for both python2/3, closing this for now, feel free to ask me to reopen it if it's not solved.
