### ISSUE TITLE
mx.nd.array indexing broken in armv7 / raspberrypi / jessie 8.0 (5 dimensional tensor)

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#8292]
## Description
test_ndarray_slice broken in armv7
multidimensional array indexing broken for 5 dimensions.

## Environment info (Required)

armv7 / raspberrypi / jessie 8.0

## Simple reproduction:
```
nosetests --verbose python/unittest/test_ndarray.py
```

Manual reproduction with a simpler example:

```
In [150]: a=mx.nd.array([[[[[0,1,2],[3,4,5]]]]])

In [151]: a[0]
Out[151]: 

[[[[ 0.  1.  2.]
   [ 3.  4.  5.]]]]
<NDArray 1x1x2x3 @cpu(0)>

In [153]: a[0]
Out[153]: 

[[[[ 0.  1.  2.]
   [ 3.  4.  5.]]]]
<NDArray 1x1x2x3 @cpu(0)>

In [154]: a[0,0]
Out[154]: 

[[[  2.00000000e+00   3.00000000e+00   4.00000000e+00]
  [  5.00000000e+00   0.00000000e+00   5.53355948e-39]]]
<NDArray 1x2x3 @cpu(0)>

In [155]: a[0,0,0]
Out[155]: 

[[  3.00000000e+00   4.00000000e+00   5.00000000e+00]
 [  0.00000000e+00   5.53355948e-39   9.62310147e+27]]
<NDArray 2x3 @cpu(0)>

In [156]: a[0,0,0,0]
Out[156]: 

[ 4.  5.  0.]
<NDArray 3 @cpu(0)>

In [157]: a[0,0,0,0,0]
Out[157]: 

[ 0.]
<NDArray 1 @cpu(0)>

In [158]:     


```

**Comment by piiswrong** [comment]
Possibly due to int32 vs int64?

**Comment by larroy** [comment]
I'm looking at this issue.

**Comment by larroy** [comment]
I think the problem must be in array slicing inside the native lib. I have debugged the python code and the call to slice is exactly the same in mac and arm:
addressing a[0,0] calls
op.slice(handle, begin=[0,0], end=[1,1])

**Comment by reminisce** [comment]
@larroy Yes, there is a high chance that something went wrong in the op's backend implementation on arm devices. Can you run gdb to find out the root cause on your device? Or you can printing statements in the code to output intermediate information.

**Comment by larroy** [comment]
@reminisce that's what I'm trying to do, thanks.

**Comment by larroy** [comment]
Found the bug: 

in matrix_op-inl.h:472 we are addressing the parameter vector outside of bounds. If you slice a 5 dimensional tensor, the loop is accessing past the end, since the param.begin and param.end have only size 2.

When you access a[0,0] it translates to a slice(begin=(0,0), end(1,1)) for example.

This is broken, and what's funny is that is working in other platforms...

I'm working on a fix. Why is param.end not even used in this slice function?

**Comment by reminisce** [comment]
Great catch! This looks like a serious bug. `param.end` was used in inferring output shape.

**Comment by larroy** [comment]
Right, we verified this with @KellenSunderland. The oshape is inferred and param.end is used in inline TShape GetSliceShape(const SliceParam& param, const TShape& dshape) 

I will send a PR with a proposed fix shortly. Unfortunately this bug is not revealed unless the right garbage is on the uninitialized params beyond ndim.
