### ISSUE TITLE
test_cifar10 fails in CI master build

### ISSUE THREAD

**Issue by indhub** [apache/incubator-mxnet#8299]
## Description
test_cifar10 fails in CI master build.
Failed build: https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/532/pipeline/

## Environment info (Required)
CI build 
Python 2 CPU

MXNet commit hash:
1c1c788916d672ee3cafdc4c91d7002a94a59d13

## Error Message:
```
======================================================================
FAIL: test_dtype.test_cifar10
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/workspace/tests/python/train/test_dtype.py", line 192, in test_cifar10
    run_cifar10(train, val, use_module=True)
  File "/workspace/tests/python/train/test_dtype.py", line 136, in run_cifar10
    assert (ret[0][1] > 0.08)
AssertionError: 
-------------------- >> begin captured logging << --------------------
root: INFO: Start training with [cpu(0)]
root: INFO: Epoch[0] Batch [50]	Speed: 7880.07 samples/sec	accuracy=0.109531
root: INFO: Epoch[0] Batch [100]	Speed: 10121.26 samples/sec	accuracy=0.092969
root: INFO: Epoch[0] Batch [150]	Speed: 9358.31 samples/sec	accuracy=0.094375
root: INFO: Epoch[0] Batch [200]	Speed: 9408.26 samples/sec	accuracy=0.100312
root: INFO: Epoch[0] Batch [250]	Speed: 10316.01 samples/sec	accuracy=0.099062
root: INFO: Epoch[0] Batch [300]	Speed: 9913.46 samples/sec	accuracy=0.093906
root: INFO: Epoch[0] Batch [350]	Speed: 10337.40 samples/sec	accuracy=0.103750
root: INFO: Epoch[0] Resetting Data Iterator
root: INFO: Epoch[0] Time cost=5.339
root: INFO: Epoch[0] Validation-accuracy=0.099881
root: INFO: final accuracy = 0.099881
root: INFO: Epoch[0] Batch [50]	Speed: 7869.73 samples/sec	accuracy=0.123775
root: INFO: Epoch[0] Batch [100]	Speed: 9542.55 samples/sec	accuracy=0.099375
root: INFO: Epoch[0] Batch [150]	Speed: 9407.05 samples/sec	accuracy=0.094219
root: INFO: Epoch[0] Batch [200]	Speed: 8906.41 samples/sec	accuracy=0.100625
root: INFO: Epoch[0] Batch [250]	Speed: 9453.06 samples/sec	accuracy=0.098125
root: INFO: Epoch[0] Batch [300]	Speed: 8874.91 samples/sec	accuracy=0.093281
root: INFO: Epoch[0] Batch [350]	Speed: 6026.26 samples/sec	accuracy=0.104063
root: INFO: Epoch[0] Train-accuracy=0.097656
root: INFO: Epoch[0] Time cost=6.069
root: INFO: Epoch[0] Validation-accuracy=0.099881
root: INFO: final accuracy = 0.099960
root: INFO: Start training with [cpu(0)]
root: INFO: Epoch[0] Batch [50]	Speed: 4614.01 samples/sec	accuracy=0.120938
root: INFO: Epoch[0] Batch [100]	Speed: 6189.65 samples/sec	accuracy=0.096562
root: INFO: Epoch[0] Batch [150]	Speed: 6062.91 samples/sec	accuracy=0.094844
root: INFO: Epoch[0] Batch [200]	Speed: 6710.55 samples/sec	accuracy=0.100312
root: INFO: Epoch[0] Batch [250]	Speed: 5982.40 samples/sec	accuracy=0.099062
root: INFO: Epoch[0] Batch [300]	Speed: 7129.64 samples/sec	accuracy=0.093906
root: INFO: Epoch[0] Batch [350]	Speed: 6555.40 samples/sec	accuracy=0.103750
root: INFO: Epoch[0] Resetting Data Iterator
root: INFO: Epoch[0] Time cost=8.313
root: INFO: Epoch[0] Validation-accuracy=0.099881
root: INFO: final accuracy = 0.099881
root: INFO: Epoch[0] Batch [50]	Speed: 4543.26 samples/sec	accuracy=0.119638
root: INFO: Epoch[0] Batch [100]	Speed: 5423.21 samples/sec	accuracy=0.103750
root: INFO: Epoch[0] Batch [150]	Speed: 5033.73 samples/sec	accuracy=0.092813
root: INFO: Epoch[0] Batch [200]	Speed: 9233.24 samples/sec	accuracy=0.100469
root: INFO: Epoch[0] Batch [250]	Speed: 9242.30 samples/sec	accuracy=0.099375
root: INFO: Epoch[0] Batch [300]	Speed: 10217.41 samples/sec	accuracy=0.093125
root: INFO: Epoch[0] Batch [350]	Speed: 8666.85 samples/sec	accuracy=0.104063
root: INFO: Epoch[0] Train-accuracy=0.092188
root: INFO: Epoch[0] Time cost=7.249
root: INFO: Epoch[0] Validation-accuracy=0.099881
root: INFO: final accuracy = 0.099960
root: INFO: Start training with [cpu(0)]
root: INFO: Epoch[0] Batch [50]	Speed: 8083.13 samples/sec	accuracy=0.102656
root: INFO: Epoch[0] Batch [100]	Speed: 9373.58 samples/sec	accuracy=0.101250
root: INFO: Epoch[0] Batch [150]	Speed: 8239.63 samples/sec	accuracy=0.092969
root: INFO: Epoch[0] Batch [200]	Speed: 8116.80 samples/sec	accuracy=0.101094
root: INFO: Epoch[0] Batch [250]	Speed: 8595.15 samples/sec	accuracy=0.099531
root: INFO: Epoch[0] Batch [300]	Speed: 9090.94 samples/sec	accuracy=0.093906
root: INFO: Epoch[0] Batch [350]	Speed: 9014.57 samples/sec	accuracy=0.103750
root: INFO: Epoch[0] Resetting Data Iterator
root: INFO: Epoch[0] Time cost=5.879
root: INFO: Epoch[0] Validation-accuracy=0.099881
root: INFO: final accuracy = 0.099881
root: INFO: Epoch[0] Batch [50]	Speed: 9343.27 samples/sec	accuracy=0.102635
root: INFO: Epoch[0] Batch [100]	Speed: 8417.44 samples/sec	accuracy=0.095312
root: INFO: Epoch[0] Batch [150]	Speed: 9007.86 samples/sec	accuracy=0.101094
root: INFO: Epoch[0] Batch [200]	Speed: 9894.47 samples/sec	accuracy=0.103125
root: INFO: Epoch[0] Batch [250]	Speed: 9899.44 samples/sec	accuracy=0.100312
root: INFO: Epoch[0] Batch [300]	Speed: 9939.62 samples/sec	accuracy=0.095781
root: INFO: Epoch[0] Batch [350]	Speed: 10021.53 samples/sec	accuracy=0.101250
root: INFO: Epoch[0] Train-accuracy=0.097656
root: INFO: Epoch[0] Time cost=5.316
root: INFO: Epoch[0] Validation-accuracy=0.078521
root: INFO: final accuracy = 0.078425
--------------------- >> end captured logging << ---------------------

[success] 29.22% test_autograd.test_autograd: 68.1240s
[fail] 27.32% test_dtype.test_cifar10: 63.6942s
[success] 21.17% test_bucketing.test_bucket_module: 49.3386s
[success] 14.59% test_mlp.test_mlp: 33.9994s
[success] 7.70% test_conv.test_mnist: 17.9464s
----------------------------------------------------------------------
Ran 5 tests in 237.792s

FAILED (failures=1)
```

## Steps to reproduce
Build and run unit test

**Comment by vdantu** [comment]
I couldn't reproduce this issue, any suggestions on what I should try? Also, how could I look for last time this test failed?


Tested it on CPU.. 


Python environment:
---------------------
**Python 2.7.12** (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Test runs:
----------
(env) :/incubator-mxnet# **MXNET_TEST_COUNT=30000 nosetests --logging-level=DEBUG --verbose -s  tests/python/train/test_dtype.py:test_cifar10**

test_dtype.test_cifar10 ... [00:15:56] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar/train.rec, use 1 threads for decoding..
[00:15:56] src/io/iter_image_recordio_2.cc:228: Load mean image from data/cifar/mean.bin
[00:15:56] src/io/iter_image_recordio_2.cc:246: Load mean image from data/cifar/mean.bin completed
[00:15:57] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar/test.rec, use 1 threads for decoding..
[00:15:57] src/io/iter_image_recordio_2.cc:228: Load mean image from data/cifar/mean.bin
[00:15:57] src/io/iter_image_recordio_2.cc:246: Load mean image from data/cifar/mean.bin completed
/incubator-mxnet/incubator-mxnet/python/mxnet/model.py:1004: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  optimizer=optimizer, initializer=initializer, **kwargs)
/incubator-mxnet/incubator-mxnet/python/mxnet/model.py:591: DeprecationWarning: Calling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.
  self.initializer(k, v)
Start training with [cpu(0)]
Epoch[0] Batch [50]	Speed: 2353.29 samples/sec	accuracy=0.169531
Epoch[0] Batch [100]	Speed: 3413.73 samples/sec	accuracy=0.270000
Epoch[0] Batch [150]	Speed: 3929.30 samples/sec	accuracy=0.323906
Epoch[0] Batch [200]	Speed: 5827.04 samples/sec	accuracy=0.347656
Epoch[0] Batch [250]	Speed: 8605.79 samples/sec	accuracy=0.368750
Epoch[0] Batch [300]	Speed: 7193.14 samples/sec	accuracy=0.380000
Epoch[0] Batch [350]	Speed: 9871.67 samples/sec	accuracy=0.400156
Epoch[0] Resetting Data Iterator
Epoch[0] Time cost=10.354
Epoch[0] Validation-accuracy=0.409019
final accuracy = 0.409019
Epoch[0] Batch [50]	Speed: 6709.95 samples/sec	accuracy=0.183517
Epoch[0] Batch [100]	Speed: 2762.11 samples/sec	accuracy=0.256094
Epoch[0] Batch [150]	Speed: 2599.24 samples/sec	accuracy=0.316719
Epoch[0] Batch [200]	Speed: 4019.71 samples/sec	accuracy=0.352344
Epoch[0] Batch [250]	Speed: 4482.44 samples/sec	accuracy=0.362969
Epoch[0] Batch [300]	Speed: 2311.78 samples/sec	accuracy=0.378125
^[Epoch[0] Batch [350]	Speed: 6287.10 samples/sec	accuracy=0.394375
Epoch[0] Train-accuracy=0.390039
Epoch[0] Time cost=13.991
Epoch[0] Validation-accuracy=0.415843
final accuracy = 0.415565
Start training with [cpu(0)]
Epoch[0] Batch [50]	Speed: 4131.70 samples/sec	accuracy=0.158438
Epoch[0] Batch [100]	Speed: 3603.14 samples/sec	accuracy=0.255469
Epoch[0] Batch [150]	Speed: 3880.94 samples/sec	accuracy=0.309688
Epoch[0] Batch [200]	Speed: 3466.17 samples/sec	accuracy=0.346719
Epoch[0] Batch [250]	Speed: 1907.85 samples/sec	accuracy=0.365625
Epoch[0] Batch [300]	Speed: 13460.59 samples/sec	accuracy=0.377344
Epoch[0] Batch [350]	Speed: 3278.69 samples/sec	accuracy=0.395781
Epoch[0] Resetting Data Iterator
Epoch[0] Time cost=13.526
Epoch[0] Validation-accuracy=0.420985
final accuracy = 0.420985
Epoch[0] Batch [50]	Speed: 2937.12 samples/sec	accuracy=0.171722
Epoch[0] Batch [100]	Speed: 3230.27 samples/sec	accuracy=0.271875
Epoch[0] Batch [150]	Speed: 7009.35 samples/sec	accuracy=0.319844
Epoch[0] Batch [200]	Speed: 7694.27 samples/sec	accuracy=0.345938
Epoch[0] Batch [250]	Speed: 5635.28 samples/sec	accuracy=0.365000
Epoch[0] Batch [300]	Speed: 3673.31 samples/sec	accuracy=0.387344
Epoch[0] Batch [350]	Speed: 1934.83 samples/sec	accuracy=0.399219
Epoch[0] Train-accuracy=0.394531
Epoch[0] Time cost=13.540
Epoch[0] Validation-accuracy=0.419600
final accuracy = 0.418570
[00:17:02] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar/train.rec, use 1 threads for decoding..
[00:17:03] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar/test.rec, use 1 threads for decoding..
Start training with [cpu(0)]
Epoch[0] Batch [50]	Speed: 6886.05 samples/sec	accuracy=0.157344
Epoch[0] Batch [100]	Speed: 2879.89 samples/sec	accuracy=0.242969
Epoch[0] Batch [150]	Speed: 2601.20 samples/sec	accuracy=0.255469
Epoch[0] Batch [200]	Speed: 3848.15 samples/sec	accuracy=0.284531
Epoch[0] Batch [250]	Speed: 5992.76 samples/sec	accuracy=0.293438
Epoch[0] Batch [300]	Speed: 3103.23 samples/sec	accuracy=0.314219
Epoch[0] Batch [350]	Speed: 6909.95 samples/sec	accuracy=0.332344
Epoch[0] Resetting Data Iterator
Epoch[0] Time cost=13.161
Epoch[0] Validation-accuracy=0.352848
final accuracy = 0.352848
Epoch[0] Batch [50]	Speed: 7453.44 samples/sec	accuracy=0.161612
Epoch[0] Batch [100]	Speed: 4445.21 samples/sec	accuracy=0.235469
Epoch[0] Batch [150]	Speed: 3297.28 samples/sec	accuracy=0.266719
Epoch[0] Batch [200]	Speed: 6435.73 samples/sec	accuracy=0.292500
Epoch[0] Batch [250]	Speed: 9299.93 samples/sec	accuracy=0.310625
Epoch[0] Batch [300]	Speed: 2478.55 samples/sec	accuracy=0.323594
Epoch[0] Batch [350]	Speed: 4273.77 samples/sec	accuracy=0.324844
Epoch[0] Train-accuracy=0.309180
Epoch[0] Time cost=10.967
Epoch[0] Validation-accuracy=0.358683
final accuracy = 0.358474
ok

----------------------------------------------------------------------
Ran 1 test in 96.476s

OK

**Comment by vdantu** [comment]
@indhub @marcoabreu  : Do you have any further suggestions to reproduce this issue?

**Comment by marcoabreu** [comment]
I can't find a record of this test failing in the last weeks, sorry (the data is currently not publicly accessible). I think we can close this for now, considering we got no additional data, it's from the old CI system, from October 2017 and your run succeeded 30000 times. 
@indhub wdyt?

**Comment by indhub** [comment]
Given it hasn't failed on the current CI in the last weeks, I agree we can close this.
