### ISSUE TITLE
[R] Bug in mx.nd.one.hot or gan code in example

### ISSUE THREAD

**Issue by q2516581** [apache/incubator-mxnet#8306]
I'm R  woker.
i m testing the GAN net using the R code from the mxnet example, but it has something error.
incubator-mxnet/example/gan/CGAN_mnist_R/CGAN_train.R
when i test 

digit<- mx.nd.array(rep(9, times=batch_size))
data<- mx.nd.one.hot(indices = digit, depth = 10)
#data<- mx.nd.reshape(data = data, shape = c(1,1,-1, batch_size))
it will back 
Error in mx.nd.one.hot(indices = digit, depth = 10) : 
  ./base.h:291: Unsupported parameter type object type for argument indices, expect integer, logical, or string.

i have tried to change digit as a numeric or array, the data will be a null list.
anyone else have tested this examble? plese help me......

**Comment by jeremiedb** [comment]
What version of MXNet package and R are you using? 
I didn't had issue with the following commands in both 0.10.1 (Windows) and 0.11.1 (Ubuntu) : 

```
> library(mxnet)
> digit <- mx.nd.array(rep(1, times=5))
> data <- mx.nd.one.hot(indices = digit, depth = 3)
> data
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    1    1    1    1    1
[3,]    0    0    0    0    0
> class(digit)
[1] "MXNDArray"
```

**Comment by anirudhacharya** [comment]
Error not reproducible. The above code works on the latest master.

@sandeep-krishnamurthy please close this issue.
