### ISSUE TITLE
Error with Python custom operator in distributed training

### ISSUE THREAD

**Issue by pqviet** [apache/incubator-mxnet#8308]
I got the same error "Cannot find custom operator type *"
when running FasterRCNN-like methods with distributed training in multiple machines
+ R-FCN, Deformable-ConvNets
+ MxNet v0.9.5, v0.11.0
+ Ubuntu
Such an error did not appear when running in a single machine even with multiple GPUs.
The above methods use some python custom operators like proposal, proposal_target, ohem...
Rewriting them in C++ or Cuda may solve the problem but we still can't understand why
distributed training can not deal with the operator registry.

**Comment by atticcas** [comment]
Ran in to the same problem.
Did some dive into the code and it seems like something with how MXNet handles distributed computation.

**Comment by pqviet** [comment]
Problem fixed in https://github.com/apache/incubator-mxnet/commit/e27f054b4693b556cddb7f7c262651862ca3d02d
