### ISSUE TITLE
asnumpy is slowly ,how can I speed up it?

### ISSUE THREAD

**Issue by zhangqianghd** [apache/incubator-mxnet#8309]
I use pretrained mod for prediction.I found asnumpy was slowly and took up most of the time.

```
import time
# compute the predict probabilities
now=time.time()
mod.forward(Batch([mx.nd.array(data)]))
mod_output=mod.get_outputs()
print(time.time()-now)

rlt=mod_output[0]
print(time.time()-now)

prob = rlt.asnumpy()
print(time.time()-now)
```
>0.009676933288574219
>0.010257959365844727
>1.285344123840332

in fact ,the rlt dimension is only 16x10
<NDArray 16x10 @cpu(0)>

**Comment by szha** [comment]
The operations are lazy-evaluated, so it's expected for the collection method takes most of the time. You can use the profiler to get the actual time for each backend operation. https://mxnet.incubator.apache.org/versions/master/how_to/perf.html?highlight=profile#profiler

**Comment by zhangqianghd** [comment]
My platform is mac os and install mxnet by pip.

When I add mx profile into the code and run ,I got the following Error.

MXNetError: [13:00:02] src/c_api/c_api.cc:104: Need to compile with USE_PROFILER=1 for MXNet Profiler

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010f365228 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x00000001101ce396 MXSetProfilerConfig + 86
[bt] (2) 2   libffi.6.dylib                      0x000000010cef8884 ffi_call_unix64 + 76
[bt] (3) 3   ???                                 0x00007ffee4735730 0x0 + 140732731184944

**Comment by zhreshold** [comment]
USE_PROFILER is switched off in pre-built packages.
You will need to build from source and enable USE_PROFILER = 1 and build to make it work

**Comment by edmBernard** [comment]
https://github.com/apache/incubator-mxnet/issues/6974

**Comment by zhangqianghd** [comment]
When I add wait_to_read,I have found the detail .
Thanks All.
