### ISSUE TITLE
Bug in ./example/

### ISSUE THREAD

**Issue by squirrel16** [apache/incubator-mxnet#8310]
1. In `/example/ssd/evaluate_net.py`, Line84 DetRecordIter using the default RGB means, not the params set in `/example/ssd/evaluate.py`.
2. In `/example/rcnn/rcnn/symbol/symbol_vgg.py` and `symbol_resnet.py`, all `mx.symbol.contrib.Proposal` need to update to `mx.contrib.symbol.Proposal`.

**Comment by zhreshold** [comment]
Thanks for reporting.

**Comment by zhreshold** [comment]
1. see fix #8352 
2. mx.symbol.contrib == mx.contrib.symbol so it's not a problem now.
