### ISSUE TITLE
There is a bug in metric.py

### ISSUE THREAD

**Issue by miraclewkf** [apache/incubator-mxnet#8315]
In the base `class EvalMetric(object)`, these is a bug in `update_dict` function of this base class:
```
def update_dict(self, label, pred):
        """Update the internal evaluation with named label and pred
        Parameters
        ----------
        labels : OrderedDict of str -> NDArray
            name to array mapping for labels.
        preds : list of NDArray
            name to array mapping of predicted outputs.
        """
        if self.output_names is not None:
            **pred = [pred[name] for name in self.output_names]**
        else:
            pred = list(pred.values())

        if self.label_names is not None:
            **label = [label[name] for name in self.label_names]**
        else:
            label = list(label.values())

        self.update(label, pred)
```
The bug is if `self.output_names` is not None,  `pred = [pred[name] for name in self.output_names]` can't work, because self.output_names is an 'int' object, for example 2, but 'int' object is not iterable

**Comment by jiarenyf** [comment]
... The `output_names` is None (default), or a list when you new a metric class with a arg called output_names ... It can not be a int ...

**Comment by jiarenyf** [comment]
By the way, I found that  nearly no one answer issue questions for a long time ... Is this framework being given up ...
