### ISSUE TITLE
[WIP-NewFeature] ONNX support for MXNet

### ISSUE THREAD

**Issue by Roshrini** [apache/incubator-mxnet#8319]
## Description
Use case is to import pretrained ONNX model and run inference in MXNet and similarly export MXNet model to [ONNX protobuf format](https://github.com/onnx/onnx).

So the idea is:
MXNet will have new module “serde”(temporary module name for serialization/deserialization purpose) which will support only ONNX format for now. (can add other formats later if needed)
And user should be just able to do the following to get MXNet model and parameters:

```
from mxnet.serde import serde
# import from onnx format
sym, params = serde.import_from(protofilepath, 'onnx')

# export to onnx format
protofile = serde.export_to(sym, params, 'onnx')
```
Any concerns or suggestions on this approach?

cc @lupesko @nswamy

**Comment by tqchen** [comment]
I would suggest use nnvm compiler IR as a bridge. http://nnvm.tvmlang.org/ 
It is already mainly based on nnvm with some upgrade discarding existing issues, and there is already support for formats like CoreML, ONNX and so on. Eventually, we want to migrate mxnet's IR directly on top of nnvm compiler, so it makes sense to put most effort on that direction

cc @mli @piiswrong

**Comment by lupesko** [comment]
Thanks @Roshrini for putting this proposal out. I like the simplicity of a single import API and the fact you are thinking ahead about importing additional formats in the future (CoreML anyone?)

Some feedback:
- `sym, params = serde.import_from(onnx_graph, 'onnx')` how does one get the "onnx_graph"? is it using onnx package? can we encapsulate that inside the import function, so the API is simply: `sym, params = serde.import(filePath, 'onnx')` 
- How about export?

@tqchen can you elaborate more about "using nnvm compiler IR as bridge"?

**Comment by tqchen** [comment]
We should do mxnet <-> nnvm compiler IR <-> onnx.

**Comment by Roshrini** [comment]
Thanks @tqchen @lupesko for the feedback

- onnx_graph is generated by using onnx package. Yes we can encapsulate it inside the import function. Updated the issue to show new usage.
- Updated the issue to show export function.

 @tqchen One of the reason to take this approach was that currently not all the operators are supported in nnvm.  Do you have any idea when mxnet's IR will be migrated directly on top of nnvm compiler?

**Comment by nswamy** [comment]
@tqchen I like the idea of having one representation that can be used to translate to different formats. 
However, I think we should give users a way to start importing ONNX models into MXNet and start using it now. 
Also, I think MXNet users do not have to concern themselves with the intermediate representation MXNet uses. I feel this encapsulation is essential at this time.
Longer term I agree that we can hook into the intermediate representation. This will be an implementation detail that we can change.

**Comment by tqchen** [comment]
To clarify, we do not need to wait until mxnet's IR migrated to nnvm compiler to go for this path and we can eanbling it now.  We only have to implement mxnet <- nnvm compiler IR. Note that mxnet->nnvm compiler IR is already supported, as well as onnx->nnvm compiler IR. I also would not dispute the API, the API can remain as it is to the user, while the actual code path go through the way we suggested.

What I want to suggest is to reduce the duplicated engineering effort. In terms of operator coverage mentioned by @Roshrini  Neither onnx or nnvm compiler covers all the operators mxnet support. If there is something missing in nnvm compiler IR, I would suggest simply add it there.

**Comment by mli** [comment]
@Roshrini @nswamy 

I think we already talked about using nnvm as the intermediate step. currently we have `onnx -> nnvm/top` and `mxnet/frontend -> nnvm/top`, then we only need to have the opposite direction done, namely `nnvm/top -> onnx` and `nnvm/top -> mxnet/backend`. 

the reason for not having `onnx -> mxnet/backend` and `mxnet/frontend -> onnx` directly is because 1) need to do things from scratch, 2) mxnet will use `nnvm+tvm` as backend soon

from the users aspect, we can hide it from them. they will not notice the difference between these two approaches.

**Comment by temoc** [comment]
@Roshrini I was wondering what the plans are for exporting an MxNet model to ONNX?
