### ISSUE TITLE
Custom operators with distributed kvstore

### ISSUE THREAD

**Issue by tdomhan** [apache/incubator-mxnet#8321]
## Description

It is currently not possible to run distributed training with `kvstore='dist_async'`, when using custom operators. (details below)

## Environment info (Required)
Python 3 + MXNet compiled with `USE_DIST_KVSTORE =1`

## Build info (Required if built from source)

MXNet compiled with `USE_DIST_KVSTORE =1`

## Steps to reproduce

Use `kvstore='dist_async'` with a network that contains a custom operator registered using `@mx.operator.register("my_custom_op")`.

## Detailed problem description

When using `kvstore='dist_async'` the parameter updates are run on the parameter server. In order to do so the optimizer is pickled and sent to the sever. Among other things the optimizer holds a reference to the symbol (see [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer.py#L104)). Now when the server loads the pickled optimizer object it tries to instantiate the symbol. This works fine only if the symbol does not use any custom object. The reason for this is the following: In order to tell mxnet about custom operators one needs to use the `@mx.operator.register`  annotation. So for the server one would need to first register the class by importing the module containing it and only then start the server. The problem is that the server gets started as soon as mxnet is important, so that one does not have any chance of ever registering the custom operator on the server, see [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/kvstore_server.py#L85).

Ideally one would write the server code something like this:
```
# register op with mxnet
from module_with_custom_op import custom_op
import mxnet.kvstore_server

mxnet.kvstore_server._init_kvstore_server_module()
```
where `mxnet.kvstore_server` no longer automatically starts the server.

## Stack trace
```
Stack trace returned 10 entries:
[bt] (0) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd9558e899c]
[bt] (1) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN5mxnet2op6custom10AttrParserEPN4nnvm9NodeAttrsE+0xc4a) [0x7fd957023d1a]
[bt] (2) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN5mxnet17UpgradeJSON_ParseEN4nnvm5GraphE+0x52e) [0x7fd95719a4ee]
[bt] (3) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7fd95719faa1]
[bt] (4) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x1803) [0x7fd957190473]
[bt] (5) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7fd95719faa1]
[bt] (6) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7fd95894a47c]
[bt] (7) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7fd9575d7259]
[bt] (8) /opt/conda/lib/python3.6/site-packages/mxnet-0.11.1-py3.6.egg/mxnet/libmxnet.so(MXSymbolCreateFromJSON+0x583) [0x7fd9575d0593]
[bt] (9) /opt/conda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7fd9662f4550]

[18:54:23] /opt/mxnet/dmlc-core/include/dmlc/./logging.h:308: [18:54:23] src/operator/custom/custom.cc:78: Check failed: Registry::Get()->Find(params.op_type) != nullptr Cannot find custom operator positional_encodings
```

**Comment by piiswrong** [comment]
We can remove symbol from optimizer

**Comment by piiswrong** [comment]
Here is the fix: https://github.com/apache/incubator-mxnet/pull/8322/files#diff-c445cb799a50a6e48c48d19a1ef37d3bR104

**Comment by tdomhan** [comment]
oh wow, awesome, that was fast! I'll give the fix a try.

**Comment by tdomhan** [comment]
I can confirm that this fixes the issue. Thanks a lot! While testing I ran into a python 3 compatibility issue. Here's a fix for that:
https://github.com/apache/incubator-mxnet/pull/8334 

I'll close the issue now.
