### ISSUE TITLE
ndarray issue

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#8330]
I just test ndarray in if case.

import find_mxnet
import mxnet as mx

a = mx.nd.array([[4, 9, 1], [16, 25, 49]])
b = a*(a > 2)

print a.asnumpy()
print b.asnumpy()

why the result b is the same as a?

I think the result b should be
4 9 0
16 25 49
because 1 is less than 2

**Comment by szha** [comment]
Works on my laptop. I'm building from source on OSX.
```python
In [1]: import mxnet as mx

In [2]: a = mx.nd.array([[4, 9, 1], [16, 25, 49]])

In [3]: a
Out[3]:

[[  4.   9.   1.]
 [ 16.  25.  49.]]
<NDArray 2x3 @cpu(0)>

In [4]: b = a*(a > 2)

In [5]: b
Out[5]:

[[  4.   9.   0.]
 [ 16.  25.  49.]]
<NDArray 2x3 @cpu(0)>

In [6]: mx.__version__
Out[6]: '0.12.0'
```

**Comment by liumilan** [comment]
there is a bug in 0.7.0,
So how can i modify the code if i would not like to  upgrade to the latest version?

**Comment by liumilan** [comment]
where is the implementation about ndarray > in mxnet code? @szha

**Comment by szha** [comment]
Here's the path for CPU broadcast_greater.
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/ndarray/ndarray.py#L293-L295

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/ndarray/ndarray.py#L2637-L2697

https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/elemwise_binary_broadcast_op_logic.cc#L67-L83

https://github.com/apache/incubator-mxnet/blob/master/src/operator/mshadow_op.h#L613-L618
