### ISSUE TITLE
SqueezeNet pretrained model download link not working

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8332]
The link http://data.dmlc.ml/mxnet/models/imagenet/squeezenet/squeezenet_v1.0.tar.gz for squeezenet model is not working. Please upload the squeezenet model

**Comment by zhreshold** [comment]
There's no more tarball files. The weights and json files are available as 
http://data.dmlc.ml/mxnet/models/imagenet/squeezenet/squeezenet_v1.0-0000.params
http://data.dmlc.ml/mxnet/models/imagenet/squeezenet/squeezenet_v1.0-symbol.json

**Comment by chowkamlee81** [comment]
Thanks zhreshold.. got the model and json file.. Closing the issue
