### ISSUE TITLE
Building with libjpeg-turbo error

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#8336]
## Description
I've installed libjpeg-turbo by "sudo apt install libjpeg-turbo8-dev" on Ubuntu 16.04

## Environment info (Required)

```
MXNet-master on Ubuntu 16.04
```

## Error Message:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:384: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
```

## Minimum reproducible example
Just set USE_LIBJPEG_TURBO = 1 and type "make -j"

**Comment by ptrendx** [comment]
Yes, unfortunately libjpeg-turbo version available in Ubuntu package compiles turbojpeg only as a static library (turbojpeg.a) instead of dynamic library (turbojpeg.so). You need to compile libjpeg-turbo from source. For system-wide installation you can use this:
```
apt-get install autoconf automake libtool nasm
JPEG_TURBO_VERSION=1.5.2 && \
wget -q -O - https://github.com/libjpeg-turbo/libjpeg-turbo/archive/${JPEG_TURBO_VERSION}.tar.gz | tar -xzf - && \
cd libjpeg-turbo-${JPEG_TURBO_VERSION} && \
autoreconf -fiv && \
./configure --enable-shared --prefix=/usr 2>&1 >/dev/null && \
make -j"$(nproc)" install 2>&1 >/dev/null && \
rm -rf libjpeg-turbo-${JPEG_TURBO_VERSION}
```
Then you need to set `USE_LIBJPEG_TURBO_PATH` in `config.mk` to `/usr`

**Comment by ptrendx** [comment]
Actually, it seems there is ubuntu package that ships `libturbojpeg.so`: it is called `libturbojpeg`. Still, compiling from source will give you newer version (1.5.2 vs 1.4.2).

**Comment by chinakook** [comment]
OK
