### ISSUE TITLE
Incorrect implied shape inside loss function

### ISSUE THREAD

**Issue by nickeleres** [apache/incubator-mxnet#8350]
Ive seen this brought up in a couple other issues, but it hasnt been resolved as far as I know.  

The data I am feeding into my loss function is of the following shape (batch size 32):

```
output.shape (32L, 51L)
label.shape (32L, 51L)
```

When the `output` and `label` are fed into the loss function, tho, I get the following error:

`MXNetError: Shape inconsistent, Provided=(32,51), inferred shape=(32,1)`

Why is the loss function implying an incorrect shape?  In the line above said loss function, Gluon knows the correct shape of each input matrix, but the loss function auto-implies the shape incorrectly.

**Comment by nickeleres** [comment]
@pluskid closed a similar unresolved issue

https://github.com/apache/incubator-mxnet/issues/880

**Comment by nickeleres** [comment]
When I reshaped my label to (32, 1), as the error message stated, I got the training to run, but the alignment between the output batch and the associated label makes no sense...There is now a single label for an entire batch.

**Comment by zhreshold** [comment]
Please post your custom loss function

**Comment by nickeleres** [comment]
No custom loss function

`loss = softmax_cross_entropy(output, label)`

It looks like the `SoftmaxCrossEntropyLoss` demo works the same way...

```
data.shape (32L, 784L)
label.shape (32L,)
output.shape (32L, 10L)
```

My labels are one-hot 1 tensors...so it appears that the 0 entry for each label tensor in the batch is used as the label for every training example in the batch, which doesnt make sense to me.

**Comment by nickeleres** [comment]
When I decrease the batch size to 1, the training labels are simply integers **(the 0th entry in the one-hot array for each actual label)**, confirming my above assumption....

**Comment by zhreshold** [comment]
You can use gluon.loss.SoftmaxCrossEntropyLoss, where you can specify `from_logits=True` to use one_hot labels.

**Comment by nickeleres** [comment]
This is my new loss function:

`softmax_cross_entropy = gluon.loss.SoftmaxCrossEntropyLoss(from_logits=True)`

And Im still getting:

`MXNetError: Shape inconsistent, Provided=(32,51), inferred shape=(32,1)`

**Comment by nickeleres** [comment]
I had to set `sparse_label=False` in my loss function, which now looks like:

`gluon.loss.SoftmaxCrossEntropyLoss(sparse_label=False, from_logits=True)`

**Comment by zhreshold** [comment]
@nickeleres  Just to mention that what I meant is sparse_label=False, from_logits is used if log_softmax is applied prior to the loss function.

**Comment by nickeleres** [comment]
Ok.  So what is the explicit correct loss function for one-hot labels?

**Comment by zhreshold** [comment]
gluon.loss.SoftmaxCrossEntropyLoss(sparse_label=False)

**Comment by nickeleres** [comment]
Awesome, thank you so much
