### ISSUE TITLE
How to add NNVM operator with auxiliary states

### ISSUE THREAD

**Issue by yuewu001** [apache/incubator-mxnet#8354]
When adding new operators with auxiliary states, how to set the attributes with NNVM_REGISTER_OP ?

**Comment by zheng-da** [comment]
You can use nnvm::FMutateInputs to specify auxiliary states. The link below shows an example.
https://github.com/zheng-da/incubator-mxnet/blob/refactor/src/operator/nn/batch_norm.cc#L448

**Comment by yuewu001** [comment]
thanks a lot
