### ISSUE TITLE
Wrong argument in mpi tracker

### ISSUE THREAD

**Issue by xcgoner** [apache/incubator-mxnet#8355]
In  dmlc-core/tracker/dmlc_tracker/mpi.py, line 72:
prog = 'mpiexec -n %d %s %s' % (nworker, get_mpi_env(pass_envs), cmd)

"nworker" should be "nserver"

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by vandanavk** [comment]
PR created https://github.com/dmlc/dmlc-core/pull/437

**Comment by vandanavk** [comment]
@xcgoner 
The change has been merged. Please verify if this issue can be closed. Thanks.
@marcoabreu
