### ISSUE TITLE
Difficulty installing mxnet

### ISSUE THREAD

**Issue by eckyu** [apache/incubator-mxnet#8356]
Hi, I am having difficulty in installing the mxnet R package on BERT console for interfacing with Excel, and am wondering if you can offer some guidance...

I am using a 32-bit Excel, and have installed the BERT Excel tool from ( https://bert-toolkit.com/ ).  I then proceeded to install the mxnet package with the lines below...

cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")

Then I receive the message saying..

Package which is only available in source form, and may need compilation
  of C/C++/Fortran: 'mxnet'
  These will not be installed

I then tried a different set of lines...

install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

Which appeared to be working, but then had the following messages when I tried library("mxnet")...

Error in library("mxnet") : there is no package called 'mxnet'
In addition: Warning message:
package 'mxnet' is not available (for R version 3.4.1) 

I also tried installing mxnet in R Studio on Mac, and I got the an error message advising that i tis not installed for arch i386.  Presumably it means 32-bit systems?

I am wondering if anyone experienced this before?  

Thanks.

**Comment by eckyu** [comment]
Hi, a quick update...  

On BERT Console.., I tried...

install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)

And I got the below error message...

Error: package 'mxnet' is not installed for 'arch = i386'

Which is similar to the error I got on Mac...

Am wondering if anyone knows how I can get round this?

Thanks, Eric.

**Comment by jeremiedb** [comment]
The issue is, like you suspected, that only 64-bit installation is supported right now. Could be a good pretext to move to 64 bit:)

**Comment by thirdwing** [comment]
As @jeremiedb  said, we only provide the 64-bit installation now.
