### ISSUE TITLE
'module' object has no attribute 'nd'

### ISSUE THREAD

**Issue by QQQYang** [apache/incubator-mxnet#8358]
## Description
'module' object has no attribute 'nd' when run command `python mxnet.py`, while a short MXNet python program for validating MXNet Installation runs successfully in terminal.

## Environment info (Required)
system: ubuntu 14.04
mxnet version: 0.11.0
```
----------Python Info----------
('Version      :', '2.7.6')
('Compiler     :', 'GCC 4.8.4')
('Build        :', ('default', 'Oct 26 2016 20:30:19'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet')
Traceback (most recent call last):
  File "diagnose.py", line 108, in check_mxnet
    with open(commit_hash, 'r') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/COMMIT_HASH'

----------System Info----------
('Platform     :', 'Linux-4.4.0-96-generic-x86_64-with-Ubuntu-14.04-trusty')
('system       :', 'Linux')
('node         :', 'ubuntu-1')
('release      :', '4.4.0-96-generic')
('version      :', '#119~14.04.1-Ubuntu SMP Wed Sep 13 08:40:48 UTC 2017')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Stepping:              3
CPU MHz:               3825.625
BogoMIPS:              8016.72
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0913 sec, LOAD: 1.2602 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0433 sec, LOAD: 1.7848 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0788 sec, LOAD: 1.2096 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0423 sec, LOAD: 0.9959 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0044 sec, LOAD: 0.4337 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>, DNS finished in 0.0764639377594 sec.



```

Package used (Python/R/Scala/Julia):
I'm using Python.

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
gcc

Build config:
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1

## Error Message:
Traceback (most recent call last):
  File "mxnet/mxnet.py", line 1, in <module>
    import mxnet as mx
  File "/home/qy/documents/PythonPrj/mxnet/mxnet.py", line 3, in <module>
    a = mx.nd.array([1, 2, 3])
AttributeError: 'module' object has no attribute 'nd'

## Details

After installing mxnet, I run the official test sample in terminal as below:
```
import mxnet as mx
a = mx.nd.ones((2, 3), mx.gpu())
b = a * 2 + 1
b.asnumpy()
```
Everything is okay. However, when I write these code to python file `mxnet.py`, and run `python mxnet.py`., it returned the mentioned error.
It seems that it didn't find mxnet library.

**Comment by Hanbo-Sun** [comment]
I met the same issue.

**Comment by 3bhady** [comment]
i have the same issue , let us know if you've solved it

**Comment by QQQYang** [comment]
@Hanbo-Sun @3bhady As for my case, it resulted from the filename which is the same with mxnet library. So when I tried to import mxnet library, what I imported actually is my own mxnet.py. Renaming the python file helped me solve the issue.

**Comment by Hanbo-Sun** [comment]
@QQQYang Thank you! :)
Same thing.

**Comment by 3bhady** [comment]
@QQQYang Thanks for replying, glad you solved yours.
But sadly this isn't the case for me i get this error on the validating program also.

**Comment by wentlei** [comment]
I have met the same question. So kindly u r,pls share with us if u have solve it.

**Comment by 3bhady** [comment]
@wentlei have you checked this?

> @Hanbo-Sun @3bhady As for my case, it resulted from the filename which is the same with mxnet library. So when I tried to import mxnet library, what I imported actually is my own mxnet.py. Renaming the python file helped me solve the issue.

**Comment by wentlei** [comment]
@3bhady  Thanks for your reply. Yes , I have renamed my python file, and I haven't encountered this problem yet. It may caused by a conflict which the filename is the same with mxnet library as u mentioned.

**Comment by pilhoon** [comment]
I just reinstalled mxnet, and this was fixed.
try,
`pip install -U mxnet-cu90` or (`pip install -U mxnet`). Don’t miss the `U` flag.
