### ISSUE TITLE
MXNet training slowing down after several epochs (inception_bn with 1 million images)

### ISSUE THREAD

**Issue by MaJieCornell** [apache/incubator-mxnet#8366]
Hi,

I encounter the training speed slowing down issue during my model training.

Specifically, I am using P2.16xlarge of Amazon EC2 instance to train an inception_bn network with 1 million of images. The AMI I am using is "Deep Learning AMI Amazon Linux Version 3.3_Oct2017", the version of MXNet is 0.11.0.

The training speed keep going down after around 5 epochs. Here are some example logs:

INFO:root:Epoch[6] Batch [420]  Speed: 490.41 samples/sec       accuracy=0.479903
INFO:root:Epoch[6] Batch [430]  Speed: 486.56 samples/sec       accuracy=0.479966
INFO:root:Epoch[6] Batch [440]  Speed: 497.60 samples/sec       accuracy=0.480021
INFO:root:Epoch[6] Batch [450]  Speed: 492.58 samples/sec       accuracy=0.480291
INFO:root:Epoch[6] Batch [460]  Speed: 528.04 samples/sec       accuracy=0.480422
INFO:root:Epoch[6] Batch [470]  Speed: 464.52 samples/sec       accuracy=0.480718
INFO:root:Epoch[6] Batch [480]  Speed: 484.11 samples/sec       accuracy=0.480919
INFO:root:Epoch[6] Batch [490]  Speed: 484.18 samples/sec       accuracy=0.480966
INFO:root:Epoch[6] Batch [500]  Speed: 495.10 samples/sec       accuracy=0.481116
INFO:root:Epoch[6] Batch [510]  Speed: 486.60 samples/sec       accuracy=0.481291
INFO:root:Epoch[6] Batch [520]  Speed: 484.40 samples/sec       accuracy=0.481406
INFO:root:Epoch[6] Batch [530]  Speed: 491.89 samples/sec       accuracy=0.481499
INFO:root:Epoch[6] Batch [540]  Speed: 489.70 samples/sec       accuracy=0.481537
INFO:root:Epoch[6] Batch [550]  Speed: 498.87 samples/sec       accuracy=0.481486
INFO:root:Epoch[6] Batch [560]  Speed: 491.44 samples/sec       accuracy=0.481388
INFO:root:Epoch[6] Batch [570]  Speed: 496.57 samples/sec       accuracy=0.481283
INFO:root:Epoch[6] Batch [580]  Speed: 498.24 samples/sec       accuracy=0.481148
INFO:root:Epoch[6] Batch [590]  Speed: 496.46 samples/sec       accuracy=0.481292
INFO:root:Epoch[6] Batch [600]  Speed: 502.20 samples/sec       accuracy=0.481486
INFO:root:Epoch[6] Batch [610]  Speed: 493.88 samples/sec       accuracy=0.481719
INFO:root:Epoch[6] Batch [620]  Speed: 487.72 samples/sec       accuracy=0.481916
INFO:root:Epoch[6] Batch [630]  Speed: 492.16 samples/sec       accuracy=0.482013
INFO:root:Epoch[6] Batch [640]  Speed: 490.07 samples/sec       accuracy=0.482199
INFO:root:Epoch[6] Batch [650]  Speed: 496.52 samples/sec       accuracy=0.482236
INFO:root:Epoch[6] Batch [660]  Speed: 488.37 samples/sec       accuracy=0.482194
INFO:root:Epoch[6] Batch [670]  Speed: 489.15 samples/sec       accuracy=0.482369
INFO:root:Epoch[6] Batch [680]  Speed: 486.11 samples/sec       accuracy=0.482336
INFO:root:Epoch[6] Batch [690]  Speed: 487.78 samples/sec       accuracy=0.482385
INFO:root:Epoch[6] Batch [700]  Speed: 488.26 samples/sec       accuracy=0.482207
INFO:root:Epoch[6] Batch [710]  Speed: 483.65 samples/sec       accuracy=0.482353
INFO:root:Epoch[6] Batch [720]  Speed: 488.62 samples/sec       accuracy=0.482530
INFO:root:Epoch[6] Batch [730]  Speed: 492.90 samples/sec       accuracy=0.482764
INFO:root:Epoch[6] Batch [740]  Speed: 485.88 samples/sec       accuracy=0.483002
INFO:root:Epoch[6] Batch [750]  Speed: 487.54 samples/sec       accuracy=0.483150
INFO:root:Epoch[6] Batch [760]  Speed: 489.82 samples/sec       accuracy=0.483384
INFO:root:Epoch[6] Batch [770]  Speed: 481.67 samples/sec       accuracy=0.483433
INFO:root:Epoch[6] Batch [780]  Speed: 491.70 samples/sec       accuracy=0.483405
INFO:root:Epoch[6] Batch [790]  Speed: 482.48 samples/sec       accuracy=0.483634
INFO:root:Epoch[6] Batch [800]  Speed: 488.26 samples/sec       accuracy=0.483785
INFO:root:Epoch[6] Batch [810]  Speed: 486.53 samples/sec       accuracy=0.483826
INFO:root:Epoch[6] Batch [820]  Speed: 478.62 samples/sec       accuracy=0.483890
INFO:root:Epoch[6] Batch [830]  Speed: 478.11 samples/sec       accuracy=0.484072
INFO:root:Epoch[6] Batch [840]  Speed: 484.99 samples/sec       accuracy=0.484117
INFO:root:Epoch[6] Batch [850]  Speed: 478.26 samples/sec       accuracy=0.484237
INFO:root:Epoch[6] Batch [860]  Speed: 482.54 samples/sec       accuracy=0.484493
INFO:root:Epoch[6] Batch [870]  Speed: 479.48 samples/sec       accuracy=0.484404
...
...
INFO:root:Epoch[47] Batch [240] Speed: 334.17 samples/sec       accuracy=0.916478
INFO:root:Epoch[47] Batch [250] Speed: 335.57 samples/sec       accuracy=0.916451
INFO:root:Epoch[47] Batch [260] Speed: 333.79 samples/sec       accuracy=0.916337
INFO:root:Epoch[47] Batch [270] Speed: 334.70 samples/sec       accuracy=0.916426
INFO:root:Epoch[47] Batch [280] Speed: 332.91 samples/sec       accuracy=0.916433
INFO:root:Epoch[47] Batch [290] Speed: 333.09 samples/sec       accuracy=0.916304
INFO:root:Epoch[47] Batch [300] Speed: 333.47 samples/sec       accuracy=0.916262
INFO:root:Epoch[47] Batch [310] Speed: 332.90 samples/sec       accuracy=0.916235
INFO:root:Epoch[47] Batch [320] Speed: 330.95 samples/sec       accuracy=0.916241
INFO:root:Epoch[47] Batch [330] Speed: 332.39 samples/sec       accuracy=0.916210
INFO:root:Epoch[47] Batch [340] Speed: 332.93 samples/sec       accuracy=0.916016
INFO:root:Epoch[47] Batch [350] Speed: 332.01 samples/sec       accuracy=0.915943
INFO:root:Epoch[47] Batch [360] Speed: 332.62 samples/sec       accuracy=0.915826
INFO:root:Epoch[47] Batch [370] Speed: 332.01 samples/sec       accuracy=0.915958
INFO:root:Epoch[47] Batch [380] Speed: 331.88 samples/sec       accuracy=0.916082
INFO:root:Epoch[47] Batch [390] Speed: 331.62 samples/sec       accuracy=0.916041
INFO:root:Epoch[47] Batch [400] Speed: 331.34 samples/sec       accuracy=0.916152
INFO:root:Epoch[47] Batch [410] Speed: 331.10 samples/sec       accuracy=0.916344
INFO:root:Epoch[47] Batch [420] Speed: 331.38 samples/sec       accuracy=0.916521
INFO:root:Epoch[47] Batch [430] Speed: 330.01 samples/sec       accuracy=0.916437
INFO:root:Epoch[47] Batch [440] Speed: 329.00 samples/sec       accuracy=0.916503
INFO:root:Epoch[47] Batch [450] Speed: 330.19 samples/sec       accuracy=0.916592
INFO:root:Epoch[47] Batch [460] Speed: 328.81 samples/sec       accuracy=0.916715
INFO:root:Epoch[47] Batch [470] Speed: 328.26 samples/sec       accuracy=0.916729
INFO:root:Epoch[47] Batch [480] Speed: 328.83 samples/sec       accuracy=0.916722
INFO:root:Epoch[47] Batch [490] Speed: 328.94 samples/sec       accuracy=0.916557
INFO:root:Epoch[47] Batch [500] Speed: 328.48 samples/sec       accuracy=0.916616
INFO:root:Epoch[47] Batch [510] Speed: 328.63 samples/sec       accuracy=0.916623
INFO:root:Epoch[47] Batch [520] Speed: 328.70 samples/sec       accuracy=0.916585
INFO:root:Epoch[47] Batch [530] Speed: 327.73 samples/sec       accuracy=0.916667
INFO:root:Epoch[47] Batch [540] Speed: 326.74 samples/sec       accuracy=0.916669
INFO:root:Epoch[47] Batch [550] Speed: 327.39 samples/sec       accuracy=0.916632
INFO:root:Epoch[47] Batch [560] Speed: 327.91 samples/sec       accuracy=0.916656
INFO:root:Epoch[47] Batch [570] Speed: 327.19 samples/sec       accuracy=0.916720
INFO:root:Epoch[47] Batch [580] Speed: 326.79 samples/sec       accuracy=0.916668
INFO:root:Epoch[47] Batch [590] Speed: 326.28 samples/sec       accuracy=0.916710
INFO:root:Epoch[47] Batch [600] Speed: 325.61 samples/sec       accuracy=0.916744
INFO:root:Epoch[47] Batch [610] Speed: 326.42 samples/sec       accuracy=0.916776
INFO:root:Epoch[47] Batch [620] Speed: 326.10 samples/sec       accuracy=0.916758
INFO:root:Epoch[47] Batch [630] Speed: 325.54 samples/sec       accuracy=0.916842
INFO:root:Epoch[47] Batch [640] Speed: 326.44 samples/sec       accuracy=0.916777
INFO:root:Epoch[47] Batch [650] Speed: 324.77 samples/sec       accuracy=0.916733
INFO:root:Epoch[47] Batch [660] Speed: 324.26 samples/sec       accuracy=0.916772
INFO:root:Epoch[47] Batch [670] Speed: 324.54 samples/sec       accuracy=0.916740
INFO:root:Epoch[47] Batch [680] Speed: 326.14 samples/sec       accuracy=0.916713

Even though the training haven't finished, the speed now is even slower than I used a P2.8xlarge which just have 8 GPUs to train the net (~330 samples/sec). 

Is there anybody looking into this issue? If you need any more information, please let me know

Thanks beforehand.

**Comment by reminisce** [comment]
Does the symptom exist in using fewer GPUs? What type of kvstore did you use?

**Comment by MaJieCornell** [comment]
This issue disappear when I restart the training, will keep tracking of this behavior. Close the issue for now.
