### ISSUE TITLE
How to change the input of a symbol when it is loaded from .json file?

### ISSUE THREAD

**Issue by GengZ** [apache/incubator-mxnet#8367]
## Description
Just convert a caffe model to a .json file and a .param file. 
Load the converted symbol with mx.model.load_checkpoint(A, B). Name the input of that symbol _Variable A_.
Now I want to **change** the **input** of the loaded symbol to another symbol named _Variable B_. 
What should I do?

Or is there a simple way to just get the **symbol.py** file?

Thanks in advance. 

## What have you tried to solve it?

1. Delete the input directly in .json file does not work...

**Comment by zhreshold** [comment]
If you mean given a graph A<--B<--C<--D, you want a new graph like B<--C<--D then it's a bit tricky. You will need some knowledge of graph traverse and parse the json file and rewrite a new graph.

**Comment by GengZ** [comment]
@zhreshold Given graph A -> B -> C -> D (from A to D), to get A -> B -> C, get_internals()will work. But as for change the input A, I got no reference...

**Comment by zhreshold** [comment]
A quick solution is to traverse back using sym.get_children(), until you reach B, and composing symbols starting from B.

**Comment by vrakesh** [comment]
@GengZ Has your question been answered? If so requesting you close this issue.
