### ISSUE TITLE
How to use val.rec file to produce 144crops

### ISSUE THREAD

**Issue by shipeng-uestc** [apache/incubator-mxnet#8381]
Hi, I am reading [Going deeper with convolutions](https://arxiv.org/abs/1409.4842),in Chapter 7 ,it mentioned 144crops,I think how to use val.rec to produce it .
      Now,I don't know how to code it by python and mxnet.
      Anyone can help me ,or give me some informations.
      Thanks.

**Comment by solin319** [comment]
https://github.com/apache/incubator-mxnet/tree/master/example/image-classification

The file 'common/data.py' may help you.

**Comment by zhreshold** [comment]
You can checkout mx.image as well.
