### ISSUE TITLE
Does gluon have a crop layer (like caffe crop layer) ? 

### ISSUE THREAD

**Issue by qiliux** [apache/incubator-mxnet#8386]
Package used (Python/R/Scala/Julia):
(I'm using ...)
Python

## What have you tried to solve it?

1. look at the gluon document.
2. look at the gluon source code.

**Comment by zhreshold** [comment]
mx.nd.slice is probably what you need if you are simply using gluon blocks.
http://mxnet.incubator.apache.org/api/python/ndarray.html?highlight=slice#mxnet.ndarray.slice

**Comment by qiliux** [comment]
@zhreshold Yeah, i have found it. However, how to use it with gluon ? I know it  can be used with the  symbol way.
```
net = nn.Sequential()
with net.name_scope():
    net.add(vgg_stack(architecture))
    net.add(nn.Flatten())
    ...
    how to use slice here???
```

**Comment by chinakook** [comment]
Use "class MyNet(nn.Block):" style

**Comment by qiliux** [comment]
Summary design your own gluon layer:
 ```
class CenteredLayer(Block):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)

    def forward(self, x):
         mx.nd.slice(x,..)
```
