### ISSUE TITLE
nd.concat with empty array throws error

### ISSUE THREAD

**Issue by SumNeuron** [apache/incubator-mxnet#8393]
So I want to initialize an empty array and throw some data in it over a training loop.
However, doing so causes a very odd error:

dumb = nd.array([])
another = nd.array([1])
nd.concat(dumb, another, dim=0)

throws an error

dumb = nd.array([1])
another = nd.array([1])
nd.concat(dumb, another, dim=0)

does not.

How do I get around this

**Comment by reminisce** [comment]
MXNet does not support empty arrays. An array of empty shape means the shape is unknown and must be inferred from other sources. In that case, the memory allocation is deferred until the shape is known; otherwise, an error message will be printed.

Could you describe your use case in detail to see if we could accommodate the need in another way?

**Comment by lebeg** [comment]
I had approximately the same issue and I've overcome it by initializing 1d vector along the axis I want to concatenate on and then slicing it off. Something like:

```
dumb = nd.array([1])
another = nd.array([1])
nd.concat(dumb, another, dim=0)
nd.slice(dumb, begin=(1, 0), end(2, 1), dim=0)
```

**Comment by lebeg** [comment]
For me the use case was that I've had to construct the tensor in a loop, row by row and therefore I would want to initialize it empty at first (partially specifying the shape).

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@sandeep-krishnamurthy please add 'HowTo' to this topic

**Comment by ThomasDelteil** [comment]
@SumNeuron does the explanation from @lebeg and @reminisce make sense to you? If not please consider creating a post on https://discuss.mxnet.io to follow up.

@nswamy could you please close the issue? Thanks!
