### ISSUE TITLE
How to include Negative samples/images for training

### ISSUE THREAD

**Issue by navneet1083** [apache/incubator-mxnet#8394]
How to add negative samples while training. If i have my own datasets for 2 classes (e.g laptop and tvmonitor) and i have to include negative images/samples (which are not laptop and tvmonitor) then how should i add those images in configuration or in labels config.

Reason being to put this forward is after trained fully my network recognises window screen (with cover and some dim sunlight) as tvmonitor so i need to feed some negative samples to overcome this issue.

Or kindly suggest me some alternative to overcome this issue.

**Comment by qiliux** [comment]
You can use some other type images to a third class. 
Then use `im2rec` tool to make the dataset.

**Comment by navneet1083** [comment]
@qiliux - I tried that but overall accuracies is going down. Also the number of negative images i need to increase but still the accuracies is not going up. Also the number of classes will increase (i meant need to put if-else condition; basically not to display). 
Is there any way to somehow lower down/increase the overtrained losses for each class by putting negative samples ? Or any research papers associated with this kind-of approach (did google but in vain)

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
