### ISSUE TITLE
A3C with multiple workers

### ISSUE THREAD

**Issue by moakra** [apache/incubator-mxnet#8397]
Hi,

When I run the a3c from this [repo](https://github.com/apache/incubator-mxnet/tree/master/example/reinforcement-learning/a3c) using the file launcher.py, it can specify the number of workers. When I specify more than 1, I get the error:
no module named dmlc_tracker

I checked this [closed issue](https://github.com/apache/incubator-mxnet/issues/3611) and tried to add

sys.path.insert(0, "your/mxnet/python/")

before importing mxnet but the problem is still the same.

Do you have any suggestion about this problem ?

Thank you!

Med

**Comment by anirudh2290** [comment]
@moakra As this script prepends OS.ENVIRON['HOME'] to the sys.path (https://github.com/apache/incubator-mxnet/blob/master/example/reinforcement-learning/a3c/launcher.py#L30), I would suggest either installing mxnet in the home directory (/home/<YOUR_ALIAS>) or changing the environment variable HOME temporarily by doing export HOME=<PATH_TO_DIRECTORY_CONTAINING_MXNET>

**Comment by moakra** [comment]
@anirudh2290 thank you. I changed the environment variable.

Now, when I run:

python2 launcher.py -n 2 --gpus=0 python2 a3c.py

I see 5 processes with nvidia-smi. It is supposed to be 2 only. Doesn't it ? Is this normal ?

**Comment by anirudh2290** [comment]
@moakra 5 processes are expected. 1 Parent process, 4 child processes, 2 workers and 2 servers.

**Comment by moakra** [comment]
Thank you @anirudh2290 !
