### ISSUE TITLE
 ImageIter save labels as float32, which meight cause numerical precision problem

### ISSUE THREAD

**Issue by akturtle** [apache/incubator-mxnet#8405]
https://github.com/apache/incubator-mxnet/blob/87068e6df91ed9b2fdbcffa4d6a83e318c002247/python/mxnet/image/image.py#L1076

This will convert the labels into the data type of float32 which has significand precision of 24 bits. When some labels are large integers (out of [-16777216,16777216] ), it will face precision limits.  An example I have met is that, when the label is 16777232, it will be changed to 167777233 after saved to imglist. It takes me a lot of time to find what's wrong.  I suggest to change float to int, or give some notice

**Comment by zhreshold** [comment]
@piiswrong Suggestion?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by b0noI** [comment]
Suggested tags: "Bug"

**Comment by vandanavk** [comment]
@akturtle could you share the dataset and/or scripts that you used?
