### ISSUE TITLE
Find models' definition of "python" style in Model Zoo in Gluon Package

### ISSUE THREAD

**Issue by Yochengliu** [apache/incubator-mxnet#8408]
How can I get the model's python definition in Gluon Package? Not only json file. For example, for vgg16 as: 

------------------------------------------------------------------------------------------------------
def vgg16_symbol():
    data = mx.sym.Variable('data')
    
    # conv1
    conv1_1 = mx.sym.Convolution(data=data, kernel=(3, 3), pad=(1, 1), num_filter=64, name="conv1_1")
    relu1_1 = mx.sym.Activation(data=conv1_1, act_type="relu", name="relu1_1")
    conv1_2 = mx.sym.Convolution(data=relu1_1, kernel=(3, 3), pad=(1, 1), num_filter=64, name="conv1_2")
    relu1_2 = mx.sym.Activation(data=conv1_2, act_type="relu", name="relu1_2")
    pool1   = mx.sym.Pooling(data=relu1_2, kernel=(2, 2), stride=(2, 2), pool_type="max", name="pool1")
    
    # conv2
    conv2_1 = mx.sym.Convolution(data=pool1, kernel=(3, 3), pad=(1, 1), num_filter=128, name="conv2_1")
    relu2_1 = mx.sym.Activation(data=conv2_1, act_type="relu", name="relu2_1")
    conv2_2 = mx.sym.Convolution(data=relu2_1, kernel=(3, 3), pad=(1, 1), num_filter=128, name="conv2_2")
    relu2_2 = mx.sym.Activation(data=conv2_2, act_type="relu", name="relu2_2")
    pool2   = mx.sym.Pooling(data=relu2_2, kernel=(2, 2), stride=(2, 2), pool_type="max", name="pool2")
    
    # conv3
    conv3_1 = mx.sym.Convolution(data=pool2, kernel=(3, 3), pad=(1, 1), num_filter=256, name="conv3_1")
    relu3_1 = mx.sym.Activation(data=conv3_1, act_type="relu", name="relu3_1")
    conv3_2 = mx.sym.Convolution(data=relu3_1, kernel=(3, 3), pad=(1, 1), num_filter=256, name="conv3_2")
    relu3_2 = mx.sym.Activation(data=conv3_2, act_type="relu", name="relu3_2")
    conv3_3 = mx.sym.Convolution(data=relu3_2, kernel=(3, 3), pad=(1, 1), num_filter=256, name="conv3_3")
    relu3_3 = mx.sym.Activation(data=conv3_3, act_type="relu", name="relu3_3")
    pool3   = mx.sym.Pooling(data=relu3_3, kernel=(2, 2), stride=(2, 2), pool_type="max", name="pool3")
    
    # conv4
    conv4_1 = mx.sym.Convolution(data=pool3, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv4_1")
    relu4_1 = mx.sym.Activation(data=conv4_1, act_type="relu", name="relu4_1")
    conv4_2 = mx.sym.Convolution(data=relu4_1, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv4_2")
    relu4_2 = mx.sym.Activation(data=conv4_2, act_type="relu", name="relu4_2")
    conv4_3 = mx.sym.Convolution(data=relu4_2, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv4_3")
    relu4_3 = mx.sym.Activation(data=conv4_3, act_type="relu", name="relu4_3")
    pool4   = mx.sym.Pooling(data=relu4_3, kernel=(2, 2), stride=(2, 2), pool_type="max", name="pool4")
    
    # conv5
    conv5_1 = mx.sym.Convolution(data=pool4, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv5_1")
    relu5_1 = mx.sym.Activation(data=conv5_1, act_type="relu", name="relu5_1")
    conv5_2 = mx.sym.Convolution(data=relu5_1, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv5_2")
    relu5_2 = mx.sym.Activation(data=conv5_2, act_type="relu", name="relu5_2")
    conv5_3 = mx.sym.Convolution(data=relu5_2, kernel=(3, 3), pad=(1, 1), num_filter=512, name="conv5_3")
    relu5_3 = mx.sym.Activation(data=conv5_3, act_type="relu", name="relu5_3")
    pool5   = mx.sym.Pooling(data=relu5_3, kernel=(2, 2), stride=(2, 2), pool_type="max", name="pool5")
    
    # fc6
    flat6     = mx.sym.Flatten(data=pool5, name="flat6")
    fc6     = mx.sym.FullyConnected(data=flat6, num_hidden=4096, name="fc6")
    relu6   = mx.sym.Activation(data=fc6, act_type="relu", name="relu6")
    drop6   = mx.sym.Dropout(data=relu6, p=0.5, name="drop6")
    
    # fc7
    fc7     = mx.sym.FullyConnected(data=drop6, num_hidden=4096, name="fc7")
    relu7   = mx.sym.Activation(data=fc7, act_type="relu", name="relu7")
    drop7   = mx.sym.Dropout(data=relu7, p=0.5, name="drop7")
    
    # fc8
    fc8     = mx.sym.FullyConnected(data=drop7, num_hidden=1000, name="fc8")
    softmax = mx.sym.Softmax(data=fc8, name="softmax")
    
    return softmax
--------------------------------------------------------------------------------------------------------

I need this kind of file, because it is convenient for me to modify the network architecture, not just use the  network simply. Moreover, it is also convenient to check the name and other parameters of each layer.

For example, if I want to modify the "resnet152_v2" in model zoo in Gluon Package, how should I do except inefficiently rewriting it's symbol in python by myself ?

My ideas:
1. load the resnet152_v2 using Gluon.model_zoo API and save as json file, then convert the json file to .py file with "def resnet152_v2_symbol():" in it.  But, I don't know how to do the second step.

Any solutions ? 
Thanks.

**Comment by szha** [comment]
Are you looking for this? https://github.com/apache/incubator-mxnet/tree/master/python/mxnet/gluon/model_zoo/vision

**Comment by Yochengliu** [comment]
@szha  It is just what I want, thank you very much.
