### ISSUE TITLE
incur unnecessary extra copy of "ret"

### ISSUE THREAD

**Issue by HaoranYi** [apache/incubator-mxnet#8410]
https://github.com/apache/incubator-mxnet/blob/87068e6df91ed9b2fdbcffa4d6a83e318c002247/src/executor/infer_graph_attr_pass.cc#L313

This line will incur a copy of nnvm::Graph. Because inside the function ret is lvalue, even when the input parameter ret is rvalue. This line should be changed to 
return std::move(ret);

**Comment by piiswrong** [comment]
https://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move
Compilers will do this automatically

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
