### ISSUE TITLE
warning when subclassing AI::MXNet::DataIter

### ISSUE THREAD

**Issue by adamcrussell** [apache/incubator-mxnet#8411]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues.

If the issue is non-technical, feel free to present the information in what you believe is the best form.

## Description
As previously suggested here, in order to ingest a variety of data types and convert them to floating point I have subclassed AI::MXNet::DataIter. This works very well. I have done this several times and each time I get the following warning:
    Prototype mismatch: sub MyData::MyDataIterator::inner: none vs (;@) at (eval 76) line 8.
Obviously MyData::MyDataIterator will vary but otherwise the message is the same. I am not the familiar with Mouse, and so I am having trouble resolving this. What does this warning mean and how can I fix my code to make it go away? It seems that maybe `use PDL;` in the same file is necessary to get this?

## Environment info (Required)

Package used (Python/R/Scala/Julia): Perl

## Build info (Required if built from source)

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

66f9b33b6965bb0ebf73b7c5d625b021f0d2adb7

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

##
    #File Example.pm
    ##
    package  ExampleIterator;
    use Mouse;
    extends AI::MXNet::DataIter;

    use PDL;

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Create ExampleIterator.pm as shown
2. perl -MExampleIterator -e 0

**Comment by sergeykolychev** [comment]
@adamcrussell Mouse imports 'inner' sub intro the package namespace and it conflicts with inner exported by PDL, just un-import Mouse and the warning will go away.   
```
package  ExampleIterator;
use Mouse;
extends AI::MXNet::DataIter;
no Mouse;
use PDL;
```

**Comment by adamcrussell** [comment]
ah! simple enough, thanks!
