### ISSUE TITLE
python api docs: links to external resources broken

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#8415]
## Description
Looks like a few of the rst tags for links to external references are malformed. Here are 3 I noticed:
https://mxnet.incubator.apache.org/versions/master/api/python/gluon.html#id123
https://mxnet.incubator.apache.org/versions/master/api/python/gluon.html#mxnet.gluon.data.vision.CIFAR10
https://mxnet.incubator.apache.org/versions/master/api/python/gluon.html#mxnet.gluon.data.vision.MNIST

Example:
```
`https://github.com/zalandoresearch/fashion-mnist`_.
```

## Environment info (Required)
Just browse the doc links provided in the description.

## Steps to reproduce
Just browse the doc links provided.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by thomelane** [comment]
@aaronmarkham it looks like you've fixed these! at least the examples you've listed. going to request for close, but reopen if still an issue.

@sandeep-krishnamurthy can we close this issue please, thanks!
