### ISSUE TITLE
MXNet with libgfortran3 will limit cpu usage.

### ISSUE THREAD

**Issue by kevinthesun** [apache/incubator-mxnet#8416]
## Description
MXNet low cpu usage for version > 0.11.0

## Steps to reproduce
We did some tests on c4.8xlarge.  cpu utilization was limited to 200% for `pip install mxnet --pre 0.11.1b20171001`. For 0.12 it was around 480%.

```python
import mxnet as mx
from collections import namedtuple
path='http://data.mxnet.io/models/imagenet/resnet/'
[mx.test_utils.download(path+'18-layers/resnet-18-symbol.json'),
 mx.test_utils.download(path+'18-layers/resnet-18-0000.params')]

ctx = mx.cpu()
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-18', 0)
mod = mx.mod.Module(symbol=sym, context=ctx, label_names=None)
mod.bind(for_training=False, data_shapes=[('data', (1,3,224,224))],
         label_shapes=mod._label_shapes)
mod.set_params(arg_params, aux_params, allow_missing=True)

Batch = namedtuple('Batch', ['data'])


import time
total_time = 0
for _ in range(1000):
    data = mx.nd.random_uniform(0, 255, shape=(1, 3, 224, 224)).as_in_context(ctx)
    start_time = time.time()
    mod.forward(Batch([data]))
    result = mod.get_outputs()[0].asnumpy()
    total_time += time.time() - start_time
print(total_time)     
```

**Comment by piiswrong** [comment]
@cjolivier01

**Comment by cjolivier01** [comment]
@piiswrong

**Comment by kevinthesun** [comment]
Some progress:
We did some tests on c4.8xlarge. At the beginning we didn't install libgfortran3 and cpu inference was slow. After installed libgfortran3, it was 3 times faster. However, cpu utilization was limited to 200%. It seems that the problem is mxnet with libgfortran3 will limit cpu usage. Docker should be the same issue since libgfortran3 is installed in docker.

**Comment by jiajiechen** [comment]
We also tried to set OMP_NUM_THREADS=16,
That doesn't help solving the cpu utilization problem during inference.

**Comment by lupesko** [comment]
@kevinthesun You mention that without libgfortran3 it was "slow", then with it is faster (200%), but still limited to 200%
It's not clear to me why without it CPU would be slow, and how much is "slow". Can you clarify?

**Comment by lupesko** [comment]
@piiswrong @cjolivier01 since you tagged one another I'll tag you here as well 😜

Do you have any idea what's going on? if libgfortran3 is so critical for perf, why aren't we linking it in or including it? Why does it limit CPU utilization?

Seems like a major perf issue, unless the example does something really wrong.

**Comment by szha** [comment]
If libgfortran wasn't installed you won't be able to run mxnet that was installed from pip, which means you are either running an older version of mxnet that doesn't include libgfortran library (which means source code difference), or you're building from source (which means potential build config and dependency differences).

**Comment by jiajiechen** [comment]
This is the number I got from running @kevinthesun 's script on a c4.2xl instance. 

  | CPU utilization | time
-- | -- | --
sudo pip install mxnet —pre | 480% | 121.730151892
sudo pip install --pre mxnet==0.11.1b20171001 | 200% | 57.8534896374
sudo pip install mxnet==0.11 | 650% | 239.623702049

**Comment by cjolivier01** [comment]
What actually loads libgfortran? Is it libc? Blas library? Low-level gcc libraries?

**Comment by cjolivier01** [comment]
Btw, if Gu load libgfortran and things start going faster, but cpu utilization goes down, this doesn’t imply that libgfortran is “limiting cpu usage”. Mxnet, like just about every multithreaded system, does not run with perfect concurrency at every point in the execution process. That doesn’t mean that there isn’t a bottleneck somewhere (ie file IO, memory cache misses) that could be improved, but I don’t think it necessarily points to libgfortran forcibly slowing things down.

**Comment by kevinthesun** [comment]
@cjolivier01 Thanks for your explanation. Close it for now.
