### ISSUE TITLE
bug in 0.12.0b20171022

### ISSUE THREAD

**Issue by HaoLiuHust** [apache/incubator-mxnet#8420]
http://nnvm.tvmlang.org/tutorials/from_mxnet.html
when run this sample in 12.0 version, below error will occur:
[14:03:53] /home/liuhao/nnvm/tvm/dmlc-core/include/dmlc/logging.h:308: [14:03:53] src/top/nn/nn.cc:44: Operator dense(use_bias=True, units=1000, name=dense0) expects weight's shape to be [1000,1], but got [1000,512].

when use 11.0 or 11.1 version, it will be ok.

**Comment by szha** [comment]
@zhreshold

**Comment by zhreshold** [comment]
Fixed in https://github.com/dmlc/nnvm/pull/200

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Closing since the bug has already been fixed.
