### ISSUE TITLE
Long Running Unit Tests: check_factorization_machine_module() on CPU

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#8432]
## Description
Test factorization machine model with sparse operators takes long to run as shown in build logs - 
"Test factorization machine model with sparse operators ... ok (**_3404.9069s_**)"

## Environment info (Required)
1. Ran as part of "Python 2 CPU" on Jenkins (ubuntu, g2.8xlarge) - 
Full log here: https://builds.apache.org/job/incubator-mxnet/job/v0.12.0/54/consoleFull

2. Also tested on c4.8xlarge as follows (by @eric-haibin-lin )- 
check_factorization_machine_module( adam ) and check_factorization_machine_module( sgd ) both takes less than 5 seconds. But check_factorization_machine_module( adagrad ) is much slower (~200 second)

```
MXNet commit hash:
MXNet 0.12.0.rc0 tag/branch

**Comment by cjolivier01** [comment]
Fixed:

https://github.com/apache/incubator-mxnet/commit/fa5126f54fd6dd21317d69c803b13ba2f6c77e9d
