### ISSUE TITLE
some questions about sparse lr examples

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#8442]
I just study sparse lr examples,and have some quesitons
why weight need to be define shape(features,2)
what is the meaning of shape[0],shape[1] in weight?
if i just like to use LogisticRegressionOutput as loss,
 x = mx.symbol.Variable("data", stype='csr')
    norm_init = mx.initializer.Normal(sigma=0.01)
    # weight with row_sparse storage type to enable sparse gradient updates
    weight = mx.symbol.Variable("weight", shape=(num_features, 1),
                                init=norm_init, stype='row_sparse')
    bias = mx.symbol.Variable("bias", shape=(1,))
    dot = mx.symbol.sparse.dot(x, weight)
    pred = mx.symbol.broadcast_add(dot, bias)
    #y = mx.symbol.Variable("softmax_label")
    #model = mx.sym.Custom(pred, y, op_type='weighted_softmax_ce_loss',
    #                      positive_cls_weight=positive_cls_weight, name='out')
    #return mx.sym.MakeLoss(model)
    net = mx.symbol.LogisticRegressionOutput(data=pred, name="softmax")
    return net
 it will report     self.update(label, pred)
  File "/search/data/mxnet_new/example/sparse/../../python/mxnet/metric.py", line 987, in update
    prob = pred[numpy.arange(num_examples, dtype=numpy.int64), numpy.int64(label)]
IndexError: index 1 is out of bounds for axis 1 with size 1 in metri
how can i fix it ?
@eric-haibin-lin

**Comment by anirudh2290** [comment]
What does your training data look like? Can you please provide your full script. I was able to run the script with mx.symbol.LogisticRegressionOutput instead of LinearRegressionOutput.

**Comment by eric-haibin-lin** [comment]
It's just that the `NegativeLogLikelihood` metric requires the prediction results are of shape (num_sample, 2) for 2-class classification. If you use `MSE ` as the metric, you won't see that err message. 
Another way is register your own metric which calculates based on pred of shape (num_sample,1) and label (num_sample, 1)

**Comment by liumilan** [comment]
i think i get it now.
Because LogisticRegressionOutput is only one input ,it has to modify some metric code ,
It fixed now.
@eric-haibin-lin
