### ISSUE TITLE
pip install mxnet-cu80==0.11.0 error

### ISSUE THREAD

**Issue by xqdan** [apache/incubator-mxnet#8447]
## Description
pip install mxnet-cu80==0.11.0,
reports,
Collecting mxnet-cu80==0.11.0
  Could not find a version that satisfies the requirement mxnet-cu80==0.11.0 (from versions: )
No matching distribution found for mxnet-cu80==0.11.0

## Environment info (Required)

----------Python Info----------
('Version      :', '2.7.6')
('Compiler     :', 'GCC 4.8.4')
('Build        :', ('default', 'Oct 26 2016 20:30:19'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet')
Traceback (most recent call last):
  File "check.py", line 108, in check_mxnet
    with open(commit_hash, 'r') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/COMMIT_HASH'

----------System Info----------
('Platform     :', 'Linux-4.2.0-27-generic-x86_64-with-Ubuntu-14.04-trusty')
('system       :', 'Linux')
('node         :', 'ubuntu')
('release      :', '4.2.0-27-generic')
('version      :', '#32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                72
On-line CPU(s) list:   0-71
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               2300.000
BogoMIPS:              4592.04
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-17,36-53
NUMA node1 CPU(s):     18-35,54-71
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.1997 sec, LOAD: 2.2869 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.1393 sec, LOAD: 0.5727 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.2254 sec, LOAD: 1.0769 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.3398 sec, LOAD: 0.3019 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1826 sec, LOAD: 0.7265 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>, DNS finished in 1.04916906357 sec.

**Comment by xqdan** [comment]
I've downloaded whl package form https://pypi.python.org/pypi/mxnet-cu75/0.12.0b20171027,
and installed manually.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by gautamkmr** [comment]
Please remove Need Triage label
Please add label: Installation, Pip
