### ISSUE TITLE
Issue Installing mxnet for R on Ubuntu 14.04 ("cholmod.h" not found)

### ISSUE THREAD

**Issue by nkravi98** [apache/incubator-mxnet#8449]

**Comment by jeremiedb** [comment]
There are a few error messages linked to the installation of the dependent packages, such as igraph and DiagrammeR. Have you tried running `sudo make rpkg` ? Otherwise, you might try to execute the make rpkg steps once at a time to identify which fdirst steps result in error during install. 
I haven't encountered installation issue on both Ubuntu 14.04 and 16.04 with the current installation instructions at https://mxnet.incubator.apache.org/get_started/install.html other than using  `sudo make rpkg` and ignoring the following `R CMD INSTALL mxnet_current_r.tar.gz`.

**Comment by nkravi98** [comment]
Thanks for the suggestions.  I tried "sudo make rpkg" and got the same error message.  I then executed just the make step that is causing the problem.   It still looks like a problem with "cholmod.h" from the SuiteSparse package (no such file or directory).  Here is the output:
------------------------------------------------------
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cloud.r-project.org/')); install_deps(pkg='R-package', dependencies = TRUE)"
trying URL 'https://cloud.r-project.org/src/contrib/DiagrammeR_0.9.2.tar.gz'
Content type 'application/x-gzip' length 1954050 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

Installing DiagrammeR
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Installing igraph
trying URL 'https://cloud.r-project.org/src/contrib/irlba_2.3.1.tar.gz'
Content type 'application/x-gzip' length 233712 bytes (228 KB)
==================================================
downloaded 228 KB

Installing irlba
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae527e4f743e/irlba'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘irlba’ ...
** package ‘irlba’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/lib/r-google/include -DNDEBUG  -I"/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I/usr/local/include   -fpic  -g -O2  -c irlb.c -o irlb.o
In file included from /usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include/Matrix.h:25:0,
                 from irlb.c:37:
/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include/cholmod.h:15:61: fatal error: third_party/SuiteSparse/CHOLMOD/Include/cholmod.h: No such file or directory
 #include "third_party/SuiteSparse/CHOLMOD/Include/cholmod.h"
                                                             ^
compilation terminated.
make: *** [irlb.o] Error 1
ERROR: compilation failed for package ‘irlba’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/irlba’
Installation failed: Command failed (1)
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae5229281d55/igraph'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘irlba’ is not available for package ‘igraph’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/igraph’
Installation failed: Command failed (1)
trying URL 'https://cloud.r-project.org/src/contrib/influenceR_0.1.0.tar.gz'
Content type 'application/x-gzip' length 23498 bytes (22 KB)
==================================================
downloaded 22 KB

Installing influenceR
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Skipping igraph, it is already being installed.
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae5250ab90e9/influenceR'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘igraph’ is not available for package ‘influenceR’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/influenceR’
Installation failed: Command failed (1)
trying URL 'https://cloud.r-project.org/src/contrib/rgexf_0.15.3.tar.gz'
Content type 'application/x-gzip' length 447723 bytes (437 KB)
==================================================
downloaded 437 KB

Installing rgexf
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Skipping igraph, it is already being installed.
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae522110691c/rgexf'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘igraph’ is not available for package ‘rgexf’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/rgexf’
Installation failed: Command failed (1)
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae521ba8a214/DiagrammeR'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependencies ‘igraph’, ‘influenceR’, ‘rgexf’ are not available for package ‘DiagrammeR’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/DiagrammeR’
Installation failed: Command failed (1)

**Comment by nkravi98** [comment]
###
Thanks for the suggestions.  I tried ```sudo make rpkg``` and got the same error message.  I then tried to execute the ```make rpkg``` steps one at a time to identify the problem.  The problem still appears to be a missing file from the SuiteSparse third party package ("cholmod.h").  Here is the executed command and error output.  Would appreciate any further suggestions.

--------
```
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cloud.r-project.org/')); install_deps(pkg='R-package', dependencies = TRUE)"
trying URL 'https://cloud.r-project.org/src/contrib/DiagrammeR_0.9.2.tar.gz'
Content type 'application/x-gzip' length 1954050 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

Installing DiagrammeR
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Installing igraph
trying URL 'https://cloud.r-project.org/src/contrib/irlba_2.3.1.tar.gz'
Content type 'application/x-gzip' length 233712 bytes (228 KB)
==================================================
downloaded 228 KB

Installing irlba
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae527e4f743e/irlba'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘irlba’ ...
** package ‘irlba’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/lib/r-google/include -DNDEBUG  -I"/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I/usr/local/include   -fpic  -g -O2  -c irlb.c -o irlb.o
In file included from /usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include/Matrix.h:25:0,
                 from irlb.c:37:
/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include/cholmod.h:15:61: fatal error: third_party/SuiteSparse/CHOLMOD/Include/cholmod.h: No such file or directory
 #include "third_party/SuiteSparse/CHOLMOD/Include/cholmod.h"
                                                             ^
compilation terminated.
make: *** [irlb.o] Error 1
ERROR: compilation failed for package ‘irlba’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/irlba’
Installation failed: Command failed (1)
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae5229281d55/igraph'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘irlba’ is not available for package ‘igraph’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/igraph’
Installation failed: Command failed (1)
trying URL 'https://cloud.r-project.org/src/contrib/influenceR_0.1.0.tar.gz'
Content type 'application/x-gzip' length 23498 bytes (22 KB)
==================================================
downloaded 22 KB

Installing influenceR
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Skipping igraph, it is already being installed.
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae5250ab90e9/influenceR'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘igraph’ is not available for package ‘influenceR’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/influenceR’
Installation failed: Command failed (1)
trying URL 'https://cloud.r-project.org/src/contrib/rgexf_0.15.3.tar.gz'
Content type 'application/x-gzip' length 447723 bytes (437 KB)
==================================================
downloaded 437 KB

Installing rgexf
trying URL 'https://cloud.r-project.org/src/contrib/igraph_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3376958 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

Skipping igraph, it is already being installed.
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae522110691c/rgexf'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependency ‘igraph’ is not available for package ‘rgexf’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/rgexf’
Installation failed: Command failed (1)
'/usr/lib/r-google/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpYW2k4K/devtoolsae521ba8a214/DiagrammeR'  \
  --library='/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

ERROR: dependencies ‘igraph’, ‘influenceR’, ‘rgexf’ are not available for package ‘DiagrammeR’
* removing ‘/usr/local/google/home/ravinarasimhan/R/x86_64-pc-linux-gnu-library/3.4/DiagrammeR’
Installation failed: Command failed (1)
```

**Comment by thirdwing** [comment]
I am afraid the is from `irlba` package, not from `mxnet`.

Can you try to install `irlba`?
