### ISSUE TITLE
R installation error in CentOS 7.4 GPU machine 

### ISSUE THREAD

**Issue by parunach** [apache/incubator-mxnet#8451]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues.

If the issue is non-technical, feel free to present the information in what you believe is the best form.

## Description
I am able to compile the mxnet but not generate the R version due to a segmentation fault when it checks if the installed package can be loaded.

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
make rpkg

## Error Message:

No man pages found in package  ‘mxnet’ 
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
sh: line 1: 61125 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpRgu1KA/fileeec1f9b98de'
ERROR: loading failed
* removing ‘/usr/lib64/R/library/mxnet’
make: *** [rpkg] Error 1

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

```
git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet --branch 0.11.0
cd mxnet
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
make rpkg
```

## What have you tried to solve it?

I tried making with and without sudo, no success. I have CUDA 8.0 in CentOS version 7.4.

**Comment by thirdwing** [comment]
Can you show the full message during installation?

**Comment by parunach** [comment]
I found the error. It was due to opencv not being installed properly. This is a problem in CentOS as it does not have 3.0. I had to install from source. After this, I could install mxnet. Sorry about that.
