### ISSUE TITLE
[CoreML Converter] Installer for python 3

### ISSUE THREAD

**Issue by pracheer** [apache/incubator-mxnet#8455]
The current [mxnet-to-coreml](https://pypi.python.org/pypi/mxnet-to-coreml) installer only supports python 2.7. We need to provide an installer for python 3.* too.

**Comment by kkk669** [comment]
The mxnet-to-coreml depends on coremltools and it only supports Python 2.7. At first, it is necessary that coremltools should support Python 3.X.

**Comment by pracheer** [comment]
Missed that fact. Resolving this since this it is not needed for the time being.
