### ISSUE TITLE
[Gluon] Gluon checkpoint incompatibility with older apis

### ISSUE THREAD

**Issue by pracheer** [apache/incubator-mxnet#8457]
As discussed in the other github issue #8390 , the models that have been checkpointed using gluon don't seem to be loadable via model api. There are at least couple of differences between the older format and gluon's checkpoint format that some of us found (are there more?):
1. Softmax layer doesn't exist in the gluon's checkpointed symbol file. (since softmax layer is associated with the loss layer)
1. The format of params file has changed. Older params file seem to have aux/arg keyword w/ every key where gluon doesn't do that.

Consequently, I'd like to know the following:
1. Is there a recommended way to convert older models that have been developed till now into gluon format?
1. Gluon models to older format?
1. By looking at the symbol/params file is it possible to figure out whether they are in gluon's format or not? The symbol file seems to have mxnet version but not this detail.

**Comment by szha** [comment]
I think Model API is deprecated. Support for module is available through this API https://mxnet.incubator.apache.org/versions/master/api/python/gluon/gluon.html#mxnet.gluon.HybridBlock.export

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by nswamy** [comment]
@pracheer Model APIs are deprecated.
