### ISSUE TITLE
anchors = mx.symbol.contrib.MultiBoxPrior

### ISSUE THREAD

**Issue by ahong007007** [apache/incubator-mxnet#8461]
## Description
(Brief description of the problem in no more than 2 sentences.)

anchors = mx.symbol.contrib.MultiBoxPrior(from_layer, sizes=size_str, ratios=ratio_str,
AttributeError: module 'mxnet.symbol' has no attribute 'contrib'

## Environment info (Required)
mxnet
```
What to do:
1. Download the example SSD

Package used (Python/R/Scala/Julia):
(I'm using ...)python


## What have you tried to solve it?

1.anchors = mx.symbol.contrib.MultiBoxPrior-->anchors = mx.contrib.symbol.MultiBoxPrior
2.

**Comment by zhreshold** [comment]
Your mxnet install is outdated. Please update mxnet first.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Please update to a version of MXNet that has the operator. Latest (1.1) should work.
