### ISSUE TITLE
num_unknown == 0 (18446744073709551591 vs. 0) Unabled to decied context for nodes

### ISSUE THREAD

**Issue by bigvat** [apache/incubator-mxnet#8467]
I get some errors:

raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [03:25:37] src/imperative/./imperative_utils.h:601: Check failed: num_unknown == 0 (18446744073709551591 vs. 0) Unabled to decied context for nodes
 
when calling loss.backward() on cpu.

mxnet 0.11.1

How I solve it ? Thank you !!

**Comment by szha** [comment]
Should have been fixed by #8450. You may try upgrade to today's nightly build and see if it's fixed.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Fixed by https://github.com/apache/incubator-mxnet/pull/8450
