### ISSUE TITLE
Gluon Model Zoo Vision Models Are Pretrained on Which Dataset?

### ISSUE THREAD

**Issue by jongchyisu** [apache/incubator-mxnet#8468]
Hi, I am using pretrained resnet models from the gluon model_zoo interface. 
However, I couldn't find the documentation of which dataset it is pretrained on. 
I can only find the sha key to download the model.
Is it on ImageNet 1K or 11K? Thanks!

**Comment by mylxiaoyi** [comment]
Hi, from `incubator-mxnet/python/mxnet/gluon/model_zoo/vision/__init__.py`, they said

    Pretrained models are converted from torchvision.

and reference to [torchvision](http://pytorch.org/docs/master/torchvision/models.html), we can see that the pretrained models are trained on ImageNet.
