### ISSUE TITLE
Use F.reshape_like as F.where condition will cause mismatch gradients

### ISSUE THREAD

**Issue by zhreshold** [apache/incubator-mxnet#8477]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues.

If the issue is non-technical, feel free to present the information in what you believe is the best form.

## Description
Use F.reshape_like as F.where condition will cause mismatch gradients,

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
9cf918cbcff32fd2ca4b2d6d53e7f33138d886ee

## Error Message:
```python
mxnet.base.MXNetError: [18:20:44] src/pass/gradient.cc:166: Check failed: (*rit)->inputs.size() == input_grads.size() (2 vs. 3) Gradient function not returning enough gradient
```

## Minimum reproducible example
```
import mxnet as mx
from mxnet import nd
from mxnet import gluon
from mxnet.gluon import nn
from mxnet import autograd


net = nn.HybridSequential()
net.add(nn.Conv2D(3, 3, 1))
net.initialize()

x = nd.ones((1, 3, 64, 64))

class myblock(gluon.Block):
    def __init__(self, **kwargs):
        super(myblock, self).__init__(**kwargs)

    def forward(self, x):
        y = nd.relu(x * 3 + 5)
        z = nd.ones_like(y)
        y = nd.where(z.reshape_like(y) == 1, z, y)  #!!! bug here
        return y

myfunc = myblock()
myloss = gluon.loss.L1Loss()

with autograd.record():
    y = net(x)
    z = myfunc(y)
    loss = myloss(y, z)
    autograd.backward(loss)

print(nd.sum(loss))
```

## What have you tried to solve it?

Use reshape_like itself won't cause problem, only when combining F.where(F.reshape_like(a, b), x, y) will raise error.

**Comment by zhreshold** [comment]
@piiswrong I think it's inrrelavent to fix in #8322

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
@zhreshold Does this issue still exist?

**Comment by zhreshold** [comment]
This is fixed, closing this.
