### ISSUE TITLE
complie error in new version

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#8479]
I just update cuda to 8.0,and when i complie the latest version,it will report
cub/cub.cuh: No such file or directory

USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
the makefile is as above

**Comment by reminisce** [comment]
Did you use `--recursive` flag when `git clone` the mxnet repo?

**Comment by liumilan** [comment]
yes,i just forget to set cuda lib in .bashrc
Now it fixed.
