### ISSUE TITLE
MXNDArrayFree in c_api.h cannot release the gpu memory

### ISSUE THREAD

**Issue by calipos** [apache/incubator-mxnet#8482]
MXNDArrayFree in c_api.h cannot release the gpu memory.  What have I done wrong?
---
test code:
        const mx_uint test_shape[4] = { 300,300,30,30 };
	const mx_uint test_shape_dim = 4;
	NDArrayHandle testGpuND;	
	MXNDArrayCreateEx(test_shape, test_shape_dim, 2, 0, false, 0, &testGpuND);
	ret = MXNDArrayFree(testGpuND);

### Environment info
---

**Comment by piiswrong** [comment]
Memory is released into a pool. It will be reused the next time you allocate an array

**Comment by calipos** [comment]
@piiswrong  
I want to ask what method has to be possible to release the pool how to release well?
I'm sure I'm not going to allocate any array,  how to make better use of the GPU

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by samskalicky** [comment]
@calipos you cannot control the memory pool. It gets freed on exit of the program.

@sandeep-krishnamurthy please close this issue. Thanks!

**Comment by zhreshold** [comment]
Currently there's no way to release the pool through existing API. You can post a feature request if you think it's important. @calipos  
Feel free to ping me to reopen this issue regarding any questions remaining, thanks.
