### ISSUE TITLE
Something complement to the official MXNet examples

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#8486]
https://github.com/chinakook/Awesome-MXNet

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by mbaijal** [comment]
@chinakook @szha  this still an open issue ?

**Comment by mbaijal** [comment]
Please add the label 'Example' and 'Pending Requester Info'

**Comment by szha** [comment]
This list of mxnet resources is awesome. @aaronmarkham could you recommend a place on the website to highlight this community contribution?

**Comment by chinakook** [comment]
It's also added by @ThomasDelteil in https://github.com/apache/incubator-mxnet/blob/c54f9f7f74c70a9ae036e765b702a2de390d16c2/example/README.md
