### ISSUE TITLE
How to use LSTM or GRU in C++ using c_predict_api.h?

### ISSUE THREAD

**Issue by xiaogehh** [apache/incubator-mxnet#8487]
I find nothing about how to use LSTM or GRU in C++ using c_predict_api.h?
Have we support these recurrent layers? If No,is there any plan?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by ThomasDelteil** [comment]
@xiaogehh currently the Gluon LSTM and GRU RNN layers cannot be hybridized but the work towards should be soon completed. You can track the effort here: https://github.com/apache/incubator-mxnet/issues/10873

Alternatively you have an example of LSTM implemented in C++ here: https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/charRNN.cpp

@sandeep-krishnamurthy could you please consider closing the issue.
@xiaogehh if you would like to follow up, please create an issue on https://discuss.mxnet.io
