### ISSUE TITLE
API documentation out-of-sync with version on website

### ISSUE THREAD

**Issue by analog-cbarber** [apache/incubator-mxnet#8490]
The version currently listed on https://mxnet.incubator.apache.org/ is 0.11.0 (although 0.12.0 was
just released but not yet shown on the versions list), but the API documentation appears to be for 0.12.0 or master. For instance, the fluent NDArray operators that were added in 0.12.0 appear in the documentation. I observed this on 10/30/2017, before 0.12.0 was released. 

I am not sure whether this is because the site doc was updated prematurely or whether it is
actually tracking master.

This caused some confusion when I tried to use documented methods that were not there.

**Comment by eric-haibin-lin** [comment]
@thinksanky

**Comment by sad-** [comment]
@eric-haibin-lin this is no longer the case. could we close out this issue? thanks
