### ISSUE TITLE
how to use mxnet mx.io.extract()  in cnn model

### ISSUE THREAD

**Issue by janejane11** [apache/incubator-mxnet#8497]
that's my problem:  how to use mx.io.extract()
in the begining,i use mx.io.ImageRecordIter to read my data(7 label) in cnn model  (below)

train = mx.io.ImageRecordIter(
    path.imglist=path1,
    path.imgrec=path2,
    batch.size=4,
    round.batch=TRUE,
    data.shape=c(50,50,1),
    preprocess.threads=1
  )
  test = mx.io.ImageRecordIter(
    path.imglist=path3,
    path.imgrec=path4,
    batch.size=4,
    data.shape=c(50,50,1),
    round.batch=FALSE,
    preprocess.threads=1

after many times training..
finally,i want to show the table about the test result  
so i write

 preds<-predict(model,test)
 pred.label<-max.col(t(preds))-1
 cm=confusionMatrix(pred.label,mx.io.extract)
 t(cm$table)

there are always some fault on mx.io.extract
i think it may need some parameter,but i have no idea

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by thomelane** [comment]
@janejane11 I realise this was an issue for you quite a while ago, but it looks to me like you should indeed be passing arguments to `mx.io.extract`. Checking the docs found [here](https://s3.amazonaws.com/mxnet-prod/docs/R/mxnet-r-reference-manual.pdf) you need to pass the data_iter and the field you're interested in extracting: `mx.io.extract(iter, field)`. But I think `ImageRecordIter` extracts the label for you, so you wouldn't need to extract this manually. And then you could pass `confusionMatrix(pred.label, test.label)` or similar.

**Comment by thomelane** [comment]
@yzhliu good to close, but @janejane11 please reopen if this is still an issue, thanks!
