### ISSUE TITLE
libPlayCtrl.so: undefined symbol: AR_Setparam

### ISSUE THREAD

**Issue by botaichang** [apache/incubator-mxnet#8499]
when i compile mxnet, i got this error:    OSError: libPlayCtrl.so: undefined symbol: AR_SetParam, could you help me solve this problem.I usually use caffe framework, this is my first time to use mxnet. Thank you.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@botaichang Thanks to try out build this package. Are you still facing the same issue now? If so, please provide the steps you have tried to build so we can better help you with that.

**Comment by szha** [comment]
libPlayCtrl.so doesn't seem like a dependency of mxnet.

For building mxnet from source, please refer to the instructions in https://mxnet.apache.org/install/index.html?device=Linux&language=Python&processor=CPU
