### ISSUE TITLE
Minor differences in distributed training with GPU/without GPU.

### ISSUE THREAD

**Issue by Luo-Liang** [apache/incubator-mxnet#8510]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues.

If the issue is non-technical, feel free to present the information in what you believe is the best form.

## Description
mnist accuracy differ slightly when training with local gpu and distributed training with GPU but accuracy is the same when training with CPU.

## Environment info (Required)
CentOS 7
MxNet latest master 

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
```

Package used (Python/R/Scala/Julia):
(I'm using ...) Python!

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)
train_mnist.py with data shuffle turned off so accuracy of each run is the same.

Compiler (gcc/clang/mingw/visual studio):
gcc 4.9

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
8592e1cd3b9f79cff740f29e599ba7788a454c54

Build config:
(Paste the content of config.mk, or the build command.)

USE_DISTRIBUTED_KVSTORE=1
USE_CUDNN=1
USE_CUDA=/usr/local/cuda

## Error Message:
1 server 1 client training with train_mnist.py WITHOUT GPU
INFO:root:Epoch[0] Batch [100]  Speed: 3606.78 samples/sec      accuracy=0.807859
INFO:root:Epoch[0] Batch [200]  Speed: 3747.11 samples/sec      accuracy=0.895469
INFO:root:Epoch[0] Batch [300]  Speed: 3982.58 samples/sec      accuracy=0.912656
INFO:root:Epoch[0] Batch [400]  Speed: 3960.68 samples/sec      accuracy=0.928594
INFO:root:Epoch[0] Batch [500]  Speed: 5376.55 samples/sec      accuracy=0.933906
INFO:root:Epoch[0] Batch [600]  Speed: 4133.33 samples/sec      accuracy=0.943906
INFO:root:Epoch[0] Batch [700]  Speed: 5935.95 samples/sec      accuracy=0.944688
INFO:root:Epoch[0] Batch [800]  Speed: 3966.74 samples/sec      accuracy=0.940312
INFO:root:Epoch[0] Batch [900]  Speed: 3803.05 samples/sec      accuracy=0.953906
INFO:root:Epoch[0] Train-accuracy=0.966639
INFO:root:Epoch[0] Time cost=14.467
INFO:root:Epoch[0] Validation-accuracy=0.943670

1 server 1 client training with train_mnist.py WITH GPU
INFO:root:Epoch[0] Batch [100]  Speed: 13700.01 samples/sec     accuracy=0.807859
INFO:root:Epoch[0] Batch [200]  Speed: 27909.23 samples/sec     accuracy=0.895469
INFO:root:Epoch[0] Batch [300]  Speed: 23719.16 samples/sec     accuracy=0.910781
INFO:root:Epoch[0] Batch [400]  Speed: 30796.60 samples/sec     accuracy=0.925312
INFO:root:Epoch[0] Batch [500]  Speed: 26746.35 samples/sec     accuracy=0.933906
INFO:root:Epoch[0] Batch [600]  Speed: 29120.16 samples/sec     accuracy=0.943906
INFO:root:Epoch[0] Batch [700]  Speed: 30805.82 samples/sec     accuracy=0.944531
INFO:root:Epoch[0] Batch [800]  Speed: 22852.49 samples/sec     accuracy=0.937813
INFO:root:Epoch[0] Batch [900]  Speed: 28238.62 samples/sec     accuracy=0.952031
INFO:root:Epoch[0] Train-accuracy=0.969172
INFO:root:Epoch[0] Time cost=2.452
INFO:root:Epoch[0] Validation-accuracy=0.936505

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

(pgrep python | xargs kill -9 && rm ~/train/profile.json) &>/dev/null
(pgrep memcheck-amd64- | xargs kill -9) &> /dev/null
export DMLC_PS_ROOT_PORT=9091;
export DMLC_NUM_WORKER=1;
export DMLC_NUM_SERVER=1;
export DMLC_PS_ROOT_URI=127.0.0.1;
export DMLC_ROLE=scheduler;
python train_mnist.py &

export DMLC_ROLE=server; 
export DMLC_SERVER_ID=0
python train_mnist.py --kv-store dist_sync --gpus 0 &

export DMLC_ROLE=worker; 
export DMLC_WORKER_ID=0
python train_mnist.py --kv-store dist_sync --num-epochs 1 --gpus 0&

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Run the example and toggle --gpus 0
2. Observe accuracy differences.

## What have you tried to solve it?

1. The problem seems to be the initialization of params in GPU.
2. The first divergence of these two training is the first gradient sent out after the first batch.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by ThomasDelteil** [comment]
have you tried to fix the seed for initialization?

**Comment by vrakesh** [comment]
@Luo-Liang Have you tried fixed seed for initialization as per @ThomasDelteil's suggestion? Requesting to close this issue, if the issue is resolved.

**Comment by Luo-Liang** [comment]
Yes. This is no longer a problem. I have confirmed it's due to initialization.
