### ISSUE TITLE
Typographic Error on Landing Page

### ISSUE THREAD

**Issue by crispybacon** [apache/incubator-mxnet#8518]
## Description
The word "practioner" is used in the MXNet landing page: https://mxnet.incubator.apache.org/

Practitioner is probably the word required.  Think tank analysts suggest that this type of error is left on cover pages to imply a deep compromise in the software.   

## Environment info (Required)
Unknown`
```
I'm a Beginner.  
## Build info (Required if built from source)
NA

Build config:
NA

## Error Message:
practioner

## Minimum reproducible example
https://mxnet.incubator.apache.org/
```html
<p id="intro">
                Building a high-performance deep learning library requires many system-level design decisions. In this design note, we share the rationale for the specific 
                choices made when designing MXNet. We imagine that these insights may be useful to both deep learning practioners and builders of other deep learning systems.
            </p>
```
## Steps to reproduce
curl https://mxnet.incubator.apache.org/
## What have you tried to solve it?
Created Issue in Git Repository.

**Comment by sandeep-krishnamurthy** [comment]
Thanks, the site is updated.

@thinksanky will create PR to update the master version of site

**Comment by sandeep-krishnamurthy** [comment]
Issue is fixed. Resolving. Thanks @crispybacon for the issue.
