### ISSUE TITLE
Issue Regarding Custom Iterator Using MxnetR

### ISSUE THREAD

**Issue by dwy904** [apache/incubator-mxnet#8521]
Hi,

I do not understand this code from the [tutorial](https://mxnet.incubator.apache.org/tutorials/r/CustomIterator.html). It is about the custom iterator using mxnetr.
You can download the original data by typing the code below in your terminal,

```
wget http://pjreddie.com/media/files/mnist_train.csv
wget http://pjreddie.com/media/files/mnist_test.csv
```

Below is the original code from the tutorial,
```
csv_iter <- mx.io.CSVIter(data.csv=data.csv, data.shape=c(feature_len), 
                                           batch.size=batch.size)
.self$iter <- csv_iter
val <- as.array(.self$iter$value()$data)

val.x <- val[-1,]
val.y <- val[1,]
```
I took a look at the the original dataset, the first column is the target label, the rest columns are the features. But the code is delete the first row not the first column when defining `val.x`, shouldn't it be something below instead ? 

```
val.x <- val[,-1]
val.y <- val,1]
```

I follow the instruction and it runs smoothly, but I just do not know how that step works.

By the way, I have already used the `h2o` r version package to train my word2vec word embedding vocabulary lookup table. I am wondering if there's any sample code to combine the lookup table and the original raw text into the `custom iterator` using mxnetr, then create the CNN text classification model ?

Thank you so much,
Michael

**Comment by Phillip1982** [comment]
I have the same issue.  Does anyone know how those lines work?

**Comment by ankkhedia** [comment]
Hi @Phillip1982 and @dwy904. Thanks for trying out MXNet-R.
The answer to your query lies in the way csviterator in MXNet is designed and how R converts one data structure to other. If you could see the description and examples for CSVIterator in https://github.com/apache/incubator-mxnet/blob/master/src/io/iter_csv.cc, you will see that data_shape parameter converts each line in csv file to that shape. In our case, we pass data_shape=785 and hence each line is read as a list of 785 elements and it reads batch size number of lines and returns this data structure. 

While converting from list/vectors/dataframes to matrix/arrays using  as.array, MXNet NDarray confers with R standards which is column major format and hence the batch size becomes number of columns and features becomes number of rows. 


On a side note, please post any questions on discuss.mxnet.io as it gets visibility from wider audience.
@dwy904 @Phillip1982 please feel free to raise any followup questions on discuss.mxnet.io 

@sandeep-krishnamurthy  Could you please close the issue as it has been resolved
