### ISSUE TITLE
How to get the correlation result of two feature maps?

### ISSUE THREAD

**Issue by squidszyd** [apache/incubator-mxnet#8531]
Suppose I have two feature maps F1 and F2 output by a network. I want to compute convolution of F1 and F2. Assume that F1 has shape (1, C, 10, 10) and F2 has shape (1, C, 3, 3) and the wanted result should have shape (1, 1, 8, 8) if pad = 0, stride = 1 and dilate = 1.
How to implement this using MXNet?
I have come up with one possible way that uses mx.sym.Correlation, but I cannot get the idea how correlation operator computes by reading the doc.
Or, can I set the weight of a mx.sym.Convolution layer to F2, and data to F1? Would this interfere the propagation of grads when training?

**Comment by zhreshold** [comment]
I am confused. For correlation, the F1 and F2 must have same shapes.
For convolution, F2 should be (C, 1, 3, 3)

**Comment by squidszyd** [comment]
@zhreshold By correlation, I mean F2 acts like a correlation kernel (or convolution kernel) that slides on F1. For example,
```
     1 1 1 2 2
F2 = 2 3 4 1 1
     0 0 0 2 3 

     0 1 0
F1 = 1 0 1
     0 1 0
``` 
Then, the correlation result should be
```
R = F1 * F2 = 7 5 9
```
where 
```
7 = 1 + 2 + 4 +０
5 = 1 + 3 +１+ 0
9 = 2 + 4 + 1 + 2

**Comment by squidszyd** [comment]
Can someone help me with this?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by jingpengw** [comment]
just do convolution with another matrix?

**Comment by ThomasDelteil** [comment]
@squidszyd 
You can do the following:
```
C = 64
F1 = mx.nd.ones((1,C,10,10))
F2 = mx.nd.ones((1,C,3,3))
convolution = mx.gluon.nn.Conv2D(channels=1, kernel_size=(3,3), use_bias=False)
convolution.initialize(mx.init.Constant(F2))
out = convolution(F1)
print(out.shape)
```
```
(1, 1, 8, 8)
```

**Comment by squidszyd** [comment]
@ThomasDelteil 
Thanks for reply. I've figured out this exact solution months before :P
I'll close this issue.
