### ISSUE TITLE
What's the equivalent of np.where()?

### ISSUE THREAD

**Issue by fallingdust** [apache/incubator-mxnet#8546]
I want to do something like:

```
keep = np.where(labels != -1)[0]
cls_scores = cls_scores[keep]
```

What's the equivalent in NDArray?

I found _ndarray.take_ may do the job, but how to get the _indices_ param?

**Comment by zhreshold** [comment]
numpy.where is cannot be fully supported because it's output shape is dependent on the values of data which is beyond the capability of inter_shape.
In some circumstances, you can have a work-around using nd.arange and nd.take/pick operations.

**Comment by fallingdust** [comment]
@zhreshold 
I can fully understand that np.where is not supported by mx.symbol, but why not mx.ndarray? We can slice the ndarray by the value of data.
And would you please give an example on how to get the cls_scores according to labels != -1?
`
keep = np.where(labels != -1)[0]
cls_scores = cls_scores[keep]
`
Thx!

**Comment by zhreshold** [comment]
Not sure how you would do with the cls_scores, if you can continue use masks, then nd.where is good, if you would like to strip out useless elements, NDArray can't do that. 
You can use asnumpy() and do whatever you want anyway.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by b0noI** [comment]
Suggested tags: "Question", "HowTo"

**Comment by ThomasDelteil** [comment]
@fallingdust I think unfortunately this usage is not supported. You can use masking, depending on what you want to achieve, you can for example set the values you'd like to ignore to 0 or -1.
Here is an example where I set the discarded value to -1.
```python
labels = nd.array([-1, 0, 1, 0, 1])
cls_scores = nd.array([0.1, 0.2, 0.3, 0.4, 0.5])
cls_scores = nd.where(labels != -1, cls_scores, labels)  

​
[-1.   0.2  0.3  0.4  0.5]
<NDArray 5 @cpu(0)>
```
Or as @zhreshold said, if this code is not in a critical path of your network, you can consider doing your array manipulation in numpy.

@zhreshold could you please close the issue?
@fallingdust if you would like to follow up, please create a post on https://discuss.mxnet.io and reference this issue. Thanks!
