### ISSUE TITLE
What's the equivalent of tf.matmul in tensorflow

### ISSUE THREAD

**Issue by AaronLeong** [apache/incubator-mxnet#8549]
https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/matmul

I want to do something like:

```
x = nd.random_normal(shape=(batch_size,32,32,10,8))
y = nd.random_normal(shape=(batch_size,32,32,8,1))
```

`matmul (x,y)==>(batch_size,32,32,10,1)`

**Comment by zhreshold** [comment]
it's `nd/sym.batch_dot`
You will need to stack 32x32 into batch_size and set `transpose_a == True`

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
