### ISSUE TITLE
Convolution  dilate run not as expected  in  cpu context

### ISSUE THREAD

**Issue by yuantangliang** [apache/incubator-mxnet#8557]
## Description
I run the same Convolution with dilate on cpu and gpu,but the result is different. 

## Environment info (Required)
Ubuntu 14.04  
Python 2.7 
mxnet version: 0.9 

## Test Code 
```
import numpy as np
import mxnet as mx


def test_dilate_cpu():
    input_data = mx.symbol.Variable(name="data")
    ctx = mx.cpu(0)

    e = mx.symbol.Convolution(data=input_data, kernel =(3,1),pad=(2,0),dilate =(2,1), num_filter = 1,num_group=1,name="uo",no_bias=True)
    e = mx.sym.MakeLoss(e)

    data = np.arange(0,60)
    data = data.reshape([1, 1, 30, 2])
    # print data
    data = mx.nd.array(data,ctx=ctx)
    weight_value = np.array([1, 1, 1])
    weight_value = weight_value.reshape([1, 1,3, 1])
    weight_value = mx.nd.array(weight_value,ctx=ctx)
    out_grad = mx.nd.array(np.zeros(data.shape),ctx=ctx)
    exe1 = e.bind(ctx, {"data": data,'uo_weight':weight_value},args_grad=[out_grad,weight_value])

    y = exe1.forward(is_train=True)
    exe1.backward()
    print  'code in cpu',y[0].asnumpy()


def test_dilate_gpu():
    input_data = mx.symbol.Variable(name="data")
    ctx = mx.gpu(0)

    e = mx.symbol.Convolution(data=input_data, kernel =(3,1),pad=(2,0),dilate =(2,1), num_filter = 1,num_group=1,name="uo",no_bias=True)
    e = mx.sym.MakeLoss(e)

    data = np.arange(0,60)
    data = data.reshape([1, 1, 30, 2])
    # print data
    data = mx.nd.array(data,ctx=ctx)
    weight_value = np.array([1, 1, 1])
    weight_value = weight_value.reshape([1, 1,3, 1])
    weight_value = mx.nd.array(weight_value,ctx=ctx)
    out_grad = mx.nd.array(np.zeros(data.shape),ctx=ctx)
    exe1 = e.bind(ctx, {"data": data,'uo_weight':weight_value},args_grad=[out_grad,weight_value])

    y = exe1.forward(is_train=True)
    exe1.backward()
    print "code in gpu", y[0].asnumpy()


test_dilate_cpu()
test_dilate_gpu()
```

##output:
code in cpu [[[[ 110.  112.]
   [ 114.  116.]
   [  58.   60.]
   [   2.    4.]
   [   6.    9.]
   [  12.   15.]
   [  18.   21.]
   [  24.   27.]
   [  30.   33.]
   [  36.   39.]
   [  42.   45.]
   [  48.   51.]
   [  54.   57.]
   [  60.   63.]
   [  66.   69.]
   [  72.   75.]
   [  78.   81.]
   [  84.   87.]
   [  90.   93.]
   [  96.   99.]
   [ 102.  105.]
   [ 108.  111.]
   [ 114.  117.]
   [ 120.  123.]
   [ 126.  129.]
   [ 132.  135.]
   [ 138.  141.]
   [ 144.  147.]
   [ 150.  153.]
   [ 156.  159.]]]]
code in gpu [[[[   4.    6.]
   [   8.   10.]
   [  12.   15.]
   [  18.   21.]
   [  24.   27.]
   [  30.   33.]
   [  36.   39.]
   [  42.   45.]
   [  48.   51.]
   [  54.   57.]
   [  60.   63.]
   [  66.   69.]
   [  72.   75.]
   [  78.   81.]
   [  84.   87.]
   [  90.   93.]
   [  96.   99.]
   [ 102.  105.]
   [ 108.  111.]
   [ 114.  117.]
   [ 120.  123.]
   [ 126.  129.]
   [ 132.  135.]
   [ 138.  141.]
   [ 144.  147.]
   [ 150.  153.]
   [ 156.  159.]
   [ 162.  165.]
   [ 108.  110.]
   [ 112.  114.]]]]

**Comment by solin319** [comment]
In MXnet=0.12, the result in cpu and gpu were same.
[[[[   4.    6.]
   [   8.   10.]
   [  12.   15.]
   [  18.   21.]
   [  24.   27.]
   [  30.   33.]
   [  36.   39.]
   [  42.   45.]
   [  48.   51.]
   [  54.   57.]
   [  60.   63.]
   [  66.   69.]
   [  72.   75.]
   [  78.   81.]
   [  84.   87.]
   [  90.   93.]
   [  96.   99.]
   [ 102.  105.]
   [ 108.  111.]
   [ 114.  117.]
   [ 120.  123.]
   [ 126.  129.]
   [ 132.  135.]
   [ 138.  141.]
   [ 144.  147.]
   [ 150.  153.]
   [ 156.  159.]
   [ 162.  165.]
   [ 108.  110.]
   [ 112.  114.]]]]

**Comment by yuantangliang** [comment]
thank you ,I will update my mxnet version.
