### ISSUE TITLE
How to adding an axes in ndarray?

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#8568]
I want to add an axes in a ndarray. for example `(3,4,5,5)` to `(1,3,4,5,5)`. **I don't know the ndarray shape in advance** I refer to the `reshape api`, but can't understand the `-4` means.

**Comment by solin319** [comment]
mx.nd.expand_dims
http://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.expand_dims

**Comment by lilhope** [comment]
Thanks @solin319
