### ISSUE TITLE
the error:mshadow::cuda::AddTakeGrad' : ambiguous call to overloaded function indexing_op.h

### ISSUE THREAD

**Issue by 994088895** [apache/incubator-mxnet#8590]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues.

If the issue is non-technical, feel free to present the information in what you believe is the best form.

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by 994088895** [comment]
I have the error mshadow::cuda::AddTakeGrad' : ambiguous call to overloaded function indexing_op.h, canyou tell me what should i do

**Comment by eric-haibin-lin** [comment]
Is that a build failure? What's your MXNet version/commit id and output of `diagnose.py `?

**Comment by 994088895** [comment]
Thank you, I have resoved it. It seems that I wrongly used the 'git clone --recursive https://github.com/tornadomeet/mxnet.git' to download.
