### ISSUE TITLE
Mxnet Initializer equivalent

### ISSUE THREAD

**Issue by SrivastavaKshitij** [apache/incubator-mxnet#8605]
Hi there

I am working on an old mxnet code. (https://mxnet.incubator.apache.org/tutorials/nlp/cnn.html)

Here initialization is being done in the following manner:

Initializer(name, arg_dict[name]).... Now this has been deprecated. How can i re-write this in the new version ?

The reason for me to ask this question is that i can't find the version before which this was deprecated. hence , i cant find the documentation

**Comment by eric-haibin-lin** [comment]
The documentation indeed needs lots of improvement. 
Did you try to type `help(function_name)` to check the documentation for the previous version and compare with the current version?
