### ISSUE TITLE
git clone command wrong for Scala setup

### ISSUE THREAD

**Issue by mwunderlich** [apache/incubator-mxnet#8609]
The git clone command provided for the scala setup on OSX (on page https://mxnet.incubator.apache.org/install/osx_setup.html) seems to be wrong. When I use 
`git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet --branch 0.12.0 ~/mxnet`

I get this error: 

`Too many arguments.`

Using this it works fine: 

`git clone --recursive --branch 0.12.0 https://github.com/apache/incubator-mxnet.git ~/mxnet`

**Comment by eric-haibin-lin** [comment]
Thanks for reporting! We'll change it accordingly.

**Comment by eric-haibin-lin** [comment]
Should be fixed by #8824
