### ISSUE TITLE
How to resize the image to same shape in ImageRecordIter?

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#8610]
Hi, 
    I have a set of images with various shapes and I write it to `.rec` file,and using `mx.io.ImageRecordIter` to load it. But I met an error: 
```
 Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape
```
I tried different ways to solve it but not works. such as set`resize mode`,`inter_method`, any helps will be appreciated.

**Comment by piiswrong** [comment]
imagerecorditer has a resize parameter. Use it to resize the image to a bigger size then crop size first

**Comment by lilhope** [comment]
@piiswrong Thanks.
