### ISSUE TITLE
Does mxnet.symbol.SoftmaxOutput support matrix label?

### ISSUE THREAD

**Issue by kohillyang** [apache/incubator-mxnet#8614]
Assume I have several Matrix classes, they are mutually exclusive, which means that the sum of them must be a matrix whose all items are 1. Can I use mxnet.symbol.SoftmaxOutput as output layer to predict these classes?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by nswamy** [comment]
Closing this, please redirect your question to our user forum
