### ISSUE TITLE
Documentation update for gluon.nn.Dense. `flatten` invalid keyword argument.

### ISSUE THREAD

**Issue by startakovsky** [apache/incubator-mxnet#8627]
Documentation is incorrect for gluon.nn.Dense

https://mxnet.incubator.apache.org/api/python/gluon.html#mxnet.gluon.nn.Dense

`flatten` is not a valid keyword argument, but it shows up in the documentation.

**Comment by kobenaxie** [comment]
Maybe your mxnet version is too old,  the newest version support flatten.

**Comment by startakovsky** [comment]
Thanks, I am on 0.11!

..sent from steven's phone..

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by yzhliu** [comment]
close since it has been resolved in new versions.
