### ISSUE TITLE
How to use label smoothing and set 'ignore_label' with gluon like mx.symSoftmaxOutput ?

### ISSUE THREAD

**Issue by kobenaxie** [apache/incubator-mxnet#8634]
In mx.sym.SoftmaxOutput(), we can set `ignore_label` and `smooth_alpha` , how to use these in gluon ?

**Comment by KeyKy** [comment]
how to use smooth_alpha, i do not find the usage in mxnet symbol document. https://mxnet.incubator.apache.org/api/python/symbol.html

**Comment by kobenaxie** [comment]
reference [https://github.com/apache/incubator-mxnet/issues/8404](url)
