### ISSUE TITLE
What differences between  ImageRecordIter and ImageRecordIter_v1?

### ISSUE THREAD

**Issue by shipeng-uestc** [apache/incubator-mxnet#8636]
I read the ImageRecordIter_v1 API ,it mentions "Read images batches from RecordIO files with a rich of data augmentation options."
But I have compare them. they have the same parameters.
So, i don't know their differences.

**Comment by eric-haibin-lin** [comment]
Could you help clarify and improve the documentation if necessary? @ptrendx

**Comment by ptrendx** [comment]
ImageRecordIter_v1 is a much slower, deprecated version of ImageRecordIter. I will make a PR to documentation to reflect that.

**Comment by sad-** [comment]
@eric-haibin-lin looks like this issue has been addressed with the pr. could you close the issue

**Comment by ThomasDelteil** [comment]
@sandeep-krishnamurthy @indhub can you please close the issue? Thanks!
