### ISSUE TITLE
How can I install the newest mxnet R package?

### ISSUE THREAD

**Issue by markusdumke** [apache/incubator-mxnet#8648]
When I run

```
cran <- getOption("repos")
cran["dmlc"] <- "https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
```

this will install `mxnet 0.10.1`. How can I install `mxnet 0.12.1`?

This is the `sessionInfo` output:

> R version 3.4.2 (2017-09-28)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252 
> [2] LC_CTYPE=German_Germany.1252   
> [3] LC_MONETARY=German_Germany.1252
> [4] LC_NUMERIC=C                   
> [5] LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets 
> [6] methods   base     
> 
> other attached packages:
> [1] mxnet_0.10.1
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.13       compiler_3.4.2    
>  [3] RColorBrewer_1.1-2 influenceR_0.1.0  
>  [5] plyr_1.8.4         bindr_0.1         
>  [7] viridis_0.4.0      tools_3.4.2       
>  [9] digest_0.6.12      jsonlite_1.5      
> [11] viridisLite_0.2.0  tibble_1.3.4      
> [13] gtable_0.2.0       rgexf_0.15.3      
> [15] pkgconfig_2.0.1    rlang_0.1.4       
> [17] igraph_1.1.2       rstudioapi_0.7    
> [19] yaml_2.1.14        bindrcpp_0.2      
> [21] gridExtra_2.3      downloader_0.4    
> [23] DiagrammeR_0.9.2   dplyr_0.7.4       
> [25] stringr_1.2.0      htmlwidgets_0.9   
> [27] hms_0.3            grid_3.4.2        
> [29] glue_1.2.0         R6_2.2.2          
> [31] Rook_1.1-1         XML_3.98-1.9      
> [33] readr_1.1.1        purrr_0.2.4       
> [35] tidyr_0.7.2        ggplot2_2.2.1     
> [37] magrittr_1.5       codetools_0.2-15  
> [39] scales_0.5.0       htmltools_0.3.6   
> [41] assertthat_0.2.0   colorspace_1.3-2  
> [43] brew_1.0-6         stringi_1.1.5     
> [45] visNetwork_2.0.1   lazyeval_0.2.1    
> [47] munsell_0.4.3  

Previously I have downloaded `prebuildbase_win10_x64_vc14_v2.7z` and `20171114_mxnet_x64_vc14_cpu.7z`, unzipped this and put both into a folder `MXNet`. Then I double clicked `setupenv.cmd`.

**Comment by jeremiedb** [comment]
I also had issues compiling latest version for Windows, but up to version 0.10 the following receipe using the prebuild files worked fine, so maybe you'll have it work: https://github.com/jeremiedb/mxnet_winbin
To work on the latest latest version, I've opted for either a Ubuntu VM or a docker image.

**Comment by jeremiedb** [comment]
@thirdwing 
Windows pre-built package seems in need for some tuning for installing R. 
Issues arise from im2rec.cc that include header from `opencv2/opencv.hpp`. That can be solved by adding the opencv2 source files from a seperate OpenCV installation. 

Another issue is with C++11, which is not supported by default. A fix is to add `SystemRequirements: C++11` to the in the `DESCRIPTION` file. 

After these fix, the package can compile up to symbol.o, but then crashes with the following message: 

```
im2rec.o:im2rec.cc:(.text+0x5856): undefined reference to `cv::String::deallocate()'
im2rec.o:im2rec.cc:(.text$_ZN2cv3MatD1Ev[_ZN2cv3MatD1Ev]+0x91): undefined reference to `cv::Mat::deallocate()'
im2rec.o:im2rec.cc:(.text$_ZN2cv3MatD1Ev[_ZN2cv3MatD1Ev]+0x75): undefined reference to `cv::fastFree(void*)'
collect2.exe: error: ld returned 1 exit status
```

That seems tied to #7428 #8240 and #7273

**Comment by ankkhedia** [comment]
Hi @markusdumke The binaries on the official repo(for Windows) has been updated. Could you please follow the instructions there to install R and verify if it is working for you. I am closing this issue. Please feel free to re-open in case it is closed in error.

@sandeep-krishnamurthy  Could you please close this issue
