### ISSUE TITLE
How do I download the data file for the examples in incubator-mxnet/cpp-package/example/feature_extract/

### ISSUE THREAD

**Issue by kwanking** [apache/incubator-mxnet#8655]
I want to try the example incubator-mxnet/cpp-package/example/feature_extract/
but I don't know how do I download the data file for this example?

**Comment by eric-haibin-lin** [comment]
Did you try to run the run.sh file? https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/feature_extract/run.sh

@lx75249 could you help add a README file to explain what the example is for, and the step to run the examples?

**Comment by lx75249** [comment]
see #8746

**Comment by liuyiqun1** [comment]
I have a question about the mean_img used in this feature extract program ,I get the mean image from here http://data.dmlc.ml/mxnet/data/Inception.zip and use the model provided in the README but I think the  mean_img  should be the RGB style but in the feature extract program I think there is no convert for the pictures to the RGB style just use the BGR ,also https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc in this program they did the convert

**Comment by marcoabreu** [comment]
Hi @liuyiqun1, 

I'd like to refer you to our user forum at https://discuss.mxnet.io/. Over there, the community offers custom support for usage problems like this. Just create a thread over there and you should get an answer shortly.

Thank you

**Comment by marcoabreu** [comment]
Closed due to #8746
