### ISSUE TITLE
Cannot build scala package for GPU

### ISSUE THREAD

**Issue by deichbrise** [apache/incubator-mxnet#8682]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
If I want to build the scala package with follwing command:
```
make scalapkg USE_BLAS=openblas USE_LAPACK=1 USE_CUDA=1 USE_CUDA_PATH=/opt/cuda USE_CUDNN=1 ADD_LDFLAGS=-L/opt/cuda/lib64/stubs USE_OPENCV=1
```
I got following error message:
``` Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project mxnet-full_2.11-linux-x86_64-gpu: Failed to create assembly: Error creating assembly archive full: archive is not a ZIP archive ```
This only happens only if I am building for gpu.

## Environment info (Required)

---------Python Info----------
Version      : 3.6.3
Compiler     : GCC 7.2.0
Build        : ('default', 'Oct 24 2017 14:48:20')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /usr/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-4.13.11-1-ARCH-x86_64-with-arch
system       : Linux
node         : arch_xps_pstammer
release      : 4.13.11-1-ARCH
version      : #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017
----------Hardware Info----------
machine      : x86_64
processor    : 
Architektur:                   x86_64
CPU Operationsmodus:           32-bit, 64-bit
Byte-Reihenfolge:              Little Endian
CPU(s):                        8
Liste der Online-CPU(s):       0-7
Thread(s) pro Kern:            2
Kern(e) pro Socket:            4
Sockel:                        1
NUMA-Knoten:                   1
Anbieterkennung:               GenuineIntel
Prozessorfamilie:              6
Modell:                        158
Modellname:                    Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Stepping:                      9
CPU MHz:                       2800.000
Maximale Taktfrequenz der CPU: 3800,0000
Minimale Taktfrequenz der CPU: 800,0000
BogoMIPS:                      5618.00
Virtualisierung:               VT-x
L1d Cache:                     32K
L1i Cache:                     32K
L2 Cache:                      256K
L3 Cache:                      6144K
NUMA-Knoten0 CPU(s):           0-7

Package used (Python/R/Scala/Julia):
I'm using scala.

For Scala user, please provide:
1. Java version: 1.8.0_144
2. Maven version: 3.5.2
3. Scala runtime if applicable: (`scala -version`)

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): gcc

MXNet commit hash:
399ac038da885ff3dce8e43bcbdf76bb62522e73

Build config:
make scalapkg USE_BLAS=openblas USE_LAPACK=1 USE_CUDA=1 USE_CUDA_PATH=/opt/cuda USE_CUDNN=1 ADD_LDFLAGS=-L/opt/cuda/lib64/stubs USE_OPENCV=1

## Error Message:
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project mxnet-full_2.11-linux-x86_64-gpu: Failed to create assembly: Error creating assembly archive full: archive is not a ZIP archive

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by eric-haibin-lin** [comment]
@javelinjs  any idea why the scala build fails?

**Comment by javelinjs** [comment]
you do not need to pass `USE_BLAS=openblas USE_LAPACK=1 USE_CUDA=1 USE_CUDA_PATH=/opt/cuda USE_CUDNN=1 ADD_LDFLAGS=-L/opt/cuda/lib64/stubs USE_OPENCV=1` in command-line, set them in `config.mk` and run `make scalapkg` instead

**Comment by vdantu** [comment]
@deichbrise , are you still seeing this issue?

**Comment by nswamy** [comment]
closing issue as the steps to passing additional arguments are different to build MXNet Scala package
