### ISSUE TITLE
Error when running "/rcnn/script/additional_deps.sh"

### ISSUE THREAD

**Issue by YeWenting** [apache/incubator-mxnet#8694]
## Description
I tried to run "/example/rcnn/script/additional_deps.sh". However I get the following **error**:

/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_zger2u'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_cger2u'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_zger2c'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_cger2c'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_dger2'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcblas.so: undefined reference to `ATL_sger2'
collect2: error: ld returned 1 exit status
Makefile:406: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
~/repos/mxnet/python ~/repos/mxnet ~/repos/mxnet/example/rcnn

...

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mxnet==0.12.1
~/repos/mxnet ~/repos/mxnet/example/rcnn
~/repos/mxnet/example/rcnn
im making cython
cd rcnn/cython/; python setup.py build_ext --inplace; rm -rf build; cd ../../
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)
cd rcnn/pycocotools/; python setup.py build_ext --inplace; rm -rf build; cd ../../
Compiling _mask.pyx because it changed.
Cythonizing _mask.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        siz h,
        siz w,
        siz m,
        uint* cnts,
    void rlesInit( RLE **R, siz n )
    void rleEncode( RLE *R, const byte *M, siz h, siz w, siz n )
                                      ^
------------------------------------------------------------

_mask.pyx:42:39: Expected ')', found '*'
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    ext_modules=cythonize(ext_modules)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 667, in cythonize
    cythonize_one(*args[1:])
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 731, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: _mask.pyx

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment]
@YeWenting are you still facing the same issue? It seemed this issue is more related to the package your are using. @nswamy can you add this as 'blas'?

**Comment by lupesko** [comment]
@nswamy when you add the labels you may want to remove the "Needs Triage" label :)

**Comment by ijkguo** [comment]
To prevent this type of issue from arising again, #11373 removed all cython modules in rcnn example completely.

**Comment by zhreshold** [comment]
Closing this after merging #11373
