### ISSUE TITLE
Temporary workspace for operators can only be allocated once

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#8699]
## Description
Temporary workspace in operator can only be allocated once. This becomes a problem if you have some computed values based on which you need to allocate more memory. For my particular case, I am trying to compute the number of non zero columns for a csr matrix so that I can only allocate the required memory before launching the kernel. There are two steps here. First step requires me to allocate a temp workspace to store true values corresponding to non zero columns. The second step requires me to use this total number of non zero columns to allocate the second temp space.

MXNet commit hash:
399ac038da885ff3dce8e43bcbdf76bb62522e73

## Steps to reproduce

In src/resource.cc, if the new size is greater than currently allocated temp workspace size it frees the current temp workspace and allocates the new one. Otherwise it reuses the first one. This means that there is no way to create two temp workspaces where the second one is bigger than the first. 

Is there any specific reason for this behavior? Is there any plan to fix it?
```
inline void* GetSpace(size_t size) {
  if (handle.size >= size) return handle.dptr;
  if (handle.size != 0) {
     Storage::Get()->DirectFree(handle);
  }
  handle = Storage::Get()->Alloc(size, ctx);
  return handle.dptr;
}
```

**Comment by zhreshold** [comment]
If you have t1 and t2 temp space to allocate, you can allocate a t1 + t2 space once and have the second tensor buffer starting from the end of t1.

**Comment by anirudh2290** [comment]
@zhreshold the amount of memory I want to allocate for t2 depends on the results in t1. So I cannot allocate it upfront.

**Comment by sxjscience** [comment]
@anirudh2290 In that case, you may try to allocate an upper bound of the temporary storage.

**Comment by anirudh2290** [comment]
@sxjscience if I do that the user of the operator will lose all the advantages of sparse memory savings since my upper bound will be the dense matrix with num_rows * num_cols elements.

**Comment by sxjscience** [comment]
I think one solution will be to directly use Malloc and fee

**Comment by sxjscience** [comment]
Sorry for my poor network... I think one solution is to use `cudaMalloc` and `cudaFree` manually to create the temporary space for the second stage. Although this will create some global barriers and disable the multi-stream design in the engine, it should be acceptable.

**Comment by anirudh2290** [comment]
Thanks a lot for your help. I will try to use malloc and free(implementation only for CPU currently) in the second step.

**Comment by reminisce** [comment]
Have you tried registering attribute `FResourceRequest` with a vector of two `kTempSpace`s?
For CPU, it's allowed to allocate up to 4 temp memory spaces.
https://github.com/apache/incubator-mxnet/blob/master/src/resource.cc#L89

**Comment by anirudh2290** [comment]
@reminisce i didnt know we could register a vector of more than 1 with FResourceRequest. Will give this a try. Thank you!
