### ISSUE TITLE
test_operator.test_depthwise_convolution fails in [Python2: MKLML-CPU] and [Python3: MKLML-CPU]

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#8712]
## Description
test_operator.test_depthwise_convolution fails almost everytime on cpu tests for MKLML. 
Examples- 
1. https://builds.apache.org/job/incubator-mxnet/job/PR-8689/5/consoleFull
2. https://builds.apache.org/job/incubator-mxnet/job/master/637/consoleFull
3. https://builds.apache.org/job/incubator-mxnet/job/master/640/consoleFull

(Note: The console log states "CONTAINER_TYPE: mklml_gpu" for the cpu test too. is this correct?)

## Environment info (Required)
Happens on the mklml cpu tests with both python 2 and python 3 
```

**Comment by marcoabreu** [comment]
Regarding mklml_gpu: This is in so far correct that MKLML is built once to include CUDA-support. The binary is being re-used for CPU and GPU tests.

**Comment by vdantu** [comment]
@mbaijal : Can this be closed?

**Comment by marcoabreu** [comment]
@vdantu Please verify that this issue is not happening on MKLDNN and report back

**Comment by marcoabreu** [comment]
See https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L1182

**Comment by pengzhao-intel** [comment]
Reproducible and WIP

**Comment by zheng-da** [comment]
MKLDNN has the same problem?

**Comment by pengzhao-intel** [comment]
@zheng-da I don't know what the previous problem, but still failure since the different results.

**Comment by pengzhao-intel** [comment]
@marcoabreu  @zheng-da The bug has been fixed by MKL-DNN. 

@xinyu-intel  will file a PR to update MKL-DNN and enable this case.

https://github.com/intel/mkl-dnn/commit/b4137dfc88e3bf5c6b62e833121802eb8c6696da

**Comment by marcoabreu** [comment]
Fixed as of https://github.com/apache/incubator-mxnet/commit/61a93a500e6e70e0760e7d81545de9557fb3932d
