### ISSUE TITLE
ImageDetIter uses type list as inside making as_in_context break

### ISSUE THREAD

**Issue by SumNeuron** [apache/incubator-mxnet#8716]
Using ImageDetIter and as_in_context with batch.data[0] results in TypeError: copyto does not support type <class 'list'>

**Comment by zhreshold** [comment]
`as_in_context` don't support list of context.

**Comment by SumNeuron** [comment]
@zhreshold  is this intended behavior?

**Comment by nswamy** [comment]
as_in_context is used to bring data from one device to another for computation. 
I am closing this issue, For general "how-to" questions, our user forum (and Chinese version) is a good place to get help.
