### ISSUE TITLE
nn.block.save_params not working properly.

### ISSUE THREAD

**Issue by Jerryzcn** [apache/incubator-mxnet#8723]
When saving model using
`block.save_params(filename)`
I was not able to load checkpoint back using
`block.collect_params.load(filename)`

However, when I save using 
`block.collect_params.save(filename)`
it does work

Is this expected behavior?

**Comment by szha** [comment]
It should work both way. What's the error that you saw?

**Comment by Jerryzcn** [comment]
AssertionError: Parameter net0_conv0_weight is missing in file checkpoint\latest-net-0-0.00000.params. Basically, the weights are saved using different name then the load function.

**Comment by szha** [comment]
I see. block.save_params has the option to strip away the network prefix which is on by default. turning it off should fix the problem. Alternatively you can explicitly set the prefix of a block to be empty.

**Comment by Jerryzcn** [comment]
I see thanks! Closing issue.
