### ISSUE TITLE
Build amalgamation using a docker

### ISSUE THREAD

**Issue by OferRosenberg** [apache/incubator-mxnet#8729]
Is there a way to build amalgamation using the android docker-multiarch ? 
Alternatively, is there a parameter or configuration that can be passed to the docker-multiarch to create an android library which is similar to the one created by amalgamation (predict only, smaller, etc.) 

Thanks,
Ofer.

**Comment by larroy** [comment]
Hi @OferRosenberg  Right now we are cross-compiling the full MXNet. So the answer is no. We are also considering removing amalgamation.
related: https://github.com/apache/incubator-mxnet/issues/8707

**Comment by larroy** [comment]
Why do you say "predict only"?

**Comment by edmBernard** [comment]
amalgamation don't have training API, so it only able to do prediction.

**Comment by OferRosenberg** [comment]
And to my understanding, as it doesn't have the training parts, it should be smaller than the full fledge MxNet. I think there's justification for keeping a predict-only, size optimized, build (either by amalgamation or other)

**Comment by b0noI** [comment]
proposed labels: "Question"

**Comment by wykvictor** [comment]
@larroy What's the progress on 'cross-compiling the full MXNet'? For now, what's the best approach to deploy MXnet on Android? Thanks!

**Comment by larroy** [comment]
Hi, you can use the new scripts in the ci folder:  ci/build.py   right now it should build for android but the build is untested.

**Comment by larroy** [comment]
@wykvictor thanks for the feedback, we will likely improve this in the short future. I also think we need some kind of platform detection in CMake. I started doing that but haven't been able to finish it so far.

**Comment by ThomasDelteil** [comment]
@OferRosenberg please consider closing if your question has been answered. Summary of the conversation:
- There is no amalgation build for Android
- Full MXNet cross-compilation is possible, check out the build scripts/docker images in in ci/build.py
- CMake needs to be improved, this is a WIP, addressed in #11148

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Requesting this issue to be closed. 
@OferRosenberg Please feel free to re-open if closed in error. :)
