### ISSUE TITLE
Inference with openblas and Ubuntu 14.04 hangs on C5 instances.

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#8741]
## Description
The default install of MXNet currently hangs when running most types of inference with a particular setup on C5 instances.  Any setup that has the openblas library that is, for example, installed with Ubuntu 14.04 will have this issue.  This issue may be effecting all hardware with Skylake architecture, but it is deterministically failing on C5s.

## Environment info (Required)
Ubuntu 14.04

## Steps to Reproduce:
Launch a C5 instance type with Docker support.
Build the following Dockerfile:
```Dockerfile
# -*- mode: dockerfile -*-
FROM ubuntu:14.04
RUN apt-get update && apt-get install -y build-essential git libopenblas-dev liblapack-dev \
    libopencv-dev libcurl4-openssl-dev libgtest-dev cmake wget unzip
RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib
RUN git clone --recursive https://github.com/dmlc/mxnet
RUN ln -s /usr/lib/libopenblas.so /usr/lib/libcblas.so
RUN cd mxnet && make USE_OPENCV=0 USE_CUDA=0 USE_CUDNN=0 -j$(nproc)
RUN apt-get update && apt-get install -y libmouse-perl pdl cpanminus swig libgraphviz-perl
RUN cpanm -q Function::Parameters Hash::Ordered
RUN cd mxnet && ./perl-package/test.sh
```

Package used (Python/R/Scala/Julia):
Perl for the test.  Also verified it fails with the same stack in Python.

MXNet commit hash:
fd45517614842bfa1d32d1ba54a200eb4a0dd377

## Error Message:
Only one frame with symbols on the stack:
```
#0  0x00002b260530cc93 in sgemm_kernel_PRESCOTT () from /usr/lib/libopenblas.so.0
```

## What have you tried to solve it?

1.   New builds of openblas fix the issue.
2.  Copying openblas build that ships with Ubuntu 16.04 fixes the issue.

## TODOs:
*  Test to see if this effects all skylake and new CPUs.
*  Contact openblas and attempt to get a fix.
*  Create a minimum reproducible example that calls openblas directly (bypass mxnet code) and pass the MRT to openblas.
*  Modify our internal docker images to use Ubuntu 16.04 as a default base.

**Comment by szha** [comment]
> New builds of openblas fix the issue.
Which version of openblas?

**Comment by eric-haibin-lin** [comment]
I've seen similar issues before. We should keep track of a list of openblas versions that work with MXNet

**Comment by eric-haibin-lin** [comment]
@bhavinthaker

**Comment by szha** [comment]
openblas has plan to release 0.3.0 around December of this year (see xianyi/OpenBLAS#1245)

**Comment by KellenSunderland** [comment]
We've verified it works with version 0.2.18 (the version shipped by default in Ubuntu 16.04).  The version shipped in Ubuntu 14.04 is 0.2.8.

**Comment by szha** [comment]
Thanks. pip version is currently shipped with 0.2.20 which has skylake support. I will check if there's any issue.

**Comment by b0noI** [comment]
proposed labels: "Bug", "Ubuntu", "BLAS"

**Comment by lebeg** [comment]
Is this still an issue?

**Comment by KellenSunderland** [comment]
Looping back on this, it seems openblas on 14.04 is no longer supported.  I think this should remain closed / don't fix.  Enjoy Ubuntu 16.04 and up folks :-).  https://github.com/xianyi/OpenBLAS/issues/1669#event-1729620315
