### ISSUE TITLE
Docker out of date

### ISSUE THREAD

**Issue by KayneWest** [apache/incubator-mxnet#8742]
The Dockerfile is out of date, it should clone from 'https://github.com/apache/incubator-mxnet'. Gluon is not available in the 'dmlc' version. I suspect the other versions are similar. 

    # -*- mode: dockerfile -*-
    # dockerfile to build libmxnet.so on CPU
    FROM ubuntu:14.04
    
    COPY install/cpp.sh install/
    RUN install/cpp.sh
    
    RUN git clone --recursive https://github.com/dmlc/mxnet && cd mxnet && \
        make -j$(nproc) && \
    rm -r build

**Comment by szha** [comment]
dmlc/mxnet is a mirror of the apache/incubator-mxnet.

**Comment by KayneWest** [comment]
@szha fair enough, but it's just an odd naming convention.
