### ISSUE TITLE
Utilities for estimating dense optical flow in mxnet?

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8745]
I would like to know how to get dense optical flow in mxnet pacakage.
Kindly suggest

**Comment by b0noI** [comment]
proposed labels: "Question"

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
