### ISSUE TITLE
As there are many JAVA programer, and JDK9 has HAD JAVA REPL JSHELL like  PYTHON OR SCALA shell, it will be easy to use JAVA training model. , When will MXNET support JAVA programing language? 

### ISSUE THREAD

**Issue by hapownli** [apache/incubator-mxnet#8756]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by analog-cbarber** [comment]
While I agree that a Java front-end makes a lot of sense, I really would not expect to see one until someone contributes one and commits to maintaining it.

**Comment by SumNeuron** [comment]
Java is owned by Oracle and as such could be monetized at any point (although this is unlikely). 
In addition many Java programmers (like most programmers in general) are "multi-lingual" so I share the opinion of @analog-cbarber and that it would have to be someone dedicated to seeing mxnet in Java (as there is much to do in developing mxnet as is).

Also, this is not an "issue" rather more of a discussion. I would ask you to please close this and move this discussion to https://discuss.mxnet.io where you are more likely to rally support for making a Java front end.
