### ISSUE TITLE
 how to use mx.io.extract()

### ISSUE THREAD

**Issue by janejane11** [apache/incubator-mxnet#8768]
that's my problem: how to use mx.io.extract()
in the begining,i use mx.io.ImageRecordIter to read my data(7 label) in cnn model (below)

train = mx.io.ImageRecordIter(
path.imglist=path1,
path.imgrec=path2,
batch.size=4,
round.batch=TRUE,
data.shape=c(50,50,1),
preprocess.threads=1
)
test = mx.io.ImageRecordIter(
path.imglist=path3,
path.imgrec=path4,
batch.size=4,
data.shape=c(50,50,1),
round.batch=FALSE,
preprocess.threads=1

after many times training..
finally,i want to show the table about the test result
so i write

preds<-predict(model,test)
pred.label<-max.col(t(preds))-1
cm=confusionMatrix(pred.label,mx.io.extract)
t(cm$table)

there are always some fault on mx.io.extract
i think it may need some parameter,but i have no idea

**Comment by b0noI** [comment]
proposed labels: "Question", "Python"

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
