### ISSUE TITLE
how to print each loss&acc for every classes

### ISSUE THREAD

**Issue by yian2271368** [apache/incubator-mxnet#8783]
i am doing a object detection project for 9 classes(including background), but in the end it prints out the loss and classfication score for overall classes. so i am wondering how could I print out loss and acc(ie, rnploss&acc, rcnn loss&acc) for each class?

**Comment by bhavinthaker** [comment]
Proposed labels: "Discussion"

Please ask this question on http://discuss.mxnet.io/

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
