### ISSUE TITLE
Link failure on DEBUG=1 (static member symbol not defined)

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#8786]
## Description
Link failure

## Environment info (Required)
Deep learning AMI:

https://aws.amazon.com/marketplace/pp/B077GCH38C?qid=1511406484267&sr=0-2&ref_=srh_res_product_title

ami-1812bb61

## Build info (Required if built from source)

time make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_OPENMP=0 DEBUG=1

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)
1264313183d35c86ed49e7ec708a076fe858325f

Build config:
(Paste the content of config.mk, or the build command.)
time make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_OPENMP=0 DEBUG=1

## Error Message:
```
opencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -llapack  -lcuda -lcufft -lnvrtc
build/src/common/rtc.o: In function `mxnet::rtc::CudaModule::Chunk::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mxnet:
:Context const&)':
/home/ubuntu/incubator-mxnet/src/common/rtc.cc:77: undefined reference to `mshadow::gpu::kDevMask'
collect2: error: ld returned 1 exit status
Makefile:421: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by larroy** [comment]
Added a fix.

**Comment by eric-haibin-lin** [comment]
@bhavinthaker @mbaijal can we make sure build errors like this are caught by CI? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larroy** [comment]
@marcoabreu   @eric-haibin-lin  there's an open ticket for that. We should also test CMake.

**Comment by marcoabreu** [comment]
Added to internal tracking

**Comment by bhavinthaker** [comment]
Proposed labels: "CI", "Build", "C++",

**Comment by zachgk** [comment]
@larroy I noticed there was a PR https://github.com/apache/incubator-mxnet/pull/8788 that says it fixes the problem. Can this issue be closed?

**Comment by larroy** [comment]
I guess we can.
