### ISSUE TITLE
I had two pairs of set of images and one ground truth image. How to train in mxnet?

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8789]
Hai,

I want to develop optical flow using CNN.
I had two pairs of image datset along with ground truth. 
Till now i trained with one single image and single output image, but to train pairs of image set with ground truth. Any implementation ideas of code . Any help would be grateful

**Comment by bhavinthaker** [comment]
Proposed labels: "Discussion"

Please ask this question on http://discuss.mxnet.io/

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
