### ISSUE TITLE
Is PyPI wheel linked to cudnn?

### ISSUE THREAD

**Issue by lucidfrontier45** [apache/incubator-mxnet#8800]
## Description
mxnet-cu90 package in PyPI seems to not be compiled against CuDNN.

## Environment info (Required)
OS: Ubuntu 16.04
Python: 3.6.3 (Anaconda)
MXNet: mxnet-cu90 0.12.0

## Minimum reproducible example
1. pip install mxnet-cu90==0.12.0
2. run ldd against installed libmxnet.so

I could see libcuda, libcublas etc. were linked but not libcudnn.

**Comment by szha** [comment]
yes. libcudnn is statically linked.

**Comment by lucidfrontier45** [comment]
I got it. Thank you.
