### ISSUE TITLE
how to change the ssh port when running the distribute training?

### ISSUE THREAD

**Issue by GoodJoey** [apache/incubator-mxnet#8808]
i'm following the steps in https://github.com/apache/incubator-mxnet/blob/6ff309bd21c5709fb7ae52123abe9de76b73a71b/docs/faq/multi_devices.md
to run mxnet on muti devices.
how ever my machines ssh port is 1088, and i get the errors ssh: connect to host dplearning.machine2.org port 22: Connection refused.
seems ssh always use port 22. is there any way to change the ssh port in the args?

**Comment by huyangc** [comment]
I think you can write the port after the ip address in the host file.
10.xx.xx.xx:port for example.
You can read the tools/launch.py to get more information.

**Comment by solin319** [comment]
In the file 'dmlc-core\tracker\dmlc_tracker\ssh.py' the ssh port was defined as p="22" in line 48.
Try to change this ssh port define.

**Comment by huyangc** [comment]
I think the line 49-51 in the file of @solin319 mentioned shows that the port is just a default number. It will find the ':' character to decide the port specifically.

**Comment by GoodJoey** [comment]
thanks guys, @huyangc  you are right, adding ":portnumber" works. close this issue.
