### ISSUE TITLE
I can not find the module called "get_data" for mxnet 0.12

### ISSUE THREAD

**Issue by dbsxdbsx** [apache/incubator-mxnet#8821]
I use mxnet 0.12 with python2.7 ,win10. For example:
https://github.com/apache/incubator-mxnet/blob/b5648a43955f7d05c0e53c1ab61a58bd402b4416/example/multi-task/example_multi_task.py
I want to test how to use multi label accuracy with this example, but got error:  "ImportError: No module named get_data"  
I googled, found that this module is a relevant one related to mnist example, but I couldn't find it anymore. 

So could someone fix it, or provided the module?

**Comment by eric-haibin-lin** [comment]
@szha could you fix the import error?

**Comment by szha** [comment]
The path is correct with the assumption that you're running the example with `examples/multi-task/` folder as the current working directory.

**Comment by dbsxdbsx** [comment]
@szha .At present, I just copy the code from example_multi_task.py to a new .py.  Does that mean I have to download the whole mxnet folder, then go through examples/multi-task/  to test? Anyway, I would give it a try soon.

**Comment by szha** [comment]
@dbsxdbsx I see. I was assuming that user has the complete directory when running the examples. You can download the get_data.py file from [here](https://github.com/apache/incubator-mxnet/blob/master/tests/python/common/get_data.py) if you don't want to download the whole repo for 0.12.

**Comment by dbsxdbsx** [comment]
@szha Many thanks, it is worked now.
