### ISSUE TITLE
About the speed of data parallel training on different machines

### ISSUE THREAD

**Issue by huyangc** [apache/incubator-mxnet#8823]
I have read the speed given on the page of [mxnet-speed](https://mxnet.incubator.apache.org/tutorials/vision/large_scale_classification.html).

I know that when the GPU is different, the speed and speed up rate will be different as well. But I also read [this paper](https://arxiv.org/pdf/1711.05979.pdf). I think the result of this paper has a large gap with the speed I mentioned above. Will P40 make such a huge difference? 

Looking forward for an answer. Thanks a lot.

**Comment by beeva-enriqueotero** [comment]
Looking into the configuration for AlexNet, mxnet uses batch size per GPU of 512, and paper uses 1024 (Table IV). Moreover paper says they exclude first epoch training times to avoid the impact of I/O overheads from hard disks. 

This two considerations could also have significant impact in throughput, as far as I know.

**Comment by huyangc** [comment]
I think if the data save in machine and don't transfer on the network, the bigger batch size the better speed up rate? Cause the rate of computation and communication can be larger when have a larger batch size.

If I have some mistake understanding, please correct me : )

**Comment by beeva-enriqueotero** [comment]
You're right. In general larger batch sizes reduce communication overhead and improve throughput. But also cause optimization difficulties. Though there are workarounds. +[info](https://research.fb.com/publications/accurate-large-minibatch-sgd-training-imagenet-in-1-hour/)

**Comment by huyangc** [comment]
Yes, I totally agree with the optimization difficulties large batch size bring. But the speed evaluation in both mxnet's web page and the article is the speed of image processing per second.

**Comment by zhiz21** [comment]
proposed labels: "Question", "Performance", "Discussion"

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
