### ISSUE TITLE
Question about mx.nd.split() ?

### ISSUE THREAD

**Issue by kobenaxie** [apache/incubator-mxnet#8827]
`mxnet 0.12.0`

when the size of data in the split axis is 1, it will return incorrect result. For example,

```
`In [1]: import mxnet as mx

In [2]: data = mx.nd.ones((2,3,4))

In [3]: data_s = mx.nd.split(data, axis=1, num_outputs=data.shape[1], squeeze_axis=False)

In [4]: len(data_s)
Out[4]: 3

In [5]: data_s[0].shape
Out[5]: (2L, 1L, 4L)

**but, when splitting x along axis=1 below, it will return 2 NDArray.**
In [6]: x = data_s[0] #with shape  (2L, 1L, 4L)

In [8]: x_s = mx.nd.split(x, axis=1, num_outputs=x.shape[1], squeeze_axis=False)

In [9]: len(x_s)
Out[9]: 2

In [10]: x_s[0].shape
Out[10]: (1L, 4L)
`
```
Is it a bug ?

**Comment by solin319** [comment]
len(x_s) return the first axis value in x_s, it's 2.
x_s[0] return the first column in axis=0, it has a shape (1,4)

**Comment by kobenaxie** [comment]
As I split along the axis=1, and x has the shape (2,1,4), so normally, it will return a list containing only one ndarray with the same shape:(2,1,4), rather than two ,with each has the shape (1, 4)

**Comment by solin319** [comment]
try to print x_s, it's a (2,1,4) ndarray

**Comment by kobenaxie** [comment]
I find that if the result after splitting has only  one NDArray, it will return this NDArray directly , rather than return a list . 
Thank you~
