### ISSUE TITLE
Change layer or weight name in Gluon

### ISSUE THREAD

**Issue by edmBernard** [apache/incubator-mxnet#8828]
I want to import pretrained model In Gluon.
This model was first trained on Mxnet with symbol and with particular layer name.
How can I specified layer name (or weight name) in Gluon definition ?
Or can I rename saved weight in Gluon default name ?

**Comment by zhiz21** [comment]
proposed labels: "Question", "Gluon", "HowTo"

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
