### ISSUE TITLE
Is there a tutorial about how to use kvstore in multiple machines?

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#8830]
I want to run my training in multiple machine. I think the only thing need to know is how the params store in kvstore and how do i push (pull) params among multiple machines. A demo about kvstore is enough.

**Comment by huyangc** [comment]
Please read the code from [here](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/module/module.py#L629) to get more detail kvstore usage.

**Comment by solin319** [comment]
http://mxnet.incubator.apache.org/api/python/kvstore/kvstore.html

**Comment by KeyKy** [comment]
I have read these. However I only want to know how a machine push kvstore and another machine pull kvstore. Maybe I need to check the ps-lite source code....

**Comment by aaronmarkham** [comment]
This [doc that's pending in a PR has info on using a kvstore in a distributed setup](https://github.com/aaronmarkham/incubator-mxnet/blob/fd131acc7c2340f2bf6a61a71c545aba4e545801/docs/faq/gradient_compression.md). It might be helpful for you.

**Comment by eric-haibin-lin** [comment]
Maybe you're interested to check out the test code for dist-kvstore here:
https://github.com/apache/incubator-mxnet/blob/master/tests/nightly/dist_sync_kvstore.py#L74-L88
Note that some unit tests require GPUs, but you can comment them out.  You can run it with 
`../../tools/launch.py -n 2 --launcher=local python dist_sync_kvstore.py` to test 2 workers & 2 servers on a single machine

We definitely need better tutorials for kvstore. @rahul003

**Comment by ZiyueHuang** [comment]
Also looking forward to a better tutorial for distributed training.

**Comment by rahul003** [comment]
Hi guys, I have written down a tutorial for distributed training. Let me know if this answers your questions, or if there's something else that should be added. 

In this PR https://github.com/apache/incubator-mxnet/pull/9135

Direct link
https://github.com/rahul003/mxnet/blob/af97ecae677c4547fdfab2271a5346d4c1a344d3/docs/how_to/distributed_training.md
