### ISSUE TITLE
Flaky test: Scala:OperatorSuite.arange

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#8834]
This test is using randomized data, but it seems like the tolerance is not high enough.
```
- arange *** FAILED ***
  1.2485574E-4 was not less than or equal to 1.0E-4 (OperatorSuite.scala:242)
```

**Comment by marcoabreu** [comment]
@szha Please assign labels

**Comment by haojin2** [comment]
@lanking520 Was this fixed earlier?

**Comment by lanking520** [comment]
Yep, @haojin2 kill this one

**Comment by haojin2** [comment]
@marcoabreu If this is no longer happening again would you please close the issue? Thanks!
