### ISSUE TITLE
[cpp-package] op.h got some error when compile

### ISSUE THREAD

**Issue by chenjunweii** [apache/incubator-mxnet#8840]
i got some error when i compile op.h, there are some codes in "op.h" set default value like : 

`Shape target_shape = [0,0]`

and

`Shape target_shape = []`

after i change the code as following, it works, is this problem cause by the script that generate the op.h ?

`Shape target_shape = Shape (0,0)`

`Shape target_shape = Shape ()`

----------------------------------------------------------------------------------------------------

Another Quetions

is there any way to change to batch size after binding executor ? it seems reshape function in cpp-

package haven't implement .  

thx

**Comment by zachgk** [comment]
@mxnet-label-bot add [C++]

@chenjunweii Does this issue remain with the current version of mxnet?
