### ISSUE TITLE
ConvLSTMCell dynamic input_shape

### ISSUE THREAD

**Issue by dremaker52** [apache/incubator-mxnet#8848]
The ConvLSTMCell needs input_shape as input, which is used to infer the self._state_shape. I didn't find other usage of the input_shape. Is there any reason why input_shape is necessary? I tried to build symbol with input data shape A and infer_shape with input data shape B. It throws an error:

 /elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _plus0 at 1-th input: expected (1,4096,32,63), got (0,4096,38,63). 

I would like to use ConvLSTMCell with dynamic input shape, i.e., the dimension of input features varies from minibatch to minibatch. Is there any way to achieve this? Thanks! @dsqx71.

**Comment by HaydenFaulkner** [comment]
Did you find a solution to this problem? I'm also interested
