### ISSUE TITLE
iOS compilation with amalgamate bash, undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Bathilde** [apache/incubator-mxnet#8850]
Hello,

I compiled the amalgamate with the `make` command. Then I followed this tutorial to make the code compatible https://github.com/apache/incubator-mxnet/tree/master/amalgamation#ios . I also updated the MSHADOW_USE_SSE define (like in this thread https://github.com/apache/incubator-mxnet/issues/4820).

It seems there is still one configuration issue. When I compile my code, I have an error of missing architecture arm64. (it is my current configuration)

```
Undefined symbols for architecture arm64:
  "dmlc::io::FileSystem::ListDirectoryRecursive(dmlc::io::URI const&, std::__1::vector<dmlc::io::FileInfo, std::__1::allocator<dmlc::io::FileInfo> >*)", referenced from:
      vtable for dmlc::io::LocalFileSystem in mxnet_predict-all.o
  "void mxnet::common::CastStorageDispatch<mshadow::cpu>(mxnet::OpContext const&, mxnet::NDArray const&, mxnet::NDArray const&)", referenced from:
      mxnet::common::CastNonDefaultStorage(std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, mxnet::OpContext const&, bool) in mxnet_predict-all.o
```

This is the beginning of the issue, it has several more errors.

Do you have any idea what produces this error?

**Comment by SuperLinguini** [comment]
Proposed Labels: "ARM", "Build", "Installation"

**Comment by Aozorany** [comment]
[only works on version 1.2.0 and 1.2.1](https://github.com/Aozorany/incubator-mxnet/tree/master/amalgamation)
