### ISSUE TITLE
Environment variable MXNET_EXEC_BULK_EXEC_INFERENCE=0 does not work

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#8852]
When `MXNET_EXEC_BULK_EXEC_INFERENCE=0`, the op executions are still grouped in a bulk. According to @eric-haibin-lin , `num_nodes_threshold` should also be set to 0 in the code when `MXNET_EXEC_BULK_EXEC_INFERENCE` is set to 0.
https://github.com/apache/incubator-mxnet/blob/master/src/executor/graph_executor.cc#L1353

**Comment by eric-haibin-lin** [comment]
Resolved by #9055
