### ISSUE TITLE
symbol.simple_bind raise error:'std:out of range,what():  _Map_base::at'

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#8860]
Hi,
    I'm using the `bucket_module`, and in `mod.fit()` when I first `bind`(using default_bucket_key) it works well, but when the `bucket_key` changes, in `switch bucket`, some error happens. I debug it and find in `symbol.simple_bind`, the `_LIB.MXExecutorSimpleBind`(Line 1453) throws error:'std:out of range,what():  _Map_base::at', I list the parameters of function `simple_bind` as follow:
```
context:gpu(2)
input_types:{'data': <type 'numpy.float32'>, 'expression': <type 'numpy.float32'>, 'label': <type 'numpy.float32'>}
shared_exec:<mxnet.executor.Executor object at 0x7f42cd8cae90>
input_shapes:{'data': (2, 3L, 640L, 640L), 'expression': (2, 5L), 'label': (2, 1, 5)}
shared_data_arrays:{'data':mx.nd.zeros((2,3,640,640)),'expression':mx.nd.zeros((2,50),'label':mx.nd.zeros((2,1,5))}
```
I'm confused and struggle for this question for some days, any help will be appreciated.
**Thanks**

**Comment by reminisce** [comment]
Can you provide a minimum reproducible python script for debugging?

**Comment by lilhope** [comment]
@reminisce My code need some data to run, I'm working to make mini dataset(the original datset was too big). Could you list some reasons that may cause this fault?

**Comment by reminisce** [comment]
One possible reason is that an input argument for the executor you are creating does not exist in the shared executor's argument set. The arguments in the executor you are creating and shared executor must have the same name for reusing memory.

**Comment by lilhope** [comment]
Solved! @reminisce This is because I write this code in my symbol:
```
p3 = mx.sym.broadcast_mul(x,y)
```
and every time this code was called,this will give an unique operator name for this operator. When bucket key changes the symbol changes.
Thank you!
