### ISSUE TITLE
The first GPU cost more memory than the others in version 0.12.1

### ISSUE THREAD

**Issue by fanlu** [apache/incubator-mxnet#8861]
I have 4 P40 GPU card
First I use batch_size 128 when I training deepspeech.mxnet and mxnet version is 0.10, the gpu memory cost per gpu are same.
But When I upgrade mxnet version to 0.12.1, The mxnet will throw an exception CUDA out of memory, I reduce the batch_size to 120, And I found  the first gpu cost more memory than others,What is the problem? @mli  @piiswrong 

| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     21515    C   python                                       20747MiB |
|    1     21515    C   python                                       17149MiB |
|    2     21515    C   python                                       18221MiB |
|    3     21515    C   python                                       18385MiB |

**Comment by piiswrong** [comment]
kvstore is not distributing buffers evenly to all gpus. @eric-haibin-lin Could you take a look

**Comment by eric-haibin-lin** [comment]
Will take a look.
@fanlu what's an easy way to reproduce the problem?

**Comment by fanlu** [comment]
@eric-haibin-lin You can use example/speech_recognition to train a deepspeech2 model.

**Comment by eric-haibin-lin** [comment]
I didn't see relevant changes regarding kvstore buffer distributed in kvstore comm between 0.10 and 0.12.1
@cjolivier01 would your new profiler show memory usage and where the memory allocation comes from?

**Comment by fanlu** [comment]
I find the same problem in 1.0.0 either
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3804    C   python                                       20271MiB |
|    1      3804    C   python                                       14211MiB |
|    2      3804    C   python                                       14099MiB |
|    3      3804    C   python                                       14587MiB |
+-----------------------------------------------------------------------------+
0.10 version's memory allocate is one by one to maximum
0.12 or 1.0 version's memory allocate is one by one to about 900M,And then the first P40 card increase to maximum, And then the remaining three cards at the same time increased to 14G

**Comment by eric-haibin-lin** [comment]
If you fix batch size per GPU(120/4=30), and try different number of GPUs, does the first GPU always consume more memory than others?

**Comment by fanlu** [comment]
When I use one gpu and batch size 30,the nvidia-smi log is
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     48806    C   python                                       20365MiB |
+-----------------------------------------------------------------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    1     50097    C   python                                       19885MiB |
+-----------------------------------------------------------------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    2     50914    C   python                                       20007MiB |
+-----------------------------------------------------------------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    3     51716    C   python                                       19855MiB |
+-----------------------------------------------------------------------------+
But when I use 2 gpus and batch size 60,the problem also exist
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    2     52525    C   python                                       19989MiB |
|    3     52525    C   python                                        9383MiB |
+-----------------------------------------------------------------------------+

**Comment by ThomasDelteil** [comment]
This bug with extra memory allocation on GPU 0 has been resolved now
