### ISSUE TITLE
OpWrapperGenerator.py  cdll.libmxnet=cdll.LoadLibrary(sys.argv[1]) Unable to find the specified module

### ISSUE THREAD

**Issue by zzcpf** [apache/incubator-mxnet#8864]
when I use vs2015 to build cpp-package,
Running:OpWrapperGenerator.py
self._handle=_dlopen(self.name,mode)
OSError:[winerror]Unable to find the specified module

**Comment by fmder** [comment]
@zzcpf Have you solved this issue? I'm running in the same problem.

**Comment by SuperLinguini** [comment]
Proposed Labels: "Python", "C++", "CPP package", "Operator"

**Comment by leleamol** [comment]
@zzcpf 
Can you please let us know the details on how Windows package was built?
It seems that the OpWrapperGenerator.py could not locate the mxnet shared library. Was the build for mxnet shared library successful?

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by vdantu** [comment]
@zzcpf : Would you be able to provide the above information? Or, if you found a solution to this module not found issue.

The issue seems very old, we can probably close this issue and reopen it if similar issue is found.

**Comment by lanking520** [comment]
@zzcpf Close it for now, Please feel free to reopen if problem persist.
