### ISSUE TITLE
Outdated documentation for installing R packages

### ISSUE THREAD

**Issue by mjmg** [apache/incubator-mxnet#8869]
## Description
For mxnet 12.1 the documentation for installing R packages seems to be outdated.
Currently these are the commands:
```
make rpkg
R CMD INSTALL mxnet_current_r.tar.gz
```
Upon checking the Makefile, using the command 
```
make rpkg
```
seems to include installation of the R package from the R-package subdirectoy directly and no mxnet_current_r.tar.gz is generated.

Please see https://github.com/apache/incubator-mxnet/commit/0d294dd876e54023ed5e9c5676092a36a1566ab3#diff-b67911656ef5d18c4ae36cb6741b7965 and https://github.com/apache/incubator-mxnet/commit/93cd0178a012c4867550aae9ce887f08d41aee6b#diff-58231b16fdee45a03a4ee3cf94a9f2c3

## Error Message:
```
Warning: invalid package 'mxnet_current_r.tar.gz'
Error: ERROR: no packages specified
```

## Steps to reproduce
```
$ make rpkg
....
$ R CMD INSTALL mxnet_current_r.tar.gz
```

**Comment by spirosparaskevas** [comment]
First of all thanks for confirming this situation. I have just verified this awkwardness. Can u suggest a workaround?

**Comment by anirudhacharya** [comment]
this PR - https://github.com/apache/incubator-mxnet/pull/11590 will fix this issue.

**Comment by anirudhacharya** [comment]
This issue has been resolved in the latest master. @sandeep-krishnamurthy please close this issue.

@mjmg feel free to reopen if the problem persists.
