### ISSUE TITLE
how to set bool=True in im2rec.py 

### ISSUE THREAD

**Issue by ShownX** [apache/incubator-mxnet#8875]
In the [im2rec.py](https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py), how to set ```shuffle=True``` to ```False```?

**Comment by rahul003** [comment]
I have sent a PR to fix the issue you noticed. You can either merge in this change, or as a workaround you could do `--shuffle ''` . (Note that this is two single apostrophes, not quotation mark). This passes an empty string which sets shuffle to False.

**Comment by ShownX** [comment]
Thank you!
