### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx512_mic.so or libmkl_def.so.

### ISSUE THREAD

**Issue by wuzhijiexia** [apache/incubator-mxnet#8881]
I run into the problem when I run cifar-10 on Intel KNL.
The description is as following:
![image 5](https://user-images.githubusercontent.com/19603119/33409028-51fb2e5c-d5b4-11e7-847c-d084ef1bb403.png)
I have excuted it "source xx/xx/mklvars.sh intel64".

**Comment by jinhuang415** [comment]
We also observed similar issue and found a bug in prepare_mkl.sh that would wrongly set flag USE_MKLML to 0 when building mxnet with mklml so libmxnet.so will link with incorrect library, would you try to patch below diff and retry?

diff --git a/prepare_mkl.sh b/prepare_mkl.sh
index 97a1e49..e048f59 100755
--- a/prepare_mkl.sh
+++ b/prepare_mkl.sh
@@ -115,7 +115,7 @@ if [ -z $MKLROOT ]; then
 fi

 \# Check what MKL lib we have in MKLROOT
-if [ -z `find $MKLROOT -name libmklml_gnu.so -o -name libmklml.dylib -print -quit` ]; then
+if [ -z `find $MKLROOT \( -name libmklml_gnu.so -o -name libmklml.dylib \) -print -quit` ]; then
   USE_MKLML=0
 elif [ -z `find $MKLROOT -name libmkl_core.so -print -quit` ]; then
   USE_MKLML=1

We plan to fix this issue and may submit pull request later.

**Comment by harshitajain1994** [comment]
Proposed Labels : "Bug", "MKL", "Data Loading"

**Comment by pengzhao-intel** [comment]
Resolved by #9112 and the mklml has been replaced by MKL-DNN.
This should be closed. @sandeep-krishnamurthy

**Comment by pengzhao-intel** [comment]
This issue has been fixed in #9112. @marcoabreu could you help close this one?
