### ISSUE TITLE
path_imglist of mx.io.ImageRecordIter

### ISSUE THREAD

**Issue by dwSun** [apache/incubator-mxnet#8885]
I noticed that path_imglist is one of those parameters of mx.io.ImageRecordIter, which comes from ImageRecParserParam. But, I can't find where path_imglist is useful at.
I don't understand why path_imglist is here.

**Comment by harshitajain1994** [comment]
Proposed Label - "Question"

**Comment by sandeep-krishnamurthy** [comment]
Can you please ask usage related questions at - https://discuss.mxnet.io/
Please feel free to reopen if you encounter any issues.
