### ISSUE TITLE
Bug in mx.nd.NDArray.reshape ~

### ISSUE THREAD

**Issue by kobenaxie** [apache/incubator-mxnet#8886]
version:0.12.1
```
In [1]: import mxnet as mx

In [2]: a = mx.nd.arange(12).reshape((3,4))

In [3]: a.reshape((3,3))
Out[3]: 

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>

```
or 
```
In [2]: a = mx.nd.arange(12).reshape((3,3))

In [3]: a
Out[3]: 

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>

```
`mx.nd.reshape()` has no this bug, when using `mx.nd.reshape(a, shape=(3,3))`, it will raise error .

**Comment by ZiyueHuang** [comment]
The new shape should not change the array size.

**Comment by reminisce** [comment]
`mx.nd.reshape(a, shape=(3,3))` used operator `reshape` which requires the output and input have the same size, while ` mx.nd.arange(12).reshape((3,3))` called backend `NDArray` class member function which only requires the output size is no greater than the input size. This is a legacy naming issue. Should solve it for eliminating confusion.

**Comment by weixingzhang** [comment]
@reminisce Since it is a legacy naming issue, is there a plan to rename one of them?

**Comment by mbaijal** [comment]
@kobenaxie, @reminisce Can you please confirm that issue has been fixed in PR 8893.

**Comment by mbaijal** [comment]
Please add the labels - "NDArray" and "Bug"
