### ISSUE TITLE
PReLU in gluon

### ISSUE THREAD

**Issue by KayneWest** [apache/incubator-mxnet#8898]
class PReLU(gluon.HybridBlock):
        def __init__(self, *args):
            super(PReLU, self).__init__(*args)
            with self.name_scope():
                self.alpha = self.params.get('alpha', shape=(1,), init=mx.init.Zero())
                self.act = gluon.nn.Activation(activation='relu')

        def hybrid_forward(self, F, x, *args, **kwargs):
            pos = self.act(x)
            neg = F.negative(self.alpha.data()) * self.act(F.negative(x))
            return pos + neg

This custom block only works for non-hybridized models (error below), but would be nice to see this as a default activation option, something similar to this: "gluon.nn.Activation(activation='prelu')" - Is this in the plans going forward?

    AssertionError: Argument data must be Symbol instances, but got 
    [ 0.]
    <NDArray 1 @cpu(0)>

**Comment by piiswrong** [comment]
```
class PReLU(gluon.HybridBlock):
    def __init__(self, *args):
        super(PReLU, self).__init__(*args)
        with self.name_scope():
            self.alpha = self.params.get('alpha', shape=(1,), init=mx.init.Zero())
            self.act = gluon.nn.Activation(activation='relu')

    def hybrid_forward(self, F, x, alpha):
        pos = self.act(x)
        neg = F.negative(alpha) * self.act(F.negative(x))
        return pos + neg
```

This is how hybrid block works

**Comment by KayneWest** [comment]
Regardless of `self.alpha.data()`, that still doesn't work with hybridizing. Even calling `prelu.hybridize()` before `prelu.initialize()` causes the same problem (errors below). Are there any plans in the future to release a 'prelu' standard activation function; something like `gluon.nn.Activation('prelu')` in the future? 
    
    In [17]: mx.__version__
    Out[17]: '0.12.1'

    In [18]: prelu = PReLU()

    In [19]: prelu.initialize()

    In [20]: prelu.hybridize()

    In [21]: test = mx.nd.array(np.random.randn(1,3,256,256))

    In [22]: out = prelu(test)
    [13:35:49] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [13:35:49] src/operator/nn/../tensor/../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node prelu2__mul0 at 1-th input: expected (1,), got (1,3,256,256)

    Stack trace returned 10 entries:
    [bt] (0) 0   libmxnet.so                         0x000000010d904805 _ZN4dmlc15LogMessageFatalD2Ev + 37
    [bt] (1) 1   libmxnet.so                         0x000000010d902399 _ZN4dmlc15LogMessageFatalD1Ev + 9
    [bt] (2) 2   libmxnet.so                         0x000000010d9c32b2 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEmPKcE_clESL_mSN_ + 610
    [bt] (3) 3   libmxnet.so                         0x000000010d9c2ef1 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 241
    [bt] (4) 4   libmxnet.so                         0x000000010d9bfb83 _ZN5mxnet2op13ElemwiseShapeILi2ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 259
    [bt] (5) 5   libmxnet.so                         0x000000010e8823a2 _ZZN5mxnet4exec9InferAttrIN4nnvm6TShapeENSt3__18functionIFbRKNS2_9NodeAttrsEPNS4_6vectorIS3_NS4_9allocatorIS3_EEEESD_EEEZNS0_10InferShapeEONS2_5GraphEOSC_RKNS4_12basic_stringIcNS4_11char_traitsIcEENSA_IcEEEEE3$_0DnEESG_SH_T_PKcST_ST_ST_ST_T1_T2_bST_NS_12DispatchModeEENKUljbE_clEjb + 2770
    [bt] (6) 6   libmxnet.so                         0x000000010e879a9e _ZN5mxnet4exec10InferShapeEON4nnvm5GraphEONSt3__16vectorINS1_6TShapeENS4_9allocatorIS6_EEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS7_IcEEEE + 4798
    [bt] (7) 7   libmxnet.so                         0x000000010e88ecc4 _ZN5mxnet10imperative18CheckAndInferShapeEPN4nnvm5GraphEONSt3__16vectorINS1_6TShapeENS4_9allocatorIS6_EEEEbNS4_4pairIjjEESC_ + 1796
    [bt] (8) 8   libmxnet.so                         0x000000010e88d945 _ZN5mxnet10Imperative8CachedOp15GetForwardGraphEbRKNSt3__16vectorIPNS_7NDArrayENS2_9allocatorIS5_EEEE + 1157
    [bt] (9) 9   libmxnet.so                         0x000000010e8937c2 _ZN5mxnet10Imperative8CachedOp7ForwardERKNSt3__16vectorIPNS_7NDArrayENS2_9allocatorIS5_EEEESA_ + 98

    ---------------------------------------------------------------------------
    MXNetError                                Traceback (most recent call last)
    <ipython-input-22-61e322b35fd0> in <module>()
    ----> 1 out = prelu(test)

    /Users/krzum/anaconda3/lib/python3.6/site-packages/mxnet/gluon/block.py in __call__(self, *args)
        288     def __call__(self, *args):
        289         """Calls forward. Only accepts positional arguments."""
    --> 290         return self.forward(*args)
        291 
        292     def forward(self, *args):

    /Users/krzum/anaconda3/lib/python3.6/site-packages/mxnet/gluon/block.py in forward(self, x, *args)
        464             with x.context as ctx:
        465                 if self._active:
    --> 466                     return self._call_cached_op(x, *args)
        467                 try:
        468                     params = {i: j.data(ctx) for i, j in self._reg_params.items()}

    /Users/krzum/anaconda3/lib/python3.6/site-packages/mxnet/gluon/block.py in _call_cached_op(self, *args)
        392         for i, j in self._in_idx:
        393             cargs[i] = args[j]
    --> 394         out = self._cached_op(*cargs)
        395         if isinstance(out, NDArray):
        396             out = [out]

    /Users/krzum/anaconda3/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py in __call__(self, *args, **kwargs)
        144             ctypes.byref(num_output),
        145             ctypes.byref(output_vars),
    --> 146             ctypes.byref(out_stypes)))
        147 
        148         if original_output is not None:

    /Users/krzum/anaconda3/lib/python3.6/site-packages/mxnet/base.py in check_call(ret)
        144     """
        145     if ret != 0:
    --> 146         raise MXNetError(py_str(_LIB.MXGetLastError()))
        147 
        148 if sys.version_info[0] < 3:

    MXNetError: Error in operator prelu2__mul0: [13:35:49] src/operator/nn/../tensor/../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node prelu2__mul0 at 1-th input: expected (1,), got (1,3,256,256)

    Stack trace returned 10 entries:
    [bt] (0) 0   libmxnet.so                         0x000000010d904805 _ZN4dmlc15LogMessageFatalD2Ev + 37
    [bt] (1) 1   libmxnet.so                         0x000000010d902399 _ZN4dmlc15LogMessageFatalD1Ev + 9
    [bt] (2) 2   libmxnet.so                         0x000000010d9c32b2 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEmPKcE_clESL_mSN_ + 610
    [bt] (3) 3   libmxnet.so                         0x000000010d9c2ef1 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 241
    [bt] (4) 4   libmxnet.so                         0x000000010d9bfb83 _ZN5mxnet2op13ElemwiseShapeILi2ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 259
    [bt] (5) 5   libmxnet.so                         0x000000010e8823a2 _ZZN5mxnet4exec9InferAttrIN4nnvm6TShapeENSt3__18functionIFbRKNS2_9NodeAttrsEPNS4_6vectorIS3_NS4_9allocatorIS3_EEEESD_EEEZNS0_10InferShapeEONS2_5GraphEOSC_RKNS4_12basic_stringIcNS4_11char_traitsIcEENSA_IcEEEEE3$_0DnEESG_SH_T_PKcST_ST_ST_ST_T1_T2_bST_NS_12DispatchModeEENKUljbE_clEjb + 2770
    [bt] (6) 6   libmxnet.so                         0x000000010e879a9e _ZN5mxnet4exec10InferShapeEON4nnvm5GraphEONSt3__16vectorINS1_6TShapeENS4_9allocatorIS6_EEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS7_IcEEEE + 4798
    [bt] (7) 7   libmxnet.so                         0x000000010e88ecc4 _ZN5mxnet10imperative18CheckAndInferShapeEPN4nnvm5GraphEONSt3__16vectorINS1_6TShapeENS4_9allocatorIS6_EEEEbNS4_4pairIjjEESC_ + 1796
    [bt] (8) 8   libmxnet.so                         0x000000010e88d945 _ZN5mxnet10Imperative8CachedOp15GetForwardGraphEbRKNSt3__16vectorIPNS_7NDArrayENS2_9allocatorIS5_EEEE + 1157
    [bt] (9) 9   libmxnet.so                         0x000000010e8937c2 _ZN5mxnet10Imperative8CachedOp7ForwardERKNSt3__16vectorIPNS_7NDArrayENS2_9allocatorIS5_EEEESA_ + 98


    In [23]: prelu = PReLU()

    In [24]: prelu.initialize()

    In [25]: out = prelu(test)

**Comment by joeddav** [comment]
`alpha` just needs to be broadcasted to multiply with `self.act(F.negative(x))`, so just use `broadcast_mul` instead of `*`. So modifying @piiswrong's code we have:

```
class PReLU(gluon.HybridBlock):
    def __init__(self, *args):
        super(PReLU, self).__init__(*args)
        with self.name_scope():
            self.alpha = self.params.get('alpha', shape=(1,), init=mx.init.Zero())
            self.act = gluon.nn.Activation(activation='relu')

    def hybrid_forward(self, F, x, alpha):
        pos = self.act(x)
        neg = F.broadcast_mul(F.negative(alpha), self.act(F.negative(x)))
        return pos + neg
```

**Comment by mbaijal** [comment]
@KayneWest Has this issue been fixed for you?

**Comment by mbaijal** [comment]
Please add the labels "Gluon" and "Question"

**Comment by KayneWest** [comment]
@mbaijal, It’s been fixed.

**Comment by mbaijal** [comment]
Thanks
