### ISSUE TITLE
A todo list for usability improvement for sparse tensor

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#8902]
## throw exception on storage fallback
Currently when storage fallback happens, the log message is printed in the console, but it's very hard for the user to figure out when the fallback happens in the code even if they use NaiveEngine for debugging. We should throw an exception when storage fallback happens to help the user debug it. 
https://github.com/apache/incubator-mxnet/blob/master/src/operator/operator_common.h#L526

## missing storage fallback message/exception during ndarray copy
cast_storage may happen when the source and destination ndarray are of different storage types. Currently it's converted in silence and the user is not aware. 

## sparse vector with shape=(10)
https://github.com/apache/incubator-mxnet/issues/8817 
Still under discussion. We should either fix it or at least not let VM crash. 

## distributed training tutorial for sparse
Maybe do this after kvstore=device is done. 

## Testing
https://github.com/apache/incubator-mxnet/issues/8709
https://github.com/apache/incubator-mxnet/issues/8542 
#8980

**Comment by ZiyueHuang** [comment]
+1 for distributed training tutorial. I can take this task after https://github.com/apache/incubator-mxnet/pull/8732 is done.
