### ISSUE TITLE
MXNet 1.0.0 Release Feedback: Source Headers and License Files

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#8913]
## Description
This issue is to track the comments from the MXNet 1.0.0 vote thread. Refer to [link 1](https://mail-archives.apache.org/mod_mbox/incubator-general/201712.mbox/%3C7D5FA7AB-8172-4927-B34C-16281F62CAC2%40classsoftware.com%3E) and [link 2](https://mail-archives.apache.org/mod_mbox/incubator-general/201712.mbox/%3CCAK1xzDeBiNqcK_nZ4wSYehrLRtxESWRpPoZm8dg6UYDt6rNevA%40mail.gmail.com%3E) for details.

The comments mentioned are as follows - 

- **Issue 1:** LICENSE has a number of minor issues (LICENSE must be reviewed in addition to issues below)

- **Issue 2:** this file has an ASF header looks to be BSD licensed. [1] Other files that are licensed in similar confusing ways include [2][3][4][14]

- **Issue 3:** same with with MIT licensed files. [9][18][19]

- **Issue 4:** this file is BSD licensed [5] so would need to be added to LICENSE. As are a dozen files here [6] and this file [13, and this one [14] and 6 files here [15] and this one [16] and also this one [23]

- **Issue 5:** some file are still missing headers. For instance [7] and probable more.

- **Issue 6:** This file is listed at Apache 2.0 licensed  in the LICNSE but is actually MIT licensed. [8] As I think is this [10] and these [17][20] (or it should be mentioned in license)

- **Issue 7:** This file has two apache headers [22]

- **Issue 8:** Also there one outstanding question from the last release how is this file licensed? (if you follow the URL mentioned in the file it is unclear). [24] but it unclear of the code come form that site or was written for the project by the author of that site.

- **Issue 9:** Deal with the Copyright statements in perl-package (copyright holder has
approved doing this)

- **Issue 10:** Lots of whitespace on end of NOTICE

- **Issue 11:** Comment added to CODEOWNERS to explain the file so we don't cause
community problems

- **Issue 12:** There was a suggestion to simplify the LICENSE to not explicitly list which packages are under each license. Something to consider.
Note: This is something that was requested in a previous release vote, so may need some discussion.

### **How to Fix**
1. Run Apache RAT and fix all issues that come up
2. Fix other issues mentioned above
3. Must be reviewed by Mentors 
4. Must be fixed before the next release 

### **MXNet commit hash**
25720d0e3c29232a37e2650f3ba3a2454f9367bb

### Index of files mentioned above  
1. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/prepare_mkl.sh
2. apache-mxnet-src-1.0.0.rc1-incubating/src/operator/nn/im2col.h / im2col.c
3. apache-mxnet-src-1.0.0.rc1-incubating/src/operator/contrib/nn/deformable_im2col.h / deformable_im2col.c
4. apache-mxnet-src-1.0.0.rc1-incubating/src/operator/contrib/ctc_include/contrib/moderngpu/include/mgpuenums.h
5. apache-mxnet-src-1.0.0.rc1-incubating/src/operator/contrib/ctc_include/contrib/moderngpu/include/mgpudevice.cuh
6. apache-mxnet-src-1.0.0.rc1-incubating/src/operator/contrib/ctc_include/contrib/moderngpu/include/device/
7. apache-mxnet-src-1.0.0.rc1-incubating/perl-package/AI-NNVMCAPI/Makefile.PL
8. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/nnvm/tvm/HalideIR/LICENSE
9. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/setup.py
10. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/gpu_nms.pyx
11. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/cpu_nms.pyx
12. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/bbox.pyx
13. apache-mxnet-src-1.0.0.rc1-incubating/nnvm/tvm/dmlc-core/cmake/Modules/FindCrypto.cmake
14. apache-mxnet-src-1.0.0.rc1-incubating/example/ssd/dataset/pycocotools/coco.py
15. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/pycocotools
16. apache-mxnet-src-1.0.0.rc1-incubating/dmlc-core/cmake/Modules/FindCrypto.cmake
17. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/gpu_nms.pyx
18. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/nms_kernel.cu
19. apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/setup.py
20. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/cpu_nms.pyx
21.  apache-mxnet-src-1.0.0.rc1-incubating/example/rcnn/rcnn/cython/bbox.pyx
22. apache-mxnet-src-1.0.0.rc1-incubating/tools/license_header.py
23. apache-mxnet-src-1.0.0.rc1-incubating.tar/apache-mxnet-src-1.0.0.rc1-incubating/cub/experimental/spmv_compare.cu
24. ./apache-mxnet-src-1.0.0.rc1-incubating/example/image-classification/predict-cpp/image-classification-predict.cc

**Comment by lupesko** [comment]
@mbaijal are you or anyone else following up on this? 1.1.0 is going out soon...

**Comment by mbaijal** [comment]
@lupesko yes, I am tracking these and other issues in [this wiki](https://cwiki.apache.org/confluence/display/MXNET/MXNet+Source+Licenses).

I will update/close this and some other related issues once the 1.1.0 release passes the voting process.

**Comment by mbaijal** [comment]
All Issues here have been fixed, discussed or tracked in the wiki linked above. I will create new github issues to track any action items post mxnet 1.1.0 release. 
Resolving this issue.

**Comment by mbaijal** [comment]
Can you please add the label "Completed" to this issue. 
Also can a new label called "Licenses" or something similar be created to track such issues.
