### ISSUE TITLE
Build using android.arm64 android.armv7 dockers fails, while arm64 and arm7 dockers work

### ISSUE THREAD

**Issue by OferRosenberg** [apache/incubator-mxnet#8917]
I'm trying to build MxNet using the multiarch dockers. 
While the arm64 and armv7 dockers end succesfully, the Android arm64 and Armv7 docker fails due to compilation errors related to shm_open and shm_unlock - see snapshot below

In file included from src/storage/storage.cc:30:
src/storage/./cpu_shared_storage_manager.h:124:13: error: use of undeclared identifier 'shm_open'
      fid = shm_open(filename.c_str(), O_EXCL|O_CREAT|O_RDWR, 0666);
            ^
src/storage/./cpu_shared_storage_manager.h:129:11: error: use of undeclared identifier 'shm_open'
    fid = shm_open(filename.c_str(), O_RDWR, 0666);
          ^
src/storage/./cpu_shared_storage_manager.h:164:14: error: use of undeclared identifier 'shm_unlink'
    CHECK_EQ(shm_unlink(filename.c_str()), 0)
             ^
3 errors generated.
make: *** [build/src/storage/storage.o] Error 1

Is there some configuration I need to do in order to make the android dockers to work ?

Thanks,
Ofer.

**Comment by edmBernard** [comment]
https://github.com/apache/incubator-mxnet/issues/8707
It's a bug introduce by a recent commit that add cpu_shared_storage_manager
If you go back to this version https://github.com/apache/incubator-mxnet/commit/c8f7dce0eb49ab1a62ddc2c7e37b93e9b92c2ae4 you will be able to compile android version.
@piiswrong

**Comment by OferRosenberg** [comment]
Thanks. So right now, building for Android is jammed, either if trying to build the full MxNet or the Amalgamation build... OK. I'll go back to Nov 16 version for now.

**Comment by lebeg** [comment]
The build should be stable now.

**Comment by OferRosenberg** [comment]
Thanks ! checked it out and it works perfectly.
