### ISSUE TITLE
MXNet 1.0.0 & 1.1.0 Release Feedback: Move the submodules to a separate directory

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#8920]
## Description
This issue is to track the comments from the MXNet 1.0.0 vote thread as follows - 

Move the various git submodules into third-party/ or similar so it's simpler to see what is Apache original source when we review a release.

**Comment by cjolivier01** [comment]
I think all of this requires a separate discussion on dev@
There are several possible solutions which have been discussed.

**Comment by mbaijal** [comment]
This was requested again in the 1.1.0 Release since the 3000 unlicensed files are mostly from submodules. 
Link to email thread:
http://mail-archives.apache.org/mod_mbox/incubator-general/201802.mbox/%3C64F689C1-F847-469A-89FE-6F2746859E8F%40classsoftware.com%3E

**Comment by mbaijal** [comment]
Can you please add the labels "Roadmap", "Module" to this issue

**Comment by eric-haibin-lin** [comment]
done in 1.2
