### ISSUE TITLE
mxnet 0.12.1 prebuilt in windows doesn't include cudnn

### ISSUE THREAD

**Issue by traveller59** [apache/incubator-mxnet#8924]
## Description
I use following command to install mxnet 0.12.1:
```bash
pip install mxnet-cu90
```
When I want to use cudnn(FusedRNN for example), I got an error:
```
RuntimeError: simple_bind error. Arguments:
data: (64, 150)
softmax_label: (64,)
[20:42:18] D:/Program Files (x86)/Jenkins/workspace/mxnet/mxnet/src/operator/rnn.cu:43: RNN is only available for cuDNN at the moment.
```
And cnn will be very slow(without cudnn)
But when I install mxnet-cu80==0.12.0, everything is ok.
## Environment info (Required)
* Windows 10
* Anaconda
* Python 3.6.3
* mxnet 0.12.1 prebuilt
* CUDA 8.0+9.0
* cudnn 6+7

**Comment by szha** [comment]
@yajiedesign

**Comment by yajiedesign** [comment]
i will check it.

**Comment by yajiedesign** [comment]
ok please wait tomorrow.

**Comment by traveller59** [comment]
Thanks, now mxnet-cu80 has no problem.
