### ISSUE TITLE
Is nadam optimizer correctly implemented?

### ISSUE THREAD

**Issue by eldercrow** [apache/incubator-mxnet#8925]
Correct me if I am wrong. 
In python/mxnet/optimizer.py, line 1103:
``` python
        # preprocess grad
        # shouldn't it be grad = grad * self.rescale_grad + wd * weight?
        grad *= self.rescale_grad + wd * weight 
        if self.clip_gradient is not None:
            grad = clip(grad, -self.clip_gradient, self.clip_gradient)
```
I reckon the commented line in the above code is how all the other optimizers are implemented with. Does nadam have a special update rule I could not understand or is this a bug?

**Comment by piiswrong** [comment]
@szha

**Comment by szha** [comment]
Thanks for reporting, @eldercrow . This is indeed a bug. The linked pull request should fix this issue.

**Comment by eldercrow** [comment]
Thanks! I will close the issue.
