### ISSUE TITLE
mxnet r package installation failed

### ISSUE THREAD

**Issue by franciszmy** [apache/incubator-mxnet#8926]
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'

How can I solve this problem?

**Comment by zepen** [comment]
i have same problem, what' s wrong?

**Comment by thirdwing** [comment]
We don't provide the `tar.gz` package for mxnet.

If you are using Linux, please compile mxnet from source.

If you are using OSX, please try

`install.packages("mxnet", type = "mac.binary.mavericks")` or `install.packages("mxnet", type = "mac.binary")`
