### ISSUE TITLE
Windows, R, GPU build is only 0.10.1, which is too far behind github 0.12.1 and soon 1.0

### ISSUE THREAD

**Issue by whatever1983** [apache/incubator-mxnet#8927]
According to the installation document:
https://mxnet.incubator.apache.org/get_started/install.html

cran <- getOption("repos")
cran["dmlc"] <- "https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/GPU"
options(repos = cran)
install.packages("mxnet")

trying URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/GPU/bin/windows/contrib/3.4/mxnet_0.10.1.zip'
Content type 'application/zip' length 220445992 bytes (210.2 MB)
downloaded 210.2 MB

Sadly, it is only 0.10.1 version,  hopefully the mxnet team treats the native R environment and GPU builds more seriously, and release the latest 0.12.1(CUDA9/CuDNN7) and soon 1.0 with ONNX inferencing.  

BTW, are you guys hitting the same NVCC bug that is stopping Tensorflow 1.4 CUDA9 win10 builds?

**Comment by whatever1983** [comment]
Just checked the MXNET 1.0 R installation document, installation commands have changed to:

install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

Kudos to the RStudio team for hosting it.  But it still doesn't install it, :(

Warning in install.packages :
  package ‘mxnet’ is not available (for R version 3.4.2)

Using RStudio 1.1.383 and Microsoft Open R 3.4.2 inside RStudio.

**Comment by ankkhedia** [comment]
Hi @whatever1983 
The latest prebuilt mxnet-cu90, cu80, cu91 and cu91 binary for win10 haas been updated. You can take a look at install instructions. Also the instructions for building it from source has been updates. Feel free to try it out and let me know if you face any issue

@sandeep-krishnamurthy Could you please close this issue as it has been resolved.

@whatever1983 
 Please feel free to reopen if closed in error.
