### ISSUE TITLE
Flaky Perl-test test_gluon_rnn.t causing seg fault (non-zero wait status 139)

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#8928]
It seems like we're having a seg fault, indicated in Perl through wait status 139. I can't reproduce this but I encountered it once (see attached [log](https://github.com/apache/incubator-mxnet/files/1525285/t_test_gluon_rnn_seg_fault_139.txt)).
Commit hash: d7da05b61adc9e4aba3e9995809b0d06965ae3bb
Command: ``tests/ci_build/ci_build.sh cpu ./perl-package/test.sh``

```
Test Summary Report
-------------------
t/test_gluon_rnn.t        (Wstat: 139 Tests: 77 Failed: 0)
  Non-zero wait status: 139
Files=27, Tests=6721, 2018 wallclock secs ( 0.45 usr  0.35 sys + 35169.82 cusr 234.15 csys = 35404.77 CPU)
Result: FAIL
Failed 1/27 test programs. 0/6721 subtests failed.
Makefile:1162: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
script returned exit code 255
```

**Comment by sergeykolychev** [comment]
@szha I am looking into this and as well into another flaky test t/test_loss.t

**Comment by szha** [comment]
Thanks for the effort. Closing now. One rare segfault case is tracked in #9415
