### ISSUE TITLE
Spelling issue to be addressed

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#8930]
Spelling issues made in this PR should be fixed on the source markdown files - https://github.com/apache/incubator-mxnet-site/pull/36

These issue has occurred multiple times, probably good time to have spell checks in the nightly nightly broken link check CI test. Doing across all pages will have too many false positive to handle like mx, sym etc.. We should at-least get started with index pages for home page and each sections.

@thinksanky @mbaijal - Thoughts?

**Comment by sad-** [comment]
@sandeep-krishnamurthy could you close this issue if it's been addressed? thanks
