### ISSUE TITLE
mobileNet pretrained model official version from MXNET

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#8932]
Is there is any official version of mobilenet pretrained model in mxnet?
Other releases were found but not effective.
Hence i would like to know official version of mobilenet pretrained model in mxnet.

**Comment by edmBernard** [comment]
https://github.com/apache/incubator-mxnet/issues/8859
KeyKy version work fine for me.

**Comment by chowkamlee81** [comment]
Yeah it is 2.5 times slower in GPU and CPU wrt original models. Is there is any official version from MXNET?
