### ISSUE TITLE
MXNET backend in Keras 2

### ISSUE THREAD

**Issue by MohammadSamragh** [apache/incubator-mxnet#8941]
Hi,

I have used Keras 1.2.2 with the MXNET backend. In my experience, it is really useful for training multi-gpu models and it outperforms Tensorflow. Are there any plans to develop a backend for Keras 2 as well? I have already opened an issue on Keras github [here](https://github.com/fchollet/keras/issues/8688).

Many thanks!

**Comment by edmBernard** [comment]
I don't see news since this issue:
@sandeep-krishnamurthy  https://github.com/gluon-api/gluon-api/issues/5

**Comment by eric-haibin-lin** [comment]
Yes! it's on our roadmap and under development.
@jiajiechen  is there a target date that we're shooting?

**Comment by sandeep-krishnamurthy** [comment]
Here is the repo we are working on - https://github.com/deep-learning-tools/keras/tree/keras2_mxnet_backend

We are looking at creating PR with Keras for MLP, CNN - CPU, GPU, multi-GPU support with MXNet backend by end of Jan, 2018.

**Comment by sandeep-krishnamurthy** [comment]
Current state of the project:
1. Supports sequential dense models.
2. Able to train CNN model (Tested Resnet architecture)

Here is a guide to install and try it out - https://github.com/deep-learning-tools/keras/wiki/Installation-Guide---Keras-with-MXNet-backend

**Comment by sandeep-krishnamurthy** [comment]
Created first PR - https://github.com/keras-team/keras/pull/9291
Resolving this issue. Please track the progress at https://github.com/deep-learning-tools/keras/tree/keras2_mxnet_backend
