### ISSUE TITLE
Not all latest version has prebuild binary for Windows on PyPI

### ISSUE THREAD

**Issue by cloudhan** [apache/incubator-mxnet#8951]
PyPI has being hosting pre-build binary since 0.11.0, but not all version has its corresponding binary.
Please make it consistent across all platform

Only the following version and run-time environment have binary on PyPI:
[0.11.0 with CUDA8.0](https://pypi.python.org/pypi/mxnet-cu80/0.11.0)
[0.12.0 with CUDA8.0](https://pypi.python.org/pypi/mxnet-cu80/0.12.0)

But the newer version 0.12.1 and 1.0.0 doesn't have it.

macOS seems also suffering from this problem.
Please make this infrastructure available for all platform and all run-time environment.

**Comment by zhreshold** [comment]
same in #8962 , cc @yajiedesign 
We are still using manual script to build the coda versions on windows, so please be patient with the release. Hopefully we will solve it in a near future.

**Comment by yajiedesign** [comment]
automatic release build is work in progress.It might take a few more days..

**Comment by whatever1983** [comment]
@yajiedesign nice work.  Make sure win10 R build is of the same priority as the python pip packages, especially the GPU version with CUDA 9 (which is the hardest to build against).

**Comment by cloudhan** [comment]
@whatever1983 CUDA 9.1 have released, so you should expect more ;)

**Comment by leleamol** [comment]
Proposed Labels: "Windows","Build","Feature Request"

**Comment by yajiedesign** [comment]
I'm now bothering the size of a huge file. The file is too large to can not be uploaded to pypi.

**Comment by szha** [comment]
This should have been fixed already. Ping me if the problem persists.
