### ISSUE TITLE
when convert predict's output to numpy, too slow at asnumpy() @cpu docker 

### ISSUE THREAD

**Issue by mangojiez** [apache/incubator-mxnet#8952]
Problem:
when convert predict's output to numpy, too slow at asnumpy(),it cost 40s 
code:
self.executor.forward()
output = self.executor.outputs
prob = output[0].asnumpy()

debug:
mxnet/ndarray.py, line 911, in asnumpy (self=<NDArray at remote 0x7fad1a284f90>, data=<numpy.ndarray at remote 0x7facfc6e97b0>)
/mxnet/ndarray.py, line 150, in __repr__ (self=<NDArray at remote 0x7fad1a284f90>, x=5911L, shape_info='1500x5911')

env:
1：CPU Docker
2：Centos
3：output[0] size is 1500*5911
4：run in tornado httpserver instance

**Comment by zhreshold** [comment]
explanation here: https://github.com/apache/incubator-mxnet/issues/8309

**Comment by leleamol** [comment]
Proposed Labels:"Performance", "Pending Requester Info",

**Comment by piyushghai** [comment]
@mangojiez Did the explanation in #8309 help you out ? 

Thanks!

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.

**Comment by phongnguyenai** [comment]
Sorry but I got the same problem, anyone solved it?
