### ISSUE TITLE
Run 'fine-tuning' example found【Wrong number of inputs】on "python3.5 mxnet 0.11.0 centos7 "

### ISSUE THREAD

**Issue by bigdata-eqxiu** [apache/incubator-mxnet#8953]
我在Centos7上安装了mxnet 0.11.0 运行李沐老师的 fine-tuning图片二分类（https://zh.gluon.ai/chapter_computer-vision/fine-tuning.html）报如下错误 请问怎么解决 谢谢！！

Start training on  cpu(1)
Traceback (most recent call last):
File “statesman_train.py”, line 66, in 
train(finetune_net, ctx)
File “statesman_train.py”, line 59, in train
utils.train(train_data, test_data, net, loss, trainer, ctx, epochs)
File “…/utils.py”, line 129, in train
outputs = [net(X) for X in data]
File “…/utils.py”, line 129, in 
outputs = [net(X) for X in data]
File “/root/anaconda3/lib/python3.5/site-packages/mxnet/gluon/block.py”, line 268, in call
return self.forward(*args)
File “/root/anaconda3/lib/python3.5/site-packages/mxnet/gluon/block.py”, line 402, in forward
return self._call_cached_op(x, *args)
File “/root/anaconda3/lib/python3.5/site-packages/mxnet/gluon/block.py”, line 376, in _call_cached_op
self._build_cache(*args)
File “/root/anaconda3/lib/python3.5/site-packages/mxnet/gluon/block.py”, line 368, in _build_cache
"Wrong number of inputs."
AssertionError: Wrong number of inputs.

**Comment by leleamol** [comment]
Proposed Labels: "Bug", "Example", "Need Triage"

**Comment by gautamkmr** [comment]
Proposed label: bug, example
Please remove the label: Need Triage

**Comment by szha** [comment]
@leleamol @sandeep-krishnamurthy please refrain from manually adding "Need Triage" label while triaging. Thanks.

**Comment by vandanavk** [comment]
Issue not reproducible with the code in https://zh.gluon.ai/chapter_computer-vision/fine-tuning.html.
(MXNET 1.3.1 Python 3.6.5 MacOS).

@sandeep-krishnamurthy  Please close this issue.
@bigdata-eqxiu Please feel free to reopen if this issue appears again.
