### ISSUE TITLE
Please add windows python package for 1.0.0 and 0.12.1 on PyPI

### ISSUE THREAD

**Issue by PaulaQin** [apache/incubator-mxnet#8962]
Hi, 
I found that you have release mxnet 0.12.1 and 1.0.0 and put the python package to PyPI. But there is not package for windows. Could you build one and add to PyPI?

Thanks.

**Comment by szha** [comment]
@yajiedesign @zhreshold

**Comment by zhreshold** [comment]
cpu versions added.

**Comment by whatever1983** [comment]
Inside Anaconda 5.0.1, after conda update --all, do:
pip install mxnet-cu90 or pip install mxnet-cu80

installs 0.12.1 version with CUDA9 support.  not 1.0 though.  The pip package is roughly 2 weeks behind github release, so expect 1.0 to follow soon

Now the R installation commands still gives 0.10.1.......talking about release fragmentation.

**Comment by machuck** [comment]
find all versions by:
`pip search mxnet`
For cpu only version
`pip install keras-mxnet`

**Comment by gautamkmr** [comment]
Please add labels: "Windows", "pip"

**Comment by szha** [comment]
This should have been fixed already. Ping me if the problem persists.
