### ISSUE TITLE
GPU Memory Usage keep increase (Not in train or predict)

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#8965]
Hi:
   I extracted some features on a series of video frames. The final layer of my symbol would be something like`mx.sym.Group([x1,x2,x3,x4,x5,x6])`, then I use the `module.predict` to get the output, the output looks like `tmps = [[x1_output,x2_output,x3_output,x4_output,x5_output,x6_output],....]`, and `len(tmps)=305`, the I use the following code to get the feature:
```
for tmp in tmps:
     #select the feat layer
     if some_condition:
          feat = tmp[4].asnumy()[0]
      else:
          feat = tmp[5].asnumpy()[0]

```
but in this circulation, the GPU memory usage was keep increase, and finally raise an Error:`Out of memory`,which makes me very confuse. Any help will be appreciated.

**Comment by edmBernard** [comment]
Most of Mxnet computation are asynchronous. 
A simple loop like this will crash GPU:
```python
for image in dataset:
     tmps += module.predict(image)
```
Because it start new prediction without waiting the end of previous one.

To force mxnet to wait the end of previous prediction you can add `waitall`
```python
for image in dataset:
     tmps += module.predict(image)
     ndarray.waitall()
```

**Comment by lilhope** [comment]
@edmBernard  Thanks， I‘ll take a try.
