### ISSUE TITLE
v1.0 with NCCL

### ISSUE THREAD

**Issue by caiqi** [apache/incubator-mxnet#8977]
When using the package from pip with NCCL, it throws the error: 

mxnet.base.MXNetError: [12:55:01] src/kvstore/kvstore.cc:66: compile with USE_NCCL=1 to use nccl

Is there any prebuilt package with NCCL support? Thanks!

**Comment by rahul003** [comment]
Not currently. We might do this at a later date

**Comment by eric-haibin-lin** [comment]
It's on our roadmap. For now you can build it from source following the instructions here: https://github.com/apache/incubator-mxnet/pull/8957/files

**Comment by caiqi** [comment]
Thanks! By the way, is there any plan to support prebuilt package with more flags open, like USE_PROFILER ?

**Comment by szha** [comment]
pip version 1.0.0.post2 for cu80/cu80mkl/cu90/cu90mkl now supports nccl out of the box.

We will consider turning on USE_PROFILER once its performance impact is evaluated and considered tolerable.
