### ISSUE TITLE
Question about 2bit gradient compression  

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#8979]
Why pull doesn't use 2bit quantize before response in kvstore_dist_server?
Does it means push gradient with 2bit compression  and pull gradient with on compression  op?
@rahul003

**Comment by rahul003** [comment]
Yes currently pull doesn't compress gradients to avoid compression at two steps. I suspect this would lead to poorer convergence because we would be losing more information. We can do this if experiments show that accuracy isn't affected much.
