### ISSUE TITLE
CI System is warning of improper sparse tensor usage during tests.

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#8980]
## Description
Test runs in CI are frequently displaying the message:
```
The operator with default storage type will be dispatched for execution. You're seeing this warning message because the operator above is unable to process the given ndarrays with specified storage types and parameter. Temporary dense ndarrays are generated in order to execute the operator. You can set environment variable MXNET_STORAGE_FALLBACK_LOG_VERBOSE to 0 to suppress the warnings.
```
I believe this indicates we aren't compiling in a way that allows for sparse tensor support to be tested.  This is not ideal as it means that 1) we have a lack of coverage of sparse tensors and 2) we're logging much too often in tests runs making it difficult to interpret results.

This is a placeholder issue for the time being, I'll investigate further and see if we do need to modify or CI environment to support sparse tensors (for example enabling a flag for build), or whether this is a false warning.

**Comment by KellenSunderland** [comment]
@eric-haibin-lin Many of these warnings seem to be coming from the sparse tensors that are passed into operators.  I just want to double check that this is expected from your pov.  Would you be able to explain what's being described in this warning?  Are we really allocating a temporary dense ndarray when we call this operator?

```
Storage fallback detected:
operator = Cast
input storage types = [row_sparse, ]
output storage types = [row_sparse, ]
params = {"dtype" : float16, }
context.dev_mask = 1
The operator with default storage type will be dispatched for execution. You're seeing this warning message because the operator above is unable to process the given ndarrays with specified storage types and parameter. Temporary dense ndarrays are generated in order to execute the operator. You can set environment variable MXNET_STORAGE_FALLBACK_LOG_VERBOSE to 0 to suppress the warnings.
```

**Comment by eric-haibin-lin** [comment]
No special build config is required for the sparse feature. 

The verbose warning message is on my list of things to fix. Most of the messages are expected as the tests indeed converts sparse ndarrays into dense ones. I need to suppress the warnings. The log is also there before the migration.

With regard to the Cast operator, it indeed doesn't support sparse format because it's using the legacy operator interface instead of nnvm.

**Comment by KellenSunderland** [comment]
Ok sounds good @eric-haibin-lin.
