### ISSUE TITLE
Can't compile unit tests 

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#8992]
error: object of type 'mxnet::test::perf::TimingInstrument::Info' cannot be assigned because its copy assignment operator is implicitly deleted

  typedef std::unordered_map<int, TimingInstrument::Info> timing_map_t;

TimingInstrument::Info  has atomics that can't be copied! Because it has some atomics as members

```
mkdir -p build && cd build
cmake -DUSE_CUDA=OFF -DUSE_OPENCV=OFF -DUSE_OPENMP=OFF -DCMAKE_BUILD_TYPE=Debug -GNinja ..
ninja -v
```

**Comment by larroy** [comment]
It can be seen in this branch:

https://github.com/larroy/mxnet/tree/googletest

**Comment by larroy** [comment]
@cjolivier01

**Comment by cjolivier01** [comment]
what platform/compiler/version?

**Comment by cjolivier01** [comment]
Also, the full error log would be useful.

**Comment by cjolivier01** [comment]
operator __int_type() const noexcept 
should satisfy:
constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }

unless your version declares this constructor explicit, which it isn't for my version.

**Comment by cjolivier01** [comment]
In addition, Info has a copy constructor:
    inline Info(const Info& o)
      : name_(o.name_)
        , baseTime_(o.baseTime_.load())
        , nestingCount_(o.nestingCount_.load())
        , cycleCount_(o.cycleCount_.load())
        , duration_(o.duration_.load()) {
      CHECK_EQ(o.nestingCount_, 0U);
    }

**Comment by larroy** [comment]
[build.log](https://github.com/apache/incubator-mxnet/files/1541143/build.log)

**Comment by larroy** [comment]
pllarroy@acbc329d1fbd:0:~/devel/mxnet/mxnet$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by larroy** [comment]
MacOsX 10.11.6.


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:903:20: note: 'operator=' has been explicitly marked deleted here
    __atomic_base& operator=(const __atomic_base&) = delete;

It's in the C++ standard since C++11 that atomic integrall types have deleted copy ctor, asignment and trivial destructor.  

"Specializations and instantiations of the atomic template shall have a deleted copy constructor, a deleted copy assignment operator, and a constexpr value constructor"
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf

**Comment by larroy** [comment]
It might work on other platforms if the enclosing class is moved...  In Linux compilation doesn't fail.

**Comment by cjolivier01** [comment]
I am not challenging the atomic class.
This appears to be due to the hash table implementation you're using trying to execute an explicit assignment: "__cache->__value_ = *__first;" when inserting the item, where the gcc and msvc implementations uses a copy constructor, which is implemented.

try changing the line:

timing_[shapes][mode] = tm;

to:

timing_[shapes].insert(std::make_pair(mode, tm));

**Comment by cjolivier01** [comment]
I'll remove some of the std::move calls while I am here since clang doesn't seem to like them

**Comment by cjolivier01** [comment]
https://github.com/apache/incubator-mxnet/pull/8996
