### ISSUE TITLE
how to train data on hadoop ？

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#8999]

**Comment by janelu9** [comment]
how use the config "USE_HDFS=1" ,is there an example?

**Comment by janelu9** [comment]
I have a data of 81GB need to be trained

**Comment by gautamkmr** [comment]
Please add the Labels  "Exploration", "HowTo", "Feature Request"

**Comment by sandeep-krishnamurthy** [comment]
Can you please usage related query at - https://discuss.mxnet.io/ 
Please file a GitHub issue if you encounter any issue.
