### ISSUE TITLE
get_next_state parameter in FusedRNN constructor

### ISSUE THREAD

**Issue by ArmageddonKnight** [apache/incubator-mxnet#9010]
Sorry but I am confused about the `get_next_state` parameter in the https://github.com/apache/incubator-mxnet/blob/3ee1ca272964a8bfc1ca40a65c3341c58352f4a4/python/mxnet/rnn/rnn_cell.py#L536 It says:

    get_next_state : bool, default False
        Whether to return the states that can be used as starting states next time.

Could someone please explain under what circumstance would we set this parameter to `true`? Thank you.

**Comment by eric-haibin-lin** [comment]
If this is set to true, `unroll` will return a list of symbols, including the symbol of the final states after unrolling. If it's set to false, they will not be returned

**Comment by ArmageddonKnight** [comment]
Hi Haibin,

Thanks for your response. But what will be returned when `get_next_state = false`? I noticed that in the `charRNN` example located in the `cpp-package`:

https://github.com/apache/incubator-mxnet/blob/20666c3186b3d7166cae625b48c81713c6811d67/cpp-package/example/charRNN.cpp#L168 

We have the following code:

```c++
  auto rnn = RNN(embed, rnn_params, rnn_h_init, rnn_c_init, num_hidden, num_lstm_layer, 
RNNMode::kLstm, false, dropout, !isTrain);
```

It seems to me that the last parameter in the C++ API (i.e. `!isTrain`) corresponds to the `get_next_state` (because its documentation says `state_outputs Whether to have the states as symbol outputs`). But why should it be set to `true` while training and `false` while not training?
