### ISSUE TITLE
pooling of dcnn

### ISSUE THREAD

**Issue by yufengwhy** [apache/incubator-mxnet#9020]
https://github.com/apache/incubator-mxnet/blob/master/example/cnn_text_classification/text_cnn.py

In line 119, the pooling should be global pooling as the paper (https://arxiv.org/pdf/1408.5882.pdf)

**Comment by eric-haibin-lin** [comment]
Agreed that the original paper uses global pooling. Was it a bug in the example or it was by any chance "intentional simplification"?  @qcl6355

**Comment by yufengwhy** [comment]
Apologize for my thoughtlessness, line 119 is actually also global pooling, because the pooling size == the input size. But if (global_pool=True) is given, the code may be easier to follow. 
By the way, do mxnet has any implementation of 1d convolution as this paper (https://arxiv.org/abs/1404.2188)?

**Comment by yufengwhy** [comment]
1d convolution is row-wise convolution over 2d input (embedding_dimension x num_words), which is useful in NLP or recommender. There is actually a theano-implementation (https://github.com/hritik25/Dynamic-CNN-for-Modelling-Sentences), which is hard to add new things. So I implement a mxnet-implementation, which is much slower than my keras-implementation, may I get help from you mxnet-master ^_^~~
