### ISSUE TITLE
Multiple featureid in one field in wide&deep example

### ISSUE THREAD

**Issue by formath** [apache/incubator-mxnet#9023]
Hi @ZiyueHuang 
Now in the example `sparse/wide_deep`, it assumes one `featureid` in one `field`. How about multiple `featureid` in one `field`?

**Comment by ZiyueHuang** [comment]
I think it doesn't matter. Just make the data for wide part model as CSR format.

**Comment by formath** [comment]
Do you mean `libsvm` format like `field:featureid`? But `LibSVMIter` will parse all `featureid` into one `CSRNDArray`. However, users may want one `CSRNDArray` per `field`. And, all embedding of many `featureid` according to one field will be summed into one embedding like that of `embedding_lookup_sparse(..., combiner='sum')` in tensorflow. Can you give an example?

**Comment by formath** [comment]
I have known how to do it. thanks

**Comment by ZiyueHuang** [comment]
OK, feel free to reopen this issue if you have any further questions or request other examples. For now user should create a single `libsvm` format file as input. I think `concat(csr, csr)` is what you need as you said "users may want one CSRNDArray per field", but this is still under development.

**Comment by formath** [comment]
`libsvm` format like `fieldid:featureid` will generate `CSRNDArray` in which index are `fieldid` but we want to use `featureid` as index. In `wide&deep` example, it's dense format of `csv` so don't have this problem. But in `csv` format, it don't support multiple `featureid` in one column where each column is a field. Right?

**Comment by ZiyueHuang** [comment]
Yes. Is your use case like

user | item 
---- | --- 
1:1, 100:1 | 3:1, 300:1 

For now, user need create a single `libsvm` format file.

**Comment by formath** [comment]
I mean

|  label        | user history clicked items | item  |  user history click rate |
| ---------  | -------------                      |-------------|-----|
| 1                | 1:293 1:394  1:743            | 2:482 | 3:0.05 |
| 0               | 1:128 1:91                           | 2:232 | 3:0.14 |
