### ISSUE TITLE
issue with memory cost

### ISSUE THREAD

**Issue by my777777** [apache/incubator-mxnet#9024]
## Description
(Brief description of the problem in no more than 2 sentences.)
when training imagenet，the memory cost of resnet has been greatly increased.
batch size =32, use resnet-34 model, the memory displayed by nvidia-smi is greater than 6000MB，but at the 0.11.0 branch, its memory cost only 2190MB.
## Environment info (Required)
cuda7.5 + cudnn v5.1
GPU: K40m, total memory: 11519MB
Package used: Python

Compiler: gcc

MXNet commit hash:
0.11.0 branch: a5edbf94094581ee27157eae4f2113115a3994e7
newest(clone from git at 2017/12/11 21:00): 20666c3186b3d7166cae625b48c81713c6811d67

Build config:
USE_CUDA = 1
USE_CUDNN = 1

## Minimum reproducible example
use the example at: examples/image-classification/train_imagenet.py

## Steps to reproduce
just run example provided by mxnet

**Comment by eric-haibin-lin** [comment]
Taking a look

**Comment by eric-haibin-lin** [comment]
Hi what's the exact command you used? 
I used the following command:
```
python train_imagenet.py --network resnet --num-layers=34 --benchmark 1 --gpus=1 --batch-size=32
```
on 0.11.0 (a5edbf94094581ee27157eae4f2113115a3994e7) and 0.12.0 (4f2af2d2e5216ab3a1faadcc117709b6836029dc) and master (20666c3) 
The memory usage observed is around 2295MB for all three versions. 

I see more than 6000MB memory usage only when using a larger batch size like 128.

**Comment by my777777** [comment]
Oh!  you are right, thank you, I make a mistake on batch size..
