### ISSUE TITLE
Scala API doc doesn't show available operators

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9041]
As I browse the scala [API doc](https://mxnet.incubator.apache.org/api/scala/docs/index.html#ml.dmlc.mxnet.NDArray), I don't see any documentation regarding the available operators. This affects the usability of scala users.

**Comment by nswamy** [comment]
This will be available starting 1.3. https://cwiki.apache.org/confluence/display/MXNET/MXNet+Scala+API+Usability+Improvement
You can view the API documentation on the master branch already
https://mxnet.incubator.apache.org/api/scala/docs/index.html#org.apache.mxnet.NDArrayAPIBase
