### ISSUE TITLE
Avoiding weight sharing among certain layers in BucketingModule?

### ISSUE THREAD

**Issue by arshitgupta** [apache/incubator-mxnet#9042]
I am using BucketingModule for training multiple small models/bots together. Here, the bucket key is bot_id. However, each bot has separate set of target labels/classes (and hence, different size of softmax layer for each bot). 
Is there any way to train such a model in mxnet, where I want to share the weights for all the layers but one (softmax) among all the bots? 
How would I initialize such a model using sym_gen method?
 If in the sym_gen method, in the Softmax layer I specify the num_hidden=size_dict[bot] i.e., 
pred = mx.sym.FullyConnected(data=pred, num_hidden=len(size_dict[bot]), name='pred')
pred = mx.sym.SoftmaxOutput(data=pred, label=label, name='softmax')
I get the error:
"Inferred shape does not match shared_exec.arg_array's shape" which makes sense as each bot has different size.

**Comment by eric-haibin-lin** [comment]
You can make `sym_gen(default_bucket_key)` returns a "master network" that contains both these two FC layers of different shapes, and `sym_gen(other_keys)` returns a subset of the master network

**Comment by arshitgupta** [comment]
This works. However, there is a small caveat (as mentioned by eric@ in offline discussion) - when you create multiple softmax layers, the 'states' dictionary keys are essentially the indices (instead of name strings), essentially creating a conflict when we have multiple softmax layers with same index. The work around for this issue is to use kvstore value of 'devices' instead of 'local' (default)!
