### ISSUE TITLE
pip package relies on outdated libgfortran.so version

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#9048]
Since at least gcc 7.2 released [2017-08-14] libgfortran.so in version 4 (i.e. libgfortran.so.4) is provided. The mxnet pip package however links against libgfortran.so.3 meaning that it cannot be used on systems with recent versions of gcc.

To resolve this issue the pip package needs to either link against libgfortran.so.4, link against both (is that possible?) or should provide a static version of the respective libgfortran library (issue #8903).

**Comment by piiswrong** [comment]
@szha Can we do a conda build?

**Comment by szha** [comment]
I'm evaluating ways to allow pip users to benefit from the change as well without static-linking.

**Comment by KellenSunderland** [comment]
@leezu Just to clarify, you're attempting to pip install and then run mxnet right?  You're not compiling or linking against the package?  

Would you be able to let us know what distribution you're using?  You can install the required package on ubuntu with 'sudo apt-get install libgfortran3'.

**Comment by leezu** [comment]
@KellenSunderland Yes, I'm referring to the case where a user on a distribution with gcc version >= 7.2 installs mxnet from pip. Self-compiling is no problem in that case, as mxnet will be linked against the "correct" libgfortran.so.4.

I'm running Gentoo, but Fedora 27 should be affected by this as well.

**Comment by KellenSunderland** [comment]
@leezu Ok great, thanks for the info, I see what you mean.  I've seen libgfortran.so.3 offered as a compat package on some distribution (iirc Amazon Linux) and I was hoping I could suggest that as a fix.  However the only compat version on Fedora 27 seems to be compat-libgfortran-41 which gets you libgfortran.so.1 and libgfortran.so.4 (neither of which work for mxnet).  Looks like the ABI changed, so I can't think of any way to link to both in the same package off the top of my head.

**Comment by szha** [comment]
The problem should have been resolved in mxnet==1.0.0.post2. @leezu could you check and see if the post2 version fixes the problem for you?

**Comment by leezu** [comment]
libmxnet is now linked against libgfortran.so.3 which is included in the pip package. So the problem is solved. Thanks @szha
