### ISSUE TITLE
[Android,v0.11.0] The result of mxnet_predict is wrong! AND how to compile the amalgamation in Android Studio?

### ISSUE THREAD

**Issue by nihilityworld** [apache/incubator-mxnet#9051]
@piiswrong I have compile the amalgamation in IOS and ANDROID. The params and the json file is same. The result in IOS is right, while it in ANDROID is wrong. I got the same result array with different image. Why I got this fault?

I tried to compile mxnet_predict-all.cc in Android Studio which can debug the code, but I failed.
Can anyone give a tutorial of compiling the amalgamation in Android Studio with cmake or tell me how to debug it?

**Comment by sad-** [comment]
compiling amalgamation to work in android studio is addressed here: https://github.com/apache/incubator-mxnet/issues/2133 @nswamy can we close out this issue?
