### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by lhb8125** [apache/incubator-mxnet#9052]
I downloaded the source package mxnet-0.12.0, but I got a warning that the variable "i" was defined at line 218 and line 226 in file kvstore_local.h.
I think you should better fix it.

**Comment by marcoabreu** [comment]
Hello @lhb8125, could you please tell us the exact steps you took in order to come to this error?

**Comment by lhb8125** [comment]
I followed the install instruction in mxnet website, and I add #include "kvstore/kvstore_local.h" in file batch_norm_v1-inl.h. After that, I compiled the makefile using "make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1", then I got the warning.

**Comment by vandanavk** [comment]
Issue not reproducible with

Python 3.6.4
MXNet 1.3.0
Platform     : Linux-4.4.0-1065-aws-x86_64-with-debian-stretch-sid
machine      : x86_64
processor    : x86_64

@lhb8125 Can this issue be closed?
