### ISSUE TITLE
sample_multinomial crashes on vector input

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9062]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
`sample_multinomial` / `random.multinomial` crashes when input probability is a vector.  @piiswrong 

## Environment info (Required)
Deep Learning AMI Ubunut 

Package used (Python/R/Scala/Julia): python
(I'm using ...) 

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash: 41394a448a92efbe7704fe21c48a8504fd8d3edc
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)
```
cp make/config.mk .
echo "USE_BLAS=openblas" >>config.mk
echo "ADD_CFLAGS += -I/usr/include/openblas" >>config.mk
echo "USE_CUDA=1" >>config.mk
echo "USE_CUDA_PATH=/usr/local/cuda" >>config.mk
echo "USE_CUDNN=1" >>config.mk
```

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)
```
>>> import mxnet as mx
>>> prob = mx.nd.ones((3,)) / 3
>>> prob

[ 0.33333334  0.33333334  0.33333334]
<NDArray 3 @cpu(0)>
>>> mx.nd.sample_multinomial(prob, shape=(25), get_prob=True)
[
[1 1 2 2 1 2 1 2 1 1 1 1 1 0 2 0 2 0 1 1 2 2 1 1 1]
<NDArray 25 @cpu(0)>,
-1.0986123085
<NDArray  @cpu(0)>]
>>> mx.nd.sample_multinomial(prob, shape=(25), get_prob=True)
*** Error in `python': free(): invalid next size (fast): 0x00007f8700004db0 ***
Bus error (core dumped)

```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by piiswrong** [comment]
These are deprecated. use mx.nd.random.multinomial now.
We should fix the document

**Comment by eric-haibin-lin** [comment]
Also core dump if `mx.nd.random.multinomial` is used
