### ISSUE TITLE
pip install mxnet dont have warpctc

### ISSUE THREAD

**Issue by hsddlz** [apache/incubator-mxnet#9078]
I used pip install mxnet ,but when I run mx.sym.WarpCTC .'module' object has no attribute 'WarpCTC'
then I try mx.sym.contrib.CTCLoss.'module' object has no attribute 'contrib'

my mxnet version is 0.11.0
what' could I do......
thx!!!

**Comment by eric-haibin-lin** [comment]
I think WarpCTC is a separate plugin that doesn't come with pip. You need to install it manually https://github.com/apache/incubator-mxnet/tree/master/example/warpctc#baidu-warp-ctc-with-mxnet 

For `mx.sym.contrib.CTCLoss `, please try to upgrade your mxnet version

**Comment by jesterhazy** [comment]
You can build mxnet from source with the warpctc plugin by following the instructions here: https://github.com/apache/incubator-mxnet/tree/master/example/ctc#building-mxnet-from-source-with-warp-ctc-integration.

**Comment by sandeep-krishnamurthy** [comment]
@hsddlz - please feel free to reopen if you still need support.
