### ISSUE TITLE
What is the difference between nd.concatenate and nd.concat?

### ISSUE THREAD

**Issue by DabiaoMa** [apache/incubator-mxnet#9084]
I am using Python mxnet 0.12 version

I built a model and used the nd.concatenat when training

The following error appears:
mxnet.base.MXNetError: [12:09:34] src/imperative/imperative.cc:249: Check failed: AGInfo::IsNone(*(outputs[i])) Inplace operations (+=, -=, x[:]=, etc) are not supported when recording with autograd.

Then I changed nd.concatenate to nd.concat, and the error does not appear.

So what is the difference between the two functions? Thanks

**Comment by eric-haibin-lin** [comment]
As the API doc suggests, `nd.concatenate` is deprecated https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.concatenate. 
Please use `nd.concat`.

**Comment by DabiaoMa** [comment]
@eric-haibin-lin Thanks.

**Comment by johnsonkee** [comment]
@eric-haibin-lin 
可以的，谢谢。
