### ISSUE TITLE
float division by zero error for small network

### ISSUE THREAD

**Issue by caiqi** [apache/incubator-mxnet#9113]
https://github.com/apache/incubator-mxnet/blob/251ae71a20d8318ab20f4c19520f74b881fdf3ff/python/mxnet/callback.py#L159 For some very small network, (time.time() - self.tic) may be zero and throws division by zero error.

**Comment by dongzhuoyao** [comment]
hah, interesting

**Comment by zchrissirhcz** [comment]
Is this because our GPU based machine runs too fast?

I also encounter this problem when playing the linear regression toy  network in https://mxnet.incubator.apache.org/tutorials/python/linear-regression.html.

**Comment by ibraheemalkilanny** [comment]
I think it is because the console, too much lines are being printed. Check out my stackoverflow question for details

**Comment by sandeep-krishnamurthy** [comment]
Resolving. Please reopen if issue still persists.
