### ISSUE TITLE
Feature request for In-Place Activated BatchNorm

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#9115]
In-Place Activated BatchNorm (InPlace-ABN) is a novel approach to reduce the memory required for training deep networks. It allows for up to 50% memory savings in modern architectures such as ResNet, ResNeXt and Wider ResNet by redefining BN + non linear activation as a single in-place operation, while smartly dropping or recomputing intermediate buffers as needed.

https://github.com/mapillary/inplace_abn
https://arxiv.org/pdf/1712.02616.pdf

**Comment by dongzhuoyao** [comment]
will you implement it recently? @chinakook

**Comment by chinakook** [comment]
@dongzhuoyao I've not sure about that whether the ABN is covered by the mirror feature of mxnet or [mxnet-memonger](https://github.com/dmlc/mxnet-memonger) machanism. So I will compare them at first.

**Comment by cjolivier01** [comment]
Seems a reasonable request since activation almost always occurs after BN

**Comment by cjolivier01** [comment]
Added JIRA: https://issues.apache.org/jira/browse/MXNET-113

**Comment by cjolivier01** [comment]
CLosing as it's now tracked by a JIRA
