### ISSUE TITLE
Are there any params replications on Parameter Servers?

### ISSUE THREAD

**Issue by huyangc** [apache/incubator-mxnet#9120]
I am very interested on the distributed training of mxnet. And I read [Scaling Distributed Machine Learning with the Parameter Server](https://www.cs.cmu.edu/~muli/file/parameter_server_osdi14.pdf). On that paper, Mu Li said that,
> Live replication of parameters between servers supports hot failover.

and used some structures like a key ring and params will replicated on different ps.

But I am reading the code of mxnet, including the ps-lite, kvstore. But I didn't find any operation of replications. I did see the key ring in ``src/kvstore/kvstore_dist.h EncodeDefaultKey``, which means that different ps holds different params.

So, I want to figure out whether I am wrong or the implementation of mxnet is a little different with the paper.

Hoping for an answer!

**Comment by eric-haibin-lin** [comment]
Hot failover is not supported in MXNet just yet.

**Comment by huyangc** [comment]
Thanks a lot!
