### ISSUE TITLE
random_uniform causes VM to crash

### ISSUE THREAD

**Issue by marfago** [apache/incubator-mxnet#9131]
The code ``` nd.random_uniform(3)``` crashes with 
```
[19:51:29] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [19:51:29] src/operator/random/./sample_op.h:294: Check failed: param.high >= param.low (1 vs. 3) low must be less or equal to high in uniform distribution
```

caused by

```
libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [19:51:29] src/engine/./threaded_engine.h:359: [19:51:29] src/operator/random/./sample_op.h:294: Check failed: param.high >= param.low (1 vs. 3) low must be less or equal to high in uniform distribution
```

Experienced with mxnet 1.0.0 on macOS Sierra and python 3.6.3

**Comment by reminisce** [comment]
In this case, low=3, high=1, raising an error is consistent with NumPy's random.uniform definition.

[When high == low, values of low will be returned. If high < low, the results are officially undefined and may eventually raise an error, i.e. do not rely on this function to behave when passed arguments satisfying that inequality condition.](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.uniform.html#numpy-random-uniform)

**Comment by marfago** [comment]
I think that crashing the VM because of wrong parameter should not be considered a consistent behavior. The right expected behavior should be a python exception.

**Comment by reminisce** [comment]
Agree that crashing the vm is not a desired behavior. Need to add exception handling in frontend.

**Comment by eric-haibin-lin** [comment]
@anirudh2290 is working on general exception handling.

**Comment by marfago** [comment]
#9154

**Comment by anirudh2290** [comment]
#7335
