### ISSUE TITLE
is it possible to use GPU to produce new data on real time with DataIter or Gluon.dataloader?

### ISSUE THREAD

**Issue by dbsxdbsx** [apache/incubator-mxnet#9137]
Env: win10 ,mxnet 0.12
Sometimes, the data used to train is not on disk, but need to produce on real time. So following tutorial [here](http://mxnet.incubator.apache.org/tutorials/basic/data.html), I built a custom dataIter.   But  I found the training speed is slow whatever GPU I  used #9026 . Here I took some module like ,OpenCV to produce data.   So I guess it is due to the time used to produce data.       

Therefore， I want to know how to use GPU to produce real time data.

**Comment by piiswrong** [comment]
You don't need dataiter when using gluon.
Dataiters just return ndarrays. You can feed generated ndarrays directly to the network without any dataiter

**Comment by harshitajain1994** [comment]
Suggested Labels: "Gluon", "Question", "Data Loading"

**Comment by sandeep-krishnamurthy** [comment]
@dbsxdbsx - Please reopen if the issue still persists.
