### ISSUE TITLE
Docs build fails on master

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#9145]
## Description
It works if you checkout the 1.0.0 tag, then do 'submodule update'. 

If you switch to master, it fails. If you use a fork, regardless of tag, or updating submodules, it fails with the same error.

## Environment info (Required)
Mac, local build.

## Build info (Required if built from source)

Checkout the latest with master.

## Error Message:

```
make[1]: *** No rule to make target `/Users/markhama/Development/mxnet-aaron/nnvm/include/nnvm/c_api.h', needed by `build/src/c_api/c_api_error.o'.  Stop.
make[1]: Leaving directory `/workspace'
Exception occurred:
  File "/workspace/docs/mxdoc.py", line 56, in _run_cmd
    raise err
CalledProcessError: Command 'cd /workspace/docs/.. && make -j$(nproc) DEBUG=1' returned non-zero exit status 2
Execute "cd /workspace/docs/.. && make -j$(nproc) DEBUG=1"
Command 'cd /workspace/docs/.. && make -j$(nproc) DEBUG=1' returned non-zero exit status 2
The full traceback has been saved in /tmp/sphinx-err-WfHDZZ.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
make: Leaving directory `/workspace/docs'
make: *** [docs] Error 2
```

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.  cd into the project root, and run `make docs`.

## What have you tried to solve it?

1. Checking out 1.0.0 tag seems to work... but only after you do submodule update.
2. Tried a fresh clone and build, but same error.

**Comment by aaronmarkham** [comment]
The docs are built in a Docker container. With the latest build from master, Docker hits a memory limit which causes the build to fail, and there's no clear indication that this is what happened.  From a tip seen on a similar unexplained exit, I bumped the memory limit in Docker's preferences to 4GB, and the build completes.

**Comment by Roshrini** [comment]
@aaronmarkham Getting similar issue on mac while building the docs using `make docs`,

```
Makefile:224: WARNING: Significant performance increases can be achieved by installing and enabling gperftools or jemalloc development packages
make[1]: *** No rule to make target `/Users/roshanin/incubator-mxnet/dmlc-core/include/dmlc/registry.h', needed by `build/src/operator/contrib/bounding_box.o'.  Stop.
make[1]: Leaving directory `/workspace'

Exception occurred:
  File "/workspace/docs/mxdoc.py", line 56, in _run_cmd
    raise err
CalledProcessError: Command 'cd /workspace/docs/.. && make -j$(nproc) DEBUG=1' returned non-zero exit status 2
Execute "cd /workspace/docs/.. && make -j$(nproc) DEBUG=1"
Command 'cd /workspace/docs/.. && make -j$(nproc) DEBUG=1' returned non-zero exit status 2
The full traceback has been saved in /tmp/sphinx-err-BzggqS.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
make: Leaving directory `/workspace/docs'
make: *** [docs] Error 2
```

Increasing docker memory doesn't seem to work either. By any chance, did you find the root cause of this?
