### ISSUE TITLE
Install instructions - selector broken

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#9146]
## Description

When choosing Windows as your install choice on [the install page](https://mxnet.incubator.apache.org/install/index.html), you are presented with just "validate mxnet installation" and no other content. 

Also, if you [look through the code](https://github.com/apache/incubator-mxnet/blame/master/docs/install/index.md#L1487-L1516), Windows install docs have "build from source" instructions but these don't appear when using the selector.

Also, if you look at the md page on github, the lack of section headings makes this page unreadable and confusing. 

Adding markdown section headings doesn't seem to be compatible with the divs used for the install selector.

## Environment info (Required)

Any

## Build info (Required if built from source)

Master

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Go to [the install page](https://mxnet.incubator.apache.org/install/index.html),
2. Try out the selector... choose Windows.

## What have you tried to solve it?

1. I tried tinkering with the selector code, but it misbehaves. The divs aren't really compatible with markdown, so fixing it for mxnet.io breaks it for github...

**Comment by szha** [comment]
Would you propose a pull request for the fix?
