### ISSUE TITLE
random_normal with wrong parameters crashes

### ISSUE THREAD

**Issue by marfago** [apache/incubator-mxnet#9154]
The code ```nd.random_normal(0,-1,(2,3))``` causes the python VM to crash with 
```
22:32:49] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [22:32:49] src/operator/random/./sample_op.h:313: Check failed: param.scale > 0 (-1 vs. 0) scale parameter in gaussian has to be positive
```

Experienced with mxnet 1.0.0 on macOS Sierra and python 3.6.3

**Comment by sxjscience** [comment]
@marfago Since the standard deviation can never be negative, it's reasonable to throw an error.

**Comment by marfago** [comment]
@sxjscience I agree if the error is wrapped in a python exception. In this case the VM exits due to a c++ assert.

**Comment by sxjscience** [comment]
I see. I think we can merge the discussion into the other issue https://github.com/apache/incubator-mxnet/issues/9131

**Comment by marfago** [comment]
Probably would be better to create a new issue with a list where to report all the issues like this and #9131
