### ISSUE TITLE
mx.nd.tanh and mx.symbol.tanh yields different results.

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#9155]
The results of using mx.symbol.tanh/mx.symbol.Activation(name, data, act_type='tanh') yields values>1 and values<-1 and results are similar

whereas using mx.nd.tanh yields tresults -1<results<1

Kindly suggest what is the solution for this problem

**Comment by sxjscience** [comment]
@chowkamlee81 Would you provide a reproducible example?

**Comment by chowkamlee81** [comment]
@sxjscience , closing the comment as you suggested earlier PR
