### ISSUE TITLE
YARN support data locality

### ISSUE THREAD

**Issue by schlichtanders** [apache/incubator-mxnet#9157]
Hadoop / YARN is famous for bringing computation to the data and not vice versa. Does MXNet's YARN support also supports this kind of data locality?
If not, is it easy to add to the YARN client?

**Comment by schlichtanders** [comment]
anyone?

**Comment by liuzx32** [comment]
anyone?

**Comment by sandeep-krishnamurthy** [comment]
@nswamy - Any comment on this issue?

**Comment by ThomasDelteil** [comment]
You can read this blog post on how to run MXNet on Spark using AWS EMR cluster [link](https://aws.amazon.com/fr/blogs/machine-learning/distributed-inference-using-apache-mxnet-and-apache-spark-on-amazon-emr/) 

@sandeep-krishnamurthy can you please close the issue?

@schlichtanders if you would like to follow up, please create a thread on https://discuss.mxnet.io, thanks!
