### ISSUE TITLE
How to convert data in range -m to +n to data in range 0 to1? Is there are any python API

### ISSUE THREAD

**Issue by ChidanandKumarKS** [apache/incubator-mxnet#9160]
I want to covert floating point symbol data in  the range -m to +n to the range 0 to 1.
Is there any python mx.symbol APIs available in mxnet? kindly do the needfull

**Comment by reminisce** [comment]
Just use element-wise ops. Suppose `x` is the tensor you want to convert, and the data range is `[-m, n]`, define
```python
y = x / (m + n) + m / (m + n)
```

**Comment by indhub** [comment]
Answered above.
