### ISSUE TITLE
fatal error: cub/cub.cuh: No such file or directory

### ISSUE THREAD

**Issue by Feywell** [apache/incubator-mxnet#9162]
## Description
I encounter a error, when I install from code as follow:

> In file included from src/operator/nn/convolution.cu:33:0:
> src/operator/nn/./depthwise_convolution-inl.h:33:23: **fatal error: cub/cub.cuh: No such file or directory**
> compilation terminated.
> make: *** [build/src/operator/nn/convolution_gpu.o] Error 1
> make: *** Waiting for unfinished jobs....
> src/operator/contrib/./.././c_lapack_api.h:328:198: note: #pragma message: Warning: lapack usage not enabled, linalg-operators will not be available. Ensure that lapack library is installed and build with USE_LAPACK=1 to get lapack functionalities.

## Environment info (Required)
**system: Centos 6.4
CUDA: 8.0**

> ----------Python Info----------
> ('Version      :', '2.7.13')
> ('Compiler     :', 'GCC 7.2.0')
> ('Build        :', ('default', 'Sep 22 2017 00:47:24'))
> ('Arch         :', ('64bit', ''))
> ------------Pip Info-----------
> ('Version      :', '9.0.1')
> ('Directory    :', '/home/liyang/anaconda2-5.0/lib/python2.7/site-packages/pip')

Package used (Python/R/Scala/Julia):
(I'm using Python)

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
**gcc  (version 5.4.0)**

Build config:
command: **`make -j $(nproc) USE_OPENCV=1 USE_BLAS=mkl USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda-8.0 USE_CUDNN=1`**

**Comment by reminisce** [comment]
`cub` has been moved to `3rdparty` folder. Update your submodule and try again.

**Comment by Feywell** [comment]
@reminisce Thank you! Can you tell me the detail?
I just git clone code yesterday. Why it is not work.
So I don't know which submodule need to update.

**Comment by sxjscience** [comment]
@Feywell 
```
cd mxnet/3rdparty
git submodule add https://github.com/dmlc/cub cub 
```

**Comment by Feywell** [comment]
@sxjscience  Thank you!
It is work for me.
