### ISSUE TITLE
how to reshape ouput during forward like caffe?

### ISSUE THREAD

**Issue by conansherry** [apache/incubator-mxnet#9163]
like faster-rcnn proposal_target_layer.py
def forward(self, bottom, top):

        .........

        # sampled rois
        top[0].reshape(*rois.shape)
        top[0].data[...] = rois

        # classification labels
        top[1].reshape(*labels.shape)
        top[1].data[...] = labels

        # bbox_targets
        top[2].reshape(*bbox_targets.shape)
        top[2].data[...] = bbox_targets

        # bbox_inside_weights
        top[3].reshape(*bbox_inside_weights.shape)
        top[3].data[...] = bbox_inside_weights

        # bbox_outside_weights
        top[4].reshape(*bbox_inside_weights.shape)
        top[4].data[...] = np.array(bbox_inside_weights > 0).astype(np.float32)

how to do this in mxnet? shape may be different in each forward.

**Comment by chinakook** [comment]
Mod.reshape

**Comment by Godricly** [comment]
if you are using ndarray, you can reshape it like numpy array.

**Comment by anirudh2290** [comment]
This questions has been answered and has been idle for a while now. Can we close this ? @sxjscience

**Comment by sxjscience** [comment]
Close it now. Feel free to reopen it.
