### ISSUE TITLE
Sample example codes to work on ConvLSTM and ConvGRU based on 2D images..

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#9179]
I would like to work on spatio-temporal mechanism using ConvLSTM/ConvGRU.
I would like to know any sample example code to work on ConvLSTM/ConvGRU is available in mxnet.
Kindly do the needful

**Comment by chowkamlee81** [comment]
@sxjscience , do you have any sample codes to work on ConvLSTM/ConvGRU.
Kindly reply

**Comment by sxjscience** [comment]
@chowkamlee81 You can try to use the ConvLSTM/ConvRNN implemented in Gluon: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/contrib/rnn/conv_rnn_cell.py. Also, you can refer to the [HKO-7](https://github.com/sxjscience/HKO-7) project, which is implemented in MXNet.

**Comment by chowkamlee81** [comment]
Thanks for your kind reply and necessary inputs. I will try go thru the examples as mentioned in HKO-7 project.

**Comment by leleamol** [comment]
Recommended Labels: "Question","Completed"
