### ISSUE TITLE
How to make a signed float32 multi-channel input .rec file for ImageRecordIter?

### ISSUE THREAD

**Issue by PhanTask** [apache/incubator-mxnet#9181]
I have some multi-channel grid data ( shape is (100 x 100 x 3) ) whose type are signed float32 (e.g. -12.5486, 65.3112), and I have read them and converted them to some numpy arrays. I want to use them as 3 channel image inputs for some CNN models, and I also want to use ImageRecordIter to achieve image data augmentation, but I don't know how to pack those data correctly.
I `tried mx.recordio.pack_img` but it seems that it can only pack the data into `.jpg` or `.png` format, which doesn't support signed float data storage (for example, the negative float numbers will be 0, and the positive float numbers will be changed after unpacking (500.5=>255 or 497.xxxxxx or 505.xxxxxx, depending on the image format parameter I set in `mx.recordio.unpack_img` ) ).
I'm not familiar with mxnet data packing/unpacking/loading API, so could anyone tell me how to use multi-channel signed float32 data as the image input and apply data augmentation by ImageRecordIter in a right way? Any suggestions would be greatly appreciated.

**Comment by zhreshold** [comment]
You may want to try https://mxnet.incubator.apache.org/api/python/io/io.html?highlight=ndarrayit#mxnet.io.NDArrayIter
ImageRecordIter is designed for images.

**Comment by PhanTask** [comment]
@zhreshold 
Thank you for your suggestion. But it seems `mxnet.io.NDArrayIter` doesn't have any ready-made functions to achieve image-like data augmentation. Is that mean I can only write some augmentation algrithm manually? I'm just very curious about the possibility of making float grid data as fake image inputs since ImageRecordIter and mxnet can handle float input.

**Comment by sandeep-krishnamurthy** [comment]
@PhanTask - Please ask usability question at  https://discuss.mxnet.io/ .
Please reopen this issue if you face any bugs.
