### ISSUE TITLE
Cannot find mxnet-cpp/op.h

### ISSUE THREAD

**Issue by zhangxiao-ustc** [apache/incubator-mxnet#9187]
I wrote a implementation based on interface provided by mxnet/cpp-packages. But when compiling, it
could not find file "mxnet-cpp/op.h". In detail, the problem is: 

In cpp-package/include/mxnet-cpp/MxNetCpp.h, it includes "mxnet-cpp/op.h". However, there is no such file named "op.h" under dir "mxnet-cpp/". What's wrong?

**Comment by thirdwing** [comment]
As said in our documents (https://mxnet.incubator.apache.org/tutorials/c++/basics.html):

> Among the header files, op.h is special since it is generated dynamically. The generation should be done when building the C++ package. 

Please follow the instructions from https://mxnet.incubator.apache.org/get_started/build_from_source.html#build-the-c-package

**Comment by anirudh2290** [comment]
@marcoabreu

**Comment by yzhliu** [comment]
Close since @thirdwing answered. @zhangxiao-ustc feel free to reopen if you still have the problem.

**Comment by dexception** [comment]
This file is not getting generated !
