### ISSUE TITLE
the serious bug of row_sparse_pull, it return the unexpected results (mxnet-0.12.1)

### ISSUE THREAD

**Issue by everwind** [apache/incubator-mxnet#9190]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
the result of kv.row_sparse_pull is error

kv_store = mx.kv.create('local') 
feat_num=60000000
emb_size=16
x=mx.nd.random_normal(shape=(feat_num, emb_size+1))/emb_size
kv_store.init( 'weight' , x.tostype('row_sparse'))

weight = mx.nd.sparse.zeros('row_sparse', (feat_num, emb_size+1) )
nd.waitall()

kv_store.row_sparse_pull('weight', out=weight, row_ids = mx.nd.array(range(59000000,59000010)))
print weight.data
print weight.indices

above codes  produce the unexpected result :

[[-0.06001008  0.12529369  0.01055183  0.03823091  0.0157164   0.05378302
   0.10645325 -0.05574675  0.043387   -0.09978856 -0.02615129  0.10425547
   0.02766469  0.00755506 -0.03756119  0.04600668 -0.1275474 ]
 [-0.01440927 -0.03559005  0.08031632 -0.14433415  0.01954315  0.04838947
  -0.07277583  0.01327891  0.08509432  0.00696959 -0.12846318 -0.05156695
   0.05502741 -0.0296046   0.02275628 -0.0119295  -0.02386227]
 [ 0.01497707 -0.01221847 -0.0309307  -0.04224245 -0.02266348  0.03766544
   0.02412536 -0.03766586  0.08927941  0.05852216  0.0724726  -0.13113973
  -0.02900447  0.0475208  -0.02984896 -0.04399877  0.06236285]]
<NDArray 3x17 @cpu(0)>

[59000000 59000004 59000008]
<NDArray 3 @cpu(0)>

``

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by everwind** [comment]
@eric-haibin-lin  row_sparse_pull return the unexpected results

**Comment by eric-haibin-lin** [comment]
nd.array by default uses float32. Could you check if your rowid are correct integers? What’s the expected output?

**Comment by everwind** [comment]
@eric-haibin-lin thanks a lot !  row_ids = mx.nd.array(range(59000000,59000010), dtype='int32')    Assign the dtype='int32', it works correctly .
