### ISSUE TITLE
Get a element of tensor

### ISSUE THREAD

**Issue by ly-atdawn** [apache/incubator-mxnet#9197]
If I have a object of Tensor, like this:
Tensor<xpu, 2> labels = in_data[softmaxout_enum::kLabel].FlatTo2D<xpu, real_t>(s);
How can I get every label in labels, it is like: labels[i]???
Thanks

**Comment by eric-haibin-lin** [comment]
`Tensor<xpu, 2> labels ` is a 2-D tensor. labels[i][j] should return the `real_t` element at position (i,j)

**Comment by ly-atdawn** [comment]
Why int int(labels[i][j]) or cout<<labels[0][1] in compiling is right, whils in performing is wrong?
And, Tensor<xpu, 2> labels, labels shape is (1, batch_size). so wo could get every label with labels[0][i]?? Is right??
Thanks

**Comment by ly-atdawn** [comment]
Why int(labels[i][j]) or cout<<labels[0][1] in compiling is right, whils in performing is wrong?
And, Tensor<xpu, 2> labels, labels shape is (1, batch_size). so wo could get every label with labels[0][i]?? Is right??
Thanks

**Comment by ly-atdawn** [comment]
Help

**Comment by indhub** [comment]
This is not an issue. For how-to questions, please use the [user forum](https://discuss.mxnet.io/).
