### ISSUE TITLE
error about rcnn of example

### ISSUE THREAD

**Issue by yhl41001** [apache/incubator-mxnet#9201]
when i run rcnn in example folder(mxnet1.0.0 and mxnet0.12.0 version), i get error:
python demo.py --prefix ../../../mxnet0120/example/rcnn/model/final --epoch 0 --image ../../../mxnet0120/example/data/person.jpg
[14:47:44] /home/yuhailong/mxnet/mxnet100/dmlc-core/include/dmlc/./logging.h:308: [14:47:44] src/ndarray/ndarray.cc:1053: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7fc97e33bad9]
[bt] (1) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet7NDArray4LoadEPN4dmlc6StreamEPSt6vectorIS0_SaIS0_EEPS4_ISsSaISsEE+0x1c5) [0x7fc9805ba775]
[bt] (2) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(MXNDArrayLoad+0x248) [0x7fc980a134b8]
[bt] (3) /lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc9b278edcc]
[bt] (4) /lib64/libffi.so.6(ffi_call+0x1f5) [0x7fc9b278e6f5]
[bt] (5) /usr/lib64/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x30b) [0x7fc98a603c8b]
[bt] (6) /usr/lib64/python2.7/lib-dynload/_ctypes.so(+0xaa85) [0x7fc98a5fda85]
[bt] (7) /lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fc9c40f88e3]
[bt] (8) /lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x2336) [0x7fc9c418d036]
[bt] (9) /lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fc9c4193e3d]

Traceback (most recent call last):
  File "demo.py", line 162, in <module>
    main()
  File "demo.py", line 157, in main
    predictor = get_net(symbol, args.prefix, args.epoch, ctx)
  File "demo.py", line 55, in get_net
    arg_params, aux_params = load_param(prefix, epoch, convert=True, ctx=ctx, process=True)
  File "/home/yuhailong/mxnet/mxnet100/example/rcnn/rcnn/utils/load_model.py", line 66, in load_param
    arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "/home/yuhailong/mxnet/mxnet100/example/rcnn/rcnn/utils/load_model.py", line 32, in load_checkpoint
    save_dict = mx.nd.load('%s-%04d.params' % (prefix, epoch))
  File "/home/yuhailong/mxnet/mxnet100/python/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/home/yuhailong/mxnet/mxnet100/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:47:44] src/ndarray/ndarray.cc:1053: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7fc97e33bad9]
[bt] (1) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet7NDArray4LoadEPN4dmlc6StreamEPSt6vectorIS0_SaIS0_EEPS4_ISsSaISsEE+0x1c5) [0x7fc9805ba775]
[bt] (2) /home/yuhailong/mxnet/mxnet100/python/mxnet/../../lib/libmxnet.so(MXNDArrayLoad+0x248) [0x7fc980a134b8]
[bt] (3) /lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc9b278edcc]
[bt] (4) /lib64/libffi.so.6(ffi_call+0x1f5) [0x7fc9b278e6f5]
[bt] (5) /usr/lib64/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x30b) [0x7fc98a603c8b]
[bt] (6) /usr/lib64/python2.7/lib-dynload/_ctypes.so(+0xaa85) [0x7fc98a5fda85]
[bt] (7) /lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fc9c40f88e3]
[bt] (8) /lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x2336) [0x7fc9c418d036]
[bt] (9) /lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fc9c4193e3d]

**Comment by yhl41001** [comment]
I have soved the problem by download the params again from another source.

**Comment by pasha76** [comment]
how did you download? can you please explain more- I have the same issue.
