### ISSUE TITLE
Caffe_Converter produce mx.symbol.SoftmaxOuput rather than SoftmaxActivation

### ISSUE THREAD

**Issue by gzygzy9211** [apache/incubator-mxnet#9225]
incubator-mxnet/tools/caffe_converter/convert_symbol.py 
According to the py code, it produce  mx.symbol.SoftmaxOuput  for caffe's  layer of type "Softmax"

However mx.symbol.SoftmaxOuput needs label and it computes gradient w.r.t to its input, which is not expected during inference.

So am I right that we should use mx.symbol.SoftmaxActivation while converting caffe's "Softmax" layer?

====================edit======================
 
it seems that mx.symbol.SoftmaxActivation has been deprecated, instead should we use mx.symbol.softmax ?

**Comment by szha** [comment]
We are deprecating caffe converter
