### ISSUE TITLE
Numpy Diag in MXNet

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#9253]
Borrow from https://discuss.gluon.ai/t/topic/3846.

We can consider to implement `np.diag` in the future.
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html

**Comment by ifeherva** [comment]
I am interested implementing this, is there a jira issue already?

**Comment by sxjscience** [comment]
@ifeherva NoJIRA issue for this one yet.

**Comment by ifeherva** [comment]
I am working on replicating np.diag(). Once done will do the full diagonal operator. This is my first operator so I am learning a lot at the moment.

See progress here: https://github.com/ifeherva/incubator-mxnet/tree/diagonal_operator

2d forward pass CPU [x]
2d forward pass GPU [x]
1d forward pass CPU []
1d forward pass GPU []
2d backward pass CPU []
2d backward pass GPU []
1d backward pass CPU []
1d backward pass GPU []

**Comment by samskalicky** [comment]
@eric-haibin-lin This issue can be closed now that the PR has been merged
