### ISSUE TITLE
nd.random_normal(0, **0**)

### ISSUE THREAD

**Issue by leo-gan** [apache/incubator-mxnet#9255]
if scale=**0** (it is 1 by default), the function random_normal is hanging up without error indefinitely in Jupyter Notebook. Python 3.5

**Comment by sxjscience** [comment]
@leo-gan Which version of MXNet are you using? I've checked tried the code in the latest master version and it raises this error:

```log
src/engine/./threaded_engine.h:359: [00:13:15] src/operator/random/./sample_op.h:297: Check failed: param.scale > 0 (0 vs. 0) scale parameter in gaussian has to be positive
```
which look reasonable.

**Comment by leo-gan** [comment]
it's the last version of MXNet.
>pip list
...
mxnet-cu80 (1.0.0)

Regards,

Leonid Ganeline
Microsoft MVP (BizTalk Server & Microsoft Integration & Microsoft Azure)
http://geekswithblogs.net/leonidganeline/

**Comment by javelinjs** [comment]
I think 1.0.0.rc1 adopts the recent fix @szha

**Comment by leo-gan** [comment]
Thanks!


Regards,

Leonid Ganeline
Microsoft MVP (BizTalk Server & Microsoft Integration & Microsoft Azure)
http://geekswithblogs.net/leonidganeline/
