### ISSUE TITLE
How to define a variable that is not trainable?

### ISSUE THREAD

**Issue by lightingghost** [apache/incubator-mxnet#9258]
When defining a variable in tensorflow, it is possible to set `trainable=False`.

Is is possible to do so in mxnet? for both `symbol` and `ndarray` APIs?

Thanks

**Comment by mwbyeon** [comment]
You can use `fixed_param_names` paramter
See https://mxnet.incubator.apache.org/api/python/module/module.html?highlight=fixed_param_names#mxnet.module.Module

And an example.
https://github.com/apache/incubator-mxnet/blob/b2ce81218b13c3140dc3d2fd9fa27a1dd0264b75/example/ssd/train/train_net.py#L200-L240

**Comment by lightingghost** [comment]
Thanks for helping! @mwbyeon
