### ISSUE TITLE
a typo in doc "nd.sum"

### ISSUE THREAD

**Issue by NonvolatileMemory** [apache/incubator-mxnet#9272]
`data = [[1,2,0],
        [3,0,1],
        [4,1,0]]

csr = cast_storage(data, 'csr')

sum(csr, axis=0)
[ 8.  2.  2.]

sum(csr, axis=1)
[ 3.  4.  5.]`

I think sum(csr, axis=0) should be [ 3.  4.  5.]?

**Comment by NonvolatileMemory** [comment]
https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html?highlight=sum#mxnet.ndarray.sum

**Comment by NonvolatileMemory** [comment]
sorry, i mean it should be8 3 1

**Comment by szha** [comment]
@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
Yes that's a typo. @NonvolatileMemory do you mind posting a pull request to fix this?  
https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/broadcast_reduce_op_value.cc?utf8=%E2%9C%93#L79-L80

**Comment by NonvolatileMemory** [comment]
@eric-haibin-lin  very thx! I will do it!

**Comment by NonvolatileMemory** [comment]
@eric-haibin-lin https://github.com/apache/incubator-mxnet/pull/9287
