### ISSUE TITLE
Is compilation on 32 bit supported?

### ISSUE THREAD

**Issue by nehaljwani** [apache/incubator-mxnet#9274]
## Description
Tried compiling mxnet using gcc 7.2.0 (32-bit), build fails with 'out of memory error'

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio): gcc

MXNet commit hash: Using tag: 1.0.0

Build config:
After applying the patches at https://github.com/apache/incubator-mxnet/pull/9273
```
export MKLROOT="<path-to-full-mkl-32-bit>"
make -j${CPU_COUNT} \
  AR="$AR" \
  CC="$CC" \
  CXX="$CXX" \
  USE_CUDA=0 \
  USE_CUDNN=0 \
  USE_OPENCV=1 \
  USE_LAPACK=1 \
  USE_BLAS=mkl \
  USE_STATIC_MKL=NONE \
  USE_INTEL_PATH=NONE \
  USE_MKL2017=1 \
  USE_PROFILER=1 \
  USE_CPP_PACKAGE=1 \
  USE_SIGNAL_HANDLER=1 \
  ADD_CFLAGS="$CFLAGS" \
  ADD_LDFLAGS="$LDFLAGS" \
  USE_OPENMP=1 \
  USE_JEMALLOC=1 \
  VERBOSE=1
```

## Error Message:
```
cc1plus: out of memory allocating 65536 bytes after a total of 3303088128 bytes
make: *** [Makefile:377: build/src/operator/tensor/indexing_op.o] Error 1
```

## What have you tried to solve it?

1. May not be relevant, but tried passing `-ftrack-macro-expansion=0` to CFLAGS.

**Comment by dabraude** [comment]
I was having trouble with windows 32bit and I found defining this 
-DDMLC_CXX11_THREAD_LOCAL=0
seems to fix it (but it does generate warnings about not being suported)

**Comment by vdantu** [comment]
@nehaljwani : Does this solve your issue? 

@sandeep-krishnamurthy : Please label this as "Compilation Errors" and close this.

**Comment by vdantu** [comment]
@sandeep-krishnamurthy : Sorry for the above .. Please label this "Build" and close this
