### ISSUE TITLE
should gluon use the sublinear memory

### ISSUE THREAD

**Issue by alexalex1234** [apache/incubator-mxnet#9279]
I set export MXNET_BACKWARD_DO_MIRROR=1 while use gluon 
Does this environment work in gluon?
Thanks a lot

**Comment by eric-haibin-lin** [comment]
It doesn't work in Gluon yet

**Comment by szha** [comment]
Related: #6644

**Comment by spidyDev** [comment]
@sandeep-krishnamurthy  Please close this issue, as the query was answered.
