### ISSUE TITLE
error on the print(net.weight)

### ISSUE THREAD

**Issue by leo-gan** [apache/incubator-mxnet#9284]
Hi,
I'm executing the http://localhost:8888/notebooks/mxnet/chapter02_supervised-learning/linear-regression-gluon.ipynb example.
`net = gluon.nn.Dense(1, in_units=2),
print(net.weight)` - returns

> KeyError                                  Traceback (most recent call last)
> <ipython-input-22-f0e92cfa80b4> in <module>()
> ----> 1 print(net.weight)
>       2 print(net.bias)
> 
> ...\lib\site-packages\mxnet\gluon\parameter.py in __repr__(self)
>     118     def __repr__(self):
>     119         s = 'Parameter {name} (shape={shape}, dtype={dtype})'
> --> 120         return s.format(**self.__dict__)
>     121 
>     122     @property
> 
> KeyError: 'shape'

It is the 

> mxnet-cu80 (1.0.0)
OS: Windows 10
Python 3.5

A similar error on this line:
`print(net.bias)`

**Comment by eric-haibin-lin** [comment]
@szha was this fixed?

**Comment by szha** [comment]
Yes, this has been fixed in the latest version
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/parameter.py#L120
