### ISSUE TITLE
SIGABRT when running mxnet_unit_tests

### ISSUE THREAD

**Issue by adstraw** [apache/incubator-mxnet#9285]
## Description
Running build/tests/cpp/mxnet_unit_tests results in an abort

## Environment info (Required)
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Nov 19 2016 06:48:10'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '8.1.1')
('Directory    :', '/usr/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('release      :', '4.4.0-97-generic')
('version      :', '#120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-111
Thread(s) per core:    2
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2338.281
CPU max MHz:           3800.0000
CPU min MHz:           1000.0000
BogoMIPS:              4989.72
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27,56-83
NUMA node1 CPU(s):     28-55,84-111
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0218 sec, LOAD: 0.9965 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0223 sec, LOAD: 0.4823 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0885 sec, LOAD: 0.5319 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0350 sec, LOAD: 0.7963 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1114 sec, LOAD: 0.2923 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1889 sec, LOAD: 0.7751 sec.

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)
Followed build instruction for Linux->Python->CPU->Build from Source here:
https://mxnet.incubator.apache.org/get_started/install.html

Build tests using:
make test

Compiler (gcc/clang/mingw/visual studio):
gcc 5.4.0

MXNet commit hash:
25720d0e3c29232a37e2650f3ba3a2454f9367bb

Build config:
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas

## Error Message:
[  PASSED  ] 63 tests.
[Thread 0x7ffed57fa700 (LWP 5009) exited]
[Thread 0x7ffed77fe700 (LWP 5005) exited]
[Thread 0x7ffed67fc700 (LWP 5007) exited]
[Thread 0x7ffed5ffb700 (LWP 5008) exited]
[Thread 0x7ffed6ffd700 (LWP 5006) exited]
*** Error in <path>: double free or corruption (!prev): 0x00000000009ad1f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff2bf97e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ffff2c0237a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff2c0653c]
/usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4(_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev+0x29)[0x7ffff445fe19]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x9a)[0x7ffff2bbc36a]
/usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4(+0x1f633)[0x7ffff442e633]

GDB backtrace:
Thread 1 "mxnet_unit_test" received signal SIGABRT, Aborted.
0x00007ffff2bb7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff2bb7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff2bb902a in __GI_abort () at abort.c:89
#2  0x00007ffff2bf97ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff2d12e98 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff2c0237a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff2d12fc8 "double free or corruption (!prev)",
    action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ffff2c0653c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00007ffff445fe19 in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() () from /usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4
#7  0x00007ffff2bbc36a in __cxa_finalize (d=0x7ffff46b8000) at cxa_finalize.c:56
#8  0x00007ffff442e633 in ?? () from /usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4
#9  0x00007fffffffe760 in ?? ()
#10 0x00007ffff7de7de7 in _dl_fini () at dl-fini.c:235
Backtrace stopped: frame did not save the PC

## Minimum reproducible example
using standard CPP unit tests without modification

## Steps to reproduce
1.  make test
2.  ./builtd/tests/cpp/mxnet_unit_tests

**Comment by spidyDev** [comment]
@adstraw Please try with latest source  and reopen the issue if the issue persists.

@sandeep-krishnamurthy  Please close this issue for now
