### ISSUE TITLE
How to get the symbol type?

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#9289]
How do i know the type of symbol? Convolution or Pooling or BN

**Comment by mwbyeon** [comment]
You can use `symbol.debug_str()`
See https://mxnet.incubator.apache.org/api/python/symbol/symbol.html?#mxnet.symbol.Symbol.debug_str

**Comment by lupesko** [comment]
Thank you @mwbyeon !
@KeyKy I think we can close the issue, feel free to re-open if you still have questions.

**Comment by lupesko** [comment]
@nswamy please apply labels:
Triaged
Request For Information

And please close.

**Comment by KeyKy** [comment]
THX!
