### ISSUE TITLE
find a bug in mxnet.gluon.utils.clip_global_norm(arrays, max_norm)

### ISSUE THREAD

**Issue by lck1201** [apache/incubator-mxnet#9291]
Find a bug in mxnet.gluon.utils.clip_global_norm(arrays, max_norm)
```python
def clip_global_norm(arrays, max_norm):
    """Rescales NDArrays so that the sum of their 2-norm is smaller than `max_norm`.
    """
    assert len(arrays) > 0
    ctx = arrays[0].context
    total_norm = ndarray.add_n(*[ndarray.dot(x, x).as_in_context(ctx)
                                 for x in (arr.reshape((-1,)) for arr in arrays)])
    total_norm = ndarray.sqrt(total_norm).asscalar()
    if not np.isfinite(total_norm):
        warnings.warn(UserWarning('nan or inf is detected. Clipping results will be undefined.'),
                      stacklevel=2)
    scale = max_norm / (total_norm + 1e-8)
    if scale < 1.0:
        for arr in arrays:
            arr *= scale
    return total_norm
```
Perhaps the function should return **arrays** rather than **total_norm**
Thx!

**Comment by lupesko** [comment]
Thank you @lck1201 !
I think you are correct, looping in @piiswrong for guidance.
Additionally, we should expand the docstring to be more informative.

@piiswrong - can you confirm this is indeed a bug?
@lck1201 - would you like to submit a PR with this fix?

**Comment by lupesko** [comment]
@nswamy please apply labels:
Triaged
Bug

**Comment by sxjscience** [comment]
This is not a bug. `clip_global_norm` clips the gradient arrays in place and returns the original norm.

**Comment by lck1201** [comment]
@lupesko  @sxjscience  thank you guys
