### ISSUE TITLE
Trouble installing on Windows

### ISSUE THREAD

**Issue by gamenn** [apache/incubator-mxnet#9294]
[I am posting this issue for the attention of @zhreshold, as suggested by a member of MXNet team.

I am trying to get MXNet working on Windows with Anaconda distribution of Python.  After running around a bit, I was told by a member of the MXNet team (AstonZ) that the installation command to use is:

`pip install mxnet-cu80==1.0.0 `

However, after doing that, "import mxnet as mx" line fails with “The specified module could not be found” error. 
  
Windows version: Windows 10
Python version: 3.6.2

**Comment by zhreshold** [comment]
This is most likely you are pythonmidmatched pip and python.
Make sure you install using the pip come with anaconda

**Comment by lupesko** [comment]
@gamenn can you please provide more info:
- Windows version
- Python version
- The full error stack

**Comment by lupesko** [comment]
@nswamy please apply labels:
- Triaged
- Windows
- Installation

**Comment by gamenn** [comment]
@zhreshold: I ran "pip install mxnet-cu80==1.0.0" from within the Anaconda prompt. I presume that would the right way to install; isn't it?

**Comment by gamenn** [comment]
@lupesko: Added Windows and Python version info to the issue above. There is not much of a error callstack for this issue since the very first import line itself is failing as unrecognized module.

**Comment by zhreshold** [comment]
@gamenn I suggest you can do quick self diagnose, for example, pip --version inside anaconda prompt, try to locate the site-packages of conda python, etc.

Anyways, if you are still out of luck, please use the script of https://github.com/apache/incubator-mxnet/blob/master/tools/diagnose.py and paste results here.

**Comment by gamenn** [comment]
@zhreshold: Pasting below the output of diagnose.py

----------Python Info----------
Version      : 3.6.2
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('default', 'Sep 19 2017 08:03:39')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\site-packages\pip
----------MXNet Info-----------
Traceback (most recent call last):
  File "diagnose.py", line 107, in check_mxnet
    import mxnet
  File "C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\__init__.py", line 25, in <module>
    from . import engine
  File "C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\base.py", line 111, in <module>
    _LIB = _load_lib()
  File "C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Users\myUserName\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

----------System Info----------
Platform     : Windows-10-10.0.15063-SP0
system       : Windows
node         : SEA-9903526803
release      : 10
version      : 10.0.15063
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0140 sec, LOAD: 0.9081 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0108 sec, LOAD: 0.0170 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0325 sec, LOAD: 0.0380 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0307 sec, LOAD: 0.0670 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0180 sec, LOAD: 0.1020 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0088 sec, LOAD: 0.0402 sec.

**Comment by zhreshold** [comment]
@gamenn you are missing dll in path. CUDA runtime, visual c++ or something. windows won’t tell you which one is missing.

**Comment by gamenn** [comment]
What exactly are the path variable names MXNet looks for?

**Comment by gamenn** [comment]
By the way, it appears like people in general have run into problems getting MXNet to work on Windows. Here are some links that come upon a quick search:

https://github.com/apache/incubator-mxnet/issues/7145 

Blog by one person who apparently could not get it to work easily and had to struggle to find a way:
https://stankirdey.com/2017/03/09/installing-mxnet-deep-learning-framework-on-windows-10/
[As indicated in comments there, other people have had problems as well]

https://discuss.mxnet.io/t/installing-mxnet-on-windows/374

Is this the end of this issue here or should I be waiting for a response?
Thanks!

**Comment by zhreshold** [comment]
@gamenn Sorry for the late reply. I though it was resolved. 
In general, there's no `fancy` stuff you need to do to install on windows. We have pre-complied and packed to pip wheel so everyone should be able to install it using `pip install mxnet`. 
The windows version was available since 0.11 several months ago, and it is considerably stable because we do have a forum that have users reporting the installation on windows version. Recently it goes alright with very little complaining about installation problems.

Unfortunately, windows may sometimes missing some fundamental dependencies, such as visual c++ runtime, or CUDA runtime which must be installed separately by users, not to mention its complicated 
PATH management, making it hard to diagnose without experience. 

If you still have problems using mxnet-cu80, you can first try uninstall it, then `pip install mxnet` and try it to see if the CPU version works. If not, try install visual c++ 2015 redistributed package to enable c++ runtime on windows. If CPU version is good, then there must be some problem with the CUDA installation. You can test with CUDA samples provided by nvidia, or check the PATH again, mxnet do search for PATH so if should be fine just add them to PATH.

**Comment by gamenn** [comment]
@zhreshold Yes, when I did "pip install mxnet", the CPU version was indeed working. The problem was with getting the gpu version to work since I was getting the "gpu not enabled error". So, I was told that to get the gpu version working, I first needed to do "pip uninstall mxnet" and then do "pip install mxnet-cu80==1.0.0". When I did that, the "import mxnet as mx" line itself started failing. 

Does MXNet need any particular version of CUDA or cuDNN? I am going to uninstall CUDA and cuDNN from my machine and do a fresh install and give it a try. So, can you please let me know exactly which versions I need to get? Or, are the latest versions OK?

Thanks.

**Comment by zhreshold** [comment]
CUDNN will be provided in pip install, so you just need make sure cuda version is correct. 
Say you have cuda 8.0, install mxnet-cu80, cuda 9.0 with mxnet-cu90, that's it.
You can also checkout the nightly build with `pip install mxnet-cu8(9)0 --pre`

**Comment by gamenn** [comment]
Thank you. Got it working.
Just for the benefit of others running into this: By default, as of now, when we download Cuda from NVidia, it installs 9.1 version. Doing "pip install mxnet-cu90" results in "module not found error" with that version of Cuda. So, I had to specifically search for 9.0 version of Cuda and install it.
