### ISSUE TITLE
How to clear the optimizer states (reset a optimizer)

### ISSUE THREAD

**Issue by wkcn** [apache/incubator-mxnet#9307]
Hi, there.

I wrote an `eval_end_callback` function, and there is a condition that changing the learning rate of the optimizer when a metric decreases.

In mxnet.optimizer.SGD, there are the optimizer states.

```python 
rescaled_grad = lr * rescale_grad * clip(grad, clip_gradient) + wd * weight
state = momentum * state + rescaled_grad
weight = weight - state
```

I want to set the state value zero as the same as the initialization of the optimizer.

How to clear the optimizer states?

Thank you!

**Comment by ankkhedia** [comment]
@wkcn we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels

- Question
- Optimiser
and close the issue.
@wkcn  if done in error please reopen and comment
