### ISSUE TITLE
batch size in inference

### ISSUE THREAD

**Issue by BenLag2906** [apache/incubator-mxnet#9308]
I work with your version of mxnet under windows in c++.

I have heard of it was possible to make inference/prediction with a batch size. This practise is usually only for training.

Could you please provide a piece of explanation to do this? I want to to boost time processing on inference ? I have seen it in python but with MXPredForward in c++, I don't see any solution ?

**Comment by mwbyeon** [comment]
This is an example. 

Fist, Set the shape of input data with batch size. `(batch_size, channel, height, width)`
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc#L197-L200

Second, Create a model with the shape of input data.
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc#L209-L218

Third, do forward and get output.
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc#L248-L267

**Comment by BenLag2906** [comment]
Hi,
Thanks for quality of your answer,
Even if I have not really understand how concatenate my images inputs.
For each image, i must set input in a loop ? eg :
fr(int i; i < Batch_size ; i++) {
  image_data = bufferImage.at(i) ; 
  MXPredSetInput(pred_hnd, "data", image_data.data(), image_size); 
}
..

MXPredForward(pred_hnd); 

..
and extract of shape the results for the buffer image.

Is it the good approach ?

thanks in advance for your answer.

regards

**Comment by mwbyeon** [comment]
@BenLag2906  This is code for understanding. (not tested)

```cpp


// Allocate memory for a batch of images
const int image_size = width * height * channels;
std::vector<mx_float> batch_data = std::vector<mx_float>(batch_size * image_size);

// Assign
for ( int i=0 ; i<batch_size ; ++i ) {
    GetImageFile(batch_file[i], &batch_data[i * image_size], channels,
                 cv::Size(width, height), nd_data);
}

// Set input data for prediction
MXPredSetInput(pred_hnd, "data", batch_data.data(), batch_size * image_size);


// Do Predict Forward
MXPredForward(pred_hnd);


// Allocate memory for output
const int output_size = batch_size * num_classes;
std::vector<float> output(output_size);

// Get output
MXPredGetOutput(pred_hnd, 0, &(output[0]), output_size);

```

**Comment by BenLag2906** [comment]
Hi,
First,  thanks for your answer!

I have concatenate image as you described: it works fine...but my last problem is to separate results..
(I promiss :it'is my last question !!)
because when i use your code, it display all bounding box on an single image: How can I separate boudning box for each image of the batch size ? output[0] contains results of all image contained in the batch..( and for example many occurence)

Could you please give a piece of advise ?
thks.
Ben

**Comment by anirudhacharya** [comment]
@BenLag2906 please ask your follow up questions in the discussion forum here - https://discuss.mxnet.io/

@sandeep-krishnamurthy please add the labels - Question and kindly close the issue.
