### ISSUE TITLE
Refactor mxnet-scala code/tests/examples/docs to use "org.apache.mxnet" instead of "ml.dmlc.mxnet".

### ISSUE THREAD

**Issue by Roshrini** [apache/incubator-mxnet#9315]
## Description
Currently, MXNet-Scala library uses "ml.dmlc.mxnet" packages. As mxnet is under apache now,  mxnet-scala code/tests/example and docs should use "org.apache.mxnet" instead of "ml.dmlc.mxnet".

This work will change the way to import modules when using mxnet-scala package.

Old way:
```
scala> import ml.dmlc.mxnet._
   import ml.dmlc.mxnet._
scala> val arr = NDArray.ones(2, 3)
   arr: ml.dmlc.mxnet.NDArray = ml.dmlc.mxnet.NDArray@f5e74790
```
New way:
```
scala> import org.apache.mxnet._
   import org.apache.mxnet._

scala> val arr = NDArray.ones(2, 3)
   arr: org.apache.mxnet.NDArray = org.apache.mxnet.NDArray@f5e74790
```

I will be creating PR soon to address this.

**Comment by lupesko** [comment]
Looks good - thanks for picking this up!

@nswamy please apply label:
- Triaged
- Enhancement

**Comment by parallelgithub** [comment]
We added dependency in **sbt.built**
`"org.apache.mxnet" % "mxnet-parent_2.11" % "1.0.1-SNAPSHOT"`
as **pom.xml** or
add
`"org.apache.mxnet" % "mxnet-core_2.10" % "0.1.1"`
as **README.md** for Scala/Java,
but we got _unresolved dependency_ error.
How do we use the new version package ?

**Comment by lanking520** [comment]
Have you still faced the same issue?

**Comment by nswamy** [comment]
This is all fixed now.
