### ISSUE TITLE
repeat run constructor function of SymbolBlock when using gluon interface

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#9319]
## Description
when convert `mx.sym.##op##()` to `SymbolBlock` and run forward() during training, i found it will repeat call the constructor function, so if we Initialize some variable in the constructor() and change it in forward(), then it will be wrong because every time after it changed, it will be Initialized again.

give an example here: 
https://github.com/luoyetx/mx-lsoftmax/blob/master/operator/lsoftmax-inl.h#L54-L70

`next_beta_` will be assign as `param.beta * 0.1f` every time before forward(), so we'll never go into https://github.com/luoyetx/mx-lsoftmax/blob/master/operator/lsoftmax-inl.h#L178  

when using no gluon interface(original mxnet symbolic interface), it works well, but if we changed to gluon(SymbolBlock), then no work.

## Environment info (Required)

python
ubuntu16.04
mxnet-v1.0.1

@piiswrong  @sxjscience

**Comment by piiswrong** [comment]
Operators was never designed to store persistent states. They should be stored as parameter or auxiliary states.

**Comment by sandeep-krishnamurthy** [comment]
@tornadomeet - Are your concerns addressed? Can this issue be closed?

**Comment by tornadomeet** [comment]
yes, this is not solved.
