### ISSUE TITLE
Example blog post: Deep learning for multivariate time series forecasting.

### ISSUE THREAD

**Issue by opringle** [apache/incubator-mxnet#9326]
Hey guys.  Checkout my blog post, implementing a state of the art multivariate time series model in MXNet.   Feel free to add it to the examples.

https://opringle.github.io/2018/01/05/deep_learning_multivariate_ts.html

**Comment by piiswrong** [comment]
Would you like to propose a PR?

**Comment by opringle** [comment]
Sure.  I'll submit one this week.

**Comment by lupesko** [comment]
Thanks for the contribution @opringle !

@sandeep-krishnamurthy kindly label as "Example" and close the issue.

**Comment by kavnish** [comment]
Can someone help me to know, how can I use LSTNet trained model for future forecasting?
Thanks!
