### ISSUE TITLE
Row wise normalization of tensor

### ISSUE THREAD

**Issue by rayjs** [apache/incubator-mxnet#9328]
Hi,
I am new to mshadow. I am seeking some help regarding a tensor operation. I see there are examples to implement elementwise tensor operations as below:
https://github.com/dmlc/mshadow/tree/3d87ed2a4b47ef749c616f208cee45d920fb6e6e/guide#user-defined-operator

But I am looking for slightly different that is, row wise normalization of a tensor
A= [row1; row2;... rowN]; Anormalized = [row1/norm(row1); ....; rowN/norm(rowN)];
norm refers to the 2-norm.
This can be also thought of as reduction and then broadcast along the rows of the tensor.
I want to have an function like Tensor out = dot(A,B);
Is there any implementation or any pointer would be helpful?

**Comment by tornadomeet** [comment]
```mx.nd.L2Normalization(data)```

**Comment by sxjscience** [comment]
I close the issue here because it's mainly related to MShadow instead of MXNet. Also, we no longer use MShadow to implement the new operators. Only some legacy implementations use MShadow and will be refactored in the future.
