### ISSUE TITLE
fcn-xs  for mutil GPU

### ISSUE THREAD

**Issue by Kenneth-X** [apache/incubator-mxnet#9344]
i follow the code:
_python -u fcn_xs.py --model=fcn32s --prefix=VGG_FC_ILSVRC_16_layers --epoch=74 --init-type=vgg16_
and change:
_ctx = [mx.gpu(0),mx.gpu(1),mx.gpu(2),mx.gpu(3)]_  
in 'fcn_x.py' file
but i get the error:

 **File "/data-sdc/tao.xie/mxnet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:50:42] include/mxnet/./base.h:341: Invalid context string [gpu(0), gpu(1), gpu(2),gpu(3)]**

then i debug it and find:  
in 'init_fcnxs.py' file the function' init_from_vgg16'

def init_from_vgg16(ctx, fcnxs_symbol, vgg16fc_args, vgg16fc_auxs):
    fcnxs_args = vgg16fc_args.copy()
    fcnxs_auxs = vgg16fc_auxs.copy()
    for k,v in fcnxs_args.items():
    if(v.context != ctx):
    **fcnxs_args[k] = mx.nd.zeros(v.shape, ctx)**

it gets error in 'mx.nd.zeros(v.shape, ctx)', in which 'ctx = [mx.gpu(0),mx.gpu(1),mx.gpu(2),mx.gpu(3)] '

it seems the ctx is Invalid ................

how can i change it to train using mutil gpu? 
need help，please

**Comment by mli** [comment]
I think fcn-xs doesn't support multiple GPUs for now, because of the input data are not well aligned within a batch. 

There is a tutorial (in chinese) shown how to fix it: http://zh.gluon.ai/chapter_computer-vision/fcn.html

**Comment by sandeep-krishnamurthy** [comment]
@Kenneth-X Please reopen if the solution suggested by Mu is not working for your use case.

**Comment by kebinpeng** [comment]
@mli what you said is on gluon,however I am using symbol. could you please help me solve this problem? thanks a lot
