### ISSUE TITLE
I found it is hard to insert a node in mxnet graph.

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#9347]
(Not Gluon) For example, if I want to insert a convolution node into VGG-16, I need to directly modify the symbol.json.

**Comment by KeyKy** [comment]
is there any tools for converting symbol.json into symbol.py

**Comment by edmBernard** [comment]
can't you: 
- load json in python
- add your layer
- save the model in symbol.json

I don't know if the second part is possible.

**Comment by KeyKy** [comment]
@edmBernard it needs the meaning of node_row_ptr.

**Comment by Godricly** [comment]
What's the trouble in modifying symbol script? It should be ok.

**Comment by KeyKy** [comment]
@Godricly Yes, i am writing a tool to convert .json into symbol.py.

**Comment by BenBBear** [comment]
it's better to define the json format with protocol buffer, sadly mxnet didn't do that.
