### ISSUE TITLE
resize image in GPU for better performance?

### ISSUE THREAD

**Issue by nicklhy** [apache/incubator-mxnet#9354]
Hi, I got a problem when pre-processing a large image dataset. The image resize operation consumes too much CPU resource in opencv (or mxnet.image.imresize). Is it possible to resize an image in GPU with mxnet?
  
PS: I noticed the `mxnet.symbol.BilinearSampler` operator and not sure if it is what I am looking for.

**Comment by sxjscience** [comment]
Yes, you can combine BilinearSampler and GridGenerator (http://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.GridGenerator) to resize the image.

**Comment by nicklhy** [comment]
Thank you. BilinearSampler is totally what I am looking for!
