### ISSUE TITLE
can group2ctx be used in multi-machine model parallel situation?

### ISSUE THREAD

**Issue by quietsmile** [apache/incubator-mxnet#9357]
I have figured out how to split a layer into 8 gpus by using group2ctx which is a very great feature. I wonder if group2ctx can support to split a layer into multi-machines (eg. 16 gpus on two machine) by doing some easy modifications?

Thanks. @tqchen @piiswrong @mli

**Comment by eric-haibin-lin** [comment]
No model parallel across multi-machines is not supported as of now.

**Comment by lupesko** [comment]
@quietsmile going forward please file questions like this in [discuss.mxnet.io](https://discuss.mxnet.io). GitHub issues are for reporting bugs, feature requests, performance issues, etc.

@sandeep-krishnamurthy kindly asking to label as "Question" and close.
