### ISSUE TITLE
Does gluon's dnn support data format of libsvm other than mxnet's?

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#9359]
The data consists of lines like the following:

-1 4:1 6:1 15:1 21:1 35:1 40:1 57:1 63:1 67:1 73:1 74:1 77:1 80:1 83:1 \n

**Comment by ankkhedia** [comment]
@janelu9  we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels

Question
Gluon
and close the issue.
@janelu9  if done in error please reopen and comment

**Comment by janelu9** [comment]
I think I can use embedding
