### ISSUE TITLE
Incorrect weight_decay implementation in AdaGrad

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9363]
In Adagrad, weight_decay should be applied to grad before clipping the gradient/updating the state/weight. 

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer.py#L856-L858

Also adadelta: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer.py#L982

**Comment by ZiyueHuang** [comment]
wd term is also not merged into grad in SGD. Should we fix them? Will it cause some problems for backward compatibility?
cc @sxjscience

**Comment by sxjscience** [comment]
For SGD, not merging in the wd term will linearly scale the “real” wd and the impact is smaller compared to Adagrad. However, the change may break lots of our current examples and I’m not sure whether to revise it or not. We need to investigate how the other packages implement the WD term.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sxjscience** [comment]
Closed by the PR. Is the AdaDelta solved?

**Comment by eric-haibin-lin** [comment]
No, the change was reverted in the PR. My PR only contains a sparse op with Wd == 0

**Comment by sxjscience** [comment]
OK, we need to reopen it then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
