### ISSUE TITLE
MultiBoxTarget +1 to label automatically is so strange ...

### ISSUE THREAD

**Issue by jiarenyf** [apache/incubator-mxnet#9368]
I wonder in https://github.com/apache/incubator-mxnet/blob/492a5fde03418ae31b64d9866ca6a7a5c72388d3/src/operator/contrib/multibox_target.cc#L259, why plus 1 to the target clsID in the code ? Shouldn't we manually add 1 when preparing label (assume 0 is for background) ? Why the code does this job automatically ?
So we should set the positive label start from 0 when preparing data, and then when calculating class_loss, we should manually add 1 to label before making loss with the target_cls for the above link ? It is so strange ...

Thanks for your help ...

**Comment by adlong01** [comment]
Could you elaborate on how you solved this? I'm guessing this is so non-mined elements of the background can remain as -1 while other elements contribute to the loss.
