### ISSUE TITLE
Compile Error: /usr/bin/ld: cannot find -lcuda

### ISSUE THREAD

**Issue by lxwgcool** [apache/incubator-mxnet#9372]
## Description
I try to compile mxnet from source code and get the error below: 
/usr/bin/ld: cannot find -lcuda
Even i try to reset the path of CUDA (such as "USE_CUDA_PATH=/apps2/cuda/8.0.61"), however, the compiler keep finding CUDA in the system folder.

## Environment info (Required)
Red Hat Enterprise Linux Workstation release 6.7 (Santiago)

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
gcc 4.8.2

## Error Message:
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/make: usr*** [bin/im2rec] Error 1/
bin/ld: cannot find -lcuda
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1

## What have you tried to solve it?

1. Add following two lines into all config.mk files 
ADD_LDFLAGS=-L/apps2/cuda/8.0.61/lib64
ADD_CFLAGS=-I/apps2/cuda/8.0.61/include

The command line i use to compile as below:
make -j 10 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/apps2/cuda/8.0.61

Here is one thing need to be mentioned: CUDA doesn't be installed in the default system path. We installed CUDA in the customized directory. 

Please help me to solve this problem. 
Thank you so much

**Comment by sxjscience** [comment]
You may try to change the USE_CUDA_PATH flag manually in the config.mk file (https://github.com/apache/incubator-mxnet/blob/master/make/config.mk#L55) to have a try

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy Tag this - Build. And please close the issue.

@lxwgcool reopen the issue if the problem persists.
