### ISSUE TITLE
Does Nvidia have a kind of cuda driver to install for the machine without GPU?

### ISSUE THREAD

**Issue by guotong1988** [apache/incubator-mxnet#9375]
So after installing the cuda driver on the NO-GPU machine, we can debug on it in GPU-mode, which is the same as a machine with GPU~
Sorry to trouble you and thank you very much~

**Comment by szha** [comment]
https://stackoverflow.com/questions/3087361/gpu-emulator-for-cuda-programming-without-the-hardware

**Comment by lupesko** [comment]
@guotong1988 going forward please use the [MXNet Discuss Forum](https://discuss.mxnet.io/) for questions.

**Comment by lupesko** [comment]
@szha can you please apply label "Question" and close?
Thanks!

**Comment by szha** [comment]
@guotong1988 closing now. Do let us know if you need any other help. Also, you may want to check out https://discuss.gluon.ai/

**Comment by guotong1988** [comment]
Thank you all. Your response is the best in all the DL frameworks community.
