### ISSUE TITLE
Init bias term in every layer

### ISSUE THREAD

**Issue by ly-atdawn** [apache/incubator-mxnet#9376]
In mxnet, the bias term in a layer is default inited with 0., if I want to init bias term to 0.1, how could I do?
I tried some ways, for example:
init_patterns = ['.*', 'bias'] # init pattern. bias init wrong, always is 0.
init_methods = [mx.initializer.Xavier(rnd_type="uniform", factor_type="avg", magnitude=1.0), 
    mx.initializer.Constant(value=0.1)]
 initializer = mx.initializer.Mixed(init_patterns, init_methods)
But, bias term in layer is still 0., What can I do to implement the goal?
Thanks. Help a lot

**Comment by lupesko** [comment]
Hi @ly-atdawn 
You'll need to use a custom initializer, see more details [here](https://mxnet.incubator.apache.org/api/python/optimization.html#mxnet.initializer.register).

Going forward, for questions like this or follow up questions please use the [MXNet Discuss Forum](https://discuss.mxnet.io/).

**Comment by lupesko** [comment]
@nswamy please apply label:
- Python
- Question

And close the issue. Thanks!

**Comment by ly-atdawn** [comment]
Thanks

**Comment by ly-atdawn** [comment]
I want to set like this:
weight init like: mx.initializer.Xavier(rnd_type="uniform", factor_type="avg", magnitude=1.0)
bias init like: 
@mx.init.register
    # @alias('myinit')
    class CustomInit(mx.init.Initializer):
        def __init__(self):
            super(CustomInit, self).__init__()
        def _init_weight(self, _, arr):
            pass
            # arr[:] = 0.1
        def _init_bias(self, _, arr):
            arr[:] = 0.1

How can implement this? Help a lot
