### ISSUE TITLE
Error: Can't find 'R-package' during the installation

### ISSUE THREAD

**Issue by imamdigmi** [apache/incubator-mxnet#9377]
## Description
Hi! I'm trying to install MXNet following [this guide](http://mxnet.incubator.apache.org/get_started/install.html) on Ubuntu 16.04 for R with GPU but have some problem here, it cant find R-Package, so I'm trying to googling how to install R-Package but i'm cant find that package.

## Environment info
I'm using R
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8              LC_NUMERIC=C              
 [3] LC_TIME=id_ID.UTF-8                    LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=id_ID.UTF-8         LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=id_ID.UTF-8                 LC_NAME=C                 
 [9] LC_ADDRESS=C                             LC_TELEPHONE=C            
[11] LC_MEASUREMENT=id_ID.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.4

loaded via a namespace (and not attached):
[1] withr_2.1.1   memoise_1.1.0 digest_0.6.13
```

## Build info
Compiler gcc

MXNet commit hash:
a5edbf94094581ee27157eae4f2113115a3994e7

## Error Message:
```
Error: Can't find 'R-package'.
Execution halted
Makefile:384: recipe for target 'rpkg' failed
make: *** [rpkg] Error 1
```

## I have tried to solve with
1. Install R-Package to build package in R but i cant find that package
2. I comment out installation of R-package but i get another errors like ```Warning: invalid package ‘R-package’
Error: ERROR: no packages specified
Makefile:481: recipe for target 'rpkg' failed
make: *** [rpkg] Error 1```

How to solve this and what should i do, thanks in adnvace.

**Comment by lupesko** [comment]
@imamdigmi to help us help you, can you please list all the steps you followed as you were building the package?
(Linux/R requires you to build from source...)

Thanks!

**Comment by lupesko** [comment]
@nswamy can you please apply the labels:
- R
- Linux
- Pending Requester Info

**Comment by imamdigmi** [comment]
Yap! @lupesko here are the steps I took :
1.`git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet --branch 0.11.0 && cd mxnet`
2. `sudo apt-get install -y libopenblas-dev liblapack-dev`
3. `make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`
4. `make rpkg`

and i got the error.

**Comment by jeremiedb** [comment]
Have you tried to install the current release rather than 0.11.0? I'd recommend using latest release, though it requires R >=3.3.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please add the labels -
R
Linux
Pending Requester Info
Triaged

**Comment by anirudhacharya** [comment]
Issue not reproducible. I am able to install R on ubuntu.

@sandeep-krishnamurthy @cjolivier01 please close the issue.
