### ISSUE TITLE
Official version of pretrained MobileNet/ShuffleNet/NASNet is available?

### ISSUE THREAD

**Issue by seyoungleecho** [apache/incubator-mxnet#9388]
I working on semantic segmentation using efficient/low memory consumption architectures.
Is any pretrained models MobileNet/ShuffleNet/NASNet trained on ImageNet data is available?
KIndly help since SqueezeNet results for semantic segmentation is not promising......because SqueezeNet accuracy itself is low.....

**Comment by seyoungleecho** [comment]
@szha , any updated on pretrained models in #9215.

**Comment by szha** [comment]
Yes, it's available now in the master branch and you can start using it. It will also be included in the next release.

**Comment by chowkamlee81** [comment]
thanks szha, closing the issue...

**Comment by lupesko** [comment]
@seyoungleecho going forward please use the [MXNet Discuss Forum](https://discuss.mxnet.io/) for questions.
@szha can you please close this issue?

Thanks!

**Comment by szha** [comment]
@jmnie it's included in the latest versions of mxnet.
```
from mxnet import gluon
net = gluon.model_zoo.vision.resnet50_v1(pretrained=True)
```
