### ISSUE TITLE
How to view the network with only model.params without having .json file?

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#9391]
I had a model file mobilenet-1.0-0000.params but doesn't have .json file. 
I would like to view/visualize the network in jpg/png files. Is there is any possibility to view the model? Kindly help

**Comment by shuokay** [comment]
No, params file is a dict like file, no symbol info in it

**Comment by sxjscience** [comment]
Yes, the `.params` just stores some NDArrays and do not define the computation logic.
