### ISSUE TITLE
Official version of MobileNet pretrained model and .json file

### ISSUE THREAD

**Issue by chowkamlee81** [apache/incubator-mxnet#9392]
Recently i found MobileNet gluon version of model.param.

I would like to have symbolic version of mobileNet in model.param and also .json format file.
Is anything are avilable in modelzoo with json and mobilenet.param file. 
Kindly reply...
@szha do you any updates on this....

**Comment by szha** [comment]
Gluon model zoo has it in master branch now, which you can use to generate the json and param
```python
mx.gluon.model_zoo.vision.mobilenet1_0(pretrained=True).export('mobilenet1_0')
```

**Comment by chowkamlee81** [comment]
Hi szha, model has been downloaded . But while exporting to .json and .param files throws an error ""Please first call block.hybridize() and then run forward with "
                "this block at least once before calling export."

Kindly help to resolve the issue as it thrown an exception in mxnet/gluon/block.py below code

    def export(self, path, epoch=0):
        """Export HybridBlock to json format that can be loaded by `mxnet.mod.Module`
        or the C++ interface.

        .. note:: When there are only one input, it will have name `data`. When there
                  Are more than one inputs, they will be named as `data0`, `data1`, etc.

        Parameters
        ----------
        path : str
            Path to save model. Two files `path-symbol.json` and `path-xxxx.params`
            will be created, where xxxx is the 4 digits epoch number.
        epoch : int
            Epoch number of saved model.
        """
        if not self._cached_graph:
            raise RuntimeError(
                "Please first call block.hybridize() and then run forward with "
                "this block at least once before calling export.")

**Comment by chowkamlee81** [comment]
@szha , model has been downloaded . But while exporting to .json and .param files throws an error ""Please first call block.hybridize() and then run forward with "
"this block at least once before calling export."

Kindly help to resolve the issue as it thrown an exception in mxnet/gluon/block.py below code

def export(self, path, epoch=0):
    """Export HybridBlock to json format that can be loaded by `mxnet.mod.Module`
    or the C++ interface.

    .. note:: When there are only one input, it will have name `data`. When there
              Are more than one inputs, they will be named as `data0`, `data1`, etc.

    Parameters
    ----------
    path : str
        Path to save model. Two files `path-symbol.json` and `path-xxxx.params`
        will be created, where xxxx is the 4 digits epoch number.
    epoch : int
        Epoch number of saved model.
    """
    if not self._cached_graph:
        raise RuntimeError(
            "Please first call block.hybridize() and then run forward with "
            "this block at least once before calling export.")

**Comment by szha** [comment]
Sorry, my bad.
```python
net = mx.gluon.model_zoo.vision.mobilenet1_0(pretrained=True)
net.hybridize()
net(mx.nd.ones((1,3,224,224)))
net.export('mobilenet1_0')
```

**Comment by chowkamlee81** [comment]
Got the one. Thanks its working... Closing the issue...

**Comment by kaivu1999** [comment]
> Sorry, my bad.
> 
> ```python
> net = mx.gluon.model_zoo.vision.mobilenet1_0(pretrained=True)
> net.hybridize()
> net(mx.nd.ones((1,3,224,224)))
> net.export('mobilenet1_0')
> ```

This works for me as well
but surprisingly 
```
>>> net.export("resnet18")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/gluon/block.py", line 885, in export
    "Please first call block.hybridize() and then run forward with "
RuntimeError: Please first call block.hybridize() and then run forward with this block at least once before calling export.
```

for 
```
net = models.resnet18_v1(pretrained=True)
net(mx.nd.ones((1,3,224,224)))
net.export("resnet18")
```
