### ISSUE TITLE
I encounter a problem in the process of running  example!

### ISSUE THREAD

**Issue by zhangguotai** [apache/incubator-mxnet#9393]
/home/root/Inception/Inception/caffenet-symbol.json ... 9015 bytes
/home/root/Inception/Inception/caffenet-0000.params ... 243861676 bytes
[14:05:34] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[14:05:34] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
terminate called after throwing an instance of 'cl::Error'
  what():  empty
Aborted
I should how to solve this probelm

**Comment by Roshrini** [comment]
@zhangguotai Can you provide more details on the issue. Please use provided format while creating the issue. It helps to reproduce and debug the error.

@sandeep-krishnamurthy Please add labels
- Pending Requester Info
- Python
- Example

**Comment by kalyc** [comment]
@zhangguotai were you able to resolve the issue? Could you please close the issue if it was resolved?

**Comment by piyushghai** [comment]
@zhangguotai Can you provide an update here ? 

Thanks!

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.
