### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by limky83** [apache/incubator-mxnet#9395]
Tried running a python program that imports the following:
import os
import sys
import tensorflow as tf
import skimage.io as io
import numpy as np

and the error "No module named 'skimage'" shows.

I am using Python 3.6.4

## Error Message:
  File "C:/Python36/imgSegmentation2.py", line 8, in <module>
    import skimage.io as io
ModuleNotFoundError: No module named 'skimage'

## What have you tried to solve it?
1. I have tried pip install scikit-image and got the following error:

<a href="http://s1221.photobucket.com/user/kk_yin/media/error.jpg.html" target="_blank"><img src="http://i1221.photobucket.com/albums/dd476/kk_yin/error.jpg" border="0" alt=" photo error.jpg"/></a>

2. Already pip installed numpy

**Comment by sxjscience** [comment]
I feel that it's not related to MXNet as the code has `import skimage.io as io`. You need to install skimage (http://scikit-image.org/docs/dev/install.html)
