### ISSUE TITLE
[Perl] Rare segfault in rnn gluon test

### ISSUE THREAD

**Issue by sergeykolychev** [apache/incubator-mxnet#9415]

**Comment by anirudhacharya** [comment]
@sergeykolychev can you elaborate more on this failure? can you share any error log you might have? Does this issue persist even after merging this PR - https://github.com/apache/incubator-mxnet/pull/9414

**Comment by sergeykolychev** [comment]
@anirudhacharya thanks for the report, I'll check it out in next few days

**Comment by anirudhacharya** [comment]
I have not been able to reproduce this issue even after running the test for ~10k times. 

@sergeykolychev is this something you are actively looking into? are you okay with closing this issue? from the past many CI runs, I don't think this is failing anymore.

**Comment by sergeykolychev** [comment]
@anirudhacharya go ahead and close the issue. thanks!
