### ISSUE TITLE
how to add 'SpatialTransformer' in gluon api?

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#9421]
`mx.sym.SpatialTransformer` and `mx.nd.SpatialTransformer` already exist, but not exist in gluon interface.  

in pytorch, you can use `affine_grid`(http://pytorch.org/docs/master/nn.html#torch.nn.functional.affine_grid) and `grid_sample`(http://pytorch.org/docs/master/nn.html#torch.nn.functional.grid_sample) to implement stn, but it is in `torch.nn.functional` ,  so where shold this add in gluon, `gluon/basic_layers.py` or somewhere else?

@szha @piiswrong

**Comment by szha** [comment]
I think gluon basic layers is fine. If you expect the interface design to iterate, then the safest bet would be gluon.contrib.

**Comment by lupesko** [comment]
@tornadomeet please use [MXNet Discuss Forum](https://discuss.mxnet.io/) for such questions going forward.

@szha can you please close the issue?

Thanks!

**Comment by szha** [comment]
@lupesko I think github issue is an appropriate place to discuss about feature requests and designs, would you agree?

**Comment by spidyDev** [comment]
@lupesko I agree  with @szha  , for new feature requests github might be a good place to start the discussion.

 @sandeep-krishnamurthy  Please close this issue, as the requester's question was answered.
