### ISSUE TITLE
How to provide std::vector<float> of parameters to operator layer

### ISSUE THREAD

**Issue by rayjs** [apache/incubator-mxnet#9429]
Hi I want to provide a float and an int vector as parameter to my operator. I have the following definition but I get compilation error. To get around this instead of `std::vector<int>`, I use `Tshape`, which works fine but for `float` it is not possible because `Tshape` accepts `int`.

Please help.

```
struct DummyParam : public dmlc::Parameter<DummyParam>
{
    std::vector<float> vfloat;
   std::vector<int> vint;
    DMLC_DECLARE_PARAMETER(DummyParam)
    {
        DMLC_DECLARE_FIELD(vint).describe("Entries of vint vector");
        DMLC_DECLARE_FIELD(vfloat).describe("Entries of vfloat vector");
    }
};
```
Thank you

**Comment by sxjscience** [comment]
@rayjs You can try to use `nnvm::Tuple<float>` instead

**Comment by rayjs** [comment]
Thank you so much :)
