### ISSUE TITLE
Can sequential module be distributed into mulit machines and how?

### ISSUE THREAD

**Issue by quietsmile** [apache/incubator-mxnet#9449]
Can sequential module be distributed into multi machines and how?
@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
I'm afraid not yet. What's your use case and why are you considering it?

**Comment by spidyDev** [comment]
@quietsmile   Hope you got answer to your question. For further queries , you can use https://discuss.mxnet.io/.

@sandeep-krishnamurthy  Please close this issue.
