### ISSUE TITLE
imread read blank (None) image for file: *.jpg

### ISSUE THREAD

**Issue by prateekagarwal3** [apache/incubator-mxnet#9450]
The image does exist but I am getting an error when I am trying to use im2rec.py, I get this error.

**Comment by roywei** [comment]
Hi @prateekagarwal3 , could you provide more details for us to reproduce the error
Please follow this [template](https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md)
@sandeep-krishnamurthy  please add label Pending Requester Info
Thanks!

**Comment by piyushghai** [comment]
@prateekagarwal3 Are you still facing the issue while using im2rec.py ?

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.
