### ISSUE TITLE
How to dynamically bind executor with variable symbol?

### ISSUE THREAD

**Issue by squidszyd** [apache/incubator-mxnet#9451]
During testing phase, my symbol's computing structure depends on some factor K. E.g, when the factor equals to K, then there are N(K) layers of Convolution operations, where N(K) changes with K.
Thus, I have to construct a new symbol and rebind it with an executor when K changes. Code may look like this:
```
if current_k != last_k:
    sym = get_symbol(current_k)
    mod = mx.mod.Module(sym, ...)
    mod.bind(...)
else:
    # keep the module unchanged
    pass
```
My question is, how to effectively release memory allocated by the bound module and rebind it with a different symbol?
I've tried using python's 'del' to delete the bound module, but the memory is not released when look into the info returned by 'nvidia-smi'.

**Comment by sandeep-krishnamurthy** [comment]
Hello @squidszyd, There is no explicit call to release the memory immediately. The memory allocated will be marked to release when the reference to the object is removed or marked with 'del' or when you 'force rebind' the module with new symbol.

Other alternative solution would be:
1. Using "reshape" if you want to change the shape of params and grad arrays already bound in the module.

Please reopen, if the issue persists.
