### ISSUE TITLE
A new deep learning visualization tool from baidu support MXNet!

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-mxnet#9452]
https://github.com/PaddlePaddle/VisualDL

**Comment by eric-haibin-lin** [comment]
@reminisce @zihaolucky

**Comment by reminisce** [comment]
@chinakook It looks easy-to-use, but still lacks many features supported in Tensorboard. Do you know how reliable this tool is? I have not been able to run their demo so far. It always complains
```
VisualDL$ visualDL --logdir=scratch_log --port=8080 --host=127.0.0.1
[INFO 2018-01-18 12:40:12,188 visualDL:230]  port=8080
[INFO 2018-01-18 12:40:12,191 _internal.py:88]  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
[INFO 2018-01-18 12:40:29,465 _internal.py:88] 127.0.0.1 - - [18/Jan/2018 12:40:29] "GET / HTTP/1.1" 302 -
[INFO 2018-01-18 12:40:29,476 _internal.py:88] 127.0.0.1 - - [18/Jan/2018 12:40:29] "GET /static/index.html HTTP/1.1" 404 -
```

**Comment by chinakook** [comment]
@reminisce I'will have a try!

**Comment by chinakook** [comment]
@reminisce It's normal in my PC. I've installed it from "pip install visualdl".

**Comment by reminisce** [comment]
@chinakook I built it from source. Can you try that and see if the demo works?

**Comment by reminisce** [comment]
@chinakook NVM, I did something wrong. I am able to run the demo from building the source code. Thanks for the recommendation.

**Comment by chinakook** [comment]
It was nothing, @reminisce

**Comment by roywei** [comment]
Thank you for your recommendation
@sandeep-krishnamurthy  please kindly add label Exploration, Discussion, and close this issue
Thanks
