### ISSUE TITLE
[R] CNN Memory Leak - Needs to somehow call Garbage Collector

### ISSUE THREAD

**Issue by some-guy1** [apache/incubator-mxnet#9453]
## Description
Memory constantly increases until out of memory of machine.  Using the following code.  The memory does not release even after Mxnet finishes requested iterations.  If I use the gc() command, all memory is released.  **How can I call gc() during Mxnet optimizing?**  Or is there a different work around?

Input is a 16x16x3 data set.  Should be fairly easy to solve.  

`train_iter = mx.io.arrayiter(data = train.x, label = train.y    )`
`data <- mx.symbol.Variable('data')`
`conv_1 <- mx.symbol.Convolution(data= data, kernel = c(2,2), num_filter = 30)`
`tanh_1 <- mx.symbol.Activation(data= conv_1, act_type = "tanh")`
`fcl_2 <- mx.symbol.FullyConnected(data = tanh_1, num_hidden = 256)`
`fcl_2 <- mx.symbol.reshape(fcl_2, shape=c(16,16,1,128))`
`NN_Model <- mx.symbol.LinearRegressionOutput(data=fcl_2, name="lro")`
`mx.set.seed(100)`

`conv.net.model <- mx.model.FeedForward.create(NN_Model, X=train_iter,`
`    ctx=mx.cpu(), num.round=150, array.batch.size=1,`
`    learning.rate=5e-4, array.layout = "rowmajor",`
`    eval.metric = mx.metric.mse, optimizer = "rmsprop",`
`    verbose = TRUE) `

MXnet R 0.10.1
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by jeremiedb** [comment]
Far from ideal, but as a dirty patch you can add a gc() call within the train.model function training loop here: 
https://github.com/apache/incubator-mxnet/blob/master/R-package/R/model.R#L221
This will require to essentially copy and call the entire model.R script since some function has dependencies on functions that aren't exported. 
It can be worthwile to add a condition such as if (nbatch %% 10) to avoid too many calls to gc() that may slowdown training.

**Comment by some-guy1** [comment]
Hmm, ok I will give that a try.  Thanks!

**Comment by some-guy1** [comment]
I attempted to copy the model.R and all dependencies, but I am stuck on the error shown below.  Seems that the missing function is embedded in c++ somewhere.  Not sure how to get around this. Is it possible to use this function without altering c++?  



 Error in mx.nd.slice(dlist$data, s$begin, s$end) : 
  could not find function "mx.nd.slice"

**Comment by jeremiedb** [comment]
No worry, mx.nd.slice is not an exported function (not sure why actually?), but is still accessible through mxnet:::mx.nd.slice. As a rule of thumb, if you have another missing function warning, you can likely solve it through mxnet:::<function_name>

**Comment by some-guy1** [comment]
Oh!! I had no idea you could that.  

Ok well I tried what you suggested and **problem solved!**  Every 10 iterations my memory drops back down to a sane level.
