### ISSUE TITLE
copy tensor from gpu to cpu

### ISSUE THREAD

**Issue by TX2012LH** [apache/incubator-mxnet#9454]
I want to copy a tensor from gpu to cpu and I did it as below. But it seems that the pointer `cpu_box1.dptr__` is disorderly after carrying on `Copy`. I wonder there is something wrong?
```
  virtual void Forward(const OpContext &ctx,
                       const std::vector<TBlob> &in_data,
                       const std::vector<OpReqType> &req,
                       const std::vector<TBlob> &out_data,
                       const std::vector<TBlob> &aux_args) {
    using namespace mshadow;
    CHECK_EQ(in_data.size(), 4U);
    CHECK_EQ(out_data.size(), 1U);
    Stream<xpu> *s = ctx.get_stream<xpu>();
    Tensor<xpu, 4, DType> data1 = in_data[roiconv::kData1].get<xpu, 4, DType>(s);
    Tensor<xpu, 2, DType> rois1 = in_data[roiconv::kRois1].get<xpu, 2, DType>(s);
    Tensor<xpu, 4, DType> out = out_data[roiconv::kOut].get<xpu, 4, DType>(s);
    out = 0.0f;
    Tensor<cpu, 2, DType> cpu_box1 = NewTensor<cpu, DType>(rois1.shape_, 0.0f);
    mshadow::Copy(cpu_box1, rois1, s);
    ...
}
```
### env
mxnet v0.12
cuda-8.0
ubuntu 16.04

**Comment by piiswrong** [comment]
NewTensor doesn't actually allocate memory.
You need to use `new` to allocate memory yourself

**Comment by TX2012LH** [comment]
I found that it worked  after I took value of tensor via `cpu_box1[i][j]` instead of pointer. The memory of tensor is not continuous.

**Comment by ankkhedia** [comment]
@TX2012LH  we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels

- Question
- C++
and close the issue.
@TX2012LH  if done in error please reopen and comment
