### ISSUE TITLE
Package actualization mxnetR for windows

### ISSUE THREAD

**Issue by RogerBorras** [apache/incubator-mxnet#9465]
Hi,

It is possible to provide an actualization for mxnetR in windows to version 1.0? @thirdwing?

Thanks!

**Comment by thirdwing** [comment]
I am afraid I need to finish my thesis first. This is my highest priority.

**Comment by RogerBorras** [comment]
Ok, good luck with your thesis!

**Comment by vdantu** [comment]
@RogerBorras : Could you be a little more precise on what you want? Also, if this is a generic question you could start a discussion at https://discuss.mxnet.io/

@sandeep-krishnamurthy : please label this "question" and this can be closed.
