### ISSUE TITLE
how to release gpu memory in the garbage pool?

### ISSUE THREAD

**Issue by weishy-xun** [apache/incubator-mxnet#9474]
As I can see,  there're a lot of issues about gpu memory leaking, and always end with something like:

> Memory isn't really 'leaked'. It's released to a pool. The pool will only be emptied when an allocation returns out of memory.

However, when I use multiprocessing,  it is really painful,  because the "pool" isn't share between process. E.g. I have 4 processes, one ocuupied 11g, when another process get "out of memory", it cannot release the first process's garbage pool. And if I do not call the first process forever, the garbage will be there forever. Is there any method to release memory manually? Or can I set a memory limitation for a process?

**Comment by weishy-xun** [comment]
Not sure if I need open another issue for code below,  showing the gpu leaking problem I met with. 


import mxnet as mx
import numpy as np
a = mx.nd.zeros((500,500,3), ctx=mx.gpu(0))
b = mx.nd.ones((500,500,3), ctx=mx.gpu(0))
for i in range(100000):
    rs1 = np.random.randint(1, 480)
    rs2 = np.random.randint(1, 480)
    a[10:10+rs1,10:10+rs2] = b[20:20+rs1, 10:10+rs2]

**Comment by piiswrong** [comment]
You can set MXNET_GPU_MEM_POOL_RESERVE to a big number (like 80, 90 or 95) to force mxnet to release memory eagerly. But this may have significant negative impact on speed.

See https://mxnet.incubator.apache.org/how_to/env_var.html

**Comment by lupesko** [comment]
@weishy-xun - did the suggestion above to use `MXNET_GPU_MEM_POOL_RESERVE` help with the issue?
Since there was no response in over a month I think it is best to close the issue, feel free to re-open if you think it is done in error.

@sandeep-krishnamurthy kindly close the issue and label as "CUDA" (asking for a new label)
