### ISSUE TITLE
OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file /home/travis/build/dmlc/mxnet-distro/deps/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 4944 terminate called after throwing an instance of 'cv::Exception'

### ISSUE THREAD

**Issue by xuzhenqi** [apache/incubator-mxnet#9475]
When I use augmentation of aspect, random scale, rotate, mxnet report this error:
```
OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file /home/travis/build/dmlc/mxnet-distro/deps/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 4944 terminate called after throwing an instance of 'cv::Exception'
```

I install the mxnet by
```
pip install  mxnet-cu80==1.0.1b20180105
```

I think mxnet should catch opencv Exceptions rather than terminating the process.

**Comment by lupesko** [comment]
@xuzhenqi can you please provide more context and details about the issue?
- Use the latest release of mxnet by `$ pip install mxnet-cu90 --upgrade` 
  (latest version is 1.1.0)
- Provide code that reproduces the issue
- Run diagnostic and attach output to provide more context on your setup: `$ python ./tools/diagnose.py`

**Comment by lupesko** [comment]
@sandeep-krishnamurthy please apply the label `Exception Handling`
Thanks!

**Comment by sandeep-krishnamurthy** [comment]
@anirudh2290 - Your recent work on exception handling, covers this usecase?

**Comment by anirudh2290** [comment]
Currently, MXNet only catches dmlc::Error and for other exceptions the process is terminated. Catching exception from dependent libraries will require more work, as it requires changing the c api guard code and the exception mapping and testing for different front-ends.

**Comment by anirudh2290** [comment]
@sandeep-krishnamurthy Please also tag as "Bug" for the crash.
