### ISSUE TITLE
Creating a symbol variable from a numpy array

### ISSUE THREAD

**Issue by opringle** [apache/incubator-mxnet#9483]
Hi guys.

- I would like to create a symbol that represents a predefined weight matrix (for use in my loss function).  
- So far I have created a symbol variable, defined it's shape and then initialized it.
- However, I cannot work out how to initialize it with anything other than random numbers, zeros or ones.  Is it possible to initialize with a numpy array?

`weights = mx.sym.Variable('weights', shape = (config.batch_size, num_labels, seq_len), init = mx.init.One())`

- I think `mxnet.initializer.Load()` is what I need but I cannot see how to pass an array to that function.

**Comment by piiswrong** [comment]
You can use set_params after initialization.

**Comment by roywei** [comment]
Please ask questions via the [Discuss Forum](https://discuss.mxnet.io/), not via issues.
@sandeep-krishnamurthy  please kindly add label Question  and close this issue.

@opringle please let us know if you still have question
Thanks!
