### ISSUE TITLE
image segmentation iterator

### ISSUE THREAD

**Issue by gaosanyuan** [apache/incubator-mxnet#9488]
I now do image segmentation task based on money framework.
I have implemented a data iter for this task, but it is a little slow for large images, I would like to know if any SegIter(based on gnu) is available, thanks

**Comment by spidyDev** [comment]
@gaosanyuan  Please file your question on https://discuss.mxnet.io/ and it would be great if you could add more details about your issue.

@sandeep-krishnamurthy
