### ISSUE TITLE
Unable to install mxnet on MacOS .. no version seemingly compatible with Python3

### ISSUE THREAD

**Issue by pabramowitsch** [apache/incubator-mxnet#9490]
I just want to play with mxnet using prebuilt code on MacOS but the pip install fails.  Following the instructions on the Apache MXNET pages,  My command line is

 **python3 -m pip -vvv install mxnet=='0.11.0'** 

but I can get the same error with the latest version. (I also get the same message using the default python & pip which are 2.6.4)   

I get a bunch of lines like this:
```
Skipping link https://pypi.python.org/packages/b8/4a/01cbb5ba05aef7721293be2de348e8ad648be9d39636d6aac6428ae22b34/mxnet-1.0.0b20171218-cp36-cp36m-macosx_10_12_x86_64.whl#md5=db310aa94547e59b2d5fc491ef63787d (from https://pypi.python.org/simple/mxnet/); it is not compatible with this Python`
. . .
Cleaning up...  No matching distribution found for mxnet==0.11.0
```
I'm pretty sure that pip3 isn't referring to python 2.x in this process because my verbose output contains t
```
Exception information:  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
```
And I can see a version to install because doing **pip3 search mxnet**  I get
`mxnet (1.0.1b20180118)          - MXNet is an ultra-scalable deep learning framework. This version uses openblas.`

ENVIRONMENT
```
brew formula python3 3.6.4_2
_system_arch=x86_64
_system_info='Darwin XXXXX 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64'
_system_name=OSX
_system_name_lowercase=osx
_system_type=Darwin
_system_version=10.9
PATH=/usr/local/opt/python3/bin:/usr/local/bin:/usr/local/bin:/.... etc
Python 3.6.4
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```

**Comment by szha** [comment]
Do you need to use 0.11.0 specifically, or would you be fine with trying more recent versions? In the later case you may try simply `pip install mxnet`

**Comment by pabramowitsch** [comment]
Thanks szha!  Yes, I've tried not specifying any version as you indicated, or tried specifying the latest version, but the errors are the same.  Basically pip lists every version in the repo and declares that my python (python3) is incompatible with it.  So clearly the error must be somewhere else.. but where?  As I have python 2.7 also on the machine, I invoke pip through python3. 
 
**>python3 -m pip install mxnet**

here's the full output.

[err.txt](https://github.com/apache/incubator-mxnet/files/1647429/err.txt)

**Comment by szha** [comment]
Hi @pabramowitsch. I just realized that your kernel version 13.4.0 indicates you're using OSX 10.9 Mavericks. Our pip package for OSX current only supports 10.10-10.12, due to the limitation in build.

**Comment by pabramowitsch** [comment]
Thank you.   I was wondering about that, but as python3 itself didn't complain about the OS, I assumed the pip install would work.  I've been stalling on upgrading this machine as it has so much running development software on it.  Can you point me to another way to install a version of mxnet on 10.9 just for learning purposes?

**Comment by aaronmarkham** [comment]
Hi @pabramowitsch, would you mind closing this?

**Comment by szha** [comment]
I can close this. @pabramowitsch let me know if you have more questions and I can re-open this issue upon your request.
