### ISSUE TITLE
LSTM doesn't work with Symbols and HybridBlocks

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [apache/incubator-mxnet#9501]
I want to use LSTM with AWS SageMaker, but I am having [problems with Symbols](https://github.com/aws/sagemaker-python-sdk/issues/51). I noticed that LSTM seems to make not attempt at using the HybridBlock pattern. For [example](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/rnn/rnn_layer.py#L173), it only defines a forward method that inherently can't be used with Symbols,

```python
    def forward(self, inputs, states=None):
        batch_size = inputs.shape[self._layout.find('N')]
        skip_states = states is None
        if skip_states:
```

Before I go about trying to fix this, I wanted to check if there were known issues, plans to fix it, or existing work done to fix this. Has any effort been made on this?

**Comment by leezu** [comment]
LSTM doesn't support HybridBlock yet. If you just wish to build a simple LSTM you can directly use the [LSTMCell](https://mxnet.incubator.apache.org/api/python/gluon.html#mxnet.gluon.rnn.LSTMCell) which can be hybridized.

**Comment by jesterhazy** [comment]
@aidan-plenert-macdonald you could try:

- training your model
- saving the weights with `net.save_params(path, epoch)`
- recreating the model in python code (instead of trying to loading symbols)
- loading the trained weights with `net.load_params(path, ...)`

this should work for (non-hybrid) gluon models generally, not just LSTM.

**Comment by kenfehling** [comment]
I have a question about its performance. The documentation says:

> Recurrent cells allows fine-grained control when defining recurrent models. User can explicit step and unroll to construct complex networks. It provides more flexibility **but is slower** than recurrent layers.

So LSTMCell is slower than LSTM, but I'm wondering if hybridized then it's faster?

**Comment by szha** [comment]
Our LSTM cell doesn't support full sequence hybridization yet. The hybridization happens only at cell level. Thus, it will still have performance penalty.

**Comment by kenfehling** [comment]
OK, thanks!
