### ISSUE TITLE
SphereFace

### ISSUE THREAD

**Issue by taylover-pei** [apache/incubator-mxnet#9509]
Is there someone who has complete the A-Softmax Loss(SphereFace) code with MxNet?

**Comment by ShownX** [comment]
https://github.com/HaoLiuHust/sphereface_mxnet_gluon

**Comment by roywei** [comment]
please refer: https://github.com/Johnson-yue/sphereface_mxnet_gluon
Also please raise questions on [Discussion Forums](https://discuss.mxnet.io) instead of issue
Closing this issue.
Thanks
@sandeep-krishnamurthy please add Label Question, and close this issue.
