### ISSUE TITLE
get the names of different outputs of the same layer

### ISSUE THREAD

**Issue by gaosanyuan** [apache/incubator-mxnet#9513]
When a layer has more than one output, how to get the names of different outputs?
For example, a custom layer outputs two symbols, when using get_internal(), they usually have the same name.

**Comment by sxjscience** [comment]
For the custom layers, the name of the outputs are controlled by `list_outputs()`. See https://mxnet.incubator.apache.org/how_to/new_op.html

**Comment by anirudhacharya** [comment]
@gaosanyuan please ask this question in the discussion forum here - https://discuss.mxnet.io/

@sandeep-krishnamurthy please add the label - Question and close this issue.
