### ISSUE TITLE
How to convert caffe slice layer to mxnet slice layer by changeing caffe_conver tool?

### ISSUE THREAD

**Issue by chenqy4933** [apache/incubator-mxnet#9515]
I try to convert slice layer of caffe to mxnet slice layer,but the caffe_conver tool does not support the  caffe slice layer,I try to fix it but with trouble when _convert_slice_param(layer.slice_param) like convelution layer.

**Comment by chenqy4933** [comment]
sorry，，，I am pool in python 。。。。。。anybody have solved this????

**Comment by chenqy4933** [comment]
@tqchen Can you solve it???

**Comment by ankkhedia** [comment]
@chenqy4933 we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels 
-How To
- Question
-Converter  

and close the issue.

@chenqy4933 if done in error please reopen and comment
