### ISSUE TITLE
cuDNN  path parameter please?

### ISSUE THREAD

**Issue by Godricly** [apache/incubator-mxnet#9518]
Can we have a separate cudnn path parameter in make/config.mk? It's quite unfriendly for me with cuDNN not in cuda path. Because I'm sharing computer with others so the cuDNN version might be different.

**Comment by szha** [comment]
You can always add that to `ADD_LD_FLAGS`, e.g. `ADD_LDFLAGS += -L$(MY_OWN_CUDNN_PATH)`
