### ISSUE TITLE
How to print loaded models ?

### ISSUE THREAD

**Issue by kmul00** [apache/incubator-mxnet#9525]
Hi,

This may seem to be a very basic question, and creating an issue for it may not be the right approach to get it solved. If that's the case, it would be of immense help if someone can direct me to the proper channel to put across my query. :) Googling didn't help much, unfortunately.

I already have a trained model, which I load using the following command and use for prediction purpose:

```python
model = mx.module.Module.load(prefix = self.model_dir, epoch = self.model_epoch, context = self.ctx)
data_shape = (1, 3, 640, 480)
model.bind(data_shapes = [('data', data_shape)], for_training = False)

output = model.predict(input)
```

Now I want to print the model. I understand that *models* in MxNet could be printed using `mx.viz.plot_network(model)` but that requires the model to be in symbolic format (i.e. `mxnet.symbol`).

If I am already loading it in `mxnet.module`, what is the correct way of printing it?

Any help would be highly appreciated. Thanks in advance.

**Comment by reminisce** [comment]
`_symbol` is a data member of `Module`. You can use `model._symbol` to get the symbol.

**Comment by kmul00** [comment]
Yeah, that solved the problem. Thank you so much @reminisce !
