### ISSUE TITLE
Cannot find engine branch for minpy package

### ISSUE THREAD

**Issue by mengyuest** [apache/incubator-mxnet#9533]
I want to use GPU on numpy opers so I tried minpy. The system is ubuntu16.04 and my display card is GTX1080 (cudnn 7.0). When I installed mxnet, I could not find "engine" branch mentioned in instruction step `git clone --recursive -b engine 
https://github.com/dmlc/mxnet.git` 
So I just installed the master branch one and at last I could not use minpy correctly. My program wrote as
```
import minpy.numpy as np
import minpy.numpy.random as random
import time
x= random.rand(1024, 1024)
y= random.rand(1024, 1024)
st = time.time()
for i in range(10):
    z= np.dot(x, y)
z.asnumpy()
print('time: {:.3f}.'.format(time.time()-st))                                                        
```
and when running, it said 
`W0123 14:35:58 22806 minpy.dispatch.registry:register:47] Type MXNet for name reshape has already existed`
Can anyone tell me what to do? Thanks.

**Comment by sxjscience** [comment]
I think you may need to raise an issue in minpy. Also, some features in minpy like [autograd](http://mxnet.incubator.apache.org/api/python/autograd/autograd.html) has been merged into MXNet and you can try that. You may also try to write your functions using [NDArray APIs](http://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html) instead of relying on minpy.

**Comment by ankkhedia** [comment]
@mengyuest Did you raise an issue with dmlc/minpy? It seems like a bug with their documentation.
Also it seems from their readme that the repository has been deprecated and merged with Mxnet Gluon. So, did you try to use that?

@sandeep-krishnamurthy Could you please tag it as

- Pending Requester Info

**Comment by mengyuest** [comment]
@ankkhedia Yeah I have already raised an issue to dmlc/minpy and they told me to use gluon. I tried gluon and it worked. Thanks. Followed is what they told me.
```
Hi @mengyuest , most minpy's functionality have been merged to Gluon. It supports dynamic autograd and quite extensive numpy operator support. Please have a look and see if it helps!
```

**Comment by sxjscience** [comment]
@mengyuest Sounds great! I'll close the issue.

**Comment by belomeriem** [comment]
Hi, 
How did you fix the problem? I am running third-party code and they have `import minpy.numpy as np
from minpy import core
from minpy.nn.solver import Solver` which produces the same error you had. I have tried to use Gluon but this does not seem to help. Any suggestions? Thanks

**Comment by mengyuest** [comment]
I used this and it worked well (though the function is very simple).

```python
import mxnet as mx
from mxnet import nd
import numpy as np
import time

t0=time.time()
mx.random.seed(1)
x=nd.array([[1,2,3,4,5,6],[3,4,56,7,8,9]],ctx=mx.gpu(0))
y1=nd.dot(x,x.T)
print(y1)
t1=time.time()
x=np.array([[1,2,3,4,5,6],[3,4,56,7,8,9]])
y2=np.dot(x,x.T)
print(y2)
t2=time.time()
print(t1-t0,t2-t1)
```
