### ISSUE TITLE
float16 have no performance improvemen in training cifar10

### ISSUE THREAD

**Issue by gzh1991** [apache/incubator-mxnet#9537]
I test the example in image_classfication to test the performance imporvement when using float16 in train phase,but get the opposite results. The parameters I use and the coresponding results are listed below:
 1. python3 train_cifar10.py --gpus 0 --disp-batches 10 --batch-size 1024 --data-nthread 4 --dtype float32

[10:21:53] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar10_train.rec, use 3 threads for decoding..
[10:21:53] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar10_val.rec, use 3 threads for decoding..
[10:21:54] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [10]   Speed: 2087.23 samples/sec      accuracy=0.119940
INFO:root:Epoch[0] Batch [20]   Speed: 2085.22 samples/sec      accuracy=0.181738
INFO:root:Epoch[0] Batch [30]   Speed: 2081.76 samples/sec      accuracy=0.222070
INFO:root:Epoch[0] Batch [40]   Speed: 2082.71 samples/sec      accuracy=0.237402

2.python3 train_cifar10.py --gpus 0 --disp-batches 10 --batch-size 1024 --data-nthread 4 --dtype float16

[10:23:57] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar10_train.rec, use 3 threads for decoding..
[10:23:57] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/cifar10_val.rec, use 3 threads for decoding..
[10:23:58] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [10]   Speed: 1570.73 samples/sec      accuracy=0.126332
INFO:root:Epoch[0] Batch [20]   Speed: 1571.33 samples/sec      accuracy=0.197168
INFO:root:Epoch[0] Batch [30]   Speed: 1568.59 samples/sec      accuracy=0.233301
INFO:root:Epoch[0] Batch [40]   Speed: 1570.66 samples/sec      accuracy=0.271680

I want to known is this the expected results or just because of 1080 Ti itself or some other reasons.

## Environment info (Required)
MXNET 1.0.0
GPU Getforce 1080 Ti
CUDA 8.0
MXNET_CUDNN_AUTOTUNE_DEFAULT=1 
CUDNN 5.1

**Comment by marcoabreu** [comment]
@KellenSunderland

**Comment by KellenSunderland** [comment]
Hello @gzh1991, thanks for aaking this question, as I'm sure it's of interest to a few users. 

I've recently had similar results,  and can share what my measurements have shown.  To find out exactly why it's slower on your machine I recommend using nvprof to look at the perf summaries for both fp32 and fp16.

What I have noted is that fp16 requires kernel launches with typically more registers used per thread than fp32.  There's a fixed number of registers per processor in your gpu, so cuda responds to this increase by decreasing the number of threads running concurrently.  This obviously lowers perf.  

So in the general case fp16 might run back little slower, but the big caveat is if you're using hardware that has special instructions to accelerate fp16 matrix mults.  Currently this means you'd need to have a V100 (as in the aws p3 instance) or a Titan V.  If you have this hardware you should see a quite dramatic increase in performance for network  layers that are supported (for example fully connected layers).  If you don't have one of those gpus you're probably better off sticking with fp32 fir training unless you're memory constrained

**Comment by KellenSunderland** [comment]
I think this one can be closed @szha.   Hopefully that answers your questions @gzh1991?  If not feel free to re-open.

**Comment by gzh1991** [comment]
Thanks a lot for your reply and explanation! I have tested on Titan X as you said, and fp16 do have a better performance.
