### ISSUE TITLE
How can I reinitialize a key in kvstore?

### ISSUE THREAD

**Issue by solin319** [apache/incubator-mxnet#9538]
I Initialize a key in kvstore.
```
kv = mx.kv.create('device') 
shape = (2,3)
kv.init(3, mx.nd.ones(shape)*2)
```
I want to init key 3 with another shape in a same program. How can I reinitialize this key? Or is there any method to remove this key in kvstore?

**Comment by tolkien16** [comment]
Hi

**Comment by solin319** [comment]
Does MXNet has a interface to remove or re-init a key-value pairs saved in kvstore?
@piiswrong

**Comment by sandeep-krishnamurthy** [comment]
Hello @solin319 
KVStore does not allow:
1. Remove a key after init
2. Modify shape of a key-value pair after init

You can only:
1. Change the value of existing key i.e., push and pull.
2. Add new key even after init.

Please feel free to reopen if you need more help.
