### ISSUE TITLE
Automatically test for addto for ALL operators

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#9546]
See https://github.com/apache/incubator-mxnet/pull/9541#issuecomment-360240969

**Comment by asmushetzel** [comment]
There is a similar issue already open #9497

May be we should use that one (or close that but we should have one single issue for this). Note that 9497 also lists one operator that does not support kAddTo, so this has to be fixed anyway.

**Comment by marcoabreu** [comment]
Ah, thanks! Closing this issue then.
