### ISSUE TITLE
Pkg MXNet doesn't build on Julia

### ISSUE THREAD

**Issue by LTGZZ** [apache/incubator-mxnet#9550]
## Description
I'm trying to build MXNet from within the latest Julia (0.6.2) on Slackware64-14.2.
The build fails with two error messages.

## Environment info (Required)

----------Python Info----------
('Version      :', '2.7.14')
('Compiler     :', 'GCC 5.3.0')
('Build        :', ('default', 'Sep 21 2017 14:27:06'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/usr/lib64/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '1.0.1')
('Directory    :', '/home/me/incubator-mxnet/python/mxnet')
Traceback (most recent call last):
  File "diagnose.py", line 171, in <module>
    check_mxnet()
  File "diagnose.py", line 113, in check_mxnet
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

## Log

/usr/share/cuda//bin/nvcc -c -o build/src/operator/batch_norm_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=[sm_61,compute_61] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/me/.julia/v0.6/MXNet/deps/src/mxnet/mshadow/ -I/home/me/.julia/v0.6/MXNet/deps/src/mxnet/dmlc-core/include -fPIC -I/home/me/.julia/v0.6/MXNet/deps/src/mxnet/nnvm/include -I/home/me/.julia/v0.6/MXNet/deps/src/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DINTERFACE64 -msse3 -I/usr/share/cuda//include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMXNET_USE_LAPACK -I/home/me/.julia/v0.6/MXNet/deps/src/mxnet/cub -DMXNET_USE_LIBJPEG_TURBO=0" src/operator/batch_norm.cu
/home/me/.julia/v0.6/MXNet/deps/src/mxnet/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh(75): error: expression preceding parentheses of apparent call must have (pointer-to-) function type

/home/me/.julia/v0.6/MXNet/deps/src/mxnet/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh(75): error: expression preceding parentheses of apparent call must have (pointer-to-) function type

2 errors detected in the compilation of "/tmp/tmpxft_0000312a_00000000-24_activation.compute_30.cpp2.i".
Makefile:353 : la recette pour la cible « build/src/operator/activation_gpu.o » a échouée
make: *** [build/src/operator/activation_gpu.o] Erreur 2
make: *** Attente des tâches non terminées....
======================================================[ ERROR: MXNet ]======================================================

LoadError: failed process: Process(`make -j8 USE_BLAS=openblas 'MSHADOW_LDFLAGS=-lm /usr/bin/../lib/julia/libopenblas64_.so'`, ProcessExited(2)) [2]
while loading /home/me/.julia/v0.6/MXNet/deps/build.jl, in expression starting on line 81

**Comment by lupesko** [comment]
@sandeep-krishnamurthy please label:
- Julia
- Build

@LTGZZ you might want to fine an issue on the [Julia GitHub repo](https://github.com/dmlc/MXNet.jl/) or provide more information about the build command you are using.

**Comment by iblis17** [comment]
see: https://github.com/apache/incubator-mxnet/issues/15587#issuecomment-513128172

**Comment by iblis17** [comment]
Please try out the v1.5.0 release.
