### ISSUE TITLE
0 to the power of 0 is nan on GPU

### ISSUE THREAD

**Issue by zhreshold** [apache/incubator-mxnet#9555]
A simple bug on gpu only
```
import mxnet as mx
import numpy as np
print(mx.nd.array([0, 1e-30], ctx=mx.cpu()) ** 0)
# [1. 1.]
print(mx.nd.array([0, 1e-30], ctx=mx.gpu()) ** 0)
# [nan 1.]
print(np.array([0, 1e-30]) ** 0)
# [1. 1.]
```
Env: mxnet-cu90 1.0.1 nightly build on windows

**Comment by sxjscience** [comment]
I think nan is the correct behavior as 0 power 0 is undefined.

**Comment by zhreshold** [comment]
It's mathmatically undefined behavior but should made consistant with numpy and cpu impl. So I guess it's CUDA `powf` function to blame?

**Comment by szha** [comment]
cc @yajiedesign

**Comment by ankkhedia** [comment]
@zhreshold The issue is duplicate of #9572. So, closing this additional issue as its already getting tracked.

@sandeep-krishnamurthy  Please tag this as 
- Duplicate
- Bug

and close the issue
@zhreshold  Please feel free to comment and reopen if the issue gets closed in error.
