### ISSUE TITLE
update_on_kvstore error setting with multiple machines

### ISSUE THREAD

**Issue by yuewu001** [apache/incubator-mxnet#9557]
When I was training with multiple machines, i found that [model.py:_create_kvstore ](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/model.py)function sets update_on_kvstore to True. In the gluon interface (trainer.py), i found the following code: 
```python
 if 'dist' in kvstore.type:
    update_on_kvstore = False
    for i, param in enumerate(self._params):
        param_arrays = param.list_data()
        kvstore.init(i, param_arrays[0])
        kvstore.pull(i, param_arrays, priority=-i)
```
while in module.py, update_on_kvstore is not set to False. 

Is this a bug?

Besides, the gluon interfaces pull all param_arrarys whatever update_on_kvstore is. But in the python interface (model.py), only when update_on_kvstore is True, the params are pulled.  Any reasons?

```python
def _initialize_kvstore(kvstore, param_arrays, arg_params, param_names, update_on_kvstore):
    """Initialize kvstore"""
    for idx, param_on_devs in enumerate(param_arrays):
        name = param_names[idx]
        kvstore.init(name,  #arg_params[name])

        if update_on_kvstore:
            kvstore.pull(name, param_on_devs, priority=-idx)
```

Overall, how to save_optimizer_states properly in distributed training?

**Comment by sandeep-krishnamurthy** [comment]
@rahul003 @piiswrong - You want to take a look at this?

**Comment by rahul003** [comment]
It doesn't look like a bug per se. The update is still done after pulling from the kvstore. I'm not sure if there is a reason why the update is done here rather than on the kvstore 

Regarding the second point, that is just the init. And update_on_kvstore is only false when kvstore is local. Maybe there is one pull that can be saved, need to look into that.

**Comment by yuewu001** [comment]
Thank you for your reply. Do you have any ideas on how to save_optimizer_states property in distributed training, especially when update_on_kvstore is True?

**Comment by sandeep-krishnamurthy** [comment]
@yuewu001 
1. Trainer is now fixed and uses the same logic as in Module. [Here in Trainer](- https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/trainer.py#L188) is where you create the KVStore using [model._create_kvstore](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/model.py#L77). However, please note that, it is not recommended to use KVStore when grad is sparse, hence, it will be set to false when grad is sparse.
2. To save optimizer states, you can use trainer.save_states(file_name). https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/trainer.py#L376

Resolving the issue. Please reopen, if your still have questions/issues.
