### ISSUE TITLE
Are saved mxnet models GPU or system specific? 

### ISSUE THREAD

**Issue by Garglesoap** [apache/incubator-mxnet#9565]
Model train system: AWS Ubuntu p2.xlarge, R 3.4.0, mxnet_1.0.1.
Saved via:
mx.model.save(A3.MXmodel, "Action/A3.MXmodel", iteration = 3000)

Loading on same system works fine via:
A3.MXmodel <- mx.model.load("A3.MXmodel", iteration=3000)
A3.pred <- predict(A3.MXmodel, as.matrix(nNewVector))
A3.pred.label = max.col(t(A3.pred))-1

Moving the model files to a new system (AMI clone of first instance BUT on g2.xlarge). And attempting to predict:
A3.pred <- predict(A3.MXmodel, as.matrix(nNewVector))
leads to an immediate crash of rstudio, no data saved or error messages. 

I can confirm mxnet is working on the new instance via the installation check: 
library(mxnet)
a <- mx.nd.ones(c(2,3), ctx = mx.gpu())
b <- a * 2 + 1
b

Do I have to specifify somewhere on the new isntance that the models are based on GPU devices? 
Can a model trained on a GPU instance be run on a CPU instance with CPU mxnet build?

**Comment by roywei** [comment]
@sandeep-krishnamurthy please add label: R, thanks!

**Comment by sandeep-krishnamurthy** [comment]
Same as this query - https://stackoverflow.com/questions/48455833/are-saved-mxnet-models-gpu-or-system-specific

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please close this bug, as the question has been answered
