### ISSUE TITLE
nd.argmax cause "Kernel Died" error in Jupyter Notebook

### ISSUE THREAD

**Issue by kaonashi-tyc** [apache/incubator-mxnet#9567]
## Description
Running the following code is causing a "Kernel Died" error in my Jupyter notebook:
```python
from mxnet import nd as nd

nd.argmax(nd.ones([1,2]))
```
However if **axis** as a keyword argument is provided, this bug can be bypassed

## Environment info
----------Python Info----------
Version      : 3.6.3
Compiler     : GCC 7.2.0
Build        : ('default', 'Oct 13 2017 12:02:49')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : xxxx
----------MXNet Info-----------
Version      : 1.0.0
Directory    :  xxx
Commit Hash   : 7a83d67ecd3e49a3b342cc896598cc0d44de60e0
----------System Info----------
Platform     : Linux-4.4.0-1048-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : xxx
release      : 4.4.0-1048-aws
version      : xxxx
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2699.894
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.11
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt

**Comment by reminisce** [comment]
`argmax` currently does not support global reduction. A workaround might be that when axis is not entered, flatten the tensor into 1D and call argmax on the 1D tensor with axis=0.

**Comment by kaonashi-tyc** [comment]
@reminisce A bigger issue is this line of code crashing the whole Python process along with itself. If Global Reduction is not supported, it should throw an exception, not kill the process or kernel.

**Comment by reminisce** [comment]
Agreed. @anirudh2290 is working on exception handling. It should allow python environment to catch the exception like this gracefully in the future.

**Comment by anirudh2290** [comment]
Related to: #7335
