### ISSUE TITLE
metric.F1 doc needs clarification

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#9587]
The current logic only supports what's called "macro F1" logic where we take the mean of F1 scores for mini-batches, which needs to be clarified in doc.

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/metric.py#L491-L493

**Comment by thomelane** [comment]
@szha @indhub the docs were updated as part of https://github.com/apache/incubator-mxnet/pull/9777 so this can be closed, thanks!
