### ISSUE TITLE
undefined symbol "_ZN5mxnet2op12CuDNNAlgoRegINS0_18DeconvolutionParamEE3GetEv" in libmxnet.so

### ISSUE THREAD

**Issue by beyond-boy** [apache/incubator-mxnet#9599]
## Description
I comile mxnet with source code and install python package.
but when I start mxnet python package, It reports "undefined symbol in libmxnet.so" error!  

## Environment info (Required)

----------Python Info----------
('Version      :', '2.7.13')
('Compiler     :', 'GCC 5.4.0')
('Build        :', ('default', 'Jan 25 2018 01:42:41'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/xx/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip')
----------MXNet Info-----------
Traceback (most recent call last):
  File "tools/diagnose.py", line 171, in <module>
    check_mxnet()
  File "tools/diagnose.py", line 113, in check_mxnet
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

Package used (Python/R/Scala/Julia):
(I'm using ...)

## Build info (Required if built from source)

Compiler (gcc5.4):

Build config:
```
export CC = gcc
export CXX = g++
export NVCC = nvcc
DEV = 0
DEBUG = 0
USE_PROFILER =
USE_SIGNAL_HANDLER =
ADD_LDFLAGS =
ADD_CFLAGS =
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda-8.0
ENABLE_CUDA_RTC = 1
USE_CUDNN = 1
USE_CUDNN_PATH = /mnt/mfs/tools/cuda
USE_NCCL = 0
USE_NCCL_PATH = NONE
USE_OPENCV = 0
USE_LIBJPEG_TURBO = 0
USE_LIBJPEG_TURBO_PATH = NONE
USE_OPENMP = 1
MKLML_ROOT=/usr/local
USE_MKL2017 = 0
USE_MKL2017_EXPERIMENTAL = 0
USE_NNPACK = 0
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = openblas
endif
USE_LAPACK = 0
USE_LAPACK_PATH =
USE_INTEL_PATH = NONE
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif
ARCH := $(shell uname -a)
ifneq (,$(filter $(ARCH), armv6l armv7l powerpc64le ppc64le aarch64))
        USE_SSE=0
else
        USE_SSE=1
endif
USE_DIST_KVSTORE = 0
USE_HDFS = 0
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server
USE_S3 = 0
USE_OPERATOR_TUNING = 1
USE_GPERFTOOLS = 1
USE_JEMALLOC = 1
EXTRA_OPERATORS =
USE_CPP_PACKAGE = 0
```

## Error Message:
```
In [1]: import mxnet as mx
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-265f02e9c062> in <module>()
----> 1 import mxnet as mx

/mnt/mfs/incubator-mxnet/python/mxnet/__init__.py in <module>()
     23 
     24 from .context import Context, current_context, cpu, gpu
---> 25 from . import engine
     26 from .base import MXNetError
     27 from . import base

/mnt/mfs/incubator-mxnet/python/mxnet/engine.py in <module>()
     21 
     22 import ctypes
---> 23 from .base import _LIB, check_call
     24 
     25 

/mnt/mfs/incubator-mxnet/python/mxnet/base.py in <module>()
    109 __version__ = libinfo.__version__
    110 # library instance of mxnet
--> 111 _LIB = _load_lib()
    112 
    113 # type definitions

/mnt/mfs/incubator-mxnet/python/mxnet/base.py in _load_lib()
    101     """Load library by searching possible path."""
    102     lib_path = libinfo.find_lib_path()
--> 103     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
    104     # DMatrix functions
    105     lib.MXGetLastError.restype = ctypes.c_char_p

/mnt/mfs/local/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360 
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

OSError: /mnt/mfs/incubator-mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN5mxnet2op12CuDNNAlgoRegINS0_18DeconvolutionParamEE3GetEv
```

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy Please apply labels - Python, Build, Pending Requester Info

@beyond-boy Can you update the steps to reproduce and if you tried anything to solve it?

**Comment by lanking520** [comment]
@beyond-boy This issue appeared that CUDNN is not properly loaded, can you double check the path and try again? Alternatively, you can try with pre-baked pip package to get it to work.

**Comment by anirudhacharya** [comment]
I think this can be closed due to inactivity. cc @nswamy

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@beyond-boy  Please feel free to re-open the issue in case closed in error.

**Comment by zachgk** [comment]
@mxnet-label-bot add [suggest-closed]

**Comment by nswamy** [comment]
closing due to lack of response from the user.
