### ISSUE TITLE
How to implement an efficient DataIter for image segmentation in mxnet?

### ISSUE THREAD

**Issue by gaosanyuan** [apache/incubator-mxnet#9600]
I have implemented one, but when the input crop image size is large, the usage of GPU is much less than 100%

**Comment by shuokay** [comment]
You can try to preload all data into memory in advance.

**Comment by gaosanyuan** [comment]
More than 100G data

**Comment by roywei** [comment]
@sandeep-krishnamurthy Please add label: Question, Exploration, thanks!

**Comment by sandeep-krishnamurthy** [comment]
@gaosanyuan - Can you please ask usability and best practices question at https://discuss.mxnet.io 
Resolving this issue. Please feel free to reopen if you find bugs/issues with MXNet.
