### ISSUE TITLE
MXNET not working in R

### ISSUE THREAD

**Issue by vijayzutshi** [apache/incubator-mxnet#9602]
Hi,

I am using Windows environment on my desktop computer. I have latest version of R installed R3.4.3. I installed mxnet as per following commands:-

cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/GPU"
options(repos = cran)
install.packages("mxnet")

after installing I got following message:-

package ‘mxnet’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Vijay\AppData\Local\Temp\RtmpApwMrr\downloaded_packages

I then wanted to use mxnet library so I typed 

library(mxnet) and got the following error:-

Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Vijay/Documents/R/win-library/3.4/mxnet/libs/x64/libmxnet.dll':
  LoadLibrary failure:  The specified module could not be found.

Please provide a solution for this.

Thanks
Vijay Zutshi

**Comment by jeremiedb** [comment]
I don't have access to a Windows GPU, but could you confirm if the CPU version can be installed and works properly? The pre-compiled Windows haven't been refreshed for a while, in the meantime, maybe you could consider running through docker? https://hub.docker.com/r/mxnet/r-lang/tags/
Sorry for the partial answer!

**Comment by jeremiedb** [comment]
Hi, the official repo hasn't been updated. In the meantime, you can install this version (CPU only for now): 
```
install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)
```

**Comment by apshreyans** [comment]
Thanks much. It worked for me.
