### ISSUE TITLE
Transition matrix is not updated during the train in the lstm_crf example

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [apache/incubator-mxnet#9613]
I think there is a bug in the lstm_crf example.
Please see my reviews there.

https://github.com/apache/incubator-mxnet/pull/7253

**Comment by sxjscience** [comment]
OK. Feel free to provide more details.

**Comment by roywei** [comment]
@sandeep-krishnamurthy Please kindly add labels, Bug, Pending Requester Info. Thanks!

**Comment by anirudh2290** [comment]
@zhangchen-qinyinghua i cannot see your reviews in #7253 . can you please provide a minimum reproducible example.

**Comment by zhangchen-qinyinghua** [comment]
@anirudh2290 
The problem is, the transition matrix should be made one of the parameters (can be learned during the train process), rather than be fixed.
I will try to make a PR resently, fix the bug together with a mini-batch version of LSTM-CRF implenmentation.

**Comment by vdantu** [comment]
@zhangchen-qinyinghua : Could you please share more information about what issue you were facing? Minimum reproducible code would be very nice to have.  Or, if you have a PR with suggested changes, please do share.

**Comment by szha** [comment]
#11375 should have fixed it.
