### ISSUE TITLE
A tutorial for Word embeddings using mxnet

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#9623]
I was trying to get familiar with mxnet framework and was browsing the tutorial section - https://mxnet.apache.org/tutorials/index.html.

I did not come across any illustrations for generating vector representations of words, like word2vec models( https://en.wikipedia.org/wiki/Word2vec ). Would it make sense to create a PR with one such tutorial. Is that something that will make sense in this code repo.

**Comment by szha** [comment]
@astonzhang

**Comment by astonzhang** [comment]
I think @zackchase is doing it.

**Comment by anirudhacharya** [comment]
Is there already a PR in review?

**Comment by Godricly** [comment]
Will MxNet implement a tokenizer as the one in Keras? Right now I use Keras to process the raw data and then convert it numpy array. It works well but too stupid. 😞 
@anirudhacharya If you are familiar with Keras, you can follow my data iter first.
[comment toxic](https://github.com/Godricly/comment_toxic)

**Comment by ThomasDelteil** [comment]
@anirudhacharya you can find example of word embedding training and usage in the [Gluon-NLP](http://gluon-nlp.mxnet.io/examples/word_embedding/word_embedding_training.html) project:
- [Using pre-trained word embeddings](http://gluon-nlp.mxnet.io/examples/word_embedding/word_embedding.html)
- [Training your own word embeddings](http://gluon-nlp.mxnet.io/examples/word_embedding/word_embedding_training.html)

Please consider closing, thanks
