### ISSUE TITLE
Support pre-kepler GPUs without __shfl_down instruction

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#9632]
https://discuss.gluon.ai/t/topic/4444

**Comment by cjolivier01** [comment]
It appears that pytorch and TF don;t support Fermi GPUs. Do we wish to continue support?

**Comment by cjolivier01** [comment]
https://github.com/apache/incubator-mxnet/pull/10375

**Comment by anirudh2290** [comment]
@piiswrong can this be closed ?

**Comment by vandanavk** [comment]
Pre-Kepler GPUs have been disabled by the PR referenced here.

@sandeep-krishnamurthy Please close this issue.

@piiswrong Please reopen this issue if it has been closed in error.
