### ISSUE TITLE
input with name 'data' is not found in symbol.list_arguments()

### ISSUE THREAD

**Issue by VictoriaYyz** [apache/incubator-mxnet#9637]
I try to construct a cnn model with MxNet Symbol API (1.0), but when I create a module:
mod = mx.mod.Module(symbol=out,label_names=('input_label',),data_names=('input_data',),context=mx.gpu(0)) 
I got a ValueError : You created Module with Module(..., data_names=['input_data']) but input with name 'input_data' is not found in symbol.list_arguments(). 
How can I solve this problem?

**Comment by reminisce** [comment]
What's the output of symbol.list_arguments()? You need to use the data name in the outputs of list_arguments() to initialize a module.

**Comment by VictoriaYyz** [comment]
The outputs of symbol.list_arguments() is 'input_label' and a name of intermediate computing result, but specify the data_names is to feed input data not intermediate computing result, right?

**Comment by VictoriaYyz** [comment]
My code is this:
  data = mx.sym.Variable(name='input_data')
  softmax_label = mx.sym.Variable(name='input_label')
  conv1 = conv_block(data,2,64,1)
  conv2 = conv_block(conv1,2,128,2)
  conv3 = conv_block(conv2,3,256,3)
  conv4 = conv_block(conv3,3,512,4)
  conv5 = conv_block(conv4,3,512,5)
  fc6 = fc_block(conv5,4096,6)
  fc7 = fc_block(fc6,4096,7)
  fc8 = out_block(fc7,10,8)
  out = mx.sym.SoftmaxOutput(data=fc8,label=softmax_label)
  mod = mx.mod.Module(symbol=out,label_names=('input_label',),data_names=('input_data',),context=mx.gpu(0))

**Comment by reminisce** [comment]
Can you post the outputs of list_arguments here?

**Comment by VictoriaYyz** [comment]
ValueError: You created Module with Module(..., data_names=['input_data']) but input with name 'input_data' is not found in symbol.list_arguments(). Did you mean one of:
	softmaxoutput0_data
	input_label

**Comment by reminisce** [comment]
Please post the whole script including conv_block, fc_block, and out_block.

**Comment by VictoriaYyz** [comment]
def conv_block(x,num_convs,out_channels,block_id):
  for i in range(num_convs):
    x = mx.sym.Convolution(data=x,num_filter=out_channels,kernel=(3,3),stride=(1,1),pad=(1,1),no_bias=False,name='conv%d_%d '% (block_id,i+1))
    x = mx.sym.BatchNorm(data=x,name='bn%d_%d '% (block_id,i+1))
    x = mx.sym.Activation(data=x,act_type='relu',name='relu%d_%d' % (block_id,i+1))
  if block_id != 5:
    x = mx.sym.Pooling(data=x,kernel=(2,2),pool_type='max',stride=(2,2),name='pool%d '% block_id)
  return x

def fc_block(x,num_hidden,block_id):
  x = mx.sym.FullyConnected(data=x,num_hidden=num_hidden,flatten=True,name='fc%d' % block_id)
  x = mx.sym.BatchNorm(data=x,name='bn%d' % block_id)
  x = mx.sym.Activation(data=x,act_type='relu',name='relu%d' % block_id)
  return x

def out_block(x,num_classes,block_id):
  x = mx.sym.FullyConnected(data=x,num_hidden=num_classes,flatten=True,name='fc%d' % block_id)

def train():
  (x_train, y_train), (x_test, y_test) = cin.read_data()
  train_iter = mx.io.NDArrayIter(data=x_train,label=y_train,batch_size=100,shuffle=True,last_batch_handle='discard',data_name='input_data', label_name='input_label')
  valid_iter = mx.io.NDArrayIter(data=x_test,label=y_test,batch_size=100)
  data = mx.sym.Variable(name='input_data')
  softmax_label = mx.sym.Variable(name='input_label')
  conv1 = conv_block(data,2,64,1)
  conv2 = conv_block(conv1,2,128,2)
  conv3 = conv_block(conv2,3,256,3)
  conv4 = conv_block(conv3,3,512,4)
  conv5 = conv_block(conv4,3,512,5)
  fc6 = fc_block(conv5,4096,6)
  fc7 = fc_block(fc6,4096,7)
  fc8 = out_block(fc7,10,8)
  out = mx.sym.SoftmaxOutput(data=fc8,label=softmax_label)
  mod = mx.mod.Module(symbol=out,label_names=('input_label',),data_names=('input_data',),context=mx.gpu(0))
  mod.bind(data_shapes=train_iter.provide_data,label_shapes=train_iter.provide_label)
  mod.fit(train_iter,eval_data=valid_iter,optimizer='sgd',optimizer_params={'learning_rate':0.1},initializer=mx.initializer.Uniform(0.1),eval_metric='acc',num_epoch=2)

**Comment by smarthi** [comment]
Please post this to dev@mxnet and let the discussion continue there, closing this issue.

**Comment by reminisce** [comment]
@smarthi Why did you close the issue?

**Comment by smarthi** [comment]
Read my comment, henceforth move these discussions to mail lists.

**Comment by reminisce** [comment]
@smarthi No more discussions on GitHub? When was this implemented? We didn't receive any notifications regarding this.

**Comment by piiswrong** [comment]
why?
I thought github issues and forums are accepted venues for discussion

**Comment by reminisce** [comment]
@VictoriaYyz In out_block, you forgot to `return x`.

**Comment by VictoriaYyz** [comment]
Oh....I'm too careless...Thank you very much !!!

**Comment by kdgutier** [comment]
I had a similar error, it turned out to be because when defining the graph I believe the Model class does not like to have 'unused' symbols.
