### ISSUE TITLE
TEST(MEMORY_TEST, MemsetAndMemcopyPerformance) sometimes failing with timer failures

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#9649]
## Description

Test relies on timings, which may or may not explain why it sometimes fails in CI.

## Things to try

We could do a 'near' comparison.

http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9609/runs/22/nodes/427/log/?start=0

## Environment info (Required)

CI Environment failure.

**Comment by spidyDev** [comment]
@KellenSunderland  @cjolivier01 

I am looking at this flaky test, had some queries and comments:
- The test compares  normal memcpy/memset against with using openmp, and expects normal memcpy to be always faster . Although its will be true for small data size ( coz of overhead of creating threads with Openmp), but Openmp can be faster for larger data size , as with multiple threads utilizes greater memory bandwidth.
Could you please let me know if I am missing something here. (reference to [code](https://github.com/apache/incubator-mxnet/blob/master/tests/cpp/misc/memory_test.cc#L123)

**Comment by KellenSunderland** [comment]
@spidyDev I found this test to vary a lot depending on machine type as well.  On my AMD machine it was consistently failing (openmp was always faster) and my intel machine it was consistently passing.  I think this would be confusing for users so my recommendation would actually be that we remove this test.

**Comment by lupesko** [comment]
@KellenSunderland the PR removing the test was merged. Kindly close the issue. Thanks!
