### ISSUE TITLE
Sparse Tensor support in scala api

### ISSUE THREAD

**Issue by ericvlognow** [apache/incubator-mxnet#9656]
The sparse tensor is supported in python api. is any plan to add the support in scala api also?

thanks

eric

**Comment by wellner** [comment]
I'd second this request for support of sparse tensors/ndarrays in Scala.  Thanks!

**Comment by lanking520** [comment]
Sparse API is still in the queue of our TODO list. We will try to get this set of APIs release in the next few months. If you can't wait and would like to 'unlock' this feature to try on your own, please change it here: 
https://github.com/apache/incubator-mxnet/blob/master/scala-package/macros/src/main/scala/org/apache/mxnet/SymbolMacro.scala#L60#L63 
or here if you prefer type-checked api:
https://github.com/apache/incubator-mxnet/blob/master/scala-package/macros/src/main/scala/org/apache/mxnet/SymbolMacro.scala#L94#L98
Just allow '_sparse_' as an accepted input. There is no guarantee that this API will fully worked as we haven't test that.

**Comment by mdespriee** [comment]
interested as well, as this is key to our adoption of MXNet (we're heavy user of sparse computations)

**Comment by zachgk** [comment]
Sparse Support was added in https://github.com/apache/incubator-mxnet/pull/15378
