### ISSUE TITLE
[Feature request] += operator for Symbol

### ISSUE THREAD

**Issue by dongzhuoyao** [apache/incubator-mxnet#9667]
```
raise NotImplementedForSymbol(self.__iadd__, '+=', other, 1)
mxnet.base.NotImplementedForSymbol: Function __iadd__ (namely operator "+=") with arguments (<class 'mxnet.symbol.symbol.Symbol'>, <type 'int'>) is not implemented for Symbol and only available in NDArray.
```

any willing to override the += operator for symbol ? if ok, I can create a pr.

**Comment by marcoabreu** [comment]
@piiswrong

**Comment by piiswrong** [comment]
symbols are immutable. This is not possible by design

**Comment by haoliyoupai09** [comment]
raise NotImplementedForSymbol(self.__iadd__, '+=', other, 1)
mxnet.base.NotImplementedForSymbol: Function __iadd__ (namely operator "+=") with arguments (<class 'mxnet.symbol.symbol.Symbol'>, <type 'int'>) is not implemented for Symbol and only available in NDArray.

When I compile a project using mxnet, I met the error like this. The mxnet is complied successfully and import mxnet in python is also right. Could you tell me what to do?

**Comment by MaAo** [comment]
I met the same problem.Can anybody fix it ?

**Comment by ChaiBapchya** [comment]
Thanks for raising this issue.
Could you explain what use case do you need it for? What were you trying to achieve and using what command can I reproduce the error? I'll try to help you in that case.

**Comment by wangpichao** [comment]
@MaAo @dongzhuoyao  please change the a=+b to a = a + b, and it would fix the issue.
