### ISSUE TITLE
MX.LSTM time series

### ISSUE THREAD

**Issue by dma100180** [apache/incubator-mxnet#9673]
[data.zip](https://github.com/apache/incubator-mxnet/files/1686927/data.zip)

Hi, I'm trying to create an **LSTM network to predict a time series**. I try with the first three variables to predict the fourth but I am not able to create the LST, LSTM.INFERENCE and LSTM.FORWARD models and the examples I do not see any that are very basic to follow, I have only been able to follow the detection of words but I do not get it. 
I leave the file with the data and the code for if someone can give me the example to continue.

Thanks greetings

require(mxnet)

batch.size = 32
seq.len = 32#en el ejemplo 32
num.hidden = 16
num.embed = 16
num.lstm.layer = 1
num.round = 1
learning.rate= 0.1
wd=0.00001
clip_gradient=1
update.period = 1

DAnalisisLSTM<-read.csv("D:/data.csv")
DAnalisisLSTM<-DAnalisisLSTM[,c(2,3,4,5)]

train2.x<-DAnalisisLSTM[1:1000,c(1,2,3)]
train2.y<-DAnalisisLSTM[1:1000,c(4)]
test2.x<-DAnalisisLSTM[1000:1203,c(1,2,3)]
test2.y<-DAnalisisLSTM[1000:1203,c(4)]

X.train <- list(data=train2.x, label=train2.y)
X.val <- list(data=test2.x, label=test2.y)

model <- mx.lstm(X.train, X.val,
                 ctx=mx.cpu(),
                 num.round=num.round,
                 update.period=update.period,
                 num.lstm.layer=num.lstm.layer,
                 seq.len=seq.len,
                 num.hidden=num.hidden,
                 num.embed=num.embed,
                 num.label=10,
                 batch.size=batch.size,
                 input.size=10,
                 initializer=mx.init.uniform(0.1),
                 learning.rate=learning.rate,
                 wd=wd,
                 clip_gradient=clip_gradient)

**Comment by jeremiedb** [comment]
mx.lstm has been deprecated for a more general rnn model constructor. You can take a look here for a time-series and other rnn examples in R: https://jeremiedb.github.io/mxnet_R_bucketing/TimeSeries_CPU.html

**Comment by dma100180** [comment]
Thank you very much ... I've been several weeks gracious again for letting me know
