### ISSUE TITLE
Is there a video classification distributed training example (demo)?

### ISSUE THREAD

**Issue by KeyKy** [apache/incubator-mxnet#9680]

**Comment by Roshrini** [comment]
@KeyKy please submit general questions on [Discuss forum](discuss.mxnet.io) for quicker response.

@sandeep-krishnamurthy can you add labels
- Question
- Doc
and close this issue?

**Comment by KeyKy** [comment]
https://github.com/apache/incubator-mxnet/issues/discuss.mxnet.io -> returns not found....

**Comment by sandeep-krishnamurthy** [comment]
https://discuss.mxnet.io/
