### ISSUE TITLE
Possible memory leak with de-convolution operator in CPU mode 

### ISSUE THREAD

**Issue by pharish93** [apache/incubator-mxnet#9690]
I face a repeated issue of minimum work space requirement , and code crashing at the deconvolution operator .
# Mxnet Version :
working on mxnet 1.0 , using python , code built from sources for a cpu version 

# Code : 
Deconvolution :- 
upsample_feature = mx.symbol.Deconvolution(    data=relu5_3, kernel=(16, 16), stride=(8, 8), pad=(4, 4), num_filter=512, num_group=512,  no_bias=True, name="upsample_proposal", workspace=2048)

# Observation
Increasing the  work space size, just increases the number of iterations after which the code breaks . I tried it a number of times and the same pattern repeats , 

# Error log :- 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:29:12] src/engine/./threaded_engine.h:359: [04:29:12] src/operator/nn/./deconvolution-inl.h:470: Check failed: param_.workspace >= required_size (536870912 vs. 613444608) 
Minimum workspace size: 2453778432 Bytes
Given: 2147483648

Stack trace returned 10 entries:
[bt] (0) /.../mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5a) [0x7fb7432d1bfa]
[bt] (1) /.../mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7fb7432d2798]
[bt] (2) /.../mxnet/libmxnet.so(mxnet::op::DeconvolutionOp<mshadow::cpu, float>::InitTemp(mshadow::Shape<4> const&, mshadow::Shape<4> const&)+0x50c) [0x7fb7457c6c8c]
[bt] (3) /.../mxnet/libmxnet.so(mxnet::op::DeconvolutionOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x8ed) [0x7fb7457cddcd]
[bt] (4) /.../mxnet/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x363) [0x7fb7459531f3]
[bt] (5) /.../mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x69) [0x7fb745efd399]
[bt] (6) /.../mxnet/libmxnet.so(+0x36b99c0) [0x7fb745ebd9c0]
[bt] (7) /.../mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x93) [0x7fb745e49c13]
[bt] (8) /.../mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>&&)+0xe2) [0x7fb745e53872]
[bt] (9) /.../mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)> (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)> >::_M_run()+0x4a) [0x7fb745e4d3ba]

**Comment by sxjscience** [comment]
@pharish93 Have you tried to increase the size of the workspace to 4096? The error message shows that the workspace is too small.

@piiswrong Workspace is used to control the `nstep_`  (https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/deconvolution-inl.h#L455-L460), which means the effective batchsize, https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/deconvolution-inl.h#L378

**Comment by pharish93** [comment]
@sxjscience  I havn't tried 4096 yet ,  I have been increasing it from 512 onwards , every time it failed . 
Upon increasing the size , it was observed that it ran for more number of iterations and breaks , it was similar to a memory leak issue . 
I could run the code for 4096 and update you by tomorrow

**Comment by sxjscience** [comment]
@pharish93 Thanks a lot! Also, would you mind providing some example codes? If this is a potential memory leakage problem,  it will be easier for us to debug.

**Comment by sxjscience** [comment]
@pharish93 Have you solved this problem?

**Comment by pharish93** [comment]
hi @sxjscience  sorry for the delay 
got held up with other work . I'll provide you updates soon

**Comment by pharish93** [comment]
@sxjscience  I was running the program overnight with increased workspace size ( 4096 ). It hasn't crashed yet . 
If it does, I would give you an update

**Comment by pharish93** [comment]
1. I couldn't repeat the issue after changing the work space size to 4096, 
I have run it for about 1.5 days now , 
2.  https://github.com/pharish93/FaceDetection/tree/code_restructure 
 is the code I was working on ... Face_3D_Models/face_3d/symbol/ gives the symbols file
