### ISSUE TITLE
How to integrate mxnet with reticulate in R

### ISSUE THREAD

**Issue by harryprince** [apache/incubator-mxnet#9691]
in R, we can use `library(mxnet)` or `mx <– reticulate::import("mxnet")`.

I am trying to leverage reticulate's power like `gluon`, however, when I try to mixture these two types of code, it tells me Rcpp object can't integrate with Python object. I am seeking tensorboard or visualDL to viz the training result~~

**Comment by ankkhedia** [comment]
@harryprince  we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels

- How To
- Question
- R
and close the issue.

@harryprince  if done in error please reopen and comment
