### ISSUE TITLE
distribute training failure about van error

### ISSUE THREAD

**Issue by tonnywang** [apache/incubator-mxnet#9695]
Hi, all,
I met an issue about van error when I tried to run distribute training, 2 machines, 3 gpus per node.
The error message is as the below.
Traceback (most recent call last):
  File "train_end2end.py", line 195, in <module>
    main()
  File "train_end2end.py", line 192, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 154, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/home/mxnet/mxnet-1.0/python/mxnet/module/base_module.py", line 466, in fit
    optimizer_params=optimizer_params)
  File "/home/mxnet/mxnet-1.0/example/rcnn/rcnn/core/module.py", line 173, in init_optimizer
    force_init=force_init)
  File "/home/mxnet/mxnet-1.0/python/mxnet/module/module.py", line 499, in init_optimizer
    _create_kvstore(kvstore, len(self._context), self._arg_params)
  File "/home/mxnet/mxnet-1.0/python/mxnet/model.py", line 82, in _create_kvstore
    kv = kvs.create(kvstore)
  File "/home/mxnet/mxnet-1.0/python/mxnet/kvstore.py", line 655, in create
    ctypes.byref(handle)))
  File "/home/mxnet/mxnet-1.0/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:30:33] src/van.cc:63: Check failed: !ip.empty() failed to get ip

What is the reason about this issue, moreover what are the environment variables setting for distribute training based on Ethernet communication.

**Comment by anirudhacharya** [comment]
@tonnywang Please share your environment and installation details. Also share steps and code to reproduce the error.

@sandeep-krishnamurthy Please add the labels - Python, Pending Requester Info.

**Comment by whu-lyh** [comment]
@tonnywang  hi ,i meet the same trouble. i want to know whether you had solve this  problem. i use three machines with GPU memory size is 4G, and mxnet(1.2.0) complied from sources using command scripts like : make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda-9.0 USE_CUDNN=1 USE_DIST_KVSTORE=1.
Looking forward to receive your reply thanks!

**Comment by whu-lyh** [comment]
@anirudhacharya  @sandeep-krishnamurthy Looking forward to getting your help too~

**Comment by lanking520** [comment]
@tonnywang @whu-lyh This looks weird. Could you please try with the pre-cooked pip package and test it? Apart from that, out native engine currently suffered about multi-threading processing on a single machine.

**Comment by ankkhedia** [comment]
@tonnywang @whu-lyh Did you try using the pip package to solve the issue? Were you able to get any success around it?

**Comment by nswamy** [comment]
closing due to no response from the user.
