### ISSUE TITLE
warpctc: module object has no at tribute 'WarpCTC'

### ISSUE THREAD

**Issue by Mendel1** [apache/incubator-mxnet#9696]
I build the mxnet from source and follows the step in [#7002](https://github.com/apache/incubator-mxnet/issues/7002).But I found it works well if I use python3 but error occurred for python2----"AttributeError: 'module' object has no attribute 'WarpCTC'"

**Comment by sandeep-krishnamurthy** [comment]
@Mendel1 - Did you make clean, set right path in config.mk and rebuild mxnet? 
Here is the issue with solution discussed - 
https://github.com/apache/incubator-mxnet/issues/2587 

Please reopen if issue persist.
