### ISSUE TITLE
MXNet pip package installs older version of numpy (1.13)

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#9699]
MXNet pip package installs numpy (<=1.13). We need to test and upgrade to the latest (1.14).
Some of the issues users can face:
1. Have an conda environment - with numpy, scipy etc. which is usually done by a DL practitioner.
2. Do pip install mxnet in the environment. This installs numpy 1.13.

Later user will fall into the following issue:

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
```

due to conflicting versions of Numpy.

**Comment by sandeep-krishnamurthy** [comment]
@szha - any suggestion on how to proceed further?

**Comment by szha** [comment]
Because of the version requirement, the environment should have rolled back the version of numpy. Why would it still cause the version problem?

**Comment by sandeep-krishnamurthy** [comment]
This issue occurs, when I create a conda environment with numpy and later in the environment, I install mxnet via pip. Issue seems to be mxnet pip package is not uninstalling and reinstall a different version of Numpy.

**Comment by szha** [comment]
Does conda allow multiple versions of the same package in the same environment?

**Comment by 0x1997** [comment]
No. Is there any trouble upgrading mxnet to use numpy 1.14?

**Comment by szha** [comment]
There shouldn't be any trouble. On the other hand, it shouldn't cause any trouble with the 1.13 version of numpy in dependencies either, which is why I was asking about it. Would one of you propose a change to update the dependency in master branch?

**Comment by sensharma** [comment]
This is something I am facing as well. When installing numba and mxnet, mxnet pulls down numpy to 1.13 and breaks numba compiled against numpy 1.14. Using the --upgrade and --upgrade-strategy="only-if-needed" with pip install still pulls down numpy to 1.13 and breaks numba. The workaround I have found is to use the --no-deps flag with pip install when installing mxnet. mxnet then happily uses numpy 1.14. The dependency tested and updated to np 1.14 would be great to have.

**Comment by leleamol** [comment]
The PR implementing the upgrade of numpy is merged. Can this issue be closed. @sandeep-krishnamurthy
