### ISSUE TITLE
Can't run mx.nd.smooth_l1

### ISSUE THREAD

**Issue by zhaodongsun** [apache/incubator-mxnet#9703]
## Description
(Brief description of the problem in no more than 2 sentences.)
Can't run mx.nd.smooth_l1

## Environment info (Required)
----------Python Info----------
Version      : 3.5.2
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('v3.5.2:4def2a2901a5', 'Jun 25 2016 22:18:55')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : C:\Users\67009\AppData\Local\Programs\Python\Python35\lib\site-packages\pip
----------MXNet Info-----------
Version      : 1.0.0
Directory    : C:\Users\67009\AppData\Local\Programs\Python\Python35\lib\site-packages\mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.16299-SP0
system       : Windows
node         : DESKTOP-NRACBB8
release      : 10
version      : 10.0.16299
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Name
Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

----------Network Test----------
Setting timeout: 10
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0393 sec, LOAD: 1.9675 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0338 sec, LOAD: 1.6308 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0321 sec, LOAD: 0.4048 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.2478 sec, LOAD: 1.1301 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0341 sec, LOAD: 1.5128 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0072 sec, LOAD: 1.3811 sec.

## Build info (Required if built from source)
N/A

## Error Message:
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    b=mx.nd.smooth_l1(a)
  File "<string>", line 48, in smooth_l1
  File "C:\Users\67009\AppData\Local\Programs\Python\Python35\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
OSError: [WinError -529697949] Windows Error 0xe06d7363

## Steps to reproduce

```
a=mx.nd.array([5,9,4])
b=mx.nd.smooth_l1(a)
```

**Comment by ZiyueHuang** [comment]
Seems that `scalar` parameter is omitted, please refer to the documents.

`b=mx.nd.smooth_l1(a, scalar=1)`

It works fine for me on ubuntu.

**Comment by zhaodongsun** [comment]
Your answer solved my problem. Thanks.

**Comment by karan6181** [comment]
@sandeep-krishnamurthy Can you please add this label and also close the issue as it's resolved.
- MXNet
- NDArray

Thanks!
