### ISSUE TITLE
what will happen if one of the node reboot when doing the distribute training?

### ISSUE THREAD

**Issue by GoodJoey** [apache/incubator-mxnet#9709]
if i 'm doing the distribute training, supposed one of my node is rebooted(or 'dead' for some other reasons), what will happen? the training will fail? or it will find another node(if there is any) instead?

**Comment by piiswrong** [comment]
All other nodes will stall.
Restart is not supported yet.

**Comment by GoodJoey** [comment]
got it, thanks.
