### ISSUE TITLE
If a relu layer can be shared by more than one convolution layers in mxnet

### ISSUE THREAD

**Issue by gaosanyuan** [apache/incubator-mxnet#9710]
If a relu layer can be shared by more than one convolution layers in mxnet.

**Comment by piiswrong** [comment]
relu layer doesn't have and parameter, so sharing it doesn't make sense. Please create a new one each time

**Comment by spidyDev** [comment]
@sandeep-krishnamurthy  Please close this issue, as this is already answered.
