### ISSUE TITLE
Is it possible to support 5-dim or x-dim data operation

### ISSUE THREAD

**Issue by dwSun** [apache/incubator-mxnet#9711]
Presently, we are use 4-dim data flow to build most of our models, **BatchSize x W x H x Channels** or **BatchSize x Channels x H x W**.

Is it possible to build 5-dim data flow? Maybe **BatchSize x Capsule x W x H x Channels**, which should be useful in ideas like CapsNet for that we don't have to reshape out data. So we can build high dimensions models which are more complicated and should be better both in structure and data extraction performance. 

According to **MobileNetV2**, performance of relu  is better in high dimensions than in low dimensions. So it maybe even more better if we can build our entire model with high dimensions operations. 
Further more, how about 6-dim or 7-dim operations, even x-dim operations?

Is this kind of operations possible? If possible, how hard will it be to implement them?

**Comment by Godricly** [comment]
5 dim version is ok. I already implemented Capsule with MxNet. You can refer to mine. But printting ndarray of high dim is not supported. Gluon is very friendly if you want to have a try.

**Comment by Roshrini** [comment]
@dwSun Please use discuss.mxnet.io forum for usability questions like this to get quicker answer and get a larger audience involved. 

@sandeep-krishnamurthy Can you add label
- Question and close the issue
