### ISSUE TITLE
Caffe converter shortcomings with Crop, Eltwise, Slice layers

### ISSUE THREAD

**Issue by drkoller** [apache/incubator-mxnet#9720]
I am converting network models from Caffe to MXNet using the `convert_symbol.py` conversion tool. The tool fails to properly convert several types of layers:

1) Caffe Crop layer: the converter ignores the "offset" parameters, and sets "center_crop=TRUE". Caffe crop does not do crop-to-center, even when no offset parameters are specified. Rather, Caffe defaults to offset values of zero (crop-to-corner).

2) Caffe Eltwise layer: the converter ignores the "operation" parameter, and converts any Eltwise layer to `mx.symbol.broadcast_add`, even though the Caffe operation may be `PROD` or `MAX`.

3) Caffe Slice layer: unsupported by the converter.

**Comment by nihilityworld** [comment]
Do you solve it ?

**Comment by vandanavk** [comment]
@drkoller Could you share the model with which you saw this issue? And any other script/data that you used, would be helpful.

**Comment by szha** [comment]
We are deprecating caffe converter
