### ISSUE TITLE
symbol logistic regression 'acc' metric stuck on training

### ISSUE THREAD

**Issue by yifeim** [apache/incubator-mxnet#9725]
## Description

With symbol modules, the training accuracy indicator seems unchanged, yet the true accuracy does improve. The problem goes away if a custom eval_metric is provided.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.4
Compiler     : GCC 7.2.0
Build        : ('default', 'Jan 16 2018 18:10:19')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.0.0
Directory    : /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet
Commit Hash   : 9ef196909ec7bf9cdda66d5b97c92793109798e1
----------System Info----------
Platform     : Linux-4.4.0-1049-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-18-237
release      : 4.4.0-1049-aws
version      : #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0013 sec, LOAD: 0.4517 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0006 sec, LOAD: 0.0210 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0003 sec, LOAD: 0.0482 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0003 sec, LOAD: 0.1803 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0094 sec, LOAD: 0.0403 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0003 sec, LOAD: 0.0551 sec.
```

Package used (Python/R/Scala/Julia):
I'm using Python.

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

[mxnet-issue.zip](https://github.com/apache/incubator-mxnet/files/1701492/mxnet-issue.zip)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Provided both html snapshot and ipynb file.

## What have you tried to solve it?

1. Use custom eval_metric seemed to solve the problem. However, it is still useful to find the original cause to be on the safe side.

**Comment by ankkhedia** [comment]
@yifeim  we handle questions via discuss.mxnet.io and not issues. Please file your question there.

@sandeep-krishnamurthy Please add the labels

- Question
- Metric

and close the issue.
@yifeim if done in error please reopen and comment
