### ISSUE TITLE
Factorization Machine can't run

### ISSUE THREAD

**Issue by ningyuwhut** [apache/incubator-mxnet#9732]
I run train.py in the example/sparse/factorization_machine dir.and I met the error:

Traceback (most recent call last):
  File "train.py", line 81, in <module>
    train_data = mx.io.LibSVMIter(data_libsvm=args.data_train, data_shape=(num_features,),
AttributeError: 'module' object has no attribute 'LibSVMIter'

my mxnet version is 0.110, is this a version problem? and how can I solve it?

Thanks!

**Comment by ZiyueHuang** [comment]
You can try a higher version of mxnet, such as 1.0.0. For installation, you can refer to https://mxnet.incubator.apache.org/install/index.html.

**Comment by ningyuwhut** [comment]
@ZiyueHuang  Thanks for replying. I finally found my mxnet version is too old  as  the LibSVMIter is added in version 0.120 (https://github.com/apache/incubator-mxnet/releases)
