### ISSUE TITLE
BUG in MultiBoxTargetForward when there is single box label

### ISSUE THREAD

**Issue by daleydeng** [apache/incubator-mxnet#9733]
There was a constraint on num_label in MultiBoxTargetForward function at multibox_target.cu:359 which will cause error when input label has only one box, is it safe to remove it?

PS: cpu version multibox_target.cc has no such constraint.

template<typename DType>
inline void MultiBoxTargetForward(const Tensor<gpu, 2, DType> &loc_target,
                           const Tensor<gpu, 2, DType> &loc_mask,
                           const Tensor<gpu, 2, DType> &cls_target,
                           const Tensor<gpu, 2, DType> &anchors,
                           const Tensor<gpu, 3, DType> &labels,
                           const Tensor<gpu, 3, DType> &cls_preds,
                           const Tensor<gpu, 4, DType> &temp_space,
                           const float overlap_threshold,
                           const float background_label,
                           const float negative_mining_ratio,
                           const float negative_mining_thresh,
                           const int minimum_negative_samples,
                           const nnvm::Tuple<float> &variances) {
  const int num_batches = labels.size(0);
  const int num_labels = labels.size(1);
  const int label_width = labels.size(2);
  const int num_anchors = anchors.size(0);
  const int num_classes = cls_preds.size(1);
  CHECK_GE(num_batches, 1);
  CHECK_GT(num_labels, 2); // here
  CHECK_GE(num_anchors, 1);
  CHECK_EQ(variances.ndim(), 4);

error logged as follows:
(1, 3318, 4)  # anchor
[[[ 1.          0.1032258   0.01        0.88387096  0.41333333]]] #input box label
<NDArray 1x1x5 @gpu(0)> (1, 6, 3318) # cls_pred
[14:31:57] /home/vision/miniconda3/conda-bld/mxnet_1514016712864/work/dmlc-core/include/dmlc/./logging.h:308: [14:31:57] src/operator/contrib/multibox_target.cu:359: Check failed: num_labels > 2 (1 vs. 2)

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy  Could you please tag it as 
- Bug
- Question
- C++

**Comment by indhub** [comment]
@zhreshold Thoughts?

**Comment by ddavydenko** [comment]
This seems to be related to the functionality of MXNet backend itself and doesn't pertain to C++ API package. @sandeep-krishnamurthy , could you please update this issue and change its labels: remove "C++" and add "Backend"? Thank you!

**Comment by apeforest** [comment]
@sandeep-krishnamurthy @nswamy This issue is fixed. Please close it. Thanks!

**Comment by piyushghai** [comment]
@lanking520 Can you please close this issue, as suggested by @apeforest that the issue is now fixed and merged.

@daleydeng Please feel free to re-open if you still face the issue. 

Thanks!

**Comment by lanking520** [comment]
@daleydeng Close this issue for now. Please feel free to reopen it if the issue persist.

**Comment by xiaoqihe** [comment]
now, this bug appear in python mxnet-cu80==1.3.1, can you check it?

**Comment by zhreshold** [comment]
@xiaoqihe 1.3.1 was released before this fix, so please wait for the next release or try nightly build instead.
