### ISSUE TITLE
Feature request: please translate zh.gluon.ai in English

### ISSUE THREAD

**Issue by feevos** [apache/incubator-mxnet#9742]
Dear all, 

there is a great deal of information in the [Chinese version of the gluon page](https://zh.gluon.ai/), google translator loses various English numbers when they are intermixed with Chinese characters and makes reading problematic (sometimes messes up code parts as well). Could please someone translate?

**Comment by astonzhang** [comment]
Thanks. Will do.

**Comment by TaoLv** [comment]
It says there is a English version here: http://gluon.mxnet.io/. But maybe there are some differences between these two versions.

**Comment by feevos** [comment]
Thank you @astonzhang !! @TaoLv  there are significant differences  (according to my humble opinion -e.g. in Computer Vision).

**Comment by TaoLv** [comment]
@feevos To translate the whole tutorial would be a long-term work. So if you have some questions on a specific chapter right now, you can put it here. Maybe we can help.

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy Can you please add labels:
Feature Request,
Doc

**Comment by ThomasDelteil** [comment]
available here: http://d2l.ai
