### ISSUE TITLE
from tensorboard import SummaryWriter wrong

### ISSUE THREAD

**Issue by qingzhouzhen** [apache/incubator-mxnet#9743]
this file ```https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/contrib/tensorboard.py``` does not work any more,
because new tensorboard does not have a Class named SummaryWrite in writer.py
how could I use tensorboard now?

**Comment by shuokay** [comment]
It's not hard to handle the tensorboard summary with python code,  [here](http://shuokay.com/2018/01/20/deeplabv3/) is an example:
```python
train_writer = SummaryWriter(cfg.train_logdir)
eval_writer = SummaryWriter(cfg.eval_logdir)
train_writer.add_scalar("loss", train_mloss, count)
train_writer.add_scalar("miou", train_miou, count)
eval_writer.add_scalar("loss", eval_mloss, count)
eval_writer.add_scalar("miou", eval_miou, count)
```

**Comment by reminisce** [comment]
`tensorboard` has been changed to refer to the TensorFlow's TensorBoard in PyPI.

**Comment by roywei** [comment]
@sandeep-krishnamurthy please add labels Breaking, thanks!

**Comment by vandanavk** [comment]
@qingzhouzhen Can this issue be closed now since https://github.com/apache/incubator-mxnet/pull/11426 has been merged?
