### ISSUE TITLE
Performance regression when OMP_NUM_THREADS environment variable is not set

### ISSUE THREAD

**Issue by cbalioglu** [apache/incubator-mxnet#9744]
## Affected Versions
- 1.0.0
- 1.1.0.rc0
- 1.1.0.rc1

## Build Options
- USE_OPENMP=ON

## Environments Tested
OS: 
- Amazon Linux 2012.03 (Kernel 4.4.48)
- Amazon Linux 2017.03 (Kernel 4.4.48)

Hardware:
- AWS m4.2xlarge
- AWS c4.2xlarge
- AWS p3.2xlarge

## Impact
The benchmark numbers below are produced by training a symbolic NTM algorithm on a quad core (8 logical cores) Intel Xeon E5-2676 CPU. However the regression is reproducible by running any type of symbolic graph on a CPU context.

OMP_NUM_THREADS | 1.0.0 + GNU OpenMP | 1.0.0 + Intel OpenMP | 1.1.0.rc0 + GNU OpenMP
----------------------|----------------------|----------------------|--------------------------
\- | 75s | 116s | 66s
4 | 65s | 77s | 48s

## Root Cause
The `mxnet::engine::OpenMP` class has already an [implementation](https://github.com/apache/incubator-mxnet/blob/3761f2f36e7e335f17e5c1dcbfe215de27f73fd5/src/engine/openmp.cc#L53) for automatically setting up the optimal number of OpenMP threads in case the `OMP_NUM_THREADS` environment variable is not explicitly set. However this implementation does not completely solve the regression problem as the `omp_set_num_threads` function is thread-local.

The setup logic referred above is only [called](https://github.com/apache/incubator-mxnet/blob/3761f2f36e7e335f17e5c1dcbfe215de27f73fd5/src/engine/openmp.cc#L102) during the static initialization of the `OpenMP` class in the main thread. However the `mxnet::engine::ThreadedEngine` class utilizes OpenMP not only in the main thread but also in worker threads. As `omp_set_num_threads` is never called in these threads, they attempt to use all logical cores for parallelized regions, which causes the regression.

## Solution
The `omp_set_num_threads` function has to be explicitly called in all threads in case the `OMP_NUM_THREADS` environment variable is not set by the user.

## Actions Required
As part of this investigation I already implemented an ad-hoc fix and plan to polish and make it production ready in the upcoming days. At this stage no action is requested from the main contributors.

**Comment by cjolivier01** [comment]
Thank you for the excellent detailed explanation.

Just curious, what is meant by "regression" in this context?  Was there some point in the past where OMP threads were set to optimum in all threads?

Is your solution calling omp_set_num_threads() from CPUWorker?

**Comment by cjolivier01** [comment]
yeah, that's probably the best place for it.  nice work!

**Comment by pengzhao-intel** [comment]
We found the similar issue that the performance will be better when we set OMP_NUM_THREADS.
@cbalioglu good catch!

**Comment by pengzhao-intel** [comment]
@cjolivier01 Thanks for the fix. I have tested in my local with your code.

The OMP_NUM_THREADS issue is fixed, but 10% performance degrade from KMP setting.
Could you help fix this issue too?

Please see my log:

[patric@mlt-skx075 mxnet-reg]$ export KMP_AFFINITY=granularity=fine,noduplicates,compact,1,0
[patric@mlt-skx075 mxnet-reg]$ export OMP_NUM_THREADS=56
[patric@mlt-skx075 mxnet-reg]$ python example/image-classification/benchmark_score.py
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
/home/patric/develop/omp_fix/python/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[23:03:45] src/operator/nn/mkldnn/mkldnn_base.cc:60: Allocate 411041792 bytes with malloc directly
**INFO:root:batch size 128, image/sec: 189.037230**

[patric@mlt-skx075 mxnet-reg]$ unset KMP_AFFINITY
[patric@mlt-skx075 mxnet-reg]$ unset OMP_NUM_THREADS
[patric@mlt-skx075 mxnet-reg]$ python example/image-classification/benchmark_score.py
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
/home/patric/develop/omp_fix/python/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[23:04:20] src/operator/nn/mkldnn/mkldnn_base.cc:60: Allocate 411041792 bytes with malloc directly
**INFO:root:batch size 128, image/sec: 169.450103**

[patric@mlt-skx075 mxnet-reg]$ export OMP_NUM_THREADS=56
[patric@mlt-skx075 mxnet-reg]$ python example/image-classification/benchmark_score.py
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
/home/patric/develop/omp_fix/python/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[23:04:44] src/operator/nn/mkldnn/mkldnn_base.cc:60: Allocate 411041792 bytes with malloc directly
**INFO:root:batch size 128, image/sec: 168.383920**

[patric@mlt-skx075 mxnet-reg]$ export KMP_AFFINITY=granularity=fine,noduplicates,compact,1,0
[patric@mlt-skx075 mxnet-reg]$ python example/image-classification/benchmark_score.py
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
/home/patric/develop/omp_fix/python/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[23:05:10] src/operator/nn/mkldnn/mkldnn_base.cc:60: Allocate 411041792 bytes with malloc directly
**INFO:root:batch size 128, image/sec: 188.962690**

**Comment by cjolivier01** [comment]
I am only vaguely familiar with the KMP stuff.  Can you please elaborate?  Are you saying that it is slower now in some situations?

**Comment by cjolivier01** [comment]
Are you sauing I should set the environment variable in the code:
KMP_AFFINITY=granularity=fine,noduplicates,compact,1,0
?

**Comment by cjolivier01** [comment]
Can you also explain what these settings do? I know it's in a manual somewhere, but from your perspective, what does it do and why is that best?

**Comment by pengzhao-intel** [comment]
Thanks, @cjolivier01,  I mean we set this environment in the code as OMP_NUM_THREADS.

Actually, this setting is useful when hyperthreading is ON and we only want to run each thread in a physical core as below picture shown (KMP_AFFINITY=granularity=fine,compact,1,0).

So, this environment will guide how to map thread into the physical core.
https://software.intel.com/en-us/node/522691


![guid-80fda344-d8c1-4fea-b268-94f685d19c4c-imageid 0abe3e2e-7a5a-4072-b22f-da7f72eb9a18](https://user-images.githubusercontent.com/22461308/36572333-23cebc60-1876-11e8-9fa8-11004a562ca8.jpg)
**KMP_AFFINITY=granularity=fine,compact,1,0**

**Comment by cjolivier01** [comment]
how to set this programmatically? i’d imagine that by the time this code
executes, the omp library may have already checked the environment variable
(as it does with OMP_NUM_THREADS)? or can it be set at any time?

**Comment by pengzhao-intel** [comment]
Normally, we set KMP_AFFILITY with OMP_NUM_THREADS together. 
And when the OMP threads are invoked, it will be used.

**Comment by cjolivier01** [comment]
i don’t set the environment variable. I doubt it would
work even if i did, from within the code. So there’s nothing I can do,
then, right? User would need to set?

I recall dumping the default behavior of KMP and i remember it showing that
the OMP threads were indeed staggered as in your picture.  I’ll check again.

**Comment by pengzhao-intel** [comment]
There're C level API too, _int kmp_set_affinity_ in openmp.
Also in this page:
https://software.intel.com/en-us/node/522691

**Comment by pengzhao-intel** [comment]
@cjolivier01 how about the progress of KMP setting? 
We prefer this can be merged into release 1.2 so that the user can get the best performance by default.

**Comment by billy19murahmi** [comment]
@pengzhao-intel I've never used "noduplicates" in KMP_AFFINITY settings. Wondering what this does? I couldn't find the explanation in the [documentation](https://software.intel.com/en-us/node/522691).

**Comment by lebeg** [comment]
Possibly related https://github.com/apache/incubator-mxnet/pull/12160

**Comment by chenliu0831** [comment]
Hi, is there any other action items remaining for this issue? I wonder if we don't have to explicitly set  `OMP_NUM_THREADS` after 1.2.0 release. Thanks
