### ISSUE TITLE
test_score.py in example\image classification error in list_gpus

### ISSUE THREAD

**Issue by shirishr** [apache/incubator-mxnet#9746]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Running python test_score.py results in following (although gpu with cuda 8.0 exists:

Traceback (most recent call last):
  File "test_score.py", line 56, in <module>
    assert len(gpus) > 0
AssertionError

## Environment info (Required)
Windows10, CUDA 8.0, MXNET==1.0.0
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)
Python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1. When I run train_mnist.py --gpus 0 it successfully runs and GPU load is seen
2.

**Comment by shirishr** [comment]
Added log from diagnose.py:

----------Python Info----------
Version      : 3.6.3
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('default', 'Nov  4 2017 10:10:42')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : C:\Anaconda3\envs\mxnet-vc14\lib\site-packages\pip
----------MXNet Info-----------
Version      : 1.0.0
Directory    : C:\Anaconda3\envs\mxnet-vc14\lib\site-packages\mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.17074-SP0
system       : Windows
node         : CRUNCH
release      : 10
version      : 10.0.17074
----------Hardware Info----------
machine      : AMD64
processor    : AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
ERROR:
Description = Exception occurred.
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0469 sec, LOAD: 1.8281 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1719 sec, LOAD: 0.1562 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.2501 sec, LOAD: 1.3744 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0781 sec, LOAD: 0.2657 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0312 sec, LOAD: 0.1876 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0313 sec, LOAD: 0.1719 sec.

**Comment by anirudh2290** [comment]
Please check if nvidia-smi is in your path. This won't work on windows if its not in your path.

**Comment by shirishr** [comment]
You are so right sir...I had created an environment variable called 'nvidia-smi' :o(
After adding nvidia-smi to the path it's running now. Thank you !!
