### ISSUE TITLE
Any ideas how to implement Z-Buffer algorithm?

### ISSUE THREAD

**Issue by ShownX** [apache/incubator-mxnet#9750]
Z-Buffer algorithm is described in this document: http://graphics.idav.ucdavis.edu/education/GraphicsNotes/Z-Buffer-Algorithm.pdf

Since it requires a for loop, and assign values to an extra array (buffer), I cannot find any operations to implement this algorithm. Any ideas?

**Comment by anirudh2290** [comment]
This seems more like Q&A/discussion topic. Please ask on discuss.mxnet.io.

**Comment by sandeep-krishnamurthy** [comment]
Resolving here.
@ShownX as Anirudh mentioned, please ask this query at - https://discuss.mxnet.io/
