### ISSUE TITLE
Can't select mxnet version on the website due to html rendering

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#9751]
As seen on the screenshot, I can't see the version dropdown when the page is not rendered wide enough.

<img width="1280" alt="screen shot 2018-02-09 at 11 57 52" src="https://user-images.githubusercontent.com/928489/36024631-9d5ce3f4-0d90-11e8-96d6-27ac9f61b719.png">

**Comment by larroy** [comment]
Same with firefox, btw.

**Comment by srochel** [comment]
the "+" sign is not working or not intuitive enough?

**Comment by larroy** [comment]
I guess is not intuitive enough, should be separated or better "..." I was not the only one in the room looking at this.

**Comment by piiswrong** [comment]
I agree.
a `...`  button close to Discuss (instead of search box) would look better

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy please add the labels - Website.

**Comment by sandeep-krishnamurthy** [comment]
This issue is resolved with new "Versions" dropdown.
