### ISSUE TITLE
Make fail for MXNET

### ISSUE THREAD

**Issue by p31415926** [apache/incubator-mxnet#9753]
I can't successfully  run make command for my MXNET.
The error as below 

/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:428: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:450: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

diagnose.py output: 

----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Dec  4 2017 14:50:18'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-4.4.0-1049-aws-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('node         :', '86c0e7605169')
('release      :', '4.4.0-1049-aws')
('version      :', '#58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2699.625
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.08
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0007 sec, LOAD: 1.2022 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0004 sec, LOAD: 0.1241 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0003 sec, LOAD: 0.1893 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0003 sec, LOAD: 0.1575 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0004 sec, LOAD: 0.0037 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0004 sec, LOAD: 0.0117 sec.

**Comment by anirudh2290** [comment]
What is the value of USE_BLAS set to, in config.mk ?

**Comment by p31415926** [comment]
ADD_LDFLAGS= -I/opt/OpenBLAS/lib
ADD_CFLAGS = -I/opt/OpenBLAS/include
USE_BLAS = openblas
 solved issues.

**Comment by KellenSunderland** [comment]
I usually create a softlink from openblas to blas.  Should be something like 
```bash
ln - s /usr/lib/libopenblas.so /usr/lib/libcblas.so
```

**Comment by vdantu** [comment]
@sandeep-krishnamurthy : This issue was resolved. Tag it to label "Installation" "question"
