### ISSUE TITLE
R-CNN proposal layer supports only single image batches

### ISSUE THREAD

**Issue by batracos** [apache/incubator-mxnet#9754]
https://github.com/apache/incubator-mxnet/blob/d2a856a3a2abb4e72edc301b8b821f0b75f30722/src/operator/contrib/proposal.cc#L292

@zhreshold, why is this necessary? Is it because of the RoI Pooling layer later on?

**Comment by lupesko** [comment]
@batracos we try to handle questions via the [Discuss Forum](https://discuss.mxnet.io/), not via issues.
Alternatively, you can comment your question on the commit [#5499](https://github.com/apache/incubator-mxnet/pull/5499), although it was closed a while back.

@sandeep-krishnamurthy please label:
- C++
- Question
And please close the issue.

@batracos if done in error please re-open and comment.
