### ISSUE TITLE
How can I pad images using mx.nd.pad?

### ISSUE THREAD

**Issue by ascust** [apache/incubator-mxnet#9760]
I tried to use mx.nd.pad to pad images decoded by mx.image.imdecode. Since the images are a 3d ndarray, I got
"Current implementation only supports 4-D or 5-D input."
Is there any way to pad the images?

**Comment by ShownX** [comment]
reshape to (1, C, H, W)?

**Comment by sandeep-krishnamurthy** [comment]
MXNet supports and is more efficient with channels_first format only. 
Resolving.
For usability question, please ask at - https://discuss.mxnet.io/
