### ISSUE TITLE
Should MXNet also support logical operations?

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#9762]
## Description
It seems MXNet doesn't support logical operations in either symbolic interface or NDArray. Even though MXNet doesn't support the boolean data type, I think it's still necessary to support logical operators, such as the ones below.
https://www.tensorflow.org/versions/r0.12/api_docs/python/control_flow_ops/logical_operators

**Comment by sandeep-krishnamurthy** [comment]
+1
For logical operators in symbolic interface.

**Comment by KellenSunderland** [comment]
+1.  This comes in quite handy for NLP problems where the sequence length is variable.

**Comment by anirudhacharya** [comment]
@zheng-da this issue has been addressed, can you please close this issue
