### ISSUE TITLE
Where to find argument definition with String type

### ISSUE THREAD

**Issue by parallelgithub** [apache/incubator-mxnet#9781]
I would like to transform the following Python to Scala: 
```python
weight = mx.symbol.Variable("linear_weight", shape=(num_linear_features, 2),
                            init=norm_init, stype='row_sparse')
```
It seems like Scala's `Variable` only accept parameters: (**name**: `String`, **attr**: `Map[String, String]`).
How do I make sure the key of **attr** is correct when I assign it into `Map`?
Especially, in above Python code **init** is Initializer, which is not `String` type. I have no idea know how to set it in `attr`.

Another similar issue is about MNIST example.
In this [tutorial](https://github.com/apache/incubator-mxnet/tree/master/scala-package):
```scala
val trainDataIter = IO.MNISTIter(Map(
  "image" -> "data/train-images-idx3-ubyte",
  "label" -> "data/train-labels-idx1-ubyte",
  "data_shape" -> "(1, 28, 28)",
  "label_name" -> "sm_label",
...
```
it use **data_shape** as the key of `Map`.
On the other hand, in this [example code](https://github.com/apache/incubator-mxnet/blob/master/scala-package/examples/src/main/scala/ml/dmlc/mxnetexamples/module/MnistMlp.scala):
```scala
val train = IO.MNISTIter(Map(
  "image" -> (inst.dataDir + "train-images-idx3-ubyte"),
  "label" -> (inst.dataDir + "train-labels-idx1-ubyte"),
  "label_name" -> "softmax_label",
  "input_shape" -> "(784,)",
  "batch_size" -> inst.batchSize.toString,
...
```
it use **input_shape** as the key of `Map`.
The Scala code is auto-generated from C++, where can I find these `String` type argument definition using in `Map`?

**Comment by lupesko** [comment]
For MXNet questions, please use [discuss.mxnet.io](https://discuss.mxnet.io/)
Thanks!

@sandeep-krishnamurthy can you please close?
