### ISSUE TITLE
net.collect_params() omits Dropout layers

### ISSUE THREAD

**Issue by rf987** [apache/incubator-mxnet#9787]
Why does net.collect_params() not make mention of Dropout layers ?

**Comment by szha** [comment]
That's because Dropout layer doesn't have a parameter right now. https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/nn/basic_layers.py#L242-L252
May I ask what you're looking for?

**Comment by rf987** [comment]
When I open old models, I use the string output of net.collect_params() to remind me of what the network architecture was.

**Comment by sxjscience** [comment]
@rf987 You may directly try `print(net)`
