### ISSUE TITLE
Sometime MXDataIter load data quickly, sometime it load data slowly?

### ISSUE THREAD

**Issue by moveforever** [apache/incubator-mxnet#9819]
I have implenmented a DataIter of C++ supporting multi data input. Sometime, usage of cpu loading data is low, that is less than 100%. Sometime, usage of cpu is about 200%~300%, and loading data is quickly.
How to tuning velocity of loading data?
Any help can be appreciated.
@eric-haibin-lin @piiswrong

**Comment by sxjscience** [comment]
According the description, the question is not related to MXNet and should not be raised as a **Github Issue**.  Stackoverflow may be a better place.

**Comment by moveforever** [comment]
@sxjscience ， i implement dataiter supporting multi input inheritated MXDataIter. The people of best kowning workflow of MXNet loading data Module to tune performance is mxnet developer.

**Comment by sxjscience** [comment]
@piiswrong What do you think? I feel this type of problems should not be raised as an issue.

**Comment by eric-haibin-lin** [comment]
I think discuss.mxnet.io is a good place to discuss questions like this. 

How did you implement the data iterator? Usually it’s not a problem if it’s not the bottleneck of your network

**Comment by moveforever** [comment]
My data format of one line is including dense and sparse as followed
![1519619151 1](https://user-images.githubusercontent.com/5248288/36654678-4b27bf2a-1af9-11e8-9e97-52ab41df5289.png)
The first column is label, the second is dense(csv), and the the third is sparse(libsvm).

**Comment by moveforever** [comment]
The test of every step's consuming has been done as followed:
![image](https://user-images.githubusercontent.com/5248288/36654797-d2207dfa-1af9-11e8-98b2-af5977200753.png)
loading data is mainly most consuming time step, that is 90 percent of  one batch update time.

**Comment by moveforever** [comment]
I implement the Iter as followed
![15984851272413857](https://user-images.githubusercontent.com/5248288/36654869-2c65667c-1afa-11e8-81f4-8d6c0cf77188.jpg)
I mainly implement KBIter similar to LibSVMIter. I implement KBIter and KBParser, then mend SparsePrefetcherIter, SparseBatchLoader, and i add some base data structure as followed
 
![image](https://user-images.githubusercontent.com/5248288/36654965-cfd729da-1afa-11e8-820d-d044992a88a7.png)
![image](https://user-images.githubusercontent.com/5248288/36654975-e42a958e-1afa-11e8-9c75-c5ef53fdec94.png)

**Comment by moveforever** [comment]
The network is not complex, and it's only including 5 fully connected hidden layer.
