### ISSUE TITLE
Google index points to old version of install instructions

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#9825]
## Description

![screenshot from 2018-02-19 15-36-47](https://user-images.githubusercontent.com/1753787/36383002-1a4d3dd0-158b-11e8-8fe1-074ce39e7a65.png)

Leads to

![screenshot from 2018-02-19 15-40-00](https://user-images.githubusercontent.com/1753787/36383061-4c876e74-158b-11e8-85de-6a34a5367243.png)

**Comment by aaronmarkham** [comment]
@marcoabreu - this issue was resolved by the redirect to the install page. Please close.
