### ISSUE TITLE
SymbolBlock/HybridBlock do not support multiple inputs from symbol api

### ISSUE THREAD

**Issue by tonytongzhao** [apache/incubator-mxnet#9854]
Just found the current mxnet SymbolBlock/HybridBlock do not support multiple inputs from symbol api model, which blocks the model reuse from previous symbol api to current gluon api. Anyone has suggestions?

**Comment by szha** [comment]
Both block types should already support multiple inputs. Any reason that you think they can't use multiple inputs?

**Comment by tonytongzhao** [comment]
Sorry, just figured it out. My current problem is about the use of SparseEmbedding in symbol api cannot be adopted to symbolblock, showing "mxnet.base.MXNetError: Error in operator sparseembedding0: [22:38:33] src/operator/tensor/./indexing_op.h:199: Not implemented: operator = _contrib_SparseEmbedding". Any suggestions? Thanks.

**Comment by szha** [comment]
This is currently on the roadmap. @eric-haibin-lin can explain more.

**Comment by sxjscience** [comment]
Close because SymbolBlock supports multiple inputs.
