### ISSUE TITLE
Flaky hanging test_operator.test_laop_3

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#9864]
Test times out due to hang.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-9848/1/pipeline

```
test_operator.test_laop_3 ... 
[INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.

Sending interrupt signal to process

Terminated

script returned exit code 143
```

**Comment by marcoabreu** [comment]
@asmushetzel would you like to investigate?

**Comment by pengzhao-intel** [comment]
@marcoabreu we can't reproduce this issue on our side. And NO MKL-DNN OP is used in this test. 
So I suggest removing MKL label.

> (apache)[zhiyuanh@mlt-skx065 incubator-mxnet]$ export MXNET_TEST_SEED=1896893923
> (apache)[zhiyuanh@mlt-skx065 incubator-mxnet]$ export MKLDNN_VERBOSE=1
> (apache)[zhiyuanh@mlt-skx065 incubator-mxnet]$ nosetests --verbose tests/python/unittest/test_operator.py:test_laop_3
> [WARNING] *** module-level seed is set: all tests running deterministically ***
> [INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1896893923 to reproduce.
> [WARNING] *** test-level seed set: all "@with_seed()" tests run deterministically ***
> test_operator.test_laop_3 ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
> ok
> 
> ----------------------------------------------------------------------
> Ran 1 test in 1.969s
> 
> OK

**Comment by vdantu** [comment]
@marcoabreu : 

I wasn't able to reproduce this issue. Am I doing anything wrong? Is it possible to know when this test last failed? 

# Environment
Tried running on: Python 3.6.4

Build command: cmake -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_MKLDNN=ON .. && make -j 4

EC2 instance: C5.4xlarge

# Test Output
## Single test run
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=116898012 to reproduce.
test_operator.test_laop_3 ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
ok

----------------------------------------------------------------------
Ran 1 test in 1.784s

OK

## Multiple count test run
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be t\
reated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1436798750 to reproduce.
test_operator.test_laop_3 ... [INFO] 1 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 2 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 3 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 5 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 6 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 7 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 8 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 9 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 10 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 11 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 12 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 13 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 14 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 15 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 16 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 17 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 18 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 19 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 20 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
......
......
[INFO] 4218 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4219 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4220 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4221 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4222 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4223 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4224 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4225 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4226 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4227 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4228 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4229 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4230 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
[INFO] 4231 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1896893923 to reproduce.
....
....

**Comment by marcoabreu** [comment]
I think it was related to some dependency version that had a bug which misinterpreted the underlying CPU name and then ran a kernel that didn't work.
@kellensunderland do you remember details?

**Comment by vdantu** [comment]
@marcoabreu @KellenSunderland : Please suggest how we could go about narrowing this down and resolve this.

**Comment by vdantu** [comment]
Any suggestions on how to go about with recreating this issue or if I am missing something in my tests.

**Comment by marcoabreu** [comment]
Let's close this for now. It was a very specific case in which it failed related to some dependencies.

Thanks for following up!
