### ISSUE TITLE
A bug in an example in the python API document

### ISSUE THREAD

**Issue by dotelos** [apache/incubator-mxnet#9872]
This is an example found in the doc for [mxnet.autograd.Function](https://mxnet.incubator.apache.org/api/python/autograd.html#mxnet.autograd.Function).
```python
class sigmoid(Function):
    def forward(self, x):
        y = 1 / (1 + mx.nd.exp(-x))
        self.save_for_backward(y)
        return y

    def backward(self, dy):
        # backward takes as many inputs as forward's return value,
        # and returns as many NDArrays as forward's arguments.
        y, = self.saved_tensors
        return y * (1-y)
```
The `backward` method should return `dy * y * (1-y)` instead of `y * (1-y)` according to the chain rule.

**Comment by dotelos** [comment]
@sxjscience Please fix the example in the doc. https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/autograd.py#L375

**Comment by sxjscience** [comment]
Sorry for not submitting the fix.
