### ISSUE TITLE
ResNet-50 is slower on Volta since #8302 

### ISSUE THREAD

**Issue by Caenorst** [apache/incubator-mxnet#9874]
## Description
I ran the Minimum reproducible example with the setup below at two different version (before and after #8302): 
Here are the results:
d03182f4fc084741ea185aac2eb02d0e7b4151f9 (before #8302):
    - real data: 5644 samples / s
    - synthetic data: 5971 samples / s
c3e3a832bfeceff070ba263aa8a4489ca27f452e (after #8302):
    - real data: 5461 samples / s
    - synthetic data: 5740 samples / s
Latest:
    - real data: 5425 samples / s
    - synthetic data: 5817 samples / s

@ptrendx @DickJC123 @mkolod 

## Environment info (Required)
CPUs: Intel Xeon E5-2698 v4 (x2)
GPUs: Nvidia V100 (x8)

## Build info (Required if built from source)
From the default config.mk (in make/config.mk) added:
```
USE_CUDA=1
USE_CUDNN=1
CUDA_ARCH := -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70
USE_CUDA_PATH=/usr/local/cuda
USE_LIBJPEG_TURBO=1
USE_LIBJPEG_TURBO_PATH=/usr
USE_NCCL=1
```

## Minimum reproducible example
```
python /mxnet/example/image-classification/train_imagenet.py --benchmark 0 --gpu 0,1,2,3,4,5,6,7 --batch-size 1024 --num-epochs 1 --data-train /data/imagenet/train-480-val-256-recordio/train.rec --data-train-idx /data/imagenet/train-480-val-256-recordio/train.idx --data-val /data/imagenet/train-480-val-256-recordio/val.rec --disp-batches 100 --network resnet-v1 --num-layers 50 --data-nthreads 40 --min-random-scale 0.533 --max-random-shear-ratio 0 --max-random-rotate-angle 0 --max-random-h 0 --max-random-l 0 --max-random-s 0 --dtype float16 --kv-store device
```

**Comment by lupesko** [comment]
@piiswrong @zheng-da - please take a look, this degradation may be related to your commit.

**Comment by rahul003** [comment]
Are the speeds that you mention averages? If so, averaged over how many batches?

**Comment by cjolivier01** [comment]
@zheng-da

**Comment by zheng-da** [comment]
I think I may know what is the potential cause of this problem. I'll fix it next week.

**Comment by cjolivier01** [comment]
Is it know what part of the commit is the problem?
Are the performance characteristics of thread_local known for the supported platforms?

**Comment by zheng-da** [comment]
@Caenorst can you test it again? I measured the perf on p3. The PR https://github.com/apache/incubator-mxnet/pull/10116 should improve the perf by about 3% for your test case.

**Comment by vandanavk** [comment]
@Caenorst did @zheng-da's PR improve the performance on your setup?

**Comment by vrakesh** [comment]
@Caenorst Has the performance, loss been negated post @zheng-da 's PR? If so requesting to close the issue.

**Comment by kalyc** [comment]
@lanking520 requesting to close this issue due to lack of activity

**Comment by lanking520** [comment]
@Caenorst Please feel free to reopen this issue if you are still facing this failure. Close it for now.
