### ISSUE TITLE
UTF-8 Support for Text Parsers

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#9891]
Please see: https://github.com/dmlc/dmlc-core/issues/372

**Comment by anirudhacharya** [comment]
@sandeep-krishnamurthy can you please add the following labels to this issue - cpp package, discussion, exploration.

**Comment by anirudh2290** [comment]
Closing this since the parsers only parse numbers for CSV, libsvm and libfm.
UTF-8 support not required at this point in time.
