### ISSUE TITLE
The different between rescale_grad on optimizer and normalization in loss layer.

### ISSUE THREAD

**Issue by huyangc** [apache/incubator-mxnet#9911]
When I normalization the gradient of the SoftmaxOutput using ``normalization=valid``, and setting the ``rescale_grad=1/batchsize``, it seems like that  the gradient will be rescale twice?  First is using the number of valid label and second using the batchsize?

**Comment by feiyuvl** [comment]
Yes， it will rescale twice

**Comment by huyangc** [comment]
orz, if so, I think it is a little hard to just rescale some specific layers' gradient.

**Comment by sad-** [comment]
@huyangc could you close the issue if you question is answered? or ask a specific follow up question if you have one. thanks
