### ISSUE TITLE
Our FCN-xs result on Pascal VOC Validation

### ISSUE THREAD

**Issue by shipeng-uestc** [apache/incubator-mxnet#9915]
Hi, all.@lupesko
@sandeep-krishnamurthy
I want to know the result by use our fcn-xs to train on pasacl voc dataset.
The IoU on validation dataset?
Thanks.I am looking forward to your reply.

**Comment by thomelane** [comment]
@shipeng-uestc Are you referring to the example [here](https://github.com/apache/incubator-mxnet/tree/master/example/fcn-xs)? When running the script you should be able to see the validation loss logged after every epoch. It will depend on the specific model you've selected though.

**Comment by ThomasDelteil** [comment]
The accuracy of the FCN models offered on Gluon-CV are reported here:
https://gluon-cv.mxnet.io/model_zoo/index.html#semantic-segmentation


Name | Method | pixAcc | mIoU | Command | log
-- | -- | -- | -- | -- | --
fcn_resnet50_voc | FCN [6] | N/A | 69.4 | shell script | log
fcn_resnet101_voc | FCN [6] | N/A | 70.9 | shell script | log

@indhub  can we please close this question? Thanks!
