### ISSUE TITLE
404 Error on website

### ISSUE THREAD

**Issue by dabraude** [apache/incubator-mxnet#9917]
When navigating:
Docs-> Architecture -> MXNet System Overview
Trys to go to:
https://mxnet.incubator.apache.org/versions/1.1.0/architecture/overview.html

and gets a 404 error

**Comment by marcoabreu** [comment]
Thank you for reporting this. There seems to be a problem with the links in general.

https://mxnet.incubator.apache.org/versions/0.12.1/architecture/index.html for example, links to the main version.

**Comment by dabraude** [comment]
seems to be working now
