### ISSUE TITLE
[DISCUSSION] module.contrib.SparseModule API

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9921]
As of now, the only way to train a model with sparse operators is using the Module API (sparse support for Gluon API not ready yet). However, the existing Module API is not a good fit for training sparse models with KVStores present. This thread discusses how to provide a user-friendly module API for sparse symbols, which serves as a guideline before the feature is added into Gluon.

## Why the current Module API is not a good fit
Currently, if a module has KVStore present, it performs the following steps for each batch:
```python
for batch in batches:
    mod.forward(batch)
    mod.backward(batch)
    mod.update() which calls the following kvstore APIs
        # kvstore.push(grad) which aggregates & applies the gradients from the current batch
        # kvstore.pull(weight) which broadcast updated weights to all devices
```
This is not ideal for models w/ sparse operators because it is not necessary to broadcast full weights. Instead, only a subset of the weights are useful for the computation when data is sparse. 

Here is an example:
Let's say input `X` is has 100,000 features, where each sample only has around 10 non-zeros features. If the model computes `dot(X, W)`, not all rows in `W` are used for the computation. In fact, if `W` only contains the rows corresponding to the non-zero features in `X`, the result of `dot` is exactly the same compared to a `dot(X, W)` w/ full(dense) `W`. 

Avoiding the communication of these full(dense) weight/gradient is essential when one tries to scale the training over multiple machines and multiple devices. 

Therefore, we want to re-order the loop and do something like the following:
```python
for batch in batches:
    kvstore.row_sparse_pull(sparse_weight, useful_rows_for_this_batch) 
    kvstore.pull(dense_weights)
    mod.forward(batch)
    mod.backward(batch) 
    mod.update()
        # kvstore.push(grad) 
```
With the module API, one must access private members of module such as `_exec_group` and `_params_dirty` and interact with kvstore directly to achieve the above like this [example](https://github.com/eric-haibin-lin/mxnet/blob/lstmp/example/sparse/linear_classification/train.py#L97-L98). We need a module API that abstracts these away and make it more user-friendly. 

## contrib.SparseModule API
Modifying the existing module API to support this may over complicate the code and make it hard to maintain. On the other hand, a new SparseModule API is a chance to educate MXNet users who already have some experience with the Module API. I propose the following SparseModule API: 

### class SparseModule(Module)

A Module that wraps a network with sparse symbols.
The module provides abstraction for data parallel distributed training with "row sparse" weights,
supporting two types of communications: update_on_kvstore=True and update_on_kvstore=False.
Distributed training includes both multi-device and multi-machine training.

- update_on_kvstore=True
    Full parameters are stored in KVStore.
    For each data batch, only broadcast the subset of "row sparse" weights that are required for the computation,
    according to the row ids provided.
    Usually the row ids correspond to features that appear in the batch.
    
    Specifically, for each batch of data,
    sparse weights are broadcast to all devices/machines based on row ids.
    Each device/machine then computes forward/backward with sparse weights.
    Finally, gradients are reduced from all devices/machines and applied on the parameters stored in KVStore.

- update_on_kvstore=False
    Full parameters are stored and duplicated on each machine/device.
    For each data batch, compute forward/backward with full weights.
    Then gradients are then broadcast to all other devices/machines.
    Each device/machine applies the gradient to the copy of the parameters it holds.

Take the following linear network as an example:
```python
 data = mx.sym.var('data', stype='csr')
 label = mx.sym.var('label')
 weight = mx.sym.var('w0', shape=(1000,1), stype='row_sparse')
 bias = mx.sym.var('b0', shape=(1,))
 pred = mx.sym.broadcast_add(mx.sym.sparse.dot(data, weight), bias)
 output = mx.sym.LogisticRegressionOutput(pred, label)
 ```

 - update_on_kvstore=True
 ```python
 mod = mx.module.contrib.SparseModule(..., update_on_kvstore=True)
 for batch in batches:
     row_id_generator = lambda x: {'w0': x.data[0].indices}
     **mod.prepare(batch, row_id_generator=row_id_generator)**
     mod.forward(batch)
     mod.backward()
     mod.update()
 ```

 - update_on_kvstore=False
 ```python
 mod = mx.module.contrib.SparseModule(..., update_on_kvstore=False)
 for batch in batches:
     **mod.prepare(batch)**
     mod.forward(batch)
     mod.backward()
     mod.update()
 ```

Which type is recommended? So far only `update_on_kvstore=True` is implemented.
- Memory: `update_on_kvstore=False` in theory leads to higher memory consumption,
   because each device keeps a complete copy of the model.
   For extremely large models that don't fit on a single machine/device,
   keeping a complete copy of the model is not feasible.
- Computation: depends on the operator. For some operators,
   they benefit from the fact that weights are sparse (such as square_sum in factorization machine)
   and do less computation during forward.
   For other operators it might not be the case
   because sparse weight requires extra efforts for lookup/search(such as SparseEmbedding).

#### __init__(..., **update_on_kvstore=None**)
    update_on_kvstore : bool 
        Specifies whether to store a copy of the parameter and perform updates on the KVStore. 
        The value type could be extended to "bool or dict" in the future,
        if we want to support different behavior per parameter, 
        where the keys of the dictionary are the names of parameters, the values are boolean.
        e.g. {'weight_0':False, 'weight_1':True}.

#### prepare(batch, row_id_generator=None)
    Prepare the module for the current data batch. 
    update_on_kvstore=True, their updated values are pulled from the KVStore,
    based on the row ids generated by row_id_generator.

    row_id_generator: a lambda function which takes data_batch as the input, 
          and outputs a dictionary of str->NDArray. The keys in the dict are sparse param names,
          the values are the row_ids to pull for each param.

    Note that the reason why row_id_generator is a function is that users can customize what row ids to provide. It could be the `indices` field from a CSRNDArray, or the input data itself (such as user_id, movie_id). 

#### update
    Update parameters based on the gradients computed by the previous forward/backward.
    If update_on_kvstore=True, it updates the parameters stored in KVStore.
    Otherwise it updates the params stored locally on each device. 

#### init_optimizer
    initialize KVStore and optimizer. 
    There is no guarantee that the parameters on devices are in sync with the ones in KVStore. 
    The sync happens in `prepare()` instead. 

#### save_checkpoint
    if update_on_kvstore=True, need to pull sparse weights before saving the checkpoint.

#### score
    if update_on_kvstore=True, need to pull sparse weights before calling forward. 

#### iter_predict
    if update_on_kvstore=True, need to pull sparse weights before calling forward. 

#### predict
    if update_on_kvstore=True, need to pull sparse weights before calling forward. 

#### fit
    if update_on_kvstore=True, need to pull sparse weights before calling forward. 

#### get_params
    Gets a copy of current parameters.
    If update_on_kvstore=True, need to pull all sparse weights. 

#### save_params
    if update_on_kvstore=True, need to pull all sparse weights.

**Comment by anirudh2290** [comment]
Why do we need both kvstore.row_sparse_pull and kvstore.pull in the example:

```
for batch in batches:
    kvstore.row_sparse_pull(sparse_weight, useful_rows_for_this_batch) 
    kvstore.pull(dense_weights)
    mod.forward(batch)
    mod.backward(batch) 
    mod.update()
        # kvstore.push(grad) 
```

**Comment by eric-haibin-lin** [comment]
Hi @anirudh2290 

Thanks for the comments!!

1. My intention for the following code is that pull/row_sparse_pull should happen when we see a new batch of data. Currently pull works for dense NDArray and row_sparse_pull works for row_sparse NDArray. A network might have both dense and sparse layers and we need to rsp_pull/pull both. 
```
for batch in batches:
    kvstore.row_sparse_pull(sparse_weight, useful_rows_for_this_batch) 
    kvstore.pull(dense_weights)
    mod.forward(batch)
    mod.backward(batch) 
    mod.update()
        # kvstore.push(grad) 
```

2. update_on_kvstore=False doesn't use kvstore to store the actual parameters, but under the hood it's used to aggregate and broadcast gradients. 

3. In that case, you can have a function which doesn't use input data batch at all, such as 
```
def f(batches, ...):
    return {'w': mx.nd.array([1,2,3])} 
```

**Comment by anirudh2290** [comment]
@eric-haibin-lin Thank you ! Can the api be such that it allows to provide static dictionary if needed, to avoid the performance overhead of the lambda function calls when not necessary.

**Comment by saswatac** [comment]
Looks good. Why not add this in module itself instead of contrib?

**Comment by zheng-da** [comment]
I don't understand how much benefit `update_on_kvstore=False` provides. Why does`update_on_kvstore=False` or `update_on_kvstore=True` reduce computation for some operators?

**Comment by eric-haibin-lin** [comment]
@anirudh2290 Yes. It takes any function. So you could have sth like:
```
class A:
    def __init__(self):
        self.dict = {'a': NDArray([1,2,3])}
    def rowids(self):
        return self.dict

and pass `A().rowids` as the function, which returns a cached dict object. 
```

@saswatac Good point. I need to further evaluate how much code I need to change to enable this in the existing Module API. Another thing I didn't think of is that modules like `BucketingModule` depends on the `Module` class, which also has to be updated. 

@zheng-da two benefits `update_on_kvstore=False` provides:
One is that users don't have to provide rowids explicitly, which makes it easier to use. This also helps the case where the model generate random samples as part of the training process and users don't know what rowids to pull before calling forward().
The other is that, for operators such as SparseEmbedding with row_sparse weights, it usually comes with some overhead of constructing a lookup table, or the effort of searching a particular row when weights.indices don't contain all rows. 

======

Note that `update_on_kvstore=False` is not supported by distributed kvstore, I'll try to implement a prototype for `update_on_kvstore=True` first.

**Comment by zheng-da** [comment]
@eric-haibin-lin I agree the first benefit is important. I wonder if we can have forward() to pull required weights from kvstore automatically? to enable this, we'll need the operators that support sparse row weights to tell the executor which rows should be pulled. we probably need to add another attribute to NNVM for these operators.

For the second benefit, I would argue that if you accept maintaining the entire weight matrix in each worker node, you can create an array lookup table (an array that maps row id to the physical location in the row sparse weight matrix) instead of a hashtable to reduce the lookup overhead. Maintaining such an array lookup table requires computation of O(nzr), the number of non-zero rows, for both cleaning the existing table and inserting entries for a new row sparse weight matrix. Maintaining the entire weight matrix in each worker node has similar overhead for updating rows. The lookup table has memory of O(n), instead of O(n * p), the size of the entire weight matrix.

**Comment by eric-haibin-lin** [comment]
@zheng-da Thanks for the comments! For the first point, however, the graph_executor/operators are not aware of the existence of KVStore at all, nor should it be. That will make the backend interface really messy and hard to maintain. 

For the second part, I don't quite understand what the "array lookup table" does. How is it different from a hash table? Also, I don't think any existing sparse operator uses hash table like `std::unordered_map` yet.  Could you elaborate? Are you suggesting keep a copy of the weight matrix in one NDArray `X`, and other NDArray `Y` just use this look up table to access the memory of `X`? I thought of this before and it seems to be very hard to maintain, encourage memory leak/corruption and race conditions..

**Comment by zheng-da** [comment]
@eric-haibin-lin True. We don't need to have graph executor or operators aware of kvstore. What we need to do is to register a function to NNVM for operators. What the function does is to return row ids for given input. The process is kind of similar to shape inference but is called when the inputs are ready. The graph executor calls these functions (if they are available) and accumulates all row ids required for the computation. Some component that is responsible for communicating with kvstore should send these row Ids to kvstore and fetch weights.

What I mean is to use an array to map row ids to the physical location of a row in the row sparse matrix, instead of using a hashtable. My point is that if you want to use `update_on_kvstore=False`, which costs memory of O(n * p), why not use an array to map row ids, which costs memory of O(n)?  It isn't expensive to maintain the map either, in terms of computation. The cost is O(nzr) if you do it correctly. I think maintaining this array map is strictly better than maintaining the entire weight matrix in every worker node, from the perspective of computation and memory overhead.

**Comment by eric-haibin-lin** [comment]
@zheng-da 
I don't quite don't understand how you could save the memory this way. With kvstore, the `row_sparse` weight is stored on a random GPU. To run data parallel on multi-GPUs, you need to obtain a copy of weight in some way (either full copy, or a copy of subset of rows) so that the cuda kernel is executed with data and weight on the same context. Even if you have a O(n) array to may row ids, you still need a copy of the data on the same context.

**Comment by zheng-da** [comment]
yes, we can keep the O(n) array and the subset of rows. Maybe we should discuss this face to face.
