### ISSUE TITLE
how to set epoch_size for distributed training in the current version?

### ISSUE THREAD

**Issue by XiaotaoChen** [apache/incubator-mxnet#9941]
[this docs](http://newdocs.readthedocs.io/en/latest/distributed_training.html) says it's better to set epoch_size explicitly in dist_sync. but haven't tell how to set.
@feiyuvl  said mxnet had remove the epoch_size arg in the current version, So how to guarantee the total iteration of each worker to the same number.

**Comment by Ishitori** [comment]
The documentation you are referring to is quite old and is not updated for a long time. It shouldn't be used anymore.

For a regularly updated version of the docs, see here: https://mxnet.incubator.apache.org/faq/distributed_training.html
