### ISSUE TITLE
Improve dot(csr, row_sparse) on CPU

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9945]
The following benchmark results shows that dot(csr, row_sparse) is slow when non-zeros spread out (credit to Saswata)

### Setup
* instance type: m4.2xlarge
* network: 
```
data = mx.sym.Variable(DATA_NAME, stype='csr')
label = mx.symbol.Variable(LABEL_NAME)

weight = mx.sym.Variable("weight", shape=(feature_dim, 1),stype='row_sparse')
net = mx.sym.sparse.dot(data, weight)
bias = mx.sym.Variable("bias", shape=(1,))
net = mx.sym.broadcast_plus(net, bias)

net = mx.sym.LogisticRegressionOutput(data=net, label=label)
```

* SGD optimizer + local kv store.
* Times measured using mxnet profiler. Times are averages across 50 mini-batches

### Results

Batch_size = 1000, NNZ (per row)= 1000, non-zeros chosen uniformly at random for every row

Dimension | Density  | Time for dot | backward_dot
-- | -- | -- | --
1m | 0.001 |  1,138.187 ms | 45.749 ms
2m | 0.0005 | 1,414.793 ms | 80.441 ms
4m | 0.00025 | 1,587.406 ms | 127.912 ms
8m | 0.00013 | 1,690.223 ms | 177.155 ms

Batch_size = 1000, NNZ (per row)= 1000, all rows have same non zero indices

Dimension | Density | Time for dot | backward_dot
-- | -- | -- | --
1m | 0.001 | 4.206 ms | 39.976 ms
2m | 0.0005 | 4.119 ms | 47.716 ms
4m | 0.00025 | 4.103 ms | 66.480 ms
8m | 0.00013 | 4.125 ms | 97.095 ms

We can see that as non-zero indices spread out, dot(csr, row_sparse) slows down. 

### Current Implementation
Assume dot(A, B)=C where A is a `m` x `n` csr_matrix, B is `n` x `k` row_sparse_array, C is a `m` x `k` dense matrix. Let's say `p` OMP threads are available. 
Each thread is responsible for `m/p` rows in the result matrix. For each row `r` in A, a thread does the following:
It reads the column index of the first non-zero element `z` in the row, and performs a **binary search** in B.indices to see if B contains the corresponding row for dot product. If so, update row `r` in C. After that, the thread performs a **linear scan** in B.indices to search for the next matching non-zero element after `z`. 

When the size of B.indices increases, linear scan quickly becomes the bottleneck. 

### Alternative Implementation
We can build a **hash table** for `B.indices`. This way there's no need to perform binary search or linear scan to see whether an element in the A has its non-zero corresponding row in B. This provides O(1) lookup time, but requires extra time to build the hash table. 
If building hash table becomes the bottleneck when the size of B.indices is large, we can also consider building `p` hash tables in parallel where each hash table `i` stores the indices in range [i*n/p, (i+1)*n/p). Bringing in third-party concurrent hash table such as cuckoohash is another choice but it leads to more dependency.

**Comment by ZiyueHuang** [comment]
working on it

**Comment by eric-haibin-lin** [comment]
Closing this for now. We probably want to revisit it when we plan to support a feature vector of billion dimensions. In that case sort and hash is definitely faster than bitmap
