### ISSUE TITLE
[Doc] Overlapping between footer and the left column + Strange nav-link highlighting

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#9948]
1. Footer looks strange:
See https://mxnet.incubator.apache.org/versions/1.1.0/architecture/index.html and https://mxnet.incubator.apache.org/versions/1.1.0/api/c++/index.html There is overlapping between the footer and the left column.
2. The chosen nav-link is not highlighted. The current behavior is quite strange.
Click "Docs - Architectures" and `Github` is highlighted.
Click "Docs - Tutorials" and  `Gluon` is highlighted.

**Comment by aaronmarkham** [comment]
@thinksanky

**Comment by aaronmarkham** [comment]
I've looked at the footer issue and had some help from a couple of people and we can't figure it out. Seems like it would take removing the customizations on the sphinx nav bars which is a can of worms.

**Comment by aaronmarkham** [comment]
Yes, that would work, but it might make for some weirdness on mobile. It's a workaround for sure.
