### ISSUE TITLE
[OP] LayerNorm in MXNet

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#9950]
## Description

[Layer Normalization](https://arxiv.org/pdf/1607.06450.pdf) is becoming more and more common in deep learning models, especially RNNs. We need to support the layer normalization layer. Although we can implement it by combining the existing symbols, e.g, [Implementation in Sockeye](https://github.com/awslabs/sockeye/blob/master/sockeye/layers.py#L53-L112), the speed and memory cost would be large due to the various broadcasting operators that cannot be calculated inplace. Thus, we need to write our own C++ implementation of this operator.

Some reference implementations:
1. https://github.com/pytorch/pytorch/issues/1959
2. https://github.com/MycChiu/fast-LayerNorm-TF

**Comment by fhieber** [comment]
I think this would be a great addition (also see #6995).

**Comment by tdomhan** [comment]
This would be great to have indeed :)

**Comment by sxjscience** [comment]
Solved in #10029
