### ISSUE TITLE
Latest Windows pre-built binary for R?(MXNet Version 1.1.0)

### ISSUE THREAD

**Issue by FrankLongueira** [apache/incubator-mxnet#9952]
Will the Windows pre-built binary for R be updated to the latest version soon? If not, where can I find the best instructions for building from source?

**Comment by sxjscience** [comment]
@hetong007

**Comment by KishoreKarunakaran** [comment]
is there latest prebuilt mxnet-cu90 binary for win10 (i.e. Mxnet 1.1.0.) So far I was only able to find linux packages [here](https://pypi.python.org/pypi/mxnet-cu90/1.0.0) ?

**Comment by marcoabreu** [comment]
@yzhliu

**Comment by harryprince** [comment]
@FrankLongueira  currently windows prebuild version is support cuda-80

**Comment by ankkhedia** [comment]
@FrankLongueira The windows pre-built binaries has already been updated. Please try the instructions mentioned on official MXNet page on how to install R for Windows.

**Comment by ankkhedia** [comment]
@KishoreKarunakaran The latest prebuilt mxnet-cu90 binary for win10 haas been updated. You can take a look at install instructions. Also the instructions for building it from source has been updates. Feel free to try it out and let  me know if you face any issue.

@sandeep-krishnamurthy  Could you please close this issue as it has been resolved.
