### ISSUE TITLE
Runtime errors during multiple outputs training under Ubuntu

### ISSUE THREAD

**Issue by SamaelChen** [apache/incubator-mxnet#9956]
## Description
Build a multiple output network but cannot train under Ubuntu. Refer https://discuss.mxnet.io/t/runtime-errors-during-multi-label-learning-using-ubuntu-but-not-mac/264

## Environment info (Required)
----------Python Info----------
Version      : 3.6.4
Compiler     : GCC 7.2.0
Build        : ('default', 'Jan 16 2018 18:10:19')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/samael/anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.1.0
Directory    : /home/samael/anaconda3/lib/python3.6/site-packages/mxnet
Commit Hash   : 07a83a0325a3d782513a04f47d711710972cb144
----------System Info----------
Platform     : Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid
system       : Linux
node         : samael-U3000
release      : 4.4.0-116-generic
version      : #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 78
Model name:            Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
Stepping:              3
CPU MHz:               2797.234
CPU max MHz:           3100.0000
CPU min MHz:           400.0000
BogoMIPS:              5183.85
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt retpoline kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0020 sec, LOAD: 1.8534 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0313 sec, LOAD: 0.3726 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0296 sec, LOAD: 1.8140 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0407 sec, LOAD: 2.1261 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0301 sec, LOAD: 0.4480 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0217 sec, LOAD: 0.2630 sec.

Package used (Python/R/Scala/Julia):
(I'm using Python)

## Error Message:
```
<ipython-input-2-9ba35177bffa> in <module>()
     18                 l = nd.slice_axis(y, axis=1, begin=i, end=i+1)
     19                 loss = loss_func(o, l)
---> 20                 loss.backward()
     21         trainer.step(x.shape[0])
     22 

~/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py in backward(self, out_grad, retain_graph, train_mode)
   2000             ctypes.c_int(train_mode),
   2001             ctypes.c_void_p(0),
-> 2002             ctypes.c_void_p(0)))
   2003 
   2004     def tostype(self, stype):

~/anaconda3/lib/python3.6/site-packages/mxnet/base.py in check_call(ret)
    144     """
    145     if ret != 0:
--> 146         raise MXNetError(py_str(_LIB.MXGetLastError()))
    147 
    148 

MXNetError: [09:53:55] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./any.h:286: Check failed: type_ != nullptr The any container is empty requested=N5mxnet10Imperative6AGInfoE

Stack trace returned 10 entries:
[bt] (0) /home/samael/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x192112) [0x7f28d0e07112]
[bt] (1) /home/samael/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x192738) [0x7f28d0e07738]
[bt] (2) /home/samael/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x237700c) [0x7f28d2fec00c]
[bt] (3) /home/samael/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x238e1c3) [0x7f28d30031c3]
[bt] (4) /home/samael/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(MXAutogradBackwardEx+0x527) [0x7f28d2f42287]
[bt] (5) /home/samael/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f28ecb81ec0]
[bt] (6) /home/samael/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f28ecb8187d]
[bt] (7) /home/samael/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f28ecd96dee]
[bt] (8) /home/samael/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7f28ecd97825]
[bt] (9) /home/samael/anaconda3/bin/python(_PyObject_FastCallDict+0x8b) [0x562943a251bb]
```
## Minimum reproducible example
```python
import mxnet as mx
from mxnet import gluon, nd, autograd

class DummyBlock(gluon.Block):
    def __init__(self, **kwargs):
        super(DummyBlock, self).__init__(**kwargs)
        with self.name_scope():
            self.fc1 = gluon.nn.Dense(5)
            self.fc2 = gluon.nn.Dense(5)

    def forward(self, x):
        z1 = self.fc1(x)
        z2 = self.fc2(x)
        return (z1, z2)
X = nd.array([
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0]],
[[0, 1, 0, 0, 0], [1, 0, 0, 0, 0]],
[[0, 0, 1, 0, 0], [0, 0, 0, 0, 1]],
[[0, 0, 0, 1, 0], [0, 0, 1, 0, 0]],
[[0, 0, 0, 0, 1], [0, 0, 0, 1, 0]]
])

Y = nd.array([
[0, 1],
[1, 0],
[2, 4],
[3, 2],
[4, 3]
])
ctx = mx.cpu()
net = DummyBlock()
net.collect_params().initialize(mx.init.Xavier(magnitude=2.24), ctx=ctx)
trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': 0.1})

batch_size = 2
loss_func = gluon.loss.SoftmaxCrossEntropyLoss()
data = gluon.data.DataLoader(gluon.data.ArrayDataset(X, Y), batch_size=batch_size)

for e in range(11):
    for x, y in data:
        x = x.as_in_context(ctx)
        y = y.as_in_context(ctx)
        with autograd.record():
            output = net(x)
            for i, o in enumerate(output):
                l = nd.slice_axis(y, axis=1, begin=i, end=i+1)
                loss = loss_func(o, l)
                loss.backward()
        trainer.step(x.shape[0])

    acc = mx.metric.Accuracy()
    for x, y in data:
        x = x.as_in_context(ctx)
        y = y.as_in_context(ctx)
        output = net(x)
        for i, o in enumerate(output):
            l = nd.slice_axis(y, axis=1, begin=i, end=i+1)
            p = nd.argmax(o, axis=1)
            acc.update(preds=p, labels=l)
    print(acc.get()[1])
```
## Steps to reproduce
(Paste the commands you ran that produced the error.)
Run above scripts in IPython

## What have you tried to solve it?

1. Build from source and reinstall
2. pip install mxnet --pre

**Comment by sxjscience** [comment]
@SamaelChen I've answered the question here https://discuss.gluon.ai/t/topic/4941/2

**Comment by SamaelChen** [comment]
@sxjscience Thanks
