### ISSUE TITLE
R Package Fails to Build since #9882

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9957]
Master build broken since #9882 - although the PR didn't touch anything related to R. 

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/438/pipeline/462

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/439/pipeline

@marcoabreu are you aware of any related changes on CI?

**Comment by jeremiedb** [comment]
DiagrammeR (package dependency used for graph visualisation) has just released 1.0 version in which a function is longer supported. I can open a PR to have this fixed.

**Comment by marcoabreu** [comment]
@jeremiedb thanks a lot for the investigation. That would be great!

**Comment by eric-haibin-lin** [comment]
Thanks @jeremiedb  that will be very helpful unblocking PRs

**Comment by marcoabreu** [comment]
Hello @jeremiedb, I have submitted a temporary fix at https://github.com/apache/incubator-mxnet/pull/9964. Could you upgrade DiagrammeR to 1.0.0 and resolve the breaking changes?

**Comment by szha** [comment]
This seems to be the cause https://github.com/rich-iannone/DiagrammeR/commit/41a70fbcf5ea40f881c26515e839d07ebd726df5#diff-7347fe5a0f184f79ef064e92e3beb297
