### ISSUE TITLE
how to group 2 or more outputs in gluon just like sym.Group()

### ISSUE THREAD

**Issue by HaoLiuHust** [apache/incubator-mxnet#9962]
``` 
def hybrid_forward(self, F, x):
        x = x.astype(np.float32) - 127.5
        x = x * 0.0078125
        fc1 = self.features(x)
        if self.get_feature:
            return fc1
        else:
            # fc1_norm = F.sqrt(F.sum(F.square(fc1), axis=1)).reshape((-1, 1))
            # fc1_normalize = F.broadcast_div(fc1, fc1_norm+1e-6)
            fc1_norm = F.L2Normalization(fc1, mode="instance")
            return [fc1_norm,self.output(fc1_norm)]
```
for example, I want to group 2 outputs, and then split them in loss, how could I do it?  just return a list can not work, it will encounter error in Loss, since forward need symbol or ndarray
@piiswrong

**Comment by HaoLiuHust** [comment]
I can do it in an ugly way...use F.concat, and then slice it

**Comment by piiswrong** [comment]
returning a list should work. What's error?

**Comment by HaoLiuHust** [comment]
the error is "HybridBlock input must be (nested) list of Symbol or NDArray, " \
        "but got %s of type %s"  
I want to pass fc1_norm and output to my custom loss, since my loss need these two, is it possible?

**Comment by orchidmajumder** [comment]
You are using imperative code in the hybrid block. Either you need to move it to make it static code (or code with fixed loop) or not hybridize the loss. In the later case, returning as a list and retrieving the proper value from it should work.

**Comment by HaoLiuHust** [comment]
@orchidmajumder Thanks, get your point
