### ISSUE TITLE
onnx-mxnet pip package prevents gpu use

### ISSUE THREAD

**Issue by jwfromm** [apache/incubator-mxnet#9971]
Using pip to install mxnet-cu90 and onnx-mxnet causes pip to reinstall mxnet, removing GPU support. Changing the order the packages are installed does not address this issue.

**Comment by marcoabreu** [comment]
@KellenSunderland

**Comment by anirudhacharya** [comment]
The onnx import functionality has now been ported into MXNet repo itself under contrib and it does not prevent GPU use. There are GPU tests currently running successfully on the CI piepline. 
This change will ship as part of MXNet v1.2 release. We will EOL the onnx-mxnet pip package after the release. Will close this bug after that.

We should also consider adding "ONNX" as a new label for issues on this repo.

**Comment by marcoabreu** [comment]
> We should also consider adding "ONNX" as a new label for issues on this repo.

Done

**Comment by anirudhacharya** [comment]
@jwfromm The above issue should not exist in the current mxnet v1.2 release. Please reopen the issue if it persists.

@marcoabreu please close this issue
