### ISSUE TITLE
Computing the second derivative

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [apache/incubator-mxnet#9979]
I would like to compute the second derivative like,

```python
from mxnet import nd, autograd

x = nd.array([3.0])
with autograd.record():
    y = x**2
    y.backward()
    z = y.grad**2
    z.backward()
    print(z.grad) # I want to get 2.0 here
```

But I get,
```
MXNetError: [19:58:46] src/imperative/imperative.cc:375: Check failed: !AGInfo::IsNone(*i) Cannot differentiate node because it is not in a computational graph. You need to set is_recording to true or use autograd.record() to save computational graphs for backward. If you want to differentiate the same graph twice, you need to pass retain_graph=True to backward.
```

Is there a way to compute the second derivative?

**Comment by vdantu** [comment]
@aidan-plenert-macdonald : This looks like a question and not an issue in MxNet. Could you please post this on  discuss.mxnet.io . You would have a larger audience to answer your question.

@sandeep-krishnamurthy : Could you label this issue as question.

**Comment by aidan-plenert-macdonald** [comment]
@sxjscience If you tell me how, I can help add support for higher order gradients in more operators

**Comment by sxjscience** [comment]
@lightingghost Thanks a lot! Could you help give the solution to the question in this PR? I'll double confirm with Eric on the current plan of supporting higher order gradient and will inform you ASAP.

**Comment by lightingghost** [comment]
I will suggest using `autograd.grad` for computing second order derivatives. like [here](https://mxnet.apache.org/api/python/autograd/autograd.html) A possible rewriting is 

```
x = nd.array([3.0])
x.attach_grad()
with autograd.record():
    y = x**2
    y_grad = autograd.grad(y, x, create_graph=True, retain_graph=True)[0]
    z = y_grad ** 2
z.backward()
print(z.grad)
```

**Comment by aidan-plenert-macdonald** [comment]
Gave me

```
MXNetError: [12:44:29] src/pass/gradient.cc:187: Operator _backward_power_scalar is non-differentiable because it didn't register FGradient attribute.
```

Which is where I assume the work to get the other operators registered comes in.

**Comment by lightingghost** [comment]
@aidan-plenert-macdonald Yes the similar error I got. It seems second derivative is the feature they are working on.

**Comment by sxjscience** [comment]
@lightingghost @aidan-plenert-macdonald Let's then redirect it to the other PR.
